TRUST: Champ_front_calc_interne Class Reference
Champ_front_calc_interne Class Reference
classe Champ_front_calc_interne
Classe derivee de Champ_front_calc qui represente
le transfert d'un champ_inc d'un cote a l'autre d'une paroi interne.
#include <Champ_front_calc_interne.h>
Public Member Functions
~Champ_front_calc_interne ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Champ_front_calc_interne ()
virtual void completer ()
void mettre_a_jour (double temps)
Mise a jour en temps du champ
On prend juste la trace du champ inconnue au pas de
temps auquel il se situe.
WEC : verifier qu'on prend l'inconnue au bon temps !
const IntTab & face_map () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_front_calc_interne & self_cast (Objet_U &)
static const
Champ_front_calc_interne & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN.
virtual Entree & readOn (Entree &)
Lit le nom d'un champ inconnue a partir d'un flot d'entree.
Cree ensuite le champ de frontiere correspondant qui mettra en relation les deux
cotes de la frontiere interne.
Format:
Champ_front_calc_interne nom_pb nom_bord nom_champ.
Protected Attributes
IntTab face_map_
Detailed Description
classe Champ_front_calc_interne
Classe derivee de Champ_front_calc qui represente
le transfert d'un champ_inc d'un cote a l'autre d'une paroi interne.
Definition at line 38 of file Champ_front_calc_interne.h.
Constructor & Destructor Documentation
Champ_front_calc_interne::~Champ_front_calc_interne ()
Definition at line 35 of file Champ_front_calc_interne.cpp.
Champ_front_calc_interne::Champ_front_calc_interne ()
Definition at line 38 of file Champ_front_calc_interne.cpp.
References Champ_front_calc::set_distant().
{
  set_distant(0);
}
Member Function Documentation
void Champ_front_calc_interne::completer () [virtual]
Reimplemented from Champ_front_calc.
Definition at line 90 of file Champ_front_calc_interne.cpp.
References Cerr, Process::exit(), face_map_, finl, Champ_front_calc::front_dis(), Array_base::NOCOPY_NOINIT, Objet_U::precision_geom, ref_cast, and IntTab::resize().
{
#ifdef MEDCOUPLING_
  using namespace MEDCoupling;
  Champ_front_calc::completer();
// Get barycenters of the concerned faces:
  const Front_VF& fvf = ref_cast(Front_VF, front_dis());
  const Zone_VF& zvf = ref_cast(Zone_VF, fvf.zone_dis());
  const DoubleTab& xv = zvf.xv();
  int nbfaces = fvf.nb_faces();
  if (nbfaces % 2)
    {
      Cerr << "ERROR : Champ_front_calc_interne::completer() - number of faces of the internal boundary is not even!"<< finl;
      Process::exit(1);
    }
  face_map_.resize(nbfaces,Array_base::NOCOPY_NOINIT);
  if (nbfaces>0)
    {
      const int ndim = xv.dimension(1);
      MCAuto<DataArrayDouble> coo(DataArrayDouble::New());
      coo->alloc(nbfaces, ndim);
      for (int i = 0; i < nbfaces; i++)
        {
          int num_f = fvf.num_face(i);
          for (int d = 0; d < ndim; d++)
            coo->setIJSilent(i, d, xv(num_f, d));
        }
      DataArrayInt *cP, *cIP;
      coo->findCommonTuples(Objet_U::precision_geom, 0, cP, cIP);
      int nb_faces_dup = cP->getNumberOfTuples();
      if (nb_faces_dup == nbfaces)
        {
// Faces dupliquees -> singularite au niveau du gap
          MCAuto<DataArrayInt> dsi(cIP->deltaShiftIndex());
          if (!dsi->isUniform(2))
            {
              Cerr << "ERROR : Problem on internal boundary. Some face(s) not duplicated." << finl;
              Process::exit(1);
            }
          const int *p(cP->begin());
          for (int i = 0; i < nbfaces / 2; i++, p += 2)
            {
              face_map_(*p) = *(p + 1);
              face_map_(*(p + 1)) = *p;
            }
        }
      else
        {
// Gap de dimension non-nulle -> on cherche le point
// d'en face le plus proche
          const DoubleVect& face_surfaces = zvf.face_surfaces();
          MCAuto<DataArrayDouble> fnorm(DataArrayDouble::New());
          fnorm->alloc(nbfaces, 1);
          fnorm->fillWithZero();
          double* pfnorm = fnorm->getPointer();
          for (int i = 0; i < nbfaces; i++)
            {
              int num_f = fvf.num_face(i);
              for (int d = 0; d < ndim; d++)
                {
                  pfnorm[i]+=zvf.face_normales(num_f,d);
                  coo->setIJSilent(i, d, xv(num_f, d));
                }
              pfnorm[i]/=face_surfaces(num_f);
            }
          double eps = 1e-10;
          MCAuto<DataArrayInt> Idpos = fnorm->findIdsInRange(1-eps,1+eps);
          MCAuto<DataArrayInt> Idneg = fnorm->findIdsInRange(-1-eps,-1+eps);
          int n1 = Idpos->getNumberOfTuples();
          int n2 = Idneg->getNumberOfTuples();
          if ((n1!=n2) || (n1+n2)!=nbfaces)
            {
              Cerr << "ERROR : Problem on internal boundary. Cannot associate pairs of faces." << finl;
              Process::exit(1);
            }
          MCAuto<DataArrayDouble> coo_pos = coo->selectByTupleId(*Idpos);
          MCAuto<DataArrayDouble> coo_neg = coo->selectByTupleId(*Idneg);
          const int* pIdpos = Idpos->getConstPointer();
          const int* pIdneg = Idneg->getConstPointer();
          MCAuto<DataArrayInt> idx = coo_pos->findClosestTupleId(coo_neg);
          const int* pidx = idx->getConstPointer();
          for (int i=0; i<nbfaces/2; i++)
            {
              int j2 = pIdneg[i];
              int k = pidx[i];
              int j1 = pIdpos[k];
              face_map_(j1) = j2;
              face_map_(j2) = j1;
            }
        }
      cIP->decrRef();
      cP->decrRef();
    }
#endif
}
Objet_U * Champ_front_calc_interne::cree_instance () [static]
Reimplemented from Champ_front_calc.
Definition at line 35 of file Champ_front_calc_interne.cpp.
int Champ_front_calc_interne::duplique () const [virtual]
Reimplemented from Champ_front_calc.
Definition at line 35 of file Champ_front_calc_interne.cpp.
const IntTab& Champ_front_calc_interne::face_map () const [inline]
Definition at line 48 of file Champ_front_calc_interne.h.
References face_map_.
  {
    return face_map_;
  }
const Type_info * Champ_front_calc_interne::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_calc.
Definition at line 35 of file Champ_front_calc_interne.cpp.
const Type_info * Champ_front_calc_interne::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_calc.
Definition at line 35 of file Champ_front_calc_interne.cpp.
void Champ_front_calc_interne::mettre_a_jour (double temps) [virtual]
Mise a jour en temps du champ
On prend juste la trace du champ inconnue au pas de
temps auquel il se situe.
WEC : verifier qu'on prend l'inconnue au bon temps !
Reimplemented from Champ_front_calc.
Definition at line 207 of file Champ_front_calc_interne.cpp.
References DoubleTab::dimension(), face_map_, DoubleTab::nb_dim(), and Champ_front_var_instationnaire::valeurs_au_temps().
{
  Champ_front_calc::mettre_a_jour(temps);
// Swap values (implies a copy)
  DoubleTab& tab=valeurs_au_temps(temps);
  assert(tab.nb_dim() == 2 && tab.dimension(1) == 1);
  DoubleTab tmp(tab);
  for (int i = 0; i < tab.dimension(0); i++)
    tab(i,0) = tmp(face_map_(i),0);
}
Sortie & Champ_front_calc_interne::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_calc.
Definition at line 57 of file Champ_front_calc_interne.cpp.
{
  return os;
}
Entree & Champ_front_calc_interne::readOn (Entree & is) [protected, virtual]
Lit le nom d'un champ inconnue a partir d'un flot d'entree.
Cree ensuite le champ de frontiere correspondant qui mettra en relation les deux
cotes de la frontiere interne.
Format:
Champ_front_calc_interne nom_pb nom_bord nom_champ.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_calc.
Definition at line 80 of file Champ_front_calc_interne.cpp.
References Cerr, and finl.
{
#ifndef MEDCOUPLING_
  Cerr << "Champ_front_calc_interne needs MEDCoupling" << finl;
#endif
  Champ_front_calc::readOn(is);
  return is;
}
Champ_front_calc_interne & Champ_front_calc_interne::self_cast (Objet_U & r) [static]
Reimplemented from Champ_front_calc.
Definition at line 35 of file Champ_front_calc_interne.cpp.
const Champ_front_calc_interne & Champ_front_calc_interne::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_front_calc.
Definition at line 35 of file Champ_front_calc_interne.cpp.
unsigned Champ_front_calc_interne::taille_memoire () const [virtual]
Reimplemented from Champ_front_calc.
Definition at line 35 of file Champ_front_calc_interne.cpp.
Member Data Documentation
IntTab Champ_front_calc_interne::face_map_ [protected]
Definition at line 54 of file Champ_front_calc_interne.h.
Referenced by completer(), face_map(), and mettre_a_jour().
const Type_info Champ_front_calc_interne::info_obj [static]
Reimplemented from Champ_front_calc.
Definition at line 41 of file Champ_front_calc_interne.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_front_calc_interne.h
src/Kernel/Champs/Champ_front_calc_interne.cpp