TRUST: Parser Class Reference
Parser Class Reference
#include <Parser.h>
Public Member Functions
Parser ()
Parser (const Parser &)
~Parser ()
Parser (std::string &, int n=1)
void init_parser ()
void parseString ()
double eval ()
void setVar (const char *sv, double val)
void setVar (const std::string &v, double val)
void setVar (int i, double val)
void setNbVar (int nvar)
void addVar (const char *)
std::string & getString ()
void setString (const std::string &s)
void addCst (const Constante &cst)
void addFunc (const UnaryFunction &f)
void setImpulsion (double tinit, double periode)
Private Member Functions
int test_op_binaire (int type)
double eval (PNode *)
double evalOp (PNode *)
double evalVar (PNode *)
double evalFunc (PNode *)
void parserState0 (StringTokenizer *, pstackPNode *, stackint *)
void parserState1 (StringTokenizer *, pstackPNode *, stackint *)
void parserState2 (StringTokenizer *, pstackPNode *, stackint *)
int searchVar (const std::string &)
int searchVar (const char *)
int searchCst (const std::string &v)
int searchFunc (const std::string &v)
Static Private Member Functions
static int precedence (int)
Private Attributes
int state
double impuls_T
double impuls_t0
double impuls_tn
double impuls_tempo
PNode * root
std::string * str
Variable ** les_var
int maxvar
int ivar
Static Private Attributes
static Constante c_pi
static ListeConstantes les_cst
static ListUnaryFunction unary_func
Detailed Description
Definition at line 33 of file Parser.h.
Constructor & Destructor Documentation
Parser() [1/3]
Parser::Parser ()
Initialise le parser avec une chaine "0" : ne sert a rien !!
Definition at line 28 of file Parser.cpp.
{
  init_parser();
  state=0;
  root=NULL;
  str= new std::string("0");
  maxvar=1;
  ivar=0;
  les_var = new Variable*[maxvar];
  impuls_tn = -1.;
  impuls_T = 1.;
  impuls_t0 = 0.;
  impuls_tempo = 0.;
}
References impuls_T, impuls_t0, impuls_tempo, impuls_tn, init_parser(), ivar, les_var, maxvar, root, state, and str.
Parser() [2/3]
Parser::Parser (const Parser & p)
Definition at line 43 of file Parser.cpp.
{
  init_parser();
  impuls_tn = p.impuls_tn;
  impuls_T = p.impuls_T;
  impuls_t0 = p.impuls_t0;
  impuls_tempo = p.impuls_tempo;
  state=p.state;
  maxvar=p.maxvar;
  ivar=p.ivar;
  root=NULL;
  str= new std::string(*p.str);
  les_var = new Variable*[maxvar];
  for (int i = 0; i < ivar; i++)
    {
      les_var[i] = new Variable(*(p.les_var[i]));
    }
  parseString();
}
References impuls_T, impuls_t0, impuls_tempo, impuls_tn, init_parser(), ivar, les_var, maxvar, parseString(), root, state, and str.
~Parser()
Parser::~Parser ()
Definition at line 147 of file Parser.cpp.
{
  if (root !=NULL) destroy(root);
  for (int i =0; i<ivar; i++)
    delete les_var[i];
  delete str;
  delete[] les_var;
}
References destroy(), ivar, les_var, root, and str.
Parser() [3/3]
Parser::Parser (std::string & s, int n = 1)
Construit un objet Parser avec une chaine specifiee et un nb max de variables a indiquer avec la methode addVar.
Definition at line 69 of file Parser.cpp.
{
  init_parser();
  impuls_tn = -1.;
  impuls_T = 1.;
  impuls_t0 = 0.;
  impuls_tempo = 0.;
  state=0;
  root=NULL;
  str= new std::string(s);
  maxvar=n;
  ivar=0;
  les_var = new Variable*[maxvar];
}
References impuls_T, impuls_t0, impuls_tempo, impuls_tn, init_parser(), ivar, les_var, maxvar, root, state, and str.
Member Function Documentation
addCst()
void Parser::addCst (const Constante & cst)
Definition at line 704 of file Parser.cpp.
{
  les_cst.add(cst);
}
References List_Constante::add(), and les_cst.
Referenced by Parser_U::addCst(), and init_parser().
addFunc()
void Parser::addFunc (const UnaryFunction & f)
Definition at line 709 of file Parser.cpp.
{
  int size = unary_func.size();
  for (int i=0; i<size; i++)
    {
      if (unary_func[i]->getName() == f.getName())
        {
          Cerr << "Function " <<  f.getName() << " has already been defined !" << finl;
          Process::exit();
        }
    }
  DERIV(UnaryFunction)& df = unary_func.add(DERIV(UnaryFunction)());
  df = f;
}
References List_Deriv_UnaryFunction::add(), Cerr, DERIV, Process::exit(), finl, UnaryFunction::getName(), liste::size(), and unary_func.
Referenced by Parser_U::addFunc(), and init_parser().
addVar()
void Parser::addVar (const char * vv)
permet d'ajouter une variable en specifiant sa chaine representative (par ex. : x, y1 etc...)
Definition at line 648 of file Parser.cpp.
{
  if (searchVar(vv)!=-1)
    {
      Cerr<<"Warning in Parser::addVar "<< vv << " already in Parser"<<finl;
      if (strcmp(vv,"x")==0 || strcmp(vv,"y")==0 || strcmp(vv,"z")==0 || strcmp(vv,"t")==0
          || strcmp(vv,"X")==0 || strcmp(vv,"Y")==0 || strcmp(vv,"Z")==0 || strcmp(vv,"T")==0)
        {
          Process::exit();
        }
    }
  if (ivar<maxvar)
    les_var[ivar++] = new Variable(vv);
  else
    {
      Cerr << "Maximum " << maxvar << " variables !! " << finl;
      Process::exit();
    }
}
References Cerr, Process::exit(), finl, ivar, les_var, maxvar, and searchVar().
Referenced by Parser_U::addVar(), Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), and Moyenne_volumique::readOn().
eval() [1/2]
double Parser::eval () inline
Sert a evaluer l'expression mathematique correspondante a la chaine de caracteres. Poru cela il faut avant toute chose construire l'arbre par la methode parseString().
Definition at line 149 of file Parser.h.
{
  return eval(root);
}
References eval(), and root.
Referenced by Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), eval(), Parser_U::eval(), Moyenne_volumique::eval_filtre(), evalFunc(), and evalOp().
eval() [2/2]
double Parser::eval (PNode * node) inline private
< PNode::OP
< PNode::VALUE
< PNode::FUNCTION
< PNode::VAR
Definition at line 201 of file Parser.h.
{
  assert(node!=NULL);
  switch(node->type)
    {
    case 1 :
      return evalOp(node);  //!< PNode::OP
    case 2 :
      return node->nvalue;  //!< PNode::VALUE
    case 3 :
      return evalFunc(node);//!< PNode::FUNCTION
    case 4 :
      return evalVar(node); //!< PNode::VAR
    default:
      Cerr << "method eval : Unknown type for this node !!!" << finl;
      Process::exit();
      return 0;
    }
}
References Cerr, evalFunc(), evalOp(), evalVar(), Process::exit(), finl, PNode::nvalue, and PNode::type.
evalFunc()
double Parser::evalFunc (PNode * node) private
< OC attention, dans node->value c est l'oppose de l'indice de la func dans la liste afin de distinguer operateur binaire (>0) et fonctions unaires (<0> Il est donc necessaire de prendre -node->value ici pour referencer un element de la liste De plus, on rajoute +1 car le zero ne doit pas etre utiliser pour les fonctions
Definition at line 205 of file Parser.cpp.
{
  /* OC : Nouvelle version : */
  if (node->value<=0)
    {
      UnaryFunction& f = unary_func[-node->value-1]; //!< OC attention, dans node->value c est l'oppose de l'indice de la func dans la liste afin de distinguer operateur binaire (>0) et fonctions unaires (<0> Il est donc necessaire de prendre -node->value ici pour referencer un element de la liste De plus, on rajoute +1 car le zero ne doit pas etre utiliser pour les fonctions
//
//
//
      return f.eval(eval(node->left));
    }
  else
    {
      Cerr << "method evalFunc : Unknown func !!!" << finl;
      Process::exit();
      return -1;
    }
}
References Cerr, eval(), UnaryFunction::eval(), Process::exit(), finl, PNode::left, unary_func, and PNode::value.
Referenced by eval().
evalOp()
double Parser::evalOp (PNode * node) private
< ADD
< SUBTRACT
< MULTIPLY
< DIVIDE
< POWER
< LT
< GT
< LE
< GE
< MOD
< MAX
< MIN
< AND
< OR
< EQ
< NEQ
Definition at line 226 of file Parser.cpp.
{
// PL 12/11/2010, reecriture avec switch pour optimisation
  double x = (node->left  != NULL ? eval(node->left)  : 0);
  double y = (node->right != NULL ? eval(node->right) : 0);
  switch (node->value)
    {
    case 0: //!< ADD
      return x + y;
    case 1: //!< SUBTRACT
      return  x - y;
    case 2: //!< MULTIPLY
      return x * y;
    case 3: //!< DIVIDE
      if (y==0)
        {
          Cerr << "Error in the Parser : x/y calculated with y equals 0. You are using a formulae with a division per 0." << finl;
          Process::exit();
        }
      return x/y;
    case 4: //!< POWER
      if (y != (int)(y) && x<0)
        {
          Cerr << "Error in the Parser : x^y calculated with negative value for x and y real." << finl;
          Process::exit();
        }
      return pow(x,y);
    case 5: //!< LT
      return (x<y)?1:0;
    case 6: //!< GT
      return (x>y)?1:0;
    case 7: //!< LE
      return (x<=y)?1:0;
    case 8: //!< GE
      return (x>=y)?1:0;
    case 9: //!< MOD
      return ((int)(x))%((int)(y));
    case 10: //!< MAX
      return (x>y)?x:y;
    case 11: //!< MIN
      return (x<y)?x:y;
    case 12: //!< AND
      return x && y;
    case 13: //!< OR
      return x || y;
    case 14: //!< EQ
      return (x == y);
    case 15: //!< NEQ
      return (x != y);
    default:
      Cerr << "Method evalOp : Unknown op " << (int)node->value << "!!!" << finl;
      Process::exit();
      return 0;
    }
}
References Cerr, eval(), Process::exit(), finl, PNode::left, PNode::right, and PNode::value.
Referenced by eval().
evalVar()
double Parser::evalVar (PNode * node) inline private
Definition at line 154 of file Parser.h.
{
  double value = les_var[node->value]->getValue();
  return value;
}
References Variable::getValue(), les_var, and PNode::value.
Referenced by eval().
getString()
std::string & Parser::getString () inline
Definition at line 95 of file Parser.h.
  {
    return *str;
  }
References str.
Referenced by Parser_U::getString(), parserState0(), parserState1(), and searchVar().
init_parser()
void Parser::init_parser ()
Definition at line 86 of file Parser.cpp.
{
  srand48(1);
  if (unary_func.size()==0)
    {
      Sin SIN;
      Asin ASIN;
      Cos COS;
      Acos ACOS;
      Tan TAN;
      Atan ATAN;
      Ln LN;
      Exp EXP;
      Sqrt SQRT;
      Int INT;
      Erf ERF;
      Rnd RND;
      Cosh COSH;
      Sinh SINH;
      Tanh TANH;
      Atanh ATANH;
      Not NOT;
      Abs ABS;
      Sgn SGN;
      addFunc(SIN);
      addFunc(ASIN);
      addFunc(COS);
      addFunc(ACOS);
      addFunc(TAN);
      addFunc(ATAN);
      addFunc(LN);
      addFunc(EXP);
      addFunc(SQRT);
      addFunc(INT);
      addFunc(ERF);
      addFunc(RND);
      addFunc(COSH);
      addFunc(SINH);
      addFunc(TANH);
      addFunc(NOT);
      addFunc(ABS);
      addFunc(SGN);
      addFunc(ATANH);
      c_pi.nommer(Nom("PI"));
      c_pi.setValue(2*asin(1.));
      addCst(c_pi);
    }
}
References addCst(), addFunc(), c_pi, Constante::nommer(), Constante::setValue(), liste::size(), and unary_func.
Referenced by Parser().
parserState0()
void Parser::parserState0 (StringTokenizer * tokenizer, pstackPNode * ob, stackint * op) private
< OC 01/2005 : Attention, on stocke l'oppose de l'indice trouve afin de bien dissocier les operateurs binaires des fonctions unaires.
Definition at line 325 of file Parser.cpp.
{
  if (tokenizer->type == StringTokenizer::STRING)
    {
      int trouv = searchVar(tokenizer->getSValue());
      if (trouv>-1)
        {
          PNode *node = new PNode();
          node->type = PNode::VAR;
          node->value = trouv;
          ob->push(node);
          state = 2;
        }
      else
        {
          const std::string& func = tokenizer->getSValue();
          trouv = searchFunc(func);
          if (trouv>-1)
            {
              op->push(-trouv); //!< OC 01/2005 : Attention, on stocke l'oppose de l'indice trouve afin de bien dissocier les operateurs binaires des fonctions unaires.
              state = 0;
            }
          else
            {
              trouv = searchCst(func);
              if (trouv>=0)
                {
                  PNode *node = new PNode();
                  node->type = PNode::VALUE;
                  node->nvalue = les_cst(trouv).getValue();
                  ob->push(node);
                  state = 2;
                }
              else
                {
                  Cerr << "Error in Parser::parserState0 during interpretation of the following string :\n ";
                  Cerr << *str << "\n";
                  Cerr << " identifier " << func << " unknown " << finl;
// permet d avoir 0 erreur valgrind avec cppunit
                  root=(PNode*) *(ob->getBase());
                  Cerr << "List of known var "<<finl;
                  for (int i=0; i<ivar; i++)
                    Cerr<<les_var[i]->getString()<< " ";
                  Cerr<<finl;
                  Process::exit();
                }
            }
        }
    }
  else if (tokenizer->type == StringTokenizer::NUMBER)
    {
      PNode* node;
      node = new PNode();
      node->type = PNode::VALUE;
// Cout << "NODE NUMBER = " << PNode::VALUE << finl;
      node->nvalue = tokenizer->getNValue();
      ob->push(node);
      state = 2;
    }
  else if (tokenizer->type ==  StringTokenizer::ADD )
    {
      PNode* node;
      op->push(StringTokenizer::ADD);
      node = new PNode();
      node->type = PNode::VALUE;
      node->nvalue = 0.;
      ob->push(node);
      state = 1;
    }
  else if (tokenizer->type ==  StringTokenizer::SUBTRACT)
    {
      PNode* node;
      op->push(StringTokenizer::SUBTRACT);
      node = new PNode();
      node->type = PNode::VALUE;
      node->nvalue = 0.;
      ob->push(node);
      state = 1;
    }
  else if (tokenizer->type ==  StringTokenizer::GRP )
    {
      op->push(StringTokenizer::GRP);
      state = 0;
    }
}
References StringTokenizer::ADD, Cerr, Process::exit(), finl, StringTokenizer::getNValue(), getString(), StringTokenizer::getSValue(), StringTokenizer::GRP, ivar, les_cst, les_var, StringTokenizer::NUMBER, PNode::nvalue, root, searchCst(), searchFunc(), searchVar(), state, str, StringTokenizer::STRING, StringTokenizer::SUBTRACT, PNode::type, StringTokenizer::type, PNode::VALUE, PNode::value, and PNode::VAR.
Referenced by parseString().
parserState1()
void Parser::parserState1 (StringTokenizer * tokenizer, pstackPNode * ob, stackint * op) private
Definition at line 417 of file Parser.cpp.
{
  if (tokenizer->type == StringTokenizer::STRING)
    {
      int trouv = searchVar(tokenizer->getSValue());
      if (trouv>-1)
        {
// Cerr << "variable = " << trouv << " " << tokenizer->getSValue() << finl;
          PNode *node = new PNode();
          node->type = PNode::VAR;
          node->value = trouv;
          ob->push(node);
          state = 2;
        }
      else
        {
          const std::string& func = tokenizer->getSValue();
          trouv = searchFunc(func);
          if (trouv>-1)
            {
              op->push(-trouv);
              state = 0;
            }
          else
            {
              trouv = searchCst(func);
              if (trouv>=0)
                {
                  PNode *node = new PNode();
                  node->type = PNode::VALUE;
                  node->nvalue = les_cst(trouv).getValue();
                  ob->push(node);
                  state = 2;
                }
              else
                {
                  Cerr << "Error in Parser::parserState1 during interpretation of the following string :\n ";
                  Cerr << *str << "\n";
                  Cerr << " identifier " << func << " unknown !! " << finl;
                  Cerr << "List of known var "<<finl;
                  for (int i=0; i<ivar; i++)
                    Cerr<<les_var[i]->getString()<< " ";
                  Cerr<<finl;
                  Process::exit();
                }
            }
        }
    }
  else if (tokenizer->type == StringTokenizer::NUMBER )
    {
      PNode* node = new PNode();
      node->type = PNode::VALUE;
      node->nvalue = tokenizer->getNValue();
      ob->push(node);
      state = 2;
    }
  else if (tokenizer->type ==StringTokenizer::GRP)
    {
      op->push(StringTokenizer::GRP);
      state = 0;
    }
  else
    {
      Cerr << "state 1 error !! " << finl;
      Process::exit();
    }
}
References Cerr, Process::exit(), finl, StringTokenizer::getNValue(), getString(), StringTokenizer::getSValue(), StringTokenizer::GRP, ivar, les_cst, les_var, StringTokenizer::NUMBER, PNode::nvalue, searchCst(), searchFunc(), searchVar(), state, str, StringTokenizer::STRING, PNode::type, StringTokenizer::type, PNode::VALUE, PNode::value, and PNode::VAR.
Referenced by parseString().
parserState2()
void Parser::parserState2 (StringTokenizer * tokenizer, pstackPNode * ob, stackint * op) private
< c est un operateur binaire
< c est une fonction unaire
< c est un operateur binaire
< c est une fonction unaire
< c est un operateur binaire
< c est une fonction unaire
Definition at line 497 of file Parser.cpp.
{
  int op_read;
  if (test_op_binaire( tokenizer->type))
    {
// case   StringTokenizer::ADD: case StringTokenizer::SUBTRACT : case StringTokenizer::MULTIPLY: case StringTokenizer::DIVIDE: case StringTokenizer::POWER:
      op_read = tokenizer->type;
// Cerr << "op read = " << (char) op_read << finl;
      if (!op->isEmpty())
        {
          int tmpi =  op->peek();
// Cerr << "op tmpi = " <<  (char) tmpi << finl;
          while (precedence(tmpi) >= precedence(op_read) )
            {
              int tmp = op->pop();
// Cerr << "op tmp = " <<  (char) tmp << finl;
              if (test_op_binaire( tmp))  //!< c est un operateur binaire
                {
                  PNode* deux = (PNode*) ob->pop();
                  PNode* un = (PNode*) ob->pop();
                  PNode* node = new PNode();
                  node->type = PNode::OP;
                  node->value=tmp;
                  node->left = un;
                  node->right = deux;
                  ob->push(node);
                }
              else if (tmp<=0) //!< c est une fonction unaire
                {
                  PNode* un = (PNode*) ob->pop();
                  PNode* node = new PNode();
                  node->type=PNode::FUNCTION;
                  node->value=tmp;
                  node->left = un;
                  node->right=NULL;
                  ob->push(node);
                }
              else if ( (tmp == StringTokenizer::GRP) || (tmp == StringTokenizer::ENDGRP) )
                {
                }
              else
                {
                  Cerr << "Unknown operation !!! " << finl;
                  Process::exit();
                  break;
                }
              if (!op->isEmpty()) tmpi =  op->peek();
              else break ;
            }
        }
      op->push(op_read);
      state =1;
    }
  else if (tokenizer->type ==  StringTokenizer::ENDGRP)
    {
      op_read = tokenizer->type;
      if (!op->isEmpty())
        {
          int tmp = op->pop();
          while (tmp != StringTokenizer::GRP )
            {
              if (test_op_binaire(tmp))  //!< c est un operateur binaire
                {
                  PNode* deux = (PNode*) ob->pop();
                  PNode* un = (PNode*) ob->pop();
                  PNode* node = new PNode();
                  node->type = PNode::OP;
                  node->value=tmp;
                  node->left = un;
                  node->right=deux;
                  ob->push(node);
                }
              else if (tmp<=0) //!< c est une fonction unaire
                {
                  PNode* un = (PNode*) ob->pop();
                  PNode* node = new PNode();
                  node->type=PNode::FUNCTION;
                  node->value=tmp;
                  node->left = un;
                  node->right=NULL;
                  ob->push(node);
                }
              else if ( (tmp == StringTokenizer::GRP) || (tmp == StringTokenizer::ENDGRP) )
                {
                }
              else
                {
                  Cerr << "Unknown operation !!! " << finl;
                  Process::exit();
                  break;
                }
              if (!op->isEmpty()) tmp =  op->pop();
              else break ;
            }
        }
      state = 2;
    }
  else if (tokenizer->type == StringTokenizer::EOS)
    {
      while (!op->isEmpty())
        {
// Cout << "fin" << finl;
          int tmp =  op->pop();
          if (test_op_binaire(tmp))//!< c est un operateur binaire
            {
              PNode* deux = (PNode*) ob->pop();
              PNode* un = (PNode*) ob->pop();
              PNode* node = new PNode();
              node->type = PNode::OP;
              node->value=tmp;
              node->left = un;
              node->right=deux;
              ob->push(node);
            }
          else if (tmp<=0) //!< c est une fonction unaire
            {
              PNode* un = (PNode*) ob->pop();
              PNode* node = new PNode();
              node->type=PNode::FUNCTION;
              node->value=tmp;
              node->left = un;
              node->right=NULL;
              ob->push(node);
            }
          else if ( (tmp == StringTokenizer::GRP) || (tmp == StringTokenizer::ENDGRP) )
            {
            }
          else
            {
              Cerr << "Unknown operation !!! " << finl;
              Process::exit();
              break;
            }
        }
      state = 0;
    }
  else
    {
      Cerr << "Error state 2 !!! " <<tokenizer->type<<"  "<<tokenizer->getSValue()<<"  "<<tokenizer->getNValue()<< finl;
      Cerr<<" StringTokenizer::ADD "<<StringTokenizer::ADD<<" StringTokenizer::SUBTRACT "<<StringTokenizer::SUBTRACT<<" StringTokenizer::MULTIPLY "<<StringTokenizer::MULTIPLY;
      Cerr<<" StringTokenizer::DIVIDE "<<StringTokenizer::DIVIDE<<" StringTokenizer::POWER "<<StringTokenizer::POWER<<" StringTokenizer::LT "<<StringTokenizer::LT<<" StringTokenizer::GT "<<StringTokenizer::GT;
      Cerr<<" StringTokenizer::LE "<<StringTokenizer::LE<<" StringTokenizer::GE "<<StringTokenizer::GE<<" StringTokenizer::MOD "<<StringTokenizer::MOD<<" ENDStringTokenizer::GRP "<<StringTokenizer::ENDGRP;
      Cerr<<" StringTokenizer::EOS "<<StringTokenizer::EOS<<" StringTokenizer::NUMBER ";
      Cerr<<StringTokenizer::NUMBER<<" StringTokenizer::STRING "<<StringTokenizer::STRING<<finl;
      Process::exit();
    }
}
References StringTokenizer::ADD, Cerr, StringTokenizer::DIVIDE, StringTokenizer::ENDGRP, StringTokenizer::EOS, Process::exit(), finl, PNode::FUNCTION, StringTokenizer::GE, StringTokenizer::getNValue(), StringTokenizer::getSValue(), StringTokenizer::GRP, StringTokenizer::GT, StringTokenizer::LE, PNode::left, StringTokenizer::LT, StringTokenizer::MOD, StringTokenizer::MULTIPLY, StringTokenizer::NUMBER, PNode::OP, StringTokenizer::POWER, precedence(), PNode::right, state, StringTokenizer::STRING, StringTokenizer::SUBTRACT, test_op_binaire(), PNode::type, StringTokenizer::type, and PNode::value.
Referenced by parseString().
parseString()
void Parser::parseString ()
Construit l'arbre correspondant a la chaine de caracteres. Cet arbre doit etre construit une seule fois et la chaine de caractere est evaluee en parcourant cet arbre par la methode eval() autant de fois qu'on le souhaite.
Definition at line 168 of file Parser.cpp.
{
  if (root!=NULL) destroy(root);
  PSTACK(PNode) st_ob(20);
  STACK(int) st_op(20);
  StringTokenizer tok(*str);
  if (!tok.check_GRP())
    {
      Cerr << "Expression " << *str << " does not contain the same number of opening and closing parenthesis." << finl;
      Process::exit();
    }
  state = 0;
  while ( (tok.nextToken()) != StringTokenizer::EOS)
    {
      switch (state)
        {
        case 0:
          parserState0(&tok,&st_ob,&st_op);
          break;
        case 1:
          parserState1(&tok,&st_ob,&st_op);
          break;
        case 2:
          parserState2(&tok,&st_ob,&st_op);
          break;
        case 3:
          break;
        default :
          break;
        }
    }
  parserState2(&tok,&st_ob,&st_op);
  root = (PNode*) *st_ob.getBase();
}
References Cerr, StringTokenizer::check_GRP(), destroy(), StringTokenizer::EOS, Process::exit(), finl, StringTokenizer::nextToken(), parserState0(), parserState1(), parserState2(), PSTACK, root, STACK, state, and str.
Referenced by Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Parser(), Parser_U::parseString(), and Moyenne_volumique::readOn().
precedence()
int Parser::precedence (int op) static private
Definition at line 283 of file Parser.cpp.
{
  int p=100;
  if (op == StringTokenizer::ADD)
    p=1;
  else if (op == StringTokenizer::SUBTRACT)
    p=2;
  else if (op ==  StringTokenizer::DIVIDE)
    p=3;
  else if (op ==  StringTokenizer::MULTIPLY)
    p=3;
  else if (op ==  StringTokenizer::POWER)
    p=5;
  else if (op ==  StringTokenizer::LT)
    p=0;
  else if (op ==  StringTokenizer::GT)
    p=0;
  else if (op ==  StringTokenizer::LE)
    p=0;
  else if (op ==  StringTokenizer::GE)
    p=0;
  else if (op ==  StringTokenizer::MOD)
    p=0;
  else if (op ==  StringTokenizer::MAX)
    p=0;
  else if (op ==  StringTokenizer::MIN)
    p=0;
  else if (op ==  StringTokenizer::AND)
    p=0;
  else if (op ==  StringTokenizer::OR)
    p=0;
  else if (op ==  StringTokenizer::EQ)
    p=0;
  else if (op ==  StringTokenizer::NEQ)
    p=0;
  else if (op ==  StringTokenizer::GRP)
    p=-1;
  else if (op ==  StringTokenizer::ENDGRP)
    p=-1;
  return p;
}
References StringTokenizer::ADD, StringTokenizer::AND, StringTokenizer::DIVIDE, StringTokenizer::ENDGRP, StringTokenizer::EQ, StringTokenizer::GE, StringTokenizer::GRP, StringTokenizer::GT, StringTokenizer::LE, StringTokenizer::LT, StringTokenizer::MAX, StringTokenizer::MIN, StringTokenizer::MOD, StringTokenizer::MULTIPLY, StringTokenizer::NEQ, StringTokenizer::OR, StringTokenizer::POWER, and StringTokenizer::SUBTRACT.
Referenced by parserState2().
searchCst()
int Parser::searchCst (const std::string & v) private
Definition at line 668 of file Parser.cpp.
{
  LIST_CURSEUR(Constante) curseur(les_cst);
  int i=0;
  Nom nv(v);
  while(curseur)
    {
      Constante& cst = ref_cast(Constante,curseur.valeur());
      std::string ss(cst.le_nom());
      for (auto & c: ss) c = toupper(c);
      if (nv == Nom(ss)) return i;
      ++curseur;
      i++;
    }
  return -1;
}
References Constante::le_nom(), les_cst, LIST_CURSEUR, and ref_cast.
Referenced by parserState0(), and parserState1().
searchFunc()
int Parser::searchFunc (const std::string & v) private
< OC: pour ne pas utiliser le zero car sinon conflit avec la nouvelle numerotation des operateurs binaires.
Definition at line 686 of file Parser.cpp.
{
  LIST_CURSEUR(DERIV(UnaryFunction)) curseur(unary_func);
  int i=0;
  Nom nv(v);
  nv.majuscule();
  while(curseur)
    {
      UnaryFunction& f = curseur.valeur().valeur();
      Nom n2(f.getName());
      n2.majuscule();
      if (nv == n2) return i+1 ; //!< OC: pour ne pas utiliser le zero car sinon conflit avec la nouvelle numerotation des operateurs binaires.
      ++curseur;
      i++;
    }
  return -1;
}
References DERIV, UnaryFunction::getName(), LIST_CURSEUR, Nom::majuscule(), and unary_func.
Referenced by parserState0(), and parserState1().
searchVar() [1/2]
int Parser::searchVar (const char * sv) inline private
Definition at line 183 of file Parser.h.
{
  std::string s(sv);
  for (auto & c: s) c = toupper(c);
  for (int i=0; i<ivar; i++)
    if ((les_var[i]->getString()).compare(s) == 0 ) return i;
  return -1;
}
References compare(), getString(), ivar, and les_var.
searchVar() [2/2]
int Parser::searchVar (const std::string & v) inline private
Definition at line 192 of file Parser.h.
{
  std::string s(v);
  for (auto & c: s) c = toupper(c);
  for (int i=0; i<ivar; i++)
    if ((les_var[i]->getString()).compare(s) == 0 ) return i;
  return -1;
}
References compare(), getString(), ivar, and les_var.
Referenced by addVar(), parserState0(), parserState1(), and setVar().
setImpulsion()
void Parser::setImpulsion (double tinit, double periode) inline
Fixe le temps initial et la periode de la fonction impulsion
Definition at line 111 of file Parser.h.
  {
    impuls_t0 = tinit;
    impuls_T = periode;
    impuls_tn = tinit-periode;
    impuls_tempo = impuls_t0;
  }
References impuls_T, impuls_t0, impuls_tempo, and impuls_tn.
Referenced by Parser_U::setImpulsion().
setNbVar()
void Parser::setNbVar (int nvar)
Fixe le nombre max de variables a indiquer avec la methode addVar.
Definition at line 157 of file Parser.cpp.
{
  if (ivar>0)
    for (int i =0; i<ivar; i++)
      delete les_var[i];
  delete[] les_var;
  maxvar=nvar;
  ivar=0;
  les_var = new Variable*[maxvar];
}
References ivar, les_var, and maxvar.
Referenced by Moyenne_volumique::readOn(), and Parser_U::setNbVar().
setString()
void Parser::setString (const std::string & s) inline
Definition at line 99 of file Parser.h.
  {
    delete str;
    str = new std::string(s);
  }
References str.
Referenced by Moyenne_volumique::readOn(), and Parser_U::setString().
setVar() [1/3]
void Parser::setVar (const char * sv, double val) inline
Fixe la valeur de la variable representee par une chaine sv.
Definition at line 160 of file Parser.h.
{
  setVar(searchVar(sv),val);
}
References searchVar(), and setVar().
Referenced by Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Moyenne_volumique::eval_filtre(), setVar(), and Parser_U::setVar().
setVar() [2/3]
void Parser::setVar (const std::string & v, double val) inline
Fixe la valeur de la variable representee par v.
Definition at line 165 of file Parser.h.
{
  setVar(searchVar(v),val);
}
References searchVar(), and setVar().
setVar() [3/3]
void Parser::setVar (int i, double val) inline
Fixe la valeur de la variable de numero specifie. Ce numero correspondt a l'ordre de l'ajout des variables par la methode addVar().
Definition at line 170 of file Parser.h.
{
  assert(i>-1 && i<ivar);
  les_var[i]->setValue(val);
  /* PL: Assert pour optimiser
     if (i>-1 && i<ivar) les_var[i]->setValue(val);
     else
     {
     Cerr << " Variable number " << i << " does not exist !! " << finl;
     Process::exit();
     }*/
}
References ivar, les_var, and Variable::setValue().
test_op_binaire()
int Parser::test_op_binaire (int type) private
Definition at line 491 of file Parser.cpp.
{
  return ((type == StringTokenizer::ADD )||( type == StringTokenizer::SUBTRACT )||( type == StringTokenizer::MULTIPLY )||( type == StringTokenizer::DIVIDE )||( type == StringTokenizer::POWER )||( type == StringTokenizer::LT )||( type == StringTokenizer::GT )||( type == StringTokenizer::LE )||( type == StringTokenizer::GE )||( type == StringTokenizer::MOD) || ( type == StringTokenizer::MAX) || ( type == StringTokenizer::MIN) || ( type == StringTokenizer::AND)||( type == StringTokenizer::OR)||( type == StringTokenizer::EQ)||( type == StringTokenizer::NEQ));
}
References StringTokenizer::ADD, StringTokenizer::AND, StringTokenizer::DIVIDE, StringTokenizer::EQ, StringTokenizer::GE, StringTokenizer::GT, StringTokenizer::LE, StringTokenizer::LT, StringTokenizer::MAX, StringTokenizer::MIN, StringTokenizer::MOD, StringTokenizer::MULTIPLY, StringTokenizer::NEQ, StringTokenizer::OR, StringTokenizer::POWER, and StringTokenizer::SUBTRACT.
Referenced by parserState2().
Member Data Documentation
c_pi
Constante Parser::c_pi static private
Definition at line 135 of file Parser.h.
Referenced by init_parser().
impuls_T
double Parser::impuls_T private
Definition at line 136 of file Parser.h.
Referenced by Parser(), and setImpulsion().
impuls_t0
double Parser::impuls_t0 private
Definition at line 137 of file Parser.h.
Referenced by Parser(), and setImpulsion().
impuls_tempo
double Parser::impuls_tempo private
Definition at line 139 of file Parser.h.
Referenced by Parser(), and setImpulsion().
impuls_tn
double Parser::impuls_tn private
Definition at line 138 of file Parser.h.
Referenced by Parser(), and setImpulsion().
ivar
int Parser::ivar private
Definition at line 146 of file Parser.h.
Referenced by addVar(), Parser(), parserState0(), parserState1(), searchVar(), setNbVar(), setVar(), and ~Parser().
les_cst
ListeConstantes Parser::les_cst static private
Definition at line 144 of file Parser.h.
Referenced by addCst(), parserState0(), parserState1(), and searchCst().
les_var
Variable** Parser::les_var private
Definition at line 143 of file Parser.h.
Referenced by addVar(), evalVar(), Parser(), parserState0(), parserState1(), searchVar(), setNbVar(), setVar(), and ~Parser().
maxvar
int Parser::maxvar private
Definition at line 146 of file Parser.h.
Referenced by addVar(), Parser(), and setNbVar().
root
PNode* Parser::root private
Definition at line 141 of file Parser.h.
Referenced by eval(), Parser(), parserState0(), parseString(), and ~Parser().
state
int Parser::state private
Definition at line 134 of file Parser.h.
Referenced by Parser(), parserState0(), parserState1(), parserState2(), and parseString().
str
std::string* Parser::str private
Definition at line 142 of file Parser.h.
Referenced by getString(), Parser(), parserState0(), parserState1(), parseString(), setString(), and ~Parser().
unary_func
ListUnaryFunction Parser::unary_func static private
Definition at line 145 of file Parser.h.
Referenced by addFunc(), evalFunc(), init_parser(), and searchFunc().
The documentation for this class was generated from the following files:
src/Kernel/Math/Parser.h
src/Kernel/Math/Parser.cpp