TRUST: Parser_Eval Class Reference
Parser_Eval Class Reference
Classe Parser_Eval
Cette classe a pour fonction d evaleur les valeurs prises par une fonction analytique.
La fonction peut dependre de l espace (x, y, z), du temps (t) et d'un champ parametre (val).
#include <Parser_Eval.h>
Public Member Functions
Vect_Parser_U & fonction ()
Parser_U & parser (int i)
Parser_U & parser (int i) const
void eval_fct (const DoubleVect &positions, DoubleVect &val) const
void eval_fct (const DoubleTab &positions, DoubleTab &val) const
void eval_fct (const DoubleTab &positions, DoubleVect &val, const int &ncomp) const
void eval_fct (const DoubleVect &positions, const double &tps, DoubleVect &val) const
void eval_fct (const DoubleTab &positions, const double &tps, DoubleTab &val) const
void eval_fct (const DoubleTab &positions, const double &tps, DoubleVect &val, const int &ncomp) const
void eval_fct (const DoubleTab &positions, const double &tps, const DoubleTab &val_param, DoubleTab &val) const
void eval_fct (const DoubleTab &positions, const double &tps, const DoubleTab &val_param, DoubleVect &val, const int &ncomp) const
void eval_fct (const DoubleTabs &variables, DoubleTab &val) const
Protected Attributes
Vect_Parser_U fonction_
Detailed Description
Classe Parser_Eval
Cette classe a pour fonction d evaleur les valeurs prises par une fonction analytique.
La fonction peut dependre de l espace (x, y, z), du temps (t) et d'un champ parametre (val).
Definition at line 39 of file Parser_Eval.h.
Member Function Documentation
void Parser_Eval::eval_fct (const DoubleVect & positions, DoubleVect & val) const
Definition at line 27 of file Parser_Eval.cpp.
References Parser_U::eval(), fonction_, parser(), Parser_U::setVar(), DoubleVect::size(), and vect_impl::size().
Referenced by Champ_Don_Fonc_txyz::mettre_a_jour(), Champ_Don_Fonc_xyz::readOn(), Champ_Don_Fonc_xyz::valeur_a(), Champ_Don_Fonc_txyz::valeur_a(), Champ_Don_Fonc_xyz::valeur_a_compo(), Champ_Don_Fonc_txyz::valeur_a_elem_compo(), Champ_Don_Fonc_xyz::valeur_aux(), Champ_Don_Fonc_txyz::valeur_aux(), Champ_Don_Fonc_xyz::valeur_aux_compo(), Champ_Don_Fonc_txyz::valeur_aux_compo(), and Table::valeurs().
{
  int dim = fonction_.size();
  int dimension = positions.size();
  double x,y,z=0;
  x = positions(0);
  y = positions(1);
  if (dimension>2)
    z = positions(2);
  for(int k=0; k<dim; k++)
    {
      Parser_U& fct = parser(k);
      fct.setVar(0,x);
      fct.setVar(1,y);
      if (dimension>2)
        fct.setVar(2,z);
      val(k) = fct.eval();
    }
}
void Parser_Eval::eval_fct (const DoubleTab & positions, DoubleTab & val) const
Definition at line 53 of file Parser_Eval.cpp.
References DoubleTab::dimension(), Parser_U::eval(), fonction_, DoubleTab::nb_dim(), parser(), Parser_U::setVar(), and vect_impl::size().
{
  int pos_size = positions.dimension(0);
  int dim = fonction_.size();
  int nb_dim = val.nb_dim();
  int dimension = positions.dimension(1);
  double x,y,z;
  x=y=z=0.;
  if (nb_dim==1)
    {
      Parser_U& fct = parser(0);
      for (int i=0; i<pos_size; i++)
        {
          x = positions(i,0);
          y = positions(i,1);
          if (dimension>2)
            z = positions(i,2);
// Optimisation
          fct.setVar(0,x); //fct.setVar("x",x);
          fct.setVar(1,y); //fct.setVar("y",y);
          if (dimension>2)
            fct.setVar(2,z); //fct.setVar("z",z);
          val(i) = fct.eval();
        }
    }
  else
    {
      for (int i=0; i<pos_size; i++)
        {
          x = positions(i,0);
          y = positions(i,1);
          if (dimension>2)
            z = positions(i,2);
          for(int k=0; k<dim; k++)
            {
              Parser_U& fct = parser(k);
              fct.setVar(0,x);
              fct.setVar(1,y);
              if (dimension>2)
                fct.setVar(2,z);
              val(i,k) = fct.eval();
            }
        }
    }
}
void Parser_Eval::eval_fct (const DoubleTab & positions, const double & tps, const DoubleTab & val_param, DoubleVect & val, const int & ncomp) const
Definition at line 299 of file Parser_Eval.cpp.
References DoubleTab::dimension(), Parser_U::eval(), parser(), and Parser_U::setVar().
{
  int pos_size = positions.dimension(0);
  int dimension = positions.dimension(1);
  double x,y,z,valp;
  x=y=z=valp=0.;
  Parser_U& fct = parser(ncomp);
  fct.setVar(0,tps);
  for (int i=0; i<pos_size; i++)
    {
      x = positions(i,0);
      y = positions(i,1);
      if (dimension>2)
        z = positions(i,2);
      valp = val_param(i);
      fct.setVar(1,x);
      fct.setVar(2,y);
      if (dimension>2)
        fct.setVar(3,z);
      fct.setVar(4,valp);
      val(i) = fct.eval();
    }
}
void Parser_Eval::eval_fct (const DoubleTab & positions, const double & tps, DoubleTab & val) const
Definition at line 157 of file Parser_Eval.cpp.
References DoubleTab::dimension(), Parser_U::eval(), fonction_, DoubleTab::nb_dim(), parser(), Parser_U::setVar(), and vect_impl::size().
{
  int pos_size = positions.dimension(0);
  int dim = fonction_.size();
  int nb_dim = val.nb_dim();
  int dimension = positions.dimension(1);
  double x,y,z;
  x=y=z=0.;
  if (nb_dim==1)
    {
      Parser_U& fct = parser(0);
      fct.setVar(0,tps); //fct.setVar("t",tps);
      for (int i=0; i<pos_size; i++)
        {
          x = positions(i,0);
          y = positions(i,1);
          if (dimension>2)
            z = positions(i,2);
          fct.setVar(1,x);
          fct.setVar(2,y);
          if (dimension>2)
            fct.setVar(3,z);
          val(i) = fct.eval();
        }
    }
  else
    {
      for (int i=0; i<pos_size; i++)
        {
          x = positions(i,0);
          y = positions(i,1);
          if (dimension>2)
            z = positions(i,2);
          for(int k=0; k<dim; k++)
            {
              Parser_U& fct = parser(k);
              fct.setVar(0,tps);
              fct.setVar(1,x);
              fct.setVar(2,y);
              if (dimension>2)
                fct.setVar(3,z);
              val(i,k) = fct.eval();
            }
        }
    }
}
void Parser_Eval::eval_fct (const DoubleTab & positions, const double & tps, DoubleVect & val, const int & ncomp) const
Definition at line 212 of file Parser_Eval.cpp.
References DoubleTab::dimension(), Parser_U::eval(), parser(), and Parser_U::setVar().
{
  int pos_size = positions.dimension(0);
  int dimension = positions.dimension(1);
  double x,y,z;
  x=y=z=0.;
  Parser_U& fct = parser(ncomp);
  fct.setVar(0,tps);
  for (int i=0; i<pos_size; i++)
    {
      x = positions(i,0);
      y = positions(i,1);
      if (dimension>2)
        z = positions(i,2);
      fct.setVar(1,x);
      fct.setVar(2,y);
      if (dimension>2)
        fct.setVar(3,z);
      val(i) = fct.eval();
    }
}
void Parser_Eval::eval_fct (const DoubleTab & positions, const double & tps, const DoubleTab & val_param, DoubleTab & val) const
Definition at line 241 of file Parser_Eval.cpp.
References DoubleTab::dimension(), Parser_U::eval(), fonction_, DoubleTab::nb_dim(), parser(), Parser_U::setVar(), and vect_impl::size().
{
  int pos_size = positions.dimension(0);
  int dim = fonction_.size();
  int nb_dim = val.nb_dim();
  int dimension = positions.dimension(1);
  double x,y,z,valp;
  x=y=z=valp=0.;
  if (nb_dim==1)
    {
      Parser_U& fct = parser(0);
      fct.setVar(0,tps);
      for (int i=0; i<pos_size; i++)
        {
          x = positions(i,0);
          y = positions(i,1);
          if (dimension>2)
            z = positions(i,2);
          valp = val_param(i);
          fct.setVar(1,x);
          fct.setVar(2,y);
          if (dimension>2)
            fct.setVar(3,z);
          fct.setVar(4,valp);
          val(i) = fct.eval();
        }
    }
  else
    {
      for (int i=0; i<pos_size; i++)
        {
          x = positions(i,0);
          y = positions(i,1);
          if (dimension>2)
            z = positions(i,2);
          for(int k=0; k<dim; k++)
            {
              Parser_U& fct = parser(k);
              valp = val_param(i,k);
              fct.setVar(0,tps);
              fct.setVar(1,x);
              fct.setVar(2,y);
              if (dimension>2)
                fct.setVar(3,z);
              fct.setVar(4,valp);
              val(i,k) = fct.eval();
            }
        }
    }
}
void Parser_Eval::eval_fct (const DoubleVect & positions, const double & tps, DoubleVect & val) const
Definition at line 133 of file Parser_Eval.cpp.
References Parser_U::eval(), fonction_, parser(), Parser_U::setVar(), DoubleVect::size(), and vect_impl::size().
{
  int dim = fonction_.size();
  int dimension = positions.size();
  double x,y,z=0;
  x = positions(0);
  y = positions(1);
  if (dimension>2)
    z = positions(2);
  for(int k=0; k<dim; k++)
    {
      Parser_U& fct = parser(k);
      fct.setVar(0,tps);
      fct.setVar(1,x);
      fct.setVar(2,y);
      if (dimension>2)
        fct.setVar(3,z);
      val(k) = fct.eval();
    }
}
void Parser_Eval::eval_fct (const DoubleTabs & variables, DoubleTab & val) const
Definition at line 328 of file Parser_Eval.cpp.
References DoubleTab::dimension(), Parser_U::eval(), fonction_, DoubleTab::nb_dim(), parser(), Parser_U::setVar(), and vect_impl::size().
{
  int dim;
  int pos_size = val.dimension(0);
  assert(fonction_.size() == 1);
  int nb_dim = val.nb_dim();
  int nbvars = variables.size();
  Parser_U& fct = parser(0);
  if (nb_dim==1)
    {
      for (int i=0; i<pos_size; i++)
        {
          for (int ivar=0; ivar<nbvars; ivar++)
            fct.setVar(ivar,variables[ivar](i));
          val(i) = fct.eval();
        }
    }
  else
    {
      dim = val.dimension(1);
      for (int i=0; i<pos_size; i++)
        {
          for(int k=0; k<dim; k++)
            {
              for (int ivar=0; ivar<nbvars; ivar++)
                fct.setVar(ivar,variables[ivar](i,k));
              val(i,k) = fct.eval();
            }
        }
    }
}
void Parser_Eval::eval_fct (const DoubleTab & positions, DoubleVect & val, const int & ncomp) const
Definition at line 104 of file Parser_Eval.cpp.
References DoubleTab::dimension(), Parser_U::eval(), parser(), and Parser_U::setVar().
{
  int pos_size = positions.dimension(0);
  int dimension = positions.dimension(1);
  double x,y,z;
  x=y=z=0.;
  Parser_U& fct = parser(ncomp);
  for (int i=0; i<pos_size; i++)
    {
      x = positions(i,0);
      y = positions(i,1);
      if (dimension>2)
        z = positions(i,2);
      fct.setVar(0,x);
      fct.setVar(1,y);
      if (dimension>2)
        fct.setVar(2,z);
      val(i) = fct.eval();
    }
}
Vect_Parser_U& Parser_Eval::fonction () [inline]
Definition at line 44 of file Parser_Eval.h.
References fonction_.
Referenced by Table::lire_f(), Table::lire_fxyzt(), Champ_Don_Fonc_xyz::readOn(), and Champ_Don_Fonc_txyz::readOn().
  {
    return fonction_;
  };
Parser_U& Parser_Eval::parser (int i) const [inline]
Definition at line 52 of file Parser_Eval.h.
References fonction_.
  {
    return fonction_[i];
  };
Parser_U& Parser_Eval::parser (int i) [inline]
Definition at line 48 of file Parser_Eval.h.
References fonction_.
Referenced by eval_fct(), and Table::val().
  {
    return fonction_[i];
  };
Member Data Documentation
Vect_Parser_U Parser_Eval::fonction_ [mutable, protected]
Definition at line 81 of file Parser_Eval.h.
Referenced by eval_fct(), fonction(), and parser().
The documentation for this class was generated from the following files:
src/Kernel/Math/Parser_Eval.h
src/Kernel/Math/Parser_Eval.cpp