TRUST: Evaluateur_Source_PolyMAC Class Reference
Evaluateur_Source_PolyMAC Class Reference abstract
#include <Evaluateur_Source_PolyMAC.h>
Public Member Functions
Evaluateur_Source_PolyMAC ()
virtual ~Evaluateur_Source_PolyMAC ()
Evaluateur_Source_PolyMAC (const Evaluateur_Source_PolyMAC &)
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
virtual double calculer_terme_source (int) const =0
virtual void calculer_terme_source (int, DoubleVect &) const =0
Protected Attributes
Ref_Zone_PolyMAC la_zone
Ref_Zone_Cl_PolyMAC la_zcl
Detailed Description
Definition at line 25 of file Evaluateur_Source_PolyMAC.h.
Constructor & Destructor Documentation
Evaluateur_Source_PolyMAC() [1/2]
Evaluateur_Source_PolyMAC::Evaluateur_Source_PolyMAC () inline
Definition at line 42 of file Evaluateur_Source_PolyMAC.h.
{}
~Evaluateur_Source_PolyMAC()
virtual Evaluateur_Source_PolyMAC::~Evaluateur_Source_PolyMAC () inline virtual
Definition at line 29 of file Evaluateur_Source_PolyMAC.h.
{};
Evaluateur_Source_PolyMAC() [2/2]
Evaluateur_Source_PolyMAC::Evaluateur_Source_PolyMAC (const Evaluateur_Source_PolyMAC & eval) inline
Definition at line 44 of file Evaluateur_Source_PolyMAC.h.
  : la_zone(eval.la_zone),la_zcl(eval.la_zcl) {}
Member Function Documentation
associer_zones()
void Evaluateur_Source_PolyMAC::associer_zones (const Zone_dis_base & zone_vdf, const Zone_Cl_dis_base & zone_cl_vdf) inline
Definition at line 47 of file Evaluateur_Source_PolyMAC.h.
{
  la_zone = ref_cast(Zone_PolyMAC, zone_vdf);
  la_zcl = ref_cast(Zone_Cl_PolyMAC, zone_cl_vdf);
  completer();
}
References completer(), la_zcl, la_zone, and ref_cast.
Referenced by Terme_Puissance_Thermique_PolyMAC_Elem::associer_zones(), and Terme_Source_Constituant_PolyMAC_Elem::associer_zones().
calculer_terme_source() [1/2]
virtual double Evaluateur_Source_PolyMAC::calculer_terme_source (int) const pure virtual
Implemented in Eval_Puiss_Th_PolyMAC_Elem, and Eval_Source_C_PolyMAC_Elem.
calculer_terme_source() [2/2]
virtual void Evaluateur_Source_PolyMAC::calculer_terme_source (int , DoubleVect &) const pure virtual
Implemented in Eval_Puiss_Th_PolyMAC_Elem, and Eval_Source_C_PolyMAC_Elem.
completer()
virtual void Evaluateur_Source_PolyMAC::completer () pure virtual
Implemented in Evaluateur_Source_PolyMAC_Elem, and Evaluateur_Source_PolyMAC_Face.
Referenced by associer_zones().
mettre_a_jour()
virtual void Evaluateur_Source_PolyMAC::mettre_a_jour () pure virtual
Implemented in Eval_Puiss_Th_PolyMAC_Elem, and Eval_Source_C_PolyMAC_Elem.
Member Data Documentation
la_zcl
Ref_Zone_Cl_PolyMAC Evaluateur_Source_PolyMAC::la_zcl protected
Definition at line 39 of file Evaluateur_Source_PolyMAC.h.
Referenced by associer_zones().
la_zone
Ref_Zone_PolyMAC Evaluateur_Source_PolyMAC::la_zone protected
Definition at line 38 of file Evaluateur_Source_PolyMAC.h.
Referenced by associer_zones(), Evaluateur_Source_PolyMAC_Elem::completer(), and Evaluateur_Source_PolyMAC_Face::completer().
The documentation for this class was generated from the following file:
src/PolyMAC/Sources/Evaluateur_Source_PolyMAC.h