TRUST: Lecture_Table Class Reference
Lecture_Table Class Reference
: class Lecture_Table
<Description of class Lecture_Table>
#include <Lecture_Table.h>
Public Member Functions
Lecture_Table ()
~Lecture_Table ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & lire_table (Entree &is, Table &la_table)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Lecture_Table & self_cast (Objet_U &)
static const Lecture_Table & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
: class Lecture_Table
<Description of class Lecture_Table>
Definition at line 36 of file Lecture_Table.h.
Constructor & Destructor Documentation
Lecture_Table::Lecture_Table ()
Definition at line 25 of file Lecture_Table.cpp.
Lecture_Table::~Lecture_Table ()
Definition at line 25 of file Lecture_Table.cpp.
Member Function Documentation
Objet_U * Lecture_Table::cree_instance () [static]
Definition at line 25 of file Lecture_Table.cpp.
int Lecture_Table::duplique () const [virtual]
Implements Objet_U.
Definition at line 25 of file Lecture_Table.cpp.
const Type_info * Lecture_Table::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 25 of file Lecture_Table.cpp.
const Type_info * Lecture_Table::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 25 of file Lecture_Table.cpp.
Entree & Lecture_Table::lire_table (Entree & is, Table & la_table)
Definition at line 39 of file Lecture_Table.cpp.
References Cerr, Process::exit(), Objet_U::que_suis_je(), and Table::remplir().
Referenced by Champ_Fonc_MED_Table_Temps::readOn().
{
  const Motcle accolade_ouverte("{");
  const Motcle accolade_fermee("}");
  int i,nb_val;
  Motcle motlu;
  is >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "Error while reading table in "<< que_suis_je() << " \n";
      Cerr << "We expected a " << accolade_ouverte << " instead of \n"
           << motlu;
      Process::exit();
    }
  is >> nb_val;
  DoubleVect param(nb_val);
  DoubleTab tab_valeurs(nb_val, 1);
  for (i=0; i<nb_val; i++)
    is >> param[i];
  for (i=0; i<nb_val; i++)
    is >> tab_valeurs(i, 0);
  la_table.remplir(param,tab_valeurs);
  is >> motlu;
  if (motlu != accolade_fermee)
    {
      Cerr << "Error while reading table in "<< que_suis_je() << " \n";
      Cerr << "We expected a " << accolade_fermee << " instead of \n"
           << motlu;
      Process::exit();
    }
  return is;
}
Sortie & Lecture_Table::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 27 of file Lecture_Table.cpp.
{
  Objet_U::printOn( os );
  return os;
}
Entree & Lecture_Table::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 33 of file Lecture_Table.cpp.
{
  Objet_U::readOn( is );
  return is;
}
Lecture_Table & Lecture_Table::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Definition at line 25 of file Lecture_Table.cpp.
const Lecture_Table & Lecture_Table::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Definition at line 25 of file Lecture_Table.cpp.
unsigned Lecture_Table::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Lecture_Table.cpp.
Member Data Documentation
const Type_info Lecture_Table::info_obj [static]
Reimplemented from Objet_U.
Definition at line 39 of file Lecture_Table.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Lecture_Table.h
src/Kernel/Utilitaires/Lecture_Table.cpp