TRUST: Mod_turb_hyd Class Reference
Mod_turb_hyd Class Reference
Classe Mod_turb_hyd
Classe generique de la hierarchie des modeles de turbulence utilises
par une equation_base
un objet Mod_turb_hyd peut referencer n'importe quel objet derivant de
Mod_turb_hyd_base.
La plupart des methodes appellent les methodes de l'objet Mod_turb_hyd
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;.
#include <Mod_turb_hyd.h>
Public Member Functions
Mod_turb_hyd ()
~Mod_turb_hyd ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Mod_turb_hyd & operator= (const Mod_turb_hyd_base &)
Operateur d'affectation d'un Mod_turb_hyd_base dans
un Mod_turb_hyd.
const Champ_Fonc & viscosite_turbulente () const
Appel a l'objet sous-jacent.
Renvoie la viscosite turbulente.
const Turbulence_paroi & loi_paroi () const
Appel a l'objet sous-jacent.
Renvoie la loi de turbulence sur la paroi.
int preparer_calcul ()
Appel a l'objet sous-jacent.
void mettre_a_jour (double)
Appel a l'objet sous-jacent.
Effectue une mise a jour en temps.
void discretiser ()
Appel a l'objet sous-jacent
Discretise le modele de turbulence.
void completer ()
Appel a l'objet sous-jacent.
int sauvegarder (Sortie &os) const override
Appel a l'objet sous-jacent
Effectue une sauvegarde sur un flot de sortie.
int reprendre (Entree &is) override
Appel a l'objet sous-jacent
Effectue une reprise sur un flot d'entree.
void imprimer (Sortie &os) const
Appel a l'objet sous-jacent.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Deriv_Mod_turb_hyd_base
~Deriv_Mod_turb_hyd_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Mod_turb_hyd_base ()
Deriv_Mod_turb_hyd_base (const Deriv_Mod_turb_hyd_base &)
const Mod_turb_hyd_base & valeur () const
Mod_turb_hyd_base & valeur ()
const Mod_turb_hyd_base * operator-> () const
Mod_turb_hyd_base * operator-> ()
const Deriv_Mod_turb_hyd_base & operator= (const Mod_turb_hyd_base &)
const Deriv_Mod_turb_hyd_base & operator= (const Deriv_Mod_turb_hyd_base &)
operator const Mod_turb_hyd_base & () const
operator Mod_turb_hyd_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Mod_turb_hyd & self_cast (Objet_U &)
static const Mod_turb_hyd & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Mod_turb_hyd_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Mod_turb_hyd_base & self_cast (Objet_U &)
static const Deriv_Mod_turb_hyd_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Mod_turb_hyd_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Lit les specifications d'un modele de turbulence
a partir d'un flot d'entree.
Lit le type de modele, type l'objet et appelle
une lecture specifique (par polymorphisme)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Deriv_Mod_turb_hyd_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Classe Mod_turb_hyd
Classe generique de la hierarchie des modeles de turbulence utilises
par une equation_base
un objet Mod_turb_hyd peut referencer n'importe quel objet derivant de
Mod_turb_hyd_base.
La plupart des methodes appellent les methodes de l'objet Mod_turb_hyd
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;.
Definition at line 40 of file Mod_turb_hyd.h.
Constructor & Destructor Documentation
Mod_turb_hyd()
Mod_turb_hyd::Mod_turb_hyd ()
Definition at line 22 of file Mod_turb_hyd.cpp.
~Mod_turb_hyd()
Mod_turb_hyd::~Mod_turb_hyd ()
Definition at line 22 of file Mod_turb_hyd.cpp.
Member Function Documentation
completer()
void Mod_turb_hyd::completer (void) inline
Appel a l'objet sous-jacent.
Definition at line 241 of file Mod_turb_hyd.h.
{
  valeur().completer();
  valeur().loi_paroi()->completer();
}
References Mod_turb_hyd_base::completer(), Mod_turb_hyd_base::loi_paroi(), and Deriv_Mod_turb_hyd_base::valeur().
cree_instance()
Objet_U * Mod_turb_hyd::cree_instance () static
Definition at line 22 of file Mod_turb_hyd.cpp.
discretiser()
void Mod_turb_hyd::discretiser () inline
Appel a l'objet sous-jacent
Discretise le modele de turbulence.
Definition at line 221 of file Mod_turb_hyd.h.
{
  valeur().discretiser();
}
References Mod_turb_hyd_base::discretiser(), and Deriv_Mod_turb_hyd_base::valeur().
duplique()
int Mod_turb_hyd::duplique () const override virtual
Reimplemented from Deriv_Mod_turb_hyd_base.
Definition at line 22 of file Mod_turb_hyd.cpp.
get_info()
const Type_info * Mod_turb_hyd::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Mod_turb_hyd_base.
Definition at line 22 of file Mod_turb_hyd.cpp.
imprimer()
void Mod_turb_hyd::imprimer (Sortie & os) const inline
Appel a l'objet sous-jacent.
Definition at line 261 of file Mod_turb_hyd.h.
{
  valeur().imprimer(os);
}
References Mod_turb_hyd_base::imprimer(), and Deriv_Mod_turb_hyd_base::valeur().
info()
const Type_info * Mod_turb_hyd::info () static
Definition at line 22 of file Mod_turb_hyd.cpp.
loi_paroi()
const Turbulence_paroi & Mod_turb_hyd::loi_paroi () const inline
Appel a l'objet sous-jacent.
Renvoie la loi de turbulence sur la paroi.
Returns
Turbulence_paroi&
Signification: la loi de turbulence sur la paroi
Contraintes: reference constante
Definition at line 118 of file Mod_turb_hyd.h.
{
  return valeur().loi_paroi();
}
References Mod_turb_hyd_base::loi_paroi(), and Deriv_Mod_turb_hyd_base::valeur().
mettre_a_jour()
void Mod_turb_hyd::mettre_a_jour (double temps) inline
Appel a l'objet sous-jacent.
Effectue une mise a jour en temps.
Definition at line 158 of file Mod_turb_hyd.h.
{
  valeur().mettre_a_jour(temps);
}
References Mod_turb_hyd_base::mettre_a_jour(), and Deriv_Mod_turb_hyd_base::valeur().
operator=()
Mod_turb_hyd & Mod_turb_hyd::operator= (const Mod_turb_hyd_base & x) inline
Operateur d'affectation d'un Mod_turb_hyd_base dans
un Mod_turb_hyd.
Returns
Mod_turb_hyd&
Signification: resultat de l'affectation (*this)
Contraintes:
Definition at line 76 of file Mod_turb_hyd.h.
{
  DERIV(Mod_turb_hyd_base)::operator=(x);
  return *this;
}
References DERIV, and operator=().
Referenced by operator=().
preparer_calcul()
int Mod_turb_hyd::preparer_calcul (void) inline
Appel a l'objet sous-jacent.
Definition at line 137 of file Mod_turb_hyd.h.
{
  return valeur().preparer_calcul();
}
References Mod_turb_hyd_base::preparer_calcul(), and Deriv_Mod_turb_hyd_base::valeur().
printOn()
Sortie & Mod_turb_hyd::printOn (Sortie & s) const override protected virtual
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Mod_turb_hyd_base.
Definition at line 38 of file Mod_turb_hyd.cpp.
{
  return DERIV(Mod_turb_hyd_base)::printOn(s);
}
References DERIV, and printOn().
Referenced by printOn().
readOn()
Entree & Mod_turb_hyd::readOn (Entree & s) override protected virtual
Lit les specifications d'un modele de turbulence
a partir d'un flot d'entree.
Lit le type de modele, type l'objet et appelle
une lecture specifique (par polymorphisme)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Mod_turb_hyd_base.
Definition at line 61 of file Mod_turb_hyd.cpp.
{
// Cerr << " Mod_turb_hyd::readOn" << finl;
  Motcle typ;
  s >> typ;
  Motcle nom1("Modele_turbulence_hyd_");
  nom1 += typ;
  Nom discr=equation().discretisation().que_suis_je();
  if ( typ.debute_par("SOUS_MAILLE") || discr == "VDF_Hyper" || typ.debute_par("LONGUEUR_MELANGE") ||
       (typ == "K_Epsilon_V2")
     )
    {
      if (dimension == 2 && discr != "VDF_Hyper")
        {
          Cerr << "Vous traitez un cas turbulent en dimension 2 avec un modele sous maille" << finl;
          Cerr << "Attention a l'interpretation des resultats !!" << finl;
// exit();
        }
      nom1 += "_";
// les operateurs de diffusion sont communs aux discretisations VEF et VEFP1B
      if (discr=="VEFPreP1B") discr="VEF";
      if (discr=="VDF_Front_Tracking") discr="VDF";
      if (discr=="VEFPreP1B_Front_Tracking") discr="VEF";
      nom1+=discr;
    }
  if (nom1=="MODELE_TURBULENCE_HYD_SOUS_MAILLE_LM_VEF")
    {
      Cerr << "Le mot cle Sous_maille_LM s'appelle desormais Longueur_Melange pour etre coherent en VDF et VEF." << finl;
      Cerr << "Changer votre jeu de donnees." << finl;
      exit();
    }
  DERIV(Mod_turb_hyd_base)::typer(nom1);
  valeur().associer_eqn(equation());
  valeur().associer(equation().zone_dis(), equation().zone_Cl_dis());
  s >> valeur();
  return s;
}
References Mod_turb_hyd_base::associer(), Mod_turb_hyd_base::associer_eqn(), Cerr, Motcle::debute_par(), DERIV, Objet_U::dimension, Equation_base::discretisation(), MorEqn::equation(), Process::exit(), finl, Objet_U::que_suis_je(), Deriv_::typer(), and Deriv_Mod_turb_hyd_base::valeur().
reprendre()
int Mod_turb_hyd::reprendre (Entree & is) inline override virtual
Appel a l'objet sous-jacent
Effectue une reprise sur un flot d'entree.
Returns
int
Signification: code de retour propage
Contraintes:
Reimplemented from Objet_U.
Definition at line 200 of file Mod_turb_hyd.h.
{
  return valeur().reprendre(is);
}
References Mod_turb_hyd_base::reprendre(), and Deriv_Mod_turb_hyd_base::valeur().
sauvegarder()
int Mod_turb_hyd::sauvegarder (Sortie & os) const inline override virtual
Appel a l'objet sous-jacent
Effectue une sauvegarde sur un flot de sortie.
Returns
int
Signification: code de retour propage
Contraintes:
Reimplemented from Objet_U.
Definition at line 179 of file Mod_turb_hyd.h.
{
  return valeur().sauvegarder(os);
}
References Mod_turb_hyd_base::sauvegarder(), and Deriv_Mod_turb_hyd_base::valeur().
self_cast() [1/2]
const Mod_turb_hyd & Mod_turb_hyd::self_cast (const Objet_U & r) static
Definition at line 22 of file Mod_turb_hyd.cpp.
self_cast() [2/2]
Mod_turb_hyd & Mod_turb_hyd::self_cast (Objet_U & r) static
Definition at line 22 of file Mod_turb_hyd.cpp.
taille_memoire()
unsigned Mod_turb_hyd::taille_memoire () const override virtual
Reimplemented from Deriv_Mod_turb_hyd_base.
Definition at line 22 of file Mod_turb_hyd.cpp.
viscosite_turbulente()
const Champ_Fonc & Mod_turb_hyd::viscosite_turbulente () const inline
Appel a l'objet sous-jacent.
Renvoie la viscosite turbulente.
Returns
Champ_Fonc&
Signification: le champ representant la viscosite turbulente
Contraintes: reference constante
Definition at line 98 of file Mod_turb_hyd.h.
{
  return valeur().viscosite_turbulente();
}
References Deriv_Mod_turb_hyd_base::valeur(), and Mod_turb_hyd_base::viscosite_turbulente().
Member Data Documentation
info_obj
const Type_info Mod_turb_hyd::info_obj static
Definition at line 42 of file Mod_turb_hyd.h.
The documentation for this class was generated from the following files:
src/ThHyd/Modele_turbulence_base/Mod_turb_hyd.h
src/ThHyd/Modele_turbulence_base/Mod_turb_hyd.cpp