TRUST: Assembleur_P_PolyMAC Class Reference
Assembleur_P_PolyMAC Class Reference
#include <Assembleur_P_PolyMAC.h>
Public Member Functions
Assembleur_P_PolyMAC ()
~Assembleur_P_PolyMAC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &) override
const Zone_dis_base & zone_dis_base () const override
const Zone_Cl_dis_base & zone_Cl_dis_base () const override
int assembler (Matrice &) override
int assembler_rho_variable (Matrice &, const Champ_Don_base &rho) override
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
int assembler_QC (const DoubleTab &, Matrice &) override
Assemble la matrice de pression pour un fluide quasi compressible
laplacein(P) est remplace par div(grad(P)/rho).
int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u) override
void dimensionner_continuite (matrices_t matrices, int aux_only=0) const override
void assembler_continuite (matrices_t matrices, DoubleTab &secmem, int aux_only=0) const override
DoubleTab norme_continuite () const override
int modifier_secmem (DoubleTab &) override
void modifier_secmem_pour_incr_p (const DoubleTab &press, const double fac, DoubleTab &incr) const override
int modifier_solution (DoubleTab &) override
void completer (const Equation_base &) override
const Equation_base & equation () const
Public Member Functions inherited from Assembleur_base
Assembleur_base ()
~Assembleur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int set_resoudre_increment_pression (int flag)
Definit la valeur du drapeau resoudre_increment_pression_.
Ce drapeau determine si le solveur en pression calcule un increment de
pression entre deux pas de temps ou la pression totale (cela affecte
en particulier le calcul des conditions aux limites).
flag = 0 : resolution en pression
flag = 1 : resolution en increment de pression.
int get_resoudre_increment_pression () const
Renvoie la valeur du drapeau resoudre_increment_pression_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
int set_resoudre_en_u (int flag)
Definit la valeur du drapeau resoudre_en_u__.
Ce drapeau determine si le solveur en pression resou en u ou en rho*u
(cela affecte
en particulier le calcul des conditions aux limites Dirichlet).
flag = 1 : resolution en u
flag = 0 : resolution en rho_u.
int get_resoudre_en_u () const
Renvoie la valeur du drapeau resoudre_en_u_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
virtual int assembler (Matrice &)=0
virtual int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u)
virtual int assembler_rho_variable (Matrice &, const Champ_Don_base &rho)
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
virtual int assembler_QC (const DoubleTab &, Matrice &)
virtual void completer (const Equation_base &)=0
virtual void associer_zone_dis_base (const Zone_dis_base &)=0
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)=0
virtual const Zone_dis_base & zone_dis_base () const =0
virtual const Zone_Cl_dis_base & zone_Cl_dis_base () const =0
virtual int modifier_secmem (DoubleTab &)=0
virtual void modifier_secmem_pour_incr_p (const DoubleTab &press, const double fac, DoubleTab &incr) const
virtual int modifier_solution (DoubleTab &)=0
virtual void dimensionner_continuite (matrices_t matrices, int aux_only=0) const
virtual void assembler_continuite (matrices_t matrices, DoubleTab &secmem, int aux_only=0) const
virtual DoubleTab norme_continuite () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Assembleur_P_PolyMAC & self_cast (Objet_U &)
static const Assembleur_P_PolyMAC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Assembleur_base
static const Type_info * info ()
static Assembleur_base & self_cast (Objet_U &)
static const Assembleur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Assembleur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Equation_base mon_equation
Ref_Zone_PolyMAC la_zone_PolyMAC
Ref_Zone_Cl_PolyMAC la_zone_Cl_PolyMAC
int has_P_ref
int stencil_done
IntVect tab1
IntVect tab2
Detailed Description
Definition at line 31 of file Assembleur_P_PolyMAC.h.
Constructor & Destructor Documentation
Assembleur_P_PolyMAC()
Assembleur_P_PolyMAC::Assembleur_P_PolyMAC ()
Definition at line 39 of file Assembleur_P_PolyMAC.cpp.
~Assembleur_P_PolyMAC()
Assembleur_P_PolyMAC::~Assembleur_P_PolyMAC ()
Definition at line 39 of file Assembleur_P_PolyMAC.cpp.
Member Function Documentation
assembler()
int Assembleur_P_PolyMAC::assembler (Matrice & la_matrice) override virtual
Implements Assembleur_base.
Definition at line 51 of file Assembleur_P_PolyMAC.cpp.
{
  DoubleVect rien;
  return assembler_mat(la_matrice,rien,1,1);
}
References assembler_mat().
Referenced by assembler_QC().
assembler_continuite()
void Assembleur_P_PolyMAC::assembler_continuite (matrices_t matrices, DoubleTab & secmem, int aux_only = 0) const override virtual
Reimplemented from Assembleur_base.
Reimplemented in Assembleur_P_PolyMAC_P0.
Definition at line 213 of file Assembleur_P_PolyMAC.cpp.
{
  const Zone_PolyMAC& zone = la_zone_PolyMAC.valeur();
  const Pb_Multiphase* pbm = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()) : NULL;
  const Conds_lim& cls = la_zone_Cl_PolyMAC->les_conditions_limites();
  const DoubleTab *alpha = pbm ? &pbm->eq_masse.inconnue().valeurs() : NULL, &press = equation().probleme().get_champ("pression").valeurs(),
                   &vit = equation().inconnue().valeurs(), *alpha_rho = pbm ? &pbm->eq_masse.champ_conserve().passe() : NULL, &nf = zone.face_normales();
  const IntTab& fcl = ref_cast(Champ_Face_PolyMAC, mon_equation->inconnue().valeur()).fcl(), &e_f = zone.elem_faces();
  const DoubleVect& ve = zone.volumes(), &pe = zone.porosite_elem(), &fs = zone.face_surfaces(), &vf = zone.volumes_entrelaces();
  int i, j, e, f, fb, n, N = vit.line_size(), m, M = press.line_size(), ne_tot = zone.nb_elem_tot(), d, D = dimension;
  Matrice_Morse *mat_a = alpha ? matrices.at("alpha") : NULL, &mat_p = *matrices.at("pression"), &mat_v = *matrices.at("vitesse");
  DoubleTrav w2, fac(N);
  double ar_tot, acc;
  w2.set_smart_resize(1);
  secmem = 0, fac = 1;
  /* equations sum alpha_k = 1 */
  /* second membre : on multiplie par porosite * volume pour que le systeme en P soit symetrique en cartesien */
  if (!aux_only)
    for (e = 0; e < zone.nb_elem(); e++)
      for (secmem(e) = -pe(e) * ve(e), n = 0; n < N; n++) secmem(e) += pe(e) * ve(e) * (*alpha)(e, n);
  /* matrice */
  if (!aux_only)
    for (e = 0; e < zone.nb_elem(); e++)
      for (n = 0; n < N; n++) (*mat_a)(e, N * e + n) = -pe(e) * ve(e);
  /* equations sur les p_f : continuite du gradient si interne, p = p_f si Neumann, sum_k alpha_k v_k = sum_k alpha_k v_k,imp si Dirichlet */
  for (mat_p.get_set_coeff() = 0, mat_v.get_set_coeff() = 0, e = 0; e < ne_tot; e++)
    for (zone.W2(NULL, e, w2), i = 0; i < w2.dimension(0); i++)
      if ((f = e_f(e, i)) >= zone.nb_faces()) continue; //faces virtuelles
      else if (!fcl(f, 0)) //face interne
        {
          for (acc = 0, j = 0; j < w2.dimension(1); acc+= pe(e) * vf(f) * w2(i, j, 0), j++)
            for (m = 0; m < M; m++) //second membre
              secmem(!aux_only * ne_tot + f, m) -= pe(e) * vf(f) * w2(i, j, 0) * (press(ne_tot + e_f(e, j), m) - press(e, m));
          for (m = 0; m < M; m++) mat_p(M * (!aux_only * ne_tot + f) + m, M * e + m) -= acc;
          for (j = 0; j < w2.dimension(1); j++) //matrice (sauf bords de Meumann)
            if (w2(i, j, 0) && fcl(fb = e_f(e, j), 0) != 1)
              for (m = 0; m <M; m++)
                mat_p(M * (!aux_only * ne_tot + f) + m, M * (ne_tot + fb) + m) += pe(e) * vf(f) * w2(i, j, 0);
        }
      else if (fcl(f, 0) == 1) //Neumann -> egalites p_f = p_imp
        {
          for (m = 0; m < M; m++) secmem(M * (!aux_only * ne_tot + f) + m) = fs(f) * (ref_cast(Neumann, cls[fcl(f, 1)].valeur()).flux_impose(fcl(f, 2), m) - press(ne_tot + f, m));
          for (m = 0; m < M; m++) mat_p(M * (!aux_only * ne_tot + f) + m, M * (ne_tot + f) + m) = fs(f);
        }
      else  //Dirichlet -> egalite flux_tot_imp - flux_tot = 0
        {
          if (M == 1 && N > 1) //une pression, plusieurs vitesses -> on ne peut imposer qu'une ponderation : on choisit celle ocrrespondant aux flux de masse total
            {
              for (ar_tot = 0, n = 0; n < N; n++) ar_tot += (*alpha_rho)(e, n);
              for (n = 0; n < N; n++) fac(n) = (*alpha_rho)(e, n) / ar_tot;
            }
          else if (M != N) abort(); //sinon, il faut autant de pressions que de vitesses
          for (n = 0, m = 0; n < N; n++, m += (M > 1)) secmem(!aux_only * ne_tot + f, m) += vf(f) * fac(n) * vit(f, n);
          if (fcl(f, 0) == 3)
            for (d = 0; d < D; d++)
              for (n = 0, m = 0; n < N; n++, m += (M > 1)) //contrib de la valeur imposee: Dirichlet non homogene seulement
                secmem(!aux_only * ne_tot + f, m) -= vf(f) * fac(n) * nf(f, d) / fs(f) * ref_cast(Dirichlet, cls[fcl(f, 1)].valeur()).val_imp(fcl(f, 2), N * d + n);
          for (n = 0, m = 0; n < N; n++, m += (M > 1)) mat_v(M * (!aux_only * ne_tot + f) + m, N * f + n) -= vf(f) * fac(n);
        }
}
References Process::abort(), Equation_base::champ_conserve(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), Pb_Multiphase::eq_masse, equation(), Zone_Poly_base::face_normales(), Zone_VF::face_surfaces(), Probleme_base::get_champ(), Equation_base::inconnue(), Masse_Multiphase::inconnue(), la_zone_Cl_PolyMAC, la_zone_PolyMAC, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), mon_equation, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Champ_Inc_base::passe(), Zone_VF::porosite_elem(), Equation_base::probleme(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), sub_type, Deriv_Champ_Inc_base::valeur(), Ref_Zone_PolyMAC::valeur(), valeur(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), Zone_VF::volumes(), Zone_VF::volumes_entrelaces(), and Zone_PolyMAC::W2().
assembler_mat()
int Assembleur_P_PolyMAC::assembler_mat (Matrice & la_matrice, const DoubleVect & diag, int incr_pression, int resoudre_en_u) override virtual
Reimplemented from Assembleur_base.
Reimplemented in Assembleur_P_PolyMAC_P0.
Definition at line 63 of file Assembleur_P_PolyMAC.cpp.
{
  set_resoudre_increment_pression(incr_pression);
  set_resoudre_en_u(resoudre_en_u);
  Cerr << "Assemblage de la matrice de pression ... " ;
  statistiques().begin_count(assemblage_sys_counter_);
  la_matrice.typer("Matrice_Morse");
  Matrice_Morse& mat = ref_cast(Matrice_Morse, la_matrice.valeur());
  const Zone_PolyMAC& zone = ref_cast(Zone_PolyMAC, la_zone_PolyMAC.valeur());
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, mon_equation->inconnue().valeur());
  const IntTab& e_f = zone.elem_faces(), &fcl = ch.fcl();
  const DoubleVect& pe = zone.porosite_elem();
  int i, j, e, f, fb, ne = zone.nb_elem(), ne_tot = zone.nb_elem_tot(), nf = zone.nb_faces(), nf_tot = zone.nb_faces_tot();
  DoubleTrav w2; //matrice W2 (de Zone_PolyMAC) par element
  w2.set_smart_resize(1);
  /* 1. stencil de la matrice en pression : seulement au premier passage */
  if (!stencil_done) /* premier passage: calcul */
    {
      IntTrav stencil(0, 2);
      stencil.set_smart_resize(1);
      for (e = 0; e < ne; e++)
        for (stencil.append_line(e, e), i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++) /* blocs "elem-elem" et "elem-face" */
          stencil.append_line(e, ne_tot + f); //toutes les faces (sauf bord de Neumann)
      for (e = 0; e < ne_tot; e++)
        for (zone.W2(NULL, e, w2), i = 0; i < w2.dimension(1); i++) /* blocs "face-elem" et "face-face" */
          if (fcl(f = e_f(e, i), 0) == 1 && f < nf) stencil.append_line(ne_tot + f, ne_tot + f); //Neumann : ligne "dpf = 0"
          else if (f < nf)
            for (stencil.append_line(ne_tot + f, e), j = 0; j < w2.dimension(1); j++) /* sinon : ligne sum w2_{ff'} (pf' - pe) */
              if (w2(i, j, 0)) stencil.append_line(ne_tot + f, ne_tot + e_f(e, j));
      tableau_trier_retirer_doublons(stencil);
      Matrix_tools::allocate_morse_matrix(ne_tot + nf_tot, ne_tot + nf_tot, stencil, mat);
      tab1.ref_array(mat.get_set_tab1()), tab2.ref_array(mat.get_set_tab2());
      stencil_done = 1;
    }
  else /* passages suivants : recyclage */
    {
      mat.get_set_tab1().ref_array(tab1);
      mat.get_set_tab2().ref_array(tab2);
      mat.get_set_coeff().resize(tab2.size()), mat.get_set_coeff() = 0;
      mat.set_nb_columns(ne_tot + nf_tot);
    }
  /* 2. coefficients */
  for (e = 0; e < ne_tot; e++)
    {
      zone.W2(NULL, e, w2); //calcul de W2
      double m_ee = 0, m_fe, m_ef; //coefficients (elem, elem), (elem, face) et (face, elem)
      for (i = 0; i < w2.dimension(0); i++, m_ee += m_ef)
        {
          for (m_ef = 0, m_fe = 0, f = e_f(e, i), j = 0; j < w2.dimension(1); j++)
            if (w2(i, j, 0))
              {
                fb = e_f(e, j);
                if (f < zone.nb_faces() && fcl(f, 0) != 1) mat(ne_tot + f, ne_tot + fb) += pe(e) * w2(i, j, 0); //interne ou Dirichlet
                else if (f < zone.nb_faces() && i == j) mat(ne_tot + f, ne_tot + fb) = 1; //f Neumann : ligne dpf = 0
                m_ef += pe(e) * w2(i, j, 0),  m_fe += pe(e) * w2(i, j, 0); //accumulation dans m_ef, m_fe
              }
          if (e < zone.nb_elem()) mat(e, ne_tot + f) -= m_ef;
          if (f < zone.nb_faces() && fcl(f, 0) != 1) mat(ne_tot + f, e) -= m_fe; //si f non Neumann : coef (face, elem)
        }
      if (e < zone.nb_elem()) mat(e, e) += m_ee; //coeff (elem, elem)
    }
// en l'absence de CLs en pression, on ajoute P(0) = 0 sur le process 0
  has_P_ref=0;
  for (int n_bord=0; n_bord<la_zone_PolyMAC->nb_front_Cl(); n_bord++)
    if (sub_type(Neumann_sortie_libre, la_zone_Cl_PolyMAC->les_conditions_limites(n_bord).valeur()) )
      has_P_ref=1;
  if (!has_P_ref && !Process::me()) mat(0, 0) *= 2;
  statistiques().end_count(assemblage_sys_counter_);
  Cerr << statistiques().last_time(assemblage_sys_counter_) << " s" << finl;
  return 1;
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), assemblage_sys_counter_, Statistiques::begin_count(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), Statistiques::end_count(), Champ_Face_PolyMAC::fcl(), finl, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), has_P_ref, Equation_base::inconnue(), la_zone_Cl_PolyMAC, la_zone_PolyMAC, Statistiques::last_time(), Zone_Cl_dis_base::les_conditions_limites(), Process::me(), mon_equation, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Zone_VF::porosite_elem(), TRUSTVect< _TYPE_ >::ref_array(), ref_cast, TRUSTVect< _TYPE_ >::resize(), Matrice_Morse::set_nb_columns(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTVect< _TYPE_ >::size(), statistiques(), stencil_done, sub_type, tab1, tab2, tableau_trier_retirer_doublons(), Deriv_::typer(), Deriv_Champ_Inc_base::valeur(), Deriv_Cond_lim_base::valeur(), Deriv_Matrice_Base::valeur(), Ref_Zone_PolyMAC::valeur(), and Zone_PolyMAC::W2().
Referenced by assembler().
assembler_QC()
int Assembleur_P_PolyMAC::assembler_QC (const DoubleTab & tab_rho, Matrice & matrice) override virtual
Assemble la matrice de pression pour un fluide quasi compressible
laplacein(P) est remplace par div(grad(P)/rho).
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 157 of file Assembleur_P_PolyMAC.cpp.
{
  Cerr << "Assemblage de la matrice de pression pour Quasi Compressible en cours..." << finl;
  assembler(matrice);
  set_resoudre_increment_pression(1);
  set_resoudre_en_u(0);
  abort();
  Matrice_Bloc& matrice_bloc= ref_cast(Matrice_Bloc,matrice.valeur());
  Matrice_Morse_Sym& la_matrice =ref_cast(Matrice_Morse_Sym,matrice_bloc.get_bloc(0,0).valeur());
  if ((la_matrice.get_est_definie()!=1)&&(1))
    {
      Cerr<<"Pas de pression imposee  --> P(0)=0"<<finl;
      if (je_suis_maitre())
        la_matrice(0,0) *= 2;
      la_matrice.set_est_definie(1);
    }
  Cerr << "Fin de l'assemblage de la matrice de pression" << finl;
  return 1;
}
References Process::abort(), assembler(), Cerr, finl, Matrice_Bloc::get_bloc(), Matrice_Sym::get_est_definie(), Process::je_suis_maitre(), ref_cast, Matrice_Sym::set_est_definie(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), and Deriv_Matrice_Base::valeur().
assembler_rho_variable()
int Assembleur_P_PolyMAC::assembler_rho_variable (Matrice & mat, const Champ_Don_base & rho) override virtual
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
Reimplemented from Assembleur_base.
Definition at line 57 of file Assembleur_P_PolyMAC.cpp.
{
  abort();
  return 0;
}
References Process::abort().
associer_zone_cl_dis_base()
void Assembleur_P_PolyMAC::associer_zone_cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis) override virtual
Implements Assembleur_base.
Definition at line 321 of file Assembleur_P_PolyMAC.cpp.
{
  la_zone_Cl_PolyMAC = ref_cast(Zone_Cl_PolyMAC, la_zone_Cl_dis);
}
References la_zone_Cl_PolyMAC, and ref_cast.
associer_zone_dis_base()
void Assembleur_P_PolyMAC::associer_zone_dis_base (const Zone_dis_base & la_zone_dis) override virtual
Implements Assembleur_base.
Definition at line 316 of file Assembleur_P_PolyMAC.cpp.
{
  la_zone_PolyMAC = ref_cast(Zone_PolyMAC,la_zone_dis);
}
References la_zone_PolyMAC, and ref_cast.
completer()
void Assembleur_P_PolyMAC::completer (const Equation_base & Eqn) override virtual
Implements Assembleur_base.
Definition at line 326 of file Assembleur_P_PolyMAC.cpp.
{
  mon_equation=Eqn;
  stencil_done = 0;
}
References mon_equation, and stencil_done.
cree_instance()
Objet_U * Assembleur_P_PolyMAC::cree_instance () static
Definition at line 39 of file Assembleur_P_PolyMAC.cpp.
dimensionner_continuite()
void Assembleur_P_PolyMAC::dimensionner_continuite (matrices_t matrices, int aux_only = 0) const override virtual
Reimplemented from Assembleur_base.
Reimplemented in Assembleur_P_PolyMAC_P0.
Definition at line 179 of file Assembleur_P_PolyMAC.cpp.
{
  const Zone_PolyMAC& zone = la_zone_PolyMAC.valeur();
  int i, j, e, f, fb, n, N = equation().inconnue().valeurs().line_size(), m, M = equation().get_champ("pression").valeurs().line_size(),
                         ne_tot = zone.nb_elem_tot(), nf_tot = zone.nb_faces_tot();
  const IntTab& fcl = ref_cast(Champ_Face_PolyMAC, mon_equation->inconnue().valeur()).fcl(), &e_f = zone.elem_faces();
  IntTrav sten_a(0, 2), sten_p(0, 2), sten_v(0, 2);
  DoubleTrav w2;
  sten_a.set_smart_resize(1), sten_p.set_smart_resize(1), sten_v.set_smart_resize(1), w2.set_smart_resize(1);
  /* equations sum alpha_k = 1 */
  if (!aux_only)
    for (e = 0; e < zone.nb_elem(); e++)
      for (n = 0; n < N; n++) sten_a.append_line(e, N * e + n);
  /* equations sur les p_f : continuite du gradient si interne, p = p_f si Neumann, sum_k alpha_k v_k = sum_k alpha_k v_k,imp si Dirichlet */
  for (e = 0; e < zone.nb_elem_tot(); e++)
    for (zone.W2(NULL, e, w2), i = 0; i < w2.dimension(0); i++)
      if ((f = e_f(e, i)) >= zone.nb_faces()) continue; //faces virtuelles
      else if (!fcl(f, 0))
        for (sten_p.append_line(!aux_only * ne_tot + f, e), j = 0; j < w2.dimension(1); j++) //face interne
          {
            if (w2(i, j, 0) && fcl(fb = e_f(e, j), 0) != 1)
              for (m = 0; m < M; m++)
                sten_p.append_line(M * (!aux_only * ne_tot + f) + m, M * (ne_tot + fb) + m);
          }
      else if (fcl(f, 0) == 1)
        for (m = 0; m < M; m++) sten_p.append_line(M * (!aux_only * ne_tot + f) + m, M * (ne_tot + f) + m); //Neumann
      else for (n = 0, m = 0; n < N; n++, m += (M > 1)) sten_v.append_line(M * (!aux_only * ne_tot + f) + m, N * f + n); //Dirichlet
  tableau_trier_retirer_doublons(sten_v), tableau_trier_retirer_doublons(sten_p);
  if (!aux_only) Matrix_tools::allocate_morse_matrix(ne_tot + nf_tot, N * ne_tot, sten_a, *matrices.at("alpha"));
  Matrix_tools::allocate_morse_matrix(M * (!aux_only * ne_tot + nf_tot), M * (ne_tot + nf_tot), sten_p, *matrices.at("pression"));
  Matrix_tools::allocate_morse_matrix(M * (!aux_only * ne_tot + nf_tot), equation().inconnue()->valeurs().size_totale(), sten_v, *matrices.at("vitesse"));
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), equation(), Equation_base::get_champ(), Equation_base::inconnue(), la_zone_PolyMAC, TRUSTVect< _TYPE_ >::line_size(), mon_equation, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), tableau_trier_retirer_doublons(), Deriv_Champ_Inc_base::valeur(), Ref_Zone_PolyMAC::valeur(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), and Zone_PolyMAC::W2().
duplique()
int Assembleur_P_PolyMAC::duplique () const override virtual
Implements Objet_U.
Reimplemented in Assembleur_P_PolyMAC_P0.
Definition at line 39 of file Assembleur_P_PolyMAC.cpp.
equation()
const Equation_base & Assembleur_P_PolyMAC::equation () const inline
Definition at line 67 of file Assembleur_P_PolyMAC.h.
{
  return  mon_equation.valeur();
}
References mon_equation, and Ref_Equation_base::valeur().
Referenced by assembler_continuite(), Assembleur_P_PolyMAC_P0::assembler_continuite(), Assembleur_P_PolyMAC_P0::assembler_mat(), dimensionner_continuite(), Assembleur_P_PolyMAC_P0::dimensionner_continuite(), and modifier_secmem_pour_incr_p().
get_info()
const Type_info * Assembleur_P_PolyMAC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Assembleur_base.
Reimplemented in Assembleur_P_PolyMAC_P0.
Definition at line 39 of file Assembleur_P_PolyMAC.cpp.
info()
const Type_info * Assembleur_P_PolyMAC::info () static
Definition at line 39 of file Assembleur_P_PolyMAC.cpp.
modifier_secmem()
int Assembleur_P_PolyMAC::modifier_secmem (DoubleTab &) inline override virtual
Implements Assembleur_base.
Definition at line 47 of file Assembleur_P_PolyMAC.h.
  {
    return 1;
  }
modifier_secmem_pour_incr_p()
void Assembleur_P_PolyMAC::modifier_secmem_pour_incr_p (const DoubleTab & press, const double fac, DoubleTab & incr) const override virtual
Reimplemented from Assembleur_base.
Reimplemented in Assembleur_P_PolyMAC_P0.
Definition at line 277 of file Assembleur_P_PolyMAC.cpp.
{
  const Zone_PolyMAC& zone = ref_cast(Zone_PolyMAC, la_zone_PolyMAC.valeur());
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, mon_equation->inconnue().valeur());
  const Conds_lim& cls = la_zone_Cl_PolyMAC->les_conditions_limites();
  const IntTab& fcl = ch.fcl();
  int f, ne_tot = zone.nb_elem_tot(), m, M = equation().probleme().get_champ("pression").valeurs().line_size();
  for (f = 0; f < zone.premiere_face_int(); f++)
    if (fcl(f, 0) == 1)
      for (m = 0; m < M; m++)
        secmem(ne_tot + f, m) = (ref_cast(Neumann_sortie_libre, cls[fcl(f, 1)].valeur()).flux_impose(fcl(f, 2), m) - press(ne_tot + f, m)) / fac;
}
References equation(), Champ_Face_PolyMAC::fcl(), Probleme_base::get_champ(), Equation_base::inconnue(), la_zone_Cl_PolyMAC, la_zone_PolyMAC, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), mon_equation, Zone_dis_base::nb_elem_tot(), Zone_VF::premiere_face_int(), Equation_base::probleme(), ref_cast, Deriv_Champ_Inc_base::valeur(), Ref_Zone_PolyMAC::valeur(), valeur(), and Champ_Proto::valeurs().
modifier_solution()
int Assembleur_P_PolyMAC::modifier_solution (DoubleTab & pression) override virtual
Implements Assembleur_base.
Definition at line 299 of file Assembleur_P_PolyMAC.cpp.
{
  Debog::verifier("pression dans modifier solution in",pression);
  if(!has_P_ref) pression -= mp_min_vect(pression);
  return 1;
}
References has_P_ref, mp_min_vect(), and Debog::verifier().
norme_continuite()
DoubleTab Assembleur_P_PolyMAC::norme_continuite () const override virtual
Reimplemented from Assembleur_base.
Definition at line 291 of file Assembleur_P_PolyMAC.cpp.
{
  const DoubleVect& pe= la_zone_PolyMAC->porosite_elem(), &ve = la_zone_PolyMAC->volumes();
  DoubleTab norm(la_zone_PolyMAC->nb_elem());
  for (int e = 0; e < la_zone_PolyMAC->nb_elem(); e++) norm(e) = pe(e) * ve(e);
  return norm;
}
References la_zone_PolyMAC, Zone_dis_base::nb_elem(), Zone_VF::porosite_elem(), and Zone_VF::volumes().
printOn()
Sortie & Assembleur_P_PolyMAC::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Assembleur_base.
Reimplemented in Assembleur_P_PolyMAC_P0.
Definition at line 41 of file Assembleur_P_PolyMAC.cpp.
{
  return s << que_suis_je() << " " << le_nom() ;
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Assembleur_P_PolyMAC::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Assembleur_base.
Reimplemented in Assembleur_P_PolyMAC_P0.
Definition at line 46 of file Assembleur_P_PolyMAC.cpp.
{
  return Assembleur_base::readOn(s);
}
References Assembleur_base::readOn().
Referenced by Assembleur_P_PolyMAC_P0::readOn().
self_cast() [1/2]
const Assembleur_P_PolyMAC & Assembleur_P_PolyMAC::self_cast (const Objet_U & r) static
Definition at line 39 of file Assembleur_P_PolyMAC.cpp.
self_cast() [2/2]
Assembleur_P_PolyMAC & Assembleur_P_PolyMAC::self_cast (Objet_U & r) static
Definition at line 39 of file Assembleur_P_PolyMAC.cpp.
taille_memoire()
unsigned Assembleur_P_PolyMAC::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Assembleur_P_PolyMAC_P0.
Definition at line 39 of file Assembleur_P_PolyMAC.cpp.
zone_Cl_dis_base()
const Zone_Cl_dis_base & Assembleur_P_PolyMAC::zone_Cl_dis_base () const override virtual
Implements Assembleur_base.
Definition at line 311 of file Assembleur_P_PolyMAC.cpp.
{
  return la_zone_Cl_PolyMAC.valeur();
}
References la_zone_Cl_PolyMAC, and Ref_Zone_Cl_PolyMAC::valeur().
zone_dis_base()
const Zone_dis_base & Assembleur_P_PolyMAC::zone_dis_base () const override virtual
Implements Assembleur_base.
Definition at line 306 of file Assembleur_P_PolyMAC.cpp.
{
  return la_zone_PolyMAC.valeur();
}
References la_zone_PolyMAC, and Ref_Zone_PolyMAC::valeur().
Member Data Documentation
has_P_ref
int Assembleur_P_PolyMAC::has_P_ref protected
Definition at line 62 of file Assembleur_P_PolyMAC.h.
Referenced by assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), and modifier_solution().
info_obj
const Type_info Assembleur_P_PolyMAC::info_obj static
Definition at line 33 of file Assembleur_P_PolyMAC.h.
la_zone_Cl_PolyMAC
Ref_Zone_Cl_PolyMAC Assembleur_P_PolyMAC::la_zone_Cl_PolyMAC protected
Definition at line 61 of file Assembleur_P_PolyMAC.h.
Referenced by assembler_continuite(), assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), associer_zone_cl_dis_base(), modifier_secmem_pour_incr_p(), and zone_Cl_dis_base().
la_zone_PolyMAC
Ref_Zone_PolyMAC Assembleur_P_PolyMAC::la_zone_PolyMAC protected
Definition at line 60 of file Assembleur_P_PolyMAC.h.
Referenced by assembler_continuite(), Assembleur_P_PolyMAC_P0::assembler_continuite(), assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), associer_zone_dis_base(), dimensionner_continuite(), Assembleur_P_PolyMAC_P0::dimensionner_continuite(), modifier_secmem_pour_incr_p(), norme_continuite(), and zone_dis_base().
mon_equation
Ref_Equation_base Assembleur_P_PolyMAC::mon_equation protected
Definition at line 59 of file Assembleur_P_PolyMAC.h.
Referenced by assembler_continuite(), assembler_mat(), completer(), dimensionner_continuite(), equation(), and modifier_secmem_pour_incr_p().
stencil_done
int Assembleur_P_PolyMAC::stencil_done protected
Definition at line 63 of file Assembleur_P_PolyMAC.h.
Referenced by assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), and completer().
tab1
IntVect Assembleur_P_PolyMAC::tab1 protected
Definition at line 64 of file Assembleur_P_PolyMAC.h.
Referenced by assembler_mat(), and Assembleur_P_PolyMAC_P0::assembler_mat().
tab2
IntVect Assembleur_P_PolyMAC::tab2 protected
Definition at line 64 of file Assembleur_P_PolyMAC.h.
Referenced by assembler_mat(), and Assembleur_P_PolyMAC_P0::assembler_mat().
The documentation for this class was generated from the following files:
src/PolyMAC/Solveurs/Assembleur_P_PolyMAC.h
src/PolyMAC/Solveurs/Assembleur_P_PolyMAC.cpp