TRUST: Champ_P1NC Class Reference
Champ_P1NC Class Reference
#include <Champ_P1NC.h>
Public Member Functions
Champ_P1NC ()
~Champ_P1NC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps du champ inconnue.
WEC : Maintenant si on l'appelle 2 fois de suite avec le meme
argument, la 2eme ne fait rien.
void abortTimeStep () override
const Zone_dis_base & zone_dis_base () const override
void associer_zone_dis_base (const Zone_dis_base &) override
const Zone_VEF & zone_vef () const override
int compo_normale_sortante (int) const
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
void cal_rot_ordre1 (DoubleTab &) const
void gradient (DoubleTab &) const
int imprime (Sortie &, int) const override
void calcul_critere_Q (DoubleVect &) const
void calcul_y_plus (const Zone_Cl_VEF &, DoubleVect &) const
void calcul_grad_T (const Zone_Cl_VEF &, DoubleTab &) const
void calcul_grad_U (const Zone_Cl_VEF &, DoubleTab &) const
void calcul_h_conv (const Zone_Cl_VEF &, DoubleTab &, int temp_ref) const
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
double valeur_a_sommet_compo (int num_som, int le_poly, int ncomp) const override
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &tab_valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &tab_valeurs, int ncomp) const override
DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &tab_valeurs) override
DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &tab_valeurs, int ncomp) override
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const override
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
NE FAIT RIEN
Methode a surcharger.
void filtrer_L2 (DoubleTab &) const
void filtrer_H1 (DoubleTab &) const
void filtrer_resu (DoubleTab &) const
virtual double norme_L2 (const Domaine &) const
Champ_base & affecter_ (const Champ_base &) override
Affectation d'un Champ generique (Champ_base) dans
un champ inconnue.
void verifie_valeurs_cl () override
virtual double norme_H1 (const Domaine &) const
virtual double norme_L2_H1 (const Domaine &dom) const
Public Member Functions inherited from Champ_Inc_base
~Champ_Inc_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_Inc_base ()
int fixer_nb_valeurs_nodales (int) override
double changer_temps (const double temps) override
Fixe le temps du champ.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps du champ inconnue.
WEC : Maintenant si on l'appelle 2 fois de suite avec le meme
argument, la 2eme ne fait rien.
int reprendre (Entree &) override
Lecture d'un champ inconnue a partir d'un flot d'entree
en vue d'une reprise.
int sauvegarder (Sortie &) const override
Sauvegarde le champ inconnue sur un flot de sortie.
Ecrit un identifiant, les valeurs du champs, et
la date (le temps au moment de la sauvegarde).
Champ_base & affecter_compo (const Champ_base &, int compo) override
Affectation d'une composante d'un Champ quelconque<br>(Champ_base) dans une composante d'un champ inconnue.
Champ_base & affecter_ (const Champ_base &) override
Affectation d'un Champ generique (Champ_base) dans
un champ inconnue.
virtual void verifie_valeurs_cl ()
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ au temps courant.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temp courant<br>(version const)
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
Calcule la valeur du champs inconnue a la position specifiee.
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
Calcule les valeurs du champs inconnue aux positions specifiees.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
Calcule les valeurs du champs inconnue aux positions specifiees,
pour une certaine composante du champ.
int nb_valeurs_nodales () const override
Returns the number of "real" geometric positions of the
degrees of freedom, or -1 if not applicable (fields with multiple
localisations)
virtual int fixer_nb_valeurs_temporelles (int)
Fixe le nombre de valeurs temporelles a conserver.
(un nombre different suivant le schema en temps utilise)
Appelle Roue::fixer_nb_cases(int)
virtual int nb_valeurs_temporelles () const
Renvoie le nombre de valeurs temporelles actuellement conservees.
Cette valeur est stockee par la Roue du Champ_Inc_base.
double changer_temps_futur (double, int i=1)
Fixe le temps du ieme champ futur.
double changer_temps_passe (double, int i=1)
Fixe le temps du ieme champ passe.
double recuperer_temps_futur (int i=1) const
Retourne le temps du ieme champ futur.
double recuperer_temps_passe (int i=1) const
Retourne le temps du ieme champ passe.
DoubleTab & valeurs (double temps) override
Renvoie les valeurs du champs a l'instant temps.
const DoubleTab & valeurs (double temps) const override
Renvoie les valeurs du champs a l'instant temps.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
DoubleTab & futur (int i=1) override
Renvoie les valeurs du champs a l'instant t+i.
const DoubleTab & futur (int i=1) const override
Renvoie les valeurs du champs a l'instant t+i.
(version const)
DoubleTab & passe (int i=1) override
Renvoie les valeurs du champs a l'instant t-i.
const DoubleTab & passe (int i=1) const override
Renvoie les valeurs du champs a l'instant t-i.
(version const)
Champ_Inc_base & avancer (int i=1)
Avance le pointeur courant de i pas de temps,
dans la liste des valeurs temporelles conservees.
Champ_Inc_base & reculer (int i=1)
Recule le pointeur courant de i pas de temps,
dans la liste des valeurs temporelles conservees.
int lire_donnees (Entree &)
Lit les valeurs du champs a partir d'un flot d'entree.
Format de lecture:
int [LE NOMBRE DE VALEURS A LIRE]
[LIRE LE NOMBRE DE VALEUR VOULUES].
virtual void associer_eqn (const Equation_base &)
Associe le champ a l'equation dont il represente une inconnue.
Simple appel a MorEqn::associer_eqn(const Equation_base&)
virtual void associer_zone_cl_dis (const Zone_Cl_dis &)
int imprime (Sortie &, int) const override
int a_une_zone_dis_base () const override
Par defaut, on ne sait pas si une zone_dis_base sera definie.
const Zone_Cl_dis & zone_Cl_dis () const
Zone_Cl_dis & zone_Cl_dis ()
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
NE FAIT RIEN
Methode a surcharger.
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
Simple appel a:
Champ_Inc_base::remplir_coord_noeuds_et_polys(DoubleTab&,IntVect& poly)
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const =0
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
Simple appel a
Champ_Inc_base::remplir_coord_noeuds(DoubleTab&)
virtual double integrale_espace (int ncomp) const
const Domaine & domaine () const
const tabs_t & derivees () const
void init_champ_calcule (const Objet_U &obj, fonc_calc_t fonc)
void reset_champ_calcule ()
DoubleTab valeur_aux_bords () const override
renvoie la valeur du champ aux faces de bord
virtual void creer_espace_distant (int dummy)
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champ_P1NC_implementation
Champ_P1NC_implementation ()
~Champ_P1NC_implementation () override
int fixer_nb_valeurs_nodales (int)
double fonction_forme_2D (double x, double y, int le_poly, int face, const IntTab &sommet_poly, const DoubleTab &coord) const
double fonction_forme_3D (double x, double y, double z, int le_poly, int face, const IntTab &sommet_poly, const DoubleTab &coord) const
double coord_barycentrique (const IntTab &sommet_poly, const DoubleTab &coord, double x, double y, int le_poly, int face) const
double coord_barycentrique (const IntTab &sommet_poly, const DoubleTab &coord, double x, double y, double z, int le_poly, int face) const
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeur_aux_sommets (const Domaine &dom, DoubleTab &ch_som) const override
DoubleVect & valeur_aux_sommets_compo (const Domaine &dom, DoubleVect &ch_som, int ncomp) const override
double valeur_a_sommet_compo (int num_som, int le_poly, int ncomp) const
DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
int imprime_P1NC (Sortie &, int) const
void filtrer_L2 (DoubleTab &) const
void filtrer_H1 (DoubleTab &) const
void filtrer_resu (DoubleTab &) const
DoubleTab & ch_som ()
DoubleVect & ch_som_vect ()
const Matrice_Morse_Sym & get_MatP1NC2P1_L2 () const
const SolveurSys & get_solveur_L2 () const
void filtrer_L2_H1 (DoubleTab &) const
const Matrice_Morse_Sym & get_MatP1NC2P1_L2_H1 () const
const Matrice_Morse_Sym & get_MatP1NC2P1_H1 () const
const SolveurSys & get_solveur_L2_H1 () const
const SolveurSys & get_solveur_H1 () const
int nb_colonnes_tot ()
int nb_colonnes ()
void dimensionner_Mat_Bloc_Morse_Sym (Matrice &matrice_tmp)
void Mat_Morse_to_Mat_Bloc (Matrice &matrice_tmp)
Public Member Functions inherited from Champ_implementation
virtual ~Champ_implementation ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const =0
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const =0
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_P1NC & self_cast (Objet_U &)
static const Champ_P1NC & self_cast (const Objet_U &)
static DoubleVect & calcul_S_barre (const DoubleTab &, DoubleVect &, const Zone_Cl_VEF &)
static DoubleTab & calcul_gradient (const DoubleTab &, DoubleTab &, const Zone_Cl_VEF &)
static DoubleTab & calcul_duidxj_paroi (DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const Zone_Cl_VEF &)
static double calculer_integrale_volumique (const Zone_VEF &, const DoubleVect &, Ok_Perio ok)
Static Public Member Functions inherited from Champ_Inc_base
static const Type_info * info ()
static Champ_Inc_base & self_cast (Objet_U &)
static const Champ_Inc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Inc_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Entree & readOn (Entree &) override
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Protected Member Functions inherited from Champ_Inc_base
Sortie & printOn (Sortie &x) const override
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Entree & readOn (Entree &) override
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
virtual void creer_tableau_distribue (const MD_Vector &, Array_base::Resize_Options=Array_base::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Champ_P1NC_implementation
virtual const Zone_VEF & zone_vef () const =0
DoubleTab & trace (const Frontiere_dis_base &fr, const DoubleTab &y, DoubleTab &x, int distant) const
Protected Member Functions inherited from Champ_implementation
virtual const Champ_base & le_champ () const =0
virtual Champ_base & le_champ ()=0
const Zone & zone () const
virtual const Zone_dis_base & zone_dis_base () const
Private Member Functions
const Champ_base & le_champ () const override
Champ_base & le_champ () override
Private Attributes
Ref_Zone_VEF la_zone_VEF
Additional Inherited Members
Protected Attributes inherited from Champ_Inc_base
Roue_ptr les_valeurs
Ref_Zone_Cl_dis ma_zone_cl_dis
fonc_calc_t fonc_calc_
int fonc_calc_init_ = 0
Ref_Objet_U obj_calc_
DoubleTab val_bord_
tabs_t deriv_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Protected Attributes inherited from Champ_P1NC_implementation
Matrice_Morse_Sym MatP1NC2P1_L2
Matrice MatP1NC2P1_L2_Parallele
SolveurSys solveur_L2
Matrice_Morse_Sym MatP1NC2P1_H1
SolveurSys solveur_H1
DoubleTab ch_som_
DoubleVect ch_som_vect_
int filtrer_L2_deja_appele_
Matrice_Morse_Sym MatP1NC2P1_L2_H1
SolveurSys solveur_L2_H1
Detailed Description
Definition at line 38 of file Champ_P1NC.h.
Constructor & Destructor Documentation
Champ_P1NC()
Champ_P1NC::Champ_P1NC ()
Definition at line 35 of file Champ_P1NC.cpp.
~Champ_P1NC()
Champ_P1NC::~Champ_P1NC ()
Definition at line 35 of file Champ_P1NC.cpp.
Member Function Documentation
abortTimeStep()
void Champ_P1NC::abortTimeStep () override virtual
Reimplemented from Champ_base.
Definition at line 72 of file Champ_P1NC.cpp.
{
  ch_som_=0;
}
References Champ_P1NC_implementation::ch_som_.
affecter_()
Champ_base & Champ_P1NC::affecter_ (const Champ_base & ch) override virtual
Affectation d'un Champ generique (Champ_base) dans
un champ inconnue.
Returns
Champ_base&
Signification: le resultat de l'affectation (*this)
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 428 of file Champ_P1NC.cpp.
{
#ifdef CLEMENT
  DoubleTab& tab = valeurs();
  DoubleTab noeuds;
  remplir_coord_noeuds(noeuds);
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const int nb_faces = zone_VEF.nb_faces();
  const IntTab& face_sommets = zone_VEF.face_sommets();
  const DoubleTab& sommets=domaine().coord_sommets();
  int nb_som=sommets.dimension(0);
  Cerr << "Affecter Clement : ... " << finl;
  DoubleTab valf(valeurs());
  ch.valeur_aux(noeuds, valf);
  DoubleTab vals(nb_som, nb_compo_);
  if(nb_compo_==1)
    {
      vals.resize(nb_som);
    }
  ch.valeur_aux(sommets, vals);
  for(int face=0; face<nb_faces; face++)
    {
      for(int comp=0; comp<nb_compo_; comp++)
        {
          double somme=0;
          for (int isom=0; isom<dimension; isom++)
            if(nb_compo_==1)
              somme+=vals(face_sommets(face,isom));
            else
              somme+=vals(face_sommets(face,isom), comp);
          if(nb_compo_==1)
            {
              if(dimension==2)
                tab(face)=1./6.*somme+2./3.*valf(face);
              else
                tab(face)=17./60.*somme+3./20.*valf(face);
            }
          else if(dimension==2)
            tab(face,comp)=1./6.*somme+2./3.*valf(face,comp);
          else
            tab(face,comp)=17./60.*somme+3./20.*valf(face,comp);
        }
    }
#else
  return Champ_Inc_base::affecter_(ch);
#endif
  return *this;
}
References Champ_Inc_base::affecter_(), Cerr, Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine(), Zone_VF::face_sommets(), finl, la_zone_VEF, Field_base::nb_compo_, Zone_VF::nb_faces(), remplir_coord_noeuds(), TRUSTTab< _TYPE_ >::resize(), Ref_Zone_VEF::valeur(), Champ_base::valeur_aux(), and Champ_Inc_base::valeurs().
associer_zone_dis_base()
void Champ_P1NC::associer_zone_dis_base (const Zone_dis_base & z_dis) override virtual
Reimplemented from Champ_base.
Definition at line 87 of file Champ_P1NC.cpp.
{
  la_zone_VEF=ref_cast(Zone_VEF, z_dis);
}
References la_zone_VEF, and ref_cast.
Referenced by VEF_1D::vitesse().
cal_rot_ordre1()
void Champ_P1NC::cal_rot_ordre1 (DoubleTab & vorticite) const
Definition at line 107 of file Champ_P1NC.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const int nb_elem = zone_VEF.nb_elem();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  DoubleTab gradient_elem(nb_elem_tot,dimension,dimension);
  gradient_elem=0.;
  vorticite=0;
  gradient(gradient_elem);
  int num_elem;
  switch(dimension)
    {
    case 2 :
      {
        for (num_elem=0; num_elem<nb_elem; num_elem++)
          {
            vorticite(num_elem)=gradient_elem(num_elem,1,0)-gradient_elem(num_elem,0,1);
          }
      }
      break;
    case 3 :
      {
        for (num_elem=0; num_elem<nb_elem; num_elem++)
          {
            vorticite(num_elem,0)=gradient_elem(num_elem,2,1)-gradient_elem(num_elem,1,2);
            vorticite(num_elem,1)=gradient_elem(num_elem,0,2)-gradient_elem(num_elem,2,0);
            vorticite(num_elem,2)=gradient_elem(num_elem,1,0)-gradient_elem(num_elem,0,1);
          }
      }
    }
  vorticite.echange_espace_virtuel();
  return ;
}
References Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), gradient(), la_zone_VEF, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), and Ref_Zone_VEF::valeur().
Referenced by Op_Conv_Vort_VEF_Face::ajouter(), and Rotationnel_Champ_P1NC::me_calculer().
calcul_critere_Q()
void Champ_P1NC::calcul_critere_Q (DoubleVect & Critere_Q) const
Definition at line 517 of file Champ_P1NC.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = ref_cast(Zone_Cl_VEF,equation().zone_Cl_dis().valeur() );
  const int nb_elem = zone_VEF.nb_elem();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  int num_elem,i,j;
  double crit,deriv1,deriv2;
  DoubleTab gradient_elem(nb_elem_tot,dimension,dimension);
  gradient_elem=0.;
// Champ_P1NC& vit = *this;
  const DoubleTab& vitesse = valeurs();
  Champ_P1NC::calcul_gradient(vitesse,gradient_elem,zone_Cl_VEF);
  for (num_elem=0; num_elem<nb_elem; num_elem++)
    {
      crit = 0.;
      for (i=0; i<dimension; i++)
        for(j=0; j<dimension; j++)
          {
            deriv1 = gradient_elem(num_elem,i,j);
            deriv2 = gradient_elem(num_elem,j,i);
            crit += -0.25*deriv1*deriv2;
          }
      Critere_Q[num_elem] = crit;
    }
}
References calcul_gradient(), Objet_U::dimension, MorEqn::equation(), la_zone_VEF, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), ref_cast, Ref_Zone_VEF::valeur(), valeur(), Champ_Inc_base::valeurs(), and Champ_Inc_base::zone_Cl_dis().
Referenced by Critere_Q_Champ_P1NC::me_calculer().
calcul_duidxj_paroi()
DoubleTab & Champ_P1NC::calcul_duidxj_paroi (DoubleTab & gij, const DoubleTab & nu, const DoubleTab & nu_turb, const DoubleTab & tau_tan, const Zone_Cl_VEF & zone_Cl_VEF) static
< orientation vers l'interieur
Definition at line 943 of file Champ_P1NC.cpp.
{
  const Zone_VEF& zone_VEF = zone_Cl_VEF.zone_VEF();
  const DoubleTab& face_normale = zone_VEF.face_normales();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  int i,j,fac,num1;
// On va modifier Sij pour les faces de Dirichlet (Paroi_fixe) si nous n utilisons pas Paroi_negligeable!!!!
// On aura : (grad u)_f = (grad u) - (grad u . n) x n + (grad u . n)_lp x n
//
// PQ : 25/01/08 : Mise au propre de la methode pour ne plus etre embete par les histoires de signes notamment
// et savoir reellement ce qu'on fait !!
//
// PRINCIPE :
// (expose en 2D, l'extension au 3D ne pose pas de probleme particulier)
//
// On considere 2 reperes : le repere global (x,y) et le repere local (t,n) ou n designe la normale a la paroi
// Le frottement retourne par la loi de paroi correspond a : || tau_tan || = u*^2 = nu.d(u_t)/dn
// Soit P la matrice de passage permettant de passer d'un repere a l'autre
//
// P = (tx  nx)
// (ty  ny)
//
// Les matrices des gradients de vitesse dans chacun des reperes :
//
// G_(x,y) =  (du/dx  du/dy)    et   F_(t,n) = (du_t/dt   du_t/dn)
// (dv/dx  dv/dy)                    (du_n/dt   du_n/dn)
//
// -1
// sont reliees l'une a l'autre par :   G_(x,y)  =  P . F_(t,n) . P
//
//
// Ainsi la correction apportee dans F = (du_t/dt   du_t/dn + C)  ou  C = -du_t/dn + tau_tan/nu
// (du_n/dt   du_n/dn)
//
// se reporte dans G de la maniere suivante :
//
// -1
// G*_(x,y) = G_(x,y) +  P . (0  C). P   =  G_(x,y) + (C.nx.tx  C.ny.tx)
// (0  0)                   (C.nx.ty  C.ny.ty)
//
//
// c'est ce dernier terme qu'il s'agit donc de determiner ici
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  int nb_cl=les_cl.size();
// Cerr << "On fait une modif aux calculs des gradient a cause de la loi de paroi!!!!" << finl;
// DoubleTrav part1_int(Objet_U::dimension), part1(Objet_U::dimension,Objet_U::dimension), part2(Objet_U::dimension,Objet_U::dimension);
  DoubleTab P(dimension,dimension);
// tau_tan could be uninitialized at this point. In such a case,
// we can skip the function because the value of gij won't change
  if (tau_tan.dimension_tot(0)==0)
    {
      return gij;
    }
  for ( int num_cl=0; num_cl<nb_cl; num_cl++)
    {
// Boucle sur les bords
      const Cond_lim& la_cl = les_cl[num_cl];
      const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = la_front_dis.num_premiere_face();
      int nfin = ndeb + la_front_dis.nb_faces();
      if (sub_type(Dirichlet_paroi_fixe,la_cl.valeur()) ||
          sub_type(Dirichlet_paroi_defilante,la_cl.valeur()) ||
          la_cl.valeur().que_suis_je() == "Entree_fluide_vitesse_imposee_ALE")
        {
          for (fac=ndeb; fac<nfin ; fac++)
            {
// Boucle sur les faces
              num1 = face_voisins(fac,0);
//
// definition des vecteurs unitaires constituant le repere local
// stockes dans la matrice de passage P
//
// vecteur tangentiel (porte par la vitesse tangentielle)
              double norme2_tau_tan = 0.;
              for(i=0 ; i<Objet_U::dimension ; i++)
                norme2_tau_tan += tau_tan(fac,i)*tau_tan(fac,i);
              double norme_tau_tan =  sqrt(norme2_tau_tan);
              for(i=0 ; i<Objet_U::dimension ; i++)
                P(i,0) = tau_tan(fac,i)/(norme_tau_tan+DMINFLOAT);
// vecteur normal a la paroi
              double norme2_n = 0.;
              int signe = -zone_VEF.oriente_normale(fac, num1); //!< orientation vers l'interieur
              for (i=0 ; i<Objet_U::dimension ; i++)
                norme2_n += face_normale(fac,i)*face_normale(fac,i);
              double norme_n = sqrt(norme2_n);
              for(i=0 ; i<Objet_U::dimension ; i++)
                P(i,1) = signe*face_normale(fac,i)/norme_n;
// (3D) on complete la base par le deuxieme vecteur tangentiel
              if(Objet_U::dimension==3)
                {
                  P(0,2) = P(1,0)*P(2,1) - P(2,0)*P(1,1) ;
                  P(1,2) = P(2,0)*P(0,1) - P(0,0)*P(2,1) ;
                  P(2,2) = P(0,0)*P(1,1) - P(1,0)*P(0,1) ;
                }
//
// determination du terme d(u_t)/dn a enlever
// -1
// terme identifie a l'aide du produit : F =  P . G . P
//
//
              double dutdn_old = 0.;
              for (i=0 ; i<Objet_U::dimension ; i++)
                for (j=0 ; j<Objet_U::dimension ; j++)
                  {
                    dutdn_old += gij(num1,i,j) * P(j,1) * P(i,0) ;
                  }
//
// Correction finale apportee a la matrice G
//
              double C = -dutdn_old + sqrt(norme2_tau_tan)/(nu[num1]+nu_turb[num1])*porosite_face(fac) ;
// la division par (nu[num1]+nu_turb[num1]) s'impose du fait que l'operateur de diffusion
// fait intervenir le produit : (nu[num1]+nu_turb[num1])*g(i,j)
              for (i=0 ; i<Objet_U::dimension ; i++)
                for (j=0 ; j<Objet_U::dimension ; j++)
                  {
                    gij(num1,i,j) += C * P(j,1) * P(i,0) ;
                  }
            }
        }
    }
  return gij;
}
References Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), DMINFLOAT, Zone_VEF::face_normales(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Zone_VEF::oriente_normale(), Zone_VF::porosite_face(), Objet_U::que_suis_je(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), and Zone_Cl_VEF::zone_VEF().
Referenced by Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), and Op_Dift_VEF_Face::contribue_au_second_membre().
calcul_grad_T()
void Champ_P1NC::calcul_grad_T (const Zone_Cl_VEF & zone_Cl_VEF, DoubleTab & grad_T) const
Definition at line 707 of file Champ_P1NC.cpp.
{
  const DoubleTab& temp = valeurs();
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  calculer_gradientP1NC(temp,zone_VEF,zone_Cl_VEF,grad_T);
  /*
      const IntTab& face_voisins = zone_VEF.face_voisins();
      const IntTab& elem_faces=zone_VEF.elem_faces();
      int nb_faces = zone_VEF.nb_faces();
      const int nb_elem = zone_VEF.nb_elem_tot();
      int num_elem,num_face,elem0,elem1,i;
      ArrOfInt sign_opp_x(nb_faces);
      ArrOfInt sign_opp_y(nb_faces);
      sign_opp_x=0;
      sign_opp_y=0;
      for (num_face=0;num_face<nb_faces;num_face++)
      {
      elem0 = face_voisins(num_face,0);
      elem1 = face_voisins(num_face,1);
      if (elem1!=-1)
      {
      if  (grad_T(elem0,0)*grad_T(elem1,0)<0.) sign_opp_x(num_face)++;
      if  (grad_T(elem0,1)*grad_T(elem1,1)<0.) sign_opp_y(num_face)++;
      }
      }
      grad_T=0.;
      for (num_elem=0;num_elem<nb_elem;num_elem++)
      {
      for (i=0;i<dimension+1;i++)
      {
      grad_T(num_elem,0) +=sign_opp_x(elem_faces(num_elem,i));
      grad_T(num_elem,1) +=sign_opp_y(elem_faces(num_elem,i));
      }
      }
// *******************************************************************
// PQ : 12/12/05 : pour pouvoir visualiser les oscillations a partir
// des changements de signes du gradient de T
// *******************************************************************
  */
}
References calculer_gradientP1NC(), la_zone_VEF, Ref_Zone_VEF::valeur(), and Champ_Inc_base::valeurs().
Referenced by grad_T_Champ_P1NC::me_calculer().
calcul_grad_U()
void Champ_P1NC::calcul_grad_U (const Zone_Cl_VEF & zone_Cl_VEF, DoubleTab & grad_u) const
Definition at line 680 of file Champ_P1NC.cpp.
{
  const DoubleTab& u = valeurs();
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const int nb_elem = zone_VEF.nb_elem();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  DoubleTab gradient_elem(nb_elem_tot,dimension,dimension);
  gradient_elem=0.;
  calculer_gradientP1NC(u,zone_VEF,zone_Cl_VEF,gradient_elem);
  for (int elem=0; elem<nb_elem; elem++)
    {
      int comp=0;
      for (int i=0; i<dimension; i++)
        for(int j=0; j<dimension; j++)
          {
            grad_u(elem,comp) = gradient_elem(elem,i,j);
            comp++;
          }
    }
}
References calculer_gradientP1NC(), Objet_U::dimension, la_zone_VEF, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Ref_Zone_VEF::valeur(), and Champ_Inc_base::valeurs().
Referenced by grad_U_Champ_P1NC::me_calculer().
calcul_gradient()
DoubleTab & Champ_P1NC::calcul_gradient (const DoubleTab & champ, DoubleTab & gij, const Zone_Cl_VEF & zone_Cl_VEF) static
Definition at line 935 of file Champ_P1NC.cpp.
{
  const Zone_VEF& zone_VEF = zone_Cl_VEF.zone_VEF();
  calculer_gradientP1NC(champ,zone_VEF,zone_Cl_VEF,gij);
  return gij;
}
References calculer_gradientP1NC(), and Zone_Cl_VEF::zone_VEF().
Referenced by Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Grad_P1NC_to_P0::ajouter(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), calcul_critere_Q(), calcul_S_barre(), Champ_Ostwald_VEF::calculer_dscald(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), Traitement_particulier_NS_Brech_VEF::calculer_terme_production_K(), Op_Dift_VEF_Face::contribue_au_second_membre(), and Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre().
calcul_h_conv()
void Champ_P1NC::calcul_h_conv (const Zone_Cl_VEF & zone_Cl_VEF, DoubleTab & h_conv, int temp_ref) const
Definition at line 755 of file Champ_P1NC.cpp.
{
  const DoubleTab& temp = valeurs();
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleTab& face_normale = zone_VEF.face_normales();
// On recupere le flux aux frontieres
  DoubleTab Flux;
  Flux=equation().operateur(0).l_op_base().flux_bords();
// On initialise a -1
  h_conv=-1.;
  double T_ref=double(temp_ref);
  for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Frontiere_dis_base& la_fr = la_cl.frontiere_dis();
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      double h_moy = 0.;
// Selon les conditions limites
      if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Champ_base& rho = equation().milieu().masse_volumique().valeur();
          const Champ_Don& Cp = equation().milieu().capacite_calorifique();
          int rho_uniforme=(sub_type(Champ_Uniforme,rho) ? 1:0);
          int cp_uniforme=(sub_type(Champ_Uniforme,Cp.valeur()) ? 1:0);
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
              int elem = face_voisins(num_face,0);
              double rho_cp = (rho_uniforme?rho(0,0):(rho.nb_comp()==1?rho(num_face):rho(num_face,0)));
              rho_cp *= (cp_uniforme?Cp(0,0):(Cp.nb_comp()==1?Cp(num_face):Cp(num_face,0)));
              h_conv(elem) = ref_cast(Echange_externe_impose,la_cl.valeur()).h_imp(num_face)*rho_cp;
              h_moy+=h_conv(elem);
            }
        }
      else  if (sub_type(Scalaire_impose_paroi,la_cl.valeur()) ||
                sub_type(Neumann_homogene,la_cl.valeur())  ||
                sub_type(Neumann_paroi,la_cl.valeur()) )
        {
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
              int elem = face_voisins(num_face,0);
              double norme_flux=0.;
              double surf=0.;
              for(int k=0; k<Flux.dimension(1); k++)
                norme_flux+=Flux(num_face,k)*Flux(num_face,k);
              for(int k=0; k<Objet_U::dimension; k++)
                surf+=face_normale(num_face,k)*face_normale(num_face,k);
              double DT=temp(num_face)-T_ref;
              if (DT==0.)
                h_conv(elem)=0.;
              else
                {
// La mise a jour de ce champ est faite quand on demande son postraitement
// et par consequent les flux ont ete mis a jour et sont deja multiplies par rho*Cp
                  h_conv(elem)=sqrt(norme_flux/surf)/DT;
                }
              h_moy+=h_conv(elem);
            }
        }
      h_moy=Process::mp_sum(h_moy);
      int nb_faces=Process::mp_sum(le_bord.nb_faces());
      h_moy/=nb_faces;
      if(je_suis_maitre())
        {
          Nom fich_hconv;
          fich_hconv  = "Heat_transfert_Coeff_";
          fich_hconv += la_fr.le_nom();
          fich_hconv += ".dat";
          SFichier fic(fich_hconv,ios::app);
          fic.setf(ios::scientific);
          double le_temps = equation().schema_temps().temps_courant();
          fic << le_temps << " " << h_moy << finl;
        }
    }
}
References Milieu_base::capacite_calorifique(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), finl, Operateur_base::flux_bords(), Cond_lim::frontiere_dis(), Process::je_suis_maitre(), Operateur::l_op_base(), la_zone_VEF, Frontiere_dis_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Milieu_base::masse_volumique(), Equation_base::milieu(), Process::mp_sum(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Equation_base::operateur(), ref_cast, Equation_base::schema_temps(), Sortie_Fichier_base::setf(), sub_type, Schema_Temps_base::temps_courant(), Deriv_Champ_base::valeur(), Deriv_Champ_Don_base::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Zone_VEF::valeur(), and Champ_Inc_base::valeurs().
Referenced by h_conv_Champ_P1NC::me_calculer().
calcul_S_barre()
DoubleVect & Champ_P1NC::calcul_S_barre (const DoubleTab & la_vitesse, DoubleVect & SMA_barre, const Zone_Cl_VEF & zone_Cl_VEF) static
Definition at line 1107 of file Champ_P1NC.cpp.
{
  const Zone_VEF& zone_VEF = zone_Cl_VEF.zone_VEF();
  const int nb_elem = zone_VEF.nb_elem();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  DoubleTab duidxj(nb_elem_tot,dimension,dimension);
  Champ_P1NC::calcul_gradient(la_vitesse,duidxj,zone_Cl_VEF);
  for (int elem=0 ; elem<nb_elem; elem++)
    {
      double temp = 0.;
      for (int i=0 ; i<dimension ; i++)
        for (int j=0 ; j<dimension ; j++)
          {
            double Sij=0.5*(duidxj(elem,i,j) + duidxj(elem,j,i));
            temp+=Sij*Sij;
          }
      SMA_barre(elem)=2.*temp;
    }
  return SMA_barre;
}
References calcul_gradient(), Objet_U::dimension, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), and Zone_Cl_VEF::zone_VEF().
Referenced by Taux_cisaillement_P0_VEF::mettre_a_jour().
calcul_y_plus()
void Champ_P1NC::calcul_y_plus (const Zone_Cl_VEF & zone_Cl_VEF, DoubleVect & y_plus) const
< will contain yplus values if available
< flag
< pour se ramener a distance paroi / milieu de num[0]-num[1]
< pour se ramener a distance paroi / milieu de num[0]-num[1]-num[2]
Definition at line 550 of file Champ_P1NC.cpp.
{
// On initialise le champ y_plus avec une valeur negative,
// comme ca lorsqu'on veut visualiser le champ pres de la paroi,
// on n'a qu'a supprimer les valeurs negatives et n'apparaissent
// que les valeurs aux parois.
  int ndeb,nfin,elem,l_unif;
  double norm_tau,u_etoile,norm_v=0, dist=0, val1, val2, val3, d_visco, visco=1.;
  IntVect num(dimension);
  y_plus=-1.;
  const Champ_P1NC& vit = *this;
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const Equation_base& eqn_hydr = equation();
  const Fluide_base& le_fluide = ref_cast(Fluide_base, eqn_hydr.milieu());
  const Champ_Don& ch_visco_cin = le_fluide.viscosite_cinematique();
  const DoubleTab& tab_visco = ch_visco_cin->valeurs();
  if (sub_type(Champ_Uniforme,ch_visco_cin.valeur()))
    {
      if(tab_visco(0,0)>DMINFLOAT) visco = tab_visco(0,0);
      else visco = DMINFLOAT;
      l_unif = 1;
    }
  else
    l_unif = 0;
  if ((!l_unif) && (tab_visco.local_min_vect()<DMINFLOAT))
// GF on ne doit pas changer tab_visco ici !
    {
      Cerr<<" visco <=0 ?"<<finl;
      exit();
    }
// tab_visco+=DMINFLOAT;
  DoubleTab yplus_faces( 1, 1 ); //!< will contain yplus values if available
  int yplus_already_computed=0; //!< flag
  const RefObjU& modele_turbulence = eqn_hydr.get_modele(TURBULENCE);
  if (modele_turbulence.non_nul() && sub_type(Mod_turb_hyd_base,modele_turbulence.valeur()))
    {
      const Mod_turb_hyd_base& mod_turb = ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur());
      const Turbulence_paroi_base& loipar = mod_turb.loi_paroi();
// if(! sub_type(Paroi_negligeable_VEF , loipar))
      if( loipar.use_shear( ) )
        {
          yplus_faces.resize( la_zone_VEF->nb_faces_tot( ) );
          yplus_faces.ref( loipar.tab_d_plus( ) );
          yplus_already_computed = 1;
        }
    }
  for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if ( sub_type(Dirichlet_paroi_fixe,la_cl.valeur()) ||
           sub_type(Dirichlet_paroi_defilante,la_cl.valeur()) ||
           la_cl.valeur().que_suis_je() == "Entree_fluide_vitesse_imposee_ALE")
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          ndeb = le_bord.num_premiere_face();
          nfin = ndeb + le_bord.nb_faces();
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
              elem =face_voisins(num_face,0);
              if( yplus_already_computed )
                {
// y+ is only defined on faces so we take the face value to put in the element
                  y_plus( elem ) = yplus_faces( num_face );
                }
              else
                {
                  if (dimension == 2 )
                    {
                      num[0]=elem_faces(elem,0);
                      num[1]=elem_faces(elem,1);
                      if (num[0]==num_face) num[0]=elem_faces(elem,2);
                      else if (num[1]==num_face) num[1]=elem_faces(elem,2);
                      dist = distance_2D(num_face,elem,zone_VEF);
                      dist *= 3./2.;//!< pour se ramener a distance paroi / milieu de num[0]-num[1]
                      norm_v=norm_2D_vit1_lp(vit.valeurs(),num_face,num[0],num[1],zone_VEF,val1,val2);
                    } //!< dim 2
                  else if (dimension == 3)
                    {
                      num[0]=elem_faces(elem,0);
                      num[1]=elem_faces(elem,1);
                      num[2]=elem_faces(elem,2);
                      if (num[0]==num_face) num[0]=elem_faces(elem,3);
                      else if (num[1]==num_face) num[1]=elem_faces(elem,3);
                      else if (num[2]==num_face) num[2]=elem_faces(elem,3);
                      dist = distance_3D(num_face,elem,zone_VEF);
                      dist *= 4./3.; //!< pour se ramener a distance paroi / milieu de num[0]-num[1]-num[2]
                      norm_v=norm_3D_vit1_lp(vit.valeurs(), num_face, num[0], num[1], num[2], zone_VEF, val1, val2, val3);
                    }//!< dim 3
                  if (l_unif)
                    d_visco = visco;
                  else
                    d_visco = tab_visco[elem];
// PQ : 01/10/03 : corrections par rapport a la version premiere
                  norm_tau = d_visco*norm_v/dist;
                  u_etoile = sqrt(norm_tau);
                  y_plus(elem) = dist*u_etoile/d_visco;
                }//!< else yplus already computed
            }//!< loop on faces
        }//!< Fin de paroi fixe
    }//!< Fin boucle sur les bords
}
References Cerr, Objet_U::dimension, distance_2D(), distance_3D(), DMINFLOAT, Zone_VF::elem_faces(), MorEqn::equation(), Process::exit(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Equation_base::get_modele(), la_zone_VEF, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::local_min_vect(), Mod_turb_hyd_base::loi_paroi(), Equation_base::milieu(), Front_VF::nb_faces(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), O_U_Ptr::non_nul(), norm_2D_vit1_lp(), norm_3D_vit1_lp(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_ >::ref(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Turbulence_paroi_base::tab_d_plus(), TURBULENCE, Turbulence_paroi_base::use_shear(), Deriv_Champ_Don_base::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Objet_U::valeur(), Ref_Zone_VEF::valeur(), Champ_Don::valeurs(), Champ_Inc_base::valeurs(), and Fluide_base::viscosite_cinematique().
Referenced by Y_plus_Champ_P1NC::me_calculer().
calculer_integrale_volumique()
double Champ_P1NC::calculer_integrale_volumique (const Zone_VEF & zone, const DoubleVect & v, Ok_Perio ok) static
Definition at line 1131 of file Champ_P1NC.cpp.
{
  if (ok != FAUX_EN_PERIO)
    {
// BM: desole
      Cerr << "Champ_P1NC::calculer_integrale_volumique pas encore code juste en perio !" << finl;
      exit();
    }
  assert(v.line_size() == 1);
  const DoubleVect& volume = zone.volumes_entrelaces();
  const double resu = mp_prodscal(v, volume);
  return resu;
}
References Cerr, Process::exit(), FAUX_EN_PERIO, finl, TRUSTVect< _TYPE_ >::line_size(), mp_prodscal(), and Champ_implementation::zone().
Referenced by EDO_Pression_th_VEF::masse_totale(), EOS_Tools_VEF::moyenne_vol(), and EDO_Pression_th_VEF_Gaz_Parfait::resoudre().
compo_normale_sortante()
int Champ_P1NC::compo_normale_sortante (int num_face) const
Definition at line 92 of file Champ_P1NC.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  double vit_norm =0;
  for (int ncomp=0; ncomp<nb_comp(); ncomp++)
    vit_norm += (*this)(num_face,ncomp)*zone_VEF.face_normales(num_face,ncomp);
  return (vit_norm > 0);
}
References Zone_VEF::face_normales(), la_zone_VEF, Field_base::nb_comp(), and Ref_Zone_VEF::valeur().
cree_instance()
Objet_U * Champ_P1NC::cree_instance () static
Definition at line 35 of file Champ_P1NC.cpp.
duplique()
int Champ_P1NC::duplique () const override virtual
Implements Objet_U.
Definition at line 35 of file Champ_P1NC.cpp.
filtrer_H1()
void Champ_P1NC::filtrer_H1 (DoubleTab & x) const inline
Definition at line 141 of file Champ_P1NC.h.
{
  Champ_P1NC_implementation::filtrer_H1(x);
}
References Champ_P1NC_implementation::filtrer_H1().
filtrer_L2()
void Champ_P1NC::filtrer_L2 (DoubleTab & x) const inline
Definition at line 136 of file Champ_P1NC.h.
{
  Champ_P1NC_implementation::filtrer_L2(x);
}
References Champ_P1NC_implementation::filtrer_L2().
Referenced by Op_Conv_EF_VEF_P1NC::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Op_Diff_P1NC_barprim::calculer(), and norme_L2().
filtrer_resu()
void Champ_P1NC::filtrer_resu (DoubleTab & x) const inline
Definition at line 145 of file Champ_P1NC.h.
{
  Champ_P1NC_implementation::filtrer_resu(x);
}
References Champ_P1NC_implementation::filtrer_resu().
Referenced by Op_Conv_EF_VEF_P1NC::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), and Op_Diff_P1NC_barprim::calculer().
fixer_nb_valeurs_nodales()
int Champ_P1NC::fixer_nb_valeurs_nodales (int nb_noeuds) override virtual
Reimplemented from Champ_Inc_base.
Definition at line 1146 of file Champ_P1NC.cpp.
{
  assert(nb_noeuds == zone_vef().nb_faces());
  const MD_Vector& md = zone_vef().md_vector_faces();
  creer_tableau_distribue(md);
  Champ_P1NC_implementation::fixer_nb_valeurs_nodales(nb_noeuds);
  return nb_noeuds;
}
References Champ_Inc_base::creer_tableau_distribue(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Zone_VF::md_vector_faces(), and zone_vef().
Referenced by VEF_1D::vitesse().
get_info()
const Type_info * Champ_P1NC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 35 of file Champ_P1NC.cpp.
gradient()
void Champ_P1NC::gradient (DoubleTab & gradient_elem) const
Definition at line 412 of file Champ_P1NC.cpp.
{
// Calcul du gradient: par exemple gradient de la vitesse pour le calcul de la vorticite
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = ref_cast(Zone_Cl_VEF,equation().zone_Cl_dis().valeur() );
  calculer_gradientP1NC(valeurs(),zone_VEF,zone_Cl_VEF,
                        gradient_elem);
}
References calculer_gradientP1NC(), MorEqn::equation(), la_zone_VEF, ref_cast, Ref_Zone_VEF::valeur(), valeur(), Champ_Inc_base::valeurs(), and Champ_Inc_base::zone_Cl_dis().
Referenced by cal_rot_ordre1().
imprime()
int Champ_P1NC::imprime (Sortie & os, int ncomp) const override virtual
Reimplemented from Champ_Inc_base.
Definition at line 422 of file Champ_P1NC.cpp.
{
  imprime_P1NC(os,ncomp);
  return 1;
}
References Champ_P1NC_implementation::imprime_P1NC().
info()
const Type_info * Champ_P1NC::info () static
Definition at line 35 of file Champ_P1NC.cpp.
le_champ() [1/2]
const Champ_base & Champ_P1NC::le_champ (void) const inline override private virtual
Implements Champ_implementation.
Definition at line 126 of file Champ_P1NC.h.
{
  return *this;
}
le_champ() [2/2]
Champ_base & Champ_P1NC::le_champ (void) inline override private virtual
Implements Champ_implementation.
Definition at line 131 of file Champ_P1NC.h.
{
  return *this;
}
mettre_a_jour()
void Champ_P1NC::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps du champ inconnue.
WEC : Maintenant si on l'appelle 2 fois de suite avec le meme
argument, la 2eme ne fait rien.
Reimplemented from Champ_Inc_base.
Definition at line 66 of file Champ_P1NC.cpp.
{
  Champ_Inc_base::mettre_a_jour(un_temps);
  filtrer_L2_deja_appele_=0;
}
References Champ_P1NC_implementation::filtrer_L2_deja_appele_, and Champ_Inc_base::mettre_a_jour().
norme_H1()
double Champ_P1NC::norme_H1 (const Domaine & dom) const virtual
Definition at line 874 of file Champ_P1NC.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const Zone& ma_zone = zone_VEF.zone();
  double dnorme_H1,norme_H1_comp,int_grad_elem,norme_grad_elem;
  int face_globale;
// On va calculer la norme H1 d'une inconnue P1NC.
// L'algorithme tient compte des contraintes suivantes:
// - l'inconnue peut avoir plusieurs composantes
// (i.e etre un scalaire ou etre un vecteur)
// - la dimension du probleme est arbitraire (1, 2 ou 3).
// ATTENTION: les prismes ne sont pas supportes.
  dnorme_H1=0.;
  for (int composante=0; composante<nb_comp(); composante++) //cas scalaire ou vectoriel
    {
      norme_H1_comp=0.; //pour eviter les accumulations
      for (int K=0; K<ma_zone.nb_elem(); K++) //boucle sur les elements
        {
          norme_grad_elem=0.; //pour eviter les accumulations
          for (int i=0; i<dimension; i++) //boucle sur la dimension du pb
            {
              int_grad_elem=0.; //pour eviter les accumulations
              for (int face=0; face<ma_zone.nb_faces_elem(); face++) //boucle sur les faces d'un "K"
                {
                  face_globale = zone_VEF.elem_faces(K,face);
                  int_grad_elem += (valeurs())(face_globale,composante)*
                                   zone_VEF.face_normales(face_globale,i)*
                                   zone_VEF.oriente_normale(face_globale,K);
                } //fin du for sur "face"
              norme_grad_elem += int_grad_elem*int_grad_elem;
            } //fin du for sur "i"
          norme_H1_comp += norme_grad_elem/zone_VEF.volumes(K);
        } //fin du for sur "K"
      dnorme_H1 += norme_H1_comp;
    } //!< fin du for sur "composante"
  return sqrt(dnorme_H1);
}
References composante(), Objet_U::dimension, Zone_VF::elem_faces(), Zone_VEF::face_normales(), la_zone_VEF, Field_base::nb_comp(), Zone::nb_elem(), Zone::nb_faces_elem(), Zone_VEF::oriente_normale(), Ref_Zone_VEF::valeur(), Champ_Inc_base::valeurs(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by norme_L2_H1().
norme_L2()
double Champ_P1NC::norme_L2 (const Domaine & dom) const virtual
Definition at line 861 of file Champ_P1NC.cpp.
{
  Cerr << "Champ_P1NC::norme_L2" << finl;
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  {
    DoubleTab x(valeurs());
    filtrer_L2(x);
    Cerr << "Norme filtree : " << ::norme_L2(x, zone_VEF) << finl;
  }
  const DoubleTab& u = valeurs();
  return ::norme_L2(u, zone_VEF);
}
References Cerr, filtrer_L2(), finl, la_zone_VEF, norme_L2(), norme_L2(), Ref_Zone_VEF::valeur(), and Champ_Inc_base::valeurs().
Referenced by norme_L2(), and norme_L2_H1().
norme_L2_H1()
double Champ_P1NC::norme_L2_H1 (const Domaine & dom) const virtual
Definition at line 920 of file Champ_P1NC.cpp.
{
  double pas_de_temps = equation().schema_temps().pas_de_temps();
  return ((1./pas_de_temps)*norme_L2(dom))+norme_H1(dom);
}
References MorEqn::equation(), norme_H1(), norme_L2(), Schema_Temps_base::pas_de_temps(), and Equation_base::schema_temps().
printOn()
Sortie & Champ_P1NC::printOn (Sortie & os) const override protected virtual
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 40 of file Champ_P1NC.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_P1NC::readOn (Entree & is) override protected virtual
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 49 of file Champ_P1NC.cpp.
{
  lire_donnees (s) ;
  return s ;
}
References Champ_Inc_base::lire_donnees().
remplir_coord_noeuds()
DoubleTab & Champ_P1NC::remplir_coord_noeuds (DoubleTab & positions) const inline override virtual
Implements Champ_Inc_base.
Definition at line 209 of file Champ_P1NC.h.
{
  return Champ_P1NC_implementation::remplir_coord_noeuds(positions);
}
References Champ_P1NC_implementation::remplir_coord_noeuds().
Referenced by affecter_().
remplir_coord_noeuds_et_polys()
int Champ_P1NC::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const inline override virtual
NE FAIT RIEN
Methode a surcharger.
Returns
int
Signification: renvoie toujours 0
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 213 of file Champ_P1NC.h.
{
  return Champ_P1NC_implementation::remplir_coord_noeuds_et_polys(positions,
                                                                  polys);
}
References Champ_P1NC_implementation::remplir_coord_noeuds_et_polys().
self_cast() [1/2]
const Champ_P1NC & Champ_P1NC::self_cast (const Objet_U & r) static
Definition at line 35 of file Champ_P1NC.cpp.
self_cast() [2/2]
Champ_P1NC & Champ_P1NC::self_cast (Objet_U & r) static
Definition at line 35 of file Champ_P1NC.cpp.
taille_memoire()
unsigned Champ_P1NC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 35 of file Champ_P1NC.cpp.
trace()
DoubleTab & Champ_P1NC::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const override virtual
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
Reimplemented from Champ_Inc_base.
Definition at line 102 of file Champ_P1NC.cpp.
{
  return Champ_P1NC_implementation::trace(fr, valeurs(tps), x,distant);
}
References Champ_P1NC_implementation::trace(), and Champ_Inc_base::valeurs().
valeur_a_elem()
DoubleVect & Champ_P1NC::valeur_a_elem (const DoubleVect & position, DoubleVect & val, int le_poly) const inline override virtual
Implements Champ_implementation.
Definition at line 150 of file Champ_P1NC.h.
{
  return Champ_P1NC_implementation::valeur_a_elem(position, val, le_poly);
}
References Champ_P1NC_implementation::valeur_a_elem().
valeur_a_elem_compo()
double Champ_P1NC::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline override virtual
Implements Champ_implementation.
Definition at line 156 of file Champ_P1NC.h.
{
  return Champ_P1NC_implementation::valeur_a_elem_compo(position, le_poly, ncomp);
}
References Champ_P1NC_implementation::valeur_a_elem_compo().
valeur_a_sommet_compo()
double Champ_P1NC::valeur_a_sommet_compo (int sommet, int le_poly, int compo) const inline override virtual
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
Reimplemented from Champ_base.
Definition at line 161 of file Champ_P1NC.h.
{
  return Champ_P1NC_implementation::valeur_a_sommet_compo(num_som, le_poly, ncomp);
}
References Champ_P1NC_implementation::valeur_a_sommet_compo().
valeur_aux_elems()
DoubleTab & Champ_P1NC::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & tab_valeurs) const inline override virtual
Implements Champ_implementation.
Definition at line 166 of file Champ_P1NC.h.
{
  return Champ_P1NC_implementation::valeur_aux_elems(positions, les_polys, tab_valeurs);
}
References Champ_P1NC_implementation::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_P1NC::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & tab_valeurs, int ncomp) const inline override virtual
Implements Champ_implementation.
Definition at line 172 of file Champ_P1NC.h.
{
  return Champ_P1NC_implementation::valeur_aux_elems_compo(positions, les_polys,
                                                           tab_valeurs, ncomp);
}
References Champ_P1NC_implementation::valeur_aux_elems_compo().
valeur_aux_elems_compo_smooth()
DoubleVect & Champ_P1NC::valeur_aux_elems_compo_smooth (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & tab_valeurs, int ncomp) inline override virtual
Reimplemented from Champ_base.
Definition at line 186 of file Champ_P1NC.h.
{
  return Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(positions, les_polys,
                                                                  tab_valeurs, ncomp);
}
References Champ_P1NC_implementation::valeur_aux_elems_compo_smooth().
valeur_aux_elems_smooth()
DoubleTab & Champ_P1NC::valeur_aux_elems_smooth (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & tab_valeurs) inline override virtual
Reimplemented from Champ_base.
Definition at line 180 of file Champ_P1NC.h.
{
  return Champ_P1NC_implementation::valeur_aux_elems_smooth(positions, les_polys, tab_valeurs);
}
References Champ_P1NC_implementation::valeur_aux_elems_smooth().
valeur_aux_sommets()
DoubleTab & Champ_P1NC::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const inline override virtual
Implements Champ_implementation.
Definition at line 194 of file Champ_P1NC.h.
{
  return Champ_P1NC_implementation::valeur_aux_sommets(dom, val);
}
References Champ_P1NC_implementation::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_P1NC::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int comp) const inline override virtual
Implements Champ_implementation.
Definition at line 204 of file Champ_P1NC.h.
{
  return Champ_P1NC_implementation::valeur_aux_sommets_compo(dom, val, comp);
}
References Champ_P1NC_implementation::valeur_aux_sommets_compo().
verifie_valeurs_cl()
void Champ_P1NC::verifie_valeurs_cl () override virtual
Reimplemented from Champ_Inc_base.
Definition at line 479 of file Champ_P1NC.cpp.
{
  const Zone_Cl_dis_base& zcl = equation().zone_Cl_dis().valeur();
  int nb_cl = zcl.nb_cond_lim();
  DoubleTab& ch_tab = valeurs();
  int nb_compo = nb_comp();
  int ndeb,nfin,num_face;
  for (int i=0; i<nb_cl; i++)
    {
      const Cond_lim_base& la_cl = zcl.les_conditions_limites(i).valeur();
      if (sub_type(Periodique,la_cl))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          ndeb = le_bord.num_premiere_face();
          nfin = ndeb + le_bord.nb_faces();
          int voisine;
          double moy;
          for (num_face=ndeb; num_face<nfin; num_face++)
            {
              voisine = la_cl_perio.face_associee(num_face-ndeb) + ndeb;
              for (int comp=0; comp<nb_compo; comp++)
                {
                  if (ch_tab(num_face,comp) != ch_tab(voisine,comp))
                    {
                      moy = 0.5*(ch_tab(num_face,comp) + ch_tab(voisine,comp));
                      ch_tab(num_face,comp) = moy;
                      ch_tab(voisine,comp) = moy;
                    }
                }
            }
        }
    }
  ch_tab.echange_espace_virtuel();
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), Periodique::face_associee(), Cond_lim_base::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Field_base::nb_comp(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Champ_Inc_base::valeurs(), and Equation_base::zone_Cl_dis().
zone_dis_base()
const Zone_dis_base & Champ_P1NC::zone_dis_base () const override virtual
Reimplemented from Champ_implementation.
Definition at line 82 of file Champ_P1NC.cpp.
{
  return la_zone_VEF.valeur();
}
References la_zone_VEF, and Ref_Zone_VEF::valeur().
Referenced by VEF_discretisation::creer_champ_vorticite().
zone_vef()
const Zone_VEF & Champ_P1NC::zone_vef () const inline override virtual
Implements Champ_P1NC_implementation.
Definition at line 220 of file Champ_P1NC.h.
{
  return la_zone_VEF.valeur();
}
References la_zone_VEF, and Ref_Zone_VEF::valeur().
Referenced by Champ_P1NC_implementation::filtrer_L2(), fixer_nb_valeurs_nodales(), and Zone_Cl_VEF::imposer_cond_lim().
Member Data Documentation
info_obj
const Type_info Champ_P1NC::info_obj static
Definition at line 41 of file Champ_P1NC.h.
la_zone_VEF
Ref_Zone_VEF Champ_P1NC::la_zone_VEF private
Definition at line 117 of file Champ_P1NC.h.
Referenced by affecter_(), associer_zone_dis_base(), cal_rot_ordre1(), calcul_critere_Q(), calcul_grad_T(), calcul_grad_U(), calcul_h_conv(), calcul_y_plus(), compo_normale_sortante(), gradient(), norme_H1(), norme_L2(), zone_dis_base(), and zone_vef().
The documentation for this class was generated from the following files:
src/VEF/Champs/Champ_P1NC.h
src/VEF/Champs/Champ_P1NC.cpp