TRUST: Ref_Zone_Cl_VDF Class Reference
Ref_Zone_Cl_VDF Class Reference
#include <Ref_Zone_Cl_VDF.h>
Public Member Functions
~Ref_Zone_Cl_VDF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Zone_Cl_VDF ()
Ref_Zone_Cl_VDF (const Zone_Cl_VDF &)
Ref_Zone_Cl_VDF (const Ref_Zone_Cl_VDF &)
const Zone_Cl_VDF & valeur () const
Zone_Cl_VDF & valeur ()
const Zone_Cl_VDF * operator-> () const
Zone_Cl_VDF * operator-> ()
const Ref_Zone_Cl_VDF & operator= (const Zone_Cl_VDF &)
const Ref_Zone_Cl_VDF & operator= (const Ref_Zone_Cl_VDF &)
operator const Zone_Cl_VDF & () const
operator Zone_Cl_VDF & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Zone_Cl_VDF & self_cast (Objet_U &)
static const Ref_Zone_Cl_VDF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Zone_Cl_VDF * pointeur_
Detailed Description
Definition at line 28 of file Ref_Zone_Cl_VDF.h.
Constructor & Destructor Documentation
Ref_Zone_Cl_VDF::~Ref_Zone_Cl_VDF ()
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
Ref_Zone_Cl_VDF::Ref_Zone_Cl_VDF ()
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
Ref_Zone_Cl_VDF::Ref_Zone_Cl_VDF (const Zone_Cl_VDF & t)
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
Ref_Zone_Cl_VDF::Ref_Zone_Cl_VDF (const Ref_Zone_Cl_VDF & t)
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
Member Function Documentation
Objet_U * Ref_Zone_Cl_VDF::cree_instance () [static]
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
int Ref_Zone_Cl_VDF::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
const Type_info * Ref_Zone_Cl_VDF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
const Type_info & Ref_Zone_Cl_VDF::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
const Type_info * Ref_Zone_Cl_VDF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
Ref_Zone_Cl_VDF::operator const Zone_Cl_VDF & () const
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
Ref_Zone_Cl_VDF::operator Zone_Cl_VDF & ()
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
const Zone_Cl_VDF * Ref_Zone_Cl_VDF::operator-> () const [inline]
Definition at line 28 of file Ref_Zone_Cl_VDF.h.
Zone_Cl_VDF * Ref_Zone_Cl_VDF::operator-> () [inline]
Definition at line 28 of file Ref_Zone_Cl_VDF.h.
const Ref_Zone_Cl_VDF & Ref_Zone_Cl_VDF::operator= (const Ref_Zone_Cl_VDF & t)
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
const Ref_Zone_Cl_VDF & Ref_Zone_Cl_VDF::operator= (const Zone_Cl_VDF & t)
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
Sortie & Ref_Zone_Cl_VDF::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
Entree & Ref_Zone_Cl_VDF::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
const Ref_Zone_Cl_VDF & Ref_Zone_Cl_VDF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
Ref_Zone_Cl_VDF & Ref_Zone_Cl_VDF::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
void Ref_Zone_Cl_VDF::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
unsigned Ref_Zone_Cl_VDF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Zone_Cl_VDF.cpp.
const Zone_Cl_VDF & Ref_Zone_Cl_VDF::valeur () const [inline]
Definition at line 28 of file Ref_Zone_Cl_VDF.h.
Referenced by Terme_Source_Qdm_VDF_Face::ajouter(), Terme_Source_inc_VDF_Face::ajouter(), Terme_Source_inc_th_VDF_Face::ajouter(), Terme_Source_Coriolis_VDF_Face::ajouter(), Terme_Source_Canal_perio_VDF_Face::ajouter(), Terme_Source_Acceleration_VDF_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter(), Op_Dift_VDF_var_Face_Axi::ajouter(), Op_Dift_VDF_Face_Axi::ajouter(), Op_Grad_VDF_Face::ajouter(), Op_Grad_P0_to_Face::ajouter(), Force_Centrifuge_VDF_Face_Axi::ajouter(), Op_Dift_VDF_var_Face_Axi::ajouter_contribution(), Op_Dift_VDF_Face_Axi::ajouter_contribution(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Op_Grad_VDF_Face::contribuer_a_avec(), Op_Grad_VDF_Face::impr(), Assembleur_P_VDF::liste_faces_periodiques(), Y_plus_Champ_Face::me_calculer(), grad_U_Champ_Face::me_calculer(), Critere_Q_Champ_Face::me_calculer(), Taux_cisaillement_P0_VDF::mettre_a_jour(), Op_Dift_VDF_var_Face_Axi::modifier_pour_Cl(), Op_Dift_VDF_Face_Axi::modifier_pour_Cl(), Op_Diff_VDF_var_Face_Axi::modifier_pour_Cl(), Op_Diff_VDF_Face_Axi::modifier_pour_Cl(), Assembleur_P_VDF::modifier_secmem(), Assembleur_P_VDF::remplir(), Iterateur_VDF_base::zone_Cl(), Assembleur_P_VDF_Q4::zone_Cl_dis_base(), Assembleur_P_VDF::zone_Cl_dis_base(), Y_plus_Champ_Face::zone_Cl_dis_base(), Critere_Q_Champ_Face::zone_Cl_dis_base(), Op_Grad_VDF_Face::zone_Cl_VDF(), and Op_Grad_P0_to_Face::zone_Cl_VDF().
Zone_Cl_VDF & Ref_Zone_Cl_VDF::valeur () [inline]
Definition at line 28 of file Ref_Zone_Cl_VDF.h.
Member Data Documentation
const Type_info Ref_Zone_Cl_VDF::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Zone_Cl_VDF.h.
Zone_Cl_VDF* Ref_Zone_Cl_VDF::pointeur_ [private]
Definition at line 28 of file Ref_Zone_Cl_VDF.h.
The documentation for this class was generated from the following files:
src/VDF/Zones/Ref_Zone_Cl_VDF.h
src/VDF/Zones/Ref_Zone_Cl_VDF.cpp