TRUST: Loi_Etat_Multi_GP_QC Class Reference
Loi_Etat_Multi_GP_QC Class Reference
#include <Loi_Etat_Multi_GP_QC.h>
Public Member Functions
~Loi_Etat_Multi_GP_QC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_Multi_GP_QC ()
void associer_espece (const Convection_Diffusion_Espece_Multi_QC &eq)
Associe les proprietes physiques
d une espece a la loi d'etat.
void calculer_masse_molaire (DoubleTab &M) const override
Calcule la masse molaire du melange (M)
M depend de la mase molaire de chaque espece et de la composition du melange (Yi)
void calculer_tab_Cp (DoubleTab &cp) const override
Calcule le Cp du melange
Le Cp depend du Cp de chaque espece et de la composition du melange (Yi)
void calculer_masse_volumique () override
Recalcule la masse volumique.
void calculer_mu_sur_Sc () override
Calcule la viscosite dynamique sur Schmidt.
double calculer_masse_volumique (double, double) const override
double calculer_masse_volumique (double P, double T, double r) const override
Public Member Functions inherited from Loi_Etat_Multi_GP_base
Loi_Etat_Multi_GP_base ()
~Loi_Etat_Multi_GP_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void calculer_masse_molaire ()
void calculer_Cp () override
Calcule le Cp
NE FAIT RIEN : le Cp est constant.
void calculer_lambda () override
Calcule la conductivite.
void calculer_alpha () override
Calcule la diffusivite.
void calculer_mu () override
Calcule la viscosite dynamique.
virtual void associer_inconnue (const Champ_Inc_base &inconnue)
Associe l inconnue de chaque equation de
fraction massique a la loi d'etat.
void initialiser_inco_ch () override
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
double calculer_masse_volumique (double, double) const override
void calculer_masse_volumique () override=0
Calcule la masse volumique.
virtual void calculer_masse_molaire (DoubleTab &M) const =0
virtual void calculer_tab_Cp (DoubleTab &cp) const =0
virtual void calculer_mu_wilke ()=0
const DoubleTab & masse_molaire () const
DoubleTab & masse_molaire ()
virtual double calculer_masse_volumique (double P, double T, double r) const
Public Member Functions inherited from Loi_Etat_Melange_GP_base
Loi_Etat_Melange_GP_base ()
~Loi_Etat_Melange_GP_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_fluide (const Fluide_Dilatable_base &) override
Associe le fluide a la loi d'etat.
Public Member Functions inherited from Loi_Etat_GP_base
~Loi_Etat_GP_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_GP_base ()
const Nom type_fluide () const override
Renvoie le type de fluide associe.
void associer_fluide (const Fluide_Dilatable_base &) override
Associe le fluide a la loi d'etat.
void calculer_lambda () override
Calcule la conductivite.
void calculer_alpha () override
Calcule la diffusivite.
void remplir_T () override
Remplit le tableau de la temperature : T=temp+273.15.
void calculer_Cp () override
Calcule le Cp
NE FAIT RIEN : le Cp est constant.
void calculer_masse_volumique () override
Calcule la masse volumique.
void initialiser () override
Initialise la loi d'etat : calcul Pth.
double calculer_masse_volumique (double, double) const override
double inverser_Pth (double, double) override
Calcule la pression avec la temperature et la masse volumique.
double R () const
Public Member Functions inherited from Loi_Etat_base
~Loi_Etat_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_base ()
void assoscier_probleme (const Probleme_base &pb)
Associe le probleme a la loi d'etat.
void mettre_a_jour (double)
Met a jour la loi d'etat et le champ rho.
void calculer_nu ()
Calcule la viscosite cinematique.
Champ_Don & ch_temperature ()
const Champ_Don & ch_temperature () const
Renvoie le champ de le temperature.
virtual void associer_fluide (const Fluide_Dilatable_base &)
Associe le fluide a la loi d'etat.
virtual void preparer_calcul ()
Prepare le fluide au calcul.
virtual void abortTimeStep ()
virtual void initialiser_inco_ch ()
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
virtual void calculer_mu ()
Calcule la viscosite.
virtual void calculer_lambda ()
Calcule la conductivite.
virtual void calculer_alpha ()
Calcule la diffusivite.
virtual void calculer_mu_sur_Sc ()
Ne fait rien
Surcharge dans Loi_Etat_Melange_GP.
virtual void calculer_nu_sur_Sc ()
Ne fait rien
Surcharge dans Loi_Etat_Melange_Binaire.
virtual void calculer_masse_volumique ()
Recalcule la masse volumique.
virtual double calculer_H (double, double) const
Cas gaz parfait : ne fait rien
Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
virtual double Drho_DP (double, double) const
virtual double Drho_DT (double, double) const
virtual double De_DP (double, double) const
virtual double De_DT (double, double) const
const Champ_base & get_champ (const Motcle &nom) const override
void creer_champ (const Motcle &motlu) override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Nom type_fluide () const =0
virtual void initialiser ()=0
virtual void remplir_T ()=0
virtual void calculer_Cp ()=0
virtual double calculer_masse_volumique (double, double) const =0
virtual double inverser_Pth (double, double)=0
Champs_compris & champs_compris ()
const DoubleTab & temperature () const
const DoubleTab & rho_n () const
const DoubleTab & rho_np1 () const
double Prandt () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Loi_Etat_Multi_GP_QC & self_cast (Objet_U &)
static const Loi_Etat_Multi_GP_QC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_Multi_GP_base
static const Type_info * info ()
static Loi_Etat_Multi_GP_base & self_cast (Objet_U &)
static const Loi_Etat_Multi_GP_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_Melange_GP_base
static const Type_info * info ()
static Loi_Etat_Melange_GP_base & self_cast (Objet_U &)
static const Loi_Etat_Melange_GP_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_GP_base
static const Type_info * info ()
static Loi_Etat_GP_base & self_cast (Objet_U &)
static const Loi_Etat_GP_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_base
static const Type_info * info ()
static Loi_Etat_base & self_cast (Objet_U &)
static const Loi_Etat_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_Multi_GP_base
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_Melange_GP_base
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_GP_base
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void rabot (int futur=0)
Corrections explicites pour les fractions massiques pour forcer
la somme a 1 et sans valeurs negatives.
Protected Member Functions inherited from Loi_Etat_Multi_GP_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void calculer_tab_mu (const DoubleTab &mu, int size)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
List_Ref_Espece liste_especes
int correction_fraction_
int ignore_check_fraction_
double Sc_
double dtol_fraction_
Protected Attributes inherited from Loi_Etat_Multi_GP_base
List_Ref_Champ_Inc_base liste_Y
DoubleTab masse_mol_mel
Protected Attributes inherited from Loi_Etat_GP_base
double Cp_
double R_
Protected Attributes inherited from Loi_Etat_base
Ref_Fluide_Dilatable_base le_fluide
Ref_Probleme_base le_prob_
Champ_Don temperature_
DoubleTab tab_rho_n
DoubleTab tab_rho_np1
double Pr_
int debug
Private Member Functions
void calculer_mu_wilke () override
Calcule la viscosite dynamique de reference (depend des Yi)
Additional Inherited Members
Static Protected Attributes inherited from Loi_Etat_Melange_GP_base
static constexpr double R_GAS = 8.314472
Detailed Description
Definition at line 35 of file Loi_Etat_Multi_GP_QC.h.
Constructor & Destructor Documentation
~Loi_Etat_Multi_GP_QC()
Loi_Etat_Multi_GP_QC::~Loi_Etat_Multi_GP_QC ()
Definition at line 27 of file Loi_Etat_Multi_GP_QC.cpp.
Loi_Etat_Multi_GP_QC()
Loi_Etat_Multi_GP_QC::Loi_Etat_Multi_GP_QC ()
Definition at line 30 of file Loi_Etat_Multi_GP_QC.cpp.
                                           : correction_fraction_(0),ignore_check_fraction_(0),
  Sc_(-1),dtol_fraction_(1.e-6) { }
Member Function Documentation
associer_espece()
void Loi_Etat_Multi_GP_QC::associer_espece (const Convection_Diffusion_Espece_Multi_QC & eq)
Associe les proprietes physiques
d une espece a la loi d'etat.
Definition at line 67 of file Loi_Etat_Multi_GP_QC.cpp.
{
  liste_especes.add(eq.espece());
}
References List_Ref_Espece::add(), Convection_Diffusion_Espece_Multi_QC::espece(), and liste_especes.
Referenced by Convection_Diffusion_Espece_Multi_QC::completer().
calculer_masse_molaire()
void Loi_Etat_Multi_GP_QC::calculer_masse_molaire (DoubleTab & M) const override virtual
Calcule la masse molaire du melange (M)
M depend de la mase molaire de chaque espece et de la composition du melange (Yi)
Implements Loi_Etat_Multi_GP_base.
Definition at line 87 of file Loi_Etat_Multi_GP_QC.cpp.
{
  const int size = tab_masse_mol_mel.size();
  ArrOfDouble inv_M(size), numer_M(size);
  for (int i=0; i<liste_Y.size(); i++)
    {
      double M_i=liste_especes(i).valeur().masse_molaire();
      const DoubleTab& Y_i=liste_Y(i).valeur().valeurs();
      double min_Y_i=local_min_vect(Y_i);
      double max_Y_i=local_max_vect(Y_i);
      if ((min_Y_i<0.-dtol_fraction_)||(max_Y_i>1.+dtol_fraction_))
        {
          Cerr << "Warning : (min_Y_i<-" << dtol_fraction_ << ")||(max_Y_i>1+" << dtol_fraction_ <<") for the " << i << "th mass fraction:" << finl;
          Cerr << "  min_Y_i = " << min_Y_i << finl;
          Cerr << "  max_Y_i = " << max_Y_i << finl;
          if (!ignore_check_fraction_) Process::exit();
        }
      for (int elem=0; elem<size; elem++)
        {
          numer_M[elem] += Y_i(elem,0);
          inv_M[elem] += Y_i(elem,0)/M_i;
        }
    }
  assert(liste_Y(0).valeur().valeurs().size()==size);
  for (int elem=0; elem<size; elem++)
    if (inv_M[elem]>1.e-8)
      tab_masse_mol_mel(elem,0) = numer_M[elem] / inv_M[elem];
}
References Cerr, dtol_fraction_, Process::exit(), finl, ignore_check_fraction_, liste_especes, Loi_Etat_Multi_GP_base::liste_Y, local_max_vect(), local_min_vect(), TRUSTVect< _TYPE_ >::size(), liste::size(), List_Ref_Champ_Inc_base::valeur(), List_Ref_Espece::valeur(), and valeur().
calculer_masse_volumique() [1/3]
void Loi_Etat_Multi_GP_QC::calculer_masse_volumique () override virtual
Recalcule la masse volumique.
Implements Loi_Etat_Multi_GP_base.
Definition at line 226 of file Loi_Etat_Multi_GP_QC.cpp.
{
  const DoubleTab& tab_ICh = le_fluide->inco_chaleur().valeurs();
  DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  if (correction_fraction_) rabot(0);
  Loi_Etat_Multi_GP_base::calculer_masse_molaire();
  double Pth = le_fluide->pression_th();
  int n = tab_rho.size();
  for (int som=0 ; som<n ; som++)
    {
      double r = 8.3143 / masse_mol_mel(som);
      tab_rho_np1(som) = calculer_masse_volumique(Pth,tab_ICh(som,0),r);
      tab_rho(som,0) = 0.5 * ( tab_rho_n(som) + tab_rho_np1(som) );
    }
  const Champ_base& rho_m=le_fluide->get_champ("rho_gaz");
  ref_cast_non_const(DoubleTab,rho_m.valeurs())=tab_rho_np1;
  tab_rho.echange_espace_virtuel();
  tab_rho_np1.echange_espace_virtuel();
  le_fluide->calculer_rho_face(tab_rho_np1);
  Debog::verifier("Loi_Etat_Multi_GP_QC::calculer_masse_volumique, tab_rho_np1",tab_rho_np1);
  Debog::verifier("Loi_Etat_Multi_GP_QC::calculer_masse_volumique, tab_rho",tab_rho);
}
References Loi_Etat_Multi_GP_base::calculer_masse_molaire(), calculer_masse_volumique(), Fluide_Dilatable_base::calculer_rho_face(), correction_fraction_, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Fluide_Dilatable_base::get_champ(), Fluide_Dilatable_base::inco_chaleur(), Loi_Etat_base::le_fluide, Loi_Etat_Multi_GP_base::masse_mol_mel, Milieu_base::masse_volumique(), Fluide_Dilatable_base::pression_th(), rabot(), ref_cast_non_const, TRUSTVect< _TYPE_ >::size(), Loi_Etat_base::tab_rho_n, Loi_Etat_base::tab_rho_np1, Champ::valeurs(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), and Debog::verifier().
Referenced by calculer_masse_volumique(), EDO_Pression_th_VDF::masse_totale(), and EDO_Pression_th_VEF::masse_totale().
calculer_masse_volumique() [2/3]
double Loi_Etat_Multi_GP_QC::calculer_masse_volumique (double P, double T, double r) const override virtual
Reimplemented from Loi_Etat_Multi_GP_base.
Definition at line 252 of file Loi_Etat_Multi_GP_QC.cpp.
{
  return Loi_Etat_Multi_GP_base::calculer_masse_volumique(P,T,r);
}
References Loi_Etat_Multi_GP_base::calculer_masse_volumique().
calculer_masse_volumique() [3/3]
double Loi_Etat_Multi_GP_QC::calculer_masse_volumique (double P, double T) const override virtual
Reimplemented from Loi_Etat_Multi_GP_base.
Definition at line 257 of file Loi_Etat_Multi_GP_QC.cpp.
{
  return Loi_Etat_Multi_GP_base::calculer_masse_volumique(P,T);
}
References Loi_Etat_Multi_GP_base::calculer_masse_volumique().
calculer_mu_sur_Sc()
void Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc () override virtual
Calcule la viscosite dynamique sur Schmidt.
Reimplemented from Loi_Etat_base.
Definition at line 329 of file Loi_Etat_Multi_GP_QC.cpp.
{
  const Champ_Don& mu = le_fluide->viscosite_dynamique();
  const DoubleTab& tab_mu = mu.valeurs();
  Champ_Don& mu_sur_Sc = le_fluide->mu_sur_Schmidt();
  DoubleTab& tab_mu_sur_Sc = mu_sur_Sc.valeurs();
  if (!sub_type(Champ_Uniforme,mu_sur_Sc.valeur()))
    {
      const int n = tab_mu_sur_Sc.size();
      if (sub_type(Champ_Uniforme,mu.valeur()))
        for (int i=0 ; i<n ; i++) tab_mu_sur_Sc(i,0) = tab_mu(0,0) / Sc_;
      else
        for (int i=0 ; i<n ; i++) tab_mu_sur_Sc(i,0) = tab_mu(i,0)/Sc_;
    }
  else //mu_sur_Sc uniforme
    tab_mu_sur_Sc(0,0) = tab_mu(0,0) / Sc_;
  double temps_champ = mu->temps();
  mu_sur_Sc.valeur().changer_temps(temps_champ);
  tab_mu_sur_Sc.echange_espace_virtuel();
}
References Champ_base::changer_temps(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Loi_Etat_base::le_fluide, Fluide_Dilatable_base::mu_sur_Schmidt(), Sc_, TRUSTVect< _TYPE_ >::size(), sub_type, Deriv_Champ_Don_base::valeur(), Champ_Don::valeurs(), and Fluide_base::viscosite_dynamique().
calculer_mu_wilke()
void Loi_Etat_Multi_GP_QC::calculer_mu_wilke () override private virtual
Calcule la viscosite dynamique de reference (depend des Yi)
Implements Loi_Etat_Multi_GP_base.
Definition at line 276 of file Loi_Etat_Multi_GP_QC.cpp.
{
// With Wilke formulation: https://aip.scitation.org/doi/pdf/10.1063/1.1747673
  const int size = liste_Y(0).valeur().valeurs().size(), list_size = liste_Y.size();
  DoubleTab phi(size);
  DoubleTab mu(size);
  mu = 0.;
  phi = 0.;
  for (int i=0; i<list_size; i++)
    {
      phi = 0.;
      double& M_i=liste_especes(i).valeur().masse_molaire();
      double mu_i=liste_especes(i).valeur().viscosite_dynamique().valeurs()(0,0);
      for (int j=0; j<list_size; j++)
        if (j!=i)
          {
            double& M_j=liste_especes(j).valeur().masse_molaire();
            double mu_j=liste_especes(j).valeur().viscosite_dynamique().valeurs()(0,0);
            double a=1.+sqrt(mu_i/mu_j)*pow(M_j/M_i,0.25);
            double b=sqrt(8.*(1.+(M_i/M_j)));
            /*
             * E Saikali : XXX XXX XXX
             * I think that a term is missing in this formulation
             * (phi_ij must be multiplied by Mi/Mj since we use mass fractions and not mol fractions !)
             */
            double phi_ij=a*a/b;
            const DoubleVect& y_j = liste_Y(j).valeur().valeurs();
// node is elem (VDF) or face (VEF)
            for (int node=0; node<y_j.size(); node++) phi(node) += y_j(node)*phi_ij;
          }
// We add the mass fraction when i = j
      const DoubleVect& y_i = liste_Y(i).valeur().valeurs();
      for (int node=0; node<y_i.size(); node++) mu(node) += mu_i * y_i(node)/ ( y_i(node) + phi(node) );
    }
  calculer_tab_mu(mu, size);
}
References Loi_Etat_Multi_GP_base::calculer_tab_mu(), liste_especes, Loi_Etat_Multi_GP_base::liste_Y, TRUSTVect< _TYPE_ >::size(), liste::size(), List_Ref_Champ_Inc_base::valeur(), and List_Ref_Espece::valeur().
calculer_tab_Cp()
void Loi_Etat_Multi_GP_QC::calculer_tab_Cp (DoubleTab & cp) const override virtual
Calcule le Cp du melange
Le Cp depend du Cp de chaque espece et de la composition du melange (Yi)
Implements Loi_Etat_Multi_GP_base.
Definition at line 134 of file Loi_Etat_Multi_GP_QC.cpp.
{
// FIXME : Actuellement on suppose que Cp est pris constant pour chacune des especes
  tab_Cp=0;
  for (int i=0; i<liste_Y.size(); i++)
    {
      const DoubleTab& Y_i=liste_Y(i).valeur().valeurs();
      const double cp_i=liste_especes(i).valeur().capacite_calorifique().valeurs()(0,0);
      assert(cp_i>0);
      for (int elem=0; elem<Y_i.size(); elem++) tab_Cp(elem,0) += Y_i(elem,0)*cp_i;
    }
}
References liste_especes, Loi_Etat_Multi_GP_base::liste_Y, TRUSTVect< _TYPE_ >::size(), liste::size(), List_Ref_Champ_Inc_base::valeur(), and List_Ref_Espece::valeur().
cree_instance()
Objet_U * Loi_Etat_Multi_GP_QC::cree_instance () static
Definition at line 27 of file Loi_Etat_Multi_GP_QC.cpp.
duplique()
int Loi_Etat_Multi_GP_QC::duplique () const override virtual
Implements Objet_U.
Definition at line 27 of file Loi_Etat_Multi_GP_QC.cpp.
get_info()
const Type_info * Loi_Etat_Multi_GP_QC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_Multi_GP_base.
Definition at line 27 of file Loi_Etat_Multi_GP_QC.cpp.
info()
const Type_info * Loi_Etat_Multi_GP_QC::info () static
Definition at line 27 of file Loi_Etat_Multi_GP_QC.cpp.
printOn()
Sortie & Loi_Etat_Multi_GP_QC::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Loi_Etat_Multi_GP_base.
Definition at line 33 of file Loi_Etat_Multi_GP_QC.cpp.
{
  os <<que_suis_je()<< finl;
  return os;
}
References finl, and Objet_U::que_suis_je().
rabot()
void Loi_Etat_Multi_GP_QC::rabot (int futur = 0) protected
Corrections explicites pour les fractions massiques pour forcer
la somme a 1 et sans valeurs negatives.
Definition at line 162 of file Loi_Etat_Multi_GP_QC.cpp.
{
  DoubleTab test( liste_Y(0).valeur().valeurs()) ;
  test=0;
  for (int i=0; i<liste_Y.size(); i++)
    {
      DoubleTab& Y_i=liste_Y(i).valeur().futur(futur);
      double min_Y_i=local_min_vect(Y_i);
      double max_Y_i=local_max_vect(Y_i);
      Cerr << "Verification of the " << i << "th mass fraction:" << finl;
      Cerr << "  min_Y_i = " << min_Y_i << finl;
      Cerr << "  max_Y_i = " << max_Y_i << finl;
      if ((min_Y_i<0.-dtol_fraction_)||(max_Y_i>1.+dtol_fraction_))
        {
          Cerr << "  Warning : (min_Y_i<-" << dtol_fraction_ << ")||(max_Y_i>1+" << dtol_fraction_ <<")" << finl;
          if (!ignore_check_fraction_) Process::exit();
        }
      for (int elem=0; elem<Y_i.size(); elem++)
        {
          if (Y_i(elem,0)<0.)
            {
              Y_i(elem,0)=0.;
              Cerr << "  Y_i forced to " << Y_i(elem,0) << " on node " << elem << finl;
            }
          if (Y_i(elem,0)>1.)
            {
              Y_i(elem,0)=1.;
              Cerr << "  Y_i forced to " << Y_i(elem,0) << " on node " << elem << finl;
            }
        }
      test+=Y_i;
    }
  double min_s=mp_min_vect(test);
  double max_s=mp_max_vect(test);
  Cerr << "Verification of the sum of the mass fractions:" << finl;
  Cerr << "  Sum(min_Y_i) =  " << min_s << finl;
  Cerr << "  Sum(max_Y_i) =  " << max_s << finl;
  for (int i=0; i<liste_Y.size(); i++)
    {
      DoubleTab& Y_i=liste_Y(i).valeur().futur(futur);
      for (int elem=0; elem<Y_i.size(); elem++) Y_i(elem,0)/=(test(elem)+DMINFLOAT);
    }
  if ((!est_egal(min_s,1.,dtol_fraction_))||(!est_egal(max_s,1.,dtol_fraction_)))
    {
      Cerr << "  Warning: the sum of the mass fractions is not equal to 1." <<finl;
      if (!ignore_check_fraction_) Process::exit();
    }
}
References Cerr, DMINFLOAT, dtol_fraction_, est_egal(), Process::exit(), finl, ignore_check_fraction_, Loi_Etat_Multi_GP_base::liste_Y, local_max_vect(), local_min_vect(), mp_max_vect(), mp_min_vect(), TRUSTVect< _TYPE_ >::size(), liste::size(), test(), List_Ref_Champ_Inc_base::valeur(), and valeur().
Referenced by calculer_masse_volumique().
readOn()
Entree & Loi_Etat_Multi_GP_QC::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
< XD_ADD_P double Schmidt number of the gas Sc=nu/D (D: diffusion coefficient of the mixing).
< XD_ADD_P double Prandtl number of the gas Pr=mu*Cp/lambda
< XD_ADD_P double Specific heat at constant pressure of the gas Cp.
< XD_ADD_P double Delta tolerance on mass fractions for check testing (default value 1.e-6).
< XD_ADD_P flag To force mass fractions between 0. and 1.
< XD_ADD_P flag Not to check if mass fractions between 0. and 1.
Reimplemented from Loi_Etat_Multi_GP_base.
Definition at line 39 of file Loi_Etat_Multi_GP_QC.cpp.
{
  Param param(que_suis_je());
  param.ajouter("Sc",&Sc_,Param::REQUIRED); //!< XD_ADD_P double Schmidt number of the gas Sc=nu/D (D: diffusion coefficient of the mixing).
  param.ajouter( "Prandtl",&Pr_,Param::REQUIRED); //!< XD_ADD_P double Prandtl number of the gas Pr=mu*Cp/lambda
  param.ajouter( "Cp",&Cp_); //!< XD_ADD_P double Specific heat at constant pressure of the gas Cp.
  param.ajouter( "dtol_fraction",&dtol_fraction_); //!< XD_ADD_P double Delta tolerance on mass fractions for check testing (default value 1.e-6).
  param.ajouter_flag( "correction_fraction",&correction_fraction_); //!< XD_ADD_P flag To force mass fractions between 0. and 1.
  param.ajouter_flag( "ignore_check_fraction",&ignore_check_fraction_); //!< XD_ADD_P flag Not to check if mass fractions between 0. and 1.
  param.lire_avec_accolades_depuis(is);
  return is;
}
References Param::ajouter(), Param::ajouter_flag(), correction_fraction_, Loi_Etat_GP_base::Cp_, dtol_fraction_, ignore_check_fraction_, Param::lire_avec_accolades_depuis(), Loi_Etat_base::Pr_, Objet_U::que_suis_je(), Param::REQUIRED, and Sc_.
self_cast() [1/2]
const Loi_Etat_Multi_GP_QC & Loi_Etat_Multi_GP_QC::self_cast (const Objet_U & r) static
Definition at line 27 of file Loi_Etat_Multi_GP_QC.cpp.
self_cast() [2/2]
Loi_Etat_Multi_GP_QC & Loi_Etat_Multi_GP_QC::self_cast (Objet_U & r) static
Definition at line 27 of file Loi_Etat_Multi_GP_QC.cpp.
taille_memoire()
unsigned Loi_Etat_Multi_GP_QC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 27 of file Loi_Etat_Multi_GP_QC.cpp.
Member Data Documentation
correction_fraction_
int Loi_Etat_Multi_GP_QC::correction_fraction_ protected
Definition at line 52 of file Loi_Etat_Multi_GP_QC.h.
Referenced by calculer_masse_volumique(), and readOn().
dtol_fraction_
double Loi_Etat_Multi_GP_QC::dtol_fraction_ protected
Definition at line 53 of file Loi_Etat_Multi_GP_QC.h.
Referenced by calculer_masse_molaire(), rabot(), and readOn().
ignore_check_fraction_
int Loi_Etat_Multi_GP_QC::ignore_check_fraction_ protected
Definition at line 52 of file Loi_Etat_Multi_GP_QC.h.
Referenced by calculer_masse_molaire(), rabot(), and readOn().
info_obj
const Type_info Loi_Etat_Multi_GP_QC::info_obj static
Definition at line 37 of file Loi_Etat_Multi_GP_QC.h.
liste_especes
List_Ref_Espece Loi_Etat_Multi_GP_QC::liste_especes protected
Definition at line 51 of file Loi_Etat_Multi_GP_QC.h.
Referenced by associer_espece(), calculer_masse_molaire(), calculer_mu_wilke(), and calculer_tab_Cp().
Sc_
double Loi_Etat_Multi_GP_QC::Sc_ protected
Definition at line 53 of file Loi_Etat_Multi_GP_QC.h.
Referenced by calculer_mu_sur_Sc(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/Loi_Etat/Loi_Etat_Multi_GP_QC.h
src/ThHyd/Dilatable/Quasi_Compressible/Loi_Etat/Loi_Etat_Multi_GP_QC.cpp