TRUST: Ref_Champ_Inc Class Reference
Ref_Champ_Inc Class Reference
#include <Ref_Champ_Inc.h>
Public Member Functions
~Ref_Champ_Inc ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Champ_Inc ()
Ref_Champ_Inc (const Champ_Inc &)
Ref_Champ_Inc (const Ref_Champ_Inc &)
const Champ_Inc & valeur () const
Champ_Inc & valeur ()
const Champ_Inc * operator-> () const
Champ_Inc * operator-> ()
const Ref_Champ_Inc & operator= (const Champ_Inc &)
const Ref_Champ_Inc & operator= (const Ref_Champ_Inc &)
operator const Champ_Inc & () const
operator Champ_Inc & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Champ_Inc & self_cast (Objet_U &)
static const Ref_Champ_Inc & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Champ_Inc * pointeur_
Detailed Description
Definition at line 28 of file Ref_Champ_Inc.h.
Constructor & Destructor Documentation
Ref_Champ_Inc::~Ref_Champ_Inc ()
Definition at line 26 of file Ref_Champ_Inc.cpp.
Ref_Champ_Inc::Ref_Champ_Inc ()
Definition at line 26 of file Ref_Champ_Inc.cpp.
Ref_Champ_Inc::Ref_Champ_Inc (const Champ_Inc & t)
Definition at line 26 of file Ref_Champ_Inc.cpp.
Ref_Champ_Inc::Ref_Champ_Inc (const Ref_Champ_Inc & t)
Definition at line 26 of file Ref_Champ_Inc.cpp.
Member Function Documentation
Objet_U * Ref_Champ_Inc::cree_instance () [static]
Definition at line 26 of file Ref_Champ_Inc.cpp.
int Ref_Champ_Inc::duplique () const [virtual]
Implements Ref_.
Definition at line 26 of file Ref_Champ_Inc.cpp.
const Type_info * Ref_Champ_Inc::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Inc.cpp.
const Type_info & Ref_Champ_Inc::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Ref_Champ_Inc.cpp.
const Type_info * Ref_Champ_Inc::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Inc.cpp.
Ref_Champ_Inc::operator Champ_Inc & ()
Definition at line 26 of file Ref_Champ_Inc.cpp.
Ref_Champ_Inc::operator const Champ_Inc & () const
Definition at line 26 of file Ref_Champ_Inc.cpp.
const Champ_Inc * Ref_Champ_Inc::operator-> () const [inline]
Definition at line 28 of file Ref_Champ_Inc.h.
Champ_Inc * Ref_Champ_Inc::operator-> () [inline]
Definition at line 28 of file Ref_Champ_Inc.h.
const Ref_Champ_Inc & Ref_Champ_Inc::operator= (const Ref_Champ_Inc & t)
Definition at line 26 of file Ref_Champ_Inc.cpp.
const Ref_Champ_Inc & Ref_Champ_Inc::operator= (const Champ_Inc & t)
Definition at line 26 of file Ref_Champ_Inc.cpp.
Sortie & Ref_Champ_Inc::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Inc.cpp.
Entree & Ref_Champ_Inc::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Inc.cpp.
const Ref_Champ_Inc & Ref_Champ_Inc::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Inc.cpp.
Ref_Champ_Inc & Ref_Champ_Inc::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Inc.cpp.
void Ref_Champ_Inc::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Ref_Champ_Inc.cpp.
unsigned Ref_Champ_Inc::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Ref_Champ_Inc.cpp.
const Champ_Inc & Ref_Champ_Inc::valeur () const [inline]
Definition at line 28 of file Ref_Champ_Inc.h.
Referenced by Operateur::ajouter(), Operateur::calculer(), Fluide_Dilatable_base::calculer_pression_tot(), Operateur_base::completer(), Fluide_Dilatable_base::inco_chaleur(), Operateur::mon_inconnue(), and Fluide_Dilatable_base::vitesse().
Champ_Inc & Ref_Champ_Inc::valeur () [inline]
Definition at line 28 of file Ref_Champ_Inc.h.
Member Data Documentation
const Type_info Ref_Champ_Inc::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Champ_Inc.h.
Champ_Inc* Ref_Champ_Inc::pointeur_ [private]
Definition at line 28 of file Ref_Champ_Inc.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Ref_Champ_Inc.h
src/Kernel/Framework/Ref_Champ_Inc.cpp