TRUST: DecoupeBord Class Reference
DecoupeBord Class Reference
#include <DecoupeBord.h>
Public Member Functions
DecoupeBord ()
~DecoupeBord ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
void Decouper (Domaine &dom, const Nom &nom_file)
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static DecoupeBord & self_cast (Objet_U &)
static const DecoupeBord & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete_geometrique_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Definition at line 34 of file DecoupeBord.h.
Constructor & Destructor Documentation
DecoupeBord()
DecoupeBord::DecoupeBord ()
Definition at line 23 of file DecoupeBord.cpp.
~DecoupeBord()
DecoupeBord::~DecoupeBord ()
Definition at line 23 of file DecoupeBord.cpp.
Member Function Documentation
cree_instance()
Objet_U * DecoupeBord::cree_instance () static
Definition at line 23 of file DecoupeBord.cpp.
Decouper()
void DecoupeBord::Decouper (Domaine & dom, const Nom & nom_file)
Definition at line 506 of file DecoupeBord.cpp.
{
  Cerr << "Splitting to the radiation of the boundaries of the domain " << dom.le_nom() << finl;
  int nb_faces_bord_sa=dom.zone(0). nb_faces_bord();
  int nb_faces_raccord_sa=dom.zone(0). nb_faces_raccord();
  if (nproc()!=1)
    {
      Cerr << " The splitting DecoupeBord can be done only in sequential " << finl;
      exit();
    }
// on ecrit la nvelle geom en sequentiel
  int nbtot=0;
  {
// on regarde le nombre de lignes de nom_file
    EFichier listb2(nom_file);
    Nom toto;
    listb2>>toto;
    while(listb2.good())
      {
        listb2>>toto;
        nbtot++;
      }
  }
  EFichier listb2(nom_file);
  Noms nomborddec(nbtot);
  for (int nf=0; nf<nbtot; nf++) listb2>>nomborddec[nf];
  Zone& zone=dom.zone(0);
  int nbfr=zone.nb_front_Cl();
  Bords& listbord=zone.faces_bord();
  Raccords& listrac=zone.faces_raccord();
  Bords listbord2;
  Raccords listrac2;
  int nbbord=zone.nb_bords();
  IntVect decoup(nbfr);
  Noms nomsdesbordsorg(nbfr);
// on parcourt toutes les frontieres
  for (int b=0; b<nbfr; b++)
    {
      Frontiere& org=zone.frontiere(b);
      const Nom& nombord=org.le_nom();
      nomsdesbordsorg[b]=nombord;
      decoup(b)=0;
      SFichier bord_xv(dom.le_nom()+"."+nomsdesbordsorg[b]+"_xv");
      bord_xv.setf(ios::scientific);
      bord_xv.precision(12);
      for (int nf=0; nf<nbtot; nf++)
        {
          Nom nombord_dec=nomborddec[nf];
          const char* marq=strchr(nombord_dec,'%');
          if (marq)
            {
              nombord_dec.prefix(marq);
// on regarde dans les bords decoupes si ils correspondent a la frontiere courante
              if (nombord==nombord_dec)
                {
// exit();
                  decoup(b)=1;
                  Bord toto_bord;
                  Raccord toto_rac;
                  if (b>=nbbord) toto_rac.typer(org.le_type());
                  Frontiere& toto=(b<nbbord?ref_cast(Frontiere,toto_bord):ref_cast(Frontiere,toto_rac.valeur()));
                  Nom nombord_dec_bis=nomborddec[nf];
                  toto.nommer(nombord_dec_bis);
                  IntVect listfaces;
// on recupere la liste des faces
                  EFichier lis(nombord_dec_bis);
                  lis>>listfaces;
// on genere les faces associes a ce nouveau bord
                  Faces& Facesorg=org.faces();
                  Faces& newfaces=toto.faces();
                  newfaces.typer(Facesorg.type_face());
                  int newnbfaces=listfaces.size();
                  int nbsom=Facesorg.nb_som_faces();
                  newfaces.dimensionner(newnbfaces);
                  const IntTab& sommetsorg=Facesorg.les_sommets();
                  IntTab& newsommet=newfaces.les_sommets();
                  for (int i=0; i<newnbfaces; i++)
                    for (int j=0; j<nbsom; j++)
                      newsommet(i,j)=sommetsorg(listfaces[i],j);
                  DoubleTab position;
                  calculer_centres_gravite(position,newfaces.type_face(),dom.coord_sommets(),newsommet);
                  bord_xv<<nombord_dec_bis<<finl;
                  bord_xv<<position<<finl;
                  if (b<nbbord)
                    listbord2.add(toto_bord);
                  else
                    listrac2.add(toto_rac);
                }
            }
        }
      bord_xv.close();
    }
// on supprime les bords decoupes du domaine
  for (int b2=0; b2<nbbord; b2++)
    if (decoup(b2))
      listbord.suppr(zone.bord(nomsdesbordsorg[b2]));
  for (int r2=nbbord; r2<nbfr; r2++)
    if (decoup(r2))
      listrac.suppr(zone.raccord(nomsdesbordsorg[r2]));
  listbord.add(listbord2);
  listrac.add(listrac2);
  int nb_faces_bord=dom.zone(0).nb_faces_bord();
  if (nb_faces_bord!=nb_faces_bord_sa)
    {
      Cerr<<"the new number of boundary faces is false :"<<nb_faces_bord;
      Cerr<<" instead of "<<nb_faces_bord_sa<<finl;
      exit();
    }
  int nb_faces_raccord=dom.zone(0).nb_faces_raccord();
  if (nb_faces_raccord!=nb_faces_raccord_sa)
    {
      Cerr<<"the new number of connection faces is false :"<<nb_faces_raccord;
      Cerr<<" instead of "<<nb_faces_raccord_sa<<finl;
      exit();
    }
}
References List_Bord::add(), List_Raccord::add(), Zone::bord(), calculer_centres_gravite(), Cerr, Sortie_Fichier_base::close(), Domaine::coord_sommets(), Faces::dimensionner(), Process::exit(), Frontiere::faces(), Zone::faces_bord(), Zone::faces_raccord(), finl, Zone::frontiere(), Entree_Fichier_base::good(), Domaine::le_nom(), Frontiere::le_nom(), Objet_U::le_type(), Faces::les_sommets(), Zone::nb_bords(), Zone::nb_faces_bord(), Zone::nb_faces_raccord(), Zone::nb_front_Cl(), Faces::nb_som_faces(), Frontiere::nommer(), Process::nproc(), Sortie_Fichier_base::precision(), Nom::prefix(), Zone::raccord(), ref_cast, Sortie_Fichier_base::setf(), TRUSTVect< _TYPE_ >::size(), List_Bord::suppr(), List_Raccord::suppr(), Faces::type_face(), Deriv_::typer(), Faces::typer(), Deriv_Raccord_base::valeur(), and Domaine::zone().
Referenced by interpreter_().
duplique()
int DecoupeBord::duplique () const override virtual
Implements Objet_U.
Definition at line 23 of file DecoupeBord.cpp.
get_info()
const Type_info * DecoupeBord::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 23 of file DecoupeBord.cpp.
info()
const Type_info * DecoupeBord::info () static
Definition at line 23 of file DecoupeBord.cpp.
interpreter_()
Entree & DecoupeBord::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base.
Definition at line 427 of file DecoupeBord.cpp.
{
  Nom nom_dom1,nom_dom2;
  Nom nom_fichier_sortie("");
  LIST(Nom) list_nom_dec;
  Noms nomdec;
  ArrOfInt nb_parts,nb_parts_geom;
  Param param(que_suis_je());
  int binaire=0;
  Noms expr;
  param.ajouter("domaine",&nom_dom1,Param::REQUIRED);
  param.ajouter("domaine_grossier",&nom_dom2);
  param.ajouter("nb_parts_naif",&nb_parts);
  param.ajouter("nb_parts_geom",&nb_parts_geom);
  param.ajouter("condition_geometrique",&expr);
  param.ajouter("bords_a_decouper",&nomdec,Param::REQUIRED);
  param.ajouter("nom_fichier_sortie",&nom_fichier_sortie);
  param.ajouter("binaire",&binaire);
  param.lire_avec_accolades_depuis(is);
// on fait une copie de dom1 pour le modifier
  associer_domaine(nom_dom1);
  const Domaine& dom_1=domaine();
  if (nom_fichier_sortie=="")
    {
      nom_fichier_sortie=dom_1.le_nom()+".newgeom";
    }
  Domaine dom1;
  dom1=dom_1;
  if (nom_dom2!=Nom())
    {
      if (!sub_type(Domaine, objet(nom_dom2)))
        {
          Cerr << nom_dom2 << " is not an object of type Domaine " << finl;
          Cerr << " Please correct your data set" << finl;
          exit();
        }
      const Domaine& dom_2=ref_cast(Domaine, objet(nom_dom2));
      create_listb_from_domaine2(dom1,dom_2,nomdec);
    }
  else
    {
// if (nb_parts.size_array()==0)
// {
// Cerr<<" You must specify domaine_grossier or cut into n"<<finl;
// exit();
// }
      if (expr.size()!=0)
        {
          create_listb_from_xyz(dom1,nomdec,expr);
        }
      else if (nb_parts.size_array()!=0)
        {
          create_listb_naif(dom1,nomdec,nb_parts);
        }
      else if (nb_parts_geom.size_array()!=0)
        {
          create_listb_geom(dom1,nomdec,nb_parts_geom);
        }
      else
        {
          Cerr<<"in DecoupeBord_pour_rayonnement : You must specify domaine_grossier or nb_parts_naif or nb_part_geom or condition_geometrique"<<finl;
          exit();
        }
    }
  Nom nom_file(dom1.le_nom()+".boundary_list");
  Decouper(dom1,nom_file);
  Cout <<"Writing of the new geometry in the file " << nom_fichier_sortie <<finl;
  SFichier fic;
  fic.set_bin(binaire);
  fic.ouvrir(nom_fichier_sortie);
  fic <<dom1 <<finl;
  return is;
}
References Param::ajouter(), Interprete_geometrique_base::associer_domaine(), Cerr, Cout, create_listb_from_domaine2(), create_listb_from_xyz(), create_listb_geom(), create_listb_naif(), Decouper(), Interprete_geometrique_base::domaine(), Process::exit(), finl, Domaine::le_nom(), Param::lire_avec_accolades_depuis(), LIST, Interprete::objet(), Sortie_Fichier_base::ouvrir(), Objet_U::que_suis_je(), ref_cast, Param::REQUIRED, Sortie::set_bin(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), and sub_type.
printOn()
Sortie & DecoupeBord::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 25 of file DecoupeBord.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & DecoupeBord::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 30 of file DecoupeBord.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const DecoupeBord & DecoupeBord::self_cast (const Objet_U & r) static
Definition at line 23 of file DecoupeBord.cpp.
self_cast() [2/2]
DecoupeBord & DecoupeBord::self_cast (Objet_U & r) static
Definition at line 23 of file DecoupeBord.cpp.
taille_memoire()
unsigned DecoupeBord::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 23 of file DecoupeBord.cpp.
Member Data Documentation
info_obj
const Type_info DecoupeBord::info_obj static
Definition at line 36 of file DecoupeBord.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/DecoupeBord.h
src/Kernel/Geometrie/DecoupeBord.cpp