TRUST: Double_ptr_trav Class Reference
Double_ptr_trav Class Reference
Une zone de travail de la Memoire TRUST composee d'elements de type double.
#include <Memoire_ptr.h>
Public Member Functions
Double_ptr_trav ()
Constructeur
La zone de travaille cree est vide.
Double_ptr_trav * add (int n)
Ajout d'elements dans la zone de travail.
int unlock ()
Deverrouille la zone de travail.
~Double_ptr_trav ()
Destructeur
Supprime les donnees attachees a la zone de travail.
double * d_ptr_ () const
Retourne un pointeur sur les donnees de la zone de travail.
Private Attributes
int sz
double * data
int lock_
Double_ptr_trav * next
Detailed Description
Une zone de travail de la Memoire TRUST composee d'elements de type double.
Definition at line 60 of file Memoire_ptr.h.
Constructor & Destructor Documentation
Double_ptr_trav::Double_ptr_trav () [inline]
Constructeur
La zone de travaille cree est vide.
Definition at line 196 of file Memoire_ptr.h.
Referenced by add().
                                        : sz(-1), data(0),
  lock_(0), next(0)
{
}
Double_ptr_trav::~Double_ptr_trav ()
Destructeur
Supprime les donnees attachees a la zone de travail.
Definition at line 125 of file Memoire_ptr.cpp.
References data, next, and sz.
{
  if(sz!=-1)
    {
      if (next) delete next;
      delete[] data;
    }
}
Member Function Documentation
Double_ptr_trav * Double_ptr_trav::add (int n)
Ajout d'elements dans la zone de travail.
Returns:
Double_ptr_trav*
Signification: pointeur sur le zone de travail contenant les elements crees
Contraintes:
Definition at line 61 of file Memoire_ptr.cpp.
References Cerr, data, Double_ptr_trav(), Process::exit(), finl, lock_, next, and sz.
Referenced by Memoire::add_trav_double().
{
  if(sz==-1)
    {
      sz=n;
      data=new double[sz];
      if(!data)
        {
          Cerr << "Not enough memory " << finl;
          Process::exit();
        }
      lock_=1;
      next=0;
      return this;
    }
  if ( (!lock_) && (sz==n))
    {
      lock_=1;
      return this;
    }
  Double_ptr_trav* curseur=this;
  while(curseur->next)
    {
      curseur=curseur->next;
      if ( (!curseur->lock_) && (curseur->sz==n))
        {
          curseur->lock_=1;
          return curseur;
        }
    }
  curseur->next= new Double_ptr_trav();
  if(!curseur->next)
    {
      Cerr << "Not enough memory " << finl;
      Process::exit();
    }
  curseur=curseur->next;
  curseur->sz=n;
  curseur->data=new double[n];
  if(!data)
    {
      Cerr << "Not enough memory " << finl;
      Process::exit();
    }
  curseur->lock_=1;
  curseur->next=0;
  return curseur;
}
double * Double_ptr_trav::d_ptr_ () const [inline]
Retourne un pointeur sur les donnees de la zone de travail.
Returns:
double*
Signification: pointeur sur le tableau de donnees
Contraintes:
Definition at line 234 of file Memoire_ptr.h.
References data.
Referenced by VDoubledata::VDoubledata().
{
  return data;
}
int Double_ptr_trav::unlock () [inline]
Deverrouille la zone de travail.
Definition at line 215 of file Memoire_ptr.h.
References lock_.
Referenced by VDoubledata::~VDoubledata().
{
  return lock_=0;
}
Member Data Documentation
double* Double_ptr_trav::data [private]
Definition at line 70 of file Memoire_ptr.h.
Referenced by add(), d_ptr_(), and ~Double_ptr_trav().
int Double_ptr_trav::lock_ [private]
Definition at line 71 of file Memoire_ptr.h.
Referenced by add(), and unlock().
Double_ptr_trav* Double_ptr_trav::next [private]
Definition at line 72 of file Memoire_ptr.h.
Referenced by add(), and ~Double_ptr_trav().
int Double_ptr_trav::sz [private]
Definition at line 69 of file Memoire_ptr.h.
Referenced by add(), and ~Double_ptr_trav().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Memoire_ptr.h
src/Kernel/Utilitaires/Memoire_ptr.cpp