TRUST: IntVect Class Reference
IntVect Class Reference
#include <IntVect.h>
Public Member Functions
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
IntVect ()
IntVect (int n)
construction d'un vecteur de taille n.
Les elements du vecteur sont initialises a zero par defaut.
Pour ne pas initialiser les valeurs, utiliser ceci:
IntVect toto;
toto.resize(n, NOCOPY_NOINIT);
IntVect (const IntVect &)
Constructeur par copie. Il s'agit d'un "deep copy"
voir ArrOfInt::ArrOfInt(const ArrOfInt &)
Remarque: il n'y a pas de constructeur par copie a partir de ArrOfInt
Ceci est volontaire, sinon on risque de grosses pertes de performances
par creation implicite d'objets, difficile a trouver.
(exemple: appel d'une methode toto(const IntVect &) avec un ArrOfInt
produit une copie du tableau !)
Utiliser copy() pour copier un ArrOfInt dans un IntVect.
~IntVect ()
virtual void reset ()
met l'objet dans l'etat obtenu par le constructeur par defaut.
(voir ArrOfInt::reset())
virtual void detach_vect ()
detach the vector.
IntVect & operator= (const IntVect &)
copie la structure et les valeurs du tableau v dans *this avec ArrOfInt::operator=()
(attention, si le tableau est de type ref_data ou ref, restrictions et cas particuliers !!!)
Attention: si on ne veut pas copier les structures paralleles, utiliser inject_array()
IntVect & operator= (int)
idem que ArrOfInt::operator=(int)
virtual void ref (const IntVect &)
detache le tableau et l'attache a v (sauf si v==*this, ne fait rien)
Fait pointer le tableau sur la meme zone de memoire que v et copie le MD_Vector
(utilise ArrOfInt::attach_array())
Attention, il devient alors interdit de resizer le tableau v ainsi que *this
Methode virtuelle reimplementee dans IntTab
virtual void ref_data (int *ptr, int new_size)
voir ArrOfInt::ref_data().
(cree un tableau sans structure parallele)
virtual void ref_array (ArrOfInt &, int start=0, int sz=-1)
voir ArrOfInt::ref_array().
(cree un tableau sans structure parallele)
void resize (int, Array_base::Resize_Options opt=COPY_INIT)
Change la taille du vecteur (identique a resize_array()
pour le traitement des anciennes valeurs et de nouvelles cases).
Attention: Cette methode n'est pas virtuelle, et afin d'eviter d'amener
un IntTab dans un etat invalide, l'appel est interdit si l'objet
est de ce type. Dans ce cas, voir resize_tab.
virtual void resize_tab (int n, Array_base::Resize_Options opt=COPY_INIT)
methode virtuelle identique a resize_array(), permet de traiter
de facon generique les ArrOf, Vect et Tab.
Cree un tableau sequentiel...
Si l'objet est de type IntVect, appel a resize(n)
Prerequis: voir resize()
void copy (const ArrOfInt &, Array_base::Resize_Options opt=COPY_INIT)
copie de la structure et des valeurs (si opt==COPY_INIT) du tableau v.
Attention, v doit vraiment etre de type ArrOfInt, pas d'un type derive
(sinon ambiguite: faut-il copier ou pas le MD_Vector ?)
void copy (const IntVect &, Array_base::Resize_Options opt=COPY_INIT)
copie de la structure du vecteur v et des valeurs si opt==COPY_INIT.
int local_max_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
int local_min_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
int local_max_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
int local_min_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
int mp_max_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
int mp_min_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
int mp_max_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
int mp_min_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
void operator+= (const IntVect &)
void operator+= (const int)
ajoute la meme valeur a toutes les cases du tableau
void operator-= (const IntVect &)
void operator-= (const int)
soustrait la meme valeur a toutes les cases
void operator*= (const IntVect &)
void operator*= (const int)
int size () const
Identique a size_reelle()
int size_totale () const
Identique a size_array()
int size_reelle () const
Taille de l'espace "reel" du vecteur.
(si md_vector_ est nul, cette valeur est identique a size_array(),
sinon, soit elle est egale a md_vector_....get_nb_items(),
soit l'appel est invalide (en particulier si les items reels ne
sont pas regroupes en debut de tableau)
On peut interroger le vecteur pour savoir si size_reelle() est valide avec size_reelle_ok()
int size_reelle_ok () const
int line_size () const
virtual void echange_espace_virtuel ()
virtual const MD_Vector & get_md_vector () const
virtual void set_md_vector (const MD_Vector &)
associe le md_vector au vecteur et initialise l'attribut size_reelle_
(voir methode size_reelle())
Si md_vector est nul, detache simplement le md_vector existant.
virtual void jump (Entree &)
virtual void lit (Entree &, int resize_and_read=1)
lecture d'un tableau pour reprise de calcul. On lit les valeurs "raw".
Attention, si le tableau n'est pas vide, il doit deja avoir la bonne
taille et la bonne structure, sinon erreur !
Parameter resize_and_read if the array is sized AND read (by default, yes)
virtual void ecrit (Sortie &) const
ecriture des valeurs du tableau "raw" sans structure parallele
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static IntVect & self_cast (Objet_U &)
static const IntVect & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture d'un vecteur sequentiel (sans descripteur parallele)
Pour l'instant: erreur si presence d'un md_vector_ (sinon quoi faire ?)
Pour les vecteurs paralleles, utiliser une methode de sauvegarde/reprise.
virtual Entree & readOn (Entree &)
Lecture d'un vecteur sequentiel (comme un ArrOfInt)
Attention: appel invalide si le vecteur a un MD_Vector non nul.
(pour les vecteurs paralleles, utiliser une methode de sauvegarde/reprise)
void set_line_size_ (int n)
change l'attribut line_size_ du tableau avec n >= 1
n == 0 est autorise uniquement si size_array_ == 0
void resize_vect_ (int n, Array_base::Resize_Options opt=COPY_INIT)
Methode interne de resize (appellee par IntTab::resize(...))
sans precondition sur le type de l'objet.
void copy_ (const IntVect &v, Array_base::Resize_Options opt=COPY_INIT)
methode protegee appelable depuis une classe derivee<br>(pas de precondition sur le type derive de *this)
void attach_vect (const IntVect &v, int start, int size=-1)
Private Attributes
MD_Vector md_vector_
int size_reelle_
int line_size_
Detailed Description
Definition at line 37 of file IntVect.h.
Constructor & Destructor Documentation
IntVect::IntVect () [inline]
Definition at line 41 of file IntVect.h.
: size_reelle_(0), line_size_(1) {};
IntVect::IntVect (int n)
construction d'un vecteur de taille n.
Les elements du vecteur sont initialises a zero par defaut.
Pour ne pas initialiser les valeurs, utiliser ceci:
IntVect toto;
toto.resize(n, NOCOPY_NOINIT);
Definition at line 76 of file IntVect.cpp.
                      :
  ArrOfInt(n),
  size_reelle_(n),
  line_size_(1)
{
}
IntVect::IntVect (const IntVect & v)
Constructeur par copie. Il s'agit d'un "deep copy"
voir ArrOfInt::ArrOfInt(const ArrOfInt &)
Remarque: il n'y a pas de constructeur par copie a partir de ArrOfInt
Ceci est volontaire, sinon on risque de grosses pertes de performances
par creation implicite d'objets, difficile a trouver.
(exemple: appel d'une methode toto(const IntVect &) avec un ArrOfInt
produit une copie du tableau !)
Utiliser copy() pour copier un ArrOfInt dans un IntVect.
Definition at line 100 of file IntVect.cpp.
                                 :
  ArrOfInt(v),
  md_vector_(v.md_vector_),
  size_reelle_(v.size_reelle_),
  line_size_(v.line_size_)
{
}
IntVect::~IntVect () [inline]
Definition at line 46 of file IntVect.h.
{};
Member Function Documentation
void IntVect::attach_vect (const IntVect & v, int start, int size = -1) [protected]
void IntVect::copy (const IntVect & v, Array_base::Resize_Options opt = COPY_INIT)
copie de la structure du vecteur v et des valeurs si opt==COPY_INIT.
Definition at line 177 of file IntVect.cpp.
References copy_(), get_info(), info(), and ArrOfInt::size_array().
{
  if (&v != this)
    {
// Interdiction de resizer si l'objet est d'un type derive de IntVect
// (sinon mauvaise dimension(0) !)
      assert(v.size_array() == size_array() || get_info() == IntVect::info());
      copy_(v, opt);
    }
}
void IntVect::copy (const ArrOfInt & v, Array_base::Resize_Options opt = COPY_INIT)
copie de la structure et des valeurs (si opt==COPY_INIT) du tableau v.
Attention, v doit vraiment etre de type ArrOfInt, pas d'un type derive
(sinon ambiguite: faut-il copier ou pas le MD_Vector ?)
Definition at line 165 of file IntVect.cpp.
References ArrOfInt::get_info(), get_info(), info(), ArrOfInt::inject_array(), md_vector_, Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), resize(), and ArrOfInt::size_array().
Referenced by Matrice_Morse::operator=(), operator=(), and Traduction_Indice_Global_Local::traduire_espace_virtuel().
{
  assert(get_info() == IntVect::info());
  assert(v.get_info() == ArrOfInt::info());
  assert(!md_vector_.non_nul());
  resize(v.size_array(), opt);
  if (opt != NOCOPY_NOINIT)
    inject_array(v);
}
void IntVect::copy_ (const IntVect & v, Array_base::Resize_Options opt = COPY_INIT) [protected]
methode protegee appelable depuis une classe derivee<br>(pas de precondition sur le type derive de *this)
< Il faut avoir fait le test avant ! Si le vecteur a deja une structure parallele, la copie n'est autorisee que si le vecteur source a la meme structure. Si ce n'est pas le cas, utiliser inject_array() pour copier uniquement les valeurs, ou faire d'abord reset() si on veut ecraser la structure.
< Pour le cas ou md_vector_ est nul et pas v.md_vector_
Definition at line 190 of file IntVect.cpp.
References ArrOfInt::inject_array(), line_size_, md_vector_, Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), ArrOfInt::resize_array_(), ArrOfInt::size_array(), and size_reelle_.
Referenced by copy(), IntTab::copy(), and IntTab::operator=().
{
  assert(&v != this); //!< Il faut avoir fait le test avant ! Si le vecteur a deja une structure parallele, la copie n'est autorisee que si le vecteur source a la meme structure. Si ce n'est pas le cas, utiliser inject_array() pour copier uniquement les valeurs, ou faire d'abord reset() si on veut ecraser la structure.
//
//
//
  assert((!md_vector_.non_nul()) || (md_vector_ == v.md_vector_));
  resize_array_(v.size_array(), NOCOPY_NOINIT);
  if (opt != NOCOPY_NOINIT)
    inject_array(v);
  md_vector_ = v.md_vector_; //!< Pour le cas ou md_vector_ est nul et pas v.md_vector_
  size_reelle_ = v.size_reelle_;
  line_size_ = v.line_size_;
}
Objet_U * IntVect::cree_instance () [static]
Reimplemented from ArrOfInt.
Reimplemented in IntTab, and IntTrav.
Definition at line 38 of file IntVect.cpp.
void IntVect::detach_vect () [virtual]
detach the vector.
Definition at line 119 of file IntVect.cpp.
References MD_Vector::detach(), and md_vector_.
Referenced by Faces::dimensionner().
{
  md_vector_.detach();
}
int IntVect::duplique () const [virtual]
Reimplemented from ArrOfInt.
Reimplemented in IntTab, and IntTrav.
Definition at line 38 of file IntVect.cpp.
void IntVect::echange_espace_virtuel () [virtual]
Definition at line 276 of file IntVect.cpp.
Referenced by Zone_Cl_VEF::associer(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), check_espace_virtuel_vect(), Zone_Cl_VDF::completer(), compute_global_connex_components(), Polyedre::compute_virtual_index(), Zone::construire_elem_virt_pe_num(), Zone_VF::construire_face_virt_pe_num(), Scatter::construire_md_vector(), Zone_VEF_PreP1b::construire_ok_arete(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_Parmetis::construire_partition(), Zone_VEF::creer_faces_virtuelles_non_std(), Zone_PolyMAC::creer_faces_virtuelles_non_std(), Zone_EF::creer_faces_virtuelles_non_std(), Zone_VDF::discretiser(), echanger_tableau_aretes(), DomaineCutter::ecrire_zones(), Extraire_surface::extraire_surface(), Zone_VDF::genere_aretes(), Zone::init_faces_virt_bord(), Zone_VDF::init_virt_e_map(), Zone_PolyMAC::init_virt_ef_map(), Echange_contact_VDF::initialiser(), Echange_contact_PolyMAC::initialiser(), Traduction_Indice_Global_Local::initialiser(), Sous_Zone::readOn(), Zone_Cl_VEF::remplir_type_elem_Cl(), Zone_VEF::reordonner(), Zone_PolyMAC::reordonner(), Zone_EF::reordonner(), Zone_CoviMAC::reordonner(), Traduction_Indice_Global_Local::traduire_espace_virtuel(), and valeur_P1_L2().
{
  MD_Vector_tools::echange_espace_virtuel(*this);
}
void IntVect::ecrit (Sortie & os) const [virtual]
ecriture des valeurs du tableau "raw" sans structure parallele
< le marqueur -1 indique que c'est le nouveau format "ecrit", sans structure parallele
Reimplemented in IntTab.
Definition at line 282 of file IntVect.cpp.
References finl, and printOn().
Referenced by Zone_VEF::ecrit(), Zone_PolyMAC::ecrit(), Zone_EF::ecrit(), and Zone_CoviMAC::ecrit().
{
  ArrOfInt::printOn(os);
  os << (int)-1 << finl; //!< le marqueur -1 indique que c'est le nouveau format "ecrit", sans structure parallele
}
const Type_info * IntVect::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from ArrOfInt.
Reimplemented in IntTab, and IntTrav.
Definition at line 38 of file IntVect.cpp.
Referenced by copy(), IntTab::operator=(), IntTab::ref(), and resize().
virtual const MD_Vector& IntVect::get_md_vector () const [inline, virtual]
Definition at line 87 of file IntVect.h.
References md_vector_.
Referenced by calculer_centres_gravite(), Periodique::completer(), Champ_Post_Operateur_Eqn::completer(), Champ_Generique_Transformation::completer(), Scatter::construire_espace_virtuel_traduction(), Zone_VEF_PreP1b::construire_renum_arete_perio(), MD_Vector_tools::creer_md_vect_renum(), Frontiere::creer_tableau_faces(), Zone_PolyMAC::discretiser(), Zone_VF::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), MD_Vector_tools::echange_espace_virtuel(), echanger_tableau_aretes(), Debog_Pb::ecrire_gen(), Debog_Pb::ecrire_partie(), Debog_Pb::find_renum_vector(), get_ref_coordinates_items(), Zone_VF::info_elem_som(), Zone::init_faces_virt_bord(), init_parts(), IntTrav::IntTrav(), invalidate_data(), lit(), IntTab::lit(), local_carre_norme_vect(), local_imax_vect(), local_imin_vect(), local_max_abs_vect(), local_max_vect(), local_min_abs_vect(), local_min_vect(), local_prodscal(), local_somme_vect(), Zone::md_vector_elements(), Zone_VEF_PreP1b::modifier_pour_Cl(), operator==(), operator_abs(), operator_add(), operator_divide(), operator_egal(), operator_multiply(), operator_negate(), operator_sub(), IntTab::printOn(), Debog_Pb::read_geometry_data(), Champ_Fonc_MED::readOn(), IntTab::readOn(), IntTab::ref_array(), IntTab::ref_data(), IntTab::ref_tab(), tri_lexicographique_tableau(), tri_lexicographique_tableau_indirect(), Debog_Pb::verifier_gen(), Debog_Pb::verifier_partie(), and Debog_Pb::verifier_partie_std().
{ return md_vector_; }
const Type_info * IntVect::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from ArrOfInt.
Reimplemented in IntTab, and IntTrav.
Definition at line 38 of file IntVect.cpp.
Referenced by copy(), and resize().
void IntVect::jump (Entree & is) [virtual]
Reimplemented in IntTab.
Definition at line 288 of file IntVect.cpp.
References lit().
{
  IntVect::lit(is, 0 /* Do not resize&read the array */);
}
int IntVect::line_size () const [inline]
Definition at line 150 of file IntVect.h.
References line_size_, and ArrOfInt::size_array().
Referenced by Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), IntTab::append_line(), Loi_Etat_Multi_GP_base::calculer_alpha(), Loi_Etat_GP_base::calculer_alpha(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Loi_Etat_base::calculer_nu(), Loi_Etat_Multi_GP_base::calculer_tab_mu(), MD_Vector_tools::creer_md_vect_renum(), Debog_Pb::ecrire_gen(), Debog_Pb::ecrire_partie(), Source_WC_Chaleur_VEF::elem_to_face(), Source_WC_Chaleur_VDF::face_to_elem(), init_parts(), MD_Vector_std::initialize_comm(), IntTrav::IntTrav(), invalidate_data(), local_carre_norme_vect(), local_imax_vect(), local_imin_vect(), local_max_abs_vect(), local_max_vect(), local_min_abs_vect(), local_min_vect(), local_prodscal(), local_somme_vect(), IntTab::operator=(), operator_abs(), operator_add(), operator_divide(), operator_egal(), operator_multiply(), operator_negate(), operator_sub(), MD_Vector_std::prepare_send_data(), IntTab::printOn(), MD_Vector_std::process_recv_data(), IntTab::ref(), IntTab::ref_tab(), Zone_VEF::reordonner(), IntTab::resize_dim0(), same_line(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), tri_lexicographique_tableau(), tri_lexicographique_tableau_indirect(), Debog_Pb::verifier_gen(), Debog_Pb::verifier_partie(), and Debog_Pb::verifier_partie_std().
{
// Si line_size_ est nulle, size_array doit etre nul aussi
  assert(line_size_ > 0 || size_array() == 0);
  return line_size_;
}
void IntVect::lit (Entree & is, int resize_and_read = 1) [virtual]
lecture d'un tableau pour reprise de calcul. On lit les valeurs "raw".
Attention, si le tableau n'est pas vide, il doit deja avoir la bonne
taille et la bonne structure, sinon erreur !
Parameter resize_and_read if the array is sized AND read (by default, yes)
Reimplemented in IntTab.
Definition at line 297 of file IntVect.cpp.
References ArrOfInt::addr(), Cerr, Process::exit(), finl, Entree::get(), get_md_vector(), min(), Array_base::NOCOPY_NOINIT, resize(), ArrOfInt::size_array(), and sz.
Referenced by jump().
{
  int sz = -1;
  is >> sz;
  if (resize_and_read)
    {
      if (size_array() == 0 && (!get_md_vector().non_nul()))
        {
          resize(sz, NOCOPY_NOINIT);
        }
      else
        {
          if (sz != size_array())
            {
// Si on cherche a relire un tableau de taille inconnue, le tableau doit
// etre reset() a l'entree. On n'aura pas la structure parallele du tableau !
              Cerr << "Error in IntVect::lit(Entree & is): array has already a structure with incorrect size" << finl;
              exit();
            }
        }
      is.get(addr(), sz);
    }
  else
    {
// May be slow if large chunks are read:
// Int tmp;
// for (int i=0;i<sz;i++) is >> tmp;
// So we bufferize:
      int buffer_size = min(sz,128000);
      ArrOfInt tmp(buffer_size);
      while(sz>buffer_size)
        {
          is.get(tmp.addr(), buffer_size);
          sz-=buffer_size;
        }
      is.get(tmp.addr(), sz);
    }
  int sz_reel = -2;
  is >> sz_reel;
  if (sz_reel >= 0)
    {
// Lecture de l'ancien format. Ignore les valeurs lues.
      int sz_virt;
      is >> sz_virt;
      DescStructure toto;
      is >> toto;
    }
}
int IntVect::local_max_abs_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 1585 of file IntVect.cpp.
{
  return ::local_max_abs_vect(*this, opt);
}
int IntVect::local_max_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 1581 of file IntVect.cpp.
Referenced by Domain_Graph::construire_graph_from_segment().
{
  return ::local_max_vect(*this, opt);
}
int IntVect::local_min_abs_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 1589 of file IntVect.cpp.
{
  return ::local_min_abs_vect(*this, opt);
}
int IntVect::local_min_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 1577 of file IntVect.cpp.
{
  return ::local_min_vect(*this, opt);
}
int IntVect::mp_max_abs_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 1601 of file IntVect.cpp.
{
  return ::mp_max_abs_vect(*this, opt);
}
int IntVect::mp_max_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 1593 of file IntVect.cpp.
Referenced by Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab().
{
  return ::mp_max_vect(*this, opt);
}
int IntVect::mp_min_abs_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 1605 of file IntVect.cpp.
{
  return ::mp_min_abs_vect(*this, opt);
}
int IntVect::mp_min_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 1597 of file IntVect.cpp.
Referenced by Matrice_Morse::imprimer_formatte(), and Matrice_Morse::imprimer_image().
{
  return ::mp_min_vect(*this, opt);
}
void IntVect::operator*= (const IntVect & v)
Definition at line 1617 of file IntVect.cpp.
References operator_multiply().
{
  operator_multiply(*this, v);
}
void IntVect::operator*= (const int x)
Definition at line 1629 of file IntVect.cpp.
References operator_multiply().
{
  operator_multiply(*this, x);
}
void IntVect::operator+= (const IntVect & v)
Definition at line 1609 of file IntVect.cpp.
References operator_add().
{
  operator_add(*this, v);
}
void IntVect::operator+= (const int dy)
ajoute la meme valeur a toutes les cases du tableau
Returns:
ArrOfInt
Signification: *this
Contraintes:
Reimplemented from ArrOfInt.
Definition at line 1621 of file IntVect.cpp.
References operator_add().
{
  operator_add(*this, x);
}
void IntVect::operator-= (const int dy)
soustrait la meme valeur a toutes les cases
Returns:
ArrOfInt &
Signification: *this
Reimplemented from ArrOfInt.
Definition at line 1625 of file IntVect.cpp.
References operator_sub().
{
  operator_sub(*this, x);
}
void IntVect::operator-= (const IntVect & v)
Definition at line 1613 of file IntVect.cpp.
References operator_sub().
{
  operator_sub(*this, v);
}
IntVect & IntVect::operator= (const IntVect & v)
copie la structure et les valeurs du tableau v dans *this avec ArrOfInt::operator=()
(attention, si le tableau est de type ref_data ou ref, restrictions et cas particuliers !!!)
Attention: si on ne veut pas copier les structures paralleles, utiliser inject_array()
Reimplemented in IntTab, and IntTrav.
Definition at line 154 of file IntVect.cpp.
References copy().
Referenced by operator=().
{
  copy(v);
  return *this;
}
IntVect & IntVect::operator= (int x)
idem que ArrOfInt::operator=(int)
Reimplemented from ArrOfInt.
Reimplemented in IntTab, and IntTrav.
Definition at line 206 of file IntVect.cpp.
References operator=().
{
  ArrOfInt::operator=(x);
  return *this;
}
Sortie & IntVect::printOn (Sortie & x) const [protected, virtual]
Ecriture d'un vecteur sequentiel (sans descripteur parallele)
Pour l'instant: erreur si presence d'un md_vector_ (sinon quoi faire ?)
Pour les vecteurs paralleles, utiliser une methode de sauvegarde/reprise.
Reimplemented from ArrOfInt.
Reimplemented in IntTab, and IntTrav.
Definition at line 43 of file IntVect.cpp.
References Cerr, Process::exit(), finl, md_vector_, MD_Vector::non_nul(), and Process::nproc().
Referenced by ecrit().
{
  if (nproc() > 1 && md_vector_.non_nul())
    {
      Cerr << "Error in IntVect::printOn: try to print a parallel vector" << finl;
      exit();
    }
  ArrOfInt::printOn(os);
  return os;
}
Entree & IntVect::readOn (Entree & is) [protected, virtual]
Lecture d'un vecteur sequentiel (comme un ArrOfInt)
Attention: appel invalide si le vecteur a un MD_Vector non nul.
(pour les vecteurs paralleles, utiliser une methode de sauvegarde/reprise)
Reimplemented from ArrOfInt.
Reimplemented in IntTab, and IntTrav.
Definition at line 57 of file IntVect.cpp.
References Cerr, Process::exit(), finl, line_size_, md_vector_, MD_Vector::non_nul(), ArrOfInt::size_array(), and size_reelle_.
{
  if (md_vector_.non_nul())
    {
// Que veut-on faire si on lit dans un vecteur ayant deja une structure parallele ?
      Cerr << "Error in IntVect::readOn: vector has a parallel structure" << finl;
      exit();
    }
  ArrOfInt::readOn(is);
  size_reelle_ = size_array();
  line_size_ = 1;
  return is;
}
void IntVect::ref (const IntVect & v) [virtual]
detache le tableau et l'attache a v (sauf si v==*this, ne fait rien)
Fait pointer le tableau sur la meme zone de memoire que v et copie le MD_Vector
(utilise ArrOfInt::attach_array())
Attention, il devient alors interdit de resizer le tableau v ainsi que *this
Methode virtuelle reimplementee dans IntTab
Reimplemented in IntTab.
Definition at line 132 of file IntVect.cpp.
References ArrOfInt::attach_array(), ArrOfInt::detach_array(), line_size_, md_vector_, and size_reelle_.
Referenced by Op_Dift_VDF_var_Face_Axi::associer(), Op_Dift_VDF_Face_Axi::associer(), Op_Diff_VDF_var_Face_Axi::associer(), Op_Diff_VDF_Face_Axi::associer(), Op_Grad_VDF_Face::associer(), Op_Grad_P0_to_Face::associer(), Evaluateur_VDF::associer_zones(), Force_Centrifuge_VDF_Face_Axi::associer_zones(), Faces_VDF::calculer_orientation(), Evaluateur_Source_VDF_Face::completer(), Evaluateur_Source_PolyMAC_Face::completer(), Evaluateur_Source_CoviMAC_Face::completer(), Evaluateur_Source_CoviMAC_Face::Evaluateur_Source_CoviMAC_Face(), Evaluateur_Source_PolyMAC_Face::Evaluateur_Source_PolyMAC_Face(), Evaluateur_Source_VDF_Face::Evaluateur_Source_VDF_Face(), Evaluateur_VDF::Evaluateur_VDF(), T_It_VDF_Face< _TYPE_ >::T_It_VDF_Face(), and Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries().
{
  if (&v != this)
    {
      detach_array();
      attach_array(v);
      md_vector_ = v.md_vector_;
      size_reelle_ = v.size_reelle_;
      line_size_ = v.line_size_;
    }
}
void IntVect::ref_array (ArrOfInt & m, int start = 0, int sz = -1) [virtual]
voir ArrOfInt::ref_array().
(cree un tableau sans structure parallele)
< pas size qui peut valoir -1
Reimplemented from ArrOfInt.
Reimplemented in IntTab.
Definition at line 234 of file IntVect.cpp.
References MD_Vector::detach(), line_size_, md_vector_, ArrOfInt::size_array(), and size_reelle_.
Referenced by Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_CoviMAC::assembler_mat(), Equation_base::dimensionner_matrice(), and Equation_base::dimensionner_matrice_sans_mem().
{
  md_vector_.detach();
  ArrOfInt::ref_array(m, start, new_size);
  size_reelle_ = size_array(); //!< pas size qui peut valoir -1
  line_size_ = 1;
}
void IntVect::ref_data (int * ptr, int new_size) [virtual]
voir ArrOfInt::ref_data().
(cree un tableau sans structure parallele)
Reimplemented from ArrOfInt.
Reimplemented in IntTab.
Definition at line 224 of file IntVect.cpp.
References MD_Vector::detach(), line_size_, md_vector_, and size_reelle_.
Referenced by Solv_GCP::prepare_data().
{
  md_vector_.detach();
  ArrOfInt::ref_data(ptr, new_size);
  size_reelle_ = new_size;
  line_size_ = 1;
}
void IntVect::reset () [virtual]
met l'objet dans l'etat obtenu par le constructeur par defaut.
(voir ArrOfInt::reset())
Reimplemented from ArrOfInt.
Reimplemented in IntTab.
Definition at line 110 of file IntVect.cpp.
References MD_Vector::detach(), line_size_, md_vector_, and size_reelle_.
Referenced by Matrix_tools::extend_matrix(), Traduction_Indice_Global_Local::initialiser(), Matrice_Morse::operator=(), Solv_GCP::prepare_data(), and Traduction_Indice_Global_Local::reset().
{
  md_vector_.detach();
  line_size_ = 1;
  size_reelle_ = 0;
  ArrOfInt::reset();
}
void IntVect::resize (int n, Array_base::Resize_Options opt = COPY_INIT) [inline]
Change la taille du vecteur (identique a resize_array()
pour le traitement des anciennes valeurs et de nouvelles cases).
Attention: Cette methode n'est pas virtuelle, et afin d'eviter d'amener
un IntTab dans un etat invalide, l'appel est interdit si l'objet
est de ce type. Dans ce cas, voir resize_tab.
Reimplemented from ArrOfInt.
Reimplemented in IntTab.
Definition at line 179 of file IntVect.h.
References get_info(), info(), resize_vect_(), and ArrOfInt::size_array().
Referenced by Sous_Zone::add_poly(), Matrice_Morse::affecte_prod(), Op_Div_VEFP1B_Elem::ajouter(), Domaine::ajouter(), Zone_Cl_VDF::associer(), Pave::associer_domaine(), Faces_VDF::calculer_orientation(), Matrice_Morse_Sym::compacte(), Matrice_Morse::compacte(), Faces::compare(), Partitionneur_Union::construire_partition(), Partitionneur_Tranche::construire_partition(), Partitionneur_Sous_Zones::construire_partition(), Partitionneur_Sous_Domaine::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_Metis::construire_partition(), Matrice_Dense::convert_to_morse_matrix(), copy(), Terme_Source_Solide_SWIFT_VDF::correspondance_SWIFT_coarse(), Aretes::dimensionner(), Matrice_Morse::dimensionner(), Ensemble_Lagrange_base::Ensemble_Lagrange_base(), Matrix_tools::extend_matrix(), Echange_contact_Correlation_VEF::init(), Traitement_particulier_Solide_canal_VDF::init_calcul_moyenne(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), Sonde_Int::initialiser(), Sonde::initialiser(), Matrice_Morse::inverse(), Solveur_U_P::iterer_NS(), Equation_base::lire_motcle_non_standard(), Perte_Charge_Singuliere::lire_surfaces(), lit(), Champ_front_recyclage::mettre_a_jour(), operator+(), Matrice_Morse::partie_sup(), Postraitement_lata::postraiter_liste_champs(), Solv_GCP::prepare_data(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), Sous_Zone::readOn(), Pave::readOn(), Champ_front_fonc_pois_tube::readOn(), Sous_Zone::remove_poly(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_Q1NC_impl::remplir_coord_noeuds_et_polys(), Champ_P1NC_implementation::remplir_coord_noeuds_et_polys(), Champ_Fonc_P0_VEF::remplir_coord_noeuds_et_polys(), Champ_Face_implementation::remplir_coord_noeuds_et_polys(), Champ_Fonc_P0_PolyMAC::remplir_coord_noeuds_et_polys(), Champ_Q4_implementation::remplir_coord_noeuds_et_polys(), Champ_implementation_P0::remplir_coord_noeuds_et_polys(), Champ_Fonc_P0_EF::remplir_coord_noeuds_et_polys(), Champ_Fonc_P0_CoviMAC::remplir_coord_noeuds_et_polys(), Champ_front_contact_VEF::remplir_elems_voisin_bord(), Champ_front_contact_VEF::remplir_faces_coin(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_CoviMAC_Face::remplir_num_faces(), DP_Impose_CoviMAC_Face::remplir_num_faces(), Traitement_particulier_NS_canal::reprendre_stat_canal(), resize_tab(), Traitement_particulier_NS_canal::Traitement_particulier_NS_canal(), Echange_contact_Correlation_VDF::trier_coord(), and Champ_Inc_base::valeur_aux().
{
// Verifie que l'objet est bien du type IntVect
  assert(n == size_array() || get_info() == IntVect::info());
  resize_vect_(n, opt);
}
void IntVect::resize_tab (int n, Array_base::Resize_Options opt = COPY_INIT) [virtual]
methode virtuelle identique a resize_array(), permet de traiter
de facon generique les ArrOf, Vect et Tab.
Cree un tableau sequentiel...
Si l'objet est de type IntVect, appel a resize(n)
Prerequis: voir resize()
Reimplemented from ArrOfInt.
Reimplemented in IntTab.
Definition at line 217 of file IntVect.cpp.
References resize().
{
  resize(n, opt);
}
void IntVect::resize_vect_ (int n, Array_base::Resize_Options opt = COPY_INIT) [inline, protected]
Methode interne de resize (appellee par IntTab::resize(...))
sans precondition sur le type de l'objet.
Definition at line 191 of file IntVect.h.
References Cerr, Process::exit(), finl, line_size_, md_vector_, MD_Vector::non_nul(), ArrOfInt::resize_array_(), and size_reelle_.
Referenced by IntTab::append_line(), resize(), IntTab::resize(), and IntTab::resize_dim0().
{
// Note B.M.: j'aurais voulu interdire completement resize des qu'on a un descripteur
// mais il y en a partout dans le code (on resize les tableaux alors qu'ils ont deja
// la bonne taille). Donc j'autorise si la taille ne change pas.
// assert(!md_vector_.non_nul() || n == size_array());
// PL: 1.7.0 is now strict about this point:
  if (md_vector_.non_nul())
    {
      Cerr << "Resize of a distributed array is forbidden!" << finl;
      exit();
    }
  assert(n == 0 || (n > 0 && line_size_ > 0 && n % line_size_ == 0));
  resize_array_(n, opt);
  size_reelle_ = n;
// ne pas mettre line_size_ a 1 ici, voir IntTab::resize_dim0()
}
const IntVect & IntVect::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from ArrOfInt.
Reimplemented in IntTab, and IntTrav.
Definition at line 38 of file IntVect.cpp.
IntVect & IntVect::self_cast (Objet_U & r) [static]
Reimplemented from ArrOfInt.
Reimplemented in IntTab, and IntTrav.
Definition at line 38 of file IntVect.cpp.
void IntVect::set_line_size_ (int n) [inline, protected]
change l'attribut line_size_ du tableau avec n >= 1
n == 0 est autorise uniquement si size_array_ == 0
Definition at line 163 of file IntVect.h.
References line_size_, md_vector_, and MD_Vector::non_nul().
Referenced by IntTab::IntTab(), IntTrav::IntTrav(), IntTab::readOn(), IntTab::ref_tab(), and IntTab::resize().
{
  assert(!md_vector_.non_nul() || line_size_ == n);
  assert(n >= 0);
  line_size_ = n;
}
void IntVect::set_md_vector (const MD_Vector & md_vector) [virtual]
associe le md_vector au vecteur et initialise l'attribut size_reelle_
(voir methode size_reelle())
Si md_vector est nul, detache simplement le md_vector existant.
< Cas particulier ou la size_reelle ne veut rien dire
Reimplemented in IntTab.
Definition at line 247 of file IntVect.cpp.
References Cerr, Process::exit(), finl, MD_Vector_base::get_nb_items_reels(), MD_Vector_base::get_nb_items_tot(), line_size_, md_vector_, MD_Vector::non_nul(), ArrOfInt::size_array(), size_reelle_, and MD_Vector::valeur().
Referenced by Zone_VDF::discretiser(), echanger_tableau_aretes(), and Solv_GCP::prepare_data().
{
  int size_r = size_array();
  if (md_vector.non_nul())
    {
      size_r = md_vector.valeur().get_nb_items_reels();
      if (size_r >= 0)
        size_r *= line_size_;
      else
        size_r = -1; //!< Cas particulier ou la size_reelle ne veut rien dire
      int size_tot = md_vector.valeur().get_nb_items_tot() * line_size_;
      if (size_tot != size_array())
        {
          Cerr << "Internal error in IntVect::set_md_vector(): wrong array size\n"
               << " Needed size = " << md_vector.valeur().get_nb_items_tot() << " x " << line_size_
               << "\n Actual size = " << size_array() << finl;
          exit();
        }
      if (line_size_ == 0)
        {
          Cerr << "Internal error in IntVect::set_md_vector():\n"
               << " cannot attach descriptor to empty array (line_size_ is zero)" << finl;
          exit();
        }
    }
  size_reelle_ = size_r;
  md_vector_ = md_vector;
}
int IntVect::size () const [inline]
Identique a size_reelle()
Definition at line 139 of file IntVect.h.
References size_reelle().
Referenced by Sous_Zone::add_poly(), Perte_Charge_VEF::ajouter(), Perte_Charge_Singuliere_VEF_Face::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), DP_Impose_PolyMAC_Face::ajouter(), Perte_Charge_Singuliere_VDF_Face::ajouter_(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_EF::assembler_mat(), Assembleur_P_CoviMAC::assembler_mat(), Perte_Charge_Singuliere::calculate_Q(), Scatter::calculer_espace_distant(), Matrice_Morse::check_morse_matrix_structure(), Matrice_Morse::check_sorted_morse_matrix_structure(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), Op_Conv_EF_VEF_P1NC_Stab::completer(), compute_global_connex_components(), Partitionneur_Sous_Zones::construire_partition(), Perte_Charge_VEF::contribuer_a_avec(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_Singuliere_VDF_Face::contribuer_a_avec(), Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec(), DP_Impose_PolyMAC_Face::contribuer_a_avec(), Zone_VDF::creer_elements_fictifs(), Matrice_Morse::dimensionner(), Faces::dimensionner(), Format_Post_Lml::ecrire_item_int_lml(), Matrix_tools::extend_matrix_stencil(), Zone_CoviMAC::fgrad(), Convection_Diffusion_Temperature::filtrage_si_appart_ibc(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Zone::init_faces_virt_bord(), Zone_PolyMAC::init_m2(), Zone_CoviMAC::init_stencils(), Sonde::initialiser(), Champ_Face_PolyMAC::interp_ve(), Decouper_multi::interpreter(), Lire_Tgrid::interpreter_(), IntTrav_test(), Matrice_Morse::inverse(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), Assembleur_P_VEFPreP1B::modifier_solution(), Sous_Zone::nb_elem_tot(), Matrice_Morse::nb_lignes(), operator<<(), ArrOfBit::operator=(), DP_Impose_PolyMAC_Face::readOn(), Sous_Zone::readOn(), DP_Impose_CoviMAC_Face::readOn(), Sous_Zone::remove_poly(), Champ_front_contact_VEF::remplir_faces_coin(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_CoviMAC_Face::remplir_num_faces(), DP_Impose_CoviMAC_Face::remplir_num_faces(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Zone_VEF::reordonner(), Zone_PolyMAC::reordonner(), Zone_EF::reordonner(), Zone_CoviMAC::reordonner(), reordonner_vdf(), IntTab_parts::size(), Champ_front_contact_VEF::test_faces_coin(), Convection_Diffusion_Temperature::transport_ibc(), Aretes::trier(), Aretes::trier_pour_debog(), Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_Q1NC_impl::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems(), Champ_implementation_sommet_base::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_Uniforme_Morceaux::valeur_aux_elems(), Champ_Tabule_Morceaux::valeur_aux_elems(), Champ_Fonc_Morceaux::valeur_aux_elems(), Champ_Fonc_Fonction_txyz_Morceaux::valeur_aux_elems(), Champ_Don_lu::valeur_aux_elems(), Champ_Fonc_Face_CoviMAC::valeur_aux_elems(), Champ_Face_CoviMAC::valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems_compo(), Champ_Q1NC_impl::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_Face_implementation::valeur_aux_elems_compo(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_implementation_sommet_base::valeur_aux_elems_compo(), Champ_implementation_P0::valeur_aux_elems_compo(), Champ_Uniforme_Morceaux::valeur_aux_elems_compo(), Champ_Fonc_Morceaux::valeur_aux_elems_compo(), Champ_Fonc_Fonction_txyz_Morceaux::valeur_aux_elems_compo(), Champ_Don_lu::valeur_aux_elems_compo(), Champ_Face_CoviMAC::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), and Debog_Pb::verifier_partie_std().
{
  return size_reelle();
}
int IntVect::size_reelle () const [inline]
Taille de l'espace "reel" du vecteur.
(si md_vector_ est nul, cette valeur est identique a size_array(),
sinon, soit elle est egale a md_vector_....get_nb_items(),
soit l'appel est invalide (en particulier si les items reels ne
sont pas regroupes en debut de tableau)
On peut interroger le vecteur pour savoir si size_reelle() est valide avec size_reelle_ok()
Definition at line 121 of file IntVect.h.
References md_vector_, MD_Vector::non_nul(), ArrOfInt::size_array(), and size_reelle_.
Referenced by Zone_Cl_VDF::completer(), Partitionneur_base::corriger_elem0_sur_proc0(), Decouper::ecrire(), DomaineCutter::ecrire_zones(), IntTab::operator=(), postraiter_decoupage(), IntTab::ref(), IntTab::ref_array(), IntTab::ref_data(), IntTab::ref_tab(), size(), and Traduction_Indice_Global_Local::traduire_espace_virtuel().
{
// Si cet assert plante, c'est que l'appel a ete declare invalide par le
// MD_Vect associe a ce vecteur.
  assert(size_reelle_ >= 0);
// Si cet assert plante, c'est que le tableau a ete redimensionne avec resize_array() au lieu de resize().
// (invalide pour un Vect ou un Tab).
  assert(size_array() == size_reelle_ || md_vector_.non_nul());
  return size_reelle_;
}
int IntVect::size_reelle_ok () const [inline]
Definition at line 133 of file IntVect.h.
References size_reelle_.
Referenced by IntTab::lit(), IntTab::operator=(), and IntTab::ref().
{
  return size_reelle_ >= 0;
}
int IntVect::size_totale () const [inline]
Identique a size_array()
Definition at line 145 of file IntVect.h.
References ArrOfInt::size_array().
Referenced by Debog_Pb::add_renum_item(), Periodique::completer(), compute_global_connex_components(), Zone::init_faces_virt_bord(), init_parts(), Traduction_Indice_Global_Local::initialiser(), local_carre_norme_vect(), local_imax_vect(), local_imin_vect(), local_max_abs_vect(), local_max_vect(), local_min_abs_vect(), local_min_vect(), local_prodscal(), local_somme_vect(), operator_abs(), operator_add(), operator_divide(), operator_egal(), operator_multiply(), operator_negate(), operator_sub(), Zone_PolyMAC::reordonner(), Zone_EF::reordonner(), Zone_CoviMAC::reordonner(), search_connex_components_local(), Traduction_Indice_Global_Local::traduire_espace_virtuel(), Debog_Pb::verifier_matrice(), and Debog_Pb::verifier_partie_std().
{
  return size_array();
}
unsigned IntVect::taille_memoire () const [virtual]
Reimplemented from ArrOfInt.
Reimplemented in IntTab, and IntTrav.
Definition at line 38 of file IntVect.cpp.
Member Data Documentation
const Type_info IntVect::info_obj [static]
Reimplemented from ArrOfInt.
Reimplemented in IntTab, and IntTrav.
Definition at line 39 of file IntVect.h.
int IntVect::line_size_ [private]
Definition at line 112 of file IntVect.h.
Referenced by copy_(), line_size(), readOn(), ref(), ref_array(), ref_data(), reset(), resize_vect_(), set_line_size_(), and set_md_vector().
MD_Vector IntVect::md_vector_ [private]
Definition at line 102 of file IntVect.h.
Referenced by copy(), copy_(), detach_vect(), get_md_vector(), printOn(), readOn(), ref(), ref_array(), ref_data(), reset(), resize_vect_(), set_line_size_(), set_md_vector(), and size_reelle().
int IntVect::size_reelle_ [private]
Definition at line 105 of file IntVect.h.
Referenced by copy_(), readOn(), ref(), ref_array(), ref_data(), reset(), resize_vect_(), set_md_vector(), size_reelle(), and size_reelle_ok().
The documentation for this class was generated from the following files:
src/Kernel/Math/IntVect.h
src/Kernel/Math/IntVect.cpp