TRUST: Op_Conv_Quick_VDF_Face Class Reference
Op_Conv_Quick_VDF_Face Class Reference
class Op_Conv_Quick_VDF_Face
Cette classe represente l'operateur de convection associe a une equation de
la quantite de mouvement.
La discretisation est VDF
Le champ convecte est de type Champ_Face
Le schema de convection est du type Quick
L'iterateur associe est de type Iterateur_VDF_Face
L'evaluateur associe est de type Eval_Quick_VDF_Face
#include <Op_Conv_Quick_VDF_Face.h>
Public Member Functions
~Op_Conv_Quick_VDF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Op_Conv_Quick_VDF_Face ()
constructeur
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
complete l'iterateur et l'evaluateur
void associer_vitesse (const Champ_base &)
associe le champ de vitesse a l'evaluateur
const Champ_Inc_base & vitesse () const
Champ_Inc_base & vitesse ()
void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Conv_Quick_VDF_Face & self_cast (Objet_U &)
static const
Op_Conv_Quick_VDF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Detailed Description
class Op_Conv_Quick_VDF_Face
Cette classe represente l'operateur de convection associe a une equation de
la quantite de mouvement.
La discretisation est VDF
Le champ convecte est de type Champ_Face
Le schema de convection est du type Quick
L'iterateur associe est de type Iterateur_VDF_Face
L'evaluateur associe est de type Eval_Quick_VDF_Face
Definition at line 56 of file Op_Conv_Quick_VDF_Face.h.
Constructor & Destructor Documentation
Op_Conv_Quick_VDF_Face::~Op_Conv_Quick_VDF_Face ()
Definition at line 26 of file Op_Conv_Quick_VDF_Face.cpp.
Op_Conv_Quick_VDF_Face::Op_Conv_Quick_VDF_Face ()
constructeur
Definition at line 88 of file Op_Conv_Quick_VDF_Face.cpp.
                                               :
  Op_Conv_VDF_base(It_VDF_Face(Eval_Quick_VDF_Face)())
{
}
Member Function Documentation
void Op_Conv_Quick_VDF_Face::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_vit) [virtual]
complete l'iterateur et l'evaluateur
< Evaluateur_VDF::associer_zones
< Eval_VDF_Face::associer_inconnue
Implements Operateur_base.
Definition at line 49 of file Op_Conv_Quick_VDF_Face.cpp.
References Iterateur_VDF::associer(), Eval_VDF_Face::associer_inconnue(), Evaluateur_VDF::associer_zones(), Cerr, Joint::epaisseur(), Iterateur_VDF::evaluateur(), Process::exit(), finl, Op_Conv_VDF_base::iter, Zone::joint(), Zone::nb_joints(), Process::nproc(), ref_cast, Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), and Zone_dis_base::zone().
{
  const Zone_VDF& zvdf = ref_cast(Zone_VDF,zone_dis.valeur());
  const Zone_Cl_VDF& zclvdf = ref_cast(Zone_Cl_VDF,zone_cl_dis.valeur());
  const Champ_Face& vit = ref_cast(Champ_Face,ch_vit.valeur());
  iter.associer(zvdf, zclvdf, *this);
  Eval_Quick_VDF_Face& eval_conv = (Eval_Quick_VDF_Face&) iter.evaluateur();
  eval_conv.associer_zones(zvdf, zclvdf );          //!< Evaluateur_VDF::associer_zones
  eval_conv.associer_inconnue(vit);        //!< Eval_VDF_Face::associer_inconnue
  if (Process::nproc()>1 && zvdf.zone().nb_joints() && zvdf.zone().joint(0).epaisseur()<2)
    {
      Cerr << "Overlapping width (given by larg_joint option) of  " << zvdf.zone().joint(0).epaisseur() << finl;
      Cerr << "is not enough for Quick scheme in VDF parallel calculation." << finl;
      Cerr << "Please, partition your mesh with an overlapping width of 2 with larg_joint option." << finl;
      Process::exit();
    }
}
void Op_Conv_Quick_VDF_Face::associer_vitesse (const Champ_base & ch_vit) [inline, virtual]
associe le champ de vitesse a l'evaluateur
< Eval_Conv_VDF::associer
Implements Operateur_Conv_base.
Definition at line 75 of file Op_Conv_Quick_VDF_Face.h.
References Eval_Conv_VDF::associer(), Iterateur_VDF::evaluateur(), and Op_Conv_VDF_base::iter.
{
  const Champ_Face& vit = (Champ_Face&) ch_vit;
  Eval_Quick_VDF_Face& eval_conv = (Eval_Quick_VDF_Face&) iter.evaluateur();
  eval_conv.associer(vit );                //!< Eval_Conv_VDF::associer
}
Objet_U * Op_Conv_Quick_VDF_Face::cree_instance () [static]
Definition at line 26 of file Op_Conv_Quick_VDF_Face.cpp.
void Op_Conv_Quick_VDF_Face::dimensionner (Matrice_Morse & mat) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 83 of file Op_Conv_Quick_VDF_Face.h.
References Op_Conv_VDF_base::iter, Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
{
  Op_VDF_Face::dimensionner(iter.zone(), iter.zone_Cl(), matrice);
}
int Op_Conv_Quick_VDF_Face::duplique () const [virtual]
Implements Op_Conv_VDF_base.
Definition at line 26 of file Op_Conv_Quick_VDF_Face.cpp.
const Type_info * Op_Conv_Quick_VDF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_VDF_base.
Definition at line 26 of file Op_Conv_Quick_VDF_Face.cpp.
const Type_info * Op_Conv_Quick_VDF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_VDF_base.
Definition at line 26 of file Op_Conv_Quick_VDF_Face.cpp.
void Op_Conv_Quick_VDF_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 88 of file Op_Conv_Quick_VDF_Face.h.
References Op_Conv_VDF_base::iter, Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
{
  Op_VDF_Face::modifier_pour_Cl(iter.zone(), iter.zone_Cl(), matrice, secmem);
}
Sortie & Op_Conv_Quick_VDF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Conv_VDF_base.
Definition at line 33 of file Op_Conv_Quick_VDF_Face.cpp.
{
  return s << que_suis_je() ;
}
Entree & Op_Conv_Quick_VDF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Conv_VDF_base.
Definition at line 41 of file Op_Conv_Quick_VDF_Face.cpp.
{
  return s ;
}
const Op_Conv_Quick_VDF_Face & Op_Conv_Quick_VDF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Conv_VDF_base.
Definition at line 26 of file Op_Conv_Quick_VDF_Face.cpp.
Op_Conv_Quick_VDF_Face & Op_Conv_Quick_VDF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Op_Conv_VDF_base.
Definition at line 26 of file Op_Conv_Quick_VDF_Face.cpp.
unsigned Op_Conv_Quick_VDF_Face::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Op_Conv_Quick_VDF_Face.cpp.
Champ_Inc_base & Op_Conv_Quick_VDF_Face::vitesse () [virtual]
Implements Op_Conv_VDF_base.
Definition at line 77 of file Op_Conv_Quick_VDF_Face.cpp.
References Iterateur_VDF::evaluateur(), Op_Conv_VDF_base::iter, and Eval_Conv_VDF::vitesse().
{
  Eval_Quick_VDF_Face& eval_conv = (Eval_Quick_VDF_Face&) iter.evaluateur();
  return eval_conv.vitesse();
}
const Champ_Inc_base & Op_Conv_Quick_VDF_Face::vitesse () const [virtual]
Implements Op_Conv_VDF_base.
Definition at line 71 of file Op_Conv_Quick_VDF_Face.cpp.
References Iterateur_VDF::evaluateur(), Op_Conv_VDF_base::iter, and Eval_Conv_VDF::vitesse().
{
  Eval_Quick_VDF_Face& eval_conv = (Eval_Quick_VDF_Face&) iter.evaluateur();
  return eval_conv.vitesse();
}
Member Data Documentation
const Type_info Op_Conv_Quick_VDF_Face::info_obj [static]
Reimplemented from Op_Conv_VDF_base.
Definition at line 59 of file Op_Conv_Quick_VDF_Face.h.
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Op_Conv_Quick_VDF_Face.h
src/VDF/Operateurs/Op_Conv_Quick_VDF_Face.cpp