TRUST: Reorienter_triangles Class Reference
Reorienter_triangles Class Reference
#include <Reorienter_triangles.h>
Public Member Functions
Reorienter_triangles ()
~Reorienter_triangles ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &)
void Reorienter (Domaine &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Reorienter_triangles & self_cast (Objet_U &)
static const Reorienter_triangles & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Types
enum Sens { DIRECT, INDIRECT }
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Reorienter_triangles::Sens test_orientation_triangle (IntTab &les_elems, int ielem, const DoubleTab &coord_sommets) const
Reorienter_triangles::Sens reorienter_triangle (IntTab &les_elems, int ielem) const
Detailed Description
Definition at line 40 of file Reorienter_triangles.h.
Member Enumeration Documentation
enum Reorienter_triangles::Sens [protected]
Enumerator:
DIRECT
INDIRECT
Definition at line 50 of file Reorienter_triangles.h.
{DIRECT , INDIRECT};
Constructor & Destructor Documentation
Reorienter_triangles::Reorienter_triangles ()
Definition at line 26 of file Reorienter_triangles.cpp.
Reorienter_triangles::~Reorienter_triangles ()
Definition at line 26 of file Reorienter_triangles.cpp.
Member Function Documentation
Objet_U * Reorienter_triangles::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 26 of file Reorienter_triangles.cpp.
int Reorienter_triangles::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 26 of file Reorienter_triangles.cpp.
const Type_info * Reorienter_triangles::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Reorienter_triangles.cpp.
const Type_info * Reorienter_triangles::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Reorienter_triangles.cpp.
Entree & Reorienter_triangles::interpreter_ (Entree & is) [virtual]
Implements Interprete_geometrique_base.
Definition at line 38 of file Reorienter_triangles.cpp.
References Interprete_geometrique_base::associer_domaine(), Cerr, Objet_U::dimension, Interprete_geometrique_base::domaine(), Process::exit(), finl, Scatter::init_sequential_domain(), Reorienter(), and Scatter::uninit_sequential_domain().
{
  Cerr << "Reorientation of triangles for either direct..." << finl;
  if (dimension != 2)
    {
      Cerr << "we can not reorientate (Reorienter) triangles in dimension " << dimension <<finl;
      exit();
    }
  Nom nom_dom, typ_zone;
  associer_domaine(is);
  Domaine& dom=domaine();
  Scatter::uninit_sequential_domain(dom);
  Reorienter(dom);
  Scatter::init_sequential_domain(dom);
  Cerr << "Reorientation of triangles... OK" << finl;
  return is;
}
Sortie & Reorienter_triangles::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Reorienter_triangles.cpp.
{
  return Interprete::printOn(os);
}
Entree & Reorienter_triangles::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 33 of file Reorienter_triangles.cpp.
{
  return Interprete::readOn(is);
}
void Reorienter_triangles::Reorienter (Domaine & dom) const
Definition at line 108 of file Reorienter_triangles.cpp.
References Domaine::coord_sommets(), IntTab::dimension(), finl, INDIRECT, Process::Journal(), Zone::les_elems(), Domaine::nb_zones(), Objet_U::que_suis_je(), reorienter_triangle(), test_orientation_triangle(), Zone::type_elem(), and Domaine::zone().
Referenced by interpreter_().
{
  const DoubleTab& coord_sommets = dom.coord_sommets();
  int nb_zones = dom.nb_zones();
  int iz;
// on balaye les zones du domaine
  for(iz=0 ; iz<nb_zones ; iz++)
    {
      Zone& zone = dom.zone(iz);
      if (zone.type_elem()->que_suis_je() == "Triangle" )
        {
// zone de triangles
          IntTab& les_elems = zone.les_elems();
          int nb_elems = les_elems.dimension(0);
          int ielem;
// balaye les triangles
          for (ielem=0 ; ielem<nb_elems ; ielem++)
            {
              if (test_orientation_triangle(les_elems, ielem, coord_sommets)==INDIRECT)
                {
// triangle oriente en sens indirect -> a reorienter
                  reorienter_triangle(les_elems, ielem);
#ifdef _AFFDEBUG
                  {
                    Process::Journal<<"  #element reoriente "<<ielem<<finl;
                    static const int SOM_Z = 0;
                    static const int SOM_A = 1;
                    static const int SOM_B = 2;
                    const int som_Z = les_elems(ielem,SOM_Z);
                    const int som_A = les_elems(ielem,SOM_A);
                    const int som_B = les_elems(ielem,SOM_B);
                    Process::Journal<<"    somZ= "<<som_Z<<"  coords= "<<coord_sommets(som_Z, 0)<<" "<<coord_sommets(som_Z, 1)<<finl;
                    Process::Journal<<"    somA= "<<som_A<<"  coords= "<<coord_sommets(som_A, 0)<<" "<<coord_sommets(som_A, 1)<<finl;
                    Process::Journal<<"    somB= "<<som_B<<"  coords= "<<coord_sommets(som_B, 0)<<" "<<coord_sommets(som_B, 1)<<finl;
                  }
#endif
                }
            }
        }
    }//fin balayage zones
}
Reorienter_triangles::Sens Reorienter_triangles::reorienter_triangle (IntTab & les_elems, int ielem) const [protected]
Definition at line 94 of file Reorienter_triangles.cpp.
References DIRECT.
Referenced by Reorienter().
{
  static const int SOM_A = 1;
  static const int SOM_B = 2;
// pour reorienter le triangle, on va permuter les sommets 1 et 2
  int tmp;
  tmp = les_elems(num_element,SOM_A);
  les_elems(num_element,SOM_A) = les_elems(num_element,SOM_B);
  les_elems(num_element,SOM_B) = tmp;
  return DIRECT;
}
const Reorienter_triangles & Reorienter_triangles::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Reorienter_triangles.cpp.
Reorienter_triangles & Reorienter_triangles::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Reorienter_triangles.cpp.
unsigned Reorienter_triangles::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 26 of file Reorienter_triangles.cpp.
Reorienter_triangles::Sens Reorienter_triangles::test_orientation_triangle (IntTab & les_elems, int ielem, const DoubleTab & coord_sommets) const [protected]
Definition at line 57 of file Reorienter_triangles.cpp.
References DIRECT, finl, INDIRECT, and Process::Journal().
Referenced by Reorienter().
{
  static const int SOM_Z = 0;
  static const int SOM_A = 1;
  static const int SOM_B = 2;
  const int som_Z = les_elems(num_element,SOM_Z);
  const int som_A = les_elems(num_element,SOM_A);
  const int som_B = les_elems(num_element,SOM_B);
  double ZA0 = coord_sommets(som_A,0) - coord_sommets(som_Z,0);
  double ZB0 = coord_sommets(som_B,0) - coord_sommets(som_Z,0);
  double ZA1 = coord_sommets(som_A,1) - coord_sommets(som_Z,1);
  double ZB1 = coord_sommets(som_B,1) - coord_sommets(som_Z,1);
// calcul pdt vect ZAxZB
  double pdtvect = ZA0*ZB1 - ZA1*ZB0;
  if (pdtvect<0.)
    {
// le pdt scalaire est negatif : il s'agit d'un triangle mal oriente
#ifdef _AFFDEBUG
      {
        Process::Journal<<"  element "<<num_element<<"  indirect"<<finl;
      }
#endif
      return INDIRECT;
    }
#ifdef _AFFDEBUG
  {
    Process::Journal<<"  element "<<num_element<<"  direct"<<finl;
  }
#endif
  return DIRECT;
}
Member Data Documentation
const Type_info Reorienter_triangles::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 42 of file Reorienter_triangles.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Reorienter_triangles.h
src/Kernel/Geometrie/Reorienter_triangles.cpp