TRUST: Sous_zone_dis Class Reference
Sous_zone_dis Class Reference
#include <Sous_zone_dis.h>
Public Member Functions
Sous_zone_dis ()
~Sous_zone_dis ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_sous_zone (const Sous_Zone &ssz)
void associer_zone_dis (const Zone_dis_base &zd)
void discretiser ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Sous_zone_dis & self_cast (Objet_U &)
static const Sous_zone_dis & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Detailed Description
Un objet de type Sous_zone_dis peut referencer n'importe quel objet derivant de Sous_zone_dis_base. ! Classe generique de la hierarchie des sous-zones discretisees.
Definition at line 37 of file Sous_zone_dis.h.
Constructor & Destructor Documentation
Sous_zone_dis::Sous_zone_dis ()
Definition at line 26 of file Sous_zone_dis.cpp.
Sous_zone_dis::~Sous_zone_dis ()
Definition at line 26 of file Sous_zone_dis.cpp.
Member Function Documentation
void Sous_zone_dis::associer_sous_zone (const Sous_Zone & ssz) [inline]
Definition at line 44 of file Sous_zone_dis.h.
References Sous_zone_dis_base::associer_sous_zone(), and Deriv_Sous_zone_dis_base::valeur().
Referenced by Domaine_dis::discretiser().
  {
    valeur().associer_sous_zone(ssz);
  }
void Sous_zone_dis::associer_zone_dis (const Zone_dis_base & zd) [inline]
Definition at line 48 of file Sous_zone_dis.h.
References Sous_zone_dis_base::associer_zone_dis(), and Deriv_Sous_zone_dis_base::valeur().
Referenced by Domaine_dis::discretiser().
  {
    valeur().associer_zone_dis(zd);
  }
Objet_U * Sous_zone_dis::cree_instance () [static]
Reimplemented from Deriv_Sous_zone_dis_base.
Definition at line 26 of file Sous_zone_dis.cpp.
void Sous_zone_dis::discretiser () [inline]
Definition at line 52 of file Sous_zone_dis.h.
References Sous_zone_dis_base::discretiser(), and Deriv_Sous_zone_dis_base::valeur().
Referenced by Domaine_dis::discretiser().
  {
    valeur().discretiser();
  }
int Sous_zone_dis::duplique () const [virtual]
Reimplemented from Deriv_Sous_zone_dis_base.
Definition at line 26 of file Sous_zone_dis.cpp.
const Type_info * Sous_zone_dis::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Sous_zone_dis_base.
Definition at line 26 of file Sous_zone_dis.cpp.
const Type_info * Sous_zone_dis::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Sous_zone_dis_base.
Definition at line 26 of file Sous_zone_dis.cpp.
Sortie & Sous_zone_dis::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_Sous_zone_dis_base.
Definition at line 29 of file Sous_zone_dis.cpp.
References DERIV.
{
  return DERIV(Sous_zone_dis_base)::printOn(os);
}
Entree & Sous_zone_dis::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_Sous_zone_dis_base.
Definition at line 34 of file Sous_zone_dis.cpp.
References DERIV.
{
  return DERIV(Sous_zone_dis_base)::readOn(is);
}
const Sous_zone_dis & Sous_zone_dis::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Sous_zone_dis_base.
Definition at line 26 of file Sous_zone_dis.cpp.
Sous_zone_dis & Sous_zone_dis::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Sous_zone_dis_base.
Definition at line 26 of file Sous_zone_dis.cpp.
unsigned Sous_zone_dis::taille_memoire () const [virtual]
Reimplemented from Deriv_Sous_zone_dis_base.
Definition at line 26 of file Sous_zone_dis.cpp.
Member Data Documentation
const Type_info Sous_zone_dis::info_obj [static]
Reimplemented from Deriv_Sous_zone_dis_base.
Definition at line 40 of file Sous_zone_dis.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Sous_zone_dis.h
src/Kernel/Framework/Sous_zone_dis.cpp