TRUST: ModPerm_Cte Class Reference
ModPerm_Cte Class Reference
Cette classe represente une permeabilite cte.
#include <ModPerm_Cte.h>
Public Member Functions
~ModPerm_Cte ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
ModPerm_Cte ()
double getK (double porosite) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static ModPerm_Cte & self_cast (Objet_U &)
static const ModPerm_Cte & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le type du modele sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit les specifications d'un modele Permeabilite
a partir d'un flot d'entree.
Controle dynamique du type du terme source.
Private Attributes
double cte
Detailed Description
Cette classe represente une permeabilite cte.
Definition at line 34 of file ModPerm_Cte.h.
Constructor & Destructor Documentation
ModPerm_Cte::~ModPerm_Cte ()
Definition at line 26 of file ModPerm_Cte.cpp.
ModPerm_Cte::ModPerm_Cte ()
Definition at line 28 of file ModPerm_Cte.cpp.
: cte(1.) { }
Member Function Documentation
Objet_U * ModPerm_Cte::cree_instance () [static]
Definition at line 26 of file ModPerm_Cte.cpp.
int ModPerm_Cte::duplique () const [virtual]
Implements Modele_Permeabilite_base.
Definition at line 26 of file ModPerm_Cte.cpp.
const Type_info * ModPerm_Cte::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Modele_Permeabilite_base.
Definition at line 26 of file ModPerm_Cte.cpp.
double ModPerm_Cte::getK (double porosite) const [inline, virtual]
Renvoie la valeur de la permeabilite en fonction de la porosite (d'une face par exemple).
Parameters:
porosite la porosite
Implements Modele_Permeabilite_base.
Definition at line 56 of file ModPerm_Cte.h.
References cte.
{
// assert(porosite != 1.);
  return cte;
}
const Type_info * ModPerm_Cte::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Modele_Permeabilite_base.
Definition at line 26 of file ModPerm_Cte.cpp.
Sortie & ModPerm_Cte::printOn (Sortie & s) const [protected, virtual]
Imprime le type du modele sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Modele_Permeabilite_base.
Definition at line 45 of file ModPerm_Cte.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & ModPerm_Cte::readOn (Entree & is) [protected, virtual]
Lit les specifications d'un modele Permeabilite
a partir d'un flot d'entree.
Controle dynamique du type du terme source.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Modele_Permeabilite_base.
Definition at line 67 of file ModPerm_Cte.cpp.
References Cerr, cte, Process::exit(), finl, Objet_U::que_suis_je(), and Motcles::search().
{
  Motcles les_mots(1);
  {
    les_mots[0] = "valeur";
  }
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
  is >> motlu;
  if(motlu!=accolade_ouverte)
    {
      Cerr << "On attendait une { a la lecture d'une " << que_suis_je() << finl;
      Cerr << "et non : " << motlu << finl;
      exit();
    }
  is >> motlu;
  while (motlu != accolade_fermee)
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          {
            is >> cte;
            break;
          }
        default :
          {
            Cerr << "Mot cle inconnu dans ModPerm_Cte  " << finl;
            exit();
          }
        }
      is >> motlu;
    }
// Cout << "<<<<<<<<<<<<<<Dans ModPerm_Cte cte = " << cte << finl;
  return is;
}
ModPerm_Cte & ModPerm_Cte::self_cast (Objet_U & r) [static]
Reimplemented from Modele_Permeabilite_base.
Definition at line 26 of file ModPerm_Cte.cpp.
const ModPerm_Cte & ModPerm_Cte::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Modele_Permeabilite_base.
Definition at line 26 of file ModPerm_Cte.cpp.
unsigned ModPerm_Cte::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file ModPerm_Cte.cpp.
Member Data Documentation
double ModPerm_Cte::cte [private]
Definition at line 52 of file ModPerm_Cte.h.
Referenced by getK(), and readOn().
const Type_info ModPerm_Cte::info_obj [static]
Reimplemented from Modele_Permeabilite_base.
Definition at line 37 of file ModPerm_Cte.h.
The documentation for this class was generated from the following files:
src/VDF/Sources/ModPerm_Cte.h
src/VDF/Sources/ModPerm_Cte.cpp