TRUST: ConstTRUSTTab_parts< _TYPE_ > Class Template Reference
ConstTRUSTTab_parts< _TYPE_ > Class Template Reference
This class allows to acces to individual sub-parts of const DoubleTab objects that have a MD_Vector_composite descriptor.
It is designed to preserve the const-ness of the object.
#include <TRUSTTab_parts.h>
Public Member Functions
ConstTRUSTTab_parts ()
ConstTRUSTTab_parts (const TRUSTVect< _TYPE_ > &)
void initialize (const TRUSTVect< _TYPE_ > &)
void reset ()
const TRUSTTab< _TYPE_ > & operator[] (int i) const
int size () const
Private Member Functions
ConstTRUSTTab_parts & operator= (const ConstTRUSTTab_parts &)=delete
ConstTRUSTTab_parts (const ConstTRUSTTab_parts &)=delete
Private Attributes
TRUST_Vector< TRUSTTab, _TYPE_ > parts_
Et ouiiiiiiiiiiiiiiii.
Detailed Description
template<typename _TYPE_>
class ConstTRUSTTab_parts< _TYPE_ >
This class allows to acces to individual sub-parts of const DoubleTab objects that have a MD_Vector_composite descriptor.
It is designed to preserve the const-ness of the object.
Definition at line 54 of file TRUSTTab_parts.h.
Constructor & Destructor Documentation
ConstTRUSTTab_parts() [1/3]
template<typename _TYPE_ > ConstTRUSTTab_parts< _TYPE_ >::ConstTRUSTTab_parts () inline
Definition at line 57 of file TRUSTTab_parts.h.
{ }
ConstTRUSTTab_parts() [2/3]
template<typename _TYPE_ > ConstTRUSTTab_parts< _TYPE_ >::ConstTRUSTTab_parts (const TRUSTVect< _TYPE_ > & vect)
Definition at line 98 of file TRUSTTab_parts.tpp.
{
  TRUSTVect<_TYPE_>& vect2 = const_cast<TRUSTVect<_TYPE_>&>(vect);
  init_parts<_TYPE_>(vect2, parts_, static_cast<TRUSTTab<_TYPE_>*>(0));
}
ConstTRUSTTab_parts() [3/3]
template<typename _TYPE_ > ConstTRUSTTab_parts< _TYPE_ >::ConstTRUSTTab_parts (const ConstTRUSTTab_parts< _TYPE_ > &) private delete
Member Function Documentation
initialize()
template<typename _TYPE_ > void ConstTRUSTTab_parts< _TYPE_ >::initialize (const TRUSTVect< _TYPE_ > & vect)
Definition at line 105 of file TRUSTTab_parts.tpp.
{
  reset();
  TRUSTVect<_TYPE_>& vect2 = const_cast<TRUSTVect<_TYPE_>&>(vect);
  init_parts<_TYPE_>(vect2, parts_, static_cast<TRUSTTab<_TYPE_>*>(0));
}
Referenced by SSOR::ssor().
operator=()
template<typename _TYPE_ > ConstTRUSTTab_parts & ConstTRUSTTab_parts< _TYPE_ >::operator= (const ConstTRUSTTab_parts< _TYPE_ > &) private delete
operator[]()
template<typename _TYPE_ > const TRUSTTab< _TYPE_ > & ConstTRUSTTab_parts< _TYPE_ >::operator[] (int i) const inline
Definition at line 61 of file TRUSTTab_parts.h.
{ return parts_[i]; }
References ConstTRUSTTab_parts< _TYPE_ >::parts_.
reset()
template<typename _TYPE_ > void ConstTRUSTTab_parts< _TYPE_ >::reset () inline
Definition at line 60 of file TRUSTTab_parts.h.
{ parts_.dimensionner_force(0); }
References vect_impl::dimensionner_force(), and ConstTRUSTTab_parts< _TYPE_ >::parts_.
size()
template<typename _TYPE_ > int ConstTRUSTTab_parts< _TYPE_ >::size () const inline
Definition at line 62 of file TRUSTTab_parts.h.
{ return parts_.size(); }
References ConstTRUSTTab_parts< _TYPE_ >::parts_, and vect_impl::size().
Referenced by Debog_Pb::ecrire_partie(), ecriture_special_part2(), SETS::eliminer(), PrecondA::prepare_(), and Debog_Pb::verifier_partie().
Member Data Documentation
parts_
template<typename _TYPE_ > TRUST_Vector<TRUSTTab,_TYPE_> ConstTRUSTTab_parts< _TYPE_ >::parts_ private
Et ouiiiiiiiiiiiiiiii.
Definition at line 69 of file TRUSTTab_parts.h.
Referenced by ConstTRUSTTab_parts< _TYPE_ >::operator[](), ConstTRUSTTab_parts< _TYPE_ >::reset(), and ConstTRUSTTab_parts< _TYPE_ >::size().
The documentation for this class was generated from the following files:
src/Kernel/Math/TRUSTTab_parts.h
src/Kernel/Math/TRUSTTab_parts.tpp