TRUST: Champ_front_normal Class Reference
Champ_front_normal Class Reference
class Champ_front_normal
#include <Champ_front_normal.h>
Public Member Functions
Champ_front_normal ()
~Champ_front_normal ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Champ_front_base & affecter_ (const Champ_front_base &ch)
Pas code !!
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_front_normal & self_cast (Objet_U &)
static const Champ_front_normal & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le nom du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Parser_U vit_norm
Detailed Description
class Champ_front_normal
Definition at line 33 of file Champ_front_normal.h.
Constructor & Destructor Documentation
Champ_front_normal::Champ_front_normal ()
Definition at line 27 of file Champ_front_normal.cpp.
Champ_front_normal::~Champ_front_normal ()
Definition at line 27 of file Champ_front_normal.cpp.
Member Function Documentation
Champ_front_base & Champ_front_normal::affecter_ (const Champ_front_base & ch) [virtual]
Pas code !!
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 59 of file Champ_front_normal.cpp.
{
// Cerr<<"avant de retourner"<<finl;
  return *this;
}
Objet_U * Champ_front_normal::cree_instance () [static]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Champ_front_debit, Champ_front_debit_massique, and Champ_front_xyz_debit.
Definition at line 27 of file Champ_front_normal.cpp.
int Champ_front_normal::duplique () const [virtual]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Champ_front_debit, Champ_front_debit_massique, and Champ_front_xyz_debit.
Definition at line 27 of file Champ_front_normal.cpp.
const Type_info * Champ_front_normal::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Champ_front_debit, Champ_front_debit_massique, and Champ_front_xyz_debit.
Definition at line 27 of file Champ_front_normal.cpp.
const Type_info * Champ_front_normal::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Champ_front_debit, Champ_front_debit_massique, and Champ_front_xyz_debit.
Definition at line 27 of file Champ_front_normal.cpp.
Sortie & Champ_front_normal::printOn (Sortie & s) const [protected, virtual]
Imprime le nom du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Champ_front_debit, Champ_front_debit_massique, and Champ_front_xyz_debit.
Definition at line 30 of file Champ_front_normal.cpp.
References DoubleVect::size(), and Champ_front_base::valeurs().
{
  const DoubleTab& tab=valeurs();
  os << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    os << tab(0,i);
  return os;
}
Entree & Champ_front_normal::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Champ_front_debit, Champ_front_debit_massique, and Champ_front_xyz_debit.
Definition at line 40 of file Champ_front_normal.cpp.
References Parser_U::addVar(), Param::ajouter(), Objet_U::dimension, Field_base::fixer_nb_comp(), Param::lire_avec_accolades(), Parser_U::parseString(), Objet_U::que_suis_je(), Parser_U::setNbVar(), Parser_U::setString(), and vit_norm.
{
  Nom expr_vit_norm;
  Param param(que_suis_je());
  param.ajouter("normal_value", &expr_vit_norm);
  param.lire_avec_accolades(is);
  fixer_nb_comp(dimension);
  vit_norm.setNbVar(1);
  vit_norm.addVar("t");
  vit_norm.setString(expr_vit_norm);
  vit_norm.parseString();
  return is;
}
const Champ_front_normal & Champ_front_normal::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Champ_front_debit, Champ_front_debit_massique, and Champ_front_xyz_debit.
Definition at line 27 of file Champ_front_normal.cpp.
Champ_front_normal & Champ_front_normal::self_cast (Objet_U & r) [static]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Champ_front_debit, Champ_front_debit_massique, and Champ_front_xyz_debit.
Definition at line 27 of file Champ_front_normal.cpp.
unsigned Champ_front_normal::taille_memoire () const [virtual]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Champ_front_debit, Champ_front_debit_massique, and Champ_front_xyz_debit.
Definition at line 27 of file Champ_front_normal.cpp.
Member Data Documentation
const Type_info Champ_front_normal::info_obj [static]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Champ_front_debit, Champ_front_debit_massique, and Champ_front_xyz_debit.
Definition at line 35 of file Champ_front_normal.h.
Parser_U Champ_front_normal::vit_norm [protected]
Definition at line 43 of file Champ_front_normal.h.
Referenced by Boundary_field_inward::mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_front_normal.h
src/Kernel/Champs/Champ_front_normal.cpp