TRUST: Champ_Generique_Extraction Class Reference
Champ_Generique_Extraction Class Reference
Un champ generique qui effctue l extraction d un champ sur une frontiere.
#include <Champ_Generique_Extraction.h>
Public Member Functions
~Champ_Generique_Extraction ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_Generique_Extraction ()
voir reset()
void set_param (Param &param) override
Entity get_localisation (const int index=-1) const override
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
const Champ_base & get_champ (Champ &espace_stockage) const override
Extraction des valeurs d un champ (trace ou champ frontiere) sur un bord du domaine.
const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const override
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
void nommer_source () override
void completer (const Postraitement_base &post) override
const Domaine & get_ref_domain () const override
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
void get_copy_domain (Domaine &) const override
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_dis_base & get_ref_zone_dis_base () const override
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
void discretiser_domaine ()
const Motcle get_directive_pour_discr () const override
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
Champ_Gen_de_Champs_Gen ()
~Champ_Gen_de_Champs_Gen () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual List_Champ_Generique & get_set_sources ()
virtual Champ_Generique & get_set_source ()
void reset () override
int sauvegarder (Sortie &os) const override
sauvegarde des differentes sources
int reprendre (Entree &is) override
reprise des differentes sources
void completer (const Postraitement_base &post) override
void mettre_a_jour (double temps) override
virtual Champ_Fonc & creer_espace_stockage (const Nature_du_champ &nature, const int nb_comp, Champ_Fonc &es_tmp) const
virtual const Champ_Generique_base & get_source (int i) const
virtual Champ_Generique_base & set_source (int i)
virtual int get_nb_sources () const
int get_dimension () const override
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
void get_property_names (Motcles &list) const override
Renvoie la liste des "query" possibles pour le champ.
double get_time () const override
Renvoie le temps du Champ_Generique.
const Probleme_base & get_ref_pb_base () const override
const Discretisation_base & get_discretisation () const override
const Motcle get_directive_pour_discr () const override
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Entity get_localisation (const int index=-1) const override
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
const DoubleTab & get_ref_values () const override
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_copy_values (DoubleTab &) const override
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
const Domaine & get_ref_domain () const override
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
void get_copy_domain (Domaine &) const override
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_dis_base & get_ref_zone_dis_base () const override
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_Cl_dis_base & get_ref_zcl_dis_base () const override
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
const DoubleTab & get_ref_coordinates () const override
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
void get_copy_coordinates (DoubleTab &) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const override
void nommer_sources ()
virtual void nommer_source ()
int get_info_type_post () const override
const Champ_Generique_base & get_champ_post (const Motcle &nom) const override
int comprend_champ_post (const Motcle &identifiant) const override
virtual void fixer_serie (const double t1, const double t2)
virtual void fixer_tstat_deb (const double t1, const double t2)
virtual void lire_bidon (Entree &is) const
Public Member Functions inherited from Champ_Generique_base
Champ_Generique_base ()
~Champ_Generique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int get_dimension () const
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
virtual double get_time () const
Renvoie le temps du Champ_Generique.
virtual const Probleme_base & get_ref_pb_base () const
virtual const Discretisation_base & get_discretisation () const
virtual const Motcle get_directive_pour_discr () const
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
virtual const Nom & get_nom_post () const
virtual void get_property_names (Motcles &list) const
Renvoie la liste des "query" possibles pour le champ.
virtual const Noms get_property (const Motcle &query) const
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
virtual Entity get_localisation (const int index=-1) const
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
virtual int get_nb_localisations () const
virtual const DoubleTab & get_ref_values () const
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_copy_values (DoubleTab &) const
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const
virtual const Domaine & get_ref_domain () const
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual void get_copy_domain (Domaine &) const
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_dis_base & get_ref_zone_dis_base () const
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_Cl_dis_base & get_ref_zcl_dis_base () const
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
virtual const DoubleTab & get_ref_coordinates () const
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
virtual void get_copy_coordinates (DoubleTab &) const
virtual const IntTab & get_ref_connectivity (Entity index1, Entity index2) const
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
virtual void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const
virtual void reset ()=0
virtual void completer (const Postraitement_base &post)=0
virtual void mettre_a_jour (double temps)=0
virtual const Champ_base & get_champ (Champ &espace_stockage) const =0
virtual const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const =0
virtual const Champ_Generique_base & get_champ_post (const Motcle &nom) const
virtual int comprend_champ_post (const Motcle &identifiant) const
virtual int get_info_type_post () const =0
void fixer_identifiant_appel (const Nom &identifiant)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Generique_Extraction & self_cast (Objet_U &)
static const Champ_Generique_Extraction & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Gen_de_Champs_Gen
static const Type_info * info ()
static Champ_Gen_de_Champs_Gen & self_cast (Objet_U &)
static const Champ_Gen_de_Champs_Gen & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Generique_base
static const Type_info * info ()
static Champ_Generique_base & self_cast (Objet_U &)
static const Champ_Generique_base & self_cast (const Objet_U &)
static int composante (const Nom &nom_test, const Nom &nom, const Noms &composantes, const Noms &synonyms)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Gen_de_Champs_Gen
static const Type_info info_obj
Static Public Attributes inherited from Champ_Generique_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
appel invalide
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Champ_Generique_base
Sortie & printOn (Sortie &x) const override
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom dom_extrac_
Nom nom_fr_
Nom methode_
Ref_Domaine domaine_
Domaine_dis le_dom_dis
Protected Attributes inherited from Champ_Gen_de_Champs_Gen
List_Nom noms_sources_ref_
List_Ref_Champ_Generique_base sources_reference_
Protected Attributes inherited from Champ_Generique_base
Nom nom_post_
Nom identifiant_appel_
Nom nom_pb_
Ref_Probleme_base ref_pb_
Additional Inherited Members
Static Protected Member Functions inherited from Champ_Generique_base
static void assert_parallel (int)
Detailed Description
Un champ generique qui effctue l extraction d un champ sur une frontiere.
Definition at line 37 of file Champ_Generique_Extraction.h.
Constructor & Destructor Documentation
~Champ_Generique_Extraction()
Champ_Generique_Extraction::~Champ_Generique_Extraction ()
Definition at line 30 of file Champ_Generique_Extraction.cpp.
Champ_Generique_Extraction()
Champ_Generique_Extraction::Champ_Generique_Extraction ()
voir reset()
Definition at line 34 of file Champ_Generique_Extraction.cpp.
{
// valeurs par defaut
  reset();
  methode_="trace";
}
References methode_, and Champ_Gen_de_Champs_Gen::reset().
Member Function Documentation
completer()
void Champ_Generique_Extraction::completer (const Postraitement_base & post) override virtual
< Pour MC2
< Pour MC2
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 251 of file Champ_Generique_Extraction.cpp.
{
  Champ_Gen_de_Champs_Gen::completer(post);
  const Objet_U& ob = interprete().objet(dom_extrac_);
  if (!sub_type(Domaine, ob))
    {
      Cerr << "Error in  Champ_Generique_Extraction:get_champ"<<finl;
      Cerr<<"We do not retrieve domain"<<finl;
      exit();
    }
  domaine_ = ref_cast(Domaine,ob);
  const Champ_Generique_base& source = get_source(0);
  if (methode_=="champ_frontiere")
    {
      if (sub_type(Champ_Generique_refChamp,source))
        {
          Champ source_espace_stockage;
          const Champ_base& source_stockage = source.get_champ(source_espace_stockage);
          if (!sub_type(Champ_Inc_base,source_stockage))
            {
              Cerr<<"The method "<<methode_<<" can be applied to extract only unknown fields of the problem."<<finl;
              Cerr<<"The field to extract "<<source_stockage.le_nom()<<" do not satisfied this requirement."<<finl;
              exit();
            }
        }
      else
        {
          const Noms nom_champ = get_property("nom");
          Cerr<<"The method "<<methode_<<" can be applied to extract only unknown fields of the problem."<<finl;
          Cerr<<"The source of the post-processing field "<<nom_champ[0]<<" do not encapsulate an unknown field."<<finl;
          exit();
        }
    }
  const Domaine& dom = source.get_ref_domain();
  if (dom==domaine_.valeur())
    {
      Cerr<<"Error in Champ_Generique_Extraction:get_champ"<<finl;
      Cerr<<"The domain is the same as the source's domain."<<finl;
      exit();
    }
  const Zone_dis_base& zone_dis_source = source.get_ref_zone_dis_base();
  const Zone_VF& zvf_source = ref_cast(Zone_VF,zone_dis_source);
// Pour eviter un crash:
  if (zvf_source.nb_frontiere_dis()==0)
    {
      Cerr << "You can't extract a field onto a boundary of the domain " << dom.le_nom() << finl;
      Cerr << "because there is NO boundaries defined on it." << finl;
      if (sub_type(Champ_Generique_Interpolation,source))
        {
          Cerr << "It is not possible to extract on a boundary a field interpolated other than the calculation domain." << finl;
          Cerr << "So, change the domain in Interpolation definition into domain " << ref_cast(Champ_Generique_Interpolation,source).get_source(0).get_ref_domain().le_nom() <<  finl;
        }
      exit();
    }
  const Frontiere_dis_base& fr_dis = zone_dis_source.frontiere_dis(nom_fr_);
  const Frontiere& la_frontiere = fr_dis.frontiere();
  const Type_Face type_face_source = la_frontiere.faces().type_face();
  int nb_faces = la_frontiere.nb_faces();
  const DoubleTab& sommets_source = dom.les_sommets();
  int num_premiere_face = la_frontiere.num_premiere_face();
  Entity index1,index2;
  index1 = FACE;
  index2 = NODE;
  const IntTab& face_sommets = source.get_ref_connectivity(index1,index2);
  int nb_som_faces = zvf_source.nb_som_face();
  Nom type_zone,type_elem;
  if (type_face_source==Faces::segment_2D || type_face_source==Faces::segment_2D_axi)
    type_elem = "Segment"; //!< Pour MC2
  else if (type_face_source==5)
    type_elem = "Segment"; //!< Pour MC2
  else if (type_face_source==Faces::quadrangle_3D)
    type_elem = "Quadrangle";
  else if (type_face_source==Faces::triangle_3D)
    type_elem = "Triangle";
  else if (type_face_source==Faces::point_1D)
    type_elem = "Point";
// Cas suivant possible en parallele
  else if ((type_face_source==Faces::vide_0D) && (nb_faces==0))
    {
      if (zvf_source.que_suis_je().debute_par("Zone_VDF"))
        type_elem = "Rectangle";
      else if (zvf_source.que_suis_je().debute_par("Zone_VEF"))
        type_elem = "Triangle";
      else
        {
          Cerr<<"The type of zone discretized"<<zvf_source.que_suis_je()<<" is not recognized"<<finl;
          exit();
        }
    }
  else
    {
      Cerr<<"The type of faces of the boundary name "<<nom_fr_<<" is neither type Faces::quadrangle_3D nor Faces::triangle_3D"<<finl;
      Cerr<<"We do not realize the extraction"<<finl;
      exit();
    }
// Verification que le domaine d'extraction utilise est correct:
  if (domaine_->nb_som()!=0)
    {
      if (domaine_->zone(0).les_elems().dimension(0) != nb_faces ||
          domaine_->zone(0).les_elems().dimension(1) != nb_som_faces)
        {
          Cerr << "Error when extracting the field " << nom_post_ << ": The " << domaine_.le_nom() << " domain can't be used cause already built with different support !" << finl;
          Cerr << "You could create an empty domain with no operations on it before extracting this field." << finl;
          Process::exit();
        }
    }
  Zone zz;
  domaine_->add(zz);
  Zone& ajoutee = domaine_->zone(0);
  ajoutee.typer(type_elem);
  ajoutee.associer_domaine(domaine_);
  IntTab& mes_elems_zone = ajoutee.les_elems();
  mes_elems_zone.reset();
  mes_elems_zone.resize(nb_faces, nb_som_faces);
// Destruction du descripteur parallele, et on reconstruit...
  domaine_->les_sommets().reset();
  domaine_->les_sommets() = sommets_source;
  for (int face = 0; face < nb_faces; face++)
    for (int s = 0; s < nb_som_faces; s++)
      mes_elems_zone(face, s) = face_sommets(num_premiere_face + face, s);
  NettoieNoeuds::nettoie(domaine_);
// Renumerotation
  ajoutee.associer_domaine(domaine_);
// Discretisation du domaine d'extraction
  discretiser_domaine();
}
References Domaine::add(), Zone::associer_domaine(), Cerr, Champ_Gen_de_Champs_Gen::completer(), Nom::debute_par(), TRUSTTab< _TYPE_ >::dimension(), discretiser_domaine(), dom_extrac_, domaine_, Process::exit(), FACE, Frontiere::faces(), finl, Frontiere_dis_base::frontiere(), Zone_dis_base::frontiere_dis(), Champ_Generique_base::get_champ(), get_property(), Champ_Generique_base::get_ref_connectivity(), Champ_Generique_base::get_ref_domain(), Champ_Generique_base::get_ref_zone_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Objet_U::interprete(), Field_base::le_nom(), Domaine::le_nom(), O_U_Ptr::le_nom(), Zone::les_elems(), Domaine::les_sommets(), methode_, Frontiere::nb_faces(), Zone_VF::nb_frontiere_dis(), Domaine::nb_som(), Zone_VF::nb_som_face(), NettoieNoeuds::nettoie(), NODE, nom_fr_, Champ_Generique_base::nom_post_, Frontiere::num_premiere_face(), Interprete::objet(), Faces::point_1D, Faces::quadrangle_3D, Objet_U::que_suis_je(), ref_cast, TRUSTTab< _TYPE_ >::reset(), TRUSTTab< _TYPE_ >::resize(), Faces::segment_2D, Faces::segment_2D_axi, sub_type, Faces::triangle_3D, type_elem(), Faces::type_face(), Zone::typer(), Ref_Domaine::valeur(), Faces::vide_0D, and Domaine::zone().
cree_instance()
Objet_U * Champ_Generique_Extraction::cree_instance () static
Definition at line 30 of file Champ_Generique_Extraction.cpp.
discretiser_domaine()
void Champ_Generique_Extraction::discretiser_domaine ()
Definition at line 433 of file Champ_Generique_Extraction.cpp.
{
  if (domaine_.non_nul())
    {
      le_dom_dis.associer_domaine(domaine_.valeur());
      const Probleme_base& Pb = get_ref_pb_base();
      const Discretisation_base& discr = Pb.discretisation();
      const Nom& type_discr = discr.que_suis_je();
      Nom type = "NO_FACE_Zone_";
      type += type_discr;
      le_dom_dis.discretiser(type);
    }
}
References Domaine_dis::associer_domaine(), Probleme_base::discretisation(), Domaine_dis::discretiser(), domaine_, Champ_Gen_de_Champs_Gen::get_ref_pb_base(), le_dom_dis, O_U_Ptr::non_nul(), Objet_U::que_suis_je(), and Ref_Domaine::valeur().
Referenced by completer().
duplique()
int Champ_Generique_Extraction::duplique () const override virtual
Implements Objet_U.
Definition at line 30 of file Champ_Generique_Extraction.cpp.
get_champ()
const Champ_base & Champ_Generique_Extraction::get_champ (Champ & espace_stockage) const override virtual
Extraction des valeurs d un champ (trace ou champ frontiere) sur un bord du domaine.
Implements Champ_Generique_base.
Definition at line 97 of file Champ_Generique_Extraction.cpp.
{
  Champ source_espace_stockage;
  const Champ_Generique_base& source = get_source(0);
  const Champ_base& source_stockage = source.get_champ(source_espace_stockage);
  const DoubleTab& source_valeurs = source_stockage.valeurs();
  const Zone_dis_base& zone_dis_source = source.get_ref_zone_dis_base();
  const Nature_du_champ& nature_source = source_stockage.nature_du_champ();
// Le test suivant n est pas dans completer() car utilise equation() : la reference doit etre initialisee
  if (methode_=="champ_frontiere")
    {
      int num_bord =  zone_dis_source.rang_frontiere(nom_fr_);
      const Champ_Inc_base& source_inconnue = ref_cast(Champ_Inc_base,source_stockage);
      const Cond_lim& cl =  source_inconnue.equation().zone_Cl_dis().les_conditions_limites(num_bord);
      if (sub_type(Dirichlet_homogene,cl.valeur()))
        {
          Cerr<<"A boundary condition of type Dirichlet homogeneous does not use field boundary"<<finl;
          Cerr<<"The extraction of field "<<source_stockage.le_nom()<<" with the option champ_frontiere"<<finl;
          Cerr<<"is therefore not possible for this type of boundary condition"<<finl;
          Cerr<<"You can possibly remove the option champ_frontiere for postprocess the trace of the field"<<finl;
          exit();
        }
    }
// Probleme pour discretisation de la zone du domaine d extraction (dimension)
//
  int nb_comp_source = source_stockage.nb_comp();
  double temps = source.get_time();
  Nom type_source, type_espace_stockage, disc;
  int nb_comp = 0;
  int nb_ddl = 0;
  if (zone_dis_source.que_suis_je().debute_par("Zone_VDF"))
    disc = "VDF";
  else if (zone_dis_source.que_suis_je().debute_par("Zone_VEF"))
    disc = "VEF";
  else if (zone_dis_source.que_suis_je().debute_par("Zone_EF"))
    disc = "EF";
  else
    {
      Cerr<<"Champ_Generique_Extraction::get_champ()"<<finl;
      Cerr<<"We do not recognize the type of area discretized"<<zone_dis_source.que_suis_je()<<finl;
      exit();
    }
  type_espace_stockage = "Champ_Fonc_P0_";
  type_espace_stockage += disc;
  if (source_stockage.que_suis_je()=="Champ_Face")
    nb_comp = dimension;
  else
    nb_comp = nb_comp_source;
// La trace rend systematiquement un tableau de valeurs aux faces de depart
// et un champ frontiere discretise est dimensionne par rapport au nombre de faces
// de la frontiere : dans les deux cas nb_ddl = nb_faces
  const Frontiere_dis_base& fr_dis = zone_dis_source.frontiere_dis(nom_fr_);
  const Frontiere& la_frontiere = fr_dis.frontiere();
  nb_ddl = la_frontiere.nb_faces();
// La zone discretisee a associer n est actuellement pas disponible
// On associe pas de zone_discretisee et on ne fixe pas nb_valeurs_nodales
  espace_stockage.typer(type_espace_stockage);
//
  espace_stockage->fixer_nb_comp(nb_comp);
//
  espace_stockage->fixer_nature_du_champ(nature_source);
  DoubleTab& espace_valeurs = espace_stockage->valeurs();
  const int N = source_valeurs.line_size();
  espace_valeurs.resize(nb_ddl,nb_comp);
  if (methode_=="trace")                         //On prend la trace du champ sur un bord
    {
      source_stockage.trace(fr_dis,espace_valeurs,temps,0);
    }
  else if (methode_=="champ_frontiere")                //On recupere le champ frontiere
    {
      int num_bord =  zone_dis_source.rang_frontiere(nom_fr_);
      const Champ_Inc_base& source_inconnue = ref_cast(Champ_Inc_base,source_stockage);
      const Champ_front& champ_fr =  source_inconnue.equation().zone_Cl_dis().les_conditions_limites(num_bord)->champ_front();
      if (sub_type(Champ_front_uniforme,champ_fr.valeur()))
        {
          for (int j = 0; j < N; j++)
            for (int i=0; i<nb_ddl; i++)
              espace_valeurs(i,j) = champ_fr.valeur()(0,j);
        }
      else
        espace_valeurs = champ_fr->valeurs();
    }
// L espace de stockage n a pas actuellement d espace virtuel
//
  return espace_stockage.valeur();
}
References Cerr, Nom::debute_par(), Objet_U::dimension, MorEqn::equation(), Process::exit(), finl, Champ::fixer_nb_comp(), Frontiere_dis_base::frontiere(), Zone_dis_base::frontiere_dis(), Champ_Generique_base::get_champ(), Champ_Generique_base::get_ref_zone_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::get_time(), Field_base::le_nom(), Zone_Cl_dis::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), methode_, Field_base::nature_du_champ(), Field_base::nb_comp(), Frontiere::nb_faces(), nom_fr_, Objet_U::que_suis_je(), Zone_dis_base::rang_frontiere(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Champ_base::trace(), Deriv_::typer(), Deriv_Champ_base::valeur(), Deriv_Champ_front_base::valeur(), Deriv_Cond_lim_base::valeur(), Champ::valeurs(), Champ_front::valeurs(), Champ_Proto::valeurs(), and Equation_base::zone_Cl_dis().
get_champ_without_evaluation()
const Champ_base & Champ_Generique_Extraction::get_champ_without_evaluation (Champ & espace_stockage) const override virtual
Implements Champ_Generique_base.
Definition at line 83 of file Champ_Generique_Extraction.cpp.
{
  Champ source_espace_stockage;
  const Champ_base& source = get_source(0).get_champ_without_evaluation(source_espace_stockage);
  Nature_du_champ nature_source = source.nature_du_champ();
  int nb_comp = source.nb_comp();
  Champ_Fonc es_tmp;
  espace_stockage = creer_espace_stockage(nature_source,nb_comp,es_tmp);
  return espace_stockage.valeur();
}
References Champ_Gen_de_Champs_Gen::creer_espace_stockage(), Champ_Generique_base::get_champ_without_evaluation(), Champ_Gen_de_Champs_Gen::get_source(), Field_base::nature_du_champ(), Field_base::nb_comp(), and Deriv_Champ_base::valeur().
get_copy_domain()
void Champ_Generique_Extraction::get_copy_domain (Domaine & domain) const override virtual
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 400 of file Champ_Generique_Extraction.cpp.
{
  const Domaine& dom = get_ref_domain();
  domain = dom;
}
References get_ref_domain().
get_directive_pour_discr()
const Motcle Champ_Generique_Extraction::get_directive_pour_discr () const override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 76 of file Champ_Generique_Extraction.cpp.
{
  Motcle directive;
  directive = "champ_elem";
  return directive;
}
get_info()
const Type_info * Champ_Generique_Extraction::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 30 of file Champ_Generique_Extraction.cpp.
get_localisation()
Entity Champ_Generique_Extraction::get_localisation (const int index = -1) const override virtual
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 422 of file Champ_Generique_Extraction.cpp.
{
  Entity loc;
  loc = ELEMENT;
  return loc;
}
References ELEMENT.
get_property()
const Noms Champ_Generique_Extraction::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 201 of file Champ_Generique_Extraction.cpp.
{
  Motcles motcles(1);
  motcles[0] = "composantes";
  int rang = motcles.search(query);
  switch(rang)
    {
    case 0:
      {
        Noms source_compos = get_source(0).get_property("composantes");
        int nb_comp = source_compos.size();
        Noms compo(nb_comp);
        for (int i=0; i<nb_comp; i++)
          {
            Nom nume(i);
            compo[i] = nom_post_+nume;
          }
        return compo;
        break;
      }
    }
  return Champ_Gen_de_Champs_Gen::get_property(query);
}
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, Motcles::search(), and vect_impl::size().
Referenced by completer().
get_ref_domain()
const Domaine & Champ_Generique_Extraction::get_ref_domain () const override virtual
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 387 of file Champ_Generique_Extraction.cpp.
{
  if (domaine_.non_nul())
    return domaine_.valeur();
  else
    {
      Cerr<<"There is no extraction domain created to this Champ_Generique_Extraction"<<finl;
      exit();
    }
// Pour compilation
  return get_ref_domain();
}
References Cerr, domaine_, Process::exit(), finl, get_ref_domain(), O_U_Ptr::non_nul(), and Ref_Domaine::valeur().
Referenced by get_copy_domain(), and get_ref_domain().
get_ref_zone_dis_base()
const Zone_dis_base & Champ_Generique_Extraction::get_ref_zone_dis_base () const override virtual
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 406 of file Champ_Generique_Extraction.cpp.
{
  if (domaine_.non_nul())
    {
      const Zone_dis_base& zone_dis = le_dom_dis.zone_dis(0).valeur();
      return  zone_dis;
    }
  else
    {
      Cerr<<"There is no domain associated to this Champ_Generique_Extraction"<<finl;
      exit();
    }
// Pour compilation
  return get_ref_zone_dis_base();
}
References Cerr, domaine_, Process::exit(), finl, get_ref_zone_dis_base(), le_dom_dis, O_U_Ptr::non_nul(), Deriv_Zone_dis_base::valeur(), and Domaine_dis::zone_dis().
Referenced by get_ref_zone_dis_base().
info()
const Type_info * Champ_Generique_Extraction::info () static
Definition at line 30 of file Champ_Generique_Extraction.cpp.
nommer_source()
void Champ_Generique_Extraction::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 232 of file Champ_Generique_Extraction.cpp.
{
  if (nom_post_=="??")
    {
      Nom nom_post_source, nom_champ_source;
      const Noms nom = get_source(0).get_property("nom");
      nom_champ_source = nom[0];
      nom_post_source = "Extraction_";
      nom_post_source += nom_champ_source;
      nommer(nom_post_source);
    }
}
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
printOn()
Sortie & Champ_Generique_Extraction::printOn (Sortie & x) const override protected virtual
appel invalide
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 55 of file Champ_Generique_Extraction.cpp.
{
  exit();
  return os;
}
References Process::exit().
readOn()
Entree & Champ_Generique_Extraction::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 42 of file Champ_Generique_Extraction.cpp.
{
  Champ_Gen_de_Champs_Gen::readOn(is);
// Verifications:
  if (get_nb_sources() != 1)
    {
      Cerr << "Error in Champ_Generique_Extraction::readOn\n"
           << " You must specify exactly 1 \"Source\"." << finl;
    }
  return is;
}
References Cerr, finl, Champ_Gen_de_Champs_Gen::get_nb_sources(), and Champ_Gen_de_Champs_Gen::readOn().
self_cast() [1/2]
const Champ_Generique_Extraction & Champ_Generique_Extraction::self_cast (const Objet_U & r) static
Definition at line 30 of file Champ_Generique_Extraction.cpp.
self_cast() [2/2]
Champ_Generique_Extraction & Champ_Generique_Extraction::self_cast (Objet_U & r) static
Definition at line 30 of file Champ_Generique_Extraction.cpp.
set_param()
void Champ_Generique_Extraction::set_param (Param & param) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 65 of file Champ_Generique_Extraction.cpp.
{
  Champ_Gen_de_Champs_Gen::set_param(param);
  param.ajouter("domaine",&dom_extrac_,Param::REQUIRED);
  param.ajouter("nom_frontiere",&nom_fr_,Param::REQUIRED);
  param.ajouter("methode",&methode_);
}
References Param::ajouter(), dom_extrac_, methode_, nom_fr_, Param::REQUIRED, and Champ_Gen_de_Champs_Gen::set_param().
taille_memoire()
unsigned Champ_Generique_Extraction::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 30 of file Champ_Generique_Extraction.cpp.
Member Data Documentation
dom_extrac_
Nom Champ_Generique_Extraction::dom_extrac_ protected
Definition at line 57 of file Champ_Generique_Extraction.h.
Referenced by completer(), and set_param().
domaine_
Ref_Domaine Champ_Generique_Extraction::domaine_ protected
Definition at line 60 of file Champ_Generique_Extraction.h.
Referenced by completer(), discretiser_domaine(), get_ref_domain(), and get_ref_zone_dis_base().
info_obj
const Type_info Champ_Generique_Extraction::info_obj static
Definition at line 39 of file Champ_Generique_Extraction.h.
le_dom_dis
Domaine_dis Champ_Generique_Extraction::le_dom_dis protected
Definition at line 61 of file Champ_Generique_Extraction.h.
Referenced by discretiser_domaine(), and get_ref_zone_dis_base().
methode_
Nom Champ_Generique_Extraction::methode_ protected
Definition at line 59 of file Champ_Generique_Extraction.h.
Referenced by Champ_Generique_Extraction(), completer(), get_champ(), and set_param().
nom_fr_
Nom Champ_Generique_Extraction::nom_fr_ protected
Definition at line 58 of file Champ_Generique_Extraction.h.
Referenced by completer(), get_champ(), and set_param().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Generique_Extraction.h
src/Kernel/Champs/Champ_Generique_Extraction.cpp