TRUST: Traitement_particulier_NS_Profils_thermo_VDF Class Reference
Traitement_particulier_NS_Profils_thermo_VDF Class Reference
classe Traitement_particulier_NS_Profils_thermo_VDF
#include <Traitement_particulier_NS_Profils_thermo_VDF.h>
Public Member Functions
Traitement_particulier_NS_Profils_thermo_VDF ()
~Traitement_particulier_NS_Profils_thermo_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & lire (Entree &is) override
Entree & lire (const Motcle &, Entree &) override
void reprendre_stat () override
void sauver_stat () const override
void associer_eqn (const Equation_base &) override
void ecriture_fichier_moy_spat_thermo (const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const IntVect &, const DoubleVect &, const DoubleVect &)
void ecriture_fichier_moy_temp_thermo (const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const double, const IntVect &)
void calculer_moyennes_spatiales_thermo (DoubleTab &, DoubleTab &, DoubleTab &, DoubleTab &, DoubleTab &, const IntTab &, const IntTab &, const IntVect &, const DoubleTab &)
void calculer_integrales_temporelles (DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleVect &, const DoubleVect &)
void post_traitement_particulier () override
void init_calcul_moyenne (void) override
void preparer_calcul_particulier (void) override
void init_calcul_stats (void)
Public Member Functions inherited from Traitement_particulier_NS_Profils_VDF
Traitement_particulier_NS_Profils_VDF ()
~Traitement_particulier_NS_Profils_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void post_traitement_particulier (void) override
Entree & lire (const Motcle &, Entree &) override
Entree & lire (Entree &) override
Public Member Functions inherited from Traitement_particulier_NS_Profils
Traitement_particulier_NS_Profils ()
~Traitement_particulier_NS_Profils () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & lire (Entree &) override
void preparer_calcul_particulier (void) override
virtual Entree & lire (const Motcle &, Entree &)=0
void post_traitement_particulier (void) override=0
void reprendre_stat () override
void sauver_stat () const override
void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double) override
Public Member Functions inherited from Traitement_particulier_NS_base
Traitement_particulier_NS_base ()
~Traitement_particulier_NS_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_eqn (const Equation_base &)
virtual void preparer_calcul_particulier (void)=0
virtual void post_traitement_particulier (void)=0
virtual Entree & lire (Entree &is)=0
virtual void sauver_stat (void) const =0
virtual void reprendre_stat (void)=0
virtual void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double)=0
void creer_champ (const Motcle &) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Traitement_particulier_NS_Profils_thermo_VDF & self_cast (Objet_U &)
static const Traitement_particulier_NS_Profils_thermo_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_Profils_VDF
static Objet_U * cree_instance ()
static const Type_info * info ()
static Traitement_particulier_NS_Profils_VDF & self_cast (Objet_U &)
static const Traitement_particulier_NS_Profils_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_Profils
static const Type_info * info ()
static Traitement_particulier_NS_Profils & self_cast (Objet_U &)
static const Traitement_particulier_NS_Profils & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_base
static const Type_info * info ()
static Traitement_particulier_NS_base & self_cast (Objet_U &)
static const Traitement_particulier_NS_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_Profils_VDF
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_Profils
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Classe permettant de faire les statistiques sur le champs
de temperature avec des profils dans un domaine homogene dans une direction.
Entree & readOn (Entree &) override
Protected Member Functions inherited from Traitement_particulier_NS_Profils_VDF
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void init_calcul_moyenne (void) override
void calculer_moyenne_spatiale_vitesse (DoubleTab &, DoubleTab &, DoubleTab &, DoubleTab &, const IntTab &, const IntTab &, const IntVect &, const int, const DoubleTab &)
void calculer_moyenne_spatiale_uv (DoubleTab &, const IntTab &, const IntTab &, const IntVect &, const DoubleTab &)
void ecriture_fichiers_moy_spat (const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleVect &, const DoubleVect &, const IntVect &, const DoubleTab &, const int)
void ecriture_fichiers_moy_spat_1col (const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleVect &, const DoubleVect &, const IntVect &, const int)
void calculer_moyenne_spatiale_nut (DoubleTab &, const IntTab &, const IntTab &, const IntVect &, const DoubleTab &)
void calculer_integrale_temporelle (DoubleTab &, DoubleTab &, DoubleTab &, const DoubleVect &, const DoubleVect &)
void ecriture_fichiers_moy_temp (const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const IntVect &, const int, const double)
void ecriture_fichiers_moy_temp_1col (const DoubleTab &, const DoubleTab &, const IntVect &, const int, const double)
Protected Member Functions inherited from Traitement_particulier_NS_Profils
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void init_calcul_stats (void)
virtual void init_calcul_moyenne (void)=0
Sortie & printOn (Sortie &x) const override
Impression de l'equation sur un flot de sortie.
Simple appel a Equation_base::printOn(Sortie&).
Entree & readOn (Entree &) override
Lit les specifications de l'equation de Navier Stokes a
partir d'un flot d'entree.
Simple appel a Navier_Stokes_std::readOn(Entree&)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
Ref_Convection_Diffusion_std mon_equation_NRJ
int oui_stats_thermo
int oui_repr_stats_thermo
int tmin_tmax
Nom fich_repr_stats_thermo
DoubleTab Tmoy_temp
DoubleTab Trms_temp
DoubleTab upTp_temp
DoubleTab vpTp_temp
DoubleTab wpTp_temp
Protected Attributes inherited from Traitement_particulier_NS_Profils_VDF
DoubleTab Yu_m
DoubleTab Yv_m
DoubleTab Yw_m
DoubleTab Yuv_m
Coordonnees des points ou est definie la vitesse.
DoubleTab Yu_p
DoubleTab Yv_p
DoubleTab Yw_p
DoubleTab Yuv_p
IntTab compt_x_m
IntTab compt_y_m
IntTab compt_z_m
IntTab compt_uv_m
Nombre de points a "meme Y" pour chaque grandeur.
IntTab compt_x_p
IntTab compt_y_p
IntTab compt_z_p
IntTab compt_uv_p
IntTab corresp_u_m
IntTab corresp_v_m
IntTab corresp_w_m
IntTab corresp_uv_m
Correspondance numerotation globale -> numerotation locale dans Yxx.
IntTab corresp_u_p
IntTab corresp_v_p
IntTab corresp_w_p
IntTab corresp_uv_p
DoubleTab xUm
DoubleTab xUp
DoubleTab xWm
DoubleTab xWp
DoubleTab xVm
DoubleTab xVp
DoubleTab xUVm
DoubleTab xUVp
Positions des points juste avant et apres.
DoubleVect delta_Um
DoubleVect delta_Up
DoubleVect delta_Wm
DoubleVect delta_Wp
DoubleVect delta_Vm
DoubleVect delta_Vp
DoubleVect delta_UVm
DoubleVect delta_UVp
Distance (tjrs positive) entre le point avant ou apres et le point du profil, pour faire les interpolations lineaires et trouver les points en question.
Protected Attributes inherited from Traitement_particulier_NS_Profils
DoubleTab u_moy_temp_x
DoubleTab u_moy_temp_y
DoubleTab u_moy_temp_z
DoubleTab uv_moy_temp
DoubleTab u2_moy_temp
DoubleTab v2_moy_temp
DoubleTab w2_moy_temp
DoubleTab u3_moy_temp
DoubleTab v3_moy_temp
DoubleTab w3_moy_temp
DoubleTab u4_moy_temp
DoubleTab v4_moy_temp
DoubleTab w4_moy_temp
DoubleTab nu_t_temp
double temps_deb
double temps_fin
double dt_post_stat
double dt_post_inst
IntVect Nxy
IntVect Nyy
IntVect Nzy
IntVect Nuv
int Nap
Nom fich_repr_u
Nom fich_repr_nu_t
int oui_repr
int oui_u_inst
int oui_stat
int oui_profil_nu_t
int oui_repr_nu_t
int n_probes
DoubleVect positions
int homo_dir
int dir_profil
Protected Attributes inherited from Traitement_particulier_NS_base
Ref_Navier_Stokes_std mon_equation
Champs_compris champs_compris_
Detailed Description
classe Traitement_particulier_NS_Profils_thermo_VDF
Definition at line 33 of file Traitement_particulier_NS_Profils_thermo_VDF.h.
Constructor & Destructor Documentation
Traitement_particulier_NS_Profils_thermo_VDF()
Traitement_particulier_NS_Profils_thermo_VDF::Traitement_particulier_NS_Profils_thermo_VDF ()
Definition at line 28 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
                                                                                          :oui_repr_stats_thermo(0)
{
}
~Traitement_particulier_NS_Profils_thermo_VDF()
Traitement_particulier_NS_Profils_thermo_VDF::~Traitement_particulier_NS_Profils_thermo_VDF ()
Definition at line 26 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
Member Function Documentation
associer_eqn()
void Traitement_particulier_NS_Profils_thermo_VDF::associer_eqn (const Equation_base & eq_ns) override virtual
Reimplemented from Traitement_particulier_NS_base.
Definition at line 121 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
  Traitement_particulier_NS_Profils_VDF::associer_eqn(eq_ns);
  const Probleme_base& pb = mon_equation.valeur().probleme();
  int flag=0;
  for(int i=0; i<pb.nombre_d_equations(); i++)
    {
      if(sub_type(Convection_Diffusion_Temperature,pb.equation(i)))
        {
          mon_equation_NRJ = ref_cast(Convection_Diffusion_Temperature,pb.equation(i));
          flag=1;
        }
      else if(sub_type(Convection_Diffusion_Chaleur_QC,pb.equation(i)))
        {
          mon_equation_NRJ = ref_cast(Convection_Diffusion_Chaleur_QC,pb.equation(i));
          flag=1;
        }
    }
  if (flag==0)
    {
      Cerr << "Error : Equation of NRJ was not found..." << finl;
      Cerr << "User can not ask for statistics on temperature" << finl;
      Cerr << "if we do not solve a heat equation." << finl;
      Cerr << "Try to remove the '_thermo' part at key-word 'Profils'" << finl;
      exit();
    }
}
References Traitement_particulier_NS_base::associer_eqn(), Cerr, Probleme_base::equation(), Process::exit(), finl, Traitement_particulier_NS_base::mon_equation, mon_equation_NRJ, Probleme_base::nombre_d_equations(), Equation_base::probleme(), ref_cast, sub_type, and Ref_Navier_Stokes_std::valeur().
calculer_integrales_temporelles()
void Traitement_particulier_NS_Profils_thermo_VDF::calculer_integrales_temporelles (DoubleTab & moy_temp, const DoubleTab & moy_spat_m, const DoubleTab & moy_spat_p, const DoubleVect & delta_m, const DoubleVect & delta_p)
Definition at line 476 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
  int i,j;
  double dt_v = mon_equation->schema_temps().pas_de_temps();
  DoubleTab moy(moy_temp);
  for(i=0; i<n_probes; i++)
    {
      for(j=0; j<Nap; j++)
        {
          moy(i,j)=moy_spat_m(i,j)*delta_m(i)/(delta_m(i)+delta_p(i));
          moy(i,j)+=moy_spat_p(i,j)*delta_p(i)/(delta_m(i)+delta_p(i));
        }
    }
  if(je_suis_maitre())
//
    moy_temp.ajoute_sans_ech_esp_virt(dt_v,moy);
}
References TRUSTVect< _TYPE_ >::ajoute_sans_ech_esp_virt(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, Schema_Temps_base::pas_de_temps(), and Equation_base::schema_temps().
Referenced by post_traitement_particulier().
calculer_moyennes_spatiales_thermo()
void Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo (DoubleTab & tmoy, DoubleTab & trms, DoubleTab & uptp, DoubleTab & vptp, DoubleTab & wptp, const IntTab & corresp, const IntTab & compt, const IntVect & NN, const DoubleTab & xUV)
Definition at line 241 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF=ref_cast(Zone_VDF, zdisbase);
  const IntTab& elem_faces = zone_VDF.elem_faces();
// Pour trouver les coordonnees des points de temperature max et min :
  const DoubleTab& xp = zone_VDF.xp();
// Le nombre d'elements de la zone VDF.
  int nb_elems = zone_VDF.zone().nb_elem();
// On veut acceder aux valeurs des 3 composantes de la vitesse a partir de mon_equation.
  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
// On veut acceder aux valeurs de la temperature a partir de mon_equation_NRJ.
  const DoubleTab& Temp = mon_equation_NRJ.valeur().inconnue().valeurs();
// Ces 3 vecteurs comportent les valeurs des 3 composantes U, V et W moyennees au centre des elements et sur tout l'espace.
// Ils correspondent a <U>, <V> et <W>.
  DoubleTab u_moy_cent(n_probes,Nap);
  u_moy_cent= 0.;
  DoubleTab v_moy_cent(n_probes,Nap);
  v_moy_cent= 0.;
  DoubleTab w_moy_cent(n_probes,Nap);
  w_moy_cent= 0.;
// t2moy correspond
  DoubleTab t2moy(n_probes,Nap);
  t2moy     = 0.;
// vitu, vitv et vitw sont les valeurs des 3 composantes de la vitesse prises au centre de l'element,
// c'est a dire moyennees.
  double vitu,vitv,vitw;
// Pour verification des bornes de temperature en canal plan
  double Tmin=1000000000.,Tmax=0.;
  int elem_min=0, elem_max=0;
// On se sert de face_ui_j pour avoir le numero de la face portant la composante de la vitesse ui
// et 0 et 1 etant les deux faces qui se font face pour faire une moyenne au centre de l'element.
// On doit procede comme ca entre autre parceque l'on va parcourir les elements.
  int face_u_0,face_u_1,face_v_0,face_v_1,face_w_0,face_w_1;
  int i,j,deja_fait=0;
  int num_elem;
// tmoy est la moyenne de T : <T>(y,t)
  tmoy = 0.;
// trms est l'ecart-type de la temperature : sqrt(<Tp^2>)(y,t)=<T^2>-<T>^2
  trms = 0.;
// uptp : <U><T>-<UT>
  uptp = 0.;
// vptp : <V><T>-<VT>
  vptp = 0.;
// wptp : <W><T>-<WT>
  wptp = 0.;
  for(i=0; i<n_probes; i++)
    {
// On parcourt tous les elements pour faire toutes les moyennes au centre des elements.
      for (num_elem=0; num_elem<nb_elems; num_elem++)
        {
// <T>
          if(xp(num_elem,dir_profil)==xUV(i))
            {
              tmoy(i,corresp(i,num_elem)) += Temp[num_elem];
              face_u_0 = elem_faces(num_elem,0);
              face_u_1 = elem_faces(num_elem,dimension);
              vitu = 0.5*(vitesse[face_u_0]+vitesse[face_u_1]);
              face_v_0 = elem_faces(num_elem,1);
              face_v_1 = elem_faces(num_elem,dimension+1);
              vitv = 0.5*(vitesse[face_v_0]+vitesse[face_v_1]);
              face_w_0 = elem_faces(num_elem,2);
              face_w_1 = elem_faces(num_elem,dimension+2);
              vitw = 0.5*(vitesse[face_w_0]+vitesse[face_w_1]);
// <U>
              u_moy_cent(i,corresp(i,num_elem)) += vitu;
// <V>
              v_moy_cent(i,corresp(i,num_elem)) += vitv;
// <W>
              w_moy_cent(i,corresp(i,num_elem)) += vitw;
// Trms : en fait ici on calcul <T^2> mais ensuite on va soustraire la partie <T>^2
              trms(i,corresp(i,num_elem)) += Temp[num_elem]*Temp[num_elem];
// On calcule <uT>, <vT>, et <wT>
              uptp(i,corresp(i,num_elem)) += vitu*Temp[num_elem];
              vptp(i,corresp(i,num_elem)) += vitv*Temp[num_elem];
              wptp(i,corresp(i,num_elem)) += vitw*Temp[num_elem];
            }
// Pour trouver les temperatures max et min dans l'ecoulement.
          if(Temp[num_elem]<Tmin)
            {
              Tmin=Temp[num_elem];
              elem_min=num_elem;
            }
          if(Temp[num_elem]>Tmax)
            {
              Tmax=Temp[num_elem];
              elem_max=num_elem;
            }
        }//FIN boucle sur les elements
      if((tmin_tmax==1)&&(deja_fait==0))
        {
          SFichier fic1("T_min_max.dat",ios::app);
          double tps = mon_equation->inconnue().temps();
          fic1 << tps << " " << Tmin << " " << xp(elem_min,0) << " " << xp(elem_min,1);
          fic1 << " " << Tmax << " " << xp(elem_max,0) << " " << xp(elem_max,1) <<finl;
          fic1.flush();
          fic1.close();
          deja_fait=1;
        }
    } //!< On a parcouru tous les profils
// NN correspond au nombre de valeurs differentes pour Y, c'est a dire le nombre de points de la courbe finale apres moyenne.
// compt[j] correspond au nombre d'elements qui ont ete utilises pour calculer une meme valeur de temperature moyenne,
// ie le nombre d'elements ayant la meme coordonnee Y.
// POUR LE PARALLELE !!
  IntTab compt_p(compt);
  envoyer(compt_p,Process::me(),0,Process::me());
  DoubleTab tmoy_p(tmoy);
  envoyer(tmoy_p,Process::me(),0,Process::me());
  DoubleTab trms_p(trms);
  envoyer(trms_p,Process::me(),0,Process::me());
  DoubleTab uptp_p(uptp);
  envoyer(uptp_p,Process::me(),0,Process::me());
  DoubleTab vptp_p(vptp);
  envoyer(vptp_p,Process::me(),0,Process::me());
  DoubleTab wptp_p(wptp);
  envoyer(wptp_p,Process::me(),0,Process::me());
  DoubleTab u_moy_cent_p(u_moy_cent);
  envoyer(u_moy_cent_p,Process::me(),0,Process::me());
  DoubleTab v_moy_cent_p(v_moy_cent);
  envoyer(v_moy_cent_p,Process::me(),0,Process::me());
  DoubleTab w_moy_cent_p(w_moy_cent);
  envoyer(w_moy_cent_p,Process::me(),0,Process::me());
  if(je_suis_maitre())
    {
      IntTab compt_tot(compt);
      DoubleTab tmoy_tot(tmoy);
      DoubleTab trms_tot(trms);
      DoubleTab uptp_tot(uptp);
      DoubleTab vptp_tot(vptp);
      DoubleTab wptp_tot(wptp);
      DoubleTab u_moy_cent_tot(u_moy_cent);
      DoubleTab v_moy_cent_tot(v_moy_cent);
      DoubleTab w_moy_cent_tot(w_moy_cent);
      compt_tot=0;
      tmoy_tot=0.;
      trms_tot=0.;
      uptp_tot=0.;
      vptp_tot=0.;
      wptp_tot=0.;
      u_moy_cent_tot=0.;
      v_moy_cent_tot=0.;
      w_moy_cent_tot=0.;
      for(int p=0; p<Process::nproc(); p++)
        {
          recevoir(compt_p,p,0,p);
          compt_tot+=compt_p;
          recevoir(tmoy_p,p,0,p);
          tmoy_tot+=tmoy_p;
          recevoir(trms_p,p,0,p);
          trms_tot+=trms_p;
          recevoir(uptp_p,p,0,p);
          uptp_tot+=uptp_p;
          recevoir(vptp_p,p,0,p);
          vptp_tot+=vptp_p;
          recevoir(wptp_p,p,0,p);
          wptp_tot+=wptp_p;
          recevoir(u_moy_cent_p,p,0,p);
          u_moy_cent_tot+=u_moy_cent_p;
          recevoir(v_moy_cent_p,p,0,p);
          v_moy_cent_tot+=v_moy_cent_p;
          recevoir(w_moy_cent_p,p,0,p);
          w_moy_cent_tot+=w_moy_cent_p;
        }
      for(i=0; i<n_probes; i++)
        {
          for (j=0; j<NN(i); j++)
            {
              tmoy(i,j) = tmoy_tot(i,j) / compt_tot(i,j);
              trms(i,j) = trms_tot(i,j) / compt_tot(i,j);
              uptp(i,j) = uptp_tot(i,j) / compt_tot(i,j);
              vptp(i,j) = vptp_tot(i,j) / compt_tot(i,j);
              wptp(i,j) = wptp_tot(i,j) / compt_tot(i,j);
              u_moy_cent(i,j) = u_moy_cent_tot(i,j) / compt_tot(i,j);
              v_moy_cent(i,j) = v_moy_cent_tot(i,j) / compt_tot(i,j);
              w_moy_cent(i,j) = w_moy_cent_tot(i,j) / compt_tot(i,j);
              trms(i,j) -= tmoy(i,j)*tmoy(i,j);
              uptp(i,j) -= u_moy_cent(i,j)*tmoy(i,j);
              vptp(i,j) -= v_moy_cent(i,j)*tmoy(i,j);
              wptp(i,j) -= w_moy_cent(i,j)*tmoy(i,j);
            }
        }//!< Fin boucle sur les profils
    }//!< FIN Parallele
}
References Sortie_Fichier_base::close(), Objet_U::dimension, Traitement_particulier_NS_Profils::dir_profil, Zone_VF::elem_faces(), envoyer(), finl, Sortie_Fichier_base::flush(), Navier_Stokes_std::inconnue(), Convection_Diffusion_std::inconnue(), Process::je_suis_maitre(), Process::me(), Traitement_particulier_NS_base::mon_equation, mon_equation_NRJ, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, Zone::nb_elem(), Process::nproc(), recevoir(), ref_cast, Champ_Inc::temps(), tmin_tmax, Ref_Convection_Diffusion_std::valeur(), Champ_Inc::valeurs(), Zone_VF::xp(), Zone_dis_base::zone(), and Champ_Inc::zone_dis_base().
Referenced by post_traitement_particulier().
cree_instance()
Objet_U * Traitement_particulier_NS_Profils_thermo_VDF::cree_instance () static
Definition at line 26 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
duplique()
int Traitement_particulier_NS_Profils_thermo_VDF::duplique () const override virtual
Implements Objet_U.
Definition at line 26 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
ecriture_fichier_moy_spat_thermo()
void Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_spat_thermo (const DoubleTab & Tmoy_m, const DoubleTab & Trms_m, const DoubleTab & upTp_m, const DoubleTab & vpTp_m, const DoubleTab & wpTp_m, const DoubleTab & Tmoy_p, const DoubleTab & Trms_p, const DoubleTab & upTp_p, const DoubleTab & vpTp_p, const DoubleTab & wpTp_p, const DoubleTab & Y, const IntVect & NN, const DoubleVect & delta_m, const DoubleVect & delta_p)
Definition at line 502 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
  int i,j;
  double tps = mon_equation->inconnue().temps();
  Nom temps = Nom(tps);
  for(i=0; i<n_probes; i++)
    {
      Nom nom_fic = "./Space_Avg/Avg_temp_";
      switch(dir_profil)
        {
        case 0:
          {
            nom_fic +="X_";
            break;
          }
        case 1:
          {
            nom_fic +="Y_";
            break;
          }
        case 2:
          {
            nom_fic +="Z_";
            break;
          }
        }
      Nom pos  = Nom(positions(i));
      nom_fic += pos;
      nom_fic += "_t_";
      nom_fic += temps;
      nom_fic += ".dat";
      if(je_suis_maitre())
        {
          SFichier fic (nom_fic);
          fic << "# Space Averaged Statistics" << finl ;
          fic << "# Y       <T>       Trms       <upTp>       -<vpTp>       -<wpTp>" << finl ;
          DoubleTab Tmoy(Tmoy_m);
          DoubleTab Trms(Trms_m);
          DoubleTab upTp(upTp_m);
          DoubleTab vpTp(vpTp_m);
          DoubleTab wpTp(wpTp_m);
          for(j=0; j<NN(i); j++)
            {
              Tmoy(i,j)=Tmoy_m(i,j)*delta_m(i)/(delta_m(i)+delta_p(i));
              Tmoy(i,j)+=Tmoy_p(i,j)*delta_p(i)/(delta_m(i)+delta_p(i));
              Trms(i,j)=Trms_m(i,j)*delta_m(i)/(delta_m(i)+delta_p(i));
              Trms(i,j)+=Trms_p(i,j)*delta_p(i)/(delta_m(i)+delta_p(i));
              upTp(i,j)=upTp_m(i,j)*delta_m(i)/(delta_m(i)+delta_p(i));
              upTp(i,j)+=upTp_p(i,j)*delta_p(i)/(delta_m(i)+delta_p(i));
              vpTp(i,j)=vpTp_m(i,j)*delta_m(i)/(delta_m(i)+delta_p(i));
              vpTp(i,j)+=vpTp_p(i,j)*delta_p(i)/(delta_m(i)+delta_p(i));
              wpTp(i,j)=wpTp_m(i,j)*delta_m(i)/(delta_m(i)+delta_p(i));
              wpTp(i,j)+=wpTp_p(i,j)*delta_p(i)/(delta_m(i)+delta_p(i));
            }
          for (j=0; j<NN(i); j++)
            fic << Y(i,j) << " " << Tmoy(i,j) << " " << sqrt(std::max(Trms(i,j),0.0)) << " " << upTp(i,j) << " " << -vpTp(i,j) << " " << -wpTp(i,j) << finl;
          fic.flush();
          fic.close();
        } //Fin du si je suis maitre
    }//FIN de boucle sur les probes
}
References Sortie_Fichier_base::close(), Traitement_particulier_NS_Profils::dir_profil, finl, Sortie_Fichier_base::flush(), Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::positions, and Champ_Inc::temps().
Referenced by post_traitement_particulier().
ecriture_fichier_moy_temp_thermo()
void Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_temp_thermo (const DoubleTab & Tmoy, const DoubleTab & Trms, const DoubleTab & upTp, const DoubleTab & vpTp, const DoubleTab & wpTp, const DoubleTab & Y, const double dt, const IntVect & NN)
Definition at line 576 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
  int i,j;
  for(i=0; i<n_probes; i++)
    {
      Nom nom_fic = "./Time_Avg/Avg_time_temp_";
      double tps = mon_equation->inconnue().temps();
      switch(dir_profil)
        {
        case 0:
          {
            nom_fic +="X_";
            break;
          }
        case 1:
          {
            nom_fic +="Y_";
            break;
          }
        case 2:
          {
            nom_fic +="Z_";
            break;
          }
        }
      Nom pos  = Nom(positions(i));
      nom_fic += pos;
      nom_fic +="_t_";
      Nom temps = Nom(tps);
      nom_fic+= temps;
      nom_fic+=".dat";
      if(je_suis_maitre())
        {
          SFichier fic (nom_fic);
          fic << "# Time Averaged Statistics" << finl ;
          fic << "# Y       <T>       Trms       <upTp>       -<vpTp>       -<wpTp>" << finl ;
          for (j=0; j<NN(i)  ; j++)
            fic << Y(i,j) << " " << Tmoy(i,j)/dt << " " << sqrt(std::max(Trms(i,j)/dt,0.0)) << " " << upTp(i,j)/dt << " " << -vpTp(i,j)/dt << " " << -wpTp(i,j)/dt << finl;
          fic.flush();
          fic.close();
        }
    }//FIN boucle sur les probes
}
References Sortie_Fichier_base::close(), Traitement_particulier_NS_Profils::dir_profil, finl, Sortie_Fichier_base::flush(), Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::positions, and Champ_Inc::temps().
Referenced by post_traitement_particulier().
get_info()
const Type_info * Traitement_particulier_NS_Profils_thermo_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Traitement_particulier_NS_Profils.
Definition at line 26 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
info()
const Type_info * Traitement_particulier_NS_Profils_thermo_VDF::info () static
Definition at line 26 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
init_calcul_moyenne()
void Traitement_particulier_NS_Profils_thermo_VDF::init_calcul_moyenne (void) override virtual
Implements Traitement_particulier_NS_Profils.
Definition at line 771 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
  Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne();
}
References Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne().
init_calcul_stats()
void Traitement_particulier_NS_Profils_thermo_VDF::init_calcul_stats (void)
Definition at line 797 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
  Traitement_particulier_NS_Profils::init_calcul_stats();
  if (oui_repr_stats_thermo!=1)
    {
// L'utilisateur ne demande pas de reprise, c'est a dire qu'il n'y aura pas de lecture
// dans un fichier et qu'il faut donc dimensionner nos tableaux nous meme pour debuter les statistiques.
// Ces tableaux sont declares dans le Traitement_particulier_NS_Profils_thermo_VDF.h
      Tmoy_temp.resize(n_probes,Nap);
      Tmoy_temp=0;
      Trms_temp.resize(n_probes,Nap);
      Trms_temp=0;
      upTp_temp.resize(n_probes,Nap);
      upTp_temp=0;
      vpTp_temp.resize(n_probes,Nap);
      vpTp_temp=0;
      wpTp_temp.resize(n_probes,Nap);
      wpTp_temp=0;
    }
}
References Traitement_particulier_NS_Profils::init_calcul_stats(), Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, oui_repr_stats_thermo, TRUSTTab< _TYPE_ >::resize(), Tmoy_temp, Trms_temp, upTp_temp, vpTp_temp, and wpTp_temp.
Referenced by preparer_calcul_particulier().
lire() [1/2]
Entree & Traitement_particulier_NS_Profils_thermo_VDF::lire (const Motcle & motlu, Entree & is) override virtual
< On veut reprendre les statistiques sur la temperature
< Indication du nom du fichier de reprise des stats pour le champs de temperature
Implements Traitement_particulier_NS_Profils.
Definition at line 81 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
// Par defaut on ne fait pas de statistiques sur la temperature.
  if (motlu=="stats_thermo")
    {
// Statistiques sur le champ de temperature
      oui_stats_thermo = 1;
    }
  else
    {
      if(motlu=="reprise_thermo")
        {
// Reprise des statistiques pour le champs de temperature
          oui_repr_stats_thermo = 1; //!< On veut reprendre les statistiques sur la temperature
          is  >> fich_repr_stats_thermo ;  //!< Indication du nom du fichier de reprise des stats pour le champs de temperature
          Cerr << "On reprend les statistiques sur le champs thermique" << finl;
        }
      else
        {
          if(motlu=="tmin_tmax")
            {
// On demande les max et min de temperature dans un fichier
              tmin_tmax = 1;
              Cerr << "User asked to monitor min and max of temperature" << finl;
              Cerr << "in channel flow computation." << finl;
            }
          else
            {
              return Traitement_particulier_NS_Profils_VDF::lire(motlu,is);
            }
        }
    }
  return is;
}
References Cerr, fich_repr_stats_thermo, finl, Traitement_particulier_NS_Profils_VDF::lire(), oui_repr_stats_thermo, oui_stats_thermo, and tmin_tmax.
lire() [2/2]
Entree & Traitement_particulier_NS_Profils_thermo_VDF::lire (Entree & is) override virtual
Reimplemented from Traitement_particulier_NS_Profils.
Definition at line 73 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
  return Traitement_particulier_NS_Profils_VDF::lire(is);
}
References Traitement_particulier_NS_Profils_VDF::lire().
post_traitement_particulier()
void Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier (void) override virtual
< si ce n est pas une reprise : sinon valeurs lues dans le fichier
Implements Traitement_particulier_NS_Profils.
Definition at line 157 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
  Traitement_particulier_NS_Profils_VDF::post_traitement_particulier();
  DoubleTab Tmoy_m(n_probes,Nap);
  Tmoy_m=0.;
  DoubleTab Trms_m(n_probes,Nap);
  Trms_m=0.;
  DoubleTab upTp_m(n_probes,Nap);
  upTp_m=0.;
  DoubleTab vpTp_m(n_probes,Nap);
  vpTp_m=0.;
  DoubleTab wpTp_m(n_probes,Nap);
  wpTp_m=0.;
  DoubleTab Tmoy_p(n_probes,Nap);
  Tmoy_p=0.;
  DoubleTab Trms_p(n_probes,Nap);
  Trms_p=0.;
  DoubleTab upTp_p(n_probes,Nap);
  upTp_p=0.;
  DoubleTab vpTp_p(n_probes,Nap);
  vpTp_p=0.;
  DoubleTab wpTp_p(n_probes,Nap);
  wpTp_p=0.;
  double tps = mon_equation->inconnue().temps();
// On ne fait des statistiques sur le champ thermique que si l'on fait des statistiques sur le champ dynamique en meme temps.
  if ((oui_u_inst != 0)&&(oui_stats_thermo != 0))
    {
      calculer_moyennes_spatiales_thermo(Tmoy_m,Trms_m,upTp_m,vpTp_m,wpTp_m,corresp_uv_m,compt_uv_m,Nuv,xUVm);
      calculer_moyennes_spatiales_thermo(Tmoy_p,Trms_p,upTp_p,vpTp_p,wpTp_p,corresp_uv_p,compt_uv_p,Nuv,xUVp);
      static double temps_dern_post_inst = -100.;
      if (std::fabs(tps-temps_dern_post_inst)>=dt_post_inst)
        {
          ecriture_fichier_moy_spat_thermo(Tmoy_m,Trms_m,upTp_m,vpTp_m,wpTp_m,Tmoy_p,Trms_p,upTp_p,vpTp_p,wpTp_p,Yuv_m,Nuv,delta_UVm, delta_UVp);
          temps_dern_post_inst = tps;
        }
    }
// Moyennes temporelles :
// On ne fait des statistiques sur le champ thermique que si l'on fait des statistiques sur le champ dynamique en meme temps.
  if ((oui_u_inst != 0)&&(oui_stats_thermo != 0)&&(oui_stat != 0))
    {
      double tpsbis = mon_equation->inconnue().temps();
      if ((tpsbis>=temps_deb)&&(tpsbis<=temps_fin))
        {
          static int init_stat_temps = 0;
          if((init_stat_temps==0)&&( oui_repr != 1))  //!< si ce n est pas une reprise : sinon valeurs lues dans le fichier
            {
              double dt_v = mon_equation->schema_temps().pas_de_temps();
              temps_deb = tpsbis-dt_v;
              init_stat_temps++;
            }
          calculer_integrales_temporelles(Tmoy_temp,Tmoy_m,Tmoy_p,delta_UVm,delta_UVp);
          calculer_integrales_temporelles(Trms_temp,Trms_m,Trms_p,delta_UVm,delta_UVp);
          calculer_integrales_temporelles(upTp_temp,upTp_m,upTp_p,delta_UVm,delta_UVp);
          calculer_integrales_temporelles(vpTp_temp,vpTp_m,vpTp_p,delta_UVm,delta_UVp);
          calculer_integrales_temporelles(wpTp_temp,wpTp_m,wpTp_p,delta_UVm,delta_UVp);
          static double temps_dern_post_stat = -100.;
          if (std::fabs(tpsbis-temps_dern_post_stat)>=dt_post_stat)
            {
              double dt = tpsbis-temps_deb;
              ecriture_fichier_moy_temp_thermo(Tmoy_temp,Trms_temp,upTp_temp,vpTp_temp,wpTp_temp,Yuv_m,dt,Nuv);
              temps_dern_post_stat = tpsbis;
            }
        }
    }
}
References calculer_integrales_temporelles(), calculer_moyennes_spatiales_thermo(), Traitement_particulier_NS_Profils_VDF::compt_uv_m, Traitement_particulier_NS_Profils_VDF::compt_uv_p, Traitement_particulier_NS_Profils_VDF::corresp_uv_m, Traitement_particulier_NS_Profils_VDF::corresp_uv_p, Traitement_particulier_NS_Profils_VDF::delta_UVm, Traitement_particulier_NS_Profils_VDF::delta_UVp, Traitement_particulier_NS_Profils::dt_post_inst, Traitement_particulier_NS_Profils::dt_post_stat, ecriture_fichier_moy_spat_thermo(), ecriture_fichier_moy_temp_thermo(), Navier_Stokes_std::inconnue(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, Traitement_particulier_NS_Profils::Nuv, Traitement_particulier_NS_Profils::oui_repr, Traitement_particulier_NS_Profils::oui_stat, oui_stats_thermo, Traitement_particulier_NS_Profils::oui_u_inst, Schema_Temps_base::pas_de_temps(), Traitement_particulier_NS_Profils_VDF::post_traitement_particulier(), Equation_base::schema_temps(), Champ_Inc::temps(), Traitement_particulier_NS_Profils::temps_deb, Traitement_particulier_NS_Profils::temps_fin, Tmoy_temp, Trms_temp, upTp_temp, vpTp_temp, wpTp_temp, Traitement_particulier_NS_Profils_VDF::xUVm, Traitement_particulier_NS_Profils_VDF::xUVp, and Traitement_particulier_NS_Profils_VDF::Yuv_m.
preparer_calcul_particulier()
void Traitement_particulier_NS_Profils_thermo_VDF::preparer_calcul_particulier (void) override virtual
Reimplemented from Traitement_particulier_NS_Profils.
Definition at line 777 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
  if ((oui_u_inst != 0)||(oui_profil_nu_t != 0))
// On fait appel uniquement a la methode dans NS_Profils_VDF pour initialiser
// le calcul des moyennes puisque on y fait uniquement la creation des tableaux
// de correspondance et le dimensionnement des grandeurs Yuv et Nuv.
    Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne();
  if (oui_stat != 0)
// Par contre, pour debuter le calcul des stats il faut faire un petit traitement
// pour la thermo puisqu'il faut dimensionner les tableaux des moyennes temporelles
// specifiques a la thermo, ainsi que ceux de l'hydraulique classique dans NS_Profils.
    init_calcul_stats();
}
References Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), init_calcul_stats(), Traitement_particulier_NS_Profils::oui_profil_nu_t, Traitement_particulier_NS_Profils::oui_stat, and Traitement_particulier_NS_Profils::oui_u_inst.
printOn()
Sortie & Traitement_particulier_NS_Profils_thermo_VDF::printOn (Sortie & is) const override protected virtual
Classe permettant de faire les statistiques sur le champs
de temperature avec des profils dans un domaine homogene dans une direction.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_Profils.
Definition at line 45 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
  return is;
}
readOn()
Entree & Traitement_particulier_NS_Profils_thermo_VDF::readOn (Entree & is) override protected virtual
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_Profils.
Definition at line 65 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
  return is;
}
reprendre_stat()
void Traitement_particulier_NS_Profils_thermo_VDF::reprendre_stat (void) override virtual
Reimplemented from Traitement_particulier_NS_Profils.
Definition at line 675 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
  Traitement_particulier_NS_Profils::reprendre_stat();
  double tps = mon_equation->inconnue().temps();
  int i,j;
  double ti;
// double ti2;
  Nom temps;
  if (oui_stat == 1)
    {
      ifstream fict(fich_repr_stats_thermo);
      if (fict)
        {
          LecFicDistribueBin fict2 (fich_repr_stats_thermo);
          fict2 >> temps;
          Tmoy_temp.resize(n_probes,Nap);
          Trms_temp.resize(n_probes,Nap);
          upTp_temp.resize(n_probes,Nap);
          vpTp_temp.resize(n_probes,Nap);
          wpTp_temp.resize(n_probes,Nap);
          for(i=0; i<n_probes; i++)
            {
              fict2 >> Nuv(i);
              for (j=0; j<Nuv(i); j++)
                {
                  fict2 >> Tmoy_temp(i,j) ;
                  fict2 >> Trms_temp(i,j);
                  fict2 >> upTp_temp(i,j) ;
                  fict2 >> vpTp_temp(i,j) ;
                  fict2 >> wpTp_temp(i,j) ;
                }
            }
          fict2 >> ti ;
          Cerr << "ti=" << ti << finl;
          Nom chc_ti = Nom(ti), chc_temps_deb = Nom(temps_deb);
          Cerr << "chc_ti=" << chc_ti << "   chc_temps_deb=" << chc_temps_deb << finl;
          if (chc_ti!=chc_temps_deb)
            {
              if (ti > temps_deb)
                {
                  Cerr << "Pb de reprise des stats du champ thermique :" << finl;
                  Cerr << "Le temps de debut des stats demande " << temps_deb  << finl;
                  Cerr << "est inferieur a celui de debut des stats sauvees !" << ti << finl;
                  exit();
                }
              else
                {
                  if (temps_deb>=tps)
                    {
                      Cerr << "On recommence le calcul des stats thermiques a partir de t=" << temps_deb << "s." << finl;
                      Tmoy_temp = 0.;
                      Trms_temp = 0.;
                      upTp_temp = 0.;
                      vpTp_temp = 0.;
                      wpTp_temp = 0.;
                      oui_repr_stats_thermo = 0;
                    }
                  else
                    {
                      Cerr << "On a deja depasse le temps auquel vous voulez commencer les stats thermiques !" << finl;
                      exit();
                    }
                }
            }
          else
            {
              Cerr << "On continue le calcul des stats thermiques, debute a t=" <<  ti << "s." << finl;
              temps_deb = ti;
            }
        }
      else
        {
          if (tps<=temps_deb)
            {
              Cerr << "On n a pas encore debute le calcul des stats thermiques." << finl;
              oui_repr_stats_thermo = 0;
            }
          else
            {
              Cerr << "Il faut donner le fichier pour reprendre les stats thermiques !" << finl;
              exit();
            }
        }
    }
  else
    {
// Cerr << "Pas de calcul des stats commence." << finl;
// Cerr << "Pas de reprise des statistiques thermiques." << finl;
    }
}
References Cerr, Process::exit(), fich_repr_stats_thermo, finl, Navier_Stokes_std::inconnue(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, Traitement_particulier_NS_Profils::Nuv, oui_repr_stats_thermo, Traitement_particulier_NS_Profils::oui_stat, Traitement_particulier_NS_Profils::reprendre_stat(), TRUSTTab< _TYPE_ >::resize(), Champ_Inc::temps(), Traitement_particulier_NS_Profils::temps_deb, Tmoy_temp, Trms_temp, upTp_temp, vpTp_temp, and wpTp_temp.
sauver_stat()
void Traitement_particulier_NS_Profils_thermo_VDF::sauver_stat (void) const override virtual
Reimplemented from Traitement_particulier_NS_Profils.
Definition at line 633 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
{
  Traitement_particulier_NS_Profils::sauver_stat();
  double tps = mon_equation->inconnue().temps();
  if (  (oui_stat == 1)&&(tps>=temps_deb)&&(tps<=temps_fin) )
    {
      Cerr << "In Traitement_particulier_NS_Profils_thermo_VDF::sauver_stat" << finl;
// On sauve la somme (sans diviser par dt)
      int i,j;
      Nom temps = Nom(tps);
      Nom fich_sauv_temp ="temperature_field_avg_time_";
      fich_sauv_temp+=temps;
      fich_sauv_temp+=".sauv";
// On sauve u_moy!!
      EcrFicCollecteBin fict (fich_sauv_temp);
      fict << temps << finl;
      for(i=0; i<n_probes; i++)
        {
          fict << Nuv(i) << finl;
          for (j=0; j<Nuv(i); j++)
            {
              fict << Tmoy_temp(i,j) << " " << finl;
              fict << Trms_temp(i,j) << " " << finl;
              fict << upTp_temp(i,j) << " " << finl;
              fict << vpTp_temp(i,j) << " " << finl;
              fict << wpTp_temp(i,j) << " " << finl;
            }
        }
      fict << temps_deb << finl;
      fict.flush();
      fict.close();
      Cerr << "Temperature statistics saved at t=" << tps << finl;
    }
}
References Cerr, Sortie_Fichier_base::close(), finl, Sortie_Fichier_base::flush(), Navier_Stokes_std::inconnue(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nuv, Traitement_particulier_NS_Profils::oui_stat, Traitement_particulier_NS_Profils::sauver_stat(), Champ_Inc::temps(), Traitement_particulier_NS_Profils::temps_deb, Traitement_particulier_NS_Profils::temps_fin, Tmoy_temp, Trms_temp, upTp_temp, vpTp_temp, and wpTp_temp.
self_cast() [1/2]
const Traitement_particulier_NS_Profils_thermo_VDF & Traitement_particulier_NS_Profils_thermo_VDF::self_cast (const Objet_U & r) static
Definition at line 26 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
self_cast() [2/2]
Traitement_particulier_NS_Profils_thermo_VDF & Traitement_particulier_NS_Profils_thermo_VDF::self_cast (Objet_U & r) static
Definition at line 26 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
taille_memoire()
unsigned Traitement_particulier_NS_Profils_thermo_VDF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 26 of file Traitement_particulier_NS_Profils_thermo_VDF.cpp.
Member Data Documentation
fich_repr_stats_thermo
Nom Traitement_particulier_NS_Profils_thermo_VDF::fich_repr_stats_thermo protected
Definition at line 58 of file Traitement_particulier_NS_Profils_thermo_VDF.h.
Referenced by lire(), and reprendre_stat().
info_obj
const Type_info Traitement_particulier_NS_Profils_thermo_VDF::info_obj static
Definition at line 35 of file Traitement_particulier_NS_Profils_thermo_VDF.h.
mon_equation_NRJ
Ref_Convection_Diffusion_std Traitement_particulier_NS_Profils_thermo_VDF::mon_equation_NRJ protected
Definition at line 56 of file Traitement_particulier_NS_Profils_thermo_VDF.h.
Referenced by associer_eqn(), and calculer_moyennes_spatiales_thermo().
oui_repr_stats_thermo
int Traitement_particulier_NS_Profils_thermo_VDF::oui_repr_stats_thermo protected
Definition at line 57 of file Traitement_particulier_NS_Profils_thermo_VDF.h.
Referenced by init_calcul_stats(), lire(), and reprendre_stat().
oui_stats_thermo
int Traitement_particulier_NS_Profils_thermo_VDF::oui_stats_thermo protected
Definition at line 57 of file Traitement_particulier_NS_Profils_thermo_VDF.h.
Referenced by lire(), and post_traitement_particulier().
tmin_tmax
int Traitement_particulier_NS_Profils_thermo_VDF::tmin_tmax protected
Definition at line 57 of file Traitement_particulier_NS_Profils_thermo_VDF.h.
Referenced by calculer_moyennes_spatiales_thermo(), and lire().
Tmoy_temp
DoubleTab Traitement_particulier_NS_Profils_thermo_VDF::Tmoy_temp protected
Definition at line 59 of file Traitement_particulier_NS_Profils_thermo_VDF.h.
Referenced by init_calcul_stats(), post_traitement_particulier(), reprendre_stat(), and sauver_stat().
Trms_temp
DoubleTab Traitement_particulier_NS_Profils_thermo_VDF::Trms_temp protected
Definition at line 59 of file Traitement_particulier_NS_Profils_thermo_VDF.h.
Referenced by init_calcul_stats(), post_traitement_particulier(), reprendre_stat(), and sauver_stat().
upTp_temp
DoubleTab Traitement_particulier_NS_Profils_thermo_VDF::upTp_temp protected
Definition at line 59 of file Traitement_particulier_NS_Profils_thermo_VDF.h.
Referenced by init_calcul_stats(), post_traitement_particulier(), reprendre_stat(), and sauver_stat().
vpTp_temp
DoubleTab Traitement_particulier_NS_Profils_thermo_VDF::vpTp_temp protected
Definition at line 59 of file Traitement_particulier_NS_Profils_thermo_VDF.h.
Referenced by init_calcul_stats(), post_traitement_particulier(), reprendre_stat(), and sauver_stat().
wpTp_temp
DoubleTab Traitement_particulier_NS_Profils_thermo_VDF::wpTp_temp protected
Definition at line 59 of file Traitement_particulier_NS_Profils_thermo_VDF.h.
Referenced by init_calcul_stats(), post_traitement_particulier(), reprendre_stat(), and sauver_stat().
The documentation for this class was generated from the following files:
src/VDF/Traitement_particulier/Traitement_particulier_NS_Profils_thermo_VDF.h
src/VDF/Traitement_particulier/Traitement_particulier_NS_Profils_thermo_VDF.cpp