TRUST: Op_Conv_Muscl_New_VEF_Face Class Reference
Op_Conv_Muscl_New_VEF_Face Class Reference
class Op_Conv_Muscl_New_VEF_Face
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VEF
Le champ convecte est scalaire ou vecteur de type Champ_P1NC
Le schema de convection est isu du papier
"High-resolution FEM-TVD schemes based on a fully multidimensional flux limiter"
D.Kuzmin and S.Turek.
On herite de Op pour recuperer l'implicitation amont
#include <Op_Conv_Muscl_New_VEF_Face.h>
Public Member Functions
Op_Conv_Muscl_New_VEF_Face ()
~Op_Conv_Muscl_New_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void remplir_fluent (DoubleVect &) const override
int is_compressible () const
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
double calculer_dt_stab () const override
Calcul dt_stab.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Public Member Functions inherited from Op_Conv_VEF_Face
~Op_Conv_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Op_Conv_VEF_Face ()
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
void remplir_fluent (DoubleVect &) const override
void dimensionner (Matrice_Morse &) const override
on dimensionne notre matrice au moyen de la methode dimensionner de la classe
Op_VEF_Face.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
On modifie le second membre et la matrice dans le cas des
conditions de dirichlet.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
on assemble la matrice des inconnues implicite.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void get_ordre (int &) const
void get_type_lim (Motcle &) const
void get_alpha (double &) const
void get_type_op (int &) const
Public Member Functions inherited from Op_Conv_VEF_base
Op_Conv_VEF_base ()
~Op_Conv_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_vitesse (const Champ_base &) override
const Champ_Inc_base & vitesse () const
Champ_Inc_base & vitesse ()
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
void abortTimeStep () override
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_dt_local (DoubleTab &) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_fluent (DoubleVect &) const
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_zone_cl_dis (const Zone_Cl_dis_base &) override
int phi_u_transportant (const Equation_base &eq) const
definit si l'on convecte psi avec phi*u ou avec u
Public Member Functions inherited from Operateur_Conv_base
Operateur_Conv_base ()
initialise dt_stab_conv a -123
~Operateur_Conv_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_vitesse (const Champ_base &vit)=0
double dt_stab_conv () const
void fixer_dt_stab_conv (double dt)
virtual void associer_norme_vitesse (const Champ_base &norme_vitesse)
virtual void associer_vitesse_pour_pas_de_temps (const Champ_base &vitesse)
virtual void set_incompressible (const int)
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Conv_Muscl_New_VEF_Face & self_cast (Objet_U &)
static const Op_Conv_Muscl_New_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Conv_VEF_Face
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Conv_VEF_Face & self_cast (Objet_U &)
static const Op_Conv_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Conv_VEF_base
static const Type_info * info ()
static Op_Conv_VEF_base & self_cast (Objet_U &)
static const Op_Conv_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Conv_base
static const Type_info * info ()
static Operateur_Conv_base & self_cast (Objet_U &)
static const Operateur_Conv_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Conv_VEF_Face
static const Type_info info_obj
Static Public Attributes inherited from Op_Conv_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Conv_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Conv_VEF_Face
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Private Member Functions
void calculer_flux_bords (const DoubleTab &, const DoubleTab &, const DoubleTab &) const
void calculer_coefficients_operateur_centre (DoubleTab &, DoubleTab &, DoubleTab &, DoubleTab &, const int, const DoubleTab &vitesse) const
void calculer_flux_operateur_centre (DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const int, const DoubleTab &, const DoubleTab &) const
void modifier_flux_operateur_centre (DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const int, const DoubleTab &, const DoubleTab &) const
DoubleTab & ajouter_partie_compressible (const DoubleTab &, DoubleTab &, const DoubleTab &vitesse) const
DoubleTab & ajouter_operateur_centre (const DoubleTab &, const DoubleTab &, const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_diffusion (const DoubleTab &, const DoubleTab &, const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_antidiffusion (const DoubleTab &, const DoubleTab &, const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_antidiffusion_v1 (const DoubleTab &, const DoubleTab &, const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_antidiffusion_v2 (const DoubleTab &, const DoubleTab &, const DoubleTab &, DoubleTab &) const
void calculer_senseur_v1 (const DoubleTab &, const DoubleTab &, const DoubleVect &, const int, const int, const IntTab &, const IntTab &, const IntTab &, ArrOfDouble &, ArrOfDouble &, ArrOfDouble &, ArrOfDouble &) const
void calculer_senseur_v2 (const DoubleTab &, const DoubleTab &, const DoubleVect &, const int, const int, const IntTab &, const IntTab &, const IntTab &, ArrOfDouble &, ArrOfDouble &, ArrOfDouble &, ArrOfDouble &) const
void mettre_a_jour_pour_periodicite (const DoubleTab &, const DoubleTab &, DoubleTab &) const
void ajouter_old (const DoubleTab &, DoubleTab &, const DoubleTab &vitesse) const
void calculer_data_pour_dirichlet ()
void ajouter_contribution_operateur_centre (const DoubleTab &, const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_diffusion (const DoubleTab &, const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_antidiffusion (const DoubleTab &, const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_partie_compressible (const DoubleTab &, const DoubleTab &, Matrice_Morse &) const
void test (const DoubleTab &, const DoubleTab &, const DoubleTab &vitesse) const
void test_difference_Kij (const DoubleTab &, DoubleTab &, DoubleTab &, const DoubleTab &vitesse) const
void test_difference_resu (const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &vitesse) const
void test_implicite () const
Private Attributes
IntTab is_element_for_upwinding_
IntTab is_dirichlet_faces_
ArrOfDouble alpha_tab
ArrOfDouble beta
vaut zero pour les faces ou l'on souhaite degenerer en Amont. mutable DoubleTab limiteurs_;//tableau stockant pour chaque face la moyenne algebrique du limiteur
double alpha_
double max_limiteur_
int centered_
int upwind_
int stabilized_
int old_centered_
int version_
int facsec_auto_
Nom nom_sous_zone
Ref_Sous_zone_VF la_sous_zone_dis
double(* limiteur_)(double)
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Protected Types inherited from Op_Conv_VEF_Face
enum type_operateur { amont , muscl , centre }
Protected Attributes inherited from Op_Conv_VEF_Face
Motcle type_lim
int ordre
double alpha_
type_operateur type_op
double(* LIMITEUR)(double, double)
ArrOfInt traitement_pres_bord_
ArrOfInt est_une_face_de_dirichlet_
Protected Attributes inherited from Op_Conv_VEF_base
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base vitesse_
DoubleVect fluent
tableau qui sert pour le calcul du pas de temps de stabilite
int jeton
int roue
Protected Attributes inherited from Operateur_Conv_base
Ref_Champ_base la_norme_vitesse
Ref_Champ_base vitesse_pour_pas_de_temps_
double dt_stab_conv_
int incompressible_ = 1
incompressible_= 1 -> l'operateur discretise div(v x inco), incompressible_ = 0 -> il discretise v.grad(inco)
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Op_Conv_Muscl_New_VEF_Face
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VEF
Le champ convecte est scalaire ou vecteur de type Champ_P1NC
Le schema de convection est isu du papier
"High-resolution FEM-TVD schemes based on a fully multidimensional flux limiter"
D.Kuzmin and S.Turek.
On herite de Op pour recuperer l'implicitation amont
Definition at line 42 of file Op_Conv_Muscl_New_VEF_Face.h.
Constructor & Destructor Documentation
Op_Conv_Muscl_New_VEF_Face()
Op_Conv_Muscl_New_VEF_Face::Op_Conv_Muscl_New_VEF_Face ()
Definition at line 73 of file Op_Conv_Muscl_New_VEF_Face.cpp.
~Op_Conv_Muscl_New_VEF_Face()
Op_Conv_Muscl_New_VEF_Face::~Op_Conv_Muscl_New_VEF_Face ()
Definition at line 73 of file Op_Conv_Muscl_New_VEF_Face.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Conv_Muscl_New_VEF_Face::ajouter (const DoubleTab & transporte_2, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 1028 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  DoubleTab sauv(resu);
  resu=0;
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Champ_P1NC& la_vitesse=ref_cast( Champ_P1NC, vitesse_.valeur());
  const DoubleTab& vitesse_2=la_vitesse.valeurs();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const int marq=phi_u_transportant(equation());
  const int nb_faces_elem=elem_faces.dimension(1);
  assert(nb_faces_elem==(dimension+1));
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const int nfa7 = zone_VEF.type_elem().nb_facette();
  int nb_comp=1;
  if(resu.nb_dim()!=1)
    nb_comp=resu.dimension(1);
  DoubleTab transporte_;
  DoubleTab vitesse_face_;
// soit on a transporte=phi*transporte_ et vitesse=vitesse_
// soit transporte=transporte_ et vitesse=phi*vitesse_
// cela depend si on transporte avec phi u ou avec u.
  const DoubleTab& velocity=modif_par_porosite_si_flag(vitesse_2,vitesse_face_,marq,porosite_face);
  DoubleTab Kij(nb_elem_tot,nb_faces_elem,nb_faces_elem);
  DoubleTab Fij(nb_elem_tot,nb_faces_elem,nb_faces_elem,nb_comp);
  DoubleTab Cij(nb_elem_tot,nfa7);
  DoubleTab Sij(nb_elem_tot,nfa7);
  DoubleTab Sij2;
  if (Objet_U::dimension==3)
    {
      Sij2.resize(nb_elem_tot,nfa7);
      Sij2=0.;
    }
// Pour tenir compte des conditions de Neumann sortie libre
// soit on a transporte=phi*transporte_ et vitesse=vitesse_
// soit transporte=transporte_ et vitesse=phi*vitesse_
// cela depend si on transporte avec phi u ou avec u.
  const DoubleTab& transporte=modif_par_porosite_si_flag(transporte_2,transporte_,!marq,porosite_face);
// Initialisation du tableau flux_bords_ pour le calcul des pertes de charge
  flux_bords_.resize(zone_VEF.nb_faces_bord(),nb_comp);
  calculer_flux_bords(Kij,velocity,transporte);
// statistiques().begin_count(m1);
  calculer_coefficients_operateur_centre(Kij,Cij,Sij,Sij2,nb_comp,velocity);
  calculer_flux_operateur_centre(Fij,Kij,Cij,Sij,Sij2,nb_comp,velocity,transporte);
  if (old_centered_) modifier_flux_operateur_centre(Fij,Kij,Cij,Sij,Sij2,nb_comp,velocity,transporte);
// statistiques().end_count(m1);
// statistiques().begin_count(m2);
  if (centered_) ajouter_operateur_centre(Kij,Fij,transporte,resu);
  if (upwind_) ajouter_diffusion(Kij,Fij,transporte,resu);
// statistiques().end_count(m2);
// statistiques().begin_count(m3);
  if (stabilized_) ajouter_antidiffusion(Kij,Fij,transporte,resu);
// statistiques().end_count(m3);
  mettre_a_jour_pour_periodicite(Kij,transporte,resu);
  resu*=-1.;//car l'operateur de convection est construit en tant que terme source
  resu+=sauv;
  modifier_flux(*this);
  return resu;
}
References ajouter_antidiffusion(), ajouter_diffusion(), ajouter_operateur_centre(), calculer_coefficients_operateur_centre(), calculer_flux_bords(), calculer_flux_operateur_centre(), centered_, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Operateur_base::flux_bords_, Op_Conv_VEF_base::la_zone_vef, mettre_a_jour_pour_periodicite(), modif_par_porosite_si_flag(), Op_VEF_Face::modifier_flux(), modifier_flux_operateur_centre(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces_bord(), Elem_VEF::nb_facette(), old_centered_, Op_Conv_VEF_base::phi_u_transportant(), Zone_VF::porosite_face(), ref_cast, TRUSTTab< _TYPE_ >::resize(), stabilized_, transporte_, Zone_VEF::type_elem(), upwind_, Ref_Champ_Inc_base::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc_base::valeurs(), and Op_Conv_VEF_base::vitesse_.
ajouter_antidiffusion()
DoubleTab & Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion (const DoubleTab & Kij, const DoubleTab & Fij, const DoubleTab & transporte, DoubleTab & resu) const private
Definition at line 1669 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  switch(version_)
    {
    case 1 :
      return ajouter_antidiffusion_v1(Kij,Fij,transporte,resu);
      break;
    case 2 :
      return ajouter_antidiffusion_v2(Kij,Fij,transporte,resu);
      break;
    default :
      if (Process::je_suis_maitre())
        {
          Cerr<<"Error in Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion()"<<finl;
          Cerr<<"Version number "<<version_<<" of antidiffusive operator does not exist"<<finl;
        }
      Process::exit();
      break;
    }
  return resu;
}
References ajouter_antidiffusion_v1(), ajouter_antidiffusion_v2(), Cerr, Process::exit(), finl, Process::je_suis_maitre(), and version_.
Referenced by ajouter().
ajouter_antidiffusion_v1()
DoubleTab & Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1 (const DoubleTab & Kij, const DoubleTab & Fij, const DoubleTab & transporte, DoubleTab & resu) const private
Definition at line 1827 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const DoubleVect& transporteV = transporte;
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& KEL=zone_VEF.type_elem().valeur().KEL();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const IntTab& num_fac_loc = zone_VEF.get_num_fac_loc();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nfa7 = zone_VEF.type_elem().nb_facette();
  int nb_comp=1;
  if (transporte.nb_dim()!=1) nb_comp=transporte.dimension(1);
  int elem=0;
  int facei=0,facei_loc=0;
  int facej=0,facej_loc=0;
  int ligne=0,colonne=0;
  int dim=0;
  int fa7=0;
// Pour le limiteur
  ArrOfDouble Pi_plus(nb_comp),Pi_moins(nb_comp);
  ArrOfDouble Qi_plus(nb_comp),Qi_moins(nb_comp);
  Pi_plus=0., Pi_moins=0.;
  Qi_plus=0., Qi_moins=0.;
// Pour le limiteur
  ArrOfDouble Pj_plus(nb_comp),Pj_moins(nb_comp);
  ArrOfDouble Qj_plus(nb_comp),Qj_moins(nb_comp);
  Pj_plus=0., Pj_moins=0.;
  Qj_plus=0., Qj_moins=0.;
// double coeffij=0.,coeffji=0.;
  double fij=0.,fji=0.;
  double kij=0.;
  double R=0.;
  double Ri=0.;
  double Rj=0.;
  double tmp=0.;
  DoubleVect& resuV = resu;
// Pour les faces internes
  for (elem=0; elem<nb_elem_tot; elem++)
    for (fa7=0; fa7<nfa7; fa7++)
      {
        facei_loc=KEL(0,fa7);
        facej_loc=KEL(1,fa7);
        facei=elem_faces(elem,facei_loc);
        facej=elem_faces(elem,facej_loc);
        kij=Kij(elem,facei_loc,facej_loc);
        Pi_plus=0., Pi_moins=0.;
        Qi_plus=0., Qi_moins=0.;
        calculer_senseur_v1(Kij,Fij,transporteV,nb_comp,facei,elem_faces,face_voisins,num_fac_loc,Pi_plus,Pi_moins,Qi_plus,Qi_moins);
        Pj_plus=0., Pj_moins=0.;
        Qj_plus=0., Qj_moins=0.;
        calculer_senseur_v1(Kij,Fij,transporteV,nb_comp,facej,elem_faces,face_voisins,num_fac_loc,Pj_plus,Pj_moins,Qj_plus,Qj_moins);
        for (dim=0; dim<nb_comp; dim++)
          {
            fij=alpha_*Fij(elem,facei_loc,facej_loc,dim);
            fji=alpha_*Fij(elem,facej_loc,facei_loc,dim);
            ligne=facei*nb_comp+dim;
            colonne=facej*nb_comp+dim;
            if (kij>=0.)
              {
// Face amont : facei
                if (fij>=0.)
                  {
// Ri=(Pi_plus(dim)==0.)?0.:Qi_plus(dim)/Pi_plus(dim);
// Rj=(Pj_moins(dim)==0.)?0.:Qj_moins(dim)/Pj_moins(dim);//car fji=-fij
// Ri=(Pi_plus(dim)==0.)?0.:Qi_plus(dim)/(Pi_plus(dim)+DMINFLOAT);
// Rj=(Pj_moins(dim)==0.)?0.:Qj_moins(dim)/(Pj_moins(dim)+DMINFLOAT);//car fji=-fij
                    Ri=(std::fabs(Pi_plus[dim])<DMINFLOAT)?0.:Qi_plus[dim]/Pi_plus[dim];
                    Rj=(std::fabs(Pj_moins[dim])<DMINFLOAT)?0.:Qj_moins[dim]/Pj_moins[dim];//car fji=-fij
                  }
                else
                  {
// Ri=(Pi_moins(dim)==0.)?0.:Qi_moins(dim)/Pi_moins(dim);
// Rj=(Pj_plus(dim)==0.)?0.:Qj_plus(dim)/Pj_plus(dim);//car fji=-fij
// Ri=(Pi_moins(dim)==0.)?0.:Qi_moins(dim)/(Pi_moins(dim)+DMINFLOAT);
// Rj=(Pj_plus(dim)==0.)?0.:Qj_plus(dim)/(Pj_plus(dim)+DMINFLOAT);//car fji=-fij
                    Ri=(std::fabs(Pi_moins[dim])<DMINFLOAT)?0.:Qi_moins[dim]/Pi_moins[dim];
                    Rj=(std::fabs(Pj_plus[dim])<DMINFLOAT)?0.:Qj_plus[dim]/Pj_plus[dim];//car fji=-fij
                  }
                if (is_dirichlet_faces_(facej)) Rj=DMAXFLOAT;//on n'a pas besoin de prendre le min quand il y a une face de Dirichlet
                R=(Ri<=Rj)?Ri:Rj;
                R=(*limiteur_)(R);
                tmp=R*fij;
                resuV[ligne]+=tmp;
                resuV[colonne]-=tmp;
              }
            else
              {
// Face amont : facej
                if (fji<=0.)
                  {
// Rj=(Pj_moins(dim)==0.)?0.:Qj_moins(dim)/Pj_moins(dim);
// Ri=(Pi_plus(dim)==0.)?0.:Qi_plus(dim)/Pi_plus(dim);
// Rj=(Pj_moins(dim)==0.)?0.:Qj_moins(dim)/(Pj_moins(dim)+DMINFLOAT);
// Ri=(Pi_plus(dim)==0.)?0.:Qi_plus(dim)/(Pi_plus(dim)+DMINFLOAT);
                    Rj=(std::fabs(Pj_moins[dim])<DMINFLOAT)?0.:Qj_moins[dim]/Pj_moins[dim];
                    Ri=(std::fabs(Pi_plus[dim])<DMINFLOAT)?0.:Qi_plus[dim]/Pi_plus[dim];
                  }
                else
                  {
// Rj=(Pj_plus(dim)==0.)?0.:Qj_plus(dim)/Pj_plus(dim);
// Ri=(Pi_moins(dim)==0.)?0.:Qi_moins(dim)/Pi_moins(dim);
// Rj=(Pj_plus(dim)==0.)?0.:Qj_plus(dim)/(Pj_plus(dim)+DMINFLOAT);
// Ri=(Pi_moins(dim)==0.)?0.:Qi_moins(dim)/(Pi_moins(dim)+DMINFLOAT);
                    Rj=(std::fabs(Pj_plus[dim])<DMINFLOAT)?0.:Qj_plus[dim]/Pj_plus[dim];
                    Ri=(std::fabs(Pi_moins[dim])<DMINFLOAT)?0.:Qi_moins[dim]/Pi_moins[dim];
                  }
                if (is_dirichlet_faces_(facei)) Ri=DMAXFLOAT;//on n'a pas besoin de prendre le min quand il y a une face de Dirichlet
                R=(Ri<=Rj)?Ri:Rj;
                R=(*limiteur_)(R);
                tmp=R*fji;
                resuV[ligne]-=tmp;
                resuV[colonne]+=tmp;
              }
          }
      }
// Pour les faces de bord
// IL N'Y A RIEN a FAIRE TOUT EST FAIT DANS LA FONCTION AJOUTER_DIFFUSION
// QUI EST PARFAITEMENT COMPLeTER PAR LA FONCTION AJOUTER_ANTIDIFFUSION
// Retour du resultat
// resuV+=antidiff;
  return resu;
}
References alpha_, calculer_senseur_v1(), TRUSTTab< _TYPE_ >::dimension(), DMAXFLOAT, DMINFLOAT, Zone_VF::elem_faces(), Zone_VF::face_voisins(), Zone_VF::get_num_fac_loc(), is_dirichlet_faces_, Elem_VEF_base::KEL(), Op_Conv_VEF_base::la_zone_vef, TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Elem_VEF::nb_facette(), Zone_VEF::type_elem(), Deriv_Elem_VEF_base::valeur(), and Ref_Zone_VEF::valeur().
Referenced by ajouter_antidiffusion().
ajouter_antidiffusion_v2()
DoubleTab & Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2 (const DoubleTab & Kij, const DoubleTab & Fij, const DoubleTab & transporte, DoubleTab & resu) const private
Definition at line 1698 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const DoubleVect& transporteV = transporte;
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& KEL=zone_VEF.type_elem().valeur().KEL();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const IntTab& num_fac_loc = zone_VEF.get_num_fac_loc();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nfa7 = zone_VEF.type_elem().nb_facette();
  int nb_comp=1;
  if (transporte.nb_dim()!=1) nb_comp=transporte.dimension(1);
  int elem=0;
  int facei=0,facei_loc=0;
  int facej=0,facej_loc=0;
  int ligne=0,colonne=0;
  int dim=0;
  int fa7=0;
// Pour le limiteur
  ArrOfDouble P_plus(nb_comp),P_moins(nb_comp);
  ArrOfDouble Q_plus(nb_comp),Q_moins(nb_comp);
  P_plus=0., P_moins=0.;
  Q_plus=0., Q_moins=0.;
// double coeffij=0.,coeffji=0.;
  double fij=0.,fji=0.;
  double kij=0.;
  double R=0.;
  double tmp=0.;
  double fij_low=0.,fji_low=0.;
  DoubleVect& resuV = resu;
// Pour les faces internes
  for (elem=0; elem<nb_elem_tot; elem++)
    for (fa7=0; fa7<nfa7; fa7++)
      {
        facei_loc=KEL(0,fa7);
        facej_loc=KEL(1,fa7);
        facei=elem_faces(elem,facei_loc);
        facej=elem_faces(elem,facej_loc);
        kij=Kij(elem,facei_loc,facej_loc);
        P_plus=0., P_moins=0.;
        Q_plus=0., Q_moins=0.;
        if (kij>=0.) //facei amont
          calculer_senseur_v2(Kij,Fij,transporteV,nb_comp,facei,elem_faces,face_voisins,num_fac_loc,P_plus,P_moins,Q_plus,Q_moins);//La face i est amont
        else //facej amont
          calculer_senseur_v2(Kij,Fij,transporteV,nb_comp,facej,elem_faces,face_voisins,num_fac_loc,P_plus,P_moins,Q_plus,Q_moins);//La face j est amont
        for (dim=0; dim<nb_comp; dim++)
          {
            fij=alpha_*Fij(elem,facei_loc,facej_loc,dim);
            fji=alpha_*Fij(elem,facej_loc,facei_loc,dim);
            ligne=facei*nb_comp+dim;
            colonne=facej*nb_comp+dim;
            fij_low=transporteV[colonne]-transporteV[ligne];
            fij_low*=kij;
            fji_low=fij_low;
            if (kij>=0.) //facei amont
              {
// if (fij>=0.) R=(P_plus(dim)==0.)?0.:Q_plus(dim)/P_plus(dim);
// else R=(P_moins(dim)==0.)?0.:Q_moins(dim)/P_moins(dim);
// if (fij>=0.) R=(P_plus(dim)==0.)?0.:Q_plus(dim)/(P_plus(dim)+DMINFLOAT);
// else R=(P_moins(dim)==0.)?0.:Q_moins(dim)/(P_moins(dim)+DMINFLOAT);
                if (fij>=0.) R=(std::fabs(P_plus[dim])<DMINFLOAT)?0.:Q_plus[dim]/P_plus[dim];
                else R=(std::fabs(P_moins[dim])<DMINFLOAT)?0.:Q_moins[dim]/P_moins[dim];
                R=(*limiteur_)(R);
                R*=fij;
                if (!is_dirichlet_faces_(facej))
                  tmp=optimum(R,fji_low);
                else
                  tmp=R;
                resuV[ligne]+=tmp;
                resuV[colonne]-=tmp;
              }
            else //facej amont
              {
// if (fji<=0.) R=(P_moins(dim)==0.)?0.:Q_moins(dim)/P_moins(dim);
// else R=(P_plus(dim)==0.)?0.:Q_plus(dim)/P_plus(dim);
// if (fji<=0.) R=(P_moins(dim)==0.)?0.:Q_moins(dim)/(P_moins(dim)+DMINFLOAT);
// else R=(P_plus(dim)==0.)?0.:Q_plus(dim)/(P_plus(dim)+DMINFLOAT);
                if (fji<=0.) R=(std::fabs(P_moins[dim])<DMINFLOAT)?0.:Q_moins[dim]/P_moins[dim];
                else R=(std::fabs(P_plus[dim])<DMINFLOAT)?0.:Q_plus[dim]/P_plus[dim];
                R=(*limiteur_)(R);
                R*=fji;
                if (!is_dirichlet_faces_(facei))
                  tmp=optimum(R,fij_low);
                else
                  tmp=R;
                resuV[ligne]-=tmp;
                resuV[colonne]+=tmp;
              }
          }
      }
// Pour les faces de bord
// IL N'Y A RIEN a FAIRE TOUT EST FAIT DANS LA FONCTION AJOUTER_DIFFUSION
// QUI EST PARFAITEMENT COMPLeTER PAR LA FONCTION AJOUTER_ANTIDIFFUSION
// Retour du resultat
  return resu;
}
References alpha_, calculer_senseur_v2(), TRUSTTab< _TYPE_ >::dimension(), DMINFLOAT, Zone_VF::elem_faces(), Zone_VF::face_voisins(), Zone_VF::get_num_fac_loc(), is_dirichlet_faces_, Elem_VEF_base::KEL(), Op_Conv_VEF_base::la_zone_vef, TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Elem_VEF::nb_facette(), optimum(), Zone_VEF::type_elem(), Deriv_Elem_VEF_base::valeur(), and Ref_Zone_VEF::valeur().
Referenced by ajouter_antidiffusion().
ajouter_contribution()
void Op_Conv_Muscl_New_VEF_Face::ajouter_contribution (const DoubleTab & transporte_2, Matrice_Morse & matrice) const
Definition at line 2356 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
}
Referenced by contribuer_a_avec().
ajouter_contribution_antidiffusion()
void Op_Conv_Muscl_New_VEF_Face::ajouter_contribution_antidiffusion (const DoubleTab & Kij, const DoubleTab & transporte, Matrice_Morse & matrice) const private
Definition at line 2777 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
// const Zone_VEF& zone_VEF=la_zone_vef.valeur();
// const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
// const IntTab& elem_faces=zone_VEF.elem_faces();
// const IntTab& face_voisins = zone_VEF.face_voisins();
// const int nb_elem_tot=zone_VEF.nb_elem_tot();
// const int nb_faces_elem=elem_faces.dimension(1);
// const int nb_bord=zone_Cl_VEF.nb_cond_lim();
// int nb_comp=1;
// if (transporte.nb_dim()!=1) nb_comp=transporte.dimension(1);
// int elem=0;
// int elem_loc=0;
// int facei=0,facei_loc=0;
// int faceiAss=0;
// int ind_face=0,ind_faceiAss=0;
// int facej=0,facej_loc=0;
// int ligne=0,colonne=0;
// int dim=0;
// int face_amont=0,face_aval=0;
// int faceToComplete=0;
// int num1=0,num2=0;
// int n_bord=0;
// double kij=0.,kji=0.,dij=0.;
// double lij=0.,lji=0.;
// double daij=0.;
// double delta=0.;
// double coeffij=0.,coeffji=0.;
// double coeff=0.;
// double R=0.;
// //Pour le limiteur
// ArrOfDouble P_plus(nb_comp),P_moins(nb_comp);
// ArrOfDouble Q_plus(nb_comp),Q_moins(nb_comp);
// P_plus=0., P_moins=0.;
// Q_plus=0., Q_moins=0.;
// const DoubleVect& transporteV=ref_cast(DoubleVect,transporte);
// const IntTab& num_fac_loc = zone_VEF.get_num_fac_loc();
// for (elem=0; elem<nb_elem_tot; elem++)
// for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
// {
// facei=elem_faces(elem,facei_loc);
// P_plus=0., P_moins=0.;
// Q_plus=0., Q_moins=0.;
// calculer_senseur(Kij,transporteV,nb_comp,facei,elem_faces,face_voisins,num_fac_loc,P_plus,P_moins,Q_plus,Q_moins);
// for (facej_loc=0; facej_loc<nb_faces_elem; facej_loc++)
// if (facej_loc!=facei_loc)
// {
// facej=elem_faces(elem,facej_loc);
// kij = Kij(elem,facei_loc,facej_loc);
// kji = Kij(elem,facej_loc,facei_loc);
// dij = Dij(elem,facei_loc,facej_loc,Kij);
// lij = kij+dij;
// lji = kji+dij;
// assert(lij>=0);
// assert(lji>=0);
// if (lij<=lji) //facei est amont
// {
// face_amont = facei;
// face_aval = facej;
// //Si lij==lji, on passe deux foix dans la boucle
// //d'ou la presence du coefficient 1/2
// coeff = 1.*(lij<lji)+0.5*(lij==lji);
// assert(coeff==1. || coeff==0.5);
// for (dim=0; dim<nb_comp; dim++)
// {
// ligne=face_amont*nb_comp+dim;
// colonne=face_aval*nb_comp+dim;
// delta=transporteV[ligne]-transporteV[colonne];
// //Limiteur de pente
// if (delta>=0.) R=(P_plus(dim)==0.) ? 0. : Q_plus(dim)/P_plus(dim);
// else  R=(P_moins(dim)==0.) ? 0. : Q_moins(dim)/P_moins(dim);
// daij=minimum(limiteur(R)*dij,lji);
// assert(daij>=0);
// assert(daij<=lji);
// coeffij=alpha_tab(face_amont)*beta(face_amont)*daij;
// coeffji=alpha_tab(face_aval)*beta(face_aval)*daij;
// //Calcul de la matrice
// matrice(ligne,ligne)-=coeffij*coeff;
// matrice(ligne,colonne)+=coeffij*coeff;
// matrice(colonne,colonne)-=coeffji*coeff;
// matrice(colonne,ligne)+=coeffji*coeff;
// }
// }
// }
// }
// //
// //Pour la periodicite
// //
// for (n_bord=0; n_bord<nb_bord; n_bord++)
// {
// const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
// const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// num1 = 0;
// num2=le_bord.nb_faces();//pour ne parcourir que les faces reelles
// if (sub_type(Periodique,la_cl.valeur()))
// {
// const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
// //Pour le limiteur
// ArrOfDouble Pj_plus(nb_comp),Pj_moins(nb_comp);
// ArrOfDouble Qj_plus(nb_comp),Qj_moins(nb_comp);
// Pj_plus=0., Pj_moins=0.;
// Qj_plus=0., Qj_moins=0.;
// for (ind_face=num1; ind_face<num2; ind_face++)
// {
// facei=le_bord.num_face(ind_face);
// ind_faceiAss=la_cl_perio.face_associee(ind_face);
// faceiAss=le_bord.num_face(ind_faceiAss);
// //Pour ne parcourir qu'une seule fois les faces perio
// if (facei<faceiAss)
// for (elem_loc=0;elem_loc<2;elem_loc++)
// {
// elem=face_voisins(facei,elem_loc);
// assert(elem!=-1);
// //Calcul du numero local de la face dans "elem"
// facei_loc=num_fac_loc(facei,elem_loc);
// if (facei_loc!=-1)
// faceToComplete=faceiAss;
// else
// {
// faceToComplete=facei;
// facei_loc=num_fac_loc(faceiAss,elem_loc);
// assert(facei_loc!=-1);
// }
// //Calcul du coefficient a rajouter dans la matrice
// P_plus=0., P_moins=0.;
// Q_plus=0., Q_moins=0.;
// calculer_senseur(Kij,transporteV,nb_comp,faceToComplete,elem_faces,face_voisins,num_fac_loc,P_plus,P_moins,Q_plus,Q_moins);
// for (facej_loc=0; facej_loc<nb_faces_elem; facej_loc++)
// if (facej_loc!=facei_loc)
// {
// facej=elem_faces(elem,facej_loc);
// kij = Kij(elem,facei_loc,facej_loc);
// kji = Kij(elem,facej_loc,facei_loc);
// dij = Dij(elem,facei_loc,facej_loc,Kij);
// lij = kij+dij;
// lji = kji+dij;
// assert(lij>=0);
// assert(lji>=0);
// if (lij<=lji) //faceToComplete est amont
// {
// face_amont=faceToComplete;
// face_aval=facej;
// //Si lij==lji, on passe deux foix dans la boucle
// //d'ou la presence du coefficient 1/2
// coeff = 1.*(lij<lji)+0.5*(lij==lji);
// assert(coeff==1. || coeff==0.5);
// for (dim=0; dim<nb_comp; dim++)
// {
// ligne=face_amont*nb_comp+dim;
// colonne=face_aval*nb_comp+dim;
// delta=transporteV[ligne]-transporteV[colonne];
// //Limiteur de pente
// if (delta>=0.) R=(P_plus(dim)==0.) ? 0. : Q_plus(dim)/P_plus(dim);
// else  R=(P_moins(dim)==0.) ? 0. : Q_moins(dim)/P_moins(dim);
// daij=minimum(limiteur(R)*dij,lji);
// assert(daij>=0);
// assert(daij<=lji);
// coeffij=alpha_tab(face_amont)*beta(face_amont)*daij;
// //Calcul de la matrice
// matrice(ligne,ligne)-=coeffij*coeff;
// matrice(ligne,colonne)+=coeffij*coeff;
// }
// }
// else  //faceToComplete est aval
// {
// face_aval=faceToComplete;
// face_amont=facej;
// coeff=1.;
// Pj_plus=0., Pj_moins=0.;
// Qj_plus=0., Qj_moins=0.;
// calculer_senseur(Kij,transporteV,nb_comp,facej,elem_faces,face_voisins,num_fac_loc,Pj_plus,Pj_moins,Qj_plus,Qj_moins);
// for (dim=0; dim<nb_comp; dim++)
// {
// ligne=face_amont*nb_comp+dim;
// colonne=face_aval*nb_comp+dim;
// delta=transporteV[ligne]-transporteV[colonne];
// //Limiteur de pente
// if (delta>=0.) R=(Pj_plus(dim)==0.) ? 0. : Qj_plus(dim)/Pj_plus(dim);
// else  R=(Pj_moins(dim)==0.) ? 0. : Qj_moins(dim)/Pj_moins(dim);
// daij=minimum(limiteur(R)*dij,lij);
// assert(daij>=0);
// assert(daij<=lij);
// coeffij=alpha_tab(face_aval)*beta(face_aval)*daij;
// //Calcul de la matrice
// matrice(colonne,colonne)-=coeffij*coeff;
// matrice(colonne,ligne)+=coeffij*coeff;
// }
// }
// }
// }
// }
// }
// }
}
ajouter_contribution_diffusion()
void Op_Conv_Muscl_New_VEF_Face::ajouter_contribution_diffusion (const DoubleTab & Kij, const DoubleTab & transporte, Matrice_Morse & matrice) const private
Definition at line 2487 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
// const Zone_VEF& zone_VEF=la_zone_vef.valeur();
// const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
// const IntTab& elem_faces=zone_VEF.elem_faces();
// const IntTab& face_voisins = zone_VEF.face_voisins();
// const int nb_elem_tot=zone_VEF.nb_elem_tot();
// const int nb_faces_elem=elem_faces.dimension(1);
// const int nb_bord=zone_Cl_VEF.nb_cond_lim();
// int nb_comp=1;
// if (transporte.nb_dim()!=1) nb_comp=transporte.dimension(1);
// int elem=0;
// int facei=0,facei_loc=0;
// int facej=0,facej_loc=0;
// int ligne=0,colonne=0;
// int dim=0;
// int ind_face=0;
// int num1=0,num2=0;
// int faceToComplete=0;
// int elem_loc=0;
// double dij=0.;
// double coeffij=0.,coeffji=0.;
// for (elem=0; elem<nb_elem_tot; elem++)
// for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
// {
// facei=elem_faces(elem,facei_loc);
// for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
// {
// facej=elem_faces(elem,facej_loc);
// assert(facej!=facei);
// dij=Dij(elem,facei_loc,facej_loc,Kij);
// assert(dij>=0);
// coeffij=alpha_tab(facei)*dij;
// coeffji=alpha_tab(facej)*dij;
// for (dim=0; dim<nb_comp; dim++)
// {
// ligne=facei*nb_comp+dim;
// colonne=facej*nb_comp+dim;
// //ATTENTION AU SIGNE : ici on code +div(uT)
// //REMARQUE : on utilise la symetrie de l'operateur
// matrice(ligne,ligne)+=coeffij;
// matrice(ligne,colonne)-=coeffij;
// matrice(colonne,colonne)+=coeffji;
// matrice(colonne,ligne)-=coeffji;
// }
// }
// }
// //
// //Pour la periodicite
// //
// const IntTab& num_fac_loc = zone_VEF.get_num_fac_loc();
// for (int n_bord=0; n_bord<nb_bord; n_bord++)
// {
// const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
// const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// num1 = 0;
// num2=le_bord.nb_faces_tot();//et surtout pas nb_faces() sinon on oublie certains coefficiens
// if (sub_type(Periodique,la_cl.valeur()))
// {
// const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
// int faceiAss=0,ind_faceiAss=0;
// for (ind_face=num1; ind_face<num2; ind_face++)
// {
// facei=le_bord.num_face(ind_face);
// ind_faceiAss=la_cl_perio.face_associee(ind_face);
// faceiAss=le_bord.num_face(ind_faceiAss);
// //Pour ne parcourir qu'une seule fois les faces perio
// if (facei<faceiAss)
// for (elem_loc=0;elem_loc<2;elem_loc++)
// {
// elem=face_voisins(facei,elem_loc);
// assert(elem!=-1);
// //Calcul du numero local de la face dans "elem"
// facei_loc=num_fac_loc(facei,elem_loc);
// if (facei_loc!=-1)
// faceToComplete=faceiAss;
// else
// {
// faceToComplete=facei;
// facei_loc=num_fac_loc(faceiAss,elem_loc);
// assert(facei_loc!=-1);
// }
// //Calcul des coefficients de la matrice dus a "elem"
// for (facej_loc=0; facej_loc<nb_faces_elem; facej_loc++)
// {
// facej=elem_faces(elem,facej_loc);
// if (facej_loc!=facei_loc)
// {
// dij=Dij(elem,facei_loc,facej_loc,Kij);
// assert(dij>=0);
// coeffij=alpha_tab(faceToComplete)*dij;
// coeffji=alpha_tab(facej)*dij;
// for (dim=0; dim<nb_comp; dim++)
// {
// ligne=faceToComplete*nb_comp+dim;
// colonne=facej*nb_comp+dim;
// //ATTENTION AU SIGNE : ici on code +div(uT)
// matrice(ligne,ligne)+=coeffij;
// matrice(ligne,colonne)-=coeffij;
// }
// }
// }
// }
// }
// }
// }
}
ajouter_contribution_operateur_centre()
void Op_Conv_Muscl_New_VEF_Face::ajouter_contribution_operateur_centre (const DoubleTab & Kij, const DoubleTab & transporte, Matrice_Morse & matrice) const private
Definition at line 2365 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
// const Zone_VEF& zone_VEF=la_zone_vef.valeur();
// const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
// const IntTab& elem_faces=zone_VEF.elem_faces();
// const IntTab& face_voisins = zone_VEF.face_voisins();
// const int nb_elem_tot=zone_VEF.nb_elem_tot();
// const int nb_faces_elem=elem_faces.dimension(1);
// const int nb_bord=zone_Cl_VEF.nb_cond_lim();
// int nb_comp=1;
// if (transporte.nb_dim()!=1) nb_comp=transporte.dimension(1);
// int elem=0;
// int facei=0,facei_loc=0;
// int facej=0,facej_loc=0;
// int ligne=0,colonne=0;
// int dim=0;
// int ind_face=0;
// int num1=0,num2=0;
// int faceToComplete=0;
// int elem_loc=0;
// double kij=0.,kji=0.;
// for (elem=0; elem<nb_elem_tot; elem++)
// for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
// {
// facei=elem_faces(elem,facei_loc);
// for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
// {
// facej=elem_faces(elem,facej_loc);
// assert(facej!=facei);
// kij=Kij(elem,facei_loc,facej_loc);
// kji=Kij(elem,facej_loc,facei_loc);
// for (dim=0; dim<nb_comp; dim++)
// {
// ligne=facei*nb_comp+dim;
// colonne=facej*nb_comp+dim;
// //ATTENTION AU SIGNE : ici on code +div(uT)
// matrice(ligne,ligne)+=kij;
// matrice(ligne,colonne)-=kij;
// matrice(colonne,colonne)+=kji;
// matrice(colonne,ligne)-=kji;
// }
// }
// }
// //
// //Pour la periodicite
// //
// const IntTab& num_fac_loc = zone_VEF.get_num_fac_loc();
// for (int n_bord=0; n_bord<nb_bord; n_bord++)
// {
// const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
// const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// num1 = 0;
// num2=le_bord.nb_faces_tot();//et surtout pas nb_faces sinon on oublie certains coefficients
// if (sub_type(Periodique,la_cl.valeur()))
// {
// const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
// int faceiAss=0,ind_faceiAss=0;
// for (ind_face=num1; ind_face<num2; ind_face++)
// {
// ind_faceiAss=la_cl_perio.face_associee(ind_face);
// facei=le_bord.num_face(ind_face);
// faceiAss=le_bord.num_face(ind_faceiAss);
// //Pour ne parcourir qu'une seule fois les faces perio
// if (facei<faceiAss)
// for (elem_loc=0;elem_loc<2;elem_loc++)
// {
// elem=face_voisins(facei,elem_loc);
// assert(elem!=-1);
// //Calcul du numero local de la face dans "elem"
// facei_loc=num_fac_loc(facei,elem_loc);
// if (facei_loc!=-1)
// faceToComplete=faceiAss;
// else
// {
// faceToComplete=facei;
// facei_loc=num_fac_loc(faceiAss,elem_loc);
// assert(facei_loc!=-1);
// }
// //Calcul des coefficients de la matrice dus a "elem"
// for (facej_loc=0; facej_loc<nb_faces_elem; facej_loc++)
// {
// facej=elem_faces(elem,facej_loc);
// if (facej_loc!=facei_loc)
// {
// kij=Kij(elem,facei_loc,facej_loc);
// kji=Kij(elem,facej_loc,facei_loc);
// for (dim=0; dim<nb_comp; dim++)
// {
// ligne=faceToComplete*nb_comp+dim;
// colonne=facej*nb_comp+dim;
// //ATTENTION AU SIGNE : ici on code +div(uT)
// matrice(ligne,ligne)+=kij;
// matrice(ligne,colonne)-=kij;
// }
// }
// }
// }
// }
// }
// }
}
ajouter_contribution_partie_compressible()
void Op_Conv_Muscl_New_VEF_Face::ajouter_contribution_partie_compressible (const DoubleTab & transporte, const DoubleTab & vitesse_2, Matrice_Morse & matrice) const private
Definition at line 2623 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
// const Zone_VEF& zone_VEF=la_zone_vef.valeur();
// const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
// const IntTab& elem_faces=zone_VEF.elem_faces();
// const IntTab& face_voisins = zone_VEF.face_voisins();
// const DoubleTab& face_normales=zone_VEF.face_normales();
// const int nb_elem_tot=zone_VEF.nb_elem_tot();
// const int nb_faces_elem=elem_faces.dimension(1);
// const int nb_bord=zone_Cl_VEF.nb_cond_lim();
// //Pour tenir compte de la porosite
// const int marq = phi_u_transportant(equation());
// const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// const DoubleVect& porosite_face = zone_VEF.porosite_face();
// DoubleTab vitesse(vitesse_.valeur().valeurs());
// for (int i=0; i<vitesse.dimension(0); i++)
// for (int j=0; j<vitesse.dimension(1); j++)
// vitesse(i,j)*=porosite_face(i);
// int nb_comp=1;
// if (transporte.nb_dim()!=1) nb_comp=transporte.dimension(1);
// int elem=0,type_elem=0;
// int facei=0,facei_loc=0;
// int faceiAss=0,ind_faceiAss=0;
// int ligne=0;
// int dim=0;
// int ind_face=0;
// int num1=0,num2=0;
// int faceToComplete=0;
// int elem_loc=0;
// int n_bord=0;
// double coeff=0.;
// double signe=0.;
// double div=0.;
// double (*formule)(int);
// if (!volumes_etendus_)
// if (dimension==2) formule=&formule_Id_2D;
// else formule=&formule_Id_3D;
// else
// if (dimension==2) formule=&formule_2D;
// else formule=&formule_3D;
// for (elem=0; elem<nb_elem_tot; elem++)
// {
// //Type de l'element : le nombre de faces de Dirichlet
// //qu'il contient
// type_elem=elem_nb_faces_dirichlet_(elem);
// coeff=formule(type_elem);
// //Calcul de la divergence par element
// div=0.;
// for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
// {
// facei=elem_faces(elem,facei_loc);
// signe=(face_voisins(facei,0)==elem)? 1.:-1.;
// for (dim=0; dim<dimension; dim++)
// div+=signe*face_normales(facei,dim)*vitesse(facei,dim);
// }
// div*=coeff;
// if (!marq) div/=porosite_elem(elem);
// //Calcul de la partie compressible
// for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
// {
// facei=elem_faces(elem,facei_loc);
// for (dim=0; dim<nb_comp; dim++)
// {
// ligne=facei*nb_comp+dim;
// matrice(ligne,ligne)+=div;
// }
// }
// }
// //
// //Pour la periodicite
// //
// const IntTab& num_fac_loc = zone_VEF.get_num_fac_loc();
// for (n_bord=0; n_bord<nb_bord; n_bord++)
// {
// const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
// const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// num1 = 0;
// num2=le_bord.nb_faces();//pour ne parcourir que les faces reelles
// if (sub_type(Periodique,la_cl.valeur()))
// {
// const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
// for (ind_face=num1; ind_face<num2; ind_face++)
// {
// facei=le_bord.num_face(ind_face);
// ind_faceiAss=la_cl_perio.face_associee(ind_face);
// faceiAss=le_bord.num_face(ind_faceiAss);
// //Pour ne parcourir qu'une seule fois les faces perio
// if (facei<faceiAss)
// for (elem_loc=0;elem_loc<2;elem_loc++)
// {
// elem=face_voisins(facei,elem_loc);
// assert(elem!=-1);
// //Calcul du numero local de la face dans "elem"
// facei_loc=num_fac_loc(facei,elem_loc);
// if (facei_loc!=-1)
// faceToComplete=faceiAss;
// else
// {
// faceToComplete=facei;
// facei_loc=num_fac_loc(faceiAss,elem_loc);
// assert(facei_loc!=-1);
// }
// //Type de l'element : le nombre de faces de Dirichlet
// //qu'il contient
// type_elem=elem_nb_faces_dirichlet_(elem);
// coeff=formule(type_elem);
// //Calcul de la divergence par element
// div=0.;
// for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
// {
// facei=elem_faces(elem,facei_loc);
// signe=(face_voisins(facei,0)==elem)? 1.:-1.;
// for (dim=0; dim<dimension; dim++)
// div+=signe*face_normales(facei,dim)*vitesse(facei,dim);
// }
// div*=coeff;
// if (!marq) div/=porosite_elem(elem);
// //Calcul de la partie compressible
// for (dim=0; dim<nb_comp; dim++)
// {
// ligne=faceToComplete*nb_comp+dim;
// matrice(ligne,ligne)+=div;
// }
// }
// }
// }
// }
}
ajouter_diffusion()
DoubleTab & Op_Conv_Muscl_New_VEF_Face::ajouter_diffusion (const DoubleTab & Kij, const DoubleTab & Fij, const DoubleTab & transporte, DoubleTab & resu) const private
Definition at line 1602 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& KEL=zone_VEF.type_elem().valeur().KEL();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nfa7 = zone_VEF.type_elem().nb_facette();
  int nb_comp=1;
  if (transporte.nb_dim()!=1) nb_comp=transporte.dimension(1);
  int elem=0;
  int facei=0,facei_loc=0;
  int facej=0,facej_loc=0;
  int ligne=0,colonne=0;
  int dim=0;
  int fa7=0;
// double coeffij=0.,coeffji=0.;
  double fij=0.,fji=0.;
  double psc=0.;
  DoubleVect& resuV = resu;
// Pour les faces internes
  for (elem=0; elem<nb_elem_tot; elem++)
    for (fa7=0; fa7<nfa7; fa7++)
      {
        facei_loc=KEL(0,fa7);
        facej_loc=KEL(1,fa7);
        facei=elem_faces(elem,facei_loc);
        facej=elem_faces(elem,facej_loc);
        psc=Kij(elem,facei_loc,facej_loc);
        for (dim=0; dim<nb_comp; dim++)
          {
            fij=alpha_*Fij(elem,facei_loc,facej_loc,dim);
            fji=alpha_*Fij(elem,facej_loc,facei_loc,dim);
            ligne=facei*nb_comp+dim;
            colonne=facej*nb_comp+dim;
            if (psc>=0.)
              {
                resuV[ligne]-=fij;
                resuV[colonne]+=fij;
              }
            else
              {
                resuV[ligne]+=fji;
                resuV[colonne]-=fji;
              }
          }
      }
// Pour les faces de bord :
// ON N'A RIEN a FAIRE
// Retour du resultat
  return resu;
}
References alpha_, TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), Elem_VEF_base::KEL(), Op_Conv_VEF_base::la_zone_vef, TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Elem_VEF::nb_facette(), Zone_VEF::type_elem(), Deriv_Elem_VEF_base::valeur(), and Ref_Zone_VEF::valeur().
Referenced by ajouter().
ajouter_old()
void Op_Conv_Muscl_New_VEF_Face::ajouter_old (const DoubleTab & transporte, DoubleTab & resu, const DoubleTab & vitesse) const private
Definition at line 2215 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
}
ajouter_operateur_centre()
DoubleTab & Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre (const DoubleTab & Kij, const DoubleTab & Fij, const DoubleTab & transporte, DoubleTab & resu) const private
Definition at line 1467 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& KEL=zone_VEF.type_elem().valeur().KEL();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const IntTab& num_fac_loc = zone_VEF.get_num_fac_loc();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nfa7 = zone_VEF.type_elem().nb_facette();
  const int premiere_face_int = zone_VEF.premiere_face_int();
  const int nb_faces = zone_VEF.nb_faces();
  int nb_comp=1;
  if (transporte.nb_dim()!=1) nb_comp=transporte.dimension(1);
  int elem=0;
  int facei=0,facei_loc=0;
  int facej=0,facej_loc=0;
  int ligne=0,colonne=0;
  int dim=0;
  int fa7=0;
  double fij=0.;
  double fji=0.;
  const DoubleVect& transporteV = transporte;
  DoubleVect& resuV = resu;
// Faces internes
  for (elem=0; elem<nb_elem_tot; elem++)
    for (fa7=0; fa7<nfa7; fa7++)
      {
        facei_loc=KEL(0,fa7);
        facej_loc=KEL(1,fa7);
        facei=elem_faces(elem,facei_loc);
        facej=elem_faces(elem,facej_loc);
        for (dim=0; dim<nb_comp; dim++)
          {
            fij=Fij(elem,facei_loc,facej_loc,dim);
            fji=Fij(elem,facej_loc,facei_loc,dim);
            ligne=facei*nb_comp+dim;
            colonne=facej*nb_comp+dim;
            resuV[ligne]+=fij;
            resuV[colonne]+=fji;
          }
      }
  if (old_centered_)
    for (facei=premiere_face_int; facei<nb_faces; facei++)
      {
// Premier voisin
        elem=face_voisins(facei,0);
        facei_loc=num_fac_loc(facei,0);
        assert(elem_faces(elem,facei_loc)==facei);
        fij=Kij(elem,facei_loc,facei_loc);
// Deuxieme voisin
        elem=face_voisins(facei,1);
        facei_loc=num_fac_loc(facei,1);
        assert(elem_faces(elem,facei_loc)==facei);
        fij+=Kij(elem,facei_loc,facei_loc);
        for (dim=0; dim<nb_comp; dim++)
          {
            ligne=facei*nb_comp+dim;
            resuV[ligne]-=fij*transporteV[ligne];
          }
      }
// Faces de bord
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const int nb_bord = zone_Cl_VEF.nb_cond_lim();
  int n_bord=-1;
  int num1=0;
  int num2=0;
  int ind_face=-1;
  double psc=0.;
  for (n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces();
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Neumann_sortie_libre& la_sortie_libre = ref_cast(Neumann_sortie_libre, la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei=le_bord.num_face(ind_face);
              facei_loc=num_fac_loc(facei,0);
              elem=face_voisins(facei,0);
              assert(elem_faces(elem,facei_loc)==facei);
              psc=Kij(elem,facei_loc,facei_loc);//ATTENTION : SUPPOSE QU'ON EST a DIVERGENCE NULLE
              if (psc>=0.)
                {
// On ne fait rien car on en a deja tenu compte dans l'operateur centre
                }
              else
                for (dim=0; dim<nb_comp; dim++)
                  {
// On modifie car on a tenu compte dans l'operateur centre de psc*tansporteV[ligne]
                    ligne=facei*nb_comp+dim;
                    resuV[ligne]+=psc*(la_sortie_libre.val_ext(facei,dim)-transporteV[ligne]);
                  }
            }//fin du for sur "face_i"
        }//fin du if sur "Neumann"
    }//fin du for sur "n_bord"
// Retour du resultat
  return resu;
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Zone_VF::get_num_fac_loc(), Elem_VEF_base::KEL(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Elem_VEF::nb_facette(), Front_VF::num_face(), old_centered_, Zone_VF::premiere_face_int(), ref_cast, sub_type, Zone_VEF::type_elem(), Neumann_sortie_libre::val_ext(), Deriv_Cond_lim_base::valeur(), Deriv_Elem_VEF_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
Referenced by ajouter().
ajouter_partie_compressible()
DoubleTab & Op_Conv_Muscl_New_VEF_Face::ajouter_partie_compressible (const DoubleTab & transporte, DoubleTab & resu, const DoubleTab & vitesse) const private
Definition at line 1232 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
// const Zone_VEF& zone_VEF=la_zone_vef.valeur();
// const IntTab& elem_faces=zone_VEF.elem_faces();
// const IntTab& face_voisins = zone_VEF.face_voisins();
// const DoubleTab& face_normales=zone_VEF.face_normales();
// const int nb_elem_tot=zone_VEF.nb_elem_tot();
// const int nb_faces_elem=elem_faces.dimension(1);
// //Pour tenir compte de la porosite
// const int marq = phi_u_transportant(equation());
// const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// const DoubleVect& porosite_face = zone_VEF.porosite_face();
// DoubleTab vitesse(vitesse_.valeur().valeurs());
// for (int i=0; i<vitesse.dimension(0); i++)
// for (int j=0; j<vitesse.dimension(1); j++)
// vitesse(i,j)*=porosite_face(i);
// int nb_comp=1;
// if (transporte.nb_dim()!=1) nb_comp=transporte.dimension(1);
// int elem=0,type_elem=0;
// int facei=0,facei_loc=0;
// int ligne=0;
// int dim=0;
// double coeff=0.;
// double signe=0.;
// double div=0.;
// const DoubleVect& transporteV=ref_cast(DoubleVect,transporte);
// DoubleVect& resuV=ref_cast(DoubleVect,resu);
// double (*formule)(int);
// if (!volumes_etendus_)
// if (dimension==2) formule=&formule_Id_2D;
// else formule=&formule_Id_3D;
// else
// if (dimension==2) formule=&formule_2D;
// else formule=&formule_3D;
// for (elem=0; elem<nb_elem_tot; elem++)
// {
// //Type de l'element : le nombre de faces de Dirichlet
// //qu'il contient
// type_elem=elem_nb_faces_dirichlet_(elem);
// coeff=formule(type_elem);
// //Calcul de la divergence par element
// div=0.;
// for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
// {
// facei=elem_faces(elem,facei_loc);
// signe=(face_voisins(facei,0)==elem)? 1.:-1.;
// for (dim=0; dim<dimension; dim++)
// div+=signe*face_normales(facei,dim)*vitesse(facei,dim);
// }
// div*=coeff;
// if (!marq) div/=porosite_elem(elem);
// //Calcul de la partie compressible
// for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
// {
// facei=elem_faces(elem,facei_loc);
// for (dim=0; dim<nb_comp; dim++)
// {
// ligne=facei*nb_comp+dim;
// resuV[ligne]-=div*transporteV[ligne];
// }
// }
// }
  return resu;
}
calculer_coefficients_operateur_centre()
void Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre (DoubleTab & Kij, DoubleTab & Cij, DoubleTab & Sij, DoubleTab & Sij2, const int nb_comp, const DoubleTab & vitesse) const private
Definition at line 313 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const DoubleTab& facette_normales = zone_VEF.facette_normales();
  const DoubleTab& facette_normales_Cl = zone_Cl_VEF.normales_facettes_Cl();
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntVect& rang_elem_non_std = zone_VEF.rang_elem_non_std();
  const IntTab& KEL=zone_VEF.type_elem().valeur().KEL();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const int nb_faces_elem=elem_faces.dimension(1);
  const int nfa7 = zone_VEF.type_elem().nb_facette();
  const int nb_som_elem = zone_VEF.zone().nb_som_elem();
  const int marq = phi_u_transportant(equation());
  int rang=-2;
  int fa7=0;
  int dim=-1;
  int itypcl=-2;
  int elem=0;
  int facei_loc=-1;
  int facej_loc=-1;
  double psc=0.;
  double porosite=0.;
  ArrOfDouble vc(Objet_U::dimension);
  ArrOfDouble vs(Objet_U::dimension);
  DoubleTab vsom(nb_som_elem,Objet_U::dimension);
  ArrOfInt face(Objet_U::dimension+1);
  assert(Kij.nb_dim()==3);
  assert(Kij.dimension(0)==nb_elem_tot);
  assert(Kij.dimension(1)==Kij.dimension(2));
  assert(Kij.dimension(1)==nb_faces_elem);
  assert(Cij.nb_dim()==2);
  assert(Cij.dimension(0)==nb_elem_tot);
  assert(Cij.dimension(1)==nfa7);
  assert(Sij.nb_dim()==2);
  assert(Sij.dimension(0)==nb_elem_tot);
  assert(Sij.dimension(1)==nfa7);
  if (Objet_U::dimension==3)
    {
      assert(Sij2.nb_dim()==2);
      assert(Sij2.dimension(0)==nb_elem_tot);
      assert(Sij2.dimension(1)==nfa7);
    }
//
// Calcul des coefficients de l'operateur
//
  for(elem=0; elem<nb_elem_tot; elem++)
    {
      rang=rang_elem_non_std(elem);
      itypcl=(rang==-1)?0:zone_Cl_VEF.type_elem_Cl(rang);
      for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
        face[facei_loc]=elem_faces(elem,facei_loc);
      vs=0.;
      for (dim=0; dim<Objet_U::dimension; dim++)
        for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
          vs[dim]+=velocity(face[facei_loc],dim);
      vsom=0;
      for (dim=0; dim<Objet_U::dimension; dim++)
        for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
          vsom(facei_loc,dim)=vs[dim]-Objet_U::dimension*velocity(face[facei_loc],dim);
      vc=0.;
      zone_VEF.type_elem().valeur().calcul_vc(face,vc,vs,vsom,(*this).vitesse(),itypcl,porosite_face);
      if (marq==0)
        {
          porosite=1./porosite_elem(elem);
          vsom*=porosite;
          vs*=porosite;
          vc*=porosite;
        }
      if (Objet_U::dimension==2)
        {
          if (rang==-1)
            for (fa7=0; fa7<nfa7; fa7++)
              {
                facei_loc=KEL(0,fa7);
                facej_loc=KEL(1,fa7);
                Cij(elem,fa7)=0.;
                for (dim=0; dim<Objet_U::dimension; dim++)
                  Cij(elem,fa7)+=vc[dim]*facette_normales(elem,fa7,dim);
                Sij(elem,fa7)=0.;
                for (dim=0; dim<Objet_U::dimension; dim++)
                  Sij(elem,fa7)+=vsom(KEL(2,fa7),dim)*facette_normales(elem,fa7,dim);
                psc=Cij(elem,fa7)+Sij(elem,fa7);
                psc*=0.5;
                Kij(elem,facei_loc,facej_loc)=psc;
                Kij(elem,facei_loc,facei_loc)-=psc;//pour l'aspect LED
                Kij(elem,facej_loc,facei_loc)=-psc;
                Kij(elem,facej_loc,facej_loc)+=psc;//pour l'aspect LED
              }
          else //rang!=-1
            for (fa7=0; fa7<nfa7; fa7++)
              {
                facei_loc=KEL(0,fa7);
                facej_loc=KEL(1,fa7);
                Cij(elem,fa7)=0.;
                for (dim=0; dim<Objet_U::dimension; dim++)
                  Cij(elem,fa7)+=vc[dim]*facette_normales_Cl(rang,fa7,dim);
                Sij(elem,fa7)=0.;
                for (dim=0; dim<Objet_U::dimension; dim++)
                  Sij(elem,fa7)+=vsom(KEL(2,fa7),dim)*facette_normales_Cl(rang,fa7,dim);
                psc=Cij(elem,fa7)+Sij(elem,fa7);
                psc*=0.5;
                Kij(elem,facei_loc,facej_loc)=psc;
                Kij(elem,facei_loc,facei_loc)-=psc;//pour l'aspect LED
                Kij(elem,facej_loc,facei_loc)=-psc;
                Kij(elem,facej_loc,facej_loc)+=psc;//pour l'aspect LED
              }
        }//fin Objet_U::dimension==2
      else //Objet_U::dimension==3
        {
          if (rang==-1)
            for (fa7=0; fa7<nfa7; fa7++)
              {
                facei_loc=KEL(0,fa7);
                facej_loc=KEL(1,fa7);
                Cij(elem,fa7)=0.;
                for (dim=0; dim<Objet_U::dimension; dim++)
                  Cij(elem,fa7)+=vc[dim]*facette_normales(elem,fa7,dim);
                Sij(elem,fa7)=0.;
                for (dim=0; dim<Objet_U::dimension; dim++)
                  Sij(elem,fa7)+=vsom(KEL(2,fa7),dim)*facette_normales(elem,fa7,dim);
                Sij2(elem,fa7)=0.;
                for (dim=0; dim<Objet_U::dimension; dim++)
                  Sij2(elem,fa7)+=vsom(KEL(3,fa7),dim)*facette_normales(elem,fa7,dim);
                psc=Cij(elem,fa7)+Sij(elem,fa7)+Sij2(elem,fa7);
                psc/=3.;
                Kij(elem,facei_loc,facej_loc)=psc;
                Kij(elem,facei_loc,facei_loc)-=psc;//pour l'aspect LED
                Kij(elem,facej_loc,facei_loc)=-psc;
                Kij(elem,facej_loc,facej_loc)+=psc;//pour l'aspect LED
              }
          else //rang!=-1
            for (fa7=0; fa7<nfa7; fa7++)
              {
                facei_loc=KEL(0,fa7);
                facej_loc=KEL(1,fa7);
                Cij(elem,fa7)=0.;
                for (dim=0; dim<Objet_U::dimension; dim++)
                  Cij(elem,fa7)+=vc[dim]*facette_normales_Cl(rang,fa7,dim);
                Sij(elem,fa7)=0.;
                for (dim=0; dim<Objet_U::dimension; dim++)
                  Sij(elem,fa7)+=vsom(KEL(2,fa7),dim)*facette_normales_Cl(rang,fa7,dim);
                Sij2(elem,fa7)=0.;
                for (dim=0; dim<Objet_U::dimension; dim++)
                  Sij2(elem,fa7)+=vsom(KEL(3,fa7),dim)*facette_normales_Cl(rang,fa7,dim);
                psc=Cij(elem,fa7)+Sij(elem,fa7)+Sij2(elem,fa7);
                psc/=3.;
                Kij(elem,facei_loc,facej_loc)=psc;
                Kij(elem,facei_loc,facei_loc)-=psc;//pour l'aspect LED
                Kij(elem,facej_loc,facei_loc)=-psc;
                Kij(elem,facej_loc,facej_loc)+=psc;//pour l'aspect LED
              }
        }//fin Objet_U::dimension==3
    }
//
// Correction des Kij pour Dirichlet !
//
  {
    int nb_bord=zone_Cl_VEF.nb_cond_lim();
    for (int n_bord=0; n_bord<nb_bord; n_bord++)
      {
        const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
        if ( (sub_type(Dirichlet,la_cl.valeur()))
             || (sub_type(Dirichlet_homogene,la_cl.valeur()))
           )
          {
// On ne fait rien
          }//!< sub_type Dirichlet
        else if (sub_type(Neumann,la_cl.valeur()) || sub_type(Neumann_homogene,la_cl.valeur()))
          {
// On ne fait rien
          }//fin du if sur Neumann
        else if (sub_type(Symetrie,la_cl.valeur()))
          {
// On ne fait rien
          }//fin du if sur Symetrie
        else if (sub_type(Periodique,la_cl.valeur()))
          {
// On ne fait rien
          }//fin du if sur Periodique
        else if (sub_type(Echange_impose_base,la_cl.valeur()))
          {
// On ne fait rien
          }//fin du if sur Echange_impose_base
        else
          {
            if (Process::je_suis_maitre())
              {
                Cerr << "Erreur Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre()" << finl;
                Cerr << "Condition aux limites " << la_cl.que_suis_je() << " non codee."   << finl;
                Cerr << "Sortie du programme." << finl;
              }
            Process::exit();
          }//fin du else sur les autres conditions aux limites
      }//fin des conditions aux limites
  }
//
// Fin de la correction des Kij
//
}
References Elem_VEF_base::calcul_vc(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Process::exit(), Zone_VEF::facette_normales(), finl, Process::je_suis_maitre(), Elem_VEF_base::KEL(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Elem_VEF::nb_facette(), Zone::nb_som_elem(), Zone_Cl_VEF::normales_facettes_Cl(), Op_Conv_VEF_base::phi_u_transportant(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Objet_U::que_suis_je(), Zone_VEF::rang_elem_non_std(), sub_type, Zone_VEF::type_elem(), Zone_Cl_VEF::type_elem_Cl(), Deriv_Cond_lim_base::valeur(), Deriv_Elem_VEF_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter(), and calculer_dt_stab().
calculer_data_pour_dirichlet()
void Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet () private
Definition at line 2225 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const IntTab& face_sommets = zone_VEF.face_sommets();
  const IntVect& rang_elem_non_std = zone_VEF.rang_elem_non_std();
  const IntTab& elem_sommets = zone_VEF.zone().les_elems();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const int nb_bord = zone_Cl_VEF.nb_cond_lim();
  const int nb_som_faces = zone_VEF.nb_som_face();
  const int nb_som_elem = zone_VEF.zone().nb_som_elem();
  int som_loc=-1;
  int som=-1;
  int ind_face=-1;
  int elem=-1;
  int rang=-2;
// On rajoute un flag aux elements qui ont au moins un sommet qui appartient
// une face de Dirichlet ou Dirichlet_homogene
  if (old_centered_)
    {
      is_element_for_upwinding_.resize(nb_elem_tot);
      is_element_for_upwinding_=0;
      IntTab est_un_sommet_de_bord(zone_VEF.nb_som_tot());
      est_un_sommet_de_bord=0;
      for (int n_bord=0; n_bord<nb_bord; n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int nb_faces_tot=le_bord.nb_faces_tot();
          int face=-1;
          if ( (sub_type(Dirichlet,la_cl.valeur()))
               || (sub_type(Dirichlet_homogene,la_cl.valeur()))
             )
            for (ind_face=0; ind_face<nb_faces_tot; ind_face++)
              {
                face = le_bord.num_face(ind_face);
                for (som_loc=0; som_loc<nb_som_faces; som_loc++)
                  {
                    som=face_sommets(face,som_loc);
                    est_un_sommet_de_bord(som)=1;
                  }
              }
        }
      for (elem=0; elem<nb_elem_tot; elem++)
        {
          rang=rang_elem_non_std(elem);
          if (rang!=-1) is_element_for_upwinding_(elem)=1;
          else
            for (som_loc=0; som_loc<nb_som_elem; som_loc++)
              {
                som=elem_sommets(elem,som_loc);
                if (est_un_sommet_de_bord(som))
                  is_element_for_upwinding_(elem)=1;
              }
        }
    }
  is_dirichlet_faces_.resize(zone_VEF.nb_faces_tot());
  is_dirichlet_faces_=0;
  for (int n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_tot=le_bord.nb_faces_tot();
      int face=-1;
      if ( (sub_type(Dirichlet,la_cl.valeur()))
           || (sub_type(Dirichlet_homogene,la_cl.valeur()))
         )
        for (ind_face=0; ind_face<nb_faces_tot; ind_face++)
          {
            face = le_bord.num_face(ind_face);
            is_dirichlet_faces_(face)=1;
          }
    }
}
References Zone_VF::face_sommets(), Cond_lim::frontiere_dis(), is_dirichlet_faces_, is_element_for_upwinding_, Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Zone_Cl_dis_base::nb_cond_lim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Zone::nb_som_elem(), Zone_VF::nb_som_face(), Zone_dis_base::nb_som_tot(), Front_VF::num_face(), old_centered_, Zone_VEF::rang_elem_non_std(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by completer().
calculer_dt_stab()
double Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 1106 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  if (!facsec_auto_)
    return Op_Conv_VEF_Face::calculer_dt_stab();
  else
    {
      const Zone_VEF& zone_VEF = la_zone_vef.valeur();
      const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
      const Champ_P1NC& la_vitesse=ref_cast( Champ_P1NC, vitesse_.valeur());
      const DoubleTab& vitesse_2=la_vitesse.valeurs();
      const DoubleVect& porosite_face = zone_VEF.porosite_face();
      const IntTab& elem_faces = zone_VEF.elem_faces();
      const int marq=phi_u_transportant(equation());
      const int nb_faces_elem=elem_faces.dimension(1);
      const int nb_elem_tot = zone_VEF.nb_elem_tot();
      const int nfa7 = zone_VEF.type_elem().nb_facette();
      const int nb_faces_tot = zone_VEF.nb_faces_tot();
      const int nb_bord = zone_Cl_VEF.nb_cond_lim();
      int nb_comp=1;
      if(equation().inconnue().valeurs().nb_dim()!=1)
        nb_comp=equation().inconnue().valeurs().dimension(1);
      int elem=-1;
      int facei_loc=-1;
      int facei=-1;
      int faceiAss=-1;
      int facej_loc=-1;
      int facej=-1;
      int n_bord=-1;
      int num1=-1,num2=-1;
      int ind_face=-1;
      int ind_face_associee=-1;
      int max_int=-1;
      double dt_stab = Op_Conv_VEF_Face::calculer_dt_stab();
      double security_coeff=0.95;
      double dt_corrector=-1.;
      double kij=0.;
// soit on a transporte=phi*transporte_ et vitesse=vitesse_
// soit transporte=transporte_ et vitesse=phi*vitesse_
// cela depend si on transporte avec phi u ou avec u.
      DoubleTab vitesse_face_;
      const DoubleTab& velocity=modif_par_porosite_si_flag(vitesse_2,vitesse_face_,marq,porosite_face);
// statistiques().begin_count(m1);
      DoubleTab Kij(nb_elem_tot,nb_faces_elem,nb_faces_elem);
      DoubleTab Cij(nb_elem_tot,nfa7);
      DoubleTab Sij(nb_elem_tot,nfa7);
      DoubleTab Sij2;
      if (Objet_U::dimension==3)
        {
          Sij2.resize(nb_elem_tot,nfa7);
          Sij2=0.;
        }
      calculer_coefficients_operateur_centre(Kij,Cij,Sij,Sij2,nb_comp,velocity);
// Debut du calcul
      IntTab plus_tab(nb_faces_tot);
      for (elem=0; elem<nb_elem_tot; elem++)
        for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
          {
            facei=elem_faces(elem,facei_loc);
            for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
              {
                kij=Kij(elem,facei_loc,facej_loc);
                facej=elem_faces(elem,facej_loc);
                if (kij>=0.)
                  plus_tab(facei)+=1;
                else
                  plus_tab(facej)+=1;
              }
          }
      for (n_bord=0; n_bord<nb_bord; n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          num1=0;
          num2=le_bord.nb_faces_tot();
          if (sub_type(Periodique,la_cl.valeur()))
            {
              const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
              for (ind_face=num1; ind_face<num2; ind_face++)
                {
                  facei=le_bord.num_face(ind_face);
                  ind_face_associee=la_cl_perio.face_associee(ind_face);
                  faceiAss=le_bord.num_face(ind_face_associee);
                  if (facei<faceiAss)
                    {
                      plus_tab[faceiAss]+=plus_tab[facei];
                      plus_tab[facei]=plus_tab[faceiAss];
                    }
                }//fin du for sur "ind_face"
            }//fin du if sur "Periodique"
        }//fin du for sur "n_bord"
      max_int=plus_tab.mp_max_vect();
      max_int=(int)Process::mp_max(max_int);
      dt_corrector=1./(1+max_limiteur_*max_int);
      dt_corrector*=security_coeff;
      dt_stab*=dt_corrector;
      Op_Conv_VEF_base& op = ref_cast_non_const(Op_Conv_VEF_base,*this);
      op.fixer_dt_stab_conv(dt_stab);
      return dt_stab;
    }
}
References calculer_coefficients_operateur_centre(), Op_Conv_VEF_base::calculer_dt_stab(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), facsec_auto_, Operateur_Conv_base::fixer_dt_stab_conv(), Cond_lim::frontiere_dis(), Equation_base::inconnue(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), max_limiteur_, modif_par_porosite_si_flag(), Process::mp_max(), TRUSTVect< _TYPE_ >::mp_max_vect(), Zone_Cl_dis_base::nb_cond_lim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Elem_VEF::nb_facette(), Front_VF::num_face(), Op_Conv_VEF_base::phi_u_transportant(), Zone_VF::porosite_face(), ref_cast, ref_cast_non_const, TRUSTTab< _TYPE_ >::resize(), sub_type, Zone_VEF::type_elem(), Deriv_Cond_lim_base::valeur(), Ref_Champ_Inc_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc::valeurs(), Champ_Inc_base::valeurs(), and Op_Conv_VEF_base::vitesse_.
calculer_flux_bords()
void Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords (const DoubleTab & Kij, const DoubleTab & velocity, const DoubleTab & transporte) const private
Definition at line 1315 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const DoubleVect& transporteV = transporte;
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const int nb_bord = zone_Cl_VEF.nb_cond_lim();
  int nb_comp=1;
  if (transporte.nb_dim()!=1) nb_comp=transporte.dimension(1);
  int facei=0;
  int dim=0;
  int n_bord=0;
  int num1=0,num2=0;
  int ind_face=0;
  double psc=0.;
  for (n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2 = le_bord.nb_faces();//il ne faut boucler que sur les faces reelles ici
      if ( sub_type(Dirichlet_homogene,la_cl.valeur()) )
        {
// On ne calcule pas le flux aux bords de Dirichlet_homogene
        }//fin du if sur "Dirichlet"
      else if ( sub_type(Dirichlet,la_cl.valeur() ))
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei = le_bord.num_face(ind_face);
              psc=0.;
              for (dim=0; dim<dimension; dim++)
                psc-=velocity(facei,dim)*face_normales(facei,dim);
              for (dim=0; dim<nb_comp; dim++)
                flux_bords_(facei,dim)=psc*transporteV[facei*nb_comp+dim];
            }
        }
      else if ( ( sub_type(Neumann,la_cl.valeur()) &&
                  !( sub_type(Neumann_sortie_libre,la_cl.valeur())) )
                || sub_type(Neumann_homogene,la_cl.valeur())
                || sub_type(Symetrie,la_cl.valeur())
                || sub_type(Echange_impose_base,la_cl.valeur())
              )
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei = le_bord.num_face(ind_face);
              psc=0.;
              for (dim=0; dim<dimension; dim++)
                psc-=velocity(facei,dim)*face_normales(facei,dim);
              for (dim=0; dim<nb_comp; dim++)
                flux_bords_(facei,dim)=psc*transporteV[facei*nb_comp+dim];
            }
        }//fin du if sur "Neumann", "Neumann_homogene", "Symetrie", "Echange_impose_base"
      else if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Neumann_sortie_libre& la_sortie_libre = ref_cast(Neumann_sortie_libre, la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei = le_bord.num_face(ind_face);
              psc=0.;
              for (dim=0; dim<dimension; dim++)
                psc-=velocity(facei,dim)*face_normales(facei,dim);
              if (psc<0.)
                {
                  for (dim=0; dim<nb_comp; dim++)
                    {
                      flux_bords_(facei,dim) = psc*transporteV[facei*nb_comp+dim];
                    }
                }
              else
                {
                  if (nb_comp == 1)
                    {
                      flux_bords_(facei,0) = psc*la_sortie_libre.val_ext(ind_face);
                    }
                  else
                    {
                      for (dim=0; dim<nb_comp; dim++)
{
                          flux_bords_(facei,dim) = psc*la_sortie_libre.val_ext(ind_face,dim);
                        }
                    }
                }
            }
        }
      else if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique, la_cl.valeur());
          ArrOfInt fait(num2);
          fait = 0;
          int ind_face_voisine = -1;
          int facei_voisine    = -1;
          double flux             = 0.;
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              if (fait[ind_face] == 0)
                {
                  facei            = le_bord.num_face(ind_face);
                  ind_face_voisine = la_cl_perio.face_associee(ind_face);
                  facei_voisine    = le_bord.num_face(ind_face_voisine);
                  psc=0.;
                  for (dim=0; dim<dimension; dim++)
                    psc-=velocity(facei,dim)*face_normales(facei,dim);
                  for (dim=0; dim<nb_comp; dim++)
                    {
                      flux                           = psc*transporteV[facei*nb_comp+dim];
                      flux_bords_(facei,dim)         =  flux;
                      flux_bords_(facei_voisine,dim) = -flux;
                    }
                  fait[ind_face]         = 1;
                  fait[ind_face_voisine] = 1;
                }
            }
        }
      else
        {
          if (Process::je_suis_maitre())
            {
              Cerr << "Erreur Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords()" << finl;
              Cerr << "Condition aux limites " << la_cl.que_suis_je() << " non codee."   << finl;
              Cerr << "Sortie du programme." << finl;
            }
          Process::exit();
        }//fin du else sur les autres conditions aux limites
    }
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Process::exit(), Periodique::face_associee(), Zone_VEF::face_normales(), finl, Operateur_base::flux_bords_, Cond_lim::frontiere_dis(), Process::je_suis_maitre(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), TRUSTTab< _TYPE_ >::nb_dim(), Front_VF::nb_faces(), Front_VF::num_face(), Objet_U::que_suis_je(), ref_cast, sub_type, Neumann_sortie_libre::val_ext(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
Referenced by ajouter().
calculer_flux_operateur_centre()
void Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre (DoubleTab & Fij, const DoubleTab & Kij, const DoubleTab & Cij, const DoubleTab & Sij, const DoubleTab & Sij2, const int nb_comp, const DoubleTab & velocity, const DoubleTab & transporte) const private
< (du/dx du/dy dv/dx dv/dy) pour un poly gradient_elem=0.;
Definition at line 564 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Domaine& domaine = zone_VEF.zone().domaine();
  const DoubleTab& vecteur_face_facette = ref_cast_non_const(Zone_VEF,zone_VEF).vecteur_face_facette();
  const DoubleTab& vecteur_face_facette_Cl = zone_Cl_VEF.vecteur_face_facette_Cl();
  const DoubleTab& coord_sommets = domaine.coord_sommets();
  const DoubleTab& xv = zone_VEF.xv();
  const DoubleVect& transporteVect = transporte;
  const IntTab& elem_faces = zone_VEF.elem_faces();
// const IntTab& face_voisins = zone_VEF.face_voisins();
  const IntVect& rang_elem_non_std = zone_VEF.rang_elem_non_std();
  const IntTab& KEL=zone_VEF.type_elem().valeur().KEL();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const int nb_faces_elem=elem_faces.dimension(1);
  const int nfa7 = zone_VEF.type_elem().nb_facette();
  int rang=-2;
  int fa7=0;
  int dim=-1;
  int elem=0;
  int face_amont=-1;
  int dir=-1;
  int comp=-1;
  int s=-1;
  int s2=-1;
  int facei=-1;
  int facej=-1;
  int facei_loc=-1;
  int facej_loc=-1;
  double inco_m=0.;
  double inco_s=0.;
  double inco_s2=0.;
  double inco_c=0.;
  double flux=0.;
  DoubleTab gradient_elem(nb_elem_tot,nb_comp,Objet_U::dimension);  //!< (du/dx du/dy dv/dx dv/dy) pour un poly  gradient_elem=0.;
  IntTab face(Objet_U::dimension+1);
  assert(Fij.nb_dim()==4);
  assert(Fij.dimension(0)==nb_elem_tot);
  assert(Fij.dimension(1)==Fij.dimension(2));
  assert(Fij.dimension(1)==nb_faces_elem);
  assert(Fij.dimension(3)==nb_comp);
//
// Calcul des flux de l'operateur
//
  Champ_P1NC::calcul_gradient(transporte,gradient_elem,zone_Cl_VEF);
  for(elem=0; elem<nb_elem_tot; elem++)
    {
      rang=rang_elem_non_std(elem);
      for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
        face(facei_loc)=elem_faces(elem,facei_loc);
      if (Objet_U::dimension==2)
        {
          if (rang==-1)
            for (fa7=0; fa7<nfa7; fa7++)
              {
                facei_loc=KEL(0,fa7);
                facej_loc=KEL(1,fa7);
                facei=face(facei_loc);
                facej=face(facej_loc);
// REMARQUE : ON N'OUBLIE PAS QUE LES NORMALES FA7 SONT ORIENTeES DE FACE_LOCI VERS FACE_LOCJ PAR DEFAUT
// LES PRODUITS SCALAIRES PSC_M, PSC_C, PSC_S SONT DONC CALCULeS POUR OBTENIR LE FLUX REcU PAR LA FACE FACE_LOCI
// ET EMIS PAR LA FACE_LOCJ
// SI L'ON VEUT OBTENIR LE FLUX REcU PAR LA FACE FACE_LOCJ ET EMIS PAR LA FACE_LOCI, IL FAUT MULTIPLIER LES
// PRODUITS SCALAIRES PSC_M, PSC_C, PSC_S PAR -1 POUR IMPLICITEMENT ReORIENTER LES NORMALES FA7 DE FACE_LOCJ VERS
// FACE_LOCI
// MEME REMARQUE POUR LE SCALAIRE "FLUX"
                const double psc_m = Kij(elem,facei_loc,facej_loc);
                const double psc_c = Cij(elem,fa7);
                const double psc_s = Sij(elem,fa7);
                if (psc_m>=0.)
                  face_amont=facei,dir=0;
                else
                  face_amont=facej,dir=1;
                s=zone_VEF.zone().sommet_elem(elem,KEL(2,fa7));
                for (comp=0; comp<nb_comp; comp++)
                  {
// Calcul de la valeur de l'inconnue aux points d'integration de la formule de Simspon
                    inco_m=transporteVect[face_amont*nb_comp+comp];
                    for(dim=0; dim<Objet_U::dimension; dim++)
                      inco_m+=gradient_elem(elem,comp,dim)*vecteur_face_facette(elem,fa7,dim,dir);
                    inco_s=transporteVect[face_amont*nb_comp+comp];
                    for(dim=0; dim<Objet_U::dimension; dim++)
                      inco_s+=gradient_elem(elem,comp,dim)*(coord_sommets(s,dim)-xv(face_amont,dim));
                    inco_c=2.*inco_m-inco_s;
// Calcul du flux final : formule d'integration de Simpson
                    flux=inco_c*psc_c;
                    flux+=4*inco_m*psc_m;
                    flux+=inco_s*psc_s;
                    flux/=6.;
// Fij(elem,facei_loc,facej_loc,comp) est le flux recu par la facei_loc dans elem
// envoye par la face facej_loc dans elem pour la composante comp de l'inconnue
                    Fij(elem,facei_loc,facej_loc,comp)=flux-psc_m*transporteVect[facei*nb_comp+comp];
                    Fij(elem,facej_loc,facei_loc,comp)=psc_m*transporteVect[facej*nb_comp+comp]-flux;
                  }
              }
          else //rang!=-1
            for (fa7=0; fa7<nfa7; fa7++)
              {
                facei_loc=KEL(0,fa7);
                facej_loc=KEL(1,fa7);
                facei=face(facei_loc);
                facej=face(facej_loc);
// REMARQUE : ON N'OUBLIE PAS QUE LES NORMALES FA7 SONT ORIENTeES DE FACE_LOCI VERS FACE_LOCJ PAR DEFAUT
// LES PRODUITS SCALAIRES PSC_M, PSC_C, PSC_S SONT DONC CALCULeS POUR OBTENIR LE FLUX REcU PAR LA FACE FACE_LOCI
// ET EMIS PAR LA FACE_LOCJ
// SI L'ON VEUT OBTENIR LE FLUX REcU PAR LA FACE FACE_LOCJ ET EMIS PAR LA FACE_LOCI, IL FAUT MULTIPLIER LES
// PRODUITS SCALAIRES PSC_M, PSC_C, PSC_S PAR -1 POUR IMPLICITEMENT ReORIENTER LES NORMALES FA7 DE FACE_LOCJ VERS
// FACE_LOCI
// MEME REMARQUE POUR LE SCALAIRE "FLUX"
                const double psc_m = Kij(elem,facei_loc,facej_loc);
                const double psc_c = Cij(elem,fa7);
                const double psc_s = Sij(elem,fa7);
                if (psc_m>=0.)
                  face_amont=facei,dir=0;
                else
                  face_amont=facej,dir=1;
                s=zone_VEF.zone().sommet_elem(elem,KEL(2,fa7));
                for (comp=0; comp<nb_comp; comp++)
                  {
// Calcul de la valeur de l'inconnue aux points d'integration de la formule de Simspon
                    inco_m=transporteVect[face_amont*nb_comp+comp];
                    for(dim=0; dim<Objet_U::dimension; dim++)
                      inco_m+=gradient_elem(elem,comp,dim)*vecteur_face_facette_Cl(rang,fa7,dim,dir);
                    inco_s=transporteVect[face_amont*nb_comp+comp];
                    for(dim=0; dim<Objet_U::dimension; dim++)
                      inco_s+=gradient_elem(elem,comp,dim)*(coord_sommets(s,dim)-xv(face_amont,dim));
                    inco_c=2.*inco_m-inco_s;
// Calcul du flux final : formule d'integration de Simpson
                    flux=inco_c*psc_c;
                    flux+=4*inco_m*psc_m;
                    flux+=inco_s*psc_s;
                    flux/=6.;
// Fij(elem,facei_loc,facej_loc,comp) est le flux recu par la facei_loc dans elem
// envoye par la face facej_loc dans elem pour la composante comp de l'inconnue
                    Fij(elem,facei_loc,facej_loc,comp)=flux-psc_m*transporteVect[facei*nb_comp+comp];
                    Fij(elem,facej_loc,facei_loc,comp)=psc_m*transporteVect[facej*nb_comp+comp]-flux;
                  }
              }
        }//fin Objet_U::dimension==2
      else //Objet_U::dimension==3
        {
          if (rang==-1)
            for (fa7=0; fa7<nfa7; fa7++)
              {
                facei_loc=KEL(0,fa7);
                facej_loc=KEL(1,fa7);
                facei=face(facei_loc);
                facej=face(facej_loc);
// REMARQUE : ON N'OUBLIE PAS QUE LES NORMALES FA7 SONT ORIENTeES DE FACE_LOCI VERS FACE_LOCJ PAR DEFAUT
// LES PRODUITS SCALAIRES PSC_M, PSC_C, PSC_S, PSC_S2 SONT DONC CALCULeS POUR OBTENIR LE FLUX REcU PAR LA FACE FACE_LOCI
// ET EMIS PAR LA FACE_LOCJ
// SI L'ON VEUT OBTENIR LE FLUX REcU PAR LA FACE FACE_LOCJ ET EMIS PAR LA FACE_LOCI, IL FAUT MULTIPLIER LES
// PRODUITS SCALAIRES PSC_M, PSC_C, PSC_S, PSC_S2 PAR -1 POUR IMPLICITEMENT ReORIENTER LES NORMALES FA7 DE FACE_LOCJ VERS
// FACE_LOCI
// MEME REMARQUE POUR LE SCALAIRE "FLUX"
                const double psc_c = Cij(elem,fa7);
                const double psc_s = Sij(elem,fa7);
                const double psc_s2 = Sij2(elem,fa7);
                const double psc_m = Kij(elem,facei_loc,facej_loc);
                if (psc_m>=0.)
                  face_amont=facei,dir=0;
                else
                  face_amont=facej,dir=1;
                s=zone_VEF.zone().sommet_elem(elem,KEL(2,fa7));
                s2=zone_VEF.zone().sommet_elem(elem,KEL(3,fa7));
                for (comp=0; comp<nb_comp; comp++)
                  {
// Calcul de la valeur de l'inconnue aux points d'integration de la formule 3D
                    inco_m=transporteVect[face_amont*nb_comp+comp];
                    for(dim=0; dim<Objet_U::dimension; dim++)
                      inco_m+=gradient_elem(elem,comp,dim)*vecteur_face_facette(elem,fa7,dim,dir);
                    inco_s=transporteVect[face_amont*nb_comp+comp];
                    for(dim=0; dim<Objet_U::dimension; dim++)
                      inco_s+=gradient_elem(elem,comp,dim)*(coord_sommets(s,dim)-xv(face_amont,dim));
                    inco_s2=transporteVect[face_amont*nb_comp+comp];
                    for(dim=0; dim<Objet_U::dimension; dim++)
                      inco_s2+=gradient_elem(elem,comp,dim)*(coord_sommets(s2,dim)-xv(face_amont,dim));
                    inco_c=3.*inco_m-inco_s-inco_s2;
// Calcul du flux final : formule d'integration 3D exacte pour les polynomes de degre 2
                    flux=(inco_s+inco_s2)*(psc_s+psc_s2);
                    flux+=(inco_s+inco_c)*(psc_s+psc_c);
                    flux+=(inco_s2+inco_c)*(psc_s2+psc_c);
                    flux/=12.;
// Fij(elem,facei_loc,facej_loc,comp) est le flux recu par la facei_loc dans elem
// envoye par la face facej_loc dans elem pour la composante comp de l'inconnue
                    Fij(elem,facei_loc,facej_loc,comp)=flux-psc_m*transporteVect[facei*nb_comp+comp];
                    Fij(elem,facej_loc,facei_loc,comp)=psc_m*transporteVect[facej*nb_comp+comp]-flux;
                  }
              }
          else //rang!=-1
            for (fa7=0; fa7<nfa7; fa7++)
              {
                facei_loc=KEL(0,fa7);
                facej_loc=KEL(1,fa7);
                facei=face(facei_loc);
                facej=face(facej_loc);
// REMARQUE : ON N'OUBLIE PAS QUE LES NORMALES FA7 SONT ORIENTeES DE FACE_LOCI VERS FACE_LOCJ PAR DEFAUT
// LES PRODUITS SCALAIRES PSC_M, PSC_C, PSC_S, PSC_S2 SONT DONC CALCULeS POUR OBTENIR LE FLUX REcU PAR LA FACE FACE_LOCI
// ET EMIS PAR LA FACE_LOCJ
// SI L'ON VEUT OBTENIR LE FLUX REcU PAR LA FACE FACE_LOCJ ET EMIS PAR LA FACE_LOCI, IL FAUT MULTIPLIER LES
// PRODUITS SCALAIRES PSC_M, PSC_C, PSC_S, PSC_S2 PAR -1 POUR IMPLICITEMENT ReORIENTER LES NORMALES FA7 DE FACE_LOCJ VERS
// FACE_LOCI
// MEME REMARQUE POUR LE SCALAIRE "FLUX"
                const double psc_c = Cij(elem,fa7);
                const double psc_s = Sij(elem,fa7);
                const double psc_s2 = Sij2(elem,fa7);
                const double psc_m = Kij(elem,facei_loc,facej_loc);
                if (psc_m>=0.)
                  face_amont=facei,dir=0;
                else
                  face_amont=facej,dir=1;
                s=zone_VEF.zone().sommet_elem(elem,KEL(2,fa7));
                s2=zone_VEF.zone().sommet_elem(elem,KEL(3,fa7));
                for (comp=0; comp<nb_comp; comp++)
                  {
// Calcul de la valeur de l'inconnue aux points d'integration de la formule 3D
                    inco_m=transporteVect[face_amont*nb_comp+comp];
                    for(dim=0; dim<Objet_U::dimension; dim++)
                      inco_m+=gradient_elem(elem,comp,dim)*vecteur_face_facette_Cl(rang,fa7,dim,dir);
                    inco_s=transporteVect[face_amont*nb_comp+comp];
                    for(dim=0; dim<Objet_U::dimension; dim++)
                      inco_s+=gradient_elem(elem,comp,dim)*(coord_sommets(s,dim)-xv(face_amont,dim));
                    inco_s2=transporteVect[face_amont*nb_comp+comp];
                    for(dim=0; dim<Objet_U::dimension; dim++)
                      inco_s2+=gradient_elem(elem,comp,dim)*(coord_sommets(s2,dim)-xv(face_amont,dim));
                    inco_c=3.*inco_m-inco_s-inco_s2;
// Calcul du flux final : formule d'integration 3D exacte pour les polynomes de degre 2
                    flux=(inco_s+inco_s2)*(psc_s+psc_s2);
                    flux+=(inco_s+inco_c)*(psc_s+psc_c);
                    flux+=(inco_s2+inco_c)*(psc_s2+psc_c);
                    flux/=12.;
// Fij(elem,facei_loc,facej_loc,comp) est le flux recu par la facei_loc dans elem
// envoye par la face facej_loc dans elem pour la composante comp de l'inconnue
                    Fij(elem,facei_loc,facej_loc,comp)=flux-psc_m*transporteVect[facei*nb_comp+comp];
                    Fij(elem,facej_loc,facei_loc,comp)=psc_m*transporteVect[facej*nb_comp+comp]-flux;
                  }
              }
        }//fin Objet_U::dimension==3
    }
}
References Champ_P1NC::calcul_gradient(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Zone_VF::elem_faces(), Elem_VEF_base::KEL(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Elem_VEF::nb_facette(), Zone_VEF::rang_elem_non_std(), ref_cast_non_const, Zone::sommet_elem(), Zone_VEF::type_elem(), Deriv_Elem_VEF_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Zone_Cl_VEF::vecteur_face_facette_Cl(), Zone_VF::xv(), and Zone_dis_base::zone().
Referenced by ajouter().
calculer_senseur_v1()
void Op_Conv_Muscl_New_VEF_Face::calculer_senseur_v1 (const DoubleTab & Kij, const DoubleTab & Fij, const DoubleVect & transporteV, const int nb_comp, const int face_i, const IntTab & elem_faces, const IntTab & face_voisins, const IntTab & num_fac_loc, ArrOfDouble & P_plus, ArrOfDouble & P_moins, ArrOfDouble & Q_plus, ArrOfDouble & Q_moins) const inline private
Definition at line 2042 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  assert(P_plus.size_array()==nb_comp);
  assert(Q_plus.size_array()==nb_comp);
  assert(P_moins.size_array()==nb_comp);
  assert(Q_moins.size_array()==nb_comp);
  double inci=0.;
  double inck=0.;
  const int nb_faces_elem=elem_faces.dimension(1);
  for (int elem_voisin=0; elem_voisin<2; elem_voisin++)
    {
      int elem = face_voisins(face_i,elem_voisin);
      if (elem!=-1)
        {
          int face_i_loc = num_fac_loc(face_i,elem_voisin);
          assert(face_i_loc>=0);
          assert(face_i_loc<nb_faces_elem);
// On travaille sur les faces de "elem"
          for (int face_k_loc=0; face_k_loc<nb_faces_elem; face_k_loc++)
            {
              int face_k=elem_faces(elem,face_k_loc);
              double kik=Kij(elem,face_i_loc,face_k_loc);
//
// Calcul des variables intermediaires
//
              for (int dim=0; dim<nb_comp; dim++)
                {
                  inci=transporteV[face_i*nb_comp+dim];
                  inck=transporteV[face_k*nb_comp+dim];
                  double fik_low=kik*(inck-inci);
                  double fik_high=Fij(elem,face_i_loc,face_k_loc,dim);
// Codage optimise:
                  if (kik<0)
                    {
                      if (fik_low>0) Q_plus[dim]+=fik_low;
                      else       Q_moins[dim]+=fik_low;
                    }
                  else
                    {
                      if (fik_high>0) P_plus[dim]+=fik_high;
                      else       P_moins[dim]+=fik_high;
                    }
                  assert(P_plus[dim]>=0);
                  assert(Q_plus[dim]>=0);
                  assert(P_moins[dim]<=0);
                  assert(Q_moins[dim]<=0);
                }//fin du for sur "dim"
//
// Fin du calcul des variables intermediaires
//
            }//fin du for sur "face_k_loc"
        }//fin du if sur "elem!=-1"
    }//fin du for sur "elem_voisin"
}
References TRUSTTab< _TYPE_ >::dimension(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by ajouter_antidiffusion_v1(), and calculer_senseur_v2().
calculer_senseur_v2()
void Op_Conv_Muscl_New_VEF_Face::calculer_senseur_v2 (const DoubleTab & Kij, const DoubleTab & Fij, const DoubleVect & transporteV, const int nb_comp, const int face_i, const IntTab & elem_faces, const IntTab & face_voisins, const IntTab & num_fac_loc, ArrOfDouble & P_plus, ArrOfDouble & P_moins, ArrOfDouble & Q_plus, ArrOfDouble & Q_moins) const inline private
Definition at line 1983 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  calculer_senseur_v1(Kij,Fij,transporteV,nb_comp,face_i,elem_faces,face_voisins,num_fac_loc,P_plus,P_moins,Q_plus,Q_moins);
// assert(P_plus.size_array()==nb_comp);
// assert(Q_plus.size_array()==nb_comp);
// assert(P_moins.size_array()==nb_comp);
// assert(Q_moins.size_array()==nb_comp);
// const int nb_faces_elem=elem_faces.dimension(1);
// for (int elem_voisin=0; elem_voisin<2; elem_voisin++)
// {
// int elem = face_voisins(face_i,elem_voisin);
// if (elem!=-1)
// {
// int face_i_loc = num_fac_loc(face_i,elem_voisin);
// assert(face_i_loc>=0);
// assert(face_i_loc<nb_faces_elem);
// //On travaille sur les faces de "elem"
// for (int face_k_loc=0; face_k_loc<nb_faces_elem; face_k_loc++)
// {
// double kik=Kij(elem,face_i_loc,face_k_loc);
// //
// //Calcul des variables intermediaires
// //
// for (int dim=0; dim<nb_comp; dim++)
// {
// double fik=Fij(elem,face_i_loc,face_k_loc,dim);
// // Codage optimise:
// if (kik<0)
// {
// if (fik>0) Q_plus(dim)+=fik;
// else       Q_moins(dim)+=fik;
// }
// else
// {
// if (fik>0) P_plus(dim)+=fik;
// else       P_moins(dim)+=fik;
// }
// assert(P_plus(dim)>=0);
// assert(Q_plus(dim)>=0);
// assert(P_moins(dim)<=0);
// assert(Q_moins(dim)<=0);
// }//fin du for sur "dim"
// //
// //Fin du calcul des variables intermediaires
// //
// }//fin du for sur "face_k_loc"
// }//fin du if sur "elem!=-1"
// }//fin du for sur "elem_voisin"
}
References calculer_senseur_v1().
Referenced by ajouter_antidiffusion_v2().
completer()
void Op_Conv_Muscl_New_VEF_Face::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Definition at line 2310 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  Op_Conv_VEF_Face::completer();
  calculer_data_pour_dirichlet();
// int nb_comp=1;
// if (equation().inconnue().valeurs().nb_dim()>1)
// nb_comp=equation().inconnue().valeurs().dimension(1);
// limiteurs_.resize(la_zone_vef->nb_faces_tot(),nb_comp);
// limiteurs_=0.;
  alpha_tab.resize_array(la_zone_vef->nb_faces_tot());
  alpha_tab = alpha_;
  beta.resize_array(la_zone_vef->nb_faces_tot());
  beta=1.;
// if (sous_zone) {
// sous_zone=false;
// const Sous_Zone& la_sous_zone=equation().probleme().domaine().ss_zone(nom_sous_zone);
// const Domaine_dis& le_domaine_dis=la_zone_vef->domaine_dis();
// for (int ssz=0;ssz<le_domaine_dis.nombre_de_sous_zones_dis();ssz++) {
// if (le_domaine_dis.sous_zone_dis(ssz)->sous_zone().est_egal_a(la_sous_zone)) {
// sous_zone=true;
// la_sous_zone_dis=ref_cast(Sous_zone_VF,le_domaine_dis.sous_zone_dis(ssz).valeur());
// }
// }
// if(!sous_zone) {
// Cerr << "On ne trouve pas la sous_zone discretisee associee a " << nom_sous_zone << finl;
// Process::exit();
// }
// const Sous_zone_VF& ssz=la_sous_zone_dis.valeur();
// int nb_faces = ssz.les_faces().size();
// for (int face=0;face<nb_faces;face++) {
// int la_face=ssz.les_faces()[face];
// beta(la_face) = 0.;
// alpha_tab(la_face) = 1.;
// }
// }
}
References alpha_, alpha_tab, beta, calculer_data_pour_dirichlet(), Operateur_base::completer(), Op_Conv_VEF_base::la_zone_vef, Zone_VF::nb_faces_tot(), and TRUSTArray< _TYPE_ >::resize_array().
contribuer_a_avec()
void Op_Conv_Muscl_New_VEF_Face::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 128 of file Op_Conv_Muscl_New_VEF_Face.h.
{
  ajouter_contribution(inco, matrice);
}
References ajouter_contribution().
cree_instance()
Objet_U * Op_Conv_Muscl_New_VEF_Face::cree_instance () static
Definition at line 73 of file Op_Conv_Muscl_New_VEF_Face.cpp.
duplique()
int Op_Conv_Muscl_New_VEF_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 73 of file Op_Conv_Muscl_New_VEF_Face.cpp.
get_info()
const Type_info * Op_Conv_Muscl_New_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Conv_base.
Definition at line 73 of file Op_Conv_Muscl_New_VEF_Face.cpp.
info()
const Type_info * Op_Conv_Muscl_New_VEF_Face::info () static
Definition at line 73 of file Op_Conv_Muscl_New_VEF_Face.cpp.
is_compressible()
int Op_Conv_Muscl_New_VEF_Face::is_compressible () const inline
Definition at line 134 of file Op_Conv_Muscl_New_VEF_Face.h.
{
  return 1;/* is_compressible_; */
}
mettre_a_jour_pour_periodicite()
void Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite (const DoubleTab & Kij, const DoubleTab & transporte, DoubleTab & resu) const private
Definition at line 2127 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const int nb_bord = zone_Cl_VEF.nb_cond_lim();
  const int nb_comp = (resu.nb_dim()==1) ? 1 : resu.dimension(1);
  const DoubleVect& transporteV = transporte;
  DoubleVect& resuV = resu;
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const IntTab& num_fac_loc = zone_VEF.get_num_fac_loc();
  int ligne=0,ligneAss=0;
  int facei=0,faceiAss=0;
  int ind_face=0;
  int num1=0,num2=0;
  int ind_face_associee=0;
  int dim=0;
  int elem=-1;
  int facei_loc=-1;
  double kii=0.;
  double tmp=0.;
// Faces de bord
  for (int n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei=le_bord.num_face(ind_face);
              ind_face_associee=la_cl_perio.face_associee(ind_face);
              faceiAss=le_bord.num_face(ind_face_associee);
              if (facei<faceiAss)
                for (dim=0; dim<nb_comp; dim++)
                  {
                    ligne=facei*nb_comp+dim;
                    ligneAss=faceiAss*nb_comp+dim;
                    resuV[ligneAss]+=resuV[ligne];
                    resuV[ligne]=resuV[ligneAss];
                  }
              if (old_centered_)
                {
// Pour le 1er element voisin
                  elem=face_voisins(facei,0);
                  facei_loc=-1;
                  facei_loc=num_fac_loc(facei,0);
                  assert(facei_loc!=-1);
                  kii=Kij(elem,facei_loc,facei_loc);
// Pour le 2eme element voisin
                  elem=face_voisins(facei,1);
                  facei_loc=-1;
                  facei_loc=num_fac_loc(facei,1);
                  assert(facei_loc!=-1);
                  kii+=Kij(elem,facei_loc,facei_loc);
                  for (dim=0; dim<nb_comp; dim++)
                    {
                      ligne=facei*nb_comp+dim;
                      ligneAss=faceiAss*nb_comp+dim;
                      tmp=kii*transporteV[ligneAss];
                      resuV[ligneAss]-=tmp;
                      resuV[ligne]-=tmp;
                    }
                }
            }//fin du for sur "face_i"
        }//fin du if sur "Periodique"
    }//fin du for sur "n_bord"
}
References TRUSTTab< _TYPE_ >::dimension(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Zone_VF::get_num_fac_loc(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), TRUSTTab< _TYPE_ >::nb_dim(), Front_VF::nb_faces(), Front_VF::num_face(), old_centered_, ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
Referenced by ajouter().
modifier_flux_operateur_centre()
void Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre (DoubleTab & Fij, const DoubleTab & Kij, const DoubleTab & Cij, const DoubleTab & Sij, const DoubleTab & Sij2, const int nb_comp, const DoubleTab & velocity, const DoubleTab & transporte) const private
< (du/dx du/dy dv/dx dv/dy) pour un poly gradient_elem=0.;
Definition at line 857 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const DoubleTab& vecteur_face_facette = ref_cast_non_const(Zone_VEF,zone_VEF).vecteur_face_facette();
  const DoubleTab& vecteur_face_facette_Cl = zone_Cl_VEF.vecteur_face_facette_Cl();
  const DoubleVect& transporteVect = transporte;
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntVect& rang_elem_non_std = zone_VEF.rang_elem_non_std();
  const IntTab& KEL=zone_VEF.type_elem().valeur().KEL();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const int nb_faces_elem=elem_faces.dimension(1);
  const int nfa7 = zone_VEF.type_elem().nb_facette();
  int rang=-2;
  int fa7=0;
  int dim=-1;
  int elem=0;
  int face_amont=-1;
  int dir=-1;
  int comp=-1;
  int facei=-1;
  int facej=-1;
  int facei_loc=-1;
  int facej_loc=-1;
  double inco_m=0.;
  double flux=0.;
  DoubleTab gradient_elem(nb_elem_tot,nb_comp,Objet_U::dimension);  //!< (du/dx du/dy dv/dx dv/dy) pour un poly  gradient_elem=0.;
  IntTab face(Objet_U::dimension+1);
  assert(Fij.nb_dim()==4);
  assert(Fij.dimension(0)==nb_elem_tot);
  assert(Fij.dimension(1)==Fij.dimension(2));
  assert(Fij.dimension(1)==nb_faces_elem);
  assert(Fij.dimension(3)==nb_comp);
//
// Calcul des flux de l'operateur
//
  Champ_P1NC::calcul_gradient(transporte,gradient_elem,zone_Cl_VEF);
  for(elem=0; elem<nb_elem_tot; elem++)
    {
      rang=rang_elem_non_std(elem);
      for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
        face(facei_loc)=elem_faces(elem,facei_loc);
// RAZ des flux des elements a modifier
      if (is_element_for_upwinding_(elem))
        for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
          for (facej_loc=0; facej_loc<nb_faces_elem; facej_loc++)
            for (comp=0; comp<nb_comp; comp++)
              Fij(elem,facei_loc,facej_loc,comp)=0.;
      if (is_element_for_upwinding_(elem))
        {
          if (rang==-1)
            for (fa7=0; fa7<nfa7; fa7++)
              {
                facei_loc=KEL(0,fa7);
                facej_loc=KEL(1,fa7);
                facei=face(facei_loc);
                facej=face(facej_loc);
// REMARQUE : ON N'OUBLIE PAS QUE LES NORMALES FA7 SONT ORIENTeES DE FACE_LOCI VERS FACE_LOCJ PAR DEFAUT
// LE PRODUIT SCALAIRE PSC_M EST DONC CALCULe POUR OBTENIR LE FLUX REcU PAR LA FACE FACE_LOCI
// ET EMIS PAR LA FACE_LOCJ
// SI L'ON VEUT OBTENIR LE FLUX REcU PAR LA FACE FACE_LOCJ ET EMIS PAR LA FACE_LOCI, IL FAUT MULTIPLIER LE
// PRODUIT SCALAIRE PSC_M PAR -1 POUR IMPLICITEMENT ReORIENTER LES NORMALES FA7 DE FACE_LOCJ VERS
// FACE_LOCI
// MEME REMARQUE POUR LE SCALAIRE "FLUX"
                const double psc_m = Kij(elem,facei_loc,facej_loc);
                if (psc_m>=0.)
                  face_amont=facei,dir=0;
                else
                  face_amont=facej,dir=1;
                for (comp=0; comp<nb_comp; comp++)
                  {
// Calcul de la valeur de l'inconnue aux points d'integration de la formule du point milieu
                    inco_m=transporteVect[face_amont*nb_comp+comp];
                    for(dim=0; dim<Objet_U::dimension; dim++)
                      inco_m+=gradient_elem(elem,comp,dim)*vecteur_face_facette(elem,fa7,dim,dir);
// Calcul du flux final : formule du point milieu
                    flux=inco_m*psc_m;
// Fij(elem,facei_loc,facej_loc,comp) est le flux recu par la facei_loc dans elem
// envoye par la face facej_loc dans elem pour la composante comp de l'inconnue
                    Fij(elem,facei_loc,facej_loc,comp)=flux-psc_m*transporteVect[facei*nb_comp+comp];
                    Fij(elem,facej_loc,facei_loc,comp)=psc_m*transporteVect[facej*nb_comp+comp]-flux;
                  }
              }
        }
      else //rang!=-1
        {
          for (fa7=0; fa7<nfa7; fa7++)
            {
              facei_loc=KEL(0,fa7);
              facej_loc=KEL(1,fa7);
              facei=face(facei_loc);
              facej=face(facej_loc);
// REMARQUE : ON N'OUBLIE PAS QUE LES NORMALES FA7 SONT ORIENTeES DE FACE_LOCI VERS FACE_LOCJ PAR DEFAUT
// LE PRODUIT SCALAIRE PSC_M EST DONC CALCULe POUR OBTENIR LE FLUX REcU PAR LA FACE FACE_LOCI
// ET EMIS PAR LA FACE_LOCJ
// SI L'ON VEUT OBTENIR LE FLUX REcU PAR LA FACE FACE_LOCJ ET EMIS PAR LA FACE_LOCI, IL FAUT MULTIPLIER LE
// PRODUIT SCALAIRE PSC_M PAR -1 POUR IMPLICITEMENT ReORIENTER LES NORMALES FA7 DE FACE_LOCJ VERS
// FACE_LOCI
// MEME REMARQUE POUR LE SCALAIRE "FLUX"
              const double psc_m = Kij(elem,facei_loc,facej_loc);
              if (psc_m>=0.)
                face_amont=facei,dir=0;
              else
                face_amont=facej,dir=1;
              for (comp=0; comp<nb_comp; comp++)
                {
// Calcul de la valeur de l'inconnue aux points d'integration de la formule du point milieu
                  inco_m=transporteVect[face_amont*nb_comp+comp];
                  for(dim=0; dim<Objet_U::dimension; dim++)
                    inco_m+=gradient_elem(elem,comp,dim)*vecteur_face_facette_Cl(rang,fa7,dim,dir);
// Calcul du flux final : formule d'integration du point milieu
                  flux=inco_m*psc_m;
// Fij(elem,facei_loc,facej_loc,comp) est le flux recu par la facei_loc dans elem
// envoye par la face facej_loc dans elem pour la composante comp de l'inconnue
                  Fij(elem,facei_loc,facej_loc,comp)=flux-psc_m*transporteVect[facei*nb_comp+comp];
                  Fij(elem,facej_loc,facei_loc,comp)=psc_m*transporteVect[facej*nb_comp+comp]-flux;
                }
            }
        }
    }//for sur elem
}
References Champ_P1NC::calcul_gradient(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), is_element_for_upwinding_, Elem_VEF_base::KEL(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Elem_VEF::nb_facette(), Zone_VEF::rang_elem_non_std(), ref_cast_non_const, Zone_VEF::type_elem(), Deriv_Elem_VEF_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and Zone_Cl_VEF::vecteur_face_facette_Cl().
Referenced by ajouter().
modifier_pour_Cl()
void Op_Conv_Muscl_New_VEF_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 2360 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  Op_Conv_VEF_Face::modifier_pour_Cl(matrice,secmem);
}
References Op_Conv_VEF_Face::modifier_pour_Cl().
printOn()
Sortie & Op_Conv_Muscl_New_VEF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Conv_base.
Definition at line 79 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  return s << que_suis_je();
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Conv_Muscl_New_VEF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Conv_base.
Definition at line 87 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
// Les mots a reconnaitre
  Motcle motlu, accouverte = "{" , accfermee = "}" ;
  Motcle limiteur;
  Motcles les_mots(8);
  {
    les_mots[0] = "centre";
    les_mots[1] = "amont";
    les_mots[2] = "stab";
    les_mots[3] = "alpha";
    les_mots[4] = "centre_old";
    les_mots[5] = "version";
    les_mots[6] = "limiteur";
    les_mots[7] = "facsec_auto";
  }
  Motcles les_mots2(3);
  {
    les_mots2[0] = "vanleer";
    les_mots2[1] = "minmod";
    les_mots2[2] = "superbee";
  }
// Les variables a instancier
  alpha_=1.;
  centered_=1;
  upwind_=1;
  stabilized_=1;
  old_centered_=0;
  version_=2;
  limiteur_=&minmod;
  facsec_auto_=0;
  max_limiteur_=1.;
// Temporaire
// s >> motlu;
// if (motlu!=accouverte)
// {
// if (Process::je_suis_maitre())
// {
// Cerr << "Erreur Op_Conv_Muscl_New_VEF_Face::readOn()" << finl;
// Cerr << "Depuis la 1.6.1, la syntaxe du mot cle MUSCL a change." << finl;
// Cerr << "Il faut commencer par une accolade ouvrante {" << finl;
// Cerr << "et les options eventuelles sont entre les accolades:" << finl;
// Cerr << "Convection { muscl } -> Convection { muscl { } }" << finl;
// }
// Process::exit();
// }
// s >> motlu;
// while(motlu!=accfermee)
// {
// int rang=les_mots.search(motlu);
// switch(rang)
// {
// case 0 :
// centered_=1;
// upwind_=0;
// stabilized_=0;
// break;
// case 1 :
// centered_=1;
// upwind_=1;
// stabilized_=0;
// break;
// case 2 :
// centered_=1;
// upwind_=1;
// stabilized_=1;
// break;
// case 3 :
// s >> alpha_;
// break;
// case 4 :
// centered_=1;
// upwind_=0;
// stabilized_=0;
// old_centered_=1;
// break;
// case 5 :
// s>>version_;
// break;
// case 6 :
// s>>limiteur;
// int rang2=les_mots2.search(limiteur);
// switch(rang2)
// {
// case 0 :
// limiteur_=&vanleer;
// max_limiteur_=2.;
// break;
// case 1 :
// limiteur_=&minmod;
// max_limiteur_=1.;
// break;
// case 2 :
// limiteur_=&superbee;
// max_limiteur_=2.;
// break;
// default :
// if (Process::je_suis_maitre())
// {
// Cerr << "Erreur Op_Conv_Muscl_New_VEF_Face::readOn()" << finl;
// Cerr << "Limiteur "<<limiteur<<" non code" << finl;
// Cerr << "Sortie du programme" << finl;
// }
// Process::exit();
// break;
// }
// break;
// case 7 :
// s>>facsec_auto_;
// break;
// default :
// if (Process::je_suis_maitre())
// {
// Cerr << "Erreur Op_Conv_Muscl_New_VEF_Face::readOn()" << finl;
// Cerr << "Mot clef " << motlu << " non connu." << finl;
// Cerr << "Sortie du programme." << finl;
// }
// Process::exit();
// break;
// }//fin du switch
// //Suite de la lecture
// s >> motlu;
// }//fin du while
// Fin du temporaire
  return s;
}
References alpha_, centered_, facsec_auto_, limiteur(), limiteur_, max_limiteur_, minmod(), old_centered_, stabilized_, upwind_, and version_.
remplir_fluent()
void Op_Conv_Muscl_New_VEF_Face::remplir_fluent (DoubleVect & fluent_) const override virtual
Reimplemented from Op_Conv_VEF_base.
Definition at line 1005 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Champ_Inc_base& la_vitesse=vitesse_.valeur();
  const DoubleTab& velocity=la_vitesse.valeurs();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const int nb_faces = zone_VEF.nb_faces();
// calcul de la CFL.
  double psc;
// On remet a zero le tableau qui sert pour
// le calcul du pas de temps de stabilite
  fluent_ = 0;
  for(int num_face=0; num_face<nb_faces; num_face++)
    {
      psc=0.;
      for (int i=0; i<dimension; i++)
        psc+=velocity(num_face,i)*face_normales(num_face,i);
      fluent_(num_face)=std::fabs(psc);
    }
}
References Objet_U::dimension, Zone_VEF::face_normales(), Op_Conv_VEF_base::la_zone_vef, Zone_VF::nb_faces(), Ref_Champ_Inc_base::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc_base::valeurs(), and Op_Conv_VEF_base::vitesse_.
self_cast() [1/2]
const Op_Conv_Muscl_New_VEF_Face & Op_Conv_Muscl_New_VEF_Face::self_cast (const Objet_U & r) static
Definition at line 73 of file Op_Conv_Muscl_New_VEF_Face.cpp.
self_cast() [2/2]
Op_Conv_Muscl_New_VEF_Face & Op_Conv_Muscl_New_VEF_Face::self_cast (Objet_U & r) static
Definition at line 73 of file Op_Conv_Muscl_New_VEF_Face.cpp.
taille_memoire()
unsigned Op_Conv_Muscl_New_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 73 of file Op_Conv_Muscl_New_VEF_Face.cpp.
test()
void Op_Conv_Muscl_New_VEF_Face::test (const DoubleTab & transporte, const DoubleTab & resu, const DoubleTab & vitesse) const private
Definition at line 2106 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
}
test_difference_Kij()
void Op_Conv_Muscl_New_VEF_Face::test_difference_Kij (const DoubleTab & transporte, DoubleTab & Kij, DoubleTab & Kij_ancien, const DoubleTab & vitesse) const private
Definition at line 2110 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
}
test_difference_resu()
void Op_Conv_Muscl_New_VEF_Face::test_difference_resu (const DoubleTab & Kij, const DoubleTab & Kij_ancien, const DoubleTab & transporte, const DoubleTab & resu, const DoubleTab & vitesse) const private
Definition at line 2114 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
// DoubleTab resu1(resu);
// resu1=0;
// if (is_compressible_) ajouter_partie_compressible(transporte,resu1,velocity);
// ajouter_operateur_centre(Kij,transporte,resu1);
// ajouter_diffusion(Kij,transporte,resu1);
// ajouter_antidiffusion(Kij,transporte,resu1);
// mettre_a_jour_pour_periodicite(resu1);
}
test_implicite()
void Op_Conv_Muscl_New_VEF_Face::test_implicite () const private
Definition at line 3012 of file Op_Conv_Muscl_New_VEF_Face.cpp.
{
}
Member Data Documentation
alpha_
double Op_Conv_Muscl_New_VEF_Face::alpha_ private
Definition at line 111 of file Op_Conv_Muscl_New_VEF_Face.h.
Referenced by ajouter_antidiffusion_v1(), ajouter_antidiffusion_v2(), ajouter_diffusion(), completer(), and readOn().
alpha_tab
ArrOfDouble Op_Conv_Muscl_New_VEF_Face::alpha_tab private
Definition at line 107 of file Op_Conv_Muscl_New_VEF_Face.h.
Referenced by completer().
beta
ArrOfDouble Op_Conv_Muscl_New_VEF_Face::beta private
vaut zero pour les faces ou l'on souhaite degenerer en Amont. mutable DoubleTab limiteurs_;//tableau stockant pour chaque face la moyenne algebrique du limiteur
Definition at line 108 of file Op_Conv_Muscl_New_VEF_Face.h.
Referenced by completer().
centered_
int Op_Conv_Muscl_New_VEF_Face::centered_ private
Definition at line 113 of file Op_Conv_Muscl_New_VEF_Face.h.
Referenced by ajouter(), and readOn().
facsec_auto_
int Op_Conv_Muscl_New_VEF_Face::facsec_auto_ private
Definition at line 118 of file Op_Conv_Muscl_New_VEF_Face.h.
Referenced by calculer_dt_stab(), and readOn().
info_obj
const Type_info Op_Conv_Muscl_New_VEF_Face::info_obj static
Definition at line 45 of file Op_Conv_Muscl_New_VEF_Face.h.
is_dirichlet_faces_
IntTab Op_Conv_Muscl_New_VEF_Face::is_dirichlet_faces_ private
Definition at line 104 of file Op_Conv_Muscl_New_VEF_Face.h.
Referenced by ajouter_antidiffusion_v1(), ajouter_antidiffusion_v2(), and calculer_data_pour_dirichlet().
is_element_for_upwinding_
IntTab Op_Conv_Muscl_New_VEF_Face::is_element_for_upwinding_ private
Definition at line 103 of file Op_Conv_Muscl_New_VEF_Face.h.
Referenced by calculer_data_pour_dirichlet(), and modifier_flux_operateur_centre().
la_sous_zone_dis
Ref_Sous_zone_VF Op_Conv_Muscl_New_VEF_Face::la_sous_zone_dis private
Definition at line 122 of file Op_Conv_Muscl_New_VEF_Face.h.
limiteur_
double(* Op_Conv_Muscl_New_VEF_Face::limiteur_) (double) private
Definition at line 124 of file Op_Conv_Muscl_New_VEF_Face.h.
Referenced by readOn().
max_limiteur_
double Op_Conv_Muscl_New_VEF_Face::max_limiteur_ private
Definition at line 112 of file Op_Conv_Muscl_New_VEF_Face.h.
Referenced by calculer_dt_stab(), and readOn().
nom_sous_zone
Nom Op_Conv_Muscl_New_VEF_Face::nom_sous_zone private
Definition at line 121 of file Op_Conv_Muscl_New_VEF_Face.h.
old_centered_
int Op_Conv_Muscl_New_VEF_Face::old_centered_ private
Definition at line 116 of file Op_Conv_Muscl_New_VEF_Face.h.
Referenced by ajouter(), ajouter_operateur_centre(), calculer_data_pour_dirichlet(), mettre_a_jour_pour_periodicite(), and readOn().
stabilized_
int Op_Conv_Muscl_New_VEF_Face::stabilized_ private
Definition at line 115 of file Op_Conv_Muscl_New_VEF_Face.h.
Referenced by ajouter(), and readOn().
upwind_
int Op_Conv_Muscl_New_VEF_Face::upwind_ private
Definition at line 114 of file Op_Conv_Muscl_New_VEF_Face.h.
Referenced by ajouter(), and readOn().
version_
int Op_Conv_Muscl_New_VEF_Face::version_ private
Definition at line 117 of file Op_Conv_Muscl_New_VEF_Face.h.
Referenced by ajouter_antidiffusion(), and readOn().
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Conv_Muscl_New_VEF_Face.h
src/VEF/Operateurs/Op_Conv_Muscl_New_VEF_Face.cpp