TRUST: Eval_VDF_Elem Class Reference
Eval_VDF_Elem Class Reference
class Eval_VDF_Elem
Cette classe represente le prototype fonctionnel
des evaluateurs de flux associes aux equations de
conservation integrees sur les elements
#include <Eval_VDF_Elem.h>
Public Member Functions
void associer_inconnue (const Champ_base &)
void coeffs_face (int, int, const Symetrie &, double &aii, double &ajj) const
void coeffs_face (int, int, const Neumann_sortie_libre &, double &aii, double &ajj) const
void coeffs_face (int, int, const Dirichlet_entree_fluide &, double &aii, double &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_fixe &, double &aii, double &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_defilante &, double &aii, double &ajj) const
void coeffs_face (int, int, const Neumann_paroi_adiabatique &, double &aii, double &ajj) const
void coeffs_face (int, int, const Neumann_paroi &, double &aii, double &ajj) const
void coeffs_face (int, int, int, int, const Echange_externe_impose &, double &aii, double &ajj) const
void coeffs_face (int, int, const Echange_global_impose &, double &aii, double &ajj) const
void coeffs_face (int, int, const Periodique &, double &aii, double &ajj) const
void coeffs_face (int, int, const NSCBC &, double &aii, double &ajj) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Dirichlet_entree_fluide &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, int, int, const Echange_externe_impose &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Echange_global_impose &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Neumann_paroi &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Neumann_paroi_adiabatique &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Symetrie &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Periodique &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const NSCBC &, int) const
double coeffs_faces_interne_bloc_vitesse (const DoubleTab &, int) const
void coeffs_faces_interne (int, double &aii, double &ajj) const
double secmem_face (int, const Symetrie &, int) const
double secmem_face (int, const Neumann_sortie_libre &, int) const
double secmem_face (int, const Dirichlet_entree_fluide &, int) const
double secmem_face (int, const Dirichlet_paroi_fixe &, int) const
double secmem_face (int, const Dirichlet_paroi_defilante &, int) const
double secmem_face (int, const Neumann_paroi_adiabatique &, int) const
double secmem_face (int, const Neumann_paroi &, int) const
double secmem_face (int, int, int, const Echange_externe_impose &, int) const
double secmem_face (int, const Echange_global_impose &, int) const
double secmem_face (int, const Periodique &, int) const
double secmem_face (int, const NSCBC &, int) const
double secmem_faces_interne (int) const
void coeffs_face (int, int, const Symetrie &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Neumann_sortie_libre &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_entree_fluide &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_fixe &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_defilante &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Neumann_paroi_adiabatique &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Neumann_paroi &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, int, int, const Echange_externe_impose &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Echange_global_impose &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Periodique &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_faces_interne (int, DoubleVect &aii, DoubleVect &ajj) const
void secmem_face (int, const Symetrie &, int, DoubleVect &) const
void secmem_face (int, const Neumann_sortie_libre &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_entree_fluide &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_paroi_fixe &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_paroi_defilante &, int, DoubleVect &) const
void secmem_face (int, const Neumann_paroi_adiabatique &, int, DoubleVect &) const
void secmem_face (int, const Neumann_paroi &, int, DoubleVect &) const
void secmem_face (int, int, int, const Echange_externe_impose &, int, DoubleVect &) const
void secmem_face (int, const Echange_global_impose &, int, DoubleVect &) const
void secmem_faces_interne (int, DoubleVect &) const
void secmem_face (int, const Periodique &, int, DoubleVect &) const
Protected Attributes
Ref_Champ_base inconnue
Detailed Description
class Eval_VDF_Elem
Cette classe represente le prototype fonctionnel
des evaluateurs de flux associes aux equations de
conservation integrees sur les elements
Definition at line 48 of file Eval_VDF_Elem.h.
Member Function Documentation
void Eval_VDF_Elem::associer_inconnue (const Champ_base & inco)
Definition at line 25 of file Eval_VDF_Elem.cpp.
References inconnue, and sub_type.
Referenced by Op_Conv_Quick_VDF_Elem::associer(), Op_Conv_centre_VDF_Elem::associer(), Op_Conv_centre4_VDF_Elem::associer(), and Op_Conv_Amont_VDF_Elem::associer().
{
  assert(sub_type(Champ_P0_VDF,inco));
  inconnue=inco;
}
void Eval_VDF_Elem::coeffs_face (int , int , const Symetrie & , double & aii, double & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 57 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Dirichlet_entree_fluide & , double & aii, double & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 65 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Neumann_paroi & , double & aii, double & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 81 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , int , int , const Echange_externe_impose & , double & aii, double & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 85 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Symetrie & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 218 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Neumann_sortie_libre & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 223 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Dirichlet_paroi_fixe & , double & aii, double & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 69 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Echange_global_impose & , double & aii, double & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 89 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Dirichlet_entree_fluide & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 228 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Dirichlet_paroi_fixe & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 233 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Dirichlet_paroi_defilante & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 238 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Neumann_paroi_adiabatique & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 243 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Periodique & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 263 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Periodique & , double & aii, double & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 93 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Neumann_paroi & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 248 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , int , int , const Echange_externe_impose & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 253 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Echange_global_impose & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 258 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Neumann_sortie_libre & , double & aii, double & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 61 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Dirichlet_paroi_defilante & , double & aii, double & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 73 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const NSCBC & , double & aii, double & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 97 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_face (int , int , const Neumann_paroi_adiabatique & , double & aii, double & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 77 of file Eval_VDF_Elem.h.
  {
    ;
  }
double Eval_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , int , int , const Echange_externe_impose & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 115 of file Eval_VDF_Elem.h.
  {
    return 0.;
  }
double Eval_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Echange_global_impose & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 119 of file Eval_VDF_Elem.h.
  {
    return 0.;
  }
double Eval_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Neumann_paroi & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 123 of file Eval_VDF_Elem.h.
  {
    return 0.;
  }
double Eval_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 127 of file Eval_VDF_Elem.h.
  {
    return 0.;
  }
double Eval_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Neumann_sortie_libre & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 131 of file Eval_VDF_Elem.h.
  {
    return 0.;
  }
double Eval_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Symetrie & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 135 of file Eval_VDF_Elem.h.
  {
    return 0.;
  }
double Eval_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Periodique & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 139 of file Eval_VDF_Elem.h.
  {
    return 0.;
  }
double Eval_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const NSCBC & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 143 of file Eval_VDF_Elem.h.
  {
    return 0.;
  }
double Eval_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Dirichlet_entree_fluide & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 103 of file Eval_VDF_Elem.h.
  {
    return 0.;
  }
double Eval_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 107 of file Eval_VDF_Elem.h.
  {
    return 0.;
  }
double Eval_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 111 of file Eval_VDF_Elem.h.
  {
    return 0.;
  }
void Eval_VDF_Elem::coeffs_faces_interne (int , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 268 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::coeffs_faces_interne (int , double & aii, double & ajj) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 155 of file Eval_VDF_Elem.h.
  {
    ;
  }
double Eval_VDF_Elem::coeffs_faces_interne_bloc_vitesse (const DoubleTab & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 147 of file Eval_VDF_Elem.h.
  {
    return 0.;
  }
void Eval_VDF_Elem::secmem_face (int , const Dirichlet_entree_fluide & , int , DoubleVect &) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 285 of file Eval_VDF_Elem.h.
  {
    ;
  }
double Eval_VDF_Elem::secmem_face (int , const Echange_global_impose & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 195 of file Eval_VDF_Elem.h.
  {
    return 0;
  }
void Eval_VDF_Elem::secmem_face (int , const Dirichlet_paroi_fixe & , int , DoubleVect &) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 289 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::secmem_face (int , const Symetrie & , int , DoubleVect &) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 277 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::secmem_face (int , const Neumann_sortie_libre & , int , DoubleVect &) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 281 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::secmem_face (int , const Echange_global_impose & , int , DoubleVect &) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 309 of file Eval_VDF_Elem.h.
  {
    ;
  }
double Eval_VDF_Elem::secmem_face (int , const NSCBC & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 203 of file Eval_VDF_Elem.h.
  {
    return 0;
  }
void Eval_VDF_Elem::secmem_face (int , const Periodique & , int , DoubleVect &) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 317 of file Eval_VDF_Elem.h.
  {
    ;
  }
double Eval_VDF_Elem::secmem_face (int , const Neumann_paroi & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 187 of file Eval_VDF_Elem.h.
  {
    return 0;
  }
double Eval_VDF_Elem::secmem_face (int , const Dirichlet_paroi_defilante & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 179 of file Eval_VDF_Elem.h.
  {
    return 0;
  }
void Eval_VDF_Elem::secmem_face (int , const Dirichlet_paroi_defilante & , int , DoubleVect &) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 293 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::secmem_face (int , const Neumann_paroi_adiabatique & , int , DoubleVect &) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 297 of file Eval_VDF_Elem.h.
  {
    ;
  }
double Eval_VDF_Elem::secmem_face (int , const Dirichlet_entree_fluide & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 171 of file Eval_VDF_Elem.h.
  {
    return 0;
  }
double Eval_VDF_Elem::secmem_face (int , int , int , const Echange_externe_impose & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 191 of file Eval_VDF_Elem.h.
  {
    return 0;
  }
double Eval_VDF_Elem::secmem_face (int , const Periodique & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 199 of file Eval_VDF_Elem.h.
  {
    return 0;
  }
void Eval_VDF_Elem::secmem_face (int , const Neumann_paroi & , int , DoubleVect &) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 301 of file Eval_VDF_Elem.h.
  {
    ;
  }
void Eval_VDF_Elem::secmem_face (int , int , int , const Echange_externe_impose & , int , DoubleVect &) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 305 of file Eval_VDF_Elem.h.
  {
    ;
  }
double Eval_VDF_Elem::secmem_face (int , const Dirichlet_paroi_fixe & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 175 of file Eval_VDF_Elem.h.
  {
    return 0;
  }
double Eval_VDF_Elem::secmem_face (int , const Neumann_sortie_libre & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 167 of file Eval_VDF_Elem.h.
  {
    return 0;
  }
double Eval_VDF_Elem::secmem_face (int , const Neumann_paroi_adiabatique & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 183 of file Eval_VDF_Elem.h.
  {
    return 0;
  }
double Eval_VDF_Elem::secmem_face (int , const Symetrie & , int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 163 of file Eval_VDF_Elem.h.
  {
    return 0;
  }
void Eval_VDF_Elem::secmem_faces_interne (int , DoubleVect &) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 313 of file Eval_VDF_Elem.h.
  {
    ;
  }
double Eval_VDF_Elem::secmem_faces_interne (int) const [inline]
Reimplemented in Eval_Amont_VDF_Elem, Eval_centre4_VDF_Elem, and Eval_centre_VDF_Elem.
Definition at line 207 of file Eval_VDF_Elem.h.
  {
    return 0;
  }
Member Data Documentation
Ref_Champ_base Eval_VDF_Elem::inconnue [protected]
Definition at line 325 of file Eval_VDF_Elem.h.
Referenced by associer_inconnue(), Eval_centre_VDF_Elem::coeffs_face(), Eval_centre4_VDF_Elem::coeffs_face(), Eval_centre_VDF_Elem::coeffs_faces_interne(), and Eval_centre4_VDF_Elem::coeffs_faces_interne().
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Evaluateurs/Eval_VDF_Elem.h
src/VDF/Operateurs/Evaluateurs/Eval_VDF_Elem.cpp