TRUST: Flux_interfacial_Coef_Constant Class Reference
Flux_interfacial_Coef_Constant Class Reference
Flux interfacial a coefficient constant par phase.
#include <Flux_interfacial_Coef_Constant.h>
Public Member Functions
Flux_interfacial_Coef_Constant ()
~Flux_interfacial_Coef_Constant ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void coeffs (const double &dh, const double *alpha, const double *T, const double p, const double *nv, const double *lambda, const double *mu, const double *rho, const double *Cp, DoubleTab &hi, DoubleTab &dT_hi, DoubleTab &da_hi, DoubleTab &dp_hi) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Flux_interfacial_Coef_Constant & self_cast (Objet_U &)
static const
Flux_interfacial_Coef_Constant & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
DoubleTab h_phase
Detailed Description
Flux interfacial a coefficient constant par phase.
Definition at line 34 of file Flux_interfacial_Coef_Constant.h.
Constructor & Destructor Documentation
Flux_interfacial_Coef_Constant::Flux_interfacial_Coef_Constant ()
Definition at line 26 of file Flux_interfacial_Coef_Constant.cpp.
Flux_interfacial_Coef_Constant::~Flux_interfacial_Coef_Constant ()
Definition at line 26 of file Flux_interfacial_Coef_Constant.cpp.
Member Function Documentation
void Flux_interfacial_Coef_Constant::coeffs (const double & dh, const double * alpha, const double * T, const double p, const double * nv, const double * lambda, const double * mu, const double * rho, const double * Cp, DoubleTab & hi, DoubleTab & dT_hi, DoubleTab & da_hi, DoubleTab & dp_hi) const [virtual]
Implements Flux_interfacial_base.
Definition at line 45 of file Flux_interfacial_Coef_Constant.cpp.
References DoubleTab::dimension(), and h_phase.
{
  int k, l, N = hi.dimension(0);
  for (k = 0; k < N; k++) for (l = 0; l < N; l++) hi(k, l) = h_phase(k); //ne depend que de la phase de depart
  dT_hi = 0, da_hi = 0, dp_hi = 0; //pas trop dur
}
Objet_U * Flux_interfacial_Coef_Constant::cree_instance () [static]
Definition at line 26 of file Flux_interfacial_Coef_Constant.cpp.
int Flux_interfacial_Coef_Constant::duplique () const [virtual]
Implements Flux_interfacial_base.
Definition at line 26 of file Flux_interfacial_Coef_Constant.cpp.
const Type_info * Flux_interfacial_Coef_Constant::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Flux_interfacial_base.
Definition at line 26 of file Flux_interfacial_Coef_Constant.cpp.
const Type_info * Flux_interfacial_Coef_Constant::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Flux_interfacial_base.
Definition at line 26 of file Flux_interfacial_Coef_Constant.cpp.
Sortie & Flux_interfacial_Coef_Constant::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Flux_interfacial_base.
Definition at line 28 of file Flux_interfacial_Coef_Constant.cpp.
{
  return os;
}
Entree & Flux_interfacial_Coef_Constant::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Flux_interfacial_base.
Definition at line 33 of file Flux_interfacial_Coef_Constant.cpp.
References Param::ajouter(), h_phase, Param::lire_avec_accolades_depuis(), Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), ref_cast, Param::REQUIRED, DoubleTab::resize(), and Ref_Probleme_base::valeur().
{
  Param param(que_suis_je());
// un parametre par phase du probleme
  const Pb_Multiphase& pbm = ref_cast(Pb_Multiphase, pb_.valeur());
  h_phase.resize(pbm.nb_phases());
  for (int n = 0; n < pbm.nb_phases(); n++)
    param.ajouter(pbm.nom_phase(n), &h_phase(n), Param::REQUIRED);
  param.lire_avec_accolades_depuis(is);
  return is;
}
const Flux_interfacial_Coef_Constant & Flux_interfacial_Coef_Constant::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Flux_interfacial_base.
Definition at line 26 of file Flux_interfacial_Coef_Constant.cpp.
Flux_interfacial_Coef_Constant & Flux_interfacial_Coef_Constant::self_cast (Objet_U & r) [static]
Reimplemented from Flux_interfacial_base.
Definition at line 26 of file Flux_interfacial_Coef_Constant.cpp.
unsigned Flux_interfacial_Coef_Constant::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Flux_interfacial_Coef_Constant.cpp.
Member Data Documentation
DoubleTab Flux_interfacial_Coef_Constant::h_phase [protected]
Definition at line 42 of file Flux_interfacial_Coef_Constant.h.
Referenced by coeffs(), and readOn().
const Type_info Flux_interfacial_Coef_Constant::info_obj [static]
Reimplemented from Flux_interfacial_base.
Definition at line 36 of file Flux_interfacial_Coef_Constant.h.
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Correlations/Flux_interfacial_Coef_Constant.h
src/ThHyd/Multiphase/Correlations/Flux_interfacial_Coef_Constant.cpp