TRUST: Create_domain_from_sous_zone Class Reference
Create_domain_from_sous_zone Class Reference
Classe Create_domain_from_sous_zone
Lecture d'un fichier.
#include <Create_domain_from_sous_zone.h>
Public Member Functions
Create_domain_from_sous_zone ()
~Create_domain_from_sous_zone ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Create_domain_from_sous_zone & self_cast (Objet_U &)
static const
Create_domain_from_sous_zone & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Classe Create_domain_from_sous_zone
Lecture d'un fichier.
Definition at line 45 of file Create_domain_from_sous_zone.h.
Constructor & Destructor Documentation
Create_domain_from_sous_zone::Create_domain_from_sous_zone ()
Definition at line 31 of file Create_domain_from_sous_zone.cpp.
Create_domain_from_sous_zone::~Create_domain_from_sous_zone ()
Definition at line 31 of file Create_domain_from_sous_zone.cpp.
Member Function Documentation
Objet_U * Create_domain_from_sous_zone::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 31 of file Create_domain_from_sous_zone.cpp.
int Create_domain_from_sous_zone::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 31 of file Create_domain_from_sous_zone.cpp.
const Type_info * Create_domain_from_sous_zone::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 31 of file Create_domain_from_sous_zone.cpp.
const Type_info * Create_domain_from_sous_zone::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 31 of file Create_domain_from_sous_zone.cpp.
Entree & Create_domain_from_sous_zone::interpreter_ (Entree & is) [virtual]
< XD_ADD_P ref_domaine new domain in which faces are stored
< XD_ADD_P chaine a sub-area allowing to choose the elements
< XD_ADD_P ref_domaine initial domain 16/10/2017: desactivation du mot-cle par_sous_zones param.ajouter("par_sous_zones",&vec_nom_ssz); // listchaine several sub-zones allowing to choose the elements param.ajouter_condition("is_read_par_sous_zone_or_is_read_par_sous_zones","Interpreter Create_domain_from_sous_zone: one of the keywords par_sous_zone or par_sous_zones must be specified.");
Implements Interprete_geometrique_base.
Definition at line 45 of file Create_domain_from_sous_zone.cpp.
References List_Raccord::add(), List_Bord::add(), Vect_Nom::add(), Param::ajouter(), ArrOfInt::append_array(), Interprete_geometrique_base::associer_domaine(), DomaineCutter::bords_internes(), Cerr, DomaineCutter::construire_sous_domaine(), Cout, Interprete_geometrique_base::domaine(), Process::exit(), Zone::faces_bord(), Zone::faces_joint(), Zone::faces_raccord(), finl, Scatter::init_sequential_domain(), DomaineCutter::initialiser(), Objet_U::le_nom(), Param::lire_avec_accolades_depuis(), LIST, Zone::nb_elem(), Sous_Zone::nb_elem_tot(), Bords::nb_faces(), Domaine::nommer(), Frontiere::nommer(), Process::nproc(), Interprete::objet(), Objet_U::que_suis_je(), Noms::rang(), REF, ref_cast, Param::REQUIRED, ArrOfInt::set_smart_resize(), liste::size(), vect_impl::size(), ArrOfInt::size_array(), Domaine::ss_zones(), List_Bord::suppr(), List_Joint::suppr(), Deriv_::typer(), valeur(), Deriv_Raccord_base::valeur(), liste::vide(), and Domaine::zone().
{
  Nom nom_dom,nom_dom_org;
  Nom nom_sous_zone;
  Noms vec_nom_ssz;
  Param param(que_suis_je());
  param.ajouter("domaine_final",&nom_dom,Param::REQUIRED); //!< XD_ADD_P ref_domaine new domain in which faces are stored
  param.ajouter("par_sous_zone",&nom_sous_zone,Param::REQUIRED); //!< XD_ADD_P chaine a sub-area allowing to choose the elements
  param.ajouter("domaine_init",&nom_dom_org,Param::REQUIRED); //!< XD_ADD_P ref_domaine initial domain 16/10/2017: desactivation du mot-cle par_sous_zones param.ajouter("par_sous_zones",&vec_nom_ssz); // listchaine several sub-zones allowing to choose the elements param.ajouter_condition("is_read_par_sous_zone_or_is_read_par_sous_zones","Interpreter Create_domain_from_sous_zone: one of the keywords par_sous_zone or par_sous_zones must be specified.");
//
//
//
  param.lire_avec_accolades_depuis(is);
  associer_domaine(nom_dom);
  Domaine& dom=domaine();
  if (nproc()>1)
    {
      Cerr<<"Options par_sous_zone and par_sous_zones of  "<<que_suis_je()<<" are for sequential." <<finl;
      exit();
    }
  const Domaine& domaine_org=ref_cast(Domaine, objet(nom_dom_org));
  IntTab marq_elem(domaine_org.zone(0).nb_elem());
  if (vec_nom_ssz.size()==0)
    vec_nom_ssz.add(Nom(nom_sous_zone));
  else
    Cerr << "\nWARNING: par_sous_zones option only available for subzones that do not touch each other!!\n" << finl;
  int nb_poly = 0;
  DomaineCutter cutter;
  Noms vide;
  for ( int i=0; i<vec_nom_ssz.size(); i++ )
    {
      const Sous_Zone& ssz=ref_cast(Sous_Zone,objet(vec_nom_ssz(i)));
      nb_poly=ssz.nb_elem_tot();
      for (int pol=0; pol<nb_poly; pol++)
        marq_elem(ssz[pol])=1;
    }
  cutter.initialiser(domaine_org,marq_elem,2,1,vide,1);
  cutter.construire_sous_domaine(1,dom);
  Zone& zone=dom.zone(0);
  Bords& bords=zone.faces_bord();
  if (cutter.bords_internes().size()>0)
    zone.faces_joint().vide();
  else
    {
// on transforme les joints en bord
      Joints& joints= zone.faces_joint();
      for (int j=joints.size()-1; j>=0; j--)
        {
          Cout <<"The joint"<<j<<" becomes a boundary"<<finl;
          Bord b;
          ref_cast(Frontiere,b)=ref_cast(Frontiere,joints(j));
          b.nommer(Nom("Couture_")+Nom(j));
          bords.add(b);
          joints.suppr(joints(j));
        }
    }
  for (int b=bords.size()-1; b>=0; b--)
    if (bords(b).nb_faces()==0)
      {
        Cout << bords(b).le_nom()<<" deleted"<<finl;
        bords.suppr(bords(b));
      }
  Raccords& listrac=zone.faces_raccord();
  for (int b=bords.size()-1; b>=0; b--)
    {
      if (cutter.bords_internes().rang(bords(b).le_nom())>=0)
        {
          Cout << bords(b).le_nom() <<" becomes a connection "<<finl;
          Raccord racc_base;
          racc_base.typer("Raccord_local_homogene");
          Raccord_base& racc=racc_base.valeur();
// on caste en Frontiere pour pouvoir faire la copie ...
          ref_cast(Frontiere,racc)=ref_cast(Frontiere,bords(b));
          listrac.add(racc_base);
          bords.suppr(bords(b));
        }
    }
// et les sous-zones?
  const LIST(REF(Sous_Zone)) & liste_sous_zones = domaine_org.ss_zones();
  int nb_sous_zones = liste_sous_zones.size();
  const Sous_Zone& ssz=ref_cast(Sous_Zone,objet(vec_nom_ssz(0)));
  ArrOfInt rev_ssz(domaine_org.zone(0).nb_elem());
  rev_ssz = -1;
  for (int i = 0; i < nb_poly; i++)
    rev_ssz(ssz[i]) = i;
  Nom jdd(" "), jdd_par(" ");
  int ecr_jdd = 0;
  for (int i = 0; i < nb_sous_zones; i++)
    if (liste_sous_zones[i]->le_nom() != nom_sous_zone)
      {
// liste des elements de la sous-sous-zone
        ArrOfInt polys;
        polys.set_smart_resize(1);
        for (int j = 0, k; j < liste_sous_zones[i]->nb_elem_tot(); j++)
          if ((k = rev_ssz[liste_sous_zones[i].valeur()[j]]) >= 0)
            polys.append_array(k);
        if (!polys.size_array())
          continue; //sous-sous-zone vide!
        Nom nom_ssz(nom_dom + "_" + liste_sous_zones[i]->le_nom()), file_ssz(nom_ssz + ".file");
// contribution aux JDDs des sous-sous-zones
        jdd += Nom("export Sous_Zone ") + nom_ssz + "\n";
        jdd += Nom("Associer ") + nom_ssz + " " + nom_dom + "\n";
        jdd += Nom("Lire ") + nom_ssz + " { fichier " + file_ssz + " }" + "\n";
        jdd_par += Nom("export Sous_Zone ") + nom_ssz + "\n";
        jdd_par += Nom("Associer ") + nom_ssz + " " + nom_dom + "\n";
        jdd_par += Nom("Lire ") + nom_ssz + " { fichier " + nom_ssz + ".ssz }" + "\n";
        ecr_jdd = 1;
// fichier de la sous-sous-zone
        SFichier f_ssz(file_ssz);
        f_ssz << polys;
      }
  if (ecr_jdd)
    {
      SFichier f_jdd(nom_dom + "_ssz.geo");
      SFichier f_jdd_par(nom_dom + "_ssz_par.geo");
      f_jdd << jdd;
      f_jdd_par << jdd_par;
    }
  dom.nommer(nom_dom);
  Scatter::init_sequential_domain(dom);
  return is;
}
Sortie & Create_domain_from_sous_zone::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 36 of file Create_domain_from_sous_zone.cpp.
{
  return Interprete::printOn(os);
}
Entree & Create_domain_from_sous_zone::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 40 of file Create_domain_from_sous_zone.cpp.
{
  return Interprete::readOn(is);
}
Create_domain_from_sous_zone & Create_domain_from_sous_zone::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 31 of file Create_domain_from_sous_zone.cpp.
const Create_domain_from_sous_zone & Create_domain_from_sous_zone::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 31 of file Create_domain_from_sous_zone.cpp.
unsigned Create_domain_from_sous_zone::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 31 of file Create_domain_from_sous_zone.cpp.
Member Data Documentation
const Type_info Create_domain_from_sous_zone::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 47 of file Create_domain_from_sous_zone.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Create_domain_from_sous_zone.h
src/Kernel/Geometrie/Create_domain_from_sous_zone.cpp