TRUST: Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC Class Reference
Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC Class Reference
class Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC
#include <Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.h>
Public Member Functions
~Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int has_interface_blocs () const
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void associer_pb (const Probleme_base &)
void mettre_a_jour (double)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC & self_cast (Objet_U &)
static const
Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
Protected Attributes
Ref_Zone_CoviMAC la_zone_CoviMAC
Ref_Zone_Cl_CoviMAC la_zone_Cl_CoviMAC
Champ_Don himp_
Champ_Don Text_
Detailed Description
class Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC
See also:
Source_base
Definition at line 44 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.h.
Constructor & Destructor Documentation
Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::~Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC ()
Definition at line 32 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.cpp.
Member Function Documentation
void Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) [virtual]
Reimplemented from Source_base.
void Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::associer_pb (const Probleme_base &) [inline, virtual]
Implements Source_base.
Definition at line 58 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.h.
{ };
void Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) [protected, virtual]
Implements Source_base.
Definition at line 86 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.cpp.
References la_zone_Cl_CoviMAC, la_zone_CoviMAC, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  la_zone_CoviMAC = ref_cast(Zone_CoviMAC, zone_dis.valeur());
  la_zone_Cl_CoviMAC = ref_cast(Zone_Cl_CoviMAC, zone_Cl_dis.valeur());
}
Objet_U * Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::cree_instance () [static]
Definition at line 32 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.cpp.
void Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::dimensionner_blocs (matrices_t matrices) const [inline, virtual]
Reimplemented from Source_base.
Definition at line 56 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.h.
{}) const { }; //rien
int Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::duplique () const [virtual]
Implements Source_base.
Definition at line 32 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.cpp.
const Type_info * Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 32 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.cpp.
int Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::has_interface_blocs () const [inline, virtual]
Reimplemented from Source_base.
Definition at line 52 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.h.
  {
    return 1;
  };
const Type_info * Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 32 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.cpp.
void Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 59 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.cpp.
References Source_base::bilan(), DoubleTab::dimension(), MorEqn::equation(), himp_, Equation_base::inconnue(), la_zone_CoviMAC, DoubleVect::line_size(), Champ_Don::mettre_a_jour(), Zone_dis_base::nb_elem(), DoubleVect::resize(), Text_, Deriv_Champ_Don_base::valeur(), Ref_Zone_CoviMAC::valeur(), Champ_Inc::valeurs(), Champ_Don_base::valeurs(), and Zone_VF::volumes().
{
  const Zone_VF& zone = la_zone_CoviMAC.valeur();
  const DoubleVect& volumes = zone.volumes();
  const DoubleTab& himp = himp_.valeur().valeurs();
  const DoubleTab& Text = Text_.valeur().valeurs();
  const DoubleTab& T = equation().inconnue().valeurs();
  int nb_elem = la_zone_CoviMAC.valeur().nb_elem(), c_h = himp.dimension(0) == 1, c_T = Text.dimension(0) == 1, n, N = T.line_size();
  bilan().resize(N), bilan() = 0;
  for (int e = 0; e < nb_elem; e++) for (n = 0; n < N; n++)
      bilan()(n) += himp(!c_h * e, n) * volumes(e) * (Text(!c_T * e, n) - T(e, n));
  himp_.mettre_a_jour(temps);
  Text_.mettre_a_jour(temps);
}
Sortie & Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 39 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je();
}
Entree & Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 48 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.cpp.
References Param::ajouter(), himp_, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), Param::REQUIRED, Source_base::set_description(), Source_base::set_fichier(), and Text_.
{
  Param param(que_suis_je());
  param.ajouter("himp",&himp_,Param::REQUIRED);
  param.ajouter("Text",&Text_,Param::REQUIRED);
  param.lire_avec_accolades_depuis(s);
  set_fichier("Terme_Puissance_Thermique_Echange_Impose");
  set_description("Power (W)");
  return s ;
}
const Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC & Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Definition at line 32 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.cpp.
Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC & Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Definition at line 32 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.cpp.
unsigned Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 32 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.cpp.
Member Data Documentation
Champ_Don Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::himp_ [protected]
Definition at line 65 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.h.
Referenced by mettre_a_jour(), and readOn().
const Type_info Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::info_obj [static]
Reimplemented from Source_base.
Definition at line 49 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.h.
Ref_Zone_Cl_CoviMAC Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::la_zone_Cl_CoviMAC [protected]
Definition at line 64 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.h.
Referenced by associer_zones().
Ref_Zone_CoviMAC Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::la_zone_CoviMAC [protected]
Definition at line 63 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.h.
Referenced by associer_zones(), and mettre_a_jour().
Champ_Don Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::Text_ [protected]
Definition at line 65 of file Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.h.
Referenced by mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/CoviMAC/Sources/Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.h
src/CoviMAC/Sources/Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.cpp