TRUST: cl_timp Class Reference
cl_timp Class Reference
#include <Cond_lim_utilisateur_base.h>
Public Member Functions
cl_timp ()
~cl_timp ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void complement (Nom &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static cl_timp & self_cast (Objet_U &)
static const cl_timp & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'une condition aux limite de type Cond_lim_utilisateur_base
a partir d'un flot d'entree.
Detailed Description
Definition at line 75 of file Cond_lim_utilisateur_base.h.
Constructor & Destructor Documentation
cl_timp::cl_timp ()
Definition at line 34 of file Cond_lim_utilisateur_base.cpp.
cl_timp::~cl_timp ()
Definition at line 34 of file Cond_lim_utilisateur_base.cpp.
Member Function Documentation
void cl_timp::complement (Nom & ajout) [virtual]
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 290 of file Cond_lim_utilisateur_base.cpp.
References Cond_lim_utilisateur_base::is_pb_rayo(), and Cond_lim_utilisateur_base::is_pb_VDF().
{
  int rayo=is_pb_rayo();
  Nom Nrayo;
  if (rayo==1) Nrayo="_rayo_semi_transp";
  if (rayo==2)  Nrayo="_rayo_transp";
  if (is_pb_VDF())
    {
      ajout= "paroi_echange_externe_impose";
      if (rayo)
        ajout+=Nrayo;
      Nom cl(" h_imp champ_front_uniforme 1 1e10 t_ext");
      ajout+=cl;
// exit();
    }
  else
    {
      ajout="temperature_imposee_paroi";
      if (rayo)
        {
          ajout="paroi_temperature_imposee";
          ajout+=Nrayo;
        }
    }
}
Objet_U * cl_timp::cree_instance () [static]
Definition at line 34 of file Cond_lim_utilisateur_base.cpp.
int cl_timp::duplique () const [virtual]
Implements Cond_lim_utilisateur_base.
Definition at line 34 of file Cond_lim_utilisateur_base.cpp.
const Type_info * cl_timp::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 34 of file Cond_lim_utilisateur_base.cpp.
const Type_info * cl_timp::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 34 of file Cond_lim_utilisateur_base.cpp.
Sortie & cl_timp::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 55 of file Cond_lim_utilisateur_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & cl_timp::readOn (Entree & s) [protected, virtual]
Lecture d'une condition aux limite de type Cond_lim_utilisateur_base
a partir d'un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 92 of file Cond_lim_utilisateur_base.cpp.
{
  return s;
}
const cl_timp & cl_timp::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 34 of file Cond_lim_utilisateur_base.cpp.
cl_timp & cl_timp::self_cast (Objet_U & r) [static]
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 34 of file Cond_lim_utilisateur_base.cpp.
unsigned cl_timp::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 34 of file Cond_lim_utilisateur_base.cpp.
Member Data Documentation
const Type_info cl_timp::info_obj [static]
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 77 of file Cond_lim_utilisateur_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Cond_lim_utilisateur_base.h
src/Kernel/Framework/Cond_lim_utilisateur_base.cpp