TRUST: Trianguler_H Class Reference
Trianguler_H Class Reference
Classe Trianguler_H
Cette classe est un interprete qui sert a lire et executer
la directive Trianguler_H:
Trianguler_H nom_domaine
Cette directive est a utiliser en discretisation VEF pour obtenir
un maillage triangulaire a partir d'un maillage constitue de rectangles.
#include <Trianguler_H.h>
Public Member Functions
Trianguler_H ()
~Trianguler_H ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void trianguler (Zone &) const override
Triangule tous les element d'une zone: transforme
les elements goemetriques de la zone en triangles.
Pour l'instant on ne sait trianguler que des Rectangles<br>(on les coupe en 2).
int dimension_application () const override
Public Member Functions inherited from Triangulation_base
Triangulation_base ()
~Triangulation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void trianguler (Zone &) const =0
virtual int dimension_application () const =0
Entree & interpreter_ (Entree &) override
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Trianguler_H & self_cast (Objet_U &)
static const Trianguler_H & self_cast (const Objet_U &)
Static Public Member Functions inherited from Triangulation_base
static const Type_info * info ()
static Triangulation_base & self_cast (Objet_U &)
static const Triangulation_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Triangulation_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Classe Trianguler_H
Cette classe est un interprete qui sert a lire et executer
la directive Trianguler_H:
Trianguler_H nom_domaine
Cette directive est a utiliser en discretisation VEF pour obtenir
un maillage triangulaire a partir d'un maillage constitue de rectangles.
Definition at line 44 of file Trianguler_H.h.
Constructor & Destructor Documentation
Trianguler_H()
Trianguler_H::Trianguler_H ()
Definition at line 19 of file Trianguler_H.cpp.
~Trianguler_H()
Trianguler_H::~Trianguler_H ()
Definition at line 19 of file Trianguler_H.cpp.
Member Function Documentation
cree_instance()
Objet_U * Trianguler_H::cree_instance () static
Definition at line 19 of file Trianguler_H.cpp.
dimension_application()
int Trianguler_H::dimension_application () const inline override virtual
Implements Triangulation_base.
Definition at line 54 of file Trianguler_H.h.
{
  return 2;
}
duplique()
int Trianguler_H::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Trianguler_H.cpp.
get_info()
const Type_info * Trianguler_H::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 19 of file Trianguler_H.cpp.
info()
const Type_info * Trianguler_H::info () static
Definition at line 19 of file Trianguler_H.cpp.
printOn()
Sortie & Trianguler_H::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 36 of file Trianguler_H.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Trianguler_H::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 56 of file Trianguler_H.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Trianguler_H & Trianguler_H::self_cast (const Objet_U & r) static
Definition at line 19 of file Trianguler_H.cpp.
self_cast() [2/2]
Trianguler_H & Trianguler_H::self_cast (Objet_U & r) static
Definition at line 19 of file Trianguler_H.cpp.
taille_memoire()
unsigned Trianguler_H::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Trianguler_H.cpp.
trianguler()
void Trianguler_H::trianguler (Zone & zone) const override virtual
Triangule tous les element d'une zone: transforme
les elements goemetriques de la zone en triangles.
Pour l'instant on ne sait trianguler que des Rectangles<br>(on les coupe en 2).
Implements Triangulation_base.
Definition at line 78 of file Trianguler_H.cpp.
{
  Domaine& dom=zone.domaine();
  IntTab& les_elems=zone.les_elems();
  int oldsz=les_elems.dimension(0);
  DoubleTab& sommets=dom.les_sommets();
  int cpt=sommets.dimension(0);
  {
    DoubleTab sommets_ajoutes(oldsz, dimension);
    zone.type_elem()->calculer_centres_gravite(sommets_ajoutes);
    sommets.resize(cpt+oldsz, dimension);
    for(int i=0; i<oldsz; i++)
      for(int j=0; j<dimension; j++)
        sommets(cpt+i,j)=sommets_ajoutes(i,j);
  }
  if ((zone.type_elem()->que_suis_je() == "Rectangle")|| (zone.type_elem()->que_suis_je() == "Quadrangle"))
    {
      zone.typer("Triangle");
      IntTab new_elems(4*oldsz, 3);
      for(int i=0; i< oldsz; i++)
        {
          int i0=les_elems(i,0);
          int i1=les_elems(i,1);
          int i2=les_elems(i,2);
          int i3=les_elems(i,3);
          new_elems(i,0)=                  i+cpt;
          new_elems(i,1)=                  i0;
          new_elems(i,2)=                  i1;
          new_elems(i+oldsz,0)=                  i+cpt;
          new_elems(i+oldsz,1)=                  i0;
          new_elems(i+oldsz,2)=                  i2;
          mettre_a_jour_sous_zone(zone,i,i+oldsz,1);
          new_elems(i+2*oldsz,0)=          i+cpt;
          new_elems(i+2*oldsz,1)=          i1;
          new_elems(i+2*oldsz,2)=          i3;
          mettre_a_jour_sous_zone(zone,i,i+2*oldsz,1);
          new_elems(i+3*oldsz,0)=          i+cpt;
          new_elems(i+3*oldsz,1)=          i2;
          new_elems(i+3*oldsz,2)=          i3;
          mettre_a_jour_sous_zone(zone,i,i+3*oldsz,1);
        }
      les_elems.ref(new_elems);
    }
  else
    {
      Cerr << "We do not yet know how to Trianguler_h the "
           << zone.type_elem()->que_suis_je() <<"s"<<finl;
    }
}
References Elem_geom::calculer_centres_gravite(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), finl, Zone::les_elems(), Domaine::les_sommets(), Interprete_geometrique_base::mettre_a_jour_sous_zone(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), Zone::type_elem(), and Zone::typer().
Member Data Documentation
info_obj
const Type_info Trianguler_H::info_obj static
Definition at line 46 of file Trianguler_H.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Trianguler_H.h
src/Kernel/Geometrie/Trianguler_H.cpp