TRUST: Correlation_base Class Reference
Correlation_base Class Reference
#include <Correlation_base.h>
Public Member Functions
Correlation_base ()
~Correlation_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual Entree & lire (Entree &is)
void associer_pb (const Probleme_base &pb)
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Correlation_base & self_cast (Objet_U &)
static const Correlation_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
Ref_Probleme_base pb_
Detailed Description
Definition at line 28 of file Correlation_base.h.
Constructor & Destructor Documentation
Correlation_base::Correlation_base ()
Definition at line 24 of file Correlation_base.cpp.
Correlation_base::~Correlation_base ()
Definition at line 24 of file Correlation_base.cpp.
Member Function Documentation
void Correlation_base::associer_pb (const Probleme_base & pb)
Definition at line 41 of file Correlation_base.cpp.
References pb_.
Referenced by Correlation::typer_lire().
{
  pb_ = pb;
}
virtual int Correlation_base::duplique () const [pure virtual]
Implements Objet_U.
Implemented in Changement_phase_base, Changement_phase_Silver_Simpson, Flux_interfacial_base, Flux_interfacial_Coef_Constant, Flux_parietal_base, Frottement_interfacial_base, Frottement_interfacial_bulles, Frottement_interfacial_Sonnenburg, Frottement_interfacial_Wallis, Masse_ajoutee_base, Masse_ajoutee_Coef_Constant, Multiplicateur_diphasique_base, Multiplicateur_diphasique_Friedel, Multiplicateur_diphasique_homogene, Multiplicateur_diphasique_Lottes_Flinn, and Multiplicateur_diphasique_Muhler_Steinhagen.
const Type_info * Correlation_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Changement_phase_base, Changement_phase_Silver_Simpson, Flux_interfacial_base, Flux_interfacial_Coef_Constant, Flux_parietal_base, Frottement_interfacial_base, Frottement_interfacial_bulles, Frottement_interfacial_Sonnenburg, Frottement_interfacial_Wallis, Masse_ajoutee_base, Masse_ajoutee_Coef_Constant, Multiplicateur_diphasique_base, Multiplicateur_diphasique_Friedel, Multiplicateur_diphasique_homogene, Multiplicateur_diphasique_Lottes_Flinn, and Multiplicateur_diphasique_Muhler_Steinhagen.
Definition at line 24 of file Correlation_base.cpp.
const Type_info * Correlation_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Changement_phase_base, Changement_phase_Silver_Simpson, Flux_interfacial_base, Flux_interfacial_Coef_Constant, Flux_parietal_base, Frottement_interfacial_base, Frottement_interfacial_bulles, Frottement_interfacial_Sonnenburg, Frottement_interfacial_Wallis, Masse_ajoutee_base, Masse_ajoutee_Coef_Constant, Multiplicateur_diphasique_base, Multiplicateur_diphasique_Friedel, Multiplicateur_diphasique_homogene, Multiplicateur_diphasique_Lottes_Flinn, and Multiplicateur_diphasique_Muhler_Steinhagen.
Definition at line 24 of file Correlation_base.cpp.
Entree & Correlation_base::lire (Entree & is) [virtual]
Definition at line 36 of file Correlation_base.cpp.
References readOn().
Referenced by Correlation::typer_lire().
{
  return readOn(is);
}
Sortie & Correlation_base::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Changement_phase_base, Changement_phase_Silver_Simpson, Flux_interfacial_base, Flux_interfacial_Coef_Constant, Flux_parietal_base, Frottement_interfacial_base, Frottement_interfacial_bulles, Frottement_interfacial_Sonnenburg, Frottement_interfacial_Wallis, Masse_ajoutee_base, Masse_ajoutee_Coef_Constant, Multiplicateur_diphasique_base, Multiplicateur_diphasique_Friedel, Multiplicateur_diphasique_homogene, Multiplicateur_diphasique_Lottes_Flinn, and Multiplicateur_diphasique_Muhler_Steinhagen.
Definition at line 26 of file Correlation_base.cpp.
{
  return os;
}
Entree & Correlation_base::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Changement_phase_base, Changement_phase_Silver_Simpson, Flux_interfacial_base, Flux_interfacial_Coef_Constant, Flux_parietal_base, Frottement_interfacial_base, Frottement_interfacial_bulles, Frottement_interfacial_Sonnenburg, Frottement_interfacial_Wallis, Masse_ajoutee_base, Masse_ajoutee_Coef_Constant, Multiplicateur_diphasique_base, Multiplicateur_diphasique_Friedel, Multiplicateur_diphasique_homogene, Multiplicateur_diphasique_Lottes_Flinn, and Multiplicateur_diphasique_Muhler_Steinhagen.
Definition at line 31 of file Correlation_base.cpp.
Referenced by lire().
{
  return is;
}
const Correlation_base & Correlation_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Reimplemented in Changement_phase_base, Changement_phase_Silver_Simpson, Flux_interfacial_base, Flux_interfacial_Coef_Constant, Flux_parietal_base, Frottement_interfacial_base, Frottement_interfacial_bulles, Frottement_interfacial_Sonnenburg, Frottement_interfacial_Wallis, Masse_ajoutee_base, Masse_ajoutee_Coef_Constant, Multiplicateur_diphasique_base, Multiplicateur_diphasique_Friedel, Multiplicateur_diphasique_homogene, Multiplicateur_diphasique_Lottes_Flinn, and Multiplicateur_diphasique_Muhler_Steinhagen.
Definition at line 24 of file Correlation_base.cpp.
Correlation_base & Correlation_base::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Reimplemented in Changement_phase_base, Changement_phase_Silver_Simpson, Flux_interfacial_base, Flux_interfacial_Coef_Constant, Flux_parietal_base, Frottement_interfacial_base, Frottement_interfacial_bulles, Frottement_interfacial_Sonnenburg, Frottement_interfacial_Wallis, Masse_ajoutee_base, Masse_ajoutee_Coef_Constant, Multiplicateur_diphasique_base, Multiplicateur_diphasique_Friedel, Multiplicateur_diphasique_homogene, Multiplicateur_diphasique_Lottes_Flinn, and Multiplicateur_diphasique_Muhler_Steinhagen.
Definition at line 24 of file Correlation_base.cpp.
Member Data Documentation
const Type_info Correlation_base::info_obj [static]
Reimplemented from Objet_U.
Reimplemented in Changement_phase_base, Changement_phase_Silver_Simpson, Flux_interfacial_base, Flux_interfacial_Coef_Constant, Flux_parietal_base, Frottement_interfacial_base, Frottement_interfacial_bulles, Frottement_interfacial_Sonnenburg, Frottement_interfacial_Wallis, Masse_ajoutee_base, Masse_ajoutee_Coef_Constant, Multiplicateur_diphasique_base, Multiplicateur_diphasique_Friedel, Multiplicateur_diphasique_homogene, Multiplicateur_diphasique_Lottes_Flinn, and Multiplicateur_diphasique_Muhler_Steinhagen.
Definition at line 30 of file Correlation_base.h.
Ref_Probleme_base Correlation_base::pb_ [protected]
Definition at line 36 of file Correlation_base.h.
Referenced by associer_pb(), Multiplicateur_diphasique_Muhler_Steinhagen::readOn(), Multiplicateur_diphasique_Lottes_Flinn::readOn(), Multiplicateur_diphasique_homogene::readOn(), Multiplicateur_diphasique_Friedel::readOn(), Frottement_interfacial_Wallis::readOn(), Frottement_interfacial_Sonnenburg::readOn(), and Flux_interfacial_Coef_Constant::readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Correlations/Correlation_base.h
src/ThHyd/Multiphase/Correlations/Correlation_base.cpp