TRUST: Champ_Fonc_MED_Tabule Class Reference
Champ_Fonc_MED_Tabule Class Reference
: class Champ_Fonc_MED_Tabule
<Description of class Champ_Fonc_MED_Tabule>
#include <Champ_Fonc_MED_Tabule.h>
Public Member Functions
Champ_Fonc_MED_Tabule ()
~Champ_Fonc_MED_Tabule ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps)
Mise a jour en temps du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Fonc_MED_Tabule & self_cast (Objet_U &)
static const
Champ_Fonc_MED_Tabule & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
DoubleTab tab1_
DoubleTab tab2_
double temps1_
double temps2_
double temps_calc_
Detailed Description
: class Champ_Fonc_MED_Tabule
<Description of class Champ_Fonc_MED_Tabule>
Definition at line 36 of file Champ_Fonc_MED_Tabule.h.
Constructor & Destructor Documentation
Champ_Fonc_MED_Tabule::Champ_Fonc_MED_Tabule ()
Definition at line 25 of file Champ_Fonc_MED_Tabule.cpp.
Champ_Fonc_MED_Tabule::~Champ_Fonc_MED_Tabule ()
Definition at line 25 of file Champ_Fonc_MED_Tabule.cpp.
Member Function Documentation
Objet_U * Champ_Fonc_MED_Tabule::cree_instance () [static]
Reimplemented from Champ_Fonc_MED.
Definition at line 25 of file Champ_Fonc_MED_Tabule.cpp.
int Champ_Fonc_MED_Tabule::duplique () const [virtual]
Reimplemented from Champ_Fonc_MED.
Definition at line 25 of file Champ_Fonc_MED_Tabule.cpp.
const Type_info * Champ_Fonc_MED_Tabule::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_MED.
Definition at line 25 of file Champ_Fonc_MED_Tabule.cpp.
const Type_info * Champ_Fonc_MED_Tabule::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_MED.
Definition at line 25 of file Champ_Fonc_MED_Tabule.cpp.
void Champ_Fonc_MED_Tabule::mettre_a_jour (double temps) [virtual]
Mise a jour en temps du champ.
Reimplemented from Champ_Fonc_MED.
Definition at line 42 of file Champ_Fonc_MED_Tabule.cpp.
References Cerr, DMAXFLOAT, est_egal(), Process::exit(), finl, Champ_Fonc_MED::lire(), ArrOfDouble::size_array(), tab1_, tab2_, temps1_, temps2_, temps_calc_, Champ_Fonc_MED::temps_sauv_, and Champ_Fonc_MED::valeurs().
{
// temps1_ temps2_ tel que temps [temps1_ , temps2_[
  if (est_egal(le_temps,temps_calc_))
    return;
  if ((temps2_<-1e8)||(le_temps<=temps_calc_))
    {
// initialisation   de -1e9 a T[0] on met la meme chose
      lire(temps_sauv_[0]);
      tab1_=valeurs();
      tab2_=valeurs();
      temps2_=temps_sauv_[0];
    }
  if (le_temps>=temps2_)
    {
      int i,nbt=temps_sauv_.size_array();
      int trouve=0;
      for (i=0; i<nbt-1; i++)
        {
          if ((le_temps>=temps_sauv_[i])&&(le_temps<=temps_sauv_[i+1]))
            {
              trouve=1;
              temps1_=temps_sauv_[i];
              lire(temps1_);
              tab1_=valeurs();
              temps2_=temps_sauv_[i+1];
              lire(temps2_);
              tab2_=valeurs();
            }
        }
      if (trouve==0)
        {
          temps1_=temps_sauv_[nbt-1];
          assert(le_temps>=temps_sauv_[nbt-1]);
          lire(temps1_);
          tab1_=valeurs();
          tab2_=tab1_;
          temps2_=DMAXFLOAT;
        }
    }
  if ((le_temps>=temps1_) && (le_temps<temps2_))
    {
      valeurs()=tab2_;
      valeurs()-=tab1_;
      valeurs()*=(le_temps-temps1_)/(temps2_-temps1_);
      valeurs()+=tab1_;
      temps_calc_=le_temps;
// Cerr<<temps_calc_<<" YYYYYY "<<valeurs()[0]<<" "<< tab2_[0]<< " "<<tab1_[0]<<finl;
    }
  else
    {
      Cerr<<"internal error"<<finl;
      exit();
    }
}
Sortie & Champ_Fonc_MED_Tabule::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_MED.
Definition at line 27 of file Champ_Fonc_MED_Tabule.cpp.
{
  Champ_Fonc_MED::printOn( os );
  return os;
}
Entree & Champ_Fonc_MED_Tabule::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
< Cas ou le maillage .med suit la numerotation du maillage decoupe
Reimplemented from Champ_Fonc_MED.
Definition at line 33 of file Champ_Fonc_MED_Tabule.cpp.
References temps1_, temps2_, and temps_calc_.
{
  temps1_=-1e9;
  temps2_=-1e9;
  temps_calc_=-2e9;
  Champ_Fonc_MED::readOn( is );
  return is;
}
Champ_Fonc_MED_Tabule & Champ_Fonc_MED_Tabule::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_MED.
Definition at line 25 of file Champ_Fonc_MED_Tabule.cpp.
const Champ_Fonc_MED_Tabule & Champ_Fonc_MED_Tabule::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_MED.
Definition at line 25 of file Champ_Fonc_MED_Tabule.cpp.
unsigned Champ_Fonc_MED_Tabule::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc_MED.
Definition at line 25 of file Champ_Fonc_MED_Tabule.cpp.
Member Data Documentation
const Type_info Champ_Fonc_MED_Tabule::info_obj [static]
Reimplemented from Champ_Fonc_MED.
Definition at line 39 of file Champ_Fonc_MED_Tabule.h.
DoubleTab Champ_Fonc_MED_Tabule::tab1_ [protected]
Definition at line 44 of file Champ_Fonc_MED_Tabule.h.
Referenced by mettre_a_jour().
DoubleTab Champ_Fonc_MED_Tabule::tab2_ [protected]
Definition at line 44 of file Champ_Fonc_MED_Tabule.h.
Referenced by mettre_a_jour().
double Champ_Fonc_MED_Tabule::temps1_ [protected]
Definition at line 45 of file Champ_Fonc_MED_Tabule.h.
Referenced by mettre_a_jour(), and readOn().
double Champ_Fonc_MED_Tabule::temps2_ [protected]
Definition at line 45 of file Champ_Fonc_MED_Tabule.h.
Referenced by mettre_a_jour(), and readOn().
double Champ_Fonc_MED_Tabule::temps_calc_ [protected]
Definition at line 45 of file Champ_Fonc_MED_Tabule.h.
Referenced by mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/MEDimpl/Champ_Fonc_MED_Tabule.h
src/Kernel/MEDimpl/Champ_Fonc_MED_Tabule.cpp