TRUST: Sch_CN_iteratif Class Reference
Sch_CN_iteratif Class Reference
classe Sch_CN_iteratif
Schema en temps alternant un demi-pas de temps d'Euler implicite et un demi-pas de temps de LeapFrog.
La resolution implicite est iterative (point fixe).
Le pas de temps est calcule comme le produit du pas de temps de stabilite explicite par un facsec.
Le facsec est ajuste automatiquement pour que la resolution converge en un nombre d'iterations predefini.
Les caracteristiques de chaque iteration sont ecrites dans le fichier dt_CN.
La resolution est gouvernee par 4 parametres (valeurs par defauts entre parentheses) :
* seuil (1e-3) : le seuil de convergence. Plus il est bas, plus la resolution est precise.
* facsec_max (2) : la valeur du facsec que l'on ne veut pas depasser (eviter les instabilites et capter les phenomenes physiques)
* niter_min (2) : le nombre minimum d'iterations. En deca, on continue a iterer meme si on semble avoir atteint la convergence.
* niter_avg (3) : le nombre d'iterations que l'on souhaite faire pour arriver a convergence.
* niter_max (6) : le nombre d'iteration au-dela duquel on reessaye avec un facsec plus petit.
Conseil pour le choix des parametres d'ajustement du facsec :
* Choisir seuil en fonction de la precision desiree.
* Choisir niter_min : 2 garantit un schema d'ordre 2 en temps.
* Si on cherche un stationnaire, choisir seuil_statio >= seuil.
* Choisir facsec_max en fonction des phenomenes physiques a capter.
* Commencer par tester avec une grande valeur de niter_avg. Observer le comportement du nombre d'iterations.
Il bute sur une valeur maximum avant de retomber.
* Choisir niter_avg aux 2/3 de cette valeur maximum, et niter_max aux 4/3 ou au double environ.
#include <Sch_CN_iteratif.h>
Public Member Functions
Sch_CN_iteratif ()
~Sch_CN_iteratif ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int nb_valeurs_temporelles () const override
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n, n+1/2 et n+1, donc 3.
int nb_valeurs_futures () const override
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1/2 et n+1 donc 2.
double temps_futur (int i) const override
Renvoie le le temps a la i-eme valeur future.
double temps_defaut () const override
Renvoie le temps que doivent utiliser les champs a
l'appel de valeurs()
Ici : t(n+1/2)
bool initTimeStep (double dt) override
bool iterateTimeStep (bool &converged) override
Calculate the U(n+1) unknown for each equation (if solved) of the problem with the selected time scheme.
int faire_un_pas_de_temps_eqn_base (Equation_base &) override
void completer () override
void set_param (Param &titi) override
Public Member Functions inherited from Schema_Temps_base
~Schema_Temps_base () override
< necessaire pour visual
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void initialize ()
virtual void terminate ()
virtual double computeTimeStep (bool &stop) const
virtual bool initTimeStep (double dt)
virtual void validateTimeStep ()
virtual bool isStationary () const
Retourne 1 si lors du dernier pas de temps, le probleme n'a pas evolue.
virtual void abortTimeStep ()
virtual bool iterateTimeStep (bool &converged)
Calculate the U(n+1) unknown for each equation (if solved) of the problem with the selected time scheme.
int limpr () const
Renvoie 1 s'il y a lieu d'effectuer une impression (cf dt_impr)
Renvoie 0 sinon.
virtual int nb_valeurs_temporelles () const =0
virtual int nb_valeurs_futures () const =0
virtual double temps_futur (int i) const =0
virtual double temps_defaut () const =0
Schema_Temps_base ()
Constructeur par defaut d'un schema en temps.
Initialise differents membres de la classe.
void nommer (const Nom &) override
surcharge Objet_U::nommer(const Nom&)
Donne un nom au shema en temps
const Nom & le_nom () const override
surcharge Objet_U::le_nom()
Renvoie le nom du shema en temps
virtual int faire_un_pas_de_temps_eqn_base (Equation_base &)=0
virtual void set_param (Param &titi)
int sauvegarder (Sortie &) const override
Sauvegarde le temps courant et le nombre de pas de temps
sur un flot de sortie.
int reprendre (Entree &) override
Reprise (lecture) du temps courant et du nombre de pas de
temps effectues a partir d'un flot d'entree.
virtual int mettre_a_jour ()
Mise a jour du temps courant (t+=dt)
et du nombre de pas de temps effectue (nb_pas_dt_++).
virtual void mettre_a_jour_dt (double toto)
virtual void mettre_a_jour_dt_stab ()
double pas_de_temps () const
Renvoie le pas de temps (delta_t) courant.
const DoubleTab & pas_de_temps_locaux () const
virtual bool corriger_dt_calcule (double &dt) const
Corrige le pas de temps calcule que l'on passe en parametre
et verifie qu'il n'est pas "trop" petit (< dt-min_).
La correction est la suivante:
delta_t = min((facteur de securite * dt_calc), dt_max)
Et on verifie que delta_t est "suffisamment" plus grand que dt_min_.
virtual void imprimer (Sortie &os) const
Imprime le pas de temps sur un flot de sortie s'il y a lieu.
virtual int impr (Sortie &os) const
Impression du numero du pas de temps, la valeur du pas de temps.
et du temps courant.
void imprimer (Sortie &os, Probleme_base &pb) const
Imprime le pas de temps sur un flot de sortie s'il y a lieu.
void imprimer (Sortie &os, const Probleme_base &pb) const
virtual int impr (Sortie &os, Probleme_base &pb) const
Impression du numero du pas de temps, la valeur du pas de temps.
et du temps courant.
virtual int impr (Sortie &os, const Probleme_base &pb) const
void imprimer_temps_courant (SFichier &) const
double pas_temps_min () const
Renvoie le pas de temps minimum.
(version const)
double & pas_temps_min ()
Renvoie une reference sur le pas de temps minimum.
double pas_temps_max () const
Renvoie le pas de temps maximum.
(version const)
double & pas_temps_max ()
Renvoie une reference sur le pas de temps maximum.
int nb_impr () const
Renvoie le nombre d'impressions effectuees.
double temps_courant () const
Renvoie le temps courant.
double temps_precedent () const
Renvoie le temps courant.
double temps_calcul () const
Renvoie le temps de calcul ecoule i.e. (temps courant - temps initial).
virtual void changer_temps_courant (const double)
Change le temps courant.
void update_critere_statio (const DoubleTab &tab_critere, Equation_base &equation)
//Actualisation de stationnaire_atteint_ et residu_
(critere residu_<seuil_statio_)
double facteur_securite_pas () const
Renvoie le facteur de securite ou multiplicateur de delta_t.
Ce facteur est utilise lors de la correction/verification du
pas de temps. Voir Schema_Temps_base::corriger_dt_calcule(double&)
(version const)
double & facteur_securite_pas ()
Renvoie une reference sur le facteur de securite ou multiplicateur de delta_t.
Ce facteur est utilise lors de la correction/verification du
pas de temps. Voir Schema_Temps_base::corriger_dt_calcule(double&)
virtual int stop () const
Renvoie 1 si il y lieu de stopper le calcul pour differente raisons:
- le temps final est atteint
- le nombre de pas de temps maximum est depasse
- l'etat stationnaire est atteint
- indicateur d'arret fichier (voir int Schema_Temps_base::stop_lu())
Renvoie 0 sinon.
int lsauv () const
int temps_final_atteint () const
Renvoie 1 si le temps final est atteint (ou depasse).
Renvoie 1 si temps_courant_ >= tmax
Renvoie 0 sinon.
int nb_pas_dt_max_atteint () const
Renvoie 1 si (le nombre de pas de temps >= nombre de pas de temps maximum).
Renvoie 0 sinon.
int temps_cpu_max_atteint () const
int stationnaire_atteint () const
int stop_lu () const
Renvoie 1 si le fichier (d'extension) .stop contient un 1
Renvoie 0 sinon.
int diffusion_implicite () const
Renvoie 1 si le schema en temps a ete lu diffusion_implicite.
double seuil_diffusion_implicite () const
int impr_diffusion_implicite () const
Seuil pour implicitation de la diffusion par GC.
int impr_extremums () const
Impression ou non de GC implicitation.
int niter_max_diffusion_implicite () const
int no_conv_subiteration_diffusion_implicite () const
Iterations maximale pour GC implicitation.
int no_error_if_not_converged_diffusion_implicite () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_nb_pas_dt_max (Entree &)
virtual Entree & lire_periode_sauvegarde_securite_en_heures (Entree &)
virtual Entree & lire_temps_cpu_max (Entree &)
virtual void completer ()=0
double temps_init () const
Renvoie le temps initial.
double temps_max () const
Renvoie une reference sur le temps maximum.
double temps_sauv () const
Renvoie une reference sur le temps de sauvegarde.
double temps_impr () const
Renvoie une reference sur le temps d'impression.
int precision_impr () const
int wcol () const
int gnuplot_header () const
double seuil_statio () const
Renvoie une reference sur le seuil stationnaire.
int nb_pas_dt_max () const
Renvoie une reference sur le nombre de pas maxi.
int nb_pas_dt () const
Renvoie le nombre de pas de temps effectues.
double mode_dt_start () const
int indice_tps_final_atteint () const
int indice_nb_pas_dt_max_atteint () const
int lu () const
int file_allocation () const
double & set_temps_init ()
double & set_temps_max ()
double & set_temps_courant ()
double & set_temps_precedent ()
int & set_nb_pas_dt ()
int & set_nb_pas_dt_max ()
double & set_dt_min ()
double & set_dt_max ()
double & set_dt_sauv ()
double & set_dt_impr ()
int & set_precision_impr ()
double & set_dt ()
double & set_facsec ()
double & set_seuil_statio ()
int & set_stationnaire_atteint ()
void set_stationnaires_atteints (bool flag)
int & set_diffusion_implicite ()
double & set_seuil_diffusion_implicite ()
int & set_niter_max_diffusion_implicite ()
double & set_mode_dt_start ()
int & set_indice_tps_final_atteint ()
int & set_indice_nb_pas_dt_max_atteint ()
int & set_lu ()
const double & residu () const
double & residu ()
int & schema_impr ()
const int & schema_impr () const
virtual void associer_pb (const Probleme_base &)
Probleme_base & pb_base ()
const Probleme_base & pb_base () const
virtual void modifier_second_membre (const Equation_base &eqn, DoubleTab &secmem)
virtual void ajouter_inertie (Matrice_Base &mat_morse, DoubleTab &secmem, const Equation_base &eqn) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const Equation_base &eqn, const tabs_t &semi_impl={}) const
int disable_progress () const
int disable_dt_ev () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Sch_CN_iteratif & self_cast (Objet_U &)
static const Sch_CN_iteratif & self_cast (const Objet_U &)
Static Public Member Functions inherited from Schema_Temps_base
static const Type_info * info ()
static Schema_Temps_base & self_cast (Objet_U &)
static const Schema_Temps_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Schema_Temps_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Types
enum type_convergence {
DIVERGENCE , NON_CONVERGENCE , CONVERGENCE_LENTE , CONVERGENCE_RAPIDE ,
CONVERGENCE_OK
}
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Entree & readOn (Entree &) override
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
virtual bool convergence (const DoubleTab &u0, const DoubleTab &up1, const DoubleTab &delta, int p) const
Indique si le calcul iteratif a converge.
Critere de convergence utilise :
|| u(n+1,p+1) - u(n+1,p) || < seuil * || u(n+1/2,p+1) ||
C'est equivalent a
|| u(n+1,p) - u(n+1) || < seuil * || (Id-(dt/2).(df/du))^-1 || * || u(n+1/2,p+1) ||
ou u(n+1) est la solution exacte en n+1,
df/du est le lagrangien de f(u), pris en u(n+1/2)
et les normes sont compatibles entre matrices et vecteurs (ici norme infinie).
virtual bool divergence (const DoubleTab &u0, const DoubleTab &up1, const DoubleTab &delta, int p) const
Indique si le calcul iteratif a diverge.
virtual void ajuster_facsec (type_convergence cv)
virtual bool iterateTimeStepOnEquation (int i, bool &converged)
Calcule une iteration de la resolution sur l'equation i.
Calcule u(n+1/2,p+1)=u(n)+f(u(n+1/2,p))*dt/2
et u(n+1,p+1)=u(n)+f(u(n+1/2,p))*dt
ou f donne du/dt en fonction de u
Retourne true dans converged si ca ne bouge plus d'une iteration a l'autre, false sinon
Renvoie true si OK pour continuer a iterer, false sinon (diverge ou trop d'iterations)
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Entree & readOn (Entree &) override
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double seuil
To determine convergence.
int niter_min
Minimum number of iterations (before, continue to iterate)
int niter_max
Maximum number of iterations (after, considered as not convergent)
int niter_avg
Average number of iterations wanted (facsec adjusted to fit that number)
double facsec_max
Maximum facsec (not to miss the physics)
int iteration
Number of iterations done for the current time step.
double last_facsec
facsec at the beginning of time step resolution, to avoid changing facsec several times for the same time step.
Protected Attributes inherited from Schema_Temps_base
Ref_Probleme_base mon_probleme
Nom nom_
double dt_
Pas de temps de calcul.
DoubleTab dt_locaux_
Local time steps: Vector of size nb faces of the mesh.
double temps_courant_
double temps_precedent_
double dt_failed_
double dt_gf_
double tinit_
double tmax_
double tcpumax_
int nb_pas_dt_
int nb_pas_dt_max_
int nb_impr_
double dt_min_
Pas de temps min fixe par l'utilisateur.
double dt_max_
Pas de temps max fixe par l'utilisateur.
Nom dt_max_str_
Parser_U dt_max_fn_
double dt_stab_
Pas de temps de stabilite.
double facsec_
double seuil_statio_
int seuil_statio_relatif_deconseille_
Drapeau pour specifier si seuil_statio_ est une valeur absolue (defaut) ou relative.
double dt_sauv_
double limite_cpu_sans_sauvegarde_
double periode_cpu_sans_sauvegarde_
double temps_cpu_ecoule_
double dt_impr_
Pas de temps d'impression.
int precision_impr_
Nombre de chiffres significatifs impression.
double mode_dt_start_
mode calcul du pas de temps de depart
double residu_
Residu.
double residu_old_slope_
double cumul_slope_
int gnuplot_header_
int ind_tps_final_atteint
int ind_nb_pas_dt_max_atteint
int ind_temps_cpu_max_atteint
int lu_
int ind_diff_impl_
double seuil_diff_impl_
int impr_diff_impl_
int impr_extremums_
int niter_max_diff_impl_
int no_conv_subiteration_diff_impl_
int no_error_if_not_converged_diff_impl_
int schema_impr_
1 si le schema a le droit d'imprimer dans le .out et dt_ev
int file_allocation_
1 = allocation espace disque (par defaut), 0 sinon
int max_length_cl_
Detailed Description
classe Sch_CN_iteratif
Schema en temps alternant un demi-pas de temps d'Euler implicite et un demi-pas de temps de LeapFrog.
La resolution implicite est iterative (point fixe).
Le pas de temps est calcule comme le produit du pas de temps de stabilite explicite par un facsec.
Le facsec est ajuste automatiquement pour que la resolution converge en un nombre d'iterations predefini.
Les caracteristiques de chaque iteration sont ecrites dans le fichier dt_CN.
La resolution est gouvernee par 4 parametres (valeurs par defauts entre parentheses) :
* seuil (1e-3) : le seuil de convergence. Plus il est bas, plus la resolution est precise.
* facsec_max (2) : la valeur du facsec que l'on ne veut pas depasser (eviter les instabilites et capter les phenomenes physiques)
* niter_min (2) : le nombre minimum d'iterations. En deca, on continue a iterer meme si on semble avoir atteint la convergence.
* niter_avg (3) : le nombre d'iterations que l'on souhaite faire pour arriver a convergence.
* niter_max (6) : le nombre d'iteration au-dela duquel on reessaye avec un facsec plus petit.
Conseil pour le choix des parametres d'ajustement du facsec :
* Choisir seuil en fonction de la precision desiree.
* Choisir niter_min : 2 garantit un schema d'ordre 2 en temps.
* Si on cherche un stationnaire, choisir seuil_statio >= seuil.
* Choisir facsec_max en fonction des phenomenes physiques a capter.
* Commencer par tester avec une grande valeur de niter_avg. Observer le comportement du nombre d'iterations.
Il bute sur une valeur maximum avant de retomber.
* Choisir niter_avg aux 2/3 de cette valeur maximum, et niter_max aux 4/3 ou au double environ.
Definition at line 51 of file Sch_CN_iteratif.h.
Member Enumeration Documentation
type_convergence
enum Sch_CN_iteratif::type_convergence protected
Enumerator
DIVERGENCE
NON_CONVERGENCE
CONVERGENCE_LENTE
CONVERGENCE_RAPIDE
CONVERGENCE_OK
Definition at line 84 of file Sch_CN_iteratif.h.
{DIVERGENCE, NON_CONVERGENCE, CONVERGENCE_LENTE, CONVERGENCE_RAPIDE, CONVERGENCE_OK};
Constructor & Destructor Documentation
Sch_CN_iteratif()
Sch_CN_iteratif::Sch_CN_iteratif ()
Definition at line 25 of file Sch_CN_iteratif.cpp.
~Sch_CN_iteratif()
Sch_CN_iteratif::~Sch_CN_iteratif ()
Definition at line 25 of file Sch_CN_iteratif.cpp.
Member Function Documentation
ajuster_facsec()
void Sch_CN_iteratif::ajuster_facsec (type_convergence cv) protected virtual
< On n'ajuste qu'une fois pour un initTimeStep.
Reimplemented in Sch_CN_EX_iteratif.
Definition at line 47 of file Sch_CN_iteratif.cpp.
{
  if (facsec_!=last_facsec) //!< On n'ajuste qu'une fois pour un initTimeStep.
    return;
  switch (cv)
    {
    case DIVERGENCE:
// le critere de divergence a ete atteint
      facsec_=last_facsec*0.8;
      break;
    case NON_CONVERGENCE:
// ni le critere de divergence ni le critere de convergence
// n'ont ete atteints en niter_max iterations
      facsec_=last_facsec*0.9;
      break;
    case CONVERGENCE_LENTE:
// le critere de convergence a ete atteint en plus que niter_avg
// iterations
      facsec_=last_facsec*0.99;
      break;
    case CONVERGENCE_RAPIDE:
// le critere de convergence a ete atteint en moins que niter_avg
// iterations
      facsec_=last_facsec*1.01;
      break;
    case CONVERGENCE_OK:
// le critere de convergence a ete atteint en niter_avg iterations
      break;
    default:
      break;
    }
  facsec_=std::min(facsec_,facsec_max);
}
References CONVERGENCE_LENTE, CONVERGENCE_OK, CONVERGENCE_RAPIDE, DIVERGENCE, Schema_Temps_base::facsec_, facsec_max, last_facsec, and NON_CONVERGENCE.
Referenced by iterateTimeStep().
completer()
void Sch_CN_iteratif::completer (void) inline override virtual
Implements Schema_Temps_base.
Definition at line 79 of file Sch_CN_iteratif.h.
{}
convergence()
bool Sch_CN_iteratif::convergence (const DoubleTab & u0, const DoubleTab & up1, const DoubleTab & delta, int p) const protected virtual
Indique si le calcul iteratif a converge.
Critere de convergence utilise :
|| u(n+1,p+1) - u(n+1,p) || < seuil * || u(n+1/2,p+1) ||
C'est equivalent a
|| u(n+1,p) - u(n+1) || < seuil * || (Id-(dt/2).(df/du))^-1 || * || u(n+1/2,p+1) ||
ou u(n+1) est la solution exacte en n+1,
df/du est le lagrangien de f(u), pris en u(n+1/2)
et les normes sont compatibles entre matrices et vecteurs (ici norme infinie).
Returns
bool
Signification: true=converge, false=non converge
Contraintes:
< pour etre certain que tout le monde fait la meme chose
Definition at line 384 of file Sch_CN_iteratif.cpp.
{
  double a = mp_max_abs_vect(delta);
  double b = mp_max_abs_vect(up1);
  int resu = (2. * a) < (seuil * b);
  envoyer_broadcast(resu, 0); //!< pour etre certain que tout le monde fait la meme chose
  return resu;
}
References envoyer_broadcast(), mp_max_abs_vect(), and seuil.
Referenced by iterateTimeStepOnEquation(), and Sch_CN_EX_iteratif::iterateTimeStepOnNS().
cree_instance()
Objet_U * Sch_CN_iteratif::cree_instance () static
Definition at line 25 of file Sch_CN_iteratif.cpp.
divergence()
bool Sch_CN_iteratif::divergence (const DoubleTab & u0, const DoubleTab & up1, const DoubleTab & delta, int p) const protected virtual
Indique si le calcul iteratif a diverge.
Returns
bool
Signification: true=diverge, false=non diverge
Contraintes:
Definition at line 418 of file Sch_CN_iteratif.cpp.
{
// WEC : ameliorable...
  return false;
}
Referenced by iterateTimeStepOnEquation(), and Sch_CN_EX_iteratif::iterateTimeStepOnNS().
duplique()
int Sch_CN_iteratif::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file Sch_CN_iteratif.cpp.
faire_un_pas_de_temps_eqn_base()
int Sch_CN_iteratif::faire_un_pas_de_temps_eqn_base (Equation_base &) override virtual
Implements Schema_Temps_base.
Definition at line 344 of file Sch_CN_iteratif.cpp.
{
  Cerr << "Sch_CN_iteratif::faire_un_pas_de_temps_eqn_base non code!" << finl;
  exit();
  return 0;
}
References Cerr, Process::exit(), and finl.
get_info()
const Type_info * Sch_CN_iteratif::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 25 of file Sch_CN_iteratif.cpp.
info()
const Type_info * Sch_CN_iteratif::info () static
Definition at line 25 of file Sch_CN_iteratif.cpp.
initTimeStep()
bool Sch_CN_iteratif::initTimeStep (double dt) override virtual
< sinon deja appele par validateTimeStep Plus necessaire car desormais dt_ est mis a jour dans Schema_Temps_base::computeTimeStep(bool& stop) facsec_=dt/dt_;
Reimplemented from Schema_Temps_base.
Definition at line 143 of file Sch_CN_iteratif.cpp.
{
  if (nb_pas_dt()==0)
    mettre_a_jour_dt_stab(); //!< sinon deja appele par validateTimeStep Plus necessaire car desormais dt_ est mis a jour dans Schema_Temps_base::computeTimeStep(bool& stop) facsec_=dt/dt_;
//
//
  last_facsec=facsec_;
  iteration=0;
  return Schema_Temps_base::initTimeStep(dt);
}
References Schema_Temps_base::facsec_, Schema_Temps_base::initTimeStep(), iteration, last_facsec, Schema_Temps_base::mettre_a_jour_dt_stab(), and Schema_Temps_base::nb_pas_dt().
iterateTimeStep()
bool Sch_CN_iteratif::iterateTimeStep (bool & converged) override virtual
Calculate the U(n+1) unknown for each equation (if solved) of the problem with the selected time scheme.
< Continuer a iterer de toutes facons
< Convergence trop rapide, augmenter facsec
< Convergence trop lente, reduire facsec
Reimplemented from Schema_Temps_base.
Definition at line 158 of file Sch_CN_iteratif.cpp.
{
  Probleme_base& pb = pb_base();
  const int nb_eqn=pb.nombre_d_equations();
  SFichier fic;
  fic.ouvrir("dt_CN",ios::app);
  if (je_suis_maitre())
    {
      fic << "Sch_CN_iteratif : pb= " <<  pb.le_nom()
          << " present= " << temps_courant()
          << " dt= " << dt_
          << " iteration= " << iteration
          << " last_facsec= " << last_facsec;
    }
  converged=true;
  bool diverged=false;
  for(int i=0; i<nb_eqn && !diverged; i++)
    {
      bool cv;
      diverged = diverged || !iterateTimeStepOnEquation(i,cv);
      converged = converged && cv;
    }
  iteration ++;
  if (iteration<niter_min)
    converged=false; //!< Continuer a iterer de toutes facons
// Un peu de bon sens...
  assert(!(converged&&diverged));
// Si convergence
  if (converged)
    {
      if (iteration<niter_avg) //!< Convergence trop rapide, augmenter facsec
        ajuster_facsec(CONVERGENCE_RAPIDE);
      else if (iteration>niter_avg) //!< Convergence trop lente, reduire facsec
        ajuster_facsec(CONVERGENCE_LENTE);
      else
        ajuster_facsec(CONVERGENCE_OK);
      if (je_suis_maitre())
        {
          fic << " facsec= " << facsec_
              << " result= CONVERGENCE" << finl;
        }
      fic.close();
      return true;
    }
// Si divergence
  else if (diverged)
    {
      ajuster_facsec(DIVERGENCE);
      if (je_suis_maitre())
        {
          fic << " facsec= " << facsec_
              << " result= DIVERGENCE" << finl;
        }
      return false;
    }
// Si pas converge assez vite
  else if (iteration==niter_max-1)
    {
      ajuster_facsec(NON_CONVERGENCE);
      if (je_suis_maitre())
        {
          fic << " facsec= " << facsec_
              << " result= NON_CONVERGENCE" << finl;
        }
      return false;
    }
// Sinon, en cours de convergence
  if (je_suis_maitre())
    {
      fic << " facsec= " << facsec_
          << " result= CONTINUE" << finl;
    }
  return true;
}
References ajuster_facsec(), Sortie_Fichier_base::close(), CONVERGENCE_LENTE, CONVERGENCE_OK, CONVERGENCE_RAPIDE, DIVERGENCE, Schema_Temps_base::dt_, Schema_Temps_base::facsec_, finl, iterateTimeStepOnEquation(), iteration, Process::je_suis_maitre(), last_facsec, Probleme_base::le_nom(), niter_avg, niter_max, niter_min, Probleme_base::nombre_d_equations(), NON_CONVERGENCE, Sortie_Fichier_base::ouvrir(), Schema_Temps_base::pb_base(), and Schema_Temps_base::temps_courant().
iterateTimeStepOnEquation()
bool Sch_CN_iteratif::iterateTimeStepOnEquation (int i, bool & converged) protected virtual
Calcule une iteration de la resolution sur l'equation i.
Calcule u(n+1/2,p+1)=u(n)+f(u(n+1/2,p))*dt/2
et u(n+1,p+1)=u(n)+f(u(n+1/2,p))*dt
ou f donne du/dt en fonction de u
Retourne true dans converged si ca ne bouge plus d'une iteration a l'autre, false sinon
Renvoie true si OK pour continuer a iterer, false sinon (diverge ou trop d'iterations)
< delta = Contient u(n+1/2,p+1) - u(n+1/2,p)
Reimplemented in Sch_CN_EX_iteratif.
Definition at line 251 of file Sch_CN_iteratif.cpp.
{
  Probleme_base& pb = pb_base();
  Equation_base& eqn = pb.equation(i);
  if (eqn.equation_non_resolue())
    {
      Cout<< "====================================================" << finl;
      Cout<< eqn.que_suis_je()<<" equation is not solved."<<finl;
      Cout<< "====================================================" << finl;
// On calcule une fois la derivee pour avoir les flux bord
      if (eqn.schema_temps().nb_pas_dt()==0)
        {
          DoubleTab inconnue_valeurs(eqn.inconnue().valeurs());
          eqn.derivee_en_temps_inco(inconnue_valeurs);
        }
      converged=true;
      return true;
    }
  double temps_intermediaire=temps_futur(1);
  double temps_final=temps_futur(2);
  double dt_intermediaire=temps_intermediaire-temps_courant();
  double dt_final=temps_final-temps_courant();
  DoubleTab& present = eqn.inconnue().valeurs();
  DoubleTab& intermediaire = eqn.inconnue()->valeurs(temps_intermediaire);
  DoubleTab& final = eqn.inconnue()->valeurs(temps_final);
  DoubleTab dudt(present);
  DoubleTab delta(intermediaire);
  delta*=-1;
// On impose les CLs Dirichlet au temps intermediaire.
// En effet, les operateurs de diffusion n'utilisent que
// l'inconnue et ne vont pas lire les CLs.
// Cela permet en particulier d'avoir l'egalite des flux en pb
// couple thermique VEF avec Chap_front_contact_VEF, meme avant convergence.
// WEC :  /!\ la vitesse au temps intermediaire
// n'est pas forcement a divergence nulle.
  eqn.zone_Cl_dis()->imposer_cond_lim(eqn.inconnue(),temps_intermediaire);
// Calcul de la derivee dudt pour la valeur intermediaire de l'inconnue.
// Bidouille : Comme les operateurs prennent par defaut le present,
// on avance temporairement l'inconnue.
  eqn.inconnue().avancer();
  eqn.derivee_en_temps_inco(dudt);
  eqn.inconnue().reculer();
// Mise a jour des valeurs de l'inconnue aux temps intermediaire et final
// intermediaire = present + dt_intermediaire * dudt;
// final =  present + dt_final * dudt;
  intermediaire = dudt;
  intermediaire*= dt_intermediaire;
  intermediaire+= present;
  eqn.zone_Cl_dis().imposer_cond_lim(eqn.inconnue(),temps_intermediaire);
  intermediaire.echange_espace_virtuel();
  final = dudt;
  final*= dt_final;
  final+= present;
  eqn.zone_Cl_dis().imposer_cond_lim(eqn.inconnue(),temps_final);
  final.echange_espace_virtuel();
  delta+=intermediaire; //!< delta = Contient u(n+1/2,p+1) - u(n+1/2,p)
// Si l'equation a diverge
  if (divergence(present,intermediaire,delta,iteration))
    {
      converged=false;
      return false;
    }
// Si l'equation a converge
  if (convergence(present,intermediaire,delta,iteration))
    {
      converged=true;
      delta=final;
      delta-=present;
      delta/=dt_final;
      update_critere_statio(delta, eqn);
    }
  else
    {
      set_stationnaire_atteint()=0;
      converged=false;
    }
  return true;
}
References Champ_Inc::avancer(), convergence(), Cout, Equation_base::derivee_en_temps_inco(), divergence(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Probleme_base::equation(), Equation_base::equation_non_resolue(), finl, Zone_Cl_dis::imposer_cond_lim(), Equation_base::inconnue(), iteration, Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::pb_base(), Objet_U::que_suis_je(), Champ_Inc::reculer(), Equation_base::schema_temps(), Schema_Temps_base::set_stationnaire_atteint(), Schema_Temps_base::temps_courant(), temps_futur(), Schema_Temps_base::update_critere_statio(), Champ_Inc::valeurs(), and Equation_base::zone_Cl_dis().
Referenced by iterateTimeStep().
nb_valeurs_futures()
int Sch_CN_iteratif::nb_valeurs_futures () const override virtual
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1/2 et n+1 donc 2.
Implements Schema_Temps_base.
Definition at line 112 of file Sch_CN_iteratif.cpp.
{
  return 2;
}
nb_valeurs_temporelles()
int Sch_CN_iteratif::nb_valeurs_temporelles () const override virtual
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n, n+1/2 et n+1, donc 3.
Implements Schema_Temps_base.
Definition at line 104 of file Sch_CN_iteratif.cpp.
{
  return 3;
}
printOn()
Sortie & Sch_CN_iteratif::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 28 of file Sch_CN_iteratif.cpp.
{
  return  Schema_Temps_base::printOn(s);
}
References Schema_Temps_base::printOn().
Referenced by Sch_CN_EX_iteratif::printOn().
readOn()
Entree & Sch_CN_iteratif::readOn (Entree & is) override protected virtual
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 34 of file Sch_CN_iteratif.cpp.
{
  seuil=1.e-3;
  niter_min=2;
  niter_max=6;
  niter_avg=3;
  facsec_max=2;
  Schema_Temps_base::readOn(s) ;
  return s;
}
References facsec_max, niter_avg, niter_max, niter_min, Schema_Temps_base::readOn(), and seuil.
self_cast() [1/2]
const Sch_CN_iteratif & Sch_CN_iteratif::self_cast (const Objet_U & r) static
Definition at line 25 of file Sch_CN_iteratif.cpp.
self_cast() [2/2]
Sch_CN_iteratif & Sch_CN_iteratif::self_cast (Objet_U & r) static
Definition at line 25 of file Sch_CN_iteratif.cpp.
set_param()
void Sch_CN_iteratif::set_param (Param & titi) override virtual
Reimplemented from Schema_Temps_base.
Definition at line 82 of file Sch_CN_iteratif.cpp.
{
  param.ajouter("seuil",&seuil);
  param.ajouter("niter_min",&niter_min);
  param.ajouter("niter_max",&niter_max);
  param.ajouter("niter_avg",&niter_avg);
  param.ajouter("facsec_max",&facsec_max);
  Schema_Temps_base::set_param(param);
}
References Param::ajouter(), facsec_max, niter_avg, niter_max, niter_min, Schema_Temps_base::set_param(), and seuil.
Referenced by Sch_CN_EX_iteratif::set_param().
taille_memoire()
unsigned Sch_CN_iteratif::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file Sch_CN_iteratif.cpp.
temps_defaut()
double Sch_CN_iteratif::temps_defaut () const override virtual
Renvoie le temps que doivent utiliser les champs a
l'appel de valeurs()
Ici : t(n+1/2)
Implements Schema_Temps_base.
Definition at line 132 of file Sch_CN_iteratif.cpp.
{
  return temps_futur(1);
}
References temps_futur().
temps_futur()
double Sch_CN_iteratif::temps_futur (int i) const override virtual
Renvoie le le temps a la i-eme valeur future.
Implements Schema_Temps_base.
Definition at line 119 of file Sch_CN_iteratif.cpp.
{
  assert(i>0 && i<=2);
  if (i==2)
    return temps_courant()+pas_de_temps();
  else
    return temps_courant()+pas_de_temps()/2;
}
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
Referenced by iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), and temps_defaut().
Member Data Documentation
facsec_max
double Sch_CN_iteratif::facsec_max protected
Maximum facsec (not to miss the physics)
Definition at line 96 of file Sch_CN_iteratif.h.
Referenced by ajuster_facsec(), Sch_CN_EX_iteratif::ajuster_facsec(), Sch_CN_EX_iteratif::readOn(), readOn(), and set_param().
info_obj
const Type_info Sch_CN_iteratif::info_obj static
Definition at line 53 of file Sch_CN_iteratif.h.
iteration
int Sch_CN_iteratif::iteration protected
Number of iterations done for the current time step.
Definition at line 99 of file Sch_CN_iteratif.h.
Referenced by initTimeStep(), iterateTimeStep(), iterateTimeStepOnEquation(), and Sch_CN_EX_iteratif::iterateTimeStepOnNS().
last_facsec
double Sch_CN_iteratif::last_facsec protected
facsec at the beginning of time step resolution, to avoid changing facsec several times for the same time step.
Definition at line 100 of file Sch_CN_iteratif.h.
Referenced by ajuster_facsec(), Sch_CN_EX_iteratif::ajuster_facsec(), initTimeStep(), and iterateTimeStep().
niter_avg
int Sch_CN_iteratif::niter_avg protected
Average number of iterations wanted (facsec adjusted to fit that number)
Definition at line 95 of file Sch_CN_iteratif.h.
Referenced by iterateTimeStep(), Sch_CN_EX_iteratif::readOn(), readOn(), and set_param().
niter_max
int Sch_CN_iteratif::niter_max protected
Maximum number of iterations (after, considered as not convergent)
Definition at line 94 of file Sch_CN_iteratif.h.
Referenced by iterateTimeStep(), Sch_CN_EX_iteratif::readOn(), readOn(), and set_param().
niter_min
int Sch_CN_iteratif::niter_min protected
Minimum number of iterations (before, continue to iterate)
Definition at line 93 of file Sch_CN_iteratif.h.
Referenced by iterateTimeStep(), Sch_CN_EX_iteratif::readOn(), readOn(), and set_param().
seuil
double Sch_CN_iteratif::seuil protected
To determine convergence.
Definition at line 92 of file Sch_CN_iteratif.h.
Referenced by convergence(), Sch_CN_EX_iteratif::readOn(), readOn(), and set_param().
The documentation for this class was generated from the following files:
src/ThHyd/Schemas_Temps/Sch_CN_iteratif.h
src/ThHyd/Schemas_Temps/Sch_CN_iteratif.cpp