TRUST: Matrice_Sym Class Reference
Matrice_Sym Class Reference abstract
Classe Matrice_Sym
Cette classe est la classe de base pour la representantion des
matrices symetriques. Cette classe est en fait une classe "interface"
qui donne acces a des methodes de resolutions de systemes lineaires
dont la matrice est symetrique: Gradient conjugue (preconditionne),
solveur SSOR, precondtionneur polynomial.
Cette classe ne contient pas de membre de donnee (hors mis ceux herites de
Process) car elle sera utilisee par heritage multiple.
Elle "accede" a la matrice via la methode de multiplication matrice-vecteur
DoubleVect& multvect(const DoubleVect&, DoubleVect& resu) const
qui est une methode abstraite.
#include <Matrice_Sym.h>
Public Member Functions
virtual ~Matrice_Sym ()
Matrice_Sym ()
int get_est_definie () const
void set_est_definie (int)
void unsymmetrize_stencil (const int nb_lines, const IntTab &symmetric_stencil, IntTab &stencil) const
void unsymmetrize_stencil_and_coefficients (const int nb_lines, const IntTab &symmetric_stencil, const ArrOfDouble &symmetric_coefficients, IntTab &stencil, ArrOfDouble &coefficients) const
Protected Member Functions
virtual DoubleTab & ajouter_multTab_ (const DoubleTab &, DoubleTab &) const =0
virtual DoubleVect & ajouter_multvect_ (const DoubleVect &, DoubleVect &) const =0
virtual DoubleVect & ajouter_multvectT_ (const DoubleVect &, DoubleVect &) const =0
Private Attributes
int est_definie_
Detailed Description
Classe Matrice_Sym
Cette classe est la classe de base pour la representantion des
matrices symetriques. Cette classe est en fait une classe "interface"
qui donne acces a des methodes de resolutions de systemes lineaires
dont la matrice est symetrique: Gradient conjugue (preconditionne),
solveur SSOR, precondtionneur polynomial.
Cette classe ne contient pas de membre de donnee (hors mis ceux herites de
Process) car elle sera utilisee par heritage multiple.
Elle "accede" a la matrice via la methode de multiplication matrice-vecteur
DoubleVect& multvect(const DoubleVect&, DoubleVect& resu) const
qui est une methode abstraite.
Definition at line 50 of file Matrice_Sym.h.
Constructor & Destructor Documentation
~Matrice_Sym()
virtual Matrice_Sym::~Matrice_Sym () inline virtual
Definition at line 53 of file Matrice_Sym.h.
{};
Matrice_Sym()
Matrice_Sym::Matrice_Sym () inline
Definition at line 54 of file Matrice_Sym.h.
:est_definie_(0) {}
Member Function Documentation
ajouter_multTab_()
virtual DoubleTab & Matrice_Sym::ajouter_multTab_ (const DoubleTab & , DoubleTab &) const protected pure virtual
Implemented in Matrice_Morse_Diag, Matrice_Morse_Sym, and Matrice_Bloc_Sym.
ajouter_multvect_()
virtual DoubleVect & Matrice_Sym::ajouter_multvect_ (const DoubleVect & , DoubleVect &) const protected pure virtual
Implemented in Matrice_Morse_Sym, Matrice_Bloc_Sym, and Matrice_Morse_Diag.
ajouter_multvectT_()
virtual DoubleVect & Matrice_Sym::ajouter_multvectT_ (const DoubleVect & , DoubleVect &) const protected pure virtual
Implemented in Matrice_Morse_Diag, Matrice_Morse_Sym, and Matrice_Bloc_Sym.
get_est_definie()
int Matrice_Sym::get_est_definie () const
Definition at line 20 of file Matrice_Sym.cpp.
{
  return est_definie_;
}
References est_definie_.
Referenced by Assembleur_P_EF::assembler_QC(), Assembleur_P_PolyMAC::assembler_QC(), Assembleur_P_VDF::assembler_QC(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Solv_Cholesky::Cholesky(), Matrice_Morse_Sym::Matrice_Morse_Sym(), Assembleur_P_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), Matrice_Morse_Sym::operator=(), Precond_local::prepare_(), Matrice_Morse_Sym::printOn(), Precond_local::res_syst_loc_hybride(), Precond_local::res_syst_loc_simple(), and Solv_Petsc::resoudre_systeme().
set_est_definie()
void Matrice_Sym::set_est_definie (int val)
Definition at line 25 of file Matrice_Sym.cpp.
{
  est_definie_ = val;
}
References est_definie_.
Referenced by assembler(), Assembleur_P_EF::assembler_mat(), Assembleur_P_EF::assembler_QC(), Assembleur_P_PolyMAC::assembler_QC(), Assembleur_P_VDF::assembler_QC(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), construire_matrice_implicite(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Matrice_Morse_Sym::Matrice_Morse_Sym(), Assembleur_P_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), Matrice_Morse_Sym::operator=(), Precond_local::prepare_(), Matrice_Morse_Sym::readOn(), Assembleur_P_VEF::remplir(), Precond_local::res_syst_loc_hybride(), and Precond_local::res_syst_loc_simple().
unsymmetrize_stencil()
void Matrice_Sym::unsymmetrize_stencil (const int nb_lines, const IntTab & symmetric_stencil, IntTab & stencil) const
Definition at line 30 of file Matrice_Sym.cpp.
{
  ArrOfInt offsets( nb_lines + 1 );
  offsets[ 0 ] = 0;
  const int symmetric_stencil_size = symmetric_stencil.dimension( 0 );
  for ( int k=0; k<symmetric_stencil_size; ++k )
    {
      const int line   = symmetric_stencil( k, 0 );
      const int column = symmetric_stencil( k, 1 );
      offsets[ line   + 1 ] += 1;
      offsets[ column + 1 ] += ( line == column ) ? 0 : 1 ;
    }
  for ( int i=0; i<nb_lines; ++i )
    {
      offsets[ i + 1 ] += offsets[ i ];
    }
  const int stencil_size = offsets[ nb_lines ];
  stencil.resize( stencil_size, 2 );
  stencil = -1;
  int index;
  for ( int k=0; k<symmetric_stencil_size; ++k )
    {
      const int line   = symmetric_stencil( k, 0 );
      const int column = symmetric_stencil( k, 1 );
      index = offsets[ line ];
      assert( stencil( index, 0 ) < 0 );
      assert( stencil( index, 1 ) < 0 );
      assert( index < offsets[ line + 1 ] );
      stencil( index, 0 ) = line;
      stencil( index, 1 ) = column;
      offsets[ line ] += 1;
      if ( line != column )
        {
          index = offsets[ column ];
          assert( stencil( index, 0 ) < 0 );
          assert( stencil( index, 1 ) < 0 );
          assert( index < offsets[ column + 1 ] );
          stencil( index, 0 ) = column;
          stencil( index, 1 ) = line;
          offsets[ column ] += 1;
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), and TRUSTTab< _TYPE_ >::resize().
Referenced by Matrice_Bloc_Sym::get_stencil(), and Matrice_Morse_Sym::get_stencil().
unsymmetrize_stencil_and_coefficients()
void Matrice_Sym::unsymmetrize_stencil_and_coefficients (const int nb_lines, const IntTab & symmetric_stencil, const ArrOfDouble & symmetric_coefficients, IntTab & stencil, ArrOfDouble & coefficients) const
Definition at line 91 of file Matrice_Sym.cpp.
{
  ArrOfInt offsets( nb_lines + 1 );
  offsets[ 0 ] = 0;
  const int symmetric_stencil_size = symmetric_stencil.dimension( 0 );
  assert( symmetric_stencil_size == symmetric_coefficients.size_array( ) );
  for ( int k=0; k<symmetric_stencil_size; ++k )
    {
      const int line   = symmetric_stencil( k, 0 );
      const int column = symmetric_stencil( k, 1 );
      offsets[ line   + 1 ] += 1;
      offsets[ column + 1 ] += ( line == column ) ? 0 : 1 ;
    }
  for ( int i=0; i<nb_lines; ++i )
    {
      offsets[ i + 1 ] += offsets[ i ];
    }
  const int stencil_size = offsets[ nb_lines ];
  stencil.resize( stencil_size, 2 );
  coefficients.resize_array( stencil_size );
  stencil = -1;
  int index;
  for ( int k=0; k<symmetric_stencil_size; ++k )
    {
      const int line        = symmetric_stencil( k, 0 );
      const int column      = symmetric_stencil( k, 1 );
      const double coefficient = symmetric_coefficients[ k ];
      index = offsets[ line ];
      assert( stencil( index, 0 ) < 0 );
      assert( stencil( index, 1 ) < 0 );
      assert( index < offsets[ line + 1 ] );
      stencil( index, 0 )   = line;
      stencil( index, 1 )   = column;
      coefficients[ index ] = coefficient;
      offsets[ line ] += 1;
      if ( line != column )
        {
          index = offsets[ column ];
          assert( stencil( index, 0 ) < 0 );
          assert( stencil( index, 1 ) < 0 );
          assert( index < offsets[ column + 1 ] );
          stencil( index, 0 )   = column;
          stencil( index, 1 )   = line;
          coefficients[ index ] = coefficient;
          offsets[ column ] += 1;
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Matrice_Bloc_Sym::get_stencil_and_coefficients(), and Matrice_Morse_Sym::get_stencil_and_coefficients().
Member Data Documentation
est_definie_
int Matrice_Sym::est_definie_ private
Definition at line 67 of file Matrice_Sym.h.
Referenced by get_est_definie(), and set_est_definie().
The documentation for this class was generated from the following files:
src/Kernel/Math/Matrices/Matrice_Sym.h
src/Kernel/Math/Matrices/Matrice_Sym.cpp