TRUST: Traitement_particulier_NS_chmoy_faceperio_VEF Class Reference
Traitement_particulier_NS_chmoy_faceperio_VEF Class Reference
classe Traitement_particulier_NS_chmoy_faceperio_VEF
Cette classe permet de faire les traitements particuliers
pour le calcul d'un canal plan :
* conservation du debit
* calculs de moyennes
#include <Traitement_particulier_NS_chmoy_faceperio_VEF.h>
Public Member Functions
Traitement_particulier_NS_chmoy_faceperio_VEF ()
~Traitement_particulier_NS_chmoy_faceperio_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Traitement_particulier_NS_chmoy_faceperio
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
~Traitement_particulier_NS_chmoy_faceperio () override
Traitement_particulier_NS_chmoy_faceperio ()
Entree & lire (Entree &) override
void preparer_calcul_particulier (void) override
void post_traitement_particulier (void) override
void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double) override
void sauver_stat (void) const override
void reprendre_stat (void) override
Public Member Functions inherited from Traitement_particulier_NS_base
Traitement_particulier_NS_base ()
~Traitement_particulier_NS_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_eqn (const Equation_base &)
virtual void preparer_calcul_particulier (void)=0
virtual void post_traitement_particulier (void)=0
virtual Entree & lire (Entree &is)=0
virtual void sauver_stat (void) const =0
virtual void reprendre_stat (void)=0
virtual void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double)=0
void creer_champ (const Motcle &) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Traitement_particulier_NS_chmoy_faceperio_VEF & self_cast (Objet_U &)
static const Traitement_particulier_NS_chmoy_faceperio_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_chmoy_faceperio
static const Type_info * info ()
static Traitement_particulier_NS_chmoy_faceperio & self_cast (Objet_U &)
static const Traitement_particulier_NS_chmoy_faceperio & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_base
static const Type_info * info ()
static Traitement_particulier_NS_base & self_cast (Objet_U &)
static const Traitement_particulier_NS_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_chmoy_faceperio
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void init_calcul_stats (void) override
void calcul_chmoy_faceperio (double, double, double) override
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual void init_calcul_stats ()=0
virtual void calcul_chmoy_faceperio (double, double, double)=0
Sortie & printOn (Sortie &x) const override
Impression de l'equation sur un flot de sortie.
Simple appel a Equation_base::printOn(Sortie&).
Entree & readOn (Entree &) override
Lit les specifications de l'equation de Navier Stokes a
partir d'un flot d'entree.
Simple appel a Navier_Stokes_std::readOn(Entree&)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Additional Inherited Members
Protected Attributes inherited from Traitement_particulier_NS_chmoy_faceperio
DoubleTab chmoy_faceperio
double temps_deb
double temps_fin
int oui_stat
SFichier * le_fichier
Protected Attributes inherited from Traitement_particulier_NS_base
Ref_Navier_Stokes_std mon_equation
Champs_compris champs_compris_
Detailed Description
classe Traitement_particulier_NS_chmoy_faceperio_VEF
Cette classe permet de faire les traitements particuliers
pour le calcul d'un canal plan :
* conservation du debit
* calculs de moyennes
Definition at line 36 of file Traitement_particulier_NS_chmoy_faceperio_VEF.h.
Constructor & Destructor Documentation
Traitement_particulier_NS_chmoy_faceperio_VEF()
Traitement_particulier_NS_chmoy_faceperio_VEF::Traitement_particulier_NS_chmoy_faceperio_VEF ()
Definition at line 26 of file Traitement_particulier_NS_chmoy_faceperio_VEF.cpp.
~Traitement_particulier_NS_chmoy_faceperio_VEF()
Traitement_particulier_NS_chmoy_faceperio_VEF::~Traitement_particulier_NS_chmoy_faceperio_VEF ()
Definition at line 26 of file Traitement_particulier_NS_chmoy_faceperio_VEF.cpp.
Member Function Documentation
calcul_chmoy_faceperio()
void Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio (double un_temps_deb, double temps, double dt) override protected virtual
Implements Traitement_particulier_NS_chmoy_faceperio.
Definition at line 102 of file Traitement_particulier_NS_chmoy_faceperio_VEF.cpp.
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VEF& zone_VEF=ref_cast(Zone_VEF, zdisbase);
  const Zone_Cl_VEF& zone_Cl_VEF = ref_cast(Zone_Cl_VEF,mon_equation->zone_Cl_dis().valeur() );
  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
// Calcul de la moyenne temporelle de la vitesse sur les frontieres periodiques:
// moy(U)=1/(temps-temps_deb)*Integrale(t=temps_deb a temps)(U(t)*dt)
  chmoy_faceperio*=(temps-un_temps_deb-dt);
  int test_proc=0;
  int nb_front=zone_VEF.nb_front_Cl();
  for (int n_bord=0; n_bord<nb_front; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          for (int num_face=num1; num_face<num2; num_face++)
            {
              for(int i=0; i<Objet_U::dimension; i++)
                chmoy_faceperio(num_face,i)+=dt*vitesse(num_face,i);
              test_proc=1;
            }
        }
    }
  chmoy_faceperio/=(temps-un_temps_deb);
  if (test_proc)
    {
      EcrFicPartage fic("chmoy_face_perio");
      fic.setf(ios::scientific);
      fic.precision(format_precision_geom);
      for (int n_bord=0; n_bord<nb_front; n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          if (sub_type(Periodique,la_cl.valeur()))
            {
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              int num1 = le_bord.num_premiere_face();
              int num2 = num1 + le_bord.nb_faces();
              int nb_faces_bord = mp_sum(le_bord.nb_faces());
              if (Process::je_suis_maitre()) fic<<nb_faces_bord<<finl;
              for (int num_face=num1; num_face<num2; num_face++)
                fic<<num_face<<" "<<chmoy_faceperio(num_face,0)<<" "<<chmoy_faceperio(num_face,1)<<" "<<chmoy_faceperio(num_face,2)<<finl;
            }
        }
      fic.syncfile();
      fic.close();
    }
}
References Traitement_particulier_NS_chmoy_faceperio::chmoy_faceperio, EcrFicPartage::close(), Objet_U::dimension, finl, Objet_U::format_precision_geom, Cond_lim::frontiere_dis(), Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Zone_Cl_dis_base::les_conditions_limites(), Traitement_particulier_NS_base::mon_equation, Process::mp_sum(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), EcrFicPartage::precision(), ref_cast, Sortie_Fichier_base::setf(), sub_type, EcrFicPartage::syncfile(), Deriv_Cond_lim_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Champ_Inc::valeurs(), Equation_base::zone_Cl_dis(), and Champ_Inc::zone_dis_base().
cree_instance()
Objet_U * Traitement_particulier_NS_chmoy_faceperio_VEF::cree_instance () static
Definition at line 26 of file Traitement_particulier_NS_chmoy_faceperio_VEF.cpp.
duplique()
int Traitement_particulier_NS_chmoy_faceperio_VEF::duplique () const override virtual
Implements Objet_U.
Definition at line 26 of file Traitement_particulier_NS_chmoy_faceperio_VEF.cpp.
get_info()
const Type_info * Traitement_particulier_NS_chmoy_faceperio_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Traitement_particulier_NS_chmoy_faceperio.
Definition at line 26 of file Traitement_particulier_NS_chmoy_faceperio_VEF.cpp.
info()
const Type_info * Traitement_particulier_NS_chmoy_faceperio_VEF::info () static
Definition at line 26 of file Traitement_particulier_NS_chmoy_faceperio_VEF.cpp.
init_calcul_stats()
void Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats (void) override protected virtual
< centre de gravite des faces Imprime dans un fichier les faces periodiques (numero+coordonnees du centre)
Implements Traitement_particulier_NS_chmoy_faceperio.
Definition at line 68 of file Traitement_particulier_NS_chmoy_faceperio_VEF.cpp.
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VEF& zone_VEF=ref_cast(Zone_VEF, zdisbase);
  const Zone_Cl_VEF& zone_Cl_VEF = ref_cast(Zone_Cl_VEF,mon_equation->zone_Cl_dis().valeur() );
  const DoubleTab& xv = zone_VEF.xv();    //!< centre de gravite des faces Imprime dans un fichier les faces periodiques (numero+coordonnees du centre)
//
  int nb_front=zone_VEF.nb_front_Cl();
  for (int n_bord=0; n_bord<nb_front; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          if (le_bord.nb_faces())
            {
              chmoy_faceperio.resize(le_bord.nb_faces(),Objet_U::dimension);
              chmoy_faceperio=0.;
              EcrFicPartage fic("geom_face_perio");
              fic.setf(ios::scientific);
              fic.precision(format_precision_geom);
              int nb_faces_bord = mp_sum(le_bord.nb_faces());
              if (Process::je_suis_maitre()) fic<<nb_faces_bord<<finl;
              int num1 = le_bord.num_premiere_face();
              int num2 = num1 + le_bord.nb_faces();
              for (int num_face=num1; num_face<num2; num_face++)
                fic<<num_face<<" "<<xv(num_face,0)<<" "<<xv(num_face,1)<<" "<<xv(num_face,2)<<finl;
              fic.syncfile();
              fic.close();
            }
        }
    }
}
References Traitement_particulier_NS_chmoy_faceperio::chmoy_faceperio, EcrFicPartage::close(), Objet_U::dimension, finl, Objet_U::format_precision_geom, Cond_lim::frontiere_dis(), Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Zone_Cl_dis_base::les_conditions_limites(), Traitement_particulier_NS_base::mon_equation, Process::mp_sum(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), EcrFicPartage::precision(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Sortie_Fichier_base::setf(), sub_type, EcrFicPartage::syncfile(), Deriv_Cond_lim_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Zone_VF::xv(), Equation_base::zone_Cl_dis(), and Champ_Inc::zone_dis_base().
printOn()
Sortie & Traitement_particulier_NS_chmoy_faceperio_VEF::printOn (Sortie & is) const override protected virtual
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_chmoy_faceperio.
Definition at line 43 of file Traitement_particulier_NS_chmoy_faceperio_VEF.cpp.
{
  return is;
}
readOn()
Entree & Traitement_particulier_NS_chmoy_faceperio_VEF::readOn (Entree & is) override protected virtual
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_chmoy_faceperio.
Definition at line 63 of file Traitement_particulier_NS_chmoy_faceperio_VEF.cpp.
{
  return is;
}
self_cast() [1/2]
const Traitement_particulier_NS_chmoy_faceperio_VEF & Traitement_particulier_NS_chmoy_faceperio_VEF::self_cast (const Objet_U & r) static
Definition at line 26 of file Traitement_particulier_NS_chmoy_faceperio_VEF.cpp.
self_cast() [2/2]
Traitement_particulier_NS_chmoy_faceperio_VEF & Traitement_particulier_NS_chmoy_faceperio_VEF::self_cast (Objet_U & r) static
Definition at line 26 of file Traitement_particulier_NS_chmoy_faceperio_VEF.cpp.
taille_memoire()
unsigned Traitement_particulier_NS_chmoy_faceperio_VEF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 26 of file Traitement_particulier_NS_chmoy_faceperio_VEF.cpp.
Member Data Documentation
info_obj
const Type_info Traitement_particulier_NS_chmoy_faceperio_VEF::info_obj static
Definition at line 38 of file Traitement_particulier_NS_chmoy_faceperio_VEF.h.
The documentation for this class was generated from the following files:
src/VEF/Traitement_particulier_NS_chmoy_faceperio_VEF.h
src/VEF/Traitement_particulier_NS_chmoy_faceperio_VEF.cpp