TRUST: Traitement_particulier_NS_THI Class Reference
Traitement_particulier_NS_THI Class Reference abstract
classe Traitement_particulier_THI
Cette classe permet de faire les traitements particuliers
pour les calculs de THI, en particulier initialisation
particuliere et calculs des spectres!!
#include <Traitement_particulier_NS_THI.h>
Public Member Functions
Traitement_particulier_NS_THI ()
~Traitement_particulier_NS_THI () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & lire (Entree &) override
void preparer_calcul_particulier (void) override
void post_traitement_particulier (void) override
void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double) override
void sauver_stat (void) const override
void reprendre_stat (void) override
int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
int comprend_champ (const Motcle &mot) const
Public Member Functions inherited from Traitement_particulier_NS_base
Traitement_particulier_NS_base ()
~Traitement_particulier_NS_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_eqn (const Equation_base &)
virtual void preparer_calcul_particulier (void)=0
virtual void post_traitement_particulier (void)=0
virtual Entree & lire (Entree &is)=0
virtual void sauver_stat (void) const =0
virtual void reprendre_stat (void)=0
virtual void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double)=0
void creer_champ (const Motcle &) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static const Type_info * info ()
static Traitement_particulier_NS_THI & self_cast (Objet_U &)
static const Traitement_particulier_NS_THI & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_base
static const Type_info * info ()
static Traitement_particulier_NS_base & self_cast (Objet_U &)
static const Traitement_particulier_NS_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual void renorm_Ec (void)=0
virtual void calcul_spectre_operateur (int, DoubleTab &, DoubleTab &, double)=0
virtual void init_calc_spectre (void)=0
virtual void calcul_spectre (void)=0
virtual void sorties_globales (void)=0
int & calcul_nb_som_dir (const Zone &)
int & calcul_nb_elem_dir (const Zone &)
void msg_erreur_maillage (const char *)
Sortie & printOn (Sortie &x) const override
Impression de l'equation sur un flot de sortie.
Simple appel a Equation_base::printOn(Sortie&).
Entree & readOn (Entree &) override
Lit les specifications de l'equation de Navier Stokes a
partir d'un flot d'entree.
Simple appel a Navier_Stokes_std::readOn(Entree&)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
int init
int oui_transf
int oui_calc_spectre
double Ec_init
int nb_som_dir
int nb_elem_dir
int fac_init
Protected Attributes inherited from Traitement_particulier_NS_base
Ref_Navier_Stokes_std mon_equation
Champs_compris champs_compris_
Detailed Description
classe Traitement_particulier_THI
Cette classe permet de faire les traitements particuliers
pour les calculs de THI, en particulier initialisation
particuliere et calculs des spectres!!
Definition at line 38 of file Traitement_particulier_NS_THI.h.
Constructor & Destructor Documentation
Traitement_particulier_NS_THI()
Traitement_particulier_NS_THI::Traitement_particulier_NS_THI ()
Definition at line 22 of file Traitement_particulier_NS_THI.cpp.
~Traitement_particulier_NS_THI()
Traitement_particulier_NS_THI::~Traitement_particulier_NS_THI () override
Definition at line 22 of file Traitement_particulier_NS_THI.cpp.
Member Function Documentation
a_pour_Champ_Fonc()
int Traitement_particulier_NS_THI::a_pour_Champ_Fonc (const Motcle & mot, Ref_Champ_base & ch_ref) const inline
Definition at line 81 of file Traitement_particulier_NS_THI.h.
{
  return 0 ;
}
calcul_nb_elem_dir()
int & Traitement_particulier_NS_THI::calcul_nb_elem_dir (const Zone & zone) protected
Definition at line 205 of file Traitement_particulier_NS_THI.cpp.
{
  const char* methode_actuelle="Traitement_particulier_NS_THI::calcul_nb_elem_dir";
  int nb_elem = zone.nb_elem();
// Somme sur tous les processeurs
  nb_elem=mp_sum(nb_elem);
  double nb=pow(nb_elem*1.,1./3.);
  nb_elem_dir = (int)(nb);
  if (nb_elem_dir*nb_elem_dir*nb_elem_dir != nb_elem)
    {
      nb_elem_dir=nb_elem_dir+1;
      if (nb_elem_dir*nb_elem_dir*nb_elem_dir != nb_elem)
        msg_erreur_maillage(methode_actuelle);
    }
  return nb_elem_dir;
}
References Process::mp_sum(), msg_erreur_maillage(), Zone::nb_elem(), and nb_elem_dir.
calcul_nb_som_dir()
int & Traitement_particulier_NS_THI::calcul_nb_som_dir (const Zone & zone) protected
Definition at line 183 of file Traitement_particulier_NS_THI.cpp.
{
  const char* methode_actuelle="Traitement_particulier_NS_THI::calcul_nb_som_dir";
// Sert a calculer le nombre de sommet commun en parallele
  ArrOfBit unused;
  int nb_som = MD_Vector_tools::get_sequential_items_flags(zone.domaine().les_sommets().get_md_vector(), unused);
// Somme sur tous les processeurs
  nb_som = mp_sum(nb_som);
  double nb=pow(nb_som*1.,1./3.);
  nb_som_dir = (int)(nb);
  if (nb_som_dir*nb_som_dir*nb_som_dir != nb_som)
    {
      nb_som_dir=nb_som_dir+1;
      if (nb_som_dir*nb_som_dir*nb_som_dir != nb_som)
        msg_erreur_maillage(methode_actuelle);
    }
  nb_som_dir=nb_som_dir-1;
  return nb_som_dir;
}
References Zone::domaine(), TRUSTVect< _TYPE_ >::get_md_vector(), MD_Vector_tools::get_sequential_items_flags(), Domaine::les_sommets(), Process::mp_sum(), msg_erreur_maillage(), and nb_som_dir.
calcul_spectre()
virtual void Traitement_particulier_NS_THI::calcul_spectre (void) protected pure virtual
Referenced by post_traitement_particulier(), and preparer_calcul_particulier().
calcul_spectre_operateur()
virtual void Traitement_particulier_NS_THI::calcul_spectre_operateur (int , DoubleTab & , DoubleTab & , double) protected pure virtual
Referenced by en_cours_de_resolution().
comprend_champ()
int Traitement_particulier_NS_THI::comprend_champ (const Motcle & mot) const inline
Definition at line 86 of file Traitement_particulier_NS_THI.h.
{
  return 0 ;
}
en_cours_de_resolution()
void Traitement_particulier_NS_THI::en_cours_de_resolution (int nb_op, DoubleTab & u, DoubleTab & u_av, double dt) override virtual
Implements Traitement_particulier_NS_base.
Definition at line 173 of file Traitement_particulier_NS_THI.cpp.
{
// il n'est en fait jamais appele cf. ci-dessous
  if (oui_transf == 1)
    {
      calcul_spectre_operateur( nb_op, u, u_av,dt);
    }
  return;
}
References calcul_spectre_operateur(), and oui_transf.
get_info()
const Type_info * Traitement_particulier_NS_THI::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Definition at line 22 of file Traitement_particulier_NS_THI.cpp.
info()
const Type_info * Traitement_particulier_NS_THI::info () static
Definition at line 22 of file Traitement_particulier_NS_THI.cpp.
init_calc_spectre()
virtual void Traitement_particulier_NS_THI::init_calc_spectre (void) protected pure virtual
Referenced by preparer_calcul_particulier().
lire()
Entree & Traitement_particulier_NS_THI::lire (Entree & is) override virtual
< init_Ec = 1
< on lit la valeur de Ec_init
< Sur quelle valeur se base l initialisation??
Implements Traitement_particulier_NS_base.
Definition at line 64 of file Traitement_particulier_NS_THI.cpp.
{
// valeurs par defaut
  init = 0;
  fac_init = 0;
  oui_transf = 0;
  oui_calc_spectre = 0;
// FIN valeurs par defaut
  Motcle accouverte = "{" , accfermee = "}" ;
  Motcle valec="val_Ec";
  Motcle facon="facon_init";
  Motcle motbidon, motlu;
  is >> motbidon ;
  if (motbidon == accouverte)
    {
      Motcles les_mots(2);
      {
        les_mots[0] = "init_Ec";
        les_mots[1] = "calc_spectre";
      }
      {
        is >> motlu;
        while(motlu != accfermee)
          {
            int rang=les_mots.search(motlu);
            switch(rang)
              {
              case 0 :
                {
                  is >> init;  //!< init_Ec = 1
                  if (init!=0)
                    {
                      is >> motlu;
                      if (motlu==valec)
{
                          is >> Ec_init; //!< on lit la valeur de Ec_init
                          Cerr << "Avec Initialisation de l Energie Cinetique Ec_init= " << Ec_init << finl;
                          is >> motlu;
                          if (motlu==facon)
{
                              is >> fac_init; //!< Sur quelle valeur se base l initialisation??
                              Cerr << "Avec Initialisation de l Energie Cinetique sur Ecspat (init_fac==0) ou Ecspec (init_fac==1) : fac_init=" << fac_init << finl;
                            }
                        }
                      else
{
                          Cerr << "Erreur dans la lecture de Traitement_particulier_NS_THI_VDF" << finl;
                          Cerr << "Le seul mot cle possible ici est : val_Ec" << finl;
                          Cerr << "Vous avez lu :" << motlu << finl;
                          exit();
                        }
                    }
                  break;
                }
              case 1 :
                {
                  is >> oui_calc_spectre;
                  if (oui_calc_spectre!=0) Cerr << "Calcul des spectres." << finl;
                  break;
                }
              default :
                {
                  Cerr << "Erreur dans la lecture de Traitement_particulier_NS_THI";
                  Cerr << "Les mots cles possibles sont : init_Ec, calc_spectre, { et }" << finl;
                  Cerr << "Vous avez lu :" << motlu << finl;
                  exit();
                  break;
                }
              }
            is >> motlu;
          }
        is >> motlu;
        if (motlu != accfermee)
          {
            Cerr << "Erreur dans la lecture de Traitement_particulier_NS_THI";
            Cerr << "On attendait une }" << finl;
            exit();
          }
      }
    }
  else
    {
      Cerr << "Erreur dans la lecture de Traitement_particulier_NS_THI";
      Cerr << "On attendait une {" << finl;
      exit();
    }
  return is;
}
References Cerr, Ec_init, Process::exit(), fac_init, finl, init, oui_calc_spectre, oui_transf, and Motcles::search().
msg_erreur_maillage()
void Traitement_particulier_NS_THI::msg_erreur_maillage (const char * methode_actuelle) protected
Definition at line 224 of file Traitement_particulier_NS_THI.cpp.
{
  if (je_suis_maitre())
    {
      Cerr << finl;
      Cerr << "Probleme dans " << methode_actuelle << " :" << finl;
      Cerr << "Votre maillage ne semble pas comporter le meme nombre de noeuds" << finl;
      Cerr << "suivant toutes les directions. Verifiez votre jeu de donnee... " << finl << finl;
// Abort pour les cas paralleles !
      abort();
    }
}
References Process::abort(), Cerr, finl, and Process::je_suis_maitre().
Referenced by calcul_nb_elem_dir(), and calcul_nb_som_dir().
post_traitement_particulier()
void Traitement_particulier_NS_THI::post_traitement_particulier (void) override virtual
Implements Traitement_particulier_NS_base.
Definition at line 165 of file Traitement_particulier_NS_THI.cpp.
{
  if (oui_calc_spectre != 0)
    calcul_spectre();
  sorties_globales();
}
References calcul_spectre(), oui_calc_spectre, and sorties_globales().
preparer_calcul_particulier()
void Traitement_particulier_NS_THI::preparer_calcul_particulier (void) override virtual
Implements Traitement_particulier_NS_base.
Definition at line 155 of file Traitement_particulier_NS_THI.cpp.
{
  if ((oui_calc_spectre != 0)||(fac_init!=0))
    init_calc_spectre();
  if (init==1) renorm_Ec();
  if (oui_calc_spectre != 0)
    calcul_spectre();
  sorties_globales();
}
References calcul_spectre(), fac_init, init, init_calc_spectre(), oui_calc_spectre, renorm_Ec(), and sorties_globales().
printOn()
Sortie & Traitement_particulier_NS_THI::printOn (Sortie & is) const override protected virtual
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Definition at line 39 of file Traitement_particulier_NS_THI.cpp.
{
  return is;
}
readOn()
Entree & Traitement_particulier_NS_THI::readOn (Entree & is) override protected virtual
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Definition at line 59 of file Traitement_particulier_NS_THI.cpp.
{
  return is;
}
renorm_Ec()
virtual void Traitement_particulier_NS_THI::renorm_Ec (void) protected pure virtual
Referenced by preparer_calcul_particulier().
reprendre_stat()
void Traitement_particulier_NS_THI::reprendre_stat (void) inline override virtual
Implements Traitement_particulier_NS_base.
Definition at line 76 of file Traitement_particulier_NS_THI.h.
{
  ;
}
sauver_stat()
void Traitement_particulier_NS_THI::sauver_stat (void) const inline override virtual
Implements Traitement_particulier_NS_base.
Definition at line 71 of file Traitement_particulier_NS_THI.h.
{
  ;
}
self_cast() [1/2]
const Traitement_particulier_NS_THI & Traitement_particulier_NS_THI::self_cast (const Objet_U & r) static
Definition at line 22 of file Traitement_particulier_NS_THI.cpp.
self_cast() [2/2]
Traitement_particulier_NS_THI & Traitement_particulier_NS_THI::self_cast (Objet_U & r) static
Definition at line 22 of file Traitement_particulier_NS_THI.cpp.
sorties_globales()
virtual void Traitement_particulier_NS_THI::sorties_globales (void) protected pure virtual
Referenced by post_traitement_particulier(), and preparer_calcul_particulier().
Member Data Documentation
Ec_init
double Traitement_particulier_NS_THI::Ec_init protected
Definition at line 65 of file Traitement_particulier_NS_THI.h.
Referenced by lire().
fac_init
int Traitement_particulier_NS_THI::fac_init protected
Definition at line 68 of file Traitement_particulier_NS_THI.h.
Referenced by lire(), and preparer_calcul_particulier().
info_obj
const Type_info Traitement_particulier_NS_THI::info_obj static
Definition at line 40 of file Traitement_particulier_NS_THI.h.
init
int Traitement_particulier_NS_THI::init protected
Definition at line 64 of file Traitement_particulier_NS_THI.h.
Referenced by lire(), and preparer_calcul_particulier().
nb_elem_dir
int Traitement_particulier_NS_THI::nb_elem_dir protected
Definition at line 67 of file Traitement_particulier_NS_THI.h.
Referenced by calcul_nb_elem_dir().
nb_som_dir
int Traitement_particulier_NS_THI::nb_som_dir protected
Definition at line 66 of file Traitement_particulier_NS_THI.h.
Referenced by calcul_nb_som_dir().
oui_calc_spectre
int Traitement_particulier_NS_THI::oui_calc_spectre protected
Definition at line 64 of file Traitement_particulier_NS_THI.h.
Referenced by lire(), post_traitement_particulier(), and preparer_calcul_particulier().
oui_transf
int Traitement_particulier_NS_THI::oui_transf protected
Definition at line 64 of file Traitement_particulier_NS_THI.h.
Referenced by en_cours_de_resolution(), and lire().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Traitement_particulier/Traitement_particulier_NS_THI.h
src/ThHyd/Incompressible/Traitement_particulier/Traitement_particulier_NS_THI.cpp