TRUST: Dirichlet_paroi_fixe Class Reference
Dirichlet_paroi_fixe Class Reference
classe Dirichlet_paroi_fixe
Represente une paroi immobile dans une equation de type Navier_Stokes.
#include <Dirichlet_paroi_fixe.h>
Public Member Functions
Dirichlet_paroi_fixe ()
~Dirichlet_paroi_fixe ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int compatible_avec_eqn (const Equation_base &) const
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Dirichlet_paroi_fixe sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Dirichlet_paroi_fixe & self_cast (Objet_U &)
static const Dirichlet_paroi_fixe & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a: Dirichlet_homogene::readOn(Entree&)
Detailed Description
classe Dirichlet_paroi_fixe
Represente une paroi immobile dans une equation de type Navier_Stokes.
Definition at line 43 of file Dirichlet_paroi_fixe.h.
Constructor & Destructor Documentation
Dirichlet_paroi_fixe::Dirichlet_paroi_fixe ()
Definition at line 27 of file Dirichlet_paroi_fixe.cpp.
Dirichlet_paroi_fixe::~Dirichlet_paroi_fixe ()
Definition at line 27 of file Dirichlet_paroi_fixe.cpp.
Member Function Documentation
int Dirichlet_paroi_fixe::compatible_avec_eqn (const Equation_base & eqn) const [virtual]
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Dirichlet_paroi_fixe sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
Returns:
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Implements Cond_lim_base.
Definition at line 94 of file Dirichlet_paroi_fixe.cpp.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Hydraulique  ="Hydraulique";
  Motcle Thermique    ="Thermique";
  Motcle K_Eps_V2     ="Transport_Keps_V2";
  Motcle K_Eps_Bas_Re ="Transport_Keps_Bas_Re";
  Motcle K_Eps_Rea    ="Transport_Keps_Rea";
  Motcle indetermine  ="indetermine";
  if ( (dom_app==Hydraulique) || (dom_app==indetermine) ||
       (dom_app==Thermique) || (dom_app=="Transport_Keps") || (dom_app==K_Eps_V2) || (dom_app==K_Eps_Bas_Re) || (dom_app==K_Eps_Rea) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
Objet_U * Dirichlet_paroi_fixe::cree_instance () [static]
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2.
Definition at line 27 of file Dirichlet_paroi_fixe.cpp.
int Dirichlet_paroi_fixe::duplique () const [virtual]
Implements Dirichlet_homogene.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2.
Definition at line 27 of file Dirichlet_paroi_fixe.cpp.
const Type_info * Dirichlet_paroi_fixe::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Dirichlet_homogene.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2.
Definition at line 27 of file Dirichlet_paroi_fixe.cpp.
const Type_info * Dirichlet_paroi_fixe::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Dirichlet_homogene.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2.
Definition at line 27 of file Dirichlet_paroi_fixe.cpp.
Sortie & Dirichlet_paroi_fixe::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Dirichlet_homogene.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2.
Definition at line 44 of file Dirichlet_paroi_fixe.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Dirichlet_paroi_fixe::readOn (Entree & s) [protected, virtual]
Simple appel a: Dirichlet_homogene::readOn(Entree&)
Returns:
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Dirichlet_homogene.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2.
Definition at line 64 of file Dirichlet_paroi_fixe.cpp.
References Objet_U::dimension, Field_base::fixer_nb_comp(), Cond_lim_base::le_champ_front, and Deriv_Champ_front_base::valeur().
{
  Dirichlet_homogene::readOn(s) ;
  int nb_comp = Objet_U::dimension;
  le_champ_front.valeur().fixer_nb_comp(nb_comp);
  return s;
}
const Dirichlet_paroi_fixe & Dirichlet_paroi_fixe::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Dirichlet_homogene.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2.
Definition at line 27 of file Dirichlet_paroi_fixe.cpp.
Dirichlet_paroi_fixe & Dirichlet_paroi_fixe::self_cast (Objet_U & r) [static]
Reimplemented from Dirichlet_homogene.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2.
Definition at line 27 of file Dirichlet_paroi_fixe.cpp.
unsigned Dirichlet_paroi_fixe::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2.
Definition at line 27 of file Dirichlet_paroi_fixe.cpp.
Member Data Documentation
const Type_info Dirichlet_paroi_fixe::info_obj [static]
Reimplemented from Dirichlet_homogene.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2.
Definition at line 46 of file Dirichlet_paroi_fixe.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Cond_Lim/Dirichlet_paroi_fixe.h
src/ThHyd/Incompressible/Cond_Lim/Dirichlet_paroi_fixe.cpp