TRUST: Parser_U Class Reference
Parser_U Class Reference
classe Parser_U
Version de la classe Parser, derivant de Objet_U.
Elle permet lors de son utilisation de beneficier de la gestion de la memoire propre aux Objet_U
a la difference de la classe Math/Parser
#include <Parser_U.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Parser_U ()
Parser_U (const Parser_U &)
~Parser_U () override
const Parser_U & operator= (const Parser_U &)
void parseString ()
double eval ()
void setVar (const char *sv, double val)
void setVar (const std::string &v, double val)
void setVar (int i, double val)
void setNbVar (int nvar)
void addVar (const char *v)
std::string & getString ()
void setString (const std::string &s)
void setString (const Nom &nom)
void addCst (const Constante &cst)
void setImpulsion (double tinit, double periode)
void addFunc (const UnaryFunction &f)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Parser_U & self_cast (Objet_U &)
static const Parser_U & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un Parser_U sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un Parser_U dans un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Parser * parser
Detailed Description
classe Parser_U
Version de la classe Parser, derivant de Objet_U.
Elle permet lors de son utilisation de beneficier de la gestion de la memoire propre aux Objet_U
a la difference de la classe Math/Parser
Definition at line 34 of file Parser_U.h.
Constructor & Destructor Documentation
Parser_U() [1/2]
Parser_U::Parser_U ()
Definition at line 62 of file Parser_U.cpp.
{
  parser = new Parser();
}
References parser.
Parser_U() [2/2]
Parser_U::Parser_U (const Parser_U & p)
Definition at line 68 of file Parser_U.cpp.
                                   : Objet_U(p)
{
  parser = new Parser(*(p.parser));
}
References parser.
~Parser_U()
Parser_U::~Parser_U () override
Definition at line 74 of file Parser_U.cpp.
{
  if (parser != NULL)
    delete parser;
}
References parser.
Member Function Documentation
addCst()
void Parser_U::addCst (const Constante & cst) inline
Definition at line 184 of file Parser_U.h.
{
  parser->addCst(cst);
}
References Parser::addCst(), and parser.
addFunc()
void Parser_U::addFunc (const UnaryFunction & f) inline
Definition at line 189 of file Parser_U.h.
{
  parser->addFunc(f);
}
References Parser::addFunc(), and parser.
addVar()
void Parser_U::addVar (const char * v) inline
permet d'ajouter une variable en specifiant sa chaine representative (par ex. : x, y1 etc...)
Definition at line 160 of file Parser_U.h.
{
  parser->addVar(v);
}
References Parser::addVar(), and parser.
Referenced by Param::check(), TRUSTChamp_Morceaux_generique< _TYPE_ >::complete_readOn(), create_listb_from_xyz(), create_listb_geom(), Equation_base::Equation_base(), extract_coef_local(), Extraire_surface::extraire_surface(), MaillerParallel::interpreter(), Extraire_domaine::interpreter_(), Remove_elem::interpreter_(), Perte_Charge_Singuliere::lire_donnees(), Postraitement::lire_motcle_non_standard(), Postraitement_lata::lire_motcle_non_standard(), Parametre_implicite::Parametre_implicite(), read(), Champ_front_normal::readOn(), Schema_Temps_base::readOn(), Sous_Zone::readOn(), Perte_Charge_Anisotrope_PolyMAC_Face::readOn(), Perte_Charge_Circulaire_PolyMAC_Face::readOn(), Perte_Charge_Directionnelle_PolyMAC_Face::readOn(), Perte_Charge_Isotrope_PolyMAC_Face::readOn(), Loi_Etat_rhoT_GP_QC::readOn(), Champ_front_pression_from_u::readOn(), Source_Neutronique::readOn(), Echange_contact_Correlation_VDF::readOn(), Echange_contact_Correlation_VEF::readOn(), Perte_Charge_Anisotrope_VEF_P1NC::readOn(), Perte_Charge_Circulaire_VEF_P1NC::readOn(), Perte_Charge_Directionnelle_VEF_P1NC::readOn(), Perte_Charge_Isotrope_VEF_P1NC::readOn(), Terme_Source_Rappel_T_VEF_Face::readOn(), and UserUnaryFunction::setFunction().
cree_instance()
Objet_U * Parser_U::cree_instance () static
Definition at line 18 of file Parser_U.cpp.
duplique()
int Parser_U::duplique () const override virtual
Implements Objet_U.
Definition at line 18 of file Parser_U.cpp.
eval()
double Parser_U::eval () inline
Sert a evaluer l'expression mathematique correspondante a la chaine de caracteres. Poru cela il faut avant toute chose construire l'arbre par la methode parseString().
Definition at line 118 of file Parser_U.h.
{
  return parser->eval();
}
References Parser::eval(), and parser.
Referenced by Terme_Source_Rappel_T_VEF_Face::ajouter(), Echange_contact_Correlation_VDF::calculer_coefficient_echange(), Echange_contact_Correlation_VEF::calculer_coefficient_echange(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Echange_contact_Correlation_VDF::calculer_prop_physique(), Echange_contact_Correlation_VEF::calculer_prop_physique(), Param::check(), Perte_Charge_Anisotrope_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Circulaire_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Directionnelle_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Isotrope_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Anisotrope_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Circulaire_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Directionnelle_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Isotrope_VEF_P1NC::coeffs_perte_charge(), Schema_Temps_base::computeTimeStep(), create_listb_from_xyz(), Postraitement_lata::dt_post_ecoule(), Parametre_implicite::equation_frequence_resolue(), Equation_base::equation_non_resolue(), UserUnaryFunction::eval(), Parser_Eval::eval_fct(), extract_coef_local(), Extraire_surface::extraire_surface(), Champ_Generique_Transformation::get_champ(), Echange_contact_Correlation_VEF::init(), MaillerParallel::interpreter(), Extraire_domaine::interpreter_(), Postraitement::lire_motcle_non_standard(), Postraitement_lata::lire_motcle_non_standard(), TRUSTChamp_Morceaux_generique< _TYPE_ >::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Boundary_field_inward::mettre_a_jour(), Schema_Temps_base::readOn(), Sous_Zone::readOn(), Remove_elem::Remove_elem_(), Source_Neutronique::rho(), Postraitement::traiter_champs(), Perte_Charge_Singuliere::update_K(), Table::val(), Champ_front_t::valeur_au_temps(), Champ_front_debit_QC_fonc_t::valeur_au_temps(), Champ_front_txyz::valeur_au_temps_et_au_point(), and Echange_contact_Correlation_VDF::volume().
get_info()
const Type_info * Parser_U::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 18 of file Parser_U.cpp.
getString()
std::string & Parser_U::getString () inline
Definition at line 165 of file Parser_U.h.
{
  return parser->getString();
}
References Parser::getString(), and parser.
Referenced by Equation_base::equation_non_resolue().
info()
const Type_info * Parser_U::info () static
Definition at line 18 of file Parser_U.cpp.
operator=()
const Parser_U & Parser_U::operator= (const Parser_U & p)
Definition at line 82 of file Parser_U.cpp.
{
  if (parser != NULL)
    delete parser;
  parser = new Parser(*(p.parser));
  return *this;
}
References parser.
parseString()
void Parser_U::parseString () inline
Construit l'arbre correspondant a la chaine de caracteres. Cet arbre doit etre construit une seule fois et la chaine de caractere est evaluee en parcourant cet arbre par la methode eval() autant de fois qu'on le souhaite.
Definition at line 109 of file Parser_U.h.
{
  parser->parseString();
}
References parser, and Parser::parseString().
Referenced by Param::check(), TRUSTChamp_Morceaux_generique< _TYPE_ >::complete_readOn(), create_listb_from_xyz(), create_listb_geom(), Equation_base::Equation_base(), extract_coef_local(), Extraire_surface::extraire_surface(), MaillerParallel::interpreter(), Extraire_domaine::interpreter_(), Remove_elem::interpreter_(), Perte_Charge_Singuliere::lire_donnees(), Equation_base::lire_motcle_non_standard(), Postraitement::lire_motcle_non_standard(), Postraitement_lata::lire_motcle_non_standard(), Parametre_implicite::Parametre_implicite(), read(), Champ_front_normal::readOn(), Schema_Temps_base::readOn(), Sous_Zone::readOn(), UserUnaryFunction::readOn(), Parametre_implicite::readOn(), Perte_Charge_Anisotrope_PolyMAC_Face::readOn(), Perte_Charge_Circulaire_PolyMAC_Face::readOn(), Perte_Charge_Directionnelle_PolyMAC_Face::readOn(), Perte_Charge_Isotrope_PolyMAC_Face::readOn(), Loi_Etat_rhoT_GP_QC::readOn(), Champ_front_pression_from_u::readOn(), Source_Neutronique::readOn(), Echange_contact_Correlation_VDF::readOn(), Echange_contact_Correlation_VEF::readOn(), Perte_Charge_Anisotrope_VEF_P1NC::readOn(), Perte_Charge_Circulaire_VEF_P1NC::readOn(), Perte_Charge_Directionnelle_VEF_P1NC::readOn(), Perte_Charge_Isotrope_VEF_P1NC::readOn(), and Terme_Source_Rappel_T_VEF_Face::readOn().
printOn()
Sortie & Parser_U::printOn (Sortie & s) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un Parser_U sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 35 of file Parser_U.cpp.
{
  return s;
}
readOn()
Entree & Parser_U::readOn (Entree & s) override protected virtual
Surcharge Objet_U::readOn(Entree&)
Lecture d'un Parser_U dans un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 56 of file Parser_U.cpp.
{
  return s;
}
self_cast() [1/2]
const Parser_U & Parser_U::self_cast (const Objet_U & r) static
Definition at line 18 of file Parser_U.cpp.
self_cast() [2/2]
Parser_U & Parser_U::self_cast (Objet_U & r) static
Definition at line 18 of file Parser_U.cpp.
setImpulsion()
void Parser_U::setImpulsion (double tinit, double periode) inline
Definition at line 194 of file Parser_U.h.
{
  parser->setImpulsion(tinit, periode);
}
References parser, and Parser::setImpulsion().
setNbVar()
void Parser_U::setNbVar (int nvar) inline
Fixe le nombre max de variables a indiquer avec la methode addVar.
Definition at line 151 of file Parser_U.h.
{
  parser->setNbVar(nvar);
}
References parser, and Parser::setNbVar().
Referenced by Param::check(), TRUSTChamp_Morceaux_generique< _TYPE_ >::complete_readOn(), create_listb_from_xyz(), create_listb_geom(), Equation_base::Equation_base(), extract_coef_local(), Extraire_surface::extraire_surface(), MaillerParallel::interpreter(), Extraire_domaine::interpreter_(), Remove_elem::interpreter_(), Perte_Charge_Singuliere::lire_donnees(), Postraitement::lire_motcle_non_standard(), Postraitement_lata::lire_motcle_non_standard(), Parametre_implicite::Parametre_implicite(), read(), Champ_front_normal::readOn(), Schema_Temps_base::readOn(), Sous_Zone::readOn(), Perte_Charge_Anisotrope_PolyMAC_Face::readOn(), Perte_Charge_Circulaire_PolyMAC_Face::readOn(), Perte_Charge_Directionnelle_PolyMAC_Face::readOn(), Perte_Charge_Isotrope_PolyMAC_Face::readOn(), Loi_Etat_rhoT_GP_QC::readOn(), Champ_front_pression_from_u::readOn(), Source_Neutronique::readOn(), Echange_contact_Correlation_VDF::readOn(), Echange_contact_Correlation_VEF::readOn(), Perte_Charge_Anisotrope_VEF_P1NC::readOn(), Perte_Charge_Circulaire_VEF_P1NC::readOn(), Perte_Charge_Directionnelle_VEF_P1NC::readOn(), Perte_Charge_Isotrope_VEF_P1NC::readOn(), and Terme_Source_Rappel_T_VEF_Face::readOn().
setString() [1/2]
void Parser_U::setString (const Nom & nom) inline
Definition at line 176 of file Parser_U.h.
{
  const char *s =  nom.getChar();
  std::string ss(s);
  for (auto & c: ss) c = toupper(c);
  setString(ss);
}
References Nom::getChar(), and setString().
setString() [2/2]
void Parser_U::setString (const std::string & s) inline
Definition at line 171 of file Parser_U.h.
{
  parser->setString(s);
}
References parser, and Parser::setString().
Referenced by Param::check(), TRUSTChamp_Morceaux_generique< _TYPE_ >::complete_readOn(), create_listb_from_xyz(), create_listb_geom(), Equation_base::Equation_base(), extract_coef_local(), Extraire_surface::extraire_surface(), MaillerParallel::interpreter(), Extraire_domaine::interpreter_(), Remove_elem::interpreter_(), Perte_Charge_Singuliere::lire_donnees(), Equation_base::lire_motcle_non_standard(), Postraitement::lire_motcle_non_standard(), Postraitement_lata::lire_motcle_non_standard(), Parametre_implicite::Parametre_implicite(), read(), Champ_front_normal::readOn(), Equation_base::readOn(), Schema_Temps_base::readOn(), Sous_Zone::readOn(), Parametre_implicite::readOn(), Perte_Charge_Anisotrope_PolyMAC_Face::readOn(), Perte_Charge_Circulaire_PolyMAC_Face::readOn(), Perte_Charge_Directionnelle_PolyMAC_Face::readOn(), Perte_Charge_Isotrope_PolyMAC_Face::readOn(), Loi_Etat_rhoT_GP_QC::readOn(), Champ_front_pression_from_u::readOn(), Source_Neutronique::readOn(), Echange_contact_Correlation_VDF::readOn(), Echange_contact_Correlation_VEF::readOn(), Perte_Charge_Anisotrope_VEF_P1NC::readOn(), Perte_Charge_Circulaire_VEF_P1NC::readOn(), Perte_Charge_Directionnelle_VEF_P1NC::readOn(), Perte_Charge_Isotrope_VEF_P1NC::readOn(), Terme_Source_Rappel_T_VEF_Face::readOn(), UserUnaryFunction::setFunction(), and setString().
setVar() [1/3]
void Parser_U::setVar (const char * sv, double val) inline
Fixe la valeur de la variable representee par une chaine sv.
Definition at line 126 of file Parser_U.h.
{
  parser->setVar(sv, val);
}
References parser, and Parser::setVar().
Referenced by Terme_Source_Rappel_T_VEF_Face::ajouter(), Echange_contact_Correlation_VDF::calculer_coefficient_echange(), Echange_contact_Correlation_VEF::calculer_coefficient_echange(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Echange_contact_Correlation_VDF::calculer_prop_physique(), Echange_contact_Correlation_VEF::calculer_prop_physique(), Param::check(), Perte_Charge_Anisotrope_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Circulaire_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Directionnelle_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Isotrope_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Anisotrope_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Circulaire_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Directionnelle_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Isotrope_VEF_P1NC::coeffs_perte_charge(), Schema_Temps_base::computeTimeStep(), create_listb_from_xyz(), Postraitement_lata::dt_post_ecoule(), Parametre_implicite::equation_frequence_resolue(), Equation_base::equation_non_resolue(), UserUnaryFunction::eval(), Parser_Eval::eval_fct(), extract_coef_local(), Extraire_surface::extraire_surface(), Champ_Generique_Transformation::get_champ(), Echange_contact_Correlation_VEF::init(), MaillerParallel::interpreter(), Extraire_domaine::interpreter_(), TRUSTChamp_Morceaux_generique< _TYPE_ >::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Boundary_field_inward::mettre_a_jour(), Sous_Zone::readOn(), Remove_elem::Remove_elem_(), Source_Neutronique::rho(), Postraitement::traiter_champs(), Perte_Charge_Singuliere::update_K(), Table::val(), Champ_front_t::valeur_au_temps(), Champ_front_debit_QC_fonc_t::valeur_au_temps(), Champ_front_txyz::valeur_au_temps_et_au_point(), and Echange_contact_Correlation_VDF::volume().
setVar() [2/3]
void Parser_U::setVar (const std::string & v, double val) inline
Fixe la valeur de la variable representee par une chaine v.
Fixe la valeur de la variable representee par un string v.
Definition at line 134 of file Parser_U.h.
{
  parser->setVar(v, val);
}
References parser, and Parser::setVar().
setVar() [3/3]
void Parser_U::setVar (int i, double val) inline
Fixe la valeur de la variable de numero specifie. Ce numero correspondt a l'ordre de l'ajout des variables par la methode addVar().
Fixe la valeur de la variable de numero specifie. Ce numero correspond a l'ordre de l'ajout des variables par la methode addVar().
Definition at line 142 of file Parser_U.h.
{
  parser->setVar(i, val);
}
References parser, and Parser::setVar().
taille_memoire()
unsigned Parser_U::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 18 of file Parser_U.cpp.
Member Data Documentation
info_obj
const Type_info Parser_U::info_obj static
Definition at line 36 of file Parser_U.h.
parser
Parser* Parser_U::parser private
Definition at line 100 of file Parser_U.h.
Referenced by addCst(), addFunc(), addVar(), eval(), getString(), operator=(), Parser_U(), parseString(), setImpulsion(), setNbVar(), setString(), setVar(), and ~Parser_U().
The documentation for this class was generated from the following files:
src/Kernel/Math/Parser_U.h
src/Kernel/Math/Parser_U.cpp