TRUST: Multiplicateur_diphasique_Friedel Class Reference
Multiplicateur_diphasique_Friedel Class Reference
classe Multiplicateur_diphasique_Friedel
multiplicateur diphasique par la correlation de Friedel :
- applique a la phase liquide pour alpha < alpha_min
- applique a la phase vapeur pour alpha > alpha_max
#include <Multiplicateur_diphasique_Friedel.h>
Public Member Functions
Multiplicateur_diphasique_Friedel ()
~Multiplicateur_diphasique_Friedel ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void coefficient (const double *alpha, const double *rho, const double *v, const double *f, const double *mu, const double Dh, const double gamma, const double *Fk, const double Fm, DoubleTab &coeff) const override
Public Member Functions inherited from Multiplicateur_diphasique_base
Multiplicateur_diphasique_base ()
~Multiplicateur_diphasique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void coefficient (const double *alpha, const double *rho, const double *v, const double *f, const double *mu, const double Dh, const double gamma, const double *Fk, const double Fm, DoubleTab &coeff) const =0
Public Member Functions inherited from Correlation_base
Correlation_base ()
~Correlation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & lire (Entree &is)
void associer_pb (const Probleme_base &pb)
virtual void mettre_a_jour (double temps)
virtual void completer ()
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Multiplicateur_diphasique_Friedel & self_cast (Objet_U &)
static const Multiplicateur_diphasique_Friedel & self_cast (const Objet_U &)
Static Public Member Functions inherited from Multiplicateur_diphasique_base
static const Type_info * info ()
static Multiplicateur_diphasique_base & self_cast (Objet_U &)
static const Multiplicateur_diphasique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Correlation_base
static const Type_info * info ()
static Correlation_base & self_cast (Objet_U &)
static const Correlation_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Multiplicateur_diphasique_base
static const Type_info info_obj
Static Public Attributes inherited from Correlation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double alpha_min_ = 1
double alpha_max_ = 1.1
int n_l = -1
int n_g = -1
int min_lottes_flinn_ = 0
int min_sensas_ = 0
Protected Attributes inherited from Correlation_base
Ref_Probleme_base pb_
Champs_compris champs_compris_
Detailed Description
classe Multiplicateur_diphasique_Friedel
multiplicateur diphasique par la correlation de Friedel :
- applique a la phase liquide pour alpha < alpha_min
- applique a la phase vapeur pour alpha > alpha_max
Definition at line 29 of file Multiplicateur_diphasique_Friedel.h.
Constructor & Destructor Documentation
Multiplicateur_diphasique_Friedel()
Multiplicateur_diphasique_Friedel::Multiplicateur_diphasique_Friedel ()
Definition at line 20 of file Multiplicateur_diphasique_Friedel.cpp.
~Multiplicateur_diphasique_Friedel()
Multiplicateur_diphasique_Friedel::~Multiplicateur_diphasique_Friedel ()
Definition at line 20 of file Multiplicateur_diphasique_Friedel.cpp.
Member Function Documentation
coefficient()
void Multiplicateur_diphasique_Friedel::coefficient (const double * alpha, const double * rho, const double * v, const double * f, const double * mu, const double Dh, const double gamma, const double * Fk, const double Fm, DoubleTab & coeff) const override virtual
Implements Multiplicateur_diphasique_base.
Definition at line 48 of file Multiplicateur_diphasique_Friedel.cpp.
{
  int min_ = min_sensas_ || min_lottes_flinn_;
  double G = alpha[n_l] * rho[n_l] * std::fabs(v[n_l]) + alpha[n_g] * rho[n_g] * std::fabs(v[n_g]), //debit total
         x = G ? alpha[n_g] * rho[n_g] * v[n_g] / G : 0, //titre
         E = (1 - x) * (1 - x) + x * x * (rho[n_l] * f[n_g] / rho[n_g] * f[n_l]),
         F = std::pow(x, 0.78) * std::pow(1 - x, 0.224),
         H = std::pow(rho[n_l] / rho[n_g], 0.91) * std::pow(mu[n_l] / mu[n_g], 0.19) * std::pow(1 - mu[n_g] / mu[n_l], 0.7),
         rho_m = alpha[n_l] * rho[n_l] + alpha[n_g] * rho[n_g], //masse volumlque du melange
         Fr = G * G / (9.81 * Dh * rho_m), We = G * G * Dh / (gamma * rho_m), //Froude, Weber,
         Phi2 = E + 3.24 * F * H * std::pow(Fr, -0.045) * std::pow(We, -0.035), //le multiplicateur!
         frac_g = std::min(std::max((alpha[n_g] - alpha_min_) / (alpha_max_ - alpha_min_), 0.), 1.), frac_l = 1 - frac_g, //fraction appliquee a la vapeur
         mul = min_sensas_ ? std::min(1., 1.4429 * std::pow(alpha[n_l], 0.6492)) : 1;
  coeff = 0;
  if (min_ && Fk[n_l] * mul < Phi2 * Fm * (alpha[n_l] * alpha[n_l])) /* Lottes-Flinn/SENSAS sur le liquide donne un frottement plus bas -> on le prend*/
    coeff(n_l, 0) = frac_l * min_ / (alpha[n_l] * alpha[n_l]), coeff(n_g, 0) = frac_g * min_ / (alpha[n_l] * alpha[n_l]);
  else  coeff(n_l, 1) = frac_l * Phi2, coeff(n_g, 1) = frac_g * Phi2; //application au liquide et/ou a la vapeur
}
References alpha_max_, alpha_min_, coeff, min_lottes_flinn_, min_sensas_, n_g, and n_l.
cree_instance()
Objet_U * Multiplicateur_diphasique_Friedel::cree_instance () static
Definition at line 20 of file Multiplicateur_diphasique_Friedel.cpp.
duplique()
int Multiplicateur_diphasique_Friedel::duplique () const override virtual
Implements Objet_U.
Definition at line 20 of file Multiplicateur_diphasique_Friedel.cpp.
get_info()
const Type_info * Multiplicateur_diphasique_Friedel::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 20 of file Multiplicateur_diphasique_Friedel.cpp.
info()
const Type_info * Multiplicateur_diphasique_Friedel::info () static
Definition at line 20 of file Multiplicateur_diphasique_Friedel.cpp.
printOn()
Sortie & Multiplicateur_diphasique_Friedel::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 22 of file Multiplicateur_diphasique_Friedel.cpp.
{
  return os;
}
readOn()
Entree & Multiplicateur_diphasique_Friedel::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 27 of file Multiplicateur_diphasique_Friedel.cpp.
{
  Param param(que_suis_je());
  param.ajouter("alpha_min", &alpha_min_);
  param.ajouter("alpha_max", &alpha_max_);
  param.ajouter("min_lottes_flinn", &min_lottes_flinn_);
  param.ajouter("min_sensas", &min_sensas_);
  param.lire_avec_accolades_depuis(is);
  const Pb_Multiphase *pbm = sub_type(Pb_Multiphase, pb_.valeur()) ? &ref_cast(Pb_Multiphase, pb_.valeur()) : NULL;
  if (!pbm || pbm->nb_phases() == 1) n_l = 0, n_g = -1; //pas un Pb_Multiphase -> monophasique liquide
  else for (int n = 0; n < pbm->nb_phases(); n++) //recherche de n_l, n_g : phase {liquide,gaz}_continu en priorite
      if (pbm->nom_phase(n).debute_par("liquide") && (n_l < 0 || pbm->nom_phase(n).finit_par("continu")))  n_l = n;
      else if (pbm->nom_phase(n).debute_par("gaz") && (n_g < 0 || pbm->nom_phase(n).finit_par("continu"))) n_g = n;
  if (n_l < 0) Process::exit(que_suis_je() + " : main phase not found!");
  return is;
}
References Param::ajouter(), alpha_max_, alpha_min_, Nom::debute_par(), Process::exit(), Param::lire_avec_accolades_depuis(), min_lottes_flinn_, min_sensas_, n_g, n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), ref_cast, sub_type, and Ref_Probleme_base::valeur().
self_cast() [1/2]
const Multiplicateur_diphasique_Friedel & Multiplicateur_diphasique_Friedel::self_cast (const Objet_U & r) static
Definition at line 20 of file Multiplicateur_diphasique_Friedel.cpp.
self_cast() [2/2]
Multiplicateur_diphasique_Friedel & Multiplicateur_diphasique_Friedel::self_cast (Objet_U & r) static
Definition at line 20 of file Multiplicateur_diphasique_Friedel.cpp.
taille_memoire()
unsigned Multiplicateur_diphasique_Friedel::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 20 of file Multiplicateur_diphasique_Friedel.cpp.
Member Data Documentation
alpha_max_
double Multiplicateur_diphasique_Friedel::alpha_max_ = 1.1 protected
Definition at line 37 of file Multiplicateur_diphasique_Friedel.h.
Referenced by coefficient(), and readOn().
alpha_min_
double Multiplicateur_diphasique_Friedel::alpha_min_ = 1 protected
Definition at line 37 of file Multiplicateur_diphasique_Friedel.h.
Referenced by coefficient(), and readOn().
info_obj
const Type_info Multiplicateur_diphasique_Friedel::info_obj static
Definition at line 31 of file Multiplicateur_diphasique_Friedel.h.
min_lottes_flinn_
int Multiplicateur_diphasique_Friedel::min_lottes_flinn_ = 0 protected
Definition at line 38 of file Multiplicateur_diphasique_Friedel.h.
Referenced by coefficient(), and readOn().
min_sensas_
int Multiplicateur_diphasique_Friedel::min_sensas_ = 0 protected
Definition at line 38 of file Multiplicateur_diphasique_Friedel.h.
Referenced by coefficient(), and readOn().
n_g
int Multiplicateur_diphasique_Friedel::n_g = -1 protected
Definition at line 38 of file Multiplicateur_diphasique_Friedel.h.
Referenced by coefficient(), and readOn().
n_l
int Multiplicateur_diphasique_Friedel::n_l = -1 protected
Definition at line 38 of file Multiplicateur_diphasique_Friedel.h.
Referenced by coefficient(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Correlations/Multiplicateur_diphasique_Friedel.h
src/ThHyd/Multiphase/Correlations/Multiplicateur_diphasique_Friedel.cpp