TRUST: Terme_Puissance_Thermique_VDF_base Class Reference
Terme_Puissance_Thermique_VDF_base Class Reference
#include <Terme_Puissance_Thermique_VDF_base.h>
Public Member Functions
Terme_Puissance_Thermique_VDF_base ()
~Terme_Puissance_Thermique_VDF_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Terme_Puissance_Thermique_VDF_base (const Iterateur_Source_VDF_base &)
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Terme_Puissance_Thermique_VDF_base & self_cast (Objet_U &)
static const
Terme_Puissance_Thermique_VDF_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Detailed Description
Definition at line 39 of file Terme_Puissance_Thermique_VDF_base.h.
Constructor & Destructor Documentation
Terme_Puissance_Thermique_VDF_base::Terme_Puissance_Thermique_VDF_base ()
Definition at line 27 of file Terme_Puissance_Thermique_VDF_base.cpp.
Terme_Puissance_Thermique_VDF_base::~Terme_Puissance_Thermique_VDF_base ()
Definition at line 27 of file Terme_Puissance_Thermique_VDF_base.cpp.
Terme_Puissance_Thermique_VDF_base::Terme_Puissance_Thermique_VDF_base (const Iterateur_Source_VDF_base & iter_base) [inline]
Definition at line 56 of file Terme_Puissance_Thermique_VDF_base.h.
  : Terme_Puissance_Thermique(), Terme_Source_VDF_base(iter_base)
{
}
Member Function Documentation
void Terme_Puissance_Thermique_VDF_base::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis) [virtual]
Implements Source_base.
Reimplemented in Terme_Puissance_Thermique_QC_VDF_Elem, Source_Dirac_VDF_Elem, and Terme_Puissance_Thermique_VDF_Elem.
Definition at line 48 of file Terme_Puissance_Thermique_VDF_base.cpp.
References Terme_Source_VDF_base::iter, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  const Zone_VDF& zvdf = ref_cast(Zone_VDF,zone_dis.valeur());
  const Zone_Cl_VDF& zclvdf = ref_cast(Zone_Cl_VDF,zone_cl_dis.valeur());
  iter->associer_zones(zvdf,zclvdf);
}
virtual int Terme_Puissance_Thermique_VDF_base::duplique () const [pure virtual]
Implements Terme_Source_VDF_base.
Implemented in Terme_Puissance_Thermique_QC_VDF_Elem, Source_Dirac_VDF_Elem, and Terme_Puissance_Thermique_VDF_Elem.
const Type_info * Terme_Puissance_Thermique_VDF_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_VDF_base.
Reimplemented in Terme_Puissance_Thermique_QC_VDF_Elem, Source_Dirac_VDF_Elem, and Terme_Puissance_Thermique_VDF_Elem.
Definition at line 27 of file Terme_Puissance_Thermique_VDF_base.cpp.
const Type_info * Terme_Puissance_Thermique_VDF_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_VDF_base.
Reimplemented in Terme_Puissance_Thermique_QC_VDF_Elem, Source_Dirac_VDF_Elem, and Terme_Puissance_Thermique_VDF_Elem.
Definition at line 27 of file Terme_Puissance_Thermique_VDF_base.cpp.
int Terme_Puissance_Thermique_VDF_base::initialiser (double temps) [virtual]
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
Reimplemented from Source_base.
Definition at line 56 of file Terme_Puissance_Thermique_VDF_base.cpp.
References MorEqn::equation(), and Terme_Puissance_Thermique::initialiser_champ_puissance().
{
  Terme_Source_VDF_base::initialiser(temps);
  initialiser_champ_puissance(equation());
  return 1;
}
Sortie & Terme_Puissance_Thermique_VDF_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Source_VDF_base.
Reimplemented in Terme_Puissance_Thermique_QC_VDF_Elem, Source_Dirac_VDF_Elem, and Terme_Puissance_Thermique_VDF_Elem.
Definition at line 30 of file Terme_Puissance_Thermique_VDF_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Terme_Puissance_Thermique_VDF_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Terme_Source_VDF_base.
Reimplemented in Terme_Puissance_Thermique_QC_VDF_Elem, Source_Dirac_VDF_Elem, and Terme_Puissance_Thermique_VDF_Elem.
Definition at line 36 of file Terme_Puissance_Thermique_VDF_base.cpp.
References Champs_compris::ajoute_champ(), Source_base::champs_compris_, MorEqn::equation(), Terme_Puissance_Thermique::la_puissance, Terme_Puissance_Thermique::lire_donnees(), Terme_Puissance_Thermique::modify_name_file(), Source_base::set_description(), and Source_base::set_fichier().
{
  const Equation_base& eqn = equation();
  Terme_Puissance_Thermique::lire_donnees(s,eqn);
  champs_compris_.ajoute_champ(la_puissance);
  Nom name_file("Puissance_Thermique");
  modify_name_file(name_file);
  set_fichier(name_file);
  set_description("Heat power release = Integral(P*dv) [W]");
  return s ;
}
const Terme_Puissance_Thermique_VDF_base & Terme_Puissance_Thermique_VDF_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Terme_Source_VDF_base.
Reimplemented in Terme_Puissance_Thermique_QC_VDF_Elem, Source_Dirac_VDF_Elem, and Terme_Puissance_Thermique_VDF_Elem.
Definition at line 27 of file Terme_Puissance_Thermique_VDF_base.cpp.
Terme_Puissance_Thermique_VDF_base & Terme_Puissance_Thermique_VDF_base::self_cast (Objet_U & r) [static]
Reimplemented from Terme_Source_VDF_base.
Reimplemented in Terme_Puissance_Thermique_QC_VDF_Elem, Source_Dirac_VDF_Elem, and Terme_Puissance_Thermique_VDF_Elem.
Definition at line 27 of file Terme_Puissance_Thermique_VDF_base.cpp.
Member Data Documentation
const Type_info Terme_Puissance_Thermique_VDF_base::info_obj [static]
Reimplemented from Terme_Source_VDF_base.
Reimplemented in Terme_Puissance_Thermique_QC_VDF_Elem, Source_Dirac_VDF_Elem, and Terme_Puissance_Thermique_VDF_Elem.
Definition at line 42 of file Terme_Puissance_Thermique_VDF_base.h.
The documentation for this class was generated from the following files:
src/VDF/Sources/Terme_Puissance_Thermique_VDF_base.h
src/VDF/Sources/Terme_Puissance_Thermique_VDF_base.cpp