TRUST: Zone_PolyMAC_P0 Class Reference
Zone_PolyMAC_P0 Class Reference
class Zone_PolyMAC_P0
Classe instanciable qui derive de Zone_VF.
Cette classe contient les informations geometriques que demande
la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
La classe porte un certain nombre d'informations concernant les faces
Dans cet ensemble de faces on fait figurer aussi les faces du bord et
des joints. Pour manipuler les faces on distingue 2 categories:
- les faces non standard qui sont sur un joint, un bord ou qui sont
internes tout en appartenant a un element du bord
- les faces standard qui sont les faces internes n'appartenant pas
a un element du bord
Cette distinction correspond au traitement des conditions aux limites:les
faces standard ne "voient pas" les conditions aux limites.
L'ensemble des faces est numerote comme suit:
- les faces qui sont sur une Zone_joint apparaissent en premier
(dans l'ordre du vecteur les_joints)
- les faces qui sont sur une Zone_bord apparaissent ensuite
(dans l'ordre du vecteur les_bords)
- les faces internes non standard apparaissent ensuite
- les faces internes standard en dernier
Finalement on trouve regroupees en premier toutes les faces non standard
qui vont necessiter un traitement particulier
On distingue deux types d'elements
- les elements non standard : ils ont au moins une face de bord
- les elements standard : ils n'ont pas de face de bord
Les elements standard (resp. les elements non standard) ne sont pas ranges
de maniere consecutive dans l'objet Zone. On utilise le tableau
rang_elem_non_std pour acceder de maniere selective a l'un ou
l'autre des types d'elements
#include <Zone_PolyMAC_P0.h>
Public Member Functions
Zone_PolyMAC_P0 ()
~Zone_PolyMAC_P0 ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretiser () override
void init_stencils () const
void fgrad (int N, int is_p, const Conds_lim &cls, const IntTab &fcl, const DoubleTab *nu, const IntTab *som_ext, int virt, int full_stencil, IntTab &phif_d, IntTab &phif_e, DoubleTab &phif_c) const
Public Member Functions inherited from Zone_PolyMAC
Zone_PolyMAC ()
~Zone_PolyMAC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretiser () override
const DoubleVect & longueur_aretes () const
const DoubleTab & ta () const
void orthocentrer ()
void M2 (const DoubleTab *nu, int e, DoubleTab &m2) const
void W2 (const DoubleTab *nu, int e, DoubleTab &w2) const
void M1 (const DoubleTab *nu, int e, DoubleTab &m1) const
void W1 (const DoubleTab *nu, int e, DoubleTab &w1) const
Public Member Functions inherited from Zone_Poly_base
Zone_Poly_base ()
~Zone_Poly_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void typer_elem (Zone &zone_geom) override
void discretiser () override
void reordonner (Faces &) override
Methode appelee par Zone_VF::discretiser apres la creation
des faces reelles.
On reordonne les faces de sorte a placer les faces "non standard"
au debut de la liste des faces. Les faces non standard sont celles
dont les volumes de controles sont modifies par les conditions aux
limites.
void modifier_pour_Cl (const Conds_lim &) override
const Elem_poly & type_elem () const
int nb_elem_Cl () const
int nb_faces_joint () const
int nb_faces_std () const
int nb_elem_std () const
double carre_pas_du_maillage () const
double carre_pas_maille (int i) const
double face_normales (int, int) const override
DoubleTab & face_normales ()
const DoubleTab & face_normales () const
IntVect & rang_elem_non_std ()
const IntVect & rang_elem_non_std () const
int oriente_normale (int face_opp, int elem2) const
const ArrOfInt & ind_faces_virt_non_std () const
void calculer_h_carre ()
DoubleTab & volumes_entrelaces_dir ()
const DoubleTab & volumes_entrelaces_dir () const
double dot (const double *a, const double *b, const double *ma=NULL, const double *mb=NULL) const
double nu_dot (const DoubleTab *nu, int e, int n, const double *a, const double *b, const double *ma=NULL, const double *mb=NULL) const
std::array< double, 3 > cross (int dima, int dimb, const double *a, const double *b, const double *ma=NULL, const double *mb=NULL) const
double dist_norm (int num_face) const
double dist_norm_bord (int num_face) const
DoubleVect & dist_norm_bord (DoubleVect &, const Nom &nom_bord) const
double dist_face_elem0 (int num_face, int n0) const
double dist_face_elem1 (int num_face, int n1) const
double dist_face_elem0_period (int num_face, int n0, double l) const
double dist_face_elem1_period (int num_face, int n1, double l) const
void detecter_faces_non_planes () const
void init_equiv () const
void init_som_elem () const
void init_dist_paroi_globale (const Conds_lim &conds_lim) override
const DoubleTab & normale_paroi_elem () const
const DoubleTab & normale_paroi_faces () const
Public Member Functions inherited from Zone_VF
Zone_VF ()
~Zone_VF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double face_normales (int, int) const =0
void calculer_face_surfaces (const DoubleVect &surfaces)
virtual const DoubleVect & face_surfaces () const
virtual double face_surfaces (int i) const
virtual double surface (int i) const
void discretiser () override
Genere les faces
construits les frontieres.
void infobord ()
void info_elem_som ()
void calculer_porosites ()
void calculer_diametres_hydrauliques ()
void calculer_sections_passage ()
void calculer_coefficient_echange_thermique ()
void calculer_coefficient_frottement ()
void marquer_faces_double_contrib (const Conds_lim &)
virtual void typer_elem (Zone &)
virtual void remplir_face_voisins_fictifs (const Zone_Cl_dis_base &)
virtual Faces * creer_faces ()
renvoie new(Faces) !
elle est surchargee par Zone_VDF par ex.
virtual void reordonner (Faces &)
cette methode ne fait rien
elle est surchargee par Zone_VDF par ex.
int nb_joints () const
renvoie le nombre de joints
int premiere_face_int () const
une face est interne ssi elle separe deux elements.
renvoie le numero de la premiere face interne.
int nb_faces () const
renvoie le nombre global de faces.
int nb_faces_tot () const
renvoie le nombre total de faces.
C'est-a-dire faces reelles + faces virtuelles
int nb_som_face () const
renvoie le nombre de sommets par face.
Rque : on a suppose que toutes les faces avait
le meme nombre de sommet ce qui exclue des elements
comme le prisme.
int nb_faces_bord () const
renvoie le nombre de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_bord_tot () const
renvoie le nombre total de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int premiere_face_bord () const
renvoie le numero de la premiere des faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_internes () const
une face est interne ssi elle separe deux elements.
renvoie le nombre de faces internes.
double xv (int, int) const
double xp (int, int) const
double xa (int, int) const
double porosite_face (int) const
double porosite_elem (int) const
double diametre_hydraulique_face (int) const
double section_passage_face (int) const
double coefficient_frottement (int) const
double coefficient_echange_thermique (int) const
int face_numero_bord (int num_face) const
IntTab & face_numero_bord ()
const IntTab & face_numero_bord () const
void remplir_face_numero_bord ()
virtual const IntVect & orientation () const
virtual int orientation (int) const
virtual int orientation_si_definie (int) const
DoubleTab normalized_boundaries_outward_vector (int global_face_number, double scale_factor) const
Compute the normalized boundary outward vector associated to the face global_face_number
and eventually scaled by scale_factor.
DoubleTab & xv ()
const DoubleTab & xv () const
DoubleTab & xp ()
const DoubleTab & xp () const
DoubleTab & xa ()
const DoubleTab & xa () const
DoubleVect & volumes_entrelaces ()
const DoubleVect & volumes_entrelaces () const
double volumes_entrelaces (int num_face) const
const DoubleTab & volumes_entrelaces_dir () const
DoubleTab & volumes_entrelaces_dir ()
DoubleVect & porosite_face ()
const DoubleVect & porosite_face () const
DoubleVect & porosite_elem ()
const DoubleVect & porosite_elem () const
DoubleVect & diametre_hydraulique_face ()
const DoubleVect & diametre_hydraulique_face () const
const DoubleVect section_passage_face () const
DoubleTab & diametre_hydraulique_elem ()
const DoubleTab & diametre_hydraulique_elem () const
DoubleVect & coefficient_frottement ()
const DoubleVect & coefficient_frottement () const
DoubleVect & coefficient_echange_thermique ()
const DoubleVect & coefficient_echange_thermique () const
const Joint & joint (int i) const
renvoie le ieme joint.
Joint & joint (int i)
renvoie le ieme joint.
Frontiere_dis_base & frontiere_dis (int) override
renvoie la ieme frontiere_discrete.
const Frontiere_dis_base & frontiere_dis (int) const override
renvoie la ieme frontiere_discrete.
int nb_frontiere_dis () const
const Front_VF & front_VF (int) const
renvoie la ieme frontiere_discrete.
double volumes (int i) const
renvoie le volume de la maille i.
double inverse_volumes (int i) const
int face_voisins (int num_face, int i) const
renvoie l'element voisin de numface dans la direction i.
i=0 : dans le sens oppose de l'axe orthogonal a la face numface.
i=1 : dans le sens de l'axe orthogonal a la face numface.
exemple :
| 0 | 1 |
numface
renvoie -1 si l'element n'existe pas (au bord).
int elem_faces (int i, int j) const
renvoie le numero de le ieme face de la maille num_elem
la facon dont ces faces sont numerotees est
laisse a la responsabilite des classes derivees
int face_sommets (int i, int j) const
renvoie le numero du ieme sommet de la face num_face.
DoubleVect & volumes ()
renvoie le tableaux des volumes des mailles.
DoubleVect & inverse_volumes ()
Tableau pour optimiser le code.
const DoubleVect & volumes () const
renvoie le tableaux des volumes des mailles.
const DoubleVect & inverse_volumes () const
Tableau pour optimiser le code.
IntTab & face_voisins () override
renvoie le tableaux des volumes des connectivites face elements
cf au dessus.
const IntTab & face_voisins () const override
cf au dessus.
const IntTab & face_voisins_fictifs () const
void face_voisins_reel_fictif (int face, int &el0, int &elf) const
renvoie dans el0 le numero de l'elt a l'interieur
renvoie dans elf le numero de l'elt fictif (-1 si il n'existe pas)
IntTab & elem_faces ()
renvoie le tableau de connectivite element/faces
const IntTab & elem_faces () const
cf au dessus.
ArrOfInt & faces_doubles ()
renvoie 1 pour les faces appartenant a un bord perio ou un item commun, 0 par defaut
const ArrOfInt & faces_doubles () const
cf au dessus
IntTab & face_sommets () override
renvoie le tableau de connectivite faces/sommets.
const IntTab & face_sommets () const override
cf au dessus.
void modifier_pour_Cl (const Conds_lim &) override
int numero_face_local (int face, int elem) const
int numero_sommet_local (int som, int elem) const
const IntTab & get_num_fac_loc () const
int get_num_fac_loc (int, int) const
void construire_num_fac_loc ()
const ArrOfInt & ind_faces_virt_bord () const
int est_une_face_virt_bord (int) const
renvoie 1 si face est une face virtuelle de bord, 0 sinon
int fbord (int f) const
void construire_face_virt_pe_num ()
Remplissage du tableau face_virt_pe_num_ (voir commentaire dans Zone_VF.h)
const IntTab & face_virt_pe_num () const
virtual void creer_tableau_faces (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_aretes (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_faces_bord (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual const MD_Vector & md_vector_faces_bord () const
virtual const MD_Vector & md_vector_faces () const
virtual const MD_Vector & md_vector_aretes () const
virtual const DoubleTab & xv_bord () const
Public Member Functions inherited from Zone_dis_base
Zone_dis_base ()
~Zone_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Associe une Zone a l'objet.
const Zone & zone () const
Renvoie la Zone associee a l'objet.
(version const)
Zone & zone ()
Renvoie la Zone associee a l'objet.
void associer_domaine_dis (const Domaine_dis &)
Associe un Domaine_dis a l'objet.
const Domaine_dis & domaine_dis () const
Domaine_dis & domaine_dis ()
virtual void discretiser ()=0
virtual void creer_elements_fictifs (const Zone_Cl_dis_base &)
virtual Frontiere_dis_base & frontiere_dis (int)=0
virtual const Frontiere_dis_base & frontiere_dis (int) const =0
int rang_frontiere (const Nom &)
int rang_frontiere (const Nom &) const
Renvoie le rang de la frontiere de Nom nom
Renvoie -1 si aucune frontiere ne s'appelle nom.
Frontiere_dis_base & frontiere_dis (const Nom &)
const Frontiere_dis_base & frontiere_dis (const Nom &) const
Renvoie la frontiere de Nom nom.
(On indexe les frontiere avec leur nom)
void ecrire_noms_bords (Sortie &) const
Ecriture des noms des bords sur un flot de sortie.
virtual void modifier_pour_Cl (const Conds_lim &)=0
virtual IntTab & face_sommets ()
virtual const IntTab & face_sommets () const
virtual IntTab & face_voisins ()
virtual const IntTab & face_voisins () const
int nb_elem () const
int nb_elem_tot () const
int nb_som () const
int nb_som_tot () const
int nb_front_Cl () const
virtual void init_dist_paroi_globale (const Conds_lim &conds_lim)
virtual const DoubleTab & y_elem () const
virtual const DoubleTab & y_faces () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_PolyMAC_P0 & self_cast (Objet_U &)
static const Zone_PolyMAC_P0 & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_PolyMAC
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_PolyMAC & self_cast (Objet_U &)
static const Zone_PolyMAC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_Poly_base
static const Type_info * info ()
static Zone_Poly_base & self_cast (Objet_U &)
static const Zone_Poly_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_VF
static const Type_info * info ()
static Zone_VF & self_cast (Objet_U &)
static const Zone_VF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_dis_base
static const Type_info * info ()
static Zone_dis_base & self_cast (Objet_U &)
static const Zone_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
IntTab fsten_d
IntTab fsten_eb
MD_Vector mdv_ch_face
Public Attributes inherited from Zone_PolyMAC
std::vector< std::map< int, int > > som_arete
MD_Vector mdv_elems_faces
MD_Vector mdv_faces_aretes
Public Attributes inherited from Zone_Poly_base
std::map< std::string, int > is_init
IntTab equiv
Static_Int_Lists som_elem
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Zone_PolyMAC
static const Type_info info_obj
Static Public Attributes inherited from Zone_Poly_base
static const Type_info info_obj
Static Public Attributes inherited from Zone_VF
static const Type_info info_obj
Static Public Attributes inherited from Zone_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Protected Member Functions inherited from Zone_Poly_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
void remplir_elem_faces () override
Sortie & ecrit (Sortie &os) const
void creer_faces_virtuelles_non_std ()
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
virtual void remplir_elem_faces ()=0
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
int first_fgrad_ = 1
Additional Inherited Members
Protected Attributes inherited from Zone_Poly_base
double h_carre
carre du pas du maillage
DoubleVect h_carre_
carre du pas d'une maille
Elem_poly type_elem_
type de l'element de discretisation
DoubleTab face_normales_
normales aux faces
int nb_faces_std_
nombre de faces standard
int nb_elem_std_
nombre d'elements standard
IntVect rang_elem_non_std_
rang_elem_non_std_= -1 si l'element est standard rang_elem_non_std_= rang de l'element dans les tableaux relatifs aux elements non standards
ArrOfInt ind_faces_virt_non_std_
contient les indices des faces virtuelles non standard
DoubleTab n_y_elem_
vecteur normal entre le bord le plus proche et l'element
DoubleTab n_y_faces_
vecteur normal entre le bord le plus proche et la face
Protected Attributes inherited from Zone_VF
DoubleVect volumes_
volumes des elements
DoubleVect inverse_volumes_
inverse du volumes des elements
DoubleVect volumes_entrelaces_
volumes entrelaces pour l'integration des Qdm
DoubleTab volumes_entrelaces_dir_
volumes entrelaces par cote
DoubleVect porosite_elem_
Porosites volumiques pour les volumes de controle de masse.
DoubleVect porosite_face_
Porosites surfaciques en masse et volumiques.
DoubleVect diametre_hydraulique_face_
DoubleTab diametre_hydraulique_elem_
DoubleVect coefficient_echange_thermique_
remplissage des coefficients d'echange_thermique
DoubleVect coefficient_frottement_
remplissage des coefficient de frottement
IntTab face_voisins_
connectivite face/elements
IntTab face_voisins_fictifs_
connectivite face/elements fictifs
DoubleTab xp_
centres de gravite des elements
DoubleTab xv_
centres de gravite des faces
DoubleTab xv_bord_
IntTab elem_faces_
connectivite element/faces
IntTab face_sommets_
sommets des faces
DoubleTab xa_
centres de gravite des aretes
IntTab face_numero_bord_
connectivite face/numero_bord
MD_Vector md_vector_faces_
MD_Vector md_vector_faces_front_
MD_Vector md_vector_aretes_
Vect_Front_VF les_bords_
IntTab num_fac_loc_
ArrOfInt faces_doubles_
faces a double contribution (faces periodiques et items communs)
IntTab face_virt_pe_num_
Protected Attributes inherited from Zone_dis_base
Ref_Zone la_zone
Ref_Domaine_dis le_domaine_dis
DoubleTab y_elem_
DoubleTab y_faces_
int dist_paroi_initialisee_ = 0
Detailed Description
class Zone_PolyMAC_P0
Classe instanciable qui derive de Zone_VF.
Cette classe contient les informations geometriques que demande
la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
La classe porte un certain nombre d'informations concernant les faces
Dans cet ensemble de faces on fait figurer aussi les faces du bord et
des joints. Pour manipuler les faces on distingue 2 categories:
- les faces non standard qui sont sur un joint, un bord ou qui sont
internes tout en appartenant a un element du bord
- les faces standard qui sont les faces internes n'appartenant pas
a un element du bord
Cette distinction correspond au traitement des conditions aux limites:les
faces standard ne "voient pas" les conditions aux limites.
L'ensemble des faces est numerote comme suit:
- les faces qui sont sur une Zone_joint apparaissent en premier
(dans l'ordre du vecteur les_joints)
- les faces qui sont sur une Zone_bord apparaissent ensuite
(dans l'ordre du vecteur les_bords)
- les faces internes non standard apparaissent ensuite
- les faces internes standard en dernier
Finalement on trouve regroupees en premier toutes les faces non standard
qui vont necessiter un traitement particulier
On distingue deux types d'elements
- les elements non standard : ils ont au moins une face de bord
- les elements standard : ils n'ont pas de face de bord
Les elements standard (resp. les elements non standard) ne sont pas ranges
de maniere consecutive dans l'objet Zone. On utilise le tableau
rang_elem_non_std pour acceder de maniere selective a l'un ou
l'autre des types d'elements
Definition at line 79 of file Zone_PolyMAC_P0.h.
Constructor & Destructor Documentation
Zone_PolyMAC_P0()
Zone_PolyMAC_P0::Zone_PolyMAC_P0 ()
Definition at line 66 of file Zone_PolyMAC_P0.cpp.
~Zone_PolyMAC_P0()
Zone_PolyMAC_P0::~Zone_PolyMAC_P0 ()
Definition at line 66 of file Zone_PolyMAC_P0.cpp.
Member Function Documentation
cree_instance()
Objet_U * Zone_PolyMAC_P0::cree_instance () static
Definition at line 66 of file Zone_PolyMAC_P0.cpp.
discretiser()
void Zone_PolyMAC_P0::discretiser () override virtual
Reimplemented from Zone_PolyMAC.
Definition at line 84 of file Zone_PolyMAC_P0.cpp.
{
  /* on saut le discretiser() de Zone_PolyMAC pour eviter d'initialiser les variables de PolyMAC_V1 */
  Zone_Poly_base::discretiser();
// MD_vector pour Champ_Face_PolyMAC_P0 (faces + dimension * champ_p0)
  MD_Vector_composite mdc_ch_face;
  mdc_ch_face.add_part(md_vector_faces());
  mdc_ch_face.add_part(zone().md_vector_elements(), dimension);
  mdv_ch_face.copy(mdc_ch_face);
}
References MD_Vector_composite::add_part(), MD_Vector::copy(), Objet_U::dimension, Zone_Poly_base::discretiser(), Zone_VF::md_vector_faces(), mdv_ch_face, and Zone_dis_base::zone().
duplique()
int Zone_PolyMAC_P0::duplique () const override virtual
Reimplemented from Zone_PolyMAC.
Definition at line 66 of file Zone_PolyMAC_P0.cpp.
fgrad()
void Zone_PolyMAC_P0::fgrad (int N, int is_p, const Conds_lim & cls, const IntTab & fcl, const DoubleTab * nu, const IntTab * som_ext, int virt, int full_stencil, IntTab & phif_d, IntTab & phif_e, DoubleTab & phif_c) const
Definition at line 140 of file Zone_PolyMAC_P0.cpp.
{
  const IntTab& f_e = face_voisins(), &e_f = elem_faces(), &f_s = face_sommets();
  const DoubleTab& nf = face_normales(), &xs = zone().domaine().coord_sommets(), &vfd = volumes_entrelaces_dir();
  const DoubleVect& fs = face_surfaces(), &vf = volumes_entrelaces();
  int i, i_s, j, k, l, e, f, s, sb, n_f, n_m, n_ef, n_e, n_eb, m, n, ne_tot = nb_elem_tot(), sgn, nw, infoo, d, db, D = dimension, rk, nl, nc, un = 1, il, ok, essai;
  double x, eps_g = 1e-6, eps = 1e-10, i3[3][3] = { { 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 }}, fac[3], vol_s;
  init_som_elem(), init_stencils();
  phif_d.set_smart_resize(1), phif_e.set_smart_resize(1), phif_e.resize(0), phif_c.resize(fsten_eb.dimension(0), N), phif_c = 0;
  std::vector<int> s_eb, s_f; //listes d'elements/bord, de faces autour du sommet
  std::vector<double> surf_fs, vol_es; //surfaces partielles des faces connectees au sommet (meme ordre que s_f)
  std::vector<std::array<std::array<double, 3>,2>> vec_fs;//pour chaque facette, base de (D-1) vecteurs permettant de la parcourir
  std::vector<std::vector<int>> se_f; /* se_f[i][.] : faces connectees au i-eme element connecte au sommet s */
  DoubleTrav M, B, X, Ff, Feb, Mf, Meb, W(1), x_fs, A, S; //systeme M.(grad u) = B dans chaque element, flux a la face Ff.u_fs + Feb.u_eb, equations Mf.u_fs = Meb.u_eb
  IntTrav piv, ctr[3];
  for (i = 0; first_fgrad_ && i < 3; i++) zone().domaine().creer_tableau_sommets(ctr[i]);
  M.set_smart_resize(1), B.set_smart_resize(1), X.set_smart_resize(1), Ff.set_smart_resize(1), Feb.set_smart_resize(1), Mf.set_smart_resize(1), Meb.set_smart_resize(1);
  W.set_smart_resize(1), x_fs.set_smart_resize(1), A.set_smart_resize(1), piv.set_smart_resize(1), S.set_smart_resize(1);
  /* contributions aux sommets : en evitant ceux de som_ext */
  for (i_s = 0; i_s <= (som_ext ? som_ext->size() : 0); i_s++)
    for (s = (som_ext && i_s ? (*som_ext)(i_s - 1) + 1 : 0); s < (som_ext && i_s < som_ext->size() ? (*som_ext)(i_s) : (virt ? nb_som_tot() : nb_som())); s++)
      {
        /* elements connectes a s : a partir de som_elem (deja classes) */
        for (s_eb.clear(), n_e = 0; n_e < som_elem.get_list_size(s); n_e++) s_eb.push_back(som_elem(s, n_e));
        /* faces et leurs surfaces partielles */
        for (s_f.clear(), surf_fs.clear(), vec_fs.clear(), se_f.resize(std::max(int(se_f.size()), n_e)), i = 0, ok = 1; i < n_e; i++)
          for (se_f[i].clear(), e = s_eb[i], j = 0; j < e_f.dimension(1) && (f = e_f(e, j)) >= 0; j++)
            {
              for (k = 0, sb = 0; k < f_s.dimension(1) && (sb = f_s(f, k)) >= 0; k++)
                if (sb == s) break;
              if (sb != s) continue; /* face de e non connectee a s -> on saute */
              if (fbord(f) >= 0) s_eb.insert(std::lower_bound(s_eb.begin(), s_eb.end(), ne_tot + f), ne_tot + f); //si f est de bord, on ajoute l'indice correspondant a s_eb
              else ok &= (f_e(f, 0) >= 0 && f_e(f, 1) >= 0); //si f est interne, alors l'amont/aval doivent etre presents
              se_f[i].push_back(f); //faces connectees a e et s
              if ((l = std::lower_bound(s_f.begin(), s_f.end(), f) - s_f.begin()) == (int) s_f.size() || s_f[l] != f) /* si f n'est pas dans s_f, on l'ajoute */
                {
                  s_f.insert(s_f.begin() + l, f); //face -> dans s_f
                  if (D < 3) surf_fs.insert(surf_fs.begin() + l, fs(f) / 2), vec_fs.insert(vec_fs.begin() + l, {{{ xs(s, 0) - xv_(f, 0), xs(s, 1) - xv_(f, 1), 0}, { 0, 0, 0 }}}); //2D -> facile
                  else for (surf_fs.insert(surf_fs.begin() + l, 0), vec_fs.insert(vec_fs.begin() + l, {{{ 0, 0, 0}, {0, 0, 0 }}}), m = 0; m < 2; m++) //3D -> deux sous-triangles
                  {
                    if (m == 1 || k > 0) sb = f_s(f, m ? (k + 1 < f_s.dimension(1) && f_s(f, k + 1) >= 0 ? k + 1 : 0) : k - 1); //sommet suivant (m = 1) ou precedent avec k > 0 -> facile
                    else for (n = f_s.dimension(1) - 1; (sb = f_s(f, n)) == -1; ) n--; //sommet precedent avec k = 0 -> on cherche a partir de la fin
                    auto v = cross(D, D, &xs(s, 0), &xs(sb, 0), &xv_(f, 0), &xv_(f, 0));//produit vectoriel (xs - xf)x(xsb - xf)
                    surf_fs[l] += std::fabs(dot(&v[0], &nf(f, 0))) / fs(f) / 4; //surface a ajouter
                    for (d = 0; d < D; d++) vec_fs[l][m][d] = (xs(s, d) + xs(sb, d)) / 2 - xv_(f, d); //vecteur face -> arete
                  }
                }
            }
        if (!ok) continue; //au moins un voisin manquant
        n_eb = s_eb.size(), n_f = s_f.size();
        /* conversion de se_f en indices dans s_f */
        for (i = 0; i < n_e; i++)
          for (j = 0; j < (int) se_f[i].size(); j++) se_f[i][j] = std::lower_bound(s_f.begin(), s_f.end(), se_f[i][j]) - s_f.begin();
        for (vol_es.resize(n_e), vol_s = 0, i = 0; i < n_e; vol_s += vol_es[i], i++)
          for (e = s_eb[i], vol_es[i] = 0, j = 0; j < (int) se_f[i].size(); j++)
            f = s_f[k = se_f[i][j]], vol_es[i] += surf_fs[k] * vfd(f, e != f_e(f, 0)) / fs(f) / D;
        for (essai = 0; essai < 3; essai++) /* essai 0 : MPFA O -> essai 1 : MPFA O avec x_fs mobiles -> essai 2 : MPFA symetrique (corecive, mais pas tres consistante) */
          {
            if (essai == 1) /* essai 1 : choix des points x_fs de continuite aux facettes pour obtenir un schema symetrique */
              {
                /* systeme lineaire */
                for (M.resize(N, nc = (D - 1) * n_f, nl = D * (D - 1) / 2 * n_e), B.resize(N, n_m = std::max(nc, nl)), M = 0, B = 0, i = 0, il = 0; i < n_e; i++)
                  for (d = 0; d < D; d++)
                    for (db = 0; db < d; db++, il++)
                      for (e = s_eb[i], j = 0; j < (int) se_f[i].size(); j++)
                        for (sgn = e == f_e(f = s_f[k = se_f[i][j]], 0) ? 1 : -1, n = 0; n < N; n++)
{
                            for (l = 0; l < D; l++) fac[l] = sgn * nu_dot(nu, e, n, &nf(f, 0), i3[l]) * surf_fs[k] / fs(f) / vol_es[i]; //vecteur lambda_e nf sortant * facteur commun
                            B(n, il) += fac[d] * (xv_(f, db) - xp_(e, db)) - fac[db] * (xv_(f, d) - xp_(e, d)); //second membre
                            for (l = 0; l < D - 1; l++) M(n, (D - 1) * k + l, il) += fac[db] * vec_fs[k][l][d] - fac[d] * vec_fs[k][l][db]; //matrice
                          }
                /* resolution -> DEGLSY */
                nw = -1, piv.resize(nc), F77NAME(dgelsy)(&nl, &nc, &un, &M(0, 0, 0), &nl, &B(0, 0), &n_m, &piv(0), &eps_g, &rk, &W(0), &nw, &infoo);
                for (W.resize(nw = W(0)), n = 0; n < N; n++) piv = 0, F77NAME(dgelsy)(&nl, &nc, &un, &M(n, 0, 0), &nl, &B(n, 0), &n_m, &piv(0), &eps_g, &rk, &W(0), &nw, &infoo);
                /* x_fs = xf + corrections */
                for (x_fs.resize(N, n_f, D), n = 0; n < N; n++)
                  for (i = 0; i < n_f; i++)
                    for (f = s_f[i], d = 0; d < D; d++)
                      for (x_fs(n, i, d) = xv_(f, d), k = 0; k < D - 1; k++) x_fs(n, i, d) += std::min(std::max(B(n, (D - 1) * i + k), 0.), 0.5) * vec_fs[i][k][d];
              }
            /* gradients par maille en fonctions des (u_eb, u_fs), flux F = Ff.u_fs + Feb.u_eb, et systeme Mf.u_fs = Feb.u_eb */
            Ff.resize(n_f, n_f, N), Feb.resize(n_f, n_eb, N), Mf.resize(N, n_f, n_f), Meb.resize(N, n_eb, n_f);
            for (Ff = 0, Feb = 0, Mf = 0, Meb = 0, i = 0; i < n_e; i++)
              for (e = s_eb[i], M.resize(n_ef = se_f[i].size(), D), B.resize(D, n_m = std::max(D, n_ef)), X.resize(n_ef, D), piv.resize(n_ef), n = 0; n < N; n++)
                {
                  if (essai < 2) /* essais 0 et 1 : gradient consistant donne par (u_e, (u_fs)_{f v e, s})*/
                    {
                      /* gradient dans (e, s) -> matrice / second membre M.x = B du systeme (grad u)_i = sum_f b_{fi} (x_fs_i - x_e), avec x_fs le pt de continuite de u_fs */
                      for (j = 0; j < n_ef; j++)
                        for (f = s_f[k = se_f[i][j]], d = 0; d < D; d++) M(j, d) = (essai ? x_fs(n, k, d) : xv_(f, d)) - xp_(e, d);
                      for (B = 0, d = 0; d < D; d++) B(d, d) = 1;
                      nw = -1, piv = 0, F77NAME(dgelsy)(&D, &n_ef, &D, &M(0, 0), &D, &B(0, 0), &n_m, &piv(0), &eps_g, &rk, &W(0), &nw, &infoo);
                      W.resize(nw = W(0)), F77NAME(dgelsy)(&D, &n_ef, &D, &M(0, 0), &D, &B(0, 0), &n_m, &piv(0), &eps_g, &rk, &W(0), &nw, &infoo);
                      for (j = 0; j < n_ef; j++)
                        for (d = 0; d < D; d++) X(j, d) = B(d, j); /* pour pouvoir utiliser nu_dot */
                    }
                  else for (j = 0; j < n_ef; j++)
                      for (sgn = e == f_e(f = s_f[k = se_f[i][j]], 0) ? 1 : -1, d = 0; d < D; d++) /* essai 2 : gradient non consistant */
                        X(j, d) = surf_fs[k] / vol_es[i] * sgn * nf(f, d) / fs(f);
                  /* flux et equation. Remarque : les CLs complexes des equations scalaires sont gerees directement dans Op_Diff_CoviMAC_Elem */
                  for (j = 0; j < n_ef; j++)
                    {
                      k = se_f[i][j], f = s_f[k], sgn = e == f_e(f, 0) ? 1 : -1; //face et son indice
                      const Cond_lim_base *cl = fcl(f, 0) ? &cls[fcl(f, 1)].valeur() : NULL; //si on est sur une CL, pointeur vers celle-ci
                      int is_dir = cl && (is_p ? sub_type(Neumann, *cl) : sub_type(Dirichlet, *cl) || sub_type(Dirichlet_homogene, *cl)); //est-elle de Dirichlet?
                      for (l = 0; l < n_ef; l++)
{
                          x = sgn * nu_dot(nu, e, n, &nf(f, 0), &X(l, 0)) * surf_fs[k] / fs(f); //contribution au flux
                          if (sgn > 0) Ff(k, se_f[i][l], n) += x, Feb(k, i, n) -= x; //flux amont->aval
                          if (!is_dir) Mf(n, se_f[i][l], k) += x, Meb(n, i, k) += x; //equation sur u_fs (sauf si CL Dirichlet)
                        }
                      if (!cl) continue; //rien de l'autre cote
                      else if (is_dir) Mf(n, k, k) = Meb(n, std::find(s_eb.begin(), s_eb.end(), ne_tot + f) - s_eb.begin(), k) = 1; //Dirichlet -> equation u_fs = u_b
                      else if (is_p ? !is_dir : sub_type(Neumann, *cl)) //Neumann -> ajout du flux au bord
                        Meb(n, std::find(s_eb.begin(), s_eb.end(), ne_tot + f) - s_eb.begin(), k) += surf_fs[k];
                      else if (sub_type(Frottement_global_impose, *cl)) //Frottement_global_impose -> flux =  - coeff * v_e
                        Meb(n, i, k) -= surf_fs[k] * ref_cast(Frottement_global_impose, *cl).coefficient_frottement(fcl(f, 2), n);
                      else if (sub_type(Frottement_externe_impose, *cl)) //Frottement_externe_impose -> flux =  - coeff * v_f
                        Mf(n, k, k) += surf_fs[k] * ref_cast(Frottement_global_impose, *cl).coefficient_frottement(fcl(f, 2), n);
                      else if (sub_type(Echange_impose_base, *cl)) //Echange_impose_base -> flux =  - h * (T_{e,f} - T_ext)
{
                          double h = ref_cast(Echange_impose_base, *cl).h_imp(fcl(f, 2), n);
                          Meb(n, std::find(s_eb.begin(), s_eb.end(), ne_tot + f) - s_eb.begin(), k) += surf_fs[k] * h; //partie h * T_ext
                          if (sub_type(Echange_externe_impose, *cl)) Mf(n, k, k) += surf_fs[k] * h; //Echange_externe_impose : partie h * T_f
                          else Meb(n, i, k) -= surf_fs[k] * h; //Echange_global_impose : partie h * T_e
                        }
                    }
                }
            /* resolution de Mf.u_fs = Meb.u_eb : DGELSY, au cas ou */
            nw = -1, piv.resize(n_f), F77NAME(dgelsy)(&n_f, &n_f, &n_eb, &Mf(0, 0, 0), &n_f, &Meb(0, 0, 0), &n_f, &piv(0), &eps, &rk, &W(0), &nw, &infoo);
            for (W.resize(nw = W(0)), n = 0; n < N; n++)
              piv = 0, F77NAME(dgelsy)(&n_f, &n_f, &n_eb, &Mf(n, 0, 0), &n_f, &Meb(n, 0, 0), &n_f, &piv(0), &eps, &rk, &W(0), &nw, &infoo);
            /* substitution dans Feb */
            for (i = 0; i < n_f; i++)
              for (j = 0; j < n_eb; j++)
                for (n = 0; n < N; n++)
                  for (k = 0; k < n_f; k++)
                    Feb(i, j, n) += Ff(i, k, n) * Meb(n, j, k);
            /* A : forme bilineaire */
            if (essai == 2) break;//pas la peine pour VFSYM
            for (A.resize(N, n_e, n_e), A = 0, i = 0; i < n_e; i++)
              for (e = s_eb[i], j = 0; j < (int) se_f[i].size(); j++)
                for (sgn = e == f_e(f = s_f[k = se_f[i][j]], 0) ? 1 : -1, l = 0; l < n_e; l++)
                  for (n = 0; n < N; n++)
                    A(n, i, l) -= sgn * Feb(k, l, n);
            /* symmetrisation */
            for (n = 0; n < N; n++)
              for (i = 0; i < n_e; i++)
                for (j = 0; j <= i; j++) A(n, i, j) = A(n, j, i) = (A(n, i, j) + A(n, j, i)) / 2;
            /* v.p. la plus petite : DSYEV */
            nw = -1, F77NAME(DSYEV)("N", "U", &n_e, &A(0, 0, 0), &n_e, S.addr(), &W(0), &nw, &infoo);
            for (W.resize(nw = W(0)), S.resize(n_e), n = 0, ok = 1; n < N; n++)
              F77NAME(DSYEV)("N", "U", &n_e, &A(n, 0, 0), &n_e, &S(0), &W(0), &nw, &infoo), ok &= S(0) > -1e-8 * vol_s;
            if (ok) break; //pour qu' "essai" ait la bonne valeur en sortie
          }
        if (first_fgrad_) ctr[essai](s) = 1;
        /* stockage dans phif_c */
        for (i = 0; i < n_f; i++)
          for (f = s_f[i], j = 0; j < n_eb; j++)
            for (k = std::lower_bound(fsten_eb.addr() + fsten_d(f), fsten_eb.addr() + fsten_d(f + 1), s_eb[j]) - fsten_eb.addr(), n = 0; n < N; n++)
              phif_c(k, n) += Feb(i, j, n) / fs(f);
      }
  /* simplification du stencil */
  int skip;
  DoubleTrav scale(N);
  for (phif_d.resize(1), phif_d = 0, phif_e.resize(0), f = 0, i = 0; f < nb_faces_tot(); f++, phif_d.append_line(i))
    if (fbord(f) >= 0 || (f_e(f, 0) >= 0 && f_e(f, 1) >= 0))
      {
        for (n = 0; n < N; n++) scale(n) = nu_dot(nu, f_e(f, 0), n, &nf(f, 0), &nf(f, 0)) / (fs(f) * vf(f)); //ordre de grandeur des coefficients
        for (j = fsten_d(f); j < fsten_d(f + 1); j++)
          {
            for (skip = !full_stencil && fsten_eb(j) != f_e(f, 0), n = 0; n < N; n++) skip &= std::fabs(phif_c(j, n)) < 1e-8 * scale(n); //que mettre ici?
            if (skip) continue;
            for (n = 0; n < N; n++) phif_c(i, n) = phif_c(j, n);
            phif_e.append_line(fsten_eb(j)), i++;
          }
      }
  /* comptage */
  if (!first_fgrad_) return;
  int count[3] = { mp_somme_vect(ctr[0]), mp_somme_vect(ctr[1]), mp_somme_vect(ctr[2]) }, tot = count[0] + count[1] + count[2];
  if (tot)
    Cerr << zone().domaine().le_nom() << "::fgrad(): " << 100. * count[0] / tot << "% MPFA-O "
         << 100. * count[1] / tot << "% MPFA-O(h) " << 100. * count[2] / tot << "% MPFA-SYM" << finl;
  first_fgrad_ = 0;
}
References TRUSTArray< _TYPE_ >::addr(), Domaine::coord_sommets(), Domaine::creer_tableau_sommets(), Zone_Poly_base::cross(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Zone_Poly_base::dot(), Zone_VF::elem_faces(), essai(), F77NAME, Zone_Poly_base::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Zone_VF::fbord(), first_fgrad_, fsten_d, fsten_eb, Static_Int_Lists::get_list_size(), Zone_Poly_base::init_som_elem(), init_stencils(), Zone_dis_base::nb_elem_tot(), Zone_dis_base::nb_som(), Zone_dis_base::nb_som_tot(), Zone_Poly_base::nu_dot(), ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), sgn, TRUSTVect< _TYPE_ >::size(), Zone_Poly_base::som_elem, sub_type, Zone_VF::volumes_entrelaces(), Zone_Poly_base::volumes_entrelaces_dir(), Zone_VF::xp_, Zone_VF::xv_, and Zone_dis_base::zone().
Referenced by Champ_Elem_PolyMAC_P0::calc_grad(), Champ_Elem_PolyMAC_P0::init_grad(), Op_Grad_PolyMAC_P0_Face::update_grad(), Op_Diff_PolyMAC_P0_base::update_phif(), and grad_Champ_Face_PolyMAC_P0::update_tab_grad().
get_info()
const Type_info * Zone_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_PolyMAC.
Definition at line 66 of file Zone_PolyMAC_P0.cpp.
info()
const Type_info * Zone_PolyMAC_P0::info () static
Definition at line 66 of file Zone_PolyMAC_P0.cpp.
init_stencils()
void Zone_PolyMAC_P0::init_stencils () const
Definition at line 97 of file Zone_PolyMAC_P0.cpp.
{
  if (is_init["stencils"]) return;
  const IntTab& f_s = face_sommets(), &f_e = face_voisins(), &e_s = zone().les_elems();
  int i, e, f, s, ne_tot = nb_elem_tot(), ns_tot = zone().domaine().nb_som_tot();
  fsten_d.set_smart_resize(1), fsten_d.resize(1), fsten_eb.set_smart_resize(1);
  /* connectivite sommets -> elems / faces de bord */
  std::vector<std::set<int>> som_eb(ns_tot);
  for (e = 0; e < nb_elem_tot(); e++)
    for (i = 0; i < e_s.dimension(1) && (s = e_s(e, i)) >= 0; i++) som_eb[s].insert(e);
  for (f = 0; f < nb_faces_tot(); f++)
    if (fbord(f) >= 0)
      for (i = 0; i < f_s.dimension(1) && (s = f_s(f, i)) >= 0; i++) som_eb[s].insert(ne_tot + f);
  std::set<int> f_eb; //sommets de la face f, elems connectes a e par soms, sommets / faces connectes par une face commune
  for (f = 0; f < nb_faces_tot(); fsten_d.append_line(fsten_eb.size()), f++)
    if (f_e(f, 0) >= 0 && (fbord(f) >= 0 || f_e(f, 1) >= 0))
      {
        /* connectivite par un sommet de f */
        for (f_eb.clear(), i = 0; i < f_s.dimension(1) && (s = f_s(f, i)) >= 0; i++)
          for (auto &&el : som_eb[s]) f_eb.insert(el);
        /* remplissage */
        for (auto && el : f_eb) fsten_eb.append_line(el);
      }
  CRIMP(fsten_d), CRIMP(fsten_eb);
  is_init["stencils"] = 1;
}
References TRUSTTab< _TYPE_ >::append_line(), CRIMP, TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), Zone_VF::fbord(), fsten_d, fsten_eb, Zone_Poly_base::is_init, Zone::les_elems(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces_tot(), Domaine::nb_som_tot(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTVect< _TYPE_ >::size(), and Zone_dis_base::zone().
Referenced by fgrad().
printOn()
Sortie & Zone_PolyMAC_P0::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Zone_PolyMAC.
Definition at line 71 of file Zone_PolyMAC_P0.cpp.
{
  return Zone_Poly_base::printOn(os);
}
References Zone_Poly_base::printOn().
readOn()
Entree & Zone_PolyMAC_P0::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Zone_PolyMAC.
Definition at line 79 of file Zone_PolyMAC_P0.cpp.
{
  return Zone_Poly_base::readOn(is);
}
References Zone_Poly_base::readOn().
self_cast() [1/2]
const Zone_PolyMAC_P0 & Zone_PolyMAC_P0::self_cast (const Objet_U & r) static
Definition at line 66 of file Zone_PolyMAC_P0.cpp.
self_cast() [2/2]
Zone_PolyMAC_P0 & Zone_PolyMAC_P0::self_cast (Objet_U & r) static
Definition at line 66 of file Zone_PolyMAC_P0.cpp.
taille_memoire()
unsigned Zone_PolyMAC_P0::taille_memoire () const override virtual
Reimplemented from Zone_PolyMAC.
Definition at line 66 of file Zone_PolyMAC_P0.cpp.
Member Data Documentation
first_fgrad_
int Zone_PolyMAC_P0::first_fgrad_ = 1 mutable private
Definition at line 111 of file Zone_PolyMAC_P0.h.
Referenced by fgrad().
fsten_d
IntTab Zone_PolyMAC_P0::fsten_d mutable
Definition at line 90 of file Zone_PolyMAC_P0.h.
Referenced by fgrad(), and init_stencils().
fsten_eb
IntTab Zone_PolyMAC_P0::fsten_eb
Definition at line 90 of file Zone_PolyMAC_P0.h.
Referenced by fgrad(), and init_stencils().
info_obj
const Type_info Zone_PolyMAC_P0::info_obj static
Definition at line 82 of file Zone_PolyMAC_P0.h.
mdv_ch_face
MD_Vector Zone_PolyMAC_P0::mdv_ch_face
Definition at line 108 of file Zone_PolyMAC_P0.h.
Referenced by discretiser(), grad_Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales(), Champ_Face_PolyMAC_P0::init_auxiliary_variables(), Champ_Face_PolyMAC_P0::init_ve2(), Champ_Face_PolyMAC_P0::trace(), Champ_Face_PolyMAC_P0::update_ve(), Champ_Face_PolyMAC_P0::update_ve2(), Champ_Face_PolyMAC_P0::valeur_aux_elems(), and Champ_Face_PolyMAC_P0::valeur_aux_elems_compo().
The documentation for this class was generated from the following files:
src/PolyMAC/Zones/Zone_PolyMAC_P0.h
src/PolyMAC/Zones/Zone_PolyMAC_P0.cpp