TRUST: Op_Diff_PolyMAC_base Class Reference
Op_Diff_PolyMAC_base Class Reference abstract
class Op_Diff_PolyMAC_base
Classe de base des operateurs de diffusion PolyMAC
#include <Op_Diff_PolyMAC_base.h>
Public Member Functions
Op_Diff_PolyMAC_base ()
~Op_Diff_PolyMAC_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void associer_diffusivite (const Champ_base &) override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
const Champ_base & diffusivite () const override
void mettre_a_jour (double t) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual int dimension_min_nu () const
virtual void modifier_nu (DoubleTab &) const
virtual void dimensionner_blocs_ext (int aux_only, matrices_t matrices, const tabs_t &semi_impl={}) const =0
virtual void ajouter_blocs_ext (int aux_only, matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const =0
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
const DoubleTab & nu () const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
calcule la contribution de la diffusion, la range dans resu
renvoie resu
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Static Public Member Functions
static const Type_info * info ()
static Op_Diff_PolyMAC_base & self_cast (Objet_U &)
static const Op_Diff_PolyMAC_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
void update_nu () const
void update_aux (double t) const
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
Ref_Zone_PolyMAC la_zone_poly_
Ref_Zone_Cl_PolyMAC la_zcl_poly_
Ref_Champ_base diffusivite_
double t_last_nu_ = -1e10
DoubleTab nu_
int nu_constant_ = 0
int nu_a_jour_ = 0
double t_last_aux_ = -1e10
int use_aux_
Matrice_Bloc mat_aux
DoubleTab var_aux
SolveurSys solv_aux
SFichier Flux
SFichier Flux_moment
SFichier Flux_sum
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Diff_PolyMAC_base
Classe de base des operateurs de diffusion PolyMAC
Definition at line 46 of file Op_Diff_PolyMAC_base.h.
Constructor & Destructor Documentation
Op_Diff_PolyMAC_base()
Op_Diff_PolyMAC_base::Op_Diff_PolyMAC_base ()
Definition at line 47 of file Op_Diff_PolyMAC_base.cpp.
~Op_Diff_PolyMAC_base()
Op_Diff_PolyMAC_base::~Op_Diff_PolyMAC_base () override
Definition at line 47 of file Op_Diff_PolyMAC_base.cpp.
Member Function Documentation
ajouter_blocs()
void Op_Diff_PolyMAC_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const inline override virtual
Reimplemented from Operateur_base.
Definition at line 81 of file Op_Diff_PolyMAC_base.h.
                                                                                       {}) const override
  {
    ajouter_blocs_ext(0, matrices, secmem, semi_impl);
  }
ajouter_blocs_ext()
virtual void Op_Diff_PolyMAC_base::ajouter_blocs_ext (int aux_only, matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const pure virtual
Implemented in Op_Diff_PolyMAC_Elem, and Op_Diff_PolyMAC_Face.
Referenced by update_aux().
associer()
void Op_Diff_PolyMAC_base::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zcl, const Champ_Inc &) override virtual
Implements Operateur_base.
Definition at line 208 of file Op_Diff_PolyMAC_base.cpp.
{
  la_zone_poly_ = ref_cast(Zone_PolyMAC,zone_dis.valeur());
  la_zcl_poly_ = ref_cast(Zone_Cl_PolyMAC,zcl.valeur());
}
References la_zcl_poly_, la_zone_poly_, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
associer_diffusivite()
void Op_Diff_PolyMAC_base::associer_diffusivite (const Champ_base & diffu) override virtual
Implements Operateur_Diff_base.
Definition at line 224 of file Op_Diff_PolyMAC_base.cpp.
{
  diffusivite_ = diffu;
}
References diffusivite_.
calculer()
DoubleTab & Op_Diff_PolyMAC_base::calculer (const DoubleTab & inco, DoubleTab & resu) const override virtual
calcule la contribution de la diffusion, la range dans resu
renvoie resu
Reimplemented from Operateur_base.
Definition at line 217 of file Op_Diff_PolyMAC_base.cpp.
{
  resu =0;
  return ajouter(inco, resu);
}
References Operateur_base::ajouter().
completer()
void Op_Diff_PolyMAC_base::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_PolyMAC_Elem, and Op_Diff_PolyMAC_Face.
Definition at line 63 of file Op_Diff_PolyMAC_base.cpp.
{
  Operateur_base::completer();
  const Equation_base& eq = equation();
  int N = eq.inconnue().valeurs().line_size(), D = dimension, N_nu = std::max(N * dimension_min_nu(), diffusivite().valeurs().line_size());
  if (N_nu == N) nu_.resize(0, N); //isotrope
  else if (N_nu == N * D) nu_.resize(0, N, D); //diagonal
  else if (N_nu == N * D * D) nu_.resize(0, N, D, D); //complet
  else Process::exit(Nom("Op_Diff_PolyMAC_base : diffusivity component count ") + Nom(N_nu) + "not among (" + Nom(N) + ", " + Nom(N * D) + ", " + Nom(N * D * D)  + ")!");
  la_zone_poly_.valeur().zone().creer_tableau_elements(nu_);
}
References Operateur_base::completer(), Zone::creer_tableau_elements(), diffusivite(), Objet_U::dimension, dimension_min_nu(), MorEqn::equation(), Process::exit(), Equation_base::inconnue(), la_zone_poly_, TRUSTVect< _TYPE_ >::line_size(), nu_, TRUSTTab< _TYPE_ >::resize(), Ref_Zone_PolyMAC::valeur(), Champ_Inc::valeurs(), and Zone_dis_base::zone().
Referenced by Op_Diff_PolyMAC_Elem::completer(), and Op_Diff_PolyMAC_Face::completer().
diffusivite()
const Champ_base & Op_Diff_PolyMAC_base::diffusivite () const override virtual
Implements Operateur_Diff_base.
Definition at line 229 of file Op_Diff_PolyMAC_base.cpp.
{
  return diffusivite_.valeur();
}
References diffusivite_, and Ref_Champ_base::valeur().
Referenced by Op_Diff_PolyMAC_Elem::calculer_dt_stab(), completer(), and update_nu().
dimension_min_nu()
virtual int Op_Diff_PolyMAC_base::dimension_min_nu () const inline virtual
Definition at line 62 of file Op_Diff_PolyMAC_base.h.
  {
    return 1;
  };
Referenced by completer().
dimensionner_blocs()
void Op_Diff_PolyMAC_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const inline override virtual
Reimplemented from Operateur_base.
Definition at line 77 of file Op_Diff_PolyMAC_base.h.
                                                                         {}) const override
  {
    dimensionner_blocs_ext(0, matrices, semi_impl);
  }
dimensionner_blocs_ext()
virtual void Op_Diff_PolyMAC_base::dimensionner_blocs_ext (int aux_only, matrices_t matrices, const tabs_t & semi_impl = {}) const pure virtual
Implemented in Op_Diff_PolyMAC_Elem, and Op_Diff_PolyMAC_Face.
Referenced by update_aux().
get_info()
const Type_info * Op_Diff_PolyMAC_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_PolyMAC_Elem, and Op_Diff_PolyMAC_Face.
Definition at line 47 of file Op_Diff_PolyMAC_base.cpp.
has_interface_blocs()
int Op_Diff_PolyMAC_base::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_PolyMAC_Face.
Definition at line 73 of file Op_Diff_PolyMAC_base.h.
  {
    return 1;
  };
impr()
int Op_Diff_PolyMAC_base::impr (Sortie & os) const override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 75 of file Op_Diff_PolyMAC_base.cpp.
{
  const Zone& ma_zone=la_zone_poly_->zone();
  const int impr_mom=ma_zone.Moments_a_imprimer();
  const int impr_sum=(ma_zone.Bords_a_imprimer_sum().est_vide() ? 0:1);
  const int impr_bord=(ma_zone.Bords_a_imprimer().est_vide() ? 0:1);
  const Schema_Temps_base& sch = la_zcl_poly_->equation().probleme().schema_temps();
  DoubleTab& tab_flux_bords= flux_bords();
  int nb_comp = tab_flux_bords.nb_dim() > 1 ? tab_flux_bords.dimension(1) : 0;
  DoubleVect bilan(nb_comp);
  const int nb_faces = la_zone_poly_->nb_faces_tot();
  DoubleTab xgr(nb_faces,dimension);
  xgr=0.;
  if (impr_mom)
    {
      const DoubleTab& xgrav = la_zone_poly_->xv();
      const ArrOfDouble& c_grav=ma_zone.cg_moments();
      for (int num_face=0; num_face <nb_faces; num_face++)
        for (int i=0; i<dimension; i++)
          xgr(num_face,i)=xgrav(num_face,i)-c_grav[i];
    }
  int k,face;
  int nb_front_Cl=la_zone_poly_->nb_front_Cl();
  DoubleTrav flux_bords2( 5, nb_front_Cl , nb_comp) ;
  flux_bords2=0;
  for (int num_cl=0; num_cl<nb_front_Cl; num_cl++)
    {
      const Cond_lim& la_cl = la_zcl_poly_->les_conditions_limites(num_cl);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = frontiere_dis.num_premiere_face();
      int nfin = ndeb + frontiere_dis.nb_faces();
      for (face=ndeb; face<nfin; face++)
        {
          for(k=0; k<nb_comp; k++)
            {
              flux_bords2(0,num_cl,k)+=tab_flux_bords(face, k);
              if (ma_zone.Bords_a_imprimer_sum().contient(frontiere_dis.le_nom()))
                flux_bords2(3,num_cl,k)+=tab_flux_bords(face, k);
            }  /* fin for k */
          if (impr_mom)
            {
              if (dimension==2)
                {
                  flux_bords2(4,num_cl,0)+=tab_flux_bords(face,1)*xgr(face,0)-tab_flux_bords(face,0)*xgr(face,1);
                }
              else
                {
                  flux_bords2(4,num_cl,0)+=tab_flux_bords(face,2)*xgr(face,1)-tab_flux_bords(face,1)*xgr(face,2);
                  flux_bords2(4,num_cl,1)+=tab_flux_bords(face,0)*xgr(face,2)-tab_flux_bords(face,2)*xgr(face,0);
                  flux_bords2(4,num_cl,2)+=tab_flux_bords(face,1)*xgr(face,0)-tab_flux_bords(face,0)*xgr(face,1);
                }
            }
        } /* fin for face */
    }
  mp_sum_for_each_item(flux_bords2);
  if (je_suis_maitre() && nb_comp > 0)
    {
// SFichier Flux;
      if (!Flux.is_open()) ouvrir_fichier(Flux,"",1);
// SFichier Flux_moment;
      if (!Flux_moment.is_open()) ouvrir_fichier(Flux_moment,"moment",impr_mom);
// SFichier Flux_sum;
      if (!Flux_sum.is_open()) ouvrir_fichier(Flux_sum,"sum",impr_sum);
      Flux.add_col(sch.temps_courant());
      if (impr_mom) Flux_moment.add_col(sch.temps_courant());
      if (impr_sum) Flux_sum.add_col(sch.temps_courant());
      for (int num_cl=0; num_cl<nb_front_Cl; num_cl++)
        {
          for(k=0; k<nb_comp; k++)
            {
              Flux.add_col(flux_bords2(0,num_cl,k));
              if (impr_sum) Flux_sum.add_col(flux_bords2(3,num_cl,k));
              bilan(k)+=flux_bords2(0,num_cl,k);
            }
          if (dimension==3)
            {
              for (k=0; k<nb_comp; k++)
                if (impr_mom) Flux_moment.add_col(flux_bords2(4,num_cl,k));
            }
          else
            {
              if (impr_mom) Flux_moment.add_col(flux_bords2(4,num_cl,0));
            }
        } /* fin for num_cl */
      for(k=0; k<nb_comp; k++)
        Flux.add_col(bilan(k));
      Flux << finl;
      if (impr_sum) Flux_sum << finl;
      if (impr_mom) Flux_moment << finl;
    }
  const LIST(Nom)& Liste_Bords_a_imprimer = la_zone_poly_->zone().Bords_a_imprimer();
  if (!Liste_Bords_a_imprimer.est_vide() && nb_comp > 0)
    {
      EcrFicPartage Flux_face;
      ouvrir_fichier_partage(Flux_face,"",impr_bord);
      for (int num_cl=0; num_cl<nb_front_Cl; num_cl++)
        {
          const Frontiere_dis_base& la_fr = la_zcl_poly_->les_conditions_limites(num_cl).frontiere_dis();
          const Cond_lim& la_cl = la_zcl_poly_->les_conditions_limites(num_cl);
          const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = frontiere_dis.num_premiere_face();
          int nfin = ndeb + frontiere_dis.nb_faces();
          if (ma_zone.Bords_a_imprimer().contient(la_fr.le_nom()))
            {
              if(je_suis_maitre())
                {
                  Flux_face << "# Flux par face sur " << la_fr.le_nom() << " au temps ";
                  sch.imprimer_temps_courant(Flux_face);
                  Flux_face << " : " << finl;
                }
              for (face=ndeb; face<nfin; face++)
                {
                  if (dimension == 2)
                    Flux_face << "# Face a x= " << la_zone_poly_->xv(face,0) << " y= " << la_zone_poly_->xv(face,1) << " : ";
                  else if (dimension == 3)
                    Flux_face << "# Face a x= " << la_zone_poly_->xv(face,0) << " y= " << la_zone_poly_->xv(face,1) << " z= " << la_zone_poly_->xv(face,2) << " : ";
                  for(k=0; k<nb_comp; k++)
                    Flux_face << tab_flux_bords(face, k) << " ";
                  Flux_face << finl;
                }
              Flux_face.syncfile();
            }
        }
    }
  return 1;
}
References Sortie::add_col(), Zone::Bords_a_imprimer(), Zone::Bords_a_imprimer_sum(), Zone::cg_moments(), List_Nom::contient(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), liste::est_vide(), finl, Flux, Operateur_base::flux_bords(), Flux_moment, Flux_sum, Cond_lim::frontiere_dis(), Schema_Temps_base::imprimer_temps_courant(), Sortie_Fichier_base::is_open(), Process::je_suis_maitre(), la_zcl_poly_, la_zone_poly_, Frontiere_dis_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), LIST, Zone::Moments_a_imprimer(), mp_sum_for_each_item(), TRUSTTab< _TYPE_ >::nb_dim(), Front_VF::nb_faces(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Operateur_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), Equation_base::probleme(), ref_cast, Probleme_base::schema_temps(), EcrFicPartage::syncfile(), Schema_Temps_base::temps_courant(), Zone_VF::xv(), and Zone_dis_base::zone().
info()
const Type_info * Op_Diff_PolyMAC_base::info () static
Definition at line 47 of file Op_Diff_PolyMAC_base.cpp.
mettre_a_jour()
void Op_Diff_PolyMAC_base::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
Reimplemented from Operateur_base.
Definition at line 53 of file Op_Diff_PolyMAC_base.cpp.
{
  Operateur_base::mettre_a_jour(t);
// si le champ est constant en temps, alors pas besoin de recalculer nu_ et les interpolations
  if (t <= t_last_nu_) return;
  if (!nu_constant_) nu_a_jour_ = 0;
  t_last_nu_ = t;
}
References Operateur_base::mettre_a_jour(), nu_a_jour_, nu_constant_, and t_last_nu_.
modifier_nu()
virtual void Op_Diff_PolyMAC_base::modifier_nu (DoubleTab &) const inline virtual
Definition at line 66 of file Op_Diff_PolyMAC_base.h.
{ };
Referenced by update_nu().
nu()
const DoubleTab & Op_Diff_PolyMAC_base::nu () const inline
Definition at line 87 of file Op_Diff_PolyMAC_base.h.
  {
    if (!nu_a_jour_) update_nu();
    return nu_;
  }
References nu_, nu_a_jour_, and update_nu().
printOn()
Sortie & Op_Diff_PolyMAC_base::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_PolyMAC_Elem, and Op_Diff_PolyMAC_Face.
Definition at line 49 of file Op_Diff_PolyMAC_base.cpp.
{ return s << que_suis_je() ; }
References Objet_U::que_suis_je().
Referenced by Op_Diff_PolyMAC_Elem::printOn(), and Op_Diff_PolyMAC_Face::printOn().
readOn()
Entree & Op_Diff_PolyMAC_base::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_PolyMAC_Elem, and Op_Diff_PolyMAC_Face.
Definition at line 51 of file Op_Diff_PolyMAC_base.cpp.
{ return s ; }
Referenced by Op_Diff_PolyMAC_Elem::readOn(), and Op_Diff_PolyMAC_Face::readOn().
self_cast() [1/2]
const Op_Diff_PolyMAC_base & Op_Diff_PolyMAC_base::self_cast (const Objet_U & r) static
Definition at line 47 of file Op_Diff_PolyMAC_base.cpp.
self_cast() [2/2]
Op_Diff_PolyMAC_base & Op_Diff_PolyMAC_base::self_cast (Objet_U & r) static
Definition at line 47 of file Op_Diff_PolyMAC_base.cpp.
update_aux()
void Op_Diff_PolyMAC_base::update_aux (double t) const protected
Definition at line 271 of file Op_Diff_PolyMAC_base.cpp.
{
  const std::string& nom_inco = (le_champ_inco.non_nul() ? le_champ_inco.valeur() : equation().inconnue().valeur()).le_nom().getString();
  int i, j, n_ext = op_ext.size(), first_run = mat_aux.nb_lignes() == 0; /* nombre d'operateurs */
  if (first_run)
    for (mat_aux.dimensionner(n_ext, n_ext), i = 0; i < n_ext; i++)
      for (j = 0; j < n_ext; j++)
        mat_aux.get_bloc(i, j).typer("Matrice_Morse");
  std::vector<const Op_Diff_PolyMAC_base *> opp_ext(n_ext);
  for (i = 0; i < n_ext; i++) opp_ext[i] = &ref_cast(Op_Diff_PolyMAC_base, *op_ext[i]);
  std::vector<matrices_t> lines(n_ext); /* sous forme d'arguments pour dimensionner/assembler_blocs */
  for (i = 0; i < n_ext; i++)
    for (j = 0; j < n_ext; j++)
      lines[i][nom_inco + (j == i ? "" : "/" + op_ext[j]->equation().probleme().le_nom().getString())] = &ref_cast(Matrice_Morse, mat_aux.get_bloc(i, j).valeur());
  if (first_run)
    for (i = 0; i < n_ext; i++) opp_ext[i]->dimensionner_blocs_ext(1, lines[i]); //dimensionnement
  /* inconnue / second membre */
  std::deque<ConstDoubleTab_parts> v_part;
  for (i = 0; i < n_ext; i++) v_part.emplace_back(op_ext[i]->has_champ_inco() ? op_ext[i]->mon_inconnue().valeurs() : op_ext[i]->equation().inconnue().valeurs());
  MD_Vector_composite mdc; //MD_Vector composite : a partir de tous les seconds blocs
  for (i = 0; i < n_ext; i++) mdc.add_part(v_part[i][1].get_md_vector(), v_part[i][1].line_size());
  MD_Vector mdv;
  mdv.copy(mdc);
  DoubleTrav inco, secmem;
  MD_Vector_tools::creer_tableau_distribue(mdv, inco), MD_Vector_tools::creer_tableau_distribue(mdv, secmem);
  DoubleTab_parts p_inc(inco), p_sec(secmem);
  for (i = 0; i < n_ext; i++) p_inc[i] = v_part[i][1];
  /* assemblage */
  if (!first_run)
    for (i = 0; i < n_ext; i++)
      for (j = 0; j < n_ext; j++) ref_cast(Matrice_Morse, mat_aux.get_bloc(i, j).valeur()).get_set_coeff() = 0;
  for (i = 0; i < n_ext; i++) opp_ext[i]->ajouter_blocs_ext(1, lines[i], p_sec[i]);
  /* passage incremente/inconnues */
  mat_aux.ajouter_multvect(inco, secmem);
  /* resolution */
  if (first_run)
    {
      if (equation().parametre_equation().non_nul())
        solv_aux = ref_cast(Parametre_implicite, equation().parametre_equation().valeur()).solveur(); //on copie le solveur de l'equation
      else
        {
          EChaine chl("petsc cholesky { }");
          chl >> solv_aux;
        }
      solv_aux->fixer_limpr(-1);
    }
  solv_aux.valeur().reinit();
  solv_aux.resoudre_systeme(mat_aux, secmem, inco);
  /* maj de var_aux / t_last_aux dans tous les operateurs */
  for (i = 0; i < n_ext; i++) opp_ext[i]->var_aux = p_inc[i], opp_ext[i]->t_last_aux_ = t, opp_ext[i]->use_aux_ = 1;
}
References MD_Vector_composite::add_part(), ajouter_blocs_ext(), Matrice_Base::ajouter_multvect(), MD_Vector::copy(), MD_Vector_tools::creer_tableau_distribue(), Matrice_Bloc::dimensionner(), dimensionner_blocs_ext(), MorEqn::equation(), Matrice_Bloc::get_bloc(), Nom::getString(), Equation_base::inconnue(), Operateur_base::le_champ_inco, Objet_U::le_nom(), mat_aux, Matrice_Bloc::nb_lignes(), O_U_Ptr::non_nul(), Operateur_Diff_base::op_ext, ref_cast, SolveurSys_base::reinit(), SolveurSys::resoudre_systeme(), solv_aux, t_last_aux_, Deriv_::typer(), use_aux_, Deriv_Champ_Inc_base::valeur(), Ref_Champ_Inc::valeur(), Deriv_Matrice_Base::valeur(), Deriv_SolveurSys_base::valeur(), valeur(), and var_aux.
Referenced by Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), and Op_Diff_PolyMAC_Face::ajouter_blocs_ext().
update_nu()
void Op_Diff_PolyMAC_base::update_nu () const protected
Definition at line 234 of file Op_Diff_PolyMAC_base.cpp.
{
  const Zone_PolyMAC& zone = la_zone_poly_.valeur();
  const DoubleTab& nu_src = diffusivite().valeurs();
  int e, i, m, n, N = equation().inconnue().valeurs().line_size(), N_nu = nu_.line_size(), N_nu_src = nu_src.line_size(), mult = N_nu / N, c_nu = nu_src.dimension_tot(0) == 1, d, db, D = dimension;
  assert(N_nu % N == 0);
  /* nu_ : si necessaire, on doit etendre la champ source */
  if (N_nu == N_nu_src)
    for (e = 0; e < zone.nb_elem_tot(); e++)
      for (n = 0; n < N_nu; n++) nu_.addr()[N_nu * e +  n] = nu_src(!c_nu * e, n); //facile
  else if (N_nu == N * D && N_nu_src == N)
    for (e = 0; e < zone.nb_elem_tot(); e++)
      for (n = 0; n < N; n++)
        for (d = 0; d < D; d++) //diagonal
          nu_(e, n, d) = nu_src(!c_nu * e, n);
  else if (N_nu == N * D * D && (N_nu_src == N || N_nu_src == N * D))
    for (e = 0; e < zone.nb_elem_tot(); e++)
      for (n = 0; n < N; n++) //complet
        for (d = 0; d < D; d++)
          for (db = 0; db < D; db++) nu_(e, n, d, db) = (d == db) * nu_src(!c_nu * e, N_nu_src == N ? n : D * n + d);
  else abort();
  /* ponderation de nu par la porosite et par alpha (si pb_Multiphase) */
  const DoubleTab *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL;
  for (e = 0; e < zone.nb_elem_tot(); e++)
    for (n = 0, i = 0; n < N; n++)
      for (m = 0; m < mult; m++, i++)
        nu_.addr()[N_nu * e + i] *= zone.porosite_elem()(e) * (alp ? std::max((*alp)(e, n), 1e-8) : 1);
  /* modification par une classe fille */
  modifier_nu(nu_);
  nu_a_jour_ = 1;
}
References Process::abort(), TRUSTArray< _TYPE_ >::addr(), diffusivite(), Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), MorEqn::equation(), Equation_base::inconnue(), la_zone_poly_, TRUSTVect< _TYPE_ >::line_size(), modifier_nu(), Zone_dis_base::nb_elem_tot(), nu_, nu_a_jour_, Zone_VF::porosite_elem(), ref_cast, sub_type, Ref_Zone_PolyMAC::valeur(), Champ_Inc::valeurs(), and Champ_Proto::valeurs().
Referenced by Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Diff_PolyMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), and nu().
Member Data Documentation
diffusivite_
Ref_Champ_base Op_Diff_PolyMAC_base::diffusivite_ protected
Definition at line 99 of file Op_Diff_PolyMAC_base.h.
Referenced by associer_diffusivite(), and diffusivite().
Flux
SFichier Op_Diff_PolyMAC_base::Flux mutable protected
Definition at line 117 of file Op_Diff_PolyMAC_base.h.
Referenced by impr().
Flux_moment
SFichier Op_Diff_PolyMAC_base::Flux_moment protected
Definition at line 117 of file Op_Diff_PolyMAC_base.h.
Referenced by impr().
Flux_sum
SFichier Op_Diff_PolyMAC_base::Flux_sum protected
Definition at line 117 of file Op_Diff_PolyMAC_base.h.
Referenced by impr().
info_obj
const Type_info Op_Diff_PolyMAC_base::info_obj static
Definition at line 50 of file Op_Diff_PolyMAC_base.h.
la_zcl_poly_
Ref_Zone_Cl_PolyMAC Op_Diff_PolyMAC_base::la_zcl_poly_ protected
Definition at line 98 of file Op_Diff_PolyMAC_base.h.
Referenced by associer(), and impr().
la_zone_poly_
Ref_Zone_PolyMAC Op_Diff_PolyMAC_base::la_zone_poly_ protected
Definition at line 97 of file Op_Diff_PolyMAC_base.h.
Referenced by Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), associer(), Op_Diff_PolyMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), impr(), and update_nu().
mat_aux
Matrice_Bloc Op_Diff_PolyMAC_base::mat_aux mutable protected
Definition at line 113 of file Op_Diff_PolyMAC_base.h.
Referenced by update_aux().
nu_
DoubleTab Op_Diff_PolyMAC_base::nu_ mutable protected
Definition at line 105 of file Op_Diff_PolyMAC_base.h.
Referenced by Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Diff_PolyMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), completer(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), nu(), and update_nu().
nu_a_jour_
int Op_Diff_PolyMAC_base::nu_a_jour_ = 0 protected
Definition at line 107 of file Op_Diff_PolyMAC_base.h.
Referenced by mettre_a_jour(), nu(), and update_nu().
nu_constant_
int Op_Diff_PolyMAC_base::nu_constant_ = 0 mutable protected
Definition at line 107 of file Op_Diff_PolyMAC_base.h.
Referenced by mettre_a_jour().
solv_aux
SolveurSys Op_Diff_PolyMAC_base::solv_aux mutable protected
Definition at line 115 of file Op_Diff_PolyMAC_base.h.
Referenced by update_aux().
t_last_aux_
double Op_Diff_PolyMAC_base::t_last_aux_ = -1e10 mutable protected
Definition at line 111 of file Op_Diff_PolyMAC_base.h.
Referenced by Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), and update_aux().
t_last_nu_
double Op_Diff_PolyMAC_base::t_last_nu_ = -1e10 protected
Definition at line 101 of file Op_Diff_PolyMAC_base.h.
Referenced by mettre_a_jour().
use_aux_
int Op_Diff_PolyMAC_base::use_aux_ mutable protected
Definition at line 112 of file Op_Diff_PolyMAC_base.h.
Referenced by Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), and update_aux().
var_aux
DoubleTab Op_Diff_PolyMAC_base::var_aux mutable protected
Definition at line 114 of file Op_Diff_PolyMAC_base.h.
Referenced by Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), and update_aux().
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Op_Diff_PolyMAC_base.h
src/PolyMAC/Operateurs/Op_Diff_PolyMAC_base.cpp