TRUST: Op_Conv_Amont_PolyMAC_Elem Class Reference
Op_Conv_Amont_PolyMAC_Elem Class Reference
class Op_Conv_Amont_PolyMAC_Elem
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est PolyMAC
Le champ convecte est scalaire
Le schema de convection est du type Amont
L'iterateur associe est de type Iterateur_PolyMAC_Elem
L'evaluateur associe est de type Eval_Amont_PolyMAC_Elem
#include <Op_Conv_Amont_PolyMAC_Elem.h>
Public Member Functions
~Op_Conv_Amont_PolyMAC_Elem ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Op_Conv_Amont_PolyMAC_Elem ()
constructeur
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
complete l'iterateur et l'evaluateur
void associer_vitesse (const Champ_base &)
associe le champ de vitesse a l'evaluateur
const Champ_base & vitesse () const
Champ_base & vitesse ()
void dimensionner (Matrice_Morse &) const
on dimensionne notre matrice.
void dimensionner_bloc_vitesse (Matrice_Morse &) const
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Conv_Amont_PolyMAC_Elem & self_cast (Objet_U &)
static const
Op_Conv_Amont_PolyMAC_Elem & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Op_Conv_Amont_PolyMAC_Elem (const Iterateur_PolyMAC_base &)
Detailed Description
class Op_Conv_Amont_PolyMAC_Elem
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est PolyMAC
Le champ convecte est scalaire
Le schema de convection est du type Amont
L'iterateur associe est de type Iterateur_PolyMAC_Elem
L'evaluateur associe est de type Eval_Amont_PolyMAC_Elem
Definition at line 55 of file Op_Conv_Amont_PolyMAC_Elem.h.
Constructor & Destructor Documentation
Op_Conv_Amont_PolyMAC_Elem::~Op_Conv_Amont_PolyMAC_Elem ()
Definition at line 26 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
Op_Conv_Amont_PolyMAC_Elem::Op_Conv_Amont_PolyMAC_Elem ()
constructeur
Definition at line 91 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
                                                       :
  Op_Conv_PolyMAC_iterateur_base(It_PolyMAC_Elem(Eval_Amont_PolyMAC_Elem)())
{
}
Op_Conv_Amont_PolyMAC_Elem::Op_Conv_Amont_PolyMAC_Elem (const Iterateur_PolyMAC_base & it) [inline, protected]
Definition at line 76 of file Op_Conv_Amont_PolyMAC_Elem.h.
  : Op_Conv_PolyMAC_iterateur_base(it)
{
}
Member Function Documentation
void Op_Conv_Amont_PolyMAC_Elem::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_transporte) [virtual]
complete l'iterateur et l'evaluateur
< Evaluateur_PolyMAC::associer
< Eval_PolyMAC_Elem::associer_inconnue
Implements Operateur_base.
Definition at line 49 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
References Iterateur_PolyMAC::associer(), Eval_PolyMAC_Elem::associer_inconnue(), Evaluateur_PolyMAC::associer_zones(), Iterateur_PolyMAC::evaluateur(), Op_Conv_PolyMAC_iterateur_base::iter, ref_cast, Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  const Zone_PolyMAC& zvdf = ref_cast(Zone_PolyMAC,zone_dis.valeur());
  const Zone_Cl_PolyMAC& zclvdf = ref_cast(Zone_Cl_PolyMAC,zone_cl_dis.valeur());
  const Champ_P0_PolyMAC& inco = ref_cast(Champ_P0_PolyMAC,ch_transporte.valeur());
  iter->associer(zvdf, zclvdf, *this);
  Eval_Amont_PolyMAC_Elem& eval_conv = (Eval_Amont_PolyMAC_Elem&) iter.evaluateur();
  eval_conv.associer_zones(zvdf, zclvdf );          //!< Evaluateur_PolyMAC::associer
  eval_conv.associer_inconnue(inco );        //!< Eval_PolyMAC_Elem::associer_inconnue
}
void Op_Conv_Amont_PolyMAC_Elem::associer_vitesse (const Champ_base & ch_vit) [virtual]
associe le champ de vitesse a l'evaluateur
< Eval_Conv_PolyMAC::associer
Implements Operateur_Conv_base.
Definition at line 66 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
References Eval_Conv_PolyMAC::associer(), Iterateur_PolyMAC::evaluateur(), Op_Conv_PolyMAC_iterateur_base::iter, and ref_cast.
{
  const Champ_Face_PolyMAC& vit = ref_cast(Champ_Face_PolyMAC, ch_vit);
  Eval_Amont_PolyMAC_Elem& eval_conv = (Eval_Amont_PolyMAC_Elem&) iter.evaluateur();
  eval_conv.associer(vit);                //!< Eval_Conv_PolyMAC::associer
}
Objet_U * Op_Conv_Amont_PolyMAC_Elem::cree_instance () [static]
Definition at line 26 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
void Op_Conv_Amont_PolyMAC_Elem::dimensionner (Matrice_Morse & matrice) const [inline, virtual]
on dimensionne notre matrice.
Reimplemented from Operateur_base.
Definition at line 83 of file Op_Conv_Amont_PolyMAC_Elem.h.
References Op_Conv_PolyMAC_iterateur_base::iter, Iterateur_PolyMAC::zone(), and Iterateur_PolyMAC::zone_Cl().
{
  Op_PolyMAC_Elem::dimensionner(iter.zone(), iter.zone_Cl(), matrice);
}
void Op_Conv_Amont_PolyMAC_Elem::dimensionner_bloc_vitesse (Matrice_Morse & matrice) const [inline, virtual]
Reimplemented from Operateur_base.
Definition at line 88 of file Op_Conv_Amont_PolyMAC_Elem.h.
References Op_Conv_PolyMAC_iterateur_base::iter, Iterateur_PolyMAC::zone(), and Iterateur_PolyMAC::zone_Cl().
{
  Op_PolyMAC_Elem::dimensionner_bloc_vitesse(iter.zone(), iter.zone_Cl(), matrice);
}
int Op_Conv_Amont_PolyMAC_Elem::duplique () const [virtual]
Implements Op_Conv_PolyMAC_iterateur_base.
Definition at line 26 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
const Type_info * Op_Conv_Amont_PolyMAC_Elem::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_PolyMAC_iterateur_base.
Definition at line 26 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
const Type_info * Op_Conv_Amont_PolyMAC_Elem::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_PolyMAC_iterateur_base.
Definition at line 26 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
void Op_Conv_Amont_PolyMAC_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 93 of file Op_Conv_Amont_PolyMAC_Elem.h.
References Op_Conv_PolyMAC_iterateur_base::iter, Iterateur_PolyMAC::zone(), and Iterateur_PolyMAC::zone_Cl().
{
  Op_PolyMAC_Elem::modifier_pour_Cl(iter.zone(), iter.zone_Cl(), matrice, secmem);
}
Sortie & Op_Conv_Amont_PolyMAC_Elem::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Conv_PolyMAC_iterateur_base.
Definition at line 33 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
{
  return s << que_suis_je() ;
}
Entree & Op_Conv_Amont_PolyMAC_Elem::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Conv_PolyMAC_iterateur_base.
Definition at line 41 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
{
  return s ;
}
const Op_Conv_Amont_PolyMAC_Elem & Op_Conv_Amont_PolyMAC_Elem::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Conv_PolyMAC_iterateur_base.
Definition at line 26 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
Op_Conv_Amont_PolyMAC_Elem & Op_Conv_Amont_PolyMAC_Elem::self_cast (Objet_U & r) [static]
Reimplemented from Op_Conv_PolyMAC_iterateur_base.
Definition at line 26 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
unsigned Op_Conv_Amont_PolyMAC_Elem::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
Champ_base & Op_Conv_Amont_PolyMAC_Elem::vitesse () [virtual]
Implements Op_Conv_PolyMAC_iterateur_base.
Definition at line 80 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
References Iterateur_PolyMAC::evaluateur(), Op_Conv_PolyMAC_iterateur_base::iter, and Eval_Conv_PolyMAC::vitesse().
{
  Eval_Amont_PolyMAC_Elem& eval_conv = (Eval_Amont_PolyMAC_Elem&) iter.evaluateur();
  return eval_conv.vitesse();
}
const Champ_base & Op_Conv_Amont_PolyMAC_Elem::vitesse () const [virtual]
Implements Op_Conv_PolyMAC_iterateur_base.
Definition at line 74 of file Op_Conv_Amont_PolyMAC_Elem.cpp.
References Iterateur_PolyMAC::evaluateur(), Op_Conv_PolyMAC_iterateur_base::iter, and Eval_Conv_PolyMAC::vitesse().
{
  Eval_Amont_PolyMAC_Elem& eval_conv = (Eval_Amont_PolyMAC_Elem&) iter.evaluateur();
  return eval_conv.vitesse();
}
Member Data Documentation
const Type_info Op_Conv_Amont_PolyMAC_Elem::info_obj [static]
Reimplemented from Op_Conv_PolyMAC_iterateur_base.
Definition at line 58 of file Op_Conv_Amont_PolyMAC_Elem.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Conv_iterateur/Op_Conv_Amont_PolyMAC_Elem.h
src/PolyMAC/Operateurs/Conv_iterateur/Op_Conv_Amont_PolyMAC_Elem.cpp