TRUST: Champ_front_synt Class Reference
Champ_front_synt Class Reference
classe Champ_front_synt
Classe derivee de Champ_front_base
#include <Champ_front_synt.h>
Public Member Functions
Champ_front_synt ()
~Champ_front_synt ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Mise a jour du temps.
Champ_front_base & affecter_ (const Champ_front_base &ch) override
Pas code !!
void mettre_a_jour (double temps) override
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
Public Member Functions inherited from Ch_front_var_instationnaire_dep
Ch_front_var_instationnaire_dep ()
~Ch_front_var_instationnaire_dep ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Champ_front_base & affecter_ (const Champ_front_base &ch) override
Public Member Functions inherited from Champ_front_var_instationnaire
Champ_front_var_instationnaire ()
~Champ_front_var_instationnaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialise le temps courant et Gpoint.
DoubleTab & Gpoint ()
const DoubleTab & Gpoint () const
void Gpoint (double t1, double t2)
DoubleTab & valeurs_au_temps (double temps) override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
const DoubleTab & valeurs_au_temps (double temps) const override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
int avancer (double temps) override
Avance jusqu'au temps desire.
Sinon, sort en erreur.
int reculer (double temps) override
Recule jusqu'au temps desire.
Sinon, sort en erreur.
virtual double valeur_au_temps_et_au_point (double temps, int som, double x, double y, double z, int comp) const
virtual int valeur_au_temps_et_au_point_disponible () const
Public Member Functions inherited from Champ_front_var
Champ_front_var ()
~Champ_front_var () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Public Member Functions inherited from Champ_front_base
~Champ_front_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base ()
virtual void completer ()
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe une frontiere discretisee au champ.
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
virtual DoubleTab & valeurs_au_temps (double temps)=0
virtual const DoubleTab & valeurs_au_temps (double temps) const =0
const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee associee au champ.
(version const)
Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee associee au champ.
const Zone_dis_base & zone_dis () const
virtual Champ_front_base & affecter_ (const Champ_front_base &ch)=0
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
virtual void calculer_coeffs_echange (double temps)
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
virtual void valeurs_face (int, DoubleVect &) const
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
virtual void verifier (const Cond_lim_base &la_cl) const
double get_temps_defaut () const
void set_temps_defaut (double temps)
virtual void changer_temps_futur (double temps, int i)
virtual int avancer (double temps)
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe
en parametre.
virtual int reculer (double temps)
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe
en parametre.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_front_synt & self_cast (Objet_U &)
static const Champ_front_synt & self_cast (const Objet_U &)
Static Public Member Functions inherited from Ch_front_var_instationnaire_dep
static Objet_U * cree_instance ()
static const Type_info * info ()
static Ch_front_var_instationnaire_dep & self_cast (Objet_U &)
static const Ch_front_var_instationnaire_dep & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var_instationnaire
static const Type_info * info ()
static Champ_front_var_instationnaire & self_cast (Objet_U &)
static const Champ_front_var_instationnaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var
static const Type_info * info ()
static Champ_front_var & self_cast (Objet_U &)
static const Champ_front_var & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_base
static const Type_info * info ()
static Champ_front_base & self_cast (Objet_U &)
static const Champ_front_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Ch_front_var_instationnaire_dep
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var_instationnaire
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Impression sur un flot de sortie au format:
taille
valeur(0) ... valeur(i) ... valeur(taille-1)
Entree & readOn (Entree &) override
Lecture a partir d'un flot d'entree au format:
nombre_de_composantes
moyenne moyenne(0) ... moyenne(nombre_de_composantes-1)
moyenne amplitude(0) ... amplitude(nombre_de_composantes-1)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
const double amp = 1.452762113
const double pi =2.*acos(0.)
const double Cmu =0.09
Ref_Champ_Inc_base ref_inco_
DoubleVect moyenne
DoubleVect dir_fluct
int nbModes
double lenghtScale
echelle integrale en espace
double timeScale
echelle integrale en temps
double turbKinEn
energie cinetique turbulente (k)
double turbDissRate
taux de dissipation turbulente (epsilon)
double KeOverKmin
double ratioCutoffWavenumber
au lieu de prendre kappa_mesh comme plus grand nombre d'onde, on prend kappa_mesh/ratioCutoffWavenumber (ratioCutoffWavenumber>1 permet de mieux discretiser les fluctuations => aspect plus lisse)
double temps_d_avant_
Protected Attributes inherited from Champ_front_var_instationnaire
DoubleTab Gpoint_
Taux d'accroissement du champ.
Protected Attributes inherited from Champ_front_base
double temps_defaut
Le temps pris par defaut quand le parametre n'est pas specifie. Ce sera en particulier celui utilise par les operateurs et les solveurs.
Ref_Frontiere_dis_base la_frontiere_dis
Roue_ptr les_valeurs
Les valeurs du champ.
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
classe Champ_front_synt
Classe derivee de Champ_front_base
Definition at line 35 of file Champ_front_synt.h.
Constructor & Destructor Documentation
Champ_front_synt()
Champ_front_synt::Champ_front_synt ()
Definition at line 30 of file Champ_front_synt.cpp.
~Champ_front_synt()
Champ_front_synt::~Champ_front_synt ()
Definition at line 30 of file Champ_front_synt.cpp.
Member Function Documentation
affecter_()
Champ_front_base & Champ_front_synt::affecter_ (const Champ_front_base & ch) override virtual
Pas code !!
Returns
Champ_front_base&
Signification:
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 253 of file Champ_front_synt.cpp.
{
  return *this;
}
cree_instance()
Objet_U * Champ_front_synt::cree_instance () static
Definition at line 30 of file Champ_front_synt.cpp.
duplique()
int Champ_front_synt::duplique () const override virtual
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 30 of file Champ_front_synt.cpp.
get_info()
const Type_info * Champ_front_synt::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 30 of file Champ_front_synt.cpp.
info()
const Type_info * Champ_front_synt::info () static
Definition at line 30 of file Champ_front_synt.cpp.
initialiser()
int Champ_front_synt::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Mise a jour du temps.
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 60 of file Champ_front_synt.cpp.
{
  if (!Ch_front_var_instationnaire_dep::initialiser(tps,inco))
    return 0;
  ref_inco_ = inco;
  temps_d_avant_ = tps;
  return 1;
}
References Ch_front_var_instationnaire_dep::initialiser(), ref_inco_, and temps_d_avant_.
mettre_a_jour()
void Champ_front_synt::mettre_a_jour (double temps) override virtual
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
!< donnees d'initialisation ///
< real only
< recuperation des faces
< Attention : contains real + virtual faces
< on prend la racine de l'aire moyenne des faces d'entree pour avoir une taille de maille caracteristique
!< valeurs remarquables du nombre d'onde ///
< plus grand nombre d'onde (depend du maillage)
< pic d'energie
< nombre d'onde de Kolmogorov
< plus petit nombre d'onde double delta_kappa = (min(kappa_eta,kappa_max) - kappa_min) / nbModes; // repartition lineaire des modes => pas bon
< repartition logarithmique des modes => OK
!< generation aleatoire des angles ///
< pour une densite de probabilite de 0.5*sin(theta) => OK
!< creation vecteur onde en coordonnee cartesienne ///
!< creation de la direction orthogonal au vecteur onde ///
< repartition logarithmique Cerr << "Kappa(n) = " << kappa_face(i) << finl;
!< recuperation des centres de gravite ///
!< MISE EN PLACE AUTOCORRELATION ///
Reimplemented from Champ_front_base.
Definition at line 258 of file Champ_front_synt.cpp.
{
// Acceder a l'equation depuis l'inconnue, ensuite acceder au milieu
  const Equation_base& equ = ref_inco_.valeur().equation();
  const Milieu_base& mil = equ.milieu();
  /*
    Cerr << "*************************************************" << finl;
    Cerr << "mil = " << mil.masse_volumique().valeur()(0,0) << finl;
    Cerr << "temps = " << equ.inconnue().temps() << finl;
    Cerr << "dt = " << equ.schema_temps().pas_de_temps() << finl;
    Cerr << "visco cinematique = " << ref_cast(Fluide_base,mil).viscosite_cinematique().valeur()(0,0) << finl;
    Cerr << "visco dynamique = " << ref_cast(Fluide_base,mil).viscosite_dynamique().valeur()(0,0) << finl;
    Cerr << "*************************************************" << finl;
    const Champ_Don& visco = ref_cast(Fluide_base,mil).viscosite_dynamique();
    if (sub_type(Champ_Uniforme,visco.valeur()))
      Cerr << "visco dynamique = " << visco(0,0) << finl;
    else
      {
        const DoubleTab& val_visco = visco.valeur().valeurs();
        Cerr << "valeurs viscosite = " << val_visco << finl;\
      }
  */
//
  ///!<            donnees d'initialisation        ///
//
  double visc = ref_cast(Fluide_base,mil).viscosite_cinematique().valeur()(0,0);
  const Front_VF& front = ref_cast(Front_VF,la_frontiere_dis.valeur());
  int nb_face = front.nb_faces(); //!< real only
  const Faces& tabFaces = front.frontiere().faces(); //!< recuperation des faces
// Cerr << "We store : temps_d_avant_ = "<<temps_d_avant_<<finl;
  DoubleTab& tab_avant=valeurs_au_temps(temps_d_avant_);
  DoubleTab& tab=valeurs_au_temps(temps);
  DoubleVect aireFaces; //!< Attention : contains real + virtual faces
  tabFaces.calculer_surfaces(aireFaces);
  double sum_aire=0.;
  for(int i=0; i<nb_face; i++)
    sum_aire += aireFaces[i];
  sum_aire = mp_sum(sum_aire);
  double dmin = sqrt( sum_aire / mp_sum(nb_face) ) ; //!< on prend la racine de l'aire moyenne des faces d'entree pour avoir une taille de maille caracteristique
// double Uref = 0.; // vitesse de reference = norme du vecteur moyenne
// for (int i=0; i<moyenne.size_reelle(); i++) Uref += moyenne(i)*moyenne(i);
// Uref = sqrt(Uref);
// double turbScale = turbIntensity * Uref; //urms=I*Uref
// double turbKinEn = 3./2. * (turbIntensity * Uref) * (turbIntensity * Uref); // evaluation de l'energie cinetique turbulente = 3/2*(I*Uref)^2
// double turbDissRate = pow(Cmu,0.75)*pow(turbKinEn,1.5)/lenghtScale; // calcul de epsilon pour un ecoulement etabli en conduite. A faire pour un ecoulement de grille ? (decroissance energetique)
//
  ///!< valeurs remarquables du nombre d'onde ///
//
  double kappa_max = (pi/dmin)*ratioCutoffWavenumber; //!< plus grand nombre d'onde (depend du maillage)
  double kappa_e = 9*pi*amp/(55*lenghtScale); //!< pic d'energie
  double kappa_eta = pow((turbDissRate/(visc*visc*visc)),0.25); //!< nombre d'onde de Kolmogorov
  double kappa_min = kappa_e / KeOverKmin; //!< plus petit nombre d'onde double delta_kappa = (min(kappa_eta,kappa_max) - kappa_min) / nbModes; // repartition lineaire des modes => pas bon
//
  double delta_kappa = pow( (std::min(kappa_eta,kappa_max) / kappa_min ), 1./(nbModes-1.)); //!< repartition logarithmique des modes => OK
// Cerr << "Remarkable wavenumbers for the method of synthetic turbulence generation:" << finl;
// Cerr << "kappa_min = " << kappa_min << finl;
// Cerr << "kappa_e = " << kappa_e << finl;
// Cerr << "kappa_mesh = " << kappa_max << finl;
// Cerr << "kappa_eta = " << kappa_eta << finl;
// Cerr << "delta_kappa = " << delta_kappa << finl;
  DoubleVect kappa_face(nbModes+1);
  DoubleVect kappa_center(nbModes);
  DoubleVect dkn(nbModes);
  DoubleVect kappa_x(nbModes);
  DoubleVect kappa_y(nbModes);
  DoubleVect kappa_z(nbModes);
  DoubleVect sigma_x(nbModes);
  DoubleVect sigma_y(nbModes);
  DoubleVect sigma_z(nbModes);
  DoubleVect phi(nbModes);
  DoubleVect alpha(nbModes);
  DoubleVect psi(nbModes);
  DoubleVect tetha(nbModes);
//
  ///!< generation aleatoire des angles      ///
//
  for(int i = 0; i<nbModes; i++)
    {
      phi(i) = drand48()* 2*pi ;
      alpha(i) = drand48()* 2*pi ;
      psi(i) = drand48()* 2*pi ;
// tetha(i) = drand48()* pi ; // pour une densite de probabilite de 1/pi => pas bon
      tetha(i) = acos(1-2*drand48()) ; //!< pour une densite de probabilite de 0.5*sin(theta) => OK
      ///!< creation vecteur onde en coordonnee cartesienne ///
      kappa_x(i) = sin(tetha(i))*cos(phi(i));
      kappa_y(i) = sin(tetha(i))*sin(phi(i));
      kappa_z(i) = cos(tetha(i));
      ///!< creation de la direction orthogonal au vecteur onde ///
      sigma_x(i) = cos(phi(i))*cos(tetha(i))*cos(alpha(i)) - sin(phi(i))*sin(alpha(i));
      sigma_y(i) = sin(phi(i))*cos(tetha(i))*cos(alpha(i)) + cos(phi(i))*sin(alpha(i));
      sigma_z(i) = -sin(tetha(i))*cos(alpha(i));
    }
// for(int i = 0; i< nbModes+1; i++) kappa_face(i) = kappa_min + delta_kappa*i; // repartition lineaire
  for(int i = 0; i< nbModes+1; i++)
    {
      kappa_face(i) = kappa_min * pow(delta_kappa,i); //!< repartition logarithmique Cerr << "Kappa(n) = " << kappa_face(i) << finl;
//
    }
  for(int i = 0; i< nbModes; i++)
    {
      kappa_center(i) = 1.0/2.0*(kappa_face(i+1)+kappa_face(i));
      dkn(i) = kappa_face(i+1)- kappa_face(i);
    }
  ///!< recuperation des centres de gravite ///
  DoubleTab centreGrav(nb_face);
  tabFaces.calculer_centres_gravite(centreGrav);
  for( int i = 0; i<nb_face; i++ )
    {
      DoubleTab turb(nb_comp());
// recuperer les points du milieu du maillage
      double x_center = centreGrav(i,0);
      double y_center = centreGrav(i,1);
      double z_center = centreGrav(i,2);
      for(int m = 0; m<nbModes; m++)
        {
          double kx = kappa_x(m) * kappa_center(m);
          double ky = kappa_y(m) * kappa_center(m);
          double kz = kappa_z(m) * kappa_center(m);
          double arg = kx*x_center + ky*y_center + kz*z_center + psi(m);
          double tfunk = cos(arg);
          double karman_spectrum = amp/kappa_e * (2.*turbKinEn/3.) * pow((kappa_center(m)/kappa_e),4)/pow(1+pow(kappa_center(m)/kappa_e, 2),17.0/6.0) * exp(-2*(pow(kappa_center(m)/kappa_eta, 2)));
          double amplitude = sqrt(karman_spectrum * dkn(m));
          turb(0) += 2*amplitude*tfunk*sigma_x(m);
          turb(1) += 2*amplitude*tfunk*sigma_y(m);
          turb(2) += 2*amplitude*tfunk*sigma_z(m);
// Cerr << "Kappa = " << kappa_center(m) << finl;
// Cerr << "Kappa, Spectre = " << kappa_center(m) << " , " << karman_spectrum << finl;
// Cerr << "Amplitude = " << amplitude << finl;
        }
//
      ///!< MISE EN PLACE AUTOCORRELATION  ///
//
      double dt = equ.schema_temps().pas_de_temps();
      double a = exp(-dt/timeScale);
      double b = sqrt(1-a*a);
      tab(i,0) = moyenne(0) + dir_fluct(0) * (a * (tab_avant(i,0) - moyenne(0)) + b * turb(0));
      tab(i,1) = moyenne(1) + dir_fluct(1) * (a * (tab_avant(i,1) - moyenne(1)) + b * turb(1));
      tab(i,2) = moyenne(2) + dir_fluct(2) * (a * (tab_avant(i,2) - moyenne(2)) + b * turb(2));
// Cerr << "r, a, b = " << dt/timeScale << " , " << a << " , " << b << finl;
// Cerr << "Uprime, uprime = " << tab(i,0) << " , " << turb(0) << finl;
// Cerr << "face, Uprime, uprime = " << i << " , " << tab(i,0) << " , " << turb(0) << finl;
    }
  tab.echange_espace_virtuel();
  temps_d_avant_ = temps;
}
References amp, Faces::calculer_centres_gravite(), Faces::calculer_surfaces(), dir_fluct, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), Frontiere::faces(), Frontiere_dis_base::frontiere(), KeOverKmin, Champ_front_base::la_frontiere_dis, lenghtScale, Equation_base::milieu(), moyenne, Process::mp_sum(), Field_base::nb_comp(), Front_VF::nb_faces(), nbModes, Schema_Temps_base::pas_de_temps(), pi, ratioCutoffWavenumber, ref_cast, ref_inco_, Equation_base::schema_temps(), temps_d_avant_, timeScale, turbDissRate, turbKinEn, Ref_Champ_Inc_base::valeur(), Ref_Frontiere_dis_base::valeur(), and Champ_front_var_instationnaire::valeurs_au_temps().
printOn()
Sortie & Champ_front_synt::printOn (Sortie & os) const override protected virtual
Impression sur un flot de sortie au format:
taille
valeur(0) ... valeur(i) ... valeur(taille-1)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 48 of file Champ_front_synt.cpp.
{
  const DoubleTab& tab=valeurs();
  os << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    os << tab(0,i);
  return os;
}
References TRUSTVect< _TYPE_ >::size(), and Champ_front_base::valeurs().
readOn()
Entree & Champ_front_synt::readOn (Entree & is) override protected virtual
Lecture a partir d'un flot d'entree au format:
nombre_de_composantes
moyenne moyenne(0) ... moyenne(nombre_de_composantes-1)
moyenne amplitude(0) ... amplitude(nombre_de_composantes-1)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 91 of file Champ_front_synt.cpp.
{
  timeScale = 0.;
  lenghtScale = 0.;
  nbModes = 0;
  turbKinEn = 0.;
  turbDissRate = 0.;
  KeOverKmin = 0.;
  ratioCutoffWavenumber = 0;
  int dim;
  dim=lire_dimension(is,que_suis_je());
  if( dim != 3)
    {
      Cerr << "Error the dimension must be equal to 3" << finl;
      exit();
    }
  Motcle motlu;
  Motcles les_mots(9);
  les_mots[0]="moyenne";
  les_mots[1]="lenghtScale";
  les_mots[2]="nbModes";
  les_mots[3]="turbKinEn";
  les_mots[4]="turbDissRate";
  les_mots[5]="KeOverKmin";
  les_mots[6]="timeScale";
  les_mots[7]="ratioCutoffWavenumber";
  les_mots[8]="dir_fluct";
  is >> motlu;
  if (motlu != "{")
    {
      Cerr << "Error while reading Champ_front_synt" << finl;
      Cerr << "We expected a { instead of " << motlu << finl;
      exit();
    }
  int cpt = 0;
  is >> motlu;
  while (motlu!="}")
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0:
          {
            cpt++;
            moyenne.resize(dim);
            fixer_nb_comp(dim);
            for(int i=0; i<dim; i++)
              is >> moyenne(i);
            break;
          }
        case 1:
          {
            cpt++;
            is >> lenghtScale;
            break;
          }
        case 2:
          {
            cpt++;
            is >> nbModes;
            break;
          }
        case 3:
          {
            cpt++;
            is >> turbKinEn;
            break;
          }
        case 4:
          {
            cpt++;
            is >> turbDissRate;
            break;
          }
        case 5:
          {
            cpt++;
            is >> KeOverKmin;
            break;
          }
        case 6:
          {
            cpt++;
            is >> timeScale;
            break;
          }
        case 7:
          {
            cpt++;
            is >> ratioCutoffWavenumber;
            break;
          }
        case 8:
          {
            cpt++;
            dir_fluct.resize(dim);
            fixer_nb_comp(dim);
            for(int i=0; i<dim; i++)
              {
                is >> dir_fluct(i);
              }
            break;
          }
        default :
          {
            if (motlu == "p")
              {
                Cerr << "Error while reading Champ_front_synt:" << finl;
                Cerr << "  Parameter " << motlu << " has been renamed to KeOverKmin since TRUST v1.9.0"<< finl;
                Cerr << "  Update your datafile."<< finl;
              }
            else
              {
                Cerr << "Error while reading Champ_front_synt:" << finl;
                Cerr << "  " << motlu << "is not understood."<< finl;
                Cerr << "  We are expecting a parameter among " << les_mots << finl;
              }
            exit();
          }
        }
      is >> motlu;
    }
  if(cpt != 9)
    {
      Cerr << "Error while reading Champ_front_synt: wrong number of parameters" << finl;
      Cerr << "You should specify all these parameters: " << les_mots << finl;
      exit();
    }
  if( lenghtScale == 0 || nbModes == 0 || turbKinEn == 0 || turbDissRate == 0 || KeOverKmin == 0 || timeScale == 0 || ratioCutoffWavenumber == 0 )
    {
      Cerr << "Error while reading Champ_front_synt" << finl;
      Cerr << "There is at least one parameter among: timeScale, lenghtScale, nbModes, turbKinEn, turbDissRate and ratioCutoffWavenumber set to 0" << finl;
      exit();
    }
  for(int i=0; i<dim; i++)
    {
      Cerr << dir_fluct(i) << " ";
    }
  Cerr << finl;
  return is;
}
References Cerr, dir_fluct, Process::exit(), finl, Field_base::fixer_nb_comp(), KeOverKmin, lenghtScale, Champ_Proto::lire_dimension(), moyenne, nbModes, Objet_U::que_suis_je(), ratioCutoffWavenumber, TRUSTVect< _TYPE_ >::resize(), Motcles::search(), timeScale, turbDissRate, and turbKinEn.
self_cast() [1/2]
const Champ_front_synt & Champ_front_synt::self_cast (const Objet_U & r) static
Definition at line 30 of file Champ_front_synt.cpp.
self_cast() [2/2]
Champ_front_synt & Champ_front_synt::self_cast (Objet_U & r) static
Definition at line 30 of file Champ_front_synt.cpp.
taille_memoire()
unsigned Champ_front_synt::taille_memoire () const override virtual
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 30 of file Champ_front_synt.cpp.
Member Data Documentation
amp
const double Champ_front_synt::amp = 1.452762113 protected
Definition at line 39 of file Champ_front_synt.h.
Referenced by mettre_a_jour().
Cmu
const double Champ_front_synt::Cmu =0.09 protected
Definition at line 41 of file Champ_front_synt.h.
dir_fluct
DoubleVect Champ_front_synt::dir_fluct protected
Definition at line 53 of file Champ_front_synt.h.
Referenced by mettre_a_jour(), and readOn().
info_obj
const Type_info Champ_front_synt::info_obj static
Definition at line 37 of file Champ_front_synt.h.
KeOverKmin
double Champ_front_synt::KeOverKmin protected
Definition at line 60 of file Champ_front_synt.h.
Referenced by mettre_a_jour(), and readOn().
lenghtScale
double Champ_front_synt::lenghtScale protected
echelle integrale en espace
Definition at line 56 of file Champ_front_synt.h.
Referenced by mettre_a_jour(), and readOn().
moyenne
DoubleVect Champ_front_synt::moyenne protected
Definition at line 52 of file Champ_front_synt.h.
Referenced by mettre_a_jour(), and readOn().
nbModes
int Champ_front_synt::nbModes protected
Definition at line 55 of file Champ_front_synt.h.
Referenced by mettre_a_jour(), and readOn().
pi
const double Champ_front_synt::pi =2.*acos(0.) protected
Definition at line 40 of file Champ_front_synt.h.
Referenced by mettre_a_jour().
ratioCutoffWavenumber
double Champ_front_synt::ratioCutoffWavenumber protected
au lieu de prendre kappa_mesh comme plus grand nombre d'onde, on prend kappa_mesh/ratioCutoffWavenumber (ratioCutoffWavenumber>1 permet de mieux discretiser les fluctuations => aspect plus lisse)
Definition at line 61 of file Champ_front_synt.h.
Referenced by mettre_a_jour(), and readOn().
ref_inco_
Ref_Champ_Inc_base Champ_front_synt::ref_inco_ protected
Definition at line 50 of file Champ_front_synt.h.
Referenced by initialiser(), and mettre_a_jour().
temps_d_avant_
double Champ_front_synt::temps_d_avant_ protected
Definition at line 62 of file Champ_front_synt.h.
Referenced by initialiser(), and mettre_a_jour().
timeScale
double Champ_front_synt::timeScale protected
echelle integrale en temps
Definition at line 57 of file Champ_front_synt.h.
Referenced by mettre_a_jour(), and readOn().
turbDissRate
double Champ_front_synt::turbDissRate protected
taux de dissipation turbulente (epsilon)
Definition at line 59 of file Champ_front_synt.h.
Referenced by mettre_a_jour(), and readOn().
turbKinEn
double Champ_front_synt::turbKinEn protected
energie cinetique turbulente (k)
Definition at line 58 of file Champ_front_synt.h.
Referenced by mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Champs/Champ_front_synt.h
src/ThHyd/Incompressible/Champs/Champ_front_synt.cpp