TRUST: ExtrudeParoi Class Reference
ExtrudeParoi Class Reference
Classe ExtrudeParoi
Cette classe est un interprete qui sert a lire et executer
la directive ExtrudeParoi:
ExtrudeParoi nom_domaine
Cette directive est a utiliser en discretisation VEF 2D pour obtenir
un maillage 3D par extrusion puis decoupage.
#include <ExtrudeParoi.h>
Public Member Functions
~ExtrudeParoi ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
ExtrudeParoi ()
Entree & interpreter_ (Entree &) override
Fonction principale de l'interprete ExtrudeParoi
Creation d'une couche de prismes en paroi<br>(prismes tetraedrises en 3)
void extrude (Domaine &)
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static ExtrudeParoi & self_cast (Objet_U &)
static const ExtrudeParoi & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Protected Member Functions inherited from Interprete_geometrique_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom nom_front
int nb_couche
ArrOfDouble epaisseur
int type
int projection_normale_bord
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Classe ExtrudeParoi
Cette classe est un interprete qui sert a lire et executer
la directive ExtrudeParoi:
ExtrudeParoi nom_domaine
Cette directive est a utiliser en discretisation VEF 2D pour obtenir
un maillage 3D par extrusion puis decoupage.
Definition at line 37 of file ExtrudeParoi.h.
Constructor & Destructor Documentation
~ExtrudeParoi()
ExtrudeParoi::~ExtrudeParoi ()
Definition at line 27 of file ExtrudeParoi.cpp.
ExtrudeParoi()
ExtrudeParoi::ExtrudeParoi ()
Definition at line 29 of file ExtrudeParoi.cpp.
{
  projection_normale_bord=1;
  nb_couche=1;
  type=0;
  epaisseur.resize_array(1);
  epaisseur[0]=0.5;
}
References epaisseur, nb_couche, projection_normale_bord, TRUSTArray< _TYPE_ >::resize_array(), and type.
Member Function Documentation
cree_instance()
Objet_U * ExtrudeParoi::cree_instance () static
Definition at line 27 of file ExtrudeParoi.cpp.
duplique()
int ExtrudeParoi::duplique () const override virtual
Implements Objet_U.
Definition at line 27 of file ExtrudeParoi.cpp.
extrude()
void ExtrudeParoi::extrude (Domaine & dom)
< Tableau dont on aura pas besoin
< les nouveaux sommets
< les nouveaux elements
< sommet rattache a l'element frontiere
< sommet de la face frontiere
< sommets de la face frontiere
< traduction de l'epaisseur relative en epaisseur absolue
< creation des nouveaux sommets rattaches a la paroi
< creation des nouveaux sommets rattaches aux couches successives
< translation des anciens sommets
Definition at line 153 of file ExtrudeParoi.cpp.
{
  Zone& zone = dom.zone(0);
  if  (zone.type_elem()->que_suis_je() == "Tetraedre")
    {
      Cerr << "ExtrudeParoi ..... " << finl;
    }
  else
    {
      Cerr << "The " << zone.type_elem()->que_suis_je() <<"s are not treated with ExtrudeParoi"<<finl;
      exit();
    }
  IntTab& les_elems = zone.les_elems();
  int oldsz = les_elems.dimension(0);
  int nbs = zone.nb_som();
  IntTab elem_traite(oldsz);
  int oldnbsom = zone.nb_som();
  Faces lesfaces;
// zone.creer_faces(les_faces);
  {
// bloc a factoriser avec Zone_VF.cpp :
    Type_Face type_face = zone.type_elem().type_face(0);
    lesfaces.typer(type_face);
    lesfaces.associer_zone(zone);
    Static_Int_Lists connectivite_som_elem;
    const int     nb_sommets_tot = zone.domaine().nb_som_tot();
    const IntTab&    elements       = zone.les_elems();
    construire_connectivite_som_elem(nb_sommets_tot,
                                     elements,
                                     connectivite_som_elem,
                                     1 /* include virtual elements */);
    Faces_builder faces_builder;
    IntTab elem_faces; //!< Tableau dont on aura pas besoin
    faces_builder.creer_faces_reeles(zone,
                                     connectivite_som_elem,
                                     lesfaces,
                                     elem_faces);
  }
  ArrOfDouble ep_abs(epaisseur);
  IntTab& faces_voisins = lesfaces.voisins();
  DoubleTab& coord=dom.les_sommets();
  IntList  List_som;
  IntTab som_arete;
  DoubleTab  normale_som(nbs,3);
  normale_som=0.;
  DoubleVect dmin_som(nbs);
  dmin_som=1e6;
  DoubleTab new_soms;                //!< les nouveaux sommets
  IntTab new_elems;                 //!< les nouveaux elements
  for (int l=0; l<zone.nb_front_Cl(); l++)
    {
      const Frontiere& fr=zone.frontiere(l);
      const Nom& nomfr=fr.le_nom();
      if(nomfr==nom_front)
        {
          int nbfaces=fr.nb_faces();
          int ndeb = fr.num_premiere_face();
          const IntTab& sommet=fr.les_sommets_des_faces();
          new_elems.resize(oldsz+nbfaces*3*nb_couche,4);
          new_elems.inject_array(les_elems);
          som_arete.resize(3*nbfaces,2);
          ArrOfInt som_elem(4); //!< sommet rattache a l'element frontiere
          ArrOfInt som_face(3); //!< sommet de la face frontiere
          ArrOfDouble pt0(3),pt1(3),pt2(3),pt_ext(3);
          ArrOfDouble normale(3),vect_int(3);
// calcul de la normale portee par chaque sommet de la frontiere
//
          int compt=0;
          for (int i=0; i<nbfaces; i++)
            {
              int elem=faces_voisins(i+ndeb,0);
              if (elem==-1) elem=faces_voisins(i+ndeb,1);
              for(int j=0; j<4; j++)   som_elem[j]=les_elems(elem,j);
              for(int j=0; j<3; j++)
                {
                  som_face[j]=sommet(i,j);
                  List_som.add_if_not(som_face[j]) ;
                }
// rangt par ordre croissant des sommets
              int stot=som_face[0]+som_face[1]+som_face[2];
              int som0=min_array(som_face);
              int som2=max_array(som_face);
              int som1=stot-som0-som2;
              som_arete(compt,0)=som0;
              som_arete(compt,1)=som1;
              compt++;
              som_arete(compt,0)=som0;
              som_arete(compt,1)=som2;
              compt++;
              som_arete(compt,0)=som1;
              som_arete(compt,1)=som2;
              compt++;
              int som_ext=0;
              for(int j=0; j<4; j++)
                {
                  int ok=0;
                  for(int k=0; k<3; k++)
                    if(som_elem[j]==som_face[k]) ok=1;
                  if(ok==0)
                    {
                      som_ext=som_elem[j] ;
                      break;
                    }
                }
              for(int j=0; j<3; j++)
                {
                  pt0[j]=coord(som_face[0],j);
                  pt1[j]=coord(som_face[1],j);
                  pt2[j]=coord(som_face[2],j);
                  vect_int[j]=coord(som_ext,j)-pt0[j];
                }
              calcul_normal_norme2(pt0,pt1,pt2,normale);
              double dist_paroi = dotproduct_array(normale,vect_int);
              if (dist_paroi<0.) normale *=-1.;
              for(int k=0; k<3; k++)
                {
                  int som=som_face[k];
                  dmin_som(som) = std::min(dmin_som(som),std::fabs(dist_paroi));
                  for(int j=0; j<3; j++) normale_som(som,j) += normale[j];
                }
            }
        }//if(nomfr==nom_front)
    }//for (l<zone.nb_front_Cl()
  calcul_tab_norme(normale_som);
  Cerr << "minimum distance node-wall : "<< dmin_som.mp_min_vect()<< finl;
  if(type==1) Cerr << "thickness of the layer "<< ep_abs[nb_couche-1] << finl;
  if(type==1 && (dmin_som.mp_min_vect()<=ep_abs[nb_couche-1]))
    {
      Cerr << "Error !! The thickness of the layer is greater than the minimum distance node-wall" << finl;
      exit();
    }
// Recherche des aretes de nom_front partagee avec d'autres frontieres
//
  tri_lexicographique_tableau(som_arete);
  IntTab som_arete_bord(som_arete.dimension(0),3);
  int nba=som_arete.dimension(0);
  int compt=0;
  for(int i=1; i<nba; i++)
    {
      if( (som_arete(i,0)==som_arete(i-1,0)) && (som_arete(i,1)==som_arete(i-1,1)) ) i++;
      else
        {
          som_arete_bord(compt,0)=som_arete(i-1,0);
          som_arete_bord(compt,1)=som_arete(i-1,1);
          compt++;
          if(i==nba)
            {
              som_arete_bord(compt,0)=som_arete(i,0);
              som_arete_bord(compt,1)=som_arete(i,1);
              compt++;
            }
        }
    }
  int nba_bord=compt;
  som_arete_bord.resize(nba_bord,3);
  ArrOfInt corresp_bord(nba_bord);
  corresp_bord=-1;
  for (int num_front=0; num_front<zone.nb_front_Cl(); num_front++)
    {
      const Frontiere& fr=zone.frontiere(num_front);
      const Nom& nomfr=fr.le_nom();
      if(nomfr!=nom_front)
        {
          int nbfaces=fr.nb_faces();
          const IntTab& sommet=fr.les_sommets_des_faces();
          ArrOfInt som_face(3); //!< sommets de la face frontiere
          for (int i=0; i<nbfaces; i++)
            {
              for(int j=0; j<3; j++) som_face[j]=sommet(i,j);
              int stot=som_face[0]+som_face[1]+som_face[2];
              int som0=min_array(som_face);
              int som2=max_array(som_face);
              int som1=stot-som0-som2;
              for(int j=0; j<nba_bord; j++)
                {
                  if((som_arete_bord(j,0)==som0) && (som_arete_bord(j,1)==som1))
                    {
                      som_arete_bord(j,2)=som2;
                      corresp_bord[j]=num_front;
                      break;
                    }
                  if((som_arete_bord(j,0)==som0) && (som_arete_bord(j,1)==som2))
                    {
                      som_arete_bord(j,2)=som1;
                      corresp_bord[j]=num_front;
                      break;
                    }
                  if((som_arete_bord(j,0)==som1) && (som_arete_bord(j,1)==som2))
                    {
                      som_arete_bord(j,2)=som0;
                      corresp_bord[j]=num_front;
                      break;
                    }
                }
            }
        }
    }
  if(min_array(corresp_bord)==-1)
    {
      Cerr << "Problem with the boundary edges !!" << finl;
      exit();
    }
// projection de la normale de bord dans le plan de la frontiere voisine de bord
//
  if(projection_normale_bord)
    {
      ArrOfDouble pt1(3),pt2(3),pt3(3);
      ArrOfDouble n1(3),n2(3),n_proj(3);
      for(int i=0; i<nba_bord; i++)
        {
          int s1 = som_arete_bord(i,0);
          int s2 = som_arete_bord(i,1);
          int s3 = som_arete_bord(i,2);
          for(int j=0; j<3; j++)
            {
              n1[j]=normale_som(s1,j) ;
              n2[j]=normale_som(s2,j) ;
              pt1[j]=coord(s1,j);
              pt2[j]=coord(s2,j);
              pt3[j]=coord(s3,j);
            }
          calcul_normal_norme2(pt1,pt2,pt3,n_proj);
          double ori = dotproduct_array(n1,n_proj);
          if (ori<0.) n_proj *=-1.;
          double psc1=dotproduct_array(n1,n_proj);
          double psc2=dotproduct_array(n2,n_proj);
          for(int j=0; j<3; j++)
            {
              normale_som(s1,j) -= psc1*n_proj[j];
              normale_som(s2,j) -= psc2*n_proj[j];
            }
        }
    }
// creation des sommets de la couche prismatique
//
  int nb_som = List_som.size();
  int newnbsom = oldnbsom+nb_couche*nb_som;
  new_soms.resize(newnbsom,3);
  new_soms.inject_array(coord);
  for (int i=0; i<nb_som; i++)
    {
      int som=List_som[i];
      if(type==0) //!< traduction de l'epaisseur relative en epaisseur absolue
        {
          for(int j=0; j<nb_couche; j++) ep_abs[j]=epaisseur[j]*dmin_som(som);
        }
      for(int j=0; j<3; j++)
        {
          new_soms(oldnbsom+i,j) = new_soms(som,j); //!< creation des nouveaux sommets rattaches a la paroi
          if(nb_couche>1)                               //!< creation des nouveaux sommets rattaches aux couches successives
            for(int k=0; k<nb_couche-1; k++)
              new_soms(oldnbsom+(k+1)*nb_som+i,j) = new_soms(som,j)+ep_abs[k]*normale_som(som,j);
          new_soms(som,j) += ep_abs[nb_couche-1]*normale_som(som,j); //!< translation des anciens sommets
        }
    }
// creation des elements de la couche prismatique
//
  IntTab som_front;
  for (int l=0; l<zone.nb_front_Cl(); l++)
    {
      const Frontiere& fr=zone.frontiere(l);
      const Nom& nomfr=fr.le_nom();
      if(nomfr==nom_front)
        {
          int nbfaces=fr.nb_faces();
          const IntTab& sommet=fr.les_sommets_des_faces();
          som_front.resize(nbfaces,3);
          int cpt=0;
          for (int i=0; i<nbfaces; i++)
            {
              int s1=sommet(i,0);
              int s2=sommet(i,1);
              int s3=sommet(i,2);
              int stot=s1+s2+s3;
              int i1=std::min(std::min(s1,s2),s3);
              int i3=std::max(std::max(s1,s2),s3);
              int i2=stot-i1-i3;
              int i4=oldnbsom+List_som.rang(i1);
              int i5=oldnbsom+List_som.rang(i2);
              int i6=oldnbsom+List_som.rang(i3);
              som_front(i,0)=i4;
              som_front(i,1)=i5;
              som_front(i,2)=i6;
              for(int k=0; k<nb_couche; k++)
                {
// sommets sup de la couche
                  int ii1=i4+(k+1)*nb_som;
                  int ii2=i5+(k+1)*nb_som;
                  int ii3=i6+(k+1)*nb_som;
                  if(k==(nb_couche-1))
                    {
                      ii1=i1;
                      ii2=i2;
                      ii3=i3;
                    }
// sommets inf de la couche
                  int ii4=i4+k*nb_som;
                  int ii5=i5+k*nb_som;
                  int ii6=i6+k*nb_som;
// connectivite sommets-element inspiree de Extruder_en3
                  new_elems(oldsz+cpt,0) = ii1;
                  new_elems(oldsz+cpt,1) = ii2;
                  new_elems(oldsz+cpt,2) = ii3;
                  new_elems(oldsz+cpt,3) = ii6;
                  cpt++;
                  new_elems(oldsz+cpt,0) = ii1;
                  new_elems(oldsz+cpt,1) = ii2;
                  new_elems(oldsz+cpt,2) = ii5;
                  new_elems(oldsz+cpt,3) = ii6;
                  cpt++;
                  new_elems(oldsz+cpt,0) = ii1;
                  new_elems(oldsz+cpt,1) = ii4;
                  new_elems(oldsz+cpt,2) = ii5;
                  new_elems(oldsz+cpt,3) = ii6;
                  cpt++;
                  mettre_a_jour_sous_zone(zone,i,oldsz,0);
                }
            }
        }//if(nomfr==nom_front)
    }//for (l<zone.nb_front_Cl()
  coord.reset();
  dom.ajouter(new_soms);
  les_elems.ref(new_elems);
// Reconstruction de l'octree
  zone.invalide_octree();
  zone.typer("Tetraedre");
  Cerr << "  Reconstruction of the Octree" << finl;
  zone.construit_octree();
  Cerr << "  Octree rebuilt" << finl;
  {
    Cerr << "Reconstruction of the boundaries" << finl;
    LIST_CURSEUR(Bord) curseur(zone.faces_bord());;;
    int num_front=0;
    while(curseur)
      {
        Faces& lesfacesbord=curseur->faces();
        lesfacesbord.typer(Faces::triangle_3D);
        IntTab& sommets=lesfacesbord.les_sommets();
        if(curseur->le_nom()==nom_front)
          {
            sommets.ref(som_front);
          }
        else
          {
            IntTab som_front2(sommets);
            int nbf =lesfacesbord.nb_faces();
            int nbf2=0;
            for (int i=0; i<nba_bord; i++)
              if(corresp_bord[i]==num_front) nbf2++;
            som_front2.resize(nbf+2*nb_couche*nbf2,3);
            int compt2=nbf;
            for (int i=0; i<nba_bord; i++)
              if(corresp_bord[i]==num_front)
                {
                  int s1=som_arete_bord(i,0);
                  int s2=som_arete_bord(i,1);
                  int s1_new=oldnbsom+List_som.rang(s1);
                  int s2_new=oldnbsom+List_som.rang(s2);
                  for(int k=0; k<nb_couche; k++)
                    {
// sommets sup de la couche
                      int s1_sup=s1_new+(k+1)*nb_som;
                      int s2_sup=s2_new+(k+1)*nb_som;
                      if(k==(nb_couche-1))
{
                          s1_sup=s1;
                          s2_sup=s2;
                        }
// sommets inf de la couche
                      int s1_inf=s1_new+k*nb_som;
                      int s2_inf=s2_new+k*nb_som;
                      som_front2(compt2,0)=s1_sup;
                      som_front2(compt2,1)=s2_sup;
                      som_front2(compt2,2)=s2_inf;
                      compt2++;
                      som_front2(compt2,0)=s1_sup;
                      som_front2(compt2,1)=s1_inf;
                      som_front2(compt2,2)=s2_inf;
                      compt2++;
                    }
                }
            sommets.ref(som_front2);
          }
        num_front++;
        ++curseur;
      }
  }
}
References TRUSTList< _TYPE_ >::add_if_not(), Domaine::ajouter(), Faces::associer_zone(), calcul_normal_norme2(), calcul_tab_norme(), Cerr, construire_connectivite_som_elem(), Zone::construit_octree(), Faces_builder::creer_faces_reeles(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), dotproduct_array(), epaisseur, Process::exit(), Zone::faces_bord(), finl, Zone::frontiere(), TRUSTArray< _TYPE_ >::inject_array(), Zone::invalide_octree(), Frontiere::le_nom(), Zone::les_elems(), Domaine::les_sommets(), Faces::les_sommets(), Frontiere::les_sommets_des_faces(), LIST_CURSEUR, max_array(), Interprete_geometrique_base::mettre_a_jour_sous_zone(), min_array(), TRUSTVect< _TYPE_ >::mp_min_vect(), nb_couche, Faces::nb_faces(), Frontiere::nb_faces(), Zone::nb_front_Cl(), Zone::nb_som(), Domaine::nb_som_tot(), nom_front, Frontiere::num_premiere_face(), projection_normale_bord, Objet_U::que_suis_je(), TRUSTList< _TYPE_ >::rang(), TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::reset(), TRUSTTab< _TYPE_ >::resize(), TRUSTList< _TYPE_ >::size(), tri_lexicographique_tableau(), Faces::triangle_3D, type, Zone::type_elem(), Elem_geom::type_face(), Faces::typer(), Zone::typer(), Faces::voisins(), and Domaine::zone().
Referenced by interpreter_().
get_info()
const Type_info * ExtrudeParoi::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 27 of file ExtrudeParoi.cpp.
info()
const Type_info * ExtrudeParoi::info () static
Definition at line 27 of file ExtrudeParoi.cpp.
interpreter_()
Entree & ExtrudeParoi::interpreter_ (Entree & is) override virtual
Fonction principale de l'interprete ExtrudeParoi
Creation d'une couche de prismes en paroi<br>(prismes tetraedrises en 3)
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Implements Interprete_geometrique_base.
Definition at line 121 of file ExtrudeParoi.cpp.
{
  Nom nom_dom;
  Param param(que_suis_je());
  param.ajouter("domaine",&nom_dom,Param::REQUIRED);
  param.ajouter("nom_bord",&nom_front,Param::REQUIRED);
  param.ajouter("epaisseur",&epaisseur);
  param.ajouter_flag("critere_absolu",&type);
  param.ajouter("projection_normale_bord",&projection_normale_bord);
  param.lire_avec_accolades_depuis(is);
  epaisseur.array_trier_retirer_doublons();
  nb_couche=epaisseur.size_array();
  associer_domaine(nom_dom);
  Scatter::uninit_sequential_domain(domaine());
  extrude(domaine());
  Scatter::init_sequential_domain(domaine());
  return is;
}
References Param::ajouter(), Param::ajouter_flag(), TRUSTArray< _TYPE_ >::array_trier_retirer_doublons(), Interprete_geometrique_base::associer_domaine(), Interprete_geometrique_base::domaine(), epaisseur, extrude(), Scatter::init_sequential_domain(), Param::lire_avec_accolades_depuis(), nb_couche, nom_front, projection_normale_bord, Objet_U::que_suis_je(), Param::REQUIRED, TRUSTArray< _TYPE_ >::size_array(), type, and Scatter::uninit_sequential_domain().
printOn()
Sortie & ExtrudeParoi::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 52 of file ExtrudeParoi.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & ExtrudeParoi::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 99 of file ExtrudeParoi.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const ExtrudeParoi & ExtrudeParoi::self_cast (const Objet_U & r) static
Definition at line 27 of file ExtrudeParoi.cpp.
self_cast() [2/2]
ExtrudeParoi & ExtrudeParoi::self_cast (Objet_U & r) static
Definition at line 27 of file ExtrudeParoi.cpp.
taille_memoire()
unsigned ExtrudeParoi::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 27 of file ExtrudeParoi.cpp.
Member Data Documentation
epaisseur
ArrOfDouble ExtrudeParoi::epaisseur protected
Definition at line 51 of file ExtrudeParoi.h.
Referenced by extrude(), ExtrudeParoi(), and interpreter_().
info_obj
const Type_info ExtrudeParoi::info_obj static
Definition at line 39 of file ExtrudeParoi.h.
nb_couche
int ExtrudeParoi::nb_couche protected
Definition at line 50 of file ExtrudeParoi.h.
Referenced by extrude(), ExtrudeParoi(), and interpreter_().
nom_front
Nom ExtrudeParoi::nom_front protected
Definition at line 49 of file ExtrudeParoi.h.
Referenced by extrude(), and interpreter_().
projection_normale_bord
int ExtrudeParoi::projection_normale_bord protected
Definition at line 53 of file ExtrudeParoi.h.
Referenced by extrude(), ExtrudeParoi(), and interpreter_().
type
int ExtrudeParoi::type protected
Definition at line 52 of file ExtrudeParoi.h.
Referenced by extrude(), ExtrudeParoi(), and interpreter_().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/ExtrudeParoi.h
src/Kernel/Geometrie/ExtrudeParoi.cpp