TRUST: Integrale_tps_Champ Class Reference
Integrale_tps_Champ Class Reference
class Integrale_tps_Champ
#include <Integrale_tps_Champ.h>
Public Member Functions
Integrale_tps_Champ ()
~Integrale_tps_Champ ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Ref_Champ_Generique_base & le_champ () const
double temps_integrale () const
double t_debut () const
le temps courant de l'integrale
double t_fin () const
le temps de debut d'integration
double dt_integration () const
le temps de fin d'integration
void fixer_t_debut (double t)
la duree d'integration deja effectuee
void fixer_t_fin (double t)
Fixe le temps de debut d'integration.
void fixer_dt_integr (double t)
Fixe le temps de fin d'integration.
void fixer_tps_integrale (double t)
Fixe la valeur de tps_integrale.
void associer (const Champ_base &, int, double, double)
Fixe le temps courant de l'integrale (derniere date a laquelle on a mis l'integrale a jour)
void associer (const Champ_Generique_base &, int, double, double)
virtual void mettre_a_jour (double)
Appel a l'objet sous-jacent
Effectue une mise a jour en temps.
virtual void mettre_a_jour_integrale ()
Mets a jour l'integrale.
Verifie que le temps de l'integrale est inferieur a celui du
champ associe et poursuit l'integration jusqu'au temps courant.
si la borne superieure de l'integrale n'est pas depassee.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Integrale_tps_Champ & self_cast (Objet_U &)
static const Integrale_tps_Champ & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture d'un Champ_Fonc sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'un Champ_Fonc sur un flot d'entree.
Protected Attributes
Ref_Champ_Generique_base mon_champ
int puissance
double t_debut_
double t_fin_
double tps_integrale
double dt_integr_calcul
Detailed Description
class Integrale_tps_Champ
Definition at line 38 of file Integrale_tps_Champ.h.
Constructor & Destructor Documentation
Integrale_tps_Champ::Integrale_tps_Champ ()
Definition at line 25 of file Integrale_tps_Champ.cpp.
Integrale_tps_Champ::~Integrale_tps_Champ ()
Definition at line 25 of file Integrale_tps_Champ.cpp.
Member Function Documentation
void Integrale_tps_Champ::associer (const Champ_base & le_ch, int n, double t0, double t1) [inline]
Fixe le temps courant de l'integrale (derniere date a laquelle on a mis l'integrale a jour)
Definition at line 101 of file Integrale_tps_Champ.h.
Referenced by Op_Moyenne::associer(), and Op_Ecart_type::associer().
{
}
void Integrale_tps_Champ::associer (const Champ_Generique_base & le_ch, int n, double t0, double t1) [inline]
Definition at line 106 of file Integrale_tps_Champ.h.
References dt_integr_calcul, mon_champ, puissance, t_debut_, t_fin_, and tps_integrale.
{
  mon_champ= le_ch;
  puissance = n;
  t_debut_ = t0;
  t_fin_ = t1;
  tps_integrale =t_debut_;
  dt_integr_calcul=0;
}
Objet_U * Integrale_tps_Champ::cree_instance () [static]
Reimplemented from Champ_Fonc.
Reimplemented in Integrale_tps_produit_champs.
Definition at line 25 of file Integrale_tps_Champ.cpp.
double Integrale_tps_Champ::dt_integration () const [inline]
le temps de fin d'integration
Definition at line 60 of file Integrale_tps_Champ.h.
References dt_integr_calcul.
Referenced by Op_Moyenne::dt_integration(), Op_Correlation::dt_integration_ab(), and Op_Ecart_type::dt_integration_carre().
  {
    return dt_integr_calcul;
  };//!< la duree d'integration deja effectuee
int Integrale_tps_Champ::duplique () const [virtual]
Reimplemented from Champ_Fonc.
Reimplemented in Integrale_tps_produit_champs.
Definition at line 25 of file Integrale_tps_Champ.cpp.
void Integrale_tps_Champ::fixer_dt_integr (double t) [inline]
Fixe le temps de fin d'integration.
Definition at line 72 of file Integrale_tps_Champ.h.
References dt_integr_calcul.
Referenced by Op_Moyenne::fixer_tstat_deb(), Op_Ecart_type::fixer_tstat_deb(), and Op_Correlation::fixer_tstat_deb().
  {
    dt_integr_calcul= t;
  };//!< Fixe la valeur de tps_integrale
void Integrale_tps_Champ::fixer_t_debut (double t) [inline]
la duree d'integration deja effectuee
Definition at line 64 of file Integrale_tps_Champ.h.
References t_debut_.
Referenced by Op_Moyenne::fixer_tstat_deb(), Op_Ecart_type::fixer_tstat_deb(), and Op_Correlation::fixer_tstat_deb().
  {
    t_debut_ = t;
  };                //!< Fixe le temps de debut d'integration
void Integrale_tps_Champ::fixer_t_fin (double t) [inline]
Fixe le temps de debut d'integration.
Definition at line 68 of file Integrale_tps_Champ.h.
References t_fin_.
Referenced by Op_Moyenne::fixer_tstat_fin(), Op_Ecart_type::fixer_tstat_fin(), and Op_Correlation::fixer_tstat_fin().
  {
    t_fin_ = t;
  };                //!< Fixe le temps de fin d'integration
void Integrale_tps_Champ::fixer_tps_integrale (double t) [inline]
Fixe la valeur de tps_integrale.
Definition at line 76 of file Integrale_tps_Champ.h.
References tps_integrale.
Referenced by Op_Moyenne::fixer_tstat_deb(), Op_Ecart_type::fixer_tstat_deb(), and Op_Correlation::fixer_tstat_deb().
  {
    tps_integrale = t;
  };        //!< Fixe le temps courant de l'integrale (derniere date a laquelle on a mis l'integrale a jour)
const Type_info * Integrale_tps_Champ::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc.
Reimplemented in Integrale_tps_produit_champs.
Definition at line 25 of file Integrale_tps_Champ.cpp.
const Type_info * Integrale_tps_Champ::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc.
Reimplemented in Integrale_tps_produit_champs.
Definition at line 25 of file Integrale_tps_Champ.cpp.
const Ref_Champ_Generique_base& Integrale_tps_Champ::le_champ (void) const [inline]
Definition at line 44 of file Integrale_tps_Champ.h.
References mon_champ.
Referenced by Op_Moyenne::completer(), Op_Ecart_type::completer(), Op_Correlation::completer(), Operateur_Statistique_tps_base::completer_post_statistiques(), Champ_Generique_Statistiques_base::completer_post_statistiques(), Champ_Generique_Moyenne::get_champ(), Champ_Generique_Ecart_Type::get_champ(), and Champ_Generique_Correlation::get_directive_pour_discr().
  {
    return mon_champ;
  };
void Integrale_tps_Champ::mettre_a_jour (double un_temps) [inline, virtual]
Appel a l'objet sous-jacent
Effectue une mise a jour en temps.
Reimplemented from Champ_Fonc.
Reimplemented in Integrale_tps_produit_champs.
Definition at line 116 of file Integrale_tps_Champ.h.
References Champ_Fonc::changer_temps(), mettre_a_jour_integrale(), and mon_champ.
Referenced by Op_Moyenne::mettre_a_jour(), and Op_Ecart_type::mettre_a_jour().
{
  mettre_a_jour_integrale();
  Champ espace_stockage_source;
  double le_temps = mon_champ->get_time();
  changer_temps(le_temps);
}
void Integrale_tps_Champ::mettre_a_jour_integrale () [virtual]
Mets a jour l'integrale.
Verifie que le temps de l'integrale est inferieur a celui du
champ associe et poursuit l'integration jusqu'au temps courant.
si la borne superieure de l'integrale n'est pas depassee.
Reimplemented in Integrale_tps_produit_champs.
Definition at line 60 of file Integrale_tps_Champ.cpp.
References DoubleVect::ajoute(), DoubleVect::ajoute_carre(), Cerr, dt_integr_calcul, Process::exit(), finl, inf_ou_egal(), mon_champ, puissance, DoubleVect::size(), t_debut_, t_fin_, tps_integrale, Champ_Fonc::valeurs(), and Champ_Proto::valeurs().
Referenced by mettre_a_jour().
{
  Champ espace_stockage_source;
  const Champ_base& source = mon_champ->get_champ(espace_stockage_source);
  double t_courant = mon_champ->get_time();
  if (t_fin_ < t_debut_)
    {
      Cerr << " Statistic begining and ending times are not coherent " << finl;
      Cerr << " t_fin_=" << t_fin_ << " < t_debut_=" << t_debut_ << finl;
      exit();
    }
  if ( inf_ou_egal(t_debut_ ,t_courant) &&  inf_ou_egal(t_courant,t_fin_) )
    {
      double dt = t_courant - tps_integrale;
      if (dt > 0)
        {
          const DoubleTab& val = source.valeurs();
          DoubleTab& mes_val = valeurs();
          if (puissance == 1)
            mes_val.ajoute(dt,val);
          else if (puissance == 2)
            mes_val.ajoute_carre(dt,val);
          else
            for (int i=0; i<val.size(); i++)
              mes_val[i] += dt*pow(val[i],puissance);
          tps_integrale = t_courant;
          dt_integr_calcul += dt;
        }
    }
}
Sortie & Integrale_tps_Champ::printOn (Sortie & s) const [protected, virtual]
Ecriture d'un Champ_Fonc sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Fonc.
Reimplemented in Integrale_tps_produit_champs.
Definition at line 30 of file Integrale_tps_Champ.cpp.
References O_U_Ptr::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Integrale_tps_Champ::readOn (Entree & s) [protected, virtual]
Lecture d'un Champ_Fonc sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Fonc.
Reimplemented in Integrale_tps_produit_champs.
Definition at line 38 of file Integrale_tps_Champ.cpp.
{
  return s ;
}
const Integrale_tps_Champ & Integrale_tps_Champ::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc.
Reimplemented in Integrale_tps_produit_champs.
Definition at line 25 of file Integrale_tps_Champ.cpp.
Integrale_tps_Champ & Integrale_tps_Champ::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc.
Reimplemented in Integrale_tps_produit_champs.
Definition at line 25 of file Integrale_tps_Champ.cpp.
double Integrale_tps_Champ::t_debut () const [inline]
le temps courant de l'integrale
Definition at line 52 of file Integrale_tps_Champ.h.
References t_debut_.
  {
    return t_debut_;
  };        //!< le temps de debut d'integration
double Integrale_tps_Champ::t_fin () const [inline]
le temps de debut d'integration
Definition at line 56 of file Integrale_tps_Champ.h.
References t_fin_.
  {
    return t_fin_;
  };           //!<  le temps de fin d'integration
unsigned Integrale_tps_Champ::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc.
Reimplemented in Integrale_tps_produit_champs.
Definition at line 25 of file Integrale_tps_Champ.cpp.
double Integrale_tps_Champ::temps_integrale () const [inline]
Definition at line 48 of file Integrale_tps_Champ.h.
References tps_integrale.
  {
    return tps_integrale;
  }; //!< le temps courant de l'integrale
Member Data Documentation
double Integrale_tps_Champ::dt_integr_calcul [protected]
Definition at line 92 of file Integrale_tps_Champ.h.
Referenced by associer(), dt_integration(), fixer_dt_integr(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), and mettre_a_jour_integrale().
const Type_info Integrale_tps_Champ::info_obj [static]
Reimplemented from Champ_Fonc.
Reimplemented in Integrale_tps_produit_champs.
Definition at line 40 of file Integrale_tps_Champ.h.
Ref_Champ_Generique_base Integrale_tps_Champ::mon_champ [protected]
Definition at line 87 of file Integrale_tps_Champ.h.
Referenced by associer(), le_champ(), Integrale_tps_produit_champs::mettre_a_jour(), mettre_a_jour(), mettre_a_jour_integrale(), and Integrale_tps_produit_champs::mon_premier_champ().
int Integrale_tps_Champ::puissance [protected]
Definition at line 88 of file Integrale_tps_Champ.h.
Referenced by associer(), mettre_a_jour_integrale(), and Integrale_tps_produit_champs::premiere_puissance().
double Integrale_tps_Champ::t_debut_ [protected]
Definition at line 89 of file Integrale_tps_Champ.h.
Referenced by associer(), fixer_t_debut(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), mettre_a_jour_integrale(), and t_debut().
double Integrale_tps_Champ::t_fin_ [protected]
Definition at line 90 of file Integrale_tps_Champ.h.
Referenced by associer(), fixer_t_fin(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), mettre_a_jour_integrale(), and t_fin().
double Integrale_tps_Champ::tps_integrale [protected]
Definition at line 91 of file Integrale_tps_Champ.h.
Referenced by associer(), fixer_tps_integrale(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), mettre_a_jour_integrale(), and temps_integrale().
The documentation for this class was generated from the following files:
src/Kernel/Statistiques_temps/Integrale_tps_Champ.h
src/Kernel/Statistiques_temps/Integrale_tps_Champ.cpp