TRUST: VEFPreP1B Class Reference
VEFPreP1B Class Reference
#include <VEFPreP1B.h>
Public Member Functions
VEFPreP1B ()
~VEFPreP1B ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const
Discretisation d'un champ pour le VEFP1B en fonction d'une directive
de discretisation. La directive est un Motcle comme "pression",
"divergence_vitesse" (cree un champ de type P1_isoP1Bulle).
Cette methode determine le type du champ a creer en fonction du type d'element
et de la directive de discretisation. Elle determine ensuite le nombre de ddl
et fixe l'ensemble des parametres du champ (type, nb_compo, nb_ddl, nb_pas_dt,
nom(s), unite(s), nature du champ et attribue un temps) et associe la Zone_dis au champ.
Voir le code pour avoir la correspondance entre les directives et
le type de champ cree.
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Fonc &champ) const
Idem que VEFPreP1B::discretiser_champ(... , Champ_Inc)
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Don &champ) const
Idem que VEFPreP1B::discretiser_champ(... , Champ_Inc)
void zone_Cl_dis (Zone_dis &z, Zone_Cl_dis &zcl) const
int get_P1Bulle () const
int get_alphaE () const
int get_alphaS () const
int get_alphaA () const
int get_modif_div_face_dirichlet () const
int get_cl_pression_sommet_faible () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static VEFPreP1B & self_cast (Objet_U &)
static const VEFPreP1B & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN.
virtual Entree & readOn (Entree &)
NE FAIT RIEN.
Private Member Functions
void discretiser_champ_fonc_don (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Objet_U &champ) const
Idem que VEF_discretisation::discretiser_champ(... , Champ_Inc)
Traitement commun aux champ_fonc et champ_don.
Cette methode est privee (passage d'un Objet_U pas propre vu
de l'exterieur ...)
void discretiser (Domaine_dis &) const
Private Attributes
int P1Bulle_
int alphaE_
int alphaS_
int alphaA_
int modif_div_face_dirichlet_
int cl_pression_sommet_faible_
determine si les cl de pression sont imposees de facon faible ou forte -> voir divergence et assembleur, zcl
Detailed Description
Definition at line 30 of file VEFPreP1B.h.
Constructor & Destructor Documentation
VEFPreP1B::VEFPreP1B ()
Definition at line 38 of file VEFPreP1B.cpp.
                     : P1Bulle_(1), alphaE_(1), alphaS_(1), alphaA_(0), modif_div_face_dirichlet_(0), cl_pression_sommet_faible_(0)
{
// Par defaut, P0+P1 et changement de base pour faire P0+P1->P1Bulle
}
VEFPreP1B::~VEFPreP1B ()
Definition at line 35 of file VEFPreP1B.cpp.
Member Function Documentation
Objet_U * VEFPreP1B::cree_instance () [static]
Reimplemented from VEF_discretisation.
Definition at line 35 of file VEFPreP1B.cpp.
void VEFPreP1B::discretiser (Domaine_dis & dom) const [private, virtual]
Reimplemented from Discretisation_base.
Definition at line 284 of file VEFPreP1B.cpp.
References Zone_VEF_PreP1b::discretiser_suite(), ref_cast, Deriv_Zone_dis_base::valeur(), and Domaine_dis::zone_dis().
{
  Discretisation_base::discretiser(dom);
  Zone_VEF_PreP1b& zvef = ref_cast(Zone_VEF_PreP1b, dom.zone_dis(0).valeur());
  zvef.discretiser_suite(*this);
}
void VEFPreP1B::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc & champ, const Nom & sous_type = nom_vide) const [virtual]
Discretisation d'un champ pour le VEFP1B en fonction d'une directive
de discretisation. La directive est un Motcle comme "pression",
"divergence_vitesse" (cree un champ de type P1_isoP1Bulle).
Cette methode determine le type du champ a creer en fonction du type d'element
et de la directive de discretisation. Elle determine ensuite le nombre de ddl
et fixe l'ensemble des parametres du champ (type, nb_compo, nb_ddl, nb_pas_dt,
nom(s), unite(s), nature du champ et attribue un temps) et associe la Zone_dis au champ.
Voir le code pour avoir la correspondance entre les directives et
le type de champ cree.
< Choix standard pour la pression
< Le type de champ obtenu en calculant div v
< Valeur par defaut du nombre de composantes
< c'est le descripteur p1b qui donnera le chiffre
Reimplemented from VEF_discretisation.
Definition at line 107 of file VEFPreP1B.cpp.
References Cerr, Discretisation_base::creer_champ(), Discretisation_base::demande_description, Process::exit(), finl, multi_scalaire, Objet_U::que_suis_je(), and Motcles::search().
Referenced by discretiser_champ_fonc_don().
{
  Motcles motcles(2);
  motcles[0] = "pression";    //!< Choix standard pour la pression
  motcles[1] = "divergence_vitesse"; //!< Le type de champ obtenu en calculant div v
  Nom type;
  int default_nb_comp = 0; //!< Valeur par defaut du nombre de composantes
  int rang = motcles.search(directive);
  switch(rang)
    {
    case 0:
      type = "Champ_P1_isoP1Bulle";
      default_nb_comp = 1;
      break;
    case 1:
      type = "Champ_P1_isoP1Bulle";
      default_nb_comp = 1;
      break;
    default:
      assert(rang < 0);
      break;
    }
  if (directive == demande_description)
    Cerr << "VEFPreP1B : " << motcles;
// Si on n'a pas compris la directive (ou si c'est une demande_description)
// alors on appelle l'ancetre :
  if (rang < 0)
    {
      VEF_discretisation::discretiser_champ(directive, z,
                                            nature, noms, unites,
                                            nb_comp, nb_pas_dt, temps, champ);
      return;
    }
  const int nb_ddl = -1; //!< c'est le descripteur p1b qui donnera le chiffre
  if (nb_comp < 0)
    nb_comp = default_nb_comp;
  assert(nb_comp > 0);
  creer_champ(champ, z, type, noms[0], unites[0], nb_comp, nb_ddl, nb_pas_dt, temps,
              directive, que_suis_je());
  if (nature == multi_scalaire)
    {
      Cerr<<"There is no field of type Champ_Inc with P1Bulle discretization"<<finl;
      Cerr<<"and a multi_scalaire nature."<<finl;
      exit();
    }
}
void VEFPreP1B::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Champ_Fonc & champ) const [virtual]
Idem que VEFPreP1B::discretiser_champ(... , Champ_Inc)
Reimplemented from VEF_discretisation.
Definition at line 167 of file VEFPreP1B.cpp.
References discretiser_champ_fonc_don().
{
  discretiser_champ_fonc_don(directive, z,
                             nature, noms, unites,
                             nb_comp, temps, champ);
}
void VEFPreP1B::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Champ_Don & champ) const [virtual]
Idem que VEFPreP1B::discretiser_champ(... , Champ_Inc)
Reimplemented from VEF_discretisation.
Definition at line 181 of file VEFPreP1B.cpp.
References discretiser_champ_fonc_don().
{
  discretiser_champ_fonc_don(directive, z,
                             nature, noms, unites,
                             nb_comp, temps, champ);
}
void VEFPreP1B::discretiser_champ_fonc_don (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Objet_U & champ) const [private]
Idem que VEF_discretisation::discretiser_champ(... , Champ_Inc)
Traitement commun aux champ_fonc et champ_don.
Cette methode est privee (passage d'un Objet_U pas propre vu
de l'exterieur ...)
< Choix standard pour la pression
< Le type de champ obtenu en calculant div v
< Valeur par defaut du nombre de composantes
< c'est le descripteur p1b qui donnera le chiffre
Reimplemented from VEF_discretisation.
Definition at line 197 of file VEFPreP1B.cpp.
References Cerr, Discretisation_base::creer_champ(), Discretisation_base::demande_description, discretiser_champ(), Process::exit(), finl, multi_scalaire, Objet_U::que_suis_je(), ref_cast, Motcles::search(), and sub_type.
Referenced by discretiser_champ().
{
// Deux pointeurs pour acceder facilement au champ_don ou au champ_fonc,
// suivant le type de l'objet champ.
  Champ_Fonc * champ_fonc = 0;
  Champ_Don * champ_don = 0;
  if (sub_type(Champ_Fonc, champ))
    champ_fonc = & ref_cast(Champ_Fonc, champ);
  else
    champ_don  = & ref_cast(Champ_Don, champ);
  Motcles motcles(2);
  motcles[0] = "pression";    //!< Choix standard pour la pression
  motcles[1] = "divergence_vitesse"; //!< Le type de champ obtenu en calculant div v
  Nom type;
  int default_nb_comp = 0; //!< Valeur par defaut du nombre de composantes
  int rang = motcles.search(directive);
  switch(rang)
    {
    case 0:
      type = "Champ_Fonc_P1_isoP1Bulle";
      default_nb_comp = 1;
      break;
    case 1:
      type = "Champ_Fonc_P1_isoP1Bulle";
      default_nb_comp = 1;
      break;
    default:
      assert(rang < 0);
      break;
    }
  if (directive == demande_description)
    Cerr << "VEFPreP1B : " << motcles;
// Si on n'a pas compris la directive (ou si c'est une demande_description)
// alors on appelle l'ancetre :
  if (rang < 0)
    {
      if (champ_fonc)
        VEF_discretisation::discretiser_champ(directive, z, nature, noms, unites,
                                              nb_comp, temps, *champ_fonc);
      else
        VEF_discretisation::discretiser_champ(directive, z, nature, noms, unites,
                                              nb_comp, temps, *champ_don);
      return;
    }
  int nb_ddl = -1; //!< c'est le descripteur p1b qui donnera le chiffre
  if (nb_comp < 0)
    nb_comp = default_nb_comp;
  assert(nb_comp > 0);
  if (champ_fonc)
    creer_champ(*champ_fonc, z, type, noms[0], unites[0], nb_comp, nb_ddl, temps,
                directive, que_suis_je());
  else
    creer_champ(*champ_don, z, type, noms[0], unites[0], nb_comp, nb_ddl, temps,
                directive, que_suis_je());
  if (nature == multi_scalaire)
    {
      Cerr<<"There is no field of type Champ_Fonc or Champ_Don with P1Bulle discretization"<<finl;
      Cerr<<"and a multi_scalaire nature."<<finl;
      exit();
    }
}
int VEFPreP1B::duplique () const [virtual]
Reimplemented from VEF_discretisation.
Definition at line 35 of file VEFPreP1B.cpp.
int VEFPreP1B::get_alphaA () const [inline]
Definition at line 68 of file VEFPreP1B.h.
References alphaA_.
Referenced by Zone_VEF_PreP1b::discretiser_suite().
  {
    return alphaA_;
  };
int VEFPreP1B::get_alphaE () const [inline]
Definition at line 60 of file VEFPreP1B.h.
References alphaE_.
Referenced by Zone_VEF_PreP1b::discretiser_suite().
  {
    return alphaE_;
  };
int VEFPreP1B::get_alphaS () const [inline]
Definition at line 64 of file VEFPreP1B.h.
References alphaS_.
Referenced by Zone_VEF_PreP1b::discretiser_suite().
  {
    return alphaS_;
  };
int VEFPreP1B::get_cl_pression_sommet_faible () const [inline]
Definition at line 76 of file VEFPreP1B.h.
References cl_pression_sommet_faible_.
Referenced by Zone_VEF_PreP1b::discretiser_suite().
  {
    return cl_pression_sommet_faible_;
  };
const Type_info * VEFPreP1B::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from VEF_discretisation.
Definition at line 35 of file VEFPreP1B.cpp.
int VEFPreP1B::get_modif_div_face_dirichlet () const [inline]
Definition at line 72 of file VEFPreP1B.h.
References modif_div_face_dirichlet_.
Referenced by Zone_VEF_PreP1b::discretiser_suite().
  {
    return modif_div_face_dirichlet_;
  };
int VEFPreP1B::get_P1Bulle () const [inline]
Definition at line 56 of file VEFPreP1B.h.
References P1Bulle_.
Referenced by Zone_VEF_PreP1b::discretiser_suite().
  {
    return P1Bulle_;
  };
const Type_info * VEFPreP1B::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from VEF_discretisation.
Definition at line 35 of file VEFPreP1B.cpp.
Sortie & VEFPreP1B::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from VEF_discretisation.
Definition at line 44 of file VEFPreP1B.cpp.
References alphaA_, alphaE_, alphaS_, cl_pression_sommet_faible_, finl, Objet_U::le_nom(), modif_div_face_dirichlet_, and P1Bulle_.
{
  s<<"lire "<<le_nom()<<" { " <<finl;
  if (alphaE_) s<<" P0";
  if (alphaS_) s<<" P1";
  if (alphaA_) s<<" Pa";
  s<<" changement_de_base_P1bulle "<<P1Bulle_;
  s<<" modif_div_face_dirichlet "<<modif_div_face_dirichlet_;
  s<<" cl_pression_sommet_faible " << cl_pression_sommet_faible_;
  s<<" } "<<finl;
  return s;
}
Entree & VEFPreP1B::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
< XD_ADD_P int (into=[0,1]) changement_de_base_p1bulle 1 This option may be used to have the P1NC/P0P1 formulation (value set to 0) or the P1NC/P1Bulle formulation (value set to 1, the default).
< XD_ADD_P rien Pressure nodes are added on element centres
< XD_ADD_P rien Pressure nodes are added on vertices
< XD_ADD_P rien Only available in 3D, pressure nodes are added on bones
< XD_ADD_P int (into=[0,1]) This option (by default 0) is used to extend control volumes for the momentum equation.
< XD_ADD_P int (into=[0,1]) This option is used to specify a strong formulation (value set to 0, the default) or a weak formulation (value set to 1) for an imposed pressure boundary condition. The first formulation converges quicker and is stable in general cases. The second formulation should be used if there are several outlet boundaries with Neumann condition (see Ecoulement_Neumann test case for example).
Reimplemented from VEF_discretisation.
Definition at line 57 of file VEFPreP1B.cpp.
References Param::ajouter(), Param::ajouter_flag(), alphaA_, alphaE_, alphaS_, Cerr, cl_pression_sommet_faible_, Objet_U::dimension, Process::exit(), finl, Param::lire_avec_accolades(), modif_div_face_dirichlet_, P1Bulle_, and Objet_U::que_suis_je().
{
  alphaE_ = alphaS_ = alphaA_ = P1Bulle_ = 0;
  cl_pression_sommet_faible_ = 1;
  modif_div_face_dirichlet_=0;
  Param param(que_suis_je());
  param.ajouter("changement_de_base_P1bulle", &P1Bulle_); //!< XD_ADD_P int (into=[0,1]) changement_de_base_p1bulle 1 This option may be used to have the P1NC/P0P1 formulation (value set to 0) or the P1NC/P1Bulle formulation (value set to 1, the default).
  param.ajouter_flag("P0", &alphaE_); //!< XD_ADD_P rien Pressure nodes are added on element centres
  param.ajouter_flag("P1", &alphaS_); //!< XD_ADD_P rien Pressure nodes are added on vertices
  param.ajouter_flag("Pa", &alphaA_); //!< XD_ADD_P rien Only available in 3D, pressure nodes are added on bones
  param.ajouter("modif_div_face_dirichlet",&modif_div_face_dirichlet_); //!< XD_ADD_P  int (into=[0,1]) This option (by default 0) is used to extend control volumes for the momentum equation.
  param.ajouter("CL_pression_sommet_faible", &cl_pression_sommet_faible_); //!< XD_ADD_P  int (into=[0,1]) This option is used to specify a strong formulation (value set to 0, the default) or a weak formulation (value set to 1) for an imposed pressure boundary condition. The first formulation converges quicker and is stable in general cases. The second formulation should be used if there are several outlet boundaries with Neumann condition (see Ecoulement_Neumann test case for example).
  param.lire_avec_accolades(is);
// Quelques verifications
  if (dimension!=3 && alphaA_)
    {
      Cerr << "Le support Pa n'est disponible qu'en 3D." << finl;
      Process::exit();
    }
  if (alphaE_+alphaS_+alphaA_==0)
    {
      Cerr << "Il faut choisir au moins un support parmi P0, P1, Pa." << finl;
      Process::exit();
    }
  if (alphaA_==1 && !alphaE_)
    {
      Cerr << "Les discretisations Pa ou P1+Pa ne sont pas encore supportees." << finl;
      Process::exit();
    }
  if (P1Bulle_)
    if (!( (alphaE_==1) && (alphaS_==1) && (alphaA_==0)))
      {
        Cerr << "L'option changement_de_base_P1bulle n'est disponible qu'en P0/P1" << finl;
        Process::exit();
      }
  return is;
}
VEFPreP1B & VEFPreP1B::self_cast (Objet_U & r) [static]
Reimplemented from VEF_discretisation.
Definition at line 35 of file VEFPreP1B.cpp.
const VEFPreP1B & VEFPreP1B::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from VEF_discretisation.
Definition at line 35 of file VEFPreP1B.cpp.
unsigned VEFPreP1B::taille_memoire () const [virtual]
Reimplemented from VEF_discretisation.
Definition at line 35 of file VEFPreP1B.cpp.
void VEFPreP1B::zone_Cl_dis (Zone_dis & z, Zone_Cl_dis & zcl) const [virtual]
Reimplemented from VEF_discretisation.
Definition at line 271 of file VEFPreP1B.cpp.
References Cerr, finl, O_U_Ptr::non_nul(), ref_cast, Deriv_::typer(), Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  Cerr << "discretisation des conditions limites" << finl;
  assert(z.non_nul());
  Zone_VEF& zone_VEF=ref_cast(Zone_VEF, z.valeur());
  zcl.typer("Zone_Cl_VEFP1B");
  assert(zcl.non_nul());
  Zone_Cl_VEFP1B& zone_Cl_VEF=ref_cast(Zone_Cl_VEFP1B, zcl.valeur());
  zone_Cl_VEF.associer(zone_VEF);
  Cerr << "discretisation des conditions limites OK" << finl;
}
Member Data Documentation
int VEFPreP1B::alphaA_ [private]
Definition at line 93 of file VEFPreP1B.h.
Referenced by get_alphaA(), printOn(), and readOn().
int VEFPreP1B::alphaE_ [private]
Definition at line 91 of file VEFPreP1B.h.
Referenced by get_alphaE(), printOn(), and readOn().
int VEFPreP1B::alphaS_ [private]
Definition at line 92 of file VEFPreP1B.h.
Referenced by get_alphaS(), printOn(), and readOn().
int VEFPreP1B::cl_pression_sommet_faible_ [private]
determine si les cl de pression sont imposees de facon faible ou forte -> voir divergence et assembleur, zcl
Definition at line 95 of file VEFPreP1B.h.
Referenced by get_cl_pression_sommet_faible(), printOn(), and readOn().
const Type_info VEFPreP1B::info_obj [static]
Reimplemented from VEF_discretisation.
Definition at line 33 of file VEFPreP1B.h.
int VEFPreP1B::modif_div_face_dirichlet_ [private]
Definition at line 94 of file VEFPreP1B.h.
Referenced by get_modif_div_face_dirichlet(), printOn(), and readOn().
int VEFPreP1B::P1Bulle_ [private]
Definition at line 90 of file VEFPreP1B.h.
Referenced by get_P1Bulle(), printOn(), and readOn().
The documentation for this class was generated from the following files:
src/P1NCP1B/Zones/VEFPreP1B.h
src/P1NCP1B/Zones/VEFPreP1B.cpp