TRUST: List_Objet_a_lire Class Reference
List_Objet_a_lire Class Reference
#include <Objet_a_lire.h>
Public Member Functions
List_Objet_a_lire ()
~List_Objet_a_lire ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
List_Objet_a_lire (const Objet_a_lire &t)
List_Objet_a_lire (const List_Objet_a_lire &t)
Objet_a_lire & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Objet_a_lire & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Objet_a_lire & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Objet_a_lire & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Objet_a_lire & operator() (int i)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Objet_a_lire & operator() (int i) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Objet_a_lire & operator() (const Nom &n)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Objet_a_lire & operator() (const Nom &n) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Objet_a_lire & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Objet_a_lire & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
List_Objet_a_lire & operator= (const Objet_a_lire &t)
Objet_a_lire * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
List_Objet_a_lire & operator= (const List_Objet_a_lire &)
List_Objet_a_lire & add (const List_Objet_a_lire &)
Objet_a_lire & add (const Objet_a_lire &)
List_Objet_a_lire & inserer (const List_Objet_a_lire &)
Objet_a_lire & inserer (const Objet_a_lire &)
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
List_Objet_a_lire & operator+= (const List_Objet_a_lire &)
List_Objet_a_lire & operator+= (const Objet_a_lire &)
Objet_a_lire & add_if_not (const Objet_a_lire &)
Objet_a_lire & add_if_not (const char *const)
List_Objet_a_lire & search (const Objet_a_lire &) const
List_Objet_a_lire & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
List_Objet_a_lire & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
const List_Objet_a_lire & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
const List_Objet_a_lire & dernier () const
Renvoie le dernier element de la liste.
List_Objet_a_lire & dernier ()
Renvoie le dernier element de la liste.
List_Objet_a_lire & operator-= (const Objet_a_lire &)
int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
int contient (const Objet_a_lire &) const
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
int rang (const Objet_a_lire &) const
void suppr (const Objet_a_lire &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static List_Objet_a_lire & self_cast (Objet_U &)
static const List_Objet_a_lire & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture d'une liste sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'une liste sur un flot d'entree.
int est_egal_a (const List_Objet_a_lire &) const
Detailed Description
Definition at line 90 of file Objet_a_lire.h.
Constructor & Destructor Documentation
List_Objet_a_lire::List_Objet_a_lire ()
Definition at line 29 of file Objet_a_lire.cpp.
List_Objet_a_lire::~List_Objet_a_lire ()
Definition at line 29 of file Objet_a_lire.cpp.
List_Objet_a_lire::List_Objet_a_lire (const Objet_a_lire & t) [inline]
Definition at line 90 of file Objet_a_lire.h.
List_Objet_a_lire::List_Objet_a_lire (const List_Objet_a_lire & t) [inline]
Definition at line 90 of file Objet_a_lire.h.
Member Function Documentation
List_Objet_a_lire & List_Objet_a_lire::add (const List_Objet_a_lire & a_list) [inline]
Definition at line 90 of file Objet_a_lire.h.
Referenced by Param::check(), and Param::create_or_get_objet_a_lire().
Objet_a_lire & List_Objet_a_lire::add (const Objet_a_lire & t) [inline]
Definition at line 90 of file Objet_a_lire.h.
Objet_a_lire & List_Objet_a_lire::add_if_not (const Objet_a_lire & t) [inline]
Definition at line 90 of file Objet_a_lire.h.
Objet_a_lire & List_Objet_a_lire::add_if_not (const char * const t) [inline]
Definition at line 90 of file Objet_a_lire.h.
int List_Objet_a_lire::contient (const Objet_a_lire & t) const [inline]
Definition at line 90 of file Objet_a_lire.h.
int List_Objet_a_lire::contient (const char * const ch) const [inline]
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
Returns:
int
Signification: 1 si la liste contient un Objet_U de Nom ch, 0 sinon
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
Objet_U * List_Objet_a_lire::cree_instance () [static]
Reimplemented from liste.
Definition at line 29 of file Objet_a_lire.cpp.
const List_Objet_a_lire& List_Objet_a_lire::dernier () const [inline]
Renvoie le dernier element de la liste.
Returns:
const liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented from liste.
List_Objet_a_lire & List_Objet_a_lire::dernier () [inline]
Renvoie le dernier element de la liste.
Returns:
liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
int List_Objet_a_lire::duplique () const [virtual]
Reimplemented from liste.
Definition at line 29 of file Objet_a_lire.cpp.
int List_Objet_a_lire::est_egal_a (const Objet_U & x) const [virtual]
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
Reimplemented from Objet_U.
Definition at line 29 of file Objet_a_lire.cpp.
int List_Objet_a_lire::est_egal_a (const List_Objet_a_lire &) const [inline, protected]
const Type_info * List_Objet_a_lire::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from liste.
Definition at line 29 of file Objet_a_lire.cpp.
const Type_info * List_Objet_a_lire::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from liste.
Definition at line 29 of file Objet_a_lire.cpp.
List_Objet_a_lire & List_Objet_a_lire::inserer (const List_Objet_a_lire & a_list) [inline]
Definition at line 90 of file Objet_a_lire.h.
Objet_a_lire & List_Objet_a_lire::inserer (const Objet_a_lire & t) [inline]
Definition at line 90 of file Objet_a_lire.h.
const Objet_a_lire & List_Objet_a_lire::operator() (const Nom & nom) const [inline]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
Objet_a_lire & List_Objet_a_lire::operator() (const Nom & nom) [inline]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
const Objet_a_lire & List_Objet_a_lire::operator() (int i) const [inline]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
Objet_a_lire & List_Objet_a_lire::operator() (int i) [inline]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
List_Objet_a_lire & List_Objet_a_lire::operator+= (const Objet_a_lire & t) [inline]
Definition at line 90 of file Objet_a_lire.h.
List_Objet_a_lire & List_Objet_a_lire::operator+= (const List_Objet_a_lire & a_list) [inline]
Definition at line 90 of file Objet_a_lire.h.
List_Objet_a_lire & List_Objet_a_lire::operator-= (const Objet_a_lire & t) [inline]
Definition at line 90 of file Objet_a_lire.h.
Objet_a_lire * List_Objet_a_lire::operator-> () [inline]
Retourne un pointeur sur l'Objet_U premier element de la liste.
Returns:
Objet_U*
Signification: pointeur sur l'Objet_U premier element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
List_Objet_a_lire & List_Objet_a_lire::operator= (const Objet_a_lire & t) [inline]
Definition at line 90 of file Objet_a_lire.h.
List_Objet_a_lire & List_Objet_a_lire::operator= (const List_Objet_a_lire & a_list) [inline]
Definition at line 90 of file Objet_a_lire.h.
Objet_a_lire & List_Objet_a_lire::operator[] (int i) [inline]
Operateur d'acces au ieme element de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
Objet_a_lire & List_Objet_a_lire::operator[] (const Nom & nom) [inline]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
const Objet_a_lire & List_Objet_a_lire::operator[] (const Nom & nom) const [inline]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
const Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
const Objet_a_lire & List_Objet_a_lire::operator[] (int i) const [inline]
Operateur d'acces au ieme element de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
Sortie & List_Objet_a_lire::printOn (Sortie & os) const [protected, virtual]
Ecriture d'une liste sur un flot de sortie.
Returns:
Sortie&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from liste.
Definition at line 29 of file Objet_a_lire.cpp.
int List_Objet_a_lire::rang (const Objet_a_lire & t) const [inline]
Definition at line 90 of file Objet_a_lire.h.
Entree & List_Objet_a_lire::readOn (Entree & is) [protected, virtual]
Lecture d'une liste sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from liste.
Definition at line 29 of file Objet_a_lire.cpp.
List_Objet_a_lire & List_Objet_a_lire::search (const Objet_a_lire & t) const [inline]
Definition at line 90 of file Objet_a_lire.h.
List_Objet_a_lire & List_Objet_a_lire::search (const char * const ch) const [inline]
Recherche d'un Objet_U de Nom ch dans la liste.
Returns:
liste&
Signification: L'element de la liste trouve
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
const List_Objet_a_lire & List_Objet_a_lire::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from liste.
Definition at line 29 of file Objet_a_lire.cpp.
List_Objet_a_lire & List_Objet_a_lire::self_cast (Objet_U & r) [static]
Reimplemented from liste.
Definition at line 29 of file Objet_a_lire.cpp.
const List_Objet_a_lire & List_Objet_a_lire::suivant () const [inline]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
const liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
List_Objet_a_lire & List_Objet_a_lire::suivant () [inline]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
void List_Objet_a_lire::suppr (const Objet_a_lire & t) [inline]
Definition at line 90 of file Objet_a_lire.h.
Referenced by Param::supprimer().
void List_Objet_a_lire::supprimer () [inline]
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
unsigned List_Objet_a_lire::taille_memoire () const [virtual]
Reimplemented from liste.
Definition at line 29 of file Objet_a_lire.cpp.
const Objet_a_lire & List_Objet_a_lire::valeur () const [inline]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
const Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
Objet_a_lire & List_Objet_a_lire::valeur () [inline]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
Member Data Documentation
const Type_info List_Objet_a_lire::info_obj [static]
Reimplemented from liste.
Definition at line 90 of file Objet_a_lire.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Objet_a_lire.h
src/Kernel/Utilitaires/Objet_a_lire.cpp