TRUST: Champ_Fonc_Q1_base Class Reference
Champ_Fonc_Q1_base Class Reference
: class Champ_Fonc_Q1_base
Decrire ici la classe Champ_Fonc_Q1_base
#include <Champ_Fonc_Q1_base.h>
Public Member Functions
Champ_Fonc_Q1_base ()
~Champ_Fonc_Q1_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & valeur_aux_sommets (const Domaine &domain, DoubleTab &result) const
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &domain, DoubleVect &result, int ncomp) const
int fixer_nb_valeurs_nodales (int nb_noeuds)
Fixe le nombre de degres de liberte par composante.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Fonc_Q1_base & self_cast (Objet_U &)
static const Champ_Fonc_Q1_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Champ_base & le_champ (void)
virtual const Champ_base & le_champ (void) const
Detailed Description
: class Champ_Fonc_Q1_base
Decrire ici la classe Champ_Fonc_Q1_base
Definition at line 36 of file Champ_Fonc_Q1_base.h.
Constructor & Destructor Documentation
Champ_Fonc_Q1_base::Champ_Fonc_Q1_base ()
Definition at line 28 of file Champ_Fonc_Q1_base.cpp.
Champ_Fonc_Q1_base::~Champ_Fonc_Q1_base ()
Definition at line 28 of file Champ_Fonc_Q1_base.cpp.
Member Function Documentation
virtual int Champ_Fonc_Q1_base::duplique () const [pure virtual]
Implements Champ_Fonc_base.
Implemented in Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Q1_EF, Champ_Fonc_Q1_MED, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Q1_VDF, and Champ_Fonc_Q1_VEF.
int Champ_Fonc_Q1_base::fixer_nb_valeurs_nodales (int nb_noeuds) [virtual]
Fixe le nombre de degres de liberte par composante.
Returns:
int
Signification: le nombre de degres de liberte par composante
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 51 of file Champ_Fonc_Q1_base.cpp.
References Champ_Fonc_base::creer_tableau_distribue(), Champ_Fonc_base::domaine(), and Domaine::md_vector_sommets().
{
  assert(nb_noeuds == domaine().nb_som());
  const MD_Vector& md = domaine().md_vector_sommets();
  creer_tableau_distribue(md);
  return 1;
}
const Type_info * Champ_Fonc_Q1_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Q1_EF, Champ_Fonc_Q1_MED, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Q1_VDF, and Champ_Fonc_Q1_VEF.
Definition at line 28 of file Champ_Fonc_Q1_base.cpp.
const Type_info * Champ_Fonc_Q1_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Q1_EF, Champ_Fonc_Q1_MED, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Q1_VDF, and Champ_Fonc_Q1_VEF.
Definition at line 28 of file Champ_Fonc_Q1_base.cpp.
const Champ_base & Champ_Fonc_Q1_base::le_champ (void) const [protected, virtual]
Implements Champ_implementation_Q1.
Definition at line 46 of file Champ_Fonc_Q1_base.cpp.
{
  return *this;
}
Champ_base & Champ_Fonc_Q1_base::le_champ (void) [protected, virtual]
Implements Champ_implementation_Q1.
Definition at line 41 of file Champ_Fonc_Q1_base.cpp.
{
  return *this;
}
Sortie & Champ_Fonc_Q1_base::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Q1_EF, Champ_Fonc_Q1_MED, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Q1_VDF, and Champ_Fonc_Q1_VEF.
Definition at line 30 of file Champ_Fonc_Q1_base.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  os << que_suis_je() << " " << le_nom();
  return os;
}
Entree & Champ_Fonc_Q1_base::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Q1_EF, Champ_Fonc_Q1_MED, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Q1_VDF, and Champ_Fonc_Q1_VEF.
Definition at line 36 of file Champ_Fonc_Q1_base.cpp.
{
  return is;
}
DoubleTab & Champ_Fonc_Q1_base::remplir_coord_noeuds (DoubleTab & coord) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
DoubleTab&
Signification: renvoie toujours le parametre coord
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 80 of file Champ_Fonc_Q1_base.h.
{
  return Champ_implementation_Q1::remplir_coord_noeuds(positions);
}
int Champ_Fonc_Q1_base::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
int
Signification: renvoie toujours 0
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 85 of file Champ_Fonc_Q1_base.h.
{
  return Champ_implementation_Q1::remplir_coord_noeuds_et_polys(positions,polys);
}
Champ_Fonc_Q1_base & Champ_Fonc_Q1_base::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Q1_EF, Champ_Fonc_Q1_MED, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Q1_VDF, and Champ_Fonc_Q1_VEF.
Definition at line 28 of file Champ_Fonc_Q1_base.cpp.
const Champ_Fonc_Q1_base & Champ_Fonc_Q1_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Q1_EF, Champ_Fonc_Q1_MED, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Q1_VDF, and Champ_Fonc_Q1_VEF.
Definition at line 28 of file Champ_Fonc_Q1_base.cpp.
DoubleVect & Champ_Fonc_Q1_base::valeur_a_elem (const DoubleVect & position, DoubleVect & result, int poly) const [inline, virtual]
Reimplemented from Champ_implementation_sommet_base.
Definition at line 60 of file Champ_Fonc_Q1_base.h.
{
  return Champ_implementation_Q1::valeur_a_elem(position,result,poly);
}
double Champ_Fonc_Q1_base::valeur_a_elem_compo (const DoubleVect & position, int poly, int ncomp) const [inline, virtual]
Reimplemented from Champ_implementation_sommet_base.
Definition at line 65 of file Champ_Fonc_Q1_base.h.
{
  return Champ_implementation_Q1::valeur_a_elem_compo(position,poly,ncomp);
}
DoubleTab & Champ_Fonc_Q1_base::valeur_aux_elems (const DoubleTab & positions, const IntVect & polys, DoubleTab & result) const [inline, virtual]
Reimplemented from Champ_implementation_sommet_base.
Definition at line 70 of file Champ_Fonc_Q1_base.h.
{
  return Champ_implementation_Q1::valeur_aux_elems(positions,polys,result);
}
DoubleVect & Champ_Fonc_Q1_base::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & polys, DoubleVect & result, int ncomp) const [inline, virtual]
Reimplemented from Champ_implementation_sommet_base.
Definition at line 75 of file Champ_Fonc_Q1_base.h.
{
  return Champ_implementation_Q1::valeur_aux_elems_compo(positions,polys,result,ncomp);
}
DoubleTab & Champ_Fonc_Q1_base::valeur_aux_sommets (const Domaine & domain, DoubleTab & result) const [inline, virtual]
Reimplemented from Champ_implementation_base.
Definition at line 90 of file Champ_Fonc_Q1_base.h.
{
  return Champ_implementation_base::valeur_aux_sommets(domain,result);
}
DoubleVect & Champ_Fonc_Q1_base::valeur_aux_sommets_compo (const Domaine & domain, DoubleVect & result, int ncomp) const [inline, virtual]
Reimplemented from Champ_implementation_base.
Definition at line 95 of file Champ_Fonc_Q1_base.h.
{
  return Champ_implementation_base::valeur_aux_sommets_compo(domain,result,ncomp);
}
Member Data Documentation
const Type_info Champ_Fonc_Q1_base::info_obj [static]
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_Q1_CoviMAC, Champ_Fonc_Q1_EF, Champ_Fonc_Q1_MED, Champ_Fonc_Q1_PolyMAC, Champ_Fonc_Q1_VDF, and Champ_Fonc_Q1_VEF.
Definition at line 39 of file Champ_Fonc_Q1_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs_dis/Champ_Fonc_Q1_base.h
src/Kernel/Champs_dis/Champ_Fonc_Q1_base.cpp