TRUST: Traitement_particulier_NS_EC Class Reference
Traitement_particulier_NS_EC Class Reference
classe Traitement_particulier_EC
Cette classe permet de faire les traitements particuliers
pour les calculs de l'energie cinetique totale
#include <Traitement_particulier_NS_EC.h>
Public Member Functions
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
~Traitement_particulier_NS_EC () override
Traitement_particulier_NS_EC ()
Entree & lire (Entree &) override
void preparer_calcul_particulier (void) override
void post_traitement_particulier (void) override
void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double) override
void sauver_stat (void) const override
void reprendre_stat (void) override
int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
int comprend_champ (const Motcle &mot) const
Public Member Functions inherited from Traitement_particulier_NS_base
Traitement_particulier_NS_base ()
~Traitement_particulier_NS_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_eqn (const Equation_base &)
virtual void preparer_calcul_particulier (void)=0
virtual void post_traitement_particulier (void)=0
virtual Entree & lire (Entree &is)=0
virtual void sauver_stat (void) const =0
virtual void reprendre_stat (void)=0
virtual void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double)=0
void creer_champ (const Motcle &) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static const Type_info * info ()
static Traitement_particulier_NS_EC & self_cast (Objet_U &)
static const Traitement_particulier_NS_EC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_base
static const Type_info * info ()
static Traitement_particulier_NS_base & self_cast (Objet_U &)
static const Traitement_particulier_NS_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void ouvrir_fichier (SFichier &s) const
virtual void calculer_Ec (double &)
Meme methode de calcul en VDF et en VEF.
Si aucun champ de masse volumique n'a ete associe, on calcule
INTEGRALE de 1/2 * u^2 sur le domaine.
Si un champ de masse volumique a ete associe, il doit etre
de type "champ aux faces". On calcule INTEGRALE de 1/2 * rho * u^2.
rho est un champ P0 aux elements, u est P0 sur les volumes entrelaces
Valeur de retour:
La somme sur tous les processeurs de l'integrale de 1/2*rho*u*u.
Sortie & printOn (Sortie &x) const override
Impression de l'equation sur un flot de sortie.
Simple appel a Equation_base::printOn(Sortie&).
Entree & readOn (Entree &) override
Lit les specifications de l'equation de Navier Stokes a
partir d'un flot d'entree.
Simple appel a Navier_Stokes_std::readOn(Entree&)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
double periode
double tinit
double nb_bip
int repere_mobile_
Protected Attributes inherited from Traitement_particulier_NS_base
Ref_Navier_Stokes_std mon_equation
Champs_compris champs_compris_
Detailed Description
classe Traitement_particulier_EC
Cette classe permet de faire les traitements particuliers
pour les calculs de l'energie cinetique totale
Definition at line 35 of file Traitement_particulier_NS_EC.h.
Constructor & Destructor Documentation
~Traitement_particulier_NS_EC()
Traitement_particulier_NS_EC::~Traitement_particulier_NS_EC () inline override
Definition at line 86 of file Traitement_particulier_NS_EC.h.
{}
Traitement_particulier_NS_EC()
Traitement_particulier_NS_EC::Traitement_particulier_NS_EC () inline
Definition at line 83 of file Traitement_particulier_NS_EC.h.
                                                                 :repere_mobile_(0)
{
}
Member Function Documentation
a_pour_Champ_Fonc()
int Traitement_particulier_NS_EC::a_pour_Champ_Fonc (const Motcle & mot, Ref_Champ_base & ch_ref) const inline
Definition at line 74 of file Traitement_particulier_NS_EC.h.
{
  return 0 ;
}
calculer_Ec()
void Traitement_particulier_NS_EC::calculer_Ec (double & energie_cinetique) protected virtual
Meme methode de calcul en VDF et en VEF.
Si aucun champ de masse volumique n'a ete associe, on calcule
INTEGRALE de 1/2 * u^2 sur le domaine.
Si un champ de masse volumique a ete associe, il doit etre
de type "champ aux faces". On calcule INTEGRALE de 1/2 * rho * u^2.
rho est un champ P0 aux elements, u est P0 sur les volumes entrelaces
Valeur de retour:
La somme sur tous les processeurs de l'integrale de 1/2*rho*u*u.
Definition at line 270 of file Traitement_particulier_NS_EC.cpp.
{
  const Zone_dis_base& zdisbase        = mon_equation->inconnue().zone_dis_base();
  const Zone_VF&    zone_VF            = ref_cast(Zone_VF, zdisbase);
  const DoubleVect& volumes_entrelaces = zone_VF.volumes_entrelaces();
  const DoubleTab&  xv                 = zone_VF.xv();
  const DoubleTab&  vitesse            = mon_equation->inconnue().valeurs();
  REF(ArrOfDouble) translation(xv);
  REF(ArrOfDouble) rotation(xv);
  REF(DoubleTab) rho(xv);
  DoubleVect rotation_nulle(dimension);
  rotation_nulle=0;
  if (repere_mobile_)
    {
      int ok=0;
// Verification de l'existence d'un terme source Acceleration dans Navier Stokes
      const Sources& les_sources=mon_equation->sources();
      CONST_LIST_CURSEUR(Source) curseur(les_sources);
      while(curseur)
        {
          if (sub_type(Terme_Source_Acceleration,curseur->valeur()))
            {
              const Terme_Source_Acceleration& terme_source_acceleration=ref_cast(Terme_Source_Acceleration,curseur->valeur());
// Verification que les vitesses de translation du repere
// mobiles sont bien definies et association des tableaux translation et
// eventuellement rotation
              if (terme_source_acceleration.champ_vitesse().non_nul())
                {
                  translation=terme_source_acceleration.champ_vitesse().valeurs();
                  if (terme_source_acceleration.omega().non_nul())
                    rotation=terme_source_acceleration.omega().valeurs();
                  else
                    rotation=rotation_nulle;
                  ok=1;
                }
            }
          ++curseur;
        }
      if (!ok)
        {
          Cerr << "Vous ne pouvez calculer l'energie cinetique dans un repere fixe" << finl;
          Cerr << "que si le repere de calcul est mobile, c'est a dire que vous avez" << finl;
          Cerr << "defini un terme source d'acceleration dans l'equation Navier Stokes." << finl;
          Cerr << "Ou bien il manque dans ce terme source la definition de la vitesse" << finl;
          Cerr << "du repere mobile dans le repere fixe. Modifier votre jeu de donnees." << finl;
          exit();
        }
    }
  double ec = 0.;
  if (has_champ_masse_volumique())
    {
      const Champ_base& champ_rho = get_champ_masse_volumique();
      rho = champ_rho.valeurs();
      if (rho->dimension(0) != zone_VF.nb_faces() || rho->line_size() != 1)
        {
          Cerr << "Erreur dans Traitement_particulier_NS_EC::calculer_Ec" << finl;
          Cerr << "le champ de masse volumique n'est pas un champ scalaire aux faces" << finl;
          Process::exit();
        }
    }
  else
    {
      rho = mon_equation->milieu().masse_volumique().valeurs();
    }
  const int nb_front = zone_VF.nb_front_Cl();
  const ArrOfInt& faces_doubles = zone_VF.faces_doubles();
// Faces de bord
  for (int i = 0; i < nb_front; i++)
    {
      const Frontiere& fr = zone_VF.front_VF(i).frontiere();
      const int debut    = fr.num_premiere_face();
      const int nb_faces = fr.nb_faces();
      ec += trait_part_calculer_ec_faces(debut, nb_faces, 1,
                                         vitesse, volumes_entrelaces, xv, rho, translation, rotation, repere_mobile_, faces_doubles);
    }
// Faces a l'interieur du domaine (y compris les faces de joint)
  {
    const int debut    = zone_VF.premiere_face_int();
    const int nb_faces = zone_VF.nb_faces_internes();
    ec += trait_part_calculer_ec_faces(debut, nb_faces, 0,
                                       vitesse, volumes_entrelaces, xv, rho, translation, rotation, repere_mobile_, faces_doubles);
  }
  ec = Process::mp_sum(ec);
  energie_cinetique = ec;
}
References Cerr, Terme_Source_Acceleration::champ_vitesse(), CONST_LIST_CURSEUR, Objet_U::dimension, Process::exit(), Zone_VF::faces_doubles(), finl, Zone_VF::front_VF(), Frontiere_dis_base::frontiere(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Navier_Stokes_std::inconnue(), Milieu_base::masse_volumique(), Navier_Stokes_std::milieu(), Traitement_particulier_NS_base::mon_equation, Process::mp_sum(), Frontiere::nb_faces(), Zone_VF::nb_faces(), Zone_VF::nb_faces_internes(), Zone_dis_base::nb_front_Cl(), O_U_Ptr::non_nul(), Frontiere::num_premiere_face(), Terme_Source_Acceleration::omega(), Zone_VF::premiere_face_int(), REF, ref_cast, repere_mobile_, Equation_base::sources(), sub_type, trait_part_calculer_ec_faces(), Champ::valeurs(), Champ_Don::valeurs(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), Zone_VF::volumes_entrelaces(), Zone_VF::xv(), and Champ_Inc::zone_dis_base().
Referenced by post_traitement_particulier(), and preparer_calcul_particulier().
comprend_champ()
int Traitement_particulier_NS_EC::comprend_champ (const Motcle & mot) const inline
Definition at line 79 of file Traitement_particulier_NS_EC.h.
{
  return 0 ;
}
en_cours_de_resolution()
void Traitement_particulier_NS_EC::en_cours_de_resolution (int , DoubleTab & , DoubleTab & , double) inline override virtual
Implements Traitement_particulier_NS_base.
Definition at line 60 of file Traitement_particulier_NS_EC.h.
{
}
get_info()
const Type_info * Traitement_particulier_NS_EC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Reimplemented in Traitement_particulier_NS_EC_VDF, and Traitement_particulier_NS_EC_VEF.
Definition at line 27 of file Traitement_particulier_NS_EC.cpp.
info()
const Type_info * Traitement_particulier_NS_EC::info () static
Definition at line 27 of file Traitement_particulier_NS_EC.cpp.
lire()
Entree & Traitement_particulier_NS_EC::lire (Entree & is) override virtual
Implements Traitement_particulier_NS_base.
Definition at line 69 of file Traitement_particulier_NS_EC.cpp.
{
  Motcle accouverte = "{" , accfermee = "}" ;
  Motcle valec="Ec";
  Motcle motbidon, motlu;
  nb_bip=0;
  periode = mon_equation->probleme().schema_temps().pas_temps_min();
  is >> motbidon ;
  if (motbidon == accouverte)
    {
      Motcles les_mots(2);
      les_mots[0] = "Ec";
      les_mots[1] = "Ec_dans_repere_fixe";
      {
        is >> motlu;
        while(motlu != accfermee)
          {
            int rang=les_mots.search(motlu);
            switch(rang)
              {
              case 0 :
              case 1 :
                {
                  if (rang==1)
                    repere_mobile_=1;
                  is >> motlu;
                  if (motlu!="periode")
                    {
                      Cerr<<"On attendait le mot cle periode apres " << les_mots[rang] << "."<<finl;
                      exit();
                    }
                  is >> periode;
                  break;
                }
              default :
                {
                  Cerr << "Erreur dans la lecture de Traitement_particulier_NS_EC";
                  Cerr << "Les mots cles possibles sont "<< les_mots <<" { et }" << finl;
                  Cerr << "Vous avez lu :" << motlu << finl;
                  exit();
                  break;
                }
              }
            is >> motlu;
          }
        is >> motlu;
        if (motlu != accfermee)
          {
            Cerr << "Erreur dans la lecture de Traitement_particulier_NS_EC";
            Cerr << "On attendait une }" << finl;
            exit();
          }
      }
    }
  else
    {
      Cerr << "Erreur dans la lecture de Traitement_particulier_NS_EC";
      Cerr << "On attendait une {" << finl;
      exit();
    }
  return is;
}
References Cerr, Process::exit(), finl, Traitement_particulier_NS_base::mon_equation, nb_bip, Schema_Temps_base::pas_temps_min(), periode, Equation_base::probleme(), repere_mobile_, Probleme_base::schema_temps(), and Motcles::search().
ouvrir_fichier()
void Traitement_particulier_NS_EC::ouvrir_fichier (SFichier & s) const protected
Definition at line 132 of file Traitement_particulier_NS_EC.cpp.
{
// Ouverture du fichier Nom_du_cas_EC.son
  Nom nom_fich(nom_du_cas());
  nom_fich += "_EC";
  if (repere_mobile_)
    nom_fich+="_dans_repere_fixe";
  nom_fich+=".son";
  const Probleme_base& pb=mon_equation->probleme();
  struct stat f;
  if (stat(nom_fich,&f) || (nb_bip==0 && !pb.reprise_effectuee()))
    s.ouvrir(nom_fich);
  else
    s.ouvrir(nom_fich,ios::app);
  s.setf(ios::scientific);
  s.precision(8);
}
References Traitement_particulier_NS_base::mon_equation, nb_bip, Objet_U::nom_du_cas(), Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), Equation_base::probleme(), repere_mobile_, Probleme_base::reprise_effectuee(), and Sortie_Fichier_base::setf().
Referenced by post_traitement_particulier(), and preparer_calcul_particulier().
post_traitement_particulier()
void Traitement_particulier_NS_EC::post_traitement_particulier (void) override virtual
Implements Traitement_particulier_NS_base.
Definition at line 166 of file Traitement_particulier_NS_EC.cpp.
{
  double temps = mon_equation->inconnue().temps();
  double nb = floor((temps - tinit) / periode);
  if (nb > nb_bip + 0.5)
    {
      nb_bip=nb;
      double Ec;
      calculer_Ec(Ec);
      if(je_suis_maitre())
        {
          SFichier le_fichier;
          ouvrir_fichier(le_fichier);
          le_fichier<<temps<<" "<<Ec<<finl;
        }
    }
}
References calculer_Ec(), finl, Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, nb_bip, ouvrir_fichier(), periode, Champ_Inc::temps(), and tinit.
preparer_calcul_particulier()
void Traitement_particulier_NS_EC::preparer_calcul_particulier (void) override virtual
Implements Traitement_particulier_NS_base.
Definition at line 151 of file Traitement_particulier_NS_EC.cpp.
{
  tinit = mon_equation->inconnue().temps();
  nb_bip=0;
  double Ec;
  calculer_Ec(Ec);
  if(je_suis_maitre())
    {
      SFichier le_fichier;
      ouvrir_fichier(le_fichier);
// Ecriture premiere ligne
      le_fichier<<"# Temps        Energie_cinetique_totale"<<finl;
      le_fichier<<tinit<<" "<<Ec<<finl;
    }
}
References calculer_Ec(), finl, Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, nb_bip, ouvrir_fichier(), Champ_Inc::temps(), and tinit.
printOn()
Sortie & Traitement_particulier_NS_EC::printOn (Sortie & is) const override protected virtual
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Reimplemented in Traitement_particulier_NS_EC_VDF, and Traitement_particulier_NS_EC_VEF.
Definition at line 44 of file Traitement_particulier_NS_EC.cpp.
{
  return is;
}
readOn()
Entree & Traitement_particulier_NS_EC::readOn (Entree & is) override protected virtual
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Reimplemented in Traitement_particulier_NS_EC_VDF, and Traitement_particulier_NS_EC_VEF.
Definition at line 64 of file Traitement_particulier_NS_EC.cpp.
{
  return is;
}
reprendre_stat()
void Traitement_particulier_NS_EC::reprendre_stat (void) inline override virtual
Implements Traitement_particulier_NS_base.
Definition at line 69 of file Traitement_particulier_NS_EC.h.
{
  ;
}
sauver_stat()
void Traitement_particulier_NS_EC::sauver_stat (void) const inline override virtual
Implements Traitement_particulier_NS_base.
Definition at line 64 of file Traitement_particulier_NS_EC.h.
{
  ;
}
self_cast() [1/2]
const Traitement_particulier_NS_EC & Traitement_particulier_NS_EC::self_cast (const Objet_U & r) static
Definition at line 27 of file Traitement_particulier_NS_EC.cpp.
self_cast() [2/2]
Traitement_particulier_NS_EC & Traitement_particulier_NS_EC::self_cast (Objet_U & r) static
Definition at line 27 of file Traitement_particulier_NS_EC.cpp.
Member Data Documentation
info_obj
const Type_info Traitement_particulier_NS_EC::info_obj static
Definition at line 37 of file Traitement_particulier_NS_EC.h.
nb_bip
double Traitement_particulier_NS_EC::nb_bip protected
Definition at line 54 of file Traitement_particulier_NS_EC.h.
Referenced by lire(), ouvrir_fichier(), post_traitement_particulier(), and preparer_calcul_particulier().
periode
double Traitement_particulier_NS_EC::periode protected
Definition at line 54 of file Traitement_particulier_NS_EC.h.
Referenced by lire(), and post_traitement_particulier().
repere_mobile_
int Traitement_particulier_NS_EC::repere_mobile_ protected
Definition at line 55 of file Traitement_particulier_NS_EC.h.
Referenced by calculer_Ec(), lire(), and ouvrir_fichier().
tinit
double Traitement_particulier_NS_EC::tinit protected
Definition at line 54 of file Traitement_particulier_NS_EC.h.
Referenced by post_traitement_particulier(), and preparer_calcul_particulier().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Traitement_particulier/Traitement_particulier_NS_EC.h
src/ThHyd/Incompressible/Traitement_particulier/Traitement_particulier_NS_EC.cpp