TRUST: Op_Grad_PolyMAC_P0_Face Class Reference
Op_Grad_PolyMAC_P0_Face Class Reference
class Op_Grad_PolyMAC_P0_Face
Cette classe represente l'operateur de gradient
La discretisation est PolyMAC_P0
On calcule le gradient d'un champ_Elem_PolyMAC_P0 (la pression)
#include <Op_Grad_PolyMAC_P0_Face.h>
Public Member Functions
Op_Grad_PolyMAC_P0_Face ()
~Op_Grad_PolyMAC_P0_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void update_grad (int full_stencil=0) const
void check_multiphase_compatibility () const override
Public Member Functions inherited from Operateur_Grad_base
Operateur_Grad_base ()
~Operateur_Grad_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void dimensionner (Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & ajouter (const DoubleTab &inco, DoubleTab &secmem) const override
virtual DoubleVect & multvect (const DoubleTab &, DoubleTab &) const
Calcul sans les conditions aux limites ?
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Grad_PolyMAC_P0_Face & self_cast (Objet_U &)
static const Op_Grad_PolyMAC_P0_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Grad_base
static const Type_info * info ()
static Operateur_Grad_base & self_cast (Objet_U &)
static const Operateur_Grad_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
IntTab fgrad_d
IntTab fgrad_e
DoubleTab fgrad_c
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Grad_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Private Attributes
double last_gradp_
Ref_Zone_PolyMAC_P0 ref_zone
Ref_Zone_Cl_PolyMAC ref_zcl
Additional Inherited Members
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Op_Grad_PolyMAC_P0_Face
Cette classe represente l'operateur de gradient
La discretisation est PolyMAC_P0
On calcule le gradient d'un champ_Elem_PolyMAC_P0 (la pression)
Definition at line 38 of file Op_Grad_PolyMAC_P0_Face.h.
Constructor & Destructor Documentation
Op_Grad_PolyMAC_P0_Face()
Op_Grad_PolyMAC_P0_Face::Op_Grad_PolyMAC_P0_Face ()
Definition at line 35 of file Op_Grad_PolyMAC_P0_Face.cpp.
~Op_Grad_PolyMAC_P0_Face()
Op_Grad_PolyMAC_P0_Face::~Op_Grad_PolyMAC_P0_Face ()
Definition at line 35 of file Op_Grad_PolyMAC_P0_Face.cpp.
Member Function Documentation
ajouter_blocs()
void Op_Grad_PolyMAC_P0_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
Definition at line 164 of file Op_Grad_PolyMAC_P0_Face.cpp.
{
  const Zone_PolyMAC_P0& zone = ref_zone.valeur();
  const Champ_Face_PolyMAC_P0& ch = ref_cast(Champ_Face_PolyMAC_P0, equation().inconnue().valeur());
  const Conds_lim& cls = ref_zcl->les_conditions_limites();
  const IntTab& f_e = zone.face_voisins(), &fcl = ch.fcl();
  const DoubleTab& nf = zone.face_normales(), &xp = zone.xp(), &xv = zone.xv(), &vfd = zone.volumes_entrelaces_dir(),
                   &press = semi_impl.count("pression") ? semi_impl.at("pression") : (le_champ_inco.non_nul() ? le_champ_inco->valeurs() : ref_cast(Navier_Stokes_std, equation()).pression().valeurs()),
                    *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL;
  const DoubleVect& fs = zone.face_surfaces(), &ve = zone.volumes(), &pe = zone.porosite_elem(), &pf = zone.porosite_face();
  int i, j, e, f, fb, ne_tot = zone.nb_elem_tot(), nf_tot = zone.nb_faces_tot(), d, D = dimension, n, N = secmem.line_size(), m, M = press.line_size();
  update_grad();
  const std::string& nom_inc = ch.le_nom().getString();
  Matrice_Morse *mat_p = !semi_impl.count("pression") && matrices.count("pression") ? matrices.at("pression") : NULL,
                 *mat_v = !semi_impl.count(nom_inc) && matrices.count(nom_inc) ? matrices.at(nom_inc) : NULL;
  DoubleTrav gb(nf_tot, M), gf(N), alpha(N); //-grad p aux bords , alpha |f| (grad p)_f
  std::map<int, std::map<int, double>> dgp_gb, dgb_v; //dependances vitesses -(dgb_v)-> -grad p aux bords -(dgp_gb)-> grad p ailleurs
  for (f = 0; f < zone.nb_faces_tot(); f++)
    if (fcl(f, 0) > 1)  //Dirichlet/Symetrie : pression du voisin + correction en regardant l'eq de NS dans celui-ci
      for (e = f_e(f, 0), n = 0, m = 0; n < N; n++, m += (M > 1))
        {
          double fac = 1. / (fs(f) * ve(e));
          std::map<int, double> *dv = mat_v ? &dgb_v[M * f + m] : NULL; //dv[indice dans mat_NS] = coeff
          for (d = 0, i = nf_tot + D * e; d < D; d++, i++)
            if (std::fabs(nf(f, d)) > 1e-6 * fs(f)) //boucle sur la direction : i est l'indice dans mat_v
              {
                gb(f, m) += fac * nf(f, d) * secmem(i, n); //partie constante -> directement dans pfb
                if (dv)
                  for (j = mat_v->get_tab1()(N * i + n) - 1; j < mat_v->get_tab1()(N * i + n + 1) - 1; j++) //partie lineaire -> dans dgb_v
                    if (mat_v->get_coeff()(j)) (*dv)[mat_v->get_tab2()(j) - 1] -= fac * nf(f, d) * mat_v->get_coeff()(j);
              }
        }
  for (f = 0; f < zone.nb_faces(); f++)
    if (fgrad_d(f + 1) == fgrad_d(f)) abort();
  /* aux faces */
  std::vector<std::map<int, double>> dgf_pe(N), dgf_gb(N); //dependance de [grad p]_f en les pressions aux elements, en les grad p aux faces de bord
  for (f = 0; f < zone.nb_faces_tot(); f++)
    {
      for (alpha = 0, i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
        for (n = 0; n < N; n++) alpha(n) += vfd(f, i) * (alp ? (*alp)(e, n) : 1);
      /* |f| grad p */
      for (gf = 0, i = fgrad_d(f); i < fgrad_d(f + 1); i++)
        for (e = fgrad_e(i), fb = e - ne_tot, n = 0, m = 0; n < N; n++, m += (M > 1))
          {
            double fac = fgrad_c(i, m);
            gf(n) += fac * (e < ne_tot ? press(e, m) : fcl(fb, 0) == 1 ? ref_cast(Neumann, cls[fcl(fb, 1)].valeur()).flux_impose(fcl(fb, 2), m) : gb(e - ne_tot, m));
            if (mat_p && e < ne_tot) dgf_pe[n][e] += fac;
            if (mat_v && fb >= 0 && dgb_v.count(M * fb + m)) dgf_gb[n][M * fb + m] += fac;
          }
      /* face -> vf(f) * phi grad p */
      if (fcl(f, 0) < 2 && f < zone.nb_faces())
        for (n = 0, m = 0; n < N; n++, m += (M > 1))
          {
            double fac = alpha(n) * pf(f);
            secmem(f, n) -= fac * gf(n);
            for (auto &&i_c : dgf_pe[n]) (*mat_p)(N * f + n, M * i_c.first + m) += fac * i_c.second;
            for (auto &&i_c : dgf_gb[n]) dgp_gb[N * f + n][M * i_c.first + m] += fac * i_c.second;
          }
      /* elems amont/aval -> ve(e) * phi grad p */
      for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
        if (e < zone.nb_elem())
          for (d = 0; d < D; d++)
            if (fs(f) * std::fabs(xv(f, d) - xp(e, d)) > 1e-6 * ve(e))
              for (n = 0, m = 0; n < N; n++, m += (M > 1))
                {
                  double fac = (i ? -1 : 1) * fs(f) * pe(e) * (xv(f, d) - xp(e, d)) * (alp ? (*alp)(e, n) : 1);
                  secmem(nf_tot + D * e + d, n) -= fac * gf(n);
                  for (auto &i_c : dgf_pe[n]) (*mat_p)(N * (nf_tot + D * e + d) + n, M * i_c.first + m) += fac * i_c.second;
                  for (auto &i_c : dgf_gb[n]) dgp_gb[N * (nf_tot + D * e + d) + n][M * i_c.first + m] += fac * i_c.second;
                }
      for (n = 0; n < N; n++) dgf_pe[n].clear(), dgf_gb[n].clear();
    }
  /* correction de mat_NS : en une seule ligne! */
  if (mat_v)
    for (auto &i_jc : dgp_gb)
      for (auto &j_c : i_jc.second)
        if (dgb_v.count(j_c.first))
          for (auto &k_d : dgb_v.at(j_c.first))
            (*mat_v)(i_jc.first, k_d.first) += j_c.second * k_d.second;
}
References Process::abort(), Objet_U::dimension, MorEqn::equation(), Zone_Poly_base::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Champ_Face_PolyMAC::fcl(), fgrad_c, fgrad_d, fgrad_e, Nom::getString(), Operateur_base::le_champ_inco, Field_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), O_U_Ptr::non_nul(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Equation_base::probleme(), ref_cast, ref_zcl, ref_zone, sub_type, update_grad(), Ref_Zone_PolyMAC_P0::valeur(), valeur(), Champ_Inc::valeurs(), Zone_VF::volumes(), Zone_Poly_base::volumes_entrelaces_dir(), Zone_VF::xp(), and Zone_VF::xv().
associer()
void Op_Grad_PolyMAC_P0_Face::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch) override virtual
Implements Operateur_base.
Definition at line 57 of file Op_Grad_PolyMAC_P0_Face.cpp.
{
  ref_zone = ref_cast(Zone_PolyMAC_P0, zone_dis.valeur());
  ref_zcl = ref_cast(Zone_Cl_PolyMAC, zone_cl_dis.valeur());
}
References ref_cast, ref_zcl, ref_zone, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
check_multiphase_compatibility()
void Op_Grad_PolyMAC_P0_Face::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
Definition at line 61 of file Op_Grad_PolyMAC_P0_Face.h.
{ }; //ok
completer()
void Op_Grad_PolyMAC_P0_Face::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Definition at line 63 of file Op_Grad_PolyMAC_P0_Face.cpp.
{
  Operateur_Grad_base::completer();
  const Zone_PolyMAC_P0& zone = ref_zone.valeur();
  /* besoin d'un joint de 1 */
  if (zone.zone().nb_joints() && zone.zone().joint(0).epaisseur() < 1)
    Cerr << "Op_Grad_PolyMAC_P0_Face : largeur de joint insuffisante (minimum 1)!" << finl, Process::exit();
  Champ_Face_PolyMAC_P0& gradp = ref_cast(Champ_Face_PolyMAC_P0, ref_cast(Navier_Stokes_std, equation()).grad_P().valeur());
  gradp.init_auxiliary_variables();
  last_gradp_ = -DBL_MAX;
}
References Cerr, Operateur_base::completer(), Joint::epaisseur(), MorEqn::equation(), Process::exit(), finl, Champ_Face_PolyMAC_P0::init_auxiliary_variables(), Zone::joint(), last_gradp_, Zone::nb_joints(), ref_cast, ref_zone, Ref_Zone_PolyMAC_P0::valeur(), valeur(), and Zone_dis_base::zone().
cree_instance()
Objet_U * Op_Grad_PolyMAC_P0_Face::cree_instance () static
Definition at line 35 of file Op_Grad_PolyMAC_P0_Face.cpp.
dimensionner_blocs()
void Op_Grad_PolyMAC_P0_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
Definition at line 90 of file Op_Grad_PolyMAC_P0_Face.cpp.
{
  const Zone_PolyMAC_P0& zone = ref_zone.valeur();
  const Champ_Face_PolyMAC_P0& ch = ref_cast(Champ_Face_PolyMAC_P0, equation().inconnue().valeur());
  const IntTab& f_e = zone.face_voisins(), &e_f = zone.elem_faces(), &fcl = ch.fcl();
  const DoubleTab& nf = zone.face_normales(), &xp = zone.xp(), &xv = zone.xv();
  const DoubleVect& fs = zone.face_surfaces(), &ve = zone.volumes();
  int i, j, e, eb, f, ne_tot = zone.nb_elem_tot(), nf_tot = zone.nb_faces_tot(), d, D = dimension, n, N = ch.valeurs().line_size(),
                      m, M = (le_champ_inco.non_nul() ? le_champ_inco->valeurs() : ref_cast(Navier_Stokes_std, equation()).pression().valeurs()).line_size();
  update_grad(sub_type(Pb_Multiphase, equation().probleme())); //provoque le calcul du gradient
  IntTrav sten_p(0, 2), sten_v(0, 2); //stencils (NS, pression), (NS, vitesse)
  sten_p.set_smart_resize(1), sten_v.set_smart_resize(1);
  const std::string& nom_inc = ch.le_nom().getString();
  Matrice_Morse *mat_p = matrices["pression"], *mat_v = !semi_impl.count(nom_inc) && matrices.count(nom_inc) ? matrices.at(nom_inc) : NULL, mat2_p, mat2_v;
  std::map<int, std::set<int>> dpb_v, dgp_pb; //dependances vitesses -(dpb_v)-> pressions au bord -(dgp_pb)-> gradient
  if (mat_v)
    for (f = 0; f < zone.nb_faces_tot(); f++)
      if (fcl(f, 0) > 1)
        for (e = f_e(f, 0), n = 0, m = 0; n < N; n++, m += (M > 1))
          for (d = 0, i = nf_tot + D * e; d < D; d++, i++)
            if (std::fabs(nf(f, d)) > 1e-6 * fs(f))
              for (dpb_v[M * f + m].insert(N * i + n), j = mat_v->get_tab1()(N * i + n) - 1; j < mat_v->get_tab1()(N * i + n + 1) - 1; j++)
                dpb_v[M * f + m].insert(mat_v->get_tab2()(j) - 1);
  /* aux faces : gradient aux faces + remplissage de dgp_pb */
  std::vector<std::set<int>> dfgpf(N); //dfgpf[n][idx] = coeff : dependance en les pfb variables (presents dans dpf_ve)
  for (f = 0; f < zone.nb_faces_tot(); f++)
    {
      /* |f| grad p */
      for (i = fgrad_d(f); i < fgrad_d(f + 1); i++) //face interne -> flux multipoints
        for (e = fgrad_e(i), n = 0, m = 0; n < N; n++, m += (M > 1))
          {
            if (f < zone.nb_faces() && e < ne_tot) sten_p.append_line(N * f + n, M * e + m);
            if (e >= ne_tot && dpb_v.count(M * (e - ne_tot) + m)) dfgpf[n].insert(M * (e - ne_tot) + m);
          }
      /* face -> vf(f) * phi grad p */
      if (fcl(f, 0) < 2 && f < zone.nb_faces())
        for (n = 0, m = 0; n < N; n++, m += (M > 1))
          for (auto &c : dfgpf[n]) dgp_pb[N * f + n].insert(M * c + m);
      /* elems amont/aval -> ve(e) * phi grad p */
      for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
        if (e < zone.nb_elem())
          for (d = 0; d < D; d++)
            if (fs(f) * std::fabs(xv(f, d) - xp(e, d)) > 1e-6 * ve(e))
              for (n = 0, m = 0; n < N; n++, m += (M > 1))
                for (auto &c : dfgpf[n])
                  dgp_pb[N * (nf_tot + D * e + d) + n].insert(M * c + m);
      for (n = 0; n < N; n++) dfgpf[n].clear();
    }
  /* aux elements : gradient aux elems */
  for (e = 0; e < zone.nb_elem(); e++)
    for (i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++)
      for (j = fgrad_d(f); j < fgrad_d(f + 1); j++)
        if ((eb = fgrad_e(j)) < ne_tot)
          for (d = 0; d < D; d++)
            if (std::fabs(fs(f) * (xv(f, d) - xp(e, d))) > 1e-6 * ve(e))
              for (n = 0, m = 0; n < N; n++, m += (M > 1))
                sten_p.append_line(N * (nf_tot + D * e + d) + n, M * eb + m);
  /* sten_v en une ligne */
  for (auto &i_sc : dgp_pb)
    for (auto &c : i_sc.second)
      for (auto &k : dpb_v.at(c)) sten_v.append_line(i_sc.first, k);
  /* allocation / remplissage */
  tableau_trier_retirer_doublons(sten_p), tableau_trier_retirer_doublons(sten_v);
  if (mat_p) Matrix_tools::allocate_morse_matrix(N * (nf_tot + ne_tot * D), M * ne_tot               , sten_p, mat2_p), mat_p->nb_colonnes() ? *mat_p += mat2_p : *mat_p = mat2_p;
  if (mat_v) Matrix_tools::allocate_morse_matrix(N * (nf_tot + ne_tot * D), N * (nf_tot + ne_tot * D), sten_v, mat2_v), mat_v->nb_colonnes() ? *mat_v += mat2_v : *mat_v = mat2_v;
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Zone_Poly_base::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Champ_Face_PolyMAC::fcl(), fgrad_d, fgrad_e, Nom::getString(), Operateur_base::le_champ_inco, Field_base::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Matrice_Morse::nb_colonnes(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), O_U_Ptr::non_nul(), ref_cast, ref_zone, TRUSTArray< _TYPE_ >::set_smart_resize(), sub_type, tableau_trier_retirer_doublons(), update_grad(), Ref_Zone_PolyMAC_P0::valeur(), valeur(), Champ_Inc::valeurs(), Champ_Inc_base::valeurs(), Zone_VF::volumes(), Zone_VF::xp(), and Zone_VF::xv().
duplique()
int Op_Grad_PolyMAC_P0_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 35 of file Op_Grad_PolyMAC_P0_Face.cpp.
get_info()
const Type_info * Op_Grad_PolyMAC_P0_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 35 of file Op_Grad_PolyMAC_P0_Face.cpp.
has_interface_blocs()
int Op_Grad_PolyMAC_P0_Face::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
Definition at line 49 of file Op_Grad_PolyMAC_P0_Face.h.
{ return 1; };
impr()
int Op_Grad_PolyMAC_P0_Face::impr (Sortie & os) const override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 250 of file Op_Grad_PolyMAC_P0_Face.cpp.
{
  return 0;
}
info()
const Type_info * Op_Grad_PolyMAC_P0_Face::info () static
Definition at line 35 of file Op_Grad_PolyMAC_P0_Face.cpp.
printOn()
Sortie & Op_Grad_PolyMAC_P0_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 41 of file Op_Grad_PolyMAC_P0_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Grad_PolyMAC_P0_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 49 of file Op_Grad_PolyMAC_P0_Face.cpp.
{
  return s ;
}
self_cast() [1/2]
const Op_Grad_PolyMAC_P0_Face & Op_Grad_PolyMAC_P0_Face::self_cast (const Objet_U & r) static
Definition at line 35 of file Op_Grad_PolyMAC_P0_Face.cpp.
self_cast() [2/2]
Op_Grad_PolyMAC_P0_Face & Op_Grad_PolyMAC_P0_Face::self_cast (Objet_U & r) static
Definition at line 35 of file Op_Grad_PolyMAC_P0_Face.cpp.
taille_memoire()
unsigned Op_Grad_PolyMAC_P0_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 35 of file Op_Grad_PolyMAC_P0_Face.cpp.
update_grad()
void Op_Grad_PolyMAC_P0_Face::update_grad (int full_stencil = 0) const
Definition at line 75 of file Op_Grad_PolyMAC_P0_Face.cpp.
{
  const Zone_PolyMAC_P0& zone = ref_zone.valeur();
  const Champ_Face_PolyMAC_P0& ch = ref_cast(Champ_Face_PolyMAC_P0, equation().inconnue().valeur());
  const DoubleTab& press = le_champ_inco.non_nul() ? le_champ_inco->valeurs() : ref_cast(Navier_Stokes_std, equation()).pression().valeurs(),
                   *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL;
  const int M = press.line_size();
  double t_past = equation().inconnue().valeur().recuperer_temps_passe();
  if (!full_stencil && (alp ? (last_gradp_ >= t_past) : (last_gradp_ != -DBL_MAX))) return; //deja calcule a ce temps -> rien a faire
  /* gradient */
  zone.fgrad(M, 1, ref_zcl->les_conditions_limites(), ch.fcl(), NULL, NULL, 1, full_stencil, fgrad_d, fgrad_e, fgrad_c);
  last_gradp_ = t_past;
}
References MorEqn::equation(), Champ_Face_PolyMAC::fcl(), Zone_PolyMAC_P0::fgrad(), fgrad_c, fgrad_d, fgrad_e, Equation_base::inconnue(), last_gradp_, Operateur_base::le_champ_inco, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), O_U_Ptr::non_nul(), Champ_Inc_base::recuperer_temps_passe(), ref_cast, ref_zcl, ref_zone, sub_type, Deriv_Champ_Inc_base::valeur(), Ref_Zone_PolyMAC_P0::valeur(), valeur(), and Champ_Inc::valeurs().
Referenced by ajouter_blocs(), Assembleur_P_PolyMAC_P0::assembler_mat(), and dimensionner_blocs().
Member Data Documentation
fgrad_c
DoubleTab Op_Grad_PolyMAC_P0_Face::fgrad_c mutable
Definition at line 59 of file Op_Grad_PolyMAC_P0_Face.h.
Referenced by ajouter_blocs(), Assembleur_P_PolyMAC_P0::assembler_mat(), and update_grad().
fgrad_d
IntTab Op_Grad_PolyMAC_P0_Face::fgrad_d mutable
Definition at line 58 of file Op_Grad_PolyMAC_P0_Face.h.
Referenced by ajouter_blocs(), Assembleur_P_PolyMAC_P0::assembler_mat(), dimensionner_blocs(), and update_grad().
fgrad_e
IntTab Op_Grad_PolyMAC_P0_Face::fgrad_e
Definition at line 58 of file Op_Grad_PolyMAC_P0_Face.h.
Referenced by ajouter_blocs(), Assembleur_P_PolyMAC_P0::assembler_mat(), dimensionner_blocs(), and update_grad().
info_obj
const Type_info Op_Grad_PolyMAC_P0_Face::info_obj static
Definition at line 41 of file Op_Grad_PolyMAC_P0_Face.h.
last_gradp_
double Op_Grad_PolyMAC_P0_Face::last_gradp_ mutable private
Definition at line 65 of file Op_Grad_PolyMAC_P0_Face.h.
Referenced by completer(), and update_grad().
ref_zcl
Ref_Zone_Cl_PolyMAC Op_Grad_PolyMAC_P0_Face::ref_zcl private
Definition at line 67 of file Op_Grad_PolyMAC_P0_Face.h.
Referenced by ajouter_blocs(), associer(), and update_grad().
ref_zone
Ref_Zone_PolyMAC_P0 Op_Grad_PolyMAC_P0_Face::ref_zone private
Definition at line 66 of file Op_Grad_PolyMAC_P0_Face.h.
Referenced by ajouter_blocs(), associer(), completer(), dimensionner_blocs(), and update_grad().
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Op_Grad_PolyMAC_P0_Face.h
src/PolyMAC/Operateurs/Op_Grad_PolyMAC_P0_Face.cpp