TRUST: EDO_Pression_th_VEF Class Reference
EDO_Pression_th_VEF Class Reference
classe EDO_Pression_th_VEF
Cette classe represente l'EDO sur la pression associee au schema de
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VEF.
#include <EDO_Pression_th_VEF.h>
Public Member Functions
~EDO_Pression_th_VEF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
EDO_Pression_th_VEF ()
const Fluide_Quasi_Compressible & le_fluide () const
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Associe les zones a l'EDO.
void completer () override
Complete l'EDO : calcule rho sur les faces.
void calculer_grad (const DoubleTab &, DoubleTab &)
double masse_totale (double P, const DoubleTab &T) override
void mettre_a_jour_CL (double P) override
double getM0 ()
Public Member Functions inherited from EDO_Pression_th_base
EDO_Pression_th_base ()
~EDO_Pression_th_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_fluide (const Fluide_Quasi_Compressible &)
Associe le fluide a l'EDO.
virtual void completer ()=0
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void mettre_a_jour_CL (double)=0
virtual double masse_totale (double P, const DoubleTab &T)=0
virtual double resoudre (double)=0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static EDO_Pression_th_VEF & self_cast (Objet_U &)
static const EDO_Pression_th_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from EDO_Pression_th_base
static const Type_info * info ()
static EDO_Pression_th_base & self_cast (Objet_U &)
static const EDO_Pression_th_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from EDO_Pression_th_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VEF la_zone
Ref_Zone_Cl_dis la_zone_Cl
double M0
la masse totale initiale
Protected Attributes inherited from EDO_Pression_th_base
Ref_Fluide_Quasi_Compressible le_fluide_
Detailed Description
classe EDO_Pression_th_VEF
Cette classe represente l'EDO sur la pression associee au schema de
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VEF.
Definition at line 35 of file EDO_Pression_th_VEF.h.
Constructor & Destructor Documentation
~EDO_Pression_th_VEF()
EDO_Pression_th_VEF::~EDO_Pression_th_VEF () override
Definition at line 27 of file EDO_Pression_th_VEF.cpp.
EDO_Pression_th_VEF()
EDO_Pression_th_VEF::EDO_Pression_th_VEF ()
Definition at line 29 of file EDO_Pression_th_VEF.cpp.
: M0(-1.) { }
Member Function Documentation
associer_zones()
void EDO_Pression_th_VEF::associer_zones (const Zone_dis & zone, const Zone_Cl_dis & zone_cl) override virtual
Associe les zones a l'EDO.
Implements EDO_Pression_th_base.
Definition at line 60 of file EDO_Pression_th_VEF.cpp.
{
  la_zone = ref_cast(Zone_VEF,zone.valeur());
  la_zone_Cl = zone_cl;
}
References la_zone, la_zone_Cl, ref_cast, and Deriv_Zone_dis_base::valeur().
calculer_grad()
void EDO_Pression_th_VEF::calculer_grad (const DoubleTab & inco, DoubleTab & grad)
Definition at line 94 of file EDO_Pression_th_VEF.cpp.
{
  assert(0);
  const IntTab& face_voisins = la_zone->face_voisins();
  const DoubleTab& face_normales = la_zone->face_normales();
  const DoubleVect& volumes_entrelaces = la_zone->volumes_entrelaces();
  const DoubleVect& volumes_entrelaces_Cl = ref_cast(Zone_Cl_VEF,la_zone_Cl->valeur()).volumes_entrelaces_Cl();
  double diff;
  int face,comp1;
// Gradient d'un champ scalaire localise aux centres des elements
// On initialise grad a zero
  grad = 0;
  if (1==1)
    {
      int elem1,elem2;
// On traite les faces des joints:
      for (face=0; face<la_zone->nb_faces_joint(); face++)
        {
          elem1 = face_voisins(face,0);
          if (elem1==-1)
            elem1 = face_voisins(face,1);
          diff = -inco[elem1];
          for (comp1=0; comp1<dimension; comp1++)
            grad(face,comp1) = diff*face_normales(face,comp1);
        }
// On traite les conditions limites
// Seule la condition aux limites de type Periodicite modifie le gradient
      for (int n_bord=0; n_bord<la_zone->nb_front_Cl(); n_bord++)
        {
          const Cond_lim& la_cl = la_zone_Cl->les_conditions_limites(n_bord);
          if (sub_type(Periodique,la_cl.valeur()))
            {
// const Periodique& la_cl_perio = (Periodique&) la_cl.valeur();
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              int num1 = le_bord.num_premiere_face();
              int num2 = num1 + le_bord.nb_faces();
              for (face=num1; face<num2; face++)
                {
                  elem1 = face_voisins(face,0);
                  elem2 = face_voisins(face,1);
                  diff = inco[elem2] - inco[elem1];
                  for (int comp2=0; comp2<dimension; comp2++)
                    grad(face,comp2) = diff*face_normales(face,comp2);
                }
            }
        }
// On traite les faces internes
// Cerr << "Faces internes." << finl;
      for (face=la_zone->premiere_face_int(); face<la_zone->nb_faces(); face++)
        {
          elem1 = face_voisins(face,0);
          elem2 = face_voisins(face,1);
          diff = inco[elem2] - inco[elem1];
          for (int comp=0; comp<dimension; comp++)
            grad(face,comp) = diff*face_normales(face,comp);
        }
// On divise par le volume!!!
      int premiere_fac_std=la_zone->premiere_face_std();
      for (face=0; face<premiere_fac_std; face++)
        {
          if (volumes_entrelaces_Cl(face)!=0)
            for (int comp=0; comp<dimension; comp++)
              grad(face,comp) /=volumes_entrelaces_Cl(face);
          else
            for (int comp=0; comp<dimension; comp++)
              grad(face,comp) =0.;
        }
      for (face=premiere_fac_std; face<la_zone->nb_faces(); face++)
        {
          for (int comp=0; comp<dimension; comp++)
            grad(face,comp) /=volumes_entrelaces(face);
        }
    }
  else
    {
      if (Objet_U::dimension==2)
        {
          int elem, nb_som = la_zone->zone().nb_som();
          int som,nsom, nse = la_zone->zone().nb_som_elem();
          const IntTab& som_elem = la_zone->zone().les_elems();
          int s0,s1,elem0,elem1;
          const IntTab& face_sommets = la_zone->face_sommets();
          const DoubleTab& coord_sommets = la_zone->zone().domaine().coord_sommets();
          const DoubleTab& xp = la_zone->xp();
// const DoubleTab& xv = la_zone->xv();
          DoubleTab incosom(nb_som);
          DoubleTab volsom(nb_som);
          incosom = 0;
          volsom = 0;
          double v,inc;
// calcul de P aux sommets
          for (elem=0 ; elem<la_zone->nb_elem() ; elem++)
            {
              v = la_zone->volumes(elem);
              inc = inco[elem];
              for (som=0 ; som<nse ; som++)
                {
                  nsom = som_elem(elem,som);
                  incosom(nsom) += v*inc;
                  volsom(nsom) += v;
                }
            }
          for (nsom=0 ; nsom<nb_som ; nsom++)
            {
              incosom(nsom) /= volsom(nsom);
            }
          double xs0,ys0,xs1,ys1,xe0,ye0,xe1,ye1, ds,de;
// faces de bord
          for (int n_bord=0; n_bord<la_zone->nb_front_Cl(); n_bord++)
            {
              const Cond_lim& la_cl = la_zone_Cl->les_conditions_limites(n_bord);
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              int num1 = le_bord.num_premiere_face();
              int num2 = num1 + le_bord.nb_faces();
              for (face=num1; face<num2; face++)
                {
                  s0 = face_sommets(face,0);
                  s1 = face_sommets(face,1);
                  xs0 = coord_sommets(s0,0);
                  ys0 = coord_sommets(s0,1);
                  xs1 = coord_sommets(s1,0);
                  ys1 = coord_sommets(s1,1);
                  v = volumes_entrelaces(face);
                  ds = (incosom(s1) - incosom(s0))/((xs1-xs0)*(xs1-xs0) + (ys1-ys0)*(ys1-ys0));
                  grad(face,0) = v* (ds*(xs1-xs0));
                  grad(face,1) = v* (ds*(ys1-ys0));
                }
            }
// faces internes
          for (face=la_zone->premiere_face_int() ; face<la_zone->nb_faces(); face++)
            {
              s0 = face_sommets(face,0);
              s1 = face_sommets(face,1);
              elem0 = face_voisins(face,0);
              elem1 = face_voisins(face,1);
              xs0 = coord_sommets(s0,0);
              ys0 = coord_sommets(s0,1);
              xs1 = coord_sommets(s1,0);
              ys1 = coord_sommets(s1,1);
              xe0 = xp(elem0,0);
              ye0 = xp(elem0,1);
              xe1 = xp(elem1,0);
              ye1 = xp(elem1,1);
              v = volumes_entrelaces(face);
              ds = (incosom(s1) - incosom(s0))/((xs1-xs0)*(xs1-xs0) + (ys1-ys0)*(ys1-ys0));
              de = (inco(elem1) - inco(elem0))/((xe1-xe0)*(xe1-xe0) + (ye1-ye0)*(ye1-ye0));
              grad(face,0) = v* (ds*(xs1-xs0) + de*(xe1-xe0));
              grad(face,1) = v* (ds*(ys1-ys0) + de*(ye1-ye0));
            }
        }
      else
        {
          Cerr<<"ATTENTION : gradient de l'inco mal calcule en 3D"<<finl;
        }
    }
}
References Cerr, Domaine::coord_sommets(), Objet_U::dimension, Zone::domaine(), Zone_VEF::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), la_zone, la_zone_Cl, Zone_Cl_dis::les_conditions_limites(), Zone::les_elems(), Zone_dis_base::nb_elem(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_VEF::nb_faces_joint(), Zone_dis_base::nb_front_Cl(), Zone::nb_som(), Zone::nb_som_elem(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), Zone_VEF::premiere_face_std(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Zone_VF::volumes(), Zone_VF::volumes_entrelaces(), Zone_VF::xp(), and Zone_dis_base::zone().
Referenced by EDO_Pression_th_VEF_Gaz_Reel::resoudre().
completer()
void EDO_Pression_th_VEF::completer (void) override virtual
Complete l'EDO : calcule rho sur les faces.
Implements EDO_Pression_th_base.
Definition at line 80 of file EDO_Pression_th_VEF.cpp.
{
  if (!ref_cast(Zone_VEF_PreP1b,la_zone.valeur()).get_alphaE())
    {
      Cerr << "Le modele quasi compressible ne fonctionne pas encore avec cette discretisation." << finl;
      Cerr << "En VEF, la discretisation doit avoir le support P0. Donc utiliser P1Bulle ou P0P1." << finl;
      Process::exit();
    }
  const DoubleTab& tab_ICh = le_fluide_->inco_chaleur().valeurs();
  double Pth=le_fluide_->pression_th();
  M0=masse_totale(Pth,tab_ICh);
  le_fluide_->checkTraitementPth(la_zone_Cl);
}
References Cerr, Fluide_Quasi_Compressible::checkTraitementPth(), Process::exit(), finl, Fluide_Dilatable_base::inco_chaleur(), la_zone, la_zone_Cl, EDO_Pression_th_base::le_fluide_, M0, masse_totale(), Fluide_Dilatable_base::pression_th(), ref_cast, Ref_Zone_VEF::valeur(), and Champ_Inc::valeurs().
get_info()
const Type_info * EDO_Pression_th_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from EDO_Pression_th_base.
Reimplemented in EDO_Pression_th_VEF_Gaz_Parfait, and EDO_Pression_th_VEF_Gaz_Reel.
Definition at line 27 of file EDO_Pression_th_VEF.cpp.
getM0()
double EDO_Pression_th_VEF::getM0 () inline
Definition at line 47 of file EDO_Pression_th_VEF.h.
{ return M0; }
References M0.
info()
const Type_info * EDO_Pression_th_VEF::info () static
Definition at line 27 of file EDO_Pression_th_VEF.cpp.
le_fluide()
const Fluide_Quasi_Compressible & EDO_Pression_th_VEF::le_fluide () const inline
Definition at line 41 of file EDO_Pression_th_VEF.h.
{ return le_fluide_.valeur(); };
References EDO_Pression_th_base::le_fluide_, and Ref_Fluide_Quasi_Compressible::valeur().
masse_totale()
double EDO_Pression_th_VEF::masse_totale (double P, const DoubleTab & T) override virtual
< just copy the structure
Implements EDO_Pression_th_base.
Definition at line 257 of file EDO_Pression_th_VEF.cpp.
{
  int nb_faces = la_zone->nb_faces();
// assert(tab.dimension(0)==nb_faces);
  const Loi_Etat_base& loi_ = ref_cast(Loi_Etat_base,le_fluide_->loi_etat().valeur());
  DoubleVect tmp;
  tmp.copy(T, ArrOfDouble::NOCOPY_NOINIT); //!< just copy the structure
  if (!sub_type(Loi_Etat_Multi_GP_QC,loi_))
    {
      for (int i = 0; i < nb_faces; i++)
        tmp[i] = loi_.calculer_masse_volumique(P, T[i]);
    }
  else
    {
      const Loi_Etat_Multi_GP_QC& loi_mel_GP = ref_cast(Loi_Etat_Multi_GP_QC,loi_);
      const DoubleTab& Masse_mol_mel = loi_mel_GP.masse_molaire();
      for (int i = 0; i < nb_faces; i++)
        {
          double r = 8.3143 / Masse_mol_mel[i];
          tmp[i] = loi_mel_GP.calculer_masse_volumique(P, T[i], r);
        }
    }
  const double M = Champ_P1NC::calculer_integrale_volumique(la_zone.valeur(), tmp, FAUX_EN_PERIO);
  return M;
}
References Champ_P1NC::calculer_integrale_volumique(), Loi_Etat_base::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), TRUSTVect< _TYPE_ >::copy(), FAUX_EN_PERIO, la_zone, EDO_Pression_th_base::le_fluide_, Fluide_Dilatable_base::loi_etat(), Loi_Etat_Multi_GP_base::masse_molaire(), Zone_VF::nb_faces(), Array_base::NOCOPY_NOINIT, ref_cast, sub_type, Deriv_Loi_Etat_base::valeur(), and Ref_Zone_VEF::valeur().
Referenced by completer().
mettre_a_jour_CL()
void EDO_Pression_th_VEF::mettre_a_jour_CL (double P) override virtual
Implements EDO_Pression_th_base.
Definition at line 285 of file EDO_Pression_th_VEF.cpp.
{
  for (int n_bord=0; n_bord<la_zone->nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = la_zone_Cl->les_conditions_limites(n_bord);
      if (sub_type(Sortie_libre_pression_imposee_QC, la_cl.valeur()))
        {
          Sortie_libre_pression_imposee_QC& cl = ref_cast_non_const(Sortie_libre_pression_imposee_QC,la_cl.valeur());
          cl.set_Pth(P);
        }
    }
}
References la_zone, la_zone_Cl, Zone_Cl_dis::les_conditions_limites(), Zone_dis_base::nb_front_Cl(), ref_cast_non_const, Sortie_libre_pression_imposee_QC::set_Pth(), sub_type, and Deriv_Cond_lim_base::valeur().
printOn()
Sortie & EDO_Pression_th_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from EDO_Pression_th_base.
Reimplemented in EDO_Pression_th_VEF_Gaz_Parfait, and EDO_Pression_th_VEF_Gaz_Reel.
Definition at line 31 of file EDO_Pression_th_VEF.cpp.
{
  return EDO_Pression_th_base::printOn(os);
}
References EDO_Pression_th_base::printOn().
readOn()
Entree & EDO_Pression_th_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from EDO_Pression_th_base.
Reimplemented in EDO_Pression_th_VEF_Gaz_Parfait, and EDO_Pression_th_VEF_Gaz_Reel.
Definition at line 36 of file EDO_Pression_th_VEF.cpp.
{
  return EDO_Pression_th_base::readOn(is);
}
References EDO_Pression_th_base::readOn().
self_cast() [1/2]
const EDO_Pression_th_VEF & EDO_Pression_th_VEF::self_cast (const Objet_U & r) static
Definition at line 27 of file EDO_Pression_th_VEF.cpp.
self_cast() [2/2]
EDO_Pression_th_VEF & EDO_Pression_th_VEF::self_cast (Objet_U & r) static
Definition at line 27 of file EDO_Pression_th_VEF.cpp.
Member Data Documentation
info_obj
const Type_info EDO_Pression_th_VEF::info_obj static
Definition at line 37 of file EDO_Pression_th_VEF.h.
la_zone
Ref_Zone_VEF EDO_Pression_th_VEF::la_zone protected
Definition at line 50 of file EDO_Pression_th_VEF.h.
Referenced by associer_zones(), calculer_grad(), completer(), masse_totale(), mettre_a_jour_CL(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), and EDO_Pression_th_VEF_Gaz_Reel::resoudre().
la_zone_Cl
Ref_Zone_Cl_dis EDO_Pression_th_VEF::la_zone_Cl protected
Definition at line 51 of file EDO_Pression_th_VEF.h.
Referenced by associer_zones(), calculer_grad(), completer(), mettre_a_jour_CL(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), and EDO_Pression_th_VEF_Gaz_Reel::resoudre().
M0
double EDO_Pression_th_VEF::M0 protected
la masse totale initiale
Definition at line 52 of file EDO_Pression_th_VEF.h.
Referenced by completer(), and getM0().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VEF/EDO_Pression_th_VEF.h
src/ThHyd/Dilatable/Quasi_Compressible/VEF/EDO_Pression_th_VEF.cpp