TRUST: Char_ptr Class Reference
Char_ptr Class Reference
class Char_ptr
Une chaine de caractere pour nommer les objets de TRUST NOM_H
#include <Char_ptr.h>
Public Member Functions
Char_ptr ()
construit "??"
Char_ptr (const char *nom)
Construction d'un nom a partir d'une chaine de caracteres
La chaine est copiee.
Char_ptr (const Char_ptr &)
Constructeur par copie d'un nom.
virtual ~Char_ptr ()
Destructeur.
void allocate (int n)
operator char * () const
Retourne un pointeur sur la chaine de caractere du nom.
int longueur () const
Renvoie le nombre de caracteres de la chaine du Char_ptr
y compris le caractere zero de fin de chaine.
Exemple : Char_ptr("hello").longueur() == 6.
Char_ptr & operator= (const char *)
Copie la chaine nom.
Modif BM pour que nom puisse pointer sur une sous-partie de nom_.
Char_ptr & operator= (const Char_ptr &)
Copie le Char_ptr nom.
char * getChar ()
const char * getChar () const
Protected Attributes
char * nom_
Detailed Description
class Char_ptr
Une chaine de caractere pour nommer les objets de TRUST NOM_H
Definition at line 40 of file Char_ptr.h.
Constructor & Destructor Documentation
Char_ptr() [1/3]
Char_ptr::Char_ptr ()
construit "??"
Constructeur par defaut.
Cree la chaine "??".
Definition at line 38 of file Char_ptr.cpp.
{
  nom_ = new char[3];
  nom_[0] = '?';
  nom_[1] = '?';
  nom_[2] = 0;
}
References nom_.
Char_ptr() [2/3]
Char_ptr::Char_ptr (const char * nom)
Construction d'un nom a partir d'une chaine de caracteres
La chaine est copiee.
Definition at line 63 of file Char_ptr.cpp.
{
  nom_ = 0;
  operator=(nom);
}
References nom_, and operator=().
Char_ptr() [3/3]
Char_ptr::Char_ptr (const Char_ptr & nom)
Constructeur par copie d'un nom.
Definition at line 83 of file Char_ptr.cpp.
{
  nom_ = 0;
  operator=(nom);
}
References nom_, and operator=().
~Char_ptr()
Char_ptr::~Char_ptr () virtual
Destructeur.
Definition at line 103 of file Char_ptr.cpp.
{
  if(nom_)
    delete[] nom_;
}
References nom_.
Member Function Documentation
allocate()
void Char_ptr::allocate (int n)
Definition at line 177 of file Char_ptr.cpp.
{
  if (nom_)
    delete [] nom_;
  nom_=new char[n+1];
  for (int i=0; i<n; i++)
    nom_[i]=' ';
  nom_[n]='\0';
}
References nom_.
Referenced by dimensionne_char_ptr_taille(), Champ_Fonc_MED::lire(), and StringTokenizer::nextToken().
getChar() [1/2]
char * Char_ptr::getChar () inline
Definition at line 52 of file Char_ptr.h.
  {
    return nom_;
  }
References nom_.
Referenced by StringTokenizer::nextToken().
getChar() [2/2]
const char * Char_ptr::getChar () const inline
Definition at line 56 of file Char_ptr.h.
  {
    return nom_;
  }
References nom_.
longueur()
int Char_ptr::longueur () const
Renvoie le nombre de caracteres de la chaine du Char_ptr
y compris le caractere zero de fin de chaine.
Exemple : Char_ptr("hello").longueur() == 6.
Definition at line 114 of file Char_ptr.cpp.
{
  return (strlen(nom_)+1);
}
References nom_.
operator char *()
Char_ptr::operator char * () const
Retourne un pointeur sur la chaine de caractere du nom.
Returns
char*
Signification: pointeur sur la chaine de caractere du nom
Contraintes:
Definition at line 171 of file Char_ptr.cpp.
{
  return nom_;
}
operator=() [1/2]
Char_ptr & Char_ptr::operator= (const char * nom)
Copie la chaine nom.
Modif BM pour que nom puisse pointer sur une sous-partie de nom_.
Definition at line 122 of file Char_ptr.cpp.
{
  if (nom_ == nom)
    return *this;
  char *old = nom_;
  const char *n = nom;
  if (!n)
    n = "??";
  nom_ = new char[strlen(n)+1];
  strcpy(nom_, n);
// On efface l'ancien apres avoir copie le nouveau au cas ou nom est une partie de nom_
  delete [] old;
  return *this;
}
References nom_.
Referenced by Char_ptr(), and operator=().
operator=() [2/2]
Char_ptr & Char_ptr::operator= (const Char_ptr & nom)
Copie le Char_ptr nom.
Returns
Char_ptr&
Signification: reference sur this qui represente la chaine du Char_ptr nom
Contraintes:
Definition at line 151 of file Char_ptr.cpp.
{
  operator=(nom.nom_);
  return *this;
}
References nom_, and operator=().
Member Data Documentation
nom_
char* Char_ptr::nom_ protected
Definition at line 62 of file Char_ptr.h.
Referenced by allocate(), Char_ptr(), getChar(), longueur(), operator=(), and ~Char_ptr().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Char_ptr.h
src/Kernel/Utilitaires/Char_ptr.cpp