TRUST: Eval_Centre_VDF_Face Class Reference
Eval_Centre_VDF_Face Class Reference
class Eval_Centre_VDF_Face
Evaluateur VDF pour la convection
Le champ convecte est un Champ_Face
Schema de convection Centre
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
Rq:Pour les bords, le calcul se fait avec le schema Amont.
#include <Eval_Centre_VDF_Face.h>
Public Member Functions
Eval_Centre_VDF_Face ()
int calculer_arete_fluide () const
int calculer_arete_paroi () const
int calculer_arete_paroi_fluide () const
int calculer_arete_symetrie () const
int calculer_arete_interne () const
int calculer_arete_mixte () const
int calculer_fa7_sortie_libre () const
int calculer_arete_periodicite () const
int calculer_arete_symetrie_paroi () const
int calculer_arete_symetrie_fluide () const
double flux_fa7_elem (const DoubleTab &, int, int, int) const
double flux_fa7_sortie_libre (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double flux_arete_interne (const DoubleTab &, int, int, int, int) const
double flux_arete_mixte (const DoubleTab &, int, int, int, int) const
double flux_arete_paroi (const DoubleTab &, int, int, int, int) const
double flux_arete_symetrie (const DoubleTab &, int, int, int, int) const
void flux_arete_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_paroi_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_periodicite (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_symetrie_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
double flux_arete_symetrie_paroi (const DoubleTab &, int, int, int, int) const
void flux_fa7_elem (const DoubleTab &, int, int, int, DoubleVect &flux) const
void flux_fa7_sortie_libre (const DoubleTab &, int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void flux_arete_interne (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_mixte (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_symetrie (const DoubleTab &, int, int, int, int, DoubleVect &) const
void flux_arete_paroi (const DoubleTab &, int, int, int, int, DoubleVect &) const
void flux_arete_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_paroi_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_periodicite (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_symetrie_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_symetrie_paroi (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
Detailed Description
class Eval_Centre_VDF_Face
Evaluateur VDF pour la convection
Le champ convecte est un Champ_Face
Schema de convection Centre
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
Rq:Pour les bords, le calcul se fait avec le schema Amont.
See also:
Eval_Conv_VDF
Definition at line 46 of file Eval_Centre_VDF_Face.h.
Constructor & Destructor Documentation
Eval_Centre_VDF_Face::Eval_Centre_VDF_Face () [inline]
Definition at line 109 of file Eval_Centre_VDF_Face.h.
{
}
Member Function Documentation
int Eval_Centre_VDF_Face::calculer_arete_fluide () const [inline]
Definition at line 116 of file Eval_Centre_VDF_Face.h.
{
  return 1;
}
int Eval_Centre_VDF_Face::calculer_arete_interne () const [inline]
Definition at line 158 of file Eval_Centre_VDF_Face.h.
{
  return 1;
}
int Eval_Centre_VDF_Face::calculer_arete_mixte () const [inline]
Definition at line 166 of file Eval_Centre_VDF_Face.h.
{
  return 1;
}
int Eval_Centre_VDF_Face::calculer_arete_paroi () const [inline]
Definition at line 125 of file Eval_Centre_VDF_Face.h.
{
  return 0;
}
int Eval_Centre_VDF_Face::calculer_arete_paroi_fluide () const [inline]
Definition at line 134 of file Eval_Centre_VDF_Face.h.
{
  return 1;
}
int Eval_Centre_VDF_Face::calculer_arete_periodicite () const [inline]
Definition at line 142 of file Eval_Centre_VDF_Face.h.
{
  return 1;
}
int Eval_Centre_VDF_Face::calculer_arete_symetrie () const [inline]
Definition at line 150 of file Eval_Centre_VDF_Face.h.
{
  return 0;
}
int Eval_Centre_VDF_Face::calculer_arete_symetrie_fluide () const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 190 of file Eval_Centre_VDF_Face.h.
{
  return 1;
}
int Eval_Centre_VDF_Face::calculer_arete_symetrie_paroi () const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 182 of file Eval_Centre_VDF_Face.h.
{
  return 0;
}
int Eval_Centre_VDF_Face::calculer_fa7_sortie_libre () const [inline]
Definition at line 174 of file Eval_Centre_VDF_Face.h.
{
  return 1;
}
void Eval_Centre_VDF_Face::flux_arete_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Definition at line 201 of file Eval_Centre_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double flux,psc;
// Calcul de flux3:
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    flux=inco[fac3]*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      flux = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl))* psc ;
    }
  flux3 =  -flux;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*0.5*(inco[fac1]+inco[fac2]);
  flux1_2 = -flux;
}
void Eval_Centre_VDF_Face::flux_arete_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Definition at line 459 of file Eval_Centre_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<flux3.size(); k++)
      flux3(k) = -inco(fac3,k)*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,k,ori,la_zcl))* psc ;
    }
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_Centre_VDF_Face::flux_arete_interne (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, DoubleVect & flux) const [inline]
Definition at line 497 of file Eval_Centre_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] ) *
               ( surface[fac1] + surface[fac2] );
  for (k=0; k<flux.size(); k++)
    flux(k) = -psc*0.5*(inco(fac3,k)+inco(fac4,k));
}
double Eval_Centre_VDF_Face::flux_arete_interne (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4) const [inline]
Definition at line 245 of file Eval_Centre_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] ) *
               ( surface[fac1] + surface[fac2] );
  flux = 0.5*(inco[fac3]+inco[fac4])*psc ;
  return -flux;
}
void Eval_Centre_VDF_Face::flux_arete_mixte (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, DoubleVect & flux) const [inline]
Definition at line 513 of file Eval_Centre_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] ) *
               ( surface[fac1] + surface[fac2] );
  for (k=0; k<flux.size(); k++)
    flux(k) = -psc*0.5*(inco(fac3,k)+inco(fac4,k));
}
double Eval_Centre_VDF_Face::flux_arete_mixte (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4) const [inline]
Definition at line 263 of file Eval_Centre_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] ) *
               ( surface[fac1] + surface[fac2] );
  flux = psc*0.5*(inco[fac3]+inco[fac4]);
  return -flux;
}
void Eval_Centre_VDF_Face::flux_arete_paroi (const DoubleTab & , int , int , int , int , DoubleVect &) const [inline]
Definition at line 530 of file Eval_Centre_VDF_Face.h.
{
  ;
}
double Eval_Centre_VDF_Face::flux_arete_paroi (const DoubleTab & , int , int , int , int) const [inline]
Definition at line 281 of file Eval_Centre_VDF_Face.h.
{
  return 0;
}
void Eval_Centre_VDF_Face::flux_arete_paroi_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Definition at line 541 of file Eval_Centre_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<flux3.size(); k++)
      flux3(k) = -inco(fac3,k)*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,k,ori,la_zcl))* psc ;
    }
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_Centre_VDF_Face::flux_arete_paroi_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Definition at line 290 of file Eval_Centre_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double psc,flux;
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    flux=inco[fac3]*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      flux = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl))* psc ;
    }
  flux3 = -flux;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*0.5*(inco[fac1]+inco[fac2]);
  flux1_2 = -flux;
}
void Eval_Centre_VDF_Face::flux_arete_periodicite (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, DoubleVect & flux3_4, DoubleVect & flux1_2) const [inline]
Definition at line 578 of file Eval_Centre_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  double psc;
  int k;
// On calcule le flux convectif entre les volumes de controle associes a fac3 et fac4:
  psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                 dt_vitesse[fac2]*porosite[fac2] ) *
        ( surface[fac1] + surface[fac2] );
  for (k=0; k<flux3_4.size(); k++)
    flux3_4(k) = -psc*0.5*(inco(fac3,k)+inco(fac4,k));
// On calcule le flux convectifs entre les volumes de controle associes a fac1 et fac2:
  psc = 0.25 * ( dt_vitesse[fac3]*porosite[fac3] +
                 dt_vitesse[fac4]*porosite[fac4] ) *
        ( surface[fac3] + surface[fac4] );
  for (k=0; k<flux1_2.size(); k++)
    flux1_2(k) = -psc*0.5*(inco(fac1,k)+inco(fac2,k));
}
void Eval_Centre_VDF_Face::flux_arete_periodicite (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, double & flux3_4, double & flux1_2) const [inline]
Definition at line 326 of file Eval_Centre_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  double psc;
// On calcule le flux convectif entre les volumes de controle associes a fac3 et fac4:
  psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                 dt_vitesse[fac2]*porosite[fac2] ) *
        ( surface[fac1] + surface[fac2] );
  flux = psc*0.5*(inco[fac3]+inco[fac4]);
  flux3_4 = -flux;
// On calcule le flux convectif entre les volumes de controle associes a fac1 et fac2:
  psc = 0.25 * ( dt_vitesse[fac3]*porosite[fac3] +
                 dt_vitesse[fac4]*porosite[fac4] ) *
        ( surface[fac3] + surface[fac4] );
  flux = psc*0.5*(inco[fac1]+inco[fac2]);
  flux1_2 = -flux;
}
void Eval_Centre_VDF_Face::flux_arete_symetrie (const DoubleTab & , int , int , int , int , DoubleVect &) const [inline]
Definition at line 608 of file Eval_Centre_VDF_Face.h.
{
  ;
}
double Eval_Centre_VDF_Face::flux_arete_symetrie (const DoubleTab & , int , int , int , int) const [inline]
Definition at line 359 of file Eval_Centre_VDF_Face.h.
{
  return 0;
}
void Eval_Centre_VDF_Face::flux_arete_symetrie_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 659 of file Eval_Centre_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<flux3.size(); k++)
      flux3(k) = -inco(fac3,k)*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,k,ori,la_zcl))* psc ;
    }
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_Centre_VDF_Face::flux_arete_symetrie_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 406 of file Eval_Centre_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord_sym(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double flux,psc;
// Calcul de flux3:
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    flux=inco[fac3]*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      flux = 0.5*(Champ_Face_get_val_imp_face_bord_sym(inco,inconnue->temps(),rang1,ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord_sym(inco,inconnue->temps(),rang2,ori,la_zcl))* psc ;
    }
  flux3 =  -flux;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*0.5*(inco[fac1]+inco[fac2]);
  flux1_2 = -flux;
}
void Eval_Centre_VDF_Face::flux_arete_symetrie_paroi (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 696 of file Eval_Centre_VDF_Face.h.
{
  ;
}
double Eval_Centre_VDF_Face::flux_arete_symetrie_paroi (const DoubleTab & , int , int , int , int) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 449 of file Eval_Centre_VDF_Face.h.
{
  return 0;
}
void Eval_Centre_VDF_Face::flux_fa7_elem (const DoubleTab & inco, int , int fac1, int fac2, DoubleVect & flux) const [inline]
Definition at line 618 of file Eval_Centre_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * (dt_vitesse[fac1]+dt_vitesse[fac2])*
               (surface[fac1]+surface[fac2]);
  if (psc>0)
    for (k=0; k<flux.size(); k++)
      flux(k) = -psc*0.5*(inco(fac1,k)*porosite[fac1]+inco(fac2,k)*porosite[fac2]);
}
double Eval_Centre_VDF_Face::flux_fa7_elem (const DoubleTab & inco, int , int fac1, int fac2) const [inline]
Definition at line 368 of file Eval_Centre_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  double psc = 0.25 * (dt_vitesse[fac1]+dt_vitesse[fac2]) *
               (surface[fac1]+surface[fac2]);
  flux = psc * 0.5*(inco[fac1]*porosite[fac1]+inco[fac2]*porosite[fac2]);
  return -flux;
}
void Eval_Centre_VDF_Face::flux_fa7_sortie_libre (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const [inline]
< (elem2 != -1)
Definition at line 633 of file Eval_Centre_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  double psc = dt_vitesse[face]*surface(face);
  int elem1 = elem_(face,0);
  int k;
  if (elem1 != -1)
    if (psc > 0)
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*inco(face,k)*porosite[face];
    else
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*la_cl.val_ext(face-num1,k);
  else //!< (elem2 != -1)
    if (psc < 0)
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*inco(face,k)*porosite[face];
    else
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*la_cl.val_ext(face-num1,k);
}
double Eval_Centre_VDF_Face::flux_fa7_sortie_libre (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1) const [inline]
< (elem2 != -1)
Definition at line 382 of file Eval_Centre_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  double flux;
  double psc = dt_vitesse[face]*surface(face);
  int elem1 = elem_(face,0);
// ce qui est fait en Amont
  if (elem1 != -1)
    if (psc > 0)
      flux = psc*inco[face]*porosite[face];
    else
      flux = psc*la_cl.val_ext(face-num1,orientation(face));
  else //!< (elem2 != -1)
    if (psc < 0)
      flux = psc*inco[face]*porosite[face];
    else
      flux = psc*la_cl.val_ext(face-num1,orientation(face));
  return -flux;
}
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs/Eval_Centre_VDF_Face.h