TRUST: Vect_Nom Class Reference
Vect_Nom Class Reference
#include <Noms.h>
Public Member Functions
~Vect_Nom ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Vect_Nom ()
Vect_Nom (int)
const Nom & operator[] (int) const
const Nom & operator() (int i) const
Nom & operator[] (int)
Nom & operator() (int i)
Vect_Nom (const Vect_Nom &)
Vect_Nom & operator= (const Vect_Nom &)
Nom & add (const Nom &titi)
Nom & add ()
void add (const Vect_Nom &)
Entree & lit (Entree &)
Public Member Functions inherited from vect_impl
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
vect_impl ()
int size () const
void build_vect_impl (int)
const Objet_U & operator[] (int) const
Objet_U & operator[] (int)
vect_impl (const vect_impl &)
~vect_impl () override
vect_impl & operator= (const vect_impl &)
void dimensionner (int)
void dimensionner_force (int)
void reset ()
vect_impl & add (const Objet_U &)
vect_impl & add (const vect_impl &)
Entree & lit (Entree &)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Vect_Nom & self_cast (Objet_U &)
static const Vect_Nom & self_cast (const Objet_U &)
Static Public Member Functions inherited from vect_impl
static Objet_U * cree_instance ()
static const Type_info * info ()
static vect_impl & self_cast (Objet_U &)
static const vect_impl & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from vect_impl
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Objet_U * cree_une_instance () const override
methhode surcharge par les classes filles pour fournir la bonne
instance aux constructeurs au readOn....
Protected Member Functions inherited from vect_impl
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual Objet_U * cree_une_instance () const
methhode surcharge par les classes filles pour fournir la bonne
instance aux constructeurs au readOn....
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from vect_impl
int sz
DerObjU * data
Detailed Description
Definition at line 21 of file Noms.h.
Constructor & Destructor Documentation
~Vect_Nom()
Vect_Nom::~Vect_Nom ()
Definition at line 17 of file Noms.cpp.
Vect_Nom() [1/3]
Vect_Nom::Vect_Nom ()
Definition at line 17 of file Noms.cpp.
Vect_Nom() [2/3]
Vect_Nom::Vect_Nom (int i)
Definition at line 17 of file Noms.cpp.
Vect_Nom() [3/3]
Vect_Nom::Vect_Nom (const Vect_Nom & avect)
Definition at line 17 of file Noms.cpp.
Member Function Documentation
add() [1/3]
Nom & Vect_Nom::add ()
Definition at line 17 of file Noms.cpp.
add() [2/3]
Nom & Vect_Nom::add (const Nom & titi)
Definition at line 17 of file Noms.cpp.
Referenced by MD_Vector_composite::add_part(), Field_base::add_synonymous(), Champs_compris::ajoute_nom_compris(), Interprete_bloc::ajouter(), calculer_elements_voisins_bords(), Champ_Generique_Transformation::completer(), Domaine::construire_renum_som_perio(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Champ_Fonc_MED::creer(), Champ_Gen_de_Champs_Gen::creer_espace_stockage(), Champ_Generique_Morceau_Equation::creer_espace_stockage(), Probleme_base::discretiser(), Discretisation_base::discretiser_champ(), DomaineCutter::ecrire_zones(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_Tparoi_VEF::get_champ_without_evaluation(), Sondes::get_from_cache(), Chimie::get_noms_champs_postraitables(), Equation_base::get_noms_champs_postraitables(), Loi_Fermeture_base::get_noms_champs_postraitables(), Milieu_base::get_noms_champs_postraitables(), Operateur_base::get_noms_champs_postraitables(), Source_base::get_noms_champs_postraitables(), Pb_MED::get_noms_champs_postraitables(), Loi_Etat_base::get_noms_champs_postraitables(), Puissance_Thermique_QC_EF::get_noms_champs_postraitables(), Marqueur_Lagrange_base::get_noms_champs_postraitables(), Traitement_particulier_NS_base::get_noms_champs_postraitables(), Mod_turb_hyd_base::get_noms_champs_postraitables(), Modele_turbulence_scal_base::get_noms_champs_postraitables(), Turbulence_paroi_base::get_noms_champs_postraitables(), Turbulence_paroi_scal_base::get_noms_champs_postraitables(), Conduction::get_noms_champs_postraitables(), Traitement_particulier_Solide_base::get_noms_champs_postraitables(), Probleme_base::getInputFieldsNames(), Probleme_base::getOutputFieldsNames(), Postraitement::init(), Phases::interpreter(), Create_domain_from_sous_zone::interpreter_(), Pb_Multiphase::lire_equations(), Champ_Fonc_Fonction::readOn(), Champ_Fonc_Fonction_txyz::readOn(), Champ_Fonc_Tabule::readOn(), Debog_Pb::register_item(), and Moyenne_volumique::traiter_champs().
add() [3/3]
void Vect_Nom::add (const Vect_Nom & data_to_add)
Definition at line 17 of file Noms.cpp.
cree_instance()
Objet_U * Vect_Nom::cree_instance () static
Definition at line 17 of file Noms.cpp.
cree_une_instance()
Objet_U * Vect_Nom::cree_une_instance () const override protected virtual
methhode surcharge par les classes filles pour fournir la bonne
instance aux constructeurs au readOn....
Reimplemented from vect_impl.
Definition at line 17 of file Noms.cpp.
duplique()
int Vect_Nom::duplique () const override virtual
Implements Objet_U.
Reimplemented in Noms.
Definition at line 17 of file Noms.cpp.
get_info()
const Type_info * Vect_Nom::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Noms.
Definition at line 17 of file Noms.cpp.
info()
const Type_info * Vect_Nom::info () static
Definition at line 17 of file Noms.cpp.
lit()
Entree & Vect_Nom::lit (Entree & s)
Definition at line 17 of file Noms.cpp.
operator()() [1/2]
Nom & Vect_Nom::operator() (int i) inline
Definition at line 21 of file Noms.h.
: public VECT(Nom)
operator()() [2/2]
const Nom & Vect_Nom::operator() (int i) const inline
Definition at line 21 of file Noms.h.
: public VECT(Nom)
Referenced by Noms::search_without_checking_Motcle().
operator=()
Vect_Nom & Vect_Nom::operator= (const Vect_Nom & avect)
Definition at line 17 of file Noms.cpp.
operator[]() [1/2]
Nom & Vect_Nom::operator[] (int i) inline
Definition at line 21 of file Noms.h.
: public VECT(Nom)
operator[]() [2/2]
const Nom & Vect_Nom::operator[] (int i) const inline
Definition at line 21 of file Noms.h.
: public VECT(Nom)
printOn()
Sortie & Vect_Nom::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Noms.
Definition at line 17 of file Noms.cpp.
readOn()
Entree & Vect_Nom::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Noms.
Definition at line 17 of file Noms.cpp.
self_cast() [1/2]
const Vect_Nom & Vect_Nom::self_cast (const Objet_U & r) static
Definition at line 17 of file Noms.cpp.
self_cast() [2/2]
Vect_Nom & Vect_Nom::self_cast (Objet_U & r) static
Definition at line 17 of file Noms.cpp.
taille_memoire()
unsigned Vect_Nom::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Noms.
Definition at line 17 of file Noms.cpp.
Member Data Documentation
info_obj
const Type_info Vect_Nom::info_obj static
Definition at line 21 of file Noms.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Noms.h
src/Kernel/Utilitaires/Noms.cpp