TRUST: Analyse_Angle Class Reference
Analyse_Angle Class Reference
#include <Analyse_Angle.h>
Public Member Functions
Analyse_Angle ()
~Analyse_Angle ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Analyse_Angle & self_cast (Objet_U &)
static const Analyse_Angle & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 35 of file Analyse_Angle.h.
Constructor & Destructor Documentation
Analyse_Angle::Analyse_Angle ()
Definition at line 27 of file Analyse_Angle.cpp.
Analyse_Angle::~Analyse_Angle ()
Definition at line 27 of file Analyse_Angle.cpp.
Member Function Documentation
Objet_U * Analyse_Angle::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 27 of file Analyse_Angle.cpp.
int Analyse_Angle::duplique () const [virtual]
Reimplemented from Interprete.
Definition at line 27 of file Analyse_Angle.cpp.
const Type_info * Analyse_Angle::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 27 of file Analyse_Angle.cpp.
const Type_info * Analyse_Angle::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 27 of file Analyse_Angle.cpp.
Entree & Analyse_Angle::interpreter (Entree & is) [virtual]
Reimplemented from Interprete.
Definition at line 102 of file Analyse_Angle.cpp.
References Cout, histogramme_angle(), Interprete::objet(), and ref_cast.
{
  int nb_histo;
  Nom nom_dom;
  is >> nom_dom;
  is >> nb_histo;
  Domaine& dom=ref_cast(Domaine,objet(nom_dom));
  histogramme_angle(dom,Cout,nb_histo);
  return is;
}
Sortie & Analyse_Angle::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 32 of file Analyse_Angle.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Analyse_Angle::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 37 of file Analyse_Angle.cpp.
{
//
// VERIFIER ICI QU'ON A BIEN TOUT LU;
//
  return is;
}
Analyse_Angle & Analyse_Angle::self_cast (Objet_U & r) [static]
Reimplemented from Interprete.
Definition at line 27 of file Analyse_Angle.cpp.
const Analyse_Angle & Analyse_Angle::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete.
Definition at line 27 of file Analyse_Angle.cpp.
unsigned Analyse_Angle::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 27 of file Analyse_Angle.cpp.
Member Data Documentation
const Type_info Analyse_Angle::info_obj [static]
Reimplemented from Interprete.
Definition at line 38 of file Analyse_Angle.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Analyse_Angle.h
src/Kernel/Geometrie/Analyse_Angle.cpp