TRUST: Deriv_SolveurSys_base Class Reference
Deriv_SolveurSys_base Class Reference
class SolveurSys
Un SolveurSys represente n'importe qu'elle classe
derivee de la classe SolveurSys_base
#include <SolveurSys.h>
Public Member Functions
~Deriv_SolveurSys_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_SolveurSys_base ()
Deriv_SolveurSys_base (const Deriv_SolveurSys_base &)
const SolveurSys_base & valeur () const
SolveurSys_base & valeur ()
const SolveurSys_base * operator-> () const
SolveurSys_base * operator-> ()
const Deriv_SolveurSys_base & operator= (const SolveurSys_base &)
const Deriv_SolveurSys_base & operator= (const Deriv_SolveurSys_base &)
operator const SolveurSys_base & () const
operator SolveurSys_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_SolveurSys_base & self_cast (Objet_U &)
static const
Deriv_SolveurSys_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
SolveurSys_base * pointeur_
Detailed Description
class SolveurSys
Un SolveurSys represente n'importe qu'elle classe
derivee de la classe SolveurSys_base
Definition at line 38 of file SolveurSys.h.
Constructor & Destructor Documentation
Deriv_SolveurSys_base::~Deriv_SolveurSys_base ()
Definition at line 28 of file SolveurSys.cpp.
Deriv_SolveurSys_base::Deriv_SolveurSys_base ()
Definition at line 28 of file SolveurSys.cpp.
Deriv_SolveurSys_base::Deriv_SolveurSys_base (const Deriv_SolveurSys_base & t)
Definition at line 28 of file SolveurSys.cpp.
Member Function Documentation
Objet_U * Deriv_SolveurSys_base::cree_instance () [static]
Reimplemented in SolveurSys.
Definition at line 28 of file SolveurSys.cpp.
int Deriv_SolveurSys_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in SolveurSys.
Definition at line 28 of file SolveurSys.cpp.
const Type_info * Deriv_SolveurSys_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in SolveurSys.
Definition at line 28 of file SolveurSys.cpp.
const Type_info & Deriv_SolveurSys_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 28 of file SolveurSys.cpp.
const Type_info * Deriv_SolveurSys_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in SolveurSys.
Definition at line 28 of file SolveurSys.cpp.
Deriv_SolveurSys_base::operator const SolveurSys_base & () const
Definition at line 28 of file SolveurSys.cpp.
Deriv_SolveurSys_base::operator SolveurSys_base & ()
Definition at line 28 of file SolveurSys.cpp.
const SolveurSys_base * Deriv_SolveurSys_base::operator-> () const [inline]
Definition at line 38 of file SolveurSys.h.
: public DERIV(SolveurSys_base)
SolveurSys_base * Deriv_SolveurSys_base::operator-> () [inline]
Definition at line 38 of file SolveurSys.h.
: public DERIV(SolveurSys_base)
const Deriv_SolveurSys_base & Deriv_SolveurSys_base::operator= (const Deriv_SolveurSys_base & t)
Definition at line 28 of file SolveurSys.cpp.
const Deriv_SolveurSys_base & Deriv_SolveurSys_base::operator= (const SolveurSys_base & t)
Definition at line 28 of file SolveurSys.cpp.
Sortie & Deriv_SolveurSys_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in SolveurSys.
Definition at line 28 of file SolveurSys.cpp.
Entree & Deriv_SolveurSys_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in SolveurSys.
Definition at line 28 of file SolveurSys.cpp.
const Deriv_SolveurSys_base & Deriv_SolveurSys_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in SolveurSys.
Definition at line 28 of file SolveurSys.cpp.
Deriv_SolveurSys_base & Deriv_SolveurSys_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in SolveurSys.
Definition at line 28 of file SolveurSys.cpp.
void Deriv_SolveurSys_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 28 of file SolveurSys.cpp.
unsigned Deriv_SolveurSys_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in SolveurSys.
Definition at line 28 of file SolveurSys.cpp.
const SolveurSys_base & Deriv_SolveurSys_base::valeur () const [inline]
Definition at line 38 of file SolveurSys.h.
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), Simpler_Base::assembler_matrice_pression_implicite(), Op_Dift_VEF_P1NCP1B_Face::associer(), Op_Diff_RotRot::associer(), Op_Diff_RotRot::calculer_vorticite(), Champ_P1NC_implementation::Champ_P1NC_implementation(), construire_matrice_implicite(), corriger(), Navier_Stokes_std::derivee_en_temps_inco(), SolveurPP1B::fixer_schema_temps_limpr(), Navier_Stokes_std::impr(), Simple::iterer_eqn(), Solveur_Lineaire_Std::iterer_eqn(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), Simpler::iterer_NS(), Simple::iterer_NS(), Piso::iterer_NS(), Piso::iterer_NS_PolyMAC(), Navier_Stokes_std::mettre_a_jour(), PrecondSolv::prepare_(), Precond_local::prepare_(), Navier_Stokes_std::projeter(), Navier_Stokes_std::readOn(), Solveur_Lineaire_Std::readOn(), SolveurSys::readOn(), Precond_local::readOn(), SolveurPP1B::reinit(), Solv_GCP_NS::reinit(), SolveurSys::resoudre_systeme(), SolveurPP1B::solveur_direct(), SolveurSys::supporte_matrice_morse_sym(), PrecondSolv::supporte_matrice_morse_sym(), and Op_Diff_RotRot::tester().
: public DERIV(SolveurSys_base)
SolveurSys_base & Deriv_SolveurSys_base::valeur () [inline]
Definition at line 38 of file SolveurSys.h.
: public DERIV(SolveurSys_base)
Member Data Documentation
const Type_info Deriv_SolveurSys_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in SolveurSys.
Definition at line 38 of file SolveurSys.h.
SolveurSys_base* Deriv_SolveurSys_base::pointeur_ [private]
Definition at line 38 of file SolveurSys.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/SolveurSys.h
src/Kernel/Math/SolvSys/SolveurSys.cpp