TRUST: Zone_Cl_VEF Class Reference
Zone_Cl_VEF Class Reference
#include <Zone_Cl_VEF.h>
Public Member Functions
Zone_Cl_VEF ()
~Zone_Cl_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_VEF &)
etape de discretisation : dimensionnement des tableaux
void completer (const Zone_dis &) override
remplissage des tableaux
int initialiser (double temps) override
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
void imposer_cond_lim (Champ_Inc &, double) override
Impose les conditions aux limites a la valeur temporelle "temps" du
Champ_Inc.
virtual void remplir_volumes_entrelaces_Cl (const Zone_VEF &)
appele par completer() : remplissage de type_elem_Cl_ et
volumes_entrelaces_Cl_
void remplir_normales_facettes_Cl (const Zone_VEF &)
appele par completer() : remplissage de normales_facettes_Cl_
et vecteur_face_caette_Cl_
CHANGER LE NOM
void remplir_vecteur_face_facette_Cl (const Zone_VEF &)
DoubleVect & volumes_entrelaces_Cl ()
const DoubleVect & volumes_entrelaces_Cl () const
const double & volumes_entrelaces_Cl (int) const
double & volumes_entrelaces_Cl (int)
DoubleTab & normales_facettes_Cl ()
const DoubleTab & normales_facettes_Cl () const
const double & normales_facettes_Cl (int, int, int) const
double & normales_facettes_Cl (int, int, int)
DoubleTab & vecteur_face_facette_Cl ()
const DoubleTab & vecteur_face_facette_Cl () const
int type_elem_Cl (int) const
int nb_faces_sortie_libre () const
Zone_VEF & zone_VEF ()
const Zone_VEF & zone_VEF () const
int nb_bord_periodicite () const
Public Member Functions inherited from Zone_Cl_dis_base
Zone_Cl_dis_base ()
~Zone_Cl_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Cond_lim & les_conditions_limites (int) const
Renvoie la i-ieme condition aux limites.
(version const)
Cond_lim & les_conditions_limites (int)
Renvoie la i-ieme condition aux limites.
Conds_lim & les_conditions_limites ()
Renvoie le tableaux des conditions aux limites.
const Conds_lim & les_conditions_limites () const
Renvoie le tableaux des conditions aux limites.
(version const)
int nb_cond_lim () const
Renvoie le nombre de conditions aux limites.
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de toutes les conditions
aux limites.
virtual void mettre_a_jour_ss_pas_dt (double temps)
Effectue une mise a jour pour des sous pas de temps
d'un schema en temps (par exemple dans RungeKutta)
pour toutes les Cond Lims renvoyant 1 par le biais de la methode
int Cond_Lim_base::a_mettre_a_jour_ss_pas_dt();.
void completer ()
Appel Cond_lim_base::completer() sur chaque
condition aux limites.
int contient_Cl (const Nom &)
Renvoie 1 si l'objet contient une condition aux limites
du Nom specifie.
Renvoie 0 sinon.
Zone_dis & zone_dis ()
Renvoie une reference sur la zone discretisee associee aux conditions
aux limites. Cette Zone_dis est associee au travers de l'equation
associee et pas directement a l'objet Zone_Cl_dis_base.
const Zone_dis & zone_dis () const
Renvoie une reference sur la zone discretisee associee aux conditions
aux limites. Cette Zone_dis est associee au travers de l'equation
associee et pas directement a l'objet Zone_Cl_dis_base.
(version const)
Zone & zone ()
const Zone & zone () const
virtual int calculer_coeffs_echange (double temps)
Calcul des coefficients d'echange pour les problemes couples thermiques.
virtual void imposer_cond_lim (Champ_Inc &, double)=0
int nb_faces_Cl () const
virtual const Cond_lim & la_cl_de_la_face (int num_face) const
A partir d'un indice de face de bord dans la Zone_VF,
renvoie la condition aux limites a laquelle cette face
appartient, pour 0 <= num_face < nb_faces_Cl().
const Cond_lim_base & condition_limite_de_la_face_reelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_face_virtuelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere) const
Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere)
void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de toutes les CLs.
void Gpoint (double t1, double t2)
void set_temps_defaut (double temps)
Change le i-eme temps futur de toutes les CLs.
int avancer (double temps)
Tourne la roue des CLs jusqu'au temps donne.
int reculer (double temps)
Tourne la roue des CLsj usqu'au temps donne.
virtual int initialiser (double temps)
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
virtual void associer_inconnue (const Champ_Inc &)
virtual const Champ_Inc & inconnue () const
virtual Champ_Inc & inconnue ()
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_Cl_VEF & self_cast (Objet_U &)
static const Zone_Cl_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_Cl_dis_base
static const Type_info * info ()
static Zone_Cl_dis_base & self_cast (Objet_U &)
static const Zone_Cl_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Zone_Cl_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
void remplir_type_elem_Cl (const Zone_VEF &)
appele par remplir_volumes_entrelaces_Cl() : remplissage de type_elem_Cl_
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
virtual void completer (const Zone_dis &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
DoubleVect volumes_entrelaces_Cl_
DoubleTab normales_facettes_Cl_
DoubleTab vecteur_face_facette_Cl_
IntVect type_elem_Cl_
int modif_perio_fait_
Protected Attributes inherited from Zone_Cl_dis_base
Nom nom_
Conds_lim les_conditions_limites_
Ref_Champ_Inc mon_inconnue
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 42 of file Zone_Cl_VEF.h.
Constructor & Destructor Documentation
Zone_Cl_VEF()
Zone_Cl_VEF::Zone_Cl_VEF ()
Definition at line 39 of file Zone_Cl_VEF.cpp.
{
~Zone_Cl_VEF()
Zone_Cl_VEF::~Zone_Cl_VEF ()
Definition at line 39 of file Zone_Cl_VEF.cpp.
{
Member Function Documentation
associer()
void Zone_Cl_VEF::associer (const Zone_VEF & la_zone_VEF)
etape de discretisation : dimensionnement des tableaux
Definition at line 86 of file Zone_Cl_VEF.cpp.
{
  int nb_faces_non_std = la_zone_VEF.nb_faces_non_std();
  const Elem_VEF& type_elem= la_zone_VEF.type_elem();
  int nb_fa7_elem = type_elem.nb_facette();
  {
    IntVect renum;
    la_zone_VEF.creer_tableau_faces(renum, ArrOfInt::NOCOPY_NOINIT);
    renum = -1;
// Marquer les faces non standard reelles (premieres faces dans la zone)
    int i;
    for (i = 0; i < nb_faces_non_std; i++)
      renum[i] = 0;
// Echange espace virtuel => marquer les faces virtuelles non standard
    renum.echange_espace_virtuel();
    MD_Vector md_vect;
    MD_Vector_tools::creer_md_vect_renum_auto(renum, md_vect);
    MD_Vector_tools::creer_tableau_distribue(md_vect, volumes_entrelaces_Cl_, Array_base::NOCOPY_NOINIT);
  }
  {
// Construction du descripteur pour le tableau des elements "Cl":
    MD_Vector md_vect;
    MD_Vector_tools::creer_md_vect_renum(la_zone_VEF.rang_elem_non_std(), md_vect);
// Creation de tableaux aux elements "Cl":
    normales_facettes_Cl_.resize(0, nb_fa7_elem, dimension);
    MD_Vector_tools::creer_tableau_distribue(md_vect, normales_facettes_Cl_, Array_base::NOCOPY_NOINIT);
    vecteur_face_facette_Cl_.resize(0, nb_fa7_elem, dimension, 2);
    MD_Vector_tools::creer_tableau_distribue(md_vect, vecteur_face_facette_Cl_, Array_base::NOCOPY_NOINIT);
    MD_Vector_tools::creer_tableau_distribue(md_vect, type_elem_Cl_, Array_base::NOCOPY_NOINIT);
  }
}
References MD_Vector_tools::creer_md_vect_renum(), MD_Vector_tools::creer_md_vect_renum_auto(), MD_Vector_tools::creer_tableau_distribue(), Zone_VF::creer_tableau_faces(), Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VEF::nb_faces_non_std(), Array_base::NOCOPY_NOINIT, normales_facettes_Cl_, Zone_VEF::rang_elem_non_std(), TRUSTTab< _TYPE_ >::resize(), Zone_VEF::type_elem(), type_elem(), type_elem_Cl_, vecteur_face_facette_Cl_, and volumes_entrelaces_Cl_.
Referenced by VEFPreP1B::zone_Cl_dis(), and VEF_discretisation::zone_Cl_dis().
completer()
void Zone_Cl_VEF::completer (const Zone_dis & une_zone_dis) override virtual
remplissage des tableaux
Implements Zone_Cl_dis_base.
Definition at line 124 of file Zone_Cl_VEF.cpp.
{
  modif_perio_fait_ =0;
  if (sub_type(Zone_VEF,une_zone_dis.valeur()))
    {
      const Zone_VEF& la_zone_VEF = ref_cast(Zone_VEF, une_zone_dis.valeur());
      remplir_type_elem_Cl(la_zone_VEF);
      remplir_volumes_entrelaces_Cl(la_zone_VEF);
      remplir_normales_facettes_Cl(la_zone_VEF);
    }
  else
    {
      Cerr << "Zone_Cl_VEF::completer() prend comme argument une Zone_VEF " << finl;
      exit();
    }
}
References Cerr, Process::exit(), finl, modif_perio_fait_, ref_cast, remplir_normales_facettes_Cl(), remplir_type_elem_Cl(), remplir_volumes_entrelaces_Cl(), sub_type, and Deriv_Zone_dis_base::valeur().
cree_instance()
Objet_U * Zone_Cl_VEF::cree_instance () static
Definition at line 39 of file Zone_Cl_VEF.cpp.
{
duplique()
int Zone_Cl_VEF::duplique () const override virtual
Implements Objet_U.
Definition at line 39 of file Zone_Cl_VEF.cpp.
{
get_info()
const Type_info * Zone_Cl_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 39 of file Zone_Cl_VEF.cpp.
{
imposer_cond_lim()
void Zone_Cl_VEF::imposer_cond_lim (Champ_Inc & ch, double temps) override virtual
Impose les conditions aux limites a la valeur temporelle "temps" du
Champ_Inc.
Implements Zone_Cl_dis_base.
Definition at line 377 of file Zone_Cl_VEF.cpp.
{
  DoubleTab& ch_tab = ch->valeurs(temps);
  if (sub_type(Champ_P0_VEF,ch.valeur()))
    {
      ;
    }
  else if (sub_type(Champ_P1NC,ch.valeur()) || sub_type(Champ_Q1NC,ch.valeur()))
    {
      int nb_comp;
      if (sub_type(Champ_P1NC,ch.valeur()))
        {
          const Champ_P1NC& chnc = ref_cast(Champ_P1NC,ch.valeur());
          nb_comp = chnc.nb_comp();
          int ndeb,nfin,num_face,ncomp;
          for(int i=0; i<nb_cond_lim(); i++)
            {
              const Cond_lim_base& la_cl = les_conditions_limites(i).valeur();
              if (sub_type(Periodique,la_cl))
                {
// On fait en sorte que le champ ait la meme valeur
// sur deux faces de periodicite qui sont en face l'une de l'autre
                  const Periodique& la_cl_perio = ref_cast(Periodique,la_cl);
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  int voisine;
                  double moy;
                  for (num_face=ndeb; num_face<nfin; num_face++)
                    {
                      voisine = la_cl_perio.face_associee(num_face-ndeb) + ndeb;
                      if (nb_comp == 1)
{
                          if ( ch_tab[num_face] != ch_tab[voisine] )
{
                              moy = 0.5*(ch_tab[num_face] + ch_tab[voisine]);
                              ch_tab[num_face] = moy;
                              ch_tab[voisine] = moy;
                            }
                        }
                      else
{
                          for (ncomp=0; ncomp<nb_comp; ncomp++)
                            if ( ch_tab(num_face,ncomp) != ch_tab(voisine,ncomp) )
{
                                moy = 0.5*(ch_tab(num_face,ncomp) + ch_tab(voisine,ncomp));
                                ch_tab(num_face,ncomp) = moy;
                                ch_tab(voisine,ncomp) = moy;
                              }
                        }
                    }
                }
              else if ( (sub_type(Symetrie,la_cl) ) &&
                        (ch->nature_du_champ()==vectoriel) )
                {
                  const Zone_VEF& zvef = chnc.zone_vef();
                  const DoubleTab& face_normales = zvef.face_normales();
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  if (nb_comp == dimension)
                    {
                      for (num_face=ndeb; num_face<nfin; num_face++)
{
                          double face_n, surf=0, flux=0;
                          for (ncomp=0; ncomp<nb_comp; ncomp++)
{
                              face_n = face_normales(num_face,ncomp);
                              flux += ch_tab(num_face,ncomp)*face_n;
                              surf += face_n*face_n;
                            }
// flux /= surf; // Fixed bug: Arithmetic exception
                          if (std::fabs(surf)>=DMINFLOAT) flux /= surf;
                          for (ncomp=0; ncomp<nb_comp; ncomp++)
                            ch_tab(num_face,ncomp) -= flux*face_normales(num_face,ncomp);
                        }
                    }
                }
              else if ( sub_type(Dirichlet_entree_fluide,la_cl) )
                {
                  const Dirichlet_entree_fluide& la_cl_diri = ref_cast(Dirichlet_entree_fluide,la_cl);
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  if (nb_comp == 1)
                    for (num_face=ndeb; num_face<nfin; num_face++)
                      ch_tab[num_face] = la_cl_diri.val_imp_au_temps(temps,num_face-ndeb);
                  else
                    {
                      for (ncomp=0; ncomp<nb_comp; ncomp++)
                        for (num_face=ndeb; num_face<nfin; num_face++)
                          ch_tab(num_face,ncomp) =la_cl_diri.val_imp_au_temps(temps,num_face-ndeb,ncomp);
                    }
                }
              else if ( sub_type(Scalaire_impose_paroi,la_cl) )
                {
                  const Scalaire_impose_paroi& la_cl_diri = ref_cast(Scalaire_impose_paroi,la_cl);
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  if (nb_comp == 1)
                    for (num_face=ndeb; num_face<nfin; num_face++)
                      {
                        ch_tab[num_face] = la_cl_diri.val_imp_au_temps(temps,num_face-ndeb);
                      }
                  else
                    {
                      for (ncomp=0; ncomp<nb_comp; ncomp++)
                        for (num_face=ndeb; num_face<nfin; num_face++)
                          ch_tab(num_face,ncomp) =la_cl_diri.val_imp_au_temps(temps,num_face-ndeb,ncomp);
                    }
                }
              else if ( (sub_type(Dirichlet_paroi_fixe,la_cl) ) &&
                        (ch->nature_du_champ()==multi_scalaire) )
                {
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  if (nb_comp == 1)
                    for (num_face=ndeb; num_face<nfin; num_face++)
                      ch_tab[num_face] = 0;
                  else
                    {
                      for (ncomp=0; ncomp<nb_comp; ncomp++)
                        for (num_face=ndeb; num_face<nfin; num_face++)
{
                            ch_tab(num_face,0) = 0;
                            ch_tab(num_face,1) = 0;
                          }
                    }
                }
              else if ( sub_type(Dirichlet_paroi_fixe,la_cl) )
                {
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  if (nb_comp == 1)
                    for (num_face=ndeb; num_face<nfin; num_face++)
                      ch_tab[num_face] = 0;
                  else
                    {
                      for (ncomp=0; ncomp<nb_comp; ncomp++)
                        for (num_face=ndeb; num_face<nfin; num_face++)
                          ch_tab(num_face,ncomp) = 0;
                    }
                }
              else if ( sub_type(Dirichlet_paroi_defilante,la_cl) )
                {
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  const Dirichlet_paroi_defilante& la_cl_diri=ref_cast(Dirichlet_paroi_defilante,la_cl);
                  const DoubleTab& face_normales = chnc.zone_vef().face_normales();
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  if (nb_comp != dimension)
                    {
                      Cerr << "Cas non prevu dans Zone_Cl_VEF::imposer_cond_lim." << finl;
                      exit();
                    }
                  else
                    {
                      for (num_face=ndeb; num_face<nfin; num_face++)
{
                          double surf=0, flux=0;
                          for (ncomp=0; ncomp<nb_comp; ncomp++)
{
                              double face_n = face_normales(num_face,ncomp);
                              flux += la_cl_diri.val_imp_au_temps(temps,num_face-ndeb, ncomp)*face_n;
                              surf += face_n*face_n;
                            }
// flux /= surf; // Fixed bug: Arithmetic exception
                          if (std::fabs(surf)>=DMINFLOAT) flux /= surf;
                          for (ncomp=0; ncomp<nb_comp; ncomp++)
                            ch_tab(num_face,ncomp) = la_cl_diri.val_imp_au_temps(temps,num_face-ndeb, ncomp) - flux * face_normales(num_face,ncomp);
                        }
                    }
                }
            }
        }
      else if (sub_type(Champ_Q1NC,ch.valeur()))
        {
          const Champ_Q1NC& chnc = ref_cast(Champ_Q1NC,ch.valeur());
          nb_comp = chnc.nb_comp();
          int ndeb,nfin,num_face,ncomp;
          for(int i=0; i<nb_cond_lim(); i++)
            {
              const Cond_lim_base& la_cl = les_conditions_limites(i).valeur();
              if (sub_type(Periodique,la_cl))
                {
// On fait en sorte que le champ ait la meme valeur
// sur deux faces de periodicite qui sont en face l'une de l'autre
                  const Periodique& la_cl_perio = ref_cast(Periodique,la_cl);
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  int voisine;
                  double moy;
                  for (num_face=ndeb; num_face<nfin; num_face++)
                    {
                      voisine = la_cl_perio.face_associee(num_face-ndeb) + ndeb;
                      if (nb_comp == 1)
{
                          if ( ch_tab[num_face] != ch_tab[voisine] )
{
                              moy = 0.5*(ch_tab[num_face] + ch_tab[voisine]);
                              ch_tab[num_face] = moy;
                              ch_tab[voisine] = moy;
                            }
                        }
                      else
{
                          for (ncomp=0; ncomp<nb_comp; ncomp++)
                            if ( ch_tab(num_face,ncomp) != ch_tab(voisine,ncomp) )
{
                                moy = 0.5*(ch_tab(num_face,ncomp) + ch_tab(voisine,ncomp));
                                ch_tab(num_face,ncomp) = moy;
                                ch_tab(voisine,ncomp) = moy;
                              }
                        }
                    }
                }
              else if ( (sub_type(Symetrie,la_cl) ) &&
                        (ch->nature_du_champ()==vectoriel) )
                {
                  const Zone_VEF& zvef = chnc.zone_vef();
                  const DoubleTab& face_normales = zvef.face_normales();
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  if (nb_comp == dimension)
                    {
                      for (num_face=ndeb; num_face<nfin; num_face++)
{
                          double face_n, surf=0, flux=0;
                          for (ncomp=0; ncomp<nb_comp; ncomp++)
{
                              face_n = face_normales(num_face,ncomp);
                              flux += ch_tab(num_face,ncomp)*face_n;
                              surf += face_n*face_n;
                            }
// flux /= surf; // Fixed bug: Arithmetic exception
                          if (std::fabs(surf)>=DMINFLOAT) flux /= surf;
                          for (ncomp=0; ncomp<nb_comp; ncomp++)
                            ch_tab(num_face,ncomp) -= flux*face_normales(num_face,ncomp);
                        }
                    }
                }
              else if ( sub_type(Dirichlet_entree_fluide,la_cl) )
                {
                  const Dirichlet_entree_fluide& la_cl_diri = ref_cast(Dirichlet_entree_fluide,la_cl);
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  if (nb_comp == 1)
                    for (num_face=ndeb; num_face<nfin; num_face++)
                      ch_tab[num_face] = la_cl_diri.val_imp_au_temps(temps,num_face-ndeb);
                  else
                    {
                      for (ncomp=0; ncomp<nb_comp; ncomp++)
                        for (num_face=ndeb; num_face<nfin; num_face++)
                          ch_tab(num_face,ncomp) =la_cl_diri.val_imp_au_temps(temps,num_face-ndeb,ncomp);
                    }
                }
              else if ( sub_type(Scalaire_impose_paroi,la_cl) )
                {
                  const Scalaire_impose_paroi& la_cl_diri = ref_cast(Scalaire_impose_paroi,la_cl);
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  if (nb_comp == 1)
                    for (num_face=ndeb; num_face<nfin; num_face++)
                      {
                        ch_tab[num_face] = la_cl_diri.val_imp_au_temps(temps,num_face-ndeb);
                      }
                  else
                    {
                      for (ncomp=0; ncomp<nb_comp; ncomp++)
                        for (num_face=ndeb; num_face<nfin; num_face++)
                          ch_tab(num_face,ncomp) =la_cl_diri.val_imp_au_temps(temps,num_face-ndeb,ncomp);
                    }
                }
              else if ( sub_type(Dirichlet_paroi_fixe,la_cl) )
                {
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  if (nb_comp == 1)
                    for (num_face=ndeb; num_face<nfin; num_face++)
                      ch_tab[num_face] = 0;
                  else
                    {
                      for (ncomp=0; ncomp<nb_comp; ncomp++)
                        for (num_face=ndeb; num_face<nfin; num_face++)
                          ch_tab(num_face,ncomp) = 0;
                    }
                }
              else if ( sub_type(Dirichlet_paroi_defilante,la_cl) )
                {
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  const Dirichlet_paroi_defilante& la_cl_diri=ref_cast(Dirichlet_paroi_defilante,la_cl);
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  if (nb_comp == 1)
                    for (num_face=ndeb; num_face<nfin; num_face++)
                      ch_tab[num_face] = la_cl_diri.val_imp_au_temps(temps,num_face-ndeb);
                  else
                    {
                      for (ncomp=0; ncomp<nb_comp; ncomp++)
                        for (num_face=ndeb; num_face<nfin; num_face++)
                          ch_tab(num_face,ncomp) =la_cl_diri.val_imp_au_temps(temps,num_face-ndeb, ncomp);
                    }
                }
            }
        }
    }
  else
    {
      Cerr << "Le type de Champ_Inc " << ch->que_suis_je() << " n'est pas prevu en VEF\n" << finl;
      exit();
    }
  ch_tab.echange_espace_virtuel();
// Debog::verifier("Zone_Cl_VEF::imposer_cond_lim ch_tab",ch_tab);
}
References Cerr, Objet_U::dimension, DMINFLOAT, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), Periodique::face_associee(), Zone_VEF::face_normales(), finl, Cond_lim_base::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), multi_scalaire, Field_base::nb_comp(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), ref_cast, sub_type, Dirichlet::val_imp_au_temps(), Deriv_Champ_Inc_base::valeur(), Champ_Inc::valeurs(), vectoriel, Champ_P1NC::zone_vef(), and Champ_Q1NC::zone_vef().
Referenced by Zone_Cl_VEFP1B::imposer_cond_lim().
info()
const Type_info * Zone_Cl_VEF::info () static
Definition at line 39 of file Zone_Cl_VEF.cpp.
{
initialiser()
int Zone_Cl_VEF::initialiser (double temps) override virtual
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Returns
int
Signification: 1 si OK, 0 sinon
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 728 of file Zone_Cl_VEF.cpp.
{
  Zone_Cl_dis_base::initialiser(temps);
  if (nb_bord_periodicite()>0)
    {
      if (modif_perio_fait_ == 0)
        {
          Cerr <<"modification de la Zone_Cl_VEF pour periodicite" << finl;
          const Zone_VEF& la_zone_VEF = ref_cast(Zone_VEF,zone_dis().valeur());
          const DoubleVect& volumes_entrelaces = la_zone_VEF.volumes_entrelaces();
          remplir_volumes_entrelaces_Cl(la_zone_VEF);
          for(int i=0; i<les_conditions_limites_.size(); i++)
            {
              const Cond_lim_base& la_cl=les_conditions_limites_[i].valeur();
              if (sub_type(Periodique,la_cl) )
                {
                  const Periodique& la_cl_perio = ref_cast(Periodique,la_cl);
                  const Front_VF& le_bord= la_zone_VEF.front_VF(i);
                  int premiere=le_bord.num_premiere_face();
                  int derniere=premiere+le_bord.nb_faces();
                  IntVect fait(le_bord.nb_faces());
                  fait = 0;
                  int ind_fac_loc;
                  for(int j=premiere; j<derniere; j++)
                    {
                      ind_fac_loc = j-premiere;
                      if (fait[ind_fac_loc]== 0)
{
                          int fac_associee = la_cl_perio.face_associee(j-premiere)+premiere;
                          if (volumes_entrelaces_Cl_[j] != volumes_entrelaces[j])
                            volumes_entrelaces_Cl_[fac_associee] = volumes_entrelaces_Cl_[j];
                          else
                            volumes_entrelaces_Cl_[j] = volumes_entrelaces_Cl_[fac_associee];
                          fait[ind_fac_loc] = 1;
                          fait[fac_associee-premiere] = 1;
                        }
                    }
                }
            }
          modif_perio_fait_ = 1;
        }
    }
  return 1;
}
References Cerr, Periodique::face_associee(), finl, Zone_VF::front_VF(), Zone_Cl_dis_base::initialiser(), Zone_Cl_dis_base::les_conditions_limites_, modif_perio_fait_, nb_bord_periodicite(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, remplir_volumes_entrelaces_Cl(), vect_impl::size(), sub_type, valeur(), Zone_VF::volumes_entrelaces(), volumes_entrelaces_Cl_, and Zone_Cl_dis_base::zone_dis().
nb_bord_periodicite()
int Zone_Cl_VEF::nb_bord_periodicite () const
Definition at line 717 of file Zone_Cl_VEF.cpp.
{
  int compteur=0;
  for(int cl=0; cl<les_conditions_limites_.size(); cl++)
    {
      if (sub_type(Periodique,les_conditions_limites_[cl].valeur()))
        compteur++;
    }
  return compteur;
}
References compteur, Zone_Cl_dis_base::les_conditions_limites_, vect_impl::size(), sub_type, and valeur().
Referenced by initialiser().
nb_faces_sortie_libre()
int Zone_Cl_VEF::nb_faces_sortie_libre () const
Definition at line 703 of file Zone_Cl_VEF.cpp.
{
  int compteur=0;
  for(int cl=0; cl<les_conditions_limites_.size(); cl++)
    {
      if(sub_type(Neumann_sortie_libre, les_conditions_limites_[cl].valeur()))
        {
          const Front_VF& le_bord=ref_cast(Front_VF,les_conditions_limites_[cl]->frontiere_dis());
          compteur+=le_bord.nb_faces();
        }
    }
  return compteur;
}
References compteur, Zone_Cl_dis_base::les_conditions_limites_, Front_VF::nb_faces(), ref_cast, vect_impl::size(), sub_type, and valeur().
normales_facettes_Cl() [1/4]
DoubleTab & Zone_Cl_VEF::normales_facettes_Cl () inline
Definition at line 123 of file Zone_Cl_VEF.h.
{
  return normales_facettes_Cl_;
}
References normales_facettes_Cl_.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_VEF_Face::remplir_fluent(), and remplir_normales_facettes_Cl().
normales_facettes_Cl() [2/4]
const DoubleTab & Zone_Cl_VEF::normales_facettes_Cl () const inline
Definition at line 128 of file Zone_Cl_VEF.h.
{
  return normales_facettes_Cl_;
}
References normales_facettes_Cl_.
normales_facettes_Cl() [3/4]
double & Zone_Cl_VEF::normales_facettes_Cl (int num_poly, int num_fa7, int ncomp) inline
Definition at line 153 of file Zone_Cl_VEF.h.
{
  return normales_facettes_Cl_(num_poly,num_fa7,ncomp);
}
References normales_facettes_Cl_.
normales_facettes_Cl() [4/4]
const double & Zone_Cl_VEF::normales_facettes_Cl (int num_poly, int num_fa7, int ncomp) const inline
Definition at line 146 of file Zone_Cl_VEF.h.
{
  return normales_facettes_Cl_(num_poly,num_fa7,ncomp);
}
References normales_facettes_Cl_.
printOn()
Sortie & Zone_Cl_VEF::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 61 of file Zone_Cl_VEF.cpp.
{
  os << volumes_entrelaces_Cl_;
  os << normales_facettes_Cl_;
  os << type_elem_Cl_;
  return os;
}
References normales_facettes_Cl_, type_elem_Cl_, and volumes_entrelaces_Cl_.
Referenced by Zone_Cl_VEFP1B::printOn().
readOn()
Entree & Zone_Cl_VEF::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 72 of file Zone_Cl_VEF.cpp.
{
  return Zone_Cl_dis_base::readOn(is) ;
}
References Zone_Cl_dis_base::readOn().
Referenced by Zone_Cl_VEFP1B::readOn().
remplir_normales_facettes_Cl()
void Zone_Cl_VEF::remplir_normales_facettes_Cl (const Zone_VEF & la_zone_VEF)
appele par completer() : remplissage de normales_facettes_Cl_
et vecteur_face_caette_Cl_
CHANGER LE NOM
Definition at line 214 of file Zone_Cl_VEF.cpp.
{
  const Zone& z = la_zone_VEF.zone();
  const Domaine& dom = z.domaine();
  const DoubleTab& les_coords =dom.coord_sommets();
  const IntTab& les_Polys = z.les_elems() ;
  const Elem_VEF& elemvef = la_zone_VEF.type_elem();
  const IntVect& rang_elem=la_zone_VEF.rang_elem_non_std();
  const IntTab& elem_faces = la_zone_VEF.elem_faces();
  const DoubleTab& xv=la_zone_VEF.xv();
  const IntTab& KEL=elemvef.valeur().KEL();
  int num_elem, fa7;
  int isom,ncomp;
  int idirichlet=-1,n1=-1,n2=-1,n3=-1;
  int nb_elem = z.nb_elem();
  int nsom = z.nb_som_elem();
  int nfa7 = elemvef.nb_facette();
// int nb_som_facette = zone().type_elem().nb_som_face();
// if (sub_type(Hexaedre_VEF,zone().type_elem().valeur())) { nb_som_facette--; }
  int nb_som_facette=dimension;
  IntVect num_som(nsom);
  DoubleTab x(nsom,dimension);
  DoubleVect xg(dimension);
  DoubleVect xj0(dimension);
  DoubleVect u(dimension);
  DoubleVect v(dimension);
// Calcul des valeurs des normales aux facettes modifiees par les C.L:
  for (int elem=0; elem<nb_elem; elem++)
    {
      if (rang_elem(elem)!= -1)
        {
          num_elem = rang_elem(elem);
// numero des sommets du polyedre:
          for (isom = 0; isom<nsom; isom++)
            num_som[isom] = les_Polys(elem,isom);
// Calcul des coordonnees des sommets du polyedre:
          for (isom = 0; isom<nsom; isom++)
            for (ncomp =0; ncomp<dimension; ncomp++)
              x(isom,ncomp) = les_coords(num_som[isom],ncomp);
// Calcul des coordonnees du point G en fonction du type du polyedre
// idirichlet= nb de faces de dirichlet de l'elem
// pour triangle si idirichlet=2, n1=sommet confondu avec G
// pour quadrangle se reporter a Quadri_VEF.cpp
          elemvef.calcul_xg(xg,x,type_elem_Cl_[num_elem],
                            idirichlet,n1,n2,n3);
// Calcul des valeurs du tableau normales_facettes_Cl:
          for (fa7=0; fa7<nfa7; fa7++)
            {
              elemvef.creer_normales_facettes_Cl(normales_facettes_Cl(),fa7, num_elem,x,xg,z);
// Correction des valeurs du tableau normales_facettes_Cl:
              elemvef.modif_normales_facettes_Cl(normales_facettes_Cl(),fa7,num_elem,idirichlet,n1,n2,n3);
              int num1= elem_faces(elem,KEL(0,fa7));
              int num2= elem_faces(elem,KEL(1,fa7));
              for (int dir=0; dir<dimension; dir++)
                {
                  double coord_centre_fa7= xg(dir);
                  for (int num_som_fa7=0; num_som_fa7<nb_som_facette-1; num_som_fa7++)
                    {
                      int isom_loc = KEL(num_som_fa7+2,fa7);
                      int isom_glob = les_Polys(elem,isom_loc);
                      coord_centre_fa7 += les_coords(isom_glob,dir);
                    }
                  coord_centre_fa7 /= nb_som_facette;
                  vecteur_face_facette_Cl_(num_elem,fa7,dir,0)=coord_centre_fa7-xv(num1,dir);
                  vecteur_face_facette_Cl_(num_elem,fa7,dir,1)=coord_centre_fa7-xv(num2,dir);
                }
            }
        }
    }
  normales_facettes_Cl_.echange_espace_virtuel();
  vecteur_face_facette_Cl_.echange_espace_virtuel();
}
References Elem_VEF::calcul_xg(), Domaine::coord_sommets(), Elem_VEF::creer_normales_facettes_Cl(), Objet_U::dimension, Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), Elem_VEF_base::KEL(), Zone::les_elems(), Elem_VEF::modif_normales_facettes_Cl(), Zone::nb_elem(), Elem_VEF::nb_facette(), Zone::nb_som_elem(), normales_facettes_Cl(), normales_facettes_Cl_, Zone_VEF::rang_elem_non_std(), Zone_VEF::type_elem(), type_elem_Cl_, Deriv_Elem_VEF_base::valeur(), vecteur_face_facette_Cl_, Zone_VF::xv(), and Zone_dis_base::zone().
Referenced by completer().
remplir_type_elem_Cl()
void Zone_Cl_VEF::remplir_type_elem_Cl (const Zone_VEF & la_zone_VEF) protected
appele par remplir_volumes_entrelaces_Cl() : remplissage de type_elem_Cl_
< dans Elem_geom
Definition at line 324 of file Zone_Cl_VEF.cpp.
{
  const Zone& z = la_zone_VEF.zone();
  int nfac= z.type_elem().nb_faces();   //!< dans Elem_geom
  const IntTab& elem_faces = la_zone_VEF.elem_faces();
  const IntTab& face_voisins = la_zone_VEF.face_voisins();
  const IntVect& rang_elem = la_zone_VEF.rang_elem_non_std();
  type_elem_Cl_ = 0;
  int elem, num_elem;
  for(int i=0; i<les_conditions_limites_.size(); i++)
    {
      Cond_lim_base& la_cl=les_conditions_limites_[i].valeur();
      if ( (sub_type(Dirichlet,la_cl))
           ||
           (sub_type(Dirichlet_homogene,la_cl))
         )
        {
          const Front_VF& le_bord= la_zone_VEF.front_VF(i);
          int premiere = le_bord.num_premiere_face();
          int derniere = premiere+le_bord.nb_faces();
          for(int j=premiere; j<derniere; j++)
            {
              elem=face_voisins(j,0);
              int numero1,numero2 =-1;
              for(numero1=0; numero1<nfac; numero1++)
                if(elem_faces(elem,numero1) == j)
                  numero2 = numero1;
              if(numero2 == -1)
                Cerr << "Zone_Cl_VEF::creer_type_elem_Cl() PAS POSSIBLE!! " << finl;
              num_elem = rang_elem(elem);
              assert(num_elem!=-1);
              if (sub_type(Tri_VEF,la_zone_VEF.type_elem().valeur()) || sub_type(Tetra_VEF,la_zone_VEF.type_elem().valeur()))
                type_elem_Cl_[num_elem]+= Deux_Puissance((int)(nfac-1-numero2));
              else if (sub_type(Quadri_VEF,la_zone_VEF.type_elem().valeur()) || sub_type(Hexa_VEF,la_zone_VEF.type_elem().valeur()) )
                type_elem_Cl_[num_elem]+= trois_puissance((int)(nfac-1-numero2));
              else
                {
                  Cerr << "erreur dans Zone_Cl_VEF::remplir_type_elem_Cl mauvais typage d'element " << finl;
                  exit();
                }
            }
        }
    }
  type_elem_Cl_.echange_espace_virtuel();
}
References Cerr, Deux_Puissance(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), Process::exit(), Zone_VF::face_voisins(), finl, Zone_VF::front_VF(), Zone_Cl_dis_base::les_conditions_limites_, Front_VF::nb_faces(), Elem_geom::nb_faces(), Front_VF::num_premiere_face(), Zone_VEF::rang_elem_non_std(), vect_impl::size(), sub_type, trois_puissance(), Zone::type_elem(), Zone_VEF::type_elem(), type_elem_Cl_, Deriv_Elem_VEF_base::valeur(), and Zone_dis_base::zone().
Referenced by completer().
remplir_vecteur_face_facette_Cl()
void Zone_Cl_VEF::remplir_vecteur_face_facette_Cl (const Zone_VEF &)
remplir_volumes_entrelaces_Cl()
void Zone_Cl_VEF::remplir_volumes_entrelaces_Cl (const Zone_VEF & la_zone_VEF) virtual
appele par completer() : remplissage de type_elem_Cl_ et
volumes_entrelaces_Cl_
Reimplemented in Zone_Cl_VEFP1B.
Definition at line 144 of file Zone_Cl_VEF.cpp.
{
  const DoubleVect& volumes_entrelaces = la_zone_VEF.volumes_entrelaces();
  const IntVect& rang_elem = la_zone_VEF.rang_elem_non_std();
// Initialisation du tableau volumes_entrelaces_Cl
// a priori les faces non standard ne sont pas touchees par les C.L
  for (int i=0; i<la_zone_VEF.nb_faces_non_std(); i++)
    volumes_entrelaces_Cl_[i] = volumes_entrelaces(i);
// Calcul des valeurs des volumes entrelaces modifiees par les C.L:
  int nb_poly_tot = la_zone_VEF.zone().nb_elem_tot();
  ArrOfInt poly_fait(nb_poly_tot);
  poly_fait = 0;
  for(int i=0; i<les_conditions_limites_.size(); i++)
    {
      const Cond_lim_base& la_cl=les_conditions_limites_[i].valeur();
      if ( (sub_type(Dirichlet,la_cl))
           ||
           (sub_type(Dirichlet_homogene,la_cl))
         )
        {
          const Front_VF& le_bord= la_zone_VEF.front_VF(i);
          const Frontiere& front=le_bord.frontiere();
          int premiere=le_bord.num_premiere_face();
          int derniere=premiere+le_bord.nb_faces();
          for(int j=premiere; j<derniere; j++)
            {
              volumes_entrelaces_Cl_[j] =0;
              int elem=la_zone_VEF.face_voisins(j,0);
              int n_poly=rang_elem(elem);
              if(!poly_fait[n_poly])
                {
                  poly_fait[n_poly]=1;
                  const Elem_VEF& type_elem= la_zone_VEF.type_elem();
                  type_elem.modif_volumes_entrelaces(j,elem,la_zone_VEF,
                                                     volumes_entrelaces_Cl(),
                                                     type_elem_Cl(n_poly)) ;
                }
            }
// faces virtuelles de bord :
          const ArrOfInt& faces_virt = front.get_faces_virt();
          int nb_faces_virt = faces_virt.size_array();
          for (int ind_face=0; ind_face<nb_faces_virt; ind_face++)
            {
              int num_face = faces_virt[ind_face];
              int elem=la_zone_VEF.face_voisins(num_face,0);
              int n_poly=rang_elem(elem);
              if(n_poly!=-1)
                {
                  if(!poly_fait[n_poly])
                    {
                      poly_fait[n_poly]=1;
                      const Elem_VEF& type_elem= la_zone_VEF.type_elem();
                      type_elem.modif_volumes_entrelaces_faces_joints(num_face,elem,la_zone_VEF,
                                                                      volumes_entrelaces_Cl(),
                                                                      type_elem_Cl(n_poly)) ;
                    }
                }
            }
        }
    }
}
References Zone_VF::face_voisins(), Zone_VF::front_VF(), Frontiere_dis_base::frontiere(), Frontiere::get_faces_virt(), Zone_Cl_dis_base::les_conditions_limites_, Zone::nb_elem_tot(), Front_VF::nb_faces(), Zone_VEF::nb_faces_non_std(), Front_VF::num_premiere_face(), Zone_VEF::rang_elem_non_std(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), sub_type, Zone_VEF::type_elem(), type_elem(), type_elem_Cl(), Zone_VF::volumes_entrelaces(), volumes_entrelaces_Cl(), volumes_entrelaces_Cl_, and Zone_dis_base::zone().
Referenced by completer(), initialiser(), and Zone_Cl_VEFP1B::remplir_volumes_entrelaces_Cl().
self_cast() [1/2]
const Zone_Cl_VEF & Zone_Cl_VEF::self_cast (const Objet_U & r) static
Definition at line 39 of file Zone_Cl_VEF.cpp.
{
self_cast() [2/2]
Zone_Cl_VEF & Zone_Cl_VEF::self_cast (Objet_U & r) static
Definition at line 39 of file Zone_Cl_VEF.cpp.
{
taille_memoire()
unsigned Zone_Cl_VEF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 39 of file Zone_Cl_VEF.cpp.
{
type_elem_Cl()
int Zone_Cl_VEF::type_elem_Cl (int i) const inline
Definition at line 160 of file Zone_Cl_VEF.h.
{
  return type_elem_Cl_[i];
}
References type_elem_Cl_.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Grad_VEF_P1B_Face::calculer_coef_som(), calculer_coef_som(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_VEF_Face::remplir_fluent(), and remplir_volumes_entrelaces_Cl().
vecteur_face_facette_Cl() [1/2]
DoubleTab & Zone_Cl_VEF::vecteur_face_facette_Cl () inline
Definition at line 133 of file Zone_Cl_VEF.h.
{
  return vecteur_face_facette_Cl_;
}
References vecteur_face_facette_Cl_.
Referenced by Op_Conv_VEF_Face::ajouter(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), and Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre().
vecteur_face_facette_Cl() [2/2]
const DoubleTab & Zone_Cl_VEF::vecteur_face_facette_Cl () const inline
Definition at line 138 of file Zone_Cl_VEF.h.
{
  return vecteur_face_facette_Cl_;
}
References vecteur_face_facette_Cl_.
volumes_entrelaces_Cl() [1/4]
DoubleVect & Zone_Cl_VEF::volumes_entrelaces_Cl () inline
Definition at line 103 of file Zone_Cl_VEF.h.
{
  return volumes_entrelaces_Cl_;
}
References volumes_entrelaces_Cl_.
Referenced by Source_Generique_VEF::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Masse_VEF_P1NC::appliquer_impl(), Assembleur_P_VEF::assembler(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_pour_post(), Evaluateur_Source_VEF_Face::completer(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), remplir_volumes_entrelaces_Cl(), and Zone_Cl_VEFP1B::remplir_volumes_entrelaces_Cl().
volumes_entrelaces_Cl() [2/4]
const DoubleVect & Zone_Cl_VEF::volumes_entrelaces_Cl () const inline
Definition at line 108 of file Zone_Cl_VEF.h.
{
  return volumes_entrelaces_Cl_;
}
References volumes_entrelaces_Cl_.
volumes_entrelaces_Cl() [3/4]
double & Zone_Cl_VEF::volumes_entrelaces_Cl (int i) inline
Definition at line 118 of file Zone_Cl_VEF.h.
{
  return volumes_entrelaces_Cl_[i];
}
References volumes_entrelaces_Cl_.
volumes_entrelaces_Cl() [4/4]
const double & Zone_Cl_VEF::volumes_entrelaces_Cl (int i) const inline
Definition at line 113 of file Zone_Cl_VEF.h.
{
  return volumes_entrelaces_Cl_[i];
}
References volumes_entrelaces_Cl_.
zone_VEF() [1/2]
Zone_VEF & Zone_Cl_VEF::zone_VEF ()
Definition at line 780 of file Zone_Cl_VEF.cpp.
{
  return ref_cast(Zone_VEF, zone_dis().valeur());
}
References ref_cast, valeur(), and Zone_Cl_dis_base::zone_dis().
Referenced by Champ_P1NC::calcul_duidxj_paroi(), Champ_P1NC::calcul_gradient(), and Champ_P1NC::calcul_S_barre().
zone_VEF() [2/2]
const Zone_VEF & Zone_Cl_VEF::zone_VEF () const
Definition at line 785 of file Zone_Cl_VEF.cpp.
{
  return ref_cast(Zone_VEF, zone_dis().valeur());
}
References ref_cast, valeur(), and Zone_Cl_dis_base::zone_dis().
Member Data Documentation
info_obj
const Type_info Zone_Cl_VEF::info_obj static
Definition at line 45 of file Zone_Cl_VEF.h.
modif_perio_fait_
int Zone_Cl_VEF::modif_perio_fait_ protected
Definition at line 88 of file Zone_Cl_VEF.h.
Referenced by completer(), and initialiser().
normales_facettes_Cl_
DoubleTab Zone_Cl_VEF::normales_facettes_Cl_ protected
Definition at line 85 of file Zone_Cl_VEF.h.
Referenced by associer(), normales_facettes_Cl(), printOn(), and remplir_normales_facettes_Cl().
type_elem_Cl_
IntVect Zone_Cl_VEF::type_elem_Cl_ protected
Definition at line 87 of file Zone_Cl_VEF.h.
Referenced by associer(), printOn(), remplir_normales_facettes_Cl(), remplir_type_elem_Cl(), and type_elem_Cl().
vecteur_face_facette_Cl_
DoubleTab Zone_Cl_VEF::vecteur_face_facette_Cl_ protected
Definition at line 86 of file Zone_Cl_VEF.h.
Referenced by associer(), remplir_normales_facettes_Cl(), and vecteur_face_facette_Cl().
volumes_entrelaces_Cl_
DoubleVect Zone_Cl_VEF::volumes_entrelaces_Cl_ protected
Definition at line 84 of file Zone_Cl_VEF.h.
Referenced by associer(), initialiser(), printOn(), remplir_volumes_entrelaces_Cl(), and volumes_entrelaces_Cl().
The documentation for this class was generated from the following files:
src/VEF/Zones/Zone_Cl_VEF.h
src/VEF/Zones/Zone_Cl_VEF.cpp