TRUST: Constante Class Reference
Constante Class Reference
#include <Constante.h>
Public Member Functions
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Constante ()
~Constante ()
Constante (const Constante &v)
void nommer (const Nom &name)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
double getValue ()
const double & getValue () const
void setValue (double x)
int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Constante & self_cast (Objet_U &)
static const Constante & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture sur un flot de sortie
Ecrit la valeur de la constante.
virtual Entree & readOn (Entree &)
Lit la valeur de la constante.
Private Attributes
Nom nom_
double value
Detailed Description
Definition at line 37 of file Constante.h.
Constructor & Destructor Documentation
Constante::Constante () [inline]
Definition at line 42 of file Constante.h.
References nom_, and value.
  {
    value = 0.;
    nom_ = "neant";
  }
Constante::~Constante () [inline]
Definition at line 47 of file Constante.h.
  {
  }
Constante::Constante (const Constante & v) [inline]
Definition at line 50 of file Constante.h.
References nom_, and value.
                               : Objet_U(v)
  {
    value =v.value;
    nom_ = v.nom_;
  }
Member Function Documentation
Objet_U * Constante::cree_instance () [static]
Definition at line 24 of file Constante.cpp.
int Constante::duplique () const [virtual]
Implements Objet_U.
Definition at line 24 of file Constante.cpp.
const Type_info * Constante::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 24 of file Constante.cpp.
double Constante::getValue () [inline]
Definition at line 63 of file Constante.h.
References value.
  {
    return value;
  }
const double& Constante::getValue () const [inline]
Definition at line 67 of file Constante.h.
References value.
  {
    return value;
  }
const Type_info * Constante::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 24 of file Constante.cpp.
const Nom& Constante::le_nom () const [inline, virtual]
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Returns:
Nom&
Signification: le nom de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 59 of file Constante.h.
References nom_.
Referenced by Parser::searchCst().
  {
    return nom_;
  }
void Constante::nommer (const Nom &) [inline, virtual]
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
Reimplemented from Objet_U.
Definition at line 55 of file Constante.h.
References nom_.
Referenced by Parser::init_parser().
  {
    nom_ = name ;
  }
Sortie & Constante::printOn (Sortie & os) const [protected, virtual]
Ecriture sur un flot de sortie
Ecrit la valeur de la constante.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 41 of file Constante.cpp.
References value.
{
  os << value;
  return os;
}
Entree & Constante::readOn (Entree & is) [protected, virtual]
Lit la valeur de la constante.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 62 of file Constante.cpp.
References value.
Referenced by reprendre().
{
  is >> value;
  return is;
}
int Constante::reprendre (Entree &) [virtual]
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns:
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 68 of file Constante.cpp.
References readOn().
{
  readOn(is);
  return 1;
}
Constante & Constante::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Definition at line 24 of file Constante.cpp.
const Constante & Constante::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Definition at line 24 of file Constante.cpp.
void Constante::setValue (double x) [inline]
Definition at line 71 of file Constante.h.
References value.
Referenced by Parser::init_parser().
  {
    value = x;
  }
unsigned Constante::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 24 of file Constante.cpp.
Member Data Documentation
const Type_info Constante::info_obj [static]
Reimplemented from Objet_U.
Definition at line 39 of file Constante.h.
Nom Constante::nom_ [private]
Definition at line 78 of file Constante.h.
Referenced by Constante(), le_nom(), and nommer().
double Constante::value [private]
Definition at line 79 of file Constante.h.
Referenced by Constante(), getValue(), printOn(), readOn(), and setValue().
The documentation for this class was generated from the following files:
src/Kernel/Math/Constante.h
src/Kernel/Math/Constante.cpp