TRUST: Source_Echange_Th_VDF Class Reference
Source_Echange_Th_VDF Class Reference
#include <Source_Echange_Th_VDF.h>
Public Member Functions
~Source_Echange_Th_VDF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Source_Echange_Th_VDF ()
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
void associer_pb (const Probleme_base &)
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Source_Echange_Th_VDF & self_cast (Objet_U &)
static const
Source_Echange_Th_VDF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Private Attributes
double h
Valeur du coefficient d'echange.
Ref_Probleme_base pb_voisin
Le probleme avec lequel se fait l'echange.
Detailed Description
Definition at line 42 of file Source_Echange_Th_VDF.h.
Constructor & Destructor Documentation
Source_Echange_Th_VDF::~Source_Echange_Th_VDF ()
Definition at line 30 of file Source_Echange_Th_VDF.cpp.
Source_Echange_Th_VDF::Source_Echange_Th_VDF () [inline]
Definition at line 48 of file Source_Echange_Th_VDF.h.
    : Terme_Source_VDF_base(It_Sou_VDF_Elem(Eval_Echange_Himp_VDF_Elem)()) {}
Member Function Documentation
void Source_Echange_Th_VDF::associer_pb (const Probleme_base & pb) [virtual]
Implements Source_base.
Definition at line 71 of file Source_Echange_Th_VDF.cpp.
References Eval_Echange_Himp_VDF_Elem::associer_champs(), Cerr, MorEqn::equation(), Iterateur_Source_VDF::evaluateur(), Process::exit(), finl, h, Equation_base::inconnue(), Terme_Source_VDF_base::iter, pb_voisin, REF, and sub_type.
{
// Associe les zones a l'iterateur et a l'evaluateur
  Eval_Echange_Himp_VDF_Elem& eval = (Eval_Echange_Himp_VDF_Elem&) iter.evaluateur();
  REF(Equation_base) eqn;
  bool eq_OK=false;
  for (int i=0; i<pb_voisin->nombre_d_equations(); i++)
    if (sub_type(Conduction,pb_voisin->equation(i))
        ||sub_type(Convection_Diffusion_Temperature,pb_voisin->equation(i)))
      {
        eqn=pb_voisin->equation(i);
        eq_OK=true;
      }
  if (!eq_OK)
    {
      Cerr << "Source_Echange_Th_VDF is not coupled to a problem solving temperature." << finl;
      exit();
    }
  eval.associer_champs(equation().inconnue(), eqn->inconnue(),h);
}
void Source_Echange_Th_VDF::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis) [virtual]
Implements Source_base.
Definition at line 53 of file Source_Echange_Th_VDF.cpp.
References Evaluateur_Source_VDF::associer_zones(), Iterateur_Source_VDF::evaluateur(), Terme_Source_VDF_base::iter, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
// Associe les zones a l'iterateur et a l'evaluateur
  const Zone_VDF& zvdf = ref_cast(Zone_VDF,zone_dis.valeur());
  const Zone_Cl_VDF& zclvdf = ref_cast(Zone_Cl_VDF,zone_cl_dis.valeur());
  /*
    Cerr << "hello" << finl;
    Cerr << "iter.non_nul()=" << iter.non_nul() << finl;
    Cerr << "hello" << finl;
  */
  iter->associer_zones(zvdf, zclvdf);
  Eval_Echange_Himp_VDF_Elem& eval = (Eval_Echange_Himp_VDF_Elem&) iter.evaluateur();
  eval.associer_zones(zvdf, zclvdf );
}
Objet_U * Source_Echange_Th_VDF::cree_instance () [static]
Definition at line 30 of file Source_Echange_Th_VDF.cpp.
int Source_Echange_Th_VDF::duplique () const [virtual]
Implements Terme_Source_VDF_base.
Definition at line 30 of file Source_Echange_Th_VDF.cpp.
const Type_info * Source_Echange_Th_VDF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_VDF_base.
Definition at line 30 of file Source_Echange_Th_VDF.cpp.
const Type_info * Source_Echange_Th_VDF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_VDF_base.
Definition at line 30 of file Source_Echange_Th_VDF.cpp.
void Source_Echange_Th_VDF::mettre_a_jour (double temps) [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 54 of file Source_Echange_Th_VDF.h.
  {
    ;
  }
Sortie & Source_Echange_Th_VDF::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Source_VDF_base.
Definition at line 35 of file Source_Echange_Th_VDF.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Source_Echange_Th_VDF::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Terme_Source_VDF_base.
Definition at line 42 of file Source_Echange_Th_VDF.cpp.
References h, Interprete::objet(), pb_voisin, ref_cast, Source_base::set_description(), and Source_base::set_fichier().
{
  Nom nom_pb;
  s >> nom_pb >> h;
  pb_voisin = ref_cast(Probleme_base,Interprete::objet(nom_pb));
  set_fichier("Ech_Thermique");
  set_description("Heat power release = h*Integral(delta_T(elem)*dv) [W]");
  return s;
}
Source_Echange_Th_VDF & Source_Echange_Th_VDF::self_cast (Objet_U & r) [static]
Reimplemented from Terme_Source_VDF_base.
Definition at line 30 of file Source_Echange_Th_VDF.cpp.
const Source_Echange_Th_VDF & Source_Echange_Th_VDF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Terme_Source_VDF_base.
Definition at line 30 of file Source_Echange_Th_VDF.cpp.
unsigned Source_Echange_Th_VDF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 30 of file Source_Echange_Th_VDF.cpp.
Member Data Documentation
double Source_Echange_Th_VDF::h [private]
Valeur du coefficient d'echange.
Definition at line 59 of file Source_Echange_Th_VDF.h.
Referenced by associer_pb(), and readOn().
const Type_info Source_Echange_Th_VDF::info_obj [static]
Reimplemented from Terme_Source_VDF_base.
Definition at line 45 of file Source_Echange_Th_VDF.h.
Ref_Probleme_base Source_Echange_Th_VDF::pb_voisin [private]
Le probleme avec lequel se fait l'echange.
Definition at line 60 of file Source_Echange_Th_VDF.h.
Referenced by associer_pb(), and readOn().
The documentation for this class was generated from the following files:
src/VDF/Sources/Source_Echange_Th_VDF.h
src/VDF/Sources/Source_Echange_Th_VDF.cpp