TRUST: VDF_discretisation Class Reference
VDF_discretisation Class Reference
#include <VDF_discretisation.h>
Public Member Functions
VDF_discretisation ()
~VDF_discretisation ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const override
Discretisation d'un Champ_Inc pour le VDF en fonction d'une directive
de discretisation. La directive est un Motcle comme "vitesse", "pression",
"temperature", "champ_elem" (cree un champ de type P0 ...), ...
Cette methode determine le type du champ a creer en fonction du type d'element
et de la directive de discretisation. Elle determine ensuite le nombre de ddl
et fixe l'ensemble des parametres du champ (type, nb_compo, nb_ddl, nb_pas_dt,
nom(s), unite(s), nature du champ et attribue un temps) et associe la Zone_dis au champ.
Voir le code pour avoir la correspondance entre les directives et
le type de champ cree.
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Fonc &champ) const override
Idem que VDF_discretisation::discretiser_champ(... , Champ_Inc)
pour un Champ_Fonc.
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Don &champ) const override
Idem que VDF_discretisation::discretiser_champ(... , Champ_Inc)
pour un Champ_Don.
void zone_Cl_dis (Zone_dis &z, Zone_Cl_dis &zcl) const override
void proprietes_physiques_fluide_Ostwald (const Zone_dis &, Fluide_Ostwald &, const Navier_Stokes_std &, const Champ_Inc &) const override
discretise en VDF le fluide incompressible, donc K e N
void vorticite (Zone_dis &, const Champ_Inc &, Champ_Fonc &) const
void creer_champ_vorticite (const Schema_Temps_base &, const Champ_Inc &, Champ_Fonc &) const override
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
void grad_u (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const override
void critere_Q (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const override
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
void reynolds_maille (const Zone_dis &, const Fluide_base &, const Champ_Inc &, Champ_Fonc &) const override
void courant_maille (const Zone_dis &, const Schema_Temps_base &, const Champ_Inc &, Champ_Fonc &) const override
void taux_cisaillement (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const override
void y_plus (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const override
void residu (const Zone_dis &, const Champ_Inc &, Champ_Fonc &) const override
Public Member Functions inherited from Discret_Thyd
Discret_Thyd ()
~Discret_Thyd () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void vitesse (const Schema_Temps_base &, Zone_dis &, Champ_Inc &, int nb_comp=1) const
void translation (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
void entcor (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
void pression (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void pression_en_pa (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void divergence_U (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void gradient_P (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void concentration (const Schema_Temps_base &, Zone_dis &, Champ_Inc &, int=1, const Nom nom_champ="concentration") const
void porosite_volumique (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
void diametre_hydraulique_elem (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
void diametre_hydraulique_face (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
void section_passage (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
virtual void creer_champ_vorticite (const Schema_Temps_base &, const Champ_Inc &, Champ_Fonc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
virtual void grad_u (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
virtual void proprietes_physiques_fluide_Ostwald (const Zone_dis &, Fluide_Ostwald &, const Navier_Stokes_std &, const Champ_Inc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
virtual void distance_paroi_globale (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
virtual void y_plus (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
virtual void grad_T (const Zone_dis &z, const Zone_Cl_dis &zcl, const Champ_Inc &eqn, Champ_Fonc &ch) const
virtual void h_conv (const Zone_dis &z, const Zone_Cl_dis &zcl, const Champ_Inc &eqn, Champ_Fonc &ch, Motcle &nom, int temp_ref) const
virtual void critere_Q (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
virtual void reynolds_maille (const Zone_dis &, const Fluide_base &, const Champ_Inc &, Champ_Fonc &) const
virtual void courant_maille (const Zone_dis &, const Schema_Temps_base &, const Champ_Inc &, Champ_Fonc &) const
virtual void estimateur_aposteriori (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, const Champ_Inc &, const Champ_Don &, Champ_Fonc &) const
virtual void taux_cisaillement (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
Public Member Functions inherited from Discret_Thermique
Discret_Thermique ()
~Discret_Thermique () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void temperature (const Schema_Temps_base &, Zone_dis &, Champ_Inc &, int nb_comp=1) const
void flux_neutronique (const Schema_Temps_base &sch, Zone_dis &z, Champ_Inc &ch, int nb_comp=1) const
void Fluctu_Temperature (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void Flux_Chaleur_Turb (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
Public Member Functions inherited from Discretisation_base
Discretisation_base ()
~Discretisation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual type_calcul_du_residu codage_du_calcul_du_residu (void) const
virtual void discretiser_variables () const
virtual void discretiser_Zone_Cl_dis (const Zone_dis &, Zone_Cl_dis &) const
virtual void discretiser (Domaine_dis &) const
virtual void zone_Cl_dis (Zone_dis &, Zone_Cl_dis &) const =0
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, double temps, Champ_Fonc &champ) const
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, double temps, Champ_Don &champ) const
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const
Discretisation d'un champ en fonction de la directive et des autres
parametres. Voir les classes derivees. Cette methode
ne traite aucune directive, elle affiche la liste des directives comprises
par les classes derivees.
Voir par exemple VDF_discretisation.cpp et VEF...
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Fonc &champ) const
idem
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Don &champ) const
idem
void nommer_completer_champ_physique (const Zone_dis_base &zone_vdf, const Nom &nom_champ, const Nom &unite, Champ_base &champ, const Probleme_base &pbi) const
int verifie_sous_type (Nom &type, const Nom &sous_type, const Motcle &directive) const
void volume_maille (const Schema_Temps_base &sch, const Zone_dis &z, Champ_Fonc &ch) const
virtual void residu (const Zone_dis &, const Champ_Inc &, Champ_Fonc &) const
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const Ref_Champ_base &champ_supp=Ref_Champ_base()) const
remplit le Nom type en focntion de la classe de operateur, du type de l'operateur et de l'equation
Parametre: class_operateur
Signification: Ce nom correspond au type de la classe de base de l'objet que l'on veut construire
exemples: "source","Op_conv","Op_diff","Op_div","Op_grad","solveur_masse"
Exemple get_name_of_type_for("Op_conv","amont",eqn,type);
get_name_of_type_for("Op_diff"," ",eqn,type,champ_diffusisivite);
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static VDF_discretisation & self_cast (Objet_U &)
static const VDF_discretisation & self_cast (const Objet_U &)
Static Public Member Functions inherited from Discret_Thyd
static const Type_info * info ()
static Discret_Thyd & self_cast (Objet_U &)
static const Discret_Thyd & self_cast (const Objet_U &)
Static Public Member Functions inherited from Discret_Thermique
static const Type_info * info ()
static Discret_Thermique & self_cast (Objet_U &)
static const Discret_Thermique & self_cast (const Objet_U &)
Static Public Member Functions inherited from Discretisation_base
static const Type_info * info ()
static Discretisation_base & self_cast (Objet_U &)
static const Discretisation_base & self_cast (const Objet_U &)
static void creer_champ (Champ_Inc &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Inc du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
static void creer_champ (Champ_Fonc &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Fonc du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
static void creer_champ (Champ_Don &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Don du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Discret_Thyd
static const Type_info info_obj
Static Public Attributes inherited from Discret_Thermique
static const Type_info info_obj
Static Public Attributes inherited from Discretisation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void discretiser_champ_fonc_don (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &noms, const Noms &unites, int nb_comp, double temps, Objet_U &champ) const
Idem que VEF_discretisation::discretiser_champ(... , Champ_Inc)
Traitement commun aux champ_fonc et champ_don.
Cette methode est privee (passage d'un Objet_U pas propre vu
de l'exterieur ...)
void modifier_champ_tabule (const Zone_dis_base &zone_dis, Champ_Fonc_Tabule &ch_tab, const Vect_Ref_Champ_base &ch_inc) const override
Additional Inherited Members
Public Types inherited from Discretisation_base
enum type_calcul_du_residu { VIA_CONTRIBUER_AU_SECOND_MEMBRE = 0 , VIA_AJOUTER = 1 }
Static Protected Attributes inherited from Discretisation_base
static const Motcle demande_description = Motcle("demande_description")
static const Nom nom_vide = Nom("-")
Detailed Description
Definition at line 45 of file VDF_discretisation.h.
Constructor & Destructor Documentation
VDF_discretisation()
VDF_discretisation::VDF_discretisation ()
Definition at line 36 of file VDF_discretisation.cpp.
~VDF_discretisation()
VDF_discretisation::~VDF_discretisation ()
Definition at line 36 of file VDF_discretisation.cpp.
Member Function Documentation
courant_maille()
void VDF_discretisation::courant_maille (const Zone_dis & z, const Schema_Temps_base & sch, const Champ_Inc & ch_vitesse, Champ_Fonc & champ) const override virtual
Reimplemented from Discret_Thyd.
Definition at line 400 of file VDF_discretisation.cpp.
{
  const Zone_VDF& zone_vdf=ref_cast(Zone_VDF, z.valeur());
  champ.typer("Courant_maille_Champ_Face");
  Courant_maille_Champ_Face& ch=ref_cast(Courant_maille_Champ_Face,champ.valeur());
  ch.associer_zone_dis_base(zone_vdf);
  const Champ_Face& vit = ref_cast(Champ_Face, ch_vitesse.valeur());
  ch.associer_champ(vit,sch);
  ch.nommer("Courant_maille");
  ch.fixer_nb_comp(dimension);
  ch.fixer_nom_compo(0, "Courant_maille_X");
  ch.fixer_nom_compo(1, "Courant_maille_Y");
  if (dimension==3) ch.fixer_nom_compo(2, "Courant_maille_Z");
  ch.fixer_nb_valeurs_nodales(zone_vdf.nb_faces());
  ch.fixer_unite("adimensionnel");
  ch.changer_temps(ch_vitesse.temps());
}
References Courant_maille_Champ_Face::associer_champ(), Champ_Fonc_Face::associer_zone_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nb_comp(), Champ_Fonc_Face::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Zone_VF::nb_faces(), Field_base::nommer(), ref_cast, Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), and Deriv_Zone_dis_base::valeur().
cree_instance()
Objet_U * VDF_discretisation::cree_instance () static
Definition at line 36 of file VDF_discretisation.cpp.
creer_champ_vorticite()
void VDF_discretisation::creer_champ_vorticite (const Schema_Temps_base & , const Champ_Inc & , Champ_Fonc &) const override virtual
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
Reimplemented from Discret_Thyd.
Definition at line 551 of file VDF_discretisation.cpp.
{
  if (sub_type(Champ_Face,ch_vitesse.valeur()))
    {
      const Champ_Face& vit = ref_cast(Champ_Face,ch_vitesse.valeur());
      const Zone_VDF& zone_VDF = ref_cast(Zone_VDF,vit.zone_dis_base());
      ch.typer("Rotationnel_Champ_Face");
      Rotationnel_Champ_Face& ch_W=ref_cast(Rotationnel_Champ_Face,ch.valeur());
      ch_W.associer_zone_dis_base(zone_VDF);
      ch_W.associer_champ(vit);
      ch_W.nommer("vorticite");
      if (dimension == 2)
        ch_W.fixer_nb_comp(1);
      else
        {
          ch_W.fixer_nb_comp(dimension);
          ch_W.fixer_nom_compo(0, "vorticiteX");
          ch_W.fixer_nom_compo(1, "vorticiteY");
          ch_W.fixer_nom_compo(2, "vorticiteZ");
        }
      ch_W.fixer_nb_valeurs_nodales(zone_VDF.nb_elem());
      ch_W.fixer_unite("s-1");
      ch_W.changer_temps(sch.temps_courant());
    }
}
References Rotationnel_Champ_Face::associer_champ(), Champ_Fonc_P0_base::associer_zone_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Zone_dis_base::nb_elem(), Field_base::nommer(), ref_cast, sub_type, Schema_Temps_base::temps_courant(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), and Champ_Face::zone_dis_base().
critere_Q()
void VDF_discretisation::critere_Q (const Zone_dis & , const Zone_Cl_dis & , const Champ_Inc & , Champ_Fonc &) const override virtual
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
Reimplemented from Discret_Thyd.
Definition at line 325 of file VDF_discretisation.cpp.
{
  const Champ_Face& vit = ref_cast(Champ_Face,ch_vitesse.valeur());
  const Zone_VDF& zone_vdf=ref_cast(Zone_VDF, z.valeur());
  const Zone_Cl_VDF& zone_cl_vdf=ref_cast(Zone_Cl_VDF, zcl.valeur());
  ch.typer("Critere_Q_Champ_Face");
  Critere_Q_Champ_Face& ch_Criter_Q=ref_cast(Critere_Q_Champ_Face,ch.valeur());
  ch_Criter_Q.associer_zone_dis_base(zone_vdf);
  ch_Criter_Q.associer_zone_Cl_dis_base(zone_cl_vdf);
  ch_Criter_Q.associer_champ(vit);
  ch_Criter_Q.nommer("Critere_Q");
  ch_Criter_Q.fixer_nb_comp(1);
  ch_Criter_Q.fixer_nb_valeurs_nodales(zone_vdf.nb_elem());
  ch_Criter_Q.fixer_unite("s-2");
  ch_Criter_Q.changer_temps(ch_vitesse.temps());
}
References Critere_Q_Champ_Face::associer_champ(), Critere_Q_Champ_Face::associer_zone_Cl_dis_base(), Champ_Fonc_P0_base::associer_zone_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Zone_dis_base::nb_elem(), Field_base::nommer(), ref_cast, Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
discretiser_champ() [1/3]
void VDF_discretisation::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Champ_Don & champ) const override virtual
Idem que VDF_discretisation::discretiser_champ(... , Champ_Inc)
pour un Champ_Don.
Reimplemented from Discretisation_base.
Definition at line 169 of file VDF_discretisation.cpp.
{
  discretiser_champ_fonc_don(directive, z,
                             nature, noms, unites,
                             nb_comp, temps, champ);
}
References discretiser_champ_fonc_don().
discretiser_champ() [2/3]
void VDF_discretisation::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Champ_Fonc & champ) const override virtual
Idem que VDF_discretisation::discretiser_champ(... , Champ_Inc)
pour un Champ_Fonc.
Reimplemented from Discretisation_base.
Definition at line 154 of file VDF_discretisation.cpp.
{
  discretiser_champ_fonc_don(directive, z,
                             nature, noms, unites,
                             nb_comp, temps, champ);
}
References discretiser_champ_fonc_don().
discretiser_champ() [3/3]
void VDF_discretisation::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc & champ, const Nom & sous_type = nom_vide) const override virtual
Discretisation d'un Champ_Inc pour le VDF en fonction d'une directive
de discretisation. La directive est un Motcle comme "vitesse", "pression",
"temperature", "champ_elem" (cree un champ de type P0 ...), ...
Cette methode determine le type du champ a creer en fonction du type d'element
et de la directive de discretisation. Elle determine ensuite le nombre de ddl
et fixe l'ensemble des parametres du champ (type, nb_compo, nb_ddl, nb_pas_dt,
nom(s), unite(s), nature du champ et attribue un temps) et associe la Zone_dis au champ.
Voir le code pour avoir la correspondance entre les directives et
le type de champ cree.
< Choix standard pour la vitesse
< Choix standard pour la pression
< Choix standard pour la temperature
< Le type de champ obtenu en calculant div v
< Le type de champ obtenu en calculant grad P
< Creer un champ aux faces
< Creer un champ aux elements (de type P0)
Reimplemented from Discretisation_base.
Definition at line 58 of file VDF_discretisation.cpp.
{
  const Zone_VDF& zone_vdf = ref_cast(Zone_VDF, z);
  Motcles motcles(7);
  motcles[0] = "vitesse";     //!< Choix standard pour la vitesse
  motcles[1] = "pression";    //!< Choix standard pour la pression
  motcles[2] = "temperature"; //!< Choix standard pour la temperature
  motcles[3] = "divergence_vitesse"; //!< Le type de champ obtenu en calculant div v
  motcles[4] = "gradient_pression";  //!< Le type de champ obtenu en calculant grad P
  motcles[5] = "champ_face";   //!< Creer un champ aux faces
  motcles[6] = "champ_elem";   //!< Creer un champ aux elements (de type P0)
  Nom type;
  int default_nb_comp = -1;
  int rang = motcles.search(directive);
  switch(rang)
    {
    case 0:
      type = "Champ_Face";
      default_nb_comp = dimension;
      break;
    case 1:
      type = "Champ_P0_VDF";
      default_nb_comp = 1;
      break;
    case 2:
      type = "Champ_P0_VDF";
      default_nb_comp = 1;
      break;
    case 3:
      type = "Champ_P0_VDF";
      default_nb_comp = 1;
      break;
    case 4:
      type = "Champ_Face";
      default_nb_comp = dimension;
      break;
    case 5:
      type = "Champ_Face";
      default_nb_comp = 1;
      break;
    case 6:
      type = "Champ_P0_VDF";
      default_nb_comp = 1;
      break;
    default:
      assert(rang < 0);
      break;
    }
  if (directive == demande_description)
    Cerr << "VDF_discretisation : " << motcles;
  if (sous_type != nom_vide)
    rang = verifie_sous_type(type,sous_type,directive);
// Si on n'a pas compris la directive (ou si c'est une demande_description)
// alors on appelle l'ancetre :
  if (rang < 0)
    {
      Discret_Thyd::discretiser_champ(directive, z,
                                      nature, noms, unites,
                                      nb_comp, nb_pas_dt, temps, champ);
      return;
    }
// Calcul du nombre de ddl
  int nb_ddl = 0;
  if (type.debute_par("Champ_P0_VDF"))    nb_ddl = z.nb_elem();
  else if (type.debute_par("Champ_Face")) nb_ddl = zone_vdf.nb_faces();
  else assert(0);
  if (nb_comp < 0)
    nb_comp = default_nb_comp;
  assert(nb_comp > 0);
  creer_champ(champ, z, type, noms[0], unites[0], nb_comp, nb_ddl, nb_pas_dt, temps,
              directive, que_suis_je());
  if (nature == multi_scalaire)
    {
      champ.valeur().fixer_nature_du_champ(nature);
      champ.valeur().fixer_unites(unites);
      champ.valeur().fixer_noms_compo(noms);
    }
}
References Cerr, Discretisation_base::creer_champ(), Nom::debute_par(), Discretisation_base::demande_description, Objet_U::dimension, Discretisation_base::discretiser_champ(), Field_base::fixer_nature_du_champ(), Field_base::fixer_noms_compo(), Field_base::fixer_unites(), multi_scalaire, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Discretisation_base::nom_vide, Objet_U::que_suis_je(), ref_cast, Motcles::search(), Deriv_Champ_Inc_base::valeur(), and Discretisation_base::verifie_sous_type().
discretiser_champ_fonc_don()
void VDF_discretisation::discretiser_champ_fonc_don (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, double temps, Objet_U & champ) const private
Idem que VEF_discretisation::discretiser_champ(... , Champ_Inc)
Traitement commun aux champ_fonc et champ_don.
Cette methode est privee (passage d'un Objet_U pas propre vu
de l'exterieur ...)
< Le type de champ obtenu en calculant div v
< Creer un champ aux elements (de type P0)
< Creer un champ comme la vitesse
< Le type de champ obtenu en calculant grad P
< Creer un champ aux faces
< Creer un champ aux sommets
< Nombre de composantes par defaut
Definition at line 186 of file VDF_discretisation.cpp.
{
// Deux pointeurs pour acceder facilement au champ_don ou au champ_fonc,
// suivant le type de l'objet champ.
  Champ_Fonc * champ_fonc = 0;
  Champ_Don * champ_don = 0;
  if (sub_type(Champ_Fonc, champ))
    champ_fonc = & ref_cast(Champ_Fonc, champ);
  else
    champ_don  = & ref_cast(Champ_Don, champ);
  Motcles motcles(8);
  motcles[0] = "pression";
  motcles[1] = "temperature";
  motcles[2] = "divergence_vitesse"; //!< Le type de champ obtenu en calculant div v
  motcles[3] = "champ_elem";  //!< Creer un champ aux elements (de type P0)
  motcles[4] = "vitesse";     //!< Creer un champ comme la vitesse
  motcles[5] = "gradient_pression";  //!< Le type de champ obtenu en calculant grad P
  motcles[6] = "champ_face";   //!< Creer un champ aux faces
  motcles[7] = "champ_sommets";   //!< Creer un champ aux sommets
  Nom type;
  int rang = motcles.search(directive);
  int default_nb_comp = 1;
  switch(rang)
    {
    case 0:
      type = "Champ_Fonc_P0_VDF";
      break;
    case 1:
      type = "Champ_Fonc_P0_VDF";
      break;
    case 2:
      type = "Champ_Fonc_P0_VDF";
      break;
    case 3:
      type = "Champ_Fonc_P0_VDF";
      break;
    case 4:
      type = "Champ_Fonc_Face";
      default_nb_comp = dimension;
      break;
    case 5:
      type = "Champ_Fonc_Face";
      default_nb_comp = dimension;
      break;
    case 6:
      type = "Champ_Fonc_Face";
      default_nb_comp = 1;
      break;
    case 7:
      type = "Champ_Fonc_Q1_VDF";
      default_nb_comp = 1;
      break;
    default:
      assert(rang < 0);
      break;
    }
  if (directive == demande_description)
    Cerr << "VDF_discretisation : " << motcles;
// Si on n'a pas compris la directive (ou si c'est une demande_description)
// alors on appelle l'ancetre :
  if (rang < 0)
    {
      if (champ_fonc)
        Discret_Thyd::discretiser_champ(directive, z, nature, noms, unites,
                                        nb_comp, temps, *champ_fonc);
      else
        Discret_Thyd::discretiser_champ(directive, z, nature, noms, unites,
                                        nb_comp, temps, *champ_don);
      return;
    }
// Calcul du nombre de ddl
  int nb_ddl = 0;
  const Zone_VDF& zone_vdf = ref_cast(Zone_VDF, z);
  if (type == "Champ_Fonc_P0_VDF")      nb_ddl = z.nb_elem();
  else if (type == "Champ_Fonc_Face")   nb_ddl = zone_vdf.nb_faces();
  else if (type == "Champ_Fonc_Q1_VDF") nb_ddl = zone_vdf.nb_som();
  else assert(0);
  if (nb_comp < 0)
    nb_comp = default_nb_comp; //!< Nombre de composantes par defaut
  if (champ_fonc)
    creer_champ(*champ_fonc, z, type, noms[0], unites[0], nb_comp, nb_ddl, temps,
                directive, que_suis_je());
  else
    creer_champ(*champ_don, z, type, noms[0], unites[0], nb_comp, nb_ddl, temps,
                directive, que_suis_je());
  if ((nature == multi_scalaire) && (champ_fonc))
    {
      champ_fonc->valeur().fixer_nature_du_champ(nature);
      champ_fonc->valeur().fixer_unites(unites);
      champ_fonc->valeur().fixer_noms_compo(noms);
    }
  else if ((nature == multi_scalaire) && (champ_don))
    {
      Cerr<<"There is no field of type Champ_Don with a multi_scalaire nature."<<finl;
      exit();
    }
}
References Cerr, Discretisation_base::creer_champ(), Discretisation_base::demande_description, Objet_U::dimension, Discretisation_base::discretiser_champ(), Process::exit(), finl, Field_base::fixer_nature_du_champ(), Field_base::fixer_noms_compo(), Field_base::fixer_unites(), multi_scalaire, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone_dis_base::nb_som(), Objet_U::que_suis_je(), ref_cast, Motcles::search(), sub_type, and Deriv_Champ_Fonc_base::valeur().
Referenced by discretiser_champ().
duplique()
int VDF_discretisation::duplique () const override virtual
Implements Objet_U.
Definition at line 36 of file VDF_discretisation.cpp.
get_info()
const Type_info * VDF_discretisation::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Discret_Thyd.
Definition at line 36 of file VDF_discretisation.cpp.
grad_u()
void VDF_discretisation::grad_u (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & ch_vitesse, Champ_Fonc & ch) const override virtual
< du/dx
< du/dy
< dv/dx
< dv/dy
< du/dx
< du/dy
< du/dz
< dv/dx
< dv/dy
< dv/dz
< dw/dx
< dw/dy
< dw/dz
Reimplemented from Discret_Thyd.
Definition at line 342 of file VDF_discretisation.cpp.
{
  const Champ_Face& vit = ref_cast(Champ_Face,ch_vitesse.valeur());
  const Zone_VDF& zone_vdf=ref_cast(Zone_VDF, z.valeur());
  const Zone_Cl_VDF& zone_cl_vdf=ref_cast(Zone_Cl_VDF, zcl.valeur());
  ch.typer("grad_U_Champ_Face");
  grad_U_Champ_Face& ch_grad_u=ref_cast(grad_U_Champ_Face,ch.valeur());
  ch_grad_u.associer_zone_dis_base(zone_vdf);
  ch_grad_u.associer_zone_Cl_dis_base(zone_cl_vdf);
  ch_grad_u.associer_champ(vit);
  ch_grad_u.nommer("gradient_vitesse");
  ch_grad_u.fixer_nb_comp(dimension*dimension);
  if (dimension == 2)
    {
      ch_grad_u.fixer_nom_compo(0,"dUdX"); //!< du/dx
      ch_grad_u.fixer_nom_compo(1,"dUdY"); //!< du/dy
      ch_grad_u.fixer_nom_compo(2,"dVdX"); //!< dv/dx
      ch_grad_u.fixer_nom_compo(3,"dVdY"); //!< dv/dy
    }
  else
    {
      ch_grad_u.fixer_nom_compo(0,"dUdX"); //!< du/dx
      ch_grad_u.fixer_nom_compo(1,"dUdY"); //!< du/dy
      ch_grad_u.fixer_nom_compo(2,"dUdZ"); //!< du/dz
      ch_grad_u.fixer_nom_compo(3,"dVdX"); //!< dv/dx
      ch_grad_u.fixer_nom_compo(4,"dVdY"); //!< dv/dy
      ch_grad_u.fixer_nom_compo(5,"dVdZ"); //!< dv/dz
      ch_grad_u.fixer_nom_compo(6,"dWdX"); //!< dw/dx
      ch_grad_u.fixer_nom_compo(7,"dWdY"); //!< dw/dy
      ch_grad_u.fixer_nom_compo(8,"dWdZ"); //!< dw/dz
    }
  ch_grad_u.fixer_nature_du_champ(vectoriel);
  ch_grad_u.fixer_nb_valeurs_nodales(zone_vdf.nb_elem());
  ch_grad_u.fixer_unite("s-1");
  ch_grad_u.changer_temps(ch_vitesse.temps());
}
References grad_U_Champ_Face::associer_champ(), grad_U_Champ_Face::associer_zone_Cl_dis_base(), Champ_Fonc_P0_base::associer_zone_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nature_du_champ(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Zone_dis_base::nb_elem(), Field_base::nommer(), ref_cast, Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), and vectoriel.
info()
const Type_info * VDF_discretisation::info () static
Definition at line 36 of file VDF_discretisation.cpp.
modifier_champ_tabule()
void VDF_discretisation::modifier_champ_tabule (const Zone_dis_base & zone_dis, Champ_Fonc_Tabule & ch_tab, const Vect_Ref_Champ_base & ch_inc) const override private virtual
< We give a name to this field, help for debug
Reimplemented from Discretisation_base.
Definition at line 467 of file VDF_discretisation.cpp.
{
  le_champ_tabule.le_champ_tabule_discretise().typer("Champ_Fonc_Tabule_P0_VDF");
  Champ_Fonc_Tabule_P0_VDF& le_champ_tabule_dis = ref_cast(Champ_Fonc_Tabule_P0_VDF,le_champ_tabule.le_champ_tabule_discretise().valeur());
  le_champ_tabule_dis.associer_zone_dis_base(zone_dis);
  le_champ_tabule_dis.associer_param(ch_inc,le_champ_tabule.table());
  le_champ_tabule_dis.nommer(le_champ_tabule.le_nom()); //!< We give a name to this field, help for debug
  le_champ_tabule_dis.fixer_nb_comp(le_champ_tabule.nb_comp());
  le_champ_tabule_dis.fixer_nb_valeurs_nodales(zone_dis.nb_elem());
  le_champ_tabule_dis.changer_temps(ch_inc[0].valeur().temps());
}
References Champ_Fonc_Tabule_P0_VDF::associer_param(), Champ_Fonc_P0_base::associer_zone_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Champ_Fonc_Tabule::le_champ_tabule_discretise(), Field_base::le_nom(), Field_base::nb_comp(), Zone_dis_base::nb_elem(), Field_base::nommer(), ref_cast, Champ_Fonc_Tabule::table(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), and valeur().
printOn()
Sortie & VDF_discretisation::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Discret_Thyd.
Definition at line 43 of file VDF_discretisation.cpp.
{
  return s ;
}
proprietes_physiques_fluide_Ostwald()
void VDF_discretisation::proprietes_physiques_fluide_Ostwald (const Zone_dis & z, Fluide_Ostwald & le_fluide, const Navier_Stokes_std & eqn_hydr, const Champ_Inc &) const override virtual
discretise en VDF le fluide incompressible, donc K e N
Reimplemented from Discret_Thyd.
Definition at line 519 of file VDF_discretisation.cpp.
{
  Cerr << "Discretisation du fluide_Ostwald" << finl;
  const Zone_VDF& zone_vdf=ref_cast(Zone_VDF, z.valeur());
  const Champ_Inc& ch_vitesse = eqn_hydr.inconnue();
  const Champ_Face& vit = ref_cast(Champ_Face,ch_vitesse.valeur());
  Champ_Don& mu = le_fluide.viscosite_dynamique();
// mu est toujours un champ_Ostwald_VDF , il faut toujours faire ce qui suit
  mu.typer("Champ_Ostwald_VDF");
  Champ_Ostwald_VDF& ch_mu = ref_cast(Champ_Ostwald_VDF,mu.valeur());
  Cerr<<"associe zonedisbase"<<finl;
  ch_mu.associer_zone_dis_base(zone_vdf);
  ch_mu.associer_fluide(le_fluide);
  ch_mu.associer_champ(vit);
  Cerr<<"associations finies"<<finl;
  ch_mu.fixer_nb_comp(1);
  Cerr<<"fait fixer_nb_valeurs_nodales"<<finl;
  Cerr<<"nb_valeurs_nodales = "<<zone_vdf.nb_elem()<<finl;
  ch_mu.fixer_nb_valeurs_nodales(zone_vdf.nb_elem());
  Cerr<<"fait changer_temps"<<finl;
  ch_mu.changer_temps(vit.temps());
  Cerr<<"mu est discretise "<<finl;
}
References Champ_Ostwald_VDF::associer_champ(), Champ_Ostwald::associer_fluide(), Champ_Ostwald_VDF::associer_zone_dis_base(), Cerr, Champ_base::changer_temps(), finl, Field_base::fixer_nb_comp(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Navier_Stokes_std::inconnue(), Zone_dis_base::nb_elem(), ref_cast, Champ_base::temps(), Deriv_::typer(), Deriv_Champ_Don_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_dis_base::valeur(), and Fluide_base::viscosite_dynamique().
readOn()
Entree & VDF_discretisation::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Discret_Thyd.
Definition at line 38 of file VDF_discretisation.cpp.
{
  return s ;
}
residu()
void VDF_discretisation::residu (const Zone_dis & z, const Champ_Inc & ch_inco, Champ_Fonc & champ) const override virtual
Reimplemented from Discretisation_base.
Definition at line 579 of file VDF_discretisation.cpp.
{
  Nom ch_name(ch_inco.le_nom());
  ch_name += "_residu";
  Cerr << "Discretization of " << ch_name << finl;
  const Zone_VDF& zone_vdf = ref_cast( Zone_VDF, z.valeur( ) );
  Motcle loc;
  int nb_comp;
  Nom type_ch = ch_inco.valeur().que_suis_je();
  if (type_ch.debute_par("Champ_Face"))
    {
      loc= "champ_face";
      nb_comp = dimension;
    }
  else
    {
      loc = "champ_elem";
      nb_comp = ch_inco.valeurs().line_size();
    }
  Discretisation_base::discretiser_champ(loc,zone_vdf, ch_name ,"units_not_defined",nb_comp,ch_inco.temps(),champ);
  Champ_Fonc_base& ch_fonc = ref_cast(Champ_Fonc_base,champ.valeur());
  DoubleTab& tab=ch_fonc.valeurs();
  tab = -10000.0 ;
  Cerr << "[Information] Discretisation_base::residu : the residue is set to -10000.0 at initial time" <<finl;
}
References Cerr, Nom::debute_par(), Objet_U::dimension, Discretisation_base::discretiser_champ(), finl, O_U_Ptr::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Objet_U::que_suis_je(), ref_cast, Champ_Inc::temps(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_Don_base::valeurs(), and Champ_Inc::valeurs().
reynolds_maille()
void VDF_discretisation::reynolds_maille (const Zone_dis & z, const Fluide_base & le_fluide, const Champ_Inc & ch_vitesse, Champ_Fonc & champ) const override virtual
Reimplemented from Discret_Thyd.
Definition at line 381 of file VDF_discretisation.cpp.
{
  const Zone_VDF& zone_vdf=ref_cast(Zone_VDF, z.valeur());
  champ.typer("Reynolds_maille_Champ_Face");
  Reynolds_maille_Champ_Face& ch=ref_cast(Reynolds_maille_Champ_Face,champ.valeur());
  ch.associer_zone_dis_base(zone_vdf);
  const Champ_Face& vit = ref_cast(Champ_Face, ch_vitesse.valeur());
  const Champ_Don& nu = le_fluide.viscosite_cinematique();
  ch.associer_champ(vit,nu);
  ch.nommer("Reynolds_maille");
  ch.fixer_nb_comp(dimension);
  ch.fixer_nom_compo(0, "Reynolds_maille_X");
  ch.fixer_nom_compo(1, "Reynolds_maille_Y");
  if (dimension==3) ch.fixer_nom_compo(2, "Reynolds_maille_Z");
  ch.fixer_nb_valeurs_nodales(zone_vdf.nb_faces());
  ch.fixer_unite("adimensionnel");
  ch.changer_temps(ch_vitesse.temps());
}
References Reynolds_maille_Champ_Face::associer_champ(), Champ_Fonc_Face::associer_zone_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nb_comp(), Champ_Fonc_Face::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Zone_VF::nb_faces(), Field_base::nommer(), ref_cast, Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_dis_base::valeur(), and Fluide_base::viscosite_cinematique().
self_cast() [1/2]
const VDF_discretisation & VDF_discretisation::self_cast (const Objet_U & r) static
Definition at line 36 of file VDF_discretisation.cpp.
self_cast() [2/2]
VDF_discretisation & VDF_discretisation::self_cast (Objet_U & r) static
Definition at line 36 of file VDF_discretisation.cpp.
taille_memoire()
unsigned VDF_discretisation::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 36 of file VDF_discretisation.cpp.
taux_cisaillement()
void VDF_discretisation::taux_cisaillement (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & ch_vitesse, Champ_Fonc & champ) const override virtual
Reimplemented from Discret_Thyd.
Definition at line 418 of file VDF_discretisation.cpp.
{
  const Zone_VDF& zone_vdf=ref_cast(Zone_VDF, z.valeur());
  const Zone_Cl_VDF& zone_cl_vdf=ref_cast(Zone_Cl_VDF, zcl.valeur());
  champ.typer("Taux_cisaillement_P0_VDF");
  Taux_cisaillement_P0_VDF& ch=ref_cast(Taux_cisaillement_P0_VDF,champ.valeur());
  ch.associer_zone_dis_base(zone_vdf);
  const Champ_Face& vit = ref_cast(Champ_Face, ch_vitesse.valeur());
  ch.associer_champ(vit, zone_cl_vdf);
  ch.nommer("Taux_cisaillement");
  ch.fixer_nb_comp(1);
  ch.fixer_nb_valeurs_nodales(zone_vdf.nb_elem());
  ch.fixer_unite("s-1");
  ch.changer_temps(ch_vitesse.temps());
}
References Taux_cisaillement_P0_VDF::associer_champ(), Champ_Fonc_P0_base::associer_zone_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Zone_dis_base::nb_elem(), Field_base::nommer(), ref_cast, Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
vorticite()
void VDF_discretisation::vorticite (Zone_dis & z, const Champ_Inc & ch_vitesse, Champ_Fonc & ch) const
Definition at line 300 of file VDF_discretisation.cpp.
{
  const Champ_Face& vit = ref_cast(Champ_Face,ch_vitesse.valeur());
  const Zone_VDF& zone_vdf=ref_cast(Zone_VDF, z.valeur());
  ch.typer("Rotationnel_Champ_Face");
  Rotationnel_Champ_Face& ch_W=ref_cast(Rotationnel_Champ_Face,ch.valeur());
  ch_W.associer_zone_dis_base(zone_vdf);
  ch_W.associer_champ(vit);
  ch_W.nommer("vorticite");
  if (dimension == 2)
    ch_W.fixer_nb_comp(1);
  else
    {
      ch_W.fixer_nb_comp(dimension);
      ch_W.fixer_nom_compo(0,"vorticiteX");
      ch_W.fixer_nom_compo(1,"vorticiteY");
      ch_W.fixer_nom_compo(2,"vorticiteZ");
    }
  ch_W.fixer_nb_valeurs_nodales(zone_vdf.nb_elem());
  ch_W.fixer_unite("s-1");
  ch_W.changer_temps(ch_vitesse.temps());
}
References Rotationnel_Champ_Face::associer_champ(), Champ_Fonc_P0_base::associer_zone_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Zone_dis_base::nb_elem(), Field_base::nommer(), ref_cast, Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), and Deriv_Zone_dis_base::valeur().
y_plus()
void VDF_discretisation::y_plus (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & ch_vitesse, Champ_Fonc & ch) const override virtual
Reimplemented from Discret_Thyd.
Definition at line 434 of file VDF_discretisation.cpp.
{
  const Champ_Face& vit = ref_cast(Champ_Face,ch_vitesse.valeur());
  const Zone_VDF& zone_vdf=ref_cast(Zone_VDF, z.valeur());
  const Zone_Cl_VDF& zone_cl_vdf=ref_cast(Zone_Cl_VDF, zcl.valeur());
  ch.typer("Y_plus_Champ_Face");
  Y_plus_Champ_Face& ch_y_plus=ref_cast(Y_plus_Champ_Face,ch.valeur());
  ch_y_plus.associer_zone_dis_base(zone_vdf);
  ch_y_plus.associer_zone_Cl_dis_base(zone_cl_vdf);
  ch_y_plus.associer_champ(vit);
  ch_y_plus.nommer("Y_plus");
  ch_y_plus.fixer_nb_comp(1);
  ch_y_plus.fixer_nb_valeurs_nodales(zone_vdf.nb_elem());
  ch_y_plus.fixer_unite("adimensionnel");
  ch_y_plus.changer_temps(ch_vitesse.temps());
}
References Y_plus_Champ_Face::associer_champ(), Y_plus_Champ_Face::associer_zone_Cl_dis_base(), Champ_Fonc_P0_base::associer_zone_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Zone_dis_base::nb_elem(), Field_base::nommer(), ref_cast, Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
zone_Cl_dis()
void VDF_discretisation::zone_Cl_dis (Zone_dis & z, Zone_Cl_dis & zcl) const override virtual
Implements Discretisation_base.
Definition at line 480 of file VDF_discretisation.cpp.
{
  Cerr << "Discretisation des conditions limites" << finl;
  Zone_VDF& zone_vdf=ref_cast(Zone_VDF, z.valeur());
  zcl.typer("Zone_Cl_VDF");
  Zone_Cl_VDF& zone_cl_vdf=ref_cast(Zone_Cl_VDF, zcl.valeur());
  zone_cl_vdf.associer(zone_vdf);
}
References Zone_Cl_VDF::associer(), Cerr, finl, ref_cast, Deriv_::typer(), Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
Member Data Documentation
info_obj
const Type_info VDF_discretisation::info_obj static
Definition at line 47 of file VDF_discretisation.h.
The documentation for this class was generated from the following files:
src/VDF/Zones/VDF_discretisation.h
src/VDF/Zones/VDF_discretisation.cpp