TRUST: Schema_Implicite_Multi_TimeStep_base Class Reference
Schema_Implicite_Multi_TimeStep_base Class Reference abstract
#include <Schema_Implicite_Multi_TimeStep_base.h>
Public Member Functions
Schema_Implicite_Multi_TimeStep_base ()
~Schema_Implicite_Multi_TimeStep_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
bool initTimeStep (double dt) override
void set_param (Param &) override
int nb_valeurs_futures () const override
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1, donc 1.
double temps_futur (int i) const override
Renvoie le le temps a la i-eme valeur future.
Ici : t(n+1)
double temps_defaut () const override
Renvoie le le temps le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : t(n+1)
int nb_valeurs_temporelles_effectives () const
virtual double changer_temps (Equation_base &eqn, const double temps)=0
virtual void update_time_derivative (Equation_base &eqn, const DoubleTab &data)=0
virtual void mettre_a_jour_equation (Equation_base &eqn, const double temps)=0
virtual void modify_equation_parameters (Equation_base &eqn, DoubleTab &stored_parameters)=0
virtual void store_equation_parameters (Equation_base &eqn, DoubleTab &stored_parameters)=0
virtual DoubleTab & coefficients ()=0
virtual void compute_coefficients (double time_step, const DoubleTab &times) const =0
virtual void add_multi_timestep_data (const Equation_base &eqn, Matrice_Base &mat_morse, DoubleTab &secmem) const =0
virtual int nb_pas_dt_seuil () const =0
virtual int nb_valeurs_passees () const =0
virtual const DoubleTab & coefficients () const =0
virtual int faire_un_pas_de_temps_pb_couple (Probleme_Couple &, int &ok)
bool iterateTimeStep (bool &converged) override
Calculate the U(n+1) unknown for each equation (if solved) of the problem with the selected time scheme.
int faire_un_pas_de_temps_eqn_base (Equation_base &) override
int mettre_a_jour () override
Mise a jour du temps courant (t+=dt)
et du nombre de pas de temps effectue (nb_pas_dt_++).
int reprendre (Entree &) override
Reprise (lecture) du temps courant et du nombre de pas de
temps effectues a partir d'un flot d'entree.
void completer (void) override
void Initialiser_Champs (Probleme_base &)
void test_stationnaire (Probleme_base &)
int Iterer_Pb (Probleme_base &, int ite)
const double & residu_old () const
void ajouter_inertie (Matrice_Base &mat_morse, DoubleTab &secmem, const Equation_base &eqn) const override
virtual void modifier_second_membre_full_impl (const Equation_base &eqn, DoubleTab &secmem)
void modifier_second_membre (const Equation_base &eqn, DoubleTab &secmem) override
Public Member Functions inherited from Schema_Implicite_base
Schema_Implicite_base ()
class Schema_Implicite_base
~Schema_Implicite_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Solveur_Implicite & solveur ()
const Solveur_Implicite & solveur () const
void set_param (Param &param) override
Public Member Functions inherited from Schema_Temps_base
~Schema_Temps_base () override
< necessaire pour visual
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void initialize ()
virtual void terminate ()
virtual double computeTimeStep (bool &stop) const
virtual bool initTimeStep (double dt)
virtual void validateTimeStep ()
virtual bool isStationary () const
Retourne 1 si lors du dernier pas de temps, le probleme n'a pas evolue.
virtual void abortTimeStep ()
virtual bool iterateTimeStep (bool &converged)
Calculate the U(n+1) unknown for each equation (if solved) of the problem with the selected time scheme.
int limpr () const
Renvoie 1 s'il y a lieu d'effectuer une impression (cf dt_impr)
Renvoie 0 sinon.
virtual int nb_valeurs_temporelles () const =0
virtual int nb_valeurs_futures () const =0
virtual double temps_futur (int i) const =0
virtual double temps_defaut () const =0
Schema_Temps_base ()
Constructeur par defaut d'un schema en temps.
Initialise differents membres de la classe.
void nommer (const Nom &) override
surcharge Objet_U::nommer(const Nom&)
Donne un nom au shema en temps
const Nom & le_nom () const override
surcharge Objet_U::le_nom()
Renvoie le nom du shema en temps
virtual int faire_un_pas_de_temps_eqn_base (Equation_base &)=0
virtual void set_param (Param &titi)
int sauvegarder (Sortie &) const override
Sauvegarde le temps courant et le nombre de pas de temps
sur un flot de sortie.
int reprendre (Entree &) override
Reprise (lecture) du temps courant et du nombre de pas de
temps effectues a partir d'un flot d'entree.
virtual int mettre_a_jour ()
Mise a jour du temps courant (t+=dt)
et du nombre de pas de temps effectue (nb_pas_dt_++).
virtual void mettre_a_jour_dt (double toto)
virtual void mettre_a_jour_dt_stab ()
double pas_de_temps () const
Renvoie le pas de temps (delta_t) courant.
const DoubleTab & pas_de_temps_locaux () const
virtual bool corriger_dt_calcule (double &dt) const
Corrige le pas de temps calcule que l'on passe en parametre
et verifie qu'il n'est pas "trop" petit (< dt-min_).
La correction est la suivante:
delta_t = min((facteur de securite * dt_calc), dt_max)
Et on verifie que delta_t est "suffisamment" plus grand que dt_min_.
virtual void imprimer (Sortie &os) const
Imprime le pas de temps sur un flot de sortie s'il y a lieu.
virtual int impr (Sortie &os) const
Impression du numero du pas de temps, la valeur du pas de temps.
et du temps courant.
void imprimer (Sortie &os, Probleme_base &pb) const
Imprime le pas de temps sur un flot de sortie s'il y a lieu.
void imprimer (Sortie &os, const Probleme_base &pb) const
virtual int impr (Sortie &os, Probleme_base &pb) const
Impression du numero du pas de temps, la valeur du pas de temps.
et du temps courant.
virtual int impr (Sortie &os, const Probleme_base &pb) const
void imprimer_temps_courant (SFichier &) const
double pas_temps_min () const
Renvoie le pas de temps minimum.
(version const)
double & pas_temps_min ()
Renvoie une reference sur le pas de temps minimum.
double pas_temps_max () const
Renvoie le pas de temps maximum.
(version const)
double & pas_temps_max ()
Renvoie une reference sur le pas de temps maximum.
int nb_impr () const
Renvoie le nombre d'impressions effectuees.
double temps_courant () const
Renvoie le temps courant.
double temps_precedent () const
Renvoie le temps courant.
double temps_calcul () const
Renvoie le temps de calcul ecoule i.e. (temps courant - temps initial).
virtual void changer_temps_courant (const double)
Change le temps courant.
void update_critere_statio (const DoubleTab &tab_critere, Equation_base &equation)
//Actualisation de stationnaire_atteint_ et residu_
(critere residu_<seuil_statio_)
double facteur_securite_pas () const
Renvoie le facteur de securite ou multiplicateur de delta_t.
Ce facteur est utilise lors de la correction/verification du
pas de temps. Voir Schema_Temps_base::corriger_dt_calcule(double&)
(version const)
double & facteur_securite_pas ()
Renvoie une reference sur le facteur de securite ou multiplicateur de delta_t.
Ce facteur est utilise lors de la correction/verification du
pas de temps. Voir Schema_Temps_base::corriger_dt_calcule(double&)
virtual int stop () const
Renvoie 1 si il y lieu de stopper le calcul pour differente raisons:
- le temps final est atteint
- le nombre de pas de temps maximum est depasse
- l'etat stationnaire est atteint
- indicateur d'arret fichier (voir int Schema_Temps_base::stop_lu())
Renvoie 0 sinon.
int lsauv () const
int temps_final_atteint () const
Renvoie 1 si le temps final est atteint (ou depasse).
Renvoie 1 si temps_courant_ >= tmax
Renvoie 0 sinon.
int nb_pas_dt_max_atteint () const
Renvoie 1 si (le nombre de pas de temps >= nombre de pas de temps maximum).
Renvoie 0 sinon.
int temps_cpu_max_atteint () const
int stationnaire_atteint () const
int stop_lu () const
Renvoie 1 si le fichier (d'extension) .stop contient un 1
Renvoie 0 sinon.
int diffusion_implicite () const
Renvoie 1 si le schema en temps a ete lu diffusion_implicite.
double seuil_diffusion_implicite () const
int impr_diffusion_implicite () const
Seuil pour implicitation de la diffusion par GC.
int impr_extremums () const
Impression ou non de GC implicitation.
int niter_max_diffusion_implicite () const
int no_conv_subiteration_diffusion_implicite () const
Iterations maximale pour GC implicitation.
int no_error_if_not_converged_diffusion_implicite () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_nb_pas_dt_max (Entree &)
virtual Entree & lire_periode_sauvegarde_securite_en_heures (Entree &)
virtual Entree & lire_temps_cpu_max (Entree &)
virtual void completer ()=0
double temps_init () const
Renvoie le temps initial.
double temps_max () const
Renvoie une reference sur le temps maximum.
double temps_sauv () const
Renvoie une reference sur le temps de sauvegarde.
double temps_impr () const
Renvoie une reference sur le temps d'impression.
int precision_impr () const
int wcol () const
int gnuplot_header () const
double seuil_statio () const
Renvoie une reference sur le seuil stationnaire.
int nb_pas_dt_max () const
Renvoie une reference sur le nombre de pas maxi.
int nb_pas_dt () const
Renvoie le nombre de pas de temps effectues.
double mode_dt_start () const
int indice_tps_final_atteint () const
int indice_nb_pas_dt_max_atteint () const
int lu () const
int file_allocation () const
double & set_temps_init ()
double & set_temps_max ()
double & set_temps_courant ()
double & set_temps_precedent ()
int & set_nb_pas_dt ()
int & set_nb_pas_dt_max ()
double & set_dt_min ()
double & set_dt_max ()
double & set_dt_sauv ()
double & set_dt_impr ()
int & set_precision_impr ()
double & set_dt ()
double & set_facsec ()
double & set_seuil_statio ()
int & set_stationnaire_atteint ()
void set_stationnaires_atteints (bool flag)
int & set_diffusion_implicite ()
double & set_seuil_diffusion_implicite ()
int & set_niter_max_diffusion_implicite ()
double & set_mode_dt_start ()
int & set_indice_tps_final_atteint ()
int & set_indice_nb_pas_dt_max_atteint ()
int & set_lu ()
const double & residu () const
double & residu ()
int & schema_impr ()
const int & schema_impr () const
virtual void associer_pb (const Probleme_base &)
Probleme_base & pb_base ()
const Probleme_base & pb_base () const
virtual void modifier_second_membre (const Equation_base &eqn, DoubleTab &secmem)
virtual void ajouter_inertie (Matrice_Base &mat_morse, DoubleTab &secmem, const Equation_base &eqn) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const Equation_base &eqn, const tabs_t &semi_impl={}) const
int disable_progress () const
int disable_dt_ev () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Schema_Implicite_Multi_TimeStep_base & self_cast (Objet_U &)
static const Schema_Implicite_Multi_TimeStep_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Schema_Implicite_base
static const Type_info * info ()
static Schema_Implicite_base & self_cast (Objet_U &)
static const Schema_Implicite_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Schema_Temps_base
static const Type_info * info ()
static Schema_Temps_base & self_cast (Objet_U &)
static const Schema_Temps_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Schema_Implicite_base
static const Type_info info_obj
Static Public Attributes inherited from Schema_Temps_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Entree & readOn (Entree &) override
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
void authorized_equation (const Equation_base &eqn)
void authorized_equation (const Equation_base &eqn) const
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Entree & readOn (Entree &) override
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Entree & readOn (Entree &) override
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int nb_ite_max
double residu_old_
double facsec_max_
int nb_ite_sans_accel_
Protected Attributes inherited from Schema_Implicite_base
Solveur_Implicite le_solveur
Protected Attributes inherited from Schema_Temps_base
Ref_Probleme_base mon_probleme
Nom nom_
double dt_
Pas de temps de calcul.
DoubleTab dt_locaux_
Local time steps: Vector of size nb faces of the mesh.
double temps_courant_
double temps_precedent_
double dt_failed_
double dt_gf_
double tinit_
double tmax_
double tcpumax_
int nb_pas_dt_
int nb_pas_dt_max_
int nb_impr_
double dt_min_
Pas de temps min fixe par l'utilisateur.
double dt_max_
Pas de temps max fixe par l'utilisateur.
Nom dt_max_str_
Parser_U dt_max_fn_
double dt_stab_
Pas de temps de stabilite.
double facsec_
double seuil_statio_
int seuil_statio_relatif_deconseille_
Drapeau pour specifier si seuil_statio_ est une valeur absolue (defaut) ou relative.
double dt_sauv_
double limite_cpu_sans_sauvegarde_
double periode_cpu_sans_sauvegarde_
double temps_cpu_ecoule_
double dt_impr_
Pas de temps d'impression.
int precision_impr_
Nombre de chiffres significatifs impression.
double mode_dt_start_
mode calcul du pas de temps de depart
double residu_
Residu.
double residu_old_slope_
double cumul_slope_
int gnuplot_header_
int ind_tps_final_atteint
int ind_nb_pas_dt_max_atteint
int ind_temps_cpu_max_atteint
int lu_
int ind_diff_impl_
double seuil_diff_impl_
int impr_diff_impl_
int impr_extremums_
int niter_max_diff_impl_
int no_conv_subiteration_diff_impl_
int no_error_if_not_converged_diff_impl_
int schema_impr_
1 si le schema a le droit d'imprimer dans le .out et dt_ev
int file_allocation_
1 = allocation espace disque (par defaut), 0 sinon
int max_length_cl_
Detailed Description
Definition at line 27 of file Schema_Implicite_Multi_TimeStep_base.h.
Constructor & Destructor Documentation
Schema_Implicite_Multi_TimeStep_base()
Schema_Implicite_Multi_TimeStep_base::Schema_Implicite_Multi_TimeStep_base ()
Definition at line 26 of file Schema_Implicite_Multi_TimeStep_base.cpp.
~Schema_Implicite_Multi_TimeStep_base()
Schema_Implicite_Multi_TimeStep_base::~Schema_Implicite_Multi_TimeStep_base () override
Definition at line 26 of file Schema_Implicite_Multi_TimeStep_base.cpp.
Member Function Documentation
add_multi_timestep_data()
virtual void Schema_Implicite_Multi_TimeStep_base::add_multi_timestep_data (const Equation_base & eqn, Matrice_Base & mat_morse, DoubleTab & secmem) const pure virtual
Implemented in Schema_Adams_Moulton_base, and Schema_Backward_Differentiation_base.
Referenced by ajouter_inertie().
ajouter_inertie()
void Schema_Implicite_Multi_TimeStep_base::ajouter_inertie (Matrice_Base & mat_morse, DoubleTab & secmem, const Equation_base & eqn) const override virtual
Reimplemented from Schema_Temps_base.
Definition at line 390 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  if (nb_pas_dt()>nb_pas_dt_seuil())
    {
      const Equation_base&  eqn_bis   = ref_cast(Equation_base,eqn);
      int             i         = 0;
      int             offset    = 0;
      double          time_step = pas_de_temps();
// Building of a time-in-ascending-order table
      DoubleTab times(nb_valeurs_temporelles_effectives());
      assert(nb_valeurs_passees()+2 == nb_valeurs_temporelles_effectives());
      for (i=0; i<nb_valeurs_passees(); ++i)
        {
          offset   =  nb_valeurs_passees()-i;
          times[i] =  eqn_bis.inconnue().valeur().recuperer_temps_passe(offset); //past time
        }
      times[nb_valeurs_passees()]   = eqn_bis.inconnue().valeur().recuperer_temps_futur(0); //present time
      times[nb_valeurs_passees()+1] = eqn_bis.inconnue().valeur().recuperer_temps_futur(1); //future time
      compute_coefficients(time_step,times);
      add_multi_timestep_data(eqn, mat_morse, secmem);
    }
  else
    {
// Backward Euler time scheme
      Schema_Temps_base::ajouter_inertie(mat_morse,secmem,eqn);
    }
}
References add_multi_timestep_data(), Schema_Temps_base::ajouter_inertie(), compute_coefficients(), Equation_base::inconnue(), Schema_Temps_base::nb_pas_dt(), nb_pas_dt_seuil(), nb_valeurs_passees(), nb_valeurs_temporelles_effectives(), Schema_Temps_base::pas_de_temps(), Champ_Inc_base::recuperer_temps_futur(), Champ_Inc_base::recuperer_temps_passe(), ref_cast, and Deriv_Champ_Inc_base::valeur().
authorized_equation() [1/2]
void Schema_Implicite_Multi_TimeStep_base::authorized_equation (const Equation_base & eqn) protected
Definition at line 592 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  Nom  equation_name(eqn.que_suis_je());
  bool authorized =  true;
  authorized &= (bool) equation_name.find("FT");
  authorized &= (bool) equation_name.find("Front_Tracking");
  authorized &= (bool) equation_name.find("QC");
  authorized &= (bool) equation_name.find("Quasi_Compressible");
  if (!authorized)
    {
      Cerr<<"Error in "<<que_suis_je()<<"::authorized_equation()"<<finl;
      Cerr<<"Equation "<<equation_name<<" is not allowed with "<<que_suis_je()<<" time scheme"<<finl;
      Process::exit();
    }
}
References Cerr, Process::exit(), Nom::find(), finl, and Objet_U::que_suis_je().
Referenced by faire_un_pas_de_temps_eqn_base(), and Iterer_Pb().
authorized_equation() [2/2]
void Schema_Implicite_Multi_TimeStep_base::authorized_equation (const Equation_base & eqn) const protected
Definition at line 610 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  Nom  equation_name(eqn.que_suis_je());
  bool authorized =  true;
  authorized &= (bool) equation_name.find("FT");
  authorized &= (bool) equation_name.find("Front_Tracking");
  authorized &= (bool) equation_name.find("QC");
  authorized &= (bool) equation_name.find("Quasi_Compressible");
  if (!authorized)
    {
      Cerr<<"Error in "<<que_suis_je()<<"::authorized_equation()"<<finl;
      Cerr<<"Equation "<<equation_name<<" is not allowed with "<<que_suis_je()<<" time scheme"<<finl;
      Process::exit();
    }
}
References Cerr, Process::exit(), Nom::find(), finl, and Objet_U::que_suis_je().
changer_temps()
virtual double Schema_Implicite_Multi_TimeStep_base::changer_temps (Equation_base & eqn, const double temps) pure virtual
Implemented in Schema_Adams_Moulton_base, and Schema_Backward_Differentiation_base.
Referenced by Iterer_Pb().
coefficients() [1/2]
virtual const DoubleTab & Schema_Implicite_Multi_TimeStep_base::coefficients () const pure virtual
Implemented in Schema_Adams_Moulton_base, and Schema_Backward_Differentiation_base.
coefficients() [2/2]
virtual DoubleTab & Schema_Implicite_Multi_TimeStep_base::coefficients () pure virtual
Implemented in Schema_Adams_Moulton_base, and Schema_Backward_Differentiation_base.
completer()
void Schema_Implicite_Multi_TimeStep_base::completer (void) inline override virtual
Implements Schema_Temps_base.
Definition at line 73 of file Schema_Implicite_Multi_TimeStep_base.h.
{ } ;
compute_coefficients()
virtual void Schema_Implicite_Multi_TimeStep_base::compute_coefficients (double time_step, const DoubleTab & times) const pure virtual
Implemented in Schema_Adams_Moulton_base, and Schema_Backward_Differentiation_base.
Referenced by ajouter_inertie().
faire_un_pas_de_temps_eqn_base()
int Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base (Equation_base & eqn) override virtual
Implements Schema_Temps_base.
Definition at line 421 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
// Necessary because of equations like Transport_K_Eps which must be time incremented but
// are not equations of the solved problem and therefore are not seen by Schema_Implicite_Multi_TimeStep_base::iterateTimeStep
  DoubleTab& passe           = eqn.inconnue().passe();
  DoubleTab& present         = eqn.inconnue().valeurs();
  DoubleTab& futur           = eqn.inconnue().futur();
  int        compteur        = 0, ok = 1;
  int        i               = 0;
  bool       convergence_eqn = false;
  DoubleTab      stored_parameters;
  authorized_equation(eqn);
// Initialize time data
  if ( (eqn.que_suis_je() != "Euler") || temps_courant_ ==0.)
    {
      for (i=nb_valeurs_passees(); i>-1; i--)
        {
          eqn.inconnue().passe(i+1) = eqn.inconnue().passe(i);
        }
    }
// sert pour la pression et les couplages
  eqn.zone_Cl_dis().imposer_cond_lim(eqn.inconnue(),temps_courant()+pas_de_temps());
  Cout << finl;
  while ((!convergence_eqn)&&(compteur<nb_ite_max))
    {
      compteur++;
      Cout<<"==================================================================================" << finl;
      Cout<<que_suis_je()<<": Implicit iteration " << compteur << " on the "<<eqn.que_suis_je() << " equation of the problem "<< eqn.probleme().le_nom()<< " :" <<finl;
      Cout<<"==================================================================================" << finl;
      const DoubleTab& inut=futur;
      store_equation_parameters(eqn,stored_parameters);
      convergence_eqn=le_solveur.valeur().iterer_eqn(eqn, inut, present, dt_, compteur, ok);
      modify_equation_parameters(eqn,stored_parameters);
      futur=present;
      eqn.zone_Cl_dis().imposer_cond_lim(eqn.inconnue(),temps_courant()+pas_de_temps());
      present=futur;
    }
// Calculation of time derivative at time n+1
  present -= passe; //"present" contains unknown at time n+1 and "passe" contains unknown at time n
  present/=dt_;
  update_critere_statio(present, eqn);
  update_time_derivative(eqn,present);
// Update time data
  for (i=0; i<nb_valeurs_passees(); i++)
    {
      eqn.inconnue().passe(i) = eqn.inconnue().passe(i+1);
    }
  return 1;
}
References authorized_equation(), compteur, Cout, Schema_Temps_base::dt_, finl, Champ_Inc::futur(), Zone_Cl_dis::imposer_cond_lim(), Equation_base::inconnue(), Solveur_Implicite_Base::iterer_eqn(), Probleme_base::le_nom(), Schema_Implicite_base::le_solveur, modify_equation_parameters(), nb_ite_max, nb_valeurs_passees(), Schema_Temps_base::pas_de_temps(), Champ_Inc::passe(), Equation_base::probleme(), Objet_U::que_suis_je(), store_equation_parameters(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_courant_, Schema_Temps_base::update_critere_statio(), update_time_derivative(), Deriv_Solveur_Implicite_Base::valeur(), Champ_Inc::valeurs(), and Equation_base::zone_Cl_dis().
faire_un_pas_de_temps_pb_couple()
int Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple (Probleme_Couple & pbc, int & ok) virtual
Definition at line 315 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
// Modif B.M. : Si on fait la sauvegarde entre derivee en temps inco et mettre a jour,
// un calcul avec reprise n'est pas equivalent au calcul ininterrompu
// (front-tracking notamment). Donc je mets la sauvegarde au debut du pas de temps.
// if (lsauv())
// for (int i=0;i<pbc.nb_problemes();i++)
// ref_cast(Probleme_base,pbc.probleme(i)).sauver();
  int convergence_pbc = 0;
  int convergence_pb;
  int i;
  for(i=0; i<pbc.nb_problemes(); i++)
    Initialiser_Champs(ref_cast(Probleme_base,pbc.probleme(i)));
  int compteur;
  while (!ok)
    {
      compteur=0;
      while ((!convergence_pbc )&&(compteur<nb_ite_max))
        {
          compteur++;
          convergence_pbc=1;
          for(i=0; i<pbc.nb_problemes()*1; i++)
            {
              Probleme_base& pb = ref_cast(Probleme_base,pbc.probleme(i));
              const int nb_eqn=pb.nombre_d_equations();
              for(int ii=0; ii<nb_eqn; ii++)
                {
                  pb.equation(ii).zone_Cl_dis()->calculer_coeffs_echange(temps_courant_+pas_de_temps());
                }
            }
          for(i=0; i<pbc.nb_problemes(); i++)
            {
              pbc.probleme(i).updateGivenFields();
              convergence_pb = Iterer_Pb(ref_cast(Probleme_base,pbc.probleme(i)),compteur);
              convergence_pbc = convergence_pbc * convergence_pb ;
            }
        }
      if ((!convergence_pbc)&&(compteur==nb_ite_max))
        {
          Cerr<<"The process is restarted. " <<finl;
          facsec_/=2;
          dt_/=2;
          ok=0;
          for(int i2=0; i2<pbc.nb_problemes(); i2++)
            {
              ref_cast(Probleme_base,pbc.probleme(i2)).abortTimeStep();
              ref_cast(Probleme_base,pbc.probleme(i2)).initTimeStep(dt_);
              Implicite_Multi_TimeStep_recommencer_pb(nb_valeurs_passees(),ref_cast(Probleme_base,pbc.probleme(i2)));
            }
        }
      else ok=1;
    }
  double residu_1=0;
  for(i=0; i<pbc.nb_problemes(); i++)
    {
      residu_1=residu_;
      test_stationnaire(ref_cast(Probleme_base,pbc.probleme(i)));
      residu_=std::max(residu_,residu_1);
    }
  return 1;
}
References Cerr, compteur, Schema_Temps_base::dt_, Probleme_base::equation(), Schema_Temps_base::facsec_, finl, Implicite_Multi_TimeStep_recommencer_pb(), Initialiser_Champs(), Iterer_Pb(), nb_ite_max, Couplage_U::nb_problemes(), nb_valeurs_passees(), Probleme_base::nombre_d_equations(), Schema_Temps_base::pas_de_temps(), Couplage_U::probleme(), ref_cast, Schema_Temps_base::residu_, Schema_Temps_base::temps_courant_, test_stationnaire(), Probleme_U::updateGivenFields(), and Equation_base::zone_Cl_dis().
get_info()
const Type_info * Schema_Implicite_Multi_TimeStep_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Implicite_base.
Reimplemented in Schema_Backward_Differentiation_base, Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Definition at line 26 of file Schema_Implicite_Multi_TimeStep_base.cpp.
info()
const Type_info * Schema_Implicite_Multi_TimeStep_base::info () static
Definition at line 26 of file Schema_Implicite_Multi_TimeStep_base.cpp.
Initialiser_Champs()
void Schema_Implicite_Multi_TimeStep_base::Initialiser_Champs (Probleme_base & pb)
Definition at line 136 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  int i      = 0;
  int j      = 0;
  for(i=0; i<pb.nombre_d_equations(); i++)
    {
      if ( (pb.equation(i).que_suis_je()!="Euler") || temps_courant_==0.)
        {
          for (j=nb_valeurs_passees(); j>-1; j--)
            {
              pb.equation(i).inconnue().passe(j+1) = pb.equation(i).inconnue().passe(j);
            }
        }
    }
}
References Probleme_base::equation(), Equation_base::inconnue(), nb_valeurs_passees(), Probleme_base::nombre_d_equations(), Champ_Inc::passe(), Objet_U::que_suis_je(), and Schema_Temps_base::temps_courant_.
Referenced by faire_un_pas_de_temps_pb_couple(), and iterateTimeStep().
initTimeStep()
bool Schema_Implicite_Multi_TimeStep_base::initTimeStep (double dt) override virtual
Reimplemented from Schema_Temps_base.
Definition at line 92 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  Schema_Implicite_base::initTimeStep(dt);
  residu_ = 0;
  return true;
}
References Schema_Temps_base::initTimeStep(), and Schema_Temps_base::residu_.
iterateTimeStep()
bool Schema_Implicite_Multi_TimeStep_base::iterateTimeStep (bool & converged) override virtual
Calculate the U(n+1) unknown for each equation (if solved) of the problem with the selected time scheme.
Reimplemented from Schema_Temps_base.
Definition at line 249 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  Probleme_base& prob=pb_base();
  int convergence_pb = 0;
  Initialiser_Champs(prob);
  int ok=0;
  int compteur;
  while (!ok)
    {
      compteur=0;
      Cout<<" "<<finl;
      Cout<<que_suis_je()<<" : solving of problem "<<prob.que_suis_je()<<finl;
      while ((!convergence_pb)&&(compteur<nb_ite_max))
        {
          compteur++;
          prob.updateGivenFields();
          convergence_pb = Iterer_Pb(prob,compteur);
          Cout<<" "<<finl;;
        }
      if ((!convergence_pb)&&(compteur==nb_ite_max))
        {
          Cerr<<que_suis_je()<<" has not converged at t="<< temps_courant_ << " with dt =" << dt_<< finl;
          double rap =  sqrt(2.);
          facsec_    /= rap;
          dt_        /= rap;
          ok         =0;
          Cerr<<"We restart with dt_ =" << dt_ <<finl;
          prob.abortTimeStep();
          prob.initTimeStep(dt_);
// PL pour corriger plantage danbs U_in_var_impl
          const int nb_eqn=prob.nombre_d_equations();
          for(int ii=0; ii<nb_eqn; ii++)
            {
              Equation_base& eqn=prob.equation(ii);
              mettre_a_jour_equation(eqn,temps_courant_+dt_);
            }
// Fin
          Implicite_Multi_TimeStep_recommencer_pb(nb_valeurs_passees(),prob);
        }
      else
        {
          Cout<<"The problem "<<prob.que_suis_je()<<" has converged after "<<compteur<<" iterations."<<finl;
          ok=1;
        }
    }
// modification : prise en compte de la possibilite de modification du dt dans Itere_Pb
// cas du solveur pour compressible : division du pas de temps par 2
// si la convergence n'est pas atteinte en un nombre de pas de temps donne
// double temps = dt_ + temps_courant_;
  test_stationnaire(prob);
  converged=true;
  return true;
}
References Probleme_base::abortTimeStep(), Cerr, compteur, Cout, Schema_Temps_base::dt_, Probleme_base::equation(), Schema_Temps_base::facsec_, finl, Implicite_Multi_TimeStep_recommencer_pb(), Initialiser_Champs(), Probleme_base::initTimeStep(), Iterer_Pb(), mettre_a_jour_equation(), nb_ite_max, nb_valeurs_passees(), Probleme_base::nombre_d_equations(), Schema_Temps_base::pb_base(), Objet_U::que_suis_je(), Schema_Temps_base::temps_courant_, test_stationnaire(), and Probleme_base::updateGivenFields().
Iterer_Pb()
int Schema_Implicite_Multi_TimeStep_base::Iterer_Pb (Probleme_base & pb, int ite)
Definition at line 161 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  int  i               = 0, ok = 1;
  int  ii              = 0;
  bool convergence_pb  = true;
  bool convergence_eqn = false;
  int  drap = pb.is_dilatable();
  for(i=0; i<pb.nombre_d_equations(); i++)
    {
// reverse equation order if quasi-compressible medium
      if ((drap)&&(i<2))
        ii = 1-i;
      else
        ii = i;
      Equation_base& eqn               = pb.equation(ii);
      DoubleTab&     present           = eqn.inconnue().valeurs();
      DoubleTab&     futur             = eqn.inconnue().futur();
      double         temps             = temps_courant_+dt_;
      DoubleTab      stored_parameters;
      authorized_equation(eqn);
// imposer_cond_lim   sert pour la pression et pour les echanges entre pbs
      eqn.zone_Cl_dis()->imposer_cond_lim(eqn.inconnue(),temps_courant()+pas_de_temps());
      Cout<<"Solving equation "<<eqn.que_suis_je()<<finl;
      const DoubleTab& inut=futur;
      store_equation_parameters(eqn,stored_parameters);
      convergence_eqn = le_solveur.valeur().iterer_eqn(eqn,inut, present, dt_,ite, ok);
      modify_equation_parameters(eqn,stored_parameters);
      convergence_pb  = convergence_pb&&convergence_eqn;
      futur           = present;
      eqn.zone_Cl_dis()->imposer_cond_lim(eqn.inconnue(),temps_courant()+pas_de_temps());
      present         = futur;
// La ligne suivante realise:
// MAJ NS (donc MAJ inc)
// MAJ modele de turbulence donc k-eps
// eqn.inconnue().mettre_a_jour(temps);
// eqn.inconnue().reculer();
      changer_temps(eqn,temps);
    }
  return (convergence_pb==true);
}
References authorized_equation(), changer_temps(), Cout, Schema_Temps_base::dt_, Probleme_base::equation(), finl, Champ_Inc::futur(), Zone_Cl_dis::imposer_cond_lim(), Equation_base::inconnue(), Probleme_base::is_dilatable(), Solveur_Implicite_Base::iterer_eqn(), Schema_Implicite_base::le_solveur, modify_equation_parameters(), Probleme_base::nombre_d_equations(), Schema_Temps_base::pas_de_temps(), Objet_U::que_suis_je(), store_equation_parameters(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_courant_, Deriv_Solveur_Implicite_Base::valeur(), Champ_Inc::valeurs(), and Equation_base::zone_Cl_dis().
Referenced by faire_un_pas_de_temps_pb_couple(), and iterateTimeStep().
mettre_a_jour()
int Schema_Implicite_Multi_TimeStep_base::mettre_a_jour () override virtual
Mise a jour du temps courant (t+=dt)
et du nombre de pas de temps effectue (nb_pas_dt_++).
Returns
int
Signification: retourne toujours 1
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 155 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  Implicite_Multi_TimeStep_calcul_fac_sec(residu_,residu_old_,facsec_,facsec_max_,nb_ite_sans_accel_);
  return Schema_Temps_base::mettre_a_jour();
}
References Schema_Temps_base::facsec_, facsec_max_, Implicite_Multi_TimeStep_calcul_fac_sec(), Schema_Temps_base::mettre_a_jour(), nb_ite_sans_accel_, Schema_Temps_base::residu_, and residu_old_.
mettre_a_jour_equation()
virtual void Schema_Implicite_Multi_TimeStep_base::mettre_a_jour_equation (Equation_base & eqn, const double temps) pure virtual
Implemented in Schema_Adams_Moulton_base, and Schema_Backward_Differentiation_base.
Referenced by iterateTimeStep().
modifier_second_membre()
void Schema_Implicite_Multi_TimeStep_base::modifier_second_membre (const Equation_base & eqn, DoubleTab & secmem) override virtual
Reimplemented from Schema_Temps_base.
Definition at line 584 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  Cerr<<"Error in "<<que_suis_je()<<"::modifier_second_membre()"<<finl;
  Cerr<<que_suis_je()<<" is an implicit time scheme"<<finl;
  Cerr<<que_suis_je()<<"::modifier_second_membre() should not be used"<<finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
modifier_second_membre_full_impl()
void Schema_Implicite_Multi_TimeStep_base::modifier_second_membre_full_impl (const Equation_base & eqn, DoubleTab & secmem) virtual
Reimplemented in Schema_Adams_Moulton_base.
Definition at line 576 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  Cerr<<"Error in "<<que_suis_je()<<"::modifier_second_membre_full_impl()"<<finl;
  Cerr<<que_suis_je()<<" is an implicit time scheme"<<finl;
  Cerr<<que_suis_je()<<"::modifier_second_membre_full_impl() should not be used"<<finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
modify_equation_parameters()
virtual void Schema_Implicite_Multi_TimeStep_base::modify_equation_parameters (Equation_base & eqn, DoubleTab & stored_parameters) pure virtual
Implemented in Schema_Adams_Moulton_base, and Schema_Backward_Differentiation_base.
Referenced by faire_un_pas_de_temps_eqn_base(), and Iterer_Pb().
nb_pas_dt_seuil()
virtual int Schema_Implicite_Multi_TimeStep_base::nb_pas_dt_seuil () const pure virtual
Implemented in Schema_Adams_Moulton_order_2, Schema_Adams_Moulton_order_3, Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Referenced by ajouter_inertie(), Schema_Adams_Moulton_base::modifier_second_membre_full_impl(), Schema_Backward_Differentiation_base::modify_equation_parameters(), and Schema_Backward_Differentiation_base::store_equation_parameters().
nb_valeurs_futures()
int Schema_Implicite_Multi_TimeStep_base::nb_valeurs_futures () const override virtual
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1, donc 1.
Implements Schema_Temps_base.
Definition at line 107 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  return 1 ;
}
nb_valeurs_passees()
virtual int Schema_Implicite_Multi_TimeStep_base::nb_valeurs_passees () const pure virtual
Implemented in Schema_Adams_Moulton_order_2, Schema_Adams_Moulton_order_3, Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Referenced by Schema_Adams_Moulton_base::add_multi_timestep_data(), Schema_Backward_Differentiation_base::add_multi_timestep_data(), ajouter_inertie(), faire_un_pas_de_temps_eqn_base(), faire_un_pas_de_temps_pb_couple(), Initialiser_Champs(), iterateTimeStep(), Schema_Adams_Moulton_base::modifier_second_membre_full_impl(), Schema_Backward_Differentiation_base::modify_equation_parameters(), and test_stationnaire().
nb_valeurs_temporelles_effectives()
int Schema_Implicite_Multi_TimeStep_base::nb_valeurs_temporelles_effectives () const inline
Definition at line 98 of file Schema_Implicite_Multi_TimeStep_base.h.
{
  return nb_valeurs_temporelles()-1;
}
References Schema_Temps_base::nb_valeurs_temporelles().
Referenced by ajouter_inertie().
printOn()
Sortie & Schema_Implicite_Multi_TimeStep_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Schema_Implicite_base.
Reimplemented in Schema_Backward_Differentiation_base, Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Definition at line 31 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  return  Schema_Implicite_base::printOn(s);
}
References Schema_Implicite_base::printOn().
Referenced by Schema_Backward_Differentiation_base::printOn().
readOn()
Entree & Schema_Implicite_Multi_TimeStep_base::readOn (Entree & is) override protected virtual
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Schema_Implicite_base.
Reimplemented in Schema_Backward_Differentiation_base, Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Definition at line 39 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  nb_ite_max=100000;
  residu_old_=0;
  facsec_max_=DMAXFLOAT;
  Schema_Implicite_base::readOn(s);
  if(!le_solveur.non_nul())
    {
      Cerr << "A solver must be selected." << finl;
      Cerr << "Syntax : " << finl
           << "Solveur solver_name [ solver parameters ] " << finl;
      exit();
    }
  if (diffusion_implicite())
    {
      Cerr << "diffusion_implicite option cannot be used with an implicit time scheme." << finl;
      exit();
    }
  return s;
}
References Cerr, Schema_Temps_base::diffusion_implicite(), DMAXFLOAT, Process::exit(), facsec_max_, finl, Schema_Implicite_base::le_solveur, nb_ite_max, O_U_Ptr::non_nul(), Schema_Implicite_base::readOn(), and residu_old_.
Referenced by Schema_Adams_Moulton_base::readOn(), and Schema_Backward_Differentiation_base::readOn().
reprendre()
int Schema_Implicite_Multi_TimeStep_base::reprendre (Entree & is) override virtual
Reprise (lecture) du temps courant et du nombre de pas de
temps effectues a partir d'un flot d'entree.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 483 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  Nom nom_fichier(nom_du_cas());
  nom_fichier+=".dt_ev";
  LecFicDiffuse test;
  if (!test.ouvrir(nom_fichier))
    {
      Cerr << "*****************************************" << finl;
      Cerr << "***************** WARNING ***************" << finl;
      Cerr << "File " << nom_fichier << " does not exist." << finl;
      Cerr << "In order to restart a calculation carried out with an implicit time scheme" << finl;
      Cerr << "it is preferable to re-read the .dt_ev file to pick up some informations" << finl;
      Cerr << "and in particular the facsec of the previous calculation." << finl;
      Cerr << "TRUST will use facsec= " << facsec_ << "." << finl;
      Cerr << "Else specify the facsec wanted value in your data file." << finl;
      Cerr << "*****************************************" << finl;
      return 1;
    }
// Reprise du facsec et du residu dans le fichier .dt_ev s'il existe
  double facsec_lu=1.;
  double residu_lu=0;
  double facsec_lu_old;
// Test ouverture du fichier
  if (je_suis_maitre())
    {
      EFichier fichier;
      fichier.ouvrir(nom_fichier);
      Nom chaine;
      double temps=0;
      double dt;
      std::string ligne;
// Si en tete on lit
      fichier >> chaine;
      if (chaine=="#")
        {
// On lit la ligne complete
          std::getline(fichier.get_ifstream(), ligne);
        } //!< Sinon on reouvre
      else
        {
          fichier.ouvrir(nom_fichier);
        }
// Recherche du pas de temps precedant tinit_
      fichier >> temps;
      while (!fichier.eof() && temps<tinit_)
        {
          facsec_lu_old = facsec_lu;
          fichier >> dt;
          fichier >> facsec_lu;
          fichier >> residu_lu;
// On lit le reste de la ligne
          std::getline(fichier.get_ifstream(), ligne);
          fichier >> temps;
          if (facsec_lu_old != facsec_lu)
            {
              residu_old_ = residu_lu;
              nb_ite_sans_accel_ = 1;
            }
          nb_ite_sans_accel_++;
        }
    }
  envoyer_broadcast(facsec_lu, 0 /* pe source */);
  envoyer_broadcast(residu_lu, 0 /* pe source */);
  envoyer_broadcast(nb_ite_sans_accel_, 0 /* pe source */);
  envoyer_broadcast(residu_old_, 0 /* pe source */);
// On prend le facsec lu uniquement s'il est entre les
// bornes specifiees dans le jeu de donnees
// En effet, on peut faire un calcul explicite puis une reprise en implicite
  residu_ = residu_lu;
  if (facsec_lu>=facsec_)
    {
      if (facsec_lu<=facsec_max_)
        facsec_ = facsec_lu;
      else
        facsec_ = facsec_max_;
      if (Process::je_suis_maitre()) Cerr << "Facsec after reading in " << nom_fichier << " : " << facsec_ << finl;
      if (Process::je_suis_maitre()) Cerr << "Residu after reading in " << nom_fichier << " : " << residu_ << finl;
    }
  else
    {
      if (Process::je_suis_maitre())
        {
          Cerr << "The readen facsec in " << nom_fichier << " : " << facsec_lu << finl;
          Cerr << "is not used since it is lower than the facsec from the data set : " << facsec_ << finl;
        }
    }
  return 1;
}
References Cerr, envoyer_broadcast(), Entree_Fichier_base::eof(), Schema_Temps_base::facsec_, facsec_max_, finl, Entree_Fichier_base::get_ifstream(), Process::je_suis_maitre(), nb_ite_sans_accel_, Objet_U::nom_du_cas(), nom_fichier(), Entree_Fichier_base::ouvrir(), Schema_Temps_base::residu_, residu_old_, test(), and Schema_Temps_base::tinit_.
residu_old()
const double & Schema_Implicite_Multi_TimeStep_base::residu_old () const inline
Definition at line 78 of file Schema_Implicite_Multi_TimeStep_base.h.
  {
    return residu_old_ ;
  };
References residu_old_.
self_cast() [1/2]
const Schema_Implicite_Multi_TimeStep_base & Schema_Implicite_Multi_TimeStep_base::self_cast (const Objet_U & r) static
Definition at line 26 of file Schema_Implicite_Multi_TimeStep_base.cpp.
self_cast() [2/2]
Schema_Implicite_Multi_TimeStep_base & Schema_Implicite_Multi_TimeStep_base::self_cast (Objet_U & r) static
Definition at line 26 of file Schema_Implicite_Multi_TimeStep_base.cpp.
set_param()
void Schema_Implicite_Multi_TimeStep_base::set_param (Param & param) override virtual
Reimplemented from Schema_Implicite_base.
Definition at line 84 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  param.ajouter("max_iter_implicite",&nb_ite_max);
  param.ajouter("facsec_max", &facsec_max_);
  Schema_Implicite_base::set_param(param);
}
References Param::ajouter(), facsec_max_, nb_ite_max, and Schema_Implicite_base::set_param().
store_equation_parameters()
virtual void Schema_Implicite_Multi_TimeStep_base::store_equation_parameters (Equation_base & eqn, DoubleTab & stored_parameters) pure virtual
Implemented in Schema_Adams_Moulton_base, and Schema_Backward_Differentiation_base.
Referenced by faire_un_pas_de_temps_eqn_base(), and Iterer_Pb().
temps_defaut()
double Schema_Implicite_Multi_TimeStep_base::temps_defaut () const override virtual
Renvoie le le temps le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : t(n+1)
Implements Schema_Temps_base.
Definition at line 125 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  return temps_courant()+pas_de_temps();
}
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
temps_futur()
double Schema_Implicite_Multi_TimeStep_base::temps_futur (int i) const override virtual
Renvoie le le temps a la i-eme valeur future.
Ici : t(n+1)
Implements Schema_Temps_base.
Definition at line 115 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  assert(i==1);
  return temps_courant()+pas_de_temps();
}
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
test_stationnaire()
void Schema_Implicite_Multi_TimeStep_base::test_stationnaire (Probleme_base & pb)
Definition at line 210 of file Schema_Implicite_Multi_TimeStep_base.cpp.
{
  int i = 0;
  int j = 0;
  for(i=0; i<pb.nombre_d_equations(); i++)
    {
// treatement of time convergency
      DoubleTab& passe = pb.equation(i).inconnue().passe();
      DoubleTab& present = pb.equation(i).inconnue().valeurs();
      DoubleTab& futur = pb.equation(i).inconnue().futur();
      futur    = present;
      pb.equation(i).zone_Cl_dis()->imposer_cond_lim(pb.equation(i).inconnue(),temps_courant()+pas_de_temps());
      present -= passe;
      present /= dt_;
      update_critere_statio(present, pb.equation(i));
      update_time_derivative(pb.equation(i),present);
      for (j=0; j<nb_valeurs_passees(); j++)
        {
          pb.equation(i).inconnue().passe(j) = pb.equation(i).inconnue().passe(j+1);
        }
    }
}
References Schema_Temps_base::dt_, Probleme_base::equation(), Champ_Inc::futur(), Zone_Cl_dis::imposer_cond_lim(), Equation_base::inconnue(), nb_valeurs_passees(), Probleme_base::nombre_d_equations(), Schema_Temps_base::pas_de_temps(), Champ_Inc::passe(), Schema_Temps_base::temps_courant(), Schema_Temps_base::update_critere_statio(), update_time_derivative(), Champ_Inc::valeurs(), and Equation_base::zone_Cl_dis().
Referenced by faire_un_pas_de_temps_pb_couple(), and iterateTimeStep().
update_time_derivative()
virtual void Schema_Implicite_Multi_TimeStep_base::update_time_derivative (Equation_base & eqn, const DoubleTab & data) pure virtual
Implemented in Schema_Adams_Moulton_base, and Schema_Backward_Differentiation_base.
Referenced by faire_un_pas_de_temps_eqn_base(), and test_stationnaire().
Member Data Documentation
facsec_max_
double Schema_Implicite_Multi_TimeStep_base::facsec_max_ protected
Definition at line 94 of file Schema_Implicite_Multi_TimeStep_base.h.
Referenced by Schema_Adams_Moulton_order_3::compute_adams_moulton_coefficients(), mettre_a_jour(), readOn(), reprendre(), and set_param().
info_obj
const Type_info Schema_Implicite_Multi_TimeStep_base::info_obj static
Definition at line 30 of file Schema_Implicite_Multi_TimeStep_base.h.
nb_ite_max
int Schema_Implicite_Multi_TimeStep_base::nb_ite_max protected
Definition at line 93 of file Schema_Implicite_Multi_TimeStep_base.h.
Referenced by faire_un_pas_de_temps_eqn_base(), faire_un_pas_de_temps_pb_couple(), iterateTimeStep(), readOn(), and set_param().
nb_ite_sans_accel_
int Schema_Implicite_Multi_TimeStep_base::nb_ite_sans_accel_ protected
Definition at line 95 of file Schema_Implicite_Multi_TimeStep_base.h.
Referenced by mettre_a_jour(), and reprendre().
residu_old_
double Schema_Implicite_Multi_TimeStep_base::residu_old_ protected
Definition at line 94 of file Schema_Implicite_Multi_TimeStep_base.h.
Referenced by mettre_a_jour(), readOn(), reprendre(), and residu_old().
The documentation for this class was generated from the following files:
src/Kernel/Schemas_Temps/Schema_Implicite_Multi_TimeStep_base.h
src/Kernel/Schemas_Temps/Schema_Implicite_Multi_TimeStep_base.cpp