TRUST: Champ_som_lu Class Reference
Champ_som_lu Class Reference
#include <Champ_som_lu.h>
Public Member Functions
Champ_som_lu ()
~Champ_som_lu ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Champ_base & affecter (const Champ_base &ch)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
DoubleVect & valeur_a (const DoubleVect &positions, DoubleTab &valeurs) const
Renvoie la valeur en un point.
DoubleVect & valeur_a (const DoubleVect &positions, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
DoubleVect & valeur_a (const DoubleVect &positions, DoubleVect &valeurs, int ncomp) const
DoubleVect & valeur_a (const DoubleVect &positions, DoubleVect &valeurs, int le_poly, int ncomp) const
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_som_lu & self_cast (Objet_U &)
static const Champ_som_lu & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a:
Champ_base::printOn(Sortie&)
virtual Entree & readOn (Entree &)
Simple appel a:
Champ_base::readOn(Entree&)
Protected Attributes
Ref_Domaine mon_domaine
double tolerance_
Detailed Description
Definition at line 36 of file Champ_som_lu.h.
Constructor & Destructor Documentation
Champ_som_lu::Champ_som_lu ()
Definition at line 30 of file Champ_som_lu.cpp.
Champ_som_lu::~Champ_som_lu ()
Definition at line 30 of file Champ_som_lu.cpp.
Member Function Documentation
Champ_base & Champ_som_lu::affecter (const Champ_base & ch)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
Returns:
Champ_base&
Signification: le resultat de l'affectation (*this)
Contraintes:
Reimplemented from Champ_base.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 55 of file Champ_som_lu.cpp.
References Champ_base::affecter_erreur().
{
  Champ_base::affecter_erreur();
  return *this;
}
Objet_U * Champ_som_lu::cree_instance () [static]
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 30 of file Champ_som_lu.cpp.
int Champ_som_lu::duplique () const [virtual]
Implements Champ_Don_base.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 30 of file Champ_som_lu.cpp.
const Type_info * Champ_som_lu::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 30 of file Champ_som_lu.cpp.
const Type_info * Champ_som_lu::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 30 of file Champ_som_lu.cpp.
Sortie & Champ_som_lu::printOn (Sortie & os) const [protected, virtual]
Simple appel a:
Champ_base::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Don_base.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 32 of file Champ_som_lu.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Internal error: Champ_som_lu::printOn not coded" << finl;
  exit();
  return os;
}
Entree & Champ_som_lu::readOn (Entree & is) [protected, virtual]
Simple appel a:
Champ_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
< nombre de composantes du champ
< tolerance en metres pour la recherche des coordonnees
< nom du fichier a lire
Reimplemented from Champ_Don_base.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 39 of file Champ_som_lu.cpp.
References Field_base::fixer_nb_comp(), Champ_implementation_P1::init_from_file(), mon_domaine, Interprete::objet(), ref_cast, tolerance_, and Champ_Don_base::valeurs_.
{
  int nbcomp;
  Nom nom;
  is >> nom;
  const Domaine& dom = ref_cast(Domaine, Interprete::objet(nom));
  is >> nbcomp; //!< nombre de composantes du champ
  is >> tolerance_; //!< tolerance en metres pour la recherche des coordonnees
  is >> nom; //!< nom du fichier a lire
  mon_domaine = dom;
  LecFicDiffuse file(nom);
  fixer_nb_comp(nbcomp);
  Champ_implementation_P1::init_from_file(valeurs_, dom, nbcomp, tolerance_, file);
  return is;
}
Champ_som_lu & Champ_som_lu::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Don_base.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 30 of file Champ_som_lu.cpp.
const Champ_som_lu & Champ_som_lu::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Don_base.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 30 of file Champ_som_lu.cpp.
unsigned Champ_som_lu::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 30 of file Champ_som_lu.cpp.
DoubleVect & Champ_som_lu::valeur_a (const DoubleVect & positions, DoubleVect & valeurs, int ncomp) const
Reimplemented in Champ_som_lu_VDF.
Definition at line 88 of file Champ_som_lu.cpp.
References Cerr, Process::exit(), finl, and Field_base::nb_compo_.
{
  if (ncomp > nb_compo_)
    {
      Cerr << "Error TRUST in Champ_Don_lu::valeur_a()" << finl;
      Cerr << "the integer ncomp is upper than the number of field components" << finl;
      exit();
    }
// const DoubleTab& ch = valeurs();
// a coder
  assert(0);
  return val;
}
DoubleVect & Champ_som_lu::valeur_a (const DoubleVect & positions, DoubleVect & valeurs, int le_poly, int ncomp) const
Reimplemented in Champ_som_lu_VDF.
Definition at line 110 of file Champ_som_lu.cpp.
References Process::exit(), and valeur_a().
{
// a coder
  exit();
  throw;
  return valeur_a(positions, tab_valeurs, le_poly, ncomp);
}
DoubleVect & Champ_som_lu::valeur_a (const DoubleVect & positions, DoubleTab & valeurs) const
Renvoie la valeur en un point.
Reimplemented in Champ_som_lu_VDF.
Definition at line 63 of file Champ_som_lu.cpp.
References Cerr, Zone::chercher_elements(), finl, mon_domaine, and valeur_aux_elems().
Referenced by valeur_a().
{
  Cerr << "We are in Champ_som_lu::valeur_a(const DoubleVect& positions,DoubleTab& valeurs) " << finl;
  const Zone& la_zone = mon_domaine->zone(0);
  IntVect le_poly(1);
  la_zone.chercher_elements(positions,le_poly);
  DoubleTab positions2;
  positions2=positions;
  return valeur_aux_elems(positions2,le_poly[0],tab_valeurs);
}
DoubleVect & Champ_som_lu::valeur_a (const DoubleVect & pos, DoubleVect & les_valeurs) const [virtual]
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
Returns:
reference a "valeurs"
Reimplemented from Champ_base.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 75 of file Champ_som_lu.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Wa are in Champ_som_lu::valeur_a(const DoubleVect& positions,DoubleVect& valeurs) " << finl;
  assert(0);
  Cerr << "It would be better to call Champ_som_lu::valeur_a with Valeur DoubleVect" << finl;
  exit();
  return tab_valeurs;
}
DoubleTab & Champ_som_lu::valeur_aux (const DoubleTab & positions, DoubleTab & les_valeurs) const [virtual]
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 122 of file Champ_som_lu.cpp.
References Zone::chercher_elements(), mon_domaine, Zone::nb_elem(), and valeur_aux_elems().
{
  const Zone& la_zone = mon_domaine->zone(0);
// B.M.: IntVect obligatoire pour l'instant a cause du prototype de valeur_aux_elems
  IntVect les_polys(la_zone.nb_elem());
  la_zone.chercher_elements(positions,les_polys);
  return valeur_aux_elems(positions,les_polys,val);
}
DoubleVect & Champ_som_lu::valeur_aux_compo (const DoubleTab & pos, DoubleVect & les_valeurs, int compo) const [virtual]
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
Returns:
reference au tableau les_valeurs
Reimplemented from Champ_base.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 135 of file Champ_som_lu.cpp.
References Cerr, Zone::chercher_elements(), finl, mon_domaine, Zone::nb_elem(), and valeur_aux_elems_compo().
{
  const Zone& la_zone = mon_domaine->zone(0);
// B.M.: IntVect obligatoire pour l'instant a cause du prototype de valeur_aux_elems
  IntVect les_polys(la_zone.nb_elem());
  Cerr << "Nb elem : " << la_zone.nb_elem() << finl;
  Cerr << "Lespolys : " << les_polys.size_array() << finl;
  la_zone.chercher_elements(positions,les_polys);
  Cerr << "Nb elem : " << la_zone.nb_elem() << finl;
  Cerr << "Lespolys : " << les_polys.size_array() << finl;
  return valeur_aux_elems_compo(positions,les_polys,tab_valeurs,ncomp);
}
DoubleTab & Champ_som_lu::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 153 of file Champ_som_lu.cpp.
References Cerr, DoubleTab::dimension(), est_egal(), Process::exit(), finl, mon_domaine, Field_base::nb_compo_, DoubleTab::nb_dim(), Zone::nb_som_elem(), DoubleTab::resize(), ArrOfInt::size_array(), Zone::sommet_elem(), and Champ_Don_base::valeurs().
Referenced by valeur_a(), and valeur_aux().
{
  DoubleTab valprov;
  if (val2.nb_dim() == 1)
    {
      assert(val2.dimension(0) == les_polys.size_array());
      assert(nb_compo_ == 1);
      valprov.resize(val2.dimension(0),1);
    }
  else if (val2.nb_dim() == 2)
    {
      assert(val2.dimension(0) == les_polys.size_array());
      assert(val2.dimension(1) == nb_compo_);
    }
  else
    {
      Cerr << "Error TRUST in Champ_som_lu::valeur_aux_elems()" << finl;
      Cerr << "The DoubleTab val has more than 2 entries" << finl;
      exit();
    }
  DoubleTab& val=(val2.nb_dim() ==1?valprov:val2);
  const DoubleTab& coord=mon_domaine->coord_sommets();
  const Zone& zone=mon_domaine->zone(0);
  int le_poly;
  {
    const DoubleTab& ch = valeurs();
    for(int rang_poly=0; rang_poly<les_polys.size_array(); rang_poly++)
      {
        le_poly=les_polys(rang_poly);
        if (le_poly == -1)
          for(int ncomp=0; ncomp<nb_compo_; ncomp++)
            val(rang_poly, ncomp) = 0;
        else if (zone.nb_som_elem() == 2)
          {
            for(int ncomp=0; ncomp<nb_compo_; ncomp++)
              {
                int som1=zone.sommet_elem(le_poly , 0 );
                int som2=zone.sommet_elem(le_poly , 1 );
                double xmin=coord(som1,0);
                double xmax=coord(som2,0);
                double ymin=coord(som1,1);
                double ymax=coord(som2,1);
                double zmin=coord(som1,2);
                double zmax=coord(som2,2);
                double hx=xmax - xmin;
                double hy=ymax - ymin;
                double hz=zmax - zmin;
                double dd = sqrt(hx*hx+hy*hy+hz*hz);
                double dxmax,dxmin,dymax,dymin,dzmax,dzmin;
                dxmax = (xmax-positions(rang_poly,0));
                dxmin = (positions(rang_poly,0)-xmin);
                dymax = (ymax-positions(rang_poly,1));
                dymin = (positions(rang_poly,1)-ymin);
                dzmax = (zmax-positions(rang_poly,2));
                dzmin = (positions(rang_poly,2)-zmin);
                if (est_egal(hx,0.))
                  {
                    dxmin = 1.;
                    dxmax = 1.;
                  }
                if (est_egal(hy,0.))
                  {
                    dymin = 1.;
                    dymax = 1.;
                  }
                if (est_egal(hz,0.))
                  {
                    dzmin = 1.;
                    dzmax = 1.;
                  }
                val(rang_poly, ncomp) =
                  ch(som1,ncomp)*dxmax*dymax*dzmax;
                val(rang_poly, ncomp) +=
                  ch(som2,ncomp)*dxmin*dymin*dzmin;
                val(rang_poly, ncomp)/=dd;
              }
          }
        else
          {
            for(int ncomp=0; ncomp<nb_compo_; ncomp++)
              {
                int som1=zone.sommet_elem(le_poly , 0 );
                int som2=zone.sommet_elem(le_poly , 1 );
                int som3=zone.sommet_elem(le_poly , 2 );
                int som4=zone.sommet_elem(le_poly , 3 );
                int som5=zone.sommet_elem(le_poly , 4 );
                int som6=zone.sommet_elem(le_poly , 5 );
                int som7=zone.sommet_elem(le_poly , 6 );
                int som8=zone.sommet_elem(le_poly , 7 );
                double xmin=coord(som1,0);
                double xmax=coord(som2,0);
                double ymin=coord(som1,1);
                double ymax=coord(som3,1);
                double zmin=coord(som1,2);
                double zmax=coord(som5,2);
                double hx=xmax - xmin;
                double hy=ymax - ymin;
                double hh=zmax - zmin;
                val(rang_poly, ncomp) =
                  ch(som1,ncomp)*(xmax-positions(rang_poly,0))
                  *(ymax-positions(rang_poly,1))*(zmax-positions(rang_poly,2));
                val(rang_poly, ncomp) +=ch(som2,ncomp)*(positions(rang_poly,0)-xmin)
                                        *(ymax-positions(rang_poly,1))*(zmax-positions(rang_poly,2));
                val(rang_poly, ncomp) +=ch(som3,ncomp)*(xmax-positions(rang_poly,0))
                                        *(positions(rang_poly,1)-ymin)*(zmax-positions(rang_poly,2));
                val(rang_poly, ncomp) +=ch(som4,ncomp)*(positions(rang_poly,0)-xmin)
                                        *(positions(rang_poly,1)-ymin)*(zmax-positions(rang_poly,2));
                val(rang_poly, ncomp) += ch(som5,ncomp)*(xmax-positions(rang_poly,0))
                                         *(ymax-positions(rang_poly,1))*(positions(rang_poly,2)-zmin);
                val(rang_poly, ncomp) +=ch(som6,ncomp)*(positions(rang_poly,0)-xmin)
                                        *(ymax-positions(rang_poly,1))*(positions(rang_poly,2)-zmin);
                val(rang_poly, ncomp) +=ch(som7,ncomp)*(xmax-positions(rang_poly,0))
                                        *(positions(rang_poly,1)-ymin)*(positions(rang_poly,2)-zmin);
                val(rang_poly, ncomp) +=ch(som8,ncomp)*(positions(rang_poly,0)-xmin)
                                        *(positions(rang_poly,1)-ymin)*(positions(rang_poly,2)-zmin);
                val(rang_poly, ncomp)/=(hx*hy*hh);
              }
          }
      }
  }
  if (val2.nb_dim() ==1)
    for (int ii=0; ii<val2.dimension(0); ii++) val2(ii)=valprov(ii,0);
  return val2;
}
DoubleVect & Champ_som_lu::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 314 of file Champ_som_lu.cpp.
References mon_domaine, DoubleVect::size(), ArrOfInt::size_array(), Zone::sommet_elem(), and Champ_Don_base::valeurs().
Referenced by valeur_aux_compo().
{
  assert(val.size() == les_polys.size_array());
  const DoubleTab& coord=mon_domaine->coord_sommets();
  const Zone& zone=mon_domaine->zone(0);
  int le_poly;
  const DoubleTab& ch = valeurs();
  for(int rang_poly=0; rang_poly<les_polys.size_array(); rang_poly++)
    {
      le_poly=les_polys(rang_poly);
      if (le_poly == -1)
        val(rang_poly) = 0;
      else
        {
          int som1=zone.sommet_elem(le_poly , 0 );
          int som2=zone.sommet_elem(le_poly , 1 );
          int som3=zone.sommet_elem(le_poly , 2 );
          int som4=zone.sommet_elem(le_poly , 3 );
          int som5=zone.sommet_elem(le_poly , 4 );
          int som6=zone.sommet_elem(le_poly , 5 );
          int som7=zone.sommet_elem(le_poly , 6 );
          int som8=zone.sommet_elem(le_poly , 7 );
          double xmin=coord(som1,0);
          double xmax=coord(som2,0);
          double ymin=coord(som1,1);
          double ymax=coord(som3,1);
          double zmin=coord(som1,2);
          double zmax=coord(som5,2);
          double hx=xmax - xmin;
          double hy=ymax - ymin;
          double hh=zmax - zmin;
          val(rang_poly) =
            ch(som1,ncomp)*(xmax-positions(rang_poly,0))
            *(ymax-positions(rang_poly,1))*(zmax-positions(rang_poly,2));
          val(rang_poly) +=ch(som2,ncomp)*(positions(rang_poly,0)-xmin)
                           *(ymax-positions(rang_poly,1))*(zmax-positions(rang_poly,2));
          val(rang_poly) +=ch(som3,ncomp)*(xmax-positions(rang_poly,0))
                           *(positions(rang_poly,1)-ymin)*(zmax-positions(rang_poly,2));
          val(rang_poly) +=ch(som4,ncomp)*(positions(rang_poly,0)-xmin)
                           *(positions(rang_poly,1)-ymin)*(zmax-positions(rang_poly,2));
          val(rang_poly) += ch(som5,ncomp)*(xmax-positions(rang_poly,0))
                            *(ymax-positions(rang_poly,1))*(positions(rang_poly,2)-zmin);
          val(rang_poly) +=ch(som6,ncomp)*(positions(rang_poly,0)-xmin)
                           *(ymax-positions(rang_poly,1))*(positions(rang_poly,2)-zmin);
          val(rang_poly) +=ch(som7,ncomp)*(xmax-positions(rang_poly,0))
                           *(positions(rang_poly,1)-ymin)*(positions(rang_poly,2)-zmin);
          val(rang_poly) +=ch(som8,ncomp)*(positions(rang_poly,0)-xmin)
                           *(positions(rang_poly,1)-ymin)*(positions(rang_poly,2)-zmin);
          val(rang_poly)/=(hx*hy*hh);
        }
    }
  return val;
}
Member Data Documentation
const Type_info Champ_som_lu::info_obj [static]
Reimplemented from Champ_Don_base.
Reimplemented in Champ_som_lu_VDF, and Champ_som_lu_VEF.
Definition at line 38 of file Champ_som_lu.h.
Ref_Domaine Champ_som_lu::mon_domaine [protected]
Definition at line 50 of file Champ_som_lu.h.
Referenced by readOn(), Champ_som_lu_VDF::valeur_a(), valeur_a(), Champ_som_lu_VEF::valeur_aux(), Champ_som_lu_VDF::valeur_aux(), valeur_aux(), Champ_som_lu_VEF::valeur_aux_compo(), Champ_som_lu_VDF::valeur_aux_compo(), valeur_aux_compo(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_som_lu_VDF::valeur_aux_elems(), valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems_compo(), Champ_som_lu_VDF::valeur_aux_elems_compo(), and valeur_aux_elems_compo().
double Champ_som_lu::tolerance_ [protected]
Definition at line 51 of file Champ_som_lu.h.
Referenced by readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs_dis/Champ_som_lu.h
src/Kernel/Champs_dis/Champ_som_lu.cpp