TRUST: Polygone_CoviMAC Class Reference
Polygone_CoviMAC Class Reference
: class Polygone_CoviMAC
<Description of class Polygone_CoviMAC>
#include <Polygone_CoviMAC.h>
Public Member Functions
Polygone_CoviMAC ()
~Polygone_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const
remplit le tableau face_normales dans la Zone_CoviMAC
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Polygone_CoviMAC & self_cast (Objet_U &)
static const Polygone_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
: class Polygone_CoviMAC
<Description of class Polygone_CoviMAC>
Definition at line 36 of file Polygone_CoviMAC.h.
Constructor & Destructor Documentation
Polygone_CoviMAC::Polygone_CoviMAC ()
Definition at line 28 of file Polygone_CoviMAC.cpp.
Polygone_CoviMAC::~Polygone_CoviMAC ()
Definition at line 28 of file Polygone_CoviMAC.cpp.
Member Function Documentation
Objet_U * Polygone_CoviMAC::cree_instance () [static]
Definition at line 28 of file Polygone_CoviMAC.cpp.
int Polygone_CoviMAC::duplique () const [virtual]
Implements Elem_CoviMAC_base.
Definition at line 28 of file Polygone_CoviMAC.cpp.
const Type_info * Polygone_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_CoviMAC_base.
Definition at line 28 of file Polygone_CoviMAC.cpp.
const Type_info * Polygone_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_CoviMAC_base.
Definition at line 28 of file Polygone_CoviMAC.cpp.
void Polygone_CoviMAC::normale (int num_Face, DoubleTab & Face_normales, const IntTab & Face_sommets, const IntTab & Face_voisins, const IntTab & elem_faces, const Zone & zone_geom) const [virtual]
remplit le tableau face_normales dans la Zone_CoviMAC
Implements Elem_CoviMAC_base.
Definition at line 42 of file Polygone_CoviMAC.cpp.
References Domaine::coord_sommets(), Zone::domaine(), ref_cast, Zone::type_elem(), and Deriv_Elem_geom_base::valeur().
{
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
  double x1,y1;
  double nx,ny;
  int n0 = Face_sommets(num_Face,0);
  int n1 = Face_sommets(num_Face,1);
  x1 = les_coords(n0,0)-les_coords(n1,0);
  y1 = les_coords(n0,1)-les_coords(n1,1);
  nx = -y1;
  ny = x1;
  /* DoubleTab xp;
  zone_geom.Zone::calculer_centres_gravite(xp);
  */
  /*
      int no3;
  int f0;
  // Orientation de la normale de elem1 vers elem2
  // pour cela recherche du sommet de elem1 qui n'est pas sur la Face
  int elem1 = Face_voisins(num_Face,0);
  if ( (f0 = elem_faces(elem1,0)) == num_Face )
    f0 = elem_faces(elem1,1);
  if ( (no3 = Face_sommets(f0,0)) != n0 && no3 != n1 )
    ;
  else
    no3 = Face_sommets(f0,1);
  x1 = les_coords(no3,0) - les_coords(n0,0);
  y1 = les_coords(no3,1) - les_coords(n0,1);
  double dot=(nx*x1+ny*y1);
  */
  int elem1=Face_voisins(num_Face,0);
  DoubleVect xp;
  ref_cast(Poly_geom_base,zone_geom.type_elem().valeur()).calculer_un_centre_gravite(elem1,xp);
  x1=xp(0)-les_coords(n0,0);
  y1=xp(1)-les_coords(n0,1);
  double dot=(nx*x1+ny*y1);
  if ( (dot) > 0 )
    {
      Face_normales(num_Face,0) = - nx;
      Face_normales(num_Face,1) = - ny;
    }
  else
    {
      assert(dot !=0);
      Face_normales(num_Face,0) = nx;
      Face_normales(num_Face,1) = ny;
    }
}
Sortie & Polygone_CoviMAC::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Elem_CoviMAC_base.
Definition at line 30 of file Polygone_CoviMAC.cpp.
References Objet_U::que_suis_je().
{
  return os << que_suis_je() << "\n";
}
Entree & Polygone_CoviMAC::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Elem_CoviMAC_base.
Definition at line 35 of file Polygone_CoviMAC.cpp.
{
  Elem_CoviMAC_base::readOn( is );
  return is;
}
Polygone_CoviMAC & Polygone_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Elem_CoviMAC_base.
Definition at line 28 of file Polygone_CoviMAC.cpp.
const Polygone_CoviMAC & Polygone_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Elem_CoviMAC_base.
Definition at line 28 of file Polygone_CoviMAC.cpp.
unsigned Polygone_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 28 of file Polygone_CoviMAC.cpp.
Member Data Documentation
const Type_info Polygone_CoviMAC::info_obj [static]
Reimplemented from Elem_CoviMAC_base.
Definition at line 39 of file Polygone_CoviMAC.h.
The documentation for this class was generated from the following files:
src/CoviMAC/Zones/Polygone_CoviMAC.h
src/CoviMAC/Zones/Polygone_CoviMAC.cpp