TRUST: IntTab_parts Class Reference
IntTab_parts Class Reference
#include <ConstDoubleTab_parts.h>
Public Member Functions
IntTab_parts ()
IntTab_parts (IntVect &)
void initialize (IntVect &)
void reset ()
IntTab & operator[] (int i)
const IntTab & operator[] (int i) const
int size () const
Private Member Functions
IntTab_parts & operator= (const IntTab_parts &)
Interdit !
IntTab_parts (const IntTab_parts &)
Interdit !
Private Attributes
Vect_IntTab parts_
Detailed Description
Definition at line 112 of file ConstDoubleTab_parts.h.
Constructor & Destructor Documentation
IntTab_parts::IntTab_parts () [inline]
Definition at line 115 of file ConstDoubleTab_parts.h.
{};
IntTab_parts::IntTab_parts (IntVect & vect)
Definition at line 220 of file ConstDoubleTab_parts.cpp.
References init_parts(), and parts_.
{
  init_parts(vect, parts_, (IntTab*) 0);
}
IntTab_parts::IntTab_parts (const IntTab_parts &) [private]
Interdit !
Definition at line 302 of file ConstDoubleTab_parts.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Internal error: call to copy constructor IntTab_parts::IntTab_parts(const IntTab_parts &) is forbidden" << finl;
  Process::exit();
}
Member Function Documentation
void IntTab_parts::initialize (IntVect & vect)
Definition at line 225 of file ConstDoubleTab_parts.cpp.
References init_parts(), parts_, and reset().
{
  reset();
  init_parts(vect, parts_, (IntTab*) 0);
}
IntTab_parts & IntTab_parts::operator= (const IntTab_parts &) [private]
Interdit !
Definition at line 294 of file ConstDoubleTab_parts.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Internal error: call to IntTab_parts::operator=(const IntTab_parts &) is forbidden" << finl;
  Process::exit();
  return *this;
}
const IntTab& IntTab_parts::operator[] (int i) const [inline]
Definition at line 126 of file ConstDoubleTab_parts.h.
  {
    return parts_[i];
  }
IntTab& IntTab_parts::operator[] (int i) [inline]
Definition at line 121 of file ConstDoubleTab_parts.h.
  {
    return parts_[i];
  }
void IntTab_parts::reset ()
Definition at line 231 of file ConstDoubleTab_parts.cpp.
References vect_impl::dimensionner_force(), and parts_.
Referenced by initialize().
{
  parts_.dimensionner_force(0);
}
int IntTab_parts::size () const [inline]
Definition at line 130 of file ConstDoubleTab_parts.h.
References IntVect::size().
  {
    return parts_.size();
  }
Member Data Documentation
Vect_IntTab IntTab_parts::parts_ [private]
Definition at line 141 of file ConstDoubleTab_parts.h.
Referenced by initialize(), IntTab_parts(), and reset().
The documentation for this class was generated from the following files:
src/Kernel/Math/ConstDoubleTab_parts.h
src/Kernel/Math/ConstDoubleTab_parts.cpp