TRUST: Prisme Class Reference
Prisme Class Reference
Classe Prisme
Cette represente l'element geometrique Prisme.
Un prisme est un polyedre ayant 5 faces, 6 sommets et deux types
de face:
2 triangles a 3 sommets
3 quadrangles a 4 sommets.
#include <Prisme.h>
Public Member Functions
Prisme ()
~Prisme ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int face_sommet (int i, int j) const override
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
int face_sommet0 (int i) const
Renvoie le numero du i-ieme sommet de la face 0.
int face_sommet1 (int i) const
Renvoie le numero du i-ieme sommet de la face 1.
int face_sommet2 (int i) const
Renvoie le numero du i-ieme sommet de la face 2.
int face_sommet3 (int i) const
Renvoie le numero du i-ieme sommet de la face 3.
int face_sommet4 (int i) const
Renvoie le numero du i-ieme sommet de la face 4.
int nb_som () const override
Renvoie le nombre de sommets d'un Prisme: 6.
int nb_faces (int=0) const override
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
Un Prisme a 2 types de faces: quadrangle ou triangle.
int nb_som_face (int=0) const override
Renvoie le nombre de sommets des faces
du type specifie.
int est_structure () const override
Renvoie toujours 0, car l'element geometrique
Prisme n'est pas de type structure.
const Nom & nom_lml () const override
Renvoie le nom LML d'un prisme = "PRISM6".
int contient (const ArrOfDouble &, int) const override
NE FAIT RIEN: A CODER, renvoie toujours 0.
Renvoie 1 si l'element "element" de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
int contient (const ArrOfInt &, int) const override
NE FAIT RIEN: A CODER, renvoie toujours 0
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Type_Face type_face (int=0) const override
Renvoie le i-ieme type de face.
Un prisme a 2 types de face: quadrangle et triangle.
void reordonner () override
Reordonne les sommets du Prisme.
NE FAIT RIEN: A CODER.
void calculer_volumes (DoubleVect &) const override
NE FAIT RIEN: A CODER
Calcule les volumes des elements de la zone associee.
int nb_type_face () const override
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const override
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
Public Member Functions inherited from Elem_geom_base
Elem_geom_base ()
~Elem_geom_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void creer_faces_elem (Faces &, int, Type_Face) const
Cree les faces de l'element geometrique specifie de la zone
en precisant le type de face a creer.
void creer_faces_elem (Faces &, int) const
Cree les faces de l'element de la zone specifie.
virtual int face_sommet (int i, int j) const =0
void associer_zone (const Zone &)
Associe l'element geometrique a sa zone.
virtual int nb_som () const =0
virtual int nb_faces (int=0) const =0
virtual int nb_som_face (int=0) const =0
virtual int est_structure () const =0
virtual const Nom & nom_lml () const =0
virtual int contient (const ArrOfDouble &, int) const =0
virtual int contient (const ArrOfInt &, int) const =0
virtual int nb_type_face () const
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
virtual int num_face (int face, Type_Face &type) const
Renvoie le parametre face si le type
de face specifie est le meme que celui de l'element
geometrique.
virtual Type_Face type_face (int=0) const =0
virtual void calculer_centres_gravite (DoubleTab &) const
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
virtual void reordonner ()
NE FAIT RIEN:
A surcharger dans les classes derivees.
virtual void calculer_volumes (DoubleVect &) const =0
virtual void calculer_normales (const IntTab &faces_sommets, DoubleTab &face_normales) const
Sort en erreur. Cette methode n'est pas virtuelle pure
pour des raisons de commodite.
virtual int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
virtual void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const
idem que Elem_geom_base::get_tab_faces_sommets_locaux mais pour les aretes:
aretes_som_local.dimension(0) = nombre d'aretes sur l'element de reference
aretes_som_local.dimension(1) = 2 (nombre de sommets par arete)
aretes_som_local(i,j) = numero d'un sommet de l'element (0 <= n < nb_sommets_par_element)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Prisme & self_cast (Objet_U &)
static const Prisme & self_cast (const Objet_U &)
Static Public Member Functions inherited from Elem_geom_base
static const Type_info * info ()
static Elem_geom_base & self_cast (Objet_U &)
static const Elem_geom_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Elem_geom_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Elem_geom_base
Ref_Zone ma_zone
Detailed Description
Classe Prisme
Cette represente l'element geometrique Prisme.
Un prisme est un polyedre ayant 5 faces, 6 sommets et deux types
de face:
2 triangles a 3 sommets
3 quadrangles a 4 sommets.
Definition at line 37 of file Prisme.h.
Constructor & Destructor Documentation
Prisme()
Prisme::Prisme ()
Definition at line 36 of file Prisme.cpp.
~Prisme()
Prisme::~Prisme ()
Definition at line 36 of file Prisme.cpp.
Member Function Documentation
calculer_volumes()
void Prisme::calculer_volumes (DoubleVect & volumes) const override virtual
NE FAIT RIEN: A CODER
Calcule les volumes des elements de la zone associee.
Implements Elem_geom_base.
Definition at line 285 of file Prisme.cpp.
{
  const Zone& zone=ma_zone.valeur();
  const IntTab& elem=zone.les_elems();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  int size_tot = zone.nb_elem_tot();
  assert(volumes.size_totale()==size_tot);
  for (int num_poly=0; num_poly<size_tot; num_poly++)
    {
      int i1=elem(num_poly,0);
      int i2=elem(num_poly,1);
      int i3=elem(num_poly,2);
      int i4=elem(num_poly,3);
      int i5=elem(num_poly,4);
      int i6=elem(num_poly,5);
// recuperer de MEDMEM_Formulae.hxx
      double a1 = (coord(i2,0)-coord(i3,0))/2.0, a2 = (coord(i2,1)-coord(i3,1))/2.0, a3 = (coord(i2,2)-coord(i3,2))/2.0;
      double b1 = (coord(i5,0)-coord(i6,0))/2.0, b2 = (coord(i5,1)-coord(i6,1))/2.0, b3 = (coord(i5,2)-coord(i6,2))/2.0;
      double c1 = (coord(i4,0)-coord(i1,0))/2.0, c2 = (coord(i4,1)-coord(i1,1))/2.0, c3 = (coord(i4,2)-coord(i1,2))/2.0;
      double d1 = (coord(i5,0)-coord(i2,0))/2.0, d2 = (coord(i5,1)-coord(i2,1))/2.0, d3 = (coord(i5,2)-coord(i2,2))/2.0;
      double e1 = (coord(i6,0)-coord(i3,0))/2.0, e2 = (coord(i6,1)-coord(i3,1))/2.0, e3 = (coord(i6,2)-coord(i3,2))/2.0;
      double f1 = (coord(i1,0)-coord(i3,0))/2.0, f2 = (coord(i1,1)-coord(i3,1))/2.0, f3 = (coord(i1,2)-coord(i3,2))/2.0;
      double h1 = (coord(i4,0)-coord(i6,0))/2.0, h2 = (coord(i4,1)-coord(i6,1))/2.0, h3 = (coord(i4,2)-coord(i6,2))/2.0;
      double A = a1*c2*f3 - a1*c3*f2 - a2*c1*f3 + a2*c3*f1 +
                 a3*c1*f2 - a3*c2*f1;
      double B = b1*c2*h3 - b1*c3*h2 - b2*c1*h3 + b2*c3*h1 +
                 b3*c1*h2 - b3*c2*h1;
      double C = (a1*c2*h3 + b1*c2*f3) - (a1*c3*h2 + b1*c3*f2) -
                 (a2*c1*h3 + b2*c1*f3) + (a2*c3*h1 + b2*c3*f1) +
                 (a3*c1*h2 + b3*c1*f2) - (a3*c2*h1 + b3*c2*f1);
      double D = a1*d2*f3 - a1*d3*f2 - a2*d1*f3 + a2*d3*f1 +
                 a3*d1*f2 - a3*d2*f1;
      double E = b1*d2*h3 - b1*d3*h2 - b2*d1*h3 + b2*d3*h1 +
                 b3*d1*h2 - b3*d2*h1;
      double F = (a1*d2*h3 + b1*d2*f3) - (a1*d3*h2 + b1*d3*f2) -
                 (a2*d1*h3 + b2*d1*f3) + (a2*d3*h1 + b2*d3*f1) +
                 (a3*d1*h2 + b3*d1*f2) - (a3*d2*h1 + b3*d2*f1);
      double G = a1*e2*f3 - a1*e3*f2 - a2*e1*f3 + a2*e3*f1 +
                 a3*e1*f2 - a3*e2*f1;
      double H = b1*e2*h3 - b1*e3*h2 - b2*e1*h3 + b2*e3*h1 +
                 b3*e1*h2 - b3*e2*h1;
      double P = (a1*e2*h3 + b1*e2*f3) - (a1*e3*h2 + b1*e3*f2) -
                 (a2*e1*h3 + b2*e1*f3) + (a2*e3*h1 + b2*e3*f1) +
                 (a3*e1*h2 + b3*e1*f2) - (a3*e2*h1 + b3*e2*f1);
      volumes[num_poly]=std::fabs(-2.0*(2.0*(A + B + D + E + G + H) + C + F + P)/9.0);
    }
}
References Domaine::coord_sommets(), Zone::domaine(), f1, f2, Zone::les_elems(), Elem_geom_base::ma_zone, Zone::nb_elem_tot(), TRUSTVect< _TYPE_ >::size_totale(), and Ref_Zone::valeur().
contient() [1/2]
int Prisme::contient (const ArrOfDouble & pos, int ielem) const override virtual
NE FAIT RIEN: A CODER, renvoie toujours 0.
Renvoie 1 si l'element "element" de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
Returns
int
Signification: 1 si le point de coordonnees specifiees
appartient a l'element "element"
0 sinon
Contraintes:
Implements Elem_geom_base.
Definition at line 149 of file Prisme.cpp.
{
// a coder :
// est-ce que le prisme de numero element contient le point de
// coordonnees pos ?
// adaptation de tetraedre contient
  assert(pos.size_array()==3);
  const Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  double prod1,prod2,xn,yn,zn;
  int som0, som1, som2, som3,som4,som5;
// On regarde tout d'abord si le pintr cherche n'est pas un des
// sommets du triangle
  som0 = zone.sommet_elem(ielem,0);
  som1 = zone.sommet_elem(ielem,1);
  som2 = zone.sommet_elem(ielem,2);
  som3 = zone.sommet_elem(ielem,3);
  som4 = zone.sommet_elem(ielem,4);
  som5 = zone.sommet_elem(ielem,5);
  if( ( est_egal(dom.coord(som0,0),pos[0]) && est_egal(dom.coord(som0,1),pos[1]) && est_egal(dom.coord(som0,2),pos[2]) )
      || (est_egal(dom.coord(som1,0),pos[0]) && est_egal(dom.coord(som1,1),pos[1]) && est_egal(dom.coord(som1,2),pos[2]))
      || (est_egal(dom.coord(som2,0),pos[0]) && est_egal(dom.coord(som2,1),pos[1]) && est_egal(dom.coord(som2,2),pos[2]))
      || (est_egal(dom.coord(som3,0),pos[0]) && est_egal(dom.coord(som3,1),pos[1]) && est_egal(dom.coord(som3,2),pos[2]))
      || (est_egal(dom.coord(som4,0),pos[0]) && est_egal(dom.coord(som4,1),pos[1]) && est_egal(dom.coord(som4,2),pos[2]))
      || (est_egal(dom.coord(som5,0),pos[0]) && est_egal(dom.coord(som5,1),pos[1]) && est_egal(dom.coord(som5,2),pos[2]))
    )
    return 1;
  for (int j=0; j<5; j++)
    {
      switch(j)
        {
        case 0 :
          som0 = zone.sommet_elem(ielem,0);
          som1 = zone.sommet_elem(ielem,1);
          som2 = zone.sommet_elem(ielem,3);
          som3 = zone.sommet_elem(ielem,2);
          break;
        case 1 :
          som0 = zone.sommet_elem(ielem,0);
          som1 = zone.sommet_elem(ielem,2);
          som2 = zone.sommet_elem(ielem,3);
          som3 = zone.sommet_elem(ielem,4);
          break;
        case 2 :
          som0 = zone.sommet_elem(ielem,1);
          som1 = zone.sommet_elem(ielem,2);
          som2 = zone.sommet_elem(ielem,4);
          som3 = zone.sommet_elem(ielem,0);
          break;
        case 3 :
          som0 = zone.sommet_elem(ielem,0);
          som1 = zone.sommet_elem(ielem,1);
          som2 = zone.sommet_elem(ielem,2);
          som3 = zone.sommet_elem(ielem,3);
          break;
        case 4 :
          som0 = zone.sommet_elem(ielem,3);
          som1 = zone.sommet_elem(ielem,4);
          som2 = zone.sommet_elem(ielem,5);
          som3 = zone.sommet_elem(ielem,0);
          break;
        }
// Algorithme : le sommet 3 et le point M doivent pour j=0 a 3 du meme cote
// que le plan formes par les points som0,som1,som2.
// calcul de la normale au plan som0,som1,som2 :
      xn = (dom.coord(som1,1)-dom.coord(som0,1))*(dom.coord(som2,2)-dom.coord(som0,2))
           - (dom.coord(som1,2)-dom.coord(som0,2))*(dom.coord(som2,1)-dom.coord(som0,1));
      yn = (dom.coord(som1,2)-dom.coord(som0,2))*(dom.coord(som2,0)-dom.coord(som0,0))
           - (dom.coord(som1,0)-dom.coord(som0,0))*(dom.coord(som2,2)-dom.coord(som0,2));
      zn = (dom.coord(som1,0)-dom.coord(som0,0))*(dom.coord(som2,1)-dom.coord(som0,1))
           - (dom.coord(som1,1)-dom.coord(som0,1))*(dom.coord(som2,0)-dom.coord(som0,0));
      prod1 = xn * ( dom.coord(som3,0) - dom.coord(som0,0) )
              + yn * ( dom.coord(som3,1) - dom.coord(som0,1) )
              + zn * ( dom.coord(som3,2) - dom.coord(som0,2) );
      prod2 = xn * ( pos[0] - dom.coord(som0,0) )
              + yn * ( pos[1] - dom.coord(som0,1) )
              + zn * ( pos[2] - dom.coord(som0,2) );
// Si le point est sur le plan (prod2 quasi nul) : on ne peut pas conclure...
      if (prod1*prod2 < 0 && std::fabs(prod2)>std::fabs(prod1)*Objet_U::precision_geom) return 0;
    }
  return 1;
}
References Domaine::coord(), Zone::domaine(), est_egal(), Elem_geom_base::ma_zone, Objet_U::precision_geom, TRUSTArray< _TYPE_ >::size_array(), Zone::sommet_elem(), and Ref_Zone::valeur().
contient() [2/2]
int Prisme::contient (const ArrOfInt & pos, int element) const override virtual
NE FAIT RIEN: A CODER, renvoie toujours 0
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Returns
int
Signification: 1 si les sommets passes en parametre
sont ceux de l'element specifie, 0 sinon
Contraintes:
Implements Elem_geom_base.
Definition at line 261 of file Prisme.cpp.
{
// a coder :
  exit();
  return 0;
}
References Process::exit().
cree_instance()
Objet_U * Prisme::cree_instance () static
Definition at line 36 of file Prisme.cpp.
duplique()
int Prisme::duplique () const override virtual
Implements Objet_U.
Definition at line 36 of file Prisme.cpp.
est_structure()
int Prisme::est_structure () const inline override virtual
Renvoie toujours 0, car l'element geometrique
Prisme n'est pas de type structure.
Returns
int
Signification: 1 si l'element est de type structure
0 sinon
Contraintes: toujours egal a 0
Implements Elem_geom_base.
Definition at line 381 of file Prisme.h.
{
  return 0;
}
face_sommet()
int Prisme::face_sommet (int face, int sommet) const inline override virtual
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
Returns
int
Signification: le numero du j-ieme sommet de la i-ieme face
Contraintes:
Implements Elem_geom_base.
Definition at line 87 of file Prisme.h.
{
  assert(face<5);
  switch(face)
    {
    case 0:
      return face_sommet0(sommet);
    case 1:
      return face_sommet1(sommet);
    case 2:
      return face_sommet2(sommet);
    case 3:
      return face_sommet3(sommet);
    case 4:
      return face_sommet4(sommet);
    default :
      return -1;
    }
}
References face_sommet0(), face_sommet1(), face_sommet2(), face_sommet3(), and face_sommet4().
face_sommet0()
int Prisme::face_sommet0 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 0.
Returns
int
Signification: le numero du i-ieme sommet de la face 0
Contraintes:
Definition at line 206 of file Prisme.h.
{
// face_sommet0(0)=0;
// face_sommet0(1)=1;
// face_sommet0(2)=3;
// face_sommet0(3)=4;
  assert(i>=0);
  assert(i<4);
  switch(i)
    {
    case 0:
      return 0;
    case 1:
      return 1;
    case 2:
      return 3;
    case 3:
      return 4;
    default :
      Cerr << "Error in Prisme::face_sommet0" << finl;
      exit();
// Pour qq compilos :
      return -1;
    }
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet1()
int Prisme::face_sommet1 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 1.
Returns
int
Signification: le numero du i-ieme sommet de la face 1
Contraintes:
Definition at line 247 of file Prisme.h.
{
// face_sommet0(0)=0;
// face_sommet0(1)=2;
// face_sommet0(2)=3;
// face_sommet0(3)=5;
  assert(i>=0);
  assert(i<4);
  switch(i)
    {
    case 0:
      return 0;
    case 1:
      return 2;
    case 2:
      return 3;
    case 3:
      return 5;
    default :
      Cerr << "Error in Prisme::face_sommet1" << finl;
      exit();
// Pour qq compilos :
      return -1;
    }
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet2()
int Prisme::face_sommet2 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 2.
Returns
int
Signification: le numero du i-ieme sommet de la face 2
Contraintes:
Definition at line 288 of file Prisme.h.
{
// face_sommet0(0)=1;
// face_sommet0(1)=2;
// face_sommet0(2)=4;
// face_sommet0(3)=5;
  assert(i>=0);
  assert(i<4);
  switch(i)
    {
    case 0:
      return 1;
    case 1:
      return 2;
    case 2:
      return 4;
    case 3:
      return 5;
    default :
      Cerr << "Error in Prisme::face_sommet2" << finl;
      exit();
// Pour qq compilos :
      return -1;
    }
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet3()
int Prisme::face_sommet3 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 3.
Returns
int
Signification: le numero du i-ieme sommet de la face 3
Contraintes:
Definition at line 329 of file Prisme.h.
{
// face_sommet0(0)=0;
// face_sommet0(1)=1;
// face_sommet0(2)=2;
  assert(i>=0);
  assert(i<3);
  return i;
}
Referenced by face_sommet().
face_sommet4()
int Prisme::face_sommet4 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 4.
Returns
int
Signification: le numero du i-ieme sommet de la face 4
Contraintes:
Definition at line 354 of file Prisme.h.
{
// face_sommet0(0)=0;
// face_sommet0(1)=1;
// face_sommet0(2)=2;
  assert(i>=0);
  assert(i<3);
  return i+3;
}
Referenced by face_sommet().
get_info()
const Type_info * Prisme::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 36 of file Prisme.cpp.
get_tab_faces_sommets_locaux()
int Prisme::get_tab_faces_sommets_locaux (IntTab & faces_som_local) const override virtual
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
Reimplemented from Elem_geom_base.
Definition at line 348 of file Prisme.cpp.
{
  faces_som_local.resize(5,4);
  for (int i=0; i<5; i++)
    for (int j=0; j<4; j++)
      faces_som_local(i,j) = faces_sommets_prisme[i][j];
  return 1;
  Cerr << "Elem_geom_base::faces_sommets_locaux : error.\n"
       << " Method not implemented for the object "
       << que_suis_je() << finl;
  exit();
  return 0;
}
References Cerr, Process::exit(), faces_sommets_prisme, finl, Objet_U::que_suis_je(), and TRUSTTab< _TYPE_ >::resize().
info()
const Type_info * Prisme::info () static
Definition at line 36 of file Prisme.cpp.
nb_faces()
int Prisme::nb_faces (int i = 0) const inline override virtual
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
Un Prisme a 2 types de faces: quadrangle ou triangle.
Returns
int
Signification: le nombre de faces de type i
Contraintes: 3 si i=0, 2 si i=1
Implements Elem_geom_base.
Definition at line 144 of file Prisme.h.
{
  switch(i)
    {
    case 0:
      return 3; //les quadrangles
    case 1:
      return 2; //les triangles
    default :
      Cerr << "Error, a prism has 2 types of faces and not " << i << finl;
      exit();
      return -1;
    }
}
References Cerr, Process::exit(), and finl.
nb_som()
int Prisme::nb_som () const inline override virtual
Renvoie le nombre de sommets d'un Prisme: 6.
Returns
int
Signification: le nombre de sommets d'un prisme
Contraintes: toujours egal a 6
Implements Elem_geom_base.
Definition at line 122 of file Prisme.h.
{
  return 6;
}
nb_som_face()
int Prisme::nb_som_face (int i = 0) const inline override virtual
Renvoie le nombre de sommets des faces
du type specifie.
Returns
int
Signification: le nombre de sommets des faces de type i
Contraintes: 4 si i=0, 3 si i=1
Implements Elem_geom_base.
Definition at line 176 of file Prisme.h.
{
  switch(i)
    {
    case 0:
      return 4;
    case 1:
      return 3;
    default :
      Cerr << "Error, a prism has 2 types of faces and not " << i << finl;
      exit();
      return -1;
    }
}
References Cerr, Process::exit(), and finl.
nb_type_face()
int Prisme::nb_type_face () const override virtual
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 336 of file Prisme.cpp.
{
  return 2;
}
nom_lml()
const Nom & Prisme::nom_lml () const override virtual
Renvoie le nom LML d'un prisme = "PRISM6".
Returns
Nom&
Signification: toujours egal a "PRISM6"
Contraintes: reference constante
Implements Elem_geom_base.
Definition at line 115 of file Prisme.cpp.
{
  static Nom nom="PRISM6";
  return nom;
}
printOn()
Sortie & Prisme::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 53 of file Prisme.cpp.
{
  return s;
}
readOn()
Entree & Prisme::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 73 of file Prisme.cpp.
{
  return s;
}
reordonner()
void Prisme::reordonner () override virtual
Reordonne les sommets du Prisme.
NE FAIT RIEN: A CODER.
Reimplemented from Elem_geom_base.
Definition at line 94 of file Prisme.cpp.
{
  Cerr << "Prisme::reordonner must be coded " << finl;
// a coder. remise en conformite de la numerotation des noeuds.
}
References Cerr, and finl.
self_cast() [1/2]
const Prisme & Prisme::self_cast (const Objet_U & r) static
Definition at line 36 of file Prisme.cpp.
self_cast() [2/2]
Prisme & Prisme::self_cast (Objet_U & r) static
Definition at line 36 of file Prisme.cpp.
taille_memoire()
unsigned Prisme::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 36 of file Prisme.cpp.
type_face()
Type_Face Prisme::type_face (int i = 0) const inline override virtual
Renvoie le i-ieme type de face.
Un prisme a 2 types de face: quadrangle et triangle.
Returns
Type_Face
Signification: le type de la face i
Contraintes: i=0 (Faces::quadrangle_3D), i=1 (Faces::triangle_3D)
Implements Elem_geom_base.
Definition at line 402 of file Prisme.h.
{
  assert(i<=1);
  switch(i)
    {
    case 0:
      return Faces::quadrangle_3D;
    case 1:
      return Faces::triangle_3D;
    default :
      Cerr << "Error, a prism has 2 types of faces and not " << i << finl;
      exit();
      return Faces::quadrangle_3D;
    }
}
References Cerr, Process::exit(), finl, Faces::quadrangle_3D, and Faces::triangle_3D.
Member Data Documentation
info_obj
const Type_info Prisme::info_obj static
Definition at line 40 of file Prisme.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Prisme.h
src/Kernel/Geometrie/Prisme.cpp