TRUST: Ref_Champ_Generique_base Class Reference
Ref_Champ_Generique_base Class Reference
#include <Ref_Champ_Generique_base.h>
Public Member Functions
~Ref_Champ_Generique_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Champ_Generique_base ()
Ref_Champ_Generique_base (const Champ_Generique_base &)
Ref_Champ_Generique_base (const Ref_Champ_Generique_base &)
const Champ_Generique_base & valeur () const
Champ_Generique_base & valeur ()
const Champ_Generique_base * operator-> () const
Champ_Generique_base * operator-> ()
const Ref_Champ_Generique_base & operator= (const Champ_Generique_base &)
const Ref_Champ_Generique_base & operator= (const Ref_Champ_Generique_base &)
operator const Champ_Generique_base & () const
operator Champ_Generique_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Champ_Generique_base & self_cast (Objet_U &)
static const
Ref_Champ_Generique_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Champ_Generique_base * pointeur_
Detailed Description
Definition at line 28 of file Ref_Champ_Generique_base.h.
Constructor & Destructor Documentation
Ref_Champ_Generique_base::~Ref_Champ_Generique_base ()
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
Ref_Champ_Generique_base::Ref_Champ_Generique_base ()
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
Ref_Champ_Generique_base::Ref_Champ_Generique_base (const Champ_Generique_base & t)
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
Ref_Champ_Generique_base::Ref_Champ_Generique_base (const Ref_Champ_Generique_base & t)
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
Member Function Documentation
Objet_U * Ref_Champ_Generique_base::cree_instance () [static]
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
int Ref_Champ_Generique_base::duplique () const [virtual]
Implements Ref_.
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
const Type_info * Ref_Champ_Generique_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
const Type_info & Ref_Champ_Generique_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
const Type_info * Ref_Champ_Generique_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
Ref_Champ_Generique_base::operator Champ_Generique_base & ()
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
Ref_Champ_Generique_base::operator const Champ_Generique_base & () const
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
const Champ_Generique_base * Ref_Champ_Generique_base::operator-> () const [inline]
Definition at line 28 of file Ref_Champ_Generique_base.h.
Champ_Generique_base * Ref_Champ_Generique_base::operator-> () [inline]
Definition at line 28 of file Ref_Champ_Generique_base.h.
const Ref_Champ_Generique_base & Ref_Champ_Generique_base::operator= (const Ref_Champ_Generique_base & t)
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
const Ref_Champ_Generique_base & Ref_Champ_Generique_base::operator= (const Champ_Generique_base & t)
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
Sortie & Ref_Champ_Generique_base::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
Entree & Ref_Champ_Generique_base::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
const Ref_Champ_Generique_base & Ref_Champ_Generique_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
Ref_Champ_Generique_base & Ref_Champ_Generique_base::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
void Ref_Champ_Generique_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
unsigned Ref_Champ_Generique_base::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Ref_Champ_Generique_base.cpp.
const Champ_Generique_base & Ref_Champ_Generique_base::valeur () const [inline]
Definition at line 28 of file Ref_Champ_Generique_base.h.
Referenced by Champ_Generique_Correlation::get_directive_pour_discr(), Sonde::init_bords(), Sonde::initialiser(), Sonde::le_champ(), and Sonde::mettre_a_jour_bords().
Champ_Generique_base & Ref_Champ_Generique_base::valeur () [inline]
Definition at line 28 of file Ref_Champ_Generique_base.h.
Member Data Documentation
const Type_info Ref_Champ_Generique_base::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Champ_Generique_base.h.
Champ_Generique_base* Ref_Champ_Generique_base::pointeur_ [private]
Definition at line 28 of file Ref_Champ_Generique_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Ref_Champ_Generique_base.h
src/Kernel/Framework/Ref_Champ_Generique_base.cpp