TRUST: Ref_ Class Reference
Ref_ Class Reference
classe Ref_
un type qui permet d'acceder a un objet de la classe Objet_U ou
de l'une quelconque des classes derivees de la classe Objet_U REF__H
#include <Ref_.h>
Public Member Functions
Ref_ ()
~Ref_ ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void reset ()
Annule la ref.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_ & self_cast (Objet_U &)
static const Ref_ & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Detailed Description
classe Ref_
un type qui permet d'acceder a un objet de la classe Objet_U ou
de l'une quelconque des classes derivees de la classe Objet_U REF__H
Definition at line 37 of file Ref_.h.
Constructor & Destructor Documentation
Ref_::Ref_ ()
Definition at line 26 of file Ref_.cpp.
Ref_::~Ref_ ()
Definition at line 26 of file Ref_.cpp.
Member Function Documentation
virtual int Ref_::duplique () const [pure virtual]
Implements O_U_Ptr.
Implemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Ref_Debog_Pb, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Ref_Interprete, Ref_Interprete_bloc, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Ref_Fluide_Dilatable_base, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Ref_Marqueur_Lagrange_base, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Ref_Correlation_base, Ref_Correlation, Ref_Saturation_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
const Type_info * Ref_::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from O_U_Ptr.
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Ref_Debog_Pb, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Ref_Interprete, Ref_Interprete_bloc, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Ref_Fluide_Dilatable_base, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Ref_Marqueur_Lagrange_base, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Ref_Correlation_base, Ref_Correlation, Ref_Saturation_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 26 of file Ref_.cpp.
const Type_info * Ref_::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from O_U_Ptr.
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Ref_Debog_Pb, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Ref_Interprete, Ref_Interprete_bloc, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Ref_Fluide_Dilatable_base, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Ref_Marqueur_Lagrange_base, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Ref_Correlation_base, Ref_Correlation, Ref_Saturation_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 26 of file Ref_.cpp.
Sortie & Ref_::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from O_U_Ptr.
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Ref_Debog_Pb, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Ref_Interprete, Ref_Interprete_bloc, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Ref_Fluide_Dilatable_base, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Ref_Marqueur_Lagrange_base, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Ref_Correlation_base, Ref_Correlation, Ref_Saturation_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 43 of file Ref_.cpp.
{
  O_U_Ptr::printOn(os);
  return os;
}
Entree & Ref_::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from O_U_Ptr.
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Ref_Debog_Pb, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Ref_Interprete, Ref_Interprete_bloc, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Ref_Fluide_Dilatable_base, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Ref_Marqueur_Lagrange_base, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Ref_Correlation_base, Ref_Correlation, Ref_Saturation_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 65 of file Ref_.cpp.
{
  O_U_Ptr::readOn(is);
  return is;
}
void Ref_::reset () [virtual]
Annule la ref.
Definition at line 72 of file Ref_.cpp.
References O_U_Ptr::set_O_U_Ptr().
Referenced by Champ_Generique_Extraction::completer(), PE_Groups::finalize(), Champ_Generique_Champ::lire_motcle_non_standard(), Champ_Input_Proto::read(), Octree_Zone::reset(), Faces_builder::reset(), DomaineCutter::reset(), Champ_Generique_refChamp::reset(), Champ_Generique_Interpolation::reset(), and Champ_Generique_Interpolation::set_domaine().
{
  set_O_U_Ptr((Objet_U*) 0);
}
Ref_ & Ref_::self_cast (Objet_U & r) [static]
Reimplemented from O_U_Ptr.
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Ref_Debog_Pb, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Ref_Interprete, Ref_Interprete_bloc, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Ref_Fluide_Dilatable_base, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Ref_Marqueur_Lagrange_base, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Ref_Correlation_base, Ref_Correlation, Ref_Saturation_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 26 of file Ref_.cpp.
const Ref_ & Ref_::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from O_U_Ptr.
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Ref_Debog_Pb, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Ref_Interprete, Ref_Interprete_bloc, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Ref_Fluide_Dilatable_base, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Ref_Marqueur_Lagrange_base, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Ref_Correlation_base, Ref_Correlation, Ref_Saturation_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 26 of file Ref_.cpp.
Member Data Documentation
const Type_info Ref_::info_obj [static]
Reimplemented from O_U_Ptr.
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Ref_Debog_Pb, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Ref_Interprete, Ref_Interprete_bloc, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Ref_Fluide_Dilatable_base, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Ref_Marqueur_Lagrange_base, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Ref_Correlation_base, Ref_Correlation, Ref_Saturation_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 39 of file Ref_.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Ref_.h
src/Kernel/Utilitaires/Ref_.cpp