TRUST: Op_Conv_kschemas_VEF Class Reference
Op_Conv_kschemas_VEF Class Reference
class Op_Conv_kschemas_VEF
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VEF
Le champ convecte est scalaire ou vecteur de type Champ_Inc_Base (P1NC et Q1NC)
Le schema de convection est du type kschemas
#include <Op_Conv_kschemas_VEF.h>
Public Member Functions
Op_Conv_kschemas_VEF ()
~Op_Conv_kschemas_VEF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
Public Member Functions inherited from Op_Conv_VEF_base
Op_Conv_VEF_base ()
~Op_Conv_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_vitesse (const Champ_base &) override
const Champ_Inc_base & vitesse () const
Champ_Inc_base & vitesse ()
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
void abortTimeStep () override
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_dt_local (DoubleTab &) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_fluent (DoubleVect &) const
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_zone_cl_dis (const Zone_Cl_dis_base &) override
int phi_u_transportant (const Equation_base &eq) const
definit si l'on convecte psi avec phi*u ou avec u
Public Member Functions inherited from Operateur_Conv_base
Operateur_Conv_base ()
initialise dt_stab_conv a -123
~Operateur_Conv_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_vitesse (const Champ_base &vit)=0
double dt_stab_conv () const
void fixer_dt_stab_conv (double dt)
virtual void associer_norme_vitesse (const Champ_base &norme_vitesse)
virtual void associer_vitesse_pour_pas_de_temps (const Champ_base &vitesse)
virtual void set_incompressible (const int)
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Static Public Member Functions
static const Type_info * info ()
static Op_Conv_kschemas_VEF & self_cast (Objet_U &)
static const Op_Conv_kschemas_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Conv_VEF_base
static const Type_info * info ()
static Op_Conv_VEF_base & self_cast (Objet_U &)
static const Op_Conv_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Conv_base
static const Type_info * info ()
static Operateur_Conv_base & self_cast (Objet_U &)
static const Operateur_Conv_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Conv_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Conv_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Conv_VEF_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Attributes
double K
int caracterisant les differents schemas
Protected Attributes inherited from Op_Conv_VEF_base
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base vitesse_
DoubleVect fluent
tableau qui sert pour le calcul du pas de temps de stabilite
int jeton
int roue
Protected Attributes inherited from Operateur_Conv_base
Ref_Champ_base la_norme_vitesse
Ref_Champ_base vitesse_pour_pas_de_temps_
double dt_stab_conv_
int incompressible_ = 1
incompressible_= 1 -> l'operateur discretise div(v x inco), incompressible_ = 0 -> il discretise v.grad(inco)
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Conv_kschemas_VEF
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VEF
Le champ convecte est scalaire ou vecteur de type Champ_Inc_Base (P1NC et Q1NC)
Le schema de convection est du type kschemas
Definition at line 36 of file Op_Conv_kschemas_VEF.h.
Constructor & Destructor Documentation
Op_Conv_kschemas_VEF()
Op_Conv_kschemas_VEF::Op_Conv_kschemas_VEF ()
Definition at line 20 of file Op_Conv_kschemas_VEF.cpp.
~Op_Conv_kschemas_VEF()
Op_Conv_kschemas_VEF::~Op_Conv_kschemas_VEF () override
Definition at line 20 of file Op_Conv_kschemas_VEF.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Conv_kschemas_VEF::ajouter (const DoubleTab & transporte, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 168 of file Op_Conv_kschemas_VEF.cpp.
{
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const Champ_Inc_base& la_vitesse=vitesse_.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const DoubleTab& facette_normales = zone_VEF.facette_normales();
  const Zone& zone = zone_VEF.zone();
  const int nb_faces = zone_VEF.nb_faces();
  const int nfa7 = zone_VEF.type_elem().nb_facette();
  const int nb_elem = zone_VEF.nb_elem();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const IntVect& rang_elem_non_std = zone_VEF.rang_elem_non_std();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleVect& volumes = zone_VEF.volumes();
  const DoubleTab& xv = zone_VEF.xv();
  const DoubleTab& xg = zone_VEF.xp();
  const DoubleTab& coord = zone.domaine().coord_sommets();
  int premiere_face_int = zone_VEF.premiere_face_int();
  const IntTab& les_Polys = zone.les_elems();
  const DoubleTab& normales_facettes_Cl = zone_Cl_VEF.normales_facettes_Cl();
  int nfac = zone.nb_faces_elem();
  int nsom = zone.nb_som_elem();
  int nb_som_facette = zone.type_elem().nb_som_face();
  DoubleVect& fluent_ = fluent;
// Pour le traitement de la convection on distingue les polyedres
// standard qui ne "voient" pas les conditions aux limites et les
// polyedres non standard qui ont au moins une face sur le bord.
// Un polyedre standard a n facettes sur lesquelles on applique le
// schema de convection.
// Pour un polyedre non standard qui porte des conditions aux limites
// de Dirichlet, une partie des facettes sont portees par les faces.
// En bref pour un polyedre le traitement de la convection depend
// du type (triangle, tetraedre ...) et du nombre de faces de Dirichlet.
  double psc;
  int poly,poly1,poly2,face_adj,fa7,i,j,n_bord;
  int num_face, rang ,itypcl;
  int num10,num20,num3,num_som;
// MODIF SB su 10/09/03
// Pour les 3 elements suivants, il y a autant de sommets que de face
// constituant l'element geometrique
// PB avec les hexa, 8 sommets et 6 faces, donc l'utilisation du tableau
// face[i] ne fonctionne plus
// la methode retenue pour eviter de calculer la vitesse aux sommets sans
// les fonctions de forme n'est donc pas utilisable,
// pour l'hexa on n'a pas acces a la face.
// il existe le tableau Face=>sommets mais pas l'inverse.
// trop couteux et pour le moment on n'etend pas les porosites aux hexa
  int istetra=0;
  const Elem_VEF_base& type_elemvef= zone_VEF.type_elem().valeur();
  Nom nom_elem=type_elemvef.que_suis_je();
  if ((nom_elem=="Tetra_VEF")||(nom_elem=="Tri_VEF")) istetra=1;
  const int ncomp_ch_transporte= transporte.line_size();
  int fac,elem1,elem2,comp0;
  int nb_faces_ = zone_VEF.nb_faces();
  IntVect face(nfac);
  DoubleVect flux(ncomp_ch_transporte);
  DoubleVect fluxsom(ncomp_ch_transporte);
  DoubleVect fluxg(ncomp_ch_transporte);
// Traitement particulier pour les faces de periodicite
  int nb_faces_perio = 0;
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          for (num_face=num1; num_face<num2; num_face++)
            nb_faces_perio++;
        }
    }
  DoubleTab tab(nb_faces_perio,ncomp_ch_transporte);
  nb_faces_perio=0;
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          for (num_face=num1; num_face<num2; num_face++)
            {
              for (int comp=0; comp<ncomp_ch_transporte; comp++)
                tab(nb_faces_perio,comp) = resu(num_face,comp);
              nb_faces_perio++;
            }
        }
    }
//
// <
// calcul des gradients;  < [ Ujp*np/vol(j) ]
// j
//
  DoubleTab gradient_elem(0, ncomp_ch_transporte, dimension);
  zone_VEF.zone().creer_tableau_elements(gradient_elem);
// Boucle sur les faces
  for (fac=0; fac< premiere_face_int; fac++)
    {
      elem1=face_voisins(fac,0);
      if(ncomp_ch_transporte==1)
        for (i=0; i<dimension; i++)
          {
            gradient_elem(elem1, 0, i) +=
              face_normales(fac,i)*transporte(fac);
          }
      else
        for (comp0=0; comp0<ncomp_ch_transporte; comp0++)
          for (i=0; i<dimension; i++)
            gradient_elem(elem1, comp0, i) +=
              face_normales(fac,i)*transporte(fac,comp0);
// dUcomp/dXi
    } //!< fin du for faces
  for (; fac<nb_faces_; fac++)
    {
      elem1=face_voisins(fac,0);
      elem2=face_voisins(fac,1);
      if(ncomp_ch_transporte==1)
        for (i=0; i<dimension; i++)
          {
            gradient_elem(elem1, 0, i) +=
              face_normales(fac,i)*transporte(fac);
            gradient_elem(elem2, 0, i) -=
              face_normales(fac,i)*transporte(fac);
          }
      else
        for (comp0=0; comp0<ncomp_ch_transporte; comp0++)
          for (i=0; i<dimension; i++)
            {
              gradient_elem(elem1, comp0, i) +=
                face_normales(fac,i)*transporte(fac,comp0);
              gradient_elem(elem2, comp0, i) -=
                face_normales(fac,i)*transporte(fac,comp0);
            }
// dUcomp/dXi
    } //!< fin du for faces
  for (int elem=0; elem<nb_elem; elem++)
    for (comp0=0; comp0<ncomp_ch_transporte; comp0++)
      for (i=0; i<dimension; i++)
        gradient_elem(elem,comp0,i) /= volumes(elem);
  gradient_elem.echange_espace_virtuel();
//
// On a les gradient_elem par elements
//
  DoubleVect vs(dimension);
  DoubleVect vc(dimension);
  DoubleTab vsom(nsom,dimension);
  DoubleVect cc(dimension);
  double xm;
// On remet a zero le tableau qui sert pour
// le calcul du pas de temps de stabilite
  fluent_ = 0;
// Les polyedres non standard sont ranges en 2 groupes dans la Zone_VEF:
// - polyedres bords et joints
// - polyedres bords et non joints
// On traite les polyedres en suivant l'ordre dans lequel ils figurent
// dans la zone
//
// boucle sur les polys
//
  const IntTab& KEL=zone_VEF.type_elem().valeur().KEL();
  for (poly=0; poly<nb_elem; poly++)
    {
      rang = rang_elem_non_std(poly);
      if (rang==-1)
        itypcl=0;
      else
        itypcl=zone_Cl_VEF.type_elem_Cl(rang);
// calcul des numeros des faces du polyedre
      for (face_adj=0; face_adj<nfac; face_adj++)
        face(face_adj)= elem_faces(poly,face_adj);
      int scom;
      DoubleVect rx0(dimension);
// calcul de la vitesse aux sommets des polyedres
      for (j=0; j<dimension; j++)
        {
          vs(j) = la_vitesse(face(0),j)*porosite_face(face(0));
          for (i=1; i<nfac; i++)
            vs(j)+= la_vitesse(face(i),j)*porosite_face(face(i));
        }
// int ncomp;
      if (istetra==1)
        {
          for (j=0; j<nsom; j++)
            {
              for (int ncomp=0; ncomp<Objet_U::dimension; ncomp++)
                vsom(j,ncomp) =vs[ncomp] - Objet_U::dimension*la_vitesse(face[j],ncomp)*porosite_face(face[j]);
            }
        }
      else
        {
// pour que cela soit valide avec les hexa
// On va utliser les fonctions de forme implementees dans la classe Champs_P1_impl ou Champs_Q1_impl
// int ncomp;
          for (j=0; j<nsom; j++)
            {
              num_som = zone.sommet_elem(poly,j);
              for (int ncomp=0; ncomp<dimension; ncomp++)
                {
                  vsom(j,ncomp) = la_vitesse.valeur_a_sommet_compo(num_som,poly,ncomp);
                }
            }
        }
// calcul de la vitesse au centre de gravite
      zone_VEF.type_elem().calcul_vc(face,vc,vs,vsom,vitesse(),itypcl,porosite_face);
// Boucle sur les facettes du polyedre non standard:
      for (fa7=0; fa7<nfa7; fa7++)
        {
// Cerr << "la facette etudiee est " << fa7 << finl;
// fa7 separe num1 et num2. num3 est la troisieme face (2D).
          num10 = face(KEL(0,fa7));
          num20 = face(KEL(1,fa7));
          num3 = face(KEL(2,fa7));
// Determination des elements voisins aux faces num1 et num2
          poly1 = face_voisins(num10,0);
          if (poly1==poly)
            poly1 = face_voisins(num10,1);
          poly2 = face_voisins(num20,0);
          if (poly2==poly)
            poly2 = face_voisins(num20,1);
          scom = les_Polys(poly,KEL(2,fa7));
// calcul des rx0, distance entre les milieux des 'num i'
          for (i=0; i<dimension; i++)
            rx0(i) = xv(num20,i)-xv(num10,i);
// normales aux facettes
          if (rang==-1)
            for (i=0; i<dimension; i++)
              cc[i] = facette_normales(poly, fa7, i);
          else
            for (i=0; i<dimension; i++)
              cc[i] = normales_facettes_Cl(rang,fa7,i);
//
// On traite le point pour lequel vitesse = 0.5(vitsommet + vitmilieu)
//
          for (i=0; i<nb_som_facette-1; i++)
            {
//
// Determination de PhiIJ au milieu entre le sommet et le milieu de num3
//
              psc = 0;
              for (j=0; j<dimension; j++)
                psc+=((vsom(KEL(i+2,fa7),j) + la_vitesse(num3,j) * porosite_face(num3)))*cc[j];
              psc *=0.5;
              convkschemas(K,ncomp_ch_transporte,dimension,poly,poly1,poly2,num10,num20,psc,transporte,
                           fluent_,flux,rx0,gradient_elem);
//
// Limiteur pour le gradient. Calcul effectue en meme temps que le calcul du flux.
// gradient(K0) = teta*gradient(K0)+ (1-teta)gradient(K1ou K2)
//
              double teta = 0.5;
//
// On traite les sommets qui sont aussi des sommets du polyedre
//
// XXX XXX XXX : Attention : we can not factorize more... the code is not the same
              if (ncomp_ch_transporte == 1)
                {
                  for (j=0; j<dimension; j++)
                    {
                      xm = 0.5 *(coord(scom,j)+xv(num3,j));
                      if (psc >= 0)
{
                          if (poly1==-1)
                            fluxsom(0) += gradient_elem(poly,0,j)*(coord(scom,j)-xm);
                          else
                            fluxsom(0) += (teta*gradient_elem(poly,0,j) + (1.- teta)*gradient_elem(poly1,0,j))*(coord(scom,j)-xm);
                        }
                      else
{
                          if (poly2==-1)
                            fluxsom(0) += gradient_elem(poly,0,j)*(coord(scom,j)-xm);
                          else
                            fluxsom(0) += (teta*gradient_elem(poly,0,j) + (1.- teta)*gradient_elem(poly2,0,j))*(coord(scom,j)-xm);
                        }
                    }
                  fluxsom(0) += flux(0);
                  fluxsom(0) *= psc;
                }
              else
                {
                  for (comp0=0; comp0<ncomp_ch_transporte; comp0++)
                    {
                      fluxsom(comp0) = flux(comp0);
                      for (j=0; j<dimension; j++)
{
                          xm = 0.5 *(coord(scom,j)+xv(num3,j));
                          if (psc >= 0)
{
                              if (poly1==-1)
                                fluxsom(comp0) += gradient_elem(poly,comp0,j)*(coord(scom,j)-xm);
                              else
                                fluxsom(comp0) += (teta*gradient_elem(poly,comp0,j) + (1.-teta)*gradient_elem(poly1,comp0,j))*(coord(scom,j)-xm);
                            }
                          else
{
                              if (poly2==-1)
                                fluxsom(comp0) += gradient_elem(poly,comp0,j)*(coord(scom,j)-xm);
                              else
                                fluxsom(comp0) += (teta*gradient_elem(poly,comp0,j) + (1.-teta)*gradient_elem(poly2,comp0,j))*(coord(scom,j)-xm);
                            }
                        }
                      fluxsom(comp0) *= psc;
                    }
                }
//
// on traite le centre de gravite
//
// XXX XXX XXX : Attention : we can not factorize more... the code is not the same
              if (ncomp_ch_transporte == 1)
                {
                  for (j=0; j<dimension; j++)
                    {
                      xm = 0.5 *(coord(scom,j)+xv(num3,j));
                      if (psc >= 0)
{
                          if (poly1==-1)
                            fluxg(0) += gradient_elem(poly,0,j)*(xg(poly,j)-xm);
                          else
                            fluxg(0) += (teta*gradient_elem(poly,0,j) + (1.- teta)*gradient_elem(poly1,0,j))*(xg(poly,j)-xm);
                        }
                      else
{
                          if (poly2==-1)
                            fluxg(0) += gradient_elem(poly,0,j)*(xg(poly,j)-xm);
                          else
                            fluxg(0) += (teta*gradient_elem(poly,0,j) + (1.- teta)*gradient_elem(poly2,0,j))*(xg(poly,j)-xm);
                        }
                    }
                  fluxg(0) += flux(0);
                  fluxg(0) *= psc;
                }
              else
                {
                  for (comp0=0; comp0<ncomp_ch_transporte; comp0++)
                    {
                      fluxg(comp0) = flux(comp0);
                      for (j=0; j<dimension; j++)
{
                          xm = 0.5 *(coord(scom,j)+xv(num3,j));
                          if (psc >= 0)
{
                              if (poly1==-1)
                                fluxg(comp0) += gradient_elem(poly,comp0,j)*(xg(poly,j)-xm);
                              else
                                fluxg(comp0) += (teta*gradient_elem(poly,comp0,j) + (1.-teta)*gradient_elem(poly1,comp0,j))*(xg(poly,j)-xm);
                            }
                          else
{
                              if (poly2==-1)
                                fluxg(comp0) += gradient_elem(poly,comp0,j)*(xg(poly,j)-xm);
                              else
                                fluxg(comp0) += (teta*gradient_elem(poly,comp0,j) + (1.-teta)*gradient_elem(poly2,comp0,j))*(xg(poly,j)-xm);
                            }
                        }
                      fluxg(comp0) *= psc;
                    }
                }
//
// Integration de u.n.flux
//
              for (comp0=0; comp0<ncomp_ch_transporte; comp0++)
                {
                  resu(num10,comp0) -= ( 0.5*(fluxsom(comp0)+fluxg(comp0)) );
                  resu(num20,comp0) += ( 0.5*(fluxsom(comp0)+fluxg(comp0)) );
                }
            }
        }
    } //!< fin de la boucle
// Traitement des elements joints d'epaisseur 1
  for (poly=0; poly<nb_elem_tot; poly++)
    {
// On regarde si une face du polyedre est une face joint
      for (face_adj=0; face_adj<nfac; face_adj++)
        if(face_adj<nb_faces) break;
      if(face_adj<nfac)
        {
          rang = rang_elem_non_std(poly);
          if (rang==-1)
            itypcl=0;
          else
            itypcl=zone_Cl_VEF.type_elem_Cl(rang);
// calcul des numeros des faces du polyedre
          for (face_adj=0; face_adj<nfac; face_adj++)
            {
              face(face_adj)= elem_faces(poly,face_adj);
// Cerr << "les faces de l'elements sont : " << face(face_adj) << finl;
            }
          int scom;
          DoubleVect rx0(dimension);
// calcul de la vitesse aux sommets des polyedres
          for (j=0; j<dimension; j++)
            {
              vs(j) = la_vitesse(face(0),j)*porosite_face(face(0));
              for (i=1; i<nfac; i++)
                vs(j)+= la_vitesse(face(i),j)*porosite_face(face(j));
            }
          int ncomp;
          for (j=0; j<nsom; j++)
            {
              num_som = zone.sommet_elem(poly,j);
              for (ncomp=0; ncomp<dimension; ncomp++)
                vsom(j,ncomp) = la_vitesse.valeur_a_sommet_compo(num_som,poly,ncomp);
            }
// calcul de la vitesse au centre de gravite
          zone_VEF.type_elem().calcul_vc(face,vc,vs,vsom,vitesse(),itypcl,porosite_face);
// Boucle sur les facettes du polyedre non standard:
          for (fa7=0; fa7<nfa7; fa7++)
            {
// Cerr << "la facette etudiee est " << fa7 << finl;
// fa7 separe num1 et num2. num3 est la troisieme face (2D).
              num10 = face(KEL(0,fa7));
              num20 = face(KEL(1,fa7));
              num3 = face(KEL(2,fa7));
// Determination des elements voisins aux faces num1 et num2
              poly1 = face_voisins(num10,0);
              if (poly1==poly)
                {
                  poly1 = face_voisins(num10,1);
                }
              poly2 = face_voisins(num20,0);
              if (poly2==poly)
                {
                  poly2 = face_voisins(num20,1);
                }
              scom = les_Polys(poly,KEL(2,fa7));
// calcul des rx0, distance entre les milieux des 'num i'
              for (i=0; i<dimension; i++)
                rx0(i) = xv(num20,i)-xv(num10,i);
// normales aux facettes
              if (rang==-1)
                for (i=0; i<dimension; i++)
                  cc[i] = facette_normales(poly, fa7, i);
              else
                for (i=0; i<dimension; i++)
                  cc[i] = normales_facettes_Cl(rang,fa7,i);
//
// On traite le point pour lequel vitesse = 0.5(vitsommet + vitmilieu)
//
              for (i=0; i<nb_som_facette-1; i++)
                {
//
// Determination de PhiIJ au milieu entre le sommet et le milieu de num3
//
                  psc = 0;
                  for (j=0; j<dimension; j++)
                    psc+=((vsom(KEL(i+2,fa7),j) + la_vitesse(num3,j) * porosite_face(num3)))*cc[j];
                  psc *=0.5;
                  convkschemas(K,ncomp_ch_transporte,dimension,poly,poly1,poly2,num10,num20,psc,transporte,
                               fluent_,flux,rx0,gradient_elem);
//
// Limiteur pour le gradient. Calcul effectue en meme temps que le calcul du flux.
// gradient(K0) = teta*gradient(K0)+ (1-teta)gradient(K1ou K2)
//
                  double teta = 0.5;
//
// On traite les sommets qui sont aussi des sommets du polyedre
//
// XXX XXX XXX : Attention : we can not factorize more... the code is not the same
                  if (ncomp_ch_transporte == 1)
                    {
                      for (j=0; j<dimension; j++)
{
                          xm = 0.5 *(coord(scom,j)+xv(num3,j));
                          if (psc >= 0)
{
                              if (poly1==-1)
                                fluxsom(0) += gradient_elem(poly,0,j)*(coord(scom,j)-xm);
                              else
                                fluxsom(0) += (teta*gradient_elem(poly,0,j) + (1.- teta)*gradient_elem(poly1,0,j))*(coord(scom,j)-xm);
                            }
                          else
{
                              if (poly2==-1)
                                fluxsom(0) += gradient_elem(poly,0,j)*(coord(scom,j)-xm);
                              else
                                fluxsom(0) += (teta*gradient_elem(poly,0,j) + (1.- teta)*gradient_elem(poly2,0,j))*(coord(scom,j)-xm);
                            }
                        }
                      fluxsom(0) += flux(0);
                      fluxsom(0) *= psc;
                    }
                  else
                    {
                      for (comp0=0; comp0<ncomp_ch_transporte; comp0++)
{
                          fluxsom(comp0) = flux(comp0);
                          for (j=0; j<dimension; j++)
{
                              xm = 0.5 *(coord(scom,j)+xv(num3,j));
                              if (psc >= 0)
{
                                  if (poly1==-1)
                                    fluxsom(comp0) += gradient_elem(poly,comp0,j)*(coord(scom,j)-xm);
                                  else
                                    fluxsom(comp0) += (teta*gradient_elem(poly,comp0,j) + (1.-teta)*gradient_elem(poly1,comp0,j))*(coord(scom,j)-xm);
                                }
                              else
{
                                  if (poly2==-1)
                                    fluxsom(comp0) += gradient_elem(poly,comp0,j)*(coord(scom,j)-xm);
                                  else
                                    fluxsom(comp0) += (teta*gradient_elem(poly,comp0,j) + (1.-teta)*gradient_elem(poly2,comp0,j))*(coord(scom,j)-xm);
                                }
                            }
                          fluxsom(comp0) *= psc;
                        }
                    }
//
// on traite le centre de gravite
//
// XXX XXX XXX : Attention : we can not factorize more... the code is not the same
                  if (ncomp_ch_transporte == 1)
                    {
                      for (j=0; j<dimension; j++)
{
                          xm = 0.5 *(coord(scom,j)+xv(num3,j));
                          if (psc >= 0)
{
                              if (poly1==-1)
                                fluxg(0) += gradient_elem(poly,0,j)*(xg(poly,j)-xm);
                              else
                                fluxg(0) += (teta*gradient_elem(poly,0,j) + (1.- teta)*gradient_elem(poly1,0,j))*(xg(poly,j)-xm);
                            }
                          else
{
                              if (poly2==-1)
                                fluxg(0) += gradient_elem(poly,0,j)*(xg(poly,j)-xm);
                              else
                                fluxg(0) += (teta*gradient_elem(poly,0,j) + (1.- teta)*gradient_elem(poly2,0,j))*(xg(poly,j)-xm);
                            }
                        }
                      fluxg(0) += flux(0);
                      fluxg(0) *= psc;
                    }
                  else
                    {
                      for (comp0=0; comp0<ncomp_ch_transporte; comp0++)
{
                          fluxg(comp0) = flux(comp0);
                          for (j=0; j<dimension; j++)
{
                              xm = 0.5 *(coord(scom,j)+xv(num3,j));
                              if (psc >= 0)
{
                                  if (poly1==-1)
                                    fluxg(comp0) += gradient_elem(poly,comp0,j)*(xg(poly,j)-xm);
                                  else
                                    fluxg(comp0) += (teta*gradient_elem(poly,comp0,j) + (1.-teta)*gradient_elem(poly1,comp0,j))*(xg(poly,j)-xm);
                                }
                              else
{
                                  if (poly2==-1)
                                    fluxg(comp0) += gradient_elem(poly,comp0,j)*(xg(poly,j)-xm);
                                  else
                                    fluxg(comp0) += (teta*gradient_elem(poly,comp0,j) + (1.-teta)*gradient_elem(poly2,comp0,j))*(xg(poly,j)-xm);
                                }
                            }
                          fluxg(comp0) *= psc;
                        }
                    }
//
// Integration de u.n.flux
//
                  for (comp0=0; comp0<ncomp_ch_transporte; comp0++)
                    {
                      resu(num10,comp0) -= ( 0.5*(fluxsom(comp0)+fluxg(comp0)) );
                      resu(num20,comp0) += ( 0.5*(fluxsom(comp0)+fluxg(comp0)) );
                    }
                }
            }
        }
    } //!< fin de la boucle
  int voisine;
  nb_faces_perio = 0;
  double diff1,diff2;
// Dimensionnement du tableau des flux convectifs au bord du domaine
// de calcul
  DoubleTab& flux_b = flux_bords_;
  flux_b.resize(zone_VEF.nb_faces_bord(),ncomp_ch_transporte);
  flux_b = 0.;
// Boucle sur les bords pour traiter les conditions aux limites
// il y a prise en compte d'un terme de convection pour les
// conditions aux limites de Neumann_sortie_libre seulement
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Neumann_sortie_libre& la_sortie_libre = ref_cast(Neumann_sortie_libre,la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          for (num_face=num1; num_face<num2; num_face++)
            {
              psc =0;
              for (i=0; i<dimension; i++)
                psc += la_vitesse(num_face,i)*face_normales(num_face,i)*porosite_face(num_face);
              if (psc>0)
                for (i=0; i<ncomp_ch_transporte; i++)
                  {
                    resu(num_face,i) -= psc*transporte(num_face,i);
                    flux_b(num_face,i) -= psc*transporte(num_face,i);
                  }
              else
                {
                  for (i=0; i<ncomp_ch_transporte; i++)
                    {
                      resu(num_face,i) -= psc*la_sortie_libre.val_ext(num_face-num1,i);
                      flux_b(num_face,i) -= psc*la_sortie_libre.val_ext(num_face-num1,i);
                    }
                  fluent_(num_face) -= psc;
                }
            }
        }
      else if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          IntVect fait(le_bord.nb_faces());
          fait = 0;
          for (num_face=num1; num_face<num2; num_face++)
            {
              if (fait[num_face-num1] == 0)
                {
                  voisine = la_cl_perio.face_associee(num_face-num1) + num1;
                  for (int comp=0; comp<ncomp_ch_transporte; comp++)
                    {
                      diff1 = resu(num_face,comp)-tab(nb_faces_perio,comp);
                      diff2 = resu(voisine,comp)-tab(nb_faces_perio+voisine-num_face,comp);
                      resu(voisine,comp)  += diff1;
                      resu(num_face,comp) += diff2;
                      flux_b(voisine,comp) += diff1;
                      flux_b(num_face,comp) += diff2;
                    }
                  fait[num_face-num1]= 1;
                  fait[voisine-num1] = 1;
                }
              nb_faces_perio++;
            }
        }
    }
  modifier_flux(*this);
  return resu;
}
References Elem_VEF::calcul_vc(), convkschemas(), Domaine::coord_sommets(), Zone::creer_tableau_elements(), Objet_U::dimension, Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Zone_VEF::facette_normales(), Op_Conv_VEF_base::fluent, Operateur_base::flux_bords_, Cond_lim::frontiere_dis(), K, Elem_VEF_base::KEL(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), TRUSTVect< _TYPE_ >::line_size(), Op_VEF_Face::modifier_flux(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone::nb_faces_elem(), Elem_VEF::nb_facette(), Zone_dis_base::nb_front_Cl(), Zone::nb_som_elem(), Elem_geom::nb_som_face(), Zone_Cl_VEF::normales_facettes_Cl(), Front_VF::num_premiere_face(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), Objet_U::que_suis_je(), Zone_VEF::rang_elem_non_std(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Zone::sommet_elem(), sub_type, Zone::type_elem(), Zone_VEF::type_elem(), Zone_Cl_VEF::type_elem_Cl(), Neumann_sortie_libre::val_ext(), Deriv_Cond_lim_base::valeur(), Ref_Champ_Inc_base::valeur(), Deriv_Elem_VEF_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_base::valeur_a_sommet_compo(), Op_Conv_VEF_base::vitesse(), Op_Conv_VEF_base::vitesse_, Zone_VF::volumes(), Zone_VF::xp(), Zone_VF::xv(), and Zone_dis_base::zone().
associer()
void Op_Conv_kschemas_VEF::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch) override virtual
Implements Operateur_base.
Definition at line 42 of file Op_Conv_kschemas_VEF.cpp.
{
// CCa le 28/05/99 Le schema Kquick ne marche pas en paralle !!
  if(Process::nproc()>1)
    {
      Cerr<<"ATTENTION le kquick ne marche pas en parallele !!!"<<finl;
      exit();
    }
  Op_Conv_VEF_base::associer(zone_dis,zone_cl_dis,ch);
}
References Op_Conv_VEF_base::associer(), Cerr, Process::exit(), finl, and Process::nproc().
get_info()
const Type_info * Op_Conv_kschemas_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in OpVEF_Centre, and OpVEF_Quick.
Definition at line 20 of file Op_Conv_kschemas_VEF.cpp.
info()
const Type_info * Op_Conv_kschemas_VEF::info () static
Definition at line 20 of file Op_Conv_kschemas_VEF.cpp.
printOn()
Sortie & Op_Conv_kschemas_VEF::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in OpVEF_Centre, and OpVEF_Quick.
Definition at line 26 of file Op_Conv_kschemas_VEF.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Conv_kschemas_VEF::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in OpVEF_Centre, and OpVEF_Quick.
Definition at line 34 of file Op_Conv_kschemas_VEF.cpp.
{
  return s ;
}
self_cast() [1/2]
const Op_Conv_kschemas_VEF & Op_Conv_kschemas_VEF::self_cast (const Objet_U & r) static
Definition at line 20 of file Op_Conv_kschemas_VEF.cpp.
self_cast() [2/2]
Op_Conv_kschemas_VEF & Op_Conv_kschemas_VEF::self_cast (Objet_U & r) static
Definition at line 20 of file Op_Conv_kschemas_VEF.cpp.
Member Data Documentation
info_obj
const Type_info Op_Conv_kschemas_VEF::info_obj static
Definition at line 39 of file Op_Conv_kschemas_VEF.h.
K
double Op_Conv_kschemas_VEF::K protected
int caracterisant les differents schemas
Definition at line 47 of file Op_Conv_kschemas_VEF.h.
Referenced by ajouter(), OpVEF_Centre::OpVEF_Centre(), and OpVEF_Quick::OpVEF_Quick().
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Conv_kschemas_VEF.h
src/VEF/Operateurs/Op_Conv_kschemas_VEF.cpp