TRUST: Champ_front_uniforme Class Reference
Champ_front_uniforme Class Reference
classe Champ_front_uniforme
Classe derivee de Champ_front_base qui represente les
champs aux frontieres uniformes en espace et constants dans
le temps
#include <Champ_front_uniforme.h>
Public Member Functions
Champ_front_uniforme ()
~Champ_front_uniforme ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & valeurs_au_temps (double temps)
Renvoie les valeurs sans s'occuper du temps puisque le champ
est stationnaire.
virtual const DoubleTab & valeurs_au_temps (double temps) const
Renvoie les valeurs sans s'occuper du temps puisque le champ
est stationnaire.
virtual int avancer (double temps)
Avance en temps : rien a faire pour un champ stationnaire !
virtual int reculer (double temps)
Recule en temps : rien a faire pour un champ stationnaire !
Champ_front_base & affecter_ (const Champ_front_base &ch)
Renvoie l'objet upcaste en Champ_front_base&.
void valeurs_face (int, DoubleVect &) const
Renvoie le vecteur des valeurs du champ pour la face donnee.
virtual void changer_temps_futur (double temps, int i)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_front_uniforme & self_cast (Objet_U &)
static const Champ_front_uniforme & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le champ sur flot de sortie.
Imprime la taille du champ et la valeur (constante) sur
la frontiere.
virtual Entree & readOn (Entree &)
Lit le champ a partir d'un flot d'entree.
Format:
Champ_front_uniforme nb_compo vrel_1 ... [vrel_i].
Detailed Description
classe Champ_front_uniforme
Classe derivee de Champ_front_base qui represente les
champs aux frontieres uniformes en espace et constants dans
le temps
Definition at line 41 of file Champ_front_uniforme.h.
Constructor & Destructor Documentation
Champ_front_uniforme::Champ_front_uniforme ()
Definition at line 25 of file Champ_front_uniforme.cpp.
Champ_front_uniforme::~Champ_front_uniforme ()
Definition at line 25 of file Champ_front_uniforme.cpp.
Member Function Documentation
Champ_front_base & Champ_front_uniforme::affecter_ (const Champ_front_base & ch) [virtual]
Renvoie l'objet upcaste en Champ_front_base&.
Returns:
Champ_front_base&
Signification: (*this) upcaste en Champ_front_base&
Contraintes:
Implements Champ_front_base.
Definition at line 99 of file Champ_front_uniforme.cpp.
{
  return *this;
}
int Champ_front_uniforme::avancer (double temps) [virtual]
Avance en temps : rien a faire pour un champ stationnaire !
Reimplemented from Champ_front_base.
Definition at line 144 of file Champ_front_uniforme.cpp.
{
  return 1;
}
void Champ_front_uniforme::changer_temps_futur (double temps, int i) [virtual]
Reimplemented from Champ_front_base.
Definition at line 158 of file Champ_front_uniforme.cpp.
{
}
Objet_U * Champ_front_uniforme::cree_instance () [static]
Definition at line 25 of file Champ_front_uniforme.cpp.
int Champ_front_uniforme::duplique () const [virtual]
Implements Champ_front_base.
Definition at line 25 of file Champ_front_uniforme.cpp.
const Type_info * Champ_front_uniforme::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_base.
Definition at line 25 of file Champ_front_uniforme.cpp.
const Type_info * Champ_front_uniforme::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_base.
Definition at line 25 of file Champ_front_uniforme.cpp.
Sortie & Champ_front_uniforme::printOn (Sortie & os) const [protected, virtual]
Imprime le champ sur flot de sortie.
Imprime la taille du champ et la valeur (constante) sur
la frontiere.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_base.
Definition at line 45 of file Champ_front_uniforme.cpp.
References DoubleVect::size(), and Champ_front_base::valeurs().
{
  const DoubleTab& tab=valeurs();
  os << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    os << tab(0,i);
  return os;
}
Entree & Champ_front_uniforme::readOn (Entree & is) [protected, virtual]
Lit le champ a partir d'un flot d'entree.
Format:
Champ_front_uniforme nb_compo vrel_1 ... [vrel_i].
Returns:
Entree& is
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_base.
Definition at line 71 of file Champ_front_uniforme.cpp.
References Field_base::fixer_nb_comp(), Champ_front_base::les_valeurs, Champ_Proto::lire_dimension(), Objet_U::que_suis_je(), and DoubleTab::resize().
{
  int dim;
  DoubleTab& tab=les_valeurs->valeurs();
  dim=lire_dimension(is,que_suis_je());
  tab.resize(1,dim);
  fixer_nb_comp(dim);
  for(int i=0; i<dim; i++)
    is >> tab(0,i);
  return is;
}
int Champ_front_uniforme::reculer (double temps) [virtual]
Recule en temps : rien a faire pour un champ stationnaire !
Reimplemented from Champ_front_base.
Definition at line 151 of file Champ_front_uniforme.cpp.
{
  return 1;
}
const Champ_front_uniforme & Champ_front_uniforme::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_front_base.
Definition at line 25 of file Champ_front_uniforme.cpp.
Champ_front_uniforme & Champ_front_uniforme::self_cast (Objet_U & r) [static]
Reimplemented from Champ_front_base.
Definition at line 25 of file Champ_front_uniforme.cpp.
unsigned Champ_front_uniforme::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Champ_front_uniforme.cpp.
DoubleTab & Champ_front_uniforme::valeurs_au_temps (double temps) [virtual]
Renvoie les valeurs sans s'occuper du temps puisque le champ
est stationnaire.
Implements Champ_front_base.
Definition at line 129 of file Champ_front_uniforme.cpp.
References Champ_front_base::les_valeurs.
{
  return les_valeurs->valeurs();
}
const DoubleTab & Champ_front_uniforme::valeurs_au_temps (double temps) const [virtual]
Renvoie les valeurs sans s'occuper du temps puisque le champ
est stationnaire.
Implements Champ_front_base.
Definition at line 137 of file Champ_front_uniforme.cpp.
References Champ_front_base::les_valeurs.
{
  return les_valeurs->valeurs();
}
void Champ_front_uniforme::valeurs_face (int face, DoubleVect & var) const [virtual]
Renvoie le vecteur des valeurs du champ pour la face donnee.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ
Contraintes:
Reimplemented from Champ_front_base.
Definition at line 118 of file Champ_front_uniforme.cpp.
References Field_base::nb_compo_, DoubleVect::resize(), and Champ_front_base::valeurs().
{
  var.resize(nb_compo_);
  int i;
  for (i=0 ; i<nb_compo_ ; i++)
    var(i) = valeurs()(0,i);
}
Member Data Documentation
const Type_info Champ_front_uniforme::info_obj [static]
Reimplemented from Champ_front_base.
Definition at line 43 of file Champ_front_uniforme.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_front_uniforme.h
src/Kernel/Champs/Champ_front_uniforme.cpp