TRUST: Echange_contact_VDF_Plaque_Flux_Cte Class Reference
Echange_contact_VDF_Plaque_Flux_Cte Class Reference
#include <Echange_contact_VDF_Plaque_Flux_Cte.h>
Public Member Functions
Echange_contact_VDF_Plaque_Flux_Cte ()
~Echange_contact_VDF_Plaque_Flux_Cte ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual double calculer_coefficient_echange (int i)
virtual double volume (double s, double d)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Echange_contact_VDF_Plaque_Flux_Cte & self_cast (Objet_U &)
static const
Echange_contact_VDF_Plaque_Flux_Cte & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
Detailed Description
Definition at line 42 of file Echange_contact_VDF_Plaque_Flux_Cte.h.
Constructor & Destructor Documentation
Echange_contact_VDF_Plaque_Flux_Cte::Echange_contact_VDF_Plaque_Flux_Cte ()
Definition at line 33 of file Echange_contact_VDF_Plaque_Flux_Cte.cpp.
Echange_contact_VDF_Plaque_Flux_Cte::~Echange_contact_VDF_Plaque_Flux_Cte ()
Definition at line 33 of file Echange_contact_VDF_Plaque_Flux_Cte.cpp.
Member Function Documentation
double Echange_contact_VDF_Plaque_Flux_Cte::calculer_coefficient_echange (int i) [virtual]
Calcule le coeff d echange suivant la correlation de Shah
Reimplemented from Echange_contact_Correlation_VDF.
Definition at line 52 of file Echange_contact_VDF_Plaque_Flux_Cte.cpp.
References Echange_contact_Correlation_VDF::getDh(), and Echange_contact_Correlation_VDF::getLambda().
{
  double Nu;
// double x_star;
  /*x_star = coord(i)-coord(0);
  if (x_star < 2e-4)
  {
  Nu = 1.49*pow(x_star,-0.3333);
  }
  else if (x_star > 1e-3)
  {
  Nu = 8.235+8.68*pow(1000*x_star,-0.506)*exp(-164*x_star);
  }
  else
  Nu = 1.49*pow(x_star,-0.3333)-0.4;
// Re = fabs(getQh()*getDh()/getMu(i));
// Pr = getMu(i)*getCp()/getLambda(i);
  */
  Nu = 8.24;
  return Nu*getLambda(i)/getDh();
}
Objet_U * Echange_contact_VDF_Plaque_Flux_Cte::cree_instance () [static]
Reimplemented from Echange_contact_Correlation_VDF.
Definition at line 33 of file Echange_contact_VDF_Plaque_Flux_Cte.cpp.
int Echange_contact_VDF_Plaque_Flux_Cte::duplique () const [virtual]
Reimplemented from Echange_contact_Correlation_VDF.
Definition at line 33 of file Echange_contact_VDF_Plaque_Flux_Cte.cpp.
const Type_info * Echange_contact_VDF_Plaque_Flux_Cte::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Echange_contact_Correlation_VDF.
Definition at line 33 of file Echange_contact_VDF_Plaque_Flux_Cte.cpp.
const Type_info * Echange_contact_VDF_Plaque_Flux_Cte::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Echange_contact_Correlation_VDF.
Definition at line 33 of file Echange_contact_VDF_Plaque_Flux_Cte.cpp.
Sortie & Echange_contact_VDF_Plaque_Flux_Cte::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Echange_contact_Correlation_VDF.
Definition at line 38 of file Echange_contact_VDF_Plaque_Flux_Cte.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Echange_contact_VDF_Plaque_Flux_Cte::readOn (Entree & s) [protected, virtual]
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
Returns:
Entree&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Echange_contact_Correlation_VDF.
Definition at line 43 of file Echange_contact_VDF_Plaque_Flux_Cte.cpp.
{
  return Echange_contact_Correlation_VDF::readOn(is);
}
const Echange_contact_VDF_Plaque_Flux_Cte & Echange_contact_VDF_Plaque_Flux_Cte::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Echange_contact_Correlation_VDF.
Definition at line 33 of file Echange_contact_VDF_Plaque_Flux_Cte.cpp.
Echange_contact_VDF_Plaque_Flux_Cte & Echange_contact_VDF_Plaque_Flux_Cte::self_cast (Objet_U & r) [static]
Reimplemented from Echange_contact_Correlation_VDF.
Definition at line 33 of file Echange_contact_VDF_Plaque_Flux_Cte.cpp.
unsigned Echange_contact_VDF_Plaque_Flux_Cte::taille_memoire () const [virtual]
Reimplemented from Echange_contact_Correlation_VDF.
Definition at line 33 of file Echange_contact_VDF_Plaque_Flux_Cte.cpp.
double Echange_contact_VDF_Plaque_Flux_Cte::volume (double s, double d) [virtual]
Calcule le volume d'une tranche de la section de surface laterale s et de diametre hydraulique d.
Reimplemented from Echange_contact_Correlation_VDF.
Definition at line 78 of file Echange_contact_VDF_Plaque_Flux_Cte.cpp.
{
  return s*0.25*d;
}
Member Data Documentation
const Type_info Echange_contact_VDF_Plaque_Flux_Cte::info_obj [static]
Reimplemented from Echange_contact_Correlation_VDF.
Definition at line 45 of file Echange_contact_VDF_Plaque_Flux_Cte.h.
The documentation for this class was generated from the following files:
src/VDF/Cond_Lim/Echange_contact_VDF_Plaque_Flux_Cte.h
src/VDF/Cond_Lim/Echange_contact_VDF_Plaque_Flux_Cte.cpp