TRUST: Champ_Q1NC Class Reference
Champ_Q1NC Class Reference
#include <Champ_Q1NC.h>
Public Member Functions
Champ_Q1NC ()
~Champ_Q1NC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Zone_dis_base & zone_dis_base () const override
void associer_zone_dis_base (const Zone_dis_base &) override
void verifie_valeurs_cl () override
const Zone_VEF & zone_vef () const override
int compo_normale_sortante (int) const
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
void cal_rot_ordre1 (DoubleTab &)
void gradient (DoubleTab &)
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
double valeur_a_sommet_compo (int num_som, int le_poly, int ncomp) const override
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &tab_valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &tab_valeurs, int ncomp) const override
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const override
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
NE FAIT RIEN
Methode a surcharger.
int fixer_nb_valeurs_nodales (int n) override
Public Member Functions inherited from Champ_Inc_base
~Champ_Inc_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_Inc_base ()
int fixer_nb_valeurs_nodales (int) override
double changer_temps (const double temps) override
Fixe le temps du champ.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps du champ inconnue.
WEC : Maintenant si on l'appelle 2 fois de suite avec le meme
argument, la 2eme ne fait rien.
int reprendre (Entree &) override
Lecture d'un champ inconnue a partir d'un flot d'entree
en vue d'une reprise.
int sauvegarder (Sortie &) const override
Sauvegarde le champ inconnue sur un flot de sortie.
Ecrit un identifiant, les valeurs du champs, et
la date (le temps au moment de la sauvegarde).
Champ_base & affecter_compo (const Champ_base &, int compo) override
Affectation d'une composante d'un Champ quelconque<br>(Champ_base) dans une composante d'un champ inconnue.
Champ_base & affecter_ (const Champ_base &) override
Affectation d'un Champ generique (Champ_base) dans
un champ inconnue.
virtual void verifie_valeurs_cl ()
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ au temps courant.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temp courant<br>(version const)
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
Calcule la valeur du champs inconnue a la position specifiee.
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
Calcule les valeurs du champs inconnue aux positions specifiees.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
Calcule les valeurs du champs inconnue aux positions specifiees,
pour une certaine composante du champ.
int nb_valeurs_nodales () const override
Returns the number of "real" geometric positions of the
degrees of freedom, or -1 if not applicable (fields with multiple
localisations)
virtual int fixer_nb_valeurs_temporelles (int)
Fixe le nombre de valeurs temporelles a conserver.
(un nombre different suivant le schema en temps utilise)
Appelle Roue::fixer_nb_cases(int)
virtual int nb_valeurs_temporelles () const
Renvoie le nombre de valeurs temporelles actuellement conservees.
Cette valeur est stockee par la Roue du Champ_Inc_base.
double changer_temps_futur (double, int i=1)
Fixe le temps du ieme champ futur.
double changer_temps_passe (double, int i=1)
Fixe le temps du ieme champ passe.
double recuperer_temps_futur (int i=1) const
Retourne le temps du ieme champ futur.
double recuperer_temps_passe (int i=1) const
Retourne le temps du ieme champ passe.
DoubleTab & valeurs (double temps) override
Renvoie les valeurs du champs a l'instant temps.
const DoubleTab & valeurs (double temps) const override
Renvoie les valeurs du champs a l'instant temps.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
DoubleTab & futur (int i=1) override
Renvoie les valeurs du champs a l'instant t+i.
const DoubleTab & futur (int i=1) const override
Renvoie les valeurs du champs a l'instant t+i.
(version const)
DoubleTab & passe (int i=1) override
Renvoie les valeurs du champs a l'instant t-i.
const DoubleTab & passe (int i=1) const override
Renvoie les valeurs du champs a l'instant t-i.
(version const)
Champ_Inc_base & avancer (int i=1)
Avance le pointeur courant de i pas de temps,
dans la liste des valeurs temporelles conservees.
Champ_Inc_base & reculer (int i=1)
Recule le pointeur courant de i pas de temps,
dans la liste des valeurs temporelles conservees.
int lire_donnees (Entree &)
Lit les valeurs du champs a partir d'un flot d'entree.
Format de lecture:
int [LE NOMBRE DE VALEURS A LIRE]
[LIRE LE NOMBRE DE VALEUR VOULUES].
virtual void associer_eqn (const Equation_base &)
Associe le champ a l'equation dont il represente une inconnue.
Simple appel a MorEqn::associer_eqn(const Equation_base&)
virtual void associer_zone_cl_dis (const Zone_Cl_dis &)
int imprime (Sortie &, int) const override
int a_une_zone_dis_base () const override
Par defaut, on ne sait pas si une zone_dis_base sera definie.
const Zone_Cl_dis & zone_Cl_dis () const
Zone_Cl_dis & zone_Cl_dis ()
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
NE FAIT RIEN
Methode a surcharger.
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
Simple appel a:
Champ_Inc_base::remplir_coord_noeuds_et_polys(DoubleTab&,IntVect& poly)
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const =0
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
Simple appel a
Champ_Inc_base::remplir_coord_noeuds(DoubleTab&)
virtual double integrale_espace (int ncomp) const
const Domaine & domaine () const
const tabs_t & derivees () const
void init_champ_calcule (const Objet_U &obj, fonc_calc_t fonc)
void reset_champ_calcule ()
DoubleTab valeur_aux_bords () const override
renvoie la valeur du champ aux faces de bord
virtual void creer_espace_distant (int dummy)
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champ_Q1NC_impl
~Champ_Q1NC_impl () override
double fonction_forme_2D (double x, double y, int le_poly, int face)
double fonction_forme_3D (double x, double y, double z, int le_poly, int face)
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double calcule_valeur_a_elem_compo (double xs, double ys, double zs, int le_poly, int ncomp) const
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
double valeur_a_sommet_compo (int num_som, int le_poly, int ncomp) const
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const override
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
void transforme_coord2D ()
void transforme_coord3D ()
Public Member Functions inherited from Champ_implementation
virtual ~Champ_implementation ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const =0
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const =0
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Q1NC & self_cast (Objet_U &)
static const Champ_Q1NC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Inc_base
static const Type_info * info ()
static Champ_Inc_base & self_cast (Objet_U &)
static const Champ_Inc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Member Functions inherited from Champ_Q1NC_impl
static double fonction_forme_2D_normalise (double x, double y, int face)
static double fonction_forme_3D_normalise (double x, double y, double z, int face)
static DoubleTab & Derivee_fonction_forme_2D_normalise (double u, double v, DoubleTab &DF)
static DoubleTab & Derivee_fonction_forme_3D_normalise (double u, double v, double w, DoubleTab &DF)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Inc_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Entree & readOn (Entree &) override
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Protected Member Functions inherited from Champ_Inc_base
Sortie & printOn (Sortie &x) const override
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Entree & readOn (Entree &) override
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
virtual void creer_tableau_distribue (const MD_Vector &, Array_base::Resize_Options=Array_base::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Champ_Q1NC_impl
virtual const Zone_VEF & zone_vef () const =0
DoubleTab & trace (const Frontiere_dis_base &fr, const DoubleTab &y, DoubleTab &x, int distant) const
Protected Member Functions inherited from Champ_implementation
virtual const Champ_base & le_champ () const =0
virtual Champ_base & le_champ ()=0
const Zone & zone () const
virtual const Zone_dis_base & zone_dis_base () const
Private Member Functions
const Champ_base & le_champ () const override
Champ_base & le_champ () override
Private Attributes
Ref_Zone_VEF la_zone_VEF
Additional Inherited Members
Protected Attributes inherited from Champ_Inc_base
Roue_ptr les_valeurs
Ref_Zone_Cl_dis ma_zone_cl_dis
fonc_calc_t fonc_calc_
int fonc_calc_init_ = 0
Ref_Objet_U obj_calc_
DoubleTab val_bord_
tabs_t deriv_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Protected Attributes inherited from Champ_Q1NC_impl
DoubleTab tab_param
Detailed Description
Definition at line 24 of file Champ_Q1NC.h.
Constructor & Destructor Documentation
Champ_Q1NC()
Champ_Q1NC::Champ_Q1NC ()
Definition at line 22 of file Champ_Q1NC.cpp.
~Champ_Q1NC()
Champ_Q1NC::~Champ_Q1NC ()
Definition at line 22 of file Champ_Q1NC.cpp.
Member Function Documentation
associer_zone_dis_base()
void Champ_Q1NC::associer_zone_dis_base (const Zone_dis_base & z_dis) override virtual
Reimplemented from Champ_base.
Definition at line 57 of file Champ_Q1NC.cpp.
{
  la_zone_VEF=ref_cast(Zone_VEF, z_dis);
}
References la_zone_VEF, and ref_cast.
Referenced by VEF_1D::vitesse().
cal_rot_ordre1()
void Champ_Q1NC::cal_rot_ordre1 (DoubleTab & vorticite)
Definition at line 116 of file Champ_Q1NC.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const int nb_elem = zone_VEF.nb_elem();
  DoubleTab gradient_elem(0, dimension, dimension);
// le tableau est initialise dans la methode gradient():
  zone_VEF.zone().creer_tableau_elements(gradient_elem, Array_base::NOCOPY_NOINIT);
  gradient(gradient_elem);
  Debog::verifier("apres calcul gradient",gradient_elem);
  int num_elem;
  switch(dimension)
    {
    case 2 :
      {
        for (num_elem=0; num_elem<nb_elem; num_elem++)
          {
            vorticite(num_elem)=gradient_elem(num_elem,1,0)-gradient_elem(num_elem,0,1);
          }
      }
      break;
    case 3 :
      {
        for (num_elem=0; num_elem<nb_elem; num_elem++)
          {
            vorticite(num_elem,0)=gradient_elem(num_elem,2,1)-gradient_elem(num_elem,1,2);
            vorticite(num_elem,1)=gradient_elem(num_elem,0,2)-gradient_elem(num_elem,2,0);
            vorticite(num_elem,2)=gradient_elem(num_elem,1,0)-gradient_elem(num_elem,0,1);
          }
      }
    }
  Debog::verifier("apres calcul vort",vorticite);
  return ;
}
References Zone::creer_tableau_elements(), Objet_U::dimension, gradient(), la_zone_VEF, Zone_dis_base::nb_elem(), Array_base::NOCOPY_NOINIT, Ref_Zone_VEF::valeur(), Debog::verifier(), and Zone_dis_base::zone().
Referenced by Rotationnel_Champ_Q1NC::me_calculer().
compo_normale_sortante()
int Champ_Q1NC::compo_normale_sortante (int num_face) const
Definition at line 102 of file Champ_Q1NC.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  double vit_norm =0;
  for (int ncomp=0; ncomp<nb_comp(); ncomp++)
    vit_norm += (*this)(num_face,ncomp)*zone_VEF.face_normales(num_face,ncomp);
  return (vit_norm > 0);
}
References Zone_VEF::face_normales(), la_zone_VEF, Field_base::nb_comp(), and Ref_Zone_VEF::valeur().
cree_instance()
Objet_U * Champ_Q1NC::cree_instance () static
Definition at line 22 of file Champ_Q1NC.cpp.
duplique()
int Champ_Q1NC::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file Champ_Q1NC.cpp.
fixer_nb_valeurs_nodales()
int Champ_Q1NC::fixer_nb_valeurs_nodales (int n) override virtual
Reimplemented from Champ_Inc_base.
Definition at line 203 of file Champ_Q1NC.cpp.
{
  const MD_Vector& md = zone_vef().md_vector_faces();
  creer_tableau_distribue(md);
  return 1;
}
References Champ_Inc_base::creer_tableau_distribue(), Zone_VF::md_vector_faces(), and zone_vef().
Referenced by VEF_1D::vitesse().
get_info()
const Type_info * Champ_Q1NC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 22 of file Champ_Q1NC.cpp.
gradient()
void Champ_Q1NC::gradient (DoubleTab & gradient_elem)
< Espace reel uniquement
Definition at line 154 of file Champ_Q1NC.cpp.
{
// Calcul du gradient de la vitesse pour le calcul de la vorticite
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const DoubleTab& vitesse = equation().inconnue().valeurs();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const int nb_faces = zone_VEF.nb_faces();
  const int nb_elem = zone_VEF.nb_elem();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int premiere_face_int = zone_VEF.premiere_face_int();
  const DoubleVect& volumes = zone_VEF.volumes();
  assert(gradient_elem.dimension(0) == nb_elem);
  assert(gradient_elem.dimension(1) == dimension);
  assert(gradient_elem.dimension(2) == dimension);
  operator_egal(gradient_elem, 0.); //!< Espace reel uniquement
  int icomp,fac,i,elem1,elem2;
// Boucle sur les faces
  for (fac=0; fac< premiere_face_int; fac++)
    {
      elem1=face_voisins(fac,0);
      for (icomp=0; icomp<dimension; icomp++)
        for (i=0; i<dimension; i++)
          {
            gradient_elem(elem1, icomp, i) +=
              face_normales(fac,i)*vitesse(fac,icomp);
          }
    }
  for (; fac<nb_faces; fac++)
    {
      elem1=face_voisins(fac,0);
      elem2=face_voisins(fac,1);
      for (icomp=0; icomp<dimension; icomp++)
        for (i=0; i<dimension; i++)
          {
            gradient_elem(elem1, icomp, i) +=
              face_normales(fac,i)*vitesse(fac,icomp);
            if(elem2<nb_elem)
              gradient_elem(elem2, icomp, i) -=
                face_normales(fac,i)*vitesse(fac,icomp);
          }
    }
  tab_divide_any_shape(gradient_elem, volumes);
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Equation_base::inconnue(), la_zone_VEF, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), operator_egal(), Zone_VF::premiere_face_int(), tab_divide_any_shape(), Ref_Zone_VEF::valeur(), Champ_Inc::valeurs(), and Zone_VF::volumes().
Referenced by cal_rot_ordre1().
info()
const Type_info * Champ_Q1NC::info () static
Definition at line 22 of file Champ_Q1NC.cpp.
le_champ() [1/2]
const Champ_base & Champ_Q1NC::le_champ (void) const inline override private virtual
Implements Champ_implementation.
Definition at line 69 of file Champ_Q1NC.h.
{
  return *this;
}
le_champ() [2/2]
Champ_base & Champ_Q1NC::le_champ (void) inline override private virtual
Implements Champ_implementation.
Definition at line 74 of file Champ_Q1NC.h.
{
  return *this;
}
printOn()
Sortie & Champ_Q1NC::printOn (Sortie & os) const override protected virtual
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 27 of file Champ_Q1NC.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Q1NC::readOn (Entree & is) override protected virtual
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 34 of file Champ_Q1NC.cpp.
{
  lire_donnees(s) ;
  return s ;
}
References Champ_Inc_base::lire_donnees().
remplir_coord_noeuds()
DoubleTab & Champ_Q1NC::remplir_coord_noeuds (DoubleTab & positions) const inline override virtual
Implements Champ_Inc_base.
Definition at line 124 of file Champ_Q1NC.h.
{
  return Champ_Q1NC_impl::remplir_coord_noeuds(positions);
}
References Champ_Q1NC_impl::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
int Champ_Q1NC::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const inline override virtual
NE FAIT RIEN
Methode a surcharger.
Returns
int
Signification: renvoie toujours 0
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 129 of file Champ_Q1NC.h.
{
  return Champ_Q1NC_impl::remplir_coord_noeuds_et_polys(positions, polys);
}
References Champ_Q1NC_impl::remplir_coord_noeuds_et_polys().
self_cast() [1/2]
const Champ_Q1NC & Champ_Q1NC::self_cast (const Objet_U & r) static
Definition at line 22 of file Champ_Q1NC.cpp.
self_cast() [2/2]
Champ_Q1NC & Champ_Q1NC::self_cast (Objet_U & r) static
Definition at line 22 of file Champ_Q1NC.cpp.
taille_memoire()
unsigned Champ_Q1NC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file Champ_Q1NC.cpp.
trace()
DoubleTab & Champ_Q1NC::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const override virtual
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
Reimplemented from Champ_Inc_base.
Definition at line 111 of file Champ_Q1NC.cpp.
{
  return Champ_Q1NC_impl::trace(fr, valeurs(tps), x,distant);
}
References Champ_Q1NC_impl::trace(), and Champ_Inc_base::valeurs().
valeur_a_elem()
DoubleVect & Champ_Q1NC::valeur_a_elem (const DoubleVect & position, DoubleVect & val, int le_poly) const inline override virtual
Implements Champ_implementation.
Definition at line 79 of file Champ_Q1NC.h.
{
  return Champ_Q1NC_impl::valeur_a_elem(position, val, le_poly);
}
References Champ_Q1NC_impl::valeur_a_elem().
valeur_a_elem_compo()
double Champ_Q1NC::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline override virtual
Implements Champ_implementation.
Definition at line 86 of file Champ_Q1NC.h.
{
  return Champ_Q1NC_impl::valeur_a_elem_compo(position, le_poly, ncomp);
}
References Champ_Q1NC_impl::valeur_a_elem_compo().
valeur_a_sommet_compo()
double Champ_Q1NC::valeur_a_sommet_compo (int sommet, int le_poly, int compo) const inline override virtual
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
Reimplemented from Champ_base.
Definition at line 92 of file Champ_Q1NC.h.
{
  return Champ_Q1NC_impl::valeur_a_sommet_compo(num_som, le_poly, ncomp);
}
References Champ_Q1NC_impl::valeur_a_sommet_compo().
valeur_aux_elems()
DoubleTab & Champ_Q1NC::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & tab_valeurs) const inline override virtual
Implements Champ_implementation.
Definition at line 98 of file Champ_Q1NC.h.
{
  return Champ_Q1NC_impl::valeur_aux_elems(positions, les_polys, tab_valeurs);
}
References Champ_Q1NC_impl::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_Q1NC::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & tab_valeurs, int ncomp) const inline override virtual
Implements Champ_implementation.
Definition at line 105 of file Champ_Q1NC.h.
{
  return Champ_Q1NC_impl::valeur_aux_elems_compo(positions, les_polys, tab_valeurs, ncomp);
}
References Champ_Q1NC_impl::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_Q1NC::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const inline override virtual
Implements Champ_implementation.
Definition at line 113 of file Champ_Q1NC.h.
{
  return Champ_Q1NC_impl::valeur_aux_sommets(dom, val);
}
References Champ_Q1NC_impl::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Q1NC::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int comp) const inline override virtual
Implements Champ_implementation.
Definition at line 118 of file Champ_Q1NC.h.
{
  return Champ_Q1NC_impl::valeur_aux_sommets_compo(dom, val, comp);
}
References Champ_Q1NC_impl::valeur_aux_sommets_compo().
verifie_valeurs_cl()
void Champ_Q1NC::verifie_valeurs_cl () override virtual
Reimplemented from Champ_Inc_base.
Definition at line 64 of file Champ_Q1NC.cpp.
{
  const Zone_Cl_dis_base& zcl = equation().zone_Cl_dis().valeur();
  int nb_cl = zcl.nb_cond_lim();
  DoubleTab& ch_tab = valeurs();
  int nb_compo = nb_comp();
  int ndeb,nfin,num_face;
  for (int i=0; i<nb_cl; i++)
    {
      const Cond_lim_base& la_cl = zcl.les_conditions_limites(i).valeur();
      if (sub_type(Periodique,la_cl))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          ndeb = le_bord.num_premiere_face();
          nfin = ndeb + le_bord.nb_faces();
          int voisine;
          double moy;
          for (num_face=ndeb; num_face<nfin; num_face++)
            {
              voisine = la_cl_perio.face_associee(num_face-ndeb) + ndeb;
              for (int comp=0; comp<nb_compo; comp++)
                {
                  if (ch_tab(num_face,comp) != ch_tab(voisine,comp))
                    {
                      moy = 0.5*(ch_tab(num_face,comp) + ch_tab(voisine,comp));
                      ch_tab(num_face,comp) = moy;
                      ch_tab(voisine,comp) = moy;
                    }
                }
            }
        }
    }
  ch_tab.echange_espace_virtuel();
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), Periodique::face_associee(), Cond_lim_base::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Field_base::nb_comp(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Champ_Inc_base::valeurs(), and Equation_base::zone_Cl_dis().
zone_dis_base()
const Zone_dis_base & Champ_Q1NC::zone_dis_base () const override virtual
Reimplemented from Champ_implementation.
Definition at line 52 of file Champ_Q1NC.cpp.
{
  return la_zone_VEF.valeur();
}
References la_zone_VEF, and Ref_Zone_VEF::valeur().
Referenced by VEF_discretisation::creer_champ_vorticite().
zone_vef()
const Zone_VEF & Champ_Q1NC::zone_vef () const inline override virtual
Implements Champ_Q1NC_impl.
Definition at line 135 of file Champ_Q1NC.h.
{
  return la_zone_VEF.valeur();
}
References la_zone_VEF, and Ref_Zone_VEF::valeur().
Referenced by fixer_nb_valeurs_nodales(), and Zone_Cl_VEF::imposer_cond_lim().
Member Data Documentation
info_obj
const Type_info Champ_Q1NC::info_obj static
Definition at line 27 of file Champ_Q1NC.h.
la_zone_VEF
Ref_Zone_VEF Champ_Q1NC::la_zone_VEF private
Definition at line 62 of file Champ_Q1NC.h.
Referenced by associer_zone_dis_base(), cal_rot_ordre1(), compo_normale_sortante(), gradient(), zone_dis_base(), and zone_vef().
The documentation for this class was generated from the following files:
src/VEF/Champs/Champ_Q1NC.h
src/VEF/Champs/Champ_Q1NC.cpp