TRUST: Op_Conv_VEF_base Class Reference
Op_Conv_VEF_base Class Reference
class Op_Conv_VEF_base
Classe de base des operateurs de convection VEF
#include <Op_Conv_VEF_base.h>
Public Member Functions
Op_Conv_VEF_base ()
~Op_Conv_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_vitesse (const Champ_base &) override
const Champ_Inc_base & vitesse () const
Champ_Inc_base & vitesse ()
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
void abortTimeStep () override
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_dt_local (DoubleTab &) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_fluent (DoubleVect &) const
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_zone_cl_dis (const Zone_Cl_dis_base &) override
int phi_u_transportant (const Equation_base &eq) const
definit si l'on convecte psi avec phi*u ou avec u
Public Member Functions inherited from Operateur_Conv_base
Operateur_Conv_base ()
initialise dt_stab_conv a -123
~Operateur_Conv_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_vitesse (const Champ_base &vit)=0
double dt_stab_conv () const
void fixer_dt_stab_conv (double dt)
virtual void associer_norme_vitesse (const Champ_base &norme_vitesse)
virtual void associer_vitesse_pour_pas_de_temps (const Champ_base &vitesse)
virtual void set_incompressible (const int)
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Static Public Member Functions
static const Type_info * info ()
static Op_Conv_VEF_base & self_cast (Objet_U &)
static const Op_Conv_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Conv_base
static const Type_info * info ()
static Operateur_Conv_base & self_cast (Objet_U &)
static const Operateur_Conv_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Conv_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Attributes
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base vitesse_
DoubleVect fluent
tableau qui sert pour le calcul du pas de temps de stabilite
int jeton
int roue
Protected Attributes inherited from Operateur_Conv_base
Ref_Champ_base la_norme_vitesse
Ref_Champ_base vitesse_pour_pas_de_temps_
double dt_stab_conv_
int incompressible_ = 1
incompressible_= 1 -> l'operateur discretise div(v x inco), incompressible_ = 0 -> il discretise v.grad(inco)
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Conv_VEF_base
Classe de base des operateurs de convection VEF
Definition at line 47 of file Op_Conv_VEF_base.h.
Constructor & Destructor Documentation
Op_Conv_VEF_base()
Op_Conv_VEF_base::Op_Conv_VEF_base ()
Definition at line 28 of file Op_Conv_VEF_base.cpp.
~Op_Conv_VEF_base()
Op_Conv_VEF_base::~Op_Conv_VEF_base () override
Definition at line 28 of file Op_Conv_VEF_base.cpp.
Member Function Documentation
abortTimeStep()
void Op_Conv_VEF_base::abortTimeStep () override virtual
Reimplemented from Operateur_base.
Definition at line 62 of file Op_Conv_VEF_base.cpp.
{
  Operateur_Conv_base::abortTimeStep();
}
References Operateur_base::abortTimeStep().
associer()
void Op_Conv_VEF_base::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc &) override virtual
Implements Operateur_base.
Definition at line 218 of file Op_Conv_VEF_base.cpp.
{
  const Zone_VEF& zvef = ref_cast(Zone_VEF,zone_dis.valeur());
  const Zone_Cl_VEF& zclvef = ref_cast(Zone_Cl_VEF,zone_cl_dis.valeur());
  la_zone_vef = zvef;
  la_zcl_vef = zclvef;
  //******************************************************************************
  // Initialisation des jetons pour l'alternance (kamoulox !)
  //******************************************************************************
  Cerr << "Initialisation de la roue pour la permutation des schemas de convection" << finl;
  roue= -1;
  //  roue2=-1;
  la_zone_vef.valeur().creer_tableau_faces(fluent);
}
References Cerr, Zone_VF::creer_tableau_faces(), finl, fluent, la_zcl_vef, la_zone_vef, ref_cast, roue, Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), and Ref_Zone_VEF::valeur().
Referenced by Op_Conv_kschemas_VEF::associer().
associer_vitesse()
void Op_Conv_VEF_base::associer_vitesse (const Champ_base & vit) override virtual
Implements Operateur_Conv_base.
Definition at line 56 of file Op_Conv_VEF_base.cpp.
{
  vitesse_ = ref_cast(Champ_Inc_base,vit);
}
References ref_cast, and vitesse_.
associer_zone_cl_dis()
void Op_Conv_VEF_base::associer_zone_cl_dis (const Zone_Cl_dis_base & zone_cl_dis) override virtual
Reimplemented from Operateur_base.
Definition at line 212 of file Op_Conv_VEF_base.cpp.
{
  const Zone_Cl_VEF& zclvef = ref_cast(Zone_Cl_VEF,zone_cl_dis);
  la_zcl_vef = zclvef;
}
References la_zcl_vef, and ref_cast.
calculer()
DoubleTab & Op_Conv_VEF_base::calculer (const DoubleTab & transporte, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 243 of file Op_Conv_VEF_base.cpp.
{
  resu = 0;
  return ajouter(transporte,resu);
}
References Operateur_base::ajouter().
calculer_dt_local()
void Op_Conv_VEF_base::calculer_dt_local (DoubleTab & dt_face) const override virtual
Reimplemented from Operateur_base.
Definition at line 268 of file Op_Conv_VEF_base.cpp.
{
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const DoubleVect& volumes_entrelaces =  zone_VEF.volumes_entrelaces();
  const DoubleVect& volumes_entrelaces_Cl = zone_Cl_VEF.volumes_entrelaces_Cl();
  int nb_faces= zone_VEF.nb_faces();
  dt_face=(volumes_entrelaces);
  remplir_fluent(fluent);
  for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      for (int num_face=ndeb; num_face<nfin; num_face++)
        {
          if( sup_strict(fluent[num_face], 1.e-30) )
            dt_face(num_face)= volumes_entrelaces_Cl(num_face)/fluent[num_face];
          else
            dt_face(num_face) = -1.;
        }
    }
  //Non-standard internal faces
  int ndeb = zone_VEF.premiere_face_int();
  int nfin = zone_VEF.premiere_face_std();
  for (int num_face=ndeb; num_face<nfin; num_face++)
    {
      if( sup_strict(fluent[num_face], 1.e-30) )
        dt_face(num_face)= volumes_entrelaces(num_face)/fluent[num_face];
      else
        dt_face(num_face) = -1.;
    }
  //The standard internal faces
  ndeb = nfin;
  nfin = zone_VEF.nb_faces();
  for (int num_face=ndeb; num_face<nfin; num_face++)
    {
      if( sup_strict(fluent[num_face], 1.e-30) )
        dt_face(num_face)= volumes_entrelaces(num_face)/fluent[num_face];
      else
        dt_face(num_face) = -1.;
    }
  double max_dt_local= dt_face.mp_max_abs_vect();
  for(int i=0; i<nb_faces; i++)
    {
      if(! sup_strict(dt_face(i), 1.e-16))
        dt_face(i) = max_dt_local;
    }
  dt_face.echange_espace_virtuel();
  for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int nb_faces_bord=le_bord.nb_faces();
          for (int ind_face=0; ind_face<nb_faces_bord; ind_face++)
            {
              int ind_face_associee = la_cl_perio.face_associee(ind_face);
              int face = le_bord.num_face(ind_face);
              int face_associee = le_bord.num_face(ind_face_associee);
              if (!est_egal(dt_face(face),dt_face(face_associee),1.e-8))
                {
                  dt_face(face) = std::min(dt_face(face),dt_face(face_associee));
                }
            }
        }
    }
  dt_face.echange_espace_virtuel();
// dt_conv_locaux=dt_face;
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), est_egal(), Periodique::face_associee(), face_associee, fluent, Cond_lim::frontiere_dis(), la_zcl_vef, la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::mp_max_abs_vect(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), Zone_VEF::premiere_face_std(), ref_cast, remplir_fluent(), sub_type, sup_strict(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Zone_VF::volumes_entrelaces(), and Zone_Cl_VEF::volumes_entrelaces_Cl().
calculer_dt_stab()
double Op_Conv_VEF_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 67 of file Op_Conv_VEF_base.cpp.
{
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const DoubleVect& volumes_entrelaces = zone_VEF.volumes_entrelaces();
  const DoubleVect& volumes_entrelaces_Cl = zone_Cl_VEF.volumes_entrelaces_Cl();
  remplir_fluent(fluent);
  if (vitesse().le_nom()=="rho_u" && equation().probleme().is_dilatable())
    diviser_par_rho_si_dilatable(fluent,equation().milieu());
  double dt_face,dt_stab =1.e30;
// On traite les conditions aux limites
// Si une face porte une condition de Dirichlet on n'en tient pas compte
// dans le calcul de dt_stab
  for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if ( (sub_type(Dirichlet,la_cl.valeur()))
           ||
           (sub_type(Dirichlet_homogene,la_cl.valeur()))
         )
        ;
      else
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
              dt_face = volumes_entrelaces_Cl(num_face)/(fluent[num_face]+1.e-30);
              dt_stab = (dt_face < dt_stab) ? dt_face : dt_stab;
            }
        }
    }
// On traite les faces internes non standard
  int ndeb = zone_VEF.premiere_face_int();
  int nfin = zone_VEF.premiere_face_std();
  for (int num_face=ndeb; num_face<nfin; num_face++)
    {
      dt_face = volumes_entrelaces_Cl(num_face)/(fluent[num_face]+DMINFLOAT);
      dt_stab =(dt_face < dt_stab) ? dt_face : dt_stab;
    }
// On traite les faces internes standard
  ndeb = nfin;
  nfin = zone_VEF.nb_faces();
  for (int num_face=ndeb; num_face<nfin; num_face++)
    {
      dt_face = volumes_entrelaces(num_face)/(fluent[num_face]+DMINFLOAT);
      dt_stab =(dt_face < dt_stab) ? dt_face : dt_stab;
    }
  dt_stab = Process::mp_min(dt_stab);
// astuce pour contourner le type const de la methode
  Op_Conv_VEF_base& op = ref_cast_non_const(Op_Conv_VEF_base,*this);
  op.fixer_dt_stab_conv(dt_stab);
  if (vitesse().le_nom()=="rho_u" && equation().probleme().is_dilatable())
    multiplier_par_rho_si_dilatable(fluent,equation().milieu());
  return dt_stab;
}
References diviser_par_rho_si_dilatable(), DMINFLOAT, MorEqn::equation(), Operateur_Conv_base::fixer_dt_stab_conv(), fluent, Cond_lim::frontiere_dis(), la_zcl_vef, la_zone_vef, Objet_U::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Process::mp_min(), multiplier_par_rho_si_dilatable(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), Zone_VEF::premiere_face_std(), ref_cast, ref_cast_non_const, remplir_fluent(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), vitesse(), Zone_VF::volumes_entrelaces(), and Zone_Cl_VEF::volumes_entrelaces_Cl().
Referenced by Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), and calculer_pour_post().
calculer_pour_post()
void Op_Conv_VEF_base::calculer_pour_post (Champ & espace_stockage, const Nom & option, int comp) const override virtual
Reimplemented from Operateur_base.
Definition at line 133 of file Op_Conv_VEF_base.cpp.
{
  if (Motcle(option)=="stabilite")
    {
      DoubleTab& es_valeurs = espace_stockage->valeurs();
      es_valeurs = 1.e30;
      if ((la_zone_vef.non_nul()) && (la_zcl_vef.non_nul()))
        {
          const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
          const Zone_VEF& zone_VEF = la_zone_vef.valeur();
          const DoubleVect& volumes_entrelaces = zone_VEF.volumes_entrelaces();
          const DoubleVect& volumes_entrelaces_Cl = zone_Cl_VEF.volumes_entrelaces_Cl();
          double dt_face;
          remplir_fluent(fluent);
          if (vitesse().le_nom()=="rho_u" && equation().probleme().is_dilatable())
            diviser_par_rho_si_dilatable(fluent,equation().milieu());
// On traite les conditions aux limites
// Si une face porte une condition de Dirichlet on n'en tient pas compte
// dans le calcul de dt_stab
          for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
            {
              const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
              if ((sub_type(Dirichlet,la_cl.valeur()))
                  ||
                  (sub_type(Dirichlet_homogene,la_cl.valeur()))
                 )
                ;
              else
                {
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  int ndeb = le_bord.num_premiere_face();
                  int nfin = ndeb + le_bord.nb_faces();
                  for (int num_face=ndeb; num_face<nfin; num_face++)
                    {
                      dt_face = volumes_entrelaces_Cl(num_face)/(fluent[num_face]+1.e-30);
                      es_valeurs(num_face) = dt_face;
                    }
                }
            }
// On traite les faces internes non standard
          int ndeb = zone_VEF.premiere_face_int();
          int nfin = zone_VEF.premiere_face_std();
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
              dt_face = volumes_entrelaces_Cl(num_face)/(fluent[num_face]+1.e-30);
              es_valeurs(num_face) = dt_face;
            }
// On traite les faces internes standard
          ndeb = nfin;
          nfin = zone_VEF.nb_faces();
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
              dt_face = volumes_entrelaces(num_face)/(fluent[num_face]+1.e-30);
              es_valeurs(num_face) = dt_face;
            }
          assert(mp_min_vect(es_valeurs)==calculer_dt_stab());
          if (vitesse().le_nom()=="rho_u" && equation().probleme().is_dilatable())
            multiplier_par_rho_si_dilatable(fluent,equation().milieu());
        }
    }
  else
    Operateur_Conv_base::calculer_pour_post(espace_stockage,option,comp);
}
References calculer_dt_stab(), Operateur_base::calculer_pour_post(), diviser_par_rho_si_dilatable(), MorEqn::equation(), fluent, Cond_lim::frontiere_dis(), la_zcl_vef, la_zone_vef, Objet_U::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), mp_min_vect(), multiplier_par_rho_si_dilatable(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), O_U_Ptr::non_nul(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), Zone_VEF::premiere_face_std(), ref_cast, remplir_fluent(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ::valeurs(), vitesse(), Zone_VF::volumes_entrelaces(), and Zone_Cl_VEF::volumes_entrelaces_Cl().
get_info()
const Type_info * Op_Conv_VEF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, OpVEF_Centre, OpVEF_Centre4, and OpVEF_Quick.
Definition at line 28 of file Op_Conv_VEF_base.cpp.
get_localisation_pour_post()
Motcle Op_Conv_VEF_base::get_localisation_pour_post (const Nom & option) const override virtual
Reimplemented from Operateur_base.
Definition at line 203 of file Op_Conv_VEF_base.cpp.
{
  Motcle loc;
  if (Motcle(option)=="stabilite")
    loc = "face";
  else
    return Operateur_Conv_base::get_localisation_pour_post(option);
  return loc;
}
References Operateur_base::get_localisation_pour_post().
impr()
int Op_Conv_VEF_base::impr (Sortie & os) const override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 238 of file Op_Conv_VEF_base.cpp.
{
  return Op_VEF_Face::impr(os, *this );
}
References Op_VEF_Face::impr().
info()
const Type_info * Op_Conv_VEF_base::info () static
Definition at line 28 of file Op_Conv_VEF_base.cpp.
phi_u_transportant()
int Op_Conv_VEF_base::phi_u_transportant (const Equation_base & eq) const
definit si l'on convecte psi avec phi*u ou avec u
Definition at line 48 of file Op_Conv_VEF_base.cpp.
{
  if (eq.inconnue().le_nom()=="vitesse")
    return 0;
  return 1;
}
References Equation_base::inconnue(), and O_U_Ptr::le_nom().
Referenced by Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), and Op_Conv_VEF_Face::remplir_fluent().
printOn()
Sortie & Op_Conv_VEF_base::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, OpVEF_Centre, OpVEF_Centre4, and OpVEF_Quick.
Definition at line 33 of file Op_Conv_VEF_base.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Conv_VEF_base::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, OpVEF_Centre, OpVEF_Centre4, and OpVEF_Quick.
Definition at line 41 of file Op_Conv_VEF_base.cpp.
{
  return s ;
}
remplir_fluent()
void Op_Conv_VEF_base::remplir_fluent (DoubleVect & tab_fluent) const virtual
Reimplemented in Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_Muscl_New_VEF_Face, and Op_Conv_VEF_Face.
Definition at line 249 of file Op_Conv_VEF_base.cpp.
{
  // Remplissage du tableau fluent par appel a ajouter
  // C'est cher mais au moins cela corrige (en attendant
  // d'optimiser) le probleme d'un pas de temps de convection
  // calcule avec des vitesses du passe
  DoubleTrav tmp(equation().inconnue().valeurs());
  DoubleTab flux_bords_sauve(flux_bords_);  // On sauve les flux_bords car sinon mis a 0
  ajouter(tmp,tmp);
  flux_bords_=flux_bords_sauve;
  // PL: C'est vraiment lourd, mais comment faire? fluent est dependant
  // du schema et donc on peut coder quelque chose comme fluent=vitesse*surface*porosite
  // dans cette presente methode
}
References Operateur_base::ajouter(), MorEqn::equation(), and Operateur_base::flux_bords_.
Referenced by calculer_dt_local(), calculer_dt_stab(), and calculer_pour_post().
self_cast() [1/2]
const Op_Conv_VEF_base & Op_Conv_VEF_base::self_cast (const Objet_U & r) static
Definition at line 28 of file Op_Conv_VEF_base.cpp.
self_cast() [2/2]
Op_Conv_VEF_base & Op_Conv_VEF_base::self_cast (Objet_U & r) static
Definition at line 28 of file Op_Conv_VEF_base.cpp.
vitesse() [1/2]
Champ_Inc_base & Op_Conv_VEF_base::vitesse () inline
Definition at line 59 of file Op_Conv_VEF_base.h.
  {
    return vitesse_.valeur();
  };
References Ref_Champ_Inc_base::valeur(), and vitesse_.
vitesse() [2/2]
const Champ_Inc_base & Op_Conv_VEF_base::vitesse () const inline
Definition at line 55 of file Op_Conv_VEF_base.h.
  {
    return vitesse_.valeur();
  };
References Ref_Champ_Inc_base::valeur(), and vitesse_.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), calculer_dt_stab(), calculer_pour_post(), Op_Conv_VEF_Face::contribue_au_second_membre(), and Op_Conv_VEF_Face::remplir_fluent().
Member Data Documentation
fluent
DoubleVect Op_Conv_VEF_base::fluent mutable protected
tableau qui sert pour le calcul du pas de temps de stabilite
Definition at line 82 of file Op_Conv_VEF_base.h.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_Centre_old_VEF_Face::associer(), associer(), calculer_dt_local(), calculer_dt_stab(), and calculer_pour_post().
info_obj
const Type_info Op_Conv_VEF_base::info_obj static
Definition at line 50 of file Op_Conv_VEF_base.h.
jeton
int Op_Conv_VEF_base::jeton mutable protected
Definition at line 89 of file Op_Conv_VEF_base.h.
la_zcl_vef
Ref_Zone_Cl_VEF Op_Conv_VEF_base::la_zcl_vef protected
Definition at line 79 of file Op_Conv_VEF_base.h.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Op_Conv_Centre_old_VEF_Face::associer(), associer(), associer_zone_cl_dis(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::calculer_data_pour_dirichlet(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), calculer_dt_local(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), calculer_dt_stab(), Op_Conv_EF_VEF_P1NC_Stab::calculer_flux_bords(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), calculer_pour_post(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Conv_Amont_old_VEF_Face::dimensionner(), Op_Conv_EF_VEF_P1NC::dimensionner(), Op_Conv_VEF_Face::dimensionner(), Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite(), Op_Conv_EF_VEF_P1NC_Stab::mettre_a_jour_pour_periodicite(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Op_Conv_Amont_old_VEF_Face::modifier_pour_Cl(), Op_Conv_EF_VEF_P1NC::modifier_pour_Cl(), Op_Conv_VEF_Face::modifier_pour_Cl(), Op_Conv_EF_VEF_P1NC_Stab::reinit_conv_pour_Cl(), Op_Conv_VEF_Face::remplir_fluent(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), and Op_Conv_EF_VEF_P1NC_Stab::test_implicite().
la_zone_vef
Ref_Zone_VEF Op_Conv_VEF_base::la_zone_vef protected
Definition at line 78 of file Op_Conv_VEF_base.h.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Conv_Muscl_New_VEF_Face::ajouter_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), Op_Conv_Centre_old_VEF_Face::associer(), associer(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::calculer_data_pour_dirichlet(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), calculer_dt_local(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), calculer_dt_stab(), Op_Conv_EF_VEF_P1NC_Stab::calculer_flux_bords(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), calculer_pour_post(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Op_Conv_Muscl_New_VEF_Face::completer(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Conv_kschemas_centre_VEF::convkschemas_centre(), Op_Conv_Amont_old_VEF_Face::dimensionner(), Op_Conv_EF_VEF_P1NC::dimensionner(), Op_Conv_VEF_Face::dimensionner(), Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Op_Conv_Amont_old_VEF_Face::modifier_pour_Cl(), Op_Conv_EF_VEF_P1NC::modifier_pour_Cl(), Op_Conv_VEF_Face::modifier_pour_Cl(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Op_Conv_EF_VEF_P1NC_Stab::reinit_conv_pour_Cl(), Op_Conv_EF_VEF_P1NC_Stab::remplir_fluent(), Op_Conv_Muscl_New_VEF_Face::remplir_fluent(), Op_Conv_VEF_Face::remplir_fluent(), Op_Conv_EF_VEF_P1NC_Stab::test(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), and Op_Conv_EF_VEF_P1NC_Stab::test_implicite().
roue
int Op_Conv_VEF_base::roue mutable protected
Definition at line 90 of file Op_Conv_VEF_base.h.
Referenced by associer().
vitesse_
Ref_Champ_Inc_base Op_Conv_VEF_base::vitesse_ protected
Definition at line 80 of file Op_Conv_VEF_base.h.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), Op_Conv_DI_L2_VEF_Face::associer_vitesse(), associer_vitesse(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Op_Conv_EF_VEF_P1NC_Stab::remplir_fluent(), Op_Conv_Muscl_New_VEF_Face::remplir_fluent(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), and vitesse().
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Conv_VEF_base.h
src/VEF/Operateurs/Op_Conv_VEF_base.cpp