TRUST: Ref_IntVect Class Reference
Ref_IntVect Class Reference
#include <Ref_IntVect.h>
Public Member Functions
~Ref_IntVect ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_IntVect ()
Ref_IntVect (const IntVect &)
Ref_IntVect (const Ref_IntVect &)
const IntVect & valeur () const
IntVect & valeur ()
const IntVect * operator-> () const
IntVect * operator-> ()
const Ref_IntVect & operator= (const IntVect &)
const Ref_IntVect & operator= (const Ref_IntVect &)
operator const IntVect & () const
operator IntVect & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_IntVect & self_cast (Objet_U &)
static const Ref_IntVect & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
IntVect * pointeur_
Detailed Description
Definition at line 29 of file Ref_IntVect.h.
Constructor & Destructor Documentation
Ref_IntVect::~Ref_IntVect ()
Definition at line 26 of file Ref_IntVect.cpp.
Ref_IntVect::Ref_IntVect ()
Definition at line 26 of file Ref_IntVect.cpp.
Ref_IntVect::Ref_IntVect (const IntVect & t)
Definition at line 26 of file Ref_IntVect.cpp.
Ref_IntVect::Ref_IntVect (const Ref_IntVect & t)
Definition at line 26 of file Ref_IntVect.cpp.
Member Function Documentation
Objet_U * Ref_IntVect::cree_instance () [static]
Definition at line 26 of file Ref_IntVect.cpp.
int Ref_IntVect::duplique () const [virtual]
Implements Ref_.
Definition at line 26 of file Ref_IntVect.cpp.
const Type_info * Ref_IntVect::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_IntVect.cpp.
const Type_info & Ref_IntVect::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Ref_IntVect.cpp.
const Type_info * Ref_IntVect::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_IntVect.cpp.
Ref_IntVect::operator const IntVect & () const
Definition at line 26 of file Ref_IntVect.cpp.
Ref_IntVect::operator IntVect & ()
Definition at line 26 of file Ref_IntVect.cpp.
const IntVect * Ref_IntVect::operator-> () const [inline]
Definition at line 29 of file Ref_IntVect.h.
IntVect * Ref_IntVect::operator-> () [inline]
Definition at line 29 of file Ref_IntVect.h.
const Ref_IntVect & Ref_IntVect::operator= (const Ref_IntVect & t)
Definition at line 26 of file Ref_IntVect.cpp.
const Ref_IntVect & Ref_IntVect::operator= (const IntVect & t)
Definition at line 26 of file Ref_IntVect.cpp.
Sortie & Ref_IntVect::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_IntVect.cpp.
Entree & Ref_IntVect::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_IntVect.cpp.
const Ref_IntVect & Ref_IntVect::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 26 of file Ref_IntVect.cpp.
Ref_IntVect & Ref_IntVect::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 26 of file Ref_IntVect.cpp.
void Ref_IntVect::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Ref_IntVect.cpp.
unsigned Ref_IntVect::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Ref_IntVect.cpp.
const IntVect & Ref_IntVect::valeur () const [inline]
Definition at line 29 of file Ref_IntVect.h.
Referenced by DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_faces_bords_ssdom(), DomaineCutter::construire_faces_internes_ssdom(), DomaineCutter::construire_faces_joints_ssdom(), DomaineCutter::construire_faces_raccords_ssdom(), DomaineCutter::construire_sommets_joints_ssdom(), Sonde_Int::initialiser(), Sonde_Int::le_tableau(), and Sonde_Int::postraiter().
IntVect & Ref_IntVect::valeur () [inline]
Definition at line 29 of file Ref_IntVect.h.
Member Data Documentation
const Type_info Ref_IntVect::info_obj [static]
Reimplemented from Ref_.
Definition at line 29 of file Ref_IntVect.h.
IntVect* Ref_IntVect::pointeur_ [private]
Definition at line 29 of file Ref_IntVect.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Ref_IntVect.h
src/Kernel/Framework/Ref_IntVect.cpp