TRUST: Sondes Class Reference
Sondes Class Reference
classe Sondes
Cette classe represente une liste de sondes.
#include <Sondes.h>
Public Member Functions
Sondes ()
~Sondes ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void ouvrir_fichiers ()
Ouvre tous les fichiers associes a chacune des sondes
de la liste.
void fermer_fichiers ()
Ferme tous les fichiers des sondes de la liste.
void completer ()
void init_bords ()
void associer_post (const Postraitement &)
Associe un postraitement a la liste des sondes.
void postraiter ()
Effectue le postraitement sur chacune des sondes de
la liste.
void mettre_a_jour (double temps, double tinit)
Effectue une mise a jour en temps de chacune
des sondes de la liste.
void lire_fichier (const Nom &nom_fichier)
Ref_Champ_base get_from_cache (Ref_Champ_Generique_base &mon_champ, const Nom &nom_champ_lu_)
void clear_cache ()
void set_noms_champs_postraitables ()
const Motcles & get_noms_champs_postraitables () const
Public Member Functions inherited from List_Sonde
List_Sonde ()
~List_Sonde ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
List_Sonde (const Sonde &t)
List_Sonde (const List_Sonde &t)
Sonde & operator[] (int)
const Sonde & operator[] (int) const
Sonde & operator[] (const Nom &)
const Sonde & operator[] (const Nom &) const
Sonde & operator() (int i)
const Sonde & operator() (int i) const
Sonde & operator() (const Nom &n)
const Sonde & operator() (const Nom &n) const
Sonde & valeur ()
const Sonde & valeur () const
List_Sonde & operator= (const Sonde &t)
Sonde * operator-> ()
List_Sonde & operator= (const List_Sonde &)
List_Sonde & add (const List_Sonde &)
Sonde & add (const Sonde &)
List_Sonde & inserer (const List_Sonde &)
Sonde & inserer (const Sonde &)
void supprimer ()
List_Sonde & operator+= (const List_Sonde &)
List_Sonde & operator+= (const Sonde &)
Sonde & add_if_not (const Sonde &)
Sonde & add_if_not (const char *const)
List_Sonde & search (const Sonde &) const
List_Sonde & search (const char *const) const
List_Sonde & suivant ()
const List_Sonde & suivant () const
const List_Sonde & dernier () const
List_Sonde & dernier ()
List_Sonde & operator-= (const Sonde &)
int est_egal_a (const Objet_U &) const override
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
int contient (const Sonde &) const
int contient (const char *const) const
int rang (const Sonde &) const
void suppr (const Sonde &)
Public Member Functions inherited from liste
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
liste ()
Constructeur par defaut
Construit une liste vide.
liste (const liste &)
Constructeur
Ajoute les elements contenus dans la liste passe en parametre.
liste (const Objet_U &)
Constructeur
Construit une liste singleton.
~liste () override
Destructeur de liste.
int size () const
Renvoie la taille de la liste
Une liste vide est de taille nulle.
int rang (const char *const) const
Renvoie le rang d'une chaine de caracteres contenue dans la liste
Recherche un Objet_U de Nom ch.
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
void suppr (const char *const)
Supprime l'Objet de Nom ch contenu dans la liste.
int est_vide () const
Teste si la liste est vide.
int est_dernier () const
Teste si la liste comporte des elements suivants ou non.
Retourne 1 si la liste est vide.
void vide ()
Vide la liste.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Sondes & self_cast (Objet_U &)
static const Sondes & self_cast (const Objet_U &)
Static Public Member Functions inherited from List_Sonde
static Objet_U * cree_instance ()
static const Type_info * info ()
static List_Sonde & self_cast (Objet_U &)
static const List_Sonde & self_cast (const Objet_U &)
Static Public Member Functions inherited from liste
static Objet_U * cree_instance ()
static const Type_info * info ()
static liste & self_cast (Objet_U &)
static const liste & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from List_Sonde
static const Type_info info_obj
Static Public Attributes inherited from liste
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
Lit une liste de sondes a partir d'un flot d'entree
Format:
{
[LIRE UNE SONDE AUTANT DE FOIS QUE NECESSAIRE]
}.
Protected Member Functions inherited from List_Sonde
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
int est_egal_a (const List_Sonde &) const
Protected Member Functions inherited from liste
Sortie & printOn (Sortie &x) const override
Ecriture d'une liste sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une liste sur un flot d'entree.
Objet_U & operator() (int)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Objet_U & operator() (int) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Objet_U & operator() (const Nom &)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Objet_U & operator() (const Nom &) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Objet_U & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Objet_U & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
liste & operator+= (const Objet_U &)
Ajoute un Objet_U a la fin de la liste.
liste & operator+= (const liste &)
Ajoute une list d'Objet_U a la fin de la liste.
liste & operator-= (const Objet_U &)
Supprime un Objet_U de la liste
Affiche un message d'erreur si l'objet n'est pas trouve.
const liste & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
liste & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
Objet_U * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
const Objet_U * operator-> () const
Retourne un pointeur sur l'Objet_U premier element de la liste.
Objet_U & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Objet_U & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Objet_U & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Objet_U & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Objet_U & add (const Objet_U &)
Ajout d'un Objet_U a la liste.
Objet_U & add_deplace (DerObjU &)
Ajout d'un Objet_U a la liste
to_add est libere en sortie.
Objet_U & inserer (const Objet_U &)
Insertion d'un Objet_U dans la liste.
liste & add (const liste &)
Ajout d'une liste a la liste.
liste & inserer (const liste &)
Insertion d'une liste
NON CODE - SORT SYSTEMATIQUEMENT EN ERREUR.
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Objet_U & add_if_not (const Objet_U &)
Ajout d'un Objet_U a la liste ssi il n'existe pas deja.
liste & search (const Objet_U &) const
Recherche d'un Objet_U dans la liste.
liste & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
int contient (const Objet_U &) const
Verifie si un Objet_U appartient ou non a la liste.
int rang (const Objet_U &) const
Renvoie le rang d'un Objet_U dans la liste.
void suppr (const Objet_U &)
Supprime un Objet_U contenu dans la liste.
liste & operator= (const liste &)
Operateur d'affectation de liste.
const liste & dernier () const
Renvoie le dernier element de la liste.
liste & dernier ()
Renvoie le dernier element de la liste.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
List_Ref_Champ_base sourceList
List_Champ espaceStockageList
Noms sourceNoms
Ref_Postraitement mon_post
Motcles noms_champs_postraitables_
Additional Inherited Members
Protected Attributes inherited from liste
DerObjU data
liste * suivant_
Detailed Description
classe Sondes
Cette classe represente une liste de sondes.
Definition at line 40 of file Sondes.h.
Constructor & Destructor Documentation
Sondes()
Sondes::Sondes ()
Definition at line 21 of file Sondes.cpp.
~Sondes()
Sondes::~Sondes ()
Definition at line 21 of file Sondes.cpp.
Member Function Documentation
associer_post()
void Sondes::associer_post (const Postraitement & post)
Associe un postraitement a la liste des sondes.
Definition at line 269 of file Sondes.cpp.
{
  mon_post = post;
}
References mon_post.
Referenced by Postraitement::lire_motcle_non_standard().
clear_cache()
void Sondes::clear_cache ()
Definition at line 196 of file Sondes.cpp.
{
  sourceList.vide();
  espaceStockageList.vide();
  sourceNoms.reset();
}
References espaceStockageList, vect_impl::reset(), sourceList, sourceNoms, and liste::vide().
Referenced by mettre_a_jour(), and postraiter().
completer()
void Sondes::completer (void)
Definition at line 159 of file Sondes.cpp.
{
  set_noms_champs_postraitables();
  LIST_CURSEUR(Sonde) curseur=*this;
  while(curseur)
    {
      curseur->completer();
      ++curseur;
    }
}
References LIST_CURSEUR, and set_noms_champs_postraitables().
Referenced by Postraitement::readOn().
cree_instance()
Objet_U * Sondes::cree_instance () static
Definition at line 21 of file Sondes.cpp.
duplique()
int Sondes::duplique () const override virtual
Reimplemented from List_Sonde.
Definition at line 21 of file Sondes.cpp.
fermer_fichiers()
void Sondes::fermer_fichiers () inline
Ferme tous les fichiers des sondes de la liste.
Definition at line 118 of file Sondes.h.
{
  LIST_CURSEUR(Sonde) curseur=*this;
  while(curseur)
    {
      curseur->fermer_fichier();
      ++curseur;
    }
}
References LIST_CURSEUR.
get_from_cache()
Ref_Champ_base Sondes::get_from_cache (Ref_Champ_Generique_base & mon_champ, const Nom & nom_champ_lu_)
Definition at line 203 of file Sondes.cpp.
{
  mon_champ->fixer_identifiant_appel(nom_champ_lu_);
  int num = sourceNoms.rang(nom_champ_lu_);
  if (num < 0)
    {
      Champ espace_stockage;
      const Champ_base& ma_source = ref_cast(Champ_base, mon_champ->get_champ(espace_stockage));
      sourceList.add(ma_source);
      espaceStockageList.add(espace_stockage);
      sourceNoms.add(nom_champ_lu_);
// Voir Champ_Generique_base pour la definition de l'espace stockage
      return espace_stockage.non_nul() ? espaceStockageList.dernier().valeur() : ma_source;
    }
  else if (espaceStockageList(num).non_nul())
    return espaceStockageList(num).valeur();
  else
    return sourceList(num);
}
References List_Champ::add(), List_Ref_Champ_base::add(), Vect_Nom::add(), List_Champ::dernier(), espaceStockageList, Champ_Generique_base::fixer_identifiant_appel(), Champ_Generique_base::get_champ(), O_U_Ptr::non_nul(), Noms::rang(), ref_cast, sourceList, sourceNoms, and List_Champ::valeur().
Referenced by Sonde::mettre_a_jour(), and Sonde::postraiter().
get_info()
const Type_info * Sondes::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from List_Sonde.
Definition at line 21 of file Sondes.cpp.
get_noms_champs_postraitables()
const Motcles & Sondes::get_noms_champs_postraitables () const inline
Definition at line 58 of file Sondes.h.
{ return noms_champs_postraitables_; }
References noms_champs_postraitables_.
Referenced by Sonde::completer(), and Sonde::readOn().
info()
const Type_info * Sondes::info () static
Definition at line 21 of file Sondes.cpp.
init_bords()
void Sondes::init_bords () inline
Definition at line 68 of file Sondes.h.
{
  LIST_CURSEUR(Sonde) curseur=*this;
  while(curseur)
    {
      curseur->init_bords();
      ++curseur;
    }
}
References LIST_CURSEUR.
Referenced by Postraitement::completer().
lire_fichier()
void Sondes::lire_fichier (const Nom & nom_fichier)
Definition at line 103 of file Sondes.cpp.
{
  set_noms_champs_postraitables();
  LecFicDiffuse_JDD f(nom_fichier);
  Motcle motlu;
  if (!f.good())
    {
      Cerr << "Cannot open the file " << nom_fichier << finl;
      Process::exit();
    }
  f >> motlu;
  while (!f.eof())
    {
      Sonde une_sonde(motlu);
      une_sonde.associer_post(mon_post.valeur());
      f >> une_sonde;
      add(une_sonde);
      f >> motlu;
    }
  f.close();
}
References List_Sonde::add(), Sonde::associer_post(), Cerr, Entree_Fichier_base::close(), Lec_Diffuse_base::eof(), Process::exit(), finl, Lec_Diffuse_base::good(), mon_post, nom_fichier(), set_noms_champs_postraitables(), and Ref_Postraitement::valeur().
Referenced by Postraitement::lire_motcle_non_standard(), and readOn().
mettre_a_jour()
void Sondes::mettre_a_jour (double temps, double tinit)
Effectue une mise a jour en temps de chacune
des sondes de la liste.
Definition at line 243 of file Sondes.cpp.
{
  LIST_CURSEUR(Sonde) curseur=*this;
  while(curseur)
    {
      curseur->mettre_a_jour(temps,tinit);
      ++curseur;
    }
  clear_cache();
}
References clear_cache(), and LIST_CURSEUR.
Referenced by Postraitement::traiter_sondes().
ouvrir_fichiers()
void Sondes::ouvrir_fichiers () inline
Ouvre tous les fichiers associes a chacune des sondes
de la liste.
Definition at line 93 of file Sondes.h.
{
  LIST_CURSEUR(Sonde) curseur=*this;
  while(curseur)
    {
      curseur->ouvrir_fichier();
      ++curseur;
    }
}
References LIST_CURSEUR.
postraiter()
void Sondes::postraiter ()
Effectue le postraitement sur chacune des sondes de
la liste.
Definition at line 185 of file Sondes.cpp.
{
  LIST_CURSEUR(Sonde) curseur=*this;
  while(curseur)
    {
      curseur->postraiter();
      ++curseur;
    }
  clear_cache();
}
References clear_cache(), and LIST_CURSEUR.
Referenced by Postraitement::postraiter_sondes().
printOn()
Sortie & Sondes::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from List_Sonde.
Definition at line 141 of file Sondes.cpp.
{
  return s ;
}
readOn()
Entree & Sondes::readOn (Entree & s) override protected virtual
Lit une liste de sondes a partir d'un flot d'entree
Format:
{
[LIRE UNE SONDE AUTANT DE FOIS QUE NECESSAIRE]
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from List_Sonde.
Definition at line 42 of file Sondes.cpp.
{
  assert(mon_post.non_nul());
  Motcle motlu;
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  s >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "Error while reading the probes in the postprocessing" << finl;
      Cerr << "We expected { to start to read the probes" << finl;
      exit();
    }
  s >> motlu;
  bool depuisFichier = false;
  Nom nom_fichier;
  if (motlu == "FICHIER")
    {
      Cerr<<"Warning: Sondes { " << motlu << " .... } no more allowed, use Sondes_fichier { " << motlu << " .... }" <<finl;
      exit();
      depuisFichier = true;
      s >> nom_fichier;
    }
  else if (motlu == accolade_fermee)
    {
      Cerr << "Error while reading the probes in the postprocessing" << finl;
      Cerr << "You have not defined any probe" << finl;
      exit();
    }
  set_noms_champs_postraitables();
  if (depuisFichier)
    {
      lire_fichier(nom_fichier);
      s >> motlu;
      if (motlu != accolade_fermee)
        {
          Cerr << "Error while reading the probes in the postprocessing" << finl;
          Cerr << "We expected } to end to read the probes" << finl;
          exit();
        }
    }
  else
    {
      while (motlu != accolade_fermee)
        {
          Sonde une_sonde(motlu);
          une_sonde.associer_post(mon_post.valeur());
          s >> une_sonde;
          add(une_sonde);
          s >> motlu;
        }
    }
  Cerr << "End of reading probes " << finl;
  return s;
}
References List_Sonde::add(), Sonde::associer_post(), Cerr, Process::exit(), finl, lire_fichier(), mon_post, nom_fichier(), O_U_Ptr::non_nul(), set_noms_champs_postraitables(), and Ref_Postraitement::valeur().
self_cast() [1/2]
const Sondes & Sondes::self_cast (const Objet_U & r) static
Definition at line 21 of file Sondes.cpp.
self_cast() [2/2]
Sondes & Sondes::self_cast (Objet_U & r) static
Definition at line 21 of file Sondes.cpp.
set_noms_champs_postraitables()
void Sondes::set_noms_champs_postraitables ()
Definition at line 146 of file Sondes.cpp.
{
// Reconstruit noms_champs_postraitables_
  if (mon_post.non_nul())
    {
      Noms noms;
      mon_post->probleme().get_noms_champs_postraitables(noms);
      noms_champs_postraitables_.dimensionner_force(noms.size());
      for (int i = 0; i < noms.size(); i++)
        noms_champs_postraitables_[i] = noms[i];
    }
}
References vect_impl::dimensionner_force(), Probleme_base::get_noms_champs_postraitables(), mon_post, noms_champs_postraitables_, O_U_Ptr::non_nul(), Postraitement::probleme(), and vect_impl::size().
Referenced by completer(), lire_fichier(), and readOn().
taille_memoire()
unsigned Sondes::taille_memoire () const override virtual
Reimplemented from List_Sonde.
Definition at line 21 of file Sondes.cpp.
Member Data Documentation
espaceStockageList
List_Champ Sondes::espaceStockageList private
Definition at line 62 of file Sondes.h.
Referenced by clear_cache(), and get_from_cache().
info_obj
const Type_info Sondes::info_obj static
Definition at line 43 of file Sondes.h.
mon_post
Ref_Postraitement Sondes::mon_post private
Definition at line 64 of file Sondes.h.
Referenced by associer_post(), lire_fichier(), readOn(), and set_noms_champs_postraitables().
noms_champs_postraitables_
Motcles Sondes::noms_champs_postraitables_ private
Definition at line 65 of file Sondes.h.
Referenced by get_noms_champs_postraitables(), and set_noms_champs_postraitables().
sourceList
List_Ref_Champ_base Sondes::sourceList private
Definition at line 61 of file Sondes.h.
Referenced by clear_cache(), and get_from_cache().
sourceNoms
Noms Sondes::sourceNoms private
Definition at line 63 of file Sondes.h.
Referenced by clear_cache(), and get_from_cache().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Sondes.h
src/Kernel/Framework/Sondes.cpp