TRUST: Conduction Class Reference
Conduction Class Reference
Classe Conduction
Cette classe represente l'equation d'evolution
de la temperature dans un solide de conductivite k et de masse volumique rho et chaleur specifique Cp
(rho.Cp) . dT/dt - div (k grad T) = (rho.Cp) . f
Les termes rho et Cp peuvent etre non uniformes car cette classe
ne fait pas le raccourci de calculer la diffusivite k/(rho*Cp).
#include <Conduction.h>
Public Member Functions
~Conduction ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Conduction ()
void set_param (Param &)
int lire_motcle_non_standard (const Motcle &, Entree &)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void associer_solide (const Solide &)
Associe le milieu solide a l'equation.
void associer_milieu_base (const Milieu_base &)
Associe un milieu physique a l'equation,
le milieu est en fait caste en Solide.
const Milieu_base & milieu () const
Renvoie le milieu physique associe a l'equation.
Ici Solide upcaste en Milieu_base.
(version const)
Milieu_base & milieu ()
Renvoie le milieu physique associe a l'equation.
Ici Solide upcaste en Milieu_base.
const Solide & solide () const
Renvoie le milieu solide associe a l'equation.
(version const)
Solide & solide ()
Renvoie le milieu solide associe a l'equation.
int nombre_d_operateurs () const
Renvoie le nombre d'operateurs de l'equation
pour l'equation de conduction standart renvoie toujours 1.
const Operateur & operateur (int) const
Renvoie l'operateur d'index specifie de l'equation.
Renvoie terme_diffusif si i=0
exit si i>0
(version const)
Operateur & operateur (int)
Renvoie l'operateur d'index specifie de l'equation.
Renvoie terme_diffusif si i=0
exit si i>0.
const Champ_Inc & inconnue () const
Renvoie le champ inconnue de l'equation,
i.e. la temperature.
(version const)
Champ_Inc & inconnue ()
Renvoie le champ inconnue de l'equation,
i.e. la temperature.
void discretiser ()
Discretise l'equation.
int impr (Sortie &os) const
Imprime le terme diffusif sur un flot de sortie.
virtual const Motcle & domaine_application () const
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
virtual void mettre_a_jour (double temps)
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
virtual const Champ_Don & diffusivite_pour_transport ()
virtual const Champ_base & diffusivite_pour_pas_de_temps ()
virtual void creer_champ (const Motcle &motlu)
virtual const Champ_base & get_champ (const Motcle &nom) const
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Conduction & self_cast (Objet_U &)
static const Conduction & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'equation sur un flot de
sortie.
virtual Entree & readOn (Entree &)
cf Equation_base::readOn(Entree&)
Protected Attributes
Traitement_particulier_Solide le_traitement_particulier
Private Attributes
Ref_Solide le_solide
Champ_Inc la_temperature
Operateur_Diff terme_diffusif
Detailed Description
Classe Conduction
Cette classe represente l'equation d'evolution
de la temperature dans un solide de conductivite k et de masse volumique rho et chaleur specifique Cp
(rho.Cp) . dT/dt - div (k grad T) = (rho.Cp) . f
Les termes rho et Cp peuvent etre non uniformes car cette classe
ne fait pas le raccourci de calculer la diffusivite k/(rho*Cp).
Definition at line 49 of file Conduction.h.
Constructor & Destructor Documentation
Conduction::~Conduction ()
Definition at line 31 of file Conduction.cpp.
Conduction::Conduction ()
Definition at line 33 of file Conduction.cpp.
References Champs_compris::ajoute_nom_compris(), and Equation_base::champs_compris_.
{
// champs_compris_.ajoute_nom_compris("temperature_paroi");
  champs_compris_.ajoute_nom_compris("temperature_residu");
}
Member Function Documentation
void Conduction::associer_milieu_base (const Milieu_base & le_milieu) [virtual]
Associe un milieu physique a l'equation,
le milieu est en fait caste en Solide.
Implements Equation_base.
Definition at line 178 of file Conduction.cpp.
References associer_solide(), and ref_cast.
{
  associer_solide(ref_cast(Solide,le_milieu));
}
void Conduction::associer_solide (const Solide & un_solide)
Associe le milieu solide a l'equation.
Definition at line 197 of file Conduction.cpp.
References le_solide.
Referenced by associer_milieu_base().
{
  le_solide = un_solide;
}
Objet_U * Conduction::cree_instance () [static]
Definition at line 31 of file Conduction.cpp.
void Conduction::creer_champ (const Motcle & motlu) [virtual]
Reimplemented from Equation_base.
Definition at line 379 of file Conduction.cpp.
{
  Equation_base::creer_champ(motlu);
  Motcle nom_mot(motlu),temp_mot(nom_mot);
  /*  if (motlu == "temperature_paroi")
      {
        if (!temperature_paroi.non_nul())
          {
            const Discret_Thermique& dis=ref_cast(Discret_Thermique, discretisation());
            dis.t_paroi(zone_dis(),zone_Cl_dis(),*this,temperature_paroi);
            champs_compris_.ajoute_champ(temperature_paroi);
          }
      } */
}
const Champ_base & Conduction::diffusivite_pour_pas_de_temps () [virtual]
Definition at line 157 of file Conduction.cpp.
References Operateur_Diff::diffusivite(), and terme_diffusif.
{
  return terme_diffusif.diffusivite();
}
const Champ_Don & Conduction::diffusivite_pour_transport () [virtual]
Definition at line 152 of file Conduction.cpp.
References Milieu_base::conductivite(), and milieu().
Referenced by lire_motcle_non_standard().
{
  return milieu().conductivite();
}
void Conduction::discretiser () [virtual]
Discretise l'equation.
Reimplemented from Equation_base.
Definition at line 301 of file Conduction.cpp.
References Champs_compris::ajoute_champ(), Cerr, Equation_base::champs_compris_, Equation_base::discretisation(), finl, la_temperature, ref_cast, Equation_base::schema_temps(), Discret_Thermique::temperature(), and Equation_base::zone_dis().
{
  const Discret_Thermique& dis=ref_cast(Discret_Thermique, discretisation());
  Cerr << "Conduction equation discretization" << finl;
  dis.temperature(schema_temps(), zone_dis(), la_temperature);
  champs_compris_.ajoute_champ(la_temperature);
  Equation_base::discretiser();
}
const Motcle & Conduction::domaine_application () const [virtual]
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
Returns:
Motcle&
Signification: le nom du domaine d'application de l'equation
Contraintes: toujours egal a "Thermique"
Reimplemented from Equation_base.
Definition at line 497 of file Conduction.cpp.
{
  static Motcle domaine = "Thermique";
  return domaine;
}
int Conduction::duplique () const [virtual]
Implements Equation_base.
Definition at line 31 of file Conduction.cpp.
const Champ_base & Conduction::get_champ (const Motcle & nom) const [virtual]
Reimplemented from Equation_base.
Definition at line 394 of file Conduction.cpp.
References le_traitement_particulier, O_U_Ptr::non_nul(), and REF.
{
  /*
    if (nom=="rho_cp")
      {
        const Champ_base& rho_cp=solide().get_rho_cp();
        return rho_cp;
      }
  */
  try
    {
      return Equation_base::get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  if (le_traitement_particulier.non_nul())
    try
      {
        return le_traitement_particulier->get_champ(nom);
      }
    catch (Champs_compris_erreur)
      {
      }
  throw Champs_compris_erreur();
  REF(Champ_base) ref_champ;
  return ref_champ;
}
const Type_info * Conduction::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Equation_base.
Definition at line 31 of file Conduction.cpp.
void Conduction::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const [virtual]
Reimplemented from Equation_base.
Definition at line 426 of file Conduction.cpp.
References Vect_Nom::add(), Cerr, Equation_base::champs_compris_, DESCRIPTION, finl, le_traitement_particulier, Champs_compris::liste_noms_compris(), and O_U_Ptr::non_nul().
{
  Equation_base::get_noms_champs_postraitables(nom,opt);
  if (opt==DESCRIPTION)
    Cerr<<"Conduction : "<<champs_compris_.liste_noms_compris()<<finl;
  else
    nom.add(champs_compris_.liste_noms_compris());
  if (le_traitement_particulier.non_nul())
    le_traitement_particulier->get_noms_champs_postraitables(nom,opt);
}
int Conduction::impr (Sortie & os) const [virtual]
Imprime le terme diffusif sur un flot de sortie.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Equation_base.
Definition at line 476 of file Conduction.cpp.
{
  return Equation_base::impr(os);
}
const Champ_Inc & Conduction::inconnue () const [inline, virtual]
Renvoie le champ inconnue de l'equation,
i.e. la temperature.
(version const)
Returns:
Champ_Inc&
Signification: le champ inconnue de l'equation: la temperature
Contraintes: reference constante
Implements Equation_base.
Definition at line 136 of file Conduction.h.
References la_temperature.
Referenced by Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), and Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne().
{
  return la_temperature;
}
Champ_Inc & Conduction::inconnue () [inline, virtual]
Renvoie le champ inconnue de l'equation,
i.e. la temperature.
Returns:
Champ_Inc&
Signification: le champ inconnue de l'equation: la temperature
Contraintes:
Implements Equation_base.
Definition at line 114 of file Conduction.h.
References la_temperature.
{
  return la_temperature;
}
const Type_info * Conduction::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Equation_base.
Definition at line 31 of file Conduction.cpp.
int Conduction::lire_motcle_non_standard (const Motcle & motlu, Entree & is) [virtual]
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns:
int
Reimplemented from Equation_base.
Definition at line 94 of file Conduction.cpp.
References Operateur_Diff::associer_diffusivite(), Operateur_Diff::associer_diffusivite_pour_pas_de_temps(), Traitement_particulier_Solide::associer_eqn(), Cerr, diffusivite_pour_transport(), Equation_base::discretisation(), Process::exit(), finl, le_traitement_particulier, Traitement_particulier_Solide::lire(), milieu(), Traitement_particulier_Solide::preparer_calcul_particulier(), Objet_U::que_suis_je(), Equation_base::solveur_masse, terme_diffusif, and Deriv_::typer().
{
  Motcle motlu;
  if (mot=="diffusion")
    {
      Cerr << "Reading and typing of the diffusion operator : " << finl;
      terme_diffusif.associer_diffusivite(diffusivite_pour_transport());
      is >> terme_diffusif;
// le champ pour le dt_stab est le meme que celui de l'operateur. On prend toujours la diffusivite()
// comme dans le cas de Conduction
      terme_diffusif.associer_diffusivite_pour_pas_de_temps(milieu().diffusivite());
      solveur_masse->set_name_of_coefficient_temporel("rho_cp_comme_T");
      return 1;
    }
  else if (mot=="Traitement_particulier")
    {
      Cerr << "Reading and typing of the Traitement_particulier object : " << finl;
      Nom type="Traitement_particulier_";
      Motcle motbidon;
      is >> motbidon;
      if (motbidon == "{")
        {
          Motcle le_cas;
          is >> le_cas;
          if (le_cas == "}")
            le_cas ="";
          else
            {
              type+= le_cas;
              type+= "_";
            }
          Nom discr=discretisation().que_suis_je();
          if (discr == "VEFPreP1B")
            discr = "VEF";
          type+=discr;
          Cerr << type << finl;
          le_traitement_particulier.typer(type);
          le_traitement_particulier.associer_eqn(*this);
          le_traitement_particulier.lire(is);
          le_traitement_particulier.preparer_calcul_particulier();
          return 1;
        }
      else
        {
          Cerr << "Error while reading Traitement_particulier" << finl;
          Cerr << "A { is expected." << finl;
          exit();
          return -1;
        }
    }
  else
    return Equation_base::lire_motcle_non_standard(mot,is);
  return 1;
}
void Conduction::mettre_a_jour (double temps) [virtual]
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
Reimplemented from Equation_base.
Definition at line 503 of file Conduction.cpp.
References le_traitement_particulier, O_U_Ptr::non_nul(), and Traitement_particulier_Solide::post_traitement_particulier().
{
  Equation_base::mettre_a_jour(temps);
  if (le_traitement_particulier.non_nul())
    le_traitement_particulier.post_traitement_particulier();
}
const Milieu_base & Conduction::milieu () const [virtual]
Renvoie le milieu physique associe a l'equation.
Ici Solide upcaste en Milieu_base.
(version const)
Returns:
Milieu_base&
Signification: le milieu physique associe a l'equation
(Solide upcaste en Milieu_base)
Contraintes: reference constante
Implements Equation_base.
Definition at line 328 of file Conduction.cpp.
References solide().
Referenced by diffusivite_pour_transport(), and lire_motcle_non_standard().
{
  return solide();
}
Milieu_base & Conduction::milieu () [virtual]
Renvoie le milieu physique associe a l'equation.
Ici Solide upcaste en Milieu_base.
Returns:
Milieu_base&
Signification: le milieu physique associe a l'equation
(Solide upcaste en Milieu_base)
Contraintes:
Implements Equation_base.
Definition at line 349 of file Conduction.cpp.
References solide().
{
  return solide();
}
int Conduction::nombre_d_operateurs () const [virtual]
Renvoie le nombre d'operateurs de l'equation
pour l'equation de conduction standart renvoie toujours 1.
Returns:
int
Signification: le nombre d'operateurs de l'equation
Contraintes: toujours egal a 1
Implements Equation_base.
Definition at line 217 of file Conduction.cpp.
{
  return 1;
}
const Operateur & Conduction::operateur (int i) const [virtual]
Renvoie l'operateur d'index specifie de l'equation.
Renvoie terme_diffusif si i=0
exit si i>0
(version const)
Returns:
Operateur&
Signification: l'operateur d'index specifie
(uniquement terme_diffusif)
Contraintes: reference constante
Implements Equation_base.
Definition at line 241 of file Conduction.cpp.
References Cerr, Process::exit(), finl, and terme_diffusif.
{
  if (i == 0)
    return terme_diffusif;
  else
    {
      Cerr << "Conduction::operateur("<<i<<") !! " << finl;
      Cerr << "Equation Conduction has only one operator." << finl;
      exit();
    }
// Pour les compilos!!
  return terme_diffusif;
}
Operateur & Conduction::operateur (int i) [virtual]
Renvoie l'operateur d'index specifie de l'equation.
Renvoie terme_diffusif si i=0
exit si i>0.
Returns:
Operateur&
Signification: l'operateur d'index specifie
(uniquement terme_diffusif)
Contraintes:
Implements Equation_base.
Definition at line 273 of file Conduction.cpp.
References Cerr, Process::exit(), finl, and terme_diffusif.
{
  if (i == 0)
    return terme_diffusif;
  else
    {
      Cerr << "Conduction::operateur("<<i<<") !! " << finl;
      Cerr << "Equation Conduction has only one operator." << finl;
      exit();
    }
// Pour les compilos!!
  return terme_diffusif;
}
Sortie & Conduction::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'equation sur un flot de
sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Equation_base.
Definition at line 53 of file Conduction.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Conduction::readOn (Entree & is) [protected, virtual]
cf Equation_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Equation_base.
Definition at line 72 of file Conduction.cpp.
References Operateur::set_description(), Operateur::set_fichier(), and terme_diffusif.
{
  Equation_base::readOn(is);
// Nom unite;
// if (dimension+bidim_axi==2) unite="[W/m]";
// else unite="[W]";
  terme_diffusif.set_fichier("Diffusion_chaleur");
// terme_diffusif.set_description((Nom)"Conduction heat transfer rate=Integral(lambda*grad(T)*ndS) "+unite);
  terme_diffusif.set_description((Nom)"Conduction heat transfer rate=Integral(lambda*grad(T)*ndS) [W] if SI units used");
  return is;
}
Conduction & Conduction::self_cast (Objet_U & r) [static]
Reimplemented from Equation_base.
Definition at line 31 of file Conduction.cpp.
const Conduction & Conduction::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Equation_base.
Definition at line 31 of file Conduction.cpp.
void Conduction::set_param (Param & param) [virtual]
Reimplemented from Equation_base.
Definition at line 85 of file Conduction.cpp.
References Param::ajouter_condition(), and Param::ajouter_non_std().
{
  Equation_base::set_param(param);
  param.ajouter_non_std("diffusion",(this));
  param.ajouter_condition("is_read_diffusion","The diffusion operator must be read, select negligeable type if you want to neglect it.");
  param.ajouter_non_std("Traitement_particulier",(this));
}
const Solide & Conduction::solide () const
Renvoie le milieu solide associe a l'equation.
(version const)
Returns:
Solide&
Signification: le milieu solide associe a l'equation
Contraintes: reference constante
Definition at line 369 of file Conduction.cpp.
References Cerr, Process::exit(), finl, Probleme_base::le_nom(), le_solide, O_U_Ptr::non_nul(), Equation_base::probleme(), and Ref_Solide::valeur().
Referenced by milieu().
{
  if(!le_solide.non_nul())
    {
      Cerr << "You forgot to associate the solid to the problem named " << probleme().le_nom() << finl;
      Process::exit();
    }
  return le_solide.valeur();
}
Solide & Conduction::solide ()
Renvoie le milieu solide associe a l'equation.
Returns:
Solide&
Signification: le milieu solide associe a l'equation
Contraintes:
Definition at line 452 of file Conduction.cpp.
References Cerr, Process::exit(), finl, le_solide, O_U_Ptr::non_nul(), and Ref_Solide::valeur().
{
  if(!le_solide.non_nul())
    {
      Cerr << "A solide medium has not been associated to a Conduction equation"<<finl;
      exit();
    }
  return le_solide.valeur();
}
unsigned Conduction::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 31 of file Conduction.cpp.
Member Data Documentation
const Type_info Conduction::info_obj [static]
Reimplemented from Equation_base.
Definition at line 52 of file Conduction.h.
Champ_Inc Conduction::la_temperature [private]
Definition at line 88 of file Conduction.h.
Referenced by discretiser(), and inconnue().
Ref_Solide Conduction::le_solide [private]
Definition at line 87 of file Conduction.h.
Referenced by associer_solide(), and solide().
Traitement_particulier_Solide Conduction::le_traitement_particulier [protected]
Definition at line 93 of file Conduction.h.
Referenced by get_champ(), get_noms_champs_postraitables(), lire_motcle_non_standard(), and mettre_a_jour().
Operateur_Diff Conduction::terme_diffusif [private]
Definition at line 89 of file Conduction.h.
Referenced by diffusivite_pour_pas_de_temps(), lire_motcle_non_standard(), operateur(), and readOn().
The documentation for this class was generated from the following files:
src/ThSol/Conduction.h
src/ThSol/Conduction.cpp