TRUST: Darcy_QC_VEF_P1NC Class Reference
Darcy_QC_VEF_P1NC Class Reference
#include <Source_QC_VEF_P1NC.h>
Public Member Functions
Darcy_QC_VEF_P1NC ()
~Darcy_QC_VEF_P1NC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & ajouter_mere (DoubleTab &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Darcy_QC_VEF_P1NC & self_cast (Objet_U &)
static const Darcy_QC_VEF_P1NC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Detailed Description
Definition at line 122 of file Source_QC_VEF_P1NC.h.
Constructor & Destructor Documentation
Darcy_QC_VEF_P1NC::Darcy_QC_VEF_P1NC ()
Definition at line 81 of file Source_QC_VEF_P1NC.cpp.
Darcy_QC_VEF_P1NC::~Darcy_QC_VEF_P1NC ()
Definition at line 81 of file Source_QC_VEF_P1NC.cpp.
Member Function Documentation
DoubleTab & Darcy_QC_VEF_P1NC::ajouter (DoubleTab & resu) const [virtual]
Reimplemented from Terme_Source_VEF_base.
Definition at line 85 of file Source_QC_VEF_P1NC.cpp.
References Source_Fluide_Dilatable_Face< Darcy_QC_VEF_P1NC >::ajouter_impl().
Referenced by ajouter_mere().
{ return ajouter_impl(resu); }
DoubleTab & Darcy_QC_VEF_P1NC::ajouter_mere (DoubleTab & resu) const
Definition at line 84 of file Source_QC_VEF_P1NC.cpp.
References ajouter().
{ return Source_Darcy_VEF_Face::ajouter(resu); }
void Darcy_QC_VEF_P1NC::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const [virtual]
contribution a la matrice implicite des termes sources
par defaut pas de contribution
Reimplemented from Source_base.
Definition at line 86 of file Source_QC_VEF_P1NC.cpp.
References Source_Fluide_Dilatable_Face< Darcy_QC_VEF_P1NC >::contribuer_a_avec_impl().
{ contribuer_a_avec_impl(resu,mat); }
Objet_U * Darcy_QC_VEF_P1NC::cree_instance () [static]
Reimplemented from Source_Darcy_VEF_Face.
Definition at line 81 of file Source_QC_VEF_P1NC.cpp.
int Darcy_QC_VEF_P1NC::duplique () const [virtual]
Reimplemented from Source_Darcy_VEF_Face.
Definition at line 81 of file Source_QC_VEF_P1NC.cpp.
const Type_info * Darcy_QC_VEF_P1NC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_Darcy_VEF_Face.
Definition at line 81 of file Source_QC_VEF_P1NC.cpp.
const Type_info * Darcy_QC_VEF_P1NC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_Darcy_VEF_Face.
Definition at line 81 of file Source_QC_VEF_P1NC.cpp.
Sortie & Darcy_QC_VEF_P1NC::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_Darcy_VEF_Face.
Definition at line 82 of file Source_QC_VEF_P1NC.cpp.
{ return Source_Darcy_VEF_Face::printOn(os); }
Entree & Darcy_QC_VEF_P1NC::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_Darcy_VEF_Face.
Definition at line 83 of file Source_QC_VEF_P1NC.cpp.
{ return Source_Darcy_VEF_Face::readOn(is); }
const Darcy_QC_VEF_P1NC & Darcy_QC_VEF_P1NC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_Darcy_VEF_Face.
Definition at line 81 of file Source_QC_VEF_P1NC.cpp.
Darcy_QC_VEF_P1NC & Darcy_QC_VEF_P1NC::self_cast (Objet_U & r) [static]
Reimplemented from Source_Darcy_VEF_Face.
Definition at line 81 of file Source_QC_VEF_P1NC.cpp.
unsigned Darcy_QC_VEF_P1NC::taille_memoire () const [virtual]
Reimplemented from Source_Darcy_VEF_Face.
Definition at line 81 of file Source_QC_VEF_P1NC.cpp.
Member Data Documentation
const Type_info Darcy_QC_VEF_P1NC::info_obj [static]
Reimplemented from Source_Darcy_VEF_Face.
Definition at line 124 of file Source_QC_VEF_P1NC.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VEF/Source_QC_VEF_P1NC.h
src/ThHyd/Dilatable/Quasi_Compressible/VEF/Source_QC_VEF_P1NC.cpp