TRUST: Mod_turb_hyd_base Class Reference
Mod_turb_hyd_base Class Reference abstract
Classe Mod_turb_hyd_base
Cette classe sert de base a la hierarchie des classes
qui representent un modele de turbulence pour les
equations de Navier-Stokes. Il existe deja deux classes derivees
qui representent le modele de turbulence (k,e) et le modele
de turbulence sous maille. Ces deux modeles ont en commun
le calcul d'une viscosite turbulente.
B.Mat. : la classe herite de support_champ_masse_volumique.
en Front-Tracking (et plus tard en qc), elle fournit le
mecanisme pour recuperer rho.
#include <Mod_turb_hyd_base.h>
Public Member Functions
~Mod_turb_hyd_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Mod_turb_hyd_base ()
const Champ_Fonc & viscosite_turbulente () const
Renvoie la viscosite turbulente.
Equation_base & equation ()
Renvoie l'equation associee au modele de turbulence.
(c'est une equation du type Equation_base)
const Equation_base & equation () const
const Turbulence_paroi & loi_paroi () const
Turbulence_paroi & loi_paroi ()
bool utiliser_loi_paroi () const
virtual bool calcul_tenseur_Re (const DoubleTab &nu_turb, const DoubleTab &grad, DoubleTab &Re) const
virtual void set_param (Param &param)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int preparer_calcul ()
Prepare le calcul.
Initialise la loi de paroi.
Remplit le champ wall_length en cas de post traitemetn de la distance_paroi.
virtual bool initTimeStep (double dt)
virtual void mettre_a_jour (double)=0
virtual void discretiser ()
Discretise le modele de turbulence.
void discretiser_visc_turb (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
void discretiser_corr_visc_turb (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
void discretiser_K (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
Utilise par les modeles de tubulence dans TrioCFD.
virtual void completer ()
NE FAIT RIEN.
void associer_eqn (const Equation_base &)
Associe l'equation passe en parametre au modele de turbulence.
virtual void associer (const Zone_dis &, const Zone_Cl_dis &)
NE FAIT RIEN
a surcharger dans les classes derivees.
Associe la zone discretisee et la zone des conditions
aux limites discretisees au modele de turbulence.
int reprendre (Entree &) override
Reprend la loi de paroi.
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Champs_compris & champs_compris ()
virtual void imprimer (Sortie &) const
Effectue l'impression si cela est necessaire.
void a_faire (Sortie &) const
Effectue l'ecriture d'une identite si cela est necessaire.
int sauvegarder (Sortie &) const override
Sauvegarde le modele de turbulence sur un flot de sortie.
Sauvegarde le type de l'objet.
int limpr_ustar (double, double, double, double) const
double get_Cmu () const
Renvoie de la valeur de Cmu.
void lire_distance_paroi ()
Lit le fichier dom_Wall_length.xyz pour remplir le champs wall_length en vue d'un post-traitement de distance_paroi.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static const Type_info * info ()
static Mod_turb_hyd_base & self_cast (Objet_U &)
static const Mod_turb_hyd_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type et le nom de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les specifications d'un modele de turbulence
a partir d'un flot d'entree.
Format:
Modele_turbulence type_modele
{
[Turbulence_paroi la_loi_de_paroi]
bloc de lecture specifique du type de turbulence
}.
void limiter_viscosite_turbulente ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
double LeCmu
Champ_Fonc la_viscosite_turbulente
Champ_Fonc wall_length_
Ref_Equation_base mon_equation
Turbulence_paroi loipar
double dt_impr_ustar
double dt_impr_ustar_mean_only
int boundaries_
List_Nom boundaries_list
Nom nom_fichier_
Champs_compris champs_compris_
Private Attributes
double XNUTM
int calcul_borne_locale_visco_turb_
double dt_diff_sur_dt_conv_
Champ_Fonc corr_visco_turb
DoubleVect borne_visco_turb
Detailed Description
Classe Mod_turb_hyd_base
Cette classe sert de base a la hierarchie des classes
qui representent un modele de turbulence pour les
equations de Navier-Stokes. Il existe deja deux classes derivees
qui representent le modele de turbulence (k,e) et le modele
de turbulence sous maille. Ces deux modeles ont en commun
le calcul d'une viscosite turbulente.
B.Mat. : la classe herite de support_champ_masse_volumique.
en Front-Tracking (et plus tard en qc), elle fournit le
mecanisme pour recuperer rho.
Definition at line 54 of file Mod_turb_hyd_base.h.
Constructor & Destructor Documentation
~Mod_turb_hyd_base()
Mod_turb_hyd_base::~Mod_turb_hyd_base () override
Definition at line 34 of file Mod_turb_hyd_base.cpp.
Mod_turb_hyd_base()
Mod_turb_hyd_base::Mod_turb_hyd_base () inline
Definition at line 139 of file Mod_turb_hyd_base.h.
{
  LeCmu = CMU ;
  dt_impr_ustar=1.e20;
  dt_impr_ustar_mean_only=1.e20;
  boundaries_=0;
  nom_fichier_="";
  XNUTM = 1.E8 ;
  calcul_borne_locale_visco_turb_ = 0;
  dt_diff_sur_dt_conv_ = -1;
}
References boundaries_, calcul_borne_locale_visco_turb_, CMU, dt_diff_sur_dt_conv_, dt_impr_ustar, dt_impr_ustar_mean_only, LeCmu, nom_fichier_, and XNUTM.
Member Function Documentation
a_faire()
void Mod_turb_hyd_base::a_faire (Sortie & os) const
Effectue l'ecriture d'une identite si cela est necessaire.
Definition at line 590 of file Mod_turb_hyd_base.cpp.
{
  int afaire,special;
  EcritureLectureSpecial::is_ecriture_special(special,afaire);
  if (afaire)
    {
      Nom mon_ident(que_suis_je());
      mon_ident += equation().probleme().domaine().le_nom();
      double temps = equation().inconnue().temps();
      mon_ident += Nom(temps,"%e");
      os << mon_ident << finl;
      os << que_suis_je() << finl;
      os.flush();
    }
}
References Probleme_base::domaine(), equation(), finl, Sortie::flush(), Equation_base::inconnue(), EcritureLectureSpecial::is_ecriture_special(), Domaine::le_nom(), Equation_base::probleme(), Objet_U::que_suis_je(), and Champ_Inc::temps().
Referenced by sauvegarder().
associer()
void Mod_turb_hyd_base::associer (const Zone_dis & , const Zone_Cl_dis &) virtual
NE FAIT RIEN
a surcharger dans les classes derivees.
Associe la zone discretisee et la zone des conditions
aux limites discretisees au modele de turbulence.
Definition at line 259 of file Mod_turb_hyd_base.cpp.
{
  ;
}
Referenced by Mod_turb_hyd::readOn().
associer_eqn()
void Mod_turb_hyd_base::associer_eqn (const Equation_base & eqn)
Associe l'equation passe en parametre au modele de turbulence.
Definition at line 231 of file Mod_turb_hyd_base.cpp.
{
  mon_equation = eqn;
}
References mon_equation.
Referenced by Mod_turb_hyd::readOn().
calcul_tenseur_Re()
virtual bool Mod_turb_hyd_base::calcul_tenseur_Re (const DoubleTab & nu_turb, const DoubleTab & grad, DoubleTab & Re) const inline virtual
Definition at line 78 of file Mod_turb_hyd_base.h.
  {
// Not coded
    return false;
  };
Referenced by Op_Dift_VEF_Face::ajouter_cas_vectoriel().
champs_compris()
Champs_compris & Mod_turb_hyd_base::champs_compris () inline
Definition at line 224 of file Mod_turb_hyd_base.h.
{
  return champs_compris_;
}
References champs_compris_.
completer()
void Mod_turb_hyd_base::completer (void) virtual
NE FAIT RIEN.
Definition at line 279 of file Mod_turb_hyd_base.cpp.
{
  ;
}
Referenced by Mod_turb_hyd::completer().
creer_champ()
void Mod_turb_hyd_base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
Definition at line 434 of file Mod_turb_hyd_base.cpp.
{
  if (loipar.non_nul())
    {
      loipar->creer_champ(motlu);
    }
}
References loipar, and O_U_Ptr::non_nul().
discretiser()
void Mod_turb_hyd_base::discretiser () virtual
Discretise le modele de turbulence.
Definition at line 340 of file Mod_turb_hyd_base.cpp.
{
  Cerr << "Turbulence hydraulic model discretization" << finl;
  discretiser_visc_turb(mon_equation->schema_temps(),mon_equation->zone_dis(),
                        la_viscosite_turbulente);
  champs_compris_.ajoute_champ(la_viscosite_turbulente);
  discretiser_corr_visc_turb(mon_equation->schema_temps(),mon_equation->zone_dis(),corr_visco_turb);
  champs_compris_.ajoute_champ(corr_visco_turb);
  const Discretisation_base& dis=ref_cast(Discretisation_base, mon_equation->discretisation());
  dis.discretiser_champ("champ_elem",mon_equation->zone_dis().valeur(),"distance_paroi","m",1,mon_equation->schema_temps().temps_courant(),wall_length_);
  champs_compris_.ajoute_champ(wall_length_);
}
References Champs_compris::ajoute_champ(), Cerr, champs_compris_, corr_visco_turb, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), discretiser_corr_visc_turb(), discretiser_visc_turb(), finl, la_viscosite_turbulente, mon_equation, ref_cast, Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), Deriv_Zone_dis_base::valeur(), wall_length_, and Equation_base::zone_dis().
Referenced by Mod_turb_hyd::discretiser().
discretiser_corr_visc_turb()
void Mod_turb_hyd_base::discretiser_corr_visc_turb (const Schema_Temps_base & sch, Zone_dis & z, Champ_Fonc & ch) const
Definition at line 368 of file Mod_turb_hyd_base.cpp.
{
  Cerr << "Turbulent viscosity correction field discretization" << finl;
  const Discretisation_base& dis = mon_equation->discretisation();
  dis.discretiser_champ("champ_elem",z.valeur(),"corr_visco_turb","adimensionnel",1,sch.temps_courant(),ch);
}
References Cerr, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), finl, mon_equation, Schema_Temps_base::temps_courant(), and Deriv_Zone_dis_base::valeur().
Referenced by discretiser().
discretiser_K()
void Mod_turb_hyd_base::discretiser_K (const Schema_Temps_base & sch, Zone_dis & z, Champ_Fonc & ch) const
Utilise par les modeles de tubulence dans TrioCFD.
Definition at line 376 of file Mod_turb_hyd_base.cpp.
{
  Cerr << "Kinetic turbulent energy field discretisation" << finl;
  const Discretisation_base& dis = mon_equation->discretisation();
  dis.discretiser_champ("champ_elem",z.valeur(),"K","m2/s2",1,sch.temps_courant(),ch);
}
References Cerr, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), finl, mon_equation, Schema_Temps_base::temps_courant(), and Deriv_Zone_dis_base::valeur().
discretiser_visc_turb()
void Mod_turb_hyd_base::discretiser_visc_turb (const Schema_Temps_base & sch, Zone_dis & z, Champ_Fonc & ch) const
Definition at line 354 of file Mod_turb_hyd_base.cpp.
{
  int is_dilat = equation().probleme().is_dilatable();
  if (!is_dilat)
    Cerr << "Turbulent viscosity field discretization" << finl;
  else
    Cerr << "Turbulent dynamic viscosity field discretization" << finl;
  Nom nom = (is_dilat==1) ? "viscosite_dynamique_turbulente" : "viscosite_turbulente";
  Nom unite = (is_dilat==1) ? "kg/(m.s)" : "m2/s";
  const Discretisation_base& dis = mon_equation->discretisation();
  dis.discretiser_champ("champ_elem",z.valeur(),nom,unite,1,sch.temps_courant(),ch);
}
References Cerr, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), equation(), finl, Probleme_base::is_dilatable(), mon_equation, Equation_base::probleme(), Schema_Temps_base::temps_courant(), and Deriv_Zone_dis_base::valeur().
Referenced by discretiser().
equation() [1/2]
Equation_base & Mod_turb_hyd_base::equation () inline
Renvoie l'equation associee au modele de turbulence.
(c'est une equation du type Equation_base)
Returns
Equation_base&
Signification: l'equation associee au modele de turbulence
Contraintes: reference constante
Definition at line 185 of file Mod_turb_hyd_base.h.
{
  if (mon_equation.non_nul()==0)
    {
      Cerr << "\nError in Mod_turb_hyd_base::equation() : The equation is unknown !" << finl;
      Process::exit();
    }
  return mon_equation.valeur();
}
References Cerr, Process::exit(), finl, mon_equation, O_U_Ptr::non_nul(), and Ref_Equation_base::valeur().
Referenced by a_faire(), Turbulence_paroi_base::creer_champ(), discretiser_visc_turb(), Turbulence_paroi_base::get_champ(), limiter_viscosite_turbulente(), lire_distance_paroi(), lire_motcle_non_standard(), Turbulence_paroi_base::ouvrir_fichier_partage(), preparer_calcul(), Turbulence_paroi::readOn(), Modele_turbulence_hyd_nul::readOn(), and Modele_turbulence_hyd_nul::sauvegarder().
equation() [2/2]
const Equation_base & Mod_turb_hyd_base::equation () const inline
Definition at line 195 of file Mod_turb_hyd_base.h.
{
  if (mon_equation.non_nul()==0)
    {
      Cerr << "\nError in Mod_turb_hyd_base::equation() : The equation is unknown !" << finl;
      Process::exit();
    }
  return mon_equation.valeur();
}
References Cerr, Process::exit(), finl, mon_equation, O_U_Ptr::non_nul(), and Ref_Equation_base::valeur().
get_champ()
const Champ_base & Mod_turb_hyd_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Definition at line 442 of file Mod_turb_hyd_base.cpp.
{
  REF(Champ_base) ref_champ;
  try
    {
      return champs_compris_.get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  if (loipar.non_nul())
    {
      try
        {
          return loipar->get_champ(nom);
        }
      catch (Champs_compris_erreur)
        {
        }
    }
  throw Champs_compris_erreur();
}
References champs_compris_, Champs_compris::get_champ(), loipar, O_U_Ptr::non_nul(), and REF.
get_Cmu()
double Mod_turb_hyd_base::get_Cmu () const inline
Renvoie de la valeur de Cmu.
Returns
la valeur Cmu
Signification:
Contraintes:
Definition at line 219 of file Mod_turb_hyd_base.h.
{
  return LeCmu;
}
References LeCmu.
get_info()
const Type_info * Mod_turb_hyd_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_nul.
Definition at line 34 of file Mod_turb_hyd_base.cpp.
get_noms_champs_postraitables()
void Mod_turb_hyd_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
Definition at line 467 of file Mod_turb_hyd_base.cpp.
{
  if (opt==DESCRIPTION)
    Cerr<<que_suis_je()<<" : "<<champs_compris_.liste_noms_compris()<<finl;
  else
    nom.add(champs_compris_.liste_noms_compris());
  if (loipar.non_nul())
    loipar->get_noms_champs_postraitables(nom,opt);
}
References Vect_Nom::add(), Cerr, champs_compris_, DESCRIPTION, finl, Champs_compris::liste_noms_compris(), loipar, O_U_Ptr::non_nul(), and Objet_U::que_suis_je().
imprimer()
void Mod_turb_hyd_base::imprimer (Sortie & os) const virtual
Effectue l'impression si cela est necessaire.
Definition at line 492 of file Mod_turb_hyd_base.cpp.
{
  const Schema_Temps_base& sch = mon_equation->schema_temps();
  double temps_courant = sch.temps_courant();
  double dt= sch.pas_de_temps() ;
  if (loipar.non_nul() && limpr_ustar(temps_courant,sch.temps_precedent(),dt,dt_impr_ustar) )
    loipar.imprimer_ustar(os);
  if (loipar.non_nul() && limpr_ustar(temps_courant,sch.temps_precedent(),dt,dt_impr_ustar_mean_only) )
    loipar.imprimer_ustar_mean_only(os, boundaries_, boundaries_list, nom_fichier_);
}
References boundaries_, boundaries_list, dt_impr_ustar, dt_impr_ustar_mean_only, Turbulence_paroi::imprimer_ustar(), Turbulence_paroi::imprimer_ustar_mean_only(), limpr_ustar(), loipar, mon_equation, nom_fichier_, O_U_Ptr::non_nul(), Schema_Temps_base::pas_de_temps(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), and Schema_Temps_base::temps_precedent().
Referenced by Mod_turb_hyd::imprimer().
info()
const Type_info * Mod_turb_hyd_base::info () static
Definition at line 34 of file Mod_turb_hyd_base.cpp.
initTimeStep()
bool Mod_turb_hyd_base::initTimeStep (double dt) virtual
Definition at line 429 of file Mod_turb_hyd_base.cpp.
{
  return true;
}
limiter_viscosite_turbulente()
void Mod_turb_hyd_base::limiter_viscosite_turbulente () protected
Definition at line 607 of file Mod_turb_hyd_base.cpp.
{
// On initial
  int size = viscosite_turbulente().valeurs().size();
  DoubleTab& visco_turb = la_viscosite_turbulente.valeurs();
  if (borne_visco_turb.size()==0)
    borne_visco_turb=visco_turb; //.resize(size);
  borne_visco_turb = XNUTM;
  if (calcul_borne_locale_visco_turb_ && (equation().schema_temps().nb_pas_dt() != 0 || equation().probleme().reprise_effectuee()))
    {
// On recalcule les bornes de la viscosite turbulente apres le premier pas de temps
      const Operateur_Diff_base& op_diff = ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base());
      const Operateur_Conv_base& op_conv = ref_cast(Operateur_Conv_base,equation().operateur(1).l_op_base());
      op_diff.calculer_borne_locale(borne_visco_turb, op_conv.dt_stab_conv(), dt_diff_sur_dt_conv_);
    }
// On borne la viscosite turbulente
  int nb_elem = equation().zone_dis().zone().nb_elem();
  assert(nb_elem==size);
  int compt=0;
  Debog::verifier("Mod_turb_hyd_base::limiter_viscosite_turbulente la_viscosite_turbulente before",la_viscosite_turbulente.valeurs());
// Debog::verifier("Mod_turb_hyd_base::limiter_viscosite_turbulente visco_turb before",visco_turb);
// Debog::verifier("Mod_turb_hyd_base::limiter_viscosite_turbulente borne_visco_turb",borne_visco_turb);
// Debog::verifier("Mod_turb_hyd_base::limiter_viscosite_turbulente corr_visco_turb before",corr_visco_turb);
  for (int elem=0; elem<nb_elem; elem++)
    {
      if (visco_turb(elem) > borne_visco_turb(elem))
        {
          compt++;
          corr_visco_turb.valeurs()(elem) = borne_visco_turb(elem) / visco_turb(elem);
          visco_turb(elem) = borne_visco_turb(elem);
        }
      else
        corr_visco_turb.valeurs()(elem) = 1.;
    }
  corr_visco_turb.changer_temps(mon_equation->inconnue().temps());
  visco_turb.echange_espace_virtuel();
// Debog::verifier("Mod_turb_hyd_base::limiter_viscosite_turbulente corr_visco_turb after",corr_visco_turb);
// Debog::verifier("Mod_turb_hyd_base::limiter_viscosite_turbulente visco_turb after",visco_turb);
  Debog::verifier("Mod_turb_hyd_base::limiter_viscosite_turbulente la_viscosite_turbulente after",la_viscosite_turbulente.valeurs());
// On imprime
  int imprimer_compt=0;
  if (mon_equation->schema_temps().temps_impr() <= mon_equation->schema_temps().pas_de_temps())
    imprimer_compt=1;
  else
    {
      if (mon_equation->schema_temps().nb_pas_dt()==0)
        imprimer_compt=0;
      else
        {
// Voir Schema_Temps_base::limpr pour information sur epsilon et modf
          double i, j, epsilon = 1.e-8;
          modf(mon_equation->schema_temps().temps_courant()/mon_equation->schema_temps().temps_impr()+epsilon, &i);
          modf((mon_equation->schema_temps().temps_courant()-mon_equation->schema_temps().pas_de_temps())/mon_equation->schema_temps().temps_impr()+epsilon, &j);
          if ( i>j )
            imprimer_compt=1;
        }
    }
  if (imprimer_compt)
    {
// PL: optimization to avoid 2 mp_sum instead 1:
      ArrOfInt tmp(2);
      tmp[0]=compt;
      tmp[1]=size;
      mp_sum_for_each_item(tmp);
      /*      compt=mp_sum(compt);
            size=mp_sum(size); */
      double pourcent = 100*(float(tmp[0])/tmp[1]);
      if (je_suis_maitre() && pourcent>0)
        Cout<<"\nTurbulent viscosity has been limited on "<<pourcent<<" % of cells mesh."<<finl;
    }
}
References borne_visco_turb, calcul_borne_locale_visco_turb_, Operateur_Diff_base::calculer_borne_locale(), Champ_Fonc::changer_temps(), corr_visco_turb, Cout, dt_diff_sur_dt_conv_, Operateur_Conv_base::dt_stab_conv(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), equation(), finl, Equation_base::inconnue(), Process::je_suis_maitre(), la_viscosite_turbulente, mon_equation, mp_sum_for_each_item(), Zone::nb_elem(), Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::pas_de_temps(), ref_cast, Equation_base::schema_temps(), TRUSTVect< _TYPE_ >::size(), Champ_Inc::temps(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_impr(), Champ_Fonc::valeurs(), Debog::verifier(), viscosite_turbulente(), XNUTM, Zone_dis::zone(), and Equation_base::zone_dis().
limpr_ustar()
int Mod_turb_hyd_base::limpr_ustar (double temps_courant, double temps_prec, double dt, double dt_ustar) const
Definition at line 503 of file Mod_turb_hyd_base.cpp.
{
  const Schema_Temps_base& sch = mon_equation->schema_temps();
  if (sch.nb_pas_dt()==0)
    return 0;
  if (dt_ustar<=dt || (( sch.temps_cpu_max_atteint() || (!get_disable_stop() && sch.stop_lu()) || sch.temps_final_atteint() || sch.nb_pas_dt_max_atteint() || sch.nb_pas_dt()==1 || sch.stationnaire_atteint()) && !est_egal(dt_ustar,1.e20) ) )
    return 1;
  else
    {
// Voir Schema_Temps_base::limpr pour information sur epsilon et modf
      double i, j, epsilon = 1.e-8;
      modf(temps_courant/dt_ustar + epsilon, &i);
      modf(temps_prec/dt_ustar + epsilon, &j);
      return ( i>j );
    }
}
References est_egal(), get_disable_stop(), mon_equation, Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::nb_pas_dt_max_atteint(), Equation_base::schema_temps(), Schema_Temps_base::stationnaire_atteint(), Schema_Temps_base::stop_lu(), Schema_Temps_base::temps_cpu_max_atteint(), and Schema_Temps_base::temps_final_atteint().
Referenced by imprimer().
lire_distance_paroi()
void Mod_turb_hyd_base::lire_distance_paroi ()
Lit le fichier dom_Wall_length.xyz pour remplir le champs wall_length en vue d'un post-traitement de distance_paroi.
Definition at line 299 of file Mod_turb_hyd_base.cpp.
{
// PQ : 25/02/04 recuperation de la distance a la paroi dans Wall_length.xyz
  DoubleTab& wall_length = wall_length_.valeurs();
  wall_length=-1.;
  LecFicDiffuse fic;
  Nom nom_fic = equation().probleme().domaine().le_nom()+"_Wall_length.xyz";
  fic.set_bin(1);
  if(!fic.ouvrir(nom_fic))
    {
      Cerr << " File " << nom_fic << " doesn't exist. To generate it, please, refer to html.doc (Distance_paroi) " << finl;
      exit();
    }
  Noms nom_paroi;
  fic >> nom_paroi;
  EcritureLectureSpecial::lecture_special(wall_length_, fic);
}
References Cerr, Probleme_base::domaine(), equation(), Process::exit(), finl, Domaine::le_nom(), EcritureLectureSpecial::lecture_special(), LecFicDiffuse::ouvrir(), Equation_base::probleme(), Lec_Diffuse_base::set_bin(), Champ_Fonc::valeurs(), and wall_length_.
Referenced by preparer_calcul().
lire_motcle_non_standard()
int Mod_turb_hyd_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
< liste stockant tous les noms de frontiere du domaine
< boundaries ou accolade_fermee ou pasbon
Reimplemented from Objet_U.
Definition at line 112 of file Mod_turb_hyd_base.cpp.
{
  Motcle motlu;
  if (mot=="turbulence_paroi")
    {
      loipar.associer_modele(*this);
      is >> loipar;
      is >> loipar.valeur();
      return 1;
    }
  else if (loipar.valeur().que_suis_je()!="negligeable_VDF" && loipar.valeur().que_suis_je()!="negligeable_VEF" && !loipar.valeur().que_suis_je().debute_par("negligeable_PolyMAC"))
    {
      if (mot=="dt_impr_ustar")
        {
// nom_fichier_=Objet_U::nom_du_cas()+"_"+equation().probleme().le_nom()+"_ustar";
          is >>  dt_impr_ustar;
        }
      else if (mot=="dt_impr_ustar_mean_only")
        {
          Nom accolade_ouverte="{";
          Nom accolade_fermee="}";
          nom_fichier_=Objet_U::nom_du_cas()+"_"+equation().probleme().le_nom()+"_ustar_mean_only";
          Domaine& dom=equation().probleme().domaine();
          Zone& zone=dom.zone(0);
          LIST(Nom) nlistbord_dom;                      //!< liste stockant tous les noms de frontiere du domaine
          int nbfr=zone.nb_front_Cl();
          for (int b=0; b<nbfr; b++)
            {
              Frontiere& org=zone.frontiere(b);
              nlistbord_dom.add(org.le_nom());
            }
          is >> motlu;
          if ( motlu != accolade_ouverte )
            {
              Cerr << motlu << " is not a keyword understood by " << que_suis_je() << " in lire_motcle_non_standard"<< finl;
              Cerr << "A specification of kind : dt_impr_ustar_mean_only { dt_impr periode [boundaries nb_boundaries boundary_name1 boundary_name2 ... ] } was expected."<<finl;
              exit();
            }
          is >> motlu;
          if (motlu!="dt_impr")
            {
              Cerr<<"We expected dt_impr..."<<finl;
              exit();
            }
          is >>  dt_impr_ustar_mean_only;
          is >> motlu; //!< boundaries ou accolade_fermee ou pasbon
          if ( motlu != accolade_fermee )
            {
              if ( motlu == "boundaries" )
                {
                  boundaries_=1;
                  int nb_bords=0;
                  Nom nom_bord_lu;
// read boundaries number
                  is >> nb_bords;
                  if ( nb_bords != 0 )
                    {
// read boundaries
                      for ( int i=0; i<nb_bords; i++ )
{
                          is >> nom_bord_lu;
                          boundaries_list.add(Nom(nom_bord_lu));
// verif nom bords
                          if (!nlistbord_dom.contient(boundaries_list[i]))
{
                              Cerr << "Problem in the dt_impr_ustar_mean_only instruction:" << finl;
                              Cerr << "The boundary named '" << boundaries_list[i] << "' is not a boundary of the domain " << dom.le_nom() << "." << finl;
                              exit();
                            }
                        }
                    }
// lecture accolade fermee
                  is >> motlu;
                  if ( motlu != accolade_fermee )
                    {
                      Cerr << "Problem in the dt_impr_ustar_mean_only instruction:" << finl;
                      Cerr << "TRUST wants to read a '" << accolade_fermee << "' but find '" << motlu << "'!!" << finl;
                      exit();
                    }
                }
              else
                {
                  Cerr << motlu << " is not a keyword understood by " << que_suis_je() << " in lire_motcle_non_standard"<< finl;
                  Cerr << "A specification of kind : dt_impr_ustar_mean_only { dt_impr periode [boundaries nb_boundaries boundary_name1 boundary_name2 ... ] } was expected."<<finl;
                  exit();
                }
            }
        } //!< fin dt_impr_ustar_mean_only
      else
        {
          Cerr << "Please remove dt_impr_ustar option if the wall law is of Negligeable type." << finl;
          exit();
        }
    } //!< fin loi paroi negligeable
  else
    {
      Cerr << mot << " is not a keyword understood by " << que_suis_je() << " in lire_motcle_non_standard"<< finl;
      exit();
    }
  return -1;
}
References Frontiere::add(), List_Nom::add(), Turbulence_paroi::associer_modele(), boundaries_, boundaries_list, Cerr, Nom::debute_par(), Probleme_base::domaine(), dt_impr_ustar, dt_impr_ustar_mean_only, equation(), Process::exit(), finl, Zone::frontiere(), Probleme_base::le_nom(), Domaine::le_nom(), Frontiere::le_nom(), LIST, loipar, Zone::nb_front_Cl(), Objet_U::nom_du_cas(), nom_fichier_, Equation_base::probleme(), Objet_U::que_suis_je(), Deriv_Turbulence_paroi_base::valeur(), and Domaine::zone().
loi_paroi() [1/2]
Turbulence_paroi & Mod_turb_hyd_base::loi_paroi () inline
Definition at line 70 of file Mod_turb_hyd_base.h.
  {
    return loipar;
  };
References loipar.
loi_paroi() [2/2]
const Turbulence_paroi & Mod_turb_hyd_base::loi_paroi () const inline
Definition at line 66 of file Mod_turb_hyd_base.h.
  {
    return loipar;
  };
References loipar.
Referenced by Op_Dift_VDF_Face_Axi_base::associer_modele_turbulence(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Mod_turb_hyd::completer(), Champ_P1NC_implementation::filtrer_L2(), Mod_turb_hyd::loi_paroi(), Eval_Dift_VDF_const_Face::mettre_a_jour(), Eval_Dift_VDF_var_Face::mettre_a_jour(), Op_Dift_EF_base::mettre_a_jour(), Op_Dift_VEF_base::mettre_a_jour(), Op_Dift_VDF_Face_Axi_base::mettre_a_jour(), Modele_turbulence_scal_base::readOn(), Turbulence_paroi_scal::readOn(), and utiliser_loi_paroi().
mettre_a_jour()
virtual void Mod_turb_hyd_base::mettre_a_jour (double) pure virtual
Implemented in Modele_turbulence_hyd_nul.
Referenced by Mod_turb_hyd::mettre_a_jour().
preparer_calcul()
int Mod_turb_hyd_base::preparer_calcul (void) virtual
Prepare le calcul.
Initialise la loi de paroi.
Remplit le champ wall_length en cas de post traitemetn de la distance_paroi.
Returns
int
Signification: code de retour de Turbulence_paroi::init_lois_paroi()
Contraintes:
Definition at line 400 of file Mod_turb_hyd_base.cpp.
{
  int res = 1;
  if (loipar.non_nul())
    res = loipar.init_lois_paroi();
  LIST_CURSEUR(DERIV(Postraitement_base)) curseur = equation().probleme().postraitements();
  bool contient_distance_paroi = false;
  while (curseur && !contient_distance_paroi)
    {
      if (sub_type(Postraitement,curseur.valeur().valeur()))
        {
          Postraitement& post = ref_cast(Postraitement,curseur.valeur().valeur());
          for (int i=0; i<post.noms_champs_a_post().size(); i++)
            {
              if (post.noms_champs_a_post()[i].contient("DISTANCE_PAROI"))
                {
                  lire_distance_paroi();
                  contient_distance_paroi = true;
                  break;
                }
            }
        }
      ++curseur;
    }
  loipar.imprimer_premiere_ligne_ustar(boundaries_, boundaries_list, nom_fichier_);
  return res;
}
References boundaries_, boundaries_list, List_Nom::contient(), DERIV, equation(), Turbulence_paroi::imprimer_premiere_ligne_ustar(), Turbulence_paroi::init_lois_paroi(), lire_distance_paroi(), LIST_CURSEUR, loipar, nom_fichier_, Postraitement::noms_champs_a_post(), O_U_Ptr::non_nul(), Probleme_base::postraitements(), Equation_base::probleme(), ref_cast, and sub_type.
Referenced by Mod_turb_hyd::preparer_calcul().
printOn()
Sortie & Mod_turb_hyd_base::printOn (Sortie & s) const override protected virtual
Ecrit le type et le nom de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_nul.
Definition at line 50 of file Mod_turb_hyd_base.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Mod_turb_hyd_base::readOn (Entree & is) override protected virtual
Lit les specifications d'un modele de turbulence
a partir d'un flot d'entree.
Format:
Modele_turbulence type_modele
{
[Turbulence_paroi la_loi_de_paroi]
bloc de lecture specifique du type de turbulence
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_nul.
Definition at line 78 of file Mod_turb_hyd_base.cpp.
{
  Cerr<<"Reading of data for a "<<que_suis_je()<<" hydraulic turbulence model"<<finl;
  Param param(que_suis_je());
  set_param(param);
  param.lire_avec_accolades_depuis(is);
// Verifications
// Cas ou Correction_visco_turb_pour_controle_pas_de_temps_parametre est lu sans Correction_visco_turb_pour_controle_pas_de_temps
  if (dt_diff_sur_dt_conv_!=-1)
    calcul_borne_locale_visco_turb_=1;
// Cas ou Correction_visco_turb_pour_controle_pas_de_temps sans Correction_visco_turb_pour_controle_pas_de_temps_parametre
  else if (calcul_borne_locale_visco_turb_)
    dt_diff_sur_dt_conv_=1;
// Cas ou Correction_visco_turb_pour_controle_pas_de_temps_parametre est incorrectement fixe
  if (dt_diff_sur_dt_conv_<=0 && calcul_borne_locale_visco_turb_)
    {
      Cerr << "Parameter value Correction_visco_turb_pour_controle_pas_de_temps_parametre must be strictly positive." << finl;
      exit();
    }
  return is;
}
References calcul_borne_locale_visco_turb_, Cerr, dt_diff_sur_dt_conv_, Process::exit(), finl, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
reprendre()
int Mod_turb_hyd_base::reprendre (Entree & is) override virtual
Reprend la loi de paroi.
Returns
int
Signification: renvoie toujours 0
Contraintes:
Reimplemented from Objet_U.
Definition at line 569 of file Mod_turb_hyd_base.cpp.
{
  if (loipar.non_nul())
    loipar->reprendre(is);
  return 0;
}
References loipar, O_U_Ptr::non_nul(), and Objet_U::reprendre().
Referenced by Mod_turb_hyd::reprendre().
sauvegarder()
int Mod_turb_hyd_base::sauvegarder (Sortie & os) const override virtual
Sauvegarde le modele de turbulence sur un flot de sortie.
Sauvegarde le type de l'objet.
Returns
int
Signification: renvoie toujours 1
Contraintes:
< OC: pour le bas Re, on ecrit negligeable => pas de pb a faire ceci ?
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_nul.
Definition at line 536 of file Mod_turb_hyd_base.cpp.
{
  a_faire(os);
  if (loipar.non_nul())
    {
      loipar->sauvegarder(os);
    }
  else  //!< OC: pour le bas Re, on ecrit negligeable => pas de pb a faire ceci ?
    {
      const Discretisation_base& discr=mon_equation->discretisation();
      Nom nom_discr=discr.que_suis_je();
      Nom type = "negligeable_";
      type+=nom_discr.substr_old(1,3);
      os << type << finl;
    }
// Verification que l'appel a bien ete fait a Mod_turb_hyd_base::limiter_viscosite_turbulente()
  assert(mp_sum(borne_visco_turb.size())!=0);
  return 0;
}
References a_faire(), borne_visco_turb, Equation_base::discretisation(), finl, loipar, mon_equation, Process::mp_sum(), O_U_Ptr::non_nul(), Objet_U::que_suis_je(), Objet_U::sauvegarder(), TRUSTVect< _TYPE_ >::size(), and Nom::substr_old().
Referenced by Mod_turb_hyd::sauvegarder().
self_cast() [1/2]
const Mod_turb_hyd_base & Mod_turb_hyd_base::self_cast (const Objet_U & r) static
Definition at line 34 of file Mod_turb_hyd_base.cpp.
self_cast() [2/2]
Mod_turb_hyd_base & Mod_turb_hyd_base::self_cast (Objet_U & r) static
Definition at line 34 of file Mod_turb_hyd_base.cpp.
set_param()
void Mod_turb_hyd_base::set_param (Param & param) virtual
Definition at line 100 of file Mod_turb_hyd_base.cpp.
{
  param.ajouter_non_std("turbulence_paroi",(this),Param::REQUIRED);
  param.ajouter_non_std("dt_impr_ustar",(this));
  param.ajouter_non_std("dt_impr_ustar_mean_only",(this));
  param.ajouter("nut_max",&XNUTM);
  param.ajouter_flag("Correction_visco_turb_pour_controle_pas_de_temps",&calcul_borne_locale_visco_turb_);
  param.ajouter("Correction_visco_turb_pour_controle_pas_de_temps_parametre",&dt_diff_sur_dt_conv_);
// param.ajouter_condition("not(is_read_dt_impr_ustar_mean_only_and_is_read_dt_impr_ustar)","only one of dt_impr_ustar_mean_only and dt_impr_ustar can be used");
}
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), calcul_borne_locale_visco_turb_, dt_diff_sur_dt_conv_, Param::REQUIRED, and XNUTM.
Referenced by readOn().
utiliser_loi_paroi()
bool Mod_turb_hyd_base::utiliser_loi_paroi () const inline
Definition at line 74 of file Mod_turb_hyd_base.h.
  {
    return loi_paroi().non_nul() ? loipar->use_shear() : false;
  };
References loi_paroi(), loipar, and O_U_Ptr::non_nul().
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_EF_Q1::ajouter_bords(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), Eval_Dift_VDF_const_Face::uses_wall(), and Eval_Dift_VDF_var_Face::uses_wall().
viscosite_turbulente()
const Champ_Fonc & Mod_turb_hyd_base::viscosite_turbulente () const inline
Renvoie la viscosite turbulente.
Returns
Champ_Fonc&
Signification: le champ representant la viscosite turbulente
Contraintes: reference constante
Definition at line 164 of file Mod_turb_hyd_base.h.
{
  return la_viscosite_turbulente;
}
References la_viscosite_turbulente.
Referenced by Op_Dift_VDF_Face_Axi_base::associer_modele_turbulence(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Op_Dift_EF_base::completer(), Op_Dift_VEF_base::completer(), Op_Diff_Dift_VDF< OP_TYPE >::completer_impl(), limiter_viscosite_turbulente(), and Mod_turb_hyd::viscosite_turbulente().
Member Data Documentation
borne_visco_turb
DoubleVect Mod_turb_hyd_base::borne_visco_turb private
Definition at line 136 of file Mod_turb_hyd_base.h.
Referenced by limiter_viscosite_turbulente(), and sauvegarder().
boundaries_
int Mod_turb_hyd_base::boundaries_ protected
Definition at line 123 of file Mod_turb_hyd_base.h.
Referenced by imprimer(), lire_motcle_non_standard(), Mod_turb_hyd_base(), and preparer_calcul().
boundaries_list
List_Nom Mod_turb_hyd_base::boundaries_list protected
Definition at line 124 of file Mod_turb_hyd_base.h.
Referenced by imprimer(), lire_motcle_non_standard(), and preparer_calcul().
calcul_borne_locale_visco_turb_
int Mod_turb_hyd_base::calcul_borne_locale_visco_turb_ private
Definition at line 133 of file Mod_turb_hyd_base.h.
Referenced by limiter_viscosite_turbulente(), Mod_turb_hyd_base(), readOn(), and set_param().
champs_compris_
Champs_compris Mod_turb_hyd_base::champs_compris_ protected
Definition at line 128 of file Mod_turb_hyd_base.h.
Referenced by champs_compris(), discretiser(), get_champ(), and get_noms_champs_postraitables().
corr_visco_turb
Champ_Fonc Mod_turb_hyd_base::corr_visco_turb private
Definition at line 135 of file Mod_turb_hyd_base.h.
Referenced by discretiser(), and limiter_viscosite_turbulente().
dt_diff_sur_dt_conv_
double Mod_turb_hyd_base::dt_diff_sur_dt_conv_ private
Definition at line 134 of file Mod_turb_hyd_base.h.
Referenced by limiter_viscosite_turbulente(), Mod_turb_hyd_base(), readOn(), and set_param().
dt_impr_ustar
double Mod_turb_hyd_base::dt_impr_ustar protected
Definition at line 121 of file Mod_turb_hyd_base.h.
Referenced by imprimer(), lire_motcle_non_standard(), and Mod_turb_hyd_base().
dt_impr_ustar_mean_only
double Mod_turb_hyd_base::dt_impr_ustar_mean_only protected
Definition at line 122 of file Mod_turb_hyd_base.h.
Referenced by imprimer(), lire_motcle_non_standard(), and Mod_turb_hyd_base().
info_obj
const Type_info Mod_turb_hyd_base::info_obj static
Definition at line 59 of file Mod_turb_hyd_base.h.
la_viscosite_turbulente
Champ_Fonc Mod_turb_hyd_base::la_viscosite_turbulente protected
Definition at line 117 of file Mod_turb_hyd_base.h.
Referenced by discretiser(), limiter_viscosite_turbulente(), and viscosite_turbulente().
LeCmu
double Mod_turb_hyd_base::LeCmu protected
Definition at line 116 of file Mod_turb_hyd_base.h.
Referenced by get_Cmu(), and Mod_turb_hyd_base().
loipar
Turbulence_paroi Mod_turb_hyd_base::loipar protected
Definition at line 120 of file Mod_turb_hyd_base.h.
Referenced by creer_champ(), get_champ(), get_noms_champs_postraitables(), imprimer(), lire_motcle_non_standard(), loi_paroi(), preparer_calcul(), Modele_turbulence_hyd_nul::readOn(), reprendre(), sauvegarder(), and utiliser_loi_paroi().
mon_equation
Ref_Equation_base Mod_turb_hyd_base::mon_equation protected
Definition at line 119 of file Mod_turb_hyd_base.h.
Referenced by associer_eqn(), discretiser(), discretiser_corr_visc_turb(), discretiser_K(), discretiser_visc_turb(), equation(), imprimer(), limiter_viscosite_turbulente(), limpr_ustar(), and sauvegarder().
nom_fichier_
Nom Mod_turb_hyd_base::nom_fichier_ protected
Definition at line 125 of file Mod_turb_hyd_base.h.
Referenced by imprimer(), lire_motcle_non_standard(), Mod_turb_hyd_base(), and preparer_calcul().
wall_length_
Champ_Fonc Mod_turb_hyd_base::wall_length_ protected
Definition at line 118 of file Mod_turb_hyd_base.h.
Referenced by discretiser(), and lire_distance_paroi().
XNUTM
double Mod_turb_hyd_base::XNUTM private
Definition at line 132 of file Mod_turb_hyd_base.h.
Referenced by limiter_viscosite_turbulente(), Mod_turb_hyd_base(), and set_param().
The documentation for this class was generated from the following files:
src/ThHyd/Modele_turbulence_base/Mod_turb_hyd_base.h
src/ThHyd/Modele_turbulence_base/Mod_turb_hyd_base.cpp