TRUST: Verifier_Simplexes Class Reference
Verifier_Simplexes Class Reference
: class Verifier_Simplexes
<Description of class Verifier_Simplexes>
#include <Verifier_Simplexes.h>
Public Member Functions
Verifier_Simplexes ()
~Verifier_Simplexes ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Verifier_Simplexes & self_cast (Objet_U &)
static const Verifier_Simplexes & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static void check_domain (Domaine &domain)
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
: class Verifier_Simplexes
<Description of class Verifier_Simplexes>
Definition at line 38 of file Verifier_Simplexes.h.
Constructor & Destructor Documentation
Verifier_Simplexes::Verifier_Simplexes ()
Definition at line 27 of file Verifier_Simplexes.cpp.
Verifier_Simplexes::~Verifier_Simplexes ()
Definition at line 27 of file Verifier_Simplexes.cpp.
Member Function Documentation
void Verifier_Simplexes::check_domain (Domaine & domain) [static]
Definition at line 295 of file Verifier_Simplexes.cpp.
References check_internal_diagonal(), and check_positive_volumes().
Referenced by interpreter_().
{
  check_internal_diagonal(domain);
  check_positive_volumes(domain);
}
Objet_U * Verifier_Simplexes::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 27 of file Verifier_Simplexes.cpp.
int Verifier_Simplexes::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 27 of file Verifier_Simplexes.cpp.
const Type_info * Verifier_Simplexes::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 27 of file Verifier_Simplexes.cpp.
const Type_info * Verifier_Simplexes::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 27 of file Verifier_Simplexes.cpp.
Entree & Verifier_Simplexes::interpreter_ (Entree & is) [virtual]
Implements Interprete_geometrique_base.
Definition at line 301 of file Verifier_Simplexes.cpp.
References Interprete_geometrique_base::associer_domaine(), check_domain(), and Interprete_geometrique_base::domaine().
{
  associer_domaine(is);
  Domaine& domain = domaine();
  check_domain(domain);
  return is;
}
Sortie & Verifier_Simplexes::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 29 of file Verifier_Simplexes.cpp.
{
  Interprete_geometrique_base::printOn(os);
  return os;
}
Entree & Verifier_Simplexes::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 35 of file Verifier_Simplexes.cpp.
{
  Interprete_geometrique_base::readOn(is);
  return is;
}
Verifier_Simplexes & Verifier_Simplexes::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 27 of file Verifier_Simplexes.cpp.
const Verifier_Simplexes & Verifier_Simplexes::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 27 of file Verifier_Simplexes.cpp.
unsigned Verifier_Simplexes::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 27 of file Verifier_Simplexes.cpp.
Member Data Documentation
const Type_info Verifier_Simplexes::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 41 of file Verifier_Simplexes.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Verifier_Simplexes.h
src/Kernel/Geometrie/Verifier_Simplexes.cpp