TRUST: Dirichlet_homogene Class Reference
Dirichlet_homogene Class Reference
Classe Dirichlet_homogene
Cette classe est la classe de base de la hierarchie des conditions
aux limites de type Dirichlet homogene.
Une condition aux limites de type Dirichlet homogene impose une valeur
nulle au champ inconnue sur une frontiere, ce qui correspond a:
- vitesse imposee a zero pour l'equation de Navier-Stokes
- scalaire impose a zero pour l'equation de transport d'un scalaire.
#include <Dirichlet_homogene.h>
Public Member Functions
Dirichlet_homogene ()
~Dirichlet_homogene ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
double val_imp (int i) const
Renvoie la valeur imposee sur la i-eme composante
du champ a la frontiere.
Toujours 0 pour Dirichlet homogene.
double val_imp (int i, int j) const
Renvoie la valeur imposee sur la (i,j)-eme composante
du champ a la frontiere.
Toujours 0 pour Dirichlet homogene.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Dirichlet_homogene & self_cast (Objet_U &)
static const Dirichlet_homogene & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Type le champ a la frontiere en "Champ_front_uniforme"
Ne lit rien sur le flot passe en parametre.
Detailed Description
Classe Dirichlet_homogene
Cette classe est la classe de base de la hierarchie des conditions
aux limites de type Dirichlet homogene.
Une condition aux limites de type Dirichlet homogene impose une valeur
nulle au champ inconnue sur une frontiere, ce qui correspond a:
- vitesse imposee a zero pour l'equation de Navier-Stokes
- scalaire impose a zero pour l'equation de transport d'un scalaire.
Definition at line 43 of file Dirichlet_homogene.h.
Constructor & Destructor Documentation
Dirichlet_homogene::Dirichlet_homogene ()
Definition at line 25 of file Dirichlet_homogene.cpp.
Dirichlet_homogene::~Dirichlet_homogene ()
Definition at line 25 of file Dirichlet_homogene.cpp.
Member Function Documentation
virtual int Dirichlet_homogene::duplique () const [pure virtual]
Implements Cond_lim_base.
Implemented in Dirichlet_paroi_fixe_iso_Genepi2, and Dirichlet_paroi_fixe.
const Type_info * Dirichlet_homogene::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2, and Dirichlet_paroi_fixe.
Definition at line 25 of file Dirichlet_homogene.cpp.
const Type_info * Dirichlet_homogene::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2, and Dirichlet_paroi_fixe.
Definition at line 25 of file Dirichlet_homogene.cpp.
Sortie & Dirichlet_homogene::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2, and Dirichlet_paroi_fixe.
Definition at line 42 of file Dirichlet_homogene.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Dirichlet_homogene::readOn (Entree & s) [protected, virtual]
Type le champ a la frontiere en "Champ_front_uniforme"
Ne lit rien sur le flot passe en parametre.
Returns:
Entree& s
Signification: le flot d'entree
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2, and Dirichlet_paroi_fixe.
Definition at line 63 of file Dirichlet_homogene.cpp.
References Cond_lim_base::le_champ_front, and Deriv_::typer().
{
  le_champ_front.typer("Champ_front_uniforme");
  return s ;
}
const Dirichlet_homogene & Dirichlet_homogene::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Cond_lim_base.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2, and Dirichlet_paroi_fixe.
Definition at line 25 of file Dirichlet_homogene.cpp.
Dirichlet_homogene & Dirichlet_homogene::self_cast (Objet_U & r) [static]
Reimplemented from Cond_lim_base.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2, and Dirichlet_paroi_fixe.
Definition at line 25 of file Dirichlet_homogene.cpp.
double Dirichlet_homogene::val_imp (int i, int j) const [inline]
Renvoie la valeur imposee sur la (i,j)-eme composante
du champ a la frontiere.
Toujours 0 pour Dirichlet homogene.
Returns:
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes: toujours egal a 0
Definition at line 99 of file Dirichlet_homogene.h.
{
  return 0;
}
double Dirichlet_homogene::val_imp (int i) const [inline]
Renvoie la valeur imposee sur la i-eme composante
du champ a la frontiere.
Toujours 0 pour Dirichlet homogene.
Returns:
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes: toujours egal a 0
Definition at line 72 of file Dirichlet_homogene.h.
Referenced by Champ_base::calculer_valeurs_som_compo_post(), Op_VEF_Face::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), and Op_EF_base::modifier_pour_Cl().
{
  return 0;
}
Member Data Documentation
const Type_info Dirichlet_homogene::info_obj [static]
Reimplemented from Cond_lim_base.
Reimplemented in Dirichlet_paroi_fixe_iso_Genepi2, and Dirichlet_paroi_fixe.
Definition at line 46 of file Dirichlet_homogene.h.
The documentation for this class was generated from the following files:
src/Kernel/Cond_Lim/Dirichlet_homogene.h
src/Kernel/Cond_Lim/Dirichlet_homogene.cpp