TRUST: Conds_lim Class Reference
Conds_lim Class Reference
#include <Conds_lim.h>
Public Member Functions
Conds_lim ()
~Conds_lim ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps)
void mettre_a_jour (double temps)
Mise a jour en temps de toutes les conditions aux limites
du vecteur.
void calculer_coeffs_echange (double temps)
Calcul des coefficients d'echange pour toutes les conditions aux limites
du vecteur.
void completer (const Zone_dis &)
Appel Cond_lim::completer() sur chaque condition aux llimites
du vecteur.
int compatible_avec_eqn (const Equation_base &) const
Renvoie si TOUTES les conditions aux limites du vecteurs
sont compatibles avec l'equation passee en parametre.
int compatible_avec_discr (const Discretisation_base &) const
Renvoie si TOUTES les conditions aux limites du vecteurs
sont compatibles avec la discretisation passee en parametre.
void set_modifier_val_imp (int)
Positionnement du drapeau modifier_val_imp de toutes les conditions aux limites
du vecteur.
Public Member Functions inherited from Vect_Cond_lim
~Vect_Cond_lim ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Vect_Cond_lim ()
Vect_Cond_lim (int)
const Cond_lim & operator[] (int) const
const Cond_lim & operator() (int i) const
Cond_lim & operator[] (int)
Cond_lim & operator() (int i)
Vect_Cond_lim (const Vect_Cond_lim &)
Vect_Cond_lim & operator= (const Vect_Cond_lim &)
Cond_lim & add (const Cond_lim &titi)
Cond_lim & add ()
void add (const Vect_Cond_lim &)
Entree & lit (Entree &)
Public Member Functions inherited from vect_impl
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
vect_impl ()
int size () const
void build_vect_impl (int)
const Objet_U & operator[] (int) const
Objet_U & operator[] (int)
vect_impl (const vect_impl &)
~vect_impl () override
vect_impl & operator= (const vect_impl &)
void dimensionner (int)
void dimensionner_force (int)
void reset ()
vect_impl & add (const Objet_U &)
vect_impl & add (const vect_impl &)
Entree & lit (Entree &)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Conds_lim & self_cast (Objet_U &)
static const Conds_lim & self_cast (const Objet_U &)
Static Public Member Functions inherited from Vect_Cond_lim
static Objet_U * cree_instance ()
static const Type_info * info ()
static Vect_Cond_lim & self_cast (Objet_U &)
static const Vect_Cond_lim & self_cast (const Objet_U &)
Static Public Member Functions inherited from vect_impl
static Objet_U * cree_instance ()
static const Type_info * info ()
static vect_impl & self_cast (Objet_U &)
static const vect_impl & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Vect_Cond_lim
static const Type_info info_obj
Static Public Attributes inherited from vect_impl
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime seulement le nom du tableau des conditions aux limites.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Vect_Cond_lim
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Objet_U * cree_une_instance () const override
methhode surcharge par les classes filles pour fournir la bonne
instance aux constructeurs au readOn....
Protected Member Functions inherited from vect_impl
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual Objet_U * cree_une_instance () const
methhode surcharge par les classes filles pour fournir la bonne
instance aux constructeurs au readOn....
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from vect_impl
int sz
DerObjU * data
Detailed Description
Definition at line 38 of file Conds_lim.h.
Constructor & Destructor Documentation
Conds_lim()
Conds_lim::Conds_lim ()
Definition at line 24 of file Conds_lim.cpp.
~Conds_lim()
Conds_lim::~Conds_lim ()
Definition at line 24 of file Conds_lim.cpp.
Member Function Documentation
calculer_coeffs_echange()
void Conds_lim::calculer_coeffs_echange (double temps) inline
Calcul des coefficients d'echange pour toutes les conditions aux limites
du vecteur.
Definition at line 102 of file Conds_lim.h.
{
  for (int i=0; i<size(); i++)
    (*this)[i].calculer_coeffs_echange(temps);
}
References vect_impl::size().
Referenced by Zone_Cl_dis_base::calculer_coeffs_echange().
compatible_avec_discr()
int Conds_lim::compatible_avec_discr (const Discretisation_base & dis) const inline
Renvoie si TOUTES les conditions aux limites du vecteurs
sont compatibles avec la discretisation passee en parametre.
Returns
int
Signification: 1 si toutes les conditions aux limites sont compatibles
avec la discretisation, 0 sinon.
Contraintes:
Definition at line 151 of file Conds_lim.h.
{
  int ok=1;
  for (int i=0; i<size(); i++)
    ok*=(*this)[i].compatible_avec_discr(dis);
  return ok;
}
References vect_impl::size().
Referenced by Equation_base::verif_Cl().
compatible_avec_eqn()
int Conds_lim::compatible_avec_eqn (const Equation_base & eqn) const inline
Renvoie si TOUTES les conditions aux limites du vecteurs
sont compatibles avec l'equation passee en parametre.
Returns
int
Signification: 1 si toutes les conditions aux limites sont compatibles
avec l'equation, 0 sinon.
Contraintes:
Definition at line 126 of file Conds_lim.h.
{
  int ok=1;
  for (int i=0; i<size(); i++)
    ok*=(*this)[i].compatible_avec_eqn(eqn);
  return ok;
}
References vect_impl::size().
Referenced by Equation_base::verif_Cl().
completer()
void Conds_lim::completer (const Zone_dis & z)
Appel Cond_lim::completer() sur chaque condition aux llimites
du vecteur.
Definition at line 83 of file Conds_lim.cpp.
{
  if (!size()) return; //rien a faire
// Completer les CL.
  for (int i=0; i<size(); i++)
    (*this)[i].completer();
// WEC : Fixer le nombre de valeurs temporelles des champ_front
// Cela pourrait etre fait dans Cond_lim_base::completer(),
// mais il faudrait retoucher a plein de classes derivees...
  int nb_cases = (*this)[0]->zone_Cl_dis().equation().schema_temps().nb_valeurs_temporelles();
  for (int i=0; i<size(); i++)
    (*this)[i]->fixer_nb_valeurs_temporelles(nb_cases);
  Domaine& dom=(*this)[0].frontiere_dis().frontiere().zone().domaine();
  dom.construire_renum_som_perio(*this, z);
}
References Domaine::construire_renum_som_perio(), Zone::domaine(), vect_impl::size(), and Domaine::zone().
Referenced by Zone_Cl_dis_base::completer().
cree_instance()
Objet_U * Conds_lim::cree_instance () static
Definition at line 24 of file Conds_lim.cpp.
duplique()
int Conds_lim::duplique () const override virtual
Reimplemented from Vect_Cond_lim.
Definition at line 24 of file Conds_lim.cpp.
get_info()
const Type_info * Conds_lim::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Vect_Cond_lim.
Definition at line 24 of file Conds_lim.cpp.
info()
const Type_info * Conds_lim::info () static
Definition at line 24 of file Conds_lim.cpp.
initialiser()
int Conds_lim::initialiser (double temps) inline
Definition at line 57 of file Conds_lim.h.
{
  int ok=1;
  for (int i=0; i<size(); i++)
    ok = ok && (*this)[i]->initialiser(temps);
  return ok;
}
References vect_impl::size().
Referenced by Zone_Cl_dis_base::initialiser().
mettre_a_jour()
void Conds_lim::mettre_a_jour (double temps) inline
Mise a jour en temps de toutes les conditions aux limites
du vecteur.
Definition at line 80 of file Conds_lim.h.
{
  for (int i=0; i<size(); i++)
    (*this)[i].mettre_a_jour(temps);
}
References vect_impl::size().
Referenced by grad_Champ_Face_PolyMAC_P0::me_calculer(), and Zone_Cl_dis_base::mettre_a_jour().
printOn()
Sortie & Conds_lim::printOn (Sortie & s) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime seulement le nom du tableau des conditions aux limites.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Vect_Cond_lim.
Definition at line 42 of file Conds_lim.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Conds_lim::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Vect_Cond_lim.
Definition at line 62 of file Conds_lim.cpp.
{
  return s ;
}
self_cast() [1/2]
const Conds_lim & Conds_lim::self_cast (const Objet_U & r) static
Definition at line 24 of file Conds_lim.cpp.
self_cast() [2/2]
Conds_lim & Conds_lim::self_cast (Objet_U & r) static
Definition at line 24 of file Conds_lim.cpp.
set_modifier_val_imp()
void Conds_lim::set_modifier_val_imp (int drap) inline
Positionnement du drapeau modifier_val_imp de toutes les conditions aux limites
du vecteur.
Definition at line 174 of file Conds_lim.h.
{
  for (int i=0; i<size(); i++)
    (*this)[i].set_modifier_val_imp(drap);
}
References vect_impl::size().
taille_memoire()
unsigned Conds_lim::taille_memoire () const override virtual
Reimplemented from Vect_Cond_lim.
Definition at line 24 of file Conds_lim.cpp.
Member Data Documentation
info_obj
const Type_info Conds_lim::info_obj static
Definition at line 41 of file Conds_lim.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Conds_lim.h
src/Kernel/Framework/Conds_lim.cpp