TRUST: Deriv_Zone_dis_base Class Reference
Deriv_Zone_dis_base Class Reference
#include <Zone_dis.h>
Public Member Functions
~Deriv_Zone_dis_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Zone_dis_base ()
Deriv_Zone_dis_base (const Deriv_Zone_dis_base &)
const Zone_dis_base & valeur () const
Zone_dis_base & valeur ()
const Zone_dis_base * operator-> () const
Zone_dis_base * operator-> ()
const Deriv_Zone_dis_base & operator= (const Zone_dis_base &)
const Deriv_Zone_dis_base & operator= (const Deriv_Zone_dis_base &)
operator const Zone_dis_base & () const
operator Zone_dis_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Zone_dis_base & self_cast (Objet_U &)
static const Deriv_Zone_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Zone_dis_base * pointeur_
Detailed Description
Definition at line 22 of file Zone_dis.h.
Constructor & Destructor Documentation
~Deriv_Zone_dis_base()
Deriv_Zone_dis_base::~Deriv_Zone_dis_base ()
Definition at line 18 of file Zone_dis.cpp.
Deriv_Zone_dis_base() [1/2]
Deriv_Zone_dis_base::Deriv_Zone_dis_base ()
Definition at line 18 of file Zone_dis.cpp.
Deriv_Zone_dis_base() [2/2]
Deriv_Zone_dis_base::Deriv_Zone_dis_base (const Deriv_Zone_dis_base & t)
Definition at line 18 of file Zone_dis.cpp.
Member Function Documentation
cree_instance()
Objet_U * Deriv_Zone_dis_base::cree_instance () static
Definition at line 18 of file Zone_dis.cpp.
duplique()
int Deriv_Zone_dis_base::duplique () const override virtual
Implements Objet_U.
Reimplemented in Zone_dis.
Definition at line 18 of file Zone_dis.cpp.
get_info()
const Type_info * Deriv_Zone_dis_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Zone_dis.
Definition at line 18 of file Zone_dis.cpp.
get_info_ptr()
const Type_info & Deriv_Zone_dis_base::get_info_ptr () const override virtual
Implements O_U_Ptr.
Definition at line 18 of file Zone_dis.cpp.
info()
const Type_info * Deriv_Zone_dis_base::info () static
Definition at line 18 of file Zone_dis.cpp.
operator const Zone_dis_base &()
Deriv_Zone_dis_base::operator const Zone_dis_base & () const
Definition at line 18 of file Zone_dis.cpp.
operator Zone_dis_base &()
Deriv_Zone_dis_base::operator Zone_dis_base & ()
Definition at line 18 of file Zone_dis.cpp.
operator->() [1/2]
Zone_dis_base * Deriv_Zone_dis_base::operator-> () inline
Definition at line 22 of file Zone_dis.h.
: public DERIV(Zone_dis_base)
operator->() [2/2]
const Zone_dis_base * Deriv_Zone_dis_base::operator-> () const inline
Definition at line 22 of file Zone_dis.h.
: public DERIV(Zone_dis_base)
operator=() [1/2]
const Deriv_Zone_dis_base & Deriv_Zone_dis_base::operator= (const Deriv_Zone_dis_base & t)
Definition at line 18 of file Zone_dis.cpp.
operator=() [2/2]
const Deriv_Zone_dis_base & Deriv_Zone_dis_base::operator= (const Zone_dis_base & t)
Definition at line 18 of file Zone_dis.cpp.
printOn()
Sortie & Deriv_Zone_dis_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Zone_dis.
Definition at line 18 of file Zone_dis.cpp.
readOn()
Entree & Deriv_Zone_dis_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Zone_dis.
Definition at line 18 of file Zone_dis.cpp.
self_cast() [1/2]
const Deriv_Zone_dis_base & Deriv_Zone_dis_base::self_cast (const Objet_U & r) static
Definition at line 18 of file Zone_dis.cpp.
self_cast() [2/2]
Deriv_Zone_dis_base & Deriv_Zone_dis_base::self_cast (Objet_U & r) static
Definition at line 18 of file Zone_dis.cpp.
set_O_U_Ptr()
void Deriv_Zone_dis_base::set_O_U_Ptr (Objet_U * ptr) override protected virtual
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 18 of file Zone_dis.cpp.
taille_memoire()
unsigned Deriv_Zone_dis_base::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Zone_dis.
Definition at line 18 of file Zone_dis.cpp.
valeur() [1/2]
Zone_dis_base & Deriv_Zone_dis_base::valeur () inline
Definition at line 22 of file Zone_dis.h.
: public DERIV(Zone_dis_base)
valeur() [2/2]
const Zone_dis_base & Deriv_Zone_dis_base::valeur () const inline
Definition at line 22 of file Zone_dis.h.
: public DERIV(Zone_dis_base)
Referenced by Simpler_Base::assembler_matrice_pression_implicite(), Op_Conv_EF_base::associer(), Op_Diff_EF_base::associer(), Op_Div_EF::associer(), Op_Grad_EF::associer(), Op_Curl_VEFP1B::associer(), Op_Diff_P1NC_barprim::associer(), Op_Diff_RotRot::associer(), Op_Diff_VEFP1NCP1B_Face::associer(), Op_Dift_VEF_P1NCP1B_Face::associer(), Op_Rot_VEFP1B::associer(), Op_Conv_PolyMAC_base::associer(), Op_Diff_PolyMAC_base::associer(), Op_Diff_PolyMAC_P0_base::associer(), Op_Div_PolyMAC::associer(), Op_Div_PolyMAC_P0::associer(), Op_Grad_PolyMAC_Face::associer(), Op_Grad_PolyMAC_P0_Face::associer(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Op_Div_VDF_Elem::associer(), Op_Grad_VDF_Face_base::associer(), Op_Conv_Centre_old_VEF_Face::associer(), Op_Conv_VEF_base::associer(), Op_Diff_VEF_base::associer(), Op_Dift_VEF_base::associer(), Op_Div_VEF_Elem::associer(), Op_Grad_P1NC_to_P0::associer(), Op_Grad_VEF_Face::associer(), Iterateur_VDF_base::associer(), Op_Conv_VDF< OP_TYPE >::associer_(), Op_Diff_Dift_VDF< OP_TYPE >::associer_(), Zone_dis::associer_domaine_dis(), Source_Fluide_Dilatable_VDF_Proto::associer_volume_porosite_impl(), Source_Fluide_Dilatable_VEF_Proto::associer_volume_porosite_impl(), Zone_dis::associer_zone(), Puissance_Thermique_EF::associer_zones(), Source_PDF_EF::associer_zones(), Source_Qdm_EF::associer_zones(), Source_Scalaire_EF::associer_zones(), Source_Generique_P0_Elem::associer_zones(), Source_Generique_Face_PolyMAC::associer_zones(), Terme_Boussinesq_PolyMAC_Face::associer_zones(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::associer_zones(), Terme_Puissance_Thermique_PolyMAC_base::associer_zones(), Terme_Puissance_Thermique_PolyMAC_Elem::associer_zones(), Terme_Source_Constituant_PolyMAC_Elem::associer_zones(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::associer_zones(), EOS_Tools_VDF::associer_zones(), EOS_Tools_VEF::associer_zones(), Puissance_Thermique_QC_EF::associer_zones(), EDO_Pression_th_VDF::associer_zones(), Terme_Puissance_Thermique_QC_VDF_Elem::associer_zones(), EDO_Pression_th_VEF::associer_zones(), Terme_Puissance_Thermique_QC_VEF_Face::associer_zones(), Force_Centrifuge_VDF_Face_Axi::associer_zones(), Perte_Charge_VDF_Face::associer_zones(), Source_Generique_VDF_Face::associer_zones(), Source_Darcy_VDF_Face::associer_zones(), Source_Dirac_VDF_Elem::associer_zones(), Source_Echange_Th_VDF::associer_zones(), Source_Forchheimer_VDF_Face::associer_zones(), Source_Neutronique_VDF::associer_zones(), Terme_Gravite_VDF_Face::associer_zones(), Terme_Puissance_Thermique_VDF_base::associer_zones(), Terme_Puissance_Thermique_VDF_Elem::associer_zones(), Terme_Source_Constituant_VDF_Elem::associer_zones(), Terme_Boussinesq_VDF_Face::associer_zones(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::associer_zones(), Terme_Source_Acceleration_VDF_Face::associer_zones(), Terme_Source_Canal_perio_VDF_Face::associer_zones(), Terme_Source_Canal_RANS_LES_VDF_Elem::associer_zones(), Terme_Source_Canal_RANS_LES_VDF_Face::associer_zones(), Terme_Source_Coriolis_VDF_Face::associer_zones(), Terme_Source_inc_th_VDF_Face::associer_zones(), Terme_Source_inc_VDF_Face::associer_zones(), Terme_Source_Qdm_VDF_Face::associer_zones(), Perte_Charge_VEF::associer_zones(), Perte_Charge_VEF_Face::associer_zones(), Source_Darcy_VEF_Face::associer_zones(), Source_Dirac_VEF_Face::associer_zones(), Source_Forchheimer_VEF_Face::associer_zones(), Source_Generique_VEF::associer_zones(), Terme_Boussinesq_VEF_Face::associer_zones(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::associer_zones(), Terme_Puissance_Thermique_VEF_base::associer_zones(), Terme_Puissance_Thermique_VEF_Face::associer_zones(), Terme_Source_Acceleration_VEF_Face::associer_zones(), Terme_Source_Canal_perio_VEF_P1NC::associer_zones(), Terme_Source_Canal_RANS_LES_VEF_Face::associer_zones(), Terme_Source_Constituant_VEF_Face::associer_zones(), Terme_Source_Decroissance_Radioactive_VEF_Face::associer_zones(), Terme_Source_Qdm_lambdaup_VEF_Face::associer_zones(), Terme_Source_Qdm_VEF_Face::associer_zones(), Terme_Source_Rappel_T_VEF_Face::associer_zones(), Source_Fluide_Dilatable_VDF_Proto::associer_zones_impl(), Source_Fluide_Dilatable_VEF_Proto::associer_zones_impl(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Champ_front_contact_VEF::calcul_coeff_amort(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Perte_Charge_Singuliere::calculate_Q(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Echange_contact_VDF::calculer_h_autre_pb(), Operateur_base::calculer_pour_post(), Periodique::completer(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Navier_Stokes_std::completer(), Terme_Source_Canal_perio::completer(), Sortie_libre_Gradient_Pression_impose::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Terme_Source_Rappel_T_VEF_Face::completer(), Champ_Post_Operateur_Eqn::completer(), Op_Ecart_type::completer(), Op_Moyenne::completer(), Zone_Cl_EF::completer(), Zone_Cl_PolyMAC::completer(), Zone_Cl_VDF::completer(), Zone_Cl_VEF::completer(), Terme_Source_Canal_perio::compute_heat_flux(), Discret_Thyd::concentration(), VDF_discretisation::courant_maille(), Zone_dis::creer_elements_fictifs(), VDF_discretisation::critere_Q(), EF_discretisation::critere_Q(), PolyMAC_discretisation::critere_Q(), VEF_discretisation::critere_Q(), Discret_Thyd::diametre_hydraulique_elem(), Discret_Thyd::diametre_hydraulique_face(), Zone_dis::discretiser(), Mod_turb_hyd_base::discretiser(), Modele_turbulence_scal_base::discretiser(), Aire_interfaciale::discretiser(), Loi_Fermeture_Test::discretiser(), Domaine_dis::discretiser(), VEFPreP1B::discretiser(), Mod_turb_hyd_base::discretiser_corr_visc_turb(), Mod_turb_hyd_base::discretiser_K(), Reaction::discretiser_omega(), Mod_turb_hyd_base::discretiser_visc_turb(), EF_discretisation::distance_paroi(), VEF_discretisation::distance_paroi(), PolyMAC_discretisation::distance_paroi_globale(), Discret_Thyd::divergence_U(), Discret_Thyd::entcor(), Discret_Thermique::Fluctu_Temperature(), Discret_Thermique::Flux_Chaleur_Turb(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Discret_Thermique::flux_neutronique(), Zone_dis::frontiere_dis(), Champ_Generique_Tparoi_VEF::get_champ(), Turbulence_paroi_base::get_champ(), Champ_Post_Operateur_Eqn::get_champ_compo_without_evaluation(), Operateur_base::get_localisation_pour_post(), Champ_Generique_base::get_ref_zone_dis_base(), Champ_Generique_Extraction::get_ref_zone_dis_base(), Champ_Generique_Interpolation::get_ref_zone_dis_base(), EF_discretisation::grad_T(), PolyMAC_discretisation::grad_T(), VEF_discretisation::grad_T(), VDF_discretisation::grad_u(), VEF_discretisation::grad_u(), PolyMAC_P0_discretisation::grad_u(), Discret_Thyd::gradient_P(), EF_discretisation::h_conv(), PolyMAC_discretisation::h_conv(), VEF_discretisation::h_conv(), Op_EF_base::impr(), Op_VEF_Face::impr(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), Echange_contact_VDF::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Champ_front_recyclage::initialiser(), Terme_Puissance_Thermique::initialiser_champ_puissance(), Diametre_hyd_champ::interpreter(), Porosites::interpreter(), Porosites_champ::interpreter(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), SETS::iterer_NS(), Postraitement_lata::lire_champs(), Terme_Source_Acceleration::lire_data(), Terme_Puissance_Thermique::lire_donnees(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), modif_matrice_pour_periodique_apres_contribuer(), modif_matrice_pour_periodique_avant_contribuer(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Discret_Thyd::porosite_volumique(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson(), Postraitement_lata::postraiter(), Postraitement_lata::postraiter_liste_champs(), Discret_Thyd::pression(), Discret_Thyd::pression_en_pa(), EF_discretisation::proprietes_physiques_fluide_Ostwald(), PolyMAC_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), VEF_discretisation::proprietes_physiques_fluide_Ostwald(), Debog_Pb::read_geometry_data(), Diametre_bulles_champ::readOn(), Diametre_bulles_constant::readOn(), Champ_Don_Face_lu::readOn(), Champ_front_contact_VEF::remplir_connect_bords(), VDF_discretisation::residu(), VEF_discretisation::residu(), PolyMAC_discretisation::residu(), VDF_discretisation::reynolds_maille(), Discret_Thyd::section_passage(), VDF_discretisation::taux_cisaillement(), VEF_discretisation::taux_cisaillement(), Discret_Thermique::temperature(), Discret_Thyd::translation(), Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries(), Champ_Post_Operateur_Eqn::verification_cas_compo(), VEF_1D::vitesse(), Discret_Thyd::vitesse(), Discretisation_base::volume_maille(), EF_discretisation::vorticite(), PolyMAC_discretisation::vorticite(), VDF_discretisation::vorticite(), VEF_discretisation::vorticite(), Debog_Pb::write_geometry_data(), VDF_discretisation::y_plus(), EF_discretisation::y_plus(), PolyMAC_discretisation::y_plus(), VEF_discretisation::y_plus(), Zone_dis::zone(), EF_discretisation::zone_Cl_dis(), VEFPreP1B::zone_Cl_dis(), PolyMAC_discretisation::zone_Cl_dis(), VDF_discretisation::zone_Cl_dis(), and VEF_discretisation::zone_Cl_dis().
Member Data Documentation
info_obj
const Type_info Deriv_Zone_dis_base::info_obj static
Definition at line 22 of file Zone_dis.h.
pointeur_
Zone_dis_base* Deriv_Zone_dis_base::pointeur_ private
Definition at line 22 of file Zone_dis.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Zone_dis.h
src/Kernel/Framework/Zone_dis.cpp