TRUST: NettoieNoeuds Class Reference
NettoieNoeuds Class Reference
#include <NettoieNoeuds.h>
Public Member Functions
NettoieNoeuds ()
~NettoieNoeuds ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static NettoieNoeuds & self_cast (Objet_U &)
static const NettoieNoeuds & self_cast (const Objet_U &)
static void nettoie (Domaine &)
static void verifie_noeuds (const Domaine &)
regarde si on n'a pas des noeuds doubles
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
static int NettoiePasNoeuds =0
Fonction principale de l'interprete NettoieNoeuds
Structure du jeu de donnee (en dimension 2) :
NettoieNoeuds dom alpha.
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Definition at line 34 of file NettoieNoeuds.h.
Constructor & Destructor Documentation
NettoieNoeuds()
NettoieNoeuds::NettoieNoeuds ()
Definition at line 20 of file NettoieNoeuds.cpp.
~NettoieNoeuds()
NettoieNoeuds::~NettoieNoeuds ()
Definition at line 20 of file NettoieNoeuds.cpp.
Member Function Documentation
cree_instance()
Objet_U * NettoieNoeuds::cree_instance () static
Definition at line 20 of file NettoieNoeuds.cpp.
duplique()
int NettoieNoeuds::duplique () const override virtual
Implements Objet_U.
Definition at line 20 of file NettoieNoeuds.cpp.
get_info()
const Type_info * NettoieNoeuds::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 20 of file NettoieNoeuds.cpp.
info()
const Type_info * NettoieNoeuds::info () static
Definition at line 20 of file NettoieNoeuds.cpp.
interpreter_()
Entree & NettoieNoeuds::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base.
Definition at line 78 of file NettoieNoeuds.cpp.
{
  associer_domaine(is);
  if (domaine().les_sommets().size()!=0)
    {
      Cerr << "The keyword NettoiePasNoeuds must be placed before the ";
      Cerr << "reading of the domain to avoid the cleaning of the double";
      Cerr << "nodes of the domain." << finl;
      exit();
    }
  NettoiePasNoeuds=1;
  Cerr << "NettoiePasNoeuds=" << NettoiePasNoeuds << " for the domain " << domaine().le_nom() << finl;
  return is;
}
References Interprete_geometrique_base::associer_domaine(), Cerr, Interprete_geometrique_base::domaine(), Process::exit(), finl, Domaine::le_nom(), and NettoiePasNoeuds.
nettoie()
void NettoieNoeuds::nettoie (Domaine & dom) static
Definition at line 96 of file NettoieNoeuds.cpp.
{
  if (NettoiePasNoeuds==1)
    return;
// Autorise la modification de structure des tableaux sommets et elements:
  Scatter::uninit_sequential_domain(dom);
  DoubleTab& coord_sommets=dom.les_sommets();
  Zone& zone=dom.zone(0);
  IntTab& les_elems=zone.les_elems();
  int nb_som_init=coord_sommets.dimension(0);
  int nb_elem=les_elems.dimension(0);
  int nb_som_elem=les_elems.dimension(1);
  ArrOfInt renum_som_old2new(nb_som_init);
  int compteur=0;
  {
// int i;
    for (int i=0; i<nb_som_init ; i++)
      renum_som_old2new[i]=-1;
    for (int i=0; i<nb_elem ; i++)
      for (int j=0; j< nb_som_elem; j++)
        {
// GF dans le cas ou on a des polyedres
          if (les_elems(i,j)==-1) break;
          int& tmp=renum_som_old2new[les_elems(i,j)];
          assert (tmp < compteur);
          if(tmp==-1)
            tmp=compteur++;
        }
// ajout GF sinon un sommet double sur un bord devient -1
    int nb_bords=zone.nb_front_Cl();
    for (int ii=0; ii<nb_bords; ii++)
      {
        const Frontiere& front= zone.frontiere(ii);
        const Faces& faces=front.faces();
        const IntTab& faces_sommets=faces.les_sommets();
        int nb_faces=faces_sommets.dimension(0);
        int nb_som_face=faces_sommets.dimension(1);
        for(int i=0; i<nb_faces; i++)
          for(int j=0; j<nb_som_face; j++)
            {
// dans le cas ou l'on a des polygones
              if (faces_sommets(i,j)==-1) break;
              int& tmp=renum_som_old2new[faces_sommets(i,j)];
              assert (tmp < compteur);
              if(tmp==-1)
                tmp=compteur++;
            }
      }
  }
  int nb_som_new=compteur;
  Cerr << "Elimination of " << nb_som_init - nb_som_new << " unnecessary nodes in the domain " << dom.le_nom() << finl;
  if(nb_som_new!=nb_som_init)
    {
      ArrOfInt renum_som_new2old(nb_som_new);
      {
        int j;
        for (int i=0; i<nb_som_init ; i++)
          if((j=renum_som_old2new[i])!=-1)
            renum_som_new2old[j]=i;
      }
      {
        int i, j;
        DoubleTab new_coord(nb_som_new, dimension);
        for (i=0; i<nb_som_new ; i++)
          for (j=0; j<dimension ; j++)
            {
              new_coord(i,j)=coord_sommets(renum_som_new2old[i],j);
            }
        coord_sommets=new_coord;
        for (i=0; i<nb_elem ; i++)
          for (j=0; j<nb_som_elem ; j++)
            {
              int num_som=les_elems(i,j);
              if (num_som!=-1)
                les_elems(i,j)=renum_som_old2new[num_som];
              else
                les_elems(i,j)=-1;
            }
      }
      {
// On recupere les bords :
        LIST_CURSEUR(Bord) curseur(zone.faces_bord());;;
        while(curseur)
          {
// while(curseur)
            Frontiere& front=curseur.valeur();
            Faces& faces=front.faces();
            IntTab& faces_sommets=faces.les_sommets();
            IntTab old_faces_sommets(faces.les_sommets());
            int nb_faces=faces_sommets.dimension(0);
            int nb_som_face=faces_sommets.dimension(1);
            for(int i=0; i<nb_faces; i++)
              for(int j=0; j<nb_som_face; j++)
                {
                  int som=old_faces_sommets(i,j);
                  if (som!=-1)
                    faces_sommets(i,j)=
                      renum_som_old2new[som];
                  else
                    faces_sommets(i,j)=som;
                }
            ++curseur;
          }
      }
      {
// Les Faces Internes :
        LIST_CURSEUR(Faces_Interne) curseur(zone.faces_int());;;
        while(curseur)
          {
// while(curseur)
            Frontiere& front=curseur.valeur();
            Faces& faces=front.faces();
            IntTab& faces_sommets=faces.les_sommets();
            IntTab old_faces_sommets(faces.les_sommets());
            int nb_faces=faces_sommets.dimension(0);
            int nb_som_face=faces_sommets.dimension(1);
            for(int i=0; i<nb_faces; i++)
              for(int j=0; j<nb_som_face; j++)
                faces_sommets(i,j)=
                  renum_som_old2new[old_faces_sommets(i,j)];
            ++curseur;
          }
      }
      {
// Les Raccords
        LIST_CURSEUR(Raccord) curseur(zone.faces_raccord());;;
        while(curseur)
          {
            Frontiere& front=curseur->valeur();
            Faces& faces=front.faces();
            IntTab& faces_sommets=faces.les_sommets();
            IntTab old_faces_sommets(faces.les_sommets());
            int nb_faces=faces_sommets.dimension(0);
            int nb_som_face=faces_sommets.dimension(1);
            for(int i=0; i<nb_faces; i++)
              for(int j=0; j<nb_som_face; j++)
                faces_sommets(i,j)=
                  renum_som_old2new[old_faces_sommets(i,j)];
            ++curseur;
          }
      }
    }
  Scatter::init_sequential_domain(dom);
}
References Cerr, compteur, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Frontiere::faces(), Zone::faces_bord(), Zone::faces_int(), Zone::faces_raccord(), finl, Zone::frontiere(), Scatter::init_sequential_domain(), Domaine::le_nom(), Zone::les_elems(), Domaine::les_sommets(), Faces::les_sommets(), LIST_CURSEUR, Zone::nb_front_Cl(), NettoiePasNoeuds, Scatter::uninit_sequential_domain(), and Domaine::zone().
Referenced by Champ_Generique_Extraction::completer(), Extraire_surface::extraire_surface(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Lire_Tgrid::interpreter_(), Mailler::interpreter_(), Remove_elem::interpreter_(), and Domaine::readOn().
printOn()
Sortie & NettoieNoeuds::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 36 of file NettoieNoeuds.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & NettoieNoeuds::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 56 of file NettoieNoeuds.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const NettoieNoeuds & NettoieNoeuds::self_cast (const Objet_U & r) static
Definition at line 20 of file NettoieNoeuds.cpp.
self_cast() [2/2]
NettoieNoeuds & NettoieNoeuds::self_cast (Objet_U & r) static
Definition at line 20 of file NettoieNoeuds.cpp.
taille_memoire()
unsigned NettoieNoeuds::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 20 of file NettoieNoeuds.cpp.
verifie_noeuds()
void NettoieNoeuds::verifie_noeuds (const Domaine & dom) static
regarde si on n'a pas des noeuds doubles
Definition at line 251 of file NettoieNoeuds.cpp.
{
  Cerr<<finl<<"Beginning of the search of identical nodes (can be long, algorithm in n^2)..."<<finl;
  const DoubleTab& coord_sommets=dom.les_sommets();
  int ns=coord_sommets.dimension(0);
// int nbsomelem=coord_sommets.dimension(1);
// const IntTab& les_elems= dom.zone(0).les_elems();
  int err=0;
  /*  for (int sommet=0;sommet<ns;sommet++)
      {
      double x,y,z=0;
      x=coord_sommets(sommet,0);
      y=coord_sommets(sommet,1);
      if (dimension>2)
      z=coord_sommets(sommet,0);
      int elem2=dom.zone(0).chercher_elements(x,y,z);
      if (elem2==-1)
      {
      Cerr<<"unable to find node "<<finl;
      exit();
      }
      int som;
      for ( som=0;som<nbsomelem;som++)
      {
      int sommet2=les_elems(elem2,som);
      int ok=1;
      for (int dir=0;dir<Objet_U::dimension;dir++)
      ok=ok&&(est_egal(coord_sommets(sommet,dir),coord_sommets(sommet2,dir)));
      if (ok)
      {
      if (sommet!=sommet2)
      {
      Cerr<<" the nodes "<<sommet<<" and "<<sommet2<<" seem the same"<<finl;
      err=1;
      }
      }
      }
      }
// la version avec chercher element plus rapide a priori
// n log(n) a des chances de rater des sommets doubles
// on revien ta un algo en n*n/2
  */
  int tmp,pourcent=0;
  for (int sommet=0; sommet<ns; sommet++)
    {
      tmp =(sommet*100)/ns;
      if(tmp>=pourcent)
        {
          pourcent = tmp;
          Cerr << pourcent << "% of nodes have been verified\r " << flush;
        }
      for ( int sommet2=sommet+1; sommet2<ns; sommet2++)
        {
          int ok=1;
          for (int dir=0; dir<Objet_U::dimension; dir++)
            ok=ok&&(est_egal(coord_sommets(sommet,dir),coord_sommets(sommet2,dir)));
          if (ok)
            {
              if (sommet!=sommet2)
                {
                  Cerr<< finl << "The nodes "<<sommet<<" and "<<sommet2<<" are the same !"<<finl;
                  err=1;
                }
            }
        }
    }
  Cerr<<"End of the search of identical nodes."<<finl;
  if (err)
    exit();
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, est_egal(), Process::exit(), finl, and Domaine::les_sommets().
Referenced by Faces_builder::check_erreur_faces().
Member Data Documentation
info_obj
const Type_info NettoieNoeuds::info_obj static
Definition at line 36 of file NettoieNoeuds.h.
NettoiePasNoeuds
int NettoieNoeuds::NettoiePasNoeuds =0 static
Fonction principale de l'interprete NettoieNoeuds
Structure du jeu de donnee (en dimension 2) :
NettoieNoeuds dom alpha.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Definition at line 41 of file NettoieNoeuds.h.
Referenced by Lire_Tgrid::interpreter_(), interpreter_(), nettoie(), and Domaine::readOn().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/NettoieNoeuds.h
src/Kernel/Geometrie/NettoieNoeuds.cpp