TRUST: Interpolation_IBM_mean_gradient Class Reference
Interpolation_IBM_mean_gradient Class Reference
: class Interpolation_IBM_mean_gradient
<Description of class Interpolation_IBM_mean_gradient>
#include <Interpolation_IBM_mean_gradient.h>
Public Member Functions
Interpolation_IBM_mean_gradient ()
~Interpolation_IBM_mean_gradient ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretise (const Discretisation_base &, Zone_dis_base &la_zone_EF) override
IntList & getSommetsVoisinsOf (int i)
Public Member Functions inherited from Interpolation_IBM_base
Interpolation_IBM_base ()
~Interpolation_IBM_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void discretise (const Discretisation_base &, Zone_dis_base &)
double get_impr ()
void set_param (Param &)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Interpolation_IBM_mean_gradient_proto
IntList & getSommetsVoisinsOf (int i)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interpolation_IBM_mean_gradient & self_cast (Objet_U &)
static const Interpolation_IBM_mean_gradient & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interpolation_IBM_base
static const Type_info * info ()
static Interpolation_IBM_base & self_cast (Objet_U &)
static const Interpolation_IBM_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interpolation_IBM_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Interpolation_IBM_mean_gradient_proto
void computeSommetsVoisins (Zone_dis_base &la_zone_EF, const Champ_Don &solid_points, const Champ_Don &corresp_elems)
Friends
class Source_PDF_EF
Additional Inherited Members
Protected Attributes inherited from Interpolation_IBM_base
Champ_Don solid_points_lu_
Champ_Don solid_points_
Champ_Don corresp_elems_lu_
Champ_Don corresp_elems_
int impr_ =0
Default value.
Protected Attributes inherited from Interpolation_IBM_mean_gradient_proto
Champ_Don is_dirichlet_lu_
Champ_Don is_dirichlet_
Champ_Don solid_elems_lu_
Champ_Don solid_elems_
IntLists sommets_voisins_
Detailed Description
: class Interpolation_IBM_mean_gradient
<Description of class Interpolation_IBM_mean_gradient>
Definition at line 31 of file Interpolation_IBM_mean_gradient.h.
Constructor & Destructor Documentation
Interpolation_IBM_mean_gradient()
Interpolation_IBM_mean_gradient::Interpolation_IBM_mean_gradient ()
Definition at line 22 of file Interpolation_IBM_mean_gradient.cpp.
~Interpolation_IBM_mean_gradient()
Interpolation_IBM_mean_gradient::~Interpolation_IBM_mean_gradient ()
Definition at line 22 of file Interpolation_IBM_mean_gradient.cpp.
Member Function Documentation
cree_instance()
Objet_U * Interpolation_IBM_mean_gradient::cree_instance () static
Definition at line 22 of file Interpolation_IBM_mean_gradient.cpp.
discretise()
void Interpolation_IBM_mean_gradient::discretise (const Discretisation_base & dis, Zone_dis_base & la_zone_EF) override virtual
Reimplemented from Interpolation_IBM_base.
Definition at line 42 of file Interpolation_IBM_mean_gradient.cpp.
{
  int nb_comp = Objet_U::dimension;
  Noms units(nb_comp);
  Noms c_nam(nb_comp);
  if ((&corresp_elems_lu_)->non_nul())
    {
      dis.discretiser_champ("champ_elem",la_zone_EF,"corresp_elems","none",1,0., corresp_elems_);
      corresp_elems_.valeur().affecter(corresp_elems_lu_);
    }
  dis.discretiser_champ("champ_sommets",la_zone_EF,"solid_elems","none",1,0., solid_elems_);
  solid_elems_.valeur().affecter(solid_elems_lu_);
  dis.discretiser_champ("champ_sommets",la_zone_EF,"is_dirichlet","none",1,0., is_dirichlet_);
  is_dirichlet_.valeur().affecter(is_dirichlet_lu_);
  dis.discretiser_champ("vitesse",la_zone_EF,vectoriel,c_nam,units,nb_comp,0., solid_points_);
  solid_points_.valeur().affecter(solid_points_lu_);
  computeSommetsVoisins(la_zone_EF, solid_points_, corresp_elems_);
}
References Champ_base::affecter(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Interpolation_IBM_base::corresp_elems_, Interpolation_IBM_base::corresp_elems_lu_, Objet_U::dimension, Discretisation_base::discretiser_champ(), Interpolation_IBM_mean_gradient_proto::is_dirichlet_, Interpolation_IBM_mean_gradient_proto::is_dirichlet_lu_, Interpolation_IBM_mean_gradient_proto::solid_elems_, Interpolation_IBM_mean_gradient_proto::solid_elems_lu_, Interpolation_IBM_base::solid_points_, Interpolation_IBM_base::solid_points_lu_, Deriv_Champ_Don_base::valeur(), and vectoriel.
duplique()
int Interpolation_IBM_mean_gradient::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file Interpolation_IBM_mean_gradient.cpp.
get_info()
const Type_info * Interpolation_IBM_mean_gradient::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interpolation_IBM_base.
Definition at line 22 of file Interpolation_IBM_mean_gradient.cpp.
getSommetsVoisinsOf()
IntList & Interpolation_IBM_mean_gradient::getSommetsVoisinsOf (int i) inline
Definition at line 38 of file Interpolation_IBM_mean_gradient.h.
  {
    return sommets_voisins_[i];
  };
References Interpolation_IBM_mean_gradient_proto::sommets_voisins_.
Referenced by Source_PDF_EF::calculer_vitesse_imposee_mean_grad().
info()
const Type_info * Interpolation_IBM_mean_gradient::info () static
Definition at line 22 of file Interpolation_IBM_mean_gradient.cpp.
printOn()
Sortie & Interpolation_IBM_mean_gradient::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interpolation_IBM_base.
Definition at line 25 of file Interpolation_IBM_mean_gradient.cpp.
{
  Objet_U::printOn( os );
  return os;
}
References Objet_U::printOn().
readOn()
Entree & Interpolation_IBM_mean_gradient::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
< XD_ADD_P field_base Node field giving the projection of the node on the immersed boundary
< XD_ADD_P field_base Node field of booleans indicating whether the node belong to an element where the interface is
< XD_ADD_P field_base Cell field giving the SALOME cell number
< XD_ADD_P field_base Node field giving the element number containing the solid point
Reimplemented from Interpolation_IBM_base.
Definition at line 31 of file Interpolation_IBM_mean_gradient.cpp.
{
  Param param(que_suis_je());
  param.ajouter("points_solides",&solid_points_lu_,Param::REQUIRED);  //!< XD_ADD_P field_base Node field giving the projection of the node on the immersed boundary
  param.ajouter("est_dirichlet",&is_dirichlet_lu_,Param::REQUIRED);   //!< XD_ADD_P field_base Node field of booleans indicating whether the node belong to an element where the interface is
  param.ajouter("correspondance_elements",&corresp_elems_lu_,Param::REQUIRED); //!< XD_ADD_P field_base Cell field giving the SALOME cell number
  param.ajouter("elements_solides",&solid_elems_lu_,Param::REQUIRED); //!< XD_ADD_P field_base Node field giving the element number containing the solid point
  param.lire_avec_accolades_depuis(is);
  return is;
}
References Param::ajouter(), Interpolation_IBM_base::corresp_elems_lu_, Interpolation_IBM_mean_gradient_proto::is_dirichlet_lu_, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), Param::REQUIRED, Interpolation_IBM_mean_gradient_proto::solid_elems_lu_, and Interpolation_IBM_base::solid_points_lu_.
self_cast() [1/2]
const Interpolation_IBM_mean_gradient & Interpolation_IBM_mean_gradient::self_cast (const Objet_U & r) static
Definition at line 22 of file Interpolation_IBM_mean_gradient.cpp.
self_cast() [2/2]
Interpolation_IBM_mean_gradient & Interpolation_IBM_mean_gradient::self_cast (Objet_U & r) static
Definition at line 22 of file Interpolation_IBM_mean_gradient.cpp.
taille_memoire()
unsigned Interpolation_IBM_mean_gradient::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file Interpolation_IBM_mean_gradient.cpp.
Friends And Related Function Documentation
Source_PDF_EF
friend class Source_PDF_EF friend
Definition at line 43 of file Interpolation_IBM_mean_gradient.h.
Member Data Documentation
info_obj
const Type_info Interpolation_IBM_mean_gradient::info_obj static
Definition at line 34 of file Interpolation_IBM_mean_gradient.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Interpolation_IBM/Interpolation_IBM_mean_gradient.h
src/Kernel/Geometrie/Interpolation_IBM/Interpolation_IBM_mean_gradient.cpp