TRUST: Sous_zone_VF Class Reference
Sous_zone_VF Class Reference
#include <Sous_zone_VF.h>
Public Member Functions
Sous_zone_VF ()
~Sous_zone_VF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const IntTab & les_faces () const
IntTab & les_faces ()
int premiere_face_bord_0 () const
int premiere_face_bord_1 () const
int premiere_face_bord () const
double volumes_entrelaces (int) const
void discretiser () override
Public Member Functions inherited from Sous_zone_dis_base
Sous_zone_dis_base ()
~Sous_zone_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_sous_zone (const Sous_Zone &)
Associe une Sous_Zone a l'objet.
const Sous_Zone & sous_zone () const
Sous_Zone & sous_zone ()
void associer_zone_dis (const Zone_dis_base &)
Associe une Zone_dis a l'objet.
const Zone_dis_base & zone_dis () const
Zone_dis_base & zone_dis ()
int nb_elem_tot () const
int operator() (int i) const
int operator[] (int i) const
virtual void discretiser ()=0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Sous_zone_VF & self_cast (Objet_U &)
static const Sous_zone_VF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Sous_zone_dis_base
static const Type_info * info ()
static Sous_zone_dis_base & self_cast (Objet_U &)
static const Sous_zone_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Sous_zone_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VF la_zone_VF
IntTab les_faces_
int premiere_face_bord_0_
int premiere_face_bord_1_
int premiere_face_bord_
DoubleTab volumes_entrelaces_
Protected Attributes inherited from Sous_zone_dis_base
Ref_Sous_Zone la_sous_zone
Ref_Zone_dis_base la_zone_dis
Detailed Description
On suppose que chaque face a au plus deux elements voisins dans la zone, ce qui est toujours le cas en maillage conforme.
Le tableau les_faces contient l'ensemble des faces de la Zone_dis qui appartiennent a cette sous-zone, classees de la facon suivante : Les faces internes a la sous-zone Les faces internes a la zone, mais dont seul le premier element voisin appartient a la sous-zone Les faces internes a la zone, mais dont seul le deuxieme element voisin appartient a la sous-zone Les faces qui ne presentent qu'un element dans la zone. Les separations sont indiquees respectivement par les variables premiere_face_bord_0, premiere_face_bord_1, et premiere_face_bord.
les_faces : nb_dim=1 dimension(0) = le nombre de faces de la sous_zone valeur de l'entier = indice dans les tableaux la_zone_VF->face_voisins_, la_zone_VF->face_sommets_,...
volumes_entrelaces(int face) renvoie le volume entrelace restreint a la sous-zone. Le numero de la face fait reference au tableau les_faces. Seuls sont stockes localement les volumes entrelaces differents de ceux de la zone. ! Cette classe abstraite contient les informations geometrique de sous-zone communes aux methodes de volumes finis (VDF et VEF par exemple)
Definition at line 50 of file Sous_zone_VF.h.
Constructor & Destructor Documentation
Sous_zone_VF()
Sous_zone_VF::Sous_zone_VF ()
Definition at line 18 of file Sous_zone_VF.cpp.
~Sous_zone_VF()
Sous_zone_VF::~Sous_zone_VF ()
Definition at line 18 of file Sous_zone_VF.cpp.
Member Function Documentation
cree_instance()
Objet_U * Sous_zone_VF::cree_instance () static
Definition at line 18 of file Sous_zone_VF.cpp.
discretiser()
void Sous_zone_VF::discretiser () override virtual
< face au bord de la zone
< dans la sous_zone
< face au bord de la zone
< dans la sous_zone
< face interne a la zone
< interne a la sous_zone
< seul elem0 est dans la sous-zone
< seul elem1 est dans la sous-zone
Implements Sous_zone_dis_base.
Definition at line 57 of file Sous_zone_VF.cpp.
{
  Cerr << "Sous_zone_VF::discretiser : discretization of the subarea "
       << la_sous_zone->le_nom() << "... ";
  la_zone_VF=ref_cast(Zone_VF,la_zone_dis.valeur());
  int nb_faces_tot=la_zone_VF->nb_faces_tot();
// Stockages temporaires :
  IntTab faces_internes;
  faces_internes.resize(nb_faces_tot);
  int nb_faces_internes=0;
  IntTab faces_bord_0;
  faces_bord_0.resize(nb_faces_tot);
  int nb_faces_bord_0=0;
  IntTab faces_bord_1;
  faces_bord_1.resize(nb_faces_tot);
  int nb_faces_bord_1=0;
  IntTab faces_bord;
  faces_bord.resize(nb_faces_tot);
  int nb_faces_bord=0;
  IntTab elem_app;
  elem_app.resize(la_zone_VF->nb_elem_tot());
  elem_app=0;
// Remplissage de elem_app
  for (int i=0; i<la_sous_zone->nb_elem_tot(); i++)
    elem_app[la_sous_zone.valeur()(i)]=1;
// Boucle sur les faces
  for (int i=0; i<nb_faces_tot; i++)
    {
      int elem0,elem1;
// Quels elements lui sont voisins ?
      elem0=la_zone_VF->face_voisins(i,0);
      elem1=la_zone_VF->face_voisins(i,1);
// Remplissage des tableaux temporaires.
      if (elem1==-1)                           //!< face au bord de la zone
        {
          if (elem_app[elem0])                         //!< dans la sous_zone
            {
              faces_bord(nb_faces_bord++)=i;
            }
        }
      else if (elem0==-1)                      //!< face au bord de la zone
        {
          if (elem_app[elem1])                         //!< dans la sous_zone
            {
              faces_bord(nb_faces_bord++)=i;
            }
        }
      else                                     //!< face interne a la zone
        {
          if (elem_app[elem0] && elem_app[elem1])          //!< interne a la sous_zone
            {
              faces_internes(nb_faces_internes++)=i;
            }
          else if (elem_app[elem0])                    //!< seul elem0 est dans la sous-zone
            {
              faces_bord_0(nb_faces_bord_0++)=i;
            }
          else if (elem_app[elem1])                    //!< seul elem1 est dans la sous-zone
            {
              faces_bord_1(nb_faces_bord_1++)=i;
            }
        }
    }
// Regroupement des resultats
  premiere_face_bord_0_ = nb_faces_internes;
  premiere_face_bord_1_ = premiere_face_bord_0_+nb_faces_bord_0;
  premiere_face_bord_   = premiere_face_bord_1_+nb_faces_bord_1;
  les_faces_.resize(premiere_face_bord_+nb_faces_bord);
  for (int i=0; i<nb_faces_internes; i++)
    les_faces_(i)=faces_internes(i);
  for (int i=0; i<nb_faces_bord_0; i++)
    les_faces_(premiere_face_bord_0_+i)=faces_bord_0(i);
  for (int i=0; i<nb_faces_bord_1; i++)
    les_faces_(premiere_face_bord_1_+i)=faces_bord_1(i);
  for (int i=0; i<nb_faces_bord; i++)
    les_faces_(premiere_face_bord_+i)=faces_bord(i);
// Calcul des volumes entrelaces
  const DoubleVect& volumes=la_zone_VF->volumes();
  volumes_entrelaces_.resize(nb_faces_bord_0+nb_faces_bord_1);
  for (int i=0; i<nb_faces_bord_0; i++)
    {
      volumes_entrelaces_(i)=volumes(la_zone_VF->face_voisins(les_faces_(premiere_face_bord_0_+i),0));
    }
  for (int i=0; i<nb_faces_bord_1; i++)
    {
      volumes_entrelaces_(nb_faces_bord_0+i)=volumes(la_zone_VF->face_voisins(les_faces_(premiere_face_bord_1_+i),1));
    }
  Cerr << "OK" << finl;
// Affichage du volume des sous zones (ca peut etre pratique)
  double volume_sous_zone=0;
  for (int j=0; j<la_sous_zone->nb_elem_tot(); j++)
    {
// On ne compte que les mailles reelles
      if (la_sous_zone.valeur()(j)<la_zone_VF->zone().nb_elem())
        volume_sous_zone+=volumes(la_sous_zone.valeur()(j));
    }
  volume_sous_zone=mp_sum(volume_sous_zone);
  if (je_suis_maitre())
    Cerr << "Volume of subarea " << la_sous_zone->le_nom() << ": " << volume_sous_zone << finl;
}
References Cerr, Zone_VF::face_voisins(), finl, Process::je_suis_maitre(), Sous_zone_dis_base::la_sous_zone, Sous_zone_dis_base::la_zone_dis, la_zone_VF, Sous_Zone::le_nom(), les_faces_, Process::mp_sum(), Zone::nb_elem(), Zone_dis_base::nb_elem_tot(), Sous_Zone::nb_elem_tot(), Zone_VF::nb_faces_tot(), premiere_face_bord_, premiere_face_bord_0_, premiere_face_bord_1_, ref_cast, TRUSTTab< _TYPE_ >::resize(), Ref_Zone_dis_base::valeur(), Ref_Sous_Zone::valeur(), Zone_VF::volumes(), volumes_entrelaces_, and Zone_dis_base::zone().
duplique()
int Sous_zone_VF::duplique () const override virtual
Implements Objet_U.
Definition at line 18 of file Sous_zone_VF.cpp.
get_info()
const Type_info * Sous_zone_VF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Sous_zone_dis_base.
Definition at line 18 of file Sous_zone_VF.cpp.
info()
const Type_info * Sous_zone_VF::info () static
Definition at line 18 of file Sous_zone_VF.cpp.
les_faces() [1/2]
IntTab & Sous_zone_VF::les_faces () inline
Definition at line 62 of file Sous_zone_VF.h.
  {
    return les_faces_;
  }
References les_faces_.
les_faces() [2/2]
const IntTab & Sous_zone_VF::les_faces () const inline
Definition at line 58 of file Sous_zone_VF.h.
  {
    return les_faces_;
  }
References les_faces_.
Referenced by Perte_Charge_VEF::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::completer(), and Perte_Charge_VEF::contribuer_a_avec().
premiere_face_bord()
int Sous_zone_VF::premiere_face_bord () const inline
Definition at line 74 of file Sous_zone_VF.h.
  {
    return premiere_face_bord_;
  }
References premiere_face_bord_.
premiere_face_bord_0()
int Sous_zone_VF::premiere_face_bord_0 () const inline
Definition at line 66 of file Sous_zone_VF.h.
  {
    return premiere_face_bord_0_;
  }
References premiere_face_bord_0_.
premiere_face_bord_1()
int Sous_zone_VF::premiere_face_bord_1 () const inline
Definition at line 70 of file Sous_zone_VF.h.
  {
    return premiere_face_bord_1_;
  }
References premiere_face_bord_1_.
printOn()
Sortie & Sous_zone_VF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Sous_zone_dis_base.
Definition at line 19 of file Sous_zone_VF.cpp.
{
  Cerr << "Sous_zone_VF::printOn" << finl;
  os << "les_faces : " << finl;
  les_faces_.ecrit(os);
  os << "premiere_face_bord_0 : " << finl;
  os << premiere_face_bord_0_ << finl;
  os << "premiere_face_bord_1 : " << finl;
  os << premiere_face_bord_1_ << finl;
  os << "premiere_face_bord : " << finl;
  os << premiere_face_bord_ << finl;
  return os ;
}
References Cerr, TRUSTTab< _TYPE_ >::ecrit(), finl, les_faces_, premiere_face_bord_, premiere_face_bord_0_, and premiere_face_bord_1_.
readOn()
Entree & Sous_zone_VF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Sous_zone_dis_base.
Definition at line 40 of file Sous_zone_VF.cpp.
{
  Cerr << "Sous_zone_VF::readOn" << finl;
  les_faces_.lit(is);
  is >> premiere_face_bord_0_;
  is >> premiere_face_bord_1_;
  is >> premiere_face_bord_;
  return is ;
}
References Cerr, finl, les_faces_, TRUSTTab< _TYPE_ >::lit(), premiere_face_bord_, premiere_face_bord_0_, and premiere_face_bord_1_.
self_cast() [1/2]
const Sous_zone_VF & Sous_zone_VF::self_cast (const Objet_U & r) static
Definition at line 18 of file Sous_zone_VF.cpp.
self_cast() [2/2]
Sous_zone_VF & Sous_zone_VF::self_cast (Objet_U & r) static
Definition at line 18 of file Sous_zone_VF.cpp.
taille_memoire()
unsigned Sous_zone_VF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 18 of file Sous_zone_VF.cpp.
volumes_entrelaces()
double Sous_zone_VF::volumes_entrelaces (int face) const inline
Definition at line 95 of file Sous_zone_VF.h.
{
  if (face<premiere_face_bord_0_ || face>=premiere_face_bord_)
    return la_zone_VF->volumes_entrelaces(les_faces_(face));
  else
    return volumes_entrelaces_(face-premiere_face_bord_0_);
}
References la_zone_VF, les_faces_, premiere_face_bord_, premiere_face_bord_0_, Zone_VF::volumes_entrelaces(), and volumes_entrelaces_.
Referenced by Perte_Charge_VEF::ajouter(), and Perte_Charge_VEF::contribuer_a_avec().
Member Data Documentation
info_obj
const Type_info Sous_zone_VF::info_obj static
Definition at line 53 of file Sous_zone_VF.h.
la_zone_VF
Ref_Zone_VF Sous_zone_VF::la_zone_VF protected
Definition at line 87 of file Sous_zone_VF.h.
Referenced by discretiser(), and volumes_entrelaces().
les_faces_
IntTab Sous_zone_VF::les_faces_ protected
Definition at line 88 of file Sous_zone_VF.h.
Referenced by discretiser(), les_faces(), printOn(), readOn(), and volumes_entrelaces().
premiere_face_bord_
int Sous_zone_VF::premiere_face_bord_ protected
Definition at line 91 of file Sous_zone_VF.h.
Referenced by discretiser(), premiere_face_bord(), printOn(), readOn(), and volumes_entrelaces().
premiere_face_bord_0_
int Sous_zone_VF::premiere_face_bord_0_ protected
Definition at line 89 of file Sous_zone_VF.h.
Referenced by discretiser(), premiere_face_bord_0(), printOn(), readOn(), and volumes_entrelaces().
premiere_face_bord_1_
int Sous_zone_VF::premiere_face_bord_1_ protected
Definition at line 90 of file Sous_zone_VF.h.
Referenced by discretiser(), premiere_face_bord_1(), printOn(), and readOn().
volumes_entrelaces_
DoubleTab Sous_zone_VF::volumes_entrelaces_ protected
Definition at line 92 of file Sous_zone_VF.h.
Referenced by discretiser(), and volumes_entrelaces().
The documentation for this class was generated from the following files:
src/Kernel/VF/Zones/Sous_zone_VF.h
src/Kernel/VF/Zones/Sous_zone_VF.cpp