TRUST: Champ_Fonc_base Class Reference
Champ_Fonc_base Class Reference
classe Champ_Fonc_base
Classe de base des champs qui sont fonction d'une grandeur calculee
au cours du temps
#include <Champ_Fonc_base.h>
Public Member Functions
Champ_Fonc_base ()
~Champ_Fonc_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps du champ.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
Reprise a partir d'un flot d'entree
Lit le temps et les valeurs du champ.
Saute un bloc si le nom du champ est "anonyme".
int sauvegarder (Sortie &) const override
Sauvegarde le champ sur un flot de sortie
Ecrit le nom, le temps et les valeurs.
Champ_base & affecter_ (const Champ_base &) override
Affecte un Champ_base dans un Champ_Fonc_base.
Champ_base & affecter_compo (const Champ_base &, int compo) override
Affecte une composante d'un Champ_base dans la meme composnate
d'un Champ_Fonc_base.
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
const Domaine & domaine () const
int a_une_zone_dis_base () const override
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void creer_espace_distant (int dummy)
Public Member Functions inherited from Champ_Don_base
Champ_Don_base ()
~Champ_Don_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps.
Parametre: double
Signification: le temps de mise a jour.
void dimensionner (int, int)
Fixe le nombre de composantes et le nombre de valeurs nodales.
Parametre: int
Signification: le nombre de noeud par composante du champ (le nombre de dl par composante)
Parametre: int
Signification: le nombre de composante du champ.
int imprime (Sortie &, int) const override
NE FAIT RIEN. EXIT ! A surcharger dans les classes derivees.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
NE FAIT RIEN. A surcharger dans les classes derivees.
int sauvegarder (Sortie &) const override
NE FAIT RIEN. A surcharger dans les classes derivees.
DoubleTab & valeurs () override
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
const DoubleTab & valeurs () const override
Champ_base & affecter_ (const Champ_base &) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
Champ_base & affecter_compo (const Champ_base &, int) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
virtual int initialiser (const double temps)
NE FAIT RIEN. A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire.
int nb_valeurs_nodales () const override
Renvoie le nombre de degre de liberte par composante: le nombre de noeuds.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static const Type_info * info ()
static Champ_Fonc_base & self_cast (Objet_U &)
static const Champ_Fonc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Don_base
static const Type_info * info ()
static Champ_Don_base & self_cast (Objet_U &)
static const Champ_Don_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Don_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void creer_tableau_distribue (const MD_Vector &, Array_base::Resize_Options=Array_base::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Champ_Don_base
DoubleTab valeurs_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
classe Champ_Fonc_base
Classe de base des champs qui sont fonction d'une grandeur calculee
au cours du temps
Definition at line 42 of file Champ_Fonc_base.h.
Constructor & Destructor Documentation
Champ_Fonc_base()
Champ_Fonc_base::Champ_Fonc_base ()
Definition at line 22 of file Champ_Fonc_base.cpp.
~Champ_Fonc_base()
Champ_Fonc_base::~Champ_Fonc_base () override
Definition at line 22 of file Champ_Fonc_base.cpp.
Member Function Documentation
a_une_zone_dis_base()
int Champ_Fonc_base::a_une_zone_dis_base () const inline override virtual
Par defaut, on ne sait pas si une zone_dis_base sera definie.
Reimplemented from Champ_base.
Definition at line 61 of file Champ_Fonc_base.h.
  {
    return 1;
  };
affecter_()
Champ_base & Champ_Fonc_base::affecter_ (const Champ_base & ch) override virtual
Affecte un Champ_base dans un Champ_Fonc_base.
Returns
Champ_base&
Signification: le resultat de l'affectation (*this) (avec upcast)
Contraintes:
Reimplemented from Champ_Don_base.
Reimplemented in Champ_Fonc_Face_PolyMAC, Champ_Ostwald, Champ_Fonc_Face, and Champ_Fonc_Elem_PolyMAC.
Definition at line 222 of file Champ_Fonc_base.cpp.
{
  DoubleTab noeuds;
  remplir_coord_noeuds(noeuds);
  ch.valeur_aux(noeuds, valeurs());
  return *this;
}
References remplir_coord_noeuds(), Champ_base::valeur_aux(), and Champ_Don_base::valeurs().
Referenced by Champ_Fonc_P0_base::affecter_().
affecter_compo()
Champ_base & Champ_Fonc_base::affecter_compo (const Champ_base & ch, int compo) override virtual
Affecte une composante d'un Champ_base dans la meme composnate
d'un Champ_Fonc_base.
Returns
Champ_base&
Signification: le resultat de l'affectation (*this) (avec upcast)
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 252 of file Champ_Fonc_base.cpp.
{
  DoubleTab noeuds;
  IntVect polys;
  if(!remplir_coord_noeuds_et_polys_compo(noeuds, polys, compo))
    {
      remplir_coord_noeuds_compo(noeuds, compo);
      ch.valeur_aux_compo(noeuds, valeurs(), compo);
    }
  else
    ch.valeur_aux_elems_compo(noeuds, polys, valeurs(), compo);
  return *this;
}
References remplir_coord_noeuds_compo(), remplir_coord_noeuds_et_polys_compo(), Champ_base::valeur_aux_compo(), Champ_base::valeur_aux_elems_compo(), and Champ_Don_base::valeurs().
creer_espace_distant()
virtual void Champ_Fonc_base::creer_espace_distant (int dummy) inline virtual
Definition at line 66 of file Champ_Fonc_base.h.
{ };
creer_tableau_distribue()
void Champ_Fonc_base::creer_tableau_distribue (const MD_Vector & md, Array_base::Resize_Options opt = Array_base::COPY_INIT) protected virtual
Definition at line 95 of file Champ_Fonc_base.cpp.
{
// Note B.M.: pour etre symetrique avec Champ_Inc_base, il faudrait tester si le
// champ est scalaire ou multi-scalaire (voir Champ_Inc_base::creer_tableau_distribue())
  if (valeurs_.size_array() == 0 && (!valeurs_.get_md_vector().non_nul()))
    {
// Note B.M.: les methodes fixer_nb_valeurs_nodales sont appelees a tort et a travers.
// Ne rien faire si le tableau a deja la bonne structure
      valeurs_.resize(0, nb_compo_);
    }
// Ca va planter si on a attache une autre structure parallele (c'est voulu !)
  if (!(valeurs_.get_md_vector() == md))
    {
      if (valeurs_.get_md_vector().non_nul())
        {
          Cerr << "Internal error in Champ_Fonc_base::creer_tableau_distribue:\n"
               << " array has alreary a (wrong) parallel descriptor" << finl;
          exit();
        }
      MD_Vector_tools::creer_tableau_distribue(md, valeurs_, opt);
    }
}
References Cerr, MD_Vector_tools::creer_tableau_distribue(), Process::exit(), finl, TRUSTVect< _TYPE_ >::get_md_vector(), Field_base::nb_compo_, MD_Vector::non_nul(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::size_array(), and Champ_Don_base::valeurs_.
Referenced by Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Champ_Fonc_Face_PolyMAC::fixer_nb_valeurs_nodales(), grad_Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales(), Champ_Fonc_P1_base::fixer_nb_valeurs_nodales(), Champ_Fonc_Q1_base::fixer_nb_valeurs_nodales(), Champ_Fonc_P1_isoP1Bulle::fixer_nb_valeurs_nodales(), Champ_Fonc_Face::fixer_nb_valeurs_nodales(), Champ_Fonc_P1NC::fixer_nb_valeurs_nodales(), and Champ_Fonc_Q1NC::fixer_nb_valeurs_nodales().
domaine()
const Domaine & Champ_Fonc_base::domaine () const
Definition at line 377 of file Champ_Fonc_base.cpp.
{
  return zone_dis_base().zone().domaine();
}
References Zone::domaine(), Zone_dis_base::zone(), and Champ_base::zone_dis_base().
Referenced by Champ_Fonc_P1_base::fixer_nb_valeurs_nodales(), and Champ_Fonc_Q1_base::fixer_nb_valeurs_nodales().
fixer_nb_valeurs_nodales()
int Champ_Fonc_base::fixer_nb_valeurs_nodales (int nb_noeuds) override virtual
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
Reimplemented from Champ_Don_base.
Reimplemented in Champ_Fonc_Face_PolyMAC, grad_Champ_Face_PolyMAC_P0, Champ_Ostwald, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Face, Champ_Fonc_P1NC, and Champ_Fonc_Q1NC.
Definition at line 87 of file Champ_Fonc_base.cpp.
{
  Cerr << "Error in Champ_Fonc_base::fixer_nb_valeurs_nodales: method not reimplemented for the class "
       << que_suis_je() << finl;
  exit();
  return nb_noeuds;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Champ_Fonc_MED::creer(), Champ_Fonc::fixer_nb_valeurs_nodales(), and Champ_Fonc_MED_Table_Temps::lire_donnees_champ().
get_info()
const Type_info * Champ_Fonc_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Reimplemented in Champ_Fonc_MED, Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_Fonc_reprise, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, grad_Champ_Face_PolyMAC_P0, Champ_Ostwald, Champ_Don_Face_lu, Champ_Fonc_Face, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 22 of file Champ_Fonc_base.cpp.
info()
const Type_info * Champ_Fonc_base::info () static
Definition at line 22 of file Champ_Fonc_base.cpp.
mettre_a_jour()
void Champ_Fonc_base::mettre_a_jour (double temps) override virtual
Mise a jour en temps du champ.
Reimplemented from Champ_Don_base.
Reimplemented in Champ_Fonc_MED_Tabule, Champ_Ostwald, Champ_Ostwald_VDF, Champ_Ostwald_VEF, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_MED, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_Fonc_reprise, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, grad_Champ_Face_PolyMAC_P0, Champ_Fonc_Face, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 81 of file Champ_Fonc_base.cpp.
{
  changer_temps(un_temps);
  valeurs().echange_espace_virtuel();
}
References Champ_base::changer_temps(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), and Champ_Don_base::valeurs().
Referenced by Equation_base::get_champ(), Convection_Diffusion_Temperature::get_champ(), Navier_Stokes_std::get_champ(), Champ_Fonc_MED::lire(), Champ_Fonc_MED_Table_Temps::lire(), Champ_Fonc_Elem_PolyMAC_P0_rot::mettre_a_jour(), Champ_Fonc::mettre_a_jour(), Champ_Fonc_Tabule::mettre_a_jour(), Champ_Fonc_P1_EF::mettre_a_jour(), Champ_Fonc_Q1_EF::mettre_a_jour(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Champ_Fonc_P0_base::mettre_a_jour(), Champ_Fonc_reprise::mettre_a_jour(), Champ_Fonc_P1_isoP1Bulle::mettre_a_jour(), Champ_Fonc_Elem_PolyMAC_P0_TC::mettre_a_jour(), Champ_Fonc_Face_PolyMAC::mettre_a_jour(), Champ_Fonc_Som_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), grad_Champ_Face_PolyMAC_P0::mettre_a_jour(), Champ_Fonc_Face::mettre_a_jour(), Champ_Fonc_P1_VDF::mettre_a_jour(), Champ_Fonc_Q1_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Correlation_Vec_Sca_VDF::mettre_a_jour(), Courant_maille_Champ_Face::mettre_a_jour(), Critere_Q_Champ_Face::mettre_a_jour(), grad_U_Champ_Face::mettre_a_jour(), Reynolds_maille_Champ_Face::mettre_a_jour(), Rotationnel_Champ_Face::mettre_a_jour(), Taux_cisaillement_P0_VDF::mettre_a_jour(), Y_plus_Champ_Face::mettre_a_jour(), Champ_Fonc_P1_VEF::mettre_a_jour(), Champ_Fonc_P1NC::mettre_a_jour(), Champ_Fonc_Q1_VEF::mettre_a_jour(), Champ_Fonc_Q1NC::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Correlation_Vec_Sca_VEF::mettre_a_jour(), Critere_Q_Champ_P1NC::mettre_a_jour(), grad_T_Champ_P1NC::mettre_a_jour(), grad_U_Champ_P1NC::mettre_a_jour(), h_conv_Champ_P1NC::mettre_a_jour(), Taux_cisaillement_P0_VEF::mettre_a_jour(), and Y_plus_Champ_P1NC::mettre_a_jour().
printOn()
Sortie & Champ_Fonc_base::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Don_base.
Reimplemented in Champ_Fonc_MED, Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_Fonc_reprise, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, grad_Champ_Face_PolyMAC_P0, Champ_Ostwald, Champ_Don_Face_lu, Champ_Fonc_Face, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 40 of file Champ_Fonc_base.cpp.
{
  return s ;
}
readOn()
Entree & Champ_Fonc_base::readOn (Entree & s) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Don_base.
Reimplemented in Champ_Fonc_MED, Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_Fonc_reprise, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, grad_Champ_Face_PolyMAC_P0, Champ_Ostwald, Champ_Don_Face_lu, Champ_Fonc_Face, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 61 of file Champ_Fonc_base.cpp.
{
  return s ;
}
remplir_coord_noeuds()
DoubleTab & Champ_Fonc_base::remplir_coord_noeuds (DoubleTab & coord) const virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
DoubleTab&
Signification: renvoie toujours le parametre coord
Contraintes:
Reimplemented in Champ_Fonc_MED, Champ_Fonc_reprise, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Face, Champ_Fonc_P1NC, and Champ_Fonc_Q1NC.
Definition at line 309 of file Champ_Fonc_base.cpp.
{
// Ne retourne rien
  return coord;
}
Referenced by affecter_(), and Champ_Fonc_MED::remplir_coord_noeuds().
remplir_coord_noeuds_compo()
DoubleTab & Champ_Fonc_base::remplir_coord_noeuds_compo (DoubleTab & coord, int) const virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
DoubleTab&
Signification: renvoie toujours le parametre coord
Contraintes:
Definition at line 336 of file Champ_Fonc_base.cpp.
{
// Ne retourne rien
  return coord;
}
Referenced by affecter_compo().
remplir_coord_noeuds_et_polys()
int Champ_Fonc_base::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
int
Signification: renvoie toujours 0
Contraintes:
Reimplemented in Champ_Fonc_MED, Champ_Fonc_reprise, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Face, Champ_Fonc_P1NC, and Champ_Fonc_Q1NC.
Definition at line 288 of file Champ_Fonc_base.cpp.
{
  return 0;
}
Referenced by Champ_Fonc_MED::remplir_coord_noeuds_et_polys().
remplir_coord_noeuds_et_polys_compo()
int Champ_Fonc_base::remplir_coord_noeuds_et_polys_compo (DoubleTab & , IntVect & , int) const virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
int
Signification: renvoie toujours 0
Contraintes:
Definition at line 369 of file Champ_Fonc_base.cpp.
{
  return 0;
}
Referenced by affecter_compo().
reprendre()
int Champ_Fonc_base::reprendre (Entree & fich) override virtual
Reprise a partir d'un flot d'entree
Lit le temps et les valeurs du champ.
Saute un bloc si le nom du champ est "anonyme".
Returns
int
Signification: renvoie toujours 1
Contraintes:
< lecture pour reprise
< lecture pour sauter le bloc
Reimplemented from Champ_Don_base.
Definition at line 185 of file Champ_Fonc_base.cpp.
{
  double un_temps;
  int special= EcritureLectureSpecial::is_lecture_special();
  if (nom_ != Nom("anonyme")) //!< lecture pour reprise
    {
      fich >> un_temps;
      if (special)
        EcritureLectureSpecial::lecture_special(*this,fich);
      else
        valeurs().lit(fich);
      Cerr << "Resume of the field " <<nom_<< " performed " << finl;
    }
  else //!< lecture pour sauter le bloc
    {
      DoubleTab tempo;
      fich >> un_temps;
      tempo.jump(fich);
    }
  return 1;
}
References Cerr, finl, EcritureLectureSpecial::is_lecture_special(), TRUSTTab< _TYPE_ >::jump(), EcritureLectureSpecial::lecture_special(), TRUSTTab< _TYPE_ >::lit(), Field_base::nom_, and Champ_Don_base::valeurs().
Referenced by Champ_Fonc::reprendre().
sauvegarder()
int Champ_Fonc_base::sauvegarder (Sortie & fich) const override virtual
Sauvegarde le champ sur un flot de sortie
Ecrit le nom, le temps et les valeurs.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 133 of file Champ_Fonc_base.cpp.
{
// en mode ecriture special seul le maitre ecrit l'entete
  int a_faire,special;
  EcritureLectureSpecial::is_ecriture_special(special,a_faire);
  if (a_faire)
    {
      Nom mon_ident(nom_);
      mon_ident += que_suis_je();
      mon_ident += zone_dis_base().zone().domaine().le_nom();
      mon_ident += Nom(temps_,"%e");
      fich << mon_ident << finl;
      fich << que_suis_je() << finl;
      fich << temps_ << finl;
    }
  int bytes = 0;
  if (special)
    bytes = EcritureLectureSpecial::ecriture_special(*this,fich);
  else
    {
      bytes = 8 * valeurs().size_array();
      valeurs().ecrit(fich);
    }
  if (a_faire)
    {
// fich << flush ; Ne marche pas en binaire, preferer:
      fich.flush();
    }
  if (Process::je_suis_maitre())
    Cerr << "Backup of the field " << nom_ << " performed on time : " << Nom(temps_,"%e") << finl;
  return bytes;
}
References Cerr, Zone::domaine(), TRUSTTab< _TYPE_ >::ecrit(), EcritureLectureSpecial::ecriture_special(), finl, Sortie::flush(), EcritureLectureSpecial::is_ecriture_special(), Process::je_suis_maitre(), Domaine::le_nom(), Field_base::nom_, Objet_U::que_suis_je(), TRUSTArray< _TYPE_ >::size_array(), Champ_base::temps_, Champ_Don_base::valeurs(), Zone_dis_base::zone(), and Champ_base::zone_dis_base().
Referenced by Champ_Fonc::sauvegarder().
self_cast() [1/2]
const Champ_Fonc_base & Champ_Fonc_base::self_cast (const Objet_U & r) static
Definition at line 22 of file Champ_Fonc_base.cpp.
self_cast() [2/2]
Champ_Fonc_base & Champ_Fonc_base::self_cast (Objet_U & r) static
Definition at line 22 of file Champ_Fonc_base.cpp.
valeur_aux()
DoubleTab & Champ_Fonc_base::valeur_aux (const DoubleTab & positions, DoubleTab & les_valeurs) const override virtual
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 382 of file Champ_Fonc_base.cpp.
{
  const Zone& zone=zone_dis_base().zone();
  IntVect les_polys(positions.dimension(0));
  zone.chercher_elements(positions, les_polys);
  return valeur_aux_elems(positions, les_polys, tab_valeurs);
}
References Zone::chercher_elements(), TRUSTTab< _TYPE_ >::dimension(), Champ_base::valeur_aux_elems(), Zone_dis_base::zone(), and Champ_base::zone_dis_base().
Referenced by Champ_Fonc_P0_VDF::imprime().
Member Data Documentation
info_obj
const Type_info Champ_Fonc_base::info_obj static
Definition at line 44 of file Champ_Fonc_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_Fonc_base.h
src/Kernel/Framework/Champ_Fonc_base.cpp