TRUST: Operateur Class Reference
Operateur Class Reference abstract
classe Operateur
Classe generique de la hierarchie des operateurs.
Cette classe generique est particuliere car elle n'HERITE PAS
de DERIV(Operateur_base) mais de MorEqn.
Une reference sur un Operateur_base est renvoye par la methode
Operateur::l_op_base() qui est virtuelle pure et doit etre surchargee
dans ses derivees.
#include <Operateur.h>
Public Member Functions
virtual Operateur_base & l_op_base ()=0
virtual const Operateur_base & l_op_base () const =0
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const =0
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const =0
DoubleTab & ajouter (const Champ_Inc &, DoubleTab &) const
Calcule et ajoute la contribution de l'operateur au second
membre de l'equation.
Appelle Operateur::ajouter(const DoubleTab&, DoubleTab&)
DoubleTab & calculer (const Champ_Inc &, DoubleTab &) const
Calcule la contribution de l'operateur, et renvoie
le tableau des valeurs.
DoubleTab & ajouter (DoubleTab &) const
Ajoute la contribution de l'operateur au tableau passe
en parametre.
Appelle Operateur::ajouter(const Champ_Inc&, DoubleTab&)
DoubleTab & calculer (DoubleTab &) const
Applique l'operateur au champ inconnu et renvoie le resultat.
Appelle Operateur::calculer(const Champ_Inc&, DoubleTab&);.
const Nom & type () const
Renvoie le (nom du) type de l'operateur a creer.
double calculer_pas_de_temps () const
Calcule le prochain pas de temps.
void calculer_pas_de_temps_locaux (DoubleTab &) const
Calculate the next local time steps.
int impr (Sortie &os) const
Imprime l'operateur sur un flot de sortie de facon
inconditionnelle.
virtual void typer ()=0
virtual void completer ()
Met a jour les references des objets associes a l'operateur.
Operateur::le_champ_inco, Operateur::champ_inco
Appelle Operateur_base::completer()
virtual void mettre_a_jour (double temps)
Effecttue une mise a jour en temps de l'operateur.
Appelle Operateur_base::mettre_a_jour(double)
const Champ_Inc & mon_inconnue () const
Renvoie le champ representant l'inconnue de l'equation dont
l'operateur fait partie.
const Discretisation_base & discretisation () const
Renvoie la discretisation de l'equation dont l'operateur
fait partie.
int limpr () const
Demande a l'equation si une impression est necessaire
Renvoie 1 pour OUI, 0 sinon.
void imprimer (Sortie &os) const
Imprime l'operateur sur un flot de sortie, si
c'est necessaire. (voir Schema_Temp_base::limpr())
Sortie & ecrire (Sortie &) const
Ecrit le type de l'operateur sur un flot de Sortie.
Entree & lire (Entree &)
Lit un operateur sur un flot d'entree.
Type l'operateur et lui associe son equation.
Format:
{
[UN Motcle REPRESENTANT UN TYPE]
}.
void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
void associer_champ (const Champ_Inc &)
void set_fichier (const Nom &nom)
void set_description (const Nom &nom)
virtual int op_non_nul () const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Protected Attributes
Ref_Champ_Inc le_champ_inco
Motcle typ
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Detailed Description
classe Operateur
Classe generique de la hierarchie des operateurs.
Cette classe generique est particuliere car elle n'HERITE PAS
de DERIV(Operateur_base) mais de MorEqn.
Une reference sur un Operateur_base est renvoye par la methode
Operateur::l_op_base() qui est virtuelle pure et doit etre surchargee
dans ses derivees.
Definition at line 46 of file Operateur.h.
Member Function Documentation
ajouter() [1/3]
DoubleTab & Operateur::ajouter (const Champ_Inc & ch, DoubleTab & resu) const
Calcule et ajoute la contribution de l'operateur au second
membre de l'equation.
Appelle Operateur::ajouter(const DoubleTab&, DoubleTab&)
Returns
DoubleTab&
Signification: le second membre auquel on a ajoute la contribution
de l'operateur
Contraintes:
Definition at line 342 of file Operateur.cpp.
{
  int i ;
  int nstep=l_op_base().get_nb_ss_pas_de_temps();
  double dt=equation().schema_temps().pas_de_temps();
  dt/=nstep;
  if(nstep==1)
    return ajouter(ch.valeurs(), resu);
  DoubleTrav derivee(resu);
  DoubleTrav inco(ch.valeurs());
  inco=ch.valeurs();
  const Solveur_Masse& solveur_masse=equation().solv_masse();
  double dt_inv=1./(double(nstep));
  for (i=0; i<nstep; i++)
    {
      calculer(inco, derivee);
      derivee.echange_espace_virtuel();
      resu.ajoute(dt_inv, derivee) ;
      solveur_masse.appliquer(derivee);
      inco.ajoute_sans_ech_esp_virt(dt, derivee, VECT_ALL_ITEMS) ;
    }
  return resu;
}
References TRUSTVect< _TYPE_ >::ajoute(), TRUSTVect< _TYPE_ >::ajoute_sans_ech_esp_virt(), ajouter(), Solveur_Masse::appliquer(), calculer(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), Operateur_base::get_nb_ss_pas_de_temps(), l_op_base(), Schema_Temps_base::pas_de_temps(), Equation_base::schema_temps(), Equation_base::solv_masse(), Champ_Inc::valeurs(), and VECT_ALL_ITEMS.
ajouter() [2/3]
virtual DoubleTab & Operateur::ajouter (const DoubleTab & , DoubleTab &) const pure virtual
Implemented in Operateur_Conv, Operateur_Diff, Operateur_Div, Operateur_Grad, and Operateur_Evanescence.
Referenced by ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Equation_base::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Temperature::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), calculer(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), Terme_Source_Canal_perio::compute_heat_flux(), Equation_base::derivee_en_temps_conv(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Equation_base::Gradient_conjugue_diff_impl(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), and Navier_Stokes_std::preparer_calcul().
ajouter() [3/3]
DoubleTab & Operateur::ajouter (DoubleTab & resu) const
Ajoute la contribution de l'operateur au tableau passe
en parametre.
Appelle Operateur::ajouter(const Champ_Inc&, DoubleTab&)
Returns
DoubleTab&
Signification: le second membre auquel on a ajoute la contribution
de l'operateur
Contraintes:
Definition at line 430 of file Operateur.cpp.
{
  return ajouter(le_champ_inco.valeur().valeurs(), resu);
}
References ajouter(), le_champ_inco, Ref_Champ_Inc::valeur(), and Champ_Inc::valeurs().
ajouter_contribution_explicite_au_second_membre()
void Operateur::ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base & inconnue, DoubleTab & derivee) const
Definition at line 468 of file Operateur.cpp.
{
  l_op_base().ajouter_contribution_explicite_au_second_membre (linconnue, derivee);
}
References Operateur_base::ajouter_contribution_explicite_au_second_membre(), and l_op_base().
associer_champ()
void Operateur::associer_champ (const Champ_Inc & ch)
Definition at line 200 of file Operateur.cpp.
{
  le_champ_inco = ch;
  l_op_base().associer_champ(ch);
}
References Operateur_base::associer_champ(), l_op_base(), and le_champ_inco.
calculer() [1/3]
DoubleTab & Operateur::calculer (const Champ_Inc & ch, DoubleTab & resu) const
Calcule la contribution de l'operateur, et renvoie
le tableau des valeurs.
Returns
DoubleTab&
Signification: le resultat de l'application de l'operateur sur le champ inconnu
Contraintes:
Definition at line 407 of file Operateur.cpp.
{
  return calculer(ch.valeurs(), resu);
}
References calculer(), and Champ_Inc::valeurs().
calculer() [2/3]
virtual DoubleTab & Operateur::calculer (const DoubleTab & , DoubleTab &) const pure virtual
Implemented in Operateur_Conv, Operateur_Diff, Operateur_Div, Operateur_Grad, and Operateur_Evanescence.
Referenced by ajouter(), calculer(), Equation_base::derivee_en_temps_inco(), and Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base().
calculer() [3/3]
DoubleTab & Operateur::calculer (DoubleTab & resu) const
Applique l'operateur au champ inconnu et renvoie le resultat.
Appelle Operateur::calculer(const Champ_Inc&, DoubleTab&);.
Returns
DoubleTab&
Signification: le resultat de l'application de l'operateur sur le champ inconnu
Contraintes:
Definition at line 451 of file Operateur.cpp.
{
  resu=0.;
  return ajouter(le_champ_inco.valeur().valeurs(), resu);
}
References ajouter(), le_champ_inco, Ref_Champ_Inc::valeur(), and Champ_Inc::valeurs().
calculer_pas_de_temps()
double Operateur::calculer_pas_de_temps () const
Calcule le prochain pas de temps.
Definition at line 239 of file Operateur.cpp.
{
// Si l'equation de l'operateur n'est pas resolue, on ne calcule pas son pas de temps de stabilite
  if (equation().equation_non_resolue())
    return DMAXFLOAT;
  statistiques().begin_count(dt_counter_);
  double dt_stab = l_op_base().calculer_dt_stab();
  statistiques().end_count(dt_counter_);
// Verification que l'operateur a bien un mp_min de fait:
  assert(dt_stab==Process::mp_min(dt_stab));
  return dt_stab;
}
References Statistiques::begin_count(), Operateur_base::calculer_dt_stab(), DMAXFLOAT, dt_counter_, Statistiques::end_count(), MorEqn::equation(), l_op_base(), Process::mp_min(), and statistiques().
Referenced by Equation_base::calculer_pas_de_temps(), Equation_base::derivee_en_temps_conv(), and Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco().
calculer_pas_de_temps_locaux()
void Operateur::calculer_pas_de_temps_locaux (DoubleTab & dt_locaux) const
Calculate the next local time steps.
Definition at line 253 of file Operateur.cpp.
{
  l_op_base().calculer_dt_local(dt_locaux);
}
References Operateur_base::calculer_dt_local(), and l_op_base().
Referenced by Equation_base::calculer_pas_de_temps_locaux().
completer()
void Operateur::completer () virtual
Met a jour les references des objets associes a l'operateur.
Operateur::le_champ_inco, Operateur::champ_inco
Appelle Operateur_base::completer()
Definition at line 192 of file Operateur.cpp.
{
  if (!le_champ_inco.non_nul())
    le_champ_inco=mon_equation->inconnue();
  l_op_base().completer();
}
References Operateur_base::completer(), Equation_base::inconnue(), l_op_base(), le_champ_inco, MorEqn::mon_equation, and O_U_Ptr::non_nul().
Referenced by Equation_base::completer(), Navier_Stokes_std::completer(), and Champ_Generique_Divergence::completer().
discretisation()
const Discretisation_base & Operateur::discretisation () const
Renvoie la discretisation de l'equation dont l'operateur
fait partie.
Returns
Discretisation_base&
Signification: la discretisation de l'equation associee
Contraintes: reference constante
Definition at line 171 of file Operateur.cpp.
{
  return mon_equation->discretisation();
}
References Equation_base::discretisation(), and MorEqn::mon_equation.
ecrire()
Sortie & Operateur::ecrire (Sortie & os) const
Ecrit le type de l'operateur sur un flot de Sortie.
Returns
Sortie& le flot de sortie modifie
Signification:
Contraintes:
Definition at line 37 of file Operateur.cpp.
{
  os << " { " << typ << " } " << finl;
  return os;
}
References finl, and typ.
Referenced by Operateur_Conv::printOn(), Operateur_Diff::printOn(), Operateur_Div::printOn(), Operateur_Grad::printOn(), and Operateur_Evanescence::printOn().
impr()
int Operateur::impr (Sortie & os) const
Imprime l'operateur sur un flot de sortie de facon
inconditionnelle.
Returns
int
Signification: code de Operateur_base::impr(Sortie&)
Contraintes:
Definition at line 314 of file Operateur.cpp.
{
  return l_op_base().impr(os);
}
References Operateur_base::impr(), and l_op_base().
Referenced by Equation_base::impr(), and Navier_Stokes_std::impr().
imprimer()
void Operateur::imprimer (Sortie & os) const
Imprime l'operateur sur un flot de sortie, si
c'est necessaire. (voir Schema_Temp_base::limpr())
Definition at line 292 of file Operateur.cpp.
{
  if(limpr())
    l_op_base().impr(os);
}
References Operateur_base::impr(), l_op_base(), and limpr().
l_op_base() [1/2]
virtual const Operateur_base & Operateur::l_op_base () const pure virtual
Implemented in Operateur_Conv, Operateur_Diff, Operateur_Div, Operateur_Grad, and Operateur_Evanescence.
l_op_base() [2/2]
virtual Operateur_base & Operateur::l_op_base () pure virtual
Implemented in Operateur_Conv, Operateur_Diff, Operateur_Div, Operateur_Grad, and Operateur_Evanescence.
Referenced by Equation_base::abortTimeStep(), ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Flux_interfacial_PolyMAC::ajouter_blocs(), ajouter_contribution_explicite_au_second_membre(), Equation_base::ajouter_termes_croises(), Equation_base::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Temperature::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Equation_base::assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), associer_champ(), Champ_P1NC::calcul_h_conv(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), Equation_base::calculer_pas_de_temps(), calculer_pas_de_temps(), Equation_base::calculer_pas_de_temps_locaux(), calculer_pas_de_temps_locaux(), Equation_base::completer(), completer(), Terme_Source_Canal_perio::compute_heat_flux(), Equation_base::contribuer_termes_croises(), Equation_base::creer_champ(), Postraitement::creer_champ_post_moreqn(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Equation_base::dimensionner_blocs(), Equation_base::dimensionner_matrice_sans_mem(), Equation_base::dimensionner_termes_croises(), Equation_base::get_champ(), Equation_base::get_noms_champs_postraitables(), Equation_base::Gradient_conjugue_diff_impl(), Equation_base::has_interface_blocs(), impr(), imprimer(), Echange_contact_PolyMAC::init_op(), Echange_contact_PolyMAC_P0::init_op(), Op_Diff_VDF_base::init_op_ext(), SETS::iterer_eqn(), lire(), mettre_a_jour(), Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_nu(), Equation_base::modifier_pour_Cl(), Champ_Generique_Morceau_Equation::morceau(), Champ_Post_Operateur_Eqn::Operateur(), Equation_base::preparer_calcul(), Equation_base::printOn(), set_description(), set_fichier(), and Equation_base::updateGivenFields().
limpr()
int Operateur::limpr () const
Demande a l'equation si une impression est necessaire
Renvoie 1 pour OUI, 0 sinon.
Returns
int
Signification: 1 si une impression est necessaire 0 sinon
Contraintes:
Definition at line 272 of file Operateur.cpp.
{
  return mon_equation->limpr();
}
References Equation_base::limpr(), and MorEqn::mon_equation.
Referenced by imprimer().
lire()
Entree & Operateur::lire (Entree & is)
Lit un operateur sur un flot d'entree.
Type l'operateur et lui associe son equation.
Format:
{
[UN Motcle REPRESENTANT UN TYPE]
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Definition at line 64 of file Operateur.cpp.
{
  typ="non defini";
  Motcle motlu;
  is >> motlu ;
  assert(motlu=="{");
  while(motlu!="}")
    {
      is>>motlu;
      if (motlu=="}")
        {
          if(typ=="non defini")
            {
              typ = "";
              typer();
              l_op_base().associer_eqn(equation());
              l_op_base().set_nb_ss_pas_de_temps(1);
              l_op_base().set_decal_temps(0);
            }
        }
      else if (motlu=="nb_sous_pas_de_temps")
        {
          if(typ=="non defini")
            {
              typ = "";
              typer();
              l_op_base().associer_eqn(equation());
            }
          int nb_ss_pas_de_temps;
          is >> nb_ss_pas_de_temps;
          l_op_base().set_nb_ss_pas_de_temps(nb_ss_pas_de_temps);
          l_op_base().set_decal_temps(0);
        }
      else if (motlu=="implicite")
        {
          if(typ=="non defini")
            {
              typ = "";
              typer();
              l_op_base().associer_eqn(equation());
            }
          l_op_base().set_decal_temps(1);
          l_op_base().set_nb_ss_pas_de_temps(1);
          is >> motlu;
          if(motlu != "solveur")
            {
              Cerr << "We expected the keyword \"solveur\" instead of : "
                   << motlu << finl;;
              Process::exit();
            }
          l_op_base().lire_solveur(is);
        }
      else
        {
          if(typ!="non defini")
            {
              Cerr << "We must choose the type of operator in beginning "
                   <<"of reading block (before implicit in particular) "
                   << finl;
              Process::exit();
            }
          typ=motlu;
          typer();
          l_op_base().associer_eqn(equation());
          l_op_base().set_decal_temps(0);
          l_op_base().set_nb_ss_pas_de_temps(1);
          is >> l_op_base();
        }
    }
  return is;
}
References Operateur_base::associer_eqn(), Cerr, MorEqn::equation(), Process::exit(), finl, l_op_base(), Operateur_base::lire_solveur(), Operateur_base::set_decal_temps(), Operateur_base::set_nb_ss_pas_de_temps(), typ, and typer().
Referenced by Operateur_Conv::readOn(), Operateur_Diff::readOn(), Operateur_Div::readOn(), Operateur_Grad::readOn(), and Operateur_Evanescence::readOn().
mettre_a_jour()
void Operateur::mettre_a_jour (double temps) virtual
Effecttue une mise a jour en temps de l'operateur.
Appelle Operateur_base::mettre_a_jour(double)
Definition at line 221 of file Operateur.cpp.
{
  l_op_base().mettre_a_jour(temps);
}
References l_op_base(), and Operateur_base::mettre_a_jour().
Referenced by Equation_base::initTimeStep().
mon_inconnue()
const Champ_Inc & Operateur::mon_inconnue () const
Renvoie le champ representant l'inconnue de l'equation dont
l'operateur fait partie.
Returns
Champ_Inc&
Signification: le champ inconuu de l'equation associee
Contraintes: reference constante
Definition at line 151 of file Operateur.cpp.
{
  return le_champ_inco.valeur();
}
References le_champ_inco, and Ref_Champ_Inc::valeur().
Referenced by Champ_Post_Operateur_Eqn::get_champ().
op_non_nul()
virtual int Operateur::op_non_nul () const pure virtual
Implemented in Operateur_Conv, Operateur_Diff, Operateur_Div, Operateur_Grad, and Operateur_Evanescence.
Referenced by Equation_base::updateGivenFields().
set_description()
void Operateur::set_description (const Nom & nom)
Definition at line 463 of file Operateur.cpp.
{
  l_op_base().set_description(nom);
}
References l_op_base(), and Operateur_base::set_description().
Referenced by Convection_Diffusion_Chaleur_Fluide_Dilatable_base::readOn(), Convection_Diffusion_Espece_Binaire_base::readOn(), Convection_Diffusion_Espece_Multi_base::readOn(), Navier_Stokes_Fluide_Dilatable_base::readOn(), Convection_Diffusion_Concentration::readOn(), Convection_Diffusion_Temperature::readOn(), Navier_Stokes_std::readOn(), Aire_interfaciale::readOn(), Energie_Multiphase::readOn(), Masse_Multiphase::readOn(), QDM_Multiphase::readOn(), and Conduction::readOn().
set_fichier()
void Operateur::set_fichier (const Nom & nom)
Definition at line 458 of file Operateur.cpp.
{
  l_op_base().set_fichier(nom);
}
References l_op_base(), and Operateur_base::set_fichier().
Referenced by Convection_Diffusion_Chaleur_Fluide_Dilatable_base::readOn(), Convection_Diffusion_Espece_Binaire_base::readOn(), Convection_Diffusion_Espece_Multi_base::readOn(), Convection_Diffusion_Concentration::readOn(), Convection_Diffusion_Temperature::readOn(), Navier_Stokes_std::readOn(), Aire_interfaciale::readOn(), Energie_Multiphase::readOn(), Masse_Multiphase::readOn(), and Conduction::readOn().
type()
const Nom & Operateur::type () const
Renvoie le (nom du) type de l'operateur a creer.
Returns
Nom&
Signification: le nom du type de l'operateur a creer
Contraintes: reference constante
Definition at line 380 of file Operateur.cpp.
{
  return typ;
}
References typ.
typer()
virtual void Operateur::typer () pure virtual
Implemented in Operateur_Conv, Operateur_Diff, Operateur_Div, Operateur_Grad, and Operateur_Evanescence.
Referenced by lire().
Member Data Documentation
le_champ_inco
Ref_Champ_Inc Operateur::le_champ_inco protected
Definition at line 82 of file Operateur.h.
Referenced by ajouter(), associer_champ(), calculer(), completer(), and mon_inconnue().
typ
Motcle Operateur::typ protected
Definition at line 83 of file Operateur.h.
Referenced by ecrire(), lire(), type(), Operateur_Conv::typer(), Operateur_Diff::typer(), and Operateur_Evanescence::typer().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Operateur.h
src/Kernel/Framework/Operateur.cpp