TRUST: h_conv_Champ_P1NC Class Reference
h_conv_Champ_P1NC Class Reference
classe h_conv_Champ_P1NC
#include <h_conv_Champ_P1NC.h>
Public Member Functions
h_conv_Champ_P1NC ()
~h_conv_Champ_P1NC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Champ_P1NC & mon_champ () const
int & temp_ref ()
const int & temp_ref () const
void mettre_a_jour (double)
Mise a jour en temps du champ.
void associer_champ (const Champ_P1NC &)
void me_calculer (double)
void associer_zone_Cl_dis_base (const Zone_Cl_dis_base &)
const Zone_Cl_dis_base & zone_Cl_dis_base () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static h_conv_Champ_P1NC & self_cast (Objet_U &)
static const h_conv_Champ_P1NC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Champ_P1NC mon_champ_
Ref_Zone_Cl_VEF la_zone_Cl_VEF
int temp_ref_
Detailed Description
classe h_conv_Champ_P1NC
Definition at line 38 of file h_conv_Champ_P1NC.h.
Constructor & Destructor Documentation
h_conv_Champ_P1NC::h_conv_Champ_P1NC ()
Definition at line 26 of file h_conv_Champ_P1NC.cpp.
h_conv_Champ_P1NC::~h_conv_Champ_P1NC ()
Definition at line 26 of file h_conv_Champ_P1NC.cpp.
Member Function Documentation
void h_conv_Champ_P1NC::associer_champ (const Champ_P1NC & un_champ)
Definition at line 44 of file h_conv_Champ_P1NC.cpp.
References mon_champ_.
Referenced by VEF_discretisation::h_conv().
{
  mon_champ_= un_champ;
}
void h_conv_Champ_P1NC::associer_zone_Cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis_base) [inline]
Definition at line 87 of file h_conv_Champ_P1NC.h.
References la_zone_Cl_VEF.
Referenced by VEF_discretisation::h_conv().
{
  la_zone_Cl_VEF  = (const Zone_Cl_VEF&) la_zone_Cl_dis_base;
}
Objet_U * h_conv_Champ_P1NC::cree_instance () [static]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 26 of file h_conv_Champ_P1NC.cpp.
int h_conv_Champ_P1NC::duplique () const [virtual]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 26 of file h_conv_Champ_P1NC.cpp.
const Type_info * h_conv_Champ_P1NC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 26 of file h_conv_Champ_P1NC.cpp.
const Type_info * h_conv_Champ_P1NC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 26 of file h_conv_Champ_P1NC.cpp.
void h_conv_Champ_P1NC::me_calculer (double tps) [virtual]
Implements Champ_h_conv.
Definition at line 51 of file h_conv_Champ_P1NC.cpp.
References la_zone_Cl_VEF, mon_champ_, temp_ref(), Champ_base::temps_, Ref_Zone_Cl_VEF::valeur(), and Champ_Don_base::valeurs().
Referenced by mettre_a_jour().
{
  if (temps_ != tps)
    {
//
      mon_champ_->calcul_h_conv(la_zone_Cl_VEF.valeur(),valeurs(),temp_ref());
    }
}
void h_conv_Champ_P1NC::mettre_a_jour (double temps) [inline, virtual]
Mise a jour en temps du champ.
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 80 of file h_conv_Champ_P1NC.h.
References Champ_base::changer_temps(), and me_calculer().
{
  me_calculer(tps);
  changer_temps(tps);
  Champ_Fonc_base::mettre_a_jour(tps);
}
const Champ_P1NC & h_conv_Champ_P1NC::mon_champ () const [inline]
Definition at line 65 of file h_conv_Champ_P1NC.h.
{
  return mon_champ_.valeur();
}
Sortie & h_conv_Champ_P1NC::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 30 of file h_conv_Champ_P1NC.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & h_conv_Champ_P1NC::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 37 of file h_conv_Champ_P1NC.cpp.
{
  return s ;
}
h_conv_Champ_P1NC & h_conv_Champ_P1NC::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 26 of file h_conv_Champ_P1NC.cpp.
const h_conv_Champ_P1NC & h_conv_Champ_P1NC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 26 of file h_conv_Champ_P1NC.cpp.
unsigned h_conv_Champ_P1NC::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 26 of file h_conv_Champ_P1NC.cpp.
int & h_conv_Champ_P1NC::temp_ref () [inline]
Definition at line 70 of file h_conv_Champ_P1NC.h.
References temp_ref_.
Referenced by VEF_discretisation::h_conv(), and me_calculer().
{
  return temp_ref_;
}
const int & h_conv_Champ_P1NC::temp_ref () const [inline]
Definition at line 74 of file h_conv_Champ_P1NC.h.
References temp_ref_.
{
  return temp_ref_;
}
const Zone_Cl_dis_base & h_conv_Champ_P1NC::zone_Cl_dis_base () const
Definition at line 60 of file h_conv_Champ_P1NC.cpp.
References la_zone_Cl_VEF, and Ref_Zone_Cl_VEF::valeur().
{
  return la_zone_Cl_VEF.valeur();
}
Member Data Documentation
const Type_info h_conv_Champ_P1NC::info_obj [static]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 43 of file h_conv_Champ_P1NC.h.
Ref_Zone_Cl_VEF h_conv_Champ_P1NC::la_zone_Cl_VEF [protected]
Definition at line 61 of file h_conv_Champ_P1NC.h.
Referenced by associer_zone_Cl_dis_base(), me_calculer(), and zone_Cl_dis_base().
Ref_Champ_P1NC h_conv_Champ_P1NC::mon_champ_ [protected]
Definition at line 60 of file h_conv_Champ_P1NC.h.
Referenced by associer_champ(), and me_calculer().
int h_conv_Champ_P1NC::temp_ref_ [protected]
Definition at line 62 of file h_conv_Champ_P1NC.h.
Referenced by temp_ref().
The documentation for this class was generated from the following files:
src/VEF/Champs/h_conv_Champ_P1NC.h
src/VEF/Champs/h_conv_Champ_P1NC.cpp