TRUST: Paroi_Knudsen_non_negligeable Class Reference
Paroi_Knudsen_non_negligeable Class Reference
classe Paroi_Knudsen_non_negligeable
Impose un saut de vitesse de paroi dans une equation de type Navier_Stokes
proportionnel au gradient de vitesse transverse.
#include <Paroi_Knudsen_non_negligeable.h>
Public Member Functions
Paroi_Knudsen_non_negligeable ()
~Paroi_Knudsen_non_negligeable ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const DoubleTab & vitesse_paroi () const
const DoubleTab & k () const
int compatible_avec_eqn (const Equation_base &) const override
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Dirichlet_paroi_defilante sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
void completer () override
NE FAIT RIEN
A surcharger dans les classes derivees.
Public Member Functions inherited from Dirichlet_paroi_defilante
Dirichlet_paroi_defilante ()
~Dirichlet_paroi_defilante ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int compatible_avec_eqn (const Equation_base &) const override
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Dirichlet_paroi_defilante sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
void completer () override
NE FAIT RIEN
A surcharger dans les classes derivees.
Public Member Functions inherited from Dirichlet
Dirichlet ()
~Dirichlet () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double val_imp (int i) const
Renvoie la valeur imposee sur la i-eme composante
du champ a la frontiere au temps par defaut du champ_front.
virtual double val_imp (int i, int j) const
Renvoie la valeur imposee sur la (i,j)-eme composante
du champ a la frontiere au temps par defaut du champ_front.
virtual double val_imp_au_temps (double temps, int i) const
Renvoie la valeur imposee sur la i-eme composante
du champ a la frontiere au temps precise.
virtual double val_imp_au_temps (double temps, int i, int j) const
Renvoie la valeur imposee sur la (i,j)-eme composante
du champ a la frontiere au temps precise.
void verifie_ch_init_nb_comp () const override
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
Public Member Functions inherited from Cond_lim_base
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Paroi_Knudsen_non_negligeable & self_cast (Objet_U &)
static const Paroi_Knudsen_non_negligeable & self_cast (const Objet_U &)
Static Public Member Functions inherited from Dirichlet_paroi_defilante
static Objet_U * cree_instance ()
static const Type_info * info ()
static Dirichlet_paroi_defilante & self_cast (Objet_U &)
static const Dirichlet_paroi_defilante & self_cast (const Objet_U &)
Static Public Member Functions inherited from Dirichlet
static const Type_info * info ()
static Dirichlet & self_cast (Objet_U &)
static const Dirichlet & self_cast (const Objet_U &)
Static Public Member Functions inherited from Cond_lim_base
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
Champ_front vitesse_paroi_
Champ_front k_
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Dirichlet_paroi_defilante
static const Type_info info_obj
Static Public Attributes inherited from Dirichlet
static const Type_info info_obj
Static Public Attributes inherited from Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture des champs vitesse_paroi et k.
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a: Cond_lim_base::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a: Cond_lim_base::readOn(Entree&)
Protected Member Functions inherited from Cond_lim_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Cond_lim_base
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Detailed Description
classe Paroi_Knudsen_non_negligeable
Impose un saut de vitesse de paroi dans une equation de type Navier_Stokes
proportionnel au gradient de vitesse transverse.
Definition at line 35 of file Paroi_Knudsen_non_negligeable.h.
Constructor & Destructor Documentation
Paroi_Knudsen_non_negligeable()
Paroi_Knudsen_non_negligeable::Paroi_Knudsen_non_negligeable ()
Definition at line 22 of file Paroi_Knudsen_non_negligeable.cpp.
~Paroi_Knudsen_non_negligeable()
Paroi_Knudsen_non_negligeable::~Paroi_Knudsen_non_negligeable ()
Definition at line 22 of file Paroi_Knudsen_non_negligeable.cpp.
Member Function Documentation
compatible_avec_eqn()
int Paroi_Knudsen_non_negligeable::compatible_avec_eqn (const Equation_base & eqn) const override virtual
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Dirichlet_paroi_defilante sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
Returns
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Reimplemented from Dirichlet_paroi_defilante.
Definition at line 123 of file Paroi_Knudsen_non_negligeable.cpp.
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Hydraulique="Hydraulique";
  Motcle indetermine="indetermine";
  if ( (dom_app==Hydraulique) || (dom_app==indetermine) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
completer()
void Paroi_Knudsen_non_negligeable::completer (void) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Dirichlet_paroi_defilante.
Definition at line 84 of file Paroi_Knudsen_non_negligeable.cpp.
{
  Cerr << "Paroi_Knudsen_non_negligeable::completer" << finl;
  Nom type="Champ_front_fonc_gradient_";
  type += zone_Cl_dis().equation().discretisation().que_suis_je();
// Typage definitif en fonction de la discretisation
  Frontiere_dis_base& fr=le_champ_front.frontiere_dis();
  le_champ_front.typer(type);
  le_champ_front.associer_fr_dis_base(fr);
// Paroi defilante : le champ_front est la vitesse de nombre
// de composantes la dimension du pb ... Est ce utile de dimensionner
// maintenant cela ?
  le_champ_front->fixer_nb_comp(dimension);
// On associe l'inconnue:
  Champ_front_fonc_gradient& ch=ref_cast(Champ_front_fonc_gradient,le_champ_front.valeur());
  ch.associer_ch_inc_base(zone_Cl_dis().equation().inconnue().valeur());
  Cerr << "Paroi_Knudsen_non_negligeable::completer OK" << finl;
}
References Champ_front_fonc_gradient::associer_ch_inc_base(), Champ_front::associer_fr_dis_base(), Cerr, Objet_U::dimension, Equation_base::discretisation(), MorEqn::equation(), finl, Champ_front::frontiere_dis(), Cond_lim_base::le_champ_front, Objet_U::que_suis_je(), ref_cast, Deriv_::typer(), Deriv_Champ_front_base::valeur(), valeur(), and Cond_lim_base::zone_Cl_dis().
cree_instance()
Objet_U * Paroi_Knudsen_non_negligeable::cree_instance () static
Definition at line 22 of file Paroi_Knudsen_non_negligeable.cpp.
duplique()
int Paroi_Knudsen_non_negligeable::duplique () const override virtual
Reimplemented from Dirichlet_paroi_defilante.
Definition at line 22 of file Paroi_Knudsen_non_negligeable.cpp.
get_info()
const Type_info * Paroi_Knudsen_non_negligeable::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Dirichlet_paroi_defilante.
Definition at line 22 of file Paroi_Knudsen_non_negligeable.cpp.
info()
const Type_info * Paroi_Knudsen_non_negligeable::info () static
Definition at line 22 of file Paroi_Knudsen_non_negligeable.cpp.
k()
const DoubleTab & Paroi_Knudsen_non_negligeable::k () const inline
Definition at line 45 of file Paroi_Knudsen_non_negligeable.h.
  {
    return k_.valeurs();
  } ;
References k_, and Champ_front::valeurs().
Referenced by Champ_front_fonc_gradient_VDF::mettre_a_jour().
printOn()
Sortie & Paroi_Knudsen_non_negligeable::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Dirichlet_paroi_defilante.
Definition at line 39 of file Paroi_Knudsen_non_negligeable.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Paroi_Knudsen_non_negligeable::readOn (Entree & s) override protected virtual
Lecture des champs vitesse_paroi et k.
Returns
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Dirichlet_paroi_defilante.
Definition at line 58 of file Paroi_Knudsen_non_negligeable.cpp.
{
  Cerr << "Paroi_Knudsen_non_negligeable::readOn" << finl;
  Motcle mot;
  Motcles les_motcles(3);
  {
    les_motcles[0] = "vitesse_paroi";
    les_motcles[1] = "k";
  }
  int nb_champs_lus=0;
  while (nb_champs_lus<2)
    {
      s >> mot ;
      int rang = les_motcles.search(mot);
      if (rang == 0)
        s >> vitesse_paroi_ ;
      if (rang == 1)
        s >> k_ ;
      nb_champs_lus++;
    }
  le_champ_front.typer("Champ_front_fonc_gradient");
  le_champ_front->fixer_nb_comp(dimension);
  return s;
}
References Cerr, Objet_U::dimension, finl, k_, Cond_lim_base::le_champ_front, Motcles::search(), Deriv_::typer(), and vitesse_paroi_.
self_cast() [1/2]
const Paroi_Knudsen_non_negligeable & Paroi_Knudsen_non_negligeable::self_cast (const Objet_U & r) static
Definition at line 22 of file Paroi_Knudsen_non_negligeable.cpp.
self_cast() [2/2]
Paroi_Knudsen_non_negligeable & Paroi_Knudsen_non_negligeable::self_cast (Objet_U & r) static
Definition at line 22 of file Paroi_Knudsen_non_negligeable.cpp.
taille_memoire()
unsigned Paroi_Knudsen_non_negligeable::taille_memoire () const override virtual
Reimplemented from Dirichlet_paroi_defilante.
Definition at line 22 of file Paroi_Knudsen_non_negligeable.cpp.
vitesse_paroi()
const DoubleTab & Paroi_Knudsen_non_negligeable::vitesse_paroi () const inline
Definition at line 41 of file Paroi_Knudsen_non_negligeable.h.
  {
    return vitesse_paroi_.valeurs();
  };
References Champ_front::valeurs(), and vitesse_paroi_.
Referenced by Champ_front_fonc_gradient_VDF::mettre_a_jour().
Member Data Documentation
info_obj
const Type_info Paroi_Knudsen_non_negligeable::info_obj static
Definition at line 38 of file Paroi_Knudsen_non_negligeable.h.
k_
Champ_front Paroi_Knudsen_non_negligeable::k_
Definition at line 52 of file Paroi_Knudsen_non_negligeable.h.
Referenced by k(), and readOn().
vitesse_paroi_
Champ_front Paroi_Knudsen_non_negligeable::vitesse_paroi_
Definition at line 51 of file Paroi_Knudsen_non_negligeable.h.
Referenced by readOn(), and vitesse_paroi().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Cond_Lim/Paroi_Knudsen_non_negligeable.h
src/ThHyd/Incompressible/Cond_Lim/Paroi_Knudsen_non_negligeable.cpp