TRUST: EDO_Pression_th_VEF_Gaz_Parfait Class Reference
EDO_Pression_th_VEF_Gaz_Parfait Class Reference
classe EDO_Pression_th_VEF_Gaz_Parfait
Cette classe represente l'EDO sur la pression associee au schema de
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VEF et pour les gaz parfaits.
#include <EDO_Pression_th_VEF_Gaz_Parfait.h>
Public Member Functions
EDO_Pression_th_VEF_Gaz_Parfait ()
~EDO_Pression_th_VEF_Gaz_Parfait ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
double resoudre (double) override
Resoud l'EDO.
Public Member Functions inherited from EDO_Pression_th_VEF
~EDO_Pression_th_VEF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
EDO_Pression_th_VEF ()
const Fluide_Quasi_Compressible & le_fluide () const
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Associe les zones a l'EDO.
void completer () override
Complete l'EDO : calcule rho sur les faces.
void calculer_grad (const DoubleTab &, DoubleTab &)
double masse_totale (double P, const DoubleTab &T) override
void mettre_a_jour_CL (double P) override
double getM0 ()
Public Member Functions inherited from EDO_Pression_th_base
EDO_Pression_th_base ()
~EDO_Pression_th_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_fluide (const Fluide_Quasi_Compressible &)
Associe le fluide a l'EDO.
virtual void completer ()=0
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void mettre_a_jour_CL (double)=0
virtual double masse_totale (double P, const DoubleTab &T)=0
virtual double resoudre (double)=0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static EDO_Pression_th_VEF_Gaz_Parfait & self_cast (Objet_U &)
static const EDO_Pression_th_VEF_Gaz_Parfait & self_cast (const Objet_U &)
Static Public Member Functions inherited from EDO_Pression_th_VEF
static const Type_info * info ()
static EDO_Pression_th_VEF & self_cast (Objet_U &)
static const EDO_Pression_th_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from EDO_Pression_th_base
static const Type_info * info ()
static EDO_Pression_th_base & self_cast (Objet_U &)
static const EDO_Pression_th_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from EDO_Pression_th_VEF
static const Type_info info_obj
Static Public Attributes inherited from EDO_Pression_th_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from EDO_Pression_th_VEF
Ref_Zone_VEF la_zone
Ref_Zone_Cl_dis la_zone_Cl
double M0
la masse totale initiale
Protected Attributes inherited from EDO_Pression_th_base
Ref_Fluide_Quasi_Compressible le_fluide_
Detailed Description
classe EDO_Pression_th_VEF_Gaz_Parfait
Cette classe represente l'EDO sur la pression associee au schema de
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VEF et pour les gaz parfaits.
Definition at line 32 of file EDO_Pression_th_VEF_Gaz_Parfait.h.
Constructor & Destructor Documentation
EDO_Pression_th_VEF_Gaz_Parfait()
EDO_Pression_th_VEF_Gaz_Parfait::EDO_Pression_th_VEF_Gaz_Parfait ()
Definition at line 29 of file EDO_Pression_th_VEF_Gaz_Parfait.cpp.
~EDO_Pression_th_VEF_Gaz_Parfait()
EDO_Pression_th_VEF_Gaz_Parfait::~EDO_Pression_th_VEF_Gaz_Parfait ()
Definition at line 29 of file EDO_Pression_th_VEF_Gaz_Parfait.cpp.
Member Function Documentation
cree_instance()
Objet_U * EDO_Pression_th_VEF_Gaz_Parfait::cree_instance () static
Definition at line 29 of file EDO_Pression_th_VEF_Gaz_Parfait.cpp.
duplique()
int EDO_Pression_th_VEF_Gaz_Parfait::duplique () const override virtual
Implements Objet_U.
Definition at line 29 of file EDO_Pression_th_VEF_Gaz_Parfait.cpp.
get_info()
const Type_info * EDO_Pression_th_VEF_Gaz_Parfait::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from EDO_Pression_th_VEF.
Definition at line 29 of file EDO_Pression_th_VEF_Gaz_Parfait.cpp.
info()
const Type_info * EDO_Pression_th_VEF_Gaz_Parfait::info () static
Definition at line 29 of file EDO_Pression_th_VEF_Gaz_Parfait.cpp.
printOn()
Sortie & EDO_Pression_th_VEF_Gaz_Parfait::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from EDO_Pression_th_VEF.
Definition at line 31 of file EDO_Pression_th_VEF_Gaz_Parfait.cpp.
{
  os <<que_suis_je()<< finl;
  return os;
}
References finl, and Objet_U::que_suis_je().
readOn()
Entree & EDO_Pression_th_VEF_Gaz_Parfait::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from EDO_Pression_th_VEF.
Definition at line 37 of file EDO_Pression_th_VEF_Gaz_Parfait.cpp.
{
  return is;
}
resoudre()
double EDO_Pression_th_VEF_Gaz_Parfait::resoudre (double Pth_n) override virtual
Resoud l'EDO.
Returns
double
Signification: La nouvelle valeur de la pression
Contraintes:
< Pth constant
< T(n+1)
< T(n)
< EDO
< n+1/2
< copie de rho
< Conservation masse (WEC mars 2008)
< copier uniquement la structure
Implements EDO_Pression_th_base.
Definition at line 57 of file EDO_Pression_th_VEF_Gaz_Parfait.cpp.
{
  int traitPth = le_fluide_->getTraitementPth();
  if (traitPth==2)  //!< Pth constant
    return Pth_n;
  double present = le_fluide_->vitesse()->equation().schema_temps().temps_courant();
  double dt      = le_fluide_->vitesse()->equation().schema_temps().pas_de_temps();
  double futur   = present+dt;
  const DoubleTab& tempnp1 = le_fluide_->inco_chaleur()->valeurs(futur);    //!< T(n+1)
  const DoubleTab& tempn = le_fluide_->inco_chaleur()->valeurs(present);    //!< T(n)
  int nb_faces = la_zone->nb_faces();
  double Pth=0;
  const Zone_VEF& zone_vef = ref_cast(Zone_VEF, la_zone.valeur());
  if (traitPth == 0)   //!< EDO
    {
      const DoubleTab& tab_rho = le_fluide_->masse_volumique().valeurs();       //!< n+1/2
      const double rho_moy = Champ_P1NC::calculer_integrale_volumique(zone_vef, tab_rho, FAUX_EN_PERIO);
      DoubleVect tmp(tab_rho); //!< copie de rho
      assert(tmp.size() == nb_faces);
      const double invdt = 1. / dt;
      for (int i = 0; i < nb_faces; i++)
        tmp[i] *= (tempnp1[i] - tempn[i]) / tempnp1[i] * invdt;
      double S = Champ_P1NC::calculer_integrale_volumique(zone_vef, tmp, FAUX_EN_PERIO);
//
      S /= rho_moy;
// double Pth = (Pth_n + S*dt/V);
// double Pth = Pth_n/(1- S*dt);
      Pth = Pth_n/(1- S*dt);
// test pour faire apparaitre la difference sur Pth
// Pth *= 1e10;
    }
  else if (traitPth == 1)   //!< Conservation masse (WEC mars 2008)
    {
// On veut Masse(n+1) - Masse(n) = dt * Debits_aux_bords
// or Masse = Pth / R * sum(Vi/Ti) en volume
// et Debit = Pth / R * sum(Sj.Uj/Tj) aux faces Dirichlet
// Donc si on note masse_n = sum(Vi/Ti(n))
// debit_u_imp = sum(Sj.Uj(impose)/Tj(n+1)) pour les vitesses imposees
// et debit_rho_u_imp = sum(Sj.Uj(impose)/Tj(n+1)) pour les rho_u imposes
// ou U(impose) = (rho.U)(impose) / rho(Pth(n),T(n+1))
// il faut Pth(n+1)*masse_np1 - Pth(n)*masse_n = Pth(n+1) * debit_u_imp * dt
// + Pth(n) * debit_rho_u_imp * dt
// Attention il faudrait prendre en compte les porosites dans les integrales !!!
      double debit_u_imp=0,debit_rho_u_imp=0;
// On veut que rho_np1 soit calcule avec T(n+1) et Pth_n pour les CLs en rho_u impose
      le_fluide_->calculer_masse_volumique();
// Calcul de masse_n et masse_np1
      DoubleVect tmp;
      tmp.copy(tempn, ArrOfDouble::NOCOPY_NOINIT); //!< copier uniquement la structure
      for (int i = 0; i < nb_faces; i++)
        tmp[i] = 1. / tempn[i];
      const double masse_n = Champ_P1NC::calculer_integrale_volumique(zone_vef, tmp, FAUX_EN_PERIO);
      for (int i = 0; i < nb_faces; i++)
        tmp[i] = 1. / tempnp1[i];
      const double masse_np1 = Champ_P1NC::calculer_integrale_volumique(zone_vef, tmp, FAUX_EN_PERIO);
// Calcul de debit_u_imp et debit_rho_u_imp
      for (int n_bord=0; n_bord<la_zone->nb_front_Cl(); n_bord++)
        {
          const Cond_lim_base& la_cl = la_zone_Cl->les_conditions_limites(n_bord).valeur();
          if (sub_type(Dirichlet, la_cl))
            {
              const Dirichlet& diri=ref_cast(Dirichlet,la_cl);
              const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
              int ndeb = la_front_dis.num_premiere_face();
              int nfin = ndeb + la_front_dis.nb_faces();
              for (int face=ndeb; face<nfin; face++)
                {
                  double debit_v=0;
                  for (int d=0; d<dimension; d++)
                    debit_v += la_zone->face_normales(face,d)*diri.val_imp_au_temps(futur,face-ndeb,d)/tempnp1(face);
                  int n0 = la_zone->face_voisins(face,0);
                  if (n0 == -1)
                    debit_v=-debit_v;
                  if (sub_type(Frontiere_ouverte_rho_u_impose, la_cl))
                    debit_rho_u_imp+=debit_v;
                  else
                    debit_u_imp+=debit_v;
                }
            }
          else if (sub_type(Neumann_sortie_libre, la_cl))
            {
              Cerr<<la_cl.que_suis_je()<<" est incompatible avec le traitement conservation_masse."<<finl;
              exit();
            }
        }
// On fait la somme sur les procs
      debit_u_imp=mp_sum(debit_u_imp);
      debit_rho_u_imp=mp_sum(debit_rho_u_imp);
// Calcul de Pth(n+1)
      Pth = Pth_n * (masse_n - dt*debit_rho_u_imp) / (masse_np1 + dt*debit_u_imp);
    }
  return Pth;
}
References Champ_P1NC::calculer_integrale_volumique(), Fluide_Dilatable_base::calculer_masse_volumique(), Cerr, TRUSTVect< _TYPE_ >::copy(), Objet_U::dimension, Process::exit(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), FAUX_EN_PERIO, finl, Cond_lim_base::frontiere_dis(), Fluide_Dilatable_base::getTraitementPth(), Fluide_Dilatable_base::inco_chaleur(), EDO_Pression_th_VEF::la_zone, EDO_Pression_th_VEF::la_zone_Cl, EDO_Pression_th_base::le_fluide_, Zone_Cl_dis::les_conditions_limites(), Milieu_base::masse_volumique(), Process::mp_sum(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Array_base::NOCOPY_NOINIT, Front_VF::num_premiere_face(), Objet_U::que_suis_je(), ref_cast, TRUSTVect< _TYPE_ >::size(), sub_type, Dirichlet::val_imp_au_temps(), Deriv_Cond_lim_base::valeur(), Ref_Zone_VEF::valeur(), Champ::valeurs(), Champ_Inc::valeurs(), and Fluide_Dilatable_base::vitesse().
self_cast() [1/2]
const EDO_Pression_th_VEF_Gaz_Parfait & EDO_Pression_th_VEF_Gaz_Parfait::self_cast (const Objet_U & r) static
Definition at line 29 of file EDO_Pression_th_VEF_Gaz_Parfait.cpp.
self_cast() [2/2]
EDO_Pression_th_VEF_Gaz_Parfait & EDO_Pression_th_VEF_Gaz_Parfait::self_cast (Objet_U & r) static
Definition at line 29 of file EDO_Pression_th_VEF_Gaz_Parfait.cpp.
taille_memoire()
unsigned EDO_Pression_th_VEF_Gaz_Parfait::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 29 of file EDO_Pression_th_VEF_Gaz_Parfait.cpp.
Member Data Documentation
info_obj
const Type_info EDO_Pression_th_VEF_Gaz_Parfait::info_obj static
Definition at line 34 of file EDO_Pression_th_VEF_Gaz_Parfait.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VEF/EDO_Pression_th_VEF_Gaz_Parfait.h
src/ThHyd/Dilatable/Quasi_Compressible/VEF/EDO_Pression_th_VEF_Gaz_Parfait.cpp