TRUST: Zones Class Reference
Zones Class Reference
Classe Zones
Cette classe represente une liste de Zone.
#include <Zones.h>
Public Member Functions
Zones ()
~Zones ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_domaine (const Domaine &)
Associe toutes les zones de la liste au
domaine specifie.
void comprimer ()
On agglomere les Zones de meme type.
void reordonner ()
Reordonne les elements du maillage.
On appelle Zone::reordonner() sur chaque
zone de la liste.
void merge ()
Merge all the zones of my processor in a single one
is not tested when the zones are dispatched on multiple processors!
Public Member Functions inherited from List_Zone
List_Zone ()
~List_Zone ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
List_Zone (const Zone &t)
List_Zone (const List_Zone &t)
Zone & operator[] (int)
const Zone & operator[] (int) const
Zone & operator[] (const Nom &)
const Zone & operator[] (const Nom &) const
Zone & operator() (int i)
const Zone & operator() (int i) const
Zone & operator() (const Nom &n)
const Zone & operator() (const Nom &n) const
Zone & valeur ()
const Zone & valeur () const
List_Zone & operator= (const Zone &t)
Zone * operator-> ()
List_Zone & operator= (const List_Zone &)
List_Zone & add (const List_Zone &)
Zone & add (const Zone &)
List_Zone & inserer (const List_Zone &)
Zone & inserer (const Zone &)
void supprimer ()
List_Zone & operator+= (const List_Zone &)
List_Zone & operator+= (const Zone &)
Zone & add_if_not (const Zone &)
Zone & add_if_not (const char *const)
List_Zone & search (const Zone &) const
List_Zone & search (const char *const) const
List_Zone & suivant ()
const List_Zone & suivant () const
const List_Zone & dernier () const
List_Zone & dernier ()
List_Zone & operator-= (const Zone &)
int est_egal_a (const Objet_U &) const override
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
int contient (const Zone &) const
int contient (const char *const) const
int rang (const Zone &) const
void suppr (const Zone &)
Public Member Functions inherited from liste
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
liste ()
Constructeur par defaut
Construit une liste vide.
liste (const liste &)
Constructeur
Ajoute les elements contenus dans la liste passe en parametre.
liste (const Objet_U &)
Constructeur
Construit une liste singleton.
~liste () override
Destructeur de liste.
int size () const
Renvoie la taille de la liste
Une liste vide est de taille nulle.
int rang (const char *const) const
Renvoie le rang d'une chaine de caracteres contenue dans la liste
Recherche un Objet_U de Nom ch.
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
void suppr (const char *const)
Supprime l'Objet de Nom ch contenu dans la liste.
int est_vide () const
Teste si la liste est vide.
int est_dernier () const
Teste si la liste comporte des elements suivants ou non.
Retourne 1 si la liste est vide.
void vide ()
Vide la liste.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zones & self_cast (Objet_U &)
static const Zones & self_cast (const Objet_U &)
Static Public Member Functions inherited from List_Zone
static Objet_U * cree_instance ()
static const Type_info * info ()
static List_Zone & self_cast (Objet_U &)
static const List_Zone & self_cast (const Objet_U &)
Static Public Member Functions inherited from liste
static Objet_U * cree_instance ()
static const Type_info * info ()
static liste & self_cast (Objet_U &)
static const liste & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from List_Zone
static const Type_info info_obj
Static Public Attributes inherited from liste
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit toutes les zones de la liste sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les zones a partir d'un flot d'entree.
Protected Member Functions inherited from List_Zone
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
int est_egal_a (const List_Zone &) const
Protected Member Functions inherited from liste
Sortie & printOn (Sortie &x) const override
Ecriture d'une liste sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une liste sur un flot d'entree.
Objet_U & operator() (int)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Objet_U & operator() (int) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Objet_U & operator() (const Nom &)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Objet_U & operator() (const Nom &) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Objet_U & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Objet_U & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
liste & operator+= (const Objet_U &)
Ajoute un Objet_U a la fin de la liste.
liste & operator+= (const liste &)
Ajoute une list d'Objet_U a la fin de la liste.
liste & operator-= (const Objet_U &)
Supprime un Objet_U de la liste
Affiche un message d'erreur si l'objet n'est pas trouve.
const liste & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
liste & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
Objet_U * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
const Objet_U * operator-> () const
Retourne un pointeur sur l'Objet_U premier element de la liste.
Objet_U & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Objet_U & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Objet_U & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Objet_U & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Objet_U & add (const Objet_U &)
Ajout d'un Objet_U a la liste.
Objet_U & add_deplace (DerObjU &)
Ajout d'un Objet_U a la liste
to_add est libere en sortie.
Objet_U & inserer (const Objet_U &)
Insertion d'un Objet_U dans la liste.
liste & add (const liste &)
Ajout d'une liste a la liste.
liste & inserer (const liste &)
Insertion d'une liste
NON CODE - SORT SYSTEMATIQUEMENT EN ERREUR.
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Objet_U & add_if_not (const Objet_U &)
Ajout d'un Objet_U a la liste ssi il n'existe pas deja.
liste & search (const Objet_U &) const
Recherche d'un Objet_U dans la liste.
liste & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
int contient (const Objet_U &) const
Verifie si un Objet_U appartient ou non a la liste.
int rang (const Objet_U &) const
Renvoie le rang d'un Objet_U dans la liste.
void suppr (const Objet_U &)
Supprime un Objet_U contenu dans la liste.
liste & operator= (const liste &)
Operateur d'affectation de liste.
const liste & dernier () const
Renvoie le dernier element de la liste.
liste & dernier ()
Renvoie le dernier element de la liste.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from liste
DerObjU data
liste * suivant_
Detailed Description
Classe Zones
Cette classe represente une liste de Zone.
Definition at line 32 of file Zones.h.
Constructor & Destructor Documentation
Zones()
Zones::Zones ()
Definition at line 20 of file Zones.cpp.
~Zones()
Zones::~Zones ()
Definition at line 20 of file Zones.cpp.
Member Function Documentation
associer_domaine()
void Zones::associer_domaine (const Domaine & un_domaine)
Associe toutes les zones de la liste au
domaine specifie.
Definition at line 76 of file Zones.cpp.
{
  LIST_CURSEUR(Zone) curseur(*this);;;
  while(curseur)
    {
      curseur->associer_domaine(un_domaine);
      ++curseur;
    }
}
References LIST_CURSEUR.
Referenced by Scatter::lire_domaine(), and Domaine::readOn().
comprimer()
void Zones::comprimer ()
On agglomere les Zones de meme type.
Definition at line 128 of file Zones.cpp.
{
  if (Process::nproc() > 1)
    {
      Cerr << "Error in Zones::comprimer() : compression prohibited in parallel mode" << finl;
      exit();
    }
  Cerr << "Compressing objects of type Zone in progress... " << finl;
  IntVect fait(size());
  int rang1=0, rang2=0;
  {
    LIST_CURSEUR(Zone) curseur(*this);;;
    while(curseur)
      {
        curseur->comprimer();
        ++curseur;
      }
  }
  LIST_CURSEUR(Zone) curseur1(*this);;;
  while(curseur1)
    {
      if (!fait(rang1) )
        {
          fait(rang1)=1;
          Zone& zone1=curseur1.valeur();
          rang2=rang1;
          LIST_CURSEUR(Zone) curseur2(curseur1.list());;;
          while(curseur2)
            {
              if (!fait(rang2) )
                {
                  Zone& zone2=curseur2.valeur();
                  if ((zone2.type_elem()->que_suis_je())
                      ==
                      (zone1.type_elem()->que_suis_je()) )
                    {
                      Nom nom1=zone1.le_nom();
                      Nom nom2=zone2.le_nom();
                      Nom nom=nom1;
                      Cerr << "agglomeration of Zones "<< nom1
                           << " and " << nom2 << finl;;
                      fait(rang2)=1;
                      if( (nom1.longueur()+nom2.longueur()) < 20 )
{
                          nom+="_";
                          nom+=nom2;
                        }
                      zone1.nommer(nom);
                      int sz1=zone1.les_elems().dimension(0);
                      int sz2=zone2.les_elems().dimension(0);
                      int nb_ccord=zone1.les_elems().dimension(1);
                      IntTab& elems1=zone1.les_elems();
                      IntTab& elems2=zone2.les_elems();
                      elems1.resize(sz1+sz2, nb_ccord);
                      for(int i=0; i<sz2; i++)
                        for(int j=0; j<nb_ccord; j++)
                          elems1(sz1+i,j)=elems2(i,j);
                      zone2.faces_bord().associer_zone(zone1);
                      zone1.faces_bord().add(zone2.faces_bord());
                      zone2.faces_joint().associer_zone(zone1);
                      zone1.faces_joint().add(zone2.faces_joint());
                      zone2.faces_raccord().associer_zone(zone1);
                      zone1.faces_raccord().add(zone2.faces_raccord());
                      zone2.faces_int().associer_zone(zone1);
                      zone1.faces_int().add(zone2.faces_int());
                      elems2.resize(0);
                      zone1.comprimer();
                    }
                }
              ++curseur2;
              rang2++;
            }
        }
      ++curseur1;
      ++rang1;
    }
  curseur1=*this;
  while(curseur1)
    {
      if (curseur1->les_elems().size()==0)
        {
// Cerr << &(curseur1.valeur()) << finl;
          suppr(curseur1.valeur());
          curseur1=*this;
        }
      else
        ++curseur1;
    }
  (*this).valeur().invalide_octree();
  Cerr << "Zones::comprimer() - End" << finl;
}
References List_Bord::add(), List_Faces_Interne::add(), List_Joint::add(), List_Raccord::add(), Bords::associer_zone(), Faces_Internes::associer_zone(), Joints::associer_zone(), Raccords::associer_zone(), Cerr, Zone::comprimer(), TRUSTTab< _TYPE_ >::dimension(), Process::exit(), Zone::faces_bord(), Zone::faces_int(), Zone::faces_joint(), Zone::faces_raccord(), finl, Zone::le_nom(), Zone::les_elems(), LIST_CURSEUR, Nom::longueur(), Zone::nommer(), Process::nproc(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_ >::resize(), liste::size(), List_Zone::suppr(), and Zone::type_elem().
Referenced by Domaine::comprimer().
cree_instance()
Objet_U * Zones::cree_instance () static
Definition at line 20 of file Zones.cpp.
duplique()
int Zones::duplique () const override virtual
Reimplemented from List_Zone.
Definition at line 20 of file Zones.cpp.
get_info()
const Type_info * Zones::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from List_Zone.
Definition at line 20 of file Zones.cpp.
info()
const Type_info * Zones::info () static
Definition at line 20 of file Zones.cpp.
merge()
void Zones::merge ()
Merge all the zones of my processor in a single one
is not tested when the zones are dispatched on multiple processors!
Definition at line 239 of file Zones.cpp.
{
  LIST_CURSEUR(Zone) curseur(*this);;;
  Zone& zone1=curseur.valeur();
  LIST_CURSEUR(Zone) curseur2(curseur.list());;;
  while(!curseur2.list().est_dernier())
    {
      Zone& zone2=curseur2.list().suivant().valeur();
      assert(zone1.le_nom() == zone2.le_nom());
      int sz1=zone1.les_elems().dimension(0);
      int sz2=zone2.les_elems().dimension(0);
      int nb_coord=zone1.les_elems().dimension(1);
      IntTab& elems1=zone1.les_elems();
      IntTab& elems2=zone2.les_elems();
      elems1.resize(sz1+sz2, nb_coord);
      for(int i=0; i<sz2; i++)
        for(int j=0; j<nb_coord; j++)
          elems1(sz1+i,j)=elems2(i,j);
      zone2.faces_bord().associer_zone(zone1);
      zone1.faces_bord().add(zone2.faces_bord());
      zone2.faces_joint().associer_zone(zone1);
      zone1.faces_joint().add(zone2.faces_joint());
      zone2.faces_raccord().associer_zone(zone1);
      zone1.faces_raccord().add(zone2.faces_raccord());
      zone2.faces_int().associer_zone(zone1);
      zone1.faces_int().add(zone2.faces_int());
      elems2.resize(0);
      zone1.correct_type_of_borders_after_merge();
      zone1.comprimer();
      zone1.comprimer_joints();
      curseur2.list().supprimer();
    }
  (*this).valeur().invalide_octree();
}
References List_Bord::add(), List_Faces_Interne::add(), List_Joint::add(), List_Raccord::add(), Bords::associer_zone(), Faces_Internes::associer_zone(), Joints::associer_zone(), Raccords::associer_zone(), Zone::comprimer(), Zone::comprimer_joints(), Zone::correct_type_of_borders_after_merge(), TRUSTTab< _TYPE_ >::dimension(), Zone::faces_bord(), Zone::faces_int(), Zone::faces_joint(), Zone::faces_raccord(), Zone::le_nom(), Zone::les_elems(), LIST_CURSEUR, and TRUSTTab< _TYPE_ >::resize().
Referenced by Scatter::mergeDomains().
printOn()
Sortie & Zones::printOn (Sortie & s) const override protected virtual
Ecrit toutes les zones de la liste sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from List_Zone.
Definition at line 36 of file Zones.cpp.
{
  return LIST(Zone)::printOn(s) ;
}
References LIST, and printOn().
Referenced by printOn().
readOn()
Entree & Zones::readOn (Entree & s) override protected virtual
Lit les zones a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from List_Zone.
Definition at line 56 of file Zones.cpp.
{
  return LIST(Zone)::readOn(s) ;
}
References LIST, and readOn().
Referenced by readOn().
reordonner()
void Zones::reordonner ()
Reordonne les elements du maillage.
On appelle Zone::reordonner() sur chaque
zone de la liste.
Definition at line 103 of file Zones.cpp.
{
  LIST_CURSEUR(Zone) curseur(*this);;;
  while(curseur)
    {
      curseur->reordonner();
      ++curseur;
    }
}
References LIST_CURSEUR.
Referenced by Domaine::reordonner().
self_cast() [1/2]
const Zones & Zones::self_cast (const Objet_U & r) static
Definition at line 20 of file Zones.cpp.
self_cast() [2/2]
Zones & Zones::self_cast (Objet_U & r) static
Definition at line 20 of file Zones.cpp.
taille_memoire()
unsigned Zones::taille_memoire () const override virtual
Reimplemented from List_Zone.
Definition at line 20 of file Zones.cpp.
Member Data Documentation
info_obj
const Type_info Zones::info_obj static
Definition at line 34 of file Zones.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Zones.h
src/Kernel/Geometrie/Zones.cpp