TRUST: OctreeFloor Class Reference
OctreeFloor Class Reference
Classe OctreeFloor.
#include <Octree.h>
Public Member Functions
OctreeFloor (Octree *mon_pere, const ArrOfInt &val, const OctreeLoc &loc)
void construire (Octree *, const ArrOfInt &, const OctreeLoc &)
int rang_elem_loc (const OctreeLoc &, double x, double y=0, double z=0) const override
int rang_elem_depuis_loc (const OctreeLoc &, int prems, double x, double y=0, double z=0) const override
Sortie & printOn (Sortie &is) const override
Appelle Octree::printOn(Sortie&)
et ecrit le numero des elements sur le
flot de sortie.
Entree & readOn (Entree &is) override
Simple appel a: Octree::readOn(Entree&)
int taille () const override
Renvoie la taille de l'octree.
Public Member Functions inherited from Octree
Octree ()
virtual ~Octree ()
Destructeur: appelle Octree::detruire().
Octree (const Octree &)
Octree (int n, Octree *mon_pere, const ArrOfInt &val, const OctreeLoc &loc)
virtual int rang_elem_loc (const OctreeLoc &, double x, double y=0, double z=0) const
virtual int rang_elem_depuis_loc (const OctreeLoc &, int prems, double x, double y=0, double z=0) const
virtual const Zone & zone () const
Renvoie une reference sur la zone associe a l'octree.
void construire (int, const ArrOfInt &, const OctreeLoc &, Octree *p=0)
int niveau () const
virtual int taille () const
Renvoie la taille de l'octree.
virtual Sortie & printOn (Sortie &is) const
virtual Entree & readOn (Entree &is)
NE FAIT RIEN.
Protected Attributes
ArrOfInt num_elem
ArrOfDouble pos
Tableau de travail.
Protected Attributes inherited from Octree
Octree ** les_octrees
Octree * pere
Additional Inherited Members
Static Public Member Functions inherited from Octree
static int nombre_d_octrees ()
Renvoie le nombre d'octree.
Protected Member Functions inherited from Octree
void detruire ()
Detruit l'octree.
Methode appelee par le destructeur.
void ranger_elem_1D (ArrOfInt &, int, int, int, const DoubleTab &, const IntTab &, ArrOfInt &, IntVects &, double)
void ranger_elem_2D (ArrOfInt &, int, int, int, const DoubleTab &, const IntTab &, ArrOfInt &, IntVects &, double, double)
void ranger_elem_3D (ArrOfInt &, int, int, int, const DoubleTab &, const IntTab &, ArrOfInt &, IntVects &, double, double, double)
double get_epsilon () const
Detailed Description
Classe OctreeFloor.
Definition at line 154 of file Octree.h.
Constructor & Destructor Documentation
OctreeFloor()
OctreeFloor::OctreeFloor (Octree * mon_pere, const ArrOfInt & val, const OctreeLoc & loc) inline
Definition at line 159 of file Octree.h.
  {
    pos.resize_array(Objet_U::dimension);
    construire(mon_pere, val, loc);
  }
References construire(), Objet_U::dimension, pos, and TRUSTArray< _TYPE_ >::resize_array().
Referenced by taille().
Member Function Documentation
construire()
void OctreeFloor::construire (Octree * pe, const ArrOfInt & Tab, const OctreeLoc & loc)
Definition at line 1734 of file Octree.cpp.
{
  static int nb_octreefloor=0;
  nb_octreefloor++;
  assert(pe!=0);
  pere=pe;
  les_octrees=0;
  num_elem=Tab;
// Ajout B.M: tri des elements dans l'ordre croissant de l'indice local.
// Ainsi, lors des recherches de sommets ou faces de joint, on tombe
// sur l'element reel, pas l'element virtuel
  num_elem.ordonne_array();
}
References Octree::les_octrees, num_elem, TRUSTArray< _TYPE_ >::ordonne_array(), and Octree::pere.
Referenced by OctreeFloor().
printOn()
Sortie & OctreeFloor::printOn (Sortie & os) const override virtual
Appelle Octree::printOn(Sortie&)
et ecrit le numero des elements sur le
flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Octree.
Definition at line 137 of file Octree.cpp.
{
  Octree::printOn(os);
  return os << num_elem << finl;
}
References finl, num_elem, and Octree::printOn().
rang_elem_depuis_loc()
int OctreeFloor::rang_elem_depuis_loc (const OctreeLoc & loc, int prems, double x, double y = 0, double z = 0) const override virtual
Returns
int
Signification:
Contraintes:
Reimplemented from Octree.
Definition at line 1680 of file Octree.cpp.
{
  int sz=num_elem.size_array();
  int element=-1;
  const Elem_geom& elemgeom=zone().type_elem();
  pos[0]=x;
  if(Objet_U::dimension>1) pos[1]=y;
  if(Objet_U::dimension>2) pos[2]=z;
  int trouve=0;
  int ielem=0;
  while((ielem < sz) && (trouve==0))
    {
      if(elemgeom.contient(pos,num_elem[ielem]))
        {
          element=num_elem[ielem];
          if(element >= prems)
            trouve=1;
          else
            ielem++;
        }
      else
        ielem++;
    }
  if(ielem>=sz)
    {
      element=-1;
    }
  return element;
}
References Elem_geom::contient(), Objet_U::dimension, num_elem, pos, TRUSTArray< _TYPE_ >::size_array(), Zone::type_elem(), and Octree::zone().
rang_elem_loc()
int OctreeFloor::rang_elem_loc (const OctreeLoc & loc, double x, double y = 0, double z = 0) const override virtual
Returns
int
Signification:
Contraintes:
Reimplemented from Octree.
Definition at line 1623 of file Octree.cpp.
{
  int sz=num_elem.size_array();
  int element=-1;
  const Elem_geom& elemgeom=zone().type_elem();
  pos[0]=x;
  if(Objet_U::dimension>1) pos[1]=y;
  if(Objet_U::dimension>2) pos[2]=z;
  for (int ielem = 0; ielem < sz; ielem++)
    {
      if(elemgeom.contient(pos,num_elem[ielem]))
        {
          element=num_elem[ielem];
          break;
        }
      else
        {
// Process::Journal() << "PAS TROUVE !!: " <<  finl;
        }
    }
  return element;
}
References Elem_geom::contient(), Objet_U::dimension, num_elem, pos, TRUSTArray< _TYPE_ >::size_array(), Zone::type_elem(), and Octree::zone().
readOn()
Entree & OctreeFloor::readOn (Entree & is) override virtual
Simple appel a: Octree::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Octree.
Definition at line 158 of file Octree.cpp.
{
  return Octree::readOn(is);
}
References Octree::readOn().
taille()
int OctreeFloor::taille () const override virtual
Renvoie la taille de l'octree.
Returns
unsigned
Signification: la taille de l'octree
Contraintes:
Reimplemented from Octree.
Definition at line 1763 of file Octree.cpp.
{
  return sizeof(OctreeFloor)+num_elem.size_array()*sizeof(int);
}
References num_elem, OctreeFloor(), and TRUSTArray< _TYPE_ >::size_array().
Member Data Documentation
num_elem
ArrOfInt OctreeFloor::num_elem protected
Definition at line 172 of file Octree.h.
Referenced by construire(), printOn(), rang_elem_depuis_loc(), rang_elem_loc(), and taille().
pos
ArrOfDouble OctreeFloor::pos mutable protected
Tableau de travail.
Definition at line 173 of file Octree.h.
Referenced by OctreeFloor(), rang_elem_depuis_loc(), and rang_elem_loc().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Octree.h
src/Kernel/Geometrie/Octree.cpp