TRUST: DomaineCutter Class Reference
DomaineCutter Class Reference
Classe outil permettant de generer des sous-domaines pour un calcul parallele
a partir d'un domaine de depart (domaine_global) et d'un tableau de decoupage
des elements de ce domaine (elem_part).
Voir aussi Partitionneur_base.
#include <DomaineCutter.h>
Public Member Functions
DomaineCutter ()
Constructeur par defaut (structure vide)
~DomaineCutter ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void initialiser (const Domaine &domaine_global, const IntVect &elem_part, const int nb_parts, const int epaisseur_joint, const Noms &bords_periodiques, const int permissif=0)
Prepare les structures de donnees pour la construction
des sous-domaines en fonction d'un decoupage fourni dans elem_part.
Parametre: domaine_global
Signification: le domaine a decouper (doit avoir une zone). On prend une ref
a ce domaine (il doit donc rester valide).
Parametre: elem_part
Signification: pour chaque element, numero du sous-domaine auquel il appartient,
avec 0 <= elem_part[i] < nb_parts. Attention, on prend une ref a ce tableau, on
ne fait pas une copie local. Le tableau doit continuer a exister jusqu'a ce qu'on
a fini d'utiliser DomaineCutter.
Parametre: nb_parts
Signification: nombre total de sous-domaines
Parametre: les_faces
Parametre: epaisseur_joint.
void reset ()
annule toutes les references et vide les tableaux
void construire_sous_domaine (const int part, DomaineCutter_Correspondance &correspondance_, Domaine &sous_domaine_, const Static_Int_Lists *som_raccord=NULL) const
Remplit la structure "correspondance" et le "sous_domaine"
pour la partie "part". On cherche les sommets qui appartiennent a la sous-partie,
on calcule les tableaux de renumerotation des sommets et des elements entre numero
global et numero local (structure correspondance), on remplit les structures de
sous_domaine (sommets, elements, frontieres, joints, etc).
Attention: sous_domaine doit etre un objet vierge (ne pas contenir de zone)
void construire_sous_domaine (const int part, Domaine &sous_domaine_) const
void ecrire_zones (const Nom &basename, const Decouper::ZonesFileOutputType format, IntVect &elem_part, const int reorder, const Static_Int_Lists *som_raccord=NULL)
Generation de tous les sous-domaines du calcul et ecriture sur disque des
fichiers basename_000n.Zones pour 0 <= n < nb_parties_.
Si des "sous-zones" sont definies (dans le champ domaine.ss_zones()),
on genere aussi un fichier par sous-zone.
const Noms & bords_internes () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static DomaineCutter & self_cast (Objet_U &)
static const DomaineCutter & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Appel invalide. exit.
Entree & readOn (Entree &) override
Appel invalide. exit.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void construire_faces_bords_ssdom (const ArrOfInt &liste_inverse_sommets, const int partie, Zone &zone_partie) const
void construire_faces_raccords_ssdom (const ArrOfInt &liste_inverse_sommets, const int partie, Zone &zone_partie) const
Constructions des raccords de la sous_partie a partir des raccords
du domaine global.
Les Raccord_local_homogene sont transformes en Raccord_distant_homogene.
void construire_faces_internes_ssdom (const ArrOfInt &liste_inverse_sommets, const int partie, Zone &zone_partie) const
void construire_sommets_joints_ssdom (const ArrOfInt &liste_sommets, const ArrOfInt &liste_inverse_sommets, const int partie, const Static_Int_Lists *som_raccord, Zone &zone_partie) const
Creation des joints et construction des listes et des
tableaux de sommets joints pour tous les joints de
la partie part. Les sommets du joint avec le "PEvoisin" sont
les sommets de la partie "part" qui sont aussi un sommet d'un
element appartenant au PEvoisin.
Les joints apparaissent dans la liste dans l'ordre croissant des PEs.
Note: Les faces que l'on va creer ensuite utilisent forcement
des sommets que l'on va trouver ici.
Propriete : Les sommets du joint sont classes dans l'ordre croissant
de leur numero local, donc dans l'ordre croissant de
leur numero global (voir Remplir_Numeros_Sommets)
void construire_faces_joints_ssdom (const int partie, const DomaineCutter_Correspondance &correspondance, Zone &zone_partie) const
void construire_elements_distants_ssdom (const int partie, const ArrOfInt &liste_sommets, const ArrOfInt &liste_inverse_elements, Zone &zone_partie) const
calcul et remplissage de
zone_partie.joint(i).set_joint_item(Joint::ELEMENT).set_items_distants()
(liste des elements distants).
Eventuellement, de nouveaux joints sont crees.
Historique: methode codee en janvier 2006 par B.Mathieu. Je croyais que c'etait
trop complique de determiner les elements distants au moment du scatter et j'ai
fini par trouver comment faire. Du coup la methode ci-dessous n'est plus utilisee
en temps normal. En cas de probleme, on peut la reactiver: en theorie elle donne
exactement le meme resultat que l'algorithme code dans Scatter::calculer_espace_distant_elements.
Attention, elle ne fait rien de special pour le bords periodiques...
void writeData (const Domaine &sous_domaine, Sortie &os) const
const DomaineCutter & operator= (const DomaineCutter &dc)
Appel invalide. exit.
DomaineCutter (const DomaineCutter &dc)
Appel invalide. exit.
Private Attributes
Ref_Domaine ref_domaine_
Ref_IntVect ref_elem_part_
Noms liste_bords_periodiques_
int nb_parties_
int epaisseur_joint_
Static_Int_Lists som_elem_
Static_Int_Lists liste_elems_sous_domaines_
Static_Int_Lists voisins_bords_
Noms bords_a_pb_
Detailed Description
Classe outil permettant de generer des sous-domaines pour un calcul parallele
a partir d'un domaine de depart (domaine_global) et d'un tableau de decoupage
des elements de ce domaine (elem_part).
Voir aussi Partitionneur_base.
Definition at line 33 of file DomaineCutter.h.
Constructor & Destructor Documentation
DomaineCutter() [1/2]
DomaineCutter::DomaineCutter ()
Constructeur par defaut (structure vide)
Definition at line 957 of file DomaineCutter.cpp.
{
  nb_parties_ = -1;
  epaisseur_joint_ = -1;
}
References epaisseur_joint_, and nb_parties_.
~DomaineCutter()
DomaineCutter::~DomaineCutter ()
Definition at line 32 of file DomaineCutter.cpp.
DomaineCutter() [2/2]
DomaineCutter::DomaineCutter (const DomaineCutter & dc) private
Appel invalide. exit.
Definition at line 42 of file DomaineCutter.cpp.
                                                   : Objet_U(dc)
{
  exit();
}
References Process::exit().
Member Function Documentation
bords_internes()
const Noms & DomaineCutter::bords_internes () const inline
Definition at line 56 of file DomaineCutter.h.
  {
    return bords_a_pb_;
  }
References bords_a_pb_.
Referenced by Create_domain_from_sous_zone::interpreter_().
construire_elements_distants_ssdom()
void DomaineCutter::construire_elements_distants_ssdom (const int partie, const ArrOfInt & liste_sommets, const ArrOfInt & liste_inverse_elements, Zone & zone_partie) const private
calcul et remplissage de
zone_partie.joint(i).set_joint_item(Joint::ELEMENT).set_items_distants()
(liste des elements distants).
Eventuellement, de nouveaux joints sont crees.
Historique: methode codee en janvier 2006 par B.Mathieu. Je croyais que c'etait
trop complique de determiner les elements distants au moment du scatter et j'ai
fini par trouver comment faire. Du coup la methode ci-dessous n'est plus utilisee
en temps normal. En cas de probleme, on peut la reactiver: en theorie elle donne
exactement le meme resultat que l'algorithme code dans Scatter::calculer_espace_distant_elements.
Attention, elle ne fait rien de special pour le bords periodiques...
< Sommets de depart
Definition at line 511 of file DomaineCutter.cpp.
{
  const Zone& zone          = ref_domaine_.valeur().zone(0);
  const IntTab& elements    = zone.les_elems();
  const IntVect& elem_part = ref_elem_part_.valeur();
  const int nb_som_elem = elements.dimension(1);
// Premiere etape: chercher les elements virtuels de la sous-partie
// (elements des autres parties situes dans l'epaisseur de joint en partant
// des sommets de joint).
  ArrOfInt elements_virtuels;
  {
// Construction d'un tableau contenant tous les sommets de tous les joints
    ArrOfInt sommets_joint;
    sommets_joint.set_smart_resize(1);
    const int nb_joints = zone_partie.nb_joints();
    for (int i_joint = 0; i_joint < nb_joints; i_joint++)
      {
        const ArrOfInt& sommets = zone_partie.joint(i_joint).joint_item(Joint::SOMMET).items_communs();
        const int n = sommets.size_array();
        for (int i = 0; i < n; i++)
          {
            const int sommet_local = sommets[i];
            const int sommet_global = liste_sommets[sommet_local];
            sommets_joint.append_array(sommet_global);
          }
      }
    parcourir_epaisseurs_elements(elements, som_elem_, elem_part,
                                  sommets_joint, //!< Sommets de depart
                                  partie, /* ignorer les elements de la partie locale */
                                  epaisseur_joint_,
                                  elements_virtuels);
  }
  const int nb_elements_virtuels = elements_virtuels.size_array();
// Construire la liste des numeros de zones voisines et ajouter les joints manquants:
  ArrOfInt parties_voisines;
  {
    parties_voisines.set_smart_resize(1);
    for (int i = 0; i < nb_elements_virtuels; i++)
      {
        const int elem = elements_virtuels[i];
        const int part = elem_part[elem];
        parties_voisines.append_array(part);
      }
    array_trier_retirer_doublons(parties_voisines);
    ajouter_joints(zone_partie, parties_voisines, epaisseur_joint_);
  }
// Pour chaque partie voisine, chercher les elements distants:
  const int nb_parties_voisines = parties_voisines.size_array();
  ArrOfInt sommets_depart;
  sommets_depart.set_smart_resize(1);
  for (int i_part = 0; i_part < nb_parties_voisines; i_part++)
    {
      const int partie_voisine = parties_voisines[i_part];
      sommets_depart.resize_array(0);
// Liste des sommets des elements virtuels de la partie voisine:
      for (int i_elem = 0; i_elem < nb_elements_virtuels; i_elem++)
        {
          const int elem = elements_virtuels[i_elem];
          if (elem_part(elem) == partie_voisine)
            {
              for (int i = 0; i < nb_som_elem; i++)
                {
                  const int som = elements(elem, i);
                  sommets_depart.append_array(som);
                }
            }
        }
// Recherche des elements voisins de cette liste:
      ArrOfInt elements_distants;
      parcourir_epaisseurs_elements(elements, som_elem_, elem_part,
                                    sommets_depart,
                                    partie_voisine, /* ignorer les elements de la partie voisine */
                                    epaisseur_joint_,
                                    elements_distants);
// Retirer de la liste les elements qui ne sont pas dans la partie locale:
      {
        int count = 0;
        const int n = elements_distants.size_array();
        for (int i = 0; i < n; i++)
          {
            const int elem = elements_distants[i];
            if (elem_part[elem] == partie && elem < elements.dimension(0) )
              elements_distants[count++] = elem;
          }
        elements_distants.resize_array(count);
      }
// Traduire les indices des elements en indices locaux sur le sous-domaine.
      {
        const int n = elements_distants.size_array();
        for (int i = 0; i < n; i++)
          {
            const int elem = elements_distants[i];
            const int renum = liste_inverse_elements[elem];
            elements_distants[i] = renum;
          }
      }
// Trier les elements dans l'ordre croissant des indices
      elements_distants.ordonne_array();
// Stocker la liste des elements distants dans le joint
      Joint&     joint = zone_partie.joint_of_pe(partie_voisine);
      joint.set_joint_item(Joint::ELEMENT).set_items_distants() = elements_distants;
    }
}
References ajouter_joints(), TRUSTArray< _TYPE_ >::append_array(), array_trier_retirer_doublons(), TRUSTTab< _TYPE_ >::dimension(), Joint::ELEMENT, epaisseur_joint_, Joint_Items::items_communs(), Zone::joint(), Joint::joint_item(), Zone::joint_of_pe(), Zone::les_elems(), Zone::nb_joints(), TRUSTArray< _TYPE_ >::ordonne_array(), parcourir_epaisseurs_elements(), ref_domaine_, ref_elem_part_, TRUSTArray< _TYPE_ >::resize_array(), Joint_Items::set_items_distants(), Joint::set_joint_item(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), som_elem_, Joint::SOMMET, Ref_IntVect::valeur(), Ref_Domaine::valeur(), and Domaine::zone().
Referenced by construire_sous_domaine().
construire_faces_bords_ssdom()
void DomaineCutter::construire_faces_bords_ssdom (const ArrOfInt & liste_inverse_sommets, const int partie, Zone & zone_partie) const private
Definition at line 292 of file DomaineCutter.cpp.
{
  const Zone& zone = ref_domaine_.valeur().zone(0);
  CONST_LIST_CURSEUR(Bord /*difference*/) curseur(zone.faces_bord()/*difference*/);
  int i_fr = 0;
  ArrOfInt elements_voisins;
  for (; curseur; ++curseur)
    {
      const Frontiere& frontiere = curseur.valeur();
      Frontiere& front_partie =
        zone_partie.faces_bord()/*difference*/.add(Bord()/*difference*/);
      front_partie.nommer(frontiere.le_nom());
      front_partie.associer_zone(zone_partie);
      front_partie.faces().typer(frontiere.faces().type_face());
      voisins_bords_.copy_list_to_array(i_fr, elements_voisins);
      construire_liste_faces_sous_domaine(elements_voisins,
                                          ref_elem_part_.valeur(),
                                          partie,
                                          frontiere.faces().les_sommets(),
                                          liste_inverse_sommets,
                                          front_partie.faces().les_sommets());
      i_fr++;
    }
}
References List_Bord::add(), Frontiere::associer_zone(), CONST_LIST_CURSEUR, construire_liste_faces_sous_domaine(), Static_Int_Lists::copy_list_to_array(), Frontiere::faces(), Zone::faces_bord(), Frontiere::le_nom(), Faces::les_sommets(), Frontiere::nommer(), ref_domaine_, ref_elem_part_, Faces::type_face(), Faces::typer(), Ref_IntVect::valeur(), Ref_Domaine::valeur(), voisins_bords_, and Domaine::zone().
Referenced by construire_sous_domaine().
construire_faces_internes_ssdom()
void DomaineCutter::construire_faces_internes_ssdom (const ArrOfInt & liste_inverse_sommets, const int partie, Zone & zone_partie) const private
Definition at line 356 of file DomaineCutter.cpp.
{
// Rappel : les faces internes sont des "frontieres" a l'interieur du domaine
// (par exemple une plaque d'epaisseur nulle dans l'ecoulement)
  const Zone& zone = ref_domaine_.valeur().zone(0);
  CONST_LIST_CURSEUR(Faces_Interne/*difference*/) curseur(zone.faces_int()/*difference*/);
  int i_fr = zone.nb_bords()+zone.nb_raccords();
  ArrOfInt elements_voisins;
  for (; curseur; ++curseur)
    {
      const Frontiere& frontiere = curseur.valeur();
      Frontiere& front_partie =
        zone_partie.faces_int()/*difference*/.add(Faces_Interne()/*difference*/);
      front_partie.nommer(frontiere.le_nom());
      front_partie.associer_zone(zone_partie);
      front_partie.faces().typer(frontiere.faces().type_face());
      voisins_bords_.copy_list_to_array(i_fr, elements_voisins);
      construire_liste_faces_sous_domaine(elements_voisins,
                                          ref_elem_part_.valeur(),
                                          partie,
                                          frontiere.faces().les_sommets(),
                                          liste_inverse_sommets,
                                          front_partie.faces().les_sommets());
      i_fr++;
    }
}
References List_Faces_Interne::add(), Frontiere::associer_zone(), CONST_LIST_CURSEUR, construire_liste_faces_sous_domaine(), Static_Int_Lists::copy_list_to_array(), Frontiere::faces(), Zone::faces_int(), Frontiere::le_nom(), Faces::les_sommets(), Zone::nb_bords(), Zone::nb_raccords(), Frontiere::nommer(), ref_domaine_, ref_elem_part_, Faces::type_face(), Faces::typer(), Ref_IntVect::valeur(), Ref_Domaine::valeur(), voisins_bords_, and Domaine::zone().
Referenced by construire_sous_domaine().
construire_faces_joints_ssdom()
void DomaineCutter::construire_faces_joints_ssdom (const int partie, const DomaineCutter_Correspondance & correspondance, Zone & zone_partie) const private
< Voir suite
< Non => cette face n'est pas sur un joint
Definition at line 731 of file DomaineCutter.cpp.
{
  const int nb_sommets_ssdom = zone_partie.nb_som();
  const int nb_elem_ssdom = zone_partie.nb_elem();
  const ArrOfInt& liste_sommets = correspondance.get_liste_sommets();
  const ArrOfInt& liste_inverse_elements = correspondance.get_liste_inverse_elements();
  const Static_Int_Lists& som_elem = som_elem_;
// Premiere etape: reperage des "elements de joint" (elements de la "partie"
// possedant un sommet de joint), et marquage des sommets de joint
  ArrOfInt liste_elements_joint;
  ArrOfBit drapeaux_sommets_joints(nb_sommets_ssdom);
  {
// Pour l'instant, on utilise les joints en const...
    const Joints& joints_partie = zone_partie.faces_joint();
    drapeaux_sommets_joints = 0;
    liste_elements_joint.set_smart_resize(1);
// Marqueurs: pour chaque element du sous-domaine, est-il deja dans la liste ?
    ArrOfBit drapeaux_elements(nb_elem_ssdom);
    drapeaux_elements = 0;
// Boucle sur tous les sommets de joint
    const int nb_joints = joints_partie.size();
    int i_joint;
    for (i_joint = 0; i_joint < nb_joints; i_joint++)
      {
        const Joint& joint = joints_partie[i_joint];
        const ArrOfInt& sommets_du_joint = joint.joint_item(Joint::SOMMET).items_communs();
        const int n = sommets_du_joint.size_array();
        int i;
        for (i = 0; i < n; i++)
          {
            const int i_sommet_local = sommets_du_joint[i];
            const int i_sommet_global = liste_sommets[i_sommet_local];
            const int nb_elem_voisins = som_elem.get_list_size(i_sommet_global);
// Marquage du sommet de joint dans le sous-domaine
            drapeaux_sommets_joints.setbit(i_sommet_local);
            int j;
            for (j = 0; j < nb_elem_voisins; j++)
              {
                const int i_elem_global = som_elem(i_sommet_global, j);
                const int i_elem_local = liste_inverse_elements[i_elem_global];
// On ajoute l'element a la liste d'elements joint s'il est dans ma partie
// et s'il n'est pas encore dans la liste.
                if (i_elem_local >= 0)
                  if (! drapeaux_elements.testsetbit(i_elem_local))
                    liste_elements_joint.append_array(i_elem_global);
              }
          }
      }
  }
// Deuxieme etape: pour chaque element de joint, construction de ses
// faces et on regarde si la face a un element voisin dans une autre partie.
// Si oui, c'est une face de joint
// Tableau des indices des sommets de toutes les faces de joint
// (tous joints confondus, indices de sommets dans le sous-domaine)
  IntTab faces_joints;
// Pour chaque face de joint, numero du sous-domaine voisin par cette face
  ArrOfInt faces_pe_voisins;
// Pour chaque processeur, nombre de faces de joint avec ce proc.
// (on initialise a zero)
  ArrOfInt nb_faces_joints(nb_parties_);
  {
    faces_joints.set_smart_resize(1);
    faces_pe_voisins.set_smart_resize(1);
// Indices des sommets des faces sur l'element de reference
    IntTab faces_element_reference;
    const Elem_geom_base& type_elem = zone_partie.type_elem().valeur();
    int is_regular = type_elem.get_tab_faces_sommets_locaux(faces_element_reference);
// On ne sait pas traiter les elements non reguliers
    if (!is_regular)
      {
// Cerr << "DomaineCutter::faces_joints Error: non-regular elements not supported" << finl;
        ref_cast(Poly_geom_base,type_elem).get_tab_faces_sommets_locaux(faces_element_reference,0);
// exit();
      }
    int nb_faces_elem       = faces_element_reference.dimension(0);
    const int nb_sommets_par_face = faces_element_reference.dimension(1);
    faces_joints.resize(0, nb_sommets_par_face); //!< Voir *suite*
    const ArrOfInt& liste_inverse_sommets = correspondance.get_liste_inverse_sommets();
    const IntVect& elem_part = ref_elem_part_.valeur();
// Sommets des elements du maillage global
    const Domaine& domaine = ref_domaine_.valeur();
    const IntTab& elem_som = domaine.zone(0).les_elems();
    ArrOfInt une_face(nb_sommets_par_face);
    ArrOfInt elements_voisins;
    elements_voisins.set_smart_resize(1);
// Boucle sur les elements de joint
    const int nb_elem_joints = liste_elements_joint.size_array();
    int i_elem_joint;
    for (i_elem_joint = 0; i_elem_joint < nb_elem_joints; i_elem_joint++)
      {
// Indice de l'element dans le domaine global
        const int i_elem_global = liste_elements_joint[i_elem_joint];
// Boucle sur les faces de l'element
        int i_face;
        if (!is_regular)
          {
// global ou non ????????
            ref_cast(Poly_geom_base,type_elem).get_tab_faces_sommets_locaux(faces_element_reference,liste_inverse_elements[i_elem_global]);
            nb_faces_elem       = faces_element_reference.dimension(0);
            while ( faces_element_reference(nb_faces_elem-1,0)==-1)
              nb_faces_elem--;
          }
        for (i_face = 0; i_face < nb_faces_elem; i_face++)
          {
// Construction de la face
            int i;
            int face_ok = 1;
            for (i = 0; i < nb_sommets_par_face; i++)
              {
                const int i_ref = faces_element_reference(i_face, i);
                if (i_ref<0)
                  {
                    une_face[i] = i_ref;
                  }
                else
                  {
                    const int i_som = elem_som(i_elem_global, i_ref);
                    une_face[i] = i_som;
// Indice du sommet dans le sous-domaine
                    if (i_som>-1)
                      {
                        const int i_som_local = liste_inverse_sommets[i_som];
                        if(i_som_local>0)
{
// Le sommet est-il sur un joint ?
                            if (drapeaux_sommets_joints[i_som_local] == 0)
                              face_ok = 0; //!< Non => cette face n'est pas sur un joint
                          }
                      }
                  }
              }
// Premier test pour eliminer tout de suite la face
// si tous ses sommets ne sont pas des sommets de joint.
            if (face_ok)
              {
// Recherche des elements voisins de cette face
                find_adjacent_elements(som_elem, une_face, elements_voisins);
// Recherche d'un element voisin qui n'est pas dans ma partie
                const int nb_elem_voisins = elements_voisins.size_array();
                int PEvoisin = -1;
                for (i = 0; i < nb_elem_voisins; i++)
                  {
                    const int i_elem_glob = elements_voisins[i];
                    PEvoisin = elem_part[i_elem_glob];
                    if (PEvoisin != partie)
                      break;
                  }
                if (i < nb_elem_voisins)
                  {
// J'ai une face de joint, je l'ajoute au tableau
                    faces_pe_voisins.append_array(PEvoisin);
                    const int n = faces_joints.dimension(0);
                    faces_joints.resize(n+1, nb_sommets_par_face);
                    for (i = 0; i < nb_sommets_par_face; i++)
                      {
                        const int i_som_global = une_face[i];
                        if (i_som_global>-1)
{
                            const int i_som_local = liste_inverse_sommets[i_som_global];
                            faces_joints(n, i) = i_som_local;
                          }
                        else
                          faces_joints(n, i) = -1;
                      }
                    nb_faces_joints[PEvoisin]++;
                  }
              }
          }
      }
  }
// Troisieme etape: ajout des faces dans les joints
  {
// Le type des faces de joint
    const Zone& zone_globale = ref_domaine_.valeur().zone(0);
    const Type_Face& type_face_joint = zone_globale.type_elem().type_face();
// On va modifier les joints:
    Joints& joints_partie = zone_partie.faces_joint();
    const int nb_joints = joints_partie.size();
    int i_joint;
    const int nb_faces_joints_tot = faces_joints.dimension(0);
// *suite* : tableau de dimension 2 meme s'il n'y a pas de faces
    const int nb_sommets_par_face = faces_joints.dimension(1);
    for (i_joint = 0; i_joint < nb_joints; i_joint++)
      {
// Typage des faces et allocation memoire
        Joint& joint = joints_partie[i_joint];
        joint.typer_faces(type_face_joint);
        joint.faces().les_sommets().resize(0, nb_sommets_par_face);
        const int PE_voisin = joint.PEvoisin();
        const int nb_faces = nb_faces_joints[PE_voisin];
        joint.dimensionner(nb_faces);
// Remplissage du tableau de faces
        IntTab& faces = joint.faces().les_sommets();
        int i;
        int k = 0;
        for (i = 0; i < nb_faces_joints_tot; i++)
          {
            const int face_pe = faces_pe_voisins[i];
            if (face_pe == PE_voisin)
              {
                int j;
                for (j = 0; j < nb_sommets_par_face; j++)
                  faces(k, j) = faces_joints(i,j);
                k++;
              }
          }
      }
  }
}
References TRUSTArray< _TYPE_ >::append_array(), TRUSTTab< _TYPE_ >::dimension(), Joint::dimensionner(), Frontiere::faces(), Zone::faces_joint(), find_adjacent_elements(), Static_Int_Lists::get_list_size(), DomaineCutter_Correspondance::get_liste_inverse_elements(), DomaineCutter_Correspondance::get_liste_inverse_sommets(), DomaineCutter_Correspondance::get_liste_sommets(), Joint_Items::items_communs(), Joint::joint_item(), Zone::les_elems(), Faces::les_sommets(), Zone::nb_elem(), nb_parties_, Zone::nb_som(), Joint::PEvoisin(), ref_cast, ref_domaine_, ref_elem_part_, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), ArrOfBit::setbit(), liste::size(), TRUSTArray< _TYPE_ >::size_array(), som_elem_, Joint::SOMMET, ArrOfBit::testsetbit(), Zone::type_elem(), type_elem(), Elem_geom::type_face(), Frontiere::typer_faces(), Ref_IntVect::valeur(), Deriv_Elem_geom_base::valeur(), Ref_Domaine::valeur(), and Domaine::zone().
Referenced by construire_sous_domaine().
construire_faces_raccords_ssdom()
void DomaineCutter::construire_faces_raccords_ssdom (const ArrOfInt & liste_inverse_sommets, const int partie, Zone & zone_partie) const private
Constructions des raccords de la sous_partie a partir des raccords
du domaine global.
Les Raccord_local_homogene sont transformes en Raccord_distant_homogene.
Definition at line 323 of file DomaineCutter.cpp.
{
  const Zone& zone = ref_domaine_.valeur().zone(0);
  CONST_LIST_CURSEUR(Raccord) curseur(zone.faces_raccord());
  int i_fr = zone.nb_bords();
  ArrOfInt elements_voisins;
  for (; curseur; ++curseur)
    {
      const Raccord& raccord = curseur.valeur();
      const Frontiere& frontiere = raccord.valeur();
      Raccord& raccord_partie = zone_partie.faces_raccord().add(Raccord());
      Nom type_raccord = frontiere.que_suis_je();
      if (type_raccord == "Raccord_local_homogene")
        type_raccord = "Raccord_distant_homogene";
      raccord_partie.typer(type_raccord);
      Frontiere& front_partie = raccord_partie.valeur();
      front_partie.nommer(frontiere.le_nom());
      front_partie.associer_zone(zone_partie);
      front_partie.faces().typer(frontiere.faces().type_face());
      voisins_bords_.copy_list_to_array(i_fr, elements_voisins);
      construire_liste_faces_sous_domaine(elements_voisins,
                                          ref_elem_part_.valeur(),
                                          partie,
                                          frontiere.faces().les_sommets(),
                                          liste_inverse_sommets,
                                          front_partie.faces().les_sommets());
      i_fr++;
    }
}
References List_Raccord::add(), Frontiere::associer_zone(), CONST_LIST_CURSEUR, construire_liste_faces_sous_domaine(), Static_Int_Lists::copy_list_to_array(), Frontiere::faces(), Zone::faces_raccord(), Frontiere::le_nom(), Faces::les_sommets(), Zone::nb_bords(), Frontiere::nommer(), Objet_U::que_suis_je(), ref_domaine_, ref_elem_part_, Faces::type_face(), Deriv_::typer(), Faces::typer(), Ref_IntVect::valeur(), Deriv_Raccord_base::valeur(), Ref_Domaine::valeur(), voisins_bords_, and Domaine::zone().
Referenced by construire_sous_domaine().
construire_sommets_joints_ssdom()
void DomaineCutter::construire_sommets_joints_ssdom (const ArrOfInt & liste_sommets, const ArrOfInt & liste_inverse_sommets, const int partie, const Static_Int_Lists * som_raccord, Zone & zone_partie) const private
Creation des joints et construction des listes et des
tableaux de sommets joints pour tous les joints de
la partie part. Les sommets du joint avec le "PEvoisin" sont
les sommets de la partie "part" qui sont aussi un sommet d'un
element appartenant au PEvoisin.
Les joints apparaissent dans la liste dans l'ordre croissant des PEs.
Note: Les faces que l'on va creer ensuite utilisent forcement
des sommets que l'on va trouver ici.
Propriete : Les sommets du joint sont classes dans l'ordre croissant
de leur numero local, donc dans l'ordre croissant de
leur numero global (voir Remplir_Numeros_Sommets)
Definition at line 637 of file DomaineCutter.cpp.
{
  Joints& les_joints = zone_partie.faces_joint();
  const int parts = nb_parties_;
  const IntVect& elem_part = ref_elem_part_.valeur();
  const Static_Int_Lists& som_elem = som_elem_;
// Liste de sommets de joint (toutes parties confondues, un sommet peut
// apparaitre plusieurs fois dans le tableau, une fois par pe voisin au maximum)
// C'est le numero global du sommet
  ArrsOfInt joints_sommets(parts);
  {
// Pour append_array :
    for (int i = 0; i < parts; i++)
      joints_sommets[i].set_smart_resize(1);
  }
// Algorithme : boucle sur les sommets de la partie.
// Pour chaque sommet du sous-domaine "p", on cherche les PEs auxquels appartiennent
// les elements voisins du sommet, et, s'il y a un PE voisin different de "p",
// on ajoute ce sommet aux joints avec ces PEs.
  const int nb_sommets = liste_sommets.size_array();
  int i_sommet;
// i = indice local du sommet dans le sous-domaine
  for (i_sommet = 0; i_sommet < nb_sommets; i_sommet++)
    {
// Numero global du sommet
      int sommet = liste_sommets[i_sommet];
// Boucle sur les elements voisins du sommet i
      int nb_elements_voisins = som_elem.get_list_size(sommet);
      int i;
      for (i = 0; i < nb_elements_voisins; i++)
        {
          int elem = som_elem(sommet, i);
          int PEvoisin = elem_part[elem];
// Faut-il ajouter ce sommet aux sommets du joint avec le PEvoisin ?
          if (PEvoisin != partie)
            joints_sommets[PEvoisin].append_array(sommet);
        }
// boucle sur les procs connectes au sommet par un raccord
      if (som_raccord)
        for (i = 0; i < som_raccord->get_list_size(sommet); i++)
          if ((*som_raccord)(sommet, i) != partie) joints_sommets[(*som_raccord)(sommet, i)].append_array(sommet);
    }
// Creation des joints : dans l'ordre croissant du PE voisin
  int PEvoisin;
  for (PEvoisin = 0; PEvoisin < parts; PEvoisin++)
    {
      ArrOfInt& sommets = joints_sommets[PEvoisin];
      if (sommets.size_array() > 0)
        {
// Trier les sommets de joint par ordre croissant de l'indice global
// (donc toutes les listes sur les processeurs voisins seront ordonnees
// de la meme facon) et retirer les doublons
          array_trier_retirer_doublons(sommets);
          const int nb_sommets2 = sommets.size_array();
// On cree un nouveau joint
          Joint& joint = les_joints.add(Joint());
          Nom nom_joint("Joint_");
          Nom nom_numero(PEvoisin);
          nom_joint+=nom_numero;
          joint.nommer(nom_joint);
          joint.affecte_epaisseur(epaisseur_joint_);
          joint.associer_zone(zone_partie);
          joint.affecte_PEvoisin(PEvoisin);
          ArrOfInt& sommets_locaux = joint.set_joint_item(Joint::SOMMET).set_items_communs();
          sommets_locaux.resize_array(nb_sommets2);
// Remplissage du tableau (transformation en indice local de sommet)
          for (int i = 0; i < nb_sommets2; i++)
            {
              const int indice_global = sommets[i];
              const int indice_local = liste_inverse_sommets[indice_global];
              assert(indice_local >= 0);
              sommets_locaux[i] = indice_local;
            }
        }
    }
}
References List_Joint::add(), Joint::affecte_epaisseur(), Joint::affecte_PEvoisin(), array_trier_retirer_doublons(), Frontiere::associer_zone(), epaisseur_joint_, Zone::faces_joint(), Static_Int_Lists::get_list_size(), nb_parties_, Frontiere::nommer(), ref_elem_part_, TRUSTArray< _TYPE_ >::resize_array(), Joint_Items::set_items_communs(), Joint::set_joint_item(), TRUSTArray< _TYPE_ >::size_array(), som_elem_, Joint::SOMMET, and Ref_IntVect::valeur().
Referenced by construire_sous_domaine().
construire_sous_domaine() [1/2]
void DomaineCutter::construire_sous_domaine (const int part, Domaine & sous_domaine_) const inline
Definition at line 49 of file DomaineCutter.h.
  {
    DomaineCutter_Correspondance  correspondance;
    construire_sous_domaine(part,correspondance,sous_domaine_);
  };
References construire_sous_domaine().
construire_sous_domaine() [2/2]
void DomaineCutter::construire_sous_domaine (const int part, DomaineCutter_Correspondance & correspondance_, Domaine & sous_domaine_, const Static_Int_Lists * som_raccord = NULL) const
Remplit la structure "correspondance" et le "sous_domaine"
pour la partie "part". On cherche les sommets qui appartiennent a la sous-partie,
on calcule les tableaux de renumerotation des sommets et des elements entre numero
global et numero local (structure correspondance), on remplit les structures de
sous_domaine (sommets, elements, frontieres, joints, etc).
Attention: sous_domaine doit etre un objet vierge (ne pas contenir de zone)
< To print NbElemDist informations
Definition at line 1110 of file DomaineCutter.cpp.
{
// L'objet doit etre initialise:
  assert(nb_parties_ >= 0);
// Pas de zone dans sous_domaine
  assert(sous_domaine.nb_zones() == 0);
// Numero de partie valide
  assert(part >= 0 && part < nb_parties_);
  correspondance.partie_ = part;
  const Domaine& domaine = ref_domaine_.valeur();
  const Zone&     zone    = domaine.zone(0);
  ArrOfInt elements_sous_partie;
  liste_elems_sous_domaines_.copy_list_to_array(part, elements_sous_partie);
// Preparation du sous_domaine
// sous_domaine.reset(); /* reset n'existe pas encore... */
  sous_domaine.nommer(domaine.le_nom());
// On cree une zone pour le domaine
  Zone new_empty_zone;
  Zone& zone_partie = sous_domaine.add(new_empty_zone);
// Nom de la zone
  {
    const Nom nom_zone = zone.le_nom();
    zone_partie.nommer(nom_zone);
  }
  zone_partie.associer_domaine(sous_domaine);
  if (sub_type(Poly_geom_base,zone.type_elem().valeur()))
    ref_cast(Poly_geom_base,zone.type_elem().valeur()).build_reduced(zone_partie.type_elem(), elements_sous_partie);
  else
    zone_partie.type_elem() = zone.type_elem();
  zone_partie.type_elem().associer_zone(zone_partie);
  construire_liste_sommets_sousdomaine(domaine.nb_som_tot(),
                                       zone.les_elems(),
                                       elements_sous_partie,
                                       part,
                                       som_raccord,
                                       correspondance.liste_sommets_ /* write */,
                                       correspondance.liste_inverse_sommets_ /* write */);
  remplir_coordsommets_sous_domaine(domaine.coord_sommets(),
                                    correspondance.liste_sommets_,
                                    sous_domaine.les_sommets() /* write */);
  construire_elems_sous_domaine(zone.les_elems(),
                                elements_sous_partie,
                                correspondance.liste_inverse_sommets_,
                                zone_partie.les_elems() /* write */,
                                correspondance.liste_inverse_elements_ /* write */);
  {
    const ArrOfInt& l_som     = correspondance.liste_sommets_;
    const ArrOfInt& l_inv_som = correspondance.liste_inverse_sommets_;
    construire_faces_bords_ssdom   (l_inv_som, part, zone_partie);
    construire_faces_raccords_ssdom(l_inv_som, part, zone_partie);
    construire_faces_internes_ssdom(l_inv_som, part, zone_partie);
    construire_sommets_joints_ssdom(l_som, l_inv_som, part, som_raccord, zone_partie);
  }
  construire_faces_joints_ssdom(part, correspondance, zone_partie);
// if som_raccord is used (for DecouperMulti), then construire_elements_distants_ssdom()
// can lead to the creation of empty joints -> it must not be called
  int compute_items_distants= Decouper::print_more_infos && !som_raccord; //!< To print NbElemDist informations
  if (compute_items_distants)
    {
// Cet algorithme sequentiel n'est pas utilise en temps normal, sauf si
// on veut tester l'algorithme parallele dans Scatter.cpp
// voir  CHECK_ALGO_ESPACE_VIRTUEL dans Scatter.cpp (Benoit Mathieu)
      construire_elements_distants_ssdom(part,
                                         correspondance.liste_sommets_,
                                         correspondance.liste_inverse_elements_,
                                         zone_partie);
    }
  else
    {
// Initialiser des joints vides (sinon assert en debug car les joints ne sont pas initialises)
      for (int ij = 0; ij < zone_partie.nb_joints(); ij++)
        {
          Joint&     joint = zone_partie.joint(ij);
          joint.set_joint_item(Joint::ELEMENT).set_items_distants();
        }
    }
  Scatter::trier_les_joints(zone_partie.faces_joint());
}
References Domaine::add(), Zone::associer_domaine(), Elem_geom::associer_zone(), construire_elements_distants_ssdom(), construire_elems_sous_domaine(), construire_faces_bords_ssdom(), construire_faces_internes_ssdom(), construire_faces_joints_ssdom(), construire_faces_raccords_ssdom(), construire_liste_sommets_sousdomaine(), construire_sommets_joints_ssdom(), Domaine::coord_sommets(), Static_Int_Lists::copy_list_to_array(), Joint::ELEMENT, Zone::faces_joint(), Zone::joint(), Domaine::le_nom(), Zone::le_nom(), Zone::les_elems(), Domaine::les_sommets(), liste_elems_sous_domaines_, DomaineCutter_Correspondance::liste_inverse_elements_, DomaineCutter_Correspondance::liste_inverse_sommets_, DomaineCutter_Correspondance::liste_sommets_, Zone::nb_joints(), nb_parties_, Domaine::nb_som_tot(), Domaine::nb_zones(), Domaine::nommer(), Zone::nommer(), DomaineCutter_Correspondance::partie_, Decouper::print_more_infos, ref_cast, ref_domaine_, remplir_coordsommets_sous_domaine(), Joint_Items::set_items_distants(), Joint::set_joint_item(), sub_type, Scatter::trier_les_joints(), Zone::type_elem(), Deriv_Elem_geom_base::valeur(), Ref_Domaine::valeur(), and Domaine::zone().
Referenced by construire_sous_domaine(), ecrire_zones(), and Create_domain_from_sous_zone::interpreter_().
cree_instance()
Objet_U * DomaineCutter::cree_instance () static
Definition at line 32 of file DomaineCutter.cpp.
duplique()
int DomaineCutter::duplique () const override virtual
Implements Objet_U.
Definition at line 32 of file DomaineCutter.cpp.
ecrire_zones()
void DomaineCutter::ecrire_zones (const Nom & basename, const Decouper::ZonesFileOutputType format, IntVect & elem_part, const int reorder, const Static_Int_Lists * som_raccord = NULL)
Generation de tous les sous-domaines du calcul et ecriture sur disque des
fichiers basename_000n.Zones pour 0 <= n < nb_parties_.
Si des "sous-zones" sont definies (dans le champ domaine.ss_zones()),
on genere aussi un fichier par sous-zone.
< create HDF5 file only once!
< Premiere partie, on ecrase le fichier
< Mode append
< involves communication: do it only if requested
Definition at line 1263 of file DomaineCutter.cpp.
{
  assert(nb_parties_ >= 0);
  const Domaine& domaine = ref_domaine_.valeur();
  DomaineCutter_Correspondance dc_correspondance;
// Needed for HDF5 Zones output:
#ifdef MPI_
  FichierHDFPar fic_hdf;
#else
  FichierHDF fic_hdf;
#endif
  Nom nom_fichier_hdf5(basename);
  nom_fichier_hdf5+=Nom(".Zones");
  nom_fichier_hdf5 = nom_fichier_hdf5.nom_me(nb_parties_, "p", 1);
// Build temp arrays to eventually reorder the partition numbering
  ArrOfInt ia(nb_parties_+1);
  ArrOfInt ja;
  ja.set_smart_resize(1);
  int nnz=0;
  ia[0]=1;
// To detect my parts (when running in parallel)
  ArrOfInt myZones(nb_parties_);
  myZones = 0;
  ArrsOfInt otherProcZones(Process::nproc());
// if some zones are splitted between multiple procs,
// we assign consecutive indices to each of its fragment
// (reading the .Zones files during Scatter will be more efficient)
// Possible values for zones_index[part]:
// -2    : means that part is detained by multiple procs but not by me
// -1    : means that part is detained by a single proc
// i >=0 : means that my proc detains the i-th fragment of part
  ArrOfInt zones_index(nb_parties_);
  zones_index = -2;
  const int nbelem = domaine.zone(0).nb_elem();
  Cerr << "Generation of " << nb_parties_ << " parts:" << finl;
  IntVect EdgeCut(nb_parties_);
  ArrsOfInt Neighbours(nb_parties_);
// 2 loops if reorder=1
  for (int loop=0; loop<1+reorder; loop++)
    {
      if (reorder)
        {
          Cerr << "====================================" << finl;
          if (loop==0)
            Cerr << "FIRST PASS, analyzing the partition:" << finl;
          else
            Cerr << "SECOND PASS, after reordering the partition:" << finl;
          Cerr << "====================================" << finl;
        }
      if(loop == reorder)
        {
// check to see which part is shared between multiple processors:
// 1- everyone sends the number of the parts that belong to them to the master process
// 2- master process will assign a unique positive number to each fragment of a shared zone
// 3- if a part is owned by a single process, it is indicated with the index -1
// 4- the master process scatters the indices to all the proc
          ArrsOfInt zones_indices(Process::nproc());
          for(int i=0; i < nbelem; i++)
            {
              const int part = elem_part[i];
              myZones[part] = 1;
            }
          for(int p=0; p<Process::nproc(); p++)
            {
              if(p==0)
                otherProcZones[p] = myZones;
              else
                {
                  otherProcZones[p].resize_array(nb_parties_);
                  otherProcZones[p] = 0;
                }
            }
          if(Process::je_suis_maitre())
            {
              for(int p=0; p<Process::nproc(); p++)
                {
                  zones_indices[p].resize_array(nb_parties_);
                  zones_indices[p] = -2;
                  if(p!=0)
                    recevoir(otherProcZones[p], p, 0, p+2001);
                }
              for(int part=0; part<nb_parties_; part++)
                {
                  int s = 0;
                  for(int proc=0; proc < Process::nproc(); proc++)
                    {
                      if(otherProcZones[proc][part])
                        zones_indices[proc][part] = s++;
                    }
                  if(s<=1)
                    {
                      if(s==0)   //empty part: master process will write it
                        myZones[part] = 1;
// part is detained by a single proc
                      for(int proc=0; proc < Process::nproc(); proc++)
                        zones_indices[proc][part] = -1;
                    }
                }
              for(int p=0; p<Process::nproc(); p++)
                {
                  if(p==0)
                    zones_index = zones_indices[p];
                  else
                    envoyer(zones_indices[p], 0, p, p+2002);
                }
            }
          else
            {
              envoyer(myZones, Process::me(), 0, Process::me()+2001);
              recevoir(zones_index, 0, Process::me(), Process::me()+2002);
            }
          if (format == Decouper::HDF5_SINGLE)  //!< create HDF5 file only once!
            {
              fic_hdf.create(nom_fichier_hdf5);
              if(Process::nproc() > 1)
                {
// creating datasets
                  Noms dataset_names;
                  if(Process::je_suis_maitre())
                    {
                      for(int part=0; part<nb_parties_; part++)
{
                          if(zones_index[part] == -1)
{
                              std::string dname = "/zone_"  + std::to_string(part);
                              Nom dataset_name(dname);
                              dataset_names.add(dataset_name);
                            }
                          else
{
                              for(int proc=0; proc < Process::nproc(); proc++)
{
                                  if(zones_indices[proc][part] >=0)
{
                                      std::string dname = "/zone_"  + std::to_string(part) + "_" + std::to_string(zones_indices[proc][part]);
                                      Nom dataset_name(dname);
                                      dataset_names.add(dataset_name);
                                    }
                                }
                            }
                        }
                    }
// estimation of an upper bound of the datasets' size
                  int ipart = 0;
                  while(!myZones[ipart]) ipart++;
                  Domaine dom_tmp;
                  construire_sous_domaine(ipart, dc_correspondance, dom_tmp);
                  Sortie_Brute os_tmp;
                  writeData(dom_tmp, os_tmp);
                  long sz_ = os_tmp.get_size();
                  sz_ *= 1.5;
                  sz_ = Process::mp_max(sz_);
                  envoyer_broadcast(dataset_names,0);
                  fic_hdf.create_datasets(dataset_names, sz_);
                }
            }
        }
      for (int i_part = 0; i_part < nb_parties_; i_part++)
        {
          if(!myZones[i_part])
            continue;
          assert(zones_index[i_part] > -2);
          Cerr << " Construction of part number " << i_part << finl;
          if(zones_index[i_part] >= 0)
            Cerr << "This part is shared between multiple processors" << finl;
          Domaine sous_domaine;
          construire_sous_domaine(i_part, dc_correspondance, sous_domaine, som_raccord);
// On affiche quelques informations...
          {
            const Zone& zone = sous_domaine.zone(0);
            const Joints& joints = zone.faces_joint();
            const int nb_joints = joints.size();
            Cerr << "  Number of nodes    : " << sous_domaine.nb_som() << finl;
            Cerr << "  Number of elements : " << zone.nb_elem() << finl;
            Cerr << "  Number of joints   : " << nb_joints << finl;
// char s[200];
            int nbfaces_total=0;
            int nbelemdist_total=0;
            int nbsom_total=0;
            Neighbours[i_part].resize_array(0);
            Neighbours[i_part].resize_array(nb_joints);
            for (int i = 0; i < nb_joints; i++)
              {
                const Joint& joint = joints[i];
                const int pe = joint.PEvoisin();
                Neighbours[i_part][i] = pe;
                const int nbsom = joint.joint_item(Joint::SOMMET).items_communs().size_array();
                nbsom_total+=nbsom;
                const int nbfaces = joint.nb_faces();
                nbfaces_total+=nbfaces;
                const int nbelemdist = joint.joint_item(Joint::ELEMENT).items_distants().size_array();
                nbelemdist_total+=nbelemdist;
// Beurk: sprintf pas beau et dangereux, mais c'est plus simple...
                assert(sizeof(int)==sizeof(int));
                Cerr<< "  Joint "<<i<<" PeVoisin "<<pe<<" NbSommets "<<nbsom<<" NbFaces "<<nbfaces;
                if (Decouper::print_more_infos) Cerr <<" NbElemDist "<<nbelemdist;
                Cerr<<finl;
              }
            Cerr<<"               Total:    NbSommets "<<nbsom_total<<" NbFaces "<<nbfaces_total;
            if (Decouper::print_more_infos) Cerr<<" NbElemDist "<<nbelemdist_total;
            EdgeCut(i_part)=nbfaces_total;
            Cerr<<finl;
          }
          if (reorder && loop==0)
            {
              const Zone& zone = sous_domaine.zone(0);
              const Joints& joints = zone.faces_joint();
              const int nb_joints = joints.size();
// Resize ja:
              ja.resize_array(nnz+nb_joints+1);
// Fortran numerotation:
              ja[nnz]=i_part+1;
              nnz++;
              ia[i_part+1]=ia[i_part]+1;
              for (int i = 0; i < nb_joints; i++)
                {
                  const int pe = joints[i].PEvoisin();
                  ja[nnz] = pe+1;
                  nnz++;
                  ia[i_part+1]++;
                }
            }
          else
            {
// Write .Zones file(s):
              if (format == Decouper::BINARY_MULTIPLE)
                {
                  Nom nom_fichier(basename);
                  nom_fichier+=Nom(".Zones");
// nom_fichier = nom_fichier.nom_me(i_part);
                  construire_nom_fichier_sous_domaine(basename,i_part, nb_parties_, zones_index[i_part], nom_fichier);
                  Cerr << "Writing part " << i_part << " into the "
                       << (format == Decouper::BINARY_MULTIPLE ? "binary" : "ascii")
                       << " file " << nom_fichier << finl;
                  SFichier os;
                  if (format == Decouper::BINARY_MULTIPLE)
                    os.set_bin(1);
                  const int ok = os.ouvrir(nom_fichier);
                  if (!ok)
                    {
                      Cerr << "DomaineCutter::ecrire_zones : Error while opening file " << finl;
                      exit();
                    }
                  writeData(sous_domaine, os);
                }
              else if (format == Decouper::HDF5_SINGLE)
                {
                  Sortie_Brute os_hdf;
                  writeData(sous_domaine, os_hdf);
                  std::string dname = "/zone_" + std::to_string(i_part);
                  if(zones_index[i_part] >=0)
                    dname += "_" + std::to_string(zones_index[i_part]);
                  Nom datasetname(dname);
                  if(Process::nproc() > 1)
                    fic_hdf.fill_dataset(datasetname, os_hdf);
                  else
                    fic_hdf.create_and_fill_dataset_SW(datasetname, os_hdf);
                }
              else
                {
                  Cerr << "DomaineCutter::ecrire_zones : Unsupported output file type!" << finl;
                  Process::exit(1);
                }
            }
// Ecritures des fichiers sous-zones .ssz
          const LIST(REF(Sous_Zone)) & liste_sous_zones = domaine.ss_zones();
          const int nb_sous_zones = liste_sous_zones.size();
          if (nb_sous_zones>0)
            {
              Cerr << " Writing of files .ssz ..." << finl;
// Un fichier par sous-zone, dans chaque fichier on trouve toutes les parties...
// Si on est en train d'ecrire la premiere partie, on efface le fichier
              IOS_OPEN_MODE mode;
              if (i_part == 0)
                mode = ios::out; //!< Premiere partie, on ecrase le fichier
              else
                mode = (ios::out | ios::app); //!< Mode append
// Boucle sur les sous-zones
              const ArrOfInt& liste_inverse_elements = dc_correspondance.liste_inverse_elements_;
              for (int i_sous_zone = 0; i_sous_zone < nb_sous_zones; i_sous_zone++)
                {
// Indices des elements du sous-domaine qui sont dans la sous-zone:
                  const Sous_Zone& sous_zone = liste_sous_zones[i_sous_zone];
                  ArrOfInt elements;
                  {
                    const int n = sous_zone.nb_elem_tot();
                    elements.set_smart_resize(1);
                    int i;
                    for (i = 0; i < n; i++)
                      {
                        const int i_elem_global = sous_zone[i];
                        const int i_elem_local = liste_inverse_elements[i_elem_global];
                        if (i_elem_local >= 0)
                          elements.append_array(i_elem_local);
                      }
                  }
                  Nom nom_fichier(sous_zone.le_nom() + Nom(".ssz"));
                  Cerr << " Subarea " << i_sous_zone
                       << "  file_name " << nom_fichier
                       << "  nb_elements in this part " << elements.size_array()
                       << finl;
// Le fichier sous-zones est toujours en ascii
                  SFichier os;
                  const int ok = os.ouvrir(nom_fichier, mode);
                  if (!ok)
                    {
                      Cerr << "DomaineCutter::ecrire_zones :\n Error while opening file"
                           << nom_fichier << finl;
                      exit();
                    }
                  os << elements;
                }
            }
        }
      if (reorder && loop==0)
        {
// Reduce the bandwith of a the matrix connectivity between parts:
// ToDo forcer a ne pas changer la partition 0 !
          ArrOfInt riord(nb_parties_+1);
          ArrOfInt levels(nb_parties_+1);
          ArrOfInt mask(nb_parties_+1);
          int maskval = 1;
          for (int i_part=0 ; i_part<nb_parties_+1; i_part++)
            mask[i_part] = maskval;
          int init=1;
          int nlev;
          F77NAME(PERPHN)(&nb_parties_, ja.addr(), ia.addr(), &init, mask.addr(), &maskval, &nlev, riord.addr(), levels.addr());
// Renumber the elem_part array:
          ArrOfInt renum(nb_parties_);
          for (int i_part=0; i_part < nb_parties_; i_part++)
            renum[riord[i_part]-1]=i_part;
          int size=elem_part.size_reelle();
          for (int i=0; i<size; i++)
            elem_part[i]=renum[elem_part[i]];
          elem_part.echange_espace_virtuel();
// Rebuild the liste_elems_sous_domaines_
          liste_elems_sous_domaines_.reset();
          calculer_listes_elements_sous_domaines(elem_part, nb_parties_, nbelem, liste_elems_sous_domaines_);
        }
      /*
      // Print statistics exactly as Fluent:
      // http://combust.hit.edu.cn:8080/fluent/Fluent60_help/html/ug/node984.htm
      Cerr << ">> Partitions:" << finl;
      Cerr << "
               P   Cells I-Cells Cell Ratio  Faces I-Faces Face Ratio Neighbors" << finl;
               0     134      10      0.075    217      10      0.046         1
               1     137      19      0.139    222      19      0.086         2
               2     134      19      0.142    218      19      0.087         2
               3     137      10      0.073    223      10      0.045         1
      Cerr << "------" << finl;
      Cerr << "Partition count             = " << nb_parties_ << finl;
      Cerr << "Cell variation              = (134 - 138)
      Cerr << "Mean cell variation         = (  -1.1% -    1.1%)
      Cerr << "Intercell variation         = (10 - 19)
      Cerr << "Intercell ratio variation   = (   7.3% -   14.2%);
      Cerr << "Global intercell ratio      =   10.7%
      Cerr << "Face variation              = (217 - 223)
      Cerr << "Interface variation         = (10 - 19)
      Cerr << "Interface ratio variation   = (   4.5% -    8.7%)
      Cerr << "Global interface ratio      =    3.4%
      Cerr << "Neighbor variation          = (1 - 2) */
    }
// if my part is shared with other procs, then my whole part may contain joints that I don't have
// calling mp_sum wouldn't be correct though, because the shared joints would be counted several times
// so we need to gather neighbours of each part
  if (Decouper::print_more_infos)   //!< involves communication: do it only if requested
    {
      if(Process::je_suis_maitre())
        {
          for(int proc=1; proc<Process::nproc(); proc++)
            {
              for(int i_part=0; i_part<nb_parties_; i_part++)
                {
                  if(otherProcZones[proc][i_part])
                    {
                      ArrOfInt tmp_neighbours;
                      tmp_neighbours.set_smart_resize(1);
                      recevoir(tmp_neighbours, proc, 0, proc+2003);
                      Neighbours[i_part].set_smart_resize(1);
                      for(int i=0; i<tmp_neighbours.size_array(); i++)
                        Neighbours[i_part].append_array(tmp_neighbours[i]);
                    }
                }
              ArrOfInt tmp_edge_cut(nb_parties_);
              tmp_edge_cut = 0;
              recevoir(tmp_edge_cut, proc, 0, proc+2008);
              for(int i_part=0; i_part<nb_parties_; i_part++)
                EdgeCut(i_part) += tmp_edge_cut[i_part];
            }
          Cout << "\nQuality of partitioning --------------------------------------------" << finl;
          int total_edge_cut = 0;
          for (int i_part=0; i_part<nb_parties_; i_part++)
            total_edge_cut+=EdgeCut(i_part);
          Cout << "Total number of edge-cut (faces shared by processes) : " << total_edge_cut << finl;
          if (total_edge_cut>0)
            {
              double mean_edgecut_zone = total_edge_cut / nb_parties_;
              int max_edgecut_zone = local_min_vect(EdgeCut);
              int min_edgecut_zone = local_max_vect(EdgeCut);
              double load_imbalance = double(max_edgecut_zone / mean_edgecut_zone);
              Cout << "Number of edge-cut per Zone (min/mean/max) : " << min_edgecut_zone  << " / "
                   << (int) (mean_edgecut_zone) << " / " << max_edgecut_zone  << " Load imbalance: " << load_imbalance
                   << "\n" << finl;
            }
          int mean_neighbours = 0;
          int min_neighbours = nb_parties_;
          int max_neighbours = 0;
          for (int i_part = 0; i_part < nb_parties_; i_part++)
            {
              Neighbours[i_part].array_trier_retirer_doublons();
              int nb_neighbours = Neighbours[i_part].size_array();
              mean_neighbours += nb_neighbours;
              if(nb_neighbours < min_neighbours)   min_neighbours = nb_neighbours;
              if(nb_neighbours > max_neighbours)   max_neighbours = nb_neighbours;
            }
          mean_neighbours/=nb_parties_;
          if (mean_neighbours>0)
            {
              double load_imbalance = double(max_neighbours / mean_neighbours);
              Cout << "Number of neighbours per Zone (min/mean/max) : " << min_neighbours << " / "
                   << (int) (mean_neighbours) << " / " <<max_neighbours << " Load imbalance: " << load_imbalance
                   << "\n" << finl;
            }
        }
      else
        {
          for(int i_part=0; i_part < nb_parties_; i_part++)
            if(myZones[i_part])
              envoyer(Neighbours[i_part], Process::me(), 0, Process::me()+2003);
          envoyer(EdgeCut, Process::me(), 0, Process::me()+2008);
        }
    }
  if (format == Decouper::HDF5_SINGLE)
    fic_hdf.close();
}
References Vect_Nom::add(), TRUSTArray< _TYPE_ >::addr(), TRUSTArray< _TYPE_ >::append_array(), Decouper::BINARY_MULTIPLE, calculer_listes_elements_sous_domaines(), Cerr, FichierHDF::close(), construire_nom_fichier_sous_domaine(), construire_sous_domaine(), Cout, FichierHDF::create(), FichierHDF::create_and_fill_dataset_SW(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Joint::ELEMENT, envoyer(), envoyer_broadcast(), Process::exit(), F77NAME, Zone::faces_joint(), FichierHDF::fill_dataset(), finl, Sortie_Brute::get_size(), Decouper::HDF5_SINGLE, IOS_OPEN_MODE, Joint_Items::items_communs(), Joint_Items::items_distants(), Process::je_suis_maitre(), Joint::joint_item(), Sous_Zone::le_nom(), LIST, liste_elems_sous_domaines_, DomaineCutter_Correspondance::liste_inverse_elements_, local_max_vect(), local_min_vect(), Process::me(), Process::mp_max(), Zone::nb_elem(), Sous_Zone::nb_elem_tot(), Frontiere::nb_faces(), nb_parties_, Domaine::nb_som(), nom_fichier(), Nom::nom_me(), Process::nproc(), Sortie_Fichier_base::ouvrir(), Joint::PEvoisin(), Decouper::print_more_infos, recevoir(), REF, ref_domaine_, Static_Int_Lists::reset(), TRUSTArray< _TYPE_ >::resize_array(), Sortie::set_bin(), TRUSTArray< _TYPE_ >::set_smart_resize(), liste::size(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_reelle(), Joint::SOMMET, Domaine::ss_zones(), Ref_Domaine::valeur(), writeData(), and Domaine::zone().
Referenced by ecrire_sous_zones().
get_info()
const Type_info * DomaineCutter::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 32 of file DomaineCutter.cpp.
info()
const Type_info * DomaineCutter::info () static
Definition at line 32 of file DomaineCutter.cpp.
initialiser()
void DomaineCutter::initialiser (const Domaine & domaine_global, const IntVect & elem_part, const int nb_parts, const int epaisseur_joint, const Noms & bords_periodiques, const int permissif = 0)
Prepare les structures de donnees pour la construction
des sous-domaines en fonction d'un decoupage fourni dans elem_part.
Parametre: domaine_global
Signification: le domaine a decouper (doit avoir une zone). On prend une ref
a ce domaine (il doit donc rester valide).
Parametre: elem_part
Signification: pour chaque element, numero du sous-domaine auquel il appartient,
avec 0 <= elem_part[i] < nb_parts. Attention, on prend une ref a ce tableau, on
ne fait pas une copie local. Le tableau doit continuer a exister jusqu'a ce qu'on
a fini d'utiliser DomaineCutter.
Parametre: nb_parts
Signification: nombre total de sous-domaines
Parametre: les_faces
Parametre: epaisseur_joint.
Definition at line 1061 of file DomaineCutter.cpp.
{
  assert(nb_parts >= 0);
  assert(domaine_global.nb_zones() == 1);
  assert(elem_part.size_array() == domaine_global.zone(0).nb_elem_tot());
  assert(max_array(elem_part) < nb_parts);
  if (min_array(elem_part)<0)
    {
      Cerr << "Error in DomaineCutter::initialiser" << finl;
      Cerr << "The built partition has a default." << finl;
      Cerr << "Try to change the partition tool or try changing some partitioning options." << finl;
      Cerr << "Contact TRUST support if you are still unsuccessful with your tries." << finl;
      Process::exit();
    }
  reset();
  ref_domaine_ = domaine_global;
  ref_elem_part_ = elem_part;
  nb_parties_ = nb_parts;
  epaisseur_joint_ = epaisseur_joint;
  liste_bords_periodiques_ = liste_bords_periodiques;
  const IntTab& elems = domaine_global.zone(0).les_elems();
  const int nb_som = domaine_global.nb_som_tot();
  construire_connectivite_som_elem(nb_som, elems, som_elem_,
                                   1 /* inclure les elems virtuels */);
  Cerr << "Search of neighboring elements of boundary faces" << finl;
  calculer_elements_voisins_bords(domaine_global, som_elem_, voisins_bords_,elem_part,permissif,bords_a_pb_);
  Cerr << "Construction of lists of elements per subdomain" << finl;
  calculer_listes_elements_sous_domaines(elem_part, nb_parts, elems.dimension(0), liste_elems_sous_domaines_);
// calculer_listes_elements_sous_domaines(elem_part, nb_parts, liste_elems_sous_domaines_);
}
References bords_a_pb_, calculer_elements_voisins_bords(), calculer_listes_elements_sous_domaines(), Cerr, construire_connectivite_som_elem(), TRUSTTab< _TYPE_ >::dimension(), epaisseur_joint_, Process::exit(), finl, Zone::les_elems(), liste_bords_periodiques_, liste_elems_sous_domaines_, max_array(), min_array(), Zone::nb_elem_tot(), nb_parties_, Domaine::nb_som_tot(), Domaine::nb_zones(), ref_domaine_, ref_elem_part_, reset(), TRUSTArray< _TYPE_ >::size_array(), som_elem_, voisins_bords_, and Domaine::zone().
Referenced by ecrire_sous_zones(), and Create_domain_from_sous_zone::interpreter_().
operator=()
const DomaineCutter & DomaineCutter::operator= (const DomaineCutter & dc) private
Appel invalide. exit.
< pour le compilateur
Definition at line 35 of file DomaineCutter.cpp.
{
  exit();
  return *this; //!< pour le compilateur
}
References Process::exit().
printOn()
Sortie & DomaineCutter::printOn (Sortie & x) const override protected virtual
Appel invalide. exit.
< pour le compilateur
Reimplemented from Objet_U.
Definition at line 48 of file DomaineCutter.cpp.
{
  Cerr << "Error : DomaineCutter::printOn should not be used." << finl;
  exit();
  return os; //!< pour le compilateur
}
References Cerr, Process::exit(), and finl.
readOn()
Entree & DomaineCutter::readOn (Entree & s) override protected virtual
Appel invalide. exit.
< pour le compilateur
Reimplemented from Objet_U.
Definition at line 56 of file DomaineCutter.cpp.
{
  Cerr << "Error : DomaineCutter::readOn should not be used." << finl;
  exit();
  return s; //!< pour le compilateur
}
References Cerr, Process::exit(), and finl.
reset()
void DomaineCutter::reset ()
annule toutes les references et vide les tableaux
Definition at line 964 of file DomaineCutter.cpp.
{
  ref_domaine_.reset();
  ref_elem_part_.reset();
  nb_parties_ = -1;
  epaisseur_joint_ = -1;
  som_elem_.reset();
}
References epaisseur_joint_, nb_parties_, ref_domaine_, ref_elem_part_, Ref_::reset(), Static_Int_Lists::reset(), and som_elem_.
Referenced by initialiser().
self_cast() [1/2]
const DomaineCutter & DomaineCutter::self_cast (const Objet_U & r) static
Definition at line 32 of file DomaineCutter.cpp.
self_cast() [2/2]
DomaineCutter & DomaineCutter::self_cast (Objet_U & r) static
Definition at line 32 of file DomaineCutter.cpp.
taille_memoire()
unsigned DomaineCutter::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 32 of file DomaineCutter.cpp.
writeData()
void DomaineCutter::writeData (const Domaine & sous_domaine, Sortie & os) const private
Definition at line 1249 of file DomaineCutter.cpp.
{
  os << sous_domaine;
// Benoit Mathieu: Scatter a besoin de la liste des bords periodiques pour le
// calcul des elements distants. Je l'ecris apres le domaine dans le fichier .Zones.
// Pas genial mais c'est pour depanner en attendant mieux.
  os << liste_bords_periodiques_;
}
References liste_bords_periodiques_.
Referenced by ecrire_zones().
Member Data Documentation
bords_a_pb_
Noms DomaineCutter::bords_a_pb_ private
Definition at line 107 of file DomaineCutter.h.
Referenced by bords_internes(), and initialiser().
epaisseur_joint_
int DomaineCutter::epaisseur_joint_ private
Definition at line 99 of file DomaineCutter.h.
Referenced by construire_elements_distants_ssdom(), construire_sommets_joints_ssdom(), DomaineCutter(), initialiser(), and reset().
info_obj
const Type_info DomaineCutter::info_obj static
Definition at line 35 of file DomaineCutter.h.
liste_bords_periodiques_
Noms DomaineCutter::liste_bords_periodiques_ private
Definition at line 95 of file DomaineCutter.h.
Referenced by initialiser(), and writeData().
liste_elems_sous_domaines_
Static_Int_Lists DomaineCutter::liste_elems_sous_domaines_ private
Definition at line 103 of file DomaineCutter.h.
Referenced by construire_sous_domaine(), ecrire_zones(), and initialiser().
nb_parties_
int DomaineCutter::nb_parties_ private
Definition at line 97 of file DomaineCutter.h.
Referenced by construire_faces_joints_ssdom(), construire_sommets_joints_ssdom(), construire_sous_domaine(), DomaineCutter(), ecrire_zones(), initialiser(), and reset().
ref_domaine_
Ref_Domaine DomaineCutter::ref_domaine_ private
Definition at line 90 of file DomaineCutter.h.
Referenced by construire_elements_distants_ssdom(), construire_faces_bords_ssdom(), construire_faces_internes_ssdom(), construire_faces_joints_ssdom(), construire_faces_raccords_ssdom(), construire_sous_domaine(), ecrire_zones(), initialiser(), and reset().
ref_elem_part_
Ref_IntVect DomaineCutter::ref_elem_part_ private
Definition at line 93 of file DomaineCutter.h.
Referenced by construire_elements_distants_ssdom(), construire_faces_bords_ssdom(), construire_faces_internes_ssdom(), construire_faces_joints_ssdom(), construire_faces_raccords_ssdom(), construire_sommets_joints_ssdom(), initialiser(), and reset().
som_elem_
Static_Int_Lists DomaineCutter::som_elem_ private
Definition at line 101 of file DomaineCutter.h.
Referenced by construire_elements_distants_ssdom(), construire_faces_joints_ssdom(), construire_sommets_joints_ssdom(), initialiser(), and reset().
voisins_bords_
Static_Int_Lists DomaineCutter::voisins_bords_ private
Definition at line 106 of file DomaineCutter.h.
Referenced by construire_faces_bords_ssdom(), construire_faces_internes_ssdom(), construire_faces_raccords_ssdom(), and initialiser().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/DomaineCutter.h
src/Kernel/Geometrie/DomaineCutter.cpp