TRUST: RK4_D3P Class Reference
RK4_D3P Class Reference
classe RK4_D3P
Cette classe represente un schema en temps de Runge Kutta d'ordre 4
degnere (schema a trois points)
(cas 17 de Williamson) s'ecrit :
q1=h f(x0)
x1=x0+b1 q1
q2=h f(x1) +a2 q1
x2=x1+b2 q2
q3=h f(x2)+a3 q2
x3=x2+b3 q3
avec a1=0, a2=-1/2, a3=-2
b1=1/2, b2=1, b3=1/6
#include <RK4_D3P.h>
Public Member Functions
RK4_D3P ()
~RK4_D3P ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int nb_valeurs_temporelles () const
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n et n+1, donc 2.
virtual int nb_valeurs_futures () const
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1, donc 1.
virtual double temps_futur (int i) const
Renvoie le le temps a la i-eme valeur future.
Ici : t(n+1)
virtual double temps_defaut () const
Renvoie le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : t(n+1)
virtual int faire_un_pas_de_temps_eqn_base (Equation_base &)
Effectue un pas de temps de Runge Kutta d'ordre 4,
sur l'equation passee en parametre.
Le schema de Runge Kutta d'ordre 4
degnere (schema a trois points)
(cas 17 de Williamson) s'ecrit :
q1=h f(x0)
x1=x0+b1 q1
q2=h f(x1) +a2 q1
x2=x1+b2 q2
q3=h f(x2)+a3 q2
x3=x2+b3 q3
avec a1=0, a2=-1/2, a3=-2
b1=1/2, b2=1, b3=1/6.
void completer ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static RK4_D3P & self_cast (Objet_U &)
static const RK4_D3P & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Detailed Description
classe RK4_D3P
Cette classe represente un schema en temps de Runge Kutta d'ordre 4
degnere (schema a trois points)
(cas 17 de Williamson) s'ecrit :
q1=h f(x0)
x1=x0+b1 q1
q2=h f(x1) +a2 q1
x2=x1+b2 q2
q3=h f(x2)+a3 q2
x3=x2+b3 q3
avec a1=0, a2=-1/2, a3=-2
b1=1/2, b2=1, b3=1/6
Definition at line 50 of file RK4_D3P.h.
Constructor & Destructor Documentation
RK4_D3P::RK4_D3P ()
Definition at line 26 of file RK4_D3P.cpp.
RK4_D3P::~RK4_D3P ()
Definition at line 26 of file RK4_D3P.cpp.
Member Function Documentation
void RK4_D3P::completer (void) [inline, virtual]
Implements Schema_Temps_base.
Definition at line 90 of file RK4_D3P.h.
{
}
Objet_U * RK4_D3P::cree_instance () [static]
Definition at line 26 of file RK4_D3P.cpp.
int RK4_D3P::duplique () const [virtual]
Implements Schema_Temps_base.
Definition at line 26 of file RK4_D3P.cpp.
int RK4_D3P::faire_un_pas_de_temps_eqn_base (Equation_base & eqn) [virtual]
Effectue un pas de temps de Runge Kutta d'ordre 4,
sur l'equation passee en parametre.
Le schema de Runge Kutta d'ordre 4
degnere (schema a trois points)
(cas 17 de Williamson) s'ecrit :
q1=h f(x0)
x1=x0+b1 q1
q2=h f(x1) +a2 q1
x2=x1+b2 q2
q3=h f(x2)+a3 q2
x3=x2+b3 q3
avec a1=0, a2=-1/2, a3=-2
b1=1/2, b2=1, b3=1/6.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Implements Schema_Temps_base.
Definition at line 146 of file RK4_D3P.cpp.
References DoubleVect::ajoute(), Cerr, Equation_base::derivee_en_temps_inco(), Schema_Temps_base::dt_, DoubleVect::echange_espace_virtuel(), Schema_Temps_base::facsec_, finl, Champ_Inc::futur(), Zone_Cl_dis::imposer_cond_lim(), Equation_base::inconnue(), Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::temps_courant(), Schema_Temps_base::update_critere_statio(), Champ_Inc::valeurs(), and Equation_base::zone_Cl_dis().
{
// Warning sur les 100 premiers pas de temps si facsec est egal a 1
// pour faire reflechir l'utilisateur
  int nw = 100;
  if ( nb_pas_dt()>=0 && nb_pas_dt()<=nw && facsec_ == 1 )
    {
      Cerr << finl << "**** Advice (printed only on the first " << nw << " time steps)****" << finl;
      Cerr << "You are using Runge Kutta schema order 4 so if you wish to increase the time step, try facsec between 1 and 4." << finl;
    }
  double a2=-1./2.;
  double a3=-2.;
  double b1=1./2.;
  double b2=1.;
  double b3=1./6.;
  DoubleTab& xi=eqn.inconnue().valeurs();
  DoubleTab& xipls1=eqn.inconnue().futur();
  DoubleTab  qi(xi) ;
  DoubleTab present(xi);
// qi=futur=f(y0)
  eqn.derivee_en_temps_inco(qi);
// q1=h f(x0)
  qi *= dt_;
// x1=x0+b1 q1
  xi.ajoute(b1, qi);
// q2=h f(x1) +a2 q1
  qi*=a2;
  eqn.derivee_en_temps_inco(xipls1);
  qi.ajoute(dt_,xipls1);
// x2=x1+b2 q2
  xi.ajoute(b2, qi);
// q3=h f(x2)+a3 q2
  qi*=a3;
  eqn.derivee_en_temps_inco(xipls1);
  qi.ajoute(dt_,xipls1);
// x3=x2+b3 q3
  xi.ajoute(b3, qi);
  xipls1=xi;
  xi -= present;
  xi /= dt_;
  update_critere_statio(xi, eqn);
  eqn.zone_Cl_dis().imposer_cond_lim(eqn.inconnue(),temps_courant()+pas_de_temps());
  xipls1.echange_espace_virtuel();
  xi=present;
  return 1;
}
const Type_info * RK4_D3P::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 26 of file RK4_D3P.cpp.
const Type_info * RK4_D3P::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 26 of file RK4_D3P.cpp.
int RK4_D3P::nb_valeurs_futures () const [virtual]
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1, donc 1.
Implements Schema_Temps_base.
Definition at line 89 of file RK4_D3P.cpp.
{
  return 1 ;
}
int RK4_D3P::nb_valeurs_temporelles () const [virtual]
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n et n+1, donc 2.
Implements Schema_Temps_base.
Definition at line 81 of file RK4_D3P.cpp.
{
  return 2 ;
}
Sortie & RK4_D3P::printOn (Sortie & s) const [protected, virtual]
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 44 of file RK4_D3P.cpp.
{
  return  Schema_Temps_base::printOn(s);
}
Entree & RK4_D3P::readOn (Entree & s) [protected, virtual]
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 65 of file RK4_D3P.cpp.
{
  return Schema_Temps_base::readOn(s) ;
}
const RK4_D3P & RK4_D3P::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Schema_Temps_base.
Definition at line 26 of file RK4_D3P.cpp.
RK4_D3P & RK4_D3P::self_cast (Objet_U & r) [static]
Reimplemented from Schema_Temps_base.
Definition at line 26 of file RK4_D3P.cpp.
unsigned RK4_D3P::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file RK4_D3P.cpp.
double RK4_D3P::temps_defaut () const [virtual]
Renvoie le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : t(n+1)
Implements Schema_Temps_base.
Definition at line 107 of file RK4_D3P.cpp.
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
{
  return temps_courant()+pas_de_temps();
}
double RK4_D3P::temps_futur (int i) const [virtual]
Renvoie le le temps a la i-eme valeur future.
Ici : t(n+1)
Implements Schema_Temps_base.
Definition at line 97 of file RK4_D3P.cpp.
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
{
  assert(i==1);
  return temps_courant()+pas_de_temps();
}
Member Data Documentation
const Type_info RK4_D3P::info_obj [static]
Reimplemented from Schema_Temps_base.
Definition at line 53 of file RK4_D3P.h.
The documentation for this class was generated from the following files:
src/Kernel/Schemas_Temps/RK4_D3P.h
src/Kernel/Schemas_Temps/RK4_D3P.cpp