TRUST: Eval_Diff_VDF_const Class Reference
Eval_Diff_VDF_const Class Reference
class Eval_Diff_VDF_const
Cette classe represente un evaluateur de flux diffusif
avec un coefficient de diffusivite qui est isotrope et constant en espace.
#include <Eval_Diff_VDF_const.h>
Public Member Functions
Eval_Diff_VDF_const ()
void associer (const Champ_base &) override
void mettre_a_jour () override
const Champ_base & get_diffusivite () const override
double nu_1_impl (int i, int compo) const
double nu_2_impl (int i, int compo) const
double compute_heq_impl (double d0, int i, double d1, int j, int compo) const
double nu_1_impl_face (int i, int j, int compo) const
double nu_2_impl_face (int i, int j, int k, int l, int compo) const
double nu_lam_impl_face (int i, int j, int k, int l, int compo) const
double nu_lam_impl_face2 (int i, int j, int compo) const
double nu_t_impl (int i, int compo) const
double tau_tan_impl (int i, int j) const
bool uses_wall () const
bool uses_mod () const
const DoubleTab & get_k_elem () const
pour F5 seulement ...
Public Member Functions inherited from Eval_Diff_VDF
virtual ~Eval_Diff_VDF ()
virtual const Champ_base & get_diffusivite () const =0
virtual void associer (const Champ_base &)=0
virtual void mettre_a_jour ()
int get_ind_Fluctu_Term () const
double get_dv_mvol (const int i) const
virtual double get_equivalent_distance (int boundary_index, int local_face) const
Protected Attributes
Ref_Champ_Uniforme diffusivite_
double db_diffusivite
Detailed Description
class Eval_Diff_VDF_const
Cette classe represente un evaluateur de flux diffusif
avec un coefficient de diffusivite qui est isotrope et constant en espace.
Definition at line 30 of file Eval_Diff_VDF_const.h.
Constructor & Destructor Documentation
Eval_Diff_VDF_const()
Eval_Diff_VDF_const::Eval_Diff_VDF_const () inline
Definition at line 34 of file Eval_Diff_VDF_const.h.
:db_diffusivite(-1.0e+300) {}
Member Function Documentation
associer()
void Eval_Diff_VDF_const::associer (const Champ_base & diffu) inline override virtual
Implements Eval_Diff_VDF.
Definition at line 58 of file Eval_Diff_VDF_const.h.
{
  diffusivite_ = ref_cast(Champ_Uniforme, diffu);
  db_diffusivite = diffusivite_.valeur()(0,0);
}
References db_diffusivite, diffusivite_, ref_cast, and Ref_Champ_Uniforme::valeur().
compute_heq_impl()
double Eval_Diff_VDF_const::compute_heq_impl (double d0, int i, double d1, int j, int compo) const inline
Definition at line 42 of file Eval_Diff_VDF_const.h.
{ return db_diffusivite/(d0+d1); }
References db_diffusivite.
Referenced by Eval_Dift_VDF_const::compute_heq_impl().
get_diffusivite()
const Champ_base & Eval_Diff_VDF_const::get_diffusivite () const inline override virtual
Implements Eval_Diff_VDF.
Definition at line 64 of file Eval_Diff_VDF_const.h.
{
  assert(diffusivite_.non_nul());
  return diffusivite_.valeur();
}
References diffusivite_, O_U_Ptr::non_nul(), and Ref_Champ_Uniforme::valeur().
get_k_elem()
const DoubleTab & Eval_Diff_VDF_const::get_k_elem () const inline
pour F5 seulement ...
Definition at line 51 of file Eval_Diff_VDF_const.h.
mettre_a_jour()
void Eval_Diff_VDF_const::mettre_a_jour () inline override virtual
Reimplemented from Eval_Diff_VDF.
Reimplemented in Eval_Dift_VDF_const, and Eval_Dift_VDF_const_Face.
Definition at line 36 of file Eval_Diff_VDF_const.h.
{ db_diffusivite = diffusivite_.valeur()(0,0); }
References db_diffusivite, diffusivite_, and Ref_Champ_Uniforme::valeur().
Referenced by Eval_Dift_VDF_const::mettre_a_jour().
nu_1_impl()
double Eval_Diff_VDF_const::nu_1_impl (int i, int compo) const inline
Definition at line 40 of file Eval_Diff_VDF_const.h.
{ return db_diffusivite; }
References db_diffusivite.
Referenced by Eval_Dift_VDF_const::nu_1_impl().
nu_1_impl_face()
double Eval_Diff_VDF_const::nu_1_impl_face (int i, int j, int compo) const inline
Definition at line 43 of file Eval_Diff_VDF_const.h.
{ return db_diffusivite; }
References db_diffusivite.
Referenced by nu_lam_impl_face2(), and Eval_Dift_VDF_const::nu_lam_impl_face2().
nu_2_impl()
double Eval_Diff_VDF_const::nu_2_impl (int i, int compo) const inline
Definition at line 41 of file Eval_Diff_VDF_const.h.
{ return db_diffusivite; }
References db_diffusivite.
Referenced by Eval_Dift_VDF_const::nu_2_impl().
nu_2_impl_face()
double Eval_Diff_VDF_const::nu_2_impl_face (int i, int j, int k, int l, int compo) const inline
Definition at line 44 of file Eval_Diff_VDF_const.h.
{ return db_diffusivite; }
References db_diffusivite.
Referenced by nu_lam_impl_face(), and Eval_Dift_VDF_const::nu_lam_impl_face().
nu_lam_impl_face()
double Eval_Diff_VDF_const::nu_lam_impl_face (int i, int j, int k, int l, int compo) const inline
Definition at line 45 of file Eval_Diff_VDF_const.h.
{ return nu_2_impl_face(i,j,k,l,compo); }
References nu_2_impl_face().
nu_lam_impl_face2()
double Eval_Diff_VDF_const::nu_lam_impl_face2 (int i, int j, int compo) const inline
Definition at line 46 of file Eval_Diff_VDF_const.h.
{ return nu_1_impl_face(i,j,compo); }
References nu_1_impl_face().
nu_t_impl()
double Eval_Diff_VDF_const::nu_t_impl (int i, int compo) const inline
Definition at line 47 of file Eval_Diff_VDF_const.h.
{ return 0.; }
tau_tan_impl()
double Eval_Diff_VDF_const::tau_tan_impl (int i, int j) const inline
Definition at line 48 of file Eval_Diff_VDF_const.h.
{ return 0.; }
uses_mod()
bool Eval_Diff_VDF_const::uses_mod () const inline
Definition at line 50 of file Eval_Diff_VDF_const.h.
{ return false; }
uses_wall()
bool Eval_Diff_VDF_const::uses_wall () const inline
Definition at line 49 of file Eval_Diff_VDF_const.h.
{ return false; }
Member Data Documentation
db_diffusivite
double Eval_Diff_VDF_const::db_diffusivite protected
Definition at line 55 of file Eval_Diff_VDF_const.h.
Referenced by associer(), compute_heq_impl(), mettre_a_jour(), nu_1_impl(), nu_1_impl_face(), nu_2_impl(), and nu_2_impl_face().
diffusivite_
Ref_Champ_Uniforme Eval_Diff_VDF_const::diffusivite_ protected
Definition at line 54 of file Eval_Diff_VDF_const.h.
Referenced by associer(), get_diffusivite(), and mettre_a_jour().
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Eval_Diff_Dift/Eval_Diff_VDF_const.h