TRUST: Extruder Class Reference
Extruder Class Reference
Classe Extruder
Cette classe est un interprete qui sert a lire et executer
la directive Extruder:
Extruder nom_domaine
Cette directive est a utiliser en discretisation VEF 2D pour obtenir
un maillage 3D par extrusion puis decoupage.
#include <Extruder.h>
Public Member Functions
~Extruder ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Extruder ()
Entree & interpreter_ (Entree &) override
Fonction principale de l'interprete Extruder
Triangule 1 a 1 toutes les zones du domaine
specifie par la directive.
On triangule la zone grace a la methode:
void Extruder::extruder(Zone& zone) const
Extruder signifie ici transformer en triangle des
elements geometrique d'une zone.
void setDirection (double lx, double ly, double lz)
void setNbTranches (int n)
void extruder (Domaine &)
Triangule tous les element d'une zone: transforme
les elements goemetriques de la zone en triangles.
Pour l'instant on ne sait raffiner que des Rectangles<br>(on les coupe en 4).
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Extruder & self_cast (Objet_U &)
static const Extruder & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
void extruder_hexa (Domaine &)
virtual void extruder_dvt (Domaine &, Faces &, int, int)
virtual void extruder_dvt_hexa (Domaine &, Faces &, int, int)
Protected Member Functions inherited from Interprete_geometrique_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
ArrOfDouble direction
int NZ
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Private Member Functions
void traiter_faces_dvt_hexa (Faces &, int)
void traiter_faces_dvt (Faces &, Faces &, int, int, int)
Detailed Description
Classe Extruder
Cette classe est un interprete qui sert a lire et executer
la directive Extruder:
Extruder nom_domaine
Cette directive est a utiliser en discretisation VEF 2D pour obtenir
un maillage 3D par extrusion puis decoupage.
Definition at line 38 of file Extruder.h.
Constructor & Destructor Documentation
~Extruder()
Extruder::~Extruder ()
Definition at line 24 of file Extruder.cpp.
Extruder()
Extruder::Extruder ()
Definition at line 25 of file Extruder.cpp.
{
  direction.resize(3,Array_base::NOCOPY_NOINIT);
}
References direction, Array_base::NOCOPY_NOINIT, and TRUSTArray< _TYPE_ >::resize().
Member Function Documentation
cree_instance()
Objet_U * Extruder::cree_instance () static
Definition at line 24 of file Extruder.cpp.
duplique()
int Extruder::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Extruder.cpp.
extruder()
void Extruder::extruder (Domaine & dom)
Triangule tous les element d'une zone: transforme
les elements goemetriques de la zone en triangles.
Pour l'instant on ne sait raffiner que des Rectangles<br>(on les coupe en 4).
< Tableau dont on aura pas besoin
< les nouveaux elements
Definition at line 133 of file Extruder.cpp.
{
  Zone& zone = dom.zone(0);
  if((zone.type_elem()->que_suis_je() == "Rectangle" || zone.type_elem()->que_suis_je() ==  "Quadrangle" ))
    {
      extruder_hexa(dom);
    }
  else if( zone.type_elem()->que_suis_je() == "Triangle")
    {
      int oldnbsom = zone.nb_som();
      IntTab& les_elems=zone.les_elems();
      int oldsz=les_elems.dimension(0);
      double dx = direction[0]/NZ;
      double dy = direction[1]/NZ;
      double dz = direction[2]/NZ;
      Faces les_faces;
// zone.creer_faces(les_faces);
      {
// bloc a factoriser avec Zone_VF.cpp :
        Type_Face type_face = zone.type_elem().type_face(0);
        les_faces.typer(type_face);
        les_faces.associer_zone(zone);
        Static_Int_Lists connectivite_som_elem;
        const int     nb_sommets_tot = zone.domaine().nb_som_tot();
        const IntTab&    elements       = zone.les_elems();
        construire_connectivite_som_elem(nb_sommets_tot,
                                         elements,
                                         connectivite_som_elem,
                                         1 /* include virtual elements */);
        Faces_builder faces_builder;
        IntTab elem_faces; //!< Tableau dont on aura pas besoin
        faces_builder.creer_faces_reeles(zone,
                                         connectivite_som_elem,
                                         les_faces,
                                         elem_faces);
      }
      const int nbfaces2D = les_faces.nb_faces();
      int newnbsom = oldnbsom*(NZ+1)+NZ*oldsz+nbfaces2D*NZ;
      DoubleTab new_soms(newnbsom, 3);
      DoubleTab& coord_sommets=dom.les_sommets();
      Objet_U::dimension=3;
// les sommets du maillage 2D sont translates en premier
      for (int i=0; i<oldnbsom; i++)
        {
          double x = coord_sommets(i,0);
          double y = coord_sommets(i,1);
          double z=0.;
          if (coord_sommets.dimension(1)>2)
            z=coord_sommets(i,2);
          for (int k=0; k<=NZ; k++)
            {
              new_soms(k*oldnbsom+i,0)=x;
              new_soms(k*oldnbsom+i,1)=y;
              new_soms(k*oldnbsom+i,2)=z;
              x += dx;
              y += dy;
              z += dz;
            }
        }
// puis on cree les centres de gravite des elements 2D puis translation de ces points
      for (int i=0; i<oldsz; i++)
        {
          int i0=les_elems(i,0);
          int i1=les_elems(i,1);
          int i2=les_elems(i,2);
          double xg = 1./3.*(coord_sommets(i0,0)+coord_sommets(i1,0)+coord_sommets(i2,0))+0.5*dx;
          double yg = 1./3.*(coord_sommets(i0,1)+coord_sommets(i1,1)+coord_sommets(i2,1))+0.5*dy;
          double z = 0.5*dz;
          if (coord_sommets.dimension(1)>2)
            z = 1./3.*(coord_sommets(i0,2)+coord_sommets(i1,2)+coord_sommets(i2,2))+0.5*dz;
          for (int k=0; k<NZ; k++)
            {
              new_soms(oldnbsom*(NZ+1)+k*oldsz+i,0)=xg;
              new_soms(oldnbsom*(NZ+1)+k*oldsz+i,1)=yg;
              new_soms(oldnbsom*(NZ+1)+k*oldsz+i,2)=z;
              xg += dx;
              yg += dy;
              z += dz;
            }
        }
// enfin, on cree les centres des faces du maillage 2D puis translation de ces points
      for (int i=0; i<nbfaces2D; i++)
        {
          int i0=les_faces.sommet(i,0);
          int i1=les_faces.sommet(i,1);
          double x01 = 0.5*(coord_sommets(i0,0)+coord_sommets(i1,0))+0.5*dx;
          double y01 = 0.5*(coord_sommets(i0,1)+coord_sommets(i1,1))+0.5*dy;
          double z = 0.5*dz;
          if (coord_sommets.dimension(1)>2)
            z = 0.5*(coord_sommets(i0,2)+coord_sommets(i1,2))+0.5*dz;
          for (int k=0; k<NZ; k++)
            {
              new_soms(oldnbsom*(NZ+1)+NZ*oldsz+k*nbfaces2D+i,0)=x01;
              new_soms(oldnbsom*(NZ+1)+NZ*oldsz+k*nbfaces2D+i,1)=y01;
              new_soms(oldnbsom*(NZ+1)+NZ*oldsz+k*nbfaces2D+i,2)=z;
              x01 += dx;
              y01 += dy;
              z += dz;
            }
        }
      coord_sommets.resize(0);
      dom.ajouter(new_soms);
      int newnbelem = 14*NZ*oldsz;
      IntTab new_elems(newnbelem, 4); //!< les nouveaux elements
      int cpt=0;
// en premier, on stocke les tetra du haut et du bas : NZ*nb_triangle*2 tetra
      for (int i=0; i<oldsz; i++)
        {
          int i0=les_elems(i,0);
          int i1=les_elems(i,1);
          int i2=les_elems(i,2);
          int ig=oldnbsom*(NZ+1)+i;
          for (int k=0; k<NZ; k++)
            {
              new_elems(2*k*oldsz+2*i,0) = i0;
              new_elems(2*k*oldsz+2*i,1) = i1;
              new_elems(2*k*oldsz+2*i,2) = i2;
              new_elems(2*k*oldsz+2*i,3) = ig;
              cpt++;
              new_elems(2*k*oldsz+2*i+1,0) = i0+oldnbsom;
              new_elems(2*k*oldsz+2*i+1,1) = i1+oldnbsom;
              new_elems(2*k*oldsz+2*i+1,2) = i2+oldnbsom;
              new_elems(2*k*oldsz+2*i+1,3) = ig;
              cpt++;
              mettre_a_jour_sous_zone(zone,i,2*k*oldsz+2*i,2);
              i0+=oldnbsom;
              i1+=oldnbsom;
              i2+=oldnbsom;
              ig+=oldsz;
            }
        }
// puis les autres tetras
      for (int i=0; i<nbfaces2D; i++)
        {
          for (int ivois=0; ivois<2; ivois++)
            {
              int elem = les_faces.voisin(i,ivois);
              if (elem>=0)
                {
                  int i0=les_faces.sommet(i,0);
                  int i1=les_faces.sommet(i,1);
                  int i01=oldnbsom*(NZ+1)+NZ*oldsz+i;
                  for (int k=0; k<NZ; k++)
                    {
                      int ig=oldnbsom*(NZ+1)+k*oldsz+elem;
                      new_elems(cpt,0) = i0;
                      new_elems(cpt,1) = i1;
                      new_elems(cpt,2) = i01;
                      new_elems(cpt++,3) = ig;
                      new_elems(cpt,0) = i0+oldnbsom;
                      new_elems(cpt,1) = i1+oldnbsom;
                      new_elems(cpt,2) = i01;
                      new_elems(cpt++,3) = ig;
                      new_elems(cpt,0) = i1;
                      new_elems(cpt,1) = i1+oldnbsom;
                      new_elems(cpt,2) = i01;
                      new_elems(cpt++,3) = ig;
                      new_elems(cpt,0) = i0;
                      new_elems(cpt,1) = i0+oldnbsom;
                      new_elems(cpt,2) = i01;
                      new_elems(cpt++,3) = ig;
                      i0+=oldnbsom;
                      i1+=oldnbsom;
                      i01+=nbfaces2D;
                      ig+=oldsz;
                    }
                }
            }
        }
      les_elems.ref(new_elems);
// Reconstruction de l'octree
      zone.invalide_octree();
      zone.typer("Tetraedre");
      extruder_dvt(dom, les_faces,oldnbsom, oldsz);
    }
  else
    {
      Cerr << "It is not known yet how to extrude "
           << zone.type_elem()->que_suis_je() <<"s"<<finl;
      exit();
    }
}
References Domaine::ajouter(), Faces::associer_zone(), Cerr, construire_connectivite_som_elem(), Faces_builder::creer_faces_reeles(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, direction, Zone::domaine(), Process::exit(), extruder_dvt(), extruder_hexa(), finl, Zone::invalide_octree(), Zone::les_elems(), Domaine::les_sommets(), Interprete_geometrique_base::mettre_a_jour_sous_zone(), Faces::nb_faces(), Zone::nb_som(), Domaine::nb_som_tot(), NZ, Objet_U::que_suis_je(), TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), Faces::sommet(), Zone::type_elem(), Elem_geom::type_face(), Faces::typer(), Zone::typer(), Faces::voisin(), and Domaine::zone().
Referenced by ExtrudeBord::extruder_bord(), and interpreter_().
extruder_dvt()
void Extruder::extruder_dvt (Domaine & dom, Faces & les_faces, int oldnbsom, int oldsz) protected virtual
Definition at line 429 of file Extruder.cpp.
{
  Zone& zone = dom.zone(0);
  const int nbfaces2D = les_faces.nb_faces();
  IntTab& les_elems=zone.les_elems();
  {
    LIST_CURSEUR(Bord) curseur(zone.faces_bord());
    while(curseur)
      {
        check_boundary_name(curseur->le_nom());
        Faces& les_faces_bord=curseur->faces();
        traiter_faces_dvt(les_faces_bord, les_faces, oldnbsom, oldsz, nbfaces2D );
        ++curseur;
      }
  }
  {
    LIST_CURSEUR(Raccord) curseur(zone.faces_raccord());
    while(curseur)
      {
        check_boundary_name(curseur->le_nom());
        Faces& les_faces_bord=curseur.valeur()->faces();
        traiter_faces_dvt(les_faces_bord, les_faces, oldnbsom, oldsz, nbfaces2D );
        ++curseur;
      }
  }
  Bord& devant = zone.faces_bord().add(Bord());
  devant.nommer("devant");
  Faces& les_faces_dvt=devant.faces();
  les_faces_dvt.typer(Faces::triangle_3D);
  IntTab som_dvt(oldsz, 3);
  les_faces_dvt.voisins().resize(oldsz, 2);
  les_faces_dvt.voisins()=-1;
  Bord& derriere = zone.faces_bord().add(Bord());
  derriere.nommer("derriere");
  Faces& les_faces_der=derriere.faces();
  les_faces_der.typer(Faces::triangle_3D);
  IntTab som_der(oldsz, 3);
  les_faces_der.voisins().resize(oldsz, 2);
  les_faces_der.voisins()=-1;
  for (int i=0; i<oldsz; i++)
    {
      int i0=les_elems(2*i,0);
      int i1=les_elems(2*i,1);
      int i2=les_elems(2*i,2);
      som_dvt(i,0) = i0;
      som_dvt(i,1) = i1;
      som_dvt(i,2) = i2;
      som_der(i,0) = i0+oldnbsom*NZ;
      som_der(i,1) = i1+oldnbsom*NZ;
      som_der(i,2) = i2+oldnbsom*NZ;
    }
  les_faces_dvt.les_sommets().ref(som_dvt);
  les_faces_der.les_sommets().ref(som_der);
}
References List_Bord::add(), check_boundary_name(), Frontiere::faces(), Zone::faces_bord(), Zone::faces_raccord(), Zone::les_elems(), Faces::les_sommets(), LIST_CURSEUR, Faces::nb_faces(), Frontiere::nommer(), NZ, TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), traiter_faces_dvt(), Faces::triangle_3D, Faces::typer(), Faces::voisins(), and Domaine::zone().
Referenced by extruder().
extruder_dvt_hexa()
void Extruder::extruder_dvt_hexa (Domaine & dom, Faces & les_faces, int oldnbsom, int oldsz) protected virtual
Definition at line 633 of file Extruder.cpp.
{
  Zone& zone = dom.zone(0);
  IntTab& les_elems=zone.les_elems();
  {
    LIST_CURSEUR(Bord) curseur(zone.faces_bord());
    while(curseur)
      {
        check_boundary_name(curseur->le_nom());
        Faces& les_faces_bord=curseur->faces();
        traiter_faces_dvt_hexa(les_faces_bord, oldnbsom);
        ++curseur;
      }
  }
  {
    LIST_CURSEUR(Raccord) curseur(zone.faces_raccord());
    while(curseur)
      {
        check_boundary_name(curseur->le_nom());
        Faces& les_faces_bord=curseur.valeur()->faces();
        traiter_faces_dvt_hexa(les_faces_bord, oldnbsom);
        ++curseur;
      }
  }
  Bord& devant = zone.faces_bord().add(Bord());
  devant.nommer("devant");
  Faces& les_faces_dvt=devant.faces();
  les_faces_dvt.typer(Faces::quadrangle_3D);
  IntTab som_dvt(oldsz, 4);
  les_faces_dvt.voisins().resize(oldsz, 2);
  les_faces_dvt.voisins()=-1;
  Bord& derriere = zone.faces_bord().add(Bord());
  derriere.nommer("derriere");
  Faces& les_faces_der=derriere.faces();
  les_faces_der.typer(Faces::quadrangle_3D);
  IntTab som_der(oldsz, 4);
  les_faces_der.voisins().resize(oldsz, 2);
  les_faces_der.voisins()=-1;
  for (int i=0; i<oldsz; i++)
    {
      int i0=les_elems(i,0);
      int i1=les_elems(i,1);
      int i2=les_elems(i,2);
      int i3=les_elems(i,3);
      som_dvt(i,0) = i0;
      som_dvt(i,1) = i1;
      som_dvt(i,2) = i2;
      som_dvt(i,3) = i3;
      som_der(i,0) = i0+oldnbsom*NZ;
      som_der(i,1) = i1+oldnbsom*NZ;
      som_der(i,2) = i2+oldnbsom*NZ;
      som_der(i,3) = i3+oldnbsom*NZ;
    }
  les_faces_dvt.les_sommets().ref(som_dvt);
  les_faces_der.les_sommets().ref(som_der);
}
References List_Bord::add(), check_boundary_name(), Frontiere::faces(), Zone::faces_bord(), Zone::faces_raccord(), Zone::les_elems(), Faces::les_sommets(), LIST_CURSEUR, Frontiere::nommer(), NZ, Faces::quadrangle_3D, TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), traiter_faces_dvt_hexa(), Faces::typer(), Faces::voisins(), and Domaine::zone().
Referenced by extruder_hexa().
extruder_hexa()
void Extruder::extruder_hexa (Domaine & dom) protected
< Tableau dont on aura pas besoin
< les nouveaux elements
Definition at line 495 of file Extruder.cpp.
{
  Zone& zone = dom.zone(0);
  int oldnbsom = zone.nb_som();
  IntTab& les_elems=zone.les_elems();
  int oldsz=les_elems.dimension(0);
  double dx = direction[0]/NZ;
  double dy = direction[1]/NZ;
  double dz = direction[2]/NZ;
  Faces les_faces;
  {
// bloc a factoriser avec Zone_VF.cpp :
    Type_Face type_face = zone.type_elem().type_face(0);
    les_faces.typer(type_face);
    les_faces.associer_zone(zone);
    Static_Int_Lists connectivite_som_elem;
    const int     nb_sommets_tot = zone.domaine().nb_som_tot();
    const IntTab&    elements       = zone.les_elems();
    construire_connectivite_som_elem(nb_sommets_tot,
                                     elements,
                                     connectivite_som_elem,
                                     1 /* include virtual elements */);
    Faces_builder faces_builder;
    IntTab elem_faces; //!< Tableau dont on aura pas besoin
    faces_builder.creer_faces_reeles(zone,
                                     connectivite_som_elem,
                                     les_faces,
                                     elem_faces);
  }
  int newnbsom = oldnbsom*(NZ+1);
  DoubleTab new_soms(newnbsom, 3);
  DoubleTab& coord_sommets=dom.les_sommets();
  Objet_U::dimension=3;
  int i;
// les sommets du maillage 2D sont translates
  for (i=0; i<oldnbsom; i++)
    {
      double x = coord_sommets(i,0);
      double y = coord_sommets(i,1);
      double z=0.;
      if (coord_sommets.dimension(1)>2)
        z=coord_sommets(i,2);
      for (int k=0; k<=NZ; k++)
        {
          new_soms(k*oldnbsom+i,0)=x;
          new_soms(k*oldnbsom+i,1)=y;
          new_soms(k*oldnbsom+i,2)=z;
          x += dx;
          y += dy;
          z += dz;
        }
    }
  coord_sommets.resize(0);
  dom.ajouter(new_soms);
  int newnbelem = NZ*oldsz;
  IntTab new_elems(newnbelem, 8); //!< les nouveaux elements
// definition des nouveaux hexas
  for (i=0; i<oldsz; i++)
    {
      int i0=les_elems(i,0);
      int i1=les_elems(i,1);
      int i2=les_elems(i,2);
      int i3=les_elems(i,3);
      for (int k=0; k<NZ; k++)
        {
          new_elems(k*oldsz+i,0) = i0;
          new_elems(k*oldsz+i,1) = i1;
          new_elems(k*oldsz+i,2) = i2;
          new_elems(k*oldsz+i,3) = i3;
          new_elems(k*oldsz+i,4) = i0+oldnbsom;
          new_elems(k*oldsz+i,5) = i1+oldnbsom;
          new_elems(k*oldsz+i,6) = i2+oldnbsom;
          new_elems(k*oldsz+i,7) = i3+oldnbsom;
          i0+=oldnbsom;
          i1+=oldnbsom;
          i2+=oldnbsom;
          i3+=oldnbsom;
        }
    }
  les_elems.ref(new_elems);
// Reconstruction de l'octree
  zone.invalide_octree();
  if ((zone.type_elem()->que_suis_je()) ==  "Quadrangle")
    zone.typer("Hexaedre_VEF");
  else
    zone.typer("Hexaedre");
  extruder_dvt_hexa(dom, les_faces,oldnbsom, oldsz);
}
References Domaine::ajouter(), Faces::associer_zone(), construire_connectivite_som_elem(), Faces_builder::creer_faces_reeles(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, direction, Zone::domaine(), extruder_dvt_hexa(), Zone::invalide_octree(), Zone::les_elems(), Domaine::les_sommets(), Zone::nb_som(), Domaine::nb_som_tot(), NZ, Objet_U::que_suis_je(), TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), Zone::type_elem(), Elem_geom::type_face(), Faces::typer(), Zone::typer(), and Domaine::zone().
Referenced by extruder().
get_info()
const Type_info * Extruder::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 24 of file Extruder.cpp.
info()
const Type_info * Extruder::info () static
Definition at line 24 of file Extruder.cpp.
interpreter_()
Entree & Extruder::interpreter_ (Entree & is) override virtual
Fonction principale de l'interprete Extruder
Triangule 1 a 1 toutes les zones du domaine
specifie par la directive.
On triangule la zone grace a la methode:
void Extruder::extruder(Zone& zone) const
Extruder signifie ici transformer en triangle des
elements geometrique d'une zone.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Implements Interprete_geometrique_base.
Definition at line 90 of file Extruder.cpp.
{
  Nom nom_dom;
  Param param(que_suis_je());
  param.ajouter("domaine",&nom_dom,Param::REQUIRED);
  param.ajouter("nb_tranches",&NZ,Param::REQUIRED);
  param.ajouter_arr_size_predefinie("direction",&direction,Param::REQUIRED);
  param.lire_avec_accolades_depuis(is);
  associer_domaine(nom_dom);
  Scatter::uninit_sequential_domain(domaine());
  extruder(domaine());
  Scatter::init_sequential_domain(domaine());
  return is;
}
References Param::ajouter(), Param::ajouter_arr_size_predefinie(), Interprete_geometrique_base::associer_domaine(), direction, Interprete_geometrique_base::domaine(), extruder(), Scatter::init_sequential_domain(), Param::lire_avec_accolades_depuis(), NZ, Objet_U::que_suis_je(), Param::REQUIRED, and Scatter::uninit_sequential_domain().
printOn()
Sortie & Extruder::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 44 of file Extruder.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Extruder::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 64 of file Extruder.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Extruder & Extruder::self_cast (const Objet_U & r) static
Definition at line 24 of file Extruder.cpp.
self_cast() [2/2]
Extruder & Extruder::self_cast (Objet_U & r) static
Definition at line 24 of file Extruder.cpp.
setDirection()
void Extruder::setDirection (double lx, double ly, double lz) inline
Definition at line 46 of file Extruder.h.
  {
    direction[0]=lx;
    direction[1]=ly;
    direction[2]=lz;
  };
References direction.
Referenced by ExtrudeBord::extruder_bord().
setNbTranches()
void Extruder::setNbTranches (int n) inline
Definition at line 52 of file Extruder.h.
  {
    NZ = n;
  };
References NZ.
Referenced by ExtrudeBord::extruder_bord().
taille_memoire()
unsigned Extruder::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Extruder.cpp.
traiter_faces_dvt()
void Extruder::traiter_faces_dvt (Faces & les_faces_bord, Faces & les_faces, int oldnbsom, int oldsz, int nbfaces2D) private
Definition at line 363 of file Extruder.cpp.
{
  int size_2D = les_faces_bord.nb_faces();
  IntTab les_sommets(4*size_2D*NZ, 3);
  for (int i=0; i<size_2D; i++)
    {
      int i0=les_faces_bord.sommet(i,0);
      int i1=les_faces_bord.sommet(i,1);
// double x01 = 0.5*(coord_sommets(i0,0)+coord_sommets(i1,0));
// double y01 = 0.5*(coord_sommets(i0,1)+coord_sommets(i1,1));
// on recherche le numero de cette face de bord: pas top!
      int jface=-1;
      for (int iface=0; iface<nbfaces2D; iface++)
        {
          int j0=les_faces.sommet(iface,0);
          int j1=les_faces.sommet(iface,1);
          if (((i0==j0) &&(i1==j1)) || ((i0==j1) &&(i1==j0)))
            {
              jface=iface;
              break;
            }
        }
      assert(jface>=0);
      for (int k=0; k<NZ; k++)
        {
// double z = (k+0.5)*dz;
// int i01 = zone.chercher_sommets(x01, y01, z);
          int j01 = oldnbsom*(NZ+1)+NZ*oldsz+k*nbfaces2D+jface;
          les_sommets(k*4*size_2D+4*i,0) = i0;
          les_sommets(k*4*size_2D+4*i,1) = i1;
          les_sommets(k*4*size_2D+4*i,2) = j01;
          les_sommets(k*4*size_2D+4*i+1,0) = j01;
          les_sommets(k*4*size_2D+4*i+1,1) = i1;
          les_sommets(k*4*size_2D+4*i+1,2) = i1+oldnbsom;
          les_sommets(k*4*size_2D+4*i+2,0) = j01;
          les_sommets(k*4*size_2D+4*i+2,1) = i0+oldnbsom;
          les_sommets(k*4*size_2D+4*i+2,2) = i1+oldnbsom;
          les_sommets(k*4*size_2D+4*i+3,0) = j01;
          les_sommets(k*4*size_2D+4*i+3,1) = i0+oldnbsom;
          les_sommets(k*4*size_2D+4*i+3,2) = i0;
          i0+=oldnbsom;
          i1+=oldnbsom;
        }
    }
  les_faces_bord.typer(Faces::triangle_3D);
  les_faces_bord.les_sommets().ref(les_sommets);
  les_faces_bord.voisins().resize(4*size_2D*NZ, 2);
  les_faces_bord.voisins()=-1;
}
References Faces::les_sommets(), Faces::nb_faces(), NZ, TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), Faces::sommet(), Faces::triangle_3D, Faces::typer(), and Faces::voisins().
Referenced by extruder_dvt().
traiter_faces_dvt_hexa()
void Extruder::traiter_faces_dvt_hexa (Faces & les_faces_bord, int oldnbsom) private
Definition at line 603 of file Extruder.cpp.
{
  int size_2D = les_faces_bord.nb_faces();
  IntTab les_sommets(size_2D*NZ, 4);
  for (int i=0; i<size_2D; i++)
    {
      int i0=les_faces_bord.sommet(i,0);
      int i1=les_faces_bord.sommet(i,1);
      for (int k=0; k<NZ; k++)
        {
          les_sommets(k*size_2D+i,0) = i0;
          les_sommets(k*size_2D+i,1) = i1;
          les_sommets(k*size_2D+i,2) = i0+oldnbsom;
          les_sommets(k*size_2D+i,3) = i1+oldnbsom;
          i0+=oldnbsom;
          i1+=oldnbsom;
        }
    }
  les_faces_bord.typer(Faces::quadrangle_3D);
  les_faces_bord.les_sommets().ref(les_sommets);
  les_faces_bord.voisins().resize(size_2D*NZ, 2);
  les_faces_bord.voisins()=-1;
}
References Faces::les_sommets(), Faces::nb_faces(), NZ, Faces::quadrangle_3D, TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), Faces::sommet(), Faces::typer(), and Faces::voisins().
Referenced by extruder_dvt_hexa().
Member Data Documentation
direction
ArrOfDouble Extruder::direction protected
Definition at line 65 of file Extruder.h.
Referenced by Extruder(), extruder(), extruder_hexa(), interpreter_(), and setDirection().
info_obj
const Type_info Extruder::info_obj static
Definition at line 40 of file Extruder.h.
NZ
int Extruder::NZ protected
Definition at line 66 of file Extruder.h.
Referenced by extruder(), extruder_dvt(), extruder_dvt_hexa(), extruder_hexa(), interpreter_(), setNbTranches(), traiter_faces_dvt(), and traiter_faces_dvt_hexa().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Extruder.h
src/Kernel/Geometrie/Extruder.cpp