TRUST: Eval_Div_VDF_Elem Class Reference
Eval_Div_VDF_Elem Class Reference
class Eval_Div_VDF_Elem
Evaluateur VDF pour la divergence
#include <Eval_Div_VDF_Elem.h>
Public Member Functions
Eval_Div_VDF_Elem ()
int calculer_flux_faces_echange_externe_impose () const
int calculer_flux_faces_echange_global_impose () const
int calculer_flux_faces_entree_fluide () const
int calculer_flux_faces_paroi () const
int calculer_flux_faces_paroi_adiabatique () const
int calculer_flux_faces_paroi_defilante () const
int calculer_flux_faces_paroi_fixe () const
int calculer_flux_faces_sortie_libre () const
int calculer_flux_faces_symetrie () const
int calculer_flux_faces_periodique () const
int calculer_flux_faces_NSCBC () const
double flux_face (const DoubleTab &, int, const Dirichlet_entree_fluide &, int) const
double flux_face (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int) const
double flux_face (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int) const
double flux_face (const DoubleTab &, int, int, int, const Echange_externe_impose &, int) const
double flux_face (const DoubleTab &, int, const Echange_global_impose &, int) const
double flux_face (const DoubleTab &, int, const Neumann_paroi &, int) const
double flux_face (const DoubleTab &, int, const Neumann_paroi_adiabatique &, int) const
double flux_face (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double flux_face (const DoubleTab &, int, const Symetrie &, int) const
double flux_face (const DoubleTab &, int, const Periodique &, int) const
double flux_face (const DoubleTab &, int, const NSCBC &, int) const
double flux_faces_interne (const DoubleTab &, int) const
void flux_face (const DoubleTab &, int, const Symetrie &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Periodique &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_entree_fluide &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_paroi_adiabatique &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_paroi &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, int, int, const Echange_externe_impose &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Echange_global_impose &, int, DoubleVect &flux) const
void flux_faces_interne (const DoubleTab &, int, DoubleVect &flux) const
Detailed Description
class Eval_Div_VDF_Elem
Evaluateur VDF pour la divergence
See also:
Eval_Div_VDF
Definition at line 41 of file Eval_Div_VDF_Elem.h.
Constructor & Destructor Documentation
Eval_Div_VDF_Elem::Eval_Div_VDF_Elem () [inline]
Definition at line 115 of file Eval_Div_VDF_Elem.h.
{
}
Member Function Documentation
int Eval_Div_VDF_Elem::calculer_flux_faces_echange_externe_impose () const [inline]
Definition at line 123 of file Eval_Div_VDF_Elem.h.
{
  return 1;
}
int Eval_Div_VDF_Elem::calculer_flux_faces_echange_global_impose () const [inline]
Definition at line 132 of file Eval_Div_VDF_Elem.h.
{
  return 1;
}
int Eval_Div_VDF_Elem::calculer_flux_faces_entree_fluide () const [inline]
Definition at line 142 of file Eval_Div_VDF_Elem.h.
{
  return 1;
}
int Eval_Div_VDF_Elem::calculer_flux_faces_NSCBC () const [inline]
Definition at line 212 of file Eval_Div_VDF_Elem.h.
{
  return 1;
}
int Eval_Div_VDF_Elem::calculer_flux_faces_paroi () const [inline]
Definition at line 151 of file Eval_Div_VDF_Elem.h.
{
  return 0;
}
int Eval_Div_VDF_Elem::calculer_flux_faces_paroi_adiabatique () const [inline]
Definition at line 160 of file Eval_Div_VDF_Elem.h.
{
  return 0;
}
int Eval_Div_VDF_Elem::calculer_flux_faces_paroi_defilante () const [inline]
Definition at line 169 of file Eval_Div_VDF_Elem.h.
{
  return 0;
}
int Eval_Div_VDF_Elem::calculer_flux_faces_paroi_fixe () const [inline]
Definition at line 178 of file Eval_Div_VDF_Elem.h.
{
  return 0;
}
int Eval_Div_VDF_Elem::calculer_flux_faces_periodique () const [inline]
Definition at line 204 of file Eval_Div_VDF_Elem.h.
{
  return 1;
}
int Eval_Div_VDF_Elem::calculer_flux_faces_sortie_libre () const [inline]
Definition at line 187 of file Eval_Div_VDF_Elem.h.
{
  return 1;
}
int Eval_Div_VDF_Elem::calculer_flux_faces_symetrie () const [inline]
Definition at line 196 of file Eval_Div_VDF_Elem.h.
{
  return 0;
}
void Eval_Div_VDF_Elem::flux_face (const DoubleTab & , int , const Symetrie & , int , DoubleVect & flux) const [inline]
Definition at line 499 of file Eval_Div_VDF_Elem.h.
{
  ;
}
void Eval_Div_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Periodique & , int , DoubleVect & flux) const [inline]
Definition at line 510 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  for (int k=0; k<flux.size(); k++)
    flux(k) = inco(face,k)*surface[face]*porosite[face];
}
void Eval_Div_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Neumann_sortie_libre & , int , DoubleVect & flux) const [inline]
Definition at line 487 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  for (int k=0; k<flux.size(); k++)
    flux(k) = inco(face,k)*surface[face]*porosite[face];
}
double Eval_Div_VDF_Elem::flux_face (const DoubleTab & vit, int face, const Periodique & , int) const [inline]
Definition at line 313 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  return vit[face]*surface[face]*porosite[face];
}
double Eval_Div_VDF_Elem::flux_face (const DoubleTab & , int , const Symetrie & , int) const [inline]
Definition at line 304 of file Eval_Div_VDF_Elem.h.
{
  return 0;
}
double Eval_Div_VDF_Elem::flux_face (const DoubleTab & vit, int face, const Neumann_sortie_libre & , int) const [inline]
Definition at line 294 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  return vit[face]*surface[face]*porosite[face];
}
double Eval_Div_VDF_Elem::flux_face (const DoubleTab & vit, int face, const Neumann_paroi_adiabatique & , int) const [inline]
Definition at line 284 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  return vit[face]*surface[face]*porosite[face];
}
void Eval_Div_VDF_Elem::flux_face (const DoubleTab & inco, int boundary_index, int face, int local_face, const Echange_externe_impose & , int , DoubleVect & flux) const [inline]
Definition at line 438 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  for (int k=0; k<flux.size(); k++)
    flux(k) = inco(face,k)*surface[face]*porosite[face];
}
double Eval_Div_VDF_Elem::flux_face (const DoubleTab & vit, int face, const Echange_global_impose & , int) const [inline]
Definition at line 263 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  return vit[face]*surface[face]*porosite[face];
}
double Eval_Div_VDF_Elem::flux_face (const DoubleTab & vit, int boundary_index, int face, int local_face, const Echange_externe_impose & , int) const [inline]
Definition at line 253 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  return vit[face]*surface[face]*porosite[face];
}
double Eval_Div_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int) const [inline]
Definition at line 243 of file Eval_Div_VDF_Elem.h.
{
  return 0;
}
double Eval_Div_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int) const [inline]
Definition at line 233 of file Eval_Div_VDF_Elem.h.
{
  return 0;
}
double Eval_Div_VDF_Elem::flux_face (const DoubleTab & vit, int face, const Dirichlet_entree_fluide & , int) const [inline]
Definition at line 223 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  return vit[face]*surface[face]*porosite[face];
}
double Eval_Div_VDF_Elem::flux_face (const DoubleTab & vit, int faceD, const NSCBC & , int) const [inline]
Definition at line 323 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  /*  // On va retirer la contribution du flux interieur
      const Zone_VDF& zvdf = la_zone;
      int oriD = zvdf.orientation(faceD);
      int faceC;
      int elem0 = zvdf.face_voisins(faceD,0);
      double signe = -1.;
      if (elem0 == -1)
      {
      elem0 = zvdf.face_voisins(faceD,1);
      faceC = zvdf.elem_faces(elem0,oriD+dimension);
      signe = 1.;
      }
      else
      faceC = zvdf.elem_faces(elem0,oriD);
      double flux = signe*flux_faces_interne(vit,faceC);
      // On retourne -flux car il faut qu'il soit retire a ce qui a deja ete ajoute
  // pour la maille de bord consideres.
  return -flux;*/
// Finalement, on calcul la divergence "standard" comme si la condition NSCBC etait
// une sortie libre.
  return vit[faceD]*surface[faceD]*porosite[faceD];
}
void Eval_Div_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Neumann_paroi & , int , DoubleVect & flux) const [inline]
Definition at line 463 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  for (int k=0; k<flux.size(); k++)
    flux(k) = inco(face,k)*surface[face]*porosite[face];
}
double Eval_Div_VDF_Elem::flux_face (const DoubleTab & vit, int face, const Neumann_paroi & , int) const [inline]
Definition at line 274 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  return vit[face]*surface[face]*porosite[face];
}
void Eval_Div_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & , int , DoubleVect & flux) const [inline]
Definition at line 404 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  for (int k=0; k<flux.size(); k++)
    flux(k) = inco(face,k)*surface[face]*porosite[face];
}
void Eval_Div_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int , DoubleVect & flux) const [inline]
Definition at line 416 of file Eval_Div_VDF_Elem.h.
{
  ;
}
void Eval_Div_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Echange_global_impose & , int , DoubleVect & flux) const [inline]
Definition at line 450 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  for (int k=0; k<flux.size(); k++)
    flux(k) = inco(face,k)*surface[face]*porosite[face];
}
void Eval_Div_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Neumann_paroi_adiabatique & , int , DoubleVect & flux) const [inline]
Definition at line 475 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  for (int k=0; k<flux.size(); k++)
    flux(k) = inco(face,k)*surface[face]*porosite[face];
}
void Eval_Div_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int , DoubleVect & flux) const [inline]
Definition at line 427 of file Eval_Div_VDF_Elem.h.
{
  ;
}
double Eval_Div_VDF_Elem::flux_faces_interne (const DoubleTab & vit, int face) const [inline]
Definition at line 359 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  /*  const Zone_VDF& zvdf = la_zone;
      int ori = zvdf.orientation(face);
      int ori_conj;
      if (ori == 0)
      ori_conj = 1;
      else
      ori_conj = 0;
      int f0,f1;
      f0 = zvdf.face_amont_conj(face,ori_conj,0);
      f1 = zvdf.face_amont_conj(face,ori_conj,1);
      double val;
      if ((f0 != -1) && (f1 != -1))
      // On est dans le domaine
      val = 0.75*vit(face) + 0.125*vit(f0) + 0.125*vit(f1);
      else
      {
      if (f0 == -1)
      {
      val = 0.875*vit(face) + 0.125*vit(f1);
      }
      else if (f1 == -1)
      {
      val = 0.875*vit(face) + 0.125*vit(f0);
      }
      }
      val = 0.5*(val + vit[face]);
// return val*surface[face]*porosite[face]; */
  return vit[face]*surface[face]*porosite[face];
}
void Eval_Div_VDF_Elem::flux_faces_interne (const DoubleTab & inco, int face, DoubleVect & flux) const [inline]
Definition at line 522 of file Eval_Div_VDF_Elem.h.
References Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  for (int k=0; k<flux.size(); k++)
    flux(k) = inco(face,k)*surface[face]*porosite[face];
}
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs/Eval_Div_VDF_Elem.h