TRUST: Champ_Uniforme_inst Class Reference
Champ_Uniforme_inst Class Reference
classe Champ_Uniforme_inst
Un champ constant dans l'espace mais dependant du temps.
Cette classe est abstraite, une classe concrete derivant de
Champ_Uniforme_inst devra surcharger la methode me_calculer(double t)
de calcul du champ en fonction du temps.
#include <Champ_Uniforme_inst.h>
Public Member Functions
Champ_Uniforme_inst ()
~Champ_Uniforme_inst ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double)
Mise a jour en temps du champ.
virtual void me_calculer (double t)=0
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Uniforme_inst & self_cast (Objet_U &)
static const Champ_Uniforme_inst & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Champ_Uniforme::printOn(Sortie&)
Imprime le champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a: Champ_Uniforme::readOn(Entree&)
Lit le champ sur un flot d'entree.
Detailed Description
classe Champ_Uniforme_inst
Un champ constant dans l'espace mais dependant du temps.
Cette classe est abstraite, une classe concrete derivant de
Champ_Uniforme_inst devra surcharger la methode me_calculer(double t)
de calcul du champ en fonction du temps.
Definition at line 44 of file Champ_Uniforme_inst.h.
Constructor & Destructor Documentation
Champ_Uniforme_inst::Champ_Uniforme_inst ()
Definition at line 25 of file Champ_Uniforme_inst.cpp.
Champ_Uniforme_inst::~Champ_Uniforme_inst ()
Definition at line 25 of file Champ_Uniforme_inst.cpp.
Member Function Documentation
virtual int Champ_Uniforme_inst::duplique () const [pure virtual]
Reimplemented from Champ_Uniforme.
Implemented in Champ_Fonc_t, and Champ_Tabule_Temps.
const Type_info * Champ_Uniforme_inst::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Uniforme.
Reimplemented in Champ_Fonc_t, and Champ_Tabule_Temps.
Definition at line 25 of file Champ_Uniforme_inst.cpp.
const Type_info * Champ_Uniforme_inst::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Uniforme.
Reimplemented in Champ_Fonc_t, and Champ_Tabule_Temps.
Definition at line 25 of file Champ_Uniforme_inst.cpp.
virtual void Champ_Uniforme_inst::me_calculer (double t) [pure virtual]
Implemented in Champ_Fonc_t, and Champ_Tabule_Temps.
Referenced by mettre_a_jour().
void Champ_Uniforme_inst::mettre_a_jour (double un_temps) [inline, virtual]
Mise a jour en temps du champ.
Reimplemented from Champ_Don_base.
Definition at line 74 of file Champ_Uniforme_inst.h.
References Champ_base::changer_temps(), and me_calculer().
{
  me_calculer(un_temps);
  changer_temps(un_temps);
}
Sortie & Champ_Uniforme_inst::printOn (Sortie & os) const [protected, virtual]
Simple appel a: Champ_Uniforme::printOn(Sortie&)
Imprime le champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Uniforme.
Reimplemented in Champ_Fonc_t, and Champ_Tabule_Temps.
Definition at line 43 of file Champ_Uniforme_inst.cpp.
{
  return Champ_Uniforme::printOn(os) ;
}
Entree & Champ_Uniforme_inst::readOn (Entree & is) [protected, virtual]
Simple appel a: Champ_Uniforme::readOn(Entree&)
Lit le champ sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Uniforme.
Reimplemented in Champ_Fonc_t, and Champ_Tabule_Temps.
Definition at line 64 of file Champ_Uniforme_inst.cpp.
{
  return Champ_Uniforme::readOn(is);
}
const Champ_Uniforme_inst & Champ_Uniforme_inst::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Uniforme.
Reimplemented in Champ_Fonc_t, and Champ_Tabule_Temps.
Definition at line 25 of file Champ_Uniforme_inst.cpp.
Champ_Uniforme_inst & Champ_Uniforme_inst::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Uniforme.
Reimplemented in Champ_Fonc_t, and Champ_Tabule_Temps.
Definition at line 25 of file Champ_Uniforme_inst.cpp.
Member Data Documentation
const Type_info Champ_Uniforme_inst::info_obj [static]
Reimplemented from Champ_Uniforme.
Reimplemented in Champ_Fonc_t, and Champ_Tabule_Temps.
Definition at line 47 of file Champ_Uniforme_inst.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Uniforme_inst.h
src/Kernel/Champs/Champ_Uniforme_inst.cpp