TRUST: Partitionneur_Metis Class Reference
Partitionneur_Metis Class Reference
Partition d'un domaine en nb_parties parties equilibrees en utilisant
la librairie METIS. Voir construire_partition.
#include <Partitionneur_Metis.h>
Public Member Functions
Partitionneur_Metis ()
~Partitionneur_Metis ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void associer_domaine (const Domaine &domaine) override
void construire_partition (IntVect &elem_part, int &nb_parts_tot) const override
Calcule le graphe de connectivite pour Metis, appelle le partitionneur
et remplit elem_part (pour chaque element, numero de la partie qui lui
est attribuee).
Les parties sont equilibrees de facon a minimiser le nombre de faces de joint
et a equilibrer le nombre d'elements par partie.
Public Member Functions inherited from Partitionneur_base
Partitionneur_base ()
~Partitionneur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void associer_domaine (const Domaine &domaine)=0
virtual void declarer_bords_periodiques (const Noms &noms_bords_periodiques)
virtual void construire_partition (IntVect &elem_part, int &nb_parts_tot) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Partitionneur_Metis & self_cast (Objet_U &)
static const Partitionneur_Metis & self_cast (const Objet_U &)
Static Public Member Functions inherited from Partitionneur_base
static const Type_info * info ()
static Partitionneur_base & self_cast (Objet_U &)
static const Partitionneur_base & self_cast (const Objet_U &)
static void corriger_elem0_sur_proc0 (IntVect &elem_part)
corrige la partition pour que l'element 0 du domaine initial
se trouve sur le premier sous-domaine de la partition.
On echange le premier sous-domaine et celui qui contient l'element 0.
static int calculer_graphe_connexions_periodiques (const Zone &zone, const Noms &liste_bords_periodiques, const Static_Int_Lists &som_elem, const int my_offset, Static_Int_Lists &graph)
Calcul d'un graphe de connectivite entre les elements lies par des faces periodiques.
Si l'element i est voisin de l'element j par une face periodique, alors il existe
k tel que graph(i,k)==j et il existe k2 tel que graph(j,k2)==i.
Parametre: zone
Signification: la zone a traiter
Parametre: liste_bords_periodiques
Signification: liste des noms des bords periodiques. ATTENTION: on suppose que les
faces des bords periodiques sont rangees selon la convention des bords periodiques.
Voir check_faces_periodiques().
Parametre: som_elem
Signification: la connectivite sommets-elements pour la zone donnee.
Parametre: graph
Signification: On y stocke le resultat.
Valeur de retour: nombre d'elements dans le graphe (egal au nombre de faces periodiques)
static int corriger_bords_avec_graphe (const Static_Int_Lists &graph_elements_perio, const Static_Int_Lists &som_elem, const Domaine &domaine, const Noms &liste_bords_perio, IntVect &elem_part)
corrige la partition elem_part pour qu'un element i se trouve sur la meme
partition elem_part[i] que tous les elements auxquels il est lie dans le graphe
(elements d'indices graph_elements_perio(i, j) pour tout j).
Parametre: graph_elements_perio
Signification: graphe calcule par la methode calculer_graphe_connexions_periodiques
Parametre: elem_part
Signification: pour chaque element, a quelle partie appartient-il.
Valeur de retour: nombre d'elements dont la partition a ete corrigee.
static void corriger_bords_avec_liste (const Domaine &dom, const Noms &liste_bords_periodiques, const int my_offset, IntVect &elem_part)
Calcul des graphes de connectivite elements periodiques et appel a
corriger_periodique_avec_graphe. (Methode a utiliser quand on ne dispose
pas encore du graphe de de connectivite, si on a le graphe sous la main,
appeler directement corriger_periodique_avec_graphe)
static int corriger_sommets_bord (const Domaine &domaine, const Noms &liste_bords_perio, const ArrOfInt &renum_som_perio, const Static_Int_Lists &som_elem, IntVect &elem_part)
Modifie elem_part pour assurer les proprietes suivantes :
1) Les elements possedant un sommet de bord sont associes
a un processeur possedant une face de bord adjacente a ce sommet.
2) Si un processeur possede un sommet periodique reel, il
possede forcement le renum_som_perio associe (donc un element
qui possede ce sommet et un face periodique).
Cette propriete est indispensable pour le periodique (existence
de renum_som_perio pour tous les sommets).
Pour les autres bords, cette correction est peut-etre inutile, mais
pas sur. Sans cette correction, il peut exister des sommets de bord
isoles (un processeur possede un sommet de bord mais aucune face).
Si on cherche les sommets de bord en parcourant les faces de bord,
c'est faux. Avec cette correction, cet algorithme est correct.
static int corriger_multiperiodique (const Domaine &domaine, const Noms &liste_bords_perio, const ArrOfInt &renum_som_perio, const Static_Int_Lists &som_elem, IntVect &elem_part)
applique des corrections a elem_part pour que le
multi-periodique soit correct :
Si un sommet appartient a plusieurs frontieres periodiques,
tous les elements adjacents sont rattaches au meme processeur.
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Partitionneur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Types
enum AlgoMetis { PMETIS , KMETIS }
Private Attributes
Ref_Domaine ref_domaine_
int nb_parties_
AlgoMetis algo_
int match_type_
int ip_type_
int ref_type_
int nb_essais_
int use_weights_
int use_segment_to_build_connectivite_elem_elem_
Additional Inherited Members
Protected Attributes inherited from Partitionneur_base
Noms liste_bords_periodiques_
Detailed Description
Partition d'un domaine en nb_parties parties equilibrees en utilisant
la librairie METIS. Voir construire_partition.
Definition at line 26 of file Partitionneur_Metis.h.
Member Enumeration Documentation
AlgoMetis
enum Partitionneur_Metis::AlgoMetis private
Enumerator
PMETIS
KMETIS
Definition at line 44 of file Partitionneur_Metis.h.
{ PMETIS, KMETIS };
Constructor & Destructor Documentation
Partitionneur_Metis()
Partitionneur_Metis::Partitionneur_Metis ()
Definition at line 33 of file Partitionneur_Metis.cpp.
{
  nb_parties_ = -1;
  nb_essais_ = 1;
  algo_ = PMETIS;
  match_type_ = -1;
  ip_type_ = -1;
  ref_type_ = -1;
  use_weights_ = 0;
  use_segment_to_build_connectivite_elem_elem_=0;
}
References algo_, ip_type_, match_type_, nb_essais_, nb_parties_, PMETIS, ref_type_, use_segment_to_build_connectivite_elem_elem_, and use_weights_.
~Partitionneur_Metis()
Partitionneur_Metis::~Partitionneur_Metis ()
Definition at line 31 of file Partitionneur_Metis.cpp.
Member Function Documentation
associer_domaine()
void Partitionneur_Metis::associer_domaine (const Domaine & domaine) override virtual
Implements Partitionneur_base.
Definition at line 113 of file Partitionneur_Metis.cpp.
{
  ref_domaine_ = domaine;
}
References ref_domaine_.
construire_partition()
void Partitionneur_Metis::construire_partition (IntVect & elem_part, int & nb_parts_tot) const override virtual
Calcule le graphe de connectivite pour Metis, appelle le partitionneur
et remplit elem_part (pour chaque element, numero de la partie qui lui
est attribuee).
Les parties sont equilibrees de facon a minimiser le nombre de faces de joint
et a equilibrer le nombre d'elements par partie.
< valeur renvoyee par metis (nombre total de faces de joint)
< Nombre de partitionnements testes pour en prendre le meilleur
< Numerotation C qui demarre a 0
< Mode verbose maximal options[METIS_OPTION_NO2HOP]=1; // 5.1.0: not perform any 2-hop matchings (as 5.0.3)
< Nombre de partitionnements testes pour en prendre le meilleur
< Numerotation C qui demarre a 0
< Mode verbose maximal
Implements Partitionneur_base.
Definition at line 126 of file Partitionneur_Metis.cpp.
{
#ifdef NO_METIS
  Cerr << "METIS is not compiled with this version. Use another partition tool like Tranche." << finl;
  Process::exit();
#else
  if (!ref_domaine_.non_nul())
    {
      Cerr << "Error in Partitionneur_Metis::construire_partition\n";
      Cerr << " The domain has not been associated" << finl;
      exit();
    }
  if (nb_parties_ <= 0)
    {
      Cerr << "Error in Partitionneur_Metis::construire_partition\n";
      Cerr << " The parts number has not been initialized" << finl;
      exit();
    }
// Cas particulier: si nb_parts == 1, METIS ne veut rien faire...
  if (nb_parties_ == 1)
    {
      int nb_elem = ref_domaine_.valeur().zone(0).nb_elem_tot();
      if (use_segment_to_build_connectivite_elem_elem_==1)
        nb_elem = ref_domaine_.valeur().nb_som();
      elem_part.resize(nb_elem);
      elem_part = 0;
      return;
    }
  if (ref_domaine_.valeur().zone(0).nb_elem() == 0)
    return;
  Cerr << "Partitionneur_Metis::construire_partition" << finl;
  Cerr << " Construction of graph connectivity..." << finl;
  Static_Int_Lists graph_elements_perio;
// const Domaine& dom = ref_domaine_.valeur();
  Domain_Graph graph;
  if (use_segment_to_build_connectivite_elem_elem_==0)
    {
      graph.construire_graph_elem_elem(ref_domaine_.valeur(), liste_bords_periodiques_,
                                       use_weights_,
                                       graph_elements_perio);
    }
  else
    {
      graph.construire_graph_from_segment(ref_domaine_.valeur(), use_weights_);
    }
  std::vector<int> partition(graph.nvtxs);
  int int_parts = nb_parties_;
  int edgecut = 0; //!< valeur renvoyee par metis (nombre total de faces de joint)
  switch(algo_)
    {
    case PMETIS:
      {
        Cerr << "===============" << finl;
        Cerr << "Call for PMETIS" << finl;
        Cerr << "===============" << finl;
// Voir le manual.pdf de METIS 5.0
        int options[METIS_NOPTIONS];
        METIS_SetDefaultOptions(options);
// options[METIS_OPTION_PTYPE]=METIS_PTYPE_RB|METIS_PTYPE_KWAY; // Methode de partitionnement
// options[METIS_OPTION_OBJTYPE]=METIS_OBJTYPE_CUT|METIS_OBJTYPE_VOL; // Objective type
// options[METIS_OPTION_CTYPE]=METIS_CTYPE_SHEM|METIS_CTYPE_RM; // Matching scheme during coarsening
// options[METIS_OPTION_IPTYPE]=METIS_IPTYPE_GROW; // Algorithm during initial partitioning
// options[METIS_OPTION_RTYPE]=METIS_RTYPE_FM;   // Algorithm for refinement
        options[METIS_OPTION_NCUTS]=nb_essais_;         //!< Nombre de partitionnements testes pour en prendre le meilleur
        options[METIS_OPTION_NUMBERING]=0;              //!< Numerotation C qui demarre a 0
        options[METIS_OPTION_DBGLVL]=111111111;         //!< Mode verbose maximal options[METIS_OPTION_NO2HOP]=1;                 // 5.1.0: not perform any 2-hop matchings (as 5.0.3)
//
        int ncon=1;
// Implementation reduite (plusieurs valeurs par defaut->NULL) pour METIS 5.0
        int status = METIS_PartGraphRecursive(&graph.nvtxs, &ncon, graph.xadj.addr(),
                                              graph.adjncy.addr(), graph.vwgts.addr(), NULL, graph.ewgts.addr(),
                                              &int_parts, NULL, NULL, options,
                                              &edgecut, partition.data());
        if (status != METIS_OK)
          {
            Cerr << "Call to METIS failed." << finl;
            if (status == METIS_ERROR_INPUT)  Cerr << "It seems there is an input error." << finl;
            if (status == METIS_ERROR_MEMORY) Cerr << "It seems it couldn't allocate enough memory." << finl;
            if (status == METIS_ERROR)        Cerr << "It seems there is a METIS internal error." << finl;
            Cerr << "Contact TRUST support." << finl;
            exit();
          }
        Cerr << "===============" << finl;
        break;
      }
    case KMETIS:
      {
        Cerr << " Call for KMETIS" << finl;
        int options[METIS_NOPTIONS];
        METIS_SetDefaultOptions(options);
// options[METIS_OPTION_PTYPE]=METIS_PTYPE_RB|METIS_PTYPE_KWAY; // Methode de partitionnement
// options[METIS_OPTION_OBJTYPE]=METIS_OBJTYPE_CUT|METIS_OBJTYPE_VOL; // Objective type
// options[METIS_OPTION_CTYPE]=METIS_CTYPE_SHEM; // Matching scheme during coarsening
// options[METIS_OPTION_IPTYPE]=METIS_IPTYPE_GROW; // Algorithm during initial partitioning
// options[METIS_OPTION_RTYPE]=METIS_RTYPE_FM; // Algorithm for refinement
        options[METIS_OPTION_NCUTS]=nb_essais_;         //!< Nombre de partitionnements testes pour en prendre le meilleur
        options[METIS_OPTION_NUMBERING]=0;     //!< Numerotation C qui demarre a 0
        options[METIS_OPTION_DBGLVL]=111111111; //!< Mode verbose maximal
        int ncon=1;
// Conseil de la doc Metis 4.0 : METIS_PartGraphKway si int_parts>8, METIS_PartGraphRecursive sinon...
// En effet semble plus rapide, mais edgecut en sortie est moins bon...
        int status = METIS_PartGraphKway(&graph.nvtxs, &ncon, graph.xadj.addr(),
                                         graph.adjncy.addr(), graph.vwgts.addr(), NULL, graph.ewgts.addr(),
                                         &int_parts, NULL, NULL, options ,
                                         &edgecut, partition.data());
        if (status != METIS_OK)
          {
            Cerr << "Call to METIS failed." << finl;
            if (status == METIS_ERROR_INPUT)  Cerr << "It seems there is an input error." << finl;
            if (status == METIS_ERROR_MEMORY) Cerr << "It seems it couldn't allocate enough memory." << finl;
            if (status == METIS_ERROR)        Cerr << "It seems there is a METIS internal error." << finl;
            Cerr << "Contact TRUST support." << finl;
            exit();
          }
        break;
      }
    default:
      {
        Cerr << "Internal error Partitionneur_Metis: not coded" << finl;
        exit();
      }
    }
  Cerr << "Partitioning quality : edgecut = " << edgecut << finl;
  Cerr << "-> It is roughly the total number of edges (faces) which will be shared by the processors." << finl;
  Cerr << "-> The lesser this number is, the lesser the total volume of communication between processors." << finl;
  Cerr << "-> You can increase nb_essais option (default 1) to try to reduce (but at a higher CPU cost) this number." << finl;
  Cerr << "===============" << finl;
  const int n = graph.nvtxs;
  elem_part.resize(n);
  for (int i = 0; i < n; i++)
    elem_part[i] = partition[i];
// Correction de la partition pour la periodicite. (***)
  if (graph_elements_perio.get_nb_lists() > 0)
    {
      Cerr << "Correction of the partition for the periodicity" << finl;
      corriger_bords_avec_liste(ref_domaine_.valeur(),
                                liste_bords_periodiques_,
                                0,
                                elem_part);
      Cerr << "  If this number is high, we can improve the splitting with the option use_weights\n"
           << "  but it takes more memory)" << finl;
    }
  if (use_segment_to_build_connectivite_elem_elem_==0)
    {
      Cerr << "Correction elem0 on processor 0" << finl;
      corriger_elem0_sur_proc0(elem_part);
    }
#endif
}
References TRUSTArray< _TYPE_ >::addr(), Domain_Graph::adjncy, algo_, Cerr, Domain_Graph::construire_graph_elem_elem(), Domain_Graph::construire_graph_from_segment(), Partitionneur_base::corriger_bords_avec_liste(), Partitionneur_base::corriger_elem0_sur_proc0(), Domain_Graph::ewgts, Process::exit(), finl, Static_Int_Lists::get_nb_lists(), KMETIS, Partitionneur_base::liste_bords_periodiques_, Zone::nb_elem(), Zone::nb_elem_tot(), nb_essais_, nb_parties_, Domaine::nb_som(), O_U_Ptr::non_nul(), Domain_Graph::nvtxs, PMETIS, ref_domaine_, TRUSTVect< _TYPE_ >::resize(), use_segment_to_build_connectivite_elem_elem_, use_weights_, Ref_Domaine::valeur(), Domain_Graph::vwgts, Domain_Graph::xadj, and Domaine::zone().
cree_instance()
Objet_U * Partitionneur_Metis::cree_instance () static
Definition at line 31 of file Partitionneur_Metis.cpp.
duplique()
int Partitionneur_Metis::duplique () const override virtual
Implements Objet_U.
Definition at line 31 of file Partitionneur_Metis.cpp.
get_info()
const Type_info * Partitionneur_Metis::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 31 of file Partitionneur_Metis.cpp.
info()
const Type_info * Partitionneur_Metis::info () static
Definition at line 31 of file Partitionneur_Metis.cpp.
lire_motcle_non_standard()
int Partitionneur_Metis::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Partitionneur_base.
Definition at line 72 of file Partitionneur_Metis.cpp.
{
  if (mot=="pmetis")
    {
      Cerr << " Algorithm PMETIS" << finl;
      algo_ = PMETIS;
      return 1;
    }
  else if (mot=="kmetis")
    {
      Cerr << " Algorithm KMETIS" << finl;
      algo_ = KMETIS;
      return 1;
    }
  else if (mot=="match_type")
    {
      not_implemented(mot);
      return 1;
    }
  else if (mot=="initial_partition_type")
    {
      not_implemented(mot);
      return 1;
    }
  else if (mot=="refinement_type")
    {
      not_implemented(mot);
      return 1;
    }
  else
    return Partitionneur_base::lire_motcle_non_standard(mot,is);
  if(Process::nproc() >1)
    {
      Cerr << "WARNING! You're using a sequential algorithm on " << nproc() << "processors " << finl;
      Cerr << "Use PARMETIS for parallel domain cutting" << finl;
      Process::exit();
    }
  return 1;
}
References algo_, Cerr, Process::exit(), finl, KMETIS, Partitionneur_base::lire_motcle_non_standard(), not_implemented(), Process::nproc(), and PMETIS.
printOn()
Sortie & Partitionneur_Metis::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 45 of file Partitionneur_Metis.cpp.
{
  Cerr << "Partitionneur_Metis::printOn invalid\n" << finl;
  exit();
  return os;
}
References Cerr, Process::exit(), and finl.
readOn()
Entree & Partitionneur_Metis::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 52 of file Partitionneur_Metis.cpp.
{
  Partitionneur_base::readOn(is);
  return is;
}
References Partitionneur_base::readOn().
self_cast() [1/2]
const Partitionneur_Metis & Partitionneur_Metis::self_cast (const Objet_U & r) static
Definition at line 31 of file Partitionneur_Metis.cpp.
self_cast() [2/2]
Partitionneur_Metis & Partitionneur_Metis::self_cast (Objet_U & r) static
Definition at line 31 of file Partitionneur_Metis.cpp.
set_param()
void Partitionneur_Metis::set_param (Param & param) override virtual
< option pour construire le grpah a partir des liens (segment) pour reseau electrique, sides ....
Implements Partitionneur_base.
Definition at line 58 of file Partitionneur_Metis.cpp.
{
  param.ajouter("nb_parts",&nb_parties_,Param::REQUIRED);
  param.ajouter("nb_essais",&nb_essais_);
  param.ajouter_condition("(value_of_nb_parts_ge_1)_and_(value_of_nb_parts_le_100000)","The following condition must be satisfied : 1 <= nb_parties <= 100000");
  param.ajouter_non_std("pmetis",(this));
  param.ajouter_non_std("kmetis",(this));
  param.ajouter_non_std("match_type",(this));
  param.ajouter_non_std("initial_partition_type",(this));
  param.ajouter_non_std("refinement_type",(this));
  param.ajouter_flag("use_weights",&use_weights_);
  param.ajouter_flag("use_segment_to_build_connectivite_elem_elem",&use_segment_to_build_connectivite_elem_elem_); //!< option pour construire le grpah a partir des liens (segment) pour reseau electrique, sides ....
}
References Param::ajouter(), Param::ajouter_condition(), Param::ajouter_flag(), Param::ajouter_non_std(), nb_essais_, nb_parties_, Param::REQUIRED, use_segment_to_build_connectivite_elem_elem_, and use_weights_.
taille_memoire()
unsigned Partitionneur_Metis::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 31 of file Partitionneur_Metis.cpp.
Member Data Documentation
algo_
AlgoMetis Partitionneur_Metis::algo_ private
Definition at line 45 of file Partitionneur_Metis.h.
Referenced by construire_partition(), lire_motcle_non_standard(), and Partitionneur_Metis().
info_obj
const Type_info Partitionneur_Metis::info_obj static
Definition at line 28 of file Partitionneur_Metis.h.
ip_type_
int Partitionneur_Metis::ip_type_ private
Definition at line 47 of file Partitionneur_Metis.h.
Referenced by Partitionneur_Metis().
match_type_
int Partitionneur_Metis::match_type_ private
Definition at line 46 of file Partitionneur_Metis.h.
Referenced by Partitionneur_Metis().
nb_essais_
int Partitionneur_Metis::nb_essais_ private
Definition at line 49 of file Partitionneur_Metis.h.
Referenced by construire_partition(), Partitionneur_Metis(), and set_param().
nb_parties_
int Partitionneur_Metis::nb_parties_ private
Definition at line 41 of file Partitionneur_Metis.h.
Referenced by construire_partition(), Partitionneur_Metis(), and set_param().
ref_domaine_
Ref_Domaine Partitionneur_Metis::ref_domaine_ private
Definition at line 40 of file Partitionneur_Metis.h.
Referenced by associer_domaine(), and construire_partition().
ref_type_
int Partitionneur_Metis::ref_type_ private
Definition at line 48 of file Partitionneur_Metis.h.
Referenced by Partitionneur_Metis().
use_segment_to_build_connectivite_elem_elem_
int Partitionneur_Metis::use_segment_to_build_connectivite_elem_elem_ private
Definition at line 59 of file Partitionneur_Metis.h.
Referenced by construire_partition(), Partitionneur_Metis(), and set_param().
use_weights_
int Partitionneur_Metis::use_weights_ private
Definition at line 58 of file Partitionneur_Metis.h.
Referenced by construire_partition(), Partitionneur_Metis(), and set_param().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Decoupeur/Partitionneur_Metis.h
src/Kernel/Geometrie/Decoupeur/Partitionneur_Metis.cpp