TRUST: Echange_impose_base Class Reference
Echange_impose_base Class Reference
classe Echange_impose_base:
Cette condition limite sert uniquement pour l'equation d'energie.
Elle correspond a imposer un echange de chaleur avec l'exterieur
du domaine en imposant une temperature exterieure T_ext et un
coefficient d'echange h_imp.
Le terme de flux calcule a partir du couple(h_imp,T_ext) s'ecrit :
h_t(T_ext - T_entier)*Surf
avec h_t : coefficient d'echange global.
Il figure au second membre de l'equation d'energie.
Soit l'utilisateur donne un coefficient d'echange qui correspond
uniquement a la paroi, auquel cas le programme calculera la diffusion
sur la demi-maille pres de la paroi, soit il donne un coefficient
d'echange global qui tient compte directement des deux precedents.
Les deux classes derivees Echange_externe_impose et Echange_global_impose
representent ces deux possibilites.
#include <Echange_impose_base.h>
Public Member Functions
~Echange_impose_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double h_imp (int num) const
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
virtual double h_imp (int num, int k) const
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
virtual double T_ext (int num) const
Renvoie la valeur de la temperature imposee
sur la i-eme composante du champ de frontiere.
virtual double T_ext (int num, int k) const
Renvoie la valeur de la temperature imposee
sur la (i,j)-eme composante du champ de frontiere.
void mettre_a_jour (double) override
Effectue une mise a jour en temps
des conditions aux limites.
Lors du premier appel des initialisations sont effectuees:
h_imp(0,0) = (rho(0,0)*Cp(0,0))
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
int a_mettre_a_jour_ss_pas_dt () override
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
void associer_fr_dis_base (const Frontiere_dis_base &) override
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
virtual Champ_front & T_ext ()
Renvoie le champ T_ext de temperature imposee a la frontiere.
virtual const Champ_front & T_ext () const
Renvoie le champ T_ext de temperature imposee a la frontiere.
(version const)
virtual Champ_front & h_imp ()
Constructeur par defaut de la classe Echange_impose_base.
Ne construit rien, initialise le champ init a 0.
virtual const Champ_front & h_imp () const
int compatible_avec_eqn (const Equation_base &) const override
Verifie la compatibilite des conditions aux limites avec
l'equation passee en parametre.
Les conditions aux limites de type Ech_imp_base sont
compatibles avec des equations de type:
- Thermique
- indetermine.
int compatible_avec_discr (const Discretisation_base &) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void liste_faces_loi_paroi (IntTab &)
Public Member Functions inherited from Cond_lim_base
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Echange_impose_base & self_cast (Objet_U &)
static const Echange_impose_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Cond_lim_base
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une condition aux limite de type Echange_impose_base
a partir d'un flot d'entree.
On doit lire le coefficient d'echange global H_imp et la temperature
a la frontiere T_ext.
Format:
"h_imp" type_champ_front bloc de lecture champ
"T_ext" type_champ_front bloc de lecture champ.
Protected Member Functions inherited from Cond_lim_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_front h_imp_
Protected Attributes inherited from Cond_lim_base
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Detailed Description
classe Echange_impose_base:
Cette condition limite sert uniquement pour l'equation d'energie.
Elle correspond a imposer un echange de chaleur avec l'exterieur
du domaine en imposant une temperature exterieure T_ext et un
coefficient d'echange h_imp.
Le terme de flux calcule a partir du couple(h_imp,T_ext) s'ecrit :
h_t(T_ext - T_entier)*Surf
avec h_t : coefficient d'echange global.
Il figure au second membre de l'equation d'energie.
Soit l'utilisateur donne un coefficient d'echange qui correspond
uniquement a la paroi, auquel cas le programme calculera la diffusion
sur la demi-maille pres de la paroi, soit il donne un coefficient
d'echange global qui tient compte directement des deux precedents.
Les deux classes derivees Echange_externe_impose et Echange_global_impose
representent ces deux possibilites.
Definition at line 43 of file Echange_impose_base.h.
Constructor & Destructor Documentation
~Echange_impose_base()
Echange_impose_base::~Echange_impose_base () override
Definition at line 25 of file Echange_impose_base.cpp.
Member Function Documentation
a_mettre_a_jour_ss_pas_dt()
int Echange_impose_base::a_mettre_a_jour_ss_pas_dt () inline override virtual
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
Reimplemented from Cond_lim_base.
Definition at line 56 of file Echange_impose_base.h.
  {
    return 1;
  };
associer_fr_dis_base()
void Echange_impose_base::associer_fr_dis_base (const Frontiere_dis_base & fr) override virtual
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_impose.
Definition at line 348 of file Echange_impose_base.cpp.
{
  if (h_imp_.non_nul())
    h_imp_.valeur().associer_fr_dis_base(fr);
  Cond_lim_base::associer_fr_dis_base(fr);
}
References Champ_front_base::associer_fr_dis_base(), Cond_lim_base::associer_fr_dis_base(), h_imp_, O_U_Ptr::non_nul(), and Deriv_Champ_front_base::valeur().
Referenced by Echange_interne_impose::associer_fr_dis_base().
avancer()
int Echange_impose_base::avancer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_contact_VDF, and Echange_interne_impose.
Definition at line 334 of file Echange_impose_base.cpp.
{
  if (h_imp_.non_nul())
    h_imp_.valeur().avancer(temps);
  return Cond_lim_base::avancer(temps);
}
References Champ_front_base::avancer(), Cond_lim_base::avancer(), h_imp_, O_U_Ptr::non_nul(), and Deriv_Champ_front_base::valeur().
Referenced by Echange_global_impose::avancer(), and Echange_interne_impose::avancer().
changer_temps_futur()
void Echange_impose_base::changer_temps_futur (double temps, int i) override virtual
Change le i-eme temps futur de la CL.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_contact_VDF, and Echange_interne_impose.
Definition at line 328 of file Echange_impose_base.cpp.
{
  if (h_imp_.non_nul())
    h_imp_.valeur().changer_temps_futur(temps,i);
  Cond_lim_base::changer_temps_futur(temps,i);
}
References Champ_front_base::changer_temps_futur(), Cond_lim_base::changer_temps_futur(), h_imp_, O_U_Ptr::non_nul(), and Deriv_Champ_front_base::valeur().
Referenced by Echange_global_impose::changer_temps_futur(), and Echange_interne_impose::changer_temps_futur().
compatible_avec_discr()
int Echange_impose_base::compatible_avec_discr (const Discretisation_base &) const override virtual
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_global_parfait.
Definition at line 265 of file Echange_impose_base.cpp.
{
  if ((discr.que_suis_je() == "VDF")
      || (discr.que_suis_je() == "VDF_Interface")
      || (discr.que_suis_je() == "VDF_Front_Tracking")
      || (discr.que_suis_je() == "VEFPreP1B")
      || (discr.que_suis_je() == "VEFPreP1B")
      || (discr.que_suis_je() == "PolyMAC")
      || (discr.que_suis_je() == "PolyMAC_P0") )
    return 1;
  else
    {
      err_pas_compatible(discr);
      return 0;
    }
}
References Cond_lim_base::err_pas_compatible(), and Objet_U::que_suis_je().
Referenced by Echange_externe_impose::compatible_avec_discr().
compatible_avec_eqn()
int Echange_impose_base::compatible_avec_eqn (const Equation_base & eqn) const override virtual
Verifie la compatibilite des conditions aux limites avec
l'equation passee en parametre.
Les conditions aux limites de type Ech_imp_base sont
compatibles avec des equations de type:
- Thermique
- indetermine.
Returns
int
Signification: valeur booleenne, 1 si compatible 0 sinon
Contraintes:
Implements Cond_lim_base.
Reimplemented in Echange_contact_Correlation_VDF.
Definition at line 302 of file Echange_impose_base.cpp.
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Thermique = "Thermique", Neutronique = "Neutronique", indetermine = "indetermine", FracMass="fraction_massique";
  if ( (dom_app == Thermique) || (dom_app == Neutronique) || (dom_app == indetermine) || (dom_app==FracMass))
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
fixer_nb_valeurs_temporelles()
void Echange_impose_base::fixer_nb_valeurs_temporelles (int nb_cases) override virtual
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_impose.
Definition at line 321 of file Echange_impose_base.cpp.
{
  if (h_imp_.non_nul())
    h_imp_.valeur().fixer_nb_valeurs_temporelles(nb_cases);
  Cond_lim_base::fixer_nb_valeurs_temporelles(nb_cases);
}
References Champ_front_base::fixer_nb_valeurs_temporelles(), Cond_lim_base::fixer_nb_valeurs_temporelles(), h_imp_, O_U_Ptr::non_nul(), and Deriv_Champ_front_base::valeur().
Referenced by Echange_interne_impose::fixer_nb_valeurs_temporelles().
get_info()
const Type_info * Echange_impose_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_global_impose, Echange_interne_global_parfait, Echange_contact_Colburn_VDF, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_contact_VDF_Plaque_Flux_Cte, Echange_interne_impose, Echange_interne_parfait, and PlaqThVDF.
Definition at line 25 of file Echange_impose_base.cpp.
h_imp() [1/4]
Champ_front & Echange_impose_base::h_imp () inline virtual
Constructeur par defaut de la classe Echange_impose_base.
Ne construit rien, initialise le champ init a 0.
Definition at line 143 of file Echange_impose_base.h.
{
  return h_imp_;
}
References h_imp_.
h_imp() [2/4]
const Champ_front & Echange_impose_base::h_imp () const inline virtual
Definition at line 148 of file Echange_impose_base.h.
{
  return h_imp_;
}
References h_imp_.
h_imp() [3/4]
double Echange_impose_base::h_imp (int i) const virtual
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
Returns
double
Signification:
Contraintes:
Definition at line 186 of file Echange_impose_base.cpp.
{
  if (h_imp_.valeurs().size()==1)
    return h_imp_(0,0);
  else if (h_imp_.valeurs().dimension(1)==1)
    return h_imp_(i,0);
  else
    Cerr << "Echange_impose_base::h_imp erreur" << finl;
  exit();
  return 0.;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, h_imp_, TRUSTVect< _TYPE_ >::size(), and Champ_front::valeurs().
Referenced by Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), and Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face().
h_imp() [4/4]
double Echange_impose_base::h_imp (int i, int j) const virtual
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
Returns
double
Signification:
Contraintes:
Definition at line 223 of file Echange_impose_base.cpp.
{
  if (h_imp_.valeurs().dimension(0)==1)
    return h_imp_(0,j);
  else
    return h_imp_(i,j);
}
References TRUSTTab< _TYPE_ >::dimension(), h_imp_, and Champ_front::valeurs().
info()
const Type_info * Echange_impose_base::info () static
Definition at line 25 of file Echange_impose_base.cpp.
initialiser()
int Echange_impose_base::initialiser (double temps) override virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Echange_contact_VDF, and Echange_interne_impose.
Definition at line 258 of file Echange_impose_base.cpp.
{
  if (h_imp_.non_nul())
    h_imp_.valeur().initialiser(temps,zone_Cl_dis().equation().inconnue()), h_imp_.mettre_a_jour(temps);
  return Cond_lim_base::initialiser(temps);
}
References h_imp_, Cond_lim_base::initialiser(), Champ_front_base::initialiser(), Champ_front::mettre_a_jour(), O_U_Ptr::non_nul(), Deriv_Champ_front_base::valeur(), and Cond_lim_base::zone_Cl_dis().
Referenced by Echange_global_impose::initialiser(), and Echange_interne_impose::initialiser().
liste_faces_loi_paroi()
virtual void Echange_impose_base::liste_faces_loi_paroi (IntTab &) inline virtual
Definition at line 80 of file Echange_impose_base.h.
{};
mettre_a_jour()
void Echange_impose_base::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps
des conditions aux limites.
Lors du premier appel des initialisations sont effectuees:
h_imp(0,0) = (rho(0,0)*Cp(0,0))
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_impose, Echange_contact_Correlation_VDF, Echange_contact_VDF, and PlaqThVDF.
Definition at line 252 of file Echange_impose_base.cpp.
{
  Cond_lim_base::mettre_a_jour(temps);
  h_imp_.mettre_a_jour(temps);
}
References h_imp_, Champ_front::mettre_a_jour(), and Cond_lim_base::mettre_a_jour().
Referenced by Echange_global_impose::mettre_a_jour(), and Echange_interne_impose::mettre_a_jour().
printOn()
Sortie & Echange_impose_base::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_global_impose, Echange_interne_global_parfait, Echange_contact_Colburn_VDF, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_contact_VDF_Plaque_Flux_Cte, Echange_interne_impose, Echange_interne_parfait, and PlaqThVDF.
Definition at line 42 of file Echange_impose_base.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Echange_impose_base::readOn (Entree & s) override protected virtual
Lecture d'une condition aux limite de type Echange_impose_base
a partir d'un flot d'entree.
On doit lire le coefficient d'echange global H_imp et la temperature
a la frontiere T_ext.
Format:
"h_imp" type_champ_front bloc de lecture champ
"T_ext" type_champ_front bloc de lecture champ.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_global_impose, Echange_interne_global_parfait, Echange_contact_Colburn_VDF, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_contact_VDF_Plaque_Flux_Cte, Echange_interne_impose, Echange_interne_parfait, and PlaqThVDF.
Definition at line 67 of file Echange_impose_base.cpp.
{
  Motcle motlu;
  Motcles les_motcles(2);
  {
    les_motcles[0] = "h_imp";
    les_motcles[1] = "T_ext";
  }
  int ind = 0;
  while (ind < 2)
    {
      s >> motlu;
      int rang = les_motcles.search(motlu);
      switch(rang)
        {
        case 0:
          {
            s >> h_imp_;
            break;
          }
        case 1:
          {
            s >> T_ext();
            break;
          }
        default:
          {
            Cerr << "Erreur a la lecture de la condition aux limites de type Echange_impose " << finl;
            Cerr << "On attendait " << les_motcles << "a la place de " <<  motlu << finl;
            exit();
          }
        }
      ind++;
    }
  return s ;
}
References Cerr, Process::exit(), finl, h_imp_, Motcles::search(), and T_ext().
Referenced by Echange_externe_impose::readOn(), and Echange_global_impose::readOn().
reculer()
int Echange_impose_base::reculer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_contact_VDF, and Echange_interne_impose.
Definition at line 342 of file Echange_impose_base.cpp.
{
  if (h_imp_.non_nul())
    h_imp_.valeur().reculer(temps);
  return Cond_lim_base::reculer(temps);
}
References h_imp_, O_U_Ptr::non_nul(), Champ_front_base::reculer(), Cond_lim_base::reculer(), and Deriv_Champ_front_base::valeur().
Referenced by Echange_global_impose::reculer(), and Echange_interne_impose::reculer().
self_cast() [1/2]
const Echange_impose_base & Echange_impose_base::self_cast (const Objet_U & r) static
Definition at line 25 of file Echange_impose_base.cpp.
self_cast() [2/2]
Echange_impose_base & Echange_impose_base::self_cast (Objet_U & r) static
Definition at line 25 of file Echange_impose_base.cpp.
set_temps_defaut()
void Echange_impose_base::set_temps_defaut (double temps) override virtual
Change le i-eme temps futur de la cl.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_impose.
Definition at line 315 of file Echange_impose_base.cpp.
{
  if (h_imp_.non_nul())
    h_imp_.valeur().set_temps_defaut(temps);
  Cond_lim_base::set_temps_defaut(temps);
}
References h_imp_, O_U_Ptr::non_nul(), Champ_front_base::set_temps_defaut(), Cond_lim_base::set_temps_defaut(), and Deriv_Champ_front_base::valeur().
Referenced by Echange_global_impose::set_temps_defaut(), and Echange_interne_impose::set_temps_defaut().
T_ext() [1/4]
Champ_front & Echange_impose_base::T_ext () inline virtual
Renvoie le champ T_ext de temperature imposee a la frontiere.
Returns
Champ_front&
Signification: le champ T_ext de temperature imposee a la frontiere
Contraintes:
Reimplemented in Echange_externe_impose_H.
Definition at line 102 of file Echange_impose_base.h.
{
  return le_champ_front;
}
References Cond_lim_base::le_champ_front.
Referenced by Echange_interne_global_impose::completer(), Echange_contact_Correlation_VDF::completer(), Echange_contact_VDF::completer(), Echange_interne_impose::completer(), Echange_interne_impose::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Echange_contact_PolyMAC::readOn(), Echange_contact_PolyMAC_P0::readOn(), Echange_couplage_thermique::readOn(), readOn(), Echange_contact_Correlation_VDF::readOn(), Echange_contact_VDF::readOn(), PlaqThVDF::readOn(), T_ext(), and Echange_couplage_thermique::T_p().
T_ext() [2/4]
const Champ_front & Echange_impose_base::T_ext () const inline virtual
Renvoie le champ T_ext de temperature imposee a la frontiere.
(version const)
Returns
Champ_front&
Signification: le champ T_ext de temperature imposee a la frontiere
Contraintes: reference constante
Reimplemented in Echange_externe_impose_H.
Definition at line 122 of file Echange_impose_base.h.
{
  return le_champ_front;
}
References Cond_lim_base::le_champ_front.
T_ext() [3/4]
double Echange_impose_base::T_ext (int i) const virtual
Renvoie la valeur de la temperature imposee
sur la i-eme composante du champ de frontiere.
Returns
double
Signification:
Contraintes:
Reimplemented in Echange_externe_impose_H.
Definition at line 125 of file Echange_impose_base.cpp.
{
  if (T_ext().valeurs().size()==1)
    return T_ext()(0,0);
  else if (T_ext().valeurs().dimension(1)==1)
    return T_ext()(i,0);
  else
    {
      Cerr << "Echange_impose_base::T_ext erreur" << finl;
      assert(0);
    }
  exit();
  return 0.;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, T_ext(), and Champ_front::valeurs().
Referenced by Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_EF_base::dimensionner(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face(), and Eval_Diff_VDF_Elem< Eval_Diff_VDF_Multi_inco_const_Elem >::secmem_face().
T_ext() [4/4]
double Echange_impose_base::T_ext (int i, int j) const virtual
Renvoie la valeur de la temperature imposee
sur la (i,j)-eme composante du champ de frontiere.
Returns
double
Signification:
Contraintes:
Reimplemented in Echange_externe_impose_H.
Definition at line 161 of file Echange_impose_base.cpp.
{
  if (T_ext().valeurs().dimension(0)==1)
    return T_ext()(0,j);
  else
    return T_ext()(i,j);
}
References Objet_U::dimension, and T_ext().
Member Data Documentation
h_imp_
Champ_front Echange_impose_base::h_imp_ protected
Definition at line 84 of file Echange_impose_base.h.
Referenced by associer_fr_dis_base(), avancer(), Echange_contact_Correlation_VDF::calculer_Q(), changer_temps_futur(), Echange_contact_Correlation_VDF::completer(), fixer_nb_valeurs_temporelles(), h_imp(), Echange_interne_impose::init(), initialiser(), Echange_contact_VDF::initialiser(), Echange_interne_impose::mettre_a_jour(), mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Echange_couplage_thermique::readOn(), readOn(), Echange_interne_global_impose::readOn(), Echange_interne_global_parfait::readOn(), Echange_contact_Correlation_VDF::readOn(), reculer(), and set_temps_defaut().
info_obj
const Type_info Echange_impose_base::info_obj static
Definition at line 46 of file Echange_impose_base.h.
The documentation for this class was generated from the following files:
src/ThSol/Echange_impose_base.h
src/ThSol/Echange_impose_base.cpp