TRUST: Solveur_Masse_base Class Reference
Solveur_Masse_base Class Reference abstract
classe Solveur_Masse_base
Represente la matrice de masse d'une equation. Une equation
contient une reference a une matrice de masse.
Cette classe est la base de la hierarchie des matrices de masse.
#include <Solveur_Masse_base.h>
Public Member Functions
Solveur_Masse_base ()
~Solveur_Masse_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & appliquer (DoubleTab &) const
renvoie appliquer_impl(x/coeffient_temporelle)
si on a un coefficient temporelle
sinon renvoie appliquer_impl(x)
Return M-1.x
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du solveur de masse.
virtual void associer_zone_dis_base (const Zone_dis_base &)=0
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)=0
virtual void assembler ()
NE FAIT RIEN
Eventuellement a surcharger dans les classes derivees
si la matrice de masse necessite un assemblage.
Assemble le solveur de masse (en general la matrice de masse)
virtual Matrice_Base & ajouter_masse (double dt, Matrice_Base &matrice, int penalisation=1) const
virtual DoubleTab & ajouter_masse (double dt, DoubleTab &x, const DoubleTab &y, int penalisation=1) const
virtual Matrice_Base & ajouter_masse_dt_local (DoubleVect &dt_locaux, Matrice_Base &matrice, int penalisation=1) const
virtual DoubleTab & ajouter_masse_dt_local (DoubleVect &dt_locaux, DoubleTab &x, const DoubleTab &y, int penalisation=1) const
virtual void get_masse_dt_local (DoubleVect &m_dt_locaux, DoubleVect &dt_locaux, int penalisation=1)
virtual void get_masse_divide_by_local_dt (DoubleVect &m_dt_locaux, DoubleVect &dt_locaux, int penalisation=1)
virtual DoubleTab & corriger_solution (DoubleTab &x, const DoubleTab &y, int incr=0) const
void set_name_of_coefficient_temporel (const Nom &)
permet de choisir le nom du coefficient temporelle
que l'on veut utiliser pour appliquer
verifie que le champ exsite bien
int has_coefficient_temporel () const
const Nom & get_name_of_coefficient_temporel () const
virtual DoubleTab & appliquer_impl (DoubleTab &x) const =0
virtual void dimensionner (Matrice_Morse &matrix) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, double dt, const tabs_t &semi_impl, int resoudre_en_increments) const
virtual void completer (void)
virtual void preparer_calcul (void)
void set_penalisation_flag (int pen)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Static Public Member Functions
static const Type_info * info ()
static Solveur_Masse_base & self_cast (Objet_U &)
static const Solveur_Masse_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Attributes
Nom name_of_coefficient_temporel_
nom du coefficient temporelle
int has_coefficient_temporel_
int penalisation_flag_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Private Attributes
double penalisation_
Detailed Description
classe Solveur_Masse_base
Represente la matrice de masse d'une equation. Une equation
contient une reference a une matrice de masse.
Cette classe est la base de la hierarchie des matrices de masse.
Definition at line 46 of file Solveur_Masse_base.h.
Constructor & Destructor Documentation
Solveur_Masse_base()
Solveur_Masse_base::Solveur_Masse_base ()
Definition at line 25 of file Solveur_Masse_base.cpp.
: has_coefficient_temporel_(0), penalisation_flag_(1), penalisation_(0)  {}
~Solveur_Masse_base()
Solveur_Masse_base::~Solveur_Masse_base () override
Definition at line 23 of file Solveur_Masse_base.cpp.
Member Function Documentation
ajouter_blocs()
void Solveur_Masse_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, double dt, const tabs_t & semi_impl, int resoudre_en_increments) const virtual
Reimplemented in Masse_PolyMAC_Elem, Masse_PolyMAC_Face, Masse_PolyMAC_P0_Face, and Masse_VDF_base.
Definition at line 428 of file Solveur_Masse_base.cpp.
{
  Process::exit(que_suis_je() + " : ajouter_blocs not coded!");
}
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Schema_Temps_base::ajouter_blocs(), and ajouter_masse().
ajouter_masse() [1/2]
DoubleTab & Solveur_Masse_base::ajouter_masse (double dt, DoubleTab & x, const DoubleTab & y, int penalisation = 1) const virtual
< M-1
Reimplemented in Solveur_Masse_EF, and Masse_VEF_P1NC.
Definition at line 226 of file Solveur_Masse_base.cpp.
{
  if (has_interface_blocs())
    {
      penalisation_flag_ = penalisation;
      const std::string& nom_inco = equation().inconnue().le_nom().getString();
      ajouter_blocs({}, x, dt, {{nom_inco,y}}, 0); //on tente ajouter_blocs()
      return x;
    }
  int sz=y.size();
  DoubleTab diag;
  diag.copy(equation().inconnue().valeurs(), Array_base::NOCOPY_NOINIT);
  diag=1.;
  appliquer(diag); //!< M-1
  if (penalisation)
    {
      if (penalisation_==0)
        penalisation_ = mp_max_vect(diag)*1.e3;
    }
  else
    penalisation_=1;
  for(int i=0; i<sz; i++)
    {
      if (diag.addr()[i]==0)
        x.addr()[i]=penalisation_*y.addr()[i];
      else
        x.addr()[i]+=1./(diag.addr()[i]*dt)*y.addr()[i];
    }
// x.echange_espace_virtuel();Debog::verifier("Solveur_Masse::ajouter_masse",x);
  return x;
}
References TRUSTArray< _TYPE_ >::addr(), ajouter_blocs(), appliquer(), TRUSTTab< _TYPE_ >::copy(), MorEqn::equation(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), O_U_Ptr::le_nom(), mp_max_vect(), Array_base::NOCOPY_NOINIT, penalisation_, penalisation_flag_, and TRUSTVect< _TYPE_ >::size().
ajouter_masse() [2/2]
Matrice_Base & Solveur_Masse_base::ajouter_masse (double dt, Matrice_Base & matrice, int penalisation = 1) const virtual
< M-1
< M/dt
Reimplemented in Solveur_Masse_EF, and Masse_VEF_P1NC.
Definition at line 178 of file Solveur_Masse_base.cpp.
{
  Matrice_Morse& matmo=ref_cast(Matrice_Morse, matrice);
  if (has_interface_blocs())
    {
      penalisation_flag_ = penalisation;
      DoubleTrav inco(equation().inconnue().valeurs());
      ajouter_blocs({{ equation().inconnue().le_nom().getString(), &matmo }}, inco, dt, {}, 0); //on tente ajouter_blocs()
      return matrice;
    }
  DoubleTrav diag(equation().inconnue().valeurs());
  const int sz = equation().inconnue().valeurs().dimension_tot(0) * diag.line_size();
  diag=1.;
  appliquer(diag); //!< M-1
  int prems=0;
  if(penalisation)
    {
      if (penalisation_==0)
        {
          double penal=0;
          for(int i=0; i<sz; i++)
            penal=std::max(penal, matmo(i,i));
          penal=mp_max(penal);
          penalisation_=(mp_max_vect(diag)/dt + penal)*1.e3;
          prems=1;
        }
    }
  else
    penalisation_=0;
  for(int i=0; i<sz; i++)
    {
      if (diag.addr()[i]==0)
        {
          if(prems)
            {
              matmo(i,i)+=penalisation_;
              prems=0;
            }
          matmo(i,i)+=penalisation_/dt;
        }
      else
        matmo(i,i)+=1./(diag.addr()[i]*dt); //!< M/dt
    }
  return matrice;
}
References TRUSTArray< _TYPE_ >::addr(), ajouter_blocs(), appliquer(), TRUSTTab< _TYPE_ >::dimension_tot(), MorEqn::equation(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), O_U_Ptr::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Process::mp_max(), mp_max_vect(), penalisation_, penalisation_flag_, ref_cast, and Champ_Inc::valeurs().
Referenced by Solveur_Masse_EF::ajouter_masse(), Masse_VEF_P1NC::ajouter_masse(), and Solveur_Masse::ajouter_masse().
ajouter_masse_dt_local() [1/2]
DoubleTab & Solveur_Masse_base::ajouter_masse_dt_local (DoubleVect & dt_locaux, DoubleTab & x, const DoubleTab & y, int penalisation = 1) const virtual
Definition at line 300 of file Solveur_Masse_base.cpp.
{
  int sz=y.size();
  DoubleTrav diag;
  diag.copy(equation().inconnue().valeurs(), Array_base::NOCOPY_NOINIT);
  diag=1.;
  appliquer(diag);
  if (penalisation)
    {
      if (penalisation_==0)
        penalisation_ = mp_max_vect(diag)*1.e3;
    }
  else
    penalisation_=1;
  for(int i=0; i<sz; i++)
    {
      if (diag.addr()[i]==0)
        x.addr()[i]=penalisation_*y.addr()[i];
      else
        x.addr()[i]+=1./(diag.addr()[i]*dt_locaux[i])*y.addr()[i];
    }
// x.echange_espace_virtuel();
// test
  return x;
}
References TRUSTArray< _TYPE_ >::addr(), appliquer(), TRUSTTab< _TYPE_ >::copy(), MorEqn::equation(), mp_max_vect(), Array_base::NOCOPY_NOINIT, penalisation_, and TRUSTVect< _TYPE_ >::size().
ajouter_masse_dt_local() [2/2]
Matrice_Base & Solveur_Masse_base::ajouter_masse_dt_local (DoubleVect & dt_locaux, Matrice_Base & matrice, int penalisation = 1) const virtual
< M-1
Definition at line 260 of file Solveur_Masse_base.cpp.
{
  Matrice_Morse& matmo=ref_cast(Matrice_Morse, matrice);
  int sz=matmo.nb_lignes();;
  DoubleTrav diag(equation().inconnue().valeurs());
  diag=1.;
  appliquer(diag); //!< M-1
  int prems=0;
  if(penalisation)
    {
      if (penalisation_==0)
        {
          double penal=0;
          for(int i=0; i<sz; i++)
            penal=std::max(penal, matmo(i,i));
          penal=mp_max(penal);
          penalisation_=(mp_max_vect(diag)/dt_locaux.local_max_vect() + penal)*1.e3;
          prems=1;
        }
    }
  else
    penalisation_=0;
  for(int i=0; i<sz; i++)
    {
      if (diag.addr()[i]==0)
        {
          if(prems)
            {
              matmo(i,i)+=penalisation_;
              prems=0;
            }
          matmo(i,i)+=penalisation_/dt_locaux[i];
        }
      else
        matmo(i,i)+=1./(diag.addr()[i]*dt_locaux[i]);
    }
  return matrice;
}
References TRUSTArray< _TYPE_ >::addr(), appliquer(), MorEqn::equation(), TRUSTVect< _TYPE_ >::local_max_vect(), Process::mp_max(), mp_max_vect(), Matrice_Morse::nb_lignes(), penalisation_, and ref_cast.
Referenced by Solveur_Masse::ajouter_masse_dt_local().
appliquer()
DoubleTab & Solveur_Masse_base::appliquer (DoubleTab & x) const virtual
renvoie appliquer_impl(x/coeffient_temporelle)
si on a un coefficient temporelle
sinon renvoie appliquer_impl(x)
Return M-1.x
< M-1.x
Definition at line 142 of file Solveur_Masse_base.cpp.
{
  if (has_coefficient_temporel_)
    {
      REF(Champ_base) ref_coeff;
      ref_coeff = equation().get_champ(name_of_coefficient_temporel_);
      DoubleTab values;
      if (sub_type(Champ_Inc_base,ref_coeff.valeur()))
        {
          const Champ_Inc_base& coeff = ref_cast(Champ_Inc_base,ref_coeff.valeur());
          values.ref(coeff.valeurs());
        }
      else if (sub_type(Champ_Fonc_base,ref_coeff.valeur()))
        {
          const Champ_Fonc_base& coeff = ref_cast(Champ_Fonc_base,ref_coeff.valeur());
          values.ref(coeff.valeurs());
        }
      else if (sub_type(Champ_Don_base,ref_coeff.valeur()))
        {
          DoubleTab nodes;
          equation().inconnue().valeur().remplir_coord_noeuds(nodes);
          ref_coeff.valeur().valeur_aux(nodes,values);
        }
      Debog::verifier("Solveur_Masse_base::appliquer coeffs",values);
// tab_divide_any_shape(x, values, VECT_REAL_ITEMS);
      DoubleTab_parts values_parts(values);
      tab_divide_any_shape(x, values_parts[0], VECT_REAL_ITEMS);
    }
  return appliquer_impl(x); //!< M-1.x
}
References appliquer_impl(), coeff, MorEqn::equation(), Equation_base::get_champ(), has_coefficient_temporel_, Equation_base::inconnue(), name_of_coefficient_temporel_, REF, TRUSTTab< _TYPE_ >::ref(), ref_cast, Champ_Inc_base::remplir_coord_noeuds(), sub_type, tab_divide_any_shape(), Deriv_Champ_Inc_base::valeur(), VECT_REAL_ITEMS, and Debog::verifier().
Referenced by Masse_VDF_base::ajouter_blocs(), ajouter_masse(), ajouter_masse_dt_local(), Solveur_Masse::appliquer(), corriger_solution(), get_masse_divide_by_local_dt(), and get_masse_dt_local().
appliquer_impl()
virtual DoubleTab & Solveur_Masse_base::appliquer_impl (DoubleTab & x) const pure virtual
Implemented in Solveur_Masse_EF, Masse_PolyMAC_Elem, Masse_PolyMAC_Face, Masse_PolyMAC_P0_Face, Masse_VDF_Elem, Masse_VDF_Face, and Masse_VEF_P1NC.
Referenced by appliquer(), calculer_inv_volume(), and Champ_Post_Operateur_Eqn::get_champ().
assembler()
void Solveur_Masse_base::assembler () virtual
NE FAIT RIEN
Eventuellement a surcharger dans les classes derivees
si la matrice de masse necessite un assemblage.
Assemble le solveur de masse (en general la matrice de masse)
Definition at line 109 of file Solveur_Masse_base.cpp.
{
  ;
}
Referenced by Solveur_Masse::assembler().
associer_zone_cl_dis_base()
virtual void Solveur_Masse_base::associer_zone_cl_dis_base (const Zone_Cl_dis_base &) pure virtual
Implemented in Solveur_Masse_EF, Masse_PolyMAC_Elem, Masse_PolyMAC_Face, Masse_PolyMAC_P0_Face, Masse_VDF_base, and Masse_VEF_P1NC.
associer_zone_dis_base()
virtual void Solveur_Masse_base::associer_zone_dis_base (const Zone_dis_base &) pure virtual
Implemented in Solveur_Masse_EF, Masse_PolyMAC_Elem, Masse_PolyMAC_Face, Masse_PolyMAC_P0_Face, Masse_VDF_base, and Masse_VEF_P1NC.
completer()
void Solveur_Masse_base::completer (void) virtual
Reimplemented in Masse_PolyMAC_P0_Face.
Definition at line 435 of file Solveur_Masse_base.cpp.
{ }
Referenced by Equation_base::completer(), and Masse_PolyMAC_P0_Face::completer().
corriger_solution()
DoubleTab & Solveur_Masse_base::corriger_solution (DoubleTab & x, const DoubleTab & y, int incr = 0) const virtual
< M-1
Reimplemented in Masse_PolyMAC_Face, Masse_PolyMAC_P0_Face, and Masse_VEF_P1NC.
Definition at line 385 of file Solveur_Masse_base.cpp.
{
  int sz = y.dimension_tot(0) * y.line_size();
  DoubleTrav diag(equation().inconnue().valeurs());
  diag=1.;
  appliquer(diag); //!< M-1
  for(int i=0; i<sz; i++)
    {
      if (diag.addr()[i]<1.e-12)
        {
          x.addr()[i] = y.addr()[i];
        }
    }
  return x;
}
References TRUSTArray< _TYPE_ >::addr(), appliquer(), TRUSTTab< _TYPE_ >::dimension_tot(), MorEqn::equation(), and TRUSTVect< _TYPE_ >::line_size().
Referenced by Solveur_Masse::corriger_solution(), and Masse_VEF_P1NC::corriger_solution().
dimensionner()
void Solveur_Masse_base::dimensionner (Matrice_Morse & matrix) const virtual
Definition at line 405 of file Solveur_Masse_base.cpp.
{
  if (has_interface_blocs())
    {
      dimensionner_blocs({{ equation().inconnue().le_nom().getString(), &matrix }}, {}); //on tente dimensionner_blocs
      return;
    }
  const DoubleTab& champ_inconnue = equation().inconnue().valeurs();
  int size = champ_inconnue.dimension_tot(0) * champ_inconnue.line_size();
  IntTab indice(size, 2);
  for(int i=0; i<size; ++i)
    {
      indice(i,0) = indice(i,1) = i;
    }
  matrix.dimensionner(indice);
}
References TRUSTTab< _TYPE_ >::dimension_tot(), Matrice_Morse::dimensionner(), dimensionner_blocs(), MorEqn::equation(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), O_U_Ptr::le_nom(), TRUSTVect< _TYPE_ >::line_size(), and Champ_Inc::valeurs().
Referenced by Equation_base::dimensionner_matrice_sans_mem().
dimensionner_blocs()
void Solveur_Masse_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const virtual
Reimplemented in Masse_PolyMAC_Face, Masse_PolyMAC_P0_Face, Masse_VDF_base, and Masse_PolyMAC_Elem.
Definition at line 423 of file Solveur_Masse_base.cpp.
{
  Process::exit(que_suis_je() + " : dimensionner_blocs not coded!");
}
References Process::exit(), and Objet_U::que_suis_je().
Referenced by dimensionner(), and Equation_base::dimensionner_blocs().
get_info()
const Type_info * Solveur_Masse_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Masse_PolyMAC_Elem, Masse_PolyMAC_Face, Masse_PolyMAC_P0_Face, Masse_VDF_base, Masse_VDF_Elem, Masse_VDF_Face, and Masse_VEF_P1NC.
Definition at line 23 of file Solveur_Masse_base.cpp.
get_masse_divide_by_local_dt()
void Solveur_Masse_base::get_masse_divide_by_local_dt (DoubleVect & m_dt_locaux, DoubleVect & dt_locaux, int penalisation = 1) virtual
Definition at line 357 of file Solveur_Masse_base.cpp.
{
  int sz=dt_locaux.size();
  DoubleTab diag;
  diag.copy(equation().inconnue().valeurs(), Array_base::NOCOPY_NOINIT);
  diag=1.;
  appliquer(diag);
  if (penalisation)
    {
      if (penalisation_==0)
        penalisation_ = mp_max_vect(diag)*1.e3;
    }
  else
    penalisation_=1;
  for(int i=0; i<sz; i++)
    {
      if (diag.addr()[i]==0)
        m_dt_locaux[i]=0.;
      else
        m_dt_locaux[i]=(1./diag.addr()[i])/dt_locaux[i];
    }
  m_dt_locaux.echange_espace_virtuel();
// Debog::verifier("Solveur_Masse::ajouter_masse",x);
}
References TRUSTArray< _TYPE_ >::addr(), appliquer(), TRUSTTab< _TYPE_ >::copy(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), mp_max_vect(), Array_base::NOCOPY_NOINIT, penalisation_, and TRUSTVect< _TYPE_ >::size().
Referenced by Solveur_Masse::get_masse_divide_by_local_dt().
get_masse_dt_local()
void Solveur_Masse_base::get_masse_dt_local (DoubleVect & m_dt_locaux, DoubleVect & dt_locaux, int penalisation = 1) virtual
Definition at line 329 of file Solveur_Masse_base.cpp.
{
  int sz=dt_locaux.size();
  DoubleTab diag;
  diag.copy(equation().inconnue().valeurs(), Array_base::NOCOPY_NOINIT);
  diag=1.;
  appliquer(diag);
  if (penalisation)
    {
      if (penalisation_==0)
        penalisation_ = mp_max_vect(diag)*1.e3;
    }
  else
    penalisation_=1;
  for(int i=0; i<sz; i++)
    {
      if (diag.addr()[i]==0)
        m_dt_locaux[i]=0.;
      else
        m_dt_locaux[i]=(1./diag.addr()[i])*dt_locaux[i];
    }
  m_dt_locaux.echange_espace_virtuel();
// Debog::verifier("Solveur_Masse::ajouter_masse",x);
}
References TRUSTArray< _TYPE_ >::addr(), appliquer(), TRUSTTab< _TYPE_ >::copy(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), mp_max_vect(), Array_base::NOCOPY_NOINIT, penalisation_, and TRUSTVect< _TYPE_ >::size().
Referenced by Solveur_Masse::get_masse_dt_local().
get_name_of_coefficient_temporel()
const Nom & Solveur_Masse_base::get_name_of_coefficient_temporel () const inline
Definition at line 72 of file Solveur_Masse_base.h.
  {
    return name_of_coefficient_temporel_;
  }
References name_of_coefficient_temporel_.
Referenced by Equation_base::calculer_champ_conserve().
has_coefficient_temporel()
int Solveur_Masse_base::has_coefficient_temporel () const inline
Definition at line 68 of file Solveur_Masse_base.h.
  {
    return has_coefficient_temporel_;
  }
References has_coefficient_temporel_.
Referenced by Equation_base::calculer_champ_conserve().
has_interface_blocs()
virtual int Solveur_Masse_base::has_interface_blocs () const inline virtual
Reimplemented in Masse_PolyMAC_Elem, Masse_PolyMAC_Face, Masse_PolyMAC_P0_Face, and Masse_VDF_base.
Definition at line 85 of file Solveur_Masse_base.h.
  {
    return 0;
  };
Referenced by ajouter_masse(), dimensionner(), and Equation_base::has_interface_blocs().
info()
const Type_info * Solveur_Masse_base::info () static
Definition at line 23 of file Solveur_Masse_base.cpp.
mettre_a_jour()
void Solveur_Masse_base::mettre_a_jour (double temps) virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du solveur de masse.
Definition at line 87 of file Solveur_Masse_base.cpp.
{
}
Referenced by Solveur_Masse::mettre_a_jour().
preparer_calcul()
void Solveur_Masse_base::preparer_calcul (void) virtual
Reimplemented in Masse_PolyMAC_Elem.
Definition at line 439 of file Solveur_Masse_base.cpp.
{ }
Referenced by Equation_base::preparer_calcul().
printOn()
Sortie & Solveur_Masse_base::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Masse_PolyMAC_Elem, Masse_PolyMAC_Face, Masse_PolyMAC_P0_Face, Masse_VDF_base, Masse_VDF_Elem, Masse_VDF_Face, and Masse_VEF_P1NC.
Definition at line 43 of file Solveur_Masse_base.cpp.
{
  return os;
}
readOn()
Entree & Solveur_Masse_base::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Masse_PolyMAC_Elem, Masse_PolyMAC_Face, Masse_PolyMAC_P0_Face, Masse_VDF_base, Masse_VDF_Elem, Masse_VDF_Face, and Masse_VEF_P1NC.
Definition at line 65 of file Solveur_Masse_base.cpp.
{
  return is;
}
self_cast() [1/2]
const Solveur_Masse_base & Solveur_Masse_base::self_cast (const Objet_U & r) static
Definition at line 23 of file Solveur_Masse_base.cpp.
self_cast() [2/2]
Solveur_Masse_base & Solveur_Masse_base::self_cast (Objet_U & r) static
Definition at line 23 of file Solveur_Masse_base.cpp.
set_name_of_coefficient_temporel()
void Solveur_Masse_base::set_name_of_coefficient_temporel (const Nom & name)
permet de choisir le nom du coefficient temporelle
que l'on veut utiliser pour appliquer
verifie que le champ exsite bien
Definition at line 116 of file Solveur_Masse_base.cpp.
{
  name_of_coefficient_temporel_=name;
  has_coefficient_temporel_=1;
  if (name=="no_coeff")
    {
      has_coefficient_temporel_=0;
      return;
    }
  REF(Champ_base) ref_coeff;
  try
    {
      ref_coeff = equation().get_champ(name_of_coefficient_temporel_);
    }
  catch (Champs_compris_erreur)
    {
      Cerr<< name_of_coefficient_temporel_<< " not understood by "<< equation().que_suis_je()<<finl;
      Process::exit();
    }
}
References Cerr, MorEqn::equation(), Process::exit(), finl, Equation_base::get_champ(), has_coefficient_temporel_, name_of_coefficient_temporel_, Objet_U::que_suis_je(), and REF.
set_penalisation_flag()
void Solveur_Masse_base::set_penalisation_flag (int pen) inline
Definition at line 102 of file Solveur_Masse_base.h.
{ penalisation_flag_ = pen;  }
References penalisation_flag_.
Referenced by Equation_base::assembler_blocs_avec_inertie().
Member Data Documentation
has_coefficient_temporel_
int Solveur_Masse_base::has_coefficient_temporel_ protected
Definition at line 107 of file Solveur_Masse_base.h.
Referenced by appliquer(), has_coefficient_temporel(), and set_name_of_coefficient_temporel().
info_obj
const Type_info Solveur_Masse_base::info_obj static
Definition at line 48 of file Solveur_Masse_base.h.
name_of_coefficient_temporel_
Nom Solveur_Masse_base::name_of_coefficient_temporel_ protected
nom du coefficient temporelle
Definition at line 106 of file Solveur_Masse_base.h.
Referenced by appliquer(), get_name_of_coefficient_temporel(), and set_name_of_coefficient_temporel().
penalisation_
double Solveur_Masse_base::penalisation_ mutable private
Definition at line 110 of file Solveur_Masse_base.h.
Referenced by ajouter_masse(), ajouter_masse_dt_local(), get_masse_divide_by_local_dt(), and get_masse_dt_local().
penalisation_flag_
int Solveur_Masse_base::penalisation_flag_ mutable protected
Definition at line 108 of file Solveur_Masse_base.h.
Referenced by Masse_VDF_base::ajouter_blocs(), ajouter_masse(), and set_penalisation_flag().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Solveur_Masse_base.h
src/Kernel/Framework/Solveur_Masse_base.cpp