TRUST: Calcul_integrale_locale Class Reference
Calcul_integrale_locale Class Reference
: classe outil utilisee en interne dans calculer_convolution()
Public Member Functions
Calcul_integrale_locale (const Zone_VF &zone_source, const Moyenne_volumique &filter, const DoubleTab &champ_source)
constructeur de la classe outil...
Voir Moyenne_volumique::calculer_convolution()
void calculer (double x, double y, double z, ArrOfDouble &resu)
evalue le produit de convolution "filter_ * champ_source_" au point x,y,z
et stocke le resultat dans resu. On determine les elements a utiliser en fonction
de la taille du filtre en utilisant une octree.
On suppose que le champ source est aux elements.
Methode appelee par Moyenne_volumique::calculer_convolution()
Protected Attributes
const Zone_VF & zone_source_
Octree_Double octree_
const Moyenne_volumique & filter_
const DoubleTab & champ_source_
ArrOfInt liste_elems_
DoubleTab filter_coords_
ArrOfDouble filter_results_
int nb_items_reels_
Detailed Description
: classe outil utilisee en interne dans calculer_convolution()
Definition at line 520 of file Moyenne_volumique.cpp.
Constructor & Destructor Documentation
Calcul_integrale_locale()
Calcul_integrale_locale::Calcul_integrale_locale (const Zone_VF & zone_source, const Moyenne_volumique & filter, const DoubleTab & champ_source)
constructeur de la classe outil...
Voir Moyenne_volumique::calculer_convolution()
Definition at line 542 of file Moyenne_volumique.cpp.
                                                                                :
  zone_source_(zone_source),
  filter_(filter),
  champ_source_(champ_source)
{
  liste_elems_.set_smart_resize(1);
  filter_coords_.set_smart_resize(1);
  filter_results_.set_smart_resize(1);
// Construction d'un octree contenant les centres des elements
// On copie le tableau car il sera retaille :
  DoubleTab coords = zone_source.xp();
  nb_items_reels_ = zone_source.nb_elem();
// Le tableau xp est dimensionne avec dimension(0)=nb_elem_tot. On le retaille a nb_elem
  coords.resize(nb_items_reels_, coords.dimension(1));
  if (champ_source.dimension(0) != nb_items_reels_)
    {
      Cerr << "Error in Calcul_integrale_locale::Calcul_integrale_locale() :\n"
           << " The source field is not discretized at the elements" << finl;
      Process::barrier();
      Process::exit();
    }
  octree_.build_nodes(coords, 0 /* no virtual items */);
}
References Process::barrier(), Octree_Double::build_nodes(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), filter_coords_, filter_results_, finl, liste_elems_, Zone_dis_base::nb_elem(), nb_items_reels_, octree_, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), and Zone_VF::xp().
Member Function Documentation
calculer()
void Calcul_integrale_locale::calculer (double x, double y, double z, ArrOfDouble & resu)
evalue le produit de convolution "filter_ * champ_source_" au point x,y,z
et stocke le resultat dans resu. On determine les elements a utiliser en fonction
de la taille du filtre en utilisant une octree.
On suppose que le champ source est aux elements.
Methode appelee par Moyenne_volumique::calculer_convolution()
Definition at line 573 of file Moyenne_volumique.cpp.
{
  const double box_size = filter_.box_size();
  octree_.search_elements_box(x - box_size, y - box_size, z - box_size,
                              x + box_size, y + box_size, z + box_size,
                              liste_elems_);
  const DoubleTab& coord_items = zone_source_.xp();
  const int nb_items = liste_elems_.size_array();
  const int dim = Objet_U::dimension;
  const int dim3 = (dim == 3);
  filter_coords_.resize(nb_items, dim);
  for (int i = 0; i < nb_items; i++)
    {
      const int item = liste_elems_[i];
      assert(item < nb_items_reels_);
      filter_coords_(i, 0) = coord_items(item, 0) - x;
      filter_coords_(i, 1) = coord_items(item, 1) - y;
      if (dim3)
        filter_coords_(i, 2) = coord_items(item, 2) - z;
    }
  filter_results_.resize_array(nb_items);
  filter_.eval_filtre(filter_coords_, filter_results_);
  const DoubleVect& volumes = zone_source_.volumes();
  const int nb_comp = champ_source_.dimension(1);
  resu = 0.;
  for (int i = 0; i < nb_items; i++)
    {
      const int item = liste_elems_[i];
      const double valeur_filtre = filter_results_[i];
      const double volume = volumes(item);
      const double facteur = valeur_filtre * volume;
      for (int j = 0; j < nb_comp; j++)
        {
// L'integrale est discretisee grossierement comme le produit des
// valeurs au centre de l'element fois le volume de l'element:
          const double valeur_champ = champ_source_(item, j);
          resu[j] += valeur_champ * facteur;
        }
    }
}
References Moyenne_volumique::box_size(), champ_source_, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Moyenne_volumique::eval_filtre(), filter_, filter_coords_, filter_results_, liste_elems_, nb_items_reels_, octree_, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), Octree_Double::search_elements_box(), TRUSTArray< _TYPE_ >::size_array(), Zone_VF::volumes(), Zone_VF::xp(), and zone_source_.
Referenced by Moyenne_volumique::calculer_convolution().
Member Data Documentation
champ_source_
const DoubleTab& Calcul_integrale_locale::champ_source_ protected
Definition at line 532 of file Moyenne_volumique.cpp.
Referenced by calculer().
filter_
const Moyenne_volumique& Calcul_integrale_locale::filter_ protected
Definition at line 531 of file Moyenne_volumique.cpp.
Referenced by calculer().
filter_coords_
DoubleTab Calcul_integrale_locale::filter_coords_ protected
Definition at line 535 of file Moyenne_volumique.cpp.
Referenced by Calcul_integrale_locale(), and calculer().
filter_results_
ArrOfDouble Calcul_integrale_locale::filter_results_ protected
Definition at line 536 of file Moyenne_volumique.cpp.
Referenced by Calcul_integrale_locale(), and calculer().
liste_elems_
ArrOfInt Calcul_integrale_locale::liste_elems_ protected
Definition at line 534 of file Moyenne_volumique.cpp.
Referenced by Calcul_integrale_locale(), and calculer().
nb_items_reels_
int Calcul_integrale_locale::nb_items_reels_ protected
Definition at line 537 of file Moyenne_volumique.cpp.
Referenced by Calcul_integrale_locale(), and calculer().
octree_
Octree_Double Calcul_integrale_locale::octree_ protected
Definition at line 530 of file Moyenne_volumique.cpp.
Referenced by Calcul_integrale_locale(), and calculer().
zone_source_
const Zone_VF& Calcul_integrale_locale::zone_source_ protected
Definition at line 529 of file Moyenne_volumique.cpp.
Referenced by calculer().
The documentation for this class was generated from the following file:
src/Kernel/Statistiques_temps/Moyenne_volumique.cpp