TRUST: VDoubledata Class Reference
VDoubledata Class Reference
VDoubledata alloue une zone de memoire de la taille specifiee au
constructeur, et libere la zone de memoire a la destruction.
La memoire peut etre allouee sur le tas (avec new) ou par le
mecanisme Memoire::add_trav_double.
"ref_count" compte le nombre de pointeurs qui font reference a "this".
(permet au dernier utilisateur de l'objet de le detruire), voir
ArrOfDouble.
Public Member Functions
VDoubledata (int size, ArrOfDouble::Storage storage)
Construit un VDoubledata de taille size >= 0
Parametre: int s
Signification: taille du VDoubledata, il faut size >= 0
Parametre: Storage storage
Signification: indique si la memoire doit etre allouee
avec "new" ou avec "memoire.add_trav_double()"
Valeurs par defaut: STANDARD (allocation avec "new")
~VDoubledata ()
Detruit la zone de memoire allouee.
int add_one_ref ()
Un nouveau tableau utilise cette zone memoire :
incremente ref_count.
int suppr_one_ref ()
Un tableau de moins utilise cette zone memoire
decremente ref_count.
double * get_data ()
renvoie data_
const double * get_data () const
renvoie data_
int ref_count () const
renvoie ref_count_
int get_size () const
renvoie size_
Private Member Functions
VDoubledata (const VDoubledata &v)
Constructeur par copie. Interdit : genere une erreur !
VDoubledata & operator= (const VDoubledata &v)
Operateur= interdit. Genere une erreur !
Private Attributes
double * data_
int ref_count_
int size_
Double_ptr_trav * d_ptr_trav_
Detailed Description
VDoubledata alloue une zone de memoire de la taille specifiee au
constructeur, et libere la zone de memoire a la destruction.
La memoire peut etre allouee sur le tas (avec new) ou par le
mecanisme Memoire::add_trav_double.
"ref_count" compte le nombre de pointeurs qui font reference a "this".
(permet au dernier utilisateur de l'objet de le detruire), voir
ArrOfDouble.
Definition at line 63 of file ArrOfDouble.cpp.
Constructor & Destructor Documentation
VDoubledata::VDoubledata (int size, ArrOfDouble::Storage storage)
Construit un VDoubledata de taille size >= 0
Parametre: int s
Signification: taille du VDoubledata, il faut size >= 0
Parametre: Storage storage
Signification: indique si la memoire doit etre allouee
avec "new" ou avec "memoire.add_trav_double()"
Valeurs par defaut: STANDARD (allocation avec "new")
Definition at line 107 of file ArrOfDouble.cpp.
References Memoire::add_trav_double(), Cerr, Double_ptr_trav::d_ptr_(), d_ptr_trav_, data_, Process::exit(), finl, Memoire::Instance(), ref_count_, size_, ArrOfDouble::STANDARD, and ArrOfDouble::TEMP_STORAGE.
{
  int size_warning=100000000;
  assert(size >= 0);
  if (size == 0)
    storage = ArrOfDouble::STANDARD;
  switch (storage)
    {
    case ArrOfDouble::STANDARD:
      {
        d_ptr_trav_ = 0;
        if (size>size_warning) Cerr << "Warning: Allocating an array of " << size << " Double ...";
#ifdef _EXCEPTION_
// Allocation de la memoire sur le tas
        try
          {
            data_ = new double[size];
          }
        catch(...)
          {
            Cerr << "unable to allocate " << size << " double " << finl;
            Process::exit();
          }
#else
        data_ = new double[size];
        if(!data_)
          {
            Cerr << "unable to allocate " << size << "double " << finl;
            Process::exit();
          }
#endif
        if (size>size_warning) Cerr << " OK" << finl;
        break;
      }
    case ArrOfDouble::TEMP_STORAGE:
      {
// Allocation de la memoire sur un tas special.
// La memoire ne sera pas rendue au systeme mais conservee pour une
// reutilisation ulterieure.
        Memoire& memoire = Memoire::Instance();
        if (size>size_warning) Cerr << "Warning: Allocating or reusing a DoubleTrav of " << size << " elements ...";
        d_ptr_trav_ = memoire.add_trav_double(size);
        assert(d_ptr_trav_ != 0);
        data_ = d_ptr_trav_->d_ptr_();
        if (size>size_warning) Cerr << " OK" << finl;
        break;
      }
    default:
      Process::exit();
    }
  ref_count_ = 1;
  size_ = size;
  assert(data_ != 0);
}
VDoubledata::~VDoubledata ()
Detruit la zone de memoire allouee.
< paranoia: si size_==-1 c'est qu'on pointe sur un zombie
< (pointeur vers un objet qui a ete detruit)
Definition at line 169 of file ArrOfDouble.cpp.
References d_ptr_trav_, data_, ref_count_, size_, and Double_ptr_trav::unlock().
{
  assert(ref_count_ == 0);
  if (d_ptr_trav_ == 0)
    {
// Stockage STANDARD
      delete[] data_;
    }
  else
    {
// Stockage TEMP_STORAGE
      d_ptr_trav_->unlock();
      d_ptr_trav_ = 0;
    }
  data_ = 0;  //!< paranoia: si size_==-1 c'est qu'on pointe sur un zombie
  size_ = -1; //!<  (pointeur vers un objet qui a ete detruit)
}
VDoubledata::VDoubledata (const VDoubledata & v) [private]
Constructeur par copie. Interdit : genere une erreur !
Definition at line 235 of file ArrOfDouble.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Error in VDoubledata: VDoubledata (const VDoubledata & v)" << finl;
  Process::exit();
}
Member Function Documentation
int VDoubledata::add_one_ref () [inline]
Un nouveau tableau utilise cette zone memoire :
incremente ref_count.
Returns:
int
Signification: ref_count
Definition at line 204 of file ArrOfDouble.cpp.
References ref_count_.
Referenced by ArrOfDouble::attach_array().
{
  return ++ref_count_;
}
const double * VDoubledata::get_data () const [inline]
renvoie data_
Definition at line 229 of file ArrOfDouble.cpp.
References data_.
{
  return data_;
}
double * VDoubledata::get_data () [inline]
renvoie data_
Definition at line 223 of file ArrOfDouble.cpp.
References data_.
Referenced by ArrOfDouble::ArrOfDouble(), and ArrOfDouble::memory_resize().
{
  return data_;
}
int VDoubledata::get_size () const [inline]
renvoie size_
Definition at line 194 of file ArrOfDouble.cpp.
References size_.
Referenced by ArrOfDouble::memory_resize().
{
  return size_;
}
VDoubledata & VDoubledata::operator= (const VDoubledata & v) [private]
Operateur= interdit. Genere une erreur !
Definition at line 242 of file ArrOfDouble.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Error in VDoubledata::operator=(const VDoubledata & v)" << finl;
  Process::exit();
  return *this;
}
int VDoubledata::ref_count () const [inline]
renvoie ref_count_
Definition at line 188 of file ArrOfDouble.cpp.
References ref_count_.
Referenced by ArrOfDouble::ref_count().
{
  return ref_count_;
}
int VDoubledata::suppr_one_ref () [inline]
Un tableau de moins utilise cette zone memoire
decremente ref_count.
Returns:
int
Signification: ref_count
Definition at line 216 of file ArrOfDouble.cpp.
References ref_count_.
Referenced by ArrOfDouble::detach_array().
{
  assert(ref_count_ > 0);
  return (--ref_count_);
}
Member Data Documentation
Double_ptr_trav* VDoubledata::d_ptr_trav_ [private]
Definition at line 93 of file ArrOfDouble.cpp.
Referenced by VDoubledata(), and ~VDoubledata().
double* VDoubledata::data_ [private]
Definition at line 83 of file ArrOfDouble.cpp.
Referenced by get_data(), VDoubledata(), and ~VDoubledata().
int VDoubledata::ref_count_ [private]
Definition at line 87 of file ArrOfDouble.cpp.
Referenced by add_one_ref(), ref_count(), suppr_one_ref(), VDoubledata(), and ~VDoubledata().
int VDoubledata::size_ [private]
Definition at line 90 of file ArrOfDouble.cpp.
Referenced by get_size(), VDoubledata(), and ~VDoubledata().
The documentation for this class was generated from the following file:
src/Kernel/Math/ArrOfDouble.cpp