TRUST: DoubleListElem Class Reference
DoubleListElem Class Reference
#include <DoubleListElem.h>
Public Member Functions
DoubleListElem ()
Construit une liste vide.
DoubleListElem (const double x)
Construit le singleton (x).
DoubleListElem (const DoubleListElem &)
Constructeur par copie.
~DoubleListElem ()
destructeur
DoubleListElem & suivant ()
renvoie le suivant.
const DoubleListElem & suivant () const
renvoie le suivant.
int est_vide () const
renvoie 1 si la liste est vide
renvoie 0 sinon.
int est_dernier () const
renvoie 1 si il n'y a pas de suivant
renvoie 0 sinon.
double & valeur ()
renvoie le reel double precision.
double valeur () const
renvoie le reel double precision.
DoubleListElem & add (double)
insertion en queue
Protected Attributes
double data
DoubleListElem * suivant_
Friends
class DoubleList
int operator== (const DoubleListElem &, const DoubleListElem &)
Operateur de comparaison de deux listes.
Detailed Description
Definition at line 46 of file DoubleListElem.h.
Constructor & Destructor Documentation
DoubleListElem::DoubleListElem () [inline]
Construit une liste vide.
Definition at line 84 of file DoubleListElem.h.
References suivant_.
Referenced by add(), DoubleList::add(), DoubleList::DoubleList(), and DoubleListElem().
{
  suivant_=this;
}
DoubleListElem::DoubleListElem (const double x) [inline]
Construit le singleton (x).
Definition at line 103 of file DoubleListElem.h.
                                                    : data(x), suivant_(0)
{}
DoubleListElem::DoubleListElem (const DoubleListElem & list)
Constructeur par copie.
Definition at line 43 of file DoubleListElem.cpp.
References data, DoubleListElem(), est_vide(), next(), and suivant_.
{
  if(list.est_vide() )
    {
      suivant_=this;
    }
  else
    {
      data=list.data;
      if(list.suivant_)
        {
          DoubleListElem* next = new DoubleListElem(*list.suivant_); //Recursif !!
          suivant_ = next;
        }
      else
        suivant_ =0;
    }
}
DoubleListElem::~DoubleListElem ()
destructeur
Definition at line 76 of file DoubleListElem.cpp.
References est_vide(), and suivant_.
{
// Cout << "Destruction de DoubleList" << finl;
  if (est_vide())
    suivant_=0;
  if(suivant_)
    {
// On ne garde pas la version delete suivant_ car sinon on est limite par le nombre d'appel recursif possible
// delete suivant_;
      DoubleListElem *poignee, *pr;
      pr=suivant_;
      suivant_=0;
      while(pr)
        {
          poignee=pr->suivant_;
          pr->suivant_=0;
          delete pr ;
          pr=poignee;
        }
    }
}
Member Function Documentation
DoubleListElem & DoubleListElem::add (double double_to_add)
insertion en queue
Returns:
Double_ListElem&
Signification: *this
Contraintes:
Reimplemented in DoubleList.
Definition at line 113 of file DoubleListElem.cpp.
References DoubleListElem(), est_dernier(), next(), and suivant_.
Referenced by DoubleList::add().
{
  assert(est_dernier());
  DoubleListElem* next=new DoubleListElem(double_to_add);
  suivant_ = next;
  return *this;
}
int DoubleListElem::est_dernier () const [inline]
renvoie 1 si il n'y a pas de suivant
renvoie 0 sinon.
Returns:
int
Signification: 1 si il n'y a pas de suivant, 0 sinon
Contraintes:
Definition at line 142 of file DoubleListElem.h.
References est_vide(), and suivant_.
Referenced by add(), DoubleList::add(), DoubleList_Curseur::operator++(), operator==(), and DoubleList::printOn().
{
  return ((est_vide()) || (suivant_==0) );
}
int DoubleListElem::est_vide () const [inline]
renvoie 1 si la liste est vide
renvoie 0 sinon.
Returns:
int
Signification: 1 si la liste est vide, 0 sinon
Contraintes:
Definition at line 121 of file DoubleListElem.h.
References suivant_.
Referenced by DoubleList::add(), DoubleList::contient(), DoubleList::DoubleList(), DoubleList_Curseur::DoubleList_Curseur(), DoubleListElem(), est_dernier(), DoubleList_Curseur::operator=(), DoubleList::operator=(), DoubleList::rang(), DoubleList::size(), DoubleList::vide(), and ~DoubleListElem().
{
  return suivant_==this;
}
const DoubleListElem & DoubleListElem::suivant () const [inline]
renvoie le suivant.
Returns:
const DoubleList&
Signification: liste sur l'element suivant
Contraintes:
Definition at line 202 of file DoubleListElem.h.
References suivant_.
{
  return *suivant_;
}
DoubleListElem & DoubleListElem::suivant () [inline]
renvoie le suivant.
Returns:
DoubleList&
Signification: liste sur l'element suivant
Contraintes: DoubleList_H
Definition at line 222 of file DoubleListElem.h.
References suivant_.
Referenced by DoubleList::add(), DoubleList_Curseur::operator++(), and DoubleList::suppr().
double DoubleListElem::valeur () const [inline]
renvoie le reel double precision.
Returns:
double&
Signification:
Contraintes:
Definition at line 182 of file DoubleListElem.h.
References data.
{
  return data;
}
double & DoubleListElem::valeur () [inline]
renvoie le reel double precision.
Returns:
double&
Signification:
Contraintes:
Definition at line 162 of file DoubleListElem.h.
References data.
Referenced by DoubleList::suppr(), and DoubleList_Curseur::valeur().
{
  return data;
}
Friends And Related Function Documentation
friend class DoubleList [friend]
Definition at line 50 of file DoubleListElem.h.
int operator== (const DoubleListElem & list1, const DoubleListElem & list2) [friend]
Operateur de comparaison de deux listes.
Returns:
int
Signification: 1 si les listes sont egales, 0 sinon
Contraintes:
Definition at line 140 of file DoubleListElem.cpp.
{
  int retour=1;
  if(list1.data != list2.data)
    retour= 0;
  if( (!list1.est_dernier()) && (list2.est_dernier()) )
    retour= 0;
  if( (list1.est_dernier()) && (!list2.est_dernier()) )
    retour= 0;
  if( (!list1.est_dernier()) && (!list2.est_dernier()) )
    retour= (*list1.suivant_ == *list2.suivant_);
  return retour;
}
Member Data Documentation
double DoubleListElem::data [protected]
Definition at line 66 of file DoubleListElem.h.
Referenced by DoubleList::add(), DoubleList::DoubleList(), DoubleListElem(), operator==(), DoubleList::suppr(), and valeur().
DoubleListElem* DoubleListElem::suivant_ [protected]
Definition at line 67 of file DoubleListElem.h.
Referenced by add(), DoubleList::add(), DoubleList::DoubleList(), DoubleListElem(), est_dernier(), est_vide(), DoubleList::operator=(), operator==(), suivant(), DoubleList::suppr(), DoubleList::vide(), and ~DoubleListElem().
The documentation for this class was generated from the following files:
src/Kernel/Math/DoubleListElem.h
src/Kernel/Math/DoubleListElem.cpp