TRUST: Simpler Class Reference
Simpler Class Reference
#include <Simpler.h>
Public Member Functions
Simpler ()
~Simpler ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok) override
Public Member Functions inherited from Simple
~Simple ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Simple ()
bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok) override
void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok) override
bool iterer_eqs (List_Ref_Equation_base eqs, int compteur, int &ok) override
Public Member Functions inherited from Simpler_Base
~Simpler_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int max_iter_implicite ()
int max_iter_implicite () const
bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok) override=0
virtual void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok)=0
void assembler_matrice_pression_implicite (Equation_base &eqn_NS, const Matrice_Morse &matrice, Matrice &matrice_en_pression_2)
Parametre_equation & get_and_set_parametre_equation (Equation_base &) override
retourne le parametre_implicte de l'equation si il existe si il n'existe pas le cree...
si les params sont vides on copie ceux du simpler
Parametre_implicite & get_and_set_parametre_implicite (Equation_base &eqn)
Public Member Functions inherited from Solveur_non_lineaire
Solveur_non_lineaire ()
~Solveur_non_lineaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Solveur_Implicite_Base
Solveur_Implicite_Base ()
~Solveur_Implicite_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok)=0
virtual bool iterer_eqs (List_Ref_Equation_base eqs, int n, int &ok)
virtual bool est_compatible_avec_th_mono () const
virtual int nb_valeurs_temporelles_pression () const
virtual double get_default_facsec_max () const
virtual double get_default_growth_factor () const
virtual Parametre_equation & get_and_set_parametre_equation (Equation_base &eqn)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Simpler & self_cast (Objet_U &)
static const Simpler & self_cast (const Objet_U &)
Static Public Member Functions inherited from Simple
static Objet_U * cree_instance ()
static const Type_info * info ()
static Simple & self_cast (Objet_U &)
static const Simple & self_cast (const Objet_U &)
Static Public Member Functions inherited from Simpler_Base
static const Type_info * info ()
static Simpler_Base & self_cast (Objet_U &)
static const Simpler_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_non_lineaire
static const Type_info * info ()
static Solveur_non_lineaire & self_cast (Objet_U &)
static const Solveur_non_lineaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_Implicite_Base
static const Type_info * info ()
static Solveur_Implicite_Base & self_cast (Objet_U &)
static const Solveur_Implicite_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Simple
static const Type_info info_obj
Static Public Attributes inherited from Simpler_Base
static const Type_info info_obj
Static Public Attributes inherited from Solveur_non_lineaire
static const Type_info info_obj
Static Public Attributes inherited from Solveur_Implicite_Base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Simple
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Entree & lire (const Motcle &, Entree &) override
void calculer_correction_en_vitesse (const DoubleTrav &correction_en_pression, DoubleTrav &gradP, DoubleTrav &correction_en_vitesse, const Matrice_Morse &matrice, const Operateur_Grad &gradient)
Protected Member Functions inherited from Simpler_Base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual Entree & lire (const Motcle &, Entree &)=0
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Simple
DoubleTab Ustar_old
double alpha_
double beta_
int with_d_rho_dt_
std::map< std::vector< intptr_t >, Matrice_Bloc > mbloc
Protected Attributes inherited from Simpler_Base
Parametre_implicite param_defaut_
int is_seuil_convg_variable
double facteur_convg_
int no_qdm_
int controle_residu_
Detailed Description
Definition at line 74 of file Simpler.h.
Constructor & Destructor Documentation
Simpler()
Simpler::Simpler ()
Definition at line 28 of file Simpler.cpp.
~Simpler()
Simpler::~Simpler ()
Definition at line 28 of file Simpler.cpp.
Member Function Documentation
cree_instance()
Objet_U * Simpler::cree_instance () static
Definition at line 28 of file Simpler.cpp.
duplique()
int Simpler::duplique () const override virtual
Reimplemented from Simple.
Definition at line 28 of file Simpler.cpp.
get_info()
const Type_info * Simpler::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Simple.
Definition at line 28 of file Simpler.cpp.
info()
const Type_info * Simpler::info () static
Definition at line 28 of file Simpler.cpp.
iterer_NS()
void Simpler::iterer_NS (Equation_base & eqn, DoubleTab & current, DoubleTab & pression, double dt, Matrice_Morse & matrice, double seuil_resol, DoubleTrav & secmem, int nb_iter, int & converge, int & ok) override virtual
Reimplemented from Simple.
Definition at line 150 of file Simpler.cpp.
{
  if (eqn.probleme().is_dilatable())
    {
      Cerr<<" Simpler cannot be used with a quasi-compressible fluid."<<finl;
      Cerr<<__FILE__<<(int)__LINE__<<" non code" <<finl;
      exit();
    }
  Parametre_implicite& param = get_and_set_parametre_implicite(eqn);
  SolveurSys& le_solveur_ = param.solveur();
  Navier_Stokes_std& eqnNS = ref_cast(Navier_Stokes_std,eqn);
  DoubleTrav gradP(current);
  DoubleTrav correction_en_pression(pression);
  DoubleTrav correction_en_vitesse(current);
  DoubleTrav resu(current);
// int deux_entrees = 0;
// if (current.nb_dim()==2) deux_entrees = 1;
  Operateur_Grad& gradient = eqnNS.operateur_gradient();
  Operateur_Div& divergence = eqnNS.operateur_divergence();
// int nb_comp = 1;
// int nb_dim = current.nb_dim();
// if (nb_dim==2)
// nb_comp = current.dimension(1);
// Construction de matrice et resu
// matrice = A[Uk-1] = M/dt + CONV +DIFF
// resu =  A[Uk-1]Uk-1 -(A[Uk-1]Uk-1-Ss) + Sv -BtPk-1
  gradient.calculer(pression,gradP);
  if (eqnNS.has_interface_blocs()) /* si assembler_blocs est disponible */
    eqnNS.assembler_blocs_avec_inertie({{ "vitesse", &matrice }}, resu);
  else
    {
      resu -= gradP;
      eqnNS.assembler_avec_inertie(matrice,current,resu);
    }
  le_solveur_.valeur().reinit();
// Resolution du systeme : D[Uk-1]UPk = E[Uk-1]Uk-1 + Sv + Ss -BtPk-1 + (M/dt)Uk-1
// matrice = A[Uk-1] = D - E avec D partie diagonale de A
// correction_en_vitesse = UPk ; current = Uk-1 ; resu = Sv + Ss -BtPk-1
  int status = inverser_par_diagonale(matrice,resu,current,correction_en_vitesse);
  if (status!=0) exit();
  Debog::verifier("Simpler::iterer_NS correction_en_vitesse",correction_en_vitesse);
// Construction de matrice_en_pression_2 = BD-1Bt[Uk-1]
  Matrice& matrice_en_pression_2 = eqnNS.matrice_pression();
  assembler_matrice_pression_implicite(eqnNS,matrice,matrice_en_pression_2);
  SolveurSys& solveur_pression_ = eqnNS.solveur_pression();
  solveur_pression_.valeur().reinit();
// Calcul de BUPk
  divergence.calculer(correction_en_vitesse,secmem);
  secmem *= -1;
  secmem.echange_espace_virtuel();
  if (nb_ite==1)
    eqnNS.assembleur_pression().valeur().modifier_secmem(secmem);
// Resolution du systeme (BD-1Bt)P*_k = BUPk
// correction_en_pression = P*_k ; secmem = BUPk
  solveur_pression_.resoudre_systeme(matrice_en_pression_2.valeur(),
                                     secmem,correction_en_pression);
// Calcul de Pk = Pk-1 + P*_k
  operator_add(pression, correction_en_pression, VECT_ALL_ITEMS);
  eqnNS.assembleur_pression().valeur().modifier_solution(pression);
// Calcul de Bt P*_k et ajustement de resu a -Bt Pk
  gradient.valeur().multvect(correction_en_pression,gradP);
  resu -= gradP;
  resu.echange_espace_virtuel();
  Debog::verifier("Simpler::iterer_NS resu",resu);
// Resolution du systeme : A[Uk-1]U*_k = -BtPk + Sv + Ss + (M/dt)Uk-1
// current = U*_k ; resu = A[Uk-1]Uk-1 - (A[Uk-1]Uk-1-Ss) + Sv -BtPk + (M/dt)Uk-1
  le_solveur_.resoudre_systeme(matrice,resu,current);
// Calcul de BU*_k
  divergence.calculer(current,secmem);
  secmem *= -1;
  secmem.echange_espace_virtuel();
  Debog::verifier("Simpler::iterer_NS secmem",secmem);
// Resolution du systeme (BD-1Bt)P'k = BU*_k
// correction_en_pression = P'k ; secmem = BU*_k
  correction_en_pression = 0;
  solveur_pression_.resoudre_systeme(matrice_en_pression_2.valeur(),
                                     secmem,correction_en_pression);
// Resolution du systeme D[Uk-1](Uk-U*_k) = -BtP'k
// correction_en_vitesse = U'k = Uk-U*_k ; correction_en_pression = P'k
  calculer_correction_en_vitesse(correction_en_pression,gradP,correction_en_vitesse,matrice,gradient);
  if (0)
    {
      Cerr<<" rr "<<mp_max_abs_vect(secmem)<<finl;
// Cerr<<secmem<<finl;
      secmem*=-1;
      divergence.ajouter(correction_en_vitesse, secmem);
      Cerr<<" rr2 "<<mp_max_abs_vect(secmem)<<finl;
    }
// Calcul de Uk = U*_k + U'k
  current += correction_en_vitesse;
  current.echange_espace_virtuel();
  Debog::verifier("Simpler::iterer_NS current",current);
  if (0)
    {
      divergence.calculer(current, secmem);
      Cerr<<" apresdiv "<<mp_max_abs_vect(secmem)<<finl;;
    }
}
References Operateur_Div::ajouter(), Equation_base::assembler_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Simpler_Base::assembler_matrice_pression_implicite(), Navier_Stokes_std::assembleur_pression(), Operateur_Div::calculer(), Operateur_Grad::calculer(), Simple::calculer_correction_en_vitesse(), Cerr, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, Simpler_Base::get_and_set_parametre_implicite(), Navier_Stokes_std::has_interface_blocs(), inverser_par_diagonale(), Probleme_base::is_dilatable(), Navier_Stokes_std::matrice_pression(), Assembleur_base::modifier_secmem(), Assembleur_base::modifier_solution(), mp_max_abs_vect(), Operateur_Grad_base::multvect(), Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::operateur_gradient(), operator_add(), Equation_base::probleme(), ref_cast, SolveurSys_base::reinit(), SolveurSys::resoudre_systeme(), Parametre_implicite::solveur(), Navier_Stokes_std::solveur_pression(), Deriv_Assembleur_base::valeur(), Deriv_Matrice_Base::valeur(), Deriv_SolveurSys_base::valeur(), Deriv_Operateur_Grad_base::valeur(), VECT_ALL_ITEMS, and Debog::verifier().
printOn()
Sortie & Simpler::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Simple.
Definition at line 30 of file Simpler.cpp.
{
  return Simple::printOn(os);
}
References Simple::printOn().
Referenced by SETS::printOn(), and Piso::printOn().
readOn()
Entree & Simpler::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Simple.
Definition at line 35 of file Simpler.cpp.
{
  return Simple::readOn(is);
}
References Simple::readOn().
Referenced by SETS::readOn(), and Piso::readOn().
self_cast() [1/2]
const Simpler & Simpler::self_cast (const Objet_U & r) static
Definition at line 28 of file Simpler.cpp.
self_cast() [2/2]
Simpler & Simpler::self_cast (Objet_U & r) static
Definition at line 28 of file Simpler.cpp.
taille_memoire()
unsigned Simpler::taille_memoire () const override virtual
Reimplemented from Simple.
Definition at line 28 of file Simpler.cpp.
Member Data Documentation
info_obj
const Type_info Simpler::info_obj static
Definition at line 77 of file Simpler.h.
The documentation for this class was generated from the following files:
src/ThHyd/Schemas_Temps/Simpler.h
src/ThHyd/Schemas_Temps/Simpler.cpp