TRUST: OBuffer Class Reference
OBuffer Class Reference
#include <OBuffer.h>
Public Member Functions
OBuffer ()
~OBuffer () override
void new_buffer ()
void precision (int) override
int get_precision ()
const char * str ()
Renvoie un pointeur sur le debut du buffer.
int len ()
int set_bin (int bin) override
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
void put_null_char ()
ajoute le caractere nul a la fin du buffer pour en faire une chaine
de caracteres valide. len() renvoie la longueur du buffer, y compris le \0
Voir Ecr_Fic_Par::syncfile()
Sortie & flush () override
Force l'ecriture sur disque des donnees dans le tampon
Utilise l'implementation de la classe ofstream.
Public Member Functions inherited from Sortie
Sortie ()
Sortie (ostream &os)
Sortie (const Sortie &os)
Sortie & operator= (ostream &os)
Sortie & operator= (Sortie &os)
ostream & get_ostream ()
const ostream & get_ostream () const
void set_ostream (ostream *os)
void set_col_width (const int)
Sortie & operator<< (ostream &(*f)(ostream &))
Sortie & operator<< (Sortie &(*f)(Sortie &))
Sortie & operator<< (ios &(*f)(ios &))
virtual Sortie & flush ()
virtual Sortie & lockfile ()
virtual Sortie & unlockfile ()
virtual Sortie & syncfile ()
virtual void setf (std::_Ios_Fmtflags)
virtual void precision (int)
virtual Sortie & operator<< (const Separateur &)
virtual Sortie & operator<< (const Objet_U &ob)
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
virtual Sortie & operator<< (const int ob)
virtual Sortie & operator<< (const unsigned ob)
virtual Sortie & operator<< (const long ob)
virtual Sortie & operator<< (const float ob)
virtual Sortie & operator<< (const double ob)
virtual Sortie & operator<< (const char *ob)
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
virtual Sortie & operator<< (const std::string &str)
virtual int add_col (const double ob)
virtual int add_col (const char *ob)
virtual int put (const unsigned *ob, int n, int nb_colonnes=1)
virtual int put (const int *ob, int n, int nb_colonnes=1)
virtual int put (const float *ob, int n, int nb_colonnes=1)
virtual int put (const double *ob, int n, int nb_colonnes=1)
virtual int put (const long *ob, int n, int nb_colonnes=1)
virtual ~Sortie ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
int is_bin ()
bool has_ostream () const
Private Attributes
int precision_
used to keep current precision when new_buffer() is called
std::ostringstream * buf_
std::string string_
Additional Inherited Members
Protected Attributes inherited from Sortie
int bin_
int col_width_
Detailed Description
Definition at line 24 of file OBuffer.h.
Constructor & Destructor Documentation
OBuffer()
OBuffer::OBuffer ()
Definition at line 18 of file OBuffer.cpp.
                 :
  precision_(8), buf_(0)
{
  new_buffer();
}
References new_buffer().
~OBuffer()
OBuffer::~OBuffer () override
< Empeche Sortie::~Sortie de detruire l'objet une deuxieme fois.
Definition at line 24 of file OBuffer.cpp.
{
  if(buf_)
    delete buf_;
  buf_=0;
  set_ostream(buf_); //!< Empeche Sortie::~Sortie de detruire l'objet une deuxieme fois.
}
References buf_, and Sortie::set_ostream().
Member Function Documentation
flush()
Sortie & OBuffer::flush () override virtual
Force l'ecriture sur disque des donnees dans le tampon
Utilise l'implementation de la classe ofstream.
Returns
Sortie&
Signification: *this
Contraintes:
Reimplemented from Sortie.
Definition at line 67 of file OBuffer.cpp.
{
  return *this;
}
get_precision()
int OBuffer::get_precision ()
Definition at line 48 of file OBuffer.cpp.
{
  return buf_->precision();
}
References buf_.
Referenced by EcrFicPartage::get_precision().
len()
int OBuffer::len ()
Definition at line 92 of file OBuffer.cpp.
{
  return buf_->tellp();
}
References buf_.
Referenced by EcrFicPartage::close(), and EcrFicPartage::syncfile().
new_buffer()
void OBuffer::new_buffer ()
Definition at line 32 of file OBuffer.cpp.
{
  if(buf_)
    delete buf_;
  buf_ = new std::ostringstream();
  set_ostream(buf_);
  buf_->setf(ios::scientific);
  buf_->precision(precision_);
}
References buf_, precision_, and Sortie::set_ostream().
Referenced by OBuffer(), EcrFicPartage::ouvrir(), and EcrFicPartage::syncfile().
precision()
void OBuffer::precision (int i) override virtual
Reimplemented from Sortie.
Definition at line 42 of file OBuffer.cpp.
{
  precision_ = i;
  buf_->precision(i);
}
References buf_, and precision_.
Referenced by EcrFicPartage::precision().
put_null_char()
void OBuffer::put_null_char ()
ajoute le caractere nul a la fin du buffer pour en faire une chaine
de caracteres valide. len() renvoie la longueur du buffer, y compris le \0
Voir Ecr_Fic_Par::syncfile()
< Ca n'a pas de sens en binaire
Definition at line 76 of file OBuffer.cpp.
{
  assert(! bin_); //!< Ca n'a pas de sens en binaire
  buf_->put('\0');
}
References Sortie::bin_, and buf_.
Referenced by EcrFicPartage::syncfile().
set_bin()
int OBuffer::set_bin (int bin) override virtual
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
Reimplemented from Sortie.
Definition at line 97 of file OBuffer.cpp.
{
  assert(bin==0 || bin==1);
  bin_ = bin;
  return bin_;
}
References Sortie::bin_.
Referenced by EcrFicPartage::set_bin().
str()
const char * OBuffer::str ()
Renvoie un pointeur sur le debut du buffer.
Definition at line 84 of file OBuffer.cpp.
{
// Need a copy:
  string_ = buf_->str();
  return string_.c_str();
}
References buf_, and string_.
Referenced by EcrFicPartage::close(), and EcrFicPartage::syncfile().
Member Data Documentation
buf_
std::ostringstream* OBuffer::buf_ private
Definition at line 44 of file OBuffer.h.
Referenced by get_precision(), len(), new_buffer(), precision(), put_null_char(), str(), and ~OBuffer().
precision_
int OBuffer::precision_ private
used to keep current precision when new_buffer() is called
Definition at line 43 of file OBuffer.h.
Referenced by new_buffer(), and precision().
string_
std::string OBuffer::string_ private
Definition at line 45 of file OBuffer.h.
Referenced by str().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/OBuffer.h
src/Kernel/Utilitaires/OBuffer.cpp