TRUST: Polygone Class Reference
Polygone Class Reference
Classe Polygone
Cette represente l'element geometrique Polygone.
Un polyedre est un element defini par ses faces
de type Faces::polygone_3D.
#include <Polygone.h>
Public Member Functions
Polygone ()
~Polygone ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int face_sommet (int i, int j) const override
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
int nb_som () const override
Renvoie le nombre de sommets d'un Polygone.
int nb_faces (int=0) const override
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
Un Polygone a 1 type de faces: polygon_3D.
int nb_som_face (int=0) const override
Renvoie le nombre maximum de sommets des faces
du type specifie.
int est_structure () const override
const Nom & nom_lml () const override
Renvoie le nom LML d'un polyedre = "POLYEDRE_"+nb_som_max.
int contient (const ArrOfDouble &, int) const override
NE FAIT RIEN: A CODER, renvoie toujours 0.
Renvoie 1 si l'element "element" de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
int contient (const ArrOfInt &, int) const override
NE FAIT RIEN: A CODER, renvoie toujours 0
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Type_Face type_face (int=0) const override
Renvoie le i-ieme type de face.
Un polyedre a 2 types de face: quadrangle et triangle.
void reordonner () override
Reordonne les sommets du Polygone.
NE FAIT RIEN: A CODER.
void calculer_volumes (DoubleVect &) const override
NE FAIT RIEN: A CODER
Calcule les volumes des elements de la zone associee.
void calculer_centres_gravite (DoubleTab &xp) const override
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
void calculer_un_centre_gravite (const int elem, DoubleVect &xp) const override
int nb_type_face () const override
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const override
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
int get_tab_faces_sommets_locaux (IntTab &faces_som_local, int elem) const override
void affecte_connectivite_numero_global (const ArrOfInt &FacesIndex, const ArrOfInt &PolygonIndex, IntTab &les_elems)
int get_nb_som_elem_max () const
int get_nb_face_elem_max () const
int get_somme_nb_faces_elem () const override
const ArrOfInt & getFacesIndex () const override
const ArrOfInt & getPolygonIndex () const
const ArrOfInt & getElemIndex () const override
void rebuild_index ()
void build_reduced (Elem_geom &type_elem, const ArrOfInt &elems_sous_part) const override
void compute_virtual_index () override
Public Member Functions inherited from Poly_geom_base
Poly_geom_base ()
~Poly_geom_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const override=0
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
virtual int get_tab_faces_sommets_locaux (IntTab &faces_som_local, int elem) const =0
virtual const ArrOfInt & getFacesIndex () const =0
virtual const ArrOfInt & getElemIndex () const =0
virtual int get_somme_nb_faces_elem () const =0
virtual void calculer_un_centre_gravite (const int elem, DoubleVect &xp) const =0
virtual void build_reduced (Elem_geom &type_elem, const ArrOfInt &elems_sous_part) const =0
virtual void compute_virtual_index ()=0
Public Member Functions inherited from Elem_geom_base
Elem_geom_base ()
~Elem_geom_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void creer_faces_elem (Faces &, int, Type_Face) const
Cree les faces de l'element geometrique specifie de la zone
en precisant le type de face a creer.
void creer_faces_elem (Faces &, int) const
Cree les faces de l'element de la zone specifie.
virtual int face_sommet (int i, int j) const =0
void associer_zone (const Zone &)
Associe l'element geometrique a sa zone.
virtual int nb_som () const =0
virtual int nb_faces (int=0) const =0
virtual int nb_som_face (int=0) const =0
virtual int est_structure () const =0
virtual const Nom & nom_lml () const =0
virtual int contient (const ArrOfDouble &, int) const =0
virtual int contient (const ArrOfInt &, int) const =0
virtual int nb_type_face () const
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
virtual int num_face (int face, Type_Face &type) const
Renvoie le parametre face si le type
de face specifie est le meme que celui de l'element
geometrique.
virtual Type_Face type_face (int=0) const =0
virtual void calculer_centres_gravite (DoubleTab &) const
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
virtual void reordonner ()
NE FAIT RIEN:
A surcharger dans les classes derivees.
virtual void calculer_volumes (DoubleVect &) const =0
virtual void calculer_normales (const IntTab &faces_sommets, DoubleTab &face_normales) const
Sort en erreur. Cette methode n'est pas virtuelle pure
pour des raisons de commodite.
virtual int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
virtual void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const
idem que Elem_geom_base::get_tab_faces_sommets_locaux mais pour les aretes:
aretes_som_local.dimension(0) = nombre d'aretes sur l'element de reference
aretes_som_local.dimension(1) = 2 (nombre de sommets par arete)
aretes_som_local(i,j) = numero d'un sommet de l'element (0 <= n < nb_sommets_par_element)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Polygone & self_cast (Objet_U &)
static const Polygone & self_cast (const Objet_U &)
Static Public Member Functions inherited from Poly_geom_base
static const Type_info * info ()
static Poly_geom_base & self_cast (Objet_U &)
static const Poly_geom_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Elem_geom_base
static const Type_info * info ()
static Elem_geom_base & self_cast (Objet_U &)
static const Elem_geom_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Poly_geom_base
static const Type_info info_obj
Static Public Attributes inherited from Elem_geom_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
ArrOfInt FacesIndex_
ArrOfInt PolygonIndex_
PolygoneIndex_[ele] numero premiere face de ele (sert sutrout en diff) FaceIndex_ numerotation globale a la zone ne sert qu'a med.
int nb_som_elem_max_
int nb_face_elem_max_
Additional Inherited Members
Protected Attributes inherited from Elem_geom_base
Ref_Zone ma_zone
Detailed Description
Classe Polygone
Cette represente l'element geometrique Polygone.
Un polyedre est un element defini par ses faces
de type Faces::polygone_3D.
Definition at line 40 of file Polygone.h.
Constructor & Destructor Documentation
Polygone()
Polygone::Polygone ()
Definition at line 25 of file Polygone.cpp.
                  : FacesIndex_(1),PolygonIndex_(1)
{
  PolygonIndex_[0]=0;
  FacesIndex_[0]=0;
  nb_som_elem_max_=-1;
  nb_face_elem_max_=0;
}
References FacesIndex_, nb_face_elem_max_, nb_som_elem_max_, and PolygonIndex_.
~Polygone()
Polygone::~Polygone ()
Definition at line 23 of file Polygone.cpp.
Member Function Documentation
affecte_connectivite_numero_global()
void Polygone::affecte_connectivite_numero_global (const ArrOfInt & FacesIndex, const ArrOfInt & PolygonIndex, IntTab & les_elems)
Definition at line 412 of file Polygone.cpp.
{
  nb_som_elem_max_=0;
// detremination de nbsom_max
  IntList prov;
  nb_face_elem_max_=0;
  int nelem=PolygonIndex.size_array()-1;
  for (int ele=0; ele<nelem; ele++)
    {
      prov.vide();
      int nbf=PolygonIndex[ele+1]-PolygonIndex[ele];
      if (nbf>nb_face_elem_max_) nb_face_elem_max_=nbf;
      for (int f=PolygonIndex[ele]; f<PolygonIndex[ele+1]; f++)
        {
// Cerr<<" ici "<<ele << " " <<f <<" "<<FacesIndex(f+1)-FacesIndex(f)<<finl;
// for (int s=FacesIndex(f); s<FacesIndex(f+1); s++)
          {
            prov.add_if_not(FacesIndex[f]);
          }
        }
      int nbsom=prov.size();
      if (nbsom>nb_som_elem_max_) nb_som_elem_max_=nbsom;
    }
  Cerr<<" Polygon information nb_som_elem_max "<< nb_som_elem_max_<<" nb_face_elem_max "<<nb_face_elem_max_<<finl;
  les_elems.resize(nelem,nb_som_elem_max_);
  les_elems=-1;
// on refait un tour pour determiiner les elems
  for (int ele=0; ele<nelem; ele++)
    {
      prov.vide();
      for (int f=PolygonIndex[ele]; f<PolygonIndex[ele+1]; f++)
        {
// for (int s=FacesIndex(f); s<FacesIndex(f+1); s++)
          {
            prov.add_if_not(FacesIndex[f]);
          }
        }
      int nbsom=prov.size();
      for (int s=0; s<nbsom; s++) les_elems(ele,s)=prov[s];
    }
  FacesIndex_=FacesIndex;
  PolygonIndex_=PolygonIndex;
  assert(nb_face_elem_max_==nb_som_elem_max_);
}
References TRUSTList< _TYPE_ >::add_if_not(), Cerr, FacesIndex_, finl, nb_face_elem_max_, nb_som_elem_max_, PolygonIndex_, TRUSTTab< _TYPE_ >::resize(), TRUSTList< _TYPE_ >::size(), TRUSTArray< _TYPE_ >::size_array(), and TRUSTList< _TYPE_ >::vide().
build_reduced()
void Polygone::build_reduced (Elem_geom & type_elem, const ArrOfInt & elems_sous_part) const override virtual
Implements Poly_geom_base.
Definition at line 85 of file Polygone.cpp.
{
  const IntTab& les_elems = ma_zone.valeur().les_elems();
  type_elem.typer("Polygone");
  Polygone& reduced = ref_cast(Polygone, type_elem.valeur());
  reduced.nb_som_elem_max_  = nb_som_elem_max_;
  reduced.nb_face_elem_max_ = nb_face_elem_max_;
  ArrOfInt& Pi = reduced.PolygonIndex_, &Fi = reduced.FacesIndex_;
  Pi.set_smart_resize(1), Fi.resize(0), Fi.set_smart_resize(1);
  for (int i = 0; i < elems_sous_part.size_array(); i++)
    {
      int e = elems_sous_part[i];
      for (int f = PolygonIndex_[e]; f < PolygonIndex_[e + 1]; f++)
        {
          Fi.append_array(les_elems(e, f - PolygonIndex_[e]));
        }
      Pi.append_array(Fi.size_array());
    }
}
References TRUSTArray< _TYPE_ >::append_array(), FacesIndex_, Zone::les_elems(), Elem_geom_base::ma_zone, nb_face_elem_max_, nb_som_elem_max_, PolygonIndex_, ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), type_elem(), and Ref_Zone::valeur().
calculer_centres_gravite()
void Polygone::calculer_centres_gravite (DoubleTab & xp) const override virtual
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
Reimplemented from Elem_geom_base.
Definition at line 477 of file Polygone.cpp.
{
  const Zone& zone=ma_zone.valeur();
  const IntTab& elem=zone.les_elems();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  int nb_elem;
  if(xp.dimension(0)==0)
    {
      nb_elem = ma_zone->nb_elem_tot();
      xp.resize(nb_elem,dimension);
    }
  else
    nb_elem=xp.dimension(0);
  xp=0;
  DoubleTab pos(3,dimension);
  ArrOfDouble xpl(dimension);
  for (int num_poly=0; num_poly<nb_elem; num_poly++)
    {
      double aire=0;
      xpl=0;
      int s0=elem(num_poly,0);
      for (int d=0; d<dimension; d++)
        pos(0,d)=coord(s0,d);
      for (int s=1; s<get_nb_som_elem_max()-1 ; s++)
        {
          int s1=elem(num_poly,s);
          int s2=elem(num_poly,s+1);
          if (s2<0)
            break;
          for (int d=0; d<dimension; d++)
            {
              pos(1,d)=coord(s1,d);
              pos(2,d)=coord(s2,d);
            }
          double airel = aire_triangle(pos);
          for (int d=0; d<dimension; d++)
            xpl[d]+=airel*(pos(0,d)+pos(1,d)+pos(2,d));
          aire+=airel;
        }
      aire*=3.;
      for (int d=0; d<dimension; d++)
        xp(num_poly,d)=xpl[d]/(aire);
    }
}
References aire_triangle(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), get_nb_som_elem_max(), Zone::les_elems(), Elem_geom_base::ma_zone, Zone::nb_elem_tot(), TRUSTTab< _TYPE_ >::resize(), and Ref_Zone::valeur().
calculer_un_centre_gravite()
void Polygone::calculer_un_centre_gravite (const int elem, DoubleVect & xp) const override virtual
Implements Poly_geom_base.
Definition at line 524 of file Polygone.cpp.
{
  const Zone& zone=ma_zone.valeur();
  const IntTab& elem=zone.les_elems();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  xp.resize(dimension);
  xp=0;
  DoubleTab pos(3,dimension);
  ArrOfDouble xpl(dimension);
  {
    double aire=0;
    xpl=0;
    int s0=elem(num_poly,0);
    for (int d=0; d<dimension; d++)
      pos(0,d)=coord(s0,d);
    for (int s=1; s<nb_som_elem_max_-1 ; s++)
      {
        int s1=elem(num_poly,s);
        int s2=elem(num_poly,s+1);
        if (s2<0)
          break;
        for (int d=0; d<dimension; d++)
          {
            pos(1,d)=coord(s1,d);
            pos(2,d)=coord(s2,d);
          }
        double airel = aire_triangle(pos);
        for (int d=0; d<dimension; d++)
          xpl[d]+=airel*(pos(0,d)+pos(1,d)+pos(2,d));
        aire+=airel;
      }
    aire*=3.;
    for (int d=0; d<dimension; d++)
      xp(d)=xpl[d]/(aire);
  }
}
References aire_triangle(), Domaine::coord_sommets(), Objet_U::dimension, Zone::domaine(), Zone::les_elems(), Elem_geom_base::ma_zone, nb_som_elem_max_, TRUSTVect< _TYPE_ >::resize(), and Ref_Zone::valeur().
calculer_volumes()
void Polygone::calculer_volumes (DoubleVect & volumes) const override virtual
NE FAIT RIEN: A CODER
Calcule les volumes des elements de la zone associee.
Implements Elem_geom_base.
Definition at line 312 of file Polygone.cpp.
{
  const Zone& zone=ma_zone.valeur();
  const IntTab& elem=zone.les_elems();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  int size = zone.nb_elem();
  assert(volumes.size_totale()==zone.nb_elem_tot());
  DoubleTab pos(3,dimension);
  for (int num_poly=0; num_poly<size; num_poly++)
    {
      double aire=0;
      int s0=elem(num_poly,0);
      for (int d=0; d<dimension; d++)
        pos(0,d)=coord(s0,d);
      for (int s=1; s<get_nb_som_elem_max()-1 ; s++)
        {
          int s1=elem(num_poly,s);
          int s2=elem(num_poly,s+1);
          if (s2<0)
            break;
          for (int d=0; d<dimension; d++)
            {
              pos(1,d)=coord(s1,d);
              pos(2,d)=coord(s2,d);
            }
          aire += aire_triangle(pos);
        }
      volumes(num_poly)=aire;
    }
  volumes.echange_espace_virtuel();
  return ;
}
References aire_triangle(), Domaine::coord_sommets(), Objet_U::dimension, Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), get_nb_som_elem_max(), Zone::les_elems(), Elem_geom_base::ma_zone, Zone::nb_elem(), Zone::nb_elem_tot(), TRUSTVect< _TYPE_ >::size_totale(), and Ref_Zone::valeur().
compute_virtual_index()
void Polygone::compute_virtual_index () override virtual
Implements Poly_geom_base.
Definition at line 108 of file Polygone.cpp.
{
  rebuild_index();
}
References rebuild_index().
contient() [1/2]
int Polygone::contient (const ArrOfDouble & pos_r, int num_poly) const override virtual
NE FAIT RIEN: A CODER, renvoie toujours 0.
Renvoie 1 si l'element "element" de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
Returns
int
Signification: 1 si le point de coordonnees specifiees
appartient a l'element "element"
0 sinon
Contraintes:
Implements Elem_geom_base.
Definition at line 238 of file Polygone.cpp.
{
  const Zone& zone=ma_zone.valeur();
  const IntTab& elem=zone.les_elems();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  DoubleTab pos(3,dimension);
// on decoupe le polygone en triangle ayany tous le sommet 0.
  int s0=elem(num_poly,0);
  for (int s=1; s<nb_som_elem_max_-1 ; s++)
    {
      int s1=elem(num_poly,s);
      int s2=elem(num_poly,s+1);
      if (s2<0)
        break;
      if (contient_triangle(pos_r,s0,s1,s2,coord))
        return 1;
    }
  return 0;
}
References contient_triangle(), Domaine::coord_sommets(), Objet_U::dimension, Zone::domaine(), Zone::les_elems(), Elem_geom_base::ma_zone, nb_som_elem_max_, and Ref_Zone::valeur().
contient() [2/2]
int Polygone::contient (const ArrOfInt & pos, int element) const override virtual
NE FAIT RIEN: A CODER, renvoie toujours 0
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Returns
int
Signification: 1 si les sommets passes en parametre
sont ceux de l'element specifie, 0 sinon
Contraintes:
Implements Elem_geom_base.
Definition at line 287 of file Polygone.cpp.
{
  BLOQUE;
// a coder :
  exit();
  return 0;
}
References BLOQUE, and Process::exit().
cree_instance()
Objet_U * Polygone::cree_instance () static
Definition at line 23 of file Polygone.cpp.
duplique()
int Polygone::duplique () const override virtual
Implements Objet_U.
Definition at line 23 of file Polygone.cpp.
est_structure()
int Polygone::est_structure () const inline override virtual
Returns
int
Signification: 1 si l'element est de type structure
0 sinon
Contraintes: toujours egal a 0
Implements Elem_geom_base.
Definition at line 203 of file Polygone.h.
{
  return 0;
}
face_sommet()
int Polygone::face_sommet (int face, int sommet) const inline override virtual
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
Returns
int
Signification: le numero du j-ieme sommet de la i-ieme face
Contraintes:
Implements Elem_geom_base.
Definition at line 116 of file Polygone.h.
{
  BLOQUE;
  return -1;
}
References BLOQUE.
get_info()
const Type_info * Polygone::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Poly_geom_base.
Definition at line 23 of file Polygone.cpp.
get_nb_face_elem_max()
int Polygone::get_nb_face_elem_max () const inline
Definition at line 68 of file Polygone.h.
  {
    return nb_face_elem_max_ ;
  } ;
References nb_face_elem_max_.
Referenced by nb_faces().
get_nb_som_elem_max()
int Polygone::get_nb_som_elem_max () const
Definition at line 141 of file Polygone.cpp.
{
  if (nb_som_elem_max_>-1)
    return nb_som_elem_max_ ;
  else
    return ma_zone.valeur().les_elems().dimension(1);
}
References TRUSTTab< _TYPE_ >::dimension(), Zone::les_elems(), Elem_geom_base::ma_zone, nb_som_elem_max_, and Ref_Zone::valeur().
Referenced by calculer_centres_gravite(), calculer_volumes(), nb_som(), nom_lml(), and rebuild_index().
get_somme_nb_faces_elem()
int Polygone::get_somme_nb_faces_elem () const override virtual
Implements Poly_geom_base.
Definition at line 114 of file Polygone.cpp.
{
  return PolygonIndex_[ma_zone.valeur().nb_elem()];
}
References Elem_geom_base::ma_zone, Zone::nb_elem(), PolygonIndex_, and Ref_Zone::valeur().
get_tab_faces_sommets_locaux() [1/2]
int Polygone::get_tab_faces_sommets_locaux (IntTab & faces_som_local) const override virtual
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
Implements Poly_geom_base.
Definition at line 364 of file Polygone.cpp.
{
  return 0;
}
get_tab_faces_sommets_locaux() [2/2]
int Polygone::get_tab_faces_sommets_locaux (IntTab & faces_som_local, int elem) const override virtual
Implements Poly_geom_base.
Definition at line 368 of file Polygone.cpp.
{
  faces_som_local.resize(nb_face_elem_max_,nb_som_face());
  faces_som_local=-1;
// on cherche les faces de l'elt
  int nb_face=PolygonIndex_[ele+1]-PolygonIndex_[ele];
  /*
   les elems pas remplis
    int nb_face2=get_nb_som_elem_max();
    const IntTab& les_elems = ma_zone.valeur().les_elems();
    {
    while (les_elems(ele,nb_face2-1)<0)
      nb_face2--;
    }
    assert(nb_face==nb_face2);
  */
  for (int fl=0; fl<nb_face-1; fl++)
    {
// numerotion locale ou globale ????
      faces_som_local(fl,0)=fl;
      faces_som_local(fl,1)=fl+1;
    }
  {
    int fl=nb_face-1;
    faces_som_local(fl,0)=fl;
    faces_som_local(fl,1)=0;
  }
  /*
    IntTab test;
    get_tab_faces_sommets_locaux(test,ele);
    test-=faces_som_local;
    assert(mp_max_abs_vect(test)==0);
  */
  return 1;
}
References nb_face_elem_max_, nb_som_face(), PolygonIndex_, and TRUSTTab< _TYPE_ >::resize().
getElemIndex()
const ArrOfInt & Polygone::getElemIndex () const inline override virtual
Implements Poly_geom_base.
Definition at line 83 of file Polygone.h.
  {
    return PolygonIndex_;
  };
References PolygonIndex_.
getFacesIndex()
const ArrOfInt & Polygone::getFacesIndex () const inline override virtual
Implements Poly_geom_base.
Definition at line 75 of file Polygone.h.
  {
    return FacesIndex_;
  };
References FacesIndex_.
getPolygonIndex()
const ArrOfInt & Polygone::getPolygonIndex () const inline
Definition at line 79 of file Polygone.h.
  {
    return PolygonIndex_;
  };
References PolygonIndex_.
info()
const Type_info * Polygone::info () static
Definition at line 23 of file Polygone.cpp.
nb_faces()
int Polygone::nb_faces (int i = 0) const inline override virtual
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
Un Polygone a 1 type de faces: polygon_3D.
Implements Elem_geom_base.
Definition at line 153 of file Polygone.h.
{
  assert(i==0);
  switch(i)
    {
    case 0:
      return get_nb_face_elem_max();
    default :
      Cerr << "Error, a polyhedron has 1 type of faces and not " << i << finl;
      exit();
      return -1;
    }
}
References Cerr, Process::exit(), finl, and get_nb_face_elem_max().
nb_som()
int Polygone::nb_som () const inline override virtual
Renvoie le nombre de sommets d'un Polygone.
Returns
int
Signification: le nombre de sommets maximum d'un polyedre
Implements Elem_geom_base.
Definition at line 136 of file Polygone.h.
{
  return get_nb_som_elem_max();
}
References get_nb_som_elem_max().
nb_som_face()
int Polygone::nb_som_face (int i = 0) const inline override virtual
Renvoie le nombre maximum de sommets des faces
du type specifie.
Returns
int
Signification: le nombre de sommets des faces de type i
Implements Elem_geom_base.
Definition at line 181 of file Polygone.h.
{
  assert(i==0);
  return 2;
}
Referenced by get_tab_faces_sommets_locaux().
nb_type_face()
int Polygone::nb_type_face () const override virtual
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 351 of file Polygone.cpp.
{
  return 1;
}
nom_lml()
const Nom & Polygone::nom_lml () const override virtual
Renvoie le nom LML d'un polyedre = "POLYEDRE_"+nb_som_max.
Returns
Nom&
Signification: toujours egal a "PRISM6"
Contraintes: reference constante
Implements Elem_geom_base.
Definition at line 163 of file Polygone.cpp.
{
  static Nom nom;
  nom="POLYEDRE_";
  Nom n(2*get_nb_som_elem_max());
  if (dimension==3) nom="POLYGONE_";
  if (dimension==3) n=Nom(get_nb_som_elem_max());
  nom+=n;
  return nom;
}
References Objet_U::dimension, and get_nb_som_elem_max().
printOn()
Sortie & Polygone::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Poly_geom_base.
Definition at line 48 of file Polygone.cpp.
{
  s<< FacesIndex_     <<finl;
  s<< PolygonIndex_ <<finl;
  s<< nb_som_elem_max_ <<finl;
  s<< nb_face_elem_max_ <<finl;
  WARN;
  return s;
}
References FacesIndex_, finl, nb_face_elem_max_, nb_som_elem_max_, PolygonIndex_, and WARN.
readOn()
Entree & Polygone::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Poly_geom_base.
Definition at line 132 of file Polygone.cpp.
{
  s>>FacesIndex_;
  s>>PolygonIndex_;
  s>>nb_som_elem_max_;
  s>>nb_face_elem_max_;
  return s;
}
References FacesIndex_, nb_face_elem_max_, nb_som_elem_max_, and PolygonIndex_.
rebuild_index()
void Polygone::rebuild_index ()
Definition at line 57 of file Polygone.cpp.
{
  const IntTab& les_elems = ma_zone.valeur().les_elems();
  int nb_elem=les_elems.dimension_tot(0);
  ArrOfInt   PolygonIndex_OK(nb_elem+1);
  PolygonIndex_OK[0]=0;
  for (int ele=0; ele<nb_elem; ele++)
    {
      int nbf=get_nb_som_elem_max();
      while (les_elems(ele,nbf-1)<0)
        nbf--;
      PolygonIndex_OK[ele+1]= PolygonIndex_OK[ele]+nbf;
    }
  ArrOfInt FacesIndex_OK(PolygonIndex_OK[nb_elem]);
  int f=0;
  for (int ele=0; ele<nb_elem; ele++)
    {
      for (int ss=0; ss<PolygonIndex_OK[ele+1]-PolygonIndex_OK[ele]; ss++)
        FacesIndex_OK[f++]= les_elems(ele,ss);
    }
  assert(f==PolygonIndex_OK[nb_elem]);
  FacesIndex_=FacesIndex_OK;
  PolygonIndex_=PolygonIndex_OK;
}
References TRUSTTab< _TYPE_ >::dimension_tot(), FacesIndex_, get_nb_som_elem_max(), Zone::les_elems(), Elem_geom_base::ma_zone, PolygonIndex_, and Ref_Zone::valeur().
Referenced by compute_virtual_index().
reordonner()
void Polygone::reordonner () override virtual
Reordonne les sommets du Polygone.
NE FAIT RIEN: A CODER.
Reimplemented from Elem_geom_base.
Definition at line 473 of file Polygone.cpp.
{
}
self_cast() [1/2]
const Polygone & Polygone::self_cast (const Objet_U & r) static
Definition at line 23 of file Polygone.cpp.
self_cast() [2/2]
Polygone & Polygone::self_cast (Objet_U & r) static
Definition at line 23 of file Polygone.cpp.
taille_memoire()
unsigned Polygone::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 23 of file Polygone.cpp.
type_face()
Type_Face Polygone::type_face (int i = 0) const inline override virtual
Renvoie le i-ieme type de face.
Un polyedre a 2 types de face: quadrangle et triangle.
Returns
Type_Face
Signification: le type de la face i
Contraintes: i=0 (Faces::polygone_3D)
Implements Elem_geom_base.
Definition at line 223 of file Polygone.h.
{
  assert(i<=0);
  switch(i)
    {
    case 0:
      return Faces::segment_2D;
    default :
      Cerr << "Error, a polyhedron has 1 type of faces and not " << i << finl;
      exit();
      return Faces::quadrangle_3D;
    }
}
References Cerr, Process::exit(), finl, Faces::quadrangle_3D, and Faces::segment_2D.
Member Data Documentation
FacesIndex_
ArrOfInt Polygone::FacesIndex_ private
Definition at line 91 of file Polygone.h.
Referenced by affecte_connectivite_numero_global(), build_reduced(), getFacesIndex(), Polygone(), printOn(), readOn(), and rebuild_index().
info_obj
const Type_info Polygone::info_obj static
Definition at line 43 of file Polygone.h.
nb_face_elem_max_
int Polygone::nb_face_elem_max_ private
Definition at line 93 of file Polygone.h.
Referenced by affecte_connectivite_numero_global(), build_reduced(), get_nb_face_elem_max(), get_tab_faces_sommets_locaux(), Polygone(), printOn(), and readOn().
nb_som_elem_max_
int Polygone::nb_som_elem_max_ private
Definition at line 93 of file Polygone.h.
Referenced by affecte_connectivite_numero_global(), build_reduced(), calculer_un_centre_gravite(), contient(), get_nb_som_elem_max(), Polygone(), printOn(), and readOn().
PolygonIndex_
ArrOfInt Polygone::PolygonIndex_ private
PolygoneIndex_[ele] numero premiere face de ele (sert sutrout en diff) FaceIndex_ numerotation globale a la zone ne sert qu'a med.
Definition at line 91 of file Polygone.h.
Referenced by affecte_connectivite_numero_global(), build_reduced(), get_somme_nb_faces_elem(), get_tab_faces_sommets_locaux(), getElemIndex(), getPolygonIndex(), Polygone(), printOn(), readOn(), and rebuild_index().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Polygone.h
src/Kernel/Geometrie/Polygone.cpp