TRUST: Porosites_champ Class Reference
Porosites_champ Class Reference
Porosites_champ nom_pb champ affecte le champ champ a la porosite volumique du domaine du probleme de nom_pb, puis calcule les porosites surfaciques comme moyenne harmonique.
#include <Porosites_champ.h>
Public Member Functions
Porosites_champ ()
~Porosites_champ ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &) override
Porosites_champ nom_pb champ affecte le champ champ a la porosite volumique du domaine du probleme de nom_pb, puis calcule les porosites surfacqiues comme moyenne harmonique.
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Porosites_champ & self_cast (Objet_U &)
static const Porosites_champ & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Porosites_champ nom_pb champ affecte le champ champ a la porosite volumique du domaine du probleme de nom_pb, puis calcule les porosites surfaciques comme moyenne harmonique.
Definition at line 23 of file Porosites_champ.h.
Constructor & Destructor Documentation
Porosites_champ()
Porosites_champ::Porosites_champ ()
Definition at line 42 of file Porosites_champ.cpp.
~Porosites_champ()
Porosites_champ::~Porosites_champ ()
Definition at line 42 of file Porosites_champ.cpp.
Member Function Documentation
cree_instance()
Objet_U * Porosites_champ::cree_instance () static
Definition at line 42 of file Porosites_champ.cpp.
duplique()
int Porosites_champ::duplique () const override virtual
Implements Objet_U.
Definition at line 42 of file Porosites_champ.cpp.
get_info()
const Type_info * Porosites_champ::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 42 of file Porosites_champ.cpp.
info()
const Type_info * Porosites_champ::info () static
Definition at line 42 of file Porosites_champ.cpp.
interpreter()
Entree & Porosites_champ::interpreter (Entree & is) override virtual
Porosites_champ nom_pb champ affecte le champ champ a la porosite volumique du domaine du probleme de nom_pb, puis calcule les porosites surfacqiues comme moyenne harmonique.
Reimplemented from Interprete.
Definition at line 55 of file Porosites_champ.cpp.
{
  Nom nom_pb;
  is >> nom_pb;
  if(! sub_type(Probleme_base, objet(nom_pb)))
    {
      Cerr << nom_pb << " is of type " << objet(nom_pb).que_suis_je() << finl;
      Cerr << "We waited an object of type Probleme_base" << finl;
      Process::exit();
    }
  Probleme_base& pb=ref_cast(Probleme_base, objet(nom_pb));
  Champ le_champ;
  is>>le_champ;
// On passe par la zone_VF
  Zone_VF& zvf=ref_cast(Zone_VF, pb.equation(0).zone_dis().valeur());
  DoubleVect& porosite_elem = zvf.porosite_elem();
  DoubleVect& porosite_face_r = zvf.porosite_face();
  const IntTab& face_voisins = zvf.face_voisins();
  int nb_elem_tot = zvf.zone().nb_elem_tot();
// on discretise des champs equivalents pour pouvoir faire affecter
// puis on recopie les valeurs
  Champ_Don porosite_elem_p;
  pb.discretisation().discretiser_champ("CHAMP_ELEM", pb.equation(0).zone_dis(), "pp", "1",1,0., porosite_elem_p);
  porosite_elem_p.valeur().valeurs()=1;
  porosite_elem_p.valeur().affecter(le_champ);
  for (int elem=0; elem<nb_elem_tot; elem++)
    porosite_elem(elem)=porosite_elem_p.valeurs()(elem);
// calcul de la porosite surfacique comme la moyenne harmonique
// cf D.J pour justification
  Champ_Don porosite_face_p;
  pb.discretisation().discretiser_champ("VITESSE", pb.equation(0).zone_dis(), "pp", "1",1,0., porosite_face_p);
  DoubleTab& porosite_face=porosite_face_p.valeurs();
  int nb_face_tot = zvf.nb_faces_tot();
  if (porosite_face_r.size()==porosite_face.size())
    {
      for (int face=0; face<nb_face_tot; face++)
        {
          int elem1 = face_voisins(face,1);
          int elem2 = face_voisins(face,0);
          if ((elem1 != -1) && (elem2 != -1))
            {
              porosite_face(face)=2./(1./porosite_elem(elem1)+1./porosite_elem(elem2));
            }
          else if (elem1!=-1)
            porosite_face(face) =  porosite_elem(elem1) ;
          else
            porosite_face(face) =  porosite_elem(elem2) ;
        }
      porosite_face.echange_espace_virtuel();
      for (int face=0; face<nb_face_tot; face++)
        porosite_face_r(face) = porosite_face(face);
    }
  return is;
}
References Champ_base::affecter(), Cerr, Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Probleme_base::equation(), Process::exit(), Zone_VF::face_voisins(), finl, Zone::nb_elem_tot(), Zone_VF::nb_faces_tot(), Interprete::objet(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Objet_U::que_suis_je(), ref_cast, TRUSTVect< _TYPE_ >::size(), sub_type, Deriv_Champ_Don_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_Don::valeurs(), Champ_Don_base::valeurs(), Zone_dis_base::zone(), and Equation_base::zone_dis().
printOn()
Sortie & Porosites_champ::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 44 of file Porosites_champ.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Porosites_champ::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 49 of file Porosites_champ.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Porosites_champ & Porosites_champ::self_cast (const Objet_U & r) static
Definition at line 42 of file Porosites_champ.cpp.
self_cast() [2/2]
Porosites_champ & Porosites_champ::self_cast (Objet_U & r) static
Definition at line 42 of file Porosites_champ.cpp.
taille_memoire()
unsigned Porosites_champ::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 42 of file Porosites_champ.cpp.
Member Data Documentation
info_obj
const Type_info Porosites_champ::info_obj static
Definition at line 25 of file Porosites_champ.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Porosites_champ.h
src/Kernel/Framework/Porosites_champ.cpp