TRUST: Domaine_bord Class Reference
Domaine_bord Class Reference
Cette classe est un domaine dont les sommets et les elements sont extraits d'un
bord d'un domaine source.
On construit ce domaine par la methode construire_domaine_bord()
#include <Domaine_bord.h>
Public Member Functions
Domaine_bord ()
~Domaine_bord ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void construire_domaine_bord (const Domaine &source, const Nom &nom_bord)
construit le domaine en appelant extraire_domaine_bord()
virtual const Domaine & get_domaine_source () const
renvoie une reference au domaine source
virtual const Nom & get_nom_bord_source () const
renvoie le nom du bord source
virtual const ArrOfInt & get_renum_som () const
renvoie renum_som (pour chaque sommet du domaine_bord, indice
du meme sommet dans le domaine)
Public Member Functions inherited from Domaine
~Domaine ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Domaine ()
Constructeur par defaut d'un objet Domaine.
Ne fait rien sauf fixer la valeur d'epsilon
a Objet_U::precision_geom
Si 2 points d'un domaine sont separes d'une distance
inferieure ou egale a epsilon ils sont consideres egaux.
const Nom & le_nom () const override
Renvoie le nom du domaine.
void nommer (const Nom &) override
Donne un nom au domaine.
int nb_zones () const
Renvoie le nombre de zone du domaine.
const Zone & zone (int) const
Renvoie la i-ieme zone du domaine.
(version const)
Zone & zone (int)
Renvoie la i-ieme zone du domaine.
const Zone & zone (const Nom &) const
Renvoie la Zone dont le nom est indique en parametre.
(version const)
Zone & zone (const Nom &)
Renvoie la Zone dont le nom est indique en parametre.
int nb_ss_zones () const
Renvoie le nombre de sous-zone.
const Sous_Zone & ss_zone (int) const
Renvoie la i-ieme sous-zone.
(version const)
Sous_Zone & ss_zone (int)
Renvoie la i-ieme sous-zone.
const Sous_Zone & ss_zone (const Nom &) const
Renvoie la sous-zone dont le nom est indique en parametre.
(version const)
Sous_Zone & ss_zone (const Nom &)
Renvoie la sous-zone dont le nom est indique en parametre.
double coord (int, int) const
Renvoie la j-ieme coordonnee du i-ieme noeud.
double & coord (int, int)
Renvoie une reference sur la j-ieme coordonnee
du i-ieme noeud. (ce qui permet de modifier sa valeur)
const DoubleTab & coord_sommets () const
Renvoie le tableau des coordonnees des noeuds (sommets).
(acces en lecture)
virtual int nb_som () const
Renvoie le nombre de sommets.
virtual int nb_som_tot () const
Renvoie le nombre total de sommets.
void add (const Sous_Zone &)
Ajoute une Sous_Zone au domaine.
int associer_ (Objet_U &) override
Association d'une Sous_Zone au domaine.
L'interface permet de passer n'importe quel
Objet_U mais ne gere (dynamiquement) que
l'association d'un objet derivant Sous_Zone.
DoubleTab & les_sommets ()
Renvoie le nombre total de sommets.
const DoubleTab & les_sommets () const
Renvoie le tableau des sommets du domaine.
DoubleTab getBoundingBox () const
Zone & add (Zone &)
Ajoute une Zone au domaine.
void ajouter (const DoubleTab &, IntVect &)
Ajoute des noeuds au domaine avec elimination des noeuds double
au retour nums contient les nouveaux numeros des noeuds de soms
apres elimination des doublons.
void ajouter (const DoubleTab &)
Ajoute des noeuds (ou sommets) au domaine<br>(sans verifier les doublons)
void comprimer ()
Rassemble les Zones de meme type.
void fixer_epsilon (double)
Fixe epsilon,
Si 2 points d'un domaine sont separes d'une distance
inferieure ou egale a epsilon ils sont consideres egaux.
double epsilon () const
Renvoie epsilon.
Si 2 points d'un domaine sont separes d'une distance
inferieure ou egale a epsilon ils sont consideres egaux.
void reordonner ()
Reordonne les mailles du domaine suivant les
conventions de Trio-U.
int numero_sommet (int i) const
const Zones & zones () const
Zones & zones ()
const List_Ref_Sous_Zone & ss_zones () const
int deformable () const
int & deformable ()
int get_renum_som_perio (int) const
void construire_renum_som_perio (const Conds_lim &, const Zone_dis &)
virtual void initialiser (double temps, Domaine_dis &, Probleme_base &)
virtual void set_dt (double &dt_)
virtual void mettre_a_jour (double temps, Domaine_dis &, Probleme_base &)
void set_fichier_lu (Nom &nom)
const Nom & get_fichier_lu () const
virtual void creer_tableau_sommets (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
Cree un tableau ayant une "ligne" par sommet du maillage.
Voir MD_Vector_tools::creer_tableau_distribue()
virtual void creer_tableau_elements (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
Cree un tableau ayant une "ligne" par element du maillage.
Pour l'instant, erreur s'il y a plus d'une zone dans le domaine.
Voir MD_Vector_tools::creer_tableau_distribue()
virtual const MD_Vector & md_vector_sommets () const
void set_renum_som_perio (IntTab &renum)
void creer_mes_domaines_frontieres (const Zone_VF &zone_vf)
void imprimer () const
const List_Ref_Domaine & domaines_frontieres () const
void buildUFacesMesh (const Zone_dis_base &zone_dis_base) const
bool Axi1d () const
bool Axi1d ()
void read_vertices (Entree &s)
only read vertices from the stream s
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Domaine_bord & self_cast (Objet_U &)
static const Domaine_bord & self_cast (const Objet_U &)
static void extraire_domaine_bord (const Domaine &src, const Nom &nom_bord, Domaine &dest, ArrOfInt &renum_som)
remplit le domaine "dest" avec les sommets et les faces du bord "nom_bord"
du domaine "src". Les sommets du domaine dest sont uniquement les sommets qui sont sur
une face du bord. Le tableau renum_som est dimensionne a dest.nb_som() et rempli comme
suit: renum_som[i] est l'indice dans le domaine "src" du sommet i du domaine "dest".
Static Public Member Functions inherited from Domaine
static Objet_U * cree_instance ()
static const Type_info * info ()
static Domaine & self_cast (Objet_U &)
static const Domaine & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Domaine
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
pour l'instant exit()
Entree & readOn (Entree &) override
pour l'instant exit()
Sortie & printOn (Sortie &x) const override
Ecrit le domaine sur un flot de sortie.
On ecrit le nom, les sommets, les zones
et les sous-zones.
Entree & readOn (Entree &) override
Lit les specifications d'un domaine
a partir d'un flot d'entree. Associe les zones
lues au domaine.
Format:
nom_domaine
bloc de lecture des Sommets
bloc de lecture des Zones
bloc de lecture des Sous_Zones
Attention: en parallele, chaque processeur s'attend a lire une strucutre domaine
avec des infos de joint, mais il y a des communications globales.
Pour lire un domaine sur un seul processeur, il faut mettre le processeur dans
un groupe seul.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Domaine domaine_source_
Nom bord_source_
ArrOfInt renum_som_
Protected Attributes inherited from Domaine
List_Ref_Domaine domaines_frontieres_
Nom nom_
DoubleTab sommets
List_Ref_Sous_Zone les_ss_zones
Zones les_zones
ArrOfInt renum_som_perio
double epsilon_
int deformable_
Nom fichier_lu_
int axi1d
Detailed Description
Cette classe est un domaine dont les sommets et les elements sont extraits d'un
bord d'un domaine source.
On construit ce domaine par la methode construire_domaine_bord()
Definition at line 22 of file Domaine_bord.h.
Constructor & Destructor Documentation
Domaine_bord()
Domaine_bord::Domaine_bord ()
Definition at line 18 of file Domaine_bord.cpp.
~Domaine_bord()
Domaine_bord::~Domaine_bord ()
Definition at line 18 of file Domaine_bord.cpp.
Member Function Documentation
construire_domaine_bord()
void Domaine_bord::construire_domaine_bord (const Domaine & source, const Nom & nom_bord) virtual
construit le domaine en appelant extraire_domaine_bord()
Definition at line 36 of file Domaine_bord.cpp.
{
  domaine_source_ = source;
  bord_source_ = nom_bord;
  extraire_domaine_bord(source, nom_bord, *this, renum_som_);
}
References bord_source_, domaine_source_, extraire_domaine_bord(), and renum_som_.
Referenced by Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio().
cree_instance()
Objet_U * Domaine_bord::cree_instance () static
Definition at line 18 of file Domaine_bord.cpp.
duplique()
int Domaine_bord::duplique () const override virtual
Reimplemented from Domaine.
Definition at line 18 of file Domaine_bord.cpp.
extraire_domaine_bord()
void Domaine_bord::extraire_domaine_bord (const Domaine & src, const Nom & nom_bord, Domaine & dest, ArrOfInt & renum_som) static
remplit le domaine "dest" avec les sommets et les faces du bord "nom_bord"
du domaine "src". Les sommets du domaine dest sont uniquement les sommets qui sont sur
une face du bord. Le tableau renum_som est dimensionne a dest.nb_som() et rempli comme
suit: renum_som[i] est l'indice dans le domaine "src" du sommet i du domaine "dest".
Definition at line 102 of file Domaine_bord.cpp.
{
  if (Process::nproc() > 1)
    {
      Cerr << "extraire_domaine_bord in parallel: the domain created will not have a distributed structure\n"
           << " (this will be done one day... ask to B.Mathieu)" << finl;
    }
  const Zone& zone_src = src.zone(0);
// Le domaine destination doit etre vide:
  assert(dest.nb_zones() == 0);
// Initialisation du domaine et d'une zone:
// On choisit un nom pour le domaine
  dest.nommer(src.le_nom() + Nom("_") + nom_bord);
// On cree une zone
  Zone z;
  dest.add(z);
  Zone& zone_dest = dest.zone(0);
  zone_dest.associer_domaine(dest);
// Type des elements de la zone:
  Motcle type_elem;
  type_face_to_type_elem(zone_src.type_elem().valeur(), zone_src.type_elem().valeur().type_face(), type_elem);
  zone_dest.type_elem().typer(type_elem);
  zone_dest.type_elem().valeur().associer_zone(zone_dest);
  const Frontiere& front = zone_src.frontiere(nom_bord);
  const int nb_faces = front.faces().nb_faces();
  const int nb_som_face = front.faces().nb_som_faces();
  const IntTab& faces_src = front.faces().les_sommets();
  IntTab& elem_dest = zone_dest.les_elems();
  elem_dest.resize(nb_faces, nb_som_face);
  renum_som.reset();
  renum_som.set_smart_resize(1);
// renum_inverse: pour chaque sommet du domaine source, son indice dans le domaine destination:
  ArrOfInt renum_inverse(src.nb_som());
  renum_inverse= -1;
  int nb_som_dest = 0;
  int i, j;
  for (i = 0; i < nb_faces; i++)
    {
      for (j = 0; j < nb_som_face; j++)
        {
          const int som = faces_src(i, j);
// Si le sommet n'a pas encore ete rencontre, lui donner un indice dans le domaine dest:
          if (renum_inverse[som] < 0)
            {
              renum_som.append_array(som);
              renum_inverse[som] = nb_som_dest++;
            }
          elem_dest(i, j) = renum_inverse[som];
        }
    }
// Copie des sommets utilises dans le domaine destination
  DoubleTab& som_dest = dest.les_sommets();
  const DoubleTab& som_src = src.les_sommets();
  const int dim = som_src.dimension(1);
  som_dest.resize(nb_som_dest, dim);
  for (i = 0; i < nb_som_dest; i++)
    {
      const int som = renum_som[i];
      for (j = 0; j < dim; j++)
        som_dest(i, j) = som_src(som, j);
    }
// A faire si besoin: initialiser le joint des sommets pour avoir les items communs,
// et autres si necessaire.
}
References Domaine::add(), TRUSTArray< _TYPE_ >::append_array(), Zone::associer_domaine(), Elem_geom_base::associer_zone(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Frontiere::faces(), finl, Zone::frontiere(), Domaine::le_nom(), Zone::les_elems(), Domaine::les_sommets(), Faces::les_sommets(), Faces::nb_faces(), Domaine::nb_som(), Faces::nb_som_faces(), Domaine::nb_zones(), Domaine::nommer(), Process::nproc(), TRUSTArray< _TYPE_ >::reset(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), Zone::type_elem(), type_elem(), Elem_geom_base::type_face(), type_face_to_type_elem(), Deriv_::typer(), Deriv_Elem_geom_base::valeur(), and Domaine::zone().
Referenced by construire_domaine_bord().
get_domaine_source()
const Domaine & Domaine_bord::get_domaine_source () const virtual
renvoie une reference au domaine source
Definition at line 44 of file Domaine_bord.cpp.
{
  return domaine_source_;
}
References domaine_source_.
get_info()
const Type_info * Domaine_bord::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Domaine.
Definition at line 18 of file Domaine_bord.cpp.
get_nom_bord_source()
const Nom & Domaine_bord::get_nom_bord_source () const virtual
renvoie le nom du bord source
Definition at line 50 of file Domaine_bord.cpp.
{
  return bord_source_;
}
References bord_source_.
get_renum_som()
const ArrOfInt & Domaine_bord::get_renum_som () const virtual
renvoie renum_som (pour chaque sommet du domaine_bord, indice
du meme sommet dans le domaine)
Definition at line 57 of file Domaine_bord.cpp.
{
  return renum_som_;
}
References renum_som_.
Referenced by Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio().
info()
const Type_info * Domaine_bord::info () static
Definition at line 18 of file Domaine_bord.cpp.
printOn()
Sortie & Domaine_bord::printOn (Sortie & x) const override protected virtual
pour l'instant exit()
Reimplemented from Domaine.
Definition at line 28 of file Domaine_bord.cpp.
{
  exit();
  return os;
}
References Process::exit().
readOn()
Entree & Domaine_bord::readOn (Entree & is) override protected virtual
pour l'instant exit()
Reimplemented from Domaine.
Definition at line 21 of file Domaine_bord.cpp.
{
  exit();
  return is;
}
References Process::exit().
self_cast() [1/2]
const Domaine_bord & Domaine_bord::self_cast (const Objet_U & r) static
Definition at line 18 of file Domaine_bord.cpp.
self_cast() [2/2]
Domaine_bord & Domaine_bord::self_cast (Objet_U & r) static
Definition at line 18 of file Domaine_bord.cpp.
taille_memoire()
unsigned Domaine_bord::taille_memoire () const override virtual
Reimplemented from Domaine.
Definition at line 18 of file Domaine_bord.cpp.
Member Data Documentation
bord_source_
Nom Domaine_bord::bord_source_ protected
Definition at line 39 of file Domaine_bord.h.
Referenced by construire_domaine_bord(), and get_nom_bord_source().
domaine_source_
Ref_Domaine Domaine_bord::domaine_source_ protected
Definition at line 37 of file Domaine_bord.h.
Referenced by construire_domaine_bord(), and get_domaine_source().
info_obj
const Type_info Domaine_bord::info_obj static
Definition at line 24 of file Domaine_bord.h.
renum_som_
ArrOfInt Domaine_bord::renum_som_ protected
Definition at line 41 of file Domaine_bord.h.
Referenced by construire_domaine_bord(), and get_renum_som().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Domaine_bord.h
src/Kernel/Geometrie/Domaine_bord.cpp