TRUST: Champ_Fonc Class Reference
Champ_Fonc Class Reference
classe Champ_Fonc
Classe generique de la hierarchie des champs fontions du temps,
un objet Champ_Fonc peut referencer n'importe quel objet derivant de
Champ_Fonc_base.
La plupart des methodes appellent les methodes de l'objet Champ_Fonc
sous-jacent via la methode valeur() declaree grace a la macro
#include <Champ_Fonc.h>
Public Member Functions
Champ_Fonc ()
~Champ_Fonc ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_Fonc (const Champ_Fonc &)=default
Champ_Fonc & operator= (const Champ_Fonc_base &)
Operateur d'affectation d'un Champ_Fonc_base dans
un Champ_Fonc.
Champ_Fonc & operator= (const Champ_Fonc &)
Operateur d'affectation d'un Champ_Fonc_base dans
un Champ_Fonc.
void fixer_nb_valeurs_nodales (int)
Appel a l'objet sous-jacent
Fixe le nombre de degres de liberte par composante.
int nb_valeurs_nodales () const
Appel a l'objet sous-jacent
Renvoie le nombre de degres de liberte par composante.
DoubleTab & valeurs () override
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs du champ<br>(version const)
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
double temps () const
Appel a l'objet sous-jacent
Renvoie le temps courant du champ.
double changer_temps (const double t)
Appel a l'objet sous-jacent
Change le temps courant du champ, et le renvoie.
void mettre_a_jour (double un_temps)
Appel a l'objet sous-jacent
Effectue une mise a jour en temps.
int initialiser (const double un_temps)
Appel a l'objet sous-jacent
Initilialise le champ (si il y lieu)
void associer_zone_dis_base (const Zone_dis_base &)
Appel a l'objet sous-jacent
Associe une zone discretisee au champ.
const Zone_dis_base & zone_dis_base () const
Appel a l'objet sous-jacent
Renvoe la zone discretisee associee.
int reprendre (Entree &) override
Appel a l'objet sous-jacent
Postraite au format lml.
int sauvegarder (Sortie &) const override
Appel a l'objet sous-jacent
Effectue une sauvegarde sur un flot de sortie.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &les_valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &les_valeurs) const
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Deriv_Champ_Fonc_base
~Deriv_Champ_Fonc_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Champ_Fonc_base ()
Deriv_Champ_Fonc_base (const Deriv_Champ_Fonc_base &)
const Champ_Fonc_base & valeur () const
Champ_Fonc_base & valeur ()
const Champ_Fonc_base * operator-> () const
Champ_Fonc_base * operator-> ()
const Deriv_Champ_Fonc_base & operator= (const Champ_Fonc_base &)
const Deriv_Champ_Fonc_base & operator= (const Deriv_Champ_Fonc_base &)
operator const Champ_Fonc_base & () const
operator Champ_Fonc_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Fonc & self_cast (Objet_U &)
static const Champ_Fonc & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Champ_Fonc_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Champ_Fonc_base & self_cast (Objet_U &)
static const Deriv_Champ_Fonc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Champ_Fonc_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture d'un Champ_Fonc sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Champ_Fonc sur un flot d'entree.
Protected Member Functions inherited from Deriv_Champ_Fonc_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
classe Champ_Fonc
Classe generique de la hierarchie des champs fontions du temps,
un objet Champ_Fonc peut referencer n'importe quel objet derivant de
Champ_Fonc_base.
La plupart des methodes appellent les methodes de l'objet Champ_Fonc
sous-jacent via la methode valeur() declaree grace a la macro
Definition at line 35 of file Champ_Fonc.h.
Constructor & Destructor Documentation
Champ_Fonc() [1/2]
Champ_Fonc::Champ_Fonc ()
Definition at line 19 of file Champ_Fonc.cpp.
~Champ_Fonc()
Champ_Fonc::~Champ_Fonc ()
Definition at line 19 of file Champ_Fonc.cpp.
Champ_Fonc() [2/2]
Champ_Fonc::Champ_Fonc (const Champ_Fonc &) default
Member Function Documentation
associer_zone_dis_base()
void Champ_Fonc::associer_zone_dis_base (const Zone_dis_base & zone_dis) inline
Appel a l'objet sous-jacent
Associe une zone discretisee au champ.
Definition at line 205 of file Champ_Fonc.h.
{
  valeur().associer_zone_dis_base(zone_dis);
}
References Champ_base::associer_zone_dis_base(), and Deriv_Champ_Fonc_base::valeur().
Referenced by Op_Correlation::associer(), Op_Ecart_type::associer(), Op_Moyenne::associer(), Champ_Fonc_Tabule::associer_zone_dis_base(), Op_Correlation::completer(), Op_Ecart_type::completer(), Op_Moyenne::completer(), and Discr_inst::discretiser_champ_fonc_don().
changer_temps()
double Champ_Fonc::changer_temps (const double t) inline
Appel a l'objet sous-jacent
Change le temps courant du champ, et le renvoie.
Returns
double
Signification: le nouveau temps courant du champ
Contraintes:
Definition at line 185 of file Champ_Fonc.h.
{
  return valeur().changer_temps(t);
}
References Champ_base::changer_temps(), and Deriv_Champ_Fonc_base::valeur().
Referenced by Op_Correlation::completer(), Op_Ecart_type::completer(), Op_Moyenne::completer(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Marqueur_Lagrange_base::mettre_a_jour(), Integrale_tps_Champ::mettre_a_jour(), Integrale_tps_produit_champs::mettre_a_jour(), Milieu_base::update_rho_cp(), and Fluide_Dilatable_base::update_rho_cp().
cree_instance()
Objet_U * Champ_Fonc::cree_instance () static
Definition at line 19 of file Champ_Fonc.cpp.
duplique()
int Champ_Fonc::duplique () const override virtual
Reimplemented from Deriv_Champ_Fonc_base.
Reimplemented in Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 19 of file Champ_Fonc.cpp.
fixer_nb_valeurs_nodales()
void Champ_Fonc::fixer_nb_valeurs_nodales (int n) inline
Appel a l'objet sous-jacent
Fixe le nombre de degres de liberte par composante.
Definition at line 84 of file Champ_Fonc.h.
{
  valeur().fixer_nb_valeurs_nodales(n);
}
References Champ_Fonc_base::fixer_nb_valeurs_nodales(), and Deriv_Champ_Fonc_base::valeur().
Referenced by Op_Correlation::completer(), and Discr_inst::discretiser_champ_fonc_don().
get_info()
const Type_info * Champ_Fonc::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Champ_Fonc_base.
Reimplemented in Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 19 of file Champ_Fonc.cpp.
info()
const Type_info * Champ_Fonc::info () static
Definition at line 19 of file Champ_Fonc.cpp.
initialiser()
int Champ_Fonc::initialiser (const double un_temps) inline
Appel a l'objet sous-jacent
Initilialise le champ (si il y lieu)
Definition at line 244 of file Champ_Fonc.h.
{
  return valeur().initialiser(un_temps);
}
References Champ_Don_base::initialiser(), and Deriv_Champ_Fonc_base::valeur().
Referenced by Champ_Fonc_Tabule::initialiser().
mettre_a_jour()
void Champ_Fonc::mettre_a_jour (double un_temps) inline
Appel a l'objet sous-jacent
Effectue une mise a jour en temps.
Definition at line 236 of file Champ_Fonc.h.
{
  valeur().mettre_a_jour(un_temps);
}
References Champ_Fonc_base::mettre_a_jour(), and Deriv_Champ_Fonc_base::valeur().
Referenced by Turbulence_paroi_base::get_champ(), Terme_Source_Acceleration::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Milieu_composite::mettre_a_jour(), and Champ_Fonc_Tabule::mettre_a_jour().
nb_valeurs_nodales()
int Champ_Fonc::nb_valeurs_nodales () const inline
Appel a l'objet sous-jacent
Renvoie le nombre de degres de liberte par composante.
Returns
int
Signification: le nombre de degres de liberte par composante
Contraintes:
Definition at line 104 of file Champ_Fonc.h.
{
  return valeur().nb_valeurs_nodales();
}
References Champ_Don_base::nb_valeurs_nodales(), and Deriv_Champ_Fonc_base::valeur().
nommer()
void Champ_Fonc::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
Reimplemented from Objet_U.
Definition at line 63 of file Champ_Fonc.h.
  {
    valeur().nommer(nom);
  };
References Field_base::nommer(), and Deriv_Champ_Fonc_base::valeur().
Referenced by Op_Correlation::completer(), Op_Ecart_type::completer(), and Op_Moyenne::completer().
operator const DoubleTab &()
Champ_Fonc::operator const DoubleTab & () const inline delete
operator DoubleTab &()
Champ_Fonc::operator DoubleTab & () inline delete
operator=() [1/2]
Champ_Fonc & Champ_Fonc::operator= (const Champ_Fonc & ch_fonc) inline
Operateur d'affectation d'un Champ_Fonc_base dans
un Champ_Fonc.
Returns
Champ_Fonc&
Signification: le resultat de l'affectation (*this)
Contraintes:
Definition at line 285 of file Champ_Fonc.h.
{
  if (ch_fonc.non_nul()) DERIV(Champ_Fonc_base)::operator=(ch_fonc.valeur());
  return *this;
}
References DERIV, O_U_Ptr::non_nul(), operator=(), and Deriv_Champ_Fonc_base::valeur().
operator=() [2/2]
Champ_Fonc & Champ_Fonc::operator= (const Champ_Fonc_base & ch_fonc_base) inline
Operateur d'affectation d'un Champ_Fonc_base dans
un Champ_Fonc.
Returns
Champ_Fonc&
Signification: le resultat de l'affectation (*this)
Contraintes:
Definition at line 264 of file Champ_Fonc.h.
{
  DERIV(Champ_Fonc_base)::operator=(ch_fonc_base);
  return *this;
}
References DERIV, and operator=().
Referenced by operator=().
printOn()
Sortie & Champ_Fonc::printOn (Sortie & s) const override protected virtual
Ecriture d'un Champ_Fonc sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Champ_Fonc_base.
Reimplemented in Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 57 of file Champ_Fonc.cpp.
{
  return DERIV(Champ_Fonc_base)::printOn(s);
}
References DERIV, and printOn().
Referenced by printOn().
readOn()
Entree & Champ_Fonc::readOn (Entree & s) override protected virtual
Lecture d'un Champ_Fonc sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Champ_Fonc_base.
Reimplemented in Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 37 of file Champ_Fonc.cpp.
{
  return DERIV(Champ_Fonc_base)::readOn(s);
}
References DERIV, and readOn().
Referenced by readOn().
reprendre()
int Champ_Fonc::reprendre (Entree & fich) inline override virtual
Appel a l'objet sous-jacent
Postraite au format lml.
Returns
int
Signification: code de retour propage
Contraintes:
Reimplemented from Objet_U.
Definition at line 311 of file Champ_Fonc.h.
{
  return valeur().reprendre(fich);
}
References Champ_Fonc_base::reprendre(), and Deriv_Champ_Fonc_base::valeur().
Referenced by Op_Correlation::reprendre(), Op_Ecart_type::reprendre(), and Op_Moyenne::reprendre().
sauvegarder()
int Champ_Fonc::sauvegarder (Sortie & fich) const inline override virtual
Appel a l'objet sous-jacent
Effectue une sauvegarde sur un flot de sortie.
Returns
int
Signification: code de retour propage
Contraintes:
Reimplemented from Objet_U.
Definition at line 331 of file Champ_Fonc.h.
{
  return valeur().sauvegarder(fich);
}
References Champ_Fonc_base::sauvegarder(), and Deriv_Champ_Fonc_base::valeur().
Referenced by Op_Correlation::sauvegarder(), Op_Ecart_type::sauvegarder(), and Op_Moyenne::sauvegarder().
self_cast() [1/2]
const Champ_Fonc & Champ_Fonc::self_cast (const Objet_U & r) static
Definition at line 19 of file Champ_Fonc.cpp.
self_cast() [2/2]
Champ_Fonc & Champ_Fonc::self_cast (Objet_U & r) static
Definition at line 19 of file Champ_Fonc.cpp.
taille_memoire()
unsigned Champ_Fonc::taille_memoire () const override virtual
Reimplemented from Deriv_Champ_Fonc_base.
Reimplemented in Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 19 of file Champ_Fonc.cpp.
temps()
double Champ_Fonc::temps () const inline
Appel a l'objet sous-jacent
Renvoie le temps courant du champ.
Returns
double
Signification: le temps courant du champ
Contraintes:
Definition at line 165 of file Champ_Fonc.h.
{
  return valeur().temps();
}
References Champ_base::temps(), and Deriv_Champ_Fonc_base::valeur().
Referenced by Equation_base::get_champ(), Champ_Generique_Correlation::temps(), Champ_Generique_Ecart_Type::temps(), Champ_Generique_Moyenne::temps(), Op_Correlation::temps(), Op_Ecart_type::temps(), and Op_Moyenne::temps().
valeur_a_elem()
DoubleVect & Champ_Fonc::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const inline
Definition at line 336 of file Champ_Fonc.h.
{
  return valeur().valeur_a_elem(position, les_valeurs, le_poly);
}
References Deriv_Champ_Fonc_base::valeur(), and Champ_base::valeur_a_elem().
valeur_a_elem_compo()
double Champ_Fonc::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline virtual
Definition at line 340 of file Champ_Fonc.h.
{
  return valeur().valeur_a_elem_compo(position, le_poly, ncomp);
}
References Deriv_Champ_Fonc_base::valeur(), and Champ_base::valeur_a_elem_compo().
Referenced by Champ_Fonc_Tabule::valeur_a_elem_compo().
valeur_aux_elems()
DoubleTab & Champ_Fonc::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const inline
Definition at line 344 of file Champ_Fonc.h.
{
  return valeur().valeur_aux_elems(positions, les_polys, les_valeurs);
}
References Deriv_Champ_Fonc_base::valeur(), and Champ_base::valeur_aux_elems().
Referenced by Champ_Fonc_Tabule::valeur_aux_elems().
valeur_aux_sommets()
DoubleTab & Champ_Fonc::valeur_aux_sommets (const Domaine & dom, DoubleTab & les_valeurs) const inline
Definition at line 348 of file Champ_Fonc.h.
{
  return valeur().valeur_aux_sommets(dom, les_valeurs);
}
References Deriv_Champ_Fonc_base::valeur(), and Champ_base::valeur_aux_sommets().
Referenced by Champ_Fonc_Tabule::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Fonc::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & les_valeurs, int compo) const inline
Definition at line 352 of file Champ_Fonc.h.
{
  return valeur().valeur_aux_sommets_compo(dom, les_valeurs, compo);
}
References Deriv_Champ_Fonc_base::valeur(), and Champ_base::valeur_aux_sommets_compo().
Referenced by Champ_Fonc_Tabule::valeur_aux_sommets_compo().
valeurs() [1/6]
const DoubleTab & Champ_Fonc::valeurs () const inline override virtual
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs du champ<br>(version const)
Returns
DoubleTab&
Signification: le tableau des valeurs du champ
Contraintes: reference constante
Implements Champ_Proto.
Definition at line 145 of file Champ_Fonc.h.
{
  return valeur().valeurs();
}
References Deriv_Champ_Fonc_base::valeur(), and Champ_Don_base::valeurs().
valeurs() [2/6]
virtual const DoubleTab & Champ_Proto::valeurs () const virtual
Implements Champ_Proto.
valeurs() [3/6]
DoubleTab & Champ_Fonc::valeurs () inline override virtual
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs du champ.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ
Contraintes:
Implements Champ_Proto.
Definition at line 124 of file Champ_Fonc.h.
{
  return valeur().valeurs();
}
References Deriv_Champ_Fonc_base::valeur(), and Champ_Don_base::valeurs().
Referenced by Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), Op_Dift_VDF_Face_Axi_base::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_standard_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VDF_base::ajouter_blocs(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Eval_Dift_VDF_const::associer_diff_turb(), Eval_Dift_VDF_Multi_inco_const::associer_diff_turb(), Eval_Dift_VDF_Multi_inco_var::associer_diff_turb(), Eval_Dift_VDF_var::associer_diff_turb(), Champ_front_contact_VEF::calcul_grads_locaux(), Op_Dift_VEF_P1NCP1B_Face::calculer_dt_stab(), Op_Dift_VEF_Face_Q1::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi(), Turbulence_paroi_base::calculer_hyd(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Op_Dift_VEF_Face::calculer_pour_post(), Op_Correlation::calculer_valeurs(), Navier_Stokes_std::completer(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), Turbulence_paroi_base::get_champ(), Moyenne_volumique::get_champ(), Op_Correlation::initialiser(), Op_Ecart_type::initialiser(), Op_Moyenne::initialiser(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Mod_turb_hyd_base::lire_distance_paroi(), Aire_interfaciale::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Integrale_tps_Champ::mettre_a_jour_integrale(), Milieu_composite::mettre_a_jour_tabs(), Diametre_bulles_constant::readOn(), Milieu_base::update_rho_cp(), Fluide_Dilatable_base::update_rho_cp(), QDM_Multiphase::update_y_plus(), Op_Ecart_type::valeurs(), Champ_Generique_Ecart_Type::valeurs(), Op_Moyenne::valeurs(), Champ_Fonc_Tabule::valeurs(), Op_Correlation::valeurs_a(), Op_Correlation::valeurs_ab(), Op_Correlation::valeurs_b(), Op_Ecart_type::valeurs_carre(), Champ_Generique_Ecart_Type::valeurs_carre(), and PolyMAC_discretisation::y_plus().
valeurs() [4/6]
virtual DoubleTab & Champ_Proto::valeurs () virtual
Implements Champ_Proto.
valeurs() [5/6]
virtual DoubleTab & Champ_Proto::valeurs (double temps) inline virtual
Reimplemented from Champ_Proto.
Definition at line 50 of file Champ_Proto.h.
{ return valeurs(); }
valeurs() [6/6]
virtual const DoubleTab & Champ_Proto::valeurs (double temps) const inline virtual
Reimplemented from Champ_Proto.
Definition at line 51 of file Champ_Proto.h.
{ return valeurs(); }
zone_dis_base()
const Zone_dis_base & Champ_Fonc::zone_dis_base () const inline
Appel a l'objet sous-jacent
Renvoe la zone discretisee associee.
Returns
Zone_dis_base&
Signification: la zone discretisee associee
Contraintes: reference constante
Definition at line 225 of file Champ_Fonc.h.
{
  return valeur().zone_dis_base();
}
References Deriv_Champ_Fonc_base::valeur(), and Champ_base::zone_dis_base().
Referenced by Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Milieu_base::update_rho_cp(), and Champ_Fonc_Tabule::zone_dis_base().
Member Data Documentation
info_obj
const Type_info Champ_Fonc::info_obj static
Definition at line 37 of file Champ_Fonc.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_Fonc.h
src/Kernel/Framework/Champ_Fonc.cpp