TRUST: Orienter_Simplexes Class Reference
Orienter_Simplexes Class Reference
: class Orienter_Simplexes
<Description of class Orienter_Simplexes>
#include <Orienter_Simplexes.h>
Public Member Functions
Orienter_Simplexes ()
~Orienter_Simplexes ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Orienter_Simplexes & self_cast (Objet_U &)
static const Orienter_Simplexes & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static void orient_domain (Domaine &domaine)
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
: class Orienter_Simplexes
<Description of class Orienter_Simplexes>
Definition at line 38 of file Orienter_Simplexes.h.
Constructor & Destructor Documentation
Orienter_Simplexes::Orienter_Simplexes ()
Definition at line 28 of file Orienter_Simplexes.cpp.
Orienter_Simplexes::~Orienter_Simplexes ()
Definition at line 28 of file Orienter_Simplexes.cpp.
Member Function Documentation
Objet_U * Orienter_Simplexes::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 28 of file Orienter_Simplexes.cpp.
int Orienter_Simplexes::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 28 of file Orienter_Simplexes.cpp.
const Type_info * Orienter_Simplexes::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Orienter_Simplexes.cpp.
const Type_info * Orienter_Simplexes::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Orienter_Simplexes.cpp.
Entree & Orienter_Simplexes::interpreter_ (Entree & is) [virtual]
Implements Interprete_geometrique_base.
Definition at line 261 of file Orienter_Simplexes.cpp.
References Interprete_geometrique_base::associer_domaine(), Interprete_geometrique_base::domaine(), Scatter::init_sequential_domain(), orient_domain(), and Scatter::uninit_sequential_domain().
{
  associer_domaine(is);
  Domaine& domain = domaine();
  Scatter::uninit_sequential_domain(domain);
  orient_domain(domain);
  Scatter::init_sequential_domain(domain);
  return is;
}
void Orienter_Simplexes::orient_domain (Domaine & domaine) [static]
Definition at line 255 of file Orienter_Simplexes.cpp.
References choose_internal_diagonal(), and ensure_positive_volumes().
Referenced by interpreter_().
{
  choose_internal_diagonal(domain);
  ensure_positive_volumes(domain);
}
Sortie & Orienter_Simplexes::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 30 of file Orienter_Simplexes.cpp.
{
  Interprete_geometrique_base::printOn(os);
  return os;
}
Entree & Orienter_Simplexes::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 36 of file Orienter_Simplexes.cpp.
{
  Interprete_geometrique_base::readOn(is);
  return is;
}
Orienter_Simplexes & Orienter_Simplexes::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Orienter_Simplexes.cpp.
const Orienter_Simplexes & Orienter_Simplexes::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Orienter_Simplexes.cpp.
unsigned Orienter_Simplexes::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 28 of file Orienter_Simplexes.cpp.
Member Data Documentation
const Type_info Orienter_Simplexes::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 41 of file Orienter_Simplexes.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Orienter_Simplexes.h
src/Kernel/Geometrie/Orienter_Simplexes.cpp