TRUST: Champ_input_P0 Class Reference
Champ_input_P0 Class Reference
class Champ_input_P0
Cette classe represente un champ accessible par setInputField
defini sur le domane avec une valeur par element.
#include <Champ_input_P0.h>
Public Member Functions
Champ_input_P0 ()
~Champ_input_P0 ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void associer_zone_dis_base (const Zone_dis_base &la_zone_dis_base)
virtual const Zone_dis_base & zone_dis_base () const
virtual void mettre_a_jour (double)
Mise a jour en temps du champ.
virtual void getTemplate (TrioField &afield) const
virtual void setValue (const TrioField &afield)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_input_P0 & self_cast (Objet_U &)
static const Champ_input_P0 & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void set_nb_comp (int i)
calls fixer_nb_comp
virtual void set_name (const Nom &)
calls nommer
virtual const Nom & get_name () const
calls le_nom
Protected Attributes
Ref_Zone_dis_base zdb_
Private Attributes
int nb_elems_reels_sous_zone_
int nb_elems_reels_loc_
Detailed Description
class Champ_input_P0
Cette classe represente un champ accessible par setInputField
defini sur le domane avec une valeur par element.
Definition at line 43 of file Champ_input_P0.h.
Constructor & Destructor Documentation
Champ_input_P0::Champ_input_P0 ()
Definition at line 33 of file Champ_input_P0.cpp.
Champ_input_P0::~Champ_input_P0 ()
Definition at line 33 of file Champ_input_P0.cpp.
Member Function Documentation
void Champ_input_P0::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) [inline, virtual]
Implements Champ_Fonc_base.
Definition at line 70 of file Champ_input_P0.h.
Referenced by readOn().
{
  zdb_=la_zone_dis_base;
}
Objet_U * Champ_input_P0::cree_instance () [static]
Definition at line 33 of file Champ_input_P0.cpp.
int Champ_input_P0::duplique () const [virtual]
Implements Champ_Fonc_P0_base.
Definition at line 33 of file Champ_input_P0.cpp.
const Type_info * Champ_input_P0::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_base.
Definition at line 33 of file Champ_input_P0.cpp.
const Nom & Champ_input_P0::get_name () const [protected, virtual]
calls le_nom
Definition at line 86 of file Champ_input_P0.cpp.
References Field_base::le_nom().
{
  return le_nom();
}
void Champ_input_P0::getTemplate (TrioField & afield) const [virtual]
Implements Champ_Input_Proto.
Definition at line 95 of file Champ_input_P0.cpp.
References affecte_double_avec_doubletab(), affecte_int_avec_inttab(), IntTab::dimension(), DoubleTab::dimension(), Zone_VF::elem_faces(), Zone_VF::face_sommets(), Field_base::le_nom(), Zone::les_elems(), Champ_Input_Proto::ma_sous_zone, Champ_Input_Proto::mon_pb, Field_base::nb_comp(), Zone_dis_base::nb_elem(), Sous_Zone::nb_elem_tot(), nb_elems_reels_sous_zone_, O_U_Ptr::non_nul(), Objet_U::que_suis_je(), ref_cast, Zone::type_elem(), type_elem(), Ref_Sous_Zone::valeur(), Zone_dis_base::zone(), and zone_dis_base().
{
  afield.clear();
  afield.setName(le_nom().getChar());
  afield._time1=mon_pb->presentTime();
  afield._time2=mon_pb->futureTime();
  afield._nb_field_components=nb_comp();
  /* coordonnees */
  const DoubleTab& sommets=mon_pb->domaine().les_sommets();
  afield._nbnodes=sommets.dimension(0);
  afield._mesh_dim = afield._space_dim = sommets.dimension(1);
  affecte_double_avec_doubletab(&afield._coords,sommets);
  /* connectivites */
  const Zone_VF& zvf = ref_cast(Zone_VF, zone_dis_base());
  afield._nb_elems = ma_sous_zone.non_nul() ? nb_elems_reels_sous_zone_ : zvf.nb_elem();
  Motcle type_elem = zvf.zone().type_elem()->que_suis_je();
  if (type_elem != "POLYEDRE") //cas simple -> il suffit de copier les_elems
    {
      const IntTab& e_s = zvf.zone().les_elems();
      afield._nodes_per_elem = e_s.dimension(1);
      if (ma_sous_zone.non_nul())
        {
          const Sous_Zone& ssz=ma_sous_zone.valeur();
          afield._connectivity = new int[afield._nb_elems * afield._nodes_per_elem];
          for (int i = 0, j = 0; i < ssz.nb_elem_tot(); i++)
            if (ssz[i] < zvf.nb_elem())
              memcpy(afield._connectivity + j * e_s.dimension(1), &e_s(ssz[i], 0), e_s.dimension(1) * sizeof(int)), j++;
        }
      else affecte_int_avec_inttab(&afield._connectivity, e_s);
    }
  else //polyedres -> il faut reconstruire une connectivite de type MEDCoupling a la main
    {
      afield._nodes_per_elem = zvf.elem_faces().dimension(1) * (zvf.face_sommets().dimension(1) + 1); //un -1 apres chaque face
      int *p = afield._connectivity = new int[afield._nb_elems * afield._nodes_per_elem];
      for (int i = 0, j, k, e, f, s; i < (ma_sous_zone.non_nul() ? ma_sous_zone.valeur().nb_elem_tot() : zvf.nb_elem()); i++)
        {
          if (ma_sous_zone.non_nul() && ma_sous_zone.valeur()[i] >= zvf.nb_elem()) continue; //element non reel de la sous-zone -> on saute
          e = ma_sous_zone.non_nul() ? ma_sous_zone.valeur()[i] : i; //numero de l'element
          int *pf = p + afield._nodes_per_elem; //fin de la ligne
          /* insertion de la connectivite de chaque face, suivie d'un -1 */
          for (j = 0; j < zvf.elem_faces().dimension(1) && (f = zvf.elem_faces(e, j)) >= 0; j++, *p = -1, p++)
            for (k = 0; k < zvf.face_sommets().dimension(1) && (s = zvf.face_sommets(f, k)) >= 0; k++) *p = s, p++;
          /* des -1 jusqu'a la ligne suivante */
          for ( ; p < pf; p++) *p = -1;
        }
    }
}
const Type_info * Champ_input_P0::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_base.
Definition at line 33 of file Champ_input_P0.cpp.
virtual void Champ_input_P0::mettre_a_jour (double temps) [inline, virtual]
Mise a jour en temps du champ.
Implements Champ_Fonc_base.
Definition at line 51 of file Champ_input_P0.h.
{}
Sortie & Champ_input_P0::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_base.
Definition at line 71 of file Champ_input_P0.cpp.
{
  return os;
}
Entree & Champ_input_P0::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_base.
Definition at line 37 of file Champ_input_P0.cpp.
References associer_zone_dis_base(), Objet_U::dimension, DoubleTab::dimension_tot(), Champ_Input_Proto::initial_value_, Champ_Input_Proto::ma_sous_zone, Champ_Input_Proto::mon_pb, Field_base::nb_compo_, Sous_Zone::nb_elem_tot(), nb_elems_reels_loc_, nb_elems_reels_sous_zone_, O_U_Ptr::non_nul(), Champ_Input_Proto::read(), DoubleTab::resize(), ArrOfDouble::size_array(), Champ_Input_Proto::sous_zone_ok, Ref_Sous_Zone::valeur(), and Champ_Don_base::valeurs_.
{
// #ifdef INT_is_64_
// Cerr << "Champ_input_P0 uses medcoupling and is not supported for 64bits integer indices" << finl;
// Process::exit();
// #endif
  sous_zone_ok=true;
  read(is);
  valeurs_.resize(0, nb_compo_);
  mon_pb->domaine().zone(0).creer_tableau_elements(valeurs_);
  associer_zone_dis_base(mon_pb->domaine_dis().zone_dis(0));
  mon_pb->addInputField(*this);
  if (initial_value_.size_array()>0)
    {
      int nb_elem_tot=valeurs_.dimension_tot(0);
      for (int ele=0; ele< nb_elem_tot; ele++)
        for (int c=0; c<nb_compo_; c++)
          valeurs_(ele,c)=initial_value_(c);
    }
  if (ma_sous_zone.non_nul())
    {
      const Sous_Zone& ssz=ma_sous_zone.valeur();
      nb_elems_reels_loc_ = mon_pb->domaine().zone(0).les_elems().dimension(0);
      for (int i = nb_elems_reels_sous_zone_ = 0; i < ssz.nb_elem_tot(); i++)
        nb_elems_reels_sous_zone_ += (ssz[i] < nb_elems_reels_loc_);
    }
  return is;
}
Champ_input_P0 & Champ_input_P0::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P0_base.
Definition at line 33 of file Champ_input_P0.cpp.
const Champ_input_P0 & Champ_input_P0::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P0_base.
Definition at line 33 of file Champ_input_P0.cpp.
void Champ_input_P0::set_name (const Nom & name) [protected, virtual]
calls nommer
Implements Champ_Input_Proto.
Definition at line 81 of file Champ_input_P0.cpp.
References Field_base::nommer().
{
  nommer(name);
}
void Champ_input_P0::set_nb_comp (int i) [protected, virtual]
calls fixer_nb_comp
Implements Champ_Input_Proto.
Definition at line 76 of file Champ_input_P0.cpp.
References Field_base::fixer_nb_comp().
{
  fixer_nb_comp(i);
}
void Champ_input_P0::setValue (const TrioField & afield) [virtual]
Implements Champ_Input_Proto.
Definition at line 150 of file Champ_input_P0.cpp.
References DoubleTab::dimension(), Nom::getChar(), O_U_Ptr::le_nom(), Champ_Input_Proto::ma_sous_zone, Champ_Input_Proto::mon_pb, Field_base::nb_compo_, Sous_Zone::nb_elem_tot(), nb_elems_reels_loc_, nb_elems_reels_sous_zone_, O_U_Ptr::non_nul(), Champ_Input_Proto::setValueOnTab(), Ref_Sous_Zone::valeur(), and Champ_Don_base::valeurs_.
{
  if (ma_sous_zone.non_nul())
    {
      const Sous_Zone& ssz=ma_sous_zone.valeur();
      if (afield._nb_elems != nb_elems_reels_sous_zone_)
        throw WrongArgument(mon_pb.le_nom().getChar(),"setInputField","afield","should have the same _nb_elems as returned by getInputFieldTemplate");
      assert(valeurs_.dimension(1)==nb_compo_);
      if (afield._nb_field_components!=valeurs_.dimension(1))
        throw WrongArgument(mon_pb.le_nom().getChar(),"setInputField","afield","should have the same _nb_field_components as returned by getInputFieldTemplate");
      for (int i=0, j, k = -1; i<ssz.nb_elem_tot(); i++)
        if (ssz[i] < nb_elems_reels_loc_)
          for (j = 0, k++ ; j<nb_compo_; j++)
            valeurs_(ssz[i],j)=afield._field[k*nb_compo_+j];
    }
  else
    Champ_Input_Proto::setValueOnTab(afield,valeurs_);
}
unsigned Champ_input_P0::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 33 of file Champ_input_P0.cpp.
const Zone_dis_base & Champ_input_P0::zone_dis_base () const [inline, virtual]
Implements Champ_Fonc_base.
Definition at line 75 of file Champ_input_P0.h.
References Ref_Zone_dis_base::valeur(), and zdb_.
Referenced by getTemplate().
{
  return zdb_.valeur();
}
Member Data Documentation
const Type_info Champ_input_P0::info_obj [static]
Reimplemented from Champ_Fonc_P0_base.
Definition at line 45 of file Champ_input_P0.h.
int Champ_input_P0::nb_elems_reels_loc_ [private]
Definition at line 67 of file Champ_input_P0.h.
Referenced by readOn(), and setValue().
int Champ_input_P0::nb_elems_reels_sous_zone_ [private]
Definition at line 66 of file Champ_input_P0.h.
Referenced by getTemplate(), readOn(), and setValue().
Ref_Zone_dis_base Champ_input_P0::zdb_ [protected]
Definition at line 63 of file Champ_input_P0.h.
Referenced by zone_dis_base().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_input_P0.h
src/Kernel/Champs/Champ_input_P0.cpp