TRUST: Source_Generique_P0_Elem Class Reference
Source_Generique_P0_Elem Class Reference
class Source_Generique_VDF_Elem<br>.SECTION voir Source_Generique_base
#include <Source_Generique_P0_Elem.h>
Public Member Functions
Source_Generique_P0_Elem ()
~Source_Generique_P0_Elem ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
Nom localisation_source ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Source_Generique_P0_Elem & self_cast (Objet_U &)
static const
Source_Generique_P0_Elem & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Protected Attributes
Ref_Zone_VF la_zone
Detailed Description
class Source_Generique_VDF_Elem<br>.SECTION voir Source_Generique_base
Definition at line 33 of file Source_Generique_P0_Elem.h.
Constructor & Destructor Documentation
Source_Generique_P0_Elem::Source_Generique_P0_Elem ()
Definition at line 27 of file Source_Generique_P0_Elem.cpp.
Source_Generique_P0_Elem::~Source_Generique_P0_Elem ()
Definition at line 27 of file Source_Generique_P0_Elem.cpp.
Member Function Documentation
DoubleTab & Source_Generique_P0_Elem::ajouter (DoubleTab & resu) const [virtual]
Implements Source_Generique_base.
Definition at line 42 of file Source_Generique_P0_Elem.cpp.
References Source_Generique_base::ch_source_, DoubleVect::echange_espace_virtuel(), la_zone, and Champ_Proto::valeurs().
{
  Champ espace_stockage;
  const Champ_base& champ_calc = ch_source_->get_champ(espace_stockage);
  const DoubleTab& valeurs_calc = champ_calc.valeurs();
  int nb_elem = la_zone->nb_elem();
  const DoubleVect& vol = la_zone->volumes();
  const DoubleVect& poro_vol = la_zone->porosite_elem();
  for (int elem = 0; elem<nb_elem; elem++)
    resu(elem) += valeurs_calc(elem)*vol(elem)*poro_vol(elem);
  resu.echange_espace_virtuel();
  return resu;
}
void Source_Generique_P0_Elem::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zcl_dis) [virtual]
Implements Source_Generique_base.
Definition at line 59 of file Source_Generique_P0_Elem.cpp.
References la_zone, ref_cast, and Deriv_Zone_dis_base::valeur().
{
  la_zone = ref_cast(Zone_VF,zone_dis.valeur());
}
Objet_U * Source_Generique_P0_Elem::cree_instance () [static]
Definition at line 27 of file Source_Generique_P0_Elem.cpp.
int Source_Generique_P0_Elem::duplique () const [virtual]
Implements Source_Generique_base.
Definition at line 27 of file Source_Generique_P0_Elem.cpp.
const Type_info * Source_Generique_P0_Elem::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_Generique_base.
Definition at line 27 of file Source_Generique_P0_Elem.cpp.
const Type_info * Source_Generique_P0_Elem::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_Generique_base.
Definition at line 27 of file Source_Generique_P0_Elem.cpp.
Nom Source_Generique_P0_Elem::localisation_source () [virtual]
Implements Source_Generique_base.
Definition at line 65 of file Source_Generique_P0_Elem.cpp.
{
  return "elem";
}
Sortie & Source_Generique_P0_Elem::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_Generique_base.
Definition at line 31 of file Source_Generique_P0_Elem.cpp.
References Objet_U::que_suis_je().
{
  return os << que_suis_je() ;
}
Entree & Source_Generique_P0_Elem::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_Generique_base.
Definition at line 36 of file Source_Generique_P0_Elem.cpp.
{
  Source_Generique_base::readOn(is);
  return is;
}
Source_Generique_P0_Elem & Source_Generique_P0_Elem::self_cast (Objet_U & r) [static]
Reimplemented from Source_Generique_base.
Definition at line 27 of file Source_Generique_P0_Elem.cpp.
const Source_Generique_P0_Elem & Source_Generique_P0_Elem::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_Generique_base.
Definition at line 27 of file Source_Generique_P0_Elem.cpp.
unsigned Source_Generique_P0_Elem::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 27 of file Source_Generique_P0_Elem.cpp.
Member Data Documentation
const Type_info Source_Generique_P0_Elem::info_obj [static]
Reimplemented from Source_Generique_base.
Definition at line 36 of file Source_Generique_P0_Elem.h.
Ref_Zone_VF Source_Generique_P0_Elem::la_zone [protected]
Definition at line 46 of file Source_Generique_P0_Elem.h.
Referenced by ajouter(), and associer_zones().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Source_Generique_P0_Elem.h
src/Kernel/Framework/Source_Generique_P0_Elem.cpp