TRUST: Loi_Etat_Binaire_GP_WC Class Reference
Loi_Etat_Binaire_GP_WC Class Reference
classe Loi_Etat_Binaire_GP_WC
Cette classe represente la loi d'etat pour les melanges binaires.
Associe a un fluide dilatable, elle definit un fluide binaire weakly compressible
dont la loi d'eata est :
Pth = rho*R*T*(Y1/M1+Y2/M2)
#include <Loi_Etat_Binaire_GP_WC.h>
Public Member Functions
Loi_Etat_Binaire_GP_WC ()
~Loi_Etat_Binaire_GP_WC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void calculer_masse_volumique () override
Calcule la masse volumique.
double calculer_masse_volumique (double P, double Y1) const override
Public Member Functions inherited from Loi_Etat_Binaire_GP_base
~Loi_Etat_Binaire_GP_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_Binaire_GP_base ()
void calculer_lambda () override
Calcule la conductivite.
void calculer_mu () override
Calcule la viscosite dynamique.
void calculer_mu_wilke ()
Calcule la viscosite dynamique de mélange (depend des fraction massique)
Voir Wilke https://aip.scitation.org/doi/pdf/10.1063/1.1747673.
void calculer_alpha () override
Calcule la diffusivite.
void calculer_mu_sur_Sc () override
returns rho * D
void calculer_nu_sur_Sc () override
returns D
void calculer_Cp () override
Calcule le Cp
NE FAIT RIEN : le Cp est constant.
const Nom type_fluide () const override
Renvoie le type de fluide associe.
double inverser_Pth (double, double) override
Calcule la pression avec la temperature et la masse volumique.
double calculer_masse_volumique (double P, double Y1) const override
void calculer_masse_volumique () override=0
Recalcule la masse volumique.
Public Member Functions inherited from Loi_Etat_Melange_GP_base
Loi_Etat_Melange_GP_base ()
~Loi_Etat_Melange_GP_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_fluide (const Fluide_Dilatable_base &) override
Associe le fluide a la loi d'etat.
Public Member Functions inherited from Loi_Etat_GP_base
~Loi_Etat_GP_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_GP_base ()
const Nom type_fluide () const override
Renvoie le type de fluide associe.
void associer_fluide (const Fluide_Dilatable_base &) override
Associe le fluide a la loi d'etat.
void calculer_lambda () override
Calcule la conductivite.
void calculer_alpha () override
Calcule la diffusivite.
void remplir_T () override
Remplit le tableau de la temperature : T=temp+273.15.
void calculer_Cp () override
Calcule le Cp
NE FAIT RIEN : le Cp est constant.
void calculer_masse_volumique () override
Calcule la masse volumique.
void initialiser () override
Initialise la loi d'etat : calcul Pth.
double calculer_masse_volumique (double, double) const override
double inverser_Pth (double, double) override
Calcule la pression avec la temperature et la masse volumique.
double R () const
Public Member Functions inherited from Loi_Etat_base
~Loi_Etat_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_base ()
void assoscier_probleme (const Probleme_base &pb)
Associe le probleme a la loi d'etat.
void mettre_a_jour (double)
Met a jour la loi d'etat et le champ rho.
void calculer_nu ()
Calcule la viscosite cinematique.
Champ_Don & ch_temperature ()
const Champ_Don & ch_temperature () const
Renvoie le champ de le temperature.
virtual void associer_fluide (const Fluide_Dilatable_base &)
Associe le fluide a la loi d'etat.
virtual void preparer_calcul ()
Prepare le fluide au calcul.
virtual void abortTimeStep ()
virtual void initialiser_inco_ch ()
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
virtual void calculer_mu ()
Calcule la viscosite.
virtual void calculer_lambda ()
Calcule la conductivite.
virtual void calculer_alpha ()
Calcule la diffusivite.
virtual void calculer_mu_sur_Sc ()
Ne fait rien
Surcharge dans Loi_Etat_Melange_GP.
virtual void calculer_nu_sur_Sc ()
Ne fait rien
Surcharge dans Loi_Etat_Melange_Binaire.
virtual void calculer_masse_volumique ()
Recalcule la masse volumique.
virtual double calculer_H (double, double) const
Cas gaz parfait : ne fait rien
Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
virtual double Drho_DP (double, double) const
virtual double Drho_DT (double, double) const
virtual double De_DP (double, double) const
virtual double De_DT (double, double) const
const Champ_base & get_champ (const Motcle &nom) const override
void creer_champ (const Motcle &motlu) override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Nom type_fluide () const =0
virtual void initialiser ()=0
virtual void remplir_T ()=0
virtual void calculer_Cp ()=0
virtual double calculer_masse_volumique (double, double) const =0
virtual double inverser_Pth (double, double)=0
Champs_compris & champs_compris ()
const DoubleTab & temperature () const
const DoubleTab & rho_n () const
const DoubleTab & rho_np1 () const
double Prandt () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Loi_Etat_Binaire_GP_WC & self_cast (Objet_U &)
static const Loi_Etat_Binaire_GP_WC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_Binaire_GP_base
static const Type_info * info ()
static Loi_Etat_Binaire_GP_base & self_cast (Objet_U &)
static const Loi_Etat_Binaire_GP_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_Melange_GP_base
static const Type_info * info ()
static Loi_Etat_Melange_GP_base & self_cast (Objet_U &)
static const Loi_Etat_Melange_GP_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_GP_base
static const Type_info * info ()
static Loi_Etat_GP_base & self_cast (Objet_U &)
static const Loi_Etat_GP_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_base
static const Type_info * info ()
static Loi_Etat_base & self_cast (Objet_U &)
static const Loi_Etat_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_Binaire_GP_base
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_Melange_GP_base
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_GP_base
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Loi_Etat_Binaire_GP_base
double massmol1_
double massmol2_
double mu1_
double mu2_
double tempr_
double diff_coeff_
Protected Attributes inherited from Loi_Etat_GP_base
double Cp_
double R_
Protected Attributes inherited from Loi_Etat_base
Ref_Fluide_Dilatable_base le_fluide
Ref_Probleme_base le_prob_
Champ_Don temperature_
DoubleTab tab_rho_n
DoubleTab tab_rho_np1
double Pr_
int debug
Static Protected Attributes inherited from Loi_Etat_Melange_GP_base
static constexpr double R_GAS = 8.314472
Detailed Description
classe Loi_Etat_Binaire_GP_WC
Cette classe represente la loi d'etat pour les melanges binaires.
Associe a un fluide dilatable, elle definit un fluide binaire weakly compressible
dont la loi d'eata est :
Pth = rho*R*T*(Y1/M1+Y2/M2)
Definition at line 33 of file Loi_Etat_Binaire_GP_WC.h.
Constructor & Destructor Documentation
Loi_Etat_Binaire_GP_WC()
Loi_Etat_Binaire_GP_WC::Loi_Etat_Binaire_GP_WC ()
Definition at line 20 of file Loi_Etat_Binaire_GP_WC.cpp.
~Loi_Etat_Binaire_GP_WC()
Loi_Etat_Binaire_GP_WC::~Loi_Etat_Binaire_GP_WC ()
Definition at line 20 of file Loi_Etat_Binaire_GP_WC.cpp.
Member Function Documentation
calculer_masse_volumique() [1/2]
void Loi_Etat_Binaire_GP_WC::calculer_masse_volumique () override virtual
Calcule la masse volumique.
Implements Loi_Etat_Binaire_GP_base.
Definition at line 60 of file Loi_Etat_Binaire_GP_WC.cpp.
{
  const DoubleTab& tab_Y1 = le_fluide->inco_chaleur().valeurs();
  Fluide_Weakly_Compressible& FWC = ref_cast(Fluide_Weakly_Compressible,le_fluide.valeur());
  DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  const DoubleTab& pres = FWC.pression_th_tab();
  const int n = tab_rho.size();
  for (int som=0 ; som<n ; som++)
    {
      tab_rho_np1(som) = calculer_masse_volumique(pres(som,0),tab_Y1(som,0));
      tab_rho(som,0) = 0.5 * ( tab_rho_n(som) + tab_rho_np1(som) );
    }
  tab_rho.echange_espace_virtuel();
  tab_rho_np1.echange_espace_virtuel();
  le_fluide->calculer_rho_face(tab_rho_np1);
  Debog::verifier("Loi_Etat_Binaire_GP_WC::calculer_masse_volumique, tab_rho_np1",tab_rho_np1);
  Debog::verifier("Loi_Etat_Binaire_GP_WC::calculer_masse_volumique, tab_rho",tab_rho);
}
References calculer_masse_volumique(), Fluide_Dilatable_base::calculer_rho_face(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Fluide_Dilatable_base::inco_chaleur(), Loi_Etat_base::le_fluide, Milieu_base::masse_volumique(), Fluide_Weakly_Compressible::pression_th_tab(), ref_cast, TRUSTVect< _TYPE_ >::size(), Loi_Etat_base::tab_rho_n, Loi_Etat_base::tab_rho_np1, Ref_Fluide_Dilatable_base::valeur(), Champ::valeurs(), Champ_Inc::valeurs(), and Debog::verifier().
Referenced by calculer_masse_volumique().
calculer_masse_volumique() [2/2]
double Loi_Etat_Binaire_GP_WC::calculer_masse_volumique (double P, double Y1) const override virtual
Reimplemented from Loi_Etat_Binaire_GP_base.
Definition at line 41 of file Loi_Etat_Binaire_GP_WC.cpp.
{
  return Loi_Etat_Binaire_GP_base::calculer_masse_volumique(P,Y1);
}
References Loi_Etat_Binaire_GP_base::calculer_masse_volumique().
cree_instance()
Objet_U * Loi_Etat_Binaire_GP_WC::cree_instance () static
Definition at line 20 of file Loi_Etat_Binaire_GP_WC.cpp.
duplique()
int Loi_Etat_Binaire_GP_WC::duplique () const override virtual
Implements Objet_U.
Definition at line 20 of file Loi_Etat_Binaire_GP_WC.cpp.
get_info()
const Type_info * Loi_Etat_Binaire_GP_WC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_Binaire_GP_base.
Definition at line 20 of file Loi_Etat_Binaire_GP_WC.cpp.
info()
const Type_info * Loi_Etat_Binaire_GP_WC::info () static
Definition at line 20 of file Loi_Etat_Binaire_GP_WC.cpp.
printOn()
Sortie & Loi_Etat_Binaire_GP_WC::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Loi_Etat_Binaire_GP_base.
Definition at line 29 of file Loi_Etat_Binaire_GP_WC.cpp.
{
  os <<que_suis_je()<< finl;
  return os;
}
References finl, and Objet_U::que_suis_je().
readOn()
Entree & Loi_Etat_Binaire_GP_WC::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Loi_Etat_Binaire_GP_base.
Definition at line 35 of file Loi_Etat_Binaire_GP_WC.cpp.
{
  Cerr<<"Lecture de la loi d'etat Melange Binaire WC ... "<<finl;
  return Loi_Etat_Binaire_GP_base::readOn(is);
}
References Cerr, finl, and Loi_Etat_Binaire_GP_base::readOn().
self_cast() [1/2]
const Loi_Etat_Binaire_GP_WC & Loi_Etat_Binaire_GP_WC::self_cast (const Objet_U & r) static
Definition at line 20 of file Loi_Etat_Binaire_GP_WC.cpp.
self_cast() [2/2]
Loi_Etat_Binaire_GP_WC & Loi_Etat_Binaire_GP_WC::self_cast (Objet_U & r) static
Definition at line 20 of file Loi_Etat_Binaire_GP_WC.cpp.
taille_memoire()
unsigned Loi_Etat_Binaire_GP_WC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 20 of file Loi_Etat_Binaire_GP_WC.cpp.
Member Data Documentation
info_obj
const Type_info Loi_Etat_Binaire_GP_WC::info_obj static
Definition at line 35 of file Loi_Etat_Binaire_GP_WC.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Weakly_Compressible/Loi_Etat/Loi_Etat_Binaire_GP_WC.h
src/ThHyd/Dilatable/Weakly_Compressible/Loi_Etat/Loi_Etat_Binaire_GP_WC.cpp