TRUST: Op_Conv_EF_Stab_PolyMAC_Elem Class Reference
Op_Conv_EF_Stab_PolyMAC_Elem Class Reference
: class Op_Conv_EF_Stab_PolyMAC_Elem
<Description of class Op_Conv_EF_Stab_PolyMAC_Elem>
#include <Op_Conv_EF_Stab_PolyMAC_Elem.h>
Public Member Functions
Op_Conv_EF_Stab_PolyMAC_Elem ()
~Op_Conv_EF_Stab_PolyMAC_Elem ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void preparer_calcul () override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
double calculer_dt_stab () const override
Calcul dt_stab.
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
void check_multiphase_compatibility () const override
void creer_champ (const Motcle &motlu) override
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
Public Member Functions inherited from Op_Conv_PolyMAC_base
Op_Conv_PolyMAC_base ()
~Op_Conv_PolyMAC_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
double calculer_dt_stab () const override
Calcul dt_stab.
DoubleTab & calculer (const DoubleTab &inco, DoubleTab &resu) const override
calcule la contribution de la convection, la range dans resu
renvoie resu
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_zone_cl_dis (const Zone_Cl_dis_base &) override
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void associer_vitesse (const Champ_base &) override
Public Member Functions inherited from Operateur_Conv_base
Operateur_Conv_base ()
initialise dt_stab_conv a -123
~Operateur_Conv_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_vitesse (const Champ_base &vit)=0
double dt_stab_conv () const
void fixer_dt_stab_conv (double dt)
virtual void associer_norme_vitesse (const Champ_base &norme_vitesse)
virtual void associer_vitesse_pour_pas_de_temps (const Champ_base &vitesse)
virtual void set_incompressible (const int)
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Conv_EF_Stab_PolyMAC_Elem & self_cast (Objet_U &)
static const Op_Conv_EF_Stab_PolyMAC_Elem & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Conv_PolyMAC_base
static const Type_info * info ()
static Op_Conv_PolyMAC_base & self_cast (Objet_U &)
static const Op_Conv_PolyMAC_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Conv_base
static const Type_info * info ()
static Operateur_Conv_base & self_cast (Objet_U &)
static const Operateur_Conv_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
double alpha
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Conv_PolyMAC_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Conv_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Conv_PolyMAC_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Attributes
std::vector< Champ_Inc > cc_phases_
Motcles noms_cc_phases_
std::vector< Champ_Inc > vd_phases_
Motcles noms_vd_phases_
std::vector< Champ_Inc > x_phases_
Motcles noms_x_phases_
Protected Attributes inherited from Op_Conv_PolyMAC_base
Ref_Zone_Poly_base la_zone_poly_
Ref_Zone_Cl_PolyMAC la_zcl_poly_
Ref_Champ_base vitesse_
SFichier Flux
SFichier Flux_moment
SFichier Flux_sum
Protected Attributes inherited from Operateur_Conv_base
Ref_Champ_base la_norme_vitesse
Ref_Champ_base vitesse_pour_pas_de_temps_
double dt_stab_conv_
int incompressible_ = 1
incompressible_= 1 -> l'operateur discretise div(v x inco), incompressible_ = 0 -> il discretise v.grad(inco)
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
: class Op_Conv_EF_Stab_PolyMAC_Elem
<Description of class Op_Conv_EF_Stab_PolyMAC_Elem>
Definition at line 30 of file Op_Conv_EF_Stab_PolyMAC_Elem.h.
Constructor & Destructor Documentation
Op_Conv_EF_Stab_PolyMAC_Elem()
Op_Conv_EF_Stab_PolyMAC_Elem::Op_Conv_EF_Stab_PolyMAC_Elem ()
Definition at line 40 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
~Op_Conv_EF_Stab_PolyMAC_Elem()
Op_Conv_EF_Stab_PolyMAC_Elem::~Op_Conv_EF_Stab_PolyMAC_Elem ()
Definition at line 40 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
Member Function Documentation
ajouter_blocs()
void Op_Conv_EF_Stab_PolyMAC_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
Definition at line 154 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
{
  const Zone_Poly_base& zone = la_zone_poly_.valeur();
  const IntTab& f_e = zone.face_voisins(), &fcl = ref_cast(Champ_Elem_PolyMAC, equation().inconnue().valeur()).fcl(), &fcl_v = ref_cast(Champ_Face_PolyMAC, vitesse_.valeur()).fcl();
  const DoubleVect& fs = zone.face_surfaces(), &pf = zone.porosite_face();
  const Champ_Inc_base& cc = le_champ_inco.non_nul() ? le_champ_inco->valeur() : equation().champ_convecte();
  const std::string& nom_cc = cc.le_nom().getString();
  const DoubleTab& vit = vitesse_->valeurs(), &vcc = semi_impl.count(nom_cc) ? semi_impl.at(nom_cc) : cc.valeurs(), bcc = cc.valeur_aux_bords();
  int i, j, e, eb, f, n, m, N = vcc.line_size(), Mv = vit.line_size(), M;
  Matrice_Morse *m_vit = mats.count("vitesse") ? mats.at("vitesse") : NULL;
  std::vector<std::tuple<const DoubleTab *, Matrice_Morse *, int>> d_cc; //liste des derivees de cc a renseigner : couples (derivee de cc, matrice, nb de compos de la variable)
  if (!semi_impl.count(nom_cc))
    for (auto &i_m : mats)
      if (cc.derivees().count(i_m.first))
        d_cc.push_back(std::make_tuple(&cc.derivees().at(i_m.first), i_m.second, equation().probleme().get_champ(i_m.first.c_str()).valeurs().line_size()));
  DoubleTrav dv_flux(N), dc_flux(2, N); //derivees du flux convectif a la face par rapport a la vitesse / au champ convecte amont / aval
  /* convection aux faces internes (fcl(f, 0) == 0), de Neumann_val_ext ou de Dirichlet */
  for (f = 0; f < zone.nb_faces(); f++)
    if (!fcl(f, 0) || (fcl(f, 0) > 4 && fcl(f, 0) < 7))
      {
        for (dv_flux = 0, dc_flux = 0, i = 0; i < 2; i++)
          for (e = f_e(f, i), n = 0, m = 0; n < N; n++, m += (Mv > 1))
            {
              double v = vit(f, m) ? vit(f, m) : DBL_MIN, fac = pf(f) * fs(f) * (1. + (v * (i ? -1 : 1) > 0 ? 1. : -1) * alpha) / 2;
              dv_flux(n) += fac * (e >= 0 ? vcc(e, n) : bcc(f, n)); //f est reelle -> indice trivial dans bcc
              dc_flux(i, n) = e >= 0 ? fac * vit(f, m) : 0;
            }
// second membre
        for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
          if (e < zone.nb_elem())
            for (n = 0, m = 0; n < N; n++, m += (Mv > 1))
              secmem(e, n) -= (i ? -1 : 1) * dv_flux(n) * vit(f, m);
// derivees : vitesse
        if (m_vit && fcl_v(f, 0) < 2)
          for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
            if (e < zone.nb_elem())
              for (n = 0, m = 0; n < N; n++, m += (Mv > 1))
                (*m_vit)(N * e + n, Mv * f + m) += (i ? -1 : 1) * dv_flux(n);
// derivees : champ convecte
        for (auto &&d_m_i : d_cc)
          for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
            if (e < zone.nb_elem())
              for (j = 0; j < 2 && (eb = f_e(f, j)) >= 0; j++)
                for (n = 0, m = 0, M = std::get<2>(d_m_i); n < N; n++, m += (M > 1))
                  (*std::get<1>(d_m_i))(N * e + n, M * eb + m) += (i ? -1 : 1) * dc_flux(j, n) * (*std::get<0>(d_m_i))(eb, m);
      }
}
References alpha, Equation_base::champ_convecte(), Champ_Inc_base::derivees(), MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Operateur_base::get_champ(), Nom::getString(), Op_Conv_PolyMAC_base::la_zone_poly_, Operateur_base::le_champ_inco, Field_base::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), O_U_Ptr::non_nul(), Zone_VF::porosite_face(), ref_cast, Deriv_Champ_Inc_base::valeur(), Ref_Champ_base::valeur(), Ref_Zone_Poly_base::valeur(), valeur(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Op_Conv_PolyMAC_base::vitesse_.
calculer_dt_stab()
double Op_Conv_EF_Stab_PolyMAC_Elem::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 94 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
{
  double dt = 1e10;
  const Zone_Poly_base& zone = la_zone_poly_.valeur();
  const DoubleVect& fs = zone.face_surfaces(), &pf = zone.porosite_face(), &ve = zone.volumes(), &pe = zone.porosite_elem();
  const DoubleTab& vit = vitesse_->valeurs(),
                   *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL;
  const IntTab& e_f = zone.elem_faces(), &f_e = zone.face_voisins();
  int i, e, f, n, N = std::min(vit.line_size(), equation().inconnue().valeurs().line_size());
  DoubleTrav flux(N); //somme des flux pf * |f| * vf
  for (e = 0; e < zone.nb_elem(); e++)
    {
      for (flux = 0, i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++)
        for (n = 0; n < N; n++)
          flux(n) += pf(f) * fs(f) * std::max((e == f_e(f, 1) ? 1 : -1) * vit(f, n), 0.); //seul le flux entrant dans e compte
      for (n = 0; n < N; n++)
        if ((!alp || (*alp)(e, n) > 1e-3) && flux(n)) dt = std::min(dt, pe(e) * ve(e) / flux(n));
    }
  return Process::mp_min(dt);
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Op_Conv_PolyMAC_base::la_zone_poly_, TRUSTVect< _TYPE_ >::line_size(), Process::mp_min(), Zone_dis_base::nb_elem(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, sub_type, Ref_Zone_Poly_base::valeur(), Champ_Proto::valeurs(), Op_Conv_PolyMAC_base::vitesse_, and Zone_VF::volumes().
check_multiphase_compatibility()
void Op_Conv_EF_Stab_PolyMAC_Elem::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
Definition at line 48 of file Op_Conv_EF_Stab_PolyMAC_Elem.h.
{ }; //of course
cree_instance()
Objet_U * Op_Conv_EF_Stab_PolyMAC_Elem::cree_instance () static
Definition at line 40 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
creer_champ()
void Op_Conv_EF_Stab_PolyMAC_Elem::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Operateur_base.
Definition at line 206 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
{
  Op_Conv_PolyMAC_base::creer_champ(motlu);
  int i = noms_cc_phases_.rang(motlu), j = noms_vd_phases_.rang(motlu), k = noms_x_phases_.rang(motlu);
  if (i >= 0 && !cc_phases_[i].non_nul())
    {
      equation().discretisation().discretiser_champ("vitesse", equation().zone_dis(), noms_cc_phases_[i], "kg/m2/s",dimension, 1, 0, cc_phases_[i]);
      champs_compris_.ajoute_champ(cc_phases_[i]);
    }
  if (j >= 0 && !vd_phases_[j].non_nul())
    {
      equation().discretisation().discretiser_champ("vitesse", equation().zone_dis(), noms_vd_phases_[j], "m/s",dimension, 1, 0, vd_phases_[j]);
      champs_compris_.ajoute_champ(vd_phases_[j]);
    }
  if (k >= 0 && !x_phases_[k].non_nul())
    {
      equation().discretisation().discretiser_champ("temperature", equation().zone_dis(), noms_x_phases_[k], "m/s",1, 1, 0, x_phases_[k]);
      champs_compris_.ajoute_champ(x_phases_[k]);
    }
}
References Champs_compris::ajoute_champ(), cc_phases_, Operateur_base::champs_compris_, Operateur_base::creer_champ(), Objet_U::dimension, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), MorEqn::equation(), noms_cc_phases_, noms_vd_phases_, noms_x_phases_, Motcles::rang(), vd_phases_, and x_phases_.
dimensionner_blocs()
void Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
Definition at line 118 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
{
  const Zone_Poly_base& zone = la_zone_poly_.valeur();
  const IntTab& f_e = zone.face_voisins(), &fcl_v = ref_cast(Champ_Face_PolyMAC, vitesse_.valeur()).fcl();
  int i, j, e, eb, f, n, N = equation().inconnue().valeurs().line_size();
  const Champ_Inc_base& cc = equation().champ_convecte();
  for (auto &&i_m : mats)
    if (i_m.first == "vitesse" || (cc.derivees().count(i_m.first) && !semi_impl.count(cc.le_nom().getString())))
      {
        Matrice_Morse mat;
        IntTrav stencil(0, 2);
        stencil.set_smart_resize(1);
        int m, M = equation().probleme().get_champ(i_m.first.c_str()).valeurs().line_size();
        if (i_m.first == "vitesse") /* vitesse */
          {
            for (f = 0; f < zone.nb_faces_tot(); f++)
              if (fcl_v(f, 0) < 2)
                for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
                  if (e < zone.nb_elem())
                    for (n = 0; n < N; n++) stencil.append_line(N * e + n, M * f + n * (M > 1));
          }
        else for (f = 0; f < zone.nb_faces_tot(); f++)
            for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
              if (e < zone.nb_elem()) /* inconnues scalaires */
                for (j = 0; j < 2 && (eb = f_e(f, j)) >= 0; j++)
                  for (n = 0, m = 0; n < N; n++, m += (M > 1)) stencil.append_line(N * e + n, M * eb + m);
        tableau_trier_retirer_doublons(stencil);
        Matrix_tools::allocate_morse_matrix(equation().inconnue().valeurs().size_totale(), i_m.first == "vitesse" ? vitesse_->valeurs().size_totale() : cc.derivees().at(i_m.first).size_totale(), stencil, mat);
        i_m.second->nb_colonnes() ? *i_m.second += mat : *i_m.second = mat;
      }
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), Equation_base::champ_convecte(), Champ_Inc_base::derivees(), MorEqn::equation(), Zone_VF::face_voisins(), Probleme_base::get_champ(), Nom::getString(), Equation_base::inconnue(), Op_Conv_PolyMAC_base::la_zone_poly_, Field_base::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces_tot(), Equation_base::probleme(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTVect< _TYPE_ >::size_totale(), tableau_trier_retirer_doublons(), Ref_Champ_base::valeur(), Ref_Zone_Poly_base::valeur(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), and Op_Conv_PolyMAC_base::vitesse_.
duplique()
int Op_Conv_EF_Stab_PolyMAC_Elem::duplique () const override virtual
Implements Objet_U.
Reimplemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
Definition at line 40 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
get_info()
const Type_info * Op_Conv_EF_Stab_PolyMAC_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
Definition at line 40 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
has_interface_blocs()
int Op_Conv_EF_Stab_PolyMAC_Elem::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
Definition at line 41 of file Op_Conv_EF_Stab_PolyMAC_Elem.h.
  {
    return 1;
  };
info()
const Type_info * Op_Conv_EF_Stab_PolyMAC_Elem::info () static
Definition at line 40 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
mettre_a_jour()
void Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
Reimplemented from Operateur_base.
Definition at line 227 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
{
  Op_Conv_PolyMAC_base::mettre_a_jour(temps);
  const Zone_Poly_base& zone = la_zone_poly_.valeur();
  const IntTab& f_e = zone.face_voisins(), &e_f = zone.elem_faces();
  const Champ_Inc_base& cc = le_champ_inco.non_nul() ? le_champ_inco.valeur() : equation().champ_convecte();
  const DoubleVect& pf = zone.porosite_face(), &pe = zone.porosite_elem(), &fs = zone.face_surfaces(), &ve = zone.volumes();
  const DoubleTab& vit = vitesse_->valeurs(), &vcc = cc.valeurs(), bcc = cc.valeur_aux_bords(), &xv = zone.xv(), &xp = zone.xp();
  DoubleTab balp;
  if (vd_phases_.size()) balp = equation().inconnue().valeur().valeur_aux_bords();
  int i, e, f, d, D = dimension, n, m, N = vcc.line_size(), M = vit.line_size();
  DoubleTrav cc_f(N); //valeur du champ convecte aux faces
  /* flux aux bords */
  for (f = 0; f < zone.premiere_face_int(); f++)
    {
      for (cc_f = 0, i = 0; i < 2; i++)
        for (e = f_e(f, i), n = 0, m = 0; n < N; n++, m += (M > 1))
          cc_f(n) +=  (1. + (vit(f, m) * (i ? -1 : 1) >= 0 ? 1. : -1.) * alpha) / 2 * (e >= 0 ? vcc(e, n) : bcc(f, n));
      for (n = 0, m = 0; n < N; n++, m += (M > 1)) flux_bords_(f, n) = pf(f) * fs(f) * vit(f, m) * cc_f(n);
    }
  if (cc_phases_.size())
    for (n = 0, m = 0; n < N; n++, m += (M > 1))
      if (cc_phases_[n].non_nul()) /* mise a jour des champs de debit */
        {
          Champ_Face_PolyMAC& c_ph = ref_cast(Champ_Face_PolyMAC, cc_phases_[n].valeur());
          DoubleTab& v_ph = c_ph.valeurs();
          for (f = 0; f < zone.nb_faces(); v_ph(f) *= vit(f, m) * pf(f), f++)
            for (v_ph(f) = 0, i = 0; i < 2; i++) v_ph(f) += (1. + (vit(f, m) * (i ? -1 : 1) >= 0 ? 1. : -1.) * alpha) / 2 * ((e = f_e(f, i)) >= 0 ? vcc(e, n) : bcc(f, n));
          c_ph.changer_temps(temps);
        }
  if (vd_phases_.size())
    for (n = 0, m = 0; n < N; n++, m += (M > 1))
      if (vd_phases_[n].non_nul()) /* mise a jour des champs de vitesse debitante */
        {
          const DoubleTab& alp = equation().inconnue().valeurs();
          Champ_Face_PolyMAC& c_ph = ref_cast(Champ_Face_PolyMAC, vd_phases_[n].valeur());
          DoubleTab& v_ph = c_ph.valeurs();
          /* on remplit la partie aux faces, puis on demande au champ d'interpoler aux elements */
          for (f = 0; f < zone.nb_faces(); v_ph(f) *= vit(f, m) * pf(f), f++)
            for (v_ph(f) = 0, i = 0; i < 2; i++) v_ph(f) += (1. + (vit(f, m) * (i ? -1 : 1) >= 0 ? 1. : -1.) * alpha) / 2 * ((e = f_e(f, i)) >= 0 ? alp(e, n) : balp(f, n));
          c_ph.changer_temps(temps);
        }
  DoubleTrav G(N), v(N, D);
  double Gt;
  if (x_phases_.size())
    for (e = 0; e < zone.nb_elem(); e++) //titre : aux elements
      {
        for (v = 0, i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++)
          for (n = 0; n < N; n++)
            for (d = 0; d < D; d++)
              v(n, d) += fs(f) * pf(f) * (xv(f, d) - xp(e, d)) * (e == f_e(f, 0) ? 1 : -1) * vit(f, n) / (pe(e) * ve(e));
        for (Gt = 0, n = 0; n < N; Gt += G(n), n++) G(n) = vcc(e, n) * sqrt(zone.dot(&v(n, 0), &v(n, 0)));
        for (n = 0; n < N; n++)
          if (x_phases_[n].non_nul()) x_phases_[n]->valeurs()(e) = Gt ? G(n) / Gt : 0;
      }
  if (x_phases_.size())
    for (n = 0; n < N; n++)
      if (x_phases_[n].non_nul()) x_phases_[n]->changer_temps(temps);
}
References alpha, cc_phases_, Equation_base::champ_convecte(), Champ_Inc_base::changer_temps(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_Poly_base::dot(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Operateur_base::flux_bords_, Equation_base::inconnue(), Op_Conv_PolyMAC_base::la_zone_poly_, Operateur_base::le_champ_inco, TRUSTVect< _TYPE_ >::line_size(), Operateur_base::mettre_a_jour(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), O_U_Ptr::non_nul(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, Deriv_Champ_Inc_base::valeur(), Ref_Champ_Inc::valeur(), Ref_Zone_Poly_base::valeur(), valeur(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc::valeurs(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), vd_phases_, Op_Conv_PolyMAC_base::vitesse_, Zone_VF::volumes(), x_phases_, Zone_VF::xp(), and Zone_VF::xv().
modifier_pour_Cl()
void Op_Conv_EF_Stab_PolyMAC_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 37 of file Op_Conv_EF_Stab_PolyMAC_Elem.h.
{ };
preparer_calcul()
void Op_Conv_EF_Stab_PolyMAC_Elem::preparer_calcul (void) override virtual
Reimplemented from Operateur_base.
Definition at line 81 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
{
  Op_Conv_PolyMAC_base::preparer_calcul();
  /* au cas ou... */
  const Zone_Poly_base& zone = la_zone_poly_.valeur();
  equation().init_champ_convecte();
  flux_bords_.resize(zone.premiere_face_int(), (le_champ_inco.non_nul() ? le_champ_inco->valeurs() : equation().inconnue().valeurs()).line_size());
  if (zone.zone().nb_joints() && zone.zone().joint(0).epaisseur() < 2)
    Cerr << "Op_Conv_EF_Stab_PolyMAC_Elem : largeur de joint insuffisante (minimum 2)!" << finl, Process::exit();
}
References Cerr, Joint::epaisseur(), MorEqn::equation(), Process::exit(), finl, Operateur_base::flux_bords_, Equation_base::init_champ_convecte(), Zone::joint(), Op_Conv_PolyMAC_base::la_zone_poly_, Operateur_base::le_champ_inco, Zone::nb_joints(), O_U_Ptr::non_nul(), Zone_VF::premiere_face_int(), Operateur_base::preparer_calcul(), TRUSTTab< _TYPE_ >::resize(), Ref_Zone_Poly_base::valeur(), Champ_Inc::valeurs(), and Zone_dis_base::zone().
printOn()
Sortie & Op_Conv_EF_Stab_PolyMAC_Elem::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
Definition at line 48 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
{ return Op_Conv_PolyMAC_base::printOn(os); }
References Op_Conv_PolyMAC_base::printOn().
Referenced by Op_Conv_Amont_PolyMAC_Elem::printOn(), and Op_Conv_Centre_PolyMAC_Elem::printOn().
readOn()
Entree & Op_Conv_EF_Stab_PolyMAC_Elem::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
< XD_ADD_P double parametre ajustant la stabilisation de 0 (schema centre) a 1 (schema amont)
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
Definition at line 54 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
{
  Op_Conv_PolyMAC_base::readOn( is );
  if (que_suis_je() == "Op_Conv_EF_Stab_PolyMAC_Elem_PolyMAC") //on n'est pas dans Op_Conv_Amont/Centre
    {
      Param param(que_suis_je());
      param.ajouter("alpha", &alpha);            //!< XD_ADD_P double parametre ajustant la stabilisation de 0 (schema centre) a 1 (schema amont)
      param.lire_avec_accolades_depuis(is);
    }
  if (sub_type(Masse_Multiphase, equation())) //convection dans Masse_Multiphase -> champs de debit / titre
    {
      const Pb_Multiphase& pb = ref_cast(Pb_Multiphase, equation().probleme());
      noms_cc_phases_.dimensionner(pb.nb_phases()), cc_phases_.resize(pb.nb_phases());
      noms_vd_phases_.dimensionner(pb.nb_phases()), vd_phases_.resize(pb.nb_phases());
      noms_x_phases_.dimensionner(pb.nb_phases()),   x_phases_.resize(pb.nb_phases());
      for (int i = 0; i < pb.nb_phases(); i++)
        {
          champs_compris_.ajoute_nom_compris(noms_cc_phases_[i] = Nom("debit_") + pb.nom_phase(i));
          champs_compris_.ajoute_nom_compris(noms_vd_phases_[i] = Nom("vitesse_debitante_") + pb.nom_phase(i));
          champs_compris_.ajoute_nom_compris(noms_x_phases_[i] = Nom("titre_") + pb.nom_phase(i));
        }
    }
  return is;
}
References Champs_compris::ajoute_nom_compris(), Param::ajouter(), alpha, cc_phases_, Operateur_base::champs_compris_, vect_impl::dimensionner(), MorEqn::equation(), Param::lire_avec_accolades_depuis(), Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), noms_cc_phases_, noms_vd_phases_, noms_x_phases_, Objet_U::que_suis_je(), Op_Conv_PolyMAC_base::readOn(), ref_cast, sub_type, vd_phases_, and x_phases_.
Referenced by Op_Conv_Amont_PolyMAC_Elem::readOn(), and Op_Conv_Centre_PolyMAC_Elem::readOn().
self_cast() [1/2]
const Op_Conv_EF_Stab_PolyMAC_Elem & Op_Conv_EF_Stab_PolyMAC_Elem::self_cast (const Objet_U & r) static
Definition at line 40 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
self_cast() [2/2]
Op_Conv_EF_Stab_PolyMAC_Elem & Op_Conv_EF_Stab_PolyMAC_Elem::self_cast (Objet_U & r) static
Definition at line 40 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
taille_memoire()
unsigned Op_Conv_EF_Stab_PolyMAC_Elem::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
Definition at line 40 of file Op_Conv_EF_Stab_PolyMAC_Elem.cpp.
Member Data Documentation
alpha
double Op_Conv_EF_Stab_PolyMAC_Elem::alpha
Definition at line 54 of file Op_Conv_EF_Stab_PolyMAC_Elem.h.
Referenced by ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), mettre_a_jour(), Op_Conv_Amont_PolyMAC_Elem::Op_Conv_Amont_PolyMAC_Elem(), Op_Conv_Centre_PolyMAC_Elem::Op_Conv_Centre_PolyMAC_Elem(), and readOn().
cc_phases_
std::vector<Champ_Inc> Op_Conv_EF_Stab_PolyMAC_Elem::cc_phases_ protected
Definition at line 58 of file Op_Conv_EF_Stab_PolyMAC_Elem.h.
Referenced by creer_champ(), mettre_a_jour(), and readOn().
info_obj
const Type_info Op_Conv_EF_Stab_PolyMAC_Elem::info_obj static
Definition at line 33 of file Op_Conv_EF_Stab_PolyMAC_Elem.h.
noms_cc_phases_
Motcles Op_Conv_EF_Stab_PolyMAC_Elem::noms_cc_phases_ protected
Definition at line 59 of file Op_Conv_EF_Stab_PolyMAC_Elem.h.
Referenced by creer_champ(), and readOn().
noms_vd_phases_
Motcles Op_Conv_EF_Stab_PolyMAC_Elem::noms_vd_phases_ protected
Definition at line 61 of file Op_Conv_EF_Stab_PolyMAC_Elem.h.
Referenced by creer_champ(), and readOn().
noms_x_phases_
Motcles Op_Conv_EF_Stab_PolyMAC_Elem::noms_x_phases_ protected
Definition at line 63 of file Op_Conv_EF_Stab_PolyMAC_Elem.h.
Referenced by creer_champ(), and readOn().
vd_phases_
std::vector<Champ_Inc> Op_Conv_EF_Stab_PolyMAC_Elem::vd_phases_ protected
Definition at line 60 of file Op_Conv_EF_Stab_PolyMAC_Elem.h.
Referenced by creer_champ(), mettre_a_jour(), and readOn().
x_phases_
std::vector<Champ_Inc> Op_Conv_EF_Stab_PolyMAC_Elem::x_phases_ protected
Definition at line 62 of file Op_Conv_EF_Stab_PolyMAC_Elem.h.
Referenced by creer_champ(), mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Op_Conv_EF_Stab_PolyMAC_Elem.h
src/PolyMAC/Operateurs/Op_Conv_EF_Stab_PolyMAC_Elem.cpp