TRUST: Fluide_reel_base Class Reference
Fluide_reel_base Class Reference abstract
Classe Fluide_reel_base
Cette classe represente un fluide reel ainsi que
ses proprietes:
- viscosite cinematique, (mu)
- viscosite dynamique, (nu)
- masse volumique, (rho)
- diffusivite, (alpha)
- conductivite, (lambda)
- capacite calorifique, (Cp)
- dilatabilite thermique du constituant (beta_co)
#include <Fluide_reel_base.h>
Public Member Functions
Fluide_reel_base ()
~Fluide_reel_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretiser (const Probleme_base &pb, const Discretisation_base &dis) override
void abortTimeStep () override
bool initTimeStep (double dt) override
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps du milieu,
et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le
nouveau temps specifie, les autres sont mis a
par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
int initialiser (const double temps) override
Initialise les parametres du fluide.
void preparer_calcul () override
void set_param (Param &param) override
int check_unknown_range () const override
virtual std::map< std::string, std::array< double, 2 > > unknown_range () const
Public Member Functions inherited from Fluide_base
~Fluide_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Fluide_base ()
const Champ_Don & viscosite_cinematique () const
Renvoie la viscosite cinematique, nu.
(vesrion const)
const Champ_Don & viscosite_dynamique () const
Renvoie la viscosite dynamique, mu.
(version const)
const Champ_Don & beta_c () const
Renvoie la dilatabilite du constituant, beta_co.
(version const)
Champ_Don & viscosite_cinematique ()
Renvoie la viscosite cinematique, nu.
Champ_Don & viscosite_dynamique ()
Renvoie la viscosite dynamique, mu.
Champ_Don & beta_c ()
Renvoie la dilatabilite du constituant, beta_co.
virtual const Champ_base & energie_interne () const
virtual Champ_base & energie_interne ()
virtual const Champ_base & enthalpie () const
virtual Champ_base & enthalpie ()
int is_rayo_semi_transp () const override
int is_rayo_transp () const override
void fixer_type_rayo ()
void reset_type_rayo ()
int longueur_rayo_is_discretised ()
Champ_Don & kappa ()
Renvoie le coefficient d'absorbtion du fluide.
const Champ_Don & kappa () const
Renvoie le coefficient d'absorbtion du fluide.
Champ_Don & indice ()
Renvoie l'indice de refraction du fluide.
const Champ_Don & indice () const
Renvoie l'indice de refraction du fluide.
Champ_Don & longueur_rayo ()
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
const Champ_Don & longeur_rayo () const
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
void set_param (Param &param) override
void verifier_coherence_champs (int &err, Nom &message) override
Verifie que les champs lus l'ont ete correctement.
bool initTimeStep (double dt) override
void mettre_a_jour (double) override
Effectue une mise a jour en temps du milieu,
et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le
nouveau temps specifie, les autres sont mis a
par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
int initialiser (const double temps) override
Initialise les parametres du fluide.
void creer_champs_non_lus () override
void discretiser (const Probleme_base &pb, const Discretisation_base &dis) override
virtual void set_h0_T0 (double h0, double T0)
Public Member Functions inherited from Milieu_base
~Milieu_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Milieu_base ()
virtual void set_param (Param &param)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void preparer_calcul ()
virtual void verifier_coherence_champs (int &err, Nom &message)
virtual void creer_champs_non_lus ()
virtual void discretiser (const Probleme_base &pb, const Discretisation_base &dis)
virtual int is_rayo_semi_transp () const
virtual int is_rayo_transp () const
virtual void mettre_a_jour (double temps)
virtual bool initTimeStep (double dt)
virtual void abortTimeStep ()
virtual int initialiser (const double temps)
virtual void associer_gravite (const Champ_Don_base &)
Associe (affecte) un champ de gravite au milieu.
virtual const Champ & masse_volumique () const
Renvoie la masse volumique du milieu.
(version const)
virtual Champ & masse_volumique ()
Renvoie la masse volumique du milieu.
virtual const Champ_Don & diffusivite () const
Renvoie la diffusivite du milieu.
(version const)
virtual Champ_Don & diffusivite ()
Renvoie la diffusivite du milieu.
virtual const Champ_Don & conductivite () const
Renvoie la conductivite du milieu.
(version const)
virtual Champ_Don & conductivite ()
Renvoie la conductivite du milieu.
virtual const Champ_Don & capacite_calorifique () const
Renvoie la capacite calorifique du milieu.
(version const)
virtual Champ_Don & capacite_calorifique ()
Renvoie la capacite calorifique du milieu.
virtual const Champ_Don & beta_t () const
Renvoie beta_t du milieu.
(version const)
virtual Champ_Don & beta_t ()
Renvoie beta_t du milieu.
virtual int a_gravite () const
Renvoie 1 si la gravite a ete initialisee.
virtual const Champ_Don_base & gravite () const
Renvoie la gravite du milieu si elle a ete associe
provoque une erreur sinon.
(version const)
virtual Champ_Don_base & gravite ()
Renvoie la gravite du milieu si elle a ete associe
provoque une erreur sinon.
int associer_ (Objet_U &) override
Associe la gravite en controlant dynamiquement le
type de l'objet a associer.
Si l'objet est du type Champ_Don ou Champ_Don_base
l'association reussit, sinon elle echoue.
virtual int est_deja_associe ()
Renvoie 0 si le milieu est deja associe a un probleme, 1 sinon.
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void update_rho_cp (double temps)
virtual void associer_equation (const Equation_base *eqn) const
virtual const Equation_base & equation (const std::string &nom_inc) const
virtual int check_unknown_range () const
void set_id_composite (const int i)
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Fluide_reel_base & self_cast (Objet_U &)
static const Fluide_reel_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Fluide_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Fluide_base & self_cast (Objet_U &)
static const Fluide_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Milieu_base
static const Type_info * info ()
static Milieu_base & self_cast (Objet_U &)
static const Milieu_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Fluide_base
static const Type_info info_obj
Static Public Attributes inherited from Milieu_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit les proprietes du fluide sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
virtual double rho_ (const double T, const double P) const =0
virtual double dP_rho_ (const double T, const double P) const =0
virtual double dT_rho_ (const double T, const double P) const =0
virtual double h_ (const double T, const double P) const =0
virtual double dP_h_ (const double T, const double P) const =0
virtual double dT_h_ (const double T, const double P) const =0
virtual double cp_ (const double T, const double P) const =0
virtual double beta_ (const double T, const double P) const =0
virtual double mu_ (const double T, const double P) const =0
virtual double lambda_ (const double T, const double P) const =0
Protected Member Functions inherited from Fluide_base
Sortie & printOn (Sortie &x) const override
Ecrit les proprietes du fluide sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
void creer_e_int () const
void creer_nu ()
Si l'objet reference par nu et du type Champ_Uniforme
type nu en "Champ_Uniforme" et le remplit
avec mu(0,0)/rho(0,0).
Sinon n efait rien.
virtual void calculer_nu ()
Protected Member Functions inherited from Milieu_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Entree & readOn (Entree &) override
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
void ecrire (Sortie &) const
Ecrit un objet milieu sur un flot de sortie.
Ecrit les caracteristiques du milieu:
- masse volumique
- conductivite
- capacite calorifique
- beta_th.
void creer_alpha ()
virtual void calculer_alpha ()
Calcul de alpha=lambda/(rho*Cp).
Suivant lambda, rho et Cp alpha peut-etre type comme
un champ uniforme ou un champ uniforme par morceau.
void creer_derivee_rho ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Static Protected Member Functions
static void calculer_masse_volumique (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
static void calculer_energie_interne (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
static void calculer_enthalpie (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Static Protected Member Functions inherited from Fluide_base
static void calculer_e_int (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Protected Attributes
double T_ref_ = -1
double P_ref_ = -1
int first_maj_ = 1
double t_init_
Protected Attributes inherited from Fluide_base
int e_int_auto_ = 0
Champ e_int
Champ h
Champ_Don mu
Champ_Don nu
Champ_Don beta_co
double h0_ = 0
double T0_ = 0
Champ_Don coeff_absorption_
Champ_Don indice_refraction_
Champ_Don longueur_rayo_
Protected Attributes inherited from Milieu_base
Champ rho
Champ_Don alpha
Champ_Don lambda
Champ_Don Cp
Champ_Don beta_th
Champ_Fonc rho_cp_elem_
Champ_Fonc rho_cp_comme_T_
Nom nom_
Ref_Champ_Don_base g
Type_rayo indic_rayo_
int deja_associe
Champs_compris champs_compris_
std::map< std::string, const Equation_base * > equation_
Additional Inherited Members
Public Attributes inherited from Milieu_base
int id_composite = -1
Protected Types inherited from Milieu_base
enum Type_rayo { NONRAYO , TRANSP , SEMITRANSP }
Detailed Description
Classe Fluide_reel_base
Cette classe represente un fluide reel ainsi que
ses proprietes:
- viscosite cinematique, (mu)
- viscosite dynamique, (nu)
- masse volumique, (rho)
- diffusivite, (alpha)
- conductivite, (lambda)
- capacite calorifique, (Cp)
- dilatabilite thermique du constituant (beta_co)
Definition at line 40 of file Fluide_reel_base.h.
Constructor & Destructor Documentation
Fluide_reel_base()
Fluide_reel_base::Fluide_reel_base ()
Definition at line 27 of file Fluide_reel_base.cpp.
~Fluide_reel_base()
Fluide_reel_base::~Fluide_reel_base () override
Definition at line 27 of file Fluide_reel_base.cpp.
Member Function Documentation
abortTimeStep()
void Fluide_reel_base::abortTimeStep () override virtual
Reimplemented from Milieu_base.
Definition at line 144 of file Fluide_reel_base.cpp.
{
  Fluide_base::abortTimeStep();
  rho->abortTimeStep();
  e_int->abortTimeStep();
  h->abortTimeStep();
}
References Milieu_base::abortTimeStep(), Fluide_base::e_int, Fluide_base::h, and Milieu_base::rho.
beta_()
virtual double Fluide_reel_base::beta_ (const double T, const double P) const protected pure virtual
Implemented in Fluide_sodium_gaz, Fluide_sodium_liquide, and StiffenedGas.
calculer_energie_interne()
void Fluide_reel_base::calculer_energie_interne (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static protected
Definition at line 210 of file Fluide_reel_base.cpp.
{
  const Fluide_reel_base& fl = ref_cast(Fluide_reel_base, obj);
  const Champ_Inc_base& ch_T = fl.equation("temperature").inconnue().valeur(),
                        &ch_p = ref_cast(Navier_Stokes_std, fl.equation("vitesse")).pression().valeur();
  const DoubleTab& T = ch_T.valeurs(), &p = ch_p.valeurs();
  int i, zero = 0, Ni = val.dimension_tot(0), Nb = bval.dimension_tot(0), n = std::max(fl.id_composite, zero), m = p.line_size() == T.line_size() ? n : 0,
         incomp = fl.T_ref_ >= 0 && fl.P_ref_ >= 0;
  if (incomp) return calculer_enthalpie(obj, val, bval, deriv); //en incompressible, on prend e_int = h
  for (i = 0; i < Ni; i++) val(i) = fl.h_(T(i, n), p(i, m)) - p(i, m) / fl.rho_(T(i, n), p(i, m));
  const DoubleTab& bT = ch_T.valeur_aux_bords(), &bp = ch_p.valeur_aux_bords();
  for (i = 0; i < Nb; i++) bval(i) = fl.h_(bT(i, n), bp(i, m)) - bp(i, m) / fl.rho_(bT(i, n), bp(i, m));
  DoubleTab& dp_e = deriv["pression"], &dT_e = deriv["temperature"];
  for (dp_e.resize(Ni, 1), i = 0; i < Ni; i++) dp_e(i) = fl.dP_h_(T(i, n), p(i, m)) - 1. / fl.rho_(T(i, n), p(i, m)) + p(i, m) * fl.dP_rho_(T(i, n), p(i, m)) / std::pow(fl.rho_(T(i, n), p(i, m)), 2);
  for (dT_e.resize(Ni, 1), i = 0; i < Ni; i++) dT_e(i) = fl.dT_h_(T(i, n), p(i, m)) + p(i, m) * fl.dT_rho_(T(i, n), p(i, m)) / std::pow(fl.rho_(T(i, n), p(i, m)), 2);
}
References calculer_enthalpie(), TRUSTTab< _TYPE_ >::dimension_tot(), dP_h_(), dP_rho_(), dT_h_(), dT_rho_(), Milieu_base::equation(), h_(), Milieu_base::id_composite, Equation_base::inconnue(), TRUSTVect< _TYPE_ >::line_size(), P_ref_, ref_cast, TRUSTTab< _TYPE_ >::resize(), rho_(), T_ref_, Deriv_Champ_Inc_base::valeur(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), and zero().
Referenced by initialiser().
calculer_enthalpie()
void Fluide_reel_base::calculer_enthalpie (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static protected
Definition at line 189 of file Fluide_reel_base.cpp.
{
  const Fluide_reel_base& fl = ref_cast(Fluide_reel_base, obj);
  const Champ_Inc_base& ch_T = fl.equation("temperature").inconnue().valeur(),
                        &ch_p = ref_cast(Navier_Stokes_std, fl.equation("vitesse")).pression().valeur();
  const DoubleTab& T = ch_T.valeurs(), &p = ch_p.valeurs();
  int i, zero = 0, Ni = val.dimension_tot(0), Nb = bval.dimension_tot(0), n = std::max(fl.id_composite, zero), m = p.line_size() == T.line_size() ? n : 0,
         incomp = fl.T_ref_ >= 0 && fl.P_ref_ >= 0;
  double h0 = incomp ? fl.h_(fl.T_ref_, fl.P_ref_) : -1, Cp0 = incomp ? fl.dT_h_(fl.T_ref_, fl.P_ref_) : -1;
  for (i = 0; i < Ni; i++) val(i) = hc(T(i, n), p(i, m));
  const DoubleTab& bT = ch_T.valeur_aux_bords(), &bp = ch_p.valeur_aux_bords();
  for (i = 0; i < Nb; i++) bval(i) = hc(bT(i, n), bp(i, m));
  DoubleTab  *dp_h = incomp ? NULL : &deriv["pression"], &dT_h = deriv["temperature"];//une seule derivee en incompressible
  if (dp_h)
    for (dp_h->resize(Ni, 1), i = 0; i < Ni; i++) (*dp_h)(i) = fl.dP_h_(T(i, n), p(i, m));
  for (dT_h.resize(Ni, 1), i = 0; i < Ni; i++) dT_h(i) = incomp ? Cp0 : fl.dT_h_(T(i, n), p(i, m));
}
References TRUSTTab< _TYPE_ >::dimension_tot(), dP_h_(), dT_h_(), Milieu_base::equation(), h_(), hc, Milieu_base::id_composite, Equation_base::inconnue(), TRUSTVect< _TYPE_ >::line_size(), P_ref_, ref_cast, TRUSTTab< _TYPE_ >::resize(), T_ref_, Deriv_Champ_Inc_base::valeur(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), and zero().
Referenced by calculer_energie_interne(), and initialiser().
calculer_masse_volumique()
void Fluide_reel_base::calculer_masse_volumique (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static protected
Definition at line 167 of file Fluide_reel_base.cpp.
{
  const Fluide_reel_base& fl = ref_cast(Fluide_reel_base, obj);
  const Champ_Inc_base& ch_T = fl.equation("temperature").inconnue().valeur(),
                        &ch_p = ref_cast(Navier_Stokes_std, fl.equation("vitesse")).pression().valeur();
  const DoubleTab& T = ch_T.valeurs(), &p = ch_p.valeurs();
  int i, zero = 0, Ni = val.dimension_tot(0), Nb = bval.dimension_tot(0), n = std::max(fl.id_composite, zero), m = p.line_size() == T.line_size() ? n : 0,
         incomp = fl.T_ref_ >= 0 && fl.P_ref_ >= 0;
  double rho0 = incomp ? fl.rho_(fl.T_ref_, fl.P_ref_) : -1;
  for (i = 0; i < Ni; i++) val(i) = rhoc(T(i, n), p(i, m));
  const DoubleTab& bT = ch_T.valeur_aux_bords(), &bp = ch_p.valeur_aux_bords();
  for (i = 0; i < Nb; i++) bval(i) = rhoc(bT(i, n), bp(i, m));
  if (incomp) return; //pas de derivees en incompressible
  DoubleTab& dp_rho = deriv["pression"], &dT_rho = deriv["temperature"];
  for (dp_rho.resize(Ni, 1), i = 0; i < Ni; i++) dp_rho(i) = fl.dP_rho_(T(i, n), p(i, m));
  for (dT_rho.resize(Ni, 1), i = 0; i < Ni; i++) dT_rho(i) = fl.dT_rho_(T(i, n), p(i, m));
}
References TRUSTTab< _TYPE_ >::dimension_tot(), dP_rho_(), dT_rho_(), Milieu_base::equation(), Milieu_base::id_composite, Equation_base::inconnue(), TRUSTVect< _TYPE_ >::line_size(), P_ref_, ref_cast, TRUSTTab< _TYPE_ >::resize(), rho_(), rhoc, T_ref_, Deriv_Champ_Inc_base::valeur(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), and zero().
Referenced by initialiser().
check_unknown_range()
int Fluide_reel_base::check_unknown_range () const override virtual
Reimplemented from Milieu_base.
Definition at line 130 of file Fluide_reel_base.cpp.
{
  int ok = 1, zero = 0, nl = rho.valeurs().dimension_tot(0); //on n'impose pas de contraintes aux lignes correspondant a des variables auxiliaires (eg pressions aux faces dans PolyMAC)
  for (auto &&i_r : unknown_range())
    {
      const DoubleTab& vals = i_r.first == "pression" ? ref_cast(Navier_Stokes_std, equation("vitesse")).pression().valeurs() : equation(i_r.first).inconnue().valeurs();
      double vmin = DBL_MAX, vmax = -DBL_MAX;
      for (int i = 0, j = std::min(std::max(id_composite, zero), vals.dimension(1) - 1); i < nl; i++)
        vmin = std::min(vmin, vals(i, j)), vmax = std::max(vmax, vals(i, j));
      ok &= Process::mp_min(vmin) >= i_r.second[0] && Process::mp_max(vmax) <= i_r.second[1];
    }
  return ok;
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), Milieu_base::equation(), Milieu_base::id_composite, Equation_base::inconnue(), Process::mp_max(), Process::mp_min(), ref_cast, Milieu_base::rho, unknown_range(), Champ::valeurs(), Champ_Inc::valeurs(), and zero().
cp_()
virtual double Fluide_reel_base::cp_ (const double T, const double P) const protected pure virtual
Implemented in Fluide_sodium_gaz, Fluide_sodium_liquide, and StiffenedGas.
Referenced by mettre_a_jour().
discretiser()
void Fluide_reel_base::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Fluide_base.
Definition at line 51 of file Fluide_reel_base.cpp.
{
  Cerr << "Medium discretization." << finl;
  const Zone_dis_base& zone_dis = pb.equation(0).zone_dis();
  const double temps = pb.schema_temps().temps_courant();
  /* masse volumique, energie interne, enthalpie : champ_inc */
  Champ_Inc rho_inc, ei_inc, h_inc;
  int nc = pb.equation(0).inconnue()->nb_valeurs_temporelles();
  dis.discretiser_champ("champ_elem", zone_dis,       "masse_volumique",    "kg/m^3", 1, nc, temps, rho_inc);
  dis.discretiser_champ("champ_elem", zone_dis,       "energie_interne",     "J/kg", 1, nc, temps, ei_inc);
  dis.discretiser_champ("champ_elem", zone_dis,             "enthalpie",     "J/kg", 1, nc, temps, h_inc);
  rho = rho_inc, e_int = ei_inc, h = h_inc;
  dis.discretiser_champ("champ_elem", zone_dis,   "viscosite_dynamique",    "kg/m/s", 1, temps,       mu);
  dis.discretiser_champ("champ_elem", zone_dis, "viscosite_cinematique",      "m2/s", 1, temps,       nu);
  dis.discretiser_champ("champ_elem", zone_dis,           "diffusivite",      "m2/s", 1, temps,    alpha);
  dis.discretiser_champ("champ_elem", zone_dis,          "conductivite",     "W/m/K", 1, temps,   lambda);
  dis.discretiser_champ("champ_elem", zone_dis,  "capacite_calorifique",    "J/kg/K", 1, temps,       Cp);
}
References Milieu_base::alpha, Cerr, Milieu_base::Cp, Discretisation_base::discretiser_champ(), Fluide_base::e_int, Probleme_base::equation(), finl, Fluide_base::h, Equation_base::inconnue(), Milieu_base::lambda, Fluide_base::mu, Champ_Inc::nb_valeurs_temporelles(), Fluide_base::nu, Milieu_base::rho, Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), and Equation_base::zone_dis().
dP_h_()
virtual double Fluide_reel_base::dP_h_ (const double T, const double P) const protected pure virtual
Implemented in Fluide_sodium_gaz, Fluide_sodium_liquide, and StiffenedGas.
Referenced by calculer_energie_interne(), and calculer_enthalpie().
dP_rho_()
virtual double Fluide_reel_base::dP_rho_ (const double T, const double P) const protected pure virtual
Implemented in Fluide_sodium_gaz, Fluide_sodium_liquide, and StiffenedGas.
Referenced by calculer_energie_interne(), and calculer_masse_volumique().
dT_h_()
virtual double Fluide_reel_base::dT_h_ (const double T, const double P) const protected pure virtual
Implemented in Fluide_sodium_gaz, Fluide_sodium_liquide, and StiffenedGas.
Referenced by calculer_energie_interne(), and calculer_enthalpie().
dT_rho_()
virtual double Fluide_reel_base::dT_rho_ (const double T, const double P) const protected pure virtual
Implemented in Fluide_sodium_gaz, Fluide_sodium_liquide, and StiffenedGas.
Referenced by calculer_energie_interne(), and calculer_masse_volumique().
get_info()
const Type_info * Fluide_reel_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Fluide_base.
Reimplemented in Fluide_sodium_gaz, Fluide_sodium_liquide, and StiffenedGas.
Definition at line 27 of file Fluide_reel_base.cpp.
h_()
virtual double Fluide_reel_base::h_ (const double T, const double P) const protected pure virtual
Implemented in Fluide_sodium_gaz, Fluide_sodium_liquide, and StiffenedGas.
Referenced by calculer_energie_interne(), and calculer_enthalpie().
info()
const Type_info * Fluide_reel_base::info () static
Definition at line 27 of file Fluide_reel_base.cpp.
initialiser()
int Fluide_reel_base::initialiser (const double temps) override virtual
Initialise les parametres du fluide.
Reimplemented from Fluide_base.
Definition at line 73 of file Fluide_reel_base.cpp.
{
  const Equation_base& eqn = equation("temperature");
  Champ_Inc_base& ch_rho = ref_cast(Champ_Inc_base, rho.valeur()),
                  &ch_e   = ref_cast(Champ_Inc_base, e_int.valeur()),
                   &ch_h   = ref_cast(Champ_Inc_base, h.valeur());
  ch_rho.associer_eqn(eqn), ch_rho.init_champ_calcule(*this, calculer_masse_volumique);
  ch_e.associer_eqn(eqn),   ch_e.init_champ_calcule(*this, calculer_energie_interne);
  ch_h.associer_eqn(eqn),   ch_h.init_champ_calcule(*this, calculer_enthalpie);
  Cp.initialiser(temps);
  mu.initialiser(temps);
  nu.initialiser(temps);
  alpha.initialiser(temps);
  lambda.initialiser(temps);
  t_init_ = temps;
  return 1;
}
References Milieu_base::alpha, Champ_Inc_base::associer_eqn(), calculer_energie_interne(), calculer_enthalpie(), calculer_masse_volumique(), Milieu_base::Cp, Fluide_base::e_int, Milieu_base::equation(), Fluide_base::h, Champ_Inc_base::init_champ_calcule(), Champ_Don::initialiser(), Milieu_base::lambda, Fluide_base::mu, Fluide_base::nu, ref_cast, Milieu_base::rho, t_init_, and Deriv_Champ_base::valeur().
initTimeStep()
bool Fluide_reel_base::initTimeStep (double dt) override virtual
Reimplemented from Fluide_base.
Definition at line 152 of file Fluide_reel_base.cpp.
{
  if (!equation_.size()) return true; //pas d'equation associee -> ???
  const Schema_Temps_base& sch = equation_.begin()->second->schema_temps(); //on recupere le schema en temps par la 1ere equation
  /* champs dont on doit creer des cases */
  std::vector<Champ_Inc_base *> vch = { &ref_cast(Champ_Inc_base, rho.valeur()), &ref_cast(Champ_Inc_base, e_int.valeur()), &ref_cast(Champ_Inc_base, h.valeur()) };
  for (auto &&pch : vch)
    for (int i = 1; i <= sch.nb_valeurs_futures(); i++)
      pch->changer_temps_futur(sch.temps_futur(i), i), pch->futur(i) = pch->valeurs();
  return true;
}
References Fluide_base::e_int, Milieu_base::equation_, Fluide_base::h, Schema_Temps_base::nb_valeurs_futures(), ref_cast, Milieu_base::rho, Schema_Temps_base::temps_futur(), and Deriv_Champ_base::valeur().
lambda_()
virtual double Fluide_reel_base::lambda_ (const double T, const double P) const protected pure virtual
Implemented in Fluide_sodium_gaz, Fluide_sodium_liquide, and StiffenedGas.
Referenced by mettre_a_jour().
mettre_a_jour()
void Fluide_reel_base::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps du milieu,
et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le
nouveau temps specifie, les autres sont mis a
par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
Reimplemented from Fluide_base.
Definition at line 98 of file Fluide_reel_base.cpp.
{
  double tp = ref_cast(Champ_Inc_base, rho.valeur()).temps(); //pour savoir si on va tourner la roue
  rho.mettre_a_jour(t);
  e_int.mettre_a_jour(t);
  h.mettre_a_jour(t);
  Cp.mettre_a_jour(t);
  mu.mettre_a_jour(t);
  lambda.mettre_a_jour(t);
  nu.mettre_a_jour(t);
  alpha.mettre_a_jour(t);
  const Champ_Inc_base& ch_T = equation("temperature").inconnue().valeur(), &ch_p = ref_cast(Navier_Stokes_std, equation("vitesse")).pression().valeur();
  const DoubleTab& temp = ch_T.valeurs(), &pres = ch_p.valeurs();
  int i, Ni = mu.valeurs().dimension_tot(0);
  DoubleTab& tab_Cp = Cp.valeurs(), &tab_mu = mu.valeurs(), &tab_lambda = lambda.valeurs(), &tab_nu = nu.valeurs(), &tab_alpha = alpha.valeurs();
  const DoubleTab& tab_rho = masse_volumique().valeurs();
  if (t > tp || first_maj_)
    for (i = 0; i < Ni; i++) /* maj uniquement en fin de pas de temps */
      {
        const double T = (T_ref_ > 0) ? T_ref_ : temp(i, id_composite), P = (P_ref_ > 0) ? P_ref_ : pres(i);
        tab_Cp(i) = cp_(T, P);
        tab_mu(i) = mu_(T, P);
        tab_lambda(i) = lambda_(T, P);
        tab_nu(i) = tab_mu(i) / tab_rho(i);
        tab_alpha(i) = tab_lambda(i) / tab_rho(i) / tab_Cp(i);
      }
  first_maj_ = 0;
}
References Milieu_base::alpha, Milieu_base::Cp, cp_(), TRUSTTab< _TYPE_ >::dimension_tot(), Fluide_base::e_int, Milieu_base::equation(), first_maj_, Fluide_base::h, Milieu_base::id_composite, Equation_base::inconnue(), Milieu_base::lambda, lambda_(), Milieu_base::masse_volumique(), Champ_Don::mettre_a_jour(), Champ::mettre_a_jour(), Fluide_base::mu, mu_(), Fluide_base::nu, P_ref_, ref_cast, Milieu_base::rho, T_ref_, Deriv_Champ_base::valeur(), Deriv_Champ_Inc_base::valeur(), Champ::valeurs(), Champ_Don::valeurs(), and Champ_Inc_base::valeurs().
Referenced by preparer_calcul().
mu_()
virtual double Fluide_reel_base::mu_ (const double T, const double P) const protected pure virtual
Implemented in Fluide_sodium_gaz, Fluide_sodium_liquide, and StiffenedGas.
Referenced by mettre_a_jour().
preparer_calcul()
void Fluide_reel_base::preparer_calcul (void) override virtual
Reimplemented from Milieu_base.
Definition at line 92 of file Fluide_reel_base.cpp.
{
  mettre_a_jour(t_init_);
}
References mettre_a_jour(), and t_init_.
printOn()
Sortie & Fluide_reel_base::printOn (Sortie & os) const override protected virtual
Ecrit les proprietes du fluide sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Fluide_base.
Reimplemented in Fluide_sodium_gaz, Fluide_sodium_liquide, and StiffenedGas.
Definition at line 46 of file Fluide_reel_base.cpp.
{
  return os;
}
readOn()
Entree & Fluide_reel_base::readOn (Entree & is) override protected virtual
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Fluide_base.
Reimplemented in Fluide_sodium_gaz, Fluide_sodium_liquide, and StiffenedGas.
Definition at line 30 of file Fluide_reel_base.cpp.
{
  Param param(que_suis_je());
  set_param(param);
  param.lire_avec_accolades_depuis(is);
  if ((P_ref_ >= 0 ) != (T_ref_ >= 0))
    Process::exit(que_suis_je() + ": T_ref and P_ref must both be specified!");
  return is;
}
References Process::exit(), Param::lire_avec_accolades_depuis(), P_ref_, Objet_U::que_suis_je(), set_param(), and T_ref_.
Referenced by Fluide_sodium_gaz::readOn(), Fluide_sodium_liquide::readOn(), and StiffenedGas::readOn().
rho_()
virtual double Fluide_reel_base::rho_ (const double T, const double P) const protected pure virtual
Implemented in Fluide_sodium_gaz, Fluide_sodium_liquide, and StiffenedGas.
Referenced by calculer_energie_interne(), and calculer_masse_volumique().
self_cast() [1/2]
const Fluide_reel_base & Fluide_reel_base::self_cast (const Objet_U & r) static
Definition at line 27 of file Fluide_reel_base.cpp.
self_cast() [2/2]
Fluide_reel_base & Fluide_reel_base::self_cast (Objet_U & r) static
Definition at line 27 of file Fluide_reel_base.cpp.
set_param()
void Fluide_reel_base::set_param (Param & param) override virtual
Reimplemented from Fluide_base.
Reimplemented in StiffenedGas.
Definition at line 40 of file Fluide_reel_base.cpp.
{
  param.ajouter("T_ref",&T_ref_);
  param.ajouter("P_ref",&P_ref_);
}
References Param::ajouter(), P_ref_, and T_ref_.
Referenced by readOn(), and StiffenedGas::set_param().
unknown_range()
virtual std::map< std::string, std::array< double, 2 > > Fluide_reel_base::unknown_range () const inline virtual
Reimplemented in Fluide_sodium_gaz, and Fluide_sodium_liquide.
Definition at line 56 of file Fluide_reel_base.h.
  {
    return {};
  }
Referenced by check_unknown_range().
Member Data Documentation
first_maj_
int Fluide_reel_base::first_maj_ = 1 protected
Definition at line 83 of file Fluide_reel_base.h.
Referenced by mettre_a_jour().
info_obj
const Type_info Fluide_reel_base::info_obj static
Definition at line 42 of file Fluide_reel_base.h.
P_ref_
double Fluide_reel_base::P_ref_ = -1 protected
Definition at line 82 of file Fluide_reel_base.h.
Referenced by calculer_energie_interne(), calculer_enthalpie(), calculer_masse_volumique(), mettre_a_jour(), readOn(), and set_param().
t_init_
double Fluide_reel_base::t_init_ protected
Definition at line 84 of file Fluide_reel_base.h.
Referenced by initialiser(), and preparer_calcul().
T_ref_
double Fluide_reel_base::T_ref_ = -1 protected
Definition at line 81 of file Fluide_reel_base.h.
Referenced by calculer_energie_interne(), calculer_enthalpie(), calculer_masse_volumique(), mettre_a_jour(), readOn(), and set_param().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Milieu/Fluide_reel_base.h
src/ThHyd/Multiphase/Milieu/Fluide_reel_base.cpp