TRUST: Fluide_Dilatable_base Class Reference
Fluide_Dilatable_base Class Reference abstract
classe Fluide_Dilatable_base
Cette classe represente un d'un fluide dilatable,
heritant de fluide base
#include <Fluide_Dilatable_base.h>
Public Member Functions
~Fluide_Dilatable_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Fluide_Dilatable_base ()
void verifier_coherence_champs (int &err, Nom &message) override
Verifie que les champs lus l'ont ete correctement.
void set_Cp (double)
Complete le fluide avec un Cp constant.
void update_rho_cp (double temps) override
void creer_champs_non_lus () override
void initialiser_radiatives (const double temps)
void warn_syntax_Sutherland ()
int initialiser (const double temps) override
Initialise les parametres du fluide.
const DoubleTab & temperature () const
Renvoie le tableau des valeurs de le temperature.
const Champ_Don & ch_temperature () const
Renvoie le champ de le temperature.
Champ_Don & ch_temperature ()
virtual void calculer_pression_tot ()
Calcule la pression totale : pression thermodynamique + pression hydrodynamique.
virtual void preparer_pas_temps ()
Prepare le pas de temps.
void abortTimeStep () override
void set_param (Param &param) override
void discretiser (const Probleme_base &pb, const Discretisation_base &dis) override
void mettre_a_jour (double) override
virtual void update_pressure_fields (double)
void preparer_calcul () override
Prepare le fluide au calcul.
virtual void completer (const Probleme_base &)
Complete le fluide avec les champs inconnus associes au probleme.
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void checkTraitementPth (const Zone_Cl_dis &)=0
virtual void prepare_pressure_edo ()=0
virtual void write_mean_edo (double)=0
virtual void secmembre_divU_Z (DoubleTab &) const =0
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
const Nom type_fluide () const
const Loi_Etat & loi_etat () const
Loi_Etat & loi_etat ()
const Champ_Inc & inco_chaleur () const
Champ_Inc & inco_chaleur ()
const Champ_Inc & vitesse () const
const Champ_Don & pression_tot () const
Champ_Don & pression_tot ()
const Champ_Don & mu_sur_Schmidt () const
Champ_Don & mu_sur_Schmidt ()
const Champ_Don & nu_sur_Schmidt () const
Champ_Don & nu_sur_Schmidt ()
const DoubleTab & rho_n () const
const DoubleTab & rho_np1 () const
void calculer_coeff_T ()
void initialiser_inco_ch ()
void calculer_Cp ()
void calculer_lambda ()
void calculer_mu ()
void calculer_nu () override
void calculer_alpha () override
Calcul de alpha=lambda/(rho*Cp).
Suivant lambda, rho et Cp alpha peut-etre type comme
un champ uniforme ou un champ uniforme par morceau.
void calculer_mu_sur_Sc ()
void calculer_nu_sur_Sc ()
void calculer_masse_volumique ()
void set_pression_th (double Pth)
int getTraitementPth () const
double pression_th () const
Pression thermodynamique.
double pression_thn () const
Pression thermodynamique a l'etape precedente.
double pression_th1 () const
Pression thermodynamique calculee pour conserver la masse.
double calculer_H (double hh) const
Probleme_base & get_problem ()
const DoubleTab & rho_discvit () const
const DoubleTab & rho_face_n () const
const DoubleTab & rho_face_np1 () const
void calculer_rho_face (const DoubleTab &tab_rho)
void divu_discvit (DoubleTab &secmem1, DoubleTab &secmem2)
double moyenne_vol (const DoubleTab &A) const
Public Member Functions inherited from Fluide_base
~Fluide_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Fluide_base ()
const Champ_Don & viscosite_cinematique () const
Renvoie la viscosite cinematique, nu.
(vesrion const)
const Champ_Don & viscosite_dynamique () const
Renvoie la viscosite dynamique, mu.
(version const)
const Champ_Don & beta_c () const
Renvoie la dilatabilite du constituant, beta_co.
(version const)
Champ_Don & viscosite_cinematique ()
Renvoie la viscosite cinematique, nu.
Champ_Don & viscosite_dynamique ()
Renvoie la viscosite dynamique, mu.
Champ_Don & beta_c ()
Renvoie la dilatabilite du constituant, beta_co.
virtual const Champ_base & energie_interne () const
virtual Champ_base & energie_interne ()
virtual const Champ_base & enthalpie () const
virtual Champ_base & enthalpie ()
int is_rayo_semi_transp () const override
int is_rayo_transp () const override
void fixer_type_rayo ()
void reset_type_rayo ()
int longueur_rayo_is_discretised ()
Champ_Don & kappa ()
Renvoie le coefficient d'absorbtion du fluide.
const Champ_Don & kappa () const
Renvoie le coefficient d'absorbtion du fluide.
Champ_Don & indice ()
Renvoie l'indice de refraction du fluide.
const Champ_Don & indice () const
Renvoie l'indice de refraction du fluide.
Champ_Don & longueur_rayo ()
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
const Champ_Don & longeur_rayo () const
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
void set_param (Param &param) override
void verifier_coherence_champs (int &err, Nom &message) override
Verifie que les champs lus l'ont ete correctement.
bool initTimeStep (double dt) override
void mettre_a_jour (double) override
Effectue une mise a jour en temps du milieu,
et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le
nouveau temps specifie, les autres sont mis a
par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
int initialiser (const double temps) override
Initialise les parametres du fluide.
void creer_champs_non_lus () override
void discretiser (const Probleme_base &pb, const Discretisation_base &dis) override
virtual void set_h0_T0 (double h0, double T0)
Public Member Functions inherited from Milieu_base
~Milieu_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Milieu_base ()
virtual void set_param (Param &param)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void preparer_calcul ()
virtual void verifier_coherence_champs (int &err, Nom &message)
virtual void creer_champs_non_lus ()
virtual void discretiser (const Probleme_base &pb, const Discretisation_base &dis)
virtual int is_rayo_semi_transp () const
virtual int is_rayo_transp () const
virtual void mettre_a_jour (double temps)
virtual bool initTimeStep (double dt)
virtual void abortTimeStep ()
virtual int initialiser (const double temps)
virtual void associer_gravite (const Champ_Don_base &)
Associe (affecte) un champ de gravite au milieu.
virtual const Champ & masse_volumique () const
Renvoie la masse volumique du milieu.
(version const)
virtual Champ & masse_volumique ()
Renvoie la masse volumique du milieu.
virtual const Champ_Don & diffusivite () const
Renvoie la diffusivite du milieu.
(version const)
virtual Champ_Don & diffusivite ()
Renvoie la diffusivite du milieu.
virtual const Champ_Don & conductivite () const
Renvoie la conductivite du milieu.
(version const)
virtual Champ_Don & conductivite ()
Renvoie la conductivite du milieu.
virtual const Champ_Don & capacite_calorifique () const
Renvoie la capacite calorifique du milieu.
(version const)
virtual Champ_Don & capacite_calorifique ()
Renvoie la capacite calorifique du milieu.
virtual const Champ_Don & beta_t () const
Renvoie beta_t du milieu.
(version const)
virtual Champ_Don & beta_t ()
Renvoie beta_t du milieu.
virtual int a_gravite () const
Renvoie 1 si la gravite a ete initialisee.
virtual const Champ_Don_base & gravite () const
Renvoie la gravite du milieu si elle a ete associe
provoque une erreur sinon.
(version const)
virtual Champ_Don_base & gravite ()
Renvoie la gravite du milieu si elle a ete associe
provoque une erreur sinon.
int associer_ (Objet_U &) override
Associe la gravite en controlant dynamiquement le
type de l'objet a associer.
Si l'objet est du type Champ_Don ou Champ_Don_base
l'association reussit, sinon elle echoue.
virtual int est_deja_associe ()
Renvoie 0 si le milieu est deja associe a un probleme, 1 sinon.
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void update_rho_cp (double temps)
virtual void associer_equation (const Equation_base *eqn) const
virtual const Equation_base & equation (const std::string &nom_inc) const
virtual int check_unknown_range () const
void set_id_composite (const int i)
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Fluide_Dilatable_base & self_cast (Objet_U &)
static const Fluide_Dilatable_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Fluide_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Fluide_base & self_cast (Objet_U &)
static const Fluide_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Milieu_base
static const Type_info * info ()
static Milieu_base & self_cast (Objet_U &)
static const Milieu_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Fluide_base
static const Type_info info_obj
Static Public Attributes inherited from Milieu_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Entree & readOn (Entree &) override
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
virtual void remplir_champ_pression_tot (int n, const DoubleTab &PHydro, DoubleTab &PTot)=0
Protected Member Functions inherited from Fluide_base
Sortie & printOn (Sortie &x) const override
Ecrit les proprietes du fluide sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
void creer_e_int () const
void creer_nu ()
Si l'objet reference par nu et du type Champ_Uniforme
type nu en "Champ_Uniforme" et le remplit
avec mu(0,0)/rho(0,0).
Sinon n efait rien.
virtual void calculer_nu ()
Protected Member Functions inherited from Milieu_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Entree & readOn (Entree &) override
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
void ecrire (Sortie &) const
Ecrit un objet milieu sur un flot de sortie.
Ecrit les caracteristiques du milieu:
- masse volumique
- conductivite
- capacite calorifique
- beta_th.
void creer_alpha ()
virtual void calculer_alpha ()
Calcul de alpha=lambda/(rho*Cp).
Suivant lambda, rho et Cp alpha peut-etre type comme
un champ uniforme ou un champ uniforme par morceau.
void creer_derivee_rho ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int traitement_PTh
flag pour le traitement de la pression thermo
double Pth_
double Pth_n
double Pth1
Ref_Champ_Inc inco_chaleur_
Ref_Champ_Inc vitesse_
Ref_Champ_Inc pression_
Ref_Probleme_base le_probleme_
Champ_Don pression_tot_
Champ_Don mu_sur_Sc
Champ_Don nu_sur_Sc
Champ_Don rho_gaz
Champ_Don rho_comme_v
Loi_Etat loi_etat_
EOS_Tools eos_tools_
Protected Attributes inherited from Fluide_base
int e_int_auto_ = 0
Champ e_int
Champ h
Champ_Don mu
Champ_Don nu
Champ_Don beta_co
double h0_ = 0
double T0_ = 0
Champ_Don coeff_absorption_
Champ_Don indice_refraction_
Champ_Don longueur_rayo_
Protected Attributes inherited from Milieu_base
Champ rho
Champ_Don alpha
Champ_Don lambda
Champ_Don Cp
Champ_Don beta_th
Champ_Fonc rho_cp_elem_
Champ_Fonc rho_cp_comme_T_
Nom nom_
Ref_Champ_Don_base g
Type_rayo indic_rayo_
int deja_associe
Champs_compris champs_compris_
std::map< std::string, const Equation_base * > equation_
Additional Inherited Members
Public Attributes inherited from Milieu_base
int id_composite = -1
Protected Types inherited from Milieu_base
enum Type_rayo { NONRAYO , TRANSP , SEMITRANSP }
Static Protected Member Functions inherited from Fluide_base
static void calculer_e_int (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Detailed Description
classe Fluide_Dilatable_base
Cette classe represente un d'un fluide dilatable,
heritant de fluide base
Definition at line 40 of file Fluide_Dilatable_base.h.
Constructor & Destructor Documentation
~Fluide_Dilatable_base()
Fluide_Dilatable_base::~Fluide_Dilatable_base () override
Definition at line 26 of file Fluide_Dilatable_base.cpp.
Fluide_Dilatable_base()
Fluide_Dilatable_base::Fluide_Dilatable_base ()
Definition at line 29 of file Fluide_Dilatable_base.cpp.
:traitement_PTh(0),Pth_(-1.),Pth_n(-1.),Pth1(-1.) {}
Member Function Documentation
abortTimeStep()
void Fluide_Dilatable_base::abortTimeStep () override virtual
Reimplemented from Milieu_base.
Reimplemented in Fluide_Weakly_Compressible.
Definition at line 335 of file Fluide_Dilatable_base.cpp.
{
  loi_etat()->abortTimeStep();
  Pth_=Pth_n;
}
References loi_etat(), Pth_, and Pth_n.
Referenced by Fluide_Weakly_Compressible::abortTimeStep().
calculer_alpha()
void Fluide_Dilatable_base::calculer_alpha () inline override virtual
Calcul de alpha=lambda/(rho*Cp).
Suivant lambda, rho et Cp alpha peut-etre type comme
un champ uniforme ou un champ uniforme par morceau.
Reimplemented from Milieu_base.
Definition at line 100 of file Fluide_Dilatable_base.h.
{ loi_etat_->calculer_alpha(); }
References loi_etat_.
Referenced by calculer_coeff_T().
calculer_coeff_T()
void Fluide_Dilatable_base::calculer_coeff_T () inline
Definition at line 131 of file Fluide_Dilatable_base.h.
{
  loi_etat_->remplir_T();
  calculer_Cp();
  calculer_mu();
  calculer_lambda();
  calculer_nu();
  calculer_alpha();
  calculer_mu_sur_Sc();
  calculer_nu_sur_Sc();
}
References calculer_alpha(), calculer_Cp(), calculer_lambda(), calculer_mu(), calculer_mu_sur_Sc(), calculer_nu(), calculer_nu_sur_Sc(), and loi_etat_.
Referenced by Pb_Dilatable_base::iterateTimeStep(), and preparer_calcul().
calculer_Cp()
void Fluide_Dilatable_base::calculer_Cp () inline
Definition at line 96 of file Fluide_Dilatable_base.h.
{ loi_etat_->calculer_Cp(); }
References loi_etat_.
Referenced by calculer_coeff_T().
calculer_H()
double Fluide_Dilatable_base::calculer_H (double hh) const inline
Definition at line 109 of file Fluide_Dilatable_base.h.
{ return loi_etat_->calculer_H(Pth_,hh); }
References loi_etat_, and Pth_.
Referenced by Echange_externe_impose_H::T_ext(), Neumann_sortie_libre_Temp_H::val_ext(), Entree_fluide_temperature_imposee_H::val_imp(), and Temperature_imposee_paroi_H::val_imp().
calculer_lambda()
void Fluide_Dilatable_base::calculer_lambda () inline
Definition at line 97 of file Fluide_Dilatable_base.h.
{ loi_etat_->calculer_lambda(); }
References loi_etat_.
Referenced by calculer_coeff_T().
calculer_masse_volumique()
void Fluide_Dilatable_base::calculer_masse_volumique () inline
Definition at line 103 of file Fluide_Dilatable_base.h.
{ loi_etat_->calculer_masse_volumique(); }
References loi_etat_.
Referenced by Pb_Dilatable_base::iterateTimeStep(), Pb_Dilatable_base::preparer_calcul(), and EDO_Pression_th_VEF_Gaz_Parfait::resoudre().
calculer_mu()
void Fluide_Dilatable_base::calculer_mu () inline
Definition at line 98 of file Fluide_Dilatable_base.h.
{ loi_etat_->calculer_mu(); }
References loi_etat_.
Referenced by calculer_coeff_T().
calculer_mu_sur_Sc()
void Fluide_Dilatable_base::calculer_mu_sur_Sc () inline
Definition at line 101 of file Fluide_Dilatable_base.h.
{ loi_etat_-> calculer_mu_sur_Sc(); }
References calculer_mu_sur_Sc(), and loi_etat_.
Referenced by calculer_coeff_T(), and calculer_mu_sur_Sc().
calculer_nu()
void Fluide_Dilatable_base::calculer_nu () inline override virtual
Reimplemented from Fluide_base.
Definition at line 99 of file Fluide_Dilatable_base.h.
{ loi_etat_->calculer_nu(); }
References loi_etat_.
Referenced by calculer_coeff_T().
calculer_nu_sur_Sc()
void Fluide_Dilatable_base::calculer_nu_sur_Sc () inline
Definition at line 102 of file Fluide_Dilatable_base.h.
{ loi_etat_-> calculer_nu_sur_Sc(); }
References calculer_nu_sur_Sc(), and loi_etat_.
Referenced by calculer_coeff_T(), and calculer_nu_sur_Sc().
calculer_pression_tot()
void Fluide_Dilatable_base::calculer_pression_tot () virtual
Calcule la pression totale : pression thermodynamique + pression hydrodynamique.
Reimplemented in Fluide_Weakly_Compressible.
Definition at line 461 of file Fluide_Dilatable_base.cpp.
{
  DoubleTab& tab_Ptot = pression_tot_.valeurs();
  const int n = tab_Ptot.dimension_tot(0);
  DoubleTab tab_PHyd(n, 1);
  if( n != pression_->valeurs().dimension_tot(0) )
    {
// Interpolation de pression_ aux elements (ex: P1P0)
      const Zone_dis_base& zone_dis= pression_-> zone_dis_base();
      const Zone_VF& zone = ref_cast(Zone_VF, zone_dis);
      const DoubleTab& centres_de_gravites=zone.xp();
      pression_->valeur().valeur_aux(centres_de_gravites,tab_PHyd);
    }
  else  tab_PHyd = pression_->valeurs();
// impl dans les classes filles
  remplir_champ_pression_tot(n,tab_PHyd,tab_Ptot);
}
References TRUSTTab< _TYPE_ >::dimension_tot(), pression_, pression_tot_, ref_cast, remplir_champ_pression_tot(), Deriv_Champ_Inc_base::valeur(), Champ_Inc_base::valeur_aux(), Champ_Don::valeurs(), Champ_Inc::valeurs(), and Zone_VF::xp().
Referenced by Fluide_Weakly_Compressible::calculer_pression_tot(), and update_pressure_fields().
calculer_rho_face()
void Fluide_Dilatable_base::calculer_rho_face (const DoubleTab & tab_rho) inline
Definition at line 116 of file Fluide_Dilatable_base.h.
{ eos_tools_->calculer_rho_face_np1(tab_rho); }
References eos_tools_.
Referenced by Loi_Etat_base::calculer_masse_volumique(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), and Loi_Etat_Multi_GP_WC::calculer_masse_volumique().
ch_temperature() [1/2]
Champ_Don & Fluide_Dilatable_base::ch_temperature ()
Definition at line 310 of file Fluide_Dilatable_base.cpp.
{
  return loi_etat_->ch_temperature();
}
References loi_etat_.
ch_temperature() [2/2]
const Champ_Don & Fluide_Dilatable_base::ch_temperature () const
Renvoie le champ de le temperature.
Definition at line 305 of file Fluide_Dilatable_base.cpp.
{
  return loi_etat_->ch_temperature();
}
References loi_etat_.
Referenced by Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), mettre_a_jour(), and temperature().
checkTraitementPth()
virtual void Fluide_Dilatable_base::checkTraitementPth (const Zone_Cl_dis &) pure virtual
Implemented in Fluide_Weakly_Compressible, and Fluide_Quasi_Compressible.
completer()
void Fluide_Dilatable_base::completer (const Probleme_base & pb) virtual
Complete le fluide avec les champs inconnus associes au probleme.
Reimplemented in Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
Definition at line 562 of file Fluide_Dilatable_base.cpp.
{
  le_probleme_ = pb;
  inco_chaleur_ = pb.equation(1).inconnue();
  vitesse_ = pb.equation(0).inconnue();
  const Navier_Stokes_std& eqn_hydr = ref_cast(Navier_Stokes_std,pb.equation(0));
  pression_ = eqn_hydr.pression();
  Nom typ = pb.equation(0).discretisation().que_suis_je();
  if (typ=="VEFPreP1B") typ = "VEF";
  eos_tools_.typer(typ);
  eos_tools_->associer_zones(pb.equation(0).zone_dis(),pb.equation(0).zone_Cl_dis());
  eos_tools_->associer_fluide(*this);
  loi_etat_->assoscier_probleme(pb);
  initialiser_inco_ch();
  eos_tools_->mettre_a_jour(pb.schema_temps().temps_courant());
  loi_etat_->initialiser();
}
References Equation_base::discretisation(), eos_tools_, Probleme_base::equation(), inco_chaleur_, Equation_base::inconnue(), initialiser_inco_ch(), le_probleme_, loi_etat_, Navier_Stokes_std::pression(), pression_, Objet_U::que_suis_je(), ref_cast, Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), EOS_Tools::typer(), vitesse_, Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
Referenced by Fluide_Quasi_Compressible::completer(), Fluide_Weakly_Compressible::completer(), and Pb_Dilatable_base::preparer_calcul().
creer_champs_non_lus()
void Fluide_Dilatable_base::creer_champs_non_lus () override virtual
Reimplemented from Milieu_base.
Reimplemented in Espece.
Definition at line 341 of file Fluide_Dilatable_base.cpp.
{
// on s'occupe de lamda si mu uniforme et CP uniforme
// on type lambda en champ uniforme et on met lambda=mu*Cp/Pr
//
  if (mu.non_nul())
    {
      if (!(lambda.non_nul())||(!sub_type(Champ_Fonc_Tabule,lambda.valeur())))
        if ((sub_type(Champ_Uniforme,mu.valeur()))&&(sub_type(Loi_Etat_GP_base,loi_etat_.valeur())))
          {
            if (!sub_type(Loi_Etat_Multi_GP_QC,loi_etat_.valeur()))
              {
// Si mu uniforme et si la loi d'etat est celle d'un gaz parfait
                double lold=-1;
                if (lambda.non_nul())
                  lold=lambda.valeurs()(0,0);
                lambda.typer(mu.valeur().le_type());
                lambda=mu;
                loi_etat_->calculer_lambda();
                double lo=lambda.valeurs()(0,0);
                if (lold!=-1)
                  {
                    if (!est_egal(lold,lo))
                      {
                        Cerr << "Error : mu, lambda, Cp and Prandtl are all specified in your data set." << finl;
                        Cerr << "It is observed that your imput values leads to :" << finl;
                        Cerr.precision(20);
                        Cerr << "mu/(lambda*Cp)=" << loi_etat_->Prandt()*(lo/lold) << " and Prandtl=" << loi_etat_->Prandt() << finl;
                        Cerr<<"Please modify your data set by specifying for instance Prandtl = "<<loi_etat_->Prandt()*(lo/lold)<<finl;
                        Process::exit();
                      }
                  }
              }
          }
      if (lambda.non_nul())
        {
          if (sub_type(Sutherland,lambda.valeur()))
            {
              if (!sub_type(Champ_Uniforme,Cp.valeur()))
                {
                  Cerr << "A sutherland law cannot be requested for the conductivity "<<finl;
                  Cerr << "by indicating Slambda if the heat capacity (Cp) is not uniform."<<finl;
                  Process::exit();
                }
              Sutherland& mu_suth = ref_cast(Sutherland,mu.valeur());
              const double mu0 = mu_suth.get_A();
              Sutherland& lambda_suth = ref_cast(Sutherland,lambda.valeur());
              double lambda0 = mu0/loi_etat_->Prandt()*Cp(0,0);
              lambda_suth.set_A(lambda0);
              lambda_suth.lire_expression();
            }
        }
    }
}
References Cerr, Milieu_base::Cp, est_egal(), Process::exit(), finl, Sutherland::get_A(), Milieu_base::lambda, Objet_U::le_type(), Sutherland::lire_expression(), loi_etat_, Fluide_base::mu, O_U_Ptr::non_nul(), ref_cast, Sutherland::set_A(), sub_type, Deriv_::typer(), Deriv_Champ_Don_base::valeur(), Deriv_Loi_Etat_base::valeur(), and Champ_Don::valeurs().
discretiser()
void Fluide_Dilatable_base::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Milieu_base.
Reimplemented in Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
Definition at line 43 of file Fluide_Dilatable_base.cpp.
{
  Cerr<<"Fluide_Dilatable_base::discretiser"<<finl;
  const Zone_dis_base& zone_dis=pb.equation(0).zone_dis();
  double temps=pb.schema_temps().temps_courant();
// les champs seront nommes par le milieu_base
  Champ_Don ch_rho;
  dis.discretiser_champ("temperature",zone_dis,"masse_volumique_p","neant",1,temps,ch_rho);
  rho = ch_rho.valeur();
  Champ_Don& cp = capacite_calorifique();
  if (!cp.non_nul() || !sub_type(Champ_Uniforme,cp.valeur())) //ie Cp non constant : gaz reels
    {
      Cerr<<"Heat capacity Cp is discretized once more for space variable case."<<finl;
      dis.discretiser_champ("temperature",zone_dis,"cp_prov","neant",1,temps,cp);
    }
  if (!lambda.non_nul() || ((!sub_type(Champ_Uniforme,lambda.valeur())) && (!sub_type(Champ_Fonc_Tabule,lambda.valeur()))))
    {
// cas particulier etait faux en VEF voir quand cela sert (FM slt) : sera nomme par milieu_base
      dis.discretiser_champ("champ_elem",zone_dis,"neant","neant",1,temps,lambda);
    }
  dis.discretiser_champ("vitesse", zone_dis,"rho_comme_v","kg/m3",1,temps,rho_comme_v);
  champs_compris_.ajoute_champ(rho_comme_v);
  dis.discretiser_champ("champ_elem",zone_dis,"mu_sur_Schmidt","kg/(m.s)",1,temps,mu_sur_Sc);
  champs_compris_.ajoute_champ(mu_sur_Sc);
  dis.discretiser_champ("champ_elem",zone_dis,"nu_sur_Schmidt","m2/s",1,temps,nu_sur_Sc);
  champs_compris_.ajoute_champ(nu_sur_Sc);
  Champ_Don& ptot = pression_tot();
  dis.discretiser_champ("champ_elem",zone_dis,"pression_tot","Pa",1,temps,ptot);
  champs_compris_.ajoute_champ(ptot);
  dis.discretiser_champ("temperature",zone_dis,"rho_gaz","kg/m3",1,temps,rho_gaz);
  champs_compris_.ajoute_champ(rho_gaz);
  Fluide_base::discretiser(pb,dis);
}
References Champs_compris::ajoute_champ(), Milieu_base::capacite_calorifique(), Cerr, Milieu_base::champs_compris_, Fluide_base::discretiser(), Discretisation_base::discretiser_champ(), Probleme_base::equation(), finl, Milieu_base::lambda, mu_sur_Sc, O_U_Ptr::non_nul(), nu_sur_Sc, pression_tot(), Milieu_base::rho, rho_comme_v, rho_gaz, Probleme_base::schema_temps(), sub_type, Schema_Temps_base::temps_courant(), Deriv_Champ_Don_base::valeur(), and Equation_base::zone_dis().
Referenced by Fluide_Quasi_Compressible::discretiser(), and Fluide_Weakly_Compressible::discretiser().
divu_discvit()
void Fluide_Dilatable_base::divu_discvit (DoubleTab & secmem1, DoubleTab & secmem2) inline
Definition at line 117 of file Fluide_Dilatable_base.h.
{ eos_tools_->divu_discvit(secmem1,secmem2); }
References eos_tools_.
get_champ()
const Champ_base & Fluide_Dilatable_base::get_champ (const Motcle & nom) const override virtual
Reimplemented from Milieu_base.
Definition at line 479 of file Fluide_Dilatable_base.cpp.
{
  REF(Champ_base) ref_champ;
  try
    {
      return Fluide_base::get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  try
    {
      return loi_etat_->get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  throw Champs_compris_erreur();
}
References Milieu_base::get_champ(), loi_etat_, and REF.
Referenced by Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), and Loi_Etat_Multi_GP_QC::calculer_masse_volumique().
get_info()
const Type_info * Fluide_Dilatable_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Milieu_base.
Reimplemented in Espece, Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
Definition at line 26 of file Fluide_Dilatable_base.cpp.
get_noms_champs_postraitables()
void Fluide_Dilatable_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Milieu_base.
Definition at line 499 of file Fluide_Dilatable_base.cpp.
{
  Fluide_base::get_noms_champs_postraitables(nom,opt);
  loi_etat_->get_noms_champs_postraitables(nom,opt);
}
References Milieu_base::get_noms_champs_postraitables(), and loi_etat_.
get_problem()
Probleme_base & Fluide_Dilatable_base::get_problem () inline
Definition at line 112 of file Fluide_Dilatable_base.h.
{ return le_probleme_.valeur(); }
References le_probleme_, and Ref_Probleme_base::valeur().
Referenced by Loi_Etat_Multi_GP_WC::update_Yn_values().
getTraitementPth()
int Fluide_Dilatable_base::getTraitementPth () const inline
Definition at line 105 of file Fluide_Dilatable_base.h.
{ return traitement_PTh; }
References traitement_PTh.
Referenced by EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), and EDO_Pression_th_VEF_Gaz_Parfait::resoudre().
inco_chaleur() [1/2]
Champ_Inc & Fluide_Dilatable_base::inco_chaleur () inline
Definition at line 84 of file Fluide_Dilatable_base.h.
{ return inco_chaleur_.valeur(); }
References inco_chaleur_, and Ref_Champ_Inc::valeur().
inco_chaleur() [2/2]
const Champ_Inc & Fluide_Dilatable_base::inco_chaleur () const inline
Definition at line 83 of file Fluide_Dilatable_base.h.
{ return inco_chaleur_.valeur(); }
References inco_chaleur_, and Ref_Champ_Inc::valeur().
Referenced by Loi_Etat_GR_base::calculer_Cp(), Loi_Etat_base::calculer_masse_volumique(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_base::calculer_mu_wilke(), EDO_Pression_th_VDF::completer(), EDO_Pression_th_VEF::completer(), Loi_Etat_GP_base::initialiser(), Loi_Etat_GR_base::initialiser(), Loi_Etat_GR_base::initialiser_inco_ch(), Loi_Etat_GP_base::remplir_T(), Loi_Etat_GR_base::remplir_T(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), and Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC().
info()
const Type_info * Fluide_Dilatable_base::info () static
Definition at line 26 of file Fluide_Dilatable_base.cpp.
initialiser()
int Fluide_Dilatable_base::initialiser (const double temps) override virtual
Initialise les parametres du fluide.
Reimplemented from Milieu_base.
Definition at line 412 of file Fluide_Dilatable_base.cpp.
{
  Cerr << "Fluide_Dilatable_base::initialiser()" << finl;
  if (sub_type(Champ_Don_base, rho))
    ref_cast(Champ_Don_base, rho).initialiser(temps);
  mu.initialiser(temps);
  lambda.initialiser(temps);
  Cp.initialiser(temps);
  update_rho_cp(temps);
  if (coeff_absorption_.non_nul() && indice_refraction_.non_nul())
    initialiser_radiatives(temps);
  return 1;
}
References Cerr, Fluide_base::coeff_absorption_, Milieu_base::Cp, finl, Fluide_base::indice_refraction_, Champ_Don::initialiser(), initialiser_radiatives(), Milieu_base::lambda, Fluide_base::mu, O_U_Ptr::non_nul(), ref_cast, Milieu_base::rho, sub_type, and update_rho_cp().
initialiser_inco_ch()
void Fluide_Dilatable_base::initialiser_inco_ch () inline
Definition at line 95 of file Fluide_Dilatable_base.h.
{ loi_etat_->initialiser_inco_ch(); }
References loi_etat_.
Referenced by completer().
initialiser_radiatives()
void Fluide_Dilatable_base::initialiser_radiatives (const double temps)
Definition at line 431 of file Fluide_Dilatable_base.cpp.
{
  coeff_absorption_.initialiser(temps);
  indice_refraction_.initialiser(temps);
  longueur_rayo_.initialiser(temps);
  if (sub_type(Champ_Uniforme,kappa().valeur()))
    longueur_rayo()->valeurs()(0,0)=1/(3*kappa()(0,0));
  else
    {
      DoubleTab& l_rayo = longueur_rayo_.valeurs();
      const DoubleTab& K = kappa().valeurs();
      for (int i=0; i<kappa().nb_valeurs_nodales(); i++)
        l_rayo[i] = 1/(3*K[i]);
    }
}
References Fluide_base::coeff_absorption_, Fluide_base::indice_refraction_, Champ_Don::initialiser(), Fluide_base::kappa(), Fluide_base::longueur_rayo(), Fluide_base::longueur_rayo_, Champ_Don::nb_valeurs_nodales(), sub_type, valeur(), and Champ_Don::valeurs().
Referenced by initialiser().
lire_motcle_non_standard()
int Fluide_Dilatable_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Milieu_base.
Reimplemented in Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
Definition at line 103 of file Fluide_Dilatable_base.cpp.
{
  Motcle motlu;
  if (mot=="loi_etat")
    {
      is>>loi_etat_;
      loi_etat_->associer_fluide(*this);
      return 1;
    }
  else if (mot=="mu")
    {
      is>>mu;
      mu->nommer("mu");
      return 1;
    }
  else if (mot=="sutherland")
    {
      double mu0,T0,C=-1,Slambda=-1;
      Nom prob;
      is>>prob;
      is>>motlu;
      if (motlu!="MU0") warn_syntax_Sutherland();
      is>>mu0;
      is>>motlu;
      if (motlu!="T0") warn_syntax_Sutherland();
      is>>T0;
      is>>motlu;
      if (motlu=="SLAMBDA")
        {
          is >> Slambda;
          is >> motlu;
        }
      if (motlu!="C") warn_syntax_Sutherland();
      is>>C;
      mu.typer("Sutherland");
      Sutherland& mu_suth = ref_cast(Sutherland,mu.valeur());
      mu_suth.set_val_params(prob,mu0,C,T0);
      mu_suth.lire_expression();
// On stocke la valeur de C (ici Slambda) pour construire(cf creer_champs_non_lus())
// la loi de Sutherland qui concerne la conductivite
      if (Slambda!=-1)
        {
          lambda.typer("Sutherland");
          Sutherland& lambda_suth = ref_cast(Sutherland,lambda.valeur());
          lambda_suth.set_prob(prob);
          lambda_suth.set_Tref(T0);
          lambda_suth.set_C(Slambda);
        }
      return 1;
    }
  else if ((mot=="beta_th") || (mot=="beta_co"))
    {
      Cerr<<"The keyword "<<mot<<" has not to be read for a "<<que_suis_je()<<" type medium."<<finl;
      Cerr<<"Please remove it from your data set."<<finl;
      Process::exit();
      return -1;
    }
  else return Fluide_base::lire_motcle_non_standard(mot,is);
}
References Cerr, Process::exit(), finl, Milieu_base::lambda, Sutherland::lire_expression(), Milieu_base::lire_motcle_non_standard(), loi_etat_, Fluide_base::mu, Objet_U::nommer(), Objet_U::que_suis_je(), ref_cast, Sutherland::set_C(), Sutherland::set_prob(), Sutherland::set_Tref(), Sutherland::set_val_params(), Deriv_::typer(), Deriv_Champ_Don_base::valeur(), and warn_syntax_Sutherland().
Referenced by Fluide_Quasi_Compressible::lire_motcle_non_standard(), and Fluide_Weakly_Compressible::lire_motcle_non_standard().
loi_etat() [1/2]
Loi_Etat & Fluide_Dilatable_base::loi_etat () inline
Definition at line 82 of file Fluide_Dilatable_base.h.
{ return loi_etat_; }
References loi_etat_.
loi_etat() [2/2]
const Loi_Etat & Fluide_Dilatable_base::loi_etat () const inline
Definition at line 81 of file Fluide_Dilatable_base.h.
{ return loi_etat_; }
References loi_etat_.
Referenced by abortTimeStep(), Convection_Diffusion_Espece_Binaire_QC::completer(), Convection_Diffusion_Espece_Multi_QC::completer(), Convection_Diffusion_Espece_Binaire_WC::completer(), Convection_Diffusion_Espece_Multi_WC::completer(), Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), EDO_Pression_th_VDF::masse_totale(), EDO_Pression_th_VEF::masse_totale(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), EOS_Tools_VDF::secmembre_divU_Z(), and EOS_Tools_VEF::secmembre_divU_Z().
mettre_a_jour()
void Fluide_Dilatable_base::mettre_a_jour (double temps) override virtual
< Note : it denotes the species Y1 for Pb_Hydraulique_Melange_Binaire_QC
< si besoin (i.e. QC)
Reimplemented from Milieu_base.
Definition at line 505 of file Fluide_Dilatable_base.cpp.
{
  rho.mettre_a_jour(temps);
  ch_temperature().mettre_a_jour(temps); //!< Note : it denotes the species Y1 for Pb_Hydraulique_Melange_Binaire_QC
  rho->changer_temps(temps);
  ch_temperature()->changer_temps(temps);
  mu->changer_temps(temps);
  lambda->changer_temps(temps);
  Cp.mettre_a_jour(temps);
  update_rho_cp(temps);
  write_mean_edo(temps); //!< si besoin (i.e. QC)
}
References ch_temperature(), Champ::changer_temps(), Milieu_base::Cp, Milieu_base::lambda, Champ_Don::mettre_a_jour(), Champ::mettre_a_jour(), Fluide_base::mu, Milieu_base::rho, update_rho_cp(), and write_mean_edo().
moyenne_vol()
double Fluide_Dilatable_base::moyenne_vol (const DoubleTab & A) const inline
Definition at line 118 of file Fluide_Dilatable_base.h.
{ return eos_tools_->moyenne_vol(A); }
References eos_tools_.
Referenced by Source_QC_Gravite_VEF::ajouter(), and Source_QC_Gravite_VDF::ajouter_blocs().
mu_sur_Schmidt() [1/2]
Champ_Don & Fluide_Dilatable_base::mu_sur_Schmidt () inline
Definition at line 89 of file Fluide_Dilatable_base.h.
{ return mu_sur_Sc; }
References mu_sur_Sc.
mu_sur_Schmidt() [2/2]
const Champ_Don & Fluide_Dilatable_base::mu_sur_Schmidt () const inline
Definition at line 88 of file Fluide_Dilatable_base.h.
{ return mu_sur_Sc; }
References mu_sur_Sc.
Referenced by Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Convection_Diffusion_Espece_Multi_QC::diffusivite_pour_pas_de_temps(), and Convection_Diffusion_Fluide_Dilatable_base::diffusivite_pour_transport().
nu_sur_Schmidt() [1/2]
Champ_Don & Fluide_Dilatable_base::nu_sur_Schmidt () inline
Definition at line 91 of file Fluide_Dilatable_base.h.
{ return nu_sur_Sc; }
References nu_sur_Sc.
nu_sur_Schmidt() [2/2]
const Champ_Don & Fluide_Dilatable_base::nu_sur_Schmidt () const inline
Definition at line 90 of file Fluide_Dilatable_base.h.
{ return nu_sur_Sc; }
References nu_sur_Sc.
Referenced by Loi_Etat_Binaire_GP_base::calculer_nu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_nu_sur_Sc(), Convection_Diffusion_Espece_Binaire_base::diffusivite_pour_pas_de_temps(), and Convection_Diffusion_Espece_Multi_WC::diffusivite_pour_pas_de_temps().
prepare_pressure_edo()
virtual void Fluide_Dilatable_base::prepare_pressure_edo () pure virtual
Implemented in Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
Referenced by preparer_calcul().
preparer_calcul()
void Fluide_Dilatable_base::preparer_calcul (void) override virtual
Prepare le fluide au calcul.
< Child can have an overload
< si besoin (i.e. QC)
Reimplemented from Milieu_base.
Definition at line 532 of file Fluide_Dilatable_base.cpp.
{
  Cerr << "Fluide_Dilatable_base::preparer_calcul()" << finl;
  Milieu_base::preparer_calcul();
  Fluide_Dilatable_base::update_pressure_fields(le_probleme_->schema_temps().temps_courant()); //!< Child can have an overload
  loi_etat_->preparer_calcul();
  prepare_pressure_edo(); //!< si besoin (i.e. QC)
  calculer_coeff_T();
}
References calculer_coeff_T(), Cerr, finl, le_probleme_, loi_etat_, prepare_pressure_edo(), Milieu_base::preparer_calcul(), Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), and update_pressure_fields().
Referenced by Pb_Dilatable_base::preparer_calcul().
preparer_pas_temps()
void Fluide_Dilatable_base::preparer_pas_temps () virtual
Prepare le pas de temps.
Reimplemented in Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
Definition at line 329 of file Fluide_Dilatable_base.cpp.
{
  loi_etat_->mettre_a_jour(le_probleme_->schema_temps().temps_courant());
  eos_tools_->mettre_a_jour(le_probleme_->schema_temps().temps_courant());
}
References eos_tools_, le_probleme_, loi_etat_, Probleme_base::schema_temps(), and Schema_Temps_base::temps_courant().
Referenced by Pb_Dilatable_base::initTimeStep(), Fluide_Quasi_Compressible::preparer_pas_temps(), and Fluide_Weakly_Compressible::preparer_pas_temps().
pression_th()
double Fluide_Dilatable_base::pression_th () const inline
Pression thermodynamique.
Definition at line 106 of file Fluide_Dilatable_base.h.
References Pth_.
Referenced by Source_QC_Chaleur::ajouter_(), Loi_Etat_GR_base::calculer_Cp(), Loi_Etat_base::calculer_masse_volumique(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), EDO_Pression_th_VDF::completer(), EDO_Pression_th_VEF::completer(), Loi_Etat_GR_base::initialiser(), Loi_Etat_GR_base::initialiser_inco_ch(), Loi_Etat_GR_base::inverser_Pth(), Loi_Etat_GR_base::remplir_T(), and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder().
pression_th1()
double Fluide_Dilatable_base::pression_th1 () const inline
Pression thermodynamique calculee pour conserver la masse.
Definition at line 108 of file Fluide_Dilatable_base.h.
References Pth1.
pression_thn()
double Fluide_Dilatable_base::pression_thn () const inline
Pression thermodynamique a l'etape precedente.
Definition at line 107 of file Fluide_Dilatable_base.h.
References Pth_n.
Referenced by Source_QC_Chaleur::ajouter_().
pression_tot() [1/2]
Champ_Don & Fluide_Dilatable_base::pression_tot () inline
Definition at line 87 of file Fluide_Dilatable_base.h.
{ return pression_tot_; }
References pression_tot_.
pression_tot() [2/2]
const Champ_Don & Fluide_Dilatable_base::pression_tot () const inline
Definition at line 86 of file Fluide_Dilatable_base.h.
{ return pression_tot_; }
References pression_tot_.
Referenced by discretiser().
printOn()
Sortie & Fluide_Dilatable_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Milieu_base.
Reimplemented in Espece, Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
Definition at line 31 of file Fluide_Dilatable_base.cpp.
{
  Fluide_base::ecrire(os);
  return os;
}
References Milieu_base::ecrire().
readOn()
Entree & Fluide_Dilatable_base::readOn (Entree & is) override protected virtual
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Milieu_base.
Reimplemented in Espece, Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
Definition at line 37 of file Fluide_Dilatable_base.cpp.
{
  Fluide_base::readOn(is);
  return is;
}
References Fluide_base::readOn().
Referenced by Fluide_Quasi_Compressible::readOn(), and Fluide_Weakly_Compressible::readOn().
remplir_champ_pression_tot()
virtual void Fluide_Dilatable_base::remplir_champ_pression_tot (int n, const DoubleTab & PHydro, DoubleTab & PTot) protected pure virtual
Implemented in Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
Referenced by calculer_pression_tot().
rho_discvit()
const DoubleTab & Fluide_Dilatable_base::rho_discvit () const inline
Definition at line 113 of file Fluide_Dilatable_base.h.
{ return eos_tools_->rho_discvit(); }
References eos_tools_.
Referenced by Source_QC_Gravite_VEF::ajouter(), Source_QC_Gravite_VDF::ajouter_blocs(), Navier_Stokes_Fluide_Dilatable_base::initTimeStep(), and Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star().
rho_face_n()
const DoubleTab & Fluide_Dilatable_base::rho_face_n () const inline
Definition at line 114 of file Fluide_Dilatable_base.h.
{ return eos_tools_->rho_face_n(); }
References eos_tools_.
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), and Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries().
rho_face_np1()
const DoubleTab & Fluide_Dilatable_base::rho_face_np1 () const inline
Definition at line 115 of file Fluide_Dilatable_base.h.
{ return eos_tools_->rho_face_np1(); }
References eos_tools_.
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), diviser_par_rho_np1_face(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries(), and Frontiere_ouverte_rho_u_impose::val_imp_au_temps().
rho_n()
const DoubleTab & Fluide_Dilatable_base::rho_n () const inline
Definition at line 92 of file Fluide_Dilatable_base.h.
{ return loi_etat_->rho_n(); }
References loi_etat_.
Referenced by EOS_Tools_VEF::rho_face_n().
rho_np1()
const DoubleTab & Fluide_Dilatable_base::rho_np1 () const inline
Definition at line 93 of file Fluide_Dilatable_base.h.
{ return loi_etat_->rho_np1(); }
References loi_etat_.
Referenced by Fluide_Weakly_Compressible::calculer_pression_hydro(), and EOS_Tools_VEF::rho_face_np1().
secmembre_divU_Z()
virtual void Fluide_Dilatable_base::secmembre_divU_Z (DoubleTab &) const pure virtual
Implemented in Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Piso::iterer_NS(), Simple::iterer_NS(), and Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star().
self_cast() [1/2]
const Fluide_Dilatable_base & Fluide_Dilatable_base::self_cast (const Objet_U & r) static
Definition at line 26 of file Fluide_Dilatable_base.cpp.
self_cast() [2/2]
Fluide_Dilatable_base & Fluide_Dilatable_base::self_cast (Objet_U & r) static
Definition at line 26 of file Fluide_Dilatable_base.cpp.
set_Cp()
void Fluide_Dilatable_base::set_Cp (double Cp_)
Complete le fluide avec un Cp constant.
Definition at line 244 of file Fluide_Dilatable_base.cpp.
{
  Cp.typer("Champ_Uniforme");
  Champ_Uniforme& ch_Cp = ref_cast(Champ_Uniforme,Cp.valeur());
  ch_Cp.dimensionner(1,1);
  DoubleTab& tab_Cp = Cp.valeurs();
  tab_Cp(0,0) = Cp_;
}
References Milieu_base::Cp, Champ_Don_base::dimensionner(), ref_cast, Deriv_::typer(), Deriv_Champ_Don_base::valeur(), and Champ_Don::valeurs().
Referenced by Loi_Etat_GP_base::associer_fluide().
set_param()
void Fluide_Dilatable_base::set_param (Param & param) override virtual
Reimplemented from Milieu_base.
Reimplemented in Espece, Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
Definition at line 87 of file Fluide_Dilatable_base.cpp.
{
  Fluide_base::set_param(param);
  param.ajouter_non_std("loi_etat",(this),Param::REQUIRED);
  param.ajouter_non_std("Traitement_PTh",(this));
// Lecture de mu et lambda pas specifiee obligatoire car option sutherland possible
// On supprime.. et on ajoute non-standard
  param.supprimer("mu");
  param.ajouter_non_std("mu",(this));
  param.ajouter_non_std("sutherland",(this));
  param.supprimer("beta_th");
  param.ajouter_non_std("beta_th",(this));
  param.supprimer("beta_co");
  param.ajouter_non_std("beta_co",(this));
}
References Param::ajouter_non_std(), Param::REQUIRED, Fluide_base::set_param(), and Param::supprimer().
Referenced by Fluide_Quasi_Compressible::set_param(), and Fluide_Weakly_Compressible::set_param().
set_pression_th()
void Fluide_Dilatable_base::set_pression_th (double Pth) inline
Definition at line 104 of file Fluide_Dilatable_base.h.
{ Pth_n = Pth_ = Pth; }
References Pth_, and Pth_n.
Referenced by Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre().
temperature()
const DoubleTab & Fluide_Dilatable_base::temperature () const
Renvoie le tableau des valeurs de le temperature.
Definition at line 286 of file Fluide_Dilatable_base.cpp.
{
  return ch_temperature().valeurs();
}
References ch_temperature(), and Champ_Don::valeurs().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl().
type_fluide()
const Nom Fluide_Dilatable_base::type_fluide () const inline
Definition at line 80 of file Fluide_Dilatable_base.h.
{ return loi_etat_->type_fluide(); }
References loi_etat_.
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::domaine_application(), Pb_Dilatable_base::preparer_calcul(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::readOn(), Convection_Diffusion_Espece_Binaire_base::readOn(), and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre().
update_pressure_fields()
void Fluide_Dilatable_base::update_pressure_fields (double temps) virtual
Reimplemented in Fluide_Weakly_Compressible.
Definition at line 542 of file Fluide_Dilatable_base.cpp.
{
  calculer_pression_tot();
  pression_tot_.mettre_a_jour(temps);
}
References calculer_pression_tot(), Champ_Don::mettre_a_jour(), and pression_tot_.
Referenced by preparer_calcul(), Pb_Dilatable_base::update_pressure_fields(), and Fluide_Weakly_Compressible::update_pressure_fields().
update_rho_cp()
void Fluide_Dilatable_base::update_rho_cp (double temps) override virtual
Reimplemented from Milieu_base.
Definition at line 253 of file Fluide_Dilatable_base.cpp.
{
  rho_cp_comme_T_.changer_temps(temps);
  rho_cp_comme_T_.valeur().changer_temps(temps);
  DoubleTab& rho_cp = rho_cp_comme_T_.valeurs();
  if (sub_type(Champ_Uniforme,rho))
    rho_cp = rho.valeurs()(0, 0);
  else
    {
// AB: rho_cp = rho.valeurs() turns rho_cp into a 2 dimensional array with 1 compo. We want to stay mono-dim:
      rho_cp = 1.;
      tab_multiply_any_shape(rho_cp, rho.valeurs());
    }
  if (sub_type(Champ_Uniforme, Cp.valeur()))
    rho_cp *= Cp.valeurs()(0, 0);
  else
    tab_multiply_any_shape(rho_cp,Cp.valeurs());
}
References Champ_base::changer_temps(), Champ_Fonc::changer_temps(), Milieu_base::Cp, Milieu_base::rho, Milieu_base::rho_cp_comme_T_, sub_type, tab_multiply_any_shape(), Deriv_Champ_Don_base::valeur(), Deriv_Champ_Fonc_base::valeur(), Champ::valeurs(), Champ_Don::valeurs(), and Champ_Fonc::valeurs().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), initialiser(), and mettre_a_jour().
verifier_coherence_champs()
void Fluide_Dilatable_base::verifier_coherence_champs (int & err, Nom & message) override virtual
Verifie que les champs lus l'ont ete correctement.
Reimplemented from Milieu_base.
Reimplemented in Espece.
Definition at line 189 of file Fluide_Dilatable_base.cpp.
{
  msg="";
  if (rho.non_nul()) { }
  else
    {
      msg += "The density rho has not been specified. \n";
      err = 1;
    }
  if (mu.non_nul())
    {
      if (sub_type(Champ_Uniforme,mu.valeur()))
        {
          if (mu(0,0) <= 0)
            {
              msg += "The dynamical viscosity mu is not striclty positive. \n";
              err = 1;
            }
        }
    }
  else
    {
      msg += "The dynamical viscosity mu has not been specified. \n";
      err = 1;
    }
  if (lambda.non_nul()) { }
  else
    {
      msg += "The conductivity lambda has not been specified. \n";
      err = 1;
    }
  if (Cp.non_nul()) { }
  else
    {
      msg += "The heat capacity Cp has not been specified. \n";
      err = 1;
    }
  Milieu_base::verifier_coherence_champs(err,msg);
}
References Milieu_base::Cp, Milieu_base::lambda, Fluide_base::mu, O_U_Ptr::non_nul(), Milieu_base::rho, sub_type, Deriv_Champ_Don_base::valeur(), and Milieu_base::verifier_coherence_champs().
vitesse()
const Champ_Inc & Fluide_Dilatable_base::vitesse () const inline
Definition at line 85 of file Fluide_Dilatable_base.h.
{ return vitesse_.valeur(); }
References Ref_Champ_Inc::valeur(), and vitesse_.
Referenced by Loi_Etat_GP_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_alpha(), Loi_Etat_base::calculer_nu(), Loi_Etat_Multi_GP_base::calculer_tab_mu(), multiplier_diviser_rho(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), EOS_Tools_VDF::secmembre_divU_Z(), and EOS_Tools_VEF::secmembre_divU_Z().
warn_syntax_Sutherland()
void Fluide_Dilatable_base::warn_syntax_Sutherland ()
Definition at line 165 of file Fluide_Dilatable_base.cpp.
{
  Cerr << "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" << finl;
  Cerr << "Error in call to Sutherland function :" << finl;
  Cerr << "The syntax has changed in version 1.8.4." << finl;
  Cerr << finl << "  A specification of kind : sutherland problem_name mu0 1.85e-5 T0 300 [Slambda 10] C 10 was expected. "<<finl;
  Cerr << finl << "Please update your dataset or contact TRUST support team." << finl;
  Process::exit();
}
References Cerr, Process::exit(), and finl.
Referenced by lire_motcle_non_standard().
write_mean_edo()
virtual void Fluide_Dilatable_base::write_mean_edo (double) pure virtual
Implemented in Fluide_Quasi_Compressible, and Fluide_Weakly_Compressible.
Referenced by mettre_a_jour().
Member Data Documentation
eos_tools_
EOS_Tools Fluide_Dilatable_base::eos_tools_ protected
Definition at line 128 of file Fluide_Dilatable_base.h.
Referenced by calculer_rho_face(), completer(), divu_discvit(), moyenne_vol(), Fluide_Quasi_Compressible::prepare_pressure_edo(), preparer_pas_temps(), rho_discvit(), rho_face_n(), rho_face_np1(), Fluide_Quasi_Compressible::secmembre_divU_Z(), Fluide_Weakly_Compressible::secmembre_divU_Z(), and Fluide_Quasi_Compressible::write_mean_edo().
inco_chaleur_
Ref_Champ_Inc Fluide_Dilatable_base::inco_chaleur_ protected
Definition at line 124 of file Fluide_Dilatable_base.h.
Referenced by completer(), inco_chaleur(), and Fluide_Quasi_Compressible::write_mean_edo().
info_obj
const Type_info Fluide_Dilatable_base::info_obj static
Definition at line 42 of file Fluide_Dilatable_base.h.
le_probleme_
Ref_Probleme_base Fluide_Dilatable_base::le_probleme_ protected
Definition at line 125 of file Fluide_Dilatable_base.h.
Referenced by completer(), get_problem(), Fluide_Weakly_Compressible::mettre_a_jour_bis(), Fluide_Quasi_Compressible::prepare_pressure_edo(), preparer_calcul(), preparer_pas_temps(), and Fluide_Weakly_Compressible::remplir_champ_pression_for_EOS().
loi_etat_
Loi_Etat Fluide_Dilatable_base::loi_etat_ protected
Definition at line 127 of file Fluide_Dilatable_base.h.
Referenced by calculer_alpha(), calculer_coeff_T(), calculer_Cp(), calculer_H(), calculer_lambda(), calculer_masse_volumique(), calculer_mu(), calculer_mu_sur_Sc(), calculer_nu(), calculer_nu_sur_Sc(), ch_temperature(), completer(), Fluide_Quasi_Compressible::completer(), Fluide_Quasi_Compressible::completer_edo(), creer_champs_non_lus(), get_champ(), get_noms_champs_postraitables(), initialiser_inco_ch(), lire_motcle_non_standard(), loi_etat(), preparer_calcul(), preparer_pas_temps(), rho_n(), rho_np1(), and type_fluide().
mu_sur_Sc
Champ_Don Fluide_Dilatable_base::mu_sur_Sc protected
Definition at line 126 of file Fluide_Dilatable_base.h.
Referenced by discretiser(), and mu_sur_Schmidt().
nu_sur_Sc
Champ_Don Fluide_Dilatable_base::nu_sur_Sc protected
Definition at line 126 of file Fluide_Dilatable_base.h.
Referenced by discretiser(), and nu_sur_Schmidt().
pression_
Ref_Champ_Inc Fluide_Dilatable_base::pression_ protected
Definition at line 124 of file Fluide_Dilatable_base.h.
Referenced by Fluide_Weakly_Compressible::calculer_pression_hydro(), calculer_pression_tot(), and completer().
pression_tot_
Champ_Don Fluide_Dilatable_base::pression_tot_ protected
Definition at line 126 of file Fluide_Dilatable_base.h.
Referenced by calculer_pression_tot(), pression_tot(), and update_pressure_fields().
Pth1
double Fluide_Dilatable_base::Pth1 protected
Definition at line 123 of file Fluide_Dilatable_base.h.
Referenced by pression_th1().
Pth_
double Fluide_Dilatable_base::Pth_ protected
Definition at line 123 of file Fluide_Dilatable_base.h.
Referenced by abortTimeStep(), calculer_H(), Fluide_Quasi_Compressible::completer(), Fluide_Weakly_Compressible::completer(), Fluide_Quasi_Compressible::completer_edo(), Fluide_Weakly_Compressible::initialiser_pth(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), Fluide_Quasi_Compressible::preparer_pas_temps(), pression_th(), Fluide_Weakly_Compressible::remplir_champ_pression_for_EOS(), Fluide_Quasi_Compressible::remplir_champ_pression_tot(), Fluide_Weakly_Compressible::remplir_champ_pression_tot(), Fluide_Quasi_Compressible::Resoudre_EDO_PT(), Fluide_Weakly_Compressible::set_param(), set_pression_th(), and Fluide_Quasi_Compressible::write_mean_edo().
Pth_n
double Fluide_Dilatable_base::Pth_n protected
Definition at line 123 of file Fluide_Dilatable_base.h.
Referenced by abortTimeStep(), Fluide_Weakly_Compressible::completer(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), pression_thn(), Fluide_Quasi_Compressible::Resoudre_EDO_PT(), and set_pression_th().
rho_comme_v
Champ_Don Fluide_Dilatable_base::rho_comme_v protected
Definition at line 126 of file Fluide_Dilatable_base.h.
Referenced by discretiser().
rho_gaz
Champ_Don Fluide_Dilatable_base::rho_gaz protected
Definition at line 126 of file Fluide_Dilatable_base.h.
Referenced by discretiser().
traitement_PTh
int Fluide_Dilatable_base::traitement_PTh protected
flag pour le traitement de la pression thermo
Definition at line 122 of file Fluide_Dilatable_base.h.
Referenced by Fluide_Quasi_Compressible::checkTraitementPth(), Fluide_Quasi_Compressible::completer(), Fluide_Quasi_Compressible::completer_edo(), getTraitementPth(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), Fluide_Weakly_Compressible::lire_motcle_non_standard(), Fluide_Quasi_Compressible::prepare_pressure_edo(), Fluide_Quasi_Compressible::preparer_pas_temps(), Fluide_Quasi_Compressible::Resoudre_EDO_PT(), and Fluide_Quasi_Compressible::write_mean_edo().
vitesse_
Ref_Champ_Inc Fluide_Dilatable_base::vitesse_ protected
Definition at line 124 of file Fluide_Dilatable_base.h.
Referenced by completer(), Fluide_Quasi_Compressible::secmembre_divU_Z(), and vitesse().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Milieu/Fluide_Dilatable_base.h
src/ThHyd/Dilatable/Common/Milieu/Fluide_Dilatable_base.cpp