TRUST: LecFicDiffuse_JDD Class Reference
LecFicDiffuse_JDD Class Reference
Cette classe implemente les operateurs et les methodes virtuelles de la classe EFichier de la facon suivante :
Le fichier a lire est physiquement localise sur le disque de la machine hebergeant la tache maitre de l'application Trio-U (le processus de rang 0 dans le groupe "tous")
et chaque item lu dans ce fichier est diffuse a tous les autres processus du groupe tous.
Il en est de meme pour les methodes d'inspection de l'etat d'un fichier.
#include <LecFicDiffuse_JDD.h>
Public Member Functions
~LecFicDiffuse_JDD ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
LecFicDiffuse_JDD ()
LecFicDiffuse_JDD (const char *name, std::_Ios_Openmode mode=ios::in, bool apply_verification=true)
ouverture du fichier name. Cette methode
doit etre appelee sur tous les processeurs. En cas
d'echec : exit()
int ouvrir (const char *name, std::_Ios_Openmode mode=ios::in) override
Ouverture du fichier. Cette methode doit etre appelee
par tous les processeurs du groupe.
Valeur de retour: 1 si ok, 0 sinon.
Entree & get_entree_master () override
Public Member Functions inherited from Lec_Diffuse_base
~Lec_Diffuse_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & operator>> (int &ob) override
Entree & operator>> (long &ob) override
Entree & operator>> (float &ob) override
Entree & operator>> (double &ob) override
int get (int *ob, int n) override
int get (long *ob, int n) override
int get (float *ob, int n) override
int get (double *ob, int n) override
int get (char *buf, int bufsize) override
Lecture d'une chaine dans ostream_
bufsize est la taille du buffer alloue pour ob (y compris
le caractere 0 final).
La chaine contient toujours un 0 meme en cas d'echec.
La methode renvoie 1 si la lecture est bonne, 0 sinon.
Si le buffer est trop petit, pour l'instant on fait exit() mais
par la suite on pourra tester: si strlen(ob)==bufsize-1, alors
refaire lire() jusqu'a arriver au bout. Si le lire() suivant
renvoie une chaine de longueur nulle, cela signifie que la taille de la
chaine etait exactement bufsize-1.
Attention: le comportement est different en binaire et en ascii.
En binaire, on lit la chaine jusqu'au prochain '\0'.
En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
int eof () override
int good () override
int fail () override
int set_bin (int bin) override
appelle get_entree_master().set_bin(bin)
void set_check_types (int flag) override
appelle get_entree_master().set_check_types(flag)
void set_diffuse (int diffuse) override
ToDo TMA : commenter.
Public Member Functions inherited from EFichier
EFichier ()
~EFichier ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
EFichier (const char *name, std::_Ios_Openmode mode=ios::in)
Public Member Functions inherited from Entree_Fichier_base
~Entree_Fichier_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree_Fichier_base ()
Entree_Fichier_base (const Entree_Fichier_base &)=default
Entree_Fichier_base (const char *name, std::_Ios_Openmode mode=ios::in)
ifstream & get_ifstream ()
void close ()
int eof () override
int fail () override
int good () override
void precision (int pre)
void setf (std::_Ios_Fmtflags code)
virtual int ouvrir (const char *name, std::_Ios_Openmode mode=ios::in)
Public Member Functions inherited from Entree
Entree ()
Entree (istream &is)
Entree (const Entree &is)
Entree & operator= (istream &is)
Entree & operator= (Entree &is)
virtual istream & get_istream ()
virtual const istream & get_istream () const
void set_istream (istream *is)
void set_different_int_size (bool is_different_int_size)
Entree & operator>> (Entree &(*f)(Entree &))
Entree & operator>> (istream &(*f)(istream &))
Entree & operator>> (ios &(*f)(ios &))
virtual Entree & operator>> (int &ob)
virtual Entree & operator>> (long &ob)
virtual Entree & operator>> (float &ob)
virtual Entree & operator>> (double &ob)
virtual int get (int *ob, int n)
virtual int get (long *ob, int n)
virtual int get (float *ob, int n)
virtual int get (double *ob, int n)
virtual int get (char *buf, int bufsize)
Lecture d'une chaine dans ostream_
bufsize est la taille du buffer alloue pour ob (y compris
le caractere 0 final).
La chaine contient toujours un 0 meme en cas d'echec.
La methode renvoie 1 si la lecture est bonne, 0 sinon.
Si le buffer est trop petit, pour l'instant on fait exit() mais
par la suite on pourra tester: si strlen(ob)==bufsize-1, alors
refaire lire() jusqu'a arriver au bout. Si le lire() suivant
renvoie une chaine de longueur nulle, cela signifie que la taille de la
chaine etait exactement bufsize-1.
Attention: le comportement est different en binaire et en ascii.
En binaire, on lit la chaine jusqu'au prochain '\0'.
En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
virtual int eof ()
virtual int fail ()
virtual int good ()
virtual ~Entree ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand.
int is_bin () const
virtual void set_check_types (int flag)
indique si le stream doit verifier les types des objets lus<br>(ints et nombres flottants). Exemple : l'entree contient 123.456 123.456
int i;
check_types(0);
is >> i; // i contient 123
check_types(1);
is >> i; // Erreur : on lit la chaine 123.456 et on essaye de la convertir en int
Voir operator>>(int &)
int check_types () const
renvoie la valeur actuelle du drapeau, voir set_check_types()
virtual void set_error_action (Error_Action)
Change le comportement en cas d'erreur de l'entree,
voir error_handle_() et get_error_action()
Error_Action get_error_action ()
renvoie error_action_ pour cette entree<br>(permet de la modifier et de restaurer ensuite la valeur anterieure)
operator istream & ()
istream & putback (char ch)
istream & ignore (int n=1, int delim=EOF)
int get_diffuse ()
virtual void set_diffuse (int diffuse)
ToDo TMA : commenter.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static LecFicDiffuse_JDD & self_cast (Objet_U &)
static const LecFicDiffuse_JDD & self_cast (const Objet_U &)
Static Public Member Functions inherited from Lec_Diffuse_base
static const Type_info * info ()
static Lec_Diffuse_base & self_cast (Objet_U &)
static const Lec_Diffuse_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from EFichier
static Objet_U * cree_instance ()
static const Type_info * info ()
static EFichier & self_cast (Objet_U &)
static const EFichier & self_cast (const Objet_U &)
Static Public Member Functions inherited from Entree_Fichier_base
static const Type_info * info ()
static Entree_Fichier_base & self_cast (Objet_U &)
static const Entree_Fichier_base & self_cast (const Objet_U &)
static bool Can_be_read (const char *name)
Return True if the file can be opened for reading, false otherwise.
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Lec_Diffuse_base
static const Type_info info_obj
Static Public Attributes inherited from EFichier
static const Type_info info_obj
Static Public Attributes inherited from Entree_Fichier_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Lec_Diffuse_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Lec_Diffuse_base ()
ne fait rien (constructeur protege car c'est une classe de base)
Lec_Diffuse_base (const Lec_Diffuse_base &)=default
Lec_Diffuse_base & operator= (const Lec_Diffuse_base &)
erreur
virtual Entree & get_entree_master ()=0
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Entree
int error_handle (int fail_flag)
virtual int error_handle_ (int fail_flag)
Cette fonction est appellee par operateur>>, get, get_nom
ouvrir, fermer, lire, etc... en cas d'echec (lorsque fail() est mis)
Elle renvoie 0 s'il y a eu une erreur (passer par error_handle() qui
traite en inline le cas ou il n'y a pas d'erreur), et 1 s'il n'y a pas
d'erreur.
(par commodite de codage des methodes qui l'utilisent, on
ecrira "return error_handle(fail());"
Elle peut etre configuree pour
- renvoyer "0" en cas d'erreur et continuer l'execution du code
(cas d'un ancien code qui ne gere pas les exceptions mais teste
le drapeau fail() de temps en temps)
Dans ce cas les methodes operator>> continuent l'execution du code
meme en cas d'echec, le contenu des variables lues est indefini !
- faire Process::exit() (cas d'une portion de code dans laquelle
on ne veut pas faire de gestion d'erreur du tout et ou on suppose
que tout va toujours bien)
- lever une exception (permet une gestion rigoureuse des erreurs
et une information utilisateur optimale en fonction du contexte)
Voir aussi set_error_action()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
EChaine chaine_
bool apply_verif
Protected Attributes inherited from Entree_Fichier_base
ifstream * ifstream_
Protected Attributes inherited from Entree
int bin_
bool is_different_int_size_
File with int32 (or int64) whereas version is int64 (or int32)
int check_types_
Error_Action error_action_
int diffuse_
By default 1, but some child classes (eg: LecFicDiffuse) could set temporary to 0 to not diffuse to other processes.
Additional Inherited Members
Public Types inherited from Entree
enum Error_Action { ERROR_EXIT , ERROR_CONTINUE , ERROR_EXCEPTION }
Detailed Description
Cette classe implemente les operateurs et les methodes virtuelles de la classe EFichier de la facon suivante :
Le fichier a lire est physiquement localise sur le disque de la machine hebergeant la tache maitre de l'application Trio-U (le processus de rang 0 dans le groupe "tous")
et chaque item lu dans ce fichier est diffuse a tous les autres processus du groupe tous.
Il en est de meme pour les methodes d'inspection de l'etat d'un fichier.
Definition at line 34 of file LecFicDiffuse_JDD.h.
Constructor & Destructor Documentation
~LecFicDiffuse_JDD()
LecFicDiffuse_JDD::~LecFicDiffuse_JDD ()
Definition at line 22 of file LecFicDiffuse_JDD.cpp.
LecFicDiffuse_JDD() [1/2]
LecFicDiffuse_JDD::LecFicDiffuse_JDD ()
Definition at line 36 of file LecFicDiffuse_JDD.cpp.
                                     :
  apply_verif(true)
{
// file_.set_error_action(ERROR_CONTINUE);
}
LecFicDiffuse_JDD() [2/2]
LecFicDiffuse_JDD::LecFicDiffuse_JDD (const char * name, std::_Ios_Openmode mode = ios::in, bool apply_verification = true)
ouverture du fichier name. Cette methode
doit etre appelee sur tous les processeurs. En cas
d'echec : exit()
Definition at line 45 of file LecFicDiffuse_JDD.cpp.
                                                              :
  apply_verif(apply_verification)
{
// file_.set_error_action(ERROR_CONTINUE);
  int ok = ouvrir(name, mode);
  if (!ok && Process::je_suis_maitre())
    {
      Cerr << "File " << name << " does not exist (LecFicDiffuse_JDD)" << finl;
      Process::exit();
    }
}
References Cerr, Process::exit(), finl, Process::je_suis_maitre(), and ouvrir().
Member Function Documentation
cree_instance()
Objet_U * LecFicDiffuse_JDD::cree_instance () static
Definition at line 22 of file LecFicDiffuse_JDD.cpp.
duplique()
int LecFicDiffuse_JDD::duplique () const override virtual
Reimplemented from EFichier.
Definition at line 22 of file LecFicDiffuse_JDD.cpp.
get_entree_master()
Entree & LecFicDiffuse_JDD::get_entree_master () override virtual
Implements Lec_Diffuse_base.
Definition at line 195 of file LecFicDiffuse_JDD.cpp.
{
  return chaine_;
}
References chaine_.
get_info()
const Type_info * LecFicDiffuse_JDD::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Lec_Diffuse_base.
Definition at line 22 of file LecFicDiffuse_JDD.cpp.
info()
const Type_info * LecFicDiffuse_JDD::info () static
Definition at line 22 of file LecFicDiffuse_JDD.cpp.
ouvrir()
int LecFicDiffuse_JDD::ouvrir (const char * name, std::_Ios_Openmode mode = ios::in) override virtual
Ouverture du fichier. Cette methode doit etre appelee
par tous les processeurs du groupe.
Valeur de retour: 1 si ok, 0 sinon.
Reimplemented from Entree_Fichier_base.
Definition at line 63 of file LecFicDiffuse_JDD.cpp.
{
  int ok = 0;
  if(Process::je_suis_maitre())
    {
      Cout <<"Reading data file "<<finl;
      int fin_lu=0;
      Motcle fin("fin|end");
      EFichier file_;
      ok = file_.ouvrir(name, mode);
      if (!ok )
        {
          Cerr << "File " << name << " does not exist (LecFicDiffuse_JDD)" << finl;
          Process::exit();
        }
      SChaine prov;
      Nom motlu;
      file_>>motlu;
      int nb_accolade=0;
      int nb_accolade_sa=-1;
      while (1)
        {
          if (file_.eof())
            {
              break;
            }
          if (motlu=="{")
            nb_accolade++;
          if (motlu=="}")
            nb_accolade--;
          if (fin==motlu)
            {
              fin_lu=1;
              nb_accolade_sa=nb_accolade;
            }
          if (motlu=="#")
            {
// Cerr<<" on passe les commentaires"<<finl;
              file_>>motlu;
              while (motlu!="#")
                {
                  if (file_.eof())
                    {
                      Cerr<<"Problem while reading some # "<<finl;
                      Cerr<<" # not closed "<<finl;
                      if (fin_lu)
                        Cerr<<" Keyword Fin is may be already readen."<<finl;
                      else
                        Process::exit();
                      break;
                    }
                  file_ >> motlu;
                }
            }
          else if (motlu=="/*")
            {
              // Cerr<<" on passe le bloc de commentaires"<<finl;
              int ouvrante=1;
              while (ouvrante!=0)
                {
                  file_ >>motlu;
                  if (file_.eof())
                    {
                      Cerr<<"Problem while reading some /* "<<finl;
                      Cerr<<" not closed "<<finl;
                      if (fin_lu)
                        Cerr<<" Keword Fin is may be already readen."<<finl;
                      else
                        Process::exit();
                      break;
                    }
                  if (motlu=="/*") ouvrante++;
                  if (motlu=="*/") ouvrante--;
                }
            }
          else if ((motlu.find("}")!=-1 && motlu != "}") || (motlu.find("{")!=-1 && motlu != "{") )
            {
              Cout << "Error while reading '" << motlu << "' from datafile. Check for missing space character" << finl;
              Process::exit();
            }
          /* GF ne pas reactiver ce morceau de code car cela
             est complique pour la traduction des jdd en python
             else if (motlu=="##")
             {
             Cerr<<" The comment line is crossed."<<finl;
             std::string ligne;
             std::getline(file_.get_ifstream(), ligne);
             }
          */
          else
            {
              prov<<motlu<<" ";
              if( apply_verif )
                verifie(motlu);
            }
          file_>>motlu;
        }
      if (fin_lu!=0)
        nb_accolade=nb_accolade_sa;
      if (nb_accolade!=0)
        {
          if (nb_accolade<0)
            Cerr<<"Error perhaps  extra \"}\" in data file"<<finl;
          else
            Cerr<<"Error check for missing \"}\" in data file"<<finl;
          Process::exit();
        }
      chaine_.init(prov.get_str());
      Cout <<finl;
      Process::Journal()<<"JDD interpreted: "<<finl<<prov.get_str()<<finl<<finl;
    }
  envoyer_broadcast(ok, 0);
  return ok;
}
References apply_verif, Cerr, chaine_, Cout, envoyer_broadcast(), Entree_Fichier_base::eof(), Process::exit(), Nom::find(), finl, SChaine::get_str(), EChaine::init(), Process::je_suis_maitre(), Process::Journal(), Entree_Fichier_base::ouvrir(), and verifie().
Referenced by LecFicDiffuse_JDD().
printOn()
Sortie & LecFicDiffuse_JDD::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Lec_Diffuse_base.
Definition at line 30 of file LecFicDiffuse_JDD.cpp.
{
  throw;
  return s;
}
readOn()
Entree & LecFicDiffuse_JDD::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Lec_Diffuse_base.
Definition at line 24 of file LecFicDiffuse_JDD.cpp.
{
  throw;
  return s;
}
self_cast() [1/2]
const LecFicDiffuse_JDD & LecFicDiffuse_JDD::self_cast (const Objet_U & r) static
Definition at line 22 of file LecFicDiffuse_JDD.cpp.
self_cast() [2/2]
LecFicDiffuse_JDD & LecFicDiffuse_JDD::self_cast (Objet_U & r) static
Definition at line 22 of file LecFicDiffuse_JDD.cpp.
taille_memoire()
unsigned LecFicDiffuse_JDD::taille_memoire () const override virtual
Reimplemented from EFichier.
Definition at line 22 of file LecFicDiffuse_JDD.cpp.
Member Data Documentation
apply_verif
bool LecFicDiffuse_JDD::apply_verif protected
Definition at line 46 of file LecFicDiffuse_JDD.h.
Referenced by ouvrir().
chaine_
EChaine LecFicDiffuse_JDD::chaine_ protected
Definition at line 44 of file LecFicDiffuse_JDD.h.
Referenced by get_entree_master(), and ouvrir().
info_obj
const Type_info LecFicDiffuse_JDD::info_obj static
Definition at line 36 of file LecFicDiffuse_JDD.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/LecFicDiffuse_JDD.h
src/Kernel/Utilitaires/LecFicDiffuse_JDD.cpp