TRUST: EcrFicCollecteBin Class Reference
EcrFicCollecteBin Class Reference
Ecriture dans un fichier au format binaire
Cette classe implemente les operateurs et les methodes virtuelles de la clase SFichier de la facon suivante :
Il y a autant de fichiers que de processus, physiquement localises sur le disque de la machine hebergeant la tache maitre de l'application Trio-U (le processus de rang 0 dans le groupe "tous")
Le processus maitre recoit chaque item a ecrire de chacun des processus et dans chacun chacun des fichiers.
il en est de meme pour les methodes d'inspection de l'etat d'un fichier.
#include <EcrFicCollecteBin.h>
Public Member Functions
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
EcrFicCollecteBin ()
EcrFicCollecteBin (const char *name, std::_Ios_Openmode mode=ios::out)
~EcrFicCollecteBin ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static EcrFicCollecteBin & self_cast (Objet_U &)
static const EcrFicCollecteBin & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Ecriture dans un fichier au format binaire
Cette classe implemente les operateurs et les methodes virtuelles de la clase SFichier de la facon suivante :
Il y a autant de fichiers que de processus, physiquement localises sur le disque de la machine hebergeant la tache maitre de l'application Trio-U (le processus de rang 0 dans le groupe "tous")
Le processus maitre recoit chaque item a ecrire de chacun des processus et dans chacun chacun des fichiers.
il en est de meme pour les methodes d'inspection de l'etat d'un fichier.
Definition at line 45 of file EcrFicCollecteBin.h.
Constructor & Destructor Documentation
EcrFicCollecteBin::EcrFicCollecteBin () [inline]
Definition at line 50 of file EcrFicCollecteBin.h.
References Sortie::set_bin().
  {
    set_bin(1);
  };
EcrFicCollecteBin::EcrFicCollecteBin (const char * name, std::_Ios_Openmode mode = ios::out) [inline]
Definition at line 54 of file EcrFicCollecteBin.h.
References EcrFicCollecte::ouvrir(), and Sortie::set_bin().
  {
    set_bin(1);
    ouvrir(name,mode);
  };
EcrFicCollecteBin::~EcrFicCollecteBin () [inline]
Definition at line 59 of file EcrFicCollecteBin.h.
References Sortie_Fichier_base::close().
  {
    close();
  };
Member Function Documentation
Objet_U * EcrFicCollecteBin::cree_instance () [static]
Reimplemented from EcrFicCollecte.
Definition at line 25 of file EcrFicCollecteBin.cpp.
int EcrFicCollecteBin::duplique () const [virtual]
Reimplemented from EcrFicCollecte.
Definition at line 25 of file EcrFicCollecteBin.cpp.
const Type_info * EcrFicCollecteBin::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from EcrFicCollecte.
Definition at line 25 of file EcrFicCollecteBin.cpp.
const Type_info * EcrFicCollecteBin::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from EcrFicCollecte.
Definition at line 25 of file EcrFicCollecteBin.cpp.
Sortie & EcrFicCollecteBin::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from EcrFicCollecte.
Definition at line 32 of file EcrFicCollecteBin.cpp.
{
  throw;
  return s;
}
Entree & EcrFicCollecteBin::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from EcrFicCollecte.
Definition at line 26 of file EcrFicCollecteBin.cpp.
{
  throw;
  return s;
}
const EcrFicCollecteBin & EcrFicCollecteBin::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from EcrFicCollecte.
Definition at line 25 of file EcrFicCollecteBin.cpp.
EcrFicCollecteBin & EcrFicCollecteBin::self_cast (Objet_U & r) [static]
Reimplemented from EcrFicCollecte.
Definition at line 25 of file EcrFicCollecteBin.cpp.
unsigned EcrFicCollecteBin::taille_memoire () const [virtual]
Reimplemented from EcrFicCollecte.
Definition at line 25 of file EcrFicCollecteBin.cpp.
Member Data Documentation
const Type_info EcrFicCollecteBin::info_obj [static]
Reimplemented from EcrFicCollecte.
Definition at line 47 of file EcrFicCollecteBin.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/EcrFicCollecteBin.h
src/Kernel/Utilitaires/EcrFicCollecteBin.cpp