TRUST: Convection_Diffusion_Espece_Multi_base Class Reference
Convection_Diffusion_Espece_Multi_base Class Reference
classe Convection_Diffusion_Espece_Multi_base
Cas particulier de Convection_Diffusion_Espece_Fluide_Dilatable_base
pour un fluide quasi conpressible quand le scalaire subissant le transport est
la fraction massique
#include <Convection_Diffusion_Espece_Multi_base.h>
Public Member Functions
Convection_Diffusion_Espece_Multi_base ()
~Convection_Diffusion_Espece_Multi_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Champ_base & get_champ (const Motcle &nom) const
virtual void set_param (Param &titi)
virtual int lire_motcle_non_standard (const Motcle &, Entree &)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
const Motcle & get_alias () const
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Convection_Diffusion_Espece_Multi_base & self_cast (Objet_U &)
static const
Convection_Diffusion_Espece_Multi_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a Equation_base::printOn(Sortie&)
virtual Entree & readOn (Entree &)
cf Equation_base::readOn(Entree&)
Protected Attributes
Motcle alias_
Detailed Description
classe Convection_Diffusion_Espece_Multi_base
Cas particulier de Convection_Diffusion_Espece_Fluide_Dilatable_base
pour un fluide quasi conpressible quand le scalaire subissant le transport est
la fraction massique
Definition at line 39 of file Convection_Diffusion_Espece_Multi_base.h.
Constructor & Destructor Documentation
Convection_Diffusion_Espece_Multi_base::Convection_Diffusion_Espece_Multi_base ()
Definition at line 28 of file Convection_Diffusion_Espece_Multi_base.cpp.
Convection_Diffusion_Espece_Multi_base::~Convection_Diffusion_Espece_Multi_base ()
Definition at line 28 of file Convection_Diffusion_Espece_Multi_base.cpp.
Member Function Documentation
virtual int Convection_Diffusion_Espece_Multi_base::duplique () const [pure virtual]
Implements Convection_Diffusion_Espece_Fluide_Dilatable_base.
Implemented in Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Espece_Multi_WC.
const Motcle& Convection_Diffusion_Espece_Multi_base::get_alias () const [inline]
Definition at line 49 of file Convection_Diffusion_Espece_Multi_base.h.
References alias_.
{ return alias_; }
const Champ_base & Convection_Diffusion_Espece_Multi_base::get_champ (const Motcle & nom) const [virtual]
Reimplemented from Equation_base.
Definition at line 76 of file Convection_Diffusion_Espece_Multi_base.cpp.
References Probleme_base::equation(), Equation_base::get_champ(), Equation_base::probleme(), and REF.
Referenced by Convection_Diffusion_Espece_Multi_QC::assembler().
{
  try
    {
      return Convection_Diffusion_Espece_Fluide_Dilatable_base::get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
// a revoir ..... a mon avis
  try
    {
      return probleme().equation(0).get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  throw Champs_compris_erreur();
  REF(Champ_base) ref_champ;
  return ref_champ;
}
const Type_info * Convection_Diffusion_Espece_Multi_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_Espece_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 28 of file Convection_Diffusion_Espece_Multi_base.cpp.
const Type_info * Convection_Diffusion_Espece_Multi_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_Espece_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 28 of file Convection_Diffusion_Espece_Multi_base.cpp.
int Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) [virtual]
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns:
int
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
Definition at line 58 of file Convection_Diffusion_Espece_Multi_base.cpp.
References Operateur_Diff::associer_diffusivite(), Operateur_Diff::associer_diffusivite_pour_pas_de_temps(), Cerr, Operateur_Diff::diffusivite(), Convection_Diffusion_Espece_Fluide_Dilatable_base::diffusivite_pour_pas_de_temps(), Convection_Diffusion_Fluide_Dilatable_base::diffusivite_pour_transport(), finl, Equation_base::nommer(), ref_cast_non_const, and Convection_Diffusion_std::terme_diffusif.
{
  if (mot=="diffusion")
    {
      Cerr << "Reading and typing of the diffusion operator : " << finl;
// associe mu_sur_Sc dans la diffusivite
      terme_diffusif.associer_diffusivite(diffusivite_pour_transport());
      ref_cast_non_const(Champ_base,terme_diffusif.diffusivite()).nommer("mu_sur_Schmidt");
      is >> terme_diffusif;
// Il faut appeler associer_diffusivite_pour_pas_de_temps
      terme_diffusif.associer_diffusivite_pour_pas_de_temps(diffusivite_pour_pas_de_temps());
      return 1;
    }
  else
    return Convection_Diffusion_Espece_Fluide_Dilatable_base::lire_motcle_non_standard(mot,is);
  return 1;
}
Sortie & Convection_Diffusion_Espece_Multi_base::printOn (Sortie & is) const [protected, virtual]
Simple appel a Equation_base::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Convection_Diffusion_Espece_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 30 of file Convection_Diffusion_Espece_Multi_base.cpp.
{
  return Convection_Diffusion_Espece_Fluide_Dilatable_base::printOn(is);
}
Entree & Convection_Diffusion_Espece_Multi_base::readOn (Entree & is) [protected, virtual]
cf Equation_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Convection_Diffusion_Espece_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 35 of file Convection_Diffusion_Espece_Multi_base.cpp.
References Field_base::add_synonymous(), Champs_compris::ajoute_champ(), alias_, Equation_base::champs_compris_, Convection_Diffusion_Fluide_Dilatable_base::inconnue(), Convection_Diffusion_Fluide_Dilatable_base::l_inco_ch, O_U_Ptr::le_nom(), Operateur::set_description(), Operateur::set_fichier(), Convection_Diffusion_std::terme_convectif, Convection_Diffusion_std::terme_diffusif, and Deriv_Champ_Inc_base::valeur().
{
  alias_=inconnue().le_nom();
  Convection_Diffusion_Espece_Fluide_Dilatable_base::readOn(is);
  Nom conv = "Convection_", diff = "Diffusion_";
  conv += alias_;
  diff += alias_;
  terme_convectif.set_fichier(conv);
  terme_convectif.set_description((Nom)"Convective flux =Integral(-rho*Y*u*ndS) [kg/s] if SI units used");
  terme_diffusif.set_fichier(diff);
  terme_diffusif.set_description((Nom)"Diffusive flux=Integral(rho*D*grad(Y)*ndS) [kg/s] if SI units used");
  champs_compris_.ajoute_champ(l_inco_ch);
  l_inco_ch.valeur().add_synonymous(alias_);
  return is;
}
const Convection_Diffusion_Espece_Multi_base & Convection_Diffusion_Espece_Multi_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Convection_Diffusion_Espece_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 28 of file Convection_Diffusion_Espece_Multi_base.cpp.
Convection_Diffusion_Espece_Multi_base & Convection_Diffusion_Espece_Multi_base::self_cast (Objet_U & r) [static]
Reimplemented from Convection_Diffusion_Espece_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 28 of file Convection_Diffusion_Espece_Multi_base.cpp.
void Convection_Diffusion_Espece_Multi_base::set_param (Param & titi) [virtual]
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Multi_QC.
Definition at line 51 of file Convection_Diffusion_Espece_Multi_base.cpp.
References Param::ajouter(), and alias_.
{
  Convection_Diffusion_Espece_Fluide_Dilatable_base::set_param(param);
  param.ajouter("alias",&alias_);
}
Member Data Documentation
Motcle Convection_Diffusion_Espece_Multi_base::alias_ [protected]
Definition at line 52 of file Convection_Diffusion_Espece_Multi_base.h.
Referenced by get_alias(), readOn(), and set_param().
const Type_info Convection_Diffusion_Espece_Multi_base::info_obj [static]
Reimplemented from Convection_Diffusion_Espece_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 41 of file Convection_Diffusion_Espece_Multi_base.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Equations/Convection_Diffusion_Espece_Multi_base.h
src/ThHyd/Dilatable/Common/Equations/Convection_Diffusion_Espece_Multi_base.cpp