TRUST: Ref_Zone_EF Class Reference
Ref_Zone_EF Class Reference
#include <Ref_Zone_EF.h>
Public Member Functions
~Ref_Zone_EF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Zone_EF ()
Ref_Zone_EF (const Zone_EF &)
Ref_Zone_EF (const Ref_Zone_EF &)
const Zone_EF & valeur () const
Zone_EF & valeur ()
const Zone_EF * operator-> () const
Zone_EF * operator-> ()
const Ref_Zone_EF & operator= (const Zone_EF &)
const Ref_Zone_EF & operator= (const Ref_Zone_EF &)
operator const Zone_EF & () const
operator Zone_EF & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Zone_EF & self_cast (Objet_U &)
static const Ref_Zone_EF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Zone_EF * pointeur_
Detailed Description
Definition at line 28 of file Ref_Zone_EF.h.
Constructor & Destructor Documentation
Ref_Zone_EF::~Ref_Zone_EF ()
Definition at line 25 of file Ref_Zone_EF.cpp.
Ref_Zone_EF::Ref_Zone_EF ()
Definition at line 25 of file Ref_Zone_EF.cpp.
Ref_Zone_EF::Ref_Zone_EF (const Zone_EF & t)
Definition at line 25 of file Ref_Zone_EF.cpp.
Ref_Zone_EF::Ref_Zone_EF (const Ref_Zone_EF & t)
Definition at line 25 of file Ref_Zone_EF.cpp.
Member Function Documentation
Objet_U * Ref_Zone_EF::cree_instance () [static]
Definition at line 25 of file Ref_Zone_EF.cpp.
int Ref_Zone_EF::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Zone_EF.cpp.
const Type_info * Ref_Zone_EF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_EF.cpp.
const Type_info & Ref_Zone_EF::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Zone_EF.cpp.
const Type_info * Ref_Zone_EF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_EF.cpp.
Ref_Zone_EF::operator const Zone_EF & () const
Definition at line 25 of file Ref_Zone_EF.cpp.
Ref_Zone_EF::operator Zone_EF & ()
Definition at line 25 of file Ref_Zone_EF.cpp.
const Zone_EF * Ref_Zone_EF::operator-> () const [inline]
Definition at line 28 of file Ref_Zone_EF.h.
Zone_EF * Ref_Zone_EF::operator-> () [inline]
Definition at line 28 of file Ref_Zone_EF.h.
const Ref_Zone_EF & Ref_Zone_EF::operator= (const Ref_Zone_EF & t)
Definition at line 25 of file Ref_Zone_EF.cpp.
const Ref_Zone_EF & Ref_Zone_EF::operator= (const Zone_EF & t)
Definition at line 25 of file Ref_Zone_EF.cpp.
Sortie & Ref_Zone_EF::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_EF.cpp.
Entree & Ref_Zone_EF::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_EF.cpp.
const Ref_Zone_EF & Ref_Zone_EF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_EF.cpp.
Ref_Zone_EF & Ref_Zone_EF::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_EF.cpp.
void Ref_Zone_EF::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Zone_EF.cpp.
unsigned Ref_Zone_EF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Zone_EF.cpp.
const Zone_EF & Ref_Zone_EF::valeur () const [inline]
Definition at line 28 of file Ref_Zone_EF.h.
Referenced by Source_Scalaire_EF::ajouter(), Source_Qdm_EF::ajouter(), Op_Diff_EF::ajouter(), Source_PDF_EF::ajouter_(), Op_Diff_EF::ajouter_bords(), Op_Diff_EF::ajouter_contributions_bords(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim2(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim2(), Op_Conv_EF::ajouter_sous_cond_gen(), Solveur_Masse_EF::appliquer_impl(), Assembleur_P_EF::assembler(), Assembleur_P_EF::assembler_mat(), Assembleur_P_EF::assembler_rho_variable(), Source_PDF_EF::associer_pb(), Op_Diff_EF_base::calculer_dt_stab(), Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_PDF_EF::compute_vitesse_imposee_projete(), Source_PDF_EF::contribuer_a_avec(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), Op_Diff_EF::dimensionner(), Op_Conv_EF::dimensionner(), Source_PDF_EF::impr(), Op_Grad_EF::impr(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Op_Diff_EF::modifier_pour_Cl(), Op_Conv_EF::modifier_pour_Cl(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_EF::modifier_solution(), Champ_Fonc_P0_EF::moyenne(), Source_PDF_EF::multiply_coeff_volume(), Op_Diff_EF::remplir_nu(), Source_PDF_EF::rotate_imposed_velocity(), Champ_Fonc_P0_EF::valeur_au_bord(), Source_PDF_EF::verif_ajouter_contrib(), Op_Div_EF::volumique(), Assembleur_P_EF::zone_dis_base(), and Champ_Fonc_P0_EF::zone_dis_base().
Zone_EF & Ref_Zone_EF::valeur () [inline]
Definition at line 28 of file Ref_Zone_EF.h.
Member Data Documentation
const Type_info Ref_Zone_EF::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Zone_EF.h.
Zone_EF* Ref_Zone_EF::pointeur_ [private]
Definition at line 28 of file Ref_Zone_EF.h.
The documentation for this class was generated from the following files:
src/EF/Zones/Ref_Zone_EF.h
src/EF/Zones/Ref_Zone_EF.cpp