TRUST: LecFicDiffuseBin Class Reference
LecFicDiffuseBin Class Reference
Read a file in binary format.
This class implements the operators and virtual methods of the EFichier class in the following way:
The file to read is physically locate on the disk of the machine hosting the master task of the Trio-U application (the process of rank 0 in the "tous" group)
and each item read from this file is published to all other processes of the "tous" group.
It is the same for the methods of inspection of the state of a file.
.SECTION see also.
#include <LecFicDiffuseBin.h>
Public Member Functions
~LecFicDiffuseBin ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
LecFicDiffuseBin ()
LecFicDiffuseBin (const char *name, std::_Ios_Openmode mode=ios::in)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static LecFicDiffuseBin & self_cast (Objet_U &)
static const LecFicDiffuseBin & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Read a file in binary format.
This class implements the operators and virtual methods of the EFichier class in the following way:
The file to read is physically locate on the disk of the machine hosting the master task of the Trio-U application (the process of rank 0 in the "tous" group)
and each item read from this file is published to all other processes of the "tous" group.
It is the same for the methods of inspection of the state of a file.
.SECTION see also.
Definition at line 41 of file LecFicDiffuseBin.h.
Constructor & Destructor Documentation
LecFicDiffuseBin::~LecFicDiffuseBin ()
Definition at line 25 of file LecFicDiffuseBin.cpp.
LecFicDiffuseBin::LecFicDiffuseBin () [inline]
Definition at line 46 of file LecFicDiffuseBin.h.
References Lec_Diffuse_base::set_bin().
  {
    set_bin(1);
  };
LecFicDiffuseBin::LecFicDiffuseBin (const char * name, std::_Ios_Openmode mode = ios::in) [inline]
Definition at line 50 of file LecFicDiffuseBin.h.
References LecFicDiffuse::ouvrir(), and Lec_Diffuse_base::set_bin().
  {
    set_bin(1);
    ouvrir(name,mode);
  };
Member Function Documentation
Objet_U * LecFicDiffuseBin::cree_instance () [static]
Reimplemented from LecFicDiffuse.
Definition at line 25 of file LecFicDiffuseBin.cpp.
int LecFicDiffuseBin::duplique () const [virtual]
Reimplemented from LecFicDiffuse.
Definition at line 25 of file LecFicDiffuseBin.cpp.
const Type_info * LecFicDiffuseBin::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from LecFicDiffuse.
Definition at line 25 of file LecFicDiffuseBin.cpp.
const Type_info * LecFicDiffuseBin::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from LecFicDiffuse.
Definition at line 25 of file LecFicDiffuseBin.cpp.
Sortie & LecFicDiffuseBin::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from LecFicDiffuse.
Definition at line 33 of file LecFicDiffuseBin.cpp.
{
  throw;
  return s;
}
Entree & LecFicDiffuseBin::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from LecFicDiffuse.
Definition at line 27 of file LecFicDiffuseBin.cpp.
{
  throw;
  return s;
}
const LecFicDiffuseBin & LecFicDiffuseBin::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from LecFicDiffuse.
Definition at line 25 of file LecFicDiffuseBin.cpp.
LecFicDiffuseBin & LecFicDiffuseBin::self_cast (Objet_U & r) [static]
Reimplemented from LecFicDiffuse.
Definition at line 25 of file LecFicDiffuseBin.cpp.
unsigned LecFicDiffuseBin::taille_memoire () const [virtual]
Reimplemented from LecFicDiffuse.
Definition at line 25 of file LecFicDiffuseBin.cpp.
Member Data Documentation
const Type_info LecFicDiffuseBin::info_obj [static]
Reimplemented from LecFicDiffuse.
Definition at line 43 of file LecFicDiffuseBin.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/LecFicDiffuseBin.h
src/Kernel/Utilitaires/LecFicDiffuseBin.cpp