TRUST: Source_PDF_base Class Reference
Source_PDF_base Class Reference
class Source_PDF_base
Base class for the source terms for the penalisation of the momentum in the Immersed Boundary Method (IBM)
#include <Source_PDF_base.h>
Public Member Functions
Source_PDF_base ()
~Source_PDF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int getInterpolationBool ()
bool get_matrice_pression_variable_bool_ ()
void associer_pb (const Probleme_base &) override
DoubleTab & ajouter_ (const DoubleTab &, DoubleTab &) const override
virtual DoubleTab & ajouter_ (const DoubleTab &, DoubleTab &, const int) const
DoubleTab & calculer (DoubleTab &) const override
DoubleTab & calculer (DoubleTab &, const int) const
DoubleTab & calculer_pdf (DoubleTab &) const
void mettre_a_jour (double) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
contribution a la matrice implicite des termes sources
par defaut pas de contribution
double fonct_coeff (const double, const double, const double) const
virtual DoubleVect diag_coeff_elem (ArrOfDouble &, const DoubleTab &, int) const
virtual DoubleTab compute_coeff_elem () const
virtual DoubleTab compute_coeff_matrice_pression () const
virtual void multiply_coeff_volume (DoubleTab &) const
virtual void correct_pressure (const DoubleTab &, DoubleTab &, const DoubleTab &) const
virtual void correct_incr_pressure (const DoubleTab &, DoubleTab &) const
virtual void correct_vitesse (const DoubleTab &, DoubleTab &) const
void calculer_vitesse_imposee ()
void updateChampRho ()
const PDF_model & get_modele () const
int impr (Sortie &) const override
void ouvrir_fichier (SFichier &, const Nom &, const int) const override
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
const DoubleTab & get_sec_mem_pdf () const
void set_sec_mem_pdf (DoubleTab &it)
Public Member Functions inherited from Source_dep_inco_base
Source_dep_inco_base ()
~Source_dep_inco_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &resu) const override
virtual DoubleTab & ajouter_ (const DoubleTab &inco, DoubleTab &resu) const =0
DoubleTab & calculer (DoubleTab &resu) const override
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Source_PDF_base & self_cast (Objet_U &)
static const Source_PDF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_dep_inco_base
static const Type_info * info ()
static Source_dep_inco_base & self_cast (Objet_U &)
static const Source_dep_inco_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_dep_inco_base
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void compute_vitesse_imposee_projete (const DoubleTab &, const DoubleTab &, double, double)
virtual void calculer_vitesse_imposee_hybrid ()
virtual void calculer_vitesse_imposee_elem_fluid ()
virtual void calculer_vitesse_imposee_mean_grad ()
virtual void calculer_vitesse_imposee_power_law_tbl ()
virtual void rotate_imposed_velocity (DoubleTab &)
ArrOfDouble get_tuvw_local () const
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
virtual void compute_indicateur_nodal_champ_aire ()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int type_vitesse_imposee_
Champ_Don champ_rotation_lu_
Champ_Don champ_rotation_
Champ_Don champ_aire_lu_
Champ_Don champ_aire_
Champ_Don champ_rho_
int transpose_rotation_
DoubleTab indicateur_nodal_champ_aire_
DoubleTab vitesse_imposee_
PDF_model modele_lu_
double temps_relax_
double echelle_relax_
bool matrice_pression_variable_bool_
bool penalized_
DoubleTab sec_mem_pdf
part of the source term computed with the imposed velocity FOR THE INTERPOLATION
Interpolation_IBM interpolation_lue_
int interpolation_bool_
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Source_PDF_base
Base class for the source terms for the penalisation of the momentum in the Immersed Boundary Method (IBM)
See also
Source_dep_inco_base, and Source_PDF
Definition at line 36 of file Source_PDF_base.h.
Constructor & Destructor Documentation
Source_PDF_base()
Source_PDF_base::Source_PDF_base ()
Definition at line 28 of file Source_PDF_base.cpp.
~Source_PDF_base()
Source_PDF_base::~Source_PDF_base () override
Definition at line 28 of file Source_PDF_base.cpp.
Member Function Documentation
ajouter_() [1/2]
DoubleTab & Source_PDF_base::ajouter_ (const DoubleTab & vitesse, DoubleTab & resu) const override virtual
Implements Source_dep_inco_base.
Definition at line 181 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
  return resu;
}
References Process::abort(), Cerr, and finl.
Referenced by calculer(), and calculer_pdf().
ajouter_() [2/2]
DoubleTab & Source_PDF_base::ajouter_ (const DoubleTab & vitesse, DoubleTab & resu, const int i_traitement_special) const virtual
Reimplemented in Source_PDF_EF.
Definition at line 188 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
  return resu;
}
References Process::abort(), Cerr, and finl.
associer_pb()
void Source_PDF_base::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Definition at line 71 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
}
References Process::abort(), Cerr, and finl.
associer_zones()
void Source_PDF_base::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
Implements Source_base.
Definition at line 89 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
}
References Process::abort(), Cerr, and finl.
calculer() [1/2]
DoubleTab & Source_PDF_base::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_dep_inco_base.
Definition at line 211 of file Source_PDF_base.cpp.
{
  resu = 0;
  const DoubleTab& vitesse=equation().inconnue().valeurs();
  return ajouter_(vitesse,resu);
}
References ajouter_(), MorEqn::equation(), Equation_base::inconnue(), and Champ_Inc::valeurs().
Referenced by Source_PDF_EF::impr(), and Piso::iterer_NS().
calculer() [2/2]
DoubleTab & Source_PDF_base::calculer (DoubleTab & resu, const int i_traitement_special) const
Definition at line 218 of file Source_PDF_base.cpp.
{
  resu = 0;
  const DoubleTab& vitesse=equation().inconnue().valeurs();
  return ajouter_(vitesse,resu, i_traitement_special);
}
References ajouter_(), MorEqn::equation(), Equation_base::inconnue(), and Champ_Inc::valeurs().
calculer_pdf()
DoubleTab & Source_PDF_base::calculer_pdf (DoubleTab & resu) const
Definition at line 272 of file Source_PDF_base.cpp.
{
  resu = 0;
  ajouter_(vitesse_imposee_,resu);
  return resu;
}
References ajouter_(), and vitesse_imposee_.
Referenced by Piso::iterer_NS(), and Navier_Stokes_std::preparer_calcul().
calculer_vitesse_imposee()
void Source_PDF_base::calculer_vitesse_imposee ()
Definition at line 249 of file Source_PDF_base.cpp.
{
  if (interpolation_bool_)
    {
      if (interpolation_lue_.valeur().que_suis_je() == "Interpolation_IBM_element_fluide")
        {
          calculer_vitesse_imposee_elem_fluid();
        }
      else if (interpolation_lue_.valeur().que_suis_je() == "Interpolation_IBM_gradient_moyen")
        {
          calculer_vitesse_imposee_mean_grad();
        }
      else if (interpolation_lue_.valeur().que_suis_je() == "Interpolation_IBM_hybride")
        {
          calculer_vitesse_imposee_hybrid();
        }
      else if (interpolation_lue_.valeur().que_suis_je() == "Interpolation_IBM_power_law_tbl")
        {
          calculer_vitesse_imposee_power_law_tbl();
        }
    }
}
References calculer_vitesse_imposee_elem_fluid(), calculer_vitesse_imposee_hybrid(), calculer_vitesse_imposee_mean_grad(), calculer_vitesse_imposee_power_law_tbl(), interpolation_bool_, interpolation_lue_, Objet_U::que_suis_je(), and Deriv_Interpolation_IBM_base::valeur().
Referenced by Navier_Stokes_std::initTimeStep().
calculer_vitesse_imposee_elem_fluid()
void Source_PDF_base::calculer_vitesse_imposee_elem_fluid () protected virtual
Reimplemented in Source_PDF_EF.
Definition at line 225 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
}
References Process::abort(), Cerr, and finl.
Referenced by calculer_vitesse_imposee().
calculer_vitesse_imposee_hybrid()
void Source_PDF_base::calculer_vitesse_imposee_hybrid () protected virtual
Reimplemented in Source_PDF_EF.
Definition at line 237 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
}
References Process::abort(), Cerr, and finl.
Referenced by calculer_vitesse_imposee().
calculer_vitesse_imposee_mean_grad()
void Source_PDF_base::calculer_vitesse_imposee_mean_grad () protected virtual
Reimplemented in Source_PDF_EF.
Definition at line 231 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
}
References Process::abort(), Cerr, and finl.
Referenced by calculer_vitesse_imposee().
calculer_vitesse_imposee_power_law_tbl()
void Source_PDF_base::calculer_vitesse_imposee_power_law_tbl () protected virtual
Reimplemented in Source_PDF_EF.
Definition at line 243 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
}
References Process::abort(), Cerr, and finl.
Referenced by calculer_vitesse_imposee().
compute_coeff_elem()
DoubleTab Source_PDF_base::compute_coeff_elem () const virtual
Reimplemented in Source_PDF_EF.
Definition at line 135 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
  return DoubleTab();
}
References Process::abort(), Cerr, and finl.
compute_coeff_matrice_pression()
DoubleTab Source_PDF_base::compute_coeff_matrice_pression () const virtual
Reimplemented in Source_PDF_EF.
Definition at line 142 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
  return DoubleTab();
}
References Process::abort(), Cerr, and finl.
Referenced by Navier_Stokes_std::initTimeStep(), and Navier_Stokes_std::preparer_calcul().
compute_indicateur_nodal_champ_aire()
void Source_PDF_base::compute_indicateur_nodal_champ_aire () protected virtual
Reimplemented in Source_PDF_EF.
Definition at line 96 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
}
References Process::abort(), Cerr, and finl.
compute_vitesse_imposee_projete()
void Source_PDF_base::compute_vitesse_imposee_projete (const DoubleTab & marqueur, const DoubleTab & points, double val, double eps) protected virtual
Reimplemented in Source_PDF_EF.
Definition at line 77 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
}
References Process::abort(), Cerr, and finl.
contribuer_a_avec()
void Source_PDF_base::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const override virtual
contribution a la matrice implicite des termes sources
par defaut pas de contribution
Reimplemented from Source_base.
Definition at line 205 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
}
References Process::abort(), Cerr, and finl.
correct_incr_pressure()
void Source_PDF_base::correct_incr_pressure (const DoubleTab & coeff_node, DoubleTab & correction_en_pression) const virtual
Reimplemented in Source_PDF_EF.
Definition at line 284 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
}
References Process::abort(), Cerr, and finl.
Referenced by Navier_Stokes_std::preparer_calcul().
correct_pressure()
void Source_PDF_base::correct_pressure (const DoubleTab & coeff_node, DoubleTab & pression, const DoubleTab & correction_en_pression) const virtual
Reimplemented in Source_PDF_EF.
Definition at line 290 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
}
References Process::abort(), Cerr, and finl.
Referenced by Piso::iterer_NS().
correct_vitesse()
void Source_PDF_base::correct_vitesse (const DoubleTab & coeff_node, DoubleTab & vitesse) const virtual
Reimplemented in Source_PDF_EF.
Definition at line 296 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
}
References Process::abort(), Cerr, and finl.
Referenced by Navier_Stokes_std::projeter().
diag_coeff_elem()
DoubleVect Source_PDF_base::diag_coeff_elem (ArrOfDouble & vitesse_elem, const DoubleTab & rotation, int num_elem) const virtual
Reimplemented in Source_PDF_EF.
Definition at line 128 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
  return DoubleVect();
}
References Process::abort(), Cerr, and finl.
fonct_coeff()
double Source_PDF_base::fonct_coeff (const double rho_m, const double aire, const double dt) const
Definition at line 102 of file Source_PDF_base.cpp.
{
  double val_coeff = 0.;
  if (aire<=0.)
    {
      return val_coeff;
    }
  double inv_dt = 1./dt;
// Cerr<<"dt pour Source_PDF_base::fonct_coeff : "<< dt <<finl;
  val_coeff = rho_m * inv_dt;
  const double tps_cour = equation().probleme().schema_temps().temps_courant();
  if (temps_relax_ != 1.0e+12)
    {
// double bco = 100.*(1.-exp(-0.1/echelle_relax_)); // tps_cour_intersection = 0.1 * temps_relax_
      double deltrel = tps_cour - temps_relax_;
      double coeff_relax = (1.+tanh(deltrel/(echelle_relax_ * temps_relax_)))/2.;
// double coeff_relax = min (1., std::max(1.-bco*deltrel*deltrel/temps_relax_/temps_relax_, exp(deltrel/(echelle_relax_ * temps_relax_))));
// double coeff_relax = 1.0 - exp(-tps_cour / temps_relax_);
// double coeff_relax = tanh(tps_cour / temps_relax_);
      val_coeff *= coeff_relax ;
// Cerr<< "coeff. relax. pour PDF = "<<coeff_relax<<" val_coeff = "<<val_coeff <<endl;
    }
  return val_coeff;
}
References echelle_relax_, MorEqn::equation(), Equation_base::probleme(), Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), and temps_relax_.
Referenced by Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), and Source_PDF_EF::compute_pond().
get_info()
const Type_info * Source_PDF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_dep_inco_base.
Definition at line 28 of file Source_PDF_base.cpp.
get_matrice_pression_variable_bool_()
bool Source_PDF_base::get_matrice_pression_variable_bool_ () inline
Definition at line 46 of file Source_PDF_base.h.
  {
    return  matrice_pression_variable_bool_;
  };
References matrice_pression_variable_bool_.
Referenced by Navier_Stokes_std::initTimeStep().
get_modele()
const PDF_model & Source_PDF_base::get_modele () const inline
Definition at line 68 of file Source_PDF_base.h.
  {
    return modele_lu_;
  }
References modele_lu_.
get_sec_mem_pdf()
const DoubleTab & Source_PDF_base::get_sec_mem_pdf () const inline
Definition at line 74 of file Source_PDF_base.h.
  {
    return sec_mem_pdf;
  }
References sec_mem_pdf.
get_tuvw_local()
ArrOfDouble Source_PDF_base::get_tuvw_local () const protected
Definition at line 161 of file Source_PDF_base.cpp.
{
  assert(Objet_U::dimension==3);
  ArrOfDouble tuvw(dimension) ;
  tuvw[0] = 1.0 / modele_lu_.eta_;
  tuvw[1] = 1.0 / modele_lu_.eta_;
  tuvw[2] = 1.0 / modele_lu_.eta_;
  return tuvw ;
}
References Objet_U::dimension, PDF_model::eta_, and modele_lu_.
Referenced by Source_PDF_EF::diag_coeff_elem().
getInterpolationBool()
int Source_PDF_base::getInterpolationBool () inline
Definition at line 42 of file Source_PDF_base.h.
  {
    return interpolation_bool_;
  };
References interpolation_bool_.
impr()
int Source_PDF_base::impr (Sortie & os) const override virtual
Reimplemented from Source_base.
Definition at line 302 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
  return 0;
}
References Process::abort(), Cerr, and finl.
info()
const Type_info * Source_PDF_base::info () static
Definition at line 28 of file Source_PDF_base.cpp.
mettre_a_jour()
void Source_PDF_base::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 279 of file Source_PDF_base.cpp.
{
// la_source->mettre_a_jour(temps);
}
multiply_coeff_volume()
void Source_PDF_base::multiply_coeff_volume (DoubleTab & coeff) const virtual
Reimplemented in Source_PDF_EF.
Definition at line 149 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
}
References Process::abort(), Cerr, and finl.
Referenced by Navier_Stokes_std::initTimeStep(), and Navier_Stokes_std::preparer_calcul().
ouvrir_fichier()
void Source_PDF_base::ouvrir_fichier (SFichier & os, const Nom & type, const int flag = 1) const override virtual
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
Reimplemented from Source_base.
Definition at line 309 of file Source_PDF_base.cpp.
{
// flag nul on n'ouvre pas le fichier
  if (flag==0)
    return ;
  const Probleme_base& pb=equation().probleme();
  const Schema_Temps_base& sch=pb.schema_temps();
  const int precision=sch.precision_impr();
  Nom nomfichier(out_);
  if (type!="") nomfichier+=(Nom)"_"+type;
  nomfichier+=".out";
// On cree le fichier a la premiere impression avec l'en tete
  if (sch.nb_impr()==1 && !pb.reprise_effectuee())
    {
      os.ouvrir(nomfichier);
      SFichier& fic=os;
      Nom espace="\t\t";
      fic << (Nom)"# Printing of the source term "+que_suis_je()+" of the equation "+equation().que_suis_je()+" of the problem "+equation().probleme().le_nom() << finl;
      fic << "# " << description() << finl;
      fic << "# Time" << espace << "Fx" << espace << "Fy" << espace << "Fz";
      fic << finl;
    }
// Sinon on l'ouvre
  else
    {
      os.ouvrir(nomfichier,ios::app);
    }
  os.precision(precision);
  os.setf(ios::scientific);
}
References Source_base::description(), MorEqn::equation(), finl, Probleme_base::le_nom(), Schema_Temps_base::nb_impr(), Source_base::out_, Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), Schema_Temps_base::precision_impr(), Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), and Sortie_Fichier_base::setf().
Referenced by Source_PDF_EF::impr().
printOn()
Sortie & Source_PDF_base::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_dep_inco_base.
Definition at line 60 of file Source_PDF_base.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Source_PDF_base::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
< XD_ADD_P field_base volumic field: a boolean for the cell (0 or 1) indicating if the obstacle is in the cell
< XD_ADD_P field_base volumic field with 9 components representing the change of basis on cells (local to global). Used for rotating cases for example.
< XD_ADD_P rien whether to transpose the basis change matrix.
< XD_ADD_P bloc_pdf_model model used for the Penalized Direct Forcing
< XD_ADD_P interpolation_ibm_base interpolation method
Reimplemented from Source_dep_inco_base.
Definition at line 37 of file Source_PDF_base.cpp.
{
  Param param(que_suis_je());
  param.ajouter("aire", &champ_aire_lu_,Param::REQUIRED); //!< XD_ADD_P field_base volumic field: a boolean for the cell (0 or 1) indicating if the obstacle is in the cell
  param.ajouter("rotation", &champ_rotation_lu_,Param::REQUIRED); //!< XD_ADD_P field_base volumic field with 9 components representing the change of basis on cells (local to global). Used for rotating cases for example.
  param.ajouter_flag("transpose_rotation", &transpose_rotation_,Param::OPTIONAL); //!< XD_ADD_P rien  whether to transpose the basis change matrix.
  param.ajouter("modele",&modele_lu_,Param::REQUIRED);   //!< XD_ADD_P bloc_pdf_model model used for the Penalized Direct Forcing
  temps_relax_ = modele_lu_.temps_relax_;
  echelle_relax_ =  modele_lu_.echelle_relax_;
  param.ajouter("interpolation",&interpolation_lue_,Param::OPTIONAL); //!< XD_ADD_P interpolation_ibm_base interpolation method
  param.lire_avec_accolades(s);
  interpolation_bool_ = false;
  if ((&interpolation_lue_)->non_nul())
    {
      if (!(interpolation_lue_.valeur().que_suis_je() == "Interpolation_IBM_aucune"))
        {
          interpolation_bool_ = true;
        }
    }
  return s;
}
References Param::ajouter(), Param::ajouter_flag(), champ_aire_lu_, champ_rotation_lu_, PDF_model::echelle_relax_, echelle_relax_, interpolation_bool_, interpolation_lue_, Param::lire_avec_accolades(), modele_lu_, Param::OPTIONAL, Objet_U::que_suis_je(), Param::REQUIRED, PDF_model::temps_relax_, temps_relax_, transpose_rotation_, and Deriv_Interpolation_IBM_base::valeur().
Referenced by Source_PDF_EF::readOn().
rotate_imposed_velocity()
void Source_PDF_base::rotate_imposed_velocity (DoubleTab & vitesse_imposee) protected virtual
Reimplemented in Source_PDF_EF.
Definition at line 83 of file Source_PDF_base.cpp.
{
  Cerr << "Source_PDF_base: Not implemented for current discretisation. Aborting..." << finl;
  abort();
}
References Process::abort(), Cerr, and finl.
self_cast() [1/2]
const Source_PDF_base & Source_PDF_base::self_cast (const Objet_U & r) static
Definition at line 28 of file Source_PDF_base.cpp.
self_cast() [2/2]
Source_PDF_base & Source_PDF_base::self_cast (Objet_U & r) static
Definition at line 28 of file Source_PDF_base.cpp.
set_sec_mem_pdf()
void Source_PDF_base::set_sec_mem_pdf (DoubleTab & it) inline
Definition at line 78 of file Source_PDF_base.h.
  {
    sec_mem_pdf = it;
  }
References sec_mem_pdf.
Referenced by Piso::iterer_NS().
updateChampRho()
void Source_PDF_base::updateChampRho ()
Definition at line 342 of file Source_PDF_base.cpp.
{
  if (equation().probleme().que_suis_je() == "Pb_Melange")
    {
      champ_rho_.valeur().affecter(equation().probleme().get_champ("masse_volumique_melange"));
    }
  else
    {
      champ_rho_.valeur().affecter(equation().probleme().get_champ("masse_volumique"));
    }
}
References Champ_base::affecter(), champ_rho_, MorEqn::equation(), Source_base::get_champ(), Objet_U::que_suis_je(), and Deriv_Champ_Don_base::valeur().
Referenced by Navier_Stokes_std::initTimeStep(), and Navier_Stokes_std::preparer_calcul().
Member Data Documentation
champ_aire_
Champ_Don Source_PDF_base::champ_aire_ protected
Definition at line 96 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::ajouter_(), Source_PDF_EF::associer_pb(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), Source_PDF_EF::contribuer_a_avec(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), and Source_PDF_EF::verif_ajouter_contrib().
champ_aire_lu_
Champ_Don Source_PDF_base::champ_aire_lu_ protected
Definition at line 95 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::associer_pb(), and readOn().
champ_rho_
Champ_Don Source_PDF_base::champ_rho_ protected
Definition at line 97 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::ajouter_(), Source_PDF_EF::associer_pb(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_PDF_EF::contribuer_a_avec(), and updateChampRho().
champ_rotation_
Champ_Don Source_PDF_base::champ_rotation_ protected
Definition at line 94 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::ajouter_(), Source_PDF_EF::associer_pb(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_PDF_EF::contribuer_a_avec(), and Source_PDF_EF::rotate_imposed_velocity().
champ_rotation_lu_
Champ_Don Source_PDF_base::champ_rotation_lu_ protected
Definition at line 93 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::associer_pb(), and readOn().
echelle_relax_
double Source_PDF_base::echelle_relax_ protected
Definition at line 103 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::associer_pb(), fonct_coeff(), and readOn().
indicateur_nodal_champ_aire_
DoubleTab Source_PDF_base::indicateur_nodal_champ_aire_ protected
Definition at line 99 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), and Source_PDF_EF::compute_indicateur_nodal_champ_aire().
info_obj
const Type_info Source_PDF_base::info_obj static
Definition at line 39 of file Source_PDF_base.h.
interpolation_bool_
int Source_PDF_base::interpolation_bool_ protected
Definition at line 109 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::associer_pb(), calculer_vitesse_imposee(), getInterpolationBool(), and readOn().
interpolation_lue_
Interpolation_IBM Source_PDF_base::interpolation_lue_ protected
Definition at line 108 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::associer_pb(), calculer_vitesse_imposee(), Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), and readOn().
matrice_pression_variable_bool_
bool Source_PDF_base::matrice_pression_variable_bool_ protected
Definition at line 104 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::associer_pb(), and get_matrice_pression_variable_bool_().
modele_lu_
PDF_model Source_PDF_base::modele_lu_ protected
Definition at line 101 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::ajouter_(), Source_PDF_EF::associer_pb(), Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::compute_vitesse_imposee_projete(), Source_PDF_EF::contribuer_a_avec(), get_modele(), get_tuvw_local(), and readOn().
penalized_
bool Source_PDF_base::penalized_ protected
Definition at line 105 of file Source_PDF_base.h.
sec_mem_pdf
DoubleTab Source_PDF_base::sec_mem_pdf protected
part of the source term computed with the imposed velocity FOR THE INTERPOLATION
Definition at line 106 of file Source_PDF_base.h.
Referenced by get_sec_mem_pdf(), Source_PDF_EF::impr(), and set_sec_mem_pdf().
temps_relax_
double Source_PDF_base::temps_relax_ protected
Definition at line 102 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::associer_pb(), fonct_coeff(), and readOn().
transpose_rotation_
int Source_PDF_base::transpose_rotation_ protected
Definition at line 98 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::associer_pb(), and readOn().
type_vitesse_imposee_
int Source_PDF_base::type_vitesse_imposee_ protected
Definition at line 92 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::associer_pb().
vitesse_imposee_
DoubleTab Source_PDF_base::vitesse_imposee_ protected
Definition at line 100 of file Source_PDF_base.h.
Referenced by Source_PDF_EF::associer_pb(), calculer_pdf(), Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), and Source_PDF_EF::correct_vitesse().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Sources/Source_PDF_base.h
src/ThHyd/Incompressible/Sources/Source_PDF_base.cpp