TRUST: Deriv_Equation_base Class Reference
Deriv_Equation_base Class Reference
#include <Equation.h>
Public Member Functions
~Deriv_Equation_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Equation_base ()
Deriv_Equation_base (const Deriv_Equation_base &)
const Equation_base & valeur () const
Equation_base & valeur ()
const Equation_base * operator-> () const
Equation_base * operator-> ()
const Deriv_Equation_base & operator= (const Equation_base &)
const Deriv_Equation_base & operator= (const Deriv_Equation_base &)
operator const Equation_base & () const
operator Equation_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Equation_base & self_cast (Objet_U &)
static const Deriv_Equation_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Equation_base * pointeur_
Detailed Description
Definition at line 31 of file Equation.h.
Constructor & Destructor Documentation
Deriv_Equation_base::~Deriv_Equation_base ()
Definition at line 25 of file Equation.cpp.
Deriv_Equation_base::Deriv_Equation_base ()
Definition at line 25 of file Equation.cpp.
Deriv_Equation_base::Deriv_Equation_base (const Deriv_Equation_base & t)
Definition at line 25 of file Equation.cpp.
Member Function Documentation
Objet_U * Deriv_Equation_base::cree_instance () [static]
Reimplemented in Equation.
Definition at line 25 of file Equation.cpp.
int Deriv_Equation_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Equation.
Definition at line 25 of file Equation.cpp.
const Type_info * Deriv_Equation_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Equation.
Definition at line 25 of file Equation.cpp.
const Type_info & Deriv_Equation_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Equation.cpp.
const Type_info * Deriv_Equation_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Equation.
Definition at line 25 of file Equation.cpp.
Deriv_Equation_base::operator const Equation_base & () const
Definition at line 25 of file Equation.cpp.
Deriv_Equation_base::operator Equation_base & ()
Definition at line 25 of file Equation.cpp.
const Equation_base * Deriv_Equation_base::operator-> () const [inline]
Definition at line 31 of file Equation.h.
: public DERIV(Equation_base)
Equation_base * Deriv_Equation_base::operator-> () [inline]
Definition at line 31 of file Equation.h.
: public DERIV(Equation_base)
const Deriv_Equation_base & Deriv_Equation_base::operator= (const Deriv_Equation_base & t)
Definition at line 25 of file Equation.cpp.
const Deriv_Equation_base & Deriv_Equation_base::operator= (const Equation_base & t)
Definition at line 25 of file Equation.cpp.
Sortie & Deriv_Equation_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Equation.
Definition at line 25 of file Equation.cpp.
Entree & Deriv_Equation_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Equation.
Definition at line 25 of file Equation.cpp.
const Deriv_Equation_base & Deriv_Equation_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Equation.
Definition at line 25 of file Equation.cpp.
Deriv_Equation_base & Deriv_Equation_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Equation.
Definition at line 25 of file Equation.cpp.
void Deriv_Equation_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Equation.cpp.
unsigned Deriv_Equation_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Equation.
Definition at line 25 of file Equation.cpp.
const Equation_base & Deriv_Equation_base::valeur () const [inline]
Definition at line 31 of file Equation.h.
Referenced by Equation::associer_milieu_base(), Equation::associer_sch_tps_base(), Equation::discretiser(), Equation::inconnue(), Equation::milieu(), Equation::nombre_d_operateurs(), Equation::operateur(), Equation::reprendre(), and Equation::sauvegarder().
: public DERIV(Equation_base)
Equation_base & Deriv_Equation_base::valeur () [inline]
Definition at line 31 of file Equation.h.
: public DERIV(Equation_base)
Member Data Documentation
const Type_info Deriv_Equation_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Equation.
Definition at line 31 of file Equation.h.
Equation_base* Deriv_Equation_base::pointeur_ [private]
Definition at line 31 of file Equation.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Equation.h
src/Kernel/Framework/Equation.cpp