TRUST: Ch_front_var_instationnaire_dep Class Reference
Ch_front_var_instationnaire_dep Class Reference
classe Ch_front_var_instationnaire_dep
Cette classe abstraite represente un champ sur une frontiere,
variable en espace, instationnaire en temps, et pouvant
dependre de donnees exterieures au champ.
De ce fait, la methode mettre_a_jour utilise des donnees
externes, et la methode initialiser ne peut pas appeler la
methode mettre_a_jour. Elle peut en revanche utiliser
l'inconnue qui lui est passee en parametre comme une premiere
estimation (c'est ce qui est code par defaut).
#include <Ch_front_var_instationnaire_dep.h>
Public Member Functions
Ch_front_var_instationnaire_dep ()
~Ch_front_var_instationnaire_dep ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialise le temps courant et Gpoint.
Champ_front_base & affecter_ (const Champ_front_base &ch)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Ch_front_var_instationnaire_dep & self_cast (Objet_U &)
static const
Ch_front_var_instationnaire_dep & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le nom du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Detailed Description
classe Ch_front_var_instationnaire_dep
Cette classe abstraite represente un champ sur une frontiere,
variable en espace, instationnaire en temps, et pouvant
dependre de donnees exterieures au champ.
De ce fait, la methode mettre_a_jour utilise des donnees
externes, et la methode initialiser ne peut pas appeler la
methode mettre_a_jour. Elle peut en revanche utiliser
l'inconnue qui lui est passee en parametre comme une premiere
estimation (c'est ce qui est code par defaut).
Definition at line 45 of file Ch_front_var_instationnaire_dep.h.
Constructor & Destructor Documentation
Ch_front_var_instationnaire_dep::Ch_front_var_instationnaire_dep ()
Definition at line 30 of file Ch_front_var_instationnaire_dep.cpp.
Ch_front_var_instationnaire_dep::~Ch_front_var_instationnaire_dep ()
Definition at line 30 of file Ch_front_var_instationnaire_dep.cpp.
Member Function Documentation
Champ_front_base & Ch_front_var_instationnaire_dep::affecter_ (const Champ_front_base & ch) [virtual]
Implements Champ_front_base.
Reimplemented in Ch_front_input, Champ_front_calc, Champ_Front_Fonction, Champ_front_normal, Champ_front_tangentiel, Champ_front_synt, and Champ_front_contact_VEF.
Definition at line 82 of file Ch_front_var_instationnaire_dep.cpp.
{
  return *this;
}
Objet_U * Ch_front_var_instationnaire_dep::cree_instance () [static]
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc_gradient, Champ_Front_Fonction, Champ_front_normal, Champ_front_tangentiel, Champ_front_xyz_debit, Ch_front_input_P1, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 30 of file Ch_front_var_instationnaire_dep.cpp.
int Ch_front_var_instationnaire_dep::duplique () const [virtual]
Implements Champ_front_var_instationnaire.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc_gradient, Champ_Front_Fonction, Champ_front_normal, Champ_front_tangentiel, Champ_front_xyz_debit, Ch_front_input_P1, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 30 of file Ch_front_var_instationnaire_dep.cpp.
const Type_info * Ch_front_var_instationnaire_dep::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc_gradient, Champ_Front_Fonction, Champ_front_normal, Champ_front_tangentiel, Champ_front_xyz_debit, Ch_front_input_P1, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 30 of file Ch_front_var_instationnaire_dep.cpp.
const Type_info * Ch_front_var_instationnaire_dep::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc_gradient, Champ_Front_Fonction, Champ_front_normal, Champ_front_tangentiel, Champ_front_xyz_debit, Ch_front_input_P1, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 30 of file Ch_front_var_instationnaire_dep.cpp.
int Ch_front_var_instationnaire_dep::initialiser (double temps, const Champ_Inc_base & inco) [virtual]
Initialise le temps courant et Gpoint.
< pour dimensionner
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Boundary_field_inward, Ch_front_input, Champ_front_calc, Champ_front_debit, Champ_Front_Fonction, Champ_front_xyz_debit, Ch_front_input_P1, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_contact_VEF, and Champ_front_tangentiel_VEF.
Definition at line 46 of file Ch_front_var_instationnaire_dep.cpp.
References Cerr, Objet_U::dimension, DoubleVect::echange_espace_virtuel(), finl, Frontiere_dis_base::frontiere(), Champ_front_base::frontiere_dis(), Champ_front_var_instationnaire::initialiser(), Champ_front_base::les_valeurs, Field_base::nb_comp(), Zone_dis_base::nb_elem(), Objet_U::que_suis_je(), ref_cast, Champ_base::temps(), Champ_Inc_base::valeurs(), and Champ_base::zone_dis_base().
Referenced by Champ_front_tangentiel_VEF::initialiser(), Champ_front_contact_VEF::initialiser(), Champ_front_synt::initialiser(), Champ_front_pression_from_u::initialiser(), Champ_front_recyclage::initialiser(), Champ_front_xyz_debit::initialiser(), Ch_front_input::initialiser(), and Boundary_field_inward::initialiser().
{
  if (!Champ_front_var_instationnaire::initialiser(temps,inco))
    return 0;
// Initialisation par defaut a la valeur de l'inconnue au bord
// Ca veut dire prendre la trace de son propre bord
// Attention, ne pas passer par les raccords !
  DoubleTab& tab=les_valeurs->valeurs();
  assert(temps==inco.temps());
  if(nb_comp()!=inco.nb_comp())
    {
// Used by ICoCo see U_in_var_impl test case
// Different field so we initialize to 0:
      tab = 0;
    }
  else
    {
      const Frontiere& MaFrontiere = frontiere_dis().frontiere();
      ConstDoubleTab_parts parts(inco.valeurs());
      if (parts[0].dimension(0)==inco.zone_dis_base().nb_elem())
        MaFrontiere.Frontiere::trace_elem_local(inco.valeurs(),tab);
      else if (parts[0].dimension(0)==ref_cast(Zone_VF,inco.zone_dis_base()).nb_faces())
        MaFrontiere.Frontiere::trace_face_local(inco.valeurs(),tab);
      else
        {
          Cerr << "Warning: Field " << inco.que_suis_je() << " is not supported yet in Ch_front_var_instationnaire_dep::initialiser" << finl;
// Process::exit();
        }
    }
  tab.echange_espace_virtuel();
  return 1;
}
Sortie & Ch_front_var_instationnaire_dep::printOn (Sortie & s) const [protected, virtual]
Imprime le nom du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc_gradient, Champ_Front_Fonction, Champ_front_normal, Champ_front_tangentiel, Champ_front_xyz_debit, Ch_front_input_P1, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 32 of file Ch_front_var_instationnaire_dep.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Ch_front_var_instationnaire_dep::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc_gradient, Champ_Front_Fonction, Champ_front_normal, Champ_front_tangentiel, Champ_front_xyz_debit, Ch_front_input_P1, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 37 of file Ch_front_var_instationnaire_dep.cpp.
References Field_base::fixer_nb_comp().
{
  int dim;
  s >> dim;
  fixer_nb_comp(dim);
  return s;
}
Ch_front_var_instationnaire_dep & Ch_front_var_instationnaire_dep::self_cast (Objet_U & r) [static]
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc_gradient, Champ_Front_Fonction, Champ_front_normal, Champ_front_tangentiel, Champ_front_xyz_debit, Ch_front_input_P1, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 30 of file Ch_front_var_instationnaire_dep.cpp.
const Ch_front_var_instationnaire_dep & Ch_front_var_instationnaire_dep::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc_gradient, Champ_Front_Fonction, Champ_front_normal, Champ_front_tangentiel, Champ_front_xyz_debit, Ch_front_input_P1, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 30 of file Ch_front_var_instationnaire_dep.cpp.
unsigned Ch_front_var_instationnaire_dep::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc_gradient, Champ_Front_Fonction, Champ_front_normal, Champ_front_tangentiel, Champ_front_xyz_debit, Ch_front_input_P1, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 30 of file Ch_front_var_instationnaire_dep.cpp.
Member Data Documentation
const Type_info Ch_front_var_instationnaire_dep::info_obj [static]
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc_gradient, Champ_Front_Fonction, Champ_front_normal, Champ_front_tangentiel, Champ_front_xyz_debit, Ch_front_input_P1, Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 47 of file Ch_front_var_instationnaire_dep.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Ch_front_var_instationnaire_dep.h
src/Kernel/Framework/Ch_front_var_instationnaire_dep.cpp