TRUST: Zone_dis_base Class Reference
Zone_dis_base Class Reference abstract
classe Zone_dis_base
Cette classe est la base de la hierarchie des zones discretisees.
Un objet Zone est associe a la zone discretise.
A chaque methode numerique de Trio U correspond une classe derivant
de Zone_dis_base implementant les outils necessaires a la methode.
#include <Zone_dis_base.h>
Public Member Functions
Zone_dis_base ()
~Zone_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Associe une Zone a l'objet.
const Zone & zone () const
Renvoie la Zone associee a l'objet.
(version const)
Zone & zone ()
Renvoie la Zone associee a l'objet.
void associer_domaine_dis (const Domaine_dis &)
Associe un Domaine_dis a l'objet.
const Domaine_dis & domaine_dis () const
Domaine_dis & domaine_dis ()
virtual void discretiser ()=0
virtual void creer_elements_fictifs (const Zone_Cl_dis_base &)
virtual Frontiere_dis_base & frontiere_dis (int)=0
virtual const Frontiere_dis_base & frontiere_dis (int) const =0
int rang_frontiere (const Nom &)
int rang_frontiere (const Nom &) const
Renvoie le rang de la frontiere de Nom nom
Renvoie -1 si aucune frontiere ne s'appelle nom.
Frontiere_dis_base & frontiere_dis (const Nom &)
const Frontiere_dis_base & frontiere_dis (const Nom &) const
Renvoie la frontiere de Nom nom.
(On indexe les frontiere avec leur nom)
void ecrire_noms_bords (Sortie &) const
Ecriture des noms des bords sur un flot de sortie.
virtual void modifier_pour_Cl (const Conds_lim &)=0
virtual IntTab & face_sommets ()
virtual const IntTab & face_sommets () const
virtual IntTab & face_voisins ()
virtual const IntTab & face_voisins () const
int nb_elem () const
int nb_elem_tot () const
int nb_som () const
int nb_som_tot () const
int nb_front_Cl () const
virtual void init_dist_paroi_globale (const Conds_lim &conds_lim)
virtual const DoubleTab & y_elem () const
virtual const DoubleTab & y_faces () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Zone_dis_base & self_cast (Objet_U &)
static const Zone_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone la_zone
Ref_Domaine_dis le_domaine_dis
DoubleTab y_elem_
DoubleTab y_faces_
int dist_paroi_initialisee_ = 0
Detailed Description
classe Zone_dis_base
Cette classe est la base de la hierarchie des zones discretisees.
Un objet Zone est associe a la zone discretise.
A chaque methode numerique de Trio U correspond une classe derivant
de Zone_dis_base implementant les outils necessaires a la methode.
Definition at line 42 of file Zone_dis_base.h.
Constructor & Destructor Documentation
Zone_dis_base()
Zone_dis_base::Zone_dis_base ()
Definition at line 20 of file Zone_dis_base.cpp.
~Zone_dis_base()
Zone_dis_base::~Zone_dis_base () override
Definition at line 20 of file Zone_dis_base.cpp.
Member Function Documentation
associer_domaine_dis()
void Zone_dis_base::associer_domaine_dis (const Domaine_dis & un_domaine_dis)
Associe un Domaine_dis a l'objet.
Definition at line 101 of file Zone_dis_base.cpp.
{
  le_domaine_dis=un_domaine_dis;
}
References le_domaine_dis.
Referenced by Zone_dis::associer_domaine_dis().
associer_zone()
void Zone_dis_base::associer_zone (const Zone & une_zone)
Associe une Zone a l'objet.
Definition at line 82 of file Zone_dis_base.cpp.
{
  la_zone=une_zone;
}
References la_zone.
Referenced by Zone_dis::associer_zone(), Champ_Fonc_MED::creer(), Discretiser_domaine::interpreter_(), and Champ_Fonc_MED_Table_Temps::lire_donnees_champ().
creer_elements_fictifs()
void Zone_dis_base::creer_elements_fictifs (const Zone_Cl_dis_base &) virtual
Reimplemented in Zone_VDF.
Definition at line 186 of file Zone_dis_base.cpp.
{
  Cerr << "Zone_dis_base::creer_elements_fictifs should be overloaded by "<< que_suis_je() <<finl;
  assert(0);
  exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Zone_dis::creer_elements_fictifs().
discretiser()
virtual void Zone_dis_base::discretiser () pure virtual
Implemented in Zone_EF, Zone_EF_axi, Zone_Poly_base, Zone_VF, Zone_VEF_PreP1b, Zone_PolyMAC, Zone_PolyMAC_P0, Zone_VDF, and Zone_VEF.
Referenced by Zone_dis::discretiser().
domaine_dis() [1/2]
Domaine_dis & Zone_dis_base::domaine_dis () inline
Definition at line 138 of file Zone_dis_base.h.
{
  return le_domaine_dis.valeur();
}
References le_domaine_dis, and Ref_Domaine_dis::valeur().
domaine_dis() [2/2]
const Domaine_dis & Zone_dis_base::domaine_dis () const inline
Definition at line 133 of file Zone_dis_base.h.
{
  return le_domaine_dis.valeur();
}
References le_domaine_dis, and Ref_Domaine_dis::valeur().
Referenced by Op_Conv_EF_VEF_P1NC_Stab::completer(), Perte_Charge_VEF::completer(), Terme_Source_Rappel_T_VEF_Face::completer(), Echange_contact_Correlation_VEF::init(), Milieu_base::update_rho_cp(), and Echange_contact_VDF::verifier_correspondance().
ecrire_noms_bords()
void Zone_dis_base::ecrire_noms_bords (Sortie & os) const
Ecriture des noms des bords sur un flot de sortie.
Definition at line 181 of file Zone_dis_base.cpp.
{
  zone().ecrire_noms_bords(os);
}
References Zone::ecrire_noms_bords(), and zone().
face_sommets() [1/2]
IntTab & Zone_dis_base::face_sommets () virtual
Reimplemented in Zone_VF.
Definition at line 193 of file Zone_dis_base.cpp.
{
  Cerr << que_suis_je() << "does not implement the method face_sommets()"
       << finl;
  exit();
  throw;
  return face_sommets();
}
References Cerr, Process::exit(), face_sommets(), finl, and Objet_U::que_suis_je().
Referenced by Periodique::completer(), Postraitement_lata::ecrire_zone(), face_sommets(), and Postraitement_lata::lire_champs().
face_sommets() [2/2]
const IntTab & Zone_dis_base::face_sommets () const virtual
Reimplemented in Zone_VF.
Definition at line 202 of file Zone_dis_base.cpp.
{
  Cerr << que_suis_je() << "does not implement the method face_sommets()"
       << finl;
  exit();
  throw;
  return face_sommets();
}
References Cerr, Process::exit(), face_sommets(), finl, and Objet_U::que_suis_je().
face_voisins() [1/2]
IntTab & Zone_dis_base::face_voisins () virtual
Reimplemented in Zone_VF.
Definition at line 211 of file Zone_dis_base.cpp.
{
  Cerr << que_suis_je() << "does not implement the method face_voisins()"
       << finl;
  exit();
  throw;
  return face_voisins();
}
References Cerr, Process::exit(), face_voisins(), finl, and Objet_U::que_suis_je().
Referenced by face_voisins(), and Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries().
face_voisins() [2/2]
const IntTab & Zone_dis_base::face_voisins () const virtual
Reimplemented in Zone_VF.
Definition at line 220 of file Zone_dis_base.cpp.
{
  Cerr << que_suis_je() << "does not implement the method face_voisins()"
       << finl;
  exit();
  throw;
  return face_voisins();
}
References Cerr, Process::exit(), face_voisins(), finl, and Objet_U::que_suis_je().
frontiere_dis() [1/4]
Frontiere_dis_base & Zone_dis_base::frontiere_dis (const Nom & nom)
Definition at line 126 of file Zone_dis_base.cpp.
{
  return frontiere_dis(rang_frontiere(nom));
}
References frontiere_dis(), and rang_frontiere().
frontiere_dis() [2/4]
const Frontiere_dis_base & Zone_dis_base::frontiere_dis (const Nom & nom) const
Renvoie la frontiere de Nom nom.
(On indexe les frontiere avec leur nom)
Returns
Frontiere_dis_base&
Signification: la frontiere discretisee indexee
Contraintes:
Definition at line 121 of file Zone_dis_base.cpp.
{
  return frontiere_dis(rang_frontiere(nom));
}
References frontiere_dis(), and rang_frontiere().
frontiere_dis() [3/4]
virtual const Frontiere_dis_base & Zone_dis_base::frontiere_dis (int) const pure virtual
Implemented in Zone_VF.
frontiere_dis() [4/4]
virtual Frontiere_dis_base & Zone_dis_base::frontiere_dis (int) pure virtual
Implemented in Zone_VF.
Referenced by Champ_Generique_Extraction::completer(), Champ_front_calc::front_dis(), Champ_front_contact_VEF::front_dis(), frontiere_dis(), Zone_dis::frontiere_dis(), Champ_Generique_Extraction::get_champ(), Champ_front_calc::mettre_a_jour(), and rang_frontiere().
get_info()
const Type_info * Zone_dis_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Zone_Poly_base, Zone_VF, Zone_VF_inst, Zone_VEF_PreP1b, Zone_PolyMAC, Zone_PolyMAC_P0, Zone_VDF, and Zone_VEF.
Definition at line 20 of file Zone_dis_base.cpp.
info()
const Type_info * Zone_dis_base::info () static
Definition at line 20 of file Zone_dis_base.cpp.
init_dist_paroi_globale()
void Zone_dis_base::init_dist_paroi_globale (const Conds_lim & conds_lim) inline virtual
Reimplemented in Zone_Poly_base.
Definition at line 163 of file Zone_dis_base.h.
{
  Cerr << "Zone_dis_base::init_dist_paroi_globale() does nothing ! " << que_suis_je() << "Needs to overload it !" << finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Navier_Stokes_std::completer().
modifier_pour_Cl()
virtual void Zone_dis_base::modifier_pour_Cl (const Conds_lim &) pure virtual
Implemented in Zone_EF, Zone_Poly_base, Zone_VF, Zone_VEF_PreP1b, Zone_VEF, and Zone_VDF.
nb_elem()
int Zone_dis_base::nb_elem () const inline
Definition at line 143 of file Zone_dis_base.h.
{
  return zone().nb_elem();
}
References Zone::nb_elem(), and zone().
Referenced by Op_Div_PolyMAC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Source_Generique_P0_Elem::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::ajouter_blocs(), Terme_Source_Canal_perio_VDF_P0::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Elem::ajouter_blocs(), Terme_Source_Solide_SWIFT_VDF::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::ajouter_blocs(), Op_Div_PolyMAC::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Masse_PolyMAC_Elem::ajouter_blocs(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_elem(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_elem(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_elem_3D(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_elem_3D(), Op_Diff_VDF_Face_Axi_base::ajouter_elem(), Op_Dift_VDF_Face_Axi_base::ajouter_elem(), Op_Diff_VDF_Face_Axi_base::ajouter_elem_3D(), Op_Dift_VDF_Face_Axi_base::ajouter_elem_3D(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Assembleur_P_PolyMAC::assembler_continuite(), Assembleur_P_PolyMAC_P0::assembler_continuite(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Op_Diff_RotRot::associer(), Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Source_Dirac_VDF_Elem::associer_zones(), Source_Dirac_VEF_Face::associer_zones(), Champ_Q1NC::cal_rot_ordre1(), Champ_P1NC::cal_rot_ordre1(), Champ_Face::calcul_critere_Q(), Champ_P1NC::calcul_critere_Q(), Champ_Face::calcul_grad_u(), Champ_P1NC::calcul_grad_U(), Calcul_integrale_locale::Calcul_integrale_locale(), Champ_Face::calcul_S_barre(), Champ_P1NC::calcul_S_barre(), Op_Dift_EF_base::calculer_borne_locale(), Op_Dift_VDF_Face_base::calculer_borne_locale(), Op_Dift_VEF_base::calculer_borne_locale(), Champ_Face::calculer_dercov_axi(), Champ_Ostwald_VEF::calculer_dscald(), Champ_Face::calculer_dscald_centre_element(), Op_Diff_EF_base::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi(), EDO_Pression_th_VEF::calculer_grad(), Zone_EF::calculer_h_carre(), Zone_Poly_base::calculer_h_carre(), Zone_VEF::calculer_h_carre(), Op_Conv_VDF_base::calculer_pour_post(), Op_Diff_VEF_base::calculer_pour_post(), Champ_Face::calculer_rotationnel_ordre2_centre_element(), Traitement_particulier_NS_Brech_VEF::calculer_terme_destruction_K(), Traitement_particulier_NS_Brech_VEF::calculer_terme_production_K(), Source_Neutronique_VDF::calculer_Tmoyenne(), Navier_Stokes_std::completer(), Terme_Source_Rappel_T_VEF_Face::completer(), Op_Correlation::completer(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Champ_front_contact_VEF::connectivity_failed(), Assembleur_P_VDF::construire(), EF_discretisation::creer_champ_vorticite(), PolyMAC_discretisation::creer_champ_vorticite(), PolyMAC_P0_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::creer_champ_vorticite(), Zone_VDF::creer_elements_fictifs(), VDF_discretisation::critere_Q(), EF_discretisation::critere_Q(), PolyMAC_discretisation::critere_Q(), VEF_discretisation::critere_Q(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Div_PolyMAC::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Masse_PolyMAC_Elem::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Flux_interfacial_PolyMAC::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::dimensionner_blocs(), Travail_pression_PolyMAC::dimensionner_blocs(), Assembleur_P_PolyMAC::dimensionner_continuite(), Assembleur_P_PolyMAC_P0::dimensionner_continuite(), Champ_Face::dimensionner_tenseur_Grad(), EF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ_fonc_don(), PolyMAC_discretisation::discretiser_champ_fonc_don(), VEF_discretisation::discretiser_champ_fonc_don(), VDF_discretisation::discretiser_champ_fonc_don(), EF_discretisation::distance_paroi(), VEF_discretisation::distance_paroi(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_val_tot_sur_vol_base::evaluer(), Extraire_surface::extraire_surface(), Discretisation_tools::faces_to_cells(), Champ_Generique_Transformation::get_champ(), Champ_input_P0::getTemplate(), EF_discretisation::grad_T(), PolyMAC_discretisation::grad_T(), VEF_discretisation::grad_T(), VDF_discretisation::grad_u(), VEF_discretisation::grad_u(), Champ_Q1NC::gradient(), EF_discretisation::h_conv(), PolyMAC_discretisation::h_conv(), VEF_discretisation::h_conv(), Terme_Source_Canal_RANS_LES_VDF_Elem::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Zone_Poly_base::init_dist_paroi_globale(), Champ_Face_PolyMAC_P0::init_ve2(), Zone_VDF::init_virt_e_map(), Ch_front_var_instationnaire_dep::initialiser(), Champ_P0_VDF::integrale_espace(), Extraire_domaine::interpreter_(), Champ_Fonc_MED::lire(), Champ_Fonc_MED_Table_Temps::lire(), Traitement_particulier_NS_Pression_VEF::lire(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Brech_VEF::lire(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), EDO_Pression_th_VDF::masse_totale(), Champ_Fonc_Elem_PolyMAC_P0_TC::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_2D(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_3D(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Taux_cisaillement_P0_VDF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Elem::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Taux_cisaillement_P0_VEF::mettre_a_jour(), VDF_discretisation::modifier_champ_tabule(), VEF_discretisation::modifier_champ_tabule(), EF_discretisation::modifier_champ_tabule(), PolyMAC_discretisation::modifier_champ_tabule(), Assembleur_P_VEF::modifier_matrice(), Champ_P0_VDF::moyenne(), Champ_Fonc_P0_base::moyenne(), EOS_Tools_VDF::moyenne_vol(), Zone_EF::nb_elem_Cl(), Zone_Poly_base::nb_elem_Cl(), Zone_VEF::nb_elem_Cl(), Champ_Elem_PolyMAC::nb_valeurs_nodales(), Discretisation_tools::nodes_to_cells(), Assembleur_P_PolyMAC::norme_continuite(), Terme_Source_Canal_RANS_LES_VDF_Face::norme_vit(), Zone_PolyMAC::orthocentrer(), projette(), EF_discretisation::proprietes_physiques_fluide_Ostwald(), PolyMAC_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), VEF_discretisation::proprietes_physiques_fluide_Ostwald(), Assembleur_P_VDF::remplir(), Champ_P0_VDF::remplir_coord_noeuds(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Zone_EF_axi::remplir_tableau_origine(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), EOS_Tools_VDF::secmembre_divU_Z(), Terme_Source_Canal_perio_VDF_P0::source_convection_diffusion(), PolyMAC_P0_discretisation::taux_cisaillement(), VDF_discretisation::taux_cisaillement(), VEF_discretisation::taux_cisaillement(), Moyenne_volumique::traiter_champs(), update_matrice_NeumannP0P1(), update_matriceP0P1(), Champ_Face_PolyMAC_P0::update_ve2(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC_P0::valeur_aux_elems(), EF_discretisation::vorticite(), PolyMAC_discretisation::vorticite(), VDF_discretisation::vorticite(), VEF_discretisation::vorticite(), VDF_discretisation::y_plus(), EF_discretisation::y_plus(), and VEF_discretisation::y_plus().
nb_elem_tot()
int Zone_dis_base::nb_elem_tot () const inline
Definition at line 147 of file Zone_dis_base.h.
{
  return zone().nb_elem_tot();
}
References Zone::nb_elem_tot(), and zone().
Referenced by Champ_Elem_PolyMAC::affecter_(), Op_Div_PolyMAC::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion_vectoriel(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Div_PolyMAC::ajouter_blocs(), Op_Grad_PolyMAC_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Dift_Stab_VEF_Face::ajouter_cas_multiscalaire(), Op_Dift_Stab_VEF_Face::ajouter_cas_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Conv_Muscl_New_VEF_Face::ajouter_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_diffusion(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Op_Dift_Stab_VEF_Face::ajouter_diffusion(), Op_Dift_Stab_VEF_Face::ajouter_diffusion_vectoriel(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_operateur_centre(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Op_Dift_Stab_VEF_Face::ajouter_operateur_centre(), Op_Dift_Stab_VEF_Face::ajouter_operateur_centre_vectoriel(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), Masse_PolyMAC_Elem::appliquer_impl(), Assembleur_P_PolyMAC::assembler_continuite(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Champ_P1NC::cal_rot_ordre1(), grad_Champ_Face_PolyMAC_P0::calc_gradfve(), Champ_Face::calcul_critere_Q(), Champ_P1NC::calcul_critere_Q(), Champ_Face::calcul_grad_u(), Champ_P1NC::calcul_grad_U(), calcul_longueur_filtre(), Champ_Face::calcul_S_barre(), Champ_P1NC::calcul_S_barre(), Zone_EF::calculer_Bij(), Zone_EF::calculer_Bij_gen(), Zone_EF_axi::calculer_Bij_gen(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Dift_Stab_VEF_Face::calculer_coefficients(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Op_Conv_EF_VEF_P1NC_Stab::calculer_data_pour_dirichlet(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Champ_Ostwald_VEF::calculer_dscald(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), calculer_gradientP1NC(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Dift_Stab_VEF_Face::calculer_min(), Op_Diff_VEF_base::calculer_pour_post(), Op_Dift_VEF_Face::calculer_pour_post(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Assembleur_P_VEFPreP1B::changer_base_pression(), Assembleur_P_VEFPreP1B::changer_base_pression_inverse(), Assembleur_P_VEFPreP1B::changer_base_second_membre(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Assembleur_P_VDF::construire(), Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), Zone_VDF::creer_elements_fictifs(), Op_Div_PolyMAC_P0::dimensionner(), Op_VDF_Elem::dimensionner_bloc_vitesse(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Grad_VDF_Face::dimensionner_blocs(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Div_PolyMAC::dimensionner_blocs(), Op_Grad_PolyMAC_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::dimensionner_blocs(), Flux_interfacial_PolyMAC::dimensionner_blocs(), Force_Tchen_PolyMAC_P0::dimensionner_blocs(), Frottement_interfacial_PolyMAC_P0::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Assembleur_P_PolyMAC::dimensionner_continuite(), Assembleur_P_PolyMAC_P0::dimensionner_continuite(), Sous_zone_VF::discretiser(), Zone_Poly_base::discretiser(), Zone_VEF_PreP1b::discretiser(), Zone_PolyMAC::discretiser(), Source_WC_Chaleur_VEF::elem_to_face(), Source_WC_Chaleur_VDF::face_to_elem(), Discretisation_tools::faces_to_cells(), Zone_PolyMAC_P0::fgrad(), Champ_Generique_Transformation::get_champ(), Champ_Elem_PolyMAC::init_auxiliary_variables(), Zone_PolyMAC_P0::init_stencils(), Zone_VDF::init_virt_e_map(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Assembleur_P_PolyMAC::modifier_secmem_pour_incr_p(), Discretisation_tools::nodes_to_cells(), Zone_VEF_PreP1b::numero_premier_sommet(), Zone_VEF_PreP1b::numero_premiere_arete(), Zone_PolyMAC::orthocentrer(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Op_Conv_VEF_Face::remplir_fluent(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Champ_Elem_PolyMAC::reprendre(), EOS_Tools_VEF::secmembre_divU_Z(), Op_Conv_EF_VEF_P1NC_Stab::test(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), Champ_Face_PolyMAC_P0::trace(), Champ_Elem_PolyMAC::trace(), Champ_Q1NC_impl::transforme_coord2D(), Champ_Q1NC_impl::transforme_coord3D(), grad_Champ_Face_PolyMAC_P0::update_ge(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), Champ_Face_PolyMAC_P0::update_ve(), Champ_Elem_PolyMAC::valeur_aux_faces(), Zone_VEF::vecteur_face_facette(), and Op_Div_VEFP1B_Elem::volumique().
nb_front_Cl()
int Zone_dis_base::nb_front_Cl () const inline
Definition at line 159 of file Zone_dis_base.h.
{
  return zone().nb_front_Cl();
}
References Zone::nb_front_Cl(), and zone().
Referenced by Op_Grad_EF::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Source_Generique_VEF::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), ajouter_bord(), Op_Dift_EF_Q1::ajouter_bords(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Source_Fluide_Dilatable_VDF_Proto::ajouter_impl(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Assembleur_P_EF::assembler_mat(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Traitement_particulier_NS_EC::calculer_Ec(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), EDO_Pression_th_VEF::calculer_grad(), calculer_gradientP1NC(), Operateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Traitement_particulier_NS_Brech_VEF::calculer_terme_destruction_K(), Traitement_particulier_NS_Brech_VEF::calculer_terme_production_K(), Terme_Source_Canal_perio::completer(), Zone_Cl_VDF::completer(), Terme_Source_Canal_perio::compute_heat_flux(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Source_WC_Chaleur::correct_grad_boundary(), Zone_VDF::creer_elements_fictifs(), Zone_VF::discretiser(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_P1NC_implementation::filtrer_resu(), Champ_Generique_Tparoi_VEF::get_champ(), Turbulence_paroi_base::get_champ(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), Op_Div_PolyMAC::impr(), Op_Div_PolyMAC_P0::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEF_Elem::impr(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Op_Diff_VDF_base::init_op_ext(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Op_Diff_VEFP1NCP1B_Face::liste_face(), EDO_Pression_th_VDF::mettre_a_jour_CL(), EDO_Pression_th_VEF::mettre_a_jour_CL(), modif_matrice_pour_periodique_apres_contribuer(), modif_matrice_pour_periodique_avant_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), rang_frontiere(), Op_Conv_VEF_Face::remplir_fluent(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), remplir_marqueur_sommet_neumann(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), and Op_Diff_VEFP1NCP1B_Face::test().
nb_som()
int Zone_dis_base::nb_som () const inline
Definition at line 151 of file Zone_dis_base.h.
{
  return zone().nb_som();
}
References Zone::nb_som(), and zone().
Referenced by Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Solveur_Masse_EF::appliquer_impl(), Assembleur_P_VDF_Q4::assembler(), Op_Diff_RotRot::associer(), Zone_EF::calculer_porosites_sommets(), Zone_EF::calculer_volumes_sommets(), Discretisation_tools::cells_to_nodes(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Op_EF_base::dimensionner(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), EF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ_fonc_don(), PolyMAC_discretisation::discretiser_champ_fonc_don(), VEF_discretisation::discretiser_champ_fonc_don(), VDF_discretisation::discretiser_champ_fonc_don(), Zone_PolyMAC_P0::fgrad(), Op_Diff_PolyMAC_P0_Elem::init_som_ext(), modifieP1P1neumann(), Assembleur_P_VDF_Q4::modifier_secmem(), update_matrice_NeumannP0P1(), update_matrice_NeumannP1P1(), update_matrice_SymetrieP1P1(), update_matriceP0P1(), and update_matriceP1P1().
nb_som_tot()
int Zone_dis_base::nb_som_tot () const inline
Definition at line 155 of file Zone_dis_base.h.
{
  return zone().nb_som_tot();
}
References Zone::nb_som_tot(), and zone().
Referenced by PDF_model::affecter_vitesse_imposee(), Op_Conv_VEF_Face::ajouter(), calcul_longueur_filtre(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Discretisation_tools::cells_to_nodes(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), construit_connectivite_sommet(), Op_EF_base::dimensionner(), Zone_PolyMAC::discretiser(), Zone_PolyMAC_P0::fgrad(), Zone_Cl_VEFP1B::imposer_cond_lim(), Zone_Poly_base::init_som_elem(), Discretisation_tools::nodes_to_cells(), Zone_VEF_PreP1b::numero_premiere_arete(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), remplir_marqueur_sommet_neumann(), and Op_Div_VEFP1B_Elem::volumique().
printOn()
Sortie & Zone_dis_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Zone_Poly_base, Zone_VF, Zone_VF_inst, Zone_VEF_PreP1b, Zone_PolyMAC, Zone_PolyMAC_P0, Zone_VDF, and Zone_VEF.
Definition at line 40 of file Zone_dis_base.cpp.
{
  return os ;
}
rang_frontiere() [1/2]
int Zone_dis_base::rang_frontiere (const Nom & nom)
Definition at line 157 of file Zone_dis_base.cpp.
{
  for(int i=0; i<nb_front_Cl(); i++)
    if (frontiere_dis(i).le_nom()==nom)
      return i;
  Cerr << "We did not find the boundary name " << nom << " on the domain " << zone().domaine().le_nom() << finl;
  Cerr << "Check the given boundary name or the domain." << finl;
  exit();
  return -1;
}
References Cerr, Zone::domaine(), Process::exit(), finl, frontiere_dis(), Frontiere_dis_base::le_nom(), Domaine::le_nom(), nb_front_Cl(), and zone().
Referenced by Champ_front_contact_VEF::calcul_coeff_amort(), Extraire_surface::extraire_surface(), frontiere_dis(), Champ_Generique_Extraction::get_champ(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_front_contact_VEF::remplir_elems_voisin_bord(), and Champ_front_contact_VEF::test_faces_coin().
rang_frontiere() [2/2]
int Zone_dis_base::rang_frontiere (const Nom & nom) const
Renvoie le rang de la frontiere de Nom nom
Renvoie -1 si aucune frontiere ne s'appelle nom.
Returns
int
Signification: le rang de la frontiere si elle existe -1 sinon
Contraintes:
Definition at line 146 of file Zone_dis_base.cpp.
{
  for(int i=0; i<nb_front_Cl(); i++)
    if (frontiere_dis(i).le_nom()==nom)
      return i;
  Cerr << "We did not find the boundary name " << nom << " on the domain " << zone().domaine().le_nom() << finl;
  Cerr << "Check the given boundary name or the domain." << finl;
  exit();
  return -1;
}
References Cerr, Zone::domaine(), Process::exit(), finl, frontiere_dis(), Frontiere_dis_base::le_nom(), Domaine::le_nom(), nb_front_Cl(), and zone().
readOn()
Entree & Zone_dis_base::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Zone_Poly_base, Zone_VF, Zone_VF_inst, Zone_VEF_PreP1b, Zone_PolyMAC, Zone_PolyMAC_P0, Zone_VDF, and Zone_VEF.
Definition at line 63 of file Zone_dis_base.cpp.
{
  return is ;
}
self_cast() [1/2]
const Zone_dis_base & Zone_dis_base::self_cast (const Objet_U & r) static
Definition at line 20 of file Zone_dis_base.cpp.
self_cast() [2/2]
Zone_dis_base & Zone_dis_base::self_cast (Objet_U & r) static
Definition at line 20 of file Zone_dis_base.cpp.
y_elem()
virtual const DoubleTab & Zone_dis_base::y_elem () const inline virtual
Definition at line 81 of file Zone_dis_base.h.
{return y_elem_;} ;
References y_elem_.
Referenced by Navier_Stokes_std::completer().
y_faces()
virtual const DoubleTab & Zone_dis_base::y_faces () const inline virtual
Definition at line 82 of file Zone_dis_base.h.
{return y_faces_;} ;
References y_faces_.
zone() [1/2]
Zone & Zone_dis_base::zone () inline
Renvoie la Zone associee a l'objet.
Returns
Zone&
Signification: la zone associee a la zone discretisee
Contraintes:
Definition at line 128 of file Zone_dis_base.h.
{
  return la_zone.valeur();
}
References la_zone, and Ref_Zone::valeur().
zone() [2/2]
const Zone & Zone_dis_base::zone () const inline
Renvoie la Zone associee a l'objet.
(version const)
Returns
Zone&
Signification: la zone associee a la zone discretisee
Contraintes: reference constante
Definition at line 109 of file Zone_dis_base.h.
{
  return la_zone.valeur();
}
References la_zone, and Ref_Zone::valeur().
Referenced by Champ_implementation_P0::affecter_(), Champ_P1_isoP1Bulle::affecter_(), Op_Diff_EF::ajouter(), Op_Dift_EF_Q1::ajouter(), Op_Div_EF::ajouter(), Op_Grad_EF::ajouter(), Op_Curl_VEFP1B::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Rot_VEFP1B::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Source_Qdm_EF::ajouter(), Source_Scalaire_EF::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Source_PDF_EF::ajouter_(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion_vectoriel(), Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), ajouter_bord(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_cas_multiscalaire(), Op_Dift_Stab_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_Stab_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Op_Dift_Stab_VEF_Face::ajouter_diffusion(), Op_Dift_Stab_VEF_Face::ajouter_diffusion_vectoriel(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Op_Dift_Stab_VEF_Face::ajouter_operateur_centre(), Op_Dift_Stab_VEF_Face::ajouter_operateur_centre_vectoriel(), Op_Diff_EF::ajouter_scalaire_template(), Op_Dift_EF_Q1::ajouter_scalaire_template(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Conv_EF::ajouter_sous_cond(), Op_Conv_EF::ajouter_sous_cond_template(), Op_Diff_EF::ajouter_vectoriel_template(), Op_Dift_EF_Q1::ajouter_vectoriel_template(), assembler(), Assembleur_P_VDF_Q4::assembler(), Assembleur_P_EF::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Op_Diff_RotRot::assembler_matrice(), assemblerP0P1(), assemblerP0Pa(), assemblerP1P1(), assemblerP1Pa(), assemblerPaPa(), Op_Conv_VDF< OP_TYPE >::associer_(), Source_PDF_EF::associer_pb(), Terme_Source_Coriolis_VDF_Face::associer_pb(), Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Source_Dirac_VDF_Elem::associer_zones(), Source_Dirac_VEF_Face::associer_zones(), build_triofield(), Champ_Q1_EF::cal_rot_ordre1(), Champ_Q1NC::cal_rot_ordre1(), Champ_Face::calcul_duidxj(), Champ_front_contact_VEF::calcul_grads_locaux(), Zone_VDF::calcul_h(), calcul_longueur_filtre(), Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Op_Diff_P1NC_barprim::calculer(), Zone_EF::calculer_Bij(), Zone_EF::calculer_Bij_gen(), Zone_EF_axi::calculer_Bij_gen(), Aretes::calculer_centre_de_gravite(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Dift_Stab_VEF_Face::calculer_coefficients(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Moyenne_volumique::calculer_convolution_champ_elem(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Zone_VF::calculer_diametres_hydrauliques(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Dift_VEF_P1NCP1B_Face::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Dift_VEF_Face_Q1::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Op_Dift_Stab_VEF_Face::calculer_gradients(), Echange_contact_VDF::calculer_h_autre_pb(), Zone_EF::calculer_h_carre(), Zone_Poly_base::calculer_h_carre(), Zone_VEF::calculer_h_carre(), calculer_h_local(), Zone_EF::calculer_IPhi(), Zone_EF_axi::calculer_IPhi(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Dift_Stab_VEF_Face::calculer_min(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), Zone_VF::calculer_porosites(), Op_Conv_VDF_base::calculer_pour_post(), Op_Dift_VEF_Face::calculer_pour_post(), Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Zone_EF::calculer_volumes_entrelaces(), Zone_VEF::calculer_volumes_entrelaces(), Zone_EF::calculer_volumes_sommets(), Op_Diff_RotRot::calculer_vorticite(), Discretisation_tools::cells_to_nodes(), Assembleur_P_VEFPreP1B::changer_base_pression(), Assembleur_P_VEFPreP1B::changer_base_pression_inverse(), Assembleur_P_VEFPreP1B::changer_base_second_membre(), chercher_arete(), Champ_front_calc::completer(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Op_Conv_EF_Stab_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_base::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Grad_PolyMAC_Face::completer(), Op_Grad_PolyMAC_P0_Face::completer(), Eval_Puiss_Th_QC_VEF_Face::completer(), Flux_interfacial_PolyMAC::completer(), Echange_interne_global_impose::completer(), Champ_front_contact_VEF::completer(), Eval_Puiss_Th_VEF_Face::completer(), Eval_Source_C_VEF_Face::completer(), Terme_Source_Rappel_T_VEF_Face::completer(), Champ_Generique_Transformation::completer(), Champ_Post_Operateur_Eqn::completer(), Zone_Cl_VDF::completer(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), Source_PDF_EF::compute_vitesse_imposee_projete(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Champ_front_contact_VEF::connectivity_failed(), Scatter::construire_correspondance_aretes_par_coordonnees(), Zone_VEF_PreP1b::construire_ok_arete(), Zone_VEF_PreP1b::construire_renum_arete_perio(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Source_PDF_EF::contribuer_a_avec(), contribuer_matrice_NeumannP0Pa(), contribuer_matrice_NeumannP1Pa(), contribuer_matrice_NeumannPaPa(), contribuer_matrice_SymetrieP1Pa(), contribuer_matrice_SymetriePaPa(), contribuer_matriceP0Pa(), contribuer_matriceP1Pa(), contribuer_matricePaPa(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), corriger(), Zone_EF::creer_faces_virtuelles_non_std(), Zone_VEF::creer_faces_virtuelles_non_std(), Op_Div_VEFP1B_Elem::degres_liberte(), Zone_Poly_base::detecter_faces_non_planes(), Op_EF_base::dimensionner(), Op_VDF_Elem::dimensionner(), Op_VEF_Face::dimensionner(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Zone_EF::discretiser(), Zone_EF_axi::discretiser(), Sous_zone_VF::discretiser(), Zone_Poly_base::discretiser(), Zone_VF::discretiser(), Zone_VEF_PreP1b::discretiser(), Zone_PolyMAC::discretiser(), Zone_PolyMAC_P0::discretiser(), Zone_VDF::discretiser(), Zone_VEF::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), VEF_discretisation::discretiser_champ_fonc_don(), Discr_inst::discretiser_champ_fonc_don(), Zone_VEF_PreP1b::discretiser_suite(), Zone_VDF::dist_face_period(), distance_sommets(), Champ_Fonc_base::domaine(), Champ_Inc_base::domaine(), Zone_EF_axi::domaine_axi(), ecrire_noms_bords(), Op_Curl_VEFP1B::elements_pour_sommet(), Op_Diff_RotRot::elements_pour_sommet(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), exemple_champ_non_homogene(), Extraire_surface::extraire_surface(), Zone_PolyMAC_P0::fgrad(), Champ_P1NC_implementation::filtrer_H1(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Champ_Inc_P0_base::fixer_nb_valeurs_nodales(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Zone_VDF::genere_aretes(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_refChamp::get_ref_connectivity(), get_ref_coordinates_items(), Champ_implementation_base::get_zone_geom(), Champ_input_P0::getTemplate(), Champ_Q1_EF::gradient(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Zone_Cl_EF::imposer_cond_lim(), Source_PDF_EF::impr(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), Op_Div_PolyMAC::impr(), Op_Div_PolyMAC_P0::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEF_Elem::impr(), Champ_Fonc_P1_EF::imprime(), Champ_Fonc_Q1_EF::imprime(), Champ_P0_EF::imprime(), Champ_P1_EF::imprime(), Champ_Q1_EF::imprime(), Champ_Elem_PolyMAC::imprime(), Champ_Fonc_Som_PolyMAC::imprime(), Champ_Som_PolyMAC::imprime(), Champ_Fonc_Q1_VDF::imprime(), Champ_Fonc_Q1_VEF::imprime(), Zone_VF::ind_faces_virt_bord(), Zone_VF::info_elem_som(), Zone_VF::infobord(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Traitement_particulier_Solide_canal_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), Zone_Poly_base::init_dist_paroi_globale(), Zone_Poly_base::init_equiv(), Echange_contact_PolyMAC_P0::init_fs_dist(), Zone_Poly_base::init_som_elem(), Zone_PolyMAC_P0::init_stencils(), Champ_Face_PolyMAC_P0::init_ve2(), Zone_VDF::init_virt_e_map(), Raccord_distant_homogene::initialise(), Sonde::initialiser(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Echange_contact_VDF::initialiser(), Champ_front_recyclage::initialiser(), Porosites::interpreter(), Porosites_champ::interpreter(), Integrer_champ_med::interpreter(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), Op_Diff_VEFP1NCP1B_Face::isInStencil(), Zone_VF::joint(), Zone_VEF_PreP1b::lecture_ok_arete(), lecture_special_part2(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Perte_Charge_Singuliere::lire_surfaces(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Zone_PolyMAC::M1(), Eval_Dirac_VDF_Elem::mettre_a_jour(), Eval_Dirac_VEF_Face::mettre_a_jour(), Correlation_Vec_Sca_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Assembleur_P_VEFPreP1B::modifier_matrice(), Zone_EF::modifier_pour_Cl(), Zone_VEF_PreP1b::modifier_pour_Cl(), Zone_VEF::modifier_pour_Cl(), Assembleur_P_VDF_Q4::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Assembleur_P_EF::modifier_solution(), Assembleur_P_VEFPreP1B::modifier_solution(), Assembleur_P_VDF::modifier_solution(), Assembleur_P_VEF::modifier_solution(), multiplier_diviser_rho(), nb_elem(), Zone_VEF_PreP1b::nb_elem(), nb_elem_tot(), Zone_VF::nb_faces_bord(), nb_front_Cl(), Zone_VF::nb_joints(), nb_som(), Zone_VEF_PreP1b::nb_som(), nb_som_tot(), Discretisation_tools::nodes_to_cells(), norm_2D_vit1(), norm_2D_vit2(), norm_3D_vit1(), norm_3D_vit2(), Champ_P1NC::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Champ_P1_isoP1Bulle::norme_L2(), Zone_VF::numero_sommet_local(), Zone_PolyMAC::orthocentrer(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), Op_Conv_EF_Stab_PolyMAC_Elem::preparer_calcul(), Assembleur_P_VEFPreP1B::projete_L2(), projette(), rang_frontiere(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Assembleur_P_VEF::remplir(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_P0_VDF::remplir_coord_noeuds(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Zone_VF::remplir_face_numero_bord(), Op_Conv_VEF_Face::remplir_fluent(), Zone_Cl_VEF::remplir_normales_facettes_Cl(), Op_Diff_VEF_base::remplir_nu(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), remplir_sommets(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Zone_Cl_EF::remplir_type_elem_Cl(), Zone_Cl_VEF::remplir_type_elem_Cl(), Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(), Traitement_particulier_NS_canal_VDF::remplir_Y(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Zone_VDF::reordonner(), Zone_VEF::reordonner(), Champ_Elem_PolyMAC::reprendre(), Precond_local::res_syst_loc_hybride(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), Source_PDF_EF::rotate_imposed_velocity(), Champ_Fonc_base::sauvegarder(), EOS_Tools_VEF::secmembre_divU_Z(), second_membre(), som_pscal(), Op_Diff_RotRot::sommets_pour_element(), Op_Diff_RotRot::sommets_voisins(), Terme_Source_Canal_perio::source_convection_diffusion(), Terme_Source_Canal_perio_VDF_P0::source_convection_diffusion(), Op_Diff_VEFP1NCP1B_Face::test(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), Champ_Face_PolyMAC::trace(), update_matrice_NeumannP0Pa(), update_matrice_NeumannP1Pa(), update_matrice_NeumannPaPa(), update_matrice_SymetrieP1Pa(), update_matrice_SymetriePaPa(), update_matriceP0Pa(), update_matriceP1Pa(), update_matricePaPa(), updateP1P1(), updateP1Pa(), updatePaPa(), Champ_Inc_base::valeur_a(), Champ_Fonc_MED::valeur_a(), Champ_P1_isoP1Bulle::valeur_au_bord(), Champ_Fonc_base::valeur_aux(), Champ_Inc_base::valeur_aux(), Champ_Fonc_Face::valeur_aux_compo(), Champ_Inc_base::valeur_aux_compo(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_P1iP1B_implementation::valeur_aux_sommets(), Champ_Q1NC_impl::valeur_aux_sommets(), Champ_Q1NC_impl::valeur_aux_sommets_compo(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), Zone_VEF::vecteur_face_facette(), Source_PDF_EF::verif_ajouter_contrib(), Zone_EF::verifie_compatibilite_domaine(), Zone_EF_axi::verifie_compatibilite_domaine(), Zone_VEF_PreP1b::verifie_ok_arete(), verifier(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), Op_Div_EF::volumique(), Op_Div_PolyMAC::volumique(), Op_Div_PolyMAC_P0::volumique(), Op_Div_VDF_Elem::volumique(), Op_Div_VEF_Elem::volumique(), Zone_PolyMAC::W1(), Champ_implementation::zone(), Zone_dis::zone(), and Op_Diff_VEF_Face_Penalise::zone().
Member Data Documentation
dist_paroi_initialisee_
int Zone_dis_base::dist_paroi_initialisee_ = 0 protected
Definition at line 91 of file Zone_dis_base.h.
Referenced by Zone_Poly_base::init_dist_paroi_globale().
info_obj
const Type_info Zone_dis_base::info_obj static
Definition at line 45 of file Zone_dis_base.h.
la_zone
Ref_Zone Zone_dis_base::la_zone protected
Definition at line 86 of file Zone_dis_base.h.
Referenced by associer_zone(), and zone().
le_domaine_dis
Ref_Domaine_dis Zone_dis_base::le_domaine_dis protected
Definition at line 87 of file Zone_dis_base.h.
Referenced by associer_domaine_dis(), and domaine_dis().
y_elem_
DoubleTab Zone_dis_base::y_elem_ protected
Definition at line 89 of file Zone_dis_base.h.
Referenced by Zone_Poly_base::init_dist_paroi_globale(), and y_elem().
y_faces_
DoubleTab Zone_dis_base::y_faces_ protected
Definition at line 90 of file Zone_dis_base.h.
Referenced by Zone_Poly_base::init_dist_paroi_globale(), and y_faces().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Zone_dis_base.h
src/Kernel/Framework/Zone_dis_base.cpp