TRUST: Champ_Input_Proto Class Reference
Champ_Input_Proto Class Reference abstract
This is the base class for all the Fields which can be written by a call to
Problem::setInputField
There are for derived classes for uniform or not / domain or boundary fields.
All are supposed to be time-dependent.
Each Pb_base keeps a list of references to the Champ_Input_Proto it contains.
#include <Champ_Input_Proto.h>
Public Member Functions
virtual ~Champ_Input_Proto ()
virtual void getTemplate (TrioField &afield) const =0
virtual void setValue (const TrioField &afield)=0
void setInitialValue (const ArrOfDouble &vo)
virtual void setDoubleValue (const double val)
Protected Member Functions
void read (Entree &is)
Lecture d'un champ input dans un flot d'entree
Factorisation des readOn des differents Champ_input
Format:
{ nb_comp nombre_de_composantes_du_champ
nom nom_du_champ
probleme nom_du_probleme_base_associe
[sous_zone nom_de_la_sous_zone_associee] }.
void setValueOnTab (const TrioField &afield, DoubleTab &tab)
virtual void set_nb_comp (int i)=0
calls fixer_nb_comp
virtual void set_name (const Nom &name)=0
calls nommer
Protected Attributes
Ref_Probleme_base mon_pb
bool sous_zone_ok
This fields knows how to deal with a sous_zone.
Ref_Sous_Zone ma_sous_zone
ArrOfDouble initial_value_
Detailed Description
This is the base class for all the Fields which can be written by a call to
Problem::setInputField
There are for derived classes for uniform or not / domain or boundary fields.
All are supposed to be time-dependent.
Each Pb_base keeps a list of references to the Champ_Input_Proto it contains.
Definition at line 43 of file Champ_Input_Proto.h.
Constructor & Destructor Documentation
~Champ_Input_Proto()
virtual Champ_Input_Proto::~Champ_Input_Proto () inline virtual
Definition at line 48 of file Champ_Input_Proto.h.
{};
Member Function Documentation
getTemplate()
virtual void Champ_Input_Proto::getTemplate (TrioField & afield) const pure virtual
Implemented in Ch_front_input, Ch_front_input_uniforme, Champ_input_P0, Ch_input_uniforme, and Ch_front_input_P1.
Referenced by Probleme_U::getInputFieldTemplate().
read()
void Champ_Input_Proto::read (Entree & is) protected
Lecture d'un champ input dans un flot d'entree
Factorisation des readOn des differents Champ_input
Format:
{ nb_comp nombre_de_composantes_du_champ
nom nom_du_champ
probleme nom_du_probleme_base_associe
[sous_zone nom_de_la_sous_zone_associee] }.
Definition at line 50 of file Champ_Input_Proto.cpp.
{
  Nom nom_champ;
  Nom nom_pb;
  Nom nom_sous_zone;
  int nbc=-1;
// Lire nom_champ et nom_pb
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Motcle motlu;
  is >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "It was expected { to start to read the Champ_Input" << finl;
      Process::exit();
    }
  is >> motlu;
  while(1)
    {
      if (motlu == "nb_comp")
        {
          is >> nbc;
          set_nb_comp(nbc);
        }
      else if (motlu == "nom")
        {
          is >> nom_champ;
        }
      else if (motlu == "initial_value")
        {
          is >> initial_value_;
        }
      else if (motlu=="probleme")
        {
          is >> nom_pb;
        }
      else if (motlu=="sous_zone")
        {
          is >> nom_sous_zone;
        }
      else if (motlu == accolade_fermee)
        break;
      else
        {
          Cerr << "Error in Ch_front_input_uniforme::readOn" << finl;
          Cerr << "We expected a } instead of " << motlu << finl;
          Process::exit();
        }
      is >> motlu;
    }
  if (nom_champ=="??" || nom_pb=="??" || nbc==-1)
    {
      Cerr << "Error in Ch_front_input_uniforme::readOn" << finl;
      Cerr << "It must be define the name, problem and number of components" << motlu << finl;
      Process::exit();
    }
// Nommer le champ
  set_name(nom_champ);
// Retrouver le probleme et s'inscrire dans sa liste
  mon_pb=ref_cast(Probleme_base,Interprete::objet(nom_pb));
  ma_sous_zone.reset();
  if (nom_sous_zone!="??")
    {
      if (!sous_zone_ok)
        {
          Cerr << "Error in Ch_front_input_uniforme::readOn" << finl;
          Cerr << "The sous_zones are not managed by this field" << finl;
          Process::exit();
        }
      ma_sous_zone=mon_pb->domaine().ss_zone(nom_sous_zone);
    }
}
References Cerr, Probleme_base::domaine(), Process::exit(), finl, initial_value_, ma_sous_zone, mon_pb, Interprete::objet(), ref_cast, Ref_::reset(), set_name(), set_nb_comp(), sous_zone_ok, and Domaine::ss_zone().
Referenced by Ch_front_input::readOn(), Ch_front_input_uniforme::readOn(), Champ_input_P0::readOn(), and Ch_input_uniforme::readOn().
set_name()
virtual void Champ_Input_Proto::set_name (const Nom & name) protected pure virtual
calls nommer
Implemented in Ch_front_input, Champ_input_P0, Ch_front_input_uniforme, and Ch_input_uniforme.
Referenced by read().
set_nb_comp()
virtual void Champ_Input_Proto::set_nb_comp (int i) protected pure virtual
calls fixer_nb_comp
Implemented in Ch_front_input, Ch_front_input_uniforme, Champ_input_P0, and Ch_input_uniforme.
Referenced by read().
setDoubleValue()
void Champ_Input_Proto::setDoubleValue (const double val) virtual
Reimplemented in Ch_front_input.
Definition at line 154 of file Champ_Input_Proto.cpp.
{
  Cerr<< "You need to override setDoubleValue() in derived class of Champ_Input_Proto"<< finl;
  throw;
}
References Cerr, and finl.
Referenced by Probleme_U::setInputDoubleValue().
setInitialValue()
void Champ_Input_Proto::setInitialValue (const ArrOfDouble & vo)
Definition at line 149 of file Champ_Input_Proto.cpp.
{
  initial_value_=vo;
}
References initial_value_.
setValue()
virtual void Champ_Input_Proto::setValue (const TrioField & afield) pure virtual
Implemented in Ch_front_input, Ch_front_input_uniforme, Champ_input_P0, Ch_input_uniforme, and Ch_front_input_P1.
Referenced by Probleme_U::setInputField().
setValueOnTab()
void Champ_Input_Proto::setValueOnTab (const TrioField & afield, DoubleTab & tab) protected
Definition at line 126 of file Champ_Input_Proto.cpp.
{
  if (afield._type==0)
    {
      if ((afield._nb_elems!=tab.dimension(0))&&(afield._nb_elems!=tab.dimension_tot(0)))
        {
          throw WrongArgument(mon_pb.le_nom().getChar(),"setInputField",afield.getCharName(),"should have the same _nb_elems as returned by getInputFieldTemplate");
        }
    }
  else
    {
      if (afield._nbnodes!=tab.dimension(0))
        throw WrongArgument(mon_pb.le_nom().getChar(),"setInputField","afield","should have the same _nb_elems as returned by getInputFieldTemplate");
      if (afield._nb_field_components!=tab.dimension(1))
        throw WrongArgument(mon_pb.le_nom().getChar(),"setInputField","afield","should have the same _nb_field_components as returned by getInputFieldTemplate");
    }
// order is   c1 c2 c3   c1 c2 c3   c1 c2 c3
  memcpy(tab.addr(),afield._field,tab.size()*sizeof(double));
  tab.echange_espace_virtuel();
}
References TRUSTArray< _TYPE_ >::addr(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Nom::getChar(), O_U_Ptr::le_nom(), mon_pb, and TRUSTVect< _TYPE_ >::size().
Referenced by Ch_front_input::setValue(), Ch_front_input_uniforme::setValue(), Champ_input_P0::setValue(), Ch_input_uniforme::setValue(), and Ch_front_input_P1::setValue().
Member Data Documentation
initial_value_
ArrOfDouble Champ_Input_Proto::initial_value_ protected
Definition at line 68 of file Champ_Input_Proto.h.
Referenced by Ch_front_input_uniforme::initialiser(), Ch_front_input_P1::initialiser(), read(), Champ_input_P0::readOn(), Ch_input_uniforme::readOn(), and setInitialValue().
ma_sous_zone
Ref_Sous_Zone Champ_Input_Proto::ma_sous_zone protected
Definition at line 67 of file Champ_Input_Proto.h.
Referenced by Champ_input_P0::getTemplate(), read(), Champ_input_P0::readOn(), and Champ_input_P0::setValue().
mon_pb
Ref_Probleme_base Champ_Input_Proto::mon_pb protected
Definition at line 65 of file Champ_Input_Proto.h.
Referenced by Ch_front_input::buildSommetsFaces(), Ch_front_input::getTemplate(), Ch_front_input_uniforme::getTemplate(), Champ_input_P0::getTemplate(), Ch_input_uniforme::getTemplate(), Ch_front_input_P1::getTemplate(), read(), Ch_front_input::readOn(), Ch_front_input_uniforme::readOn(), Champ_input_P0::readOn(), Ch_input_uniforme::readOn(), Champ_input_P0::setValue(), and setValueOnTab().
sous_zone_ok
bool Champ_Input_Proto::sous_zone_ok protected
This fields knows how to deal with a sous_zone.
Definition at line 66 of file Champ_Input_Proto.h.
Referenced by read(), Ch_front_input::readOn(), Ch_front_input_uniforme::readOn(), Champ_input_P0::readOn(), and Ch_input_uniforme::readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Input_Proto.h
src/Kernel/Champs/Champ_Input_Proto.cpp