TRUST: Matrice_Bloc Class Reference
Matrice_Bloc Class Reference
#include <Matrice_Bloc.h>
Public Member Functions
~Matrice_Bloc ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int ordre (void) const override
int nb_lignes (void) const override
int nb_colonnes (void) const override
DoubleVect & ajouter_multvect_ (const DoubleVect &x, DoubleVect &r) const override
DoubleVect & ajouter_multvectT_ (const DoubleVect &x, DoubleVect &r) const override
DoubleTab & ajouter_multTab_ (const DoubleTab &x, DoubleTab &r) const override
void scale (const double x) override
void get_stencil (IntTab &stencil) const override
void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const override
Sortie & imprimer (Sortie &s) const override
Sortie & imprimer_formatte (Sortie &s) const override
virtual void dimensionner (int N, int M)
virtual const Matrice & get_bloc (int i, int j) const
virtual Matrice & get_bloc (int i, int j)
void build_stencil (void) override
Matrice_Bloc (int N=0, int M=0)
int dim (int d) const
si d=0 => N_ si d=1 => M_
int nb_bloc_lignes (void) const
retourne N_
int nb_bloc_colonnes (void) const
retourne M_
void remplir (const IntLists &voisins, const DoubleLists &valeurs, const DoubleVect &terme_diag, const int i, const int n)
void remplir (const IntLists &voisins, const DoubleLists &valeurs, const int i, const int n, const int j, const int m)
void remplir (const IntLists &voisins, const DoubleLists &valeurs, const DoubleVect &terme_diag, const int i, const int n, const int j, const int m)
void BlocToMatMorse (Matrice_Morse &matrix) const
Matrice_Bloc & operator*= (double x)
bool check_block_matrix_structure (void) const
void assert_check_block_matrix_structure (void) const
Public Member Functions inherited from Matrice_Base
Matrice_Base ()
~Matrice_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual int ordre () const =0
virtual int nb_lignes () const =0
virtual int nb_colonnes () const =0
virtual DoubleVect & ajouter_multvect_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleVect & ajouter_multvectT_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleTab & ajouter_multTab_ (const DoubleTab &x, DoubleTab &r) const =0
virtual DoubleVect & ajouter_multvect (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleVect & ajouter_multvectT (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleTab & ajouter_multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice represente par un tableau)
Operation: R = R + A*X.
virtual DoubleVect & multvect_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvect (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice.
Operation: r = A*x.
virtual DoubleVect & multvectT_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvectT (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice transposee.
Operation: r = AT*x.
virtual DoubleTab & multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Multiplication d'une matrice representee par un tableau par la matrice.
Operation: R = A*X.
virtual Sortie & imprimer (Sortie &) const
virtual Sortie & imprimer_formatte (Sortie &s) const
virtual void scale (const double x)=0
virtual void get_stencil (IntTab &stencil) const
virtual void get_symmetric_stencil (IntTab &stencil) const
virtual void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
virtual void get_symmetric_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
int get_stencil_size (void) const
virtual void build_stencil (void)
void set_stencil (const IntTab &stencil)
bool is_stencil_up_to_date (void) const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Matrice_Bloc & self_cast (Objet_U &)
static const Matrice_Bloc & self_cast (const Objet_U &)
Static Public Member Functions inherited from Matrice_Base
static const Type_info * info ()
static Matrice_Base & self_cast (Objet_U &)
static const Matrice_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Matrice_Base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Vect_Matrice blocs_
les blocs de la matrices source A
int N_
1ere dim de A
int M_
2eme dim de A
int nb_blocs_
nb total des blocs de A (= N_ * M_)
ArrOfInt offsets_
Protected Attributes inherited from Matrice_Base
bool is_stencil_up_to_date_
IntTab stencil_
Detailed Description
Definition at line 48 of file Matrice_Bloc.h.
Constructor & Destructor Documentation
~Matrice_Bloc()
Matrice_Bloc::~Matrice_Bloc ()
Definition at line 23 of file Matrice_Bloc.cpp.
Matrice_Bloc()
Matrice_Bloc::Matrice_Bloc (int N = 0, int M = 0)
Definition at line 597 of file Matrice_Bloc.cpp.
                                         : Matrice_Base( )
{
  dimensionner(N,M);
  is_stencil_up_to_date_ = false ;
}
References dimensionner(), and Matrice_Base::is_stencil_up_to_date_.
Member Function Documentation
ajouter_multTab_()
DoubleTab & Matrice_Bloc::ajouter_multTab_ (const DoubleTab & x, DoubleTab & r) const override virtual
Implements Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
Definition at line 172 of file Matrice_Bloc.cpp.
{
  Cerr << "Error in 'Matrice_Bloc::ajouter_multTab_()':" << finl;
  Cerr << "  Not yet implemented" << finl;
  Process::exit( );
  return r;
}
References Cerr, Process::exit(), and finl.
ajouter_multvect_()
DoubleVect & Matrice_Bloc::ajouter_multvect_ (const DoubleVect & x, DoubleVect & r) const override virtual
< Une sous-partie de x
< Une sous-partie de y
< Premier element de r du bloc courant Boucle sur les lignes de blocs
< Premier element de x du bloc courant Boucle sur les colonnes de blocs
Implements Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
Definition at line 106 of file Matrice_Bloc.cpp.
{
  const double * const_x_addr = x.addr( );
  double * x_addr = ( double * ) const_x_addr;
  double * r_addr = r.addr( );
  DoubleVect x_bloc; //!< Une sous-partie de x
  DoubleVect r_bloc; //!< Une sous-partie de y
  int r_bloc_debut = 0; //!< Premier element de r du bloc courant Boucle sur les lignes de blocs
//
  for ( int i_ligne = 0; i_ligne < N_; ++i_ligne )
    {
      const int r_bloc_size = get_bloc( i_ligne, 0 ).valeur( ).nb_lignes( );
      r_bloc.ref_data( r_addr + r_bloc_debut, r_bloc_size );
      assert( r_bloc_debut+r_bloc_size <= r.size_array( ) );
      int x_bloc_debut = 0; //!< Premier element de x du bloc courant Boucle sur les colonnes de blocs
//
      for ( int i_colonne = 0; i_colonne < M_; ++i_colonne )
        {
          const Matrice& sub_bloc = get_bloc( i_ligne, i_colonne );
          const int x_bloc_size = sub_bloc.valeur( ).nb_colonnes( );
          x_bloc.ref_data( x_addr + x_bloc_debut, x_bloc_size );
          assert( x_bloc_debut+x_bloc_size <= x.size_array( ) );
          sub_bloc.valeur( ).ajouter_multvect_( x_bloc, r_bloc );
          x_bloc_debut += x_bloc_size;
        }
      r_bloc_debut += r_bloc_size;
    }
  return r;
}
References TRUSTArray< _TYPE_ >::addr(), Matrice_Base::ajouter_multvect_(), get_bloc(), M_, N_, Matrice_Base::nb_colonnes(), Matrice_Base::nb_lignes(), TRUSTVect< _TYPE_ >::ref_data(), TRUSTArray< _TYPE_ >::size_array(), and Deriv_Matrice_Base::valeur().
ajouter_multvectT_()
DoubleVect & Matrice_Bloc::ajouter_multvectT_ (const DoubleVect & x, DoubleVect & r) const override virtual
< Une sous-partie de x
< Une sous-partie de r
< Premier element de r du bloc courant Boucle sur les lignes de blocs
< Premier element de x du bloc courant Boucle sur les colonnes de blocs
Implements Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
Definition at line 139 of file Matrice_Bloc.cpp.
{
  const double * const_x_addr = x.addr( );
  double * x_addr = ( double * ) const_x_addr;
  double * r_addr = r.addr( );
  DoubleVect x_bloc; //!< Une sous-partie de x
  DoubleVect r_bloc; //!< Une sous-partie de r
  int r_bloc_debut = 0; //!< Premier element de r du bloc courant Boucle sur les lignes de blocs
//
  for ( int i_ligne = 0; i_ligne < M_; ++i_ligne )
    {
      const int r_bloc_size = get_bloc( 0, i_ligne ).valeur( ).nb_colonnes( );
      r_bloc.ref_data( r_addr + r_bloc_debut, r_bloc_size );
      assert( r_bloc_debut+r_bloc_size <= r.size_array( ) );
      int x_bloc_debut = 0; //!< Premier element de x du bloc courant Boucle sur les colonnes de blocs
//
      for ( int i_colonne = 0; i_colonne < N_; ++i_colonne )
        {
          const Matrice& sub_bloc = get_bloc( i_colonne, i_ligne );
          const int x_bloc_size = sub_bloc.valeur( ).nb_lignes( );
          x_bloc.ref_data( x_addr + x_bloc_debut, x_bloc_size );
          assert( x_bloc_debut+x_bloc_size <= x.size_array( ) );
          sub_bloc.valeur( ).ajouter_multvectT_( x_bloc, r_bloc );
          x_bloc_debut += x_bloc_size;
        }
      r_bloc_debut += r_bloc_size;
    }
  return r;
}
References TRUSTArray< _TYPE_ >::addr(), Matrice_Base::ajouter_multvectT_(), get_bloc(), M_, N_, Matrice_Base::nb_colonnes(), Matrice_Base::nb_lignes(), TRUSTVect< _TYPE_ >::ref_data(), TRUSTArray< _TYPE_ >::size_array(), and Deriv_Matrice_Base::valeur().
assert_check_block_matrix_structure()
void Matrice_Bloc::assert_check_block_matrix_structure (void) const
Definition at line 902 of file Matrice_Bloc.cpp.
{
#ifndef NDEBUG
  if ( ! ( check_block_matrix_structure( ) ) )
    {
      Cerr << "Error in 'Matrice_Bloc::assert_check_block_matrix_structure( )':" << finl;
      Cerr << "  Exiting..." << finl;
      Process::exit( );
    }
#endif
}
References Cerr, check_block_matrix_structure(), Process::exit(), and finl.
Referenced by get_stencil(), and get_stencil_and_coefficients().
BlocToMatMorse()
void Matrice_Bloc::BlocToMatMorse (Matrice_Morse & matrix) const
Definition at line 627 of file Matrice_Bloc.cpp.
{
  Matrix_tools::convert_to_morse_matrix( (*this), result );
}
References Matrix_tools::convert_to_morse_matrix().
Referenced by Solv_Petsc::resoudre_systeme().
build_stencil()
void Matrice_Bloc::build_stencil (void) override virtual
Reimplemented from Matrice_Base.
Definition at line 293 of file Matrice_Bloc.cpp.
{
  const int nb_line_blocks   = nb_bloc_lignes( );
  const int nb_column_blocks = nb_bloc_colonnes( );
  const int nb_stencils      = nb_line_blocks * nb_column_blocks;
  VECT( IntTab ) local_stencils;
  local_stencils.dimensionner( nb_stencils );
  int imin = 0;
  int imax = 0;
  int jmin = 0;
  int jmax = 0;
  for ( int i=0; i<nb_line_blocks; ++i )
    {
      for ( int j=0; j<nb_column_blocks; ++j )
        {
          const Matrice_Base& local_matrix = get_bloc( i, j ).valeur( );
          imax = imin + local_matrix.nb_lignes( );
          jmax = jmin + local_matrix.nb_colonnes( );
          IntTab& local_stencil = local_stencils[ i * nb_column_blocks + j ];
          local_matrix.get_stencil( local_stencil );
          const int size = local_stencil.dimension( 0 );
          for ( int k=0; k<size; ++k )
            {
              local_stencil( k, 0 ) += imin;
              local_stencil( k, 1 ) += jmin;
            }
          jmin = jmax;
        }
      imin = imax;
      jmin = 0;
    }
  const int nb_lines = nb_lignes( );
  ArrOfInt offsets( nb_lines + 1 );
  offsets[ 0 ] = 0;
  for ( int i=0; i<nb_stencils; ++i )
    {
      const IntTab& local_stencil = local_stencils[ i ];
      const int size = local_stencil.dimension( 0 );
      for ( int k=0; k<size; ++k )
        {
          const int line = local_stencil( k, 0 );
          offsets[ line + 1 ] += 1;
        }
    }
  for ( int i=0; i<nb_lines; ++i )
    {
      offsets[ i + 1 ] += offsets[ i ];
    }
  offsets_ = offsets ;
  const int stencil_size = offsets[ nb_lines ];
  stencil_.resize( stencil_size, 2 );
  stencil_ = -1;
  for ( int i=0; i<nb_stencils; ++i )
    {
      const IntTab& local_stencil = local_stencils[ i ];
      const int size = local_stencil.dimension( 0 );
      for ( int k=0; k<size; ++k )
        {
          const int line   = local_stencil( k, 0 );
          const int column = local_stencil( k, 1 );
          const int index  = offsets[ line ];
          assert( stencil_( index, 0 ) < 0 );
          assert( stencil_( index, 1 ) < 0 );
          assert( index < offsets[ line + 1 ] );
          stencil_( index, 0 )  = line;
          stencil_( index, 1 )  = column;
          offsets[ line ]     += 1;
        }
    }
  is_stencil_up_to_date_ = true ;
}
References TRUSTTab< _TYPE_ >::dimension(), get_bloc(), Matrice_Base::get_stencil(), Matrice_Base::is_stencil_up_to_date_, nb_bloc_colonnes(), nb_bloc_lignes(), Matrice_Base::nb_colonnes(), Matrice_Base::nb_lignes(), nb_lignes(), offsets_, TRUSTTab< _TYPE_ >::resize(), Matrice_Base::stencil_, Deriv_Matrice_Base::valeur(), and VECT.
check_block_matrix_structure()
bool Matrice_Bloc::check_block_matrix_structure (void) const
Definition at line 865 of file Matrice_Bloc.cpp.
{
  const int nb_line_blocks   = nb_bloc_lignes( );
  const int nb_column_blocks = nb_bloc_colonnes( );
  for ( int i=0; i<nb_line_blocks; ++i )
    {
      int nb_lines = get_bloc( i, 0 ).valeur( ).nb_lignes( );
      for ( int j=0; j<nb_column_blocks; ++j )
        {
          if ( nb_lines != get_bloc( i, j ).valeur( ).nb_lignes( ) )
            {
              Cerr << "Invalid number of lines in bloc ( " << i << ", " << j << " )" << finl;
              return false;
            }
        }
    }
  for ( int j=0; j<nb_column_blocks; ++j )
    {
      int nb_columns = get_bloc( 0, j ).valeur( ).nb_colonnes( );
      for ( int i=0; i<nb_line_blocks; ++i )
        {
          if ( nb_columns != get_bloc( i, j ).valeur( ).nb_colonnes( ) )
            {
              Cerr << "Invalid number of columns in bloc ( " << i << ", " << j << " )" << finl;
              return false;
            }
        }
    }
  return true;
}
References Cerr, finl, get_bloc(), nb_bloc_colonnes(), nb_bloc_lignes(), Matrice_Base::nb_colonnes(), nb_colonnes(), Matrice_Base::nb_lignes(), nb_lignes(), Deriv_Matrice_Base::valeur(), and valeur().
Referenced by assert_check_block_matrix_structure().
cree_instance()
Objet_U * Matrice_Bloc::cree_instance () static
Definition at line 23 of file Matrice_Bloc.cpp.
dim()
int Matrice_Bloc::dim (int d) const
si d=0 => N_ si d=1 => M_
Definition at line 603 of file Matrice_Bloc.cpp.
{
  if ( d==0 )
    {
      return N_;
    }
  else
    {
      return M_;
    }
}
References M_, and N_.
dimensionner()
void Matrice_Bloc::dimensionner (int N, int M) virtual
Reimplemented in Matrice_Bloc_Sym.
Definition at line 551 of file Matrice_Bloc.cpp.
{
  N_ = N;
  M_ = M;
  nb_blocs_ = N*M;
  blocs_.dimensionner(nb_blocs_);
}
References blocs_, vect_impl::dimensionner(), M_, N_, and nb_blocs_.
Referenced by Assembleur_P_EF::assembler_mat(), Assembleur_P_VDF::construire(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), Simple::iterer_eqs(), SETS::iterer_NS(), Matrice_Bloc(), remplir(), Assembleur_P_VEF::remplir(), and Op_Diff_PolyMAC_base::update_aux().
duplique()
int Matrice_Bloc::duplique () const override virtual
Implements Objet_U.
Reimplemented in Matrice_Bloc_Sym.
Definition at line 23 of file Matrice_Bloc.cpp.
get_bloc() [1/2]
Matrice & Matrice_Bloc::get_bloc (int i, int j) virtual
Reimplemented in Matrice_Bloc_Sym.
Definition at line 578 of file Matrice_Bloc.cpp.
{
  if ( ( i<0 ) || ( i>=N_ ) )
    {
      Cerr << "Error in 'Matrice_Bloc::get_bloc()': " << finl;
      Cerr << "  Line index is out of range" << finl;
      Process::exit( );
    }
  if ( ( j<0 ) || ( j>=M_ ) )
    {
      Cerr << "Error in 'Matrice_Bloc::get_bloc()': " << finl;
      Cerr << "  Column index is out of range" << finl;
      Process::exit( );
    }
  return blocs_[i * M_ + j];
}
References blocs_, Cerr, Process::exit(), finl, M_, and N_.
get_bloc() [2/2]
const Matrice & Matrice_Bloc::get_bloc (int i, int j) const virtual
Reimplemented in Matrice_Bloc_Sym.
Definition at line 559 of file Matrice_Bloc.cpp.
{
  if ( ( i<0 ) || ( i>=N_ ) )
    {
      Cerr << "Error in 'Matrice_Bloc::get_bloc()': " << finl;
      Cerr << "  Line index is out of range" << finl;
      Process::exit( );
    }
  if ( ( j<0 ) || ( j>=M_ ) )
    {
      Cerr << "Error in 'Matrice_Bloc::get_bloc()': " << finl;
      Cerr << "  Column index is out of range" << finl;
      Process::exit( );
    }
  return blocs_[i * M_ + j];
}
References blocs_, Cerr, Process::exit(), finl, M_, and N_.
Referenced by ajouter_multvect_(), ajouter_multvectT_(), Assembleur_P_EF::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Assembleur_P_EF::assembler_QC(), Assembleur_P_PolyMAC::assembler_QC(), Assembleur_P_VDF::assembler_QC(), build_stencil(), check_block_matrix_structure(), Assembleur_P_VDF::construire(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), get_stencil(), get_stencil_and_coefficients(), imprimer(), imprimer_formatte(), Simple::iterer_eqs(), SETS::iterer_NS(), Solveur_U_P::iterer_NS(), Champ_P1NC_implementation::Mat_Morse_to_Mat_Bloc(), modifieP1P1neumann(), Assembleur_P_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), nb_colonnes(), nb_lignes(), operation01(), operation11(), SSOR::preconditionner_(), ILU::prepare_(), Precond_local::prepare_(), Solv_GCP::prepare_data(), remplir(), Assembleur_P_VEF::remplir(), Assembleur_P_VDF::remplir(), Solv_Cholesky::resoudre_systeme(), Solv_Gen::resoudre_systeme(), Solv_Gmres::resoudre_systeme(), Solv_Petsc::resoudre_systeme(), scale(), SSOR::ssor(), Op_Diff_PolyMAC_base::update_aux(), updateP0P1(), updateP0Pa(), updateP1P1(), updateP1Pa(), updatePaPa(), and zero().
get_info()
const Type_info * Matrice_Bloc::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
Definition at line 23 of file Matrice_Bloc.cpp.
get_stencil()
void Matrice_Bloc::get_stencil (IntTab & stencil) const override virtual
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
Definition at line 198 of file Matrice_Bloc.cpp.
{
  assert_check_block_matrix_structure( );
  if(  is_stencil_up_to_date_ )
    {
      stencil = stencil_;
      return;
    }
  const int nb_line_blocks   = nb_bloc_lignes( );
  const int nb_column_blocks = nb_bloc_colonnes( );
  const int nb_stencils      =  nb_line_blocks * nb_column_blocks;
  VECT( IntTab ) local_stencils;
  local_stencils.dimensionner( nb_stencils );
  int imin = 0;
  int imax = 0;
  int jmin = 0;
  int jmax = 0;
  for ( int i=0; i<nb_line_blocks; ++i )
    {
      for ( int j=0; j<nb_column_blocks; ++j )
        {
          const Matrice_Base& local_matrix = get_bloc( i, j ).valeur( );
          imax = imin + local_matrix.nb_lignes( );
          jmax = jmin + local_matrix.nb_colonnes( );
          IntTab& local_stencil = local_stencils[ i * nb_column_blocks + j ];
          local_matrix.get_stencil( local_stencil );
          const int size = local_stencil.dimension( 0 );
          for ( int k=0; k<size; ++k )
            {
              local_stencil( k, 0 ) += imin;
              local_stencil( k, 1 ) += jmin;
            }
          jmin = jmax;
        }
      imin = imax;
      jmin = 0;
    }
  const int nb_lines = nb_lignes( );
  ArrOfInt offsets( nb_lines + 1 );
  offsets[ 0 ] = 0;
  for ( int i=0; i<nb_stencils; ++i )
    {
      const IntTab& local_stencil = local_stencils[ i ];
      const int size = local_stencil.dimension( 0 );
      for ( int k=0; k<size; ++k )
        {
          const int line = local_stencil( k, 0 );
          offsets[ line + 1 ] += 1;
        }
    }
  for ( int i=0; i<nb_lines; ++i )
    {
      offsets[ i + 1 ] += offsets[ i ];
    }
  const int stencil_size = offsets[ nb_lines ];
  stencil.resize( stencil_size, 2 );
  stencil = -1;
  for ( int i=0; i<nb_stencils; ++i )
    {
      const IntTab& local_stencil = local_stencils[ i ];
      const int size = local_stencil.dimension( 0 );
      for ( int k=0; k<size; ++k )
        {
          const int line   = local_stencil( k, 0 );
          const int column = local_stencil( k, 1 );
          const int index  = offsets[ line ];
          assert( stencil( index, 0 ) < 0 );
          assert( stencil( index, 1 ) < 0 );
          assert( index < offsets[ line + 1 ] );
          stencil( index, 0 )  = line;
          stencil( index, 1 )  = column;
          offsets[ line ]     += 1;
        }
    }
}
References assert_check_block_matrix_structure(), TRUSTTab< _TYPE_ >::dimension(), get_bloc(), Matrice_Base::get_stencil(), Matrice_Base::is_stencil_up_to_date_, nb_bloc_colonnes(), nb_bloc_lignes(), Matrice_Base::nb_colonnes(), Matrice_Base::nb_lignes(), nb_lignes(), TRUSTTab< _TYPE_ >::resize(), Matrice_Base::stencil_, Deriv_Matrice_Base::valeur(), and VECT.
get_stencil_and_coefficients()
void Matrice_Bloc::get_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const override virtual
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
Definition at line 384 of file Matrice_Bloc.cpp.
{
  assert_check_block_matrix_structure( );
  const int nb_line_blocks   = nb_bloc_lignes( );
  const int nb_column_blocks = nb_bloc_colonnes( );
  int imin = 0;
  int imax = 0;
  int jmin = 0;
  int jmax = 0;
  if( is_stencil_up_to_date_ )
    {
      stencil = stencil_;
      ArrOfInt offsets = offsets_;
      const int stencil_size = stencil_.dimension(0);
      coefficients.resize_array( stencil_size );
      IntTab      local_stencil;
      ArrOfDouble local_coeff;
      for ( int i=0; i<nb_line_blocks; ++i )
        {
          for ( int j=0; j<nb_column_blocks; ++j )
            {
              const Matrice_Base& local_matrix = get_bloc( i, j ).valeur( );
              imax = imin + local_matrix.nb_lignes( );
              jmax = jmin + local_matrix.nb_colonnes( );
              local_matrix.get_stencil_and_coefficients( local_stencil, local_coeff );
              const int size = local_stencil.dimension( 0 );
              for ( int k=0; k<size; ++k )
                {
                  const int line           = local_stencil( k, 0 ) + imin;
                  const double coefficient = local_coeff[ k ];
                  const int index          = offsets[ line ];
                  coefficients[ index ] = coefficient;
                  offsets[ line ] += 1;
                }
              jmin = jmax;
            }
          imin = imax;
          jmin = 0;
        }
      return;
    }
  const int nb_stencils      =  nb_line_blocks * nb_column_blocks;
  VECT( IntTab ) vect_local_stencils;
  vect_local_stencils.dimensionner( nb_stencils );
  VECT( ArrOfDouble ) vect_local_coefficients;
  vect_local_coefficients.dimensionner( nb_stencils );
  for ( int i=0; i<nb_line_blocks; ++i )
    {
      for ( int j=0; j<nb_column_blocks; ++j )
        {
          const Matrice_Base& local_matrix = get_bloc( i, j ).valeur( );
          imax = imin + local_matrix.nb_lignes( );
          jmax = jmin + local_matrix.nb_colonnes( );
          IntTab&      local_stencil = vect_local_stencils[ i * nb_column_blocks + j ];
          ArrOfDouble& local_coefficients = vect_local_coefficients[i * nb_column_blocks + j ];
          local_matrix.get_stencil_and_coefficients( local_stencil, local_coefficients );
          const int size = local_stencil.dimension( 0 );
          for ( int k=0; k<size; ++k )
            {
              local_stencil( k, 0 ) += imin;
              local_stencil( k, 1 ) += jmin;
            }
          jmin = jmax;
        }
      imin = imax;
      jmin = 0;
    }
  const int nb_lines = nb_lignes( );
  ArrOfInt offsets( nb_lines + 1 );
  offsets[ 0 ] = 0;
  for ( int i=0; i<nb_stencils; ++i )
    {
      const IntTab& local_stencil = vect_local_stencils[ i ];
      const int size = local_stencil.dimension( 0 );
      for ( int k=0; k<size; ++k )
        {
          const int line = local_stencil( k, 0 );
          offsets[ line + 1 ] += 1;
        }
    }
  for ( int i=0; i<nb_lines; ++i )
    {
      offsets[ i + 1 ] += offsets[ i ];
    }
  const int stencil_size = offsets[ nb_lines ];
  stencil.resize( stencil_size, 2 );
  coefficients.resize_array( stencil_size );
  stencil = -1;
  for ( int i=0; i<nb_stencils; ++i )
    {
      const IntTab&      local_stencil= vect_local_stencils[ i ];
      const ArrOfDouble& local_coefficients = vect_local_coefficients[ i ];
      const int size = local_stencil.dimension( 0 );
      assert( local_coefficients.size_array( ) == size );
      for ( int k=0; k<size; ++k )
        {
          const int line        = local_stencil( k, 0 );
          const int column      = local_stencil( k, 1 );
          const double coefficient = local_coefficients[ k ];
          const int index       = offsets[ line ];
          assert( stencil( index, 0 ) < 0 );
          assert( stencil( index, 1 ) < 0 );
          assert( index < offsets[ line + 1 ] );
          stencil( index, 0 )   = line;
          stencil( index, 1 )   = column;
          coefficients[ index ] = coefficient;
          offsets[ line ] += 1;
        }
    }
}
References assert_check_block_matrix_structure(), TRUSTTab< _TYPE_ >::dimension(), get_bloc(), Matrice_Base::get_stencil_and_coefficients(), Matrice_Base::is_stencil_up_to_date_, nb_bloc_colonnes(), nb_bloc_lignes(), Matrice_Base::nb_colonnes(), Matrice_Base::nb_lignes(), nb_lignes(), offsets_, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::size_array(), Matrice_Base::stencil_, Deriv_Matrice_Base::valeur(), and VECT.
imprimer()
Sortie & Matrice_Bloc::imprimer (Sortie & s) const override virtual
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
Definition at line 525 of file Matrice_Bloc.cpp.
{
  for ( int i=0; i<N_; ++i )
    {
      for ( int j=0; j<M_; ++j )
        {
          os << "Bloc (" << i << "," << j << ")" << finl;
          get_bloc( i, j ).valeur( ).imprimer( os );
        }
    }
  return os;
}
References finl, get_bloc(), Matrice_Base::imprimer(), M_, N_, and Deriv_Matrice_Base::valeur().
imprimer_formatte()
Sortie & Matrice_Bloc::imprimer_formatte (Sortie & s) const override virtual
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
Definition at line 538 of file Matrice_Bloc.cpp.
{
  for ( int i=0; i<N_; ++i )
    {
      for ( int j=0; j<M_; ++j )
        {
          os << "Bloc (" << i << "," << j << ")" << finl;
          get_bloc( i, j ).valeur( ).imprimer_formatte( os );
        }
    }
  return os;
}
References finl, get_bloc(), Matrice_Base::imprimer_formatte(), M_, N_, and Deriv_Matrice_Base::valeur().
info()
const Type_info * Matrice_Bloc::info () static
Definition at line 23 of file Matrice_Bloc.cpp.
nb_bloc_colonnes()
int Matrice_Bloc::nb_bloc_colonnes (void) const
retourne M_
Definition at line 620 of file Matrice_Bloc.cpp.
{
  return M_;
}
References M_.
Referenced by build_stencil(), check_block_matrix_structure(), Matrice_Bloc_Sym::check_symmetric_block_matrix_structure(), get_stencil(), get_stencil_and_coefficients(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), operation01(), operation11(), PrecondA::preconditionner_(), Solv_GCP_NS::resoudre_systeme(), and scale().
nb_bloc_lignes()
int Matrice_Bloc::nb_bloc_lignes (void) const
retourne N_
Definition at line 615 of file Matrice_Bloc.cpp.
{
  return N_;
}
References N_.
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), build_stencil(), check_block_matrix_structure(), Matrice_Bloc_Sym::check_symmetric_block_matrix_structure(), get_stencil(), get_stencil_and_coefficients(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), operation01(), operation11(), PrecondA::preconditionner_(), Solv_Cholesky::resoudre_systeme(), Solv_Gmres::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), scale(), and SSOR::ssor().
nb_colonnes()
int Matrice_Bloc::nb_colonnes (void) const override virtual
Implements Matrice_Base.
Definition at line 96 of file Matrice_Bloc.cpp.
{
  int sum=0;
  for( int i=0; i<M_; ++i )
    {
      sum += get_bloc(0,i).valeur( ).nb_colonnes();
    }
  return sum;
}
References get_bloc(), M_, Matrice_Base::nb_colonnes(), and Deriv_Matrice_Base::valeur().
Referenced by check_block_matrix_structure(), and Matrice_Bloc_Sym::check_symmetric_block_matrix_structure().
nb_lignes()
int Matrice_Bloc::nb_lignes (void) const override virtual
Implements Matrice_Base.
Definition at line 85 of file Matrice_Bloc.cpp.
{
  int sum=0;
  for( int i=0; i<N_; ++i )
    {
// Codage pour fonctionner avec le stockage de Mat_Bloc_Sym (j>=i)
      sum += get_bloc(i,M_-1).valeur( ).nb_lignes();
    }
  return sum;
}
References get_bloc(), M_, N_, Matrice_Base::nb_lignes(), and Deriv_Matrice_Base::valeur().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), build_stencil(), check_block_matrix_structure(), Matrice_Bloc_Sym::check_symmetric_block_matrix_structure(), get_stencil(), Matrice_Bloc_Sym::get_stencil(), get_stencil_and_coefficients(), Matrice_Bloc_Sym::get_stencil_and_coefficients(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), SETS::iterer_NS(), and Op_Diff_PolyMAC_base::update_aux().
operator*=()
Matrice_Bloc & Matrice_Bloc::operator*= (double x)
Definition at line 859 of file Matrice_Bloc.cpp.
{
  scale( x );
  return *this;
}
References scale().
ordre()
int Matrice_Bloc::ordre (void) const override virtual
Implements Matrice_Base.
Definition at line 76 of file Matrice_Bloc.cpp.
{
  if ( M_ == N_)
    {
      return N_;
    }
  return 0;
}
References M_, and N_.
Referenced by zero().
printOn()
Sortie & Matrice_Bloc::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
Definition at line 38 of file Matrice_Bloc.cpp.
{
  os << nb_blocs_ << finl;
  os << N_ << finl;
  os << M_ << finl;
  for ( int i=0; i<nb_blocs_; ++i )
    {
      os << blocs_[i] << finl;
    }
  return os;
}
References blocs_, finl, M_, N_, and nb_blocs_.
Referenced by Matrice_Bloc_Sym::printOn().
readOn()
Entree & Matrice_Bloc::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
Definition at line 63 of file Matrice_Bloc.cpp.
{
  is >> nb_blocs_;
  is >> N_;
  is >> M_;
  blocs_.dimensionner( nb_blocs_ );
  for ( int i=0; i<nb_blocs_; ++i )
    {
      is >> blocs_[i];
    }
  return is;
}
References blocs_, vect_impl::dimensionner(), M_, N_, and nb_blocs_.
Referenced by Matrice_Bloc_Sym::readOn().
remplir() [1/3]
void Matrice_Bloc::remplir (const IntLists & voisins, const DoubleLists & valeurs, const DoubleVect & terme_diag, const int i, const int n)
< Bloc RR
< Bloc RV
< Bloc VR
< Bloc VV
Definition at line 638 of file Matrice_Bloc.cpp.
{
  dimensionner(2, 2) ;
  get_bloc(0,0).typer("Matrice_Morse_Sym");        //!< Bloc RR
  get_bloc(0,1).typer("Matrice_Morse");        //!< Bloc RV
  get_bloc(1,0).typer("Matrice_Morse");        //!< Bloc VR
  get_bloc(1,1).typer("Matrice_Morse");        //!< Bloc VV
  remplir(voisins, valeurs, terme_diag, i, n, i, n);
}
References dimensionner(), get_bloc(), remplir(), and Deriv_::typer().
Referenced by assemblerP0P1(), assemblerP0Pa(), assemblerP1P1(), assemblerP1Pa(), assemblerPaPa(), and remplir().
remplir() [2/3]
void Matrice_Bloc::remplir (const IntLists & voisins, const DoubleLists & valeurs, const DoubleVect & terme_diag, const int i, const int n, const int j, const int m)
< Sous Bloc RR
< Sous Bloc VR
< Sous Bloc RV
< Sous Bloc VV
< Dimension RR
< Dimension RV
< Dimension VR
< Dimension VV
< Sous Bloc RR
< Sous Bloc VR
< Sous Bloc RV
< Sous Bloc VV
Definition at line 667 of file Matrice_Bloc.cpp.
{
  Matrice_Morse& RR=ref_cast(Matrice_Morse,get_bloc(0,0).valeur());
  Matrice_Morse& RV=ref_cast(Matrice_Morse,get_bloc(0,1).valeur());
  Matrice_Morse& VR=ref_cast(Matrice_Morse,get_bloc(1,0).valeur());
  Matrice_Morse& VV=ref_cast(Matrice_Morse,get_bloc(1,1).valeur());
// Premiere passe pour le dimensionnement
  int RR_compteur, RR_rang=0;
  int RV_compteur, RV_rang=0;
  int VR_compteur, VR_rang=0;
  int VV_compteur, VV_rang=0;
  int num_elem;
  for (num_elem=0; num_elem<n; num_elem++)
    {
      IntList_Curseur liste_vois(voisins[num_elem]);
      DoubleList_Curseur liste_val(valeurs[num_elem]);
      RR_compteur=0;
      RV_compteur=0;
      VR_compteur=0;
      VV_compteur=0;
// Diagonale
      if (terme_diag.size_array()!=0)
        {
          if (num_elem<i)
            RR_compteur++;
          else
            VV_compteur++;
        }
      while (liste_vois)
        {
          int colonne = liste_vois.valeur();
          if (colonne<j)
            {
              if (num_elem<i)
                RR_compteur++;         //!< Sous Bloc RR
              else
                VR_compteur++;        //!< Sous Bloc VR
            }
          else
            {
              if (num_elem<i)
                RV_compteur++;        //!< Sous Bloc RV
              else
                VV_compteur++;         //!< Sous Bloc VV
            }
          ++liste_vois;
          ++liste_val;
        }
      RR_rang += RR_compteur;
      RV_rang += RV_compteur;
      VR_rang += VR_compteur;
      VV_rang += VV_compteur;
    }
  RR.dimensionner(i,        j,        RR_rang);        //!< Dimension RR
  RV.dimensionner(i,        m-j,        RV_rang);        //!< Dimension RV
  VR.dimensionner(n-i,        j,        VR_rang);        //!< Dimension VR
  VV.dimensionner(n-i,        m-j,        VV_rang);        //!< Dimension VV
// Initialisations necessaires
  RR.get_set_tab1()=1;
  RV.get_set_tab1()=1;
  VR.get_set_tab1()=1;
  VV.get_set_tab1()=1;
// Deuxieme passe pour le remplissage
// Tableaux tab1, tab2 et coeff_ pour le bloc RR
  int* RR_tab1 = RR.get_set_tab1().addr();
  int* RR_tab2 = RR.get_set_tab2().addr();
  double* RR_coeff = RR.get_set_coeff().addr();
  int* RR_tab2_ptr = RR_tab2;
// Tableaux tab1, tab2 et coeff_ pour le bloc RV
  int* RV_tab1 = RV.get_set_tab1().addr();
  int* RV_tab2 = RV.get_set_tab2().addr();
  double* RV_coeff = RV.get_set_coeff().addr();
  int* RV_tab2_ptr = RV_tab2;
// Tableaux tab1, tab2 et coeff_ pour le bloc VR
  int* VR_tab1 = VR.get_set_tab1().addr();
  int* VR_tab2 = VR.get_set_tab2().addr();
  double* VR_coeff = VR.get_set_coeff().addr();
  int* VR_tab2_ptr = VR_tab2;
// Tableaux tab1, tab2 et coeff_ pour le bloc VV
  int* VV_tab1 = VV.get_set_tab1().addr();
  int* VV_tab2 = VV.get_set_tab2().addr();
  double* VV_coeff = VV.get_set_coeff().addr();
  int* VV_tab2_ptr = VV_tab2;
  RR_rang=0;
  RV_rang=0;
  VR_rang=0;
  VV_rang=0;
  for (num_elem=0; num_elem<n; num_elem++)
    {
      IntList_Curseur liste_vois(voisins[num_elem]);
      DoubleList_Curseur liste_val(valeurs[num_elem]);
      RR_compteur=0;
      RV_compteur=0;
      VR_compteur=0;
      VV_compteur=0;
      if (num_elem<i)
        {
          *RR_tab1++ = RR_rang;
          *RV_tab1++ = RV_rang;
        }
      else
        {
          *VR_tab1++ = VR_rang;
          *VV_tab1++ = VV_rang;
        }
// Diagonale eventuelle
      if (terme_diag.size_array()!=0)
        {
          if (num_elem<i)
            {
              *RR_tab2_ptr++ = num_elem;
              *RR_coeff++ = terme_diag[num_elem];
              RR_compteur++;
            }
          else
            {
              *VV_tab2_ptr++ = num_elem-i;
              *VV_coeff++ = terme_diag[num_elem];
              VV_compteur++;
            }
        }
      while (liste_vois)
        {
          int colonne = liste_vois.valeur();
          double coeff = liste_val.valeur();
          if (colonne<j)
            {
              if (num_elem<i) //!< Sous Bloc RR
                {
                  *RR_tab2_ptr++ = colonne;
                  *RR_coeff++ = coeff;
                  RR_compteur++;
                }
              else  //!< Sous Bloc VR
                {
                  *VR_tab2_ptr++ = colonne;
                  *VR_coeff++ = coeff;
                  VR_compteur++;
                }
            }
          else
            {
              if (num_elem<i) //!< Sous Bloc RV
                {
                  *RV_tab2_ptr++ = colonne-j;
                  *RV_coeff++ = coeff;
                  RV_compteur++;
                }
              else //!< Sous Bloc VV
                {
                  *VV_tab2_ptr++ = colonne-j;
                  *VV_coeff++ = coeff;
                  VV_compteur++;
                }
            }
          ++liste_vois;
          ++liste_val;
        }
      RR_rang += RR_compteur;
      RV_rang += RV_compteur;
      VR_rang += VR_compteur;
      VV_rang += VV_compteur;
    }
  RR.get_set_tab1()(i)=RR_rang;
  RV.get_set_tab1()(i)=RV_rang;
  VR.get_set_tab1()(n-i)=VR_rang;
  VV.get_set_tab1()(n-i)=VV_rang;
// Passage a la numerotation Fortran
  RR.formeF();
  RV.formeF();
  VR.formeF();
  VV.formeF();
// Compactage de la matrice
  RR.compacte();
  RV.compacte();
  VR.compacte();
  VV.compacte();
}
References TRUSTArray< _TYPE_ >::addr(), coeff, Matrice_Morse::compacte(), Matrice_Morse::dimensionner(), Matrice_Morse::formeF(), get_bloc(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), ref_cast, TRUSTArray< _TYPE_ >::size_array(), TRUSTList_Curseur< _TYPE_ >::valeur(), and valeur().
remplir() [3/3]
void Matrice_Bloc::remplir (const IntLists & voisins, const DoubleLists & valeurs, const int i, const int n, const int j, const int m)
< Bloc RR
< Bloc RV
< Bloc VR
< Bloc VV
Definition at line 652 of file Matrice_Bloc.cpp.
{
  dimensionner(2, 2) ;
  get_bloc(0,0).typer("Matrice_Morse");        //!< Bloc RR
  get_bloc(0,1).typer("Matrice_Morse");        //!< Bloc RV
  get_bloc(1,0).typer("Matrice_Morse");        //!< Bloc VR
  get_bloc(1,1).typer("Matrice_Morse");        //!< Bloc VV
  DoubleVect diagonale_vide;
  remplir(voisins, valeurs, diagonale_vide, i, n, j, m);
}
References dimensionner(), get_bloc(), remplir(), and Deriv_::typer().
scale()
void Matrice_Bloc::scale (const double x) override virtual
Implements Matrice_Base.
Definition at line 182 of file Matrice_Bloc.cpp.
{
  const int nb_line_blocks   = nb_bloc_lignes( );
  const int nb_column_blocks = nb_bloc_colonnes( );
  for (int i=0; i<nb_line_blocks; i++)
    {
      for (int j=0; j<nb_column_blocks; j++)
        {
          Matrice_Base& matrix = get_bloc( i, j ).valeur( );
          matrix.scale( x );
        }
    }
}
References get_bloc(), nb_bloc_colonnes(), nb_bloc_lignes(), Matrice_Base::scale(), and Deriv_Matrice_Base::valeur().
Referenced by operator*=().
self_cast() [1/2]
const Matrice_Bloc & Matrice_Bloc::self_cast (const Objet_U & r) static
Definition at line 23 of file Matrice_Bloc.cpp.
self_cast() [2/2]
Matrice_Bloc & Matrice_Bloc::self_cast (Objet_U & r) static
Definition at line 23 of file Matrice_Bloc.cpp.
taille_memoire()
unsigned Matrice_Bloc::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Matrice_Bloc_Sym.
Definition at line 23 of file Matrice_Bloc.cpp.
Member Data Documentation
blocs_
Vect_Matrice Matrice_Bloc::blocs_ protected
les blocs de la matrices source A
Definition at line 109 of file Matrice_Bloc.h.
Referenced by dimensionner(), Matrice_Bloc_Sym::dimensionner(), get_bloc(), Matrice_Bloc_Sym::get_bloc(), printOn(), and readOn().
info_obj
const Type_info Matrice_Bloc::info_obj static
Definition at line 50 of file Matrice_Bloc.h.
M_
int Matrice_Bloc::M_ protected
2eme dim de A
Definition at line 111 of file Matrice_Bloc.h.
Referenced by ajouter_multvect_(), ajouter_multvectT_(), dim(), dimensionner(), Matrice_Bloc_Sym::dimensionner(), get_bloc(), Matrice_Bloc_Sym::get_bloc(), imprimer(), Matrice_Bloc_Sym::imprimer(), imprimer_formatte(), Matrice_Bloc_Sym::imprimer_formatte(), nb_bloc_colonnes(), nb_colonnes(), nb_lignes(), ordre(), printOn(), and readOn().
N_
int Matrice_Bloc::N_ protected
1ere dim de A
Definition at line 110 of file Matrice_Bloc.h.
Referenced by ajouter_multvect_(), Matrice_Bloc_Sym::ajouter_multvect_(), ajouter_multvectT_(), dim(), dimensionner(), Matrice_Bloc_Sym::dimensionner(), get_bloc(), Matrice_Bloc_Sym::get_bloc(), imprimer(), Matrice_Bloc_Sym::imprimer(), imprimer_formatte(), Matrice_Bloc_Sym::imprimer_formatte(), nb_bloc_lignes(), nb_lignes(), ordre(), printOn(), and readOn().
nb_blocs_
int Matrice_Bloc::nb_blocs_ protected
nb total des blocs de A (= N_ * M_)
Definition at line 112 of file Matrice_Bloc.h.
Referenced by dimensionner(), Matrice_Bloc_Sym::dimensionner(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), printOn(), and readOn().
offsets_
ArrOfInt Matrice_Bloc::offsets_ protected
Definition at line 114 of file Matrice_Bloc.h.
Referenced by build_stencil(), and get_stencil_and_coefficients().
The documentation for this class was generated from the following files:
src/Kernel/Math/Matrices/Matrice_Bloc.h
src/Kernel/Math/Matrices/Matrice_Bloc.cpp