TRUST: Ch_front_input_uniforme Class Reference
Ch_front_input_uniforme Class Reference
class Ch_front_input_uniforme
Cette classe represente un champ accessible par setInputField
uniforme sur une frontiere.
#include <Ch_front_input_uniforme.h>
Public Member Functions
Ch_front_input_uniforme ()
~Ch_front_input_uniforme ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
virtual Champ_front_base & affecter_ (const Champ_front_base &)
virtual void getTemplate (TrioField &afield) const
virtual void setValue (const TrioField &afield)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ch_front_input_uniforme & self_cast (Objet_U &)
static const
Ch_front_input_uniforme & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le temps du champ instationnaire sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit le temps du champ instationnaire sur un flot d'entree.
virtual void set_nb_comp (int i)
calls fixer_nb_comp
virtual void set_name (const Nom &name)
calls nommer
virtual const Nom & get_name () const
calls le_nom
Detailed Description
class Ch_front_input_uniforme
Cette classe represente un champ accessible par setInputField
uniforme sur une frontiere.
Definition at line 43 of file Ch_front_input_uniforme.h.
Constructor & Destructor Documentation
Ch_front_input_uniforme::Ch_front_input_uniforme ()
Definition at line 28 of file Ch_front_input_uniforme.cpp.
Ch_front_input_uniforme::~Ch_front_input_uniforme ()
Definition at line 28 of file Ch_front_input_uniforme.cpp.
Member Function Documentation
virtual Champ_front_base& Ch_front_input_uniforme::affecter_ (const Champ_front_base &) [inline, virtual]
Implements Champ_front_base.
Definition at line 50 of file Ch_front_input_uniforme.h.
  {
    return *this;
  }
Objet_U * Ch_front_input_uniforme::cree_instance () [static]
Definition at line 28 of file Ch_front_input_uniforme.cpp.
int Ch_front_input_uniforme::duplique () const [virtual]
Implements Champ_front_instationnaire_base.
Definition at line 28 of file Ch_front_input_uniforme.cpp.
const Type_info * Ch_front_input_uniforme::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_instationnaire_base.
Definition at line 28 of file Ch_front_input_uniforme.cpp.
const Nom & Ch_front_input_uniforme::get_name () const [protected, virtual]
calls le_nom
Definition at line 54 of file Ch_front_input_uniforme.cpp.
References Field_base::le_nom().
{
  return le_nom();
}
void Ch_front_input_uniforme::getTemplate (TrioField & afield) const [virtual]
Implements Champ_Input_Proto.
Definition at line 81 of file Ch_front_input_uniforme.cpp.
References Field_base::le_nom(), Champ_Input_Proto::mon_pb, and Field_base::nb_comp().
{
  afield.dummy_geom();
  afield.setName(le_nom().getChar());
  afield._time1=mon_pb->presentTime();
  afield._time2=mon_pb->futureTime();
  afield._nb_field_components=nb_comp();
}
const Type_info * Ch_front_input_uniforme::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_instationnaire_base.
Definition at line 28 of file Ch_front_input_uniforme.cpp.
int Ch_front_input_uniforme::initialiser (double temps, const Champ_Inc_base & inco) [virtual]
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Returns:
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Champ_front_instationnaire_base.
Definition at line 61 of file Ch_front_input_uniforme.cpp.
References DoubleTab::dimension(), Champ_Input_Proto::initial_value_, Champ_front_instationnaire_base::initialiser(), Champ_front_base::les_valeurs, and ArrOfDouble::size_array().
{
  if (!Champ_front_instationnaire_base::initialiser(temps,inco))
    return 0;
  for(int i=0; i<les_valeurs->nb_cases(); i++)
    {
      DoubleTab& val=les_valeurs[i].valeurs();
      int nbcomp=val.dimension(1);
      if (initial_value_.size_array()==0)
        val=0;
      else
        for (int c=0; c<nbcomp; c++)
          val(0,c)=initial_value_(c);
    }
  return 1;
}
Sortie & Ch_front_input_uniforme::printOn (Sortie & os) const [protected, virtual]
Ecrit le temps du champ instationnaire sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_instationnaire_base.
Definition at line 39 of file Ch_front_input_uniforme.cpp.
{
  return os;
}
Entree & Ch_front_input_uniforme::readOn (Entree & is) [protected, virtual]
Lit le temps du champ instationnaire sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_instationnaire_base.
Definition at line 31 of file Ch_front_input_uniforme.cpp.
References Champ_Input_Proto::mon_pb, Champ_Input_Proto::read(), and Champ_Input_Proto::sous_zone_ok.
{
  sous_zone_ok=false;
  read(is);
  mon_pb->addInputField(*this);
  return is;
}
const Ch_front_input_uniforme & Ch_front_input_uniforme::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_front_instationnaire_base.
Definition at line 28 of file Ch_front_input_uniforme.cpp.
Ch_front_input_uniforme & Ch_front_input_uniforme::self_cast (Objet_U & r) [static]
Reimplemented from Champ_front_instationnaire_base.
Definition at line 28 of file Ch_front_input_uniforme.cpp.
void Ch_front_input_uniforme::set_name (const Nom & name) [protected, virtual]
calls nommer
Implements Champ_Input_Proto.
Definition at line 49 of file Ch_front_input_uniforme.cpp.
References Field_base::nommer().
{
  nommer(name);
}
void Ch_front_input_uniforme::set_nb_comp (int i) [protected, virtual]
calls fixer_nb_comp
Implements Champ_Input_Proto.
Definition at line 44 of file Ch_front_input_uniforme.cpp.
References Field_base::fixer_nb_comp().
{
  fixer_nb_comp(i);
}
void Ch_front_input_uniforme::setValue (const TrioField & afield) [virtual]
Implements Champ_Input_Proto.
Definition at line 95 of file Ch_front_input_uniforme.cpp.
References Champ_front_instationnaire_base::Gpoint(), Champ_front_base::les_valeurs, Champ_Input_Proto::setValueOnTab(), and Champ_front_base::valeurs().
{
  for (int i=1; i<les_valeurs->nb_cases(); i++)
    Champ_Input_Proto::setValueOnTab(afield,les_valeurs[i].valeurs());
  Gpoint(afield._time1,afield._time2);
}
unsigned Ch_front_input_uniforme::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 28 of file Ch_front_input_uniforme.cpp.
Member Data Documentation
const Type_info Ch_front_input_uniforme::info_obj [static]
Reimplemented from Champ_front_instationnaire_base.
Definition at line 45 of file Ch_front_input_uniforme.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Ch_front_input_uniforme.h
src/Kernel/Champs/Ch_front_input_uniforme.cpp