TRUST: Op_Div_VDF_base Class Reference
Op_Div_VDF_base Class Reference
class Op_Div_VDF_base
Classe de base des operateurs de divergence VDF
#include <Op_Div_VDF_base.h>
Public Member Functions
Op_Div_VDF_base ()
~Op_Div_VDF_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Op_Div_VDF_base (const Iterateur_VDF_base &)
constructeur
DoubleTab & ajouter (const DoubleTab &inco, DoubleTab &resu) const
ajoute la contribution de la divergence a resu
renvoie resu
DoubleTab & calculer (const DoubleTab &inco, DoubleTab &resu) const
calcule la contribution de la divergence, la range dans resu
renvoie resu
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Div_VDF_base & self_cast (Objet_U &)
static const Op_Div_VDF_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
Protected Attributes
Iterateur_VDF iter
Detailed Description
class Op_Div_VDF_base
Classe de base des operateurs de divergence VDF
Definition at line 47 of file Op_Div_VDF_base.h.
Constructor & Destructor Documentation
Op_Div_VDF_base::Op_Div_VDF_base ()
Definition at line 25 of file Op_Div_VDF_base.cpp.
Op_Div_VDF_base::~Op_Div_VDF_base ()
Definition at line 25 of file Op_Div_VDF_base.cpp.
Op_Div_VDF_base::Op_Div_VDF_base (const Iterateur_VDF_base & iter_base) [inline]
constructeur
Definition at line 72 of file Op_Div_VDF_base.h.
                                                                           :
  iter(iter_base)
{}
Member Function Documentation
DoubleTab & Op_Div_VDF_base::ajouter (const DoubleTab & inco, DoubleTab & resu) const [inline, virtual]
ajoute la contribution de la divergence a resu
renvoie resu
Reimplemented from Operateur_base.
Definition at line 79 of file Op_Div_VDF_base.h.
References Iterateur_VDF::ajouter(), and iter.
{
  return iter.ajouter(inco, resu);
}
DoubleTab & Op_Div_VDF_base::calculer (const DoubleTab & inco, DoubleTab & resu) const [inline, virtual]
calcule la contribution de la divergence, la range dans resu
renvoie resu
Reimplemented from Operateur_base.
Definition at line 87 of file Op_Div_VDF_base.h.
References Iterateur_VDF::calculer(), and iter.
{
  return iter.calculer(inco, resu);
}
void Op_Div_VDF_base::completer (void) [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Definition at line 45 of file Op_Div_VDF_base.cpp.
References Iterateur_VDF::completer_(), and iter.
{
  Operateur_base::completer();
  iter.completer_();
}
virtual int Op_Div_VDF_base::duplique () const [pure virtual]
Implements Operateur_Div_base.
Implemented in Op_Div_VDF_Elem.
const Type_info * Op_Div_VDF_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Div_base.
Reimplemented in Op_Div_VDF_Elem.
Definition at line 25 of file Op_Div_VDF_base.cpp.
int Op_Div_VDF_base::impr (Sortie & os) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 52 of file Op_Div_VDF_base.cpp.
References Iterateur_VDF::impr(), and iter.
{
  return iter.impr(os);
}
const Type_info * Op_Div_VDF_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Div_base.
Reimplemented in Op_Div_VDF_Elem.
Definition at line 25 of file Op_Div_VDF_base.cpp.
Sortie & Op_Div_VDF_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Div_base.
Reimplemented in Op_Div_VDF_Elem.
Definition at line 31 of file Op_Div_VDF_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Div_VDF_base::readOn (Entree & is) [protected, virtual]
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Div_base.
Reimplemented in Op_Div_VDF_Elem.
Definition at line 40 of file Op_Div_VDF_base.cpp.
{
  return s ;
}
const Op_Div_VDF_base & Op_Div_VDF_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Operateur_Div_base.
Reimplemented in Op_Div_VDF_Elem.
Definition at line 25 of file Op_Div_VDF_base.cpp.
Op_Div_VDF_base & Op_Div_VDF_base::self_cast (Objet_U & r) [static]
Reimplemented from Operateur_Div_base.
Reimplemented in Op_Div_VDF_Elem.
Definition at line 25 of file Op_Div_VDF_base.cpp.
Member Data Documentation
const Type_info Op_Div_VDF_base::info_obj [static]
Reimplemented from Operateur_Div_base.
Reimplemented in Op_Div_VDF_Elem.
Definition at line 50 of file Op_Div_VDF_base.h.
Iterateur_VDF Op_Div_VDF_base::iter [protected]
Definition at line 62 of file Op_Div_VDF_base.h.
Referenced by ajouter(), Op_Div_VDF_Elem::associer(), calculer(), completer(), and impr().
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Op_Div_VDF_base.h
src/VDF/Operateurs/Op_Div_VDF_base.cpp