TRUST: DoubleList_Curseur Class Reference
DoubleList_Curseur Class Reference
List_Curseur de reels double precision.
#include <DoubleList.h>
Public Member Functions
DoubleList_Curseur (const DoubleList &a_list)
Constructeur
Construit une liste_curseur a partir d'une liste.
DoubleList_Curseur (const DoubleListElem &a_list)
Constructeur
Construit une liste_curseur a partir d'une liste.
operator bool () const
Teste si le curseur est non nul.
void operator++ ()
Avance le curseur dans la liste
Si le curseur est sur le dernier element, il devient nul.
double valeur () const
retourne la valeur du curseur
double & valeur ()
retourne la valeur du curseur
void operator= (const DoubleList &a_list)
Affectation d'une liste a une liste_curseur.
const DoubleListElem & list () const
Retourne la liste associee a la liste_curseur.
DoubleListElem & list ()
Retourne la liste associee a la liste_curseur.
Private Attributes
DoubleListElem * curseur
Detailed Description
List_Curseur de reels double precision.
Definition at line 84 of file DoubleList.h.
Constructor & Destructor Documentation
DoubleList_Curseur::DoubleList_Curseur (const DoubleList & a_list) [inline]
Constructeur
Construit une liste_curseur a partir d'une liste.
Definition at line 137 of file DoubleList.h.
References curseur, and DoubleListElem::est_vide().
  : curseur(&(DoubleListElem&)a_list)
{
  if (a_list.est_vide())
    curseur=0;
}
DoubleList_Curseur::DoubleList_Curseur (const DoubleListElem & a_list) [inline]
Constructeur
Construit une liste_curseur a partir d'une liste.
Definition at line 159 of file DoubleList.h.
References curseur, and DoubleListElem::est_vide().
  : curseur(&(DoubleListElem&)a_list)
{
  if (a_list.est_vide())
    curseur=0;
}
Member Function Documentation
const DoubleListElem & DoubleList_Curseur::list () const [inline]
Retourne la liste associee a la liste_curseur.
Returns:
const DoubleList&
Signification: la liste associee
Contraintes:
Definition at line 288 of file DoubleList.h.
References curseur.
Referenced by DoubleList::printOn(), and DoubleList::suppr().
{
  return *curseur;
}
DoubleListElem & DoubleList_Curseur::list () [inline]
Retourne la liste associee a la liste_curseur.
Returns:
DoubleList&
Signification: la liste associee
Contraintes: DoubleList_H
Definition at line 308 of file DoubleList.h.
References curseur.
DoubleList_Curseur::operator bool () const [inline]
Teste si le curseur est non nul.
Returns:
int
Signification: 1 si le curseur est non nul, 0 si il est nul
Contraintes:
Definition at line 181 of file DoubleList.h.
References curseur.
{
  return (curseur!=0);
}
void DoubleList_Curseur::operator++ () [inline]
Avance le curseur dans la liste
Si le curseur est sur le dernier element, il devient nul.
Definition at line 202 of file DoubleList.h.
References curseur, DoubleListElem::est_dernier(), and DoubleListElem::suivant().
{
  if(curseur->est_dernier())
    curseur=0;
  else
    curseur=&(curseur->suivant());
}
void DoubleList_Curseur::operator= (const DoubleList & a_list) [inline]
Affectation d'une liste a une liste_curseur.
Definition at line 266 of file DoubleList.h.
References curseur, and DoubleListElem::est_vide().
{
  curseur=(&(DoubleListElem&)a_list);
  if (a_list.est_vide())
    curseur=0;
}
double DoubleList_Curseur::valeur () const [inline]
retourne la valeur du curseur
Returns:
double
Signification: valeur du curseur
Contraintes:
Definition at line 225 of file DoubleList.h.
References curseur, and DoubleListElem::valeur().
Referenced by DoubleList::calcule_min_max(), DoubleList::contient(), DoubleList::operator=(), DoubleList::operator[](), DoubleList::printOn(), DoubleList::rang(), Matrice_Morse::remplir(), Matrice_Bloc::remplir(), and DoubleList::suppr().
{
  return curseur->valeur();
}
double & DoubleList_Curseur::valeur () [inline]
retourne la valeur du curseur
Returns:
double&
Signification: valeur du curseur
Contraintes:
Definition at line 245 of file DoubleList.h.
References curseur, and DoubleListElem::valeur().
{
  return curseur->valeur();
}
Member Data Documentation
DoubleListElem* DoubleList_Curseur::curseur [private]
Definition at line 98 of file DoubleList.h.
Referenced by DoubleList_Curseur(), list(), operator bool(), operator++(), operator=(), and valeur().
The documentation for this class was generated from the following file:
src/Kernel/Math/DoubleList.h