TRUST: Pb_Hydraulique_Concentration Class Reference
Pb_Hydraulique_Concentration Class Reference
Classe Pb_Hydraulique_Concentration
Cette classe represente un probleme d'hydraulique avec transport
d'un ou plusieurs constituants:
- Equations de Navier_Stokes en regime laminaire
pour un fluide incompressible
- Equations de convection-diffusion en regime laminaire
En fait si on transporte plusieurs constituants on utilisera une
seule equation de convection-diffusion avec une inconnue vectorielle.
En general, on couple les 2 equations par l'intermediaire du terme
source des forces de volume de Navier_Stokes dans lequel on prend
en compte de petites variations de la masse volumique en fonction
du ou des constituants.
#include <Pb_Hydraulique_Concentration.h>
Public Member Functions
Pb_Hydraulique_Concentration ()
~Pb_Hydraulique_Concentration ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int nombre_d_equations () const
Renvoie le nombre d'equation,
Renvoie 2 car il y a 2 equations a un probleme
hydraulique avec transport:
- l'equation de Navier Stokes
- une equation de convection-diffusion (eventuellement vectorielle)
const Equation_base & equation (int) const
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0
Renvoie l'equation de convection-diffusion de type
Convection_Diffusion_Concentration si i=1
(l'equation de convection diffusion peut-etre vectorielle)
(version const)
Equation_base & equation (int)
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0
Renvoie l'equation de convection-diffusion de type
Convection_Diffusion_Concentration si i=1
(l'equation de convection diffusion peut-etre vectorielle)
void associer_milieu_base (const Milieu_base &)
Associe un milieu au probleme,
Si le milieu est de type
- Fluide_Incompressible, il sera associe a l'equation de l'hydraulique
- Constituant, il sera associe a l'equation de convection-diffusion
Un autre type de milieu provoque une erreur.
int verifier ()
Teste la compatibilite des equations de convection-diffusion
et de l'hydraulique. Le test se fait sur les conditions
aux limites discretisees de chaque equation.
Appel la fonction de librairie hors classe:
tester_compatibilite_hydr_concentration(const Zone_Cl_dis&,const Zone_Cl_dis&)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Pb_Hydraulique_Concentration & self_cast (Objet_U &)
static const
Pb_Hydraulique_Concentration & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Pb_Fluide_base::printOn(Sortie&)
Ecrit le probleme sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a: Pb_Fluide_base::readOn(Entree&)
Lit le probleme a partir d'un flot d'entree.
Protected Attributes
Navier_Stokes_std eq_hydraulique
Convection_Diffusion_Concentration eq_concentration
Detailed Description
Classe Pb_Hydraulique_Concentration
Cette classe represente un probleme d'hydraulique avec transport
d'un ou plusieurs constituants:
- Equations de Navier_Stokes en regime laminaire
pour un fluide incompressible
- Equations de convection-diffusion en regime laminaire
En fait si on transporte plusieurs constituants on utilisera une
seule equation de convection-diffusion avec une inconnue vectorielle.
En general, on couple les 2 equations par l'intermediaire du terme
source des forces de volume de Navier_Stokes dans lequel on prend
en compte de petites variations de la masse volumique en fonction
du ou des constituants.
Definition at line 51 of file Pb_Hydraulique_Concentration.h.
Constructor & Destructor Documentation
Pb_Hydraulique_Concentration::Pb_Hydraulique_Concentration ()
Definition at line 28 of file Pb_Hydraulique_Concentration.cpp.
Pb_Hydraulique_Concentration::~Pb_Hydraulique_Concentration ()
Definition at line 28 of file Pb_Hydraulique_Concentration.cpp.
Member Function Documentation
void Pb_Hydraulique_Concentration::associer_milieu_base (const Milieu_base & mil) [virtual]
Associe un milieu au probleme,
Si le milieu est de type
- Fluide_Incompressible, il sera associe a l'equation de l'hydraulique
- Constituant, il sera associe a l'equation de convection-diffusion
Un autre type de milieu provoque une erreur.
Reimplemented from Probleme_base.
Reimplemented in Pb_Hydraulique_Concentration_Scalaires_Passifs.
Definition at line 177 of file Pb_Hydraulique_Concentration.cpp.
References Convection_Diffusion_Concentration::associer_milieu_base(), Navier_Stokes_std::associer_milieu_base(), Cerr, eq_concentration, eq_hydraulique, Process::exit(), finl, Objet_U::que_suis_je(), and sub_type.
{
  if ( sub_type(Fluide_Incompressible,mil) )
    eq_hydraulique.associer_milieu_base(mil);
  else if ( sub_type(Constituant,mil) )
    eq_concentration.associer_milieu_base(mil);
  else
    {
      Cerr << "Un milieu de type " << mil.que_suis_je() << " ne peut etre associe a " << finl;
      Cerr << "un probleme de type Pb_Hydraulique_Concentration " << finl;
      exit();
    }
}
Objet_U * Pb_Hydraulique_Concentration::cree_instance () [static]
Reimplemented in Pb_Hydraulique_Concentration_Scalaires_Passifs.
Definition at line 28 of file Pb_Hydraulique_Concentration.cpp.
int Pb_Hydraulique_Concentration::duplique () const [virtual]
Implements Pb_Fluide_base.
Reimplemented in Pb_Hydraulique_Concentration_Scalaires_Passifs.
Definition at line 28 of file Pb_Hydraulique_Concentration.cpp.
const Equation_base & Pb_Hydraulique_Concentration::equation (int i) const [virtual]
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0
Renvoie l'equation de convection-diffusion de type
Convection_Diffusion_Concentration si i=1
(l'equation de convection diffusion peut-etre vectorielle)
(version const)
Returns:
Equation_base&
Signification: l'equation correspondante a l'index
Contraintes: reference constante
Implements Probleme_base.
Reimplemented in Pb_Hydraulique_Concentration_Scalaires_Passifs.
Definition at line 113 of file Pb_Hydraulique_Concentration.cpp.
References Cerr, eq_concentration, eq_hydraulique, Process::exit(), and finl.
{
  if ( !( i==0 || i==1 ) )
    {
      Cerr << "\nError in Pb_Hydraulique_Concentration::equation() : Wrong number of equation !" << finl;
      Process::exit();
    }
  if (i == 0)
    return eq_hydraulique;
  else
    return eq_concentration;
}
Equation_base & Pb_Hydraulique_Concentration::equation (int i) [virtual]
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0
Renvoie l'equation de convection-diffusion de type
Convection_Diffusion_Concentration si i=1
(l'equation de convection diffusion peut-etre vectorielle)
Returns:
Equation_base&
Signification: l'equation correspondante a l'index
Contraintes:
Implements Probleme_base.
Reimplemented in Pb_Hydraulique_Concentration_Scalaires_Passifs.
Definition at line 143 of file Pb_Hydraulique_Concentration.cpp.
References Cerr, eq_concentration, eq_hydraulique, Process::exit(), and finl.
{
  if ( !( i==0 || i==1 ) )
    {
      Cerr << "\nError in Pb_Hydraulique_Concentration::equation() : Wrong number of equation !" << finl;
      Process::exit();
    }
  if (i == 0)
    return eq_hydraulique;
  else
    return eq_concentration;
}
const Type_info * Pb_Hydraulique_Concentration::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Hydraulique_Concentration_Scalaires_Passifs.
Definition at line 28 of file Pb_Hydraulique_Concentration.cpp.
const Type_info * Pb_Hydraulique_Concentration::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Hydraulique_Concentration_Scalaires_Passifs.
Definition at line 28 of file Pb_Hydraulique_Concentration.cpp.
int Pb_Hydraulique_Concentration::nombre_d_equations () const [virtual]
Renvoie le nombre d'equation,
Renvoie 2 car il y a 2 equations a un probleme
hydraulique avec transport:
- l'equation de Navier Stokes
- une equation de convection-diffusion (eventuellement vectorielle)
Returns:
int
Signification: le nombre d'equation
Contraintes: toujours 2 car il y 2 equations au probleme
Implements Probleme_base.
Reimplemented in Pb_Hydraulique_Concentration_Scalaires_Passifs.
Definition at line 90 of file Pb_Hydraulique_Concentration.cpp.
{
  return 2;
}
Sortie & Pb_Hydraulique_Concentration::printOn (Sortie & os) const [protected, virtual]
Simple appel a: Pb_Fluide_base::printOn(Sortie&)
Ecrit le probleme sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Hydraulique_Concentration_Scalaires_Passifs.
Definition at line 46 of file Pb_Hydraulique_Concentration.cpp.
{
  return Pb_Fluide_base::printOn(os);
}
Entree & Pb_Hydraulique_Concentration::readOn (Entree & is) [protected, virtual]
Simple appel a: Pb_Fluide_base::readOn(Entree&)
Lit le probleme a partir d'un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Hydraulique_Concentration_Scalaires_Passifs.
Definition at line 67 of file Pb_Hydraulique_Concentration.cpp.
{
  return Pb_Fluide_base::readOn(is);
}
const Pb_Hydraulique_Concentration & Pb_Hydraulique_Concentration::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Hydraulique_Concentration_Scalaires_Passifs.
Definition at line 28 of file Pb_Hydraulique_Concentration.cpp.
Pb_Hydraulique_Concentration & Pb_Hydraulique_Concentration::self_cast (Objet_U & r) [static]
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Hydraulique_Concentration_Scalaires_Passifs.
Definition at line 28 of file Pb_Hydraulique_Concentration.cpp.
unsigned Pb_Hydraulique_Concentration::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Pb_Hydraulique_Concentration_Scalaires_Passifs.
Definition at line 28 of file Pb_Hydraulique_Concentration.cpp.
int Pb_Hydraulique_Concentration::verifier () [virtual]
Teste la compatibilite des equations de convection-diffusion
et de l'hydraulique. Le test se fait sur les conditions
aux limites discretisees de chaque equation.
Appel la fonction de librairie hors classe:
tester_compatibilite_hydr_concentration(const Zone_Cl_dis&,const Zone_Cl_dis&)
Returns:
int
Signification: code de retour propage
Contraintes:
Reimplemented from Probleme_base.
Definition at line 210 of file Pb_Hydraulique_Concentration.cpp.
References eq_concentration, eq_hydraulique, tester_compatibilite_hydr_concentration(), and Equation_base::zone_Cl_dis().
{
  const Zone_Cl_dis& zone_Cl_hydr = eq_hydraulique.zone_Cl_dis();
  const Zone_Cl_dis& zone_Cl_co = eq_concentration.zone_Cl_dis();
  return tester_compatibilite_hydr_concentration(zone_Cl_hydr,zone_Cl_co);
}
Member Data Documentation
Convection_Diffusion_Concentration Pb_Hydraulique_Concentration::eq_concentration [protected]
Definition at line 67 of file Pb_Hydraulique_Concentration.h.
Referenced by associer_milieu_base(), equation(), and verifier().
Navier_Stokes_std Pb_Hydraulique_Concentration::eq_hydraulique [protected]
Definition at line 66 of file Pb_Hydraulique_Concentration.h.
Referenced by associer_milieu_base(), equation(), and verifier().
const Type_info Pb_Hydraulique_Concentration::info_obj [static]
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Hydraulique_Concentration_Scalaires_Passifs.
Definition at line 54 of file Pb_Hydraulique_Concentration.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Problems/Pb_Hydraulique_Concentration.h
src/ThHyd/Incompressible/Problems/Pb_Hydraulique_Concentration.cpp