TRUST: IntTrav Class Reference
IntTrav Class Reference
Tableau de travail a n entrees pour n<= 4
C'est un IntTab avec allocation dans un pool de memoire gere par
la_memoire. L'allocation initiale est realisee avec alloc_temp_storage.
#include <IntTrav.h>
Public Member Functions
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
IntTrav ()
IntTrav (int n)
IntTrav (int n1, int n2)
IntTrav (int n1, int n2, int n3)
IntTrav (int n1, int n2, int n3, int n4)
IntTrav (const IntTab &)
ATTENTION: non standard, voir la description !!!
IntTrav (const IntVect &)
ATTENTION: non standard, voir la description !!!
IntTrav (const IntTrav &)
ATTENTION: non standard, voir la description !!! Operateurs copie.
IntTrav & operator= (const IntTrav &)
Operateur copie (on ne veut pas l'operateur par defaut)
IntTrav & operator= (const IntTab &)
Operateur copie d'un tableau (copie structure ET contenu)
IntTrav & operator= (const IntVect &)
Operateur copie d'un tableau (copie structure ET contenu)
IntTrav & operator= (int d)
Comme on surcharge l'operateur copie, il faut redefinir celui-la aussi.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static IntTrav & self_cast (Objet_U &)
static const IntTrav & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Appel a IntTab::printOn.
virtual Entree & readOn (Entree &)
Appel a IntTab::readOn.
Detailed Description
Tableau de travail a n entrees pour n<= 4
C'est un IntTab avec allocation dans un pool de memoire gere par
la_memoire. L'allocation initiale est realisee avec alloc_temp_storage.
Definition at line 40 of file IntTrav.h.
Constructor & Destructor Documentation
IntTrav::IntTrav ()
Definition at line 51 of file IntTrav.cpp.
References ArrOfInt::set_mem_storage(), and ArrOfInt::TEMP_STORAGE.
{
  set_mem_storage(TEMP_STORAGE);
}
IntTrav::IntTrav (int n)
Definition at line 57 of file IntTrav.cpp.
References IntTab::resize(), ArrOfInt::set_mem_storage(), and ArrOfInt::TEMP_STORAGE.
{
  set_mem_storage(TEMP_STORAGE);
  resize(n);
}
IntTrav::IntTrav (int n1, int n2)
Definition at line 64 of file IntTrav.cpp.
References IntTab::resize(), ArrOfInt::set_mem_storage(), and ArrOfInt::TEMP_STORAGE.
{
  set_mem_storage(TEMP_STORAGE);
  resize(n1, n2);
}
IntTrav::IntTrav (int n1, int n2, int n3)
Definition at line 74 of file IntTrav.cpp.
References IntTab::resize(), ArrOfInt::set_mem_storage(), and ArrOfInt::TEMP_STORAGE.
{
  set_mem_storage(TEMP_STORAGE);
  resize(n1, n2, n3);
}
IntTrav::IntTrav (int n1, int n2, int n3, int n4)
Definition at line 81 of file IntTrav.cpp.
References IntTab::resize(), ArrOfInt::set_mem_storage(), and ArrOfInt::TEMP_STORAGE.
{
  set_mem_storage(TEMP_STORAGE);
  resize(n1, n2, n3, n4);
}
IntTrav::IntTrav (const IntTab & tab)
ATTENTION: non standard, voir la description !!!
ATTENTION: construit un tableau de meme taill et de meme structure<br>(espaces virtuels), mais initialise avec ZERO !!!
Definition at line 90 of file IntTrav.cpp.
References IntTab::copy(), Array_base::NOCOPY_NOINIT, operator=(), ArrOfInt::set_mem_storage(), ArrOfInt::TEMP_STORAGE, and zero_int.
{
  set_mem_storage(TEMP_STORAGE);
  IntTab::copy(tab, Array_base::NOCOPY_NOINIT);
  IntTab::operator=(zero_int);
}
IntTrav::IntTrav (const IntVect & tab)
ATTENTION: non standard, voir la description !!!
Constructeur par copie
ATTENTION: construit un tableau de meme taill et de meme structure<br>(espaces virtuels), mais initialise avec ZERO !!!
Definition at line 112 of file IntTrav.cpp.
References IntVect::get_md_vector(), IntVect::line_size(), Array_base::NOCOPY_NOINIT, operator=(), IntTab::resize(), IntVect::set_line_size_(), IntTab::set_md_vector(), ArrOfInt::set_mem_storage(), ArrOfInt::size_array(), ArrOfInt::TEMP_STORAGE, and zero_int.
{
  set_mem_storage(TEMP_STORAGE);
  set_line_size_(tab.line_size());
  IntTab::resize(tab.size_array(), Array_base::NOCOPY_NOINIT);
  set_md_vector(tab.get_md_vector());
  IntTab::operator=(zero_int);
}
IntTrav::IntTrav (const IntTrav & tab)
ATTENTION: non standard, voir la description !!! Operateurs copie.
Constructeur par copie
ATTENTION: construit un tableau de meme taill et de meme structure<br>(espaces virtuels), mais initialise avec ZERO !!!
Definition at line 101 of file IntTrav.cpp.
References IntTab::copy(), Array_base::NOCOPY_NOINIT, operator=(), ArrOfInt::set_mem_storage(), ArrOfInt::TEMP_STORAGE, and zero_int.
                                  :IntTab()
{
  set_mem_storage(TEMP_STORAGE);
  IntTab::copy(tab, Array_base::NOCOPY_NOINIT);
  IntTab::operator=(zero_int);
}
Member Function Documentation
Objet_U * IntTrav::cree_instance () [static]
Reimplemented from IntTab.
Definition at line 29 of file IntTrav.cpp.
int IntTrav::duplique () const [virtual]
Reimplemented from IntTab.
Definition at line 29 of file IntTrav.cpp.
const Type_info * IntTrav::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from IntTab.
Definition at line 29 of file IntTrav.cpp.
const Type_info * IntTrav::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from IntTab.
Definition at line 29 of file IntTrav.cpp.
IntTrav & IntTrav::operator= (const IntTab & tab)
Operateur copie d'un tableau (copie structure ET contenu)
Reimplemented from IntTab.
Definition at line 131 of file IntTrav.cpp.
References operator=().
{
// ATTENTION: note aux programmeurs
// La declaration de cet operateur est indispensable, sinon
// IntTab b;
// IntTrav a;
// a = b
// est traduit en
// IntTrav tmp(b); // copie la structure mais met les valeurs a zero
// a.operator=(tmp);
  IntTab::operator=(tab);
  return *this;
}
IntTrav & IntTrav::operator= (const IntTrav & tab)
Operateur copie (on ne veut pas l'operateur par defaut)
Definition at line 123 of file IntTrav.cpp.
Referenced by IntTrav(), and operator=().
{
  IntTab::operator=(tab);
  return *this;
}
IntTrav & IntTrav::operator= (int d)
Comme on surcharge l'operateur copie, il faut redefinir celui-la aussi.
Reimplemented from IntTab.
Definition at line 161 of file IntTrav.cpp.
References operator=().
{
  IntTab::operator=(d);
  return *this;
}
IntTrav & IntTrav::operator= (const IntVect & tab)
Operateur copie d'un tableau (copie structure ET contenu)
Reimplemented from IntTab.
Definition at line 146 of file IntTrav.cpp.
References operator=().
{
// ATTENTION: note aux programmeurs
// La declaration de cet operateur est indispensable, sinon
// IntTab b;
// IntTrav a;
// a = b
// est traduit en
// IntTrav tmp(b); // copie la structure mais met les valeurs a zero
// a.operator=(tmp);
  IntTab::operator=(tab);
  return *this;
}
Sortie & IntTrav::printOn (Sortie & x) const [protected, virtual]
Appel a IntTab::printOn.
Reimplemented from IntTab.
Definition at line 36 of file IntTrav.cpp.
{
  IntTab::printOn(os);
  return os;
}
Entree & IntTrav::readOn (Entree & is) [protected, virtual]
Appel a IntTab::readOn.
Reimplemented from IntTab.
Definition at line 43 of file IntTrav.cpp.
{
  IntTab::readOn(is);
  return is;
}
IntTrav & IntTrav::self_cast (Objet_U & r) [static]
Reimplemented from IntTab.
Definition at line 29 of file IntTrav.cpp.
const IntTrav & IntTrav::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from IntTab.
Definition at line 29 of file IntTrav.cpp.
unsigned IntTrav::taille_memoire () const [virtual]
Reimplemented from IntTab.
Definition at line 29 of file IntTrav.cpp.
Member Data Documentation
const Type_info IntTrav::info_obj [static]
Reimplemented from IntTab.
Definition at line 42 of file IntTrav.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/IntTrav.h
src/Kernel/Math/IntTrav.cpp