TRUST: Champ_Fonc_P0_VEF Class Reference
Champ_Fonc_P0_VEF Class Reference
classe Champ_Fonc_P0_VEF
#include <Champ_Fonc_P0_VEF.h>
Public Member Functions
Champ_Fonc_P0_VEF ()
~Champ_Fonc_P0_VEF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &)
const Zone_dis_base & zone_dis_base () const
virtual void mettre_a_jour (double)
Mise a jour en temps du champ.
double valeur_au_bord (int face) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
DoubleVect moyenne () const
renvoie la moyenne du champ au sens P0 i.e la somme, divisee par
le volume total du domaine, des valeurs constantes par element
multipliees par les volumes des elements
double moyenne (int) const
Cette fonction effectue le calcul de la moyenne au sens P0
de la kieme composante du champ.
int imprime (Sortie &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees
Sauvegarder sur un flot de sortie.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Fonc_P0_VEF & self_cast (Objet_U &)
static const Champ_Fonc_P0_VEF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Zone_VEF la_zone_VEF
Detailed Description
classe Champ_Fonc_P0_VEF
Definition at line 36 of file Champ_Fonc_P0_VEF.h.
Constructor & Destructor Documentation
Champ_Fonc_P0_VEF::Champ_Fonc_P0_VEF ()
Definition at line 26 of file Champ_Fonc_P0_VEF.cpp.
Champ_Fonc_P0_VEF::~Champ_Fonc_P0_VEF ()
Definition at line 26 of file Champ_Fonc_P0_VEF.cpp.
Member Function Documentation
void Champ_Fonc_P0_VEF::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) [inline, virtual]
Implements Champ_Fonc_base.
Definition at line 56 of file Champ_Fonc_P0_VEF.h.
Referenced by Champ_front_contact_VEF::connectivity_failed(), VEF_discretisation::critere_Q(), VEF_discretisation::distance_paroi(), VEF_discretisation::grad_u(), VEF_discretisation::h_conv(), VEF_discretisation::modifier_champ_tabule(), VEF_discretisation::taux_cisaillement(), and VEF_discretisation::y_plus().
{
  la_zone_VEF = (const Zone_VEF&) la_zone_dis_base;
}
Objet_U * Champ_Fonc_P0_VEF::cree_instance () [static]
Reimplemented in Champ_Fonc_Tabule_P0_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 26 of file Champ_Fonc_P0_VEF.cpp.
int Champ_Fonc_P0_VEF::duplique () const [virtual]
Implements Champ_Fonc_P0_base.
Reimplemented in Champ_Fonc_Tabule_P0_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 26 of file Champ_Fonc_P0_VEF.cpp.
const Type_info * Champ_Fonc_P0_VEF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_base.
Reimplemented in Champ_Fonc_Tabule_P0_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 26 of file Champ_Fonc_P0_VEF.cpp.
int Champ_Fonc_P0_VEF::imprime (Sortie & os, int ncomp) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees
Sauvegarder sur un flot de sortie.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 146 of file Champ_Fonc_P0_VEF.cpp.
References Champ_implementation_P0::imprime_P0().
{
  imprime_P0(os,ncomp);
  return 1;
}
const Type_info * Champ_Fonc_P0_VEF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_base.
Reimplemented in Champ_Fonc_Tabule_P0_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 26 of file Champ_Fonc_P0_VEF.cpp.
void Champ_Fonc_P0_VEF::mettre_a_jour (double temps) [virtual]
Mise a jour en temps du champ.
Implements Champ_Fonc_base.
Reimplemented in Champ_Fonc_Tabule_P0_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 45 of file Champ_Fonc_P0_VEF.cpp.
{
  Champ_Fonc_base::mettre_a_jour(t);
}
double Champ_Fonc_P0_VEF::moyenne (int ncomp) const
Cette fonction effectue le calcul de la moyenne au sens P0
de la kieme composante du champ.
Definition at line 117 of file Champ_Fonc_P0_VEF.cpp.
References la_zone_VEF, Field_base::nb_comp(), Zone_dis_base::nb_elem(), Zone_VF::porosite_elem(), Ref_Zone_VEF::valeur(), Champ_Don_base::valeurs(), and Zone_VF::volumes().
{
  const Zone_VEF& zvef=la_zone_VEF.valeur();
  const DoubleVect& porosite = zvef.porosite_elem();
  const DoubleVect& volumes = zvef.volumes();
  const DoubleTab& val = valeurs();
  double moy=0;
  double coef,sum_vol=0;
  if (nb_comp() == 1)
    for (int num_elem=0; num_elem<zvef.nb_elem(); num_elem++)
      {
        coef = porosite(num_elem)*volumes(num_elem);
        moy += val(num_elem)*coef;
        sum_vol += coef;
      }
  else
    for (int num_elem=0; num_elem<zvef.nb_elem(); num_elem++)
      {
        coef = porosite(num_elem)*volumes(num_elem);
        moy += val(num_elem,ncomp)*coef;
        sum_vol += coef;
      }
  moy /= sum_vol;
  return moy;
}
DoubleVect Champ_Fonc_P0_VEF::moyenne () const
renvoie la moyenne du champ au sens P0 i.e la somme, divisee par
le volume total du domaine, des valeurs constantes par element
multipliees par les volumes des elements
Definition at line 90 of file Champ_Fonc_P0_VEF.cpp.
References la_zone_VEF, Field_base::nb_comp(), Zone_dis_base::nb_elem(), Zone_VF::porosite_elem(), Ref_Zone_VEF::valeur(), Champ_Don_base::valeurs(), and Zone_VF::volumes().
{
  const Zone_VEF& zvef=la_zone_VEF.valeur();
  const DoubleVect& porosite = zvef.porosite_elem();
  const DoubleVect& volumes = zvef.volumes();
  const DoubleTab& val = valeurs();
  int k,nb_compo = nb_comp();
  DoubleVect moy(nb_compo);
  moy =0;
  double coef,sum_vol=0;
  for (int num_elem=0; num_elem<zvef.nb_elem(); num_elem++)
    {
      coef = porosite(num_elem)*volumes(num_elem);
      for (k=0; k<nb_compo; k++)
        moy[k] += val(num_elem,k)*coef;
      sum_vol += coef;
    }
  moy /= sum_vol;
  return moy;
}
Sortie & Champ_Fonc_P0_VEF::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_base.
Reimplemented in Champ_Fonc_Tabule_P0_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 32 of file Champ_Fonc_P0_VEF.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Champ_Fonc_P0_VEF::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_base.
Reimplemented in Champ_Fonc_Tabule_P0_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 40 of file Champ_Fonc_P0_VEF.cpp.
{
  return s ;
}
int Champ_Fonc_P0_VEF::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const [virtual]
Reimplemented from Champ_Fonc_P0_base.
Definition at line 70 of file Champ_Fonc_P0_VEF.cpp.
References Zone::nb_elem(), Champ_Fonc_P0_base::remplir_coord_noeuds(), IntVect::resize(), Zone_dis_base::zone(), and zone_dis_base().
{
  const Zone_dis_base& zone_dis = zone_dis_base();
  const Zone& zone = zone_dis.zone();
  int nb_elem=zone.nb_elem();
  polys.resize(nb_elem);
  remplir_coord_noeuds(positions);
  for(int i=0; i<nb_elem; i++)
    polys(i)=i;
  return 1;
}
const Champ_Fonc_P0_VEF & Champ_Fonc_P0_VEF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P0_base.
Reimplemented in Champ_Fonc_Tabule_P0_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 26 of file Champ_Fonc_P0_VEF.cpp.
Champ_Fonc_P0_VEF & Champ_Fonc_P0_VEF::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P0_base.
Reimplemented in Champ_Fonc_Tabule_P0_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 26 of file Champ_Fonc_P0_VEF.cpp.
unsigned Champ_Fonc_P0_VEF::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Champ_Fonc_Tabule_P0_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 26 of file Champ_Fonc_P0_VEF.cpp.
double Champ_Fonc_P0_VEF::valeur_au_bord (int face) const
Definition at line 50 of file Champ_Fonc_P0_VEF.cpp.
References Zone_VF::face_voisins(), la_zone_VEF, Ref_Zone_VEF::valeur(), and Champ_Don_base::valeurs().
{
  double val_bord;
  const DoubleTab& val = valeurs();
  const Zone_VEF& zone_VEF=la_zone_VEF.valeur();
  int n0 = zone_VEF.face_voisins(face,0);
  if (n0 != -1)
    val_bord = val[n0];
  else
    val_bord = val[zone_VEF.face_voisins(face,1)];
  return val_bord;
}
const Zone_dis_base & Champ_Fonc_P0_VEF::zone_dis_base () const [virtual]
Implements Champ_Fonc_base.
Definition at line 64 of file Champ_Fonc_P0_VEF.cpp.
References la_zone_VEF, and Ref_Zone_VEF::valeur().
Referenced by remplir_coord_noeuds_et_polys().
{
  return la_zone_VEF.valeur();
}
Member Data Documentation
const Type_info Champ_Fonc_P0_VEF::info_obj [static]
Reimplemented from Champ_Fonc_P0_base.
Reimplemented in Champ_Fonc_Tabule_P0_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 39 of file Champ_Fonc_P0_VEF.h.
Ref_Zone_VEF Champ_Fonc_P0_VEF::la_zone_VEF [protected]
Definition at line 53 of file Champ_Fonc_P0_VEF.h.
Referenced by Taux_cisaillement_P0_VEF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), moyenne(), valeur_au_bord(), and zone_dis_base().
The documentation for this class was generated from the following files:
src/VEF/Champs/Champ_Fonc_P0_VEF.h
src/VEF/Champs/Champ_Fonc_P0_VEF.cpp