TRUST: Champ_Generique_Morceau_Equation Class Reference
Champ_Generique_Morceau_Equation Class Reference
class Champ_Generique_Morceau_Equation
Champ destine a post-traiter une quantite liee a un morceau d equation
Consulter la hierarchie de MorEqn pour connaitre les morceaux d equation /!< Syntaxe a respecter pour jdd "nom_champ" Morceau_Equation { type "type_moreqn" numero "numero_moreqn" option "type_option" [ compo "num_compo" ] source Champ_Post_ref_Champ { Pb_champ "nom_pb" "nom_champ_discret" } } "nom_champ" fixe par utilisateur sera le nom du champ generique "type_moreqn" designe le type de morceau d equation (actuellement disponible "operateur") "numero_moreqn" designe le numero du morceau ex : cas operateur : 0 (diffusion) 1 (convection) [ 2 (gradient) 3 (divergence) pour le cas des "flux_bords" ] "type_option" option choisie ("stabilite" ou "flux_bords") "num_compo" numero de la composante a postraiter (a considerer uniquement pour "flux_bords" si plusieurs composantes)
#include <Champ_Generique_Morceau_Equation.h>
Public Member Functions
~Champ_Generique_Morceau_Equation ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_Generique_Morceau_Equation ()
void set_param (Param &param) override
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Entity get_localisation (const int index=-1) const override
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
const Motcle get_directive_pour_discr () const override
const Champ_base & get_champ (Champ &espace_stockage) const override
le morceau d equation lance la discretisation du champ espace_stockage
et remplit son tableau de valeurs par la methode calculer_pour_post(...)
Rq : Ce procede differe de celui applique dans les autres Champ_Generique pour lesquels
le remplissage du tableau de valeurs de espace_stockage n'est pas delegue
const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const override
Champ_Fonc & creer_espace_stockage (const Nature_du_champ &nature, const int nb_comp, Champ_Fonc &es_tmp) const override
const MorEqn & morceau () const
MorEqn & morceau ()
void completer (const Postraitement_base &post) override
void nommer_source () override
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
Champ_Gen_de_Champs_Gen ()
~Champ_Gen_de_Champs_Gen () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual List_Champ_Generique & get_set_sources ()
virtual Champ_Generique & get_set_source ()
void reset () override
int sauvegarder (Sortie &os) const override
sauvegarde des differentes sources
int reprendre (Entree &is) override
reprise des differentes sources
void completer (const Postraitement_base &post) override
void mettre_a_jour (double temps) override
virtual Champ_Fonc & creer_espace_stockage (const Nature_du_champ &nature, const int nb_comp, Champ_Fonc &es_tmp) const
virtual const Champ_Generique_base & get_source (int i) const
virtual Champ_Generique_base & set_source (int i)
virtual int get_nb_sources () const
int get_dimension () const override
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
void get_property_names (Motcles &list) const override
Renvoie la liste des "query" possibles pour le champ.
double get_time () const override
Renvoie le temps du Champ_Generique.
const Probleme_base & get_ref_pb_base () const override
const Discretisation_base & get_discretisation () const override
const Motcle get_directive_pour_discr () const override
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Entity get_localisation (const int index=-1) const override
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
const DoubleTab & get_ref_values () const override
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_copy_values (DoubleTab &) const override
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
const Domaine & get_ref_domain () const override
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
void get_copy_domain (Domaine &) const override
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_dis_base & get_ref_zone_dis_base () const override
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_Cl_dis_base & get_ref_zcl_dis_base () const override
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
const DoubleTab & get_ref_coordinates () const override
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
void get_copy_coordinates (DoubleTab &) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const override
void nommer_sources ()
virtual void nommer_source ()
int get_info_type_post () const override
const Champ_Generique_base & get_champ_post (const Motcle &nom) const override
int comprend_champ_post (const Motcle &identifiant) const override
virtual void fixer_serie (const double t1, const double t2)
virtual void fixer_tstat_deb (const double t1, const double t2)
virtual void lire_bidon (Entree &is) const
Public Member Functions inherited from Champ_Generique_base
Champ_Generique_base ()
~Champ_Generique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int get_dimension () const
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
virtual double get_time () const
Renvoie le temps du Champ_Generique.
virtual const Probleme_base & get_ref_pb_base () const
virtual const Discretisation_base & get_discretisation () const
virtual const Motcle get_directive_pour_discr () const
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
virtual const Nom & get_nom_post () const
virtual void get_property_names (Motcles &list) const
Renvoie la liste des "query" possibles pour le champ.
virtual const Noms get_property (const Motcle &query) const
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
virtual Entity get_localisation (const int index=-1) const
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
virtual int get_nb_localisations () const
virtual const DoubleTab & get_ref_values () const
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_copy_values (DoubleTab &) const
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const
virtual const Domaine & get_ref_domain () const
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual void get_copy_domain (Domaine &) const
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_dis_base & get_ref_zone_dis_base () const
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_Cl_dis_base & get_ref_zcl_dis_base () const
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
virtual const DoubleTab & get_ref_coordinates () const
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
virtual void get_copy_coordinates (DoubleTab &) const
virtual const IntTab & get_ref_connectivity (Entity index1, Entity index2) const
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
virtual void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const
virtual void reset ()=0
virtual void completer (const Postraitement_base &post)=0
virtual void mettre_a_jour (double temps)=0
virtual const Champ_base & get_champ (Champ &espace_stockage) const =0
virtual const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const =0
virtual const Champ_Generique_base & get_champ_post (const Motcle &nom) const
virtual int comprend_champ_post (const Motcle &identifiant) const
virtual int get_info_type_post () const =0
void fixer_identifiant_appel (const Nom &identifiant)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Generique_Morceau_Equation & self_cast (Objet_U &)
static const Champ_Generique_Morceau_Equation & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Gen_de_Champs_Gen
static const Type_info * info ()
static Champ_Gen_de_Champs_Gen & self_cast (Objet_U &)
static const Champ_Gen_de_Champs_Gen & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Generique_base
static const Type_info * info ()
static Champ_Generique_base & self_cast (Objet_U &)
static const Champ_Generique_base & self_cast (const Objet_U &)
static int composante (const Nom &nom_test, const Nom &nom, const Noms &composantes, const Noms &synonyms)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Gen_de_Champs_Gen
static const Type_info info_obj
Static Public Attributes inherited from Champ_Generique_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Champ_Generique_base
Sortie & printOn (Sortie &x) const override
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int numero_morceau_
Nom type_morceau_
Nom option_
int compo_
Ref_Equation_base ref_eq_
Motcle localisation_
Protected Attributes inherited from Champ_Gen_de_Champs_Gen
List_Nom noms_sources_ref_
List_Ref_Champ_Generique_base sources_reference_
Protected Attributes inherited from Champ_Generique_base
Nom nom_post_
Nom identifiant_appel_
Nom nom_pb_
Ref_Probleme_base ref_pb_
Additional Inherited Members
Static Protected Member Functions inherited from Champ_Generique_base
static void assert_parallel (int)
Detailed Description
class Champ_Generique_Morceau_Equation
Champ destine a post-traiter une quantite liee a un morceau d equation
Consulter la hierarchie de MorEqn pour connaitre les morceaux d equation /!< Syntaxe a respecter pour jdd "nom_champ" Morceau_Equation { type "type_moreqn" numero "numero_moreqn" option "type_option" [ compo "num_compo" ] source Champ_Post_ref_Champ { Pb_champ "nom_pb" "nom_champ_discret" } } "nom_champ" fixe par utilisateur sera le nom du champ generique "type_moreqn" designe le type de morceau d equation (actuellement disponible "operateur") "numero_moreqn" designe le numero du morceau ex : cas operateur : 0 (diffusion) 1 (convection) [ 2 (gradient) 3 (divergence) pour le cas des "flux_bords" ] "type_option" option choisie ("stabilite" ou "flux_bords") "num_compo" numero de la composante a postraiter (a considerer uniquement pour "flux_bords" si plusieurs composantes)
Definition at line 39 of file Champ_Generique_Morceau_Equation.h.
Constructor & Destructor Documentation
~Champ_Generique_Morceau_Equation()
Champ_Generique_Morceau_Equation::~Champ_Generique_Morceau_Equation ()
Definition at line 24 of file Champ_Generique_Morceau_Equation.cpp.
Champ_Generique_Morceau_Equation()
Champ_Generique_Morceau_Equation::Champ_Generique_Morceau_Equation ()
Definition at line 27 of file Champ_Generique_Morceau_Equation.cpp.
{
  numero_morceau_ = -1;
  compo_=0;
}
References compo_, and numero_morceau_.
Member Function Documentation
completer()
void Champ_Generique_Morceau_Equation::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 65 of file Champ_Generique_Morceau_Equation.cpp.
{
  const Probleme_base& Pb = get_ref_pb_base();
  int numero_eq_=-1;
  if (sub_type(Champ_Generique_refChamp,get_source(0)))
    {
      Champ espace_stockage;
      const Champ_base& mon_champ = get_source(0).get_champ(espace_stockage);
      if (sub_type(Champ_Inc_base,mon_champ))
        {
          const Champ_Inc_base& mon_champ_inc = ref_cast(Champ_Inc_base,mon_champ);
          {
// On recupere l equation alors qu elle n est pas encore associee au Champ_Inc
// On parcours les equations du probleme et on identifie celle qui correspond au champ inconnu
            int nb_eq = Pb.nombre_d_equations();
            int i=0;
            while (i<nb_eq)
              {
                const Equation_base& eq_test = Pb.equation(i);
                if ((eq_test.inconnue().le_nom() == mon_champ_inc.le_nom()))
                  {
                    numero_eq_=i;
                    break;
                  }
                i++;
              }
          }
        }
    }
  if (numero_eq_==-1)
    {
      Cerr<<"We can apply a Champ_Generique_Morceau_Equation only to an unknown field of the problem"<<finl;
      exit();
    }
  ref_eq_ = Pb.equation(numero_eq_);
  localisation_ = morceau().get_localisation_pour_post(option_);
// Appel de la methode de la classe mere fait apres pour que
// la methode nommer_source() dispose de ref_eq_ initialise
  Champ_Gen_de_Champs_Gen::completer(post);
}
References Cerr, Champ_Gen_de_Champs_Gen::completer(), Probleme_base::equation(), Process::exit(), finl, Champ_Generique_base::get_champ(), MorEqn::get_localisation_pour_post(), Champ_Gen_de_Champs_Gen::get_ref_pb_base(), Champ_Gen_de_Champs_Gen::get_source(), Equation_base::inconnue(), Field_base::le_nom(), O_U_Ptr::le_nom(), localisation_, morceau(), Probleme_base::nombre_d_equations(), option_, ref_cast, ref_eq_, and sub_type.
cree_instance()
Objet_U * Champ_Generique_Morceau_Equation::cree_instance () static
Definition at line 24 of file Champ_Generique_Morceau_Equation.cpp.
creer_espace_stockage()
Champ_Fonc & Champ_Generique_Morceau_Equation::creer_espace_stockage (const Nature_du_champ & nature, const int nb_comp, Champ_Fonc & es_tmp) const override virtual
< Pour avoir les flux_bords aux faces et non aux elements en VDF (ex: temperature)
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 113 of file Champ_Generique_Morceau_Equation.cpp.
{
  Noms noms;
  Noms unites;
  for (int c=0; c<nb_comp; c++)
    {
// noms.add("bidon");
      unites.add("bidon");
    }
  noms.add("bidon");
  double temps;
  temps = get_time();
  const Discretisation_base&  discr = get_discretisation();
  Motcle directive;
  if ((Motcle(option_)=="flux_bords") || (Motcle(option_)=="flux_surfacique_bords"))
    directive = "champ_face"; //!< Pour avoir les flux_bords aux faces et non aux elements en VDF (ex: temperature)
  else
    directive = get_directive_pour_discr();
  const Zone_dis_base& zone_dis = get_ref_zone_dis_base();
  discr.discretiser_champ(directive,zone_dis,nature,noms,unites,nb_comp,temps,es_tmp);
  if (directive=="pression")
    {
      const  Zone_Cl_dis_base& zcl = get_ref_zcl_dis_base();
      es_tmp->completer(zcl);
    }
  return es_tmp;
}
References Vect_Nom::add(), Discretisation_base::discretiser_champ(), get_directive_pour_discr(), Champ_Gen_de_Champs_Gen::get_discretisation(), Champ_Gen_de_Champs_Gen::get_ref_zcl_dis_base(), Champ_Gen_de_Champs_Gen::get_ref_zone_dis_base(), Champ_Gen_de_Champs_Gen::get_time(), and option_.
Referenced by get_champ(), and get_champ_without_evaluation().
duplique()
int Champ_Generique_Morceau_Equation::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Champ_Generique_Morceau_Equation.cpp.
get_champ()
const Champ_base & Champ_Generique_Morceau_Equation::get_champ (Champ & espace_stockage) const override virtual
le morceau d equation lance la discretisation du champ espace_stockage
et remplit son tableau de valeurs par la methode calculer_pour_post(...)
Rq : Ce procede differe de celui applique dans les autres Champ_Generique pour lesquels
le remplissage du tableau de valeurs de espace_stockage n'est pas delegue
Implements Champ_Generique_base.
Definition at line 152 of file Champ_Generique_Morceau_Equation.cpp.
{
  Champ_Fonc es_tmp;
  Nature_du_champ nature;
  int nb_comp = -1;
  if ((Motcle(option_)=="stabilite") || (Motcle(option_)=="flux_bords") || (Motcle(option_)=="flux_surfacique_bords"))
    {
      nature = scalaire;
      nb_comp = 1;
    }
  else
    {
      Cerr << "Error. Contact TRUST support." << finl;
      Process::exit();
    }
  espace_stockage = creer_espace_stockage(nature,nb_comp,es_tmp);
  morceau().calculer_pour_post(espace_stockage,option_,compo_);
  DoubleTab& es_val = espace_stockage.valeurs();
  es_val.echange_espace_virtuel();
  return espace_stockage.valeur();
}
References MorEqn::calculer_pour_post(), Cerr, compo_, creer_espace_stockage(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, morceau(), option_, scalaire, Deriv_Champ_base::valeur(), and Champ::valeurs().
get_champ_without_evaluation()
const Champ_base & Champ_Generique_Morceau_Equation::get_champ_without_evaluation (Champ & espace_stockage) const override virtual
Implements Champ_Generique_base.
Definition at line 176 of file Champ_Generique_Morceau_Equation.cpp.
{
  Champ_Fonc es_tmp;
  Nature_du_champ nature;
  int nb_comp = -1;
  if ((Motcle(option_)=="stabilite") || (Motcle(option_)=="flux_bords") || (Motcle(option_)=="flux_surfacique_bords"))
    {
      nature = scalaire;
      nb_comp = 1;
    }
  espace_stockage = creer_espace_stockage(nature,nb_comp,es_tmp);
  return espace_stockage.valeur();
}
References creer_espace_stockage(), option_, scalaire, and Deriv_Champ_base::valeur().
get_directive_pour_discr()
const Motcle Champ_Generique_Morceau_Equation::get_directive_pour_discr () const override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 334 of file Champ_Generique_Morceau_Equation.cpp.
{
  Motcle directive;
  if (localisation_=="elem")
    directive = "champ_elem";
  else if (localisation_=="face")
    directive = "champ_face";
  else if (localisation_=="som")
    directive = "champ_sommets";
  else
    {
      Cerr << "Error of type : localisation should be specified to elem or som or face for the defined field " << nom_post_ << finl;
      throw Champ_Generique_erreur("INVALID");
    }
  return directive;
}
References Cerr, finl, localisation_, and Champ_Generique_base::nom_post_.
Referenced by creer_espace_stockage().
get_info()
const Type_info * Champ_Generique_Morceau_Equation::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 24 of file Champ_Generique_Morceau_Equation.cpp.
get_localisation()
Entity Champ_Generique_Morceau_Equation::get_localisation (const int index = -1) const override virtual
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 227 of file Champ_Generique_Morceau_Equation.cpp.
{
  Entity loc;
// Pour initialisation
  loc = NODE;
  if (localisation_=="elem")
    loc = ELEMENT;
  else if (localisation_=="face")
    loc = FACE;
  else if (localisation_=="som")
    loc = NODE;
  else
    {
      Cerr << "Error of type : localisation should be specified to elem or som or face for the defined field " << nom_post_ << finl;
      throw Champ_Generique_erreur("INVALID");
    }
  return loc;
}
References Cerr, ELEMENT, FACE, finl, localisation_, NODE, and Champ_Generique_base::nom_post_.
get_property()
const Noms Champ_Generique_Morceau_Equation::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 191 of file Champ_Generique_Morceau_Equation.cpp.
{
  Motcles motcles(2);
  motcles[0] = "composantes";
  motcles[1] = "unites";
  int rang = motcles.search(query);
  switch(rang)
    {
    case 0:
      {
        Noms compo(1);
        Nom nume((int)1);
        compo[0] = nom_post_+nume;
        return compo;
        break;
      }
    case 1:
      {
        Noms unites(1);
        if (Motcle(option_)=="stabilite")
          unites[0] = "s";
        else if (Motcle(option_)=="flux_bords" || Motcle(option_)=="flux_surfacique_bords")
          unites[0] = "bidon";
        return unites;
        break;
      }
    }
  return Champ_Gen_de_Champs_Gen::get_property(query);
}
References Champ_Gen_de_Champs_Gen::get_property(), Champ_Generique_base::nom_post_, option_, and Motcles::search().
info()
const Type_info * Champ_Generique_Morceau_Equation::info () static
Definition at line 24 of file Champ_Generique_Morceau_Equation.cpp.
morceau() [1/2]
MorEqn & Champ_Generique_Morceau_Equation::morceau ()
Definition at line 325 of file Champ_Generique_Morceau_Equation.cpp.
{
  int nb_operateurs = ref_eq_->nombre_d_operateurs();
  if (numero_morceau_ >= nb_operateurs)
    return ref_eq_->operateur_fonctionnel(numero_morceau_-nb_operateurs).l_op_base();
  return ref_eq_->operateur(numero_morceau_).l_op_base();
}
References Operateur::l_op_base(), Equation_base::nombre_d_operateurs(), numero_morceau_, Equation_base::operateur(), Equation_base::operateur_fonctionnel(), and ref_eq_.
morceau() [2/2]
const MorEqn & Champ_Generique_Morceau_Equation::morceau () const
Definition at line 316 of file Champ_Generique_Morceau_Equation.cpp.
{
  int nb_operateurs = ref_eq_->nombre_d_operateurs();
  if (numero_morceau_ >= nb_operateurs)
    return ref_eq_->operateur_fonctionnel(numero_morceau_-nb_operateurs).l_op_base();
  return ref_eq_->operateur(numero_morceau_).l_op_base();
}
References Operateur::l_op_base(), Equation_base::nombre_d_operateurs(), numero_morceau_, Equation_base::operateur(), Equation_base::operateur_fonctionnel(), and ref_eq_.
Referenced by completer(), and get_champ().
nommer_source()
void Champ_Generique_Morceau_Equation::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 250 of file Champ_Generique_Morceau_Equation.cpp.
{
  Motcle type_morceau, type_option;
  if (Motcle(type_morceau_)=="operateur")
    {
      if (numero_morceau_==0)
        type_morceau = "diffusion";
      else if (numero_morceau_==1)
        type_morceau = "convection";
      else if (numero_morceau_==2)
        type_morceau = "gradient";
      else if (numero_morceau_==3)
        type_morceau = "divergence";
      else
        {
          Cerr<<"This operateur number is not available."<<finl;
          exit();
        }
    }
  else
    {
      Cerr<<"Currently the only pieces of equations considered for the postprocessing"<<finl;
      Cerr<<"are of type operator"<<finl;
      exit();
    }
  if (Motcle(option_)=="stabilite")
    type_option = "dt";
  else if (Motcle(option_)=="flux_bords")
    {
      type_option = "flux_bords";
    }
  else if (Motcle(option_)=="flux_surfacique_bords")
    {
      type_option = "flux_surfacique_bords";
    }
  else
    {
      Cerr<<"Currently the only options considered for a piece of equation are \"stabilite\" and \"flux_bords\"."<<finl;
      exit();
    }
  if (nom_post_=="??")
    {
      Nom nom_post_source;
      const Nom& nom_eq = ref_eq_->le_nom();
      nom_post_source = nom_eq;
      nom_post_source += "_";
      nom_post_source +=  type_morceau;
      nom_post_source += "_";
      nom_post_source += type_option ;
      if ((Motcle(option_)=="flux_bords") || (Motcle(option_)=="flux_surfacique_bords"))
        {
          Nom nume(compo_);
          nom_post_source += nume;
        }
      nommer(nom_post_source);
    }
}
References Cerr, compo_, Process::exit(), finl, Equation_base::le_nom(), Champ_Generique_base::nom_post_, Champ_Generique_base::nommer(), numero_morceau_, option_, ref_eq_, and type_morceau_.
printOn()
Sortie & Champ_Generique_Morceau_Equation::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 33 of file Champ_Generique_Morceau_Equation.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Generique_Morceau_Equation::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 39 of file Champ_Generique_Morceau_Equation.cpp.
{
  Champ_Gen_de_Champs_Gen::readOn(s);
  return s ;
}
References Champ_Gen_de_Champs_Gen::readOn().
self_cast() [1/2]
const Champ_Generique_Morceau_Equation & Champ_Generique_Morceau_Equation::self_cast (const Objet_U & r) static
Definition at line 24 of file Champ_Generique_Morceau_Equation.cpp.
self_cast() [2/2]
Champ_Generique_Morceau_Equation & Champ_Generique_Morceau_Equation::self_cast (Objet_U & r) static
Definition at line 24 of file Champ_Generique_Morceau_Equation.cpp.
set_param()
void Champ_Generique_Morceau_Equation::set_param (Param & param) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 52 of file Champ_Generique_Morceau_Equation.cpp.
{
  Champ_Gen_de_Champs_Gen::set_param(param);
  param.ajouter("type",&type_morceau_,Param::REQUIRED);
  param.ajouter("numero",&numero_morceau_);
  param.ajouter("option",&option_,Param::REQUIRED);
  param.ajouter("compo",&compo_);
}
References Param::ajouter(), compo_, numero_morceau_, option_, Param::REQUIRED, Champ_Gen_de_Champs_Gen::set_param(), and type_morceau_.
taille_memoire()
unsigned Champ_Generique_Morceau_Equation::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Champ_Generique_Morceau_Equation.cpp.
Member Data Documentation
compo_
int Champ_Generique_Morceau_Equation::compo_ protected
Definition at line 67 of file Champ_Generique_Morceau_Equation.h.
Referenced by Champ_Generique_Morceau_Equation(), get_champ(), nommer_source(), and set_param().
info_obj
const Type_info Champ_Generique_Morceau_Equation::info_obj static
Definition at line 42 of file Champ_Generique_Morceau_Equation.h.
localisation_
Motcle Champ_Generique_Morceau_Equation::localisation_ protected
Definition at line 69 of file Champ_Generique_Morceau_Equation.h.
Referenced by completer(), get_directive_pour_discr(), and get_localisation().
numero_morceau_
int Champ_Generique_Morceau_Equation::numero_morceau_ protected
Definition at line 64 of file Champ_Generique_Morceau_Equation.h.
Referenced by Champ_Generique_Morceau_Equation(), morceau(), nommer_source(), and set_param().
option_
Nom Champ_Generique_Morceau_Equation::option_ protected
Definition at line 66 of file Champ_Generique_Morceau_Equation.h.
Referenced by completer(), creer_espace_stockage(), get_champ(), get_champ_without_evaluation(), get_property(), nommer_source(), and set_param().
ref_eq_
Ref_Equation_base Champ_Generique_Morceau_Equation::ref_eq_ protected
Definition at line 68 of file Champ_Generique_Morceau_Equation.h.
Referenced by completer(), morceau(), and nommer_source().
type_morceau_
Nom Champ_Generique_Morceau_Equation::type_morceau_ protected
Definition at line 65 of file Champ_Generique_Morceau_Equation.h.
Referenced by nommer_source(), and set_param().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Generique_Morceau_Equation.h
src/Kernel/Champs/Champ_Generique_Morceau_Equation.cpp