TRUST: O_U_Ptr Class Reference
O_U_Ptr Class Reference
Pointeur sur un Objet_U.
Le constructeur par defaut construit un pointeur "nul". O_U_Ptr_H.
#include <O_U_Ptr.h>
Public Member Functions
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr ()
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const)
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Private Member Functions
O_U_Ptr (const O_U_Ptr &)
Constructeur par copie.
const O_U_Ptr & operator= (const O_U_Ptr &)
Operateur copie.
Private Attributes
int cle_
int ptr_object_id_
Detailed Description
Pointeur sur un Objet_U.
Le constructeur par defaut construit un pointeur "nul". O_U_Ptr_H.
Definition at line 39 of file O_U_Ptr.h.
Constructor & Destructor Documentation
O_U_Ptr::~O_U_Ptr () [protected]
Destructeur. Il ne detruit pas l'objet en reference.
Definition at line 66 of file O_U_Ptr.cpp.
References cle_.
{
// Paranoia : on rend le pointeur invalide
  cle_ = -2;
}
O_U_Ptr::O_U_Ptr () [protected]
construit un pointeur nul (cle a -1)
Definition at line 74 of file O_U_Ptr.cpp.
                 :
  cle_(-1),
  ptr_object_id_(-1)
{
}
O_U_Ptr::O_U_Ptr (const O_U_Ptr & ptr) [private]
Constructeur par copie.
Definition at line 82 of file O_U_Ptr.cpp.
                                  : Objet_U(ptr)
{
  assert(0);
}
Member Function Documentation
int O_U_Ptr::change_num (const int * const new_ones) [protected, virtual]
renumerotation des objets
Pour mettre a jour les cles lorsque les
Objet_U ont etes renumerotes.
Returns:
int
Signification: la nouvelle cle du pointeur
Contraintes:
Reimplemented from Objet_U.
Definition at line 203 of file O_U_Ptr.cpp.
References cle_.
{
  Objet_U::change_num(new_ones);
// Il ne faut pas faire d'appel a une fonction qui fait "verifie"
// car la memoire est en cours de modification.
  if (cle_ > -1)
    cle_ = new_ones[cle_];
  return cle_;
}
int O_U_Ptr::check_O_U_Ptr_type (const Objet_U * ptr) const [protected]
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
< Le pointeur nul est valide
Definition at line 148 of file O_U_Ptr.cpp.
References Type_info::can_cast(), Cerr, cle_, Process::exit(), Objet_U::get_info(), get_info_ptr(), Objet_U::le_type(), Process::me(), Type_info::name(), and ptr_object_id_.
Referenced by set_O_U_Ptr().
{
  if (ptr == 0)
    return 1; //!< Le pointeur nul est valide
  const Objet_U& objet = *ptr;
// On verifie que l'objet est du bon type :
// type accepte par le pointeur :
  const Type_info& type_info_ptr = get_info_ptr();
// type de l'objet :
  const Type_info& type_info_obj = *(objet.get_info());
// Peut-on convertir type_info_obj en type_info_ptr ?
  if (! type_info_ptr.can_cast(&type_info_obj))
    {
      Cerr << "(PE" << me() << ") ";
      Cerr << "Error in O_U_Ptr::get_O_U_Ptr_check() : Type error\n";
      Cerr << " Pointer type " << le_type();
      Cerr << "\n cle_           = " << cle_;
      Cerr << "\n ptr_object_id_ = " << ptr_object_id_;
      std::cerr << "\n &memoire.objet_u(cle_) = " << ptr;
      Cerr << "\n Type accepted by the pointer : " << type_info_ptr.name();
      Cerr << "\n Object type in reference : " << type_info_obj.name();
      assert(0);
      exit();
    }
  return 1;
}
virtual int O_U_Ptr::duplique () const [pure virtual]
Implements Objet_U.
Implemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Ref_Debog_Pb, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Deriv_, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Ref_Interprete, Ref_Interprete_bloc, Ref_, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Ref_Fluide_Dilatable_base, Deriv_EDO_Pression_th_base, EDO_Pression_th, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Ref_Marqueur_Lagrange_base, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Ref_Correlation_base, Deriv_Correlation_base, Correlation, Ref_Correlation, Ref_Saturation_base, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, Elem_VEF, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
const Type_info * O_U_Ptr::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Ref_Debog_Pb, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Deriv_, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Ref_Interprete, Ref_Interprete_bloc, Ref_, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Ref_Fluide_Dilatable_base, Deriv_EDO_Pression_th_base, EDO_Pression_th, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Ref_Marqueur_Lagrange_base, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Ref_Correlation_base, Deriv_Correlation_base, Correlation, Ref_Correlation, Ref_Saturation_base, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, Elem_VEF, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 28 of file O_U_Ptr.cpp.
virtual const Type_info& O_U_Ptr::get_info_ptr () const [pure virtual]
Implemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Deriv_Iterateur_Source_CoviMAC_base, Deriv_Elem_CoviMAC_base, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Deriv_Iterateur_Source_EF_base, Deriv_Elem_EF_base, Ref_Zone_Cl_EF, Ref_Zone_EF, Deriv_Champ_Generique_Statistiques_base, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Deriv_Assembleur_base, Deriv_Champ_base, Deriv_Champ_Don_base, Deriv_Champ_Fonc_base, Deriv_Champ_front_base, Deriv_Champ_Generique_base, Deriv_Champ_Inc_base, Deriv_Cond_lim_base, Ref_Debog_Pb, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Deriv_Equation_base, Deriv_Format_Post_base, Deriv_Parametre_equation_base, Deriv_Postraitement_base, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Deriv_Schema_Temps_base, Deriv_Solveur_Implicite_Base, Deriv_Solveur_Masse_base, Deriv_Source_base, Deriv_Sous_zone_dis_base, Deriv_Zone_Cl_dis_base, Deriv_Zone_dis_base, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Deriv_Interpolation_IBM_base, Deriv_Raccord_base, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Deriv_Precond_base, Deriv_SolvElem_base, Deriv_SolveurSys_base, Deriv_Operateur_Conv_base, Deriv_Operateur_Diff_base, Deriv_Operateur_Div_base, Deriv_Operateur_Grad_base, Deriv_Operateur_Statistique_tps_base, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Ref_Interprete, Ref_Interprete_bloc, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Deriv_Iterateur_PolyMAC_base, Deriv_Iterateur_Source_PolyMAC_base, Deriv_Elem_PolyMAC_base, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Deriv_EOS_Tools_base, Deriv_Loi_Etat_base, Ref_Fluide_Dilatable_base, Deriv_EDO_Pression_th_base, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Deriv_Modele_Permeabilite_base, Ref_Marqueur_Lagrange_base, Deriv_Traitement_particulier_NS_base, Deriv_Mod_turb_hyd_base, Deriv_Modele_turbulence_scal_base, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Deriv_Turbulence_paroi_base, Deriv_Turbulence_paroi_scal_base, Ref_Correlation_base, Deriv_Correlation_base, Ref_Correlation, Ref_Saturation_base, Deriv_Saturation_base, Deriv_Operateur_Evanescence_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Deriv_Traitement_particulier_Solide_base, Ref_Champ_Face, Ref_Champ_P0_VDF, Deriv_Iterateur_VDF_base, Deriv_Iterateur_Source_VDF_base, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Deriv_Iterateur_Source_VEF_base, Deriv_Elem_VEF_base, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Referenced by check_O_U_Ptr_type(), and Deriv_::typer().
Objet_U * O_U_Ptr::get_O_U_Ptr () const [protected, virtual]
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
Definition at line 239 of file O_U_Ptr.cpp.
References cle_, get_O_U_Ptr_check(), Memoire::Instance(), and Memoire::objet_u().
Referenced by Deriv_::detach(), Deriv_::printOn(), and Deriv_::typer().
{
  const Objet_U * objet;
  if (cle_ < 0)
    {
      objet =  0;
    }
  else
    {
      Memoire& memoire = Memoire::Instance();
      objet = & memoire.objet_u(cle_);
    }
  assert(objet == get_O_U_Ptr_check());
  return (Objet_U*) objet;
}
Objet_U * O_U_Ptr::get_O_U_Ptr_check () const [protected]
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
Definition at line 111 of file O_U_Ptr.cpp.
References Cerr, cle_, Process::exit(), Objet_U::get_object_id(), Memoire::Instance(), Objet_U::le_type(), Process::me(), Memoire::objet_u(), and ptr_object_id_.
Referenced by Deriv_::associer_(), get_O_U_Ptr(), le_nom(), non_nul(), printOn(), and set_O_U_Ptr().
{
  Objet_U * addr = 0;
  if (cle_ == -1 && ptr_object_id_ == -1)
    {
      addr = 0;
    }
  else
    {
      Memoire& memoire = Memoire::Instance();
      Objet_U& objet = memoire.objet_u(cle_);
      addr = &objet;
      const int id = objet.get_object_id();
      if (id != ptr_object_id_)
        {
          Cerr << "(PE" << me() << ") ";
          Cerr << "Error in O_U_Ptr::get_O_U_Ptr_check() : id != ptr_object_id_\n";
          Cerr << " Pointer type " << le_type();
          Cerr << "\n cle_           = " << cle_;
          Cerr << "\n ptr_object_id_ = " << ptr_object_id_;
          Cerr << "\n id             = " << id;
          std::cerr << "\n &la_memoire().objet_u(cle_) = " << addr << std::endl;
// Si ca plante a cet endroit, c'est que l'objet en reference
// a ete detruit et que la reference est encore utilisee.
          assert(0);
          exit();
        }
    }
  return addr;
}
int O_U_Ptr::get_ptr_cle () const [protected]
Definition at line 277 of file O_U_Ptr.cpp.
References cle_.
{
  return cle_;
}
int O_U_Ptr::get_ptr_object_id () const [protected]
Definition at line 282 of file O_U_Ptr.cpp.
References ptr_object_id_.
{
  return ptr_object_id_;
}
const Type_info * O_U_Ptr::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Ref_Debog_Pb, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Deriv_, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Ref_Interprete, Ref_Interprete_bloc, Ref_, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Ref_Fluide_Dilatable_base, Deriv_EDO_Pression_th_base, EDO_Pression_th, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Ref_Marqueur_Lagrange_base, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Ref_Correlation_base, Deriv_Correlation_base, Correlation, Ref_Correlation, Ref_Saturation_base, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, Elem_VEF, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 28 of file O_U_Ptr.cpp.
const Nom & O_U_Ptr::le_nom () const [virtual]
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
Reimplemented from Objet_U.
Reimplemented in Champ, Champ_front, SolveurSys, and Operateur_Statistique_tps.
Definition at line 179 of file O_U_Ptr.cpp.
References get_O_U_Ptr_check(), and Objet_U::le_nom().
Referenced by Masse_CoviMAC_Face::ajouter_blocs(), Op_Conv_EF::ajouter_contribution_sous_cond(), Solveur_Masse_base::ajouter_masse(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim2(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim2(), Op_Conv_EF::ajouter_sous_cond_gen(), Milieu_base::associer_equation(), Terme_Source_Constituant_VEF_Face::associer_pb(), Terme_Source_Constituant_VDF_Elem::associer_pb(), Terme_Boussinesq_base::associer_pb(), Terme_Source_Constituant_PolyMAC_Elem::associer_pb(), Puissance_Thermique_EF::associer_pb(), Terme_Source_Constituant_CoviMAC_Elem::associer_pb(), Op_Conv_EF::calculer_dt_stab(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), paroi_contact_fictif::complement(), paroi_contact::complement(), QDM_Multiphase::completer(), Navier_Stokes_Fluide_Dilatable_base::completer(), Champ_Post_Operateur_Eqn::completer(), Champ_Generique_Transformation::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Generique_Gradient::completer(), Champ_Generique_Extraction::completer(), Source_base::contribuer_a_avec(), Operateur_base::contribuer_a_avec(), Operateur_base::contribuer_termes_croises(), Champ_front_contact_VEF::creer(), Champ_Fonc_MED::creer(), Equation_base::creer_champ(), Postraitement::creer_champ_post_moreqn(), Source_base::dimensionner(), Solveur_Masse_base::dimensionner(), Operateur_base::dimensionner(), Masse_CoviMAC_Face::dimensionner_blocs(), Operateur_base::dimensionner_termes_croises(), Sous_zone_VF::discretiser(), Champ_Generique_Interpolation::discretiser_domaine(), Equation_base::expression_residu(), Turbulence_paroi_base::get_champ(), Equation_base::get_champ(), Discretisation_base::get_name_of_type_for(), Champ_Generique_Interpolation::get_ref_zone_dis_base(), Op_VEF_Face::impr(), Op_EF_base::impr(), Sonde::initialiser(), Champ_front_lu::initialiser(), Loi_Etat_GR_base::initialiser_inco_ch(), Simple::iterer_eqn(), SETS::iterer_eqn(), Simple::iterer_eqs(), SETS::iterer_NS(), Op_Moyenne::le_nom(), Op_Ecart_type::le_nom(), Op_Correlation::le_nom(), Frontiere_dis_base::le_nom(), Champ_Fonc_MED::lire(), Equation_base::lire_cond_init(), Terme_Puissance_Thermique::lire_donnees(), PlaqThVDF::mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), Op_VEF_Face::modifier_flux(), Terme_Puissance_Thermique::modify_name_file(), Champ_Generique_Morceau_Equation::nommer_source(), Operateur_base::ouvrir_fichier(), Op_Diff_VEF_base::phi_psi_diffuse(), Op_Conv_VEF_base::phi_u_transportant(), Op_Conv_EF_base::phi_u_transportant(), Turbulence_paroi_scal::printOn(), Turbulence_paroi::printOn(), Integrale_tps_produit_champs::printOn(), Integrale_tps_Champ::printOn(), Cond_lim::printOn(), Terme_Source_Solide_SWIFT_VDF::readOn(), Convection_Diffusion_Temperature::readOn(), Convection_Diffusion_Concentration::readOn(), Convection_Diffusion_Espece_Multi_base::readOn(), Navier_Stokes_std::reprendre(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), VEF_discretisation::residu(), VDF_discretisation::residu(), CoviMAC_discretisation::residu(), Operateurs_Statistique_tps::sauvegarder(), Champ_input_P0::setValue(), Champ_Input_Proto::setValueOnTab(), liste::suppr(), and Champ_front_contact_VEF::test_faces_coin().
{
  static Nom nom("Pointeur Nul");
  const Objet_U * addr = get_O_U_Ptr_check();
  if (addr)
    return addr->le_nom();
  return nom;
}
int O_U_Ptr::non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
Definition at line 98 of file O_U_Ptr.cpp.
References cle_, and get_O_U_Ptr_check().
Referenced by Milieu_base::a_gravite(), Milieu_composite::abortTimeStep(), Milieu_base::abortTimeStep(), Equation_base::abortTimeStep(), Debog::active(), ajouter_bord(), Masse_VDF_Face::appliquer_impl(), Masse_PolyMAC_Face::appliquer_impl(), Assembleur_P_VDF::assembler_mat(), Assembleur_P_VDF::assembler_QC(), Assembleur_P_VDF::assembler_rho_variable(), Sous_Zone::associer_(), Echange_impose_base::associer_fr_dis_base(), Neumann_sortie_libre::associer_fr_dis_base(), Cond_lim_base::associer_fr_dis_base(), Convection_Diffusion_Temperature::associer_milieu_base(), Convection_Diffusion_Concentration::associer_milieu_base(), Eval_Dift_VDF_var_Elem::associer_modele_turbulence(), Eval_Dift_VDF_const_Elem::associer_modele_turbulence(), Terme_Boussinesq_base::associer_pb(), Probleme_base::associer_sch_tps_base(), Echange_impose_base::avancer(), Equation_base::avancer(), Schema_Comm::begin_comm(), Champ_front_contact_VEF::calcul_grads_locaux(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Milieu_base::calculer_alpha(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Traitement_particulier_NS_EC::calculer_Ec(), calculer_h_distant(), calculer_h_local(), Terme_Source_Acceleration::calculer_la_source(), Loi_Etat_GP_QC::calculer_masse_volumique(), Op_Dift_VEF_Face::calculer_pour_post(), Op_Diff_VEF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::calculer_trace_pression(), Echange_impose_base::changer_temps_futur(), Zone::chercher_elements(), Op_Dift_VEF_base::completer(), Op_Dift_VDF_var_Elem::completer(), Op_Dift_VDF_Elem::completer(), Op_Diff_VDF_base::completer(), Fluide_Weakly_Compressible::completer(), Op_Moyenne::completer(), Op_Ecart_type::completer(), Operateur_base::completer(), Operateur::completer(), Equation_base::completer(), Op_Diff_CoviMAC_Face::completer(), Op_Diff_CoviMAC_Elem::completer(), Convection_Diffusion_Concentration::constituant(), construire_matrice_implicite(), Partitionneur_Tranche::construire_partition(), Partitionneur_Sous_Zones::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Metis::construire_partition(), Partitionneur_Fichier_Decoupage::construire_partition(), OctreeRoot::construit(), Zone::construit_octree(), corriger(), Milieu_base::creer_alpha(), Turbulence_paroi_base::creer_champ(), Modele_turbulence_scal_base::creer_champ(), Mod_turb_hyd_base::creer_champ(), Navier_Stokes_std::creer_champ(), Convection_Diffusion_Temperature::creer_champ(), Pb_MED::creer_champ(), Equation_base::creer_champ(), Fluide_Dilatable_base::creer_champs_non_lus(), Milieu_base::creer_champs_non_lus(), Fluide_base::creer_nu(), Navier_Stokes_std::derivee_en_temps_inco(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), QDM_Multiphase::dimensionner_matrice_sans_mem(), Energie_Multiphase::dimensionner_matrice_sans_mem(), Probleme_base::discretisation(), Equation_base::discretisation(), Fluide_Ostwald::discretiser(), Fluide_base::discretiser(), Fluide_Dilatable_base::discretiser(), Milieu_base::discretiser(), Domaine_dis::discretiser(), Champ_Generique_Interpolation::discretiser_domaine(), Champ_Generique_Extraction::discretiser_domaine(), Schema_Comm::echange_messages(), Schema_Comm::echange_taille(), Schema_Comm::end_comm(), Fluide_base::energie_interne(), Fluide_base::enthalpie(), Champ_front_contact_VEF::equation(), Modele_turbulence_scal_base::equation(), Mod_turb_hyd_base::equation(), Assembleur_P_VEFPreP1B::equation(), MorEqn::equation(), Champ_front_calc::equation(), Champ_P1NC_implementation::filtrer_L2(), Probleme_base::finir(), Echange_impose_base::fixer_nb_valeurs_temporelles(), Fluide_base::fixer_type_rayo(), Masse_Multiphase::fluide(), Energie_Multiphase::fluide(), Convection_Diffusion_Temperature::fluide(), Convection_Diffusion_Fluide_Dilatable_base::fluide(), Simpler_Base::get_and_set_parametre_implicite(), Champ_Generique_Tparoi_VEF::get_champ(), Conduction::get_champ(), Modele_turbulence_scal_base::get_champ(), Mod_turb_hyd_base::get_champ(), Navier_Stokes_std::get_champ(), Convection_Diffusion_Temperature::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Divergence::get_champ(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Champ_Generique_Gradient::get_champ_without_evaluation(), Champ_Generique_Divergence::get_champ_without_evaluation(), Eval_Diff_VDF_var_aniso::get_diffusivite(), Eval_Diff_VDF_var::get_diffusivite(), Eval_Diff_VDF_const::get_diffusivite(), Sondes::get_from_cache(), Schema_Comm::get_group(), Conduction::get_noms_champs_postraitables(), Modele_turbulence_scal_base::get_noms_champs_postraitables(), Mod_turb_hyd_base::get_noms_champs_postraitables(), Navier_Stokes_std::get_noms_champs_postraitables(), Schema_Comm::get_recv_pe_list(), Champ_Generique_refChamp::get_ref_champ_base(), Champ_Generique_Interpolation::get_ref_domain(), Champ_Generique_Extraction::get_ref_domain(), Champ_Generique_Interpolation::get_ref_zone_dis_base(), Champ_Generique_Extraction::get_ref_zone_dis_base(), Schema_Comm::get_send_pe_list(), Champ_input_P0::getTemplate(), Equation_base::Gradient_conjugue_diff_impl(), Milieu_base::gravite(), Equation_base::has_champ_conserve(), Energie_Multiphase::has_champ_convecte(), Equation_base::has_champ_convecte(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Op_Diff_Turbulent_base::has_diffusivite_turbulente(), QDM_Multiphase::has_interface_blocs(), Masse_Multiphase::has_interface_blocs(), Energie_Multiphase::has_interface_blocs(), Zone_Cl_EF::imposer_symetrie(), Zone_Cl_EF::imposer_symetrie_matrice_secmem(), Zone_Cl_EF::imposer_symetrie_partiellement(), Op_Diff_VDF_base::impr(), Mod_turb_hyd_base::imprimer(), Postraitement::init(), Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Echange_impose_base::initialiser(), Fluide_base::initialiser(), Constituant::initialiser(), Neumann_sortie_libre::initialiser(), Fluide_Dilatable_base::initialiser(), Partitionneur_Tranche::initialiser(), Partitionneur_Sous_Zones::initialiser(), Partitionneur_Partition::initialiser(), Milieu_base::initialiser(), Milieu_composite::initTimeStep(), Equation_base::initTimeStep(), Interprete_bloc::Interprete_bloc(), Porosites::interpreter(), Interprete_bloc::interpreter_bloc(), Zone::invalide_octree(), Simple::iterer_eqn(), Champ_Fonc_Tabule::le_champ_tabule_discretise(), Equation_base::lire_cl(), Terme_Source_Acceleration::lire_data(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Modele_turbulence_scal_base::loi_paroi_non_nulle(), Fluide_base::longueur_rayo_is_discretised(), Op_Dift_VEF_base::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEF::mettre_a_jour(), Champ_front_contact_VEF::mettre_a_jour(), Champ_front_contact_fictif_VEF::mettre_a_jour(), Op_Dift_VDF_var_Face_Axi::mettre_a_jour(), Eval_Dift_VDF_var_Face::mettre_a_jour(), Eval_Dift_VDF_const_Face::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Sortie_libre_Gradient_Pression_impose::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Conduction::mettre_a_jour(), Milieu_composite::mettre_a_jour(), Terme_Source_Acceleration::mettre_a_jour(), Fluide_Ostwald::mettre_a_jour(), Fluide_base::mettre_a_jour(), Constituant::mettre_a_jour(), Navier_Stokes_std::mettre_a_jour(), Op_Moyenne::mettre_a_jour(), Milieu_base::mettre_a_jour(), Equation_base::mettre_a_jour(), Champ_Fonc_Morceaux::mettre_a_jour(), Fluide_Weakly_Compressible::mettre_a_jour_bis(), Milieu_composite::mettre_a_jour_tabs(), Navier_Stokes_std::milieu(), Zone_Cl_EF::modifie_gradient(), MorEqn::mon_equation_non_nul(), Operateur_Evanescence::op_non_nul(), Operateur_Grad::op_non_nul(), Operateur_Div::op_non_nul(), Operateur_Diff::op_non_nul(), Operateur_Conv::op_non_nul(), Champ_Fonc::operator=(), Postraitement::postraiter_champs(), prepare_precond(), Modele_turbulence_scal_base::preparer_calcul(), Mod_turb_hyd_base::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), Terme_Puissance_Thermique::preparer_source(), Solv_GCP::printOn(), Perte_Charge_Circulaire_VEF_P1NC::readOn(), QDM_Multiphase::readOn(), Masse_Multiphase::readOn(), Energie_Multiphase::readOn(), Modele_turbulence_scal_base::readOn(), Convection_Diffusion_Temperature::readOn(), Convection_Diffusion_Concentration::readOn(), Loi_Etat_GP_WC::readOn(), Navier_Stokes_WC::readOn(), Loi_Etat_rhoT_GP_QC::readOn(), Navier_Stokes_QC::readOn(), Convection_Diffusion_Fluide_Dilatable_base::readOn(), Perte_Charge_Circulaire_PolyMAC_Face::readOn(), Solveur_Lineaire_Std::readOn(), Schema_Implicite_Multi_TimeStep_base::readOn(), Schema_Euler_Implicite::readOn(), Solv_GCP::readOn(), Sous_Zone::readOn(), Partitionneur_Tranche::readOn(), Partitionneur_Sous_Zones::readOn(), Partitionneur_Partition::readOn(), Zone_Cl_dis_base::readOn(), Sondes_Int::readOn(), Sondes::readOn(), Sonde_Int::readOn(), Sonde::readOn(), Postraitement::readOn(), Champ_input_P0::readOn(), Champ_Fonc_Morceaux::readOn(), Perte_Charge_Circulaire_CoviMAC_Face::readOn(), Echange_impose_base::reculer(), Equation_base::reculer(), Schema_Comm::recv_buffer(), Solv_Optimal::reinit(), Solv_Gen::reinit(), Solv_GCP::reinit(), Zone_EF_axi::remplir_tableau_origine(), Zone_Cl_EF::remplir_type_elem_Cl(), Modele_turbulence_scal_base::reprendre(), Mod_turb_hyd_base::reprendre(), Navier_Stokes_std::reprendre(), Operateurs_Statistique_tps::reprendre(), Ch_front_Vortex::reprendre_vortex(), Solv_GCP::resoudre_(), Solv_GCP_NS::resoudre_systeme(), Modele_turbulence_scal_base::sauvegarder(), Mod_turb_hyd_base::sauvegarder(), Ch_front_Vortex::sauvegarder_vortex(), Navier_Stokes_std::sauver(), Probleme_base::sauver(), Probleme_base::schema_temps(), Equation_base::schema_temps(), Schema_Comm::send_buffer(), Sondes::set_noms_champs_postraitables(), Champ_Generique_refChamp::set_ref_champ(), Equation_base::set_residuals(), Echange_impose_base::set_temps_defaut(), Champ_input_P0::setValue(), Conduction::solide(), Solv_Gen::solve(), Solv_GCP::supporte_matrice_morse_sym(), Operateur_Diff::typer(), Eval_Turbulence::update_equivalent_distance(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_CoviMAC_base::update_nu_invh(), Fluide_Weakly_Compressible::use_pth_xyz(), Mod_turb_hyd_base::utiliser_loi_paroi(), Champ_P0_VEF::valeur_au_bord(), Champ_P0_VDF::valeur_au_bord(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), Echange_externe_impose::verifie_ch_init_nb_comp(), Neumann_sortie_libre::verifie_ch_init_nb_comp(), Neumann_paroi::verifie_ch_init_nb_comp(), Dirichlet::verifie_ch_init_nb_comp(), Fluide_Incompressible::verifier_coherence_champs(), Fluide_base::verifier_coherence_champs(), Fluide_Dilatable_base::verifier_coherence_champs(), VEF_discretisation::zone_Cl_dis(), PolyMAC_discretisation::zone_Cl_dis(), VEFPreP1B::zone_Cl_dis(), Champ_Inc_base::zone_Cl_dis(), EF_discretisation::zone_Cl_dis(), CoviMAC_discretisation::zone_Cl_dis(), Equation_base::zone_dis(), Domaine_dis::~Domaine_dis(), and Solv_Optimal::~Solv_Optimal().
{
  assert(get_O_U_Ptr_check() || 1);
  return (cle_ >= 0);
}
const O_U_Ptr & O_U_Ptr::operator= (const O_U_Ptr & ptr) [private]
Operateur copie.
Definition at line 89 of file O_U_Ptr.cpp.
{
  assert(0);
  return *this;
}
Sortie & O_U_Ptr::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Objet_U.
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Ref_Debog_Pb, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Deriv_, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Ref_Interprete, Ref_Interprete_bloc, Ref_, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Ref_Fluide_Dilatable_base, Deriv_EDO_Pression_th_base, EDO_Pression_th, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Ref_Marqueur_Lagrange_base, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Ref_Correlation_base, Deriv_Correlation_base, Correlation, Ref_Correlation, Ref_Saturation_base, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, Elem_VEF, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 35 of file O_U_Ptr.cpp.
References cle_, finl, and get_O_U_Ptr_check().
{
  get_O_U_Ptr_check();
  return os << cle_ << finl;
}
Entree & O_U_Ptr::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Objet_U.
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Ref_Debog_Pb, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Deriv_, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Ref_Interprete, Ref_Interprete_bloc, Ref_, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Ref_Fluide_Dilatable_base, Deriv_EDO_Pression_th_base, EDO_Pression_th, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Ref_Marqueur_Lagrange_base, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Ref_Correlation_base, Deriv_Correlation_base, Correlation, Ref_Correlation, Ref_Saturation_base, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, Elem_VEF, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 46 of file O_U_Ptr.cpp.
{
// Il y aurait deux choix pertinents:
// choix 1:
// is >> cle_ >> pointeur_;
// choix 2:
// is >> cle_;
// if (cle_ >= 0)
// pointeur_ = la_memoire().objet_u(cle_);
// else
// pointeur_ = 0;
// B.Mathieu (8/7/2004)
// Pour l'instant, ne fait rien : necessaire pour compatibilite
// avec le reste du code (exemple Op_Diff_negligeable::readOn)
  return is;
}
void O_U_Ptr::recopie (const Objet_U & obj) [protected]
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
Definition at line 228 of file O_U_Ptr.cpp.
References Objet_U::duplique(), Memoire::Instance(), Memoire::objet_u(), and set_O_U_Ptr().
{
  int cle = obj.duplique();
  Memoire& memoire = Memoire::Instance();
  Objet_U& objet = memoire.objet_u(cle);
  set_O_U_Ptr(& objet);
}
const O_U_Ptr & O_U_Ptr::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Ref_Debog_Pb, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Deriv_, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Ref_Interprete, Ref_Interprete_bloc, Ref_, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Ref_Fluide_Dilatable_base, Deriv_EDO_Pression_th_base, EDO_Pression_th, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Ref_Marqueur_Lagrange_base, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Ref_Correlation_base, Deriv_Correlation_base, Correlation, Ref_Correlation, Ref_Saturation_base, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, Elem_VEF, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 28 of file O_U_Ptr.cpp.
O_U_Ptr & O_U_Ptr::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Ref_Debog_Pb, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Deriv_, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Ref_Interprete, Ref_Interprete_bloc, Ref_, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Ref_Fluide_Dilatable_base, Deriv_EDO_Pression_th_base, EDO_Pression_th, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Ref_Marqueur_Lagrange_base, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Ref_Correlation_base, Deriv_Correlation_base, Correlation, Ref_Correlation, Ref_Saturation_base, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, Elem_VEF, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 28 of file O_U_Ptr.cpp.
void O_U_Ptr::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Deriv_Iterateur_Source_CoviMAC_base, Deriv_Elem_CoviMAC_base, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Deriv_Iterateur_Source_EF_base, Deriv_Elem_EF_base, Ref_Zone_Cl_EF, Ref_Zone_EF, Deriv_Champ_Generique_Statistiques_base, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Deriv_Assembleur_base, Deriv_Champ_base, Deriv_Champ_Don_base, Deriv_Champ_Fonc_base, Deriv_Champ_front_base, Deriv_Champ_Generique_base, Deriv_Champ_Inc_base, Deriv_Cond_lim_base, Ref_Debog_Pb, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Deriv_Equation_base, Deriv_Format_Post_base, Deriv_Parametre_equation_base, Deriv_Postraitement_base, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Deriv_Schema_Temps_base, Deriv_Solveur_Implicite_Base, Deriv_Solveur_Masse_base, Deriv_Source_base, Deriv_Sous_zone_dis_base, Deriv_Zone_Cl_dis_base, Deriv_Zone_dis_base, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Deriv_Interpolation_IBM_base, Deriv_Raccord_base, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Deriv_Precond_base, Deriv_SolvElem_base, Deriv_SolveurSys_base, Deriv_Operateur_Conv_base, Deriv_Operateur_Diff_base, Deriv_Operateur_Div_base, Deriv_Operateur_Grad_base, Deriv_Operateur_Statistique_tps_base, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Ref_Interprete, Ref_Interprete_bloc, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Deriv_Iterateur_PolyMAC_base, Deriv_Iterateur_Source_PolyMAC_base, Deriv_Elem_PolyMAC_base, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Deriv_EOS_Tools_base, Deriv_Loi_Etat_base, Ref_Fluide_Dilatable_base, Deriv_EDO_Pression_th_base, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Deriv_Modele_Permeabilite_base, Ref_Marqueur_Lagrange_base, Deriv_Traitement_particulier_NS_base, Deriv_Mod_turb_hyd_base, Deriv_Modele_turbulence_scal_base, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Deriv_Turbulence_paroi_base, Deriv_Turbulence_paroi_scal_base, Ref_Correlation_base, Deriv_Correlation_base, Ref_Correlation, Ref_Saturation_base, Deriv_Saturation_base, Deriv_Operateur_Evanescence_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Deriv_Traitement_particulier_Solide_base, Ref_Champ_Face, Ref_Champ_P0_VDF, Deriv_Iterateur_VDF_base, Deriv_Iterateur_Source_VDF_base, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Deriv_Iterateur_Source_VEF_base, Deriv_Elem_VEF_base, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 258 of file O_U_Ptr.cpp.
References check_O_U_Ptr_type(), cle_, get_O_U_Ptr_check(), Objet_U::get_object_id(), Objet_U::numero(), and ptr_object_id_.
Referenced by Deriv_::detach(), Deriv_::readOn(), recopie(), Ref_::reset(), and Deriv_::typer().
{
  if (ptr != 0)
    {
      cle_ = ptr->numero();
      ptr_object_id_ = ptr->get_object_id();
    }
  else
    {
      cle_ = -1;
      ptr_object_id_ = -1;
    }
// Il suffit de tester le type ici : si le type est bon ici
// et qu'ensuite l'object_id_ ne change pas, alors le
// type est toujours bon.
  assert(check_O_U_Ptr_type(ptr));
  assert(get_O_U_Ptr_check() == ptr);
}
Member Data Documentation
int O_U_Ptr::cle_ [private]
Definition at line 74 of file O_U_Ptr.h.
Referenced by change_num(), check_O_U_Ptr_type(), get_O_U_Ptr(), get_O_U_Ptr_check(), get_ptr_cle(), non_nul(), printOn(), set_O_U_Ptr(), and ~O_U_Ptr().
const Type_info O_U_Ptr::info_obj [static]
Reimplemented from Objet_U.
Reimplemented in Ref_Champ_Face_CoviMAC, Ref_Champ_P0_CoviMAC, Ref_Op_Diff_CoviMAC_base, Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Ref_Zone_Cl_CoviMAC, Ref_Zone_CoviMAC, Ref_Champ_P1_EF, Ref_Champ_Q1_EF, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Ref_Zone_Cl_EF, Ref_Zone_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Ref_Champ_Fonc_base, Ref_Champ_Generique_Moyenne, Ref_Champ_Generique_Statistiques_base, Ref_Champ_Uniforme, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Ref_Debog_Pb, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Ref_Discretisation_base, Ref_Sous_zones_dis, Ref_Zones_dis, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Ref_Champ_base, Ref_Champ_Don, Ref_Champ_Don_base, Ref_Champ_Fonc, Ref_Champ_front, Ref_Champ_front_base, Ref_Champ_Generique_base, Ref_Champ_Inc, Ref_Champ_Inc_base, Ref_Cond_lim_base, Ref_Domaine_dis, Ref_Equation_base, Ref_Field_base, Ref_Frontiere_dis_base, Ref_IntVect, Ref_Loi_Fermeture_base, Ref_Loi_horaire, Ref_Milieu_base, Ref_Operateur_base, Ref_Postraitement, Ref_Probleme_base, Ref_Probleme_Couple, Ref_Probleme_U, Ref_Schema_Temps_base, Ref_Source_base, Ref_Zone_Cl_dis, Ref_Zone_Cl_dis_base, Ref_Zone_dis, Ref_Zone_dis_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Ref_Domaine, Ref_Joint, Ref_Sous_Zone, Ref_Zone, Ref_Frontiere, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Ref_Matrice_Base, Ref_ArrOfDouble, Ref_ArrOfInt, Ref_DoubleTab, Ref_DoubleVect, Ref_IntTab, Ref_Table, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Ref_Integrale_tps_Champ, Ref_Op_Ecart_type, Ref_Op_Moyenne, Ref_Operateur_Statistique_tps_base, Deriv_, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Ref_Interprete, Ref_Interprete_bloc, Ref_, Ref_Comm_Group, Ref_Objet_U, Ref_Front_VF, Ref_Sous_zone_VF, Ref_Zone_VF, Ref_Champ_P1_isoP1Bulle, Ref_Zone_Cl_VEFP1B, Ref_Zone_VEF_PreP1b, Ref_Champ_Face_PolyMAC, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Ref_Zone_Cl_PolyMAC, Ref_Zone_PolyMAC, Ref_Chimie, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Ref_Fluide_Dilatable_base, Deriv_EDO_Pression_th_base, EDO_Pression_th, Ref_Espece, Ref_Fluide_Quasi_Compressible, Ref_Fluide_Weakly_Compressible, Ref_Convection_Diffusion_Concentration, Ref_Convection_Diffusion_std, Ref_Convection_Diffusion_Temperature, Ref_Navier_Stokes_std, Ref_Constituant, Ref_Fluide_base, Ref_Fluide_Incompressible, Ref_Fluide_Ostwald, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Ref_Marqueur_Lagrange_base, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Ref_Mod_turb_hyd_base, Ref_Modele_turbulence_scal_base, Ref_Turbulence_paroi, Ref_Turbulence_paroi_base, Ref_Turbulence_paroi_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Ref_Correlation_base, Deriv_Correlation_base, Correlation, Ref_Correlation, Ref_Saturation_base, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Ref_Pb_Multiphase, Ref_Conduction, Ref_Solide, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Ref_Champ_Face, Ref_Champ_P0_VDF, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Ref_Zone_Cl_VDF, Ref_Zone_VDF, Ref_Champ_front_contact_VEF, Ref_Champ_P0_VEF, Ref_Champ_P1NC, Ref_Champ_Q1NC, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, Elem_VEF, Ref_Zone_Cl_VEF, and Ref_Zone_VEF.
Definition at line 41 of file O_U_Ptr.h.
int O_U_Ptr::ptr_object_id_ [private]
Definition at line 78 of file O_U_Ptr.h.
Referenced by check_O_U_Ptr_type(), get_O_U_Ptr_check(), get_ptr_object_id(), and set_O_U_Ptr().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/O_U_Ptr.h
src/Kernel/Utilitaires/O_U_Ptr.cpp