TRUST: Ref_Zone_CoviMAC Class Reference
Ref_Zone_CoviMAC Class Reference
#include <Ref_Zone_CoviMAC.h>
Public Member Functions
~Ref_Zone_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Zone_CoviMAC ()
Ref_Zone_CoviMAC (const Zone_CoviMAC &)
Ref_Zone_CoviMAC (const Ref_Zone_CoviMAC &)
const Zone_CoviMAC & valeur () const
Zone_CoviMAC & valeur ()
const Zone_CoviMAC * operator-> () const
Zone_CoviMAC * operator-> ()
const Ref_Zone_CoviMAC & operator= (const Zone_CoviMAC &)
const Ref_Zone_CoviMAC & operator= (const Ref_Zone_CoviMAC &)
operator const Zone_CoviMAC & () const
operator Zone_CoviMAC & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Zone_CoviMAC & self_cast (Objet_U &)
static const Ref_Zone_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Zone_CoviMAC * pointeur_
Detailed Description
Definition at line 28 of file Ref_Zone_CoviMAC.h.
Constructor & Destructor Documentation
Ref_Zone_CoviMAC::~Ref_Zone_CoviMAC ()
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
Ref_Zone_CoviMAC::Ref_Zone_CoviMAC ()
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
Ref_Zone_CoviMAC::Ref_Zone_CoviMAC (const Zone_CoviMAC & t)
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
Ref_Zone_CoviMAC::Ref_Zone_CoviMAC (const Ref_Zone_CoviMAC & t)
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
Member Function Documentation
Objet_U * Ref_Zone_CoviMAC::cree_instance () [static]
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
int Ref_Zone_CoviMAC::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
const Type_info * Ref_Zone_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
const Type_info & Ref_Zone_CoviMAC::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
const Type_info * Ref_Zone_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
Ref_Zone_CoviMAC::operator const Zone_CoviMAC & () const
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
Ref_Zone_CoviMAC::operator Zone_CoviMAC & ()
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
const Zone_CoviMAC * Ref_Zone_CoviMAC::operator-> () const [inline]
Definition at line 28 of file Ref_Zone_CoviMAC.h.
Zone_CoviMAC * Ref_Zone_CoviMAC::operator-> () [inline]
Definition at line 28 of file Ref_Zone_CoviMAC.h.
const Ref_Zone_CoviMAC & Ref_Zone_CoviMAC::operator= (const Ref_Zone_CoviMAC & t)
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
const Ref_Zone_CoviMAC & Ref_Zone_CoviMAC::operator= (const Zone_CoviMAC & t)
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
Sortie & Ref_Zone_CoviMAC::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
Entree & Ref_Zone_CoviMAC::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
const Ref_Zone_CoviMAC & Ref_Zone_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
Ref_Zone_CoviMAC & Ref_Zone_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
void Ref_Zone_CoviMAC::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
unsigned Ref_Zone_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Zone_CoviMAC.cpp.
const Zone_CoviMAC & Ref_Zone_CoviMAC::valeur () const [inline]
Definition at line 28 of file Ref_Zone_CoviMAC.h.
Referenced by Op_Div_CoviMAC::ajouter(), Masse_CoviMAC_Elem::ajouter_blocs(), Travail_pression_CoviMAC::ajouter_blocs(), Masse_CoviMAC_Face::appliquer_impl(), Masse_CoviMAC_Elem::appliquer_impl(), Assembleur_P_CoviMAC::assembler_mat(), Op_Diff_CoviMAC_Face::calculer_dt_stab(), Op_Diff_CoviMAC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Elem::calculer_dt_stab(), Op_Grad_CoviMAC_Face::completer(), Op_Diff_CoviMAC_Face::completer(), Op_Diff_CoviMAC_Elem::completer(), Op_Diff_CoviMAC_base::completer(), Op_Conv_EF_Stab_CoviMAC_Face::completer(), Op_Div_CoviMAC::contribuer_a_avec(), Op_Div_CoviMAC::dimensionner(), QDM_Multiphase::dimensionner_blocs(), Op_Diff_CoviMAC_base::init_op_ext(), Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::mettre_a_jour(), Op_Conv_EF_Stab_CoviMAC_Elem::mettre_a_jour(), Champ_Fonc_Tabule_P0_CoviMAC::mettre_a_jour(), Assembleur_P_CoviMAC::modifier_solution(), Champ_Fonc_P0_CoviMAC::moyenne(), Op_Grad_CoviMAC_Face::mu_f(), Op_Conv_EF_Stab_CoviMAC_Elem::preparer_calcul(), Op_Diff_CoviMAC_base::update_nu_invh(), Champ_Fonc_P0_CoviMAC::valeur_au_bord(), Op_Div_CoviMAC::volumique(), Assembleur_P_CoviMAC::zone_dis_base(), and Champ_Fonc_P0_CoviMAC::zone_dis_base().
Zone_CoviMAC & Ref_Zone_CoviMAC::valeur () [inline]
Definition at line 28 of file Ref_Zone_CoviMAC.h.
Member Data Documentation
const Type_info Ref_Zone_CoviMAC::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Zone_CoviMAC.h.
Zone_CoviMAC* Ref_Zone_CoviMAC::pointeur_ [private]
Definition at line 28 of file Ref_Zone_CoviMAC.h.
The documentation for this class was generated from the following files:
src/CoviMAC/Zones/Ref_Zone_CoviMAC.h
src/CoviMAC/Zones/Ref_Zone_CoviMAC.cpp