TRUST: EcrFicPartageBin Class Reference
EcrFicPartageBin Class Reference
Ecriture dans un fichier partage
Cette classe derive de Ecr_Fic_Par, en utilisant une sortie en binaire.
Ce type de fichier est notamment utilise pour la creation d'un fichier de post-traitement unique.
#include <EcrFicPartageBin.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
EcrFicPartageBin ()
EcrFicPartageBin (const char *name, std::_Ios_Openmode mode=ios::out)
Public Member Functions inherited from EcrFicPartage
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
EcrFicPartage ()
EcrFicPartage (const char *name, std::_Ios_Openmode mode=ios::out)
Ouvre le fichier avec les parametres mode et prot donnes
Ces parametres sont les parametres de la methode open standard.
int ouvrir (const char *name, std::_Ios_Openmode mode=ios::out) override
Ouvre le fichier avec les parametres mode et prot donnes
Ces parametres sont les parametres de la methode open standard.
~EcrFicPartage () override
ferme le fichier
void close ()
Sortie & lockfile () override
Permet au processus appelant de bloquer en attente de la ressource commune a tous les processus qui est le fichier partage.
Si le processus appelant cette methode n'est pas le premier, il atend du processus precedent l'endroit ou il doit se positionner dans le fichier pour effectuer sa prochaine ecriture.
Cette methode est systematiquement appelee avant toute nouvelle ecriture dans le fichier.
Sortie & unlockfile () override
Permet de debloquer la ressource critique pour leprocessus suivant.
Le processus appelant, sauf si c'est le premier processus du groupe, envoie
sa position courante au precessus suivant dans le groupe. Cette methode est
a appeler apres chaque ecriture dans le fichier.
Sortie & syncfile () override
Provoque l'ecriture sur disque des donnees accumulees sur les differents processeurs
depuis le dernier appel a syncfile().
Les donnees sont ecrites dans l'ordre croissant des processeurs.
Cette fonction doit etre appelee le meme nombre de fois sur tous les processeurs !
Exemple:
processeur 0: processeur 1:
file << "pe0 : 1" << finl; file << "pe1 : 1" << finl;
file << "pe0 : 2" << finl; file << "pe1 : 2" << finl;
file.syncfile(); file.syncfile();
file << "pe0 : 3" << finl; file << "pe1 : 3" << finl;
file << "pe0 : 4" << finl;
file.syncfile(); file.syncfile();
file << "pe0 : end" << finl; // le processeur 1 n'ecrit pas de donnees
file.syncfile(); file.syncfile();
Contenu du fichier :
pe0 : 1
pe0 : 2
pe1 : 1
pe1 : 2
pe0 : 3
pe0 : 4
pe1 : 3
pe0 : end.
void precision (int) override
int get_precision () override
Sortie & flush () override
int set_bin (int bin) override
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
Sortie & operator<< (const char *ob) override
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
Sortie & operator<< (const Objet_U &ob) override
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
Sortie & operator<< (const std::string &ob) override
Sortie & operator<< (const Separateur &) override
Sortie & operator<< (const unsigned ob) override
Sortie & operator<< (const int ob) override
Sortie & operator<< (const float ob) override
Sortie & operator<< (const double ob) override
Sortie & operator<< (const long ob) override
int put (const unsigned *ob, int n, int pas) override
int put (const int *ob, int n, int pas) override
int put (const float *ob, int n, int pas) override
int put (const double *ob, int n, int pas) override
int put (const long *ob, int n, int pas) override
Public Member Functions inherited from SFichier
SFichier ()
~SFichier ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
SFichier (const char *name, std::_Ios_Openmode mode=ios::out)
Public Member Functions inherited from Sortie_Fichier_base
~Sortie_Fichier_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Sortie_Fichier_base ()
Sortie_Fichier_base (const Sortie_Fichier_base &)=default
Sortie_Fichier_base (const char *name, std::_Ios_Openmode mode=ios::out)
ofstream & get_ofstream ()
void close ()
void precision (int pre) override
virtual int get_precision ()
void setf (std::_Ios_Fmtflags code) override
bool is_open ()
virtual int ouvrir (const char *name, std::_Ios_Openmode mode=ios::out)
Sortie & flush () override
Force l'ecriture sur disque des donnees dans le tampon
Utilise l'implementation de la classe ofstream.
Public Member Functions inherited from Sortie
Sortie ()
Sortie (ostream &os)
Sortie (const Sortie &os)
Sortie & operator= (ostream &os)
Sortie & operator= (Sortie &os)
ostream & get_ostream ()
const ostream & get_ostream () const
void set_ostream (ostream *os)
void set_col_width (const int)
Sortie & operator<< (ostream &(*f)(ostream &))
Sortie & operator<< (Sortie &(*f)(Sortie &))
Sortie & operator<< (ios &(*f)(ios &))
virtual Sortie & flush ()
virtual Sortie & lockfile ()
virtual Sortie & unlockfile ()
virtual Sortie & syncfile ()
virtual void setf (std::_Ios_Fmtflags)
virtual void precision (int)
virtual Sortie & operator<< (const Separateur &)
virtual Sortie & operator<< (const Objet_U &ob)
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
virtual Sortie & operator<< (const int ob)
virtual Sortie & operator<< (const unsigned ob)
virtual Sortie & operator<< (const long ob)
virtual Sortie & operator<< (const float ob)
virtual Sortie & operator<< (const double ob)
virtual Sortie & operator<< (const char *ob)
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
virtual Sortie & operator<< (const std::string &str)
virtual int add_col (const double ob)
virtual int add_col (const char *ob)
virtual int put (const unsigned *ob, int n, int nb_colonnes=1)
virtual int put (const int *ob, int n, int nb_colonnes=1)
virtual int put (const float *ob, int n, int nb_colonnes=1)
virtual int put (const double *ob, int n, int nb_colonnes=1)
virtual int put (const long *ob, int n, int nb_colonnes=1)
virtual ~Sortie ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
int is_bin ()
bool has_ostream () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static EcrFicPartageBin & self_cast (Objet_U &)
static const EcrFicPartageBin & self_cast (const Objet_U &)
Static Public Member Functions inherited from EcrFicPartage
static Objet_U * cree_instance ()
static const Type_info * info ()
static EcrFicPartage & self_cast (Objet_U &)
static const EcrFicPartage & self_cast (const Objet_U &)
Static Public Member Functions inherited from SFichier
static Objet_U * cree_instance ()
static const Type_info * info ()
static SFichier & self_cast (Objet_U &)
static const SFichier & self_cast (const Objet_U &)
Static Public Member Functions inherited from Sortie_Fichier_base
static const Type_info * info ()
static Sortie_Fichier_base & self_cast (Objet_U &)
static const Sortie_Fichier_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from EcrFicPartage
static const Type_info info_obj
Static Public Attributes inherited from SFichier
static const Type_info info_obj
Static Public Attributes inherited from Sortie_Fichier_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from SFichier
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Sortie_Fichier_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from EcrFicPartage
Nom nom_fic_
Protected Attributes inherited from Sortie_Fichier_base
ofstream * ofstream_
Protected Attributes inherited from Sortie
int bin_
int col_width_
Detailed Description
Ecriture dans un fichier partage
Cette classe derive de Ecr_Fic_Par, en utilisant une sortie en binaire.
Ce type de fichier est notamment utilise pour la creation d'un fichier de post-traitement unique.
Definition at line 32 of file EcrFicPartageBin.h.
Constructor & Destructor Documentation
EcrFicPartageBin() [1/2]
EcrFicPartageBin::EcrFicPartageBin () inline
Definition at line 37 of file EcrFicPartageBin.h.
                    : EcrFicPartage()
  {
    set_bin(1);
  };
References EcrFicPartage::set_bin().
EcrFicPartageBin() [2/2]
EcrFicPartageBin::EcrFicPartageBin (const char * name, std::_Ios_Openmode mode = ios::out) inline
Definition at line 41 of file EcrFicPartageBin.h.
  {
    set_bin(1);
    ouvrir(name, mode);
  };
References EcrFicPartage::ouvrir(), and EcrFicPartage::set_bin().
Member Function Documentation
cree_instance()
Objet_U * EcrFicPartageBin::cree_instance () static
Definition at line 18 of file EcrFicPartageBin.cpp.
duplique()
int EcrFicPartageBin::duplique () const override virtual
Reimplemented from EcrFicPartage.
Definition at line 18 of file EcrFicPartageBin.cpp.
get_info()
const Type_info * EcrFicPartageBin::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from EcrFicPartage.
Definition at line 18 of file EcrFicPartageBin.cpp.
info()
const Type_info * EcrFicPartageBin::info () static
Definition at line 18 of file EcrFicPartageBin.cpp.
printOn()
Sortie & EcrFicPartageBin::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from EcrFicPartage.
Definition at line 25 of file EcrFicPartageBin.cpp.
{
  throw;
  return s;
}
readOn()
Entree & EcrFicPartageBin::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from EcrFicPartage.
Definition at line 19 of file EcrFicPartageBin.cpp.
{
  throw;
  return s;
}
self_cast() [1/2]
const EcrFicPartageBin & EcrFicPartageBin::self_cast (const Objet_U & r) static
Definition at line 18 of file EcrFicPartageBin.cpp.
self_cast() [2/2]
EcrFicPartageBin & EcrFicPartageBin::self_cast (Objet_U & r) static
Definition at line 18 of file EcrFicPartageBin.cpp.
taille_memoire()
unsigned EcrFicPartageBin::taille_memoire () const override virtual
Reimplemented from EcrFicPartage.
Definition at line 18 of file EcrFicPartageBin.cpp.
Member Data Documentation
info_obj
const Type_info EcrFicPartageBin::info_obj static
Definition at line 34 of file EcrFicPartageBin.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/EcrFicPartageBin.h
src/Kernel/Utilitaires/EcrFicPartageBin.cpp