TRUST: Sortie_libre_Gradient_Pression_impose_VEF Class Reference
Sortie_libre_Gradient_Pression_impose_VEF Class Reference
Sortie_libre_Gradient_Pression_impose_VEF
Cette classe derive de la classe Neumann_sortie_libre
Elle represente une frontiere ouverte avec condition
de gradient de pression impose.
L'objet de type Champ_front le_champ_front contient le gradient
impose. La fonction flux_impose() renvoie une valeur de pression
a l'exterieur calculee a partir du gradient de pression impose
et de la pression a l'interieur du domaine.
#include <Sortie_libre_Gradient_Pression_impose_VEF.h>
Public Member Functions
Sortie_libre_Gradient_Pression_impose_VEF ()
~Sortie_libre_Gradient_Pression_impose_VEF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual double flux_impose (int) const
Renvoie la valeur du flux impose sur la i-eme composante
du champ representant le flux a la frontiere.
virtual double flux_impose (int, int) const
Renvoie la valeur du flux impose sur la (i,j)-eme composante
du champ representant le flux a la frontiere.
int compatible_avec_eqn (const Equation_base &) const
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Neumann_sortie_libre sont compatibles
avec une equation dont le domaine est la Thermique, le Transport_Keps,
la Concentration, la Fraction_massique ou bien indetermine.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Sortie_libre_Gradient_Pression_impose_VEF & self_cast (Objet_U &)
static const
Sortie_libre_Gradient_Pression_impose_VEF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions
aux limites sont specifiees: "T_ext", "C_ext", "Y_ext", "K_Eps_ext" ou "F_M_ext"
Produit une erreur sinon.
Protected Attributes
Ref_Zone_VEF la_zone_VEF
Ref_Champ_P0_VEF pression_interne
DoubleVect trace_pression_int
pression interne sur les mailles de bord
DoubleVect coeff
Detailed Description
Sortie_libre_Gradient_Pression_impose_VEF
Cette classe derive de la classe Neumann_sortie_libre
Elle represente une frontiere ouverte avec condition
de gradient de pression impose.
L'objet de type Champ_front le_champ_front contient le gradient
impose. La fonction flux_impose() renvoie une valeur de pression
a l'exterieur calculee a partir du gradient de pression impose
et de la pression a l'interieur du domaine.
Definition at line 48 of file Sortie_libre_Gradient_Pression_impose_VEF.h.
Constructor & Destructor Documentation
Sortie_libre_Gradient_Pression_impose_VEF::Sortie_libre_Gradient_Pression_impose_VEF ()
Definition at line 32 of file Sortie_libre_Gradient_Pression_impose_VEF.cpp.
Sortie_libre_Gradient_Pression_impose_VEF::~Sortie_libre_Gradient_Pression_impose_VEF ()
Definition at line 32 of file Sortie_libre_Gradient_Pression_impose_VEF.cpp.
Member Function Documentation
int Sortie_libre_Gradient_Pression_impose_VEF::compatible_avec_eqn (const Equation_base & eqn) const [virtual]
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Neumann_sortie_libre sont compatibles
avec une equation dont le domaine est la Thermique, le Transport_Keps,
la Concentration, la Fraction_massique ou bien indetermine.
Returns:
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Reimplemented from Neumann_sortie_libre.
Definition at line 91 of file Sortie_libre_Gradient_Pression_impose_VEF.cpp.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Hydraulique="Hydraulique";
  Motcle indetermine="indetermine";
  if ( (dom_app==Hydraulique) || (dom_app==indetermine) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
Objet_U * Sortie_libre_Gradient_Pression_impose_VEF::cree_instance () [static]
Reimplemented from Neumann_sortie_libre.
Reimplemented in Sortie_libre_Gradient_Pression_impose_VEFPreP1B.
Definition at line 32 of file Sortie_libre_Gradient_Pression_impose_VEF.cpp.
int Sortie_libre_Gradient_Pression_impose_VEF::duplique () const [virtual]
Reimplemented from Neumann_sortie_libre.
Reimplemented in Sortie_libre_Gradient_Pression_impose_VEFPreP1B.
Definition at line 32 of file Sortie_libre_Gradient_Pression_impose_VEF.cpp.
double Sortie_libre_Gradient_Pression_impose_VEF::flux_impose (int i) const [virtual]
Renvoie la valeur du flux impose sur la i-eme composante
du champ representant le flux a la frontiere.
Returns:
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented from Neumann.
Definition at line 63 of file Sortie_libre_Gradient_Pression_impose_VEF.cpp.
References Cerr, coeff, Process::exit(), finl, Cond_lim_base::le_champ_front, DoubleVect::line_size(), DoubleVect::size(), trace_pression_int, and Champ_front::valeurs().
{
  if (le_champ_front.valeurs().size()==1)
    {
      double a1 = trace_pression_int[face];
      double a2 = coeff[face];
      double a3 = le_champ_front(0,0);
      double Pimp  = a1 + a2*a3;
      return Pimp ;
    }
  else if (le_champ_front.valeurs().line_size()==1)
    {
      return (trace_pression_int[face] + coeff[face]*le_champ_front(face,0));
    }
  else
    Cerr << "Sortie_libre_Gradient_Pression_impose_VEF::flux_impose erreur" << finl;
  exit();
  return 0.;
}
double Sortie_libre_Gradient_Pression_impose_VEF::flux_impose (int i, int j) const [virtual]
Renvoie la valeur du flux impose sur la (i,j)-eme composante
du champ representant le flux a la frontiere.
Returns:
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented from Neumann.
Definition at line 83 of file Sortie_libre_Gradient_Pression_impose_VEF.cpp.
References Cerr, and finl.
{
  Cerr << "Sortie_libre_Gradient_Pression_impose_VEF::flux_impose(int  , int )" << finl;
  Cerr << "On ne sait imposer que la composante normale du gradient" << finl;
  return 0.;
}
const Type_info * Sortie_libre_Gradient_Pression_impose_VEF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Neumann_sortie_libre.
Reimplemented in Sortie_libre_Gradient_Pression_impose_VEFPreP1B.
Definition at line 32 of file Sortie_libre_Gradient_Pression_impose_VEF.cpp.
const Type_info * Sortie_libre_Gradient_Pression_impose_VEF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Neumann_sortie_libre.
Reimplemented in Sortie_libre_Gradient_Pression_impose_VEFPreP1B.
Definition at line 32 of file Sortie_libre_Gradient_Pression_impose_VEF.cpp.
Sortie & Sortie_libre_Gradient_Pression_impose_VEF::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Neumann_sortie_libre.
Reimplemented in Sortie_libre_Gradient_Pression_impose_VEFPreP1B.
Definition at line 38 of file Sortie_libre_Gradient_Pression_impose_VEF.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Sortie_libre_Gradient_Pression_impose_VEF::readOn (Entree & s) [protected, virtual]
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions
aux limites sont specifiees: "T_ext", "C_ext", "Y_ext", "K_Eps_ext" ou "F_M_ext"
Produit une erreur sinon.
Returns:
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Neumann_sortie_libre.
Reimplemented in Sortie_libre_Gradient_Pression_impose_VEFPreP1B.
Definition at line 46 of file Sortie_libre_Gradient_Pression_impose_VEF.cpp.
References Objet_U::dimension, Neumann_sortie_libre::le_champ_ext, Cond_lim_base::le_champ_front, DoubleTab::resize(), Deriv_::typer(), and Champ_front::valeurs().
{
  s >> le_champ_front;
  le_champ_ext.typer("Champ_front_uniforme");
  le_champ_ext.valeurs().resize(1,dimension);
  return s;
}
const Sortie_libre_Gradient_Pression_impose_VEF & Sortie_libre_Gradient_Pression_impose_VEF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Neumann_sortie_libre.
Reimplemented in Sortie_libre_Gradient_Pression_impose_VEFPreP1B.
Definition at line 32 of file Sortie_libre_Gradient_Pression_impose_VEF.cpp.
Sortie_libre_Gradient_Pression_impose_VEF & Sortie_libre_Gradient_Pression_impose_VEF::self_cast (Objet_U & r) [static]
Reimplemented from Neumann_sortie_libre.
Reimplemented in Sortie_libre_Gradient_Pression_impose_VEFPreP1B.
Definition at line 32 of file Sortie_libre_Gradient_Pression_impose_VEF.cpp.
unsigned Sortie_libre_Gradient_Pression_impose_VEF::taille_memoire () const [virtual]
Reimplemented from Neumann_sortie_libre.
Reimplemented in Sortie_libre_Gradient_Pression_impose_VEFPreP1B.
Definition at line 32 of file Sortie_libre_Gradient_Pression_impose_VEF.cpp.
Member Data Documentation
DoubleVect Sortie_libre_Gradient_Pression_impose_VEF::coeff [protected]
Definition at line 64 of file Sortie_libre_Gradient_Pression_impose_VEF.h.
Referenced by flux_impose(), and Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser().
const Type_info Sortie_libre_Gradient_Pression_impose_VEF::info_obj [static]
Reimplemented from Neumann_sortie_libre.
Reimplemented in Sortie_libre_Gradient_Pression_impose_VEFPreP1B.
Definition at line 51 of file Sortie_libre_Gradient_Pression_impose_VEF.h.
Ref_Zone_VEF Sortie_libre_Gradient_Pression_impose_VEF::la_zone_VEF [protected]
Definition at line 61 of file Sortie_libre_Gradient_Pression_impose_VEF.h.
Ref_Champ_P0_VEF Sortie_libre_Gradient_Pression_impose_VEF::pression_interne [protected]
Reimplemented in Sortie_libre_Gradient_Pression_impose_VEFPreP1B.
Definition at line 62 of file Sortie_libre_Gradient_Pression_impose_VEF.h.
DoubleVect Sortie_libre_Gradient_Pression_impose_VEF::trace_pression_int [protected]
pression interne sur les mailles de bord
Definition at line 63 of file Sortie_libre_Gradient_Pression_impose_VEF.h.
Referenced by Sortie_libre_Gradient_Pression_impose_VEFPreP1B::calculer_trace_pression(), flux_impose(), and Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser().
The documentation for this class was generated from the following files:
src/VEF/Cond_Lim/Sortie_libre_Gradient_Pression_impose_VEF.h
src/VEF/Cond_Lim/Sortie_libre_Gradient_Pression_impose_VEF.cpp