TRUST: ArrOfDouble Class Reference
ArrOfDouble Class Reference
Represente un tableau d'elements de type double.
L'etat du tableau est caracterise par la valeur de p_ et de data_ :
* detache : on a alors p_==0, data_==0, size_array_==0
(etat obtenu par le constructeur par defaut, detach_array()
et resize_array(0) dans certains cas)
* normal : alors p pointe vers une structure Vdbldata, data_==p->data_
et size_array_ <= p->size_. A la destruction du tableau, si
p->ref_count_ est nul on libere la memoire.
data_ n'est pas nul.
L'espace memoire du tableau peut etre partage entre plusieurs
ArrOfDouble (le pointeur "p" pointe alors sur une meme structure).
Ce type de tableau est produit par ref_array().
Le dernier ArrOfDouble a utiliser une zone de memoire
la detruit lorsqu'il a fini (voir detach_array())
Si smart_resize_==0, alors on a toujours size_array_==p->size_.
* ref_data : p_==0, data_ pointe vers un tableau existant, la memoire
n'est pas liberee a la destruction du ArrOfDouble.
Ces tableaux sont obtenus par appel a ref_data(...) et peuvent servir
pour importer un tableau fourni par une routine exterieure (C ou fortran)
Valeur initiale par defaut : voir "fill_default_value".
Priere de supposer desormais que les tableaux ne sont pas initialises
par defaut.
#include <ArrOfDouble.h>
Public Types
enum Storage { STANDARD, TEMP_STORAGE }
Public Member Functions
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
~ArrOfDouble ()
Destructeur : appelle detach_array()
ArrOfDouble ()
Constructeur par defaut: cree un tableau "detache",
soit p_==0, data_==0, size_array_==0, smart_resize_==0.
ArrOfDouble (int size)
Cree un tableau de taille n avec allocation standard (voir set_mem_storage).
Le tableau est rempli avec zero par defaut. Pour creer un tableau non initialise, utiliser:
ArrOfDouble toto;
toto.resize_array(n, NOCOPY_NOINIT);
Parametre: int n
Signification: taille du tableau.
ArrOfDouble (const ArrOfDouble &)
Constructeur par copie. On alloue une nouvelle zone de memoire
et on copie le contenu du tableau (il s'agit d'un "deep copy").
L'attribut smart_resize_ est copie aussi.
Si le tableau A est de taille nulle, on cree un tableau "detache",
sinon on cree un tableau "normal".
Parametre: const ArrOfDouble& A
Signification: le tableau a copier.
void resize_array (int new_size, Array_base::Resize_Options opt=COPY_INIT)
void resize (int new_size, Array_base::Resize_Options opt=COPY_INIT)
appel a ArrOfDouble::resize_array()
virtual void resize_tab (int n, Array_base::Resize_Options opt=COPY_INIT)
methode virtuelle identique a resize_array(), permet de traiter
de facon generique les ArrOf, Vect et Tab.
Si l'objet est de type ArrOfDouble, appel a resize_array(n)
Prerequis: le tableau doit etre "resizable" (voir resize_array()).
S'il est d'un type derive (Vect ou Tab), il ne doit pas avoir de descripteur
parallele si la taille est effectivement modifiee.
void set_smart_resize (int flag)
Change le mode l'allocation memoire: reallocation d'un tableau
a chaque changement de taille (flag = 0) ou reallocation
uniquement si la taille augmente et par doublement de la taille
du tableau (flag = 1).
void set_mem_storage (const Storage storage)
Change le mode d'allocation memoire lors des resize<br>(voir VDoubledata et Double_ptr_trav)
Exemple pour creer un tableau avec allocation temporaire:
DoubleTab tab; // Creation d'un tableau vide
tab.set_mem_storage(TEMP_STORAGE); // Changement de mode d'allocation
tab.resize(n); // Allocation memoire.
Storage get_mem_storage () const
Renvoie le mode d'allocation du tableau (qui sera utilise
lors du prochain resize si changement de taille).
(voir VDoubledata et Double_ptr_trav)
virtual void ref_data (double *ptr, int size)
Fait pointer le tableau vers la zone de memoire "data_".
On detache la zone de memoire existante. Le tableau devient
de type "ref_data". Attention : ptr doit etre non nul.
La taille est initialisee avec size.
Attention: methode virtuelle: dans les classes derivee, cette methode
initialise les structures pour creer un tableau sequentiel.
Pour faire une ref sur un tableau parallele utiliser DoubleVect::ref()
Parametre: double*
Signification: le tableau a recuperer. Si pointeur nul alors size
doit etre nulle aussi et le tableau reste detache
Parametre: int size
Signification: le nombre d'elements du tableau.
virtual void ref_array (ArrOfDouble &, int start=0, int sz=-1)
Fait pointer le tableau vers les memes donnees qu'un tableau
existant. Le tableau sera du meme type que le tableau m ("detache",
"normal"). Le tableau m ne doit pas etre de type "ref_data"
Attention, le tableau source et *this sont ensuite figes (resize_array()
interdit).
Attention: methode virtuelle: dans les classes derivee, cette methode
initialise les structures pour creer un tableau sequentiel.
Parametre: const ArrOfDouble& m
Signification: le tableau a referencer (pas de type "ref_data"
et different de *this !!!)
ArrOfDouble & operator= (const ArrOfDouble &)
Copie les donnees du tableau m.
Si "m" n'a pas la meme taille que "*this", on fait un resize_array.
Ensuite, on copie les valeurs de "m" dans "*this".
Le type de tableau (methode d'allocation) n'est pas copie.
virtual void reset ()
Remet le tableau dans l'etat obtenu avec le constructeur par defaut
(libere la memoire mais conserve le mode d'allocation memoire actuel)
ArrOfDouble & operator= (double valeur)
x est affecte a toutes les cases
double & operator[] (int i)
operateur [] retourne le ieme element du tableau
const double & operator[] (int i) const
operateur [] retourne le ieme element du tableau
double & operator() (int i)
idem operator[]
const double & operator() (int i) const
const double * addr () const
Renvoie un pointeur sur le premier element du tableau.
Le pointeur est nul si le tableau est "detache".
Attention, l'adresse peut changer apres un appel
a resize_array(), ref_data, ref_array, ...
double * addr ()
Renvoie un pointeur sur le premier element du tableau.
Le pointeur est nul si le tableau est "detache".
int size_array () const
Renvoie la taille du tableau (nombre d'elements declares
a la construction ou a resize_array()).
C'est le nombre d'elements accessibles a operator[].
int ref_count () const
Retourne le nombre de references des donnees du tableau
si le tableau est "normal", -1 s'il est "detache" ou "ref_data".
void append_array (double valeur)
Ajoute une case en fin de tableau et y stocke la "valeur".
ArrOfDouble & operator+= (const ArrOfDouble &)
Addition case a case sur toutes les cases du tableau.
ArrOfDouble & operator+= (const double)
ajoute la meme valeur a toutes les cases du tableau
ArrOfDouble & operator-= (const ArrOfDouble &)
Soustraction case a case sur toutes les cases du tableau
Parametre: const ArrOfDouble& y
Signification: tableau de meme taille que *this.
ArrOfDouble & operator-= (const double)
soustrait la meme valeur a toutes les cases
ArrOfDouble & inject_array (const ArrOfDouble &source, int nb_elements=-1, int first_element_dest=0, int first_element_source=0)
Copie les elements source[first_element_source + i]
dans les elements (*this)[first_element_dest + i] pour 0 <= i < nb_elements
Les autres elements de (*this) sont inchanges.
ArrOfDouble & copy_array (const ArrOfDouble &)
appelle operator=(a)
ArrOfDouble & operator= (const FArrOfDouble &)
ArrOfDouble & operator*= (const double)
muliplie toutes les cases par dy
ArrOfDouble & operator/= (const double)
divise toutes les cases par dy
void ordonne_array ()
Tri des valeurs du tableau dans l'ordre croissant.
La fonction utilisee est qsort de stdlib (elle est en n*log(n)).
void array_trier_retirer_doublons ()
Tri des valeurs du tableau dans l'ordre croissant et suppresion des doublons
La fonction utilisee est qsort de stdlib (elle est en n*log(n)).
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static ArrOfDouble & self_cast (Objet_U &)
static const ArrOfDouble & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture du tableau sur "os" :
ecrit le nombre d'elements suivi des valeurs du tableau.
virtual Entree & readOn (Entree &)
Lecture d'un tableau dans un flot d'entree
Lit le nombre d'elements suivi des elements eux-memes.
void attach_array (const ArrOfDouble &a, int start=0, int size=-1)
Amene le tableau dans l'etat "normal", "detache" ou "ref_array"
en associant une sous-zone de memoire du tableau m, definie par start et size
Si size < 0, on prend le tableau m jusqu'a la fin.
int detach_array ()
Amene le tableau dans l'etat "detache". C'est a dire:
Si le tableau est "detache" :
* ne rien faire
Si le tableau est "normal" :
* decremente le nombre de references a *p
* detruit *p si p->ref_count==0
* annule p_, data_ et size_array_
Si le tableau est "ref_data" :
* annule data_ et size_array_.
void fill_default_value (Array_base::Resize_Options opt, int first, int nb)
Remplit "nb" cases consecutives du tableau a partir de la case "first"
avec une valeur par defaut.
Cette fonction est appelee lors d'un resize pour initialiser les
cases nouvellement creees.
Le comportement depend actuellement du type de tableau :
* Tableau de type "smart_resize":
* en mode debug (macro NDEBUG non definie) le tableau est initialise
avec une valeur invalide.
* en optimise, le tableau n'est pas initialise
* Tableau normal :
Le tableau est initialise avec la valeur 0. Ce comportement est choisi
pour des raisons de compatibilite avec l'implementation precedente.
Cette specification pourrait etre modifiee prochainement pour des raisons
de performances (pour ne pas avoir a initialiser inutilement les tableaux).
DONC: il faut supposer desormais que les nouvelles cases ne sont pas
initialisees lors d'un resize.
Parametre: first
Signification: premiere case a initialiser.
Contrainte: (nb==0) ou (0 <= first < memory_size_)
Parametre: nb
Signification: nombre de cases a initialiser.
Contrainte: (nb==0) ou (0 < nb <= memory_size_ - first)
void resize_array_ (int n, Array_base::Resize_Options opt=COPY_INIT)
methode protegee de changement de taille, appelable par
les classes derivees (idem que resize_array() mais sans condition sur le
type derive de l'objet)
Private Member Functions
void memory_resize (int new_size, Array_base::Resize_Options opt=COPY_INIT)
Si besoin, alloue une nouvelle zone de memoire,
copie les donnees et efface l'ancienne zone de memoire.
Attention, on suppose que cette methode est appelee par
resize_array().
Attention: si ref_count_>1, l'appel a resize_array() est
autorise uniquement si la nouvelle taille est identique
a la precedente (auquel cas on ne fait rien)
Si ref_count_ == 1, l'appel est invalide si p_->data_ est
different de data_ (le tableau a ete construit avec ref_array()
avec start > 0)
Private Attributes
VDoubledata * p_
double * data_
int size_array_
int memory_size_
int smart_resize_
Storage storage_type_
Detailed Description
Represente un tableau d'elements de type double.
L'etat du tableau est caracterise par la valeur de p_ et de data_ :
* detache : on a alors p_==0, data_==0, size_array_==0
(etat obtenu par le constructeur par defaut, detach_array()
et resize_array(0) dans certains cas)
* normal : alors p pointe vers une structure Vdbldata, data_==p->data_
et size_array_ <= p->size_. A la destruction du tableau, si
p->ref_count_ est nul on libere la memoire.
data_ n'est pas nul.
L'espace memoire du tableau peut etre partage entre plusieurs
ArrOfDouble (le pointeur "p" pointe alors sur une meme structure).
Ce type de tableau est produit par ref_array().
Le dernier ArrOfDouble a utiliser une zone de memoire
la detruit lorsqu'il a fini (voir detach_array())
Si smart_resize_==0, alors on a toujours size_array_==p->size_.
* ref_data : p_==0, data_ pointe vers un tableau existant, la memoire
n'est pas liberee a la destruction du ArrOfDouble.
Ces tableaux sont obtenus par appel a ref_data(...) et peuvent servir
pour importer un tableau fourni par une routine exterieure (C ou fortran)
Valeur initiale par defaut : voir "fill_default_value".
Priere de supposer desormais que les tableaux ne sont pas initialises
par defaut.
Definition at line 71 of file ArrOfDouble.h.
Member Enumeration Documentation
enum ArrOfDouble::Storage
Enumerator:
STANDARD
TEMP_STORAGE
Definition at line 101 of file ArrOfDouble.h.
{ STANDARD, TEMP_STORAGE };
Constructor & Destructor Documentation
ArrOfDouble::~ArrOfDouble ()
Destructeur : appelle detach_array()
< Paranoia: si size_array_==-1, c'est un zombie
Definition at line 316 of file ArrOfDouble.cpp.
References detach_array(), and size_array_.
{
  detach_array();
  size_array_ = -1; //!< Paranoia: si size_array_==-1, c'est un zombie
}
ArrOfDouble::ArrOfDouble ()
Constructeur par defaut: cree un tableau "detache",
soit p_==0, data_==0, size_array_==0, smart_resize_==0.
Definition at line 325 of file ArrOfDouble.cpp.
                         :
  p_(0),
  data_(0),
  size_array_(0),
  memory_size_(0),
  smart_resize_(0),
  storage_type_(STANDARD)
{
}
ArrOfDouble::ArrOfDouble (int size)
Cree un tableau de taille n avec allocation standard (voir set_mem_storage).
Le tableau est rempli avec zero par defaut. Pour creer un tableau non initialise, utiliser:
ArrOfDouble toto;
toto.resize_array(n, NOCOPY_NOINIT);
Parametre: int n
Signification: taille du tableau.
Definition at line 342 of file ArrOfDouble.cpp.
References Array_base::COPY_INIT, data_, fill_default_value(), VDoubledata::get_data(), p_, and STANDARD.
                              :
  p_(0),
  data_(0),
  size_array_(n),
  memory_size_(n),
  smart_resize_(0),
  storage_type_(STANDARD)
{
  if (n)
    {
      p_ = new VDoubledata(n, STANDARD);
      data_ = p_->get_data();
      fill_default_value(COPY_INIT, 0, n);
    }
}
ArrOfDouble::ArrOfDouble (const ArrOfDouble & A)
Constructeur par copie. On alloue une nouvelle zone de memoire
et on copie le contenu du tableau (il s'agit d'un "deep copy").
L'attribut smart_resize_ est copie aussi.
Si le tableau A est de taille nulle, on cree un tableau "detache",
sinon on cree un tableau "normal".
Parametre: const ArrOfDouble& A
Signification: le tableau a copier.
Definition at line 390 of file ArrOfDouble.cpp.
References data_, VDoubledata::get_data(), inject_array(), memory_size_, p_, size_array(), size_array_, smart_resize_, STANDARD, and storage_type_.
                                            : Array_base()
{
  const int size = A.size_array();
  if (size > 0)
    {
// Creation d'un tableau "normal"
      storage_type_ = STANDARD;
      p_ = new VDoubledata(size, STANDARD);
      data_ = p_->get_data();
      size_array_ = size;
      memory_size_ = size;
      smart_resize_ = A.smart_resize_;
      inject_array(A);
    }
  else
    {
// Creation d'un tableau "detache"
      p_ = 0;
      data_ = 0;
      size_array_ = 0;
      memory_size_ = 0;
      smart_resize_ = 0;
      storage_type_ = STANDARD;
    }
}
Member Function Documentation
const double * ArrOfDouble::addr () const [inline]
Renvoie un pointeur sur le premier element du tableau.
Le pointeur est nul si le tableau est "detache".
Attention, l'adresse peut changer apres un appel
a resize_array(), ref_data, ref_array, ...
Returns:
const double*
Signification: pointeur sur le premier element du tableau
Definition at line 379 of file ArrOfDouble.h.
References data_.
Referenced by add_to_vect_blocs(), add_to_vect_items(), affecte_double_avec_doubletab(), ajoute_alpha_v(), ajoute_alpha_v_norme(), ajoute_carre(), ajoute_produit_scalaire(), Terme_Source_Decroissance_Radioactive_VEF_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::ajouter(), T_It_VDF_Elem< _TYPE_ >::ajouter(), Terme_Boussinesq_PolyMAC_Face::ajouter(), Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::ajouter_masse_dt_local(), Matrice_SuperMorse::ajouter_mult_vect_et_prodscal(), Matrice_Morse_Sym::ajouter_multvect_(), Matrice_Morse::ajouter_multvect_(), Matrice_Diagonale::ajouter_multvect_(), Matrice_Bloc_Sym::ajouter_multvect_(), Matrice_Bloc::ajouter_multvect_(), Matrice_Bloc::ajouter_multvectT_(), Op_Diff_EF::ajouter_scalaire_dim2_nbn_4(), Op_Diff_EF::ajouter_scalaire_dim3_nbn_8(), Op_Diff_EF::ajouter_scalaire_gen(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim2(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim2(), Op_Diff_EF::ajouter_vectoriel_dim2_nbn_4(), Op_Diff_EF::ajouter_vectoriel_dim3_nbn_8(), Op_Diff_EF::ajouter_vectoriel_gen(), DoubleTab::append_line(), Fluide_base::calculer_nu(), carre(), Solv_Cholesky::Cholesky(), interface_INITGAUSS::Compute(), interface_CALCULSI::Compute(), interface_CALCULBIJ::Compute(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::contribuer_a_avec(), Solveur_Masse_base::corriger_solution(), descente(), descente_assert(), descente_assert_precond_diag(), descente_bloc_extradiag_assert(), descente_diag_ok_assert(), descente_precond_diag(), Matrice_Morse::diagmulmat(), disp_da(), disp_dt(), disp_m(), dotproduct_array(), MD_Vector_tools::dump_vector_with_md(), Debog_Pb::ecrire_partie(), ecrit(), envoyer_all_to_all(), Solv_Cholesky::Fact_Cholesky(), ILU::factoriser(), Champ_P1iP1B_implementation::filtrage(), Champ_Generique_Transformation::get_champ(), Solveur_Masse_base::get_masse_divide_by_local_dt(), Solveur_Masse_base::get_masse_dt_local(), ILU::ilu(), ILU::ilut(), Echange_contact_CoviMAC::init_fe_dist(), Champ_implementation_P1::init_from_file(), Zone_PolyMAC::init_m2(), inject_array(), Champ_Face_PolyMAC::interp_gve(), Integrer_champ_med::interpreter(), Lire_Ideas::interpreter_(), invalidate_data(), Matrice_Morse::inverse(), Matrice_Dense::inverse(), SolvElem_Gmres::iteration(), SolvElem_BiCGStab::iteration(), kersol(), lire_special(), DoubleVect::lit(), local_carre_norme_vect(), local_imax_vect(), local_imin_vect(), local_max_abs_vect(), local_max_vect(), local_min_abs_vect(), local_min_vect(), local_prodscal(), local_somme_vect(), DoubleTab::max_du_u(), max_to_vect_items(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::mettre_a_jour(), Chimie::mettre_a_jour(), Champ_Fonc_Fonction_txyz_Morceaux::mettre_a_jour(), mincol1_to_vect_items(), mp_collective_op(), multiply_sub(), Matrice_Morse_Sym::multvect_et_prodscal(), operation01(), operation11(), operator+(), operator==(), operator_abs(), operator_add(), operator_divide(), operator_egal(), operator_inverse(), operator_multiply(), operator_negate(), operator_sub(), Solv_GCP::prepare_data(), DoubleTab::printOn(), racine_carree(), read_from_vect_blocs(), read_from_vect_items(), remontee(), remontee_assert(), remontee_assert_precond_diag(), remontee_bloc_extradiag_assert(), remontee_diag_ok_assert(), remontee_precond_diag(), Matrice_Morse::remplir(), Matrice_Bloc::remplir(), Matrice_Morse_Sym::renumerote(), Solv_Petsc::resoudre_systeme(), MD_Vector_tools::restore_vector_with_md(), sameDoubleTab(), Champ_Input_Proto::setValueOnTab(), tab_divide_any_shape_(), tab_multiply_any_shape_(), Raccord_distant_homogene::trace_face_distant(), Frontiere::trace_face_local(), traite_diagonale(), Op_Diff_CoviMAC_base::update_nu_invh(), Champ_Face_CoviMAC::valeur_aux_elems_compo(), Vecteur3::Vecteur3(), Debog_Pb::verifier_partie_std(), Format_Post_Lata::write_doubletab(), write_to_vect_blocs(), write_to_vect_items(), and Zone_VF::xv_bord().
{
  return data_;
}
double * ArrOfDouble::addr () [inline]
Renvoie un pointeur sur le premier element du tableau.
Le pointeur est nul si le tableau est "detache".
Returns:
const double*
Signification: la zone memoire du tableau
Definition at line 390 of file ArrOfDouble.h.
References data_.
{
  return data_;
}
void ArrOfDouble::append_array (double valeur) [inline]
Ajoute une case en fin de tableau et y stocke la "valeur".
Definition at line 363 of file ArrOfDouble.h.
References Array_base::COPY_NOINIT, data_, resize_array(), size_array_, smart_resize_, and valeur().
Referenced by CSR_Builder::add_coeff(), and Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients().
{
  assert(smart_resize_);
  const int n = size_array_;
  resize_array(size_array_+1, COPY_NOINIT);
  data_[n] = valeur;
}
void ArrOfDouble::array_trier_retirer_doublons ()
Tri des valeurs du tableau dans l'ordre croissant et suppresion des doublons
La fonction utilisee est qsort de stdlib (elle est en n*log(n)).
Definition at line 923 of file ArrOfDouble.cpp.
References data_, ordonne_array(), resize_array(), and size_array_.
Referenced by ExtrudeParoi::interpreter_().
{
  const int size_ = size_array_;
  if (size_ <= 0)
    return;
// Tri dans l'ordre croissant
  ordonne_array();
// Retire les doublons (codage optimise en pointeurs)
  double last_value = *data_;
  double *src = data_ + 1;
  double *dest = data_ + 1;
  for (int i = size_ - 1; i != 0; i--)
    {
      double x = *(src++);
      if (x != last_value)
        {
          *(dest++) = x;
          last_value = x;
        }
    }
  int new_size_ = dest - data_;
  resize_array(new_size_);
}
void ArrOfDouble::attach_array (const ArrOfDouble & a, int start = 0, int size = -1) [protected]
Amene le tableau dans l'etat "normal", "detache" ou "ref_array"
en associant une sous-zone de memoire du tableau m, definie par start et size
Si size < 0, on prend le tableau m jusqu'a la fin.
Definition at line 1054 of file ArrOfDouble.cpp.
References VDoubledata::add_one_ref(), data_, memory_size_, p_, size_array(), size_array_, and smart_resize_.
Referenced by DoubleVect::ref(), and ref_array().
{
// Le tableau doit etre detache
  assert(data_ == 0 && p_ == 0);
// Le tableau doit etre different de *this
  assert(&m != this);
  if (size < 0)
    size = m.size_array_ - start;
  assert(start >= 0 && size >=0 && start + size <= m.size_array_);
  if (m.size_array() > 0)
    {
      p_ = m.p_;
      if (p_)
        p_->add_one_ref();
      data_ = m.data_ + start;
      size_array_ = size;
      memory_size_ = m.memory_size_ - start;
      smart_resize_ = m.smart_resize_;
    }
  else
    {
// Cas particulier ou on attache un tableau de taille nulle:
// en theorie, c'est pareil qu'un tableau de taille non nulle, MAIS
// dans les operateurs (ex:Op_Dift_VDF_Face_Axi), une ref est construite
// avant que le tableau ne prenne sa taille definitive. Donc, pour ne pas
// empecher le resize, il ne faut pas attacher le tableau s'il n'a pas
// encore la bonne taille. Solution propre: reecrire les operateurs pour
// qu'ils ne prennent pas une ref avant que le tableau ne soit valide
// et faire p_ = m.p_ dans tous les cas.
// Process::Journal() << "Warning ArrOfDouble::attach_array(m), m.size_array()==0, on n attache pas le tableau" << finl;
    }
}
ArrOfDouble & ArrOfDouble::copy_array (const ArrOfDouble & a)
appelle operator=(a)
Definition at line 500 of file ArrOfDouble.cpp.
References operator=().
Referenced by Champ_front_contact_VEF::calcul_grads_transf().
{
  operator=(a);
  return *this;
}
Objet_U * ArrOfDouble::cree_instance () [static]
Reimplemented in DoubleTab, DoubleTrav, and DoubleVect.
Definition at line 37 of file ArrOfDouble.cpp.
{
int ArrOfDouble::detach_array () [protected]
Amene le tableau dans l'etat "detache". C'est a dire:
Si le tableau est "detache" :
* ne rien faire
Si le tableau est "normal" :
* decremente le nombre de references a *p
* detruit *p si p->ref_count==0
* annule p_, data_ et size_array_
Si le tableau est "ref_data" :
* annule data_ et size_array_.
Returns:
int
Signification: 1 si les donnees du tableau ont ete supprimees
Definition at line 1014 of file ArrOfDouble.cpp.
References data_, memory_size_, p_, size_array_, and VDoubledata::suppr_one_ref().
Referenced by memory_resize(), DoubleVect::ref(), ref_array(), ref_data(), reset(), and ~ArrOfDouble().
{
  int retour = 0;
  if (p_)
    {
// Le tableau est de type "normal"
// Si la zone de memoire n'est plus utilisee par personne,
// on la detruit.
      if ((p_->suppr_one_ref()) == 0)
        {
          delete p_;
          retour = 1;
        }
      p_ = 0;
    }
  data_ = 0;
  size_array_ = 0;
  memory_size_ = 0;
  return retour;
}
int ArrOfDouble::duplique () const [virtual]
Implements Array_base.
Reimplemented in DoubleTab, DoubleTrav, and DoubleVect.
Definition at line 37 of file ArrOfDouble.cpp.
{
void ArrOfDouble::fill_default_value (Array_base::Resize_Options opt, int first, int nb) [protected]
Remplit "nb" cases consecutives du tableau a partir de la case "first"
avec une valeur par defaut.
Cette fonction est appelee lors d'un resize pour initialiser les
cases nouvellement creees.
Le comportement depend actuellement du type de tableau :
* Tableau de type "smart_resize":
* en mode debug (macro NDEBUG non definie) le tableau est initialise
avec une valeur invalide.
* en optimise, le tableau n'est pas initialise
* Tableau normal :
Le tableau est initialise avec la valeur 0. Ce comportement est choisi
pour des raisons de compatibilite avec l'implementation precedente.
Cette specification pourrait etre modifiee prochainement pour des raisons
de performances (pour ne pas avoir a initialiser inutilement les tableaux).
DONC: il faut supposer desormais que les nouvelles cases ne sont pas
initialisees lors d'un resize.
Parametre: first
Signification: premiere case a initialiser.
Contrainte: (nb==0) ou (0 <= first < memory_size_)
Parametre: nb
Signification: nombre de cases a initialiser.
Contrainte: (nb==0) ou (0 < nb <= memory_size_ - first)
Definition at line 650 of file ArrOfDouble.cpp.
References Array_base::COPY_INIT, data_, DMAXFLOAT, and memory_size_.
Referenced by ArrOfDouble(), and memory_resize().
{
  assert((nb == 0) || (first >= 0 && first < memory_size_));
  assert((nb == 0) || (nb > 0 && nb <= memory_size_ - first));
  double * data = data_;
  assert(data!=0 || nb==0);
  data += first;
  if (opt != COPY_INIT)
    {
// On initialise uniquement en mode debug
#ifndef NDEBUG
// B.M. L'utilisation de NAN n'est pas possible car elle provoque une erreur
// dans double & operator[] a cause de assert(...DMAXFLOAT). Du coup il est
// impossible de mettre une valeur dans le tableau autrement qu'avec append_array()
#if 0
// Ceci represente un NAN. N'importe quelle operation avec ca fait encore un NAN.
// Si c'est pas portable, on peut remplacer par DMAX_FLOAT sur les autres machines.
// Attention, il faut long long car sinon warning sur gcc 4.1 et i686
      static const unsigned long long VALEUR_INVALIDE =
        0x7ff7ffffffffffffULL;
      /* static const double VALEUR_INVALIDE = DMAXFLOAT;    */
// On utilise "memcpy" et non "=" car "=" peut provoquer une exception
// si la copie passe par le fpu.
      for (int i = 0; i < nb; i++)
        memcpy(data + i, & VALEUR_INVALIDE, sizeof(double));
#else
// Alternative acceptable... ?
      for (int i = 0; i < nb; i++)
        data[i] = DMAXFLOAT*0.999;
#endif
#endif
    }
  else
    {
// Comportement pour les tableaux normaux : compatibilite avec la
// version precedente : on initialise avec 0.
      for (int i = 0; i < nb; i++)
        data[i] = (double) 0;
    }
}
const Type_info * ArrOfDouble::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Array_base.
Reimplemented in DoubleTab, DoubleTrav, and DoubleVect.
Definition at line 37 of file ArrOfDouble.cpp.
Referenced by DoubleVect::copy(), and resize_array().
{
enum ArrOfDouble::Storage ArrOfDouble::get_mem_storage () const
Renvoie le mode d'allocation du tableau (qui sera utilise
lors du prochain resize si changement de taille).
(voir VDoubledata et Double_ptr_trav)
Definition at line 432 of file ArrOfDouble.cpp.
References storage_type_.
{
  return storage_type_;
}
const Type_info * ArrOfDouble::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Array_base.
Reimplemented in DoubleTab, DoubleTrav, and DoubleVect.
Definition at line 37 of file ArrOfDouble.cpp.
Referenced by resize_array().
{
ArrOfDouble & ArrOfDouble::inject_array (const ArrOfDouble & source, int nb_elements = -1, int first_element_dest = 0, int first_element_source = 0)
Copie les elements source[first_element_source + i]
dans les elements (*this)[first_element_dest + i] pour 0 <= i < nb_elements
Les autres elements de (*this) sont inchanges.
Returns:
ArrOfDouble&
Signification: *this
Contraintes:
Definition at line 1110 of file ArrOfDouble.cpp.
References addr(), data_, and size_array().
Referenced by append_array_to_array(), ArrOfDouble(), Eval_Source_C_VEF_Face::calculer_terme_source_non_standard(), Eval_Source_C_VEF_Face::calculer_terme_source_standard(), DoubleVect::copy(), DoubleVect::copy_(), envoyer_all_to_all(), ExtrudeParoi::extrude(), multiplier_diviser_rho(), operator=(), Solv_GCP::prepare_data(), Op_Diff_VEF_base::remplir_nu(), Solv_GCP::resoudre_(), Discret_Thyd::section_passage(), and Op_Diff_PolyMAC_base::update_nu().
{
  assert(&source != this);
  assert(nb_elements >= -1);
  assert(first_element_dest >= 0);
  assert(first_element_source >= 0);
  if (nb_elements < 0)
    nb_elements = source.size_array();
  assert(first_element_source + nb_elements <= source.size_array());
  assert(first_element_dest + nb_elements <= size_array());
  if (nb_elements > 0)
    {
      double * addr_dest = data_ + first_element_dest;
      const double * addr_source = source.addr() + first_element_source;
// PL: On utilise le memcpy car c'est VRAIMENT plus rapide (10% +vite sur RNR_G20)
      memcpy(addr_dest , addr_source, nb_elements * sizeof(double));
      /*
        int i;
        for (i = 0; i < nb_elements; i++) {
        addr_dest[i] = addr_source[i];
        } */
    }
  return *this;
}
void ArrOfDouble::memory_resize (int new_size, Array_base::Resize_Options opt = COPY_INIT) [private]
Si besoin, alloue une nouvelle zone de memoire,
copie les donnees et efface l'ancienne zone de memoire.
Attention, on suppose que cette methode est appelee par
resize_array().
Attention: si ref_count_>1, l'appel a resize_array() est
autorise uniquement si la nouvelle taille est identique
a la precedente (auquel cas on ne fait rien)
Si ref_count_ == 1, l'appel est invalide si p_->data_ est
different de data_ (le tableau a ete construit avec ref_array()
avec start > 0)
Definition at line 541 of file ArrOfDouble.cpp.
References Array_base::COPY_INIT, data_, detach_array(), fill_default_value(), VDoubledata::get_data(), VDoubledata::get_size(), memory_size_, Array_base::NOCOPY_NOINIT, p_, ref_count(), size_array_, smart_resize_, and storage_type_.
Referenced by resize_array_().
{
  assert(new_size >= 0);
// Si new_size==size_array_, on ne fait rien, c'est toujours autorise
  if (new_size == size_array_)
    return;
// Sinon, il faut que le resize soit autorise, c'est a dire
// - soit le tableau est detache
// - soit le tableau est normal et il n'y a pas d'autre reference au tableau
  assert((data_ == 0) || ((p_ != 0) && (p_->get_data() == data_) && (ref_count() == 1)));
// Occupation memoire de l'ancien tableau:
  int old_mem_size = memory_size_;
  assert((!p_) || (p_->get_size() == memory_size_));
  assert(memory_size_ >= size_array_);
// Occupation memoire du nouveau tableau :
// Si smart_resize, on prend au moins deux fois la taille
// precedente, ou new_size
  int new_mem_size = new_size;
  if (smart_resize_)
    {
      if (new_size <= old_mem_size)
        new_mem_size = old_mem_size;
      else if (new_size < old_mem_size * 2)
        new_mem_size = old_mem_size * 2;
      else if (new_size > old_mem_size && old_mem_size > INT_MAX / 2)
        new_mem_size = INT_MAX;
    }
  if (new_mem_size != old_mem_size)
    {
// detach_array() efface le contenu de size_array_. On le met de cote:
      const int old_size_array = size_array_;
      if (new_mem_size == 0)
        {
// La nouvelle taille est nulle, on cree un tableau "detache"
          detach_array();
        }
      else
        {
// Allocation d'une nouvelle zone
          VDoubledata * new_p = new VDoubledata(new_mem_size, storage_type_);
          double * new_data = new_p->get_data();
// Raccourci si le tableau etait "detache", inutile de copier
// les anciennes donnees. On copie si COPY_OLD est demande
          int copy_size = 0;
          if (data_ != 0)
            {
// Calcul du nombre d'elements a copier vers la nouvelle
// zone de memoire : c'est le min de l'ancienne et de
// la nouvelle taille.
              if (opt != NOCOPY_NOINIT)
                {
                  copy_size = size_array_;
                  if (new_size < copy_size)
                    copy_size = new_size;
// Copie des valeurs dans le nouveau tableau
                  for (int i = 0; i < copy_size; i++)
                    new_data[i] = data_[i];
                }
// Destruction de l'ancienne zone (si plus aucune reference)
              detach_array();
            }
// On attache la nouvelle zone de memoire
          p_ = new_p;
          data_ = new_data;
          memory_size_ = new_mem_size;
// Initialisation des cases supplementaires avec une valeur par defaut
          fill_default_value(opt, copy_size, new_mem_size - copy_size);
// Restaure l'ancienne valeur de size_array_
          size_array_ = old_size_array;
        }
    }
  else
    {
// Pas de reallocation, initialisation si besoin
      if (opt == COPY_INIT && new_size > size_array_)
        {
          fill_default_value(opt, size_array_, new_size - size_array_);
        }
    }
}
double & ArrOfDouble::operator() (int i) [inline]
idem operator[]
Reimplemented in DoubleTab.
Definition at line 335 of file ArrOfDouble.h.
References operator[]().
{
  return operator[](i);
}
const double & ArrOfDouble::operator() (int i) const [inline]
Reimplemented in DoubleTab.
Definition at line 340 of file ArrOfDouble.h.
References operator[]().
{
  return operator[](i);
}
ArrOfDouble & ArrOfDouble::operator*= (const double dy)
muliplie toutes les cases par dy
Returns:
ArrOfDouble &
Signification: *this
Reimplemented in DoubleVect.
Definition at line 1238 of file ArrOfDouble.cpp.
References data_, and size_array().
Referenced by operator/=().
{
  double * data = data_;
  const int n = size_array();
  for(int i=0; i < n; i++)
    data[i] *= dy;
  return *this;
}
ArrOfDouble & ArrOfDouble::operator+= (const ArrOfDouble & y)
Addition case a case sur toutes les cases du tableau.
Returns:
ArrOfDouble&
Signification: *this
Contraintes:
Definition at line 1169 of file ArrOfDouble.cpp.
References data_, and size_array().
{
  assert(size_array()==y.size_array());
  double* dx = data_;
  const double* dy = y.data_;
  const int n = size_array();
  for (int i=0; i<n; i++)
    dx[i] += dy[i];
  return *this;
}
ArrOfDouble & ArrOfDouble::operator+= (const double dy)
ajoute la meme valeur a toutes les cases du tableau
Returns:
ArrOfDouble
Signification: *this
Contraintes:
Reimplemented in DoubleVect.
Definition at line 1194 of file ArrOfDouble.cpp.
References data_, and size_array().
{
  double * data = data_;
  const int n = size_array();
  for(int i=0; i < n; i++)
    data[i] += dy;
  return *this;
}
ArrOfDouble & ArrOfDouble::operator-= (const ArrOfDouble & y)
Soustraction case a case sur toutes les cases du tableau
Parametre: const ArrOfDouble& y
Signification: tableau de meme taille que *this.
Returns:
ArrOfDouble&
Signification: *this
Definition at line 1208 of file ArrOfDouble.cpp.
References data_, and size_array().
{
  const int size = size_array();
  assert(size == y.size_array());
  double * data = data_;
  const double * data_y = y.data_;
  for (int i=0; i < size; i++)
    data[i] -= data_y[i];
  return *this;
}
ArrOfDouble & ArrOfDouble::operator-= (const double dy)
soustrait la meme valeur a toutes les cases
Returns:
ArrOfDouble &
Signification: *this
Reimplemented in DoubleVect.
Definition at line 1224 of file ArrOfDouble.cpp.
References data_, and size_array().
{
  double * data = data_;
  const int n = size_array();
  for(int i=0; i < n; i++)
    data[i] -= dy;
  return *this;
}
ArrOfDouble & ArrOfDouble::operator/= (const double dy)
divise toutes les cases par dy
Returns:
ArrOfDouble &
Signification: *this
Reimplemented in DoubleVect.
Definition at line 1252 of file ArrOfDouble.cpp.
References operator*=().
{
  const double i_dy = 1. / dy;
  operator*=(i_dy);
  return *this;
}
ArrOfDouble & ArrOfDouble::operator= (const ArrOfDouble & m)
Copie les donnees du tableau m.
Si "m" n'a pas la meme taille que "*this", on fait un resize_array.
Ensuite, on copie les valeurs de "m" dans "*this".
Le type de tableau (methode d'allocation) n'est pas copie.
Returns:
ArrOfDouble&
Signification: *this
Definition at line 467 of file ArrOfDouble.cpp.
References inject_array(), Array_base::NOCOPY_NOINIT, resize_array(), and size_array().
Referenced by copy_array().
{
  if (&m != this)
    {
      const int new_size = m.size_array();
// On utilise la methode resize_array() qui teste le type derive de l'objet
// (resize interdit sur un type derive)
      resize_array(new_size, NOCOPY_NOINIT);
      inject_array(m);
    }
  return *this;
}
ArrOfDouble& ArrOfDouble::operator= (const FArrOfDouble &)
ArrOfDouble & ArrOfDouble::operator= (double x) [inline]
x est affecte a toutes les cases
Returns:
ArrOfDouble&
Signification: *this
Contraintes:
Reimplemented in DoubleTab, DoubleTrav, and DoubleVect.
Definition at line 292 of file ArrOfDouble.h.
References data_, and size_array_.
{
  const int n = size_array_;
  double *data = data_;
  for (int i = 0; i < n; i++)
    {
      data[i] = x;
    }
  return *this;
}
double & ArrOfDouble::operator[] (int i) [inline]
operateur [] retourne le ieme element du tableau
Reimplemented in DoubleTab.
Definition at line 311 of file ArrOfDouble.h.
References data_, DMAXFLOAT, and size_array_.
Referenced by operator()().
{
  assert(i >= 0 && i < size_array_);
  assert(data_[i] > -DMAXFLOAT && data_[i] < DMAXFLOAT);
  return data_[i];
}
const double & ArrOfDouble::operator[] (int i) const [inline]
operateur [] retourne le ieme element du tableau
Reimplemented in DoubleTab.
Definition at line 326 of file ArrOfDouble.h.
References data_, DMAXFLOAT, and size_array_.
{
  assert(i >= 0 && i < size_array_);
  assert(data_[i] > -DMAXFLOAT && data_[i] < DMAXFLOAT);
  return data_[i];
}
void ArrOfDouble::ordonne_array ()
Tri des valeurs du tableau dans l'ordre croissant.
La fonction utilisee est qsort de stdlib (elle est en n*log(n)).
Definition at line 909 of file ArrOfDouble.cpp.
References data_, fonction_compare_arrofdouble_ordonner(), and size_array_.
Referenced by array_trier_retirer_doublons(), and Traitement_particulier_NS_canal::remplir_reordonne_Y_tot().
{
  const int size = size_array_;
  if (size > 1)
    {
      double * data = data_;
      qsort(data, size, sizeof(double),
            fonction_compare_arrofdouble_ordonner);
    }
}
Sortie & ArrOfDouble::printOn (Sortie & os) const [protected, virtual]
Ecriture du tableau sur "os" :
ecrit le nombre d'elements suivi des valeurs du tableau.
Returns:
Sortie&
Signification: le flot de sortie modifie
Reimplemented from Array_base.
Reimplemented in DoubleTab, DoubleTrav, and DoubleVect.
Definition at line 263 of file ArrOfDouble.cpp.
References data_, finl, Sortie::put(), size_array(), and sz.
{
  int sz=size_array();
  os << sz << finl;
  if (sz > 0)
    {
      const double* v = data_;
      os.put(v,sz,sz);
    }
  return os;
}
Entree & ArrOfDouble::readOn (Entree & is) [protected, virtual]
Lecture d'un tableau dans un flot d'entree
Lit le nombre d'elements suivi des elements eux-memes.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Array_base.
Reimplemented in DoubleTab, DoubleTrav, and DoubleVect.
Definition at line 290 of file ArrOfDouble.cpp.
References Cerr, data_, Process::exit(), finl, Entree::get(), resize_array_(), and sz.
{
  int sz;
  is >> sz;
  if (sz >= 0)
    {
// Appel a la methode sans precondition sur le type derive
// (car readOn est virtuelle, les autres proprietes seront initialisees correctement)
      resize_array_(sz);
      if (sz > 0)
        {
          double* v = data_;
          is.get(v,sz);
        }
    }
  else
    {
      Cerr << "Error in ArrOfDouble:readOn : size = " << sz << finl;
      assert(0);
      exit();
    }
  return is;
}
void ArrOfDouble::ref_array (ArrOfDouble & m, int start = 0, int size = -1) [virtual]
Fait pointer le tableau vers les memes donnees qu'un tableau
existant. Le tableau sera du meme type que le tableau m ("detache",
"normal"). Le tableau m ne doit pas etre de type "ref_data"
Attention, le tableau source et *this sont ensuite figes (resize_array()
interdit).
Attention: methode virtuelle: dans les classes derivee, cette methode
initialise les structures pour creer un tableau sequentiel.
Parametre: const ArrOfDouble& m
Signification: le tableau a referencer (pas de type "ref_data"
et different de *this !!!)
Returns:
ArrOfDouble&
Signification: *this
Contraintes:
Reimplemented in DoubleTab, and DoubleVect.
Definition at line 964 of file ArrOfDouble.cpp.
References attach_array(), and detach_array().
Referenced by Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), and Champ_implementation_P1::init_from_file().
{
  assert(&m != this);
// La condition 'm n'est pas de type "ref_data"' est necessaire pour
// attach_array().
  detach_array();
  attach_array(m, start, size);
}
int ArrOfDouble::ref_count () const
Retourne le nombre de references des donnees du tableau
si le tableau est "normal", -1 s'il est "detache" ou "ref_data".
Returns:
int
Signification: ref_count_
Definition at line 1146 of file ArrOfDouble.cpp.
References p_, and VDoubledata::ref_count().
Referenced by memory_resize(), operator<<(), and resize_array_().
{
  if (p_)
    return p_->ref_count();
  else
    return -1;
}
void ArrOfDouble::ref_data (double * ptr, int size) [virtual]
Fait pointer le tableau vers la zone de memoire "data_".
On detache la zone de memoire existante. Le tableau devient
de type "ref_data". Attention : ptr doit etre non nul.
La taille est initialisee avec size.
Attention: methode virtuelle: dans les classes derivee, cette methode
initialise les structures pour creer un tableau sequentiel.
Pour faire une ref sur un tableau parallele utiliser DoubleVect::ref()
Parametre: double*
Signification: le tableau a recuperer. Si pointeur nul alors size
doit etre nulle aussi et le tableau reste detache
Parametre: int size
Signification: le nombre d'elements du tableau.
Returns:
ArrOfDouble&
Signification: *this
< Pour passer les tests si on resize a la meme taille
Reimplemented in DoubleTab, and DoubleVect.
Definition at line 988 of file ArrOfDouble.cpp.
References data_, detach_array(), memory_size_, and size_array_.
Referenced by Schema_Comm_Vecteurs::get_next_area_double(), and Solv_GCP::prepare_data().
{
  assert(ptr != 0 || size == 0);
  assert(size >= 0);
  detach_array();
  data_ = ptr;
  size_array_ = size;
  memory_size_ = size; //!< Pour passer les tests si on resize a la meme taille
}
void ArrOfDouble::reset () [virtual]
Remet le tableau dans l'etat obtenu avec le constructeur par defaut
(libere la memoire mais conserve le mode d'allocation memoire actuel)
Reimplemented in DoubleTab, and DoubleVect.
Definition at line 451 of file ArrOfDouble.cpp.
References detach_array().
Referenced by Octree_Zone::reset(), and Octree_Double::reset().
{
  detach_array();
}
void ArrOfDouble::resize (int new_size, Array_base::Resize_Options opt = COPY_INIT) [inline]
appel a ArrOfDouble::resize_array()
Reimplemented in DoubleTab, and DoubleVect.
Definition at line 252 of file ArrOfDouble.h.
References resize_array().
Referenced by Extruder::Extruder(), Extruder_en20::Extruder_en20(), Extruder_en3::Extruder_en3(), Matrice_Nulle::get_stencil_and_coefficients(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Terme_Source_Canal_perio::lire_donnees(), Terme_Boussinesq_base::lire_donnees(), print_stat(), and Terme_Source_Canal_perio::source().
{
  resize_array(new_size, opt);
}
void ArrOfDouble::resize_array (int new_size, Array_base::Resize_Options opt = COPY_INIT) [inline]
Definition at line 244 of file ArrOfDouble.h.
References get_info(), info(), resize_array_(), and size_array_.
Referenced by append_array(), append_array_to_array(), array_smart_allocate(), array_trier_retirer_doublons(), Octree_Zone::build(), Calcul_integrale_locale::calculer(), Reordonner_faces_periodiques::check_faces_periodiques(), Reordonner_faces_periodiques::chercher_direction_perio(), Terme_Source_Rappel_T_VEF_Face::completer(), Op_Conv_Muscl_New_VEF_Face::completer(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Reaction::completer(), Chimie::completer(), compute_cell_qualities_for_tetrahedron(), compute_cell_qualities_for_triangle(), Octree_Double::compute_origin_factors(), Assembleur_P_VDF::construire(), SolvElem_Gmres::dimensionne_wks(), SolvElem_BiCGStab::dimensionne_wks(), envoyer_all_to_all(), extract_coef_local(), ExtrudeParoi::ExtrudeParoi(), Solv_Cholesky::Fact_Cholesky(), ILU::factoriser(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Diagonale::get_stencil_and_coefficients(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), MaillerParallel::interpreter(), Extraire_plan::interpreter_(), Calculer_Moments::interpreter_(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), Equation_base::lire_motcle_non_standard(), operator=(), Solv_GCP::prepare_data(), resize(), resize_tab(), and Matrice_Sym::unsymmetrize_stencil_and_coefficients().
{
// Si le tableau change de taille, il doit etre du type ArrOfDouble
  assert(new_size == size_array_ || get_info() == ArrOfDouble::info());
  resize_array_(new_size, opt);
}
void ArrOfDouble::resize_array_ (int n, Array_base::Resize_Options opt = COPY_INIT) [inline, protected]
methode protegee de changement de taille, appelable par
les classes derivees (idem que resize_array() mais sans condition sur le
type derive de l'objet)
Definition at line 260 of file ArrOfDouble.h.
References Array_base::COPY_INIT, data_, memory_resize(), memory_size_, p_, ref_count(), size_array_, and smart_resize_.
Referenced by DoubleVect::copy_(), readOn(), resize_array(), and DoubleVect::resize_vect_().
{
  assert(new_size >= 0);
// Soit le tableau est detache (data_==0), soit il est normal (p_!=0)
// S'il est normal, il ne faut pas qu'il y ait d'autre reference au tableau,
// ou alors la taille ne doit pas changer.
  assert(new_size == size_array_ || data_ == 0 || (p_ != 0 && ref_count() == 1));
// Le seul cas ou on n'appelle pas memory_resize est le suivant:
// le tableau est smart_resize
// ET la taille reste inferieure ou egale a la taille allouee
// ET on ne veut pas initialiser les nouvelles cases
  if ((opt == COPY_INIT) || (new_size > memory_size_) || (smart_resize_ == 0))
// attention, il existe un cas ou memory_resize realloue un buffer meme si size_array_==new_size:
// si on est passe de smart_resize=1 a smart_resize=0, on realloue juste ce qu'il faut.
    memory_resize(new_size, opt);
  size_array_ = new_size;
}
void ArrOfDouble::resize_tab (int n, Array_base::Resize_Options opt = COPY_INIT) [virtual]
methode virtuelle identique a resize_array(), permet de traiter
de facon generique les ArrOf, Vect et Tab.
Si l'objet est de type ArrOfDouble, appel a resize_array(n)
Prerequis: le tableau doit etre "resizable" (voir resize_array()).
S'il est d'un type derive (Vect ou Tab), il ne doit pas avoir de descripteur
parallele si la taille est effectivement modifiee.
Reimplemented in DoubleTab, and DoubleVect.
Definition at line 512 of file ArrOfDouble.cpp.
References resize_array().
{
  resize_array(n, opt);
}
ArrOfDouble & ArrOfDouble::self_cast (Objet_U & r) [static]
Reimplemented from Array_base.
Reimplemented in DoubleTab, DoubleTrav, and DoubleVect.
Definition at line 37 of file ArrOfDouble.cpp.
{
const ArrOfDouble & ArrOfDouble::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Array_base.
Reimplemented in DoubleTab, DoubleTrav, and DoubleVect.
Definition at line 37 of file ArrOfDouble.cpp.
{
void ArrOfDouble::set_mem_storage (const Storage storage)
Change le mode d'allocation memoire lors des resize<br>(voir VDoubledata et Double_ptr_trav)
Exemple pour creer un tableau avec allocation temporaire:
DoubleTab tab; // Creation d'un tableau vide
tab.set_mem_storage(TEMP_STORAGE); // Changement de mode d'allocation
tab.resize(n); // Allocation memoire.
Definition at line 423 of file ArrOfDouble.cpp.
References storage_type_.
Referenced by DoubleTrav::DoubleTrav().
{
  storage_type_ = storage;
}
void ArrOfDouble::set_smart_resize (int flag)
Change le mode l'allocation memoire: reallocation d'un tableau
a chaque changement de taille (flag = 0) ou reallocation
uniquement si la taille augmente et par doublement de la taille
du tableau (flag = 1).
Definition at line 442 of file ArrOfDouble.cpp.
References smart_resize_.
Referenced by array_smart_allocate(), Assembleur_P_PolyMAC::assembler_mat(), Ch_front_input::buildSommetsFaces(), Calcul_integrale_locale::Calcul_integrale_locale(), Zone_CoviMAC::fgrad(), Echange_contact_CoviMAC::fgrad(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Zone_PolyMAC::init_m1_2d(), Zone_PolyMAC::init_m1_3d(), Zone_PolyMAC::init_m2(), Champ_Face_PolyMAC::init_ra(), Zone_PolyMAC::init_rf(), Champ_Face_PolyMAC::init_va(), Zone_PolyMAC::init_ve(), Zone_CoviMAC::init_ve(), Champ_Face_CoviMAC::init_ve2(), Zone_PolyMAC::init_we_2d(), Zone_PolyMAC::init_we_3d(), Champ_front_recyclage::initialiser(), and Zone_PolyMAC::orthocentrer().
{
  assert(flag == 0 || flag == 1);
  smart_resize_ = flag;
}
int ArrOfDouble::size_array () const [inline]
Renvoie la taille du tableau (nombre d'elements declares
a la construction ou a resize_array()).
C'est le nombre d'elements accessibles a operator[].
Returns:
int
Definition at line 350 of file ArrOfDouble.h.
References size_array_.
Referenced by CSR_Builder::add_coeff(), Matrix_tools::add_scaled_matrices(), Matrix_tools::add_symmetric_scaled_matrices(), add_to_vect_blocs(), add_to_vect_items(), affecte_double_avec_doubletab(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), T_It_VDF_Elem< _TYPE_ >::ajouter(), Matrice_SuperMorse::ajouter_mult_vect_et_prodscal(), Matrice_Morse::ajouter_multvect_(), Matrice_Dense::ajouter_multvect_(), Matrice_Bloc_Sym::ajouter_multvect_(), Matrice_Bloc::ajouter_multvect_(), Matrice_Morse::ajouter_multvectT_(), Matrice_Dense::ajouter_multvectT_(), Matrice_Bloc::ajouter_multvectT_(), append_array_to_array(), DoubleTab::append_line(), ArrOfDouble(), Assembleur_P_VEFPreP1B::assembler_rho_variable(), Assembleur_P_EF::assembler_rho_variable(), attach_array(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Matrix_tools::build_morse_matrix(), Matrix_tools::build_symmetric_morse_matrix(), Reaction::calcul_proportion_implicite(), Zone_EF::calculer_Bij(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_Elem_Axi::calculer_dt_stab(), Partitionneur_base::calculer_graphe_connexions_periodiques(), Op_Dift_VEF_Face::calculer_pour_post(), Op_Diff_VEF_base::calculer_pour_post(), Op_Conv_EF_VEF_P1NC_Stab::calculer_senseur(), Op_Conv_Muscl_New_VEF_Face::calculer_senseur_v1(), Eval_Puiss_Th_QC_VDF_Elem::calculer_terme_source(), calculer_vecteur_2faces(), Zone_EF::calculer_volumes_sommets(), Scatter::check_consistancy_remote_items(), Zone::chercher_elements(), Periodique::completer(), Schema_Adams_Bashforth_order_3::compute_adams_bashforth_coefficients(), Schema_Adams_Bashforth_order_2::compute_adams_bashforth_coefficients(), Schema_Adams_Moulton_order_3::compute_adams_moulton_coefficients(), Schema_Adams_Moulton_order_2::compute_adams_moulton_coefficients(), Schema_Backward_Differentiation_order_3::compute_backward_differentiation_coefficients(), Schema_Backward_Differentiation_order_2::compute_backward_differentiation_coefficients(), Triangle::contient(), Tetraedre::contient(), Segment::contient(), Rectangle_axi::contient(), Rectangle::contient(), Quadrangle_VEF::contient(), Prisme::contient(), Point::contient(), Hexaedre_VEF::contient(), Hexaedre_axi::contient(), Hexaedre::contient(), DoubleVect::copy(), DoubleVect::copy_(), Champ_Inc_base::creer_tableau_distribue(), Champ_Fonc_base::creer_tableau_distribue(), descente_bloc_extradiag_assert(), Matrice_Morse::diagmulmat(), disp_da(), dotproduct_array(), dotproduct_array_fois_inverse_quantitee_entrelacee(), DoubleTrav::DoubleTrav(), MD_Vector_tools::dump_vector_with_md(), Debog_Pb::ecrire_partie(), envoyer_all_to_all(), Moyenne_volumique::eval_filtre(), exemple_champ_non_homogene(), Equation_base::expression_residu(), Reaction::extract_coef(), Octree_Zone::find_elements(), Turbulence_paroi_base::get_champ(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), gmres_local(), imax_array(), imin_array(), Navier_Stokes_std::impr(), Equation_base::imprime_residu(), Ch_front_input_P1::initialiser(), Ch_front_input_uniforme::initialiser(), inject_array(), ExtrudeParoi::interpreter_(), Extraire_plan::interpreter_(), Corriger_frontiere_periodique::interpreter_(), invalidate_data(), inverse(), DoubleTab::inverse_LU(), DoubleVect::line_size(), Champ_Fonc_MED::lire(), lire_special(), DoubleVect::lit(), DoubleTab::lit(), local_carre_norme_tab(), local_max_abs_tab(), max_abs_array(), max_array(), DoubleTab::max_du_u(), max_to_vect_items(), Op_Dift_VEF_base::mettre_a_jour(), Eval_Dift_VDF_var_Face::mettre_a_jour(), Terme_Boussinesq_base::mettre_a_jour(), Champ_Fonc_MED_Tabule::mettre_a_jour(), Champ_front_xyz_debit::mettre_a_jour(), min_abs_array(), min_array(), mincol1_to_vect_items(), Zone_Cl_EF::modifie_gradient(), mp_collective_op(), mp_norme_tab(), multiplie(), norme_array(), operator*=(), operator+=(), operator-=(), operator<<(), DoubleTab::operator=(), operator=(), operator==(), Solv_GCP::prepare_data(), DoubleTab::printOn(), printOn(), Eval_centre_VDF_Elem::qcentre(), Eval_centre4_VDF_Elem::qcentre(), Eval_centre_PolyMAC_Elem::qcentre(), Eval_Quick_VDF_Elem::quick_fram(), Objet_a_lire::read(), read_from_vect_blocs(), read_from_vect_items(), Pbc_MED::readOn(), Champ_Fonc_MED::readOn(), DoubleVect::readOn(), DoubleTab::readOn(), Champ_input_P0::readOn(), Ch_input_uniforme::readOn(), DoubleTab::ref(), DoubleVect::ref_array(), DoubleTab::ref_array(), DoubleTab::ref_data(), DoubleTab::ref_tab(), remontee_bloc_extradiag_assert(), Assembleur_P_VEF::remplir(), Matrice_Bloc::remplir(), Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(), DoubleVect::resize(), DoubleTab::resize_dim0(), Solv_Petsc::resoudre_systeme(), sameDoubleTab(), Champ_Inc_base::sauvegarder(), Champ_Fonc_base::sauvegarder(), Octree_Double::search_elements_box(), Octree_Double::search_nodes_close_to(), Zone_VF::section_passage_face(), DoubleVect::set_md_vector(), DoubleVect::size_reelle(), DoubleVect::size_totale(), Solv_Gen::solve(), tab_divide_any_shape(), tab_multiply_any_shape(), test_solveur(), test_un_solveur(), Raccord_distant_homogene::trace_elem_distant(), Frontiere::trace_elem_local(), Raccord_distant_homogene::trace_face_distant(), Frontiere::trace_som_local(), trier(), trier_abs(), Matrice_Sym::unsymmetrize_stencil_and_coefficients(), Schema_Temps_base::update_critere_statio(), Loi_horaire::verifier_derivee(), Debog_Pb::verifier_gen(), Verifier_Qualite_Raffinements::verifier_qualite_raffinements(), write_to_vect_blocs(), and write_to_vect_items().
{
  return size_array_;
}
unsigned ArrOfDouble::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in DoubleTab, DoubleTrav, and DoubleVect.
Definition at line 37 of file ArrOfDouble.cpp.
{
Member Data Documentation
double* ArrOfDouble::data_ [private]
Definition at line 178 of file ArrOfDouble.h.
Referenced by addr(), append_array(), array_trier_retirer_doublons(), ArrOfDouble(), attach_array(), detach_array(), fill_default_value(), inject_array(), memory_resize(), operator*=(), operator+=(), operator-=(), operator=(), operator[](), ordonne_array(), printOn(), readOn(), ref_data(), and resize_array_().
const Type_info ArrOfDouble::info_obj [static]
Reimplemented from Array_base.
Reimplemented in DoubleTab, DoubleTrav, and DoubleVect.
Definition at line 74 of file ArrOfDouble.h.
int ArrOfDouble::memory_size_ [private]
Definition at line 187 of file ArrOfDouble.h.
Referenced by ArrOfDouble(), attach_array(), detach_array(), fill_default_value(), memory_resize(), ref_data(), and resize_array_().
VDoubledata* ArrOfDouble::p_ [private]
Definition at line 170 of file ArrOfDouble.h.
Referenced by ArrOfDouble(), attach_array(), detach_array(), memory_resize(), ref_count(), and resize_array_().
int ArrOfDouble::size_array_ [private]
Definition at line 182 of file ArrOfDouble.h.
Referenced by append_array(), array_trier_retirer_doublons(), ArrOfDouble(), attach_array(), detach_array(), memory_resize(), operator=(), operator[](), ordonne_array(), ref_data(), resize_array(), resize_array_(), size_array(), and ~ArrOfDouble().
int ArrOfDouble::smart_resize_ [private]
Definition at line 193 of file ArrOfDouble.h.
Referenced by append_array(), ArrOfDouble(), attach_array(), memory_resize(), resize_array_(), and set_smart_resize().
Storage ArrOfDouble::storage_type_ [private]
Definition at line 197 of file ArrOfDouble.h.
Referenced by ArrOfDouble(), get_mem_storage(), memory_resize(), and set_mem_storage().
The documentation for this class was generated from the following files:
src/Kernel/Math/ArrOfDouble.h
src/Kernel/Math/ArrOfDouble.cpp