TRUST: Convection_Diffusion_Temperature Class Reference
Convection_Diffusion_Temperature Class Reference
classe Convection_Diffusion_Temperature
Cas particulier de Convection_Diffusion_std
quand le scalaire subissant le transport est la temperature.
#include <Convection_Diffusion_Temperature.h>
Public Member Functions
~Convection_Diffusion_Temperature ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Convection_Diffusion_Temperature ()
void set_param (Param &titi) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void associer_fluide (const Fluide_base &)
Associe un fluide incompressible a l'equation.
const Champ_Inc & inconnue () const override
Renvoie le champ inconnue representant la temperatue.
(version const)
Champ_Inc & inconnue () override
Renvoie le champ inconnue representant la temperatue.
void discretiser () override
Discretise l'equation.
const Milieu_base & milieu () const override
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
(version const)
const Fluide_base & fluide () const
Renvoie le fluide incompressible associe a l'equation.
(version const)
Fluide_base & fluide ()
Renvoie le fluide incompressible associe a l'equation.
Milieu_base & milieu () override
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
void associer_milieu_base (const Milieu_base &) override
Associe un milieu physique a l'equation,
le milieu est en fait caste en Fluide_base ou en Fluide_Ostwald.
int impr (Sortie &os) const override
Impression des flux sur les bords sur un flot de sortie.
Appelle Equation_base::impr(Sortie&)
const Champ_Don & diffusivite_pour_transport () const override
const Champ_base & diffusivite_pour_pas_de_temps () const override
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
const Motcle & domaine_application () const override
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
DoubleTab & derivee_en_temps_inco_eq_base (DoubleTab &)
void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem) override
void assembler_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
Public Member Functions inherited from Convection_Diffusion_std
Convection_Diffusion_std ()
~Convection_Diffusion_std () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &titi) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
int nombre_d_operateurs () const override
Renvoie le nombre d'operateurs de l'equation:
2 pour une equation de diffusion.
const Operateur & operateur (int) const override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1
(version const)
Operateur & operateur (int) override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1.
void associer_vitesse (const Champ_base &)
Associe la vitesse transportante a l'equation.
const Champ_Inc_base & vitesse_transportante () const
Renvoie une reference sur le champ representant
la vitesse transportante.
const Champ_Inc & inconnue () const override=0
Champ_Inc & inconnue () override=0
virtual const Champ_Don & diffusivite_pour_transport () const
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
virtual const Champ_base & vitesse_pour_transport () const
int sauvegarder_base (Sortie &) const
int reprendre_base (Entree &)
Public Member Functions inherited from Equation_base
Equation_base ()
~Equation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Methode appelee lorsqu'on cree l'instance de l'objet dans
le jeu de donnees (Interprete::ajouter)
virtual void avancer (int i=1)
virtual void reculer (int i=1)
virtual int nombre_d_operateurs () const =0
virtual int nombre_d_operateurs_tot () const
virtual const Operateur & operateur (int) const =0
virtual Operateur & operateur (int)=0
virtual const Operateur & operateur_fonctionnel (int) const
virtual Operateur & operateur_fonctionnel (int)
virtual const Champ_Inc & inconnue () const =0
virtual Champ_Inc & inconnue ()=0
virtual void associer_milieu_base (const Milieu_base &)=0
virtual const Milieu_base & milieu () const =0
virtual Milieu_base & milieu ()=0
int sauvegarder (Sortie &) const override
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
int reprendre (Entree &) override
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
int limpr () const
Demande au schema en temps si il faut effectuer une impression.
Renvoie 1 si il faut effectuer une impression.
Appel simple a Schema_Temps_base::limpr()
virtual void imprimer (Sortie &os) const
Imprime les operateurs de l'equation si le schema en temps
indique que c'est necessaire.
[SI limpr() ALORS impr(os)].
virtual int impr (Sortie &os) const
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
virtual void associer_milieu_equation ()
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
virtual DoubleTab & derivee_en_temps_inco_transport (DoubleTab &derivee)
virtual DoubleTab & corriger_derivee_expl (DoubleTab &)
virtual DoubleTab & corriger_derivee_impl (DoubleTab &)
virtual void mettre_a_jour (double temps)
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
virtual void abortTimeStep ()
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
virtual void valider_iteration ()
virtual int preparer_calcul ()
Tout ce qui ne depend pas des autres problemes eventuels.
virtual bool initTimeStep (double dt)
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
virtual bool updateGivenFields ()
virtual void discretiser ()
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
virtual void associer_pb_base (const Probleme_base &)
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur
de masse a l'equation.
virtual void completer ()
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
virtual double calculer_pas_de_temps () const
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des
pas de temps calcules par les operateurs.
Ces pas de temps sont ceux pour le schema d'Euler explicite.
Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule.
void calculer_pas_de_temps_locaux (DoubleTab &) const
Sources & sources ()
Renvoie les termes sources asssocies a l'equation.
const Sources & sources () const
Renvoie les termes sources asssocies a l'equation<br>(version const)
Solveur_Masse & solv_masse ()
Renvoie le solveur de masse associe a l'equation.
const Solveur_Masse & solv_masse () const
Renvoie le solveur de masse associe a l'equation.
(version const)
Probleme_base & probleme ()
Renvoie le probleme associe a l'equation.
const Probleme_base & probleme () const
Renvoie le probleme associe a l'equation.
(version const)
Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe a l'equation.
const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe a l'equation.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
S'associe au schema_en_temps.
virtual void associer_zone_dis (const Zone_dis &)
Associe la zone discretisee a l'equation.
const Discretisation_base & discretisation () const
Renvoie la discretisation associee a l'equation.
virtual Zone_Cl_dis & zone_Cl_dis ()
Renvoie la zone des conditions aux limite discretisee
associee a l'equation.
virtual const Zone_Cl_dis & zone_Cl_dis () const
Renvoie la zone des conditions aux limite discretisee
associee a l'equation<br>(version const)
Zone_dis & zone_dis ()
Renvoie la zone discretisee associee a l'equation.
const Zone_dis & zone_dis () const
Renvoie la zone discretisee associee a l'equation.
(version const)
const Nom & le_nom () const override
Renvoie le nom de l'equation.
DoubleVect & get_residu ()
DoubleVect & residu_initial ()
void initialise_residu (int=0)
virtual void imprime_residu (SFichier &)
virtual Nom expression_residu ()
virtual void dimensionner_matrice (Matrice_Morse &mat_morse)
virtual void dimensionner_matrice_sans_mem (Matrice_Morse &mat_morse)
virtual void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void modifier_pour_Cl (Matrice_Morse &mat_morse, DoubleTab &secmem) const
virtual void assembler_avec_inertie (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void dimensionner_termes_croises (Matrice_Morse &matrice, const Probleme_base &autre_pb, int nl, int nc)
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void assembler_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={})
Champ_Inc_base & champ_conserve () const
int has_champ_conserve () const
void init_champ_conserve () const
virtual std::pair< std::string, fonc_calc_t > get_fonc_champ_conserve () const
virtual Champ_Inc_base & champ_convecte () const
virtual int has_champ_convecte () const
virtual void init_champ_convecte () const
virtual void mettre_a_jour_champs_conserves (double temps, int reset=0)
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Motcle & domaine_application () const
Renvoie "indetermine"
Navier_Stokes_standard par exemple surcharge cette methode
pour renvoyer "Hydraulique".
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Verification du nombre de composantes lues pour la specification d un champ.
Actuellement utilise pour la lecture d un condition initiale ou limite.
virtual void verifie_ch_init_nb_comp_cl (const Champ_Inc_base &ch_ref, const int nb_comp, const Cond_lim_base &cl) const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
Add convection term
In: solution is the unknown I
Out: secmem is increased by convection(I)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution, const DoubleTab &terme_mul)
Parametre_equation & parametre_equation ()
const Parametre_equation & parametre_equation () const
virtual const Ref_Objet_U & get_modele (Type_modele type) const
virtual int equation_non_resolue () const
int disable_equation_residual () const
virtual const Champ_Inc & derivee_en_temps () const
virtual Champ_Inc & derivee_en_temps ()
void set_calculate_time_derivative (int i)
int calculate_time_derivative () const
void set_residuals (DoubleTab r)
virtual int positive_unkown ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Convection_Diffusion_Temperature & self_cast (Objet_U &)
static const Convection_Diffusion_Temperature & self_cast (const Objet_U &)
Static Public Member Functions inherited from Convection_Diffusion_std
static const Type_info * info ()
static Convection_Diffusion_std & self_cast (Objet_U &)
static const Convection_Diffusion_std & self_cast (const Objet_U &)
Static Public Member Functions inherited from Equation_base
static const Type_info * info ()
static Equation_base & self_cast (Objet_U &)
static const Equation_base & self_cast (const Objet_U &)
static void calculer_champ_conserve (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Convection_Diffusion_std
static const Type_info info_obj
Static Public Attributes inherited from Equation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Convection_Diffusion_std::printOn(Sortie&)
Entree & readOn (Entree &) override
Verifie si l'equation a une temperature et un fluide associe
cf Convection_Diffusion_std::readOn(Entree&).
DoubleTab & filtrage_si_appart_ibc (DoubleTab &, DoubleTab &)
DoubleTab & penalisation_L2 (DoubleTab &)
int verifier_tag_indicatrice_pena_glob ()
int mise_a_jour_tag_indicatrice_pena_glob ()
void set_indic_pena_globale ()
void mise_en_place_zone_fantome (DoubleTab &)
void calcul_indic_pena_global (IntTab &, IntTab &)
void transport_ibc (DoubleTrav &, DoubleTab &)
void ecrire_fichier_pena_th (DoubleTab &, DoubleTab &, DoubleTab &, DoubleTab &)
Sortie & printOn (Sortie &x) const override
Simple appel a Equation_base::printOn(Sortie&)
Entree & readOn (Entree &) override
cf Equation_base::readOn(Entree&)
Protected Member Functions inherited from Equation_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
virtual void set_param (Param &titi)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_sources (Entree &)
Lecture des termes sources dans un flot d'entree.
virtual Entree & lire_cond_init (Entree &)
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
virtual Entree & lire_cl (Entree &)
Lecture des conditions limites sur un flot d'entree.
voir Zone_Cl_dis_base::readOn.
virtual int verif_Cl () const
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
virtual void lire ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_Inc la_temperature
Ref_Fluide_base le_fluide
Champ_Fonc gradient_temperature
Champ_Fonc h_echange
int is_penalized
double eta
int choix_pena
int tag_indic_pena_global
IntTab indic_pena_global
IntTab indic_face_pena_global
Vect_RefObjU ref_penalisation_L2_FTD
DoubleTabs tab_penalisation_L2_FTD
Protected Attributes inherited from Convection_Diffusion_std
Ref_Champ_Inc_base la_vitesse_transportante
Operateur_Conv terme_convectif
Operateur_Diff terme_diffusif
Protected Attributes inherited from Equation_base
Nom nom_
Solveur_Masse solveur_masse
Sources les_sources
Ref_Schema_Temps_base le_schema_en_temps
Ref_Zone_dis la_zone_dis
Zone_Cl_dis la_zone_Cl_dis
Ref_Probleme_base mon_probleme
DoubleList dt_op_bak
int sys_invariant_
int implicite_
Parametre_equation parametre_equation_
Champ_Fonc volume_maille
List_RefObjU liste_modeles_
Champs_compris champs_compris_
Champs_Fonc list_champ_combi
Matrice_Morse matrice_stockee
int matrice_init
Champ_Inc champ_conserve_
Champ_Inc champ_convecte_
Detailed Description
classe Convection_Diffusion_Temperature
Cas particulier de Convection_Diffusion_std
quand le scalaire subissant le transport est la temperature.
Definition at line 37 of file Convection_Diffusion_Temperature.h.
Constructor & Destructor Documentation
~Convection_Diffusion_Temperature()
Convection_Diffusion_Temperature::~Convection_Diffusion_Temperature ()
Definition at line 36 of file Convection_Diffusion_Temperature.cpp.
Convection_Diffusion_Temperature()
Convection_Diffusion_Temperature::Convection_Diffusion_Temperature ()
Definition at line 39 of file Convection_Diffusion_Temperature.cpp.
{
// champs_compris_.ajoute_nom_compris("temperature_paroi");
  champs_compris_.ajoute_nom_compris("gradient_temperature");
  champs_compris_.ajoute_nom_compris("h_echange_");
  champs_compris_.ajoute_nom_compris("temperature_residu");
  eta = 1.0;
  is_penalized = 0;
  tag_indic_pena_global = -1;
  indic_pena_global = 0;
  indic_face_pena_global = 0;
  choix_pena = 0;
}
References Champs_compris::ajoute_nom_compris(), Equation_base::champs_compris_, choix_pena, eta, indic_face_pena_global, indic_pena_global, is_penalized, and tag_indic_pena_global.
Member Function Documentation
assembler()
void Convection_Diffusion_Temperature::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) override virtual
< Add source residual first
< la derivee est multipliee par rhoCp pour la convection
< Ajout de A*Inco(n) PL (11/04/2018): On aimerait bien calculer la contribution des sources en premier comme dans le cas VIA_CONTRIBUER_AU_SECOND_MEMBRE mais le cas Canal_perio_3D (keps periodique plante: il y'a une erreur de periodicite dans les termes sources du modele KEps...
Reimplemented from Equation_base.
Definition at line 697 of file Convection_Diffusion_Temperature.cpp.
{
  const double rhoCp = le_fluide->capacite_calorifique().valeurs()(0, 0) * le_fluide->masse_volumique().valeurs()(0, 0);
// Test de verification de la methode contribuer_a_avec
  for (int op=0; op<nombre_d_operateurs(); op++)
    operateur(op).l_op_base().tester_contribuer_a_avec(inco, matrice);
// Contribution des operateurs et des sources:
// [Vol/dt+A]Inco(n+1)=somme(residu)+Vol/dt*Inco(n)
// Typiquement: si Op=flux(Inco) alors la matrice implicite A contient une contribution -dflux/dInco
// Exemple: Op flux convectif en VDF:
// Op=T*u*S et A=-d(T*u*S)/dT=-u*S
  const Discretisation_base::type_calcul_du_residu& type_codage=probleme().discretisation().codage_du_calcul_du_residu();
  if (type_codage==Discretisation_base::VIA_CONTRIBUER_AU_SECOND_MEMBRE)
    {
      if ( probleme().discretisation().que_suis_je() == "EF")
        {
// On calcule somme(residu) par contribuer_au_second_membre (typiquement CL non implicitees)
// Cette approche necessite de coder 3 methodes (contribuer_a_avec, contribuer_au_second_membre et ajouter pour l'explicite)
          sources().contribuer_a_avec(inco,matrice);
          statistiques().end_count(assemblage_sys_counter_,0,0);
          sources().ajouter(resu);
          statistiques().begin_count(assemblage_sys_counter_);
          matrice.ajouter_multvect(inco, resu); //!< Add source residual first
          for (int op = 0; op < nombre_d_operateurs(); op++)
            {
              operateur(op).l_op_base().contribuer_a_avec(inco, matrice);
              operateur(op).l_op_base().contribuer_au_second_membre(resu);
            }
        }
      else
        {
          Cerr << "VIA_CONTRIBUER_AU_SECOND_MEMBRE pas code pour " << que_suis_je() << ":assembler" << finl;
          Cerr << "avec discretisation " <<  probleme().discretisation().que_suis_je() << "" << finl;
          Process::exit();
        }
// // On calcule somme(residu) par contribuer_au_second_membre (typiquement CL non implicitees)
// // Cette approche necessite de coder 3 methodes (contribuer_a_avec, contribuer_au_second_membre et ajouter pour l'explicite)
// sources().contribuer_a_avec(inco,matrice);
// statistiques().end_count(assemblage_sys_counter_,0,0);
// sources().ajouter(resu);
// statistiques().begin_count(assemblage_sys_counter_);
// matrice.ajouter_multvect(inco, resu); // Add source residual first
// for (int op = 0; op < nombre_d_operateurs(); op++)
// {
// operateur(op).l_op_base().contribuer_a_avec(inco, matrice);
// operateur(op).l_op_base().contribuer_au_second_membre(resu);
// }
    }
  else if (type_codage==Discretisation_base::VIA_AJOUTER)
    {
// On calcule somme(residu) par somme(operateur)+sources+A*Inco(n)
// Cette approche necessite de coder seulement deux methodes (contribuer_a_avec et ajouter)
// Donc un peu plus couteux en temps de calcul mais moins de code a ecrire/maintenir
      for (int op=0; op<nombre_d_operateurs(); op++)
        {
          Matrice_Morse mat(matrice);
          mat.get_set_coeff() = 0.0;
          operateur(op).l_op_base().contribuer_a_avec(inco, mat);
          if (op == 1) mat *= rhoCp; //!< la derivee est multipliee par rhoCp pour la convection
          matrice += mat;
          statistiques().end_count(assemblage_sys_counter_, 0, 0);
          {
            DoubleTab resu_tmp(resu);
            resu_tmp = 0.;
            operateur(op).ajouter(inco, resu_tmp);
            if (op == 1) resu_tmp *= rhoCp;
            resu += resu_tmp;
          }
          statistiques().begin_count(assemblage_sys_counter_);
        }
      sources().contribuer_a_avec(inco,matrice);
      statistiques().end_count(assemblage_sys_counter_,0,0);
      sources().ajouter(resu);
      statistiques().begin_count(assemblage_sys_counter_);
      matrice.ajouter_multvect(inco, resu); //!< Ajout de A*Inco(n) PL (11/04/2018): On aimerait bien calculer la contribution des sources en premier comme dans le cas VIA_CONTRIBUER_AU_SECOND_MEMBRE mais le cas Canal_perio_3D (keps periodique plante: il y'a une erreur de periodicite dans les termes sources du modele KEps...
//
//
//
    }
  else
    {
      Cerr << "Unknown value in Equation_base::assembler for " << (int)type_codage << finl;
      Process::exit();
    }
}
References Operateur::ajouter(), Sources::ajouter(), Matrice_Base::ajouter_multvect(), assemblage_sys_counter_, Statistiques::begin_count(), Milieu_base::capacite_calorifique(), Cerr, Discretisation_base::codage_du_calcul_du_residu(), Operateur_base::contribuer_a_avec(), Sources::contribuer_a_avec(), Operateur_base::contribuer_au_second_membre(), Equation_base::discretisation(), Probleme_base::discretisation(), Statistiques::end_count(), Process::exit(), finl, Matrice_Morse::get_set_coeff(), Operateur::l_op_base(), le_fluide, Milieu_base::masse_volumique(), Convection_Diffusion_std::nombre_d_operateurs(), Convection_Diffusion_std::operateur(), Equation_base::probleme(), Objet_U::que_suis_je(), Equation_base::sources(), statistiques(), Operateur_base::tester_contribuer_a_avec(), Champ::valeurs(), Champ_Don::valeurs(), Discretisation_base::VIA_AJOUTER, and Discretisation_base::VIA_CONTRIBUER_AU_SECOND_MEMBRE.
assembler_blocs()
void Convection_Diffusion_Temperature::assembler_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Equation_base.
Definition at line 785 of file Convection_Diffusion_Temperature.cpp.
{
  if (discretisation().que_suis_je().debute_par("PolyMAC"))
    {
      Equation_base::assembler_blocs(matrices, secmem, semi_impl);
      return;
    }
  const double rhoCp = le_fluide->capacite_calorifique().valeurs()(0, 0) * le_fluide->masse_volumique().valeurs()(0, 0);
  /* mise a zero */
  secmem = 0;
  for (auto &&i_m : matrices) i_m.second->get_set_coeff() = 0;
  matrices_t mats2;
  for (auto &&i_m : matrices)
    {
      Matrice_Morse* mat2 = new Matrice_Morse;
      *mat2=*i_m.second;
      mats2[i_m.first] = mat2;
    }
  /* operateurs, sources, masse */
  for (int i = 0; i < nombre_d_operateurs(); i++)
    {
      DoubleTab secmem_tmp(secmem);
      secmem_tmp = 0.;
      for (auto &&i_m : mats2)
        mats2[i_m.first]->get_set_coeff() = 0;
      operateur(i).l_op_base().ajouter_blocs(mats2, secmem_tmp, semi_impl);
      if (i == 1)
        {
          secmem_tmp *= rhoCp;
          for (auto &&i_m : mats2) *i_m.second *= rhoCp;
        }
      for (auto &&i_m : matrices) *i_m.second += *mats2[i_m.first];
      secmem += secmem_tmp;
    }
  statistiques().end_count(assemblage_sys_counter_, 0, 0);
  statistiques().begin_count(source_counter_);
  for (int i = 0; i < les_sources.size(); i++)
    les_sources(i).valeur().ajouter_blocs(matrices, secmem, semi_impl);
  statistiques().end_count(source_counter_);
  statistiques().begin_count(assemblage_sys_counter_);
  const std::string& nom_inco = inconnue().le_nom().getString();
  Matrice_Morse *mat = matrices.count(nom_inco)?matrices.at(nom_inco):NULL;
  if(mat) mat->ajouter_multvect(inconnue().valeurs(), secmem);
  for (auto &&i_m : mats2)
    delete i_m.second;
}
References Operateur_base::ajouter_blocs(), Matrice_Base::ajouter_multvect(), assemblage_sys_counter_, Equation_base::assembler_blocs(), Statistiques::begin_count(), Milieu_base::capacite_calorifique(), Equation_base::discretisation(), Statistiques::end_count(), Nom::getString(), inconnue(), Operateur::l_op_base(), le_fluide, O_U_Ptr::le_nom(), Equation_base::les_sources, Milieu_base::masse_volumique(), Convection_Diffusion_std::nombre_d_operateurs(), Convection_Diffusion_std::operateur(), Objet_U::que_suis_je(), liste::size(), source_counter_, statistiques(), List_Source::valeur(), Champ::valeurs(), and Champ_Don::valeurs().
associer_fluide()
void Convection_Diffusion_Temperature::associer_fluide (const Fluide_base & un_fluide) inline
Associe un fluide incompressible a l'equation.
Definition at line 122 of file Convection_Diffusion_Temperature.h.
{
  le_fluide = un_fluide;
}
References le_fluide.
Referenced by associer_milieu_base().
associer_milieu_base()
void Convection_Diffusion_Temperature::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation,
le milieu est en fait caste en Fluide_base ou en Fluide_Ostwald.
Implements Equation_base.
Definition at line 183 of file Convection_Diffusion_Temperature.cpp.
{
  if (sub_type(Fluide_Ostwald, un_milieu))
    {
      const Fluide_Ostwald& un_fluide = ref_cast(Fluide_Ostwald,un_milieu);
      if  ((un_fluide.conductivite().non_nul()) &&
           ((un_fluide.capacite_calorifique().non_nul()) && (un_fluide.beta_t().non_nul())))
        associer_fluide(un_fluide);
      else
        {
          Cerr << "Vous n'avez pas defini toutes les proprietes physiques du fluide " << finl;
          Cerr << "necessaires pour resoudre l'equation d'energie " << finl;
          Cerr << "Verifier que vous avez defini: la conductivite (lambda)"<< finl;
          Cerr << "                                  la capacite calorifique (Cp)"<< finl;
          Cerr << "                                  le coefficient de dilatation thermique (beta_th)"<< finl;
          exit();
        }
    }
  else if (sub_type(Fluide_base,un_milieu))
    {
      const Fluide_base& un_fluide = ref_cast(Fluide_base,un_milieu);
      if  ((un_fluide.conductivite().non_nul()) &&
           ((un_fluide.capacite_calorifique().non_nul()) && (un_fluide.beta_t().non_nul())))
        associer_fluide(un_fluide);
      else
        {
          Cerr << "Vous n'avez pas defini toutes les proprietes physiques du fluide " << finl;
          Cerr << "necessaires pour resoudre l'equation d'energie " << finl;
          Cerr << "Verifier que vous avez defini: la conductivite (lambda)"<< finl;
          Cerr << "                                  la capacite calorifique (Cp)"<< finl;
          Cerr << "                                  le coefficient de dilatation thermique (beta_th)"<< finl;
          exit();
        }
    }
  else
    {
      if (Process::je_suis_maitre())
        Cerr << "le fluide considere n'est un sous fluide de Fluide_base, \n"
             << "ni un sous fluide de Fluide_Ostwald. " << finl;
    }
}
References associer_fluide(), Milieu_base::beta_t(), Milieu_base::capacite_calorifique(), Cerr, Milieu_base::conductivite(), Process::exit(), finl, Process::je_suis_maitre(), O_U_Ptr::non_nul(), ref_cast, and sub_type.
Referenced by Pb_Thermohydraulique::associer_milieu_base(), and Pb_Thermohydraulique_Concentration::associer_milieu_base().
calcul_indic_pena_global()
void Convection_Diffusion_Temperature::calcul_indic_pena_global (IntTab & indicatrice_totale, IntTab & indicatrice_face_totale) protected
Definition at line 1141 of file Convection_Diffusion_Temperature.cpp.
{
// fonction characteristique globale ibc penalisees
  indicatrice_totale.copy(indic_pena_global);
  indicatrice_face_totale.copy(indic_face_pena_global);
  indicatrice_totale = 0;
  indicatrice_face_totale = 0;
  int x=0;
  int xf=0;
  const int nb_elem  = indicatrice_totale.dimension_tot(0);
  const int nfaces = indicatrice_face_totale.dimension_tot(0);
// boucle sur les ibc
  for ( int w = 0 ; w<ref_penalisation_L2_FTD.size() ; ++w)
    {
      Transport_Interfaces_base& nom_eq = ref_cast(Transport_Interfaces_base,ref_penalisation_L2_FTD[w].valeur());
      const DoubleTab& indicatrice = nom_eq.get_update_indicatrice().valeurs();
// fonction characteristique (0 ou 1) pour l'ensemble des ibc
      for (int k_elem =0 ; k_elem <nb_elem; ++k_elem)
        {
          if (indicatrice(k_elem)>0.)
            {
              if(indicatrice_totale(k_elem) != 0)
                {
                  Cerr<<"calcul_indic_pena_global : Attention: les elements des indicatrices se chevauchent "<<finl;
                  exit();
                }
              indicatrice_totale(k_elem) = w+1;
              ++x;
            }
        }
// fonction characteristique (numero ibc) pour l'ensemble des ibc
      const Zone_VF& zone_vf = ref_cast(Zone_VF, zone_dis().valeur());
      const IntTab& face_voisins = zone_vf.face_voisins();
      for (int i = 0; i < nfaces ; i++)
        {
          const int elem0 = face_voisins(i, 0);
          const int elem1 = face_voisins(i, 1);
          double indi = 0.;
          if (elem0 >= 0) indi = indicatrice(elem0);
          if (elem1 >= 0) indi += indicatrice(elem1);
          if(indi > 0.)
            {
              if(indicatrice_face_totale(i) !=  0)
                {
                  Cerr<<"calcul_indic_pena_global : Attention: les faces des indicatrices se chevauchent "<<finl;
                  exit();
                }
              indicatrice_face_totale(i) = w+1;
              ++xf;
            }
        }
    }
  Cout<<"Calcul_indic_pena_global : Nb d elements de l indicatrice globale des IBCs: "<<x;
  Cout<<"  et nb de faces : "<<xf<<finl;
  indicatrice_totale.echange_espace_virtuel();
  indicatrice_face_totale.echange_espace_virtuel();
// Debog::verifier("Convection_Diffusion_Temperature::calcul_indic_pena_global indicatrice_totale ",indicatrice_totale);
// Debog::verifier("Convection_Diffusion_Temperature::calcul_indic_pena_global indicatrice_face_totale ",indicatrice_face_totale);
}
References Cerr, TRUSTTab< _TYPE_ >::copy(), Cout, TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), Zone_VF::face_voisins(), finl, Transport_Interfaces_base::get_update_indicatrice(), indic_face_pena_global, indic_pena_global, ref_cast, ref_penalisation_L2_FTD, vect_impl::size(), valeur(), Champ_Proto::valeurs(), and Equation_base::zone_dis().
Referenced by mise_en_place_zone_fantome(), and set_indic_pena_globale().
cree_instance()
Objet_U * Convection_Diffusion_Temperature::cree_instance () static
Definition at line 36 of file Convection_Diffusion_Temperature.cpp.
creer_champ()
void Convection_Diffusion_Temperature::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Equation_base.
Definition at line 392 of file Convection_Diffusion_Temperature.cpp.
{
  Convection_Diffusion_std::creer_champ(motlu);
  Motcle nom_mot(motlu),temp_mot(nom_mot);
  /*  if (motlu == "temperature_paroi")
      {
        if (!temperature_paroi.non_nul())
          {
            const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
            dis.t_paroi(zone_dis(),zone_Cl_dis(),*this,temperature_paroi);
            champs_compris_.ajoute_champ(temperature_paroi);
          }
      } */
  if (motlu == "gradient_temperature")
    {
      if (!gradient_temperature.non_nul())
        {
          const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
          dis.grad_T(zone_dis(),zone_Cl_dis(),la_temperature,gradient_temperature);
          champs_compris_.ajoute_champ(gradient_temperature);
        }
    }
  if (nom_mot.debute_par("H_ECHANGE"))
    {
      if (!h_echange.non_nul())
        {
          const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
          temp_mot.suffix("H_ECHANGE_");
          int temperature;
          string2int(temp_mot,temperature);
          dis.h_conv(zone_dis(),zone_Cl_dis(),la_temperature,h_echange,nom_mot,temperature);
          champs_compris_.ajoute_champ(h_echange);
        }
    }
}
References Champs_compris::ajoute_champ(), Equation_base::champs_compris_, Equation_base::creer_champ(), Equation_base::discretisation(), Discret_Thyd::grad_T(), gradient_temperature, Discret_Thyd::h_conv(), h_echange, la_temperature, O_U_Ptr::non_nul(), ref_cast, string2int(), Nom::suffix(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
derivee_en_temps_inco()
DoubleTab & Convection_Diffusion_Temperature::derivee_en_temps_inco (DoubleTab & derivee) override virtual
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
< Change secmem for some schemes (eg: Adams_Bashforth)
< Change secmem for some schemes (eg: Adams_Bashforth)
< Add specific term for an equation (eg: -gradP for Navier Stokes)
< M-1 * secmem
< Solve specific implicit term for an equation (eg: pressure for Navier Stokes)
Reimplemented from Equation_base.
Definition at line 497 of file Convection_Diffusion_Temperature.cpp.
{
  if (!is_penalized)
    {
      return derivee_en_temps_inco_eq_base(derivee);
    }
  else
    {
      const double rhoCp = le_fluide->capacite_calorifique().valeurs()(0, 0) * le_fluide->masse_volumique().valeurs()(0, 0);
// Specific code if temperature equation is penalized
      derivee=inconnue().valeurs();
// Mise en place d'une methode de mise en place d'une zone fantome
      mise_en_place_zone_fantome(derivee);
      DoubleTab& inc=inconnue().valeurs();
      inc = derivee;
      DoubleTrav secmem(derivee);
      if (nombre_d_operateurs()>1)
        {
          derivee_en_temps_conv(secmem, derivee);
          secmem *= rhoCp;
        }
// Transport des ibcs et de la couche limite
      DoubleTrav secmem_conv_vr(derivee);
// on advecte la variable avec la vitesse ibc
      transport_ibc(secmem_conv_vr, derivee);
// on retranche cette advection
      secmem -= secmem_conv_vr;
      DoubleTab derivee_conv;
      derivee_conv.copy(secmem, Array_base::COPY_INIT);
      les_sources.ajouter(secmem);
      filtrage_si_appart_ibc(derivee_conv,secmem);
      secmem.echange_espace_virtuel();
      if (calculate_time_derivative())
        {
// Store dI/dt(n) = M-1 secmem :
          derivee_en_temps().valeurs()=secmem;
          solveur_masse.appliquer(derivee_en_temps().valeurs());
          schema_temps().modifier_second_membre((*this),secmem); //!< Change secmem for some schemes (eg: Adams_Bashforth)
        }
      solveur_masse.appliquer(secmem);
      Equation_base::Gradient_conjugue_diff_impl(secmem, derivee);
// penalisation de la temperature
      penalisation_L2(derivee);
      return derivee;
    }
}
References Sources::ajouter(), Solveur_Masse::appliquer(), Equation_base::calculate_time_derivative(), Milieu_base::capacite_calorifique(), TRUSTTab< _TYPE_ >::copy(), Array_base::COPY_INIT, Equation_base::derivee_en_temps(), Equation_base::derivee_en_temps_conv(), derivee_en_temps_inco_eq_base(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), filtrage_si_appart_ibc(), Equation_base::Gradient_conjugue_diff_impl(), inconnue(), is_penalized, le_fluide, Equation_base::les_sources, Milieu_base::masse_volumique(), mise_en_place_zone_fantome(), Schema_Temps_base::modifier_second_membre(), Convection_Diffusion_std::nombre_d_operateurs(), penalisation_L2(), Equation_base::schema_temps(), Equation_base::solveur_masse, transport_ibc(), Champ::valeurs(), Champ_Don::valeurs(), and Champ_Inc::valeurs().
derivee_en_temps_inco_eq_base()
DoubleTab & Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base (DoubleTab & derivee)
< Change secmem for some schemes (eg: Adams_Bashforth)
< Add specific term for an equation (eg: -gradP for Navier Stokes)
< M-1 * secmem
< Solve specific implicit term for an equation (eg: pressure for Navier Stokes)
Definition at line 553 of file Convection_Diffusion_Temperature.cpp.
{
  derivee=0;
  DoubleTrav secmem(derivee);
  const double rhoCp = le_fluide->capacite_calorifique().valeurs()(0, 0) * le_fluide->masse_volumique().valeurs()(0, 0);
// secmem = sum(operators) + sources + equation specific terms
  if (schema_temps().diffusion_implicite())
    {
// Add convection operator only if equation has one
      derivee = inconnue().valeurs();
      if (nombre_d_operateurs()>1)
        {
          derivee_en_temps_conv(secmem, derivee);
          secmem *= rhoCp;
        }
    }
  else
    {
// Add all explicit operators
      for(int i=0; i<nombre_d_operateurs(); i++)
        if(operateur(i).l_op_base().get_decal_temps()!=1)
          {
            DoubleTrav secmem_tmp(secmem);
            operateur(i).ajouter(secmem_tmp);
            if (i == 1) secmem_tmp *= rhoCp;
            secmem += secmem_tmp;
          }
    }
  les_sources.ajouter(secmem);
  if (calculate_time_derivative())
    {
// Store dI/dt(n) = M-1 secmem :
      derivee_en_temps().valeurs()=secmem;
      solveur_masse.appliquer(derivee_en_temps().valeurs());
      schema_temps().modifier_second_membre((*this),secmem); //!< Change secmem for some schemes (eg: Adams_Bashforth)
    }
  corriger_derivee_expl(secmem); //!< Add specific term for an equation (eg: -gradP for Navier Stokes)
  if (implicite_==0)
    {
      solveur_masse.appliquer(secmem); //!< M-1 * secmem
      if (schema_temps().diffusion_implicite())
        {
// Solve: (1/dt + M-1*A)*dI = M-1 * secmem
// where A is the diffusion
          Equation_base::Gradient_conjugue_diff_impl(secmem, derivee);
        }
      else
        {
          derivee = secmem;
          derivee.echange_espace_virtuel();
        }
      corriger_derivee_impl(derivee);  //!< Solve specific implicit term for an equation (eg: pressure for Navier Stokes)
    }
  else if (implicite_>0)
    {
// TRUST support notices that this part has never been covered...
// implicite
// M dU/dt + AU* = f -BUn;
// U* = Un+dt dU/dt
// (M/dt + A) U* = f -BUn + M/dt Un
//
      double dt=schema_temps().pas_de_temps();
      for(int i=0; i<nombre_d_operateurs(); i++)
        {
// boucle sur les operateurs
          Operateur_base& op=operateur(i).l_op_base();
          if(!op.get_matrice().non_nul())
            op.set_matrice().typer("Matrice_Morse");
          if(op.get_decal_temps()==1)
            {
// if (op.set_matrice().valeur().nb_lignes()<2)
              {
                Matrice_Morse& matrice=ref_cast(Matrice_Morse,op.set_matrice().valeur());
                op.dimensionner(matrice);
                sys_invariant_=0;
              }
              if(!sys_invariant_)
                {
                  Matrice_Morse& matrice=ref_cast(Matrice_Morse, op.set_matrice().valeur());
                  op.contribuer_a_avec(inconnue().valeurs(), matrice);
                  solv_masse().ajouter_masse(dt, op.set_matrice().valeur());
                  if(
                    (op.get_solveur()->que_suis_je()=="Solv_Cholesky")
                    ||
                    (op.get_solveur()->que_suis_je()=="Solv_GCP")
                  )
                    {
                      Matrice_Morse_Sym new_mat(matrice);
                      new_mat.set_est_definie(1);
                      op.set_matrice()=new_mat;
                      ref_cast_non_const(SolveurSys,op.get_solveur())->reinit();
                    }
                }
            }
        }
      if(implicite_==1)
        {
// Un seul operateur implicite.
// On suppose que c'est le premier (la diffusion !!)
          Operateur_base& op=operateur(0).l_op_base();
          Matrice_Base& matrice=op.set_matrice().valeur();
// DoubleTrav secmem(derivee);
          secmem=derivee;
          solv_masse().ajouter_masse(dt, secmem, inconnue().valeurs());
          op.contribuer_au_second_membre(secmem );
          op.set_solveur().resoudre_systeme(matrice,
                                            secmem,
                                            derivee
                                           );
          solv_masse().corriger_solution(derivee,inconnue().valeurs());
          derivee-=inconnue().valeurs();
          derivee/=dt;
// Sert uniquement a calculer les flux sur les bords quand la diffusion est implicitee !
          DoubleTab resu;
          resu=derivee;
          operateur(0).calculer(inconnue().valeurs(), resu);
        }
      else
        {
// plusieurs operateurs implicites ...
          Cerr << "Must be coded ... " << finl;
          exit();
        }
    }
  else
    {
      Cerr << "Error in Equation_base::derivee_en_temps_inco" << finl;
      Cerr << "implicite_ = " << implicite_ << " has not been initialized!" << finl;
      Cerr << "May be " << que_suis_je() << "::completer() method doesn't call Equation_base::completer()" << finl;
      Cerr << "Contact TRUST support." << finl;
      Process::exit();
    }
  return derivee;
}
References Operateur::ajouter(), Sources::ajouter(), Solveur_Masse::ajouter_masse(), Solveur_Masse::appliquer(), Equation_base::calculate_time_derivative(), Operateur::calculer(), Milieu_base::capacite_calorifique(), Cerr, Operateur_base::contribuer_a_avec(), Operateur_base::contribuer_au_second_membre(), Equation_base::corriger_derivee_expl(), Equation_base::corriger_derivee_impl(), Solveur_Masse::corriger_solution(), Equation_base::derivee_en_temps(), Equation_base::derivee_en_temps_conv(), Schema_Temps_base::diffusion_implicite(), Operateur_base::dimensionner(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, Operateur_base::get_decal_temps(), Operateur_base::get_matrice(), Operateur_base::get_solveur(), Equation_base::Gradient_conjugue_diff_impl(), Equation_base::implicite_, inconnue(), Operateur::l_op_base(), le_fluide, Equation_base::les_sources, Milieu_base::masse_volumique(), Schema_Temps_base::modifier_second_membre(), Convection_Diffusion_std::nombre_d_operateurs(), O_U_Ptr::non_nul(), Convection_Diffusion_std::operateur(), Schema_Temps_base::pas_de_temps(), Objet_U::que_suis_je(), ref_cast, ref_cast_non_const, SolveurSys::resoudre_systeme(), Equation_base::schema_temps(), Matrice_Sym::set_est_definie(), Operateur_base::set_matrice(), Operateur_base::set_solveur(), Equation_base::solv_masse(), Equation_base::solveur_masse, Equation_base::sys_invariant_, Deriv_::typer(), Deriv_Matrice_Base::valeur(), Champ::valeurs(), Champ_Don::valeurs(), and Champ_Inc::valeurs().
Referenced by derivee_en_temps_inco().
diffusivite_pour_pas_de_temps()
const Champ_base & Convection_Diffusion_Temperature::diffusivite_pour_pas_de_temps () const override virtual
Reimplemented from Convection_Diffusion_std.
Definition at line 1524 of file Convection_Diffusion_Temperature.cpp.
{
  return milieu().diffusivite();
}
References Milieu_base::diffusivite(), and milieu().
diffusivite_pour_transport()
const Champ_Don & Convection_Diffusion_Temperature::diffusivite_pour_transport () const override virtual
Reimplemented from Convection_Diffusion_std.
Definition at line 1519 of file Convection_Diffusion_Temperature.cpp.
{
  return milieu().conductivite();
}
References Milieu_base::conductivite(), and milieu().
discretiser()
void Convection_Diffusion_Temperature::discretiser () override virtual
Discretise l'equation.
Reimplemented from Equation_base.
Definition at line 241 of file Convection_Diffusion_Temperature.cpp.
{
  const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
  if (Process::je_suis_maitre())
    Cerr << "Energy equation discretization" << finl;
  dis.temperature(schema_temps(), zone_dis(), la_temperature);
  champs_compris_.ajoute_champ(la_temperature);
  Equation_base::discretiser();
  if (Process::je_suis_maitre())
    Cerr << "Convection_Diffusion_Temperature::discretiser() ok" << finl;
}
References Champs_compris::ajoute_champ(), Cerr, Equation_base::champs_compris_, Equation_base::discretisation(), Equation_base::discretiser(), finl, Process::je_suis_maitre(), la_temperature, ref_cast, Equation_base::schema_temps(), Discret_Thermique::temperature(), and Equation_base::zone_dis().
domaine_application()
const Motcle & Convection_Diffusion_Temperature::domaine_application () const override virtual
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
Returns
Motcle&
Signification: le nom du domaine d'application de l'equation
Contraintes: toujours egal a "Thermique"
Reimplemented from Equation_base.
Definition at line 491 of file Convection_Diffusion_Temperature.cpp.
{
  static Motcle domaine = "Thermique";
  return domaine;
}
duplique()
int Convection_Diffusion_Temperature::duplique () const override virtual
Implements Objet_U.
Definition at line 36 of file Convection_Diffusion_Temperature.cpp.
ecrire_fichier_pena_th()
void Convection_Diffusion_Temperature::ecrire_fichier_pena_th (DoubleTab & u_old, DoubleTab & u, DoubleTab & tref, DoubleTab & denom) protected
Definition at line 1399 of file Convection_Diffusion_Temperature.cpp.
{
  if (le_schema_en_temps->limpr())
    {
      const Zone_VF& zone_vf = ref_cast(Zone_VF, zone_dis().valeur());
      const DoubleVect& vol_maille = zone_vf.volumes();
      const Fluide_base& fluide_inc = ref_cast(Fluide_base, milieu());
      const DoubleTab& tab_rho = fluide_inc.masse_volumique().valeurs();
      const double rho = tab_rho(0,0);
      const DoubleTab& tab_cp = fluide_inc.capacite_calorifique().valeur().valeurs();
      const double cp = tab_cp(0,0);
// Methode pour calculer le flux total sur les ibc
// Calcul de T_n+1 apres penalisation
      const DoubleTab& inc=inconnue().valeurs();
      const int nb_elem  = u.dimension(0);
      const double dt = schema_temps().pas_de_temps();
      DoubleTab tkp1(inc);
      for (int k = 0 ; k<nb_elem ; ++k) tkp1(k) += u(k)*dt;
// Terme de penalisation:       Sigma_ibc Ksi_ibc * (T_n+1 - Tref_ibc) / eta
      DoubleTrav F(inc);
      for (int j = 0; j<nb_elem; ++j)  F(j) = (tref(j)-denom(j)*tkp1(j))/eta;
// boucle sur les IBC
      DoubleTrav filtre(nb_elem);
      DoubleTrav filtre_glob(nb_elem);
      const double temps_flux = le_schema_en_temps->temps_courant();
      Nom espace=" \t";
      for ( int i = 0 ; i < ref_penalisation_L2_FTD.size() ; ++i) //boucle sur le nombre d'ibc
        {
          Transport_Interfaces_base& nom_eq = ref_cast(Transport_Interfaces_base,ref_penalisation_L2_FTD[i].valeur());
          const DoubleTab& indicatrice = nom_eq.get_update_indicatrice().valeurs();
          double Flux_pena= 0.;
          double Flux_pena_old= 0.;
          double Flux_temp_interne= 0.;
// Filtre ibc (1) / non ibc (0)
          filtre = 0.;
          for ( int j = 0 ; j<nb_elem ; ++j)
            {
              if (indicatrice(j) > 0.)
                {
                  filtre(j) = 1.;
                  filtre_glob(j)=1.;
                }
// bilans
// Attention rho et cp constants
              Flux_pena_old += u_old(j) * filtre(j) *rho *cp *vol_maille(j);
              Flux_pena += F(j) * filtre(j) * vol_maille(j) *rho *cp;
              Flux_temp_interne += filtre(j)*rho*cp*vol_maille(j)*u(j);
            }
// Ajout des differents processeurs en //
          Flux_pena_old = mp_sum(Flux_pena_old);
          Flux_pena = mp_sum(Flux_pena);
          Flux_temp_interne = mp_sum(Flux_temp_interne);
// ecriture
          if (Process::je_suis_maitre())
            {
              SFichier FTE;
              ouvrir_fichier_pena_th(FTE,"Puissance_penalisation_thermique_ibc",1,nom_eq);
              FTE << temps_flux;
              FTE << espace << Flux_pena;
              FTE << finl;
              SFichier FTI;
              ouvrir_fichier_pena_th(FTI,"Puissance_thermique_ibc",1,nom_eq);
              FTI << temps_flux;
              FTI << espace << Flux_pena_old;
              FTI << finl;
              SFichier FTTI;
              ouvrir_fichier_pena_th(FTTI,"Derivee_temps_temperature_ibc",1,nom_eq);
              FTTI << temps_flux;
              FTTI << espace << Flux_temp_interne;
              FTTI << finl;
            }
        }
// bilan Derivee_temps_temperature_fluide
// Attention rho et cp constants
      double Flux_temp_externe= 0.;
      for (int j = 0; j<nb_elem; ++j)
        {
          Flux_temp_externe += (1.-filtre_glob(j))  *rho *cp *vol_maille(j) * u(j); //fluide
        }
// Ajout des differents processeurs en //
      Flux_temp_externe = mp_sum(Flux_temp_externe); //fluide
// ecriture
      if (Process::je_suis_maitre())
        {
          SFichier fichier;
          Nom fichier_nom=Objet_U::nom_du_cas();
          fichier_nom+="_";
          fichier_nom+="Derivee_temps_temperature_fluide.out";
          if (le_schema_en_temps->nb_impr()==1 && !probleme().reprise_effectuee())
            {
              fichier.ouvrir(fichier_nom);
            }
          else
            {
              fichier.ouvrir(fichier_nom,ios::app);
            }
// if (fichier)
          {
            (fichier) <<temps_flux<<" \t"<<Flux_temp_externe<<finl;
          }
        }
    }
}
References Milieu_base::capacite_calorifique(), TRUSTTab< _TYPE_ >::dimension(), eta, finl, Transport_Interfaces_base::get_update_indicatrice(), inconnue(), Process::je_suis_maitre(), Equation_base::le_schema_en_temps, Schema_Temps_base::limpr(), Milieu_base::masse_volumique(), milieu(), Process::mp_sum(), Schema_Temps_base::nb_impr(), Objet_U::nom_du_cas(), Sortie_Fichier_base::ouvrir(), ouvrir_fichier_pena_th(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), ref_cast, ref_penalisation_L2_FTD, Equation_base::schema_temps(), vect_impl::size(), Schema_Temps_base::temps_courant(), Deriv_Champ_Don_base::valeur(), valeur(), Champ::valeurs(), Champ_Don_base::valeurs(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), Zone_VF::volumes(), and Equation_base::zone_dis().
Referenced by penalisation_L2().
filtrage_si_appart_ibc()
DoubleTab & Convection_Diffusion_Temperature::filtrage_si_appart_ibc (DoubleTab & u_conv, DoubleTab & u) protected
Definition at line 1127 of file Convection_Diffusion_Temperature.cpp.
{
// caclul de la fonction caracteristique globale des ibc pour le calcul de T_voisinage
  set_indic_pena_globale();
  for (int j = 0 ; j< indic_pena_global.size() ; ++j)
    {
      if ( indic_pena_global(j) != 0) u(j) = u_conv(j);
    }
  u.echange_espace_virtuel();
// Debog::verifier("Convection_Diffusion_Temperature::filtrage_si_appart_ibc u ",u);
  return u;
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), indic_pena_global, set_indic_pena_globale(), and TRUSTVect< _TYPE_ >::size().
Referenced by derivee_en_temps_inco().
fluide() [1/2]
Fluide_base & Convection_Diffusion_Temperature::fluide ()
Renvoie le fluide incompressible associe a l'equation.
Returns
Fluide_base&
Signification: le fluide incompressible associe a l'equation
Contraintes:
Definition at line 339 of file Convection_Diffusion_Temperature.cpp.
{
  if(!le_fluide.non_nul())
    {
      Cerr << "A fluid has not been associated to"
           << "the Convection_Diffusion_Temperature equation" << finl;
      exit();
    }
  return le_fluide.valeur();
}
References Cerr, Process::exit(), finl, le_fluide, O_U_Ptr::non_nul(), and Ref_Fluide_base::valeur().
fluide() [2/2]
const Fluide_base & Convection_Diffusion_Temperature::fluide () const
Renvoie le fluide incompressible associe a l'equation.
(version const)
Returns
Fluide_base&
Signification: le fluide incompressible associe a l'equation
Contraintes: reference constante
Definition at line 313 of file Convection_Diffusion_Temperature.cpp.
{
  if(!le_fluide.non_nul())
    {
      Cerr << "A fluid has not been associated to "
           << "the Convection_Diffusion_Temperature equation" << finl;
      exit();
    }
  return le_fluide.valeur();
}
References Cerr, Process::exit(), finl, le_fluide, O_U_Ptr::non_nul(), and Ref_Fluide_base::valeur().
Referenced by Terme_Source_inc_th_VDF_Face::associer_pb(), and milieu().
get_champ()
const Champ_base & Convection_Diffusion_Temperature::get_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
Definition at line 429 of file Convection_Diffusion_Temperature.cpp.
{
  /*  if (nom=="temperature_paroi")
      {
        double temps_init = schema_temps().temps_init();
        Champ_Fonc_base& ch_tp=ref_cast_non_const(Champ_Fonc_base,temperature_paroi.valeur());
        if (((ch_tp.temps()!=la_temperature->temps()) || (ch_tp.temps()==temps_init)) && ((la_temperature->mon_equation_non_nul())))
          ch_tp.mettre_a_jour(la_temperature->temps());
        return champs_compris_.get_champ(nom);
      } */
  if (nom=="gradient_temperature")
    {
      double temps_init = schema_temps().temps_init();
      Champ_Fonc_base& ch_gt=ref_cast_non_const(Champ_Fonc_base,gradient_temperature.valeur());
      if (((ch_gt.temps()!=la_temperature->temps()) || (ch_gt.temps()==temps_init)) && (la_temperature->mon_equation_non_nul()))
        ch_gt.mettre_a_jour(la_temperature->temps());
      return champs_compris_.get_champ(nom);
    }
  if (h_echange.non_nul())
    if (nom==h_echange.valeur().le_nom())
      {
        double temps_init = schema_temps().temps_init();
        Champ_Fonc_base& ch_hconv=ref_cast_non_const(Champ_Fonc_base,h_echange.valeur());
        if (((ch_hconv.temps()!=la_temperature->temps()) || (ch_hconv.temps()==temps_init)) && (la_temperature->mon_equation_non_nul()))
          {
            ch_hconv.mettre_a_jour(la_temperature->temps());
          }
        return champs_compris_.get_champ(nom);
      }
  try
    {
      return Convection_Diffusion_std::get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  throw Champs_compris_erreur();
  REF(Champ_base) ref_champ;
  return ref_champ;
}
References Equation_base::champs_compris_, Champs_compris::get_champ(), Equation_base::get_champ(), gradient_temperature, h_echange, la_temperature, Field_base::le_nom(), Champ_Fonc_base::mettre_a_jour(), O_U_Ptr::non_nul(), REF, ref_cast_non_const, Equation_base::schema_temps(), Champ_base::temps(), Champ_Inc::temps(), Schema_Temps_base::temps_init(), and Deriv_Champ_Fonc_base::valeur().
get_info()
const Type_info * Convection_Diffusion_Temperature::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_std.
Definition at line 36 of file Convection_Diffusion_Temperature.cpp.
impr()
int Convection_Diffusion_Temperature::impr (Sortie & os) const override virtual
Impression des flux sur les bords sur un flot de sortie.
Appelle Equation_base::impr(Sortie&)
Returns
int
Signification: code de retour propage
Contraintes:
Reimplemented from Equation_base.
Definition at line 365 of file Convection_Diffusion_Temperature.cpp.
{
  return Equation_base::impr(os);
}
References Equation_base::impr().
inconnue() [1/2]
const Champ_Inc & Convection_Diffusion_Temperature::inconnue () const inline override virtual
Renvoie le champ inconnue representant la temperatue.
(version const)
Returns
Champ_Inc&
Signification: le champ inconnue representant la temperatue
Contraintes: reference constante
Implements Convection_Diffusion_std.
Definition at line 143 of file Convection_Diffusion_Temperature.h.
{
  return la_temperature;
}
References la_temperature.
Referenced by Terme_Source_inc_th_VDF_Face::ajouter_blocs(), assembler_blocs(), derivee_en_temps_inco(), derivee_en_temps_inco_eq_base(), ecrire_fichier_pena_th(), penalisation_L2(), and readOn().
inconnue() [2/2]
Champ_Inc & Convection_Diffusion_Temperature::inconnue () inline override virtual
Renvoie le champ inconnue representant la temperatue.
Returns
Champ_Inc&
Signification: le champ inconnue representant la temperatue
Contraintes:
Implements Convection_Diffusion_std.
Definition at line 163 of file Convection_Diffusion_Temperature.h.
{
  return la_temperature;
}
References la_temperature.
info()
const Type_info * Convection_Diffusion_Temperature::info () static
Definition at line 36 of file Convection_Diffusion_Temperature.cpp.
lire_motcle_non_standard()
int Convection_Diffusion_Temperature::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Convection_Diffusion_std.
Definition at line 117 of file Convection_Diffusion_Temperature.cpp.
{
  if (un_mot=="penalisation_L2_FTD")
    {
      is_penalized = 1;
      eta = 1.e-12;
      Cerr << " Equation_base :: penalisation_L2_FTD" << finl;
      Cerr << "Equation_base: modele penalisation ibc = "<< choix_pena << finl;
      Nom mot, nom_equation;
      int dim;
      is >> mot;
      Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
      if (mot == accolade_ouverte)
        {
          is >> mot;
          while (mot != accolade_fermee)
            {
              nom_equation = mot;
              Cerr << "penalisation_L2_FTD equation: "<< nom_equation << finl;
              const Transport_Interfaces_base& eq = ref_cast(Transport_Interfaces_base,probleme().get_equation_by_name(nom_equation));
              ref_penalisation_L2_FTD.add(eq);
              is >> dim;
              DoubleTab tab = DoubleTab();
              tab.resize(dim);
              for ( int i = 0 ; i<dim ; i++)
                {
                  is >> tab(i);
                  Cerr << "Lecture de la valeur de la penalisation suivant la direction " << i+1 <<" :" << tab(i) << finl;
                }
              tab_penalisation_L2_FTD.add(tab);
              is >> mot ;
            }
        }
      else
        {
          Cerr << "Erreur a la lecture des parametres de la penalisation L2 " << finl;
          Cerr << "On attendait : " << accolade_ouverte << finl;
          exit();
        }
      const Zone_VF& zone_vf = ref_cast(Zone_VF, zone_dis().valeur());
      zone_vf.zone().creer_tableau_elements(indic_pena_global);
      zone_vf.creer_tableau_faces(indic_face_pena_global);
    }
  else
    return Convection_Diffusion_std::lire_motcle_non_standard(un_mot,is);
  return 1;
}
References TRUST_Vector< _TRUST_TABL_, _TYPE_ >::add(), Vect_RefObjU::add(), Cerr, choix_pena, Zone::creer_tableau_elements(), Zone_VF::creer_tableau_faces(), eta, Process::exit(), finl, indic_face_pena_global, indic_pena_global, is_penalized, Convection_Diffusion_std::lire_motcle_non_standard(), Equation_base::probleme(), ref_cast, ref_penalisation_L2_FTD, TRUSTTab< _TYPE_ >::resize(), tab_penalisation_L2_FTD, valeur(), Zone_dis_base::zone(), and Equation_base::zone_dis().
milieu() [1/2]
const Milieu_base & Convection_Diffusion_Temperature::milieu () const override virtual
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
(version const)
Returns
Milieu_base&
Signification: le Fluide_base upcaste en Milieu_base
Contraintes: reference constante
Implements Equation_base.
Definition at line 271 of file Convection_Diffusion_Temperature.cpp.
{
  return fluide();
}
References fluide().
Referenced by diffusivite_pour_pas_de_temps(), diffusivite_pour_transport(), and ecrire_fichier_pena_th().
milieu() [2/2]
Milieu_base & Convection_Diffusion_Temperature::milieu () override virtual
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
Returns
Milieu_base&
Signification: le Fluide_base upcaste en Milieu_base
Contraintes:
Implements Equation_base.
Definition at line 292 of file Convection_Diffusion_Temperature.cpp.
{
  return fluide();
}
References fluide().
mise_a_jour_tag_indicatrice_pena_glob()
int Convection_Diffusion_Temperature::mise_a_jour_tag_indicatrice_pena_glob () protected
Definition at line 856 of file Convection_Diffusion_Temperature.cpp.
{
// Les ibcs ont elles ete modifiees ?
  int maj = 0;
  int tag_all = 0;
  for ( int w = 0; w<ref_penalisation_L2_FTD.size() ; ++w)
    {
      Transport_Interfaces_base& nom_eq = ref_cast(Transport_Interfaces_base,ref_penalisation_L2_FTD[w].valeur());
      tag_all += nom_eq.get_mesh_tag();
    }
  if (tag_all != tag_indic_pena_global)
    {
      tag_indic_pena_global = tag_all;
      maj = 1;
    }
  return maj;
}
References Transport_Interfaces_base::get_mesh_tag(), ref_cast, ref_penalisation_L2_FTD, vect_impl::size(), tag_indic_pena_global, and valeur().
Referenced by mise_en_place_zone_fantome(), and set_indic_pena_globale().
mise_en_place_zone_fantome()
void Convection_Diffusion_Temperature::mise_en_place_zone_fantome (DoubleTab & solution) protected
< le voisin existe
< strictement fluide aux deux pas de temps
< On sauve le numero du voisin
< le voisin existe et pas i_elem
< strictement fluide aux deux pas de temps
< le voisin existe
< On sauve le numero du voisin
< le voisin existe et pas i_elem
< strictement ibc aux deux pas de temps (la meme) car solution a ete modifiee ci-dessus
Definition at line 968 of file Convection_Diffusion_Temperature.cpp.
{
  int maj = verifier_tag_indicatrice_pena_glob();
  if (maj == 1) return;
// garde-fou
  if (schema_temps().facteur_securite_pas() > 1.0)
    {
      Cerr << "Convection_Diffusion_Temperature::mise_en_place_zone_fantome Facteur securite doit etre <= 1"<<finl;
      exit();
    }
// fonction characteristique globale ibc penalisees actuelle
  IntTrav indicatrice_totale;
  IntTrav indicatrice_face_totale ;
  calcul_indic_pena_global(indicatrice_totale,indicatrice_face_totale);
// etat des lieux actuel
  const int nb_elem  = indicatrice_totale.dimension(0);
  int x=0;
  int j=0;
  for (int k_elem =0 ; k_elem <nb_elem; ++k_elem)  ((indicatrice_totale(k_elem)!=0) ? ++x : ++j);
// traitement cellules fantomes (if any)
  const Zone_VF& zone_vf = ref_cast(Zone_VF, zone_dis().valeur());
  const IntTab& elem_faces = zone_vf.elem_faces();
  const IntTab& faces_elem = zone_vf.face_voisins();
  const int nb_faces_elem = elem_faces.dimension(1);
  int k=0; //nb cellules fantomes ibc -> fluide
  int k_cor=0; //nb cellules fantomes (ibc -> fluide) corrigees
  int k_cor2=0; //nb cellules fantomes (fluide -> ibc) corrigees
  int u=0; //nb cellules fluide -> ibc
  for (int i_elem = 0; i_elem < nb_elem; i_elem++)
    {
// cellules fantomes (actuellement fluide et precedement ibc) => on modifie solution
      double somme_inc = 0.;
      double coeff = 0.;
      if (indic_pena_global(i_elem) != 0 && indicatrice_totale(i_elem) == 0)
        {
          ++k;
// boucle sur les faces pour determiner la valeur de la variable pour les cellules voisines strictement fluide
          IntTrav stok_vois(nb_faces_elem);
          for (int i_face = 0; i_face < nb_faces_elem; i_face++)
            {
              const int face = elem_faces(i_elem, i_face);
              const int voisin = faces_elem(face, 0) + faces_elem(face, 1) - i_elem;
              if (voisin >= 0) //!< le voisin existe
                {
                  if ((indic_pena_global(voisin) == indicatrice_totale(voisin)) &&  (indic_pena_global(voisin) == indicatrice_totale(i_elem))) //!< strictement fluide aux deux pas de temps
                    {
                      somme_inc += solution(voisin);
                      ++coeff;
                    }
                  else     //!< On sauve le numero du voisin
                    {
                      stok_vois(i_face) = voisin;
                    }
                }
            }
// Si on n a pas trouve de cellules fluide, on regarde les voisins des voisins
          if (coeff == 0.)
            {
              for (int i_vois = 0; i_vois < nb_faces_elem; i_vois++)
                {
                  for (int ii_face = 0; ii_face < nb_faces_elem; ii_face++)
                    {
                      const int face_v = elem_faces(stok_vois(i_vois), ii_face);
                      const int voisin_v = faces_elem(face_v, 0) + faces_elem(face_v, 1) - stok_vois(i_vois);
                      if ((voisin_v >= 0) && (voisin_v != i_elem) )//!< le voisin existe et pas i_elem
{
                          if ((indic_pena_global(voisin_v) == indicatrice_totale(voisin_v)) &&  (indic_pena_global(voisin_v) == indicatrice_totale(i_elem))) //!< strictement fluide aux deux pas de temps
{
                              somme_inc += solution(voisin_v);
                              ++coeff;
                            }
                        }
                    }
                }
            }
// definition d une nouvelle valleur de la variable pour la cellule fantome
          if (coeff > 0.)
            {
              solution(i_elem) = somme_inc / coeff;
              k_cor += 1;
            }
        }
// cellules actuellement ibc et precedement fluide
      if (indic_pena_global(i_elem) == 0 && indicatrice_totale(i_elem) != 0)
        {
          ++u;
// boucle sur les faces pour determiner la valeur de la variable pour les cellules voisines strictement ibc
          IntTrav stok_vois(nb_faces_elem);
          for (int i_face = 0; i_face < nb_faces_elem; i_face++)
            {
              const int face = elem_faces(i_elem, i_face);
              const int voisin = faces_elem(face, 0) + faces_elem(face, 1) - i_elem;
              if (voisin >= 0) //!< le voisin existe
                {
// strictement ibc aux deux pas de temps (la meme) car solution a ete modifiee ci-dessus
                  if ((indic_pena_global(voisin) == indicatrice_totale(voisin)) && (indic_pena_global(voisin) == indicatrice_totale(i_elem)))
                    {
                      somme_inc += solution(voisin);
                      ++coeff;
                    }
                  else     //!< On sauve le numero du voisin
                    {
                      stok_vois(i_face) = voisin;
                    }
                }
            }
// Si on n a pas trouve de cellules ibc, on regarde les voisins des voisins
          if (coeff == 0.)
            {
              for (int i_vois = 0; i_vois < nb_faces_elem; i_vois++)
                {
                  for (int ii_face = 0; ii_face < nb_faces_elem; ii_face++)
                    {
                      const int face_v = elem_faces(stok_vois(i_vois), ii_face);
                      const int voisin_v = faces_elem(face_v, 0) + faces_elem(face_v, 1) - stok_vois(i_vois);
                      if ((voisin_v >= 0) && (voisin_v != i_elem) )//!< le voisin existe et pas i_elem
{
                          if ((indic_pena_global(voisin_v) == indicatrice_totale(voisin_v)) && (indic_pena_global(voisin_v) == indicatrice_totale(i_elem))) //!< strictement ibc aux deux pas de temps (la meme) car solution a ete modifiee ci-dessus
{
                              somme_inc += solution(voisin_v);
                              ++coeff;
                            }
                        }
                    }
                }
            }
// definition d une nouvelle valleur de la variable pour la cellule fantome
          if (coeff > 0.)
            {
              solution(i_elem) = somme_inc / coeff;
              k_cor2 += 1;
            }
          else
            {
              solution(i_elem) = tab_penalisation_L2_FTD[indicatrice_totale(i_elem)-1](0);
              k_cor2 += 1;
            }
        }
    }
  solution.echange_espace_virtuel();
// Debog::verifier("Convection_Diffusion_Temperature::mise_en_place_zone_fantome solution ",solution);
  Cout <<"Mise_en_place_zone_fantome : fluide -> ibc : "<<u<< " elem. (dont "<<k_cor2<<" corrigees) et ibc -> fluide : ";
  Cout<<k<<" elem.(dont "<<k_cor<<" corrigees)"<<finl;
  Cout <<"             nb elem. ibc : "<<x<<" et nb elem fluide : "<<j<<" sur un total de : "<<nb_elem<<finl;
  if ((u != k_cor2) || (k !=k_cor))
    {
      Cerr <<"Mise_en_place_zone_fantome : Les cellules fantomes ne sont pas toutes corrigees"<<finl;
      exit();
    }
  indic_pena_global = indicatrice_totale;
  indic_face_pena_global = indicatrice_face_totale;
  maj = mise_a_jour_tag_indicatrice_pena_glob();
  assert(maj == 1);
}
References calcul_indic_pena_global(), Cerr, coeff, Cout, TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), Process::exit(), Zone_VF::face_voisins(), finl, indic_face_pena_global, indic_pena_global, mise_a_jour_tag_indicatrice_pena_glob(), ref_cast, Equation_base::schema_temps(), tab_penalisation_L2_FTD, valeur(), verifier_tag_indicatrice_pena_glob(), and Equation_base::zone_dis().
Referenced by derivee_en_temps_inco().
penalisation_L2()
DoubleTab & Convection_Diffusion_Temperature::penalisation_L2 (DoubleTab & u) protected
Definition at line 1201 of file Convection_Diffusion_Temperature.cpp.
{
// garde-fou
  assert(ref_penalisation_L2_FTD.size() != 0);
  assert(ref_penalisation_L2_FTD.size() == tab_penalisation_L2_FTD.size());
  const double dt = schema_temps().pas_de_temps();
  DoubleTab u_old(u);
// caclul de la fonction caracteristique globale des ibc pour le calcul de T_voisinage
  set_indic_pena_globale();
// calcul de T_voisinage pour tous les elemnts
  const Zone_VF& zone_vf = ref_cast(Zone_VF, zone_dis().valeur());
  const IntTab& elem_faces = zone_vf.elem_faces();
  const IntTab& faces_elem = zone_vf.face_voisins();
  const int nb_faces_elem = elem_faces.dimension(1);
  const DoubleTab& inc=inconnue().valeurs();
// inconnue doit etre scalaire
  assert(inc.line_size() == 1);
  DoubleTrav t_voisinage(inc);
  DoubleTrav u_voisinage(u);
  const int nb_elem  = u.dimension_tot(0);
  for (int i_elem = 0; i_elem < nb_elem; i_elem++)
    {
      double somme = 0.;
      double somme_deriv = 0.;
      double coeff = 0.;
      if( indic_pena_global(i_elem) != 0)
        {
// boucle sur les faces de l element
          for (int i_face = 0; i_face < nb_faces_elem; i_face++)
            {
              const int face = elem_faces(i_elem, i_face);
              const int voisin = faces_elem(face, 0) + faces_elem(face, 1) - i_elem;
              if (voisin >= 0)
                {
                  if (indic_pena_global(voisin) == 0)
                    {
                      somme += inc(voisin);
                      somme_deriv += u(voisin);
                      coeff += 1.;
                    }
                }
            }
        }
      if (coeff > 0.)
        {
          t_voisinage(i_elem) = somme / coeff;
          u_voisinage(i_elem) = somme_deriv / coeff;
        }
      else
        {
// cas pas de voisin dans le fluide
          t_voisinage(i_elem) = inc(i_elem);
          u_voisinage(i_elem) = u(i_elem);
        }
    }
  t_voisinage.echange_espace_virtuel();
  u_voisinage.echange_espace_virtuel();
// determination du champ global de penalisation L2
  DoubleTrav pena_glob(inc); //initialise a zero
  DoubleTrav tab_(inc); //initialise a zero
  DoubleTrav denom(inc); //initialise a zero
// boucle ibc
  for ( int i = 0 ; i < ref_penalisation_L2_FTD.size() ; ++i)
    {
      Transport_Interfaces_base& nom_eq = ref_cast(Transport_Interfaces_base,ref_penalisation_L2_FTD[i].valeur());
      const DoubleTab& tab = tab_penalisation_L2_FTD[i];
// verification dimensions tab t obstacle = nb dim de l inconnu
      if ( tab.dimension(0) != inc.line_size() )
        {
          Cerr << " penalisation_L2: Les champs de temperature impose et calcule n'ont pas les memes dimensions" <<finl;
          Cerr << " Dimension du champ de temperature impose "<< tab.dimension(0) << finl;
          Cerr << " Dimension du champ de temperature calcule par TRUST "<<inc.line_size() <<finl;
          Cerr << " Nombre d'elements stockes au dans l'iconnue " <<inc.size() <<finl;
          Process::exit();
        }
      const DoubleTab& indicatrice = nom_eq.get_update_indicatrice().valeurs();
      DoubleTrav pena_loc(indicatrice);
// Determination du terme de penalisation pour l ibc courante
// boucle sur les elements
      for (int j = 0; j<nb_elem ; ++j)
        {
// calcul de la fonction characteristique Ksi de l ibc courante -> pena_loc
          if (indicatrice(j) > 0.)
            {
              double coeff_p=1.;
              pena_loc(j) = coeff_p;
// calcul du denominateur du terme de penalisation (Sigma_ibc Ksi_ibc(j))
              denom(j) += coeff_p;
// determination valeur a imposer T_ref
              double tref_j = 0.;
              switch (choix_pena)
                {
                case 0 :
// approximation de T_ref par T_ref = T_imp
                  tref_j = tab(0);
                  break;
                case 1 :
// approximation de T_ref par T_ref = T+dt*derivee
                  tref_j = inc(j) + dt*u_old(j);
                  break;
                case 2 :
// approximation de T_imp par T_ref= tau*T_imp + (1-tau)*T_voisin
// approximation de T_voisin par T_voisin= 1/n * somme(1,n)(T_environnant+dt*derivee_environnant)
                  tref_j = (indicatrice(j)*tab(0)+(1.-indicatrice(j))*(t_voisinage(j)+dt*u_voisinage(j)));
                  break;
                case 3 :
// approximation de T_imp par T_ref= [(1-tau)*T_voisin + (1/2)*T_imp] / (3/2 -tau)
// approximation de T_voisin par T_voisin= 1/n * somme(1,n)(T_environnant+dt*derivee_environnant)
                  tref_j = ((1.-indicatrice(j))*(t_voisinage(j)+dt*u_voisinage(j))+0.5*tab(0))/(1.5-indicatrice(j));
                  break;
                case 4 :
// approximation de T_imp par T_ref= T_imp si tau=1 sinon T_ref=T_voisin
                  if (indicatrice(j) == 1.)
                    {
                      tref_j = tab(0);
                    }
                  else
                    {
                      tref_j = (t_voisinage(j)+dt*u_voisinage(j));
                    }
                  break;
                default:
                  Cerr << "Penalisation_L2: choix_pena invalide "<< choix_pena <<finl;
                  exit();
                  break;
                }
// sauvegarde de Sigma_ibc Ksi_ibc(j) Tref_ibc pour post-traitement
              tab_(j) += tref_j;
// penalisation_global = Sigma_ibc Ksi_ibc(j)*(Tref_ibc - inc) /  eta;
              pena_loc(j) *= (tref_j-inc(j));
              pena_loc(j) /= eta;
              pena_glob(j)  += pena_loc(j);
            }
        }
    }
// Realisation de la penalisation L2 de la derivee en temps: (dT_t_* + pena_glob) / (1 + (dt*Sigma_ibc Ksi_ibc(j)) / eta)
// Tref est la moyenne arithmetique de Tref_j lorsque 0<eta<<1
  for (int j = 0 ; j<nb_elem ; ++j)
    {
      u(j) = u_old(j) + pena_glob(j);
      u(j) /= (1. + denom(j)*dt/eta);
    }
  u.echange_espace_virtuel();
// Sauvegarde des flux
  ecrire_fichier_pena_th(u_old,u,tab_,denom);
// Debog::verifier("Convection_Diffusion_Temperature::penalisation_L2 u ",u);
  return u;
}
References Cerr, choix_pena, coeff, TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), ecrire_fichier_pena_th(), Zone_VF::elem_faces(), eta, Process::exit(), Zone_VF::face_voisins(), finl, Transport_Interfaces_base::get_update_indicatrice(), inconnue(), indic_pena_global, TRUSTVect< _TYPE_ >::line_size(), Schema_Temps_base::pas_de_temps(), ref_cast, ref_penalisation_L2_FTD, Equation_base::schema_temps(), set_indic_pena_globale(), TRUSTVect< _TYPE_ >::size(), vect_impl::size(), tab_penalisation_L2_FTD, valeur(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), and Equation_base::zone_dis().
Referenced by derivee_en_temps_inco().
printOn()
Sortie & Convection_Diffusion_Temperature::printOn (Sortie & is) const override protected virtual
Simple appel a: Convection_Diffusion_std::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Convection_Diffusion_std.
Definition at line 66 of file Convection_Diffusion_Temperature.cpp.
{
  return Convection_Diffusion_std::printOn(is);
}
References Convection_Diffusion_std::printOn().
readOn()
Entree & Convection_Diffusion_Temperature::readOn (Entree & is) override protected virtual
Verifie si l'equation a une temperature et un fluide associe
cf Convection_Diffusion_std::readOn(Entree&).
Returns
Entree& is
Signification: le flot d'entree modifie
Contraintes:
< On prevoir le cas d'equation de scalaires passifs
Reimplemented from Convection_Diffusion_std.
Definition at line 87 of file Convection_Diffusion_Temperature.cpp.
{
  assert(la_temperature.non_nul());
  assert(le_fluide.non_nul());
  Convection_Diffusion_std::readOn(is);
// Nom unite;
// if (dimension+bidim_axi==2) unite="[W/m]";
// else unite="[W]";
  Nom num=inconnue().le_nom(); //!< On prevoir le cas d'equation de scalaires passifs
  num.suffix("temperature");
  Nom nom="Convection_chaleur";
  nom+=num;
  terme_convectif.set_fichier(nom);
// terme_convectif.set_description((Nom)"Convective heat transfer rate=Integral(-rho*cp*T*u*ndS) "+unite);
  terme_convectif.set_description((Nom)"Convective heat transfer rate=Integral(-rho*cp*T*u*ndS) [W] if SI units used");
  nom="Diffusion_chaleur";
  nom+=num;
  terme_diffusif.set_fichier(nom);
// terme_diffusif.set_description((Nom)"Conduction heat transfer rate=Integral(lambda*grad(T)*ndS) "+unite);
  terme_diffusif.set_description((Nom)"Conduction heat transfer rate=Integral(lambda*grad(T)*ndS) [W] if SI units used");
  solveur_masse->set_name_of_coefficient_temporel("rho_cp_comme_T");
  return is;
}
References inconnue(), la_temperature, le_fluide, O_U_Ptr::le_nom(), O_U_Ptr::non_nul(), Convection_Diffusion_std::readOn(), Operateur::set_description(), Operateur::set_fichier(), Equation_base::solveur_masse, Nom::suffix(), Convection_Diffusion_std::terme_convectif, and Convection_Diffusion_std::terme_diffusif.
self_cast() [1/2]
const Convection_Diffusion_Temperature & Convection_Diffusion_Temperature::self_cast (const Objet_U & r) static
Definition at line 36 of file Convection_Diffusion_Temperature.cpp.
self_cast() [2/2]
Convection_Diffusion_Temperature & Convection_Diffusion_Temperature::self_cast (Objet_U & r) static
Definition at line 36 of file Convection_Diffusion_Temperature.cpp.
set_indic_pena_globale()
void Convection_Diffusion_Temperature::set_indic_pena_globale () protected
Definition at line 874 of file Convection_Diffusion_Temperature.cpp.
{
// Set de la fonction characteristique ibc globlale (element et faces)
  int maj = verifier_tag_indicatrice_pena_glob();
  if (maj == 0)
    {
      calcul_indic_pena_global(indic_pena_global, indic_face_pena_global);
      maj = mise_a_jour_tag_indicatrice_pena_glob();
      assert(maj == 1);
    }
}
References calcul_indic_pena_global(), indic_face_pena_global, indic_pena_global, mise_a_jour_tag_indicatrice_pena_glob(), and verifier_tag_indicatrice_pena_glob().
Referenced by filtrage_si_appart_ibc(), penalisation_L2(), and transport_ibc().
set_param()
void Convection_Diffusion_Temperature::set_param (Param & titi) override virtual
Reimplemented from Convection_Diffusion_std.
Definition at line 111 of file Convection_Diffusion_Temperature.cpp.
{
  Convection_Diffusion_std::set_param(param);
  param.ajouter_non_std("penalisation_L2_FTD",(this));
}
References Param::ajouter_non_std(), and Convection_Diffusion_std::set_param().
taille_memoire()
unsigned Convection_Diffusion_Temperature::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 36 of file Convection_Diffusion_Temperature.cpp.
transport_ibc()
void Convection_Diffusion_Temperature::transport_ibc (DoubleTrav & secmem_conv_vr, DoubleTab & inco_conv_vr) protected
Definition at line 886 of file Convection_Diffusion_Temperature.cpp.
{
  secmem_conv_vr = 0.;
  const double rhoCp = le_fluide->capacite_calorifique().valeurs()(0, 0) * le_fluide->masse_volumique().valeurs()(0, 0);
// fonction characteristique globale ibc au temps courant
  set_indic_pena_globale();
// on calcule l indicatrice epaisse
  const Zone_VF& zone_vf = ref_cast(Zone_VF, zone_dis().valeur());
  const IntTab& faces_elem = zone_vf.face_voisins();
  IntTrav indic_pena_global_fat(indic_pena_global);
  for (int i_face = 0; i_face < indic_face_pena_global.size(); i_face++)
    {
      if (indic_face_pena_global(i_face) > 0.)
        {
          const int voisin_0 = faces_elem(i_face, 0);
          if (voisin_0 >= 0) indic_pena_global_fat(voisin_0) = 1;
          const int voisin_1 = faces_elem(i_face, 1);
          if (voisin_1 >= 0) indic_pena_global_fat(voisin_1) = 1;
        }
    }
// post-traitement particulier pour les coins
  const IntTab& elem_faces = zone_vf.elem_faces();
  const int nb_faces_elem = elem_faces.dimension(1);
  const int nb_elem  = indic_pena_global.dimension(0);
  for (int i_elem = 0; i_elem < nb_elem;  i_elem++)
    {
      if (indic_pena_global_fat(i_elem) == 0)
        {
          int coeff = 0;
          for (int i_face = 0; i_face < nb_faces_elem; i_face++)
            {
              const int face = elem_faces(i_elem, i_face);
              const int voisin = faces_elem(face, 0) + faces_elem(face, 1) - i_elem;
              if (voisin >= 0)
                {
                  if (indic_pena_global_fat(voisin) != 0)
                    {
                      ++coeff;
                    } ;
                }
            }
          if (coeff > 1) indic_pena_global_fat(i_elem) = 1;
        }
    }
// Si on veut un traitement local a chaque indicatrice (necessaire si on utilise vitesse imposee)
// IntTrav indic_pena_fat(indic_pena_global);
// for (int w = 0; w < ref_penalisation_L2_FTD.size(); w++)
// {
// Transport_Interfaces_base & nom_eq = ref_cast(Transport_Interfaces_base,ref_penalisation_L2_FTD[w].valeur());
// // on calcul le filtre local a l ibc
// const DoubleTab & indicatrice_face = nom_eq.get_compute_indicatrice_faces().valeurs();
// indic_pena_fat = 0;
// for (int i_face = 0; i_face < indicatrice_face.size(); i_face++)
// {
// if (indicatrice_face(i_face) > 0.)
// {
// const int voisin_0 = faces_elem(i_face, 0);
// if (voisin_0 >= 0) indic_pena_fat(voisin_0) = 1;
// const int voisin_1 = faces_elem(i_face, 1);
// if (voisin_1 >= 0) indic_pena_fat(voisin_1) = 1;
// }
// }
// indic_pena_global_fat += indic_pena_fat;
// }
// on convecte le champ de variable avec la vitesse fluide pour les faces ibc
  if ( nombre_d_operateurs() > 1 )
    {
      derivee_en_temps_conv(secmem_conv_vr, inco_conv_vr);
      secmem_conv_vr *= rhoCp;
    }
// on ne garde la contribution que pour les cellules dont indicatrice fat est <> 0
  for (int i_elem = 0; i_elem < nb_elem;  i_elem++)
    {
      if (indic_pena_global_fat(i_elem) == 0) secmem_conv_vr(i_elem) = 0.;
    }
}
References Milieu_base::capacite_calorifique(), coeff, Equation_base::derivee_en_temps_conv(), TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), Zone_VF::face_voisins(), indic_face_pena_global, indic_pena_global, le_fluide, Milieu_base::masse_volumique(), Convection_Diffusion_std::nombre_d_operateurs(), ref_cast, set_indic_pena_globale(), TRUSTVect< _TYPE_ >::size(), valeur(), Champ::valeurs(), Champ_Don::valeurs(), and Equation_base::zone_dis().
Referenced by derivee_en_temps_inco().
verifier_tag_indicatrice_pena_glob()
int Convection_Diffusion_Temperature::verifier_tag_indicatrice_pena_glob () protected
Definition at line 842 of file Convection_Diffusion_Temperature.cpp.
{
// Les ibcs ont elles ete modifiees ?
  int maj = 0;
  int tag_all = 0;
  for ( int w = 0; w<ref_penalisation_L2_FTD.size() ; ++w)
    {
      Transport_Interfaces_base& nom_eq = ref_cast(Transport_Interfaces_base,ref_penalisation_L2_FTD[w].valeur());
      tag_all += nom_eq.get_mesh_tag();
    }
  if (tag_all == tag_indic_pena_global) maj = 1;
  return maj;
}
References Transport_Interfaces_base::get_mesh_tag(), ref_cast, ref_penalisation_L2_FTD, vect_impl::size(), tag_indic_pena_global, and valeur().
Referenced by mise_en_place_zone_fantome(), and set_indic_pena_globale().
Member Data Documentation
choix_pena
int Convection_Diffusion_Temperature::choix_pena protected
Definition at line 86 of file Convection_Diffusion_Temperature.h.
Referenced by Convection_Diffusion_Temperature(), lire_motcle_non_standard(), and penalisation_L2().
eta
double Convection_Diffusion_Temperature::eta protected
Definition at line 85 of file Convection_Diffusion_Temperature.h.
Referenced by Convection_Diffusion_Temperature(), ecrire_fichier_pena_th(), lire_motcle_non_standard(), and penalisation_L2().
gradient_temperature
Champ_Fonc Convection_Diffusion_Temperature::gradient_temperature protected
Definition at line 77 of file Convection_Diffusion_Temperature.h.
Referenced by creer_champ(), and get_champ().
h_echange
Champ_Fonc Convection_Diffusion_Temperature::h_echange protected
Definition at line 81 of file Convection_Diffusion_Temperature.h.
Referenced by creer_champ(), and get_champ().
indic_face_pena_global
IntTab Convection_Diffusion_Temperature::indic_face_pena_global protected
Definition at line 89 of file Convection_Diffusion_Temperature.h.
Referenced by calcul_indic_pena_global(), Convection_Diffusion_Temperature(), lire_motcle_non_standard(), mise_en_place_zone_fantome(), set_indic_pena_globale(), and transport_ibc().
indic_pena_global
IntTab Convection_Diffusion_Temperature::indic_pena_global protected
Definition at line 88 of file Convection_Diffusion_Temperature.h.
Referenced by calcul_indic_pena_global(), Convection_Diffusion_Temperature(), filtrage_si_appart_ibc(), lire_motcle_non_standard(), mise_en_place_zone_fantome(), penalisation_L2(), set_indic_pena_globale(), and transport_ibc().
info_obj
const Type_info Convection_Diffusion_Temperature::info_obj static
Definition at line 39 of file Convection_Diffusion_Temperature.h.
is_penalized
int Convection_Diffusion_Temperature::is_penalized protected
Definition at line 84 of file Convection_Diffusion_Temperature.h.
Referenced by Convection_Diffusion_Temperature(), derivee_en_temps_inco(), and lire_motcle_non_standard().
la_temperature
Champ_Inc Convection_Diffusion_Temperature::la_temperature protected
Definition at line 73 of file Convection_Diffusion_Temperature.h.
Referenced by creer_champ(), discretiser(), get_champ(), inconnue(), and readOn().
le_fluide
Ref_Fluide_base Convection_Diffusion_Temperature::le_fluide protected
Definition at line 74 of file Convection_Diffusion_Temperature.h.
Referenced by assembler(), assembler_blocs(), associer_fluide(), derivee_en_temps_inco(), derivee_en_temps_inco_eq_base(), fluide(), readOn(), and transport_ibc().
ref_penalisation_L2_FTD
Vect_RefObjU Convection_Diffusion_Temperature::ref_penalisation_L2_FTD protected
Definition at line 90 of file Convection_Diffusion_Temperature.h.
Referenced by calcul_indic_pena_global(), ecrire_fichier_pena_th(), lire_motcle_non_standard(), mise_a_jour_tag_indicatrice_pena_glob(), penalisation_L2(), and verifier_tag_indicatrice_pena_glob().
tab_penalisation_L2_FTD
DoubleTabs Convection_Diffusion_Temperature::tab_penalisation_L2_FTD protected
Definition at line 91 of file Convection_Diffusion_Temperature.h.
Referenced by lire_motcle_non_standard(), mise_en_place_zone_fantome(), and penalisation_L2().
tag_indic_pena_global
int Convection_Diffusion_Temperature::tag_indic_pena_global protected
Definition at line 87 of file Convection_Diffusion_Temperature.h.
Referenced by Convection_Diffusion_Temperature(), mise_a_jour_tag_indicatrice_pena_glob(), and verifier_tag_indicatrice_pena_glob().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Equations/Convection_Diffusion_Temperature.h
src/ThHyd/Incompressible/Equations/Convection_Diffusion_Temperature.cpp