TRUST: Energie_Multiphase Class Reference
Energie_Multiphase Class Reference
classe Energie_Multiphase
Cas particulier de Convection_Diffusion_std pour un fluide quasi conpressible
quand le scalaire subissant le transport est la temperature en gaz parfaits,
ou l'enthalpie en gaz reels.
(generalisation de Convection_Diffusion_Temperature pour les gaz reels)
#include <Energie_Multiphase.h>
Public Member Functions
~Energie_Multiphase ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Energie_Multiphase ()
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void associer_fluide (const Fluide_base &)
Associe un fluide incompressible a l'equation.
const Champ_Inc & inconnue () const override
Renvoie le champ inconnue representant l'inconnue (T ou H)
(version const)
Champ_Inc & inconnue () override
Renvoie le champ inconnue representant l'inconnue (T ou H)
void discretiser () override
Discretise l'equation.
const Milieu_base & milieu () const override
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
(version const)
const Fluide_base & fluide () const
Renvoie le fluide incompressible associe a l'equation.
(version const)
Fluide_base & fluide ()
Renvoie le fluide incompressible associe a l'equation.
Milieu_base & milieu () override
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
void associer_milieu_base (const Milieu_base &) override
Associe un milieu physique a l'equation,
le milieu est en fait caste en Fluide_base ou en Fluide_Ostwald.
int impr (Sortie &os) const override
Impression des flux sur les bords sur un flot de sortie.
Appelle Equation_base::impr(Sortie&)
const Champ_Don & diffusivite_pour_transport () const override
const Champ_base & diffusivite_pour_pas_de_temps () const override
void dimensionner_matrice_sans_mem (Matrice_Morse &matrice) override
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) override
const Motcle & domaine_application () const override
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
void verifie_ch_init_nb_comp_cl (const Champ_Inc_base &ch_ref, const int nb_comp, const Cond_lim_base &cl) const override
Verification du nombre de composantes lues pour la specification d un champ.
Dans Energie_Multiphase, les conditions aux limites de type "paroi" ne prennent
qu'une compposante lorsqu'une correlation "flux_parietal" est definie au niveau du probleme.
std::pair< std::string, fonc_calc_t > get_fonc_champ_conserve () const override
virtual std::pair< std::string, fonc_calc_t > get_fonc_champ_convecte () const
Champ_Inc_base & champ_convecte () const override
int has_champ_convecte () const override
void init_champ_convecte () const override
Public Member Functions inherited from Convection_Diffusion_std
Convection_Diffusion_std ()
~Convection_Diffusion_std () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &titi) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
int nombre_d_operateurs () const override
Renvoie le nombre d'operateurs de l'equation:
2 pour une equation de diffusion.
const Operateur & operateur (int) const override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1
(version const)
Operateur & operateur (int) override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1.
void associer_vitesse (const Champ_base &)
Associe la vitesse transportante a l'equation.
const Champ_Inc_base & vitesse_transportante () const
Renvoie une reference sur le champ representant
la vitesse transportante.
const Champ_Inc & inconnue () const override=0
Champ_Inc & inconnue () override=0
virtual const Champ_Don & diffusivite_pour_transport () const
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
virtual const Champ_base & vitesse_pour_transport () const
int sauvegarder_base (Sortie &) const
int reprendre_base (Entree &)
Public Member Functions inherited from Equation_base
Equation_base ()
~Equation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Methode appelee lorsqu'on cree l'instance de l'objet dans
le jeu de donnees (Interprete::ajouter)
virtual void avancer (int i=1)
virtual void reculer (int i=1)
virtual int nombre_d_operateurs () const =0
virtual int nombre_d_operateurs_tot () const
virtual const Operateur & operateur (int) const =0
virtual Operateur & operateur (int)=0
virtual const Operateur & operateur_fonctionnel (int) const
virtual Operateur & operateur_fonctionnel (int)
virtual const Champ_Inc & inconnue () const =0
virtual Champ_Inc & inconnue ()=0
virtual void associer_milieu_base (const Milieu_base &)=0
virtual const Milieu_base & milieu () const =0
virtual Milieu_base & milieu ()=0
int sauvegarder (Sortie &) const override
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
int reprendre (Entree &) override
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
int limpr () const
Demande au schema en temps si il faut effectuer une impression.
Renvoie 1 si il faut effectuer une impression.
Appel simple a Schema_Temps_base::limpr()
virtual void imprimer (Sortie &os) const
Imprime les operateurs de l'equation si le schema en temps
indique que c'est necessaire.
[SI limpr() ALORS impr(os)].
virtual int impr (Sortie &os) const
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
virtual void associer_milieu_equation ()
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
virtual DoubleTab & derivee_en_temps_inco_transport (DoubleTab &derivee)
virtual DoubleTab & corriger_derivee_expl (DoubleTab &)
virtual DoubleTab & corriger_derivee_impl (DoubleTab &)
virtual void mettre_a_jour (double temps)
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
virtual void abortTimeStep ()
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
virtual void valider_iteration ()
virtual int preparer_calcul ()
Tout ce qui ne depend pas des autres problemes eventuels.
virtual bool initTimeStep (double dt)
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
virtual bool updateGivenFields ()
virtual void discretiser ()
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
virtual void associer_pb_base (const Probleme_base &)
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur
de masse a l'equation.
virtual void completer ()
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
virtual double calculer_pas_de_temps () const
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des
pas de temps calcules par les operateurs.
Ces pas de temps sont ceux pour le schema d'Euler explicite.
Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule.
void calculer_pas_de_temps_locaux (DoubleTab &) const
Sources & sources ()
Renvoie les termes sources asssocies a l'equation.
const Sources & sources () const
Renvoie les termes sources asssocies a l'equation<br>(version const)
Solveur_Masse & solv_masse ()
Renvoie le solveur de masse associe a l'equation.
const Solveur_Masse & solv_masse () const
Renvoie le solveur de masse associe a l'equation.
(version const)
Probleme_base & probleme ()
Renvoie le probleme associe a l'equation.
const Probleme_base & probleme () const
Renvoie le probleme associe a l'equation.
(version const)
Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe a l'equation.
const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe a l'equation.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
S'associe au schema_en_temps.
virtual void associer_zone_dis (const Zone_dis &)
Associe la zone discretisee a l'equation.
const Discretisation_base & discretisation () const
Renvoie la discretisation associee a l'equation.
virtual Zone_Cl_dis & zone_Cl_dis ()
Renvoie la zone des conditions aux limite discretisee
associee a l'equation.
virtual const Zone_Cl_dis & zone_Cl_dis () const
Renvoie la zone des conditions aux limite discretisee
associee a l'equation<br>(version const)
Zone_dis & zone_dis ()
Renvoie la zone discretisee associee a l'equation.
const Zone_dis & zone_dis () const
Renvoie la zone discretisee associee a l'equation.
(version const)
const Nom & le_nom () const override
Renvoie le nom de l'equation.
DoubleVect & get_residu ()
DoubleVect & residu_initial ()
void initialise_residu (int=0)
virtual void imprime_residu (SFichier &)
virtual Nom expression_residu ()
virtual void dimensionner_matrice (Matrice_Morse &mat_morse)
virtual void dimensionner_matrice_sans_mem (Matrice_Morse &mat_morse)
virtual void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void modifier_pour_Cl (Matrice_Morse &mat_morse, DoubleTab &secmem) const
virtual void assembler_avec_inertie (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void dimensionner_termes_croises (Matrice_Morse &matrice, const Probleme_base &autre_pb, int nl, int nc)
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void assembler_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={})
Champ_Inc_base & champ_conserve () const
int has_champ_conserve () const
void init_champ_conserve () const
virtual std::pair< std::string, fonc_calc_t > get_fonc_champ_conserve () const
virtual Champ_Inc_base & champ_convecte () const
virtual int has_champ_convecte () const
virtual void init_champ_convecte () const
virtual void mettre_a_jour_champs_conserves (double temps, int reset=0)
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Motcle & domaine_application () const
Renvoie "indetermine"
Navier_Stokes_standard par exemple surcharge cette methode
pour renvoyer "Hydraulique".
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Verification du nombre de composantes lues pour la specification d un champ.
Actuellement utilise pour la lecture d un condition initiale ou limite.
virtual void verifie_ch_init_nb_comp_cl (const Champ_Inc_base &ch_ref, const int nb_comp, const Cond_lim_base &cl) const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
Add convection term
In: solution is the unknown I
Out: secmem is increased by convection(I)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution, const DoubleTab &terme_mul)
Parametre_equation & parametre_equation ()
const Parametre_equation & parametre_equation () const
virtual const Ref_Objet_U & get_modele (Type_modele type) const
virtual int equation_non_resolue () const
int disable_equation_residual () const
virtual const Champ_Inc & derivee_en_temps () const
virtual Champ_Inc & derivee_en_temps ()
void set_calculate_time_derivative (int i)
int calculate_time_derivative () const
void set_residuals (DoubleTab r)
virtual int positive_unkown ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Energie_Multiphase & self_cast (Objet_U &)
static const Energie_Multiphase & self_cast (const Objet_U &)
static void calculer_alpha_rho_e (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
static void calculer_alpha_rho_h (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Static Public Member Functions inherited from Convection_Diffusion_std
static const Type_info * info ()
static Convection_Diffusion_std & self_cast (Objet_U &)
static const Convection_Diffusion_std & self_cast (const Objet_U &)
Static Public Member Functions inherited from Equation_base
static const Type_info * info ()
static Equation_base & self_cast (Objet_U &)
static const Equation_base & self_cast (const Objet_U &)
static void calculer_champ_conserve (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Convection_Diffusion_std
static const Type_info info_obj
Static Public Attributes inherited from Equation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Convection_Diffusion_std::printOn(Sortie&)
Entree & readOn (Entree &) override
Verifie si l'equation a une inconnue et un fluide associe
et appelle Convection_Diffusion_std::readOn(Entree&).
Sortie & printOn (Sortie &x) const override
Simple appel a Equation_base::printOn(Sortie&)
Entree & readOn (Entree &) override
cf Equation_base::readOn(Entree&)
Protected Member Functions inherited from Equation_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
virtual void set_param (Param &titi)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_sources (Entree &)
Lecture des termes sources dans un flot d'entree.
virtual Entree & lire_cond_init (Entree &)
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
virtual Entree & lire_cl (Entree &)
Lecture des conditions limites sur un flot d'entree.
voir Zone_Cl_dis_base::readOn.
virtual int verif_Cl () const
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
virtual void lire ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_Inc l_inco_ch
Operateur_Evanescence evanescence
Ref_Fluide_base le_fluide
Protected Attributes inherited from Convection_Diffusion_std
Ref_Champ_Inc_base la_vitesse_transportante
Operateur_Conv terme_convectif
Operateur_Diff terme_diffusif
Protected Attributes inherited from Equation_base
Nom nom_
Solveur_Masse solveur_masse
Sources les_sources
Ref_Schema_Temps_base le_schema_en_temps
Ref_Zone_dis la_zone_dis
Zone_Cl_dis la_zone_Cl_dis
Ref_Probleme_base mon_probleme
DoubleList dt_op_bak
int sys_invariant_
int implicite_
Parametre_equation parametre_equation_
Champ_Fonc volume_maille
List_RefObjU liste_modeles_
Champs_compris champs_compris_
Champs_Fonc list_champ_combi
Matrice_Morse matrice_stockee
int matrice_init
Champ_Inc champ_conserve_
Champ_Inc champ_convecte_
Detailed Description
classe Energie_Multiphase
Cas particulier de Convection_Diffusion_std pour un fluide quasi conpressible
quand le scalaire subissant le transport est la temperature en gaz parfaits,
ou l'enthalpie en gaz reels.
(generalisation de Convection_Diffusion_Temperature pour les gaz reels)
Definition at line 35 of file Energie_Multiphase.h.
Constructor & Destructor Documentation
~Energie_Multiphase()
Energie_Multiphase::~Energie_Multiphase ()
Definition at line 36 of file Energie_Multiphase.cpp.
Energie_Multiphase()
Energie_Multiphase::Energie_Multiphase ()
Definition at line 36 of file Energie_Multiphase.cpp.
Member Function Documentation
assembler_blocs_avec_inertie()
void Energie_Multiphase::assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) override virtual
Reimplemented from Equation_base.
Definition at line 387 of file Energie_Multiphase.cpp.
{
  Convection_Diffusion_std::assembler_blocs_avec_inertie(matrices, secmem, semi_impl);
  if (evanescence.non_nul()) evanescence.valeur().ajouter_blocs(matrices, secmem, semi_impl);
}
References Operateur_base::ajouter_blocs(), Equation_base::assembler_blocs_avec_inertie(), evanescence, O_U_Ptr::non_nul(), and Deriv_Operateur_Evanescence_base::valeur().
associer_fluide()
void Energie_Multiphase::associer_fluide (const Fluide_base & un_fluide)
Associe un fluide incompressible a l'equation.
Definition at line 362 of file Energie_Multiphase.cpp.
{
  le_fluide = un_fluide;
}
References le_fluide.
Referenced by associer_milieu_base().
associer_milieu_base()
void Energie_Multiphase::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation,
le milieu est en fait caste en Fluide_base ou en Fluide_Ostwald.
Implements Equation_base.
Definition at line 144 of file Energie_Multiphase.cpp.
{
  const Fluide_base& un_fluide = ref_cast(Fluide_base,un_milieu);
  associer_fluide(un_fluide);
}
References associer_fluide(), and ref_cast.
Referenced by Pb_Multiphase::associer_milieu_base().
calculer_alpha_rho_e()
void Energie_Multiphase::calculer_alpha_rho_e (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static
Definition at line 394 of file Energie_Multiphase.cpp.
{
  const Equation_base& eqn = ref_cast(Equation_base, obj);
  const Fluide_base& fl = ref_cast(Fluide_base, eqn.milieu());
  const Champ_base& ch_rho = fl.masse_volumique().valeur();
  const Champ_Inc_base& ch_alpha = ref_cast(Pb_Multiphase, eqn.probleme()).eq_masse.inconnue(),
                        &ch_en = ref_cast(Champ_Inc_base, fl.energie_interne()), //toujours un Champ_Inc
                         *pch_rho = sub_type(Champ_Inc_base, ch_rho) ? &ref_cast(Champ_Inc_base, ch_rho) : NULL; //pas toujours un Champ_Inc
  const DoubleTab& alpha = ch_alpha.valeurs(), &rho = ch_rho.valeurs(), &en = ch_en.valeurs();
  /* valeurs du champ */
  int i, n, N = val.line_size(), Nl = val.dimension_tot(0), cR = sub_type(Champ_Uniforme, ch_rho);
  for (i = 0; i < Nl; i++)
    for (n = 0; n < N; n++) val(i, n) = alpha(i, n) * rho(!cR * i, n) * en(i, n);
  /* on ne peut utiliser valeur_aux_bords que si ch_rho a une zone_dis_base */
  DoubleTab b_al = ch_alpha.valeur_aux_bords(), b_rho, b_en = ch_en.valeur_aux_bords();
  int Nb = b_al.dimension_tot(0);
  if (ch_rho.a_une_zone_dis_base()) b_rho = ch_rho.valeur_aux_bords();
  else b_rho.resize(Nb, N), ch_rho.valeur_aux(ref_cast(Zone_VF, eqn.zone_dis().valeur()).xv_bord(), b_rho);
  for (i = 0; i < Nb; i++)
    for (n = 0; n < N; n++) bval(i, n) = b_al(i, n) * b_rho(i, n) * b_en(i, n);
  DoubleTab& d_a = deriv["alpha"];//derivee en alpha : rho * en
  for (d_a.resize(Nl, N), i = 0; i < Nl; i++)
    for (n = 0; n < N; n++) d_a(i, n) = rho(!cR * i, n) * en(i, n);
  /* derivees a travers rho et en */
  const tabs_t d_vide = {}, &d_rho = pch_rho ? pch_rho->derivees() : d_vide, &d_en = ch_en.derivees();
  std::set<std::string> vars; //liste de toutes les derivees possibles
  for (auto && d_c : d_rho) vars.insert(d_c.first);
  for (auto && d_c : d_en) vars.insert(d_c.first);
  for (auto && var : vars)
    {
      const DoubleTab *dr = d_rho.count(var) ? &d_rho.at(var) : NULL, *de = d_en.count(var) ? &d_en.at(var) : NULL;
      DoubleTab& d_v = deriv[var];
      for (d_v.resize(Nl, N), i = 0; i < Nl; i++)
        for (n = 0; n < N; n++)
          d_v(i, n) = alpha(i, n) * ((dr ? (*dr)(i, n) * en(i, n) : 0) + (de ? rho(!cR * i, n) * (*de)(i, n) : 0));
    }
}
References Champ_base::a_une_zone_dis_base(), TRUSTTab< _TYPE_ >::dimension_tot(), Fluide_base::energie_interne(), TRUSTVect< _TYPE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Equation_base::probleme(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Deriv_Champ_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_base::valeur_aux(), Champ_base::valeur_aux_bords(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Equation_base::zone_dis().
Referenced by get_fonc_champ_conserve(), and get_fonc_champ_convecte().
calculer_alpha_rho_h()
void Energie_Multiphase::calculer_alpha_rho_h (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static
Definition at line 437 of file Energie_Multiphase.cpp.
{
  const Equation_base& eqn = ref_cast(Equation_base, obj);
  const Fluide_base& fl = ref_cast(Fluide_base, eqn.milieu());
  const Champ_base& ch_rho = fl.masse_volumique().valeur();
  const Champ_Inc_base& ch_alpha = ref_cast(Pb_Multiphase, eqn.probleme()).eq_masse.inconnue(),
                        &ch_h = ref_cast(Champ_Inc_base, fl.enthalpie()), //toujours un Champ_Inc
                         *pch_rho = sub_type(Champ_Inc_base, ch_rho) ? &ref_cast(Champ_Inc_base, ch_rho) : NULL; //pas toujours un Champ_Inc
  const DoubleTab& alpha = ch_alpha.valeurs(), &rho = ch_rho.valeurs(), &h = ch_h.valeurs();
  /* valeurs du champ */
  int i, n, N = val.line_size(), Nl = val.dimension_tot(0), cR = sub_type(Champ_Uniforme, ch_rho);
  for (i = 0; i < Nl; i++)
    for (n = 0; n < N; n++) val(i, n) = alpha(i, n) * rho(!cR * i, n) * h(i, n);
  /* on ne peut utiliser valeur_aux_bords que si ch_rho a une zone_dis_base */
  DoubleTab b_al = ch_alpha.valeur_aux_bords(), b_rho, b_h = ch_h.valeur_aux_bords();
  int Nb = b_al.dimension_tot(0);
  if (ch_rho.a_une_zone_dis_base()) b_rho = ch_rho.valeur_aux_bords();
  else b_rho.resize(Nb, N), ch_rho.valeur_aux(ref_cast(Zone_VF, eqn.zone_dis().valeur()).xv_bord(), b_rho);
  for (i = 0; i < Nb; i++)
    for (n = 0; n < N; n++) bval(i, n) = b_al(i, n) * b_rho(i, n) * b_h(i, n);
  DoubleTab& d_a = deriv["alpha"];//derivee en alpha : rho * h
  for (d_a.resize(Nl, N), i = 0; i < Nl; i++)
    for (n = 0; n < N; n++) d_a(i, n) = rho(!cR * i, n) * h(i, n);
  /* derivees a travers rho et en */
  const tabs_t d_vide = {}, &d_rho = pch_rho ? pch_rho->derivees() : d_vide, &d_h = ch_h.derivees();
  std::set<std::string> vars; //liste de toutes les derivees possibles
  for (auto && d_c : d_rho) vars.insert(d_c.first);
  for (auto && d_c : d_h) vars.insert(d_c.first);
  for (auto && var : vars)
    {
      const DoubleTab *dr = d_rho.count(var) ? &d_rho.at(var) : NULL, *dh = d_h.count(var) ? &d_h.at(var) : NULL;
      DoubleTab& d_v = deriv[var];
      for (d_v.resize(Nl, N), i = 0; i < Nl; i++)
        for (n = 0; n < N; n++)
          d_v(i, n) = alpha(i, n) * ((dr ? (*dr)(i, n) * h(i, n) : 0) + (dh ? rho(!cR * i, n) * (*dh)(i, n) : 0));
    }
}
References Champ_base::a_une_zone_dis_base(), TRUSTTab< _TYPE_ >::dimension_tot(), Fluide_base::enthalpie(), TRUSTVect< _TYPE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Equation_base::probleme(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Deriv_Champ_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_base::valeur_aux(), Champ_base::valeur_aux_bords(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Equation_base::zone_dis().
champ_convecte()
Champ_Inc_base & Energie_Multiphase::champ_convecte () const inline override virtual
Reimplemented from Equation_base.
Definition at line 82 of file Energie_Multiphase.h.
  {
    return champ_convecte_.valeur();
  }
References Equation_base::champ_convecte_, and Deriv_Champ_Inc_base::valeur().
cree_instance()
Objet_U * Energie_Multiphase::cree_instance () static
Definition at line 36 of file Energie_Multiphase.cpp.
diffusivite_pour_pas_de_temps()
const Champ_base & Energie_Multiphase::diffusivite_pour_pas_de_temps () const override virtual
Reimplemented from Convection_Diffusion_std.
Definition at line 155 of file Energie_Multiphase.cpp.
{
  return milieu().diffusivite();
}
References Milieu_base::diffusivite(), and milieu().
diffusivite_pour_transport()
const Champ_Don & Energie_Multiphase::diffusivite_pour_transport () const override virtual
Reimplemented from Convection_Diffusion_std.
Definition at line 150 of file Energie_Multiphase.cpp.
{
  return milieu().conductivite();
}
References Milieu_base::conductivite(), and milieu().
dimensionner_blocs()
void Energie_Multiphase::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Equation_base.
Definition at line 381 of file Energie_Multiphase.cpp.
{
  Convection_Diffusion_std::dimensionner_blocs(matrices, semi_impl);
  if (evanescence.non_nul()) evanescence.valeur().dimensionner_blocs(matrices, semi_impl);
}
References Equation_base::dimensionner_blocs(), Operateur_base::dimensionner_blocs(), evanescence, O_U_Ptr::non_nul(), and Deriv_Operateur_Evanescence_base::valeur().
dimensionner_matrice_sans_mem()
void Energie_Multiphase::dimensionner_matrice_sans_mem (Matrice_Morse & matrice) override virtual
Reimplemented from Equation_base.
Definition at line 367 of file Energie_Multiphase.cpp.
{
  Convection_Diffusion_std::dimensionner_matrice_sans_mem(matrice);
  if (evanescence.non_nul()) evanescence.valeur().dimensionner(matrice);
}
References Operateur_base::dimensionner(), Equation_base::dimensionner_matrice_sans_mem(), evanescence, O_U_Ptr::non_nul(), and Deriv_Operateur_Evanescence_base::valeur().
discretiser()
void Energie_Multiphase::discretiser () override virtual
Discretise l'equation.
Reimplemented from Equation_base.
Definition at line 174 of file Energie_Multiphase.cpp.
{
  const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
  Cerr << "Energy equation discretization " << finl;
  const Pb_Multiphase& pb = ref_cast(Pb_Multiphase, probleme());
  dis.temperature(schema_temps(), zone_dis(), l_inco_ch, pb.nb_phases());
  l_inco_ch.valeur().fixer_nature_du_champ(pb.nb_phases() == 1 ? scalaire : pb.nb_phases() == dimension ? vectoriel : multi_scalaire); //pfft
  for (int i = 0; i < pb.nb_phases(); i++)
    l_inco_ch.valeur().fixer_nom_compo(i, Nom("temperature_") + pb.nom_phase(i));
  champs_compris_.ajoute_champ(l_inco_ch);
  Equation_base::discretiser();
  Cerr << "Energie_Multiphase::discretiser() ok" << finl;
}
References Champs_compris::ajoute_champ(), Cerr, Equation_base::champs_compris_, Objet_U::dimension, Equation_base::discretisation(), Equation_base::discretiser(), finl, Field_base::fixer_nature_du_champ(), Field_base::fixer_nom_compo(), l_inco_ch, multi_scalaire, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Equation_base::probleme(), ref_cast, scalaire, Equation_base::schema_temps(), Discret_Thermique::temperature(), Deriv_Champ_Inc_base::valeur(), vectoriel, and Equation_base::zone_dis().
domaine_application()
const Motcle & Energie_Multiphase::domaine_application () const override virtual
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
Returns
Motcle&
Signification: le nom du domaine d'application de l'equation
Contraintes: toujours egal a "Thermique"
Reimplemented from Equation_base.
Definition at line 342 of file Energie_Multiphase.cpp.
{
  static Motcle mot("Thermique");
  return mot;
}
duplique()
int Energie_Multiphase::duplique () const override virtual
Implements Objet_U.
Definition at line 36 of file Energie_Multiphase.cpp.
fluide() [1/2]
Fluide_base & Energie_Multiphase::fluide ()
Renvoie le fluide incompressible associe a l'equation.
Returns
Fluide_base&
Signification: le fluide incompressible associe a l'equation
Contraintes:
Definition at line 272 of file Energie_Multiphase.cpp.
{
  assert(le_fluide.non_nul());
  return le_fluide.valeur();
}
References le_fluide, O_U_Ptr::non_nul(), and Ref_Fluide_base::valeur().
fluide() [2/2]
const Fluide_base & Energie_Multiphase::fluide () const
Renvoie le fluide incompressible associe a l'equation.
(version const)
Returns
Fluide_base&
Signification: le fluide incompressible associe a l'equation
Contraintes: reference constante
Definition at line 247 of file Energie_Multiphase.cpp.
{
  if (!le_fluide.non_nul())
    {
      Cerr << "You forgot to associate the fluid to the problem named " << probleme().le_nom() << finl;
      Process::exit();
    }
  return le_fluide.valeur();
}
References Cerr, Process::exit(), finl, le_fluide, Probleme_base::le_nom(), O_U_Ptr::non_nul(), Equation_base::probleme(), and Ref_Fluide_base::valeur().
Referenced by milieu().
get_fonc_champ_conserve()
std::pair< std::string, fonc_calc_t > Energie_Multiphase::get_fonc_champ_conserve () const inline override virtual
Reimplemented from Equation_base.
Definition at line 71 of file Energie_Multiphase.h.
  {
    return { "alpha_rho_e", calculer_alpha_rho_e };
  }
References calculer_alpha_rho_e().
get_fonc_champ_convecte()
virtual std::pair< std::string, fonc_calc_t > Energie_Multiphase::get_fonc_champ_convecte () const inline virtual
Definition at line 77 of file Energie_Multiphase.h.
  {
    return { "alpha_rho_e_conv", calculer_alpha_rho_e };
  }
References calculer_alpha_rho_e().
Referenced by init_champ_convecte().
get_info()
const Type_info * Energie_Multiphase::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_std.
Definition at line 36 of file Energie_Multiphase.cpp.
has_champ_convecte()
int Energie_Multiphase::has_champ_convecte () const inline override virtual
Reimplemented from Equation_base.
Definition at line 86 of file Energie_Multiphase.h.
  {
    return champ_convecte_.non_nul();
  }
References Equation_base::champ_convecte_, and O_U_Ptr::non_nul().
has_interface_blocs()
int Energie_Multiphase::has_interface_blocs () const override virtual
Reimplemented from Equation_base.
Definition at line 373 of file Energie_Multiphase.cpp.
{
  int ok = Convection_Diffusion_std::has_interface_blocs();
  if (evanescence.non_nul()) ok &= evanescence.valeur().has_interface_blocs();
  return ok;
}
References evanescence, Equation_base::has_interface_blocs(), Operateur_base::has_interface_blocs(), O_U_Ptr::non_nul(), and Deriv_Operateur_Evanescence_base::valeur().
impr()
int Energie_Multiphase::impr (Sortie & os) const override virtual
Impression des flux sur les bords sur un flot de sortie.
Appelle Equation_base::impr(Sortie&)
Returns
int
Signification: code de retour propage
Contraintes:
Reimplemented from Equation_base.
Definition at line 294 of file Energie_Multiphase.cpp.
{
  return Equation_base::impr(os);
}
References Equation_base::impr().
inconnue() [1/2]
const Champ_Inc & Energie_Multiphase::inconnue () const inline override virtual
Renvoie le champ inconnue representant l'inconnue (T ou H)
(version const)
Returns
Champ_Inc&
Signification: le champ inconnue representant la temperature (GP)
ou l'enthalpie (GR)
Contraintes: reference constante
Implements Convection_Diffusion_std.
Definition at line 118 of file Energie_Multiphase.h.
{
  return l_inco_ch;
}
References l_inco_ch.
Referenced by Flux_interfacial_PolyMAC::ajouter_blocs(), and init_champ_convecte().
inconnue() [2/2]
Champ_Inc & Energie_Multiphase::inconnue () inline override virtual
Renvoie le champ inconnue representant l'inconnue (T ou H)
Returns
Champ_Inc&
Signification: le champ inconnue representant la temperature (GP)
ou l'enthalpie (GR)
Contraintes:
Implements Convection_Diffusion_std.
Definition at line 139 of file Energie_Multiphase.h.
{
  return l_inco_ch;
}
References l_inco_ch.
info()
const Type_info * Energie_Multiphase::info () static
Definition at line 36 of file Energie_Multiphase.cpp.
init_champ_convecte()
void Energie_Multiphase::init_champ_convecte () const override virtual
Reimplemented from Equation_base.
Definition at line 480 of file Energie_Multiphase.cpp.
{
  if (champ_convecte_.non_nul()) return; //deja fait
  int Nt = inconnue()->nb_valeurs_temporelles(), Nl = inconnue().valeurs().size_reelle_ok() ? inconnue().valeurs().dimension(0) : -1, Nc = inconnue().valeurs().line_size();
// champ_convecte_ : meme type / support que l'inconnue
  discretisation().creer_champ(champ_convecte_, zone_dis().valeur(), inconnue().valeur().que_suis_je(), "N/A", "N/A", Nc, Nl, Nt, schema_temps().temps_courant());
  champ_convecte_->associer_eqn(*this);
  auto nom_fonc = get_fonc_champ_convecte();
  champ_convecte_->nommer(nom_fonc.first);
  champ_convecte_->init_champ_calcule(*this, nom_fonc.second);
}
References Champ_Inc::associer_eqn(), Equation_base::champ_convecte_, Discretisation_base::creer_champ(), TRUSTTab< _TYPE_ >::dimension(), Equation_base::discretisation(), get_fonc_champ_convecte(), inconnue(), TRUSTVect< _TYPE_ >::line_size(), Champ_Inc::nb_valeurs_temporelles(), Objet_U::nommer(), O_U_Ptr::non_nul(), Objet_U::que_suis_je(), Equation_base::schema_temps(), TRUSTVect< _TYPE_ >::size_reelle_ok(), valeur(), Champ_Inc::valeurs(), and Equation_base::zone_dis().
lire_motcle_non_standard()
int Energie_Multiphase::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Convection_Diffusion_std.
Definition at line 121 of file Energie_Multiphase.cpp.
{
  if (mot=="evanescence") is >> evanescence;
  else return Convection_Diffusion_std::lire_motcle_non_standard(mot, is);
  return 1;
}
References evanescence, and Convection_Diffusion_std::lire_motcle_non_standard().
milieu() [1/2]
const Milieu_base & Energie_Multiphase::milieu () const override virtual
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
(version const)
Returns
Milieu_base&
Signification: le Fluide_base upcaste en Milieu_base
Contraintes: reference constante
Implements Equation_base.
Definition at line 205 of file Energie_Multiphase.cpp.
{
  return fluide();
}
References fluide().
Referenced by diffusivite_pour_pas_de_temps(), and diffusivite_pour_transport().
milieu() [2/2]
Milieu_base & Energie_Multiphase::milieu () override virtual
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
Returns
Milieu_base&
Signification: le Fluide_base upcaste en Milieu_base
Contraintes:
Implements Equation_base.
Definition at line 226 of file Energie_Multiphase.cpp.
{
  return fluide();
}
References fluide().
printOn()
Sortie & Energie_Multiphase::printOn (Sortie & is) const override protected virtual
Simple appel a: Convection_Diffusion_std::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Convection_Diffusion_std.
Definition at line 53 of file Energie_Multiphase.cpp.
{
  return Convection_Diffusion_std::printOn(is);
}
References Convection_Diffusion_std::printOn().
readOn()
Entree & Energie_Multiphase::readOn (Entree & is) override protected virtual
Verifie si l'equation a une inconnue et un fluide associe
et appelle Convection_Diffusion_std::readOn(Entree&).
Returns
Entree& is
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Convection_Diffusion_std.
Definition at line 74 of file Energie_Multiphase.cpp.
{
  assert(l_inco_ch.non_nul());
  assert(le_fluide.non_nul());
  evanescence.associer_eqn(*this);
  Convection_Diffusion_std::readOn(is);
// if (!evanescence.non_nul())
// {
// EChaine eva("{ homogene { alpha_res 1e-6 } }");
// eva >> evanescence;
// }
// Nom unite;
// if (dimension+bidim_axi==2) unite="[W/m]";
// else unite="[W]";
  terme_convectif.set_fichier("Convection_chaleur");
  terme_convectif.set_description((Nom)"Convective heat transfer rate=Integral(-h*u*ndS) [W] if SI units used");
  terme_diffusif.set_fichier("Diffusion_chaleur");
// terme_diffusif.set_description((Nom)"Conduction heat transfer rate=Integral(lambda*grad(T)*ndS) "+unite);
  terme_diffusif.set_description((Nom)"Conduction heat transfer rate=Integral(lambda*grad(T)*ndS) [W] if SI units used");
// Special treatment for Pb_HEM
// We enforce the presence of a source term related to the
// interfacial flux automatically defined in the Pb_HEM class.
  if (probleme().que_suis_je() == "Pb_HEM")
    {
      int check_source_FICC(0);
      for (int ii = 0; ii < sources().size(); ii++)
        if (sources()(ii).valeur().que_suis_je().debute_par("Flux_interfacial"))
          check_source_FICC = 1;
      if (check_source_FICC == 0)
        {
          EChaine source_FI("{ flux_interfacial }");
          lire_sources(source_FI);
        }
    }
// End of Pb_HEM special treatment
  return is;
}
References MorEqn::associer_eqn(), evanescence, l_inco_ch, le_fluide, Equation_base::lire_sources(), O_U_Ptr::non_nul(), Equation_base::probleme(), Objet_U::que_suis_je(), Convection_Diffusion_std::readOn(), Operateur::set_description(), Operateur::set_fichier(), liste::size(), Equation_base::sources(), Convection_Diffusion_std::terme_convectif, Convection_Diffusion_std::terme_diffusif, and valeur().
self_cast() [1/2]
const Energie_Multiphase & Energie_Multiphase::self_cast (const Objet_U & r) static
Definition at line 36 of file Energie_Multiphase.cpp.
self_cast() [2/2]
Energie_Multiphase & Energie_Multiphase::self_cast (Objet_U & r) static
Definition at line 36 of file Energie_Multiphase.cpp.
set_param()
void Energie_Multiphase::set_param (Param & param) override virtual
Reimplemented from Convection_Diffusion_std.
Definition at line 115 of file Energie_Multiphase.cpp.
{
  Convection_Diffusion_std::set_param(param);
  param.ajouter_non_std("evanescence|vanishing",(this));
}
References Param::ajouter_non_std(), and Convection_Diffusion_std::set_param().
taille_memoire()
unsigned Energie_Multiphase::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 36 of file Energie_Multiphase.cpp.
verifie_ch_init_nb_comp_cl()
void Energie_Multiphase::verifie_ch_init_nb_comp_cl (const Champ_Inc_base & ch_ref, const int nb_comp, const Cond_lim_base & cl) const override virtual
Verification du nombre de composantes lues pour la specification d un champ.
Dans Energie_Multiphase, les conditions aux limites de type "paroi" ne prennent
qu'une compposante lorsqu'une correlation "flux_parietal" est definie au niveau du probleme.
Reimplemented from Equation_base.
Definition at line 311 of file Energie_Multiphase.cpp.
{
// si on verifie une CL de type
  if (ref_cast(Pb_Multiphase, probleme()).has_correlation("flux_parietal")
      && (sub_type(Neumann_paroi, cl) || sub_type(Scalaire_impose_paroi, cl) || sub_type(Echange_global_impose, cl)))
    {
      if (nb_comp == 1) return; //OK
      Cerr << "Energie_Multiphase : when using a Flux_parietal correlation, only one wall temperature/heat flux "
           << "can be specified at the boundary " << cl.le_nom() << " . Please provide 1 component instead of " << nb_comp << "!" << finl;
      Process::exit();
    }
  else Convection_Diffusion_std::verifie_ch_init_nb_comp(ch_ref, nb_comp); //traitement normal
}
References Cerr, Process::exit(), finl, Objet_U::le_nom(), Equation_base::probleme(), ref_cast, sub_type, and Equation_base::verifie_ch_init_nb_comp().
Member Data Documentation
evanescence
Operateur_Evanescence Energie_Multiphase::evanescence protected
Definition at line 95 of file Energie_Multiphase.h.
Referenced by assembler_blocs_avec_inertie(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), has_interface_blocs(), lire_motcle_non_standard(), and readOn().
info_obj
const Type_info Energie_Multiphase::info_obj static
Definition at line 37 of file Energie_Multiphase.h.
l_inco_ch
Champ_Inc Energie_Multiphase::l_inco_ch protected
Definition at line 94 of file Energie_Multiphase.h.
Referenced by discretiser(), inconnue(), and readOn().
le_fluide
Ref_Fluide_base Energie_Multiphase::le_fluide protected
Definition at line 96 of file Energie_Multiphase.h.
Referenced by associer_fluide(), fluide(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Equations/Energie_Multiphase.h
src/ThHyd/Multiphase/Equations/Energie_Multiphase.cpp