TRUST: Op_Grad_P1NC_to_P0 Class Reference
Op_Grad_P1NC_to_P0 Class Reference
class Op_Grad_P1NC_to_P0
Cette classe represente un operateur de gradient
La discretisation est VEF
On calcule le gradient d'un champ_P1NC a une composante (temperature,concentration)
et le champ de sortie est P0 (aux elements)
#include <Op_Grad_P1NC_to_P0.h>
Public Member Functions
Op_Grad_P1NC_to_P0 ()
~Op_Grad_P1NC_to_P0 ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Grad_P1NC_to_P0 & self_cast (Objet_U &)
static const Op_Grad_P1NC_to_P0 & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Detailed Description
class Op_Grad_P1NC_to_P0
Cette classe represente un operateur de gradient
La discretisation est VEF
On calcule le gradient d'un champ_P1NC a une composante (temperature,concentration)
et le champ de sortie est P0 (aux elements)
Definition at line 54 of file Op_Grad_P1NC_to_P0.h.
Constructor & Destructor Documentation
Op_Grad_P1NC_to_P0::Op_Grad_P1NC_to_P0 ()
Definition at line 26 of file Op_Grad_P1NC_to_P0.cpp.
Op_Grad_P1NC_to_P0::~Op_Grad_P1NC_to_P0 ()
Definition at line 26 of file Op_Grad_P1NC_to_P0.cpp.
Member Function Documentation
DoubleTab & Op_Grad_P1NC_to_P0::ajouter (const DoubleTab & valeurs_source, DoubleTab & grad) const [virtual]
Reimplemented from Operateur_Grad_base.
Definition at line 59 of file Op_Grad_P1NC_to_P0.cpp.
References Champ_P1NC::calcul_gradient(), DoubleVect::echange_espace_virtuel(), la_zcl_vef, and Ref_Zone_Cl_VEF::valeur().
Referenced by calculer().
{
  Champ_P1NC::calcul_gradient(valeurs_source,grad,la_zcl_vef.valeur());
  grad.echange_espace_virtuel();
  return grad;
}
void Op_Grad_P1NC_to_P0::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis, const Champ_Inc &) [virtual]
Implements Operateur_base.
Definition at line 48 of file Op_Grad_P1NC_to_P0.cpp.
References la_zcl_vef, la_zone_vef, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  const Zone_VEF& zvef = ref_cast(Zone_VEF, zone_dis.valeur());
  const Zone_Cl_VEF& zclvef = ref_cast(Zone_Cl_VEF, zone_Cl_dis.valeur());
  la_zone_vef = zvef;
  la_zcl_vef = zclvef;
}
DoubleTab & Op_Grad_P1NC_to_P0::calculer (const DoubleTab & valeurs_source, DoubleTab & grad) const [virtual]
Reimplemented from Operateur_base.
Definition at line 66 of file Op_Grad_P1NC_to_P0.cpp.
References ajouter().
{
  grad = 0;
  return ajouter(valeurs_source,grad);
}
Objet_U * Op_Grad_P1NC_to_P0::cree_instance () [static]
Definition at line 26 of file Op_Grad_P1NC_to_P0.cpp.
int Op_Grad_P1NC_to_P0::duplique () const [virtual]
Implements Operateur_Grad_base.
Definition at line 26 of file Op_Grad_P1NC_to_P0.cpp.
const Type_info * Op_Grad_P1NC_to_P0::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 26 of file Op_Grad_P1NC_to_P0.cpp.
const Type_info * Op_Grad_P1NC_to_P0::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 26 of file Op_Grad_P1NC_to_P0.cpp.
Sortie & Op_Grad_P1NC_to_P0::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 32 of file Op_Grad_P1NC_to_P0.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Grad_P1NC_to_P0::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 40 of file Op_Grad_P1NC_to_P0.cpp.
{
  return s ;
}
const Op_Grad_P1NC_to_P0 & Op_Grad_P1NC_to_P0::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Operateur_Grad_base.
Definition at line 26 of file Op_Grad_P1NC_to_P0.cpp.
Op_Grad_P1NC_to_P0 & Op_Grad_P1NC_to_P0::self_cast (Objet_U & r) [static]
Reimplemented from Operateur_Grad_base.
Definition at line 26 of file Op_Grad_P1NC_to_P0.cpp.
unsigned Op_Grad_P1NC_to_P0::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Op_Grad_P1NC_to_P0.cpp.
Member Data Documentation
const Type_info Op_Grad_P1NC_to_P0::info_obj [static]
Reimplemented from Operateur_Grad_base.
Definition at line 57 of file Op_Grad_P1NC_to_P0.h.
Ref_Zone_Cl_VEF Op_Grad_P1NC_to_P0::la_zcl_vef [protected]
Definition at line 68 of file Op_Grad_P1NC_to_P0.h.
Referenced by ajouter(), and associer().
Ref_Zone_VEF Op_Grad_P1NC_to_P0::la_zone_vef [protected]
Definition at line 67 of file Op_Grad_P1NC_to_P0.h.
Referenced by associer().
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Grad_P1NC_to_P0.h
src/VEF/Operateurs/Op_Grad_P1NC_to_P0.cpp