TRUST: Matrice_Bloc_Sym Class Reference
Matrice_Bloc_Sym Class Reference
#include <Matrice_Bloc_Sym.h>
Public Member Functions
~Matrice_Bloc_Sym ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Matrice_Bloc_Sym (int N=0, int M=0)
Sortie & imprimer (Sortie &s) const override
Sortie & imprimer_formatte (Sortie &s) const override
DoubleVect & ajouter_multvect_ (const DoubleVect &x, DoubleVect &y) const override
DoubleVect & ajouter_multvectT_ (const DoubleVect &x, DoubleVect &y) const override
DoubleTab & ajouter_multTab_ (const DoubleTab &x, DoubleTab &y) const override
void BlocSymToMatMorseSym (Matrice_Morse_Sym &mat) const
void dimensionner (int N, int M) override
dimensionnement de blocs_
const Matrice & get_bloc (int i, int j) const override
(0<=i<N , i<=j<M)
Matrice & get_bloc (int i, int j) override
void get_stencil (IntTab &stencil) const override
void get_symmetric_stencil (IntTab &stencil) const override
void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const override
void get_symmetric_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const override
bool check_symmetric_block_matrix_structure (void) const
void assert_check_symmetric_block_matrix_structure (void) const
Public Member Functions inherited from Matrice_Bloc
~Matrice_Bloc ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int ordre (void) const override
int nb_lignes (void) const override
int nb_colonnes (void) const override
DoubleVect & ajouter_multvect_ (const DoubleVect &x, DoubleVect &r) const override
DoubleVect & ajouter_multvectT_ (const DoubleVect &x, DoubleVect &r) const override
DoubleTab & ajouter_multTab_ (const DoubleTab &x, DoubleTab &r) const override
void scale (const double x) override
void get_stencil (IntTab &stencil) const override
void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const override
Sortie & imprimer (Sortie &s) const override
Sortie & imprimer_formatte (Sortie &s) const override
virtual void dimensionner (int N, int M)
virtual const Matrice & get_bloc (int i, int j) const
virtual Matrice & get_bloc (int i, int j)
void build_stencil (void) override
Matrice_Bloc (int N=0, int M=0)
int dim (int d) const
si d=0 => N_ si d=1 => M_
int nb_bloc_lignes (void) const
retourne N_
int nb_bloc_colonnes (void) const
retourne M_
void remplir (const IntLists &voisins, const DoubleLists &valeurs, const DoubleVect &terme_diag, const int i, const int n)
void remplir (const IntLists &voisins, const DoubleLists &valeurs, const int i, const int n, const int j, const int m)
void remplir (const IntLists &voisins, const DoubleLists &valeurs, const DoubleVect &terme_diag, const int i, const int n, const int j, const int m)
void BlocToMatMorse (Matrice_Morse &matrix) const
Matrice_Bloc & operator*= (double x)
bool check_block_matrix_structure (void) const
void assert_check_block_matrix_structure (void) const
Public Member Functions inherited from Matrice_Base
Matrice_Base ()
~Matrice_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual int ordre () const =0
virtual int nb_lignes () const =0
virtual int nb_colonnes () const =0
virtual DoubleVect & ajouter_multvect_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleVect & ajouter_multvectT_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleTab & ajouter_multTab_ (const DoubleTab &x, DoubleTab &r) const =0
virtual DoubleVect & ajouter_multvect (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleVect & ajouter_multvectT (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleTab & ajouter_multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice represente par un tableau)
Operation: R = R + A*X.
virtual DoubleVect & multvect_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvect (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice.
Operation: r = A*x.
virtual DoubleVect & multvectT_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvectT (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice transposee.
Operation: r = AT*x.
virtual DoubleTab & multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Multiplication d'une matrice representee par un tableau par la matrice.
Operation: R = A*X.
virtual Sortie & imprimer (Sortie &) const
virtual Sortie & imprimer_formatte (Sortie &s) const
virtual void scale (const double x)=0
virtual void get_stencil (IntTab &stencil) const
virtual void get_symmetric_stencil (IntTab &stencil) const
virtual void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
virtual void get_symmetric_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
int get_stencil_size (void) const
virtual void build_stencil (void)
void set_stencil (const IntTab &stencil)
bool is_stencil_up_to_date (void) const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Matrice_Sym
virtual ~Matrice_Sym ()
Matrice_Sym ()
int get_est_definie () const
void set_est_definie (int)
void unsymmetrize_stencil (const int nb_lines, const IntTab &symmetric_stencil, IntTab &stencil) const
void unsymmetrize_stencil_and_coefficients (const int nb_lines, const IntTab &symmetric_stencil, const ArrOfDouble &symmetric_coefficients, IntTab &stencil, ArrOfDouble &coefficients) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Matrice_Bloc_Sym & self_cast (Objet_U &)
static const Matrice_Bloc_Sym & self_cast (const Objet_U &)
Static Public Member Functions inherited from Matrice_Bloc
static Objet_U * cree_instance ()
static const Type_info * info ()
static Matrice_Bloc & self_cast (Objet_U &)
static const Matrice_Bloc & self_cast (const Objet_U &)
Static Public Member Functions inherited from Matrice_Base
static const Type_info * info ()
static Matrice_Base & self_cast (Objet_U &)
static const Matrice_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Matrice_Bloc
static const Type_info info_obj
Static Public Attributes inherited from Matrice_Base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
virtual DoubleTab & ajouter_multTab_ (const DoubleTab &, DoubleTab &) const =0
virtual DoubleVect & ajouter_multvect_ (const DoubleVect &, DoubleVect &) const =0
virtual DoubleVect & ajouter_multvectT_ (const DoubleVect &, DoubleVect &) const =0
Additional Inherited Members
Protected Attributes inherited from Matrice_Bloc
Vect_Matrice blocs_
les blocs de la matrices source A
int N_
1ere dim de A
int M_
2eme dim de A
int nb_blocs_
nb total des blocs de A (= N_ * M_)
ArrOfInt offsets_
Protected Attributes inherited from Matrice_Base
bool is_stencil_up_to_date_
IntTab stencil_
Detailed Description
Definition at line 61 of file Matrice_Bloc_Sym.h.
Constructor & Destructor Documentation
~Matrice_Bloc_Sym()
Matrice_Bloc_Sym::~Matrice_Bloc_Sym ()
Definition at line 23 of file Matrice_Bloc_Sym.cpp.
Matrice_Bloc_Sym()
Matrice_Bloc_Sym::Matrice_Bloc_Sym (int N = 0, int M = 0)
Definition at line 42 of file Matrice_Bloc_Sym.cpp.
                                               : Matrice_Bloc( )
{
  dimensionner(N,M);
}
References dimensionner().
Member Function Documentation
ajouter_multTab_()
DoubleTab & Matrice_Bloc_Sym::ajouter_multTab_ (const DoubleTab & x, DoubleTab & y) const override virtual
Reimplemented from Matrice_Bloc.
Definition at line 135 of file Matrice_Bloc_Sym.cpp.
{
  Cerr <<"Matrice_Bloc_Sym::ajouter_multTab_ is not coded"<<finl<<flush;
  exit();
  return y;
}
References Cerr, Process::exit(), and finl.
ajouter_multvect_()
DoubleVect & Matrice_Bloc_Sym::ajouter_multvect_ (const DoubleVect & x, DoubleVect & y) const override virtual
Reimplemented from Matrice_Bloc.
Definition at line 73 of file Matrice_Bloc_Sym.cpp.
{
  const double * const_x_addr = x.addr();
  double* x_addr = (double *) const_x_addr;
  double* y_addr = y.addr();
// Si on met static la methode ne fonctionne pas pour une Matrice_Bloc_Sym de Matrice_Bloc_Sym
// static DoubleVect xtmp;
// static DoubleVect ytmp;
  DoubleVect xtmp;
  DoubleVect ytmp;
  int nbr_lignes;
  int nbr_colonnes;
  int decaly=0;
  for(int i=0; i<N_; i++)
    {
      int decalx=0;
      nbr_lignes=0;
      for(int j=0; j<i; j++)
        {
          const Matrice_Base& mij=get_bloc(j,i).valeur();
          nbr_colonnes=mij.nb_lignes();
          decalx+=nbr_colonnes;
        }
      for(int j=i; j<N_; j++)
        {
          const Matrice_Base& mij=get_bloc(i,j).valeur();
          if(!nbr_lignes) nbr_lignes=mij.nb_lignes();
          nbr_colonnes=mij.nb_colonnes();
          if (nbr_colonnes>0 && nbr_lignes>0)
            {
              xtmp.ref_data(x_addr+decalx,nbr_colonnes);
              assert((decalx+nbr_colonnes)<=x.size_array());
              ytmp.ref_data(y_addr+decaly,nbr_lignes);
              assert((decaly+nbr_lignes)<=y.size_array());
              mij.ajouter_multvect_(xtmp,ytmp);
              if(i!=j)
                {
                  xtmp.ref_data(x_addr+decaly,nbr_lignes);
                  assert((decaly+nbr_lignes)<=x.size_array());
                  ytmp.ref_data(y_addr+decalx,nbr_colonnes);
                  assert((decalx+nbr_colonnes)<=y.size_array());
                  mij.ajouter_multvectT_(xtmp,ytmp);
                }
              decalx+=nbr_colonnes;
            }
        }
      decaly+=nbr_lignes;
    }
  return y;
}
References TRUSTArray< _TYPE_ >::addr(), Matrice_Base::ajouter_multvect_(), Matrice_Base::ajouter_multvectT_(), get_bloc(), Matrice_Bloc::N_, Matrice_Base::nb_colonnes(), Matrice_Base::nb_lignes(), TRUSTVect< _TYPE_ >::ref_data(), TRUSTArray< _TYPE_ >::size_array(), and Deriv_Matrice_Base::valeur().
ajouter_multvectT_()
DoubleVect & Matrice_Bloc_Sym::ajouter_multvectT_ (const DoubleVect & x, DoubleVect & y) const override virtual
Reimplemented from Matrice_Bloc.
Definition at line 127 of file Matrice_Bloc_Sym.cpp.
{
  Cerr <<"Matrice_Bloc_Sym::ajouter_multvectT_ is not coded"<<finl<<flush;
  exit();
  return y;
}
References Cerr, Process::exit(), and finl.
assert_check_symmetric_block_matrix_structure()
void Matrice_Bloc_Sym::assert_check_symmetric_block_matrix_structure (void) const
Definition at line 573 of file Matrice_Bloc_Sym.cpp.
{
#ifndef NDEBUG
  if ( ! ( check_symmetric_block_matrix_structure( ) ) )
    {
      Cerr << "Error in 'Matrice_Bloc_Sym::assert_check_symmetric_block_matrix_structure( )':" << finl;
      Cerr << "  Exiting..." << finl;
      Process::exit( );
    }
#endif
}
References Cerr, check_symmetric_block_matrix_structure(), Process::exit(), and finl.
Referenced by get_stencil(), get_stencil_and_coefficients(), get_symmetric_stencil(), and get_symmetric_stencil_and_coefficients().
BlocSymToMatMorseSym()
void Matrice_Bloc_Sym::BlocSymToMatMorseSym (Matrice_Morse_Sym & mat) const
Definition at line 142 of file Matrice_Bloc_Sym.cpp.
{
  if ( Process::je_suis_maitre( ) )
    {
      Cerr << "Conversion BlocSymToMatMorseSym..." << finl;
    }
  Matrix_tools::convert_to_symmetric_morse_matrix( (*this), mat );
  mat.set_est_definie( get_est_definie( ) );
// int n=nb_lignes();
// // Dimensionnement et initialisation d'une matrice Morse
// Matrice_Morse mat_morse;
// mat_morse.dimensionner(n,n,0);
// mat_morse.tab1_=1;
// // Remplissage de cette matrice en sommant les contributions de chaque bloc
// Matrice_Morse contribution;
// int ideb=0;
// for (int ibloc=0; ibloc<nb_bloc_lignes(); ibloc++)
// {
// int nb_lignes=0;
// int jdeb=0;
// for (int jbloc=0; jbloc<ibloc; jbloc++)
// {
// if (!sub_type(Matrice_Bloc,get_bloc(jbloc,ibloc).valeur()))
// {
// Cerr << "Matrice_Bloc_Sym::BlocSymToMatMorseSym applies only to a Matrice_Bloc_Sym type matrix" << finl;
// Cerr << "constituted of Matrice_Bloc type matrixes." << finl;
// exit();
// }
// // Pour calculer le nombre de colonnes du bloc(j,i), on prend le nombre de lignes du bloc transpose bloc(i,j)
// const Matrice_Bloc& bloc = ref_cast(Matrice_Bloc,get_bloc(jbloc,ibloc).valeur());
// jdeb += bloc.nb_lignes();
// }
// for (int jbloc=ibloc; jbloc<nb_bloc_colonnes(); jbloc++)
// {
// if (!sub_type(Matrice_Bloc,get_bloc(ibloc,jbloc).valeur()))
// {
// Cerr << "Matrice_Bloc_Sym::BlocSymToMatMorseSym applies only to a Matrice_Bloc_Sym type matrix" << finl;
// Cerr << "constituted of Matrice_Bloc type matrixes." << finl;
// exit();
// }
// const Matrice_Bloc& bloc = ref_cast(Matrice_Bloc,get_bloc(ibloc,jbloc).valeur());
// // Transforme la Matrice_Bloc bloc en Matrice_Morse bloc_en_morse
// Matrice_Morse bloc_en_morse;
// bloc.BlocToMatMorse(bloc_en_morse);
// // Remplissage de la matrice contribution
// contribution.remplir(ideb, jdeb, n, n, bloc_en_morse);
// if (jbloc==ibloc) nb_lignes = bloc.nb_lignes();
// assert(nb_lignes==bloc_en_morse.nb_lignes());
// assert(nb_lignes==bloc.nb_lignes());
// jdeb += bloc.nb_colonnes();
// mat_morse += contribution;
// }
// ideb+=nb_lignes;
// }
// // Remplissage de la Matrice_Morse_Symetrique
// mat=mat_morse;
// // La matrice est t'elle definie ? On regarde son bloc(0,0)
// //  const Matrice_Bloc& bloc=ref_cast(Matrice_Bloc,get_bloc(0,0).valeur());
// //  const Matrice_Morse_Sym& sous_bloc=ref_cast(Matrice_Morse_Sym,bloc.get_bloc(0,0).valeur());
// //  mat.set_est_definie(sous_bloc.get_est_definie());
// mat.set_est_definie(get_est_definie());
// Debut test
  int test=0;
  if(test)
    {
      int n = nb_lignes( );
      DoubleVect x(n);
      DoubleVect resu1(n);
      DoubleVect resu2(n);
      for (int i=0; i<x.size(); i++)
        {
          x=0;
          resu1=0;
          resu2=0;
          x(i)=1;
          mat.multvect(x,resu1);
          multvect(x,resu2);
          Journal() << "Test Conversion Natif/Morse " << i << "/" << x.size() << ":" << mp_norme_vect(resu1) << " " << mp_norme_vect(resu2) << finl;
          for (int j=0; j<x.size(); j++)
            {
              if (!est_egal(resu1(j),resu2(j)))
                {
                  Journal() << "Test Conversion Natif/Morse A(" << i << "," << j << ") : " << resu1(j) << " " << resu2(j) << finl;
                  Journal()<<"Format Matrice_Bloc_Sym:" <<finl;
                  imprimer_formatte(Journal());
                  Journal()<<"Format Morse:" <<finl;
                  mat.imprimer_formatte(Journal());
                  Cerr<<"Error in Matrice_Bloc_Sym::BlocSymToMatMorseSym" << finl;
                  Cerr<<"See the .log files of the calculation." << finl;
                  exit();
                }
            }
        }
    }
// Matrice_Morse mat1;
// Matrice_Morse mat2;
// Matrix_tools::convert_to_morse_matrix(result, mat1);
// Matrix_tools::convert_to_morse_matrix(mat, mat2);
// mat2 *= -1;
// mat1 += mat2;
// Cerr << "***********************************" << finl;
// Cerr << " bloc_sym to morse_sym:" << finl;
// Cerr << "min  = " << mp_min_vect(mat1.coeff_,VECT_ALL_ITEMS) << finl;
// Cerr << "imin = " << local_imin_vect(mat1.coeff_,VECT_ALL_ITEMS) << finl;
// Cerr << "max  = " << mp_max_vect(mat1.coeff_,VECT_ALL_ITEMS) << finl;
// Cerr << "imax = " << local_imax_vect(mat1.coeff_,VECT_ALL_ITEMS) << finl;
// Cerr << "***********************************" << finl;
}
References Cerr, Matrix_tools::convert_to_symmetric_morse_matrix(), est_egal(), Process::exit(), finl, Matrice_Sym::get_est_definie(), imprimer_formatte(), Matrice_Morse_Sym::imprimer_formatte(), Process::je_suis_maitre(), Process::Journal(), mp_norme_vect(), Matrice_Base::multvect(), Matrice_Bloc::nb_lignes(), Matrice_Sym::set_est_definie(), TRUSTVect< _TYPE_ >::size(), and test().
Referenced by Precond_local::prepare_(), and Solv_Petsc::resoudre_systeme().
check_symmetric_block_matrix_structure()
bool Matrice_Bloc_Sym::check_symmetric_block_matrix_structure (void) const
Definition at line 535 of file Matrice_Bloc_Sym.cpp.
{
  const int nb_line_blocks   = nb_bloc_lignes( );
  const int nb_column_blocks = nb_bloc_colonnes( );
  for ( int i=0; i<nb_line_blocks; ++i )
    {
      int nb_lines   = get_bloc( i, i ).valeur( ).nb_lignes( );
      int nb_columns = get_bloc( i, i ).valeur( ).nb_colonnes( );
      if  ( nb_lines != nb_columns )
        {
          Cerr << "bloc( " << i << ", " << i << " ) is not square" << finl;
          return false;
        }
      for ( int j=0; j<i; ++j )
        {
          if ( nb_columns != get_bloc( j, i ).valeur( ).nb_colonnes( ) )
            {
              Cerr << "Invalid number of columns in bloc ( " << j << ", " << i << " )" << finl;
              return false;
            }
        }
      for ( int j=i; j<nb_column_blocks; ++j )
        {
          if ( nb_lines != get_bloc( i, j ).valeur( ).nb_lignes( ) )
            {
              Cerr << "Invalid number of lines in bloc ( " << i << ", " << j << " )" << finl;
              return false;
            }
        }
    }
  return true;
}
References Cerr, finl, get_bloc(), Matrice_Bloc::nb_bloc_colonnes(), Matrice_Bloc::nb_bloc_lignes(), Matrice_Base::nb_colonnes(), Matrice_Bloc::nb_colonnes(), Matrice_Base::nb_lignes(), Matrice_Bloc::nb_lignes(), Deriv_Matrice_Base::valeur(), and valeur().
Referenced by assert_check_symmetric_block_matrix_structure().
cree_instance()
Objet_U * Matrice_Bloc_Sym::cree_instance () static
Definition at line 23 of file Matrice_Bloc_Sym.cpp.
dimensionner()
void Matrice_Bloc_Sym::dimensionner (int N, int M) override virtual
dimensionnement de blocs_
Reimplemented from Matrice_Bloc.
Definition at line 260 of file Matrice_Bloc_Sym.cpp.
{
  if(N!=M)
    {
      Cerr << "Trying to size a Matrice_Bloc_Sym type matrix not squared !!"
           <<finl<<flush;
      exit();
    }
  N_ = N;
  M_ = M;
  nb_blocs_ = (N_*(N_+1))/2 ;
  blocs_.dimensionner(nb_blocs_);
}
References Matrice_Bloc::blocs_, Cerr, vect_impl::dimensionner(), Process::exit(), finl, Matrice_Bloc::M_, Matrice_Bloc::N_, and Matrice_Bloc::nb_blocs_.
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), and Matrice_Bloc_Sym().
duplique()
int Matrice_Bloc_Sym::duplique () const override virtual
Reimplemented from Matrice_Bloc.
Definition at line 23 of file Matrice_Bloc_Sym.cpp.
get_bloc() [1/2]
const Matrice & Matrice_Bloc_Sym::get_bloc (int i, int j) const override virtual
(0<=i<N , i<=j<M)
Reimplemented from Matrice_Bloc.
Definition at line 274 of file Matrice_Bloc_Sym.cpp.
{
  if (j<i || i<0 || i>=N_ || j<0 || j>=M_)
    {
      Cerr << "Matrice_Bloc_Sym::bloc("<<i<<","<<j<<") does not exist." << finl;
      Process::exit();
    }
  return blocs_[i*(N_-1)-i*(i-1)/2+j];
}
References Matrice_Bloc::blocs_, Cerr, Process::exit(), finl, Matrice_Bloc::M_, and Matrice_Bloc::N_.
Referenced by ajouter_multvect_(), Assembleur_P_VEFPreP1B::assembler_mat(), Assembleur_P_VEFPreP1B::changer_base_matrice(), check_symmetric_block_matrix_structure(), get_symmetric_stencil(), get_symmetric_stencil_and_coefficients(), Assembleur_P_VEFPreP1B::modifier_matrice(), PrecondA::preconditionner_(), Precond_local::prepare_(), PrecondA::prepare_(), Solv_GCP_NS::resoudre_systeme(), SSOR::ssor(), and zero().
get_bloc() [2/2]
Matrice & Matrice_Bloc_Sym::get_bloc (int i, int j) override virtual
Reimplemented from Matrice_Bloc.
Definition at line 284 of file Matrice_Bloc_Sym.cpp.
{
  if (j<i || i<0 || i>=N_ || j<0 || j>=M_)
    {
      Cerr << "Matrice_Bloc_Sym::bloc(" << i << "," << j << ") out of range : N=" << N_ << " M_=" << M_ << finl;
      Process::exit();
    }
  return blocs_[i*(N_-1)-i*(i-1)/2+j];
}
References Matrice_Bloc::blocs_, Cerr, Process::exit(), finl, Matrice_Bloc::M_, and Matrice_Bloc::N_.
get_info()
const Type_info * Matrice_Bloc_Sym::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Matrice_Bloc.
Definition at line 23 of file Matrice_Bloc_Sym.cpp.
get_stencil()
void Matrice_Bloc_Sym::get_stencil (IntTab & stencil) const override virtual
Reimplemented from Matrice_Bloc.
Definition at line 294 of file Matrice_Bloc_Sym.cpp.
{
  assert_check_symmetric_block_matrix_structure( );
  IntTab symmetric_stencil;
  get_symmetric_stencil( symmetric_stencil );
  Matrice_Sym::unsymmetrize_stencil( nb_lignes( ),
                                     symmetric_stencil,
                                     stencil );
}
References assert_check_symmetric_block_matrix_structure(), get_symmetric_stencil(), Matrice_Bloc::nb_lignes(), and Matrice_Sym::unsymmetrize_stencil().
get_stencil_and_coefficients()
void Matrice_Bloc_Sym::get_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const override virtual
Reimplemented from Matrice_Bloc.
Definition at line 407 of file Matrice_Bloc_Sym.cpp.
{
  assert_check_symmetric_block_matrix_structure( );
  IntTab symmetric_stencil;
  ArrOfDouble symmetric_coefficients;
  get_symmetric_stencil_and_coefficients( symmetric_stencil, symmetric_coefficients );
  Matrice_Sym::unsymmetrize_stencil_and_coefficients( nb_lignes( ),
                                                      symmetric_stencil,
                                                      symmetric_coefficients,
                                                      stencil,
                                                      coefficients );
}
References assert_check_symmetric_block_matrix_structure(), get_symmetric_stencil_and_coefficients(), Matrice_Bloc::nb_lignes(), and Matrice_Sym::unsymmetrize_stencil_and_coefficients().
get_symmetric_stencil()
void Matrice_Bloc_Sym::get_symmetric_stencil (IntTab & stencil) const override virtual
Reimplemented from Matrice_Base.
Definition at line 306 of file Matrice_Bloc_Sym.cpp.
{
  assert_check_symmetric_block_matrix_structure( );
  const int nb_line_blocks   = nb_bloc_lignes( );
  const int nb_column_blocks = nb_bloc_colonnes( );
  const int nb_stencils      = nb_blocs_;
  VECT( IntTab ) local_stencils;
  local_stencils.dimensionner( nb_stencils );
  int imin  = 0;
  int imax  = 0;
  int jmin  = 0;
  int jmax  = 0;
  int jprev = 0;
  for ( int i=0; i<nb_line_blocks; ++i )
    {
      for ( int j=i; j<nb_column_blocks; ++j )
        {
          const Matrice_Base& local_matrix = get_bloc( i, j ).valeur( );
          imax  = imin + local_matrix.nb_lignes( );
          jmax  = jmin + local_matrix.nb_colonnes( );
          jprev = ( i==j ) ? jmax : jprev;
          int stencil_index = i *( nb_line_blocks - 1 ) - i * ( i - 1) / 2 + j;
          IntTab& local_stencil_ = local_stencils[ stencil_index ];
          if ( i == j )
            {
              local_matrix.get_symmetric_stencil( local_stencil_ );
            }
          else
            {
              local_matrix.get_stencil( local_stencil_ );
            }
          const int size = local_stencil_.dimension( 0 );
          for ( int k=0; k<size; ++k )
            {
              local_stencil_( k, 0 ) += imin;
              local_stencil_( k, 1 ) += jmin;
            }
          jmin = jmax;
        }
      imin = imax;
      jmin = jprev;
    }
  const int nb_lines = nb_lignes( );
  ArrOfInt offsets( nb_lines + 1 );
  offsets[ 0 ] = 0;
  for ( int i=0; i<nb_stencils; ++i )
    {
      const IntTab& local_stencil_ = local_stencils[ i ];
      const int size = local_stencil_.dimension( 0 );
      for ( int k=0; k<size; ++k )
        {
          const int line = local_stencil_( k, 0 );
          offsets[ line + 1 ] += 1;
        }
    }
  for ( int i=0; i<nb_lines; ++i )
    {
      offsets[ i + 1 ] += offsets[ i ];
    }
  const int stencil_size = offsets[ nb_lines ];
  stencil.resize( stencil_size, 2 );
  stencil = -1;
  for ( int i=0; i<nb_stencils; ++i )
    {
      const IntTab& local_stencil_ = local_stencils[ i ];
      const int size = local_stencil_.dimension( 0 );
      for ( int k=0; k<size; ++k )
        {
          const int line   = local_stencil_( k, 0 );
          const int column = local_stencil_( k, 1 );
          const int index  = offsets[ line ];
          assert( stencil( index, 0 ) < 0 );
          assert( stencil( index, 1 ) < 0 );
          assert( index < offsets[ line + 1 ] );
          stencil( index, 0 ) = line;
          stencil( index, 1 ) = column;
          offsets[ line ] += 1;
        }
    }
}
References assert_check_symmetric_block_matrix_structure(), TRUSTTab< _TYPE_ >::dimension(), get_bloc(), Matrice_Base::get_stencil(), Matrice_Base::get_symmetric_stencil(), Matrice_Bloc::nb_bloc_colonnes(), Matrice_Bloc::nb_bloc_lignes(), Matrice_Bloc::nb_blocs_, Matrice_Base::nb_colonnes(), Matrice_Base::nb_lignes(), Matrice_Bloc::nb_lignes(), TRUSTTab< _TYPE_ >::resize(), Deriv_Matrice_Base::valeur(), and VECT.
Referenced by get_stencil().
get_symmetric_stencil_and_coefficients()
void Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const override virtual
Reimplemented from Matrice_Base.
Definition at line 423 of file Matrice_Bloc_Sym.cpp.
{
  assert_check_symmetric_block_matrix_structure( );
  const int nb_line_blocks   = nb_bloc_lignes( );
  const int nb_column_blocks = nb_bloc_colonnes( );
  const int nb_stencils      = nb_blocs_;
  VECT( IntTab ) local_stencils;
  local_stencils.dimensionner( nb_stencils );
  VECT( ArrOfDouble ) local_coefficients;
  local_coefficients.dimensionner( nb_stencils );
  int imin  = 0;
  int imax  = 0;
  int jmin  = 0;
  int jmax  = 0;
  int jprev = 0;
  for ( int i=0; i<nb_line_blocks; ++i )
    {
      for ( int j=i; j<nb_column_blocks; ++j )
        {
          const Matrice_Base& local_matrix = get_bloc( i, j ).valeur( );
          imax  = imin + local_matrix.nb_lignes( );
          jmax  = jmin + local_matrix.nb_colonnes( );
          jprev = ( i==j ) ? jmax : jprev;
          int stencil_index = i *( nb_line_blocks - 1 ) - i * ( i - 1) / 2 + j;
          IntTab&      local_stencil_      = local_stencils[ stencil_index ];
          ArrOfDouble& coefficients_       = local_coefficients[ stencil_index ];
          if ( i == j )
            {
              local_matrix.get_symmetric_stencil_and_coefficients( local_stencil_, coefficients_ );
            }
          else
            {
              local_matrix.get_stencil_and_coefficients( local_stencil_, coefficients_ );
            }
          const int size = local_stencil_.dimension( 0 );
          for ( int k=0; k<size; ++k )
            {
              local_stencil_( k, 0 ) += imin;
              local_stencil_( k, 1 ) += jmin;
            }
          jmin = jmax;
        }
      imin = imax;
      jmin = jprev;
    }
  const int nb_lines = nb_lignes( );
  ArrOfInt offsets( nb_lines + 1 );
  offsets[ 0 ] = 0;
  for ( int i=0; i<nb_stencils; ++i )
    {
      const IntTab& local_stencil_ = local_stencils[ i ];
      const int size = local_stencil_.dimension( 0 );
      for ( int k=0; k<size; ++k )
        {
          const int line = local_stencil_( k, 0 );
          offsets[ line + 1 ] += 1;
        }
    }
  for ( int i=0; i<nb_lines; ++i )
    {
      offsets[ i + 1 ] += offsets[ i ];
    }
  const int stencil_size = offsets[ nb_lines ];
  stencil.resize( stencil_size, 2 );
  coefficients.resize_array( stencil_size );
  stencil = -1;
  for ( int i=0; i<nb_stencils; ++i )
    {
      const IntTab&      local_stencil_       = local_stencils[ i ];
      const ArrOfDouble&        coefficients_ = local_coefficients[ i ];
      const int size = local_stencil_.dimension( 0 );
      assert( coefficients_.size_array( ) == size );
      for ( int k=0; k<size; ++k )
        {
          const int line        = local_stencil_( k, 0 );
          const int column      = local_stencil_( k, 1 );
          const double coefficient = coefficients_[ k ];
          const int index       = offsets[ line ];
          assert( stencil( index, 0 ) < 0 );
          assert( stencil( index, 1 ) < 0 );
          assert( index < offsets[ line + 1 ] );
          stencil( index, 0 )   = line;
          stencil( index, 1 )   = column;
          coefficients[ index ] = coefficient;
          offsets[ line ] += 1;
        }
    }
}
References assert_check_symmetric_block_matrix_structure(), TRUSTTab< _TYPE_ >::dimension(), get_bloc(), Matrice_Base::get_stencil_and_coefficients(), Matrice_Base::get_symmetric_stencil_and_coefficients(), Matrice_Bloc::nb_bloc_colonnes(), Matrice_Bloc::nb_bloc_lignes(), Matrice_Bloc::nb_blocs_, Matrice_Base::nb_colonnes(), Matrice_Base::nb_lignes(), Matrice_Bloc::nb_lignes(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::size_array(), Deriv_Matrice_Base::valeur(), and VECT.
Referenced by get_stencil_and_coefficients().
imprimer()
Sortie & Matrice_Bloc_Sym::imprimer (Sortie & s) const override virtual
Reimplemented from Matrice_Bloc.
Definition at line 48 of file Matrice_Bloc_Sym.cpp.
{
  int i,j;
  for(i=0; i<N_; i++)
    for(j=i; j<M_; j++)
      (*this).get_bloc(i,j).valeur().imprimer(os);
  return os;
}
References Matrice_Bloc::M_, and Matrice_Bloc::N_.
imprimer_formatte()
Sortie & Matrice_Bloc_Sym::imprimer_formatte (Sortie & s) const override virtual
Reimplemented from Matrice_Bloc.
Definition at line 57 of file Matrice_Bloc_Sym.cpp.
{
  for(int i=0; i<N_; i++)
    {
      for(int j=i; j<M_; j++)
        {
          os<<"----------"<<finl;
          os<<"Bloc ("<<i<<","<<j<<"):"<<finl;
          os<<"----------"<<finl;
          (*this).get_bloc(i,j).valeur().imprimer_formatte(os);
        }
    }
  return os;
}
References finl, Matrice_Bloc::M_, and Matrice_Bloc::N_.
Referenced by BlocSymToMatMorseSym(), and verifier().
info()
const Type_info * Matrice_Bloc_Sym::info () static
Definition at line 23 of file Matrice_Bloc_Sym.cpp.
printOn()
Sortie & Matrice_Bloc_Sym::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Matrice_Bloc.
Definition at line 25 of file Matrice_Bloc_Sym.cpp.
{
  return Matrice_Bloc::printOn(os);
}
References Matrice_Bloc::printOn().
readOn()
Entree & Matrice_Bloc_Sym::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Matrice_Bloc.
Definition at line 30 of file Matrice_Bloc_Sym.cpp.
{
  return Matrice_Bloc::readOn(is);
}
References Matrice_Bloc::readOn().
self_cast() [1/2]
const Matrice_Bloc_Sym & Matrice_Bloc_Sym::self_cast (const Objet_U & r) static
Definition at line 23 of file Matrice_Bloc_Sym.cpp.
self_cast() [2/2]
Matrice_Bloc_Sym & Matrice_Bloc_Sym::self_cast (Objet_U & r) static
Definition at line 23 of file Matrice_Bloc_Sym.cpp.
taille_memoire()
unsigned Matrice_Bloc_Sym::taille_memoire () const override virtual
Reimplemented from Matrice_Bloc.
Definition at line 23 of file Matrice_Bloc_Sym.cpp.
Member Data Documentation
info_obj
const Type_info Matrice_Bloc_Sym::info_obj static
Definition at line 63 of file Matrice_Bloc_Sym.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/Matrices/Matrice_Bloc_Sym.h
src/Kernel/Math/Matrices/Matrice_Bloc_Sym.cpp