TRUST: Schema_Adams_Bashforth_base Class Reference
Schema_Adams_Bashforth_base Class Reference
classe Schema_Adams_Bashforth_base
#include <Schema_Adams_Bashforth_base.h>
Public Member Functions
Schema_Adams_Bashforth_base ()
~Schema_Adams_Bashforth_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &)
void modifier_second_membre (const Equation_base &eqn, DoubleTab &secmem)
void compute_coefficients (double time_step, const DoubleTab &times)
const DoubleTab & coefficients () const
DoubleTab & coefficients ()
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Schema_Adams_Bashforth_base & self_cast (Objet_U &)
static const
Schema_Adams_Bashforth_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
virtual void compute_adams_bashforth_coefficients (double time_step, const DoubleTab &times)=0
Private Attributes
DoubleTab adams_bashforth_coefficients_
Detailed Description
classe Schema_Adams_Bashforth_base
Definition at line 35 of file Schema_Adams_Bashforth_base.h.
Constructor & Destructor Documentation
Schema_Adams_Bashforth_base::Schema_Adams_Bashforth_base ()
Definition at line 29 of file Schema_Adams_Bashforth_base.cpp.
Schema_Adams_Bashforth_base::~Schema_Adams_Bashforth_base ()
Definition at line 29 of file Schema_Adams_Bashforth_base.cpp.
Member Function Documentation
void Schema_Adams_Bashforth_base::associer_pb (const Probleme_base & un_probleme) [virtual]
Reimplemented from Schema_Temps_base.
Definition at line 73 of file Schema_Adams_Bashforth_base.cpp.
References Probleme_base::equation(), Probleme_base::nombre_d_equations(), Schema_Temps_base::pb_base(), and Equation_base::set_calculate_time_derivative().
{
  Schema_Explicite_Multi_TimeStep_base::associer_pb(un_probleme);
// Loop on equations
  for (int i=0; i<pb_base().nombre_d_equations(); i++)
    pb_base().equation(i).set_calculate_time_derivative(1);
}
const DoubleTab & Schema_Adams_Bashforth_base::coefficients () const [inline, virtual]
Implements Schema_Explicite_Multi_TimeStep_base.
Definition at line 59 of file Schema_Adams_Bashforth_base.h.
References adams_bashforth_coefficients_.
Referenced by Schema_Adams_Bashforth_order_3::compute_adams_bashforth_coefficients(), Schema_Adams_Bashforth_order_2::compute_adams_bashforth_coefficients(), and modifier_second_membre().
{
  return adams_bashforth_coefficients_;
}
DoubleTab & Schema_Adams_Bashforth_base::coefficients () [inline, virtual]
Implements Schema_Explicite_Multi_TimeStep_base.
Definition at line 64 of file Schema_Adams_Bashforth_base.h.
References adams_bashforth_coefficients_.
{
  return adams_bashforth_coefficients_;
}
virtual void Schema_Adams_Bashforth_base::compute_adams_bashforth_coefficients (double time_step, const DoubleTab & times) [protected, pure virtual]
Implemented in Schema_Adams_Bashforth_order_2, and Schema_Adams_Bashforth_order_3.
Referenced by compute_coefficients().
void Schema_Adams_Bashforth_base::compute_coefficients (double time_step, const DoubleTab & times) [virtual]
Implements Schema_Explicite_Multi_TimeStep_base.
Definition at line 81 of file Schema_Adams_Bashforth_base.cpp.
References compute_adams_bashforth_coefficients().
Referenced by modifier_second_membre().
{
  compute_adams_bashforth_coefficients(time_step,times);
}
virtual int Schema_Adams_Bashforth_base::duplique () const [pure virtual]
Implements Schema_Explicite_Multi_TimeStep_base.
Implemented in Schema_Adams_Bashforth_order_2, and Schema_Adams_Bashforth_order_3.
const Type_info * Schema_Adams_Bashforth_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Explicite_Multi_TimeStep_base.
Reimplemented in Schema_Adams_Bashforth_order_2, and Schema_Adams_Bashforth_order_3.
Definition at line 29 of file Schema_Adams_Bashforth_base.cpp.
const Type_info * Schema_Adams_Bashforth_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Explicite_Multi_TimeStep_base.
Reimplemented in Schema_Adams_Bashforth_order_2, and Schema_Adams_Bashforth_order_3.
Definition at line 29 of file Schema_Adams_Bashforth_base.cpp.
void Schema_Adams_Bashforth_base::modifier_second_membre (const Equation_base & eqn, DoubleTab & secmem) [virtual]
Implements Schema_Explicite_Multi_TimeStep_base.
Definition at line 86 of file Schema_Adams_Bashforth_base.cpp.
References Solveur_Masse::ajouter_masse(), coefficients(), compute_coefficients(), Equation_base::derivee_en_temps(), Equation_base::inconnue(), Schema_Temps_base::nb_pas_dt(), Schema_Explicite_Multi_TimeStep_base::nb_pas_dt_seuil(), Schema_Explicite_Multi_TimeStep_base::nb_valeurs_passees(), Schema_Temps_base::nb_valeurs_temporelles(), Schema_Temps_base::pas_de_temps(), Champ_Inc::passe(), Champ_Inc_base::recuperer_temps_futur(), Champ_Inc_base::recuperer_temps_passe(), ref_cast, Equation_base::solv_masse(), Deriv_Champ_Inc_base::valeur(), and Champ_Inc::valeurs().
{
  if (nb_pas_dt()> nb_pas_dt_seuil())
    {
      const Equation_base& eqn_bis   = ref_cast(Equation_base,eqn);
      int            i         = 0;
      int            offset    = 0;
      double         time_step = pas_de_temps(); //tn+1-tn
      DoubleTab times(nb_valeurs_temporelles());
// Building of a time-in-ascending-order table
      assert(nb_valeurs_passees()+2 == nb_valeurs_temporelles());
      for (i=0; i<nb_valeurs_passees(); ++i)
        {
          offset   =  nb_valeurs_passees()-i;
          times[i] =  eqn_bis.inconnue().valeur().recuperer_temps_passe(offset); //past
        }
      times[nb_valeurs_passees()]   = eqn_bis.inconnue().valeur().recuperer_temps_futur(0); //present
      times[nb_valeurs_passees()+1] = eqn_bis.inconnue().valeur().recuperer_temps_futur(1); //future
      compute_coefficients(time_step,times);
// Modification due to present time and past times
      secmem*=coefficients()[nb_valeurs_passees()]; //present time
      DoubleTrav dudt(eqn.inconnue().valeurs());
      DoubleTrav tmp(dudt);
// Compute sum(coeff*dudt)
      for (i=0; i<nb_valeurs_passees(); ++i)
        {
          offset = nb_valeurs_passees()-i;
          tmp = eqn.derivee_en_temps().passe(offset);
          tmp *= coefficients()[i];
          dudt += tmp; //past time
        }
// secmem+=Mdu/dt
      eqn.solv_masse().ajouter_masse(1.,secmem,dudt,0);
    }
}
Sortie & Schema_Adams_Bashforth_base::printOn (Sortie & s) const [protected, virtual]
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Schema_Explicite_Multi_TimeStep_base.
Reimplemented in Schema_Adams_Bashforth_order_2, and Schema_Adams_Bashforth_order_3.
Definition at line 47 of file Schema_Adams_Bashforth_base.cpp.
{
  return Schema_Explicite_Multi_TimeStep_base::printOn(s);
}
Entree & Schema_Adams_Bashforth_base::readOn (Entree & s) [protected, virtual]
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Schema_Explicite_Multi_TimeStep_base.
Reimplemented in Schema_Adams_Bashforth_order_2, and Schema_Adams_Bashforth_order_3.
Definition at line 68 of file Schema_Adams_Bashforth_base.cpp.
{
  return Schema_Explicite_Multi_TimeStep_base::readOn(s) ;
}
const Schema_Adams_Bashforth_base & Schema_Adams_Bashforth_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Schema_Explicite_Multi_TimeStep_base.
Reimplemented in Schema_Adams_Bashforth_order_2, and Schema_Adams_Bashforth_order_3.
Definition at line 29 of file Schema_Adams_Bashforth_base.cpp.
Schema_Adams_Bashforth_base & Schema_Adams_Bashforth_base::self_cast (Objet_U & r) [static]
Reimplemented from Schema_Explicite_Multi_TimeStep_base.
Reimplemented in Schema_Adams_Bashforth_order_2, and Schema_Adams_Bashforth_order_3.
Definition at line 29 of file Schema_Adams_Bashforth_base.cpp.
Member Data Documentation
DoubleTab Schema_Adams_Bashforth_base::adams_bashforth_coefficients_ [private]
Definition at line 56 of file Schema_Adams_Bashforth_base.h.
Referenced by coefficients().
const Type_info Schema_Adams_Bashforth_base::info_obj [static]
Reimplemented from Schema_Explicite_Multi_TimeStep_base.
Reimplemented in Schema_Adams_Bashforth_order_2, and Schema_Adams_Bashforth_order_3.
Definition at line 38 of file Schema_Adams_Bashforth_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Schemas_Temps/Schema_Adams_Bashforth_base.h
src/Kernel/Schemas_Temps/Schema_Adams_Bashforth_base.cpp