TRUST: Reaction Class Reference
Reaction Class Reference
#include <Reaction.h>
Public Member Functions
Reaction ()
~Reaction ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void completer (const Motcles &list_var, const ArrOfDouble &masse_molaire)
void reagir (Vect_Ref_Champ_Inc_base &liste_c, const double deltat) const
double calcul_proportion_implicite (ArrOfDouble &C_temp, const ArrOfDouble &C0, double deltat, double seuil, double &poroportion_directe) const
void extract_coef (ArrOfDouble &coeff_recactifs, ArrOfDouble &coeff_produits, const Motcles &list_var, const ArrOfDouble &masse_molaire) const
double calculer_pas_de_temps () const
int lire_motcle_non_standard (const Motcle &motlu, Entree &is) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
const Champ_base & get_omega () const
void discretiser_omega (const Probleme_base &pb, const Nom &)
const int & nb_sous_pas_de_temps_reaction () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Reaction & self_cast (Objet_U &)
static const Reaction & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom reactifs_
Nom produits_
Nom activite_
double constante_taux_reaction_
double enthalpie_reaction_
en J/mol
double contre_reaction_
prefacteur
double Sc_t_
Nombre de Schmidt turbulent (e.g. 0.8)
double Ea_
en J/mol
double beta_
ArrOfDouble coeff_Y_
ArrOfDouble coeff_stoechio_
ArrOfDouble coeff_activite_
Motcles save_alias_
Champ_Fonc omega_
double proportion_max_sur_delta_t_
double proportion_max_admissible_
int nb_sous_pas_de_temps_reaction_
Friends
class Chimie
Detailed Description
Definition at line 29 of file Reaction.h.
Constructor & Destructor Documentation
Reaction()
Reaction::Reaction ()
Definition at line 23 of file Reaction.cpp.
~Reaction()
Reaction::~Reaction ()
Definition at line 23 of file Reaction.cpp.
Member Function Documentation
calcul_proportion_implicite()
double Reaction::calcul_proportion_implicite (ArrOfDouble & C_temp, const ArrOfDouble & C0, double deltat, double seuil, double & poroportion_directe) const
< 1/s // prefacteur du taux de reaction volumique local omegapoint*=pow(T_elem,beta_)*exp(-Ea_/(R_gaz_parfait*T_elem)); // Arrhenius et facteur temperature
< m3/kg/s // prefacteur du taux de reaction volumique local proportion=dy_omega*deltat; // m3/kg a ce stade si une seule activite exposant 1
< c'est un reactif gazeux => produit par son activite
< contre-Arrhenius
< c'est un reactif
< c'est un reactif car on est dans le cas contre treaction
< c'est un reactif car on est dans le cas contre treaction
Definition at line 298 of file Reaction.cpp.
{
  int nbc=C0.size_array();
// double proportion_directe_es;
  double proportion=-1, omegapoint, dy_omega, proportion_inverse=-1;
  double rho_mel=1 ; //tab_rho(elem);                //!< kg/m3
  double T_elem=1 ; //temperature(elem);             //!< K
  omegapoint=constante_taux_reaction_;  //!< 1/s     // prefacteur du taux de reaction volumique local omegapoint*=pow(T_elem,beta_)*exp(-Ea_/(R_gaz_parfait*T_elem)); // Arrhenius et facteur temperature
//
  dy_omega=omegapoint/rho_mel;          //!< m3/kg/s // prefacteur du taux de reaction volumique local proportion=dy_omega*deltat;           // m3/kg a ce stade si une seule activite exposant 1
//
  double produit_activite=1;
  double produit_contre=1;
  double R_gaz_parfait=8.3143;
  double securite=1-1e-6;
  if (contre_reaction_>0)
    securite=0.5;
  ArrOfDouble& C=C_temp;
  C=C0;
  int ite=0;
  double dmax=2*seuil;
  while((dmax>seuil)&&(ite<1000))
// while(ite<5)
    {
      dmax=0;
      produit_activite=1;
      produit_contre=1;
      proportion=dy_omega*deltat;
// calcul du taux de reaction brut
      for (int i=0; i<nbc; i++)
        {
          if (coeff_Y_[i]>0.) //!< c'est un reactif gazeux => produit par son activite
            {
              produit_activite*=pow(C[i],coeff_activite_[i]);
            }
          else if (contre_reaction_>0)
            if (coeff_Y_[i]<0.)
              {
                produit_contre*=pow(C[i],coeff_activite_[i]);
              }
        } //!< mol/kg a ce stade
      assert(produit_contre>=0);
      proportion_directe=produit_activite*proportion;
      if (contre_reaction_>0)
        {
          proportion_inverse=produit_contre/(contre_reaction_*exp(-c_r_Ea_/(R_gaz_parfait*T_elem)))*proportion;  //!< contre-Arrhenius
          proportion=proportion_directe-proportion_inverse;
        }
      else
        proportion=proportion_directe;
// proportion*=produit_activite;
      if (1)
        {
// conditionnement en temps pour ne pas consommer plus que ce qui est present
          if (proportion>0)
            for (int i=0; i<nbc; i++)
              {
                if (coeff_Y_[i]>0.) //!< c'est un reactif
                  {
                    if (proportion > C[i]/coeff_stoechio_[i]*securite) Cerr<<" on limite" <<finl;
                    proportion=std::min(proportion,C[i]/coeff_stoechio_[i]*securite);
                  }
              }
          else
            for (int i=0; i<nbc; i++)
              {
                if (coeff_Y_[i]<0.) //!< c'est un reactif car on est dans le cas contre treaction
                  {
// on prend le max car proportion et Y_i(elem)/coeff_Y_[i] sont negatifs
                    proportion=std::max(proportion,C[i]/coeff_stoechio_[i]*securite);
                  }
              }
        }
      proportion_max_sur_delta_t_=std::max(proportion_max_sur_delta_t_,std::fabs(proportion));
// if (ite==0)
// proportion_directe_es=proportion_directe;
      for (int i=0; i<nbc; i++)
        if (1)
          {
            if (coeff_Y_[i]!=0.) //!< c'est un reactif car on est dans le cas contre treaction
              {
                double pond=-1;
                if (coeff_Y_[i]>0)
                  {
                    if (C[i]>0)
                      pond=proportion_directe*coeff_stoechio_[i]/C[i];
                    else
                      pond=0;
                  }
                else
                  {
                    if ((contre_reaction_>0)&&(C[i]>0))
                      pond=-proportion_inverse*coeff_stoechio_[i]/C[i];
                    else
                      pond=0;
                  }
                if (pond<0)
                  exit();
// pond=0;
                double nc=((C0[i]-proportion*coeff_stoechio_[i]/2.+pond/2.*C[i])/(1.+pond/2.)-C[i]);
                double dc=std::fabs(nc);
                C[i]+=nc;
                if (dc>dmax)
                  dmax=dc;
// Cerr<<ite<<" i "<< i<< " "<<C(i)-C0(i)<<" dc"<< dmax <<finl;
              }
          }
        else
          {
            double nc=C0[i]-proportion*coeff_stoechio_[i]/2.-C[i];
            C[i]+=nc;
            double dc=std::fabs(nc);
            if (dc>dmax)
              dmax=dc;
          }
      ite++;
// Cerr<<ite<< " ici " <<proportion <<" "<<dmax<<" direct " <<proportion_directe<<finl;
// dmax=0;
    }
// Cerr<<"convergence en  "<<ite <<" "<<dmax<<" "<<proportion_directe<<finl;
  return proportion;
}
References Cerr, coeff_activite_, coeff_stoechio_, coeff_Y_, constante_taux_reaction_, contre_reaction_, Process::exit(), finl, proportion_max_sur_delta_t_, and TRUSTArray< _TYPE_ >::size_array().
Referenced by Chimie::mettre_a_jour(), and reagir().
calculer_pas_de_temps()
double Reaction::calculer_pas_de_temps () const
Definition at line 230 of file Reaction.cpp.
{
  return proportion_max_admissible_/(proportion_max_sur_delta_t_+DMINFLOAT);
}
References DMINFLOAT, proportion_max_admissible_, and proportion_max_sur_delta_t_.
completer()
void Reaction::completer (const Motcles & list_var, const ArrOfDouble & masse_molaire)
Definition at line 90 of file Reaction.cpp.
{
// test
  ArrOfDouble coeff_reactifs;
  ArrOfDouble coeff_produits;
  extract_coef(coeff_reactifs,coeff_produits,list_var,masse_molaire);
  int sz=list_var.size();
  double mreactif=0,mproduit=0;
  coeff_Y_.resize_array(sz);
  coeff_Y_=0;
  coeff_stoechio_.resize_array(sz);
  coeff_stoechio_=0;
  coeff_activite_.resize_array(sz);
  coeff_activite_=0;
  for (int p=0; p<sz; p++)
    {
      mreactif+=masse_molaire[p]*coeff_reactifs[p];
      mproduit+=masse_molaire[p]*coeff_produits[p];
      coeff_Y_[p]+=masse_molaire[p]*coeff_reactifs[p];
      coeff_Y_[p]-=masse_molaire[p]*coeff_produits[p];
      coeff_stoechio_[p]+=coeff_reactifs[p];
      coeff_stoechio_[p]-=coeff_produits[p];
    }
  if (!est_egal(mreactif,mproduit))
    {
      Cerr<<" erreur dans la chimie de "<<(*this)<<finl;
      Cerr<<" mreactif "<< mreactif<<finl;
      Cerr<<" mproduit "<< mproduit<<finl;
      exit();
    }
// coeff_Y_/=mreactif;
  save_alias_=list_var;
  Cerr<<" Extraction des activites "<<finl;
  extract_coef_local(coeff_activite_,activite_,list_var);
}
References activite_, Cerr, coeff_activite_, coeff_stoechio_, coeff_Y_, est_egal(), Process::exit(), extract_coef(), extract_coef_local(), finl, TRUSTArray< _TYPE_ >::resize_array(), save_alias_, and vect_impl::size().
cree_instance()
Objet_U * Reaction::cree_instance () static
Definition at line 23 of file Reaction.cpp.
discretiser_omega()
void Reaction::discretiser_omega (const Probleme_base & pb, const Nom & nom)
Definition at line 235 of file Reaction.cpp.
{
  const Equation_base& eqn=pb.equation(0);
  eqn.discretisation().discretiser_champ("temperature",eqn.zone_dis().valeur(),nom,"unit", -1,0.,omega_);
}
References Equation_base::discretisation(), Discretisation_base::discretiser_champ(), Probleme_base::equation(), omega_, Deriv_Zone_dis_base::valeur(), and Equation_base::zone_dis().
duplique()
int Reaction::duplique () const override virtual
Implements Objet_U.
Definition at line 23 of file Reaction.cpp.
extract_coef()
void Reaction::extract_coef (ArrOfDouble & coeff_recactifs, ArrOfDouble & coeff_produits, const Motcles & list_var, const ArrOfDouble & masse_molaire) const
Definition at line 83 of file Reaction.cpp.
{
  assert(masse_molaire.size_array()==list_var.size());
  extract_coef_local(coeff_reactifs,reactifs_, list_var);
  extract_coef_local(coeff_produits,produits_, list_var);
}
References extract_coef_local(), produits_, reactifs_, vect_impl::size(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by completer().
get_info()
const Type_info * Reaction::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 23 of file Reaction.cpp.
get_omega()
const Champ_base & Reaction::get_omega () const inline
Definition at line 41 of file Reaction.h.
  {
    return omega_.valeur();
  };
References omega_, and Deriv_Champ_Fonc_base::valeur().
info()
const Type_info * Reaction::info () static
Definition at line 23 of file Reaction.cpp.
lire_motcle_non_standard()
int Reaction::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Objet_U.
Definition at line 200 of file Reaction.cpp.
{
  if (motlu=="coefficients_activites")
    {
      Nom motlubis;
      is >> motlubis;
      if (motlubis!="{")
        {
          Cerr<<"On attendait { et non " <<motlubis<<" dans lire_motcle_non_standard de "<<que_suis_je()<<finl;
          exit();
        }
      is>>motlubis;
      while (motlubis!="}")
        {
// on lit deux mots et on fait +mot1*mot2
          activite_+="+";
          activite_+=motlubis;
          activite_+="*";
          is>>motlubis;
          activite_+=motlubis;
          is>>motlubis;
        }
    }
  else
    {
      Cerr<<"On attendait coefficients_activites et non " <<motlu<<" dans lire_motcle_non_standard de "<<que_suis_je()<<finl;
      exit();
    }
  return 1;
}
References activite_, Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
nb_sous_pas_de_temps_reaction()
const int & Reaction::nb_sous_pas_de_temps_reaction () const inline
Definition at line 46 of file Reaction.h.
  {
    return nb_sous_pas_de_temps_reaction_ ;
  };
References nb_sous_pas_de_temps_reaction_.
Referenced by Chimie::mettre_a_jour().
printOn()
Sortie & Reaction::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 26 of file Reaction.cpp.
{
  os<<" { "<<finl;
  os<<"reactifs "<<reactifs_<<finl;
  os<<"produits "<<produits_<<finl;
  os<<"exposant_beta "<<beta_<<finl;
  os<<"constante_taux_reaction "<<constante_taux_reaction_<<finl;
  /*  os<<"c0_D_G "<<c0_D_G_<<" Pa.m2/s"<<finl;
      os<<"c1_D_G "<<c1_D_G_<<" Pa.m2/s/K"<<finl;
      os<<"c2_D_G "<<c2_D_G_<<" Pa.m2/s/K2"<<finl;
      os<<"d_D_G  "<<d_D_G_<<" Pa.m2/s/K^(3/2)"<<finl;
      os<<"c_Re05Sc033 "<<c_Re05Sc033_<<finl; */
  os<<"Sc_t "<<Sc_t_<<finl;
  /*  os<<"d_min "<<d_min_<<finl;
      os<<"d_max "<<d_max_<<finl; */
  os<<"enthalpie_reaction "<<enthalpie_reaction_<<" J/mol"<<finl;
  os<<"energie_activation "<<Ea_<<" J/mol"<<finl;
  os<<"proportion_max_admissible "<<proportion_max_admissible_<<finl;
  os<<"nb_sous_pas_de_temps_reaction "<<nb_sous_pas_de_temps_reaction_<<finl;
  os<<"contre_reaction "<<contre_reaction_<<finl;
  os<<"contre_energie_activation "<<c_r_Ea_<<finl;
  /*
    os<<"nb_iter_impl_contre_reaction "<<nb_iter_impl_contre_reaction_<<finl;
    os<<"sous_relax__impl_contre_reaction "<<sous_relax__impl_contre_reaction_<<finl; */
  os<<" } "<<finl;
  return os;
}
References beta_, constante_taux_reaction_, contre_reaction_, Ea_, enthalpie_reaction_, finl, nb_sous_pas_de_temps_reaction_, produits_, proportion_max_admissible_, reactifs_, and Sc_t_.
readOn()
Entree & Reaction::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
< J/mol
< mol/kg
Reimplemented from Objet_U.
Definition at line 127 of file Reaction.cpp.
{
  Ea_=0;                            //!< J/mol
  beta_=0;
  c_r_Ea_=0;
  /*  c0_D_G_ =0.;                      // Pa.m2/s
      c1_D_G_ =0.;                      // Pa.m2/s/K
      c2_D_G_ =0.;                      // Pa.m2/s/K2
      d_D_G_=1e30;                      // Pa.m2/s/K^(3/2)
      c_Re05Sc033_=0.3;                 // constante de la loi de type Ranz-Marschall pour D_G (e.g. 0.3)
  constante_taux_reaction_=1e30;    //!< 1/s en gaz, m/s en grains (et suivant nombre de produits d'activite !)
  */
  /*  d_min_=1e-10;
  Sc_t_=0.8;                        //!< Nombre de Schmidt turbulent dans le calcul de D_G
      d_max_=1.; */
  proportion_max_admissible_=1e30;
  proportion_max_sur_delta_t_=1;    //!< mol/kg
  activite_="0";
  nb_sous_pas_de_temps_reaction_ =1;
  contre_reaction_=-1;
// nb_iter_impl_contre_reaction_=1;      // pas d'iteration
// sous_relax__impl_contre_reaction_=1.; // pas de sous-relaxation
  Param param(que_suis_je());
  param.ajouter( "reactifs",&reactifs_,Param::REQUIRED);
  param.ajouter( "produits",&produits_,Param::REQUIRED);
  param.ajouter( "constante_taux_reaction",&constante_taux_reaction_);
  param.ajouter( "enthalpie_reaction",&enthalpie_reaction_,Param::REQUIRED);
  param.ajouter( "energie_activation",&Ea_);
  param.ajouter( "exposant_beta",&beta_);
  param.ajouter_non_std("coefficients_activites",(this));
  param.ajouter( "contre_reaction",&contre_reaction_);
  param.ajouter( "contre_energie_activation",&c_r_Ea_);
  /* param.ajouter( "c0_D_G", &c0_D_G_);
     param.ajouter( "c1_D_G", &c1_D_G_);
     param.ajouter( "c2_D_G", &c2_D_G_);
     param.ajouter( "d_D_G",&d_D_G_);
     param.ajouter( "c_Re05Sc033 ",&c_Re05Sc033_);
     param.ajouter( "d_min",&d_min_);
     param.ajouter( "d_max",&d_max_);
     param.ajouter( "proportion_max_admissible",&proportion_max_admissible_);
     param.ajouter( "nb_sous_pas_de_temps_reaction",&nb_sous_pas_de_temps_reaction_);
     param.ajouter( "nb_iter_impl_contre_reaction",&nb_iter_impl_contre_reaction_);
     param.ajouter( "sous_relax__impl_contre_reaction",&sous_relax__impl_contre_reaction_);
  */
  param.ajouter( "Sc_t",&Sc_t_);
  param.lire_avec_accolades_depuis(is);
  /*
    if (((c0_D_G_+c1_D_G_*1.E3+c2_D_G_*1.E6+d_D_G_*3.E4)>1.e29)&&(constante_taux_reaction_>1.e29))
    { // NB : D_G=1/p*(c0+c1*T+c2*T^2+c32*T^(3/2))
    Cerr<<" L'une des deux valeurs D_G(T) ou constante_taux_reaction doit etre << 1E30 !"<<finl;
    Cerr<<"   c0_D_G & d_D_G : "<<c0_D_G_<<" & "<<d_D_G_ <<finl;
    Cerr<<"   constante_taux_reaction : "<< constante_taux_reaction_ <<finl;
    exit();
    }
  */
  if (Sc_t_==0.)
    {
      Cerr<<" Une valeur nulle du Schmidt turbulent est impossible ! Essayer plutot 1E30 !"<<finl;
      exit();
    }
  return is;
}
References activite_, Param::ajouter(), Param::ajouter_non_std(), beta_, Cerr, constante_taux_reaction_, contre_reaction_, Ea_, enthalpie_reaction_, Process::exit(), finl, Param::lire_avec_accolades_depuis(), nb_sous_pas_de_temps_reaction_, produits_, proportion_max_admissible_, proportion_max_sur_delta_t_, Objet_U::que_suis_je(), reactifs_, Param::REQUIRED, and Sc_t_.
reagir()
void Reaction::reagir (Vect_Ref_Champ_Inc_base & liste_c, const double deltat) const
< c'est un reactif ou un produit
< c'est un reactif ou un produit
< kg/kg C_i(elem)-=proportion*coeff_stoechio_[i];
Definition at line 240 of file Reaction.cpp.
{
// il faut savoir e que l'on veut faire ....
// Cerr<<__FILE__<<" "<<(int)__LINE__<<" non  code "<<finl;  exit();
  int size=liste_C.size();
  ArrOfDouble C(size),C0(size);
  int nb_case= liste_C[0].valeur().valeurs().size();
  if ((beta_!=0)||(Ea_!=0)||((c_r_Ea_!=0)&&(contre_reaction_>0)))
    {
      Cerr<<"Reaction :  Donnees incompatibles avec le fait que l on n a pas de temperature"<<finl;
      Cerr<<*this<<finl;
      exit();
    }
  for (int elem=0; elem<nb_case; elem++)
    {
// initialisation et rabotage des C
      for (int i=0; i<size; i++)
        {
          if (coeff_Y_[i]!=0.) //!< c'est un reactif ou un produit
            {
              C[i]=liste_C[i].valeur().valeurs()(elem);
              if (C[i]<0)
                {
                  if (C[i]<-1e-5)
                    {
                      Cerr<<" on rabote C_"<<i<<" dans la maille "<<elem<<" dans la chimie !!!!!! "<<C[i]<<finl;
                      exit();
                    }
                  C[i]=0;
                }
            }
          else
            C[i]=0;
        }
// calcul du taux de reaction implicite
      C0=C;
      double proportion_directe;
      double proportion=calcul_proportion_implicite(C,C0,deltat,1e-7,proportion_directe);
      for (int i=0; i<size; i++)
        if (coeff_Y_[i]!=0.) //!< c'est un reactif ou un produit
          {
            DoubleTab& C_i = liste_C[i].valeur().valeurs(); //!< kg/kg    C_i(elem)-=proportion*coeff_stoechio_[i];
//
            C_i(elem)=C0[i]-proportion*coeff_stoechio_[i];
          }
    }
}
References beta_, calcul_proportion_implicite(), Cerr, coeff_stoechio_, coeff_Y_, contre_reaction_, Ea_, Process::exit(), finl, TRUSTVect< _TYPE_ >::size(), and Champ_Inc_base::valeurs().
Referenced by Chimie::mettre_a_jour().
self_cast() [1/2]
const Reaction & Reaction::self_cast (const Objet_U & r) static
Definition at line 23 of file Reaction.cpp.
self_cast() [2/2]
Reaction & Reaction::self_cast (Objet_U & r) static
Definition at line 23 of file Reaction.cpp.
taille_memoire()
unsigned Reaction::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 23 of file Reaction.cpp.
Friends And Related Function Documentation
Chimie
friend class Chimie friend
Definition at line 33 of file Reaction.h.
Member Data Documentation
activite_
Nom Reaction::activite_ protected
Definition at line 51 of file Reaction.h.
Referenced by completer(), lire_motcle_non_standard(), and readOn().
beta_
double Reaction::beta_ protected
Definition at line 67 of file Reaction.h.
Referenced by Chimie::mettre_a_jour(), printOn(), readOn(), and reagir().
coeff_activite_
ArrOfDouble Reaction::coeff_activite_ protected
Definition at line 69 of file Reaction.h.
Referenced by calcul_proportion_implicite(), completer(), and Chimie::mettre_a_jour().
coeff_stoechio_
ArrOfDouble Reaction::coeff_stoechio_ protected
Definition at line 68 of file Reaction.h.
Referenced by calcul_proportion_implicite(), completer(), Chimie::mettre_a_jour(), and reagir().
coeff_Y_
ArrOfDouble Reaction::coeff_Y_ protected
Definition at line 68 of file Reaction.h.
Referenced by calcul_proportion_implicite(), completer(), Chimie::mettre_a_jour(), and reagir().
constante_taux_reaction_
double Reaction::constante_taux_reaction_ protected
Definition at line 53 of file Reaction.h.
Referenced by calcul_proportion_implicite(), Chimie::mettre_a_jour(), printOn(), and readOn().
contre_reaction_
double Reaction::contre_reaction_ protected
prefacteur
Definition at line 55 of file Reaction.h.
Referenced by calcul_proportion_implicite(), Chimie::mettre_a_jour(), printOn(), readOn(), and reagir().
Ea_
double Reaction::Ea_ protected
en J/mol
Definition at line 66 of file Reaction.h.
Referenced by Chimie::mettre_a_jour(), printOn(), readOn(), and reagir().
enthalpie_reaction_
double Reaction::enthalpie_reaction_ protected
en J/mol
Definition at line 54 of file Reaction.h.
Referenced by printOn(), and readOn().
info_obj
const Type_info Reaction::info_obj static
Definition at line 31 of file Reaction.h.
nb_sous_pas_de_temps_reaction_
int Reaction::nb_sous_pas_de_temps_reaction_ protected
Definition at line 75 of file Reaction.h.
Referenced by nb_sous_pas_de_temps_reaction(), printOn(), and readOn().
omega_
Champ_Fonc Reaction::omega_ mutable protected
Definition at line 71 of file Reaction.h.
Referenced by discretiser_omega(), and get_omega().
produits_
Nom Reaction::produits_ protected
Definition at line 51 of file Reaction.h.
Referenced by extract_coef(), printOn(), and readOn().
proportion_max_admissible_
double Reaction::proportion_max_admissible_ protected
Definition at line 74 of file Reaction.h.
Referenced by calculer_pas_de_temps(), printOn(), and readOn().
proportion_max_sur_delta_t_
double Reaction::proportion_max_sur_delta_t_ mutable protected
Definition at line 73 of file Reaction.h.
Referenced by calcul_proportion_implicite(), calculer_pas_de_temps(), and readOn().
reactifs_
Nom Reaction::reactifs_ protected
Definition at line 51 of file Reaction.h.
Referenced by extract_coef(), printOn(), and readOn().
save_alias_
Motcles Reaction::save_alias_ protected
Definition at line 70 of file Reaction.h.
Referenced by completer().
Sc_t_
double Reaction::Sc_t_ protected
Nombre de Schmidt turbulent (e.g. 0.8)
Definition at line 65 of file Reaction.h.
Referenced by printOn(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Chimie/Reaction.h
src/ThHyd/Chimie/Reaction.cpp