TRUST: Echange_contact_VDF Class Reference
Echange_contact_VDF Class Reference
#include <Echange_contact_VDF.h>
Public Member Functions
Echange_contact_VDF ()
~Echange_contact_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void completer () override
NE FAIT RIEN
A surcharger dans les classes derivees.
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
void mettre_a_jour (double) override
Effectue une mise a jour en temps de la condition aux limites.
void calculer_h_autre_pb (DoubleTab &tab, double invhparoi, int opt)
void calculer_h_mon_pb (DoubleTab &, double, int)
virtual Champ_front & T_autre_pb ()
virtual const Champ_front & T_autre_pb () const
virtual void calculer_Teta_paroi (DoubleTab &tab_p, const DoubleTab &mon_h, const DoubleTab &autre_h, int is_pb_fluide, double temps)
remplit Teta_p
utilise T_autre_pb au temps passe en parametre
virtual void calculer_Teta_equiv (DoubleTab &Teta_equiv, const DoubleTab &mon_h, const DoubleTab &autre_h, int is_pb_fluide, double temps)
remplit Teta_eq
utilise T_autre_pb au temps passe en parametre
int verifier_correspondance () const
const DoubleTab & T_wall () const
const DoubleTab & h_autre_pb () const
const IntTab & get_remote_elems () const
const Nom & nom_autre_pb () const
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
Public Member Functions inherited from Echange_global_impose
Echange_global_impose ()
~Echange_global_impose ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int compatible_avec_discr (const Discretisation_base &discr) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
void completer () override
NE FAIT RIEN
A surcharger dans les classes derivees.
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps de la condition aux limites.
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Champ_front & derivee_phi_ext ()
const Champ_front & derivee_phi_ext () const
Champ_front & phi_ext ()
const Champ_front & phi_ext () const
virtual double champ_exterieur (int i, int j, const Champ_front &champ_ext) const
virtual double champ_exterieur (int i, const Champ_front &champ_ext) const
virtual double flux_exterieur_impose (int i) const
virtual double flux_exterieur_impose (int i, int j) const
virtual double derivee_flux_exterieur_imposee (int i) const
virtual double derivee_flux_exterieur_imposee (int i, int j) const
const bool & has_phi_ext () const
Public Member Functions inherited from Echange_impose_base
~Echange_impose_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double h_imp (int num) const
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
virtual double h_imp (int num, int k) const
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
virtual double T_ext (int num) const
Renvoie la valeur de la temperature imposee
sur la i-eme composante du champ de frontiere.
virtual double T_ext (int num, int k) const
Renvoie la valeur de la temperature imposee
sur la (i,j)-eme composante du champ de frontiere.
void mettre_a_jour (double) override
Effectue une mise a jour en temps
des conditions aux limites.
Lors du premier appel des initialisations sont effectuees:
h_imp(0,0) = (rho(0,0)*Cp(0,0))
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
int a_mettre_a_jour_ss_pas_dt () override
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
void associer_fr_dis_base (const Frontiere_dis_base &) override
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
virtual Champ_front & T_ext ()
Renvoie le champ T_ext de temperature imposee a la frontiere.
virtual const Champ_front & T_ext () const
Renvoie le champ T_ext de temperature imposee a la frontiere.
(version const)
virtual Champ_front & h_imp ()
Constructeur par defaut de la classe Echange_impose_base.
Ne construit rien, initialise le champ init a 0.
virtual const Champ_front & h_imp () const
int compatible_avec_eqn (const Equation_base &) const override
Verifie la compatibilite des conditions aux limites avec
l'equation passee en parametre.
Les conditions aux limites de type Ech_imp_base sont
compatibles avec des equations de type:
- Thermique
- indetermine.
int compatible_avec_discr (const Discretisation_base &) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void liste_faces_loi_paroi (IntTab &)
Public Member Functions inherited from Cond_lim_base
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Echange_contact_VDF & self_cast (Objet_U &)
static const Echange_contact_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Echange_global_impose
static Objet_U * cree_instance ()
static const Type_info * info ()
static Echange_global_impose & self_cast (Objet_U &)
static const Echange_global_impose & self_cast (const Objet_U &)
Static Public Member Functions inherited from Echange_impose_base
static const Type_info * info ()
static Echange_impose_base & self_cast (Objet_U &)
static const Echange_impose_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Cond_lim_base
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
IntTab item
int monolithic
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Echange_global_impose
static const Type_info info_obj
Static Public Attributes inherited from Echange_impose_base
static const Type_info info_obj
Static Public Attributes inherited from Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une condition aux limite de type Echange_impose_base
a partir d'un flot d'entree.
On doit lire le coefficient d'echange global H_imp et la temperature
a la frontiere T_ext.
Format:
"h_imp" type_champ_front bloc de lecture champ
"T_ext" type_champ_front bloc de lecture champ.
Protected Member Functions inherited from Cond_lim_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double h_paroi
DoubleTab autre_h
Champ_front T_autre_pb_
DoubleTab T_wall_
Nom nom_autre_pb_
IntTab remote_elems_
Protected Attributes inherited from Echange_global_impose
bool phi_ext_lu_
Champ_front derivee_phi_ext_
Champ_front phi_ext_
Protected Attributes inherited from Echange_impose_base
Champ_front h_imp_
Protected Attributes inherited from Cond_lim_base
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Detailed Description
Definition at line 34 of file Echange_contact_VDF.h.
Constructor & Destructor Documentation
Echange_contact_VDF()
Echange_contact_VDF::Echange_contact_VDF ()
Definition at line 30 of file Echange_contact_VDF.cpp.
~Echange_contact_VDF()
Echange_contact_VDF::~Echange_contact_VDF ()
Definition at line 30 of file Echange_contact_VDF.cpp.
Member Function Documentation
avancer()
int Echange_contact_VDF::avancer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Echange_global_impose.
Definition at line 73 of file Echange_contact_VDF.cpp.
{
  int ok=Cond_lim_base::avancer(temps);
  ok = ok && T_autre_pb()->avancer(temps);
  return ok;
}
References Cond_lim_base::avancer(), and T_autre_pb().
calculer_h_autre_pb()
void Echange_contact_VDF::calculer_h_autre_pb (DoubleTab & tab, double invhparoi, int opt)
< Raccord_local_homogene
Definition at line 230 of file Echange_contact_VDF.cpp.
{
  Champ_front_calc& ch=ref_cast(Champ_front_calc, T_autre_pb().valeur());
  const Milieu_base& le_milieu=ch.milieu();
  const Zone_VDF& zvdf_2=ref_cast(Zone_VDF, ch.zone_dis());
  const Front_VF& front_vf=ref_cast(Front_VF, ch.front_dis());
  const Equation_base& une_eqn=ch.equation();
  int nb_comp = le_milieu.conductivite()->nb_comp();
  assert(nb_comp==1);
  Zone_dis_base& zone_dis1 = zone_Cl_dis().zone_dis().valeur();
  Nom nom_racc1=frontiere_dis().frontiere().le_nom();
  Nom nom_racc2=ch.nom_bord_oppose();
  int nb_faces_raccord1 = zone_dis1.zone().raccord(nom_racc1).valeur().nb_faces();
  if (tab.dimension(0)!=nb_faces_raccord1
      ||tab.dimension(1)!=nb_comp)
    {
      Cerr << "Dans Echange_contact_VDF::calculer_h_autre_pb, tab n'est plus dimensionne." << finl;
      Cerr << "Le dimensionnement est fait dans Echange_contact_VDF::initialiser." << finl;
      exit();
    }
  if (zone_dis1.zone().raccord(nom_racc1).valeur().que_suis_je() =="Raccord_distant_homogene")
    {
      calculer_h_distant(tab,une_eqn,zvdf_2,front_vf,le_milieu,invhparoi,opt,nom_racc2);
    }
  else //!< Raccord_local_homogene
    {
      calculer_h_local(tab,une_eqn,zvdf_2,front_vf,le_milieu,invhparoi,opt);
    }
}
References calculer_h_distant(), calculer_h_local(), Cerr, Milieu_base::conductivite(), TRUSTTab< _TYPE_ >::dimension(), Champ_front_calc::equation(), Process::exit(), finl, Champ_front_calc::front_dis(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Frontiere::le_nom(), Champ_front_calc::milieu(), Champ_Don::nb_comp(), Frontiere::nb_faces(), Champ_front_calc::nom_bord_oppose(), Objet_U::que_suis_je(), Zone::raccord(), ref_cast, T_autre_pb(), Deriv_Zone_dis_base::valeur(), Deriv_Raccord_base::valeur(), valeur(), Zone_dis_base::zone(), Cond_lim_base::zone_Cl_dis(), Zone_Cl_dis_base::zone_dis(), and Champ_front_calc::zone_dis().
Referenced by mettre_a_jour().
calculer_h_mon_pb()
void Echange_contact_VDF::calculer_h_mon_pb (DoubleTab & tab, double invhparoi, int opt)
Definition at line 220 of file Echange_contact_VDF.cpp.
{
// forcement local
  const Equation_base& mon_eqn = zone_Cl_dis().equation();
  const Milieu_base& mon_milieu = mon_eqn.milieu();
  const Zone_VDF& ma_zvdf = ref_cast(Zone_VDF,zone_Cl_dis().zone_dis().valeur());
  const Front_VF& ma_front_vf = ref_cast(Front_VF,frontiere_dis());
  calculer_h_local(tab,mon_eqn,ma_zvdf,ma_front_vf,mon_milieu,invhparoi,opt);
}
References calculer_h_local(), MorEqn::equation(), Cond_lim_base::frontiere_dis(), Equation_base::milieu(), ref_cast, valeur(), and Cond_lim_base::zone_Cl_dis().
Referenced by mettre_a_jour().
calculer_Teta_equiv()
void Echange_contact_VDF::calculer_Teta_equiv (DoubleTab & Teta_equiv, const DoubleTab & mon_h, const DoubleTab & autre_h, int is_pb_fluide, double temps) virtual
remplit Teta_eq
utilise T_autre_pb au temps passe en parametre
Definition at line 366 of file Echange_contact_VDF.cpp.
{
  const Front_VF& ma_front_vf = ref_cast(Front_VF,frontiere_dis());
  int nb_faces_bord = ma_front_vf.nb_faces();
  assert(Teta_eq.dimension(0)==nb_faces_bord);
  assert(Teta_eq.dimension(1)==1);
  DoubleTab& t_autre=T_autre_pb()->valeurs_au_temps(temps);
  for (int numfa=0; numfa<nb_faces_bord; numfa++)
    {
      Teta_eq(numfa,0) = t_autre(numfa,0);
    }
  Teta_eq.echange_espace_virtuel();
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Cond_lim_base::frontiere_dis(), Front_VF::nb_faces(), ref_cast, and T_autre_pb().
Referenced by mettre_a_jour().
calculer_Teta_paroi()
void Echange_contact_VDF::calculer_Teta_paroi (DoubleTab & tab_p, const DoubleTab & mon_h, const DoubleTab & autre_h, int is_pb_fluide, double temps) virtual
remplit Teta_p
utilise T_autre_pb au temps passe en parametre
Definition at line 383 of file Echange_contact_VDF.cpp.
{
  const Equation_base& mon_eqn = zone_Cl_dis().equation();
  const DoubleTab& mon_inco=mon_eqn.inconnue().valeurs();
  const Zone_VDF& ma_zvdf = ref_cast(Zone_VDF,zone_Cl_dis().zone_dis().valeur());
  const Front_VF& ma_front_vf = ref_cast(Front_VF,frontiere_dis());
  int ndeb = ma_front_vf.num_premiere_face();
  int nb_faces_bord = ma_front_vf.nb_faces();
  int ind_fac,elem;
  Teta_p.resize(nb_faces_bord,1);
  DoubleTab& t_autre=T_autre_pb()->valeurs_au_temps(temps);
  for (int numfa=0; numfa<nb_faces_bord; numfa++)
    {
      ind_fac = numfa+ndeb;
      if (ma_zvdf.face_voisins(ind_fac,0)!= -1)
        elem = ma_zvdf.face_voisins(ind_fac,0);
      else
        elem = ma_zvdf.face_voisins(ind_fac,1);
      Teta_p(numfa,0) = (mon_h(numfa,0)*mon_inco(elem) + lautre_h(numfa,0)*t_autre(numfa,0))/(mon_h(numfa,0)+lautre_h(numfa,0));
    }
}
References MorEqn::equation(), Zone_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Equation_base::inconnue(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, TRUSTTab< _TYPE_ >::resize(), T_autre_pb(), valeur(), Champ_Inc::valeurs(), and Cond_lim_base::zone_Cl_dis().
Referenced by mettre_a_jour().
changer_temps_futur()
void Echange_contact_VDF::changer_temps_futur (double temps, int i) override virtual
Change le i-eme temps futur de la CL.
Reimplemented from Echange_global_impose.
Definition at line 65 of file Echange_contact_VDF.cpp.
{
  Cond_lim_base::changer_temps_futur(temps,i);
  T_autre_pb()->changer_temps_futur(temps,i);
}
References Cond_lim_base::changer_temps_futur(), and T_autre_pb().
completer()
void Echange_contact_VDF::completer (void) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Echange_global_impose.
Definition at line 54 of file Echange_contact_VDF.cpp.
{
  Echange_global_impose::completer();
  int nb_cases=zone_Cl_dis().equation().schema_temps().nb_valeurs_temporelles();
  T_autre_pb().associer_fr_dis_base(T_ext().frontiere_dis());
  T_autre_pb()->completer();
  T_autre_pb()->fixer_nb_valeurs_temporelles(nb_cases);
}
References Champ_front::associer_fr_dis_base(), Echange_global_impose::completer(), MorEqn::equation(), Cond_lim_base::frontiere_dis(), Schema_Temps_base::nb_valeurs_temporelles(), Equation_base::schema_temps(), T_autre_pb(), Echange_impose_base::T_ext(), and Cond_lim_base::zone_Cl_dis().
cree_instance()
Objet_U * Echange_contact_VDF::cree_instance () static
Definition at line 30 of file Echange_contact_VDF.cpp.
duplique()
int Echange_contact_VDF::duplique () const override virtual
Reimplemented from Echange_global_impose.
Definition at line 30 of file Echange_contact_VDF.cpp.
get_info()
const Type_info * Echange_contact_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Echange_global_impose.
Definition at line 30 of file Echange_contact_VDF.cpp.
get_remote_elems()
const IntTab & Echange_contact_VDF::get_remote_elems () const inline
Definition at line 63 of file Echange_contact_VDF.h.
  {
// renvoie e_pb1 -> e_pb2 pour e voisin d'une face de paroi contact
// avec nl, nc  le nombre de lignes et de colonnes de la matrice de couplage entre le pb1 et le pb2
    return remote_elems_;
  };
References remote_elems_.
h_autre_pb()
const DoubleTab & Echange_contact_VDF::h_autre_pb () const inline
Definition at line 59 of file Echange_contact_VDF.h.
  {
    return autre_h;
  };
References autre_h.
info()
const Type_info * Echange_contact_VDF::info () static
Definition at line 30 of file Echange_contact_VDF.cpp.
initialiser()
int Echange_contact_VDF::initialiser (double temps) override virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Echange_global_impose.
Definition at line 262 of file Echange_contact_VDF.cpp.
{
  if (!Echange_global_impose::initialiser(temps))
    return 0;
  Champ_front_calc& ch=ref_cast(Champ_front_calc, T_autre_pb().valeur());
  const Equation_base& o_eqn = ch.equation();
  const Front_VF& fvf = ref_cast(Front_VF, frontiere_dis()), o_fvf = ref_cast(Front_VF, ch.front_dis());
  const Zone_VDF& o_zone = ref_cast(Zone_VDF, ch.zone_dis());
  const IntTab& o_f_e = o_zone.face_voisins();
  const Milieu_base& le_milieu=ch.milieu();
  int nb_comp = le_milieu.conductivite()->nb_comp();
  Nom nom_racc1=frontiere_dis().frontiere().le_nom();
  Zone_dis_base& zone_dis1 = zone_Cl_dis().zone_dis().valeur();
  int nb_faces_raccord1 = zone_dis1.zone().raccord(nom_racc1).valeur().nb_faces();
  h_imp_.typer("Champ_front_fonc");
  h_imp_->fixer_nb_comp(nb_comp);
  h_imp_.valeurs().resize(nb_faces_raccord1,nb_comp);
  if (zone_dis1.zone().raccord(nom_racc1).valeur().que_suis_je() !="Raccord_distant_homogene")
    verifier_correspondance();
  autre_h.resize(nb_faces_raccord1,nb_comp);
  ch.initialiser(temps,zone_Cl_dis().equation().inconnue());
  monolithic = sub_type(Schema_Euler_Implicite, o_eqn.schema_temps()) ?
               ref_cast(Schema_Euler_Implicite, o_eqn.schema_temps()).resolution_monolithique(o_eqn.domaine_application()) : 0;
  if (!monolithic) return 1; //pas besoin du reste
  o_zone.init_virt_e_map();
  /* src(i) = (proc, j) : source de l'item i de mdv_elem */
  IntTab src(0, 2);
  MD_Vector_tools::creer_tableau_distribue(o_zone.zone().md_vector_elements(), src);
  for (int i = 0; i < src.dimension_tot(0); i++) src(i, 0) = Process::me(), src(i, 1) = i;
  src.echange_espace_virtuel();
  /* o_proc, o_item -> processeur/item de l'element pour chaque face de la frontiere */
  DoubleTrav o_proc, o_item, proc, l_item;
  o_zone.creer_tableau_faces(o_proc), o_zone.creer_tableau_faces(o_item);
  fvf.frontiere().creer_tableau_faces(proc), fvf.frontiere().creer_tableau_faces(l_item);
  for (int i = 0; i < o_fvf.nb_faces(); i++)
    {
      int f = o_fvf.num_face(i), e = o_f_e(f, 0) == -1 ? o_f_e(f, 1) : o_f_e(f, 0);
      o_proc(f) = src(e, 0), o_item(f) = src(e, 1); //element
    }
// projection sur la frontiere locale
  if (o_fvf.frontiere().que_suis_je() == "Raccord_distant_homogene")
    o_fvf.frontiere().trace_face_distant(o_proc, proc), o_fvf.frontiere().trace_face_distant(o_item, l_item);
  else o_fvf.frontiere().trace_face_local(o_proc, proc), o_fvf.frontiere().trace_face_local(o_item, l_item);
// remplissage
  item.resize(fvf.nb_faces()), item = -1;
  for (int i = 0; i < fvf.nb_faces(); i++)
    if (l_item(i) >= 0)
      {
        if (proc(i) == Process::me()) item(i) = l_item(i);                     //item local (reel)
        else
          {
            if (o_zone.virt_e_map.count({{ (int) proc(i), (int) l_item(i) }}))   //item local (virtuel)
            item(i) = o_zone.virt_e_map.at({{ (int) proc(i),  (int) l_item(i) }});
            else Process::exit(Nom("Echange_contact_VDF : missing element opposite face ") + Nom(fvf.num_face(i)) + " in " + fvf.le_nom() + " ! Have you used Decouper_multi?");
          }
      }
  return 1;
}
References autre_h, Milieu_base::conductivite(), MD_Vector_tools::creer_tableau_distribue(), Frontiere::creer_tableau_faces(), Zone_VF::creer_tableau_faces(), TRUSTTab< _TYPE_ >::dimension_tot(), Equation_base::domaine_application(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Champ_front_calc::equation(), Process::exit(), Zone_VF::face_voisins(), Champ_front_calc::front_dis(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Echange_impose_base::h_imp_, Zone_VDF::init_virt_e_map(), Echange_global_impose::initialiser(), Champ_front_calc::initialiser(), item, Frontiere_dis_base::le_nom(), Frontiere::le_nom(), Zone::md_vector_elements(), Process::me(), Champ_front_calc::milieu(), monolithic, Champ_Don::nb_comp(), Frontiere::nb_faces(), Front_VF::nb_faces(), Front_VF::num_face(), Objet_U::que_suis_je(), Zone::raccord(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Equation_base::schema_temps(), sub_type, T_autre_pb(), Deriv_::typer(), Deriv_Zone_dis_base::valeur(), Deriv_Raccord_base::valeur(), valeur(), Champ_front::valeurs(), verifier_correspondance(), Zone_VDF::virt_e_map, Zone_dis_base::zone(), Cond_lim_base::zone_Cl_dis(), Zone_Cl_dis_base::zone_dis(), and Champ_front_calc::zone_dis().
mettre_a_jour()
void Echange_contact_VDF::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Reimplemented from Echange_global_impose.
Definition at line 331 of file Echange_contact_VDF.cpp.
{
  Champ_front_calc& ch=ref_cast(Champ_front_calc, T_autre_pb().valeur());
  const Milieu_base& le_milieu=ch.milieu();
  int nb_comp = le_milieu.conductivite()->nb_comp();
  assert(nb_comp==1);
  T_autre_pb().mettre_a_jour(temps);
  int is_pb_fluide=0;
  DoubleTab& mon_h= h_imp_->valeurs();
  int opt=0;
  assert(h_paroi!=0.);
  double invhparoi=1./h_paroi;
  calculer_h_autre_pb( autre_h, invhparoi, opt);
  calculer_h_mon_pb(mon_h,0.,opt);
  calculer_Teta_paroi(T_wall_,mon_h,autre_h,is_pb_fluide,temps);
  calculer_Teta_equiv(T_ext()->valeurs_au_temps(temps),mon_h,autre_h,is_pb_fluide,temps);
// on a calculer Teta paroi, on peut calculer htot dans himp (= mon_h)
  int taille=mon_h.dimension(0);
  for (int ii=0; ii<taille; ii++)
    for (int jj=0; jj<nb_comp; jj++)
      {
        mon_h(ii,jj)=1./(1./autre_h(ii,jj)+1./mon_h(ii,jj));
      }
  Echange_global_impose::mettre_a_jour(temps);
}
References autre_h, calculer_h_autre_pb(), calculer_h_mon_pb(), calculer_Teta_equiv(), calculer_Teta_paroi(), Milieu_base::conductivite(), TRUSTTab< _TYPE_ >::dimension(), Echange_impose_base::h_imp_, h_paroi, Champ_front::mettre_a_jour(), Echange_global_impose::mettre_a_jour(), Champ_front_calc::milieu(), Champ_Don::nb_comp(), ref_cast, T_autre_pb(), Echange_impose_base::T_ext(), T_wall_, valeur(), and Champ_front::valeurs().
nom_autre_pb()
const Nom & Echange_contact_VDF::nom_autre_pb () const inline
Definition at line 69 of file Echange_contact_VDF.h.
  {
    return nom_autre_pb_;
  };
References nom_autre_pb_.
Referenced by Op_Diff_VDF_Elem_base::contribuer_termes_croises(), and Op_Diff_VDF_Elem_base::dimensionner_termes_croises().
printOn()
Sortie & Echange_contact_VDF::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Echange_global_impose.
Definition at line 35 of file Echange_contact_VDF.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Echange_contact_VDF::readOn (Entree & s) override protected virtual
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Echange_global_impose.
Definition at line 40 of file Echange_contact_VDF.cpp.
{
  Nom nom_pb, nom_bord;
  Motcle nom_champ;
  s >> nom_pb >> nom_bord >> nom_champ >> h_paroi;
  T_autre_pb().typer("Champ_front_calc");
  Champ_front_calc& ch=ref_cast(Champ_front_calc, T_autre_pb().valeur());
  ch.creer(nom_pb, nom_bord, nom_champ);
  T_ext().typer("Ch_front_var_instationnaire_dep");
  T_ext()->fixer_nb_comp(1);
  nom_autre_pb_ = nom_pb;
  return s ;
}
References Champ_front_calc::creer(), h_paroi, nom_autre_pb_, ref_cast, T_autre_pb(), Echange_impose_base::T_ext(), Deriv_::typer(), and valeur().
reculer()
int Echange_contact_VDF::reculer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Echange_global_impose.
Definition at line 82 of file Echange_contact_VDF.cpp.
{
  int ok=Cond_lim_base::reculer(temps);
  ok = ok && T_autre_pb()->reculer(temps);
  return ok;
}
References Cond_lim_base::reculer(), and T_autre_pb().
self_cast() [1/2]
const Echange_contact_VDF & Echange_contact_VDF::self_cast (const Objet_U & r) static
Definition at line 30 of file Echange_contact_VDF.cpp.
self_cast() [2/2]
Echange_contact_VDF & Echange_contact_VDF::self_cast (Objet_U & r) static
Definition at line 30 of file Echange_contact_VDF.cpp.
T_autre_pb() [1/2]
virtual Champ_front & Echange_contact_VDF::T_autre_pb () inline virtual
Definition at line 44 of file Echange_contact_VDF.h.
  {
    return T_autre_pb_;
  };
References T_autre_pb_.
Referenced by avancer(), calculer_h_autre_pb(), calculer_Teta_equiv(), calculer_Teta_paroi(), changer_temps_futur(), completer(), Op_Diff_VDF_base::init_op_ext(), initialiser(), mettre_a_jour(), readOn(), reculer(), and verifier_correspondance().
T_autre_pb() [2/2]
virtual const Champ_front & Echange_contact_VDF::T_autre_pb () const inline virtual
Definition at line 48 of file Echange_contact_VDF.h.
  {
    return T_autre_pb_;
  };
References T_autre_pb_.
T_wall()
const DoubleTab & Echange_contact_VDF::T_wall () const inline
Definition at line 55 of file Echange_contact_VDF.h.
  {
    return T_wall_;
  };
References T_wall_.
taille_memoire()
unsigned Echange_contact_VDF::taille_memoire () const override virtual
Reimplemented from Echange_global_impose.
Definition at line 30 of file Echange_contact_VDF.cpp.
verifier_correspondance()
int Echange_contact_VDF::verifier_correspondance () const
Definition at line 407 of file Echange_contact_VDF.cpp.
{
  const Champ_front_calc& ch=ref_cast(Champ_front_calc, T_autre_pb().valeur());
  const Zone_VDF& ma_zvdf = ref_cast(Zone_VDF,zone_Cl_dis().zone_dis().valeur());
  const Front_VF& ma_front_vf = ref_cast(Front_VF,frontiere_dis());
  const Zone_VDF& zvdf_2=ref_cast(Zone_VDF, ch.zone_dis());
  const Front_VF& front_vf=ref_cast(Front_VF, ch.front_dis());
  int ndeb = ma_front_vf.num_premiere_face();
  int ndeb2 = front_vf.num_premiere_face();
  int nb_faces_bord = ma_front_vf.nb_faces();
  int ind_fac,ind_fac_2;
  const DoubleTab& xv=ma_zvdf.xv();
  const DoubleTab& xv2=zvdf_2.xv();
  DoubleVect x1(dimension);
  DoubleVect x2(dimension);
  for (int numfa=0; numfa<nb_faces_bord; numfa++)
    {
      ind_fac = numfa+ndeb;
      ind_fac_2=numfa+ndeb2;
      for (int k=0; k<dimension; k++)
        {
          x1[k] = xv(ind_fac,k);
          x2[k] = xv2(ind_fac_2,k);
        }
      if (!meme_point2(x1,x2))
        {
          Cerr<<finl;
          Cerr<<"Correspondence problem: the two 'Raccords' named "<<ma_front_vf.le_nom() <<" are not facing."<<finl;
          Cerr<<"Problem on the following faces:" << finl;
          if ( dimension==2 )
            {
              Cerr << "Coordinates of the face 1: (" << x1[0] << " " << x1[1] << ") on the domain " << ma_zvdf.domaine_dis().domaine().le_nom() << finl;
              Cerr << "Coordinates of the face 2: (" << x2[0] << " " << x2[1] << ") on the domain " << zvdf_2.domaine_dis().domaine().le_nom()  << finl;
            }
          else
            {
              Cerr << "Coordinates of the face 1: (" << x1[0] << " " << x1[1] << x1[2] << ") on the domain " << ma_zvdf.domaine_dis().domaine().le_nom() << finl;
              Cerr << "Coordinates of the face 2: (" << x2[0] << " " << x2[1] << x2[2] << ") on the domain " << zvdf_2.domaine_dis().domaine().le_nom()  << finl;
            }
          Cerr << "\nIn VDF, numbering of faces on each 'Raccord' must be identical (to a constant)." << finl;
          Cerr << "The faces of each sub frontier of the boundary " << ma_front_vf.le_nom() << " must be created in the same order on each domain, this process is sensitive to the reading sense of the faces." << finl;
          exit();
          return 0;
        }
    }
  return 1;
}
References Cerr, Objet_U::dimension, Domaine_dis::domaine(), Zone_dis_base::domaine_dis(), Process::exit(), finl, Champ_front_calc::front_dis(), Cond_lim_base::frontiere_dis(), Frontiere_dis_base::le_nom(), Domaine::le_nom(), meme_point2(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, T_autre_pb(), valeur(), Zone_VF::xv(), Cond_lim_base::zone_Cl_dis(), and Champ_front_calc::zone_dis().
Referenced by initialiser().
Member Data Documentation
autre_h
DoubleTab Echange_contact_VDF::autre_h protected
Definition at line 82 of file Echange_contact_VDF.h.
Referenced by h_autre_pb(), initialiser(), and mettre_a_jour().
h_paroi
double Echange_contact_VDF::h_paroi protected
Definition at line 81 of file Echange_contact_VDF.h.
Referenced by mettre_a_jour(), and readOn().
info_obj
const Type_info Echange_contact_VDF::info_obj static
Definition at line 37 of file Echange_contact_VDF.h.
item
IntTab Echange_contact_VDF::item mutable
Definition at line 78 of file Echange_contact_VDF.h.
Referenced by Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), and initialiser().
monolithic
int Echange_contact_VDF::monolithic
Definition at line 79 of file Echange_contact_VDF.h.
Referenced by initialiser().
nom_autre_pb_
Nom Echange_contact_VDF::nom_autre_pb_ protected
Definition at line 85 of file Echange_contact_VDF.h.
Referenced by nom_autre_pb(), and readOn().
remote_elems_
IntTab Echange_contact_VDF::remote_elems_ protected
Definition at line 86 of file Echange_contact_VDF.h.
Referenced by get_remote_elems().
T_autre_pb_
Champ_front Echange_contact_VDF::T_autre_pb_ protected
Definition at line 83 of file Echange_contact_VDF.h.
Referenced by T_autre_pb().
T_wall_
DoubleTab Echange_contact_VDF::T_wall_ protected
Definition at line 84 of file Echange_contact_VDF.h.
Referenced by mettre_a_jour(), and T_wall().
The documentation for this class was generated from the following files:
src/VDF/Cond_Lim/Echange_contact_VDF.h
src/VDF/Cond_Lim/Echange_contact_VDF.cpp