TRUST: Eval_Gravite_VDF_Face Class Reference
Eval_Gravite_VDF_Face Class Reference
#include <Eval_Gravite_VDF_Face.h>
Public Member Functions
Eval_Gravite_VDF_Face ()
Eval_Gravite_VDF_Face (const Eval_Gravite_VDF_Face &eval)
template<typename Type_Double >
void calculer_terme_source (const int, Type_Double &) const
template<typename Type_Double >
void calculer_terme_source_bord (const int num_face, Type_Double &source) const
void associer (const Champ_Don_base &)
void mettre_a_jour () override
Public Member Functions inherited from Evaluateur_Source_VDF_Face
Evaluateur_Source_VDF_Face ()
Evaluateur_Source_VDF_Face (const Evaluateur_Source_VDF_Face &)
void completer () override
template<typename Type_Double >
void calculer_terme_source_bord (int, Type_Double &) const
Public Member Functions inherited from Evaluateur_Source_VDF
Evaluateur_Source_VDF ()
Evaluateur_Source_VDF (const Evaluateur_Source_VDF &eval)
virtual ~Evaluateur_Source_VDF ()
template<typename Type_Double >
void calculer_terme_source (int, Type_Double &) const
virtual void mettre_a_jour ()=0
virtual void completer ()=0
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
Protected Attributes
Ref_Champ_Don_base la_gravite
DoubleVect g
Protected Attributes inherited from Evaluateur_Source_VDF_Face
IntVect orientation
orientations des faces
DoubleVect volumes_entrelaces
DoubleVect porosite_surf
porosites surfaciques
Protected Attributes inherited from Evaluateur_Source_VDF
Ref_Zone_VDF la_zone
Ref_Zone_Cl_VDF la_zcl
Detailed Description
Definition at line 23 of file Eval_Gravite_VDF_Face.h.
Constructor & Destructor Documentation
Eval_Gravite_VDF_Face() [1/2]
Eval_Gravite_VDF_Face::Eval_Gravite_VDF_Face () inline
Definition at line 26 of file Eval_Gravite_VDF_Face.h.
{ }
Eval_Gravite_VDF_Face() [2/2]
Eval_Gravite_VDF_Face::Eval_Gravite_VDF_Face (const Eval_Gravite_VDF_Face & eval) inline
Definition at line 27 of file Eval_Gravite_VDF_Face.h.
: Evaluateur_Source_VDF_Face(eval), la_gravite(eval.la_gravite) { g.ref(eval.g); }
References g, and TRUSTVect< _TYPE_ >::ref().
Member Function Documentation
associer()
void Eval_Gravite_VDF_Face::associer (const Champ_Don_base & gravite) inline
Definition at line 38 of file Eval_Gravite_VDF_Face.h.
{
  la_gravite = gravite;
  g.ref(gravite.valeurs());
}
References g, la_gravite, TRUSTVect< _TYPE_ >::ref(), and Champ_Don_base::valeurs().
Referenced by Terme_Gravite_VDF_Face::associer_gravite().
calculer_terme_source()
template<typename Type_Double > void Eval_Gravite_VDF_Face::calculer_terme_source (const int num_face, Type_Double & source) const
Definition at line 45 of file Eval_Gravite_VDF_Face.h.
{
  const int size = source.size_array();
  for (int i = 0; i < size; i++) source[i] = g(orientation(num_face))*volumes_entrelaces(num_face)*porosite_surf(num_face);
}
References g, Evaluateur_Source_VDF_Face::orientation, Evaluateur_Source_VDF_Face::porosite_surf, and Evaluateur_Source_VDF_Face::volumes_entrelaces.
Referenced by calculer_terme_source_bord().
calculer_terme_source_bord()
template<typename Type_Double > void Eval_Gravite_VDF_Face::calculer_terme_source_bord (const int num_face, Type_Double & source) const inline
Definition at line 29 of file Eval_Gravite_VDF_Face.h.
{ calculer_terme_source(num_face,source);}
References calculer_terme_source().
mettre_a_jour()
void Eval_Gravite_VDF_Face::mettre_a_jour () inline override virtual
Implements Evaluateur_Source_VDF.
Definition at line 31 of file Eval_Gravite_VDF_Face.h.
{ /* Do nothing */ }
Member Data Documentation
g
DoubleVect Eval_Gravite_VDF_Face::g protected
Definition at line 35 of file Eval_Gravite_VDF_Face.h.
Referenced by associer(), calculer_terme_source(), and Eval_Gravite_VDF_Face().
la_gravite
Ref_Champ_Don_base Eval_Gravite_VDF_Face::la_gravite protected
Definition at line 34 of file Eval_Gravite_VDF_Face.h.
Referenced by associer().
The documentation for this class was generated from the following file:
src/VDF/Sources/Evaluateurs/Eval_Gravite_VDF_Face.h