TRUST: Terme_Puissance_Thermique_Echange_Impose_P0_VDF Class Reference
Terme_Puissance_Thermique_Echange_Impose_P0_VDF Class Reference
class Terme_Puissance_Thermique_Echange_Impose_P0_VDF
#include <Terme_Puissance_Thermique_Echange_Impose_P0_VDF.h>
Public Member Functions
~Terme_Puissance_Thermique_Echange_Impose_P0_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & calculer (DoubleTab &) const override
void associer_pb (const Probleme_base &) override
void mettre_a_jour (double) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) const override
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Terme_Puissance_Thermique_Echange_Impose_P0_VDF & self_cast (Objet_U &)
static const Terme_Puissance_Thermique_Echange_Impose_P0_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VDF la_zone_VDF
Ref_Zone_Cl_VDF la_zone_Cl_VDF
Champ_Don himp_
Champ_Don Text_
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Terme_Puissance_Thermique_Echange_Impose_P0_VDF
See also
Source_base
Definition at line 37 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.h.
Constructor & Destructor Documentation
~Terme_Puissance_Thermique_Echange_Impose_P0_VDF()
Terme_Puissance_Thermique_Echange_Impose_P0_VDF::~Terme_Puissance_Thermique_Echange_Impose_P0_VDF ()
Definition at line 26 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
Member Function Documentation
ajouter_blocs()
void Terme_Puissance_Thermique_Echange_Impose_P0_VDF::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_base.
Definition at line 107 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
{
  int nb_elem=la_zone_VDF.valeur().nb_elem();
  const Zone_VF&     zone               = la_zone_VDF.valeur();
  const DoubleVect& volumes = zone.volumes();
  const DoubleTab& himp = himp_.valeur().valeurs();
  const DoubleTab& Text = Text_.valeur().valeurs();
  const DoubleTab& T = equation().inconnue().valeurs();
  const std::string& nom_inco = equation().inconnue().le_nom().getString();
  Matrice_Morse *mat = matrices.count(nom_inco) ? matrices.at(nom_inco) : NULL;
  for (int e = 0; e < nb_elem; e++)
    {
      if(mat) (*mat)(e, e) += volumes(e) * himp.addr()[himp.dimension(0) > 1 ? e : 0];
      secmem(e) -= volumes(e) * himp.addr()[himp.dimension(0) > 1 ? e : 0] * (T(e) - Text.addr()[Text.dimension(0) > 1 ? e : 0]);
    }
}
References TRUSTArray< _TYPE_ >::addr(), TRUSTTab< _TYPE_ >::dimension(), MorEqn::equation(), Nom::getString(), himp_, Equation_base::inconnue(), la_zone_VDF, O_U_Ptr::le_nom(), Zone_dis_base::nb_elem(), Text_, Deriv_Champ_Don_base::valeur(), Ref_Zone_VDF::valeur(), Champ_Don_base::valeurs(), Champ_Inc::valeurs(), and Zone_VF::volumes().
associer_pb()
void Terme_Puissance_Thermique_Echange_Impose_P0_VDF::associer_pb (const Probleme_base &) inline override virtual
Implements Source_base.
Definition at line 47 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.h.
{ };
associer_zones()
void Terme_Puissance_Thermique_Echange_Impose_P0_VDF::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
Implements Source_base.
Definition at line 80 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
{
  la_zone_VDF = ref_cast(Zone_VDF, zone_dis.valeur());
  la_zone_Cl_VDF = ref_cast(Zone_Cl_VDF, zone_Cl_dis.valeur());
}
References la_zone_Cl_VDF, la_zone_VDF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
calculer()
DoubleTab & Terme_Puissance_Thermique_Echange_Impose_P0_VDF::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 125 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
{
  resu=0;
  ajouter(resu);
  return resu;
}
References Source_base::ajouter().
cree_instance()
Objet_U * Terme_Puissance_Thermique_Echange_Impose_P0_VDF::cree_instance () static
Definition at line 26 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
dimensionner_blocs()
void Terme_Puissance_Thermique_Echange_Impose_P0_VDF::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_base.
Definition at line 87 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
{
  const std::string& nom_inco = equation().inconnue().le_nom().getString();
  Matrice_Morse *mat = matrices.count(nom_inco) ? matrices.at(nom_inco) : NULL, mat2;
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  IntTab stencil(0, 2);
  stencil.set_smart_resize(1);
  for (int e = 0; e < zone_VDF.nb_elem(); e++)
    stencil.append_line(e, e);
  tableau_trier_retirer_doublons(stencil);
  if (mat)
    {
      Matrix_tools::allocate_morse_matrix(zone_VDF.nb_elem_tot(), zone_VDF.nb_elem_tot(), stencil, mat2);
      mat->nb_colonnes() ? *mat += mat2 : *mat = mat2;
    }
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), la_zone_VDF, O_U_Ptr::le_nom(), Matrice_Morse::nb_colonnes(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), TRUSTArray< _TYPE_ >::set_smart_resize(), tableau_trier_retirer_doublons(), and Ref_Zone_VDF::valeur().
duplique()
int Terme_Puissance_Thermique_Echange_Impose_P0_VDF::duplique () const override virtual
Implements Objet_U.
Definition at line 26 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
get_info()
const Type_info * Terme_Puissance_Thermique_Echange_Impose_P0_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 26 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
has_interface_blocs()
int Terme_Puissance_Thermique_Echange_Impose_P0_VDF::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Definition at line 49 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.h.
  {
    return 1;
  };
info()
const Type_info * Terme_Puissance_Thermique_Echange_Impose_P0_VDF::info () static
Definition at line 26 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
mettre_a_jour()
void Terme_Puissance_Thermique_Echange_Impose_P0_VDF::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 53 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
{
  int nb_elem = la_zone_VDF.valeur().nb_elem();
  const Zone_VF& zone = la_zone_VDF.valeur();
  const DoubleVect& volumes = zone.volumes();
  const DoubleTab& himp = himp_.valeur().valeurs();
  const DoubleTab& Text = Text_.valeur().valeurs();
  const DoubleTab& T = equation().inconnue().valeurs();
  bilan()(0) = 0;
  for (int e = 0; e < nb_elem; e++)
    bilan()(0) += himp.addr()[himp.dimension(0) > 1 ? e : 0] * volumes(e) * (Text.addr()[Text.dimension(0) > 1 ? e : 0] - T(e));
  himp_.mettre_a_jour(temps);
  Text_.mettre_a_jour(temps);
}
References TRUSTArray< _TYPE_ >::addr(), Source_base::bilan(), TRUSTTab< _TYPE_ >::dimension(), MorEqn::equation(), himp_, Equation_base::inconnue(), la_zone_VDF, Champ_Don::mettre_a_jour(), Zone_dis_base::nb_elem(), Text_, Deriv_Champ_Don_base::valeur(), Ref_Zone_VDF::valeur(), Champ_Don_base::valeurs(), Champ_Inc::valeurs(), and Zone_VF::volumes().
printOn()
Sortie & Terme_Puissance_Thermique_Echange_Impose_P0_VDF::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 33 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
{
  return s << que_suis_je();
}
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Puissance_Thermique_Echange_Impose_P0_VDF::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 42 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
{
  Param param(que_suis_je());
  param.ajouter("himp",&himp_,Param::REQUIRED);
  param.ajouter("Text",&Text_,Param::REQUIRED);
  param.lire_avec_accolades_depuis(s);
  set_fichier("Terme_Puissance_Thermique_Echange_Impose");
  set_description("Power (W)");
  return s ;
}
References Param::ajouter(), himp_, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), Param::REQUIRED, Source_base::set_description(), Source_base::set_fichier(), and Text_.
self_cast() [1/2]
const Terme_Puissance_Thermique_Echange_Impose_P0_VDF & Terme_Puissance_Thermique_Echange_Impose_P0_VDF::self_cast (const Objet_U & r) static
Definition at line 26 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
self_cast() [2/2]
Terme_Puissance_Thermique_Echange_Impose_P0_VDF & Terme_Puissance_Thermique_Echange_Impose_P0_VDF::self_cast (Objet_U & r) static
Definition at line 26 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
taille_memoire()
unsigned Terme_Puissance_Thermique_Echange_Impose_P0_VDF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 26 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp.
Member Data Documentation
himp_
Champ_Don Terme_Puissance_Thermique_Echange_Impose_P0_VDF::himp_ protected
Definition at line 60 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.h.
Referenced by ajouter_blocs(), mettre_a_jour(), and readOn().
info_obj
const Type_info Terme_Puissance_Thermique_Echange_Impose_P0_VDF::info_obj static
Definition at line 42 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.h.
la_zone_Cl_VDF
Ref_Zone_Cl_VDF Terme_Puissance_Thermique_Echange_Impose_P0_VDF::la_zone_Cl_VDF protected
Definition at line 59 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.h.
Referenced by associer_zones().
la_zone_VDF
Ref_Zone_VDF Terme_Puissance_Thermique_Echange_Impose_P0_VDF::la_zone_VDF protected
Definition at line 58 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.h.
Referenced by ajouter_blocs(), associer_zones(), dimensionner_blocs(), and mettre_a_jour().
Text_
Champ_Don Terme_Puissance_Thermique_Echange_Impose_P0_VDF::Text_ protected
Definition at line 60 of file Terme_Puissance_Thermique_Echange_Impose_P0_VDF.h.
Referenced by ajouter_blocs(), mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/VDF/Sources/Terme_Puissance_Thermique_Echange_Impose_P0_VDF.h
src/VDF/Sources/Terme_Puissance_Thermique_Echange_Impose_P0_VDF.cpp