TRUST: Solv_GCP Class Reference
Solv_GCP Class Reference
#include <Solv_GCP.h>
Public Member Functions
~Solv_GCP ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Solv_GCP ()
int resoudre_systeme (const Matrice_Base &, const DoubleVect &, DoubleVect &) override
int resoudre_systeme (const Matrice_Base &, const DoubleVect &, DoubleVect &, int) override
const Precond & get_precond () const
void set_precond (const Precond &)
void reinit () override
int supporte_matrice_morse_sym () override
int get_flag_updated_input () const override
Public Member Functions inherited from solv_iteratif
~solv_iteratif () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
solv_iteratif ()
void set_seuil (double s)
double get_seuil () const
int solveur_direct () const override
Public Member Functions inherited from SolveurSys_base
~SolveurSys_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
SolveurSys_base ()
virtual int solveur_direct () const =0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x)=0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x, int niter_max)
virtual void fixer_schema_temps_limpr (int l)
void fixer_limpr (int l)
void set_return_on_error (int ret)
int limpr () const
virtual void reinit ()
int nouvelle_matrice () const
void fixer_nouvelle_matrice (int i)
virtual int supporte_matrice_morse_sym ()
virtual int get_flag_updated_input () const
void set_flag_updated_result (int flag)
int get_flag_updated_result () const
void save_matrice_secmem_conditionnel (const Matrice_Base &la_matrice, const DoubleVect &secmem, const DoubleVect &solution, int binaire=1)
void set_reuse_preconditioner (bool flag)
bool reuse_preconditioner ()
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Solv_GCP & self_cast (Objet_U &)
static const Solv_GCP & self_cast (const Objet_U &)
Static Public Member Functions inherited from solv_iteratif
static const Type_info * info ()
static solv_iteratif & self_cast (Objet_U &)
static const solv_iteratif & self_cast (const Objet_U &)
Static Public Member Functions inherited from SolveurSys_base
static const Type_info * info ()
static SolveurSys_base & self_cast (Objet_U &)
static const SolveurSys_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from solv_iteratif
static const Type_info info_obj
Static Public Attributes inherited from SolveurSys_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void prepare_data (const Matrice_Base &matrice, const DoubleVect &secmem, DoubleVect &solution)
int resoudre_ (const Matrice_Base &, const DoubleVect &, DoubleVect &, int)
Protected Member Functions inherited from solv_iteratif
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from SolveurSys_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int optimized_
Precond le_precond_
int precond_diag_
DoubleVect tmp_p_avec_items_virt_
DoubleVect resu_
DoubleVect residu_
DoubleVect tmp_p_
DoubleVect tmp_solution_
Matrice_Morse_Sym tmp_mat_
Matrice_SuperMorse tmp_mat_virt_
ArrOfDouble tmp_data_block_
IntVect renum_
DoubleVect inv_sqrt_diag_
int reinit_
0=> rien n'est pret 1=> memoire allouee, coeffs matrice a copier, 2=> ok
int nb_it_max_
Protected Attributes inherited from solv_iteratif
double seuil_
Protected Attributes inherited from SolveurSys_base
int nouvelle_matrice_
Drapeau pour savoir si un stockage ou une factorisation est a refaire.
int save_matrice_
Drapeau pour savoir si un stockage disque est a refaire.
int return_on_error_ = 0
Detailed Description
Definition at line 24 of file Solv_GCP.h.
Constructor & Destructor Documentation
~Solv_GCP()
Solv_GCP::~Solv_GCP ()
Definition at line 26 of file Solv_GCP.cpp.
Solv_GCP()
Solv_GCP::Solv_GCP ()
Definition at line 30 of file Solv_GCP.cpp.
{
  seuil_=1.e-12;
  reinit_ = 0;
  precond_diag_ = 0;
  optimized_ = 0;
  nb_it_max_=-1;
}
References nb_it_max_, optimized_, precond_diag_, reinit_, and solv_iteratif::seuil_.
Member Function Documentation
cree_instance()
Objet_U * Solv_GCP::cree_instance () static
Definition at line 26 of file Solv_GCP.cpp.
duplique()
int Solv_GCP::duplique () const override virtual
Implements Objet_U.
Definition at line 26 of file Solv_GCP.cpp.
get_flag_updated_input()
int Solv_GCP::get_flag_updated_input () const inline override virtual
Reimplemented from SolveurSys_base.
Definition at line 39 of file Solv_GCP.h.
  {
    return 0;
  }
get_info()
const Type_info * Solv_GCP::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 26 of file Solv_GCP.cpp.
get_precond()
const Precond & Solv_GCP::get_precond () const inline
Definition at line 95 of file Solv_GCP.h.
{
  return le_precond_;
}
References le_precond_.
info()
const Type_info * Solv_GCP::info () static
Definition at line 26 of file Solv_GCP.cpp.
prepare_data()
void Solv_GCP::prepare_data (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution) protected
< fortran -> c
< vecteurs avec espace virtuel (tmp_p_)
< vecteurs sans espace virtuel
< pour tab1_
< pour les coefficients
< pour les indices matrice reel/virtuel
< pour tab1_
< pour les coefficients
< pour les indices taille de tmp_mat_virt_.lignes_non_vides_
< avec espace virtuel
< sans l'espace virtuel
< fortran->c
< c->fortran
< index dans mat.tab2_ et coeff_
< index dans tmp_mat_.tab2_ et coeff_
< indice fortran du debut de ligne
< index fortran
< indice fortran du debut de ligne
< indice fortran
< index fortran
< fortran->c
< indice fortran
< index fortran
Definition at line 116 of file Solv_GCP.cpp.
{
  if (reinit_ == 0)
    {
// Reconstruction de toute la structure (tableaux d'index et coefficients)
      if (secmem.line_size() != 1)
        {
          Cerr << "Error line_size>1 not coded (GCP)" << finl;
          exit();
        }
      const Matrice_Bloc& mat_bloc = ref_cast(Matrice_Bloc, matrice);
      const Matrice_Morse_Sym& mat = ref_cast(Matrice_Morse_Sym, mat_bloc.get_bloc(0,0).valeur());
      const Matrice_Morse& mat_virt = ref_cast(Matrice_Morse, mat_bloc.get_bloc(0,1).valeur());
// Determination du nombre d'items reellement utilises:
      {
        const int sztot_source = secmem.size_array();
        const int sz = secmem.size();
        renum_.reset();
        renum_.resize(sztot_source, Array_base::NOCOPY_NOINIT);
        renum_ = 0;
// Retirer les items virtuels
        int i;
        for (i = sz; i < sztot_source; i++)
          renum_[i] = -1;
        renum_.set_md_vector(secmem.get_md_vector());
        const ArrOfInt& tab2 = mat_virt.get_tab2();
        const int n = tab2.size_array();
        for (i = 0; i < n; i++)
          {
// Attention: tab2 de la partie reele-virtuelle contient des indices
// relatifs au debut de la partie virtuelle (d'ou "+ sz")
            const int j = tab2[i]-1 + sz; //!< fortran -> c
            renum_[j] = 0;
          }
      }
// Determination du nombre de lignes non vides de mat_virt
      int nb_lignes_mat_virt = 0;
      {
        const int n = mat_virt.get_tab1().size_array() - 1;
        for (int i = 0; i < n; i++)
          if (mat_virt.get_tab1()(i+1) - mat_virt.get_tab1()(i) > 0)
            nb_lignes_mat_virt++;
      }
// Descripteur contenant uniquement les items utiles:
      MD_Vector md;
      MD_Vector_tools::creer_md_vect_renum_auto(renum_, md);
      const int sz_tot = md.valeur().get_nb_items_tot();
      const int sz = md.valeur().get_nb_items_reels();
// Calcul de la taille memoire requise:
      int mem_size = 0;
      mem_size += sz_tot * sizeof(double); //!<  vecteurs avec espace virtuel (tmp_p_)
      mem_size += sz * sizeof(double) * 3; //!< vecteurs sans espace virtuel
      const int nb_lignes_mat = sz;
// matrice reel/reel
      mem_size += (sz + 1) * sizeof(int); //!< pour tab1_
      int nnz_reel_reel = 0;
      assert(mat.get_tab1().size_array() == sz + 1);
      assert(mat.get_tab2().size_array() == mat.get_coeff().size_array());
      if (! precond_diag_)
        {
          nnz_reel_reel = mat.get_coeff().size_array();
        }
      else
        {
// On ne stocke pas les coefficients diagonaux:
          nnz_reel_reel = mat.get_coeff().size_array() - sz;
        }
      mem_size += nnz_reel_reel * sizeof(double); //!< pour les coefficients
      mem_size += nnz_reel_reel * sizeof(int); //!< pour les indices matrice reel/virtuel
//
      mem_size += (nb_lignes_mat_virt+1) * sizeof(int); //!< pour tab1_
      const int nnz_reel_virtuel = mat_virt.get_coeff().size_array();
      assert(mat_virt.get_tab2().size_array() == nnz_reel_virtuel);
      mem_size += nnz_reel_virtuel * sizeof(double); //!< pour les coefficients
      mem_size += nnz_reel_virtuel * sizeof(int); //!< pour les indices taille de tmp_mat_virt_.lignes_non_vides_
//
      mem_size += nb_lignes_mat_virt * sizeof(int);
// aligner la taille sur un multiple de 8
      if (mem_size % 8 != 0)
        mem_size = (mem_size/8+1)*8;
// Allocation des tableaux:
// (on met d'abord tous les tableaux de double, puis a la fin les tableaux d'entiers
// sinon il faut ajouter du padding pour aligner si on remet des double apres de int)
//
      Journal() << "Solv_GCP::prepare allocating data chunk : " << mem_size << " bytes" << finl;
      tmp_data_block_.resize_array(mem_size/8, Array_base::NOCOPY_NOINIT);
      double *ptr = tmp_data_block_.addr();
      resu_.ref_data(ptr, sz);
      ptr += sz;
      residu_.ref_data(ptr, sz);
      ptr += sz;
      tmp_p_avec_items_virt_.ref_data(ptr, sz_tot); //!< avec espace virtuel
      tmp_p_avec_items_virt_.set_md_vector(md);
// tmp_p_ pointe sur la meme zone:
      tmp_p_.ref_data(ptr, sz); //!< sans l'espace virtuel
      ptr += sz_tot;
      tmp_solution_.ref_data(ptr, sz);
      ptr += sz;
// Allocation des tableaux pour les matrices:
      tmp_mat_.get_set_coeff().ref_data(ptr, nnz_reel_reel);
      ptr += nnz_reel_reel;
      tmp_mat_virt_.get_set_coeff().ref_data(ptr, nnz_reel_virtuel);
      ptr += nnz_reel_virtuel;
// On a fini les double, on passe aux tableaux d'entiers:
      int * iptr = (int*)ptr;
      tmp_mat_.get_set_tab1().ref_data(iptr, nb_lignes_mat + 1);
      iptr += nb_lignes_mat + 1;
      tmp_mat_.get_set_tab2().ref_data(iptr, nnz_reel_reel);
      iptr += nnz_reel_reel;
      tmp_mat_virt_.lignes_non_vides_.ref_data(iptr, nb_lignes_mat_virt);
      iptr += nb_lignes_mat_virt;
      tmp_mat_virt_.get_set_tab1().ref_data(iptr, nb_lignes_mat_virt + 1);
      iptr += nb_lignes_mat_virt + 1;
      tmp_mat_virt_.get_set_tab2().ref_data(iptr, nnz_reel_virtuel);
      iptr += nnz_reel_virtuel;
// Allocation terminee.
      assert(((char*)iptr) <= ((char*)tmp_data_block_.addr() + mem_size));
// Remplissages des tableaux d'index (tab1_, tab2_ et lignes_non_vides_)
      if (! precond_diag_)
        {
          tmp_mat_.get_set_tab1().inject_array(mat.get_tab1());
          {
// remplissage de tab2 (renumerotation eventuelle)
            for (int i = 0; i < nnz_reel_reel; i++)
              {
                int j = mat.get_tab2()(i)-1; //!< fortran->c
                int rj = renum_[j];
                assert(rj < sz_tot);
                tmp_mat_.get_set_tab2()(i) = rj+1; //!< c->fortran
              }
          }
          tmp_mat_.set_nb_columns( sz_tot );
        }
      else
        {
// Construction de la matrice D^(-1/2) * A * D^(-1/2)
// on ne stocke pas les coeffs diagonaux
// Le remplissage de tab1_ n'est pas trivial, du coup:
          {
            int src_index = 0; //!< index dans mat.tab2_ et coeff_
            int dest_index = 0; //!< index dans tmp_mat_.tab2_ et coeff_
            int i_ligne;
            for (i_ligne = 0; i_ligne < nb_lignes_mat; i_ligne++)
              {
// A chaque ligne on a un coefficient de moins que dans la matrice d'origine
// (on ne met pas le coeff diagonal)
                tmp_mat_.get_set_tab1()(i_ligne) = dest_index + 1; //!< indice fortran du debut de ligne
                const int ncoeff = mat.get_tab1()(i_ligne+1) - mat.get_tab1()(i_ligne) - 1;
// Ne pas inserer le coeff diagonal
                assert(mat.get_tab2()(src_index) == i_ligne + 1); //!< index fortran
                src_index++;
// Inserer les autres coeffs:
                for (int i = 0; i < ncoeff; i++, src_index++, dest_index++)
                  tmp_mat_.get_set_tab2()(dest_index) = mat.get_tab2()(src_index);
              }
// Fin de la derniere ligne:
            tmp_mat_.get_set_tab1()(i_ligne) = dest_index + 1; //!< indice fortran du debut de ligne
          }
          tmp_mat_.set_nb_columns( sz_tot );
        }
// remplissage de tmp_mat_virt_
      {
        tmp_mat_virt_.get_set_tab1()[0] = 1;
        int i_ligne_dest = 0;
        int dest_index = 0;
        for (int i_ligne = 0; i_ligne < nb_lignes_mat; i_ligne++)
          {
            const int count = mat_virt.get_tab1()(i_ligne+1) - mat_virt.get_tab1()(i_ligne);
            if (count > 0)
              {
                tmp_mat_virt_.lignes_non_vides_[i_ligne_dest] = i_ligne + 1; //!< indice fortran
                tmp_mat_virt_.get_set_tab1()[i_ligne_dest] = dest_index + 1; //!< index fortran
                i_ligne_dest++;
                int src_index = mat_virt.get_tab1()(i_ligne) - 1; //!< fortran->c
                for (int i = 0; i < count; i++, src_index++, dest_index++)
                  {
// mat_virt contient des indices fortran relatifs au debut de la partie virtuelle,
// on transform en indice C, relatif au vecteur complet
                    int j = mat_virt.get_tab2()(src_index) + sz - 1;
                    int rj = renum_[j];
// on stocke dans tmp_mat_virt des indices de colonnes relatifs au vecteur complet
// (pas seulement la partie virtuelle)
                    tmp_mat_virt_.get_set_tab2()[dest_index] = rj + 1; //!< indice fortran
                  }
              }
          }
// Fin de la derniere ligne:
        tmp_mat_virt_.get_set_tab1()[i_ligne_dest] = dest_index + 1; //!< index fortran
      }
      reinit_ = 1;
    }
  if (reinit_ < 2)
    {
      const Matrice_Bloc& mat_bloc = ref_cast(Matrice_Bloc, matrice);
      const Matrice_Morse_Sym& mat = ref_cast(Matrice_Morse_Sym, mat_bloc.get_bloc(0,0).valeur());
      const Matrice_Morse& mat_virt = ref_cast(Matrice_Morse, mat_bloc.get_bloc(0,1).valeur());
      if (!precond_diag_)
        {
          tmp_mat_.get_set_coeff().inject_array(mat.get_coeff());
          tmp_mat_virt_.get_set_coeff().inject_array(mat_virt.get_coeff());
        }
      else
        {
// calcul de D^(-1/2)
          exit();
// calcul du produit D^(-1/2) * A * D^(-1/2)
        }
      reinit_ = 2;
    }
  if (!precond_diag_)
    {
      tmp_solution_.inject_array(solution, tmp_solution_.size());
      resu_.inject_array(secmem, resu_.size_array());
    }
  else
    {
      exit();
    }
}
References TRUSTArray< _TYPE_ >::addr(), Cerr, MD_Vector_tools::creer_md_vect_renum_auto(), Process::exit(), finl, Matrice_Bloc::get_bloc(), Matrice_Morse::get_coeff(), TRUSTVect< _TYPE_ >::get_md_vector(), MD_Vector_base::get_nb_items_reels(), MD_Vector_base::get_nb_items_tot(), Matrice_Morse::get_set_coeff(), Matrice_SuperMorse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_SuperMorse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_SuperMorse::get_set_tab2(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), TRUSTArray< _TYPE_ >::inject_array(), Process::Journal(), Matrice_SuperMorse::lignes_non_vides_, TRUSTVect< _TYPE_ >::line_size(), Array_base::NOCOPY_NOINIT, precond_diag_, ref_cast, TRUSTVect< _TYPE_ >::ref_data(), TRUSTArray< _TYPE_ >::ref_data(), reinit_, renum_, TRUSTVect< _TYPE_ >::reset(), residu_, TRUSTVect< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), resu_, TRUSTVect< _TYPE_ >::set_md_vector(), Matrice_Morse::set_nb_columns(), TRUSTVect< _TYPE_ >::size(), TRUSTArray< _TYPE_ >::size_array(), tmp_data_block_, tmp_mat_, tmp_mat_virt_, tmp_p_, tmp_p_avec_items_virt_, tmp_solution_, Deriv_Matrice_Base::valeur(), and MD_Vector::valeur().
Referenced by resoudre_().
printOn()
Sortie & Solv_GCP::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 39 of file Solv_GCP.cpp.
{
  s<<" { seuil " << seuil_ ;
  if (le_precond_.non_nul())
    s<<" precond " <<le_precond_;
  else
    s<<" precond_nul ";
  if (limpr()==1) s<<" impr ";
  if (limpr()==-1) s<<" quiet ";
  if (save_matrice_) s<<" save_matrice ";
  if (nb_it_max_!=-1) s<<" nb_it_max "<<nb_it_max_;
  s<<" } ";
  return s ;
}
References le_precond_, SolveurSys_base::limpr(), nb_it_max_, O_U_Ptr::non_nul(), SolveurSys_base::save_matrice_, and solv_iteratif::seuil_.
readOn()
Entree & Solv_GCP::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 55 of file Solv_GCP.cpp.
{
  int precond_nul;
  int impr,quiet;
  Param param((*this).que_suis_je());
  param.ajouter("seuil",&seuil_,Param::REQUIRED);
  param.ajouter("nb_it_max",&nb_it_max_);
  param.ajouter_flag("impr",&impr);
  param.ajouter_flag("quiet",&quiet);
  param.ajouter_flag("save_matrice|save_matrix",&save_matrice_);
  param.ajouter("precond",&le_precond_);
  param.ajouter_flag("precond_nul",&precond_nul);
  param.ajouter_flag("precond_diagonal", &precond_diag_);
  param.ajouter_flag("optimized", &optimized_);
  param.lire_avec_accolades_depuis(is);
// Obligation de definir un precond
  if (!le_precond_.non_nul() && precond_nul==0 && precond_diag_==0)
    {
      Cerr << "You forgot to define a preconditionner with the keyword precond." << finl;
      Cerr << "If you don't want a preconditionner, add for the solver definition:" << finl;
      Cerr << "precond_nul" << finl;
      Process::exit();
    }
  if (precond_nul)
    {
      le_precond_.detach();
    }
  assert(seuil_>0);
  fixer_limpr(impr);
  if (quiet)
    fixer_limpr(-1);
  return is;
}
References Param::ajouter(), Param::ajouter_flag(), Cerr, Deriv_::detach(), Process::exit(), finl, SolveurSys_base::fixer_limpr(), le_precond_, Param::lire_avec_accolades_depuis(), nb_it_max_, O_U_Ptr::non_nul(), optimized_, precond_diag_, Param::REQUIRED, SolveurSys_base::save_matrice_, and solv_iteratif::seuil_.
reinit()
void Solv_GCP::reinit () override virtual
< Si reinit_ = 0, ne pas toucher.
Reimplemented from SolveurSys_base.
Definition at line 107 of file Solv_GCP.cpp.
{
  if (reinit_ > 1) //!< Si reinit_ = 0, ne pas toucher.
    reinit_ = 1;
  SolveurSys_base::reinit();
  if (le_precond_.non_nul())
    le_precond_.valeur().reinit();
}
References le_precond_, O_U_Ptr::non_nul(), SolveurSys_base::reinit(), Precond_base::reinit(), reinit_, and Deriv_Precond_base::valeur().
resoudre_()
int Solv_GCP::resoudre_ (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution, int nmax) protected
< ne pas toucher a l'espace virtuel
Definition at line 396 of file Solv_GCP.cpp.
{
  const int n_items_reels = solution.size_reelle_ok() ? solution.size_reelle() : solution.size_totale();
  {
    const int nb_items_seq = solution.get_md_vector().valeur().nb_items_seq_tot();
    const int ls = secmem.line_size();
    const int nb_inco_tot = nb_items_seq * ls;
    nmax = std::max(nb_inco_tot, nmax);
  }
  const int avec_precond = le_precond_.non_nul();
  const int precond_requires_echange_espace_virtuel =
    avec_precond && (le_precond_.valeur().get_flag_updated_input());
  const int optimized = optimized_;
  if (optimized)
    {
      prepare_data(matrice, secmem, solution);
    }
  else
    {
      resu_.reset();
      residu_.reset();
      tmp_p_avec_items_virt_.reset();
      resu_.copy(solution, Array_base::NOCOPY_NOINIT);
      residu_.copy(solution, Array_base::NOCOPY_NOINIT);
      tmp_p_avec_items_virt_.copy(solution, Array_base::NOCOPY_NOINIT);
      tmp_p_.ref(tmp_p_avec_items_virt_);
      tmp_solution_.ref(solution);
      resu_.inject_array(secmem);
    }
  tmp_p_avec_items_virt_.inject_array(tmp_solution_, n_items_reels);
  tmp_p_avec_items_virt_.echange_espace_virtuel();
// On n'a pas besoin que residu ait son espace virtuel a jour
// En revanche, on a besoin de l'espace virtuel de tmp_p_...
  if (optimized)
    {
      tmp_mat_.multvect_(tmp_p_avec_items_virt_, residu_);
// calcul du produit, le produit scalaire n'est pas utilise:
      tmp_mat_virt_.ajouter_mult_vect_et_prodscal(tmp_p_avec_items_virt_, residu_);
    }
  else
    {
      matrice.multvect(tmp_p_avec_items_virt_, residu_);
    }
// ATTENTION: on suppose que secmem a ete copie dans resu_
  operator_sub(residu_, resu_, VECT_REAL_ITEMS); //!< ne pas toucher a l'espace virtuel
  if (avec_precond)
    {
      if (precond_requires_echange_espace_virtuel)
        residu_.echange_espace_virtuel();
      if (optimized)
        le_precond_.valeur().preconditionner(tmp_mat_, residu_, tmp_p_);
      else
        le_precond_.valeur().preconditionner(matrice, residu_, tmp_p_);
    }
  else
    {
      tmp_p_.inject_array(residu_, n_items_reels);
    }
  double dold = mp_prodscal(residu_, tmp_p_);
  operator_negate(tmp_p_, VECT_REAL_ITEMS);
  double norme = mp_norme_vect(residu_);
  double norme_b = mp_norme_vect(resu_);
  if (limpr()==1)
    {
      double norme_relative=(norme_b>DMINFLOAT?norme/(norme_b+DMINFLOAT):norme);
      Cout << "Norm of the residue: " << norme << " (" << norme_relative << ")" << finl;
    }
  int niter = 0;
  int nb_it_max=nmax;
  if (nb_it_max_>-1)
    nb_it_max=nb_it_max_;
  while ( ( norme > seuil_ ) && (niter++ < nmax) &&( niter<nb_it_max))
    {
// Precondition pour multvect
// (le seul echange espace virtuel de l'algo sauf si le precond en a besoin)
      tmp_p_avec_items_virt_.echange_espace_virtuel();
// En revanche, on n'a pas besoin de l'espace virtuel a jour de resu:
      double resu_scalaire_p_local;
      if (optimized)
        {
          resu_scalaire_p_local = tmp_mat_.multvect_et_prodscal(tmp_p_avec_items_virt_, resu_);
          resu_scalaire_p_local += tmp_mat_virt_.ajouter_mult_vect_et_prodscal(tmp_p_avec_items_virt_, resu_);
        }
      else
        {
          matrice.multvect(tmp_p_avec_items_virt_, resu_);
          resu_scalaire_p_local = local_prodscal(resu_, tmp_p_avec_items_virt_);
        }
      const double resu_scalaire_p = mp_sum(resu_scalaire_p_local);
      const double alfa = dold / resu_scalaire_p;
      ajoute_alpha_v(tmp_solution_, alfa, tmp_p_, VECT_REAL_ITEMS);
      double norme_residu_locale;
      if (optimized)
        {
          norme_residu_locale = ajoute_alpha_v_norme(residu_, alfa, resu_);
        }
      else
        {
          ajoute_alpha_v(residu_, alfa, resu_);
          norme_residu_locale = local_carre_norme_vect(residu_);
        }
      if(avec_precond)
        {
          if (precond_requires_echange_espace_virtuel)
            residu_.echange_espace_virtuel();
          if (optimized)
            le_precond_.valeur().preconditionner(tmp_mat_, residu_, resu_);
          else
            le_precond_.valeur().preconditionner(matrice, residu_, resu_);
          double residu_scalaire_resu = local_prodscal(residu_, resu_);
          norme = norme_residu_locale;
// optimisation: on calcule en une seule fois les deux sommes
          mpsum_multiple(residu_scalaire_resu, norme);
          assert(residu_scalaire_resu >= 0);
          multiply_sub(tmp_p_, resu_, residu_scalaire_resu / dold);
          dold = residu_scalaire_resu;
        }
      else
        {
          const double dnew = mp_carre_norme_vect(residu_);
          norme = mp_sum(norme_residu_locale);
          assert(dnew >= 0);
          multiply_sub(tmp_p_, residu_, dnew / dold);
          dold = dnew;
        }
      norme = sqrt(norme);
      if (limpr()==1)
        {
          Cout << norme << " ";
          if ((niter % 15) == 0) Cout << finl ;
        }
    }
  if ((nb_it_max_<0)&& (norme > seuil_))
    {
      Cerr << "No convergence after : " << niter << " iterations\n";
      Cerr << " Residue : "<< norme << "\n";
      Cerr << " threshold : "<< seuil_ << "\n";
      Cerr << "Change your data set." << finl;
      exit();
    }
  if (optimized)
    solution.inject_array(tmp_solution_, n_items_reels);
// The user wants a result with updated virtual space:
  if (get_flag_updated_result())
    solution.echange_espace_virtuel();
// On affiche quand meme le nombre d'iterations
  if (limpr()>-1)
    {
      double norme_relative=(norme_b>0?norme/(norme_b+DMINFLOAT):norme);
      Cout << finl;
      Cout << "Final residue: " << norme << " ( " << norme_relative << " )"<<finl;
    }
  return(niter);
}
References ajoute_alpha_v(), ajoute_alpha_v_norme(), Matrice_SuperMorse::ajouter_mult_vect_et_prodscal(), Cerr, TRUSTVect< _TYPE_ >::copy(), Cout, DMINFLOAT, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, Precond_base::get_flag_updated_input(), SolveurSys_base::get_flag_updated_result(), TRUSTVect< _TYPE_ >::get_md_vector(), TRUSTArray< _TYPE_ >::inject_array(), le_precond_, SolveurSys_base::limpr(), TRUSTVect< _TYPE_ >::line_size(), local_carre_norme_vect(), local_prodscal(), mp_carre_norme_vect(), mp_norme_vect(), mp_prodscal(), Process::mp_sum(), mpsum_multiple(), multiply_sub(), Matrice_Base::multvect(), Matrice_Base::multvect_(), Matrice_Morse_Sym::multvect_et_prodscal(), nb_it_max_, MD_Vector_base::nb_items_seq_tot(), Array_base::NOCOPY_NOINIT, O_U_Ptr::non_nul(), norme(), operator_negate(), operator_sub(), optimized_, Precond_base::preconditionner(), prepare_data(), TRUSTVect< _TYPE_ >::ref(), TRUSTVect< _TYPE_ >::reset(), residu_, resu_, solv_iteratif::seuil_, TRUSTVect< _TYPE_ >::size_reelle(), TRUSTVect< _TYPE_ >::size_reelle_ok(), TRUSTVect< _TYPE_ >::size_totale(), tmp_mat_, tmp_mat_virt_, tmp_p_, tmp_p_avec_items_virt_, tmp_solution_, MD_Vector::valeur(), Deriv_Precond_base::valeur(), and VECT_REAL_ITEMS.
Referenced by resoudre_systeme().
resoudre_systeme() [1/2]
int Solv_GCP::resoudre_systeme (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution) override virtual
Implements SolveurSys_base.
Definition at line 89 of file Solv_GCP.cpp.
{
  int n = resoudre_(matrice, secmem, solution, 100);
  return n;
}
References resoudre_().
Referenced by Op_Diff_RotRot::calculer_vorticite(), and Op_Diff_RotRot::tester().
resoudre_systeme() [2/2]
int Solv_GCP::resoudre_systeme (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution, int nmax) override virtual
Reimplemented from SolveurSys_base.
Definition at line 97 of file Solv_GCP.cpp.
{
  int n = resoudre_(matrice, secmem, solution, nmax);
  return n;
}
References resoudre_().
self_cast() [1/2]
const Solv_GCP & Solv_GCP::self_cast (const Objet_U & r) static
Definition at line 26 of file Solv_GCP.cpp.
self_cast() [2/2]
Solv_GCP & Solv_GCP::self_cast (Objet_U & r) static
Definition at line 26 of file Solv_GCP.cpp.
set_precond()
void Solv_GCP::set_precond (const Precond & pre) inline
Definition at line 90 of file Solv_GCP.h.
{
  le_precond_ = pre;
}
References le_precond_.
supporte_matrice_morse_sym()
int Solv_GCP::supporte_matrice_morse_sym () inline override virtual
Reimplemented from SolveurSys_base.
Definition at line 34 of file Solv_GCP.h.
  {
    return !le_precond_.non_nul() || le_precond_.supporte_matrice_morse_sym();
  };
References le_precond_, O_U_Ptr::non_nul(), and Precond::supporte_matrice_morse_sym().
taille_memoire()
unsigned Solv_GCP::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 26 of file Solv_GCP.cpp.
Member Data Documentation
info_obj
const Type_info Solv_GCP::info_obj static
Definition at line 26 of file Solv_GCP.h.
inv_sqrt_diag_
DoubleVect Solv_GCP::inv_sqrt_diag_ protected
Definition at line 85 of file Solv_GCP.h.
le_precond_
Precond Solv_GCP::le_precond_ protected
Definition at line 48 of file Solv_GCP.h.
Referenced by get_precond(), printOn(), readOn(), reinit(), resoudre_(), set_precond(), and supporte_matrice_morse_sym().
nb_it_max_
int Solv_GCP::nb_it_max_ protected
Definition at line 87 of file Solv_GCP.h.
Referenced by printOn(), readOn(), resoudre_(), and Solv_GCP().
optimized_
int Solv_GCP::optimized_ protected
Definition at line 47 of file Solv_GCP.h.
Referenced by readOn(), resoudre_(), and Solv_GCP().
precond_diag_
int Solv_GCP::precond_diag_ protected
Definition at line 57 of file Solv_GCP.h.
Referenced by prepare_data(), readOn(), and Solv_GCP().
reinit_
int Solv_GCP::reinit_ protected
0=> rien n'est pret 1=> memoire allouee, coeffs matrice a copier, 2=> ok
Definition at line 86 of file Solv_GCP.h.
Referenced by prepare_data(), reinit(), and Solv_GCP().
renum_
IntVect Solv_GCP::renum_ protected
Definition at line 80 of file Solv_GCP.h.
Referenced by prepare_data().
residu_
DoubleVect Solv_GCP::residu_ protected
Definition at line 63 of file Solv_GCP.h.
Referenced by prepare_data(), and resoudre_().
resu_
DoubleVect Solv_GCP::resu_ protected
Definition at line 62 of file Solv_GCP.h.
Referenced by prepare_data(), and resoudre_().
tmp_data_block_
ArrOfDouble Solv_GCP::tmp_data_block_ protected
Definition at line 77 of file Solv_GCP.h.
Referenced by prepare_data().
tmp_mat_
Matrice_Morse_Sym Solv_GCP::tmp_mat_ protected
Definition at line 71 of file Solv_GCP.h.
Referenced by prepare_data(), and resoudre_().
tmp_mat_virt_
Matrice_SuperMorse Solv_GCP::tmp_mat_virt_ protected
Definition at line 73 of file Solv_GCP.h.
Referenced by prepare_data(), and resoudre_().
tmp_p_
DoubleVect Solv_GCP::tmp_p_ protected
Definition at line 68 of file Solv_GCP.h.
Referenced by prepare_data(), and resoudre_().
tmp_p_avec_items_virt_
DoubleVect Solv_GCP::tmp_p_avec_items_virt_ protected
Definition at line 59 of file Solv_GCP.h.
Referenced by prepare_data(), and resoudre_().
tmp_solution_
DoubleVect Solv_GCP::tmp_solution_ protected
Definition at line 69 of file Solv_GCP.h.
Referenced by prepare_data(), and resoudre_().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/Solv_GCP.h
src/Kernel/Math/SolvSys/Solv_GCP.cpp