TRUST: Eval_centre4_VDF_Face Class Reference
Eval_centre4_VDF_Face Class Reference
class Eval_centre4_VDF_Face
Evaluateur VDF pour la convection
Le champ convecte est un Champ_Face
Schema de convection centre4 (sur 4 points)
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
#include <Eval_centre4_VDF_Face.h>
Public Member Functions
Eval_centre4_VDF_Face ()
int calculer_arete_fluide () const
int calculer_arete_paroi () const
int calculer_arete_paroi_fluide () const
int calculer_arete_symetrie () const
int calculer_arete_interne () const
int calculer_arete_mixte () const
int calculer_fa7_sortie_libre () const
int calculer_arete_periodicite () const
int calculer_arete_symetrie_paroi () const
int calculer_arete_symetrie_fluide () const
double flux_fa7_sortie_libre (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double flux_fa7_elem (const DoubleTab &, int, int, int) const
double flux_arete_interne (const DoubleTab &, int, int, int, int) const
double flux_arete_mixte (const DoubleTab &, int, int, int, int) const
double flux_arete_paroi (const DoubleTab &, int, int, int, int) const
double flux_arete_symetrie (const DoubleTab &, int, int, int, int) const
void flux_arete_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_paroi_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_periodicite (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_symetrie_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
double flux_arete_symetrie_paroi (const DoubleTab &, int, int, int, int) const
void flux_fa7_elem (const DoubleTab &, int, int, int, DoubleVect &flux) const
void flux_fa7_sortie_libre (const DoubleTab &, int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void flux_arete_interne (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_mixte (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_symetrie (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_paroi (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_paroi_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_periodicite (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_symetrie_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_symetrie_paroi (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
Private Member Functions
double dist_face (int n1, int n2, int k) const
double dist_face_period (int n1, int n2, int k) const
double dist_elem_period (int n1, int n2, int k) const
int face_amont_conj (int, int, int) const
int face_amont_princ (int, int) const
double dim_elem (int n1, int k) const
Detailed Description
class Eval_centre4_VDF_Face
Evaluateur VDF pour la convection
Le champ convecte est un Champ_Face
Schema de convection centre4 (sur 4 points)
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
See also:
Eval_Conv_VDF
Definition at line 45 of file Eval_centre4_VDF_Face.h.
Constructor & Destructor Documentation
Eval_centre4_VDF_Face::Eval_centre4_VDF_Face () [inline]
Definition at line 132 of file Eval_centre4_VDF_Face.h.
{
}
Member Function Documentation
int Eval_centre4_VDF_Face::calculer_arete_fluide () const [inline]
Definition at line 140 of file Eval_centre4_VDF_Face.h.
{
  return 1;
}
int Eval_centre4_VDF_Face::calculer_arete_interne () const [inline]
Definition at line 175 of file Eval_centre4_VDF_Face.h.
{
  return 1;
}
int Eval_centre4_VDF_Face::calculer_arete_mixte () const [inline]
Definition at line 183 of file Eval_centre4_VDF_Face.h.
{
  return 1;
}
int Eval_centre4_VDF_Face::calculer_arete_paroi () const [inline]
Definition at line 149 of file Eval_centre4_VDF_Face.h.
{
  return 0;
}
int Eval_centre4_VDF_Face::calculer_arete_paroi_fluide () const [inline]
Definition at line 158 of file Eval_centre4_VDF_Face.h.
{
  return 1;
}
int Eval_centre4_VDF_Face::calculer_arete_periodicite () const [inline]
Definition at line 199 of file Eval_centre4_VDF_Face.h.
{
  return 1;
}
int Eval_centre4_VDF_Face::calculer_arete_symetrie () const [inline]
Definition at line 167 of file Eval_centre4_VDF_Face.h.
{
  return 0;
}
int Eval_centre4_VDF_Face::calculer_arete_symetrie_fluide () const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 215 of file Eval_centre4_VDF_Face.h.
{
  return 1;
}
int Eval_centre4_VDF_Face::calculer_arete_symetrie_paroi () const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 207 of file Eval_centre4_VDF_Face.h.
{
  return 0;
}
int Eval_centre4_VDF_Face::calculer_fa7_sortie_libre () const [inline]
Definition at line 191 of file Eval_centre4_VDF_Face.h.
{
  return 1;
}
double Eval_centre4_VDF_Face::dim_elem (int n1, int k) const [inline, private]
Definition at line 122 of file Eval_centre4_VDF_Face.h.
References Evaluateur_VDF::la_zone.
Referenced by flux_fa7_elem().
  {
    return la_zone->dim_elem(n1,k);
  };
double Eval_centre4_VDF_Face::dist_elem_period (int n1, int n2, int k) const [inline, private]
Definition at line 116 of file Eval_centre4_VDF_Face.h.
References Evaluateur_VDF::la_zone.
  {
    return la_zone->dist_elem_period(n1,n2,k);
  };
double Eval_centre4_VDF_Face::dist_face (int n1, int n2, int k) const [inline, private]
Reimplemented from Evaluateur_VDF.
Definition at line 108 of file Eval_centre4_VDF_Face.h.
References Evaluateur_VDF::la_zone.
Referenced by flux_arete_interne().
  {
    return la_zone->dist_face(n1,n2,k);
  };
double Eval_centre4_VDF_Face::dist_face_period (int n1, int n2, int k) const [inline, private]
Reimplemented from Evaluateur_VDF.
Definition at line 112 of file Eval_centre4_VDF_Face.h.
References Evaluateur_VDF::la_zone.
Referenced by flux_arete_interne(), and flux_arete_periodicite().
  {
    return la_zone->dist_face_period(n1,n2,k);
  };
int Eval_centre4_VDF_Face::face_amont_conj (int num_face, int i, int k) const [inline, private]
Definition at line 236 of file Eval_centre4_VDF_Face.h.
References Evaluateur_VDF::la_zone.
Referenced by flux_arete_interne(), and flux_arete_periodicite().
{
  return la_zone->face_amont_conj(num_face, i, k);
}
int Eval_centre4_VDF_Face::face_amont_princ (int num_face, int i) const [inline, private]
Definition at line 241 of file Eval_centre4_VDF_Face.h.
References Evaluateur_VDF::la_zone.
Referenced by flux_fa7_elem().
{
  return la_zone->face_amont_princ(num_face, i);
}
void Eval_centre4_VDF_Face::flux_arete_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Definition at line 252 of file Eval_centre4_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double flux,psc;
  int ori;
// calcul de flux3:
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ( psc*signe >0)
    flux=inco[fac3]*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      ori =orientation(fac3);
      flux = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl)) * psc ;
    }
  flux3 = -flux;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*inco[fac2];
  flux1_2 = -flux;
}
void Eval_centre4_VDF_Face::flux_arete_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Definition at line 563 of file Eval_centre4_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<flux3.size(); k++)
      flux3(k) = -inco(fac3,k)*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,k,ori,la_zcl)) * psc ;
    }
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_centre4_VDF_Face::flux_arete_interne (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, DoubleVect & flux) const [inline]
< Schema centre 2
< Schema centre4
Definition at line 602 of file Eval_centre4_VDF_Face.h.
References calcul_g(), conv_centre(), dist_face(), dist_face_period(), Eval_Conv_VDF::dt_vitesse, face_amont_conj(), Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  int ncomp = flux.size();
  double psc = 0.25* (dt_vitesse[fac1]*porosite(fac1) + dt_vitesse[fac2]*porosite(fac2))
               * (surface(fac1) + surface(fac2));
  int ori = orientation(fac1);
  int num0_0 = face_amont_conj(fac3,ori,0);
  int num1_1 = face_amont_conj(fac4,ori,1);
  if  ( (num0_0 == -1) || (num1_1== -1) ) //!< Schema centre 2
    for (k=0; k<ncomp; k++)
      flux(k) = -psc*0.5*(inco(fac3,k)+inco(fac4,k));
  else   //!< Schema centre4
    {
      double dx = dist_face(fac3,fac4,ori);
      double dxam = dist_face_period(num0_0,fac3,ori);
      double dxav = dist_face_period(fac4,num1_1,ori);
      ArrOfDouble vit_0(ncomp);
      ArrOfDouble vit_0_0(ncomp);
      ArrOfDouble vit_1_1(ncomp);
      ArrOfDouble vit_1(ncomp);
      double g1,g2,g3,g4;
      calcul_g(dxam,dx,dxav,g1,g2,g3,g4);
      for (k=0; k<ncomp; k++)
        {
          vit_0(k) = inco(fac3,k);
          vit_0_0(k) = inco(num0_0,k);
          vit_1(k) = inco(fac4,k);
          vit_1_1(k)=inco(num1_1,k);
          flux(k) = -conv_centre(psc,vit_0_0(k),vit_0(k),vit_1(k),vit_1_1(k),g1,g2,g3,g4);
        }
    }
}
double Eval_centre4_VDF_Face::flux_arete_interne (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4) const [inline]
< Schema centre 2 (pas assez de faces)
< Schema Centre
< Inutile de prendre dist_face_period car fac3 et fac4 ne peuvent etre periodiques (arete interne)
Definition at line 291 of file Eval_centre4_VDF_Face.h.
References calcul_g(), conv_centre(), dist_face(), dist_face_period(), Eval_Conv_VDF::dt_vitesse, face_amont_conj(), Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  double psc = 0.25* (dt_vitesse[fac1]*porosite(fac1) + dt_vitesse[fac2]*porosite(fac2))
               * (surface(fac1) + surface(fac2));
  int ori = orientation(fac1);
  int num0_0 = face_amont_conj(fac3,ori,0);
  int num1_1 = face_amont_conj(fac4,ori,1);
  if ( (num0_0 == -1)||(num1_1== -1) )  //!< Schema centre 2 (pas assez de faces)
    flux = 0.5*(inco[fac3]+inco[fac4])*psc ;
  else  //!< Schema Centre
    {
      double dx = dist_face(fac3,fac4,ori); //!< Inutile de prendre dist_face_period car fac3 et fac4 ne peuvent etre periodiques (arete interne)
      double dxam = dist_face_period(num0_0,fac3,ori);
      double dxav = dist_face_period(fac4,num1_1,ori);
      double vit_0 = inco[fac3];
      double vit_0_0 = inco[num0_0];
      double vit_1 = inco[fac4];
      double vit_1_1 = inco[num1_1];
      double g1,g2,g3,g4;
      calcul_g(dxam,dx,dxav,g1,g2,g3,g4);
      flux = conv_centre(psc,vit_0_0,vit_0,vit_1,vit_1_1,g1,g2,g3,g4);
    }
  return -flux;
}
void Eval_centre4_VDF_Face::flux_arete_mixte (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, DoubleVect & flux) const [inline]
Definition at line 647 of file Eval_centre4_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] )  *
               ( surface[fac1] + surface[fac2] );
  if (psc>0)
    for (k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(fac3,k);
  else
    for (k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(fac4,k);
}
double Eval_centre4_VDF_Face::flux_arete_mixte (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4) const [inline]
Definition at line 325 of file Eval_centre4_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] )  *
               ( surface[fac1] + surface[fac2] );
  if (psc>0)
    flux = psc*inco[fac3];
  else
    flux = psc*inco[fac4];
  return -flux;
}
void Eval_centre4_VDF_Face::flux_arete_paroi (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 668 of file Eval_centre4_VDF_Face.h.
{
  ;
}
double Eval_centre4_VDF_Face::flux_arete_paroi (const DoubleTab & , int , int , int , int) const [inline]
Definition at line 345 of file Eval_centre4_VDF_Face.h.
{
  return 0;
}
void Eval_centre4_VDF_Face::flux_arete_paroi_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Definition at line 354 of file Eval_centre4_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double flux,psc;
  int ori;
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    flux=inco[fac3]*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      ori =orientation(fac3);
      flux = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1, ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2, ori,la_zcl))* psc ;
    }
  flux3 = -flux;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*inco[fac2];
  flux1_2 = -flux;
}
void Eval_centre4_VDF_Face::flux_arete_paroi_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Definition at line 678 of file Eval_centre4_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<flux3.size(); k++)
      flux3(k) = -inco(fac3,k)*psc;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,k,ori,la_zcl))* psc ;
    }
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_centre4_VDF_Face::flux_arete_periodicite (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, DoubleVect & flux3_4, DoubleVect & flux1_2) const [inline]
< Schema centre 2
< Schema centre2
Definition at line 716 of file Eval_centre4_VDF_Face.h.
References calcul_g(), conv_centre(), dist_face_period(), Eval_Conv_VDF::dt_vitesse, face_amont_conj(), Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
// On calcule le flux convectif entre les volumes de controle associes a fac3 et fac4:
  int k;
  int ncomp = flux3_4.size();
  double psc = 0.25* (dt_vitesse[fac1]*porosite(fac1) + dt_vitesse[fac2]*porosite(fac2))
               * (surface(fac1) + surface(fac2));
  int ori = orientation(fac1);
  int num0_0 = face_amont_conj(fac3,ori,0);
  int num1_1 = face_amont_conj(fac4,ori,1);
  if  ( (num0_0 == -1) || (num1_1== -1) )                           //!< Schema centre 2
    for (k=0; k<ncomp; k++)
      flux3_4(k) = -psc*0.5*(inco(fac3,k)+inco(fac4,k));
  else
    {
// Schema centre4
      double dx = dist_face_period(fac3,fac4,ori);
      double dxam = dist_face_period(num0_0,fac3,ori);
      double dxav = dist_face_period(fac4,num1_1,ori);
      ArrOfDouble vit_0(ncomp);
      ArrOfDouble vit_0_0(ncomp);
      ArrOfDouble vit_1_1(ncomp);
      ArrOfDouble vit_1(ncomp);
      double g1,g2,g3,g4;
      calcul_g(dxam,dx,dxav,g1,g2,g3,g4);
      for (k=0; k<ncomp; k++)
        {
          vit_0(k) = inco(fac3,k);
          vit_0_0(k) = inco(num0_0,k);
          vit_1(k) = inco(fac4,k);
          vit_1_1(k)=inco(num1_1,k);
          flux3_4(k) = -conv_centre(psc,vit_0_0(k),vit_0(k),vit_1(k),vit_1_1(k),g1,g2,g3,g4);
        }
    }
// On calcule le flux convectif entre les volumes de controle associes a fac1 et fac2:
  psc = 0.25* (dt_vitesse[fac3]*porosite(fac3) + dt_vitesse[fac4]*porosite(fac4))
        * (surface(fac3) + surface(fac4));
  ori = orientation(fac3);
  num0_0 = face_amont_conj(fac1,ori,0);
  num1_1 = face_amont_conj(fac2,ori,1);
  if  ( (num0_0 == -1) || (num1_1== -1) )                           //!< Schema centre2
    for (k=0; k<ncomp; k++)
      flux1_2(k) = -psc*0.5*(inco(fac1,k)+inco(fac2,k));
  else
    {
// Schema centre4
      double dx = dist_face_period(fac1,fac2,ori);
      double dxam = dist_face_period(num0_0,fac1,ori);
      double dxav = dist_face_period(fac2,num1_1,ori);
      ArrOfDouble vit_0(ncomp);
      ArrOfDouble vit_0_0(ncomp);
      ArrOfDouble vit_1_1(ncomp);
      ArrOfDouble vit_1(ncomp);
      double g1,g2,g3,g4;
      calcul_g(dxam,dx,dxav,g1,g2,g3,g4);
      for (k=0; k<ncomp; k++)
        {
          vit_0(k) = inco(fac1,k);
          vit_0_0(k) = inco(num0_0,k);
          vit_1(k) = inco(fac2,k);
          vit_1_1(k)=inco(num1_1,k);
          flux1_2(k) = -conv_centre(psc,vit_0_0(k),vit_0(k),vit_1(k),vit_1_1(k),g1,g2,g3,g4);
        }
    }
}
void Eval_centre4_VDF_Face::flux_arete_periodicite (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, double & flux3_4, double & flux1_2) const [inline]
< Schema centre 2 (pas assez de faces)
< Schema Centre
< Schema centre 2 (pas assez de faces)
< Schema Centre
Definition at line 392 of file Eval_centre4_VDF_Face.h.
References calcul_g(), conv_centre(), dist_face_period(), Eval_Conv_VDF::dt_vitesse, face_amont_conj(), Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
// On calcule le flux convectif entre les volumes de controle associes a fac3 et fac4:
  double psc = 0.25* (dt_vitesse[fac1]*porosite(fac1) + dt_vitesse[fac2]*porosite(fac2))
               * (surface(fac1) + surface(fac2));
  int ori = orientation(fac1);
  int num0_0 = face_amont_conj(fac3,ori,0);
  int num1_1 = face_amont_conj(fac4,ori,1);
  if ( (num0_0 == -1)||(num1_1== -1) )  //!< Schema centre 2 (pas assez de faces)
    flux3_4 = -psc*0.5*(inco[fac3]+inco[fac4]);
  else                                                             //!< Schema Centre
    {
      double dx = dist_face_period(fac3,fac4,ori);
      double dxam = dist_face_period(num0_0,fac3,ori);
      double dxav = dist_face_period(fac4,num1_1,ori);
      double vit_0 = inco[fac3];
      double vit_0_0 = inco[num0_0];
      double vit_1 = inco[fac4];
      double vit_1_1 = inco[num1_1];
      double g1,g2,g3,g4;
      calcul_g(dxam,dx,dxav,g1,g2,g3,g4);
      flux3_4 = -conv_centre(psc,vit_0_0,vit_0,vit_1,vit_1_1,g1,g2,g3,g4);
    }
// On calcule le flux convectif entre les volumes de controle associes a fac1 et fac2:
  psc = 0.25* (dt_vitesse[fac3]*porosite(fac3) + dt_vitesse[fac4]*porosite(fac4))
        * (surface(fac3) + surface(fac4));
  ori = orientation(fac3);
  num0_0 = face_amont_conj(fac1,ori,0);
  num1_1 = face_amont_conj(fac2,ori,1);
  if ( (num0_0 == -1)||(num1_1== -1) )  //!< Schema centre 2 (pas assez de faces)
    flux1_2 = -psc*0.5*(inco[fac1]+inco[fac2]);
  else                                                             //!< Schema Centre
    {
      double dx = dist_face_period(fac1,fac2,ori);
      double dxam = dist_face_period(num0_0,fac1,ori);
      double dxav = dist_face_period(fac2,num1_1,ori);
      double vit_0 = inco[fac1];
      double vit_0_0 = inco[num0_0];
      double vit_1 = inco[fac2];
      double vit_1_1 = inco[num1_1];
      double g1,g2,g3,g4;
      calcul_g(dxam,dx,dxav,g1,g2,g3,g4);
      flux1_2 = -conv_centre(psc,vit_0_0,vit_0,vit_1,vit_1_1,g1,g2,g3,g4);
    }
}
double Eval_centre4_VDF_Face::flux_arete_symetrie (const DoubleTab & , int , int , int , int) const [inline]
Definition at line 449 of file Eval_centre4_VDF_Face.h.
{
  return 0;
}
void Eval_centre4_VDF_Face::flux_arete_symetrie (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 795 of file Eval_centre4_VDF_Face.h.
{
  ;
}
void Eval_centre4_VDF_Face::flux_arete_symetrie_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 870 of file Eval_centre4_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<flux3.size(); k++)
      flux3(k) = -inco(fac3,k)*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,k,ori,la_zcl)) * psc ;
    }
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_centre4_VDF_Face::flux_arete_symetrie_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 510 of file Eval_centre4_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord_sym(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double flux,psc;
// Calcul de flux3:
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    flux=inco[fac3]*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      flux = 0.5*(Champ_Face_get_val_imp_face_bord_sym(inco,inconnue->temps(),rang1,ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord_sym(inco,inconnue->temps(),rang2,ori,la_zcl))* psc ;
    }
  flux3 =  -flux;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*0.5*(inco[fac1]+inco[fac2]);
  flux1_2 = -flux;
}
double Eval_centre4_VDF_Face::flux_arete_symetrie_paroi (const DoubleTab & , int , int , int , int) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 553 of file Eval_centre4_VDF_Face.h.
{
  return 0;
}
void Eval_centre4_VDF_Face::flux_arete_symetrie_paroi (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 908 of file Eval_centre4_VDF_Face.h.
{
  ;
}
double Eval_centre4_VDF_Face::flux_fa7_elem (const DoubleTab & inco, int num_elem, int fac1, int fac2) const [inline]
< Schema centre 2
< Schema centre
Definition at line 458 of file Eval_centre4_VDF_Face.h.
References calcul_g(), conv_centre(), dim_elem(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, face_amont_princ(), Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  int num0_0 = face_amont_princ(fac1,0);
  int num1_1 = face_amont_princ(fac2,1);
  double psc = 0.25 * (dt_vitesse[fac1]+dt_vitesse[fac2])*(surface(fac1)+surface(fac2));
  if  ( (num0_0 == -1) || (num1_1== -1) )       //!< Schema centre 2
    flux = psc * 0.5*(inco[fac1]*porosite[fac1]+inco[fac2]*porosite[fac2]);
  else                                                                    //!< Schema centre
    {
      int ori=orientation(fac1);
      double dx = dim_elem(num_elem,ori);
      double dxam = dim_elem(elem_(fac1,0),ori);
      double dxav = dim_elem(elem_(fac2,1),ori);
      double vit_0 = inco[fac1]*porosite(fac1);
      double vit_0_0 = inco[num0_0]*porosite(num0_0);
      double vit_1 = inco[fac2]*porosite(fac2);
      double vit_1_1 = inco[num1_1]*porosite(num1_1);
      double g1,g2,g3,g4;
      calcul_g(dxam,dx,dxav,g1,g2,g3,g4);
      flux = conv_centre(psc,vit_0_0,vit_0,vit_1,vit_1_1,g1,g2,g3,g4);
    }
  return -flux;
}
void Eval_centre4_VDF_Face::flux_fa7_elem (const DoubleTab & inco, int num_elem, int fac1, int fac2, DoubleVect & flux) const [inline]
< Schema centre2
< Schema centre4
Definition at line 805 of file Eval_centre4_VDF_Face.h.
References calcul_g(), conv_centre(), dim_elem(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, face_amont_princ(), Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  int ncomp = flux.size();
  int ori = orientation(fac1);
  int num0_0 = face_amont_princ(fac1,0);
  int num1_1 = face_amont_princ(fac2,1);
  double psc = 0.25* (dt_vitesse[fac1]*porosite(fac1) + dt_vitesse[fac2]*porosite(fac2))
               * (surface(fac1) + surface(fac2));
  if ( (num0_0 == -1) || (num1_1== -1) ) //!< Schema centre2
    for (k=0; k<ncomp; k++)
      flux(k) = -psc*0.5*(inco(fac1,k)*porosite[fac1]+inco(fac2,k)*porosite[fac2]);
  else       //!< Schema centre4
    {
      double dx = dim_elem(num_elem,ori);
      double dxam = dim_elem(elem_(fac1,0),ori);
      double dxav = dim_elem(elem_(fac2,1),ori);
      ArrOfDouble vit_0(ncomp);
      ArrOfDouble vit_0_0(ncomp);
      ArrOfDouble vit_1_1(ncomp);
      ArrOfDouble vit_1(ncomp);
      double g1,g2,g3,g4;
      calcul_g(dxam,dx,dxav,g1,g2,g3,g4);
      for (k=0; k<ncomp; k++)
        {
          vit_0(k) = inco(fac1,k)* porosite(fac1);
          vit_0_0(k) = inco(num0_0,k)*porosite(num0_0);
          vit_1(k) = inco(fac2,k)*porosite(fac2);
          vit_1_1(k)=inco(num1_1,k)*porosite(num1_1);
          flux(k) = -conv_centre(psc,vit_0_0(k),vit_0(k),vit_1(k),vit_1_1(k),g1,g2,g3,g4);
        }
    }
}
double Eval_centre4_VDF_Face::flux_fa7_sortie_libre (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1) const [inline]
< (elem2 != -1)
Definition at line 487 of file Eval_centre4_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::orientation, Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  double flux;
  double psc = dt_vitesse[face]*surface(face);
  int elem1 = elem_(face,0);
  if (elem1 != -1)
    if (psc > 0)
      flux = psc*inco[face];
    else
      flux = psc*la_cl.val_ext(face-num1,orientation(face));
  else //!< (elem2 != -1)
    if (psc < 0)
      flux = psc*inco[face];
    else
      flux = psc*la_cl.val_ext(face-num1,orientation(face));
  return -flux;
}
void Eval_centre4_VDF_Face::flux_fa7_sortie_libre (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const [inline]
< (elem2 != -1)
Definition at line 844 of file Eval_centre4_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, DoubleVect::size(), Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  int k;
  double psc = dt_vitesse[face]*surface(face);
  int elem1 = elem_(face,0);
  if (elem1 != -1)
    if (psc > 0)
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*inco(face,k);
    else
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*la_cl.val_ext(face-num1,k);
  else //!< (elem2 != -1)
    if (psc < 0)
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*inco(face,k);
    else
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*la_cl.val_ext(face-num1,k);
}
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs/Eval_centre4_VDF_Face.h