TRUST: DoubleVect Class Reference
DoubleVect Class Reference
#include <DoubleVect.h>
Public Member Functions
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleVect ()
DoubleVect (int n)
construction d'un vecteur de taille n.
Les elements du vecteur sont initialises a zero par defaut.
Pour ne pas initialiser les valeurs, utiliser ceci:
DoubleVect toto;
toto.resize(n, NOCOPY_NOINIT);
DoubleVect (const DoubleVect &)
Constructeur par copie. Il s'agit d'un "deep copy"
voir ArrOfDouble::ArrOfDouble(const ArrOfDouble &)
Remarque: il n'y a pas de constructeur par copie a partir de ArrOfDouble
Ceci est volontaire, sinon on risque de grosses pertes de performances
par creation implicite d'objets, difficile a trouver.
(exemple: appel d'une methode toto(const IntVect &) avec un ArrOfInt
produit une copie du tableau !)
Utiliser copy() pour copier un ArrOfDouble dans un DoubleVect.
~DoubleVect ()
virtual void reset ()
met l'objet dans l'etat obtenu par le constructeur par defaut.
(voir ArrOfDouble::reset())
virtual void detach_vect ()
detach the vector.
DoubleVect & operator= (const DoubleVect &)
copie la structure et les valeurs du tableau v dans *this avec ArrOfDouble::operator=()
(attention, si le tableau est de type ref_data ou ref, restrictions et cas particuliers !!!)
Attention: si on ne veut pas copier les structures paralleles, utiliser inject_array()
DoubleVect & operator= (double)
idem que ArrOfDouble::operator=(double)
virtual void ref (const DoubleVect &)
detache le tableau et l'attache a v (sauf si v==*this, ne fait rien)
Fait pointer le tableau sur la meme zone de memoire que v et copie le MD_Vector
(utilise ArrOfDouble::attach_array())
Attention, il devient alors interdit de resizer le tableau v ainsi que *this
Methode virtuelle reimplementee dans DoubleTab
virtual void ref_data (double *ptr, int new_size)
voir ArrOfDouble::ref_data().
(cree un tableau sans structure parallele)
virtual void ref_array (ArrOfDouble &, int start=0, int sz=-1)
voir ArrOfDouble::ref_array().
(cree un tableau sans structure parallele)
void resize (int, Array_base::Resize_Options opt=COPY_INIT)
Change la taille du vecteur (identique a resize_array()
pour le traitement des anciennes valeurs et de nouvelles cases).
Attention: Cette methode n'est pas virtuelle, et afin d'eviter d'amener
un DoubleTab dans un etat invalide, l'appel est interdit si l'objet
est de ce type. Dans ce cas, voir resize_tab.
virtual void resize_tab (int n, Array_base::Resize_Options opt=COPY_INIT)
methode virtuelle identique a resize_array(), permet de traiter
de facon generique les ArrOf, Vect et Tab.
Cree un tableau sequentiel...
Si l'objet est de type DoubleVect, appel a resize(n)
Prerequis: voir resize()
void copy (const ArrOfDouble &, Array_base::Resize_Options opt=COPY_INIT)
copie de la structure et des valeurs (si opt==COPY_INIT) du tableau v.
Attention, v doit vraiment etre de type ArrOfDouble, pas d'un type derive
(sinon ambiguite: faut-il copier ou pas le MD_Vector ?)
void copy (const DoubleVect &, Array_base::Resize_Options opt=COPY_INIT)
copie de la structure du vecteur v et des valeurs si opt==COPY_INIT.
double local_max_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
double local_min_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
double local_max_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
double local_min_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
double mp_max_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
double mp_min_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
double mp_max_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
double mp_min_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
double mp_norme_vect () const
void operator+= (const DoubleVect &)
void operator+= (const double)
ajoute la meme valeur a toutes les cases du tableau
void operator-= (const DoubleVect &)
void operator-= (const double)
soustrait la meme valeur a toutes les cases
void operator*= (const DoubleVect &)
void operator*= (const double)
muliplie toutes les cases par dy
void operator/= (const DoubleVect &)
void operator/= (const double)
divise toutes les cases par dy
void abs (Mp_vect_options opt=VECT_ALL_ITEMS)
void carre (Mp_vect_options opt=VECT_ALL_ITEMS)
void racine_carree (Mp_vect_options opt=VECT_ALL_ITEMS)
void ajoute (double alpha, const DoubleVect &y, Mp_vect_options opt=VECT_ALL_ITEMS)
x+=alpha*y
void ajoute_sans_ech_esp_virt (double alpha, const DoubleVect &y, Mp_vect_options opt=VECT_REAL_ITEMS)
x+=alpha*y sans echange_espace_virtuel
void ajoute_produit_scalaire (double alpha, const DoubleVect &, const DoubleVect &, Mp_vect_options opt=VECT_ALL_ITEMS)
z+=alpha*x*y;
void ajoute_carre (double alpha, const DoubleVect &y, Mp_vect_options opt=VECT_ALL_ITEMS)
int size () const
Identique a size_reelle()
int size_totale () const
Identique a size_array()
int size_reelle () const
Taille de l'espace "reel" du vecteur.
(si md_vector_ est nul, cette valeur est identique a size_array(),
sinon, soit elle est egale a md_vector_....get_nb_items(),
soit l'appel est invalide (en particulier si les items reels ne
sont pas regroupes en debut de tableau)
On peut interroger le vecteur pour savoir si size_reelle() est valide avec size_reelle_ok()
int size_reelle_ok () const
int line_size () const
virtual void echange_espace_virtuel ()
virtual const MD_Vector & get_md_vector () const
virtual void set_md_vector (const MD_Vector &)
associe le md_vector au vecteur et initialise l'attribut size_reelle_
(voir methode size_reelle())
Si md_vector est nul, detache simplement le md_vector existant.
virtual void jump (Entree &)
virtual void lit (Entree &, int resize_and_read=1)
lecture d'un tableau pour reprise de calcul. On lit les valeurs "raw".
Attention, si le tableau n'est pas vide, il doit deja avoir la bonne
taille et la bonne structure, sinon erreur !
Parameter resize_and_read if the array is sized AND read (by default, yes)
virtual void ecrit (Sortie &) const
ecriture des valeurs du tableau "raw" sans structure parallele
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static DoubleVect & self_cast (Objet_U &)
static const DoubleVect & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture d'un vecteur sequentiel (sans descripteur parallele)
Pour l'instant: erreur si presence d'un md_vector_ (sinon quoi faire ?)
Pour les vecteurs paralleles, utiliser une methode de sauvegarde/reprise.
virtual Entree & readOn (Entree &)
Lecture d'un vecteur sequentiel (comme un ArrOfDouble)
Attention: appel invalide si le vecteur a un MD_Vector non nul.
(pour les vecteurs paralleles, utiliser une methode de sauvegarde/reprise)
void set_line_size_ (int n)
change l'attribut line_size_ du tableau avec n >= 1
n == 0 est autorise uniquement si size_array_ == 0
void resize_vect_ (int n, Array_base::Resize_Options opt=COPY_INIT)
Methode interne de resize (appellee par DoubleTab::resize(...))
sans precondition sur le type de l'objet.
void copy_ (const DoubleVect &v, Array_base::Resize_Options opt=COPY_INIT)
methode protegee appelable depuis une classe derivee<br>(pas de precondition sur le type derive de *this)
void attach_vect (const DoubleVect &v, int start, int size=-1)
Private Attributes
MD_Vector md_vector_
int size_reelle_
int line_size_
Detailed Description
Definition at line 38 of file DoubleVect.h.
Constructor & Destructor Documentation
DoubleVect::DoubleVect () [inline]
Definition at line 42 of file DoubleVect.h.
: size_reelle_(0), line_size_(1) {};
DoubleVect::DoubleVect (int n)
construction d'un vecteur de taille n.
Les elements du vecteur sont initialises a zero par defaut.
Pour ne pas initialiser les valeurs, utiliser ceci:
DoubleVect toto;
toto.resize(n, NOCOPY_NOINIT);
Definition at line 77 of file DoubleVect.cpp.
                            :
  ArrOfDouble(n),
  size_reelle_(n),
  line_size_(1)
{
}
DoubleVect::DoubleVect (const DoubleVect & v)
Constructeur par copie. Il s'agit d'un "deep copy"
voir ArrOfDouble::ArrOfDouble(const ArrOfDouble &)
Remarque: il n'y a pas de constructeur par copie a partir de ArrOfDouble
Ceci est volontaire, sinon on risque de grosses pertes de performances
par creation implicite d'objets, difficile a trouver.
(exemple: appel d'une methode toto(const IntVect &) avec un ArrOfInt
produit une copie du tableau !)
Utiliser copy() pour copier un ArrOfDouble dans un DoubleVect.
Definition at line 101 of file DoubleVect.cpp.
                                          :
  ArrOfDouble(v),
  md_vector_(v.md_vector_),
  size_reelle_(v.size_reelle_),
  line_size_(v.line_size_)
{
}
DoubleVect::~DoubleVect () [inline]
Definition at line 47 of file DoubleVect.h.
{};
Member Function Documentation
void DoubleVect::abs (Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 2297 of file DoubleVect.cpp.
References operator_abs().
Referenced by Op_Ecart_type::calculer_valeurs().
{
  operator_abs(*this, opt);
}
void DoubleVect::ajoute (double alpha, const DoubleVect & y, Mp_vect_options opt = VECT_ALL_ITEMS)
x+=alpha*y
Definition at line 2309 of file DoubleVect.cpp.
References ajoute_alpha_v(), echange_espace_virtuel(), and VECT_ALL_ITEMS.
Referenced by Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Operateur::ajouter(), Terme_Source_Canal_RANS_LES_VDF_Face::calculer_integrale_temporelle(), Equation_base::derivee_en_temps_conv(), RRK2::faire_un_pas_de_temps_eqn_base(), RK4_D3P::faire_un_pas_de_temps_eqn_base(), RK3::faire_un_pas_de_temps_eqn_base(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Source_Neutronique::faire_un_pas_de_temps_RK(), Equation_base::Gradient_conjugue_diff_impl(), Simple::iterer_NS(), Integrale_tps_Champ::mettre_a_jour_integrale(), PrecondA::preconditionner_(), Navier_Stokes_std::projeter(), Solv_GCP_NS::resoudre_systeme(), and Navier_Stokes_std::uzawa().
{
  ajoute_alpha_v(*this, alpha, y, opt);
  if (opt == VECT_ALL_ITEMS)
    echange_espace_virtuel();
}
void DoubleVect::ajoute_carre (double alpha, const DoubleVect & y, Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 2323 of file DoubleVect.cpp.
Referenced by Op_Ecart_type::calculer_valeurs(), and Integrale_tps_Champ::mettre_a_jour_integrale().
{
  ::ajoute_carre(*this, alpha, y, opt);
}
void DoubleVect::ajoute_produit_scalaire (double alpha, const DoubleVect & x, const DoubleVect & y, Mp_vect_options opt = VECT_ALL_ITEMS)
z+=alpha*x*y;
Definition at line 2319 of file DoubleVect.cpp.
{
  ::ajoute_produit_scalaire(*this, alpha, x, y, opt);
}
void DoubleVect::ajoute_sans_ech_esp_virt (double alpha, const DoubleVect & y, Mp_vect_options opt = VECT_REAL_ITEMS)
x+=alpha*y sans echange_espace_virtuel
Definition at line 2315 of file DoubleVect.cpp.
References ajoute_alpha_v().
Referenced by Operateur::ajouter(), Traitement_particulier_NS_Profils_VDF::calculer_integrale_temporelle(), Traitement_particulier_Solide_canal_VDF::calculer_integrales_temporelles(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_integrales_temporelles(), gradient_biconjugue(), and Fluide_Quasi_Compressible::secmembre_divU_Z().
{
  ajoute_alpha_v(*this, alpha, y, opt);
}
void DoubleVect::attach_vect (const DoubleVect & v, int start, int size = -1) [protected]
void DoubleVect::carre (Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 2301 of file DoubleVect.cpp.
{
  ::carre(*this, opt);
}
void DoubleVect::copy (const ArrOfDouble & v, Array_base::Resize_Options opt = COPY_INIT)
copie de la structure et des valeurs (si opt==COPY_INIT) du tableau v.
Attention, v doit vraiment etre de type ArrOfDouble, pas d'un type derive
(sinon ambiguite: faut-il copier ou pas le MD_Vector ?)
Definition at line 166 of file DoubleVect.cpp.
References ArrOfDouble::get_info(), get_info(), info(), ArrOfDouble::inject_array(), md_vector_, Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), resize(), and ArrOfDouble::size_array().
Referenced by Source_Dirac_VEF_Face::associer_pb(), Source_Dirac_VDF_Elem::associer_pb(), corriger(), EDO_Pression_th_VEF::masse_totale(), Matrice_Morse::operator=(), operator=(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), and Solv_GCP::resoudre_().
{
  assert(get_info() == DoubleVect::info());
  assert(v.get_info() == ArrOfDouble::info());
  assert(!md_vector_.non_nul());
  resize(v.size_array(), opt);
  if (opt != NOCOPY_NOINIT)
    inject_array(v);
}
void DoubleVect::copy (const DoubleVect & v, Array_base::Resize_Options opt = COPY_INIT)
copie de la structure du vecteur v et des valeurs si opt==COPY_INIT.
Definition at line 178 of file DoubleVect.cpp.
References copy_(), get_info(), info(), and ArrOfDouble::size_array().
{
  if (&v != this)
    {
// Interdiction de resizer si l'objet est d'un type derive de DoubleVect
// (sinon mauvaise dimension(0) !)
      assert(v.size_array() == size_array() || get_info() == DoubleVect::info());
      copy_(v, opt);
    }
}
void DoubleVect::copy_ (const DoubleVect & v, Array_base::Resize_Options opt = COPY_INIT) [protected]
methode protegee appelable depuis une classe derivee<br>(pas de precondition sur le type derive de *this)
< Il faut avoir fait le test avant ! Si le vecteur a deja une structure parallele, la copie n'est autorisee que si le vecteur source a la meme structure. Si ce n'est pas le cas, utiliser inject_array() pour copier uniquement les valeurs, ou faire d'abord reset() si on veut ecraser la structure.
< Pour le cas ou md_vector_ est nul et pas v.md_vector_
Definition at line 191 of file DoubleVect.cpp.
References ArrOfDouble::inject_array(), line_size_, md_vector_, Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), ArrOfDouble::resize_array_(), ArrOfDouble::size_array(), and size_reelle_.
Referenced by copy(), DoubleTab::copy(), and DoubleTab::operator=().
{
  assert(&v != this); //!< Il faut avoir fait le test avant ! Si le vecteur a deja une structure parallele, la copie n'est autorisee que si le vecteur source a la meme structure. Si ce n'est pas le cas, utiliser inject_array() pour copier uniquement les valeurs, ou faire d'abord reset() si on veut ecraser la structure.
//
//
//
  assert((!md_vector_.non_nul()) || (md_vector_ == v.md_vector_));
  resize_array_(v.size_array(), NOCOPY_NOINIT);
  if (opt != NOCOPY_NOINIT)
    inject_array(v);
  md_vector_ = v.md_vector_; //!< Pour le cas ou md_vector_ est nul et pas v.md_vector_
  size_reelle_ = v.size_reelle_;
  line_size_ = v.line_size_;
}
Objet_U * DoubleVect::cree_instance () [static]
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab, and DoubleTrav.
Definition at line 39 of file DoubleVect.cpp.
void DoubleVect::detach_vect () [virtual]
detach the vector.
Definition at line 120 of file DoubleVect.cpp.
References MD_Vector::detach(), and md_vector_.
{
  md_vector_.detach();
}
int DoubleVect::duplique () const [virtual]
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab, and DoubleTrav.
Definition at line 39 of file DoubleVect.cpp.
void DoubleVect::echange_espace_virtuel () [virtual]
Definition at line 277 of file DoubleVect.cpp.
Referenced by Champ_base::affecter(), Champ_P0_PolyMAC::affecter_(), Champ_P1_isoP1Bulle::affecter_(), Champ_Inc_base::affecter_(), Champ_Face_CoviMAC::affecter_(), ajoute(), Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Op_Grad_P1NC_to_P0::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Terme_Source_inc_VDF_Face::ajouter(), Terme_Source_inc_th_VDF_Face::ajouter(), Source_Generique_VDF_Face::ajouter(), Op_Grad_VDF_Face::ajouter(), Op_Grad_P0_to_Face::ajouter(), Source_WC_Chaleur::ajouter(), Op_Grad_PolyMAC_Face::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Source_Generique_P0_Elem::ajouter(), Op_Grad_EF::ajouter(), Op_Div_CoviMAC::ajouter(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), Matrice_Base::ajouter_multTab(), Matrice_Base::ajouter_multvect(), Matrice_Base::ajouter_multvectT(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim2(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim2(), Op_Conv_EF::ajouter_sous_cond_gen(), Masse_VDF_Elem::appliquer_impl(), Masse_PolyMAC_Elem::appliquer_impl(), Solveur_Masse_EF::appliquer_impl(), Masse_CoviMAC_Face::appliquer_impl(), Assembleur_P_VEF::assembler(), Assembleur_P_VEFPreP1B::assembler_mat(), Simpler_Base::assembler_matrice_pression_implicite(), Champ_P1NC::cal_rot_ordre1(), Op_Dift_standard_VEF_Face::calcul_divergence(), Terme_Source_inc_VDF_Face::calculer(), Terme_Source_inc_th_VDF_Face::calculer(), Terme_Source_Acceleration::calculer(), Op_Diff_P1NC_barprim::calculer(), Loi_Etat_Multi_GP_base::calculer_alpha(), Loi_Etat_GP_base::calculer_alpha(), Loi_Etat_base::calculer_alpha(), Champ_Tabule_Morceaux::calculer_champ_tabule_morceaux(), Simple::calculer_correction_en_vitesse(), Loi_Etat_Multi_GP_base::calculer_Cp(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_VDF_base::calculer_dt_local(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Zone_EF_axi::calculer_IPhi(), Zone_EF::calculer_IPhi(), Loi_Etat_Multi_GP_base::calculer_lambda(), Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_base::calculer_lambda(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_base::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Binaire_GP_base::calculer_mu_wilke(), Loi_Etat_base::calculer_nu(), Loi_Etat_Multi_GP_WC::calculer_nu_sur_Sc(), Loi_Etat_Binaire_GP_base::calculer_nu_sur_Sc(), Navier_Stokes_std::calculer_pression_hydrostatique(), EOS_Tools_VDF::calculer_rho_face_np1(), Loi_Etat_Multi_GP_base::calculer_tab_mu(), Echange_contact_VDF::calculer_Teta_equiv(), Polygone::calculer_volumes(), Zone_VEF::calculer_volumes_entrelaces(), Zone_VDF::calculer_volumes_entrelaces(), Zone_PolyMAC::calculer_volumes_entrelaces(), Zone_EF::calculer_volumes_entrelaces(), Zone_EF::calculer_volumes_sommets(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Assembleur_P_VEFPreP1B::changer_base_second_membre(), check_espace_virtuel_vect(), Solv_Cholesky::Cholesky(), Scatter::construire_structures_paralleles(), Op_Dift_VEF_Face::contribue_au_second_membre(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), corriger(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Navier_Stokes_std::corriger_derivee_impl(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Assembleur_P_PolyMAC::corriger_vitesses(), Tri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Quadri_VEF::creer_facette_normales(), Hexa_VEF::creer_facette_normales(), Equation_base::derivee_en_temps_conv(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Zone_PolyMAC::discretiser(), Zone_VEF_PreP1b::discretiser(), Zone_VF::discretiser(), Zone_CoviMAC::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), EOS_Tools_VDF::divu_discvit(), Champ_val_tot_sur_vol_base::evaluer(), exemple_champ_non_homogene(), Discretisation_tools::faces_to_cells(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), RK4_D3P::faire_un_pas_de_temps_eqn_base(), RK3::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Convection_Diffusion_Temperature::filtrage_si_appart_ibc(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Champ_Generique_Tparoi_VEF::get_champ(), Turbulence_paroi_base::get_champ(), Champ_Generique_modifier_pour_QC::get_champ(), Champ_Post_Operateur_Eqn::get_champ(), Champ_Generique_Moyenne::get_champ(), Champ_Generique_Morceau_Equation::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Ecart_Type::get_champ(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Correlation::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Solveur_Masse_base::get_masse_divide_by_local_dt(), Solveur_Masse_base::get_masse_dt_local(), gmres_local(), Equation_base::Gradient_conjugue_diff_impl(), Zone_Cl_VEF::imposer_cond_lim(), Zone_Cl_VDF::imposer_cond_lim(), Zone_Cl_PolyMAC::imposer_cond_lim(), Zone_Cl_VEFP1B::imposer_cond_lim(), Zone_Cl_CoviMAC::imposer_cond_lim(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Champ_implementation_P1::init_from_file(), Fluide_base::initialiser(), Champ_front_softanalytique::initialiser(), Champ_front_var::initialiser(), Ch_front_var_instationnaire_dep::initialiser(), Champ_front_lu::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Loi_Etat_base::initialiser_inco_ch(), Navier_Stokes_std::initTimeStep(), Champ_Face_PolyMAC::interp_gve(), Test_solveur::interpreter(), Porosites_champ::interpreter(), inverser_par_diagonale(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), Simple::iterer_eqn(), Simple::iterer_eqs(), Simpler::iterer_NS(), Simple::iterer_NS(), Piso::iterer_NS(), Piso::iterer_NS_PolyMAC(), EcritureLectureSpecial::lecture_special(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Champ_Uniforme_Morceaux_Tabule_Temps::me_calculer(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Champ_front_contact_fictif_VEF::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), Fluide_base::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Chimie::mettre_a_jour(), Champ_front_recyclage::mettre_a_jour(), Champ_Fonc_base::mettre_a_jour(), Champ_Don_base::mettre_a_jour(), Champ_front_txyz::mettre_a_jour(), Champ_front_t::mettre_a_jour(), Champ_front_bruite::mettre_a_jour(), Champ_Don_Fonc_txyz::mettre_a_jour(), Convection_Diffusion_Temperature::mise_en_place_zone_fantome(), Zone_VEF_PreP1b::modifier_pour_Cl(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VDF_Q4::modifier_secmem(), Assembleur_P_VDF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_VEF::modifier_solution(), Assembleur_P_VDF::modifier_solution(), Assembleur_P_EF::modifier_solution(), Assembleur_P_CoviMAC::modifier_solution(), multiplier_ou_diviser(), Matrice_Base::multTab(), Matrice_Base::multvect(), Matrice_Base::multvectT(), Discretisation_tools::nodes_to_cells(), Convection_Diffusion_Temperature::penalisation_L2(), SSOR::preconditionner_(), Navier_Stokes_std::preparer_calcul(), Equation_base::preparer_calcul(), Navier_Stokes_std::projeter(), Champ_Uniforme_Morceaux::readOn(), Champ_Don_lu::readOn(), Champ_Don_Fonc_xyz::readOn(), Zone_Cl_VEF::remplir_normales_facettes_Cl(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), Champ_front_MED::remplir_tab(), Zone_Cl_EF::remplir_type_elem_Cl(), Precond_local::res_syst_loc_hybride(), Solv_GCP::resoudre_(), Solv_Petsc::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl(), EOS_Tools_VEF::secmembre_divU_Z(), second_membre(), Champ_Input_Proto::setValueOnTab(), Solv_Gen::solve(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_P1NC_implementation::trace(), Champ_implementation_P0::trace(), Echange_contact_PolyMAC::update_coeffs(), Op_Diff_PolyMAC_Elem::update_delta(), Echange_contact_PolyMAC::update_delta(), Op_Diff_PolyMAC_Elem::update_delta_int(), Op_Diff_PolyMAC_base::update_nu(), Champ_Face_CoviMAC::update_ve2(), Navier_Stokes_std::uzawa(), valeur_P1_L2(), Champ_Q1NC::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), Champ_Face::verifie_valeurs_cl(), verifier(), and Zone_VF::xv_bord().
{
  MD_Vector_tools::echange_espace_virtuel(*this);
}
void DoubleVect::ecrit (Sortie & os) const [virtual]
ecriture des valeurs du tableau "raw" sans structure parallele
< le marqueur -1 indique que c'est le nouveau format "ecrit", sans structure parallele
Reimplemented in DoubleTab.
Definition at line 283 of file DoubleVect.cpp.
References finl, and printOn().
Referenced by Zone_VEF::ecrit(), Zone_PolyMAC::ecrit(), Zone_EF::ecrit(), Zone_CoviMAC::ecrit(), and Zone_VF::printOn().
{
  ArrOfDouble::printOn(os);
  os << (int)-1 << finl; //!< le marqueur -1 indique que c'est le nouveau format "ecrit", sans structure parallele
}
const Type_info * DoubleVect::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab, and DoubleTrav.
Definition at line 39 of file DoubleVect.cpp.
Referenced by copy(), DoubleTab::operator=(), DoubleTab::ref(), and resize().
virtual const MD_Vector& DoubleVect::get_md_vector () const [inline, virtual]
Definition at line 101 of file DoubleVect.h.
References md_vector_.
Referenced by ajoute_alpha_v(), ajoute_carre(), ajoute_produit_scalaire(), DoubleTab::ajoute_produit_tensoriel(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), SETS::assembler(), Traitement_particulier_NS_THI::calcul_nb_som_dir(), Zone::calculer_volumes(), Zone_VEF::calculer_volumes_entrelaces(), carre(), Op_Correlation::completer(), Champ_Post_Operateur_Eqn::completer(), Champ_Generique_Transformation::completer(), Zone_VEF_PreP1b::construire_ok_arete(), Tri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Champ_Inc_base::creer_tableau_distribue(), Champ_Fonc_base::creer_tableau_distribue(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), Zone_VF::discretiser(), DoubleTrav::DoubleTrav(), MD_Vector_tools::dump_vector_with_md(), MD_Vector_tools::echange_espace_virtuel(), Debog_Pb::ecrire_gen(), Debog_Pb::ecrire_partie(), EcritureLectureSpecial::ecriture_special(), ecriture_special_part2(), get_ref_coordinates_items(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Zone_VF::info_elem_som(), Zone::init_faces_virt_bord(), init_parts(), Test_solveur::interpreter(), invalidate_data(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), EcritureLectureSpecial::lecture_special(), lecture_special_part2(), lire_special(), lit(), DoubleTab::lit(), local_carre_norme_tab(), local_carre_norme_vect(), local_imax_vect(), local_imin_vect(), local_max_abs_tab(), local_max_abs_vect(), local_max_vect(), local_min_abs_vect(), local_min_vect(), local_prodscal(), local_somme_vect(), Domaine::md_vector_sommets(), mp_moyenne_vect(), multiplier_diviser_rho(), operator==(), operator_abs(), operator_add(), operator_divide(), operator_egal(), operator_inverse(), operator_multiply(), operator_negate(), operator_sub(), SSOR::prepare_(), Solv_GCP::prepare_data(), DoubleTab::printOn(), racine_carree(), Debog_Pb::read_geometry_data(), Champ_Fonc_MED::readOn(), DoubleTab::readOn(), DoubleTab::ref_array(), DoubleTab::ref_data(), DoubleTab::ref_tab(), Op_Diff_VEF_base::remplir_nu(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), Reordonner_faces_periodiques::renum_som_perio(), Scatter::reordonner_faces_de_joint(), Solv_GCP::resoudre_(), Solv_Gen::solve(), tab_divide_any_shape(), tab_divide_any_shape_(), tab_multiply_any_shape(), tab_multiply_any_shape_(), Op_Diff_PolyMAC_base::update_nu(), Milieu_base::update_rho_cp(), Debog_Pb::verifier_gen(), Debog_Pb::verifier_partie(), Debog_Pb::verifier_partie_std(), and Zone_VF::xv_bord().
{ return md_vector_; }
const Type_info * DoubleVect::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab, and DoubleTrav.
Definition at line 39 of file DoubleVect.cpp.
Referenced by copy(), and resize().
void DoubleVect::jump (Entree & is) [virtual]
Reimplemented in DoubleTab.
Definition at line 289 of file DoubleVect.cpp.
References lit().
{
  DoubleVect::lit(is, 0 /* Do not resize&read the array */);
}
int DoubleVect::line_size () const [inline]
Definition at line 164 of file DoubleVect.h.
References line_size_, and ArrOfDouble::size_array().
Referenced by add_sommets_communs(), Champ_Face_CoviMAC::affecter_(), ajoute_alpha_v(), ajoute_carre(), ajoute_produit_scalaire(), DoubleTab::ajoute_produit_tensoriel(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Source_Generique_VEF::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_standard_VEF_Face::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter(), T_It_Sou_VDF_Face< _TYPE_ >::ajouter(), T_It_Sou_VDF_Elem< _TYPE_ >::ajouter(), Op_Dift_VDF_Face_Axi::ajouter(), Op_Diff_VDF_Face_Axi::ajouter(), T_It_VDF_Elem< _TYPE_ >::ajouter(), Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC::ajouter(), Terme_Boussinesq_PolyMAC_Face::ajouter(), Op_Diff_PolyMAC_Elem::ajouter(), Op_Diff_EF::ajouter(), Op_Div_CoviMAC::ajouter(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion_vectoriel(), Masse_CoviMAC_Face::ajouter_blocs(), Masse_CoviMAC_Elem::ajouter_blocs(), Travail_pression_CoviMAC::ajouter_blocs(), T_It_VDF_Elem< _TYPE_ >::ajouter_bords(), Op_Diff_EF::ajouter_bords(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Diff_VDF_Face_Axi::ajouter_contribution(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution(), Op_Diff_EF::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_bords(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_interne(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_EF::ajouter_contribution_new(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_Stab_VEF_Face::ajouter_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_diffusion(), Op_Dift_Stab_VEF_Face::ajouter_diffusion_vectoriel(), T_It_VDF_Elem< _TYPE_ >::ajouter_interne(), Masse_PolyMAC_Elem::ajouter_masse(), Solveur_Masse_base::ajouter_masse(), Op_Diff_EF::ajouter_new(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Dift_Stab_VEF_Face::ajouter_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_operateur_centre(), Op_Dift_Stab_VEF_Face::ajouter_operateur_centre_vectoriel(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), Op_Diff_EF::ajouter_scalaire_gen(), Op_Conv_EF::ajouter_sous_cond(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim2(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim2(), Op_Conv_EF::ajouter_sous_cond_gen(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Op_Diff_EF::ajouter_vectoriel_gen(), DoubleTab::append_line(), Masse_VEF_P1NC::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_PolyMAC_Face::appliquer_impl(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_CoviMAC_Face::appliquer_impl(), Masse_CoviMAC_Elem::appliquer_impl(), SETS::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Equation_base::calculer_champ_conserve(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Moyenne_volumique::calculer_convolution(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Diff_CoviMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Elem::calculer_dt_stab(), Fluide_reel_base::calculer_energie_interne(), Fluide_reel_base::calculer_enthalpie(), T_It_VDF_Elem< _TYPE_ >::calculer_flux_bord(), Op_Conv_EF_VEF_P1NC_Stab::calculer_flux_bords(), calculer_gradientP1NC(), Loi_Etat_rhoT_GR_QC::calculer_H(), Champ_P1NC::calculer_integrale_volumique(), Fluide_reel_base::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_rhoT_GR_QC::calculer_masse_volumique(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_min(), Fluide_base::calculer_nu(), Loi_Etat_rhoT_GR_QC::calculer_temperature(), carre(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Terme_Source_Decroissance_Radioactive_VEF_Face::completer(), Terme_Source_Decroissance_Radioactive_P0_PolyMAC::completer(), Op_Diff_PolyMAC_Elem::completer(), Terme_Source_Decroissance_Radioactive_P0_CoviMAC::completer(), Op_Diff_CoviMAC_Face::completer(), Op_Diff_CoviMAC_Elem::completer(), Op_Diff_CoviMAC_base::completer(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC::contribuer_a_avec(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Op_Div_CoviMAC::contribuer_a_avec(), T_It_VDF_Elem< _TYPE_ >::contribuer_au_second_membre_bords(), T_It_VDF_Elem< _TYPE_ >::contribuer_au_second_membre_interne(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), corriger_incr_alpha(), Solveur_Masse_base::corriger_solution(), Fluide_base::creer_nu(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Op_VEF_Face::dimensionner(), Op_VDF_Face::dimensionner(), Op_VDF_Elem::dimensionner(), Masse_PolyMAC_Elem::dimensionner(), Op_Diff_PolyMAC_Elem::dimensionner(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Solveur_Masse_base::dimensionner(), Op_EF_base::dimensionner(), Op_Div_CoviMAC::dimensionner(), Masse_CoviMAC_Face::dimensionner_blocs(), QDM_Multiphase::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), DoubleTrav::DoubleTrav(), Loi_Etat_rhoT_GR_QC::Drho_DP(), Loi_Etat_rhoT_GR_QC::Drho_DT(), Loi_Etat_rhoT_GR_QC::DT_DH(), MD_Vector_tools::dump_vector_with_md(), Debog_Pb::ecrire_gen(), Debog_Pb::ecrire_partie(), Source_WC_Chaleur_VEF::elem_to_face(), Champ_P1NC_implementation::filtrer_H1(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Sortie_libre_Gradient_Pression_impose_VEF::flux_impose(), Sortie_libre_Gradient_Pression_impose::flux_impose(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Extraction::get_champ(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Sortie_libre_Gradient_Pression_libre_VEF::Grad_P_lib_VEF(), Equation_base::Gradient_conjugue_diff_impl(), Zone_Cl_CoviMAC::imposer_cond_lim(), Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Op_Diff_CoviMAC_base::init_op_ext(), init_parts(), Equation_base::initialise_residu(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Champ_front_xyz_debit::initialiser(), MD_Vector_std::initialize_comm(), Champ_P0_VDF::integrale_espace(), invalidate_data(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), local_carre_norme_tab(), local_carre_norme_vect(), local_imax_vect(), local_imin_vect(), local_max_abs_tab(), local_max_abs_vect(), local_max_vect(), local_min_abs_vect(), local_min_vect(), local_prodscal(), local_somme_vect(), QDM_Multiphase::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::mettre_a_jour(), Op_Conv_EF_Stab_CoviMAC_Elem::mettre_a_jour(), modif_matrice_pour_periodique_apres_contribuer(), modif_matrice_pour_periodique_avant_contribuer(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_EF_base::modifier_pour_Cl(), EOS_Tools_VEF::moyenne_vol(), mp_moyenne_vect(), Op_Grad_CoviMAC_Face::mu_f(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_L2(), norme_L2(), DoubleTab::operator=(), operator_abs(), operator_add(), operator_divide(), operator_egal(), operator_inverse(), operator_multiply(), operator_negate(), operator_sub(), Operateur_base::ouvrir_fichier(), Convection_Diffusion_Temperature::penalisation_L2(), Sonde::postraiter(), Postraitement::postraiter_tableau(), SSOR::prepare_(), Solv_GCP::prepare_data(), MD_Vector_std::prepare_send_data(), Op_Conv_EF_Stab_CoviMAC_Elem::preparer_calcul(), DoubleTab::printOn(), MD_Vector_std::process_recv_data(), racine_carree(), Loi_Etat_Multi_GP_WC::readOn(), DoubleTab::ref(), DoubleTab::ref_tab(), Op_Conv_EF_VEF_P1NC_Stab::reinit_conv_pour_Cl(), Champ_Q1NC_impl::remplir_coord_noeuds(), Op_Diff_VEF_base::remplir_nu(), VEF_discretisation::residu(), VDF_discretisation::residu(), CoviMAC_discretisation::residu(), DoubleTab::resize_dim0(), Solv_GCP::resoudre_(), Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl(), Solv_Gen::solve(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), tab_divide_any_shape(), tab_divide_any_shape_(), tab_multiply_any_shape(), tab_multiply_any_shape_(), Op_Diff_VEFP1NCP1B_Face::test(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), Raccord_distant_homogene::trace_elem_distant(), Frontiere::trace_elem_local(), Raccord_distant_homogene::trace_face_distant(), Frontiere::trace_face_local(), Frontiere::trace_som_local(), trait_part_calculer_ec_faces(), Champ_front_debit_massique::update_coeff(), Op_Diff_PolyMAC_Elem::update_delta(), Op_Diff_PolyMAC_Elem::update_delta_int(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_CoviMAC_base::update_nu_invh(), Champ_Face_CoviMAC::update_ve(), Champ_Face_CoviMAC::update_ve2(), Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries(), Dirichlet::val_imp_au_temps(), Champ_implementation_P0::valeur_a_elem_compo(), Champ_Inc_base::valeur_aux_bords(), Champ_base::valeur_aux_bords(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_Tabule_Morceaux::valeur_aux_elems(), Champ_Face_CoviMAC::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems_compo(), Champ_Face_CoviMAC::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_P1iP1B_implementation::valeur_aux_sommets(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), Champ_implementation_sommet_base::valeur_aux_sommets_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), valeur_P1_L2(), Champ_implementation_P1::value_interpolation(), Vecteur3::Vecteur3(), Debog_Pb::verifier_gen(), Debog_Pb::verifier_partie(), and Debog_Pb::verifier_partie_std().
{
// Si line_size_ est nulle, size_array doit etre nul aussi
  assert(line_size_ > 0 || size_array() == 0);
  return line_size_;
}
void DoubleVect::lit (Entree & is, int resize_and_read = 1) [virtual]
lecture d'un tableau pour reprise de calcul. On lit les valeurs "raw".
Attention, si le tableau n'est pas vide, il doit deja avoir la bonne
taille et la bonne structure, sinon erreur !
Parameter resize_and_read if the array is sized AND read (by default, yes)
Reimplemented in DoubleTab.
Definition at line 298 of file DoubleVect.cpp.
References ArrOfDouble::addr(), Cerr, Process::exit(), finl, Entree::get(), get_md_vector(), min(), Array_base::NOCOPY_NOINIT, resize(), ArrOfDouble::size_array(), and sz.
Referenced by jump(), and Zone_VF::readOn().
{
  int sz = -1;
  is >> sz;
  if (resize_and_read)
    {
      if (size_array() == 0 && (!get_md_vector().non_nul()))
        {
          resize(sz, NOCOPY_NOINIT);
        }
      else
        {
          if (sz != size_array())
            {
// Si on cherche a relire un tableau de taille inconnue, le tableau doit
// etre reset() a l'entree. On n'aura pas la structure parallele du tableau !
              Cerr << "Error in DoubleVect::lit(Entree & is): array has already a structure with incorrect size" << finl;
              exit();
            }
        }
      is.get(addr(), sz);
    }
  else
    {
// May be slow if large chunks are read:
// Double tmp;
// for (int i=0;i<sz;i++) is >> tmp;
// So we bufferize:
      int buffer_size = min(sz,128000);
      ArrOfDouble tmp(buffer_size);
      while(sz>buffer_size)
        {
          is.get(tmp.addr(), buffer_size);
          sz-=buffer_size;
        }
      is.get(tmp.addr(), sz);
    }
  int sz_reel = -2;
  is >> sz_reel;
  if (sz_reel >= 0)
    {
// Lecture de l'ancien format. Ignore les valeurs lues.
      int sz_virt;
      is >> sz_virt;
      DescStructure toto;
      is >> toto;
      ArrOfInt it_communs;
      is >> it_communs;
      ArrOfInt it_communs_tot;
      is >> it_communs_tot;
    }
}
double DoubleVect::local_max_abs_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 2217 of file DoubleVect.cpp.
Referenced by Op_Diff_VEFP1NCP1B_Face::test().
{
  return ::local_max_abs_vect(*this, opt);
}
double DoubleVect::local_max_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 2213 of file DoubleVect.cpp.
Referenced by Solveur_Masse_base::ajouter_masse_dt_local().
{
  return ::local_max_vect(*this, opt);
}
double DoubleVect::local_min_abs_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 2221 of file DoubleVect.cpp.
{
  return ::local_min_abs_vect(*this, opt);
}
double DoubleVect::local_min_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 2209 of file DoubleVect.cpp.
Referenced by Champ_P1NC::calcul_y_plus(), and Porosites::interpreter().
{
  return ::local_min_vect(*this, opt);
}
double DoubleVect::mp_max_abs_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 2233 of file DoubleVect.cpp.
Referenced by Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_VDF_base::calculer_dt_local(), and test().
{
  return ::mp_max_abs_vect(*this, opt);
}
double DoubleVect::mp_max_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 2225 of file DoubleVect.cpp.
{
  return ::mp_max_vect(*this, opt);
}
double DoubleVect::mp_min_abs_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 2237 of file DoubleVect.cpp.
{
  return ::mp_min_abs_vect(*this, opt);
}
double DoubleVect::mp_min_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const
Definition at line 2229 of file DoubleVect.cpp.
Referenced by ExtrudeParoi::extrude().
{
  return ::mp_min_vect(*this, opt);
}
double DoubleVect::mp_norme_vect () const
Definition at line 2349 of file DoubleVect.cpp.
{
  return ::mp_norme_vect(*this);
}
void DoubleVect::operator*= (const DoubleVect & v)
Definition at line 2249 of file DoubleVect.cpp.
References operator_multiply().
{
  operator_multiply(*this, v);
}
void DoubleVect::operator*= (const double dy)
muliplie toutes les cases par dy
Returns:
ArrOfDouble &
Signification: *this
Reimplemented from ArrOfDouble.
Definition at line 2261 of file DoubleVect.cpp.
References operator_multiply().
{
  operator_multiply(*this, x);
}
void DoubleVect::operator+= (const DoubleVect & v)
Definition at line 2241 of file DoubleVect.cpp.
References operator_add().
{
  operator_add(*this, v);
}
void DoubleVect::operator+= (const double dy)
ajoute la meme valeur a toutes les cases du tableau
Returns:
ArrOfDouble
Signification: *this
Contraintes:
Reimplemented from ArrOfDouble.
Definition at line 2253 of file DoubleVect.cpp.
References operator_add().
{
  operator_add(*this, x);
}
void DoubleVect::operator-= (const double dy)
soustrait la meme valeur a toutes les cases
Returns:
ArrOfDouble &
Signification: *this
Reimplemented from ArrOfDouble.
Definition at line 2257 of file DoubleVect.cpp.
References operator_sub().
{
  operator_sub(*this, x);
}
void DoubleVect::operator-= (const DoubleVect & v)
Definition at line 2245 of file DoubleVect.cpp.
References operator_sub().
{
  operator_sub(*this, v);
}
void DoubleVect::operator/= (const double dy)
divise toutes les cases par dy
Returns:
ArrOfDouble &
Signification: *this
Reimplemented from ArrOfDouble.
Definition at line 2289 of file DoubleVect.cpp.
References operator_divide().
{
  operator_divide(*this, x);
}
void DoubleVect::operator/= (const DoubleVect & v)
Definition at line 2293 of file DoubleVect.cpp.
References operator_divide().
{
  operator_divide(*this, v);
}
DoubleVect & DoubleVect::operator= (const DoubleVect & v)
copie la structure et les valeurs du tableau v dans *this avec ArrOfDouble::operator=()
(attention, si le tableau est de type ref_data ou ref, restrictions et cas particuliers !!!)
Attention: si on ne veut pas copier les structures paralleles, utiliser inject_array()
Reimplemented in DoubleTab, and DoubleTrav.
Definition at line 155 of file DoubleVect.cpp.
References copy().
Referenced by operator=().
{
  copy(v);
  return *this;
}
DoubleVect & DoubleVect::operator= (double x)
idem que ArrOfDouble::operator=(double)
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab, and DoubleTrav.
Definition at line 207 of file DoubleVect.cpp.
References operator=().
{
  ArrOfDouble::operator=(x);
  return *this;
}
Sortie & DoubleVect::printOn (Sortie & x) const [protected, virtual]
Ecriture d'un vecteur sequentiel (sans descripteur parallele)
Pour l'instant: erreur si presence d'un md_vector_ (sinon quoi faire ?)
Pour les vecteurs paralleles, utiliser une methode de sauvegarde/reprise.
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab, and DoubleTrav.
Definition at line 44 of file DoubleVect.cpp.
References Cerr, Process::exit(), finl, md_vector_, MD_Vector::non_nul(), and Process::nproc().
Referenced by ecrit().
{
  if (nproc() > 1 && md_vector_.non_nul())
    {
      Cerr << "Error in DoubleVect::printOn: try to print a parallel vector" << finl;
      exit();
    }
  ArrOfDouble::printOn(os);
  return os;
}
void DoubleVect::racine_carree (Mp_vect_options opt = VECT_ALL_ITEMS)
Definition at line 2305 of file DoubleVect.cpp.
Referenced by Op_Ecart_type::calculer_valeurs().
{
  ::racine_carree(*this, opt);
}
Entree & DoubleVect::readOn (Entree & is) [protected, virtual]
Lecture d'un vecteur sequentiel (comme un ArrOfDouble)
Attention: appel invalide si le vecteur a un MD_Vector non nul.
(pour les vecteurs paralleles, utiliser une methode de sauvegarde/reprise)
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab, and DoubleTrav.
Definition at line 58 of file DoubleVect.cpp.
References Cerr, Process::exit(), finl, line_size_, md_vector_, MD_Vector::non_nul(), ArrOfDouble::size_array(), and size_reelle_.
{
  if (md_vector_.non_nul())
    {
// Que veut-on faire si on lit dans un vecteur ayant deja une structure parallele ?
      Cerr << "Error in DoubleVect::readOn: vector has a parallel structure" << finl;
      exit();
    }
  ArrOfDouble::readOn(is);
  size_reelle_ = size_array();
  line_size_ = 1;
  return is;
}
void DoubleVect::ref (const DoubleVect & v) [virtual]
detache le tableau et l'attache a v (sauf si v==*this, ne fait rien)
Fait pointer le tableau sur la meme zone de memoire que v et copie le MD_Vector
(utilise ArrOfDouble::attach_array())
Attention, il devient alors interdit de resizer le tableau v ainsi que *this
Methode virtuelle reimplementee dans DoubleTab
Reimplemented in DoubleTab.
Definition at line 133 of file DoubleVect.cpp.
References ArrOfDouble::attach_array(), ArrOfDouble::detach_array(), line_size_, md_vector_, and size_reelle_.
Referenced by Eval_Gravite_VDF_Face::associer(), Op_Dift_VDF_var_Face_Axi::associer(), Op_Dift_VDF_Face_Axi::associer(), Op_Diff_VDF_var_Face_Axi::associer(), Op_Diff_VDF_Face_Axi::associer(), Op_Grad_VDF_Face::associer(), Op_Grad_P0_to_Face::associer(), Eval_Diff_VDF_var::associer(), Eval_Diff_VDF_Multi_inco_const::associer(), Op_Grad_PolyMAC_Face::associer(), Eval_Dift_VDF_var::associer_diff_turb(), Eval_Dift_VDF_Multi_inco_var::associer_diff_turb(), Eval_Dift_VDF_Multi_inco_const::associer_diff_turb(), Eval_Dift_VDF_const::associer_diff_turb(), Evaluateur_VDF::associer_porosite(), Evaluateur_PolyMAC::associer_porosite(), Source_Fluide_Dilatable_VEF_Proto::associer_volume_porosite_impl(), Source_Fluide_Dilatable_VDF_Proto::associer_volume_porosite_impl(), Evaluateur_VDF::associer_zones(), Force_Centrifuge_VDF_Face_Axi::associer_zones(), Evaluateur_PolyMAC::associer_zones(), Evaluateur_Source_VEF_Face::changer_volumes_entrelaces_Cl(), Evaluateur_Source_VEF_Face::completer(), Eval_Source_C_VEF_Face::completer(), Eval_Puiss_Th_VEF_Face::completer(), Evaluateur_Source_VDF_Face::completer(), Evaluateur_Source_VDF_Elem::completer(), Eval_Puiss_Th_QC_VEF_Face::completer(), Evaluateur_Source_PolyMAC_Face::completer(), Evaluateur_Source_PolyMAC_Elem::completer(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Evaluateur_Source_CoviMAC_Face::completer(), Evaluateur_Source_CoviMAC_Elem::completer(), Op_Diff_CoviMAC_Face::completer(), Op_Conv_EF_Stab_CoviMAC_Face::completer(), Eval_Gravite_VDF_Face::Eval_Gravite_VDF_Face(), Evaluateur_PolyMAC::Evaluateur_PolyMAC(), Evaluateur_Source_CoviMAC_Elem::Evaluateur_Source_CoviMAC_Elem(), Evaluateur_Source_CoviMAC_Face::Evaluateur_Source_CoviMAC_Face(), Evaluateur_Source_PolyMAC_Elem::Evaluateur_Source_PolyMAC_Elem(), Evaluateur_Source_PolyMAC_Face::Evaluateur_Source_PolyMAC_Face(), Evaluateur_Source_VDF_Elem::Evaluateur_Source_VDF_Elem(), Evaluateur_Source_VDF_Face::Evaluateur_Source_VDF_Face(), Evaluateur_Source_VEF_Face::Evaluateur_Source_VEF_Face(), Evaluateur_VDF::Evaluateur_VDF(), Eval_Diff_VDF_var::mettre_a_jour(), Solv_GCP::resoudre_(), and MD_Vector_tools::restore_vector_with_md().
{
  if (&v != this)
    {
      detach_array();
      attach_array(v);
      md_vector_ = v.md_vector_;
      size_reelle_ = v.size_reelle_;
      line_size_ = v.line_size_;
    }
}
void DoubleVect::ref_array (ArrOfDouble & m, int start = 0, int sz = -1) [virtual]
voir ArrOfDouble::ref_array().
(cree un tableau sans structure parallele)
< pas size qui peut valoir -1
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab.
Definition at line 235 of file DoubleVect.cpp.
References MD_Vector::detach(), line_size_, md_vector_, ArrOfDouble::size_array(), and size_reelle_.
Referenced by Equation_base::dimensionner_matrice(), and Equation_base::dimensionner_matrice_sans_mem().
{
  md_vector_.detach();
  ArrOfDouble::ref_array(m, start, new_size);
  size_reelle_ = size_array(); //!< pas size qui peut valoir -1
  line_size_ = 1;
}
void DoubleVect::ref_data (double * ptr, int new_size) [virtual]
voir ArrOfDouble::ref_data().
(cree un tableau sans structure parallele)
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab.
Definition at line 225 of file DoubleVect.cpp.
References MD_Vector::detach(), line_size_, md_vector_, and size_reelle_.
Referenced by Matrice_Bloc_Sym::ajouter_multvect_(), Matrice_Bloc::ajouter_multvect_(), Matrice_Bloc::ajouter_multvectT_(), and Solv_GCP::prepare_data().
{
  md_vector_.detach();
  ArrOfDouble::ref_data(ptr, new_size);
  size_reelle_ = new_size;
  line_size_ = 1;
}
void DoubleVect::reset () [virtual]
met l'objet dans l'etat obtenu par le constructeur par defaut.
(voir ArrOfDouble::reset())
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab.
Definition at line 111 of file DoubleVect.cpp.
References MD_Vector::detach(), line_size_, md_vector_, and size_reelle_.
Referenced by Op_Conv_Centre_old_VEF_Face::associer(), Zone_VEF::calculer_volumes_entrelaces(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Matrice_Morse::operator=(), Solv_GCP::resoudre_(), and MD_Vector_tools::restore_vector_with_md().
{
  md_vector_.detach();
  line_size_ = 1;
  size_reelle_ = 0;
  ArrOfDouble::reset();
}
void DoubleVect::resize (int n, Array_base::Resize_Options opt = COPY_INIT) [inline]
Change la taille du vecteur (identique a resize_array()
pour le traitement des anciennes valeurs et de nouvelles cases).
Attention: Cette methode n'est pas virtuelle, et afin d'eviter d'amener
un DoubleTab dans un etat invalide, l'appel est interdit si l'objet
est de ce type. Dans ce cas, voir resize_tab.
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab.
Definition at line 193 of file DoubleVect.h.
References get_info(), info(), resize_vect_(), and ArrOfDouble::size_array().
Referenced by Matrice_Morse::affecte_prod(), T_It_Sou_VDF_Face< _TYPE_ >::ajouter(), DP_Impose_PolyMAC_Face::ajouter(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_CoviMAC::assembler_mat(), Champ_front_contact_VEF::calcul_grads_locaux(), Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), Op_Diff_P1NC_barprim::calculer(), Zone_VF::calculer_coefficient_echange_thermique(), Zone_VF::calculer_coefficient_frottement(), Zone_VEF::calculer_h_carre(), Zone_PolyMAC::calculer_h_carre(), Zone_EF::calculer_h_carre(), Zone_CoviMAC::calculer_h_carre(), calculer_h_local(), Echange_contact_Correlation_VDF::calculer_h_solide(), Zone_EF::calculer_porosites_sommets(), Faces::calculer_surfaces(), Polygone::calculer_un_centre_gravite(), Polyedre::calculer_un_centre_gravite(), Zone_EF::calculer_volumes_sommets(), Champ_front_recyclage::Champ_front_recyclage(), Perte_Charge_Circulaire_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Circulaire_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Circulaire_CoviMAC_Face::coeffs_perte_charge(), Matrice_Morse_Sym::compacte(), Matrice_Morse::compacte(), Sortie_libre_Gradient_Pression_libre_VEF::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Sortie_libre_Gradient_Pression_impose::completer(), Source_Neutronique::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), Source_base::completer(), Matrice_Dense::convert_to_morse_matrix(), copy(), Matrice_Morse::dimensionner(), Matrice_Diagonale::dimensionner(), Zone_VDF::dist_norm_bord(), Zone_PolyMAC::dist_norm_bord(), Zone_CoviMAC::dist_norm_bord(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Zone::identifie_item_unique(), Echange_contact_Correlation_VEF::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Terme_Source_Canal_RANS_LES_VDF_Elem::init(), Traitement_particulier_Solide_canal_VDF::init_calcul_moyenne(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), Traitement_particulier_Solide_canal_VDF::init_calcul_stats(), Traitement_particulier_Solide_canal::init_calcul_stats(), Equation_base::initialise_residu(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Champ_front_contact_VEF::initialiser(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), Ch_front_Vortex::initialiser(), Navier_Stokes_std::initTimeStep(), Matrice_Morse::inverse(), Simple::iterer_eqs(), Traitement_particulier_NS_Brech_VEF::lire(), Traitement_particulier_NS_Profils::lire(), Terme_Source_Coriolis::lire_donnees(), lit(), Echange_contact_Correlation_VEF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC::mettre_a_jour(), DP_Impose_PolyMAC_Face::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::mettre_a_jour(), DP_Impose_CoviMAC_Face::mettre_a_jour(), Assembleur_P_VDF_Q4::modifier_secmem(), Terme_Source_Canal_RANS_LES_VDF_Face::norme_vit(), operator+(), Matrice_Morse::partie_sup(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), Source_Dirac_VEF_Face::readOn(), Perte_Charge_Singuliere_VEF_Face::readOn(), Op_Conv_EF_VEF_P1NC_Stab::readOn(), Source_Dirac_VDF_Elem::readOn(), Perte_Charge_Singuliere_VDF_Face::readOn(), Source_Neutronique::readOn(), Champ_front_synt::readOn(), Champ_front_debit_QC::readOn(), Perte_Charge_Singuliere_PolyMAC_Face::readOn(), Champ_front_recyclage::readOn(), Pave::readOn(), Init_par_partie::readOn(), Champ_front_fonc_pois_tube::readOn(), Champ_front_fonc_pois_ipsn::readOn(), Champ_front_bruite::readOn(), Perte_Charge_Singuliere_CoviMAC_Face::readOn(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Traitement_particulier_NS_canal_VEF::remplir_Y(), Traitement_particulier_NS_canal_VDF::remplir_Y(), resize_tab(), Solv_TDMA::resoudre(), Solv_Gen::resoudre_systeme(), Raccord_distant_homogene::trace_face_distant(), Echange_contact_Correlation_VDF::trier_coord(), Champ_front_recyclage::UPb(), Champ_front_softanalytique::valeur_a(), champ_init_canal_sinal::valeur_a(), Champ_som_lu_VEF::valeur_a_compo(), champ_init_canal_sinal::valeur_aux_compo(), Champ_front_instationnaire_base::valeurs_face(), Champ_front_base::valeurs_face(), and Champ_front_uniforme::valeurs_face().
{
// Verifie que l'objet est bien du type DoubleVect
  assert(n == size_array() || get_info() == DoubleVect::info());
  resize_vect_(n, opt);
}
void DoubleVect::resize_tab (int n, Array_base::Resize_Options opt = COPY_INIT) [virtual]
methode virtuelle identique a resize_array(), permet de traiter
de facon generique les ArrOf, Vect et Tab.
Cree un tableau sequentiel...
Si l'objet est de type DoubleVect, appel a resize(n)
Prerequis: voir resize()
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab.
Definition at line 218 of file DoubleVect.cpp.
References resize().
{
  resize(n, opt);
}
void DoubleVect::resize_vect_ (int n, Array_base::Resize_Options opt = COPY_INIT) [inline, protected]
Methode interne de resize (appellee par DoubleTab::resize(...))
sans precondition sur le type de l'objet.
Definition at line 205 of file DoubleVect.h.
References Cerr, Process::exit(), finl, line_size_, md_vector_, MD_Vector::non_nul(), ArrOfDouble::resize_array_(), and size_reelle_.
Referenced by DoubleTab::append_line(), resize(), DoubleTab::resize(), and DoubleTab::resize_dim0().
{
// Note B.M.: j'aurais voulu interdire completement resize des qu'on a un descripteur
// mais il y en a partout dans le code (on resize les tableaux alors qu'ils ont deja
// la bonne taille). Donc j'autorise si la taille ne change pas.
// assert(!md_vector_.non_nul() || n == size_array());
// PL: 1.7.0 is now strict about this point:
  if (md_vector_.non_nul())
    {
      Cerr << "Resize of a distributed array is forbidden!" << finl;
      exit();
    }
  assert(n == 0 || (n > 0 && line_size_ > 0 && n % line_size_ == 0));
  resize_array_(n, opt);
  size_reelle_ = n;
// ne pas mettre line_size_ a 1 ici, voir DoubleTab::resize_dim0()
}
DoubleVect & DoubleVect::self_cast (Objet_U & r) [static]
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab, and DoubleTrav.
Definition at line 39 of file DoubleVect.cpp.
const DoubleVect & DoubleVect::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab, and DoubleTrav.
Definition at line 39 of file DoubleVect.cpp.
void DoubleVect::set_line_size_ (int n) [inline, protected]
change l'attribut line_size_ du tableau avec n >= 1
n == 0 est autorise uniquement si size_array_ == 0
Definition at line 177 of file DoubleVect.h.
References line_size_, md_vector_, and MD_Vector::non_nul().
Referenced by DoubleTab::DoubleTab(), DoubleTrav::DoubleTrav(), DoubleTab::readOn(), DoubleTab::ref_tab(), and DoubleTab::resize().
{
  assert(!md_vector_.non_nul() || line_size_ == n);
  assert(n >= 0);
  line_size_ = n;
}
void DoubleVect::set_md_vector (const MD_Vector & md_vector) [virtual]
associe le md_vector au vecteur et initialise l'attribut size_reelle_
(voir methode size_reelle())
Si md_vector est nul, detache simplement le md_vector existant.
< Cas particulier ou la size_reelle ne veut rien dire
Reimplemented in DoubleTab.
Definition at line 248 of file DoubleVect.cpp.
References Cerr, Process::exit(), finl, MD_Vector_base::get_nb_items_reels(), MD_Vector_base::get_nb_items_tot(), line_size_, md_vector_, MD_Vector::non_nul(), ArrOfDouble::size_array(), size_reelle_, and MD_Vector::valeur().
Referenced by Zone_VF::discretiser(), Test_solveur::interpreter(), and Solv_GCP::prepare_data().
{
  int size_r = size_array();
  if (md_vector.non_nul())
    {
      size_r = md_vector.valeur().get_nb_items_reels();
      if (size_r >= 0)
        size_r *= line_size_;
      else
        size_r = -1; //!< Cas particulier ou la size_reelle ne veut rien dire
      int size_tot = md_vector.valeur().get_nb_items_tot() * line_size_;
      if (size_tot != size_array())
        {
          Cerr << "Internal error in DoubleVect::set_md_vector(): wrong array size\n"
               << " Needed size = " << md_vector.valeur().get_nb_items_tot() << " x " << line_size_
               << "\n Actual size = " << size_array() << finl;
          exit();
        }
      if (line_size_ == 0)
        {
          Cerr << "Internal error in DoubleVect::set_md_vector():\n"
               << " cannot attach descriptor to empty array (line_size_ is zero)" << finl;
          exit();
        }
    }
  size_reelle_ = size_r;
  md_vector_ = md_vector;
}
int DoubleVect::size () const [inline]
Identique a size_reelle()
Definition at line 153 of file DoubleVect.h.
References size_reelle().
Referenced by Champ_Face::affecter(), ajoute_alpha_v_norme(), Op_Dift_VDF_base::ajouter(), Op_Diff_VDF_base::ajouter(), T_It_VDF_Elem< _TYPE_ >::ajouter(), Source_WC_Chaleur::ajouter(), Op_Conv_EF::ajouter_contribution_sous_cond(), Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::ajouter_masse_dt_local(), Matrice_SuperMorse::ajouter_mult_vect_et_prodscal(), Matrice_Diagonale::ajouter_multTab_(), Matrice_Morse_Sym::ajouter_multvect_(), Matrice_Morse::ajouter_multvect_(), Matrice_Diagonale::ajouter_multvect_(), Matrice_Dense::ajouter_multvect_(), Matrice_Dense::ajouter_multvectT_(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim2(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim2(), Op_Conv_EF::ajouter_sous_cond_gen(), Masse_VDF_Elem::appliquer_impl(), Assembleur_P_VEF::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Assembleur_P_PolyMAC::assembler_mat(), Simpler_Base::assembler_matrice_pression_implicite(), Pave::associer_domaine(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Matrice_Dense::build_matrix_from_coefficients_column_by_column(), Matrice_Dense::build_matrix_from_coefficients_line_by_line(), calcul_longueur_filtre(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Tri_VEF::calcul_xg(), Tetra_VEF::calcul_xg(), Quadri_VEF::calcul_xg(), Hexa_VEF::calcul_xg(), Tetra_PolyMAC::calcul_xg(), Segment_PolyMAC::calcul_xg(), Quadri_PolyMAC::calcul_xg(), Hexa_PolyMAC::calcul_xg(), Tri_EF::calcul_xg(), Tetra_EF::calcul_xg(), Segment_EF::calcul_xg(), Quadri_EF::calcul_xg(), Point_EF::calcul_xg(), Hexa_EF::calcul_xg(), Tetra_CoviMAC::calcul_xg(), Segment_CoviMAC::calcul_xg(), Quadri_CoviMAC::calcul_xg(), Hexa_CoviMAC::calcul_xg(), Champ_Q1NC_impl::calcule_valeur_a_elem_compo(), Loi_Etat_Multi_GP_base::calculer_alpha(), Loi_Etat_GP_base::calculer_alpha(), Loi_Etat_base::calculer_alpha(), Op_Dift_VDF_Face_base::calculer_borne_locale(), Champ_front_xyz_debit::calculer_champ_vitesse(), Loi_Etat_GR_base::calculer_Cp(), Op_Conv_VDF_base::calculer_dt_local(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Conv_EF::calculer_dt_stab(), Loi_Etat_Multi_GP_base::calculer_lambda(), Loi_Etat_GR_base::calculer_lambda(), Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_base::calculer_lambda(), Loi_Etat_Multi_GP_WC::calculer_masse_molaire(), Loi_Etat_Multi_GP_QC::calculer_masse_molaire(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_base::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_wilke(), Loi_Etat_Multi_GP_QC::calculer_mu_wilke(), Loi_Etat_Binaire_GP_base::calculer_mu_wilke(), Champ_front_xyz_debit::calculer_normales_et_integrale(), Loi_Etat_base::calculer_nu(), Loi_Etat_Multi_GP_WC::calculer_nu_sur_Sc(), Loi_Etat_Binaire_GP_base::calculer_nu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_tab_Cp(), Loi_Etat_Multi_GP_base::calculer_tab_mu(), Eval_Forchheimer_VEF_Face::calculer_terme_source(), Eval_Darcy_VEF_Face::calculer_terme_source(), Eval_Source_C_VDF_Elem::calculer_terme_source(), Eval_Source_C_PolyMAC_Elem::calculer_terme_source(), Eval_Source_C_CoviMAC_Elem::calculer_terme_source(), Eval_Puiss_Th_CoviMAC_Elem::calculer_terme_source(), Eval_Source_C_VEF_Face::calculer_terme_source_non_standard(), Eval_Source_C_VEF_Face::calculer_terme_source_standard(), Op_Diff_RotRot::calculer_vorticite(), Matrice_Morse::check_morse_matrix_structure(), Matrice_Morse::check_sorted_morse_matrix_structure(), Zone::chercher_elements(), Eval_Amont_VDF_Face::coeffs_arete_fluide(), Eval_Amont_VDF_Face::coeffs_arete_interne(), Eval_Amont_VDF_Face::coeffs_arete_mixte(), Eval_Amont_VDF_Face::coeffs_arete_paroi_fluide(), Eval_Amont_VDF_Face::coeffs_arete_periodicite(), Eval_Amont_VDF_Face::coeffs_arete_symetrie_fluide(), Eval_Amont_VDF_Face::coeffs_fa7_elem(), Eval_Amont_VDF_Face::coeffs_fa7_sortie_libre(), Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face(), Eval_centre_VDF_Elem::coeffs_face(), Eval_centre4_VDF_Elem::coeffs_face(), Eval_Amont_VDF_Elem::coeffs_face(), Eval_centre_PolyMAC_Elem::coeffs_face(), Eval_Amont_PolyMAC_Elem::coeffs_face(), Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_faces_interne(), Eval_centre_VDF_Elem::coeffs_faces_interne(), Eval_centre4_VDF_Elem::coeffs_faces_interne(), Eval_Amont_VDF_Elem::coeffs_faces_interne(), Eval_centre_PolyMAC_Elem::coeffs_faces_interne(), Eval_Amont_PolyMAC_Elem::coeffs_faces_interne(), Terme_Source_Canal_perio::compute_heat_flux(), Op_Dift_VDF_base::contribuer_a_avec(), Op_Diff_VDF_base::contribuer_a_avec(), Op_Dift_VDF_base::contribuer_au_second_membre(), Op_Diff_VDF_base::contribuer_au_second_membre(), convert_domain_to_Domaine(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), Source_PDF_EF::correct_vitesse(), Perte_Charge_Reguliere::correction_direction(), Terme_Source_Solide_SWIFT_VDF::correspondance_SWIFT_coarse(), Roue::dimensionner(), DoubleTrav_test(), Echange_contact_Correlation_VEF_reprendre(), Echange_contact_Correlation_VEF_sauvegarder(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_nut(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp_old(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu_old(), envoyer_all_to_all(), Parser_Eval::eval_fct(), ILU::factorisation(), Champ_P1NC_implementation::filtrer_L2(), Eval_Quick_VDF_Face::flux_arete_fluide(), Eval_Centre_VDF_Face::flux_arete_fluide(), Eval_centre4_VDF_Face::flux_arete_fluide(), Eval_Amont_VDF_Face::flux_arete_fluide(), Eval_Quick_VDF_Face_Axi::flux_arete_fluide(), Eval_Quick_VDF_Face::flux_arete_interne(), Eval_Centre_VDF_Face::flux_arete_interne(), Eval_centre4_VDF_Face::flux_arete_interne(), Eval_Amont_VDF_Face::flux_arete_interne(), Eval_Quick_VDF_Face_Axi::flux_arete_interne(), Eval_Quick_VDF_Face::flux_arete_mixte(), Eval_Centre_VDF_Face::flux_arete_mixte(), Eval_centre4_VDF_Face::flux_arete_mixte(), Eval_Amont_VDF_Face::flux_arete_mixte(), Eval_Quick_VDF_Face_Axi::flux_arete_mixte(), Eval_Quick_VDF_Face::flux_arete_paroi_fluide(), Eval_Centre_VDF_Face::flux_arete_paroi_fluide(), Eval_centre4_VDF_Face::flux_arete_paroi_fluide(), Eval_Amont_VDF_Face::flux_arete_paroi_fluide(), Eval_Quick_VDF_Face_Axi::flux_arete_paroi_fluide(), Eval_Quick_VDF_Face::flux_arete_periodicite(), Eval_Centre_VDF_Face::flux_arete_periodicite(), Eval_centre4_VDF_Face::flux_arete_periodicite(), Eval_Amont_VDF_Face::flux_arete_periodicite(), Eval_Quick_VDF_Face::flux_arete_symetrie_fluide(), Eval_Centre_VDF_Face::flux_arete_symetrie_fluide(), Eval_centre4_VDF_Face::flux_arete_symetrie_fluide(), Eval_Amont_VDF_Face::flux_arete_symetrie_fluide(), Eval_Quick_VDF_Face::flux_fa7_elem(), Eval_Grad_VDF_Face::flux_fa7_elem(), Eval_Centre_VDF_Face::flux_fa7_elem(), Eval_centre4_VDF_Face::flux_fa7_elem(), Eval_Amont_VDF_Face::flux_fa7_elem(), Eval_Quick_VDF_Face_Axi::flux_fa7_elem(), Eval_Quick_VDF_Face::flux_fa7_sortie_libre(), Eval_Grad_VDF_Face::flux_fa7_sortie_libre(), Eval_Centre_VDF_Face::flux_fa7_sortie_libre(), Eval_centre4_VDF_Face::flux_fa7_sortie_libre(), Eval_Amont_VDF_Face::flux_fa7_sortie_libre(), Eval_Quick_VDF_Face_Axi::flux_fa7_sortie_libre(), Eval_Diff_VDF_Elem< DERIVED_T >::flux_face(), Eval_Quick_VDF_Elem::flux_face(), Eval_Div_VDF_Elem::flux_face(), Eval_centre_VDF_Elem::flux_face(), Eval_centre4_VDF_Elem::flux_face(), Eval_Amont_VDF_Elem::flux_face(), Eval_centre_PolyMAC_Elem::flux_face(), Eval_Amont_PolyMAC_Elem::flux_face(), Eval_Diff_VDF_Elem< DERIVED_T >::flux_faces_interne(), Eval_Quick_VDF_Elem::flux_faces_interne(), Eval_Div_VDF_Elem::flux_faces_interne(), Eval_centre_VDF_Elem::flux_faces_interne(), Eval_centre4_VDF_Elem::flux_faces_interne(), Eval_Amont_VDF_Elem::flux_faces_interne(), Eval_centre_PolyMAC_Elem::flux_faces_interne(), Eval_Amont_PolyMAC_Elem::flux_faces_interne(), Sortie_libre_Gradient_Pression_impose_VEF::flux_impose(), Sortie_libre_Gradient_Pression_impose::flux_impose(), Sortie_libre_Text_H_ext::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), Neumann_paroi::flux_impose(), Sortie_libre_pression_imposee_QC::flux_impose(), Neumann::flux_impose(), Champ_Generique_Transformation::get_champ(), Solveur_Masse_base::get_masse_divide_by_local_dt(), Solveur_Masse_base::get_masse_dt_local(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Diagonale::get_stencil_and_coefficients(), gmres_local(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Sortie_libre_Gradient_Pression_libre_VEF::Grad_P_lib_VEF(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), Echange_impose_base::h_imp(), Source_base::impr(), Source_PDF_EF::impr(), Champ_P0_VDF::imprime(), Champ_Fonc_P0_VDF::imprime(), Champ_Face_implementation::imprime_Face(), Echange_contact_Correlation_VEF::imprimer(), Echange_contact_Correlation_VDF::imprimer(), Loi_Etat_GP_base::initialiser(), Champ_front_recyclage::initialiser(), Fluide_Weakly_Compressible::initialiser_pth_xyz(), Loi_Etat_rhoT_GP_QC::initialiser_rho(), Testeur::interpreter(), Porosites_champ::interpreter(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Champ_Tabule_Temps::me_calculer(), meme_point2(), Correlation_Vec_Sca_VEF::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Sonde::mettre_a_jour_bords(), Integrale_tps_Champ::mettre_a_jour_integrale(), Tri_VEF::modif_volumes_entrelaces_faces_joints(), Tetra_VEF::modif_volumes_entrelaces_faces_joints(), multiplier_diviser_rho(), Source_PDF_EF::multiply_coeff_volume(), multiply_sub(), Matrice_Morse_Sym::multvect_et_prodscal(), Matrice_Morse::nb_coeff(), Matrice_Diagonale::nb_colonnes(), Matrice_Diagonale::nb_lignes(), Champ_P1_isoP1Bulle::norme_L2(), Matrice_Diagonale::ordre(), Convection_Diffusion_Temperature::penalisation_L2(), Traitement_particulier_NS_canal::post_traitement_particulier(), Precond_local::precond(), ILU::preconditionner_(), Solv_GCP::prepare_data(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), Champ_Don_Face_lu::printOn(), Champ_front_synt::printOn(), Champ_front_debit_QC_fonc_t::printOn(), Champ_front_debit_QC::printOn(), Champ_front_softanalytique::printOn(), Champ_Uniforme::printOn(), Champ_front_uniforme::printOn(), Champ_front_txyz::printOn(), Champ_front_tangentiel::printOn(), Champ_front_t::printOn(), Champ_front_normal::printOn(), Champ_front_lu::printOn(), Champ_front_fonc_pois_tube::printOn(), Champ_front_fonc_pois_ipsn::printOn(), Champ_front_bruite::printOn(), Champ_Don_lu::printOn(), Champ_Don_Fonc_xyz::printOn(), Champ_Don_Fonc_txyz::printOn(), Ch_front_Vortex::printOn(), Loi_Etat_Multi_GP_QC::rabot(), Reaction::reagir(), Table::remplir(), Op_Diff_EF::remplir_nu(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Precond_local::res_syst_loc_hybride(), Precond_local::res_syst_loc_simple(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), Solv_Gen::resoudre_systeme(), Mod_turb_hyd_base::sauvegarder(), Ch_front_Vortex::sauvegarder_vortex(), Eval_Amont_VDF_Face::secmem_arete_fluide(), Eval_Amont_VDF_Face::secmem_arete_paroi_fluide(), Eval_Amont_VDF_Face::secmem_arete_symetrie_fluide(), Eval_Amont_VDF_Face::secmem_fa7_sortie_libre(), Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face(), Eval_centre_VDF_Elem::secmem_face(), Eval_centre4_VDF_Elem::secmem_face(), Eval_Amont_VDF_Elem::secmem_face(), Eval_centre_PolyMAC_Elem::secmem_face(), Eval_Amont_PolyMAC_Elem::secmem_face(), Eval_Diff_VDF_Elem< DERIVED_T >::secmem_faces_interne(), Champ_Input_Proto::setValueOnTab(), ConstIntTab_parts::size(), DoubleTab_parts::size(), Solv_Gen::solve(), Terme_Source_Canal_perio::source(), Echange_externe_impose_H::T_ext(), Operateur_base::tester_contribuer_a_avec(), Raccord_distant_homogene::trace_face_distant(), Champ_front_contact_VEF::trace_face_raccord(), Op_Diff_PolyMAC_base::update_nu(), Loi_Etat_Multi_GP_WC::update_Yn_values(), Navier_Stokes_std::uzawa(), Table::val(), Sortie_libre_Text_H_ext::val_ext(), Neumann_sortie_libre::val_ext(), Neumann_sortie_libre_Temp_H::val_ext(), Entree_fluide_T_h_imposee::val_imp(), Temperature_imposee_paroi_H::val_imp(), Entree_fluide_temperature_imposee_H::val_imp(), Dirichlet::val_imp_au_temps(), Champ_front_softanalytique::valeur_a(), Champ_base::valeur_a(), Champ_Don_Fonc_xyz::valeur_a(), Champ_Don_Fonc_txyz::valeur_a(), Champ_som_lu_VEF::valeur_a_compo(), Champ_Q1NC_impl::valeur_a_elem(), Champ_implementation_sommet_base::valeur_a_elem(), Champ_implementation_P0::valeur_a_elem(), Champ_Uniforme_Morceaux::valeur_a_elem(), Champ_Fonc_Morceaux::valeur_a_elem(), Champ_Fonc_Fonction_txyz_Morceaux::valeur_a_elem(), Champ_Don_lu::valeur_a_elem(), Champ_implementation_sommet_base::valeur_a_elem_compo(), Tayl_Green::valeur_aux(), Champ_base::valeur_aux_compo(), Tayl_Green::valeur_aux_compo(), Champ_Q1NC_impl::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems_compo(), Champ_Q1NC_impl::valeur_aux_elems_compo(), Champ_som_lu_VDF::valeur_aux_elems_compo(), Champ_Face_implementation::valeur_aux_elems_compo(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), Champ_som_lu::valeur_aux_elems_compo(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_implementation_sommet_base::valeur_aux_elems_compo(), Champ_implementation_P0::valeur_aux_elems_compo(), Champ_Uniforme_Morceaux::valeur_aux_elems_compo(), Champ_Fonc_Morceaux::valeur_aux_elems_compo(), Champ_Fonc_Fonction_txyz_Morceaux::valeur_aux_elems_compo(), Champ_Don_lu::valeur_aux_elems_compo(), Champ_Face_CoviMAC::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_Q4_implementation::valeur_aux_sommets(), Champ_Q4_implementation::valeur_aux_sommets_compo(), Champ_implementation_sommet_base::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), Table::valeurs(), Zone_VEF::vecteur_face_facette(), verifier(), Roue::~Roue(), Terme_Source_Canal_RANS_LES_VDF_Elem::~Terme_Source_Canal_RANS_LES_VDF_Elem(), Terme_Source_Canal_RANS_LES_VDF_Face::~Terme_Source_Canal_RANS_LES_VDF_Face(), and Terme_Source_Canal_RANS_LES_VEF_Face::~Terme_Source_Canal_RANS_LES_VEF_Face().
{
  return size_reelle();
}
int DoubleVect::size_reelle () const [inline]
Taille de l'espace "reel" du vecteur.
(si md_vector_ est nul, cette valeur est identique a size_array(),
sinon, soit elle est egale a md_vector_....get_nb_items(),
soit l'appel est invalide (en particulier si les items reels ne
sont pas regroupes en debut de tableau)
On peut interroger le vecteur pour savoir si size_reelle() est valide avec size_reelle_ok()
Definition at line 135 of file DoubleVect.h.
References md_vector_, MD_Vector::non_nul(), ArrOfDouble::size_array(), and size_reelle_.
Referenced by descente(), descente_assert(), descente_assert_precond_diag(), descente_bloc_extradiag_assert(), descente_diag_ok_assert(), descente_precond_diag(), gmres_local(), local_norme_vect(), Champ_P1NC_implementation::nb_colonnes(), DoubleTab::operator=(), DoubleTab::ref(), DoubleTab::ref_array(), DoubleTab::ref_data(), DoubleTab::ref_tab(), remontee(), remontee_assert(), remontee_assert_precond_diag(), remontee_bloc_extradiag_assert(), remontee_diag_ok_assert(), remontee_precond_diag(), Solv_GCP::resoudre_(), size(), and traite_diagonale().
{
// Si cet assert plante, c'est que l'appel a ete declare invalide par le
// MD_Vect associe a ce vecteur.
  assert(size_reelle_ >= 0);
// Si cet assert plante, c'est que le tableau a ete redimensionne avec resize_array() au lieu de resize().
// (invalide pour un Vect ou un Tab).
  assert(size_array() == size_reelle_ || md_vector_.non_nul());
  return size_reelle_;
}
int DoubleVect::size_reelle_ok () const [inline]
Definition at line 147 of file DoubleVect.h.
References size_reelle_.
Referenced by Op_Correlation::completer(), descente(), descente_assert(), descente_assert_precond_diag(), descente_bloc_extradiag_assert(), descente_diag_ok_assert(), descente_precond_diag(), gmres_local(), DoubleTab::lit(), multiply_sub(), Champ_Inc_base::nb_valeurs_nodales(), DoubleTab::operator=(), DoubleTab::ref(), remontee(), remontee_assert(), remontee_assert_precond_diag(), remontee_bloc_extradiag_assert(), remontee_diag_ok_assert(), remontee_precond_diag(), Solv_GCP::resoudre_(), and traite_diagonale().
{
  return size_reelle_ >= 0;
}
int DoubleVect::size_totale () const [inline]
Identique a size_array()
Definition at line 159 of file DoubleVect.h.
References ArrOfDouble::size_array().
Referenced by Loi_Etat_base::abortTimeStep(), ajoute_alpha_v(), ajoute_carre(), ajoute_produit_scalaire(), DoubleTab::ajoute_produit_tensoriel(), Op_Dift_VDF_base::ajouter(), Matrice_Morse_Sym::ajouter_multvect_(), Assembleur_P_VEFPreP1B::assembler_mat(), Zone_EF::calculer_Bij(), Assembleur_P_VEF::calculer_inv_volume(), calculer_inv_volume(), Zone::calculer_volumes(), Triangle::calculer_volumes(), Tetraedre::calculer_volumes(), Segment_axi::calculer_volumes(), Segment::calculer_volumes(), Rectangle_axi::calculer_volumes(), Rectangle_2D_axi::calculer_volumes(), Rectangle::calculer_volumes(), Quadrangle_VEF::calculer_volumes(), Prisme::calculer_volumes(), Polygone::calculer_volumes(), Polyedre::calculer_volumes(), Hexaedre_VEF::calculer_volumes(), Hexaedre_axi::calculer_volumes(), Hexaedre::calculer_volumes(), carre(), Solv_Cholesky::Cholesky(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), descente(), descente_assert(), descente_assert_precond_diag(), descente_bloc_extradiag_assert(), descente_diag_ok_assert(), descente_precond_diag(), Masse_CoviMAC_Face::dimensionner_blocs(), Equation_base::Gradient_conjugue_diff_impl(), init_parts(), Loi_Etat_GP_base::initialiser(), Test_solveur::interpreter(), Simple::iterer_eqs(), local_carre_norme_vect(), local_imax_vect(), local_imin_vect(), local_max_abs_vect(), local_max_vect(), local_min_abs_vect(), local_min_vect(), local_prodscal(), local_somme_vect(), EOS_Tools_VDF::mettre_a_jour(), Loi_Etat_base::mettre_a_jour(), modif_par_porosite_si_flag(), mp_moyenne_vect(), multiply_sub(), Matrice_Morse_Sym::multvect_et_prodscal(), Champ_P1NC_implementation::nb_colonnes_tot(), operator_abs(), operator_add(), operator_divide(), operator_egal(), operator_inverse(), operator_multiply(), operator_negate(), operator_sub(), SSOR::prepare_(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), racine_carree(), remontee(), remontee_assert(), remontee_assert_precond_diag(), remontee_bloc_extradiag_assert(), remontee_diag_ok_assert(), remontee_precond_diag(), Op_Diff_EF::remplir_nu(), Loi_Etat_GP_base::remplir_T(), Solv_GCP::resoudre_(), Solv_GCP_NS::resoudre_systeme(), Fluide_Quasi_Compressible::secmembre_divU_Z(), EOS_Tools_VEF::secmembre_divU_Z(), tab_divide_any_shape_(), tab_multiply_any_shape_(), traite_diagonale(), Tayl_Green::valeur_aux(), Init_par_partie::valeur_aux(), champ_init_canal_sinal::valeur_aux(), Tayl_Green::valeur_aux_compo(), verifier(), and Op_Div_VEFP1B_Elem::volumique().
{
  return size_array();
}
unsigned DoubleVect::taille_memoire () const [virtual]
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab, and DoubleTrav.
Definition at line 39 of file DoubleVect.cpp.
Member Data Documentation
const Type_info DoubleVect::info_obj [static]
Reimplemented from ArrOfDouble.
Reimplemented in DoubleTab, and DoubleTrav.
Definition at line 40 of file DoubleVect.h.
int DoubleVect::line_size_ [private]
Definition at line 126 of file DoubleVect.h.
Referenced by copy_(), line_size(), readOn(), ref(), ref_array(), ref_data(), reset(), resize_vect_(), set_line_size_(), and set_md_vector().
MD_Vector DoubleVect::md_vector_ [private]
Definition at line 116 of file DoubleVect.h.
Referenced by copy(), copy_(), detach_vect(), get_md_vector(), printOn(), readOn(), ref(), ref_array(), ref_data(), reset(), resize_vect_(), set_line_size_(), set_md_vector(), and size_reelle().
int DoubleVect::size_reelle_ [private]
Definition at line 119 of file DoubleVect.h.
Referenced by copy_(), readOn(), ref(), ref_array(), ref_data(), reset(), resize_vect_(), set_md_vector(), size_reelle(), and size_reelle_ok().
The documentation for this class was generated from the following files:
src/Kernel/Math/DoubleVect.h
src/Kernel/Math/DoubleVect.cpp