TRUST: Champ_Face_PolyMAC_P0 Class Reference
Champ_Face_PolyMAC_P0 Class Reference
: class Champ_Face_PolyMAC_P0
Champ correspondant a une inconnue decrite par ses tangentes aux faces duales (ligne amont-aval, type vitesse)
Les flux aux faces sont accessibles par les methodes valeurs_normales(), avec synchro automatique
Degres de libertes : composantes tangentielles aux faces duales
#include <Champ_Face_PolyMAC_P0.h>
Public Member Functions
Champ_Face_PolyMAC_P0 ()
~Champ_Face_PolyMAC_P0 ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int fixer_nb_valeurs_nodales (int n) override
void init_auxiliary_variables () override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
Champ_base & affecter_ (const Champ_base &) override
Affectation d'un Champ generique (Champ_base) dans
un champ inconnue.
void update_ve (DoubleTab &val) const
void init_ve2 () const
void update_ve2 (DoubleTab &val, int incr=0) const
double v_norm (const DoubleTab &val, const DoubleTab &val_f, int e, int f, int k, int l, double *v_ext, double *dnv) const
Public Member Functions inherited from Champ_Face_PolyMAC
Champ_Face_PolyMAC ()
~Champ_Face_PolyMAC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
const Zone_dis_base & zone_dis_base () const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
NE FAIT RIEN
Methode a surcharger.
DoubleTab & valeur_aux_faces (DoubleTab &result) const override
renvoie la valeur du champ aux faces
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
Champ_base & affecter_ (const Champ_base &) override
Affectation d'un Champ generique (Champ_base) dans
un champ inconnue.
int nb_valeurs_nodales () const override
Returns the number of "real" geometric positions of the
degrees of freedom, or -1 if not applicable (fields with multiple
localisations)
const Zone_VF & zone_vf () const
int fixer_nb_valeurs_nodales (int n) override
virtual void init_auxiliary_variables ()
int reprendre (Entree &fich) override
Lecture d'un champ inconnue a partir d'un flot d'entree
en vue d'une reprise.
const IntTab & fcl () const
void interp_ve (const DoubleTab &inco, DoubleTab &val, bool is_vit=true) const
void interp_ve (const DoubleTab &inco, const IntVect &, DoubleTab &val, bool is_vit=true) const
Public Member Functions inherited from Champ_Inc_base
~Champ_Inc_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_Inc_base ()
int fixer_nb_valeurs_nodales (int) override
double changer_temps (const double temps) override
Fixe le temps du champ.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps du champ inconnue.
WEC : Maintenant si on l'appelle 2 fois de suite avec le meme
argument, la 2eme ne fait rien.
int reprendre (Entree &) override
Lecture d'un champ inconnue a partir d'un flot d'entree
en vue d'une reprise.
int sauvegarder (Sortie &) const override
Sauvegarde le champ inconnue sur un flot de sortie.
Ecrit un identifiant, les valeurs du champs, et
la date (le temps au moment de la sauvegarde).
Champ_base & affecter_compo (const Champ_base &, int compo) override
Affectation d'une composante d'un Champ quelconque<br>(Champ_base) dans une composante d'un champ inconnue.
Champ_base & affecter_ (const Champ_base &) override
Affectation d'un Champ generique (Champ_base) dans
un champ inconnue.
virtual void verifie_valeurs_cl ()
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ au temps courant.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temp courant<br>(version const)
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
Calcule la valeur du champs inconnue a la position specifiee.
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
Calcule les valeurs du champs inconnue aux positions specifiees.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
Calcule les valeurs du champs inconnue aux positions specifiees,
pour une certaine composante du champ.
int nb_valeurs_nodales () const override
Returns the number of "real" geometric positions of the
degrees of freedom, or -1 if not applicable (fields with multiple
localisations)
virtual int fixer_nb_valeurs_temporelles (int)
Fixe le nombre de valeurs temporelles a conserver.
(un nombre different suivant le schema en temps utilise)
Appelle Roue::fixer_nb_cases(int)
virtual int nb_valeurs_temporelles () const
Renvoie le nombre de valeurs temporelles actuellement conservees.
Cette valeur est stockee par la Roue du Champ_Inc_base.
double changer_temps_futur (double, int i=1)
Fixe le temps du ieme champ futur.
double changer_temps_passe (double, int i=1)
Fixe le temps du ieme champ passe.
double recuperer_temps_futur (int i=1) const
Retourne le temps du ieme champ futur.
double recuperer_temps_passe (int i=1) const
Retourne le temps du ieme champ passe.
DoubleTab & valeurs (double temps) override
Renvoie les valeurs du champs a l'instant temps.
const DoubleTab & valeurs (double temps) const override
Renvoie les valeurs du champs a l'instant temps.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
DoubleTab & futur (int i=1) override
Renvoie les valeurs du champs a l'instant t+i.
const DoubleTab & futur (int i=1) const override
Renvoie les valeurs du champs a l'instant t+i.
(version const)
DoubleTab & passe (int i=1) override
Renvoie les valeurs du champs a l'instant t-i.
const DoubleTab & passe (int i=1) const override
Renvoie les valeurs du champs a l'instant t-i.
(version const)
Champ_Inc_base & avancer (int i=1)
Avance le pointeur courant de i pas de temps,
dans la liste des valeurs temporelles conservees.
Champ_Inc_base & reculer (int i=1)
Recule le pointeur courant de i pas de temps,
dans la liste des valeurs temporelles conservees.
int lire_donnees (Entree &)
Lit les valeurs du champs a partir d'un flot d'entree.
Format de lecture:
int [LE NOMBRE DE VALEURS A LIRE]
[LIRE LE NOMBRE DE VALEUR VOULUES].
virtual void associer_eqn (const Equation_base &)
Associe le champ a l'equation dont il represente une inconnue.
Simple appel a MorEqn::associer_eqn(const Equation_base&)
virtual void associer_zone_cl_dis (const Zone_Cl_dis &)
int imprime (Sortie &, int) const override
int a_une_zone_dis_base () const override
Par defaut, on ne sait pas si une zone_dis_base sera definie.
const Zone_Cl_dis & zone_Cl_dis () const
Zone_Cl_dis & zone_Cl_dis ()
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
NE FAIT RIEN
Methode a surcharger.
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
Simple appel a:
Champ_Inc_base::remplir_coord_noeuds_et_polys(DoubleTab&,IntVect& poly)
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const =0
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
Simple appel a
Champ_Inc_base::remplir_coord_noeuds(DoubleTab&)
virtual double integrale_espace (int ncomp) const
const Domaine & domaine () const
const tabs_t & derivees () const
void init_champ_calcule (const Objet_U &obj, fonc_calc_t fonc)
void reset_champ_calcule ()
DoubleTab valeur_aux_bords () const override
renvoie la valeur du champ aux faces de bord
virtual void creer_espace_distant (int dummy)
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Face_PolyMAC_P0 & self_cast (Objet_U &)
static const Champ_Face_PolyMAC_P0 & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Face_PolyMAC
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Face_PolyMAC & self_cast (Objet_U &)
static const Champ_Face_PolyMAC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Inc_base
static const Type_info * info ()
static Champ_Inc_base & self_cast (Objet_U &)
static const Champ_Inc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
IntTab ve2d
IntTab ve2j
IntTab ve2bj
DoubleTab ve2c
DoubleTab ve2bc
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Face_PolyMAC
static const Type_info info_obj
Static Public Attributes inherited from Champ_Inc_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Entree & readOn (Entree &) override
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Protected Member Functions inherited from Champ_Face_PolyMAC
Sortie & printOn (Sortie &x) const override
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Entree & readOn (Entree &) override
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
virtual Champ_base & le_champ (void)
virtual const Champ_base & le_champ (void) const
void init_fcl () const
Protected Member Functions inherited from Champ_Inc_base
Sortie & printOn (Sortie &x) const override
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Entree & readOn (Entree &) override
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
virtual void creer_tableau_distribue (const MD_Vector &, Array_base::Resize_Options=Array_base::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Additional Inherited Members
Protected Attributes inherited from Champ_Face_PolyMAC
Ref_Zone_VF ref_zone_vf_
IntTab fcl_
int fcl_init_ = 0
Protected Attributes inherited from Champ_Inc_base
Roue_ptr les_valeurs
Ref_Zone_Cl_dis ma_zone_cl_dis
fonc_calc_t fonc_calc_
int fonc_calc_init_ = 0
Ref_Objet_U obj_calc_
DoubleTab val_bord_
tabs_t deriv_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
: class Champ_Face_PolyMAC_P0
Champ correspondant a une inconnue decrite par ses tangentes aux faces duales (ligne amont-aval, type vitesse)
Les flux aux faces sont accessibles par les methodes valeurs_normales(), avec synchro automatique
Degres de libertes : composantes tangentielles aux faces duales
Definition at line 35 of file Champ_Face_PolyMAC_P0.h.
Constructor & Destructor Documentation
Champ_Face_PolyMAC_P0()
Champ_Face_PolyMAC_P0::Champ_Face_PolyMAC_P0 ()
Definition at line 37 of file Champ_Face_PolyMAC_P0.cpp.
~Champ_Face_PolyMAC_P0()
Champ_Face_PolyMAC_P0::~Champ_Face_PolyMAC_P0 ()
Definition at line 37 of file Champ_Face_PolyMAC_P0.cpp.
Member Function Documentation
affecter_()
Champ_base & Champ_Face_PolyMAC_P0::affecter_ (const Champ_base & ch) override virtual
Affectation d'un Champ generique (Champ_base) dans
un champ inconnue.
Returns
Champ_base&
Signification: le resultat de l'affectation (*this)
Contraintes:
Reimplemented from Champ_Face_PolyMAC.
Definition at line 90 of file Champ_Face_PolyMAC_P0.cpp.
{
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0,ref_zone_vf_.valeur());
  const DoubleVect& fs = zone.face_surfaces();
  const DoubleTab& nf = zone.face_normales(), &xv = zone.xv();
  DoubleTab& val = valeurs(), eval;
  if (sub_type(Champ_Fonc_reprise, ch))
    {
      for (int num_face=0; num_face<zone.nb_faces(); num_face++)
        val(num_face) = ch.valeurs()[num_face];
    }
  else
    {
      int f, n, N = val.line_size(), d, D = dimension, unif = sub_type(Champ_Uniforme, ch);
      if (unif) eval = ch.valeurs();
      else eval.resize(val.dimension_tot(0), N * D), ch.valeur_aux(xv,eval);
      for (f = 0; f < zone.nb_faces_tot(); f++)
        for (d = 0; d < D; d++)
          for (n = 0; n < N; n++)
            val(f, n) += eval(unif ? 0 : f, N * d + n) * nf(f, d) / fs(f);
      update_ve(val);
// copie dans toutes les cases
      valeurs().echange_espace_virtuel();
      for(int i=1; i<les_valeurs->nb_cases(); i++) les_valeurs[i].valeurs() = valeurs();
    }
  return *this;
}
References Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_Poly_base::face_normales(), Zone_VF::face_surfaces(), Champ_Inc_base::les_valeurs, TRUSTVect< _TYPE_ >::line_size(), Roue::nb_cases(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), ref_cast, Champ_Face_PolyMAC::ref_zone_vf_, TRUSTTab< _TYPE_ >::resize(), sub_type, update_ve(), Ref_Zone_VF::valeur(), Champ_base::valeur_aux(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Zone_VF::xv().
cree_instance()
Objet_U * Champ_Face_PolyMAC_P0::cree_instance () static
Definition at line 37 of file Champ_Face_PolyMAC_P0.cpp.
duplique()
int Champ_Face_PolyMAC_P0::duplique () const override virtual
Reimplemented from Champ_Face_PolyMAC.
Definition at line 37 of file Champ_Face_PolyMAC_P0.cpp.
fixer_nb_valeurs_nodales()
int Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales (int n) override virtual
Reimplemented from Champ_Face_PolyMAC.
Definition at line 50 of file Champ_Face_PolyMAC_P0.cpp.
{
// j'utilise le meme genre de code que dans Champ_Fonc_P0_base
// sauf que je recupere le nombre de faces au lieu du nombre d'elements
//
// je suis tout de meme etonne du code utilise dans
// Champ_Fonc_P0_base::fixer_nb_valeurs_nodales()
// pour recuperer la zone discrete...
  const Champ_Inc_base& self = ref_cast(Champ_Inc_base, *this);
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0,self.zone_dis_base());
  assert(n == zone.nb_faces() || n < 0);
// Probleme: nb_comp vaut dimension mais on ne veut qu'une dimension !!!
// HACK :
  int old_nb_compo = nb_compo_;
  if(nb_compo_ != 1) nb_compo_ /= dimension;
  /* variables : valeurs normales aux faces, puis valeurs aux elements par blocs -> pour que line_size() marche */
  creer_tableau_distribue(zone.md_vector_faces());
  nb_compo_ = old_nb_compo;
  return n;
}
References Champ_Inc_base::creer_tableau_distribue(), Objet_U::dimension, Zone_VF::md_vector_faces(), Field_base::nb_compo_, Zone_VF::nb_faces(), ref_cast, and Champ_base::zone_dis_base().
get_info()
const Type_info * Champ_Face_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Face_PolyMAC.
Definition at line 37 of file Champ_Face_PolyMAC_P0.cpp.
info()
const Type_info * Champ_Face_PolyMAC_P0::info () static
Definition at line 37 of file Champ_Face_PolyMAC_P0.cpp.
init_auxiliary_variables()
void Champ_Face_PolyMAC_P0::init_auxiliary_variables () override virtual
Reimplemented from Champ_Face_PolyMAC.
Definition at line 77 of file Champ_Face_PolyMAC_P0.cpp.
{
  const Zone_PolyMAC_P0& zone = ref_cast( Zone_PolyMAC_P0,ref_zone_vf_.valeur());
  for (int n = 0; n < nb_valeurs_temporelles(); n++)
    {
      DoubleTab& vals = futur(n);
      vals.set_md_vector(MD_Vector()); //on enleve le MD_Vector...
      vals.resize_dim0(zone.mdv_ch_face.valeur().get_nb_items_tot()); //...on dimensionne a la bonne taille...
      vals.set_md_vector(zone.mdv_ch_face); //...et on remet le bon MD_Vector
      update_ve(vals);
    }
}
References Champ_Inc_base::futur(), MD_Vector_base::get_nb_items_tot(), Zone_PolyMAC_P0::mdv_ch_face, Champ_Inc_base::nb_valeurs_temporelles(), ref_cast, Champ_Face_PolyMAC::ref_zone_vf_, TRUSTTab< _TYPE_ >::resize_dim0(), TRUSTTab< _TYPE_ >::set_md_vector(), update_ve(), MD_Vector::valeur(), and Ref_Zone_VF::valeur().
Referenced by Op_Diff_PolyMAC_P0_Face::completer(), Op_Grad_PolyMAC_P0_Face::completer(), and Masse_PolyMAC_P0_Face::completer().
init_ve2()
void Champ_Face_PolyMAC_P0::init_ve2 () const
< v_i[{f, -1 (interne) ou composante }] = indice
< v_i[i_v[f]] = f
Definition at line 140 of file Champ_Face_PolyMAC_P0.cpp.
{
#ifdef _COMPILE_AVEC_PGCC
// PL ToDo: rewrite code
  Cerr << "Internal error with nvc++: Internal error: read_memory_region: not all expected entries were read." << finl;
  Process::exit();
#else
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0,zone_vf());
  if (ve2d.dimension(0) || valeurs().get_md_vector() != zone.mdv_ch_face) return; //deja initialise ou pas de variables auxiliaires
  const DoubleVect& pf = zone.porosite_face(), &pe = zone.porosite_elem(), &fs = zone.face_surfaces(), &ve = zone.volumes();
  const DoubleTab& xp = zone.xp(), &xv = zone.xv(), &nf = zone.face_normales();
  const IntTab& f_e = zone.face_voisins(), &e_f = zone.elem_faces(), &e_s = zone.zone().les_elems(), &f_s = zone.face_sommets();
  int i, j, jb, k, e, f, s, d, db, D = dimension, nc, nl = D * (D + 1), nw, infoo=0, un = 1, rank;
  double eps = 1e-8, fac;
  const double *xf;
  init_fcl();
// position des points aux faces de bord : CG si interne ou Dirichlet, projection si Neumann
  DoubleTrav xfb(zone.nb_faces_tot(), D), ve2, ve2i, A, B, P, W(1);
  IntTrav pvt;
  ve2.set_smart_resize(1), A.set_smart_resize(1), B.set_smart_resize(1), P.set_smart_resize(1), W.set_smart_resize(1), pvt.set_smart_resize(1);
  for (f = 0; f < zone.nb_faces_tot(); f++)
    if (fcl_(f, 0) == 1 || fcl_(f, 0) == 2) //Neumann / Symetrie
      {
        double scal = zone.dot(&xv(f, 0), &nf(f, 0), &xp(e = f_e(f, 0), 0)) / (fs(f) * fs(f));
        for (d = 0; d < D; d++) xfb(f, d) = xp(e, d) + scal * nf(f, d);
      }
    else if (fcl_(f, 0))
      for (d = 0; d < D; d++) xfb(f, d) = xv(f, d); //Dirichlet
  /* connectivites som-elem et elem-elem */
  std::vector<std::set<int>> s_f(zone.zone().nb_som()), e_s_f(zone.nb_elem());
  for (f = 0; f < zone.nb_faces_tot(); f++)
    for (i = 0; i < f_s.dimension(1) && (s = f_s(f, i)) >= 0; i++)
      if (s < zone.zone().nb_som()) s_f[s].insert(f);
  for (e = 0; e < zone.nb_elem(); e++)
    for (i = 0; i < e_s.dimension(1) && (s = e_s(e, i)) >= 0; i++)
      for (auto &&fa : s_f[s]) e_s_f[e].insert(fa);
  ve2d.resize(1, 2), ve2d.set_smart_resize(1), ve2j.set_smart_resize(1), ve2bj.resize(0, 2), ve2bj.set_smart_resize(1);
  ve2c.set_smart_resize(1), ve2bc.set_smart_resize(1);
  std::map<std::array<int, 2>, int> v_i; //!< v_i[{f, -1 (interne) ou composante }] = indice
  std::vector<std::array<int, 2>> i_v; //!< v_i[i_v[f]] = f
  for (e = 0; e < zone.nb_elem(); e++, v_i.clear(), i_v.clear())
    {
      /* stencil : faces de l'element et de ses voisins par som-elem + toutes composantes a ses faces de bord */
      for (auto &&fa : e_s_f[e])
        if (!v_i.count({{ fa, -1 }})) v_i[ {{fa, -1}}] = i_v.size(), i_v.push_back({{fa, -1}});
      for (i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++)
        if (fcl_(f, 0))
          for (d = 0; d < D; d++)
            v_i[ {{f, d }}] = i_v.size(), i_v.push_back({{f, d}});
      /* coeffs de l'interpolation d'ordre 1, ponderations (comme dans Zone_PolyMAC_P0::{e,f}grad)  */
      ve2.resize(nc = i_v.size(), D), A.resize(nc, nl), B.resize(nc), P.resize(nc), pvt.resize(nc);
      for (ve2 = 0, i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++)
        for (fac = (e == f_e(f, 0) ? 1 : -1) * fs(f) / ve(e), j = v_i.at({{ f, -1 }}), d = 0; d < D; d++)
      ve2(j, d) += fac * (xv(f, d) - xp(e, d));
      for (i = 0; i < nc; i++) f = i_v[i][0], xf = i_v[i][1] < 0 ? &xv(f, 0) : &xfb(f, 0), P(i) = 1. / sqrt(zone.dot(xf, xf, &xp(e, 0), &xp(e, 0)));
      /* par composante : correction pour etre d'ordre 2 */
      for (d = 0; d < D; d++)
        {
          /* systeme A.x = b */
          for (B = 0, pvt = 0, i = 0; i < nc; i++)
            for (f = i_v[i][0], db = i_v[i][1], xf = db < 0 ? &xv(f, 0) : &xfb(f, 0), j = 0, jb = 0; j < D; j++)
              for (k = 0; k <= D; k++, jb++)
                {
                  fac = (db < 0 ? nf(f, j) / fs(f) : (db == j)) * (k < D ? xf[k] - xp(e, k) : 1);
                  A(i, jb) = fac * P(i);
                  if (k < D) B(jb) -= fac * ve2(i, d); //erreur de l'interp d'ordre 1 a corriger
                }
          /* x de norme L2 minimale par dgels */
          nw = -1,             F77NAME(dgelsy)(&nl, &nc, &un, &A(0, 0), &nl, &B(0), &nc, &pvt(0), &eps, &rank, &W(0), &nw, &infoo);
          W.resize(nw = W(0)), F77NAME(dgelsy)(&nl, &nc, &un, &A(0, 0), &nl, &B(0), &nc, &pvt(0), &eps, &rank, &W(0), &nw, &infoo);
          assert(infoo == 0);
          /* ajout dans ve2 */
          for (i = 0; i < nc; i++) ve2(i, d) += P(i) * B(i);
        }
      /* implicitation des CLs de Neumann / Symetrie */
      Matrice33 M(1, 0, 0, 0, 1, 0, 0, 0, 1), iM;
      for (i = 0; i < nc; i++)
        if (i_v[i][1] >= 0 && fcl_(i_v[i][0], 0) < 2)
          for (j = 0; j < D; j++)
            M(j, i_v[i][1]) -= ve2(i, j);
      Matrice33::inverse(M, iM);
      for (ve2i.resize(nc, D), i = 0; i < nc; i++)
        for (j = 0; j < D; j++)
          for (ve2i(i, j) = 0, k = 0; k < D; k++)
            ve2i(i, j) += iM(j, k) * ve2(i, k);
      /* stockage */
      for (d = 0; d < D; d++, ve2d.append_line(ve2c.size(), ve2bc.size()))
        for (i = 0; i < nc; i++)
          if (std::fabs(ve2i(i, d)) > 1e-6 && (i_v[i][1] < 0 || fcl_(i_v[i][0], 0) == 3))
            {
              i_v[i][1] < 0 ? ve2j.append_line(i_v[i][0])  : ve2bj.append_line(i_v[i][0], i_v[i][1]);
              (i_v[i][1] < 0 ? &ve2c : &ve2bc)->append_line(ve2i(i, d) * pf(i_v[i][0]) / pe(e));
            }
    }
  CRIMP(ve2d), CRIMP(ve2j), CRIMP(ve2bj), CRIMP(ve2c), CRIMP(ve2bc);
#endif
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_Poly_base::dot(), Zone_VF::elem_faces(), Process::exit(), Zone_Poly_base::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Champ_Face_PolyMAC::fcl_, finl, Champ_Face_PolyMAC::init_fcl(), Zone::les_elems(), Zone_PolyMAC_P0::mdv_ch_face, Zone_dis_base::nb_elem(), Zone_VF::nb_faces_tot(), Zone::nb_som(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), Champ_Inc_base::valeurs(), ve2bc, ve2bj, ve2c, ve2d, ve2j, Zone_VF::volumes(), Zone_VF::xp(), Zone_VF::xv(), Zone_dis_base::zone(), and Champ_Face_PolyMAC::zone_vf().
Referenced by update_ve2().
printOn()
Sortie & Champ_Face_PolyMAC_P0::printOn (Sortie & os) const override protected virtual
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Face_PolyMAC.
Definition at line 39 of file Champ_Face_PolyMAC_P0.cpp.
{
  os << que_suis_je() << " " << le_nom();
  return os;
}
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Face_PolyMAC_P0::readOn (Entree & is) override protected virtual
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Face_PolyMAC.
Definition at line 45 of file Champ_Face_PolyMAC_P0.cpp.
{
  return is;
}
self_cast() [1/2]
const Champ_Face_PolyMAC_P0 & Champ_Face_PolyMAC_P0::self_cast (const Objet_U & r) static
Definition at line 37 of file Champ_Face_PolyMAC_P0.cpp.
self_cast() [2/2]
Champ_Face_PolyMAC_P0 & Champ_Face_PolyMAC_P0::self_cast (Objet_U & r) static
Definition at line 37 of file Champ_Face_PolyMAC_P0.cpp.
taille_memoire()
unsigned Champ_Face_PolyMAC_P0::taille_memoire () const override virtual
Reimplemented from Champ_Face_PolyMAC.
Definition at line 37 of file Champ_Face_PolyMAC_P0.cpp.
trace()
DoubleTab & Champ_Face_PolyMAC_P0::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const override virtual
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
Reimplemented from Champ_Face_PolyMAC.
Definition at line 320 of file Champ_Face_PolyMAC_P0.cpp.
{
  assert(distant==0);
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0,zone_vf());
  if (valeurs().get_md_vector() != zone.mdv_ch_face) return Champ_Face_PolyMAC::trace(fr, x, t, distant);
  const bool vectoriel = (le_champ().nb_comp() > 1);
  const int dim = vectoriel ? dimension : 1, ne_tot = zone.nb_elem_tot(), nf_tot = zone.nb_faces_tot();
  const Front_VF& fr_vf = ref_cast(Front_VF, fr);
  const IntTab& face_voisins = zone.face_voisins();
  const DoubleTab& val = valeurs(t);
  for (int i = 0; i < fr_vf.nb_faces(); i++)
    {
      const int face = fr_vf.num_premiere_face() + i, elem = face_voisins(face, 0);
      for (int d = 0; d < dim; d++) x(i, d) = val(vectoriel ? nf_tot + ne_tot * d + elem : face);
    }
  return x;
}
References Objet_U::dimension, Zone_VF::face_voisins(), Champ_Face_PolyMAC::le_champ(), Zone_PolyMAC_P0::mdv_ch_face, Field_base::nb_comp(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Zone_VF::nb_faces_tot(), Front_VF::num_premiere_face(), ref_cast, Champ_Face_PolyMAC::trace(), Champ_Inc_base::valeurs(), vectoriel, and Champ_Face_PolyMAC::zone_vf().
update_ve()
void Champ_Face_PolyMAC_P0::update_ve (DoubleTab & val) const
Definition at line 121 of file Champ_Face_PolyMAC_P0.cpp.
{
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0,zone_vf());
  if (valeurs().get_md_vector() != zone.mdv_ch_face) return; //pas de variables auxiliaires -> rien a faire
  const DoubleVect& fs = zone.face_surfaces(), &ve = zone.volumes(), &pf = zone.porosite_face(), &pe = zone.porosite_elem();
  const DoubleTab& xp = zone.xp(), &xv = zone.xv();
  const IntTab& e_f = zone.elem_faces(), &f_e = zone.face_voisins();
  int e, f, j, d, D = dimension, n, N = val.line_size(), ne_tot = zone.nb_elem_tot(), nf_tot = zone.nb_faces_tot();
  double fac;
  for (e = 0; e < ne_tot; e++)
    {
      for (d = 0; d < D; d++)
        for (n = 0; n < N; n++) val(nf_tot + D * e + d, n) = 0;
      for (j = 0; j < e_f.dimension(1) && (f = e_f(e, j)) >= 0; j++)
        for (fac = (e == f_e(f, 0) ? 1 : -1) * pf(f) * fs(f) / (pe(e) * ve(e)), d = 0; d < D; d++)
          for (n = 0; n < N; n++) val(nf_tot + D * e + d, n) += fac * (xv(f, d) - xp(e, d)) * val(f, n);
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), TRUSTVect< _TYPE_ >::line_size(), Zone_PolyMAC_P0::mdv_ch_face, Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces_tot(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, Champ_Inc_base::valeurs(), Zone_VF::volumes(), Zone_VF::xp(), Zone_VF::xv(), and Champ_Face_PolyMAC::zone_vf().
Referenced by affecter_(), Masse_PolyMAC_P0_Face::corriger_solution(), init_auxiliary_variables(), and valeur_aux_elems_compo().
update_ve2()
void Champ_Face_PolyMAC_P0::update_ve2 (DoubleTab & val, int incr = 0) const
Definition at line 247 of file Champ_Face_PolyMAC_P0.cpp.
{
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0,zone_vf());
  if (valeurs().get_md_vector() != zone.mdv_ch_face) return; //pas de variables auxiliaires -> on sort
  const Conds_lim& cls = zone_Cl_dis().les_conditions_limites();
  int i, j, e, ed, d, D = dimension, n, N = val.line_size(), nf_tot = zone.nb_faces_tot();
  init_ve2(), init_fcl();
  for (e = 0, ed = 0, i = nf_tot; e < zone.nb_elem(); e++)
    for (d = 0; d < D; d++, ed++, i++)
      for (n = 0; n < N; n++)
        {
          /* partie "interne" */
          for (val(i, n) = 0, j = ve2d(ed, 0); j < ve2d(ed + 1, 0); j++)
            val(i, n) += ve2c(j) * val(ve2j(j), n);
          /* partie "faces de bord de Dirichlet" (sauf si on fait des increments) */
          if (!incr)
            for (j = ve2d(ed, 1); j < ve2d(ed + 1, 1); j++)
              if (sub_type(Dirichlet, cls[fcl_(ve2bj(j, 0), 1)].valeur()))
                val(i, n) += ve2bc(j) * ref_cast(Dirichlet, cls[fcl_(ve2bj(j, 0), 1)].valeur()).val_imp(fcl_(ve2bj(j, 0), 2), N * ve2bj(j, 1) + n);
        }
  val.echange_espace_virtuel();
}
References Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Champ_Face_PolyMAC::fcl_, Champ_Face_PolyMAC::init_fcl(), init_ve2(), Zone_Cl_dis::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Zone_PolyMAC_P0::mdv_ch_face, Zone_dis_base::nb_elem(), Zone_VF::nb_faces_tot(), ref_cast, sub_type, valeur(), Champ_Inc_base::valeurs(), ve2bc, ve2bj, ve2c, ve2d, ve2j, Champ_Inc_base::zone_Cl_dis(), and Champ_Face_PolyMAC::zone_vf().
Referenced by Masse_PolyMAC_P0_Face::corriger_solution().
v_norm()
double Champ_Face_PolyMAC_P0::v_norm (const DoubleTab & val, const DoubleTab & val_f, int e, int f, int k, int l, double * v_ext, double * dnv) const inline
Definition at line 62 of file Champ_Face_PolyMAC_P0.h.
  {
    const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0, zone_dis_base());
    int d, D = dimension, nf_tot = zone.nb_faces_tot();
    const DoubleTab& nf = zone.face_normales();
    const DoubleVect& fs = zone.face_surfaces();
    double scal = 0, vf = f >= 0 ? val_f(f, k) - (l >= 0 ? val_f(f, l) : 0) : 0, v_temp[3], *v = v_ext ? v_ext : v_temp;
    for (d = 0; d < D; d++) v[d] = val(nf_tot + D * e + d, k) - (l >= 0 ? val(nf_tot + D * e + d, l) : 0);
    if (f >= 0)
      for (d = 0, scal = zone.dot(v, &nf(f, 0)) / fs(f); d < D; d++) v[d] += (vf - scal) * nf(f, d) / fs(f);
    double nv = sqrt(zone.dot(v, v));
    if (dnv)
      for (d = 0; d < D; d++) dnv[d] = nv ? (v[d] - (f >= 0 ? vf * nf(f, d) / fs(f) : 0)) / nv : 0;
    if (dnv) dnv[3] = f >= 0 && nv ? vf / nv : 0;
    return nv;
  }
References Objet_U::dimension, Zone_Poly_base::dot(), Zone_Poly_base::face_normales(), Zone_VF::face_surfaces(), Zone_VF::nb_faces_tot(), ref_cast, and Champ_Face_PolyMAC::zone_dis_base().
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), and Portance_interfaciale_PolyMAC_P0::ajouter_blocs().
valeur_aux_elems()
DoubleTab & Champ_Face_PolyMAC_P0::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const override virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_Face_PolyMAC.
Definition at line 273 of file Champ_Face_PolyMAC_P0.cpp.
{
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0,zone_vf());
  if (valeurs().get_md_vector() != zone.mdv_ch_face) return Champ_Face_PolyMAC::valeur_aux_elems(positions, les_polys, val);
  const Champ_base& cha=le_champ();
  int nb_compo=cha.nb_comp(), nf_tot = zone.nb_faces_tot(), d, D = dimension, n, N = valeurs().line_size();
// XXX : TODO Check this assert (positions and not val)
  assert((positions.dimension(0) == les_polys.size())||(positions.dimension_tot(0) == les_polys.size()));
// assert((val.dimension(0) == les_polys.size())||(val.dimension_tot(0) == les_polys.size()));
  if (val.nb_dim() > 2)
    {
      Cerr << "Erreur TRUST dans Champ_Face_PolyMAC_P0::valeur_aux_elems()" << finl;
      Cerr << "Le DoubleTab val a plus de 2 entrees" << finl;
      Process::exit();
    }
  if (nb_compo == 1)
    {
      Cerr<<"Champ_Face_PolyMAC_P0::valeur_aux_elems"<<finl;
      Cerr <<"A scalar field cannot be of Champ_Face type." << finl;
      Process::exit();
    }
  for (int p = 0, e; p < les_polys.size(); p++)
    for (e = les_polys(p), d = 0; e < zone.nb_elem() && d < D; d++)
      for (n = 0; n < N; n++)
        val(p, N * d + n) = valeurs()(nf_tot + D * e + d, n);
  return val;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), Process::exit(), finl, Champ_Face_PolyMAC::le_champ(), TRUSTVect< _TYPE_ >::line_size(), Zone_PolyMAC_P0::mdv_ch_face, Field_base::nb_comp(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces_tot(), ref_cast, TRUSTVect< _TYPE_ >::size(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_Inc_base::valeurs(), and Champ_Face_PolyMAC::zone_vf().
valeur_aux_elems_compo()
DoubleVect & Champ_Face_PolyMAC_P0::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const override virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_Face_PolyMAC.
Definition at line 305 of file Champ_Face_PolyMAC_P0.cpp.
{
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0,zone_vf());
  if (valeurs().get_md_vector() != zone.mdv_ch_face) return Champ_Face_PolyMAC::valeur_aux_elems_compo(positions, polys, val, ncomp);
  int nf_tot = zone.nb_faces_tot(), D = dimension, N = valeurs().line_size();
  assert(val.size() == polys.size());
  DoubleTab vfe(valeurs());
  update_ve(vfe);
  for (int p = 0, e; p < polys.size(); p++) val(p) = (e = polys(p)) < 0 ? 0. : vfe.addr()[N * (nf_tot + D * polys(p)) + ncomp];
  return val;
}
References TRUSTArray< _TYPE_ >::addr(), Objet_U::dimension, TRUSTVect< _TYPE_ >::line_size(), Zone_PolyMAC_P0::mdv_ch_face, Zone_VF::nb_faces_tot(), ref_cast, TRUSTVect< _TYPE_ >::size(), update_ve(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), Champ_Inc_base::valeurs(), and Champ_Face_PolyMAC::zone_vf().
Member Data Documentation
info_obj
const Type_info Champ_Face_PolyMAC_P0::info_obj static
Definition at line 38 of file Champ_Face_PolyMAC_P0.h.
ve2bc
DoubleTab Champ_Face_PolyMAC_P0::ve2bc
Definition at line 56 of file Champ_Face_PolyMAC_P0.h.
Referenced by init_ve2(), and update_ve2().
ve2bj
IntTab Champ_Face_PolyMAC_P0::ve2bj
Definition at line 55 of file Champ_Face_PolyMAC_P0.h.
Referenced by init_ve2(), and update_ve2().
ve2c
DoubleTab Champ_Face_PolyMAC_P0::ve2c mutable
Definition at line 56 of file Champ_Face_PolyMAC_P0.h.
Referenced by init_ve2(), and update_ve2().
ve2d
IntTab Champ_Face_PolyMAC_P0::ve2d mutable
Definition at line 55 of file Champ_Face_PolyMAC_P0.h.
Referenced by init_ve2(), and update_ve2().
ve2j
IntTab Champ_Face_PolyMAC_P0::ve2j
Definition at line 55 of file Champ_Face_PolyMAC_P0.h.
Referenced by init_ve2(), and update_ve2().
The documentation for this class was generated from the following files:
src/PolyMAC/Champs/Champ_Face_PolyMAC_P0.h
src/PolyMAC/Champs/Champ_Face_PolyMAC_P0.cpp