TRUST: Traitement_particulier_NS_Brech_VEF Class Reference
Traitement_particulier_NS_Brech_VEF Class Reference
classe Traitement_particulier_Brech_VEF
Cette classe permet de faire les traitements particuliers
pour le calcul des flux pour le cas Brech :
#include <Traitement_particulier_NS_Brech_VEF.h>
Public Member Functions
~Traitement_particulier_NS_Brech_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Traitement_particulier_NS_Brech_VEF ()
void post_traitement_particulier (void) override
Entree & lire (Entree &) override
Public Member Functions inherited from Traitement_particulier_NS_VEF
Traitement_particulier_NS_VEF ()
~Traitement_particulier_NS_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_eqn (const Equation_base &) override
void preparer_calcul_particulier (void) override
virtual void traitement_particulier_debut_mettre_a_jour (double &)
virtual void traitement_particulier_fin_mettre_a_jour (double &)
void sauver_stat (void) const override
void reprendre_stat (void) override
void post_traitement_particulier (void) override
void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double) override
Entree & lire (Entree &) override
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
virtual int comprend_champ (const Motcle &mot) const
Public Member Functions inherited from Traitement_particulier_NS_base
Traitement_particulier_NS_base ()
~Traitement_particulier_NS_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_eqn (const Equation_base &)
virtual void preparer_calcul_particulier (void)=0
virtual void post_traitement_particulier (void)=0
virtual Entree & lire (Entree &is)=0
virtual void sauver_stat (void) const =0
virtual void reprendre_stat (void)=0
virtual void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double)=0
void creer_champ (const Motcle &) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Traitement_particulier_NS_Brech_VEF & self_cast (Objet_U &)
static const Traitement_particulier_NS_Brech_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_VEF
static Objet_U * cree_instance ()
static const Type_info * info ()
static Traitement_particulier_NS_VEF & self_cast (Objet_U &)
static const Traitement_particulier_NS_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_base
static const Type_info * info ()
static Traitement_particulier_NS_base & self_cast (Objet_U &)
static const Traitement_particulier_NS_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_VEF
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Traitement_particulier_NS_VEF
Sortie & printOn (Sortie &x) const override
Impression de l'equation sur un flot de sortie.
Simple appel a Equation_base::printOn(Sortie&).
Entree & readOn (Entree &) override
Lit les specifications de l'equation de Navier Stokes a
partir d'un flot d'entree.
Simple appel a Navier_Stokes_std::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Impression de l'equation sur un flot de sortie.
Simple appel a Equation_base::printOn(Sortie&).
Entree & readOn (Entree &) override
Lit les specifications de l'equation de Navier Stokes a
partir d'un flot d'entree.
Simple appel a Navier_Stokes_std::readOn(Entree&)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
Champ_Fonc_P1NC ch_ri
Champ_Fonc_P1NC ch_p
Protected Attributes inherited from Traitement_particulier_NS_base
Ref_Navier_Stokes_std mon_equation
Champs_compris champs_compris_
Private Member Functions
void calculer_terme_production_K (const Zone_VEF &, const Zone_Cl_VEF &, DoubleVect &, const DoubleTab &) const
void calculer_terme_destruction_K (const Zone_VEF &, const Zone_Cl_VEF &, DoubleVect &, const DoubleTab &, const DoubleVect &, const DoubleVect &) const
void post_traitement_particulier_calcul_flux ()
void post_traitement_particulier_Richardson ()
void post_traitement_particulier_calcul_pression ()
Private Attributes
DoubleTab R_loc
DoubleTab C_trans
DoubleVect r_int
DoubleVect r_out
DoubleVect delta_r
DoubleVect delta_teta
int c_flux
int nb
int c_Richardson
int c_pression
Detailed Description
classe Traitement_particulier_Brech_VEF
Cette classe permet de faire les traitements particuliers
pour le calcul des flux pour le cas Brech :
Definition at line 37 of file Traitement_particulier_NS_Brech_VEF.h.
Constructor & Destructor Documentation
~Traitement_particulier_NS_Brech_VEF()
Traitement_particulier_NS_Brech_VEF::~Traitement_particulier_NS_Brech_VEF ()
Definition at line 24 of file Traitement_particulier_NS_Brech_VEF.cpp.
Traitement_particulier_NS_Brech_VEF()
Traitement_particulier_NS_Brech_VEF::Traitement_particulier_NS_Brech_VEF ()
Definition at line 26 of file Traitement_particulier_NS_Brech_VEF.cpp.
{
  /*
    Noms& nom=champs_compris_.liste_noms_compris();
    nom.dimensionner(2);
    nom[0]="Pression_porosite";
    nom[1]="Richardson";
  */
}
Member Function Documentation
calculer_terme_destruction_K()
void Traitement_particulier_NS_Brech_VEF::calculer_terme_destruction_K (const Zone_VEF & zone_VEF, const Zone_Cl_VEF & zcl_VEF, DoubleVect & G, const DoubleTab & temper, const DoubleVect & beta, const DoubleVect & gravite) const private
Definition at line 706 of file Traitement_particulier_NS_Brech_VEF.cpp.
{
//
// G est discretise comme K et Eps i.e au centre des faces
//
// --> ----->
// G(face) = beta alpha_t(face) G . gradT(face)
//
  int nb_elem = zone_VEF.nb_elem();
  int nb_faces= zone_VEF.nb_faces();
  DoubleTrav u_teta(nb_faces,dimension);
  DoubleTrav gradient_elem(nb_elem,dimension);
  u_teta=0;
  gradient_elem=0;
// const Zone& la_zone=zone_VEF.zone();
// int nb_faces_elem = la_zone.nb_faces_elem();
// const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  int premiere_face_entier = zone_VEF.premiere_face_int();
  const DoubleVect& volumes = zone_VEF.volumes();
  int nb_faces_ = zone_VEF.nb_faces();
  int elem1,elem2,fac;
  DoubleVect coef(Objet_U::dimension);
// const IntTab& les_elem_faces = zone_VEF.elem_faces();
// Calcul du gradient de temperature :
// On traite les bords
  int n_bord;
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zcl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          for (fac=ndeb; fac<nfin; fac++)
            {
              elem1=face_voisins(fac,0);
              elem2=face_voisins(fac,1);
              for (int i=0; i<dimension; i++)
                {
                  gradient_elem(elem1,i) += 0.5*face_normales(fac,i)*temper(fac);
                  gradient_elem(elem2,i) -= 0.5*face_normales(fac,i)*temper(fac);
                }
            }
        }
      else
        {
          for (int fac2=ndeb; fac2<nfin; fac2++)
            {
              elem1=face_voisins(fac2,0);
              for (int i=0; i<dimension; i++)
                gradient_elem(elem1,i) += face_normales(fac2,i)*temper(fac2);
            }
        }
    }
// On traite les faces internes
  for (fac = premiere_face_entier ; fac<nb_faces_; fac++)
    {
      elem1=face_voisins(fac,0);
      elem2=face_voisins(fac,1);
      for (int i=0; i<dimension; i++)
        {
          gradient_elem(elem1,i) += face_normales(fac,i)*temper(fac);
          gradient_elem(elem2,i) -= face_normales(fac,i)*temper(fac);
        }
    }
  for (int elem=0; elem<nb_elem; elem++)
    for (int i=0; i<dimension; i++)
      gradient_elem(elem,i) /= volumes(elem);
// Calcul de u_teta :
// On traite les bords
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zcl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          for (fac=ndeb; fac<nfin; fac++)
            {
              elem1 = face_voisins(fac,0);
              elem2 = face_voisins(fac,1);
              double a=volumes(elem1)/(volumes(elem1)+volumes(elem2));
              double b=volumes(elem2)/(volumes(elem1)+volumes(elem2));
              for (int i=0; i<dimension; i++)
                u_teta(fac,i)=a*beta(elem1)*gradient_elem(elem1,i)
                              +b*beta(elem2)*gradient_elem(elem2,i);
            }
        }
      else
        {
          for (fac=ndeb; fac< nfin; fac++)
            {
              elem1 = face_voisins(fac,0);
              for (int i=0; i<dimension; i++)
                u_teta(fac,i)=beta(elem1)*gradient_elem(elem1,i);
            }
        }
    }
  for (; fac<nb_faces_; fac++)
    {
      elem1 = face_voisins(fac,0);
      elem2 = face_voisins(fac,1);
      double a=volumes(elem1)/(volumes(elem1)+volumes(elem2));
      double b=volumes(elem2)/(volumes(elem1)+volumes(elem2));
      for (int i=0; i<dimension; i++)
        u_teta(fac,i)=a*beta(elem1)*gradient_elem(elem1,i)+b*beta(elem2)*gradient_elem(elem2,i);
    }
// ------->  ------>
// Calcul de gravite . u_teta
//
  G = 0;
  for (fac=0; fac< nb_faces_; fac++)
    {
      if (dimension == 2)
        G[fac] = gravite(0)*u_teta(fac,0) + gravite(1)*u_teta(fac,1);
      else if (dimension == 3)
        G[fac] = gravite(0)*u_teta(fac,0) + gravite(1)*u_teta(fac,1) + gravite(2)*u_teta(fac,2);
    }
}
References Objet_U::dimension, Zone_VEF::face_normales(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_elem(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), and Zone_VF::volumes().
Referenced by post_traitement_particulier_Richardson().
calculer_terme_production_K()
void Traitement_particulier_NS_Brech_VEF::calculer_terme_production_K (const Zone_VEF & zone_VEF, const Zone_Cl_VEF & zcl_VEF, DoubleVect & P, const DoubleTab & vit) const private
Definition at line 527 of file Traitement_particulier_NS_Brech_VEF.cpp.
{
// P est discretise comme K et Eps i.e au centre des elements
//
// P(elem) = -(2/3)*k(i)*div_U(i) + nu_t(i) * F(u,v,w)
//
// 2          2          2
// avec F(u,v,w) = 2[(du/dx)  + (dv/dy)  + (dw/dz) ] +
//
// 2               2               2
// (du/dy+dv/dx) + (du/dz+dw/dx) + (dw/dy+dv/dz)
//
// Rqs: On se place dans le cadre incompressible donc on neglige
// le terme (2/3)*k(i)*div_U(i)
  P= 0;
// Calcul de F(u,v,w):
// const Zone& zone = zone_VEF.zone();
  int nb_elem = zone_VEF.nb_elem();
// const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
// const int nb_faces = zone_VEF.nb_faces();
  const DoubleVect& volumes = zone_VEF.volumes();
// int premiere_face_entier = zone_VEF.premiere_face_int();
// const IntTab& les_Polys = zone.les_elems();
  int fac=0, poly1, poly2;
  int nb_faces_ = zone_VEF.nb_faces();
// (du/dx du/dy dv/dx dv/dy ...) pour un poly
//
// <
// calcul des gradients;  < [ Ujp*np/vol(j) ]
// j
//
  int n_bord;
  DoubleTab gradient_elem(nb_elem,dimension,dimension);
  Champ_P1NC::calcul_gradient(vit,gradient_elem,zcl_VEF);
// On a les gradient_elem par elements
//
  double du_dx;
  double du_dy;
  double du_dz;
  double dv_dx;
  double dv_dy;
  double dv_dz;
  double dw_dx;
  double dw_dy;
  double dw_dz;
//
// Calcul des du/dx dv/dy et des derivees croisees sur les faces de chaque elements dans le cas 2D
//
// Boucle sur les bords pour traiter les faces de bord
// en distinguant le cas periodicite
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zcl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          for (fac=ndeb; fac<nfin; fac++)
            {
              poly1 = face_voisins(fac,0);
              poly2 = face_voisins(fac,1);
              double a=volumes(poly1)/(volumes(poly1)+volumes(poly2));
              double b=volumes(poly2)/(volumes(poly1)+volumes(poly2));
              du_dx =a*gradient_elem(poly1,0,0) + b*gradient_elem(poly2,0,0);
              du_dy =a*gradient_elem(poly1,0,1) + b*gradient_elem(poly2,0,1);
              dv_dx =a*gradient_elem(poly1,1,0) + b*gradient_elem(poly2,1,0);
              dv_dy =a*gradient_elem(poly1,1,1) + b*gradient_elem(poly2,1,1);
// Determination du terme de production
              P(fac) = ( 2*(du_dx *du_dx  + dv_dy *dv_dy) + ((du_dy+dv_dx)*(du_dy+dv_dx)));
              if (dimension == 3)
                {
                  du_dz=a*gradient_elem(poly1,0,2) + b*gradient_elem(poly2,0,2);
                  dv_dz=a*gradient_elem(poly1,1,2) + b*gradient_elem(poly2,1,2);
                  dw_dx=a*gradient_elem(poly1,2,0) + b*gradient_elem(poly2,2,0);
                  dw_dy=a*gradient_elem(poly1,2,1) + b*gradient_elem(poly2,2,1);
                  dw_dz=a*gradient_elem(poly1,2,2) + b*gradient_elem(poly2,2,2);
// Determination du terme de production
                  P(fac) = (2*( du_dx*du_dx + dv_dy*dv_dy + dw_dz*dw_dz )
                            + ( (du_dy+dv_dx)*(du_dy+dv_dx)
                                +   (du_dz+dw_dx)*(du_dz+dw_dx)
                                +   (dw_dy+dv_dz)*(dw_dy+dv_dz)));
                }
            }
        }
      else
        {
          for (fac=ndeb; fac<nfin; fac++)
            {
              poly1 = face_voisins(fac,0);
              du_dx=gradient_elem(poly1,0,0);
              du_dy=gradient_elem(poly1,0,1);
              dv_dx=gradient_elem(poly1,1,0);
              dv_dy=gradient_elem(poly1,1,1);
// Determination du terme de production
              P(fac) = ( 2*(du_dx*du_dx + dv_dy*dv_dy) + ((du_dy+dv_dx)*(du_dy+dv_dx)));
              if (dimension == 3)
                {
                  du_dz=gradient_elem(poly1,0,2);
                  dv_dz=gradient_elem(poly1,1,2);
                  dw_dx=gradient_elem(poly1,2,0);
                  dw_dy=gradient_elem(poly1,2,1);
                  dw_dz=gradient_elem(poly1,2,2);
// Determination du terme de production
                  P(fac) = (2*( du_dx*du_dx + dv_dy*dv_dy + dw_dz*dw_dz )
                            + ( (du_dy+dv_dx)*(du_dy+dv_dx)
                                +   (du_dz+dw_dx)*(du_dz+dw_dx)
                                +   (dw_dy+dv_dz)*(dw_dy+dv_dz)));
                }
            }
        }
    }
// Traitement des faces internes
  for (; fac<nb_faces_; fac++)
    {
      poly1 = face_voisins(fac,0);
      poly2 = face_voisins(fac,1);
      double a=volumes(poly1)/(volumes(poly1)+volumes(poly2));
      double b=volumes(poly2)/(volumes(poly1)+volumes(poly2));
      du_dx=a*gradient_elem(poly1,0,0) + b*gradient_elem(poly2,0,0);
      du_dy=a*gradient_elem(poly1,0,1) + b*gradient_elem(poly2,0,1);
      dv_dx=a*gradient_elem(poly1,1,0) + b*gradient_elem(poly2,1,0);
      dv_dy=a*gradient_elem(poly1,1,1) + b*gradient_elem(poly2,1,1);
// Determination du terme de production
      P(fac) = ( 2*(du_dx*du_dx + dv_dy*dv_dy) + ((du_dy+dv_dx)*(du_dy+dv_dx)));
      if (dimension == 3)
        {
          du_dz=a*gradient_elem(poly1,0,2) + b*gradient_elem(poly2,0,2);
          dv_dz=a*gradient_elem(poly1,1,2) + b*gradient_elem(poly2,1,2);
          dw_dx=a*gradient_elem(poly1,2,0) + b*gradient_elem(poly2,2,0);
          dw_dy=a*gradient_elem(poly1,2,1) + b*gradient_elem(poly2,2,1);
          dw_dz=a*gradient_elem(poly1,2,2) + b*gradient_elem(poly2,2,2);
// Determination du terme de production
          P(fac) = (2*( du_dx*du_dx + dv_dy*dv_dy + dw_dz*dw_dz )
                    + ( (du_dy+dv_dx)*(du_dy+dv_dx)
                        +   (du_dz+dw_dx)*(du_dz+dw_dx)
                        +   (dw_dy+dv_dz)*(dw_dy+dv_dz)));
        }
    }
}
References Champ_P1NC::calcul_gradient(), Objet_U::dimension, Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_elem(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), and Zone_VF::volumes().
Referenced by post_traitement_particulier_Richardson().
cree_instance()
Objet_U * Traitement_particulier_NS_Brech_VEF::cree_instance () static
Definition at line 24 of file Traitement_particulier_NS_Brech_VEF.cpp.
duplique()
int Traitement_particulier_NS_Brech_VEF::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Traitement_particulier_NS_Brech_VEF.cpp.
get_info()
const Type_info * Traitement_particulier_NS_Brech_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Definition at line 24 of file Traitement_particulier_NS_Brech_VEF.cpp.
info()
const Type_info * Traitement_particulier_NS_Brech_VEF::info () static
Definition at line 24 of file Traitement_particulier_NS_Brech_VEF.cpp.
lire()
Entree & Traitement_particulier_NS_Brech_VEF::lire (Entree & is) override virtual
Implements Traitement_particulier_NS_base.
Definition at line 95 of file Traitement_particulier_NS_Brech_VEF.cpp.
{
  Motcle accouverte = "{" , accfermee = "}" ;
  Motcle motbidon, motlu;
  c_flux = 0 ;
  c_Richardson = 0 ;
  c_pression = 0 ;
  is >> motbidon ;
  Motcles les_mots(3);
  {
    les_mots[0] = "calcul_flux";
    les_mots[1] = "Richardson";
    les_mots[2] = "Pression_porosite";
  }
  if (motbidon == accouverte)
    {
// is >> motlu;
      while(motlu != accfermee)
        {
          is >> motlu;
          int rang=les_mots.search(motlu);
          switch(rang)
            {
            case 0 :
              {
                is >> motbidon ;
                if (motbidon != accouverte)
                  {
                    Cerr << " on attent { et pas " << motbidon << finl ;
                  }
                is >> nb ;
                C_trans.resize(nb,3) ;
                R_loc.resize(nb,3) ;
                r_int.resize(nb) ;
                r_out.resize(nb) ;
                delta_r.resize(nb) ;
                delta_teta.resize(nb);
                for (int i=0; i<nb; i++)
                  {
                    Cerr << " Lire plan de coupe en x " << finl;
                    is >> R_loc(i,0) ;
                    is >> R_loc(i,1) ;
                    is >> R_loc(i,2) ;
                    is >> C_trans(i,0) ;
                    is >> C_trans(i,1) ;
                    is >> C_trans(i,2) ;
                    is >> r_int(i);
                    is >> r_out(i);
                    is >> delta_r(i);
                    is >> delta_teta(i) ;
                  }
                c_flux = 1 ;
                is >> motbidon ;
                if (motbidon != accfermee)
                  {
                    Cerr << " on attent } et pas " << motbidon << finl ;
                  }
                break ;
              }
            case 1 :
              {
                Cerr << " Lire Richardson " << finl;
                const Zone_dis_base& zdis=mon_equation->inconnue().zone_dis_base();
                const Zone_VEF& zone_VEF=ref_cast(Zone_VEF, zdis);
// const Probleme_base& pb = mon_equation->probleme();
                const int nb_faces = zone_VEF.nb_faces() ;
                ch_ri.associer_zone_dis_base(zdis);
                ch_ri.nommer("Richardson");
                ch_ri.fixer_nb_comp(1);
                ch_ri.fixer_nb_valeurs_nodales(nb_faces);
                ch_ri.fixer_unite("-");
                c_Richardson = 1 ;
                champs_compris_.ajoute_champ(ch_ri);
                break ;
              }
            case 2 :
              {
                Cerr << " Lire Pression_porosite " << finl;
                const Zone_dis_base& zdis=mon_equation->inconnue().zone_dis_base();
                const Zone_VEF& zone_VEF=ref_cast(Zone_VEF, zdis);
// const Probleme_base& pb = mon_equation->probleme();
                const int nb_elem = zone_VEF.nb_elem() ;
                ch_p.associer_zone_dis_base(zdis);
                ch_p.nommer("Pression_porosite");
                ch_p.fixer_nb_comp(1);
                ch_p.fixer_nb_valeurs_nodales(nb_elem);
                ch_p.fixer_unite("Pa.m3/kg");
                c_pression = 1 ;
                champs_compris_.ajoute_champ(ch_p);
                break ;
              }
            default :
              {
                if (motlu == accfermee)
                  {
                    break ;
                  }
                else
                  {
                    Cerr << "Erreur dans la lecture de Traitement_particulier_Brech_VEF" << finl;
                    Cerr << "Les mots cles possibles sont : calcul_flux ou Richardson " << finl;
                    Cerr << "Vous avez lu :" << motlu << finl;
                    exit();
                    break;
                  }
              }
            }
        }
      is >> motlu;
      if (motlu != accfermee)
        {
          Cerr << "Erreur dans la lecture de Traitement_particulier_NS_Brech_VEF 1 ";
          Cerr << "On attendait une } et pas " << motlu << finl;
          exit();
        }
// is >> motlu;
// if (motlu != accfermee)
// {
// Cerr << "Erreur dans la lecture de Traitement_particulier_NS_Brech_VEF 2 ";
// Cerr << "On attendait une } et pas " << motlu << finl;
// exit();
// }
// is >> motlu;
// if (motlu != accfermee)
// {
// Cerr << "Erreur dans la lecture de Traitement_particulier_NS_Brech_VEF 3 ";
// Cerr << "On attendait une } et pas " << motlu << finl;
// exit();
// }
    }
  return is;
}
References Champs_compris::ajoute_champ(), Champ_Fonc_P1NC::associer_zone_dis_base(), c_flux, c_pression, c_Richardson, C_trans, Cerr, ch_p, ch_ri, Traitement_particulier_NS_base::champs_compris_, delta_r, delta_teta, Process::exit(), finl, Field_base::fixer_nb_comp(), Champ_Fonc_P1NC::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Navier_Stokes_std::inconnue(), Traitement_particulier_NS_base::mon_equation, nb, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Field_base::nommer(), r_int, R_loc, r_out, ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), Motcles::search(), and Champ_Inc::zone_dis_base().
post_traitement_particulier()
void Traitement_particulier_NS_Brech_VEF::post_traitement_particulier (void) inline override virtual
Implements Traitement_particulier_NS_base.
Definition at line 256 of file Traitement_particulier_NS_Brech_VEF.cpp.
{
  if (c_flux == 1 ) post_traitement_particulier_calcul_flux() ;
  if (c_Richardson == 1 ) post_traitement_particulier_Richardson() ;
  if (c_pression == 1 ) post_traitement_particulier_calcul_pression() ;
}
References c_flux, c_pression, c_Richardson, post_traitement_particulier_calcul_flux(), post_traitement_particulier_calcul_pression(), and post_traitement_particulier_Richardson().
post_traitement_particulier_calcul_flux()
void Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux () private
Definition at line 264 of file Traitement_particulier_NS_Brech_VEF.cpp.
{
  for (int ii =0; ii<nb; ii++)
    {
      int taille = 1 ;
      DoubleTab coord_trace (taille,3) ;
      DoubleTab Surf_trace(taille,3) ;
      DoubleTab valeurs_(taille,3) ;
// Modifs VB pour prise en compte rho et calcul du flux enthalpique + Tmoy
      REF(Champ_base) rch1 ;
      REF(Champ_Inc_base) l_inco ;
      const Probleme_base& pb = mon_equation->probleme();
      /*
        pb.a_pour_Champ_Inc("Temperature", rch1 ) ;
        l_inco = ref_cast(Champ_Inc_base, rch1.valeur()) ;
        const Champ_Inc_base& temp = l_inco.valeur();
      */
      rch1 = pb.get_champ("Temperature");
      l_inco = ref_cast(Champ_Inc_base, rch1.valeur()) ;
      const Champ_Inc_base& temp = l_inco.valeur();
      DoubleTab temper_(taille,1);
      DoubleTab rho_(taille,1) ;
      DoubleTab cp_(taille,1) ;
// Fin Modifs VB
//
      double rad, teta ;
      double dr    = ( r_out(ii) - r_int(ii) ) /delta_r(ii) ;
      double dteta = 2.*3.14159/delta_teta(ii) ;
      taille = (int)(delta_r(ii)) * (int)(delta_teta(ii)) ;
      coord_trace.resize(taille,3) ;
      Surf_trace.resize(taille,3) ;
      valeurs_.resize(taille,3);
// Modifs VB pour prise en compte rho et calcul du flux enthalpique + Tmoy
      rho_.resize(taille,1) ;
      temper_.resize(taille,1);
      cp_.resize(taille,1);
// Fin Modifs VB
      double a,b,c ;
// Modifs VB pour calculer le flux sur une face inclinee
// anglex est l'angle que fait la normale a la face par rapport a l'axe des x (angle aigu)
      double anglex = acos(C_trans(ii,0)/sqrt( C_trans(ii,0) * C_trans(ii,0)
                                               + C_trans(ii,1) * C_trans(ii,1)
                                               + C_trans(ii,2) * C_trans(ii,2) )) ;
// Fin Modifs VB
      int i =-1 ;
      for ( rad = (r_int(ii)+(dr/2.)) ; rad < r_out(ii) ; rad += dr )
        for (teta = dteta/2. ; teta < 2.*3.14159 ; teta += dteta )
          {
            i++ ;
// Modifs VB pour calculer le flux sur une face inclinee
// a = 0. ;
// b = rad * cos(teta) ;
            a = - rad * cos(teta) * sin(anglex) ;
            b =   rad * cos(teta) * cos(anglex) ;
// Fin Modifs VB
            c = rad * sin(teta) ;
            coord_trace(i,0) = a + R_loc(ii,0) ;
            coord_trace(i,1) = b + R_loc(ii,1) ;
            coord_trace(i,2) = c + R_loc(ii,2) ;
            double ra = (dr/2.+rad) * (dr/2.+rad) ;
            double ri = (rad - (dr/2.))* (rad - (dr/2.)) ;
            Surf_trace(i,0) = 3.14159 * (ra -ri) / delta_teta(ii) ;
          }
      double flux_pos = 0. ;
      double flux_neg = 0. ;
      double flux ;
// Modifs VB pour prise en compte rho et calcul du flux enthalpique + Tmoy
      double tempmoy = 0. ;
      double massvol = 0. ;
      double fluxE_pos = 0. ;
      double fluxE_neg = 0. ;
      double fluxE ;
// fin modifs VB
      const Zone_dis_base& zdis=mon_equation->inconnue().zone_dis_base();
      const Zone& zone=zdis.zone();
      IntVect les_polys(coord_trace.dimension(0));
      zone.chercher_elements(coord_trace, les_polys);
      mon_equation->inconnue()->valeur_aux_elems(coord_trace, les_polys, valeurs_);
// Modifs VB pour prise en compte rho et calcul du flux enthalpique + Tmoy
      mon_equation->fluide().masse_volumique()->valeur_aux_elems(coord_trace, les_polys, rho_);
      mon_equation->fluide().capacite_calorifique()->valeur_aux_elems(coord_trace, les_polys, cp_);
      temp.valeur_aux_elems(coord_trace, les_polys, temper_);
// Fin Modifs VB
// On annulle la partie virtuelle
      for (i=0 ; i<taille; i++)
        if (les_polys(i)>=zone.nb_elem())
          {
            for (int k=0; k<dimension; k++)
              valeurs_(i,k)=0;
// Modifs VB pour prise en compte rho et calcul du flux enthalpique + Tmoy
            rho_(i)=0.;
            temper_(i)=0.;
            cp_(i)=0.;
          }
// Fin Modifs VB
      for (i=0 ; i<taille; i++ )
        {
// Modifs VB pour prise en compte rho et calcul du flux enthalpique + Tmoy
// flux = valeurs_(i,0)*Surf_trace(i,0) ;
          massvol += rho_(i) ;
          tempmoy += temper_(i) ;
          flux  = ( valeurs_(i,0)*cos(anglex) + valeurs_(i,1)*sin(anglex) )
                  *   Surf_trace(i,0)*rho_(i) ;
          fluxE = ( valeurs_(i,0)*cos(anglex) + valeurs_(i,1)*sin(anglex) )
                  *   Surf_trace(i,0)*rho_(i)*cp_(i)*temper_(i) ;
          flux=Process::mp_sum(flux);
          fluxE=Process::mp_sum(fluxE);
          if ( flux > 0. ) flux_pos += flux ;
          if ( flux < 0. ) flux_neg += flux ;
          if ( fluxE > 0. ) fluxE_pos += fluxE ;
          if ( fluxE < 0. ) fluxE_neg += fluxE ;
        }
      tempmoy=Process::mp_sum(tempmoy);
      massvol=Process::mp_sum(massvol);
      tempmoy /= taille ;
      massvol /= taille ;
      if (je_suis_maitre())
        {
          Cout << finl ;
          Cout << " ----------------------- " << finl ;
          Cout << " Traitement_particulier flux en x (Plan Oyz) a: "<<  R_loc(ii,0) << " "
               <<  R_loc(ii,1) << " "
               <<  R_loc(ii,2) << finl ;
          Cout << " angle de la normale du plan par rapport a x = " << anglex/3.1415*180. << " (deg) " << finl ;
          Cout << " flux_pos = " << flux_pos << " flux_neg = " << flux_neg << " (kg/s) " << finl ;
          Cout << " fluxEnthalpique_pos = " << fluxE_pos << " fluxEnthalpique_neg = " << fluxE_neg << " (Watts) " << finl ;
          Cout << " masse volumique moyenne sur le plan de coupe : " << massvol << finl ;
          Cout << " temperature moyenne     sur le plan de coupe : " << tempmoy << finl ;
        }
// Fin Modifs VB
    }
}
References C_trans, Milieu_base::capacite_calorifique(), Zone::chercher_elements(), Cout, delta_r, delta_teta, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, finl, Navier_Stokes_std::fluide(), Probleme_base::get_champ(), Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Milieu_base::masse_volumique(), Traitement_particulier_NS_base::mon_equation, Process::mp_sum(), nb, Zone::nb_elem(), Equation_base::probleme(), r_int, R_loc, r_out, REF, ref_cast, TRUSTTab< _TYPE_ >::resize(), Champ::valeur_aux_elems(), Champ_base::valeur_aux_elems(), Zone_dis_base::zone(), and Champ_Inc::zone_dis_base().
Referenced by post_traitement_particulier().
post_traitement_particulier_calcul_pression()
void Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression () private
< car div =-B
Definition at line 466 of file Traitement_particulier_NS_Brech_VEF.cpp.
{
  const Zone_VEF& zvef=ref_cast(Zone_VEF, mon_equation->zone_dis().valeur());
  const DoubleVect& porosite_face = zvef.porosite_face();
  int i,comp;
  int nb_face = zvef.nb_faces();
// Champ_Inc la_pression = mon_equation->pression();
// Champ_Inc la_vitesse =  mon_equation->vitesse();
  Operateur_Div divergence = mon_equation->operateur_divergence();
  Operateur_Grad gradient = mon_equation->operateur_gradient();
  SolveurSys solveur_pression_ = mon_equation->solveur_pression();
  DoubleTab& pression=mon_equation->pression().valeurs();
  DoubleTab& vitesse=mon_equation->vitesse().valeurs();
// DoubleTrav gradP(la_vitesse.valeurs());
// DoubleTrav gradP(vitesse);
// DoubleTrav inc_pre(pression);
  DoubleTab gradP(vitesse);
  DoubleTab inc_pre(pression);
// DoubleVect& inc_pre = ch_p.valeurs();
  inc_pre  = 0. ;
// DoubleTrav secmem(pression);
  DoubleTab secmem(pression);
  gradient.calculer(mon_equation->pression().valeurs(),gradP);
// gradient.calculer(la_pression,gradP);
// Cerr << "gradP " << gradP << finl;
// on veut BM-1Bt(psi*Pression)
  mon_equation->solv_masse().appliquer(gradP);
// DoubleTrav grad_temp(la_vitesse.valeurs());
// DoubleTrav grad_temp(vitesse);
  DoubleTab grad_temp(vitesse);
  for(i=0; i<nb_face; i++)
    {
      for (comp=0; comp<dimension; comp++)
        grad_temp(i,comp) = gradP(i,comp)/porosite_face(i);
    }
  divergence.calculer(grad_temp, secmem);
  secmem *= -1; //!< car div =-B
  solveur_pression_.resoudre_systeme(mon_equation->matrice_pression().valeur(),secmem, inc_pre);
// solveur_pression_.resoudre_systeme(mon_equation->matrice_pression().valeur(),secmem, inc_pre, la_pression.valeur());
// Cerr << "la pression " << pression << finl;
// Cerr << "inc_pre " << inc_pre << finl;
  DoubleVect& la_pression_porosite = ch_p.valeurs();
  la_pression_porosite = inc_pre ;
  Cerr << "la_pression " << mon_equation->pression().valeurs() << finl;
  Cerr << "ch_p.valeurs() " << ch_p.valeurs() << finl;
}
References Solveur_Masse::appliquer(), Operateur_Div::calculer(), Operateur_Grad::calculer(), Cerr, ch_p, Objet_U::dimension, finl, Navier_Stokes_std::matrice_pression(), Traitement_particulier_NS_base::mon_equation, Zone_VF::nb_faces(), Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::operateur_gradient(), Zone_VF::porosite_face(), Navier_Stokes_std::pression(), ref_cast, SolveurSys::resoudre_systeme(), Equation_base::solv_masse(), Navier_Stokes_std::solveur_pression(), Deriv_Zone_dis_base::valeur(), Deriv_Matrice_Base::valeur(), Champ_Don_base::valeurs(), Champ_Inc::valeurs(), Navier_Stokes_std::vitesse(), and Equation_base::zone_dis().
Referenced by post_traitement_particulier().
post_traitement_particulier_Richardson()
void Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson () private
Definition at line 413 of file Traitement_particulier_NS_Brech_VEF.cpp.
{
  const Zone_dis& zdis=mon_equation->zone_dis();
  const Zone_VEF& zone_VEF=ref_cast(Zone_VEF, zdis.valeur());
  const Zone_Cl_VEF& zone_Cl_VEF = ref_cast(Zone_Cl_VEF,mon_equation->zone_Cl_dis().valeur() );
  REF(Champ_base) rch1 ;
  REF(Champ_Inc_base) l_inco ;
  const Probleme_base& pb = mon_equation->probleme();
  /*
    pb.a_pour_Champ_Inc("Temperature", rch1 ) ;
    l_inco = ref_cast(Champ_Inc_base, rch1.valeur()) ;
  */
  rch1 = pb.get_champ("Temperature");
  l_inco = ref_cast(Champ_Inc_base, rch1.valeur()) ;
  const Champ_Inc_base& temp = l_inco.valeur();
  const DoubleTab& temperature = temp.valeurs();
  const DoubleTab&  vitesse = mon_equation->inconnue().valeurs();
  const DoubleVect& gravite = mon_equation->fluide().gravite().valeurs();
  const DoubleVect& beta     = mon_equation->fluide().beta_t().valeurs();
  const int nb_faces = zone_VEF.nb_faces();
  DoubleVect P(nb_faces) ;
  DoubleVect G(nb_faces) ;
  DoubleVect beta_i(nb_faces) ;
  beta_i = beta(0) ;
  calculer_terme_production_K( zone_VEF, zone_Cl_VEF,
                               P, vitesse);
  calculer_terme_destruction_K( zone_VEF, zone_Cl_VEF,
                                G, temperature,
                                beta_i, gravite) ;
  DoubleVect&  richard_loc = ch_ri.valeurs();
  richard_loc = 0. ;
  for ( int i=0; i<nb_faces; i++ )
    {
      if (std::fabs (P[i]) > 1.e-9 )richard_loc [i] = -G[i]/P[i] ;
      else richard_loc [i] = 0. ;
    }
  ch_ri.changer_temps(mon_equation->inconnue().temps());
}
References Milieu_base::beta_t(), calculer_terme_destruction_K(), calculer_terme_production_K(), ch_ri, Champ_base::changer_temps(), Navier_Stokes_std::fluide(), Probleme_base::get_champ(), Milieu_base::gravite(), Navier_Stokes_std::inconnue(), Traitement_particulier_NS_base::mon_equation, Zone_VF::nb_faces(), Equation_base::probleme(), REF, ref_cast, Champ_Inc::temps(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_Don::valeurs(), Champ_Don_base::valeurs(), Champ_Inc::valeurs(), Champ_Inc_base::valeurs(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
Referenced by post_traitement_particulier().
printOn()
Sortie & Traitement_particulier_NS_Brech_VEF::printOn (Sortie & is) const override protected virtual
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Definition at line 49 of file Traitement_particulier_NS_Brech_VEF.cpp.
{
  return is;
}
readOn()
Entree & Traitement_particulier_NS_Brech_VEF::readOn (Entree & is) override protected virtual
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Definition at line 69 of file Traitement_particulier_NS_Brech_VEF.cpp.
{
  return is;
}
self_cast() [1/2]
const Traitement_particulier_NS_Brech_VEF & Traitement_particulier_NS_Brech_VEF::self_cast (const Objet_U & r) static
Definition at line 24 of file Traitement_particulier_NS_Brech_VEF.cpp.
self_cast() [2/2]
Traitement_particulier_NS_Brech_VEF & Traitement_particulier_NS_Brech_VEF::self_cast (Objet_U & r) static
Definition at line 24 of file Traitement_particulier_NS_Brech_VEF.cpp.
taille_memoire()
unsigned Traitement_particulier_NS_Brech_VEF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Traitement_particulier_NS_Brech_VEF.cpp.
Member Data Documentation
c_flux
int Traitement_particulier_NS_Brech_VEF::c_flux private
Definition at line 77 of file Traitement_particulier_NS_Brech_VEF.h.
Referenced by lire(), and post_traitement_particulier().
c_pression
int Traitement_particulier_NS_Brech_VEF::c_pression private
Definition at line 79 of file Traitement_particulier_NS_Brech_VEF.h.
Referenced by lire(), and post_traitement_particulier().
c_Richardson
int Traitement_particulier_NS_Brech_VEF::c_Richardson private
Definition at line 78 of file Traitement_particulier_NS_Brech_VEF.h.
Referenced by lire(), and post_traitement_particulier().
C_trans
DoubleTab Traitement_particulier_NS_Brech_VEF::C_trans private
Definition at line 72 of file Traitement_particulier_NS_Brech_VEF.h.
Referenced by lire(), and post_traitement_particulier_calcul_flux().
ch_p
Champ_Fonc_P1NC Traitement_particulier_NS_Brech_VEF::ch_p protected
Definition at line 56 of file Traitement_particulier_NS_Brech_VEF.h.
Referenced by lire(), and post_traitement_particulier_calcul_pression().
ch_ri
Champ_Fonc_P1NC Traitement_particulier_NS_Brech_VEF::ch_ri protected
Definition at line 55 of file Traitement_particulier_NS_Brech_VEF.h.
Referenced by lire(), and post_traitement_particulier_Richardson().
delta_r
DoubleVect Traitement_particulier_NS_Brech_VEF::delta_r private
Definition at line 75 of file Traitement_particulier_NS_Brech_VEF.h.
Referenced by lire(), and post_traitement_particulier_calcul_flux().
delta_teta
DoubleVect Traitement_particulier_NS_Brech_VEF::delta_teta private
Definition at line 76 of file Traitement_particulier_NS_Brech_VEF.h.
Referenced by lire(), and post_traitement_particulier_calcul_flux().
info_obj
const Type_info Traitement_particulier_NS_Brech_VEF::info_obj static
Definition at line 39 of file Traitement_particulier_NS_Brech_VEF.h.
nb
int Traitement_particulier_NS_Brech_VEF::nb private
Definition at line 77 of file Traitement_particulier_NS_Brech_VEF.h.
Referenced by lire(), and post_traitement_particulier_calcul_flux().
r_int
DoubleVect Traitement_particulier_NS_Brech_VEF::r_int private
Definition at line 73 of file Traitement_particulier_NS_Brech_VEF.h.
Referenced by lire(), and post_traitement_particulier_calcul_flux().
R_loc
DoubleTab Traitement_particulier_NS_Brech_VEF::R_loc private
Definition at line 71 of file Traitement_particulier_NS_Brech_VEF.h.
Referenced by lire(), and post_traitement_particulier_calcul_flux().
r_out
DoubleVect Traitement_particulier_NS_Brech_VEF::r_out private
Definition at line 74 of file Traitement_particulier_NS_Brech_VEF.h.
Referenced by lire(), and post_traitement_particulier_calcul_flux().
The documentation for this class was generated from the following files:
src/VEF/Traitement_particulier_NS_Brech_VEF.h
src/VEF/Traitement_particulier_NS_Brech_VEF.cpp