TRUST: Ref_Zone_Cl_VEF Class Reference
Ref_Zone_Cl_VEF Class Reference
#include <Ref_Zone_Cl_VEF.h>
Public Member Functions
~Ref_Zone_Cl_VEF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Zone_Cl_VEF ()
Ref_Zone_Cl_VEF (const Zone_Cl_VEF &)
Ref_Zone_Cl_VEF (const Ref_Zone_Cl_VEF &)
const Zone_Cl_VEF & valeur () const
Zone_Cl_VEF & valeur ()
const Zone_Cl_VEF * operator-> () const
Zone_Cl_VEF * operator-> ()
const Ref_Zone_Cl_VEF & operator= (const Zone_Cl_VEF &)
const Ref_Zone_Cl_VEF & operator= (const Ref_Zone_Cl_VEF &)
operator const Zone_Cl_VEF & () const
operator Zone_Cl_VEF & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Zone_Cl_VEF & self_cast (Objet_U &)
static const Ref_Zone_Cl_VEF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Zone_Cl_VEF * pointeur_
Detailed Description
Definition at line 28 of file Ref_Zone_Cl_VEF.h.
Constructor & Destructor Documentation
Ref_Zone_Cl_VEF::~Ref_Zone_Cl_VEF ()
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
Ref_Zone_Cl_VEF::Ref_Zone_Cl_VEF ()
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
Ref_Zone_Cl_VEF::Ref_Zone_Cl_VEF (const Zone_Cl_VEF & t)
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
Ref_Zone_Cl_VEF::Ref_Zone_Cl_VEF (const Ref_Zone_Cl_VEF & t)
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
Member Function Documentation
Objet_U * Ref_Zone_Cl_VEF::cree_instance () [static]
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
int Ref_Zone_Cl_VEF::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
const Type_info * Ref_Zone_Cl_VEF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
const Type_info & Ref_Zone_Cl_VEF::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
const Type_info * Ref_Zone_Cl_VEF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
Ref_Zone_Cl_VEF::operator const Zone_Cl_VEF & () const
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
Ref_Zone_Cl_VEF::operator Zone_Cl_VEF & ()
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
const Zone_Cl_VEF * Ref_Zone_Cl_VEF::operator-> () const [inline]
Definition at line 28 of file Ref_Zone_Cl_VEF.h.
Zone_Cl_VEF * Ref_Zone_Cl_VEF::operator-> () [inline]
Definition at line 28 of file Ref_Zone_Cl_VEF.h.
const Ref_Zone_Cl_VEF & Ref_Zone_Cl_VEF::operator= (const Ref_Zone_Cl_VEF & t)
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
const Ref_Zone_Cl_VEF & Ref_Zone_Cl_VEF::operator= (const Zone_Cl_VEF & t)
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
Sortie & Ref_Zone_Cl_VEF::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
Entree & Ref_Zone_Cl_VEF::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
const Ref_Zone_Cl_VEF & Ref_Zone_Cl_VEF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
Ref_Zone_Cl_VEF & Ref_Zone_Cl_VEF::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
void Ref_Zone_Cl_VEF::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
unsigned Ref_Zone_Cl_VEF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Zone_Cl_VEF.cpp.
const Zone_Cl_VEF & Ref_Zone_Cl_VEF::valeur () const [inline]
Definition at line 28 of file Ref_Zone_Cl_VEF.h.
Referenced by Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Op_Grad_P1NC_to_P0::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_standard_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Masse_VEF_P1NC::ajouter_masse(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Masse_VEF_P1NC::appliquer_impl(), Assembleur_P_VEF::assembler(), Assembleur_P_VEF::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Op_Conv_EF_VEF_P1NC_Stab::calculer_data_pour_dirichlet(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_VEF_base::calculer_dt_local(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Op_Conv_EF_VEF_P1NC_Stab::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_min(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Conv_VEF_base::calculer_pour_post(), Op_Dift_Stab_VEF_Face::completer(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Dift_VEF_Face_Q1::dimensionner(), Op_Dift_VEF_Face::dimensionner(), Op_Diff_VEF_Face_Q1::dimensionner(), Op_Diff_VEF_Face::dimensionner(), Op_Diff_VEF_Anisotrope_Face::dimensionner(), Op_Conv_VEF_Face::dimensionner(), Op_Conv_EF_VEF_P1NC::dimensionner(), Op_Conv_Amont_old_VEF_Face::dimensionner(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Op_Grad_VEF_P1B_Face::impr(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Y_plus_Champ_P1NC::me_calculer(), h_conv_Champ_P1NC::me_calculer(), grad_U_Champ_P1NC::me_calculer(), grad_T_Champ_P1NC::me_calculer(), Taux_cisaillement_P0_VEF::mettre_a_jour(), Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite(), Op_Conv_EF_VEF_P1NC_Stab::mettre_a_jour_pour_periodicite(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_matrice(), Op_Dift_VEF_Face_Q1::modifier_pour_Cl(), Op_Dift_VEF_Face::modifier_pour_Cl(), Op_Diff_VEF_Face_Q1::modifier_pour_Cl(), Op_Diff_VEF_Face::modifier_pour_Cl(), Op_Diff_VEF_Anisotrope_Face::modifier_pour_Cl(), Op_Conv_VEF_Face::modifier_pour_Cl(), Op_Conv_EF_VEF_P1NC::modifier_pour_Cl(), Op_Conv_Amont_old_VEF_Face::modifier_pour_Cl(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Op_Conv_EF_VEF_P1NC_Stab::reinit_conv_pour_Cl(), Assembleur_P_VEF::remplir(), Op_Conv_VEF_Face::remplir_fluent(), Op_Diff_VEFP1NCP1B_Face::test(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), Op_Diff_VEF_Face_Penalise::zone_cl(), Assembleur_P_VEF::zone_Cl_dis_base(), Y_plus_Champ_P1NC::zone_Cl_dis_base(), h_conv_Champ_P1NC::zone_Cl_dis_base(), grad_U_Champ_P1NC::zone_Cl_dis_base(), grad_T_Champ_P1NC::zone_Cl_dis_base(), and Op_Diff_VEFP1NCP1B_Face::zone_Cl_VEFPreP1B().
Zone_Cl_VEF & Ref_Zone_Cl_VEF::valeur () [inline]
Definition at line 28 of file Ref_Zone_Cl_VEF.h.
Member Data Documentation
const Type_info Ref_Zone_Cl_VEF::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Zone_Cl_VEF.h.
Zone_Cl_VEF* Ref_Zone_Cl_VEF::pointeur_ [private]
Definition at line 28 of file Ref_Zone_Cl_VEF.h.
The documentation for this class was generated from the following files:
src/VEF/Zones/Ref_Zone_Cl_VEF.h
src/VEF/Zones/Ref_Zone_Cl_VEF.cpp