TRUST: Terme_Source_EF_base Class Reference
Terme_Source_EF_base Class Reference
#include <Terme_Source_EF_base.h>
Public Member Functions
Terme_Source_EF_base ()
~Terme_Source_EF_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Terme_Source_EF_base (const Iterateur_Source_EF_base &)
constructeur
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & calculer (DoubleTab &) const
void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
int impr (Sortie &os) const
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Terme_Source_EF_base & self_cast (Objet_U &)
static const Terme_Source_EF_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Protected Attributes
Iterateur_Source_EF iter
Detailed Description
Definition at line 40 of file Terme_Source_EF_base.h.
Constructor & Destructor Documentation
Terme_Source_EF_base::Terme_Source_EF_base ()
Definition at line 25 of file Terme_Source_EF_base.cpp.
Terme_Source_EF_base::~Terme_Source_EF_base ()
Definition at line 25 of file Terme_Source_EF_base.cpp.
Terme_Source_EF_base::Terme_Source_EF_base (const Iterateur_Source_EF_base & iter_base) [inline]
constructeur
Definition at line 64 of file Terme_Source_EF_base.h.
                                                                                           :
  iter(iter_base)
{}
Member Function Documentation
DoubleTab & Terme_Source_EF_base::ajouter (DoubleTab & resu) const [inline, virtual]
Reimplemented from Source_base.
Definition at line 68 of file Terme_Source_EF_base.h.
References Iterateur_Source_EF::ajouter(), and iter.
{
  return iter.ajouter(resu);
}
DoubleTab & Terme_Source_EF_base::calculer (DoubleTab & resu) const [inline, virtual]
Reimplemented from Source_base.
Definition at line 73 of file Terme_Source_EF_base.h.
References Iterateur_Source_EF::calculer(), and iter.
{
  return iter.calculer(resu);
}
void Terme_Source_EF_base::completer () [virtual]
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
Definition at line 45 of file Terme_Source_EF_base.cpp.
References Iterateur_Source_EF::completer_(), and iter.
{
  Source_base::completer();
  iter.completer_();
}
virtual int Terme_Source_EF_base::duplique () const [pure virtual]
Implements Source_base.
Implemented in Puissance_Thermique_EF, and Puissance_Thermique_QC_EF.
const Type_info * Terme_Source_EF_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Puissance_Thermique_EF, and Puissance_Thermique_QC_EF.
Definition at line 25 of file Terme_Source_EF_base.cpp.
int Terme_Source_EF_base::impr (Sortie & os) const [inline, virtual]
Reimplemented from Source_base.
Definition at line 78 of file Terme_Source_EF_base.h.
References Iterateur_Source_EF_base::impr(), iter, Process::je_suis_maitre(), Objet_U::que_suis_je(), and Deriv_Iterateur_Source_EF_base::valeur().
{
  if(je_suis_maitre())
    os << que_suis_je();
  return iter.valeur().impr(os);
}
const Type_info * Terme_Source_EF_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Puissance_Thermique_EF, and Puissance_Thermique_QC_EF.
Definition at line 25 of file Terme_Source_EF_base.cpp.
Sortie & Terme_Source_EF_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Puissance_Thermique_EF, and Puissance_Thermique_QC_EF.
Definition at line 31 of file Terme_Source_EF_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Terme_Source_EF_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Puissance_Thermique_EF, and Puissance_Thermique_QC_EF.
Definition at line 40 of file Terme_Source_EF_base.cpp.
{
  return s ;
}
const Terme_Source_EF_base & Terme_Source_EF_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Reimplemented in Puissance_Thermique_EF, and Puissance_Thermique_QC_EF.
Definition at line 25 of file Terme_Source_EF_base.cpp.
Terme_Source_EF_base & Terme_Source_EF_base::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Reimplemented in Puissance_Thermique_EF, and Puissance_Thermique_QC_EF.
Definition at line 25 of file Terme_Source_EF_base.cpp.
Member Data Documentation
const Type_info Terme_Source_EF_base::info_obj [static]
Reimplemented from Source_base.
Reimplemented in Puissance_Thermique_EF, and Puissance_Thermique_QC_EF.
Definition at line 43 of file Terme_Source_EF_base.h.
Iterateur_Source_EF Terme_Source_EF_base::iter [protected]
Definition at line 55 of file Terme_Source_EF_base.h.
Referenced by ajouter(), Puissance_Thermique_QC_EF::associer_pb(), Puissance_Thermique_EF::associer_pb(), Puissance_Thermique_QC_EF::associer_zones(), Puissance_Thermique_EF::associer_zones(), calculer(), completer(), and impr().
The documentation for this class was generated from the following files:
src/EF/Sources/Terme_Source_EF_base.h
src/EF/Sources/Terme_Source_EF_base.cpp