TRUST: Source_QC_Chaleur Class Reference
Source_QC_Chaleur Class Reference
class Source_QC_Chaleur
Cette classe represente un terme source supplementaire a prendre en compte dans
les equations de la chaleur dans le cas ou le fluide est quasi compressible
#include <Source_QC_Chaleur.h>
Public Member Functions
Source_QC_Chaleur ()
~Source_QC_Chaleur ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
Ajoute les termes sources.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Source_QC_Chaleur & self_cast (Objet_U &)
static const Source_QC_Chaleur & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Detailed Description
class Source_QC_Chaleur
Cette classe represente un terme source supplementaire a prendre en compte dans
les equations de la chaleur dans le cas ou le fluide est quasi compressible
Definition at line 44 of file Source_QC_Chaleur.h.
Constructor & Destructor Documentation
Source_QC_Chaleur::Source_QC_Chaleur ()
Definition at line 28 of file Source_QC_Chaleur.cpp.
Source_QC_Chaleur::~Source_QC_Chaleur ()
Definition at line 28 of file Source_QC_Chaleur.cpp.
Member Function Documentation
DoubleTab & Source_QC_Chaleur::ajouter (DoubleTab & resu) const [virtual]
Ajoute les termes sources.
Returns:
Entree&
Signification:
Contraintes:
< On calcul pas ce terme source si dt<=0
Implements Source_Chaleur_Fluide_Dilatable_base.
Definition at line 55 of file Source_QC_Chaleur.cpp.
References DoubleTab::dimension(), Source_Chaleur_Fluide_Dilatable_base::le_fluide, MorEqn::mon_equation, Source_Chaleur_Fluide_Dilatable_base::porosites, Fluide_Dilatable_base::pression_th(), Fluide_Dilatable_base::pression_thn(), ref_cast, Ref_Fluide_Dilatable_base::valeur(), and Source_Chaleur_Fluide_Dilatable_base::volumes.
{
  double dt_= mon_equation->schema_temps().temps_courant() - mon_equation->schema_temps().temps_precedent();
  if (dt_<=0) return resu; //!< On calcul pas ce terme source si dt<=0
  /*
   * The source term corresponds to :
   * d P_tot / d t = del P / del t + u.grad(P_tot)
   * Here grad(P_tot) = 0 (uniform in space)
   */
  int i, nsom = resu.dimension(0);
  const Fluide_Quasi_Compressible& FQC = ref_cast(Fluide_Quasi_Compressible,le_fluide.valeur());
  double Pth = FQC.pression_th(), Pthn = FQC.pression_thn();
  double dpth = ( Pth - Pthn ) / dt_;
  for (i=0 ; i<nsom ; i++) resu(i) += dpth * volumes(i) * porosites(i);
  return resu;
}
virtual int Source_QC_Chaleur::duplique () const [pure virtual]
Implements Source_Chaleur_Fluide_Dilatable_base.
Implemented in Source_QC_Chaleur_VDF, and Source_QC_Chaleur_VEF.
const Type_info * Source_QC_Chaleur::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_Chaleur_Fluide_Dilatable_base.
Reimplemented in Source_QC_Chaleur_VDF, and Source_QC_Chaleur_VEF.
Definition at line 28 of file Source_QC_Chaleur.cpp.
const Type_info * Source_QC_Chaleur::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_Chaleur_Fluide_Dilatable_base.
Reimplemented in Source_QC_Chaleur_VDF, and Source_QC_Chaleur_VEF.
Definition at line 28 of file Source_QC_Chaleur.cpp.
Sortie & Source_QC_Chaleur::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_Chaleur_Fluide_Dilatable_base.
Reimplemented in Source_QC_Chaleur_VDF, and Source_QC_Chaleur_VEF.
Definition at line 30 of file Source_QC_Chaleur.cpp.
References finl, and Objet_U::que_suis_je().
{
  os <<que_suis_je()<< finl;
  return os;
}
Entree & Source_QC_Chaleur::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_Chaleur_Fluide_Dilatable_base.
Reimplemented in Source_QC_Chaleur_VDF, and Source_QC_Chaleur_VEF.
Definition at line 36 of file Source_QC_Chaleur.cpp.
{
  return is;
}
const Source_QC_Chaleur & Source_QC_Chaleur::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_Chaleur_Fluide_Dilatable_base.
Reimplemented in Source_QC_Chaleur_VDF, and Source_QC_Chaleur_VEF.
Definition at line 28 of file Source_QC_Chaleur.cpp.
Source_QC_Chaleur & Source_QC_Chaleur::self_cast (Objet_U & r) [static]
Reimplemented from Source_Chaleur_Fluide_Dilatable_base.
Reimplemented in Source_QC_Chaleur_VDF, and Source_QC_Chaleur_VEF.
Definition at line 28 of file Source_QC_Chaleur.cpp.
Member Data Documentation
const Type_info Source_QC_Chaleur::info_obj [static]
Reimplemented from Source_Chaleur_Fluide_Dilatable_base.
Reimplemented in Source_QC_Chaleur_VDF, and Source_QC_Chaleur_VEF.
Definition at line 46 of file Source_QC_Chaleur.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/Sources/Source_QC_Chaleur.h
src/ThHyd/Dilatable/Quasi_Compressible/Sources/Source_QC_Chaleur.cpp