TRUST: paroi_adiabatique Class Reference
paroi_adiabatique Class Reference
#include <Cond_lim_utilisateur_base.h>
Public Member Functions
paroi_adiabatique ()
~paroi_adiabatique ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void complement (Nom &nom)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static paroi_adiabatique & self_cast (Objet_U &)
static const paroi_adiabatique & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'une condition aux limite de type Cond_lim_utilisateur_base
a partir d'un flot d'entree.
Detailed Description
Definition at line 82 of file Cond_lim_utilisateur_base.h.
Constructor & Destructor Documentation
paroi_adiabatique::paroi_adiabatique ()
Definition at line 35 of file Cond_lim_utilisateur_base.cpp.
paroi_adiabatique::~paroi_adiabatique ()
Definition at line 35 of file Cond_lim_utilisateur_base.cpp.
Member Function Documentation
void paroi_adiabatique::complement (Nom & nom) [virtual]
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 258 of file Cond_lim_utilisateur_base.cpp.
References Cond_lim_utilisateur_base::is_pb_rayo(), and Cond_lim_utilisateur_base::is_pb_VDF().
{
  int rayo=is_pb_rayo();
  if (rayo==1)
    {
      if (is_pb_VDF())
        ajout="paroi_flux_impose_rayo_semi_transp_VDF champ_front_uniforme 1 0";
      else
        ajout="paroi_flux_impose_rayo_semi_transp_VEF champ_front_uniforme 1 0";
// ajout="Neumann_Paroi_adiabatique";
    }
  else if (rayo==2)
    ajout="paroi_flux_impose_rayo_transp champ_front_uniforme 1 0";
  else
    ajout="Neumann_Paroi_adiabatique";
}
Objet_U * paroi_adiabatique::cree_instance () [static]
Definition at line 35 of file Cond_lim_utilisateur_base.cpp.
int paroi_adiabatique::duplique () const [virtual]
Implements Cond_lim_utilisateur_base.
Definition at line 35 of file Cond_lim_utilisateur_base.cpp.
const Type_info * paroi_adiabatique::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 35 of file Cond_lim_utilisateur_base.cpp.
const Type_info * paroi_adiabatique::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 35 of file Cond_lim_utilisateur_base.cpp.
Sortie & paroi_adiabatique::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 59 of file Cond_lim_utilisateur_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & paroi_adiabatique::readOn (Entree & s) [protected, virtual]
Lecture d'une condition aux limite de type Cond_lim_utilisateur_base
a partir d'un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 96 of file Cond_lim_utilisateur_base.cpp.
{
  return s;
}
const paroi_adiabatique & paroi_adiabatique::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 35 of file Cond_lim_utilisateur_base.cpp.
paroi_adiabatique & paroi_adiabatique::self_cast (Objet_U & r) [static]
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 35 of file Cond_lim_utilisateur_base.cpp.
unsigned paroi_adiabatique::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 35 of file Cond_lim_utilisateur_base.cpp.
Member Data Documentation
const Type_info paroi_adiabatique::info_obj [static]
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 84 of file Cond_lim_utilisateur_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Cond_lim_utilisateur_base.h
src/Kernel/Framework/Cond_lim_utilisateur_base.cpp