TRUST: Champ_Proto Class Reference
Champ_Proto Class Reference abstract
classe Champ_Proto
Classe representant un prototype de Champ. Tous les classes
representant des champs derivent de Champ_proto. Champ_proto offre
des methodes classiques sur des champs (min, max, norme, += ...)
mais ne contient pas de membre representant des donnees.
La plupart des methodes de Champ_proto font appel aux methodes de
meme nom d'un objet DoubleTab renvoye par la methode abstraite
de Champ_proto valeurs().
#include <Champ_Proto.h>
Public Member Functions
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Detailed Description
classe Champ_Proto
Classe representant un prototype de Champ. Tous les classes
representant des champs derivent de Champ_proto. Champ_proto offre
des methodes classiques sur des champs (min, max, norme, += ...)
mais ne contient pas de membre representant des donnees.
La plupart des methodes de Champ_proto font appel aux methodes de
meme nom d'un objet DoubleTab renvoye par la methode abstraite
de Champ_proto valeurs().
Definition at line 42 of file Champ_Proto.h.
Constructor & Destructor Documentation
~Champ_Proto()
virtual Champ_Proto::~Champ_Proto () inline virtual
Definition at line 45 of file Champ_Proto.h.
{ }
Member Function Documentation
futur() [1/2]
virtual DoubleTab & Champ_Proto::futur (int i = 1) inline virtual
Reimplemented in Champ_Inc, and Champ_Inc_base.
Definition at line 52 of file Champ_Proto.h.
{ return valeurs(); }
References valeurs().
futur() [2/2]
virtual const DoubleTab & Champ_Proto::futur (int i = 1) const inline virtual
Reimplemented in Champ_Inc, and Champ_Inc_base.
Definition at line 53 of file Champ_Proto.h.
{ return valeurs(); }
References valeurs().
lire_dimension() [1/2]
int Champ_Proto::lire_dimension (Entree & is, const Nom & le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
Returns
int
Signification: la dimension du champ
Contraintes:
Definition at line 33 of file Champ_Proto.cpp.
{
  if(!is.check_types()) abort();
// verification meme en optim
  int dim = -1;
  is >> dim;
  return lire_dimension(dim, le_nom_);
}
References Entree::check_types(), and lire_dimension().
Referenced by lire_dimension(), Champ_Fonc_Tabule::readOn(), Champ_front_bruite::readOn(), Champ_front_fonc_pois_ipsn::readOn(), Champ_front_fonc_pois_tube::readOn(), Champ_Front_Fonction::readOn(), Champ_front_lu::readOn(), Champ_front_t::readOn(), Champ_front_Tabule::readOn(), Champ_front_Tabule_lu::readOn(), Champ_front_txyz::readOn(), Champ_front_uniforme::readOn(), Champ_Don_Fonc_txyz::readOn(), Champ_Don_Fonc_xyz::readOn(), Champ_Don_lu::readOn(), Champ_Fonc_Fonction_txyz_Morceaux::readOn(), Champ_Fonc_Morceaux::readOn(), Champ_Fonc_t::readOn(), Champ_Fonc_Tabule_Morceaux::readOn(), champ_init_canal_sinal::readOn(), Champ_Tabule_Temps::readOn(), Champ_Uniforme::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Uniforme_Morceaux_Tabule_Temps::readOn(), Init_par_partie::readOn(), Champ_front_softanalytique::readOn(), and Champ_front_synt::readOn().
lire_dimension() [2/2]
int Champ_Proto::lire_dimension (int dim, const Nom & le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
Returns
int
Signification: la dimension du champ
Contraintes:
Definition at line 57 of file Champ_Proto.cpp.
{
  if (dim < 1)
    {
      Cerr << "Error in int Champ_Proto::lire_dimension() for " << le_nom_
           << "\n bad dimension : " << dim << finl;
      Process::exit();
    }
  return dim;
}
References Cerr, Process::exit(), and finl.
operator()() [1/4]
double & Champ_Proto::operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Returns
double&
Signification: la i-ieme composantes du champ
Contraintes:
Definition at line 107 of file Champ_Proto.cpp.
{
  return valeurs()(i);
}
References valeurs().
operator()() [2/4]
double Champ_Proto::operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
Returns
double
Signification: la i-ieme composantes du champ
Contraintes:
Definition at line 85 of file Champ_Proto.cpp.
{
  return valeurs()(i);
}
References valeurs().
operator()() [3/4]
double & Champ_Proto::operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
Returns
double&
Signification: la composante (i,j) du champ
Contraintes: reference
Definition at line 162 of file Champ_Proto.cpp.
{
  return valeurs()(i,j);
}
References valeurs().
operator()() [4/4]
double Champ_Proto::operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
Returns
double
Signification: la composante (i,j) du champ
Contraintes:
Definition at line 135 of file Champ_Proto.cpp.
{
  return valeurs()(i,j);
}
References valeurs().
passe() [1/2]
virtual DoubleTab & Champ_Proto::passe (int i = 1) inline virtual
Reimplemented in Champ_Inc, and Champ_Inc_base.
Definition at line 54 of file Champ_Proto.h.
{ return valeurs(); }
References valeurs().
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_Turbulent_PolyMAC_P0_Face::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), and Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_nu().
passe() [2/2]
virtual const DoubleTab & Champ_Proto::passe (int i = 1) const inline virtual
Reimplemented in Champ_Inc, and Champ_Inc_base.
Definition at line 55 of file Champ_Proto.h.
{ return valeurs(); }
References valeurs().
valeurs() [1/4]
virtual const DoubleTab & Champ_Proto::valeurs () const pure virtual
Implemented in Champ_Fonc_Tabule, Champ, Champ_Don, Champ_Don_base, Champ_Fonc, Champ_front, Champ_front_base, Champ_Inc, Champ_Inc_base, Champ_Fonc_MED, Champ_Fonc_reprise, Champ, Champ_Don, Champ_Don_base, Champ_Fonc, Champ_front, Champ_front_base, and Champ_Inc.
valeurs() [2/4]
virtual DoubleTab & Champ_Proto::valeurs () pure virtual
Implemented in Champ_Fonc_Tabule, Champ, Champ_Don, Champ_Don_base, Champ_Fonc, Champ_front, Champ_front_base, Champ_Inc, Champ_Inc_base, Champ_Fonc_MED, Champ_Fonc_reprise, Champ, Champ_Don, Champ_Don_base, Champ_Fonc, Champ_front, Champ_front_base, and Champ_Inc.
Referenced by Champ_base::affecter(), Champ_Fonc_Tabule::affecter_(), Champ_P1_isoP1Bulle::affecter_(), Champ_Face_PolyMAC::affecter_(), Champ_Face_PolyMAC_P0::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Face::affecter_(), Champ_Fonc_Face::affecter_(), Champ_Uniforme::affecter_(), TRUSTChamp_Don_generique< _TYPE_ >::affecter_(), TRUSTChamp_Morceaux_generique< _TYPE_ >::affecter_(), Champ_Elem_PolyMAC::affecter_(), Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Source_Generique_P0_Elem::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), T_It_Sou_VDF_Face< _TYPE_ >::ajouter(), Source_Generique_VEF::ajouter(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Masse_PolyMAC_Elem::ajouter_blocs(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Conv_EF::ajouter_sous_cond_template(), Op_Dift_VDF_Multi_inco_Elem_Axi::alpha_(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC::assembler_continuite(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Eval_Diff_VDF_Multi_inco_const::associer(), Eval_Diff_VDF_Multi_inco_var::associer(), Eval_Diff_VDF_var::associer(), Eval_Diff_VDF_var_aniso::associer(), build_triofield(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Perte_Charge_Singuliere::calculate_Q(), Champ_Q1NC_impl::calcule_valeur_a_elem_compo(), Op_Diff_P1NC_barprim::calculer(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Op_Dift_EF_base::calculer_borne_locale(), Op_Dift_VDF_Face_base::calculer_borne_locale(), Op_Dift_VEF_base::calculer_borne_locale(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Fluide_base::calculer_e_int(), Traitement_particulier_NS_EC::calculer_Ec(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_Temp(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Op_Conv_VDF_base::calculer_pour_post(), Op_Diff_VEF_base::calculer_pour_post(), Op_Dift_VEF_Face::calculer_pour_post(), Navier_Stokes_std::calculer_pression_hydrostatique(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Flux_interfacial_Ranz_Marshall::coeffs(), Op_Diff_PolyMAC_P0_base::completer(), Champ_Generique_Transformation::completer(), Op_Ecart_type::completer(), Op_Moyenne::completer(), Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Op_Dift_EF_Q1::diffusivite(), Op_Dift_VEF_Face::diffusivite(), Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs(), Masse_PolyMAC_Elem::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Flux_interfacial_PolyMAC::dimensionner_blocs(), Travail_pression_PolyMAC::dimensionner_blocs(), Assembleur_P_PolyMAC::dimensionner_continuite(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), EcritureLectureSpecial::ecriture_special(), Discretisation_tools::faces_to_cells(), Champ_P1iP1B_implementation::filtrage(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), futur(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_modifier_pour_QC::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_refChamp::get_localisation(), Champ_Generique_refChamp::get_ref_values(), Champ_implementation_P0::imprime_P0(), Champ_P1NC_implementation::imprime_P1NC(), Champ_Q4_implementation::imprime_Q4(), Fluide_Weakly_Compressible::initialiser_pth_xyz(), Loi_Etat_rhoT_GP_QC::initialiser_rho(), EcritureLectureSpecial::lecture_special(), Postraitement_lata::lire_champs(), Op_EF_base::marque_elem(), Eval_Diff_VDF_var::mettre_a_jour(), Eval_Diff_VDF_var_aniso::mettre_a_jour(), TRUSTChamp_Morceaux_generique< _TYPE_ >::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Correlation_Vec_Sca_VEF::mettre_a_jour(), Integrale_tps_Champ::mettre_a_jour_integrale(), Milieu_composite::mettre_a_jour_tabs(), Assembleur_P_PolyMAC::modifier_secmem_pour_incr_p(), Discretisation_tools::nodes_to_cells(), Op_Diff_VDF_var_Face_Axi::nu_(), Op_Dift_VDF_var_Face_Axi::nu_(), Op_Diff_VDF_var_Face_Axi::nu_mean_2_pts_(), Op_Dift_VDF_var_Face_Axi::nu_mean_2_pts_(), Op_Dift_VDF_var_Face_Axi::nu_mean_4_pts_(), Op_Diff_VDF_var_Face_Axi::nu_mean_4_pts_(), operator()(), passe(), Convection_Diffusion_Temperature::penalisation_L2(), Postraitement::postraiter_champs(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), Op_Diff_VEF_base::remplir_nu(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), Source_PDF_EF::rotate_imposed_velocity(), TSAVDF_ajouter_liste_faces(), TSAVEF_ajouter_liste_faces(), Champ_front_debit_massique::update_coeff(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), Champ_implementation_P0::valeur_a_elem(), Champ_implementation_sommet_base::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem(), Champ_Face_implementation::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem(), Champ_Q1NC_impl::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem_compo(), Champ_Face_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_elem_compo(), Champ_implementation_P0::valeur_a_elem_compo(), Champ_implementation_sommet_base::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_sommet_compo(), Champ_base::valeur_aux_bords(), Champ_Q4_implementation::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Q1NC_impl::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_implementation_sommet_base::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_Face_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_Q1NC_impl::valeur_aux_elems_compo(), Champ_implementation_P0::valeur_aux_elems_compo(), Champ_implementation_sommet_base::valeur_aux_elems_compo(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Face_PolyMAC::valeur_aux_faces(), Champ_Q4_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_Q4_implementation::valeur_aux_sommets_compo(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), Champ_implementation_sommet_base::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_implementation_sommet_base::valeur_aux_sommets_impl(), and Champ::valeurs().
valeurs() [3/4]
virtual DoubleTab & Champ_Proto::valeurs (double temps) inline virtual
Reimplemented in Champ, Champ_Don, Champ_Don_base, Champ_Fonc, Champ_front, Champ_front_base, Champ_Inc, and Champ_Inc_base.
Definition at line 50 of file Champ_Proto.h.
{ return valeurs(); }
References valeurs().
Referenced by valeurs().
valeurs() [4/4]
virtual const DoubleTab & Champ_Proto::valeurs (double temps) const inline virtual
Reimplemented in Champ, Champ_Don, Champ_Don_base, Champ_Fonc, Champ_front, Champ_front_base, Champ_Inc, and Champ_Inc_base.
Definition at line 51 of file Champ_Proto.h.
{ return valeurs(); }
References valeurs().
Referenced by valeurs().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_Proto.h
src/Kernel/Framework/Champ_Proto.cpp