TRUST: EOS_Tools_VDF Class Reference
EOS_Tools_VDF Class Reference
classe EOS_Tools_VDF
Cette classe et specifique a discretisation de type VDF.
#include <EOS_Tools_VDF.h>
Public Member Functions
EOS_Tools_VDF ()
~EOS_Tools_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const DoubleTab & rho_discvit () const override
Renvoie rho avec la meme discretisation que la vitesse :
une valeur par face en VDF.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
void divu_discvit (const DoubleTab &, DoubleTab &) override
Renvoie div(u) avec la meme discretisation que la vitesse :
une valeur par face en VDF.
void secmembre_divU_Z (DoubleTab &) const override
Calcule le second membre de l'equation de continuite :
div(rhoU) = W = -dZ/dT avec Z=rho.
void mettre_a_jour (double temps) override
void calculer_rho_face_np1 (const DoubleTab &rho) override
double moyenne_vol (const DoubleTab &) const override
Calcule la moyenne volumique de la grandeur P0 donnee.
const DoubleTab & rho_face_n () const override
const DoubleTab & rho_face_np1 () const override
const Fluide_Dilatable_base & le_fluide () const
Public Member Functions inherited from EOS_Tools_base
EOS_Tools_base ()
~EOS_Tools_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_fluide (const Fluide_Dilatable_base &)
virtual void mettre_a_jour (double)
virtual const DoubleTab & rho_discvit () const =0
virtual const DoubleTab & rho_face_n () const =0
virtual const DoubleTab & rho_face_np1 () const =0
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void divu_discvit (const DoubleTab &, DoubleTab &)=0
virtual void secmembre_divU_Z (DoubleTab &) const =0
virtual void calculer_rho_face_np1 (const DoubleTab &rho)=0
virtual double moyenne_vol (const DoubleTab &) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static EOS_Tools_VDF & self_cast (Objet_U &)
static const EOS_Tools_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from EOS_Tools_base
static const Type_info * info ()
static EOS_Tools_base & self_cast (Objet_U &)
static const EOS_Tools_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from EOS_Tools_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VDF la_zone
Ref_Zone_Cl_dis la_zone_Cl
DoubleTab tab_rho_face
DoubleTab tab_rho_face_demi
DoubleTab tab_rho_face_np1
Protected Attributes inherited from EOS_Tools_base
Ref_Fluide_Dilatable_base le_fluide_
Detailed Description
classe EOS_Tools_VDF
Cette classe et specifique a discretisation de type VDF.
Definition at line 35 of file EOS_Tools_VDF.h.
Constructor & Destructor Documentation
EOS_Tools_VDF()
EOS_Tools_VDF::EOS_Tools_VDF ()
Definition at line 26 of file EOS_Tools_VDF.cpp.
~EOS_Tools_VDF()
EOS_Tools_VDF::~EOS_Tools_VDF ()
Definition at line 26 of file EOS_Tools_VDF.cpp.
Member Function Documentation
associer_zones()
void EOS_Tools_VDF::associer_zones (const Zone_dis & zone, const Zone_Cl_dis & zone_cl) override virtual
Implements EOS_Tools_base.
Definition at line 39 of file EOS_Tools_VDF.cpp.
{
  la_zone = ref_cast(Zone_VDF,zone.valeur());
  la_zone_Cl = zone_cl;
  Champ_Face toto;
  toto.associer_zone_dis_base(zone.valeur());
  toto.fixer_nb_comp(1);
  toto.fixer_nb_valeurs_nodales(la_zone->nb_faces());
  tab_rho_face=toto.valeurs();
  tab_rho_face_demi=toto.valeurs();
  tab_rho_face_np1=toto.valeurs();
}
References Champ_Face::associer_zone_dis_base(), Field_base::fixer_nb_comp(), Champ_Face::fixer_nb_valeurs_nodales(), la_zone, la_zone_Cl, Zone_VF::nb_faces(), ref_cast, tab_rho_face, tab_rho_face_demi, tab_rho_face_np1, Deriv_Zone_dis_base::valeur(), and Champ_Inc_base::valeurs().
calculer_rho_face_np1()
void EOS_Tools_VDF::calculer_rho_face_np1 (const DoubleTab & rho) override virtual
Implements EOS_Tools_base.
Definition at line 83 of file EOS_Tools_VDF.cpp.
{
  int face, elem, nb_faces_tot = la_zone->nb_faces_tot();
  Debog::verifier("tab_rhoP0",tab_rhoP0);
  int i, nb_comp;
  IntTab& face_voisins = la_zone->face_voisins();
  for (face=0 ; face<nb_faces_tot ; face++)
    {
      nb_comp=0;
      tab_rho_face_np1(face) = 0;
      for (i=0 ; i<2 ; i++)
        {
          elem= face_voisins(face,i);
          if (elem!=-1)
            {
              nb_comp++;
              tab_rho_face_np1(face) += tab_rhoP0(elem);
            }
        }
      tab_rho_face_np1(face) /= nb_comp;
    }
  tab_rho_face_np1.echange_espace_virtuel();
  Debog::verifier("tab_rho_face_np1",tab_rho_face_np1);
  for (face=0 ; face<nb_faces_tot ; face++)
    tab_rho_face_demi(face)=(tab_rho_face_np1(face)+tab_rho_face(face))/2.;
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::face_voisins(), la_zone, Zone_VF::nb_faces_tot(), tab_rho_face, tab_rho_face_demi, tab_rho_face_np1, and Debog::verifier().
cree_instance()
Objet_U * EOS_Tools_VDF::cree_instance () static
Definition at line 26 of file EOS_Tools_VDF.cpp.
divu_discvit()
void EOS_Tools_VDF::divu_discvit (const DoubleTab & secmem1, DoubleTab & secmem2) override virtual
Renvoie div(u) avec la meme discretisation que la vitesse :
une valeur par face en VDF.
Implements EOS_Tools_base.
Definition at line 146 of file EOS_Tools_VDF.cpp.
{
  assert_espace_virtuel_vect(secmem1);
  int nb_faces_tot = la_zone->nb_faces_tot();
  IntTab& face_voisins = la_zone->face_voisins();
// remplissage de div(u) sur les faces
  for (int face=0 ; face<nb_faces_tot; face++)
    {
      int nb_comp=0;
      secmem2(face)=0;
      for (int i=0 ; i<2 ; i++)
        {
          int elem= face_voisins(face,i);
          if (elem!=-1)
            {
              nb_comp++;
              secmem2(face) += secmem1(elem);
            }
        }
      secmem2(face) /= nb_comp;
    }
  secmem2.echange_espace_virtuel();
}
References assert_espace_virtuel_vect(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::face_voisins(), la_zone, and Zone_VF::nb_faces_tot().
duplique()
int EOS_Tools_VDF::duplique () const override virtual
Implements Objet_U.
Definition at line 26 of file EOS_Tools_VDF.cpp.
get_info()
const Type_info * EOS_Tools_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from EOS_Tools_base.
Definition at line 26 of file EOS_Tools_VDF.cpp.
info()
const Type_info * EOS_Tools_VDF::info () static
Definition at line 26 of file EOS_Tools_VDF.cpp.
le_fluide()
const Fluide_Dilatable_base & EOS_Tools_VDF::le_fluide () const inline
Definition at line 48 of file EOS_Tools_VDF.h.
{ return le_fluide_.valeur(); }
References EOS_Tools_base::le_fluide_, and Ref_Fluide_Dilatable_base::valeur().
Referenced by secmembre_divU_Z().
mettre_a_jour()
void EOS_Tools_VDF::mettre_a_jour (double temps) override virtual
Reimplemented from EOS_Tools_base.
Definition at line 208 of file EOS_Tools_VDF.cpp.
{
  int n=tab_rho_face_np1.size_totale();
  for (int i=0; i<n; i++)
    {
      tab_rho_face(i)=tab_rho_face_np1(i);
      tab_rho_face_demi(i)=tab_rho_face_np1(i);
    }
}
References TRUSTVect< _TYPE_ >::size_totale(), tab_rho_face, tab_rho_face_demi, and tab_rho_face_np1.
moyenne_vol()
double EOS_Tools_VDF::moyenne_vol (const DoubleTab & tab) const override virtual
Calcule la moyenne volumique de la grandeur P0 donnee.
Returns
DoubleTab&
Signification: rho discretise par face
Contraintes:
Implements EOS_Tools_base.
Definition at line 66 of file EOS_Tools_VDF.cpp.
{
  int nb_elem=la_zone->nb_elem();
  const DoubleVect& volumes = la_zone->volumes();
  assert(tab.dimension(0)==nb_elem);
  ArrOfDouble sum(2);
  sum = 0;
  for (int elem=0 ; elem<nb_elem ; elem++)
    {
      double v = volumes(elem);
      sum[0] += v;
      sum[1] += v*tab(elem);
    }
  mp_sum_for_each_item(sum);
  return sum[1]/sum[0];
}
References TRUSTTab< _TYPE_ >::dimension(), la_zone, mp_sum_for_each_item(), Zone_dis_base::nb_elem(), and Zone_VF::volumes().
printOn()
Sortie & EOS_Tools_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from EOS_Tools_base.
Definition at line 28 of file EOS_Tools_VDF.cpp.
{
  os <<que_suis_je()<< finl;
  return os;
}
References finl, and Objet_U::que_suis_je().
readOn()
Entree & EOS_Tools_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from EOS_Tools_base.
Definition at line 34 of file EOS_Tools_VDF.cpp.
{
  return is;
}
rho_discvit()
const DoubleTab & EOS_Tools_VDF::rho_discvit () const override virtual
Renvoie rho avec la meme discretisation que la vitesse :
une valeur par face en VDF.
Returns
DoubleTab&
Signification: rho discretise par face
Contraintes:
Implements EOS_Tools_base.
Definition at line 126 of file EOS_Tools_VDF.cpp.
{
  return tab_rho_face_demi;
}
References tab_rho_face_demi.
rho_face_n()
const DoubleTab & EOS_Tools_VDF::rho_face_n () const inline override virtual
Implements EOS_Tools_base.
Definition at line 46 of file EOS_Tools_VDF.h.
{ return tab_rho_face; }
References tab_rho_face.
rho_face_np1()
const DoubleTab & EOS_Tools_VDF::rho_face_np1 () const inline override virtual
Implements EOS_Tools_base.
Definition at line 47 of file EOS_Tools_VDF.h.
{ return tab_rho_face_np1; }
References tab_rho_face_np1.
secmembre_divU_Z()
void EOS_Tools_VDF::secmembre_divU_Z (DoubleTab & tab_W) const override virtual
Calcule le second membre de l'equation de continuite :
div(rhoU) = W = -dZ/dT avec Z=rho.
Implements EOS_Tools_base.
Definition at line 185 of file EOS_Tools_VDF.cpp.
{
  double dt = le_fluide().vitesse()->equation().schema_temps().pas_de_temps();
  int elem,nb_elem = la_zone->nb_elem(),nb_faces = la_zone->nb_faces();
  DoubleVect tab_dZ(nb_elem);
  DoubleTab tab_gradZ(nb_faces);
  const DoubleTab& tab_rhonP0 = le_fluide().loi_etat()->rho_n();
  const DoubleTab& tab_rhonp1P0 = le_fluide().loi_etat()->rho_np1();
  Debog::verifier("divU tab_rhonP0",tab_rhonP0);
  Debog::verifier("divU tab_rhonp1P0",tab_rhonp1P0);
  const DoubleVect& volumes = la_zone->volumes();
  for (elem=0 ; elem<nb_elem ; elem++)
    tab_dZ(elem) = (tab_rhonp1P0(elem)-tab_rhonP0(elem))/dt;
  double tmp;
  for (elem=0 ; elem<nb_elem ; elem++)
    {
      tmp = tab_dZ(elem) ;
      tab_W(elem) = -tmp * volumes(elem);
    }
}
References la_zone, le_fluide(), Fluide_Dilatable_base::loi_etat(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Debog::verifier(), Fluide_Dilatable_base::vitesse(), and Zone_VF::volumes().
self_cast() [1/2]
const EOS_Tools_VDF & EOS_Tools_VDF::self_cast (const Objet_U & r) static
Definition at line 26 of file EOS_Tools_VDF.cpp.
self_cast() [2/2]
EOS_Tools_VDF & EOS_Tools_VDF::self_cast (Objet_U & r) static
Definition at line 26 of file EOS_Tools_VDF.cpp.
taille_memoire()
unsigned EOS_Tools_VDF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 26 of file EOS_Tools_VDF.cpp.
Member Data Documentation
info_obj
const Type_info EOS_Tools_VDF::info_obj static
Definition at line 37 of file EOS_Tools_VDF.h.
la_zone
Ref_Zone_VDF EOS_Tools_VDF::la_zone protected
Definition at line 51 of file EOS_Tools_VDF.h.
Referenced by associer_zones(), calculer_rho_face_np1(), divu_discvit(), moyenne_vol(), and secmembre_divU_Z().
la_zone_Cl
Ref_Zone_Cl_dis EOS_Tools_VDF::la_zone_Cl protected
Definition at line 52 of file EOS_Tools_VDF.h.
Referenced by associer_zones().
tab_rho_face
DoubleTab EOS_Tools_VDF::tab_rho_face protected
Definition at line 53 of file EOS_Tools_VDF.h.
Referenced by associer_zones(), calculer_rho_face_np1(), mettre_a_jour(), and rho_face_n().
tab_rho_face_demi
DoubleTab EOS_Tools_VDF::tab_rho_face_demi protected
Definition at line 53 of file EOS_Tools_VDF.h.
Referenced by associer_zones(), calculer_rho_face_np1(), mettre_a_jour(), and rho_discvit().
tab_rho_face_np1
DoubleTab EOS_Tools_VDF::tab_rho_face_np1 protected
Definition at line 53 of file EOS_Tools_VDF.h.
Referenced by associer_zones(), calculer_rho_face_np1(), mettre_a_jour(), and rho_face_np1().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/VDF/EOS_Tools_VDF.h
src/ThHyd/Dilatable/Common/VDF/EOS_Tools_VDF.cpp