TRUST: Op_Conv_BTD_EF Class Reference
Op_Conv_BTD_EF Class Reference
#include <Op_Conv_EF.h>
Public Member Functions
Op_Conv_BTD_EF ()
~Op_Conv_BTD_EF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Op_Conv_EF
Op_Conv_EF ()
~Op_Conv_EF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & ajouter_a_la_diffusion (const DoubleTab &, DoubleTab &) const
double calculer_dt_stab () const override
Calcul dt_stab.
void dimensionner (Matrice_Morse &matrice) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &inco, Matrice_Morse &matrice) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_au_second_membre (DoubleTab &resu) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution_sous_cond (const DoubleTab &transporte, Matrice_Morse &matrice, int btd_impl, int hourglass_impl, int centre_impl) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_a_la_diffusion (const DoubleTab &, Matrice_Morse &) const
void contribue_au_second_membre_a_la_diffusion (DoubleTab &resu) const
DoubleTab & ajouter_sous_cond (const DoubleTab &transporte, DoubleTab &resu, int btd_impl, int hourglass_impl, int centre_impl) const
virtual double coefficient_btd () const
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
double get_btd () const
const Champ_base & get_champ (const Motcle &nom) const override
Public Member Functions inherited from Op_Conv_EF_base
Op_Conv_EF_base ()
~Op_Conv_EF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_vitesse (const Champ_base &) override
const Champ_Inc_base & vitesse () const
Champ_Inc_base & vitesse ()
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
void abortTimeStep () override
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int) const override
virtual void remplir_fluent (DoubleVect &) const
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_zone_cl_dis (const Zone_Cl_dis_base &) override
int phi_u_transportant (const Equation_base &eq) const
definit si l'on convecte psi avec phi*u ou avec u
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
Public Member Functions inherited from Operateur_Conv_base
Operateur_Conv_base ()
initialise dt_stab_conv a -123
~Operateur_Conv_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_vitesse (const Champ_base &vit)=0
double dt_stab_conv () const
void fixer_dt_stab_conv (double dt)
virtual void associer_norme_vitesse (const Champ_base &norme_vitesse)
virtual void associer_vitesse_pour_pas_de_temps (const Champ_base &vitesse)
virtual void set_incompressible (const int)
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Op_EF_base
void dimensionner (const Zone_EF &, const Zone_Cl_EF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_EF &, const Zone_Cl_EF &, Matrice_Morse &, DoubleTab &) const
void modifier_flux (const Operateur_base &) const
int impr (Sortie &, const Operateur_base &) const
int elem_contribue (const int elem) const
void marque_elem (const Equation_base &eqn)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Conv_BTD_EF & self_cast (Objet_U &)
static const Op_Conv_BTD_EF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Conv_EF
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Conv_EF & self_cast (Objet_U &)
static const Op_Conv_EF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Conv_EF_base
static const Type_info * info ()
static Op_Conv_EF_base & self_cast (Objet_U &)
static const Op_Conv_EF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Conv_base
static const Type_info * info ()
static Operateur_Conv_base & self_cast (Objet_U &)
static const Operateur_Conv_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Conv_EF
static const Type_info info_obj
Static Public Attributes inherited from Op_Conv_EF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Conv_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
double coefficient_btd () const override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
Protected Member Functions inherited from Op_Conv_EF
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
DoubleTab & ajouter_sous_cond_gen (const DoubleTab &transporte, DoubleTab &resu, int btd_impl, int hourglass_impl, int centre_impl) const
DoubleTab & ajouter_sous_cond_dim3_nbn8_nbdim1 (const DoubleTab &transporte, DoubleTab &resu, int btd_impl, int hourglass_impl, int centre_impl) const
DoubleTab & ajouter_sous_cond_dim3_nbn8_nbdim2 (const DoubleTab &transporte, DoubleTab &resu, int btd_impl, int hourglass_impl, int centre_impl) const
DoubleTab & ajouter_sous_cond_dim2_nbn4_nbdim1 (const DoubleTab &transporte, DoubleTab &resu, int btd_impl, int hourglass_impl, int centre_impl) const
DoubleTab & ajouter_sous_cond_dim2_nbn4_nbdim2 (const DoubleTab &transporte, DoubleTab &resu, int btd_impl, int hourglass_impl, int centre_impl) const
template<AJOUTE_COND _COND_>
DoubleTab & ajouter_sous_cond_template (const DoubleTab &transporte, DoubleTab &resu, int btd_impl, int hourglass_impl, int centre_impl) const
Protected Member Functions inherited from Op_Conv_EF_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Operateur_Conv_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Attributes
double facteur_
Protected Attributes inherited from Op_Conv_EF
double hourglass
int hourglass_impl_
int btd_impl_
int centre_impl_
flag pour savoir si les termes sont implicites
int hourglass_hors_conv_
int btd_hors_conv_
double f_lu_
int calcul_dt_stab_
type_operateur type_op
double max_ue_
double min_dx_
Champ_Uniforme coefficient_correcteur_supg_
double btd_
Protected Attributes inherited from Op_Conv_EF_base
Ref_Zone_EF la_zone_EF
Ref_Zone_Cl_EF la_zcl_EF
Ref_Champ_Inc_base vitesse_
DoubleVect fluent
tableau qui sert pour le calcul du pas de temps de stabilite
Protected Attributes inherited from Operateur_Conv_base
Ref_Champ_base la_norme_vitesse
Ref_Champ_base vitesse_pour_pas_de_temps_
double dt_stab_conv_
int incompressible_ = 1
incompressible_= 1 -> l'operateur discretise div(v x inco), incompressible_ = 0 -> il discretise v.grad(inco)
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Protected Attributes inherited from Op_EF_base
Matrice_Morse matrice_sto_
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Protected Types inherited from Op_Conv_EF
enum type_operateur { amont , muscl , centre }
Detailed Description
Definition at line 89 of file Op_Conv_EF.h.
Constructor & Destructor Documentation
Op_Conv_BTD_EF()
Op_Conv_BTD_EF::Op_Conv_BTD_EF ()
Definition at line 25 of file Op_Conv_EF.cpp.
                               : Op_Conv_EF()
{
  calcul_dt_stab_=2;
  type_op = amont;
  hourglass=1;
  hourglass_impl_=1;
  btd_impl_=1;
  centre_impl_=1;
  btd_hors_conv_=1;
  hourglass_hors_conv_=1;
}
References Op_Conv_EF::amont, Op_Conv_EF::btd_hors_conv_, Op_Conv_EF::btd_impl_, Op_Conv_EF::calcul_dt_stab_, Op_Conv_EF::centre_impl_, Op_Conv_EF::hourglass, Op_Conv_EF::hourglass_hors_conv_, Op_Conv_EF::hourglass_impl_, and Op_Conv_EF::type_op.
~Op_Conv_BTD_EF()
Op_Conv_BTD_EF::~Op_Conv_BTD_EF ()
Definition at line 24 of file Op_Conv_EF.cpp.
Member Function Documentation
coefficient_btd()
double Op_Conv_BTD_EF::coefficient_btd () const override protected virtual
Reimplemented from Op_Conv_EF.
Reimplemented in Op_Conv_SUPG_EF.
Definition at line 56 of file Op_Conv_EF.cpp.
{
  if (equation().equation_non_resolue())
    calculer_dt_stab();
  double f=dt_stab_conv()*facteur_*btd_/2.;
  return f;
}
References Op_Conv_EF::btd_, Op_Conv_EF::calculer_dt_stab(), Operateur_Conv_base::dt_stab_conv(), MorEqn::equation(), and facteur_.
completer()
void Op_Conv_BTD_EF::completer () override protected virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Op_Conv_EF.
Definition at line 36 of file Op_Conv_EF.cpp.
{
// pour ne pas mettre les flags automatiquement
  Op_Conv_EF_base::completer();
}
References Op_Conv_EF_base::completer().
cree_instance()
Objet_U * Op_Conv_BTD_EF::cree_instance () static
Definition at line 24 of file Op_Conv_EF.cpp.
duplique()
int Op_Conv_BTD_EF::duplique () const override virtual
Reimplemented from Op_Conv_EF.
Reimplemented in Op_Conv_SUPG_EF.
Definition at line 24 of file Op_Conv_EF.cpp.
get_info()
const Type_info * Op_Conv_BTD_EF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_EF.
Reimplemented in Op_Conv_SUPG_EF.
Definition at line 24 of file Op_Conv_EF.cpp.
info()
const Type_info * Op_Conv_BTD_EF::info () static
Definition at line 24 of file Op_Conv_EF.cpp.
printOn()
Sortie & Op_Conv_BTD_EF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Op_Conv_EF.
Reimplemented in Op_Conv_SUPG_EF.
Definition at line 42 of file Op_Conv_EF.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
Referenced by Op_Conv_SUPG_EF::printOn().
readOn()
Entree & Op_Conv_BTD_EF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
< XD convection_btd convection_deriv btd 1 Only for EF discretization.
< XD_ADD_P double not_set
< XD_ADD_P double not_set
Reimplemented from Op_Conv_EF.
Reimplemented in Op_Conv_SUPG_EF.
Definition at line 46 of file Op_Conv_EF.cpp.
{
  Param param(que_suis_je()); //!< XD convection_btd convection_deriv btd 1 Only for EF discretization.
  param.ajouter("btd",&btd_,Param::REQUIRED); //!< XD_ADD_P double not_set
  param.ajouter("facteur",&facteur_,Param::REQUIRED);  //!< XD_ADD_P double not_set
  param.lire_avec_accolades(s);
  return s;
}
References Param::ajouter(), Op_Conv_EF::btd_, facteur_, Param::lire_avec_accolades(), Objet_U::que_suis_je(), and Param::REQUIRED.
self_cast() [1/2]
const Op_Conv_BTD_EF & Op_Conv_BTD_EF::self_cast (const Objet_U & r) static
Definition at line 24 of file Op_Conv_EF.cpp.
self_cast() [2/2]
Op_Conv_BTD_EF & Op_Conv_BTD_EF::self_cast (Objet_U & r) static
Definition at line 24 of file Op_Conv_EF.cpp.
taille_memoire()
unsigned Op_Conv_BTD_EF::taille_memoire () const override virtual
Reimplemented from Op_Conv_EF.
Reimplemented in Op_Conv_SUPG_EF.
Definition at line 24 of file Op_Conv_EF.cpp.
Member Data Documentation
facteur_
double Op_Conv_BTD_EF::facteur_ protected
Definition at line 95 of file Op_Conv_EF.h.
Referenced by coefficient_btd(), and readOn().
info_obj
const Type_info Op_Conv_BTD_EF::info_obj static
Definition at line 91 of file Op_Conv_EF.h.
The documentation for this class was generated from the following files:
src/EF/Operateurs/Op_Conv_EF.h
src/EF/Operateurs/Op_Conv_EF.cpp