TRUST: Turbulence_paroi_scal Class Reference
Turbulence_paroi_scal Class Reference
Classe Turbulence_paroi_scal
Classe generique de la hierarchie des turbulences au niveau de la
paroi, un objet Turbulence_paroi peut referencer n'importe quel
objet derivant Turbulence_paroi_base.
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;.
#include <Turbulence_paroi_scal.h>
Public Member Functions
Turbulence_paroi_scal ()
~Turbulence_paroi_scal ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Turbulence_paroi_scal & operator= (const Turbulence_paroi_scal_base &paroi_base)
Operateur d'affectation d'un objet Turbulence_paroi_scal_base
dans un objet Turbulence_paroi_scal.
void associer_modele (const Modele_turbulence_scal_base &)
Associe un modele de turbulence a l'objet.
int init_lois_paroi ()
Appel a l'objet sous-jacent.
Initialise les lois de parois.
int calculer_scal (Champ_Fonc &)
Appel a l'objet sous-jacent.
int calculer_scal (Champ_Fonc_base &)
Appel a l'objet sous-jacent.
void imprimer_nusselt (Sortie &) const
Appel a l'objet sous-jacent.
Imprime le nusselt de la loi de paroi.
int tab_equivalent_distance_size ()
Appel a l'objet sous-jacent.
const DoubleVect & tab_equivalent_distance (int bord) const
Appel a l'objet sous-jacent.
Public Member Functions inherited from Deriv_Turbulence_paroi_scal_base
~Deriv_Turbulence_paroi_scal_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Turbulence_paroi_scal_base ()
Deriv_Turbulence_paroi_scal_base (const Deriv_Turbulence_paroi_scal_base &)
const Turbulence_paroi_scal_base & valeur () const
Turbulence_paroi_scal_base & valeur ()
const Turbulence_paroi_scal_base * operator-> () const
Turbulence_paroi_scal_base * operator-> ()
const Deriv_Turbulence_paroi_scal_base & operator= (const Turbulence_paroi_scal_base &)
const Deriv_Turbulence_paroi_scal_base & operator= (const Deriv_Turbulence_paroi_scal_base &)
operator const Turbulence_paroi_scal_base & () const
operator Turbulence_paroi_scal_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Turbulence_paroi_scal & self_cast (Objet_U &)
static const Turbulence_paroi_scal & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Turbulence_paroi_scal_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Turbulence_paroi_scal_base & self_cast (Objet_U &)
static const Deriv_Turbulence_paroi_scal_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Turbulence_paroi_scal_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les caracteristques de la loi de parois
a partir d'un flot d'entree.
Format:
type_de_loi_de_paroi
Les valeurs possibles du type de loi de paroi sont:
- "loi_standard_hydr"
- "negligeable"
- "loi_VanDriest"
- "loi_standard_hydr_scalaire".
Protected Member Functions inherited from Deriv_Turbulence_paroi_scal_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Modele_turbulence_scal_base mon_modele_turb_scal
Detailed Description
Classe Turbulence_paroi_scal
Classe generique de la hierarchie des turbulences au niveau de la
paroi, un objet Turbulence_paroi peut referencer n'importe quel
objet derivant Turbulence_paroi_base.
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;.
Definition at line 41 of file Turbulence_paroi_scal.h.
Constructor & Destructor Documentation
Turbulence_paroi_scal()
Turbulence_paroi_scal::Turbulence_paroi_scal ()
Definition at line 25 of file Turbulence_paroi_scal.cpp.
~Turbulence_paroi_scal()
Turbulence_paroi_scal::~Turbulence_paroi_scal ()
Definition at line 25 of file Turbulence_paroi_scal.cpp.
Member Function Documentation
associer_modele()
void Turbulence_paroi_scal::associer_modele (const Modele_turbulence_scal_base & mod)
Associe un modele de turbulence a l'objet.
Definition at line 129 of file Turbulence_paroi_scal.cpp.
{
  mon_modele_turb_scal = mod;
}
References mon_modele_turb_scal.
Referenced by Modele_turbulence_scal_base::lire_motcle_non_standard().
calculer_scal() [1/2]
int Turbulence_paroi_scal::calculer_scal (Champ_Fonc & ch) inline
Appel a l'objet sous-jacent.
Returns
int
Signification: code de retour propage
Contraintes:
Definition at line 139 of file Turbulence_paroi_scal.h.
{
  return valeur().calculer_scal(ch);
}
References Turbulence_paroi_scal_base::calculer_scal(), and Deriv_Turbulence_paroi_scal_base::valeur().
calculer_scal() [2/2]
int Turbulence_paroi_scal::calculer_scal (Champ_Fonc_base & ch) inline
Appel a l'objet sous-jacent.
Returns
int
Signification: code de retour propage
Contraintes:
Definition at line 158 of file Turbulence_paroi_scal.h.
{
  return valeur().calculer_scal(ch);
}
References Turbulence_paroi_scal_base::calculer_scal(), and Deriv_Turbulence_paroi_scal_base::valeur().
cree_instance()
Objet_U * Turbulence_paroi_scal::cree_instance () static
Definition at line 25 of file Turbulence_paroi_scal.cpp.
duplique()
int Turbulence_paroi_scal::duplique () const override virtual
Reimplemented from Deriv_Turbulence_paroi_scal_base.
Definition at line 25 of file Turbulence_paroi_scal.cpp.
get_info()
const Type_info * Turbulence_paroi_scal::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Turbulence_paroi_scal_base.
Definition at line 25 of file Turbulence_paroi_scal.cpp.
imprimer_nusselt()
void Turbulence_paroi_scal::imprimer_nusselt (Sortie & os) const inline
Appel a l'objet sous-jacent.
Imprime le nusselt de la loi de paroi.
Definition at line 100 of file Turbulence_paroi_scal.h.
{
  valeur().imprimer_nusselt(os);
}
References Turbulence_paroi_scal_base::imprimer_nusselt(), and Deriv_Turbulence_paroi_scal_base::valeur().
Referenced by Modele_turbulence_scal_base::imprimer().
info()
const Type_info * Turbulence_paroi_scal::info () static
Definition at line 25 of file Turbulence_paroi_scal.cpp.
init_lois_paroi()
int Turbulence_paroi_scal::init_lois_paroi () inline
Appel a l'objet sous-jacent.
Initialise les lois de parois.
Returns
int
Signification: code de retour propage
Contraintes:
Definition at line 120 of file Turbulence_paroi_scal.h.
{
  return valeur().init_lois_paroi();
}
References Turbulence_paroi_scal_base::init_lois_paroi(), and Deriv_Turbulence_paroi_scal_base::valeur().
Referenced by Modele_turbulence_scal_base::preparer_calcul().
operator=()
Turbulence_paroi_scal & Turbulence_paroi_scal::operator= (const Turbulence_paroi_scal_base & paroi_base) inline
Operateur d'affectation d'un objet Turbulence_paroi_scal_base
dans un objet Turbulence_paroi_scal.
Returns
Turbulence_paroi_scal&
Signification: le resultat de l'affectation (*this)
Contraintes:
Definition at line 79 of file Turbulence_paroi_scal.h.
{
  DERIV(Turbulence_paroi_scal_base)::operator=(paroi_base);
  return *this;
}
References DERIV, and operator=().
Referenced by operator=().
printOn()
Sortie & Turbulence_paroi_scal::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Turbulence_paroi_scal_base.
Definition at line 42 of file Turbulence_paroi_scal.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References O_U_Ptr::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Turbulence_paroi_scal::readOn (Entree & s) override protected virtual
Lit les caracteristques de la loi de parois
a partir d'un flot d'entree.
Format:
type_de_loi_de_paroi
Les valeurs possibles du type de loi de paroi sont:
- "loi_standard_hydr"
- "negligeable"
- "loi_VanDriest"
- "loi_standard_hydr_scalaire".
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Turbulence_paroi_scal_base.
Definition at line 70 of file Turbulence_paroi_scal.cpp.
{
  Cerr << "Lecture du type de loi de parois " << finl;
// On recupere l'equation hydraulique
  const Equation_base& eqn = mon_modele_turb_scal->equation().probleme().equation(0);
  Motcle typ;
  s >> typ;
  const RefObjU& modele_turbulence = eqn.get_modele(TURBULENCE);
  const Mod_turb_hyd_base& mod_turb_hydr = ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur());
  const Turbulence_paroi& loi = mod_turb_hydr.loi_paroi();
  if (typ!="negligeable_scalaire")
    if ((loi.valeur().que_suis_je()=="negligeable_VDF") || (loi.valeur().que_suis_je()=="negligeable_VEF"))
      {
        Cerr<<"La loi de paroi de type "<<typ<<" choisie pour le scalaire n'est pas compatible avec"<<finl;
        Cerr<<"la loi de type "<<loi.valeur().que_suis_je()<<" choisie pour l'hydraulique"<<finl;
        Cerr<<"Utiliser le type 'negligeable_scalaire' pour le scalaire ou utiliser une loi de paroi"<<finl;
        Cerr<<"non negligeable pour l hydraulique"<<finl;
        exit();
      }
  typ+="_";
  Nom discr=eqn.discretisation().que_suis_je();
// les operateurs de diffusion sont communs aux discretisations VEF et VEFP1B
  if(discr=="VEFPreP1B") discr="VEF";
  typ+=discr;
  if (typ=="loi_analytique_scalaire_VDF")
    {
      Cerr<<"La loi de paroi scalaire de type loi_analytique_scalaire"<<finl;
      Cerr<<"n est utilisable qu avec une discretisation de type VEF"<<finl;
      exit();
    }
  Cerr<<"et typage :"<<typ<<finl;
  DERIV(Turbulence_paroi_scal_base)::typer(typ);
  valeur().associer_modele(mon_modele_turb_scal.valeur());
  valeur().associer(eqn.zone_dis(),eqn.zone_Cl_dis());
  return s;
}
References Turbulence_paroi_scal_base::associer(), Turbulence_paroi_scal_base::associer_modele(), Cerr, DERIV, Equation_base::discretisation(), Modele_turbulence_scal_base::equation(), Probleme_base::equation(), Process::exit(), finl, Equation_base::get_modele(), Mod_turb_hyd_base::loi_paroi(), mon_modele_turb_scal, Equation_base::probleme(), Objet_U::que_suis_je(), ref_cast, TURBULENCE, Deriv_::typer(), Ref_Objet_U::valeur(), Ref_Modele_turbulence_scal_base::valeur(), Deriv_Turbulence_paroi_base::valeur(), Deriv_Turbulence_paroi_scal_base::valeur(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
self_cast() [1/2]
const Turbulence_paroi_scal & Turbulence_paroi_scal::self_cast (const Objet_U & r) static
Definition at line 25 of file Turbulence_paroi_scal.cpp.
self_cast() [2/2]
Turbulence_paroi_scal & Turbulence_paroi_scal::self_cast (Objet_U & r) static
Definition at line 25 of file Turbulence_paroi_scal.cpp.
tab_equivalent_distance()
const DoubleVect & Turbulence_paroi_scal::tab_equivalent_distance (int boundary_index) const inline
Appel a l'objet sous-jacent.
Returns
Doublevect
Signification: return equivalent distances associated to boundary index
Contraintes:
Definition at line 196 of file Turbulence_paroi_scal.h.
{
  return valeur().tab_equivalent_distance(boundary_index);
}
References Turbulence_paroi_scal_base::tab_equivalent_distance(), and Deriv_Turbulence_paroi_scal_base::valeur().
Referenced by Eval_Turbulence::update_equivalent_distance().
tab_equivalent_distance_size()
int Turbulence_paroi_scal::tab_equivalent_distance_size () inline
Appel a l'objet sous-jacent.
Returns
int
Signification: return size of tabular containing equivalent distances associated to all boundaries, so it is equivalent to number of boundaries
Contraintes:
Definition at line 177 of file Turbulence_paroi_scal.h.
{
  return valeur().tab_equivalent_distance_size();
}
References Turbulence_paroi_scal_base::tab_equivalent_distance_size(), and Deriv_Turbulence_paroi_scal_base::valeur().
Referenced by Eval_Turbulence::update_equivalent_distance().
taille_memoire()
unsigned Turbulence_paroi_scal::taille_memoire () const override virtual
Reimplemented from Deriv_Turbulence_paroi_scal_base.
Definition at line 25 of file Turbulence_paroi_scal.cpp.
Member Data Documentation
info_obj
const Type_info Turbulence_paroi_scal::info_obj static
Definition at line 44 of file Turbulence_paroi_scal.h.
mon_modele_turb_scal
Ref_Modele_turbulence_scal_base Turbulence_paroi_scal::mon_modele_turb_scal protected
Definition at line 60 of file Turbulence_paroi_scal.h.
Referenced by associer_modele(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Modele_turbulence_base/Turbulence_paroi_scal.h
src/ThHyd/Modele_turbulence_base/Turbulence_paroi_scal.cpp