TRUST: Champ_front_xyz_debit Class Reference
Champ_front_xyz_debit Class Reference
class Champ_front_xyz_debit
#include <Champ_front_xyz_debit.h>
Public Member Functions
Champ_front_xyz_debit ()
~Champ_front_xyz_debit ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double tps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
virtual void update_coeff (double temps)
void mettre_a_jour (double temps) override
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
void associer_fr_dis_base (const Frontiere_dis_base &fr) override
Associe une frontiere discretisee au champ.
void set_temps_defaut (double temps)
void fixer_nb_valeurs_temporelles (int nb_cases) override
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
void changer_temps_futur (double temps, int i) override
int avancer (double temps) override
Turn the wheel of the CL.
int reculer (double temps) override
Turn the wheel of the CL.
Public Member Functions inherited from Champ_front_normal
Champ_front_normal ()
~Champ_front_normal ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base & affecter_ (const Champ_front_base &ch) override
Pas code !!
Public Member Functions inherited from Ch_front_var_instationnaire_dep
Ch_front_var_instationnaire_dep ()
~Ch_front_var_instationnaire_dep ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Champ_front_base & affecter_ (const Champ_front_base &ch) override
Public Member Functions inherited from Champ_front_var_instationnaire
Champ_front_var_instationnaire ()
~Champ_front_var_instationnaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialise le temps courant et Gpoint.
DoubleTab & Gpoint ()
const DoubleTab & Gpoint () const
void Gpoint (double t1, double t2)
DoubleTab & valeurs_au_temps (double temps) override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
const DoubleTab & valeurs_au_temps (double temps) const override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
int avancer (double temps) override
Avance jusqu'au temps desire.
Sinon, sort en erreur.
int reculer (double temps) override
Recule jusqu'au temps desire.
Sinon, sort en erreur.
virtual double valeur_au_temps_et_au_point (double temps, int som, double x, double y, double z, int comp) const
virtual int valeur_au_temps_et_au_point_disponible () const
Public Member Functions inherited from Champ_front_var
Champ_front_var ()
~Champ_front_var () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Public Member Functions inherited from Champ_front_base
~Champ_front_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base ()
virtual void completer ()
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe une frontiere discretisee au champ.
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
virtual DoubleTab & valeurs_au_temps (double temps)=0
virtual const DoubleTab & valeurs_au_temps (double temps) const =0
const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee associee au champ.
(version const)
Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee associee au champ.
const Zone_dis_base & zone_dis () const
virtual Champ_front_base & affecter_ (const Champ_front_base &ch)=0
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
virtual void calculer_coeffs_echange (double temps)
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
virtual void valeurs_face (int, DoubleVect &) const
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
virtual void verifier (const Cond_lim_base &la_cl) const
double get_temps_defaut () const
void set_temps_defaut (double temps)
virtual void changer_temps_futur (double temps, int i)
virtual int avancer (double temps)
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe
en parametre.
virtual int reculer (double temps)
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe
en parametre.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_front_xyz_debit & self_cast (Objet_U &)
static const Champ_front_xyz_debit & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_normal
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_front_normal & self_cast (Objet_U &)
static const Champ_front_normal & self_cast (const Objet_U &)
Static Public Member Functions inherited from Ch_front_var_instationnaire_dep
static Objet_U * cree_instance ()
static const Type_info * info ()
static Ch_front_var_instationnaire_dep & self_cast (Objet_U &)
static const Ch_front_var_instationnaire_dep & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var_instationnaire
static const Type_info * info ()
static Champ_front_var_instationnaire & self_cast (Objet_U &)
static const Champ_front_var_instationnaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var
static const Type_info * info ()
static Champ_front_var & self_cast (Objet_U &)
static const Champ_front_var & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_base
static const Type_info * info ()
static Champ_front_base & self_cast (Objet_U &)
static const Champ_front_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_normal
static const Type_info info_obj
Static Public Attributes inherited from Ch_front_var_instationnaire_dep
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var_instationnaire
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual void initialiser_coefficient (const Champ_Inc_base &inco, double tps)
void calculer_normales_et_integrale (const Front_VF &le_bord, DoubleTab &velocity_user)
void calculer_champ_vitesse (const Front_VF &le_bord, DoubleTab &velocity_field, DoubleTab &velocity_user, double temps)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Ch_front_var_instationnaire_dep
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Champ_front_var_instationnaire
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_front velocity_profil_
Champ_front flow_rate_
DoubleTab normal_vectors_
DoubleTab coeff_
DoubleTab integrale_
bool flow_rate_alone_ =0
bool update_coeff_ = false
Protected Attributes inherited from Champ_front_normal
Parser_U vit_norm
Protected Attributes inherited from Champ_front_var_instationnaire
DoubleTab Gpoint_
Taux d'accroissement du champ.
Protected Attributes inherited from Champ_front_base
double temps_defaut
Le temps pris par defaut quand le parametre n'est pas specifie. Ce sera en particulier celui utilise par les operateurs et les solveurs.
Ref_Frontiere_dis_base la_frontiere_dis
Roue_ptr les_valeurs
Les valeurs du champ.
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
class Champ_front_xyz_debit
Definition at line 30 of file Champ_front_xyz_debit.h.
Constructor & Destructor Documentation
Champ_front_xyz_debit()
Champ_front_xyz_debit::Champ_front_xyz_debit ()
Definition at line 24 of file Champ_front_xyz_debit.cpp.
~Champ_front_xyz_debit()
Champ_front_xyz_debit::~Champ_front_xyz_debit ()
Definition at line 24 of file Champ_front_xyz_debit.cpp.
Member Function Documentation
associer_fr_dis_base()
void Champ_front_xyz_debit::associer_fr_dis_base (const Frontiere_dis_base & fr) override virtual
Associe une frontiere discretisee au champ.
Reimplemented from Champ_front_base.
Definition at line 135 of file Champ_front_xyz_debit.cpp.
{
  flow_rate_.valeur().associer_fr_dis_base(fr);
// Cerr << "Champ_front_xyz_debit::associer_fr_dis_base flow_rate_alone_ " << flow_rate_alone_ << finl;
  if (!flow_rate_alone_)
    velocity_profil_.valeur().associer_fr_dis_base(fr);
  Champ_front_normal::associer_fr_dis_base(fr);
}
References Champ_front_base::associer_fr_dis_base(), flow_rate_, flow_rate_alone_, Deriv_Champ_front_base::valeur(), and velocity_profil_.
avancer()
int Champ_front_xyz_debit::avancer (double temps) override virtual
Turn the wheel of the CL.
Reimplemented from Champ_front_base.
Definition at line 173 of file Champ_front_xyz_debit.cpp.
{
// Cerr << "Champ_front_xyz_debit::avancer" << finl;
  Champ_front_normal::avancer(temps);
  if (flow_rate_.valeur().avancer(temps))
    if (!flow_rate_alone_)
      return velocity_profil_.valeur().avancer(temps);
    else
      return 1;
  else
    return 0;
}
References Champ_front_base::avancer(), Champ_front_var_instationnaire::avancer(), flow_rate_, flow_rate_alone_, Deriv_Champ_front_base::valeur(), and velocity_profil_.
calculer_champ_vitesse()
void Champ_front_xyz_debit::calculer_champ_vitesse (const Front_VF & le_bord, DoubleTab & velocity_field, DoubleTab & velocity_user, double temps) protected
Definition at line 121 of file Champ_front_xyz_debit.cpp.
{
  const int N = flow_rate_.nb_comp();
  for(int i = 0; i < le_bord.nb_faces_tot(); i++)
    for (int n = 0; n < N; ++n)
      for(int j = 0; j < dimension; j++)
        {
          double v_mult = flow_rate_.valeur().valeurs_au_temps(temps)(0, n) / integrale_(n) ; //the profile/normals must be multiplied by this to get the correct inward flow
          double n_mult = flow_rate_alone_ ? normal_vectors_(i,j) : (velocity_user(velocity_user.size() > dimension ? i : 0, j));
          velocity_field(i, N * j + n) = v_mult * n_mult;
        }
}
References Objet_U::dimension, flow_rate_, flow_rate_alone_, integrale_, Champ_front::nb_comp(), Front_VF::nb_faces_tot(), normal_vectors_, TRUSTVect< _TYPE_ >::size(), Deriv_Champ_front_base::valeur(), and Champ_front_base::valeurs_au_temps().
Referenced by initialiser(), and mettre_a_jour().
calculer_normales_et_integrale()
void Champ_front_xyz_debit::calculer_normales_et_integrale (const Front_VF & le_bord, DoubleTab & velocity_user) protected
< inward normal
Definition at line 89 of file Champ_front_xyz_debit.cpp.
{
  const int N = flow_rate_.nb_comp();
  const Zone_VF& zone_VF = ref_cast(Zone_VF,zone_dis());
  integrale_ = 0.;
  for(int i = 0; i < le_bord.nb_faces_tot(); i++)
    {
      int f = le_bord.num_face(i);
      const double dS = zone_VF.face_surfaces(f);
      for (int n = 0; n < N; ++n)
        {
          double u_scal_n = 0;
          for(int j = 0; j < dimension; j++)
            {
              normal_vectors_(i, j) = -zone_VF.normalized_boundaries_outward_vector(f, 1.)(j); //!< inward normal
              u_scal_n += normal_vectors_(i, j) * (velocity_user.size() ? velocity_user(velocity_user.size() > dimension ? i : 0, j) : normal_vectors_(i, j));
            }
          if (i < le_bord.nb_faces()) integrale_(n) += dS * u_scal_n / coeff_(i, n) * zone_VF.porosite_face(f); //real faces only
        }
    }
  for (int n = 0; n < N; ++n)
    integrale_(n) = mp_sum(integrale_(n));
}
References coeff_, Objet_U::dimension, Zone_VF::face_surfaces(), flow_rate_, integrale_, Process::mp_sum(), Champ_front::nb_comp(), Front_VF::nb_faces(), Front_VF::nb_faces_tot(), normal_vectors_, Zone_VF::normalized_boundaries_outward_vector(), Front_VF::num_face(), Zone_VF::porosite_face(), ref_cast, TRUSTVect< _TYPE_ >::size(), and Champ_front_base::zone_dis().
Referenced by initialiser(), and mettre_a_jour().
changer_temps_futur()
void Champ_front_xyz_debit::changer_temps_futur (double temps, int i) override virtual
Reimplemented from Champ_front_base.
Definition at line 162 of file Champ_front_xyz_debit.cpp.
{
// Cerr << "Champ_front_xyz_debit::changer_temps_futur" << finl;
  Champ_front_normal::changer_temps_futur(temps,i);
  flow_rate_.valeur().changer_temps_futur(temps,i);
  if (!flow_rate_alone_)
    velocity_profil_.valeur().changer_temps_futur(temps,i);
}
References Champ_front_base::changer_temps_futur(), flow_rate_, flow_rate_alone_, Deriv_Champ_front_base::valeur(), and velocity_profil_.
cree_instance()
Objet_U * Champ_front_xyz_debit::cree_instance () static
Definition at line 24 of file Champ_front_xyz_debit.cpp.
duplique()
int Champ_front_xyz_debit::duplique () const override virtual
Reimplemented from Champ_front_normal.
Definition at line 24 of file Champ_front_xyz_debit.cpp.
fixer_nb_valeurs_temporelles()
void Champ_front_xyz_debit::fixer_nb_valeurs_temporelles (int nb_cases) override virtual
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
Reimplemented from Champ_front_base.
Definition at line 153 of file Champ_front_xyz_debit.cpp.
{
// Cerr << "Champ_front_xyz_debit::fixer_nb_valeurs_temporelles" << finl;
  flow_rate_.valeur().fixer_nb_valeurs_temporelles(nb_cases);
  if (!flow_rate_alone_)
    velocity_profil_.valeur().fixer_nb_valeurs_temporelles(nb_cases);
  Champ_front_normal::fixer_nb_valeurs_temporelles(nb_cases);
}
References Champ_front_base::fixer_nb_valeurs_temporelles(), Champ_front_var_instationnaire::fixer_nb_valeurs_temporelles(), flow_rate_, flow_rate_alone_, Deriv_Champ_front_base::valeur(), and velocity_profil_.
get_info()
const Type_info * Champ_front_xyz_debit::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_normal.
Definition at line 24 of file Champ_front_xyz_debit.cpp.
info()
const Type_info * Champ_front_xyz_debit::info () static
Definition at line 24 of file Champ_front_xyz_debit.cpp.
initialiser()
int Champ_front_xyz_debit::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
< cases number of the wheel
< values of the field at time t, type Roue_ptr
Reimplemented from Champ_front_base.
Definition at line 43 of file Champ_front_xyz_debit.cpp.
{
// Cerr << "Champ_front_xyz_debit::initialiser" << finl;
  if (!Champ_front_normal::initialiser(tps,inco))
    return 0;
  const Front_VF& le_bord= ref_cast(Front_VF,frontiere_dis());
  flow_rate_.valeur().initialiser(tps,inco);
  if ( !sub_type(Champ_front_uniforme,flow_rate_.valeur()) && !sub_type(Ch_front_input_uniforme,flow_rate_.valeur()) && !sub_type(Champ_front_t,flow_rate_.valeur()) && !sub_type(Champ_front_Tabule,flow_rate_.valeur()))
    {
      Cerr << "\nError in Champ_front_xyz_debit::initialiser() \nflow_rate must be of type champ_front_uniforme, ch_front_input_uniforme, champ_front_tabule or champ_front_fonc_t!" << finl;
      exit();
    }
  if (!flow_rate_alone_)
    {
      velocity_profil_.valeur().initialiser(tps,inco);
      if (velocity_profil_.valeur().nb_comp()!=dimension)
        {
          Cerr << "\nError in Champ_front_xyz_debit::initialiser() \nvelocity_profil must have " << dimension << " components!" << finl;
          exit();
        }
    }
  initialiser_coefficient(inco, tps);
// For tabular sizing only
  normal_vectors_=les_valeurs[0].valeurs();
  integrale_.resize(flow_rate_.valeur().valeurs().line_size());
  DoubleTab velocity_user;
  if (!flow_rate_alone_)
    velocity_user=velocity_profil_.valeur().valeurs();
  calculer_normales_et_integrale(le_bord,velocity_user);
// the flow rate Q_user and the velocity profil U_user are imposed on the boundary
// so the velocity field u is computed as following :
// u = (Q_user U_user n)/ Integrale(U_user . n dS)
// where n is the normal vector associated to the boundary
// fill at every time
  int nb_cases=les_valeurs->nb_cases(); //!< cases number of the wheel
  for (int t=0; t<nb_cases; t++)
    {
      DoubleTab& velocity_field=les_valeurs[t].valeurs(); //!< values of the field at time t, type Roue_ptr
      calculer_champ_vitesse(le_bord, velocity_field, velocity_user, tps);
    }
  return 1;
}
References calculer_champ_vitesse(), calculer_normales_et_integrale(), Cerr, Objet_U::dimension, Process::exit(), finl, flow_rate_, flow_rate_alone_, Champ_front_base::frontiere_dis(), Champ_front_base::initialiser(), Ch_front_var_instationnaire_dep::initialiser(), initialiser_coefficient(), integrale_, Champ_front_base::les_valeurs, TRUSTVect< _TYPE_ >::line_size(), Roue::nb_cases(), Field_base::nb_comp(), normal_vectors_, ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Deriv_Champ_front_base::valeur(), Champ_front_base::valeurs(), and velocity_profil_.
Referenced by Champ_front_debit::initialiser().
initialiser_coefficient()
void Champ_front_xyz_debit::initialiser_coefficient (const Champ_Inc_base & inco, double tps) protected virtual
Reimplemented in Champ_front_debit_massique.
Definition at line 114 of file Champ_front_xyz_debit.cpp.
{
  const Front_VF& le_bord = ref_cast(Front_VF,frontiere_dis());
  coeff_.resize(le_bord.nb_faces_tot(), flow_rate_.nb_comp());
  coeff_ = 1.;
}
References coeff_, flow_rate_, Champ_front_base::frontiere_dis(), Champ_front::nb_comp(), Front_VF::nb_faces_tot(), ref_cast, and TRUSTTab< _TYPE_ >::resize().
Referenced by initialiser(), and Champ_front_debit_massique::initialiser_coefficient().
mettre_a_jour()
void Champ_front_xyz_debit::mettre_a_jour (double temps) override virtual
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
< values of the field at time t, type Roue_ptr
Reimplemented from Champ_front_base.
Definition at line 201 of file Champ_front_xyz_debit.cpp.
{
// Cerr << "Champ_front_xyz_debit::mettre_a_jour  temps = " << temps << finl;
  if (update_coeff_) update_coeff(temps);
  DoubleTab velocity_user;
  flow_rate_.valeur().mettre_a_jour(temps);
  if (!flow_rate_alone_)
    {
      velocity_profil_.valeur().mettre_a_jour(temps);
      velocity_user=velocity_profil_.valeur().valeurs_au_temps(temps);
    }
  else
    {
      velocity_user.resize(1,dimension);
      velocity_user=1;
    }
  if (update_coeff_) calculer_normales_et_integrale(ref_cast(Front_VF,frontiere_dis()),velocity_user);
  DoubleTab& velocity_field=valeurs_au_temps(temps); //!< values of the field at time t, type Roue_ptr
  const Front_VF& le_bord= ref_cast(Front_VF,frontiere_dis());
  if (velocity_field.size_array())
    calculer_champ_vitesse(le_bord, velocity_field, velocity_user, temps);
}
References calculer_champ_vitesse(), calculer_normales_et_integrale(), Objet_U::dimension, flow_rate_, flow_rate_alone_, Champ_front_base::frontiere_dis(), Champ_front_base::mettre_a_jour(), ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::size_array(), update_coeff(), update_coeff_, Deriv_Champ_front_base::valeur(), Champ_front_var_instationnaire::valeurs_au_temps(), Champ_front_base::valeurs_au_temps(), and velocity_profil_.
printOn()
Sortie & Champ_front_xyz_debit::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_normal.
Definition at line 27 of file Champ_front_xyz_debit.cpp.
{
  return Champ_front_normal::printOn(os);
}
References Champ_front_normal::printOn().
Referenced by Champ_front_debit::printOn().
readOn()
Entree & Champ_front_xyz_debit::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
< XD_ADD_P front_field_base velocity_profil 0 velocity field to define the profil of velocity.
< XD_ADD_P front_field_base flow_rate 1 uniform field in space to define the flow rate. It could be, for example, champ_front_uniforme, ch_front_input_uniform or champ_front_fonc_t
Reimplemented from Champ_front_normal.
Definition at line 33 of file Champ_front_xyz_debit.cpp.
{
  Param param(que_suis_je());
  param.ajouter("velocity_profil", &velocity_profil_, Param::OPTIONAL); //!< XD_ADD_P front_field_base velocity_profil 0 velocity field to define the profil of velocity.
  param.ajouter("flow_rate", &flow_rate_, Param::REQUIRED); //!<  XD_ADD_P front_field_base flow_rate 1 uniform field in space to define the flow rate. It could be, for example, champ_front_uniforme, ch_front_input_uniform or champ_front_fonc_t
  param.lire_avec_accolades_depuis(is);
  fixer_nb_comp(dimension * flow_rate_.nb_comp());
  return is;
}
References Param::ajouter(), Objet_U::dimension, Field_base::fixer_nb_comp(), flow_rate_, Param::lire_avec_accolades_depuis(), Champ_front::nb_comp(), Param::OPTIONAL, Objet_U::que_suis_je(), Param::REQUIRED, and velocity_profil_.
reculer()
int Champ_front_xyz_debit::reculer (double temps) override virtual
Turn the wheel of the CL.
Reimplemented from Champ_front_base.
Definition at line 188 of file Champ_front_xyz_debit.cpp.
{
// Cerr << "Champ_front_xyz_debit::reculer" << finl;
  Champ_front_normal::reculer(temps);
  if (flow_rate_.valeur().reculer(temps))
    if (!flow_rate_alone_)
      return velocity_profil_.valeur().reculer(temps);
    else
      return 1;
  else
    return 0;
}
References flow_rate_, flow_rate_alone_, Champ_front_base::reculer(), Champ_front_var_instationnaire::reculer(), Deriv_Champ_front_base::valeur(), and velocity_profil_.
self_cast() [1/2]
const Champ_front_xyz_debit & Champ_front_xyz_debit::self_cast (const Objet_U & r) static
Definition at line 24 of file Champ_front_xyz_debit.cpp.
self_cast() [2/2]
Champ_front_xyz_debit & Champ_front_xyz_debit::self_cast (Objet_U & r) static
Definition at line 24 of file Champ_front_xyz_debit.cpp.
set_temps_defaut()
void Champ_front_xyz_debit::set_temps_defaut (double temps)
Definition at line 144 of file Champ_front_xyz_debit.cpp.
{
// Cerr << "Champ_front_xyz_debit::set_temps_defaut" << finl;
  flow_rate_.valeur().set_temps_defaut(temps);
  if (!flow_rate_alone_)
    velocity_profil_.valeur().set_temps_defaut(temps);
  Champ_front_normal::set_temps_defaut(temps);
}
References flow_rate_, flow_rate_alone_, Champ_front_base::set_temps_defaut(), Deriv_Champ_front_base::valeur(), and velocity_profil_.
taille_memoire()
unsigned Champ_front_xyz_debit::taille_memoire () const override virtual
Reimplemented from Champ_front_normal.
Definition at line 24 of file Champ_front_xyz_debit.cpp.
update_coeff()
virtual void Champ_front_xyz_debit::update_coeff (double temps) inline virtual
Reimplemented in Champ_front_debit_massique.
Definition at line 52 of file Champ_front_xyz_debit.h.
{ };
Referenced by mettre_a_jour().
Member Data Documentation
coeff_
DoubleTab Champ_front_xyz_debit::coeff_ protected
Definition at line 41 of file Champ_front_xyz_debit.h.
Referenced by calculer_normales_et_integrale(), initialiser_coefficient(), and Champ_front_debit_massique::update_coeff().
flow_rate_
Champ_front Champ_front_xyz_debit::flow_rate_ protected
Definition at line 36 of file Champ_front_xyz_debit.h.
Referenced by associer_fr_dis_base(), avancer(), calculer_champ_vitesse(), calculer_normales_et_integrale(), changer_temps_futur(), fixer_nb_valeurs_temporelles(), initialiser(), initialiser_coefficient(), mettre_a_jour(), Champ_front_debit::readOn(), readOn(), reculer(), and set_temps_defaut().
flow_rate_alone_
bool Champ_front_xyz_debit::flow_rate_alone_ =0 protected
Definition at line 43 of file Champ_front_xyz_debit.h.
Referenced by associer_fr_dis_base(), avancer(), calculer_champ_vitesse(), changer_temps_futur(), fixer_nb_valeurs_temporelles(), initialiser(), mettre_a_jour(), Champ_front_debit::readOn(), reculer(), and set_temps_defaut().
info_obj
const Type_info Champ_front_xyz_debit::info_obj static
Definition at line 32 of file Champ_front_xyz_debit.h.
integrale_
DoubleTab Champ_front_xyz_debit::integrale_ protected
Definition at line 42 of file Champ_front_xyz_debit.h.
Referenced by calculer_champ_vitesse(), calculer_normales_et_integrale(), and initialiser().
normal_vectors_
DoubleTab Champ_front_xyz_debit::normal_vectors_ protected
Definition at line 40 of file Champ_front_xyz_debit.h.
Referenced by calculer_champ_vitesse(), calculer_normales_et_integrale(), and initialiser().
update_coeff_
bool Champ_front_xyz_debit::update_coeff_ = false protected
Definition at line 44 of file Champ_front_xyz_debit.h.
Referenced by Champ_front_debit_massique::initialiser_coefficient(), and mettre_a_jour().
velocity_profil_
Champ_front Champ_front_xyz_debit::velocity_profil_ protected
Definition at line 35 of file Champ_front_xyz_debit.h.
Referenced by associer_fr_dis_base(), avancer(), changer_temps_futur(), fixer_nb_valeurs_temporelles(), initialiser(), mettre_a_jour(), readOn(), reculer(), and set_temps_defaut().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_front_xyz_debit.h
src/Kernel/Champs/Champ_front_xyz_debit.cpp