TRUST: Zone_EF Class Reference
Zone_EF Class Reference
class Zone_EF
Classe instanciable qui derive de Zone_VF.
Cette classe contient les informations geometriques que demande
la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
La classe porte un certain nombre d'informations concernant les faces
Dans cet ensemble de faces on fait figurer aussi les faces du bord et
des joints. Pour manipuler les faces on distingue 2 categories:
- les faces non standard qui sont sur un joint, un bord ou qui sont
internes tout en appartenant a un element du bord
- les faces standard qui sont les faces internes n'appartenant pas
a un element du bord
Cette distinction correspond au traitement des conditions aux limites:les
faces standard ne "voient pas" les conditions aux limites.
L'ensemble des faces est numerote comme suit:
- les faces qui sont sur une Zone_joint apparaissent en premier
(dans l'ordre du vecteur les_joints)
- les faces qui sont sur une Zone_bord apparaissent ensuite
(dans l'ordre du vecteur les_bords)
- les faces internes non standard apparaissent ensuite
- les faces internes standard en dernier
Finalement on trouve regroupees en premier toutes les faces non standard
qui vont necessiter un traitement particulier
On distingue deux types d'elements
- les elements non standard : ils ont au moins une face de bord
- les elements standard : ils n'ont pas de face de bord
Les elements standard (resp. les elements non standard) ne sont pas ranges
de maniere consecutive dans l'objet Zone. On utilise le tableau
rang_elem_non_std pour acceder de maniere selective a l'un ou
l'autre des types d'elements
#include <Zone_EF.h>
Public Member Functions
Zone_EF ()
~Zone_EF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void typer_elem (Zone &zone_geom) override
void discretiser () override
void swap (int, int, int)
void reordonner (Faces &) override
Methode appelee par Zone_VF::discretiser apres la creation
des faces reelles.
On reordonne les faces de sorte a placer les faces "non standard"
au debut de la liste des faces. Les faces non standard sont celles
dont les volumes de controles sont modifies par les conditions aux
limites.
void modifier_pour_Cl (const Conds_lim &) override
const Elem_EF & type_elem () const
int nb_elem_Cl () const
int nb_faces_joint () const
int nb_faces_std () const
int nb_elem_std () const
double carre_pas_du_maillage () const
double carre_pas_maille (int i) const
double face_normales (int, int) const override
DoubleTab & face_normales ()
const DoubleTab & face_normales () const
IntVect & rang_elem_non_std ()
const IntVect & rang_elem_non_std () const
int oriente_normale (int face_opp, int elem2) const
const ArrOfInt & ind_faces_virt_non_std () const
void calculer_volumes_entrelaces ()
void calculer_volumes_sommets ()
virtual void calculer_IPhi ()
virtual void calculer_Bij (DoubleTab &bij_)
virtual void calculer_Bij_gen (DoubleTab &bij)
const DoubleVect & volumes_thilde () const
const DoubleVect & volumes_sommets_thilde () const
const DoubleVect & porosite_sommet () const
DoubleVect & set_porosite_sommet ()
void calculer_h_carre ()
void calculer_porosites_sommets ()
const DoubleTab & Bij () const
const DoubleTab & Bij_thilde () const
const DoubleTab & IPhi () const
const DoubleTab & IPhi_thilde () const
virtual void verifie_compatibilite_domaine ()
Public Member Functions inherited from Zone_VF
Zone_VF ()
~Zone_VF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double face_normales (int, int) const =0
void calculer_face_surfaces (const DoubleVect &surfaces)
virtual const DoubleVect & face_surfaces () const
virtual double face_surfaces (int i) const
virtual double surface (int i) const
void discretiser () override
Genere les faces
construits les frontieres.
void infobord ()
void info_elem_som ()
void calculer_porosites ()
void calculer_diametres_hydrauliques ()
void calculer_sections_passage ()
void calculer_coefficient_echange_thermique ()
void calculer_coefficient_frottement ()
void marquer_faces_double_contrib (const Conds_lim &)
virtual void typer_elem (Zone &)
virtual void remplir_face_voisins_fictifs (const Zone_Cl_dis_base &)
virtual Faces * creer_faces ()
renvoie new(Faces) !
elle est surchargee par Zone_VDF par ex.
virtual void reordonner (Faces &)
cette methode ne fait rien
elle est surchargee par Zone_VDF par ex.
int nb_joints () const
renvoie le nombre de joints
int premiere_face_int () const
une face est interne ssi elle separe deux elements.
renvoie le numero de la premiere face interne.
int nb_faces () const
renvoie le nombre global de faces.
int nb_faces_tot () const
renvoie le nombre total de faces.
C'est-a-dire faces reelles + faces virtuelles
int nb_som_face () const
renvoie le nombre de sommets par face.
Rque : on a suppose que toutes les faces avait
le meme nombre de sommet ce qui exclue des elements
comme le prisme.
int nb_faces_bord () const
renvoie le nombre de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_bord_tot () const
renvoie le nombre total de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int premiere_face_bord () const
renvoie le numero de la premiere des faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_internes () const
une face est interne ssi elle separe deux elements.
renvoie le nombre de faces internes.
double xv (int, int) const
double xp (int, int) const
double xa (int, int) const
double porosite_face (int) const
double porosite_elem (int) const
double diametre_hydraulique_face (int) const
double section_passage_face (int) const
double coefficient_frottement (int) const
double coefficient_echange_thermique (int) const
int face_numero_bord (int num_face) const
IntTab & face_numero_bord ()
const IntTab & face_numero_bord () const
void remplir_face_numero_bord ()
virtual const IntVect & orientation () const
virtual int orientation (int) const
virtual int orientation_si_definie (int) const
DoubleTab normalized_boundaries_outward_vector (int global_face_number, double scale_factor) const
Compute the normalized boundary outward vector associated to the face global_face_number
and eventually scaled by scale_factor.
DoubleTab & xv ()
const DoubleTab & xv () const
DoubleTab & xp ()
const DoubleTab & xp () const
DoubleTab & xa ()
const DoubleTab & xa () const
DoubleVect & volumes_entrelaces ()
const DoubleVect & volumes_entrelaces () const
double volumes_entrelaces (int num_face) const
const DoubleTab & volumes_entrelaces_dir () const
DoubleTab & volumes_entrelaces_dir ()
DoubleVect & porosite_face ()
const DoubleVect & porosite_face () const
DoubleVect & porosite_elem ()
const DoubleVect & porosite_elem () const
DoubleVect & diametre_hydraulique_face ()
const DoubleVect & diametre_hydraulique_face () const
const DoubleVect section_passage_face () const
DoubleTab & diametre_hydraulique_elem ()
const DoubleTab & diametre_hydraulique_elem () const
DoubleVect & coefficient_frottement ()
const DoubleVect & coefficient_frottement () const
DoubleVect & coefficient_echange_thermique ()
const DoubleVect & coefficient_echange_thermique () const
const Joint & joint (int i) const
renvoie le ieme joint.
Joint & joint (int i)
renvoie le ieme joint.
Frontiere_dis_base & frontiere_dis (int) override
renvoie la ieme frontiere_discrete.
const Frontiere_dis_base & frontiere_dis (int) const override
renvoie la ieme frontiere_discrete.
int nb_frontiere_dis () const
const Front_VF & front_VF (int) const
renvoie la ieme frontiere_discrete.
double volumes (int i) const
renvoie le volume de la maille i.
double inverse_volumes (int i) const
int face_voisins (int num_face, int i) const
renvoie l'element voisin de numface dans la direction i.
i=0 : dans le sens oppose de l'axe orthogonal a la face numface.
i=1 : dans le sens de l'axe orthogonal a la face numface.
exemple :
| 0 | 1 |
numface
renvoie -1 si l'element n'existe pas (au bord).
int elem_faces (int i, int j) const
renvoie le numero de le ieme face de la maille num_elem
la facon dont ces faces sont numerotees est
laisse a la responsabilite des classes derivees
int face_sommets (int i, int j) const
renvoie le numero du ieme sommet de la face num_face.
DoubleVect & volumes ()
renvoie le tableaux des volumes des mailles.
DoubleVect & inverse_volumes ()
Tableau pour optimiser le code.
const DoubleVect & volumes () const
renvoie le tableaux des volumes des mailles.
const DoubleVect & inverse_volumes () const
Tableau pour optimiser le code.
IntTab & face_voisins () override
renvoie le tableaux des volumes des connectivites face elements
cf au dessus.
const IntTab & face_voisins () const override
cf au dessus.
const IntTab & face_voisins_fictifs () const
void face_voisins_reel_fictif (int face, int &el0, int &elf) const
renvoie dans el0 le numero de l'elt a l'interieur
renvoie dans elf le numero de l'elt fictif (-1 si il n'existe pas)
IntTab & elem_faces ()
renvoie le tableau de connectivite element/faces
const IntTab & elem_faces () const
cf au dessus.
ArrOfInt & faces_doubles ()
renvoie 1 pour les faces appartenant a un bord perio ou un item commun, 0 par defaut
const ArrOfInt & faces_doubles () const
cf au dessus
IntTab & face_sommets () override
renvoie le tableau de connectivite faces/sommets.
const IntTab & face_sommets () const override
cf au dessus.
void modifier_pour_Cl (const Conds_lim &) override
int numero_face_local (int face, int elem) const
int numero_sommet_local (int som, int elem) const
const IntTab & get_num_fac_loc () const
int get_num_fac_loc (int, int) const
void construire_num_fac_loc ()
const ArrOfInt & ind_faces_virt_bord () const
int est_une_face_virt_bord (int) const
renvoie 1 si face est une face virtuelle de bord, 0 sinon
int fbord (int f) const
void construire_face_virt_pe_num ()
Remplissage du tableau face_virt_pe_num_ (voir commentaire dans Zone_VF.h)
const IntTab & face_virt_pe_num () const
virtual void creer_tableau_faces (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_aretes (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_faces_bord (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual const MD_Vector & md_vector_faces_bord () const
virtual const MD_Vector & md_vector_faces () const
virtual const MD_Vector & md_vector_aretes () const
virtual const DoubleTab & xv_bord () const
Public Member Functions inherited from Zone_dis_base
Zone_dis_base ()
~Zone_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Associe une Zone a l'objet.
const Zone & zone () const
Renvoie la Zone associee a l'objet.
(version const)
Zone & zone ()
Renvoie la Zone associee a l'objet.
void associer_domaine_dis (const Domaine_dis &)
Associe un Domaine_dis a l'objet.
const Domaine_dis & domaine_dis () const
Domaine_dis & domaine_dis ()
virtual void discretiser ()=0
virtual void creer_elements_fictifs (const Zone_Cl_dis_base &)
virtual Frontiere_dis_base & frontiere_dis (int)=0
virtual const Frontiere_dis_base & frontiere_dis (int) const =0
int rang_frontiere (const Nom &)
int rang_frontiere (const Nom &) const
Renvoie le rang de la frontiere de Nom nom
Renvoie -1 si aucune frontiere ne s'appelle nom.
Frontiere_dis_base & frontiere_dis (const Nom &)
const Frontiere_dis_base & frontiere_dis (const Nom &) const
Renvoie la frontiere de Nom nom.
(On indexe les frontiere avec leur nom)
void ecrire_noms_bords (Sortie &) const
Ecriture des noms des bords sur un flot de sortie.
virtual void modifier_pour_Cl (const Conds_lim &)=0
virtual IntTab & face_sommets ()
virtual const IntTab & face_sommets () const
virtual IntTab & face_voisins ()
virtual const IntTab & face_voisins () const
int nb_elem () const
int nb_elem_tot () const
int nb_som () const
int nb_som_tot () const
int nb_front_Cl () const
virtual void init_dist_paroi_globale (const Conds_lim &conds_lim)
virtual const DoubleTab & y_elem () const
virtual const DoubleTab & y_faces () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_EF & self_cast (Objet_U &)
static const Zone_EF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_VF
static const Type_info * info ()
static Zone_VF & self_cast (Objet_U &)
static const Zone_VF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_dis_base
static const Type_info * info ()
static Zone_dis_base & self_cast (Objet_U &)
static const Zone_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Zone_VF
static const Type_info info_obj
Static Public Attributes inherited from Zone_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Zone_VF
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
virtual void remplir_elem_faces ()=0
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
DoubleTab IPhi_
DoubleTab IPhi_thilde_
Protected Attributes inherited from Zone_VF
DoubleVect volumes_
volumes des elements
DoubleVect inverse_volumes_
inverse du volumes des elements
DoubleVect volumes_entrelaces_
volumes entrelaces pour l'integration des Qdm
DoubleTab volumes_entrelaces_dir_
volumes entrelaces par cote
DoubleVect porosite_elem_
Porosites volumiques pour les volumes de controle de masse.
DoubleVect porosite_face_
Porosites surfaciques en masse et volumiques.
DoubleVect diametre_hydraulique_face_
DoubleTab diametre_hydraulique_elem_
DoubleVect coefficient_echange_thermique_
remplissage des coefficients d'echange_thermique
DoubleVect coefficient_frottement_
remplissage des coefficient de frottement
IntTab face_voisins_
connectivite face/elements
IntTab face_voisins_fictifs_
connectivite face/elements fictifs
DoubleTab xp_
centres de gravite des elements
DoubleTab xv_
centres de gravite des faces
DoubleTab xv_bord_
IntTab elem_faces_
connectivite element/faces
IntTab face_sommets_
sommets des faces
DoubleTab xa_
centres de gravite des aretes
IntTab face_numero_bord_
connectivite face/numero_bord
MD_Vector md_vector_faces_
MD_Vector md_vector_faces_front_
MD_Vector md_vector_aretes_
Vect_Front_VF les_bords_
IntTab num_fac_loc_
ArrOfInt faces_doubles_
faces a double contribution (faces periodiques et items communs)
IntTab face_virt_pe_num_
Protected Attributes inherited from Zone_dis_base
Ref_Zone la_zone
Ref_Domaine_dis le_domaine_dis
DoubleTab y_elem_
DoubleTab y_faces_
int dist_paroi_initialisee_ = 0
Private Member Functions
void remplir_elem_faces () override
Sortie & ecrit (Sortie &os) const
void creer_faces_virtuelles_non_std ()
creation de l'espace distant pour les faces virtuelles;
creation du tableau des faces virtuelles de bord
Private Attributes
DoubleVect porosite_sommets_
DoubleVect volumes_sommets_thilde_
DoubleVect volumes_thilde_
DoubleTab Bij_
DoubleTab Bij_thilde_
stockage des matrice Bije
double h_carre
carre du pas du maillage
DoubleVect h_carre_
carre du pas d'une maille
Elem_EF type_elem_
type de l'element de discretisation
DoubleTab face_normales_
normales aux faces
int nb_faces_std_
nombre de faces standard
int nb_elem_std_
nombre d'elements standard
IntVect rang_elem_non_std_
rang_elem_non_std_= -1 si l'element est standard rang_elem_non_std_= rang de l'element dans les tableaux relatifs aux elements non standards
ArrOfInt ind_faces_virt_non_std_
contient les indices des faces virtuelles non standard
IntVect orientation_
Detailed Description
class Zone_EF
Classe instanciable qui derive de Zone_VF.
Cette classe contient les informations geometriques que demande
la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
La classe porte un certain nombre d'informations concernant les faces
Dans cet ensemble de faces on fait figurer aussi les faces du bord et
des joints. Pour manipuler les faces on distingue 2 categories:
- les faces non standard qui sont sur un joint, un bord ou qui sont
internes tout en appartenant a un element du bord
- les faces standard qui sont les faces internes n'appartenant pas
a un element du bord
Cette distinction correspond au traitement des conditions aux limites:les
faces standard ne "voient pas" les conditions aux limites.
L'ensemble des faces est numerote comme suit:
- les faces qui sont sur une Zone_joint apparaissent en premier
(dans l'ordre du vecteur les_joints)
- les faces qui sont sur une Zone_bord apparaissent ensuite
(dans l'ordre du vecteur les_bords)
- les faces internes non standard apparaissent ensuite
- les faces internes standard en dernier
Finalement on trouve regroupees en premier toutes les faces non standard
qui vont necessiter un traitement particulier
On distingue deux types d'elements
- les elements non standard : ils ont au moins une face de bord
- les elements standard : ils n'ont pas de face de bord
Les elements standard (resp. les elements non standard) ne sont pas ranges
de maniere consecutive dans l'objet Zone. On utilise le tableau
rang_elem_non_std pour acceder de maniere selective a l'un ou
l'autre des types d'elements
Definition at line 60 of file Zone_EF.h.
Constructor & Destructor Documentation
Zone_EF()
Zone_EF::Zone_EF ()
Definition at line 38 of file Zone_EF.cpp.
~Zone_EF()
Zone_EF::~Zone_EF ()
Definition at line 38 of file Zone_EF.cpp.
Member Function Documentation
Bij()
const DoubleTab & Zone_EF::Bij () const inline
Definition at line 115 of file Zone_EF.h.
  {
    return Bij_ ;
  };
References Bij_.
Referenced by Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Diff_EF::ajouter_scalaire_template(), Op_Dift_EF_Q1::ajouter_scalaire_template(), Op_Conv_EF::ajouter_sous_cond_template(), Op_Diff_EF::ajouter_vectoriel_template(), and Op_Dift_EF_Q1::ajouter_vectoriel_template().
Bij_thilde()
const DoubleTab & Zone_EF::Bij_thilde () const inline
Definition at line 119 of file Zone_EF.h.
  {
    return Bij_thilde_ ;
  };
References Bij_thilde_.
Referenced by Op_Div_EF::ajouter(), Op_Grad_EF::ajouter(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Assembleur_P_EF::assembler_mat(), and Champ_Q1_EF::gradient().
calculer_Bij()
void Zone_EF::calculer_Bij (DoubleTab & bij_) virtual
Definition at line 571 of file Zone_EF.cpp.
{
  int nbsom_face=nb_som_face();
  int nbelem=nb_elem_tot();
  int nbsom_elem=zone().nb_som_elem();
  bij.resize(nbelem,nbsom_elem,dimension);
  const IntTab& les_elems=zone().les_elems() ;
  if (nbsom_elem!=8)
    {
      calculer_Bij_gen(bij);
      bij/=nbsom_face;
      Bij_thilde_=bij;
      {
// int nbelem=nb_elem_tot();
// int nbsom_elem=zone().nb_som_elem();
        const IntTab& elems=zone().les_elems() ;
// Cerr<<min(porosite_elem_)<<finl;abort();
        for (int elem=0; elem<nbelem; elem++)
          for (int i=0; i<nbsom_elem; i++)
            {
              int som_glob=elems(elem,i);;
              for (int j=0; j<dimension; j++)
                {
                  Bij_thilde_(elem,i,j)=bij(elem,i,j)*porosite_sommets_(som_glob);
                }
            }
// essai
        if(0)
          {
            EFichier bthilde("Bthilde");
            for (int elem=0; elem<nbelem; elem++)
              for (int i=0; i<nbsom_elem; i++)
                for (int j=0; j<dimension; j++)
                  {
                    int ii,jj,ele;
// Cout<< elem<<" "<<i<<" "<<j<<" "<<Bij_thilde_(elem,i,j)<<" uuu ";
                    int i2=i;
                    if (i2==2) i2=3;
                    if (i2==3) i2=2;
                    if (i2==7) i2=6;
                    if (i2==6) i2=7;
                    Cout<< elem<<" "<<i<<" "<<j<<" "<<Bij_thilde_(elem,i2,j)<<" uuu ";
                    bthilde >> ele>> ii >> jj >> Bij_thilde_(elem,i2,j);
                    Cout<< Bij_thilde_(elem,i2,j)<<finl;
                    assert(ele==elem+1);
                    assert(ii==i+1);
                    assert(jj==j+1);
                  }
          }
      }
    }
  else
    {
      volumes_sommets_thilde_=0;
      Bij_thilde_.resize(nbelem,nbsom_elem,dimension);
      ArrOfInt filter(8) ;
      filter[0] = 0 ;
      filter[1] = 2 ;
      filter[2] = 3 ;
      filter[3] = 1 ;
      filter[4] = 4 ;
      filter[5] = 6 ;
      filter[6] = 7 ;
      filter[7] = 5 ;
      interface_INITGAUSS init_gauss;
      int npgau=27;
// npgau=1;
      int nbnn=nbsom_elem;
      DoubleTab xgau(npgau,3),frgau(npgau,nbnn),dfrgau(npgau,nbnn,(int)3),poigau(npgau);
      DoubleVect volumes_sommets_(volumes_sommets_thilde_);
      int dim=3;
// init_gauss.compute(&dim,&nbnn,&npgau,xgau.addr(),frgau.addr(),dfrgau.addr(),poigau.addr());
      init_gauss.Compute(dim,nbnn,npgau,xgau,frgau,dfrgau,poigau);
      ArrOfInt num(nbnn);
      interface_CALCULBIJ CALCULBIJ;
      DoubleTab xl(dimension,nbnn),bijl(dimension,nbnn),poro;
      DoubleTab detj(npgau),ajm1(npgau*9),aj(npgau*9),df(npgau*nbnn*3),iphi(nbnn);
      int ip=0;
      const DoubleTab& coord=zone().domaine().coord_sommets();
      for (int elem=0; elem<nbelem; elem++)
        {
          for (int i=0; i<nbnn; i++)
            num[i]=les_elems(elem,filter[i]);
          for (int i=0; i<nbnn; i++)
            for (int d=0; d<dimension; d++)
              {
                xl(d,i)=coord(num[i],d);
              }
          num+=1;
          ip=0;
          double vol;
          int nbsom_tot=volumes_sommets_.size_totale();
          CALCULBIJ.Compute(nbnn,nbsom_tot, xl, num, bijl,
                            porosite_sommets_, ip,
                            npgau, xgau, frgau, dfrgau,
                            poigau,detj, ajm1, aj, df,vol,volumes_sommets_,iphi);
          if (!est_egal(volumes_(elem),vol,1e-5))
            {
              Cerr<<"Erreur volume "<<elem<< " vol: "<<volumes_(elem)<<" new "<<vol<<" delta "<<volumes_(elem)-vol;
              exit();
            }
          for (int i=0; i<nbnn; i++)
            {
              for (int d=0; d<dimension; d++)
                {
                  bij(elem,filter[i],d)=bijl(d,(i));
                  IPhi_(elem,filter[i])=iphi(i);
                }
            }
          ip=1;
          CALCULBIJ.Compute(nbnn, nbsom_tot, xl, num, bijl,
                            porosite_sommets_, ip,
                            npgau, xgau, frgau, dfrgau,
                            poigau,detj, ajm1, aj, df,volumes_thilde_(elem),volumes_sommets_thilde_,iphi);
          for (int i=0; i<nbnn; i++)
            {
              for (int d=0; d<dimension; d++)
                {
                  Bij_thilde_(elem,filter[i],d)=bijl(d,(i));
                  IPhi_thilde_(elem,filter[i])=iphi(i);
                }
            }
// exit();
        }
    }
  if (0)
    {
      for (int elem=0; elem<nbelem; elem++)
        {
          for (int i=0; i<nbsom_elem; i++)
            {
              for (int d=0; d<dimension; d++)
                Cerr<<" BIJ "<<elem<<" "<< i<< " "<<d<<" "<<bij(elem,i,d)<<" "<<Bij_thilde_(elem,i,d)<<finl;
              Cerr<< " Iphi " << IPhi_(elem,i)<<" "<<IPhi_thilde_(elem,i)<<finl;
            }
          Cerr<<"vol elem "<<volumes_(elem)<< " "<<volumes_thilde_(elem)<<finl;
        }
      for (int elem=0; elem<volumes_sommets_thilde_.size_array(); elem++)
        Cerr<<elem<<" vol som "<< volumes_sommets_thilde_(elem)<<finl;
    }
// verif
  Cerr<<"max/min/max_abs bij "<<mp_max_vect(bij)<< " "<<mp_min_vect(bij)<<" "<<mp_max_abs_vect(bij)<<finl;
  int err=0;
  for (int elem=0; elem<nbelem; elem++)
    for (int j=0; j<dimension; j++)
      {
        double tot=0;
        for (int i=0; i<nbsom_elem; i++)
          tot+=bij(elem,i,j);
        if (!est_egal(tot,0))
          {
            err++;
            Cerr<<" pb elem "<< elem<<" direction "<<j<<" : "<<tot<<finl;
          }
// Cerr<<"vol elem "<<volumes_(elem)<< " "<<volumes_thilde_(elem)<<finl;
      }
  if (err) exit();
}
References Bij_thilde_, calculer_Bij_gen(), Cerr, interface_INITGAUSS::Compute(), interface_CALCULBIJ::Compute(), Domaine::coord_sommets(), Cout, Objet_U::dimension, Zone::domaine(), est_egal(), Process::exit(), finl, IPhi_, IPhi_thilde_, Zone::les_elems(), mp_max_abs_vect(), mp_max_vect(), mp_min_vect(), Zone_dis_base::nb_elem_tot(), Zone::nb_som_elem(), Zone_VF::nb_som_face(), porosite_sommets_, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), Zone_VF::volumes_, volumes_sommets_thilde_, volumes_thilde_, and Zone_dis_base::zone().
Referenced by modifier_pour_Cl().
calculer_Bij_gen()
void Zone_EF::calculer_Bij_gen (DoubleTab & bij) virtual
Reimplemented in Zone_EF_axi.
Definition at line 543 of file Zone_EF.cpp.
{
  const IntTab& les_elems=zone().les_elems() ;
  int nbsom_face=nb_som_face();
  int nbelem=nb_elem_tot();
  int nbsom_elem=zone().nb_som_elem();
  const IntTab& elemfaces=elem_faces_;
  int nbface_elem=zone().nb_faces_elem();
  for (int elem=0; elem<nbelem; elem++)
    for (int i=0; i<nbsom_elem; i++)
      {
// on cherche les faces contribuantes ,ce n'est pas optimal
        for (int f=0; f<nbface_elem; f++)
          {
            int face=elemfaces(elem,f);
            for (int s=0; s<nbsom_face; s++)
              if (face_sommets_(face,s)==les_elems(elem,i))
// on cherche les faces contribuantes ,ce n'est pas optimal
                for (int j=0; j<dimension; j++)
                  {
                    bij(elem,i,j)+=face_normales(face,j)*oriente_normale(face,elem);
                  }
          }
      }
}
References Objet_U::dimension, Zone_VF::elem_faces_, face_normales(), Zone_VF::face_sommets_, Zone::les_elems(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Zone::nb_som_elem(), Zone_VF::nb_som_face(), oriente_normale(), and Zone_dis_base::zone().
Referenced by calculer_Bij().
calculer_h_carre()
void Zone_EF::calculer_h_carre ()
Definition at line 745 of file Zone_EF.cpp.
{
// Calcul de h_carre
  h_carre = 1.e30;
  h_carre_.resize(nb_faces());
// Calcul des surfaces
  const DoubleVect& surfaces=face_surfaces();
  const int nb_faces_elem=zone().nb_faces_elem();
  const int nbe=nb_elem();
  for (int num_elem=0; num_elem<nbe; num_elem++)
    {
      double surf_max = 0;
      for (int i=0; i<nb_faces_elem; i++)
        {
          double surf = surfaces(elem_faces(num_elem,i));
          surf_max = (surf > surf_max)? surf : surf_max;
        }
      double vol = volumes(num_elem)/surf_max;
      vol *= vol;
      h_carre_(num_elem) = vol;
      h_carre = ( vol < h_carre )? vol : h_carre;
    }
}
References Zone_VF::elem_faces(), Zone_VF::face_surfaces(), h_carre, h_carre_, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), TRUSTVect< _TYPE_ >::resize(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by modifier_pour_Cl().
calculer_IPhi()
void Zone_EF::calculer_IPhi () virtual
Reimplemented in Zone_EF_axi.
Definition at line 101 of file Zone_EF.cpp.
{
  int nbelem=zone().nb_elem();
  int nb_som_elem=zone().nb_som_elem();
  IPhi_.resize(nbelem,nb_som_elem);
  zone().domaine().creer_tableau_elements(IPhi_);
// Scatter::creer_tableau_distribue(zone().domaine(), Joint::ELEMENT, IPhi_);
  IPhi_thilde_=IPhi_;
  double rap=1./zone().nb_som_elem();
// calcul de IPhi_ version valable poour les carres...
  for (int elem=0; elem<nbelem; elem++)
    {
      double vol=volumes(elem)*rap;
      for (int s=0; s<nb_som_elem; s++)
        {
          IPhi_(elem,s)=vol;
          IPhi_thilde_(elem,s)=vol*porosite_elem_(elem);
        }
    }
  IPhi_.echange_espace_virtuel();
  IPhi_thilde_.echange_espace_virtuel();
}
References Domaine::creer_tableau_elements(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), IPhi_, IPhi_thilde_, Zone::nb_elem(), Zone::nb_som_elem(), Zone_VF::porosite_elem_, TRUSTTab< _TYPE_ >::resize(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by calculer_volumes_sommets().
calculer_porosites_sommets()
void Zone_EF::calculer_porosites_sommets ()
Definition at line 738 of file Zone_EF.cpp.
{
  porosite_sommets_.resize(nb_som());
  porosite_sommets_=1;
}
References Zone_dis_base::nb_som(), porosite_sommets_, and TRUSTVect< _TYPE_ >::resize().
calculer_volumes_entrelaces()
void Zone_EF::calculer_volumes_entrelaces ()
Definition at line 769 of file Zone_EF.cpp.
{
// Cerr << "les normales aux faces " << face_normales() << finl;
// On calcule les volumes entrelaces;
// volumes_entrelaces_.resize(nb_faces());
  creer_tableau_faces(volumes_entrelaces_);
  int elem1,elem2;
  int nb_faces_elem=zone().nb_faces_elem();
  int num_face;
  for (num_face=0; num_face<premiere_face_int(); num_face++)
    {
      elem1 = face_voisins_(num_face,0);
      volumes_entrelaces_[num_face] = volumes_[elem1]/nb_faces_elem;
    }
  for (num_face=premiere_face_int(); num_face<nb_faces(); num_face++)
    {
      elem1 = face_voisins_(num_face,0);
      elem2 = face_voisins_(num_face,1);
      volumes_entrelaces_[num_face] = (volumes_[elem1] + volumes_[elem2])
                                      /
                                      nb_faces_elem;
    }
  volumes_entrelaces_.echange_espace_virtuel();
}
References Zone_VF::creer_tableau_faces(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::face_voisins_, Zone_VF::nb_faces(), Zone::nb_faces_elem(), Zone_VF::premiere_face_int(), Zone_VF::volumes_, Zone_VF::volumes_entrelaces_, and Zone_dis_base::zone().
calculer_volumes_sommets()
void Zone_EF::calculer_volumes_sommets ()
Definition at line 125 of file Zone_EF.cpp.
{
// volumes_sommets_thilde_.resize(nb_som());
// Scatter::creer_tableau_distribue(zone().domaine(), Joint::SOMMET, volumes_sommets_thilde_);
// zone().domaine().creer_tableau_sommets(volumes_sommets_thilde_);
  calculer_IPhi();
// calcul de volumes_sommets_thilde
  const IntTab& les_elems=zone().les_elems() ;
  DoubleVect volumes_som_prov(volumes_sommets_thilde_);
  for (int elem=0; elem<zone().nb_elem_tot(); elem++)
    {
      for (int s=0; s<zone().nb_som_elem(); s++)
        {
          double vol=IPhi_thilde_(elem,s);
          int s_glob=les_elems(elem,s);
          volumes_sommets_thilde_(s_glob)+=vol;
          volumes_som_prov(s_glob)+=IPhi_(elem,s);
        }
    }
// volumes_sommets_thilde_.resize(nb_som());
  volumes_sommets_thilde_.echange_espace_virtuel();
  if (porosite_sommets_.size_array()==0)
    {
// abort();
      porosite_sommets_=volumes_sommets_thilde_;
      for (int som=0; som<nb_som(); som++)
        {
          porosite_sommets_(som)=volumes_sommets_thilde_(som)/volumes_som_prov(som);
        }
      porosite_sommets_.echange_espace_virtuel();
    }
#if 0
  if (0)
    {
      porosite_sommets_.resize(0);
      DoubleVect volumes_som_prov(volumes_sommets_thilde_);
      DoubleVect volumes_som_prov_b(volumes_sommets_thilde_);
      volumes_som_prov=0;
      volumes_som_prov_b=0;
      for (int elem=0; elem<zone().nb_elem_tot(); elem++)
        {
          for (int s=0; s<zone().nb_som_elem(); s++)
            {
              double vol=IPhi_thilde_(elem,s);
              double v2=IPhi_(elem,s);
              int s_glob=les_elems(elem,s);
              volumes_som_prov(s_glob)+=v2/vol;
              volumes_som_prov_b(s_glob)+=1;
            }
        }
      Cerr<<mp_max_vect(porosite_elem_)<<" "<<mp_min_vect( porosite_elem_)<<finl;
      Cerr<<mp_max_vect(volumes_som_prov)<<" "<<mp_min_vect( volumes_som_prov)<<finl;
      Cerr<<mp_max_vect(volumes_som_prov_b)<<" "<<mp_min_vect( volumes_som_prov_b)<<finl;
      if (porosite_sommets_.size_array()==0)
        {
// abort();
          porosite_sommets_=volumes_sommets_thilde_;
          for (int som=0; som<nb_som(); som++)
            {
              porosite_sommets_(som)=1./volumes_som_prov(som)*volumes_som_prov_b(som);
            }
          porosite_sommets_.echange_espace_virtuel();
        }
      Cerr<<mp_max_vect( porosite_sommets_)<<" "<<mp_min_vect( porosite_sommets_)<<finl;
      for (int elem=0; elem<zone().nb_elem_tot(); elem++)
        for (int s=0; s<zone().nb_som_elem(); s++)
          IPhi_thilde_(elem,s)= IPhi_thilde_(elem,s)*porosite_sommets_(les_elems(elem,s));
    }
#endif
  volumes_thilde_=volumes_;
  for (int elem=0; elem<zone().nb_elem_tot(); elem++)
    {
      volumes_thilde_(elem)=volumes_(elem)*porosite_elem_(elem);
    }
}
References calculer_IPhi(), Cerr, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), finl, IPhi_, IPhi_thilde_, Zone::les_elems(), mp_max_vect(), mp_min_vect(), Zone::nb_elem_tot(), Zone_dis_base::nb_som(), Zone::nb_som_elem(), Zone_VF::porosite_elem_, porosite_sommets_, TRUSTVect< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::size_array(), Zone_VF::volumes_, volumes_sommets_thilde_, volumes_thilde_, and Zone_dis_base::zone().
Referenced by modifier_pour_Cl().
carre_pas_du_maillage()
double Zone_EF::carre_pas_du_maillage () const inline
Definition at line 229 of file Zone_EF.h.
{
  return h_carre;
}
References h_carre.
Referenced by Op_Diff_EF_base::calculer_dt_stab().
carre_pas_maille()
double Zone_EF::carre_pas_maille (int i) const inline
Definition at line 78 of file Zone_EF.h.
  {
    return h_carre_(i);
  };
References h_carre_.
Referenced by Op_Dift_EF_base::calculer_borne_locale(), Op_Diff_EF_base::calculer_dt_stab(), and Op_Dift_EF_Q1::calculer_dt_stab().
cree_instance()
Objet_U * Zone_EF::cree_instance () static
Definition at line 38 of file Zone_EF.cpp.
creer_faces_virtuelles_non_std()
void Zone_EF::creer_faces_virtuelles_non_std () private
creation de l'espace distant pour les faces virtuelles;
creation du tableau des faces virtuelles de bord
Definition at line 901 of file Zone_EF.cpp.
{
  ind_faces_virt_non_std_.resize_array(314);
  ind_faces_virt_non_std_ = -999;
#if 0
  int i,j,id_joint;
  int nb_faces_front=premiere_face_int();
  int nb_faces_virt=zone().ind_faces_virt_bord().size_array();
// Constitution du tableau des indices de faces
// virtuelles non standards.
  int prem_face_std=premiere_face_std();
  IntVect ind_faces_nstd(nb_faces_non_std());
  IntVect ind_faces(nb_faces_);
  const VectEsp_Virt& vev_id_f = ind_faces.renvoi_espaces_virtuels();
  for(j=0; j<nb_faces_; j++)
    ind_faces[j]=j;
  for(j=premiere_face_int(); j<prem_face_std; j++)
    ind_faces_nstd[j]=j;
  for(id_joint=0; id_joint<nb_joints(); id_joint++)
    {
      Joint& le_joint = joint(id_joint);
      int PEvoisin=le_joint.PEvoisin();
      const ArrOfInt& edf=le_joint.esp_dist_faces();
      int nbfd = edf.size_array();
      ind_faces.ajoute_espace_distant(PEvoisin,edf);
      ArrOfInt tempo(nbfd);
      int cpt=0;
      for(i=0; i<nbfd; i++)
        if((edf[i]<prem_face_std)&&(edf[i]>=nb_faces_front))
          tempo[cpt++]=edf[i];
      tempo.resize_array(cpt);
      ind_faces_nstd.ajoute_espace_distant(PEvoisin,tempo);
    }
  ind_faces.echange_espace_virtuel();
  ind_faces_nstd.echange_espace_virtuel();
  const VectEsp_Virt& vev_id_fnstd =
    ind_faces_nstd.renvoi_espaces_virtuels();
  ind_faces_virt_non_std_.resize_array(nb_faces_virt);
  for(id_joint=0; id_joint<nb_joints(); id_joint++)
    {
      int deb=vev_id_f[id_joint].deb();
      int fin=deb+vev_id_f[id_joint].nb();
      int deb_b=vev_id_fnstd[id_joint].deb();
      int fin_b=deb_b+vev_id_fnstd[id_joint].nb();
      for(i=deb_b; i<fin_b; i++)
        {
          for(j=deb; j<fin; j++)
            if(ind_faces[j]==ind_faces_nstd[i])
              break;
          assert(j<fin);
          ind_faces_virt_non_std_[j-nb_faces_]=i;
        }
    }
#endif
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Joint::esp_dist_faces(), Zone::ind_faces_virt_bord(), ind_faces_virt_non_std_, Zone_VF::joint(), Zone_VF::nb_joints(), Joint::PEvoisin(), Zone_VF::premiere_face_int(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::size_array(), and Zone_dis_base::zone().
Referenced by remplir_elem_faces().
discretiser()
void Zone_EF::discretiser () override virtual
Implements Zone_dis_base.
Reimplemented in Zone_EF_axi.
Definition at line 423 of file Zone_EF.cpp.
{
  verifie_compatibilite_domaine();
  Zone& zone_geom=zone();
  typer_elem(zone_geom);
  Elem_geom_base& elem_geom = zone_geom.type_elem().valeur();
  Zone_VF::discretiser();
// Correction du tableau facevoisins:
// A l'issue de Zone_VF::discretiser(), les elements voisins 0 et 1 d'une
// face sont les memes sur tous les processeurs qui possedent la face.
// Si la face est virtuelle et qu'un des deux elements voisins n'est
// pas connu (il n'est pas dans l'epaisseur du joint), l'element voisin
// vaut -1. Cela peut etre un voisin 0 ou un voisin 1.
// On corrige les faces virtuelles pour que, si un element voisin n'est
// pas connu, alors il est voisin1. Le voisin0 est donc toujours valide.
  {
    IntTab& face_vois = face_voisins();
    const int debut = nb_faces();
    const int fin   = nb_faces_tot();
    for (int i = debut; i < fin; i++)
      {
        if (face_voisins(i, 0) == -1)
          {
            face_vois(i, 0) = face_vois(i, 1);
            face_vois(i, 1) = -1;
          }
      }
  }
// Verification de la coherence entre l'element geometrique et
// l'elemnt de discretisation
  if (sub_type(Segment_EF,type_elem_.valeur()))
    {
      if (!sub_type(Segment,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " << elem_geom.que_suis_je() << " est incorrect" << finl;
          exit();
        }
    }
  else if (sub_type(Tri_EF,type_elem_.valeur()))
    {
      if (!sub_type(Triangle,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " <<
               elem_geom.que_suis_je() << " est incorrect" << finl;
          Cerr << " Seul le type Triangle est compatible avec la discretisation EF en dimension 2" << finl;
          Cerr << " Il faut trianguler le domaine lorsqu'on utilise le mailleur interne" ;
          Cerr << " en utilisant l'instruction: Trianguler nom_dom" << finl;
          exit();
        }
    }
  else if (sub_type(Tetra_EF,type_elem_.valeur()))
    {
      if (!sub_type(Tetraedre,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " <<
               elem_geom.que_suis_je() << " est incorrect" << finl;
          Cerr << " Seul le type Tetraedre est compatible avec la discretisation EF en dimension 3" << finl;
          Cerr << " Il faut tetraedriser le domaine lorsqu'on utilise le mailleur interne";
          Cerr << " en utilisant l'instruction: Tetraedriser nom_dom" << finl;
          exit();
        }
    }
  else if (sub_type(Quadri_EF,type_elem_.valeur()))
    {
      if (!sub_type(Quadrangle_VEF,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " << elem_geom.que_suis_je() << " est incorrect" << finl;
          exit();
        }
    }
  else if (sub_type(Hexa_EF,type_elem_.valeur()))
    {
      if (!sub_type(Hexaedre_VEF,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " << elem_geom.que_suis_je() << " est incorrect" << finl;
          exit();
        }
    }
  int num_face;
// On remplit le tableau face_normales_;
// Attention : le tableau face_voisins n'est pas exactement un
// tableau distribue. Une face n'a pas ses deux voisins dans le
// meme ordre sur tous les processeurs qui possedent la face.
// Donc la normale a la face peut changer de direction d'un
// processeur a l'autre, y compris pour les faces de joint.
  {
    const int n = nb_faces();
    face_normales_.resize(n, dimension);
// const Domaine & dom = zone().domaine();
// Scatter::creer_tableau_distribue(dom, Joint::FACE, face_normales_);
    creer_tableau_faces(face_normales_);
    const IntTab& face_som = face_sommets();
    const IntTab& face_vois = face_voisins();
    const IntTab& elem_face = elem_faces();
    const int n_tot = nb_faces_tot();
    for (num_face = 0; num_face < n_tot; num_face++)
      {
        type_elem_.normale(num_face,
                           face_normales_,
                           face_som, face_vois, elem_face, zone_geom);
      }
  }
  Zone_VF::calculer_porosites();
// calculer_volumes_entrelaces();
  zone().domaine().creer_tableau_sommets(volumes_sommets_thilde_);
}
References Zone_VF::calculer_porosites(), Cerr, Zone_VF::creer_tableau_faces(), Domaine::creer_tableau_sommets(), Objet_U::dimension, Zone_VF::discretiser(), Zone::domaine(), Zone_VF::elem_faces(), Process::exit(), face_normales_, Zone_VF::face_sommets(), face_vois(), Zone_VF::face_voisins(), finl, Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Elem_EF::normale(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_ >::resize(), sub_type, Zone::type_elem(), type_elem_, typer_elem(), Deriv_Elem_EF_base::valeur(), Deriv_Elem_geom_base::valeur(), verifie_compatibilite_domaine(), volumes_sommets_thilde_, and Zone_dis_base::zone().
Referenced by Zone_EF_axi::discretiser().
duplique()
int Zone_EF::duplique () const override virtual
Implements Objet_U.
Reimplemented in Zone_EF_axi.
Definition at line 38 of file Zone_EF.cpp.
ecrit()
Sortie & Zone_EF::ecrit (Sortie & os) const private
Definition at line 44 of file Zone_EF.cpp.
{
  Zone_VF::printOn(os);
  os << "____ h_carre "<<finl;
  os << h_carre << finl;
  os << "____ type_elem_ "<<finl;
  os << type_elem_ << finl;
  os << "____ nb_elem_std_ "<<finl;
  os << nb_elem_std_ << finl;
  os << "____ volumes_entrelaces_ "<<finl;
  volumes_entrelaces_.ecrit(os);
  os << "____ face_normales_ "<<finl;
  face_normales_.ecrit(os);
  os << "____ nb_faces_std_ "<<finl;
  os << nb_faces_std_ << finl;
  os << "____ rang_elem_non_std_ "<<finl;
  rang_elem_non_std_.ecrit(os);
  return os;
}
References TRUSTVect< _TYPE_ >::ecrit(), TRUSTTab< _TYPE_ >::ecrit(), face_normales_, finl, h_carre, nb_elem_std_, nb_faces_std_, Zone_VF::printOn(), rang_elem_non_std_, type_elem_, and Zone_VF::volumes_entrelaces_.
face_normales() [1/3]
DoubleTab & Zone_EF::face_normales () inline
Definition at line 176 of file Zone_EF.h.
{
  return face_normales_;
}
References face_normales_.
Referenced by calculer_Bij_gen(), and Zone_EF_axi::calculer_Bij_gen().
face_normales() [2/3]
const DoubleTab & Zone_EF::face_normales () const inline
Definition at line 183 of file Zone_EF.h.
{
  return face_normales_;
}
References face_normales_.
face_normales() [3/3]
double Zone_EF::face_normales (int face, int comp) const inline override virtual
Implements Zone_VF.
Definition at line 169 of file Zone_EF.h.
{
  return face_normales_(face,comp);
}
References face_normales_.
Referenced by Op_Div_EF::ajouter(), Op_Grad_EF::ajouter(), ajouter_bord(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), distance_2D(), distance_3D(), distance_face(), Op_Grad_EF::impr(), Assembleur_P_EF::modifier_secmem(), norm_2D_vit1_k(), norm_2D_vit2_k(), norm_3D_vit1(), norm_3D_vit2(), norm_vit_lp(), and Zone_Cl_EF::remplir_type_elem_Cl().
get_info()
const Type_info * Zone_EF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Zone_EF_axi.
Definition at line 38 of file Zone_EF.cpp.
ind_faces_virt_non_std()
const ArrOfInt & Zone_EF::ind_faces_virt_non_std () const inline
Definition at line 252 of file Zone_EF.h.
{
  return ind_faces_virt_non_std_;
}
References ind_faces_virt_non_std_.
info()
const Type_info * Zone_EF::info () static
Definition at line 38 of file Zone_EF.cpp.
IPhi()
const DoubleTab & Zone_EF::IPhi () const inline
Definition at line 123 of file Zone_EF.h.
  {
    return IPhi_ ;
  };
References IPhi_.
Referenced by Source_Scalaire_EF::ajouter().
IPhi_thilde()
const DoubleTab & Zone_EF::IPhi_thilde () const inline
Definition at line 127 of file Zone_EF.h.
  {
    return IPhi_thilde_ ;
  };
References IPhi_thilde_.
Referenced by Source_Qdm_EF::ajouter(), Op_Conv_EF::ajouter_contribution_sous_cond(), and Op_Conv_EF::ajouter_sous_cond_template().
modifier_pour_Cl()
void Zone_EF::modifier_pour_Cl (const Conds_lim & conds_lim) override virtual
Implements Zone_dis_base.
Definition at line 798 of file Zone_EF.cpp.
{
// if (volumes_sommets_thilde_.size()!=nb_som())
  if (Bij_.nb_dim()==1)
    {
      calculer_volumes_sommets();
      Cerr << "La Zone_EF a ete remplie avec succes" << finl;
      calculer_h_carre();
// Calcul des porosites
// les porosites sommets ne servent pas
// calculer_porosites_sommets();
      calculer_Bij(Bij_);
    }
  Journal() << "Zone_EF::Modifier_pour_Cl" << finl;
  int nb_cond_lim=conds_lim.size();
  int num_cond_lim=0;
  for (; num_cond_lim<nb_cond_lim; num_cond_lim++)
    {
// for cl
      const Cond_lim_base& cl = conds_lim[num_cond_lim].valeur();
      if (sub_type(Periodique, cl))
        {
// if Perio
          const Periodique& la_cl_period = ref_cast(Periodique,cl);
          int nb_faces_elem = zone().nb_faces_elem();
          const Front_VF& la_front_dis = ref_cast(Front_VF,cl.frontiere_dis());
          int ndeb = 0;
          int nfin = la_front_dis.nb_faces_tot();
#ifndef NDEBUG
          int num_premiere_face = la_front_dis.num_premiere_face();
          int num_derniere_face = num_premiere_face+nfin;
#endif
          int nbr_faces_bord = la_front_dis.nb_faces();
          assert((nb_faces()==0)||(ndeb<nb_faces()));
          assert(nfin>=ndeb);
          int elem1,elem2,k;
          int face;
// Modification des tableaux face_voisins_ , face_normales_ , volumes_entrelaces_
// On change l'orientation de certaines normales
// de sorte que les normales aux faces de periodicite soient orientees
// de face_voisins(la_face_en_question,0) vers face_voisins(la_face_en_question,1)
// comme le sont les faces internes d'ailleurs
          DoubleVect C1C2(dimension);
          double vol,psc=0;
          for (int ind_face=ndeb; ind_face<nfin; ind_face++)
            {
// for ind_face
              face = la_front_dis.num_face(ind_face);
              if  ( (face_voisins_(face,0) == -1) || (face_voisins_(face,1) == -1) )
                {
                  int faassociee = la_front_dis.num_face(la_cl_period.face_associee(ind_face));
                  if (ind_face<nbr_faces_bord)
                    {
                      assert(faassociee>=num_premiere_face);
                      assert(faassociee<num_derniere_face);
                    }
                  elem1 = face_voisins_(face,0);
                  elem2 = face_voisins_(faassociee,0);
                  vol = (volumes_[elem1] + volumes_[elem2])/nb_faces_elem;
                  volumes_entrelaces_[face] = vol;
                  volumes_entrelaces_[faassociee] = vol;
                  face_voisins_(face,1) = elem2;
                  face_voisins_(faassociee,0) = elem1;
                  face_voisins_(faassociee,1) = elem2;
                  psc = 0;
                  for (k=0; k<dimension; k++)
                    {
                      C1C2[k] = xv_(face,k) - xp_(face_voisins_(face,0),k);
                      psc += face_normales_(face,k)*C1C2[k];
                    }
                  if (psc < 0)
                    for (k=0; k<dimension; k++)
                      face_normales_(face,k) *= -1;
                  for (k=0; k<dimension; k++)
                    face_normales_(faassociee,k) = face_normales_(face,k);
                }
            }
        }
    }
// PQ : 10/10/05 : les faces periodiques etant a double contribution
// l'appel a marquer_faces_double_contrib s'effectue dans cette methode
// afin de pouvoir beneficier de conds_lim.
  Zone_VF::marquer_faces_double_contrib(conds_lim);
}
References Bij_, calculer_Bij(), calculer_h_carre(), calculer_volumes_sommets(), Cerr, Objet_U::dimension, Periodique::face_associee(), face_normales_, Zone_VF::face_voisins_, finl, Cond_lim_base::frontiere_dis(), Process::Journal(), Zone_VF::marquer_faces_double_contrib(), TRUSTTab< _TYPE_ >::nb_dim(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Front_VF::num_premiere_face(), ref_cast, vect_impl::size(), sub_type, Zone_VF::volumes_, Zone_VF::volumes_entrelaces_, Zone_VF::xp_, Zone_VF::xv_, and Zone_dis_base::zone().
nb_elem_Cl()
int Zone_EF::nb_elem_Cl () const inline
Definition at line 222 of file Zone_EF.h.
{
  return nb_elem() - nb_elem_std_;
}
References Zone_dis_base::nb_elem(), and nb_elem_std_.
nb_elem_std()
int Zone_EF::nb_elem_std () const inline
Definition at line 216 of file Zone_EF.h.
{
  return nb_elem_std_;
}
References nb_elem_std_.
nb_faces_joint()
int Zone_EF::nb_faces_joint () const inline
Definition at line 203 of file Zone_EF.h.
{
  return 0;
// return nb_faces_joint_;    A FAIRE
}
nb_faces_std()
int Zone_EF::nb_faces_std () const inline
Definition at line 210 of file Zone_EF.h.
{
  return nb_faces_std_;
}
References nb_faces_std_.
oriente_normale()
int Zone_EF::oriente_normale (int face_opp, int elem2) const inline
Definition at line 235 of file Zone_EF.h.
{
  if(face_voisins(face_opp,0)==elem2)
    return 1;
  else return -1;
}
References Zone_VF::face_voisins().
Referenced by calculer_Bij_gen(), and Zone_EF_axi::calculer_Bij_gen().
porosite_sommet()
const DoubleVect & Zone_EF::porosite_sommet () const inline
Definition at line 104 of file Zone_EF.h.
  {
    return porosite_sommets_;
  }
References porosite_sommets_.
Referenced by Op_Div_EF::ajouter(), and ajouter_bord().
printOn()
Sortie & Zone_EF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Zone_EF_axi.
Definition at line 67 of file Zone_EF.cpp.
{
  Zone_VF::printOn(os);
  os << h_carre << finl;
  os << type_elem_ << finl;
  os << nb_elem_std_ << finl;
  os << volumes_entrelaces_ << finl;
  os << face_normales_ << finl;
  os << xp_ << finl;
  os << xv_ << finl;
  os << nb_faces_std_ << finl;
  os << rang_elem_non_std_ << finl;
  return os;
}
References face_normales_, finl, h_carre, nb_elem_std_, nb_faces_std_, Zone_VF::printOn(), rang_elem_non_std_, type_elem_, Zone_VF::volumes_entrelaces_, Zone_VF::xp_, and Zone_VF::xv_.
Referenced by Zone_EF_axi::printOn().
rang_elem_non_std() [1/2]
IntVect & Zone_EF::rang_elem_non_std () inline
Definition at line 190 of file Zone_EF.h.
{
  return rang_elem_non_std_;
}
References rang_elem_non_std_.
rang_elem_non_std() [2/2]
const IntVect & Zone_EF::rang_elem_non_std () const inline
Definition at line 196 of file Zone_EF.h.
{
  return rang_elem_non_std_;
}
References rang_elem_non_std_.
readOn()
Entree & Zone_EF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Zone_EF_axi.
Definition at line 86 of file Zone_EF.cpp.
{
  Zone_VF::readOn(is);
  is >> h_carre;
  is >> type_elem_;
  is >> nb_elem_std_ ;
  is >> volumes_entrelaces_ ;
  is >> face_normales_ ;
  is >> xp_;
  is >> xv_;
  is >> nb_faces_std_ ;
  is >> rang_elem_non_std_ ;
  return is;
}
References face_normales_, h_carre, nb_elem_std_, nb_faces_std_, rang_elem_non_std_, Zone_VF::readOn(), type_elem_, Zone_VF::volumes_entrelaces_, Zone_VF::xp_, and Zone_VF::xv_.
Referenced by Zone_EF_axi::readOn().
remplir_elem_faces()
void Zone_EF::remplir_elem_faces () override private virtual
Implements Zone_VF.
Definition at line 793 of file Zone_EF.cpp.
{
  creer_faces_virtuelles_non_std();
}
References creer_faces_virtuelles_non_std().
reordonner()
void Zone_EF::reordonner (Faces & les_faces) override virtual
Methode appelee par Zone_VF::discretiser apres la creation
des faces reelles.
On reordonne les faces de sorte a placer les faces "non standard"
au debut de la liste des faces. Les faces non standard sont celles
dont les volumes de controles sont modifies par les conditions aux
limites.
< renum_items_communs rempli ?
< ancien indice local
Reimplemented from Zone_VF.
Definition at line 224 of file Zone_EF.cpp.
{
  if (Process::je_suis_maitre())
    Cerr << "Zone_EF::reordonner les_faces " << finl;
// Construction de rang_elem_non_std_ :
// C'est un vecteur indexe par les elements du domaine.
// size() = nb_elem()
// size_tot() = nb_elem_tot()
// Valeurs dans le tableau :
// rang_elem_non_std_[i] = -1 si l'element i est standard,
// sinon
// rang_elem_non_std_[i] = j, ou j est l'indice de l'element dans
// les tableaux indexes par les elements non standards (par exemple
// le tableau Zone_Cl_EF::type_elem_Cl_).
// Un element est non standard s'il est voisin d'une face frontiere.
  {
    const Domaine& dom = zone().domaine();
    const int nb_elements = nb_elem();
    const int nb_faces_front = zone().nb_faces_frontiere();
    dom.creer_tableau_elements(rang_elem_non_std_);
// rang_elem_non_std_.resize(nb_elements);
// Scatter::creer_tableau_distribue(dom, Joint::ELEMENT, rang_elem_non_std_);
    rang_elem_non_std_ = -1;
    int nb_elems_non_std = 0;
// D'abord on marque les elements non standards avec rang_elem_non_std_[i] = 0
    for (int i_face = 0; i_face < nb_faces_front; i_face++)
      {
        const int elem = les_faces.voisin(i_face, 0);
        if (rang_elem_non_std_[elem] < 0)
          {
            rang_elem_non_std_[elem] = 0;
            nb_elems_non_std++;
          }
      }
    nb_elem_std_ = nb_elements - nb_elems_non_std;
    rang_elem_non_std_.echange_espace_virtuel();
    int count = 0;
    const int size_tot = rang_elem_non_std_.size_totale();
// On remplace le marqueur "0" par l'indice j.
    for (int elem = 0; elem < size_tot; elem++)
      {
        if (rang_elem_non_std_[elem] == 0)
          {
            rang_elem_non_std_[elem] = count;
            count++;
          }
      }
  }
// Construction du tableau de renumerotation des faces. Ce tableau,
// une fois trie dans l'ordre croissant donne l'ordre des faces dans
// la zone_VF. La cle de tri est construite de sorte a pouvoir retrouver
// l'indice de la face a partir de la cle par la formule :
// indice_face = cle % nb_faces
  const int nbfaces = les_faces.nb_faces();
  ArrOfInt sort_key(nbfaces);
  {
    nb_faces_std_ =0;
    const int nb_faces_front = zone().nb_faces_frontiere();
// Attention : face_voisins_ n'est pas encore initialise, il
// faut passer par les_faces.voisins() :
    const IntTab& facevoisins = les_faces.voisins();
// On place en premier les faces de bord:
    int i_face;
    for (i_face = 0; i_face < nbfaces; i_face++)
      {
        int key = -1;
        if (i_face < nb_faces_front)
          {
// Si la face est au bord, elle doit etre placee au debut
// (en fait elle ne doit pas etre renumerotee)
            key = i_face;
          }
        else
          {
            const int elem0 = facevoisins(i_face, 0);
            const int elem1 = facevoisins(i_face, 1);
// Ces faces ont toujours deux voisins.
            assert(elem0 >= 0 && elem1 >= 0);
            if (rang_elem_non_std_[elem0] >= 0 || rang_elem_non_std_[elem1] >= 0)
              {
// Si la face est voisine d'un element non standard, elle
// doit etre classee juste apres les faces de bord:
                key = i_face;
              }
            else
              {
// Face standard : a la fin du tableau
                key = i_face + nbfaces;
                nb_faces_std_++;
              }
          }
        sort_key[i_face] = key;
      }
    sort_key.ordonne_array();
// On transforme a nouveau la cle en numero de face:
    for (i_face = 0; i_face < nbfaces; i_face++)
      {
        const int key = sort_key[i_face] % nbfaces;
        sort_key[i_face] = key;
      }
  }
// On reordonne les faces:
  {
    IntTab& faces_sommets = les_faces.les_sommets();
    IntTab old_tab(faces_sommets);
    const int nb_som_faces = faces_sommets.dimension(1);
    for (int i = 0; i < nbfaces; i++)
      {
        const int old_i = sort_key[i];
        for (int j = 0; j < nb_som_faces; j++)
          faces_sommets(i, j) = old_tab(old_i, j);
      }
  }
  {
    IntTab& faces_voisins = les_faces.voisins();
    IntTab old_tab(faces_voisins);
    for (int i = 0; i < nbfaces; i++)
      {
        const int old_i = sort_key[i];
        faces_voisins(i, 0) = old_tab(old_i, 0);
        faces_voisins(i, 1) = old_tab(old_i, 1);
      }
  }
// Calcul de la table inversee: reverse_index[ancien_numero] = nouveau numero
  ArrOfInt reverse_index(nbfaces);
  {
    for (int i = 0; i < nbfaces; i++)
      {
        const int j = sort_key[i];
        reverse_index[j] = i;
      }
  }
// Renumerotation de elem_faces:
  {
// Nombre d'indices de faces dans le tableau
    const int nb_items = elem_faces_.size();
    ArrOfInt& array = elem_faces_;
    for (int i = 0; i < nb_items; i++)
      {
        const int old = array[i];
        array[i] = reverse_index[old];
      }
  }
// Mise a jour des indices des faces de joint:
  {
    Joints&      joints    = zone().faces_joint();
    const int nbjoints = joints.size();
    for (int i_joint = 0; i_joint < nbjoints; i_joint++)
      {
        Joint&     un_joint         = joints[i_joint];
        ArrOfInt& indices_faces = un_joint.set_joint_item(Joint::FACE).set_items_communs();
        const int nbfaces2    = indices_faces.size_array();
        assert(nbfaces2 == un_joint.nb_faces()); //!< renum_items_communs rempli ?
        for (int i = 0; i < nbfaces2; i++)
          {
            const int old = indices_faces[i]; //!< ancien indice local
            indices_faces[i] = reverse_index[old];
          }
// Les faces de joint ne sont plus consecutives dans le
// tableau: num_premiere_face n'a plus ne sens
        un_joint.fixer_num_premiere_face(-1);
      }
  }
}
References Cerr, Domaine::creer_tableau_elements(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces_, Joint::FACE, Zone::faces_joint(), finl, Frontiere::fixer_num_premiere_face(), Process::je_suis_maitre(), Faces::les_sommets(), Zone_dis_base::nb_elem(), nb_elem_std_, Faces::nb_faces(), Frontiere::nb_faces(), Zone::nb_faces_frontiere(), nb_faces_std_, TRUSTArray< _TYPE_ >::ordonne_array(), rang_elem_non_std_, Joint_Items::set_items_communs(), Joint::set_joint_item(), TRUSTVect< _TYPE_ >::size(), liste::size(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), Faces::voisin(), Faces::voisins(), and Zone_dis_base::zone().
self_cast() [1/2]
const Zone_EF & Zone_EF::self_cast (const Objet_U & r) static
Definition at line 38 of file Zone_EF.cpp.
self_cast() [2/2]
Zone_EF & Zone_EF::self_cast (Objet_U & r) static
Definition at line 38 of file Zone_EF.cpp.
set_porosite_sommet()
DoubleVect & Zone_EF::set_porosite_sommet () inline
Definition at line 108 of file Zone_EF.h.
  {
    return porosite_sommets_;
  }
References porosite_sommets_.
swap()
void Zone_EF::swap (int fac1, int fac2, int nb_som_faces)
Definition at line 212 of file Zone_EF.cpp.
{
}
taille_memoire()
unsigned Zone_EF::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Zone_EF_axi.
Definition at line 38 of file Zone_EF.cpp.
type_elem()
const Elem_EF & Zone_EF::type_elem () const inline
Definition at line 162 of file Zone_EF.h.
{
  return type_elem_;
}
References type_elem_.
Referenced by EF_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ_fonc_don(), and EF_discretisation::vorticite().
typer_elem()
void Zone_EF::typer_elem (Zone & zone_geom) override virtual
Reimplemented from Zone_VF.
Definition at line 394 of file Zone_EF.cpp.
{
  const Elem_geom_base& type_elem_geom = zone_geom.type_elem().valeur();
  if (sub_type(Rectangle,type_elem_geom))
    {
      zone_geom.typer("Quadrangle");
    }
  else if (sub_type(Hexaedre,type_elem_geom))
    zone_geom.typer("Hexaedre_VEF");
  const Elem_geom_base& elem_geom = zone_geom.type_elem().valeur();
  type_elem_.typer(elem_geom.que_suis_je());
}
References Objet_U::que_suis_je(), sub_type, Zone::type_elem(), type_elem_, Zone::typer(), Elem_EF::typer(), and Deriv_Elem_geom_base::valeur().
Referenced by discretiser(), and Zone_EF_axi::discretiser().
verifie_compatibilite_domaine()
void Zone_EF::verifie_compatibilite_domaine () virtual
Reimplemented in Zone_EF_axi.
Definition at line 409 of file Zone_EF.cpp.
{
  if (zone().domaine().Axi1d())
    {
      Cerr << "*****************************************************************************" << finl;
      Cerr << " Error in " << que_suis_je() << " : the type of domain " << zone().domaine().que_suis_je();
      Cerr << " is not compatible" << finl;
      Cerr << " with the discretisation EF. " << finl;
      Cerr << " Please use the discretization EF_axi or define a domain of type Domaine." << finl;
      Cerr << "*****************************************************************************" << finl;
      Process::exit();
    }
}
References Cerr, Zone::domaine(), Process::exit(), finl, Objet_U::que_suis_je(), and Zone_dis_base::zone().
Referenced by discretiser().
volumes_sommets_thilde()
const DoubleVect & Zone_EF::volumes_sommets_thilde () const inline
Definition at line 100 of file Zone_EF.h.
  {
    return volumes_sommets_thilde_;
  }
References volumes_sommets_thilde_.
Referenced by Solveur_Masse_EF::appliquer_impl(), and Assembleur_P_EF::assembler().
volumes_thilde()
const DoubleVect & Zone_EF::volumes_thilde () const inline
Definition at line 96 of file Zone_EF.h.
  {
    return volumes_thilde_;
  }
References volumes_thilde_.
Referenced by Source_PDF_EF::ajouter_(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_scalaire_template(), Op_Dift_EF_Q1::ajouter_scalaire_template(), Op_Conv_EF::ajouter_sous_cond_template(), Op_Diff_EF::ajouter_vectoriel_template(), Op_Dift_EF_Q1::ajouter_vectoriel_template(), Source_PDF_EF::contribuer_a_avec(), and Champ_Q1_EF::gradient().
Member Data Documentation
Bij_
DoubleTab Zone_EF::Bij_ private
Definition at line 139 of file Zone_EF.h.
Referenced by Bij(), and modifier_pour_Cl().
Bij_thilde_
DoubleTab Zone_EF::Bij_thilde_ private
stockage des matrice Bije
Definition at line 139 of file Zone_EF.h.
Referenced by Bij_thilde(), and calculer_Bij().
face_normales_
DoubleTab Zone_EF::face_normales_ private
normales aux faces
Definition at line 144 of file Zone_EF.h.
Referenced by discretiser(), ecrit(), face_normales(), modifier_pour_Cl(), printOn(), and readOn().
h_carre
double Zone_EF::h_carre private
carre du pas du maillage
Definition at line 141 of file Zone_EF.h.
Referenced by calculer_h_carre(), carre_pas_du_maillage(), ecrit(), printOn(), and readOn().
h_carre_
DoubleVect Zone_EF::h_carre_ private
carre du pas d'une maille
Definition at line 142 of file Zone_EF.h.
Referenced by calculer_h_carre(), and carre_pas_maille().
ind_faces_virt_non_std_
ArrOfInt Zone_EF::ind_faces_virt_non_std_ private
contient les indices des faces virtuelles non standard
Definition at line 151 of file Zone_EF.h.
Referenced by creer_faces_virtuelles_non_std(), and ind_faces_virt_non_std().
info_obj
const Type_info Zone_EF::info_obj static
Definition at line 63 of file Zone_EF.h.
IPhi_
DoubleTab Zone_EF::IPhi_ protected
Definition at line 135 of file Zone_EF.h.
Referenced by calculer_Bij(), calculer_IPhi(), Zone_EF_axi::calculer_IPhi(), calculer_volumes_sommets(), and IPhi().
IPhi_thilde_
DoubleTab Zone_EF::IPhi_thilde_ protected
Definition at line 135 of file Zone_EF.h.
Referenced by calculer_Bij(), calculer_IPhi(), Zone_EF_axi::calculer_IPhi(), calculer_volumes_sommets(), and IPhi_thilde().
nb_elem_std_
int Zone_EF::nb_elem_std_ private
nombre d'elements standard
Definition at line 146 of file Zone_EF.h.
Referenced by ecrit(), nb_elem_Cl(), nb_elem_std(), printOn(), readOn(), and reordonner().
nb_faces_std_
int Zone_EF::nb_faces_std_ private
nombre de faces standard
Definition at line 145 of file Zone_EF.h.
Referenced by ecrit(), nb_faces_std(), printOn(), readOn(), and reordonner().
orientation_
IntVect Zone_EF::orientation_ private
Definition at line 155 of file Zone_EF.h.
porosite_sommets_
DoubleVect Zone_EF::porosite_sommets_ private
Definition at line 137 of file Zone_EF.h.
Referenced by calculer_Bij(), calculer_porosites_sommets(), calculer_volumes_sommets(), porosite_sommet(), and set_porosite_sommet().
rang_elem_non_std_
IntVect Zone_EF::rang_elem_non_std_ private
rang_elem_non_std_= -1 si l'element est standard rang_elem_non_std_= rang de l'element dans les tableaux relatifs aux elements non standards
Definition at line 147 of file Zone_EF.h.
Referenced by ecrit(), printOn(), rang_elem_non_std(), readOn(), and reordonner().
type_elem_
Elem_EF Zone_EF::type_elem_ private
type de l'element de discretisation
Definition at line 143 of file Zone_EF.h.
Referenced by discretiser(), ecrit(), printOn(), readOn(), type_elem(), and typer_elem().
volumes_sommets_thilde_
DoubleVect Zone_EF::volumes_sommets_thilde_ private
Definition at line 137 of file Zone_EF.h.
Referenced by calculer_Bij(), calculer_volumes_sommets(), discretiser(), and volumes_sommets_thilde().
volumes_thilde_
DoubleVect Zone_EF::volumes_thilde_ private
Definition at line 137 of file Zone_EF.h.
Referenced by calculer_Bij(), calculer_volumes_sommets(), and volumes_thilde().
The documentation for this class was generated from the following files:
src/EF/Zones/Zone_EF.h
src/EF/Zones/Zone_EF.cpp