TRUST: Ref_Champ_Face Class Reference
Ref_Champ_Face Class Reference
#include <Ref_Champ_Face.h>
Public Member Functions
~Ref_Champ_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Champ_Face ()
Ref_Champ_Face (const Champ_Face &)
Ref_Champ_Face (const Ref_Champ_Face &)
const Champ_Face & valeur () const
Champ_Face & valeur ()
const Champ_Face * operator-> () const
Champ_Face * operator-> ()
const Ref_Champ_Face & operator= (const Champ_Face &)
const Ref_Champ_Face & operator= (const Ref_Champ_Face &)
operator const Champ_Face & () const
operator Champ_Face & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Champ_Face & self_cast (Objet_U &)
static const Ref_Champ_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Champ_Face * pointeur_
Detailed Description
Definition at line 29 of file Ref_Champ_Face.h.
Constructor & Destructor Documentation
Ref_Champ_Face::~Ref_Champ_Face ()
Definition at line 26 of file Ref_Champ_Face.cpp.
Ref_Champ_Face::Ref_Champ_Face ()
Definition at line 26 of file Ref_Champ_Face.cpp.
Ref_Champ_Face::Ref_Champ_Face (const Champ_Face & t)
Definition at line 26 of file Ref_Champ_Face.cpp.
Ref_Champ_Face::Ref_Champ_Face (const Ref_Champ_Face & t)
Definition at line 26 of file Ref_Champ_Face.cpp.
Member Function Documentation
Objet_U * Ref_Champ_Face::cree_instance () [static]
Definition at line 26 of file Ref_Champ_Face.cpp.
int Ref_Champ_Face::duplique () const [virtual]
Implements Ref_.
Definition at line 26 of file Ref_Champ_Face.cpp.
const Type_info * Ref_Champ_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Face.cpp.
const Type_info & Ref_Champ_Face::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Ref_Champ_Face.cpp.
const Type_info * Ref_Champ_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Face.cpp.
Ref_Champ_Face::operator Champ_Face & ()
Definition at line 26 of file Ref_Champ_Face.cpp.
Ref_Champ_Face::operator const Champ_Face & () const
Definition at line 26 of file Ref_Champ_Face.cpp.
const Champ_Face * Ref_Champ_Face::operator-> () const [inline]
Definition at line 29 of file Ref_Champ_Face.h.
Champ_Face * Ref_Champ_Face::operator-> () [inline]
Definition at line 29 of file Ref_Champ_Face.h.
const Ref_Champ_Face & Ref_Champ_Face::operator= (const Ref_Champ_Face & t)
Definition at line 26 of file Ref_Champ_Face.cpp.
const Ref_Champ_Face & Ref_Champ_Face::operator= (const Champ_Face & t)
Definition at line 26 of file Ref_Champ_Face.cpp.
Sortie & Ref_Champ_Face::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Face.cpp.
Entree & Ref_Champ_Face::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Face.cpp.
const Ref_Champ_Face & Ref_Champ_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Face.cpp.
Ref_Champ_Face & Ref_Champ_Face::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Face.cpp.
void Ref_Champ_Face::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Ref_Champ_Face.cpp.
unsigned Ref_Champ_Face::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Ref_Champ_Face.cpp.
const Champ_Face & Ref_Champ_Face::valeur () const [inline]
Definition at line 29 of file Ref_Champ_Face.h.
Referenced by Op_Dift_VDF_var_Face_Axi::ajouter(), Op_Dift_VDF_Face_Axi::ajouter(), Op_Dift_VDF_var_Face_Axi::ajouter_contribution(), Op_Dift_VDF_Face_Axi::ajouter_contribution(), Op_Dift_VDF_var_Face_Axi::contribue_au_second_membre(), Op_Dift_VDF_Face_Axi::contribue_au_second_membre(), Op_Diff_VDF_var_Face_Axi::contribue_au_second_membre(), Op_Diff_VDF_Face_Axi::contribue_au_second_membre(), grad_U_Champ_Face::me_calculer(), Taux_cisaillement_P0_VDF::mettre_a_jour(), Eval_Conv_VDF::vitesse(), Reynolds_maille_Champ_Face::vitesse(), and Courant_maille_Champ_Face::vitesse().
Champ_Face & Ref_Champ_Face::valeur () [inline]
Definition at line 29 of file Ref_Champ_Face.h.
Member Data Documentation
const Type_info Ref_Champ_Face::info_obj [static]
Reimplemented from Ref_.
Definition at line 29 of file Ref_Champ_Face.h.
Champ_Face* Ref_Champ_Face::pointeur_ [private]
Definition at line 29 of file Ref_Champ_Face.h.
The documentation for this class was generated from the following files:
src/VDF/Champs/Ref_Champ_Face.h
src/VDF/Champs/Ref_Champ_Face.cpp