TRUST: Ref_Conduction Class Reference
Ref_Conduction Class Reference
#include <Ref_Conduction.h>
Public Member Functions
~Ref_Conduction ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Conduction ()
Ref_Conduction (const Conduction &)
Ref_Conduction (const Ref_Conduction &)
const Conduction & valeur () const
Conduction & valeur ()
const Conduction * operator-> () const
Conduction * operator-> ()
const Ref_Conduction & operator= (const Conduction &)
const Ref_Conduction & operator= (const Ref_Conduction &)
operator const Conduction & () const
operator Conduction & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Conduction & self_cast (Objet_U &)
static const Ref_Conduction & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Conduction * pointeur_
Detailed Description
Definition at line 28 of file Ref_Conduction.h.
Constructor & Destructor Documentation
Ref_Conduction::~Ref_Conduction ()
Definition at line 25 of file Ref_Conduction.cpp.
Ref_Conduction::Ref_Conduction ()
Definition at line 25 of file Ref_Conduction.cpp.
Ref_Conduction::Ref_Conduction (const Conduction & t)
Definition at line 25 of file Ref_Conduction.cpp.
Ref_Conduction::Ref_Conduction (const Ref_Conduction & t)
Definition at line 25 of file Ref_Conduction.cpp.
Member Function Documentation
Objet_U * Ref_Conduction::cree_instance () [static]
Definition at line 25 of file Ref_Conduction.cpp.
int Ref_Conduction::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Conduction.cpp.
const Type_info * Ref_Conduction::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Conduction.cpp.
const Type_info & Ref_Conduction::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Conduction.cpp.
const Type_info * Ref_Conduction::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Conduction.cpp.
Ref_Conduction::operator Conduction & ()
Definition at line 25 of file Ref_Conduction.cpp.
Ref_Conduction::operator const Conduction & () const
Definition at line 25 of file Ref_Conduction.cpp.
const Conduction * Ref_Conduction::operator-> () const [inline]
Definition at line 28 of file Ref_Conduction.h.
Conduction * Ref_Conduction::operator-> () [inline]
Definition at line 28 of file Ref_Conduction.h.
const Ref_Conduction & Ref_Conduction::operator= (const Ref_Conduction & t)
Definition at line 25 of file Ref_Conduction.cpp.
const Ref_Conduction & Ref_Conduction::operator= (const Conduction & t)
Definition at line 25 of file Ref_Conduction.cpp.
Sortie & Ref_Conduction::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Conduction.cpp.
Entree & Ref_Conduction::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Conduction.cpp.
const Ref_Conduction & Ref_Conduction::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Conduction.cpp.
Ref_Conduction & Ref_Conduction::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Conduction.cpp.
void Ref_Conduction::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Conduction.cpp.
unsigned Ref_Conduction::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Conduction.cpp.
const Conduction & Ref_Conduction::valeur () const [inline]
Definition at line 28 of file Ref_Conduction.h.
Referenced by Terme_Source_Solide_SWIFT_VDF::ajouter(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), and Terme_Source_Solide_SWIFT_VDF::readOn().
Conduction & Ref_Conduction::valeur () [inline]
Definition at line 28 of file Ref_Conduction.h.
Member Data Documentation
const Type_info Ref_Conduction::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Conduction.h.
Conduction* Ref_Conduction::pointeur_ [private]
Definition at line 28 of file Ref_Conduction.h.
The documentation for this class was generated from the following files:
src/ThSol/Ref_Conduction.h
src/ThSol/Ref_Conduction.cpp