TRUST: Entree Class Reference
Entree Class Reference
Classe de definition des operateurs et methodes pour toute lecture dans un flot d'entree
(fichier, clavier, tampon de communication, etc)
#include <Entree.h>
Public Types
enum Error_Action { ERROR_EXIT, ERROR_CONTINUE, ERROR_EXCEPTION }
Public Member Functions
Entree ()
Entree (istream &is)
Entree (const Entree &is)
Entree & operator= (istream &is)
Entree & operator= (Entree &is)
virtual istream & get_istream ()
virtual const istream & get_istream () const
void set_istream (istream *is)
Entree & operator>> (Entree &(*f)(Entree &))
Entree & operator>> (istream &(*f)(istream &))
Entree & operator>> (ios &(*f)(ios &))
virtual Entree & operator>> (int &ob)
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
virtual Entree & operator>> (long &ob)
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
virtual Entree & operator>> (float &ob)
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
virtual Entree & operator>> (double &ob)
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
virtual int get (int *ob, int n)
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
virtual int get (long *ob, int n)
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
virtual int get (float *ob, int n)
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
virtual int get (double *ob, int n)
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
virtual int get (char *buf, int bufsize)
Lecture d'une chaine dans ostream_
bufsize est la taille du buffer alloue pour ob (y compris
le caractere 0 final).
La chaine contient toujours un 0 meme en cas d'echec.
La methode renvoie 1 si la lecture est bonne, 0 sinon.
Si le buffer est trop petit, pour l'instant on fait exit() mais
par la suite on pourra tester: si strlen(ob)==bufsize-1, alors
refaire lire() jusqu'a arriver au bout. Si le lire() suivant
renvoie une chaine de longueur nulle, cela signifie que la taille de la
chaine etait exactement bufsize-1.
Attention: le comportement est different en binaire et en ascii.
En binaire, on lit la chaine jusqu'au prochain '\0'.
En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
virtual int eof ()
virtual int fail ()
virtual int good ()
virtual ~Entree ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand.
int is_bin () const
virtual void set_check_types (int flag)
indique si le stream doit verifier les types des objets lus<br>(ints et nombres flottants). Exemple : l'entree contient 123.456 123.456
int i;
check_types(0);
is >> i; // i contient 123
check_types(1);
is >> i; // Erreur : on lit la chaine 123.456 et on essaye de la convertir en int
Voir operator>>(int &)
int check_types () const
renvoie la valeur actuelle du drapeau, voir set_check_types()
virtual void set_error_action (Error_Action)
Change le comportement en cas d'erreur de l'entree,
voir error_handle_() et get_error_action()
Error_Action get_error_action ()
renvoie error_action_ pour cette entree<br>(permet de la modifier et de restaurer ensuite la valeur anterieure)
operator istream & ()
istream & putback (char ch)
istream & ignore (int n=1, int delim=EOF)
virtual void set_diffuse (int diffuse)
ToDo TMA : commenter.
int get_diffuse ()
Protected Member Functions
int error_handle (int fail_flag)
methode inline pour traiter rapidement le cas trivial.
Sinon, appel a la methode virtuelle error_handle_()
virtual int error_handle_ (int fail_flag)
Cette fonction est appellee par operateur>>, get, get_nom
ouvrir, fermer, lire, etc... en cas d'echec (lorsque fail() est mis)
Elle renvoie 0 s'il y a eu une erreur (passer par error_handle() qui
traite en inline le cas ou il n'y a pas d'erreur), et 1 s'il n'y a pas
d'erreur.
(par commodite de codage des methodes qui l'utilisent, on
ecrira "return error_handle(fail());"
Elle peut etre configuree pour
- renvoyer "0" en cas d'erreur et continuer l'execution du code
(cas d'un ancien code qui ne gere pas les exceptions mais teste
le drapeau fail() de temps en temps)
Dans ce cas les methodes operator>> continuent l'execution du code
meme en cas d'echec, le contenu des variables lues est indefini !
- faire Process::exit() (cas d'une portion de code dans laquelle
on ne veut pas faire de gestion d'erreur du tout et ou on suppose
que tout va toujours bien)
- lever une exception (permet une gestion rigoureuse des erreurs
et une information utilisateur optimale en fonction du contexte)
Voir aussi set_error_action()
Protected Attributes
int bin_
bool is_different_int_size_
File with int32 (or int64) whereas version is int64 (or int32à
int check_types_
Error_Action error_action_
int diffuse_
By default 1, but some child classes (eg: LecFicDiffuse) could set temporary to 0 to not diffuse to other processes.
Private Attributes
istream * istream_
Detailed Description
Classe de definition des operateurs et methodes pour toute lecture dans un flot d'entree
(fichier, clavier, tampon de communication, etc)
Definition at line 49 of file Entree.h.
Member Enumeration Documentation
enum Entree::Error_Action
Enumerator:
ERROR_EXIT
ERROR_CONTINUE
ERROR_EXCEPTION
Definition at line 92 of file Entree.h.
{ ERROR_EXIT, ERROR_CONTINUE, ERROR_EXCEPTION };
Constructor & Destructor Documentation
Entree::Entree ()
Definition at line 65 of file Entree.cpp.
References bin_, check_types_, diffuse_, error_action_, ERROR_CONTINUE, is_different_int_size_, and istream_.
{
  bin_=0;
  is_different_int_size_=false;
  istream_ = 0;
  check_types_ = 0;
  error_action_ = ERROR_CONTINUE;
  diffuse_ = 1;
}
Entree::Entree (istream & is)
Definition at line 75 of file Entree.cpp.
References bin_, check_types_, diffuse_, error_action_, ERROR_CONTINUE, is_different_int_size_, and istream_.
{
  bin_=0;
  is_different_int_size_=false;
  istream_ = new istream(is.rdbuf());
  check_types_ = 0;
  error_action_ = ERROR_CONTINUE;
  diffuse_ = 1;
}
Entree::Entree (const Entree & is)
Definition at line 85 of file Entree.cpp.
References bin_, check_types_, diffuse_, error_action_, ERROR_CONTINUE, get_istream(), is_different_int_size_, and istream_.
{
  bin_=0;
  is_different_int_size_=false;
  istream_ = new istream(is.get_istream().rdbuf());
  check_types_ = 0;
  error_action_ = ERROR_CONTINUE;
  diffuse_ = 1;
}
Entree::~Entree () [virtual]
Definition at line 570 of file Entree.cpp.
References istream_.
{
  if(istream_)
    delete istream_;
  istream_=0;
}
Member Function Documentation
int Entree::check_types () const
renvoie la valeur actuelle du drapeau, voir set_check_types()
Definition at line 612 of file Entree.cpp.
References check_types_.
Referenced by Entree_complete::Entree_complete(), and Champ_Proto::lire_dimension().
{
  return check_types_;
}
int Entree::eof () [virtual]
Reimplemented in Entree_complete, Entree_Fichier_base, and Lec_Diffuse_base.
Definition at line 549 of file Entree.cpp.
References istream_.
Referenced by Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), Lec_Diffuse_base::eof(), Entree_complete::eof(), error_handle_(), find_matching_coordinates(), Associer::interpreter(), and Interprete_bloc::interpreter_bloc().
{
  if(istream_)
    return (istream_->eof());
  else
    return -1;
}
int Entree::error_handle (int fail_flag) [inline, protected]
methode inline pour traiter rapidement le cas trivial.
Sinon, appel a la methode virtuelle error_handle_()
Definition at line 129 of file Entree.h.
References error_handle_().
Referenced by Lec_Diffuse_base::get(), get(), Lec_Diffuse_base::operator>>(), and operator>>().
{
  if (!fail_flag)
    return 1;
  else
    return error_handle_(fail_flag);
}
int Entree::error_handle_ (int fail_flag) [protected, virtual]
Cette fonction est appellee par operateur>>, get, get_nom
ouvrir, fermer, lire, etc... en cas d'echec (lorsque fail() est mis)
Elle renvoie 0 s'il y a eu une erreur (passer par error_handle() qui
traite en inline le cas ou il n'y a pas d'erreur), et 1 s'il n'y a pas
d'erreur.
(par commodite de codage des methodes qui l'utilisent, on
ecrira "return error_handle(fail());"
Elle peut etre configuree pour
- renvoyer "0" en cas d'erreur et continuer l'execution du code
(cas d'un ancien code qui ne gere pas les exceptions mais teste
le drapeau fail() de temps en temps)
Dans ce cas les methodes operator>> continuent l'execution du code
meme en cas d'echec, le contenu des variables lues est indefini !
- faire Process::exit() (cas d'une portion de code dans laquelle
on ne veut pas faire de gestion d'erreur du tout et ou on suppose
que tout va toujours bien)
- lever une exception (permet une gestion rigoureuse des erreurs
et une information utilisateur optimale en fonction du contexte)
Voir aussi set_error_action()
Definition at line 637 of file Entree.cpp.
References Cerr, eof(), error_action_, ERROR_CONTINUE, ERROR_EXCEPTION, ERROR_EXIT, Process::exit(), finl, get_istream(), and istream_.
Referenced by error_handle().
{
  if (!fail_flag)
    return 1;
  switch(error_action_)
    {
    case ERROR_CONTINUE:
      break;
    case ERROR_EXIT:
      Cerr << "Error while reading in Entree object. Exiting.\n";
      if (istream_)
        {
// On n'utilise pas Entree::eof() car dans le cas d'un Lec_Fic_Dif
// eof() est parallele et ca peut bloquer.
          if (get_istream().eof())
            Cerr << " End of file reached." << finl;
          else
            Cerr << " IO error (not an EOF error)." << finl;
        }
      Process::exit();
      break;
    case ERROR_EXCEPTION:
      Entree_Sortie_Error e;
      throw (e);
    }
  return 0;
}
int Entree::fail () [virtual]
Reimplemented in Entree_complete, Entree_Fichier_base, and Lec_Diffuse_base.
Definition at line 556 of file Entree.cpp.
References istream_.
Referenced by Lec_Diffuse_base::fail(), and Entree_complete::fail().
{
  if(istream_)
    return (istream_->fail());
  else
    return -1;
}
int Entree::get (int * ob, int n) [virtual]
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
Reimplemented in Entree_complete, and Lec_Diffuse_base.
Definition at line 302 of file Entree.cpp.
References bin_, error_handle(), is_different_int_size_, istream_, and sz.
Referenced by Lec_Diffuse_base::get(), Entree_complete::get(), Champ_implementation_P1::init_from_file(), lire_special(), IntVect::lit(), DoubleVect::lit(), operator>>(), Nom::readOn(), IntTab::readOn(), FloatTab::readOn(), DoubleTab::readOn(), ArrOfInt::readOn(), ArrOfFloat::readOn(), ArrOfDouble::readOn(), and MD_Vector_tools::restore_vector_with_md().
{
  assert(istream_!=0);
  assert(n >= 0);
  if (bin_)
    {
      if (is_different_int_size_)
        {
          for (int i=0; i<n; i++)
            (*this)>> ob[i];
        }
      else
        {
          char * ptr = (char*) ob;
// En binaire: lecture optimisee en bloc:
          std::streamsize sz = sizeof(int);
          sz *= n;
// Overflow checking :
          assert(sz / (std::streamsize)sizeof(int) == (std::streamsize)n);
          istream_->read(ptr, sz);
          error_handle(istream_->fail());
        }
    }
  else
    {
// En ascii : on passe par operator>> pour verifier les conversions
// Attention : on appelle celui de cette classe, pas de la classe derivee
      for (int i = 0; i < n; i++)
        Entree::operator>>(ob[i]);
    }
  return (!istream_->fail());
}
int Entree::get (double * ob, int n) [virtual]
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
Reimplemented in Entree_complete, and Lec_Diffuse_base.
Definition at line 511 of file Entree.cpp.
References bin_, error_handle(), istream_, and sz.
{
  assert(istream_!=0);
  assert(n >= 0);
  if (bin_)
    {
      {
        char * ptr = (char*) ob;
// En binaire: lecture optimisee en bloc:
        std::streamsize sz = sizeof(double);
        sz *= n;
// Overflow checking :
        assert(sz / (std::streamsize)sizeof(double) == (std::streamsize)n);
        istream_->read(ptr, sz);
        error_handle(istream_->fail());
      }
    }
  else
    {
// En ascii : on passe par operator>> pour verifier les conversions
// Attention : on appelle celui de cette classe, pas de la classe derivee
      for (int i = 0; i < n; i++)
        Entree::operator>>(ob[i]);
    }
  return (!istream_->fail());
}
int Entree::get (char * buf, int bufsize) [virtual]
Lecture d'une chaine dans ostream_
bufsize est la taille du buffer alloue pour ob (y compris
le caractere 0 final).
La chaine contient toujours un 0 meme en cas d'echec.
La methode renvoie 1 si la lecture est bonne, 0 sinon.
Si le buffer est trop petit, pour l'instant on fait exit() mais
par la suite on pourra tester: si strlen(ob)==bufsize-1, alors
refaire lire() jusqu'a arriver au bout. Si le lire() suivant
renvoie une chaine de longueur nulle, cela signifie que la taille de la
chaine etait exactement bufsize-1.
Attention: le comportement est different en binaire et en ascii.
En binaire, on lit la chaine jusqu'au prochain '\0'.
En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
Reimplemented in Entree_complete, and Lec_Diffuse_base.
Definition at line 125 of file Entree.cpp.
References bin_, Cerr, error_handle(), Process::exit(), finl, and istream_.
{
  assert(istream_!=0);
  assert(bufsize > 0);
  ob[bufsize-1] = 1;
  if(bin_)
    {
// En binaire, on lit jusqu'au prochain caractere 0
// (y compris espaces, retours a la ligne etc)
      int i;
      for (i = 0; i < bufsize-1; i++)
        {
          (*istream_).read(ob+i, sizeof(char));
          if (!error_handle(istream_->fail()))
            ob[i] = 0;
          if (ob[i] == 0)
            break;
        }
      ob[i] = 0;
    }
  else
    {
// L'appel suivant permet a l'operateur>> de limiter le nombre
// de caracteres lus. On lira au maximum bufsize-1 caracteres.
      istream_->width(bufsize);
      (*istream_) >> ob;
      if (!error_handle(istream_->fail()))
        ob[0] = 0;
    }
  if (ob[bufsize-1] == 0)
    {
// Note Benoit Mathieu:
// Si on a rempli le buffer jusqu'au bout, c'est qu'il est probablement
// trop petit. Lire la suite est dangereux car en ascii on ne sait pas
// si on a pu lire pile poil la chaine (donc c'est ok), ou si la chaine
// n'a pas ete lue en int. Il faut tester tres serieusement la stl et
// ca depend sans doute de l'implementation. Donc, si le buffer est plein,
// on plante le code et tant pis.
      Cerr << "Error in Entree::lire(char* ob, int bufsize) : buffer too small" << finl;
      Process::exit();
    }
  return (!istream_->fail());
}
int Entree::get (long * ob, int n) [virtual]
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
Reimplemented in Entree_complete, and Lec_Diffuse_base.
Definition at line 376 of file Entree.cpp.
References bin_, error_handle(), istream_, and sz.
{
  assert(istream_!=0);
  assert(n >= 0);
  if (bin_)
    {
      {
        char * ptr = (char*) ob;
// En binaire: lecture optimisee en bloc:
        std::streamsize sz = sizeof(long);
        sz *= n;
// Overflow checking :
        assert(sz / (std::streamsize)sizeof(long) == (std::streamsize)n);
        istream_->read(ptr, sz);
        error_handle(istream_->fail());
      }
    }
  else
    {
// En ascii : on passe par operator>> pour verifier les conversions
// Attention : on appelle celui de cette classe, pas de la classe derivee
      for (int i = 0; i < n; i++)
        Entree::operator>>(ob[i]);
    }
  return (!istream_->fail());
}
int Entree::get (float * ob, int n) [virtual]
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
Reimplemented in Entree_complete, and Lec_Diffuse_base.
Definition at line 444 of file Entree.cpp.
References bin_, error_handle(), istream_, and sz.
{
  assert(istream_!=0);
  assert(n >= 0);
  if (bin_)
    {
      {
        char * ptr = (char*) ob;
// En binaire: lecture optimisee en bloc:
        std::streamsize sz = sizeof(float);
        sz *= n;
// Overflow checking :
        assert(sz / (std::streamsize)sizeof(float) == (std::streamsize)n);
        istream_->read(ptr, sz);
        error_handle(istream_->fail());
      }
    }
  else
    {
// En ascii : on passe par operator>> pour verifier les conversions
// Attention : on appelle celui de cette classe, pas de la classe derivee
      for (int i = 0; i < n; i++)
        Entree::operator>>(ob[i]);
    }
  return (!istream_->fail());
}
int Entree::get_diffuse () [inline]
Definition at line 110 of file Entree.h.
References diffuse_.
Referenced by avancer_fichier().
  {
    return diffuse_;
  };
Entree::Error_Action Entree::get_error_action ()
renvoie error_action_ pour cette entree<br>(permet de la modifier et de restaurer ensuite la valeur anterieure)
Definition at line 668 of file Entree.cpp.
References error_action_.
Referenced by Entree_complete::Entree_complete(), Lec_Diffuse_base::get(), and Lec_Diffuse_base::operator>>().
{
  return error_action_;
}
istream & Entree::get_istream () [virtual]
Reimplemented in LecFicDiffuse.
Definition at line 35 of file Entree.cpp.
References istream_.
Referenced by avancer_fichier(), check_ICEM_binary_file(), Entree(), error_handle_(), Entree_complete::get_input(), LecFicDiffuse::get_istream(), ignore(), operator istream &(), operator=(), putback(), read_write_string_from(), and Entree_Brute::set_data().
{
  return *istream_;
}
const istream & Entree::get_istream () const [virtual]
Reimplemented in LecFicDiffuse.
Definition at line 40 of file Entree.cpp.
References istream_.
{
  return *istream_;
}
int Entree::good () [virtual]
Reimplemented in Entree_complete, Entree_Fichier_base, and Lec_Diffuse_base.
Definition at line 563 of file Entree.cpp.
References istream_.
Referenced by Lec_Diffuse_base::good(), Entree_complete::good(), System::interpreter(), Lec_Diffuse_base::operator>>(), and test_solveur().
{
  if(istream_)
    return (istream_->good());
  else
    return -1;
}
istream& Entree::ignore (int n = 1, int delim = EOF) [inline]
Definition at line 104 of file Entree.h.
References get_istream().
  {
    return get_istream().ignore(n,delim);
  };
int Entree::is_bin () const
Definition at line 593 of file Entree.cpp.
References bin_.
{
  return bin_;
}
Entree::operator istream & () [inline]
Definition at line 96 of file Entree.h.
References get_istream().
  {
    return get_istream();
  }   ;
Entree & Entree::operator= (Entree & is)
Definition at line 104 of file Entree.cpp.
References get_istream(), and istream_.
{
  if(istream_)
    delete istream_;
  istream_ = new istream(is.get_istream().rdbuf());
  return *this;
}
Entree & Entree::operator= (istream & is)
Definition at line 96 of file Entree.cpp.
References istream_.
{
  if(istream_)
    delete istream_;
  istream_ = new istream(is.rdbuf());
  return *this;
}
Entree & Entree::operator>> (int & ob) [virtual]
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
< Bien appeler get de cette classe
Reimplemented in Entree_complete, and Lec_Diffuse_base.
Definition at line 254 of file Entree.cpp.
References bin_, check_types_, convert_to(), error_handle(), Process::exit(), get(), is_different_int_size_, and istream_.
{
  assert(istream_!=0);
  if (bin_)
    {
      if (is_different_int_size_)
        {
#ifdef INT_is_64_
          True_int pr;
          char * ptr = (char*) &pr;
          istream_->read(ptr, sizeof(True_int));
          ob=pr;
#else
          long pr;
          char * ptr = (char*) &pr;
          istream_->read(ptr, sizeof(long));
          if (pr>INT32_MAX) Process::exit("Can't read this int64 binary file with an int32 binary: overflow.");
          ob=pr;
#endif
        }
      else
        {
          char * ptr = (char*) &ob;
          istream_->read(ptr, sizeof(int));
          error_handle(istream_->fail());
        }
    }
  else
    {
      if (check_types_)
        {
          char buffer[100];
          int ok = Entree::get(buffer, 100); //!< Bien appeler get de cette classe
          if (ok)
            convert_to(buffer, ob);
        }
      else
        {
          (*istream_) >> ob;
          error_handle(istream_->fail());
        }
    }
  return *this;
}
Entree & Entree::operator>> (ios &(*)(ios &) f)
Definition at line 59 of file Entree.cpp.
{
  (*f)(*istream_);
  return *this;
}
Entree & Entree::operator>> (istream &(*)(istream &) f)
Definition at line 54 of file Entree.cpp.
{
  (*f)(*istream_);
  return *this;
}
Entree & Entree::operator>> (long & ob) [virtual]
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
< Bien appeler get de cette classe
Reimplemented in Entree_complete, and Lec_Diffuse_base.
Definition at line 344 of file Entree.cpp.
References bin_, check_types_, convert_to(), error_handle(), get(), and istream_.
{
  assert(istream_!=0);
  if (bin_)
    {
      {
        char * ptr = (char*) &ob;
        istream_->read(ptr, sizeof(long));
        error_handle(istream_->fail());
      }
    }
  else
    {
      if (check_types_)
        {
          char buffer[100];
          int ok = Entree::get(buffer, 100); //!< Bien appeler get de cette classe
          if (ok)
            convert_to(buffer, ob);
        }
      else
        {
          (*istream_) >> ob;
          error_handle(istream_->fail());
        }
    }
  return *this;
}
Entree & Entree::operator>> (float & ob) [virtual]
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
< Bien appeler get de cette classe
Reimplemented in Entree_complete, and Lec_Diffuse_base.
Definition at line 412 of file Entree.cpp.
References bin_, check_types_, convert_to(), error_handle(), get(), and istream_.
{
  assert(istream_!=0);
  if (bin_)
    {
      {
        char * ptr = (char*) &ob;
        istream_->read(ptr, sizeof(float));
        error_handle(istream_->fail());
      }
    }
  else
    {
      if (check_types_)
        {
          char buffer[100];
          int ok = Entree::get(buffer, 100); //!< Bien appeler get de cette classe
          if (ok)
            convert_to(buffer, ob);
        }
      else
        {
          (*istream_) >> ob;
          error_handle(istream_->fail());
        }
    }
  return *this;
}
Entree & Entree::operator>> (double & ob) [virtual]
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
< Bien appeler get de cette classe
Reimplemented in Entree_complete, and Lec_Diffuse_base.
Definition at line 479 of file Entree.cpp.
References bin_, check_types_, convert_to(), error_handle(), get(), and istream_.
{
  assert(istream_!=0);
  if (bin_)
    {
      {
        char * ptr = (char*) &ob;
        istream_->read(ptr, sizeof(double));
        error_handle(istream_->fail());
      }
    }
  else
    {
      if (check_types_)
        {
          char buffer[100];
          int ok = Entree::get(buffer, 100); //!< Bien appeler get de cette classe
          if (ok)
            convert_to(buffer, ob);
        }
      else
        {
          (*istream_) >> ob;
          error_handle(istream_->fail());
        }
    }
  return *this;
}
Entree & Entree::operator>> (Entree &(*)(Entree &) f)
Definition at line 49 of file Entree.cpp.
{
  (*f)(*this);
  return *this;
}
istream& Entree::putback (char ch) [inline]
Definition at line 100 of file Entree.h.
References get_istream().
  {
    return get_istream().putback(ch);
  };
int Entree::set_bin (int bin) [virtual]
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand.
Reimplemented in Entree_Brute, Entree_complete, and Lec_Diffuse_base.
Definition at line 580 of file Entree.cpp.
References bin_, Cerr, Process::exit(), finl, and istream_.
Referenced by EFichierBin::EFichierBin(), Test_solveur::interpreter(), Raffiner_isotrope_parallele::interpreter(), LecFicDistribueBin::LecFicDistribueBin(), and Lec_Diffuse_base::set_bin().
{
  assert(bin==0 || bin==1);
  bin_ = bin;
  if (istream_)
    {
      Cerr<<"Error you cant change binary format after open "<<finl;
      assert(0);
      Process::exit();
    }
  return bin_;
}
void Entree::set_check_types (int flag) [virtual]
indique si le stream doit verifier les types des objets lus<br>(ints et nombres flottants). Exemple : l'entree contient 123.456 123.456
int i;
check_types(0);
is >> i; // i contient 123
check_types(1);
is >> i; // Erreur : on lit la chaine 123.456 et on essaye de la convertir en int
Voir operator>>(int &)
Reimplemented in Entree_complete, and Lec_Diffuse_base.
Definition at line 606 of file Entree.cpp.
References check_types_.
Referenced by EChaine::EChaine(), Echange_contact_Correlation_VEF_reprendre(), Entree_complete::Entree_complete(), Lire_Ideas::interpreter_(), Champ_Don_Face_lu::readOn(), Lec_Diffuse_base::set_check_types(), and Entree_complete::set_check_types().
{
  check_types_ = flag;
}
void Entree::set_diffuse (int diffuse) [virtual]
ToDo TMA : commenter.
Reimplemented in Lec_Diffuse_base.
Definition at line 702 of file Entree.cpp.
References diffuse_.
Referenced by avancer_fichier().
{
// virtual method does nothing ; cf Lec_Diffuse_base
  diffuse_ = 1;
}
void Entree::set_error_action (Entree::Error_Action action) [virtual]
Change le comportement en cas d'erreur de l'entree,
voir error_handle_() et get_error_action()
Reimplemented in Entree_complete.
Definition at line 675 of file Entree.cpp.
References error_action_.
Referenced by Echange_contact_Correlation_VEF_reprendre(), Entree_complete::Entree_complete(), InputCommBuffer::InputCommBuffer(), Interprete_bloc::interpreter_bloc(), LecFicDiffuse::LecFicDiffuse(), Debog_Pb::read_geometry_data(), Debog_Pb::readOn(), and Entree_complete::set_error_action().
{
  error_action_ = action;
}
void Entree::set_istream (istream * is)
Definition at line 44 of file Entree.cpp.
References istream_.
Referenced by InputCommBuffer::clear(), InputCommBuffer::create_stream(), InputCommBuffer::create_stream_from_output_stream(), Entree_Brute::Entree_Brute(), Entree_Fichier_base::Entree_Fichier_base(), EChaine::init(), Entree_Fichier_base::ouvrir(), and Entree_Brute::set_data().
{
  istream_ = is;
}
Member Data Documentation
int Entree::bin_ [protected]
Definition at line 118 of file Entree.h.
Referenced by Entree(), get(), InputCommBuffer::InputCommBuffer(), is_bin(), LecFicDistribue::LecFicDistribue(), operator>>(), Entree_Fichier_base::ouvrir(), and set_bin().
int Entree::check_types_ [protected]
Definition at line 120 of file Entree.h.
Referenced by check_types(), Entree(), operator>>(), and set_check_types().
int Entree::diffuse_ [protected]
By default 1, but some child classes (eg: LecFicDiffuse) could set temporary to 0 to not diffuse to other processes.
Definition at line 122 of file Entree.h.
Referenced by Entree(), Lec_Diffuse_base::eof(), Lec_Diffuse_base::fail(), Lec_Diffuse_base::get(), get_diffuse(), Lec_Diffuse_base::good(), Lec_Diffuse_base::operator>>(), Lec_Diffuse_base::set_bin(), Lec_Diffuse_base::set_diffuse(), and set_diffuse().
Error_Action Entree::error_action_ [protected]
Definition at line 121 of file Entree.h.
Referenced by Entree(), error_handle_(), get_error_action(), and set_error_action().
bool Entree::is_different_int_size_ [protected]
File with int32 (or int64) whereas version is int64 (or int32à
Definition at line 119 of file Entree.h.
Referenced by Entree(), get(), operator>>(), and Entree_Fichier_base::ouvrir().
istream* Entree::istream_ [private]
Definition at line 124 of file Entree.h.
Referenced by Entree(), eof(), error_handle_(), fail(), get(), get_istream(), good(), operator=(), operator>>(), set_bin(), set_istream(), and ~Entree().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Entree.h
src/Kernel/Utilitaires/Entree.cpp