TRUST: Champ_Generique_base Class Reference
Champ_Generique_base Class Reference abstract
Classe de base des champs generiques pour importation d un champ discret
et actions elementaires sur ce champ<br>(postraitement, etc)
Attention: toutes les methodes sont PARALLELES, il faut les appeler
simultanement sur tous les processeurs (get_domain() peut par exemple
construire le domaine parallele avant de le renvoyer).
#include <Champ_Generique_base.h>
Public Member Functions
Champ_Generique_base ()
~Champ_Generique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int get_dimension () const
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
virtual double get_time () const
Renvoie le temps du Champ_Generique.
virtual const Probleme_base & get_ref_pb_base () const
virtual const Discretisation_base & get_discretisation () const
virtual const Motcle get_directive_pour_discr () const
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
virtual const Nom & get_nom_post () const
virtual void get_property_names (Motcles &list) const
Renvoie la liste des "query" possibles pour le champ.
virtual const Noms get_property (const Motcle &query) const
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
virtual Entity get_localisation (const int index=-1) const
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
virtual int get_nb_localisations () const
virtual const DoubleTab & get_ref_values () const
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_copy_values (DoubleTab &) const
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const
virtual const Domaine & get_ref_domain () const
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual void get_copy_domain (Domaine &) const
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_dis_base & get_ref_zone_dis_base () const
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_Cl_dis_base & get_ref_zcl_dis_base () const
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
virtual const DoubleTab & get_ref_coordinates () const
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
virtual void get_copy_coordinates (DoubleTab &) const
virtual const IntTab & get_ref_connectivity (Entity index1, Entity index2) const
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
virtual void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const
virtual void reset ()=0
virtual void completer (const Postraitement_base &post)=0
virtual void mettre_a_jour (double temps)=0
virtual const Champ_base & get_champ (Champ &espace_stockage) const =0
virtual const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const =0
virtual const Champ_Generique_base & get_champ_post (const Motcle &nom) const
virtual int comprend_champ_post (const Motcle &identifiant) const
virtual int get_info_type_post () const =0
void fixer_identifiant_appel (const Nom &identifiant)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Champ_Generique_base & self_cast (Objet_U &)
static const Champ_Generique_base & self_cast (const Objet_U &)
static int composante (const Nom &nom_test, const Nom &nom, const Noms &composantes, const Noms &synonyms)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Static Protected Member Functions
static void assert_parallel (int)
Protected Attributes
Nom nom_post_
Nom identifiant_appel_
Nom nom_pb_
Ref_Probleme_base ref_pb_
Detailed Description
Classe de base des champs generiques pour importation d un champ discret
et actions elementaires sur ce champ<br>(postraitement, etc)
Attention: toutes les methodes sont PARALLELES, il faut les appeler
simultanement sur tous les processeurs (get_domain() peut par exemple
construire le domaine parallele avant de le renvoyer).
Definition at line 37 of file Champ_Generique_base.h.
Constructor & Destructor Documentation
Champ_Generique_base()
Champ_Generique_base::Champ_Generique_base ()
Definition at line 23 of file Champ_Generique_base.cpp.
~Champ_Generique_base()
Champ_Generique_base::~Champ_Generique_base () override
Definition at line 23 of file Champ_Generique_base.cpp.
Member Function Documentation
assert_parallel()
static void Champ_Generique_base::assert_parallel (int) static protected
completer()
virtual void Champ_Generique_base::completer (const Postraitement_base & post) pure virtual
Implemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Ecart_Type, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_refChamp, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, and Champ_Generique_modifier_pour_QC.
Referenced by Champ_Gen_de_Champs_Gen::completer().
composante()
int Champ_Generique_base::composante (const Nom & nom_test, const Nom & nom, const Noms & composantes, const Noms & synonyms) inline static
Definition at line 139 of file Champ_Generique_base.h.
{
  Motcle motlu(nom_test);
  if (motlu == Motcle(nom))
    return -1;
  for (int i=0; i<syno.size(); i++)
    if (syno[i]==motlu) return -1;
  int n = composantes.size();
  Motcles les_noms_comp(n);
  for (int i=0; i<n; i++)
    les_noms_comp[i] = composantes[i];
  int ncomp = les_noms_comp.search(motlu);
  if (ncomp == -1)
    {
      Cerr << "Error TRUST, the identifier : " << nom_test << finl
           << "did not designate the name of the field tested nor any of its components\n";
      Cerr <<" the components of field named "<<nom <<" are :"<< finl;
      for (int ii=0; ii<n; ii++)
        Cerr << composantes[ii] << " ";
      Cerr << finl;
      exit();
    }
  return ncomp;
}
References Cerr, Process::exit(), finl, Motcles::search(), and vect_impl::size().
Referenced by Sonde::completer(), Postraitement::creer_champ_post(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_Interpolation::get_champ_without_evaluation(), and Postraitement::postraiter_champs().
comprend_champ_post()
int Champ_Generique_base::comprend_champ_post (const Motcle & identifiant) const virtual
Reimplemented in Champ_Gen_de_Champs_Gen, and Champ_Generique_Moyenne.
Definition at line 353 of file Champ_Generique_base.cpp.
{
  Motcle nom_champ;
  const Noms nom_champ_post = get_property("nom");
  nom_champ = Motcle(nom_champ_post[0]);
  if (nom_champ==identifiant)
    return 1;
  else
    {
      const Noms composantes = get_property("composantes");
      int nb_composantes = composantes.size();
      for (int i=0; i<nb_composantes; i++)
        {
          nom_champ = Motcle(composantes[i]);
          if (nom_champ==identifiant)
            return 1;
        }
    }
  return 0;
}
References get_property(), and vect_impl::size().
Referenced by Champ_Gen_de_Champs_Gen::comprend_champ_post().
fixer_identifiant_appel()
void Champ_Generique_base::fixer_identifiant_appel (const Nom & identifiant) inline
Definition at line 134 of file Champ_Generique_base.h.
{
  identifiant_appel_ = identifiant;
}
References identifiant_appel_.
Referenced by Sondes::get_from_cache().
get_champ()
virtual const Champ_base & Champ_Generique_base::get_champ (Champ & espace_stockage) const pure virtual
Implemented in Champ_Generique_Champ, Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Ecart_Type, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_refChamp, Champ_Generique_refChamp_special, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, Champ_Generique_modifier_pour_QC, and Champ_Generique_Tparoi_VEF.
Referenced by Op_Correlation::associer(), Op_Ecart_type::associer(), Op_Moyenne::associer(), build_triofield(), Champ_Generique_Extraction::completer(), Champ_Generique_Gradient::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Post_Operateur_Eqn::completer(), Champ_Generique_Statistiques_base::completer_post_statistiques(), Operateur_Statistique_tps_base::completer_post_statistiques(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_modifier_pour_QC::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_Statistiques_base::get_champ_without_evaluation(), Sondes::get_from_cache(), Integrale_tps_produit_champs::mettre_a_jour(), Integrale_tps_Champ::mettre_a_jour_integrale(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), Postraitement::postraiter_champs(), and Champ_Generique_Transformation::preparer_macro().
get_champ_post()
const Champ_Generique_base & Champ_Generique_base::get_champ_post (const Motcle & nom) const virtual
Reimplemented in Champ_Gen_de_Champs_Gen, and Champ_Generique_Moyenne.
Definition at line 306 of file Champ_Generique_base.cpp.
{
  REF(Champ_Generique_base) ref_champ;
  Motcle nom_champ;
  const Noms nom_champ_post = get_property("nom");
  nom_champ = Motcle(nom_champ_post[0]);
  if (nom_champ==nom)
    {
      ref_champ = *this;
      ref_champ->fixer_identifiant_appel(nom);
      return ref_champ;
    }
  const Noms syno = get_property("synonyms");
  int nb_syno = syno.size();
  for (int i=0; i<nb_syno; i++)
    {
      nom_champ = Motcle(syno[i]);
      if (nom_champ==nom)
        {
          ref_champ = *this;
          ref_champ->fixer_identifiant_appel(nom);
          return ref_champ;
        }
    }
  {
    const Noms composantes = get_property("composantes");
    int nb_composantes = composantes.size();
    for (int i=0; i<nb_composantes; i++)
      {
        nom_champ = Motcle(composantes[i]);
        if (nom_champ==nom)
          {
            ref_champ = *this;
            ref_champ->fixer_identifiant_appel(nom);
            return ref_champ;
          }
      }
  }
  throw Champs_compris_erreur();
  return ref_champ;
}
References get_property(), REF, and vect_impl::size().
Referenced by Postraitement::get_champ_post(), and Champ_Gen_de_Champs_Gen::get_champ_post().
get_champ_without_evaluation()
virtual const Champ_base & Champ_Generique_base::get_champ_without_evaluation (Champ & espace_stockage) const pure virtual
Implemented in Champ_Generique_Divergence, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_refChamp, Champ_Generique_Statistiques_base, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, Champ_Generique_modifier_pour_QC, and Champ_Generique_Tparoi_VEF.
Referenced by Champ_Generique_Transformation::completer(), Champ_Generique_Extraction::get_champ_without_evaluation(), Champ_Generique_Interpolation::get_champ_without_evaluation(), Champ_Generique_modifier_pour_QC::get_champ_without_evaluation(), Champ_Generique_Tparoi_VEF::get_champ_without_evaluation(), and Champ_Generique_Transformation::preparer_macro().
get_copy_connectivity()
void Champ_Generique_base::get_copy_connectivity (Entity index1, Entity index2, IntTab &) const virtual
Reimplemented in Champ_Gen_de_Champs_Gen, and Champ_Generique_refChamp.
Definition at line 258 of file Champ_Generique_base.cpp.
{
  throw Champ_Generique_erreur("NOT_IMPLEMENTED");
}
Referenced by Champ_Gen_de_Champs_Gen::get_copy_connectivity().
get_copy_coordinates()
void Champ_Generique_base::get_copy_coordinates (DoubleTab &) const virtual
Reimplemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Interpolation, and Champ_Generique_refChamp.
Definition at line 232 of file Champ_Generique_base.cpp.
{
  throw Champ_Generique_erreur("NO_REF");
}
Referenced by Champ_Gen_de_Champs_Gen::get_copy_coordinates().
get_copy_domain()
void Champ_Generique_base::get_copy_domain (Domaine & domain) const virtual
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Extraction, and Champ_Generique_Interpolation.
Definition at line 278 of file Champ_Generique_base.cpp.
{
  const Domaine& dom = get_ref_domain();
  domain = dom;
}
References get_ref_domain().
Referenced by Champ_Gen_de_Champs_Gen::get_copy_domain().
get_copy_values()
void Champ_Generique_base::get_copy_values (DoubleTab & values) const virtual
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
Reimplemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Interpolation, and Champ_Generique_refChamp.
Definition at line 187 of file Champ_Generique_base.cpp.
{
  throw Champ_Generique_erreur("NOT_IMPLEMENTED");
}
get_dimension()
int Champ_Generique_base::get_dimension () const virtual
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
Reimplemented in Champ_Gen_de_Champs_Gen, and Champ_Generique_refChamp.
Definition at line 59 of file Champ_Generique_base.cpp.
{
  throw Champ_Generique_erreur("NOT_IMPLEMENTED");
// On n'arrive jamais ici
  return get_dimension();
}
References get_dimension().
Referenced by get_dimension(), and Champ_Gen_de_Champs_Gen::get_dimension().
get_directive_pour_discr()
const Motcle Champ_Generique_base::get_directive_pour_discr () const virtual
Reimplemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_refChamp, and Champ_Generique_Transformation.
Definition at line 93 of file Champ_Generique_base.cpp.
{
  throw Champ_Generique_erreur("NOT_IMPLEMENTED");
  return get_directive_pour_discr();
}
References get_directive_pour_discr().
Referenced by Champ_Generique_Transformation::completer(), Champ_Generique_Transformation::get_champ(), get_directive_pour_discr(), Champ_Gen_de_Champs_Gen::get_directive_pour_discr(), and Champ_Generique_Correlation::get_directive_pour_discr().
get_discretisation()
const Discretisation_base & Champ_Generique_base::get_discretisation () const virtual
Reimplemented in Champ_Gen_de_Champs_Gen.
Definition at line 83 of file Champ_Generique_base.cpp.
{
  const Objet_U& ob = interprete().objet(nom_pb_);
  const Probleme_base& pb = ref_cast(Probleme_base,ob);
  const Discretisation_base& discr = pb.discretisation();
  return discr;
}
References Probleme_base::discretisation(), Objet_U::interprete(), nom_pb_, Interprete::objet(), and ref_cast.
Referenced by Champ_Gen_de_Champs_Gen::get_discretisation().
get_info()
const Type_info * Champ_Generique_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Generique_modifier_pour_QC, and Champ_Generique_Tparoi_VEF.
Definition at line 23 of file Champ_Generique_base.cpp.
get_info_type_post()
virtual int Champ_Generique_base::get_info_type_post () const pure virtual
Implemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Correlation, and Champ_Generique_refChamp.
Referenced by Champ_Gen_de_Champs_Gen::get_info_type_post(), and Postraitement::postraiter_champs().
get_localisation()
Entity Champ_Generique_base::get_localisation (const int index = -1) const virtual
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
Reimplemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Divergence, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_refChamp, Champ_Generique_Transformation, and Champ_Post_Operateur_Eqn.
Definition at line 150 of file Champ_Generique_base.cpp.
{
  throw Champ_Generique_erreur("NOT_IMPLEMENTED");
// On n'arrive jamais ici
  return get_localisation(index);
}
References get_localisation().
Referenced by build_triofield(), get_localisation(), Champ_Gen_de_Champs_Gen::get_localisation(), and Postraitement::postraiter_champs().
get_nb_localisations()
int Champ_Generique_base::get_nb_localisations () const virtual
Definition at line 157 of file Champ_Generique_base.cpp.
{
  throw Champ_Generique_erreur("NOT_IMPLEMENTED");
// On n'arrive jamais ici
  return get_nb_localisations();
}
References get_nb_localisations().
Referenced by get_nb_localisations().
get_nom_post()
const Nom & Champ_Generique_base::get_nom_post () const virtual
Reimplemented in Champ_Generique_Predefini.
Definition at line 104 of file Champ_Generique_base.cpp.
{
  return nom_post_;
}
References nom_post_.
get_property()
const Noms Champ_Generique_base::get_property (const Motcle & query) const virtual
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Reimplemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Ecart_Type, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_refChamp, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, and Champ_Generique_Tparoi_VEF.
Definition at line 127 of file Champ_Generique_base.cpp.
{
  throw Champ_Generique_erreur("NOT_IMPLEMENTED");
// On n'arrive jamais ici
  return get_property(query);
}
References get_property().
Referenced by Sonde::completer(), Champ_Generique_Correlation::completer(), Champ_Generique_Ecart_Type::completer(), Champ_Generique_Transformation::completer(), comprend_champ_post(), Champ_Generique_Moyenne::comprend_champ_post(), Champ_Generique_Transformation::creer_expression_macro(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Transformation::get_champ(), get_champ_post(), Champ_Generique_Moyenne::get_champ_post(), Champ_Generique_Divergence::get_champ_without_evaluation(), Champ_Generique_Gradient::get_champ_without_evaluation(), get_property(), Champ_Gen_de_Champs_Gen::get_property(), Champ_Generique_Divergence::get_property(), Champ_Generique_Ecart_Type::get_property(), Champ_Generique_Extraction::get_property(), Champ_Generique_Gradient::get_property(), Champ_Generique_Interpolation::get_property(), Champ_Generique_Moyenne::get_property(), Champ_Generique_Tparoi_VEF::get_property(), Sonde::initialiser(), Postraitement::lire_champs_a_postraiter(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), Champ_Generique_Correlation::nommer_source(), Champ_Generique_Divergence::nommer_source(), Champ_Generique_Ecart_Type::nommer_source(), Champ_Generique_Extraction::nommer_source(), Champ_Generique_Gradient::nommer_source(), Champ_Generique_Interpolation::nommer_source(), Champ_Generique_Moyenne::nommer_source(), Champ_Generique_modifier_pour_QC::nommer_source(), Champ_Generique_Tparoi_VEF::nommer_source(), Sonde::postraiter(), Postraitement::postraiter_champs(), and Champ_Generique_Transformation::preparer_macro().
get_property_names()
void Champ_Generique_base::get_property_names (Motcles & list) const virtual
Renvoie la liste des "query" possibles pour le champ.
Reimplemented in Champ_Gen_de_Champs_Gen, and Champ_Generique_refChamp.
Definition at line 111 of file Champ_Generique_base.cpp.
{
  throw Champ_Generique_erreur("NOT_IMPLEMENTED");
}
Referenced by Champ_Gen_de_Champs_Gen::get_property_names().
get_ref_connectivity()
const IntTab & Champ_Generique_base::get_ref_connectivity (Entity index1, Entity index2) const virtual
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
Reimplemented in Champ_Gen_de_Champs_Gen, and Champ_Generique_refChamp.
Definition at line 251 of file Champ_Generique_base.cpp.
{
  throw Champ_Generique_erreur("NOT_IMPLEMENTED");
// On n'arrive jamais ici
  return get_ref_connectivity(index1,index2);
}
References get_ref_connectivity().
Referenced by Champ_Generique_Extraction::completer(), get_ref_connectivity(), and Champ_Gen_de_Champs_Gen::get_ref_connectivity().
get_ref_coordinates()
const DoubleTab & Champ_Generique_base::get_ref_coordinates () const virtual
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
Reimplemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Interpolation, and Champ_Generique_refChamp.
Definition at line 223 of file Champ_Generique_base.cpp.
{
// Implementation par defaut : exception NO_REF
  throw Champ_Generique_erreur("NO_REF");
// On n'arrive jamais ici
  return get_ref_coordinates();
}
References get_ref_coordinates().
Referenced by get_ref_coordinates(), and Champ_Gen_de_Champs_Gen::get_ref_coordinates().
get_ref_domain()
const Domaine & Champ_Generique_base::get_ref_domain () const virtual
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Extraction, and Champ_Generique_Interpolation.
Definition at line 266 of file Champ_Generique_base.cpp.
{
  const Objet_U& ob = interprete().objet(nom_pb_);
  const Probleme_base& pb = ref_cast(Probleme_base,ob);
  const Domaine& dom = pb.domaine_dis().domaine();
  return dom;
}
References Domaine_dis::domaine(), Probleme_base::domaine_dis(), Objet_U::interprete(), nom_pb_, Interprete::objet(), and ref_cast.
Referenced by Sonde::ajouter_bords(), Champ_Generique_Extraction::completer(), Champ_Generique_Interpolation::completer(), get_copy_domain(), Champ_Generique_refChamp::get_ref_coordinates(), Champ_Gen_de_Champs_Gen::get_ref_domain(), Champ_Generique_Interpolation::get_ref_domain(), Sonde::initialiser(), and Champ_Generique_refChamp::nommer_source().
get_ref_pb_base()
const Probleme_base & Champ_Generique_base::get_ref_pb_base () const virtual
Reimplemented in Champ_Gen_de_Champs_Gen, and Champ_Generique_refChamp.
Definition at line 76 of file Champ_Generique_base.cpp.
{
  throw Champ_Generique_erreur("NOT_IMPLEMENTED");
  return get_ref_pb_base();
}
References get_ref_pb_base().
Referenced by get_ref_pb_base(), and Champ_Gen_de_Champs_Gen::get_ref_pb_base().
get_ref_values()
const DoubleTab & Champ_Generique_base::get_ref_values () const virtual
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
Reimplemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Interpolation, Champ_Generique_refChamp, and Champ_Generique_refChamp_special.
Definition at line 174 of file Champ_Generique_base.cpp.
{
// Implementation par defaut : exception NO_REF
  throw Champ_Generique_erreur("NO_REF");
// On n'arrive jamais ici
  return get_ref_values();
}
References get_ref_values().
Referenced by get_ref_values(), and Champ_Gen_de_Champs_Gen::get_ref_values().
get_ref_zcl_dis_base()
const Zone_Cl_dis_base & Champ_Generique_base::get_ref_zcl_dis_base () const virtual
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
Reimplemented in Champ_Gen_de_Champs_Gen, and Champ_Generique_refChamp.
Definition at line 299 of file Champ_Generique_base.cpp.
{
  throw Champ_Generique_erreur("INVALID");
// On n'arrive jamais ici
  return get_ref_zcl_dis_base();
}
References get_ref_zcl_dis_base().
Referenced by get_ref_zcl_dis_base(), and Champ_Gen_de_Champs_Gen::get_ref_zcl_dis_base().
get_ref_zone_dis_base()
const Zone_dis_base & Champ_Generique_base::get_ref_zone_dis_base () const virtual
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Extraction, and Champ_Generique_Interpolation.
Definition at line 289 of file Champ_Generique_base.cpp.
{
  const Objet_U& ob = interprete().objet(nom_pb_);
  const Probleme_base& pb = ref_cast(Probleme_base,ob);
  const Zone_dis_base& zone_dis = pb.domaine_dis().zone_dis(0).valeur();
  return zone_dis;
}
References Probleme_base::domaine_dis(), Objet_U::interprete(), nom_pb_, Interprete::objet(), ref_cast, Deriv_Zone_dis_base::valeur(), and Domaine_dis::zone_dis().
Referenced by Sonde::ajouter_bords(), build_triofield(), Champ_Generique_Extraction::completer(), Champ_Generique_Extraction::get_champ(), Champ_Generique_refChamp::get_localisation(), Champ_Gen_de_Champs_Gen::get_ref_zone_dis_base(), Sonde::initialiser(), and Sonde::mettre_a_jour_bords().
get_time()
double Champ_Generique_base::get_time () const virtual
Renvoie le temps du Champ_Generique.
Reimplemented in Champ_Gen_de_Champs_Gen, and Champ_Generique_refChamp.
Definition at line 68 of file Champ_Generique_base.cpp.
{
  throw Champ_Generique_erreur("NOT_IMPLEMENTED");
// On n'arrive jamais ici
  return get_time();
}
References get_time().
Referenced by build_triofield(), Champ_Generique_Extraction::get_champ(), get_time(), Champ_Gen_de_Champs_Gen::get_time(), Sonde::mettre_a_jour(), Integrale_tps_Champ::mettre_a_jour(), Integrale_tps_Champ::mettre_a_jour_integrale(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), and Postraitement::postraiter_champs().
get_xyz_values()
void Champ_Generique_base::get_xyz_values (const DoubleTab & coords, DoubleTab & values, ArrOfBit & validity_flag) const virtual
Calcule la valeur ponctuelle du champ aux coordonnees donnees dans coords et
les met dans values. validity_flag est rempli avec 1 si la valeur est valide
(coordonnees a l'interieur du domaine), 0 sinon. < Attention en parallele: Chaque processeur traite le tableau coords qui lui est fourni : on peut soit faire calculer le meme tableau a tout le monde: dans ce cas, validity_flag indique sur chaque processeur quelles valeurs chaque processeur a pu calculer, soit on sait par avance quelles coordonnees sont calculable par chaque processeur et on donne au processeur local uniquement des coordonnees qu'il possede. Si une meme coordonnee est demandee a plusieurs processeurs, on ne garantit pas que tous donnent le meme resultat. En general, un seul aura le validity_flag mis pour cette coordonnee. Exceptions: - GenericFieldError::NOT_IMPLEMENTED : le paresseux n'a pas code les methodes d'interpolation il faut se debrouiller avec le maillage et les valeurs discretes. - GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie
Reimplemented in Champ_Gen_de_Champs_Gen, and Champ_Generique_refChamp.
Definition at line 208 of file Champ_Generique_base.cpp.
{
  throw Champ_Generique_erreur("NOT_IMPLEMENTED");
}
info()
const Type_info * Champ_Generique_base::info () static
Definition at line 23 of file Champ_Generique_base.cpp.
lire_motcle_non_standard()
int Champ_Generique_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Objet_U.
Definition at line 46 of file Champ_Generique_base.cpp.
{
  Cerr << mot << " is not a keyword understood by " << que_suis_je() << " in lire_motcle_non_standard"<< finl;
  exit();
  return -1;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), Champ_Generique_Predefini::lire_motcle_non_standard(), and Champ_Generique_refChamp::lire_motcle_non_standard().
mettre_a_jour()
virtual void Champ_Generique_base::mettre_a_jour (double temps) pure virtual
Implemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Champ, Champ_Generique_refChamp, and Champ_Generique_Statistiques_base.
nommer()
void Champ_Generique_base::nommer (const Nom &) override virtual
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
Reimplemented from Objet_U.
Definition at line 99 of file Champ_Generique_base.cpp.
{
  nom_post_ = nom;
}
References nom_post_.
Referenced by Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), Champ_Generique_refChamp::lire_motcle_non_standard(), Champ_Generique_refChamp::nommer_source(), Champ_Generique_Correlation::nommer_source(), Champ_Generique_Divergence::nommer_source(), Champ_Generique_Ecart_Type::nommer_source(), Champ_Generique_Extraction::nommer_source(), Champ_Generique_Gradient::nommer_source(), Champ_Generique_Interpolation::nommer_source(), Champ_Generique_Morceau_Equation::nommer_source(), Champ_Generique_Moyenne::nommer_source(), Champ_Generique_Transformation::nommer_source(), Champ_Post_Operateur_Eqn::nommer_source(), Champ_Generique_modifier_pour_QC::nommer_source(), and Champ_Generique_Tparoi_VEF::nommer_source().
printOn()
Sortie & Champ_Generique_base::printOn (Sortie & os) const override protected virtual
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Champ_Generique_modifier_pour_QC, and Champ_Generique_Tparoi_VEF.
Definition at line 32 of file Champ_Generique_base.cpp.
{
  return os;
}
readOn()
Entree & Champ_Generique_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Generique_modifier_pour_QC, and Champ_Generique_Tparoi_VEF.
Definition at line 37 of file Champ_Generique_base.cpp.
{
  Journal()<<"Reading data for a "<<que_suis_je()<<" field." <<finl;
  Param param(que_suis_je());
  set_param(param);
  param.lire_avec_accolades_depuis(is);
  return is;
}
References finl, Process::Journal(), Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
Referenced by Champ_Gen_de_Champs_Gen::readOn(), and Champ_Generique_refChamp::readOn().
reset()
virtual void Champ_Generique_base::reset () pure virtual
Implemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Champ, Champ_Generique_Interpolation, and Champ_Generique_refChamp.
self_cast() [1/2]
const Champ_Generique_base & Champ_Generique_base::self_cast (const Objet_U & r) static
Definition at line 23 of file Champ_Generique_base.cpp.
self_cast() [2/2]
Champ_Generique_base & Champ_Generique_base::self_cast (Objet_U & r) static
Definition at line 23 of file Champ_Generique_base.cpp.
set_param()
virtual void Champ_Generique_base::set_param (Param & param) pure virtual
Implemented in Champ_Gen_de_Champs_Gen, Champ_Generique_Champ, Champ_Generique_Extraction, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_refChamp, Champ_Generique_refChamp_special, Champ_Generique_Statistiques_base, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, and Champ_Generique_modifier_pour_QC.
Referenced by readOn().
Member Data Documentation
identifiant_appel_
Nom Champ_Generique_base::identifiant_appel_ protected
Definition at line 129 of file Champ_Generique_base.h.
Referenced by fixer_identifiant_appel(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), and Champ_Generique_Interpolation::get_champ_without_evaluation().
info_obj
const Type_info Champ_Generique_base::info_obj static
Definition at line 39 of file Champ_Generique_base.h.
nom_pb_
Nom Champ_Generique_base::nom_pb_ protected
Definition at line 130 of file Champ_Generique_base.h.
Referenced by Champ_Gen_de_Champs_Gen::completer(), Champ_Generique_refChamp_special::get_champ(), get_discretisation(), get_ref_domain(), get_ref_zone_dis_base(), Champ_Generique_refChamp::lire_motcle_non_standard(), and Champ_Generique_Champ::set_param().
nom_post_
Nom Champ_Generique_base::nom_post_ protected
Definition at line 128 of file Champ_Generique_base.h.
Referenced by Champ_Generique_Extraction::completer(), Champ_Generique_Transformation::completer(), Champ_Generique_Morceau_Equation::get_directive_pour_discr(), Champ_Generique_Divergence::get_localisation(), Champ_Generique_Gradient::get_localisation(), Champ_Generique_Interpolation::get_localisation(), Champ_Generique_Morceau_Equation::get_localisation(), Champ_Generique_Transformation::get_localisation(), get_nom_post(), Champ_Gen_de_Champs_Gen::get_property(), Champ_Generique_Divergence::get_property(), Champ_Generique_Ecart_Type::get_property(), Champ_Generique_Extraction::get_property(), Champ_Generique_Gradient::get_property(), Champ_Generique_Interpolation::get_property(), Champ_Generique_Morceau_Equation::get_property(), Champ_Generique_Moyenne::get_property(), Champ_Generique_refChamp::get_property(), Champ_Generique_Transformation::get_property(), Champ_Post_Operateur_Eqn::get_property(), Champ_Generique_Tparoi_VEF::get_property(), nommer(), Champ_Generique_refChamp::nommer_source(), Champ_Generique_Correlation::nommer_source(), Champ_Generique_Divergence::nommer_source(), Champ_Generique_Ecart_Type::nommer_source(), Champ_Generique_Extraction::nommer_source(), Champ_Generique_Gradient::nommer_source(), Champ_Generique_Interpolation::nommer_source(), Champ_Generique_Morceau_Equation::nommer_source(), Champ_Generique_Moyenne::nommer_source(), Champ_Generique_Transformation::nommer_source(), Champ_Post_Operateur_Eqn::nommer_source(), Champ_Generique_modifier_pour_QC::nommer_source(), Champ_Generique_Tparoi_VEF::nommer_source(), and Champ_Generique_Transformation::preparer_macro().
ref_pb_
Ref_Probleme_base Champ_Generique_base::ref_pb_ protected
Definition at line 131 of file Champ_Generique_base.h.
Referenced by Champ_Generique_refChamp::get_champ(), Champ_Generique_refChamp::get_ref_pb_base(), and Champ_Generique_refChamp::lire_motcle_non_standard().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_Generique_base.h
src/Kernel/Framework/Champ_Generique_base.cpp