TRUST: Deriv_Operateur_Statistique_tps_base Class Reference
Deriv_Operateur_Statistique_tps_base Class Reference
#include <Operateur_Statistique_tps.h>
Public Member Functions
~Deriv_Operateur_Statistique_tps_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Operateur_Statistique_tps_base ()
Deriv_Operateur_Statistique_tps_base (const Deriv_Operateur_Statistique_tps_base &)
const
Operateur_Statistique_tps_base & valeur () const
Operateur_Statistique_tps_base & valeur ()
const
Operateur_Statistique_tps_base * operator-> () const
Operateur_Statistique_tps_base * operator-> ()
const
Deriv_Operateur_Statistique_tps_base & operator= (const Operateur_Statistique_tps_base &)
const
Deriv_Operateur_Statistique_tps_base & operator= (const Deriv_Operateur_Statistique_tps_base &)
operator const Operateur_Statistique_tps_base & () const
operator Operateur_Statistique_tps_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Deriv_Operateur_Statistique_tps_base & self_cast (Objet_U &)
static const
Deriv_Operateur_Statistique_tps_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Operateur_Statistique_tps_base * pointeur_
Detailed Description
Definition at line 32 of file Operateur_Statistique_tps.h.
Constructor & Destructor Documentation
Deriv_Operateur_Statistique_tps_base::~Deriv_Operateur_Statistique_tps_base ()
Definition at line 25 of file Operateur_Statistique_tps.cpp.
Deriv_Operateur_Statistique_tps_base::Deriv_Operateur_Statistique_tps_base ()
Definition at line 25 of file Operateur_Statistique_tps.cpp.
Deriv_Operateur_Statistique_tps_base::Deriv_Operateur_Statistique_tps_base (const Deriv_Operateur_Statistique_tps_base & t)
Definition at line 25 of file Operateur_Statistique_tps.cpp.
Member Function Documentation
Objet_U * Deriv_Operateur_Statistique_tps_base::cree_instance () [static]
Reimplemented in Operateur_Statistique_tps.
Definition at line 25 of file Operateur_Statistique_tps.cpp.
int Deriv_Operateur_Statistique_tps_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Operateur_Statistique_tps.
Definition at line 25 of file Operateur_Statistique_tps.cpp.
const Type_info * Deriv_Operateur_Statistique_tps_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Operateur_Statistique_tps.
Definition at line 25 of file Operateur_Statistique_tps.cpp.
const Type_info & Deriv_Operateur_Statistique_tps_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Operateur_Statistique_tps.cpp.
const Type_info * Deriv_Operateur_Statistique_tps_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Operateur_Statistique_tps.
Definition at line 25 of file Operateur_Statistique_tps.cpp.
Deriv_Operateur_Statistique_tps_base::operator const Operateur_Statistique_tps_base & () const
Definition at line 25 of file Operateur_Statistique_tps.cpp.
Deriv_Operateur_Statistique_tps_base::operator Operateur_Statistique_tps_base & ()
Definition at line 25 of file Operateur_Statistique_tps.cpp.
const Operateur_Statistique_tps_base * Deriv_Operateur_Statistique_tps_base::operator-> () const [inline]
Definition at line 32 of file Operateur_Statistique_tps.h.
: public DERIV(Operateur_Statistique_tps_base)
Operateur_Statistique_tps_base * Deriv_Operateur_Statistique_tps_base::operator-> () [inline]
Definition at line 32 of file Operateur_Statistique_tps.h.
: public DERIV(Operateur_Statistique_tps_base)
const Deriv_Operateur_Statistique_tps_base & Deriv_Operateur_Statistique_tps_base::operator= (const Deriv_Operateur_Statistique_tps_base & t)
Definition at line 25 of file Operateur_Statistique_tps.cpp.
const Deriv_Operateur_Statistique_tps_base & Deriv_Operateur_Statistique_tps_base::operator= (const Operateur_Statistique_tps_base & t)
Reimplemented in Operateur_Statistique_tps.
Definition at line 25 of file Operateur_Statistique_tps.cpp.
Sortie & Deriv_Operateur_Statistique_tps_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Operateur_Statistique_tps.
Definition at line 25 of file Operateur_Statistique_tps.cpp.
Entree & Deriv_Operateur_Statistique_tps_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Operateur_Statistique_tps.
Definition at line 25 of file Operateur_Statistique_tps.cpp.
const Deriv_Operateur_Statistique_tps_base & Deriv_Operateur_Statistique_tps_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Operateur_Statistique_tps.
Definition at line 25 of file Operateur_Statistique_tps.cpp.
Deriv_Operateur_Statistique_tps_base & Deriv_Operateur_Statistique_tps_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Operateur_Statistique_tps.
Definition at line 25 of file Operateur_Statistique_tps.cpp.
void Deriv_Operateur_Statistique_tps_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Operateur_Statistique_tps.cpp.
unsigned Deriv_Operateur_Statistique_tps_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Operateur_Statistique_tps.
Definition at line 25 of file Operateur_Statistique_tps.cpp.
const Operateur_Statistique_tps_base & Deriv_Operateur_Statistique_tps_base::valeur () const [inline]
Definition at line 32 of file Operateur_Statistique_tps.h.
Referenced by Operateur_Statistique_tps::calculer_valeurs(), Operateur_Statistique_tps::completer(), Operateur_Statistique_tps::completer_post_statistiques(), Operateur_Statistique_tps::fixer_tstat_deb(), Operateur_Statistique_tps::fixer_tstat_fin(), Operateur_Statistique_tps::initialiser(), Operateur_Statistique_tps::integrale(), Operateur_Statistique_tps::le_nom(), Operateur_Statistique_tps::localisation_post(), Operateur_Statistique_tps::mettre_a_jour(), Operateur_Statistique_tps::reprendre(), Operateur_Statistique_tps::sauvegarder(), and Operateur_Statistique_tps::temps().
: public DERIV(Operateur_Statistique_tps_base)
Operateur_Statistique_tps_base & Deriv_Operateur_Statistique_tps_base::valeur () [inline]
Definition at line 32 of file Operateur_Statistique_tps.h.
: public DERIV(Operateur_Statistique_tps_base)
Member Data Documentation
const Type_info Deriv_Operateur_Statistique_tps_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Operateur_Statistique_tps.
Definition at line 32 of file Operateur_Statistique_tps.h.
Operateur_Statistique_tps_base* Deriv_Operateur_Statistique_tps_base::pointeur_ [private]
Definition at line 32 of file Operateur_Statistique_tps.h.
The documentation for this class was generated from the following files:
src/Kernel/Statistiques_temps/Operateur_Statistique_tps.h
src/Kernel/Statistiques_temps/Operateur_Statistique_tps.cpp