TRUST: Elem_geom Class Reference
Elem_geom Class Reference
#include <Elem_geom.h>
Public Member Functions
Elem_geom ()
~Elem_geom ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Appel a l'objet sous-jacent
Associe l'element geometrique a sa zone.
void creer_faces_elem (Faces &, int) const
Appel a l'objet sous-jacent
Cree les faces de l'element specifie de la zone.
(sans specifier le type de face a creer)
void creer_faces_elem (Faces &, int, Type_Face) const
Appel a l'objet sous-jacent
Cree les faces de l'element specifie de la zone
en specifiant le type de de face a creer.
void face_sommet (int i, int j) const
Appel a l'objet sous-jacent
Renvoie le j-ieme sommet de la i-ieme face de
l'element.
int nb_som () const
Appel a l'objet sous-jacent
Renvoie le nombre de sommets de l'element.
int nb_faces (int=0) const
Appel a l'objet sous-jacent
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
int nb_som_face (int=0) const
Appel a l'objet sous-jacent
Renvoie le nombre de sommets des faces
du type specifie.
int est_structure () const
Appel a l'objet sous-jacent
Renvoie 1 si l'element geometrique est structure,
0 sinon.
const Nom & nom_lml () const
int contient (const ArrOfDouble &, int) const
Appel a l'objet sous-jacent
Renvoie 1 si l'element i de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
int contient (const ArrOfInt &, int) const
Appel a l'objet sous-jacent
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element i de la zone associee a
l'element geometrique.
int nb_type_face () const
Appel a l'objet sous-jacent
Renvoie le nombre de type de face
de l'element geometrique.
Type_Face type_face (int=0) const
Appel a l'objet sous-jacent
Renvoie le i-eme type de face de l'element
geometrique.
void calculer_centres_gravite (DoubleTab &) const
Appel a l'objet sous-jacent
Calcule les centres de gravites de tous les elements
de la zone geometrique associee.
void reordonner ()
Appel a l'objet sous-jacent
Reordonne les sommets du maillage.
void calculer_volumes (DoubleVect &) const
Appel a l'objet sous-jacent
Calcule les volumes des elements de la zone associee.
void calculer_normales (const IntTab &, DoubleTab &) const
Appel a l'objet sous-jacent
Calcule les normales aux faces des elements de la zone associee.
Public Member Functions inherited from Deriv_Elem_geom_base
~Deriv_Elem_geom_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Elem_geom_base ()
Deriv_Elem_geom_base (const Deriv_Elem_geom_base &)
const Elem_geom_base & valeur () const
Elem_geom_base & valeur ()
const Elem_geom_base * operator-> () const
Elem_geom_base * operator-> ()
const Deriv_Elem_geom_base & operator= (const Elem_geom_base &)
const Deriv_Elem_geom_base & operator= (const Deriv_Elem_geom_base &)
operator const Elem_geom_base & () const
operator Elem_geom_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Elem_geom & self_cast (Objet_U &)
static const Elem_geom & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Elem_geom_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Elem_geom_base & self_cast (Objet_U &)
static const Deriv_Elem_geom_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Elem_geom_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from Deriv_Elem_geom_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Definition at line 38 of file Elem_geom.h.
Constructor & Destructor Documentation
Elem_geom()
Elem_geom::Elem_geom ()
Definition at line 20 of file Elem_geom.cpp.
~Elem_geom()
Elem_geom::~Elem_geom ()
Definition at line 20 of file Elem_geom.cpp.
Member Function Documentation
associer_zone()
void Elem_geom::associer_zone (const Zone & z) inline
Appel a l'objet sous-jacent
Associe l'element geometrique a sa zone.
Definition at line 80 of file Elem_geom.h.
{
  valeur().associer_zone(z);
}
References Elem_geom_base::associer_zone(), and Deriv_Elem_geom_base::valeur().
Referenced by Zone::check_zone(), DomaineCutter::construire_sous_domaine(), convert_domain_to_Domaine(), Interprete_geometrique_base::interpreter(), Extraire_domaine::interpreter_(), Extruder_en3::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), Mailler::interpreter_(), and Zone::typer().
calculer_centres_gravite()
void Elem_geom::calculer_centres_gravite (DoubleTab & xp) const inline
Appel a l'objet sous-jacent
Calcule les centres de gravites de tous les elements
de la zone geometrique associee.
Definition at line 191 of file Elem_geom.h.
{
  valeur().calculer_centres_gravite(xp);
}
References Elem_geom_base::calculer_centres_gravite(), and Deriv_Elem_geom_base::valeur().
Referenced by Zone::calculer_centres_gravite(), Raffiner_anisotrope::Raffiner_anisotrope_(), Remove_elem::Remove_elem_(), Trianguler_fin::trianguler(), and Trianguler_H::trianguler().
calculer_normales()
void Elem_geom::calculer_normales (const IntTab & face_sommets, DoubleTab & face_normales) const inline
Appel a l'objet sous-jacent
Calcule les normales aux faces des elements de la zone associee.
Definition at line 237 of file Elem_geom.h.
{
  valeur().calculer_normales(face_sommets,face_normales);
}
References Elem_geom_base::calculer_normales(), and Deriv_Elem_geom_base::valeur().
Referenced by Reordonner_faces_periodiques::chercher_direction_perio().
calculer_volumes()
void Elem_geom::calculer_volumes (DoubleVect & volumes) const inline
Appel a l'objet sous-jacent
Calcule les volumes des elements de la zone associee.
Definition at line 213 of file Elem_geom.h.
{
  valeur().calculer_volumes(volumes);
}
References Elem_geom_base::calculer_volumes(), and Deriv_Elem_geom_base::valeur().
Referenced by Zone::calculer_volumes().
contient() [1/2]
int Elem_geom::contient (const ArrOfDouble & pos, int i) const inline
Appel a l'objet sous-jacent
Renvoie 1 si l'element i de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
Returns
int
Signification: 1 si le point de coordonnees specifiees
appartient a l'element i
0 sinon
Contraintes:
Definition at line 382 of file Elem_geom.h.
{
  return valeur().contient(pos, i);
}
References Elem_geom_base::contient(), and Deriv_Elem_geom_base::valeur().
Referenced by Source_Dirac_VDF_Elem::associer_zones(), Source_Dirac_VEF_Face::associer_zones(), Eval_Dirac_VDF_Elem::calculer_terme_source(), Eval_Dirac_VEF_Face::calculer_terme_source_non_standard(), Eval_Dirac_VEF_Face::calculer_terme_source_standard(), Octree_Zone::find_elements(), OctreeFloor::rang_elem_depuis_loc(), and OctreeFloor::rang_elem_loc().
contient() [2/2]
int Elem_geom::contient (const ArrOfInt & pos, int i) const inline
Appel a l'objet sous-jacent
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element i de la zone associee a
l'element geometrique.
Returns
int
Signification: 1 si les sommets passes en parametre
sont ceux de l'element i, 0 sinon
Contraintes:
Definition at line 413 of file Elem_geom.h.
{
  return valeur().contient(pos, i);
}
References Elem_geom_base::contient(), and Deriv_Elem_geom_base::valeur().
cree_instance()
Objet_U * Elem_geom::cree_instance () static
Definition at line 20 of file Elem_geom.cpp.
creer_faces_elem() [1/2]
void Elem_geom::creer_faces_elem (Faces & les_faces, int num_elem) const inline
Appel a l'objet sous-jacent
Cree les faces de l'element specifie de la zone.
(sans specifier le type de face a creer)
Definition at line 135 of file Elem_geom.h.
{
  valeur().creer_faces_elem(les_faces,num_elem);
}
References Elem_geom_base::creer_faces_elem(), and Deriv_Elem_geom_base::valeur().
creer_faces_elem() [2/2]
void Elem_geom::creer_faces_elem (Faces & les_faces, int num_elem, Type_Face typ) const inline
Appel a l'objet sous-jacent
Cree les faces de l'element specifie de la zone
en specifiant le type de de face a creer.
Definition at line 168 of file Elem_geom.h.
{
  valeur().creer_faces_elem(les_faces,num_elem,typ);
}
References Elem_geom_base::creer_faces_elem(), and Deriv_Elem_geom_base::valeur().
duplique()
int Elem_geom::duplique () const override virtual
Reimplemented from Deriv_Elem_geom_base.
Definition at line 20 of file Elem_geom.cpp.
est_structure()
int Elem_geom::est_structure () const inline
Appel a l'objet sous-jacent
Renvoie 1 si l'element geometrique est structure,
0 sinon.
Returns
int
Signification: renvoie 1 si l'element geometrique
est structure, 0 sinon
Contraintes:
Definition at line 326 of file Elem_geom.h.
{
  return valeur().est_structure();
}
References Elem_geom_base::est_structure(), and Deriv_Elem_geom_base::valeur().
face_sommet()
void Elem_geom::face_sommet (int i, int j) const inline
Appel a l'objet sous-jacent
Renvoie le j-ieme sommet de la i-ieme face de
l'element.
Definition at line 107 of file Elem_geom.h.
{
  valeur().face_sommet(i, j);
}
References Elem_geom_base::face_sommet(), and Deriv_Elem_geom_base::valeur().
get_info()
const Type_info * Elem_geom::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Elem_geom_base.
Definition at line 20 of file Elem_geom.cpp.
info()
const Type_info * Elem_geom::info () static
Definition at line 20 of file Elem_geom.cpp.
nb_faces()
int Elem_geom::nb_faces (int i = 0) const inline
Appel a l'objet sous-jacent
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
Returns
int
Signification: le nombre de face du type specifie
dans l'element geometrique courant
Contraintes:
Definition at line 259 of file Elem_geom.h.
{
  assert(i<nb_type_face());
  return valeur().nb_faces(i);
}
References Elem_geom_base::nb_faces(), nb_type_face(), and Deriv_Elem_geom_base::valeur().
Referenced by Zone::nb_faces_elem(), and Zone_Cl_VEF::remplir_type_elem_Cl().
nb_som()
int Elem_geom::nb_som () const inline
Appel a l'objet sous-jacent
Renvoie le nombre de sommets de l'element.
Returns
int
Signification: le nombre de sommets de l'element
Contraintes:
Definition at line 281 of file Elem_geom.h.
{
  return valeur().nb_som();
}
References Elem_geom_base::nb_som(), and Deriv_Elem_geom_base::valeur().
Referenced by Zone::nb_som_elem().
nb_som_face()
int Elem_geom::nb_som_face (int i = 0) const inline
Appel a l'objet sous-jacent
Renvoie le nombre de sommets des faces
du type specifie.
Returns
int
Signification: le nombre de sommets des faces du type specifie
Contraintes:
Definition at line 302 of file Elem_geom.h.
{
  assert(i<nb_type_face());
  return valeur().nb_som_face(i);
}
References Elem_geom_base::nb_som_face(), nb_type_face(), and Deriv_Elem_geom_base::valeur().
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Zone_VEF_PreP1b::construire_renum_arete_perio(), and Scatter::corriger_espace_distant_elements_perio().
nb_type_face()
int Elem_geom::nb_type_face () const inline
Appel a l'objet sous-jacent
Renvoie le nombre de type de face
de l'element geometrique.
Definition at line 479 of file Elem_geom.h.
{
  return valeur().nb_type_face();
}
References Elem_geom_base::nb_type_face(), and Deriv_Elem_geom_base::valeur().
Referenced by nb_faces(), nb_som_face(), and type_face().
nom_lml()
const Nom & Elem_geom::nom_lml () const inline
Returns
Nom&
Signification: le nom de l'element geometrique
au format LML
Contraintes: reference constante
Definition at line 349 of file Elem_geom.h.
{
  return valeur().nom_lml();
}
References Elem_geom_base::nom_lml(), and Deriv_Elem_geom_base::valeur().
Referenced by Format_Post_Lml::ecrire_domaine_lml().
printOn()
Sortie & Elem_geom::printOn (Sortie & s) const override protected virtual
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Elem_geom_base.
Definition at line 36 of file Elem_geom.cpp.
{
  return DERIV(Elem_geom_base)::printOn(s);
}
References DERIV, and printOn().
Referenced by printOn().
readOn()
Entree & Elem_geom::readOn (Entree & s) override protected virtual
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Elem_geom_base.
Definition at line 56 of file Elem_geom.cpp.
{
  return DERIV(Elem_geom_base)::readOn(s);
}
References DERIV, and readOn().
Referenced by readOn().
reordonner()
void Elem_geom::reordonner () inline
Appel a l'objet sous-jacent
Reordonne les sommets du maillage.
Definition at line 457 of file Elem_geom.h.
{
  valeur().reordonner();
}
References Elem_geom_base::reordonner(), and Deriv_Elem_geom_base::valeur().
Referenced by Lire_Tgrid::interpreter_(), and Zone::reordonner().
self_cast() [1/2]
const Elem_geom & Elem_geom::self_cast (const Objet_U & r) static
Definition at line 20 of file Elem_geom.cpp.
self_cast() [2/2]
Elem_geom & Elem_geom::self_cast (Objet_U & r) static
Definition at line 20 of file Elem_geom.cpp.
taille_memoire()
unsigned Elem_geom::taille_memoire () const override virtual
Reimplemented from Deriv_Elem_geom_base.
Definition at line 20 of file Elem_geom.cpp.
type_face()
Type_Face Elem_geom::type_face (int i = 0) const inline
Appel a l'objet sous-jacent
Renvoie le i-eme type de face de l'element
geometrique.
Returns
Type_Face
Signification: un objet Type_Face correspondant au type
demande
Contraintes:
Definition at line 436 of file Elem_geom.h.
{
  assert(i<nb_type_face());
  return valeur().type_face(i);
}
References nb_type_face(), Elem_geom_base::type_face(), and Deriv_Elem_geom_base::valeur().
Referenced by DomaineCutter::construire_faces_joints_ssdom(), Zone_VF::discretiser(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), and Pave::lire_front().
Member Data Documentation
info_obj
const Type_info Elem_geom::info_obj static
Definition at line 41 of file Elem_geom.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Elem_geom.h
src/Kernel/Geometrie/Elem_geom.cpp