TRUST: Champ_front_instationnaire_base Class Reference
Champ_front_instationnaire_base Class Reference
classe Champ_front_base
Classe de base pour les Champs aux frontieres instationnaires,
mais uniformes en espace.
Les aspects temporels sont equivalents a ceux de
Ch_front_var_instationnaire.
En revanche, le tableau de valeurs est dimensionne a une seule
valeur et n'a pas d'espace virtuel.
#include <Champ_front_instationnaire_base.h>
Public Member Functions
Champ_front_instationnaire_base ()
~Champ_front_instationnaire_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
DoubleTab & Gpoint ()
const DoubleTab & Gpoint () const
void Gpoint (double t1, double t2)
virtual DoubleTab & valeurs_au_temps (double temps)
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
virtual const DoubleTab & valeurs_au_temps (double temps) const
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
virtual int avancer (double temps)
Avance jusqu'au temps desire.
Sinon, sort en erreur.
virtual int reculer (double temps)
Recule jusqu'au temps desire.
Sinon, sort en erreur.
virtual void valeurs_face (int, DoubleVect &) const
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Champ_front_instationnaire_base & self_cast (Objet_U &)
static const
Champ_front_instationnaire_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le temps du champ instationnaire sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit le temps du champ instationnaire sur un flot d'entree.
Protected Attributes
DoubleTab Gpoint_
Derivee en temps des valeurs conditons limites.
Detailed Description
classe Champ_front_base
Classe de base pour les Champs aux frontieres instationnaires,
mais uniformes en espace.
Les aspects temporels sont equivalents a ceux de
Ch_front_var_instationnaire.
En revanche, le tableau de valeurs est dimensionne a une seule
valeur et n'a pas d'espace virtuel.
Definition at line 44 of file Champ_front_instationnaire_base.h.
Constructor & Destructor Documentation
Champ_front_instationnaire_base::Champ_front_instationnaire_base ()
Definition at line 25 of file Champ_front_instationnaire_base.cpp.
Champ_front_instationnaire_base::~Champ_front_instationnaire_base ()
Definition at line 25 of file Champ_front_instationnaire_base.cpp.
Member Function Documentation
int Champ_front_instationnaire_base::avancer (double temps) [virtual]
Avance jusqu'au temps desire.
Sinon, sort en erreur.
Reimplemented from Champ_front_base.
Definition at line 142 of file Champ_front_instationnaire_base.cpp.
References Cerr, est_egal(), Process::exit(), finl, Champ_front_base::les_valeurs, and print().
{
// S"agit-il bien d'une avance en temps ?
  assert(temps>les_valeurs->temps());
  for(int i=1; i<les_valeurs->nb_cases(); i++)
    {
      if(est_egal(les_valeurs[i].temps(),temps))
        {
          les_valeurs=les_valeurs[i];
          return 1;
        }
    }
  Cerr << "In Champ_front_instationnaire_base::avancer(double), "
       << "time " << temps << " not found." << finl;
  print(les_valeurs);
  exit();
  return 0;
}
virtual int Champ_front_instationnaire_base::duplique () const [pure virtual]
Implements Champ_front_base.
Implemented in Ch_front_input_uniforme, and Champ_front_Tabule.
void Champ_front_instationnaire_base::fixer_nb_valeurs_temporelles (int nb_cases) [virtual]
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
Reimplemented from Champ_front_base.
Definition at line 89 of file Champ_front_instationnaire_base.cpp.
References Champ_front_base::les_valeurs.
{
  les_valeurs->fixer_nb_cases(nb_cases);
}
const Type_info * Champ_front_instationnaire_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_base.
Reimplemented in Ch_front_input_uniforme, and Champ_front_Tabule.
Definition at line 25 of file Champ_front_instationnaire_base.cpp.
DoubleTab & Champ_front_instationnaire_base::Gpoint () [inline]
Definition at line 66 of file Champ_front_instationnaire_base.h.
References Gpoint_.
Referenced by Zone_Cl_dis_base::Gpoint(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_EF::modifier_secmem(), and Ch_front_input_uniforme::setValue().
{
  return Gpoint_;
}
const DoubleTab & Champ_front_instationnaire_base::Gpoint () const [inline]
Definition at line 71 of file Champ_front_instationnaire_base.h.
References Gpoint_.
{
  return Gpoint_;
}
void Champ_front_instationnaire_base::Gpoint (double t1, double t2)
Definition at line 190 of file Champ_front_instationnaire_base.cpp.
References DoubleTab::dimension(), Gpoint_, DoubleTab::resize(), and valeurs_au_temps().
{
  DoubleTab& v1=valeurs_au_temps(t1);
  DoubleTab& v2=valeurs_au_temps(t2);
  int dim=v1.dimension(1);
  Gpoint_.resize(dim);
  for (int i=0; i<dim; i++)
    Gpoint_(i) = (v2(0,i)-v1(0,i)) / (t2-t1);
}
const Type_info * Champ_front_instationnaire_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_base.
Reimplemented in Ch_front_input_uniforme, and Champ_front_Tabule.
Definition at line 25 of file Champ_front_instationnaire_base.cpp.
int Champ_front_instationnaire_base::initialiser (double temps, const Champ_Inc_base & inco) [virtual]
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Returns:
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
< pour dimensionner
Reimplemented from Champ_front_base.
Reimplemented in Ch_front_input_uniforme, and Champ_front_Tabule.
Definition at line 67 of file Champ_front_instationnaire_base.cpp.
References Champ_front_base::changer_temps_futur(), Gpoint_, Champ_front_base::initialiser(), Champ_front_base::les_valeurs, Field_base::nb_comp(), Champ_front_base::temps_defaut, and Champ_front_base::valeurs().
Referenced by Champ_front_Tabule::initialiser(), and Ch_front_input_uniforme::initialiser().
{
  if (!Champ_front_base::initialiser(temps,inco))
    return 0;
  temps_defaut=temps;
  changer_temps_futur(temps,0);
  for(int i=0; i<les_valeurs->nb_cases(); i++)
    {
      les_valeurs[i].valeurs().resize(1,nb_comp());
    }
  Gpoint_=valeurs(); //!< pour dimensionner
  Gpoint_=0.;
  return 1;
}
Sortie & Champ_front_instationnaire_base::printOn (Sortie & os) const [protected, virtual]
Ecrit le temps du champ instationnaire sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_base.
Reimplemented in Ch_front_input_uniforme, and Champ_front_Tabule.
Definition at line 62 of file Champ_front_instationnaire_base.cpp.
{
  return os;
}
Entree & Champ_front_instationnaire_base::readOn (Entree & is) [protected, virtual]
Lit le temps du champ instationnaire sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_base.
Reimplemented in Ch_front_input_uniforme, and Champ_front_Tabule.
Definition at line 42 of file Champ_front_instationnaire_base.cpp.
{
  return is;
}
int Champ_front_instationnaire_base::reculer (double temps) [virtual]
Recule jusqu'au temps desire.
Sinon, sort en erreur.
Reimplemented from Champ_front_base.
Definition at line 166 of file Champ_front_instationnaire_base.cpp.
References Cerr, est_egal(), Process::exit(), finl, Champ_front_base::les_valeurs, and print().
{
// S"agit-il bien d'une avance en temps ?
  assert(temps<les_valeurs->temps());
  for(int i=les_valeurs->nb_cases()-1; i>=1; i++)
    {
      if(est_egal(les_valeurs[i].temps(),temps))
        {
          les_valeurs=les_valeurs[i];
          return 1;
        }
    }
  Cerr << "In Champ_front_instationnaire_base::reculer(double), "
       << "time " << temps << " not found." << finl;
  print(les_valeurs);
  exit();
  return 0;
}
Champ_front_instationnaire_base & Champ_front_instationnaire_base::self_cast (Objet_U & r) [static]
Reimplemented from Champ_front_base.
Reimplemented in Ch_front_input_uniforme, and Champ_front_Tabule.
Definition at line 25 of file Champ_front_instationnaire_base.cpp.
const Champ_front_instationnaire_base & Champ_front_instationnaire_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_front_base.
Reimplemented in Ch_front_input_uniforme, and Champ_front_Tabule.
Definition at line 25 of file Champ_front_instationnaire_base.cpp.
DoubleTab & Champ_front_instationnaire_base::valeurs_au_temps (double temps) [virtual]
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
< For compilers
Implements Champ_front_base.
Definition at line 104 of file Champ_front_instationnaire_base.cpp.
References Cerr, est_egal(), Process::exit(), finl, Champ_front_base::les_valeurs, print(), and Champ_front_base::valeurs().
Referenced by Gpoint(), and Champ_front_Tabule::mettre_a_jour().
{
  for(int i=0; i<les_valeurs->nb_cases(); i++)
    {
      if(est_egal(les_valeurs[i].temps(),temps))
        return les_valeurs[i].valeurs();
    }
  Cerr << "In Champ_front_instationnaire_base::valeurs(double), "
       << "time " << temps << " not found." << finl;
  print(les_valeurs);
  exit();
  return valeurs(); //!< For compilers
}
const DoubleTab & Champ_front_instationnaire_base::valeurs_au_temps (double temps) const [virtual]
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
< For compilers
Implements Champ_front_base.
Definition at line 123 of file Champ_front_instationnaire_base.cpp.
References Cerr, est_egal(), Process::exit(), finl, Champ_front_base::les_valeurs, print(), and Champ_front_base::valeurs().
{
  for(int i=0; i<les_valeurs->nb_cases(); i++)
    {
      if(est_egal(les_valeurs[i].temps(),temps))
        return les_valeurs[i].valeurs();
    }
  Cerr << "In Champ_front_instationnaire_base::valeurs(double), "
       << "time " << temps << " not found." << finl;
  print(les_valeurs);
  exit();
  return valeurs(); //!< For compilers
}
void Champ_front_instationnaire_base::valeurs_face (int num_face, DoubleVect & val) const [virtual]
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
Reimplemented from Champ_front_base.
Definition at line 201 of file Champ_front_instationnaire_base.cpp.
References Field_base::nb_compo_, DoubleVect::resize(), and Champ_front_base::valeurs().
{
  var.resize(nb_compo_);
  int i;
  for (i=0 ; i<nb_compo_ ; i++)
    var(i) = valeurs()(0,i);
}
Member Data Documentation
DoubleTab Champ_front_instationnaire_base::Gpoint_ [protected]
Derivee en temps des valeurs conditons limites.
Definition at line 62 of file Champ_front_instationnaire_base.h.
Referenced by Gpoint(), and initialiser().
const Type_info Champ_front_instationnaire_base::info_obj [static]
Reimplemented from Champ_front_base.
Reimplemented in Ch_front_input_uniforme, and Champ_front_Tabule.
Definition at line 47 of file Champ_front_instationnaire_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_front_instationnaire_base.h
src/Kernel/Framework/Champ_front_instationnaire_base.cpp