TRUST: Boundary_field_inward Class Reference
Boundary_field_inward Class Reference
class Boundary_field_inward
#include <Boundary_field_inward.h>
Public Member Functions
Boundary_field_inward ()
~Boundary_field_inward ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int initialiser (double tps, const Champ_Inc_base &inco)
Initialize normal inward field given on boundaries.
void mettre_a_jour (double tps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Boundary_field_inward & self_cast (Objet_U &)
static const
Boundary_field_inward & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le nom du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Detailed Description
class Boundary_field_inward
Definition at line 32 of file Boundary_field_inward.h.
Constructor & Destructor Documentation
Boundary_field_inward::Boundary_field_inward ()
Definition at line 30 of file Boundary_field_inward.cpp.
Boundary_field_inward::~Boundary_field_inward ()
Definition at line 30 of file Boundary_field_inward.cpp.
Member Function Documentation
Objet_U * Boundary_field_inward::cree_instance () [static]
Reimplemented from Champ_front_normal.
Reimplemented in Champ_front_normal_VEF.
Definition at line 30 of file Boundary_field_inward.cpp.
int Boundary_field_inward::duplique () const [virtual]
Reimplemented from Champ_front_normal.
Reimplemented in Champ_front_normal_VEF.
Definition at line 30 of file Boundary_field_inward.cpp.
const Type_info * Boundary_field_inward::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_normal.
Reimplemented in Champ_front_normal_VEF.
Definition at line 30 of file Boundary_field_inward.cpp.
const Type_info * Boundary_field_inward::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_normal.
Reimplemented in Champ_front_normal_VEF.
Definition at line 30 of file Boundary_field_inward.cpp.
int Boundary_field_inward::initialiser (double tps, const Champ_Inc_base & inco) [virtual]
Initialize normal inward field given on boundaries.
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 55 of file Boundary_field_inward.cpp.
References Ch_front_var_instationnaire_dep::initialiser(), and mettre_a_jour().
{
  if( !Champ_front_normal::initialiser(tps,inco) )
    return 0;
  mettre_a_jour(tps);
  return 1;
}
void Boundary_field_inward::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
Reimplemented from Champ_front_base.
Definition at line 63 of file Boundary_field_inward.cpp.
References Objet_U::dimension, Parser_U::eval(), Champ_front_base::frontiere_dis(), Champ_front_base::les_valeurs, Front_VF::nb_faces(), Zone_VF::normalized_boundaries_outward_vector(), Front_VF::num_premiere_face(), ref_cast, Parser_U::setVar(), Champ_front_normal::vit_norm, and Champ_front_base::zone_dis().
Referenced by initialiser().
{
  const Zone_VF& zone_VF = ref_cast(Zone_VF,zone_dis());
  const Front_VF& le_bord= ref_cast(Front_VF,frontiere_dis());
  int first=le_bord.num_premiere_face();
  int nb_cases=les_valeurs->nb_cases();
  DoubleTab tab_normal_vector(le_bord.nb_faces(),dimension);
// Evaluation de vit_norm:
  vit_norm.setVar("t",tps);
  double value = vit_norm.eval();
  for(int i=0; i<le_bord.nb_faces(); i++)
    {
      int signe = -1;//we want the opposite of the normal vector
      int global_boundary_face_number=i+first;
// outward vector associated to the fac global_boundary_face_number
      DoubleTab normal_vector = zone_VF.normalized_boundaries_outward_vector(global_boundary_face_number,signe);
      for (int k=0; k<dimension; k++)
        {
          tab_normal_vector(i,k) = normal_vector(k);
        }
// Fill all moments
      for (int t=0; t<nb_cases; t++)
        {
          DoubleTab& tab=les_valeurs[t].valeurs();
          for(int j=0; j<dimension; j++)
            {
              tab(i,j)=tab_normal_vector(i,j);
              tab(i,j)*=value;
            }
        }
    }
}
Sortie & Boundary_field_inward::printOn (Sortie & s) const [protected, virtual]
Imprime le nom du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_normal.
Reimplemented in Champ_front_normal_VEF.
Definition at line 33 of file Boundary_field_inward.cpp.
{
  return Champ_front_normal::printOn(os);
}
Entree & Boundary_field_inward::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_normal.
Reimplemented in Champ_front_normal_VEF.
Definition at line 39 of file Boundary_field_inward.cpp.
{
  return Champ_front_normal::readOn(is);
}
Boundary_field_inward & Boundary_field_inward::self_cast (Objet_U & r) [static]
Reimplemented from Champ_front_normal.
Reimplemented in Champ_front_normal_VEF.
Definition at line 30 of file Boundary_field_inward.cpp.
const Boundary_field_inward & Boundary_field_inward::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_front_normal.
Reimplemented in Champ_front_normal_VEF.
Definition at line 30 of file Boundary_field_inward.cpp.
unsigned Boundary_field_inward::taille_memoire () const [virtual]
Reimplemented from Champ_front_normal.
Reimplemented in Champ_front_normal_VEF.
Definition at line 30 of file Boundary_field_inward.cpp.
Member Data Documentation
const Type_info Boundary_field_inward::info_obj [static]
Reimplemented from Champ_front_normal.
Reimplemented in Champ_front_normal_VEF.
Definition at line 34 of file Boundary_field_inward.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Boundary_field_inward.h
src/Kernel/Champs/Boundary_field_inward.cpp