TRUST: Polyedre Class Reference
Polyedre Class Reference
Classe Polyedre
Cette represente l'element geometrique Polyedre.
Un polyedre est un element defini par ses faces
de type Faces::polygone_3D.
#include <Polyedre.h>
Public Member Functions
Polyedre ()
~Polyedre ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void calculer_un_centre_gravite (const int elem, DoubleVect &xp) const override
void calculer_centres_gravite (DoubleTab &xp) const override
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
int face_sommet (int i, int j) const override
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
int nb_som () const override
Renvoie le nombre de sommets d'un Polyedre.
int nb_faces (int=0) const override
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
Un Polyedre a 1 type de faces: polygon_3D.
int nb_som_face (int=0) const override
Renvoie le nombre maximum de sommets des faces
du type specifie.
int est_structure () const override
const Nom & nom_lml () const override
Renvoie le nom LML d'un polyedre = "POLYEDRE_"+nb_som_max.
int contient (const ArrOfDouble &, int) const override
NE FAIT RIEN: A CODER, renvoie toujours 0.
Renvoie 1 si l'element "element" de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
int contient (const ArrOfInt &, int) const override
NE FAIT RIEN: A CODER, renvoie toujours 0
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Type_Face type_face (int=0) const override
Renvoie le i-ieme type de face.
Un polyedre a 2 types de face: quadrangle et triangle.
void reordonner () override
Reordonne les sommets du Polyedre.
NE FAIT RIEN: A CODER.
void calculer_volumes (DoubleVect &) const override
NE FAIT RIEN: A CODER
Calcule les volumes des elements de la zone associee.
int nb_type_face () const override
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const override
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
int get_tab_faces_sommets_locaux (IntTab &faces_som_local, int elem) const override
void affecte_connectivite_numero_global (const ArrOfInt &Nodes, const ArrOfInt &FacesIndex, const ArrOfInt &PolyhedronIndex, IntTab &les_elems)
int get_nb_som_elem_max () const
int get_nb_face_elem_max () const
int get_nb_som_face_max () const
int get_somme_nb_faces_elem () const override
const ArrOfInt & getFacesIndex () const override
const ArrOfInt & getPolyhedronIndex () const
const ArrOfInt & getElemIndex () const override
void remplir_Nodes_glob (ArrOfInt &Nodes_glob, const IntTab &les_elems) const
void ajouter_elements (const Elem_geom_base &new_elem, const IntTab &new_elems, IntTab &les_elems)
void build_reduced (Elem_geom &type_elem, const ArrOfInt &elems_sous_part) const override
void compute_virtual_index () override
Public Member Functions inherited from Poly_geom_base
Poly_geom_base ()
~Poly_geom_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const override=0
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
virtual int get_tab_faces_sommets_locaux (IntTab &faces_som_local, int elem) const =0
virtual const ArrOfInt & getFacesIndex () const =0
virtual const ArrOfInt & getElemIndex () const =0
virtual int get_somme_nb_faces_elem () const =0
virtual void calculer_un_centre_gravite (const int elem, DoubleVect &xp) const =0
virtual void build_reduced (Elem_geom &type_elem, const ArrOfInt &elems_sous_part) const =0
virtual void compute_virtual_index ()=0
Public Member Functions inherited from Elem_geom_base
Elem_geom_base ()
~Elem_geom_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void creer_faces_elem (Faces &, int, Type_Face) const
Cree les faces de l'element geometrique specifie de la zone
en precisant le type de face a creer.
void creer_faces_elem (Faces &, int) const
Cree les faces de l'element de la zone specifie.
virtual int face_sommet (int i, int j) const =0
void associer_zone (const Zone &)
Associe l'element geometrique a sa zone.
virtual int nb_som () const =0
virtual int nb_faces (int=0) const =0
virtual int nb_som_face (int=0) const =0
virtual int est_structure () const =0
virtual const Nom & nom_lml () const =0
virtual int contient (const ArrOfDouble &, int) const =0
virtual int contient (const ArrOfInt &, int) const =0
virtual int nb_type_face () const
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
virtual int num_face (int face, Type_Face &type) const
Renvoie le parametre face si le type
de face specifie est le meme que celui de l'element
geometrique.
virtual Type_Face type_face (int=0) const =0
virtual void calculer_centres_gravite (DoubleTab &) const
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
virtual void reordonner ()
NE FAIT RIEN:
A surcharger dans les classes derivees.
virtual void calculer_volumes (DoubleVect &) const =0
virtual void calculer_normales (const IntTab &faces_sommets, DoubleTab &face_normales) const
Sort en erreur. Cette methode n'est pas virtuelle pure
pour des raisons de commodite.
virtual int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
virtual void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const
idem que Elem_geom_base::get_tab_faces_sommets_locaux mais pour les aretes:
aretes_som_local.dimension(0) = nombre d'aretes sur l'element de reference
aretes_som_local.dimension(1) = 2 (nombre de sommets par arete)
aretes_som_local(i,j) = numero d'un sommet de l'element (0 <= n < nb_sommets_par_element)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Polyedre & self_cast (Objet_U &)
static const Polyedre & self_cast (const Objet_U &)
Static Public Member Functions inherited from Poly_geom_base
static const Type_info * info ()
static Poly_geom_base & self_cast (Objet_U &)
static const Poly_geom_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Elem_geom_base
static const Type_info * info ()
static Elem_geom_base & self_cast (Objet_U &)
static const Elem_geom_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Poly_geom_base
static const Type_info info_obj
Static Public Attributes inherited from Elem_geom_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
ArrOfInt Nodes_
ArrOfInt FacesIndex_
ArrOfInt PolyhedronIndex_
PolyhedronIndex_[ele] numero premiere face de l'ele FacesIndex_[f] numero premier indice de sommet de la face f dans Nodes Nodes_[s] numero local du sommet s d'une face, elem(ele,s) -> numero global.
int nb_som_elem_max_
int nb_face_elem_max_
int nb_som_face_max_
Additional Inherited Members
Protected Attributes inherited from Elem_geom_base
Ref_Zone ma_zone
Detailed Description
Classe Polyedre
Cette represente l'element geometrique Polyedre.
Un polyedre est un element defini par ses faces
de type Faces::polygone_3D.
Definition at line 39 of file Polyedre.h.
Constructor & Destructor Documentation
Polyedre()
Polyedre::Polyedre ()
Definition at line 26 of file Polyedre.cpp.
                  : FacesIndex_(1),PolyhedronIndex_(1)
{
  PolyhedronIndex_[0]=0;
  FacesIndex_[0]=0;
  nb_som_elem_max_=-1;
  nb_face_elem_max_=0;
  nb_som_face_max_=0;
}
References FacesIndex_, nb_face_elem_max_, nb_som_elem_max_, nb_som_face_max_, and PolyhedronIndex_.
~Polyedre()
Polyedre::~Polyedre ()
Definition at line 24 of file Polyedre.cpp.
Member Function Documentation
affecte_connectivite_numero_global()
void Polyedre::affecte_connectivite_numero_global (const ArrOfInt & Nodes, const ArrOfInt & FacesIndex, const ArrOfInt & PolyhedronIndex, IntTab & les_elems)
Definition at line 458 of file Polyedre.cpp.
{
  nb_som_elem_max_=0;
// detremination de nbsom_max
  IntList prov;
  nb_face_elem_max_=0;
  nb_som_face_max_=0;
  int nelem=PolyhedronIndex.size_array()-1;
  for (int ele=0; ele<nelem; ele++)
    {
      prov.vide();
      int nbf=PolyhedronIndex[ele+1]-PolyhedronIndex[ele];
      if (nbf>nb_face_elem_max_) nb_face_elem_max_=nbf;
      for (int f=PolyhedronIndex[ele]; f<PolyhedronIndex[ele+1]; f++)
        {
// Cerr<<" ici "<<ele << " " <<f <<" "<<FacesIndex(f+1)-FacesIndex(f)<<finl;
          int nbs=FacesIndex[f+1]-FacesIndex[f];
          if (nbs>nb_som_face_max_) nb_som_face_max_=nbs;
          for (int s=FacesIndex[f]; s<FacesIndex[f+1]; s++)
            {
              prov.add_if_not(Nodes[s]);
            }
        }
      int nbsom=prov.size();
      if (nbsom>nb_som_elem_max_) nb_som_elem_max_=nbsom;
    }
  Cerr<<" Polyhedron information nb_som_elem_max "<< nb_som_elem_max_<<" nb_som_face_max "<<nb_som_face_max_<<" nb_face_elem_max "<<nb_face_elem_max_<<finl;
  les_elems.resize(nelem,nb_som_elem_max_);
  les_elems=-1;
// on refait un tour pour determiiner les elems
  for (int ele=0; ele<nelem; ele++)
    {
      prov.vide();
      for (int f=PolyhedronIndex[ele]; f<PolyhedronIndex[ele+1]; f++)
        {
          for (int s=FacesIndex[f]; s<FacesIndex[f+1]; s++)
            {
              prov.add_if_not(Nodes[s]);
            }
        }
      int nbsom=prov.size();
// on trie prov dans l'ordre croissant
// pas strictement necessaire mais permet de garder le meme tableau elem meme si on a effectue des permutation pour les faces
      int perm=1;
      while (perm)
        {
          perm=0;
          for (int i=0; i<nbsom-1; i++)
            if (prov[i]>prov[i+1])
              {
                perm=1;
                int sa=prov[i];
                prov[i]=prov[i+1];
                prov[i+1]=sa;
              }
        }
      for (int s=0; s<nbsom; s++) les_elems(ele,s)=prov[s];
    }
  FacesIndex_=FacesIndex;
  PolyhedronIndex_=PolyhedronIndex;
// determination de Nodes_...
  Nodes_=Nodes;
  {
    Nodes_=-2;
    for (int ele=0; ele<nelem; ele++)
      {
        for (int f=PolyhedronIndex[ele]; f<PolyhedronIndex[ele+1]; f++)
          {
            for (int s=FacesIndex[f]; s<FacesIndex[f+1]; s++)
              {
                int somm_glob=Nodes[s];
                for (int sl=0; sl<nb_som_elem_max_; sl++)
                  if (les_elems(ele,sl)==somm_glob)
                    {
                      Nodes_[s]=sl;
                      break;
                    }
              }
          }
      }
  }
  assert(min_array(Nodes_)>-1);
}
References TRUSTList< _TYPE_ >::add_if_not(), Cerr, FacesIndex_, finl, min_array(), nb_face_elem_max_, nb_som_elem_max_, nb_som_face_max_, Nodes_, PolyhedronIndex_, TRUSTTab< _TYPE_ >::resize(), TRUSTList< _TYPE_ >::size(), TRUSTArray< _TYPE_ >::size_array(), and TRUSTList< _TYPE_ >::vide().
Referenced by Polyedriser::polyedriser().
ajouter_elements()
void Polyedre::ajouter_elements (const Elem_geom_base & new_elem, const IntTab & new_elems, IntTab & les_elems)
Definition at line 578 of file Polyedre.cpp.
{
// On a joute les new_elems a les_elems
  int nb_old_elem=les_elems.dimension(0);
  int nb_new_elem=new_elems.dimension(0);
  int nb_som_old_elem=les_elems.dimension(1);
  int nb_som_new_elem=new_elems.dimension(1);
  nb_som_elem_max_ = std::max(nb_som_old_elem,nb_som_new_elem);
  les_elems.set_smart_resize(1);
  les_elems.resize(nb_old_elem+nb_new_elem,nb_som_elem_max_, ArrOfInt::COPY_NOINIT);
  for (int el=0; el<nb_new_elem; el++)
    {
      for (int s=0; s<nb_som_new_elem; s++)
        les_elems(nb_old_elem+el,s)=new_elems(el,s);
      for (int s=nb_som_new_elem; s<nb_som_old_elem; s++)
        les_elems(nb_old_elem+el,s)=-1;
    }
// on ajoute les faces pour cela on recupere le tableau de creation des faces
  IntTab faces_som_local;
  type_elem.get_tab_faces_sommets_locaux(faces_som_local);
  int nb_face_new_elem=faces_som_local.dimension(0);
  int nb_som_face_new_elem=faces_som_local.dimension(1);
  nb_face_elem_max_=std::max(nb_face_elem_max_,nb_face_new_elem);
  nb_som_face_max_=std::max(nb_som_face_max_,nb_som_face_new_elem);
  PolyhedronIndex_.set_smart_resize(1);
  PolyhedronIndex_.resize_array(1+nb_old_elem+nb_new_elem);
  FacesIndex_.set_smart_resize(1);
  int old_faces_index= FacesIndex_.size_array();
  FacesIndex_.resize_array(old_faces_index+nb_new_elem*nb_face_new_elem);
  Nodes_.set_smart_resize(1);
  int old_nodes_index= Nodes_.size_array();
  Nodes_.resize_array(old_nodes_index+nb_new_elem*nb_face_new_elem*nb_som_face_new_elem);
  int new_s=0;
  for (int el=0; el<nb_new_elem; el++)
    {
      PolyhedronIndex_[nb_old_elem+el+1]=PolyhedronIndex_[nb_old_elem+el]+nb_face_new_elem;
      for (int f=0; f<nb_face_new_elem; f++)
        {
          int nb_som_face_this_elem=0;
          for (int s=0; s<nb_som_face_new_elem; s++)
            if (faces_som_local(f,s)!=-1)
              {
                Nodes_[old_nodes_index+new_s++]=faces_som_local(f,s);
                nb_som_face_this_elem++;
              }
          if (nb_som_face_this_elem==4)
            {
// on inverse 3 et 4 en cas de quadrangle
              int last=old_nodes_index+new_s-1;
              swap(Nodes_[last],Nodes_[last-1]);
            }
          FacesIndex_[old_faces_index+(el*nb_face_new_elem)+f]=
            FacesIndex_[old_faces_index+(el*nb_face_new_elem)+f-1]+nb_som_face_this_elem;
        }
    }
  Nodes_.resize_array(old_nodes_index+new_s);
}
References Array_base::COPY_NOINIT, TRUSTTab< _TYPE_ >::dimension(), FacesIndex_, nb_face_elem_max_, nb_som_elem_max_, nb_som_face_max_, Nodes_, PolyhedronIndex_, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), swap(), and type_elem().
build_reduced()
void Polyedre::build_reduced (Elem_geom & type_elem, const ArrOfInt & elems_sous_part) const override virtual
Implements Poly_geom_base.
Definition at line 642 of file Polyedre.cpp.
{
  type_elem.typer("Polyedre");
  Polyedre& reduced = ref_cast(Polyedre, type_elem.valeur());
  reduced.nb_som_elem_max_  = nb_som_elem_max_;
  reduced.nb_face_elem_max_ = nb_face_elem_max_;
  reduced.nb_som_face_max_  = nb_som_face_max_;
  ArrOfInt& Pi = reduced.PolyhedronIndex_, &Fi = reduced.FacesIndex_, &N = reduced.Nodes_;
  Pi.set_smart_resize(1), Fi.set_smart_resize(1), N.set_smart_resize(1);
  for (int i = 0; i < elems_sous_part.size_array(); i++)
    {
      int e = elems_sous_part[i];
      for (int f = PolyhedronIndex_[e]; f < PolyhedronIndex_[e + 1]; f++)
        {
          for (int s = FacesIndex_[f]; s < FacesIndex_[f + 1]; s++) N.append_array(Nodes_[s]);
          Fi.append_array(N.size_array());
        }
      Pi.append_array(Fi.size_array() - 1);
    }
}
References TRUSTArray< _TYPE_ >::append_array(), FacesIndex_, nb_face_elem_max_, nb_som_elem_max_, nb_som_face_max_, Nodes_, PolyhedronIndex_, ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), and type_elem().
calculer_centres_gravite()
void Polyedre::calculer_centres_gravite (DoubleTab & xp) const override virtual
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
Reimplemented from Elem_geom_base.
Definition at line 87 of file Polyedre.cpp.
{
  const Zone& zone=ma_zone.valeur();
  const IntTab& elem=zone.les_elems();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  int nb_elem;
  if(xp.dimension(0)==0)
    {
      nb_elem = ma_zone->nb_elem_tot();
      xp.resize(nb_elem,dimension);
    }
  else
    nb_elem=xp.dimension(0);
  for (int num_poly=0; num_poly<nb_elem; num_poly++)
    {
      double volume=0;
      Vecteur3 xg(0,0,0);
      int nb_som_max=elem.dimension(1);
      int nb_som_reel;
      for (nb_som_reel=0; nb_som_reel<nb_som_max; nb_som_reel++)
        {
          int n=elem(num_poly,nb_som_reel);
          if (n<0)
            break;
          Vecteur3 S(coord(n,0),coord(n,1),coord(n,2));
          xg+=S;
        }
      xg*=1./nb_som_reel;
      Vecteur3 moinsS0(xg);
      moinsS0*=-1;
      Vecteur3 vraixg(0,0,0);
      for (int f=PolyhedronIndex_[num_poly]; f<PolyhedronIndex_[num_poly+1]; f++)
        {
          int somm_loc3=Nodes_[FacesIndex_[f+1]-1];
          int n3=elem(num_poly,somm_loc3);
          Vecteur3 S3(coord(n3,0),coord(n3,1),coord(n3,2));
          Vecteur3 S3sa(S3);
          S3+=  moinsS0;
          for (int s=FacesIndex_[f]; s<FacesIndex_[f+1]-2; s++)
            {
              int somm_loc1=Nodes_[s];
              int n1=elem(num_poly,somm_loc1);
              int somm_loc2=Nodes_[s+1];
              int n2=elem(num_poly,somm_loc2);
              Vecteur3 S1(coord(n1,0),coord(n1,1),coord(n1,2));
              Vecteur3 S2(coord(n2,0),coord(n2,1),coord(n2,2));
              Vecteur3 xgl(xg);
              xgl+=S3sa;
              xgl+=S1;
              xgl+=S2;
              xgl*=0.25;
              S1+=  moinsS0;
              S2+=  moinsS0;
              double vol_l= std::fabs(
                              S1[0] * ( S2[1] * S3[2] - S3[1] * S2[2] )
                              + S2[0] * ( S3[1] * S1[2] - S1[1] * S3[2] )
                              + S3[0] * ( S1[1] * S2[2] - S2[1] * S1[2] ) );
              volume+=vol_l;
              xgl*=vol_l;
              vraixg+=xgl;
            }
        }
      vraixg*=1./volume;
      xp(num_poly,0)=vraixg[0];
      xp(num_poly,1)=vraixg[1];
      xp(num_poly,2)=vraixg[2];
// Vecteur3 test= xg -vraixg;
// Cerr<<num_poly<< "iiii "<<test[0]<< " "<<test[1]<<" "<<test[2]<<finl;
    }
// Cerr<<" xp "<<xp << finl;
  return ;
// on a change la methode dans Polygone mais pas dans Polyedre ?
  WARN;
  return Elem_geom_base::calculer_centres_gravite(xp);
}
References Elem_geom_base::calculer_centres_gravite(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), FacesIndex_, Zone::les_elems(), Elem_geom_base::ma_zone, Zone::nb_elem_tot(), Nodes_, PolyhedronIndex_, TRUSTTab< _TYPE_ >::resize(), Ref_Zone::valeur(), and WARN.
calculer_un_centre_gravite()
void Polyedre::calculer_un_centre_gravite (const int elem, DoubleVect & xp) const override virtual
Implements Poly_geom_base.
Definition at line 175 of file Polyedre.cpp.
{
  const IntTab& les_Polys = ma_zone->les_elems();
  const Domaine& le_domaine = ma_zone->domaine();
  xp.resize(dimension);
  int nb_som_reel=nb_som();
  while (les_Polys(num_elem,nb_som_reel-1)==-1)  nb_som_reel--;
  for(int s=0; s<nb_som_reel; s++)
    {
      int num_som = les_Polys(num_elem,s);
      for(int i=0; i<dimension; i++)
        xp(i) += le_domaine.coord(num_som,i)/nb_som_reel;
    }
  WARN;
}
References Domaine::coord(), Objet_U::dimension, Zone::domaine(), Zone::les_elems(), Elem_geom_base::ma_zone, nb_som(), TRUSTVect< _TYPE_ >::resize(), and WARN.
calculer_volumes()
void Polyedre::calculer_volumes (DoubleVect & volumes) const override virtual
NE FAIT RIEN: A CODER
Calcule les volumes des elements de la zone associee.
Implements Elem_geom_base.
Definition at line 362 of file Polyedre.cpp.
{
  const Zone& zone=ma_zone.valeur();
  const IntTab& elem=zone.les_elems();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  int size_tot = zone.nb_elem_tot();
  assert(volumes.size_totale()==size_tot);
  for (int num_poly=0; num_poly<size_tot; num_poly++)
    {
      double volume=0;
      Vecteur3 xg(0,0,0);
      int nb_som_max=elem.dimension(1);
      int nb_som_reel;
      for (nb_som_reel=0; nb_som_reel<nb_som_max; nb_som_reel++)
        {
          int n=elem(num_poly,nb_som_reel);
          if (n<0)
            break;
          Vecteur3 S(coord(n,0),coord(n,1),coord(n,2));
          xg+=S;
        }
      xg*=1./nb_som_reel;
      Vecteur3 moinsS0(xg);
      moinsS0*=-1;
      for (int f=PolyhedronIndex_[num_poly]; f<PolyhedronIndex_[num_poly+1]; f++)
        {
          int somm_loc3=Nodes_[FacesIndex_[f+1]-1];
          int n3=elem(num_poly,somm_loc3);
          Vecteur3 S3(coord(n3,0),coord(n3,1),coord(n3,2));
          S3+=  moinsS0;
          for (int s=FacesIndex_[f]; s<FacesIndex_[f+1]-2; s++)
            {
              int somm_loc1=Nodes_[s];
              int n1=elem(num_poly,somm_loc1);
              int somm_loc2=Nodes_[s+1];
              int n2=elem(num_poly,somm_loc2);
              Vecteur3 S1(coord(n1,0),coord(n1,1),coord(n1,2));
              Vecteur3 S2(coord(n2,0),coord(n2,1),coord(n2,2));
              S1+=  moinsS0;
              S2+=  moinsS0;
              volume += std::fabs(
                          S1[0] * ( S2[1] * S3[2] - S3[1] * S2[2] )
                          + S2[0] * ( S3[1] * S1[2] - S1[1] * S3[2] )
                          + S3[0] * ( S1[1] * S2[2] - S2[1] * S1[2] ) );
            }
        }
      volumes(num_poly)=volume/6.;
    }
// Cerr<<" volumes "<<volumes << finl;
  return ;
}
References Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), FacesIndex_, Zone::les_elems(), Elem_geom_base::ma_zone, Zone::nb_elem_tot(), Nodes_, PolyhedronIndex_, TRUSTVect< _TYPE_ >::size_totale(), and Ref_Zone::valeur().
compute_virtual_index()
void Polyedre::compute_virtual_index () override virtual
Implements Poly_geom_base.
Definition at line 664 of file Polyedre.cpp.
{
// Methode brutal mais il faut bien commencer ....
  IntTab faces_som(0,nb_face_elem_max_,nb_som_face_max_);
  ma_zone.valeur().creer_tableau_elements(faces_som);
  IntTab faces_som_local;
  int nb_elem=ma_zone.valeur().nb_elem();
  int nb_elem_tot=ma_zone.valeur().nb_elem_tot();
  for (int ele=0; ele<nb_elem; ele++)
    {
      get_tab_faces_sommets_locaux(faces_som_local,ele);
      for (int k=0; k<nb_face_elem_max_; k++)
        for (int l=0; l<nb_som_face_max_; l++)
          faces_som(ele,k,l)=faces_som_local(k,l);
    }
  faces_som.echange_espace_virtuel();
  int nbs=0;
  PolyhedronIndex_.resize(nb_elem_tot+1);
// Cerr<<"uuu "<< PolyhedronIndex_<<finl;
  for (int ele=nb_elem; ele<nb_elem_tot; ele++)
    {
      int nbf=0;
      for (int k=0; k<nb_face_elem_max_; k++)
        {
          if (faces_som(ele,k,0)!=-1)
            nbf++;
          for (int l=0; l<nb_som_face_max_; l++)
            {
              if (faces_som(ele,k,l)!=-1)
                nbs++;
// Cerr <<" INFO " << ele<< " k" <<k << " l "<< l<< " iiii "<<faces_som(ele,k,l)<<finl;
            }
        }
      PolyhedronIndex_[ele+1]=PolyhedronIndex_[ele]+nbf;
    }
  FacesIndex_.resize(PolyhedronIndex_[nb_elem_tot]+1);
  int nbs_old=Nodes_.size_array();
  Nodes_.resize(nbs_old+nbs);
  int nbft=PolyhedronIndex_[nb_elem];
  nbs=nbs_old;
  for (int ele=nb_elem; ele<nb_elem_tot; ele++)
    {
      for (int k=0; k<nb_face_elem_max_; k++)
        {
          for (int l=0; l<nb_som_face_max_; l++)
            {
              if (faces_som(ele,k,l)!=-1)
                {
                  Nodes_[nbs]=faces_som(ele,k,l);
                  nbs++;
                }
            }
          if (faces_som(ele,k,0)!=-1)
            {
              FacesIndex_[nbft+1]=nbs;
              nbft++;
            }
        }
    }
  for (int ele=nb_elem; ele<nb_elem_tot; ele++)
    {
      get_tab_faces_sommets_locaux(faces_som_local,ele);
      for (int k=0; k<nb_face_elem_max_; k++)
        for (int l=0; l<nb_som_face_max_; l++)
          {
            int ind1=faces_som(ele,k,l);
            int ind2=faces_som_local(k,l);
            if (ind1!=ind2)
              {
                Cerr << "PPPPB "<< ele<< " k " <<k << " l "<< l<< " iiii "<<ind1<<" "<<ind2<<finl;
                abort();
              }
          }
    }
// BLOQUE;
}
References Process::abort(), Cerr, Zone::creer_tableau_elements(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), FacesIndex_, finl, get_tab_faces_sommets_locaux(), Elem_geom_base::ma_zone, Zone::nb_elem(), Zone::nb_elem_tot(), nb_face_elem_max_, nb_som_face_max_, Nodes_, PolyhedronIndex_, TRUSTArray< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::size_array(), and Ref_Zone::valeur().
contient() [1/2]
int Polyedre::contient (const ArrOfDouble & pos, int num_poly) const override virtual
NE FAIT RIEN: A CODER, renvoie toujours 0.
Renvoie 1 si l'element "element" de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
Returns
int
Signification: 1 si le point de coordonnees specifiees
appartient a l'element "element"
0 sinon
Contraintes:
Implements Elem_geom_base.
Definition at line 253 of file Polyedre.cpp.
{
// on regarde si le point P est du meme cote que xg pour chaque face .
  const Zone& zone=ma_zone.valeur();
  const IntTab& elem=zone.les_elems();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  Vecteur3 P(pos[0],pos[1],pos[2]);
  Vecteur3 xg(0,0,0);
  int nb_som_max=elem.dimension(1);
  int nb_som_reel;
  for (nb_som_reel=0; nb_som_reel<nb_som_max; nb_som_reel++)
    {
      int n=elem(num_poly,nb_som_reel);
      if (n<0)
        break;
      Vecteur3 S(coord(n,0),coord(n,1),coord(n,2));
      xg+=S;
    }
  xg*=1./nb_som_reel;
  for (int f=PolyhedronIndex_[num_poly]; f<PolyhedronIndex_[num_poly+1]; f++)
    {
      Vecteur3 n(0,0,0);
      int somm_loc3=Nodes_[FacesIndex_[f+1]-1];
      int n3=elem(num_poly,somm_loc3);
      Vecteur3 moinsS3(-coord(n3,0),-coord(n3,1),-coord(n3,2));
      for (int s=FacesIndex_[f]; s<FacesIndex_[f+1]-2; s++)
        {
          int somm_loc1=Nodes_[s];
          int n1=elem(num_poly,somm_loc1);
          int somm_loc2=Nodes_[s+1];
          int n2=elem(num_poly,somm_loc2);
          Vecteur3 S1(coord(n1,0),coord(n1,1),coord(n1,2));
          Vecteur3 S2(coord(n2,0),coord(n2,1),coord(n2,2));
          S1+=moinsS3;
          S2+=moinsS3;
          Vecteur3 nTr;
          Vecteur3::produit_vectoriel(S1,S2,nTr);
          n+=nTr;
        }
      Vecteur3 S3G(xg);
      S3G+=moinsS3;
      Vecteur3 S3P(P);
      S3P+=moinsS3;
      double prod_scal1=Vecteur3::produit_scalaire(n,S3G);
      double prod_scal2=Vecteur3::produit_scalaire(n,S3P);
      if (prod_scal1*prod_scal2<-Objet_U::precision_geom*prod_scal1*prod_scal1)
        return 0;
    }
  return 1;
}
References Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), FacesIndex_, Zone::les_elems(), Elem_geom_base::ma_zone, Nodes_, PolyhedronIndex_, Objet_U::precision_geom, Vecteur3::produit_scalaire(), Vecteur3::produit_vectoriel(), and Ref_Zone::valeur().
contient() [2/2]
int Polyedre::contient (const ArrOfInt & pos, int num_poly) const override virtual
NE FAIT RIEN: A CODER, renvoie toujours 0
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Returns
int
Signification: 1 si les sommets passes en parametre
sont ceux de l'element specifie, 0 sinon
Contraintes:
Implements Elem_geom_base.
Definition at line 339 of file Polyedre.cpp.
{
  BLOQUE;
  return 0;
}
References BLOQUE.
cree_instance()
Objet_U * Polyedre::cree_instance () static
Definition at line 24 of file Polyedre.cpp.
duplique()
int Polyedre::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Polyedre.cpp.
est_structure()
int Polyedre::est_structure () const inline override virtual
Returns
int
Signification: 1 si l'element est de type structure
0 sinon
Contraintes: toujours egal a 0
Implements Elem_geom_base.
Definition at line 208 of file Polyedre.h.
{
  return 0;
}
face_sommet()
int Polyedre::face_sommet (int face, int sommet) const inline override virtual
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
Returns
int
Signification: le numero du j-ieme sommet de la i-ieme face
Contraintes:
Implements Elem_geom_base.
Definition at line 121 of file Polyedre.h.
{
  BLOQUE;
  return -1;
}
References BLOQUE.
get_info()
const Type_info * Polyedre::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Poly_geom_base.
Definition at line 24 of file Polyedre.cpp.
get_nb_face_elem_max()
int Polyedre::get_nb_face_elem_max () const inline
Definition at line 66 of file Polyedre.h.
  {
    return nb_face_elem_max_ ;
  } ;
References nb_face_elem_max_.
Referenced by nb_faces().
get_nb_som_elem_max()
int Polyedre::get_nb_som_elem_max () const
Definition at line 194 of file Polyedre.cpp.
{
  if (nb_som_elem_max_>-1)
    return nb_som_elem_max_ ;
  else
    return ma_zone.valeur().les_elems().dimension(1);
}
References TRUSTTab< _TYPE_ >::dimension(), Zone::les_elems(), Elem_geom_base::ma_zone, nb_som_elem_max_, and Ref_Zone::valeur().
Referenced by nb_som(), and nom_lml().
get_nb_som_face_max()
int Polyedre::get_nb_som_face_max () const inline
Definition at line 70 of file Polyedre.h.
  {
    return nb_som_face_max_ ;
  } ;
References nb_som_face_max_.
Referenced by nb_som_face().
get_somme_nb_faces_elem()
int Polyedre::get_somme_nb_faces_elem () const override virtual
Implements Poly_geom_base.
Definition at line 754 of file Polyedre.cpp.
{
  int titi= PolyhedronIndex_[ma_zone.valeur().nb_elem()];
  return titi;
}
References Elem_geom_base::ma_zone, Zone::nb_elem(), PolyhedronIndex_, and Ref_Zone::valeur().
get_tab_faces_sommets_locaux() [1/2]
int Polyedre::get_tab_faces_sommets_locaux (IntTab & faces_som_local) const override virtual
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
Implements Poly_geom_base.
Definition at line 428 of file Polyedre.cpp.
{
  return 0;
}
Referenced by compute_virtual_index().
get_tab_faces_sommets_locaux() [2/2]
int Polyedre::get_tab_faces_sommets_locaux (IntTab & faces_som_local, int elem) const override virtual
Implements Poly_geom_base.
Definition at line 432 of file Polyedre.cpp.
{
  faces_som_local.resize(nb_face_elem_max_,nb_som_face_max_);
  faces_som_local=-1;
  if (ele == 0 && PolyhedronIndex_.size_array() == 1) return 1; //pas d'elements!
// on cherche les faces de l'elt
  int fl=0;
  for (int f=PolyhedronIndex_[ele]; f<PolyhedronIndex_[ele+1]; f++)
    {
      int sl=0;
      for (int s=FacesIndex_[f]; s<FacesIndex_[f+1]; s++)
        {
          int somm_loc=Nodes_[s];
          faces_som_local(fl,sl)=somm_loc;
          sl++;
        }
      fl++;
    }
  return 1;
}
References FacesIndex_, nb_face_elem_max_, nb_som_face_max_, Nodes_, PolyhedronIndex_, TRUSTTab< _TYPE_ >::resize(), and TRUSTArray< _TYPE_ >::size_array().
getElemIndex()
const ArrOfInt & Polyedre::getElemIndex () const inline override virtual
Implements Poly_geom_base.
Definition at line 84 of file Polyedre.h.
  {
    return PolyhedronIndex_;
  };
References PolyhedronIndex_.
getFacesIndex()
const ArrOfInt & Polyedre::getFacesIndex () const inline override virtual
Implements Poly_geom_base.
Definition at line 76 of file Polyedre.h.
  {
    return FacesIndex_;
  };
References FacesIndex_.
getPolyhedronIndex()
const ArrOfInt & Polyedre::getPolyhedronIndex () const inline
Definition at line 80 of file Polyedre.h.
  {
    return PolyhedronIndex_;
  };
References PolyhedronIndex_.
info()
const Type_info * Polyedre::info () static
Definition at line 24 of file Polyedre.cpp.
nb_faces()
int Polyedre::nb_faces (int i = 0) const inline override virtual
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
Un Polyedre a 1 type de faces: polygon_3D.
Implements Elem_geom_base.
Definition at line 158 of file Polyedre.h.
{
  assert(i==0);
  switch(i)
    {
    case 0:
      return get_nb_face_elem_max();
    default :
      Cerr << "Error, a polyhedron has 1 type of faces and not " << i << finl;
      exit();
      return -1;
    }
}
References Cerr, Process::exit(), finl, and get_nb_face_elem_max().
nb_som()
int Polyedre::nb_som () const inline override virtual
Renvoie le nombre de sommets d'un Polyedre.
Returns
int
Signification: le nombre de sommets maximum d'un polyedre
Implements Elem_geom_base.
Definition at line 141 of file Polyedre.h.
{
  return get_nb_som_elem_max();
}
References get_nb_som_elem_max().
Referenced by calculer_un_centre_gravite().
nb_som_face()
int Polyedre::nb_som_face (int i = 0) const inline override virtual
Renvoie le nombre maximum de sommets des faces
du type specifie.
Returns
int
Signification: le nombre de sommets des faces de type i
Implements Elem_geom_base.
Definition at line 186 of file Polyedre.h.
{
  assert(i==0);
  return get_nb_som_face_max();
}
References get_nb_som_face_max().
nb_type_face()
int Polyedre::nb_type_face () const override virtual
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 415 of file Polyedre.cpp.
{
  return 1;
}
nom_lml()
const Nom & Polyedre::nom_lml () const override virtual
Renvoie le nom LML d'un polyedre = "POLYEDRE_"+nb_som_max.
Returns
Nom&
Signification: toujours egal a "PRISM6"
Contraintes: reference constante
Implements Elem_geom_base.
Definition at line 216 of file Polyedre.cpp.
{
  static Nom nom;
  nom="POLYEDRE_";
  Nom n(get_nb_som_elem_max());
  nom+=n;
  return nom;
}
References get_nb_som_elem_max().
printOn()
Sortie & Polyedre::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Poly_geom_base.
Definition at line 49 of file Polyedre.cpp.
{
  s<< Nodes_        <<finl;
  s<< FacesIndex_     <<finl;
  s<< PolyhedronIndex_ <<finl;
  s<< nb_som_elem_max_ <<finl;
  s<< nb_face_elem_max_ <<finl;
  s<< nb_som_face_max_ <<finl;;
  WARN;
  return s;
}
References FacesIndex_, finl, nb_face_elem_max_, nb_som_elem_max_, nb_som_face_max_, Nodes_, PolyhedronIndex_, and WARN.
readOn()
Entree & Polyedre::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Poly_geom_base.
Definition at line 76 of file Polyedre.cpp.
{
  s>> Nodes_;
  s>>FacesIndex_;
  s>>PolyhedronIndex_;
  s>>nb_som_elem_max_;
  s>>nb_face_elem_max_;
  s>>nb_som_face_max_;;
  return s;
}
References FacesIndex_, nb_face_elem_max_, nb_som_elem_max_, nb_som_face_max_, Nodes_, and PolyhedronIndex_.
remplir_Nodes_glob()
void Polyedre::remplir_Nodes_glob (ArrOfInt & Nodes_glob, const IntTab & les_elems) const
Definition at line 542 of file Polyedre.cpp.
{
  Nodes_glob=Nodes_;
  int nelem=les_elems.dimension_tot(0);
  for (int ele=0; ele<nelem; ele++)
    {
      for (int f=PolyhedronIndex_[ele]; f<PolyhedronIndex_[ele+1]; f++)
        {
          for (int s=FacesIndex_[f]; s<FacesIndex_[f+1]; s++)
            {
              int somm_loc=Nodes_[s];
              Nodes_glob[s]=les_elems(ele,somm_loc);
            }
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension_tot(), FacesIndex_, Nodes_, and PolyhedronIndex_.
reordonner()
void Polyedre::reordonner () override virtual
Reordonne les sommets du Polyedre.
NE FAIT RIEN: A CODER.
Reimplemented from Elem_geom_base.
Definition at line 574 of file Polyedre.cpp.
{
}
self_cast() [1/2]
const Polyedre & Polyedre::self_cast (const Objet_U & r) static
Definition at line 24 of file Polyedre.cpp.
self_cast() [2/2]
Polyedre & Polyedre::self_cast (Objet_U & r) static
Definition at line 24 of file Polyedre.cpp.
taille_memoire()
unsigned Polyedre::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Polyedre.cpp.
type_face()
Type_Face Polyedre::type_face (int i = 0) const inline override virtual
Renvoie le i-ieme type de face.
Un polyedre a 2 types de face: quadrangle et triangle.
Returns
Type_Face
Signification: le type de la face i
Contraintes: i=0 (Faces::polygone_3D)
Implements Elem_geom_base.
Definition at line 228 of file Polyedre.h.
{
  assert(i<=0);
  switch(i)
    {
    case 0:
      return Faces::polygone_3D;
    default :
      Cerr << "Error, a polyhedron has 1 type of faces and not " << i << finl;
      exit();
      return Faces::quadrangle_3D;
    }
}
References Cerr, Process::exit(), finl, Faces::polygone_3D, and Faces::quadrangle_3D.
Member Data Documentation
FacesIndex_
ArrOfInt Polyedre::FacesIndex_ private
Definition at line 95 of file Polyedre.h.
Referenced by affecte_connectivite_numero_global(), ajouter_elements(), build_reduced(), calculer_centres_gravite(), calculer_volumes(), compute_virtual_index(), contient(), get_tab_faces_sommets_locaux(), getFacesIndex(), Polyedre(), printOn(), readOn(), and remplir_Nodes_glob().
info_obj
const Type_info Polyedre::info_obj static
Definition at line 42 of file Polyedre.h.
nb_face_elem_max_
int Polyedre::nb_face_elem_max_ private
Definition at line 98 of file Polyedre.h.
Referenced by affecte_connectivite_numero_global(), ajouter_elements(), build_reduced(), compute_virtual_index(), get_nb_face_elem_max(), get_tab_faces_sommets_locaux(), Polyedre(), printOn(), and readOn().
nb_som_elem_max_
int Polyedre::nb_som_elem_max_ private
Definition at line 98 of file Polyedre.h.
Referenced by affecte_connectivite_numero_global(), ajouter_elements(), build_reduced(), get_nb_som_elem_max(), Polyedre(), printOn(), and readOn().
nb_som_face_max_
int Polyedre::nb_som_face_max_ private
Definition at line 98 of file Polyedre.h.
Referenced by affecte_connectivite_numero_global(), ajouter_elements(), build_reduced(), compute_virtual_index(), get_nb_som_face_max(), get_tab_faces_sommets_locaux(), Polyedre(), printOn(), and readOn().
Nodes_
ArrOfInt Polyedre::Nodes_ private
Definition at line 95 of file Polyedre.h.
Referenced by affecte_connectivite_numero_global(), ajouter_elements(), build_reduced(), calculer_centres_gravite(), calculer_volumes(), compute_virtual_index(), contient(), get_tab_faces_sommets_locaux(), printOn(), readOn(), and remplir_Nodes_glob().
PolyhedronIndex_
ArrOfInt Polyedre::PolyhedronIndex_ private
PolyhedronIndex_[ele] numero premiere face de l'ele FacesIndex_[f] numero premier indice de sommet de la face f dans Nodes Nodes_[s] numero local du sommet s d'une face, elem(ele,s) -> numero global.
Definition at line 95 of file Polyedre.h.
Referenced by affecte_connectivite_numero_global(), ajouter_elements(), build_reduced(), calculer_centres_gravite(), calculer_volumes(), compute_virtual_index(), contient(), get_somme_nb_faces_elem(), get_tab_faces_sommets_locaux(), getElemIndex(), getPolyhedronIndex(), Polyedre(), printOn(), readOn(), and remplir_Nodes_glob().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Polyedre.h
src/Kernel/Geometrie/Polyedre.cpp