TRUST: Op_Conv_DI_L2_VEF_Face Class Reference
Op_Conv_DI_L2_VEF_Face Class Reference
class Op_Conv_DI_L2_VEF_Face
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VEF
Le champ convecte est scalaire ou vecteur de type Champ_P1NC
Le schema de convection est du type Amont
#include <Op_Conv_DI_L2_VEF_Face.h>
Public Member Functions
Op_Conv_DI_L2_VEF_Face ()
~Op_Conv_DI_L2_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_vitesse (const Champ_base &) override
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
Public Member Functions inherited from Op_Conv_VEF_base
Op_Conv_VEF_base ()
~Op_Conv_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_vitesse (const Champ_base &) override
const Champ_Inc_base & vitesse () const
Champ_Inc_base & vitesse ()
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
void abortTimeStep () override
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_dt_local (DoubleTab &) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_fluent (DoubleVect &) const
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_zone_cl_dis (const Zone_Cl_dis_base &) override
int phi_u_transportant (const Equation_base &eq) const
definit si l'on convecte psi avec phi*u ou avec u
Public Member Functions inherited from Operateur_Conv_base
Operateur_Conv_base ()
initialise dt_stab_conv a -123
~Operateur_Conv_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_vitesse (const Champ_base &vit)=0
double dt_stab_conv () const
void fixer_dt_stab_conv (double dt)
virtual void associer_norme_vitesse (const Champ_base &norme_vitesse)
virtual void associer_vitesse_pour_pas_de_temps (const Champ_base &vitesse)
virtual void set_incompressible (const int)
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Conv_DI_L2_VEF_Face & self_cast (Objet_U &)
static const Op_Conv_DI_L2_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Conv_VEF_base
static const Type_info * info ()
static Op_Conv_VEF_base & self_cast (Objet_U &)
static const Op_Conv_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Conv_base
static const Type_info * info ()
static Operateur_Conv_base & self_cast (Objet_U &)
static const Operateur_Conv_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Conv_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Conv_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
void poly_DI_L2_2d (int, int, DoubleTab &, int, int, const DoubleTab &, int &) const
void poly_DI_L2_3d (int, int, DoubleTab &, int, int, const DoubleTab &, int &) const
void reconst_DI_L2_2d (DoubleTab &, int, double, int, int, const DoubleTab &, int, DoubleTab &, DoubleVect &, int, int &) const
void reconst_DI_L2_3d (DoubleTab &, int, double, int, int, const DoubleTab &, int, DoubleTab &, DoubleVect &, int, int, DoubleVect &, int &) const
Protected Member Functions inherited from Op_Conv_VEF_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Protected Attributes inherited from Op_Conv_VEF_base
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base vitesse_
DoubleVect fluent
tableau qui sert pour le calcul du pas de temps de stabilite
int jeton
int roue
Protected Attributes inherited from Operateur_Conv_base
Ref_Champ_base la_norme_vitesse
Ref_Champ_base vitesse_pour_pas_de_temps_
double dt_stab_conv_
int incompressible_ = 1
incompressible_= 1 -> l'operateur discretise div(v x inco), incompressible_ = 0 -> il discretise v.grad(inco)
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Op_Conv_DI_L2_VEF_Face
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VEF
Le champ convecte est scalaire ou vecteur de type Champ_P1NC
Le schema de convection est du type Amont
Definition at line 38 of file Op_Conv_DI_L2_VEF_Face.h.
Constructor & Destructor Documentation
Op_Conv_DI_L2_VEF_Face()
Op_Conv_DI_L2_VEF_Face::Op_Conv_DI_L2_VEF_Face ()
Definition at line 23 of file Op_Conv_DI_L2_VEF_Face.cpp.
~Op_Conv_DI_L2_VEF_Face()
Op_Conv_DI_L2_VEF_Face::~Op_Conv_DI_L2_VEF_Face ()
Definition at line 23 of file Op_Conv_DI_L2_VEF_Face.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Conv_DI_L2_VEF_Face::ajouter (const DoubleTab & transporte, DoubleTab & resu) const override virtual
< (dimension == 3)
Reimplemented from Operateur_base.
Definition at line 403 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Champ_Inc_base& la_vitesse=vitesse_.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const DoubleTab& facette_normales = zone_VEF.facette_normales();
// const DoubleVect& volumes_entrelaces = zone_VEF.volumes_entrelaces();
  const Zone& zone = zone_VEF.zone();
// const int nb_faces = zone_VEF.nb_faces();
  const int nfa7 = zone_VEF.type_elem().nb_facette();
// const int nb_elem = zone_VEF.nb_elem();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const IntVect& rang_elem_non_std = zone_VEF.rang_elem_non_std();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  /*  const IntTab& face_voisins = zone_VEF.face_voisins();
      int jjj;
      for(jjj = 0;jjj<zone_VEF.nb_faces_tot();jjj++)
      Cerr<<"face_voisins : face = "<<jjj<<" : "<<face_voisins(jjj,0)<<", "<<face_voisins(jjj,1)<<finl;*/
  const DoubleTab& normales_facettes_Cl = zone_Cl_VEF.normales_facettes_Cl();
// const DoubleVect& volumes_entrelaces_Cl = zone_Cl_VEF.volumes_entrelaces_Cl();
  DoubleVect& fluent_ = fluent;
  int nfac = zone.nb_faces_elem();
  int nsom = zone.nb_som_elem();
  int nb_som_facette = zone.type_elem().nb_som_face();
// int premiere_face_int = zone_VEF.premiere_face_int();
// Pour le traitement de la convection on distingue les polyedres
// standard qui ne "voient" pas les conditions aux limites et les
// polyedres non standard qui ont au moins une face sur le bord.
// Un polyedre standard a n facettes sur lesquelles on applique le
// schema de convection.
// Pour un polyedre non standard qui porte des conditions aux limites
// de Dirichlet, une partie des facettes sont portees par les faces.
// En bref pour un polyedre le traitement de la convection depend
// du type (triangle, tetraedre ...) et du nombre de faces de Dirichlet.
  double psc;
  int poly,face_adj,fa7,i,j,n_bord;
  int num_face, rang ,itypcl;
  int num10,num20;
  int ncomp_ch_transporte, first;
  if (transporte.nb_dim() == 1)
    ncomp_ch_transporte=1;
  else
    ncomp_ch_transporte= transporte.dimension(1);
  IntVect face(nfac);
  DoubleVect vs(dimension);
  DoubleVect vc(dimension);
  DoubleTab  vsom(nsom,dimension);
  DoubleVect cc(dimension);
  DoubleTab derive(1,1) ;
  int N ,M , sing , cal_amont;
  DoubleVect trans(ncomp_ch_transporte) ;
  if (dimension == 2)
    {
      N = 5 ;
      M = 8 ;
      derive.resize(N,ncomp_ch_transporte) ;
    }
  else //!< (dimension == 3)
    {
      N = 9 ;
      M = 15 ;
      derive.resize(N,ncomp_ch_transporte) ;
    }
// On remet a zero le tableau qui sert pour
// le calcul du pas de temps de stabilite
  fluent_ = 0;
// Traitement particulier pour les faces de periodicite
  int nb_faces_perio = 0;
// Boucle pour compter le nombre de faces de periodicite
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          nb_faces_perio += le_bord.nb_faces();
        }
    }
  DoubleTab tab;
  if (ncomp_ch_transporte == 1)
    tab.resize(nb_faces_perio);
  else
    tab.resize(nb_faces_perio,ncomp_ch_transporte);
// Boucle pour remplir tab
  nb_faces_perio=0;
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
// const Periodique& la_cl_perio = ref_cast(Periodique, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          for (num_face=num1; num_face<num2; num_face++)
            {
              if (ncomp_ch_transporte == 1)
                tab(nb_faces_perio) = resu(num_face);
              else
                for (int comp=0; comp<ncomp_ch_transporte; comp++)
                  tab(nb_faces_perio,comp) = resu(num_face,comp);
              nb_faces_perio++;
            }
        }
    }
// Les polyedres non standard sont ranges en 2 groupes dans la Zone_VEF:
// - polyedres bords et joints
// - polyedres bords et non joints
// On traite les polyedres en suivant l'ordre dans lequel ils figurent
// dans la zone
// boucle sur les polys
  int nlim = -1 ;
  const IntTab& KEL=zone_VEF.type_elem().valeur().KEL();
  for (poly=0; poly<nb_elem_tot; poly++)
    {
      rang = rang_elem_non_std(poly);
      if (rang==-1)
        itypcl=0;
      else
        itypcl=zone_Cl_VEF.type_elem_Cl(rang);
// calcul des numeros des faces du polyedre
      for (face_adj=0; face_adj<nfac; face_adj++)
        face[face_adj]= elem_faces(poly,face_adj);
// calcul de la vitesse aux sommets des polyedres
      for (j=0; j<dimension; j++)
        {
          vs[j] = la_vitesse(face[0],j);
          for (i=1; i<nfac; i++)
            vs[j]+= la_vitesse(face[i],j);
        }
      for (i=0; i<nsom; i++)
        for (j=0; j<dimension; j++)
          vsom(i,j) = vs[j] - dimension*la_vitesse(face[i],j);
// calcul de vc
      zone_VEF.type_elem().calcul_vc(face,vc,vs,vsom,vitesse(),
                                     itypcl,porosite_face);
      /*    Cerr<<"premiere_face_int = "<<premiere_face_int<<", zone_VEF.nb_faces_joint() = "<<zone_VEF.nb_faces_joint()<<finl;
            Cerr<<"premiere_face_std() = "<<zone_VEF.premiere_face_std()<<finl;
            Cerr<<"nb_elem() = "<<zone_VEF.nb_elem()<<", nb_elem_tot() = "<<zone_VEF.nb_elem_tot()<<finl;
            Cerr<<"nb_faces() = "<<zone_VEF.nb_faces()<<", nb_faces_tot() = "<<zone_VEF.nb_faces_tot()<<finl;
            Cerr<<"nb_faces_bord() = "<<zone_VEF.nb_faces_bord()<<", premiere_face_bord() = "<<zone_VEF.premiere_face_bord()<<finl;*/
      cal_amont = 0 ;
      int elem0,elem1,face_adj_glob;
      for (face_adj=0; face_adj<nfac; face_adj++)
        {
          face_adj_glob = face[face_adj];
          elem0 = face_voisins(face_adj_glob,0);
          elem1 = face_voisins(face_adj_glob,1);
          if ((elem0 == -1) || (elem1 == -1))
            cal_amont++ ;
        }
// calcul polynom de reconstruction
      if(dimension == 2 )
        {
          if ( cal_amont == 0) poly_DI_L2_2d(N,M,derive,poly,ncomp_ch_transporte,transporte,sing);
        }
      else
        {
          if ( cal_amont == 0) poly_DI_L2_3d(N,M,derive,poly,ncomp_ch_transporte,transporte,sing);
        }
// Boucle sur les facettes du polyedre
      for (fa7=0; fa7<nfa7; fa7++)
        {
          if (rang==-1)
            for (i=0; i<dimension; i++)
              cc[i] = facette_normales(poly,fa7,i);
          else
            for (i=0; i<dimension; i++)
              cc[i] = normales_facettes_Cl(rang,fa7,i);
// On applique le schema de convection a chaque sommet de la facette
// reconstruction seulement wenn first = 0
          first = -1 ;
// On traite le ou les sommets qui sont aussi des sommets du polyedre
          for (i=0; i<nb_som_facette-1; i++)
            {
              first++ ;
              psc =0;
              for (j=0; j<dimension; j++)
                psc+= (vc(j)/double(nb_som_facette-1)+vsom(KEL(i+2,fa7),j))*cc[j];
              psc /= nb_som_facette;
              num10 = face[KEL(0,fa7)];
              num20 = face[KEL(1,fa7)];
              if ( cal_amont > 0)
                {
                  convbis(psc,num10,num20,transporte,ncomp_ch_transporte,resu,fluent_);
                }
              else
                {
                  if(dimension == 2 )
                    {
                      reconst_DI_L2_2d(derive,poly,psc,num10,num20,transporte,ncomp_ch_transporte,resu,fluent_,sing,
                                       nlim );
                    }
                  else
                    {
                      reconst_DI_L2_3d(derive,poly,psc,num10,num20,transporte,ncomp_ch_transporte,resu,fluent_,sing,
                                       first,trans,nlim);
                    }
                }
            }
        }
    } //!< fin de la boucle
  Cerr << " limitiert in " << nlim << " valeurs " << finl ;
  int voisine;
  nb_faces_perio = 0;
  double diff1,diff2;
// Dimensionnement du tableau des flux convectifs au bord du domaine
// de calcul
  DoubleTab& flux_b = flux_bords_;
  flux_b.resize(zone_VEF.nb_faces_bord(),ncomp_ch_transporte);
  flux_b = 0.;
// Boucle sur les bords pour traiter les conditions aux limites
// il y a prise en compte d'un terme de convection pour les
// conditions aux limites de Neumann_sortie_libre seulement
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Neumann_sortie_libre& la_sortie_libre = ref_cast(Neumann_sortie_libre, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          for (num_face=num1; num_face<num2; num_face++)
            {
              psc =0;
              for (i=0; i<dimension; i++)
                psc += la_vitesse(num_face,i)*face_normales(num_face,i);
              if (psc>0)
                if (ncomp_ch_transporte == 1)
                  {
                    resu(num_face) -= psc*transporte(num_face);
                    flux_b(num_face,0) -= psc*transporte(num_face);
                  }
                else
                  for (i=0; i<ncomp_ch_transporte; i++)
                    {
                      resu(num_face,i) -= psc*transporte(num_face,i);
                      flux_b(num_face,i) -= psc*transporte(num_face,i);
                    }
              else
                {
                  if (ncomp_ch_transporte == 1)
                    {
                      resu(num_face) -= psc*la_sortie_libre.val_ext(num_face-num1);
                      flux_b(num_face,0) -= psc*la_sortie_libre.val_ext(num_face-num1);
                    }
                  else
                    for (i=0; i<ncomp_ch_transporte; i++)
                      {
                        resu(num_face,i) -= psc*la_sortie_libre.val_ext(num_face-num1,i);
                        flux_b(num_face,i) -= psc*la_sortie_libre.val_ext(num_face-num1);
                      }
                  fluent_[num_face] -= psc;
                }
            }
        }
      else if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          IntVect fait(le_bord.nb_faces());
          fait = 0;
          for (num_face=num1; num_face<num2; num_face++)
            {
              if (fait[num_face-num1] == 0)
                {
                  voisine = la_cl_perio.face_associee(num_face-num1) + num1;
                  if (ncomp_ch_transporte == 1)
                    {
                      diff1 = resu(num_face)-tab(nb_faces_perio);
                      diff2 = resu(voisine)-tab(nb_faces_perio+voisine-num_face);
                      resu(voisine)  += diff1;
                      resu(num_face) += diff2;
                      flux_b(voisine,1) += diff1;
                      flux_b(num_face,0) += diff2;
                    }
                  else
                    for (int comp=0; comp<ncomp_ch_transporte; comp++)
                      {
                        diff1 = resu(num_face,comp)-tab(nb_faces_perio,comp);
                        diff2 = resu(voisine,comp)-tab(nb_faces_perio+voisine-num_face,comp);
                        resu(voisine,comp)  += diff1;
                        resu(num_face,comp) += diff2;
                        flux_b(voisine,comp) += diff1;
                        flux_b(num_face,comp) += diff2;
                      }
                  fait[num_face-num1]= 1;
                  fait[voisine-num1] = 1;
                }
              nb_faces_perio++;
            }
        }
    }
  modifier_flux(*this);
  return resu;
}
References Elem_VEF::calcul_vc(), Cerr, convbis(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Zone_VEF::facette_normales(), finl, Op_Conv_VEF_base::fluent, Operateur_base::flux_bords_, Cond_lim::frontiere_dis(), Elem_VEF_base::KEL(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Op_VEF_Face::modifier_flux(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone::nb_faces_elem(), Elem_VEF::nb_facette(), Zone_dis_base::nb_front_Cl(), Zone::nb_som_elem(), Elem_geom::nb_som_face(), Zone_Cl_VEF::normales_facettes_Cl(), Front_VF::num_premiere_face(), poly_DI_L2_2d(), poly_DI_L2_3d(), Zone_VF::porosite_face(), Zone_VEF::rang_elem_non_std(), reconst_DI_L2_2d(), reconst_DI_L2_3d(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Zone::type_elem(), Zone_VEF::type_elem(), Zone_Cl_VEF::type_elem_Cl(), Neumann_sortie_libre::val_ext(), Deriv_Cond_lim_base::valeur(), Ref_Champ_Inc_base::valeur(), Deriv_Elem_VEF_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Op_Conv_VEF_base::vitesse(), Op_Conv_VEF_base::vitesse_, and Zone_dis_base::zone().
associer_vitesse()
void Op_Conv_DI_L2_VEF_Face::associer_vitesse (const Champ_base & vit) override virtual
Implements Operateur_Conv_base.
Definition at line 46 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
  const Champ_P1NC& inco = ref_cast(Champ_P1NC,vit);
  vitesse_= inco;
}
References ref_cast, and Op_Conv_VEF_base::vitesse_.
cree_instance()
Objet_U * Op_Conv_DI_L2_VEF_Face::cree_instance () static
Definition at line 23 of file Op_Conv_DI_L2_VEF_Face.cpp.
duplique()
int Op_Conv_DI_L2_VEF_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 23 of file Op_Conv_DI_L2_VEF_Face.cpp.
get_info()
const Type_info * Op_Conv_DI_L2_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Conv_base.
Definition at line 23 of file Op_Conv_DI_L2_VEF_Face.cpp.
info()
const Type_info * Op_Conv_DI_L2_VEF_Face::info () static
Definition at line 23 of file Op_Conv_DI_L2_VEF_Face.cpp.
poly_DI_L2_2d()
void Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d (int N, int M, DoubleTab & derive, int poly, int ncomp, const DoubleTab & transporte, int & sing) const protected
Definition at line 1191 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
// Cerr << " in           poly_DI_L2_2d " << finl ;
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const Zone& zone = zone_VEF.zone();
  int nfac = zone.nb_faces_elem();
  const DoubleTab& xv = zone_VEF.xv();
  const DoubleTab& xp = zone_VEF.xp();
  int i, j, face_adj , face_glob , poly1 ;
  DoubleVect dist(dimension) ;
  DoubleTab coor_trans(dimension,dimension) ;
  IntVect face(nfac) ;
  DoubleTab L(M,N) ;
  DoubleTab B(M,ncomp) ;
  DoubleVect dTransp_x(N) ;
  DoubleVect  C(N) ;
  DoubleVect D(N) ;
  DoubleVect SM(N) ;
  double poid ;
  for(face_adj=0; face_adj<nfac; face_adj ++)
    {
      face_glob = elem_faces(poly, face_adj );
      face(face_adj) = face_glob ;
    }
  int num3 = elem_faces(poly, 0);
// coor_trans(0) =  cos((xv(num3,1) - xp(poly,1)) / (xv(num3,0) - xp(poly,0))) ;
// coor_trans(1) =  cos(1.- (xv(num3,1) - xp(poly,1)) / (xv(num3,0) - xp(poly,0))) ;
// coor_trans(0,0) = cos(3.14159/4.) ;
// coor_trans(0,1) = cos(3.14159/4.) ;
// coor_trans(1,0) = cos(3.14159/2.-3.14159/4.) ;
// coor_trans(1,1) = cos(3.14159/2.+3.14159/4.) ;
  coor_trans(0,0) = 1. ;
  coor_trans(0,1) = 0. ;
  coor_trans(1,0) = 0. ;
  coor_trans(1,1) = 1. ;
  int row = -1 ;
  for(int face_adj_poly =0; face_adj_poly < nfac; face_adj_poly ++)
    {
      poly1 = face_voisins(face[face_adj_poly],0);
      if (poly1 == poly ) poly1 = face_voisins(face[face_adj_poly], 1);
      for(face_adj=0; face_adj<nfac; face_adj ++)
        {
          face_glob = elem_faces(poly1, face_adj);
          if (face_glob != num3 )
            {
              row++ ;
              dist = 0.;
              for (i=0; i<dimension; i++)
                for (j=0; j<dimension; j++)
                  dist(i) += (xv(face_glob,j) - xv(num3,j)) * coor_trans(i,j) ;
              poid = 0. ;
              for (i=0; i<dimension; i++)
                poid += ( (xv(face_glob,i)-xp(poly,i)) * (xv(face_glob,i)-xp(poly,i)) );
              poid = 1./sqrt(poid) ;
              L(row,4) = poid * dist(0) * coor_trans(0,0) ;
              L(row,3) = poid * dist(1) * coor_trans(1,1) ;
              L(row,2) = poid * 1./2.*dist(0)*dist(0) ;
              L(row,1) = poid * 1./2.*dist(1)*dist(1) ;
              L(row,0) = poid * dist(0)*dist(1) ;
              if (ncomp == 1)
                B(row,0) = poid * (transporte(face_glob)  - transporte(num3) )  ;
              else for (j=0; j<ncomp; j++)
                  B(row,j) = poid * (transporte(face_glob,j) - transporte(num3,j)) ;
            }
        }
    }
  DoubleTab Lij(N,N) ;
  DoubleTab Bij(N,ncomp) ;
  for (j=0; j<N; j++)
    for (i=0; i<ncomp; i++)
      for (int k=0; k<M; k++)       Bij(j,i) += L(k,j) * B(k,i) ;
  for (i=0; i<N; i++)
    for (j=0; j<N; j++)
      for (int k=0; k<M; k++)       Lij(i,j) += L(k,i) * L(k,j) ;
  for (j=0; j<ncomp; j++)
    {
      for (i=0; i<N; i++)   SM(i)=Bij(i,j) ;
      qrsolv(Lij, N, SM, dTransp_x, sing, j, C, D);
      if (sing == 0 )
        {
          if(ncomp == 1)
            {
              for (int val_N= 0; val_N < N ; val_N++ )
                derive(val_N) = dTransp_x(val_N) ;
            }
          else
            {
              for (int val_N= 0; val_N < N ; val_N++ )
                derive(val_N,j) = dTransp_x(val_N) ;
            }
        }
    }
}
References Objet_U::dimension, Zone_VF::elem_faces(), Zone_VF::face_voisins(), Op_Conv_VEF_base::la_zone_vef, Zone::nb_faces_elem(), qrsolv(), Ref_Zone_VEF::valeur(), Zone_VF::xp(), Zone_VF::xv(), and Zone_dis_base::zone().
Referenced by ajouter().
poly_DI_L2_3d()
void Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d (int N, int M, DoubleTab & derive, int poly, int ncomp, const DoubleTab & transporte, int & sing) const protected
Definition at line 1312 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
// Cerr<<"Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d 0 "<<finl;
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const Zone& zone = zone_VEF.zone();
  int nfac = zone.nb_faces_elem();
  const DoubleTab& xv = zone_VEF.xv();
  const DoubleTab& xp = zone_VEF.xp();
  int i, j, face_adj , face_glob , poly1 ;
  DoubleVect dist(dimension) ;
  DoubleTab coor_trans(dimension,dimension) ;
  IntVect face(nfac) ;
  DoubleTab L(M,N) ;
  DoubleTab B(M,ncomp) ;
  DoubleVect dTransp_x(N) ;
  DoubleVect  C(N) ;
  DoubleVect D(N) ;
  DoubleVect SM(N) ;
  double poid ;
// Cerr<<"Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d 1 "<<finl;
  for(face_adj=0; face_adj<nfac; face_adj ++)
    {
      face_glob = elem_faces(poly, face_adj );
      face(face_adj) = face_glob ;
    }
// Cerr<<"Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d 2 "<<finl;
  int num3 = elem_faces(poly, 0);
  coor_trans(0,0) = cos(3.14159/4.) ;
  coor_trans(0,1) = cos(3.14159/4.) ;
  coor_trans(0,2) = cos(3.14159/2.) ;
  coor_trans(1,0) = cos(3.14159/2.-3.14159/4.) ;
  coor_trans(1,1) = cos(3.14159/2.+3.14159/4.) ;
  coor_trans(1,2) = cos(3.14159/2.) ;
  coor_trans(2,0) = cos(3.14159/2.) ;
  coor_trans(2,1) = cos(3.14159/2.) ;
  coor_trans(2,2) = cos(0.) ;
// coor_trans = 0.;
// coor_trans(0,0) = 1. ;
// coor_trans(1,1) = 1. ;
// coor_trans(2,2) = 1. ;
  int row = -1 ;
// Cerr<<"Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d 3 "<<finl;
  for(int face_adj_poly =0; face_adj_poly < nfac; face_adj_poly ++)
    {
      poly1 = face_voisins(face[face_adj_poly],0);
// Cerr<<"avant poly = "<<poly<<", poly1 = "<<poly1<<", proc = "<<me()<<finl;
// Cerr<<"face[face_adj_poly] = "<<face[face_adj_poly]<<finl;
      if (poly1 == poly ) poly1 = face_voisins(face[face_adj_poly], 1);
// Cerr<<"apres poly = "<<poly<<", poly1 = "<<poly1<<", proc = "<<me()<<finl;
      for(face_adj=0; face_adj<nfac; face_adj ++)
        {
          face_glob = elem_faces(poly1, face_adj);
          if (face_glob != num3 )
            {
              row++ ;
              dist=0 ;
              for (i=0; i<dimension; i++)
                for (j=0; j<dimension; j++)
                  dist(i) += (xv(face_glob,j) - xv(num3,j)) * coor_trans(i,j) ;
              poid = 0. ;
              for (i=0; i<dimension; i++)
                poid += ( (xv(face_glob,i)-xp(poly,i)) * (xv(face_glob,i)-xp(poly,i)) );
              poid = 1./(poid) ;
              L(row,8) = poid*dist(0) * coor_trans(0,0) ;
              L(row,7) = poid*dist(1) * coor_trans(1,1) ;
              L(row,6) = poid*dist(2) * coor_trans(2,2) ;
              L(row,5) = poid*1./2.*dist(0)*dist(0) ;
              L(row,4) = poid*1./2.*dist(1)*dist(1) ;
              L(row,3) = poid*1./2.*dist(2)*dist(2) ;
              L(row,2) = poid*dist(0)*dist(1) ;
              L(row,1) = poid*dist(0)*dist(2) ;
              L(row,0) = poid*dist(1)*dist(2) ;
              if (ncomp == 1)
                B(row,0) = poid * (transporte(face_glob)  - transporte(num3) )  ;
              else for (j=0; j<ncomp; j++)
                  B(row,j) = poid * (transporte(face_glob,j) - transporte(num3,j)) ;
            }
        }
    }
// Cerr<<"Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d 4 "<<finl;
  DoubleTab Lij(N,N) ;
  DoubleTab Bij(N,ncomp) ;
  for (j=0; j<N; j++)
    for (i=0; i<ncomp; i++)
      for (int k=0; k<M; k++)       Bij(j,i) += L(k,j) * B(k,i) ;
// Cerr<<"Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d 5 "<<finl;
  for (i=0; i<N; i++)
    for (j=0; j<N; j++)
      for (int k=0; k<M; k++)       Lij(i,j) += L(k,i) * L(k,j) ;
// Cerr<<"Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d 6 "<<finl;
  for (j=0; j<ncomp; j++)
    {
      for (i=0; i<N; i++) SM(i)=Bij(i,j) ;
      qrsolv(Lij, N, SM, dTransp_x, sing, j, C, D);
      if (sing == 0 )
        {
          if(ncomp == 1)
            {
              for (int val_N= 0; val_N < N ; val_N++ )
                derive(val_N) = dTransp_x(val_N) ;
            }
          else
            {
              for (int val_N= 0; val_N < N ; val_N++ )
                derive(val_N,j) = dTransp_x(val_N) ;
            }
        }
    }
// Cerr<<"Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d 7 "<<finl;
}
References Objet_U::dimension, Zone_VF::elem_faces(), Zone_VF::face_voisins(), Op_Conv_VEF_base::la_zone_vef, Zone::nb_faces_elem(), qrsolv(), Ref_Zone_VEF::valeur(), Zone_VF::xp(), Zone_VF::xv(), and Zone_dis_base::zone().
Referenced by ajouter().
printOn()
Sortie & Op_Conv_DI_L2_VEF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Conv_base.
Definition at line 29 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Conv_DI_L2_VEF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Conv_base.
Definition at line 37 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
  return s ;
}
reconst_DI_L2_2d()
void Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d (DoubleTab & derive, int poly, double psc, int num1, int num2, const DoubleTab & transporte, int ncomp, DoubleTab & resu, DoubleVect & tab_fluent, int sing, int & nlim) const protected
Definition at line 755 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
// Cerr << " in reconst_DI_L2_2d " << sing << finl ;
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
// const IntTab& face_voisins = zone_VEF.face_voisins();
  const Zone& zone = zone_VEF.zone();
  int nfac = zone.nb_faces_elem();
  const DoubleTab& xv = zone_VEF.xv();
  const DoubleTab& xp = zone_VEF.xp();
  double dt=equation().schema_temps().pas_de_temps();
  const Champ_Inc_base& la_vitesse=vitesse_.valeur();
  int i, j, face_adj , face_glob, numg=-1 ;
  DoubleVect dist(dimension) ;
  DoubleVect trans_c_g(ncomp) ;
  DoubleVect vs(ncomp) ;
  DoubleVect trans(ncomp) ;
  DoubleTab coor_trans(dimension,dimension) ;
  trans_c_g = 0. ;
  for (j=0; j<ncomp; j++)
    {
      for(face_adj=0; face_adj<nfac; face_adj ++)
        {
          face_glob = elem_faces(poly, face_adj);
          if (ncomp == 1) trans_c_g(0) += transporte(face_glob)/double(nfac) ;
          else trans_c_g(j) += transporte(face_glob,j)/double(nfac) ;
          if ((face_glob != num1) && (face_glob != num2)) numg = face_glob ;
        }
    }
  int num3 = elem_faces(poly, 0 ) ;
// coor_trans(0,0) = cos(3.14159/4.) ;
// coor_trans(0,1) = cos(3.14159/4.) ;
// coor_trans(1,0) = cos(3.14159/2.-3.14159/4.) ;
// coor_trans(1,1) = cos(3.14159/2.+3.14159/4.) ;
  coor_trans(0,0) = 1. ;
  coor_trans(0,1) = 0. ;
  coor_trans(1,0) = 0. ;
  coor_trans(1,1) = 1. ;
  for (i=0; i<dimension; i++) vs(i)= (la_vitesse(num1,i)+la_vitesse(num2,i)) / 2.;
  dist = 0. ;
  for (i=0; i<dimension; i++)
    for (j=0; j<dimension; j++)
      dist(i) += (2.*xp(poly,j) - xv(numg,j)  -  xv(num3,j) - vs(j)*dt/2. ) * coor_trans(i,j) ;
  double dtrans_max, dtrans_min, dtrans_cen ;
  int amont, aval ;
  if (psc >= 0)
    {
      amont = num1;
      aval  = num2;
    }
  else
    {
      amont = num2;
      aval  = num1;
    }
  for (j=0; j<ncomp; j++)
    {
      if (sing == 0 )
        {
          if(ncomp == 1)
            {
              trans(0) = transporte(num3) + derive(4)*dist(0) * coor_trans(0,0)
                         + derive(3)*dist(1) * coor_trans(1,1)
                         + 1./2.*( derive(2)*dist(0)*dist(0) + derive(1)*dist(1)*dist(1) )
                         + derive(0)*dist(0)*dist(1)    ;
              dtrans_cen =  transporte(amont) + transporte(aval) - trans_c_g(0) ;
              dtrans_max =  std::max( transporte(amont), dtrans_cen ) ;
              dtrans_min =  std::min( transporte(amont), dtrans_cen ) ;
            }
          else
            {
              trans(j) = transporte(num3,j) + derive(4,j)*dist(0) * coor_trans(0,0)
                         + derive(3,j)*dist(1) * coor_trans(1,1)
                         + 1./2.*( derive(2,j)*dist(0)*dist(0) + derive(1,j)*dist(1)*dist(1) )
                         + derive(0,j)*dist(0)*dist(1)    ;
// dtrans_cen =  transporte(num1,j) + transporte(num2,j) - trans_c_g(j) ;
// dtrans_cen =  1./2.*(transporte(amont,j) + transporte(aval,j)) ;
              dtrans_cen =  transporte(num1,j) + transporte(num2,j) - trans_c_g(j) ;
// dtrans_max =  std::max(transporte(amont,j), transporte(aval,j)) ;
              dtrans_max =  std::max( transporte(amont,j) , dtrans_cen) ;
              dtrans_min =  std::min( transporte(amont,j) , dtrans_cen) ;
// dtrans_min =  std::min(dtrans_min, dtrans_cen) ;
            }
          if (trans(j) > dtrans_max )
            {
// Cerr << "lim_max "<< finl ;
              nlim++ ;
              trans(j) = dtrans_max ;
            }
          if (trans(j) < dtrans_min )
            {
// Cerr << "lim_min "<< finl ;
              nlim++ ;
              trans(j) = dtrans_min ;
            }
        }
      else
        {
          if(ncomp == 1) trans(0) = ( transporte(num1) + transporte(num2) ) - trans_c_g(0) ;
          else           trans(j) = ( transporte(num1,j) + transporte(num2,j) ) - trans_c_g(j) ;
          Cerr << " singx != 0 " << finl ;
        }
    }
// double kwave = 1. ;
// double lo_x = xv(num1,0)+xv(num2,0)-xp(poly,0) ;
// double lo_y = xv(num1,1)+xv(num2,1)-xp(poly,1) ;
// double exact0= -sin(kwave*lo_x)*cos(kwave*lo_y);
// double exact1=  cos(kwave*lo_x)*sin(kwave*lo_y);
// double exact0 = kwave*lo_x*lo_x ;
// double exact1 = kwave*lo_y*lo_y ;
// double moyenne0 = (transporte(num1,0) + transporte(num2,0)) - trans_c_g(0)  ;
// double moyenne1 = (transporte(num1,1) + transporte(num2,1)) - trans_c_g(1)  ;
// double xv1 = (xv(num1,0)+xv(num2,0)-xp(poly,0)) - (xv(num3,0) + dist(0) - coor_trans(0)) ;
// double xv2 = (xv(num1,1)+xv(num2,1)-xp(poly,1)) - (xv(num3,1) + dist(1) - coor_trans(1)) ;
// double moyenne0 = transporte(numg,0) ;
// double moyenne1 = transporte(numg,1) ;
// if (sing == 0) Cerr << exact0 << " " << moyenne0 << " " << trans(0)  << " "
// << exact1 << " " << moyenne1 << " " << trans(1) << finl ;
// if (sing == 0) Cerr << moyenne0 << " " << trans(0)  << " "
// << moyenne1 << " " << trans(1) << finl ;
// Cerr << numg <<  " " << num3 << finl ;
  double flux;
  if (psc >= 0)
    {
      tab_fluent[num2] += psc;
    }
  else
    {
      tab_fluent[num1] -= psc;
    }
  if (ncomp == 1)
    {
      flux = trans(0)*psc;
      resu(num1) -= flux;
      resu(num2) += flux;
    }
  else
    {
      for (i=0; i<ncomp; i++)
        {
          flux = trans(i)*psc;
          resu(num1,i) -= flux;
          resu(num2,i) += flux;
        }
    }
}
References Cerr, Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), finl, Op_Conv_VEF_base::la_zone_vef, Zone::nb_faces_elem(), Schema_Temps_base::pas_de_temps(), Equation_base::schema_temps(), Ref_Champ_Inc_base::valeur(), Ref_Zone_VEF::valeur(), Op_Conv_VEF_base::vitesse_, Zone_VF::xp(), Zone_VF::xv(), and Zone_dis_base::zone().
Referenced by ajouter().
reconst_DI_L2_3d()
void Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d (DoubleTab & derive, int poly, double psc, int num1, int num2, const DoubleTab & transporte, int ncomp, DoubleTab & resu, DoubleVect & tab_fluent, int sing, int first, DoubleVect & trans, int & nlim) const protected
Definition at line 946 of file Op_Conv_DI_L2_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
// const IntTab& face_voisins = zone_VEF.face_voisins();
// const int nb_faces = zone_VEF.nb_faces();
// const int nfa7 = zone_VEF.type_elem().nb_facette();
// const int nb_elem = zone_VEF.nb_elem();
// const int nb_elem_tot = zone_VEF.nb_elem_tot();
// int premiere_face_std = zone_VEF.premiere_face_std();
  const Zone& zone = zone_VEF.zone();
  int nfac = zone.nb_faces_elem();
// int nsom = zone.nb_som_elem();
// int nb_som_facette = zone.type_elem().nb_som_face();
  const DoubleTab& xv = zone_VEF.xv();
  const DoubleTab& xp = zone_VEF.xp();
  double dt=equation().schema_temps().pas_de_temps();
  const Champ_Inc_base& la_vitesse=vitesse_.valeur();
  double dtrans_max, dtrans_min, dtrans_cen;//, dtrans_aval ;
  int i, j, face_adj , face_glob ;
  DoubleVect dist(dimension) ;
  DoubleTab coor_trans(dimension,dimension) ;
  DoubleVect trans_c_g(ncomp) ;
  double flux;
  IntVect face(nfac) ;
  DoubleVect vs(dimension) ;
  int amont, aval ;
  if (psc >= 0)
    {
      amont = num1;
      aval  = num2;
    }
  else
    {
      amont = num2;
      aval  = num1;
    }
  if(first == 0)
    {
      trans_c_g = 0. ;
      for(face_adj=0; face_adj<nfac; face_adj ++)
        {
          face_glob = elem_faces(poly, face_adj );
          face(face_adj) = face_glob ;
          for (i=0; i<ncomp; i++)
            trans_c_g(i) += transporte(face_glob,i)/double(nfac) ;
        }
      int num3 = elem_faces(poly, 0 ) ;
      coor_trans(0,0) = cos(3.14159/4.) ;
      coor_trans(0,1) = cos(3.14159/4.) ;
      coor_trans(0,2) = cos(3.14159/2.) ;
      coor_trans(1,0) = cos(3.14159/2.-3.14159/4.) ;
      coor_trans(1,1) = cos(3.14159/2.+3.14159/4.) ;
      coor_trans(1,2) = cos(3.14159/2.) ;
      coor_trans(2,0) = cos(3.14159/2.) ;
      coor_trans(2,1) = cos(3.14159/2.) ;
      coor_trans(2,2) = cos(0.) ;
// coor_trans = 0.;
// coor_trans(0,0) = 1. ;
// coor_trans(1,1) = 1. ;
// coor_trans(2,2) = 1. ;
      vs =0. ;
      for(face_adj=0; face_adj<nfac; face_adj ++)
        {
          face_glob = elem_faces(poly, face_adj );
          face(face_adj) = face_glob ;
          for (i=0; i<dimension; i++)
            vs(i) -= la_vitesse(face_glob,i)/double(nfac) ;
        }
      for (i=0; i<dimension; i++) vs(i) += la_vitesse(num1,i) + la_vitesse(num2,i) ;
      dist = 0. ;
      for(face_adj=0; face_adj<nfac; face_adj ++)
        {
          face_glob = elem_faces(poly, face_adj);
          if ((face_glob == num1) || (face_glob == num2 ))
            for (i=0; i<dimension; i++)
              for (j=0; j<dimension; j++)
                dist(i) += xv(face_glob,j) * coor_trans(i,j) ;
        }
      for(i=0; i<dimension; i++)
        for (j=0; j<dimension; j++)
          dist(i) -= (xp(poly,j) + xv(num3,j) + vs(j)*dt/2.) * coor_trans(i,j) ;
      for (j=0; j<ncomp; j++)
        {
          if (sing == 0 )
            {
              if(ncomp == 1)
                {
                  trans(j) = transporte(num3,j) + derive(8)*dist(0) * coor_trans(0,0)
                             + derive(7)*dist(1) * coor_trans(1,1)
                             + derive(6)*dist(2) * coor_trans(2,2)
                             + 1./2.*( derive(5)*dist(0)*dist(0) + derive(4)*dist(1)*dist(1)
                                       + derive(3)*dist(2)*dist(2) )
                             + derive(2)*dist(0)*dist(1) + derive(1)*dist(0)*dist(2)
                             + derive(0)*dist(1)*dist(2) ;
                  dtrans_cen =  transporte(amont) + transporte(aval) - trans_c_g(0) ;
// dtrans_max =  std::max(transporte(amont), transporte(aval)) ;
                  dtrans_max =  std::max( transporte(amont), dtrans_cen ) ;
                  dtrans_min =  std::min( transporte(amont), dtrans_cen ) ;
// dtrans_min =  std::min(dtrans_min, dtrans_cen) ;
                }
              else
                {
                  trans(j) = transporte(num3,j) + derive(8,j)*dist(0) * coor_trans(0,0)
                             + derive(7,j)*dist(1) * coor_trans(1,1)
                             + derive(6,j)*dist(2) * coor_trans(2,2)
                             + 1./2.*( derive(5,j)*dist(0)*dist(0) + derive(4,j)*dist(1)*dist(1)
                                       + derive(3,j)*dist(2)*dist(2) )
                             +         derive(2,j)*dist(0)*dist(1) + derive(1,j)*dist(0)*dist(2)
                             +         derive(0,j)*dist(1)*dist(2) ;
                  dtrans_cen  =  transporte(amont,j) + transporte(aval,j) - trans_c_g(j) ;
                  dtrans_max =  std::max( transporte(amont,j), dtrans_cen ) ;
                  dtrans_min =  std::min( transporte(amont,j), dtrans_cen ) ;
                }
              if (trans(j) > dtrans_max )
                {
// Cerr << " lim max in element " << poly << finl ;
                  trans(j) = dtrans_max ;
                  nlim++ ;
                }
              if (trans(j) < dtrans_min )
                {
// Cerr << " lim min in element " << poly << finl ;
                  trans(j) = dtrans_min ;
                  nlim++ ;
                }
            }
          else
            {
              if(ncomp == 1)
                {
                  trans(0) =  transporte(num1) + transporte(num2)  - trans_c_g(0) ;
                }
              else
                {
                  trans(j) =  transporte(num1,j) + transporte(num2,j)  - trans_c_g(j) ;
// Cerr << " singx != 0 " << finl ;
                }
            }
        }
// double lo_x = xv(num1,0)+xv(num2,0)-xp(poly,0) ;
// double lo_y = xv(num1,1)+xv(num2,1)-xp(poly,1) ;
// double lo_z = xv(num1,2)+xv(num2,2)-xp(poly,2) ;
// double exact0= -sin(kwave*lo_x)*cos(kwave*lo_y);
// double exact1=  cos(kwave*lo_x)*sin(kwave*lo_y);
// double exact0 = lo_x*lo_x   ;
// double exact1 = lo_y*lo_y   ;
// double exact2 = lo_z*lo_z   ;
// double moyenne0 =  (transporte(num1,0) + transporte(num2,0)) - trans_c_g(0) ;
// double moyenne1 =  (transporte(num1,1) + transporte(num2,1)) - trans_c_g(1) ;
// double moyenne2 =  (transporte(num1,2) + transporte(num2,2)) - trans_c_g(2) ;
// double moyenne0 =   transporte(num1,0) ;
// double moyenne1 =   transporte(num1,1) ;
// double moyenne2 =   transporte(num1,2) ;   ;
// double x0 =  (xv(num1,0) + xv(num2,0)) - xp(poly,0) ;
// double x1 =  (xv(num1,1) + xv(num2,1)) - xp(poly,1) ;
// double x2 =  (xv(num1,2) + xv(num2,2)) - xp(poly,2) ;
// double x0 =   xv(num1,0) ;
// double x1 =   xv(num1,1) ;
// double x2 =   xv(num1,2) ;
// double y0 =   xv(num3,0) + dist(0) ;
// double y1 =   xv(num3,1) + dist(1) ;
// double y2 =   xv(num3,2) + dist(2) ;
// if (sing == 0) Cerr << moyenne0 <<  "  " <<trans(0) << "  " << moyenne1 <<
// "  " << trans(1) << "  " << moyenne2 << "  " << trans(2) <<finl ;
// Cerr << " exact0" <<  " " << exact0 << "  " << "exact1" <<  " " << exact1
// << " exact2" <<  " " << exact2 << finl ;
// Cerr << x0<<  " " << y0 <<  " "<<x1 <<  " "<< y1<<  " " << x2 <<  " "<< y2 << finl ;
    } //!< ende first = 0 und normal weiter
  if (psc >= 0)
    {
      tab_fluent[num2] += psc;
    }
  else
    {
      tab_fluent[num1] -= psc;
    }
  if (ncomp == 1)
    {
      flux = trans(0)*psc;
      resu(num1) -= flux;
      resu(num2) += flux;
    }
  else
    {
      for (i=0; i<ncomp; i++)
        {
          flux = trans(i)*psc;
          resu(num1,i) -= flux;
          resu(num2,i) += flux;
        }
    }
}
References Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Op_Conv_VEF_base::la_zone_vef, Zone::nb_faces_elem(), Schema_Temps_base::pas_de_temps(), Equation_base::schema_temps(), Ref_Champ_Inc_base::valeur(), Ref_Zone_VEF::valeur(), Op_Conv_VEF_base::vitesse_, Zone_VF::xp(), Zone_VF::xv(), and Zone_dis_base::zone().
Referenced by ajouter().
self_cast() [1/2]
const Op_Conv_DI_L2_VEF_Face & Op_Conv_DI_L2_VEF_Face::self_cast (const Objet_U & r) static
Definition at line 23 of file Op_Conv_DI_L2_VEF_Face.cpp.
self_cast() [2/2]
Op_Conv_DI_L2_VEF_Face & Op_Conv_DI_L2_VEF_Face::self_cast (Objet_U & r) static
Definition at line 23 of file Op_Conv_DI_L2_VEF_Face.cpp.
taille_memoire()
unsigned Op_Conv_DI_L2_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 23 of file Op_Conv_DI_L2_VEF_Face.cpp.
Member Data Documentation
info_obj
const Type_info Op_Conv_DI_L2_VEF_Face::info_obj static
Definition at line 41 of file Op_Conv_DI_L2_VEF_Face.h.
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Conv_DI_L2_VEF_Face.h
src/VEF/Operateurs/Op_Conv_DI_L2_VEF_Face.cpp