TRUST: Champ Class Reference
Champ Class Reference
class Champ
Cette classe sert a representer n'importe quelle classe derivee de la classe Champ_base
#include <Champ.h>
Public Member Functions
Champ ()
~Champ ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int nb_comp () const
double changer_temps (const double t)
double temps () const
void nommer (const Nom &un_nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
void fixer_nb_comp (int i)
void mettre_a_jour (double un_temps)
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Noms & fixer_unites (const Noms &les_unites)
const Nom & fixer_unite (const Nom &lunite)
const Nom & fixer_unite (int i, const Nom &lunite)
const Noms & unites () const
const Nom & unite () const
const Nom & unite (int i) const
const Noms & fixer_noms_compo (const Noms &les_noms)
const Nom & fixer_nom_compo (int i, const Nom &nom)
const Nom & fixer_nom_compo (const Nom &nom)
const Noms & noms_compo () const
const Nom & nom_compo (int i) const
const Nom & nom_compo () const
const Champ_base & operator= (const Champ_base &ch)
Champ_base & affecter (const Champ_base &ch)
Champ_base & affecter_compo (const Champ_base &ch, int compo)
DoubleTab & valeurs () override
const DoubleTab & valeurs () const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &les_valeurs) const
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &les_valeurs, int le_poly) const
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
double valeur_a_sommet_compo (int num_som, int le_poly, int ncomp) const
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &les_valeurs) const
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &les_valeurs, int ncomp) const
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &les_valeurs) const
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &les_valeurs, int ncomp) const
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Deriv_Champ_base
~Deriv_Champ_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Champ_base ()
Deriv_Champ_base (const Deriv_Champ_base &)
const Champ_base & valeur () const
Champ_base & valeur ()
const Champ_base * operator-> () const
Champ_base * operator-> ()
const Deriv_Champ_base & operator= (const Champ_base &)
const Deriv_Champ_base & operator= (const Deriv_Champ_base &)
operator const Champ_base & () const
operator Champ_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ & self_cast (Objet_U &)
static const Champ & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Champ_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Champ_base & self_cast (Objet_U &)
static const Deriv_Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Deriv_Champ_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
class Champ
Cette classe sert a representer n'importe quelle classe derivee de la classe Champ_base
Definition at line 27 of file Champ.h.
Constructor & Destructor Documentation
Champ()
Champ::Champ ()
Definition at line 19 of file Champ.cpp.
~Champ()
Champ::~Champ ()
Definition at line 19 of file Champ.cpp.
Member Function Documentation
affecter()
Champ_base & Champ::affecter (const Champ_base & ch) inline
Definition at line 61 of file Champ.h.
{ return valeur().affecter(ch); }
References Champ_base::affecter(), and Deriv_Champ_base::valeur().
Referenced by Champ_Generique_Interpolation::get_champ_with_calculer_champ_post().
affecter_compo()
Champ_base & Champ::affecter_compo (const Champ_base & ch, int compo) inline
Definition at line 62 of file Champ.h.
{ return valeur().affecter_compo(ch, compo); }
References Champ_base::affecter_compo(), and Deriv_Champ_base::valeur().
changer_temps()
double Champ::changer_temps (const double t) inline
Definition at line 32 of file Champ.h.
{ return valeur().changer_temps(t); }
References Champ_base::changer_temps(), and Deriv_Champ_base::valeur().
Referenced by Fluide_Dilatable_base::mettre_a_jour().
cree_instance()
Objet_U * Champ::cree_instance () static
Definition at line 19 of file Champ.cpp.
duplique()
int Champ::duplique () const override virtual
Reimplemented from Deriv_Champ_base.
Definition at line 19 of file Champ.cpp.
fixer_nb_comp()
void Champ::fixer_nb_comp (int i) inline
Definition at line 35 of file Champ.h.
{ valeur().fixer_nb_comp(i); }
References Field_base::fixer_nb_comp(), and Deriv_Champ_base::valeur().
Referenced by Champ_Generique_Extraction::get_champ().
fixer_nom_compo() [1/2]
const Nom & Champ::fixer_nom_compo (const Nom & nom) inline
Definition at line 49 of file Champ.h.
{ return valeur().fixer_nom_compo(nom); }
References Field_base::fixer_nom_compo(), and Deriv_Champ_base::valeur().
fixer_nom_compo() [2/2]
const Nom & Champ::fixer_nom_compo (int i, const Nom & nom) inline
Definition at line 48 of file Champ.h.
{ return valeur().fixer_nom_compo(i, nom); }
References Field_base::fixer_nom_compo(), and Deriv_Champ_base::valeur().
fixer_noms_compo()
const Noms & Champ::fixer_noms_compo (const Noms & les_noms) inline
Definition at line 47 of file Champ.h.
{ return valeur().fixer_noms_compo(les_noms); }
References Field_base::fixer_noms_compo(), and Deriv_Champ_base::valeur().
fixer_unite() [1/2]
const Nom & Champ::fixer_unite (const Nom & lunite) inline
Definition at line 40 of file Champ.h.
{ return valeur().fixer_unite(lunite); }
References Field_base::fixer_unite(), and Deriv_Champ_base::valeur().
fixer_unite() [2/2]
const Nom & Champ::fixer_unite (int i, const Nom & lunite) inline
Definition at line 41 of file Champ.h.
{ return valeur().fixer_unite(i, lunite); }
References Field_base::fixer_unite(), and Deriv_Champ_base::valeur().
fixer_unites()
const Noms & Champ::fixer_unites (const Noms & les_unites) inline
Definition at line 39 of file Champ.h.
{ return valeur().fixer_unites(les_unites); }
References Field_base::fixer_unites(), and Deriv_Champ_base::valeur().
get_info()
const Type_info * Champ::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Champ_base.
Definition at line 19 of file Champ.cpp.
info()
const Type_info * Champ::info () static
Definition at line 19 of file Champ.cpp.
le_nom()
const Nom & Champ::le_nom () const inline override virtual
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
Nom&
Signification: le nom de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 37 of file Champ.h.
{ return valeur().le_nom(); }
References Field_base::le_nom(), and Deriv_Champ_base::valeur().
mettre_a_jour()
void Champ::mettre_a_jour (double un_temps) inline
Definition at line 36 of file Champ.h.
{ valeur().mettre_a_jour(un_temps); }
References Champ_base::mettre_a_jour(), and Deriv_Champ_base::valeur().
Referenced by Fluide_base::creer_e_int(), Milieu_base::mettre_a_jour(), Champ_Generique_Champ::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour(), Loi_Etat_base::mettre_a_jour(), Fluide_Dilatable_base::mettre_a_jour(), and Fluide_base::mettre_a_jour().
nb_comp()
int Champ::nb_comp () const inline
Definition at line 31 of file Champ.h.
{ return valeur().nb_comp(); }
References Field_base::nb_comp(), and Deriv_Champ_base::valeur().
Referenced by Milieu_base::discretiser(), and Diametre_hyd_champ::interpreter().
nom_compo() [1/2]
const Nom & Champ::nom_compo () const inline
Definition at line 53 of file Champ.h.
{ return valeur().nom_compo(); }
References Field_base::nom_compo(), and Deriv_Champ_base::valeur().
nom_compo() [2/2]
const Nom & Champ::nom_compo (int i) const inline
Definition at line 52 of file Champ.h.
{ return valeur().nom_compo(i); }
References Field_base::nom_compo(), and Deriv_Champ_base::valeur().
nommer()
void Champ::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
Reimplemented from Objet_U.
Definition at line 34 of file Champ.h.
{ valeur().nommer(un_nom); }
References Field_base::nommer(), and Deriv_Champ_base::valeur().
noms_compo()
const Noms & Champ::noms_compo () const inline
Definition at line 51 of file Champ.h.
{ return valeur().noms_compo(); }
References Field_base::noms_compo(), and Deriv_Champ_base::valeur().
operator=()
const Champ_base & Champ::operator= (const Champ_base & ch) inline
Definition at line 55 of file Champ.h.
  {
    DERIV(Champ_base)::operator=(ch);
    return this->valeur();
  }
References DERIV, operator=(), and Deriv_Champ_base::valeur().
Referenced by operator=().
printOn()
Sortie & Champ::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Champ_base.
Definition at line 20 of file Champ.cpp.
{ return DERIV(Champ_base)::printOn(os); }
References DERIV, and printOn().
Referenced by printOn().
readOn()
Entree & Champ::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Champ_base.
Definition at line 21 of file Champ.cpp.
{ return DERIV(Champ_base)::readOn(is); }
References DERIV, and readOn().
Referenced by readOn().
self_cast() [1/2]
const Champ & Champ::self_cast (const Objet_U & r) static
Definition at line 19 of file Champ.cpp.
self_cast() [2/2]
Champ & Champ::self_cast (Objet_U & r) static
Definition at line 19 of file Champ.cpp.
taille_memoire()
unsigned Champ::taille_memoire () const override virtual
Reimplemented from Deriv_Champ_base.
Definition at line 19 of file Champ.cpp.
temps()
double Champ::temps () const inline
Definition at line 33 of file Champ.h.
{ return valeur().temps(); }
References Champ_base::temps(), and Deriv_Champ_base::valeur().
Referenced by Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_base::calculer_nu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_nu_sur_Sc(), and Loi_Etat_Multi_GP_WC::initialiser_inco_ch().
unite() [1/2]
const Nom & Champ::unite () const inline
Definition at line 44 of file Champ.h.
{ return valeur().unite(); }
References Field_base::unite(), and Deriv_Champ_base::valeur().
unite() [2/2]
const Nom & Champ::unite (int i) const inline
Definition at line 45 of file Champ.h.
{ return valeur().unite(i); }
References Field_base::unite(), and Deriv_Champ_base::valeur().
unites()
const Noms & Champ::unites () const inline
Definition at line 43 of file Champ.h.
{ return valeur().unites(); }
References Field_base::unites(), and Deriv_Champ_base::valeur().
valeur_a()
DoubleVect & Champ::valeur_a (const DoubleVect & position, DoubleVect & les_valeurs) const inline
Definition at line 68 of file Champ.h.
  {
    return valeur().valeur_a(position, les_valeurs);
  }
References Deriv_Champ_base::valeur(), and Champ_base::valeur_a().
valeur_a_elem()
DoubleVect & Champ::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const inline
Definition at line 73 of file Champ.h.
  {
    return valeur().valeur_a_elem(position, les_valeurs, le_poly);
  }
References Deriv_Champ_base::valeur(), and Champ_base::valeur_a_elem().
valeur_a_elem_compo()
double Champ::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline
Definition at line 78 of file Champ.h.
  {
    return valeur().valeur_a_elem_compo(position, le_poly, ncomp);
  }
References Deriv_Champ_base::valeur(), and Champ_base::valeur_a_elem_compo().
valeur_a_sommet_compo()
double Champ::valeur_a_sommet_compo (int num_som, int le_poly, int ncomp) const inline
Definition at line 83 of file Champ.h.
  {
    return valeur().valeur_a_sommet_compo(num_som, le_poly, ncomp);
  }
References Deriv_Champ_base::valeur(), and Champ_base::valeur_a_sommet_compo().
valeur_aux()
DoubleTab & Champ::valeur_aux (const DoubleTab & positions, DoubleTab & les_valeurs) const inline
Definition at line 88 of file Champ.h.
  {
    return valeur().valeur_aux(positions, les_valeurs);
  }
References Deriv_Champ_base::valeur(), and Champ_base::valeur_aux().
valeur_aux_compo()
DoubleVect & Champ::valeur_aux_compo (const DoubleTab & positions, DoubleVect & les_valeurs, int ncomp) const inline
Definition at line 93 of file Champ.h.
  {
    return valeur().valeur_aux_compo(positions, les_valeurs, ncomp);
  }
References Deriv_Champ_base::valeur(), and Champ_base::valeur_aux_compo().
valeur_aux_elems()
DoubleTab & Champ::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const inline
Definition at line 98 of file Champ.h.
  {
    return valeur().valeur_aux_elems(positions, les_polys, les_valeurs);
  }
References Deriv_Champ_base::valeur(), and Champ_base::valeur_aux_elems().
Referenced by Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), and Zone_EF_axi::remplir_tableau_origine().
valeur_aux_elems_compo()
DoubleVect & Champ::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const inline
Definition at line 103 of file Champ.h.
  {
    return valeur().valeur_aux_elems_compo(positions, les_polys, les_valeurs, ncomp);
  }
References Deriv_Champ_base::valeur(), and Champ_base::valeur_aux_elems_compo().
valeurs() [1/6]
const DoubleTab & Champ::valeurs () const inline override virtual
Implements Champ_Proto.
Definition at line 66 of file Champ.h.
{ return valeur().valeurs(); }
References Deriv_Champ_base::valeur(), and Champ_Proto::valeurs().
valeurs() [2/6]
virtual const DoubleTab & Champ_Proto::valeurs () const virtual
Implements Champ_Proto.
valeurs() [3/6]
DoubleTab & Champ::valeurs () inline override virtual
Implements Champ_Proto.
Definition at line 65 of file Champ.h.
{ return valeur().valeurs(); }
References Deriv_Champ_base::valeur(), and Champ_Proto::valeurs().
Referenced by Terme_Source_Th_TdivU_VEF_Face::ajouter(), Source_QC_Gravite_VDF::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Convection_Diffusion_Temperature::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Milieu_base::calculer_alpha(), Loi_Etat_base::calculer_alpha(), Loi_Etat_GP_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_alpha(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Traitement_particulier_NS_EC::calculer_Ec(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Loi_Etat_base::calculer_masse_volumique(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Loi_Etat_base::calculer_nu(), Fluide_base::calculer_nu(), Operateur_base::calculer_pour_post(), Op_Diff_negligeable::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Op_Diff_VEF_base::calculer_pour_post(), Op_Dift_VEF_Face::calculer_pour_post(), Fluide_reel_base::check_unknown_range(), Op_Diff_PolyMAC_P0_base::completer(), Fluide_base::creer_nu(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Champ_Generique_Correlation::get_champ(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Ecart_Type::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Morceau_Equation::get_champ(), Champ_Generique_Moyenne::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Post_Operateur_Eqn::get_champ(), Champ_Generique_modifier_pour_QC::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_Interpolation::get_ref_values(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Loi_Etat_GP_base::initialiser(), Loi_Etat_GR_base::initialiser(), Loi_Etat_base::initialiser_inco_ch(), Loi_Etat_GR_base::initialiser_inco_ch(), Fluide_Weakly_Compressible::initialiser_pth(), Loi_Etat_rhoT_GP_QC::initialiser_rho(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), Fluide_reel_base::mettre_a_jour(), Loi_Etat_base::mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), multiplier_diviser_rho(), Navier_Stokes_std::preparer_calcul(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), EOS_Tools_VEF::rho_discvit(), Convection_Diffusion_Temperature::transport_ibc(), Op_Diff_PolyMAC_P0_base::update_nu(), Milieu_base::update_rho_cp(), Fluide_Dilatable_base::update_rho_cp(), Fluide_base::verifier_coherence_champs(), and Fluide_Quasi_Compressible::write_mean_edo().
valeurs() [4/6]
virtual DoubleTab & Champ_Proto::valeurs () virtual
Implements Champ_Proto.
valeurs() [5/6]
virtual DoubleTab & Champ_Proto::valeurs (double temps) inline virtual
Reimplemented from Champ_Proto.
Definition at line 50 of file Champ_Proto.h.
{ return valeurs(); }
valeurs() [6/6]
virtual const DoubleTab & Champ_Proto::valeurs (double temps) const inline virtual
Reimplemented from Champ_Proto.
Definition at line 51 of file Champ_Proto.h.
{ return valeurs(); }
Member Data Documentation
info_obj
const Type_info Champ::info_obj static
Definition at line 29 of file Champ.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ.h
src/Kernel/Framework/Champ.cpp