TRUST: Comm_Group_Noparallel Class Reference
Comm_Group_Noparallel Class Reference
#include <Comm_Group_Noparallel.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Comm_Group_Noparallel ()
~Comm_Group_Noparallel () override
void abort () const override
void mp_collective_op (const double *x, double *resu, int n, Collective_Op op) const override
void mp_collective_op (const double *x, double *resu, const Collective_Op *op, int n) const override
void mp_collective_op (const int *x, int *resu, int n, Collective_Op op) const override
void mp_collective_op (const int *x, int *resu, const Collective_Op *op, int n) const override
void barrier (int tag) const override
int reverse_send_recv_list (const ArrOfInt &src_list, ArrOfInt &dest_list) const
Comm_Group_Noparallel (const ArrOfInt &pe_list)
void send_recv_start (const ArrOfInt &send_list, const ArrOfInt &send_size, const char *const *const send_buffers, const ArrOfInt &recv_list, const ArrOfInt &recv_size, char *const *const recv_buffers, TypeHint typehint=CHAR) const override
void send_recv_finish () const override
void send (int pe, const void *buffer, int size, int tag) const override
Envoi bloquant.
void recv (int pe, void *buffer, int size, int tag) const override
Reception bloquante.
void broadcast (void *buffer, int size, int pe_source) const override
void all_to_all (const void *src_buffer, void *dest_buffer, int data_size) const override
Public Member Functions inherited from Comm_Group
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Comm_Group ()
~Comm_Group () override
Destructeur (pour l'instant, rien a faire)
virtual void abort () const =0
virtual void mp_collective_op (const double *x, double *resu, int n, Collective_Op op) const =0
virtual void mp_collective_op (const double *x, double *resu, const Collective_Op *op, int n) const =0
virtual void mp_collective_op (const int *x, int *resu, int n, Collective_Op op) const =0
virtual void mp_collective_op (const int *x, int *resu, const Collective_Op *op, int n) const =0
virtual void barrier (int tag) const =0
int get_new_tag () const
Cette fonction renvoie un nouveau tag de communication pour le groupe.
Effet de bord : incremente le membre group_communication_tag_.
int rank () const
Renvoie le rang du processeur local dans le groupe *this.
ou -1 si je ne suis pas dans le groupe.
int nproc () const
Renvoie le nombre de processeurs dans le groupe *this.
virtual void send_recv_start (const ArrOfInt &send_list, const ArrOfInt &send_size, const char *const *const send_buffers, const ArrOfInt &recv_list, const ArrOfInt &recv_size, char *const *const recv_buffers, TypeHint typehint=CHAR) const =0
virtual void send_recv_finish () const =0
virtual void send (int pe, const void *buffer, int size, int tag) const =0
Envoi bloquant.
virtual void recv (int pe, void *buffer, int size, int tag) const =0
Reception bloquante.
virtual void broadcast (void *buffer, int size, int pe_source) const =0
virtual void all_to_all (const void *src_buffer, void *dest_buffer, int data_size) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Comm_Group_Noparallel & self_cast (Objet_U &)
static const Comm_Group_Noparallel & self_cast (const Objet_U &)
Static Public Member Functions inherited from Comm_Group
static const Type_info * info ()
static Comm_Group & self_cast (Objet_U &)
static const Comm_Group & self_cast (const Objet_U &)
static int check_enabled ()
static void set_check_enabled (int flag)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Comm_Group
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void init_group (const ArrOfInt &pe_list) override
constructeur pour un sous-groupe *‍/
Protected Member Functions inherited from Comm_Group
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Comm_Group (const Comm_Group &)
interdit !
const Comm_Group & operator= (const Comm_Group &)
interdit !
virtual void init_group (const ArrOfInt &pe_list)
Cette fonction doit etre appelee simultanement
par tous les PEs du groupe current_group avec les memes parametres.
Les processeurs de la pe_list sont les rangs dans current_group() des
processeurs du nouveau groupe. Le maitre du groupe est le premier de la liste,
le rang du processeur courant, s'il est dans le groupe est determine par
son rang dans la liste. Il ne doit pas y avoir de doublon.
Cette fonction est appelee par les methodes init_group des classes derivees.
void init_group_trio (int nproc, int rank)
Initialise le groupe_TRUST().
Cette methode est appelee par init_group_trio() des classes derivees.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
template<typename _TYPE_ >
void mp_collective_op_template (const _TYPE_ *x, _TYPE_ *resu, int n, Collective_Op op) const
template<typename _TYPE_ >
void mp_collective_op_template (const _TYPE_ *x, _TYPE_ *resu, const Collective_Op *op, int n) const
Operation collective sur chaque element d'un tableau de taille n.
x, resu et op doivent pointer sur un tableau de taille n.
Pour chaque element x[i] on effectue l'operation op[i] et on met le resultat dans resu[i].
Static Private Attributes
static int sending_ = 0
Additional Inherited Members
Public Types inherited from Comm_Group
enum Collective_Op { COLL_SUM , COLL_MIN , COLL_MAX , COLL_PARTIAL_SUM }
enum TypeHint { CHAR , INT , DOUBLE }
Detailed Description
Definition at line 21 of file Comm_Group_Noparallel.h.
Constructor & Destructor Documentation
Comm_Group_Noparallel() [1/2]
Comm_Group_Noparallel::Comm_Group_Noparallel ()
Definition at line 24 of file Comm_Group_Noparallel.cpp.
{ Comm_Group::init_group_trio(1 /* nproc */, 0 /* rank */); }
References Comm_Group::init_group_trio().
~Comm_Group_Noparallel()
Comm_Group_Noparallel::~Comm_Group_Noparallel () override
Definition at line 25 of file Comm_Group_Noparallel.cpp.
{ }
Comm_Group_Noparallel() [2/2]
Comm_Group_Noparallel::Comm_Group_Noparallel (const ArrOfInt & pe_list)
Member Function Documentation
abort()
void Comm_Group_Noparallel::abort () const override virtual
Implements Comm_Group.
Definition at line 34 of file Comm_Group_Noparallel.cpp.
{ }
all_to_all()
void Comm_Group_Noparallel::all_to_all (const void * src_buffer, void * dest_buffer, int data_size) const override virtual
Implements Comm_Group.
Definition at line 91 of file Comm_Group_Noparallel.cpp.
{
  memcpy(dest_buffer, src_buffer, data_size);
}
barrier()
void Comm_Group_Noparallel::barrier (int tag) const override virtual
Implements Comm_Group.
Definition at line 50 of file Comm_Group_Noparallel.cpp.
{ return; }
broadcast()
void Comm_Group_Noparallel::broadcast (void * buffer, int size, int pe_source) const override virtual
Implements Comm_Group.
Definition at line 89 of file Comm_Group_Noparallel.cpp.
{ return; }
cree_instance()
Objet_U * Comm_Group_Noparallel::cree_instance () static
Definition at line 19 of file Comm_Group_Noparallel.cpp.
duplique()
int Comm_Group_Noparallel::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Comm_Group_Noparallel.cpp.
get_info()
const Type_info * Comm_Group_Noparallel::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Comm_Group.
Definition at line 19 of file Comm_Group_Noparallel.cpp.
info()
const Type_info * Comm_Group_Noparallel::info () static
Definition at line 19 of file Comm_Group_Noparallel.cpp.
init_group()
void Comm_Group_Noparallel::init_group (const ArrOfInt & pe_list) override protected virtual
constructeur pour un sous-groupe *‍/
Reimplemented from Comm_Group.
Definition at line 28 of file Comm_Group_Noparallel.cpp.
{
  assert(pe_list.size_array() == 1);
  Comm_Group::init_group(pe_list);
}
References Comm_Group::init_group(), and TRUSTArray< _TYPE_ >::size_array().
mp_collective_op() [1/4]
void Comm_Group_Noparallel::mp_collective_op (const double * x, double * resu, const Collective_Op * op, int n) const inline override virtual
Implements Comm_Group.
Definition at line 30 of file Comm_Group_Noparallel.h.
{ mp_collective_op_template<double>(x,resu,op,n); }
mp_collective_op() [2/4]
void Comm_Group_Noparallel::mp_collective_op (const double * x, double * resu, int n, Collective_Op op) const inline override virtual
Implements Comm_Group.
Definition at line 29 of file Comm_Group_Noparallel.h.
{ mp_collective_op_template<double>(x,resu,n,op); }
mp_collective_op() [3/4]
void Comm_Group_Noparallel::mp_collective_op (const int * x, int * resu, const Collective_Op * op, int n) const inline override virtual
Implements Comm_Group.
Definition at line 32 of file Comm_Group_Noparallel.h.
{ mp_collective_op_template<int>(x,resu,op,n); }
mp_collective_op() [4/4]
void Comm_Group_Noparallel::mp_collective_op (const int * x, int * resu, int n, Collective_Op op) const inline override virtual
Implements Comm_Group.
Definition at line 31 of file Comm_Group_Noparallel.h.
{ mp_collective_op_template<int>(x,resu,n,op); }
mp_collective_op_template() [1/2]
template<typename _TYPE_ > void Comm_Group_Noparallel::mp_collective_op_template (const _TYPE_ * x, _TYPE_ * resu, const Collective_Op * op, int n) const inline private
Operation collective sur chaque element d'un tableau de taille n.
x, resu et op doivent pointer sur un tableau de taille n.
Pour chaque element x[i] on effectue l'operation op[i] et on met le resultat dans resu[i].
Definition at line 68 of file Comm_Group_Noparallel.h.
  {
    for (int i = 0; i < n; i++)
      {
        if (op[i] != COLL_PARTIAL_SUM) resu[i] = x[i];
        else resu[i] = 0;
      }
  }
References Comm_Group::COLL_PARTIAL_SUM.
mp_collective_op_template() [2/2]
template<typename _TYPE_ > void Comm_Group_Noparallel::mp_collective_op_template (const _TYPE_ * x, _TYPE_ * resu, int n, Collective_Op op) const inline private
Definition at line 56 of file Comm_Group_Noparallel.h.
  {
    if (op != COLL_PARTIAL_SUM)
      for (int i = 0; i < n; i++) resu[i] = x[i];
    else
      for (int i = 0; i < n; i++) resu[i] = 0;
  }
References Comm_Group::COLL_PARTIAL_SUM.
printOn()
Sortie & Comm_Group_Noparallel::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Comm_Group.
Definition at line 36 of file Comm_Group_Noparallel.cpp.
{
  assert(0);
  exit();
  return os;
}
References Process::exit().
readOn()
Entree & Comm_Group_Noparallel::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Comm_Group.
Definition at line 43 of file Comm_Group_Noparallel.cpp.
{
  assert(0);
  exit();
  return is;
}
References Process::exit().
recv()
void Comm_Group_Noparallel::recv (int pe, void * buffer, int size, int tag) const override virtual
Reception bloquante.
Implements Comm_Group.
Definition at line 87 of file Comm_Group_Noparallel.cpp.
{ assert(0); }
reverse_send_recv_list()
int Comm_Group_Noparallel::reverse_send_recv_list (const ArrOfInt & src_list, ArrOfInt & dest_list) const
Definition at line 52 of file Comm_Group_Noparallel.cpp.
{
  assert(src_list.size_array() == 0);
  assert(dest_list.size_array() == 0);
  return 0;
}
References TRUSTArray< _TYPE_ >::size_array().
self_cast() [1/2]
const Comm_Group_Noparallel & Comm_Group_Noparallel::self_cast (const Objet_U & r) static
Definition at line 19 of file Comm_Group_Noparallel.cpp.
self_cast() [2/2]
Comm_Group_Noparallel & Comm_Group_Noparallel::self_cast (Objet_U & r) static
Definition at line 19 of file Comm_Group_Noparallel.cpp.
send()
void Comm_Group_Noparallel::send (int pe, const void * buffer, int size, int tag) const override virtual
Envoi bloquant.
Implements Comm_Group.
Definition at line 85 of file Comm_Group_Noparallel.cpp.
{ assert(0); }
send_recv_finish()
void Comm_Group_Noparallel::send_recv_finish () const override virtual
Implements Comm_Group.
Definition at line 79 of file Comm_Group_Noparallel.cpp.
{
  assert(sending_);
  sending_ = 0;
}
References sending_.
send_recv_start()
void Comm_Group_Noparallel::send_recv_start (const ArrOfInt & send_list, const ArrOfInt & send_size, const char *const *const send_buffers, const ArrOfInt & recv_list, const ArrOfInt & recv_size, char *const *const recv_buffers, TypeHint typehint = CHAR) const override virtual
Implements Comm_Group.
Definition at line 59 of file Comm_Group_Noparallel.cpp.
{
  assert(sending_ == 0);
  if (send_list.size_array() == 1 && send_list[0] == 0 &&
      recv_list.size_array() == 1 && recv_list[0] == 0 &&
      send_size.size_array() == 1 && recv_size.size_array() == 1
      && send_size[0] == recv_size[0])
    {
      memcpy(recv_buffers[0], send_buffers[0], send_size[0]);
    }
  else
    {
      assert(recv_list.size_array() == 0);
      assert(send_list.size_array() == 0);
    }
  sending_ = 1;
  return;
}
References sending_, and TRUSTArray< _TYPE_ >::size_array().
taille_memoire()
unsigned Comm_Group_Noparallel::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Comm_Group_Noparallel.cpp.
Member Data Documentation
info_obj
const Type_info Comm_Group_Noparallel::info_obj static
Definition at line 23 of file Comm_Group_Noparallel.h.
sending_
int Comm_Group_Noparallel::sending_ = 0 static private
Definition at line 51 of file Comm_Group_Noparallel.h.
Referenced by send_recv_finish(), and send_recv_start().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Comm_Group_Noparallel.h
src/Kernel/Utilitaires/Comm_Group_Noparallel.cpp