TRUST: Ref_Zone_Cl_EF Class Reference
Ref_Zone_Cl_EF Class Reference
#include <Ref_Zone_Cl_EF.h>
Public Member Functions
~Ref_Zone_Cl_EF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Zone_Cl_EF ()
Ref_Zone_Cl_EF (const Zone_Cl_EF &)
Ref_Zone_Cl_EF (const Ref_Zone_Cl_EF &)
const Zone_Cl_EF & valeur () const
Zone_Cl_EF & valeur ()
const Zone_Cl_EF * operator-> () const
Zone_Cl_EF * operator-> ()
const Ref_Zone_Cl_EF & operator= (const Zone_Cl_EF &)
const Ref_Zone_Cl_EF & operator= (const Ref_Zone_Cl_EF &)
operator const Zone_Cl_EF & () const
operator Zone_Cl_EF & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Zone_Cl_EF & self_cast (Objet_U &)
static const Ref_Zone_Cl_EF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Zone_Cl_EF * pointeur_
Detailed Description
Definition at line 28 of file Ref_Zone_Cl_EF.h.
Constructor & Destructor Documentation
Ref_Zone_Cl_EF::~Ref_Zone_Cl_EF ()
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
Ref_Zone_Cl_EF::Ref_Zone_Cl_EF ()
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
Ref_Zone_Cl_EF::Ref_Zone_Cl_EF (const Zone_Cl_EF & t)
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
Ref_Zone_Cl_EF::Ref_Zone_Cl_EF (const Ref_Zone_Cl_EF & t)
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
Member Function Documentation
Objet_U * Ref_Zone_Cl_EF::cree_instance () [static]
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
int Ref_Zone_Cl_EF::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
const Type_info * Ref_Zone_Cl_EF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
const Type_info & Ref_Zone_Cl_EF::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
const Type_info * Ref_Zone_Cl_EF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
Ref_Zone_Cl_EF::operator const Zone_Cl_EF & () const
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
Ref_Zone_Cl_EF::operator Zone_Cl_EF & ()
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
const Zone_Cl_EF * Ref_Zone_Cl_EF::operator-> () const [inline]
Definition at line 28 of file Ref_Zone_Cl_EF.h.
Zone_Cl_EF * Ref_Zone_Cl_EF::operator-> () [inline]
Definition at line 28 of file Ref_Zone_Cl_EF.h.
const Ref_Zone_Cl_EF & Ref_Zone_Cl_EF::operator= (const Ref_Zone_Cl_EF & t)
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
const Ref_Zone_Cl_EF & Ref_Zone_Cl_EF::operator= (const Zone_Cl_EF & t)
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
Sortie & Ref_Zone_Cl_EF::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
Entree & Ref_Zone_Cl_EF::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
const Ref_Zone_Cl_EF & Ref_Zone_Cl_EF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
Ref_Zone_Cl_EF & Ref_Zone_Cl_EF::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
void Ref_Zone_Cl_EF::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
unsigned Ref_Zone_Cl_EF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Zone_Cl_EF.cpp.
const Zone_Cl_EF & Ref_Zone_Cl_EF::valeur () const [inline]
Definition at line 28 of file Ref_Zone_Cl_EF.h.
Referenced by Op_Grad_EF::ajouter(), Op_Diff_EF::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Diff_EF::ajouter_contributions_bords(), Solveur_Masse_EF::ajouter_masse(), Op_Diff_EF::ajouter_new(), Op_Diff_EF::ajouter_vectoriel_dim2_nbn_4(), Op_Diff_EF::ajouter_vectoriel_dim3_nbn_8(), Op_Diff_EF::ajouter_vectoriel_gen(), Solveur_Masse_EF::appliquer_impl(), Assembleur_P_EF::assembler_mat(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), Op_Diff_EF::dimensionner(), Op_Conv_EF::dimensionner(), Op_Grad_EF::impr(), Op_Diff_EF::modifier_pour_Cl(), Op_Conv_EF::modifier_pour_Cl(), Assembleur_P_EF::modifier_secmem(), and Assembleur_P_EF::zone_Cl_dis_base().
Zone_Cl_EF & Ref_Zone_Cl_EF::valeur () [inline]
Definition at line 28 of file Ref_Zone_Cl_EF.h.
Member Data Documentation
const Type_info Ref_Zone_Cl_EF::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Zone_Cl_EF.h.
Zone_Cl_EF* Ref_Zone_Cl_EF::pointeur_ [private]
Definition at line 28 of file Ref_Zone_Cl_EF.h.
The documentation for this class was generated from the following files:
src/EF/Zones/Ref_Zone_Cl_EF.h
src/EF/Zones/Ref_Zone_Cl_EF.cpp