TRUST: Iterateur_VDF Class Reference
Iterateur_VDF Class Reference
#include <Iterateur_VDF_base.h>
Public Member Functions
Iterateur_VDF ()
~Iterateur_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int impr (Sortie &os) const
void completer_ ()
void associer (const Zone_VDF &zvdf, const Zone_Cl_VDF &zcl_vdf, const Operateur_base &op)
void associer (const Zone_dis &zdis, const Zone_Cl_dis &zcl_dis, const Operateur_base &op)
void contribuer_au_second_membre (DoubleTab &resu) const
void ajouter_contribution (const DoubleTab &inco, Matrice_Morse &matrice) const
void ajouter_contribution_vitesse (const DoubleTab &inco, Matrice_Morse &matrice) const
void ajouter_contribution_autre_pb (const DoubleTab &inco, Matrice_Morse &matrice, const Cond_lim &la_cl, std::map< int, std::pair< int, int > > &) const
Iterateur_VDF (const Iterateur_VDF_base &)
Evaluateur_VDF & evaluateur ()
const Evaluateur_VDF & evaluateur () const
const Zone_VDF & zone () const
const Zone_Cl_VDF & zone_Cl () const
DoubleTab & ajouter (const DoubleTab &inco, DoubleTab &resu) const
DoubleTab & calculer (const DoubleTab &inco, DoubleTab &resu) const
Public Member Functions inherited from Deriv_Iterateur_VDF_base
~Deriv_Iterateur_VDF_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Iterateur_VDF_base ()
Deriv_Iterateur_VDF_base (const Deriv_Iterateur_VDF_base &)
const Iterateur_VDF_base & valeur () const
Iterateur_VDF_base & valeur ()
const Iterateur_VDF_base * operator-> () const
Iterateur_VDF_base * operator-> ()
const Deriv_Iterateur_VDF_base & operator= (const Iterateur_VDF_base &)
const Deriv_Iterateur_VDF_base & operator= (const Deriv_Iterateur_VDF_base &)
operator const Iterateur_VDF_base & () const
operator Iterateur_VDF_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Iterateur_VDF & self_cast (Objet_U &)
static const Iterateur_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Iterateur_VDF_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Iterateur_VDF_base & self_cast (Objet_U &)
static const Deriv_Iterateur_VDF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Iterateur_VDF_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Type_Cl_VDF type_cl (const Cond_lim &cl) const
Protected Member Functions inherited from Deriv_Iterateur_VDF_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Definition at line 99 of file Iterateur_VDF_base.h.
Constructor & Destructor Documentation
Iterateur_VDF() [1/2]
Iterateur_VDF::Iterateur_VDF ()
Definition at line 20 of file Iterateur_VDF_base.cpp.
~Iterateur_VDF()
Iterateur_VDF::~Iterateur_VDF ()
Definition at line 20 of file Iterateur_VDF_base.cpp.
Iterateur_VDF() [2/2]
Iterateur_VDF::Iterateur_VDF (const Iterateur_VDF_base & Opb) inline
Definition at line 123 of file Iterateur_VDF_base.h.
  : DERIV(Iterateur_VDF_base)()
{
  DERIV(Iterateur_VDF_base)::operator=(Opb);
}
References DERIV, and Deriv_Iterateur_VDF_base::operator=().
Member Function Documentation
ajouter()
DoubleTab & Iterateur_VDF::ajouter (const DoubleTab & inco, DoubleTab & resu) const inline
Definition at line 116 of file Iterateur_VDF_base.h.
{ return valeur().ajouter(inco,resu); }
References Iterateur_VDF_base::ajouter(), and Deriv_Iterateur_VDF_base::valeur().
Referenced by Op_Div_VDF_base::ajouter(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Op_Grad_VDF_base::ajouter_blocs(), and Op_Conv_VDF_base::ajouter_blocs().
ajouter_contribution()
void Iterateur_VDF::ajouter_contribution (const DoubleTab & inco, Matrice_Morse & matrice) const inline
Definition at line 108 of file Iterateur_VDF_base.h.
{ valeur().ajouter_contribution(inco, matrice); }
References Iterateur_VDF_base::ajouter_contribution(), and Deriv_Iterateur_VDF_base::valeur().
Referenced by Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), and Op_Conv_VDF_base::ajouter_blocs().
ajouter_contribution_autre_pb()
void Iterateur_VDF::ajouter_contribution_autre_pb (const DoubleTab & inco, Matrice_Morse & matrice, const Cond_lim & la_cl, std::map< int, std::pair< int, int > > & f2e) const inline
Definition at line 129 of file Iterateur_VDF_base.h.
{
  return valeur().ajouter_contribution_autre_pb(inco, matrice, la_cl, f2e);
}
References Iterateur_VDF_base::ajouter_contribution_autre_pb(), and Deriv_Iterateur_VDF_base::valeur().
Referenced by Op_Diff_VDF_Elem_base::contribuer_termes_croises().
ajouter_contribution_vitesse()
void Iterateur_VDF::ajouter_contribution_vitesse (const DoubleTab & inco, Matrice_Morse & matrice) const inline
Definition at line 109 of file Iterateur_VDF_base.h.
{ valeur().ajouter_contribution_vitesse(inco, matrice); }
References Iterateur_VDF_base::ajouter_contribution_vitesse(), and Deriv_Iterateur_VDF_base::valeur().
Referenced by Op_Conv_VDF_base::contribuer_bloc_vitesse().
associer() [1/2]
void Iterateur_VDF::associer (const Zone_dis & zdis, const Zone_Cl_dis & zcl_dis, const Operateur_base & op) inline
Definition at line 106 of file Iterateur_VDF_base.h.
{ valeur().associer(zdis,zcl_dis,op); }
References Iterateur_VDF_base::associer(), and Deriv_Iterateur_VDF_base::valeur().
associer() [2/2]
void Iterateur_VDF::associer (const Zone_VDF & zvdf, const Zone_Cl_VDF & zcl_vdf, const Operateur_base & op) inline
Definition at line 105 of file Iterateur_VDF_base.h.
{ valeur().associer(zvdf,zcl_vdf,op); }
References Iterateur_VDF_base::associer(), and Deriv_Iterateur_VDF_base::valeur().
Referenced by Op_Div_VDF_Elem::associer(), Op_Conv_VDF< OP_TYPE >::associer_(), and Op_Diff_Dift_VDF< OP_TYPE >::associer_().
calculer()
DoubleTab & Iterateur_VDF::calculer (const DoubleTab & inco, DoubleTab & resu) const inline
Definition at line 117 of file Iterateur_VDF_base.h.
{ return valeur().calculer(inco, resu); }
References Iterateur_VDF_base::calculer(), and Deriv_Iterateur_VDF_base::valeur().
Referenced by Op_Conv_VDF_base::calculer(), Op_Div_VDF_base::calculer(), and Op_Grad_VDF_base::calculer().
completer_()
void Iterateur_VDF::completer_ () inline
Definition at line 104 of file Iterateur_VDF_base.h.
{ valeur().completer_(); }
References Iterateur_VDF_base::completer_(), and Deriv_Iterateur_VDF_base::valeur().
Referenced by Op_Conv_VDF_base::completer(), Op_Diff_VDF_base::completer(), Op_Div_VDF_base::completer(), and Op_Grad_VDF_base::completer().
contribuer_au_second_membre()
void Iterateur_VDF::contribuer_au_second_membre (DoubleTab & resu) const inline
Definition at line 107 of file Iterateur_VDF_base.h.
{ valeur().contribuer_au_second_membre(resu); }
References Iterateur_VDF_base::contribuer_au_second_membre(), and Deriv_Iterateur_VDF_base::valeur().
Referenced by Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), and Op_Conv_VDF_base::contribuer_au_second_membre().
cree_instance()
Objet_U * Iterateur_VDF::cree_instance () static
Definition at line 20 of file Iterateur_VDF_base.cpp.
duplique()
int Iterateur_VDF::duplique () const override virtual
Reimplemented from Deriv_Iterateur_VDF_base.
Definition at line 20 of file Iterateur_VDF_base.cpp.
evaluateur() [1/2]
Evaluateur_VDF & Iterateur_VDF::evaluateur () inline
Definition at line 112 of file Iterateur_VDF_base.h.
{ return valeur().evaluateur(); }
References Iterateur_VDF_base::evaluateur(), and Deriv_Iterateur_VDF_base::valeur().
Referenced by Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Op_Div_VDF_Elem::associer(), Op_Conv_VDF< OP_TYPE >::associer_(), Op_Diff_Dift_VDF< OP_TYPE >::associer_(), Op_Diff_Dift_VDF< OP_TYPE >::associer_diffusivite_impl(), Op_Diff_Dift_VDF< OP_TYPE >::associer_diffusivite_turbulente_impl(), Op_Diff_Dift_VDF< OP_TYPE >::associer_loipar_impl(), Op_Conv_VDF< OP_TYPE >::associer_vitesse_impl(), Op_Diff_Dift_VDF< OP_TYPE >::completer_impl(), Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), Op_Diff_Dift_VDF< OP_TYPE >::diffusivite_impl(), Op_Diff_Dift_VDF< OP_TYPE >::mettre_a_jour_impl(), and Op_Conv_VDF< OP_TYPE >::vitesse_impl().
evaluateur() [2/2]
const Evaluateur_VDF & Iterateur_VDF::evaluateur () const inline
Definition at line 113 of file Iterateur_VDF_base.h.
{ return valeur().evaluateur(); }
References Iterateur_VDF_base::evaluateur(), and Deriv_Iterateur_VDF_base::valeur().
get_info()
const Type_info * Iterateur_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Iterateur_VDF_base.
Definition at line 20 of file Iterateur_VDF_base.cpp.
impr()
int Iterateur_VDF::impr (Sortie & os) const inline
Definition at line 103 of file Iterateur_VDF_base.h.
{ return valeur().impr(os); }
References Iterateur_VDF_base::impr(), and Deriv_Iterateur_VDF_base::valeur().
Referenced by Op_Conv_VDF_base::impr(), Op_Diff_VDF_base::impr(), Op_Div_VDF_base::impr(), and Op_Grad_VDF_base::impr().
info()
const Type_info * Iterateur_VDF::info () static
Definition at line 20 of file Iterateur_VDF_base.cpp.
printOn()
Sortie & Iterateur_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Iterateur_VDF_base.
Definition at line 57 of file Iterateur_VDF_base.cpp.
{ return s << que_suis_je() ; }
References Objet_U::que_suis_je().
readOn()
Entree & Iterateur_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Iterateur_VDF_base.
Definition at line 27 of file Iterateur_VDF_base.cpp.
{ return s ; }
self_cast() [1/2]
const Iterateur_VDF & Iterateur_VDF::self_cast (const Objet_U & r) static
Definition at line 20 of file Iterateur_VDF_base.cpp.
self_cast() [2/2]
Iterateur_VDF & Iterateur_VDF::self_cast (Objet_U & r) static
Definition at line 20 of file Iterateur_VDF_base.cpp.
taille_memoire()
unsigned Iterateur_VDF::taille_memoire () const override virtual
Reimplemented from Deriv_Iterateur_VDF_base.
Definition at line 20 of file Iterateur_VDF_base.cpp.
type_cl()
Type_Cl_VDF Iterateur_VDF::type_cl (const Cond_lim & cl) const inline protected
Definition at line 120 of file Iterateur_VDF_base.h.
{ return valeur().type_cl(cl); }
References Iterateur_VDF_base::type_cl(), and Deriv_Iterateur_VDF_base::valeur().
zone()
const Zone_VDF & Iterateur_VDF::zone () const inline
Definition at line 114 of file Iterateur_VDF_base.h.
{ return valeur().zone(); }
References Deriv_Iterateur_VDF_base::valeur(), and Iterateur_VDF_base::zone().
Referenced by Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Op_Dift_VDF_Face_base::calculer_borne_locale(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi(), Op_Conv_VDF_base::calculer_pour_post(), Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Diff_VDF_Face_base::dimensionner_blocs(), Op_Dift_VDF_Elem_base::dimensionner_blocs(), Op_Dift_VDF_Face_base::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Op_Diff_VDF_base::init_op_ext(), Op_Diff_VDF_Elem_base::modifier_pour_Cl(), Op_Diff_VDF_Face_base::modifier_pour_Cl(), Op_Dift_VDF_Elem_base::modifier_pour_Cl(), and Op_Dift_VDF_Face_base::modifier_pour_Cl().
zone_Cl()
const Zone_Cl_VDF & Iterateur_VDF::zone_Cl () const inline
Definition at line 115 of file Iterateur_VDF_base.h.
{ return valeur().zone_Cl(); }
References Deriv_Iterateur_VDF_base::valeur(), and Iterateur_VDF_base::zone_Cl().
Referenced by Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_pour_post(), Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Diff_VDF_Face_base::dimensionner_blocs(), Op_Dift_VDF_Elem_base::dimensionner_blocs(), Op_Dift_VDF_Face_base::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Op_Diff_VDF_base::init_op_ext(), Op_Diff_VDF_Elem_base::modifier_pour_Cl(), Op_Diff_VDF_Face_base::modifier_pour_Cl(), Op_Dift_VDF_Elem_base::modifier_pour_Cl(), and Op_Dift_VDF_Face_base::modifier_pour_Cl().
Member Data Documentation
info_obj
const Type_info Iterateur_VDF::info_obj static
Definition at line 101 of file Iterateur_VDF_base.h.
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Iterateurs/Iterateur_VDF_base.h
src/VDF/Operateurs/Iterateurs/Iterateur_VDF_base.cpp