TRUST: liste Class Reference
liste Class Reference
Les classes liste et liste_curseur representent
une liste de Deriv<Objet_U> et un curseur associe.
List<T> et List_Curseur<T> en heritent.
#include <liste.h>
Public Member Functions
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
liste ()
Constructeur par defaut
Construit une liste vide.
liste (const liste &)
Constructeur
Ajoute les elements contenus dans la liste passe en parametre.
liste (const Objet_U &)
Constructeur
Construit une liste singleton.
virtual ~liste ()
Destructeur de liste.
int size () const
Renvoie la taille de la liste
Une liste vide est de taille nulle.
int rang (const char *const) const
Renvoie le rang d'une chaine de caracteres contenue dans la liste
Recherche un Objet_U de Nom ch.
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
void suppr (const char *const)
Supprime l'Objet de Nom ch contenu dans la liste.
int est_vide () const
Teste si la liste est vide.
int est_dernier () const
Teste si la liste comporte des elements suivants ou non.
Retourne 1 si la liste est vide.
void vide ()
Vide la liste.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static liste & self_cast (Objet_U &)
static const liste & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture d'une liste sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'une liste sur un flot d'entree.
Objet_U & operator() (int)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Objet_U & operator() (int) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Objet_U & operator() (const Nom &)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Objet_U & operator() (const Nom &) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Objet_U & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Objet_U & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
liste & operator+= (const Objet_U &)
Ajoute un Objet_U a la fin de la liste.
liste & operator+= (const liste &)
Ajoute une list d'Objet_U a la fin de la liste.
liste & operator-= (const Objet_U &)
Supprime un Objet_U de la liste
Affiche un message d'erreur si l'objet n'est pas trouve.
const liste & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
liste & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
Objet_U * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
const Objet_U * operator-> () const
Retourne un pointeur sur l'Objet_U premier element de la liste.
Objet_U & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Objet_U & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Objet_U & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Objet_U & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Objet_U & add (const Objet_U &)
Ajout d'un Objet_U a la liste.
Objet_U & add_deplace (DerObjU &)
Ajout d'un Objet_U a la liste
to_add est libere en sortie.
Objet_U & inserer (const Objet_U &)
Insertion d'un Objet_U dans la liste.
liste & add (const liste &)
Ajout d'une liste a la liste.
liste & inserer (const liste &)
Insertion d'une liste
NON CODE - SORT SYSTEMATIQUEMENT EN ERREUR.
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Objet_U & add_if_not (const Objet_U &)
Ajout d'un Objet_U a la liste ssi il n'existe pas deja.
liste & search (const Objet_U &) const
Recherche d'un Objet_U dans la liste.
liste & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
int contient (const Objet_U &) const
Verifie si un Objet_U appartient ou non a la liste.
int rang (const Objet_U &) const
Renvoie le rang d'un Objet_U dans la liste.
void suppr (const Objet_U &)
Supprime un Objet_U contenu dans la liste.
liste & operator= (const liste &)
Operateur d'affectation de liste.
const liste & dernier () const
Renvoie le dernier element de la liste.
liste & dernier ()
Renvoie le dernier element de la liste.
Protected Attributes
DerObjU data
liste * suivant_
Friends
class liste_curseur
int operator== (const liste &, const liste &)
Operateur de comparaison de deux listes
La comparaison repose sur l'egalite des Objet_U des 2 listes.
int operator!= (const liste &, const liste &)
Operateur de difference entre deux listes
La comparaison repose sur l'egalite des Objet_U des 2 listes.
Detailed Description
Les classes liste et liste_curseur representent
une liste de Deriv<Objet_U> et un curseur associe.
List<T> et List_Curseur<T> en heritent.
Definition at line 39 of file liste.h.
Constructor & Destructor Documentation
liste::liste () [inline]
Constructeur par defaut
Construit une liste vide.
Definition at line 140 of file liste.h.
References suivant_.
Referenced by add(), add_deplace(), and inserer().
{
  suivant_=this;
}
liste::liste (const liste & a_list) [inline]
Constructeur
Ajoute les elements contenus dans la liste passe en parametre.
Definition at line 179 of file liste.h.
References add(), and suivant_.
                                      : Objet_U(a_list)
{
  suivant_=this;
  add(a_list);
}
liste::liste (const Objet_U & ob) [inline]
Constructeur
Construit une liste singleton.
Definition at line 160 of file liste.h.
                                     : Objet_U(ob),data(ob), suivant_(0)
{
}
liste::~liste () [virtual]
Destructeur de liste.
Definition at line 203 of file liste.cpp.
References suivant_, and vide().
{
  vide();
  suivant_=0;
}
Member Function Documentation
Objet_U & liste::add (const Objet_U & to_add) [protected]
Ajout d'un Objet_U a la liste.
Returns:
Objet_U&
Signification: L'Objet_U ajoute
Contraintes:
Definition at line 440 of file liste.cpp.
References add(), Cerr, data, dernier(), est_dernier(), est_vide(), Process::exit(), finl, liste(), suivant_, and valeur().
Referenced by add(), add_if_not(), inserer(), liste(), operator+=(), operator=(), and readOn().
{
  if( est_vide())
    {
      data=to_add;
      suivant_=0;
      return valeur();
    }
  else
    {
      if(est_dernier())
        {
          suivant_=new liste(to_add);
          if(!suivant_)
            {
              Cerr << "Run out of memory " << finl;
              exit();
            }
          return suivant_->valeur();
        }
      else
        return dernier().add(to_add);
    }
}
liste & liste::add (const liste & list) [protected]
Ajout d'une liste a la liste.
Returns:
liste&
Signification: la liste comportant tous les elements
Contraintes:
Definition at line 479 of file liste.cpp.
References add(), and liste_curseur::valeur().
{
  liste_curseur curseur(list);
  while(curseur)
    {
      Objet_U& to_add=curseur.valeur();
      add(to_add);
      ++curseur;
    }
  return *this;
}
Objet_U & liste::add_deplace (DerObjU & to_add) [protected]
Ajout d'un Objet_U a la liste
to_add est libere en sortie.
Definition at line 398 of file liste.cpp.
References add_deplace(), Cerr, data, Deriv_Objet_U::deplace(), dernier(), est_dernier(), est_vide(), Process::exit(), finl, liste(), suivant_, and valeur().
Referenced by add_deplace(), and Interprete_bloc::ajouter().
{
  if( est_vide())
    {
      data.deplace(to_add);
      suivant_=0;
      return valeur();
    }
  else
    {
      if(est_dernier())
        {
          liste* liste_ptr=new liste;
          if(!liste_ptr)
            {
              Cerr << "Run out of memory " << finl;
              exit();
            }
          liste_ptr->add_deplace(to_add);
          suivant_=liste_ptr;
          return suivant_->valeur();
        }
      else
        return dernier().add_deplace(to_add);
    }
}
Objet_U & liste::add_if_not (const Objet_U & to_add) [protected]
Ajout d'un Objet_U a la liste ssi il n'existe pas deja.
Returns:
Objet_U&
Signification: L'Objet_U existant deja dans la liste ou celui ajoute
Contraintes:
Definition at line 505 of file liste.cpp.
References add(), Cerr, data, est_dernier(), est_vide(), finl, liste_curseur::list(), suivant_, liste_curseur::valeur(), and valeur().
{
  if( est_vide())
    {
      data=to_add;
      suivant_=0;
      return valeur();
    }
  else
    {
      liste_curseur curseur=*this;
      while(curseur)
        {
          if(curseur.valeur()==to_add)
            return curseur.valeur();
          if(curseur.list().est_dernier())
            return(curseur.list().add(to_add));
          ++curseur;
        }
    }
// On ne devrait pas passer la :
  Cerr << "Error in a list for add_if_not " << finl;
  return valeur();
}
int liste::contient (const char * const ch) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
Returns:
int
Signification: 1 si la liste contient un Objet_U de Nom ch, 0 sinon
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 629 of file liste.cpp.
{
  Nom nom(ch);
  liste_curseur curseur=*this;
  while(curseur)
    {
      if(curseur->le_nom()==nom)
        return 1;
      ++curseur;
    }
  return 0;
}
int liste::contient (const Objet_U & obj) const [protected]
Verifie si un Objet_U appartient ou non a la liste.
Returns:
int
Signification: 1 si la liste contient l'Objet_U obj, 0 sinon
Contraintes:
Definition at line 603 of file liste.cpp.
References liste_curseur::valeur().
{
  liste_curseur curseur=*this;
  while(curseur)
    {
      if(curseur.valeur()==obj)
        return 1;
      ++curseur;
    }
  return 0;
}
Objet_U * liste::cree_instance () [static]
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, Champs_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, Liste_Champ_Generique, List_Deriv_Postraitement_base, Postraitements, List_Sonde, List_Champ, Sondes, List_Sonde_Int, Sondes_Int, List_Source, Sources, List_Bord, Bords, List_Domaine, List_Faces_Interne, Faces_Internes, List_Ref_Domaine, List_Joint, Joints, List_Ref_Sous_Zone, List_Raccord, Raccords, List_Ref_Frontiere, List_Zone, Zones, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, Operateurs_Statistique_tps, Interprete_bloc, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 25 of file liste.cpp.
const liste & liste::dernier () const [protected]
Renvoie le dernier element de la liste.
Returns:
const liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 149 of file liste.cpp.
References est_dernier(), and liste_curseur::list().
Referenced by add(), and add_deplace().
{
  if (est_dernier()) return *this;
  liste_curseur curseur(*this);
  while(curseur)
    if (curseur.list().est_dernier()) break;
    else ++curseur;
  return curseur.list();
}
liste & liste::dernier () [protected]
Renvoie le dernier element de la liste.
Returns:
liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 124 of file liste.cpp.
References est_dernier(), and liste_curseur::list().
{
  if (est_dernier()) return *this;
  liste_curseur curseur(*this);
  while(curseur)
    if (curseur.list().est_dernier()) break;
    else ++curseur;
  return curseur.list();
}
int liste::duplique () const [virtual]
Implements Objet_U.
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, Champs_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, Liste_Champ_Generique, List_Deriv_Postraitement_base, Postraitements, List_Sonde, List_Champ, Sondes, List_Sonde_Int, Sondes_Int, List_Source, Sources, List_Bord, Bords, List_Domaine, List_Faces_Interne, Faces_Internes, List_Ref_Domaine, List_Joint, Joints, List_Ref_Sous_Zone, List_Raccord, Raccords, List_Ref_Frontiere, List_Zone, Zones, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, Operateurs_Statistique_tps, Interprete_bloc, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 25 of file liste.cpp.
int liste::est_dernier () const [inline]
Teste si la liste comporte des elements suivants ou non.
Retourne 1 si la liste est vide.
Returns:
int
Signification: 1 si la liste est le dernier element d'une liste chainee
Contraintes:
Definition at line 219 of file liste.h.
References est_vide(), and suivant_.
Referenced by add(), add_deplace(), add_if_not(), dernier(), inserer(), liste_curseur::operator++(), printOn(), size(), and supprimer().
{
  return ( est_vide() || (!suivant_) );
}
int liste::est_vide () const [inline]
Teste si la liste est vide.
Returns:
int
Signification: 1 si le liste est vide, 0 sinon
Contraintes:
Definition at line 199 of file liste.h.
References suivant_.
Referenced by add(), add_deplace(), add_if_not(), est_dernier(), Op_VEF_Face::impr(), T_It_VDF_Face< _TYPE_ >::impr(), Op_Diff_PolyMAC_base::impr(), T_It_PolyMAC_Elem< _TYPE_ >::impr(), Op_EF_base::impr(), Op_Diff_CoviMAC_base::impr(), inserer(), Lire_Tgrid::interpreter_(), liste_curseur::liste_curseur(), printOn(), size(), supprimer(), and vide().
{
  return suivant_==this;
}
const Type_info * liste::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, Champs_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, Liste_Champ_Generique, List_Deriv_Postraitement_base, Postraitements, List_Sonde, List_Champ, Sondes, List_Sonde_Int, Sondes_Int, List_Source, Sources, List_Bord, Bords, List_Domaine, List_Faces_Interne, Faces_Internes, List_Ref_Domaine, List_Joint, Joints, List_Ref_Sous_Zone, List_Raccord, Raccords, List_Ref_Frontiere, List_Zone, Zones, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, Operateurs_Statistique_tps, Interprete_bloc, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 25 of file liste.cpp.
const Type_info * liste::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, Champs_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, Liste_Champ_Generique, List_Deriv_Postraitement_base, Postraitements, List_Sonde, List_Champ, Sondes, List_Sonde_Int, Sondes_Int, List_Source, Sources, List_Bord, Bords, List_Domaine, List_Faces_Interne, Faces_Internes, List_Ref_Domaine, List_Joint, Joints, List_Ref_Sous_Zone, List_Raccord, Raccords, List_Ref_Frontiere, List_Zone, Zones, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, Operateurs_Statistique_tps, Interprete_bloc, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 25 of file liste.cpp.
Objet_U & liste::inserer (const Objet_U & ob) [protected]
Insertion d'un Objet_U dans la liste.
Returns:
Objet_U&
Signification: L'Objet_U insere
Contraintes:
Definition at line 829 of file liste.cpp.
References add(), est_dernier(), est_vide(), liste(), next(), suivant_, and valeur().
{
  if (est_vide() || est_dernier())
    return add(ob);
  else
    {
      liste* next=suivant_;
      suivant_=new liste(ob);
      suivant_->suivant_=next;
      return suivant_->valeur();
    }
}
liste & liste::inserer (const liste &) [protected]
Insertion d'une liste
NON CODE - SORT SYSTEMATIQUEMENT EN ERREUR.
Definition at line 858 of file liste.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "liste::inserer(const liste&) : not coded !" << finl;
  exit();
  return *this;
}
Objet_U & liste::operator() (int i) [inline, protected]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 239 of file liste.h.
References operator[]().
{
  return operator[](i);
}
const Objet_U & liste::operator() (int i) const [inline, protected]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 259 of file liste.h.
References operator[]().
{
  return operator[](i);
}
Objet_U & liste::operator() (const Nom & nom) [inline, protected]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 279 of file liste.h.
References operator[]().
{
  return operator[](nom);
}
const Objet_U & liste::operator() (const Nom & nom) const [inline, protected]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 299 of file liste.h.
References operator[]().
{
  return operator[](nom);
}
liste & liste::operator+= (const Objet_U & ob) [inline, protected]
Ajoute un Objet_U a la fin de la liste.
Definition at line 356 of file liste.h.
References add().
{
  add(ob);
  return *this;
}
liste & liste::operator+= (const liste & a_list) [inline, protected]
Ajoute une list d'Objet_U a la fin de la liste.
Definition at line 376 of file liste.h.
References add().
{
  return add(a_list);
}
liste & liste::operator-= (const Objet_U & ob) [inline, protected]
Supprime un Objet_U de la liste
Affiche un message d'erreur si l'objet n'est pas trouve.
Definition at line 396 of file liste.h.
References suppr().
{
  suppr(ob);
  return *this;
}
Objet_U * liste::operator-> () [inline, protected]
Retourne un pointeur sur l'Objet_U premier element de la liste.
Returns:
Objet_U*
Signification: pointeur sur l'Objet_U premier element de la liste
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 455 of file liste.h.
References valeur().
{
  return(&(valeur()));
}
const Objet_U * liste::operator-> () const [inline, protected]
Retourne un pointeur sur l'Objet_U premier element de la liste.
Returns:
const Objet_U*
Signification: pointeur sur l'Objet_U premier element de la liste
Contraintes:
Definition at line 475 of file liste.h.
References valeur().
{
  return(&(valeur()));
}
liste & liste::operator= (const liste & list) [protected]
Operateur d'affectation de liste.
Definition at line 386 of file liste.cpp.
References add(), and vide().
{
  vide();
  add(list);
  return *this;
}
const Objet_U & liste::operator[] (const Nom & nom) const [protected]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
const Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 349 of file liste.cpp.
References Cerr, Process::exit(), finl, and liste_curseur::valeur().
{
  liste_curseur curseur(*this);
  while(curseur)
    if( (curseur->le_nom()) == nom) break;
    else ++curseur;
  if(!curseur)
    {
      Cerr << "We have not found an object with name " << nom << finl;
      Cerr << "The known names are : ";
      liste_curseur curseur2(*this);
      while(curseur2)
        {
          Cerr << curseur2->le_nom() << " ; " ;
          ++curseur2;
        }
      exit();
    }
  return curseur.valeur();
}
Objet_U & liste::operator[] (const Nom & nom) [protected]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 312 of file liste.cpp.
References Cerr, Process::exit(), finl, and liste_curseur::valeur().
{
  liste_curseur curseur(*this);
  while(curseur)
    if( (curseur->le_nom()) == nom) break;
    else ++curseur;
  if(!curseur)
    {
      Cerr << "We have not found an object with name " << nom << finl;
      Cerr << "The known names are : " << finl;
      liste_curseur curseur2(*this);
      while(curseur2)
        {
          Cerr << curseur2->le_nom() << " ; " ;
          ++curseur2;
        }
      Cerr << finl;
      exit();
    }
  return curseur.valeur();
}
const Objet_U & liste::operator[] (int i) const [protected]
Operateur d'acces au ieme element de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 284 of file liste.cpp.
References Cerr, Process::exit(), finl, Objet_U::que_suis_je(), and liste_curseur::valeur().
{
  liste_curseur curseur(*this);
  while(curseur && i--)
    ++curseur;
  if(i!=-1)
    {
      Cerr << que_suis_je() << " : overflow of list " << finl;
      assert(i==-1);
      exit();
    }
  return curseur.valeur();
}
Objet_U & liste::operator[] (int i) [protected]
Operateur d'acces au ieme element de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 251 of file liste.cpp.
References Cerr, Process::exit(), finl, Objet_U::que_suis_je(), and liste_curseur::valeur().
Referenced by Interprete_bloc::objet_local(), and operator()().
{
  liste_curseur curseur(*this);
  if (!curseur)
    {
      Cerr << que_suis_je() << " : empty list !" << finl;
      exit();
    }
  while(curseur && i--)
    ++curseur;
  if(i!=-1)
    {
      Cerr << que_suis_je() << " : overflow of list " << finl;
      assert(i==-1);
      exit();
    }
  return curseur.valeur();
}
Sortie & liste::printOn (Sortie & os) const [protected, virtual]
Ecriture d'une liste sur un flot de sortie.
Returns:
Sortie&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, Champs_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, Liste_Champ_Generique, List_Deriv_Postraitement_base, Postraitements, List_Sonde, List_Champ, Sondes, List_Sonde_Int, Sondes_Int, List_Source, Sources, List_Bord, Bords, List_Domaine, List_Faces_Interne, Faces_Internes, List_Ref_Domaine, List_Joint, Joints, List_Ref_Sous_Zone, List_Raccord, Raccords, List_Ref_Frontiere, List_Zone, Zones, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, Operateurs_Statistique_tps, Interprete_bloc, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 87 of file liste.cpp.
References est_dernier(), est_vide(), finl, liste_curseur::list(), and liste_curseur::valeur().
{
  Nom accouverte="{";
  Nom accfermee="}";
  Nom virgule=",";
  Nom blanc=" ";
  if (est_vide()) os << "vide" << finl;
  else
    {
      os << accouverte << finl;
      liste_curseur curseur(*this);
      while(curseur)
        {
          os << curseur.valeur() ;
          if (!curseur.list().est_dernier())
            os << blanc << virgule << finl;
          ++curseur;
        }
      os <<finl << accfermee << finl;
    }
  return os;
}
int liste::rang (const char * const ch) const
Renvoie le rang d'une chaine de caracteres contenue dans la liste
Recherche un Objet_U de Nom ch.
Returns:
int
Signification: le rang de l'Objet_U trouve ou -1 si aucun ne correspond
Contraintes:
Definition at line 685 of file liste.cpp.
{
  Nom nom(ch);
  liste_curseur curseur=*this;
  int i=0;
  while(curseur)
    {
      if(curseur->le_nom()==nom)
        return i;
      ++i;
      ++curseur;
    }
  return -1;
}
int liste::rang (const Objet_U & obj) const [protected]
Renvoie le rang d'un Objet_U dans la liste.
Returns:
int
Signification: le rang de L'Objet_U dans la liste, -1 si l'Objet_U n'est pas dans la liste
Contraintes:
Definition at line 656 of file liste.cpp.
References liste_curseur::valeur().
{
  liste_curseur curseur=*this;
  int i=0;
  while(curseur)
    {
      if(curseur.valeur()==obj)
        return i;
      ++i;
      ++curseur;
    }
  return -1;
}
Entree & liste::readOn (Entree & is) [protected, virtual]
Lecture d'une liste sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, Champs_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, Liste_Champ_Generique, List_Deriv_Postraitement_base, Postraitements, List_Sonde, List_Champ, Sondes, List_Sonde_Int, Sondes_Int, List_Source, Sources, List_Bord, Bords, List_Domaine, List_Faces_Interne, Faces_Internes, List_Ref_Domaine, List_Joint, Joints, List_Ref_Sous_Zone, List_Raccord, Raccords, List_Ref_Frontiere, List_Zone, Zones, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, Operateurs_Statistique_tps, Interprete_bloc, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 41 of file liste.cpp.
References add(), Cerr, Process::exit(), finl, and vide().
{
  vide();
  Nom accouverte="{";
  Nom accfermee="}";
  Nom virgule=",";
  Nom nom;
  is >> nom;
  if(nom ==(const char*)"vide") return is;
  if(nom!=accouverte)
    {
      Cerr << "We expected a { and not " << nom << finl;
      exit();
    }
  while(nom!=accfermee)
    {
      is >> nom;
      if (nom !=  accfermee)
        {
          add(nom);
          is >> nom;
        }
      if((nom!=accfermee)&&(nom!=virgule))
        {
          Cerr << "We expected a } or a , and not " << nom << finl;
          exit();
        }
    }
  return is;
}
liste & liste::search (const Objet_U & obj) const [protected]
Recherche d'un Objet_U dans la liste.
Returns:
liste&
Signification: L'element trouve dans la liste
Contraintes:
Definition at line 545 of file liste.cpp.
References Cerr, Process::exit(), finl, liste_curseur::list(), suivant_, and liste_curseur::valeur().
{
  liste_curseur curseur=*this;
  while(curseur)
    {
      if(curseur.valeur()==obj)
        return curseur.list();
      ++curseur;
    }
  Cerr << "We have not found an object "<< obj <<" !" << finl;
  exit();
  return *suivant_;
}
liste & liste::search (const char * const ch) const [protected]
Recherche d'un Objet_U de Nom ch dans la liste.
Returns:
liste&
Signification: L'element de la liste trouve
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 574 of file liste.cpp.
References Cerr, Process::exit(), finl, liste_curseur::list(), and suivant_.
{
  Nom nom(ch);
  liste_curseur curseur=*this;
  while(curseur)
    {
      if(curseur->le_nom()==nom)
        return curseur.list();
      ++curseur;
    }
  Cerr << "We have not found an object with name "<< nom <<" !" << finl;
  exit();
  return *suivant_;
}
liste & liste::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, Champs_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, Liste_Champ_Generique, List_Deriv_Postraitement_base, Postraitements, List_Sonde, List_Champ, Sondes, List_Sonde_Int, Sondes_Int, List_Source, Sources, List_Bord, Bords, List_Domaine, List_Faces_Interne, Faces_Internes, List_Ref_Domaine, List_Joint, Joints, List_Ref_Sous_Zone, List_Raccord, Raccords, List_Ref_Frontiere, List_Zone, Zones, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, Operateurs_Statistique_tps, Interprete_bloc, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 25 of file liste.cpp.
const liste & liste::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, Champs_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, Liste_Champ_Generique, List_Deriv_Postraitement_base, Postraitements, List_Sonde, List_Champ, Sondes, List_Sonde_Int, Sondes_Int, List_Source, Sources, List_Bord, Bords, List_Domaine, List_Faces_Interne, Faces_Internes, List_Ref_Domaine, List_Joint, Joints, List_Ref_Sous_Zone, List_Raccord, Raccords, List_Ref_Frontiere, List_Zone, Zones, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, Operateurs_Statistique_tps, Interprete_bloc, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 25 of file liste.cpp.
int liste::size () const
Renvoie la taille de la liste
Une liste vide est de taille nulle.
Returns:
int
Signification: nombre d'elements de la liste
Contraintes:
Definition at line 175 of file liste.cpp.
References compteur, est_dernier(), est_vide(), and suivant_.
Referenced by add_sommets_communs(), Parser::addFunc(), Probleme_base::addInputField(), Param::ajouter_condition(), ajouter_joint(), Scatter::ajouter_joints(), ajouter_joints(), Navier_Stokes_std::assembler_blocs(), Milieu_composite::associer_equation(), auto_build_joints(), Echange_contact_Correlation_VEF::calculer_CL(), Echange_contact_Correlation_VDF::calculer_CL(), Milieu_composite::calculer_energie_interne(), Milieu_composite::calculer_enthalpie(), Scatter::calculer_espace_distant(), calculer_espace_distant_item(), Loi_Etat_Multi_GP_QC::calculer_masse_molaire(), Milieu_composite::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_mu_wilke(), Loi_Etat_Multi_GP_QC::calculer_mu_wilke(), Scatter::calculer_nb_items_virtuels(), Chimie::calculer_pas_de_temps(), Scatter::calculer_renum_items_communs(), Loi_Etat_Multi_GP_WC::calculer_tab_Cp(), Loi_Etat_Multi_GP_QC::calculer_tab_Cp(), Param::check(), Scatter::check_consistancy_remote_items(), Milieu_composite::check_unknown_range(), Zone::check_zone(), Chimie::completer(), Equation_base::completer(), Champ_Gen_de_Champs_Gen::completer(), Zones::comprimer(), Joints::comprimer(), Scatter::construire_correspondance_items_par_coordonnees(), DomaineCutter::construire_faces_joints_ssdom(), Scatter::construire_md_vector(), Postraitement::creer_champ_post_med(), Faces_builder::creer_faces_reeles(), Param::dictionnaire(), Param::dictionnaire_param(), Milieu_composite::discretiser(), Chimie::discretiser(), Postraiter_domaine::ecrire(), DomaineCutter::ecrire_zones(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Chimie::get_champ(), Moyenne_volumique::get_champ(), Objet_a_lire::get_names_message(), Champ_Gen_de_Champs_Gen::get_nb_sources(), Chimie::get_noms_champs_postraitables(), Champ_Gen_de_Champs_Gen::get_set_source(), Champ_Gen_de_Champs_Gen::get_source(), Param::get_value(), Probleme_base::getInputFieldsNames(), Probleme_base::getOutputFieldsNames(), Equation_base::Gradient_conjugue_diff_impl(), Equation_base::has_interface_blocs(), Parser::init_parser(), Echange_contact_Correlation_VDF::init_tab_echange(), Milieu_composite::initialiser(), Loi_Etat_Multi_GP_WC::initialiser_inco_ch(), Milieu_composite::initTimeStep(), MaillerParallel::interpreter(), Interprete_geometrique_base::interpreter(), SupprimeBord::interpreter_(), Postraiter_domaine::interpreter_(), Create_domain_from_sous_zone::interpreter_(), Scatter::lire_domaine(), Scatter::mergeDomains(), Milieu_composite::mettre_a_jour(), Chimie::mettre_a_jour(), Champ_Gen_de_Champs_Gen::mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), mon_construire_correspondance_items_par_coordonnees(), Bords::nb_bords(), Champ_Tabule_Morceaux::nb_champs_tabules(), List_Equations_Scalaires_Passifs_Especes::nb_equation(), Faces_Internes::nb_faces_internes(), Joints::nb_joints(), Couplage_U::nb_problemes(), Raccords::nb_raccords(), Domaine::nb_ss_zones(), Domaine::nb_zones(), Param::print(), Loi_Etat_Multi_GP_QC::rabot(), Param::read(), Milieu_composite::readOn(), Navier_Stokes_std::readOn(), Sonde::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Raffiner_Simplexes::refine_domain(), RegroupeBord::regroupe_bord(), Zone_VEF::reordonner(), Zone_PolyMAC::reordonner(), Zone_EF::reordonner(), Zone_CoviMAC::reordonner(), Scatter::reordonner_faces_de_joint(), reordonner_vdf(), Champ_Gen_de_Champs_Gen::reprendre(), Operateurs_Statistique_tps::sauvegarder(), Champ_Gen_de_Champs_Gen::sauvegarder(), Scatter::trier_les_joints(), Loi_Etat_Multi_GP_WC::update_Yn_values(), Champ_Tabule_Morceaux::valeur_a_elem_compo(), Champ_Tabule_Morceaux::valeur_aux_elems(), Zone_VEF_PreP1b::verifie_ok_arete(), and Verifier_Qualite_Raffinements::verifier_qualite_raffinements().
{
  if(est_vide()) return 0;
  if(est_dernier()) return 1;
  int compteur=1;
  liste_curseur curseur(*suivant_);
  while(curseur)
    {
      ++compteur;
      ++curseur;
    }
  return compteur;
}
const liste & liste::suivant () const [inline, protected]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
const liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 435 of file liste.h.
References suivant_.
Referenced by liste_curseur::operator++().
{
  return *suivant_;
}
liste & liste::suivant () [inline, protected]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 416 of file liste.h.
References suivant_.
{
  return *suivant_;
}
void liste::suppr (const char * const ch)
Supprime l'Objet de Nom ch contenu dans la liste.
Definition at line 771 of file liste.cpp.
References Cerr, data, Deriv_Objet_U::deplace(), finl, O_U_Ptr::le_nom(), liste_curseur::list(), next(), suivant_, and vide().
Referenced by operator-=().
{
  Nom nom(ch);
  if(data.le_nom()==nom)
    {
// L'objet recherche est le premier
      if(suivant_)
        {
// La liste n'est pas un singleton
          liste* next=suivant_;
          suivant_=next->suivant_;
          data.deplace(next->data);
          next->suivant_=0;
          delete next;
          return;
        }
      else
        {
          vide();
          suivant_=this;
        }
      return;
    }
// L'objet n'est pas en tete
  liste_curseur curseur_pre=*this;
  liste_curseur curseur=*suivant_;
  while(curseur)
    {
      if(curseur->le_nom()==nom)
        {
// On l'a trouve
          liste* next=curseur_pre.list().suivant_;
          curseur_pre.list().suivant_=curseur.list().suivant_;
          next->suivant_=0;
          delete next;
          return ;
        }
      ++curseur;
      ++curseur_pre;
    }
  Cerr << "WARNING while deleting in a list " << finl;
  Cerr << "We have not found an object with name : " << ch << finl;
}
void liste::suppr (const Objet_U & obj) [protected]
Supprime un Objet_U contenu dans la liste.
Definition at line 714 of file liste.cpp.
References Cerr, data, Deriv_Objet_U::deplace(), finl, liste_curseur::list(), next(), suivant_, liste_curseur::valeur(), valeur(), and vide().
{
  if(valeur()==obj)
    {
// L'objet recherche est le premier
      if(suivant_)
        {
// La liste n'est pas un singleton
          liste* next=suivant_;
          suivant_=next->suivant_;
          data.deplace(next->data);
          next->suivant_=0;
          delete next;
          return;
        }
      else
        {
          vide();
          suivant_=this;
        }
      return;
    }
// L'objet n'est pas en tete
  liste_curseur curseur_pre=*this;
  liste_curseur curseur=*suivant_;
  while(curseur)
    {
      if(curseur.valeur()==obj)
        {
// On l'a trouve
          liste* next=curseur_pre.list().suivant_;
          curseur_pre.list().suivant_=curseur.list().suivant_;
          next->suivant_=0;
          delete next;
          return ;
        }
      ++curseur;
      ++curseur_pre;
    }
  Cerr << "WARNING while deleting in a list " << finl;
  Cerr << "We have not found an object == : " << obj << finl;
}
void liste::supprimer () [protected]
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 880 of file liste.cpp.
References est_dernier(), est_vide(), and suivant_.
{
  if(est_vide()) return;
  if(est_dernier()) return;
  liste* old=suivant_;
  suivant_=suivant_->suivant_;
  old->suivant_=0;
  delete old;
}
unsigned liste::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, Champs_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, Liste_Champ_Generique, List_Deriv_Postraitement_base, Postraitements, List_Sonde, List_Champ, Sondes, List_Sonde_Int, Sondes_Int, List_Source, Sources, List_Bord, Bords, List_Domaine, List_Faces_Interne, Faces_Internes, List_Ref_Domaine, List_Joint, Joints, List_Ref_Sous_Zone, List_Raccord, Raccords, List_Ref_Frontiere, List_Zone, Zones, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, Operateurs_Statistique_tps, Interprete_bloc, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 25 of file liste.cpp.
Objet_U & liste::valeur () [inline, protected]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 318 of file liste.h.
References data, and Deriv_Objet_U::valeur().
Referenced by add(), add_deplace(), add_if_not(), inserer(), Interprete_bloc::interprete_courant(), Interprete_bloc::objet_global(), Interprete_bloc::objet_global_existant(), operator->(), suppr(), and liste_curseur::valeur().
{
  return data.valeur();
}
const Objet_U & liste::valeur () const [inline, protected]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
const Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, List_Deriv_Postraitement_base, List_Sonde, List_Champ, List_Sonde_Int, List_Source, List_Bord, List_Domaine, List_Faces_Interne, List_Ref_Domaine, List_Joint, List_Ref_Sous_Zone, List_Raccord, List_Ref_Frontiere, List_Zone, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 337 of file liste.h.
References data, and Deriv_Objet_U::valeur().
{
  return data.valeur();
}
void liste::vide ()
Vide la liste.
Definition at line 223 of file liste.cpp.
References data, est_vide(), suivant_, and vide().
Referenced by Sondes::clear_cache(), Champ_Generique_Transformation::completer(), Champ_Gen_de_Champs_Gen::completer(), Domaine::creer_mes_domaines_frontieres(), Create_domain_from_sous_zone::interpreter_(), operator=(), Domaine::read_vertices(), readOn(), Domaine::readOn(), Raffiner_Simplexes::refine_domain(), Champ_Gen_de_Champs_Gen::reset(), suppr(), vide(), ~liste(), and mon_main::~mon_main().
{
  if (!est_vide())
    {
      if(suivant_)
        {
          suivant_->vide();
          delete suivant_;
        }
      data=DerObjU();
    }
  suivant_=this;
}
Friends And Related Function Documentation
friend class liste_curseur [friend]
Definition at line 56 of file liste.h.
int operator!= (const liste & list1, const liste & list2) [friend]
Operateur de difference entre deux listes
La comparaison repose sur l'egalite des Objet_U des 2 listes.
Returns:
int
Signification: 1 si les listes sont differentes, 0 si elles egales
Contraintes:
Definition at line 948 of file liste.cpp.
{
  return !(list1==list2);
}
int operator== (const liste & list1, const liste & list2) [friend]
Operateur de comparaison de deux listes
La comparaison repose sur l'egalite des Objet_U des 2 listes.
Returns:
int
Signification: 1 si les listes sont egales, 0 sinon
Contraintes:
Definition at line 910 of file liste.cpp.
{
  liste_curseur curseur1=list1;
  liste_curseur curseur2=list2;
  while(curseur1 && curseur2)
    if(curseur1.valeur() != curseur2.valeur())
      return 0;
    else
      {
        ++curseur1 ;
        ++curseur2;
      }
  if(!curseur1 && !curseur2)
    return 1;
  return 0;
}
Member Data Documentation
DerObjU liste::data [protected]
Definition at line 94 of file liste.h.
Referenced by add(), add_deplace(), add_if_not(), suppr(), valeur(), and vide().
const Type_info liste::info_obj [static]
Reimplemented from Objet_U.
Reimplemented in List_Table, List_Champ_Fonc_Tabule, List_Ref_Champ_base, List_Champ_Fonc, Champs_Fonc, List_RefObjU, List_Equation, List_Ref_Champ_Generique_base, List_Ref_Equation_base, List_Ref_Field_base, List_Ref_IntVect, List_Ref_Loi_Fermeture_base, List_Ref_Postraitement, List_Ref_Probleme_U, List_Champ_Generique, Liste_Champ_Generique, List_Deriv_Postraitement_base, Postraitements, List_Sonde, List_Champ, Sondes, List_Sonde_Int, Sondes_Int, List_Source, Sources, List_Bord, Bords, List_Domaine, List_Faces_Interne, Faces_Internes, List_Ref_Domaine, List_Joint, Joints, List_Ref_Sous_Zone, List_Raccord, Raccords, List_Ref_Frontiere, List_Zone, Zones, List_Constante, List_DoubleVect, List_Deriv_UnaryFunction, List_Matrice_Morse_Sym, List_Polynome, List_Operateur_Statistique_tps, Operateurs_Statistique_tps, Interprete_bloc, List_List_Nom, List_Motcle, List_Nom, List_Noms, List_Objet_a_lire, List_Reaction, List_Ref_Champ_Inc_base, List_Ref_Espece, and List_Fluide_base.
Definition at line 42 of file liste.h.
liste* liste::suivant_ [protected]
Definition at line 95 of file liste.h.
Referenced by add(), add_deplace(), add_if_not(), est_dernier(), est_vide(), inserer(), liste(), search(), size(), suivant(), suppr(), supprimer(), vide(), and ~liste().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/liste.h
src/Kernel/Utilitaires/liste.cpp