TRUST: Source_dep_inco_base Class Reference
Source_dep_inco_base Class Reference
#include <Source_dep_inco_base.h>
Public Member Functions
Source_dep_inco_base ()
~Source_dep_inco_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &resu) const
virtual DoubleTab & ajouter_ (const DoubleTab &inco, DoubleTab &resu) const =0
virtual DoubleTab & calculer (DoubleTab &resu) const
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Source_dep_inco_base & self_cast (Objet_U &)
static const Source_dep_inco_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Detailed Description
Definition at line 37 of file Source_dep_inco_base.h.
Constructor & Destructor Documentation
Source_dep_inco_base::Source_dep_inco_base ()
Definition at line 26 of file Source_dep_inco_base.cpp.
Source_dep_inco_base::~Source_dep_inco_base ()
Definition at line 26 of file Source_dep_inco_base.cpp.
Member Function Documentation
DoubleTab & Source_dep_inco_base::ajouter (DoubleTab & resu) const [virtual]
Reimplemented from Source_base.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face, and Perte_Charge_Singuliere_QC_VDF_Face.
Definition at line 46 of file Source_dep_inco_base.cpp.
References ajouter_(), and MorEqn::equation().
Referenced by calculer().
{
  return ajouter_(equation().inconnue(),resu);
}
virtual DoubleTab& Source_dep_inco_base::ajouter_ (const DoubleTab & inco, DoubleTab & resu) const [pure virtual]
Implemented in Source_PDF_EF, Source_PDF_base, Perte_Charge_Reguliere_VDF_Face, and Perte_Charge_Singuliere_VDF_Face.
Referenced by ajouter().
DoubleTab & Source_dep_inco_base::calculer (DoubleTab & resu) const [virtual]
Reimplemented from Source_base.
Reimplemented in Source_PDF_base.
Definition at line 50 of file Source_dep_inco_base.cpp.
References ajouter().
{
  resu=0;
  return ajouter(resu);
}
virtual int Source_dep_inco_base::duplique () const [pure virtual]
Implements Source_base.
Implemented in Source_PDF_EF, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Source_PDF_base, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, and Perte_Charge_VDF_Face.
const Type_info * Source_dep_inco_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Source_PDF_EF, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Source_PDF_base, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, and Perte_Charge_VDF_Face.
Definition at line 26 of file Source_dep_inco_base.cpp.
const Type_info * Source_dep_inco_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Source_PDF_EF, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Source_PDF_base, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, and Perte_Charge_VDF_Face.
Definition at line 26 of file Source_dep_inco_base.cpp.
Sortie & Source_dep_inco_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Source_PDF_EF, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Source_PDF_base, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, and Perte_Charge_VDF_Face.
Definition at line 32 of file Source_dep_inco_base.cpp.
{
  return s ;
}
Entree & Source_dep_inco_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Source_PDF_EF, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Source_PDF_base, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, and Perte_Charge_VDF_Face.
Definition at line 41 of file Source_dep_inco_base.cpp.
{
  return s ;
}
const Source_dep_inco_base & Source_dep_inco_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Reimplemented in Source_PDF_EF, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Source_PDF_base, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, and Perte_Charge_VDF_Face.
Definition at line 26 of file Source_dep_inco_base.cpp.
Source_dep_inco_base & Source_dep_inco_base::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Reimplemented in Source_PDF_EF, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Source_PDF_base, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, and Perte_Charge_VDF_Face.
Definition at line 26 of file Source_dep_inco_base.cpp.
Member Data Documentation
const Type_info Source_dep_inco_base::info_obj [static]
Reimplemented from Source_base.
Reimplemented in Source_PDF_EF, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Source_PDF_base, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, and Perte_Charge_VDF_Face.
Definition at line 40 of file Source_dep_inco_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Source_dep_inco_base.h
src/Kernel/Framework/Source_dep_inco_base.cpp