TRUST: Perte_Charge_VEF Class Reference
Perte_Charge_VEF Class Reference abstract
#include <Perte_Charge_VEF.h>
Public Member Functions
Perte_Charge_VEF ()
~Perte_Charge_VEF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const override
Appelle perte_charge pour chaque face ou cela est necessaire.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
copie de ajouter sauf la derniere ligne
DoubleTab & calculer (DoubleTab &) const override
void associer_pb (const Probleme_base &) override
associe le_fluide et la_vitesse
void completer () override
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don & source () const
Renvoie le champ donne representant le terme source.
Static Public Member Functions
static const Type_info * info ()
static Perte_Charge_VEF & self_cast (Objet_U &)
static const Perte_Charge_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
associe la_zone_VEF et la_zone_Cl_VEF
virtual void coeffs_perte_charge (const DoubleVect &u, const DoubleVect &pos, double t, double norme_u, double dh, double nu, double reynolds, double &coeff_ortho, double &coeff_long, double &u_l, DoubleVect &v_valeur) const =0
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_Don diam_hydr
Ref_Fluide_base le_fluide
Ref_Champ_Inc_base la_vitesse
Ref_Zone_VEF la_zone_VEF
Ref_Zone_Cl_VEF la_zone_Cl_VEF
bool sous_zone
Le terme est-il limite a une sous-zone ?
Nom nom_sous_zone
Nom de la sous-zone, initialise dans readOn()
Ref_Sous_zone_VF la_sous_zone_dis
Initialise dans completer()
int implicite_
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Protected Attributes inherited from Terme_Source_Qdm
Champ_Don la_source
Detailed Description
Perte_Charge_Isotrope, Perte_Charge_Directionnelle et Perte_Charge_Anisotrope heritent de Perte_Charge_VEF. Elles doivent surcharger essentiellement readOn() et perte_charge(). readOn() est suppose lire au moins diam_hydr et sous_zone.
Ces classes sont censees remplacer Perte_Charge_VEF_Face et Perte_Charge_VEF_P1NC. ! Factorise les fonctionnalites de plusieurs pertes de charge en VEF, vitesse aux faces
Definition at line 38 of file Perte_Charge_VEF.h.
Constructor & Destructor Documentation
Perte_Charge_VEF()
Perte_Charge_VEF::Perte_Charge_VEF ()
Definition at line 29 of file Perte_Charge_VEF.cpp.
:implicite_(1) { }
~Perte_Charge_VEF()
Perte_Charge_VEF::~Perte_Charge_VEF () override
Definition at line 27 of file Perte_Charge_VEF.cpp.
Member Function Documentation
ajouter()
DoubleTab & Perte_Charge_VEF::ajouter (DoubleTab & resu) const override virtual
Appelle perte_charge pour chaque face ou cela est necessaire.
< viscosite cinematique
< centres de gravite des faces
Reimplemented from Source_base.
Definition at line 53 of file Perte_Charge_VEF.cpp.
{
  const Zone_VEF& zvef=la_zone_VEF.valeur();
  const Champ_Don& nu=le_fluide->viscosite_cinematique(); //!< viscosite cinematique
  const DoubleTab& xv=zvef.xv() ;                 //!< centres de gravite des faces
  const DoubleTab& vit=la_vitesse->valeurs();
// Sinon segfault a l'initialisation de ssz quand il n'y a pas de sous-zone !
  const Sous_zone_VF& ssz = sous_zone ? la_sous_zone_dis.valeur() : Sous_zone_VF();
// Parametres pour perte_charge()
  DoubleVect u(dimension);
  DoubleVect pos(dimension);
  DoubleVect v_valeur(dimension);
// Optimisations pour les cas ou nu ou diam_hydr sont constants
  bool nu_constant=sub_type(Champ_Uniforme,nu.valeur())?true:false;
  bool dh_constant=sub_type(Champ_Uniforme,diam_hydr.valeur())?true:false;
// Le temps actuel
  double t=equation().schema_temps().temps_courant();
// Nombre de faces a traiter.
  int max_faces = sous_zone ? ssz.les_faces().size() : zvef.nb_faces();
  for (int face=0; face<max_faces; face++)
    {
// indice de la face dans la zone_VEF
      int la_face = sous_zone ? ssz.les_faces()[face] : face;
      if (la_face<zvef.nb_faces())
        {
// Recup la vitesse a la face, et en calcule le module
          double norme_u=0;
          for (int dim=0; dim<dimension; dim++)
            {
              u[dim]=vit(la_face,dim);
              norme_u+=u[dim]*u[dim];
            }
          norme_u=sqrt(norme_u) ;
// Calcul de la position
          for (int i=0; i<dimension; i++)
            pos[i]=xv(la_face,i);
// Calcul de nu
          double nu_valeur = nu_constant ? nu(0,0) : nu->valeur_a_compo(pos,0);
// Calcul du diametre hydraulique
          double dh_valeur = dh_constant ? diam_hydr(0,0) : diam_hydr->valeur_a_compo(pos,0);
// Calcul du reynolds
          double reynolds=norme_u*dh_valeur/nu_valeur;
// Lambda est souvent indetermine pour Re->0
          if (reynolds < 1.e-10)
            reynolds=1e-10;
// Calcul du volume d'integration
          double volume=sous_zone?
                        ssz.volumes_entrelaces(face) :
                        zvef.volumes_entrelaces(la_face);
          volume*=zvef.porosite_face(la_face);
// Calcul du resultat final (ouf)
          double coeff_ortho,coeff_long,u_l;
          coeffs_perte_charge(u,pos,t,norme_u,dh_valeur,nu_valeur,reynolds,coeff_ortho,coeff_long,u_l,v_valeur);
          for (int dim=0; dim<dimension; dim++)
            {
// La perte de charge vaut -coeff_long*u_l*v_valeur[dim] -coeff_ortho(u[dim] -u_v*v_valeur[dim])
// soit -coeff_ortho* u[dim] - (coeff_long-coeff_ortho)* u_l*v_valeur[dim]
              resu(la_face,dim)-=(coeff_ortho* u[dim] + (coeff_long-coeff_ortho)* u_l*v_valeur[dim])*volume;
            }
        }
    }
  return resu;
}
References coeffs_perte_charge(), diam_hydr, Objet_U::dimension, MorEqn::equation(), la_sous_zone_dis, la_vitesse, la_zone_VEF, le_fluide, Sous_zone_VF::les_faces(), Zone_VF::nb_faces(), Zone_VF::porosite_face(), Equation_base::schema_temps(), TRUSTVect< _TYPE_ >::size(), sous_zone, sub_type, Schema_Temps_base::temps_courant(), Deriv_Champ_Don_base::valeur(), Ref_Sous_zone_VF::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc_base::valeurs(), Fluide_base::viscosite_cinematique(), Zone_VF::volumes_entrelaces(), Sous_zone_VF::volumes_entrelaces(), and Zone_VF::xv().
Referenced by Perte_Charge_Circulaire_QC_VEF_P1NC::ajouter_mere(), Perte_Charge_Anisotrope_QC_VEF_P1NC::ajouter_mere(), Perte_Charge_Directionnelle_QC_VEF_P1NC::ajouter_mere(), Perte_Charge_Isotrope_QC_VEF_P1NC::ajouter_mere(), and calculer().
associer_pb()
void Perte_Charge_VEF::associer_pb (const Probleme_base & pb) override virtual
associe le_fluide et la_vitesse
Implements Source_base.
Definition at line 273 of file Perte_Charge_VEF.cpp.
{
  la_vitesse = ref_cast(Champ_P1NC,equation().inconnue().valeur());
  le_fluide = ref_cast(Fluide_base,equation().milieu());
}
References MorEqn::equation(), la_vitesse, le_fluide, ref_cast, and valeur().
associer_zones()
void Perte_Charge_VEF::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
associe la_zone_VEF et la_zone_Cl_VEF
Implements Source_base.
Definition at line 279 of file Perte_Charge_VEF.cpp.
{
  la_zone_VEF = ref_cast(Zone_VEF, zone_dis.valeur());
  la_zone_Cl_VEF = ref_cast(Zone_Cl_VEF, zone_Cl_dis.valeur());
}
References la_zone_Cl_VEF, la_zone_VEF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
calculer()
DoubleTab & Perte_Charge_VEF::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 233 of file Perte_Charge_VEF.cpp.
{
  resu=0;
  return ajouter(resu);
}
References ajouter().
coeffs_perte_charge()
virtual void Perte_Charge_VEF::coeffs_perte_charge (const DoubleVect & u, const DoubleVect & pos, double t, double norme_u, double dh, double nu, double reynolds, double & coeff_ortho, double & coeff_long, double & u_l, DoubleVect & v_valeur) const protected pure virtual
 Utilise les intermediaires de calcul : u, norme_u, dh_valeur, reynolds
 Retourne le resultat calcule dans p_charge.
 Avantage : bonne factorisation.
 Inconvenient : cout de l'appel d'une methode virtuelle a
 l'interieur d'une boucle.
 \param u La vitesse a la face courante. 2 ou 3 composantes
 \param pos toto
 \param t titi
 \param norme_u La norme de la vitesse a la face courante
 \param dh Le diametre hydraulique a la face courante (tire de diam_hydr)
 \param nu la viscosite cinematique
 \param reynolds Le nombre de reynolds a la face courante : norme_u * dh_valeur / nu
 \param coeff_ortho coefficient dans la direction orthogonale
 \param coeff_long coefficient dans la direction longitudinale
 \param u_l vitesse dans la direction longitudinale
 \param v_valeur direction_longitudinale p_charge a 2 ou 3 composantes
 La perte de charge vaut -coeff_long*u_l*v_valeur -coeff_ortho(u -u_v*v_valeur)
! Appele pour chaque face par ajouter()
Implemented in Perte_Charge_Anisotrope_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, and Perte_Charge_Isotrope_VEF_P1NC.
Referenced by ajouter(), and contribuer_a_avec().
completer()
void Perte_Charge_VEF::completer (void) override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
Definition at line 240 of file Perte_Charge_VEF.cpp.
{
  Source_base::completer();
  if (sous_zone)
    {
      sous_zone=false;
      const Sous_Zone& la_sous_zone=equation().probleme().domaine().ss_zone(nom_sous_zone);
      const Domaine_dis& le_domaine_dis=la_zone_VEF->domaine_dis();
      for (int ssz=0; ssz<le_domaine_dis.nombre_de_sous_zones_dis(); ssz++)
        {
          if (le_domaine_dis.sous_zone_dis(ssz)->sous_zone().est_egal_a(la_sous_zone))
            {
              sous_zone=true;
              la_sous_zone_dis=ref_cast(Sous_zone_VF,le_domaine_dis.sous_zone_dis(ssz).valeur());
            }
        }
      if(!sous_zone)
        {
          Cerr << "On ne trouve pas la sous_zone discretisee associee a " << nom_sous_zone << finl;
          exit();
        }
    }
}
References Cerr, Source_base::completer(), Probleme_base::domaine(), Zone_dis_base::domaine_dis(), MorEqn::equation(), Objet_U::est_egal_a(), Process::exit(), finl, la_sous_zone_dis, la_zone_VEF, nom_sous_zone, Domaine_dis::nombre_de_sous_zones_dis(), Equation_base::probleme(), ref_cast, sous_zone, Domaine_dis::sous_zone_dis(), Domaine::ss_zone(), and Deriv_Sous_zone_dis_base::valeur().
contribuer_a_avec()
void Perte_Charge_VEF::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const override virtual
copie de ajouter sauf la derniere ligne
< La perte de charge n'est pas implicitee, on quitte
< viscosite cinematique
< centres de gravite des faces
Reimplemented from Source_base.
Definition at line 130 of file Perte_Charge_VEF.cpp.
{
  if (implicite_==0) return; //!< La perte de charge n'est pas implicitee, on quitte
// Raccourcis
  const Champ_Don& nu=le_fluide->viscosite_cinematique(); //!< viscosite cinematique
  const DoubleTab& xv=la_zone_VEF->xv() ;                     //!< centres de gravite des faces
  const DoubleTab& vit=la_vitesse->valeurs();
// Sinon segfault a l'initialisation de ssz quand il n'y a pas de sous-zone !
  const Sous_zone_VF& ssz=sous_zone?la_sous_zone_dis.valeur():Sous_zone_VF();
  const Zone_VEF& zvef=la_zone_VEF.valeur();
// Parametres pour perte_charge()
  DoubleVect u(dimension);
  double norme_u;
  double dh_valeur;
  double reynolds;
  DoubleVect pos(dimension);
  DoubleVect v_valeur(dimension);
// Optimisations pour les cas ou nu ou diam_hydr sont constants
  bool nu_constant=sub_type(Champ_Uniforme,nu.valeur())?true:false;
  double nu_valeur;
  bool dh_constant=sub_type(Champ_Uniforme,diam_hydr.valeur())?true:false;
// Le temps actuel
  double t=equation().schema_temps().temps_courant();
// Nombre de faces a traiter.
  int max_faces=sous_zone?
                ssz.les_faces().size() :
                zvef.nb_faces();
// To ensure that nu_valeur will not be zero
// and not have a division by zero for the calculation of Reynolds
  assert_espace_virtuel_vect(nu->valeurs());
  for (int face=0; face<max_faces; face++)
    {
// indice de la face dans la zone_VEF
      int la_face=sous_zone?
                  ssz.les_faces()[face] :
                  face;
// Fixed bug by GF: si la face est une face virtuelle on passe, car nu mal calcule et coef(no,no) invalide
      if (la_face>=zvef.nb_faces())
        continue;
// Recup la vitesse a la face, et en calcule le module
      norme_u=0;
      for (int dim=0; dim<dimension; dim++)
        {
          u[dim]=vit(la_face,dim);
          norme_u+=u[dim]*u[dim];
        }
      norme_u=sqrt(norme_u) ;
// Calcul de la position
      for (int i=0; i<dimension; i++)
        pos[i]=xv(la_face,i);
// Calcul de nu
      if (!nu_constant)
        {
          nu_valeur=nu->valeur_a_compo(pos,0);
        }
      else nu_valeur=nu(0,0);
// Calcul du diametre hydraulique
      if (!dh_constant)
        {
          dh_valeur=diam_hydr->valeur_a_compo(pos,0);
        }
      else dh_valeur=diam_hydr(0,0);
// Calcul du reynolds
      reynolds=norme_u*dh_valeur/nu_valeur;
// Lambda est souvent indetermine pour Re->0
      if (reynolds < 1.e-10)
        reynolds=1e-10;
// Calcul du volume d'integration
      double volume=sous_zone?
                    ssz.volumes_entrelaces(face) :
                    zvef.volumes_entrelaces(la_face);
      volume*=zvef.porosite_face(la_face);
// Calcul du resultat final (ouf)
      double coeff_ortho,coeff_long,u_l;
      coeffs_perte_charge(u,pos,t,norme_u,dh_valeur,nu_valeur,reynolds,coeff_ortho,coeff_long,u_l,v_valeur);
      for (int dim=0; dim<dimension; dim++)
        {
          int n0=la_face*dimension+dim;
// matrice.coef(n0,n0) += (coeff_ortho + (coeff_long-coeff_ortho)* v_valeur[dim]*v_valeur[dim]); // Fixed bug
          matrice.coef(n0,n0) += (coeff_ortho + (coeff_long-coeff_ortho)* v_valeur[dim]*v_valeur[dim])*volume;
// La perte de charge vaut -coeff_long*u_l*v_valeur[dim] -coeff_ortho(u[dim] -u_v*v_valeur[dim])
// soit -coeff_ortho* u[dim] - (coeff_long-coeff_orho)* u_l*v_valeur[dim]
// resu(la_face,dim)-=(coeff_ortho* u[dim] + (coeff_long-coeff_orho)* u_l*v_valeur[dim]);
        }
    }
}
References assert_espace_virtuel_vect(), Matrice_Morse::coef(), coeffs_perte_charge(), diam_hydr, Objet_U::dimension, MorEqn::equation(), implicite_, la_sous_zone_dis, la_vitesse, la_zone_VEF, le_fluide, Sous_zone_VF::les_faces(), Zone_VF::nb_faces(), Zone_VF::porosite_face(), Equation_base::schema_temps(), TRUSTVect< _TYPE_ >::size(), sous_zone, sub_type, Schema_Temps_base::temps_courant(), Deriv_Champ_Don_base::valeur(), Ref_Sous_zone_VF::valeur(), Ref_Zone_VEF::valeur(), Champ_Don::valeurs(), Champ_Inc_base::valeurs(), Fluide_base::viscosite_cinematique(), Zone_VF::volumes_entrelaces(), Sous_zone_VF::volumes_entrelaces(), and Zone_VF::xv().
get_info()
const Type_info * Perte_Charge_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 27 of file Perte_Charge_VEF.cpp.
info()
const Type_info * Perte_Charge_VEF::info () static
Definition at line 27 of file Perte_Charge_VEF.cpp.
printOn()
Sortie & Perte_Charge_VEF::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 34 of file Perte_Charge_VEF.cpp.
{
  return s << que_suis_je() << finl;
}
References finl, and Objet_U::que_suis_je().
readOn()
Entree & Perte_Charge_VEF::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 42 of file Perte_Charge_VEF.cpp.
{
  return s;
}
self_cast() [1/2]
const Perte_Charge_VEF & Perte_Charge_VEF::self_cast (const Objet_U & r) static
Definition at line 27 of file Perte_Charge_VEF.cpp.
self_cast() [2/2]
Perte_Charge_VEF & Perte_Charge_VEF::self_cast (Objet_U & r) static
Definition at line 27 of file Perte_Charge_VEF.cpp.
Member Data Documentation
diam_hydr
Champ_Don Perte_Charge_VEF::diam_hydr protected
Definition at line 81 of file Perte_Charge_VEF.h.
Referenced by ajouter(), contribuer_a_avec(), Perte_Charge_Anisotrope_VEF_P1NC::mettre_a_jour(), Perte_Charge_Circulaire_VEF_P1NC::mettre_a_jour(), Perte_Charge_Directionnelle_VEF_P1NC::mettre_a_jour(), Perte_Charge_Isotrope_VEF_P1NC::mettre_a_jour(), Perte_Charge_Anisotrope_VEF_P1NC::readOn(), Perte_Charge_Circulaire_VEF_P1NC::readOn(), Perte_Charge_Directionnelle_VEF_P1NC::readOn(), and Perte_Charge_Isotrope_VEF_P1NC::readOn().
implicite_
int Perte_Charge_VEF::implicite_ protected
Definition at line 94 of file Perte_Charge_VEF.h.
Referenced by contribuer_a_avec(), Perte_Charge_Anisotrope_VEF_P1NC::readOn(), Perte_Charge_Circulaire_VEF_P1NC::readOn(), Perte_Charge_Directionnelle_VEF_P1NC::readOn(), and Perte_Charge_Isotrope_VEF_P1NC::readOn().
info_obj
const Type_info Perte_Charge_VEF::info_obj static
Definition at line 40 of file Perte_Charge_VEF.h.
la_sous_zone_dis
Ref_Sous_zone_VF Perte_Charge_VEF::la_sous_zone_dis protected
Initialise dans completer()
Definition at line 93 of file Perte_Charge_VEF.h.
Referenced by ajouter(), completer(), and contribuer_a_avec().
la_vitesse
Ref_Champ_Inc_base Perte_Charge_VEF::la_vitesse protected
Definition at line 85 of file Perte_Charge_VEF.h.
Referenced by ajouter(), associer_pb(), and contribuer_a_avec().
la_zone_Cl_VEF
Ref_Zone_Cl_VEF Perte_Charge_VEF::la_zone_Cl_VEF protected
Definition at line 88 of file Perte_Charge_VEF.h.
Referenced by associer_zones().
la_zone_VEF
Ref_Zone_VEF Perte_Charge_VEF::la_zone_VEF protected
Definition at line 87 of file Perte_Charge_VEF.h.
Referenced by ajouter(), associer_zones(), completer(), and contribuer_a_avec().
le_fluide
Ref_Fluide_base Perte_Charge_VEF::le_fluide protected
Definition at line 83 of file Perte_Charge_VEF.h.
Referenced by ajouter(), associer_pb(), and contribuer_a_avec().
nom_sous_zone
Nom Perte_Charge_VEF::nom_sous_zone protected
Nom de la sous-zone, initialise dans readOn()
Definition at line 92 of file Perte_Charge_VEF.h.
Referenced by completer(), Perte_Charge_Anisotrope_VEF_P1NC::readOn(), Perte_Charge_Circulaire_VEF_P1NC::readOn(), Perte_Charge_Directionnelle_VEF_P1NC::readOn(), and Perte_Charge_Isotrope_VEF_P1NC::readOn().
sous_zone
bool Perte_Charge_VEF::sous_zone protected
Le terme est-il limite a une sous-zone ?
Definition at line 91 of file Perte_Charge_VEF.h.
Referenced by ajouter(), completer(), contribuer_a_avec(), Perte_Charge_Anisotrope_VEF_P1NC::readOn(), Perte_Charge_Circulaire_VEF_P1NC::readOn(), Perte_Charge_Directionnelle_VEF_P1NC::readOn(), and Perte_Charge_Isotrope_VEF_P1NC::readOn().
The documentation for this class was generated from the following files:
src/VEF/Sources/Perte_Charge_VEF.h
src/VEF/Sources/Perte_Charge_VEF.cpp