TRUST: Source_WC_Chaleur_VEF Class Reference
Source_WC_Chaleur_VEF Class Reference
class Source_WC_Chaleur_VEF
Cette classe represente un terme source supplementaire
a prendre en compte dans les equations de la chaleur
dans le cas ou le fluide est weakly compressible et pour
une discretisation VEF
#include <Source_WC_Chaleur_VEF.h>
Public Member Functions
Source_WC_Chaleur_VEF ()
~Source_WC_Chaleur_VEF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Source_WC_Chaleur_VEF & self_cast (Objet_U &)
static const
Source_WC_Chaleur_VEF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
void compute_interpolate_gradP (DoubleTab &UgradP_face, const DoubleTab &Ptot) const
Private Member Functions
void elem_to_face (const Zone_VF &zone, const DoubleTab &grad_Ptot, DoubleTab &grad_Ptot_face) const
Detailed Description
class Source_WC_Chaleur_VEF
Cette classe represente un terme source supplementaire
a prendre en compte dans les equations de la chaleur
dans le cas ou le fluide est weakly compressible et pour
une discretisation VEF
Definition at line 44 of file Source_WC_Chaleur_VEF.h.
Constructor & Destructor Documentation
Source_WC_Chaleur_VEF::Source_WC_Chaleur_VEF ()
Definition at line 31 of file Source_WC_Chaleur_VEF.cpp.
Source_WC_Chaleur_VEF::~Source_WC_Chaleur_VEF ()
Definition at line 31 of file Source_WC_Chaleur_VEF.cpp.
Member Function Documentation
void Source_WC_Chaleur_VEF::associer_zones (const Zone_dis & zone, const Zone_Cl_dis &) [protected, virtual]
Implements Source_Chaleur_Fluide_Dilatable_base.
Definition at line 41 of file Source_WC_Chaleur_VEF.cpp.
References Source_Fluide_Dilatable_VEF_Proto::associer_volume_porosite_impl(), Source_Chaleur_Fluide_Dilatable_base::porosites, and Source_Chaleur_Fluide_Dilatable_base::volumes.
{
  associer_volume_porosite_impl(zone,volumes,porosites);
}
void Source_WC_Chaleur_VEF::compute_interpolate_gradP (DoubleTab & UgradP_face, const DoubleTab & Ptot) const [protected, virtual]
< compute grad(P_tot)
< champs sur les faces
Implements Source_WC_Chaleur.
Definition at line 46 of file Source_WC_Chaleur_VEF.cpp.
References Operateur_Grad::calculer(), Milieu_base::conductivite(), Source_WC_Chaleur::correct_grad_boundary(), DoubleTab::dimension_tot(), elem_to_face(), DoubleVect::line_size(), Navier_Stokes_std::milieu(), MorEqn::mon_equation, Zone_VF::nb_faces_tot(), Convection_Diffusion_Chaleur_WC::operateur_gradient_WC(), Objet_U::que_suis_je(), ref_cast, DoubleTab::resize(), DoubleVect::size_totale(), Ref_Equation_base::valeur(), Champ_Don::valeurs(), Champ_Inc::valeurs(), and Navier_Stokes_std::vitesse().
{
  /*
   * NOTA BENE :
   * On a discretisé P_EOS avec une directive = temperature qui donne en VEF :
   * Ptot => aux faces
   * la_vitesse => faces car vef
   * grad_Ptot => elem
   *
   * L'equation est une equation de scalaire => aux faces car vef
   * On a d P_tot / d t = del P / del t + u.grad(P_tot)
   *
   * del P / del t => aux faces
   * u.grad(P_tot) !!! faut interpoler grad(P_tot) aux faces
   */
  const Navier_Stokes_WC& eqHyd = ref_cast(Navier_Stokes_WC,mon_equation->probleme().equation(0));
  const DoubleTab& la_vitesse = eqHyd.vitesse().valeurs();
// On sait que grad_Ptot est un champ elem => on pense à la conductivite (elem en vef !!)
  DoubleTab grad_Ptot;
  const DoubleTab& lambda = eqHyd.milieu().conductivite()->valeurs();
  const int nb = lambda.size_totale(), nbcomp = la_vitesse.line_size();
  assert (nb == lambda.dimension_tot(0) && lambda.line_size() == 1);
  grad_Ptot.resize(nb,nbcomp);
  const Convection_Diffusion_Chaleur_WC& eq_chal = ref_cast(Convection_Diffusion_Chaleur_WC,mon_equation.valeur());
  const Operateur_Grad& Op_Grad = eq_chal.operateur_gradient_WC();
  Op_Grad.calculer(Ptot,grad_Ptot); //!< compute grad(P_tot)
  const Zone_dis_base& zone_dis = mon_equation->inconnue().zone_dis_base();
  const Zone_VF& zone = ref_cast(Zone_VF, zone_dis);
  assert (zone_dis.que_suis_je() == "Zone_VEFPreP1b" || zone_dis.que_suis_je() == "Zone_VEF");
// grad should be zero at boundary
  correct_grad_boundary(zone,grad_Ptot);
// We compute u*grad(P_tot) on each face
  DoubleTab grad_Ptot_face(la_vitesse); //!< champs sur les faces
// get grad_Ptot on faces
  elem_to_face(zone,grad_Ptot,grad_Ptot_face);
  const int n = la_vitesse.dimension_tot(0);
  assert (UgradP_face.dimension_tot(0) == n && grad_Ptot_face.dimension_tot(0) == n);
  assert (UgradP_face.line_size() == 1 && n == zone.nb_faces_tot());
  for (int i=0 ; i <n ; i++)
    {
      UgradP_face(i,0) = 0.;
      for (int j=0 ; j <nbcomp ; j++) UgradP_face(i,0) += la_vitesse(i,j) * grad_Ptot_face(i,j);
    }
}
Objet_U * Source_WC_Chaleur_VEF::cree_instance () [static]
Definition at line 31 of file Source_WC_Chaleur_VEF.cpp.
int Source_WC_Chaleur_VEF::duplique () const [virtual]
Implements Source_WC_Chaleur.
Definition at line 31 of file Source_WC_Chaleur_VEF.cpp.
void Source_WC_Chaleur_VEF::elem_to_face (const Zone_VF & zone, const DoubleTab & grad_Ptot, DoubleTab & grad_Ptot_face) const [private]
Definition at line 100 of file Source_WC_Chaleur_VEF.cpp.
References DoubleTab::dimension_tot(), Zone_VF::elem_faces(), DoubleVect::line_size(), IntVect::line_size(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces_tot(), Source_Chaleur_Fluide_Dilatable_base::volumes, and Zone_VF::volumes().
Referenced by compute_interpolate_gradP().
{
  const DoubleVect& vol = zone.volumes();
  const IntTab& elem_faces = zone.elem_faces();
  const int nb_face_elem = elem_faces.line_size(), nb_elem_tot = zone.nb_elem_tot(), nb_comp = grad_Ptot_face.line_size();
  assert (grad_Ptot.dimension_tot(0) == nb_elem_tot && grad_Ptot_face.dimension_tot(0) == zone.nb_faces_tot());
  assert (grad_Ptot.line_size() == nb_comp);
  grad_Ptot_face = 0.;
  for (int ele = 0; ele < nb_elem_tot; ele++)
    for (int s = 0; s < nb_face_elem; s++)
      {
        const int face = elem_faces(ele,s);
        for (int comp = 0; comp < nb_comp; comp++) grad_Ptot_face(face,comp) += grad_Ptot(ele,comp)*vol(ele);
      }
  for (int f=0; f<zone.nb_faces_tot(); f++)
    for (int comp=0; comp<nb_comp; comp++) grad_Ptot_face(f,comp) /= volumes(f)*nb_face_elem;
}
const Type_info * Source_WC_Chaleur_VEF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_WC_Chaleur.
Definition at line 31 of file Source_WC_Chaleur_VEF.cpp.
const Type_info * Source_WC_Chaleur_VEF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_WC_Chaleur.
Definition at line 31 of file Source_WC_Chaleur_VEF.cpp.
Sortie & Source_WC_Chaleur_VEF::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_WC_Chaleur.
Definition at line 33 of file Source_WC_Chaleur_VEF.cpp.
References finl, and Objet_U::que_suis_je().
{
  os <<que_suis_je()<< finl;
  return os;
}
Entree & Source_WC_Chaleur_VEF::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_WC_Chaleur.
Definition at line 39 of file Source_WC_Chaleur_VEF.cpp.
{ return is; }
const Source_WC_Chaleur_VEF & Source_WC_Chaleur_VEF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_WC_Chaleur.
Definition at line 31 of file Source_WC_Chaleur_VEF.cpp.
Source_WC_Chaleur_VEF & Source_WC_Chaleur_VEF::self_cast (Objet_U & r) [static]
Reimplemented from Source_WC_Chaleur.
Definition at line 31 of file Source_WC_Chaleur_VEF.cpp.
unsigned Source_WC_Chaleur_VEF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 31 of file Source_WC_Chaleur_VEF.cpp.
Member Data Documentation
const Type_info Source_WC_Chaleur_VEF::info_obj [static]
Reimplemented from Source_WC_Chaleur.
Definition at line 46 of file Source_WC_Chaleur_VEF.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Weakly_Compressible/VEF/Source_WC_Chaleur_VEF.h
src/ThHyd/Dilatable/Weakly_Compressible/VEF/Source_WC_Chaleur_VEF.cpp