TRUST: Acceleration_QC_VEF_P1NC Class Reference
Acceleration_QC_VEF_P1NC Class Reference
#include <Source_QC_VEF_P1NC.h>
Public Member Functions
Acceleration_QC_VEF_P1NC ()
~Acceleration_QC_VEF_P1NC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
DoubleTab & ajouter (DoubleTab &) const
Ajoute le terme (la_source_ * rho * volume_entrelace) au champ resu.
On suppose que resu est discretise comme la vitesse.
L'espace virtuel de "resu" n'est PAS mis a jour !
Commentaire sur le schema: L'acceleration d/dt(v) est calculee aux elements,
puis multipliee par "rho" aux elements, puis evaluee aux faces par une
moyenne sur les elements voisins de la face. C'est un premier essai, pas
forcement la meilleure idee. Comme l'acceleration depend de la vitesse qui
est aux faces, on passe par deux interpolations successives.
Effet de bord:
On met (la_source_ * rho) dans terme_source_post_.
DoubleTab & ajouter_mere (DoubleTab &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Acceleration_QC_VEF_P1NC & self_cast (Objet_U &)
static const
Acceleration_QC_VEF_P1NC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
Appel a Terme_Source_Acceleration::lire_data.
Detailed Description
Definition at line 50 of file Source_QC_VEF_P1NC.h.
Constructor & Destructor Documentation
Acceleration_QC_VEF_P1NC::Acceleration_QC_VEF_P1NC ()
Definition at line 25 of file Source_QC_VEF_P1NC.cpp.
Acceleration_QC_VEF_P1NC::~Acceleration_QC_VEF_P1NC ()
Definition at line 25 of file Source_QC_VEF_P1NC.cpp.
Member Function Documentation
DoubleTab & Acceleration_QC_VEF_P1NC::ajouter (DoubleTab & resu) const [virtual]
Ajoute le terme (la_source_ * rho * volume_entrelace) au champ resu.
On suppose que resu est discretise comme la vitesse.
L'espace virtuel de "resu" n'est PAS mis a jour !
Commentaire sur le schema: L'acceleration d/dt(v) est calculee aux elements,
puis multipliee par "rho" aux elements, puis evaluee aux faces par une
moyenne sur les elements voisins de la face. C'est un premier essai, pas
forcement la meilleure idee. Comme l'acceleration depend de la vitesse qui
est aux faces, on passe par deux interpolations successives.
Effet de bord:
On met (la_source_ * rho) dans terme_source_post_.
Reimplemented from Terme_Source_Acceleration_VEF_Face.
Definition at line 29 of file Source_QC_VEF_P1NC.cpp.
References Source_Fluide_Dilatable_Face< Acceleration_QC_VEF_P1NC >::ajouter_impl().
Referenced by ajouter_mere().
{ return ajouter_impl(resu); }
DoubleTab & Acceleration_QC_VEF_P1NC::ajouter_mere (DoubleTab & resu) const
Definition at line 28 of file Source_QC_VEF_P1NC.cpp.
References ajouter().
{ return Terme_Source_Acceleration_VEF_Face::ajouter(resu); }
void Acceleration_QC_VEF_P1NC::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const [virtual]
contribution a la matrice implicite des termes sources
par defaut pas de contribution
Reimplemented from Source_base.
Definition at line 30 of file Source_QC_VEF_P1NC.cpp.
References Source_Fluide_Dilatable_Face< Acceleration_QC_VEF_P1NC >::contribuer_a_avec_impl().
{ contribuer_a_avec_impl(resu,mat); }
Objet_U * Acceleration_QC_VEF_P1NC::cree_instance () [static]
Reimplemented from Terme_Source_Acceleration_VEF_Face.
Definition at line 25 of file Source_QC_VEF_P1NC.cpp.
int Acceleration_QC_VEF_P1NC::duplique () const [virtual]
Reimplemented from Terme_Source_Acceleration_VEF_Face.
Definition at line 25 of file Source_QC_VEF_P1NC.cpp.
const Type_info * Acceleration_QC_VEF_P1NC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_Acceleration_VEF_Face.
Definition at line 25 of file Source_QC_VEF_P1NC.cpp.
const Type_info * Acceleration_QC_VEF_P1NC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_Acceleration_VEF_Face.
Definition at line 25 of file Source_QC_VEF_P1NC.cpp.
Sortie & Acceleration_QC_VEF_P1NC::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Source_Acceleration_VEF_Face.
Definition at line 26 of file Source_QC_VEF_P1NC.cpp.
{ return Terme_Source_Acceleration_VEF_Face::printOn(os); }
Entree & Acceleration_QC_VEF_P1NC::readOn (Entree & s) [protected, virtual]
Appel a Terme_Source_Acceleration::lire_data.
Reimplemented from Terme_Source_Acceleration_VEF_Face.
Definition at line 27 of file Source_QC_VEF_P1NC.cpp.
{ return Terme_Source_Acceleration_VEF_Face::readOn(is); }
const Acceleration_QC_VEF_P1NC & Acceleration_QC_VEF_P1NC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Terme_Source_Acceleration_VEF_Face.
Definition at line 25 of file Source_QC_VEF_P1NC.cpp.
Acceleration_QC_VEF_P1NC & Acceleration_QC_VEF_P1NC::self_cast (Objet_U & r) [static]
Reimplemented from Terme_Source_Acceleration_VEF_Face.
Definition at line 25 of file Source_QC_VEF_P1NC.cpp.
unsigned Acceleration_QC_VEF_P1NC::taille_memoire () const [virtual]
Reimplemented from Terme_Source_Acceleration_VEF_Face.
Definition at line 25 of file Source_QC_VEF_P1NC.cpp.
Member Data Documentation
const Type_info Acceleration_QC_VEF_P1NC::info_obj [static]
Reimplemented from Terme_Source_Acceleration_VEF_Face.
Definition at line 52 of file Source_QC_VEF_P1NC.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VEF/Source_QC_VEF_P1NC.h
src/ThHyd/Dilatable/Quasi_Compressible/VEF/Source_QC_VEF_P1NC.cpp