TRUST: Champ_Elem_PolyMAC_P0 Class Reference
Champ_Elem_PolyMAC_P0 Class Reference
: class Champ_Elem_PolyMAC_P0
Champ correspondant a une inconnue scalaire (type temperature ou pression)
Degres de libertes : valeur aux elements + flux aux faces
#include <Champ_Elem_PolyMAC_P0.h>
Public Member Functions
Champ_Elem_PolyMAC_P0 ()
~Champ_Elem_PolyMAC_P0 ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Zone_PolyMAC_P0 & zone_PolyMAC_P0 () const
void init_auxiliary_variables () override
Champ_base & affecter_ (const Champ_base &ch) override
void init_grad (int full_stencil) const
Call to initialise the tables ; no updates necessary.
void calc_grad (int full_stencil) const
Call to calculate the tables ; updates necessary.
void mettre_a_jour (double tps) override
Effectue une mise a jour en temps du champ inconnue.
WEC : Maintenant si on l'appelle 2 fois de suite avec le meme
argument, la 2eme ne fait rien.
Public Member Functions inherited from Champ_Elem_PolyMAC
Champ_Elem_PolyMAC ()
~Champ_Elem_PolyMAC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Zone_PolyMAC & zone_PolyMAC () const
void associer_zone_dis_base (const Zone_dis_base &) override
virtual const Zone_dis_base & zone_dis_base () const override
Champ_base & affecter_ (const Champ_base &ch) override
int imprime (Sortie &, int) const override
int fixer_nb_valeurs_nodales (int n) override
int nb_valeurs_nodales () const override
Returns the number of "real" geometric positions of the
degrees of freedom, or -1 if not applicable (fields with multiple
localisations)
virtual void init_auxiliary_variables ()
int reprendre (Entree &fich) override
Lecture d'un champ inconnue a partir d'un flot d'entree
en vue d'une reprise.
DoubleTab & valeur_aux_faces (DoubleTab &vals) const override
renvoie la valeur du champ aux faces
DoubleTab & trace (const Frontiere_dis_base &fr, DoubleTab &x, double t, int distant) const override
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
const IntTab & fcl () const
Public Member Functions inherited from Champ_Inc_P0_base
Champ_Inc_P0_base ()
~Champ_Inc_P0_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
DoubleTab & valeur_aux_sommets (const Domaine &domain, DoubleTab &result) const override
DoubleVect & valeur_aux_sommets_compo (const Domaine &domain, DoubleVect &result, int ncomp) const override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
Champ_base & affecter_ (const Champ_base &) override
int fixer_nb_valeurs_nodales (int n) override
Public Member Functions inherited from Champ_Inc_base
~Champ_Inc_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_Inc_base ()
int fixer_nb_valeurs_nodales (int) override
double changer_temps (const double temps) override
Fixe le temps du champ.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps du champ inconnue.
WEC : Maintenant si on l'appelle 2 fois de suite avec le meme
argument, la 2eme ne fait rien.
int reprendre (Entree &) override
Lecture d'un champ inconnue a partir d'un flot d'entree
en vue d'une reprise.
int sauvegarder (Sortie &) const override
Sauvegarde le champ inconnue sur un flot de sortie.
Ecrit un identifiant, les valeurs du champs, et
la date (le temps au moment de la sauvegarde).
Champ_base & affecter_compo (const Champ_base &, int compo) override
Affectation d'une composante d'un Champ quelconque<br>(Champ_base) dans une composante d'un champ inconnue.
Champ_base & affecter_ (const Champ_base &) override
Affectation d'un Champ generique (Champ_base) dans
un champ inconnue.
virtual void verifie_valeurs_cl ()
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ au temps courant.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temp courant<br>(version const)
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
Calcule la valeur du champs inconnue a la position specifiee.
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
Calcule les valeurs du champs inconnue aux positions specifiees.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
Calcule les valeurs du champs inconnue aux positions specifiees,
pour une certaine composante du champ.
int nb_valeurs_nodales () const override
Returns the number of "real" geometric positions of the
degrees of freedom, or -1 if not applicable (fields with multiple
localisations)
virtual int fixer_nb_valeurs_temporelles (int)
Fixe le nombre de valeurs temporelles a conserver.
(un nombre different suivant le schema en temps utilise)
Appelle Roue::fixer_nb_cases(int)
virtual int nb_valeurs_temporelles () const
Renvoie le nombre de valeurs temporelles actuellement conservees.
Cette valeur est stockee par la Roue du Champ_Inc_base.
double changer_temps_futur (double, int i=1)
Fixe le temps du ieme champ futur.
double changer_temps_passe (double, int i=1)
Fixe le temps du ieme champ passe.
double recuperer_temps_futur (int i=1) const
Retourne le temps du ieme champ futur.
double recuperer_temps_passe (int i=1) const
Retourne le temps du ieme champ passe.
DoubleTab & valeurs (double temps) override
Renvoie les valeurs du champs a l'instant temps.
const DoubleTab & valeurs (double temps) const override
Renvoie les valeurs du champs a l'instant temps.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
DoubleTab & futur (int i=1) override
Renvoie les valeurs du champs a l'instant t+i.
const DoubleTab & futur (int i=1) const override
Renvoie les valeurs du champs a l'instant t+i.
(version const)
DoubleTab & passe (int i=1) override
Renvoie les valeurs du champs a l'instant t-i.
const DoubleTab & passe (int i=1) const override
Renvoie les valeurs du champs a l'instant t-i.
(version const)
Champ_Inc_base & avancer (int i=1)
Avance le pointeur courant de i pas de temps,
dans la liste des valeurs temporelles conservees.
Champ_Inc_base & reculer (int i=1)
Recule le pointeur courant de i pas de temps,
dans la liste des valeurs temporelles conservees.
int lire_donnees (Entree &)
Lit les valeurs du champs a partir d'un flot d'entree.
Format de lecture:
int [LE NOMBRE DE VALEURS A LIRE]
[LIRE LE NOMBRE DE VALEUR VOULUES].
virtual void associer_eqn (const Equation_base &)
Associe le champ a l'equation dont il represente une inconnue.
Simple appel a MorEqn::associer_eqn(const Equation_base&)
virtual void associer_zone_cl_dis (const Zone_Cl_dis &)
int imprime (Sortie &, int) const override
int a_une_zone_dis_base () const override
Par defaut, on ne sait pas si une zone_dis_base sera definie.
const Zone_Cl_dis & zone_Cl_dis () const
Zone_Cl_dis & zone_Cl_dis ()
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
NE FAIT RIEN
Methode a surcharger.
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
Simple appel a:
Champ_Inc_base::remplir_coord_noeuds_et_polys(DoubleTab&,IntVect& poly)
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const =0
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
Simple appel a
Champ_Inc_base::remplir_coord_noeuds(DoubleTab&)
virtual double integrale_espace (int ncomp) const
const Domaine & domaine () const
const tabs_t & derivees () const
void init_champ_calcule (const Objet_U &obj, fonc_calc_t fonc)
void reset_champ_calcule ()
DoubleTab valeur_aux_bords () const override
renvoie la valeur du champ aux faces de bord
virtual void creer_espace_distant (int dummy)
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champ_implementation_P0
~Champ_implementation_P0 () override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
int imprime_P0 (Sortie &, int) const
Public Member Functions inherited from Champ_implementation_base
virtual ~Champ_implementation_base ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &domain, DoubleTab &result) const
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &domain, DoubleVect &result, int ncomp) const
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Elem_PolyMAC_P0 & self_cast (Objet_U &)
static const Champ_Elem_PolyMAC_P0 & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Elem_PolyMAC
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Elem_PolyMAC & self_cast (Objet_U &)
static const Champ_Elem_PolyMAC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Inc_P0_base
static const Type_info * info ()
static Champ_Inc_P0_base & self_cast (Objet_U &)
static const Champ_Inc_P0_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Inc_base
static const Type_info * info ()
static Champ_Inc_base & self_cast (Objet_U &)
static const Champ_Inc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
IntTab fgrad_d
IntTab fgrad_e
Tables used in zone_PolyMAC_P0::fgrad.
DoubleTab fgrad_w
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Elem_PolyMAC
static const Type_info info_obj
Static Public Attributes inherited from Champ_Inc_P0_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_Inc_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Champ_Elem_PolyMAC
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void init_fcl () const
Protected Member Functions inherited from Champ_Inc_P0_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Champ_base & le_champ (void) override
const Champ_base & le_champ (void) const override
Protected Member Functions inherited from Champ_Inc_base
Sortie & printOn (Sortie &x) const override
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Entree & readOn (Entree &) override
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
virtual void creer_tableau_distribue (const MD_Vector &, Array_base::Resize_Options=Array_base::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Champ_implementation_P0
Champ_base & le_champ (void) override=0
const Champ_base & le_champ (void) const override=0
DoubleTab & valeur_aux_sommets_impl (DoubleTab &result) const override
DoubleVect & valeur_aux_sommets_compo_impl (DoubleVect &result, int ncomp) const override
int affecter_ (const Champ_base &)
DoubleTab & trace (const Frontiere_dis_base &fr, const DoubleTab &y, DoubleTab &x, int distant) const
Protected Member Functions inherited from Champ_implementation_base
virtual DoubleTab & valeur_aux_sommets_impl (DoubleTab &result) const =0
virtual DoubleVect & valeur_aux_sommets_compo_impl (DoubleVect &result, int ncomp) const =0
const Zone_VF & get_zone_dis (void) const
const Zone & get_zone_geom (void) const
virtual Champ_base & le_champ (void)=0
virtual const Champ_base & le_champ (void) const =0
Protected Attributes
int grad_a_jour = 0
Protected Attributes inherited from Champ_Elem_PolyMAC
Ref_Zone_VF la_zone_VF
IntTab fcl_
int fcl_init_ = 0
Protected Attributes inherited from Champ_Inc_base
Roue_ptr les_valeurs
Ref_Zone_Cl_dis ma_zone_cl_dis
fonc_calc_t fonc_calc_
int fonc_calc_init_ = 0
Ref_Objet_U obj_calc_
DoubleTab val_bord_
tabs_t deriv_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
: class Champ_Elem_PolyMAC_P0
Champ correspondant a une inconnue scalaire (type temperature ou pression)
Degres de libertes : valeur aux elements + flux aux faces
Definition at line 34 of file Champ_Elem_PolyMAC_P0.h.
Constructor & Destructor Documentation
Champ_Elem_PolyMAC_P0()
Champ_Elem_PolyMAC_P0::Champ_Elem_PolyMAC_P0 ()
Definition at line 33 of file Champ_Elem_PolyMAC_P0.cpp.
~Champ_Elem_PolyMAC_P0()
Champ_Elem_PolyMAC_P0::~Champ_Elem_PolyMAC_P0 ()
Definition at line 33 of file Champ_Elem_PolyMAC_P0.cpp.
Member Function Documentation
affecter_()
Champ_base & Champ_Elem_PolyMAC_P0::affecter_ (const Champ_base & ch) inline override virtual
Reimplemented from Champ_Elem_PolyMAC.
Definition at line 43 of file Champ_Elem_PolyMAC_P0.h.
{ return Champ_Inc_P0_base::affecter_(ch); }
References Champ_Inc_P0_base::affecter_().
calc_grad()
void Champ_Elem_PolyMAC_P0::calc_grad (int full_stencil) const
Call to calculate the tables ; updates necessary.
< CAL du champ driver
Definition at line 84 of file Champ_Elem_PolyMAC_P0.cpp.
{
  if (grad_a_jour) return;
  const IntTab&             f_cl = fcl();
  const Zone_PolyMAC_P0&       zone = ref_cast(Zone_PolyMAC_P0, la_zone_VF.valeur());
  const Conds_lim&           cls = zone_Cl_dis().les_conditions_limites(); //!< CAL du champ  driver
  zone.fgrad(1, 0, cls, f_cl, NULL, NULL, 1, full_stencil, fgrad_d, fgrad_e, fgrad_w);
  grad_a_jour = 1;
}
References Champ_Elem_PolyMAC::fcl(), Zone_PolyMAC_P0::fgrad(), fgrad_d, fgrad_e, fgrad_w, grad_a_jour, Champ_Elem_PolyMAC::la_zone_VF, Zone_Cl_dis::les_conditions_limites(), ref_cast, Ref_Zone_VF::valeur(), and Champ_Inc_base::zone_Cl_dis().
cree_instance()
Objet_U * Champ_Elem_PolyMAC_P0::cree_instance () static
Definition at line 33 of file Champ_Elem_PolyMAC_P0.cpp.
duplique()
int Champ_Elem_PolyMAC_P0::duplique () const override virtual
Reimplemented from Champ_Elem_PolyMAC.
Definition at line 33 of file Champ_Elem_PolyMAC_P0.cpp.
get_info()
const Type_info * Champ_Elem_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Elem_PolyMAC.
Definition at line 33 of file Champ_Elem_PolyMAC_P0.cpp.
info()
const Type_info * Champ_Elem_PolyMAC_P0::info () static
Definition at line 33 of file Champ_Elem_PolyMAC_P0.cpp.
init_auxiliary_variables()
void Champ_Elem_PolyMAC_P0::init_auxiliary_variables () inline override virtual
Reimplemented from Champ_Elem_PolyMAC.
Definition at line 42 of file Champ_Elem_PolyMAC_P0.h.
{ };
init_grad()
void Champ_Elem_PolyMAC_P0::init_grad (int full_stencil) const
Call to initialise the tables ; no updates necessary.
< CAL du champ driver
Definition at line 75 of file Champ_Elem_PolyMAC_P0.cpp.
{
  if (fgrad_d.size()) return;
  const IntTab&             f_cl = fcl();
  const Zone_PolyMAC_P0&       zone = ref_cast(Zone_PolyMAC_P0, la_zone_VF.valeur());
  const Conds_lim&           cls = zone_Cl_dis().les_conditions_limites(); //!< CAL du champ  driver
  zone.fgrad(1, 0, cls, f_cl, NULL, NULL, 1, full_stencil, fgrad_d, fgrad_e, fgrad_w);
}
References Champ_Elem_PolyMAC::fcl(), Zone_PolyMAC_P0::fgrad(), fgrad_d, fgrad_e, fgrad_w, Champ_Elem_PolyMAC::la_zone_VF, Zone_Cl_dis::les_conditions_limites(), ref_cast, TRUSTVect< _TYPE_ >::size(), Ref_Zone_VF::valeur(), and Champ_Inc_base::zone_Cl_dis().
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs().
mettre_a_jour()
void Champ_Elem_PolyMAC_P0::mettre_a_jour (double temps) inline override virtual
Effectue une mise a jour en temps du champ inconnue.
WEC : Maintenant si on l'appelle 2 fois de suite avec le meme
argument, la 2eme ne fait rien.
Reimplemented from Champ_Inc_base.
Definition at line 69 of file Champ_Elem_PolyMAC_P0.cpp.
{
  if (temps()!=tps) grad_a_jour = 0 ;
  Champ_Inc_P0_base::mettre_a_jour(tps);
}
References grad_a_jour, Champ_Inc_base::mettre_a_jour(), and Champ_base::temps().
printOn()
Sortie & Champ_Elem_PolyMAC_P0::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Champ_Elem_PolyMAC.
Definition at line 37 of file Champ_Elem_PolyMAC_P0.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Elem_PolyMAC_P0::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_Elem_PolyMAC.
Definition at line 45 of file Champ_Elem_PolyMAC_P0.cpp.
{
  lire_donnees(s) ;
  return s ;
}
References Champ_Inc_base::lire_donnees().
self_cast() [1/2]
const Champ_Elem_PolyMAC_P0 & Champ_Elem_PolyMAC_P0::self_cast (const Objet_U & r) static
Definition at line 33 of file Champ_Elem_PolyMAC_P0.cpp.
self_cast() [2/2]
Champ_Elem_PolyMAC_P0 & Champ_Elem_PolyMAC_P0::self_cast (Objet_U & r) static
Definition at line 33 of file Champ_Elem_PolyMAC_P0.cpp.
taille_memoire()
unsigned Champ_Elem_PolyMAC_P0::taille_memoire () const override virtual
Reimplemented from Champ_Elem_PolyMAC.
Definition at line 33 of file Champ_Elem_PolyMAC_P0.cpp.
zone_PolyMAC_P0()
const Zone_PolyMAC_P0 & Champ_Elem_PolyMAC_P0::zone_PolyMAC_P0 () const
Returns
la_zone_PolyMAC_P0_P0.valeur()
Signification:
Contraintes:
Definition at line 64 of file Champ_Elem_PolyMAC_P0.cpp.
{
  return ref_cast(Zone_PolyMAC_P0, la_zone_VF.valeur());
}
References Champ_Elem_PolyMAC::la_zone_VF, ref_cast, and Ref_Zone_VF::valeur().
Member Data Documentation
fgrad_d
IntTab Champ_Elem_PolyMAC_P0::fgrad_d mutable
Definition at line 46 of file Champ_Elem_PolyMAC_P0.h.
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), calc_grad(), and init_grad().
fgrad_e
IntTab Champ_Elem_PolyMAC_P0::fgrad_e
Tables used in zone_PolyMAC_P0::fgrad.
Definition at line 46 of file Champ_Elem_PolyMAC_P0.h.
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), calc_grad(), and init_grad().
fgrad_w
DoubleTab Champ_Elem_PolyMAC_P0::fgrad_w mutable
Definition at line 47 of file Champ_Elem_PolyMAC_P0.h.
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), calc_grad(), and init_grad().
grad_a_jour
int Champ_Elem_PolyMAC_P0::grad_a_jour = 0 mutable protected
Definition at line 54 of file Champ_Elem_PolyMAC_P0.h.
Referenced by calc_grad(), and mettre_a_jour().
info_obj
const Type_info Champ_Elem_PolyMAC_P0::info_obj static
Definition at line 36 of file Champ_Elem_PolyMAC_P0.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Champs/Champ_Elem_PolyMAC_P0.h
src/PolyMAC/Champs/Champ_Elem_PolyMAC_P0.cpp