TRUST: Precond_base Class Reference
Precond_base Class Reference abstract
#include <Precond_base.h>
Public Types
enum Init_Status { READY = 0 , REINIT_COEFF = 1 , REINIT_ALL = 2 }
Public Member Functions
~Precond_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Precond_base ()
void reinit (Init_Status x=REINIT_ALL)
this method must be called before preconditionner() whenever
the matrix changes (coefficients only or coefficients and structure) to
tell the object to recompute some matrix related data.
void set_echange_espace_virtuel_resultat (int flag)
Call this method to change the behaviour of the preconditionner() method
0-> result will not have an up-to-date virtual space
1-> yes it will (this must be the default value in the implementation)
int preconditionner (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)
Call to the prepare() method if reinit() has been called previously, then
call to preconditionner_()...
If echange_ev_solution is not zero, the solution vector will have an updated virtual space.
void prepare (const Matrice_Base &, const DoubleVect &src)
prepares the preconditionner if needed after a matrix change (reinit() call).
prepare() is public, in case we want to perform preparation separately from preconditionning (eg nested solvers)
but calling prepare() is not mandatory (done automatically in preconditionner())
m is the new matrix, and md is the descriptor of the solution vector.
virtual int supporte_matrice_morse_sym ()
returns 1 if the implementation accepts Matrice_Morse_Sym matrices, otherwise 0.
(must be reimplemented if answer is 0)
Init_Status get_status ()
virtual int get_flag_updated_input () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Precond_base & self_cast (Objet_U &)
static const Precond_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int preconditionner_ (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)=0
virtual void prepare_ (const Matrice_Base &, const DoubleVect &)
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int echange_ev_solution_
Private Attributes
Init_Status status_
Detailed Description
Definition at line 25 of file Precond_base.h.
Member Enumeration Documentation
Init_Status
enum Precond_base::Init_Status
Enumerator
READY
REINIT_COEFF
REINIT_ALL
Definition at line 30 of file Precond_base.h.
{ READY = 0, REINIT_COEFF = 1, REINIT_ALL = 2 };
Constructor & Destructor Documentation
~Precond_base()
Precond_base::~Precond_base () override
Definition at line 19 of file Precond_base.cpp.
Precond_base()
Precond_base::Precond_base ()
Definition at line 21 of file Precond_base.cpp.
{
  status_ = REINIT_ALL;
  echange_ev_solution_ = 1;
}
References echange_ev_solution_, REINIT_ALL, and status_.
Member Function Documentation
get_flag_updated_input()
virtual int Precond_base::get_flag_updated_input () const inline virtual
Reimplemented in SSOR.
Definition at line 42 of file Precond_base.h.
{ return 1; }
Referenced by Solv_GCP::resoudre_().
get_info()
const Type_info * Precond_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Precond_local, PrecondA, PrecondSolv, and SSOR.
Definition at line 19 of file Precond_base.cpp.
get_status()
Init_Status Precond_base::get_status () inline
Definition at line 40 of file Precond_base.h.
{ return status_; }
References status_.
Referenced by ILU::prepare_(), SSOR::prepare_(), and PrecondA::prepare_().
info()
const Type_info * Precond_base::info () static
Definition at line 19 of file Precond_base.cpp.
preconditionner()
int Precond_base::preconditionner (const Matrice_Base & m, const DoubleVect & src, DoubleVect & solution)
Call to the prepare() method if reinit() has been called previously, then
call to preconditionner_()...
If echange_ev_solution is not zero, the solution vector will have an updated virtual space.
Definition at line 79 of file Precond_base.cpp.
{
  if (status_ != READY)
    prepare(m, src);
// implementation of the prepare() method must call ancestor methods until Precond_base::prepare();
  assert(status_ == READY);
  int ok = preconditionner_(m, src, solution);
  return ok;
}
References preconditionner_(), prepare(), READY, and status_.
Referenced by Testeur::interpreter(), Precond::preconditionner(), and Solv_GCP::resoudre_().
preconditionner_()
virtual int Precond_base::preconditionner_ (const Matrice_Base & , const DoubleVect & src, DoubleVect & solution) protected pure virtual
Implemented in ILU, Precond_local, PrecondSolv, SSOR, and PrecondA.
Referenced by preconditionner().
prepare()
void Precond_base::prepare (const Matrice_Base & m, const DoubleVect & src)
prepares the preconditionner if needed after a matrix change (reinit() call).
prepare() is public, in case we want to perform preparation separately from preconditionning (eg nested solvers)
but calling prepare() is not mandatory (done automatically in preconditionner())
m is the new matrix, and md is the descriptor of the solution vector.
Definition at line 93 of file Precond_base.cpp.
{
  if (status_ != READY)
    prepare_(m, v);
  assert(status_ == READY);
}
References prepare_(), READY, and status_.
Referenced by preconditionner(), and prepare_precond().
prepare_()
void Precond_base::prepare_ (const Matrice_Base & m, const DoubleVect & v) protected virtual
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
Reimplemented in ILU, Precond_local, SSOR, PrecondA, and PrecondSolv.
Definition at line 104 of file Precond_base.cpp.
{
  status_ = READY;
}
References READY, and status_.
Referenced by prepare(), ILU::prepare_(), Precond_local::prepare_(), SSOR::prepare_(), PrecondA::prepare_(), and PrecondSolv::prepare_().
printOn()
Sortie & Precond_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Precond_local, PrecondA, PrecondSolv, and SSOR.
Definition at line 27 of file Precond_base.cpp.
{
  return s  << que_suis_je();
}
References Objet_U::que_suis_je().
readOn()
Entree & Precond_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Precond_local, PrecondA, PrecondSolv, and SSOR.
Definition at line 32 of file Precond_base.cpp.
{
  return is;
}
reinit()
void Precond_base::reinit (Init_Status x = REINIT_ALL)
this method must be called before preconditionner() whenever
the matrix changes (coefficients only or coefficients and structure) to
tell the object to recompute some matrix related data.
Definition at line 40 of file Precond_base.cpp.
{
  switch(x)
    {
    case READY:
      break;
    case REINIT_COEFF:
      if (status_ != REINIT_ALL) status_ = REINIT_COEFF;
      break;
    case REINIT_ALL:
      status_ = REINIT_ALL;
      break;
    default:
      Cerr << "Error Precond_base::reinit" << finl;
      exit();
    }
}
References Cerr, Process::exit(), finl, READY, REINIT_ALL, REINIT_COEFF, and status_.
Referenced by prepare_precond(), Solv_GCP::reinit(), Solv_Gen::reinit(), and SSOR::set_omega().
self_cast() [1/2]
const Precond_base & Precond_base::self_cast (const Objet_U & r) static
Definition at line 19 of file Precond_base.cpp.
self_cast() [2/2]
Precond_base & Precond_base::self_cast (Objet_U & r) static
Definition at line 19 of file Precond_base.cpp.
set_echange_espace_virtuel_resultat()
void Precond_base::set_echange_espace_virtuel_resultat (int flag)
Call this method to change the behaviour of the preconditionner() method
0-> result will not have an up-to-date virtual space
1-> yes it will (this must be the default value in the implementation)
Definition at line 71 of file Precond_base.cpp.
{
  echange_ev_solution_ = flag;
}
References echange_ev_solution_.
supporte_matrice_morse_sym()
int Precond_base::supporte_matrice_morse_sym () virtual
returns 1 if the implementation accepts Matrice_Morse_Sym matrices, otherwise 0.
(must be reimplemented if answer is 0)
Reimplemented in PrecondA, and PrecondSolv.
Definition at line 60 of file Precond_base.cpp.
{
  return 1;
}
Referenced by Precond::supporte_matrice_morse_sym().
Member Data Documentation
echange_ev_solution_
int Precond_base::echange_ev_solution_ protected
Definition at line 51 of file Precond_base.h.
Referenced by Precond_base(), PrecondSolv::preconditionner_(), SSOR::preconditionner_(), and set_echange_espace_virtuel_resultat().
info_obj
const Type_info Precond_base::info_obj static
Definition at line 27 of file Precond_base.h.
status_
Init_Status Precond_base::status_ private
Definition at line 54 of file Precond_base.h.
Referenced by get_status(), Precond_base(), preconditionner(), prepare(), prepare_(), and reinit().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/Precond_base.h
src/Kernel/Math/SolvSys/Precond_base.cpp