TRUST: ScatterMED Class Reference
ScatterMED Class Reference
#include <ScatterMED.h>
Public Member Functions
ScatterMED ()
~ScatterMED ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void lire_domaine (Nom &, Noms &liste_bords_periodiques) override
Lit le domaine dans le fichier de nom "nomentree",
de type LecFicDistribueBin ou LecFicDistribue<br>(selon fichier_zone_format_binaire_)
Le format historique n'est plus supporte.
Format attendu : Domaine::ReadOn
La zone est renommee comme le domaine (pour lance_test_seq_par)
Public Member Functions inherited from Scatter
~Scatter ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Scatter ()
Entree & interpreter (Entree &) override
Lit et complete un domaine parallele selon les motcles lus
dans le jeu de donnees. Format:
Scatter [debug] file_name domain_name
On lit les sommets, les elements et les sommets et faces de joint,
On construit les espaces distants et virtuels en fonction
de l'epaisseur de joint.
virtual void lire_domaine (Nom &, Noms &liste_bords_periodiques)
Lit le domaine dans le fichier de nom "nomentree",
de type LecFicDistribueBin ou LecFicDistribue
Format attendu : Domaine::ReadOn
La zone est renommee comme le domaine (pour lance_test_seq_par)
Domaine & domaine ()
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static ScatterMED & self_cast (Objet_U &)
static const ScatterMED & self_cast (const Objet_U &)
Static Public Member Functions inherited from Scatter
static Objet_U * cree_instance ()
static const Type_info * info ()
static Scatter & self_cast (Objet_U &)
static const Scatter & self_cast (const Objet_U &)
static int Chercher_Correspondance (const DoubleTab &sommets1, const DoubleTab &sommets2, ArrOfInt &correspondance, const double epsilon)
Construit le tableau "correspondance" tel que
Pour 0 <= i < sommets2.size_array(),
Si sommet2(i) existe dans le tableau sommet1, alors
sommets2(i, ...) == sommets1(correspondance[i], ...)
Sinon
correspondance[i] = -1
L'egalite est verifiee a epsilon pres en absolu (soit abs(x1-x2)<epsilon)
L'algorithme est generalement en n1*log(n1) + n2*log(n1)
(recherche basee sur un quicksort).
En cas d'echec du tri, on utilise un algorithme en n1*n2.
Les tableaux sommets1 et sommets2 doivent etre de dimension 2
Le tableau correspondance doit etre de taille sommets2.size_array().
Valeur de retour: nombre de sommets de sommets2 non trouves dans le tableau sommets1.
static void construire_correspondance_sommets_par_coordonnees (Domaine &dom)
Construction des tableaux joint_item(Joint::SOMMET).items_communs de tous les joints de la zone(0) du domaine dom.
static void construire_correspondance_aretes_par_coordonnees (Zone_VF &zvf)
static void construire_correspondance_items_par_coordonnees (Joints &joints, const Joint::Type_Item type_item, const DoubleTab &coord_items)
Methode obsolete (utilisee avec l'ancien decoupeur).
On suppose que le domaine contient les structures suivantes:
* zone(0).faces_joint[i].sommets() (les sommets de joint isoles)
* zone(0).faces_joint[i].faces().les_sommets (les sommets des faces de joint)
et que chaque processeur contient une portion d'un domaine complet.
On remplit les tableaux joint_item(Joint::Type_Item).items_communs pour tous les joints de la
zone 0 du domaine et renum_items_communs.
Ordre d'apparition des items : ordre croissant de l'indice du
sommet sur le processeur de rang le plus petit
Cette methode doit etre appelee simultanement sur tous les processeurs
du groupe et ne s'applique qu'aux items ARETE et SOMMET
L'algorithme utilise les coordonnees des items pour retrouver la
correspondance entre les items de joint.
static void construire_structures_paralleles (Domaine &dom, const Noms &liste_bords_perio)
Construction des structures paralleles du domaine et de la zone
(determination des elements distants en fonction de l'epaisseur de joint,
determination des sommets distants,
creation des sommets et des elements virtuels)
static void calculer_espace_distant (Zone &zone, const int nb_items_reels, const ArrsOfInt &items_to_send, const Joint::Type_Item type_item)
Determination des items distants en fonction d'une liste d'items
a envoyer et de listes d'items communs.
exemple:
calculer_espace_distant_sommets
calculer_espace_distant_faces
Pour les sommets: les "items_to_send" sont les sommets des elements distants,
Si le processeur A veut que le processeur B connaisse le sommet i,
il faut que le processeur qui possede le sommet l'envoie a B.
Le processeur qui "possede" le sommet est le plus petit parmi les PEs
qui partagent ce sommet (item commun) (requis pour pouvoir faire
echange_item_commun et echange_espace_virtuel en une seule passe).
De plus, si plusieurs processeurs demandent a envoyer le meme sommet
au meme processeur, il ne faut l'inserer qu'une seule fois dans l'espace
distant.
Parametre: joints
Signification: les joints dans lesquels on veut calculer un espace distant
Parametre: nb_items_reels
Signification: le nombre d'items reels (sommets, faces, ...)
Parametre: items_to_send
Signification: un vecteur de "nproc()" tableaux, pour chaque processeur,
la liste des items qu'on veut lui envoyer (exemple:tous les sommets des
elements distants, ou toutes les faces)
Parametre: type_item
Signification: les items dont on veut calculer l'espace distant.
static void calculer_nb_items_virtuels (Joints &joints, const Joint::Type_Item type_item)
!< Description Pour un item geometrique "type_item", remplit le champ nb_items_virtuels_ des joints en fonction du nombre d'items distants : Le nombre d'items virtuels sur un joint i du processeur j est le nombre d'items distants du joint j sur le processeur i.
static void calculer_renum_items_communs (Joints &joints, const Joint::Type_Item type_item)
On suppose que chaque joint[i].joint_item(type_item).items_communs()
contient les indices locaux des items de joint communs dans le meme
ordre sur les deux processeurs (local et voisin)
On remplit renum_items_communs :
colonne 0=contenu du tableau items_communs sur le PE voisin
colonne 1=contenu du tableau items_communs sur le PE local.
static void calculer_espace_distant_faces (Zone &zone, const int nb_faces_reelles, const IntTab &elem_faces)
Idem que Scatter::calculer_espace_distant_sommets pour les faces.
static void calculer_espace_distant_aretes (Zone &zone, const int nb_aretes_reelles, const IntTab &elem_aretes)
Idem que Scatter::calculer_espace_distant_sommets pour les aretes.
static void calculer_espace_distant_elements (Domaine &dom)
Remplissage du tableau "espace_distant()" des elements dans les joints.
C'est ici qu'on determine les elements de joint en fonction de l'epaisseur de joint.
Le tableau espace_distant contient les
indices locaux des elements distants (a envoyer aux processeurs voisins)
Pour un joint d'epaisseur 1, ce sont tous les elements voisins d'un
sommet de joint (sommet sur un face de joint ou sommet isole).
Pour un joint d'epaisseur n>1, ce sont tous les elements voisins d'un
sommet d'un element du joint d'epaisseur n-1.
Le voisinage s'entend sur le domaine global (toutes zones confondues)
Historique: premiere version B.Mathieu le 16/01/2007.
Il existe une methode qui determine les elements distants au moment du decoupage<br>(DomaineCutter::construire_elements_distants_ssdom).
La methode ci-dessous a ete validee par comparaison avec la methode du decoupeur.
Les sorties ont ete verifiees pour des epaisseurs jusqu'a 5 sur des maillages tetra.
La difficulte de l'algorithme est d'obtenir les elements virtuels d'epaisseur > 1 qui se
trouvent sur des sous-domaines qui ne sont pas en contact direct avec le sous-domaine
local. Difficulte resolue par l'algorithme ci-dessous.
static void corriger_espace_distant_elements_perio (Domaine &dom, const Noms &liste_bords_periodiques)
Les algorithmes actuels pour le periodique (assembleur P1B, OpDivElem P1B)
ont besoin que pour chaque face virtuelle periodique, la face opposee soit
aussi virtuelle. Ceci n'est pas assure a la sortie de la methode
calculer_elements_distants. Cette methode ajoute aux elements distants les
elements manquants pour assurer cette condition:
Si un element est distant pour un PE donne est voisin d'une face periodique,
on ajoute a l'espace distant l'element adjacent a la face opposee.
static void calculer_espace_distant_sommets (Domaine &dom, const Noms &liste_bords_periodiques)
En fonction de l'espace distant des elements, calcule l'espace
distant des sommets. Pour chaque joint, on envoie au processeur voisin
l'ensemble des sommets de tous les elements du joint.
C'est le processeur proprietaire du sommet<br>(plus petit pe qui le possede) qui le met dans son espace distant.
Attention, on cree de nouveaux joints.
On remplit les tableaux
dom.zone(0).faces_joint(i).joint_item(Joint::SOMMET).items_distants();.
static void construire_espace_virtuel_traduction (const MD_Vector &md_indice, const MD_Vector &md_valeur, IntTab &tableau, const int error_is_fatal=1)
Construit la structure items_communs + espaces virtuels d'un tableau contenant
des indices d'items geometriques, indexe par un autre type d'item geometrique.
Exemple: tableau indexe par md_indice, contenant des indices md_valeur:
type_indice type_valeur exemple de tableau:
element sommet zone.les_elems()
face sommet faces_sommets
element face elem_faces
face element faces_voisins
element element ?
element arete elem_aretes
Nb_valeurs_max est le nombre d'items reels de type "type_valeur".
static void reordonner_faces_de_joint (Domaine &dom)
Reordonne les faces de joint de sorte qu'elles apparaissent dans le meme
ordre sur chaque couple de processeur voisin. En pratique, pour un couple
pe1 < pe2, pe1 envoie ses faces de joint a pe2 et pe2 les traduit en indices
de sommets locaux. Les faces de joint du PE2 ne sont donc pas utilisees.
static void ajouter_joints (Zone &zone, ArrOfInt &pe_voisins)
Ajoute des joints avec tous les pe de pe_voisins.
Pour que l'ensemble des joints soit symetrique,
on en cree aussi un joint sur le processeur destination:
Si A ajoute un joint avec B, alors B ajoute un joint avec A.
On trie les joints par ordre croissant du numero de PE.
ATTENTION: les joints sont donc reordonnes !
On met dans pe_voisins la liste des joints effectivement crees.
static void trier_les_joints (Joints &joints)
Tri des joints dans l'ordre croissant des processeurs.
static void construire_md_vector (const Domaine &, int nb_items_reels, const Joint::Type_Item, MD_Vector &)
construction d'un MD_Vector_std a partir des informations de joint du domaine
pour le type d'item demande.
static void init_sequential_domain (Domaine &)
cree des descripteurs sequentiels pour les tableaux sommets
et elements du domaine (necessaire car Scatter n'est pas appele pour les
domaines en sequentiel)
static void uninit_sequential_domain (Domaine &)
methode utilisee par les interpretes qui modifient le domaine<br>(sequentiel), detruit les descripteurs des sommets et elements pour permettre
la modification de ces tableaux.
static void check_consistancy_remote_items (Domaine &dom, const ArrOfInt &mergedZones)
Merged zones receive joints information from their neighbours
to ensure that their common items (vertices) appear in the same order
If it's not the case, the merged zone reorders its common items so that it matches the neighbour's order
When 2 neighbouring zones have each been merged,
only the processor with the lowest rank proceeds to reordering.
static void readDomainWithoutCollComm (Domaine &dom, Entree &fic)
Does the exact same thing as the readOn of the class Domaine
but without collective communication
Necessary when the processors don't have the same numbers of file to read.
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Scatter
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Scatter
Ref_Domaine le_domaine
Detailed Description
Definition at line 22 of file ScatterMED.h.
Constructor & Destructor Documentation
ScatterMED()
ScatterMED::ScatterMED ()
Definition at line 22 of file ScatterMED.cpp.
~ScatterMED()
ScatterMED::~ScatterMED ()
Definition at line 22 of file ScatterMED.cpp.
Member Function Documentation
cree_instance()
Objet_U * ScatterMED::cree_instance () static
Definition at line 22 of file ScatterMED.cpp.
duplique()
int ScatterMED::duplique () const override virtual
Reimplemented from Scatter.
Definition at line 22 of file ScatterMED.cpp.
get_info()
const Type_info * ScatterMED::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Scatter.
Definition at line 22 of file ScatterMED.cpp.
info()
const Type_info * ScatterMED::info () static
Definition at line 22 of file ScatterMED.cpp.
lire_domaine()
void ScatterMED::lire_domaine (Nom & nomentree, Noms & liste_bords_periodiques) override virtual
Lit le domaine dans le fichier de nom "nomentree",
de type LecFicDistribueBin ou LecFicDistribue<br>(selon fichier_zone_format_binaire_)
Le format historique n'est plus supporte.
Format attendu : Domaine::ReadOn
La zone est renommee comme le domaine (pour lance_test_seq_par)
Reimplemented from Scatter.
Definition at line 57 of file ScatterMED.cpp.
{
  Nom fichiermed(nomentree);
  fichiermed.prefix(".med");
  Nom n(me()+1);
  fichiermed+=n;
  fichiermed+=".med";
  Domaine& dom = domaine();
  LireMED lire_med;
  Nom nom_lu(dom.le_nom());
  nom_lu+="_";
  nom_lu+=n;
  lire_med.lire_geom(fichiermed,dom,nom_lu,dom.le_nom());
// Renseigne dans quel fichier le domaine a ete lu
  dom.set_fichier_lu(nomentree);
// On renomme la zone (important pour le format lml:
// nom de la topologie utilise par lance_test_seq_par)
  const Nom& nom_dom = dom.le_nom();
  dom.zone(0).nommer(nom_dom);
// fichier >> liste_bords_periodiques;
// fichier.close();
  if (0)
    {
      Nom org=("debug.Zones");
      org=org.nom_me(me());
      SFichier  file_out(org);
      file_out << dom << finl<<"0 "<<finl;
    }
  barrier();
}
References Process::barrier(), Scatter::domaine(), finl, Domaine::le_nom(), LireMED::lire_geom(), Process::me(), Nom::nom_me(), Zone::nommer(), Nom::prefix(), Domaine::set_fichier_lu(), and Domaine::zone().
printOn()
Sortie & ScatterMED::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Scatter.
Definition at line 39 of file ScatterMED.cpp.
{
  return Scatter::printOn(os);
}
References Scatter::printOn().
readOn()
Entree & ScatterMED::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Scatter.
Definition at line 44 of file ScatterMED.cpp.
{
  return Scatter::readOn(is);
}
References Scatter::readOn().
self_cast() [1/2]
const ScatterMED & ScatterMED::self_cast (const Objet_U & r) static
Definition at line 22 of file ScatterMED.cpp.
self_cast() [2/2]
ScatterMED & ScatterMED::self_cast (Objet_U & r) static
Definition at line 22 of file ScatterMED.cpp.
taille_memoire()
unsigned ScatterMED::taille_memoire () const override virtual
Reimplemented from Scatter.
Definition at line 22 of file ScatterMED.cpp.
Member Data Documentation
info_obj
const Type_info ScatterMED::info_obj static
Definition at line 24 of file ScatterMED.h.
The documentation for this class was generated from the following files:
src/Kernel/MEDimpl/ScatterMED.h
src/Kernel/MEDimpl/ScatterMED.cpp