TRUST: Quadri_CoviMAC Class Reference
Quadri_CoviMAC Class Reference
#include <Quadri_CoviMAC.h>
Public Member Functions
~Quadri_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Quadri_CoviMAC ()
KEL_(0,fa7),KEL_(1,fa7) sont les numeros locaux des 2 faces
qui entourent la facette de numero local fa7
le numero local de la fa7 est celui du sommet qui la porte.
void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int) const
void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=2, n1 est le numero du sommet confondu avec G
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const
remplit le tableau face_normales dans la Zone_CoviMAC
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Quadri_CoviMAC & self_cast (Objet_U &)
static const Quadri_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 30 of file Quadri_CoviMAC.h.
Constructor & Destructor Documentation
Quadri_CoviMAC::~Quadri_CoviMAC ()
Definition at line 26 of file Quadri_CoviMAC.cpp.
Quadri_CoviMAC::Quadri_CoviMAC ()
KEL_(0,fa7),KEL_(1,fa7) sont les numeros locaux des 2 faces
qui entourent la facette de numero local fa7
le numero local de la fa7 est celui du sommet qui la porte.
Definition at line 44 of file Quadri_CoviMAC.cpp.
{
}
Member Function Documentation
void Quadri_CoviMAC::calcul_vc (const ArrOfInt & Face, ArrOfDouble & vc, const ArrOfDouble & vs, const DoubleTab & vsom, const Champ_Inc_base & vitesse, int type_cl) const
Definition at line 134 of file Quadri_CoviMAC.cpp.
{
// Cerr << " DANS Quadri_CoviMAC::calcul_vc , type_cl = " << type_cl << finl;
// Cerr << "vs " << vs << " et vsom " << vsom << " et vitesse " << vitesse << finl;
// switch(type_cl) {
// case 0: //  pas de Face de Dirichlet
// {
  vc[0] = vs[0]*0.25;
  vc[1] = vs[1]*0.25;
// break;
// }
// case 1: // une Face de Dirichlet : Face 3
// {
// vc[0] = vitesse(Face[3],0);
// vc[1] = vitesse(Face[3],1);
// break;
// }
// case 3: // une Face de Dirichlet : Face 2
// {
// vc[0] = vitesse(Face[2],0);
// vc[1] = vitesse(Face[2],1);
// break;
// }
// case 9: // une Face de Dirichlet : Face 1
// {
// vc[0] = vitesse(Face[1],0);
// vc[1] = vitesse(Face[1],1);
// break;
// }
// case 27: // une Faces de Dirichlet :Face 0
// {
// vc[0] = vitesse(Face[0],0);
// vc[1] = vitesse(Face[0],1);
// break;
// }
// case 4: // deux Faces de Dirichlet : Faces 2,3
// {
// vc[0]= vsom(3,0);
// vc[1]= vsom(3,1);
// break;
// }
// case 28: // deux Faces de Dirichlet : Faces 0,3
// {
// vc[0]= vsom(2,0);
// vc[1]= vsom(2,1);
// break;
// }
// case 12: // deux Faces de Dirichlet : Faces 1,2
// {
// vc[0]= vsom(1,0);
// vc[1]= vsom(1,1);
// break;
// }
// case 36: // deux Faces de Dirichlet : Faces 0,1
// {
// vc[0]= vsom(0,0);
// vc[1]= vsom(0,1);
// break;
// }
// case 10: // deux Faces de Dirichlet : Faces 1,3
// {
// vc[0] = vs[0]*0.25;
// vc[1] = vs[1]*0.25;
// break;
// }
// case 30: // deux Faces de Dirichlet : Faces 0,2
// {
// vc[0] = vs[0]*0.25;
// vc[1] = vs[1]*0.25;
// break;
// }
// case 13: //trois Faces de Dirichlet : Faces 3,2,1
// {
// vc[0]= vitesse(Face[2],0);
// vc[1]= vitesse(Face[2],1);
// break;
// }
// case 31: //trois Faces de Dirichlet : Faces 0,3,2
// {
// vc[0]= vitesse(Face[3],0);
// vc[1]= vitesse(Face[3],1);
// break;
// }
// case 37: //trois Faces de Dirichlet : Faces 1,0,3
// {
// vc[0]= vitesse(Face[0],0);
// vc[1]= vitesse(Face[0],1);
// break;
// }
// case 39: //trois Faces de Dirichlet : Faces 2,1,0
// {
// vc[0]= vitesse(Face[1],0);
// vc[1]= vitesse(Face[1],1);
// break;
// }
// default :
// {
// Cerr << "\n  type inconnu : " << type_cl ;
// exit();
// }
// } // fin du switch
}
void Quadri_CoviMAC::calcul_xg (DoubleVect & xg, const DoubleTab & x, const int type_elem_Cl, int & idirichlet, int & n1, int & , int &) const
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=2, n1 est le numero du sommet confondu avec G
Definition at line 262 of file Quadri_CoviMAC.cpp.
References DoubleVect::size().
{
  int j,dim=xg.size();
// switch(type_elem_Cl) {
// case 0:  //  pas de Face de dirichlet: il a 4 Facettes
// //  le point G est le barycentre des sommets du triangle
// {
  for (j=0; j<dim; j++)
    xg[j]=(x(0,j)+x(1,j)+x(2,j)+x(3,j))*0.25;
  idirichlet=0;
// break;
// }
// case 1: // une Face de Dirichlet : Face 3
// // le point G est le centre de la face 3
// {
// for (j=0; j<dim; j++)
// xg[j]=(x(2,j)+x(3,j))*0.5;
// idirichlet=1;
// break;
// }
// case 3: // une Face de Dirichlet : Face 2
// // le point G est le centre de la face 2
// {
// for (j=0; j<dim; j++)
// xg[j]=(x(1,j)+x(3,j))*0.5;
// idirichlet=1;
// break;
// }
// case 9: // une Face de Dirichlet : Face 1
// // le point G est le centre de la face 1
// {
// for (j=0; j<dim; j++)
// xg[j]=(x(0,j)+x(1,j))*0.5;
// idirichlet=1;
// break;
// }
// case 27: // une Faces de Dirichlet :Face 0
// // le point G est le centre de la face 0
// {
// for (j=0; j<dim; j++)
// xg[j]=(x(0,j)+x(2,j))*0.5;
// idirichlet=1;
// break;
// }
// case 4: // deux Faces de Dirichlet : Faces 2,3
// //le point G est le sommet commun au deux faces de dirichlet
// {
// for (j=0; j<dim; j++)
// xg[j]=x(3,j);
// idirichlet=2;
// break;
// }
// case 28: // deux Faces de Dirichlet : Faces 0,3
// //le point G est le sommet commun au deux faces de dirichlet
// {
// for (j=0; j<dim; j++)
// xg[j]=x(2,j);
// idirichlet=2;
// break;
// }
// case 12: // deux Faces de Dirichlet : Faces 1,2
// //le point G est le sommet commun au deux faces de dirichlet
// {
// for (j=0; j<dim; j++)
// xg[j]=x(1,j);
// idirichlet=2;
// break;
// }
// case 36: // deux Faces de Dirichlet : Faces 0,1
// //le point G est le sommet commun au deux faces de dirichlet
// {
// for (j=0; j<dim; j++)
// xg[j]=x(0,j);
// idirichlet=2;
// break;
// }
// case 10: // deux Faces de Dirichlet : Faces 1,3
// // on garde les memes volumes de controles que pour des faces internes
// {
// for (j=0; j<dim; j++)
// xg[j]=(x(0,j)+x(1,j)+x(2,j)+x(3,j))*0.25;
// idirichlet=0;
// break;
// }
// case 30: // deux Faces de Dirichlet : Faces 0,2
// // on garde les memes volumes de controles que pour des faces internes
// {
// for (j=0; j<dim; j++)
// xg[j]=(x(0,j)+x(1,j)+x(2,j)+x(3,j))*0.25;
// idirichlet=0;
// break;
// }
// case 13: //trois Faces de Dirichlet : Faces 3,2,1
// // le point G est le centre de la face de dirichlet opposee a la face non-dirichlet
// {
// for (j=0; j<dim; j++)
// xg[j]=(x(1,j)+x(3,j))*0.5;
// idirichlet=3;
// break;
// }
// case 31: //trois Faces de Dirichlet : Faces 0,3,2
// // le point G est le centre de la face de dirichlet opposee a la face non-dirichlet
// {
// for (j=0; j<dim; j++)
// xg[j]=(x(2,j)+x(3,j))*0.5;
// idirichlet=3;
// break;
// }
// case 37: //trois Faces de Dirichlet : Faces 1,0,3
// // le point G est le centre de la face de dirichlet opposee a la face non-dirichlet
// {
// for (j=0; j<dim; j++)
// xg[j]=(x(0,j)+x(2,j))*0.5;
// idirichlet=3;
// break;
// }
// case 39: //trois Faces de Dirichlet : Faces 2,1,0
// // le point G est le centre de la face de dirichlet opposee a la face non-dirichlet
// {
// for (j=0; j<dim; j++)
// xg[j]=(x(0,j)+x(1,j))*0.5;
// idirichlet=3;
// break;
// }
// } // fin du switch
}
Objet_U * Quadri_CoviMAC::cree_instance () [static]
Definition at line 26 of file Quadri_CoviMAC.cpp.
int Quadri_CoviMAC::duplique () const [virtual]
Implements Elem_CoviMAC_base.
Definition at line 26 of file Quadri_CoviMAC.cpp.
const Type_info * Quadri_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_CoviMAC_base.
Definition at line 26 of file Quadri_CoviMAC.cpp.
const Type_info * Quadri_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_CoviMAC_base.
Definition at line 26 of file Quadri_CoviMAC.cpp.
void Quadri_CoviMAC::normale (int num_Face, DoubleTab & Face_normales, const IntTab & Face_sommets, const IntTab & Face_voisins, const IntTab & elem_faces, const Zone & zone_geom) const [virtual]
remplit le tableau face_normales dans la Zone_CoviMAC
Implements Elem_CoviMAC_base.
Definition at line 50 of file Quadri_CoviMAC.cpp.
References Domaine::coord_sommets(), and Zone::domaine().
{
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
  double x1,y1;
  double nx,ny;
  double x1g=0,y1g=0;
  double x2g=0,y2g=0;
  double grx,gry,psc;
  int sign=1,i;
  int n0 = Face_sommets(num_Face,0);
  int n1 = Face_sommets(num_Face,1);
  x1 = les_coords(n0,0)-les_coords(n1,0);
  y1 = les_coords(n0,1)-les_coords(n1,1);
  nx = -y1;
  ny = x1;
  int elem1=Face_voisins(num_Face,0);
  int elem2=Face_voisins(num_Face,1);
// Orientation de la normale vers le plus grand numero d'elem
// pour cela on teste d'abord si l'on est sur le bord
  if (elem2!=-1)
    {
// on oriente a partir du centre de gravite
// calcul du centre de gravite de chaque element
      for(i=0; i<4; i++)
        {
          x1g+=les_coords(Face_sommets(elem_faces(elem1,i),0),0);
          x1g+=les_coords(Face_sommets(elem_faces(elem1,i),1),0);
          y1g+=les_coords(Face_sommets(elem_faces(elem1,i),0),1);
          y1g+=les_coords(Face_sommets(elem_faces(elem1,i),1),1);
          x2g+=les_coords(Face_sommets(elem_faces(elem2,i),0),0);
          x2g+=les_coords(Face_sommets(elem_faces(elem2,i),1),0);
          y2g+=les_coords(Face_sommets(elem_faces(elem2,i),0),1);
          y2g+=les_coords(Face_sommets(elem_faces(elem2,i),1),1);
        }
      grx=(x2g-x1g)*0.125;
      gry=(y2g-y1g)*0.125;
// on regarde le signe du produit scalaire
      psc=grx*nx+gry*ny;
      if(psc<0)
        {
          if(elem1<elem2)
            sign=-1;
        }
      else if(elem2<elem1)
        sign=-1;
    }
  else
    {
// on oriente a partir du centre de gravite et du milieu de la
// face courante
      for(i=0; i<4; i++)
        {
          x1g+=les_coords(Face_sommets(elem_faces(elem1,i),0),0);
          x1g+=les_coords(Face_sommets(elem_faces(elem1,i),1),0);
          y1g+=les_coords(Face_sommets(elem_faces(elem1,i),0),1);
          y1g+=les_coords(Face_sommets(elem_faces(elem1,i),1),1);
        }
// Cerr << "xg et yg de Face_normales: " << x1g << " " << y1g << finl;
      x2g = les_coords(n0,0)+les_coords(n1,0);
      y2g = les_coords(n0,1)+les_coords(n1,1);
      grx=x2g*0.5-x1g*0.125;
      gry=y2g*0.5-y1g*0.125;
// Cerr << "grx et gry : " << grx << " " << gry << finl;
// on regarde le signe du produit scalaire
      psc=grx*nx+gry*ny;
      if(psc<0)
        sign=-1;
    }
  Face_normales(num_Face,0)=sign*nx;
  Face_normales(num_Face,1)=sign*ny;
}
Sortie & Quadri_CoviMAC::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Elem_CoviMAC_base.
Definition at line 30 of file Quadri_CoviMAC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Quadri_CoviMAC::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Elem_CoviMAC_base.
Definition at line 35 of file Quadri_CoviMAC.cpp.
{
  return s ;
}
Quadri_CoviMAC & Quadri_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Elem_CoviMAC_base.
Definition at line 26 of file Quadri_CoviMAC.cpp.
const Quadri_CoviMAC & Quadri_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Elem_CoviMAC_base.
Definition at line 26 of file Quadri_CoviMAC.cpp.
unsigned Quadri_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Quadri_CoviMAC.cpp.
Member Data Documentation
const Type_info Quadri_CoviMAC::info_obj [static]
Reimplemented from Elem_CoviMAC_base.
Definition at line 33 of file Quadri_CoviMAC.h.
The documentation for this class was generated from the following files:
src/CoviMAC/Zones/Quadri_CoviMAC.h
src/CoviMAC/Zones/Quadri_CoviMAC.cpp