TRUST: Eval_Conv_PolyMAC Class Reference
Eval_Conv_PolyMAC Class Reference
class Eval_Conv_PolyMAC
classe de base des evaluateurs de convection PolyMAC
#include <Eval_Conv_PolyMAC.h>
Public Member Functions
Eval_Conv_PolyMAC ()
constructeur par defaut
Eval_Conv_PolyMAC (const Eval_Conv_PolyMAC &)
void associer (const Champ_Face_PolyMAC &)
associe le champ de vitesse transportante
void mettre_a_jour ()
mise a jour du DoubleTab vitesse
const Champ_Inc_base & vitesse () const
Champ_Inc_base & vitesse ()
Protected Attributes
Ref_Champ_Face_PolyMAC vitesse_
DoubleTab dt_vitesse
Detailed Description
class Eval_Conv_PolyMAC
classe de base des evaluateurs de convection PolyMAC
See also:
Evaluateur_PolyMAC
Definition at line 42 of file Eval_Conv_PolyMAC.h.
Constructor & Destructor Documentation
Eval_Conv_PolyMAC::Eval_Conv_PolyMAC () [inline]
constructeur par defaut
Definition at line 66 of file Eval_Conv_PolyMAC.h.
{}
Eval_Conv_PolyMAC::Eval_Conv_PolyMAC (const Eval_Conv_PolyMAC & eval) [inline]
Definition at line 69 of file Eval_Conv_PolyMAC.h.
References dt_vitesse, and DoubleTab::ref().
  :Evaluateur_PolyMAC(eval), vitesse_(eval.vitesse_)
{
  dt_vitesse.ref(eval.dt_vitesse);
}
Member Function Documentation
void Eval_Conv_PolyMAC::associer (const Champ_Face_PolyMAC & vit)
associe le champ de vitesse transportante
Definition at line 38 of file Eval_Conv_PolyMAC.cpp.
References dt_vitesse, DoubleTab::ref(), Champ_Inc_base::valeurs(), and vitesse_.
Referenced by Op_Conv_Centre_PolyMAC_Elem::associer_vitesse(), and Op_Conv_Amont_PolyMAC_Elem::associer_vitesse().
{
  vitesse_=vit;
  dt_vitesse.ref(vit.valeurs());
}
void Eval_Conv_PolyMAC::mettre_a_jour ()
mise a jour du DoubleTab vitesse
Definition at line 46 of file Eval_Conv_PolyMAC.cpp.
References dt_vitesse, DoubleTab::ref(), and vitesse_.
{
  dt_vitesse.ref(vitesse_->valeurs());
}
const Champ_Inc_base & Eval_Conv_PolyMAC::vitesse () const
Definition at line 26 of file Eval_Conv_PolyMAC.cpp.
References Ref_Champ_Face_PolyMAC::valeur(), and vitesse_.
Referenced by Op_Conv_Centre_PolyMAC_Elem::vitesse(), and Op_Conv_Amont_PolyMAC_Elem::vitesse().
{
  return vitesse_.valeur();
}
Champ_Inc_base & Eval_Conv_PolyMAC::vitesse ()
Definition at line 31 of file Eval_Conv_PolyMAC.cpp.
References Ref_Champ_Face_PolyMAC::valeur(), and vitesse_.
{
  return vitesse_.valeur();
}
Member Data Documentation
DoubleTab Eval_Conv_PolyMAC::dt_vitesse [protected]
Definition at line 57 of file Eval_Conv_PolyMAC.h.
Referenced by associer(), Eval_centre_PolyMAC_Elem::coeffs_face(), Eval_Amont_PolyMAC_Elem::coeffs_face(), Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse(), Eval_centre_PolyMAC_Elem::coeffs_faces_interne(), Eval_Amont_PolyMAC_Elem::coeffs_faces_interne(), Eval_Amont_PolyMAC_Elem::coeffs_faces_interne_bloc_vitesse(), Eval_Conv_PolyMAC(), Eval_centre_PolyMAC_Elem::flux_face(), Eval_Amont_PolyMAC_Elem::flux_face(), Eval_centre_PolyMAC_Elem::flux_faces_interne(), Eval_Amont_PolyMAC_Elem::flux_faces_interne(), mettre_a_jour(), Eval_centre_PolyMAC_Elem::secmem_face(), and Eval_Amont_PolyMAC_Elem::secmem_face().
Ref_Champ_Face_PolyMAC Eval_Conv_PolyMAC::vitesse_ [protected]
Definition at line 56 of file Eval_Conv_PolyMAC.h.
Referenced by associer(), mettre_a_jour(), and vitesse().
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Conv_iterateur/Eval_Conv_PolyMAC.h
src/PolyMAC/Operateurs/Conv_iterateur/Eval_Conv_PolyMAC.cpp