TRUST: Perte_Charge_Singuliere_QC_VDF_Face Class Reference
Perte_Charge_Singuliere_QC_VDF_Face Class Reference
#include <Source_QC_VDF_Face.h>
Public Member Functions
Perte_Charge_Singuliere_QC_VDF_Face ()
~Perte_Charge_Singuliere_QC_VDF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & ajouter_mere (DoubleTab &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Perte_Charge_Singuliere_QC_VDF_Face & self_cast (Objet_U &)
static const
Perte_Charge_Singuliere_QC_VDF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Detailed Description
Definition at line 72 of file Source_QC_VDF_Face.h.
Constructor & Destructor Documentation
Perte_Charge_Singuliere_QC_VDF_Face::Perte_Charge_Singuliere_QC_VDF_Face ()
Definition at line 46 of file Source_QC_VDF_Face.cpp.
Perte_Charge_Singuliere_QC_VDF_Face::~Perte_Charge_Singuliere_QC_VDF_Face ()
Definition at line 46 of file Source_QC_VDF_Face.cpp.
Member Function Documentation
DoubleTab & Perte_Charge_Singuliere_QC_VDF_Face::ajouter (DoubleTab & resu) const [virtual]
Reimplemented from Source_dep_inco_base.
Definition at line 50 of file Source_QC_VDF_Face.cpp.
References Source_Fluide_Dilatable_Face< Perte_Charge_Singuliere_QC_VDF_Face >::ajouter_impl().
Referenced by ajouter_mere().
{ return ajouter_impl(resu); }
DoubleTab & Perte_Charge_Singuliere_QC_VDF_Face::ajouter_mere (DoubleTab & resu) const
Definition at line 49 of file Source_QC_VDF_Face.cpp.
References ajouter().
{ return Perte_Charge_Singuliere_VDF_Face::ajouter(resu); }
void Perte_Charge_Singuliere_QC_VDF_Face::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const [virtual]
contribution a la matrice implicite des termes sources
par defaut pas de contribution
Reimplemented from Perte_Charge_Singuliere_VDF_Face.
Definition at line 51 of file Source_QC_VDF_Face.cpp.
References Source_Fluide_Dilatable_Face< Perte_Charge_Singuliere_QC_VDF_Face >::contribuer_a_avec_impl().
{ contribuer_a_avec_impl(resu,mat); }
Objet_U * Perte_Charge_Singuliere_QC_VDF_Face::cree_instance () [static]
Reimplemented from Perte_Charge_Singuliere_VDF_Face.
Definition at line 46 of file Source_QC_VDF_Face.cpp.
int Perte_Charge_Singuliere_QC_VDF_Face::duplique () const [virtual]
Reimplemented from Perte_Charge_Singuliere_VDF_Face.
Definition at line 46 of file Source_QC_VDF_Face.cpp.
const Type_info * Perte_Charge_Singuliere_QC_VDF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_Singuliere_VDF_Face.
Definition at line 46 of file Source_QC_VDF_Face.cpp.
const Type_info * Perte_Charge_Singuliere_QC_VDF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_Singuliere_VDF_Face.
Definition at line 46 of file Source_QC_VDF_Face.cpp.
Sortie & Perte_Charge_Singuliere_QC_VDF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Perte_Charge_Singuliere_VDF_Face.
Definition at line 47 of file Source_QC_VDF_Face.cpp.
{ return Perte_Charge_Singuliere_VDF_Face::printOn(os); }
Entree & Perte_Charge_Singuliere_QC_VDF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Perte_Charge_Singuliere_VDF_Face.
Definition at line 48 of file Source_QC_VDF_Face.cpp.
{ return Perte_Charge_Singuliere_VDF_Face::readOn(is); }
const Perte_Charge_Singuliere_QC_VDF_Face & Perte_Charge_Singuliere_QC_VDF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Perte_Charge_Singuliere_VDF_Face.
Definition at line 46 of file Source_QC_VDF_Face.cpp.
Perte_Charge_Singuliere_QC_VDF_Face & Perte_Charge_Singuliere_QC_VDF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Perte_Charge_Singuliere_VDF_Face.
Definition at line 46 of file Source_QC_VDF_Face.cpp.
unsigned Perte_Charge_Singuliere_QC_VDF_Face::taille_memoire () const [virtual]
Reimplemented from Perte_Charge_Singuliere_VDF_Face.
Definition at line 46 of file Source_QC_VDF_Face.cpp.
Member Data Documentation
const Type_info Perte_Charge_Singuliere_QC_VDF_Face::info_obj [static]
Reimplemented from Perte_Charge_Singuliere_VDF_Face.
Definition at line 74 of file Source_QC_VDF_Face.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VDF/Source_QC_VDF_Face.h
src/ThHyd/Dilatable/Quasi_Compressible/VDF/Source_QC_VDF_Face.cpp