TRUST: Transformer Class Reference
Transformer Class Reference
Classe Transformer
Applique un changement de coordonnees
Structure du jeu de donnee (en dimension 2) :
Transformer dom expr1 expr2.
#include <Transformer.h>
Public Member Functions
Transformer ()
~Transformer ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
void transformer (Domaine &, Noms &)
void transformation_complete (Noms &les_fcts)
void verifie_type_elem ()
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Transformer & self_cast (Objet_U &)
static const Transformer & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Classe Transformer
Applique un changement de coordonnees
Structure du jeu de donnee (en dimension 2) :
Transformer dom expr1 expr2.
Definition at line 32 of file Transformer.h.
Constructor & Destructor Documentation
Transformer()
Transformer::Transformer ()
Definition at line 22 of file Transformer.cpp.
~Transformer()
Transformer::~Transformer ()
Definition at line 22 of file Transformer.cpp.
Member Function Documentation
cree_instance()
Objet_U * Transformer::cree_instance () static
Definition at line 22 of file Transformer.cpp.
duplique()
int Transformer::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file Transformer.cpp.
get_info()
const Type_info * Transformer::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 22 of file Transformer.cpp.
info()
const Type_info * Transformer::info () static
Definition at line 22 of file Transformer.cpp.
interpreter_()
Entree & Transformer::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base.
Definition at line 64 of file Transformer.cpp.
{
  associer_domaine(is);
  verifie_type_elem();
  Noms les_fcts;
  les_fcts.dimensionner(dimension);
  for (int i=0; i<dimension; i++)
    {
      is >> les_fcts[i];
    }
  transformation_complete(les_fcts);
  return is;
}
References Interprete_geometrique_base::associer_domaine(), Objet_U::dimension, vect_impl::dimensionner(), transformation_complete(), and verifie_type_elem().
printOn()
Sortie & Transformer::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 39 of file Transformer.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
Referenced by Rotation::printOn().
readOn()
Entree & Transformer::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 59 of file Transformer.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
Referenced by Rotation::readOn().
self_cast() [1/2]
const Transformer & Transformer::self_cast (const Objet_U & r) static
Definition at line 22 of file Transformer.cpp.
self_cast() [2/2]
Transformer & Transformer::self_cast (Objet_U & r) static
Definition at line 22 of file Transformer.cpp.
taille_memoire()
unsigned Transformer::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file Transformer.cpp.
transformation_complete()
void Transformer::transformation_complete (Noms & les_fcts)
< Le reordonner_elem revele que l'on n'a plus des Rectangle
< Le reordonner_elem revele que l'on n'a plus des Hexaedre
Definition at line 143 of file Transformer.cpp.
{
  Scatter::uninit_sequential_domain(domaine());
  transformer(domaine(), les_fcts);
// Transformation de l'element parfois necessaire
  Elem_geom& type_elem=domaine().zone(0).type_elem();
  if (type_elem->que_suis_je() == "Rectangle")
    {
      if (ref_cast(Rectangle,type_elem.valeur()).reordonner_elem()==-1) //!< Le reordonner_elem revele que l'on n'a plus des Rectangle
        {
          type_elem.typer("Quadrangle");
          type_elem.associer_zone(domaine().zone(0));
        }
    }
  if (type_elem->que_suis_je() == "Hexaedre")
    {
      if (ref_cast(Hexaedre,type_elem.valeur()).reordonner_elem()==-1) //!< Le reordonner_elem revele que l'on n'a plus des Hexaedre
        {
          type_elem.typer("Hexaedre_VEF");
          type_elem.associer_zone(domaine().zone(0));
          Bords& les_bords=domaine().zone(0).faces_bord();
          LIST_CURSEUR(Bord) curseur=les_bords;
          while (curseur)
            {
              curseur->faces().typer(Faces::quadrangle_3D);
              ++curseur;
            }
          les_bords.associer_zone(domaine().zone(0));
        }
    }
// Il faut reordonner apres un Transformer -y x par exemple car
// la numerotation des elements est melangee... Le probleme c'est
// que tous les reordonner ne sont pas correctement faits...
// 2-3
// 0-1
  domaine().reordonner();
  Scatter::init_sequential_domain(domaine());
}
References Bords::associer_zone(), Interprete_geometrique_base::domaine(), Zone::faces_bord(), Scatter::init_sequential_domain(), LIST_CURSEUR, Faces::quadrangle_3D, ref_cast, Domaine::reordonner(), transformer(), Zone::type_elem(), type_elem(), Scatter::uninit_sequential_domain(), and Domaine::zone().
Referenced by Rotation::interpreter_(), and interpreter_().
transformer()
void Transformer::transformer (Domaine & dom, Noms & les_fcts)
Definition at line 83 of file Transformer.cpp.
{
  VECT(Parser_U) fxyz(dimension);
  for (int i = 0; i<dimension; i++)
    {
      Cerr << "Reading and interpretation of the function " << les_fcts[i] << finl;
      fxyz[i].setNbVar(3);
      fxyz[i].setString(les_fcts[i]);
      fxyz[i].addVar("x");
      fxyz[i].addVar("y");
      fxyz[i].addVar("z");
      fxyz[i].parseString();
      Cerr << "Interpretation of the function " << les_fcts[i] << " Ok" << finl;
    }
  DoubleTab& sommets=dom.les_sommets();
  DoubleTab new_sommets(sommets);
  int sz=sommets.dimension(0);
  double x=0;
  double y=0;
  double z=0;
  for (int i = 0; i<sz; i++)
    {
      for (int j = 0; j<dimension; j++)
        {
          x=sommets(i,0);
          y=sommets(i,1);
          z=0;
          if (dimension >2 )
            z = sommets(i,2);
        }
      for(int  j=0; j<dimension; j++)
        {
          fxyz[j].setVar("x",x);
          fxyz[j].setVar("y",y);
          fxyz[j].setVar("z",z);
          new_sommets(i,j)=fxyz[j].eval();
        }
    }
  sommets=new_sommets;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, finl, Domaine::les_sommets(), and VECT.
Referenced by ExtrudeBord::extruder_bord(), and transformation_complete().
verifie_type_elem()
void Transformer::verifie_type_elem ()
Definition at line 126 of file Transformer.cpp.
{
  Elem_geom& type_elem=domaine().zone(0).type_elem();
  if (type_elem->que_suis_je() == "Hexaedre_VEF")
    {
      Cerr << "------------------------------------------------------------------" << finl;
      Cerr << "It is advised to not use directly \"Transformer\" on a mesh" << finl;
      Cerr << "with VEF hexahedra since the method Hexaedre_VEF::reordonner" << finl;
      Cerr << "is not fairly general in TRUST." << finl;
      Cerr << "If your purpose is to make tetrahedra on your mesh," << finl;
      Cerr << "create it first after reading your hexahedral meshing," << finl;
      Cerr << "then use \"Transformer\"." << finl;
      Cerr << "------------------------------------------------------------------" << finl;
      exit();
    }
}
References Cerr, Interprete_geometrique_base::domaine(), Process::exit(), finl, Zone::type_elem(), type_elem(), and Domaine::zone().
Referenced by Rotation::interpreter_(), and interpreter_().
Member Data Documentation
info_obj
const Type_info Transformer::info_obj static
Definition at line 34 of file Transformer.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Transformer.h
src/Kernel/Geometrie/Transformer.cpp