TRUST: Terme_Source_Th_TdivU_VEF_Face Class Reference
Terme_Source_Th_TdivU_VEF_Face Class Reference
class Terme_Source_Th_TdivU_VEF_Face
#include <Terme_Source_Th_TdivU_VEF_Face.h>
Public Member Functions
Terme_Source_Th_TdivU_VEF_Face ()
~Terme_Source_Th_TdivU_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &) override
DoubleTab & ajouter (DoubleTab &) const override
DoubleTab & calculer (DoubleTab &) const override
void mettre_a_jour (double) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void completer () override
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
void associer_eqn_t ()
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don & source () const
Renvoie le champ donne representant le terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Terme_Source_Th_TdivU_VEF_Face & self_cast (Objet_U &)
static const Terme_Source_Th_TdivU_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void modifier_zone_cl ()
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Equation_base eqn_t
Zone_Cl_dis ma_zonecl_
Ref_Zone_Cl_dis_base zonecl_sa
int zone_cl_mod_
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Protected Attributes inherited from Terme_Source_Qdm
Champ_Don la_source
Detailed Description
class Terme_Source_Th_TdivU_VEF_Face
See also
Source_base
Definition at line 34 of file Terme_Source_Th_TdivU_VEF_Face.h.
Constructor & Destructor Documentation
Terme_Source_Th_TdivU_VEF_Face()
Terme_Source_Th_TdivU_VEF_Face::Terme_Source_Th_TdivU_VEF_Face ()
Definition at line 31 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
~Terme_Source_Th_TdivU_VEF_Face()
Terme_Source_Th_TdivU_VEF_Face::~Terme_Source_Th_TdivU_VEF_Face ()
Definition at line 31 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
Member Function Documentation
ajouter()
DoubleTab & Terme_Source_Th_TdivU_VEF_Face::ajouter (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 156 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
{
  Terme_Source_Th_TdivU_VEF_Face& me_non_const=ref_cast_non_const(Terme_Source_Th_TdivU_VEF_Face,*this);
  me_non_const.modifier_zone_cl();
  if(resu.line_size() > 1)
    {
      Cerr << "Error in " << que_suis_je()  << finl;
      Cerr << "The source term Source_Th_TdivU_VEF_P1NC is only dedicated to thermal equation" << finl;
      exit();
    }
  const DoubleTab& temperature=equation().inconnue().valeurs();
  const int nb_faces = temperature.dimension_tot(0);
// Calcul de TdivU d'apres le schema de convection
  DoubleTab temp(temperature);
  DoubleTab TdivU(resu);
  TdivU=0.;
  temp=1.;
  const Operateur& Op_conv=equation().operateur(1);
  Operateur_base& optype=ref_cast_non_const(Operateur_base,Op_conv.l_op_base());
// We save the boundary fluxes:
  DoubleTab flux_bords_backup = optype.flux_bords();
  optype.associer_zone_cl_dis(ma_zonecl_);
  Op_conv.ajouter(temp,TdivU);
  for(int face=0; face<nb_faces; face++)
    {
      TdivU[face]*=temperature(face);
    }
  if (mp_max_vect(TdivU)==0)
    {
      Cerr << finl;
      Cerr << "******* Warning *******" << finl;
      Cerr << "You are using source term TdivU into one transport equation." << finl;
      Cerr << "It seems useless cause TdivU=0" << finl;
      Cerr << "May be the advection operator is calculated with the non-conservative formulation." << finl;
    }
// la partie en TdivU est un bout de l'operateur de convection -> il doit etre multiplie par rhoCp
  const double rhoCp = equation().milieu().capacite_calorifique().valeurs()(0, 0) * equation().milieu().masse_volumique().valeurs()(0, 0);
  TdivU *= rhoCp;
  resu-=TdivU;
// on remet la bonne zone_cl_dis
  optype.associer_zone_cl_dis(zonecl_sa.valeur());
// We reset flux_bords
  optype.flux_bords() = flux_bords_backup;
  return resu;
}
References Operateur::ajouter(), Operateur_base::associer_zone_cl_dis(), Milieu_base::capacite_calorifique(), Cerr, TRUSTTab< _TYPE_ >::dimension_tot(), MorEqn::equation(), Process::exit(), finl, Operateur_base::flux_bords(), Equation_base::inconnue(), Operateur::l_op_base(), TRUSTVect< _TYPE_ >::line_size(), ma_zonecl_, Milieu_base::masse_volumique(), Equation_base::milieu(), modifier_zone_cl(), mp_max_vect(), Equation_base::operateur(), Objet_U::que_suis_je(), ref_cast_non_const, Ref_Zone_Cl_dis_base::valeur(), Champ::valeurs(), Champ_Don::valeurs(), Champ_Inc::valeurs(), and zonecl_sa.
Referenced by calculer().
associer_eqn_t()
void Terme_Source_Th_TdivU_VEF_Face::associer_eqn_t ()
Definition at line 83 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
{
  eqn_t = equation();
}
References eqn_t, and MorEqn::equation().
Referenced by completer().
associer_pb()
void Terme_Source_Th_TdivU_VEF_Face::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Definition at line 52 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
{
  int nb_eqn = pb.nombre_d_equations();
  int ok_vit=0;
  int ok_temp=0;
  for (int i=0; i<nb_eqn; i++)
    {
      const Equation_base& eqn = pb.equation(i);
      if  (sub_type(Navier_Stokes_std,eqn))
        {
          ok_vit = 1;
        }
      if  (sub_type(Convection_Diffusion_std,eqn))
        {
          ok_temp = 1;
        }
    }
  if (!ok_vit)
    {
      Cerr << "Error TRUST in " << que_suis_je()  << finl;
      Cerr << "Hydraulic equation not found" << finl;
      exit();
    }
  if (!ok_temp)
    {
      Cerr << "Error TRUST in " << que_suis_je()  << finl;
      Cerr << "Thermal equation not found" << finl;
      exit();
    }
}
References Cerr, Probleme_base::equation(), Process::exit(), finl, Probleme_base::nombre_d_equations(), Objet_U::que_suis_je(), and sub_type.
associer_zones()
void Terme_Source_Th_TdivU_VEF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
Implements Source_base.
Definition at line 88 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
{
}
calculer()
DoubleTab & Terme_Source_Th_TdivU_VEF_Face::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 204 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
{
  resu = 0.;
  return ajouter(resu);
}
References ajouter().
completer()
void Terme_Source_Th_TdivU_VEF_Face::completer (void) override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
Definition at line 93 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
{
  Source_base::completer();
  associer_eqn_t();
  zone_cl_mod_=0;
}
References associer_eqn_t(), Source_base::completer(), and zone_cl_mod_.
cree_instance()
Objet_U * Terme_Source_Th_TdivU_VEF_Face::cree_instance () static
Definition at line 31 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
duplique()
int Terme_Source_Th_TdivU_VEF_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 31 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
get_info()
const Type_info * Terme_Source_Th_TdivU_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 31 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
info()
const Type_info * Terme_Source_Th_TdivU_VEF_Face::info () static
Definition at line 31 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
mettre_a_jour()
void Terme_Source_Th_TdivU_VEF_Face::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 210 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
{
  ;
}
modifier_zone_cl()
void Terme_Source_Th_TdivU_VEF_Face::modifier_zone_cl () protected
Definition at line 100 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
{
  if (zone_cl_mod_) return;
  zone_cl_mod_=1;
  Zone_Cl_dis& ma_zonecl=ref_cast(Zone_Cl_dis,ma_zonecl_);
  ma_zonecl=eqn_t.valeur().zone_Cl_dis();
  zonecl_sa=eqn_t.valeur().zone_Cl_dis().valeur();
  Conds_lim& condlims=ma_zonecl.les_conditions_limites();
  Conds_lim& condlims_sa=zonecl_sa.valeur().les_conditions_limites();
  int nb=condlims.size();
  for (int i=0; i<nb*0; i++)
    {
      condlims[i]= condlims_sa[i];
// Cerr<<(int)(&condlims[i].valeur())<<" addr "<<(int) &condlims_sa[i].valeur()<<finl;
    }
  for (int i=0; i<nb; i++)
    {
      Cond_lim_base& la_cl=condlims_sa[i].valeur();
      int modif=0;
      Nom new_cl;
      if (sub_type(Periodique,la_cl)||sub_type(Symetrie,la_cl))
        {
          ;
        }
      else if (sub_type(Neumann_homogene,la_cl)||sub_type(Neumann,la_cl)||sub_type(Neumann_val_ext,la_cl)||sub_type(Echange_impose_base,la_cl))
        {
          modif=1;
          new_cl="Frontiere_ouverte T_ext Champ_front_uniforme 1 1";
        }
      else if  (sub_type(Dirichlet_homogene,la_cl)||sub_type(Dirichlet,la_cl))
        {
          modif=1;
          new_cl="Frontiere_ouverte_temperature_imposee Champ_front_uniforme 1 1";
        }
      else
        {
          Cerr<<"surcharge de la cl "<<la_cl.que_suis_je()<<"pas codee dans "<<__FILE__<<finl;
          exit();
        }
      if (modif)
        {
          EChaine cons("Frontiere_ouverte T_ext Champ_front_uniforme 1 1");
// EChaine cons("symetrie");
          Frontiere_dis_base& frdis=condlims[i].valeur().frontiere_dis();
          cons>>condlims[i];
          Cond_lim_base& cl_m=condlims[i].valeur();
          cl_m.associer_fr_dis_base(frdis);
          cl_m.completer();
        }
    }
}
References Cond_lim_base::associer_fr_dis_base(), Cerr, Cond_lim_base::completer(), eqn_t, Process::exit(), finl, Zone_Cl_dis::les_conditions_limites(), Zone_Cl_dis_base::les_conditions_limites(), ma_zonecl_, Objet_U::que_suis_je(), ref_cast, vect_impl::size(), sub_type, Ref_Equation_base::valeur(), Ref_Zone_Cl_dis_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Equation_base::zone_Cl_dis(), zone_cl_mod_, and zonecl_sa.
Referenced by ajouter().
printOn()
Sortie & Terme_Source_Th_TdivU_VEF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 38 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_Th_TdivU_VEF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 47 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
{
  return s ;
}
self_cast() [1/2]
const Terme_Source_Th_TdivU_VEF_Face & Terme_Source_Th_TdivU_VEF_Face::self_cast (const Objet_U & r) static
Definition at line 31 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
self_cast() [2/2]
Terme_Source_Th_TdivU_VEF_Face & Terme_Source_Th_TdivU_VEF_Face::self_cast (Objet_U & r) static
Definition at line 31 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
taille_memoire()
unsigned Terme_Source_Th_TdivU_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 31 of file Terme_Source_Th_TdivU_VEF_Face.cpp.
Member Data Documentation
eqn_t
Ref_Equation_base Terme_Source_Th_TdivU_VEF_Face::eqn_t protected
Definition at line 52 of file Terme_Source_Th_TdivU_VEF_Face.h.
Referenced by associer_eqn_t(), and modifier_zone_cl().
info_obj
const Type_info Terme_Source_Th_TdivU_VEF_Face::info_obj static
Definition at line 37 of file Terme_Source_Th_TdivU_VEF_Face.h.
ma_zonecl_
Zone_Cl_dis Terme_Source_Th_TdivU_VEF_Face::ma_zonecl_ protected
Definition at line 53 of file Terme_Source_Th_TdivU_VEF_Face.h.
Referenced by ajouter(), and modifier_zone_cl().
zone_cl_mod_
int Terme_Source_Th_TdivU_VEF_Face::zone_cl_mod_ protected
Definition at line 55 of file Terme_Source_Th_TdivU_VEF_Face.h.
Referenced by completer(), and modifier_zone_cl().
zonecl_sa
Ref_Zone_Cl_dis_base Terme_Source_Th_TdivU_VEF_Face::zonecl_sa protected
Definition at line 54 of file Terme_Source_Th_TdivU_VEF_Face.h.
Referenced by ajouter(), and modifier_zone_cl().
The documentation for this class was generated from the following files:
src/VEF/Sources/Terme_Source_Th_TdivU_VEF_Face.h
src/VEF/Sources/Terme_Source_Th_TdivU_VEF_Face.cpp