TRUST: Ref_Domaine Class Reference
Ref_Domaine Class Reference
#include <Ref_Domaine.h>
Public Member Functions
~Ref_Domaine ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Domaine ()
Ref_Domaine (const Domaine &)
Ref_Domaine (const Ref_Domaine &)
const Domaine & valeur () const
Domaine & valeur ()
const Domaine * operator-> () const
Domaine * operator-> ()
const Ref_Domaine & operator= (const Domaine &)
const Ref_Domaine & operator= (const Ref_Domaine &)
operator const Domaine & () const
operator Domaine & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Domaine & self_cast (Objet_U &)
static const Ref_Domaine & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Domaine * pointeur_
Detailed Description
Definition at line 32 of file Ref_Domaine.h.
Constructor & Destructor Documentation
Ref_Domaine::~Ref_Domaine ()
Definition at line 25 of file Ref_Domaine.cpp.
Ref_Domaine::Ref_Domaine ()
Definition at line 25 of file Ref_Domaine.cpp.
Ref_Domaine::Ref_Domaine (const Domaine & t)
Definition at line 25 of file Ref_Domaine.cpp.
Ref_Domaine::Ref_Domaine (const Ref_Domaine & t)
Definition at line 25 of file Ref_Domaine.cpp.
Member Function Documentation
Objet_U * Ref_Domaine::cree_instance () [static]
Definition at line 25 of file Ref_Domaine.cpp.
int Ref_Domaine::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Domaine.cpp.
const Type_info * Ref_Domaine::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Domaine.cpp.
const Type_info & Ref_Domaine::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Domaine.cpp.
const Type_info * Ref_Domaine::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Domaine.cpp.
Ref_Domaine::operator const Domaine & () const
Definition at line 25 of file Ref_Domaine.cpp.
Ref_Domaine::operator Domaine & ()
Definition at line 25 of file Ref_Domaine.cpp.
const Domaine * Ref_Domaine::operator-> () const [inline]
Definition at line 32 of file Ref_Domaine.h.
Domaine * Ref_Domaine::operator-> () [inline]
Definition at line 32 of file Ref_Domaine.h.
const Ref_Domaine & Ref_Domaine::operator= (const Ref_Domaine & t)
Definition at line 25 of file Ref_Domaine.cpp.
const Ref_Domaine & Ref_Domaine::operator= (const Domaine & t)
Definition at line 25 of file Ref_Domaine.cpp.
Sortie & Ref_Domaine::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Domaine.cpp.
Entree & Ref_Domaine::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Domaine.cpp.
const Ref_Domaine & Ref_Domaine::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Domaine.cpp.
Ref_Domaine & Ref_Domaine::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Domaine.cpp.
void Ref_Domaine::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Domaine.cpp.
unsigned Ref_Domaine::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Domaine.cpp.
const Domaine & Ref_Domaine::valeur () const [inline]
Definition at line 32 of file Ref_Domaine.h.
Referenced by Champ_Generique_Extraction::completer(), DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_faces_bords_ssdom(), DomaineCutter::construire_faces_internes_ssdom(), DomaineCutter::construire_faces_joints_ssdom(), DomaineCutter::construire_faces_raccords_ssdom(), Partitionneur_Tranche::construire_partition(), Partitionneur_Sous_Zones::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Metis::construire_partition(), Partitionneur_Fichier_Decoupage::construire_partition(), DomaineCutter::construire_sous_domaine(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_stat(), Domaine_dis::discretiser(), Champ_Generique_Interpolation::discretiser_domaine(), Champ_Generique_Extraction::discretiser_domaine(), Zone::domaine(), Scatter::domaine(), Domaine_dis::domaine(), Decouper::ecrire(), DomaineCutter::ecrire_zones(), Champ_Generique_Interpolation::get_ref_domain(), Champ_Generique_Extraction::get_ref_domain(), Postraitement::init(), Champ_front_lu::initialiser(), Ch_front_Vortex::initialiser(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), Champ_Fonc_Morceaux::mettre_a_jour(), Champ_Fonc_Fonction_txyz_Morceaux::mettre_a_jour(), Champ_Don_Fonc_txyz::mettre_a_jour(), Postraitement::postraiter_champs(), Postraitement::postraiter_tableaux(), Champ_Uniforme_Morceaux_Tabule_Temps::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Tabule_Morceaux::readOn(), Champ_Fonc_Morceaux::readOn(), Champ_Fonc_Fonction_txyz_Morceaux::readOn(), Champ_Don_lu::readOn(), Champ_Don_Fonc_xyz::readOn(), and Champ_Don_Fonc_txyz::readOn().
Domaine & Ref_Domaine::valeur () [inline]
Definition at line 32 of file Ref_Domaine.h.
Member Data Documentation
const Type_info Ref_Domaine::info_obj [static]
Reimplemented from Ref_.
Definition at line 32 of file Ref_Domaine.h.
Domaine* Ref_Domaine::pointeur_ [private]
Definition at line 32 of file Ref_Domaine.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Ref_Domaine.h
src/Kernel/Geometrie/Ref_Domaine.cpp