TRUST: Op_Div_VDF_Elem Class Reference
Op_Div_VDF_Elem Class Reference
class Op_Div_VDF_Elem
Cette classe represente l'operateur de divergence
La discretisation est VDF
On calcule la divergence d'un champ de type Champ_Face
L'iterateur associe est de type Iterateur_VDF_Elem
L'evaluateur associe est de type Eval_Div_VDF_Elem
#include <Op_Div_VDF_Elem.h>
Public Member Functions
~Op_Div_VDF_Elem ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Op_Div_VDF_Elem ()
constructeur
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
void volumique (DoubleTab &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Div_VDF_Elem & self_cast (Objet_U &)
static const Op_Div_VDF_Elem & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
Protected Attributes
Ref_Zone_VDF la_zone_vdf
Ref_Zone_Cl_VDF la_zcl_vdf
Detailed Description
class Op_Div_VDF_Elem
Cette classe represente l'operateur de divergence
La discretisation est VDF
On calcule la divergence d'un champ de type Champ_Face
L'iterateur associe est de type Iterateur_VDF_Elem
L'evaluateur associe est de type Eval_Div_VDF_Elem
Definition at line 53 of file Op_Div_VDF_Elem.h.
Constructor & Destructor Documentation
Op_Div_VDF_Elem::~Op_Div_VDF_Elem ()
Definition at line 25 of file Op_Div_VDF_Elem.cpp.
Op_Div_VDF_Elem::Op_Div_VDF_Elem ()
constructeur
Definition at line 82 of file Op_Div_VDF_Elem.cpp.
                                 :
  Op_Div_VDF_base(It_VDF_Elem(Eval_Div_VDF_Elem)())
{
}
Member Function Documentation
void Op_Div_VDF_Elem::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis, const Champ_Inc &) [virtual]
< Evaluateur_VDF::associer_zones
Implements Operateur_base.
Definition at line 46 of file Op_Div_VDF_Elem.cpp.
References Iterateur_VDF::associer(), Evaluateur_VDF::associer_zones(), Iterateur_VDF::evaluateur(), Op_Div_VDF_base::iter, la_zcl_vdf, la_zone_vdf, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  const Zone_VDF& zvdf = ref_cast(Zone_VDF,zone_dis.valeur());
  const Zone_Cl_VDF& zclvdf = ref_cast(Zone_Cl_VDF,zone_Cl_dis.valeur());
// On n'associe pas div a la vitesse car non P0
// On n'associe pas div a la pression car div(P) n'a pas de sens.
  iter.associer(zvdf, zclvdf, *this);
  Eval_Div_VDF_Elem& eval_div = (Eval_Div_VDF_Elem&) iter.evaluateur();
  eval_div.associer_zones(zvdf, zclvdf );          //!< Evaluateur_VDF::associer_zones
  la_zone_vdf = zvdf;
  la_zcl_vdf = zclvdf;
}
Objet_U * Op_Div_VDF_Elem::cree_instance () [static]
Definition at line 25 of file Op_Div_VDF_Elem.cpp.
int Op_Div_VDF_Elem::duplique () const [virtual]
Implements Op_Div_VDF_base.
Definition at line 25 of file Op_Div_VDF_Elem.cpp.
const Type_info * Op_Div_VDF_Elem::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Div_VDF_base.
Definition at line 25 of file Op_Div_VDF_Elem.cpp.
const Type_info * Op_Div_VDF_Elem::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Div_VDF_base.
Definition at line 25 of file Op_Div_VDF_Elem.cpp.
Sortie & Op_Div_VDF_Elem::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Div_VDF_base.
Definition at line 32 of file Op_Div_VDF_Elem.cpp.
{
  return s << que_suis_je() ;
}
Entree & Op_Div_VDF_Elem::readOn (Entree & is) [protected, virtual]
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Div_VDF_base.
Definition at line 40 of file Op_Div_VDF_Elem.cpp.
{
  return s ;
}
const Op_Div_VDF_Elem & Op_Div_VDF_Elem::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Div_VDF_base.
Definition at line 25 of file Op_Div_VDF_Elem.cpp.
Op_Div_VDF_Elem & Op_Div_VDF_Elem::self_cast (Objet_U & r) [static]
Reimplemented from Op_Div_VDF_base.
Definition at line 25 of file Op_Div_VDF_Elem.cpp.
unsigned Op_Div_VDF_Elem::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Op_Div_VDF_Elem.cpp.
void Op_Div_VDF_Elem::volumique (DoubleTab & div) const [virtual]
Implements Operateur_Div_base.
Definition at line 65 of file Op_Div_VDF_Elem.cpp.
References la_zone_vdf, Zone::nb_elem_tot(), Ref_Zone_VDF::valeur(), Zone_VF::volumes(), and Zone_dis_base::zone().
{
// PQ : 04/03
  const Zone_VDF& zone_VDF = la_zone_vdf.valeur();
  const DoubleVect& vol = zone_VDF.volumes();
  int nb_elem=zone_VDF.zone().nb_elem_tot();
  int num_elem;
  for(num_elem=0; num_elem<nb_elem; num_elem++)
    div(num_elem)/=vol(num_elem);
}
Member Data Documentation
const Type_info Op_Div_VDF_Elem::info_obj [static]
Reimplemented from Op_Div_VDF_base.
Definition at line 56 of file Op_Div_VDF_Elem.h.
Ref_Zone_Cl_VDF Op_Div_VDF_Elem::la_zcl_vdf [protected]
Definition at line 68 of file Op_Div_VDF_Elem.h.
Referenced by associer().
Ref_Zone_VDF Op_Div_VDF_Elem::la_zone_vdf [protected]
Definition at line 67 of file Op_Div_VDF_Elem.h.
Referenced by associer(), and volumique().
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Op_Div_VDF_Elem.h
src/VDF/Operateurs/Op_Div_VDF_Elem.cpp