TRUST: Option_VDF Class Reference
Option_VDF Class Reference
#include <Option_VDF.h>
Public Member Functions
Option_VDF ()
~Option_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &) override
Fonction principale de l'interprete Option_VDF
Lit la dimension d'espace du probleme.
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
int test_mot (const Motcle &mot) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Option_VDF & self_cast (Objet_U &)
static const Option_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
static int traitement_coins =0
static double coeff_P_neumann =1.
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Definition at line 23 of file Option_VDF.h.
Constructor & Destructor Documentation
Option_VDF()
Option_VDF::Option_VDF ()
Definition at line 20 of file Option_VDF.cpp.
~Option_VDF()
Option_VDF::~Option_VDF ()
Definition at line 20 of file Option_VDF.cpp.
Member Function Documentation
cree_instance()
Objet_U * Option_VDF::cree_instance () static
Definition at line 20 of file Option_VDF.cpp.
duplique()
int Option_VDF::duplique () const override virtual
Reimplemented from Interprete.
Definition at line 20 of file Option_VDF.cpp.
get_info()
const Type_info * Option_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 20 of file Option_VDF.cpp.
info()
const Type_info * Option_VDF::info () static
Definition at line 20 of file Option_VDF.cpp.
interpreter()
Entree & Option_VDF::interpreter (Entree & is) override virtual
Fonction principale de l'interprete Option_VDF
Lit la dimension d'espace du probleme.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
< XD_ADD_P chaine(into=["oui","non"]) Treatment of corners (yes or no). This option modifies slightly the calculations at the outlet of the plane channel. It supposes that the boundary continues after channel outlet (i.e. velocity vector remains parallel to the boundary).
< XD_ADD_P chaine(into=["oui","non"]) Pressure imposed at the faces (yes or no).
Reimplemented from Interprete.
Definition at line 101 of file Option_VDF.cpp.
{
  Param param(que_suis_je());
  param.ajouter_non_std("traitement_coins",(this)); //!< XD_ADD_P chaine(into=["oui","non"]) Treatment of corners (yes or no). This option modifies slightly the calculations at the outlet of the plane channel. It supposes that the boundary continues after channel outlet (i.e. velocity vector remains parallel to the boundary).
  param.ajouter_non_std("P_imposee_aux_faces",(this)); //!< XD_ADD_P chaine(into=["oui","non"]) Pressure imposed at the faces (yes or no).
  param.lire_avec_accolades_depuis(is);
  return is;
}
References Param::ajouter_non_std(), Param::lire_avec_accolades_depuis(), and Objet_U::que_suis_je().
lire_motcle_non_standard()
int Option_VDF::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Objet_U.
Definition at line 110 of file Option_VDF.cpp.
{
  Motcle motlu;
  if (mot=="traitement_coins")
    {
      is >>motlu;
      if (test_mot(motlu))
        {
          Cerr<< motlu <<" will affect the action of the method Zone_Cl_VDF::completer"<<finl;
          Option_VDF::traitement_coins=1;
        }
      else
        Option_VDF::traitement_coins=0;
      return 1;
    }
  else if (mot=="P_imposee_aux_faces")
    {
      is >>motlu;
      if (test_mot(motlu))
        {
          Cerr<<motlu<<" will affect the action of the operator gradient for Neumann_sortie_libre boundary condition" <<finl;
          Cerr<<motlu<<" and therefore the assembleur action will also be affected."<<finl;
          Option_VDF::coeff_P_neumann=2.;
        }
      else
        Option_VDF::coeff_P_neumann=1.;
      return 1;
    }
  else
    {
      Cerr << mot << "is not a keyword understood by " << que_suis_je() << "in methode lire_motcle_non_standard"<< finl;
      exit();
    }
  return -1;
}
References Cerr, coeff_P_neumann, Process::exit(), finl, Objet_U::que_suis_je(), test_mot(), and traitement_coins.
printOn()
Sortie & Option_VDF::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 41 of file Option_VDF.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Option_VDF::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 61 of file Option_VDF.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Option_VDF & Option_VDF::self_cast (const Objet_U & r) static
Definition at line 20 of file Option_VDF.cpp.
self_cast() [2/2]
Option_VDF & Option_VDF::self_cast (Objet_U & r) static
Definition at line 20 of file Option_VDF.cpp.
taille_memoire()
unsigned Option_VDF::taille_memoire () const override virtual
Reimplemented from Interprete.
Definition at line 20 of file Option_VDF.cpp.
test_mot()
int Option_VDF::test_mot (const Motcle & mot) const
Definition at line 67 of file Option_VDF.cpp.
{
  Motcles les_mots(2);
  {
    les_mots[1] = "oui";
    les_mots[0] = "non";
  }
  int rang=les_mots.search(motlu);
  if (rang==-1)
    {
      Cerr<<"Method "<<que_suis_je()<<"::test_mot : Tested keyword is "<<motlu<<finl;
      Cerr<<"One expected a keyword among yhe following :"<<finl<<les_mots<<finl;
      abort();
      return -1;
    }
  else
    return rang;
}
References Process::abort(), Cerr, finl, Objet_U::que_suis_je(), and Motcles::search().
Referenced by lire_motcle_non_standard().
Member Data Documentation
coeff_P_neumann
double Option_VDF::coeff_P_neumann =1. static
Definition at line 33 of file Option_VDF.h.
Referenced by Op_Grad_VDF_Face::ajouter_blocs(), lire_motcle_non_standard(), and Assembleur_P_VDF::remplir().
info_obj
const Type_info Option_VDF::info_obj static
Definition at line 25 of file Option_VDF.h.
traitement_coins
int Option_VDF::traitement_coins =0 static
Definition at line 32 of file Option_VDF.h.
Referenced by Zone_Cl_VDF::completer(), and lire_motcle_non_standard().
The documentation for this class was generated from the following files:
src/VDF/Option_VDF.h
src/VDF/Option_VDF.cpp