TRUST: Ref_Champ_P1NC Class Reference
Ref_Champ_P1NC Class Reference
#include <Ref_Champ_P1NC.h>
Public Member Functions
~Ref_Champ_P1NC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Champ_P1NC ()
Ref_Champ_P1NC (const Champ_P1NC &)
Ref_Champ_P1NC (const Ref_Champ_P1NC &)
const Champ_P1NC & valeur () const
Champ_P1NC & valeur ()
const Champ_P1NC * operator-> () const
Champ_P1NC * operator-> ()
const Ref_Champ_P1NC & operator= (const Champ_P1NC &)
const Ref_Champ_P1NC & operator= (const Ref_Champ_P1NC &)
operator const Champ_P1NC & () const
operator Champ_P1NC & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Champ_P1NC & self_cast (Objet_U &)
static const Ref_Champ_P1NC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Champ_P1NC * pointeur_
Detailed Description
Definition at line 27 of file Ref_Champ_P1NC.h.
Constructor & Destructor Documentation
Ref_Champ_P1NC::~Ref_Champ_P1NC ()
Definition at line 25 of file Ref_Champ_P1NC.cpp.
Ref_Champ_P1NC::Ref_Champ_P1NC ()
Definition at line 25 of file Ref_Champ_P1NC.cpp.
Ref_Champ_P1NC::Ref_Champ_P1NC (const Champ_P1NC & t)
Definition at line 25 of file Ref_Champ_P1NC.cpp.
Ref_Champ_P1NC::Ref_Champ_P1NC (const Ref_Champ_P1NC & t)
Definition at line 25 of file Ref_Champ_P1NC.cpp.
Member Function Documentation
Objet_U * Ref_Champ_P1NC::cree_instance () [static]
Definition at line 25 of file Ref_Champ_P1NC.cpp.
int Ref_Champ_P1NC::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Champ_P1NC.cpp.
const Type_info * Ref_Champ_P1NC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Champ_P1NC.cpp.
const Type_info & Ref_Champ_P1NC::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Champ_P1NC.cpp.
const Type_info * Ref_Champ_P1NC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Champ_P1NC.cpp.
Ref_Champ_P1NC::operator Champ_P1NC & ()
Definition at line 25 of file Ref_Champ_P1NC.cpp.
Ref_Champ_P1NC::operator const Champ_P1NC & () const
Definition at line 25 of file Ref_Champ_P1NC.cpp.
const Champ_P1NC * Ref_Champ_P1NC::operator-> () const [inline]
Definition at line 27 of file Ref_Champ_P1NC.h.
Champ_P1NC * Ref_Champ_P1NC::operator-> () [inline]
Definition at line 27 of file Ref_Champ_P1NC.h.
const Ref_Champ_P1NC & Ref_Champ_P1NC::operator= (const Ref_Champ_P1NC & t)
Definition at line 25 of file Ref_Champ_P1NC.cpp.
const Ref_Champ_P1NC & Ref_Champ_P1NC::operator= (const Champ_P1NC & t)
Definition at line 25 of file Ref_Champ_P1NC.cpp.
Sortie & Ref_Champ_P1NC::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Champ_P1NC.cpp.
Entree & Ref_Champ_P1NC::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Champ_P1NC.cpp.
const Ref_Champ_P1NC & Ref_Champ_P1NC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Champ_P1NC.cpp.
Ref_Champ_P1NC & Ref_Champ_P1NC::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Champ_P1NC.cpp.
void Ref_Champ_P1NC::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Champ_P1NC.cpp.
unsigned Ref_Champ_P1NC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Champ_P1NC.cpp.
const Champ_P1NC & Ref_Champ_P1NC::valeur () const [inline]
Definition at line 27 of file Ref_Champ_P1NC.h.
Referenced by Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Taux_cisaillement_P0_VEF::mettre_a_jour(), and Terme_Source_Qdm_lambdaup_VEF_Face::norme_L2_H1().
Champ_P1NC & Ref_Champ_P1NC::valeur () [inline]
Definition at line 27 of file Ref_Champ_P1NC.h.
Member Data Documentation
const Type_info Ref_Champ_P1NC::info_obj [static]
Reimplemented from Ref_.
Definition at line 27 of file Ref_Champ_P1NC.h.
Champ_P1NC* Ref_Champ_P1NC::pointeur_ [private]
Definition at line 27 of file Ref_Champ_P1NC.h.
The documentation for this class was generated from the following files:
src/VEF/Champs/Ref_Champ_P1NC.h
src/VEF/Champs/Ref_Champ_P1NC.cpp