TRUST: Op_Diff_VDF_base Class Reference
Op_Diff_VDF_base Class Reference
class Op_Diff_VDF_base
Classe de base des operateurs de diffusion VDF
#include <Op_Diff_VDF_base.h>
Public Member Functions
Op_Diff_VDF_base ()
~Op_Diff_VDF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Op_Diff_VDF_base (const Iterateur_VDF_base &iter_base)
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
calcule la contribution de la diffusion, la range dans resu
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
virtual void calculer_flux_bord (const DoubleTab &inco) const
const Iterateur_VDF & get_iter () const
Iterateur_VDF & get_iter ()
int has_interface_blocs () const override
void init_op_ext () const
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Static Public Member Functions
static const Type_info * info ()
static Op_Diff_VDF_base & self_cast (Objet_U &)
static const Op_Diff_VDF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
Iterateur_VDF iter
int op_ext_init_
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Diff_VDF_base
Classe de base des operateurs de diffusion VDF
Definition at line 26 of file Op_Diff_VDF_base.h.
Constructor & Destructor Documentation
Op_Diff_VDF_base() [1/2]
Op_Diff_VDF_base::Op_Diff_VDF_base ()
Definition at line 26 of file Op_Diff_VDF_base.cpp.
~Op_Diff_VDF_base()
Op_Diff_VDF_base::~Op_Diff_VDF_base () override
Definition at line 26 of file Op_Diff_VDF_base.cpp.
Op_Diff_VDF_base() [2/2]
Op_Diff_VDF_base::Op_Diff_VDF_base (const Iterateur_VDF_base & iter_base) inline
Definition at line 31 of file Op_Diff_VDF_base.h.
: iter(iter_base), op_ext_init_(0) { }
Member Function Documentation
calculer()
DoubleTab & Op_Diff_VDF_base::calculer (const DoubleTab & inco, DoubleTab & resu) const override virtual
calcule la contribution de la diffusion, la range dans resu
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VDF_Face_Axi_base, and Op_Dift_VDF_Face_Axi_base.
Definition at line 131 of file Op_Diff_VDF_base.cpp.
{
  resu =0;
  return ajouter(inco, resu);
}
References Operateur_base::ajouter().
calculer_flux_bord()
void Op_Diff_VDF_base::calculer_flux_bord (const DoubleTab & inco) const virtual
Definition at line 46 of file Op_Diff_VDF_base.cpp.
{
  iter.valeur().calculer_flux_bord(inco);
}
References Iterateur_VDF_base::calculer_flux_bord(), iter, and Deriv_Iterateur_VDF_base::valeur().
completer()
void Op_Diff_VDF_base::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Reimplemented in Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_Face, and Op_Dift_VDF_var_Face.
Definition at line 31 of file Op_Diff_VDF_base.cpp.
{
  Operateur_base::completer();
// Certains operateurs (Axi) n'ont pas d'iterateurs en VDF...
// Encore une anomalie dans la conception a corriger un jour !
  if (iter.non_nul()) iter.completer_();
}
References Operateur_base::completer(), Iterateur_VDF::completer_(), iter, and O_U_Ptr::non_nul().
Referenced by Op_Dift_VDF_Face_Axi_base::completer(), and Op_Dift_VDF_base::completer_Op_Dift_VDF_base().
contribuer_au_second_membre()
void Op_Diff_VDF_base::contribuer_au_second_membre (DoubleTab & resu) const override virtual
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
Reimplemented in Op_Dift_VDF_base, Op_Diff_VDF_Face_Axi_base, and Op_Dift_VDF_Face_Axi_base.
Definition at line 53 of file Op_Diff_VDF_base.cpp.
{
  iter.contribuer_au_second_membre(resu);
  if (equation().domaine_application() == Motcle("Hydraulique"))
// On est dans le cas des equations de Navier_Stokes
    {
// Ajout du terme du au terme supplementaire en V/(R*R)
// dans le cas des coordonnees axisymetriques
      if(Objet_U::bidim_axi == 1)
        {
          const Zone_VDF& zvdf=iter.zone();
          const Zone_Cl_VDF& zclvdf = iter.zone_Cl();
          const DoubleTab& xv=zvdf.xv();
          const IntVect& ori=zvdf.orientation();
          const IntTab& face_voisins=zvdf.face_voisins();
          const DoubleVect& volumes_entrelaces=zvdf.volumes_entrelaces();
// int nb_faces=zvdf.nb_faces();
          DoubleTrav diffu_tot(zvdf.nb_elem_tot());
          double db_diffusivite;
          if (equation().que_suis_je() == "Navier_Stokes_standard")
            {
              const Eval_Diff_VDF& eval=dynamic_cast<const Eval_Diff_VDF&> (iter->evaluateur());
              const Champ_base& ch_diff=eval.get_diffusivite();
              const DoubleTab& tab_diffusivite=ch_diff.valeurs();
              if (tab_diffusivite.size() == 1)
                diffu_tot = tab_diffusivite(0,0);
              else
                diffu_tot = tab_diffusivite;
            }
          else
            {
              Cerr << "Probleme dans Op_Diff_VDF_base::contribuer_au_second_membre  avec le type de l'equation" << finl;
              Cerr << "on n'a pas prevu d'autre cas que Navier_Stokes_std" << finl;
              exit();
            }
// Boucle sur les conditions limites pour traiter les faces de bord
          int ndeb,nfin,num_face;
          for (int n_bord=0; n_bord<zvdf.nb_front_Cl(); n_bord++)
            {
              const Cond_lim& la_cl = zclvdf.les_conditions_limites(n_bord);
              if (sub_type(Dirichlet,la_cl.valeur()))
                {
                  const Dirichlet& la_cl_diri = ref_cast(Dirichlet,la_cl.valeur());
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  double r_2,coef;
                  for (num_face=ndeb; num_face<nfin; num_face++)
                    {
                      if (ori(num_face) == 0)
{
                          int elem1=face_voisins(num_face,0);
                          int elem2=face_voisins(num_face,1);
                          if(elem1==-1)
                            db_diffusivite=diffu_tot(elem2);
                          else
{
                              assert (elem2==-1);
                              db_diffusivite=diffu_tot(elem1);
                            }
                          r_2 = xv(num_face,0)*xv(num_face,0);
                          coef = volumes_entrelaces(num_face)/r_2;
                          resu(num_face) -= (la_cl_diri.val_imp(num_face-ndeb)*coef)*db_diffusivite;
                        }
                    }
                }
            }
        }
    }
}
References Objet_U::bidim_axi, Cerr, Iterateur_VDF::contribuer_au_second_membre(), MorEqn::equation(), Iterateur_VDF::evaluateur(), Process::exit(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Eval_Diff_VDF::get_diffusivite(), iter, Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), Objet_U::que_suis_je(), ref_cast, TRUSTVect< _TYPE_ >::size(), sub_type, Dirichlet::val_imp(), Deriv_Cond_lim_base::valeur(), Champ_Proto::valeurs(), Zone_VF::volumes_entrelaces(), Zone_VF::xv(), Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
get_info()
const Type_info * Op_Diff_VDF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_base, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_var_Elem, Op_Diff_VDF_var_Elem_Axi, Op_Diff_VDF_var_Elem_aniso, Op_Diff_VDF_Multi_inco_var_Elem, Op_Diff_VDF_Multi_inco_var_Elem_Axi, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_var_Face, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_var_Face, and Op_Dift_VDF_var_Face_Axi.
Definition at line 26 of file Op_Diff_VDF_base.cpp.
get_iter() [1/2]
Iterateur_VDF & Op_Diff_VDF_base::get_iter () inline
Definition at line 39 of file Op_Diff_VDF_base.h.
{ return iter; }
References iter.
get_iter() [2/2]
const Iterateur_VDF & Op_Diff_VDF_base::get_iter () const inline
Definition at line 38 of file Op_Diff_VDF_base.h.
{ return iter; }
References iter.
has_interface_blocs()
int Op_Diff_VDF_base::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
Definition at line 41 of file Op_Diff_VDF_base.h.
  {
    return 1;
  };
impr()
int Op_Diff_VDF_base::impr (Sortie & os) const override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 39 of file Op_Diff_VDF_base.cpp.
{
// Certains operateurs (Axi) n'ont pas d'iterateurs en VDF...
// Encore une anomalie dans la conception a corriger un jour !
  return (iter.non_nul()) ? iter.impr(os) : 0;
}
References Iterateur_VDF::impr(), iter, and O_U_Ptr::non_nul().
info()
const Type_info * Op_Diff_VDF_base::info () static
Definition at line 26 of file Op_Diff_VDF_base.cpp.
init_op_ext()
void Op_Diff_VDF_base::init_op_ext () const
Definition at line 137 of file Op_Diff_VDF_base.cpp.
{
  const Zone_VDF& zvdf = iter.zone();
  const Zone_Cl_VDF& zclvdf = iter.zone_Cl();
  op_ext = { this };//le premier op_ext est l'operateur local
  for (int n_bord=0; n_bord<zvdf.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zclvdf.les_conditions_limites(n_bord);
      if (sub_type(Echange_contact_VDF,la_cl.valeur()))
        {
          const Echange_contact_VDF& cl = ref_cast(Echange_contact_VDF, la_cl.valeur());
          const Champ_front_calc& ch=ref_cast(Champ_front_calc, cl.T_autre_pb().valeur());
          const Equation_base& o_eqn = ch.equation();
          const Op_Diff_VDF_base *o_diff = &ref_cast(Op_Diff_VDF_base, o_eqn.operateur(0).l_op_base());
          if (std::find(op_ext.begin(), op_ext.end(), o_diff) == op_ext.end()) op_ext.push_back(o_diff);
        }
    }
  op_ext_init_ = 1;
}
References Champ_front_calc::equation(), iter, Operateur::l_op_base(), Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_front_Cl(), Operateur_Diff_base::op_ext, op_ext_init_, Equation_base::operateur(), ref_cast, sub_type, Echange_contact_VDF::T_autre_pb(), Deriv_Champ_front_base::valeur(), Deriv_Cond_lim_base::valeur(), Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
Referenced by Op_Diff_VDF_Elem_base::ajouter_blocs(), and Op_Diff_VDF_Elem_base::dimensionner_blocs().
printOn()
Sortie & Op_Diff_VDF_base::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_base, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_var_Elem, Op_Diff_VDF_var_Elem_Axi, Op_Diff_VDF_var_Elem_aniso, Op_Diff_VDF_Multi_inco_var_Elem, Op_Diff_VDF_Multi_inco_var_Elem_Axi, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_var_Face, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_var_Face, and Op_Dift_VDF_var_Face_Axi.
Definition at line 28 of file Op_Diff_VDF_base.cpp.
{ return s << que_suis_je() ; }
References Objet_U::que_suis_je().
Referenced by Op_Dift_VDF_base::printOn().
readOn()
Entree & Op_Diff_VDF_base::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi_base, Op_Diff_VDF_Face_base, Op_Dift_VDF_base, Op_Dift_VDF_Elem_base, Op_Dift_VDF_Face_Axi_base, Op_Dift_VDF_Face_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_var_Elem, Op_Diff_VDF_var_Elem_Axi, Op_Diff_VDF_var_Elem_aniso, Op_Diff_VDF_Multi_inco_var_Elem, Op_Diff_VDF_Multi_inco_var_Elem_Axi, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_var_Face, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_var_Face, and Op_Dift_VDF_var_Face_Axi.
Definition at line 29 of file Op_Diff_VDF_base.cpp.
{ return s ; }
Referenced by Op_Dift_VDF_base::readOn().
self_cast() [1/2]
const Op_Diff_VDF_base & Op_Diff_VDF_base::self_cast (const Objet_U & r) static
Definition at line 26 of file Op_Diff_VDF_base.cpp.
self_cast() [2/2]
Op_Diff_VDF_base & Op_Diff_VDF_base::self_cast (Objet_U & r) static
Definition at line 26 of file Op_Diff_VDF_base.cpp.
Member Data Documentation
info_obj
const Type_info Op_Diff_VDF_base::info_obj static
Definition at line 28 of file Op_Diff_VDF_base.h.
iter
Iterateur_VDF Op_Diff_VDF_base::iter protected
Definition at line 48 of file Op_Diff_VDF_base.h.
Referenced by Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Op_Dift_VDF_Face_base::calculer_borne_locale(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi(), calculer_flux_bord(), completer(), contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Diff_VDF_Face_base::dimensionner_blocs(), Op_Dift_VDF_Elem_base::dimensionner_blocs(), Op_Dift_VDF_Face_base::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), get_iter(), impr(), init_op_ext(), Op_Diff_VDF_Elem_base::modifier_pour_Cl(), Op_Diff_VDF_Face_base::modifier_pour_Cl(), Op_Dift_VDF_Elem_base::modifier_pour_Cl(), and Op_Dift_VDF_Face_base::modifier_pour_Cl().
op_ext_init_
int Op_Diff_VDF_base::op_ext_init_ mutable protected
Definition at line 49 of file Op_Diff_VDF_base.h.
Referenced by Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), and init_op_ext().
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Op_Diff_Dift/Op_Diff_Dift_base/Op_Diff_VDF_base.h
src/VDF/Operateurs/Op_Diff_Dift/Op_Diff_Dift_base/Op_Diff_VDF_base.cpp