TRUST: TRUSTListElem< _TYPE_ > Class Template Reference
TRUSTListElem< _TYPE_ > Class Template Reference
: Classe qui sert a representer une liste de reels int/double precision. On ne peut pas utiliser la classe container
List avec des objets du type int/double car int/double est un type predefini du C++ qui ne possede pas les fonctions exigees par List< >.
#include <TRUSTListElem.h>
Public Member Functions
TRUSTListElem ()
Construit une liste vide.
TRUSTListElem (const _TYPE_ x)
Construit le singleton (x).
TRUSTListElem (const TRUSTListElem &)
Constructeur par copie
Parametre: const TRUSTListElem& list (la liste a copier)
~TRUSTListElem ()
int est_vide () const
renvoie 1 si la liste est vide. 0 sinon
int est_dernier () const
renvoie 1 si il n'y a pas de suivant. 0 sinon
_TYPE_ & valeur ()
_TYPE_ valeur () const
TRUSTListElem & add (_TYPE_)
insertion en queue
Parametre: int/double value_to_add (element a ajouter)
TRUSTListElem & suivant ()
const TRUSTListElem & suivant () const
Protected Attributes
_TYPE_ data
TRUSTListElem * suivant_
Friends
class TRUSTList< _TYPE_ >
template<typename T >
int operator== (const TRUSTListElem< T > &, const TRUSTListElem< T > &)
Detailed Description
template<typename _TYPE_>
class TRUSTListElem< _TYPE_ >
: Classe qui sert a representer une liste de reels int/double precision. On ne peut pas utiliser la classe container
List avec des objets du type int/double car int/double est un type predefini du C++ qui ne possede pas les fonctions exigees par List< >.
Definition at line 27 of file TRUSTListElem.h.
Constructor & Destructor Documentation
TRUSTListElem() [1/3]
template<typename _TYPE_ > TRUSTListElem< _TYPE_ >::TRUSTListElem () inline
Construit une liste vide.
Definition at line 32 of file TRUSTListElem.h.
References TRUSTListElem< _TYPE_ >::suivant_.
TRUSTListElem() [2/3]
template<typename _TYPE_ > TRUSTListElem< _TYPE_ >::TRUSTListElem (const _TYPE_ x) inline
Construit le singleton (x).
Definition at line 33 of file TRUSTListElem.h.
TRUSTListElem() [3/3]
template<typename _TYPE_ > TRUSTListElem< _TYPE_ >::TRUSTListElem (const TRUSTListElem< _TYPE_ > & list)
Constructeur par copie
Parametre: const TRUSTListElem& list (la liste a copier)
Definition at line 61 of file TRUSTListElem.h.
{
  if (list.est_vide()) suivant_ = this;
  else
    {
      data = list.data;
      if (list.suivant_)
        {
          TRUSTListElem<_TYPE_> *next = new TRUSTListElem<_TYPE_>(*list.suivant_); //Recursif !!
          suivant_ = next;
        }
      else suivant_ = 0;
    }
}
References TRUSTListElem< _TYPE_ >::data, TRUSTListElem< _TYPE_ >::est_vide(), next(), and TRUSTListElem< _TYPE_ >::suivant_.
~TRUSTListElem()
template<typename _TYPE_ > TRUSTListElem< _TYPE_ >::~TRUSTListElem
Definition at line 77 of file TRUSTListElem.h.
{
  if (est_vide()) suivant_ = 0;
  if (suivant_)
    {
// On ne garde pas la version delete suivant_ car sinon on est limite par le nombre d'appel recursif possible
// delete suivant_;
      TRUSTListElem<_TYPE_> *poignee, *pr;
      pr = suivant_;
      suivant_ = 0;
      while (pr)
        {
          poignee = pr->suivant_;
          pr->suivant_ = 0;
          delete pr;
          pr = poignee;
        }
    }
}
References TRUSTListElem< _TYPE_ >::est_vide(), and TRUSTListElem< _TYPE_ >::suivant_.
Member Function Documentation
add()
template<typename _TYPE_ > TRUSTListElem< _TYPE_ > & TRUSTListElem< _TYPE_ >::add (_TYPE_ value_to_add) inline
insertion en queue
Parametre: int/double value_to_add (element a ajouter)
Definition at line 101 of file TRUSTListElem.h.
{
  assert(est_dernier());
  TRUSTListElem<_TYPE_> *next = new TRUSTListElem<_TYPE_>(value_to_add);
  suivant_ = next;
  return *this;
}
References TRUSTListElem< _TYPE_ >::est_dernier(), next(), and TRUSTListElem< _TYPE_ >::suivant_.
est_dernier()
template<typename _TYPE_ > int TRUSTListElem< _TYPE_ >::est_dernier () const inline
renvoie 1 si il n'y a pas de suivant. 0 sinon
Definition at line 38 of file TRUSTListElem.h.
References TRUSTListElem< _TYPE_ >::est_vide(), and TRUSTListElem< _TYPE_ >::suivant_.
Referenced by TRUSTListElem< _TYPE_ >::add(), and operator==().
est_vide()
template<typename _TYPE_ > int TRUSTListElem< _TYPE_ >::est_vide () const inline
renvoie 1 si la liste est vide. 0 sinon
Definition at line 37 of file TRUSTListElem.h.
References TRUSTListElem< _TYPE_ >::suivant_.
Referenced by Op_Rot_VEFP1B::ajouter(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), Op_Diff_RotRot::elements_pour_sommet(), TRUSTListElem< _TYPE_ >::est_dernier(), Op_Diff_VEF_Face_Penalise::faces_communes(), TRUSTList< _TYPE_ >::operator=(), TRUSTList_Curseur< _TYPE_ >::operator=(), Op_Diff_VEF_Face_Penalise::reduction(), Op_Diff_RotRot::sommets_pour_element(), Op_Diff_RotRot::Tri(), TRUSTList< _TYPE_ >::TRUSTList(), TRUSTList_Curseur< _TYPE_ >::TRUSTList_Curseur(), TRUSTListElem< _TYPE_ >::TRUSTListElem(), Op_Diff_VEF_Face_Penalise::voisinage(), and TRUSTListElem< _TYPE_ >::~TRUSTListElem().
suivant() [1/2]
template<typename _TYPE_ > TRUSTListElem & TRUSTListElem< _TYPE_ >::suivant () inline
Definition at line 44 of file TRUSTListElem.h.
{ return *suivant_; }
References TRUSTListElem< _TYPE_ >::suivant_.
suivant() [2/2]
template<typename _TYPE_ > const TRUSTListElem & TRUSTListElem< _TYPE_ >::suivant () const inline
Definition at line 45 of file TRUSTListElem.h.
{ return *suivant_; }
References TRUSTListElem< _TYPE_ >::suivant_.
valeur() [1/2]
template<typename _TYPE_ > _TYPE_ & TRUSTListElem< _TYPE_ >::valeur () inline
Definition at line 40 of file TRUSTListElem.h.
{ return data; }
References TRUSTListElem< _TYPE_ >::data.
valeur() [2/2]
template<typename _TYPE_ > _TYPE_ TRUSTListElem< _TYPE_ >::valeur () const inline
Definition at line 41 of file TRUSTListElem.h.
{ return data; }
References TRUSTListElem< _TYPE_ >::data.
Friends And Related Function Documentation
operator==
template<typename _TYPE_ > template<typename T > int operator== (const TRUSTListElem< T > & , const TRUSTListElem< T > &) friend
TRUSTList< _TYPE_ >
template<typename _TYPE_ > friend class TRUSTList< _TYPE_ > friend
Definition at line 112 of file TRUSTListElem.h.
Member Data Documentation
data
template<typename _TYPE_ > _TYPE_ TRUSTListElem< _TYPE_ >::data protected
Definition at line 51 of file TRUSTListElem.h.
Referenced by operator==(), TRUSTList< _TYPE_ >::TRUSTList(), TRUSTListElem< _TYPE_ >::TRUSTListElem(), and TRUSTListElem< _TYPE_ >::valeur().
suivant_
template<typename _TYPE_ > TRUSTListElem* TRUSTListElem< _TYPE_ >::suivant_ protected
Definition at line 52 of file TRUSTListElem.h.
Referenced by TRUSTListElem< _TYPE_ >::add(), TRUSTListElem< _TYPE_ >::est_dernier(), TRUSTListElem< _TYPE_ >::est_vide(), operator==(), TRUSTListElem< _TYPE_ >::suivant(), TRUSTList< _TYPE_ >::TRUSTList(), TRUSTListElem< _TYPE_ >::TRUSTListElem(), and TRUSTListElem< _TYPE_ >::~TRUSTListElem().
The documentation for this class was generated from the following file:
src/Kernel/Math/TRUSTListElem.h