TRUST: Op_Dift_EF_Q1 Class Reference
Op_Dift_EF_Q1 Class Reference
class Op_Dift_EF_Q1
Cette classe represente l'operateur de diffusion
La discretisation est EF
Le champ diffuse est scalaire
Le champ de diffusivite est uniforme
#include <Op_Dift_EF_Q1.h>
Public Member Functions
Op_Dift_EF_Q1 ()
~Op_Dift_EF_Q1 ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_diffusivite (const Champ_base &) override
associe le champ de diffusivite
const Champ_base & diffusivite () const override
double diffusivite (int) const
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & ajouter_new (const DoubleTab &, DoubleTab &) const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
void verifier () const
void remplir_nu (DoubleTab &) const override
void remplir_marqueur_elem_CL_paroi (ArrOfInt &, const Zone_EF &, const Zone_Cl_EF &) const
void dimensionner (Matrice_Morse &matrice) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &inco, Matrice_Morse &matrice) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_au_second_membre (DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void ajouter_bords (const DoubleTab &, DoubleTab &, int contrib_interne=1) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contributions_bords (Matrice_Morse &matrice) const
void ajouter_contribution_new (const DoubleTab &, Matrice_Morse &) const
void ajouter_cas_scalaire (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_EF &zone_Cl_EF, const Zone_EF &zone_EF) const
void ajouter_cas_vectoriel (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_EF &zone_Cl_EF, const Zone_EF &zone_EF, int nb_comp) const
Public Member Functions inherited from Op_Dift_EF_base
Op_Dift_EF_base ()
~Op_Dift_EF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_modele_turbulence (const Mod_turb_hyd_base &)
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
void calculer_borne_locale (DoubleVect &, double, double) const override
Public Member Functions inherited from Op_Diff_EF_base
Op_Diff_EF_base ()
~Op_Diff_EF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
double calculer_dt_stab () const override
Calcul dt_stab.
virtual void remplir_nu (DoubleTab &) const =0
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Op_EF_base
void dimensionner (const Zone_EF &, const Zone_Cl_EF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_EF &, const Zone_Cl_EF &, Matrice_Morse &, DoubleTab &) const
void modifier_flux (const Operateur_base &) const
int impr (Sortie &, const Operateur_base &) const
int elem_contribue (const int elem) const
void marque_elem (const Equation_base &eqn)
Public Member Functions inherited from Op_Diff_Turbulent_base
virtual ~Op_Diff_Turbulent_base ()
void associer_diffusivite_turbulente (const Champ_Fonc &)
const Champ_Fonc & diffusivite_turbulente () const
bool has_diffusivite_turbulente () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Dift_EF_Q1 & self_cast (Objet_U &)
static const Op_Dift_EF_Q1 & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Dift_EF_base
static const Type_info * info ()
static Op_Dift_EF_base & self_cast (Objet_U &)
static const Op_Dift_EF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_EF_base
static const Type_info * info ()
static Op_Diff_EF_base & self_cast (Objet_U &)
static const Op_Diff_EF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Dift_EF_base
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_EF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
DoubleTab & ajouter_scalaire_dim3_nbn_8 (const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_scalaire_dim2_nbn_4 (const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_scalaire_gen (const DoubleTab &, DoubleTab &) const
template<AJOUTE_SCAL _T_>
DoubleTab & ajouter_scalaire_template (const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_vectoriel_dim3_nbn_8 (const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_vectoriel_dim2_nbn_4 (const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_vectoriel_gen (const DoubleTab &, DoubleTab &) const
template<AJOUTE_VECT _T_>
DoubleTab & ajouter_vectoriel_template (const DoubleTab &, DoubleTab &) const
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
int transpose_
vaurt zero si on ne veut pas calculer grad u transpose
int transpose_partout_
vaut 1 si on veut calculer grad_u_transpose meme au bord
int nouvelle_expression_
Ref_Champ_base diffusivite_
Protected Attributes inherited from Op_Dift_EF_base
Ref_Mod_turb_hyd_base le_modele_turbulence
A deplacer dans Op_Diff_turb ?
DoubleTab tau_tan_
Protected Attributes inherited from Op_Diff_EF_base
Ref_Zone_EF la_zone_EF
Ref_Zone_Cl_EF la_zcl_EF
Ref_Champ_Inc_base inconnue
DoubleTab nu_
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Protected Attributes inherited from Op_EF_base
Matrice_Morse matrice_sto_
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Dift_EF_Q1
Cette classe represente l'operateur de diffusion
La discretisation est EF
Le champ diffuse est scalaire
Le champ de diffusivite est uniforme
Definition at line 33 of file Op_Dift_EF_Q1.h.
Constructor & Destructor Documentation
Op_Dift_EF_Q1()
Op_Dift_EF_Q1::Op_Dift_EF_Q1 ()
Definition at line 38 of file Op_Dift_EF_Q1.cpp.
:transpose_(1),transpose_partout_(0),nouvelle_expression_(0) { }
~Op_Dift_EF_Q1()
Op_Dift_EF_Q1::~Op_Dift_EF_Q1 ()
Definition at line 36 of file Op_Dift_EF_Q1.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Dift_EF_Q1::ajouter (const DoubleTab & tab_inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 116 of file Op_Dift_EF_Q1.cpp.
{
  if ((equation().nombre_d_operateurs()>1)&&sub_type(Op_Conv_EF,equation().operateur(1).l_op_base()))
    ref_cast(Op_Conv_EF,equation().operateur(1).l_op_base()).ajouter_a_la_diffusion(tab_inconnue,resu);
// ref_cast(Op_Conv_EF,equation().operateur(1).l_op_base()).ajouter_sous_cond(tab_inconnue,resu,0,0,1);
  if (nouvelle_expression_==1)
    return ajouter_new(tab_inconnue,resu);
  remplir_nu(nu_);
// const Zone_Cl_EF& zone_Cl_EF = la_zcl_EF.valeur();
  const Zone_EF& zone_ef = la_zone_EF.valeur();
  int nb_som_elem=zone_ef.zone().nb_som_elem();
  int N = resu.line_size();
  Nature_du_champ nat= equation().inconnue().valeur().nature_du_champ();
  if (nat==vectoriel)
    {
      if ((dimension==3)&&(nb_som_elem==8))
        return ajouter_vectoriel_dim3_nbn_8(tab_inconnue,resu);
      else if ((dimension==2)&&(nb_som_elem==4))
        {
          return ajouter_vectoriel_dim2_nbn_4(tab_inconnue,resu);
        }
      else
        {
          Cerr<<__FILE__<<(int)__LINE__<< "cas non optimise "<<finl;
          return ajouter_vectoriel_gen(tab_inconnue,resu);
        }
    }
  else
    {
      if (N != 1)
        {
          Cerr<<__FILE__<<(int)__LINE__<< "cas non prevu "<<finl;
          assert(0);
          exit();
          return ajouter(tab_inconnue,resu);
        }
      if ((dimension==3)&&(nb_som_elem==8))
        return ajouter_scalaire_dim3_nbn_8(tab_inconnue,resu);
      else if ((dimension==2)&&(nb_som_elem==4))
        {
          return ajouter_scalaire_dim2_nbn_4(tab_inconnue,resu);
        }
      else
        {
          Cerr<<__FILE__<<(int)__LINE__<< "cas non optimise "<<finl;
          return ajouter_scalaire_gen(tab_inconnue,resu);
        }
    }
//
}
References ajouter(), ajouter_new(), ajouter_scalaire_dim2_nbn_4(), ajouter_scalaire_dim3_nbn_8(), ajouter_scalaire_gen(), ajouter_vectoriel_dim2_nbn_4(), ajouter_vectoriel_dim3_nbn_8(), ajouter_vectoriel_gen(), Cerr, Objet_U::dimension, MorEqn::equation(), Process::exit(), finl, Equation_base::inconnue(), Op_Diff_EF_base::la_zone_EF, TRUSTVect< _TYPE_ >::line_size(), Field_base::nature_du_champ(), Zone::nb_som_elem(), nouvelle_expression_, Op_Diff_EF_base::nu_, ref_cast, remplir_nu(), sub_type, Ref_Zone_EF::valeur(), Deriv_Champ_Inc_base::valeur(), vectoriel, and Zone_dis_base::zone().
Referenced by ajouter(), and calculer().
ajouter_bords()
void Op_Dift_EF_Q1::ajouter_bords (const DoubleTab & tab_inconnue, DoubleTab & resu, int contrib_interne = 1) const
< face on the other side of the inner wall:
< first time we encounter one of the face of the pair
< 2 faces per elem max - 1D
< taken from ajouter() ...
< other face of the current elem
< taken from ajouter() ...
< remove B.T(i+2) and add B.T(i)
< contrib_interne=0 --> implicit
< opposite temp.
< explicit case
< implicit case via contribuer_au_second_membre()
Definition at line 427 of file Op_Dift_EF_Q1.cpp.
{
// a mettre dans calculer_flux_bord....
  const Zone_Cl_EF& zone_Cl_EF = la_zcl_EF.valeur();
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  flux_bords_=0.;
// const DoubleTab& tab_inconnue=equation().inconnue().valeurs();
// on parcourt toutes les faces de bord et on calcule lambda*gradT
  const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
  const IntTab& face_voisins=zone_ef.face_voisins();
  const DoubleTab& bij=zone_ef.Bij();
  int nb_som_elem=zone_ef.zone().nb_som_elem();
  const IntTab& elems=zone_ef.zone().les_elems() ;
  const DoubleTab& face_normales=zone_ef.face_normales();
  const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
  const DoubleVect& volumes= zone_ef.volumes();
  const IntTab& face_sommets=zone_ef.face_sommets();
  int nb_som_face=zone_ef.nb_som_face();
  int nb_faces_elem = zone_ef.zone().nb_faces_elem();
  const IntTab& elem_faces = zone_ef.elem_faces();
  int nb_som_free = nb_som_elem-nb_som_face;
  const int N = resu.line_size();
  DoubleVect diffu_turb(diffusivite_turbulente()->valeurs());
  DoubleTab diffu(nu_);
  if (N > 1)
    {
      for (int n_bord=0; n_bord<zone_ef.nb_front_Cl(); n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_EF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int nb_faces_bord = le_bord.nb_faces();
          int num1=0;
          int num2=nb_faces_bord;
          if (sub_type(Dirichlet_paroi_fixe,la_cl.valeur()) ||
              sub_type(Dirichlet_paroi_defilante,la_cl.valeur()) )
            {
              if (le_modele_turbulence.valeur().utiliser_loi_paroi())
                {
                  DoubleVect n(dimension);
                  DoubleTrav Tgrad(dimension,dimension);
                  ArrOfDouble effort_face(dimension);
                  ArrOfDouble effort_elem(dimension);
                  ArrOfInt som_CL(nb_som_face);
// Boucle sur les faces de la CL
                  for (int ind_face=num1; ind_face<num2; ind_face++)
                    {
                      int num_face = le_bord.num_face(ind_face);
                      for (int isom=0; isom<nb_som_face; isom++)
{
                          int glob2=face_sommets(num_face,isom);
                          som_CL(isom) = glob2;
                        }
                      int elem=face_voisins(num_face,0);
                      double pond=volumes_thilde(elem)/volumes(elem);
                      for (int a=0; a<dimension; a++) n[a]=face_normales(num_face,a);
                      n/=norme_array(n);
// Calcul du gradient gradU via tau
// Au bord, n toujours oriente vers l'exterieur
                      for (int nc=0; nc<dimension; nc++)
                        for (int nc2=0; nc2<dimension; nc2++)
                          Tgrad(nc,nc2)=tau_tan_(num_face,nc)*n[nc2];
// Boucle sur les faces de l'element
// (Sigma_e somme_face n = 0 => -Sigma_e somme_face_cl n = + Sigma_e somme_face_non_cl n)
                      effort_elem = 0.;
                      for (int i=0; i<nb_faces_elem; i++)
{
                          int face_i=elem_faces(elem,i);
// On calcule la contribution de la face :
                          effort_face = 0.;
                          double ori=1.;
                          if ( face_voisins(face_i,0) != elem ) ori=-1;
                          if (face_i != num_face)
                            for (int nc=0; nc<dimension; nc++)
                              for (int nc2=0; nc2<dimension; nc2++)
                                effort_face(nc)+=ori*(Tgrad(nc,nc2)*face_normales(face_i,nc2))*pond;
// Cerr<<"force cisaillement face "<<i<<" => "<<effort_face<<finl;
                          effort_elem+=effort_face;
                        }
// Cerr<<"force cisaillement elem "<<elem<<" => "<<effort_elem<<finl;
// On calcule la contribution a chaque noeud de l'element :
// (les nb_som_face noeuds de la face CL Dirichlet ne sont pas concernes)
                      int nb_iok = 0;
                      for (int jsom=0; jsom<nb_som_elem; jsom++)
{
                          int num_som = elems(elem,jsom);
                          int iok = 1;
                          for (int isom=0; isom<nb_som_face; isom++)
                            if (num_som == som_CL(isom)) iok = 0;
                          nb_iok += iok;
                          if (iok)
                            for (int nc=0; nc<dimension; nc++)
                              resu(num_som,nc)+= effort_elem(nc)/(nb_som_free);
                        }
                      if (nb_iok != nb_som_free)
{
                          Cerr<<"Op_Dift_EF_Q1::ajouter_bords: erreur nombre de noeuds"<<finl;
                          exit();
                        }
                    }
                }
            }
        }
// Cerr<<__PRETTY_FUNCTION__<<" non code pour les vecteurs"<<finl;
      modifier_flux(*this);
      return;
    }
  int premiere_face_int=zone_ef.premiere_face_int();
  for (int face=0; face<premiere_face_int; face++)
    {
      int elem=face_voisins(face,0);
      if (elem==-1) face_voisins(face,1);
      double pond= volumes_thilde(elem)/volumes(elem)/volumes(elem);
      for (int i1=0; i1<nb_som_elem; i1++)
        {
          int glob2=elems(elem,i1);
          {
            for (int a=0; a<dimension; a++)
              {
                flux_bords_(face,0)+=face_normales(face,a)*bij(elem,i1,a)*tab_inconnue(glob2)*(diffu[elem]+diffu_turb[elem])*pond;
              }
          }
        }
    }
// Neumann :
  int n_bord;
  int nb_bords=zone_Cl_EF.nb_cond_lim();
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_EF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi, la_cl.valeur());
          for (int face=ndeb; face<nfin; face++)
            {
              double flux=la_cl_paroi.flux_impose(face-ndeb)*zone_EF.surface(face);
              for (int i1=0; i1<nb_som_face; i1++)
                {
                  int glob2=face_sommets(face,i1);
                  {
                    resu[glob2] += flux/nb_som_face;
                  }
                  flux_bords_(face,0) = flux;
                }
            }
        }
      else if (sub_type(Echange_couplage_thermique, la_cl.valeur()))
        {
          const Echange_couplage_thermique& la_cl_paroi = ref_cast(Echange_couplage_thermique, la_cl.valeur());
          for (int face=ndeb; face<nfin; face++)
            {
              double h=la_cl_paroi.h_imp(face-ndeb);
              double Text=la_cl_paroi.T_ext(face-ndeb);
              double phiext=la_cl_paroi.flux_exterieur_impose(face-ndeb);
              double tm=0;
              if (contrib_interne)
                {
                  for (int i1=0; i1<nb_som_face; i1++)
                    {
                      int glob2=face_sommets(face,i1);
                      tm+=tab_inconnue(glob2);
                    }
                  tm/=nb_som_face;
                }
              double flux=(phiext+h*(Text-tm))*zone_EF.surface(face);
              flux_bords_(face,0) = flux;
              flux/=nb_som_face;
              for (int i1=0; i1<nb_som_face; i1++)
                {
                  int glob2=face_sommets(face,i1);
                  resu[glob2] += flux;
                }
            }
        }
      else if (sub_type(Echange_interne_global_parfait, la_cl.valeur()))
        {
          if (contrib_interne)
            {
              const Echange_interne_global_parfait& la_cl_paroi = ref_cast(Echange_interne_global_parfait, la_cl.valeur());
              const Champ_front_calc_interne& Text = ref_cast(Champ_front_calc_interne, la_cl_paroi.T_ext().valeur());
              const IntTab& fmap = Text.face_map();
              std::vector<bool> hit(nfin-ndeb);
              std::fill(hit.begin(), hit.end(), false);
              for (int face=ndeb; face<nfin; face++)
                {
                  int opp_face = fmap(face-ndeb)+ndeb;   //!< face on the other side of the inner wall:
// STRONG assumption : 1D, only one node per face:
                  int som=face_sommets(face,0);
                  int som_opp=face_sommets(opp_face,0);
                  if (!hit[face-ndeb])  //!< first time we encounter one of the face of the pair
                    {
// This where we write the heat equation skipping duplicated face: -A.T(i-1) + (A*T(i)+B.T(i)) - B.T(i+2)
// By default, we just have -A.T(i-1) + A*T(i)
// Recompute the extra bit of flux coming from the other side:
// Get opposite element
                      int elem1 = zone_EF.face_voisins(opp_face, 0);
                      int elem_opp = (elem1 != -1) ? elem1 : zone_EF.face_voisins(opp_face, 1);
// Other face of the opposite element (i.e. face "after" opp_face)
                      int f1 = zone_EF.elem_faces(elem_opp, 0);
                      int face_plus_2 = f1 != opp_face ? f1 : zone_EF.elem_faces(elem_opp, 1);  //!< 2 faces per elem max - 1D
                      int som_p2 = face_sommets(face_plus_2, 0);
                      double pond = volumes_thilde(elem_opp)/volumes(elem_opp)/volumes(elem_opp); //!< taken from ajouter() ...
                      double B = nu_(elem_opp)*pond;
                      resu[som] -= B*(tab_inconnue[som]-tab_inconnue[som_p2]);
                    }
                  else
                    {
// This is where we set a Dirichlet T(face) = T(opposite_face)
// Initially, flux for this som is -B.T(i+1) + B.T(i+2)   with B = nu(i+1)  (nu being the diffusivity)
// -> We want to have  B.T(i) - B.T(i+1)
                      int elem = zone_EF.face_voisins(face, 0);
                      int f1 = zone_EF.elem_faces(elem, 0);
                      int face_p2 = f1 != face ? f1 : zone_EF.elem_faces(elem, 1);  //!< other face of the current elem
                      int som_p2=face_sommets(face_p2,0);
                      double pond = volumes_thilde(elem)/volumes(elem)/volumes(elem); //!< taken from ajouter() ...
                      double B = nu_(elem)*pond;
                      resu[som] += B*(-tab_inconnue[som_p2] + tab_inconnue[som_opp]); //!< remove B.T(i+2) and add B.T(i)
                    }
                  hit[face-ndeb] = true;
                  hit[opp_face-ndeb] = true;
                }
            }
          else   //!< contrib_interne=0 --> implicit
            {
              for (int face=ndeb; face<nfin; face++)
                {
                  flux_bords_(face,0) = 0.0;
                }
            }
        }
      else if (sub_type(Echange_interne_global_impose, la_cl.valeur()))
        {
          const Echange_interne_global_impose& la_cl_paroi = ref_cast(Echange_interne_global_impose, la_cl.valeur());
          const DoubleVect& surface_gap = la_cl_paroi.surface_gap();
          for (int face=ndeb; face<nfin; face++)
            {
              double h=la_cl_paroi.h_imp(face-ndeb);
              const Champ_front_calc_interne& Text = ref_cast(Champ_front_calc_interne, la_cl_paroi.T_ext().valeur());
              const IntTab& fmap = Text.face_map();
              int opp_face = fmap(face-ndeb)+ndeb;
              double tm=0.0;
              double to=0.0;  //!< opposite temp.
              double flux=0.0;
              if (contrib_interne)  //!< explicit case
                {
                  for (int i1=0; i1<nb_som_face; i1++)
                    {
                      int glob2=face_sommets(face,i1);
                      int glob3 =face_sommets(opp_face,i1);
                      tm+=tab_inconnue(glob2);
                      to+=tab_inconnue(glob3);
                    }
                  tm/=nb_som_face;
                  to/=nb_som_face;
// flux=h*(to-tm)*zone_EF.surface(face);
                  flux=h*(to-tm)*surface_gap(face-ndeb);
                }
              else   //!< implicit case via contribuer_au_second_membre()
                {
                  flux = 0.0;
                }
              flux_bords_(face,0) = flux;
              flux/=nb_som_face;
              for (int i1=0; i1<nb_som_face; i1++)
                {
                  int glob2=face_sommets(face,i1);
                  resu[glob2] += flux;
                }
            }
        }
      else if (sub_type(Echange_global_impose, la_cl.valeur()))
        {
          const Echange_global_impose& la_cl_paroi = ref_cast(Echange_global_impose, la_cl.valeur());
          for (int face=ndeb; face<nfin; face++)
            {
              double h=la_cl_paroi.h_imp(face-ndeb);
              double Text=la_cl_paroi.T_ext(face-ndeb);
              double tm=0;
              if (contrib_interne)
                {
                  for (int i1=0; i1<nb_som_face; i1++)
                    {
                      int glob2=face_sommets(face,i1);
                      {
                        tm+=tab_inconnue(glob2);
                      }
                    }
                  tm/=nb_som_face;
                }
              double flux=h*(Text-tm)*zone_EF.surface(face);
              flux_bords_(face,0) = flux;
              flux/=nb_som_face;
              for (int i1=0; i1<nb_som_face; i1++)
                {
                  int glob2=face_sommets(face,i1);
                  {
                    resu[glob2] += flux;
                  }
                }
            }
        }
    }
  modifier_flux(*this);
}
References Zone_EF::Bij(), Cerr, Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Process::exit(), f1, Champ_front_calc_interne::face_map(), Zone_EF::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), finl, Operateur_base::flux_bords_, Echange_couplage_thermique::flux_exterieur_impose(), Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Echange_impose_base::h_imp(), Op_Diff_EF_base::la_zcl_EF, Op_Diff_EF_base::la_zone_EF, Op_Dift_EF_base::le_modele_turbulence, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), TRUSTVect< _TYPE_ >::line_size(), Op_EF_base::modifier_flux(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Zone::nb_faces_elem(), Zone_dis_base::nb_front_Cl(), Zone::nb_som_elem(), Zone_VF::nb_som_face(), norme_array(), Op_Diff_EF_base::nu_, Front_VF::num_face(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, sub_type, Zone_VF::surface(), Echange_interne_global_impose::surface_gap(), Echange_impose_base::T_ext(), Op_Dift_EF_base::tau_tan_, Mod_turb_hyd_base::utiliser_loi_paroi(), Ref_Zone_Cl_EF::valeur(), Ref_Zone_EF::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Mod_turb_hyd_base::valeur(), valeur(), Zone_VF::volumes(), Zone_EF::volumes_thilde(), and Zone_dis_base::zone().
Referenced by ajouter_new(), ajouter_scalaire_template(), ajouter_vectoriel_template(), and contribuer_au_second_membre().
ajouter_cas_scalaire()
void Op_Dift_EF_Q1::ajouter_cas_scalaire (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Zone_Cl_EF & zone_Cl_EF, const Zone_EF & zone_EF) const
ajouter_cas_vectoriel()
void Op_Dift_EF_Q1::ajouter_cas_vectoriel (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Zone_Cl_EF & zone_Cl_EF, const Zone_EF & zone_EF, int nb_comp) const
ajouter_contribution()
void Op_Dift_EF_Q1::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
Definition at line 294 of file Op_Dift_EF_Q1.cpp.
{
  if (1)
    if ((equation().nombre_d_operateurs()>1)&&sub_type(Op_Conv_EF,equation().operateur(1).l_op_base()))
      ref_cast(Op_Conv_EF,equation().operateur(1).l_op_base()).ajouter_contribution_a_la_diffusion(transporte,matrice);
  if (nouvelle_expression_==1)
    {
      ajouter_contribution_new(transporte,matrice);
    }
// On remplit le tableau nu car l'assemblage d'une
// matrice avec ajouter_contribution peut se faire
// avant le premier pas de temps
  remplir_nu(nu_);
  DoubleVect diffu_turb(diffusivite_turbulente()->valeurs());
  DoubleTab diffu(nu_);
  const int N = transporte.line_size();
  const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
  const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
  const DoubleVect& volumes= zone_ef.volumes();
  const DoubleTab& bij=zone_ef.Bij();
  int nb_elem_tot=zone_ef.zone().nb_elem_tot();
  int nb_som_elem=zone_ef.zone().nb_som_elem();
  const IntTab& elems=zone_ef.zone().les_elems() ;
  int nb_som=zone_ef.zone().nb_som();
  ArrOfInt marqueur_neuman;
  remplir_marqueur_sommet_neumann( marqueur_neuman,zone_ef,la_zcl_EF.valeur(),transpose_partout_ );
  ArrOfInt marqueur_paroi = 0;
  remplir_marqueur_elem_CL_paroi( marqueur_paroi,zone_ef,la_zcl_EF.valeur() );
  for (int elem=0; elem<nb_elem_tot; elem++)
    if (elem_contribue(elem)&&(!marqueur_paroi(elem)))
      {
        double pond=volumes_thilde(elem)/volumes(elem)/volumes(elem);
        for (int i1=0; i1<nb_som_elem; i1++)
          {
            int glob=elems(elem,i1);
            int transpose = (marqueur_neuman[glob] == 1 || N == 1) ? 0 : transpose_;
            if (glob<nb_som)
              for (int i2=0; i2<nb_som_elem; i2++)
                {
                  int glob2=elems(elem,i2);
                  double cb=0;
                  for (int b=0; b<dimension; b++)
                    cb+=bij(elem,i1,b)*bij(elem,i2,b);
                  for (int n = 0; n < N; n++)
                    {
                      matrice_coef(glob * N + n, glob2 * N + n) += cb * (diffu[elem]+diffu_turb[elem]) * pond;
                      if (transpose)
                        for (int d = 0; d < dimension; d++)
                          matrice_coef(glob * N + n, glob2 * N + d) += bij(elem, i1, d) * bij(elem, i2, n) * (diffu[elem]+diffu_turb[elem]) * pond;
                    }
                }
          }
      }
  if (N == 1) ajouter_contributions_bords(matrice);
}
References ajouter_contribution_new(), ajouter_contributions_bords(), Zone_EF::Bij(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Op_EF_base::elem_contribue(), MorEqn::equation(), Op_Diff_EF_base::la_zcl_EF, Zone::les_elems(), TRUSTVect< _TYPE_ >::line_size(), matrice_coef, Zone::nb_elem_tot(), Zone::nb_som(), Zone::nb_som_elem(), nouvelle_expression_, Op_Diff_EF_base::nu_, ref_cast, remplir_marqueur_elem_CL_paroi(), remplir_marqueur_sommet_neumann(), remplir_nu(), sub_type, transpose_, transpose_partout_, Ref_Zone_Cl_EF::valeur(), valeur(), Zone_VF::volumes(), Zone_EF::volumes_thilde(), and Zone_dis_base::zone().
Referenced by contribuer_a_avec().
ajouter_contribution_new()
void Op_Dift_EF_Q1::ajouter_contribution_new (const DoubleTab & transporte, Matrice_Morse & matrice) const
Definition at line 360 of file Op_Dift_EF_Q1.cpp.
{
// Cerr<<" NEW"<<finl;
// On remplit le tableau nu car l'assemblage d'une
// matrice avec ajouter_contribution peut se faire
// avant le premier pas de temps
  remplir_nu(nu_);
  DoubleVect diffu_turb(diffusivite_turbulente()->valeurs());
  DoubleTab diffu(nu_);
  const int N = transporte.line_size();
  const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
// const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
  const DoubleVect& volumes= zone_ef.volumes();
  const DoubleTab& bij=zone_ef.Bij();
  const DoubleTab& bij_thilde=zone_ef.Bij_thilde();
  int nb_elem_tot=zone_ef.zone().nb_elem_tot();
  int nb_som_elem=zone_ef.zone().nb_som_elem();
  const IntTab& elems=zone_ef.zone().les_elems() ;
  int nb_som=zone_ef.zone().nb_som();
  ArrOfInt marqueur_neuman;
  remplir_marqueur_sommet_neumann( marqueur_neuman,zone_ef,la_zcl_EF.valeur(),transpose_partout_ );
  ArrOfInt marqueur_paroi = 0;
  remplir_marqueur_elem_CL_paroi( marqueur_paroi,zone_ef,la_zcl_EF.valeur() );
  for (int elem=0; elem<nb_elem_tot; elem++)
    if (elem_contribue(elem)&&(!marqueur_paroi(elem)))
      {
        double pond=1./volumes(elem);
        for (int i1=0; i1<nb_som_elem; i1++)
          {
            int glob=elems(elem,i1);
            int transpose = (marqueur_neuman[glob] == 1 || N == 1) ? 0 : transpose_;
            if (glob<nb_som)
              for (int i2=0; i2<nb_som_elem; i2++)
                {
                  int glob2=elems(elem,i2);
                  double cb=0;
                  for (int b=0; b<dimension; b++)
                    cb+=bij(elem,i1,b)*bij_thilde(elem,i2,b);
                  for (int n = 0; n < N; n++)
                    {
                      matrice_coef(glob * N + n, glob2 * N + n) += cb * (diffu[elem]+diffu_turb[elem]) * pond;
                      if (transpose)
                        for (int d = 0; d < dimension; d++)
                          matrice_coef(glob * N + n, glob2 * N + d) += bij(elem, i1, d) * bij_thilde(elem, i2, n) * (diffu[elem]+diffu_turb[elem]) * pond;
                    }
                }
          }
      }
}
References Zone_EF::Bij(), Zone_EF::Bij_thilde(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Op_EF_base::elem_contribue(), MorEqn::equation(), Op_Diff_EF_base::la_zcl_EF, Zone::les_elems(), TRUSTVect< _TYPE_ >::line_size(), matrice_coef, Zone::nb_elem_tot(), Zone::nb_som(), Zone::nb_som_elem(), Op_Diff_EF_base::nu_, ref_cast, remplir_marqueur_elem_CL_paroi(), remplir_marqueur_sommet_neumann(), remplir_nu(), transpose_, transpose_partout_, Ref_Zone_Cl_EF::valeur(), valeur(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by ajouter_contribution().
ajouter_contributions_bords()
void Op_Dift_EF_Q1::ajouter_contributions_bords (Matrice_Morse & matrice) const
< 2 faces per elem max - 1D other face of the current elem
< first time we encounter one of the face of the pair
< we have already handled the opposite side of the wall
Definition at line 770 of file Op_Dift_EF_Q1.cpp.
{
  const Zone_Cl_EF& zone_Cl_EF = la_zcl_EF.valeur();
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
  const IntTab& face_sommets=zone_ef.face_sommets();
  int nb_som_face=zone_ef.nb_som_face();
  int N = equation().inconnue().valeurs().line_size();
  if (N > 1)
    {
// Cerr<<__PRETTY_FUNCTION__<<" non code pour les vecteurs"<<finl;
      throw;
      return;
    }
// Neumann :
  int n_bord;
  int nb_bords=zone_Cl_EF.nb_cond_lim();
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_EF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      if (sub_type(Echange_couplage_thermique, la_cl.valeur()))
        {
// matrice.imprimer(Cout);
          const Echange_couplage_thermique& la_cl_paroi = ref_cast(Echange_couplage_thermique, la_cl.valeur());
          for (int face=ndeb; face<nfin; face++)
            {
              double h=la_cl_paroi.h_imp(face-ndeb);
              double dphi_dT=la_cl_paroi.derivee_flux_exterieur_imposee(face-ndeb);
              double tm=1./(nb_som_face*nb_som_face);
              double flux=(dphi_dT+h)*zone_EF.surface(face)*tm;
              for (int i1=0; i1<nb_som_face; i1++)
                {
                  int glob2=face_sommets(face,i1);
                  for (int j1=0; j1<nb_som_face; j1++)
                    {
                      int glob1=face_sommets(face,j1);
                      matrice.coef(glob1,glob2) += flux;
                    }
                }
            }
// matrice.imprimer(Cout);exit();
        }
      else if (sub_type(Echange_interne_global_parfait, la_cl.valeur()))
        {
          const Echange_interne_global_parfait& la_cl_paroi = ref_cast(Echange_interne_global_parfait, la_cl.valeur());
          const Champ_front_calc_interne& Text = ref_cast(Champ_front_calc_interne, la_cl_paroi.T_ext().valeur());
          const IntTab& fmap = Text.face_map();
          std::vector<bool> hit(nfin-ndeb);
          std::fill(hit.begin(), hit.end(), false);
          for (int face=ndeb; face<nfin; face++)
            {
// face on the other side of the inner wall:
              int opp_face = fmap(face-ndeb)+ndeb;
// element attached to it
              int elem1 = zone_EF.face_voisins(opp_face, 0);
              int elem_opp = (elem1 != -1) ? elem1 : zone_EF.face_voisins(opp_face, 1);
// other face of the opposite element (i.e. face "after" opp_face)
              int f1 = zone_EF.elem_faces(elem_opp, 0);
              int face_plus_2 = f1 != opp_face ? f1 : zone_EF.elem_faces(elem_opp, 1);  //!< 2 faces per elem max - 1D other face of the current elem
//
              int elem = zone_EF.face_voisins(face, 0);
              f1 = zone_EF.elem_faces(elem, 0);
              int face_min_1 = f1 != face ? f1 : zone_EF.elem_faces(elem, 1);
              for (int i1=0; i1<nb_som_face; i1++)
                {
                  int som=face_sommets(face,i1);
                  int som_opp=face_sommets(opp_face,i1);
                  if (!hit[face-ndeb])  //!< first time we encounter one of the face of the pair
                    {
                      for (int j1=0; j1<nb_som_face; j1++)
{
// heat equation skipping duplicated face: -T(i-1) + 2*T(i) - T(i+2)
                          int som_p2=face_sommets(face_plus_2,j1);
                          matrice.coef(som,som_p2) -= matrice.coef(som_opp, som_opp);
                          matrice.coef(som, som) += matrice.coef(som_opp, som_opp);
                        }
                      hit[face-ndeb] = true;
                      hit[opp_face-ndeb] = true;
                    }
                  else   //!< we have already handled the opposite side of the wall
                    for (int j1=0; j1<nb_som_face; j1++)
                      {
// Dirichlet T(face) = T(opposite_face) and cancelling right term in the tri-band
                        int som_m1=face_sommets(face_min_1, j1);
                        matrice.coef(som,som_opp) = -matrice.coef(som,som);
                        matrice.coef(som,som_m1) = 0;
                      }
                }
            }
// matrice.imprimer(Cout);
        }
      else if (sub_type(Echange_interne_global_impose, la_cl.valeur()))
        {
          const Echange_interne_global_impose& la_cl_paroi = ref_cast(Echange_interne_global_impose, la_cl.valeur());
          const Champ_front_calc_interne& Text = ref_cast(Champ_front_calc_interne, la_cl_paroi.T_ext().valeur());
          const IntTab& fmap = Text.face_map();
          const DoubleVect& surface_gap = la_cl_paroi.surface_gap();
          for (int face=ndeb; face<nfin; face++)
            {
              double h=la_cl_paroi.h_imp(face-ndeb);
              double tm=1./(nb_som_face*nb_som_face);
// double flux=h*zone_EF.surface(face)*tm;
              double flux=h*surface_gap(face-ndeb)*tm;
              int opp_face = fmap(face-ndeb)+ndeb;
              for (int i1=0; i1<nb_som_face; i1++)
                {
                  int glob2=face_sommets(face,i1);
                  int glob3=face_sommets(opp_face,i1);
                  for (int j1=0; j1<nb_som_face; j1++)
                    {
                      int glob1=face_sommets(face,j1);
                      matrice.coef(glob1,glob2) += flux;
                      matrice.coef(glob1,glob3) -= flux;
                    }
                }
            }
// matrice.imprimer(Cout);
        }
      else if (sub_type(Echange_global_impose, la_cl.valeur()))
        {
// matrice.imprimer(Cout);
          const Echange_global_impose& la_cl_paroi = ref_cast(Echange_global_impose, la_cl.valeur());
          for (int face=ndeb; face<nfin; face++)
            {
              double h=la_cl_paroi.h_imp(face-ndeb);
              double tm=1./(nb_som_face*nb_som_face);
              double flux=h*zone_EF.surface(face)*tm;
              for (int i1=0; i1<nb_som_face; i1++)
                {
                  int glob2=face_sommets(face,i1);
                  for (int j1=0; j1<nb_som_face; j1++)
                    {
                      int glob1=face_sommets(face,j1);
                      matrice.coef(glob1,glob2) += flux;
                    }
                }
            }
        }
    }
}
References Matrice_Morse::coef(), Echange_global_impose::derivee_flux_exterieur_imposee(), Zone_VF::elem_faces(), MorEqn::equation(), f1, Champ_front_calc_interne::face_map(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Echange_impose_base::h_imp(), Equation_base::inconnue(), Op_Diff_EF_base::la_zcl_EF, Op_Diff_EF_base::la_zone_EF, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Zone_VF::nb_som_face(), Front_VF::num_premiere_face(), ref_cast, sub_type, Zone_VF::surface(), Echange_interne_global_impose::surface_gap(), Echange_impose_base::T_ext(), Ref_Zone_Cl_EF::valeur(), Ref_Zone_EF::valeur(), Deriv_Cond_lim_base::valeur(), valeur(), and Champ_Inc::valeurs().
Referenced by ajouter_contribution().
ajouter_new()
DoubleTab & Op_Dift_EF_Q1::ajouter_new (const DoubleTab & tab_inconnue, DoubleTab & resu) const
Definition at line 204 of file Op_Dift_EF_Q1.cpp.
{
  Cerr<<"NEW"<<finl;
  remplir_nu(nu_);
// const Zone_Cl_EF& zone_Cl_EF = la_zcl_EF.valeur();
// const Zone_EF& zone_EF = la_zone_EF.valeur();
  DoubleVect diffu_turb(diffusivite_turbulente()->valeurs());
  DoubleTab diffu(nu_);
  const int N = resu.line_size();
  ArrOfInt marqueur_neuman;
  ArrOfInt marqueur_paroi=0;
  const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
  if(N > 1)
    {
      remplir_marqueur_sommet_neumann( marqueur_neuman,zone_ef,la_zcl_EF.valeur(),transpose_partout_ );
      remplir_marqueur_elem_CL_paroi( marqueur_paroi,zone_ef,la_zcl_EF.valeur() );
    }
  const DoubleVect& volumes= zone_ef.volumes();
  const DoubleTab& bij=zone_ef.Bij();
  const DoubleTab& bij_thilde=zone_ef.Bij_thilde();
  int nb_elem_tot=zone_ef.zone().nb_elem_tot();
  int nb_som_elem=zone_ef.zone().nb_som_elem();
  const IntTab& elems=zone_ef.zone().les_elems() ;
  for (int elem=0; elem<nb_elem_tot; elem++)
    if (elem_contribue(elem)&&(!marqueur_paroi(elem)))
      {
        double pond=1./volumes(elem);
        assert(N == dimension || N == 1);
        for (int i1=0; i1<nb_som_elem; i1++)
          {
            int glob=elems(elem,i1);
            int transpose = (marqueur_neuman[glob] == 1 || N == 1) ? 0 : transpose_;
            for (int i2=0; i2<nb_som_elem; i2++)
              {
                int glob2=elems(elem,i2);
                for (int n = 0; n < N; n++)
                  for (int d = 0; d < dimension; d++)
                    resu(glob, n) -= bij(elem, i1, d) * (bij_thilde(elem, i2, d) * tab_inconnue(glob2, n) + transpose * bij_thilde(elem, i2, n) * tab_inconnue(glob2, d)) * (diffu[elem]+diffu_turb[elem]) * pond;
              }
          }
      }
// Debog::verifier(" Op_Dift_EF_Q1::ajouter, resu 0 ",resu);
// Journal()<<max(resu)<<" "<<min(resu)<<finl;
// on ajoute la contribution des bords
  ajouter_bords(tab_inconnue,resu);
  return resu;
}
References ajouter_bords(), Zone_EF::Bij(), Zone_EF::Bij_thilde(), Cerr, Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Op_EF_base::elem_contribue(), MorEqn::equation(), finl, Op_Diff_EF_base::la_zcl_EF, Zone::les_elems(), TRUSTVect< _TYPE_ >::line_size(), Zone::nb_elem_tot(), Zone::nb_som_elem(), Op_Diff_EF_base::nu_, ref_cast, remplir_marqueur_elem_CL_paroi(), remplir_marqueur_sommet_neumann(), remplir_nu(), transpose_, transpose_partout_, Ref_Zone_Cl_EF::valeur(), valeur(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_scalaire_dim2_nbn_4()
DoubleTab & Op_Dift_EF_Q1::ajouter_scalaire_dim2_nbn_4 (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Definition at line 189 of file Op_Dift_EF_Q1.cpp.
{
  return ajouter_scalaire_template<AJOUTE_SCAL::D2_4>(tab_inconnue, resu);
}
Referenced by ajouter().
ajouter_scalaire_dim3_nbn_8()
DoubleTab & Op_Dift_EF_Q1::ajouter_scalaire_dim3_nbn_8 (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Definition at line 184 of file Op_Dift_EF_Q1.cpp.
{
  return ajouter_scalaire_template<AJOUTE_SCAL::D3_8>(tab_inconnue, resu);
}
Referenced by ajouter().
ajouter_scalaire_gen()
DoubleTab & Op_Dift_EF_Q1::ajouter_scalaire_gen (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Definition at line 194 of file Op_Dift_EF_Q1.cpp.
{
  return ajouter_scalaire_template<AJOUTE_SCAL::GEN>(tab_inconnue, resu);
}
Referenced by ajouter().
ajouter_scalaire_template()
template<AJOUTE_SCAL _T_> DoubleTab & Op_Dift_EF_Q1::ajouter_scalaire_template (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Definition at line 94 of file Op_Dift_EF_Q1.h.
{
  static constexpr bool IS_GEN = (_T_ == AJOUTE_SCAL::GEN), IS_D3_8 = (_T_ == AJOUTE_SCAL::D3_8), IS_D2_4 = (_T_ == AJOUTE_SCAL::D2_4);
  const Zone_EF& zone_ef = ref_cast(Zone_EF, equation().zone_dis().valeur());
  const int N = IS_GEN ? resu.line_size() : 1;
  const int nb_som_elem = IS_D3_8 ? 8 : ( IS_D2_4 ? 4 : zone_ef.zone().nb_som_elem() /* IS_GEN */);
  const int const_dimension = IS_D3_8 ? 3 : ( IS_D2_4 ? 2 : Objet_U::dimension /* IS_GEN */);
  const int dim_fois_nbn = nb_som_elem * const_dimension;
  const DoubleVect& volumes_thilde = zone_ef.volumes_thilde(), &volumes = zone_ef.volumes();
  const DoubleTab& bij = zone_ef.Bij();
  int nb_elem_tot = zone_ef.zone().nb_elem_tot();
  const IntTab& elems = zone_ef.zone().les_elems();
  remplir_nu(nu_);
  DoubleVect diffu_turb(diffusivite_turbulente()->valeurs());
  DoubleTab diffu(nu_);
  const double *bij_ptr = bij.addr();
  const double *inco_ptr = tab_inconnue.addr();
#define bij_(elem,i,j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define inconnue_(som,a) inco_ptr[som * N + a]
#define resu_(som,a) resu_ptr[som * N + a]
  ArrOfDouble pr(N);
  for (int elem = 0; elem < nb_elem_tot; elem++)
    if (elem_contribue(elem))
      {
        double pond = volumes_thilde(elem) / volumes(elem) / volumes(elem) * (diffu[elem] + diffu_turb[elem]);
        for (int i1 = 0; i1 < nb_som_elem; i1++)
          {
            int glob = elems(elem, i1);
            for (int yy = 0; yy < N; yy++) pr[yy] = 0;
            for (int i2 = 0; i2 < nb_som_elem; i2++)
              {
                int glob2 = elems(elem, i2);
                {
                  double prod = 0;
                  for (int b = 0; b < const_dimension; b++)
                    {
                      prod += bij_(elem,i1,b)*bij_(elem,i2,b);
                    }
                  for (int n = 0; n < N; n++) pr[n] += prod * inconnue_(glob2, n);
                }
              }
            resu(glob) -= pr[0] * pond;
          }
      }
// on ajoute la contribution des bords
  ajouter_bords(tab_inconnue, resu);
  return resu;
#undef bij_
#undef inconnue_
#undef resu_
}
References TRUSTArray< _TYPE_ >::addr(), ajouter_bords(), Zone_EF::Bij(), bij_, D2_4, D3_8, Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Op_EF_base::elem_contribue(), MorEqn::equation(), GEN, inconnue_, Zone::les_elems(), TRUSTVect< _TYPE_ >::line_size(), Zone::nb_elem_tot(), Zone::nb_som_elem(), Op_Diff_EF_base::nu_, prod(), ref_cast, remplir_nu(), valeur(), Zone_VF::volumes(), Zone_EF::volumes_thilde(), and Zone_dis_base::zone().
ajouter_vectoriel_dim2_nbn_4()
DoubleTab & Op_Dift_EF_Q1::ajouter_vectoriel_dim2_nbn_4 (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Definition at line 179 of file Op_Dift_EF_Q1.cpp.
{
  return ajouter_vectoriel_template<AJOUTE_VECT::D2_4>(tab_inconnue,resu);
}
Referenced by ajouter().
ajouter_vectoriel_dim3_nbn_8()
DoubleTab & Op_Dift_EF_Q1::ajouter_vectoriel_dim3_nbn_8 (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Definition at line 174 of file Op_Dift_EF_Q1.cpp.
{
  return ajouter_vectoriel_template<AJOUTE_VECT::D3_8>(tab_inconnue,resu);
}
Referenced by ajouter().
ajouter_vectoriel_gen()
DoubleTab & Op_Dift_EF_Q1::ajouter_vectoriel_gen (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Definition at line 199 of file Op_Dift_EF_Q1.cpp.
{
  return ajouter_vectoriel_template<AJOUTE_VECT::GEN>(tab_inconnue,resu);
}
Referenced by ajouter().
ajouter_vectoriel_template()
template<AJOUTE_VECT _T_> DoubleTab & Op_Dift_EF_Q1::ajouter_vectoriel_template (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Definition at line 160 of file Op_Dift_EF_Q1.h.
{
  static constexpr bool IS_GEN = (_T_ == AJOUTE_VECT::GEN), IS_D3_8 = (_T_ == AJOUTE_VECT::D3_8), IS_D2_4 = (_T_ == AJOUTE_VECT::D2_4);
  const Zone_EF& zone_ef = ref_cast(Zone_EF, equation().zone_dis().valeur());
  const int N = IS_D3_8 ? 3 : (IS_D2_4 ? 2 : resu.line_size() /* IS_GEN */);
  const int const_dimension = IS_GEN ? Objet_U::dimension : N;
  const int nb_som_elem = IS_D3_8 ? 8 : (IS_D2_4 ? 4 : zone_ef.zone().nb_som_elem() /* IS_GEN */);
  const int dim_fois_nbn = nb_som_elem * const_dimension;
  ArrOfInt marqueur_neuman;
  remplir_marqueur_sommet_neumann(marqueur_neuman, zone_ef, la_zcl_EF.valeur(), transpose_partout_);
  ArrOfInt marqueur_paroi;
  remplir_marqueur_elem_CL_paroi(marqueur_paroi, zone_ef, la_zcl_EF.valeur());
  const DoubleVect& volumes_thilde = zone_ef.volumes_thilde(), &volumes = zone_ef.volumes();
  const DoubleTab& bij = zone_ef.Bij();
  int nb_elem_tot = zone_ef.zone().nb_elem_tot();
  const IntTab& elems = zone_ef.zone().les_elems();
  remplir_nu(nu_);
  DoubleVect diffu_turb(diffusivite_turbulente()->valeurs());
  DoubleTab diffu(nu_);
  const double *bij_ptr = bij.addr();
  const double *inco_ptr = tab_inconnue.addr();
  double *resu_ptr = resu.addr();
#define bij_(elem,i,j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define inconnue_(som,a) inco_ptr[som * N + a]
#define resu_(som,a) resu_ptr[som * N + a]
  ArrOfDouble pr(N);
  for (int elem = 0; elem < nb_elem_tot; elem++)
    if (elem_contribue(elem))
      {
        double pond = volumes_thilde(elem) / volumes(elem) / volumes(elem) * (diffu[elem] + diffu_turb[elem]);
        for (int i1 = 0; i1 < nb_som_elem; i1++)
          {
            int glob = elems(elem, i1);
            for (int yy = 0; yy < N; yy++)
              pr[yy] = 0;
            int transpose = (marqueur_neuman[glob] == 1 || N == 1) ? 0 : transpose_;
            for (int i2 = 0; i2 < nb_som_elem; i2++)
              {
                int glob2 = elems(elem, i2);
                {
                  double prod = 0;
                  double prod2 = 0;
                  for (int b = 0; b < const_dimension; b++)
                    {
                      prod += bij_(elem,i1,b)*bij_(elem,i2,b);
                      if (transpose)
                        prod2+=bij_(elem,i1,b)*inconnue_(glob2,b);
                    }
                  for (int n = 0; n < N; n++) pr[n] += prod * inconnue_(glob2, n) + prod2 * bij_(elem, i2, n);
                }
              }
            for (int n = 0; n < N; n++) resu_(glob, n)-= pr[n] * pond;
          }
      }
// on ajoute la contribution des bords
  ajouter_bords(tab_inconnue, resu);
  return resu;
#undef bij_
#undef inconnue_
#undef resu_
}
References TRUSTArray< _TYPE_ >::addr(), ajouter_bords(), Zone_EF::Bij(), bij_, D2_4, D3_8, Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Op_EF_base::elem_contribue(), MorEqn::equation(), GEN, inconnue_, Op_Diff_EF_base::la_zcl_EF, Zone::les_elems(), TRUSTVect< _TYPE_ >::line_size(), Zone::nb_elem_tot(), Zone::nb_som_elem(), Op_Diff_EF_base::nu_, prod(), ref_cast, remplir_marqueur_elem_CL_paroi(), remplir_marqueur_sommet_neumann(), remplir_nu(), resu_, transpose_, transpose_partout_, Ref_Zone_Cl_EF::valeur(), valeur(), Zone_VF::volumes(), Zone_EF::volumes_thilde(), and Zone_dis_base::zone().
associer_diffusivite()
void Op_Dift_EF_Q1::associer_diffusivite (const Champ_base & diffu) override virtual
associe le champ de diffusivite
Implements Operateur_Diff_base.
Definition at line 90 of file Op_Dift_EF_Q1.cpp.
{
  diffusivite_ = diffu;
}
References diffusivite_.
calculer()
DoubleTab & Op_Dift_EF_Q1::calculer (const DoubleTab & tab_inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 260 of file Op_Dift_EF_Q1.cpp.
{
  resu = 0;
  return ajouter(tab_inconnue,resu);
}
References ajouter().
calculer_dt_stab()
double Op_Dift_EF_Q1::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
double
Signification: renvoie toujours 1.e30
Contraintes:
< PQ : 06/03
< PQ : 06/03
Reimplemented from Op_Diff_EF_base.
Definition at line 936 of file Op_Dift_EF_Q1.cpp.
{
// 12/04: Premiers efforts d'optimisation du code a tenir
// compte lors de la factorisation des pas de temps de stabilite
// Calcul de dt_stab
// La diffusivite est constante par elements donc
// il faut calculer dt_diff pour chaque element et
// dt_stab=Min(dt_diff (K) = h(K)*h(K)/(2*dimension*diffu2_(K)))
// ou diffu2_ est la somme des 2 diffusivite laminaire et turbulente
// GF
// alpha_dt_stab=(alpha+alpha_t)*alpha_dt_stab/alpha
// alpha_dt_stab=(nu+diff_nu_turb)*valeurs_diffusivite_dt/nu
// On remplit le tableau nu contenant la diffusivite en chaque elem
  remplir_nu(nu_);
  double dt_stab=1.e30;
  double coef;
  const Zone_EF& ma_zone_EF = la_zone_EF.valeur();
  const Zone& ma_zone= ma_zone_EF.zone();
  DoubleVect diffu_turb(diffusivite_turbulente()->valeurs());
  DoubleTab diffu(nu_);
  if (equation().que_suis_je().debute_par("Convection_Diffusion_Temp"))
    {
      double rhocp = mon_equation->milieu().capacite_calorifique().valeurs()(0, 0) * mon_equation->milieu().masse_volumique().valeurs()(0, 0);
      diffu_turb /= rhocp;
      diffu /= rhocp;
    }
  double alpha;
  int ma_zone_nb_elem=ma_zone.nb_elem();
  if (has_champ_masse_volumique())
    {
      const DoubleTab& rho_elem = get_champ_masse_volumique().valeurs();
      assert(rho_elem.size_array()==ma_zone_EF.nb_elem_tot());
      for (int num_elem=0; num_elem<ma_zone_nb_elem; num_elem++)
        {
          alpha = diffu[num_elem] + diffu_turb[num_elem]; //!< PQ : 06/03
          alpha/=rho_elem[num_elem];
// dt=1/(dimension/(pas*pas))/(2*alpha)
          coef=ma_zone_EF.carre_pas_maille(num_elem)/(2.*dimension*(alpha+DMINFLOAT));
// dt_stab=min(dt);
          if (coef<dt_stab) dt_stab = coef;
        }
    }
  else
    {
      const Champ_base& champ_diffusivite = diffusivite_pour_pas_de_temps();
      const DoubleTab&      valeurs_diffusivite = champ_diffusivite.valeurs();
      double valeurs_diffusivite_dt=-1;
      int unif_diffu_dt;
      const Nature_du_champ nature_champ = equation().inconnue()->nature_du_champ();
      if (sub_type(Champ_Uniforme,champ_diffusivite))
        {
          valeurs_diffusivite_dt=valeurs_diffusivite(0,0);
          unif_diffu_dt=1;
        }
      else
        unif_diffu_dt=0;
      if (nature_champ!=multi_scalaire)
        {
          int nb_dim = valeurs_diffusivite.nb_dim();
          for (int num_elem=0; num_elem<ma_zone_nb_elem; num_elem++)
            {
              alpha =  diffu[num_elem] + diffu_turb[num_elem]; //!< PQ : 06/03
              if(unif_diffu_dt==0)
                valeurs_diffusivite_dt=(nb_dim==1?valeurs_diffusivite(num_elem):valeurs_diffusivite(num_elem,0));
              alpha*=valeurs_diffusivite_dt/(diffu[num_elem]+DMINFLOAT);
// dt=1/(dimension/(pas*pas))/(2*alpha)
              coef=ma_zone_EF.carre_pas_maille(num_elem)/(2.*dimension*(alpha+DMINFLOAT));
              assert(coef>=0);
// dt_stab=min(dt);
              if (coef<dt_stab) dt_stab = coef;
            }
        }
      else
        {
          int nb_comp = valeurs_diffusivite.dimension(1);
          for (int nc=0; nc<nb_comp; nc++)
            {
              for (int num_elem=0; num_elem<ma_zone_nb_elem; num_elem++)
                {
                  alpha =  diffu(num_elem,nc) + diffu_turb[num_elem];
// if(unif_diffu_dt==0)
                  valeurs_diffusivite_dt=valeurs_diffusivite(0,nc);
                  alpha*=valeurs_diffusivite_dt/(diffu(num_elem,nc)+DMINFLOAT);
                  coef=ma_zone_EF.carre_pas_maille(num_elem)/(2.*dimension*(alpha+DMINFLOAT));
                  if (coef<dt_stab) dt_stab = coef;
                }
            }
        }
    }
  dt_stab = Process::mp_min(dt_stab);
  return dt_stab;
}
References Milieu_base::capacite_calorifique(), Zone_EF::carre_pas_maille(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Op_Diff_Turbulent_base::diffusivite_turbulente(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, DMINFLOAT, MorEqn::equation(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Equation_base::inconnue(), Op_Diff_EF_base::la_zone_EF, Milieu_base::masse_volumique(), Equation_base::milieu(), MorEqn::mon_equation, Process::mp_min(), multi_scalaire, TRUSTTab< _TYPE_ >::nb_dim(), Zone::nb_elem(), Zone_dis_base::nb_elem_tot(), Op_Diff_EF_base::nu_, Objet_U::que_suis_je(), remplir_nu(), TRUSTArray< _TYPE_ >::size_array(), sub_type, Ref_Zone_EF::valeur(), Champ::valeurs(), Champ_Don::valeurs(), Champ_Proto::valeurs(), and Zone_dis_base::zone().
calculer_pour_post()
void Op_Dift_EF_Q1::calculer_pour_post (Champ & espace_stockage, const Nom & option, int comp) const override virtual
Reimplemented from MorEqn.
Definition at line 932 of file Op_Dift_EF_Q1.cpp.
{
}
contribuer_a_avec()
void Op_Dift_EF_Q1::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 57 of file Op_Dift_EF_Q1.h.
{ ajouter_contribution(inco, matrice); }
References ajouter_contribution().
contribuer_au_second_membre()
void Op_Dift_EF_Q1::contribuer_au_second_membre (DoubleTab &) const override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 419 of file Op_Dift_EF_Q1.cpp.
{
  if ((equation().nombre_d_operateurs()>1)&&sub_type(Op_Conv_EF,equation().operateur(1).l_op_base()))
    ref_cast(Op_Conv_EF,equation().operateur(1).l_op_base()).contribue_au_second_membre_a_la_diffusion(resu);
  const DoubleTab& tab_inconnue=equation().inconnue().valeurs();
  ajouter_bords(tab_inconnue,resu,0);
}
References ajouter_bords(), MorEqn::equation(), Equation_base::inconnue(), ref_cast, sub_type, and Champ_Inc::valeurs().
cree_instance()
Objet_U * Op_Dift_EF_Q1::cree_instance () static
Definition at line 36 of file Op_Dift_EF_Q1.cpp.
diffusivite() [1/2]
const Champ_base & Op_Dift_EF_Q1::diffusivite () const inline override virtual
Implements Operateur_Diff_base.
Definition at line 39 of file Op_Dift_EF_Q1.h.
{ return diffusivite_; }
References diffusivite_.
Referenced by diffusivite(), and remplir_nu().
diffusivite() [2/2]
double Op_Dift_EF_Q1::diffusivite (int) const inline
Definition at line 40 of file Op_Dift_EF_Q1.h.
  {
    return (diffusivite().valeurs().nb_dim() == 1) ? (diffusivite().valeurs())(0) : (diffusivite().valeurs())(0, 0);
  }
References diffusivite(), and Champ_Proto::valeurs().
dimensionner()
void Op_Dift_EF_Q1::dimensionner (Matrice_Morse & mat) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 55 of file Op_Dift_EF_Q1.h.
{ Op_EF_base::dimensionner(la_zone_EF.valeur(), la_zcl_EF.valeur(), matrice); }
References Op_EF_base::dimensionner(), Op_Diff_EF_base::la_zcl_EF, Op_Diff_EF_base::la_zone_EF, Ref_Zone_Cl_EF::valeur(), and Ref_Zone_EF::valeur().
duplique()
int Op_Dift_EF_Q1::duplique () const override virtual
Implements Objet_U.
Reimplemented in Op_Dift_EF_Q1_option.
Definition at line 36 of file Op_Dift_EF_Q1.cpp.
get_info()
const Type_info * Op_Dift_EF_Q1::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Dift_EF_base.
Reimplemented in Op_Dift_EF_Q1_option.
Definition at line 36 of file Op_Dift_EF_Q1.cpp.
info()
const Type_info * Op_Dift_EF_Q1::info () static
Definition at line 36 of file Op_Dift_EF_Q1.cpp.
modifier_pour_Cl()
void Op_Dift_EF_Q1::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 56 of file Op_Dift_EF_Q1.h.
{ Op_EF_base::modifier_pour_Cl(la_zone_EF.valeur(),la_zcl_EF.valeur(), matrice, secmem); }
References Op_Diff_EF_base::la_zcl_EF, Op_Diff_EF_base::la_zone_EF, Op_EF_base::modifier_pour_Cl(), Ref_Zone_Cl_EF::valeur(), and Ref_Zone_EF::valeur().
printOn()
Sortie & Op_Dift_EF_Q1::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Op_Dift_EF_base.
Reimplemented in Op_Dift_EF_Q1_option.
Definition at line 40 of file Op_Dift_EF_Q1.cpp.
{ return s << que_suis_je() ; }
References Objet_U::que_suis_je().
readOn()
Entree & Op_Dift_EF_Q1::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Op_Dift_EF_base.
Reimplemented in Op_Dift_EF_Q1_option.
Definition at line 42 of file Op_Dift_EF_Q1.cpp.
{ return s ; }
remplir_marqueur_elem_CL_paroi()
void Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi (ArrOfInt & marqueur, const Zone_EF & zone_EF, const Zone_Cl_EF & zone_Cl_EF) const
Definition at line 62 of file Op_Dift_EF_Q1.cpp.
{
  const IntTab& face_voisins=zone_EF.face_voisins();
  marqueur.resize_array(zone_EF.nb_elem_tot());
  if (!(le_modele_turbulence.valeur().utiliser_loi_paroi())) return;
  int nb_bords=zone_EF.nb_front_Cl();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_EF.les_conditions_limites(n_bord);
// Paroi fixe, Paroi defilante :
      if (sub_type(Dirichlet_paroi_fixe,la_cl.valeur()) ||
          sub_type(Dirichlet_paroi_defilante,la_cl.valeur()) )
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int nfin =le_bord.nb_faces_tot();
          for (int ind_face=0; ind_face<nfin; ind_face++)
            {
              int face=le_bord.num_face(ind_face);
              int elem=face_voisins(face,0);
              marqueur(elem)=1;
            }
        }
    }
}
References Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Op_Dift_EF_base::le_modele_turbulence, Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), ref_cast, TRUSTArray< _TYPE_ >::resize_array(), sub_type, Mod_turb_hyd_base::utiliser_loi_paroi(), Deriv_Cond_lim_base::valeur(), and Ref_Mod_turb_hyd_base::valeur().
Referenced by ajouter_contribution(), ajouter_contribution_new(), ajouter_new(), and ajouter_vectoriel_template().
remplir_nu()
void Op_Dift_EF_Q1::remplir_nu (DoubleTab & nu) const override virtual
Implements Op_Diff_EF_base.
Definition at line 95 of file Op_Dift_EF_Q1.cpp.
{
  const Zone_EF& zone_EF = la_zone_EF.valeur();
// On dimensionne nu
  if (!nu.get_md_vector().non_nul())
    zone_EF.zone().creer_tableau_elements(nu);
  const DoubleTab& diffu=diffusivite().valeurs();
  if (diffu.size()==1)
    nu = diffu(0,0);
  else if (diffu.nb_dim()==1)
    nu = diffu;
  else
    {
      assert(diffu.dimension(1)==1);
      for (int i=0; i<diffu.size_totale(); i++) nu(i)=diffu(i,0);
    }
// nu.echange_espace_virtuel();
}
References Zone::creer_tableau_elements(), diffusivite(), TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::get_md_vector(), Op_Diff_EF_base::la_zone_EF, TRUSTTab< _TYPE_ >::nb_dim(), MD_Vector::non_nul(), TRUSTVect< _TYPE_ >::size(), TRUSTVect< _TYPE_ >::size_totale(), Ref_Zone_EF::valeur(), Champ_Proto::valeurs(), and Zone_dis_base::zone().
Referenced by ajouter(), ajouter_contribution(), ajouter_contribution_new(), ajouter_new(), ajouter_scalaire_template(), ajouter_vectoriel_template(), and calculer_dt_stab().
self_cast() [1/2]
const Op_Dift_EF_Q1 & Op_Dift_EF_Q1::self_cast (const Objet_U & r) static
Definition at line 36 of file Op_Dift_EF_Q1.cpp.
self_cast() [2/2]
Op_Dift_EF_Q1 & Op_Dift_EF_Q1::self_cast (Objet_U & r) static
Definition at line 36 of file Op_Dift_EF_Q1.cpp.
taille_memoire()
unsigned Op_Dift_EF_Q1::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Op_Dift_EF_Q1_option.
Definition at line 36 of file Op_Dift_EF_Q1.cpp.
verifier()
void Op_Dift_EF_Q1::verifier () const
Definition at line 924 of file Op_Dift_EF_Q1.cpp.
{
  static int testee=0;
  if(testee)
    return;
  testee=1;
}
Member Data Documentation
diffusivite_
Ref_Champ_base Op_Dift_EF_Q1::diffusivite_ protected
Definition at line 71 of file Op_Dift_EF_Q1.h.
Referenced by associer_diffusivite(), and diffusivite().
info_obj
const Type_info Op_Dift_EF_Q1::info_obj static
Definition at line 35 of file Op_Dift_EF_Q1.h.
nouvelle_expression_
int Op_Dift_EF_Q1::nouvelle_expression_ protected
Definition at line 70 of file Op_Dift_EF_Q1.h.
Referenced by ajouter(), ajouter_contribution(), and Op_Dift_EF_Q1_option::readOn().
transpose_
int Op_Dift_EF_Q1::transpose_ protected
vaurt zero si on ne veut pas calculer grad u transpose
Definition at line 68 of file Op_Dift_EF_Q1.h.
Referenced by ajouter_contribution(), ajouter_contribution_new(), ajouter_new(), ajouter_vectoriel_template(), and Op_Dift_EF_Q1_option::readOn().
transpose_partout_
int Op_Dift_EF_Q1::transpose_partout_ protected
vaut 1 si on veut calculer grad_u_transpose meme au bord
Definition at line 69 of file Op_Dift_EF_Q1.h.
Referenced by ajouter_contribution(), ajouter_contribution_new(), ajouter_new(), ajouter_vectoriel_template(), and Op_Dift_EF_Q1_option::readOn().
The documentation for this class was generated from the following files:
src/EF/Operateurs/Op_Dift_EF_Q1.h
src/EF/Operateurs/Op_Dift_EF_Q1.cpp