TRUST: Dirichlet_paroi_defilante Class Reference
Dirichlet_paroi_defilante Class Reference
classe Dirichlet_paroi_defilante
Impose la vitesse de paroi dnas une equation de type Navier_Stokes.
#include <Dirichlet_paroi_defilante.h>
Public Member Functions
Dirichlet_paroi_defilante ()
~Dirichlet_paroi_defilante ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int compatible_avec_eqn (const Equation_base &) const
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Dirichlet_paroi_defilante sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Dirichlet_paroi_defilante & self_cast (Objet_U &)
static const
Dirichlet_paroi_defilante & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a: Cond_lim_base::readOn(Entree&)
Detailed Description
classe Dirichlet_paroi_defilante
Impose la vitesse de paroi dnas une equation de type Navier_Stokes.
Definition at line 41 of file Dirichlet_paroi_defilante.h.
Constructor & Destructor Documentation
Dirichlet_paroi_defilante::Dirichlet_paroi_defilante ()
Definition at line 27 of file Dirichlet_paroi_defilante.cpp.
Dirichlet_paroi_defilante::~Dirichlet_paroi_defilante ()
Definition at line 27 of file Dirichlet_paroi_defilante.cpp.
Member Function Documentation
int Dirichlet_paroi_defilante::compatible_avec_eqn (const Equation_base & eqn) const [virtual]
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Dirichlet_paroi_defilante sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
Returns:
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Implements Cond_lim_base.
Reimplemented in Paroi_Knudsen_non_negligeable.
Definition at line 92 of file Dirichlet_paroi_defilante.cpp.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Hydraulique="Hydraulique";
  Motcle indetermine="indetermine";
  if ( (dom_app==Hydraulique) || (dom_app==indetermine) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
void Dirichlet_paroi_defilante::completer (void) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Cond_lim_base.
Reimplemented in Paroi_Knudsen_non_negligeable.
Definition at line 68 of file Dirichlet_paroi_defilante.cpp.
{
}
Objet_U * Dirichlet_paroi_defilante::cree_instance () [static]
Reimplemented in Paroi_Knudsen_non_negligeable.
Definition at line 27 of file Dirichlet_paroi_defilante.cpp.
int Dirichlet_paroi_defilante::duplique () const [virtual]
Implements Dirichlet.
Reimplemented in Paroi_Knudsen_non_negligeable.
Definition at line 27 of file Dirichlet_paroi_defilante.cpp.
const Type_info * Dirichlet_paroi_defilante::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Dirichlet.
Reimplemented in Paroi_Knudsen_non_negligeable.
Definition at line 27 of file Dirichlet_paroi_defilante.cpp.
const Type_info * Dirichlet_paroi_defilante::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Dirichlet.
Reimplemented in Paroi_Knudsen_non_negligeable.
Definition at line 27 of file Dirichlet_paroi_defilante.cpp.
Sortie & Dirichlet_paroi_defilante::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Dirichlet.
Reimplemented in Paroi_Knudsen_non_negligeable.
Definition at line 44 of file Dirichlet_paroi_defilante.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Dirichlet_paroi_defilante::readOn (Entree & s) [protected, virtual]
Simple appel a: Cond_lim_base::readOn(Entree&)
Returns:
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Dirichlet.
Reimplemented in Paroi_Knudsen_non_negligeable.
Definition at line 63 of file Dirichlet_paroi_defilante.cpp.
{
  return Cond_lim_base::readOn(s);
}
const Dirichlet_paroi_defilante & Dirichlet_paroi_defilante::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Dirichlet.
Reimplemented in Paroi_Knudsen_non_negligeable.
Definition at line 27 of file Dirichlet_paroi_defilante.cpp.
Dirichlet_paroi_defilante & Dirichlet_paroi_defilante::self_cast (Objet_U & r) [static]
Reimplemented from Dirichlet.
Reimplemented in Paroi_Knudsen_non_negligeable.
Definition at line 27 of file Dirichlet_paroi_defilante.cpp.
unsigned Dirichlet_paroi_defilante::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Paroi_Knudsen_non_negligeable.
Definition at line 27 of file Dirichlet_paroi_defilante.cpp.
Member Data Documentation
const Type_info Dirichlet_paroi_defilante::info_obj [static]
Reimplemented from Dirichlet.
Reimplemented in Paroi_Knudsen_non_negligeable.
Definition at line 44 of file Dirichlet_paroi_defilante.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Cond_Lim/Dirichlet_paroi_defilante.h
src/ThHyd/Incompressible/Cond_Lim/Dirichlet_paroi_defilante.cpp