TRUST: Ref_Zone_VEF Class Reference
Ref_Zone_VEF Class Reference
#include <Ref_Zone_VEF.h>
Public Member Functions
~Ref_Zone_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Ref_Zone_VEF ()
Ref_Zone_VEF (const Zone_VEF &)
Ref_Zone_VEF (const Ref_Zone_VEF &)
const Zone_VEF & valeur () const
Zone_VEF & valeur ()
const Zone_VEF * operator-> () const
Zone_VEF * operator-> ()
const Ref_Zone_VEF & operator= (const Zone_VEF &)
const Ref_Zone_VEF & operator= (const Ref_Zone_VEF &)
operator const Zone_VEF & () const
operator Zone_VEF & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Ref_
Ref_ ()
~Ref_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void reset ()
Annule la ref.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Ref_Zone_VEF & self_cast (Objet_U &)
static const Ref_Zone_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Ref_
static const Type_info * info ()
static Ref_ & self_cast (Objet_U &)
static const Ref_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Ref_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'Objet_U reference sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Sortie & printOn (Sortie &x) const override
Ecriture de l'Objet_U reference sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Zone_VEF * pointeur_
Detailed Description
Definition at line 21 of file Ref_Zone_VEF.h.
Constructor & Destructor Documentation
~Ref_Zone_VEF()
Ref_Zone_VEF::~Ref_Zone_VEF ()
Definition at line 18 of file Ref_Zone_VEF.cpp.
Ref_Zone_VEF() [1/3]
Ref_Zone_VEF::Ref_Zone_VEF ()
Definition at line 18 of file Ref_Zone_VEF.cpp.
Ref_Zone_VEF() [2/3]
Ref_Zone_VEF::Ref_Zone_VEF (const Zone_VEF & t)
Definition at line 18 of file Ref_Zone_VEF.cpp.
Ref_Zone_VEF() [3/3]
Ref_Zone_VEF::Ref_Zone_VEF (const Ref_Zone_VEF & t)
Definition at line 18 of file Ref_Zone_VEF.cpp.
Member Function Documentation
cree_instance()
Objet_U * Ref_Zone_VEF::cree_instance () static
Definition at line 18 of file Ref_Zone_VEF.cpp.
duplique()
int Ref_Zone_VEF::duplique () const override virtual
Implements Objet_U.
Definition at line 18 of file Ref_Zone_VEF.cpp.
get_info()
const Type_info * Ref_Zone_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 18 of file Ref_Zone_VEF.cpp.
get_info_ptr()
const Type_info & Ref_Zone_VEF::get_info_ptr () const override virtual
Implements O_U_Ptr.
Definition at line 18 of file Ref_Zone_VEF.cpp.
info()
const Type_info * Ref_Zone_VEF::info () static
Definition at line 18 of file Ref_Zone_VEF.cpp.
operator const Zone_VEF &()
Ref_Zone_VEF::operator const Zone_VEF & () const
Definition at line 18 of file Ref_Zone_VEF.cpp.
operator Zone_VEF &()
Ref_Zone_VEF::operator Zone_VEF & ()
Definition at line 18 of file Ref_Zone_VEF.cpp.
operator->() [1/2]
Zone_VEF * Ref_Zone_VEF::operator-> () inline
Definition at line 21 of file Ref_Zone_VEF.h.
operator->() [2/2]
const Zone_VEF * Ref_Zone_VEF::operator-> () const inline
Definition at line 21 of file Ref_Zone_VEF.h.
operator=() [1/2]
const Ref_Zone_VEF & Ref_Zone_VEF::operator= (const Ref_Zone_VEF & t)
Definition at line 18 of file Ref_Zone_VEF.cpp.
operator=() [2/2]
const Ref_Zone_VEF & Ref_Zone_VEF::operator= (const Zone_VEF & t)
Definition at line 18 of file Ref_Zone_VEF.cpp.
printOn()
Sortie & Ref_Zone_VEF::printOn (Sortie & os) const override protected virtual
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 18 of file Ref_Zone_VEF.cpp.
readOn()
Entree & Ref_Zone_VEF::readOn (Entree & is) override protected virtual
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 18 of file Ref_Zone_VEF.cpp.
self_cast() [1/2]
const Ref_Zone_VEF & Ref_Zone_VEF::self_cast (const Objet_U & r) static
Definition at line 18 of file Ref_Zone_VEF.cpp.
self_cast() [2/2]
Ref_Zone_VEF & Ref_Zone_VEF::self_cast (Objet_U & r) static
Definition at line 18 of file Ref_Zone_VEF.cpp.
set_O_U_Ptr()
void Ref_Zone_VEF::set_O_U_Ptr (Objet_U * ptr) override protected virtual
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 18 of file Ref_Zone_VEF.cpp.
taille_memoire()
unsigned Ref_Zone_VEF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 18 of file Ref_Zone_VEF.cpp.
valeur() [1/2]
Zone_VEF & Ref_Zone_VEF::valeur () inline
Definition at line 21 of file Ref_Zone_VEF.h.
valeur() [2/2]
const Zone_VEF & Ref_Zone_VEF::valeur () const inline
Definition at line 21 of file Ref_Zone_VEF.h.
Referenced by Champ_P1NC::affecter_(), Op_Dift_Stab_VEF_Face::aij_extradiag(), Op_Curl_VEFP1B::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_VEF_P1B_Face::ajouter(), Op_Rot_VEFP1B::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_standard_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Perte_Charge_Singuliere_VEF_Face::ajouter(), Perte_Charge_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Terme_Source_Decroissance_Radioactive_VEF_Face::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion_vectoriel(), Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Dift_Stab_VEF_Face::ajouter_cas_multiscalaire(), Op_Dift_Stab_VEF_Face::ajouter_cas_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Conv_Muscl_New_VEF_Face::ajouter_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_diffusion(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Op_Dift_Stab_VEF_Face::ajouter_diffusion(), Op_Dift_Stab_VEF_Face::ajouter_diffusion_vectoriel(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_operateur_centre(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Op_Dift_Stab_VEF_Face::ajouter_operateur_centre(), Op_Dift_Stab_VEF_Face::ajouter_operateur_centre_vectoriel(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Masse_VEF_P1NC::appliquer_impl(), Eval_Darcy_VEF_Face::associer(), Op_Conv_Centre_old_VEF_Face::associer(), Op_Conv_VEF_base::associer(), Op_Diff_VEF_base::associer(), Champ_Q1NC::cal_rot_ordre1(), Champ_P1NC::cal_rot_ordre1(), Champ_P1NC::calcul_critere_Q(), Champ_P1NC::calcul_grad_T(), Champ_P1NC::calcul_grad_U(), Champ_P1NC::calcul_h_conv(), Champ_P1NC::calcul_y_plus(), Op_Dift_VEF_base::calculer_borne_locale(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Dift_Stab_VEF_Face::calculer_coefficients(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Op_Conv_EF_VEF_P1NC_Stab::calculer_data_pour_dirichlet(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Champ_Ostwald_VEF::calculer_dscald(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VEF_Face_Q1::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Dift_VEF_Face_Q1::calculer_dt_stab(), Op_Conv_EF_VEF_P1NC_Stab::calculer_flux_bords(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Op_Dift_Stab_VEF_Face::calculer_gradients(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Dift_Stab_VEF_Face::calculer_min(), Op_Conv_VEF_base::calculer_pour_post(), Op_Diff_VEF_base::calculer_pour_post(), Op_Dift_VEF_Face::calculer_pour_post(), EDO_Pression_th_VEF::completer(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Champ_P1NC::compo_normale_sortante(), Champ_Q1NC::compo_normale_sortante(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec(), Terme_Source_Decroissance_Radioactive_VEF_Face::contribuer_a_avec(), Op_Conv_kschemas_centre_VEF::convkschemas_centre(), Op_Div_VEFP1B_Elem::degres_liberte(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Op_Conv_Amont_old_VEF_Face::dimensionner(), Op_Conv_EF_VEF_P1NC::dimensionner(), Op_Conv_VEF_Face::dimensionner(), Op_Diff_VEF_Anisotrope_Face::dimensionner(), Op_Diff_VEF_Face::dimensionner(), Op_Diff_VEF_Face_Q1::dimensionner(), Op_Dift_VEF_Face::dimensionner(), Op_Dift_VEF_Face_Q1::dimensionner(), Op_Curl_VEFP1B::elements_pour_sommet(), Champ_Q1NC::gradient(), Champ_P1NC::gradient(), EDO_Pression_th_VEF::masse_totale(), Eval_Darcy_VEF_Face::mettre_a_jour(), Eval_Dirac_VEF_Face::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VEF_Face::mettre_a_jour(), Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Assembleur_P_VEF::modifier_matrice(), Op_Conv_Amont_old_VEF_Face::modifier_pour_Cl(), Op_Conv_EF_VEF_P1NC::modifier_pour_Cl(), Op_Conv_VEF_Face::modifier_pour_Cl(), Op_Diff_VEF_Anisotrope_Face::modifier_pour_Cl(), Op_Diff_VEF_Face::modifier_pour_Cl(), Op_Diff_VEF_Face_Q1::modifier_pour_Cl(), Op_Dift_VEF_Face::modifier_pour_Cl(), Op_Dift_VEF_Face_Q1::modifier_pour_Cl(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEF::modifier_solution(), EOS_Tools_VEF::moyenne_vol(), Champ_P1NC::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Champ_P1NC::norme_L2(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_L2(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Op_Conv_EF_VEF_P1NC_Stab::reinit_conv_pour_Cl(), Assembleur_P_VEF::remplir(), Op_Conv_EF_VEF_P1NC_Stab::remplir_fluent(), Op_Conv_Muscl_New_VEF_Face::remplir_fluent(), Op_Conv_VEF_Face::remplir_fluent(), Op_Diff_VEF_base::remplir_nu(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EOS_Tools_VEF::secmembre_divU_Z(), Op_Conv_EF_VEF_P1NC_Stab::test(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), Champ_P0_VEF::valeur_au_bord(), Op_Curl_VEFP1B::vecteur_normal(), Op_Diff_RotRot::vecteur_normal(), Op_Rot_VEFP1B::vecteur_normal(), Op_Diff_VEF_Anisotrope_Face::verifier(), Op_Diff_VEF_Face::verifier(), Op_Diff_VEF_base::viscA(), Op_Div_VEFP1B_Elem::volumique(), Op_Div_VEF_Elem::volumique(), Champ_Fonc_P1_VEF::zone_dis_base(), Champ_Fonc_P1NC::zone_dis_base(), Champ_Fonc_Q1NC::zone_dis_base(), Champ_Ostwald_VEF::zone_dis_base(), Champ_P0_VEF::zone_dis_base(), Champ_P1NC::zone_dis_base(), Champ_Q1NC::zone_dis_base(), Assembleur_P_VEF::zone_dis_base(), Op_Curl_VEFP1B::zone_Vef(), Op_Diff_RotRot::zone_Vef(), Op_Grad_VEF_P1B_Face::zone_Vef(), Op_Rot_VEFP1B::zone_Vef(), Assembleur_P_VEFPreP1B::zone_Vef(), Op_Diff_VEF_Face_Penalise::zone_vef(), Champ_Fonc_P1NC::zone_vef(), Champ_Fonc_Q1NC::zone_vef(), Champ_P1NC::zone_vef(), Champ_Q1NC::zone_vef(), and Op_Diff_VEFP1NCP1B_Face::zone_VEFPreP1B().
Member Data Documentation
info_obj
const Type_info Ref_Zone_VEF::info_obj static
Definition at line 21 of file Ref_Zone_VEF.h.
pointeur_
Zone_VEF* Ref_Zone_VEF::pointeur_ private
Definition at line 21 of file Ref_Zone_VEF.h.
The documentation for this class was generated from the following files:
src/VEF/Zones/Ref_Zone_VEF.h
src/VEF/Zones/Ref_Zone_VEF.cpp