TRUST: Loi_Etat_Multi_GP_WC Class Reference
Loi_Etat_Multi_GP_WC Class Reference
classe Loi_Etat_Multi_GP_WC
Cette classe represente la loi d'etat pour un melange de gaz parfaits.
#include <Loi_Etat_Multi_GP_WC.h>
Public Member Functions
~Loi_Etat_Multi_GP_WC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_Multi_GP_WC ()
void initialiser_inco_ch () override
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
void calculer_masse_molaire (DoubleTab &M) const override
Calcule la masse molaire du melange (M)
M depend de la mase molaire de chaque espece et de la composition du melange (Yi)
void calculer_tab_Cp (DoubleTab &cp) const override
Calcule le Cp du melange
Le Cp depend du Cp de chaque espece et de la composition du melange (Yi)
void calculer_masse_volumique () override
Recalcule la masse volumique.
void calculer_mu_sur_Sc () override
returns rho * D
void calculer_nu_sur_Sc () override
returns D
double calculer_masse_volumique (double, double) const override
double calculer_masse_volumique (double P, double T, double r) const override
const Champ_Don & masse_molaire_especes () const
const Champ_Don & visc_dynamique_especes () const
const Champ_Don & coeff_diffusion_especes () const
const Champ_Don & cp_especes () const
Public Member Functions inherited from Loi_Etat_Multi_GP_base
Loi_Etat_Multi_GP_base ()
~Loi_Etat_Multi_GP_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void calculer_masse_molaire ()
void calculer_Cp () override
Calcule le Cp
NE FAIT RIEN : le Cp est constant.
void calculer_lambda () override
Calcule la conductivite.
void calculer_alpha () override
Calcule la diffusivite.
void calculer_mu () override
Calcule la viscosite dynamique.
virtual void associer_inconnue (const Champ_Inc_base &inconnue)
Associe l inconnue de chaque equation de
fraction massique a la loi d'etat.
void initialiser_inco_ch () override
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
double calculer_masse_volumique (double, double) const override
void calculer_masse_volumique () override=0
Calcule la masse volumique.
virtual void calculer_masse_molaire (DoubleTab &M) const =0
virtual void calculer_tab_Cp (DoubleTab &cp) const =0
virtual void calculer_mu_wilke ()=0
const DoubleTab & masse_molaire () const
DoubleTab & masse_molaire ()
virtual double calculer_masse_volumique (double P, double T, double r) const
Public Member Functions inherited from Loi_Etat_Melange_GP_base
Loi_Etat_Melange_GP_base ()
~Loi_Etat_Melange_GP_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_fluide (const Fluide_Dilatable_base &) override
Associe le fluide a la loi d'etat.
Public Member Functions inherited from Loi_Etat_GP_base
~Loi_Etat_GP_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_GP_base ()
const Nom type_fluide () const override
Renvoie le type de fluide associe.
void associer_fluide (const Fluide_Dilatable_base &) override
Associe le fluide a la loi d'etat.
void calculer_lambda () override
Calcule la conductivite.
void calculer_alpha () override
Calcule la diffusivite.
void remplir_T () override
Remplit le tableau de la temperature : T=temp+273.15.
void calculer_Cp () override
Calcule le Cp
NE FAIT RIEN : le Cp est constant.
void calculer_masse_volumique () override
Calcule la masse volumique.
void initialiser () override
Initialise la loi d'etat : calcul Pth.
double calculer_masse_volumique (double, double) const override
double inverser_Pth (double, double) override
Calcule la pression avec la temperature et la masse volumique.
double R () const
Public Member Functions inherited from Loi_Etat_base
~Loi_Etat_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_base ()
void assoscier_probleme (const Probleme_base &pb)
Associe le probleme a la loi d'etat.
void mettre_a_jour (double)
Met a jour la loi d'etat et le champ rho.
void calculer_nu ()
Calcule la viscosite cinematique.
Champ_Don & ch_temperature ()
const Champ_Don & ch_temperature () const
Renvoie le champ de le temperature.
virtual void associer_fluide (const Fluide_Dilatable_base &)
Associe le fluide a la loi d'etat.
virtual void preparer_calcul ()
Prepare le fluide au calcul.
virtual void abortTimeStep ()
virtual void initialiser_inco_ch ()
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
virtual void calculer_mu ()
Calcule la viscosite.
virtual void calculer_lambda ()
Calcule la conductivite.
virtual void calculer_alpha ()
Calcule la diffusivite.
virtual void calculer_mu_sur_Sc ()
Ne fait rien
Surcharge dans Loi_Etat_Melange_GP.
virtual void calculer_nu_sur_Sc ()
Ne fait rien
Surcharge dans Loi_Etat_Melange_Binaire.
virtual void calculer_masse_volumique ()
Recalcule la masse volumique.
virtual double calculer_H (double, double) const
Cas gaz parfait : ne fait rien
Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
virtual double Drho_DP (double, double) const
virtual double Drho_DT (double, double) const
virtual double De_DP (double, double) const
virtual double De_DT (double, double) const
const Champ_base & get_champ (const Motcle &nom) const override
void creer_champ (const Motcle &motlu) override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Nom type_fluide () const =0
virtual void initialiser ()=0
virtual void remplir_T ()=0
virtual void calculer_Cp ()=0
virtual double calculer_masse_volumique (double, double) const =0
virtual double inverser_Pth (double, double)=0
Champs_compris & champs_compris ()
const DoubleTab & temperature () const
const DoubleTab & rho_n () const
const DoubleTab & rho_np1 () const
double Prandt () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Loi_Etat_Multi_GP_WC & self_cast (Objet_U &)
static const Loi_Etat_Multi_GP_WC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_Multi_GP_base
static const Type_info * info ()
static Loi_Etat_Multi_GP_base & self_cast (Objet_U &)
static const Loi_Etat_Multi_GP_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_Melange_GP_base
static const Type_info * info ()
static Loi_Etat_Melange_GP_base & self_cast (Objet_U &)
static const Loi_Etat_Melange_GP_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_GP_base
static const Type_info * info ()
static Loi_Etat_GP_base & self_cast (Objet_U &)
static const Loi_Etat_GP_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_base
static const Type_info * info ()
static Loi_Etat_base & self_cast (Objet_U &)
static const Loi_Etat_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_Multi_GP_base
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_Melange_GP_base
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_GP_base
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Loi_Etat_Multi_GP_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void calculer_tab_mu (const DoubleTab &mu, int size)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_Don molar_mass_
Champ_Don mu_
Champ_Don diffusion_coeff_
Champ_Don cp_
int num_espece_
Protected Attributes inherited from Loi_Etat_Multi_GP_base
List_Ref_Champ_Inc_base liste_Y
DoubleTab masse_mol_mel
Protected Attributes inherited from Loi_Etat_GP_base
double Cp_
double R_
Protected Attributes inherited from Loi_Etat_base
Ref_Fluide_Dilatable_base le_fluide
Ref_Probleme_base le_prob_
Champ_Don temperature_
DoubleTab tab_rho_n
DoubleTab tab_rho_np1
double Pr_
int debug
Private Member Functions
void calculer_mu_wilke () override
Calcule la viscosite dynamique de reference (depend des Yi)
void update_Yn_values (Champ_Don &Yn, double temps)
Additional Inherited Members
Static Protected Attributes inherited from Loi_Etat_Melange_GP_base
static constexpr double R_GAS = 8.314472
Detailed Description
classe Loi_Etat_Multi_GP_WC
Cette classe represente la loi d'etat pour un melange de gaz parfaits.
Definition at line 32 of file Loi_Etat_Multi_GP_WC.h.
Constructor & Destructor Documentation
~Loi_Etat_Multi_GP_WC()
Loi_Etat_Multi_GP_WC::~Loi_Etat_Multi_GP_WC ()
Definition at line 25 of file Loi_Etat_Multi_GP_WC.cpp.
Loi_Etat_Multi_GP_WC()
Loi_Etat_Multi_GP_WC::Loi_Etat_Multi_GP_WC ()
Definition at line 28 of file Loi_Etat_Multi_GP_WC.cpp.
: num_espece_(-1) { }
Member Function Documentation
calculer_masse_molaire()
void Loi_Etat_Multi_GP_WC::calculer_masse_molaire (DoubleTab & M) const override virtual
Calcule la masse molaire du melange (M)
M depend de la mase molaire de chaque espece et de la composition du melange (Yi)
Implements Loi_Etat_Multi_GP_base.
Definition at line 125 of file Loi_Etat_Multi_GP_WC.cpp.
{
  assert (sub_type(Champ_Uniforme,masse_molaire_especes().valeur()));
  const int size = tab_masse_mol_mel.size();
  assert (liste_Y(0)->valeurs().size()==size);
  ArrOfDouble inv_M(size);
  const Fluide_Weakly_Compressible& FWC = ref_cast(Fluide_Weakly_Compressible,le_fluide.valeur());
  const DoubleTab& Yn = FWC.fraction_massique_nonresolue().valeurs();
  for (int i=0; i < num_espece_; i++)
    {
      const DoubleTab& Y_i = (i == num_espece_ -1) ? Yn : liste_Y(i)->valeurs();
      const double M_i = masse_molaire_especes()->valeurs()(0,i);
      for (int elem=0; elem<size; elem++) inv_M[elem] += Y_i(elem,0)/M_i;
    }
  for (int elem=0; elem<size; elem++) tab_masse_mol_mel(elem,0) = 1.0 / inv_M[elem];
}
References Fluide_Weakly_Compressible::fraction_massique_nonresolue(), Loi_Etat_base::le_fluide, Loi_Etat_Multi_GP_base::liste_Y, masse_molaire_especes(), num_espece_, ref_cast, TRUSTVect< _TYPE_ >::size(), sub_type, Ref_Fluide_Dilatable_base::valeur(), valeur(), and Champ_Don::valeurs().
calculer_masse_volumique() [1/3]
void Loi_Etat_Multi_GP_WC::calculer_masse_volumique () override virtual
Recalcule la masse volumique.
< XXX : a voir si l'appel est dans le bon endroit ...
Implements Loi_Etat_Multi_GP_base.
Definition at line 195 of file Loi_Etat_Multi_GP_WC.cpp.
{
  const DoubleTab& tab_ICh = le_fluide->inco_chaleur().valeurs();
  DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  Fluide_Weakly_Compressible& FWC = ref_cast(Fluide_Weakly_Compressible,le_fluide.valeur());
  Champ_Don& Yn = FWC.fraction_massique_nonresolue();
  double temps = le_fluide->masse_volumique().temps();
  update_Yn_values(Yn,temps); //!< XXX : a voir si l'appel est dans le bon endroit ...
  Loi_Etat_Multi_GP_base::calculer_masse_molaire();
  assert (tab_rho.line_size() == 1);
  const int n = tab_rho.size();
  const DoubleTab& pres = FWC.pression_th_tab();
  for (int som=0 ; som<n ; som++)
    {
      double r = R_GAS / masse_mol_mel(som);
      tab_rho_np1(som) = calculer_masse_volumique(pres(som,0),tab_ICh(som,0),r);
      tab_rho(som,0) = 0.5 * ( tab_rho_n(som) + tab_rho_np1(som) );
    }
  tab_rho.echange_espace_virtuel();
  tab_rho_np1.echange_espace_virtuel();
  le_fluide->calculer_rho_face(tab_rho_np1);
  Debog::verifier("Loi_Etat_Multi_GP_WC::calculer_masse_volumique, tab_rho_np1",tab_rho_np1);
  Debog::verifier("Loi_Etat_Multi_GP_WC::calculer_masse_volumique, tab_rho",tab_rho);
}
References Loi_Etat_Multi_GP_base::calculer_masse_molaire(), calculer_masse_volumique(), Fluide_Dilatable_base::calculer_rho_face(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Fluide_Weakly_Compressible::fraction_massique_nonresolue(), Fluide_Dilatable_base::inco_chaleur(), Loi_Etat_base::le_fluide, TRUSTVect< _TYPE_ >::line_size(), Loi_Etat_Multi_GP_base::masse_mol_mel, Milieu_base::masse_volumique(), Fluide_Weakly_Compressible::pression_th_tab(), Loi_Etat_Melange_GP_base::R_GAS, ref_cast, TRUSTVect< _TYPE_ >::size(), Loi_Etat_base::tab_rho_n, Loi_Etat_base::tab_rho_np1, Champ::temps(), update_Yn_values(), Ref_Fluide_Dilatable_base::valeur(), Champ::valeurs(), Champ_Inc::valeurs(), and Debog::verifier().
Referenced by calculer_masse_volumique().
calculer_masse_volumique() [2/3]
double Loi_Etat_Multi_GP_WC::calculer_masse_volumique (double P, double T, double r) const override virtual
Reimplemented from Loi_Etat_Multi_GP_base.
Definition at line 224 of file Loi_Etat_Multi_GP_WC.cpp.
{
  return Loi_Etat_Multi_GP_base::calculer_masse_volumique(P,T,r);
}
References Loi_Etat_Multi_GP_base::calculer_masse_volumique().
calculer_masse_volumique() [3/3]
double Loi_Etat_Multi_GP_WC::calculer_masse_volumique (double P, double T) const override virtual
Reimplemented from Loi_Etat_Multi_GP_base.
Definition at line 229 of file Loi_Etat_Multi_GP_WC.cpp.
{
  return Loi_Etat_Multi_GP_base::calculer_masse_volumique(P,T);
}
References Loi_Etat_Multi_GP_base::calculer_masse_volumique().
calculer_mu_sur_Sc()
void Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc () override virtual
returns rho * D
Calcule la viscosite dynamique sur Schmidt = rho * D.
Reimplemented from Loi_Etat_base.
Definition at line 304 of file Loi_Etat_Multi_GP_WC.cpp.
{
  /*
   * ====================================================================
   * Schmidt number : Sc = nu / D = mu / ( rho * D )
   * => rho * D = mu/Sc
   * species equation : div ( rho * D * grad Y1) = div ( mu/Sc * grad Y1)
   * ====================================================================
   */
  Champ_Don& mu_sur_Sc = le_fluide->mu_sur_Schmidt();
  DoubleTab& tab_mu_sur_Sc = mu_sur_Sc.valeurs();
  const Champ_base& rho = le_fluide->masse_volumique().valeur();
  const DoubleTab& tab_rho = rho.valeurs();
  const int n = tab_mu_sur_Sc.size();
// TODO : FIXME : On a tab_mu_sur_Sc.line_size() = 1 :(:/ :(
// BUG : il faut avoir line_size = num_espece_ car on peut avoir D qui varie entre espce
  if (!sub_type(Champ_Uniforme,mu_sur_Sc.valeur()))
    {
      if (sub_type(Champ_Uniforme,rho))
        {
          Cerr << "We should not have a density field of type Champ_Uniforme !" << finl;
          Process::exit();
        }
      else
        for (int i=0 ; i<n ; i++)
          {
// TODO : FIXME : j'ai pris D de l'espce 1 ...
            tab_mu_sur_Sc(i,0) = tab_rho(i,0) * coeff_diffusion_especes()->valeurs()(0,0);
          }
    }
  else
    {
      Cerr << "We should not have a mu_sur_Sc of type Champ_Uniforme !" << finl;
      Process::exit();
    }
  mu_sur_Sc.valeur().changer_temps(rho.temps());
  tab_mu_sur_Sc.echange_espace_virtuel();
}
References Cerr, Champ_base::changer_temps(), coeff_diffusion_especes(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, Loi_Etat_base::le_fluide, Milieu_base::masse_volumique(), Fluide_Dilatable_base::mu_sur_Schmidt(), TRUSTVect< _TYPE_ >::size(), sub_type, Champ_base::temps(), Deriv_Champ_base::valeur(), Deriv_Champ_Don_base::valeur(), Champ_Don::valeurs(), and Champ_Proto::valeurs().
calculer_mu_wilke()
void Loi_Etat_Multi_GP_WC::calculer_mu_wilke () override private virtual
Calcule la viscosite dynamique de reference (depend des Yi)
< sinon phi_ii = 1
Implements Loi_Etat_Multi_GP_base.
Definition at line 248 of file Loi_Etat_Multi_GP_WC.cpp.
{
// With Wilke formulation : https://aip.scitation.org/doi/pdf/10.1063/1.1747673
// See also for mass fractions : https://doi.org/10.1016/j.ijheatmasstransfer.2020.120470
  assert (liste_Y.size() + 1 == num_espece_);
  const int size = liste_Y(0)->valeurs().size();
  DoubleTab phi(size), mu(size);
  mu = 0.;
  phi = 0.;
  Fluide_Weakly_Compressible& FWC = ref_cast(Fluide_Weakly_Compressible,le_fluide.valeur());
  DoubleTab& Yn = FWC.fraction_massique_nonresolue().valeurs();
  for (int i=0; i < num_espece_ ; i++)
    {
      phi = 0.;
      const double M_i = masse_molaire_especes()->valeurs()(0,i);
      const double mu_i = visc_dynamique_especes()->valeurs()(0,i);
      for (int j=0; j < num_espece_ ; j++)
        if (j != i) //!< sinon phi_ii = 1
          {
            const double M_j = masse_molaire_especes()->valeurs()(0,j);
            const double mu_j = visc_dynamique_especes()->valeurs()(0,j);
            double a = 1. + sqrt( mu_i / mu_j ) * pow( M_j / M_i , 0.25);
            double b = sqrt( 8. * ( 1. + ( M_i / M_j )));
            double phi_ij = ( M_i / M_j ) * a * a / b;
// TODO : FIXME : a voir si Yn->valeurs() est a jour
            const DoubleTab& y_j = (j == num_espece_ -1) ? Yn : liste_Y(j)->valeurs();
// node is elem (VDF) or face (VEF)
            for (int node=0; node<y_j.size(); node++) phi(node) += y_j(node,0) * phi_ij;
          }
// We add the mass fraction when i = j
      const DoubleTab& y_i = (i == num_espece_ -1) ? Yn : liste_Y(i)->valeurs();
      for (int node=0; node<y_i.size(); node++) mu(node) += mu_i * y_i(node,0) / ( y_i(node,0) + phi(node) );
    }
  calculer_tab_mu(mu, size);
}
References Loi_Etat_Multi_GP_base::calculer_tab_mu(), Fluide_Weakly_Compressible::fraction_massique_nonresolue(), Loi_Etat_base::le_fluide, Loi_Etat_Multi_GP_base::liste_Y, masse_molaire_especes(), num_espece_, ref_cast, TRUSTVect< _TYPE_ >::size(), liste::size(), Ref_Fluide_Dilatable_base::valeur(), Champ_Don::valeurs(), and visc_dynamique_especes().
calculer_nu_sur_Sc()
void Loi_Etat_Multi_GP_WC::calculer_nu_sur_Sc () override virtual
returns D
Calcule la viscosite dynamique sur Schmidt = D.
Reimplemented from Loi_Etat_base.
Definition at line 361 of file Loi_Etat_Multi_GP_WC.cpp.
{
  /*
   * ====================================================================
   * Schmidt number : Sc = nu / D
   * => D = nu/Sc
   * ====================================================================
   */
  Champ_Don& nu_sur_Sc = le_fluide->nu_sur_Schmidt();
  DoubleTab& tab_nu_sur_Sc = nu_sur_Sc.valeurs();
  const int n = tab_nu_sur_Sc.size();
// TODO : FIXME : On a tab_nu_sur_Sc.line_size() = 1 :(:/ :(
// BUG : il faut avoir line_size = num_espece_ car on peut avoir D qui varie entre espce
// TODO : FIXME : j'ai pris D de l'espce 1 ...
  for (int i=0 ; i<n ; i++) tab_nu_sur_Sc(i,0) = coeff_diffusion_especes()->valeurs()(0,0);
  double temps_champ = le_fluide->masse_volumique().temps();
  nu_sur_Sc.valeur().changer_temps(temps_champ);
  tab_nu_sur_Sc.echange_espace_virtuel();
}
References Champ_base::changer_temps(), coeff_diffusion_especes(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Loi_Etat_base::le_fluide, Milieu_base::masse_volumique(), Fluide_Dilatable_base::nu_sur_Schmidt(), TRUSTVect< _TYPE_ >::size(), Champ::temps(), Deriv_Champ_Don_base::valeur(), and Champ_Don::valeurs().
calculer_tab_Cp()
void Loi_Etat_Multi_GP_WC::calculer_tab_Cp (DoubleTab & cp) const override virtual
Calcule le Cp du melange
Le Cp depend du Cp de chaque espece et de la composition du melange (Yi)
Implements Loi_Etat_Multi_GP_base.
Definition at line 161 of file Loi_Etat_Multi_GP_WC.cpp.
{
// FIXME : Actuellement on suppose que Cp est pris constant pour chacune des especes
  assert (sub_type(Champ_Uniforme,cp_especes().valeur()));
  tab_Cp = 0;
  const int size =liste_Y(0)->valeurs().size();
  const Fluide_Weakly_Compressible& FWC = ref_cast(Fluide_Weakly_Compressible,le_fluide.valeur());
  const DoubleTab& Yn = FWC.fraction_massique_nonresolue().valeurs();
  for (int i=0; i<num_espece_; i++)
    {
// TODO : FIXME : a voir si Yn->valeurs() est a jour
      const DoubleTab& Y_i = (i == num_espece_ -1) ? Yn : liste_Y(i)->valeurs();
      const double cp_i = cp_especes()->valeurs()(0,i);
      for (int elem=0; elem<size; elem++) tab_Cp(elem,0) += Y_i(elem,0)*cp_i;
    }
}
References cp_especes(), Fluide_Weakly_Compressible::fraction_massique_nonresolue(), Loi_Etat_base::le_fluide, Loi_Etat_Multi_GP_base::liste_Y, num_espece_, ref_cast, sub_type, Ref_Fluide_Dilatable_base::valeur(), valeur(), and Champ_Don::valeurs().
coeff_diffusion_especes()
const Champ_Don & Loi_Etat_Multi_GP_WC::coeff_diffusion_especes () const inline
Definition at line 50 of file Loi_Etat_Multi_GP_WC.h.
{ return diffusion_coeff_; }
References diffusion_coeff_.
Referenced by calculer_mu_sur_Sc(), and calculer_nu_sur_Sc().
cp_especes()
const Champ_Don & Loi_Etat_Multi_GP_WC::cp_especes () const inline
Definition at line 51 of file Loi_Etat_Multi_GP_WC.h.
{ return cp_; }
References cp_.
Referenced by calculer_tab_Cp().
cree_instance()
Objet_U * Loi_Etat_Multi_GP_WC::cree_instance () static
Definition at line 25 of file Loi_Etat_Multi_GP_WC.cpp.
duplique()
int Loi_Etat_Multi_GP_WC::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file Loi_Etat_Multi_GP_WC.cpp.
get_info()
const Type_info * Loi_Etat_Multi_GP_WC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_Multi_GP_base.
Definition at line 25 of file Loi_Etat_Multi_GP_WC.cpp.
info()
const Type_info * Loi_Etat_Multi_GP_WC::info () static
Definition at line 25 of file Loi_Etat_Multi_GP_WC.cpp.
initialiser_inco_ch()
void Loi_Etat_Multi_GP_WC::initialiser_inco_ch () override virtual
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
< pas 0 car reprise pt etre
Reimplemented from Loi_Etat_Multi_GP_base.
Definition at line 61 of file Loi_Etat_Multi_GP_WC.cpp.
{
  /*
   * XXX : In this problem we solve n-1 equations for n species
   * The mass fraction of species n is [ 1 - (y1+y2+ ... +yn-1) ]
   */
  if (liste_Y.size() + 1  != num_espece_ )
    {
      Cerr << "Error in your data file : This is not allowed !" << finl;
      Cerr << "You should define " << num_espece_-1 << " Species equations and not " << liste_Y.size() << finl;
      Process::exit();
    }
  Fluide_Weakly_Compressible& FWC = ref_cast(Fluide_Weakly_Compressible,le_fluide.valeur());
  Champ_Don& Yn = FWC.fraction_massique_nonresolue();
  Yn.nommer("fraction_massique_nonresolue");
  double t = le_fluide->masse_volumique().temps(); //!< pas 0 car reprise pt etre
  update_Yn_values(Yn,t);
  Loi_Etat_Multi_GP_base::initialiser_inco_ch();
}
References Cerr, Process::exit(), finl, Fluide_Weakly_Compressible::fraction_massique_nonresolue(), Loi_Etat_Multi_GP_base::initialiser_inco_ch(), Loi_Etat_base::le_fluide, Loi_Etat_Multi_GP_base::liste_Y, Milieu_base::masse_volumique(), Objet_U::nommer(), num_espece_, ref_cast, liste::size(), Champ::temps(), update_Yn_values(), and Ref_Fluide_Dilatable_base::valeur().
masse_molaire_especes()
const Champ_Don & Loi_Etat_Multi_GP_WC::masse_molaire_especes () const inline
Definition at line 48 of file Loi_Etat_Multi_GP_WC.h.
{ return molar_mass_; }
References molar_mass_.
Referenced by calculer_masse_molaire(), and calculer_mu_wilke().
printOn()
Sortie & Loi_Etat_Multi_GP_WC::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Loi_Etat_Multi_GP_base.
Definition at line 30 of file Loi_Etat_Multi_GP_WC.cpp.
{
  os <<que_suis_je()<< finl;
  return os;
}
References finl, and Objet_U::que_suis_je().
readOn()
Entree & Loi_Etat_Multi_GP_WC::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
< XD_ADD_P int Number of species you are considering in your problem.
< XD_ADD_P field_base Diffusion coefficient of each species, defined with a Champ_uniforme of dimension equals to the species_number.
< XD_ADD_P field_base Molar mass of each species, defined with a Champ_uniforme of dimension equals to the species_number.
< XD_ADD_P field_base Dynamic viscosity of each species, defined with a Champ_uniforme of dimension equals to the species_number.
< XD_ADD_P field_base Specific heat at constant pressure of the gas Cp, defined with a Champ_uniforme of dimension equals to the species_number..
< XD_ADD_P double Prandtl number of the gas Pr=mu*Cp/lambda.
Reimplemented from Loi_Etat_Multi_GP_base.
Definition at line 36 of file Loi_Etat_Multi_GP_WC.cpp.
{
  Param param(que_suis_je());
  param.ajouter("Species_number",&num_espece_,Param::REQUIRED); //!< XD_ADD_P int Number of species you are considering in your problem.
  param.ajouter("Diffusion_coeff",&diffusion_coeff_,Param::REQUIRED); //!< XD_ADD_P field_base Diffusion coefficient of each species, defined with a Champ_uniforme of dimension equals to the species_number.
  param.ajouter("Molar_mass",&molar_mass_,Param::REQUIRED); //!< XD_ADD_P field_base Molar mass of each species, defined with a Champ_uniforme of dimension equals to the species_number.
  param.ajouter("Mu",&mu_,Param::REQUIRED); //!< XD_ADD_P field_base Dynamic viscosity of each species, defined with a Champ_uniforme of dimension equals to the species_number.
  param.ajouter("Cp",&cp_,Param::REQUIRED);//!< XD_ADD_P field_base Specific heat at constant pressure of the gas Cp, defined with a Champ_uniforme of dimension equals to the species_number..
  param.ajouter("Prandtl",&Pr_,Param::REQUIRED); //!< XD_ADD_P double Prandtl number of the gas Pr=mu*Cp/lambda.
  param.lire_avec_accolades_depuis(is);
// XXX
  if (diffusion_coeff_->valeurs().line_size() != num_espece_ ||
      molar_mass_->valeurs().line_size() != num_espece_ ||
      mu_->valeurs().line_size() != num_espece_  ||
      cp_->valeurs().line_size() != num_espece_ )
    {
      Cerr << "Error while reading the EOS Multi_Gaz_Parfait_WC : This is not allowed !" << finl;
      Cerr << "Verify that the dimension of the fields Diffusion_coeff, Molar_mass, Mu and Cp is = " << num_espece_ << finl;
      Process::exit();
    }
  return is;
}
References Param::ajouter(), Cerr, cp_, diffusion_coeff_, Process::exit(), finl, TRUSTVect< _TYPE_ >::line_size(), Param::lire_avec_accolades_depuis(), molar_mass_, mu_, num_espece_, Loi_Etat_base::Pr_, Objet_U::que_suis_je(), Param::REQUIRED, and Champ_Don::valeurs().
self_cast() [1/2]
const Loi_Etat_Multi_GP_WC & Loi_Etat_Multi_GP_WC::self_cast (const Objet_U & r) static
Definition at line 25 of file Loi_Etat_Multi_GP_WC.cpp.
self_cast() [2/2]
Loi_Etat_Multi_GP_WC & Loi_Etat_Multi_GP_WC::self_cast (Objet_U & r) static
Definition at line 25 of file Loi_Etat_Multi_GP_WC.cpp.
taille_memoire()
unsigned Loi_Etat_Multi_GP_WC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file Loi_Etat_Multi_GP_WC.cpp.
update_Yn_values()
void Loi_Etat_Multi_GP_WC::update_Yn_values (Champ_Don & Yn, double temps) private
< re-initialize as 1
Definition at line 83 of file Loi_Etat_Multi_GP_WC.cpp.
{
  DoubleTab& tab_Yn = Yn.valeurs();
  Yn.mettre_a_jour(temps);
  tab_Yn = 1.0;//!< re-initialize as 1
  const int size = liste_Y(0)->valeurs().size();
  assert(tab_Yn.size() == size);
  assert (liste_Y.size() + 1  == num_espece_);
  for (int i=0; i<liste_Y.size(); i++)
    for (int n=0; n<size; n++) tab_Yn(n,0) -= liste_Y(i)->valeurs()(n,0);
  double min_Yn = local_min_vect(tab_Yn);
  if (min_Yn < 0)
    {
      Cerr << "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" << finl;
      Cerr << "BIG PROBLEM : check your calculation because we are detecting negative mass fraction !" << finl;
      Cerr << "The results are saved to help you !" << finl;
      Cerr << "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" << finl;
      Fluide_Weakly_Compressible& FWC = ref_cast(Fluide_Weakly_Compressible,le_fluide.valeur());
      Probleme_base& pb = FWC.get_problem();
      pb.postraiter(1);
      pb.sauver();
      Process::exit();
    }
}
References Cerr, Process::exit(), finl, Fluide_Dilatable_base::get_problem(), Loi_Etat_base::le_fluide, Loi_Etat_Multi_GP_base::liste_Y, local_min_vect(), Champ_Don::mettre_a_jour(), num_espece_, Probleme_base::postraiter(), ref_cast, Probleme_base::sauver(), TRUSTVect< _TYPE_ >::size(), liste::size(), Ref_Fluide_Dilatable_base::valeur(), and Champ_Don::valeurs().
Referenced by calculer_masse_volumique(), and initialiser_inco_ch().
visc_dynamique_especes()
const Champ_Don & Loi_Etat_Multi_GP_WC::visc_dynamique_especes () const inline
Definition at line 49 of file Loi_Etat_Multi_GP_WC.h.
{ return mu_; }
References mu_.
Referenced by calculer_mu_wilke().
Member Data Documentation
cp_
Champ_Don Loi_Etat_Multi_GP_WC::cp_ protected
Definition at line 54 of file Loi_Etat_Multi_GP_WC.h.
Referenced by cp_especes(), and readOn().
diffusion_coeff_
Champ_Don Loi_Etat_Multi_GP_WC::diffusion_coeff_ protected
Definition at line 54 of file Loi_Etat_Multi_GP_WC.h.
Referenced by coeff_diffusion_especes(), and readOn().
info_obj
const Type_info Loi_Etat_Multi_GP_WC::info_obj static
Definition at line 34 of file Loi_Etat_Multi_GP_WC.h.
molar_mass_
Champ_Don Loi_Etat_Multi_GP_WC::molar_mass_ protected
Definition at line 54 of file Loi_Etat_Multi_GP_WC.h.
Referenced by masse_molaire_especes(), and readOn().
mu_
Champ_Don Loi_Etat_Multi_GP_WC::mu_ protected
Definition at line 54 of file Loi_Etat_Multi_GP_WC.h.
Referenced by readOn(), and visc_dynamique_especes().
num_espece_
int Loi_Etat_Multi_GP_WC::num_espece_ protected
Definition at line 55 of file Loi_Etat_Multi_GP_WC.h.
Referenced by calculer_masse_molaire(), calculer_mu_wilke(), calculer_tab_Cp(), initialiser_inco_ch(), readOn(), and update_Yn_values().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Weakly_Compressible/Loi_Etat/Loi_Etat_Multi_GP_WC.h
src/ThHyd/Dilatable/Weakly_Compressible/Loi_Etat/Loi_Etat_Multi_GP_WC.cpp