TRUST: Solv_Cholesky Class Reference
Solv_Cholesky Class Reference
#include <Solv_Cholesky.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Solv_Cholesky ()
~Solv_Cholesky () override
int resoudre_systeme (const Matrice_Base &, const DoubleVect &, DoubleVect &) override
int resoudre_systeme (const Matrice_Base &M, const DoubleVect &A, DoubleVect &B, int niter_max) override
int solveur_direct () const override
Public Member Functions inherited from SolveurSys_base
~SolveurSys_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
SolveurSys_base ()
virtual int solveur_direct () const =0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x)=0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x, int niter_max)
virtual void fixer_schema_temps_limpr (int l)
void fixer_limpr (int l)
void set_return_on_error (int ret)
int limpr () const
virtual void reinit ()
int nouvelle_matrice () const
void fixer_nouvelle_matrice (int i)
virtual int supporte_matrice_morse_sym ()
virtual int get_flag_updated_input () const
void set_flag_updated_result (int flag)
int get_flag_updated_result () const
void save_matrice_secmem_conditionnel (const Matrice_Base &la_matrice, const DoubleVect &secmem, const DoubleVect &solution, int binaire=1)
void set_reuse_preconditioner (bool flag)
bool reuse_preconditioner ()
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Solv_Cholesky & self_cast (Objet_U &)
static const Solv_Cholesky & self_cast (const Objet_U &)
Static Public Member Functions inherited from SolveurSys_base
static const Type_info * info ()
static SolveurSys_base & self_cast (Objet_U &)
static const SolveurSys_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from SolveurSys_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
int Cholesky (const Matrice_Morse_Sym &, const DoubleVect &, DoubleVect &)
int Fact_Cholesky (const Matrice_Morse_Sym &, const int)
met a jour matrice_bande_factorisee_fortran_
Protected Member Functions inherited from SolveurSys_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int largeur_de_bande_
ArrOfDouble matrice_bande_factorisee_fortran_
Matrice_Morse_Sym matrice_de_travail
Protected Attributes inherited from SolveurSys_base
int nouvelle_matrice_
Drapeau pour savoir si un stockage ou une factorisation est a refaire.
int save_matrice_
Drapeau pour savoir si un stockage disque est a refaire.
int return_on_error_ = 0
Detailed Description
Definition at line 25 of file Solv_Cholesky.h.
Constructor & Destructor Documentation
Solv_Cholesky()
Solv_Cholesky::Solv_Cholesky () inline
Definition at line 51 of file Solv_Cholesky.h.
{
  matrice_bande_factorisee_fortran_=0;
}
References matrice_bande_factorisee_fortran_.
~Solv_Cholesky()
Solv_Cholesky::~Solv_Cholesky () inline override
Definition at line 56 of file Solv_Cholesky.h.
{
// if (matrice_bande_factorisee_fortran_) delete[] matrice_bande_factorisee_fortran_;
}
Member Function Documentation
Cholesky()
int Solv_Cholesky::Cholesky (const Matrice_Morse_Sym & matrice, const DoubleVect & secmem, DoubleVect & solution) protected
< A est triangulaire superieure
< largeur de bande sup int N = n; //m_ // ordre de A (=nb col de abd_)
< nb de col de b (=vecteur)
Definition at line 136 of file Solv_Cholesky.cpp.
{
  int avec_renumerotation=1;
  if (nouvelle_matrice())
    {
      fixer_nouvelle_matrice(0);
// On rend definie la matrice dans le cas sequentiel ou Cholesky est le solveur en pression
// En parallele, Cholesky est utilise en preconditionnement local et il ne faut
// pas modifier la matrice locale.
      Cerr << "Order of the matrix : " << matrice.ordre() << finl;
// Les champs P1bulle n'ont pas de size_reelle et en parallele ca ne marche pas...
      const int sz = secmem.size_totale();
      if(matrice.get_est_definie()==0 && nproc()==1)
        {
          Cerr << "Matrix not defined : " << finl;
          Cerr << "zero value is imposed at point 0" << finl;
          Matrice_Morse_Sym& mat = ref_cast_non_const(Matrice_Morse_Sym,matrice);
          mat(0,0)*=1E+6;
        }
      if (avec_renumerotation)
        {
          matrice.renumerote();
          Fact_Cholesky(matrice.matrice_renumerotee(),sz);
        }
      else
        Fact_Cholesky(matrice, sz);
    }
// int ordre = la_matrice.ordre();
  DoubleVect vecteur(secmem);
  double* vect_data = vecteur.addr();
// solution = 0.0;
  const int n = secmem.size_totale();//ordre;
  int N=n;
// permutation du second membre
// subroutine dvperm (n, x, perm)
// SPARSKIT2/FORMATS/unary.f
  if (avec_renumerotation) F77NAME(DVPERM)(&n, vect_data, matrice.permutation().addr());
  char UPLO = 'U';                          //!< A est triangulaire superieure
  int KD   = largeur_de_bande_-1;           //!< largeur de bande sup int N    = n;                             //m_ // ordre de A (=nb col de abd_)
//
  int LDAB = largeur_de_bande_;             //n_;//!< nb de lg de abd_
  int LDB  = n;                             //m_;//!< nb de lg de b
  int NRHS = 1;                             //!< nb de col de b (=vecteur)
  int INFO = 0;
// resolution du systeme
#ifdef CRAY
  Nom UPLOCpp(UPLO);
  _fcd UPLOF90;
  nomCtonomF90(UPLOCpp,UPLOF90);
  F77NAME(SPBTRS)(UPLOF90, &N, &KD, &NRHS,
                  matrice_bande_factorisee_fortran_.addr() ,
                  &LDAB, vecteur.addr(), &LDB, &INFO);
#else
  F77NAME(DPBTRS)(&UPLO, &N, &KD, &NRHS, matrice_bande_factorisee_fortran_.addr() , &LDAB, vecteur.addr(), &LDB, &INFO);
#endif
  if(INFO)
    {
      Cerr << "Solv_Cholesky::resoudre_systeme error : ";
      if(INFO<0) Cerr << "F77NAME(DPBTRS) param. " << -INFO << " invalid" << finl;
      if(INFO>0) Cerr << "singular matrix ! resolution impossible" << finl;
      exit();
    };
// permutation inverse du resultat
// subroutine dvperm (n, x, perm)
// SPARSKIT2/FORMATS/unary.f
  if (avec_renumerotation) F77NAME(DVPERM)(&n, vect_data, matrice.permutation_inverse().addr());
  solution = vecteur;
  solution.echange_espace_virtuel();
// test
// DoubleVect res;
// Cout<<"second membre "<<secmem.norme()<<finl;
// Cout<<"solution "<<solution.norme()<<finl;
// res = matrice*solution - secmem;
// Cout<<"residu "<<res.norme()<<finl;
  return 1;
}
References TRUSTArray< _TYPE_ >::addr(), Cerr, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), F77NAME, Fact_Cholesky(), finl, SolveurSys_base::fixer_nouvelle_matrice(), Matrice_Sym::get_est_definie(), largeur_de_bande_, matrice_bande_factorisee_fortran_, Matrice_Morse_Sym::matrice_renumerotee(), SolveurSys_base::nouvelle_matrice(), Process::nproc(), Matrice_Morse::ordre(), Matrice_Morse_Sym::permutation(), Matrice_Morse_Sym::permutation_inverse(), ref_cast_non_const, Matrice_Morse_Sym::renumerote(), and TRUSTVect< _TYPE_ >::size_totale().
Referenced by resoudre_systeme().
cree_instance()
Objet_U * Solv_Cholesky::cree_instance () static
Definition at line 26 of file Solv_Cholesky.cpp.
duplique()
int Solv_Cholesky::duplique () const override virtual
Implements Objet_U.
Definition at line 26 of file Solv_Cholesky.cpp.
Fact_Cholesky()
int Solv_Cholesky::Fact_Cholesky (const Matrice_Morse_Sym & mat1, const int size_reelle) protected
met a jour matrice_bande_factorisee_fortran_
< mu nbre de diagonales superieures
Definition at line 229 of file Solv_Cholesky.cpp.
{
  largeur_de_bande_ = mat1.largeur_de_bande();
// stockage de la matrice en format bande FORTRAN
  matrice_bande_factorisee_fortran_.resize_array(size_reelle*largeur_de_bande_);
  for (int j=0; j<size_reelle; j++)
    {
      int  i;
      i = j+1 - largeur_de_bande_;
      int k = 0;
      while (k < largeur_de_bande_)
        {
          if (i >= 0)
            {
// Cout<<"i j "<<i<<" "<<j<<" "<<mat1(i,j)<<" "<<me()<<finl;
              const double tmpa = mat1(i,j);
              matrice_bande_factorisee_fortran_[j * largeur_de_bande_ + k] = tmpa;
            }
          i++;
          k++;
        }
    }
// Factorisation de Cholesky
// int DBG=1;
// int PRC=0;
  char UPLO = 'U';
  int N = size_reelle;
  int KD = largeur_de_bande_ - 1;//!< mu nbre de diagonales superieures
  int LDAB = largeur_de_bande_; //n_
  int INFO = 0;
  Cerr << "Starting factorisation ..." << finl;
#ifdef CRAY
  Nom UPLOCpp(UPLO);
  _fcd UPLOF90;
  nomCtonomF90(UPLOCpp,UPLOF90);
  SPBTRF(UPLOF90, &N, &KD,
         matrice_bande_factorisee_fortran_.addr() , &LDAB, &INFO);
#else
  F77NAME(DPBTRF)(&UPLO, &N, &KD,
                  matrice_bande_factorisee_fortran_.addr() , &LDAB, &INFO);
#endif
  Cerr << "End factorization." << finl;
// {
// double ANORM=1.0;
// double RCOND;
// ArrOfDouble WORK(3*N);
// ArrOfInt IWORK(N);
// F77NAME(DPBCON)(&UPLO, &N, &KD,
// matrice_bande_factorisee_fortran_.addr() , &LDAB,
// &ANORM, &RCOND, WORK.addr(), IWORK.addr(), &INFO);
// Cerr<<"//////////// RCOND : "<<RCOND<<finl;
// }
  if(INFO)
    {
      Cerr << "Solv_Cholesky::Fact_Cholesky() error : ";
      if(INFO<0) Cerr << "F77NAME(DPBTRF) param. " << -INFO
                        << " invalid" << finl;
      if(INFO>0) Cerr << "submatrix of order " << INFO
                        << " not positive definite!" << finl;
      if (INFO<100)
        {
          for (int i=0; i<INFO; i++)
            Cerr << "A(" <<i<<","<<i<<")="<<mat1(i,i)<<finl;
          Cerr << "non-positive definite matrix ="<<finl;
          mat1.imprimer_formatte(Cerr);
        }
      exit();
    };
// rovisoire : on pourrait vider matrice et matrice_renumerotee
  return 1;
}
References TRUSTArray< _TYPE_ >::addr(), Cerr, Process::exit(), F77NAME, finl, Matrice_Morse_Sym::imprimer_formatte(), Matrice_Morse::largeur_de_bande(), largeur_de_bande_, matrice_bande_factorisee_fortran_, and TRUSTArray< _TYPE_ >::resize_array().
Referenced by Cholesky().
get_info()
const Type_info * Solv_Cholesky::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 26 of file Solv_Cholesky.cpp.
info()
const Type_info * Solv_Cholesky::info () static
Definition at line 26 of file Solv_Cholesky.cpp.
printOn()
Sortie & Solv_Cholesky::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 30 of file Solv_Cholesky.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Solv_Cholesky::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 35 of file Solv_Cholesky.cpp.
{
  if ( Process::nproc()>1 )
    {
      Cerr << finl;
      Cerr << "Cholesky solver not parallelized in TRUST!!!" << finl;
      Cerr << "Change your solver." << finl;
      Cerr << "Try using Petsc Cholesky solver." << finl;
      exit();
    }
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Motcles les_parametres(3);
  {
    les_parametres[0] = "impr";
    les_parametres[1] = "save_matrice|save_matrix";
    les_parametres[2] = "quiet";
  }
  int rang;
  Motcle motlu;
  is >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "Error when reading parameters for Cholesky " << finl;
      Cerr << "One expected : " << accolade_ouverte << finl;
      exit();
    }
  is >> motlu;
  while (motlu != accolade_fermee)
    {
      rang = les_parametres.search(motlu);
      switch(rang)
        {
        case 0:
          {
            fixer_limpr(1);
            break;
          }
        case 1:
          {
            save_matrice_ = 1;
            break;
          }
        case 2:
          {
            fixer_limpr(-1);
            break;
          }
        default :
          {
            Cerr << "Error when reading parameters for Cholesky " << finl;
            Cerr << "On expected " << les_parametres << " instead of " << motlu << finl;
            exit();
          }
        }
      is >> motlu;
    }
  return is;
}
References Cerr, Process::exit(), finl, SolveurSys_base::fixer_limpr(), Process::nproc(), SolveurSys_base::save_matrice_, and Motcles::search().
resoudre_systeme() [1/2]
int Solv_Cholesky::resoudre_systeme (const Matrice_Base & la_matrice, const DoubleVect & secmem, DoubleVect & solution) override virtual
Implements SolveurSys_base.
Definition at line 97 of file Solv_Cholesky.cpp.
{
  if(sub_type(Matrice_Morse_Sym,la_matrice))
    {
      const Matrice_Morse_Sym& matrice = ref_cast(Matrice_Morse_Sym,la_matrice);
      return Cholesky(matrice,secmem,solution);
    }
  else
    {
      if(sub_type(Matrice_Bloc_Sym,la_matrice))
        {
// Conversion d'une matrice au format Matrice_Bloc_Sym au format Matrice Morse
          if (nouvelle_matrice())
            ref_cast(Matrice_Bloc_Sym,la_matrice).BlocSymToMatMorseSym(matrice_de_travail);
          return Cholesky(matrice_de_travail,secmem,solution);
        }
      else if(sub_type(Matrice_Bloc,la_matrice))
        {
          const Matrice_Bloc& matrice = ref_cast(Matrice_Bloc,la_matrice);
          if((matrice.nb_bloc_lignes()>1 && ref_cast(Matrice_Morse,matrice.get_bloc(1,0).valeur()).nb_lignes()>0))
            {
              Cerr<<"Solv_Cholesky : WARNING : Cholesky by blocks cannot be done"<<finl;
              exit();
              return(-1);
            }
          const Matrice_Morse_Sym& MB00 = ref_cast(Matrice_Morse_Sym,matrice.get_bloc(0,0).valeur());
          return Cholesky(MB00,secmem,solution);
        }
      else
        {
          Cerr<<"Solv_Cholesky : Warning : one is not able to carry out preconditionning for linear systems based on Matrice_Morse_Sym or Matrice_Bloc type matrixes"<<finl;
          exit();
          return(-1);
        }
    }
}
References Cerr, Cholesky(), Process::exit(), finl, Matrice_Bloc::get_bloc(), matrice_de_travail, Matrice_Bloc::nb_bloc_lignes(), SolveurSys_base::nouvelle_matrice(), ref_cast, sub_type, and Deriv_Matrice_Base::valeur().
Referenced by resoudre_systeme().
resoudre_systeme() [2/2]
int Solv_Cholesky::resoudre_systeme (const Matrice_Base & M, const DoubleVect & A, DoubleVect & B, int niter_max) inline override virtual
Reimplemented from SolveurSys_base.
Definition at line 36 of file Solv_Cholesky.h.
  {
    return resoudre_systeme(M, A, B);
  }
References resoudre_systeme().
self_cast() [1/2]
const Solv_Cholesky & Solv_Cholesky::self_cast (const Objet_U & r) static
Definition at line 26 of file Solv_Cholesky.cpp.
self_cast() [2/2]
Solv_Cholesky & Solv_Cholesky::self_cast (Objet_U & r) static
Definition at line 26 of file Solv_Cholesky.cpp.
solveur_direct()
int Solv_Cholesky::solveur_direct () const inline override virtual
Implements SolveurSys_base.
Definition at line 40 of file Solv_Cholesky.h.
{ return 1; }
taille_memoire()
unsigned Solv_Cholesky::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 26 of file Solv_Cholesky.cpp.
Member Data Documentation
info_obj
const Type_info Solv_Cholesky::info_obj static
Definition at line 27 of file Solv_Cholesky.h.
largeur_de_bande_
int Solv_Cholesky::largeur_de_bande_ protected
Definition at line 44 of file Solv_Cholesky.h.
Referenced by Cholesky(), and Fact_Cholesky().
matrice_bande_factorisee_fortran_
ArrOfDouble Solv_Cholesky::matrice_bande_factorisee_fortran_ protected
Definition at line 45 of file Solv_Cholesky.h.
Referenced by Cholesky(), Fact_Cholesky(), and Solv_Cholesky().
matrice_de_travail
Matrice_Morse_Sym Solv_Cholesky::matrice_de_travail protected
Definition at line 46 of file Solv_Cholesky.h.
Referenced by resoudre_systeme().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/Solv_Cholesky.h
src/Kernel/Math/SolvSys/Solv_Cholesky.cpp