TRUST: Champ_P0_CoviMAC Class Reference
Champ_P0_CoviMAC Class Reference
: class Champ_P0_CoviMAC
Champ correspondant a une inconnue scalaire (type temperature ou pression)
Degres de libertes : valeur aux elements + flux aux faces
#include <Champ_P0_CoviMAC.h>
Public Member Functions
Champ_P0_CoviMAC ()
~Champ_P0_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Zone_CoviMAC & zone_CoviMAC () const
void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
int imprime (Sortie &, int) const
const IntTab & fcl () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_P0_CoviMAC & self_cast (Objet_U &)
static const Champ_P0_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
virtual Entree & readOn (Entree &)
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
void init_fcl () const
Protected Attributes
Ref_Zone_VF la_zone_VF
IntTab fcl_
int fcl_init_ = 0
Detailed Description
: class Champ_P0_CoviMAC
Champ correspondant a une inconnue scalaire (type temperature ou pression)
Degres de libertes : valeur aux elements + flux aux faces
Definition at line 41 of file Champ_P0_CoviMAC.h.
Constructor & Destructor Documentation
Champ_P0_CoviMAC::Champ_P0_CoviMAC ()
Definition at line 40 of file Champ_P0_CoviMAC.cpp.
Champ_P0_CoviMAC::~Champ_P0_CoviMAC ()
Definition at line 40 of file Champ_P0_CoviMAC.cpp.
Member Function Documentation
void Champ_P0_CoviMAC::associer_zone_dis_base (const Zone_dis_base & z_dis) [virtual]
Returns:
z_dis
Signification: la zone discretise
Contraintes:
Reimplemented from Champ_base.
Definition at line 88 of file Champ_P0_CoviMAC.cpp.
References la_zone_VF, and ref_cast.
{
  la_zone_VF=ref_cast(Zone_VF, z_dis);
}
Objet_U * Champ_P0_CoviMAC::cree_instance () [static]
Definition at line 40 of file Champ_P0_CoviMAC.cpp.
int Champ_P0_CoviMAC::duplique () const [virtual]
Implements Champ_Inc_P0_base.
Definition at line 40 of file Champ_P0_CoviMAC.cpp.
const IntTab& Champ_P0_CoviMAC::fcl () const [inline]
Definition at line 61 of file Champ_P0_CoviMAC.h.
References fcl_, fcl_init_, and init_fcl().
  {
    if (!fcl_init_) init_fcl();
    return fcl_;
  }
const Type_info * Champ_P0_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Inc_P0_base.
Definition at line 40 of file Champ_P0_CoviMAC.cpp.
int Champ_P0_CoviMAC::imprime (Sortie & os, int ncomp) const [virtual]
Reimplemented from Champ_Inc_base.
Definition at line 111 of file Champ_P0_CoviMAC.cpp.
References Domaine::coord_sommets(), Cout, Objet_U::dimension, Zone::domaine(), finl, Field_base::nb_compo_, Domaine::nb_som(), Champ_Inc_base::valeurs(), Zone_dis_base::zone(), and zone_dis_base().
{
  const Zone_dis_base& zone_dis = zone_dis_base();
  const Zone& zone = zone_dis.zone();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  const int nb_som = zone.domaine().nb_som();
  const DoubleTab& val = valeurs();
  int som;
  os << nb_som << finl;
  for (som=0; som<nb_som; som++)
    {
      if (dimension==3)
        os << coord(som,0) << " " << coord(som,1) << " " << coord(som,2) << " " ;
      if (dimension==2)
        os << coord(som,0) << " " << coord(som,1) << " " ;
      if (nb_compo_ == 1)
        os << val(som) << finl;
      else
        os << val(som,ncomp) << finl;
    }
  os << finl;
  Cout << "Champ_P0_CoviMAC::imprime FIN >>>>>>>>>> " << finl;
  return 1;
}
const Type_info * Champ_P0_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Inc_P0_base.
Definition at line 40 of file Champ_P0_CoviMAC.cpp.
void Champ_P0_CoviMAC::init_fcl () const [protected]
Definition at line 137 of file Champ_P0_CoviMAC.cpp.
References Cerr, MorEqn::equation(), Process::exit(), fcl_, fcl_init_, finl, la_zone_VF, Zone_Cl_dis::les_conditions_limites(), Champ_Inc_base::ma_zone_cl_dis, Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, IntTab::resize(), sub_type, valeur(), Ref_Zone_Cl_dis::valeur(), and Ref_Zone_VF::valeur().
Referenced by fcl().
{
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC,la_zone_VF.valeur());
  const Conds_lim& cls = ma_zone_cl_dis.valeur().les_conditions_limites();
  int i, f, n;
  fcl_.resize(zone.nb_faces_tot(), 3);
  for (n = 0; n < cls.size(); n++)
    {
      const Front_VF& fvf = ref_cast(Front_VF, cls[n].frontiere_dis());
      int idx = sub_type(Echange_externe_impose, cls[n].valeur()) + 2 * sub_type(Echange_global_impose, cls[n].valeur())
                + 4 * sub_type(Neumann_paroi, cls[n].valeur())      + 5 * (sub_type(Neumann_homogene, cls[n].valeur()) || sub_type(Neumann_sortie_libre, cls[n].valeur()) || sub_type(Symetrie, cls[n].valeur()))
                + 6 * sub_type(Dirichlet, cls[n].valeur())          + 7 * sub_type(Dirichlet_homogene, cls[n].valeur());
      if (sub_type(Echange_contact_CoviMAC, cls[n].valeur()) && sub_type(Schema_Euler_Implicite, equation().schema_temps())
          && ref_cast(Schema_Euler_Implicite, equation().schema_temps()).thermique_monolithique()) idx = 3;
      if (!idx) Cerr << "Champ_P0_CoviMAC : CL non codee rencontree!" << finl, Process::exit();
      for (i = 0; i < fvf.nb_faces_tot(); i++)
        f = fvf.num_face(i), fcl_(f, 0) = idx, fcl_(f, 1) = n, fcl_(f, 2) = i;
    }
  fcl_init_ = 1;
}
Sortie & Champ_P0_CoviMAC::printOn (Sortie & os) const [protected, virtual]
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Inc_P0_base.
Definition at line 44 of file Champ_P0_CoviMAC.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Champ_P0_CoviMAC::readOn (Entree & is) [protected, virtual]
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Inc_P0_base.
Definition at line 52 of file Champ_P0_CoviMAC.cpp.
References Champ_Inc_base::lire_donnees().
{
  lire_donnees(s) ;
  return s ;
}
const Champ_P0_CoviMAC & Champ_P0_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Inc_P0_base.
Definition at line 40 of file Champ_P0_CoviMAC.cpp.
Champ_P0_CoviMAC & Champ_P0_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Inc_P0_base.
Definition at line 40 of file Champ_P0_CoviMAC.cpp.
unsigned Champ_P0_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 40 of file Champ_P0_CoviMAC.cpp.
const Zone_CoviMAC & Champ_P0_CoviMAC::zone_CoviMAC () const
Returns:
la_zone_CoviMAC_P0.valeur()
Signification:
Contraintes:
Definition at line 106 of file Champ_P0_CoviMAC.cpp.
References la_zone_VF, ref_cast, and Ref_Zone_VF::valeur().
{
  return ref_cast(Zone_CoviMAC, la_zone_VF.valeur());
}
const Zone_dis_base & Champ_P0_CoviMAC::zone_dis_base () const [virtual]
Reimplemented from Champ_base.
Definition at line 71 of file Champ_P0_CoviMAC.cpp.
References la_zone_VF, and Ref_Zone_VF::valeur().
Referenced by imprime().
{
  return la_zone_VF.valeur();
}
Member Data Documentation
IntTab Champ_P0_CoviMAC::fcl_ [mutable, protected]
Definition at line 72 of file Champ_P0_CoviMAC.h.
Referenced by fcl(), and init_fcl().
int Champ_P0_CoviMAC::fcl_init_ = 0 [mutable, protected]
Definition at line 73 of file Champ_P0_CoviMAC.h.
Referenced by fcl(), and init_fcl().
const Type_info Champ_P0_CoviMAC::info_obj [static]
Reimplemented from Champ_Inc_P0_base.
Definition at line 43 of file Champ_P0_CoviMAC.h.
Ref_Zone_VF Champ_P0_CoviMAC::la_zone_VF [protected]
Definition at line 69 of file Champ_P0_CoviMAC.h.
Referenced by associer_zone_dis_base(), init_fcl(), zone_CoviMAC(), and zone_dis_base().
The documentation for this class was generated from the following files:
src/CoviMAC/Champs/Champ_P0_CoviMAC.h
src/CoviMAC/Champs/Champ_P0_CoviMAC.cpp