TRUST: Ecrire Class Reference
Ecrire Class Reference
Ecrit un objet :
Ecrire ob1.
#include <Ecrire.h>
Public Member Functions
Ecrire ()
~Ecrire ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &)
Lit le nom d'un objet dans is
Ecrit l'objet correspondant sur la sortie standard.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ecrire & self_cast (Objet_U &)
static const Ecrire & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
appel a la methode printOn de la classe Interprete
virtual Entree & readOn (Entree &)
appel a la methode readOn de la classe Interprete
Detailed Description
Ecrit un objet :
Ecrire ob1.
Definition at line 37 of file Ecrire.h.
Constructor & Destructor Documentation
Ecrire::Ecrire ()
Definition at line 25 of file Ecrire.cpp.
Ecrire::~Ecrire ()
Definition at line 25 of file Ecrire.cpp.
Member Function Documentation
Objet_U * Ecrire::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 25 of file Ecrire.cpp.
int Ecrire::duplique () const [virtual]
Reimplemented from Interprete.
Definition at line 25 of file Ecrire.cpp.
const Type_info * Ecrire::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 25 of file Ecrire.cpp.
const Type_info * Ecrire::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 25 of file Ecrire.cpp.
Entree & Ecrire::interpreter (Entree & is) [virtual]
Lit le nom d'un objet dans is
Ecrit l'objet correspondant sur la sortie standard.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Interprete.
Definition at line 80 of file Ecrire.cpp.
References Cout, finl, Process::me(), Process::nproc(), and Interprete::objet().
{
  Nom nom1;
  is >> nom1;
  if (nproc() > 1)
    {
      Cout << "Ecrire::interpreter " << nom1 << " not done in parallel !" << finl;
    }
  else
    {
      Objet_U& ob1=objet(nom1);
      Cout << "["<<Process::me()<<"] "<< ob1 << finl;
    }
  return is;
}
Sortie & Ecrire::printOn (Sortie & x) const [protected, virtual]
appel a la methode printOn de la classe Interprete
Reimplemented from Interprete.
Definition at line 41 of file Ecrire.cpp.
{
  return Interprete::printOn(os);
}
Entree & Ecrire::readOn (Entree & is) [protected, virtual]
appel a la methode readOn de la classe Interprete
Reimplemented from Interprete.
Definition at line 60 of file Ecrire.cpp.
{
  return Interprete::readOn(is);
}
Ecrire & Ecrire::self_cast (Objet_U & r) [static]
Reimplemented from Interprete.
Definition at line 25 of file Ecrire.cpp.
const Ecrire & Ecrire::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete.
Definition at line 25 of file Ecrire.cpp.
unsigned Ecrire::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 25 of file Ecrire.cpp.
Member Data Documentation
const Type_info Ecrire::info_obj [static]
Reimplemented from Interprete.
Definition at line 39 of file Ecrire.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Ecrire.h
src/Kernel/Utilitaires/Ecrire.cpp