TRUST: Champ_Fonc_Tabule Class Reference
Champ_Fonc_Tabule Class Reference
Classe Champ_Fonc_Tabule
Classe derivee de Champ_Fonc_base qui represente les
champs fonctions d'un autre champ par tabulation
L'objet porte un membre de type Champ_Fonc qui stocke
les valeurs du champ tabule.
#include <Champ_Fonc_Tabule.h>
Public Member Functions
Champ_Fonc_Tabule ()
~Champ_Fonc_Tabule ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (const double un_temps) override
Initialisation du champ.
void mettre_a_jour (double un_temps) override
Effectue une mise a jour en temps.
void associer_zone_dis_base (const Zone_dis_base &) override
Associe une Zone discretisee au champ.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ.
(version const)
const Zone_dis_base & zone_dis_base () const override
Renvoie la Zone discretisee associee.
const Champ_Fonc & le_champ_tabule_discretise () const
Renvoie le champ tabule calcule.
(version const)
Champ_Fonc & le_champ_tabule_discretise ()
const Table & table () const
Table & table ()
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const override
Effectue le postraitement au format lml
Simple appel a Champ_Fonc::postraiter_lml(Sortie&,const Motcle&) const.
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const override
renvoie la compo eme valeur aux sommets de dom.
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const override
renvoie les valeurs aux sommets du Domaine dom
Noms & noms_champs_parametre ()
Noms & noms_problemes ()
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Champ_base & affecter_ (const Champ_base &) override
Public Member Functions inherited from Champ_Fonc_base
Champ_Fonc_base ()
~Champ_Fonc_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps du champ.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
Reprise a partir d'un flot d'entree
Lit le temps et les valeurs du champ.
Saute un bloc si le nom du champ est "anonyme".
int sauvegarder (Sortie &) const override
Sauvegarde le champ sur un flot de sortie
Ecrit le nom, le temps et les valeurs.
Champ_base & affecter_ (const Champ_base &) override
Affecte un Champ_base dans un Champ_Fonc_base.
Champ_base & affecter_compo (const Champ_base &, int compo) override
Affecte une composante d'un Champ_base dans la meme composnate
d'un Champ_Fonc_base.
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
const Domaine & domaine () const
int a_une_zone_dis_base () const override
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void creer_espace_distant (int dummy)
Public Member Functions inherited from Champ_Don_base
Champ_Don_base ()
~Champ_Don_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps.
Parametre: double
Signification: le temps de mise a jour.
void dimensionner (int, int)
Fixe le nombre de composantes et le nombre de valeurs nodales.
Parametre: int
Signification: le nombre de noeud par composante du champ (le nombre de dl par composante)
Parametre: int
Signification: le nombre de composante du champ.
int imprime (Sortie &, int) const override
NE FAIT RIEN. EXIT ! A surcharger dans les classes derivees.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
NE FAIT RIEN. A surcharger dans les classes derivees.
int sauvegarder (Sortie &) const override
NE FAIT RIEN. A surcharger dans les classes derivees.
DoubleTab & valeurs () override
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
const DoubleTab & valeurs () const override
Champ_base & affecter_ (const Champ_base &) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
Champ_base & affecter_compo (const Champ_base &, int) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
virtual int initialiser (const double temps)
NE FAIT RIEN. A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire.
int nb_valeurs_nodales () const override
Renvoie le nombre de degre de liberte par composante: le nombre de noeuds.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Fonc_Tabule & self_cast (Objet_U &)
static const Champ_Fonc_Tabule & self_cast (const Objet_U &)
static void Warn_old_chp_fonc_syntax (const char *nom_class, const Nom &val1, const Nom &val2, int &dim, Nom &param)
static void Warn_old_chp_fonc_syntax_V_184 (const char *nom_class, const Nom &val, int &dim, int &old_synt)
static bool Check_if_int (const Nom &val)
Static Public Member Functions inherited from Champ_Fonc_base
static const Type_info * info ()
static Champ_Fonc_base & self_cast (Objet_U &)
static const Champ_Fonc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Don_base
static const Type_info * info ()
static Champ_Don_base & self_cast (Objet_U &)
static const Champ_Don_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Fonc_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_Don_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture du Champ a partir d'un flot d'entree,
(On ne sait traiter que les champs scalaires.)
exemple:
Champ_Fonc_Tabule {probleme ch }
1 (nombre de composantes)
{
2
0 500 0 250 (ch(0)=0 && ch(500)=250
}.
Protected Member Functions inherited from Champ_Fonc_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void creer_tableau_distribue (const MD_Vector &, Array_base::Resize_Options=Array_base::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Noms noms_champs_parametre_
Noms noms_pbs_
Nom nom_domaine
Table la_table
Champ_Fonc le_champ_tabule_dis
Protected Attributes inherited from Champ_Don_base
DoubleTab valeurs_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
Classe Champ_Fonc_Tabule
Classe derivee de Champ_Fonc_base qui represente les
champs fonctions d'un autre champ par tabulation
L'objet porte un membre de type Champ_Fonc qui stocke
les valeurs du champ tabule.
Definition at line 36 of file Champ_Fonc_Tabule.h.
Constructor & Destructor Documentation
Champ_Fonc_Tabule()
Champ_Fonc_Tabule::Champ_Fonc_Tabule ()
Definition at line 21 of file Champ_Fonc_Tabule.cpp.
~Champ_Fonc_Tabule()
Champ_Fonc_Tabule::~Champ_Fonc_Tabule ()
Definition at line 21 of file Champ_Fonc_Tabule.cpp.
Member Function Documentation
affecter_()
Champ_base & Champ_Fonc_Tabule::affecter_ (const Champ_base & ch) override virtual
Implements Champ_base.
Definition at line 177 of file Champ_Fonc_Tabule.cpp.
{
  if(!le_champ_tabule_discretise().non_nul())
    Cerr << le_nom() << "type : " << que_suis_je()
         << " can not be assigned to " << ch.le_nom()
         << " because " << le_nom() << " is incomplete " << finl;
  else
    {
      if(sub_type(Champ_Uniforme, ch))
        valeurs()=ch.valeurs()(0,0);
      else
        valeurs()=ch.valeurs();
    }
  return *this;
}
References Cerr, finl, le_champ_tabule_discretise(), Field_base::le_nom(), Objet_U::que_suis_je(), sub_type, valeurs(), and Champ_Proto::valeurs().
associer_zone_dis_base()
void Champ_Fonc_Tabule::associer_zone_dis_base (const Zone_dis_base & zone_dis) inline override virtual
Associe une Zone discretisee au champ.
Reimplemented from Champ_base.
Definition at line 168 of file Champ_Fonc_Tabule.h.
{
  le_champ_tabule_discretise().associer_zone_dis_base(zone_dis);
}
References Champ_Fonc::associer_zone_dis_base(), and le_champ_tabule_discretise().
Check_if_int()
bool Champ_Fonc_Tabule::Check_if_int (const Nom & val) static
Definition at line 60 of file Champ_Fonc_Tabule.cpp.
{
  std::string s((const char*)val);
// lambda checking whehter a char is not a digit:
  auto checkNotDig = [](unsigned char c) {  return !std::isdigit(c); };
  return (!s.empty() && std::find_if(s.begin(), s.end(), checkNotDig) == s.end());
}
Referenced by Warn_old_chp_fonc_syntax(), and Warn_old_chp_fonc_syntax_V_184().
cree_instance()
Objet_U * Champ_Fonc_Tabule::cree_instance () static
Definition at line 21 of file Champ_Fonc_Tabule.cpp.
duplique()
int Champ_Fonc_Tabule::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Champ_Fonc_Tabule.cpp.
get_info()
const Type_info * Champ_Fonc_Tabule::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 21 of file Champ_Fonc_Tabule.cpp.
info()
const Type_info * Champ_Fonc_Tabule::info () static
Definition at line 21 of file Champ_Fonc_Tabule.cpp.
initialiser()
int Champ_Fonc_Tabule::initialiser (const double un_temps) inline override virtual
Initialisation du champ.
Reimplemented from Champ_Don_base.
Definition at line 109 of file Champ_Fonc_Tabule.h.
{
  le_champ_tabule_discretise().initialiser(un_temps);
  return 1;
}
References Champ_Fonc::initialiser(), and le_champ_tabule_discretise().
le_champ_tabule_discretise() [1/2]
Champ_Fonc & Champ_Fonc_Tabule::le_champ_tabule_discretise () inline
Definition at line 49 of file Champ_Fonc_Tabule.h.
{ return le_champ_tabule_dis; }
References le_champ_tabule_dis.
le_champ_tabule_discretise() [2/2]
const Champ_Fonc & Champ_Fonc_Tabule::le_champ_tabule_discretise () const inline
Renvoie le champ tabule calcule.
(version const)
Returns
Champ_Fonc&
Signification: le champ tabule calcule
Contraintes: reference constante
Definition at line 254 of file Champ_Fonc_Tabule.h.
{
  if(!le_champ_tabule_dis.non_nul())
    {
      Cerr << "The attribute le_champ_tabule_dis of Champ_fonc_tabule " << le_nom() << " is not filled." << finl;
      exit();
    }
  return le_champ_tabule_dis;
}
References Cerr, Process::exit(), finl, le_champ_tabule_dis, Field_base::le_nom(), and O_U_Ptr::non_nul().
Referenced by affecter_(), associer_zone_dis_base(), initialiser(), mettre_a_jour(), VDF_discretisation::modifier_champ_tabule(), VEF_discretisation::modifier_champ_tabule(), EF_discretisation::modifier_champ_tabule(), PolyMAC_discretisation::modifier_champ_tabule(), valeur_a_elem_compo(), valeur_aux_elems(), valeur_aux_sommets(), valeur_aux_sommets_compo(), valeurs(), and zone_dis_base().
mettre_a_jour()
void Champ_Fonc_Tabule::mettre_a_jour (double un_temps) inline override virtual
Effectue une mise a jour en temps.
Reimplemented from Champ_base.
Definition at line 89 of file Champ_Fonc_Tabule.h.
{
  le_champ_tabule_discretise().mettre_a_jour(un_temps);
  Champ_Fonc_base::mettre_a_jour(un_temps);
}
References le_champ_tabule_discretise(), Champ_Fonc_base::mettre_a_jour(), and Champ_Fonc::mettre_a_jour().
noms_champs_parametre()
Noms & Champ_Fonc_Tabule::noms_champs_parametre () inline
Definition at line 57 of file Champ_Fonc_Tabule.h.
{ return noms_champs_parametre_; };
References noms_champs_parametre_.
noms_problemes()
Noms & Champ_Fonc_Tabule::noms_problemes () inline
Definition at line 58 of file Champ_Fonc_Tabule.h.
{ return noms_pbs_; };
References noms_pbs_.
printOn()
Sortie & Champ_Fonc_Tabule::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 68 of file Champ_Fonc_Tabule.cpp.
{
  return os;
}
readOn()
Entree & Champ_Fonc_Tabule::readOn (Entree & is) override protected virtual
Lecture du Champ a partir d'un flot d'entree,
(On ne sait traiter que les champs scalaires.)
exemple:
Champ_Fonc_Tabule {probleme ch }
1 (nombre de composantes)
{
2
0 500 0 250 (ch(0)=0 && ch(500)=250
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 96 of file Champ_Fonc_Tabule.cpp.
{
  int nbcomp, old_table_syntax_ = 0;
  Nom motlu;
  const Motcle accolade_ouverte("{"), accolade_fermee("}");
  is >> motlu;
  if (motlu != accolade_ouverte)
    {
      noms_champs_parametre_.add(motlu);
      old_table_syntax_ = 1;
    }
  else
    {
      assert (old_table_syntax_ == 0);
      while (true)
        {
          is >> motlu;
          if (motlu == "}") break;
          noms_pbs_.add(motlu);
          is >> motlu;
          noms_champs_parametre_.add(motlu);
        }
    }
  const int nb_param = noms_champs_parametre_.size();
  if (old_table_syntax_ && noms_pbs_.size() != 0 && nb_param != 1)
    {
      Cerr << "What ??? Big problem in Champ_Fonc_Tabule::readOn !!!" << finl;
      throw;
    }
  is >> nbcomp;
  fixer_nb_comp(nbcomp);
  is >> motlu;
  if (motlu == accolade_ouverte)
    {
      /* 1. lecture de la grille de parametres */
      DoubleVects params;
      for (int n = 0; n < nb_param; n++)
        {
          const int nb_val = lire_dimension(is, que_suis_je());
          DoubleVect param(nb_val);
          for (int i = 0; i < nb_val; i++) is >> param[i];
          params.add(param);
        }
      /* 2. lecture des valeurs des parametres */
// taille totale du tableau de valeurs
      int size = nbcomp;
      for (int n = 0; n < nb_param; n++) size *= params[n].size();
// lecture : tout dans un tableau 1D
      DoubleVect tab_valeurs(size);
      for (int i = 0; i < size; i++) is >> tab_valeurs[i];
      la_table.remplir(params, tab_valeurs);
      is >> motlu;
      if (motlu != accolade_fermee)
        {
          Cerr << "Error reading from an object of type Champ_Fonc_Tabule" << finl;
          Cerr << "We expected keyword } instead of " << motlu << finl;
          exit();
        }
    }
  else if (motlu=="fonction")
    {
      Cerr<<"The syntax has changed..." << finl;
      Cerr<<"The syntax is now Champ_Fonc_fonction 1 field_expression"<<finl;
      exit();
      Cerr<<"We read the analytic function "<<finl;
      la_table.lire_f(is,0);
    }
  else
    {
      Cerr << "Error reading from an object of type Champ_Fonc_Tabule" << finl;
      Cerr << "We expected keyword { or fonction instead of " << motlu << finl;
      exit();
    }
  return is;
}
References TRUST_Vector< _TRUST_TABL_, _TYPE_ >::add(), Vect_Nom::add(), Cerr, Process::exit(), finl, Field_base::fixer_nb_comp(), la_table, Champ_Proto::lire_dimension(), Table::lire_f(), noms_champs_parametre_, noms_pbs_, Objet_U::que_suis_je(), Table::remplir(), and vect_impl::size().
self_cast() [1/2]
const Champ_Fonc_Tabule & Champ_Fonc_Tabule::self_cast (const Objet_U & r) static
Definition at line 21 of file Champ_Fonc_Tabule.cpp.
self_cast() [2/2]
Champ_Fonc_Tabule & Champ_Fonc_Tabule::self_cast (Objet_U & r) static
Definition at line 21 of file Champ_Fonc_Tabule.cpp.
table() [1/2]
Table & Champ_Fonc_Tabule::table () inline
Definition at line 51 of file Champ_Fonc_Tabule.h.
{ return la_table; }
References la_table.
table() [2/2]
const Table & Champ_Fonc_Tabule::table () const inline
Definition at line 50 of file Champ_Fonc_Tabule.h.
{ return la_table; }
References la_table.
Referenced by Sutherland::lire_expression(), VDF_discretisation::modifier_champ_tabule(), VEF_discretisation::modifier_champ_tabule(), EF_discretisation::modifier_champ_tabule(), and PolyMAC_discretisation::modifier_champ_tabule().
taille_memoire()
unsigned Champ_Fonc_Tabule::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Champ_Fonc_Tabule.cpp.
valeur_a_elem()
DoubleVect & Champ_Fonc_Tabule::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const inline override virtual
Effectue le postraitement au format lml
Simple appel a Champ_Fonc::postraiter_lml(Sortie&,const Motcle&) const.
Returns
int
Signification: code de retour propage
Contraintes:
Reimplemented from Champ_base.
Definition at line 192 of file Champ_Fonc_Tabule.h.
{
  return le_champ_tabule_discretise().valeur_a_elem(position, les_valeurs, le_poly);
}
valeur_a_elem_compo()
double Champ_Fonc_Tabule::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline override virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
Definition at line 218 of file Champ_Fonc_Tabule.h.
{
  return le_champ_tabule_discretise().valeur_a_elem_compo(position, le_poly, ncomp);
}
References le_champ_tabule_discretise(), and Champ_Fonc::valeur_a_elem_compo().
valeur_aux_elems()
DoubleTab & Champ_Fonc_Tabule::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const inline override virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 223 of file Champ_Fonc_Tabule.h.
{
  return le_champ_tabule_discretise().valeur_aux_elems(positions, les_polys, les_valeurs);
}
References le_champ_tabule_discretise(), and Champ_Fonc::valeur_aux_elems().
valeur_aux_sommets()
DoubleTab & Champ_Fonc_Tabule::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const inline override virtual
renvoie les valeurs aux sommets du Domaine dom
Reimplemented from Champ_base.
Definition at line 229 of file Champ_Fonc_Tabule.h.
{
  return le_champ_tabule_discretise().valeur_aux_sommets(dom, les_valeurs);
}
References le_champ_tabule_discretise(), and Champ_Fonc::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Fonc_Tabule::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int compo) const inline override virtual
renvoie la compo eme valeur aux sommets de dom.
Reimplemented from Champ_base.
Definition at line 233 of file Champ_Fonc_Tabule.h.
{
  return le_champ_tabule_discretise().valeur_aux_sommets_compo(dom, les_valeurs, compo);
}
References le_champ_tabule_discretise(), and Champ_Fonc::valeur_aux_sommets_compo().
valeurs() [1/2]
const DoubleTab & Champ_Fonc_Tabule::valeurs () const inline override virtual
Renvoie le tableau des valeurs du champ.
(version const)
Returns
DoubleTab&
Signification: le tableau des valeurs du champ
Contraintes: reference constante
Implements Champ_Proto.
Definition at line 149 of file Champ_Fonc_Tabule.h.
{
  return le_champ_tabule_discretise().valeurs();
}
References le_champ_tabule_discretise(), and Champ_Fonc::valeurs().
Referenced by affecter_().
valeurs() [2/2]
DoubleTab & Champ_Fonc_Tabule::valeurs () inline override virtual
Renvoie le tableau des valeurs du champ.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ
Contraintes:
Implements Champ_Proto.
Definition at line 129 of file Champ_Fonc_Tabule.h.
{
  return le_champ_tabule_discretise().valeurs();
}
References le_champ_tabule_discretise(), and Champ_Fonc::valeurs().
Warn_old_chp_fonc_syntax()
void Champ_Fonc_Tabule::Warn_old_chp_fonc_syntax (const char * nom_class, const Nom & val1, const Nom & val2, int & dim, Nom & param) static
< val1 is not a num - this is the correct new syntax
< Detect old syntax and inform user
Definition at line 27 of file Champ_Fonc_Tabule.cpp.
{
  const bool isNum = Check_if_int(val1);
  if (!isNum) //!< val1 is not a num - this is the correct new syntax
    {
      param = val1;
      dim = atoi(val2);
      return;
    }
  else   //!< Detect old syntax and inform user
    {
      Cerr << "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" << finl;
      Cerr << "Error in call to " << nom_class << ":" << finl;
      Cerr << "The syntax has changed in version 1.8.2." << finl;
      Cerr << "You should now pass the dimension/number of components AFTER the field/parameter name." << finl;
      Cerr << "Please update your dataset or contact TRUST support team." << finl;
      Process::exit();
    }
}
References Cerr, Check_if_int(), Process::exit(), and finl.
Referenced by Champ_Fonc_Fonction_txyz_Morceaux::readOn().
Warn_old_chp_fonc_syntax_V_184()
void Champ_Fonc_Tabule::Warn_old_chp_fonc_syntax_V_184 (const char * nom_class, const Nom & val, int & dim, int & old_synt) static
< old syntax
Definition at line 47 of file Champ_Fonc_Tabule.cpp.
{
  const bool isNum = Check_if_int(val);
  if (isNum) //!< old syntax
    {
      Cerr << "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" << finl;
      Cerr << "Attention : you are using an old syntax for the class " << nom_class << " :" << finl;
      Cerr << "We are trying to fix this ..." << finl;
      dim = atoi(val);
      old_synt = 1;
    }
}
References Cerr, Check_if_int(), and finl.
Referenced by Champ_Fonc_Fonction::readOn(), and Champ_Fonc_Fonction_txyz::readOn().
zone_dis_base()
const Zone_dis_base & Champ_Fonc_Tabule::zone_dis_base () const inline override virtual
Renvoie la Zone discretisee associee.
Returns
Zone_dis_base&
Signification: la Zone discretisee associee
Contraintes: reference constante
Reimplemented from Champ_base.
Definition at line 187 of file Champ_Fonc_Tabule.h.
{
  return le_champ_tabule_discretise().zone_dis_base();
}
References le_champ_tabule_discretise(), and Champ_Fonc::zone_dis_base().
Member Data Documentation
info_obj
const Type_info Champ_Fonc_Tabule::info_obj static
Definition at line 38 of file Champ_Fonc_Tabule.h.
la_table
Table Champ_Fonc_Tabule::la_table protected
Definition at line 71 of file Champ_Fonc_Tabule.h.
Referenced by Champ_Fonc_Fonction::readOn(), Champ_Fonc_Fonction_txyz::readOn(), readOn(), and table().
le_champ_tabule_dis
Champ_Fonc Champ_Fonc_Tabule::le_champ_tabule_dis protected
Definition at line 72 of file Champ_Fonc_Tabule.h.
Referenced by le_champ_tabule_discretise().
nom_domaine
Nom Champ_Fonc_Tabule::nom_domaine protected
Definition at line 70 of file Champ_Fonc_Tabule.h.
noms_champs_parametre_
Noms Champ_Fonc_Tabule::noms_champs_parametre_ protected
Definition at line 69 of file Champ_Fonc_Tabule.h.
Referenced by noms_champs_parametre(), Champ_Fonc_Fonction::readOn(), Champ_Fonc_Fonction_txyz::readOn(), and readOn().
noms_pbs_
Noms Champ_Fonc_Tabule::noms_pbs_ protected
Definition at line 69 of file Champ_Fonc_Tabule.h.
Referenced by noms_problemes(), Champ_Fonc_Fonction::readOn(), Champ_Fonc_Fonction_txyz::readOn(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Fonc_Tabule.h
src/Kernel/Champs/Champ_Fonc_Tabule.cpp