TRUST: Champ_Face Class Reference
Champ_Face Class Reference
class Champ_Face
Cette classe sert a representer un champ vectoriel dont on ne calcule
que les composantes normales aux faces.Il n'y a donc qu'un degre de
liberte par face et l'attribut nb_comp_ d'un objet de type Champ_Face
vaut 1. On peut neammoins imposer toutes les composantes du champ sur
le bord. Si n est le nombre de faces total de la zone et nb_faces_bord
le nombre de faces de bord le tableau de valeurs associe au champ
est construit comme suit:
- n valeurs pour representer les composantes normales aux faces
- nb_faces_bord*dimension pour stocker les valeurs imposees
sur les faces de bord
Rq : cette classe est specifique au module VDF
#include <Champ_Face.h>
Public Member Functions
Champ_Face ()
~Champ_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
int fixer_nb_valeurs_nodales (int) override
const Zone_dis_base & zone_dis_base () const override
const Zone_VDF & zone_vdf () const override
Champ_base & affecter_ (const Champ_base &) override
Affectation d'un Champ generique (Champ_base) dans
un champ inconnue.
virtual const Champ_Proto & affecter (const double x1, const double x2)
virtual const Champ_Proto & affecter (const double x1, const double x2, const double x3)
virtual const Champ_Proto & affecter (const DoubleTab &)
void verifie_valeurs_cl () override
int compo_normale_sortante (int) const
const DoubleTab & tau_diag () const
const DoubleTab & tau_croises () const
DoubleTab & tau_diag ()
DoubleTab & tau_croises ()
void dimensionner_tenseur_Grad ()
void calculer_dercov_axi (const Zone_Cl_VDF &)
void calculer_rotationnel_ordre2_centre_element (DoubleTab &) const
int imprime (Sortie &, int) const override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps du champ inconnue.
WEC : Maintenant si on l'appelle 2 fois de suite avec le meme
argument, la 2eme ne fait rien.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &tab_valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &tab_valeurs, int ncomp) const override
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const override
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
NE FAIT RIEN
Methode a surcharger.
void calculer_dscald_centre_element (DoubleTab &) const
void calcul_critere_Q (DoubleTab &, const Zone_Cl_VDF &)
void calcul_grad_u (const DoubleTab &, DoubleTab &, const Zone_Cl_VDF &)
void calcul_y_plus (DoubleTab &, const Zone_Cl_VDF &)
DoubleTab & calcul_duidxj (const DoubleTab &, DoubleTab &) const
DoubleTab & calcul_duidxj (const DoubleTab &, DoubleTab &, const Zone_Cl_VDF &) const
DoubleVect & calcul_S_barre (const DoubleTab &, DoubleVect &, const Zone_Cl_VDF &) const
DoubleVect & calcul_S_barre_sans_contrib_paroi (const DoubleTab &, DoubleVect &, const Zone_Cl_VDF &) const
Public Member Functions inherited from Champ_Inc_base
~Champ_Inc_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_Inc_base ()
int fixer_nb_valeurs_nodales (int) override
double changer_temps (const double temps) override
Fixe le temps du champ.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps du champ inconnue.
WEC : Maintenant si on l'appelle 2 fois de suite avec le meme
argument, la 2eme ne fait rien.
int reprendre (Entree &) override
Lecture d'un champ inconnue a partir d'un flot d'entree
en vue d'une reprise.
int sauvegarder (Sortie &) const override
Sauvegarde le champ inconnue sur un flot de sortie.
Ecrit un identifiant, les valeurs du champs, et
la date (le temps au moment de la sauvegarde).
Champ_base & affecter_compo (const Champ_base &, int compo) override
Affectation d'une composante d'un Champ quelconque<br>(Champ_base) dans une composante d'un champ inconnue.
Champ_base & affecter_ (const Champ_base &) override
Affectation d'un Champ generique (Champ_base) dans
un champ inconnue.
virtual void verifie_valeurs_cl ()
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ au temps courant.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temp courant<br>(version const)
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
Calcule la valeur du champs inconnue a la position specifiee.
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
Calcule les valeurs du champs inconnue aux positions specifiees.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
Calcule les valeurs du champs inconnue aux positions specifiees,
pour une certaine composante du champ.
int nb_valeurs_nodales () const override
Returns the number of "real" geometric positions of the
degrees of freedom, or -1 if not applicable (fields with multiple
localisations)
virtual int fixer_nb_valeurs_temporelles (int)
Fixe le nombre de valeurs temporelles a conserver.
(un nombre different suivant le schema en temps utilise)
Appelle Roue::fixer_nb_cases(int)
virtual int nb_valeurs_temporelles () const
Renvoie le nombre de valeurs temporelles actuellement conservees.
Cette valeur est stockee par la Roue du Champ_Inc_base.
double changer_temps_futur (double, int i=1)
Fixe le temps du ieme champ futur.
double changer_temps_passe (double, int i=1)
Fixe le temps du ieme champ passe.
double recuperer_temps_futur (int i=1) const
Retourne le temps du ieme champ futur.
double recuperer_temps_passe (int i=1) const
Retourne le temps du ieme champ passe.
DoubleTab & valeurs (double temps) override
Renvoie les valeurs du champs a l'instant temps.
const DoubleTab & valeurs (double temps) const override
Renvoie les valeurs du champs a l'instant temps.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
DoubleTab & futur (int i=1) override
Renvoie les valeurs du champs a l'instant t+i.
const DoubleTab & futur (int i=1) const override
Renvoie les valeurs du champs a l'instant t+i.
(version const)
DoubleTab & passe (int i=1) override
Renvoie les valeurs du champs a l'instant t-i.
const DoubleTab & passe (int i=1) const override
Renvoie les valeurs du champs a l'instant t-i.
(version const)
Champ_Inc_base & avancer (int i=1)
Avance le pointeur courant de i pas de temps,
dans la liste des valeurs temporelles conservees.
Champ_Inc_base & reculer (int i=1)
Recule le pointeur courant de i pas de temps,
dans la liste des valeurs temporelles conservees.
int lire_donnees (Entree &)
Lit les valeurs du champs a partir d'un flot d'entree.
Format de lecture:
int [LE NOMBRE DE VALEURS A LIRE]
[LIRE LE NOMBRE DE VALEUR VOULUES].
virtual void associer_eqn (const Equation_base &)
Associe le champ a l'equation dont il represente une inconnue.
Simple appel a MorEqn::associer_eqn(const Equation_base&)
virtual void associer_zone_cl_dis (const Zone_Cl_dis &)
int imprime (Sortie &, int) const override
int a_une_zone_dis_base () const override
Par defaut, on ne sait pas si une zone_dis_base sera definie.
const Zone_Cl_dis & zone_Cl_dis () const
Zone_Cl_dis & zone_Cl_dis ()
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
NE FAIT RIEN
Methode a surcharger.
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
Simple appel a:
Champ_Inc_base::remplir_coord_noeuds_et_polys(DoubleTab&,IntVect& poly)
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const =0
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
Simple appel a
Champ_Inc_base::remplir_coord_noeuds(DoubleTab&)
virtual double integrale_espace (int ncomp) const
const Domaine & domaine () const
const tabs_t & derivees () const
void init_champ_calcule (const Objet_U &obj, fonc_calc_t fonc)
void reset_champ_calcule ()
DoubleTab valeur_aux_bords () const override
renvoie la valeur du champ aux faces de bord
virtual void creer_espace_distant (int dummy)
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champ_Face_implementation
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const override
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
int imprime_Face (Sortie &, int) const
Public Member Functions inherited from Champ_implementation
virtual ~Champ_implementation ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const =0
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const =0
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Face & self_cast (Objet_U &)
static const Champ_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Inc_base
static const Type_info * info ()
static Champ_Inc_base & self_cast (Objet_U &)
static const Champ_Inc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Inc_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Entree & readOn (Entree &) override
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Protected Member Functions inherited from Champ_Inc_base
Sortie & printOn (Sortie &x) const override
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Entree & readOn (Entree &) override
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
virtual void creer_tableau_distribue (const MD_Vector &, Array_base::Resize_Options=Array_base::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Champ_Face_implementation
virtual const Zone_VDF & zone_vdf () const =0
double interpolation (const double, const double, const double) const
DoubleTab & trace (const Frontiere_dis_base &fr, const DoubleTab &y, DoubleTab &x, int distant) const
Protected Member Functions inherited from Champ_implementation
virtual const Champ_base & le_champ () const =0
virtual Champ_base & le_champ ()=0
const Zone & zone () const
virtual const Zone_dis_base & zone_dis_base () const
Private Member Functions
double val_imp_face_bord_private (int face, int comp) const
double val_imp_face_bord_private (int face, int comp1, int comp2) const
const Champ_base & le_champ () const override
Champ_base & le_champ () override
Private Attributes
Ref_Zone_VDF la_zone_VDF
DoubleTab tau_diag_
termes diagonaux du tenseur Grad
DoubleTab tau_croises_
termes extradiagonaux du tenseur Grad
Additional Inherited Members
Protected Attributes inherited from Champ_Inc_base
Roue_ptr les_valeurs
Ref_Zone_Cl_dis ma_zone_cl_dis
fonc_calc_t fonc_calc_
int fonc_calc_init_ = 0
Ref_Objet_U obj_calc_
DoubleTab val_bord_
tabs_t deriv_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Champ_Face
Cette classe sert a representer un champ vectoriel dont on ne calcule
que les composantes normales aux faces.Il n'y a donc qu'un degre de
liberte par face et l'attribut nb_comp_ d'un objet de type Champ_Face
vaut 1. On peut neammoins imposer toutes les composantes du champ sur
le bord. Si n est le nombre de faces total de la zone et nb_faces_bord
le nombre de faces de bord le tableau de valeurs associe au champ
est construit comme suit:
- n valeurs pour representer les composantes normales aux faces
- nb_faces_bord*dimension pour stocker les valeurs imposees
sur les faces de bord
Rq : cette classe est specifique au module VDF
Definition at line 43 of file Champ_Face.h.
Constructor & Destructor Documentation
Champ_Face()
Champ_Face::Champ_Face ()
Definition at line 29 of file Champ_Face.cpp.
~Champ_Face()
Champ_Face::~Champ_Face ()
Definition at line 29 of file Champ_Face.cpp.
Member Function Documentation
affecter() [1/3]
const Champ_Proto & Champ_Face::affecter (const double x1, const double x2) virtual
Definition at line 186 of file Champ_Face.cpp.
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const IntVect& orientation = zone_VDF.orientation();
  DoubleTab& val = valeurs();
  for (int num_face=0; num_face<val.size(); num_face++)
    {
      int ori = orientation(num_face);
      switch(ori)
        {
        case 0 :
          val(num_face)=x1;
          break;
        case 1 :
          val(num_face)=x2;
          break;
        }
    }
  return *this;
}
References la_zone_VDF, Zone_VDF::orientation(), TRUSTVect< _TYPE_ >::size(), Ref_Zone_VDF::valeur(), and Champ_Inc_base::valeurs().
affecter() [2/3]
const Champ_Proto & Champ_Face::affecter (const double x1, const double x2, const double x3) virtual
Definition at line 207 of file Champ_Face.cpp.
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const IntVect& orientation = zone_VDF.orientation();
  DoubleTab& val = valeurs();
  for (int num_face=0; num_face<val.size(); num_face++)
    {
      int ori = orientation(num_face);
      switch(ori)
        {
        case 0 :
          val(num_face)=x1;
          break;
        case 1 :
          val(num_face)=x2;
          break;
        case 2 :
          val(num_face)=x3;
          break;
        }
    }
  return *this;
}
References la_zone_VDF, Zone_VDF::orientation(), TRUSTVect< _TYPE_ >::size(), Ref_Zone_VDF::valeur(), and Champ_Inc_base::valeurs().
affecter() [3/3]
const Champ_Proto & Champ_Face::affecter (const DoubleTab & v) virtual
Definition at line 232 of file Champ_Face.cpp.
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const IntVect& orientation = zone_VDF.orientation();
  DoubleTab& val = valeurs();
  if (v.nb_dim() == 2)
    {
      if (v.dimension(1) == dimension)
        {
          if (v.dimension(0) == val.size())
            for (int num_face=0; num_face<val.size(); num_face++)
              val(num_face)=v(num_face,orientation(num_face));
          else
            {
              Cerr << "Erreur TRUST dans Champ_Face::affecter(const DoubleTab& )" << finl;
              Cerr << "les dimensions du DoubleTab passe en parametre sont incompatibles " << finl;
              Cerr << "avec celles du Champ_Face " << finl;
              exit();
            }
        }
      else
        {
          Cerr << "Erreur TRUST dans Champ_Face::affecter(const DoubleTab& )" << finl;
          Cerr << "les dimensions du DoubleTab passe en parametre sont incompatibles " << finl;
          Cerr << "avec celles du Champ_Face " << finl;
          exit();
        }
    }
  return *this;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Process::exit(), finl, la_zone_VDF, TRUSTTab< _TYPE_ >::nb_dim(), Zone_VDF::orientation(), TRUSTVect< _TYPE_ >::size(), Ref_Zone_VDF::valeur(), and Champ_Inc_base::valeurs().
affecter_()
Champ_base & Champ_Face::affecter_ (const Champ_base & ch) override virtual
Affectation d'un Champ generique (Champ_base) dans
un champ inconnue.
Returns
Champ_base&
Signification: le resultat de l'affectation (*this)
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 83 of file Champ_Face.cpp.
{
  const DoubleTab& v = ch.valeurs();
  DoubleTab& val = valeurs();
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  int nb_faces = zone_VDF.nb_faces();
  const IntVect& orientation = zone_VDF.orientation();
  int ori, n0, n1;
  if (sub_type(Champ_Uniforme,ch))
    {
      for (int num_face=0; num_face<nb_faces; num_face++)
        val(num_face) = v(0,orientation(num_face));
    }
  else if ( (sub_type(Champ_Uniforme_Morceaux,ch))
            || (sub_type(Champ_Don_lu,ch)) )
    {
      int ndeb_int = zone_VDF.premiere_face_int();
      const IntTab& face_voisins = zone_VDF.face_voisins();
      int num_face;
      for (num_face=0; num_face<ndeb_int; num_face++)
        {
          ori = orientation(num_face);
          n0 = face_voisins(num_face,0);
          if (n0 != -1)
            val(num_face) = v(n0,ori);
          else
            val(num_face) = v(face_voisins(num_face,1),ori);
        }
      for (num_face=ndeb_int; num_face<nb_faces; num_face++)
        {
          ori = orientation(num_face);
          n0 = face_voisins(num_face,0);
          n1 = face_voisins(num_face,1);
          val(num_face) = 0.5*(v(n0,ori)+v(n1,ori));
        }
    }
  else
    {
// int ndeb_int = zone_VDF.premiere_face_int();
// const IntTab& face_voisins = zone_VDF.face_voisins();
      DoubleTab positionX(zone_VDF.nb_faces_X() ,dimension);
      DoubleVect U(zone_VDF.nb_faces_X());
      DoubleTab positionY(zone_VDF.nb_faces_Y() ,dimension);
      DoubleVect V(zone_VDF.nb_faces_Y());
      DoubleTab positionZ(zone_VDF.nb_faces_Z() ,dimension);
      DoubleVect W(zone_VDF.nb_faces_Z());
      const DoubleTab& xv=zone_VDF.xv();
      int nbx=0;
      int nby=0;
      int nbz=0;
      int num_face, k;
      for (num_face=0; num_face<nb_faces; num_face++)
        {
          ori = orientation(num_face);
          switch(ori)
            {
            case 0:
              for(k=0; k<dimension; k++)
                positionX(nbx, k)=xv(num_face, k);
              nbx++;
              break;
            case 1:
              for(k=0; k<dimension; k++)
                positionY(nby, k)=xv(num_face, k);
              nby++;
              break;
            case 2:
              for(k=0; k<dimension; k++)
                positionZ(nbz, k)=xv(num_face, k);
              nbz++;
              break;
            }
        }
      ch.valeur_aux_compo(positionX, U, 0);
      ch.valeur_aux_compo(positionY, V, 1);
      if(dimension == 3)
        ch.valeur_aux_compo(positionZ, W, 2);
      nbx=nby=nbz=0;
      for (num_face=0; num_face<nb_faces; num_face++)
        {
          ori = orientation(num_face);
          switch(ori)
            {
            case 0:
              val(num_face) = U(nbx++);
              break;
            case 1:
              val(num_face) = V(nby++);
              break;
            case 2:
              val(num_face) = W(nbz++);
              break;
            }
        }
    }
  return *this;
}
References Objet_U::dimension, Zone_VF::face_voisins(), la_zone_VDF, Zone_VF::nb_faces(), Zone_VDF::nb_faces_X(), Zone_VDF::nb_faces_Y(), Zone_VDF::nb_faces_Z(), Zone_VDF::orientation(), Zone_VF::premiere_face_int(), sub_type, Ref_Zone_VDF::valeur(), Champ_base::valeur_aux_compo(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Zone_VF::xv().
associer_zone_dis_base()
void Champ_Face::associer_zone_dis_base (const Zone_dis_base & z_dis) override virtual
Reimplemented from Champ_base.
Definition at line 59 of file Champ_Face.cpp.
{
  la_zone_VDF=ref_cast(Zone_VDF, z_dis);
}
References la_zone_VDF, and ref_cast.
Referenced by EOS_Tools_VDF::associer_zones().
calcul_critere_Q()
void Champ_Face::calcul_critere_Q (DoubleTab & Q, const Zone_Cl_VDF & zone_Cl_VDF)
Definition at line 512 of file Champ_Face3.cpp.
{
// Q=0.5*(\Omega_{ij}*\Omega_{ij}-S_{ij}*S_{ij})=-0.25*du_i/dx_j*du_j/dx_i
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const int nb_elem = zone_VDF.nb_elem();
  const int nb_elem_tot = zone_VDF.nb_elem_tot();
  int num_elem,i,j;
  double crit,deriv1,deriv2;
  DoubleTab gradient_elem(nb_elem_tot,dimension,dimension);
  gradient_elem=0.;
  Champ_Face& vit = *this;
  const DoubleTab& vitesse = valeurs();
  vit.calcul_duidxj(vitesse,gradient_elem,zone_Cl_VDF);
  for (num_elem=0; num_elem<nb_elem; num_elem++)
    {
      crit = 0.;
      for (i=0; i<dimension; i++)
        for(j=0; j<dimension; j++)
          {
            deriv1 = gradient_elem(num_elem,i,j);
            deriv2 = gradient_elem(num_elem,j,i);
            crit += -0.25*deriv1*deriv2;
          }
      Q[num_elem] = crit;
    }
}
References calcul_duidxj(), Objet_U::dimension, la_zone_VDF, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Ref_Zone_VDF::valeur(), and Champ_Inc_base::valeurs().
Referenced by Critere_Q_Champ_Face::me_calculer().
calcul_duidxj() [1/2]
DoubleTab & Champ_Face::calcul_duidxj (const DoubleTab & in_vel, DoubleTab & gij) const
Definition at line 987 of file Champ_Face3.cpp.
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  int nb_elem_tot = zone_VDF.zone().nb_elem_tot();
  const IntTab& face_voisins = zone_VDF.face_voisins();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  int element_number;
  int num0,num1,num2,num3,num4,num5;
  int f0,f1,f2,f3,f4,f5;
  //
  // Calculate the Sij tensor
  //
  if (dimension ==2)
    {
      for (element_number=0 ; element_number<nb_elem_tot ; element_number ++)
        {
          f0 = elem_faces(element_number,0);
          num0 = face_voisins(f0,0);
          if (num0 == -1)
            num0 = element_number;
          f1 = elem_faces(element_number,1);
          num1 = face_voisins(f1,0);
          if (num1 == -1)
            num1 = element_number;
          f2 = elem_faces(element_number,2);
          num2 = face_voisins(f2,1);
          if (num2 == -1)
            num2 = element_number;
          f3 = elem_faces(element_number,3);
          num3 = face_voisins(f3,1);
          if (num3 == -1)
            num3 = element_number;
          gij(element_number,0,0)=0.5*((in_vel(num2,0)-in_vel(num0,0))/
                                       zone_VDF.dim_elem(element_number,0));
          gij(element_number,0,1) = 0.5*((in_vel(num3,0)-in_vel(num1,0))/zone_VDF.dim_elem(element_number,1));
          gij(element_number,1,0) = 0.5*((in_vel(num2,1)-in_vel(num0,1))/zone_VDF.dim_elem(element_number,0));
          gij(element_number,1,1)=0.5*((in_vel(num3,1)-in_vel(num1,1))/
                                       zone_VDF.dim_elem(element_number,1));
        }
    }
  else
    {
      for (element_number=0 ; element_number<nb_elem_tot ; element_number ++)
        {
          f0 = elem_faces(element_number,0);
          num0 = face_voisins(f0,0);
          if (num0 == -1)
            num0 = element_number;
          f1 = elem_faces(element_number,1);
          num1 = face_voisins(f1,0);
          if (num1 == -1)
            num1 = element_number;
          f2 = elem_faces(element_number,2);
          num2 = face_voisins(f2,0);
          if (num2 == -1)
            num2 = element_number;
          f3 = elem_faces(element_number,3);
          num3 = face_voisins(f3,1);
          if (num3 == -1)
            num3 = element_number;
          f4 = elem_faces(element_number,4);
          num4 = face_voisins(f4,1);
          if (num4 == -1)
            num4 = element_number;
          f5 = elem_faces(element_number,5);
          num5 = face_voisins(f5,1);
          if (num5 == -1)
            num5 = element_number;
          gij(element_number,0,0)=0.5*((in_vel(num3,0)-in_vel(num0,0))/
                                       zone_VDF.dim_elem(element_number,0));
          gij(element_number,0,1) = 0.5*((in_vel(num4,0)-in_vel(num1,0))/
                                         zone_VDF.dim_elem(element_number,1));
          gij(element_number,1,0) = 0.5*((in_vel(num3,1)-in_vel(num0,1))/
                                         zone_VDF.dim_elem(element_number,0));
          gij(element_number,0,2) =  0.5*((in_vel(num5,0)-in_vel(num2,0))/
                                          zone_VDF.dim_elem(element_number,2));
          gij(element_number,2,0) = 0.5*((in_vel(num3,2)-in_vel(num0,2))/
                                         zone_VDF.dim_elem(element_number,0));
          gij(element_number,1,1)=0.5*((in_vel(num4,1)-in_vel(num1,1))/
                                       zone_VDF.dim_elem(element_number,1));
          gij(element_number,1,2) = 0.5*((in_vel(num5,1)-in_vel(num2,1))/
                                         zone_VDF.dim_elem(element_number,2));
          gij(element_number,2,1) = 0.5*((in_vel(num4,2)-in_vel(num1,2))/
                                         zone_VDF.dim_elem(element_number,1));
          gij(element_number,2,2)=0.5*((in_vel(num5,2)-in_vel(num2,2))/
                                       zone_VDF.dim_elem(element_number,2));
        }
    }
  return gij;
}
References Zone_VDF::dim_elem(), Objet_U::dimension, Zone_VF::elem_faces(), f1, f2, Zone_VF::face_voisins(), la_zone_VDF, Zone::nb_elem_tot(), Ref_Zone_VDF::valeur(), and Zone_dis_base::zone().
Referenced by calcul_critere_Q(), calcul_grad_u(), and calcul_S_barre().
calcul_duidxj() [2/2]
DoubleTab & Champ_Face::calcul_duidxj (const DoubleTab & vitesse, DoubleTab & gij, const Zone_Cl_VDF & zone_Cl_VDF) const
< arete de type periodicite
< dui/dxj
< duj/dxi
< dui/dxj
< vitesse tangentielle Dans cette partie, on conserve le codage de Hyd_SGE_Wale_VDF (num1 et non num2) pour calculer la distance entre le centre de la maille et le bord.
Definition at line 675 of file Champ_Face3.cpp.
{
  const Champ_Face& vit = ref_cast(Champ_Face, mon_equation->inconnue().valeur());
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  int nb_elem = zone_VDF.zone().nb_elem_tot();
  const IntTab& face_voisins = zone_VDF.face_voisins();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  const IntTab& Qdm = zone_VDF.Qdm();
  const IntVect& orientation = zone_VDF.orientation();
  int premiere_arete_mixte = zone_VDF.premiere_arete_mixte();
  int premiere_arete_interne =  zone_VDF.premiere_arete_interne();
  int derniere_arete_mixte = premiere_arete_mixte+zone_VDF.nb_aretes_mixtes();
  int derniere_arete_interne = premiere_arete_interne+zone_VDF.nb_aretes_internes();
  int elem;
  int num_arete;
  IntVect element(4);
  int num0,num1,num2,num3,signe;
  int ndeb = zone_VDF.premiere_arete_bord();
  int nfin = ndeb + zone_VDF.nb_aretes_bord();
  int n_type;
  gij = 0.;
//
// On parcourt toutes les aretes qui permettent
// de calculer les termes croises dui/dxj.
//
// (les termes non-croises sont calcules
// en bouclant sur les elements)
//
  for (num_arete=ndeb; num_arete<nfin; num_arete++)
    {
      n_type=zone_Cl_VDF.type_arete_bord(num_arete-ndeb);
      if (n_type == 4) //!< arete de type periodicite
        {
          num0 = Qdm(num_arete,0);
          num1 = Qdm(num_arete,1);
          num2 = Qdm(num_arete,2);
          num3 = Qdm(num_arete,3);
          int i=0;
          int j=0;
          i=orientation(num0);
          j=orientation(num2);
          double temp1 = (vitesse[num1]-vitesse[num0])
                         /zone_VDF.dist_face_period(num0,num1,j);            //!< dui/dxj
          double temp2 = (vitesse[num3]-vitesse[num2])
                         /zone_VDF.dist_face_period(num2,num3,i);            //!< duj/dxi
          element(0) = face_voisins(num0,0);
          element(1) = face_voisins(num0,1);
          element(2) = face_voisins(num1,0);
          element(3) = face_voisins(num1,1);
          for (int k=0 ; k<4 ; k++)
            {
              gij(element(k),i,j)+=temp1*0.5*0.25;
              gij(element(k),j,i)+=temp2*0.5*0.25;
// Justification des coeff derriere :
// 1) 0.5 : pour la periodicite,
// car on distribuera deux fois sur
// les elements qui "touchent" cette arete
// puisqu'elle existe en double.
// 2) 0.25 : on distribue le gradient de vitesse
// sur les 4 elements qui l'entourent.
            }        //!< fin du for k
        }
      else
        {
          num0 = Qdm(num_arete,0);
          num1 = Qdm(num_arete,1);
          num2 = Qdm(num_arete,2);
          signe = Qdm(num_arete,3);
          int j=0;
          j=orientation(num2);
          double temp2;
          double temp1 = (vitesse[num1]-vitesse[num0])
                         /zone_VDF.dist_face_period(num0,num1,j);        //!< dui/dxj
          double vit_imp = 0.5*(vit.val_imp_face_bord_private(num0,j)+
                                vit.val_imp_face_bord_private(num1,j));                //!< vitesse tangentielle Dans cette partie, on conserve le codage de Hyd_SGE_Wale_VDF (num1 et non num2) pour calculer la distance entre le centre de la maille et le bord.
//
//
          temp2 = -signe*(vitesse[num2]-vit_imp)/zone_VDF.dist_norm_bord(num1);
          element(0) = face_voisins(num2,0);
          element(1) = face_voisins(num2,1);
          int i=orientation(num0);
          for (int k=0 ; k<2 ; k++)
            {
              gij(element(k),i,j)+=temp1*0.25;
              gij(element(k),j,i)+=temp2*0.25;
// Justification des coeff derriere :
// 1) 0.25 : on distribue le gradient de vitesse
// sur les 4 elements qui l'entourent.
            } //!< fin du for k
        }
    }
  //*******************************
  //On parcourt les aretes coins
  //*******************************
  ndeb = zone_VDF.premiere_arete_coin();
  nfin = ndeb + zone_VDF.nb_aretes_coin();
  for (num_arete=ndeb; num_arete<nfin; num_arete++)
    {
      n_type=zone_Cl_VDF.type_arete_coin(num_arete-ndeb);
      //***************************************
      // Traitement des aretes coin perio-perio
      //***************************************
      if (n_type == 0) // arete de type periodicite-periodicite
        {
          num0 = Qdm(num_arete,0);
          num1 = Qdm(num_arete,1);
          num2 = Qdm(num_arete,2);
          num3 = Qdm(num_arete,3);
          int i=0;
          int j=0;
          i=orientation(num0);
          j=orientation(num2);
          double temp1 = (vitesse[num1]-vitesse[num0])
                         /zone_VDF.dist_face_period(num0,num1,j);        // dui/dxj
          double temp2 = (vitesse[num3]-vitesse[num2])
                         /zone_VDF.dist_face_period(num2,num3,i);        // duj/dxi
          element(0) = face_voisins(num0,0);
          element(1) = face_voisins(num0,1);
          element(2) = face_voisins(num1,0);
          element(3) = face_voisins(num1,1);
          for (int k=0 ; k<4 ; k++)
            {
              gij(element(k),i,j)+=temp1*0.5*0.5*0.25;
              gij(element(k),j,i)+=temp2*0.5*0.5*0.25;
              // Justification des coeff derriere :
              // 1) 0.5 : pour la periodicite,
              //           car on distribuera deux fois sur
              //           les elements qui "touchent" cette arete
              //           puisqu'elle existe en double.
              // 2) 0.5 : idem ci-dessus, car cette fois-ci on a
              //           un coin perio-perio.
              // 3) 0.25 : on distribue le gradient de vitesse
              //            sur les 4 elements qui l'entourent.
            } // fin du for k
        }
      //***************************************
      // Traitement des aretes coin perio-paroi
      //***************************************
      if (n_type == 1) // arete de type periodicite-paroi
        {
          num0 = Qdm(num_arete,0);
          num1 = Qdm(num_arete,1);
          num2 = Qdm(num_arete,2);
          signe = Qdm(num_arete,3);
          int j=0;
          j=orientation(num2);
          double temp2;
          double temp1 = (vitesse[num1]-vitesse[num0])
                         /zone_VDF.dist_face_period(num0,num1,j);                // dui/dxj
          double vit_imp = 0.5*(vit.val_imp_face_bord_private(num0,j)+
                                vit.val_imp_face_bord_private(num1,j));        // vitesse tangentielle
          temp2  = -signe*(vitesse[num2]-vit_imp)/zone_VDF.dist_norm_bord(num1);
          element(0) = face_voisins(num2,0);
          element(1) = face_voisins(num2,1);
          int i=orientation(num1);
          for (int k=0 ; k<2 ; k++)
            {
              gij(element(k),i,j)+=temp1*0.5*0.25;
              gij(element(k),j,i)+=temp2*0.5*0.25;
              // Justification des coeff derriere :
              // 1) 0.5 : pour la periodicite,
              //           car on distribuera deux fois sur
              //           les elements qui "touchent" cette arete
              //           puisqu'elle existe en double.
              // 2) 0.25 : on distribue le gradient de vitesse
              //            sur les 4 elements qui l'entourent.
            } // fin du for k
        }
    }
  // 1ere partie:boucles sur les aretes et remplissage de Sij pour la partie
  // derivees croisees (dui/dxj)
  // vitesse[face] renvoie la vitesse NORMALE a la face
  //   for (num_arete = premiere_arete_bord ; num_arete<derniere_arete_bord ; num_arete ++)
  //     {
  //       const IntVect& type_arete_bord = zone_Cl_VDF.type_arete_bord();
  for(num_arete=premiere_arete_mixte ; num_arete<derniere_arete_mixte ; num_arete ++)
    {
      num0 = Qdm(num_arete,0);
      num1 = Qdm(num_arete,1);
      num2 = Qdm(num_arete,2);
      num3 = Qdm(num_arete,3);
      int i=0;
      int j=0;
      i=orientation(num0);
      j=orientation(num2);
      double temp1 = (vitesse[num1]-vitesse[num0])
                     /zone_VDF.dist_face_period(num0,num1,j);        // dui/dxj
      double temp2 = (vitesse[num3]-vitesse[num2])
                     /zone_VDF.dist_face_period(num2,num3,i);        // duj/dxi
      element(0) = face_voisins(num0,0);
      element(1) = face_voisins(num0,1);
      element(2) = face_voisins(num1,0);
      element(3) = face_voisins(num1,1);
      for (int k=0 ; k<4 ; k++)
        {
          if (element(k)!=-1)
            {
              gij(element(k),i,j)+=temp1*0.25;
              gij(element(k),j,i)+=temp2*0.25;
              // Justification des coeff derriere :
              // 1) 0.25 : on distribue le gradient de vitesse
              //            sur les 3 elements qui l'entourent.
              //            C'est pour cela que l'on regarde si element(k)!=-1,
              //            car dans ce cas la, c'est qu'il s'agit de "la case qui manque" !
            } // fin de else if
        } // fin du for k
    } // fin de la boucle sur les aretes mixtes
  for (num_arete=premiere_arete_interne ; num_arete<derniere_arete_interne ; num_arete ++)
    {
      num0 = Qdm(num_arete,0);
      num1 = Qdm(num_arete,1);
      num2 = Qdm(num_arete,2);
      num3 = Qdm(num_arete,3);
      int i=0;
      int j=0;
      i=orientation(num0);
      j=orientation(num2);
      double temp1 = (vitesse[num1]-vitesse[num0])
                     /zone_VDF.dist_face_period(num0,num1,j);        // dui/dxj
      assert(est_egal(zone_VDF.dist_face_period(num0,num1,j),zone_VDF.dist_face(num0,num1,j)));
      double temp2 = (vitesse[num3]-vitesse[num2])
                     /zone_VDF.dist_face_period(num2,num3,i);        // duj/dxi
      assert(est_egal(zone_VDF.dist_face_period(num2,num3,j),zone_VDF.dist_face(num2,num3,j)));
      element(0) = face_voisins(num0,0);
      element(1) = face_voisins(num0,1);
      element(2) = face_voisins(num1,0);
      element(3) = face_voisins(num1,1);
      for (int k=0 ; k<4 ; k++)
        {
          gij(element(k),i,j)+=temp1*0.25;
          gij(element(k),j,i)+=temp2*0.25;
          // Justification des coeff :
          // 1) 0.25 : on distribue le gradient de vitesse
          //            sur les 4 elements qui l'entourent.
        } // fin du for k
    } // fin de la boucle sur les aretes internes
  // 2eme partie: boucle sur les elements et remplissage de Sij pour les
  //  derivees non croisees (dui/dxi).
  // En fait dans ces cas la, on calcul directement le gradient dans l'element
  //  et on ne redistribue pas.
  for(elem=0 ; elem<nb_elem ; elem ++)
    {
      for (int i = 0 ; i<dimension ; i++)
        {
          double temp1 = (vitesse[elem_faces(elem,i)]
                          -vitesse[elem_faces(elem,i+dimension)])
                         /zone_VDF.dim_elem(elem,orientation(elem_faces(elem,i)));
          gij(elem,i,i)=-temp1;
        }
    }
  return gij;
}
References Zone_VDF::dim_elem(), Objet_U::dimension, Zone_VDF::dist_face(), Zone_VDF::dist_face_period(), Zone_VDF::dist_norm_bord(), Zone_VF::elem_faces(), est_egal(), Zone_VF::face_voisins(), Equation_base::inconnue(), la_zone_VDF, MorEqn::mon_equation, Zone_VDF::nb_aretes_bord(), Zone_VDF::nb_aretes_coin(), Zone_VDF::nb_aretes_internes(), Zone_VDF::nb_aretes_mixtes(), Zone::nb_elem_tot(), Zone_VDF::orientation(), Zone_VDF::premiere_arete_bord(), Zone_VDF::premiere_arete_coin(), Zone_VDF::premiere_arete_interne(), Zone_VDF::premiere_arete_mixte(), Zone_VDF::Qdm(), ref_cast, Zone_Cl_VDF::type_arete_bord(), Zone_Cl_VDF::type_arete_coin(), val_imp_face_bord_private(), Deriv_Champ_Inc_base::valeur(), Ref_Zone_VDF::valeur(), and Zone_dis_base::zone().
calcul_grad_u()
void Champ_Face::calcul_grad_u (const DoubleTab & vitesse, DoubleTab & grad_u, const Zone_Cl_VDF & zone_Cl_VDF)
Definition at line 1450 of file Champ_Face3.cpp.
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const int nb_elem = zone_VDF.nb_elem();
  const int nb_elem_tot = zone_VDF.nb_elem_tot();
  DoubleTab gradient_elem(nb_elem_tot,dimension,dimension);
  gradient_elem=0.;
  calcul_duidxj(vitesse,gradient_elem,zone_Cl_VDF);
  for (int elem=0; elem<nb_elem; elem++)
    {
      int comp=0;
      for (int i=0; i<dimension; i++)
        for(int j=0; j<dimension; j++)
          {
            grad_u(elem,comp) = gradient_elem(elem,i,j);
            comp++;
          }
    }
}
References calcul_duidxj(), Objet_U::dimension, la_zone_VDF, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), and Ref_Zone_VDF::valeur().
Referenced by grad_U_Champ_Face::me_calculer().
calcul_S_barre()
DoubleVect & Champ_Face::calcul_S_barre (const DoubleTab & vitesse, DoubleVect & SMA_barre, const Zone_Cl_VDF & zone_Cl_VDF) const
Definition at line 1420 of file Champ_Face3.cpp.
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const int nb_elem_tot = zone_VDF.nb_elem_tot();
  const int nb_elem = zone_VDF.nb_elem();
  int i,j;
  int elem;
  double Sij,temp;
  DoubleTab duidxj(nb_elem_tot,dimension,dimension);
  calcul_duidxj(vitesse,duidxj,zone_Cl_VDF);
  for (elem=0 ; elem<nb_elem; elem++)
    {
      temp = 0.;
      for ( i=0 ; i<dimension ; i++)
        for ( j=0 ; j<dimension ; j++)
          {
            Sij=0.5*(duidxj(elem,i,j) + duidxj(elem,j,i));
            temp+=Sij*Sij;
          }
      SMA_barre(elem)=2.*temp;
    }
  return SMA_barre;
}
References calcul_duidxj(), Objet_U::dimension, la_zone_VDF, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), and Ref_Zone_VDF::valeur().
Referenced by Taux_cisaillement_P0_VDF::mettre_a_jour().
calcul_S_barre_sans_contrib_paroi()
DoubleVect & Champ_Face::calcul_S_barre_sans_contrib_paroi (const DoubleTab & vitesse, DoubleVect & SMA_barre, const Zone_Cl_VDF & zone_Cl_VDF) const
Definition at line 1121 of file Champ_Face3.cpp.
{
  // On calcule directement S_barre(num_elem)!!!!!!!!!!
  // Le parametre contribution_paroi (ici fixe a 0) permet de ne pas prendre en compte
  // la contribution de la paroi au produit SMA_barre = Sij*Sij
  int contribution_paroi;
  contribution_paroi=0;
  const Champ_Face& vit = ref_cast(Champ_Face, mon_equation->inconnue().valeur());
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  int nb_elem = zone_VDF.zone().nb_elem();
  const IntTab& face_voisins = zone_VDF.face_voisins();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  const IntTab& Qdm = zone_VDF.Qdm();
  const IntVect& orientation = zone_VDF.orientation();
  int premiere_arete_mixte = zone_VDF.premiere_arete_mixte();
  int premiere_arete_interne =  zone_VDF.premiere_arete_interne();
  int derniere_arete_mixte = premiere_arete_mixte+zone_VDF.nb_aretes_mixtes();
  int derniere_arete_interne = premiere_arete_interne+zone_VDF.nb_aretes_internes();
  int elem;
  int num_arete;
  ArrOfInt element(4);
  int num0,num1,num2,num3,signe;
  int ndeb = zone_VDF.premiere_arete_bord();
  int nfin = ndeb + zone_VDF.nb_aretes_bord();
  int n_type;
  for (num_arete=ndeb; num_arete<nfin; num_arete++)
    {
      n_type=zone_Cl_VDF.type_arete_bord(num_arete-ndeb);
      if (n_type == 4) // arete de type periodicite
        {
          num0 = Qdm(num_arete,0);
          num1 = Qdm(num_arete,1);
          num2 = Qdm(num_arete,2);
          num3 = Qdm(num_arete,3);
          int i=0;
          int j=0;
          i=orientation(num0);
          j=orientation(num2);
          double temp1 = (vitesse[num1]-vitesse[num0])
                         /zone_VDF.dist_face_period(num0,num1,j);            // dv/dx
          double temp2 = (vitesse[num3]-vitesse[num2])
                         /zone_VDF.dist_face_period(num2,num3,i);            // du/dy
          element[0] = face_voisins(num0,0);
          element[1] = face_voisins(num0,1);
          element[2] = face_voisins(num1,0);
          element[3] = face_voisins(num1,1);
          for (int k=0 ; k<4 ; k++)
            {
              SMA_barre[element[k]]+=0.5*(temp1+temp2)*(temp1+temp2)*0.25;
              // Justification du coeff :
              // on calcule la somme des termes croises :
              // 2*( (0.5*Sij)^2+(0.5*Sji)^2)
              // Comme on est sur les aretes et qu on distribue sur l'element
              // il faut multiplier par 0.25
              // d ou : 0.25*(2*(2*0.5^2))=0.25*4*0.25=0.25!!!!!!
              // le 0.5 devant vient du fait que nous parcourons les faces de periodicite
              // comme les aretes periodiques sont les "memes", on ajoute deux fois ce qu il faut
              // aux elements -> 0.5!!!
            }        // fin du for k
        }
      else
        {
          num0 = Qdm(num_arete,0);
          num1 = Qdm(num_arete,1);
          num2 = Qdm(num_arete,2);
          signe = Qdm(num_arete,3);
          int j=0;
          j=orientation(num2);
          double temp2;
          double temp1 = (vitesse[num1]-vitesse[num0])
                         /zone_VDF.dist_face_period(num0,num1,j);        // dv/dx
          double vit_imp = 0.5*(vit.val_imp_face_bord_private(num0,j)+
                                vit.val_imp_face_bord_private(num1,j));                // vitesse tangentielle
          if ( n_type == 0 && contribution_paroi == 0 )
            temp2 = 0;
          else
            temp2  = -signe*(vitesse[num2]-vit_imp)/zone_VDF.dist_norm_bord(num1);
          element[0] = face_voisins(num2,0);
          element[1] = face_voisins(num2,1);
          for (int k=0 ; k<2 ; k++)
            {
              SMA_barre[element[k]]+=(temp1+temp2)*(temp1+temp2)*0.25;
              // Justification du coeff :
              // on calcule la somme des termes croises :
              // 2*( (0.5*Sij)^2+(0.5*Sji)^2)
              // Comme on est sur les aretes et qu on distribue sur l'element
              // il faut multiplier par 0.25
              // d ou : 0.25*(2*(2*0.5^2))=0.25*4*0.25=0.25!!!!!!
              // Prise en compte des 2 termes symetriques : SijSij+SjiSji
            }                // fin du for k
        }
    }
  /////////////////////////////////
  //On parcourt les aretes coins
  ////////////////////////////////
  ndeb = zone_VDF.premiere_arete_coin();
  nfin = ndeb + zone_VDF.nb_aretes_coin();
  for (num_arete=ndeb; num_arete<nfin; num_arete++)
    {
      n_type=zone_Cl_VDF.type_arete_coin(num_arete-ndeb);
      //////////////////////////////////////////
      // Traitement des aretes coin perio-perio
      //////////////////////////////////////////
      if (n_type == 0) // arete de type periodicite-periodicite
        {
          num0 = Qdm(num_arete,0);
          num1 = Qdm(num_arete,1);
          num2 = Qdm(num_arete,2);
          num3 = Qdm(num_arete,3);
          int i=0;
          int j=0;
          i=orientation(num0);
          j=orientation(num2);
          double temp1 = (vitesse[num1]-vitesse[num0])
                         /zone_VDF.dist_face_period(num0,num1,j);            // dv/dx
          double temp2 = (vitesse[num3]-vitesse[num2])
                         /zone_VDF.dist_face_period(num2,num3,i);            // du/dy
          element[0] = face_voisins(num0,0);
          element[1] = face_voisins(num0,1);
          element[2] = face_voisins(num1,0);
          element[3] = face_voisins(num1,1);
          for (int k=0 ; k<4 ; k++)
            {
              SMA_barre[element[k]]+=0.5*0.5*(temp1+temp2)*(temp1+temp2)*0.25;
              // Justification du coeff :
              // on calcule la somme des termes croises :
              // 2*( (0.5*Sij)^2+(0.5*Sji)^2)
              // Comme on est sur les aretes et qu on distribue sur l'element
              // il faut multiplier par 0.25
              // d ou : 0.25*(2*(2*0.5^2))=0.25*4*0.25=0.25!!!!!!
              // le 0.5 devant vient du fait que nous parcourons les faces de periodicite
              // comme les aretes periodiques sont les "memes", on ajoute deux fois ce qu il faut
              // aux elements -> 0.5!!!
              // encore un *0.5 car ce sont des aretes perio perio donc que l on parcourt 4 fois!!!!
            }        // fin du for k
        }
      //////////////////////////////////////////
      // Traitement des aretes coin perio-paroi
      //////////////////////////////////////////
      if (n_type == 1) // arete de type periodicite-paroi
        {
          num0 = Qdm(num_arete,0);
          num1 = Qdm(num_arete,1);
          num2 = Qdm(num_arete,2);
          signe = Qdm(num_arete,3);
          int j=0;
          j=orientation(num2);
          double temp2;
          double temp1 = (vitesse[num1]-vitesse[num0])
                         /zone_VDF.dist_face_period(num0,num1,j);        // dv/dx
          double vit_imp = 0.5*(vit.val_imp_face_bord_private(num0,j)+
                                vit.val_imp_face_bord_private(num1,j));             // vitesse tangentielle
          if ( contribution_paroi == 0 )
            temp2 = 0;
          else
            temp2  = -signe*(vitesse[num2]-vit_imp)/zone_VDF.dist_norm_bord(num1);
          element[0] = face_voisins(num2,0);
          element[1] = face_voisins(num2,1);
          for (int k=0 ; k<2 ; k++)
            {
              SMA_barre[element[k]]+=0.5*(temp1+temp2)*(temp1+temp2)*0.25;
              // Justification du coeff :
              // on calcule la somme des termes croises :
              // 2*( (0.5*Sij)^2+(0.5*Sji)^2)
              // Comme on est sur les aretes et qu on distribue sur l'element
              // il faut multiplier par 0.25
              // d ou : 0.25*(2*(2*0.5^2))=0.25*4*0.25=0.25!!!!!!
              // Prise en compte des 2 termes symetriques : SijSij+SjiSji
              // encore un *0.5 car ce sont des aretes perio perio donc que l on parcourt 2 fois!!!!
            }                // fin du for k
        }
    }
  // 1ere partie:boucles sur les aretes et remplissage de Sij pour la partie
  // derivees croisees (dv/dx+du/dy)
  // vitesse[face] renvoie la vitesse NORMALE a la face
  //   for (num_arete = premiere_arete_bord ; num_arete<derniere_arete_bord ; num_arete ++)
  //     {
  //       const IntVect& type_arete_bord = zone_Cl_VDF.type_arete_bord();
  for(num_arete=premiere_arete_mixte ; num_arete<derniere_arete_mixte ; num_arete ++)
    {
      num0 = Qdm(num_arete,0);
      num1 = Qdm(num_arete,1);
      num2 = Qdm(num_arete,2);
      num3 = Qdm(num_arete,3);
      int i=0;
      int j=0;
      i=orientation(num0);
      j=orientation(num2);
      double temp1 = (vitesse[num1]-vitesse[num0])
                     /zone_VDF.dist_face_period(num0,num1,j);          // dv/dx
      double temp2 = (vitesse[num3]-vitesse[num2])
                     /zone_VDF.dist_face_period(num2,num3,i);          // du/dy
      element[0] = face_voisins(num0,0);
      element[1] = face_voisins(num0,1);
      element[2] = face_voisins(num1,0);
      element[3] = face_voisins(num1,1);
      for (int k=0 ; k<4 ; k++)
        {
          if (element[k]!=-1)
            {
              SMA_barre[element[k]]+=(temp1+temp2)*(temp1+temp2)*0.25;
              // Justification du coeff :
              // on calcule la somme des termes croises :
              // 2*( (0.5*Sij)^2+(0.5*Sji)^2)
              // Comme on est sur les aretes et qu on distribue sur l'element
              // il faut multiplier par 0.25
              // d ou : 0.25*(2*(2*0.5^2))=0.25*4*0.25=0.25!!!!!!
              // Prise en compte des 2 termes symetriques : SijSij+SjiSji
            }        // fin de else if
        }                // fin du for k
    }                // fin de la boucle sur les aretes mixtes
  for (num_arete=premiere_arete_interne ; num_arete<derniere_arete_interne ; num_arete ++)
    {
      num0 = Qdm(num_arete,0);
      num1 = Qdm(num_arete,1);
      num2 = Qdm(num_arete,2);
      num3 = Qdm(num_arete,3);
      int i=0;
      int j=0;
      i=orientation(num0);
      j=orientation(num2);
      double temp1 = (vitesse[num1]-vitesse[num0])
                     /zone_VDF.dist_face_period(num0,num1,j);            // dv/dx
      double temp2 = (vitesse[num3]-vitesse[num2])
                     /zone_VDF.dist_face_period(num2,num3,i);            // du/dy
      element[0] = face_voisins(num0,0);
      element[1] = face_voisins(num0,1);
      element[2] = face_voisins(num1,0);
      element[3] = face_voisins(num1,1);
      for (int k=0 ; k<4 ; k++)
        {
          SMA_barre[element[k]]+=(temp1+temp2)*(temp1+temp2)*0.25;
          // Justification du coeff :
          // on calcule la somme des termes croises :
          // 2*( (0.5*Sij)^2+(0.5*Sji)^2)
          // Comme on est sur les aretes et qu on distribue sur l'element
          // il faut multiplier par 0.25
          // d ou : 0.25*(2*(2*0.5^2))=0.25*4*0.25=0.25!!!!!!
          // Prise en compte des 2 termes symetriques : SijSij+SjiSji
        }        // fin du for k
    }        // fin de la boucle sur les aretes internes
  // 2eme partie: boucle sur les elements et remplissage de Sij pour les
  // derivees non croisees (du/dx et dv/dy)
  for(elem=0 ; elem<nb_elem ; elem ++)
    {
      for (int i = 0 ; i<dimension ; i++)
        {
          double temp1 = (vitesse[elem_faces(elem,i)]
                          -vitesse[elem_faces(elem,i+dimension)])
                         /zone_VDF.dim_elem(elem,orientation(elem_faces(elem,i)));
          SMA_barre(elem)+=2.0*temp1*temp1;
        }
    }
  // On prend la racine carre!!!!!  ATTENTION SMA_barre=invariant au carre!!!
  //  racine_carree(SMA_barre)
  return SMA_barre;
}
References Zone_VDF::dim_elem(), Objet_U::dimension, Zone_VDF::dist_face_period(), Zone_VDF::dist_norm_bord(), Zone_VF::elem_faces(), Zone_VF::face_voisins(), Equation_base::inconnue(), la_zone_VDF, MorEqn::mon_equation, Zone_VDF::nb_aretes_bord(), Zone_VDF::nb_aretes_coin(), Zone_VDF::nb_aretes_internes(), Zone_VDF::nb_aretes_mixtes(), Zone::nb_elem(), Zone_VDF::orientation(), Zone_VDF::premiere_arete_bord(), Zone_VDF::premiere_arete_coin(), Zone_VDF::premiere_arete_interne(), Zone_VDF::premiere_arete_mixte(), Zone_VDF::Qdm(), ref_cast, Zone_Cl_VDF::type_arete_bord(), Zone_Cl_VDF::type_arete_coin(), val_imp_face_bord_private(), Deriv_Champ_Inc_base::valeur(), Ref_Zone_VDF::valeur(), and Zone_dis_base::zone().
calcul_y_plus()
void Champ_Face::calcul_y_plus (DoubleTab & y_plus, const Zone_Cl_VDF & zone_Cl_VDF)
< will contain yplus values if available
< flag
Definition at line 548 of file Champ_Face3.cpp.
{
// On initialise le champ y_plus avec une valeur negative,
// comme ca lorsqu'on veut visualiser le champ pres de la paroi,
// on n'a qu'a supprimer les valeurs negatives et n'apparaissent
// que les valeurs aux parois.
  int ndeb,nfin,elem,ori,l_unif;
  double norm_tau,u_etoile,norm_v=0, dist, val0, val1, val2, d_visco=0, visco=1.;
  y_plus=-1.;
  const Champ_Face& vit = *this;
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const IntTab& face_voisins = zone_VDF.face_voisins();
  const IntVect& orientation = zone_VDF.orientation();
  const Equation_base& eqn_hydr = equation();
  const Fluide_base& le_fluide = ref_cast(Fluide_base, eqn_hydr.milieu());
  const Champ_Don& ch_visco_cin = le_fluide.viscosite_cinematique();
  const DoubleTab& tab_visco = ch_visco_cin->valeurs();
// DoubleTab& tab_visco = ch_visco_cin.valeur().valeurs();
  if (sub_type(Champ_Uniforme, ch_visco_cin.valeur()))
    {
      visco = tab_visco(0,0);
      l_unif = 1;
    }
  else
    l_unif = 0;
  /* GF on a pas a change tab_visco ici !
  if (!l_unif)
    {
      const int n = tab_visco.size_array();
      ArrOfDouble& v = tab_visco;
      for (int i = 0; i < n; i++)
        if (v[i] < DMINFLOAT)
          v[i] = DMINFLOAT;
    }
// Changer uniquement les valeurs < DMINFLOAT (l'ancien code n'est pas parallele)
  */
  DoubleTab yplus_faces( 1, 1 ); //!< will contain yplus values if available
  int yplus_already_computed=0; //!< flag
  const RefObjU& modele_turbulence = eqn_hydr.get_modele(TURBULENCE);
  if (modele_turbulence.non_nul() && sub_type(Mod_turb_hyd_base,modele_turbulence.valeur()))
    {
      const Mod_turb_hyd_base& mod_turb = ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur());
      const Turbulence_paroi_base& loipar = mod_turb.loi_paroi();
      if( loipar.use_shear( ) )
        {
          yplus_faces.resize( la_zone_VDF->nb_faces_tot( ) );
          yplus_faces.ref( loipar.tab_d_plus( ) );
          yplus_already_computed = 1;
        }
    }
  for (int n_bord=0; n_bord<zone_VDF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VDF.les_conditions_limites(n_bord);
      if ( sub_type(Dirichlet_paroi_fixe,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          ndeb = le_bord.num_premiere_face();
          nfin = ndeb + le_bord.nb_faces();
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
              if( face_voisins( num_face, 0 ) != -1 )
                elem = face_voisins( num_face, 0 ) ;
              else
                elem = face_voisins( num_face, 1 ) ;
              if( yplus_already_computed )
                {
// y+ is only defined on faces so we take the face value to put in the element
                  y_plus( elem ) = yplus_faces( num_face );
                }
              else
                {
                  if ( dimension == 2 )
                    {
                      ori = orientation(num_face);
                      norm_v=norm_2D_vit(vit.valeurs(),elem,ori,zone_VDF,val0);
                    }
                  else if ( dimension == 3)
                    {
                      ori = orientation(num_face);
                      norm_v=norm_3D_vit(vit.valeurs(),elem,ori,zone_VDF,val1,val2);
                    } //!< dim 3
                  if ( axi )
                    dist=zone_VDF.dist_norm_bord_axi(num_face);
                  else
                    dist=zone_VDF.dist_norm_bord(num_face);
                  if ( l_unif )
                    d_visco = visco;
                  else
                    d_visco = tab_visco[elem];
// PQ : 01/10/03 : corrections par rapport a la version premiere
                  norm_tau = d_visco*norm_v/dist;
                  u_etoile = sqrt(norm_tau);
                  y_plus(elem) = dist*u_etoile/d_visco;
                } //!< else yplus already computed
            } //!< loop on faces
        } //!< Fin paroi fixe
    } //!< Fin boucle sur les bords
}
References Objet_U::axi, Objet_U::dimension, Zone_VDF::dist_norm_bord(), Zone_VDF::dist_norm_bord_axi(), MorEqn::equation(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Equation_base::get_modele(), la_zone_VDF, Zone_Cl_dis_base::les_conditions_limites(), Mod_turb_hyd_base::loi_paroi(), Equation_base::milieu(), Front_VF::nb_faces(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), O_U_Ptr::non_nul(), norm_2D_vit(), norm_3D_vit(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), TRUSTTab< _TYPE_ >::ref(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Turbulence_paroi_base::tab_d_plus(), TURBULENCE, Turbulence_paroi_base::use_shear(), Deriv_Champ_Don_base::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Objet_U::valeur(), Ref_Zone_VDF::valeur(), Champ_Don::valeurs(), Champ_Inc_base::valeurs(), and Fluide_base::viscosite_cinematique().
Referenced by Y_plus_Champ_Face::me_calculer().
calculer_dercov_axi()
void Champ_Face::calculer_dercov_axi (const Zone_Cl_VDF & zone_Cl_VDF)
< bord d'equation R = cte
< bord d'equation teta = cte
< (ori1 == 2) bord d'equation Z = cte
< (seule possibilite : ori3 =0) Arete XY
< (seule possibilite ori1 = 2) arete YZ
< seule possibilite ori1 = 2 et ori3 = 0: arete XZ
Definition at line 24 of file Champ_Face2.cpp.
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const DoubleTab& inco = valeurs();
  const IntVect& orientation = zone_VDF.orientation();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  const IntTab& Qdm = zone_VDF.Qdm();
  const DoubleTab& xv = zone_VDF.xv();
  const DoubleTab& xp = zone_VDF.xp();
  const IntVect& type_arete_bord = zone_Cl_VDF.type_arete_bord();
  double d_teta,R;
  double deux_pi = M_PI*2.0;
// Remplissage de tau_diag_ : termes diagonaux du tenseur GradU
  int fx0,fx1,fy0,fy1;
  int num_elem;
  for (num_elem=0; num_elem<zone_VDF.nb_elem(); num_elem++)
    {
      fx0 = elem_faces(num_elem,0);
      fx1 = elem_faces(num_elem,dimension);
      fy0 = elem_faces(num_elem,1);
      fy1 = elem_faces(num_elem,1+dimension);
// Calcul de tau11
      tau_diag_(num_elem,0) = (inco[fx1]-inco[fx0])/(xv(fx1,0) - xv(fx0,0));
// Calcul de tau22
      R = xp(num_elem,0);
      d_teta = xv(fy1,1) - xv(fy0,1);
      if (d_teta < 0)
        d_teta += deux_pi;
      tau_diag_(num_elem,1) =     (inco[fy1]-inco[fy0])/(R*d_teta)
                                  + 0.5*(inco[fx0]+inco[fx1])/R;
    }
  if (dimension == 3)
    {
      int fz0,fz1;
      for (num_elem=0; num_elem<zone_VDF.nb_elem(); num_elem++)
        {
          fz0 = elem_faces(num_elem,2);
          fz1 = elem_faces(num_elem,2+dimension);
// Calcul de tau33
          tau_diag_(num_elem,2) = (inco[fz1]-inco[fz0])/(xv(fz1,2) - xv(fz0,2));
        }
    }
// Remplissage de tau_croises_ : termes extradiagonaux du tenseur GradU
// Les derivees croisees de la vitesse (termes extradiagonaux du tenseur
// GradU) sont calculees sur les aretes.
// Il y a deux derivees par arete:
// Pour une arete XY : tau12 et tau21
// Pour une arete YZ : tau23 et tau32
// Pour une arete XZ : tau13 et tau31
// Boucle sur les aretes bord
  int n_arete;
  int ndeb = zone_VDF.premiere_arete_bord();
  int nfin = ndeb + zone_VDF.nb_aretes_bord();
  int ori1,ori3;
  int fac1,fac2,fac3,fac4,signe;
  double dist3;
  int n_type;
  for (n_arete=ndeb; n_arete<nfin; n_arete++)
    {
      n_type=type_arete_bord(n_arete-ndeb);
      switch(n_type)
        {
        case TypeAreteBordVDF::PAROI_PAROI :
// paroi-paroi
        case TypeAreteBordVDF::FLUIDE_FLUIDE:
// fluide-fluide
        case TypeAreteBordVDF::PAROI_FLUIDE:
// paroi-fluide
          {
            fac1 = Qdm(n_arete,0);
            fac2 = Qdm(n_arete,1);
            fac3 = Qdm(n_arete,2);
            signe  = Qdm(n_arete,3);
            ori1 = orientation(fac1);
            ori3 = orientation(fac3);
            int rang1 = fac1 - zone_VDF.premiere_face_bord();
            int rang2 = fac2 - zone_VDF.premiere_face_bord();
            double vit_imp;
            if (n_type == TypeAreteBordVDF::PAROI_FLUIDE)
// arete paroi_fluide :il faut determiner qui est la face fluide
              {
                if (est_egal(inco[fac1],0))
                  vit_imp = val_imp_face_bord_private(rang2,ori3);
                else
                  vit_imp = val_imp_face_bord_private(rang1,ori3);
              }
            else
              vit_imp = 0.5*(val_imp_face_bord_private(rang1,ori3)+
                             val_imp_face_bord_private(rang2,ori3));
            if (ori1 == 0) //!< bord d'equation R = cte
              {
                dist3 = xv(fac3,0) - xv(fac1,0);
                if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                  dist3 *= 2;
                if (ori3 == 1)
                  {
// calcul de tau12
                    tau_croises_(n_arete,0) = signe*(vit_imp-inco[fac3])/dist3;
// calcul de tau21
                    R = xv(fac1,0);
                    d_teta = xv(fac2,1) - xv(fac1,1);
                    if  (d_teta < 0)
                      d_teta += deux_pi;
                    tau_croises_(n_arete,1) = (inco[fac2]-inco[fac1])/(R*d_teta);
                  }
                else if (ori3 == 2)
                  {
// calcul de tau13
                    tau_croises_(n_arete,0) = signe*(vit_imp-inco[fac3])/dist3;
// calcul de tau31
                    tau_croises_(n_arete,1) = (inco[fac2]-inco[fac1])/(xv(fac2,2)-xv(fac1,2));
                  }
              }
            else if (ori1 == 1) //!< bord d'equation teta = cte
              {
                R = xv(fac3,0);
                d_teta = xv(fac3,1) - xv(fac1,1);
                if (d_teta < 0)
                  d_teta += deux_pi;
                dist3  = R*d_teta;
                if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                  dist3 *= 2;
                if (ori3 == 0)
                  {
// calcul de tau21
                    tau_croises_(n_arete,0) = signe*(vit_imp-inco[fac3])/dist3
                                              - 0.5*(inco[fac1]+inco[fac2])/R;
// calcul de tau12
                    tau_croises_(n_arete,1) = (inco[fac2]-inco[fac1])/(xv(fac2,0) - xv(fac1,0));
                  }
                else if (ori3 == 2)
                  {
// calcul de tau23
                    tau_croises_(n_arete,0) = signe*(vit_imp-inco[fac3])/dist3;
// calcul de tau32
                    tau_croises_(n_arete,1) = (inco[fac2]-inco[fac1])/(xv(fac2,2) - xv(fac1,2));
                  }
              }
            else //!< (ori1 == 2) bord d'equation Z = cte
              {
                dist3 = xv(fac3,2)-xv(fac1,2);
                if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                  dist3 *= 2;
                if (ori3 == TypeAreteBordVDF::PAROI_PAROI)
                  {
// calcul de tau31
                    tau_croises_(n_arete,0) = signe*(vit_imp-inco[fac3])/dist3;
// calcul de tau13
                    tau_croises_(n_arete,1) = (inco[fac2]-inco[fac1])/(xv(fac2,0) - xv(fac1,0));
                  }
                else if (ori3 == 1)
                  {
// calcul de tau32
                    tau_croises_(n_arete,0) = signe*(vit_imp-inco[fac3])/dist3;
// calcul de tau23
                    R = xv(fac1,0);
                    d_teta = xv(fac2,1) - xv(fac1,1);
                    if  (d_teta < 0)
                      d_teta += deux_pi;
                    tau_croises_(n_arete,1) = (inco[fac2]-inco[fac1])/(R*d_teta);
                  }
              }
            break;
          }
        case 3:
          {
// symetrie-symetrie
// pas de flux diffusif calcule
            break;
          }
        default :
          {
            Cerr << "On a rencontre un type d'arete non prevu\n";
            Cerr << "num arete : " << n_arete;
            Cerr << " type : " << n_type;
            exit();
            break;
          }
        }
    }
// Boucle sur les aretes mixtes et internes
  ndeb = zone_VDF.premiere_arete_mixte();
  nfin = zone_VDF.nb_aretes();
  for (n_arete=ndeb; n_arete<nfin; n_arete++)
    {
      fac1=Qdm(n_arete,0);
      fac2=Qdm(n_arete,1);
      fac3=Qdm(n_arete,2);
      fac4=Qdm(n_arete,3);
      ori1 = orientation(fac1);
      ori3 = orientation(fac3);
      if (ori1 == 1)  //!< (seule possibilite : ori3 =0)  Arete XY
        {
// Calcul de tau21
          R = xv(fac3,0);
          d_teta = xv(fac4,1) - xv(fac3,1);
          if (d_teta < 0)
            d_teta += deux_pi;
          tau_croises_(n_arete,1) = (inco(fac4)-inco(fac3))/(R*d_teta) - 0.5*(inco[fac1]+inco[fac2])/R;
// Calcul de tau12
          tau_croises_(n_arete,0) = (inco(fac2)-inco(fac1))/(xv(fac2,0) - xv(fac1,0));
        }
      else if (ori3 == 1) //!< (seule possibilite ori1 = 2) arete YZ
        {
// Calcul de tau32
          tau_croises_(n_arete,1) = (inco(fac4)-inco(fac3))/(xv(fac4,2) - xv(fac3,2));
// Calcul de tau23
          R = xv(fac1,0);
          d_teta = xv(fac2,1) - xv(fac1,1);
          if (d_teta < 0)
            d_teta += deux_pi;
          tau_croises_(n_arete,0) = (inco(fac2)-inco(fac1))/(R*d_teta);
        }
      else //!< seule possibilite ori1 = 2 et ori3 = 0:  arete XZ
        {
// Calcul de tau31
          tau_croises_(n_arete,1) = (inco(fac4)-inco(fac3))/(xv(fac4,2) - xv(fac3,2));
// Calcul de tau13
          tau_croises_(n_arete,0) = (inco(fac2)-inco(fac1))/(xv(fac2,0) - xv(fac1,0));
        }
    }
}
References Cerr, Objet_U::dimension, Zone_VF::elem_faces(), est_egal(), Process::exit(), TypeAreteBordVDF::FLUIDE_FLUIDE, la_zone_VDF, M_PI, Zone_VDF::nb_aretes(), Zone_VDF::nb_aretes_bord(), Zone_dis_base::nb_elem(), Zone_VDF::orientation(), TypeAreteBordVDF::PAROI_FLUIDE, TypeAreteBordVDF::PAROI_PAROI, Zone_VDF::premiere_arete_bord(), Zone_VDF::premiere_arete_mixte(), Zone_VF::premiere_face_bord(), Zone_VDF::Qdm(), tau_croises_, tau_diag_, Zone_Cl_VDF::type_arete_bord(), val_imp_face_bord_private(), Ref_Zone_VDF::valeur(), Champ_Inc_base::valeurs(), Zone_VF::xp(), and Zone_VF::xv().
calculer_dscald_centre_element()
void Champ_Face::calculer_dscald_centre_element (DoubleTab & dscald) const
Definition at line 793 of file Champ_Face4.cpp.
{
  const DoubleTab& val = valeurs();
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  int nb_elem = zone_VDF.nb_elem();
  const IntTab& face_voisins = zone_VDF.face_voisins();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  if (dimension == 2 )
    caldscaldcentelemdim2(dscald, val, zone_VDF, nb_elem, face_voisins, elem_faces);
  else if (dimension == 3)
    caldscaldcentelemdim3(dscald, val, zone_VDF, nb_elem, face_voisins, elem_faces);
}
References caldscaldcentelemdim2(), caldscaldcentelemdim3(), Objet_U::dimension, Zone_VF::elem_faces(), Zone_VF::face_voisins(), la_zone_VDF, Zone_dis_base::nb_elem(), Ref_Zone_VDF::valeur(), and Champ_Inc_base::valeurs().
Referenced by Champ_Ostwald_VDF::me_calculer().
calculer_rotationnel_ordre2_centre_element()
void Champ_Face::calculer_rotationnel_ordre2_centre_element (DoubleTab & rot) const
Definition at line 491 of file Champ_Face3.cpp.
{
  const DoubleTab& val = valeurs();
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  int nb_elem = zone_VDF.nb_elem();
  const IntTab& face_voisins = zone_VDF.face_voisins();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  if (dimension == 2 )
    calrotord2centelemdim2(rot, val, zone_VDF, nb_elem, face_voisins, elem_faces);
  else if (dimension == 3)
    calrotord2centelemdim3(rot, val, zone_VDF, nb_elem, face_voisins, elem_faces);
}
References calrotord2centelemdim2(), calrotord2centelemdim3(), Objet_U::dimension, Zone_VF::elem_faces(), Zone_VF::face_voisins(), la_zone_VDF, Zone_dis_base::nb_elem(), Ref_Zone_VDF::valeur(), and Champ_Inc_base::valeurs().
Referenced by Rotationnel_Champ_Face::me_calculer().
compo_normale_sortante()
int Champ_Face::compo_normale_sortante (int num_face) const
Definition at line 443 of file Champ_Face.cpp.
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  int signe =1;
  double vit_norm;
// signe vaut -1 si face_voisins(num_face,0) est a l'exterieur
// signe vaut  1 si face_voisins(num_face,1) est a l'exterieur
  if (zone_VDF.face_voisins(num_face,0) == -1)
    signe = -1;
  vit_norm= (*this)(num_face)*signe;
  return (vit_norm > 0);
}
References Zone_VF::face_voisins(), la_zone_VDF, and Ref_Zone_VDF::valeur().
cree_instance()
Objet_U * Champ_Face::cree_instance () static
Definition at line 29 of file Champ_Face.cpp.
dimensionner_tenseur_Grad()
void Champ_Face::dimensionner_tenseur_Grad ()
Definition at line 77 of file Champ_Face.cpp.
{
  tau_diag_.resize(la_zone_VDF->nb_elem(),dimension);
  tau_croises_.resize(la_zone_VDF->nb_aretes(),2);
}
References Objet_U::dimension, la_zone_VDF, Zone_VDF::nb_aretes(), Zone_dis_base::nb_elem(), TRUSTTab< _TYPE_ >::resize(), tau_croises_, and tau_diag_.
Referenced by Op_Dift_VDF_Face_Axi_base::completer().
duplique()
int Champ_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 29 of file Champ_Face.cpp.
fixer_nb_valeurs_nodales()
int Champ_Face::fixer_nb_valeurs_nodales (int nb_noeuds) override virtual
Reimplemented from Champ_Inc_base.
Definition at line 64 of file Champ_Face.cpp.
{
  assert(nb_noeuds == zone_vdf().nb_faces());
  const MD_Vector& md = zone_vdf().md_vector_faces();
// Probleme: nb_comp vaut 2 mais on ne veut qu'une dimension !!!
// HACK :
  int old_nb_compo = nb_compo_;
  nb_compo_ = 1;
  creer_tableau_distribue(md);
  nb_compo_ = old_nb_compo;
  return nb_noeuds;
}
References Champ_Inc_base::creer_tableau_distribue(), Zone_VF::md_vector_faces(), Field_base::nb_compo_, and zone_vdf().
Referenced by EOS_Tools_VDF::associer_zones().
get_info()
const Type_info * Champ_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 29 of file Champ_Face.cpp.
imprime()
int Champ_Face::imprime (Sortie & os, int ncomp) const override virtual
Reimplemented from Champ_Inc_base.
Definition at line 505 of file Champ_Face3.cpp.
{
  imprime_Face(os,ncomp);
  return 1;
}
References Champ_Face_implementation::imprime_Face().
info()
const Type_info * Champ_Face::info () static
Definition at line 29 of file Champ_Face.cpp.
le_champ() [1/2]
const Champ_base & Champ_Face::le_champ (void) const inline override private virtual
Implements Champ_implementation.
Definition at line 131 of file Champ_Face.h.
{
  return *this;
}
le_champ() [2/2]
Champ_base & Champ_Face::le_champ (void) inline override private virtual
Implements Champ_implementation.
Definition at line 136 of file Champ_Face.h.
{
  return *this;
}
mettre_a_jour()
void Champ_Face::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps du champ inconnue.
WEC : Maintenant si on l'appelle 2 fois de suite avec le meme
argument, la 2eme ne fait rien.
Reimplemented from Champ_Inc_base.
Definition at line 461 of file Champ_Face.cpp.
{
  Champ_Inc_base::mettre_a_jour(un_temps);
}
References Champ_Inc_base::mettre_a_jour().
printOn()
Sortie & Champ_Face::printOn (Sortie & os) const override protected virtual
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 34 of file Champ_Face.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Face::readOn (Entree & is) override protected virtual
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 42 of file Champ_Face.cpp.
{
  lire_donnees (s) ;
  return s ;
}
References Champ_Inc_base::lire_donnees().
remplir_coord_noeuds()
DoubleTab & Champ_Face::remplir_coord_noeuds (DoubleTab & positions) const inline override virtual
Implements Champ_Inc_base.
Definition at line 175 of file Champ_Face.h.
{
  return Champ_Face_implementation::remplir_coord_noeuds(positions);
}
References Champ_Face_implementation::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
int Champ_Face::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const inline override virtual
NE FAIT RIEN
Methode a surcharger.
Returns
int
Signification: renvoie toujours 0
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 179 of file Champ_Face.h.
{
  return Champ_Face_implementation::remplir_coord_noeuds_et_polys(positions,
                                                                  polys);
}
References Champ_Face_implementation::remplir_coord_noeuds_et_polys().
self_cast() [1/2]
const Champ_Face & Champ_Face::self_cast (const Objet_U & r) static
Definition at line 29 of file Champ_Face.cpp.
self_cast() [2/2]
Champ_Face & Champ_Face::self_cast (Objet_U & r) static
Definition at line 29 of file Champ_Face.cpp.
taille_memoire()
unsigned Champ_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 29 of file Champ_Face.cpp.
tau_croises() [1/2]
DoubleTab & Champ_Face::tau_croises () inline
Definition at line 201 of file Champ_Face.h.
{
  return tau_croises_;
}
References tau_croises_.
tau_croises() [2/2]
const DoubleTab & Champ_Face::tau_croises () const inline
Definition at line 191 of file Champ_Face.h.
{
  return tau_croises_;
}
References tau_croises_.
Referenced by Op_Dift_VDF_Face_Axi_base::ajouter().
tau_diag() [1/2]
DoubleTab & Champ_Face::tau_diag () inline
Definition at line 196 of file Champ_Face.h.
{
  return tau_diag_;
}
References tau_diag_.
tau_diag() [2/2]
const DoubleTab & Champ_Face::tau_diag () const inline
Definition at line 186 of file Champ_Face.h.
{
  return tau_diag_;
}
References tau_diag_.
Referenced by Op_Dift_VDF_Face_Axi_base::ajouter(), and Op_Dift_VDF_Face_Axi_base::ajouter_contribution().
trace()
DoubleTab & Champ_Face::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const override virtual
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
Reimplemented from Champ_Inc_base.
Definition at line 456 of file Champ_Face.cpp.
{
  return Champ_Face_implementation::trace(fr, valeurs(tps), x,distant);
}
References Champ_Face_implementation::trace(), and Champ_Inc_base::valeurs().
val_imp_face_bord_private() [1/2]
double Champ_Face::val_imp_face_bord_private (int face, int comp) const private
Definition at line 307 of file Champ_Face.cpp.
{
  const Zone_Cl_VDF& zclo=ref_cast(Zone_Cl_VDF,equation().zone_Cl_dis().valeur());
  return Champ_Face_get_val_imp_face_bord_sym(valeurs(),temps(), face,comp,  zclo);
}
References Champ_Face_get_val_imp_face_bord_sym(), MorEqn::equation(), ref_cast, Champ_base::temps(), valeur(), Champ_Inc_base::valeurs(), and Champ_Inc_base::zone_Cl_dis().
Referenced by calcul_duidxj(), calcul_S_barre_sans_contrib_paroi(), and calculer_dercov_axi().
val_imp_face_bord_private() [2/2]
double Champ_Face::val_imp_face_bord_private (int face, int comp1, int comp2) const private
< For compilers
Definition at line 426 of file Champ_Face.cpp.
{
  Cerr << "Champ_Face::val_imp_face_bord(,,) exit" << finl;
  exit();
  return 0; //!< For compilers
}
References Cerr, Process::exit(), and finl.
valeur_a_elem()
DoubleVect & Champ_Face::valeur_a_elem (const DoubleVect & position, DoubleVect & val, int le_poly) const inline override virtual
Implements Champ_implementation.
Definition at line 141 of file Champ_Face.h.
{
  return Champ_Face_implementation::valeur_a_elem(position, val, le_poly);
}
References Champ_Face_implementation::valeur_a_elem().
valeur_a_elem_compo()
double Champ_Face::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline override virtual
Implements Champ_implementation.
Definition at line 147 of file Champ_Face.h.
{
  return Champ_Face_implementation::valeur_a_elem_compo(position, le_poly, ncomp);
}
References Champ_Face_implementation::valeur_a_elem_compo().
valeur_aux_elems()
DoubleTab & Champ_Face::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & tab_valeurs) const inline override virtual
Implements Champ_implementation.
Definition at line 152 of file Champ_Face.h.
{
  return Champ_Face_implementation::valeur_aux_elems(positions, les_polys, tab_valeurs);
}
References Champ_Face_implementation::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_Face::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & tab_valeurs, int ncomp) const inline override virtual
Implements Champ_implementation.
Definition at line 158 of file Champ_Face.h.
{
  return Champ_Face_implementation::valeur_aux_elems_compo(positions, les_polys,
                                                           tab_valeurs, ncomp);
}
References Champ_Face_implementation::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_Face::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const inline override virtual
Implements Champ_implementation.
Definition at line 166 of file Champ_Face.h.
{
  return Champ_Face_implementation::valeur_aux_sommets(dom, val);
}
References Champ_Face_implementation::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Face::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int comp) const inline override virtual
Implements Champ_implementation.
Definition at line 170 of file Champ_Face.h.
{
  return Champ_Face_implementation::valeur_aux_sommets_compo(dom, val, comp);
}
References Champ_Face_implementation::valeur_aux_sommets_compo().
verifie_valeurs_cl()
void Champ_Face::verifie_valeurs_cl () override virtual
Reimplemented from Champ_Inc_base.
Definition at line 266 of file Champ_Face.cpp.
{
  const Zone_Cl_dis_base& zcl = zone_Cl_dis().valeur();
  int nb_cl = zcl.nb_cond_lim();
  DoubleTab& ch_tab = valeurs();
  int ndeb,nfin,num_face;
  for (int i=0; i<nb_cl; i++)
    {
      const Cond_lim_base& la_cl = zcl.les_conditions_limites(i).valeur();
      if (sub_type(Periodique,la_cl))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          ndeb = le_bord.num_premiere_face();
          nfin = ndeb + le_bord.nb_faces();
          int voisine;
          double moy;
          for (num_face=ndeb; num_face<nfin; num_face++)
            {
              voisine = la_cl_perio.face_associee(num_face-ndeb) + ndeb;
              if (ch_tab[num_face] != ch_tab[voisine])
                {
                  moy = 0.5*(ch_tab[num_face] + ch_tab[voisine]);
                  ch_tab[num_face] = moy;
                  ch_tab[voisine] = moy;
                }
            }
        }
    }
  ch_tab.echange_espace_virtuel();
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Periodique::face_associee(), Cond_lim_base::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Champ_Inc_base::valeurs(), and Champ_Inc_base::zone_Cl_dis().
zone_dis_base()
const Zone_dis_base & Champ_Face::zone_dis_base () const override virtual
Reimplemented from Champ_implementation.
Definition at line 54 of file Champ_Face.cpp.
{
  return la_zone_VDF.valeur();
}
References la_zone_VDF, and Ref_Zone_VDF::valeur().
Referenced by VDF_discretisation::creer_champ_vorticite().
zone_vdf()
const Zone_VDF & Champ_Face::zone_vdf () const inline override virtual
Implements Champ_Face_implementation.
Definition at line 206 of file Champ_Face.h.
{
  return la_zone_VDF.valeur();
}
References la_zone_VDF, and Ref_Zone_VDF::valeur().
Referenced by fixer_nb_valeurs_nodales(), and Zone_Cl_VDF::imposer_cond_lim().
Member Data Documentation
info_obj
const Type_info Champ_Face::info_obj static
Definition at line 46 of file Champ_Face.h.
la_zone_VDF
Ref_Zone_VDF Champ_Face::la_zone_VDF private
Definition at line 112 of file Champ_Face.h.
Referenced by affecter(), affecter_(), associer_zone_dis_base(), calcul_critere_Q(), calcul_duidxj(), calcul_grad_u(), calcul_S_barre(), calcul_S_barre_sans_contrib_paroi(), calcul_y_plus(), calculer_dercov_axi(), calculer_dscald_centre_element(), calculer_rotationnel_ordre2_centre_element(), compo_normale_sortante(), dimensionner_tenseur_Grad(), zone_dis_base(), and zone_vdf().
tau_croises_
DoubleTab Champ_Face::tau_croises_ private
termes extradiagonaux du tenseur Grad
Definition at line 115 of file Champ_Face.h.
Referenced by calculer_dercov_axi(), dimensionner_tenseur_Grad(), and tau_croises().
tau_diag_
DoubleTab Champ_Face::tau_diag_ private
termes diagonaux du tenseur Grad
Definition at line 114 of file Champ_Face.h.
Referenced by calculer_dercov_axi(), dimensionner_tenseur_Grad(), and tau_diag().
The documentation for this class was generated from the following files:
src/VDF/Champs/Champ_Face.h
src/VDF/Champs/Champ_Face.cpp
src/VDF/Champs/Champ_Face2.cpp
src/VDF/Champs/Champ_Face3.cpp
src/VDF/Champs/Champ_Face4.cpp