TRUST: Deriv_Iterateur_Source_PolyMAC_base Class Reference
Deriv_Iterateur_Source_PolyMAC_base Class Reference
class Iterateur_Source_PolyMAC
#include <Iterateur_Source_PolyMAC.h>
Public Member Functions
~Deriv_Iterateur_Source_PolyMAC_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Iterateur_Source_PolyMAC_base ()
Deriv_Iterateur_Source_PolyMAC_base (const Deriv_Iterateur_Source_PolyMAC_base &)
const
Iterateur_Source_PolyMAC_base & valeur () const
Iterateur_Source_PolyMAC_base & valeur ()
const
Iterateur_Source_PolyMAC_base * operator-> () const
Iterateur_Source_PolyMAC_base * operator-> ()
const
Deriv_Iterateur_Source_PolyMAC_base & operator= (const Iterateur_Source_PolyMAC_base &)
const
Deriv_Iterateur_Source_PolyMAC_base & operator= (const Deriv_Iterateur_Source_PolyMAC_base &)
operator const Iterateur_Source_PolyMAC_base & () const
operator Iterateur_Source_PolyMAC_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Deriv_Iterateur_Source_PolyMAC_base & self_cast (Objet_U &)
static const
Deriv_Iterateur_Source_PolyMAC_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Iterateur_Source_PolyMAC_base * pointeur_
Detailed Description
class Iterateur_Source_PolyMAC
Definition at line 35 of file Iterateur_Source_PolyMAC.h.
Constructor & Destructor Documentation
Deriv_Iterateur_Source_PolyMAC_base::~Deriv_Iterateur_Source_PolyMAC_base ()
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
Deriv_Iterateur_Source_PolyMAC_base::Deriv_Iterateur_Source_PolyMAC_base ()
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
Deriv_Iterateur_Source_PolyMAC_base::Deriv_Iterateur_Source_PolyMAC_base (const Deriv_Iterateur_Source_PolyMAC_base & t)
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
Member Function Documentation
Objet_U * Deriv_Iterateur_Source_PolyMAC_base::cree_instance () [static]
Reimplemented in Iterateur_Source_PolyMAC.
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
int Deriv_Iterateur_Source_PolyMAC_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Iterateur_Source_PolyMAC.
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
const Type_info * Deriv_Iterateur_Source_PolyMAC_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Iterateur_Source_PolyMAC.
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
const Type_info & Deriv_Iterateur_Source_PolyMAC_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
const Type_info * Deriv_Iterateur_Source_PolyMAC_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Iterateur_Source_PolyMAC.
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
Deriv_Iterateur_Source_PolyMAC_base::operator const Iterateur_Source_PolyMAC_base & () const
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
Deriv_Iterateur_Source_PolyMAC_base::operator Iterateur_Source_PolyMAC_base & ()
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
const Iterateur_Source_PolyMAC_base * Deriv_Iterateur_Source_PolyMAC_base::operator-> () const [inline]
Definition at line 35 of file Iterateur_Source_PolyMAC.h.
: public DERIV(Iterateur_Source_PolyMAC_base)
Iterateur_Source_PolyMAC_base * Deriv_Iterateur_Source_PolyMAC_base::operator-> () [inline]
Definition at line 35 of file Iterateur_Source_PolyMAC.h.
: public DERIV(Iterateur_Source_PolyMAC_base)
const Deriv_Iterateur_Source_PolyMAC_base & Deriv_Iterateur_Source_PolyMAC_base::operator= (const Deriv_Iterateur_Source_PolyMAC_base & t)
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
const Deriv_Iterateur_Source_PolyMAC_base & Deriv_Iterateur_Source_PolyMAC_base::operator= (const Iterateur_Source_PolyMAC_base & t)
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
Referenced by Iterateur_Source_PolyMAC::Iterateur_Source_PolyMAC().
Sortie & Deriv_Iterateur_Source_PolyMAC_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Iterateur_Source_PolyMAC.
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
Entree & Deriv_Iterateur_Source_PolyMAC_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Iterateur_Source_PolyMAC.
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
const Deriv_Iterateur_Source_PolyMAC_base & Deriv_Iterateur_Source_PolyMAC_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Iterateur_Source_PolyMAC.
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
Deriv_Iterateur_Source_PolyMAC_base & Deriv_Iterateur_Source_PolyMAC_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Iterateur_Source_PolyMAC.
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
void Deriv_Iterateur_Source_PolyMAC_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
unsigned Deriv_Iterateur_Source_PolyMAC_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Iterateur_Source_PolyMAC.
Definition at line 25 of file Iterateur_Source_PolyMAC.cpp.
const Iterateur_Source_PolyMAC_base & Deriv_Iterateur_Source_PolyMAC_base::valeur () const [inline]
Definition at line 35 of file Iterateur_Source_PolyMAC.h.
Referenced by Iterateur_Source_PolyMAC::ajouter(), Iterateur_Source_PolyMAC::associer(), Iterateur_Source_PolyMAC::calculer(), Iterateur_Source_PolyMAC::completer_(), and Iterateur_Source_PolyMAC::evaluateur().
: public DERIV(Iterateur_Source_PolyMAC_base)
Iterateur_Source_PolyMAC_base & Deriv_Iterateur_Source_PolyMAC_base::valeur () [inline]
Definition at line 35 of file Iterateur_Source_PolyMAC.h.
: public DERIV(Iterateur_Source_PolyMAC_base)
Member Data Documentation
const Type_info Deriv_Iterateur_Source_PolyMAC_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Iterateur_Source_PolyMAC.
Definition at line 35 of file Iterateur_Source_PolyMAC.h.
Iterateur_Source_PolyMAC_base* Deriv_Iterateur_Source_PolyMAC_base::pointeur_ [private]
Definition at line 35 of file Iterateur_Source_PolyMAC.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Sources/Iterateur_Source_PolyMAC.h
src/PolyMAC/Sources/Iterateur_Source_PolyMAC.cpp