TRUST: Champ_Fonc_Face_CoviMAC Class Reference
Champ_Fonc_Face_CoviMAC Class Reference
: class Champ_Fonc_Face_CoviMAC
<Description of class Champ_Fonc_Face_CoviMAC>
#include <Champ_Fonc_Face_CoviMAC.h>
Public Member Functions
Champ_Fonc_Face_CoviMAC ()
~Champ_Fonc_Face_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double)
Mise a jour en temps du champ.
void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & valeur_aux_sommets (const Domaine &domain, DoubleTab &result) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &domain, DoubleVect &result, int ncomp) const
renvoie la compo eme valeur aux sommets de dom.
Champ_base & affecter_ (const Champ_base &)
Affecte un Champ_base dans un Champ_Fonc_base.
const Zone_VF & zone_vf () const
virtual int fixer_nb_valeurs_nodales (int n)
Fixe le nombre de degres de liberte par composante.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Fonc_Face_CoviMAC & self_cast (Objet_U &)
static const
Champ_Fonc_Face_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Champ_base & le_champ (void)
virtual const Champ_base & le_champ (void) const
Protected Attributes
Ref_Zone_VF ref_zone_vf_
Detailed Description
: class Champ_Fonc_Face_CoviMAC
<Description of class Champ_Fonc_Face_CoviMAC>
Definition at line 40 of file Champ_Fonc_Face_CoviMAC.h.
Constructor & Destructor Documentation
Champ_Fonc_Face_CoviMAC::Champ_Fonc_Face_CoviMAC ()
Definition at line 30 of file Champ_Fonc_Face_CoviMAC.cpp.
Champ_Fonc_Face_CoviMAC::~Champ_Fonc_Face_CoviMAC ()
Definition at line 30 of file Champ_Fonc_Face_CoviMAC.cpp.
Member Function Documentation
Champ_base & Champ_Fonc_Face_CoviMAC::affecter_ (const Champ_base & ch) [virtual]
Affecte un Champ_base dans un Champ_Fonc_base.
Returns:
Champ_base&
Signification: le resultat de l'affectation (*this) (avec upcast)
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 84 of file Champ_Fonc_Face_CoviMAC.cpp.
References Objet_U::dimension, DoubleTab::dimension_tot(), Zone_CoviMAC::face_normales(), Zone_VF::face_surfaces(), Zone_VF::nb_faces_tot(), ref_cast, ref_zone_vf_, DoubleTab::resize(), sub_type, Ref_Zone_VF::valeur(), Champ_base::valeur_aux(), Champ_Proto::valeurs(), Champ_Don_base::valeurs(), and Zone_VF::xv().
{
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC,ref_zone_vf_.valeur());
  const DoubleTab& nf = zone.face_normales(), &xv = zone.xv();
  const DoubleVect& fs = zone.face_surfaces();
  DoubleTab& val = valeurs(), eval;
  if (sub_type(Champ_Uniforme, ch)) eval = ch.valeurs();
  else eval.resize(val.dimension_tot(0), dimension), ch.valeur_aux(xv,eval);
  for (int f = 0, unif = sub_type(Champ_Uniforme, ch); f < zone.nb_faces_tot(); f++)
    for (int r = 0; r < dimension; r++) val(f) += eval(unif ? 0 : f, r) * nf(f, r) / fs(f);
  return *this;
}
void Champ_Fonc_Face_CoviMAC::associer_zone_dis_base (const Zone_dis_base & z_dis) [virtual]
Implements Champ_Fonc_base.
Definition at line 53 of file Champ_Fonc_Face_CoviMAC.cpp.
References ref_cast, and ref_zone_vf_.
{
  ref_zone_vf_=ref_cast(Zone_VF, z_dis);
}
Objet_U * Champ_Fonc_Face_CoviMAC::cree_instance () [static]
Definition at line 30 of file Champ_Fonc_Face_CoviMAC.cpp.
int Champ_Fonc_Face_CoviMAC::duplique () const [virtual]
Implements Champ_Fonc_base.
Definition at line 30 of file Champ_Fonc_Face_CoviMAC.cpp.
int Champ_Fonc_Face_CoviMAC::fixer_nb_valeurs_nodales (int nb_noeuds) [virtual]
Fixe le nombre de degres de liberte par composante.
Returns:
int
Signification: le nombre de degres de liberte par composante
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 58 of file Champ_Fonc_Face_CoviMAC.cpp.
References Champ_Fonc_base::creer_tableau_distribue(), Zone_VF::md_vector_faces(), Field_base::nb_compo_, Zone_VF::nb_faces(), ref_cast, and zone_dis_base().
{
// j'utilise le meme genre de code que dans Champ_Fonc_P0_base
// sauf que je recupere le nombre de faces au lieu du nombre d'elements
//
// je suis tout de meme etonne du code utilise dans
// Champ_Fonc_P0_base::fixer_nb_valeurs_nodales()
// pour recuperer la zone discrete...
  const Champ_Fonc_base& self = ref_cast(Champ_Fonc_base, *this);
  const Zone_VF& la_zone_vf = ref_cast(Zone_VF,self.zone_dis_base());
  assert(n == la_zone_vf.nb_faces());
  const MD_Vector& md = la_zone_vf.md_vector_faces();
// Probleme: nb_comp vaut 2 mais on ne veut qu'une dimension !!!
// HACK :
  int old_nb_compo = nb_compo_;
  nb_compo_ = 1;
  creer_tableau_distribue(md);
  nb_compo_ = old_nb_compo;
  return n;
}
const Type_info * Champ_Fonc_Face_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 30 of file Champ_Fonc_Face_CoviMAC.cpp.
const Type_info * Champ_Fonc_Face_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 30 of file Champ_Fonc_Face_CoviMAC.cpp.
Champ_base & Champ_Fonc_Face_CoviMAC::le_champ (void) [protected, virtual]
Definition at line 43 of file Champ_Fonc_Face_CoviMAC.cpp.
Referenced by valeur_aux_elems().
{
  return *this;
}
const Champ_base & Champ_Fonc_Face_CoviMAC::le_champ (void) const [protected, virtual]
Definition at line 48 of file Champ_Fonc_Face_CoviMAC.cpp.
{
  return *this;
}
void Champ_Fonc_Face_CoviMAC::mettre_a_jour (double temps) [virtual]
Mise a jour en temps du champ.
Implements Champ_Fonc_base.
Definition at line 220 of file Champ_Fonc_Face_CoviMAC.cpp.
{
  return Champ_Fonc_base::mettre_a_jour( un_temps);
}
Sortie & Champ_Fonc_Face_CoviMAC::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 32 of file Champ_Fonc_Face_CoviMAC.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  os << que_suis_je() << " " << le_nom();
  return os;
}
Entree & Champ_Fonc_Face_CoviMAC::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 38 of file Champ_Fonc_Face_CoviMAC.cpp.
{
  return is;
}
DoubleTab & Champ_Fonc_Face_CoviMAC::remplir_coord_noeuds (DoubleTab & coord) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
DoubleTab&
Signification: renvoie toujours le parametre coord
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 192 of file Champ_Fonc_Face_CoviMAC.cpp.
{
  throw;
// return Champ_implementation_RT0::remplir_coord_noeuds(positions);
}
int Champ_Fonc_Face_CoviMAC::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
int
Signification: renvoie toujours 0
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 199 of file Champ_Fonc_Face_CoviMAC.cpp.
{
  throw;
// return Champ_implementation_RT0::remplir_coord_noeuds_et_polys(positions,polys);
}
Champ_Fonc_Face_CoviMAC & Champ_Fonc_Face_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_base.
Definition at line 30 of file Champ_Fonc_Face_CoviMAC.cpp.
const Champ_Fonc_Face_CoviMAC & Champ_Fonc_Face_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_base.
Definition at line 30 of file Champ_Fonc_Face_CoviMAC.cpp.
unsigned Champ_Fonc_Face_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 30 of file Champ_Fonc_Face_CoviMAC.cpp.
DoubleVect & Champ_Fonc_Face_CoviMAC::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Returns:
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 99 of file Champ_Fonc_Face_CoviMAC.cpp.
{
  throw;
// return Champ_implementation_RT0::valeur_a_elem(position,result,poly);
}
double Champ_Fonc_Face_CoviMAC::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
Definition at line 105 of file Champ_Fonc_Face_CoviMAC.cpp.
{
  throw;
// return Champ_implementation_RT0::valeur_a_elem_compo(position,poly,ncomp);
}
DoubleTab & Champ_Fonc_Face_CoviMAC::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
< (nb_compo != 1)
Reimplemented from Champ_base.
Definition at line 111 of file Champ_Fonc_Face_CoviMAC.cpp.
References Cerr, dabs(), IntTab::dimension(), DoubleTab::dimension(), DoubleTab::dimension_tot(), Zone_VF::elem_faces(), Process::exit(), Zone_CoviMAC::face_normales(), finl, le_champ(), Field_base::nb_comp(), DoubleTab::nb_dim(), ref_cast, IntVect::size(), Champ_Proto::valeurs(), and zone_vf().
{
  const Champ_base& cha=le_champ();
  int nb_compo=cha.nb_comp();
  if (val.nb_dim() == 1)
    {
      assert((val.dimension(0) == les_polys.size())||(val.dimension_tot(0) == les_polys.size()));
      assert(nb_compo == 1);
    }
  else if (val.nb_dim() == 2)
    {
      assert((val.dimension(0) == les_polys.size())||(val.dimension_tot(0) == les_polys.size()));
      assert(val.dimension(1) == nb_compo);
    }
  else
    {
      Cerr << "Erreur TRUST dans Champ_Face_implementation::valeur_aux_elems()" << finl;
      Cerr << "Le DoubleTab val a plus de 2 entrees" << finl;
      Process::exit();
    }
  const Zone_CoviMAC& zone_VF = ref_cast(Zone_CoviMAC,zone_vf());
// const Zone& zone_geom = zone_VDF.zone();
  const DoubleTab& normales = zone_VF.face_normales();
// const DoubleVect& surfaces = zone_VF.face_surfaces();
  const IntTab& elem_faces = zone_VF.elem_faces();
  const DoubleTab& ch = cha.valeurs();
  if (nb_compo == 1)
    {
      Cerr<<"Champ_Face_implementation::valeur_aux_elems"<<finl;
      Cerr <<"A scalar field cannot be of Champ_Face type." << finl;
      Process::exit();
    }
  else //!< (nb_compo != 1)
    {
      ArrOfDouble vale(nb_compo),s(nb_compo);
      for(int rang_poly=0; rang_poly<les_polys.size(); rang_poly++)
        {
          int le_poly=les_polys(rang_poly);
          if (le_poly == -1)
            for(int ncomp=0; ncomp<nb_compo; ncomp++)
              val(rang_poly,ncomp) = 0;
          else
            {
              vale=0;
              s=0;
              int nb_faces_elem_max=elem_faces.dimension(1);
              int nf;
              for (nf=0; nf<nb_faces_elem_max; nf++)
                {
                  int face=elem_faces(le_poly,nf);
                  if(face<0)
                    break;
                  for(int ncomp=0; ncomp<nb_compo; ncomp++)
                    {
                      vale(ncomp)+=ch(face)*normales(face,ncomp);
                      s(ncomp)+=dabs(normales(face,ncomp));
                    }
                }
              for(int ncomp=0; ncomp<nb_compo; ncomp++)
                val(rang_poly,ncomp)=vale(ncomp)/s(ncomp);
            }
        }
    }
  return val;
}
DoubleVect & Champ_Fonc_Face_CoviMAC::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 185 of file Champ_Fonc_Face_CoviMAC.cpp.
{
  throw;
// return Champ_implementation_RT0::valeur_aux_elems_compo(positions,polys,result,ncomp);
}
DoubleTab & Champ_Fonc_Face_CoviMAC::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const [virtual]
renvoie les valeurs aux sommets du Domaine dom
Reimplemented from Champ_base.
Definition at line 206 of file Champ_Fonc_Face_CoviMAC.cpp.
{
  throw;
// return Champ_implementation_RT0::valeur_aux_sommets(domain,result);
}
DoubleVect & Champ_Fonc_Face_CoviMAC::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int compo) const [virtual]
renvoie la compo eme valeur aux sommets de dom.
Reimplemented from Champ_base.
Definition at line 213 of file Champ_Fonc_Face_CoviMAC.cpp.
{
  throw;
// return Champ_implementation_RT0::valeur_aux_sommets_compo(domain,result,ncomp);
}
virtual const Zone_dis_base& Champ_Fonc_Face_CoviMAC::zone_dis_base () const [inline, virtual]
Implements Champ_Fonc_base.
Definition at line 54 of file Champ_Fonc_Face_CoviMAC.h.
References ref_zone_vf_, and Ref_Zone_VF::valeur().
Referenced by fixer_nb_valeurs_nodales().
  {
    return ref_zone_vf_.valeur();
  } ;
const Zone_VF& Champ_Fonc_Face_CoviMAC::zone_vf () const [inline]
Definition at line 72 of file Champ_Fonc_Face_CoviMAC.h.
References ref_zone_vf_, and Ref_Zone_VF::valeur().
Referenced by valeur_aux_elems().
  {
    return ref_zone_vf_.valeur();
  };
Member Data Documentation
const Type_info Champ_Fonc_Face_CoviMAC::info_obj [static]
Reimplemented from Champ_Fonc_base.
Definition at line 43 of file Champ_Fonc_Face_CoviMAC.h.
Ref_Zone_VF Champ_Fonc_Face_CoviMAC::ref_zone_vf_ [protected]
Definition at line 81 of file Champ_Fonc_Face_CoviMAC.h.
Referenced by affecter_(), associer_zone_dis_base(), zone_dis_base(), and zone_vf().
The documentation for this class was generated from the following files:
src/CoviMAC/Champs/Champ_Fonc_Face_CoviMAC.h
src/CoviMAC/Champs/Champ_Fonc_Face_CoviMAC.cpp