TRUST: Comm_Group Class Reference
Comm_Group Class Reference abstract
:
Cette classe decrit un groupe de processeurs sur lesquels
une portion de code s'execute simultanement. Elle fournit
toutes les methodes permettant d'echanger des donnees entre
les processeurs du groupe (mpsum, send, recv, ...),
et de synchroniser les processeurs (barrier).
Elle est specialisee selon le support reseau (MPI, PVM, ...)
Attention, ces methodes sont reservees a des operations de bas niveau<br>(noyau TRUST).
Dans le code courant, il faut utiliser les methodes classes de communications
de haut niveau :
(envoyer(), envoyer_broadcast(), class Schema_Comm, class Process, etc)
Pour creer un nouveau groupe et l'utiliser, voir class PE_Groups
Pour la procedure d'initialisation, voir PE_Groups::Initialize()
#include <Comm_Group.h>
Public Types
enum Collective_Op { COLL_SUM , COLL_MIN , COLL_MAX , COLL_PARTIAL_SUM }
enum TypeHint { CHAR , INT , DOUBLE }
Public Member Functions
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Comm_Group ()
~Comm_Group () override
Destructeur (pour l'instant, rien a faire)
virtual void abort () const =0
virtual void mp_collective_op (const double *x, double *resu, int n, Collective_Op op) const =0
virtual void mp_collective_op (const double *x, double *resu, const Collective_Op *op, int n) const =0
virtual void mp_collective_op (const int *x, int *resu, int n, Collective_Op op) const =0
virtual void mp_collective_op (const int *x, int *resu, const Collective_Op *op, int n) const =0
virtual void barrier (int tag) const =0
int get_new_tag () const
Cette fonction renvoie un nouveau tag de communication pour le groupe.
Effet de bord : incremente le membre group_communication_tag_.
int rank () const
Renvoie le rang du processeur local dans le groupe *this.
ou -1 si je ne suis pas dans le groupe.
int nproc () const
Renvoie le nombre de processeurs dans le groupe *this.
virtual void send_recv_start (const ArrOfInt &send_list, const ArrOfInt &send_size, const char *const *const send_buffers, const ArrOfInt &recv_list, const ArrOfInt &recv_size, char *const *const recv_buffers, TypeHint typehint=CHAR) const =0
virtual void send_recv_finish () const =0
virtual void send (int pe, const void *buffer, int size, int tag) const =0
Envoi bloquant.
virtual void recv (int pe, void *buffer, int size, int tag) const =0
Reception bloquante.
virtual void broadcast (void *buffer, int size, int pe_source) const =0
virtual void all_to_all (const void *src_buffer, void *dest_buffer, int data_size) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Comm_Group & self_cast (Objet_U &)
static const Comm_Group & self_cast (const Objet_U &)
static int check_enabled ()
static void set_check_enabled (int flag)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Comm_Group (const Comm_Group &)
interdit !
const Comm_Group & operator= (const Comm_Group &)
interdit !
virtual void init_group (const ArrOfInt &pe_list)
Cette fonction doit etre appelee simultanement
par tous les PEs du groupe current_group avec les memes parametres.
Les processeurs de la pe_list sont les rangs dans current_group() des
processeurs du nouveau groupe. Le maitre du groupe est le premier de la liste,
le rang du processeur courant, s'il est dans le groupe est determine par
son rang dans la liste. Il ne doit pas y avoir de doublon.
Cette fonction est appelee par les methodes init_group des classes derivees.
void init_group_trio (int nproc, int rank)
Initialise le groupe_TRUST().
Cette methode est appelee par init_group_trio() des classes derivees.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
int rank_
int nproc_
ArrOfInt local_ranks_
ArrOfInt world_ranks_
int group_number_
int group_tag_increment_
int group_communication_tag_
Static Private Attributes
static int check_enabled_ = 0
static int static_group_number_ = 0
Friends
class PE_Groups
Detailed Description
:
Cette classe decrit un groupe de processeurs sur lesquels
une portion de code s'execute simultanement. Elle fournit
toutes les methodes permettant d'echanger des donnees entre
les processeurs du groupe (mpsum, send, recv, ...),
et de synchroniser les processeurs (barrier).
Elle est specialisee selon le support reseau (MPI, PVM, ...)
Attention, ces methodes sont reservees a des operations de bas niveau<br>(noyau TRUST).
Dans le code courant, il faut utiliser les methodes classes de communications
de haut niveau :
(envoyer(), envoyer_broadcast(), class Schema_Comm, class Process, etc)
Pour creer un nouveau groupe et l'utiliser, voir class PE_Groups
Pour la procedure d'initialisation, voir PE_Groups::Initialize()
Definition at line 36 of file Comm_Group.h.
Member Enumeration Documentation
Collective_Op
enum Comm_Group::Collective_Op
Enumerator
COLL_SUM
COLL_MIN
COLL_MAX
COLL_PARTIAL_SUM
Definition at line 49 of file Comm_Group.h.
{ COLL_SUM, COLL_MIN, COLL_MAX, COLL_PARTIAL_SUM };
TypeHint
enum Comm_Group::TypeHint
Enumerator
CHAR
INT
DOUBLE
Definition at line 68 of file Comm_Group.h.
{ CHAR, INT, DOUBLE };
Constructor & Destructor Documentation
Comm_Group() [1/2]
Comm_Group::Comm_Group ()
Definition at line 40 of file Comm_Group.cpp.
{
  static const int group_increment = 32;
// Les tags des communications sont differents
// pour chaque groupe tant qu'il n'y a pas plus de 32 groupes.
// Ainsi, chaque communication de chaque groupe aura un tag different.
  rank_ = -1;
  nproc_ = -1;
  group_number_ = static_group_number_;
  group_tag_increment_ = group_increment;
  static_group_number_++;
  group_communication_tag_ = group_number_ % group_increment;
}
References group_communication_tag_, group_number_, group_tag_increment_, nproc_, rank_, and static_group_number_.
~Comm_Group()
Comm_Group::~Comm_Group () override
Destructeur (pour l'instant, rien a faire)
Definition at line 70 of file Comm_Group.cpp.
{
}
Comm_Group() [2/2]
Comm_Group::Comm_Group (const Comm_Group & a) protected
interdit !
Le constructeur par copie est interdit !
Definition at line 56 of file Comm_Group.cpp.
                                         : Objet_U(a)
{
  Cerr << "Comm_Group::Comm_Group(const Comm_Group &) error" << finl;
  exit();
}
References Cerr, Process::exit(), and finl.
Member Function Documentation
abort()
virtual void Comm_Group::abort () const pure virtual
Implemented in Comm_Group_MPI, and Comm_Group_Noparallel.
Referenced by build_medfield(), and Process::exit().
all_to_all()
virtual void Comm_Group::all_to_all (const void * src_buffer, void * dest_buffer, int data_size) const pure virtual
Implemented in Comm_Group_MPI, and Comm_Group_Noparallel.
Referenced by envoyer_all_to_all().
barrier()
virtual void Comm_Group::barrier (int tag) const pure virtual
Implemented in Comm_Group_MPI, and Comm_Group_Noparallel.
Referenced by Process::barrier(), Schema_Comm::begin_comm(), Schema_Comm::echange_messages(), Schema_Comm::echange_taille(), Schema_Comm::end_comm(), PE_Groups::enter_group(), PE_Groups::exit_group(), init_group(), and Schema_Comm::operator=().
broadcast()
virtual void Comm_Group::broadcast (void * buffer, int size, int pe_source) const pure virtual
Implemented in Comm_Group_MPI, and Comm_Group_Noparallel.
Referenced by envoyer_broadcast_array(), and envoyer_broadcast_buffered_().
check_enabled()
int Comm_Group::check_enabled () inline static
Definition at line 136 of file Comm_Group.h.
{
  return check_enabled_;
}
References check_enabled_.
Referenced by assert_espace_virtuel_vect(), assert_invalide_items_non_calcules(), assert_parallel(), Comm_Group_MPI::barrier(), Schema_Comm::begin_comm(), comm_check_enabled(), declare_espace_virtuel_invalide(), Schema_Comm::echange_messages(), Schema_Comm::echange_taille(), Schema_Comm::end_comm(), Schema_Comm_Vecteurs::end_init(), PE_Groups::enter_group(), envoyer_array(), envoyer_broadcast_array(), PE_Groups::exit_group(), init_group(), Schema_Comm::operator=(), recevoir_array(), Comm_Group_MPI::send(), and Schema_Comm::set_send_recv_pe_list().
get_info()
const Type_info * Comm_Group::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Comm_Group_MPI, and Comm_Group_Noparallel.
Definition at line 23 of file Comm_Group.cpp.
get_new_tag()
int Comm_Group::get_new_tag () const inline
Cette fonction renvoie un nouveau tag de communication pour le groupe.
Effet de bord : incremente le membre group_communication_tag_.
Definition at line 144 of file Comm_Group.h.
{
// B.M. Cette fonctionnalite est finalement tres peu utile en pratique
// et quand le compteur depasse une limite ca plante mpi. Je desactive:
// group_communication_tag_ += group_tag_increment_;
  return group_communication_tag_;
}
References group_communication_tag_.
Referenced by Comm_Group_MPI::barrier(), Comm_Group_MPI::mppartial_sum(), and Comm_Group_MPI::send_recv_start().
info()
const Type_info * Comm_Group::info () static
Definition at line 23 of file Comm_Group.cpp.
init_group()
void Comm_Group::init_group (const ArrOfInt & pe_list) protected virtual
Cette fonction doit etre appelee simultanement
par tous les PEs du groupe current_group avec les memes parametres.
Les processeurs de la pe_list sont les rangs dans current_group() des
processeurs du nouveau groupe. Le maitre du groupe est le premier de la liste,
le rang du processeur courant, s'il est dans le groupe est determine par
son rang dans la liste. Il ne doit pas y avoir de doublon.
Cette fonction est appelee par les methodes init_group des classes derivees.
Reimplemented in Comm_Group_MPI, and Comm_Group_Noparallel.
Definition at line 82 of file Comm_Group.cpp.
{
// Tous les processeurs du groupe courant doivent arriver ici
  const Comm_Group& current = PE_Groups::current_group();
  current.barrier(0);
  nproc_ = pe_list.size_array();
  if (nproc_ == 0)
    {
      Cerr << "Comm_Group::set_group_properties : empty process list" << finl;
      exit();
    }
  rank_ = -1;
  const Comm_Group& groupe_trio = PE_Groups::groupe_TRUST();
  local_ranks_.resize_array(groupe_trio.nproc());
  local_ranks_ = -1;
  world_ranks_.resize_array(nproc_);
  for (int i = 0; i < nproc_; i++)
    {
// rank du pe dans current_group()
      const int pe = pe_list[i];
      if (check_enabled())
        {
          int pe_check = pe;
          envoyer_broadcast(pe_check, 0);
          if (pe_check != pe)
            {
              Cerr << "Comm_Group::set_group_properties : processes have different pe_lists" << finl;
              exit();
            }
        }
      if (pe < 0 || pe >= current.nproc_)
        {
          Cerr << "Comm_Group::set_group_properties : process "
               << pe << " is not in current_group()" << finl;
          exit();
        }
// rank du pe dans le groupe_TRUST
      const int world_rank = current.world_ranks_[pe];
      if (local_ranks_[world_rank] >= 0)
        {
          Cerr << "Comm_Group::set_group_properties : duplicate pe in pe_list" << finl;
          exit();
        }
      world_ranks_[i] = world_rank;
      local_ranks_[world_rank] = i;
      if (pe == current.rank_)
        rank_ = i;
    }
}
References barrier(), Cerr, check_enabled(), PE_Groups::current_group(), envoyer_broadcast(), Process::exit(), finl, PE_Groups::groupe_TRUST(), local_ranks_, nproc(), nproc_, rank_, TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::size_array(), and world_ranks_.
Referenced by PE_Groups::create_group(), Comm_Group_MPI::init_group(), and Comm_Group_Noparallel::init_group().
init_group_trio()
void Comm_Group::init_group_trio (int nproc, int rank) protected
Initialise le groupe_TRUST().
Cette methode est appelee par init_group_trio() des classes derivees.
Definition at line 139 of file Comm_Group.cpp.
{
  assert(arank >= 0 && arank < nproc_tot);
  rank_ = arank;
  nproc_ = nproc_tot;
  local_ranks_.resize_array(nproc_);
  world_ranks_.resize_array(nproc_);
  for (int i = 0; i < nproc_; i++)
    {
      local_ranks_[i] = i;
      world_ranks_[i] = i;
    }
}
References local_ranks_, nproc_, rank_, TRUSTArray< _TYPE_ >::resize_array(), and world_ranks_.
Referenced by Comm_Group_Noparallel::Comm_Group_Noparallel(), and Comm_Group_MPI::init_group_trio().
mp_collective_op() [1/4]
virtual void Comm_Group::mp_collective_op (const double * x, double * resu, const Collective_Op * op, int n) const pure virtual
Implemented in Comm_Group_MPI, and Comm_Group_Noparallel.
mp_collective_op() [2/4]
virtual void Comm_Group::mp_collective_op (const double * x, double * resu, int n, Collective_Op op) const pure virtual
Implemented in Comm_Group_MPI, and Comm_Group_Noparallel.
Referenced by is_parallel_object(), Process::mp_and(), mp_collective_op(), Process::mp_max(), Process::mp_min(), mp_operations_commun_(), Process::mp_sum(), and mpsum_multiple().
mp_collective_op() [3/4]
virtual void Comm_Group::mp_collective_op (const int * x, int * resu, const Collective_Op * op, int n) const pure virtual
Implemented in Comm_Group_MPI, and Comm_Group_Noparallel.
mp_collective_op() [4/4]
virtual void Comm_Group::mp_collective_op (const int * x, int * resu, int n, Collective_Op op) const pure virtual
Implemented in Comm_Group_MPI, and Comm_Group_Noparallel.
nproc()
int Comm_Group::nproc () const inline
Renvoie le nombre de processeurs dans le groupe *this.
Definition at line 162 of file Comm_Group.h.
{
  assert(nproc_ >= 0);
  return nproc_;
}
References nproc_.
Referenced by Comm_Group_MPI::all_to_allv(), envoyer_all_to_all(), envoyer_all_to_all_(), envoyer_array(), envoyer_buffered_(), exchange_data(), Schema_Comm_Vecteurs_Static_Data::init(), init_group(), Comm_Group_MPI::init_group(), Comm_Group_MPI::mppartial_sum(), Process::nproc(), Comm_Group_MPI::ptop_send_recv(), Comm_Group_MPI::recv(), reverse_send_recv_pe_list(), Comm_Group_MPI::send(), and Comm_Group_MPI::send_recv_start().
operator=()
const Comm_Group & Comm_Group::operator= (const Comm_Group &) protected
interdit !
La copie est interdite !
Definition at line 63 of file Comm_Group.cpp.
{
  exit();
  return *this;
}
References Process::exit().
printOn()
Sortie & Comm_Group::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Comm_Group_MPI, and Comm_Group_Noparallel.
Definition at line 28 of file Comm_Group.cpp.
{
  exit();
  return os;
}
References Process::exit().
rank()
int Comm_Group::rank () const inline
Renvoie le rang du processeur local dans le groupe *this.
ou -1 si je ne suis pas dans le groupe.
Definition at line 155 of file Comm_Group.h.
{
  return rank_;
}
References rank_.
Referenced by envoyer_all_to_all_(), envoyer_array(), envoyer_broadcast_buffered_(), Process::je_suis_maitre(), Process::me(), Comm_Group_MPI::mppartial_sum(), and recevoir_array().
readOn()
Entree & Comm_Group::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Comm_Group_MPI, and Comm_Group_Noparallel.
Definition at line 34 of file Comm_Group.cpp.
{
  exit();
  return is;
}
References Process::exit().
recv()
virtual void Comm_Group::recv (int pe, void * buffer, int size, int tag) const pure virtual
Reception bloquante.
Implemented in Comm_Group_MPI, and Comm_Group_Noparallel.
Referenced by recevoir_array(), recevoir_buffered_(), and EcrFicPartage::syncfile().
self_cast() [1/2]
const Comm_Group & Comm_Group::self_cast (const Objet_U & r) static
Definition at line 23 of file Comm_Group.cpp.
self_cast() [2/2]
Comm_Group & Comm_Group::self_cast (Objet_U & r) static
Definition at line 23 of file Comm_Group.cpp.
send()
virtual void Comm_Group::send (int pe, const void * buffer, int size, int tag) const pure virtual
Envoi bloquant.
Implemented in Comm_Group_MPI, and Comm_Group_Noparallel.
Referenced by envoyer_array(), envoyer_buffered_(), and EcrFicPartage::syncfile().
send_recv_finish()
virtual void Comm_Group::send_recv_finish () const pure virtual
Implemented in Comm_Group_MPI, and Comm_Group_Noparallel.
Referenced by Schema_Comm_Vecteurs::exchange(), and exchange_data().
send_recv_start()
virtual void Comm_Group::send_recv_start (const ArrOfInt & send_list, const ArrOfInt & send_size, const char *const *const send_buffers, const ArrOfInt & recv_list, const ArrOfInt & recv_size, char *const *const recv_buffers, TypeHint typehint = CHAR) const pure virtual
Implemented in Comm_Group_MPI, and Comm_Group_Noparallel.
Referenced by Schema_Comm_Vecteurs::exchange(), and exchange_data().
set_check_enabled()
void Comm_Group::set_check_enabled (int flag) static
Definition at line 153 of file Comm_Group.cpp.
{
  if (flag)
    check_enabled_ = 1;
  else
    check_enabled_ = 0;
}
References check_enabled_.
Referenced by mon_main::init_parallel().
Friends And Related Function Documentation
PE_Groups
friend class PE_Groups friend
Definition at line 105 of file Comm_Group.h.
Member Data Documentation
check_enabled_
int Comm_Group::check_enabled_ = 0 static private
Definition at line 108 of file Comm_Group.h.
Referenced by check_enabled(), and set_check_enabled().
group_communication_tag_
int Comm_Group::group_communication_tag_ mutable private
Definition at line 133 of file Comm_Group.h.
Referenced by Comm_Group(), and get_new_tag().
group_number_
int Comm_Group::group_number_ private
Definition at line 125 of file Comm_Group.h.
Referenced by Comm_Group().
group_tag_increment_
int Comm_Group::group_tag_increment_ private
Definition at line 130 of file Comm_Group.h.
Referenced by Comm_Group().
info_obj
const Type_info Comm_Group::info_obj static
Definition at line 38 of file Comm_Group.h.
local_ranks_
ArrOfInt Comm_Group::local_ranks_ private
Definition at line 118 of file Comm_Group.h.
Referenced by init_group(), init_group_trio(), and PE_Groups::rank_translate().
nproc_
int Comm_Group::nproc_ private
Definition at line 114 of file Comm_Group.h.
Referenced by Comm_Group(), init_group(), init_group_trio(), and nproc().
rank_
int Comm_Group::rank_ private
Definition at line 112 of file Comm_Group.h.
Referenced by Comm_Group(), init_group(), init_group_trio(), and rank().
static_group_number_
int Comm_Group::static_group_number_ = 0 static private
Definition at line 109 of file Comm_Group.h.
Referenced by Comm_Group().
world_ranks_
ArrOfInt Comm_Group::world_ranks_ private
Definition at line 121 of file Comm_Group.h.
Referenced by init_group(), init_group_trio(), and PE_Groups::rank_translate().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Comm_Group.h
src/Kernel/Utilitaires/Comm_Group.cpp