TRUST: Flux_interfacial_CoviMAC Class Reference
Flux_interfacial_CoviMAC Class Reference
Classe Flux_interfacial_CoviMAC
Cette classe implemente dans CoviMAC un operateur de frottement interfacial
de la forme F_{kl} = - F_{lk} = - C_{kl} (u_k - u_l)
le calcul de C_{kl} est realise par la hierarchie Coefficient_Flux_interfacial_base.
#include <Flux_interfacial_CoviMAC.h>
Public Member Functions
Flux_interfacial_CoviMAC ()
~Flux_interfacial_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int has_interface_blocs () const
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void check_multiphase_compatibility () const
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
void associer_pb (const Probleme_base &)
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Flux_interfacial_CoviMAC & self_cast (Objet_U &)
static const
Flux_interfacial_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Private Attributes
Ref_Correlation correlation_
Detailed Description
Classe Flux_interfacial_CoviMAC
Cette classe implemente dans CoviMAC un operateur de frottement interfacial
de la forme F_{kl} = - F_{lk} = - C_{kl} (u_k - u_l)
le calcul de C_{kl} est realise par la hierarchie Coefficient_Flux_interfacial_base.
Definition at line 39 of file Flux_interfacial_CoviMAC.h.
Constructor & Destructor Documentation
Flux_interfacial_CoviMAC::Flux_interfacial_CoviMAC ()
Definition at line 33 of file Flux_interfacial_CoviMAC.cpp.
Flux_interfacial_CoviMAC::~Flux_interfacial_CoviMAC ()
Definition at line 33 of file Flux_interfacial_CoviMAC.cpp.
Member Function Documentation
void Flux_interfacial_CoviMAC::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) [virtual]
Reimplemented from Source_base.
void Flux_interfacial_CoviMAC::associer_pb (const Probleme_base &) [inline, virtual]
Implements Source_base.
Definition at line 52 of file Flux_interfacial_CoviMAC.h.
{ };
void Flux_interfacial_CoviMAC::associer_zones (const Zone_dis & , const Zone_Cl_dis &) [inline, virtual]
Implements Source_base.
Definition at line 51 of file Flux_interfacial_CoviMAC.h.
{ };
void Flux_interfacial_CoviMAC::check_multiphase_compatibility () const [inline, virtual]
Reimplemented from MorEqn.
Definition at line 49 of file Flux_interfacial_CoviMAC.h.
{}; //of course
Objet_U * Flux_interfacial_CoviMAC::cree_instance () [static]
Definition at line 33 of file Flux_interfacial_CoviMAC.cpp.
void Flux_interfacial_CoviMAC::dimensionner_blocs (matrices_t matrices) [virtual]
Reimplemented from Source_base.
int Flux_interfacial_CoviMAC::duplique () const [virtual]
Implements Source_base.
Definition at line 33 of file Flux_interfacial_CoviMAC.cpp.
const Type_info * Flux_interfacial_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 33 of file Flux_interfacial_CoviMAC.cpp.
int Flux_interfacial_CoviMAC::has_interface_blocs () const [inline, virtual]
Reimplemented from Source_base.
Definition at line 43 of file Flux_interfacial_CoviMAC.h.
  {
    return 1;
  }
const Type_info * Flux_interfacial_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 33 of file Flux_interfacial_CoviMAC.cpp.
void Flux_interfacial_CoviMAC::mettre_a_jour (double temps) [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 53 of file Flux_interfacial_CoviMAC.h.
{ };
Sortie & Flux_interfacial_CoviMAC::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 35 of file Flux_interfacial_CoviMAC.cpp.
{
  return os;
}
Entree & Flux_interfacial_CoviMAC::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 40 of file Flux_interfacial_CoviMAC.cpp.
References correlation_, MorEqn::equation(), Process::exit(), Pb_Multiphase::get_correlation(), Pb_Multiphase::has_correlation(), Objet_U::que_suis_je(), and ref_cast.
{
  const Pb_Multiphase& pbm = ref_cast(Pb_Multiphase, equation().probleme());
  if (!pbm.has_correlation("flux_interfacial")) Process::exit(que_suis_je() + " : a flux_interfacial correlation must be defined in the global correlations { } block!");
  correlation_ = pbm.get_correlation("flux_interfacial");
  return is;
}
const Flux_interfacial_CoviMAC & Flux_interfacial_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Definition at line 33 of file Flux_interfacial_CoviMAC.cpp.
Flux_interfacial_CoviMAC & Flux_interfacial_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Definition at line 33 of file Flux_interfacial_CoviMAC.cpp.
unsigned Flux_interfacial_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 33 of file Flux_interfacial_CoviMAC.cpp.
Member Data Documentation
Ref_Correlation Flux_interfacial_CoviMAC::correlation_ [private]
Definition at line 53 of file Flux_interfacial_CoviMAC.h.
Referenced by readOn().
const Type_info Flux_interfacial_CoviMAC::info_obj [static]
Reimplemented from Source_base.
Definition at line 41 of file Flux_interfacial_CoviMAC.h.
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/CoviMAC/Flux_interfacial_CoviMAC.h
src/ThHyd/Multiphase/CoviMAC/Flux_interfacial_CoviMAC.cpp