TRUST: SETS Class Reference
SETS Class Reference
#include <SETS.h>
Public Member Functions
~SETS ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
SETS ()
Entree & lire (const Motcle &, Entree &) override
int nb_valeurs_temporelles_pression () const override
bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok) override
void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok) override
double get_default_growth_factor () const override
double unknown_positivation (const DoubleTab &uk, DoubleTab &incr)
brings to 0 unknowns that should stay positive
Public Member Functions inherited from Simpler
Simpler ()
~Simpler ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok) override
Public Member Functions inherited from Simple
~Simple ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Simple ()
bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok) override
void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok) override
bool iterer_eqs (List_Ref_Equation_base eqs, int compteur, int &ok) override
Public Member Functions inherited from Simpler_Base
~Simpler_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int max_iter_implicite ()
int max_iter_implicite () const
bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok) override=0
virtual void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok)=0
void assembler_matrice_pression_implicite (Equation_base &eqn_NS, const Matrice_Morse &matrice, Matrice &matrice_en_pression_2)
Parametre_equation & get_and_set_parametre_equation (Equation_base &) override
retourne le parametre_implicte de l'equation si il existe si il n'existe pas le cree...
si les params sont vides on copie ceux du simpler
Parametre_implicite & get_and_set_parametre_implicite (Equation_base &eqn)
Public Member Functions inherited from Solveur_non_lineaire
Solveur_non_lineaire ()
~Solveur_non_lineaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Solveur_Implicite_Base
Solveur_Implicite_Base ()
~Solveur_Implicite_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok)=0
virtual bool iterer_eqs (List_Ref_Equation_base eqs, int n, int &ok)
virtual bool est_compatible_avec_th_mono () const
virtual int nb_valeurs_temporelles_pression () const
virtual double get_default_facsec_max () const
virtual double get_default_growth_factor () const
virtual Parametre_equation & get_and_set_parametre_equation (Equation_base &eqn)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static SETS & self_cast (Objet_U &)
static const SETS & self_cast (const Objet_U &)
static void eliminer (const std::vector< std::set< std::pair< std::string, int > > > ordre, const std::string inco_p, const std::map< std::string, matrices_t > &mats, const tabs_t &sec, std::map< std::string, Matrice_Morse > &A_p, tabs_t &b_p)
static void assembler (const std::string inco_p, const std::map< std::string, Matrice_Morse > &A_p, const tabs_t &b_p, const std::map< std::string, matrices_t > &mats, const tabs_t &sec, Matrice_Morse &matrice, DoubleTab &secmem, int p_degen)
Static Public Member Functions inherited from Simpler
static Objet_U * cree_instance ()
static const Type_info * info ()
static Simpler & self_cast (Objet_U &)
static const Simpler & self_cast (const Objet_U &)
Static Public Member Functions inherited from Simple
static Objet_U * cree_instance ()
static const Type_info * info ()
static Simple & self_cast (Objet_U &)
static const Simple & self_cast (const Objet_U &)
Static Public Member Functions inherited from Simpler_Base
static const Type_info * info ()
static Simpler_Base & self_cast (Objet_U &)
static const Simpler_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_non_lineaire
static const Type_info * info ()
static Solveur_non_lineaire & self_cast (Objet_U &)
static const Solveur_non_lineaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_Implicite_Base
static const Type_info * info ()
static Solveur_Implicite_Base & self_cast (Objet_U &)
static const Solveur_Implicite_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
int iteration
int p_degen = -1
int sets_
1 si on fait l'etape de prediction des vitesses
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Simpler
static const Type_info info_obj
Static Public Attributes inherited from Simple
static const Type_info info_obj
Static Public Attributes inherited from Simpler_Base
static const Type_info info_obj
Static Public Attributes inherited from Solveur_non_lineaire
static const Type_info info_obj
Static Public Attributes inherited from Solveur_Implicite_Base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Simpler
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Simple
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Entree & lire (const Motcle &, Entree &) override
void calculer_correction_en_vitesse (const DoubleTrav &correction_en_pression, DoubleTrav &gradP, DoubleTrav &correction_en_vitesse, const Matrice_Morse &matrice, const Operateur_Grad &gradient)
Protected Member Functions inherited from Simpler_Base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual Entree & lire (const Motcle &, Entree &)=0
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int iter_min_ = 1
int iter_max_ = 10
int first_call_
std::map< std::string, double > crit_conv
std::map< std::string, matrices_t > mats
matrices : mats[nom de l'inconnue de l'equation][nom de l'autre inconnue] = matrice
Matrice_Bloc mat_semi_impl
std::map< std::string, Matrice_Morse > mat_pred
std::map< std::string, Matrice_Morse > A_p
Matrice_Morse matrice_pression
Protected Attributes inherited from Simple
DoubleTab Ustar_old
double alpha_
double beta_
int with_d_rho_dt_
std::map< std::vector< intptr_t >, Matrice_Bloc > mbloc
Protected Attributes inherited from Simpler_Base
Parametre_implicite param_defaut_
int is_seuil_convg_variable
double facteur_convg_
int no_qdm_
int controle_residu_
Detailed Description
Definition at line 32 of file SETS.h.
Constructor & Destructor Documentation
~SETS()
SETS::~SETS ()
Definition at line 48 of file SETS.cpp.
SETS()
SETS::SETS ()
Definition at line 52 of file SETS.cpp.
{
  sets_ = 1;
}
References sets_.
Member Function Documentation
assembler()
void SETS::assembler (const std::string inco_p, const std::map< std::string, Matrice_Morse > & A_p, const tabs_t & b_p, const std::map< std::string, matrices_t > & mats, const tabs_t & sec, Matrice_Morse & matrice, DoubleTab & secmem, int p_degen) static
Definition at line 626 of file SETS.cpp.
{
  secmem = sec.at(inco_p);
  int i, ib, j, k, l, np = secmem.dimension_tot(0), m, M = secmem.line_size(), deb, fin, pos, col;
  /* calc(i) = 1 si on doit remplir les lignes [N * i, (N + 1) * i[ de la matrice */
  ArrOfBit calc(np);
  if (secmem.get_md_vector().non_nul()) MD_Vector_tools::get_sequential_items_flags(secmem.get_md_vector(), calc);
  else calc = 1;
  if (!P.nb_colonnes()) //dimensionnement au premier passage
    {
      IntTrav stencil(0, 2);
      stencil.set_smart_resize(1);
      for (auto &&n_m : mats.at(inco_p))
        if (n_m.second && n_m.second->nb_colonnes())
          {
            const Matrice_Morse& Mp = *n_m.second, *Ap = n_m.first != inco_p ? &A_p.at(n_m.first) : NULL;
            for (i = 0; i < np; i++)
              if (calc[i])
                for (ib = M * i, m = 0; m < M; m++, ib++)
                  for (j = Mp.get_tab1()(ib) - 1; j < Mp.get_tab1()(ib + 1) - 1; j++)
                    for (k = Mp.get_tab2()(j) - 1, l = (Ap ? Ap->get_tab1()(k) - 1 : 0); l < (Ap ? Ap->get_tab1()(k + 1) - 1 : 1); l++)
                      stencil.append_line(ib, Ap ? Ap->get_tab2()(l) - 1 : k);
          }
      tableau_trier_retirer_doublons(stencil);
      Matrix_tools::allocate_morse_matrix(secmem.size_totale(), secmem.size_totale(), stencil, P);
    }
  /* remplissage de P / secmem */
  P.get_set_coeff() = 0;
  for (auto &&n_m : mats.at(inco_p))
    if (n_m.first == inco_p && n_m.second && n_m.second->nb_colonnes()) P += *n_m.second; /* dependance directe en inco_p -> on ajoute */
    else if (n_m.second && n_m.second->nb_colonnes()) /* dependance en une autre inconnue -> produit Mp.Ap + modif second membre */
      {
        const Matrice_Morse& Mp = *n_m.second, &Ap = A_p.at(n_m.first);
        const DoubleTab& bp = b_p.at(n_m.first);
        for (i = 0; i < np; i++)
          if (calc[i])
            for (ib = M * i, m = 0; m < M; m++, ib++)
              for (deb = P.get_tab1()(ib) - 1, fin = P.get_tab1()(ib + 1) - 1, j = Mp.get_tab1()(ib) - 1; j < Mp.get_tab1()(ib + 1) - 1; j++)
                for (k = Mp.get_tab2()(j) - 1, secmem(i, m) -= Mp.get_coeff()(j) * bp.addr()[k], l = Ap.get_tab1()(k) - 1, pos = deb - 1; l < Ap.get_tab1()(k + 1) - 1; l++)
                  {
                    for (col = Ap.get_tab2()(l), pos++; P.get_tab2()(pos) != col && pos < fin; ) pos++;
                    assert(P.get_tab2()(pos) == col);
                    P.get_set_coeff()(pos) += Mp.get_coeff()(j) * Ap.get_coeff()(l);
                  }
      }
  double diag = P.get_coeff()(0);
  if (p_degen && !Process::me())
    for (i = 0; i < P.get_tab1()(1) - 1; i++) P.get_set_coeff()(i) += diag; //de-degeneration de la matrice
}
References A_p, TRUSTArray< _TYPE_ >::addr(), Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), TRUSTTab< _TYPE_ >::dimension_tot(), Matrice_Morse::get_coeff(), TRUSTVect< _TYPE_ >::get_md_vector(), MD_Vector_tools::get_sequential_items_flags(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), TRUSTVect< _TYPE_ >::line_size(), mats, Process::me(), Matrice_Morse::nb_colonnes(), MD_Vector::non_nul(), p_degen, TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTVect< _TYPE_ >::size_totale(), and tableau_trier_retirer_doublons().
cree_instance()
Objet_U * SETS::cree_instance () static
Definition at line 48 of file SETS.cpp.
duplique()
int SETS::duplique () const override virtual
Implements Objet_U.
Reimplemented in ICE.
Definition at line 48 of file SETS.cpp.
eliminer()
void SETS::eliminer (const std::vector< std::set< std::pair< std::string, int > > > ordre, const std::string inco_p, const std::map< std::string, matrices_t > & mats, const tabs_t & sec, std::map< std::string, Matrice_Morse > & A_p, tabs_t & b_p) static
Definition at line 431 of file SETS.cpp.
{
  int i, j, jb, k, l, lb, m, oMl, oMg, M, n, oNl, oNg, N, prems = !A_p.size(), infoo = 0; //si A_p est vide, premier passage -> on doit dimensionner
  const Matrice_Morse * A;
  char trans = 'T';
  /* decoupage des inconnues de sec en parties par DoubleTab_parts */
  std::map<std::pair<std::string, int>, int> offs; //offs[{inco, bloc}] : offset du bloc k de l'inconnue inco
  std::map<std::pair<std::string, int>, std::array<int, 2>> dims; //dims[{inco, bloc}] : dimension 0/ line_size() du bloc k de inco
  for (auto &&n_v : sec)
    {
      ConstDoubleTab_parts part(n_v.second);
      for (i = 0; i < part.size(); i++)
        {
          offs[ {n_v.first, i}] = offs.count({ n_v.first, i - 1 }) ? offs[ { n_v.first, i - 1 }] + dims[ { n_v.first, i - 1 }][0] * dims[ { n_v.first, i - 1 }][1] : 0;
          dims[ {n_v.first, i}] = { part[i].dimension_tot(0), part[i].line_size() };
        }
    }
  /* boucle sur les blocs */
  std::set<std::pair<std::string, int>> e_ib; //liste des { variable, bloc } deja elimines
  std::set<std::string> e_i; //liste des variables deja eliminees
  for (auto &&bloc : ordre)
    {
      std::set<std::string> i_bloc, dep; //variables du bloc, variables deja eliminees dont le bloc depend
      for (auto &&i_b : bloc) i_bloc.insert(i_b.first);
      for (auto &&i_b : bloc)
        for (auto && v_m : mats.at(i_b.first))
          if (v_m.second->nb_colonnes() && v_m.first != inco_p && e_i.count(v_m.first) && !i_bloc.count(v_m.first))
            dep.insert(v_m.first);
      /* lignes du bloc a traiter */
      std::pair<std::string, int> i_b0 = *bloc.begin();//premiere inconnue du bloc
      IntTrav calc(dims[i_b0][0]); //calc[i] = 1 si on doit traiter l'item i
      for (A = mats.at(i_b0.first).at(i_b0.first), oMg = offs[i_b0], M = dims[i_b0][1], i = 0; i < calc.size_array(); i++)
        if (A->get_tab1()(oMg + M * i + 1) > A->get_tab1()(oMg + M * i)) calc(i) = 1; //on traite toutes les lignes dont la matrice est remplie
      if (prems) //premier passage -> dimensionnement des A_p
        {
          /* verification de la compatibilite des inconnues du bloc -> avec les MD_Vector renseignes dans sec */
          for (auto &&i_b : bloc)
            if (dims[i_b0][0] != dims[i_b][0])
              Cerr << "SETS::eliminer() : discretisation des inconnues" << i_b0.first << "/" << i_b0.second << " et " << i_b.first
                   << "/" << i_b.second << " incompatibles!" << finl, Process::exit();
          std::vector<std::set<int>> stencil(calc.size_array()); //stencil[i] -> stencil de l'item i (a demultiplier par le line_size() de chaque variable)
          for (auto &&i_b : bloc)
            for (auto &&v_m : mats.at(i_b.first))
              if (v_m.second->nb_colonnes())
                {
                  oMg = offs[i_b], M = dims[i_b][1];
                  if (v_m.first == inco_p) //dependance directe en inco_p
                    {
                      for (i = 0; i < calc.size_array(); i++)
                        if (calc[i])
                          for (j = v_m.second->get_tab1()(oMg + M * i) - 1; j < v_m.second->get_tab1()(oMg + M * (i + 1)) - 1; j++) //dependances de toutes les lignes
                            stencil[i].insert(v_m.second->get_tab2()(j) - 1);
                    }
                  else if (e_i.count(v_m.first) || i_bloc.count(v_m.first)) //dependance en une variable partiellement / totalement eliminee
                    {
                      A = A_p.count(v_m.first) ? &A_p.at(v_m.first) : NULL;
                      for (i = 0; i < calc.size_array(); i++)
                        if (calc[i])
                          for (j = v_m.second->get_tab1()(oMg + M * i) - 1; j < v_m.second->get_tab1()(oMg + M * (i + 1)) - 1; j++)
{
                              for (jb = v_m.second->get_tab2()(j) - 1, k = 0; offs.count({ v_m.first, k + 1}) && jb >= offs.at({ v_m.first, k + 1 }); ) k++; //l : bloc de l'inconnue dont on depend
                              oNg = offs[ { v_m.first, k }], N = dims[ { v_m.first, k }][1], n = jb - oNg - N * i;
                              if (bloc.count({ v_m.first, k }) && n >= 0 && n < N) continue; //(variable, bloc) en cours d'elimination et coeff bloc-diagonal -> ok
                              else if (e_ib.count({ v_m.first, k }))  //(variable, bloc) elimine -> dependance en inco_p dans A_p
                                for (l = A->get_tab1()(jb) - 1; l < A->get_tab1()(jb + 1) - 1; l++)
                                  stencil[i].insert(A->get_tab2()(l) - 1);
                              else Cerr << "SETS::eliminer() : dependance ( " << i_b.first << "/" << i_b.second << " , "
                                          << v_m.first << "/" << k << " ) interdite!" << finl, Process::exit();
                            }
                    }
                  else Cerr << "SETS::eliminer() : dependance ( " << i_b.first << "/" << i_b.second << " , "
                              << v_m.first << " ) interdite!" << finl, Process::exit();
                }
          for (auto &&i_bl : bloc) //stencil par inconnue -> en demultipliant
            {
              IntTrav sten(0, 2);
              sten.set_smart_resize(1);
              for (oMg = offs[i_bl], M = dims[i_bl][1], i = 0; i < calc.size_array(); i++)
                if (calc[i])
                  for (m = 0; m < M; m++)
                    for (auto &&col : stencil[i]) sten.append_line(oMg + M * i + m, col);
              Matrice_Morse mat2;
              Matrix_tools::allocate_morse_matrix(sec.at(i_bl.first).size_totale(), sec.at(inco_p).size_totale(), sten, mat2);
              A_p[i_bl.first].nb_colonnes() ? A_p[i_bl.first] += mat2 : A_p[i_bl.first] = mat2; //A_p peut deja etre partiellement creee
            }
        }
      std::vector<std::string> vbloc(i_bloc.begin(), i_bloc.end()), vdep(dep.begin(), dep.end()); //sous forme de liste
      int nv = vbloc.size(), nd = vdep.size(), nb = 0; //nombre de variables du bloc, de dependances, taille totale
      std::vector<int> size, off_l, off_g; //par (variable, bloc) : taille dans le systeme local, offset dans le systeme local, offset dans les systemes globaux
      for (auto && i_b : bloc) off_l.push_back(nb), size.push_back(dims[i_b][1]), off_g.push_back(offs[i_b]), nb += size.back();
      std::vector<const Matrice_Morse *> pmat(nv), dAp(nd); //par variable : dependance directe en inco_p, des variables du bloc / deja resolues
      std::vector<std::vector<const Matrice_Morse *>> mat(nv), dmat(nv); //matrices des variables du bloc, des dependances
      std::vector<const DoubleTab*> vsec(nv), dbp(nd); //seconds membres des variables, vecteurs b_p des variables / des dependances
      std::vector<Matrice_Morse *> Ap(nv); //resultats : d{inco} = A_p[inco].d{inco_p} + b_p[inco] pour les variables du bloc
      std::vector<DoubleTab*> bp(nv);
      for (i = 0; i < nv; i++)
        {
          Ap[i] = &A_p[vbloc[i]], vsec[i] = &sec.at(vbloc[i]);
          if (!b_p.count(vbloc[i])) b_p[vbloc[i]] = *vsec[i]; //creation des b_p
          bp[i] = &b_p[vbloc[i]];
          const matrices_t& line = mats.at(vbloc[i]);
          pmat[i] = line.count(inco_p) && line.at(inco_p)->nb_colonnes() ? line.at(inco_p) : NULL;
          for ( mat[i].resize(nv), j = 0; j < nv; j++)  mat[i][j] = line.count(vbloc[j]) && line.at(vbloc[j])->nb_colonnes() ? line.at(vbloc[j]) : NULL;
          for (dmat[i].resize(nd), j = 0; j < nd; j++) dmat[i][j] = line.count(vdep[j]) && line.at(vdep[j])->nb_colonnes() ? line.at(vdep[j]) : NULL;
        }
      for (i = 0; i < nd; i++) dbp[i] = &b_p.at(vdep[i]), dAp[i] = &A_p.at(vdep[i]); //b_p / A_p des dependances
      DoubleTrav D(nb, nb), S; //bloc diagonal, seconds membres
      S.set_smart_resize(1);
      IntTrav piv(nb);
      for (i = 0; i < calc.size_array(); i++)
        if (calc[i])
          {
            int deb = Ap[0]->get_tab1()(off_g[0] + size[0] * i) - 1, fin = Ap[0]->get_tab1()(off_g[0] + size[0] * i + 1) - 1, ic = fin - deb, nc = ic + 1, pos, col;
            S.resize(nc, nb), S = 0; //second membre : 5(i, .) -> dependance en la i-eme colonne du stencil des Ap du bloc, S(ic, .) -> partie constante
// partie "second membre des equations"
            for (j = 0; j < nv; j++)
              for (M = size[j], oMg = off_g[j], oMl = off_l[j], m = 0; m < M; m++) S(ic, oMl + m) = vsec[j]->addr()[oMg + M * i + m];
            /* remplissage par les matrices du bloc : diagonale, second membre (si partie d'une variable deja eliminee) */
            for (D = 0, j = 0; j < nv; j++)
              for (M = size[j], oMg = off_g[j], oMl = off_l[j], k = 0; k < nv; k++)
                if (mat[j][k])
                  {
                    for (N = size[k], oNg = off_g[k], oNl = off_l[k], m = 0; m < M; m++)
                      for (l = mat[j][k]->get_tab1()(oMg + M * i + m) - 1; l < mat[j][k]->get_tab1()(oMg + M * i + m + 1) - 1; l++)
                        if ((n = (jb = mat[j][k]->get_tab2()(l) - 1) - oNg - N * i) >= 0 && n < N) //on est dans le bloc diagonal
                          D(oMl + m, oNl + n) = mat[j][k]->get_coeff()(l);
                        else //dependance en un bloc deja elimine
{
                            double coeff = mat[j][k]->get_coeff()(l);
                            S(ic, oMl + m) -= coeff * bp[k]->addr()[jb];
                            for (lb = Ap[k]->get_tab1()(jb) - 1, pos = deb - 1; lb < Ap[k]->get_tab1()(jb + 1) - 1; lb++)
{
                                for (col = Ap[k]->get_tab2()(lb), pos++; Ap[0]->get_tab2()(pos) != col && pos < fin; ) pos++;
                                assert(Ap[0]->get_tab2()(pos) == col);
                                S(pos - deb, oMl + m) -= coeff * Ap[k]->get_coeff()(lb);
                              }
                          }
                  }
// partie "dependance directe en inco_p" -> dans S([0, ic[, .)
            for (j = 0; j < nv; j++)
              if (pmat[j])
                for (M = size[j], oMg = off_g[j], oMl = off_l[j], m = 0; m < M; m++)
                  for (k = pmat[j]->get_tab1()(oMg + M * i + m) - 1, pos = deb - 1; k < pmat[j]->get_tab1()(oMg + M * i + m + 1) - 1; k++)
                    {
                      for (col = pmat[j]->get_tab2()(k), pos++; Ap[0]->get_tab2()(pos) != col && pos < fin; ) pos++;
                      assert(Ap[0]->get_tab2()(pos) == col);
                      S(pos - deb, oMl + m) -= pmat[j]->get_coeff()(k);
                    }
// partie "dependance en une variable hors bloc eliminee" -> b_p contribue a S(0, .), A_p contribue a S(1..nc, .)
            for (j = 0; j < nv; j++)
              for (k = 0; k < nd; k++)
                if (dmat[j][k])
                  for (M = size[j], oMg = off_g[j], oMl = off_l[j], m = 0; m < M; m++)
                    for (l = dmat[j][k]->get_tab1()(oMg + M * i + m) - 1; l < dmat[j][k]->get_tab1()(oMg + M * i + m + 1) - 1; l++)
                      {
                        double coeff = dmat[j][k]->get_coeff()(l);
                        jb = dmat[j][k]->get_tab2()(l) - 1, S(ic, oMl + m) -= coeff * dbp[k]->addr()[jb]; //partie "constante"
                        for (lb = dAp[k]->get_tab1()(jb) - 1, pos = deb - 1; lb < dAp[k]->get_tab1()(jb + 1) - 1; lb++) //partie "dependance en inco_p"
{
                            for (col = dAp[k]->get_tab2()(lb), pos++; Ap[0]->get_tab2()(pos) != col && pos < fin; ) pos++;
                            assert(Ap[0]->get_tab2()(pos) == col);
                            S(pos - deb, oMl + m) -= coeff * dAp[k]->get_coeff()(lb);
                          }
                      }
            /* factorisation et resolution */
// DoubleTrav D_back = D;
            F77NAME(dgetrf)(&nb, &nb, &D(0, 0), &nb, &piv(0), &infoo);
            F77NAME(dgetrs)(&trans, &nb, &nc, &D(0, 0), &nb, &piv(0), &S(0, 0), &nb, &infoo);
            /* stockage : S(0, .) dans b_p, S(1..nc, .) dans A_p */
            for (j = 0; j < nv; j++)
              for (M = size[j], oMg = off_g[j], oMl = off_l[j], m = 0; m < M; m++)
                for (bp[j]->addr()[oMg + M * i + m] = S(ic, oMl + m), k = 0, l = Ap[j]->get_tab1()(oMg + M * i + m) - 1; k < ic; k++, l++)
                  Ap[j]->get_set_coeff()(l) = S(k, oMl + m);
          }
      for (auto &&i_b : bloc) e_ib.insert(i_b), e_i.insert(i_b.first);
    }
}
References A_p, TRUSTArray< _TYPE_ >::addr(), Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), Cerr, coeff, Process::exit(), F77NAME, finl, Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), mats, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), ConstTRUSTTab_parts< _TYPE_ >::size(), and TRUSTArray< _TYPE_ >::size_array().
get_default_growth_factor()
double SETS::get_default_growth_factor () const inline override virtual
Reimplemented from Solveur_Implicite_Base.
Definition at line 77 of file SETS.h.
  {
    return 1.2; /* en cas de pas de temps rate, on remonte doucement */
  }
get_info()
const Type_info * SETS::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_non_lineaire.
Reimplemented in ICE.
Definition at line 48 of file SETS.cpp.
info()
const Type_info * SETS::info () static
Definition at line 48 of file SETS.cpp.
iterer_eqn()
bool SETS::iterer_eqn (Equation_base & equation, const DoubleTab & inconnue, DoubleTab & result, double dt, int numero_iteration, int & ok) override virtual
Implements Simpler_Base.
Definition at line 193 of file SETS.cpp.
{
  int cv;
  /* on ne traite que Pb_Multiphase ou Pb_conduction */
  if (!sub_type(Pb_Multiphase, eqn.probleme()) && !sub_type(Pb_Conduction, eqn.probleme()))
    Process::exit(que_suis_je() + " cannot be applied to the problem " + eqn.probleme().le_nom() + " of type " + eqn.probleme().que_suis_je() + "!");
  /* equations non resolues directement : Masse_Multiphase (toujours), Energie_Multiphase (en ICE), Convection_Diffusion_std i.e. quantites turbulentes (en ICE) */
  if (sub_type(Masse_Multiphase, eqn) || (!sets_ && sub_type(Energie_Multiphase, eqn))|| (!sets_ && sub_type(Convection_Diffusion_std, eqn)))
    return true;
  /* QDM_Multiphase: resolue par iterer_NS */
  if (sub_type(QDM_Multiphase, eqn))
    {
      Matrice_Morse matrix_unused;
      DoubleTrav secmem_unused;
      iterer_NS(eqn, current, ref_cast(QDM_Multiphase, eqn).pression().valeurs(), dt, matrix_unused, 0, secmem_unused, numero_iteration, cv, ok);
      return cv;
    }
  /* cas restant : equation thermique d'un Pb_Multi ou d'un Pb_conduction -> on regle semi_impl si necessaire, puis on resout */
  const std::string& nom_inco = eqn.inconnue().le_nom().getString(), nom_pb_inco = eqn.probleme().le_nom().getString() + "/" + nom_inco;
  tabs_t semi_impl; /* en ICE, les temperatures de tous les problemes sont explicites */
  const Operateur_Diff_base& op_diff = ref_cast(Operateur_Diff_base, eqn.operateur(0).l_op_base());
  if (!sets_)
    for (auto &&op_ext : op_diff.op_ext)
      semi_impl[nom_inco + (op_ext != &op_diff ? "/" + op_ext->equation().probleme().le_nom().getString() : "")] = op_ext->equation().inconnue().passe();
  if (!mat_pred.count(nom_pb_inco)) /* matrice : dimensionnement au premier passage */
    eqn.dimensionner_blocs({{ nom_inco, &mat_pred[nom_pb_inco]}}, semi_impl);
  /* assemblage et resolution */
  DoubleTrav secmem(current);
  SolveurSys& solv = get_and_set_parametre_implicite(eqn).solveur();
  eqn.assembler_blocs_avec_inertie({{ nom_inco, &mat_pred[nom_pb_inco] }}, secmem, semi_impl);
  mat_pred[nom_pb_inco].ajouter_multvect(current, secmem); //passage increment -> variable
  solv.valeur().reinit();
  solv.resoudre_systeme(mat_pred[nom_pb_inco], secmem, current);
  if (eqn.positive_unkown()==1)
    {
      DoubleTrav incr ;
      incr = current;
      incr -= eqn.inconnue()->valeurs();
      unknown_positivation(eqn.inconnue()->valeurs(), incr);
      incr += eqn.inconnue()->valeurs();
      current = incr;
    }
  /* mise a jour */
  eqn.probleme().mettre_a_jour(eqn.schema_temps().temps_courant());
  eqn.inconnue().futur() = current;
  return true;
}
References Equation_base::dimensionner_blocs(), MorEqn::equation(), Process::exit(), Nom::getString(), Equation_base::inconnue(), iterer_NS(), Operateur::l_op_base(), Probleme_base::le_nom(), O_U_Ptr::le_nom(), mat_pred, Operateur_Diff_base::op_ext, Equation_base::operateur(), Equation_base::probleme(), Objet_U::que_suis_je(), ref_cast, sets_, and sub_type.
iterer_NS()
void SETS::iterer_NS (Equation_base & eqn, DoubleTab & current, DoubleTab & pression, double dt, Matrice_Morse & matrice_unused, double seuil_resol, DoubleTrav & secmem_unused, int nb_iter, int & converge, int & ok) override virtual
< On prend la pression minimale comme pression de reference afin d'avoir la meme pression de reference en sequentiel et parallele
Implements Simpler_Base.
Definition at line 252 of file SETS.cpp.
{
  Pb_Multiphase& pb = *(Pb_Multiphase *) &ref_cast(Pb_Multiphase, eqn.probleme());
  int i, j, &it = iteration, n_eq = pb.nombre_d_equations();
  QDM_Multiphase& eq_qdm = ref_cast(QDM_Multiphase, eqn);
  double t = eqn.schema_temps().temps_courant(), err_a_sum = 0;
  std::vector<Equation_base *> eq_list; //ordres des equations
  for (i = 0; i < n_eq; i++) eq_list.push_back(&pb.equation(i));
  std::map<std::string, Equation_base *> eqs; //eqs[inconnue] = equation
  std::vector<std::string> noms; //ordre des inconnues : le meme que les equations, puis la pression
  for (i = 0; i < n_eq; i++) noms.push_back(eq_list[i]->inconnue().le_nom().getString()), eqs[noms[i]] = eq_list[i];
  noms.push_back("pression"); //pas d'equation associee a la pression!
  std::map<std::string, Champ_Inc_base *> inco; //tous les Champ_Inc
  for (auto &i_eq : eqs) inco[i_eq.first] = &i_eq.second->inconnue().valeur();
  inco["pression"] = &eq_qdm.pression().valeur();
// initialisation du Newton avec les valeurs presentes (stockees dans passe() en implicite), dimensionnement de incr / sec
  pb.mettre_a_jour(t); //inconnues -> milieu -> champs conserves
  /* valeurs semi-implicites : inconnues (alpha, v, T, ..) et champs conserves (alpha_rho, alpha_rho_e, ..) */
  tabs_t semi_impl;
  for (auto &&i_eq : eqs)
    if (i_eq.second != &eq_qdm)
      {
        semi_impl[i_eq.first] = i_eq.second->inconnue().passe();
        if (i_eq.second->has_champ_conserve()) semi_impl[i_eq.second->champ_conserve().le_nom().getString()] = i_eq.second->champ_conserve().passe();
        if (i_eq.second->has_champ_convecte()) semi_impl[i_eq.second->champ_convecte().le_nom().getString()] = i_eq.second->champ_convecte().passe();
      }
// en SETS, on remplace la valeur passee de v par celle donnee par une etape de prediction
  if (sets_ && !first_call_)
    {
      DoubleTrav secmem(current);
      /* assemblage "implicite, vitesses seulement" */
      if (!mat_pred.count("vitesse")) eq_qdm.dimensionner_blocs({{"vitesse", &mat_pred["vitesse"] }}); //premier passage : dimensionnement
      eq_qdm.assembler_blocs_avec_inertie({{"vitesse", &mat_pred["vitesse"] }}, secmem);
      /* resolution et stockage de la vitesse pedite dans current */
      SolveurSys& solv_qdm = get_and_set_parametre_implicite(eqn).solveur();
      solv_qdm.valeur().reinit();
      mat_pred["vitesse"].ajouter_multvect(current, secmem); //passage increment -> variable pour faire plaisir aux solveurs iteratifs
      solv_qdm.resoudre_systeme(mat_pred["vitesse"], secmem, current);
      semi_impl["vitesse"] = current;
    }
  else semi_impl["vitesse"] = eq_qdm.inconnue().passe();
  eqn.solv_masse().corriger_solution(current, current, 0); //pour PolyMAC_P0 : vf -> ve
// premier passage : dimensionnement de mat_semi_impl, remplissage de p_degen_
  if (!mat_semi_impl.nb_lignes())
    {
      mat_semi_impl.dimensionner(n_eq + 1, n_eq + 1);//derniere ligne -> continuite
      for (i = 0; i <= n_eq; i++)
        for (j = 0; j <= n_eq; j++)
          mat_semi_impl.get_bloc(i, j).typer("Matrice_Morse"), mats[noms[i]][noms[j]] = &ref_cast(Matrice_Morse, mat_semi_impl.get_bloc(i, j).valeur());
      for (auto &&i_eq : eqs) i_eq.second->dimensionner_blocs(mats[i_eq.first], semi_impl); //option semi-implicite
      eq_qdm.assembleur_pression()->dimensionner_continuite(mats["pression"]);
      /* reglage de p_degen si non lu : si incompressible sans CLs de pression imposee, alors la pression est degeneree */
      if (p_degen < 0)
        for (p_degen = sub_type(Fluide_base, eq_qdm.milieu()), i = 0; i < eq_qdm.zone_Cl_dis().nb_cond_lim(); i++)
          p_degen &= !sub_type(Neumann_val_ext, eq_qdm.zone_Cl_dis().les_conditions_limites(i).valeur());
    }
  /* Newton : assemblage de mat_semi_impl -> assemblage de la matrice en pression -> resolution -> substitution */
  tabs_t incr, sec; //increments / seconds membres associes
  for (auto &&n_i : inco) incr[n_i.first] = sec[n_i.first] = n_i.second->valeurs();
  TablePrinter tp(&get_Cerr().get_ostream());
  if (!Process::me())
    {
      tp.AddColumn("it", 5);
      for (auto &&n_i : inco) tp.AddColumn(n_i.first, std::max(12, (True_int) n_i.first.length()));
      tp.PrintHeader();
    }
  for (it = 0, cv = 0; it < iter_min_ || (!cv && it < iter_max_); it++)
    {
      /* remplissage par assembler_blocs */
// equation d'energie en premier pour pouvoir utiliser q_pi dans d'autres equations
      eqs["temperature"]->assembler_blocs_avec_inertie(mats["temperature"], sec["temperature"], semi_impl);
// les autres
      for (auto &n_e : eqs)
        if (n_e.first != "temperature") n_e.second->assembler_blocs_avec_inertie(mats[n_e.first], sec[n_e.first], semi_impl);
// equation de continuite sum_k alpha_k = 1
      eq_qdm.assembleur_pression()->assembler_continuite(mats["pression"], sec["pression"]);
      /* expression des autres inconnues (x) en fonction de p : vitesse, puis temperature / pression */
      tabs_t b_p;
      std::vector<std::set<std::pair<std::string, int>>> ordre;
      if (eq_qdm.zone_dis().valeur().le_nom() == "PolyMAC_P0") ordre.push_back({{ "vitesse", 1 }}); //si PolyMAC_P0: on commence par ve
      ordre.push_back({{ "vitesse", 0 }}), ordre.push_back({}); //puis vf, puis toutes les autres inconnues simultanment
      for (auto &&nom : noms)
        if (nom != "vitesse" && nom != "pression") ordre.back().insert({{ nom, 0 }});
      eliminer(ordre, "pression", mats, sec, A_p, b_p);
      /* assemblage du systeme en pression */
      DoubleTrav secmem_pression;
      assembler("pression", A_p, b_p, mats, sec, matrice_pression, secmem_pression, p_degen);
      SolveurSys& solv_p = eq_qdm.solveur_pression();
#ifdef PETSCKSP_H
      if (!cv_ctx && sub_type(Solv_Petsc, solv_p.valeur()))
        {
          init_cv_ctx(secmem_pression, eq_qdm.assembleur_pression()->norme_continuite());
          ref_cast(Solv_Petsc, solv_p.valeur()).set_convergence_test(convergence_test, cv_ctx, destroy_cvctx);
        }
#endif
      /* resolution : seulement si l'erreur en alpha (dans secmem_pression) depasse un seuil */
      if (mp_max_abs_vect(secmem_pression) > 1e-16)
        {
          matrice_pression.ajouter_multvect(inco["pression"]->valeurs(), secmem_pression); //passage increment -> variable pour faire plaisir aux solveurs iteratifs
          solv_p.valeur().reinit(), solv_p.valeur().set_return_on_error(1); /* pour eviter un exit() en cas d'echec */
          ok = (solv_p.resoudre_systeme(matrice_pression, secmem_pression, incr["pression"]) >= 0);
          if (!ok) break; //le solveur a echoue -> on sort
          incr["pression"].echange_espace_virtuel();
          incr["pression"] -= inco["pression"]->valeurs();
        }
      else incr["pression"] = 0;
// increments des autres variables
      for (auto &&n_v : b_p)
        {
          incr[n_v.first] = n_v.second; //partie constante
          A_p[n_v.first].ajouter_multvect(incr["pression"], incr[n_v.first]); //dependance en les increments de pression
          incr[n_v.first].echange_espace_virtuel();
        }
      eqn.solv_masse().corriger_solution(incr["vitesse"], incr["vitesse"], 1); //pour PolyMAC_P0 : sert a corriger ve
      if (!Process::me()) tp << it + 1;
      for (auto &&n_v : incr)
        {
          double vm = mp_min_vect(n_v.second), vM = mp_max_vect(n_v.second), x = std::fabs(vM) > std::fabs(vm) ? vM : vm;
          if (!Process::me()) tp << x;
        }
      /* convergence? */
      cv = corriger_incr_alpha(inco["alpha"]->valeurs(), incr["alpha"], err_a_sum) < crit_conv["alpha"];
      for (auto && n_v : incr)
        if (crit_conv.count(n_v.first)) cv &= mp_max_abs_vect(n_v.second) < crit_conv.at(n_v.first);
      /* mises a jour : inconnues -> milieu -> champs/conserves -> sources */
      for (auto && n_i : inco) n_i.second->valeurs() += incr[n_i.first];
      if (p_degen) inco["pression"]->valeurs() -= mp_min_vect(inco["pression"]->valeurs()); //!< On prend la pression minimale comme pression de reference afin d'avoir la meme pression de reference en sequentiel et parallele
      if (!(ok = err_a_sum < crit_conv["alpha"] && eq_qdm.milieu().check_unknown_range())) break; //si on a depasse les bornes du milieu sur (p, T) ou si on manque de precision, on doit sortir
      pb.mettre_a_jour(t); //inconnues -> milieu -> champs conserves
    }
  if (!Process::me()) tp.PrintFooter();
// ha ha ha
  if (ok && cv)
    {
      for (i = 0 ; i < pb.nombre_d_equations(); i++)
        if (pb.equation(i).positive_unkown()==1)
          {
            std::string nom_inco = pb.equation(i).inconnue().le_nom().getString() ;
            unknown_positivation(inco[nom_inco]->valeurs(), incr[nom_inco]) ;
          }
      pb.mettre_a_jour(t); //inconnues -> milieu -> champs conserves
      for (auto && n_i : inco) n_i.second->futur() = n_i.second->valeurs();
      eq_qdm.pression().futur() = eq_qdm.pression().valeurs();
      ConstDoubleTab_parts ppart(inco["pression"]->valeurs());
// en multiphase, la pression est deja en Pa
      /* si pression_pa() est plus petit que pression() (ex. : variables auxiliaires PolyMAC), alors on ne copie que la 1ere partie */
      eq_qdm.pression_pa().valeurs() = eq_qdm.pression_pa().valeurs().dimension_tot(0) < inco["pression"]->valeurs().dimension_tot(0) ? ppart[0] : inco["pression"]->valeurs(); //en multiphase, la pression est deja en Pa
      first_call_ = 0;
    }
  else
    {
      for (auto && n_i : inco)  n_i.second->futur() = n_i.second->valeurs() = n_i.second->passe();
      if (err_a_sum > crit_conv["alpha"])
        Cerr << que_suis_je() + ": pressure solver inaccuracy detected (requested precision " << Nom(crit_conv["alpha"]) << " , achieved precision " << Nom(err_a_sum) + " )" << finl;
      ok = 0;
    }
  return;
}
References bprinter::TablePrinter::AddColumn(), QDM_Multiphase::assembler_blocs_avec_inertie(), Navier_Stokes_std::assembleur_pression(), Solveur_Masse::corriger_solution(), Matrice_Bloc::dimensionner(), QDM_Multiphase::dimensionner_blocs(), Pb_Multiphase::equation(), first_call_, Simpler_Base::get_and_set_parametre_implicite(), Matrice_Bloc::get_bloc(), get_Cerr(), Navier_Stokes_std::inconnue(), iter_max_, iter_min_, iteration, Objet_U::le_nom(), Zone_Cl_dis::les_conditions_limites(), mat_pred, mat_semi_impl, mats, Process::me(), Pb_Multiphase::mettre_a_jour(), Navier_Stokes_std::milieu(), Zone_Cl_dis::nb_cond_lim(), Matrice_Bloc::nb_lignes(), Pb_Multiphase::nombre_d_equations(), p_degen, Champ_Inc::passe(), Navier_Stokes_std::pression(), bprinter::TablePrinter::PrintHeader(), Equation_base::probleme(), ref_cast, SolveurSys_base::reinit(), SolveurSys::resoudre_systeme(), Equation_base::schema_temps(), sets_, Equation_base::solv_masse(), Parametre_implicite::solveur(), sub_type, Schema_Temps_base::temps_courant(), Deriv_::typer(), Deriv_Champ_Inc_base::valeur(), Deriv_Cond_lim_base::valeur(), Deriv_Zone_dis_base::valeur(), Deriv_Matrice_Base::valeur(), Deriv_SolveurSys_base::valeur(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
Referenced by iterer_eqn().
lire()
Entree & SETS::lire (const Motcle & mot, Entree & is) override virtual
Implements Simpler_Base.
Definition at line 76 of file SETS.cpp.
{
  if (mot == Motcle("criteres_convergence"))
    {
      Nom nom;
      is >> nom;
      if (nom != "{") Cerr << "SETS::lire() : { expected instead of " << nom << finl, Process::exit();
      for (is >> nom; nom != "}"; is >> nom)
        {
          double val;
          is >> val;
          crit_conv[nom.getString()] = val;
        }
    }
  else if (mot == "iter_min") is >> iter_min_;
  else if (mot == "iter_max") is >> iter_max_;
  else if (mot == "pression_degeneree") is >> p_degen;
  else return Simpler::lire(mot, is); //la classe mere connait-elle ce mot cle?
  return is;
}
References Cerr, crit_conv, Process::exit(), finl, Nom::getString(), iter_max_, iter_min_, Simple::lire(), and p_degen.
nb_valeurs_temporelles_pression()
int SETS::nb_valeurs_temporelles_pression () const inline override virtual
Reimplemented from Solveur_Implicite_Base.
Definition at line 41 of file SETS.h.
  {
    return 3; /* autant que les autres variables */
  }
printOn()
Sortie & SETS::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Solveur_non_lineaire.
Reimplemented in ICE.
Definition at line 62 of file SETS.cpp.
{
  return Simpler::printOn(os);
}
References Simpler::printOn().
Referenced by ICE::printOn().
readOn()
Entree & SETS::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Solveur_non_lineaire.
Reimplemented in ICE.
Definition at line 67 of file SETS.cpp.
{
  /* valeurs par defaut des criteres de convergence */
  crit_conv = { { "alpha", 1e-2 }, { "temperature", 1e-1 }, { "vitesse", 1e-2 }, { "pression", 100 }, {"k", 1e-2}, {"tau", 1e-2}, {"omega", 1e-2}, {"k_WIT", 1e-2}, {"interfacial_area", 1e-2} };
  first_call_ = 1;
  Simpler::readOn(is);
  return is;
}
References crit_conv, first_call_, and Simpler::readOn().
Referenced by ICE::readOn().
self_cast() [1/2]
const SETS & SETS::self_cast (const Objet_U & r) static
Definition at line 48 of file SETS.cpp.
self_cast() [2/2]
SETS & SETS::self_cast (Objet_U & r) static
Definition at line 48 of file SETS.cpp.
taille_memoire()
unsigned SETS::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in ICE.
Definition at line 48 of file SETS.cpp.
unknown_positivation()
double SETS::unknown_positivation (const DoubleTab & uk, DoubleTab & incr)
brings to 0 unknowns that should stay positive
Definition at line 128 of file SETS.cpp.
{
  double corr_max = 0;
  int N = uk.line_size();
  for (int i=0 ; i<uk.dimension_tot(0) ; i++)
    for (int n = 0 ; n<N ; n++)
      if (uk(i, n) + incr(i, n) < 0)
        {
          if (- uk(i, n) - incr(i, n) > corr_max) corr_max =  std::abs(uk(i, n) + incr(i, n));
          incr(i, n) = -uk(i, n);
        }
  return Process::mp_max(corr_max);
}
References TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::line_size(), and Process::mp_max().
Member Data Documentation
A_p
std::map<std::string, Matrice_Morse> SETS::A_p protected
Definition at line 117 of file SETS.h.
Referenced by assembler(), and eliminer().
crit_conv
std::map<std::string, double> SETS::crit_conv protected
Definition at line 109 of file SETS.h.
Referenced by lire(), and readOn().
first_call_
int SETS::first_call_ protected
Definition at line 106 of file SETS.h.
Referenced by iterer_NS(), and readOn().
info_obj
const Type_info SETS::info_obj static
Definition at line 35 of file SETS.h.
iter_max_
int SETS::iter_max_ = 10 protected
Definition at line 105 of file SETS.h.
Referenced by iterer_NS(), and lire().
iter_min_
int SETS::iter_min_ = 1 protected
Definition at line 105 of file SETS.h.
Referenced by iterer_NS(), and lire().
iteration
int SETS::iteration
Definition at line 82 of file SETS.h.
Referenced by Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), and iterer_NS().
mat_pred
std::map<std::string, Matrice_Morse> SETS::mat_pred protected
Definition at line 114 of file SETS.h.
Referenced by iterer_eqn(), and iterer_NS().
mat_semi_impl
Matrice_Bloc SETS::mat_semi_impl protected
Definition at line 113 of file SETS.h.
Referenced by iterer_NS().
matrice_pression
Matrice_Morse SETS::matrice_pression protected
Definition at line 120 of file SETS.h.
mats
std::map<std::string, matrices_t> SETS::mats protected
matrices : mats[nom de l'inconnue de l'equation][nom de l'autre inconnue] = matrice
Definition at line 112 of file SETS.h.
Referenced by assembler(), eliminer(), and iterer_NS().
p_degen
int SETS::p_degen = -1
Definition at line 83 of file SETS.h.
Referenced by Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), assembler(), iterer_NS(), and lire().
sets_
int SETS::sets_
1 si on fait l'etape de prediction des vitesses
Definition at line 84 of file SETS.h.
Referenced by ICE::ICE(), iterer_eqn(), iterer_NS(), and SETS().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Schemas_Temps/SETS.h
src/ThHyd/Multiphase/Schemas_Temps/SETS.cpp