TRUST: Terme_Source_Canal_RANS_LES_VDF_Elem Class Reference
Terme_Source_Canal_RANS_LES_VDF_Elem Class Reference
#include <Terme_Source_Canal_RANS_LES_VDF_Elem.h>
Public Member Functions
Terme_Source_Canal_RANS_LES_VDF_Elem ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
~Terme_Source_Canal_RANS_LES_VDF_Elem () override
void associer_pb (const Probleme_base &) override
DoubleTab & calculer (DoubleTab &) const override
void init ()
void mettre_a_jour (double) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) const override
int has_interface_blocs () const override
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Terme_Source_Canal_RANS_LES_VDF_Elem & self_cast (Objet_U &)
static const Terme_Source_Canal_RANS_LES_VDF_Elem & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VDF la_zone_VDF
Ref_Zone_Cl_VDF la_zone_Cl_VDF
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Private Attributes
int moyenne
int cpt
int compteur_reprise
double alpha_tau
double Ly
double f_start
double t_av
DoubleTab tau
DoubleTab U_RANS
Nom nom_pb_rans
DoubleVect utemp_gliss
DoubleVect utemp
DoubleVect utemp_sum
DoubleVect umoy
Detailed Description
Definition at line 35 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Constructor & Destructor Documentation
Terme_Source_Canal_RANS_LES_VDF_Elem()
Terme_Source_Canal_RANS_LES_VDF_Elem::Terme_Source_Canal_RANS_LES_VDF_Elem ()
Definition at line 26 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
~Terme_Source_Canal_RANS_LES_VDF_Elem()
Terme_Source_Canal_RANS_LES_VDF_Elem::~Terme_Source_Canal_RANS_LES_VDF_Elem () override
Definition at line 30 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
{
// Le destructeur est appele a l'initialisation alors
// la sauvegarde du champ se fait hors initialisation
  if(umoy.size()!=0)
    {
      SFichier vit_sauv ("Ttemp_sum.dat");
      vit_sauv << utemp_sum;
      SFichier vit_sauv2 ("Tmoy.dat");
      vit_sauv2 << umoy;
    }
}
References TRUSTVect< _TYPE_ >::size(), umoy, and utemp_sum.
Member Function Documentation
ajouter_blocs()
void Terme_Source_Canal_RANS_LES_VDF_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_base.
Definition at line 343 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  int nb_elems = zone_VDF.nb_elem();
  const DoubleVect& volume = zone_VDF.volumes();
  const double tps = mon_equation->schema_temps().temps_courant();
  const double dt = mon_equation->schema_temps().pas_de_temps();
  const double dt_min = mon_equation->schema_temps().pas_temps_min();
  //vitesse=temperature
  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
  double vol=0.;
  SFichier fic_f("f_temp.dat", ios::app);
  SFichier fic_finst("f_temp_inst.dat", ios::app);
  double mbf = 0.; //maximum body force
  double mbf2 = 0.; //maximum body force
  static int cpt2=0;
  // Calcul de la norme des vitesses au centre des elements
  if(((tps>f_start)&&(compteur_reprise > 1))||((moyenne==3)&&(tps>dt_min)))
    {
      for(int num_elem = 0 ; num_elem<nb_elems ; num_elem++)
        {
          vol = volume(num_elem);
          secmem(num_elem) += ((U_RANS(num_elem)-umoy(num_elem))/(tau(num_elem)*dt))*vol;
          mbf2 +=((U_RANS(num_elem)-umoy(num_elem))/(tau(num_elem)*dt))*vol;
          cpt2++;
        }
      mbf2 = mbf2/cpt2;
      int num_elem=12;
      mbf = (U_RANS(num_elem)-umoy(num_elem))
            /(tau(num_elem)*dt)*vol;
      fic_finst << tps << " " << mbf << " " <<  U_RANS(num_elem)
                << " " << umoy(num_elem) << "  " << vitesse(num_elem) << finl;
      fic_f << tps << " " << mbf2 << " "
            << U_RANS(num_elem) << " " << umoy(num_elem) << " "
            << utemp_sum(num_elem) << " " << dt <<finl;
    }//fin if f_start
}
References compteur_reprise, f_start, finl, Equation_base::inconnue(), la_zone_VDF, MorEqn::mon_equation, moyenne, Zone_dis_base::nb_elem(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Equation_base::schema_temps(), tau, Schema_Temps_base::temps_courant(), U_RANS, umoy, utemp_sum, Ref_Zone_VDF::valeur(), Champ_Inc::valeurs(), and Zone_VF::volumes().
associer_pb()
void Terme_Source_Canal_RANS_LES_VDF_Elem::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Definition at line 154 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
{
  ;
}
associer_zones()
void Terme_Source_Canal_RANS_LES_VDF_Elem::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
Implements Source_base.
Definition at line 147 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
{
  la_zone_VDF = ref_cast(Zone_VDF, zone_dis.valeur());
  la_zone_Cl_VDF = ref_cast(Zone_Cl_VDF, zone_Cl_dis.valeur());
}
References la_zone_Cl_VDF, la_zone_VDF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
calculer()
DoubleTab & Terme_Source_Canal_RANS_LES_VDF_Elem::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 396 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
{
  resu = 0;
  return ajouter(resu);
}
References Source_base::ajouter().
cree_instance()
Objet_U * Terme_Source_Canal_RANS_LES_VDF_Elem::cree_instance () static
Definition at line 26 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
dimensionner_blocs()
void Terme_Source_Canal_RANS_LES_VDF_Elem::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
Definition at line 46 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
{}
duplique()
int Terme_Source_Canal_RANS_LES_VDF_Elem::duplique () const override virtual
Implements Objet_U.
Definition at line 26 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
get_info()
const Type_info * Terme_Source_Canal_RANS_LES_VDF_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 26 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
has_interface_blocs()
int Terme_Source_Canal_RANS_LES_VDF_Elem::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Definition at line 48 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
  {
    return 1;
  };
info()
const Type_info * Terme_Source_Canal_RANS_LES_VDF_Elem::info () static
Definition at line 26 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
init()
void Terme_Source_Canal_RANS_LES_VDF_Elem::init ()
Definition at line 159 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF=ref_cast(Zone_VDF, zdisbase);
  const double tps = mon_equation->schema_temps().temps_courant();
  int nb_elems = zone_VDF.nb_elem();
  tau.resize(nb_elems);
  U_RANS.resize(nb_elems);
  if(nom_pb_rans == "non_couple")
    {
      SFichier fic_verif("Tverif.RANS");
      EFichier fic_vit("temperature_RANS.dat");
      for(int num_elem=0 ; num_elem<nb_elems ; num_elem++)
        {
          int elem;
          fic_vit >> elem ;
          fic_vit >> U_RANS(elem) ;
          fic_verif << elem << " " << U_RANS(elem) << finl;
        }
    }
  for(int num_elem=0 ; num_elem<nb_elems ; num_elem++)
    {
      tau(num_elem) = alpha_tau;
    }
  utemp_gliss.resize(nb_elems);
  utemp.resize(nb_elems);
  utemp_sum.resize(nb_elems);
  utemp_gliss = 0.;
  utemp = 0.;
  utemp_sum = 0.;
  umoy.resize(nb_elems);
  if (tps > f_start)
    {
      EFichier vit_umoy ("Ttemp_sum.dat");
      EFichier vit_umoy2 ("Tmoy.dat");
      SFichier vit_reprise ("TLES.reprise");
      SFichier vit_reprise2 ("TLES2.reprise");
      int trash;
      vit_umoy >> trash;
      Cerr << "trash = " << trash << finl;
      vit_umoy2 >> trash;
      Cerr << "trash = " << trash << finl;
      for(int num_elem = 0 ; num_elem<nb_elems ; num_elem++)
        {
          vit_umoy >> utemp_sum(num_elem);
          vit_umoy2 >> umoy(num_elem);
          vit_reprise << num_elem << " " << utemp_sum(num_elem) << finl;
          vit_reprise2 << num_elem << " " << umoy(num_elem) << finl;
        }
    }
  cpt = 0;
  compteur_reprise = 0;
}//fin init
References alpha_tau, Cerr, compteur_reprise, cpt, f_start, finl, Equation_base::inconnue(), MorEqn::mon_equation, Zone_dis_base::nb_elem(), nom_pb_rans, ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), Equation_base::schema_temps(), tau, Schema_Temps_base::temps_courant(), U_RANS, umoy, utemp, utemp_gliss, utemp_sum, and Champ_Inc::zone_dis_base().
Referenced by readOn().
mettre_a_jour()
void Terme_Source_Canal_RANS_LES_VDF_Elem::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 228 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
{
// Cerr << "Je suis dans le mettre_a_jour" << finl;
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
// vitesse=temperature
  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
  const double dt = mon_equation->schema_temps().pas_de_temps();
  const double tps = mon_equation->schema_temps().temps_courant();
  int nb_elems = zone_VDF.nb_elem();
  const double dt_min = mon_equation->schema_temps().pas_temps_min();
  int cptbis=0;
  //****************************************************
  //******* MaJ de la vitesse cible (RANS) ***********
  //**************************************************
  if(nom_pb_rans != "non_couple")
    {
      REF(Probleme_base) pb_rans;
      Objet_U& obj=Interprete::objet(nom_pb_rans);
      if( sub_type(Probleme_base, obj) )
        {
          pb_rans = ref_cast(Probleme_base, obj);
        }
      U_RANS = pb_rans.valeur().equation(1).inconnue().valeurs();
    }
  //***************************************************
  if(moyenne==2)
    {
      //******************************************************
      //*************** MOYENNE TEMPORELLE *******************
      //******************************************************
      //Calcul d'une premiere moyenne temporelle significative
      if((tps>(f_start-t_av))&&(tps<f_start))
        {
          if (cptbis==0)
            {
              for (int num_elem=0; num_elem<nb_elems; num_elem++)
                {
                  utemp_sum(num_elem) = vitesse(num_elem)*(tps-(f_start-t_av));
                  umoy(num_elem) = vitesse(num_elem);
                }
              cptbis = 3;
            }
          else
            {
              for (int num_elem=0; num_elem<nb_elems; num_elem++)
                {
                  utemp_sum(num_elem) += vitesse(num_elem)*dt;
                  umoy(num_elem) = utemp_gliss(num_elem)/(tps-(f_start-t_av));
                }
            }
        }
      if(tps>=f_start)
        {
          for (int num_elem=0; num_elem<nb_elems; num_elem++)
            {
              utemp_sum(num_elem) += dt*vitesse(num_elem);
              umoy(num_elem)=utemp_sum(num_elem)/(tps-(f_start-t_av));
            }
          cptbis=4;
        }
      //***********************************************************
      //*************** FIN MOYENNE TEMPORELLE  ***************
      //*******************************************************
    }
  else if(moyenne==3)
    {
      if (tps>0)
        {
          if (cptbis==0)
            {
              for (int num_elem=0; num_elem<nb_elems; num_elem++)
                {
                  utemp_sum(num_elem) = vitesse(num_elem)*dt;
                  umoy(num_elem) = vitesse(num_elem);
                }
              cptbis ++;
            }
          else
            {
              for (int num_elem=0; num_elem<nb_elems; num_elem++)
                {
                  utemp_sum(num_elem) += vitesse(num_elem)*dt;
                  umoy(num_elem) = utemp_sum(num_elem)/(tps-dt_min+dt);
                }
            }
        }
    }
  else
    {
      Cerr << "moyenne = " << moyenne << finl;
      Cerr << "Probleme pour le choix du type de moyenne" << finl;
    }
  compteur_reprise++;
}//fin mettre_a_jour
References Cerr, compteur_reprise, f_start, finl, Equation_base::inconnue(), la_zone_VDF, MorEqn::mon_equation, moyenne, Zone_dis_base::nb_elem(), nom_pb_rans, Interprete::objet(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), REF, ref_cast, Equation_base::schema_temps(), sub_type, t_av, Schema_Temps_base::temps_courant(), U_RANS, umoy, utemp_gliss, utemp_sum, Ref_Zone_VDF::valeur(), and Champ_Inc::valeurs().
printOn()
Sortie & Terme_Source_Canal_RANS_LES_VDF_Elem::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 47 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_Canal_RANS_LES_VDF_Elem::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 56 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
{
  int compteur = 0;
  Motcle mot_lu;
  Motcle acc_ouverte("{");
  Motcle acc_fermee("}");
  nom_pb_rans="non_couple";
  t_av=-1;
  f_start = 0.;
  moyenne = 0;//valeur par defaut
// 0 => moyenne spatiale
// 1 => moyenne temporelle glissante (moyenne en alpha)
// 2 => moyenne temporelle
  Motcles les_mots(6);
  {
    les_mots[0]="alpha_tau"; //coeff de relaxation du terme source
    les_mots[1]="Ly"; //Hauteur du canal plan (utile pour la moyenne spatiale)
    les_mots[2]="f_start"; //temps a partir duquel le terme source est active
    les_mots[3]="t_av"; //temps de prise de moyenne (moyenne temporelle glissante)
    les_mots[4]="type_moyenne"; //
    les_mots[5]="nom_pb_rans"; //
  }
  is >> mot_lu;
  if(mot_lu != acc_ouverte)
    {
      Cerr << "On attendait { a la place de " << mot_lu
           << " lors de la lecture des parametres de la loi de paroi " << finl;
    }
  is >> mot_lu;
  while(mot_lu != acc_fermee)
    {
      int rang=les_mots.search(mot_lu);
      switch(rang)
        {
        case 0 :
          is >> alpha_tau;
          Cerr << "alpha_tau = " << alpha_tau << finl;
          compteur++;
          break;
        case 1  :
          is >> Ly;
          Cerr << "Ly = "<< Ly << finl;
          compteur++;
          break;
        case 2  :
          is >> f_start;
          Cerr << "f_start = "<< f_start << finl;
          compteur++;
          break;
        case 3  :
          is >> t_av;
          Cerr << "t_av = " << t_av << finl;
          Cerr << "type_moyenne : " << moyenne << finl;
          if((moyenne==1)&&(t_av<=0))
            {
              Cerr << "La periode en temps de la moyenne temporelle glissante est non precisee !"
                   << finl;
              exit();
            }
          compteur++;
          break;
        case 4  :
          is >> moyenne;
          Cerr << "type_moyenne : " << moyenne << finl;
          compteur++;
          break;
        case 5  :
          is >> nom_pb_rans;
          compteur++;
          break;
        default :
          {
            Cerr << mot_lu << " n'est pas un mot compris" << finl;
            Cerr << "Les mots compris sont : " << les_mots << finl;
            exit();
          }
        }
      is >> mot_lu;
    }
  Cerr << "nom_pb_rans = " << nom_pb_rans << finl;
  Cerr << compteur << " motcles ont ete lus dans le readOn du terme de forcage thermique" << finl;
  init();
  return is;
}
References alpha_tau, Cerr, compteur, Process::exit(), f_start, finl, init(), Ly, moyenne, nom_pb_rans, Motcles::search(), and t_av.
self_cast() [1/2]
const Terme_Source_Canal_RANS_LES_VDF_Elem & Terme_Source_Canal_RANS_LES_VDF_Elem::self_cast (const Objet_U & r) static
Definition at line 26 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
self_cast() [2/2]
Terme_Source_Canal_RANS_LES_VDF_Elem & Terme_Source_Canal_RANS_LES_VDF_Elem::self_cast (Objet_U & r) static
Definition at line 26 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
taille_memoire()
unsigned Terme_Source_Canal_RANS_LES_VDF_Elem::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 26 of file Terme_Source_Canal_RANS_LES_VDF_Elem.cpp.
Member Data Documentation
alpha_tau
double Terme_Source_Canal_RANS_LES_VDF_Elem::alpha_tau private
Definition at line 61 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by init(), and readOn().
compteur_reprise
int Terme_Source_Canal_RANS_LES_VDF_Elem::compteur_reprise private
Definition at line 60 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by ajouter_blocs(), init(), and mettre_a_jour().
cpt
int Terme_Source_Canal_RANS_LES_VDF_Elem::cpt private
Definition at line 60 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by init().
f_start
double Terme_Source_Canal_RANS_LES_VDF_Elem::f_start private
Definition at line 62 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by ajouter_blocs(), init(), mettre_a_jour(), and readOn().
info_obj
const Type_info Terme_Source_Canal_RANS_LES_VDF_Elem::info_obj static
Definition at line 37 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
la_zone_Cl_VDF
Ref_Zone_Cl_VDF Terme_Source_Canal_RANS_LES_VDF_Elem::la_zone_Cl_VDF protected
Definition at line 56 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by associer_zones().
la_zone_VDF
Ref_Zone_VDF Terme_Source_Canal_RANS_LES_VDF_Elem::la_zone_VDF protected
Definition at line 55 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by ajouter_blocs(), associer_zones(), and mettre_a_jour().
Ly
double Terme_Source_Canal_RANS_LES_VDF_Elem::Ly private
Definition at line 61 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by readOn().
moyenne
int Terme_Source_Canal_RANS_LES_VDF_Elem::moyenne private
Definition at line 59 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by ajouter_blocs(), mettre_a_jour(), and readOn().
nom_pb_rans
Nom Terme_Source_Canal_RANS_LES_VDF_Elem::nom_pb_rans private
Definition at line 66 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by init(), mettre_a_jour(), and readOn().
t_av
double Terme_Source_Canal_RANS_LES_VDF_Elem::t_av private
Definition at line 62 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by mettre_a_jour(), and readOn().
tau
DoubleTab Terme_Source_Canal_RANS_LES_VDF_Elem::tau private
Definition at line 64 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by ajouter_blocs(), and init().
U_RANS
DoubleTab Terme_Source_Canal_RANS_LES_VDF_Elem::U_RANS private
Definition at line 65 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by ajouter_blocs(), init(), and mettre_a_jour().
umoy
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Elem::umoy private
Definition at line 68 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by ajouter_blocs(), init(), mettre_a_jour(), and ~Terme_Source_Canal_RANS_LES_VDF_Elem().
utemp
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Elem::utemp private
Definition at line 68 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by init().
utemp_gliss
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Elem::utemp_gliss private
Definition at line 68 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by init(), and mettre_a_jour().
utemp_sum
DoubleVect Terme_Source_Canal_RANS_LES_VDF_Elem::utemp_sum private
Definition at line 68 of file Terme_Source_Canal_RANS_LES_VDF_Elem.h.
Referenced by ajouter_blocs(), init(), mettre_a_jour(), and ~Terme_Source_Canal_RANS_LES_VDF_Elem().
The documentation for this class was generated from the following files:
src/VDF/Sources/Terme_Source_Canal_RANS_LES_VDF_Elem.h
src/VDF/Sources/Terme_Source_Canal_RANS_LES_VDF_Elem.cpp