TRUST: Rectangle Class Reference
Rectangle Class Reference
Classe Rectangle
Cette classe represente l'element geometrique Rectangle.
Un rectangle a 4 faces, 4 sommets et 1 seul type de face ayant 2
sommets par face.
#include <Rectangle.h>
Public Member Functions
Rectangle ()
~Rectangle ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int face_sommet (int i, int j) const
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
int face_sommet0 (int i) const
Renvoie le numero du i-ieme sommet de la face 0.
int face_sommet1 (int i) const
Renvoie le numero du i-ieme sommet de la face 1.
int face_sommet2 (int i) const
Renvoie le numero du i-ieme sommet de la face 2.
int face_sommet3 (int i) const
Renvoie le numero du i-ieme sommet de la face 3.
int nb_som () const
Renvoie le nombre de sommets d'un triangle: 3.
int nb_faces (int=0) const
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
int nb_som_face (int=0) const
Renvoie le nombre de sommets des faces
du type specifie.
int est_structure () const
Renvoie toujours 1, car l'element geometrique
Rectangle est de type structure.
const Nom & nom_lml () const
Renvoie le nom LML d'un rectangle = "VOXEL8".
virtual int contient (const ArrOfDouble &, int) const
Renvoie 1 si l'element ielem de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
virtual int contient (const ArrOfInt &, int) const
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Type_Face type_face (int=0) const
Renvoie le i-ieme type de face.
Un rectangle n'a qu'un seul type de face.
virtual void reordonner ()
Reordonne les sommets du rectangle.
int reordonner_elem ()
Reordonne et verifie que l'on a bien des rectangles.
virtual void calculer_volumes (DoubleVect &) const
Calcule les volumes des elements de la zone associee.
void calculer_normales (const IntTab &faces_sommets, DoubleTab &face_normales) const
Calcule les normales aux faces des elements de la zone associee.
int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const
voir ElemGeomBase::get_tab_faces_sommets_locaux
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Rectangle & self_cast (Objet_U &)
static const Rectangle & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN.
virtual Entree & readOn (Entree &)
NE FAIT RIEN.
Detailed Description
Classe Rectangle
Cette classe represente l'element geometrique Rectangle.
Un rectangle a 4 faces, 4 sommets et 1 seul type de face ayant 2
sommets par face.
Definition at line 39 of file Rectangle.h.
Constructor & Destructor Documentation
Rectangle::Rectangle ()
Definition at line 34 of file Rectangle.cpp.
Rectangle::~Rectangle ()
Definition at line 34 of file Rectangle.cpp.
Member Function Documentation
void Rectangle::calculer_normales (const IntTab & faces_sommets, DoubleTab & face_normales) const [virtual]
Calcule les normales aux faces des elements de la zone associee.
Reimplemented from Elem_geom_base.
Definition at line 333 of file Rectangle.cpp.
References Domaine::coord_sommets(), IntTab::dimension(), Zone::domaine(), Elem_geom_base::ma_zone, and Ref_Zone::valeur().
{
  const Zone& zone_geom = ma_zone.valeur();
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
  int nbfaces = Face_sommets.dimension(0);
  double x1,y1;
  int n0,n1;
  for (int numface=0; numface<nbfaces; numface++)
    {
      n0 = Face_sommets(numface,0);
      n1 = Face_sommets(numface,1);
      x1 = les_coords(n0,0) - les_coords(n1,0);
      y1 = les_coords(n0,1) - les_coords(n1,1);
      face_normales(numface,0) = -y1;
      face_normales(numface,1) = x1;
    }
}
void Rectangle::calculer_volumes (DoubleVect & volumes) const [virtual]
Calcule les volumes des elements de la zone associee.
Implements Elem_geom_base.
Reimplemented in Rectangle_2D_axi, and Rectangle_axi.
Definition at line 289 of file Rectangle.cpp.
References Cerr, Domaine::coord(), Objet_U::dimension, Zone::domaine(), Process::exit(), finl, Elem_geom_base::ma_zone, Zone::nb_elem_tot(), DoubleVect::size_totale(), Zone::sommet_elem(), and Ref_Zone::valeur().
{
  if (dimension==3)
    {
      Cerr << "Rectangle::calculer_volumes is not supported for 3D yet." << finl;
      exit();
    }
  const Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  double dx,dy;
  int S1,S2,S3;
  int size_tot = zone.nb_elem_tot();
  assert(volumes.size_totale()==size_tot);
  for (int num_poly=0; num_poly<size_tot; num_poly++)
    {
      S1 = zone.sommet_elem(num_poly,0);
      S2 = zone.sommet_elem(num_poly,1);
      S3 = zone.sommet_elem(num_poly,2);
      dx = dom.coord(S2,0) - dom.coord(S1,0);
      dy = dom.coord(S3,1) - dom.coord(S1,1);
      volumes[num_poly]= dx*dy;
    }
}
int Rectangle::contient (const ArrOfInt & som, int element) const [virtual]
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Returns:
int
Signification: 1 si les sommets passes en parametre
sont ceux de l'element specifie, 0 sinon
Contraintes:
Implements Elem_geom_base.
Reimplemented in Rectangle_axi.
Definition at line 261 of file Rectangle.cpp.
References Elem_geom_base::ma_zone, Zone::sommet_elem(), and Ref_Zone::valeur().
{
  const Zone& zone=ma_zone.valeur();
  if((zone.sommet_elem(element,0)==som[0])&&
      (zone.sommet_elem(element,1)==som[1])&&
      (zone.sommet_elem(element,2)==som[2])&&
      (zone.sommet_elem(element,3)==som[3]))
    return 1;
  else
    return 0;
}
int Rectangle::contient (const ArrOfDouble & pos, int element) const [virtual]
Renvoie 1 si l'element ielem de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
Returns:
int
Signification: 1 si le point de coordonnees specifiees
appartient a l'element ielem
0 sinon
Contraintes:
Implements Elem_geom_base.
Reimplemented in Rectangle_axi.
Definition at line 223 of file Rectangle.cpp.
References Domaine::coord(), inf_ou_egal(), Elem_geom_base::ma_zone, ArrOfDouble::size_array(), and Ref_Zone::valeur().
{
  assert(pos.size_array()==2);
  const Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  int som0 = zone.sommet_elem(element,0);
  int som3 = zone.sommet_elem(element,3);
  if (    inf_ou_egal(dom.coord(som0,0),pos[0]) && inf_ou_egal(pos[0],dom.coord(som3,0))
          && inf_ou_egal(dom.coord(som0,1),pos[1]) && inf_ou_egal(pos[1],dom.coord(som3,1)) )
    return 1;
  else
    return 0;
}
Objet_U * Rectangle::cree_instance () [static]
Reimplemented in Rectangle_2D_axi, and Rectangle_axi.
Definition at line 34 of file Rectangle.cpp.
int Rectangle::duplique () const [virtual]
Implements Elem_geom_base.
Reimplemented in Rectangle_2D_axi, and Rectangle_axi.
Definition at line 34 of file Rectangle.cpp.
int Rectangle::est_structure () const [inline, virtual]
Renvoie toujours 1, car l'element geometrique
Rectangle est de type structure.
Returns:
int
Signification: 1 si l'element est de type structure
0 sinon
Contraintes: toujours egal a 1
Implements Elem_geom_base.
Definition at line 315 of file Rectangle.h.
{
  return 1;
}
int Rectangle::face_sommet (int i, int j) const [inline, virtual]
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
Returns:
int
Signification: le numero du j-ieme sommet de la i-ieme face
Contraintes:
Implements Elem_geom_base.
Definition at line 90 of file Rectangle.h.
References face_sommet0(), face_sommet1(), face_sommet2(), and face_sommet3().
{
  assert(i<4);
  switch(i)
    {
    case 0:
      return face_sommet0(j);
    case 1:
      return face_sommet1(j);
    case 2:
      return face_sommet2(j);
    case 3:
      return face_sommet3(j);
    default :
      return -1;
    }
}
int Rectangle::face_sommet0 (int i) const [inline]
Renvoie le numero du i-ieme sommet de la face 0.
Returns:
int
Signification: le numero du i-ieme sommet de la face 0
Contraintes:
Definition at line 123 of file Rectangle.h.
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
{
// face_sommet0(0)=0;
// face_sommet0(1)=2;
  assert(i>=0);
  assert(i<2);
  if(i>=2)
    {
      Cerr << "A rectangle has not " << i << " nodes per face" << finl;
      exit();
    }
  return 2*i;
}
int Rectangle::face_sommet1 (int i) const [inline]
Renvoie le numero du i-ieme sommet de la face 1.
Returns:
int
Signification: le numero du i-ieme sommet de la face 1
Contraintes:
Definition at line 152 of file Rectangle.h.
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
{
// face_sommet1(0)=0;
// face_sommet1(1)=1;
  assert(i>=0);
  assert(i<2);
  if(i>=2)
    {
      Cerr << "A rectangle has not " << i << " nodes per face" << finl;
      exit();
    }
  return i;
}
int Rectangle::face_sommet2 (int i) const [inline]
Renvoie le numero du i-ieme sommet de la face 2.
Returns:
int
Signification: le numero du i-ieme sommet de la face 2
Contraintes:
Definition at line 181 of file Rectangle.h.
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
{
// face_sommet2(0)=1;
// face_sommet2(1)=3;
  assert(i>=0);
  assert(i<2);
  if(i>=2)
    {
      Cerr << "A rectangle has not " << i << " nodes per face" << finl;
      exit();
    }
  return 2*i+1;
}
int Rectangle::face_sommet3 (int i) const [inline]
Renvoie le numero du i-ieme sommet de la face 3.
Returns:
int
Signification: le numero du i-ieme sommet de la face 3
Contraintes:
Definition at line 210 of file Rectangle.h.
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
{
// face_sommet3(0)=2;
// face_sommet3(1)=3;
  assert(i>=0);
  assert(i<2);
  if(i>=2)
    {
      Cerr << "A rectangle has not " << i << " nodes per face" << finl;
      exit();
    }
  return i+2;
}
const Type_info * Rectangle::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_geom_base.
Reimplemented in Rectangle_2D_axi, and Rectangle_axi.
Definition at line 34 of file Rectangle.cpp.
int Rectangle::get_tab_faces_sommets_locaux (IntTab & faces_som_local) const [virtual]
voir ElemGeomBase::get_tab_faces_sommets_locaux
Reimplemented from Elem_geom_base.
Definition at line 353 of file Rectangle.cpp.
References faces_sommets_rectangle, and IntTab::resize().
{
  faces_som_local.resize(4,2);
  for (int i=0; i<4; i++)
    for (int j=0; j<2; j++)
      faces_som_local(i,j) = faces_sommets_rectangle[i][j];
  return 1;
}
const Type_info * Rectangle::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_geom_base.
Reimplemented in Rectangle_2D_axi, and Rectangle_axi.
Definition at line 34 of file Rectangle.cpp.
int Rectangle::nb_faces (int i = 0) const [inline, virtual]
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
Returns:
int
Signification: le nombre de faces de type i
Contraintes: toujours egal a 4 (si i=0)
Implements Elem_geom_base.
Definition at line 260 of file Rectangle.h.
References Cerr, Process::exit(), and finl.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A rectangle has not " << i << " types of face" << finl;
      exit();
    }
  return 4;
}
int Rectangle::nb_som () const [inline, virtual]
Renvoie le nombre de sommets d'un triangle: 3.
Returns:
int
Signification: le nombre de sommets d'un triangle
Contraintes: toujours egal a 3
Implements Elem_geom_base.
Definition at line 239 of file Rectangle.h.
Referenced by Rectangle_axi::calculer_centres_gravite().
{
  return 4;
}
int Rectangle::nb_som_face (int i = 0) const [inline, virtual]
Renvoie le nombre de sommets des faces
du type specifie.
Returns:
int
Signification: le nombre de sommets des faces de type i
Contraintes: toujours egal a 2 (si i=0)
Implements Elem_geom_base.
Definition at line 287 of file Rectangle.h.
References Cerr, Process::exit(), and finl.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A rectangle has not " << i << " types of face" << finl;
      exit();
    }
  return 2;
}
const Nom & Rectangle::nom_lml () const [virtual]
Renvoie le nom LML d'un rectangle = "VOXEL8".
Returns:
Nom&
Signification: toujours egal a "VOXEL8"
Contraintes: reference constante
Implements Elem_geom_base.
Reimplemented in Rectangle_2D_axi, and Rectangle_axi.
Definition at line 189 of file Rectangle.cpp.
References Objet_U::dimension.
{
  static Nom nom="VOXEL8";
  if (dimension==3) nom="QUADRANGLE_3D";
  return nom;
}
Sortie & Rectangle::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Elem_geom_base.
Reimplemented in Rectangle_2D_axi, and Rectangle_axi.
Definition at line 53 of file Rectangle.cpp.
{
  return s;
}
Entree & Rectangle::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Elem_geom_base.
Reimplemented in Rectangle_2D_axi, and Rectangle_axi.
Definition at line 73 of file Rectangle.cpp.
{
  return s;
}
void Rectangle::reordonner () [virtual]
Reordonne les sommets du rectangle.
Reimplemented from Elem_geom_base.
Reimplemented in Rectangle_2D_axi, and Rectangle_axi.
Definition at line 94 of file Rectangle.cpp.
References Cerr, Process::exit(), finl, and reordonner_elem().
{
  if (reordonner_elem()==-1)
    {
      Cerr << "It is expected to treat rectangles but" << finl;
      Cerr << "one of the elements is not rectangle!" << finl;
      Cerr << "Check your mesh." << finl;
      exit();
    }
}
int Rectangle::reordonner_elem ()
Reordonne et verifie que l'on a bien des rectangles.
Definition at line 121 of file Rectangle.cpp.
References Cerr, Domaine::coord(), Zone::domaine(), est_egal(), finl, Zone::les_elems(), Elem_geom_base::ma_zone, min(), min_array(), Zone::nb_elem(), and Ref_Zone::valeur().
Referenced by reordonner().
{
  Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  IntTab& elem=zone.les_elems();
  ArrOfInt S(4);
  ArrOfInt NS(4);
  DoubleTab co(4,2);
  int i,j;
  int num_poly;
  double xmin, ymin;
  const int& nb_elem=zone.nb_elem();
  for (num_poly=0; num_poly<nb_elem; num_poly++)
    {
      NS=-1;
      for(i=0; i<4; i++)
        {
          S(i) = elem(num_poly,i);
          for(j=0; j<2; j++)
            co(i,j) = dom.coord(S(i), j);
        }
      xmin=min(co(0, 0), co(1, 0));
      xmin=min(xmin, co(2, 0));
      ymin=min(co(0, 1), co(1, 1));
      ymin=min(ymin, co(2, 1));
      for(i=0; i<4; i++)
        if ( est_egal(co(i, 0),xmin) && est_egal(co(i, 1),ymin))
          NS(0)=S(i);
      for(i=0; i<4; i++)
        if ( !est_egal(co(i, 0),xmin) && est_egal(co(i, 1),ymin))
          NS(1)=S(i);
      for(i=0; i<4; i++)
        if ( est_egal(co(i, 0),xmin) && !est_egal(co(i, 1),ymin))
          NS(2)=S(i);
      for(i=0; i<4; i++)
        if ( !est_egal(co(i, 0),xmin) && !est_egal(co(i, 1),ymin))
          NS(3)=S(i);
// Si un sommet vaut -1, ce n'est pas un Rectangle !
      if (min_array(NS)==-1)
        {
          Cerr << "The element " << num_poly << " is not a rectangle." << finl;
          return -1;
        }
// Sinon on remplit elem
      for(i=0; i<4; i++)
        elem(num_poly, i)=NS(i);
    }
  return 0;
}
const Rectangle & Rectangle::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Elem_geom_base.
Reimplemented in Rectangle_2D_axi, and Rectangle_axi.
Definition at line 34 of file Rectangle.cpp.
Rectangle & Rectangle::self_cast (Objet_U & r) [static]
Reimplemented from Elem_geom_base.
Reimplemented in Rectangle_2D_axi, and Rectangle_axi.
Definition at line 34 of file Rectangle.cpp.
unsigned Rectangle::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Rectangle_2D_axi, and Rectangle_axi.
Definition at line 34 of file Rectangle.cpp.
Type_Face Rectangle::type_face (int i = 0) const [inline, virtual]
Renvoie le i-ieme type de face.
Un rectangle n'a qu'un seul type de face.
Returns:
Type_Face
Signification: un type de face
Contraintes: toujours egal a Faces::segment_2D (si i=0)
Implements Elem_geom_base.
Reimplemented in Rectangle_2D_axi, and Rectangle_axi.
Definition at line 336 of file Rectangle.h.
References Cerr, Process::exit(), finl, and Faces::segment_2D.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A rectangle has not " << i << " types of face" << finl;
      exit();
    }
// Cerr << finl;
// Cerr << "on ait dans Type_Face Rectangle::type_face(int i) const" << finl;
  return Faces::segment_2D;
}
Member Data Documentation
const Type_info Rectangle::info_obj [static]
Reimplemented from Elem_geom_base.
Reimplemented in Rectangle_2D_axi, and Rectangle_axi.
Definition at line 42 of file Rectangle.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Rectangle.h
src/Kernel/Geometrie/Rectangle.cpp