TRUST: PDF_model Class Reference
PDF_model Class Reference
: class PDF_model
<Description of class PDF_model>
#include <PDF_model.h>
Public Member Functions
PDF_model ()
~PDF_model ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
double get_vitesse_imposee (ArrOfDouble &, int)
void affecter_vitesse_imposee (Zone_VF &, const DoubleTab &)
double eta () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static PDF_model & self_cast (Objet_U &)
static const PDF_model & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_Don vitesse_imposee_lu_
Champ_Don vitesse_imposee_
double eta_
double coefku_
double temps_relax_
double echelle_relax_
int type_vitesse_imposee_
int local_
Private Attributes
Vect_Parser_U parsers_
Friends
class Source_PDF_base
class Source_PDF_EF
Detailed Description
: class PDF_model
<Description of class PDF_model>
Definition at line 35 of file PDF_model.h.
Constructor & Destructor Documentation
PDF_model()
PDF_model::PDF_model ()
Definition at line 27 of file PDF_model.cpp.
~PDF_model()
PDF_model::~PDF_model ()
Definition at line 27 of file PDF_model.cpp.
Member Function Documentation
affecter_vitesse_imposee()
void PDF_model::affecter_vitesse_imposee (Zone_VF & la_zone, const DoubleTab & coords)
Definition at line 98 of file PDF_model.cpp.
{
  if (type_vitesse_imposee_ == 1)
    {
      int nb_som_tot = la_zone.nb_som_tot();
      DoubleTab& vitesse_imposee_ref = vitesse_imposee_.valeur().valeurs();
      int dim = Objet_U::dimension;
      ArrOfDouble x(dim);
      for (int i = 0; i < nb_som_tot; i++)
        {
          for (int j = 0; j < dim; j++)
            {
              x[j] = coords(i,j);
            }
          for (int j = 0; j < dim; j++)
            {
              vitesse_imposee_ref(i,j) = get_vitesse_imposee(x,j);
            }
        }
    }
  else
    {
      Cerr << __FILE__ << ", line " << (int)__LINE__ << " : Unexpected error." << finl;
      exit();
    }
}
References Cerr, Objet_U::dimension, Process::exit(), finl, get_vitesse_imposee(), Zone_dis_base::nb_som_tot(), type_vitesse_imposee_, Deriv_Champ_Don_base::valeur(), Champ_Don_base::valeurs(), and vitesse_imposee_.
Referenced by Source_PDF_EF::associer_pb().
cree_instance()
Objet_U * PDF_model::cree_instance () static
Definition at line 27 of file PDF_model.cpp.
duplique()
int PDF_model::duplique () const override virtual
Implements Objet_U.
Definition at line 27 of file PDF_model.cpp.
eta()
double PDF_model::eta () const inline
Definition at line 41 of file PDF_model.h.
{ return eta_; }
References eta_.
get_info()
const Type_info * PDF_model::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 27 of file PDF_model.cpp.
get_vitesse_imposee()
double PDF_model::get_vitesse_imposee (ArrOfDouble & x, int comp)
Definition at line 129 of file PDF_model.cpp.
{
  int dim = Objet_U::dimension;
  for (int i = 0; i < dim; i++)
    {
      parsers_[comp].setVar(i,x[i]);
    }
  return parsers_[comp].eval();
}
References Objet_U::dimension, and parsers_.
Referenced by affecter_vitesse_imposee(), and Source_PDF_EF::compute_vitesse_imposee_projete().
info()
const Type_info * PDF_model::info () static
Definition at line 27 of file PDF_model.cpp.
lire_motcle_non_standard()
int PDF_model::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Objet_U.
Definition at line 59 of file PDF_model.cpp.
{
  if (un_mot == "vitesse_imposee_fonction")
    {
      if (Process::je_suis_maitre())
        {
          Cerr << " PDF_model is reading imposed velocity... " << finl;
        }
      type_vitesse_imposee_ = 1;
      Nom expr_vit_imp;
      int dim = Objet_U::dimension;
      parsers_.dimensionner(dim);
      for (int i = 0; i < dim; i++)
        {
          is >> expr_vit_imp;
          std::string sx(expr_vit_imp);
          for (auto & c: sx) c = toupper(c);
          parsers_[i].setString(sx);
          parsers_[i].setNbVar(4);
          parsers_[i].addVar("x");
          parsers_[i].addVar("y");
          parsers_[i].addVar("z");
          parsers_[i].addVar("t");
          parsers_[i].parseString();
        }
    }
  else if (un_mot == "vitesse_imposee_data")
    {
      type_vitesse_imposee_ = 0;
      is >> vitesse_imposee_lu_;
    }
  else
    {
      Cerr << "PDF_model: token not understood: " << un_mot << finl;
      Process::exit();
    }
  return 1;
}
References Cerr, Objet_U::dimension, vect_impl::dimensionner(), Process::exit(), finl, Process::je_suis_maitre(), parsers_, type_vitesse_imposee_, and vitesse_imposee_lu_.
printOn()
Sortie & PDF_model::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 30 of file PDF_model.cpp.
{
  Objet_U::printOn(os);
  return os;
}
References Objet_U::printOn().
readOn()
Entree & PDF_model::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 36 of file PDF_model.cpp.
{
// (xdata documentation is in the TRAD_2.org because we need a special bloc_lecture object)
  type_vitesse_imposee_ = -1; //DEFAULT VALUE = not set
  Param param(que_suis_je());
  param.ajouter("eta",&eta_, Param::REQUIRED);
  temps_relax_=1.0e+12;
  param.ajouter("temps_relaxation_coefficient_PDF",&temps_relax_,Param::OPTIONAL);
  echelle_relax_=5.0e-2;
  param.ajouter("echelle_relaxation_coefficient_PDF",&echelle_relax_,Param::OPTIONAL);
  param.ajouter_flag("local",&local_);
  param.ajouter_non_std("vitesse_imposee_data",(this),Param::OPTIONAL);
  param.ajouter_non_std("vitesse_imposee_fonction",(this),Param::OPTIONAL);
  param.lire_avec_accolades_depuis(is);
  if (type_vitesse_imposee_ == -1)
    {
      Cerr << "PDF_model: you must specify either 'vitesse_imposee_data' or 'vitesse_imposee_fonction'" << finl;
      Process::exit();
    }
  coefku_ = 1./eta_;
  return is;
}
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), Cerr, coefku_, echelle_relax_, eta_, Process::exit(), finl, Param::lire_avec_accolades_depuis(), local_, Param::OPTIONAL, Objet_U::que_suis_je(), Param::REQUIRED, temps_relax_, and type_vitesse_imposee_.
self_cast() [1/2]
const PDF_model & PDF_model::self_cast (const Objet_U & r) static
Definition at line 27 of file PDF_model.cpp.
self_cast() [2/2]
PDF_model & PDF_model::self_cast (Objet_U & r) static
Definition at line 27 of file PDF_model.cpp.
taille_memoire()
unsigned PDF_model::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 27 of file PDF_model.cpp.
Friends And Related Function Documentation
Source_PDF_base
friend class Source_PDF_base friend
Definition at line 53 of file PDF_model.h.
Source_PDF_EF
friend class Source_PDF_EF friend
Definition at line 54 of file PDF_model.h.
Member Data Documentation
coefku_
double PDF_model::coefku_ protected
Definition at line 48 of file PDF_model.h.
Referenced by readOn().
echelle_relax_
double PDF_model::echelle_relax_ protected
Definition at line 50 of file PDF_model.h.
Referenced by Source_PDF_EF::associer_pb(), readOn(), and Source_PDF_base::readOn().
eta_
double PDF_model::eta_ protected
Definition at line 47 of file PDF_model.h.
Referenced by Source_PDF_EF::ajouter_(), Source_PDF_EF::contribuer_a_avec(), eta(), Source_PDF_base::get_tuvw_local(), and readOn().
info_obj
const Type_info PDF_model::info_obj static
Definition at line 37 of file PDF_model.h.
local_
int PDF_model::local_ protected
Definition at line 52 of file PDF_model.h.
Referenced by Source_PDF_EF::associer_pb(), and readOn().
parsers_
Vect_Parser_U PDF_model::parsers_ private
Definition at line 56 of file PDF_model.h.
Referenced by get_vitesse_imposee(), and lire_motcle_non_standard().
temps_relax_
double PDF_model::temps_relax_ protected
Definition at line 49 of file PDF_model.h.
Referenced by Source_PDF_EF::associer_pb(), readOn(), and Source_PDF_base::readOn().
type_vitesse_imposee_
int PDF_model::type_vitesse_imposee_ protected
Definition at line 51 of file PDF_model.h.
Referenced by affecter_vitesse_imposee(), Source_PDF_EF::associer_pb(), lire_motcle_non_standard(), and readOn().
vitesse_imposee_
Champ_Don PDF_model::vitesse_imposee_ protected
Definition at line 46 of file PDF_model.h.
Referenced by affecter_vitesse_imposee(), Source_PDF_EF::associer_pb(), Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), and Source_PDF_EF::compute_vitesse_imposee_projete().
vitesse_imposee_lu_
Champ_Don PDF_model::vitesse_imposee_lu_ protected
Definition at line 45 of file PDF_model.h.
Referenced by Source_PDF_EF::associer_pb(), and lire_motcle_non_standard().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/PDF_model.h
src/ThHyd/Incompressible/PDF_model.cpp