TRUST: Cond_lim_base Class Reference
Cond_lim_base Class Reference abstract
classe Cond_lim_base
Classe de base pour la hierarchie des classes qui representent
les differentes conditions aux limites (Dirichlet, Neumann ...).
Un objet condition aux limite sert a definir, pour une equation
donnee, les conditions aux limites a appliquer sur une frontiere
d'un domaine.
Chaque objet Cond_lim_base contient une reference vers l'objet
Zone_Cl_dis_base dont il fait partie.
Chaque objet contient egalement un objet Champ_front contenant les
valeurs a imposer sur la frontiere.
#include <Cond_lim_base.h>
Public Member Functions
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Detailed Description
classe Cond_lim_base
Classe de base pour la hierarchie des classes qui representent
les differentes conditions aux limites (Dirichlet, Neumann ...).
Un objet condition aux limite sert a definir, pour une equation
donnee, les conditions aux limites a appliquer sur une frontiere
d'un domaine.
Chaque objet Cond_lim_base contient une reference vers l'objet
Zone_Cl_dis_base dont il fait partie.
Chaque objet contient egalement un objet Champ_front contenant les
valeurs a imposer sur la frontiere.
Definition at line 47 of file Cond_lim_base.h.
Constructor & Destructor Documentation
Cond_lim_base()
Cond_lim_base::Cond_lim_base ()
Definition at line 20 of file Cond_lim_base.cpp.
~Cond_lim_base()
Cond_lim_base::~Cond_lim_base () override
Definition at line 20 of file Cond_lim_base.cpp.
Member Function Documentation
a_mettre_a_jour_ss_pas_dt()
int Cond_lim_base::a_mettre_a_jour_ss_pas_dt () virtual
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
Reimplemented in Echange_impose_base.
Definition at line 172 of file Cond_lim_base.cpp.
{
  return 0;
}
Referenced by Zone_Cl_dis_base::mettre_a_jour_ss_pas_dt().
associer_fr_dis_base()
void Cond_lim_base::associer_fr_dis_base (const Frontiere_dis_base & fr) virtual
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Reimplemented in Neumann_sortie_libre, Echange_impose_base, Frottement_impose_base, Neumann_loi_paroi, and Echange_interne_impose.
Definition at line 237 of file Cond_lim_base.cpp.
{
  assert(le_champ_front.non_nul());
  le_champ_front.associer_fr_dis_base(fr);
  modifier_val_imp = 0;
}
References Champ_front::associer_fr_dis_base(), le_champ_front, modifier_val_imp, and O_U_Ptr::non_nul().
Referenced by Neumann_sortie_libre::associer_fr_dis_base(), Echange_impose_base::associer_fr_dis_base(), and Terme_Source_Th_TdivU_VEF_Face::modifier_zone_cl().
associer_zone_cl_dis_base()
void Cond_lim_base::associer_zone_cl_dis_base (const Zone_Cl_dis_base & zcl) virtual
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Reimplemented in Frottement_impose_base, and Neumann_loi_paroi.
Definition at line 262 of file Cond_lim_base.cpp.
{
  ma_zone_cl_dis=zcl;
  le_champ_front.valeur().verifier(*this);
}
References le_champ_front, ma_zone_cl_dis, Deriv_Champ_front_base::valeur(), and Champ_front_base::verifier().
avancer()
int Cond_lim_base::avancer (double temps) virtual
Tourne la roue de la CL.
Reimplemented in Neumann_sortie_libre, Echange_couplage_thermique, Echange_global_impose, Echange_impose_base, Echange_contact_VDF, and Echange_interne_impose.
Definition at line 97 of file Cond_lim_base.cpp.
{
  return champ_front()->avancer(temps);
}
References champ_front().
Referenced by Neumann_sortie_libre::avancer(), Echange_impose_base::avancer(), and Echange_contact_VDF::avancer().
calculer_coeffs_echange()
void Cond_lim_base::calculer_coeffs_echange (double temps) virtual
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
Reimplemented in Frottement_impose_base, and Neumann_loi_paroi.
Definition at line 199 of file Cond_lim_base.cpp.
{
  le_champ_front.calculer_coeffs_echange(temps);
}
References Champ_front::calculer_coeffs_echange(), and le_champ_front.
Referenced by Cond_lim::calculer_coeffs_echange().
champ_front() [1/3]
Champ_front & Cond_lim_base::champ_front () inline
Definition at line 189 of file Cond_lim_base.h.
{
  return le_champ_front;
}
References le_champ_front.
Referenced by Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), avancer(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Echange_contact_Correlation_VEF::calculer_Q(), Champ_Face_get_val_imp_face_bord(), Champ_Face_get_val_imp_face_bord_sym(), changer_temps_futur(), completer(), Echange_contact_Correlation_VEF::completer(), fixer_nb_valeurs_temporelles(), Zone_Cl_EF::imposer_cond_lim(), Echange_contact_Correlation_VEF::mettre_a_jour(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), Echange_contact_Correlation_VEF::readOn(), reculer(), and set_temps_defaut().
champ_front() [2/3]
const Champ_front & Cond_lim_base::champ_front () const inline
Definition at line 194 of file Cond_lim_base.h.
{
  return le_champ_front;
}
References le_champ_front.
champ_front() [3/3]
void Cond_lim_base::champ_front (int face, DoubleVect & var) const virtual
Definition at line 343 of file Cond_lim_base.cpp.
{
  le_champ_front->valeurs_face(face,var);
}
References le_champ_front.
changer_temps_futur()
void Cond_lim_base::changer_temps_futur (double temps, int i) virtual
Change le i-eme temps futur de la CL.
Reimplemented in Frottement_impose_base, Neumann_sortie_libre, Neumann_loi_paroi, Echange_couplage_thermique, Echange_global_impose, Echange_impose_base, Echange_contact_VDF, and Echange_interne_impose.
Definition at line 90 of file Cond_lim_base.cpp.
{
  champ_front()->changer_temps_futur(temps,i);
}
References champ_front().
Referenced by Neumann_sortie_libre::changer_temps_futur(), Echange_impose_base::changer_temps_futur(), and Echange_contact_VDF::changer_temps_futur().
compatible_avec_discr()
int Cond_lim_base::compatible_avec_discr (const Discretisation_base &) const virtual
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented in Scalaire_impose_paroi, Sortie_libre_Gradient_Pression_impose_VEFPreP1B, Sortie_libre_Gradient_Pression_libre_VEFPreP1B, Echange_externe_impose, Echange_impose_base, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Sortie_libre_Gradient_Pression_libre_VEF, Echange_couplage_thermique, Echange_global_impose, and Echange_interne_global_parfait.
Definition at line 287 of file Cond_lim_base.cpp.
{
  return 1;
}
Referenced by Cond_lim::compatible_avec_discr().
compatible_avec_eqn()
virtual int Cond_lim_base::compatible_avec_eqn (const Equation_base &) const pure virtual
Implemented in Dirichlet_paroi_defilante, Navier, Scalaire_impose_paroi, Cond_lim_utilisateur_base, Periodique, Sortie_libre_Gradient_Pression_libre_VEFPreP1B, Echange_externe_impose_H, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Neumann_sortie_libre_Temp_H, Temperature_imposee_paroi_H, Sortie_libre_pression_imposee_QC, Dirichlet_paroi_fixe, Entree_fluide_concentration_imposee, Entree_fluide_Fluctu_Temperature_imposee, Entree_fluide_Flux_Chaleur_Turbulente_imposee, Entree_fluide_fraction_massique_imposee, Entree_fluide_T_h_imposee, Entree_fluide_temperature_imposee, Entree_fluide_V2_impose, Entree_fluide_vitesse_imposee, Neumann_paroi, Neumann_paroi_adiabatique, Neumann_paroi_flux_nul, Neumann_sortie_libre, Paroi_Knudsen_non_negligeable, Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Sortie_libre_Text_H_ext, Temperature_imposee_paroi, Entree_fluide_alpha_impose, Echange_couplage_thermique, Echange_impose_base, Echange_contact_Correlation_VDF, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Echange_contact_Correlation_VEF, Sortie_libre_Gradient_Pression_impose_VEF, and Sortie_libre_Gradient_Pression_libre_VEF.
Referenced by Cond_lim::compatible_avec_eqn().
completer()
void Cond_lim_base::completer () virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented in Dirichlet_paroi_defilante, Periodique, Sortie_libre_Gradient_Pression_libre_VEFPreP1B, Echange_externe_impose_H, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Neumann_sortie_libre_Temp_H, Temperature_imposee_paroi_H, Sortie_libre_pression_imposee_QC, Frottement_impose_base, Paroi_Knudsen_non_negligeable, Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Neumann_loi_paroi, Echange_couplage_thermique, Echange_global_impose, Echange_interne_global_impose, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_interne_impose, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Echange_contact_Correlation_VEF, and Sortie_libre_Gradient_Pression_libre_VEF.
Definition at line 83 of file Cond_lim_base.cpp.
{
  champ_front()->completer();
}
References champ_front().
Referenced by Cond_lim::completer(), Echange_externe_impose_H::completer(), Echange_global_impose::completer(), Echange_contact_Correlation_VDF::completer(), Echange_interne_impose::completer(), and Terme_Source_Th_TdivU_VEF_Face::modifier_zone_cl().
err_pas_compatible() [1/2]
void Cond_lim_base::err_pas_compatible (const Discretisation_base & discr) const protected
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Definition at line 335 of file Cond_lim_base.cpp.
{
  Cerr << "The boundary condition " << que_suis_je() << " can't be used with " << finl
       << "the discretization of kind " << discr.que_suis_je()
       << finl;
  exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
err_pas_compatible() [2/2]
void Cond_lim_base::err_pas_compatible (const Equation_base & eqn) const protected
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
Definition at line 309 of file Cond_lim_base.cpp.
{
  Cerr << "The boundary condition " << que_suis_je() << " can't apply to " << finl
       << "the equation of kind " << eqn.que_suis_je()
       << finl;
  exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Scalaire_impose_paroi::compatible_avec_discr(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::compatible_avec_discr(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::compatible_avec_discr(), Echange_impose_base::compatible_avec_discr(), Sortie_libre_Gradient_Pression_impose::compatible_avec_discr(), Sortie_libre_Pression_imposee_Orlansky::compatible_avec_discr(), Sortie_libre_Gradient_Pression_libre_VEF::compatible_avec_discr(), Echange_couplage_thermique::compatible_avec_discr(), Echange_interne_global_parfait::compatible_avec_discr(), Dirichlet_paroi_defilante::compatible_avec_eqn(), Scalaire_impose_paroi::compatible_avec_eqn(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::compatible_avec_eqn(), Echange_externe_impose_H::compatible_avec_eqn(), Entree_fluide_temperature_imposee_H::compatible_avec_eqn(), Neumann_sortie_libre_Temp_H::compatible_avec_eqn(), Temperature_imposee_paroi_H::compatible_avec_eqn(), Sortie_libre_pression_imposee_QC::compatible_avec_eqn(), Dirichlet_paroi_fixe::compatible_avec_eqn(), Entree_fluide_concentration_imposee::compatible_avec_eqn(), Entree_fluide_Fluctu_Temperature_imposee::compatible_avec_eqn(), Entree_fluide_Flux_Chaleur_Turbulente_imposee::compatible_avec_eqn(), Entree_fluide_fraction_massique_imposee::compatible_avec_eqn(), Entree_fluide_T_h_imposee::compatible_avec_eqn(), Entree_fluide_temperature_imposee::compatible_avec_eqn(), Entree_fluide_V2_impose::compatible_avec_eqn(), Entree_fluide_vitesse_imposee::compatible_avec_eqn(), Neumann_paroi::compatible_avec_eqn(), Neumann_paroi_adiabatique::compatible_avec_eqn(), Neumann_paroi_flux_nul::compatible_avec_eqn(), Neumann_sortie_libre::compatible_avec_eqn(), Paroi_Knudsen_non_negligeable::compatible_avec_eqn(), Sortie_libre_pression_imposee::compatible_avec_eqn(), Sortie_libre_pression_moyenne_imposee::compatible_avec_eqn(), Sortie_libre_Text_H_ext::compatible_avec_eqn(), Temperature_imposee_paroi::compatible_avec_eqn(), Entree_fluide_alpha_impose::compatible_avec_eqn(), Echange_couplage_thermique::compatible_avec_eqn(), Echange_impose_base::compatible_avec_eqn(), Echange_contact_Correlation_VDF::compatible_avec_eqn(), Sortie_libre_Gradient_Pression_impose::compatible_avec_eqn(), Sortie_libre_Pression_imposee_Orlansky::compatible_avec_eqn(), Echange_contact_Correlation_VEF::compatible_avec_eqn(), Sortie_libre_Gradient_Pression_impose_VEF::compatible_avec_eqn(), and Sortie_libre_Gradient_Pression_libre_VEF::compatible_avec_eqn().
fixer_nb_valeurs_temporelles()
void Cond_lim_base::fixer_nb_valeurs_temporelles (int nb_cases) virtual
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
Reimplemented in Frottement_impose_base, Neumann_sortie_libre, Neumann_loi_paroi, Echange_impose_base, and Echange_interne_impose.
Definition at line 364 of file Cond_lim_base.cpp.
{
  champ_front()->fixer_nb_valeurs_temporelles(nb_cases);
}
References champ_front().
Referenced by Neumann_sortie_libre::fixer_nb_valeurs_temporelles(), and Echange_impose_base::fixer_nb_valeurs_temporelles().
frontiere_dis() [1/2]
Frontiere_dis_base & Cond_lim_base::frontiere_dis () inline virtual
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
Returns
Frontiere_dis_base&
Signification: la frontiere discretisee a laquelle les conditions
aux limites sont associees
Contraintes:
Reimplemented in Frottement_impose_base, and Neumann_loi_paroi.
Definition at line 116 of file Cond_lim_base.h.
{
  return le_champ_front.frontiere_dis();
}
References Champ_front::frontiere_dis(), and le_champ_front.
Referenced by Op_Conv_VEF_Face::ajouter(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_Correlation_VDF::calculer_h_mon_pb(), Echange_contact_VDF::calculer_h_mon_pb(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_Q(), Echange_contact_Correlation_VEF::calculer_Q(), Echange_contact_VDF::calculer_Teta_equiv(), Echange_contact_VDF::calculer_Teta_paroi(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::calculer_trace_pression(), Equation_base::completer(), Periodique::completer(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Echange_couplage_thermique::completer(), Echange_global_impose::completer(), Echange_interne_global_impose::completer(), Echange_contact_Correlation_VDF::completer(), Echange_contact_VDF::completer(), Echange_interne_impose::completer(), Sortie_libre_Gradient_Pression_impose::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Echange_contact_Correlation_VEF::completer(), Sortie_libre_Gradient_Pression_libre_VEF::completer(), Zone_Cl_VDF::completer(), Zone_VEF_PreP1b::construire_renum_arete_perio(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), T_It_VDF_Face< _TYPE_ >::corriger_coeffs_fa7_elem_periodicite(), T_It_VDF_Face< _TYPE_ >::corriger_flux_fa7_elem_periodicite(), T_It_VDF_Face< _TYPE_ >::corriger_secmem_fa7_elem_periodicite(), Op_EF_base::dimensionner(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Equation_base::ecrire_fichier_xyz(), Cond_lim::frontiere_dis(), Zone_Cl_EF::imposer_cond_lim(), Zone_Cl_VEFP1B::imposer_cond_lim(), Zone_Cl_PolyMAC::imposer_cond_lim(), Zone_Cl_VDF::imposer_cond_lim(), Zone_Cl_VEF::imposer_cond_lim(), Zone_Cl_EF::imposer_symetrie_partiellement(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Echange_contact_Correlation_VEF::init(), Echange_contact_PolyMAC::init_op(), Echange_contact_PolyMAC_P0::init_op(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::initialiser(), Echange_couplage_thermique::initialiser(), Echange_contact_VDF::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Zone_Cl_dis_base::la_cl_de_la_face(), Assembleur_P_VDF::liste_faces_periodiques(), Zone_VF::marquer_faces_double_contrib(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEF::mettre_a_jour(), Echange_interne_impose::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Sortie_libre_Gradient_Pression_impose::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), modifieP1P1neumann(), Zone_EF::modifier_pour_Cl(), Zone_VF::modifier_pour_Cl(), Zone_VEF::modifier_pour_Cl(), Zone_VDF::modifier_pour_Cl(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VDF::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Assembleur_P_VDF::remplir(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), Echange_contact_Correlation_VDF::trier_coord(), Echange_interne_impose::update_inv_lambda(), Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries(), Champ_Face::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), Champ_Q1NC::verifie_valeurs_cl(), and Echange_contact_VDF::verifier_correspondance().
frontiere_dis() [2/2]
const Frontiere_dis_base & Cond_lim_base::frontiere_dis () const inline virtual
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
Returns
Frontiere_dis_base&
Signification: la frontiere discretisee a laquelle les conditions
aux limites sont associees
Contraintes: reference constante
Reimplemented in Frottement_impose_base, and Neumann_loi_paroi.
Definition at line 139 of file Cond_lim_base.h.
{
  return le_champ_front.frontiere_dis();
}
References Champ_front::frontiere_dis(), and le_champ_front.
get_info()
const Type_info * Cond_lim_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Cond_lim_utilisateur_base, cl_timp, paroi_adiabatique, paroi_flux_impose, paroi_contact, paroi_contact_fictif, Periodique, Sortie_libre_Gradient_Pression_impose_VEFPreP1B, Sortie_libre_Gradient_Pression_libre_VEFPreP1B, Echange_contact_PolyMAC, Echange_contact_PolyMAC_P0, Echange_externe_impose_H, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Neumann_sortie_libre_Temp_H, Temperature_imposee_paroi_H, Sortie_libre_pression_imposee_QC, Dirichlet_entree_fluide, Dirichlet_paroi_fixe, Entree_fluide_concentration_imposee, Entree_fluide_Fluctu_Temperature_imposee, Entree_fluide_Flux_Chaleur_Turbulente_imposee, Entree_fluide_fraction_massique_imposee, Entree_fluide_T_h_imposee, Entree_fluide_temperature_imposee, Entree_fluide_V2_impose, Entree_fluide_vitesse_imposee, Entree_fluide_vitesse_imposee_libre, Frottement_externe_impose, Frottement_global_impose, Frottement_impose_base, Neumann_paroi, Neumann_paroi_adiabatique, Neumann_paroi_flux_nul, Neumann_sortie_libre, Paroi_Knudsen_non_negligeable, Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Sortie_libre_Text_H_ext, Temperature_imposee_paroi, Entree_fluide_alpha_impose, Neumann_loi_paroi, Echange_couplage_thermique, Echange_externe_impose, Echange_global_impose, Echange_impose_base, Echange_interne_global_impose, Echange_interne_global_parfait, Echange_contact_Colburn_VDF, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_contact_VDF_Plaque_Flux_Cte, Echange_interne_impose, Echange_interne_parfait, PlaqThVDF, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Echange_contact_Correlation_VEF, Sortie_libre_Gradient_Pression_impose_VEF, and Sortie_libre_Gradient_Pression_libre_VEF.
Definition at line 20 of file Cond_lim_base.cpp.
info()
const Type_info * Cond_lim_base::info () static
Definition at line 20 of file Cond_lim_base.cpp.
initialiser()
int Cond_lim_base::initialiser (double temps) virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented in Sortie_libre_Gradient_Pression_impose_VEFPreP1B, Sortie_libre_Gradient_Pression_libre_VEFPreP1B, Neumann_sortie_libre, Echange_couplage_thermique, Echange_global_impose, Echange_impose_base, Echange_contact_VDF, Echange_interne_impose, Sortie_libre_Gradient_Pression_libre_VEF, and Frottement_impose_base.
Definition at line 128 of file Cond_lim_base.cpp.
{
  return le_champ_front->initialiser(temps,zone_Cl_dis().inconnue());
}
References le_champ_front, and zone_Cl_dis().
Referenced by Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::initialiser(), Neumann_sortie_libre::initialiser(), Echange_impose_base::initialiser(), and Sortie_libre_Gradient_Pression_libre_VEF::initialiser().
injecter_dans_champ_inc()
void Cond_lim_base::injecter_dans_champ_inc (const Champ_Inc &) const virtual
Definition at line 348 of file Cond_lim_base.cpp.
{
  Cerr << "Cond_lim_base::injecter_dans_champ_inc()" << finl;
  Cerr << "this method does nothing and must be overloaded " << finl;
  Cerr << "Contact TRUST support." << finl;
  exit();
}
References Cerr, Process::exit(), and finl.
Referenced by Cond_lim::injecter_dans_champ_inc().
mettre_a_jour()
void Cond_lim_base::mettre_a_jour (double temps) virtual
Effectue une mise a jour en temps de la condition aux limites.
Reimplemented in Periodique, Sortie_libre_Gradient_Pression_libre_VEFPreP1B, Echange_contact_PolyMAC, Echange_contact_PolyMAC_P0, Neumann_paroi, Neumann_sortie_libre, Echange_couplage_thermique, Echange_global_impose, Sortie_libre_Gradient_Pression_libre_VEF, Echange_interne_impose, Sortie_libre_Gradient_Pression_impose_VEFPreP1B, Sortie_libre_pression_moyenne_imposee, Echange_impose_base, Echange_contact_Correlation_VDF, Echange_contact_VDF, PlaqThVDF, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, and Echange_contact_Correlation_VEF.
Definition at line 148 of file Cond_lim_base.cpp.
{
  le_champ_front.mettre_a_jour(temps);
}
References le_champ_front, and Champ_front::mettre_a_jour().
Referenced by Cond_lim::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Neumann_paroi::mettre_a_jour(), Neumann_sortie_libre::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEF::mettre_a_jour(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::mettre_a_jour(), Sortie_libre_pression_moyenne_imposee::mettre_a_jour(), Echange_impose_base::mettre_a_jour(), Sortie_libre_Gradient_Pression_impose::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), and Zone_Cl_dis_base::mettre_a_jour_ss_pas_dt().
printOn()
Sortie & Cond_lim_base::printOn (Sortie & s) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Cond_lim_utilisateur_base, cl_timp, paroi_adiabatique, paroi_flux_impose, paroi_contact, paroi_contact_fictif, Periodique, Sortie_libre_Gradient_Pression_impose_VEFPreP1B, Sortie_libre_Gradient_Pression_libre_VEFPreP1B, Echange_contact_PolyMAC, Echange_contact_PolyMAC_P0, Echange_externe_impose_H, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Neumann_sortie_libre_Temp_H, Temperature_imposee_paroi_H, Sortie_libre_pression_imposee_QC, Dirichlet_entree_fluide, Dirichlet_paroi_fixe, Entree_fluide_concentration_imposee, Entree_fluide_Fluctu_Temperature_imposee, Entree_fluide_Flux_Chaleur_Turbulente_imposee, Entree_fluide_fraction_massique_imposee, Entree_fluide_T_h_imposee, Entree_fluide_temperature_imposee, Entree_fluide_V2_impose, Entree_fluide_vitesse_imposee, Entree_fluide_vitesse_imposee_libre, Frottement_externe_impose, Frottement_global_impose, Frottement_impose_base, Neumann_paroi, Neumann_paroi_adiabatique, Neumann_paroi_flux_nul, Neumann_sortie_libre, Paroi_Knudsen_non_negligeable, Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Sortie_libre_Text_H_ext, Temperature_imposee_paroi, Entree_fluide_alpha_impose, Neumann_loi_paroi, Echange_couplage_thermique, Echange_externe_impose, Echange_global_impose, Echange_impose_base, Echange_interne_global_impose, Echange_interne_global_parfait, Echange_contact_Colburn_VDF, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_contact_VDF_Plaque_Flux_Cte, Echange_interne_impose, Echange_interne_parfait, PlaqThVDF, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Echange_contact_Correlation_VEF, Sortie_libre_Gradient_Pression_impose_VEF, and Sortie_libre_Gradient_Pression_libre_VEF.
Definition at line 40 of file Cond_lim_base.cpp.
{
  return s << le_champ_front ;
}
References le_champ_front.
readOn()
Entree & Cond_lim_base::readOn (Entree & s) override protected virtual
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Cond_lim_utilisateur_base, cl_timp, paroi_adiabatique, paroi_flux_impose, paroi_contact, paroi_contact_fictif, Periodique, Sortie_libre_Gradient_Pression_impose_VEFPreP1B, Sortie_libre_Gradient_Pression_libre_VEFPreP1B, Echange_contact_PolyMAC, Echange_contact_PolyMAC_P0, Echange_externe_impose_H, Entree_fluide_temperature_imposee_H, Frontiere_ouverte_rho_u_impose, Neumann_sortie_libre_Temp_H, Temperature_imposee_paroi_H, Sortie_libre_pression_imposee_QC, Dirichlet_entree_fluide, Dirichlet_paroi_fixe, Entree_fluide_concentration_imposee, Entree_fluide_Fluctu_Temperature_imposee, Entree_fluide_Flux_Chaleur_Turbulente_imposee, Entree_fluide_fraction_massique_imposee, Entree_fluide_T_h_imposee, Entree_fluide_temperature_imposee, Entree_fluide_V2_impose, Entree_fluide_vitesse_imposee, Entree_fluide_vitesse_imposee_libre, Frottement_externe_impose, Frottement_global_impose, Frottement_impose_base, Neumann_paroi, Neumann_paroi_adiabatique, Neumann_paroi_flux_nul, Neumann_sortie_libre, Paroi_Knudsen_non_negligeable, Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Sortie_libre_Text_H_ext, Temperature_imposee_paroi, Entree_fluide_alpha_impose, Neumann_loi_paroi, Echange_couplage_thermique, Echange_externe_impose, Echange_global_impose, Echange_impose_base, Echange_interne_global_impose, Echange_interne_global_parfait, Echange_contact_Colburn_VDF, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_contact_VDF_Plaque_Flux_Cte, Echange_interne_impose, Echange_interne_parfait, PlaqThVDF, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Echange_contact_Correlation_VEF, Sortie_libre_Gradient_Pression_impose_VEF, and Sortie_libre_Gradient_Pression_libre_VEF.
Definition at line 62 of file Cond_lim_base.cpp.
{
  return s >> le_champ_front ;
}
References le_champ_front.
Referenced by Dirichlet::readOn(), Dirichlet_paroi_defilante::readOn(), Neumann::readOn(), Neumann_val_ext::readOn(), Dirichlet_entree_fluide::readOn(), Entree_fluide_concentration_imposee::readOn(), Entree_fluide_Fluctu_Temperature_imposee::readOn(), Entree_fluide_Flux_Chaleur_Turbulente_imposee::readOn(), Entree_fluide_fraction_massique_imposee::readOn(), Entree_fluide_temperature_imposee::readOn(), Entree_fluide_V2_impose::readOn(), Entree_fluide_vitesse_imposee::readOn(), Entree_fluide_vitesse_imposee_libre::readOn(), Neumann_paroi::readOn(), and Entree_fluide_alpha_impose::readOn().
reculer()
int Cond_lim_base::reculer (double temps) virtual
Tourne la roue de la CL.
Reimplemented in Neumann_sortie_libre, Echange_couplage_thermique, Echange_global_impose, Echange_impose_base, Echange_contact_VDF, and Echange_interne_impose.
Definition at line 104 of file Cond_lim_base.cpp.
{
  return champ_front()->reculer(temps);
}
References champ_front().
Referenced by Neumann_sortie_libre::reculer(), Echange_impose_base::reculer(), and Echange_contact_VDF::reculer().
self_cast() [1/2]
const Cond_lim_base & Cond_lim_base::self_cast (const Objet_U & r) static
Definition at line 20 of file Cond_lim_base.cpp.
self_cast() [2/2]
Cond_lim_base & Cond_lim_base::self_cast (Objet_U & r) static
Definition at line 20 of file Cond_lim_base.cpp.
set_modifier_val_imp()
void Cond_lim_base::set_modifier_val_imp (int drap) inline
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
Definition at line 222 of file Cond_lim_base.h.
{
// positionne le drapeau a 0 ou 1
  modifier_val_imp = (drap==1);
}
References modifier_val_imp.
Referenced by Cond_lim::set_modifier_val_imp().
set_temps_defaut()
void Cond_lim_base::set_temps_defaut (double temps) virtual
Change le i-eme temps futur de la cl.
Reimplemented in Frottement_impose_base, Neumann_sortie_libre, Neumann_loi_paroi, Echange_couplage_thermique, Echange_global_impose, Echange_impose_base, and Echange_interne_impose.
Definition at line 357 of file Cond_lim_base.cpp.
{
  champ_front()->set_temps_defaut(temps);
}
References champ_front().
Referenced by Neumann_sortie_libre::set_temps_defaut(), and Echange_impose_base::set_temps_defaut().
verifie_ch_init_nb_comp()
void Cond_lim_base::verifie_ch_init_nb_comp () const virtual
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
Reimplemented in Dirichlet, Echange_contact_PolyMAC, Echange_contact_PolyMAC_P0, Frottement_impose_base, Neumann_paroi, Neumann_sortie_libre, Neumann_loi_paroi, Echange_externe_impose, Echange_interne_global_impose, and Echange_interne_impose.
Definition at line 215 of file Cond_lim_base.cpp.
{
}
zone_Cl_dis() [1/2]
Zone_Cl_dis_base & Cond_lim_base::zone_Cl_dis () inline
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
Returns
Zone_Cl_dis_base&
Signification: la zone des conditions aux limites discretisee dont
l'objet fait partie
Contraintes:
Definition at line 161 of file Cond_lim_base.h.
{
  return ma_zone_cl_dis.valeur();
}
References ma_zone_cl_dis, and Ref_Zone_Cl_dis_base::valeur().
Referenced by Echange_contact_Correlation_VDF::calculer_CL(), Echange_contact_Correlation_VEF::calculer_CL(), Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_Correlation_VDF::calculer_h_mon_pb(), Echange_contact_VDF::calculer_h_mon_pb(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_Q(), Echange_contact_Correlation_VEF::calculer_Q(), Echange_contact_VDF::calculer_Teta_paroi(), Echange_contact_Correlation_VDF::calculer_Tfluide(), Echange_contact_Correlation_VEF::calculer_Tfluide(), Periodique::completer(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), Paroi_Knudsen_non_negligeable::completer(), Echange_interne_global_impose::completer(), Echange_contact_Correlation_VDF::completer(), Echange_contact_VDF::completer(), Echange_interne_impose::completer(), Sortie_libre_Gradient_Pression_impose::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Echange_contact_Correlation_VEF::completer(), Sortie_libre_Gradient_Pression_libre_VEF::completer(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Echange_contact_Correlation_VEF::init(), Echange_contact_PolyMAC::init_op(), Echange_contact_PolyMAC_P0::init_op(), Echange_contact_Correlation_VDF::init_tab_echange(), initialiser(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), Neumann_sortie_libre::initialiser(), Echange_couplage_thermique::initialiser(), Echange_global_impose::initialiser(), Echange_impose_base::initialiser(), Echange_contact_VDF::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Echange_contact_Correlation_VDF::limpr(), Echange_contact_Correlation_VEF::limpr(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Zone_VDF::modifier_pour_Cl(), Echange_contact_Correlation_VDF::trier_coord(), Dirichlet::verifie_ch_init_nb_comp(), Neumann_paroi::verifie_ch_init_nb_comp(), Neumann_sortie_libre::verifie_ch_init_nb_comp(), Echange_externe_impose::verifie_ch_init_nb_comp(), and Echange_contact_VDF::verifier_correspondance().
zone_Cl_dis() [2/2]
const Zone_Cl_dis_base & Cond_lim_base::zone_Cl_dis () const inline
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
Returns
Zone_Cl_dis_base&
Signification: la zone des conditions aux limites discretisee dont
l'objet fait partie
Contraintes: reference constante
Definition at line 184 of file Cond_lim_base.h.
{
  return ma_zone_cl_dis.valeur();
}
References ma_zone_cl_dis, and Ref_Zone_Cl_dis_base::valeur().
Member Data Documentation
info_obj
const Type_info Cond_lim_base::info_obj static
Definition at line 50 of file Cond_lim_base.h.
le_champ_front
Champ_front Cond_lim_base::le_champ_front protected
Definition at line 90 of file Cond_lim_base.h.
Referenced by associer_fr_dis_base(), associer_zone_cl_dis_base(), calculer_coeffs_echange(), champ_front(), Paroi_Knudsen_non_negligeable::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Neumann::flux_impose(), Sortie_libre_pression_imposee_QC::flux_impose(), Neumann_paroi::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Sortie_libre_Gradient_Pression_impose::flux_impose(), Sortie_libre_Pression_imposee_Orlansky::flux_impose(), Sortie_libre_Gradient_Pression_impose_VEF::flux_impose(), frontiere_dis(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Sortie_libre_Gradient_Pression_libre_VEF::Grad_P_lib_VEF(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), Echange_interne_global_impose::init(), Echange_interne_impose::init(), initialiser(), Echange_couplage_thermique::initialiser(), mettre_a_jour(), Neumann_paroi::mettre_a_jour(), Sortie_libre_pression_moyenne_imposee::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), printOn(), Dirichlet_homogene::readOn(), Neumann_homogene::readOn(), Symetrie::readOn(), readOn(), Periodique::readOn(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::readOn(), Neumann_sortie_libre_Temp_H::readOn(), Sortie_libre_pression_imposee_QC::readOn(), Dirichlet_paroi_fixe::readOn(), Entree_fluide_T_h_imposee::readOn(), Neumann_sortie_libre::readOn(), Paroi_Knudsen_non_negligeable::readOn(), Sortie_libre_pression_imposee::readOn(), Sortie_libre_pression_moyenne_imposee::readOn(), Sortie_libre_Text_H_ext::readOn(), Sortie_libre_Gradient_Pression_impose::readOn(), Sortie_libre_Pression_imposee_Orlansky::readOn(), Sortie_libre_Gradient_Pression_impose_VEF::readOn(), Sortie_libre_Gradient_Pression_libre_VEF::readOn(), Echange_impose_base::T_ext(), Echange_externe_impose_H::T_ext(), Dirichlet::val_imp(), Entree_fluide_temperature_imposee_H::val_imp(), Temperature_imposee_paroi_H::val_imp(), Dirichlet::val_imp_au_temps(), Frontiere_ouverte_rho_u_impose::val_imp_au_temps(), Dirichlet::verifie_ch_init_nb_comp(), Neumann_paroi::verifie_ch_init_nb_comp(), Neumann_sortie_libre::verifie_ch_init_nb_comp(), and Echange_externe_impose::verifie_ch_init_nb_comp().
ma_zone_cl_dis
Ref_Zone_Cl_dis_base Cond_lim_base::ma_zone_cl_dis protected
Definition at line 91 of file Cond_lim_base.h.
Referenced by associer_zone_cl_dis_base(), Frottement_impose_base::associer_zone_cl_dis_base(), Neumann_loi_paroi::associer_zone_cl_dis_base(), Echange_global_impose::champ_exterieur(), Echange_couplage_thermique::champ_exterieur(), Frontiere_ouverte_rho_u_impose::compatible_avec_eqn(), Echange_externe_impose_H::completer(), Entree_fluide_temperature_imposee_H::completer(), Frontiere_ouverte_rho_u_impose::completer(), Neumann_sortie_libre_Temp_H::completer(), Temperature_imposee_paroi_H::completer(), Sortie_libre_pression_imposee_QC::completer(), Sortie_libre_pression_imposee::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Sortie_libre_pression_imposee_QC::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Echange_couplage_thermique::get_dRho_dCp(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Sortie_libre_Gradient_Pression_libre_VEF::Grad_P_lib_VEF(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), Sortie_libre_pression_moyenne_imposee::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), and zone_Cl_dis().
modifier_val_imp
int Cond_lim_base::modifier_val_imp protected
Definition at line 96 of file Cond_lim_base.h.
Referenced by associer_fr_dis_base(), Neumann_sortie_libre::associer_fr_dis_base(), Echange_externe_impose_H::completer(), Entree_fluide_temperature_imposee_H::completer(), Neumann_sortie_libre_Temp_H::completer(), Temperature_imposee_paroi_H::completer(), set_modifier_val_imp(), Echange_externe_impose_H::T_ext(), Neumann_sortie_libre_Temp_H::val_ext(), Entree_fluide_temperature_imposee_H::val_imp(), and Temperature_imposee_paroi_H::val_imp().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Cond_lim_base.h
src/Kernel/Framework/Cond_lim_base.cpp