TRUST: Static_Int_Lists Class Reference
Static_Int_Lists Class Reference
Cette classe permet de stocker des listes d'entiers accessibles
en temps constant. La taille des listes ne peut pas changer sans
perdre le contenu (ce sont des listes statiques).
Exemple:
Static_Int_List l;
ArrOfInt tailles(3);
tailles[0] = 2; tailles[1] = 3; tailles[2] = 0;
// On reserve la memoire pour trois listes de taille 2, 3 et 0:
l.set_list_sizes(tailles);
// On affecte une valeur au deuxieme element de la premiere liste:
l.set_value(0,1,765);
// Affiche la valeur
Cout << l(0,1);.
#include <Static_Int_Lists.h>
Public Member Functions
void set_list_sizes (const ArrOfInt &sizes)
detruit les listes existantes et en cree de nouvelles.
On cree autant de listes que d'elements dans le tableau sizes.
La i-ieme liste a une taille sizes[i]
Les valeurs sizes doivent etre positives ou nulles.
void reset ()
detruit toutes les listes
void copy_list_to_array (int i_liste, ArrOfInt &array) const
copie la i-ieme liste dans le tableau fourni
Le tableau array doit etre resizable.
void set_value (int i_liste, int i_element, int valeur)
affecte la "valeur" au j-ieme element de la i-ieme liste avec
0 <= i < get_nb_lists() et 0 <= j < get_list_size(i)
int operator() (int i_liste, int i_element) const
renvoie le j-ieme element de la i-ieme liste avec
0 <= i < get_nb_lists() et 0 <= j < get_list_size(i)
int get_list_size (int i_liste) const
renvoie le nombre d'elements de la liste i
int get_nb_lists () const
renvoie le nombre de listes stockees
const ArrOfInt & get_index () const
const ArrOfInt & get_data () const
void set_data (const ArrOfInt &data)
remplace les valeurs stockes par toutes les listes par celles
du tableau data. data doit avoir pour taille la somme des tailles de toutes
les listes.
void set_index_data (const ArrOfInt &index, const ArrOfInt &data)
remplace index et data.
void trier_liste (int i)
tri par ordre croissant des valeurs de la i-ieme liste.
Si num_liste < 0, on trie toutes les listes.
void set (const ArrsOfInt &)
Sortie & printOn (Sortie &os) const
Entree & readOn (Entree &is)
Sortie & ecrire (Sortie &os) const
Private Attributes
ArrOfInt index_
ArrOfInt valeurs_
Detailed Description
Cette classe permet de stocker des listes d'entiers accessibles
en temps constant. La taille des listes ne peut pas changer sans
perdre le contenu (ce sont des listes statiques).
Exemple:
Static_Int_List l;
ArrOfInt tailles(3);
tailles[0] = 2; tailles[1] = 3; tailles[2] = 0;
// On reserve la memoire pour trois listes de taille 2, 3 et 0:
l.set_list_sizes(tailles);
// On affecte une valeur au deuxieme element de la premiere liste:
l.set_value(0,1,765);
// Affiche la valeur
Cout << l(0,1);.
Definition at line 36 of file Static_Int_Lists.h.
Member Function Documentation
copy_list_to_array()
void Static_Int_Lists::copy_list_to_array (int i_liste, ArrOfInt & array) const
copie la i-ieme liste dans le tableau fourni
Le tableau array doit etre resizable.
Definition at line 102 of file Static_Int_Lists.cpp.
{
  const int n = get_list_size(i);
  array.resize_array(n, Array_base::NOCOPY_NOINIT);
  const int index = index_[i];
  array.inject_array(valeurs_, n, 0 /* destination index */, index /* source index */);
}
References get_list_size(), index_, TRUSTArray< _TYPE_ >::inject_array(), Array_base::NOCOPY_NOINIT, TRUSTArray< _TYPE_ >::resize_array(), and valeurs_.
Referenced by append_global_md(), DomaineCutter::construire_faces_bords_ssdom(), DomaineCutter::construire_faces_internes_ssdom(), DomaineCutter::construire_faces_raccords_ssdom(), DomaineCutter::construire_sous_domaine(), find_adjacent_elements(), and Refine_Mesh::find_edge().
ecrire()
Sortie & Static_Int_Lists::ecrire (Sortie & os) const
Definition at line 125 of file Static_Int_Lists.cpp.
{
  os << "nb lists       : " << get_nb_lists() << finl;
  os << "sizes of lists : ";
  for (int i=0; i<get_nb_lists(); ++i)
    {
      os << get_list_size(i) << " ";
    }
  os << finl;
  for (int i=0; i<get_nb_lists(); ++i)
    {
      os << "{ " ;
      const int sz = get_list_size(i);
      for (int j=0; j<sz; ++j)
        {
          os <<  valeurs_[(index_[i]+j)] << " ";
        }
      os << "}" << finl;
    }
  return os;
}
References finl, get_list_size(), get_nb_lists(), index_, and valeurs_.
get_data()
const ArrOfInt & Static_Int_Lists::get_data () const inline
Definition at line 51 of file Static_Int_Lists.h.
  {
    return valeurs_;
  }
References valeurs_.
Referenced by creer_md_vect_renum(), MD_Vector_std::initialize_comm_template(), MD_Vector_std::MD_Vector_std(), mincol1_to_vect_items(), MD_Vector_std::prepare_send_data_template(), MD_Vector_std::printOn(), MD_Vector_std::process_recv_data_template(), vect_blocs_generic(), and vect_items_generic().
get_index()
const ArrOfInt & Static_Int_Lists::get_index () const inline
Definition at line 47 of file Static_Int_Lists.h.
  {
    return index_;
  }
References index_.
Referenced by mincol1_to_vect_items(), MD_Vector_std::printOn(), vect_blocs_generic(), and vect_items_generic().
get_list_size()
int Static_Int_Lists::get_list_size (int i_liste) const inline
renvoie le nombre d'elements de la liste i
Definition at line 99 of file Static_Int_Lists.h.
{
  const int size = index_[i+1] - index_[i];
  return size;
}
References index_.
Referenced by append_global_md(), Assembleur_P_EF::assembler_mat(), Scatter::calculer_espace_distant_elements(), DomaineCutter::construire_faces_joints_ssdom(), Domain_Graph::construire_graph_elem_elem(), construire_liste_sommets_sousdomaine(), Zone_VEF_PreP1b::construire_ok_arete(), DomaineCutter::construire_sommets_joints_ssdom(), copy_list_to_array(), Partitionneur_base::corriger_bords_avec_graphe(), Partitionneur_base::corriger_multiperiodique(), Partitionneur_base::corriger_sommets_bord(), creer_md_vect_renum(), ecrire(), MD_Vector_tools::extend(), Zone_PolyMAC_P0::fgrad(), find_adjacent_elements(), Op_Diff_PolyMAC_P0_Elem::init_som_ext(), MD_Vector_std::initialize_comm_template(), MD_Vector_std::MD_Vector_std(), parcourir_epaisseurs_elements(), and Zone_Cl_EF::remplir_type_elem_Cl().
get_nb_lists()
int Static_Int_Lists::get_nb_lists () const inline
renvoie le nombre de listes stockees
Definition at line 106 of file Static_Int_Lists.h.
{
  return index_.size_array() - 1;
}
References index_, and TRUSTArray< _TYPE_ >::size_array().
Referenced by build_frontier(), construire_liste_sommets_sousdomaine(), Partitionneur_Metis::construire_partition(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_base::corriger_bords_avec_graphe(), Faces_builder::creer_faces_reeles(), ecrire(), mincol1_to_vect_items(), parcourir_epaisseurs_elements(), Raffiner_Simplexes::refine_domain(), vect_blocs_generic(), and vect_items_generic().
operator()()
int Static_Int_Lists::operator() (int i_liste, int i_element) const inline
renvoie le j-ieme element de la i-ieme liste avec
0 <= i < get_nb_lists() et 0 <= j < get_list_size(i)
Definition at line 90 of file Static_Int_Lists.h.
{
  const int index = index_[i] + j;
  assert(index < index_[i+1]);
  const int val = valeurs_[index];
  return val;
}
References index_, and valeurs_.
printOn()
Sortie & Static_Int_Lists::printOn (Sortie & os) const
Definition at line 110 of file Static_Int_Lists.cpp.
{
  os << index_   << space;
  os << valeurs_ << space;
  return os;
}
References index_, space, and valeurs_.
readOn()
Entree & Static_Int_Lists::readOn (Entree & is)
Definition at line 117 of file Static_Int_Lists.cpp.
{
  reset();
  is >> index_;
  is >> valeurs_;
  return is;
}
References index_, reset(), and valeurs_.
reset()
void Static_Int_Lists::reset ()
detruit toutes les listes
Definition at line 19 of file Static_Int_Lists.cpp.
{
  index_.resize_array(0);
  valeurs_.resize_array(0);
}
References index_, TRUSTArray< _TYPE_ >::resize_array(), and valeurs_.
Referenced by DomaineCutter::ecrire_zones(), readOn(), DomaineCutter::reset(), and set_list_sizes().
set()
void Static_Int_Lists::set (const ArrsOfInt & src)
Definition at line 148 of file Static_Int_Lists.cpp.
{
  const int nb_lists = src.size();
  index_.resize_array(nb_lists + 1, Array_base::NOCOPY_NOINIT);
  int idx = 0;
  int i;
  index_[0] = 0;
  for (i = 0; i < nb_lists; i++)
    {
      idx += src[i].size_array();
      index_[i+1] = idx;
    }
  valeurs_.resize_array(idx, Array_base::NOCOPY_NOINIT);
  idx = 0;
  for (i = 0; i < nb_lists; i++)
    {
      const ArrOfInt& a = src[i];
      int sz = a.size_array();
      valeurs_.inject_array(a, sz, idx /* dest index */, 0 /* source index */);
      idx += sz;
    }
}
References index_, TRUSTArray< _TYPE_ >::inject_array(), Array_base::NOCOPY_NOINIT, TRUSTArray< _TYPE_ >::resize_array(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), and valeurs_.
Referenced by MD_Vector_std::MD_Vector_std().
set_data()
void Static_Int_Lists::set_data (const ArrOfInt & data)
remplace les valeurs stockes par toutes les listes par celles
du tableau data. data doit avoir pour taille la somme des tailles de toutes
les listes.
Definition at line 50 of file Static_Int_Lists.cpp.
{
  assert(data.size_array() == valeurs_.size_array());
  valeurs_.inject_array(data);
}
References TRUSTArray< _TYPE_ >::inject_array(), TRUSTArray< _TYPE_ >::size_array(), and valeurs_.
Referenced by append_global_md().
set_index_data()
void Static_Int_Lists::set_index_data (const ArrOfInt & index, const ArrOfInt & data)
remplace index et data.
Definition at line 75 of file Static_Int_Lists.cpp.
{
  assert(check_index_data(index, data));
  index_ = index;
  valeurs_ = data;
}
References check_index_data(), index_, and valeurs_.
Referenced by creer_md_vect_renum(), and MD_Vector_std::readOn().
set_list_sizes()
void Static_Int_Lists::set_list_sizes (const ArrOfInt & sizes)
detruit les listes existantes et en cree de nouvelles.
On cree autant de listes que d'elements dans le tableau sizes.
La i-ieme liste a une taille sizes[i]
Les valeurs sizes doivent etre positives ou nulles.
Definition at line 29 of file Static_Int_Lists.cpp.
{
  reset();
  const int nb_listes = sizes.size_array();
  index_.resize_array(nb_listes + 1);
// Construction du tableau d'index
  index_[0];
  int i;
  for (i = 0; i < nb_listes; i++)
    {
      assert(sizes[i] >= 0);
      index_[i+1] = index_[i] + sizes[i];
    }
  const int somme_sizes = index_[nb_listes];
  valeurs_.resize_array(somme_sizes);
}
References index_, reset(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::size_array(), and valeurs_.
Referenced by append_global_md(), Refine_Mesh::build_incidence_from_node_to_edges(), calculer_elements_voisins_bords(), Scatter::calculer_espace_distant_elements(), Partitionneur_base::calculer_graphe_connexions_periodiques(), calculer_listes_elements_sous_domaines(), construire_connectivite_real_som_virtual_elem(), construire_connectivite_som_elem(), construit_connectivite_sommet(), and Decouper_multi::interpreter().
set_value()
void Static_Int_Lists::set_value (int i_liste, int i_element, int valeur) inline
affecte la "valeur" au j-ieme element de la i-ieme liste avec
0 <= i < get_nb_lists() et 0 <= j < get_list_size(i)
Definition at line 81 of file Static_Int_Lists.h.
{
  const int index = index_[i] + j;
  assert(index < index_[i+1]);
  valeurs_[index] = valeur;
}
References index_, valeur(), and valeurs_.
Referenced by Refine_Mesh::build_incidence_from_node_to_edges(), calculer_elements_voisins_bords(), Scatter::calculer_espace_distant_elements(), Partitionneur_base::calculer_graphe_connexions_periodiques(), calculer_listes_elements_sous_domaines(), construire_connectivite_real_som_virtual_elem(), construire_connectivite_som_elem(), construit_connectivite_sommet(), and Decouper_multi::interpreter().
trier_liste()
void Static_Int_Lists::trier_liste (int i)
tri par ordre croissant des valeurs de la i-ieme liste.
Si num_liste < 0, on trie toutes les listes.
Definition at line 84 of file Static_Int_Lists.cpp.
{
  const int i_debut = (num_liste < 0) ? 0 : num_liste;
  const int i_fin   = (num_liste < 0) ? index_.size_array() - 1 : num_liste + 1;
  int i;
  ArrOfInt valeurs_liste;
  for (i = i_debut; i < i_fin; i++)
    {
      const int index = index_[i];
      const int size  = index_[i+1] - index;
      valeurs_liste.ref_array(valeurs_, index, size);
      valeurs_liste.ordonne_array();
    }
}
References index_, TRUSTArray< _TYPE_ >::ordonne_array(), TRUSTArray< _TYPE_ >::ref_array(), TRUSTArray< _TYPE_ >::size_array(), and valeurs_.
Referenced by Refine_Mesh::build_incidence_from_node_to_edges(), construire_connectivite_real_som_virtual_elem(), and construire_connectivite_som_elem().
Member Data Documentation
index_
ArrOfInt Static_Int_Lists::index_ private
Definition at line 75 of file Static_Int_Lists.h.
Referenced by copy_list_to_array(), ecrire(), get_index(), get_list_size(), get_nb_lists(), operator()(), printOn(), readOn(), reset(), set(), set_index_data(), set_list_sizes(), set_value(), and trier_liste().
valeurs_
ArrOfInt Static_Int_Lists::valeurs_ private
Definition at line 76 of file Static_Int_Lists.h.
Referenced by copy_list_to_array(), ecrire(), get_data(), operator()(), printOn(), readOn(), reset(), set(), set_data(), set_index_data(), set_list_sizes(), set_value(), and trier_liste().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Static_Int_Lists.h
src/Kernel/Utilitaires/Static_Int_Lists.cpp