TRUST: Champ_Ostwald_VEF Class Reference
Champ_Ostwald_VEF Class Reference
classe Champ_Ostwald_VEF
Represente un champ en discretisation VEF qui varie en fonction
de la consistance et de l'indice de structure.
Champ utilise pour le fluide d'Ostwald et la discretisation VEF.
Fait reference a zone_VEF pou utiliser la bonne zone avec zone_dis_base
Champ_P1NC pour calculer D:D
Navier_Stokes_std pour avoir l'equation thermo_hydraulique
et pouvoir utiliser une de ses inconnues: la vitesse.
#include <Champ_Ostwald_VEF.h>
Public Member Functions
Champ_Ostwald_VEF ()
~Champ_Ostwald_VEF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Champ_P1NC & mon_champs () const
void associer_champ (const Champ_P1NC &)
void associer_zone_dis_base (const Zone_dis_base &la_zone_dis_base)
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
void associer_eqn (const Navier_Stokes_std &)
const Zone_dis_base & zone_dis_base () const
void mettre_a_jour (double temps)
met le parametre mu a jour
void me_calculer (double tps)
Calcul le champ Ostwald :
calcul de D::D
puis calcul de mu.
int initialiser (const double &temps)
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
void init_mu (DoubleTab &)
Initialise le champs.
void calculer_dscald (DoubleTab &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Ostwald_VEF & self_cast (Objet_U &)
static const Champ_Ostwald_VEF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
Ne sert a rien
Format:
void calculer_mu (DoubleTab &)
Calcul la viscosite mu en fonction de la consistance et de
l'indice de structure en utilisant la loi d'Ostwald. Pour
des viscsites tres faible et tres fortes on utilise une regression.
Protected Attributes
Ref_Champ_P1NC mon_champ_
pour calculer D::D
Ref_Zone_VEF la_zone_VEF
Ref_Navier_Stokes_std eq_hydraulique
Detailed Description
classe Champ_Ostwald_VEF
Represente un champ en discretisation VEF qui varie en fonction
de la consistance et de l'indice de structure.
Champ utilise pour le fluide d'Ostwald et la discretisation VEF.
Fait reference a zone_VEF pou utiliser la bonne zone avec zone_dis_base
Champ_P1NC pour calculer D:D
Navier_Stokes_std pour avoir l'equation thermo_hydraulique
et pouvoir utiliser une de ses inconnues: la vitesse.
Definition at line 51 of file Champ_Ostwald_VEF.h.
Constructor & Destructor Documentation
Champ_Ostwald_VEF::Champ_Ostwald_VEF ()
Definition at line 30 of file Champ_Ostwald_VEF.cpp.
Champ_Ostwald_VEF::~Champ_Ostwald_VEF ()
Definition at line 30 of file Champ_Ostwald_VEF.cpp.
Member Function Documentation
void Champ_Ostwald_VEF::associer_champ (const Champ_P1NC & un_champ) [inline]
Definition at line 89 of file Champ_Ostwald_VEF.h.
References mon_champ_.
Referenced by VEF_discretisation::proprietes_physiques_fluide_Ostwald().
{
  mon_champ_ = un_champ;
}
void Champ_Ostwald_VEF::associer_eqn (const Navier_Stokes_std & eq)
Definition at line 145 of file Champ_Ostwald_VEF.cpp.
References Cerr, eq_hydraulique, finl, and ref_cast.
Referenced by VEF_discretisation::proprietes_physiques_fluide_Ostwald().
{
  Cerr<<"on associe pour mu le pb a une equation de Navier_Stockes_std"<<finl;
  eq_hydraulique = ref_cast(Navier_Stokes_std,eq);
}
void Champ_Ostwald_VEF::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) [inline, virtual]
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
Reimplemented from Champ_Ostwald.
Definition at line 95 of file Champ_Ostwald_VEF.h.
References Cerr, finl, and la_zone_VEF.
Referenced by VEF_discretisation::proprietes_physiques_fluide_Ostwald().
{
  Cerr<<"on est dans  Champ_Ostwald_VEF::associer_zone_dis_base "<<finl;
  la_zone_VEF = (const Zone_VEF&) la_zone_dis_base;
}
void Champ_Ostwald_VEF::calculer_dscald (DoubleTab & dscald)
Definition at line 151 of file Champ_Ostwald_VEF.cpp.
References Champ_P1NC::calcul_gradient(), Objet_U::dimension, eq_hydraulique, la_zone_VEF, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), ref_cast, Ref_Navier_Stokes_std::valeur(), and Ref_Zone_VEF::valeur().
Referenced by me_calculer().
{
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const Zone_Cl_VEF& zcl_VEF = ref_cast(Zone_Cl_VEF,eq_hydraulique->zone_Cl_dis().valeur());
  const DoubleTab& vit = eq_hydraulique->inconnue().valeurs();
  int nb_elem = zone_VEF.nb_elem();
  int nb_elem_tot = zone_VEF.nb_elem_tot();
  int elem;
  DoubleTab gradient_elem(nb_elem_tot,dimension,dimension);
  Champ_P1NC::calcul_gradient(vit,gradient_elem,zcl_VEF);
  if (dimension == 2)
    for (elem=0; elem<nb_elem; elem++)
      {
        dscald(elem) = 4. * (gradient_elem(elem, 0, 0) * gradient_elem(elem, 0, 0) +
                             gradient_elem(elem, 1, 1) * gradient_elem(elem, 1, 1)) +
                       2. * ((gradient_elem(elem, 0, 1) + gradient_elem(elem, 1, 0)) *
                             (gradient_elem(elem, 0, 1) + gradient_elem(elem, 1, 0))) ;
      }
  else if (dimension == 3)
    for (elem=0; elem<nb_elem; elem++)
      {
        dscald(elem) = 4. * (gradient_elem(elem, 0, 0) * gradient_elem(elem, 0, 0) +
                             gradient_elem(elem, 1, 1) * gradient_elem(elem, 1, 1) +
                             gradient_elem(elem, 2, 2) * gradient_elem(elem, 2, 2)) +
                       2. *(((gradient_elem(elem, 0, 1) + gradient_elem(elem, 1, 0)) *
                             (gradient_elem(elem, 0, 1) + gradient_elem(elem, 1, 0))) +
                            ((gradient_elem(elem, 2, 0) + gradient_elem(elem, 0, 2)) *
                             (gradient_elem(elem, 2, 0) + gradient_elem(elem, 0, 2))) +
                            ((gradient_elem(elem, 2, 1) + gradient_elem(elem, 1, 2)) *
                             (gradient_elem(elem, 2, 1) + gradient_elem(elem, 1, 2)))) ;
      }
}
void Champ_Ostwald_VEF::calculer_mu (DoubleTab & mu_tab) [protected]
Calcul la viscosite mu en fonction de la consistance et de
l'indice de structure en utilisant la loi d'Ostwald. Pour
des viscsites tres faible et tres fortes on utilise une regression.
< K varie en fonction de la temperature
Definition at line 116 of file Champ_Ostwald_VEF.cpp.
References Champ_Ostwald::mon_fluide_, Champ_Don_base::nb_valeurs_nodales(), sub_type, and Ref_Fluide_Ostwald::valeur().
Referenced by me_calculer().
{
  const double d_n = mon_fluide_->indice_struct().valeurs()(0,0);
  for (int i=0 ; i<nb_valeurs_nodales() ; i++)
    {
      if (sub_type(Champ_Uniforme, mon_fluide_->consistance().valeur()))
        {
          const double d_k = mon_fluide_->consistance().valeurs()(0,0);
          if ( mu_tab[i] < 1.E-4 )
            mu_tab[i] = d_k * pow( 0.5 * 1.E-4 , (d_n - 1.) / 2.);
          else if ( mu_tab[i] > 1.E16 )
            mu_tab[i] = d_k * pow( 0.5 * 1.E16 , (d_n - 1.) / 2.);
          else
            mu_tab[i] = d_k * pow( 0.5 * mu_tab[i] , (d_n - 1.) / 2.);
        }
      else  //!< K varie en fonction de la temperature
        {
          const DoubleTab& K_tab = mon_fluide_->consistance().valeurs();
          if ( mu_tab[i] < 1.E-4 )
            mu_tab[i] = K_tab[i] * pow( 0.5 * 1.E-4 , (d_n - 1.) / 2.);
          else if ( mu_tab[i] > 1.E16 )
            mu_tab[i] = K_tab[i] * pow( 0.5 * 1.E16 , (d_n - 1.) / 2.);
          else
            mu_tab[i] = K_tab[i] * pow( 0.5 * mu_tab[i] , (d_n - 1.) / 2.);
        }
    }
}
Objet_U * Champ_Ostwald_VEF::cree_instance () [static]
Reimplemented from Champ_Ostwald.
Definition at line 30 of file Champ_Ostwald_VEF.cpp.
int Champ_Ostwald_VEF::duplique () const [virtual]
Reimplemented from Champ_Ostwald.
Definition at line 30 of file Champ_Ostwald_VEF.cpp.
const Type_info * Champ_Ostwald_VEF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Ostwald.
Definition at line 30 of file Champ_Ostwald_VEF.cpp.
const Type_info * Champ_Ostwald_VEF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Ostwald.
Definition at line 30 of file Champ_Ostwald_VEF.cpp.
void Champ_Ostwald_VEF::init_mu (DoubleTab & mu_tab)
Initialise le champs.
Definition at line 231 of file Champ_Ostwald_VEF.cpp.
References Champ_Ostwald::mon_fluide_, and Champ_Don_base::nb_valeurs_nodales().
{
  const DoubleTab& K_tab = mon_fluide_->consistance().valeurs();
  for (int i=0 ; i<nb_valeurs_nodales() ; i++)
    mu_tab[i] = K_tab[i];
}
int Champ_Ostwald_VEF::initialiser (const double & temps) [virtual]
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
Reimplemented from Champ_Ostwald.
Definition at line 238 of file Champ_Ostwald_VEF.cpp.
References mettre_a_jour().
{
  mettre_a_jour(un_temps);
  return 1;
}
void Champ_Ostwald_VEF::me_calculer (double tps) [virtual]
Calcul le champ Ostwald :
calcul de D::D
puis calcul de mu.
Reimplemented from Champ_Ostwald.
Definition at line 205 of file Champ_Ostwald_VEF.cpp.
References calculer_dscald(), calculer_mu(), Champ_base::temps_, and Champ_Don_base::valeurs().
Referenced by mettre_a_jour().
{
  if (temps_ != tps)
    {
// Cerr<< "Calcul de Mu Ostwald"<<finl;
      calculer_dscald(valeurs());
      calculer_mu(valeurs());
    }
}
void Champ_Ostwald_VEF::mettre_a_jour (double temps) [virtual]
met le parametre mu a jour
Reimplemented from Champ_Ostwald.
Definition at line 90 of file Champ_Ostwald_VEF.cpp.
References Champ_base::changer_temps(), and me_calculer().
Referenced by initialiser().
{
  me_calculer(tps);
  changer_temps(tps);
  Champ_Don_base::mettre_a_jour(tps);
}
const Champ_P1NC & Champ_Ostwald_VEF::mon_champs () const [inline]
Definition at line 84 of file Champ_Ostwald_VEF.h.
{
  return mon_champ_.valeur();
}
Sortie & Champ_Ostwald_VEF::printOn (Sortie & os) const [protected, virtual]
Imprime le champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Ostwald.
Definition at line 47 of file Champ_Ostwald_VEF.cpp.
References Champ_Don_base::valeurs().
{
// const int nb_compo = valeurs()(0,0);
  os << valeurs()(0,0);
  return os;
}
Entree & Champ_Ostwald_VEF::readOn (Entree & is) [protected, virtual]
Ne sert a rien
Format:
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Ostwald.
Definition at line 71 of file Champ_Ostwald_VEF.cpp.
{
  return is;
}
const Champ_Ostwald_VEF & Champ_Ostwald_VEF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Ostwald.
Definition at line 30 of file Champ_Ostwald_VEF.cpp.
Champ_Ostwald_VEF & Champ_Ostwald_VEF::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Ostwald.
Definition at line 30 of file Champ_Ostwald_VEF.cpp.
unsigned Champ_Ostwald_VEF::taille_memoire () const [virtual]
Reimplemented from Champ_Ostwald.
Definition at line 30 of file Champ_Ostwald_VEF.cpp.
const Zone_dis_base & Champ_Ostwald_VEF::zone_dis_base () const [virtual]
Reimplemented from Champ_Ostwald.
Definition at line 245 of file Champ_Ostwald_VEF.cpp.
References la_zone_VEF, and Ref_Zone_VEF::valeur().
{
  return la_zone_VEF.valeur();
}
Member Data Documentation
Ref_Navier_Stokes_std Champ_Ostwald_VEF::eq_hydraulique [protected]
Definition at line 77 of file Champ_Ostwald_VEF.h.
Referenced by associer_eqn(), and calculer_dscald().
const Type_info Champ_Ostwald_VEF::info_obj [static]
Reimplemented from Champ_Ostwald.
Definition at line 54 of file Champ_Ostwald_VEF.h.
Ref_Zone_VEF Champ_Ostwald_VEF::la_zone_VEF [protected]
Definition at line 76 of file Champ_Ostwald_VEF.h.
Referenced by associer_zone_dis_base(), calculer_dscald(), and zone_dis_base().
Ref_Champ_P1NC Champ_Ostwald_VEF::mon_champ_ [protected]
pour calculer D::D
Definition at line 75 of file Champ_Ostwald_VEF.h.
Referenced by associer_champ().
The documentation for this class was generated from the following files:
src/VEF/Champs/Champ_Ostwald_VEF.h
src/VEF/Champs/Champ_Ostwald_VEF.cpp