TRUST: Simple Class Reference
Simple Class Reference
#include <Simple.h>
Public Member Functions
~Simple ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Simple ()
bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok) override
void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok) override
bool iterer_eqs (List_Ref_Equation_base eqs, int compteur, int &ok) override
Public Member Functions inherited from Simpler_Base
~Simpler_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int max_iter_implicite ()
int max_iter_implicite () const
bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok) override=0
virtual void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok)=0
void assembler_matrice_pression_implicite (Equation_base &eqn_NS, const Matrice_Morse &matrice, Matrice &matrice_en_pression_2)
Parametre_equation & get_and_set_parametre_equation (Equation_base &) override
retourne le parametre_implicte de l'equation si il existe si il n'existe pas le cree...
si les params sont vides on copie ceux du simpler
Parametre_implicite & get_and_set_parametre_implicite (Equation_base &eqn)
Public Member Functions inherited from Solveur_non_lineaire
Solveur_non_lineaire ()
~Solveur_non_lineaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Solveur_Implicite_Base
Solveur_Implicite_Base ()
~Solveur_Implicite_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok)=0
virtual bool iterer_eqs (List_Ref_Equation_base eqs, int n, int &ok)
virtual bool est_compatible_avec_th_mono () const
virtual int nb_valeurs_temporelles_pression () const
virtual double get_default_facsec_max () const
virtual double get_default_growth_factor () const
virtual Parametre_equation & get_and_set_parametre_equation (Equation_base &eqn)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Simple & self_cast (Objet_U &)
static const Simple & self_cast (const Objet_U &)
Static Public Member Functions inherited from Simpler_Base
static const Type_info * info ()
static Simpler_Base & self_cast (Objet_U &)
static const Simpler_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_non_lineaire
static const Type_info * info ()
static Solveur_non_lineaire & self_cast (Objet_U &)
static const Solveur_non_lineaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_Implicite_Base
static const Type_info * info ()
static Solveur_Implicite_Base & self_cast (Objet_U &)
static const Solveur_Implicite_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Simpler_Base
static const Type_info info_obj
Static Public Attributes inherited from Solveur_non_lineaire
static const Type_info info_obj
Static Public Attributes inherited from Solveur_Implicite_Base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Entree & lire (const Motcle &, Entree &) override
void calculer_correction_en_vitesse (const DoubleTrav &correction_en_pression, DoubleTrav &gradP, DoubleTrav &correction_en_vitesse, const Matrice_Morse &matrice, const Operateur_Grad &gradient)
Protected Member Functions inherited from Simpler_Base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual Entree & lire (const Motcle &, Entree &)=0
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
DoubleTab Ustar_old
double alpha_
double beta_
int with_d_rho_dt_
std::map< std::vector< intptr_t >, Matrice_Bloc > mbloc
Protected Attributes inherited from Simpler_Base
Parametre_implicite param_defaut_
int is_seuil_convg_variable
double facteur_convg_
int no_qdm_
int controle_residu_
Detailed Description
Definition at line 62 of file Simple.h.
Constructor & Destructor Documentation
~Simple()
Simple::~Simple ()
Definition at line 37 of file Simple.cpp.
Simple()
Simple::Simple ()
Definition at line 39 of file Simple.cpp.
{
  alpha_ = 1.;
  beta_ = 1.;
  with_d_rho_dt_ = 1;
  Ustar_old.resize(0);
}
References alpha_, beta_, TRUSTTab< _TYPE_ >::resize(), Ustar_old, and with_d_rho_dt_.
Member Function Documentation
calculer_correction_en_vitesse()
void Simple::calculer_correction_en_vitesse (const DoubleTrav & correction_en_pression, DoubleTrav & gradP, DoubleTrav & correction_en_vitesse, const Matrice_Morse & matrice, const Operateur_Grad & gradient) protected
Definition at line 508 of file Simple.cpp.
{
  int deux_entrees = 0;
  if (correction_en_vitesse.nb_dim()==2) deux_entrees = 1;
  gradient.valeur().multvect(correction_en_pression,gradP);
  int nb_comp = 1;
  if(deux_entrees)
    nb_comp = correction_en_vitesse.dimension(1);
  int nb_ligne_reel = correction_en_vitesse.dimension(0);
  if ((Process::nproc()==1)&& (nb_ligne_reel!=matrice.ordre()/nb_comp)) abort();
  if (deux_entrees==0)
    {
// D(Uk-1)^-1 resu
      int i,j;
      for(i=0; i<nb_ligne_reel; i++)
        for (j=0; j<nb_comp; j++)
          {
// k=tab1(i*nb_comp+j)-1;
            correction_en_vitesse(i) = -gradP(i)/matrice(i*nb_comp+j,i*nb_comp+j);
          }
    }
  else
    {
      int i,j;
      for(i=0; i<nb_ligne_reel; i++)
        for (j=0; j<nb_comp; j++)
          {
// k = tab1(i*nb_comp+j)-1;
            correction_en_vitesse(i,j) = -gradP(i,j)/matrice(i*nb_comp+j,i*nb_comp+j);
          }
    }
  correction_en_vitesse.echange_espace_virtuel();
}
References Process::abort(), TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Operateur_Grad_base::multvect(), TRUSTTab< _TYPE_ >::nb_dim(), Process::nproc(), Matrice_Morse::ordre(), and Deriv_Operateur_Grad_base::valeur().
Referenced by Piso::iterer_NS(), iterer_NS(), and Simpler::iterer_NS().
cree_instance()
Objet_U * Simple::cree_instance () static
Definition at line 37 of file Simple.cpp.
duplique()
int Simple::duplique () const override virtual
Implements Objet_U.
Reimplemented in Simpler, and Solveur_U_P.
Definition at line 37 of file Simple.cpp.
get_info()
const Type_info * Simple::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_non_lineaire.
Reimplemented in Simpler, and Solveur_U_P.
Definition at line 37 of file Simple.cpp.
info()
const Type_info * Simple::info () static
Definition at line 37 of file Simple.cpp.
iterer_eqn()
bool Simple::iterer_eqn (Equation_base & equation, const DoubleTab & inconnue, DoubleTab & result, double dt, int numero_iteration, int & ok) override virtual
< pour pouvoir tester la convergence.
Implements Simpler_Base.
Definition at line 170 of file Simple.cpp.
{
  DoubleTab dudt(current);
  Parametre_implicite& param = get_and_set_parametre_implicite(eqn);
  int converge=0;
  int nb_pas_dt = eqn.schema_temps().nb_pas_dt();
  double temps = eqn.schema_temps().temps_courant();
  int freq = param.equation_frequence_resolue(temps);
  if (freq!=0 && (nb_pas_dt%freq)!=0)
    {
      Cout<<"Time step : "<<nb_pas_dt<<" - "<<eqn.que_suis_je()<<" equation is not solved."<<finl;
      eqn.valider_iteration();
      return true;
    }
  if (eqn.equation_non_resolue())
    {
      Cout<<eqn.que_suis_je()<<" equation is not solved."<<finl;
// on calcule une fois la derivee pour avoir les flux bord
      if  (eqn.schema_temps().nb_pas_dt()==0)
        {
          DoubleTab toto(eqn.inconnue().valeurs());
          eqn.derivee_en_temps_inco(toto);
        }
      eqn.valider_iteration();
      converge = 1;
      return true;
    }
  if (param.calcul_explicite())
    {
      if (param.seuil_diffusion_implicite()<0)
        iterer_eqn_expl(eqn,nb_iter,dt,current,dudt,converge,no_qdm_);
      else
        iterer_eqn_expl_diffusion_implicite(eqn,nb_iter,dt,current,dudt,converge,no_qdm_,param.seuil_diffusion_implicite());
      return (converge==1);
    }
  double& seuil_convergence_implicite = param.seuil_convergence_implicite();
  double seuil_verification_solveur = param.seuil_verification_solveur();
  double seuil_test_preliminaire_solveur = param.seuil_test_preliminaire_solveur();
  assert(seuil_verification_solveur>0);
  SolveurSys& solveur = param.solveur();
  double seuil_convg = seuil_convergence_implicite;
  if (is_seuil_convg_variable)
    {
      double residu = ref_cast(Schema_Euler_Implicite,eqn.schema_temps()).residu_old();
      if ((residu*dt*10<seuil_convg)&&(nb_iter==1))
        {
          seuil_convergence_implicite /= 1.1;
          seuil_convg = seuil_convergence_implicite;
        }
      Cout<<"seuil_convg "<<seuil_convg<<finl;
    }
  converge = 0;
  if ((no_qdm_) && (sub_type(Navier_Stokes_std,eqn)))
    {
      Matrice& matrice_en_pression_2 = ref_cast(Navier_Stokes_std, eqn).matrice_pression();
      if (!matrice_en_pression_2.non_nul()) matrice_en_pression_2.detach();
      converge = 1;
      return true;
    }
//
// Resolution implicite -par iterer_NS pour Navier_Stokes
// -...solveur.resoudre_systeme()... pour les autres equations
//
  dudt = current; //!< pour pouvoir tester la convergence.
  Matrice_Morse matrice;
  if (!(sub_type(Navier_Stokes_std,eqn) && sub_type(SETS, *this))) //SETS et ICE gerent eux-memes leurs matrices
    {
      eqn.dimensionner_matrice(matrice);
      matrice.get_set_coeff() = 0;
    }
  DoubleTrav resu(current);
  if( sub_type(Navier_Stokes_std,eqn))
    {
      Navier_Stokes_std& eqnNS = ref_cast(Navier_Stokes_std,eqn);
      DoubleTab& pression = eqnNS.pression().valeurs();
      DoubleTrav secmem(pression);
      pression.echange_espace_virtuel();
      iterer_NS(eqnNS,current,pression,dt,matrice,seuil_verification_solveur,secmem,nb_iter,converge, ok);
    }
  else
    {
      solveur.valeur().reinit();
      DoubleTrav resu_temp(current); /* residu en increments */
      if (eqn.has_interface_blocs()) /* si assembler_blocs est disponible */
        {
          if (eqn.discretisation().que_suis_je().debute_par("PolyMAC"))
            {
              eqn.assembler_blocs_avec_inertie({{ eqn.inconnue().le_nom().getString(), &matrice }}, resu_temp, { });
              resu = resu_temp;
              matrice.ajouter_multvect(current, resu);
            }
          else
            {
              eqn.assembler_blocs_avec_inertie({{ eqn.inconnue().le_nom().getString(), &matrice }}, resu, { });
              resu_temp = 0;
              matrice.ajouter_multvect(current,resu_temp);
              resu_temp -= resu;
            }
        }
      else
        {
          eqn.assembler_avec_inertie(matrice,current,resu);
          resu_temp = 0;
          matrice.ajouter_multvect(current,resu_temp);
          resu_temp -= resu;
        }
      if (seuil_test_preliminaire_solveur>0)
        {
          double norme_b=mp_norme_vect(resu_temp);
          if (norme_b<seuil_test_preliminaire_solveur)
            {
// GF le test suivant est peut etre intelligent ?
// if (nb_iter>1)
              {
                converge = 1;
                Cout<<"Resolution of system is not necessary: "<< norme_b <<" < "<< seuil_test_preliminaire_solveur <<finl;
              }
            }
        }
      if (converge==0)
        {
          int con = 0;
          while (con==0)
            {
              con = 1;
              solveur.resoudre_systeme(matrice,resu,current);
              ok = eqn.milieu().check_unknown_range(); //verification que l'inconnue est dans les bornes du milieu
              if (ok)
                {
                  resu_temp = 0;
                  matrice.ajouter_multvect(current,resu_temp);
                  resu_temp -= resu;
                  double norme_resu = mp_norme_vect(resu_temp) ;
                  if (norme_resu>seuil_verification_solveur) con = 0;
                  if (con==0)
                    {
                      Cout<<"Residu of iterative solving : "<<norme_resu<<" instead of "<<seuil_verification_solveur<<finl;
                      Cout<<"Iterating on the linear system again:"<< finl;
                      seuil_verification_solveur *= 2;
                      con = 0;
                    }
                }
              else current = eqn.inconnue().passe(); //si ok == 0, on restaure la valeur passee de inco
            }
          converge = 0;
        }
    }
//
// Test de convergence de la solution entre deux iterations successives
// Pas applique pour l inconnue de N_S avec alorithme PISO et Implicite
//
  if(!converge && ok)
    {
// permet de controler ce qui se passe
// en particulier la positivite de K et de eps
      eqn.valider_iteration();
      dudt -= current;
      double dudt_norme = mp_norme_vect(dudt);
      converge = (dudt_norme < seuil_convg);
      if (!converge)
        {
          Cout<<eqn.que_suis_je()<<" is not converged at the implicit iteration "<<nb_iter<<" ( ||uk-uk-1|| = "<<dudt_norme<<" > implicit threshold "<<seuil_convg<<" )"<<finl;
          if (nb_iter>=10) Cout << "Consider lowering facsec_max value. Look at the reference manual for advice to set facsec_max value according to the problem type." << finl;
        }
      else
        Cout<<eqn.que_suis_je()<<" is converged at the implicit iteration "<<nb_iter<<" ( ||uk-uk-1|| = "<<dudt_norme<<" < implicit threshold "<<seuil_convg<<" )"<<finl;
    }
  if(ok && eqn.discretisation().que_suis_je().debute_par("PolyMAC")) eqn.probleme().mettre_a_jour(eqn.schema_temps().temps_courant());
  solveur->reinit();
  return (ok && converge==1);
}
References Matrice_Base::ajouter_multvect(), Equation_base::assembler_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Parametre_implicite::calcul_explicite(), Milieu_base::check_unknown_range(), Cout, Nom::debute_par(), Equation_base::derivee_en_temps_inco(), Deriv_::detach(), Equation_base::dimensionner_matrice(), Equation_base::discretisation(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Parametre_implicite::equation_frequence_resolue(), Equation_base::equation_non_resolue(), finl, Simpler_Base::get_and_set_parametre_implicite(), Matrice_Morse::get_set_coeff(), Equation_base::has_interface_blocs(), Equation_base::inconnue(), Simpler_Base::is_seuil_convg_variable, iterer_eqn_expl(), iterer_eqn_expl_diffusion_implicite(), iterer_NS(), Objet_U::le_nom(), Probleme_base::mettre_a_jour(), Equation_base::milieu(), mp_norme_vect(), Schema_Temps_base::nb_pas_dt(), Simpler_Base::no_qdm_, O_U_Ptr::non_nul(), Champ_Inc::passe(), Navier_Stokes_std::pression(), Equation_base::probleme(), Objet_U::que_suis_je(), ref_cast, SolveurSys_base::reinit(), SolveurSys::resoudre_systeme(), Equation_base::schema_temps(), Parametre_implicite::seuil_convergence_implicite(), Parametre_implicite::seuil_diffusion_implicite(), Parametre_implicite::seuil_test_preliminaire_solveur(), Parametre_implicite::seuil_verification_solveur(), Parametre_implicite::solveur(), sub_type, Schema_Temps_base::temps_courant(), Deriv_SolveurSys_base::valeur(), Champ_Inc::valeurs(), and Equation_base::valider_iteration().
iterer_eqs()
bool Simple::iterer_eqs (List_Ref_Equation_base eqs, int compteur, int & ok) override virtual
Reimplemented from Solveur_Implicite_Base.
Definition at line 363 of file Simple.cpp.
{
// on recupere le solveur de systeme lineaire
  Parametre_implicite& param = get_and_set_parametre_implicite(eqs[0]);
  SolveurSys& solveur = param.solveur();
  double seuil_convg = param.seuil_convergence_implicite();
  int i, j, bs = 0; //bs : linesize commune des tableaux si > 0, 0 sinon
  /* cle pour la memoization */
  std::vector<intptr_t> key(eqs.size());
  for (i = 0; i < eqs.size(); i++) key[i] = (intptr_t) &eqs[i].valeur();
  int init = !mbloc.count(key); //premier passage
  Matrice_Bloc& Mglob = mbloc[key];
  if (init)
    for (Mglob.dimensionner(eqs.size(), eqs.size()), i = 0; i < eqs.size(); i++)
      for (j = 0; j < eqs.size(); j++) Mglob.get_bloc(i, j).typer("Matrice_Morse");
  /* pour interface_blocs : si toutes les equations ont cette interface, on l'utilise */
  int interface_blocs_ok = 1;
  for (i = 0; i < eqs.size(); i++) interface_blocs_ok &= eqs[i]->has_interface_blocs();
  std::vector<matrices_t> mats(eqs.size()); //ligne de matrices de l'equation i
  for (i = 0; i < eqs.size(); i++)
    for (j = 0; j < eqs.size(); j++)
      {
        Nom nom_i = eqs[j]->inconnue().le_nom();
// champ d'un autre probleme : on ajoute un suffixe
        if (eqs[i]->probleme().le_nom().getString() != eqs[j]->probleme().le_nom().getString()) nom_i += Nom("/") + eqs[j]->probleme().le_nom();
        mats[i][nom_i.getString()] = &ref_cast(Matrice_Morse, Mglob.get_bloc(i, j).valeur());
      }
// Les inconues/residus ont-ils la meme forme?
  for (bs = eqs[0]->inconnue().valeurs().line_size(), i = 1; i < eqs.size(); i++)
    if (eqs[i]->inconnue().valeurs().line_size() != bs) bs = 0;
// MD_Vector global
  MD_Vector_composite mdc; //version composite
  for (i = 0; i < eqs.size(); i++)
    mdc.add_part(eqs[i]->inconnue().valeurs().get_md_vector(), bs ? 0 : eqs[i]->inconnue().valeurs().line_size());
  MD_Vector mdv;
  mdv.copy(mdc);
  if (init) //1er passage -> dimensionnement des MD_Vector et des matrices
    {
      /* dimensionnement de la matrice globale */
      if (interface_blocs_ok)
        for (i = 0; i < eqs.size(); i++) eqs[i]->dimensionner_blocs(mats[i], {});
      else for (i = 0; i < eqs.size(); i++)
          for (j = 0; j < eqs.size(); j++)
            {
              Matrice_Morse& mat = ref_cast(Matrice_Morse, Mglob.get_bloc(i, j).valeur()), mat2;
              int nl = eqs[i]->inconnue().valeurs().size_totale(), nc = eqs[j]->inconnue().valeurs().size_totale();
              if (i == j) eqs[i]->dimensionner_matrice(mat);
              eqs[i]->dimensionner_termes_croises(i == j ? mat2 : mat, eqs[j]->probleme(), nl, nc);
              if (i == j) mat += mat2;
            }
    }
  else for (i = 0; i < eqs.size(); i++)
      for (j = 0; j < eqs.size(); j++) //passages suivantes -> il suffit de reallouer les tableaux coeff()
        {
          Matrice_Morse& mat = ref_cast(Matrice_Morse, Mglob.get_bloc(i, j).valeur());
          mat.get_set_coeff().resize(mat.get_set_tab2().size());
        }
// tableaux de travail
  DoubleTrav inconnues, residus, dudt;
  if (bs) inconnues.resize(0, bs), residus.resize(0, bs), dudt.resize(0, bs); //pour que les tableaux aggreges aient la bonne line_size() si elle existe
  MD_Vector_tools::creer_tableau_distribue(mdv, inconnues);
  MD_Vector_tools::creer_tableau_distribue(mdv, residus);
  MD_Vector_tools::creer_tableau_distribue(mdv, dudt);
  DoubleTab_parts residu_parts(residus), inconnues_parts(inconnues), dudt_parts(dudt);
// remplissage des inconnues
  for(i = 0; i < eqs.size(); i++) inconnues_parts[i] = eqs[i]->inconnue().valeurs();
  dudt = inconnues;
// remplissage des matrices
  if (interface_blocs_ok)
    {
      for (i = 0; i < eqs.size(); i++)
        {
          eqs[i]->assembler_blocs_avec_inertie(mats[i], residu_parts[i], {});
          if (!eqs[i]->discretisation().que_suis_je().debute_par("PolyMAC"))
            {
              for (j = 0; j < eqs.size(); j++)
                {
                  Nom nom_j = eqs[j]->inconnue().le_nom();
                  if (eqs[i]->probleme().le_nom().getString() != eqs[j]->probleme().le_nom().getString())
                    {
                      nom_j += Nom("/") + eqs[j]->probleme().le_nom();
                      mats[i][nom_j.getString()]->ajouter_multvect(inconnues_parts[j], residu_parts[i]);
                    }
                }
            }
        }
      if (eqs[0]->discretisation().que_suis_je().debute_par("PolyMAC")) Mglob.ajouter_multvect(inconnues, residus); //pour ne pas resoudre en increments
    }
  else for(i = 0; i < eqs.size(); i++)
      for (j = 0; j < eqs.size(); j++)
        {
          Matrice_Morse& mat = ref_cast(Matrice_Morse, Mglob.get_bloc(i, j).valeur());
          eqs[i]->ajouter_termes_croises(inconnues_parts[i], eqs[j]->probleme(), inconnues_parts[j], residu_parts[i]);
          eqs[i]->contribuer_termes_croises(inconnues_parts[i], eqs[j]->probleme(), inconnues_parts[j], mat);
          /* si i == j, alors assembler_avec_inertie() se charge du produit matrice/vecteur : sinon, on doit le faire a la main */
          if (i == j) eqs[i]->assembler_avec_inertie(mat, inconnues_parts[i], residu_parts[i]);
          else mat.ajouter_multvect(inconnues_parts[j], residu_parts[i]);
        }
// resolution
  solveur.valeur().reinit();
  solveur.resoudre_systeme(Mglob, residus, inconnues);
  inconnues.echange_espace_virtuel();
// mise a jour
  bool converge = true;
  for(i = 0; i < eqs.size(); i++)
    {
      dudt_parts[i] -= inconnues_parts[i];
      double dudt_norme = mp_norme_vect(dudt_parts[i]);
      eqs[i]->inconnue().valeurs() = inconnues_parts[i];
      converge &= (dudt_norme < seuil_convg);
      if (!converge)
        {
          Cout<<eqs[i]->que_suis_je()<<" is not converged at the implicit iteration "<<nb_iter<<" ( ||uk-uk-1|| = "<<dudt_norme<<" > implicit threshold "<<seuil_convg<<" )"<<finl;
          if (nb_iter>=10) Cout << "Consider lowering facsec_max value. Look at the reference manual for advice to set facsec_max value according to the problem type." << finl;
        }
      else
        Cout<<eqs[i]->que_suis_je()<<" is converged at the implicit iteration "<<nb_iter<<" ( ||uk-uk-1|| = "<<dudt_norme<<" < implicit threshold "<<seuil_convg<<" )"<<finl;
      eqs[i]->inconnue().futur() = eqs[i]->inconnue().valeurs();
      const double t = eqs[i]->schema_temps().temps_courant() + eqs[i]->schema_temps().pas_de_temps();
      eqs[i]->zone_Cl_dis()->imposer_cond_lim(eqs[i]->inconnue(), t);
      eqs[i]->inconnue().valeurs() = eqs[i]->inconnue().futur();
      eqs[i]->inconnue().valeur().Champ_base::changer_temps(t);
    }
  for(i = 0; i < eqs.size(); i++) eqs[i]->probleme().mettre_a_jour(eqs[i]->schema_temps().temps_courant());
// on desalloue les tableaux de coeffs
  for (i = 0; i < eqs.size(); i++)
    for (j = 0; j < eqs.size(); j++) ref_cast(Matrice_Morse, Mglob.get_bloc(i, j).valeur()).get_set_coeff().reset();
  return converge;
}
References MD_Vector_composite::add_part(), Matrice_Base::ajouter_multvect(), Equation_base::ajouter_termes_croises(), Equation_base::assembler_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Equation_base::contribuer_termes_croises(), MD_Vector::copy(), Cout, MD_Vector_tools::creer_tableau_distribue(), Matrice_Bloc::dimensionner(), Equation_base::dimensionner_matrice(), Equation_base::dimensionner_termes_croises(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), finl, Champ_Inc::futur(), Simpler_Base::get_and_set_parametre_implicite(), Matrice_Bloc::get_bloc(), TRUSTVect< _TYPE_ >::get_md_vector(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab2(), Nom::getString(), Zone_Cl_dis::imposer_cond_lim(), Equation_base::inconnue(), Objet_U::le_nom(), Probleme_base::le_nom(), O_U_Ptr::le_nom(), TRUSTVect< _TYPE_ >::line_size(), mbloc, Equation_base::mettre_a_jour(), mp_norme_vect(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), Objet_U::que_suis_je(), ref_cast, SolveurSys_base::reinit(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), SolveurSys::resoudre_systeme(), Equation_base::schema_temps(), Parametre_implicite::seuil_convergence_implicite(), TRUSTVect< _TYPE_ >::size(), TRUSTVect< _TYPE_ >::size_totale(), Parametre_implicite::solveur(), Schema_Temps_base::temps_courant(), Deriv_::typer(), Deriv_Champ_Inc_base::valeur(), Deriv_Matrice_Base::valeur(), Deriv_SolveurSys_base::valeur(), Champ_Inc::valeurs(), and Equation_base::zone_Cl_dis().
iterer_NS()
void Simple::iterer_NS (Equation_base & eqn, DoubleTab & current, DoubleTab & pression, double dt, Matrice_Morse & matrice, double seuil_resol, DoubleTrav & secmem, int nb_iter, int & converge, int & ok) override virtual
Implements Simpler_Base.
Reimplemented in Simpler, and Solveur_U_P.
Definition at line 549 of file Simple.cpp.
{
  Parametre_implicite& param = get_and_set_parametre_implicite(eqn);
  SolveurSys& solveur = param.solveur();
  Navier_Stokes_std& eqnNS = ref_cast(Navier_Stokes_std,eqn);
  DoubleTrav gradP(current);
  DoubleTrav correction_en_pression(pression);
  DoubleTrav correction_en_vitesse(current);
  DoubleTrav resu(current);
  int is_dilat = eqn.probleme().is_dilatable();
// int deux_entrees = 0;
// if (current.nb_dim()==2) deux_entrees = 1;
  Operateur_Grad& gradient = eqnNS.operateur_gradient();
  Operateur_Div& divergence = eqnNS.operateur_divergence();
  /* int nb_comp = 1;
     int nb_dim = current.nb_dim();
     if (nb_dim==2)
     nb_comp = current.dimension(1);
  */
  gradient.calculer(pression,gradP);
// Construction de matrice et resu
// matrice = A[Uk-1] = M/dt + CONV + DIFF
// resu = A[Uk-1]Uk-1 -(A[Uk-1]Uk-1-Ss) + Sv + (M/dt)Uk-1 -BtPk-1
  if (eqnNS.has_interface_blocs()) //si l'interface blocs est disponible, on l'utilise
    eqnNS.assembler_blocs_avec_inertie({{ "vitesse", &matrice }}, resu);
  else //sinon, on passe par ajouter/contribuer
    {
      resu -= gradP;
      eqnNS.assembler_avec_inertie(matrice,current,resu);
    }
  solveur.valeur().reinit();
// Resolution du systeme A[Uk-1]U* = -BtP* + Sv + Ss + (M/dt)Uk-1
// current = U*
  solveur.resoudre_systeme(matrice,resu,current);
// Relaxation du champ de vitesse U*
// U* = alpha U*_new + (1-alpha)*U*_old
  if (nb_ite==1)
    Ustar_old = current;
  current *= alpha_ ;
  current.ajoute(1.-alpha_,Ustar_old);
  current.echange_espace_virtuel();
  Ustar_old = current;
// Construction de matrice_en_pression_2 = BD-1Bt[Uk-1]
  Matrice& matrice_en_pression_2 = eqnNS.matrice_pression();
  assembler_matrice_pression_implicite(eqnNS,matrice,matrice_en_pression_2);
  SolveurSys& solveur_pression_ = eqnNS.solveur_pression();
  solveur_pression_.valeur().reinit();
// Calcul de secmem = BU* (en incompressible) BU* -drho/dt (en quasi-compressible)
  if (is_dilat)
    {
      if (with_d_rho_dt_)
        {
          Fluide_Dilatable_base& fluide_dil = ref_cast(Fluide_Dilatable_base,eqn.milieu());
          fluide_dil.secmembre_divU_Z(secmem);
          secmem *= -1;
        }
      else secmem = 0;
      divergence.ajouter(current,secmem);
    }
  else
    divergence.calculer(current,secmem);
  secmem *= -1;
  secmem.echange_espace_virtuel();
// Resolution du systeme (BD-1Bt)P' = BU* en incompressible
// (BD-1Bt)P' = BU* -drho/dt en quasi-compressible
// correction_en_pression = P'
  solveur_pression_.resoudre_systeme(matrice_en_pression_2.valeur(),
                                     secmem,correction_en_pression);
// Resolution de DU' = BP'
// correction_en_vitesse = U'
  calculer_correction_en_vitesse(correction_en_pression,gradP,correction_en_vitesse,matrice,gradient);
// Correction de la pression P = P* + beta_*P'
// Correction de la vitesse U = U* + beta_u*U' (beta_u=1)
  pression.ajoute(beta_,correction_en_pression);
  eqnNS.assembleur_pression().valeur().modifier_solution(pression);
  current += correction_en_vitesse;
  if (is_dilat)
    diviser_par_rho_np1_face(eqn,current);
}
References TRUSTVect< _TYPE_ >::ajoute(), Operateur_Div::ajouter(), alpha_, Equation_base::assembler_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Simpler_Base::assembler_matrice_pression_implicite(), Navier_Stokes_std::assembleur_pression(), beta_, Operateur_Div::calculer(), Operateur_Grad::calculer(), calculer_correction_en_vitesse(), diviser_par_rho_np1_face(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Simpler_Base::get_and_set_parametre_implicite(), Navier_Stokes_std::has_interface_blocs(), Probleme_base::is_dilatable(), Navier_Stokes_std::matrice_pression(), Equation_base::milieu(), Assembleur_base::modifier_solution(), Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::operateur_gradient(), Equation_base::probleme(), ref_cast, SolveurSys_base::reinit(), SolveurSys::resoudre_systeme(), Fluide_Dilatable_base::secmembre_divU_Z(), Parametre_implicite::solveur(), Navier_Stokes_std::solveur_pression(), Ustar_old, Deriv_Assembleur_base::valeur(), Deriv_Matrice_Base::valeur(), Deriv_SolveurSys_base::valeur(), and with_d_rho_dt_.
Referenced by iterer_eqn().
lire()
Entree & Simple::lire (const Motcle & motlu, Entree & is) override protected virtual
Implements Simpler_Base.
Definition at line 57 of file Simple.cpp.
{
  Motcles les_mots(1);
  {
    les_mots[0] = "relax_pression";
  }
  int rang=les_mots.search(motlu);
  switch(rang)
    {
    case 0:
      {
        is >> beta_;
        break;
      }
    default :
      {
        Cerr << "Keyword : " << motlu << " is not undertood in " << que_suis_je() << finl;
        exit();
      }
    }
  return is;
}
References beta_, Cerr, Process::exit(), finl, Objet_U::que_suis_je(), and Motcles::search().
Referenced by SETS::lire().
printOn()
Sortie & Simple::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Solveur_non_lineaire.
Reimplemented in Simpler, and Solveur_U_P.
Definition at line 47 of file Simple.cpp.
{
  return Simpler_Base::printOn(os);
}
References Simpler_Base::printOn().
Referenced by Simpler::printOn(), and Solveur_U_P::printOn().
readOn()
Entree & Simple::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Solveur_non_lineaire.
Reimplemented in Simpler, and Solveur_U_P.
Definition at line 52 of file Simple.cpp.
{
  return Simpler_Base::readOn(is);
}
References Simpler_Base::readOn().
Referenced by Simpler::readOn(), and Solveur_U_P::readOn().
self_cast() [1/2]
const Simple & Simple::self_cast (const Objet_U & r) static
Definition at line 37 of file Simple.cpp.
self_cast() [2/2]
Simple & Simple::self_cast (Objet_U & r) static
Definition at line 37 of file Simple.cpp.
taille_memoire()
unsigned Simple::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Simpler, and Solveur_U_P.
Definition at line 37 of file Simple.cpp.
Member Data Documentation
alpha_
double Simple::alpha_ protected
Definition at line 76 of file Simple.h.
Referenced by iterer_NS(), and Simple().
beta_
double Simple::beta_ protected
Definition at line 76 of file Simple.h.
Referenced by iterer_NS(), lire(), and Simple().
info_obj
const Type_info Simple::info_obj static
Definition at line 64 of file Simple.h.
mbloc
std::map<std::vector<intptr_t>, Matrice_Bloc> Simple::mbloc protected
Definition at line 83 of file Simple.h.
Referenced by iterer_eqs().
Ustar_old
DoubleTab Simple::Ustar_old protected
Definition at line 75 of file Simple.h.
Referenced by iterer_NS(), and Simple().
with_d_rho_dt_
int Simple::with_d_rho_dt_ protected
Definition at line 77 of file Simple.h.
Referenced by Piso::iterer_NS(), iterer_NS(), and Simple().
The documentation for this class was generated from the following files:
src/ThHyd/Schemas_Temps/Simple.h
src/ThHyd/Schemas_Temps/Simple.cpp