TRUST: Operateur_Diff Class Reference
Operateur_Diff Class Reference
classe Operateur_Diff
Classe generique de la hierarchie des operateurs representant un terme
de diffusion. Un objet Operateur_Diff peut referencer n'importe quel
objet derivant de Operateur_Diff_base.
#include <Operateur_Diff.h>
Public Member Functions
Operateur_Diff ()
~Operateur_Diff ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Operateur_base & l_op_base () override
Renvoie l'objet sous-jacent upcaste en Operateur_base.
const Operateur_base & l_op_base () const override
Renvoie l'objet sous-jacent upcaste en Operateur_base<br>(version const)
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
Appel a l'objet sous-jacent.
Ajoute la contribution de l'operateur au tableau
passe en parametre.
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
Appel a l'objet sous-jacent.
Initialise le tableau passe en parametre avec la contribution
de l'operateur.
void associer_diffusivite (const Champ_base &)
Associe la diffusivite a l'operateur.
void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
const Champ_base & diffusivite () const
Renvoie le champ representant la diffusivite.
void typer () override
Type l'operateur:
se type "Op_Diff_"+discretisation()+
("_"ou"_Multi_inco_")+("const_"ou"var_")
+ inconnue().suffix
Associe la diffusivite a l'operateur base.
void typer (const Nom &)
Type l'operateur.
int op_non_nul () const override
Public Member Functions inherited from Operateur
virtual Operateur_base & l_op_base ()=0
virtual const Operateur_base & l_op_base () const =0
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const =0
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const =0
DoubleTab & ajouter (const Champ_Inc &, DoubleTab &) const
Calcule et ajoute la contribution de l'operateur au second
membre de l'equation.
Appelle Operateur::ajouter(const DoubleTab&, DoubleTab&)
DoubleTab & calculer (const Champ_Inc &, DoubleTab &) const
Calcule la contribution de l'operateur, et renvoie
le tableau des valeurs.
DoubleTab & ajouter (DoubleTab &) const
Ajoute la contribution de l'operateur au tableau passe
en parametre.
Appelle Operateur::ajouter(const Champ_Inc&, DoubleTab&)
DoubleTab & calculer (DoubleTab &) const
Applique l'operateur au champ inconnu et renvoie le resultat.
Appelle Operateur::calculer(const Champ_Inc&, DoubleTab&);.
const Nom & type () const
Renvoie le (nom du) type de l'operateur a creer.
double calculer_pas_de_temps () const
Calcule le prochain pas de temps.
void calculer_pas_de_temps_locaux (DoubleTab &) const
Calculate the next local time steps.
int impr (Sortie &os) const
Imprime l'operateur sur un flot de sortie de facon
inconditionnelle.
virtual void typer ()=0
virtual void completer ()
Met a jour les references des objets associes a l'operateur.
Operateur::le_champ_inco, Operateur::champ_inco
Appelle Operateur_base::completer()
virtual void mettre_a_jour (double temps)
Effecttue une mise a jour en temps de l'operateur.
Appelle Operateur_base::mettre_a_jour(double)
const Champ_Inc & mon_inconnue () const
Renvoie le champ representant l'inconnue de l'equation dont
l'operateur fait partie.
const Discretisation_base & discretisation () const
Renvoie la discretisation de l'equation dont l'operateur
fait partie.
int limpr () const
Demande a l'equation si une impression est necessaire
Renvoie 1 pour OUI, 0 sinon.
void imprimer (Sortie &os) const
Imprime l'operateur sur un flot de sortie, si
c'est necessaire. (voir Schema_Temp_base::limpr())
Sortie & ecrire (Sortie &) const
Ecrit le type de l'operateur sur un flot de Sortie.
Entree & lire (Entree &)
Lit un operateur sur un flot d'entree.
Type l'operateur et lui associe son equation.
Format:
{
[UN Motcle REPRESENTANT UN TYPE]
}.
void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
void associer_champ (const Champ_Inc &)
void set_fichier (const Nom &nom)
void set_description (const Nom &nom)
virtual int op_non_nul () const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Deriv_Operateur_Diff_base
~Deriv_Operateur_Diff_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Operateur_Diff_base ()
Deriv_Operateur_Diff_base (const Deriv_Operateur_Diff_base &)
const Operateur_Diff_base & valeur () const
Operateur_Diff_base & valeur ()
const Operateur_Diff_base * operator-> () const
Operateur_Diff_base * operator-> ()
const Deriv_Operateur_Diff_base & operator= (const Operateur_Diff_base &)
const Deriv_Operateur_Diff_base & operator= (const Deriv_Operateur_Diff_base &)
operator const Operateur_Diff_base & () const
operator Operateur_Diff_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Operateur_Diff & self_cast (Objet_U &)
static const Operateur_Diff & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Operateur_Diff_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Operateur_Diff_base & self_cast (Objet_U &)
static const Deriv_Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a Operateur::ecrire(Sortie&)
Ecrit l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a Operateur::lire(Entree&)
Lit l'operateur a partir d'un flot d'entree.
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Deriv_Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Champ_base la_diffusivite
Protected Attributes inherited from Operateur
Ref_Champ_Inc le_champ_inco
Motcle typ
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
classe Operateur_Diff
Classe generique de la hierarchie des operateurs representant un terme
de diffusion. Un objet Operateur_Diff peut referencer n'importe quel
objet derivant de Operateur_Diff_base.
Definition at line 36 of file Operateur_Diff.h.
Constructor & Destructor Documentation
Operateur_Diff()
Operateur_Diff::Operateur_Diff ()
Definition at line 23 of file Operateur_Diff.cpp.
~Operateur_Diff()
Operateur_Diff::~Operateur_Diff ()
Definition at line 23 of file Operateur_Diff.cpp.
Member Function Documentation
ajouter()
DoubleTab & Operateur_Diff::ajouter (const DoubleTab & donnee, DoubleTab & resu) const override virtual
Appel a l'objet sous-jacent.
Ajoute la contribution de l'operateur au tableau
passe en parametre.
Returns
DoubleTab&
Signification: le tableau contenant le resultat
Contraintes:
Implements Operateur.
Definition at line 165 of file Operateur_Diff.cpp.
{
  statistiques().begin_count(diffusion_counter_);
  DoubleTab& tmp = valeur().ajouter(donnee, resu);
  statistiques().end_count(diffusion_counter_);
  return tmp;
}
References Operateur_base::ajouter(), Statistiques::begin_count(), diffusion_counter_, Statistiques::end_count(), statistiques(), and Deriv_Operateur_Diff_base::valeur().
associer_diffusivite()
void Operateur_Diff::associer_diffusivite (const Champ_base & nu)
Associe la diffusivite a l'operateur.
Definition at line 240 of file Operateur_Diff.cpp.
{
  la_diffusivite=nu;
}
References la_diffusivite.
Referenced by Convection_Diffusion_Espece_Binaire_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard(), Convection_Diffusion_std::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), and Conduction::lire_motcle_non_standard().
associer_diffusivite_pour_pas_de_temps()
void Operateur_Diff::associer_diffusivite_pour_pas_de_temps (const Champ_base & nu)
Definition at line 245 of file Operateur_Diff.cpp.
{
  valeur().associer_diffusivite_pour_pas_de_temps(nu);
}
References Operateur_Diff_base::associer_diffusivite_pour_pas_de_temps(), and Deriv_Operateur_Diff_base::valeur().
Referenced by Convection_Diffusion_Espece_Binaire_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard(), Convection_Diffusion_std::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), and Conduction::lire_motcle_non_standard().
calculer()
DoubleTab & Operateur_Diff::calculer (const DoubleTab & donnee, DoubleTab & resu) const override virtual
Appel a l'objet sous-jacent.
Initialise le tableau passe en parametre avec la contribution
de l'operateur.
Returns
DoubleTab&
Signification: le tableau contenant le resultat
Contraintes:
Implements Operateur.
Definition at line 196 of file Operateur_Diff.cpp.
{
  statistiques().begin_count(diffusion_counter_);
  DoubleTab& tmp = valeur().calculer(donnee, resu);
  statistiques().end_count(diffusion_counter_);
  return tmp;
}
References Statistiques::begin_count(), Operateur_base::calculer(), diffusion_counter_, Statistiques::end_count(), statistiques(), and Deriv_Operateur_Diff_base::valeur().
cree_instance()
Objet_U * Operateur_Diff::cree_instance () static
Definition at line 23 of file Operateur_Diff.cpp.
diffusivite()
const Champ_base & Operateur_Diff::diffusivite () const
Renvoie le champ representant la diffusivite.
Returns
Champ_Don&
Signification: le champ representant la diffusivite
Contraintes: reference constante
Definition at line 220 of file Operateur_Diff.cpp.
{
  return la_diffusivite.valeur();
}
References la_diffusivite, and Ref_Champ_base::valeur().
Referenced by Convection_Diffusion_std::diffusivite_pour_pas_de_temps(), Navier_Stokes_std::diffusivite_pour_pas_de_temps(), Conduction::diffusivite_pour_pas_de_temps(), Convection_Diffusion_Espece_Binaire_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard(), and typer().
duplique()
int Operateur_Diff::duplique () const override virtual
Reimplemented from Deriv_Operateur_Diff_base.
Definition at line 23 of file Operateur_Diff.cpp.
get_info()
const Type_info * Operateur_Diff::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Operateur_Diff_base.
Definition at line 23 of file Operateur_Diff.cpp.
info()
const Type_info * Operateur_Diff::info () static
Definition at line 23 of file Operateur_Diff.cpp.
l_op_base() [1/2]
const Operateur_base & Operateur_Diff::l_op_base () const override virtual
Renvoie l'objet sous-jacent upcaste en Operateur_base<br>(version const)
Returns
Operateur_base&
Signification: l'objet sous-jacent upcaste en Operateur_base
Contraintes: reference constante
Implements Operateur.
Definition at line 138 of file Operateur_Diff.cpp.
{
  return valeur();
}
References Deriv_Operateur_Diff_base::valeur().
l_op_base() [2/2]
Operateur_base & Operateur_Diff::l_op_base () override virtual
Renvoie l'objet sous-jacent upcaste en Operateur_base.
Returns
Operateur_base&
Signification: l'objet sous-jacent upcaste en Operateur_base
Contraintes:
Implements Operateur.
Definition at line 119 of file Operateur_Diff.cpp.
{
  return valeur();
}
References Deriv_Operateur_Diff_base::valeur().
op_non_nul()
int Operateur_Diff::op_non_nul () const inline override virtual
Implements Operateur.
Definition at line 55 of file Operateur_Diff.h.
{
  if (non_nul())
    return 1;
  else
    return 0;
}
References O_U_Ptr::non_nul().
Referenced by Convection_Diffusion_Concentration::readOn().
printOn()
Sortie & Operateur_Diff::printOn (Sortie & os) const override protected virtual
Simple appel a Operateur::ecrire(Sortie&)
Ecrit l'operateur sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Operateur_Diff_base.
Definition at line 41 of file Operateur_Diff.cpp.
{
  return Operateur::ecrire(os);
}
References Operateur::ecrire().
readOn()
Entree & Operateur_Diff::readOn (Entree & is) override protected virtual
Simple appel a Operateur::lire(Entree&)
Lit l'operateur a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Operateur_Diff_base.
Definition at line 62 of file Operateur_Diff.cpp.
{
  return Operateur::lire(is);
}
References Operateur::lire().
self_cast() [1/2]
const Operateur_Diff & Operateur_Diff::self_cast (const Objet_U & r) static
Definition at line 23 of file Operateur_Diff.cpp.
self_cast() [2/2]
Operateur_Diff & Operateur_Diff::self_cast (Objet_U & r) static
Definition at line 23 of file Operateur_Diff.cpp.
taille_memoire()
unsigned Operateur_Diff::taille_memoire () const override virtual
Reimplemented from Deriv_Operateur_Diff_base.
Definition at line 23 of file Operateur_Diff.cpp.
typer() [1/2]
void Operateur_Diff::typer () override virtual
Type l'operateur:
se type "Op_Diff_"+discretisation()+
("_"ou"_Multi_inco_")+("const_"ou"var_")
+ inconnue().suffix
Associe la diffusivite a l'operateur base.
Implements Operateur.
Definition at line 86 of file Operateur_Diff.cpp.
{
  Cerr << "Operateur_Diff::typer("<<typ<<")" << finl;
  if (Motcle(typ)==Motcle("negligeable"))
    {
      DERIV(Operateur_Diff_base)::typer("Op_Diff_negligeable");
      valeur().associer_diffusivite(diffusivite());
    }
  else
    {
      assert(la_diffusivite.non_nul());
      Equation_base& eqn=mon_equation.valeur();
      Nom nom_type= eqn.discretisation().get_name_of_type_for(que_suis_je(),typ,eqn,diffusivite());
      DERIV(Operateur_Diff_base)::typer(nom_type);
      valeur().associer_diffusivite(diffusivite());
    }
  Cerr << valeur().que_suis_je() << finl;
}
References Operateur_Diff_base::associer_diffusivite(), Cerr, DERIV, diffusivite(), Equation_base::discretisation(), finl, Discretisation_base::get_name_of_type_for(), la_diffusivite, MorEqn::mon_equation, O_U_Ptr::non_nul(), Objet_U::que_suis_je(), Operateur::typ, typer(), Ref_Equation_base::valeur(), and Deriv_Operateur_Diff_base::valeur().
Referenced by typer().
typer() [2/2]
void Operateur_Diff::typer (const Nom & un_type)
Type l'operateur.
Definition at line 264 of file Operateur_Diff.cpp.
{
  DERIV(Operateur_Diff_base)::typer(un_type);
}
References DERIV, and typer().
Member Data Documentation
info_obj
const Type_info Operateur_Diff::info_obj static
Definition at line 39 of file Operateur_Diff.h.
la_diffusivite
Ref_Champ_base Operateur_Diff::la_diffusivite protected
Definition at line 53 of file Operateur_Diff.h.
Referenced by associer_diffusivite(), diffusivite(), and typer().
The documentation for this class was generated from the following files:
src/Kernel/Operateurs/Operateur_Diff.h
src/Kernel/Operateurs/Operateur_Diff.cpp