TRUST: Ref_Champ_Don Class Reference
Ref_Champ_Don Class Reference
#include <Ref_Champ_Don.h>
Public Member Functions
~Ref_Champ_Don ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Champ_Don ()
Ref_Champ_Don (const Champ_Don &)
Ref_Champ_Don (const Ref_Champ_Don &)
const Champ_Don & valeur () const
Champ_Don & valeur ()
const Champ_Don * operator-> () const
Champ_Don * operator-> ()
const Ref_Champ_Don & operator= (const Champ_Don &)
const Ref_Champ_Don & operator= (const Ref_Champ_Don &)
operator const Champ_Don & () const
operator Champ_Don & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Champ_Don & self_cast (Objet_U &)
static const Ref_Champ_Don & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Champ_Don * pointeur_
Detailed Description
Definition at line 28 of file Ref_Champ_Don.h.
Constructor & Destructor Documentation
Ref_Champ_Don::~Ref_Champ_Don ()
Definition at line 26 of file Ref_Champ_Don.cpp.
Ref_Champ_Don::Ref_Champ_Don ()
Definition at line 26 of file Ref_Champ_Don.cpp.
Ref_Champ_Don::Ref_Champ_Don (const Champ_Don & t)
Definition at line 26 of file Ref_Champ_Don.cpp.
Ref_Champ_Don::Ref_Champ_Don (const Ref_Champ_Don & t)
Definition at line 26 of file Ref_Champ_Don.cpp.
Member Function Documentation
Objet_U * Ref_Champ_Don::cree_instance () [static]
Definition at line 26 of file Ref_Champ_Don.cpp.
int Ref_Champ_Don::duplique () const [virtual]
Implements Ref_.
Definition at line 26 of file Ref_Champ_Don.cpp.
const Type_info * Ref_Champ_Don::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Don.cpp.
const Type_info & Ref_Champ_Don::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Ref_Champ_Don.cpp.
const Type_info * Ref_Champ_Don::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Don.cpp.
Ref_Champ_Don::operator Champ_Don & ()
Definition at line 26 of file Ref_Champ_Don.cpp.
Ref_Champ_Don::operator const Champ_Don & () const
Definition at line 26 of file Ref_Champ_Don.cpp.
const Champ_Don * Ref_Champ_Don::operator-> () const [inline]
Definition at line 28 of file Ref_Champ_Don.h.
Champ_Don * Ref_Champ_Don::operator-> () [inline]
Definition at line 28 of file Ref_Champ_Don.h.
const Ref_Champ_Don & Ref_Champ_Don::operator= (const Ref_Champ_Don & t)
Definition at line 26 of file Ref_Champ_Don.cpp.
const Ref_Champ_Don & Ref_Champ_Don::operator= (const Champ_Don & t)
Definition at line 26 of file Ref_Champ_Don.cpp.
Sortie & Ref_Champ_Don::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Don.cpp.
Entree & Ref_Champ_Don::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Don.cpp.
const Ref_Champ_Don & Ref_Champ_Don::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Don.cpp.
Ref_Champ_Don & Ref_Champ_Don::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Don.cpp.
void Ref_Champ_Don::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Ref_Champ_Don.cpp.
unsigned Ref_Champ_Don::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Ref_Champ_Don.cpp.
const Champ_Don & Ref_Champ_Don::valeur () const [inline]
Definition at line 28 of file Ref_Champ_Don.h.
Referenced by Source_Neutronique_VDF::associer_pb(), Terme_Source_inc_th_VDF_Face::beta(), Terme_Boussinesq_base::beta(), Eval_Source_C_VDF_Elem::calculer_terme_source(), Eval_Source_C_PolyMAC_Elem::calculer_terme_source(), Eval_Source_C_CoviMAC_Elem::calculer_terme_source(), Eval_Puiss_Th_CoviMAC_Elem::calculer_terme_source(), Eval_Source_C_VEF_Face::calculer_terme_source_non_standard(), Eval_Puiss_Th_VEF_Face::calculer_terme_source_non_standard(), Eval_Puiss_Th_QC_VEF_Face::calculer_terme_source_non_standard(), Eval_Source_C_VEF_Face::calculer_terme_source_standard(), Eval_Puiss_Th_QC_VEF_Face::calculer_terme_source_standard(), Eval_Puiss_Th_QC_EF::calculer_terme_source_standard(), Eval_Puiss_Th_EF::calculer_terme_source_standard(), Eval_Dirac_VEF_Face::mettre_a_jour(), and Eval_Dirac_VDF_Elem::mettre_a_jour().
Champ_Don & Ref_Champ_Don::valeur () [inline]
Definition at line 28 of file Ref_Champ_Don.h.
Member Data Documentation
const Type_info Ref_Champ_Don::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Champ_Don.h.
Champ_Don* Ref_Champ_Don::pointeur_ [private]
Definition at line 28 of file Ref_Champ_Don.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Ref_Champ_Don.h
src/Kernel/Framework/Ref_Champ_Don.cpp