TRUST: Op_Diff_Dift_VDF< OP_TYPE > Class Template Reference
Op_Diff_Dift_VDF< OP_TYPE > Class Template Reference
#include <Op_Diff_Dift_VDF.h>
Protected Member Functions
template<Type_Operateur _TYPE_, typename EVAL_TYPE >
std::enable_if< _TYPE_==Type_Operateur::Op_DIFF_ELEM||_TYPE_==Type_Operateur::Op_DIFT_ELEM, void >::type associer_impl (const Zone_dis &zone_dis, const Zone_Cl_dis &zone_cl_dis, const Champ_Inc &ch_diffuse)
template<Type_Operateur _TYPE_, typename EVAL_TYPE >
std::enable_if< _TYPE_==Type_Operateur::Op_DIFF_FACE||_TYPE_==Type_Operateur::Op_DIFT_FACE, void >::type associer_impl (const Zone_dis &zone_dis, const Zone_Cl_dis &zone_cl_dis, const Champ_Inc &ch_diffuse)
template<typename EVAL_TYPE >
void associer_diffusivite_impl (const Champ_base &ch_diff)
template<typename EVAL_TYPE >
const Champ_base & diffusivite_impl () const
template<Type_Operateur _TYPE_, typename EVAL_TYPE >
std::enable_if< _TYPE_==Type_Operateur::Op_DIFF_FACE, void >::type mettre_a_jour_impl ()
template<Type_Operateur _TYPE_, typename EVAL_TYPE >
std::enable_if< _TYPE_==Type_Operateur::Op_DIFT_ELEM||_TYPE_==Type_Operateur::Op_DIFT_FACE, void >::type associer_diffusivite_turbulente_impl (const Champ_Fonc &visc_ou_diff_turb)
template<Type_Operateur _TYPE_, typename EVAL_TYPE >
std::enable_if< _TYPE_==Type_Operateur::Op_DIFT_ELEM, void >::type associer_loipar_impl (const Turbulence_paroi_scal &loi_paroi)
template<Type_Operateur _TYPE_, typename EVAL_TYPE >
std::enable_if< _TYPE_==Type_Operateur::Op_DIFT_ELEM, void >::type completer_impl ()
template<Type_Operateur _TYPE_, typename EVAL_TYPE >
std::enable_if< _TYPE_==Type_Operateur::Op_DIFT_FACE, void >::type completer_impl ()
Private Member Functions
const Iterateur_VDF & iter_ () const
Iterateur_VDF & iter_ ()
template<typename EVAL_TYPE >
EVAL_TYPE & associer_ (const Zone_dis &zone_dis, const Zone_Cl_dis &zone_cl_dis)
Detailed Description
template<typename OP_TYPE>
class Op_Diff_Dift_VDF< OP_TYPE >
Definition at line 30 of file Op_Diff_Dift_VDF.h.
Member Function Documentation
associer_()
template<typename OP_TYPE > template<typename EVAL_TYPE > EVAL_TYPE & Op_Diff_Dift_VDF< OP_TYPE >::associer_ (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis) inline private
Definition at line 132 of file Op_Diff_Dift_VDF.h.
  {
    const Zone_VDF& zvdf = ref_cast(Zone_VDF,zone_dis.valeur());
    const Zone_Cl_VDF& zclvdf = ref_cast(Zone_Cl_VDF,zone_cl_dis.valeur());
    iter_()->associer(zvdf,zclvdf,static_cast<OP_TYPE&>(*this));
    EVAL_TYPE& eval_diff = static_cast<EVAL_TYPE&> (iter_()->evaluateur());
    eval_diff.associer_zones(zvdf,zclvdf);
    return eval_diff;
  }
References Iterateur_VDF::associer(), Iterateur_VDF::evaluateur(), Op_Diff_Dift_VDF< OP_TYPE >::iter_(), ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
associer_diffusivite_impl()
template<typename OP_TYPE > template<typename EVAL_TYPE > void Op_Diff_Dift_VDF< OP_TYPE >::associer_diffusivite_impl (const Champ_base & ch_diff) inline protected
Definition at line 51 of file Op_Diff_Dift_VDF.h.
  {
    EVAL_TYPE& eval_diff_turb = static_cast<EVAL_TYPE&>(iter_()->evaluateur());
    eval_diff_turb.associer(ch_diff);
  }
References Iterateur_VDF::evaluateur(), and Op_Diff_Dift_VDF< OP_TYPE >::iter_().
associer_diffusivite_turbulente_impl()
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if< _TYPE_==Type_Operateur::Op_DIFT_ELEM||_TYPE_==Type_Operateur::Op_DIFT_FACE, void >::type Op_Diff_Dift_VDF< OP_TYPE >::associer_diffusivite_turbulente_impl (const Champ_Fonc & visc_ou_diff_turb) inline protected
< hohohoho
Definition at line 74 of file Op_Diff_Dift_VDF.h.
  {
    static_cast<OP_TYPE *>(this)->associer_diffusivite_turbulente_base(visc_ou_diff_turb); //!< hohohoho
    EVAL_TYPE& eval_diff_turb = static_cast<EVAL_TYPE&>(iter_()->evaluateur());
    eval_diff_turb.associer_diff_turb(visc_ou_diff_turb);
  }
References Iterateur_VDF::evaluateur(), and Op_Diff_Dift_VDF< OP_TYPE >::iter_().
associer_impl() [1/2]
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if< _TYPE_==Type_Operateur::Op_DIFF_ELEM||_TYPE_==Type_Operateur::Op_DIFT_ELEM, void >::type Op_Diff_Dift_VDF< OP_TYPE >::associer_impl (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_diffuse) inline protected
Definition at line 36 of file Op_Diff_Dift_VDF.h.
  {
    const Champ_P0_VDF& inco = ref_cast(Champ_P0_VDF,ch_diffuse.valeur());
    associer_<EVAL_TYPE>(zone_dis,zone_cl_dis).associer_inconnue(inco);
  }
References ref_cast, and Deriv_Champ_Inc_base::valeur().
associer_impl() [2/2]
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if< _TYPE_==Type_Operateur::Op_DIFF_FACE||_TYPE_==Type_Operateur::Op_DIFT_FACE, void >::type Op_Diff_Dift_VDF< OP_TYPE >::associer_impl (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_diffuse) inline protected
Definition at line 44 of file Op_Diff_Dift_VDF.h.
  {
    const Champ_Face& inco = ref_cast(Champ_Face,ch_diffuse.valeur());
    associer_<EVAL_TYPE>(zone_dis,zone_cl_dis).associer_inconnue(inco);
  }
References ref_cast, and Deriv_Champ_Inc_base::valeur().
associer_loipar_impl()
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if< _TYPE_==Type_Operateur::Op_DIFT_ELEM, void >::type Op_Diff_Dift_VDF< OP_TYPE >::associer_loipar_impl (const Turbulence_paroi_scal & loi_paroi) inline protected
Definition at line 83 of file Op_Diff_Dift_VDF.h.
  {
    EVAL_TYPE& eval_diff_turb = static_cast<EVAL_TYPE&>(iter_()->evaluateur());
    eval_diff_turb.associer_loipar(loi_paroi);
  }
References Iterateur_VDF::evaluateur(), and Op_Diff_Dift_VDF< OP_TYPE >::iter_().
completer_impl() [1/2]
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if< _TYPE_==Type_Operateur::Op_DIFT_ELEM, void >::type Op_Diff_Dift_VDF< OP_TYPE >::completer_impl () inline protected
< YES !
< Et YES !
< utile juste pour Const/Var Elem... sinon on fait rien
< bizarre mais V2 (on fait comme le cas de l'Op_FACE mais sans assoscier un modele ...)
Definition at line 90 of file Op_Diff_Dift_VDF.h.
  {
    static_cast<OP_TYPE *>(this)->completer_Op_Dift_VDF_base();
    const RefObjU& modele_turbulence = static_cast<OP_TYPE *>(this)->equation().get_modele(TURBULENCE);
    if (sub_type(Modele_turbulence_scal_base,modele_turbulence.valeur()))
      {
        const Modele_turbulence_scal_base& mod_turb = ref_cast(Modele_turbulence_scal_base,modele_turbulence.valeur());
        const Champ_Fonc& lambda_t = mod_turb.conductivite_turbulente();
        associer_diffusivite_turbulente_impl<_TYPE_,EVAL_TYPE>(lambda_t); //!< YES !
        const Turbulence_paroi_scal& loipar = mod_turb.loi_paroi();
        if (loipar.non_nul()) associer_loipar_impl<_TYPE_,EVAL_TYPE>(loipar); //!< Et YES !
        EVAL_TYPE& eval_diff_turb = static_cast<EVAL_TYPE&> (iter_()->evaluateur());
        eval_diff_turb.init_ind_fluctu_term(); //!< utile juste pour Const/Var Elem... sinon on fait rien
      }
    else //!< bizarre mais V2 (on fait comme le cas de l'Op_FACE mais sans assoscier un modele ...)
      {
        const Mod_turb_hyd_base& mod_turb = ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur());
        const Champ_Fonc& alpha_t = mod_turb.viscosite_turbulente();
        associer_diffusivite_turbulente_impl<_TYPE_,EVAL_TYPE>(alpha_t);
      }
  }
References Modele_turbulence_scal_base::conductivite_turbulente(), Iterateur_VDF::evaluateur(), Op_Diff_Dift_VDF< OP_TYPE >::iter_(), Modele_turbulence_scal_base::loi_paroi(), O_U_Ptr::non_nul(), ref_cast, sub_type, TURBULENCE, Ref_Objet_U::valeur(), and Mod_turb_hyd_base::viscosite_turbulente().
completer_impl() [2/2]
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if< _TYPE_==Type_Operateur::Op_DIFT_FACE, void >::type Op_Diff_Dift_VDF< OP_TYPE >::completer_impl () inline protected
Definition at line 115 of file Op_Diff_Dift_VDF.h.
  {
    static_cast<OP_TYPE *>(this)->completer_Op_Dift_VDF_base();
    const RefObjU& modele_turbulence = static_cast<OP_TYPE *>(this)->equation().get_modele(TURBULENCE);
    const Mod_turb_hyd_base& mod_turb = ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur());
    const Champ_Fonc& visc_turb = mod_turb.viscosite_turbulente();
    associer_diffusivite_turbulente_impl<_TYPE_,EVAL_TYPE>(visc_turb);
    EVAL_TYPE& eval_diff_turb = static_cast<EVAL_TYPE&> (iter_()->evaluateur());
    eval_diff_turb.associer_modele_turbulence(mod_turb);
  }
References Iterateur_VDF::evaluateur(), Op_Diff_Dift_VDF< OP_TYPE >::iter_(), ref_cast, TURBULENCE, Ref_Objet_U::valeur(), and Mod_turb_hyd_base::viscosite_turbulente().
diffusivite_impl()
template<typename OP_TYPE > template<typename EVAL_TYPE > const Champ_base & Op_Diff_Dift_VDF< OP_TYPE >::diffusivite_impl () const inline protected
Definition at line 58 of file Op_Diff_Dift_VDF.h.
  {
    const EVAL_TYPE& eval_diff_turb = static_cast<const EVAL_TYPE&>(iter_()->evaluateur());
    return eval_diff_turb.get_diffusivite();
  }
References Iterateur_VDF::evaluateur(), and Op_Diff_Dift_VDF< OP_TYPE >::iter_().
iter_() [1/2]
template<typename OP_TYPE > Iterateur_VDF & Op_Diff_Dift_VDF< OP_TYPE >::iter_ () inline private
Definition at line 129 of file Op_Diff_Dift_VDF.h.
{ return static_cast<OP_TYPE *>(this)->get_iter(); }
iter_() [2/2]
template<typename OP_TYPE > const Iterateur_VDF & Op_Diff_Dift_VDF< OP_TYPE >::iter_ () const inline private
Definition at line 128 of file Op_Diff_Dift_VDF.h.
{ return static_cast<const OP_TYPE *>(this)->get_iter(); }
Referenced by Op_Diff_Dift_VDF< OP_TYPE >::associer_(), Op_Diff_Dift_VDF< OP_TYPE >::associer_diffusivite_impl(), Op_Diff_Dift_VDF< OP_TYPE >::associer_diffusivite_turbulente_impl(), Op_Diff_Dift_VDF< OP_TYPE >::associer_loipar_impl(), Op_Diff_Dift_VDF< OP_TYPE >::completer_impl(), Op_Diff_Dift_VDF< OP_TYPE >::diffusivite_impl(), and Op_Diff_Dift_VDF< OP_TYPE >::mettre_a_jour_impl().
mettre_a_jour_impl()
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if< _TYPE_==Type_Operateur::Op_DIFF_FACE, void >::type Op_Diff_Dift_VDF< OP_TYPE >::mettre_a_jour_impl () inline protected
Definition at line 66 of file Op_Diff_Dift_VDF.h.
  {
    EVAL_TYPE& eval_diff = static_cast<EVAL_TYPE&> (iter_()->evaluateur());
    eval_diff.mettre_a_jour();
  }
References Iterateur_VDF::evaluateur(), and Op_Diff_Dift_VDF< OP_TYPE >::iter_().
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Op_Diff_Dift/Op_Diff_Dift_VDF.h