TRUST: Zone_dis Class Reference
Zone_dis Class Reference
classe Zone_dis
Classe generique de la hierarchie des zones discretisees. Un objet
de type Zone_dis peut referencer n'importe quel objet derivant de
Zone_dis_base.
La plupart des methodes appellent les methodes de l'objet Zone
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
#include <Zone_dis.h>
Public Member Functions
Zone_dis ()
~Zone_dis ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Appel a l'objet sous-jacent.
Associe une zone (non discretisee) a l'objet.
void associer_domaine_dis (const Domaine_dis &)
const Zone & zone () const
Appel a l'objet sous-jacent.
Renvoie la zone associee.
(version const)
Zone & zone ()
Appel a l'objet sous-jacent.
Renvoie la zone associee.
void discretiser ()
Appel a l'objet sous-jacent.
Se discretise cf Zone_dis_base.
void creer_elements_fictifs (const Zone_Cl_dis_base &)
const Frontiere_dis_base & frontiere_dis (int) const
Appel a l'objet sous-jacent.
Renvoie la ieme frontiere.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Zone_dis & self_cast (Objet_U &)
static const Zone_dis & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Imprime la zone discretisee sur un flot de sortie.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lit la zone discretisee a partir d'un flot d'entree.
Detailed Description
classe Zone_dis
Classe generique de la hierarchie des zones discretisees. Un objet
de type Zone_dis peut referencer n'importe quel objet derivant de
Zone_dis_base.
La plupart des methodes appellent les methodes de l'objet Zone
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
Definition at line 47 of file Zone_dis.h.
Constructor & Destructor Documentation
Zone_dis::Zone_dis ()
Definition at line 26 of file Zone_dis.cpp.
Zone_dis::~Zone_dis ()
Definition at line 26 of file Zone_dis.cpp.
Member Function Documentation
void Zone_dis::associer_domaine_dis (const Domaine_dis & un_domaine_dis) [inline]
Definition at line 84 of file Zone_dis.h.
References Zone_dis_base::associer_domaine_dis(), and Deriv_Zone_dis_base::valeur().
Referenced by Domaine_dis::discretiser().
{
  valeur().associer_domaine_dis(un_domaine_dis);
}
void Zone_dis::associer_zone (const Zone & une_zone) [inline]
Appel a l'objet sous-jacent.
Associe une zone (non discretisee) a l'objet.
Definition at line 79 of file Zone_dis.h.
References Zone_dis_base::associer_zone(), and Deriv_Zone_dis_base::valeur().
Referenced by Domaine_dis::discretiser().
{
  valeur().associer_zone(une_zone);
}
Objet_U * Zone_dis::cree_instance () [static]
Reimplemented from Deriv_Zone_dis_base.
Definition at line 26 of file Zone_dis.cpp.
void Zone_dis::creer_elements_fictifs (const Zone_Cl_dis_base & zcl) [inline]
Definition at line 150 of file Zone_dis.h.
References Zone_dis_base::creer_elements_fictifs(), and Deriv_Zone_dis_base::valeur().
{
  valeur().creer_elements_fictifs( zcl);
}
void Zone_dis::discretiser () [inline]
Appel a l'objet sous-jacent.
Se discretise cf Zone_dis_base.
Definition at line 145 of file Zone_dis.h.
References Zone_dis_base::discretiser(), and Deriv_Zone_dis_base::valeur().
Referenced by Domaine_dis::discretiser().
{
  valeur().discretiser();
}
int Zone_dis::duplique () const [virtual]
Reimplemented from Deriv_Zone_dis_base.
Definition at line 26 of file Zone_dis.cpp.
const Frontiere_dis_base & Zone_dis::frontiere_dis (int i) const [inline]
Appel a l'objet sous-jacent.
Renvoie la ieme frontiere.
Returns:
Frontiere_dis_base&
Signification: la i-eme frontiere de la zone discretisee
Contraintes: reference constante
Definition at line 169 of file Zone_dis.h.
References Zone_dis_base::frontiere_dis(), and Deriv_Zone_dis_base::valeur().
{
  return valeur().frontiere_dis(i);
}
const Type_info * Zone_dis::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Zone_dis_base.
Definition at line 26 of file Zone_dis.cpp.
const Type_info * Zone_dis::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Zone_dis_base.
Definition at line 26 of file Zone_dis.cpp.
Sortie & Zone_dis::printOn (Sortie & os) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Imprime la zone discretisee sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Zone_dis_base.
Definition at line 44 of file Zone_dis.cpp.
References DERIV.
{
  return DERIV(Zone_dis_base)::printOn(os);
}
Entree & Zone_dis::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lit la zone discretisee a partir d'un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Zone_dis_base.
Definition at line 65 of file Zone_dis.cpp.
References DERIV.
{
  return DERIV(Zone_dis_base)::readOn(is);
}
const Zone_dis & Zone_dis::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Zone_dis_base.
Definition at line 26 of file Zone_dis.cpp.
Zone_dis & Zone_dis::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Zone_dis_base.
Definition at line 26 of file Zone_dis.cpp.
unsigned Zone_dis::taille_memoire () const [virtual]
Reimplemented from Deriv_Zone_dis_base.
Definition at line 26 of file Zone_dis.cpp.
Zone & Zone_dis::zone () [inline]
Appel a l'objet sous-jacent.
Renvoie la zone associee.
Returns:
Zone&
Signification: la zone associee
Contraintes:
Definition at line 125 of file Zone_dis.h.
References Deriv_Zone_dis_base::valeur(), and Zone_dis_base::zone().
{
  return valeur().zone();
}
const Zone & Zone_dis::zone () const [inline]
Appel a l'objet sous-jacent.
Renvoie la zone associee.
(version const)
Returns:
Zone&
Signification: la zone associee
Contraintes: reference constante
Definition at line 105 of file Zone_dis.h.
References Deriv_Zone_dis_base::valeur(), and Zone_dis_base::zone().
Referenced by Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Navier_Stokes_std::calculer_pression_hydrostatique(), Zone_Cl_EF::imposer_symetrie(), Zone_Cl_EF::imposer_symetrie_matrice_secmem(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Operateur_base::ouvrir_fichier(), Zone_Cl_dis_base::readOn(), and Zone_Cl_dis_base::zone().
{
  return valeur().zone();
}
Member Data Documentation
const Type_info Zone_dis::info_obj [static]
Reimplemented from Deriv_Zone_dis_base.
Definition at line 50 of file Zone_dis.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Zone_dis.h
src/Kernel/Framework/Zone_dis.cpp