TRUST: Assembleur Class Reference
Assembleur Class Reference
#include <Assembleur.h>
Public Member Functions
Assembleur ()
~Assembleur ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int assembler (Matrice &)
Appel a l'objet sous-jacent.
Permet d'assembler le systeme.
int assembler_QC (const DoubleTab &, Matrice &)
Appel a l'objet sous-jacent.
Permet d'assembler le systeme.
void completer (const Equation_base &)
Appel a l'objet sous-jacent.
Permet de completer le systeme.
void associer_zone_dis_base (const Zone_dis_base &)
Appel a l'objet sous-jacent.
Permet d'associer l'objet a la zone discretisee.
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Appel a l'objet sous-jacent.
Permet d'associer l'objet a la Zone_Cl_dis.
const Zone_dis_base & zone_dis_base () const
Appel a l'objet sous-jacent.
Renvoie la zone discretisee associee a l'objet.
const Zone_Cl_dis_base & zone_Cl_dis_base () const
Appel a l'objet sous-jacent.
Renvoie la Zone_Cl_dis associee a l'objet.
int modifier_secmem (DoubleTab &)
Appel a l'objet sous-jacent.
Permet de modifier le second membre du systeme
Modifie egalement la solution (dans le cas du systeme en pression)
en fonction des conditions aux limites.
int modifier_solution (DoubleTab &)
Appel a l'objet sous-jacent.
Permet de modifier la pression.
Public Member Functions inherited from Deriv_Assembleur_base
~Deriv_Assembleur_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Assembleur_base ()
Deriv_Assembleur_base (const Deriv_Assembleur_base &)
const Assembleur_base & valeur () const
Assembleur_base & valeur ()
const Assembleur_base * operator-> () const
Assembleur_base * operator-> ()
const Deriv_Assembleur_base & operator= (const Assembleur_base &)
const Deriv_Assembleur_base & operator= (const Deriv_Assembleur_base &)
operator const Assembleur_base & () const
operator Assembleur_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Assembleur & self_cast (Objet_U &)
static const Assembleur & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Assembleur_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Assembleur_base & self_cast (Objet_U &)
static const Deriv_Assembleur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Assembleur_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a Assembleur_base::printOn(Sortie&)
Imprime l'equation et ses composants sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a Assembleur_base::readOn(Entree&)
Imprime l'equation et ses composants sur un flot de sortie.
Protected Member Functions inherited from Deriv_Assembleur_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Definition at line 41 of file Assembleur.h.
Constructor & Destructor Documentation
Assembleur()
Assembleur::Assembleur ()
Definition at line 20 of file Assembleur.cpp.
~Assembleur()
Assembleur::~Assembleur ()
Definition at line 20 of file Assembleur.cpp.
Member Function Documentation
assembler()
int Assembleur::assembler (Matrice & mat)
Appel a l'objet sous-jacent.
Permet d'assembler le systeme.
Returns
int
Signification:
Contraintes:
Definition at line 100 of file Assembleur.cpp.
{
  return valeur().assembler(mat);
}
References Assembleur_base::assembler(), and Deriv_Assembleur_base::valeur().
Referenced by Navier_Stokes_std::preparer_calcul().
assembler_QC()
int Assembleur::assembler_QC (const DoubleTab & rho, Matrice & mat)
Appel a l'objet sous-jacent.
Permet d'assembler le systeme.
Returns
int
Signification:
Contraintes:
Definition at line 120 of file Assembleur.cpp.
{
  return valeur().assembler_QC(rho,mat);
}
References Assembleur_base::assembler_QC(), and Deriv_Assembleur_base::valeur().
Referenced by Navier_Stokes_std::preparer_calcul().
associer_zone_cl_dis_base()
void Assembleur::associer_zone_cl_dis_base (const Zone_Cl_dis_base & zcldis)
Appel a l'objet sous-jacent.
Permet d'associer l'objet a la Zone_Cl_dis.
Definition at line 160 of file Assembleur.cpp.
{
  valeur().associer_zone_cl_dis_base(zcldis);
}
References Assembleur_base::associer_zone_cl_dis_base(), and Deriv_Assembleur_base::valeur().
Referenced by Navier_Stokes_std::completer().
associer_zone_dis_base()
void Assembleur::associer_zone_dis_base (const Zone_dis_base & zdis)
Appel a l'objet sous-jacent.
Permet d'associer l'objet a la zone discretisee.
Definition at line 140 of file Assembleur.cpp.
{
  valeur().associer_zone_dis_base(zdis);
}
References Assembleur_base::associer_zone_dis_base(), and Deriv_Assembleur_base::valeur().
Referenced by Navier_Stokes_std::discretiser_assembleur_pression().
completer()
void Assembleur::completer (const Equation_base & eqn)
Appel a l'objet sous-jacent.
Permet de completer le systeme.
Definition at line 80 of file Assembleur.cpp.
{
  valeur().completer(eqn);
}
References Assembleur_base::completer(), and Deriv_Assembleur_base::valeur().
Referenced by Navier_Stokes_std::completer().
cree_instance()
Objet_U * Assembleur::cree_instance () static
Definition at line 20 of file Assembleur.cpp.
duplique()
int Assembleur::duplique () const override virtual
Reimplemented from Deriv_Assembleur_base.
Definition at line 20 of file Assembleur.cpp.
get_info()
const Type_info * Assembleur::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Assembleur_base.
Definition at line 20 of file Assembleur.cpp.
info()
const Type_info * Assembleur::info () static
Definition at line 20 of file Assembleur.cpp.
modifier_secmem()
int Assembleur::modifier_secmem (DoubleTab & secmem)
Appel a l'objet sous-jacent.
Permet de modifier le second membre du systeme
Modifie egalement la solution (dans le cas du systeme en pression)
en fonction des conditions aux limites.
Returns
int
Signification:
Contraintes:
Definition at line 222 of file Assembleur.cpp.
{
  return valeur().modifier_secmem(secmem);
}
References Assembleur_base::modifier_secmem(), and Deriv_Assembleur_base::valeur().
Referenced by Navier_Stokes_std::corriger_derivee_impl(), and Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment().
modifier_solution()
int Assembleur::modifier_solution (DoubleTab & sol)
Appel a l'objet sous-jacent.
Permet de modifier la pression.
Returns
int
Signification:
Contraintes:
Definition at line 241 of file Assembleur.cpp.
{
  return valeur().modifier_solution(sol);
}
References Assembleur_base::modifier_solution(), and Deriv_Assembleur_base::valeur().
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), Navier_Stokes_std::corriger_derivee_impl(), Solveur_U_P::iterer_NS(), and Navier_Stokes_std::projeter().
printOn()
Sortie & Assembleur::printOn (Sortie & os) const override protected virtual
Simple appel a Assembleur_base::printOn(Sortie&)
Imprime l'equation et ses composants sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Assembleur_base.
Definition at line 38 of file Assembleur.cpp.
{
  return DERIV(Assembleur_base)::printOn(os);
}
References DERIV, and printOn().
Referenced by printOn().
readOn()
Entree & Assembleur::readOn (Entree & is) override protected virtual
Simple appel a Assembleur_base::readOn(Entree&)
Imprime l'equation et ses composants sur un flot de sortie.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Assembleur_base.
Definition at line 59 of file Assembleur.cpp.
{
  return DERIV(Assembleur_base)::readOn(is);
}
References DERIV, and readOn().
Referenced by readOn().
self_cast() [1/2]
const Assembleur & Assembleur::self_cast (const Objet_U & r) static
Definition at line 20 of file Assembleur.cpp.
self_cast() [2/2]
Assembleur & Assembleur::self_cast (Objet_U & r) static
Definition at line 20 of file Assembleur.cpp.
taille_memoire()
unsigned Assembleur::taille_memoire () const override virtual
Reimplemented from Deriv_Assembleur_base.
Definition at line 20 of file Assembleur.cpp.
zone_Cl_dis_base()
const Zone_Cl_dis_base & Assembleur::zone_Cl_dis_base () const
Appel a l'objet sous-jacent.
Renvoie la Zone_Cl_dis associee a l'objet.
Returns
int
Signification:
Contraintes:
Definition at line 200 of file Assembleur.cpp.
{
  return valeur().zone_Cl_dis_base();
}
References Deriv_Assembleur_base::valeur(), and Assembleur_base::zone_Cl_dis_base().
zone_dis_base()
const Zone_dis_base & Assembleur::zone_dis_base () const
Appel a l'objet sous-jacent.
Renvoie la zone discretisee associee a l'objet.
Returns
int
Signification:
Contraintes:
Definition at line 180 of file Assembleur.cpp.
{
  return valeur().zone_dis_base();
}
References Deriv_Assembleur_base::valeur(), and Assembleur_base::zone_dis_base().
Member Data Documentation
info_obj
const Type_info Assembleur::info_obj static
Definition at line 43 of file Assembleur.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Assembleur.h
src/Kernel/Framework/Assembleur.cpp