TRUST: Echange_global_impose Class Reference
Echange_global_impose Class Reference
Classe Echange_global_impose
Cette classe represente le cas particulier de la classe
Echange_impose_base ou l'echange de chaleur total est calcule grace au
coefficient d'echange de chaleur global fourni par l'utilisateur.
ATTENTION, dans le cas des discretisations ou T est localisee au centre de l'element (VDF)
cela correspond a la modelisation d'une paroi d'echange dont l'epaisseur s'etend jusqu'a la moitie
de la premiere maille.
h_t : coefficient d'echange total
h_imp_: coefficient d'echange global (donnee utilisateur)
On a: h_t = h_imp
Les champs h_imp et T_ext sont uniformes.
#include <Echange_global_impose.h>
Public Member Functions
Echange_global_impose ()
~Echange_global_impose ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int compatible_avec_discr (const Discretisation_base &discr) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
void completer () override
NE FAIT RIEN
A surcharger dans les classes derivees.
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps de la condition aux limites.
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Champ_front & derivee_phi_ext ()
const Champ_front & derivee_phi_ext () const
Champ_front & phi_ext ()
const Champ_front & phi_ext () const
virtual double champ_exterieur (int i, int j, const Champ_front &champ_ext) const
virtual double champ_exterieur (int i, const Champ_front &champ_ext) const
virtual double flux_exterieur_impose (int i) const
virtual double flux_exterieur_impose (int i, int j) const
virtual double derivee_flux_exterieur_imposee (int i) const
virtual double derivee_flux_exterieur_imposee (int i, int j) const
const bool & has_phi_ext () const
Public Member Functions inherited from Echange_impose_base
~Echange_impose_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double h_imp (int num) const
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
virtual double h_imp (int num, int k) const
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
virtual double T_ext (int num) const
Renvoie la valeur de la temperature imposee
sur la i-eme composante du champ de frontiere.
virtual double T_ext (int num, int k) const
Renvoie la valeur de la temperature imposee
sur la (i,j)-eme composante du champ de frontiere.
void mettre_a_jour (double) override
Effectue une mise a jour en temps
des conditions aux limites.
Lors du premier appel des initialisations sont effectuees:
h_imp(0,0) = (rho(0,0)*Cp(0,0))
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
int a_mettre_a_jour_ss_pas_dt () override
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
void associer_fr_dis_base (const Frontiere_dis_base &) override
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
virtual Champ_front & T_ext ()
Renvoie le champ T_ext de temperature imposee a la frontiere.
virtual const Champ_front & T_ext () const
Renvoie le champ T_ext de temperature imposee a la frontiere.
(version const)
virtual Champ_front & h_imp ()
Constructeur par defaut de la classe Echange_impose_base.
Ne construit rien, initialise le champ init a 0.
virtual const Champ_front & h_imp () const
int compatible_avec_eqn (const Equation_base &) const override
Verifie la compatibilite des conditions aux limites avec
l'equation passee en parametre.
Les conditions aux limites de type Ech_imp_base sont
compatibles avec des equations de type:
- Thermique
- indetermine.
int compatible_avec_discr (const Discretisation_base &) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void liste_faces_loi_paroi (IntTab &)
Public Member Functions inherited from Cond_lim_base
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Echange_global_impose & self_cast (Objet_U &)
static const Echange_global_impose & self_cast (const Objet_U &)
Static Public Member Functions inherited from Echange_impose_base
static const Type_info * info ()
static Echange_impose_base & self_cast (Objet_U &)
static const Echange_impose_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Cond_lim_base
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Echange_impose_base
static const Type_info info_obj
Static Public Attributes inherited from Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
Protected Member Functions inherited from Echange_impose_base
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une condition aux limite de type Echange_impose_base
a partir d'un flot d'entree.
On doit lire le coefficient d'echange global H_imp et la temperature
a la frontiere T_ext.
Format:
"h_imp" type_champ_front bloc de lecture champ
"T_ext" type_champ_front bloc de lecture champ.
Protected Member Functions inherited from Cond_lim_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
bool phi_ext_lu_
Champ_front derivee_phi_ext_
Champ_front phi_ext_
Protected Attributes inherited from Echange_impose_base
Champ_front h_imp_
Protected Attributes inherited from Cond_lim_base
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Detailed Description
Classe Echange_global_impose
Cette classe represente le cas particulier de la classe
Echange_impose_base ou l'echange de chaleur total est calcule grace au
coefficient d'echange de chaleur global fourni par l'utilisateur.
ATTENTION, dans le cas des discretisations ou T est localisee au centre de l'element (VDF)
cela correspond a la modelisation d'une paroi d'echange dont l'epaisseur s'etend jusqu'a la moitie
de la premiere maille.
h_t : coefficient d'echange total
h_imp_: coefficient d'echange global (donnee utilisateur)
On a: h_t = h_imp
Les champs h_imp et T_ext sont uniformes.
Definition at line 48 of file Echange_global_impose.h.
Constructor & Destructor Documentation
Echange_global_impose()
Echange_global_impose::Echange_global_impose ()
Definition at line 25 of file Echange_global_impose.cpp.
{
  phi_ext_lu_ = false;
}
References phi_ext_lu_.
~Echange_global_impose()
Echange_global_impose::~Echange_global_impose ()
Definition at line 23 of file Echange_global_impose.cpp.
Member Function Documentation
avancer()
int Echange_global_impose::avancer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_contact_VDF.
Definition at line 90 of file Echange_global_impose.cpp.
{
  if (phi_ext_lu_)
    {
      derivee_phi_ext_->avancer(temps);
      phi_ext_->avancer(temps);
    }
  return  Echange_impose_base::avancer(temps);
}
References Echange_impose_base::avancer(), derivee_phi_ext_, phi_ext_, and phi_ext_lu_.
Referenced by Echange_couplage_thermique::avancer().
champ_exterieur() [1/2]
double Echange_global_impose::champ_exterieur (int i, const Champ_front & champ_ext) const virtual
Reimplemented in Echange_couplage_thermique.
Definition at line 147 of file Echange_global_impose.cpp.
{
  if (ma_zone_cl_dis->equation().que_suis_je()!="Convection_Diffusion_Concentration")
    {
      const Milieu_base& mil=ma_zone_cl_dis->equation().milieu();
      Nom nom_pb=ma_zone_cl_dis->equation().probleme().que_suis_je();
      double d_Cp;
      double d_rho;
      const Champ_base& rho=mil.masse_volumique().valeur();
      if ((nom_pb.debute_par("Probleme_Interface")|| nom_pb==Nom("Probleme_Thermo_Front_Tracking"))||!sub_type(Champ_Uniforme,rho)||nom_pb==Nom("Pb_Conduction"))
        {
// Pour le front tracking, on ne divise pas par Rho*Cp
// ni pour QC
          d_rho=1.;
          d_Cp=1.;
        }
      else
        {
          const Champ_Don& Cp =mil.capacite_calorifique();
          if (sub_type(Champ_Uniforme,rho))
            {
              d_rho= rho(0,0);
            }
          else
            {
              d_rho= rho(i);
            }
          if (sub_type(Champ_Uniforme,Cp.valeur()))
            {
              d_Cp= Cp(0,0);
            }
          else
            {
              d_Cp= Cp.valeur()(i);
            }
        }
      if (champ_ext.valeurs().size()==1)
        return champ_ext(0,0)/(d_rho*d_Cp);
      else if (champ_ext.valeurs().dimension(1)==1)
        return champ_ext(i,0)/(d_rho*d_Cp);
      else
        Cerr << "Echange_global_impose::flux_impose erreur" << finl;
      exit();
      return 0.;
    }
  else
    {
      if (champ_ext.valeurs().size()==1)
        return champ_ext(0,0);
      else if (champ_ext.valeurs().dimension(1)==1)
        return champ_ext(i,0);
      else
        Cerr << "Echange_global_impose::flux_impose erreur" << finl;
      exit();
      return 0.;
    }
}
References Milieu_base::capacite_calorifique(), Cerr, Nom::debute_par(), TRUSTTab< _TYPE_ >::dimension(), MorEqn::equation(), Process::exit(), finl, Cond_lim_base::ma_zone_cl_dis, Milieu_base::masse_volumique(), Equation_base::milieu(), Equation_base::probleme(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_ >::size(), sub_type, Deriv_Champ_base::valeur(), Deriv_Champ_Don_base::valeur(), and Champ_front::valeurs().
champ_exterieur() [2/2]
double Echange_global_impose::champ_exterieur (int i, int j, const Champ_front & champ_ext) const virtual
Reimplemented in Echange_couplage_thermique.
Definition at line 208 of file Echange_global_impose.cpp.
{
  if (ma_zone_cl_dis->equation().que_suis_je()!="Convection_Diffusion_Concentration")
    {
      const Milieu_base& mil=ma_zone_cl_dis->equation().milieu();
      Nom nom_pb=ma_zone_cl_dis->equation().probleme().que_suis_je();
      double d_Cp;
      double d_rho;
      const Champ_base& rho=mil.masse_volumique().valeur();
      if ((nom_pb.debute_par("Probleme_Interface")|| nom_pb==Nom("Probleme_Thermo_Front_Tracking"))||!sub_type(Champ_Uniforme,rho)||nom_pb==Nom("Pb_Conduction"))
        {
// Pour le front tracking, on ne divise pas par Rho*Cp
// ni pour QC
          d_rho=1.;
          d_Cp=1.;
        }
      else
        {
          const Champ_Don& Cp =mil.capacite_calorifique();
          if (sub_type(Champ_Uniforme,rho))
            {
              d_rho= rho(0,0);
            }
          else
            {
              d_rho= rho(i);
            }
          if (sub_type(Champ_Uniforme,Cp.valeur()))
            {
              d_Cp= Cp(0,0);
            }
          else
            {
              d_Cp= Cp.valeur()(i);
            }
        }
      if (champ_ext.valeurs().dimension(0)==1)
        return champ_ext(0,j)/(d_rho*d_Cp);
      else
        return champ_ext(i,j)/(d_rho*d_Cp);
    }
  else
    {
      if (champ_ext.valeurs().dimension(0)==1)
        return champ_ext(0,j);
      else
        return champ_ext(i,j);
    }
}
References Milieu_base::capacite_calorifique(), Nom::debute_par(), TRUSTTab< _TYPE_ >::dimension(), MorEqn::equation(), Cond_lim_base::ma_zone_cl_dis, Milieu_base::masse_volumique(), Equation_base::milieu(), Equation_base::probleme(), Objet_U::que_suis_je(), sub_type, Deriv_Champ_base::valeur(), Deriv_Champ_Don_base::valeur(), and Champ_front::valeurs().
Referenced by derivee_flux_exterieur_imposee(), and flux_exterieur_impose().
changer_temps_futur()
void Echange_global_impose::changer_temps_futur (double temps, int i) override virtual
Change le i-eme temps futur de la CL.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_contact_VDF.
Definition at line 80 of file Echange_global_impose.cpp.
{
  Echange_impose_base::changer_temps_futur(temps,i);
  if (phi_ext_lu_)
    {
      derivee_phi_ext_->changer_temps_futur(temps, i);
      phi_ext_->changer_temps_futur(temps, i);
    }
}
References Echange_impose_base::changer_temps_futur(), derivee_phi_ext_, phi_ext_, and phi_ext_lu_.
Referenced by Echange_couplage_thermique::changer_temps_futur().
compatible_avec_discr()
int Echange_global_impose::compatible_avec_discr (const Discretisation_base &) const override virtual
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_global_parfait.
Definition at line 75 of file Echange_global_impose.cpp.
{
  return 1;
}
completer()
void Echange_global_impose::completer (void) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_global_impose, Echange_contact_Correlation_VDF, and Echange_contact_VDF.
Definition at line 259 of file Echange_global_impose.cpp.
{
  Echange_impose_base::completer();
  if (phi_ext_lu_)
    {
      derivee_phi_ext_.typer("Ch_front_var_instationnaire_dep");
      derivee_phi_ext_->fixer_nb_comp(1);
      derivee_phi_ext_->associer_fr_dis_base(frontiere_dis());
      derivee_phi_ext_->fixer_nb_valeurs_temporelles(3);
      phi_ext_.typer("Ch_front_var_instationnaire_dep");
      phi_ext_->fixer_nb_comp(1);
      phi_ext_->associer_fr_dis_base(frontiere_dis());
      phi_ext_->fixer_nb_valeurs_temporelles(3);
    }
}
References Champ_front::associer_fr_dis_base(), Cond_lim_base::completer(), derivee_phi_ext_, Cond_lim_base::frontiere_dis(), phi_ext_, phi_ext_lu_, and Deriv_::typer().
Referenced by Echange_couplage_thermique::completer(), Echange_interne_global_impose::completer(), and Echange_contact_VDF::completer().
cree_instance()
Objet_U * Echange_global_impose::cree_instance () static
Definition at line 23 of file Echange_global_impose.cpp.
derivee_flux_exterieur_imposee() [1/2]
double Echange_global_impose::derivee_flux_exterieur_imposee (int i) const virtual
Definition at line 281 of file Echange_global_impose.cpp.
{
  return champ_exterieur(i,derivee_phi_ext());
}
References champ_exterieur(), and derivee_phi_ext().
Referenced by Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), and Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face().
derivee_flux_exterieur_imposee() [2/2]
double Echange_global_impose::derivee_flux_exterieur_imposee (int i, int j) const virtual
Definition at line 276 of file Echange_global_impose.cpp.
{
  return champ_exterieur(i,j,derivee_phi_ext());
}
References champ_exterieur(), and derivee_phi_ext().
derivee_phi_ext() [1/2]
Champ_front & Echange_global_impose::derivee_phi_ext () inline
Definition at line 93 of file Echange_global_impose.h.
{
  return derivee_phi_ext_;
}
References derivee_phi_ext_.
Referenced by derivee_flux_exterieur_imposee().
derivee_phi_ext() [2/2]
const Champ_front & Echange_global_impose::derivee_phi_ext () const inline
Definition at line 88 of file Echange_global_impose.h.
{
  return derivee_phi_ext_;
}
References derivee_phi_ext_.
duplique()
int Echange_global_impose::duplique () const override virtual
Implements Objet_U.
Reimplemented in Echange_interne_global_impose, Echange_interne_global_parfait, Echange_contact_Colburn_VDF, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_contact_VDF_Plaque_Flux_Cte, and PlaqThVDF.
Definition at line 23 of file Echange_global_impose.cpp.
flux_exterieur_impose() [1/2]
double Echange_global_impose::flux_exterieur_impose (int i) const virtual
Reimplemented in Echange_couplage_thermique.
Definition at line 291 of file Echange_global_impose.cpp.
{
  return champ_exterieur(i,phi_ext());
}
References champ_exterieur(), and phi_ext().
Referenced by Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face().
flux_exterieur_impose() [2/2]
double Echange_global_impose::flux_exterieur_impose (int i, int j) const virtual
Reimplemented in Echange_couplage_thermique.
Definition at line 286 of file Echange_global_impose.cpp.
{
  return champ_exterieur(i,j,phi_ext());
}
References champ_exterieur(), and phi_ext().
get_info()
const Type_info * Echange_global_impose::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_global_impose, Echange_interne_global_parfait, Echange_contact_Colburn_VDF, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_contact_VDF_Plaque_Flux_Cte, and PlaqThVDF.
Definition at line 23 of file Echange_global_impose.cpp.
has_phi_ext()
const bool & Echange_global_impose::has_phi_ext () const inline
Definition at line 78 of file Echange_global_impose.h.
{ return phi_ext_lu_; };
References phi_ext_lu_.
Referenced by Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face(), and Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face().
info()
const Type_info * Echange_global_impose::info () static
Definition at line 23 of file Echange_global_impose.cpp.
initialiser()
int Echange_global_impose::initialiser (double temps) override virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Echange_contact_VDF.
Definition at line 130 of file Echange_global_impose.cpp.
{
  Echange_impose_base::initialiser(temps);
  if (phi_ext_lu_)
    {
      derivee_phi_ext_->initialiser(temps, zone_Cl_dis().inconnue());
      phi_ext_->initialiser(temps, zone_Cl_dis().inconnue());
      DoubleTab& vals_derphi = derivee_phi_ext_->valeurs();
      vals_derphi = 0.;
      DoubleTab& vals_phi = phi_ext_->valeurs();
      vals_phi = 0.;
    }
  return 1;
}
References derivee_phi_ext_, Echange_impose_base::initialiser(), phi_ext_, phi_ext_lu_, Champ_front::valeurs(), and Cond_lim_base::zone_Cl_dis().
Referenced by Echange_couplage_thermique::initialiser(), and Echange_contact_VDF::initialiser().
mettre_a_jour()
void Echange_global_impose::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_contact_Correlation_VDF, Echange_contact_VDF, and PlaqThVDF.
Definition at line 120 of file Echange_global_impose.cpp.
{
  Echange_impose_base::mettre_a_jour(temps);
  if (phi_ext_lu_)
    {
      derivee_phi_ext_->mettre_a_jour(temps);
      phi_ext_->mettre_a_jour(temps);
    }
}
References derivee_phi_ext_, Champ_front::mettre_a_jour(), Echange_impose_base::mettre_a_jour(), phi_ext_, and phi_ext_lu_.
Referenced by Echange_couplage_thermique::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), and Echange_contact_VDF::mettre_a_jour().
phi_ext() [1/2]
Champ_front & Echange_global_impose::phi_ext () inline
Definition at line 103 of file Echange_global_impose.h.
{
  return phi_ext_;
}
References phi_ext_.
Referenced by flux_exterieur_impose(), and Echange_couplage_thermique::flux_exterieur_impose().
phi_ext() [2/2]
const Champ_front & Echange_global_impose::phi_ext () const inline
Definition at line 98 of file Echange_global_impose.h.
{
  return phi_ext_;
}
References phi_ext_.
printOn()
Sortie & Echange_global_impose::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_global_impose, Echange_interne_global_parfait, Echange_contact_Colburn_VDF, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_contact_VDF_Plaque_Flux_Cte, and PlaqThVDF.
Definition at line 44 of file Echange_global_impose.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
Referenced by Echange_couplage_thermique::printOn().
readOn()
Entree & Echange_global_impose::readOn (Entree & s) override protected virtual
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_global_impose, Echange_interne_global_parfait, Echange_contact_Colburn_VDF, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_contact_VDF_Plaque_Flux_Cte, and PlaqThVDF.
Definition at line 65 of file Echange_global_impose.cpp.
{
  phi_ext_lu_ = false;
// TODO : optional reading of phi_ext
  Echange_impose_base::readOn(s);
  return s ;
}
References phi_ext_lu_, and Echange_impose_base::readOn().
reculer()
int Echange_global_impose::reculer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_contact_VDF.
Definition at line 100 of file Echange_global_impose.cpp.
{
  if (phi_ext_lu_)
    {
      derivee_phi_ext_->reculer(temps);
      phi_ext_->reculer(temps);
    }
  return  Echange_impose_base::reculer(temps);
}
References derivee_phi_ext_, phi_ext_, phi_ext_lu_, and Echange_impose_base::reculer().
Referenced by Echange_couplage_thermique::reculer().
self_cast() [1/2]
const Echange_global_impose & Echange_global_impose::self_cast (const Objet_U & r) static
Definition at line 23 of file Echange_global_impose.cpp.
self_cast() [2/2]
Echange_global_impose & Echange_global_impose::self_cast (Objet_U & r) static
Definition at line 23 of file Echange_global_impose.cpp.
set_temps_defaut()
void Echange_global_impose::set_temps_defaut (double temps) override virtual
Change le i-eme temps futur de la cl.
Reimplemented from Cond_lim_base.
Definition at line 110 of file Echange_global_impose.cpp.
{
  Echange_impose_base::set_temps_defaut(temps);
  if (phi_ext_lu_)
    {
      derivee_phi_ext_->set_temps_defaut(temps);
      phi_ext_->set_temps_defaut(temps);
    }
}
References derivee_phi_ext_, phi_ext_, phi_ext_lu_, and Echange_impose_base::set_temps_defaut().
Referenced by Echange_couplage_thermique::set_temps_defaut().
taille_memoire()
unsigned Echange_global_impose::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Echange_interne_global_impose, Echange_interne_global_parfait, Echange_contact_Colburn_VDF, Echange_contact_Correlation_VDF, Echange_contact_VDF, Echange_contact_VDF_Plaque_Flux_Cte, and PlaqThVDF.
Definition at line 23 of file Echange_global_impose.cpp.
Member Data Documentation
derivee_phi_ext_
Champ_front Echange_global_impose::derivee_phi_ext_ protected
Definition at line 83 of file Echange_global_impose.h.
Referenced by avancer(), changer_temps_futur(), completer(), derivee_phi_ext(), initialiser(), mettre_a_jour(), reculer(), and set_temps_defaut().
info_obj
const Type_info Echange_global_impose::info_obj static
Definition at line 51 of file Echange_global_impose.h.
phi_ext_
Champ_front Echange_global_impose::phi_ext_ protected
Definition at line 84 of file Echange_global_impose.h.
Referenced by avancer(), changer_temps_futur(), completer(), Echange_couplage_thermique::initialiser(), initialiser(), mettre_a_jour(), phi_ext(), reculer(), and set_temps_defaut().
phi_ext_lu_
bool Echange_global_impose::phi_ext_lu_ protected
Definition at line 82 of file Echange_global_impose.h.
Referenced by avancer(), changer_temps_futur(), completer(), Echange_couplage_thermique::Echange_couplage_thermique(), Echange_global_impose(), has_phi_ext(), initialiser(), mettre_a_jour(), readOn(), reculer(), and set_temps_defaut().
The documentation for this class was generated from the following files:
src/ThSol/Echange_global_impose.h
src/ThSol/Echange_global_impose.cpp