TRUST: Matrice_Morse_Sym Class Reference
Matrice_Morse_Sym Class Reference
Classe Matrice_Morse_Sym
Represente une matrice M (creuse) symetrique stockee au format Morse
Symetrique: on ne stocke que la partie triangulaire superieure de la
matrice. Important: Tous les coefficients diagonaux doivent etre stockes
meme s'ils sont nuls (hypothese TRUST pour plusieurs methodes dont multvect).
Cette classe derive de Matrice_Morse et Matrice_Sym.
#include <Matrice_Morse_Sym.h>
Public Member Functions
~Matrice_Morse_Sym ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Matrice_Morse_Sym (int n1=1, int n2=1)
Matrice_Morse_Sym (int, int, const IntLists &, const DoubleLists &, const DoubleVect &)
Constructeur d'une Matrice_Morse_Sym comportant
n1 lignes et pouvant stocker n2 elements non-nuls (au maximum).
Les elements de la matrice et la table des connectivites
sont donnes dans les 3 derniers parametres.
Matrice_Morse_Sym (const Matrice &)
Matrice_Morse_Sym (const Matrice_Morse &)
Constructeur d'une Matrice_Morse_Sym par copie
d'une Matrice_Morse.
Matrice_Morse_Sym (const Matrice_Morse_Sym &)
Constructeur d'une Matrice_Morse_Sym par copie
d'une Matrice_Morse.
Matrice_Morse_Sym & operator= (const Matrice_Morse_Sym &)
Operateur d'affectatiob d'une Matrice_Morse_Sym
dans une Matrice_Morse_Sym.
Matrice_Morse_Sym & operator= (const Matrice_Morse &)
Matrice_Morse_Sym & operator= (const Matrice &)
Matrice_Morse_Sym & operator*= (double)
NE FAIT RIEN : NON CODE.
void scale (const double x) override
void get_stencil (IntTab &stencil) const override
void get_symmetric_stencil (IntTab &stencil) const override
void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const override
void get_symmetric_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const override
Matrice_Morse_Sym operator- () const
Operateur de negation unaire,
renvoie l'opposee de la matrice: - A.
Appelle operator*(const Matrice_Morse_Sym&,double)
DoubleTab & ajouter_multTab_ (const DoubleTab &, DoubleTab &) const override
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice represente par un tableau)
Operation: RESU = RESU + A*X.
DoubleVect & ajouter_multvect_ (const DoubleVect &, DoubleVect &) const override
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: resu = resu + A*x.
DoubleVect & ajouter_multvectT_ (const DoubleVect &, DoubleVect &) const override
Operation de multiplication-accumulation (saxpy) matrice vecteur,
par la matrice transposee.
Operation: resu = resu + A^{T}*x.
virtual double multvect_et_prodscal (const DoubleVect &, DoubleVect &) const
int inverse (const DoubleVect &, DoubleVect &, double) const override
Calcule la solution du systeme lineaire: A * solution = secmem.
La methode utilisee est GMRES preconditionnee avec ILUT.
ATTENTION: cette methode n'a vraisemblablement jamais ete testee en parallele.
int inverse (const DoubleVect &, DoubleVect &, double, int) const override
Sortie & imprimer_formatte (Sortie &s) const override
void compacte (int elim_coeff_nul=0)
Suppression des doublons
on ordonne tab2;
Verification de la diagonale: tous ses elements doivent etre stockes.
void renumerote () const
Creation d'une matrice renumerotee pour reduire la largeur de bande.
Matrice & matrice_renumerotee ()
Renvoie la matrice renumerotee.
Matrice & matrice_renumerotee () const
Renvoie la matrice renumerotee.
ArrOfInt & permutation ()
ArrOfInt & permutation_inverse ()
ArrOfInt & permutation () const
ArrOfInt & permutation_inverse () const
bool check_symmetric_morse_matrix_structure (void) const
bool check_sorted_symmetric_morse_matrix_structure (void) const
void assert_check_symmetric_morse_matrix_structure (void) const
void assert_check_sorted_symmetric_morse_matrix_structure (void) const
Public Member Functions inherited from Matrice_Morse
~Matrice_Morse ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Matrice_Morse ()
Matrice_Morse (int n, int nnz)
Constructeur d'une matrice Morse carree d'ordre n
et pouvant stocker au maximum nnz elements non nuls.
Egalement constructeur par defaut car les 2 parametres
ont une valeur par defaut.
Matrice_Morse (int n, int m, int nnz)
Constructeur d'une matrice Morse avec n lignes et m colonnes
pouvant stocker au maximum nnz elements non nuls.
Matrice_Morse (const Matrice_Morse &)
Constructeur par copie d'une Matrice_Morse.
Copie de chaque membre donne du paramtre.
Matrice_Morse (int, int, const IntLists &, const DoubleLists &, const DoubleVect &)
Sortie & imprimer (Sortie &s) const override
Sortie & imprimer_formatte (Sortie &s) const override
Sortie & imprimer_formatte (Sortie &s, int symetrie) const
Sortie & imprimer_image (Sortie &s) const
Sortie & imprimer_image (Sortie &s, int symetrie) const
int largeur_de_bande () const
Retourne la largeur de bande.
void remplir (const IntLists &, const DoubleLists &, const DoubleVect &)
void remplir (const IntLists &, const DoubleLists &)
void remplir (const int, const int, const int, const int, const Matrice_Morse &)
Remplissage d'une matrice morse par une matrice morse plus petite.
void dimensionner (int n, int nnz)
Size the matrix with n lines and n columns and nnz zero-values coefficients.
void dimensionner (int n, int m, int nnz)
Size the matrix with n lines, m columns with nnz zero-values coefficients.
void dimensionner (const IntTab &)
int ordre () const override
Renvoie l'ordre de la matrice:
- le nombre de lignes si la matrice est carree
- 0 sinon.
int nb_lignes () const override
nb_lignes retourne n
int nb_colonnes () const override
nb_colonnes retourne m
int nb_coeff () const
nb_coeff retourne nnz
void set_nb_columns (const int)
void set_symmetric (const int)
int get_symmetric () const
IntVect & get_set_tab1 (void)
IntVect & get_set_tab2 (void)
DoubleVect & get_set_coeff (void)
const IntVect & get_tab1 (void) const
const IntVect & get_tab2 (void) const
const DoubleVect & get_coeff (void) const
int nb_vois (int i) const
void clean ()
Remplit la matrice avec des zeros.
double & operator() (int i, int j)
double operator() (int i, int j) const
double coef (int i, int j) const
double & coef (int i, int j)
Matrice_Morse & operator= (const Matrice_Morse &)
Operateur d'affectation d'une Matrice_Morse dans une
autre Matrice_Morse.
Matrice_Morse & operator+= (const Matrice_Morse &)
NE FAIT RIEN.
Matrice_Morse & operator*= (double)
Operateur de multiplication (de tous les elements)
d'une matrice par un scalaire.
Operation: A = x * A.
void scale (const double x) override
void get_stencil (IntTab &stencil) const override
void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const override
Matrice_Morse & operator/= (double)
Operateur de division (de tous les elements)
d'une matrice par un scalaire.
Operation: A = A / x.
Matrice_Morse & operator*= (const DoubleVect &)
Operateur de multiplication d'une matrice par un vecteur:
scaling des lignes de la matrice par les coefficients
correspondants du vecteur passe en parametre.
A *= x, effectue les scaling suivants:
A(i,:) = A(i,:) * x(i), pour toutes les lignes i de A.
Matrice_Morse operator- () const
Operateur de negation unaire, renvoie l'opposee de la matrice: - A
Appelle operator*(double,const Matrice_Morse&)
virtual int inverse (const DoubleVect &, DoubleVect &, double) const
Calcule la solution du systeme lineaire: A * solution = secmem.
La methode utilisee est GMRES preconditionnee avec ILUT.
ATTENTION: cette methode n'a vraisemblablement jamais ete testee en parallele.
virtual int inverse (const DoubleVect &, DoubleVect &, double, int) const
Matrice_Morse & affecte_prod (const Matrice_Morse &A, const Matrice_Morse &B)
Affecte le produit de 2 matrices Morse A et B a l'objet (this).
Operation: this = A * B.
void compacte (int elim_coeff_nul=0)
Method to check/clean the Matrice_Morse matrix:
-Suppress coefficient defined several times
-elim_coeff_nul=0, on ne supprime pas les coefficients nuls de la matrice
-elim_coeff_nul=1, on supprime les coefficients nuls de la matrice
-elim_coeff_nul=2, on supprime les coefficients nuls et quasi-nuls de la matrice.
DoubleVect & ajouter_multvect_ (const DoubleVect &, DoubleVect &) const override
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: resu = resu + A*x.
ArrOfDouble & ajouter_multvect_ (const ArrOfDouble &, ArrOfDouble &, ArrOfInt &) const
DoubleTab & ajouter_multTab_ (const DoubleTab &, DoubleTab &) const override
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice X representee par un tableau)
Operation: RESU = RESU + A*X.
DoubleVect & ajouter_multvectT_ (const DoubleVect &, DoubleVect &) const override
Operation de multiplication-accumulation (saxpy) matrice vecteur,
par la matrice transposee.
Operation: resu = resu + A^{T}*x.
ArrOfDouble & ajouter_multvectT_ (const ArrOfDouble &, ArrOfDouble &, ArrOfInt &) const
virtual Matrice_Morse & transpose (const Matrice_Morse &a)
*this = a transposee.
virtual Matrice_Morse & diagmulmat (const DoubleVect &x)
virtual Matrice_Morse & partie_sup (const Matrice_Morse &a)
void unite ()
void construire_sous_bloc (int nl0, int nc0, int nl1, int nc1, Matrice_Morse &result) const
void formeC ()
void formeF ()
bool has_same_morse_matrix_structure (const Matrice_Morse &) const
bool check_morse_matrix_structure (void) const
bool check_sorted_morse_matrix_structure (void) const
void assert_check_morse_matrix_structure (void) const
void assert_check_sorted_morse_matrix_structure (void) const
void sort_stencil ()
Public Member Functions inherited from Matrice_Base
Matrice_Base ()
~Matrice_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual int ordre () const =0
virtual int nb_lignes () const =0
virtual int nb_colonnes () const =0
virtual DoubleVect & ajouter_multvect_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleVect & ajouter_multvectT_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleTab & ajouter_multTab_ (const DoubleTab &x, DoubleTab &r) const =0
virtual DoubleVect & ajouter_multvect (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleVect & ajouter_multvectT (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleTab & ajouter_multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice represente par un tableau)
Operation: R = R + A*X.
virtual DoubleVect & multvect_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvect (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice.
Operation: r = A*x.
virtual DoubleVect & multvectT_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvectT (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice transposee.
Operation: r = AT*x.
virtual DoubleTab & multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Multiplication d'une matrice representee par un tableau par la matrice.
Operation: R = A*X.
virtual Sortie & imprimer (Sortie &) const
virtual Sortie & imprimer_formatte (Sortie &s) const
virtual void scale (const double x)=0
virtual void get_stencil (IntTab &stencil) const
virtual void get_symmetric_stencil (IntTab &stencil) const
virtual void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
virtual void get_symmetric_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
int get_stencil_size (void) const
virtual void build_stencil (void)
void set_stencil (const IntTab &stencil)
bool is_stencil_up_to_date (void) const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Matrice_Sym
virtual ~Matrice_Sym ()
Matrice_Sym ()
int get_est_definie () const
void set_est_definie (int)
void unsymmetrize_stencil (const int nb_lines, const IntTab &symmetric_stencil, IntTab &stencil) const
void unsymmetrize_stencil_and_coefficients (const int nb_lines, const IntTab &symmetric_stencil, const ArrOfDouble &symmetric_coefficients, IntTab &stencil, ArrOfDouble &coefficients) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Matrice_Morse_Sym & self_cast (Objet_U &)
static const Matrice_Morse_Sym & self_cast (const Objet_U &)
Static Public Member Functions inherited from Matrice_Morse
static Objet_U * cree_instance ()
static const Type_info * info ()
static Matrice_Morse & self_cast (Objet_U &)
static const Matrice_Morse & self_cast (const Objet_U &)
Static Public Member Functions inherited from Matrice_Base
static const Type_info * info ()
static Matrice_Base & self_cast (Objet_U &)
static const Matrice_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Matrice_Morse
static const Type_info info_obj
Static Public Attributes inherited from Matrice_Base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit les trois tableaux de la structure de stockage
Morse sur un flot de sortie.
Entree & readOn (Entree &) override
NON CODE.
Sortie & printOn (Sortie &x) const override
Ecrit les trois tableaux de la structure de stockage
Morse sur un flot de sortie.
Entree & readOn (Entree &) override
NON CODE.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
virtual DoubleTab & ajouter_multTab_ (const DoubleTab &, DoubleTab &) const =0
virtual DoubleVect & ajouter_multvect_ (const DoubleVect &, DoubleVect &) const =0
virtual DoubleVect & ajouter_multvectT_ (const DoubleVect &, DoubleVect &) const =0
Private Member Functions
int isLU () const
Private Attributes
ArrOfInt permutation_
ArrOfInt permutation_inverse_
Matrice matrice_renumerotee_
Friends
Matrice_Morse_Sym operator+ (const Matrice_Morse_Sym &, const Matrice_Morse_Sym &)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
NE FAIT RIEN : NON CODE.
Matrice_Morse_Sym operator* (const Matrice_Morse_Sym &, double)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
Simple appel a operator*(double,const Matrice_Morse_Sym&) (qui est NON CODE)
Matrice_Morse_Sym operator* (double, const Matrice_Morse_Sym &)
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
NE FAIT RIEN : NON CODE.
Additional Inherited Members
Public Attributes inherited from Matrice_Morse
int morse_matrix_structure_has_changed_
Flag if matrix structure changes.
int sorted_
Protected Attributes inherited from Matrice_Morse
IntVect tab1_
IntVect tab2_
DoubleVect coeff_
int m_
Number of columns.
int symetrique_
Pour inliner operator()(i,j) afin d'optimiser.
Protected Attributes inherited from Matrice_Base
bool is_stencil_up_to_date_
IntTab stencil_
Detailed Description
Classe Matrice_Morse_Sym
Represente une matrice M (creuse) symetrique stockee au format Morse
Symetrique: on ne stocke que la partie triangulaire superieure de la
matrice. Important: Tous les coefficients diagonaux doivent etre stockes
meme s'ils sont nuls (hypothese TRUST pour plusieurs methodes dont multvect).
Cette classe derive de Matrice_Morse et Matrice_Sym.
Definition at line 36 of file Matrice_Morse_Sym.h.
Constructor & Destructor Documentation
~Matrice_Morse_Sym()
Matrice_Morse_Sym::~Matrice_Morse_Sym ()
Definition at line 24 of file Matrice_Morse_Sym.cpp.
Matrice_Morse_Sym() [1/5]
Matrice_Morse_Sym::Matrice_Morse_Sym (int n1 = 1, int n2 = 1) inline
Definition at line 44 of file Matrice_Morse_Sym.h.
                                       : Matrice_Morse(n1,n2)
  {
    symetrique_=1;
  }
References Matrice_Morse::symetrique_.
Matrice_Morse_Sym() [2/5]
Matrice_Morse_Sym::Matrice_Morse_Sym (int n1, int n2, const IntLists & voisins, const DoubleLists & valeurs, const DoubleVect & terme_diag)
Constructeur d'une Matrice_Morse_Sym comportant
n1 lignes et pouvant stocker n2 elements non-nuls (au maximum).
Les elements de la matrice et la table des connectivites
sont donnes dans les 3 derniers parametres.
Definition at line 108 of file Matrice_Morse_Sym.cpp.
  : Matrice_Morse(n1, n2)
{
  symetrique_=1;
  remplir(voisins, valeurs, terme_diag);
  morse_matrix_structure_has_changed_=1;
}
References Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::remplir(), and Matrice_Morse::symetrique_.
Matrice_Morse_Sym() [3/5]
Matrice_Morse_Sym::Matrice_Morse_Sym (const Matrice & A)
Definition at line 142 of file Matrice_Morse_Sym.cpp.
{
  const Matrice_Base& A_base=A.valeur();
  if(sub_type(Matrice_Morse_Sym, A_base))
    *this=ref_cast(Matrice_Morse_Sym, A_base);
  else if(sub_type(Matrice_Morse, A_base))
    *this=ref_cast(Matrice_Morse, A_base);
  symetrique_=1;
  morse_matrix_structure_has_changed_=1;
}
References Matrice_Morse::morse_matrix_structure_has_changed_, ref_cast, sub_type, Matrice_Morse::symetrique_, and Deriv_Matrice_Base::valeur().
Matrice_Morse_Sym() [4/5]
Matrice_Morse_Sym::Matrice_Morse_Sym (const Matrice_Morse & A)
Constructeur d'une Matrice_Morse_Sym par copie
d'une Matrice_Morse.
Definition at line 134 of file Matrice_Morse_Sym.cpp.
  :Matrice_Morse(A)
{
  symetrique_=1;
  partie_sup(A);
  compacte();
  morse_matrix_structure_has_changed_=1;
}
References compacte(), Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::partie_sup(), and Matrice_Morse::symetrique_.
Matrice_Morse_Sym() [5/5]
Matrice_Morse_Sym::Matrice_Morse_Sym (const Matrice_Morse_Sym & acopier)
Constructeur d'une Matrice_Morse_Sym par copie
d'une Matrice_Morse.
Definition at line 191 of file Matrice_Morse_Sym.cpp.
                                                                     :
  Matrice_Morse(acopier),Matrice_Sym()
{
  set_est_definie(acopier.get_est_definie());
  symetrique_=1;
  morse_matrix_structure_has_changed_=1;
}
References Matrice_Sym::get_est_definie(), Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Sym::set_est_definie(), and Matrice_Morse::symetrique_.
Member Function Documentation
ajouter_multTab_()
DoubleTab & Matrice_Morse_Sym::ajouter_multTab_ (const DoubleTab & x, DoubleTab & resu) const override virtual
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice represente par un tableau)
Operation: RESU = RESU + A*X.
Returns
DoubleTab&
Signification: la matrice resultat de l'operation
Contraintes:
Reimplemented from Matrice_Morse.
Definition at line 220 of file Matrice_Morse_Sym.cpp.
{
  if ( (x.nb_dim() == 1) && (resu.nb_dim() == 1))
    {
      ajouter_multvect(x,resu);
      return resu;
    }
  assert_check_symmetric_morse_matrix_structure( );
  int i,k,j;
  double aij;
  int comp;
  int nb_com=x.dimension(1);
  assert(resu.dimension(1)==nb_com);
  double* t=new double[nb_com];
  int n=nb_lignes();
  for(i=0; i<n; i++)
    {
      for(comp=0; comp<nb_com; comp++)
        t[comp] = coeff_(tab1_(i)-1)*x(i,comp);
      for (k=tab1_(i); k<tab1_(i+1)-1; k++)
        {
          j = tab2_(k)-1;
          aij = coeff_(k);
          for(comp=0; comp<nb_com; comp++)
            {
              t[comp] += aij*x(j,comp);
              resu(j,comp) += aij*x(i,comp);
            }
        }
      for(comp=0; comp<nb_com; comp++)
        resu(i,comp) += t[comp] ;
    }
  delete [] t;
  return resu;
}
References Matrice_Base::ajouter_multvect(), assert_check_symmetric_morse_matrix_structure(), Matrice_Morse::coeff_, TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::nb_dim(), Matrice_Morse::nb_lignes(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
ajouter_multvect_()
DoubleVect & Matrice_Morse_Sym::ajouter_multvect_ (const DoubleVect & x, DoubleVect & resu) const override virtual
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: resu = resu + A*x.
Returns
DoubleVect&
Signification: le vecteur resultat de l'operation
Contraintes:
< La diagonale meme nulle doit etre stockee dans une Mat_Morse_Sym
Reimplemented from Matrice_Morse.
Definition at line 326 of file Matrice_Morse_Sym.cpp.
{
  assert_check_symmetric_morse_matrix_structure( );
  assert(x.size_totale() == nb_lignes() || x.size() == nb_lignes());
  assert(resu.size_totale() == nb_lignes() || resu.size() == nb_lignes());
  assert(m_ <= x.size_totale());
  const int fin = nb_lignes() + 1;
  {
    const double * thecoef = get_coeff().addr() - 1;
    const double * xx = x.addr() - 1;
    double * res = resu.addr() - 1;
    const int * index1 = get_tab1().addr() - 1;
    const int * index2 = get_tab2().addr() - 1;
#ifdef COMPILER_BLRTS_XLC
#pragma disjoint (*coef, *xx, *res)
#endif
    int i;
    for (i = 1; i < fin; i++)
      {
        int j = index1[i];
        int j_next= index1[i+1];
        assert(i==index2[j]); //!< La diagonale meme nulle doit etre stockee dans une Mat_Morse_Sym
#if 0
// Note B.M.: sur les procs intel ce deroulage n'a aucun effet benefique.
        int ncoeffs = j_next - j;
        if (ncoeffs == 4)
          {
            int n2 = index2[j+1];
            int n3 = index2[j+2];
            int n4 = index2[j+3];
            double xi = xx[i];
            double res_i  = res[i];
            double res_n2 = res[n2];
            double res_n3 = res[n3];
            double res_n4 = res[n4];
            double a1 = thecoef[j];
            double a2 = thecoef[j+1];
            double a3 = thecoef[j+2];
            double a4 = thecoef[j+3];
            res[i] = res_i + a1 * xi + a2 * xx[n2] + a3 * xx[n3] + a4 * xx[n4];
            res[n2] = res_n2 + a2 * xi;
            res[n3] = res_n3 + a3 * xi;
            res[n4] = res_n4 + a4 * xi;
          }
        else
#endif
          {
            double xi = xx[i];
            double resu_tmp = res[i] + thecoef[j] * xi;
            j++;
            for (; j < j_next; j++)
              {
                int nj     = index2[j];
                double coef_j = thecoef[j];
                double xn     = xx[nj];
                resu_tmp   += coef_j * xn;
                res[nj] += coef_j * xi;
              }
            res[i] = resu_tmp;
          }
      }
  }
#if 0
  int fin2,l;
  m=tab1_(0);
  for(i=debut; i<n; i++)
    {
      xi=x(i);
      l=m;
      m=tab1_(i+1);
      t = coeff_(l-1)*xi;
      assert(i==tab2(l-1)-1); //!< La diagonale meme nulle doit etre stockee dans une Mat_Morse_Sym aij=coeff_(tab1_(i)-1);
//
      fin2=m-1;
      for (k=l; k<fin2; k++)
        {
          j = tab2_(k)-1;
          assert(j<n);
          aij = coeff_(k);
          t += aij*x(j);
          resu(j) += aij*xi;
        }
      resu(i) += t ;
    }
#endif
  return resu;
}
References TRUSTArray< _TYPE_ >::addr(), assert_check_symmetric_morse_matrix_structure(), Matrice_Morse::coeff_, Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::m_, Matrice_Morse::nb_lignes(), TRUSTVect< _TYPE_ >::size(), TRUSTVect< _TYPE_ >::size_totale(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
ajouter_multvectT_()
DoubleVect & Matrice_Morse_Sym::ajouter_multvectT_ (const DoubleVect & x, DoubleVect & resu) const override virtual
Operation de multiplication-accumulation (saxpy) matrice vecteur,
par la matrice transposee.
Operation: resu = resu + A^{T}*x.
Returns
DoubleVect&
Signification: le vecteur resultat de l'operation
Contraintes:
Reimplemented from Matrice_Morse.
Definition at line 438 of file Matrice_Morse_Sym.cpp.
{
  Cerr <<"Matrice_Morse_Sym::ajouter_multvectT_ is not coded" << finl;
  exit();
  return resu;
}
References Cerr, Process::exit(), and finl.
assert_check_sorted_symmetric_morse_matrix_structure()
void Matrice_Morse_Sym::assert_check_sorted_symmetric_morse_matrix_structure (void) const
Definition at line 1150 of file Matrice_Morse_Sym.cpp.
{
  if (!morse_matrix_structure_has_changed_) return;
#ifndef NDEBUG
  if ( ! ( check_symmetric_morse_matrix_structure( ) ) )
    {
      Cerr << "Error in 'Matrice_Morse_Sym::assert_check_sorted_symmetric_morse_matrix_structure( )':" << finl;
      Cerr << "  Exiting..." << finl;
      Process::exit( );
    }
  else
    morse_matrix_structure_has_changed_=0;
#endif
}
References Cerr, check_symmetric_morse_matrix_structure(), Process::exit(), finl, and Matrice_Morse::morse_matrix_structure_has_changed_.
assert_check_symmetric_morse_matrix_structure()
void Matrice_Morse_Sym::assert_check_symmetric_morse_matrix_structure (void) const
Definition at line 1135 of file Matrice_Morse_Sym.cpp.
{
  if (!morse_matrix_structure_has_changed_) return;
#ifndef NDEBUG
  if ( ! ( check_symmetric_morse_matrix_structure( ) ) )
    {
      Cerr << "Error in 'Matrice_Morse_Sym::assert_check_symmetric_morse_matrix_structure( )':" << finl;
      Cerr << "  Exiting..." << finl;
      Process::exit( );
    }
  else
    morse_matrix_structure_has_changed_=0;
#endif
}
References Cerr, check_symmetric_morse_matrix_structure(), Process::exit(), finl, and Matrice_Morse::morse_matrix_structure_has_changed_.
Referenced by ajouter_multTab_(), ajouter_multvect_(), get_stencil(), get_stencil_and_coefficients(), get_symmetric_stencil(), get_symmetric_stencil_and_coefficients(), and multvect_et_prodscal().
check_sorted_symmetric_morse_matrix_structure()
bool Matrice_Morse_Sym::check_sorted_symmetric_morse_matrix_structure (void) const
Definition at line 1108 of file Matrice_Morse_Sym.cpp.
{
  if ( ! ( check_sorted_morse_matrix_structure( ) ) )
    {
      return false;
    }
  const int nb_lines = nb_lignes( );
  for ( int i=0; i<nb_lines; ++i )
    {
      int k0 = tab1_( i ) - 1;
      int k1 = tab1_( i + 1 ) - 1;
      for ( int k=k0; k<k1; ++k )
        {
          int j = tab2_( k ) - 1;
          if  ( j < i )
            {
              Cerr << "( j < i ) : line index : " << i << " and column index " << j << finl;
              return false;
            }
        }
    }
  return true;
}
References Cerr, Matrice_Morse::check_sorted_morse_matrix_structure(), finl, Matrice_Morse::nb_lignes(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
Referenced by Matrix_tools::add_symmetric_scaled_matrices().
check_symmetric_morse_matrix_structure()
bool Matrice_Morse_Sym::check_symmetric_morse_matrix_structure (void) const
Definition at line 1081 of file Matrice_Morse_Sym.cpp.
{
  if ( ! ( check_morse_matrix_structure( ) ) )
    {
      Cerr << "Invalid morse structure" << finl;
      return false;
    }
  const int nb_lines = nb_lignes( );
  for ( int i=0; i<nb_lines; ++i )
    {
      int k0 = tab1_( i ) - 1;
      int k1 = tab1_( i + 1 ) - 1;
      for ( int k=k0; k<k1; ++k )
        {
          int j = tab2_( k ) - 1;
          if  ( j < i )
            {
              Cerr << "( j < i ) : line index : " << i << " and column index " << j << finl;
              return false;
            }
        }
    }
  return true;
}
References Cerr, Matrice_Morse::check_morse_matrix_structure(), finl, Matrice_Morse::nb_lignes(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
Referenced by assert_check_sorted_symmetric_morse_matrix_structure(), and assert_check_symmetric_morse_matrix_structure().
compacte()
void Matrice_Morse_Sym::compacte (int elim_coeff_nul = 0)
Suppression des doublons
on ordonne tab2;
Verification de la diagonale: tous ses elements doivent etre stockes.
Definition at line 919 of file Matrice_Morse_Sym.cpp.
{
  Matrice_Morse::compacte(elim_coeff_nul);
// Verification si tous les elements de la diagonale sont bien stockes
  int n=nb_lignes();
  int elements_diagonaux_non_stockes=0;
  int size_tab2_ = tab2_.size_array();
  for (int i=0; i<n; i++)
    {
      int k=tab1_(i)-1;
      if (k>=size_tab2_ || i!=tab2_(k)-1)
        {
          elements_diagonaux_non_stockes++;
// Cerr << "Probleme rencontre dans une Matrice_Morse_Sym:" << finl;
// Cerr << "La ligne "<<i<<" n'a pas sa diagonale correctement stockee." << finl;
// Cerr << "Les elements diagonaux meme nuls doivent etre stockes dans une Mat_Morse_Sym TRUST." << finl;
        }
    }
  if (elements_diagonaux_non_stockes)
    {
// On resize
      int nnz=size_tab2_+elements_diagonaux_non_stockes;
      tab2_.resize(nnz);
      coeff_.resize(nnz);
// On change la matrice en partant de la fin
      for (int i=n-1; i>=0; i--)
        {
// On copie en decalant
          int k1=tab1_(i)-1;
          int k2=tab1_(i+1)-1;
          for (int j=k2-1; j>=k1; j--)
            {
              tab2_(j+elements_diagonaux_non_stockes)=tab2_(j);
              coeff_(j+elements_diagonaux_non_stockes)=coeff_(j);
            }
          tab1_(i+1)+=elements_diagonaux_non_stockes;
          if (k1>=size_tab2_ || i!=tab2_(k1)-1)
            {
// On insere l'element diagonal nul manquant
              elements_diagonaux_non_stockes--;
              tab2_(k1+elements_diagonaux_non_stockes)=i+1;
              coeff_(k1+elements_diagonaux_non_stockes)=0.;
            }
        }
      assert(elements_diagonaux_non_stockes==0);
    }
  morse_matrix_structure_has_changed_=1;
}
References Matrice_Morse::coeff_, Matrice_Morse::compacte(), Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::nb_lignes(), TRUSTVect< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::size_array(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
Referenced by assembler(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Matrice_Morse_Sym(), and operator=().
cree_instance()
Objet_U * Matrice_Morse_Sym::cree_instance () static
Definition at line 24 of file Matrice_Morse_Sym.cpp.
duplique()
int Matrice_Morse_Sym::duplique () const override virtual
Reimplemented from Matrice_Morse.
Definition at line 24 of file Matrice_Morse_Sym.cpp.
get_info()
const Type_info * Matrice_Morse_Sym::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Matrice_Morse.
Definition at line 24 of file Matrice_Morse_Sym.cpp.
get_stencil()
void Matrice_Morse_Sym::get_stencil (IntTab & stencil) const override virtual
Reimplemented from Matrice_Morse.
Definition at line 672 of file Matrice_Morse_Sym.cpp.
{
  assert_check_symmetric_morse_matrix_structure( );
  IntTab symmetric_stencil;
  get_symmetric_stencil( symmetric_stencil );
  Matrice_Sym::unsymmetrize_stencil( nb_lignes( ),
                                     symmetric_stencil,
                                     stencil );
}
References assert_check_symmetric_morse_matrix_structure(), get_symmetric_stencil(), Matrice_Morse::nb_lignes(), and Matrice_Sym::unsymmetrize_stencil().
get_stencil_and_coefficients()
void Matrice_Morse_Sym::get_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const override virtual
Reimplemented from Matrice_Morse.
Definition at line 722 of file Matrice_Morse_Sym.cpp.
{
  assert_check_symmetric_morse_matrix_structure( );
  IntTab symmetric_stencil;
  ArrOfDouble symmetric_coefficients;
  get_symmetric_stencil_and_coefficients( symmetric_stencil, symmetric_coefficients );
  Matrice_Sym::unsymmetrize_stencil_and_coefficients( nb_lignes( ),
                                                      symmetric_stencil,
                                                      symmetric_coefficients,
                                                      stencil,
                                                      coefficients );
}
References assert_check_symmetric_morse_matrix_structure(), get_symmetric_stencil_and_coefficients(), Matrice_Morse::nb_lignes(), and Matrice_Sym::unsymmetrize_stencil_and_coefficients().
get_symmetric_stencil()
void Matrice_Morse_Sym::get_symmetric_stencil (IntTab & stencil) const override virtual
Reimplemented from Matrice_Base.
Definition at line 684 of file Matrice_Morse_Sym.cpp.
{
  assert_check_symmetric_morse_matrix_structure( );
  stencil.resize( 0, 2 );
  stencil.set_smart_resize( 1 );
  ArrOfInt tmp;
  tmp.set_smart_resize( 1 );
  const int nb_lines = nb_lignes( );
  for ( int i=0; i<nb_lines; ++i )
    {
      int k0 = tab1_( i ) - 1;
      int k1 = tab1_( i + 1 ) - 1;
      int size = k1 - k0;
      tmp.resize_array( 0 );
      tmp.resize_array( size );
      for ( int k=0; k<size; ++k )
        {
          tmp[ k ] = tab2_( k + k0 ) - 1;
        }
      tmp.ordonne_array( );
      for ( int k=0; k<size; ++k )
        {
          stencil.append_line( i, tmp[ k ] );
        }
    }
  const int new_size = stencil.dimension( 0 );
  stencil.set_smart_resize( 0 );
  stencil.resize( new_size, 2 );
}
References TRUSTTab< _TYPE_ >::append_line(), assert_check_symmetric_morse_matrix_structure(), TRUSTTab< _TYPE_ >::dimension(), Matrice_Morse::nb_lignes(), TRUSTArray< _TYPE_ >::ordonne_array(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::set_smart_resize(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
Referenced by get_stencil(), and Matrice_Base::get_symmetric_stencil().
get_symmetric_stencil_and_coefficients()
void Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const override virtual
Reimplemented from Matrice_Base.
Definition at line 739 of file Matrice_Morse_Sym.cpp.
{
  assert_check_symmetric_morse_matrix_structure( );
  stencil.resize( 0, 2 );
  stencil.set_smart_resize( 1 );
  coefficients.resize( 0 );
  coefficients.set_smart_resize( 1 );
  IntTab tmp1(0);
  tmp1.set_smart_resize( 1 );
  ArrOfDouble tmp2;
  tmp2.set_smart_resize( 1 );
  ArrOfInt index;
  index.set_smart_resize( 1 );
  const int nb_lines = nb_lignes( );
  for ( int i=0; i<nb_lines; ++i )
    {
      int k0   = tab1_( i ) - 1;
      int k1   = tab1_( i + 1 ) - 1;
      int size = k1 - k0;
      index.resize_array( 0 );
      tmp1.resize( 0 );
      tmp1.resize( size );
      tmp2.resize_array( 0 );
      tmp2.resize_array( size );
      for ( int k=0; k<size; ++k )
        {
          tmp1( k ) = tab2_( k + k0 ) - 1;
          tmp2[ k ] = coeff_( k + k0 );
        }
      tri_lexicographique_tableau_indirect( tmp1, index );
      for ( int k=0; k<size; ++k )
        {
          int l = index[ k ];
          stencil.append_line( i, tmp1[ l ] );
          coefficients.append_array( tmp2[ l ] );
        }
    }
  const int new_size = stencil.dimension( 0 );
  assert( coefficients.size_array( ) == new_size );
  stencil.set_smart_resize( 0 );
  stencil.resize( new_size, 2 );
  coefficients.set_smart_resize( 0 );
  coefficients.resize_array( new_size );
}
References TRUSTArray< _TYPE_ >::append_array(), TRUSTTab< _TYPE_ >::append_line(), assert_check_symmetric_morse_matrix_structure(), Matrice_Morse::coeff_, TRUSTTab< _TYPE_ >::dimension(), Matrice_Morse::nb_lignes(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), Matrice_Morse::tab1_, Matrice_Morse::tab2_, and tri_lexicographique_tableau_indirect().
Referenced by get_stencil_and_coefficients(), and Matrice_Base::get_symmetric_stencil_and_coefficients().
imprimer_formatte()
Sortie & Matrice_Morse_Sym::imprimer_formatte (Sortie & s) const override virtual
Reimplemented from Matrice_Morse.
Definition at line 902 of file Matrice_Morse_Sym.cpp.
{
  return Matrice_Morse::imprimer_formatte(s, 1);
}
References Matrice_Morse::imprimer_formatte().
Referenced by Assembleur_P_EF::assembler_mat(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Solv_Cholesky::Fact_Cholesky(), and Op_Diff_RotRot::tester().
info()
const Type_info * Matrice_Morse_Sym::info () static
Definition at line 24 of file Matrice_Morse_Sym.cpp.
inverse() [1/2]
int Matrice_Morse_Sym::inverse (const DoubleVect & secmem, DoubleVect & solution, double coeff_seuil) const override virtual
Calcule la solution du systeme lineaire: A * solution = secmem.
La methode utilisee est GMRES preconditionnee avec ILUT.
ATTENTION: cette methode n'a vraisemblablement jamais ete testee en parallele.
Returns
int
Signification: renvoie toujours 1
Contraintes:
< On ne calcul L et U que si prems =1
< nombre de termes ajouter dans L et U
< ordre de la matrice
< degre de l'espace de Krilov
< tableau pour L et U
< tableau pour L et U
< tableau pour L et U
< tableau de travail pour pgmres DoubleVect Resini(nn);
< niveau d'erreur
< nombre de termes non nuls dans LU
< filtrage des coefficents de L U
< tableau de travail pour ilut DoubleVect wl(nn); // tableau de travail pour ilut
< tableau de travail pour ilut IntVect jwu(nn); // tableau de travail pour ilut IntVect jwl(nn); // tableau de travail pour ilut coeff_[0]*=2.0; // pour rendre A non singuliere!
< fichier de sortie
Reimplemented from Matrice_Morse.
Definition at line 886 of file Matrice_Morse_Sym.cpp.
{
  Cerr << "Not coded." << finl;
  exit();
  return 0;
}
References Cerr, Process::exit(), and finl.
inverse() [2/2]
int Matrice_Morse_Sym::inverse (const DoubleVect & secmem, DoubleVect & solution, double coeff_seuil, int max_iter) const override virtual
Reimplemented from Matrice_Morse.
Definition at line 894 of file Matrice_Morse_Sym.cpp.
{
  Cerr << "Not coded." << finl;
  exit();
  return 0;
}
References Cerr, Process::exit(), and finl.
isLU()
int Matrice_Morse_Sym::isLU () const inline private
Definition at line 97 of file Matrice_Morse_Sym.h.
{ return 0; }
matrice_renumerotee() [1/2]
Matrice & Matrice_Morse_Sym::matrice_renumerotee () inline
Renvoie la matrice renumerotee.
Definition at line 84 of file Matrice_Morse_Sym.h.
References matrice_renumerotee_.
Referenced by Solv_Cholesky::Cholesky().
matrice_renumerotee() [2/2]
Matrice & Matrice_Morse_Sym::matrice_renumerotee () const inline
Renvoie la matrice renumerotee.
Definition at line 85 of file Matrice_Morse_Sym.h.
References matrice_renumerotee_.
multvect_et_prodscal()
double Matrice_Morse_Sym::multvect_et_prodscal (const DoubleVect & x, DoubleVect & resu) const virtual
< La diagonale meme nulle doit etre stockee dans une Mat_Morse_Sym
Definition at line 257 of file Matrice_Morse_Sym.cpp.
{
  assert_check_symmetric_morse_matrix_structure( );
  assert(x.size_totale() == nb_lignes() || x.size() == nb_lignes());
  assert(resu.size_totale() == nb_lignes() || resu.size() == nb_lignes());
  assert(m_ <= x.size_totale());
  double prod_scal_local = 0.;
  operator_egal(resu, 0.);
  const int fin = nb_lignes() + 1;
  {
    const double * thecoef = get_coeff().addr() - 1;
    const double * xx = x.addr() - 1;
    double * res = resu.addr() - 1;
    const int * index1 = get_tab1().addr() - 1;
    const int * index2 = get_tab2().addr() - 1;
#ifdef COMPILER_BLRTS_XLC
#pragma disjoint (*coef, *xx, *res)
#endif
    int i;
    for (i = 1; i < fin; i++)
      {
        int j = index1[i];
        int j_next= index1[i+1];
// int ncoeffs = j_next - j;
        assert(i==index2[j]); //!< La diagonale meme nulle doit etre stockee dans une Mat_Morse_Sym
        double xi = xx[i];
        double resu_tmp = res[i] + thecoef[j] * xi;
        j++;
        for (; j < j_next; j++)
          {
            int nj     = index2[j];
            double coef_j = thecoef[j];
            double xn     = xx[nj];
            resu_tmp   += coef_j * xn;
            res[nj] += coef_j * xi;
          }
        res[i] = resu_tmp;
        prod_scal_local += resu_tmp * xi;
      }
  }
  return prod_scal_local;
}
References TRUSTArray< _TYPE_ >::addr(), assert_check_symmetric_morse_matrix_structure(), Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::m_, Matrice_Morse::nb_lignes(), operator_egal(), TRUSTVect< _TYPE_ >::size(), and TRUSTVect< _TYPE_ >::size_totale().
Referenced by Solv_GCP::resoudre_().
operator*=()
Matrice_Morse_Sym & Matrice_Morse_Sym::operator*= (double x)
NE FAIT RIEN : NON CODE.
Returns
Matrice_Morse_Sym
Signification:
Contraintes:
Definition at line 661 of file Matrice_Morse_Sym.cpp.
{
  scale( x );
  return(*this);
}
References scale().
operator-()
Matrice_Morse_Sym Matrice_Morse_Sym::operator- () const
Operateur de negation unaire,
renvoie l'opposee de la matrice: - A.
Appelle operator*(const Matrice_Morse_Sym&,double)
Definition at line 816 of file Matrice_Morse_Sym.cpp.
{
  return((*this)*(-1));
}
operator=() [1/3]
Matrice_Morse_Sym & Matrice_Morse_Sym::operator= (const Matrice & A)
Definition at line 165 of file Matrice_Morse_Sym.cpp.
{
  const Matrice_Base& A_base=A.valeur();
  if(sub_type(Matrice_Morse_Sym, A_base))
    *this=ref_cast(Matrice_Morse_Sym, A_base);
  else if(sub_type(Matrice_Morse, A_base))
    *this=ref_cast(Matrice_Morse, A_base);
  morse_matrix_structure_has_changed_=1;
  return *this;
}
References Matrice_Morse::morse_matrix_structure_has_changed_, ref_cast, sub_type, and Deriv_Matrice_Base::valeur().
operator=() [2/3]
Matrice_Morse_Sym & Matrice_Morse_Sym::operator= (const Matrice_Morse & A)
Definition at line 152 of file Matrice_Morse_Sym.cpp.
{
  tab1_=A.get_tab1();
  tab2_=A.get_tab2();
  coeff_=A.get_coeff();
  m_=A.nb_colonnes();
  symetrique_=A.get_symmetric();
  partie_sup(A);
  compacte();
  morse_matrix_structure_has_changed_=1;
  is_stencil_up_to_date_=A.is_stencil_up_to_date();
  return *this;
}
References Matrice_Morse::coeff_, compacte(), Matrice_Morse::get_coeff(), Matrice_Morse::get_symmetric(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Base::is_stencil_up_to_date(), Matrice_Base::is_stencil_up_to_date_, Matrice_Morse::m_, Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::nb_colonnes(), Matrice_Morse::partie_sup(), Matrice_Morse::symetrique_, Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
operator=() [3/3]
Matrice_Morse_Sym & Matrice_Morse_Sym::operator= (const Matrice_Morse_Sym & a)
Operateur d'affectatiob d'une Matrice_Morse_Sym
dans une Matrice_Morse_Sym.
Returns
Matrice_Morse_Sym&
Signification: le resultat de l'affectation (*this)
Contraintes:
Definition at line 868 of file Matrice_Morse_Sym.cpp.
{
  tab1_  =a.get_tab1();
  tab2_  =a.get_tab2();
  coeff_ =a.get_coeff();
  m_=a.nb_colonnes();
  set_est_definie(a.get_est_definie());
  morse_matrix_structure_has_changed_=1;
  is_stencil_up_to_date_ =  a.is_stencil_up_to_date() ;
  return(*this);
}
References Matrice_Morse::coeff_, Matrice_Morse::get_coeff(), Matrice_Sym::get_est_definie(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Base::is_stencil_up_to_date(), Matrice_Base::is_stencil_up_to_date_, Matrice_Morse::m_, Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::nb_colonnes(), Matrice_Sym::set_est_definie(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
permutation() [1/2]
ArrOfInt & Matrice_Morse_Sym::permutation () inline
Definition at line 86 of file Matrice_Morse_Sym.h.
{ return permutation_; }
References permutation_.
Referenced by Solv_Cholesky::Cholesky(), and renumerote().
permutation() [2/2]
ArrOfInt & Matrice_Morse_Sym::permutation () const inline
Definition at line 88 of file Matrice_Morse_Sym.h.
{ return permutation_; }
References permutation_.
permutation_inverse() [1/2]
ArrOfInt & Matrice_Morse_Sym::permutation_inverse () inline
Definition at line 87 of file Matrice_Morse_Sym.h.
{ return permutation_inverse_; }
References permutation_inverse_.
Referenced by Solv_Cholesky::Cholesky(), and renumerote().
permutation_inverse() [2/2]
ArrOfInt & Matrice_Morse_Sym::permutation_inverse () const inline
Definition at line 89 of file Matrice_Morse_Sym.h.
{ return permutation_inverse_; }
References permutation_inverse_.
printOn()
Sortie & Matrice_Morse_Sym::printOn (Sortie & s) const override protected virtual
Ecrit les trois tableaux de la structure de stockage
Morse sur un flot de sortie.
Returns
Sortie& s
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Matrice_Morse.
Definition at line 41 of file Matrice_Morse_Sym.cpp.
{
  s<<get_est_definie()<<finl;
  return  Matrice_Morse::printOn(s);
}
References finl, Matrice_Sym::get_est_definie(), and Matrice_Morse::printOn().
readOn()
Entree & Matrice_Morse_Sym::readOn (Entree & s) override protected virtual
NON CODE.
Returns
Entree& s
Signification: le flot d'entree
Contraintes:
Reimplemented from Matrice_Morse.
Definition at line 62 of file Matrice_Morse_Sym.cpp.
{
  int est_def;
  s>>est_def;
  set_est_definie(est_def);
  return Matrice_Morse::readOn(s) ;
}
References Matrice_Morse::readOn(), and Matrice_Sym::set_est_definie().
renumerote()
void Matrice_Morse_Sym::renumerote () const
Creation d'une matrice renumerotee pour reduire la largeur de bande.
Renumerotation d'une matrice afin de reduire la largeur de bande.
Definition at line 979 of file Matrice_Morse_Sym.cpp.
{
  Cerr << "Bandwidth of the matrix : " << largeur_de_bande() << finl;
  Cerr << "Renumbering the matrix ..." << finl;
// rovisoire chercher a reecrire
  const Matrice_Morse_Sym& matrice_initial = *this;
  ArrOfInt& tab_iperm = matrice_initial.permutation_inverse();
// transformation d une matrice morse symetrique en matrice morse
  Matrice_Morse matrice2(matrice_initial);
  Matrice_Morse matrice(matrice_initial);
  int mon_ordre = matrice.ordre();
// int i;
  matrice2.transpose(matrice);
  for (int i=0; i<mon_ordre; i++) matrice2(i, i) = 0.;
  matrice2 += matrice ;
// Matrice_Bande_Sym matrice_tmp;
// matrice_tmp.charger_coeff(matrice);
// Cout<<"avant renumerotation largeur de bande:"<<matrice_tmp.dim(0)<<finl;
// calcul de la permutation a effectuer
// int nnz = matrice2.coeff_.size();
  const int n = mon_ordre;
  const int* tab1tmp = matrice2.get_tab1().addr();
  const int* tab2tmp = matrice2.get_tab2().addr();
// const int nfirst=1;
  int init = 1;
  tab_iperm.resize_array(n);
  tab_iperm[0] = 1;
  int* masktmp  = new int[n];
  for (int i=0 ; i<n; i++ ) masktmp[i] = 1;
  const int* mask = (const int*) masktmp;
  const int maskval = 1;
// GF passage a n+1 pour permettre de faire du Cholesky sur 1 maillage 1xN
  int*  level = new int[n+1];
  int nlev;
// renumerotation des noeuds
// subroutine perphn(n,ja,ia,init,iperm,mask,maskval,nlev,riord,levels)
// SPARSKIT2/ORDERINGS/levset.f
  F77NAME(PERPHN)(&n, tab2tmp, tab1tmp, &init,  mask, &maskval,
                  &nlev, tab_iperm.addr(), level);
  delete []masktmp;
  delete []level;
  ArrOfInt tab_perm(n);
  for (int i=0 ; i<n; i++ ) tab_perm[tab_iperm[i] - 1] = i + 1;
  matrice2 = matrice;
  const double* a = matrice.get_coeff().addr();
  const int* ja = matrice.get_tab2().addr();
  const int* ia = matrice.get_tab1().addr();
  const double* tao = matrice2.get_coeff().addr();
  double* ao = (double*)tao;
  const  int* tjao = matrice2.get_tab2().addr();
  int* jao = (int*)tjao;
  const  int* tiao = matrice2.get_tab1().addr();
  int* iao = (int*)tiao;
  const int* perm = tab_perm.addr();
  const int* perm_inv = tab_iperm.addr();//normalement inutile
  const int job = 1;
// permutation de la matrice i.e. calcul de P A tP
// ici on ne permute que la partie supeieure
// subroutine dperm (nrow,a,ja,ia,ao,jao,iao,perm,qperm,job)
// SPARSKIT2/FORMATS/unary.f
  F77NAME(DPERM) (&n, a, ja, ia, ao, jao, iao, perm, perm_inv, &job);
  matrice.transpose(matrice2);
  for (int i=0; i<mon_ordre; i++) matrice2(i, i) = 0.;
  matrice2 += matrice ;
  matrice.partie_sup(matrice2);
  matrice_renumerotee_.typer("Matrice_Morse_Sym");
  ref_cast(Matrice_Morse_Sym,matrice_renumerotee_.valeur()) = matrice;
// Construction de permutation() rovisoire deja fait avec
  int size=permutation_inverse().size_array();
  permutation().resize_array(size);
  for(int i=0; i<size; i++)
    permutation()[permutation_inverse()[i]-1]=i+1;
  Cerr << "Bandwidth of the renumbered matrix : " << ref_cast(Matrice_Morse,matrice_renumerotee_.valeur()).largeur_de_bande() << finl;
  morse_matrix_structure_has_changed_=1;
}
References TRUSTArray< _TYPE_ >::addr(), Cerr, F77NAME, finl, Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::largeur_de_bande(), matrice_renumerotee_, Matrice_Morse::morse_matrix_structure_has_changed_, Matrice_Morse::ordre(), Matrice_Morse::partie_sup(), permutation(), permutation_inverse(), ref_cast, TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::size_array(), Matrice_Morse::transpose(), Deriv_::typer(), and Deriv_Matrice_Base::valeur().
Referenced by Solv_Cholesky::Cholesky().
scale()
void Matrice_Morse_Sym::scale (const double x) override virtual
Reimplemented from Matrice_Morse.
Definition at line 667 of file Matrice_Morse_Sym.cpp.
{
  coeff_ *= x;
}
References Matrice_Morse::coeff_.
Referenced by operator*=().
self_cast() [1/2]
const Matrice_Morse_Sym & Matrice_Morse_Sym::self_cast (const Objet_U & r) static
Definition at line 24 of file Matrice_Morse_Sym.cpp.
self_cast() [2/2]
Matrice_Morse_Sym & Matrice_Morse_Sym::self_cast (Objet_U & r) static
Definition at line 24 of file Matrice_Morse_Sym.cpp.
taille_memoire()
unsigned Matrice_Morse_Sym::taille_memoire () const override virtual
Reimplemented from Matrice_Morse.
Definition at line 24 of file Matrice_Morse_Sym.cpp.
Friends And Related Function Documentation
operator* [1/2]
Matrice_Morse_Sym operator* (const Matrice_Morse_Sym & , double) friend
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
Simple appel a operator*(double,const Matrice_Morse_Sym&) (qui est NON CODE)
Returns
Matrice_Morse_Sym
Signification: le resultat de l'appel sous-jacent
Contraintes:
Definition at line 641 of file Matrice_Morse_Sym.cpp.
{
  return(x*A);
}
operator* [2/2]
Matrice_Morse_Sym operator* (double , const Matrice_Morse_Sym &) friend
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
NE FAIT RIEN : NON CODE.
Returns
Matrice_Morse_Sym
Signification:
Contraintes:
Definition at line 612 of file Matrice_Morse_Sym.cpp.
{
  Matrice_Morse_Sym mat_res(A);
  mat_res.get_set_coeff()*=x;
  mat_res.morse_matrix_structure_has_changed_=1;
  return(mat_res);
}
operator+
Matrice_Morse_Sym operator+ (const Matrice_Morse_Sym & , const Matrice_Morse_Sym &) friend
Fonction (hors classe) amie de la classe Matrice_Morse_Sym
NE FAIT RIEN : NON CODE.
Returns
Matrice_Morse_Sym
Signification:
Contraintes:
Definition at line 466 of file Matrice_Morse_Sym.cpp.
{
// Il faut evidemment que les matrices soient de meme taille
  if (A.nb_lignes() != B.nb_lignes())
    {
      Cerr << "Error in Matrice_Morse_Sym::operator+" << finl;
      Cerr << "The 2 matrices must have the same dimension" << finl;
      Cerr << "The first matrix is of dimension: " << A.nb_lignes()<< finl;
      Cerr << "The second matrix is of dimension: " << B.nb_lignes()<< finl;
      Process::exit();
    }
  Matrice_Morse_Sym somme(A.nb_lignes(),A.nb_coeff()+B.nb_coeff());
  IntList colonnes_A_ligne_i,colonnes_B_ligne_i;
  int min_colonnes_A,min_colonnes_B,non_nuls_ligne_i;
  DoubleList coeffs_A_ligne_i,coeffs_B_ligne_i;
  double coeff_A,coeff_B;
// Pour s'assurer que compacte() va marcher
  for (int i=0; i<somme.get_coeff().size(); i++)
    somme.get_set_coeff()(i) = 0.;
// On va remplir tab2_ par ordre croissant de colonnes
  somme.get_set_tab1()(0) = 1;
  for (int i=0; i<A.nb_lignes(); i++) //boucle sur les lignes
    {
// Pour eviter les effets de bord
      if (!colonnes_A_ligne_i.est_vide()) colonnes_A_ligne_i.vide();
      if (!colonnes_B_ligne_i.est_vide()) colonnes_B_ligne_i.vide();
// Initialisation des colonnes_A et colonnes_B
// ATTENTION a la numerotation C++
      for (int j=0; j<A.get_tab1()(i+1)-A.get_tab1()(i); j++)
        {
          colonnes_A_ligne_i.add_if_not(A.get_tab2()(A.get_tab1()(i)+j-1));
          coeffs_A_ligne_i.add(A.get_coeff()(A.get_tab1()(i)+j-1));
        }//fin for
      for (int j=0; j<B.get_tab1()(i+1)-B.get_tab1()(i); j++)
        {
          colonnes_B_ligne_i.add_if_not(B.get_tab2()(B.get_tab1()(i)+j-1));
          coeffs_B_ligne_i.add(B.get_coeff()(B.get_tab1()(i)+j-1));
        }//fin for
// On initialise d'autres varibles
      non_nuls_ligne_i = 0;
// Debut de l'algorithme
      while (!colonnes_A_ligne_i.est_vide() || !colonnes_B_ligne_i.est_vide())
        {
// Si l'une des listes est vide et pas l'autre
          if (colonnes_A_ligne_i.est_vide() && !colonnes_B_ligne_i.est_vide())
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) =
                colonnes_B_ligne_i[0];
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) =
                coeffs_B_ligne_i[0] ;
              colonnes_B_ligne_i.suppr(colonnes_B_ligne_i[0]);
              coeffs_B_ligne_i.suppr(coeffs_B_ligne_i[0]);
              non_nuls_ligne_i++;
            }//fin if
          if (colonnes_B_ligne_i.est_vide() && !colonnes_A_ligne_i.est_vide())
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) =
                colonnes_A_ligne_i[0];
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) =
                coeffs_A_ligne_i[0];
              colonnes_A_ligne_i.suppr(colonnes_A_ligne_i[0]);
              coeffs_A_ligne_i.suppr(coeffs_A_ligne_i[0]);
              non_nuls_ligne_i++;
            }//fin if
// Aucune des deux listes n'est vide
          min_colonnes_A = colonnes_A_ligne_i[0];
          min_colonnes_B = colonnes_B_ligne_i[0];
          coeff_A = coeffs_A_ligne_i[0];
          coeff_B = coeffs_B_ligne_i[0];
          if (min_colonnes_A < min_colonnes_B)
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = min_colonnes_A;
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = coeff_A;
              colonnes_A_ligne_i.suppr(min_colonnes_A);
              coeffs_A_ligne_i.suppr(coeff_A);
              non_nuls_ligne_i++;
            }//fin if
          if (min_colonnes_B < min_colonnes_A)
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = min_colonnes_B;
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = coeff_B;
              colonnes_B_ligne_i.suppr(min_colonnes_B);
              coeffs_B_ligne_i.suppr(coeff_B);
              non_nuls_ligne_i++;
            }//fin if
          if (min_colonnes_A == min_colonnes_B)
            {
              somme.get_set_tab2()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = min_colonnes_A;
              somme.get_set_coeff()(somme.get_tab1()(i)+non_nuls_ligne_i-1) = coeff_A+coeff_B;
              colonnes_A_ligne_i.suppr(min_colonnes_A);
              colonnes_B_ligne_i.suppr(min_colonnes_B);
              coeffs_A_ligne_i.suppr(coeff_A);
              coeffs_B_ligne_i.suppr(coeff_B);
              non_nuls_ligne_i++;
            }//fin if
        }//!< fin while
      somme.get_set_tab1()(i+1) = somme.get_tab1()(i)+non_nuls_ligne_i;//?????
    }//!< fin for
  somme.compacte();
  somme.morse_matrix_structure_has_changed_=1;
  return somme;
}
Member Data Documentation
info_obj
const Type_info Matrice_Morse_Sym::info_obj static
Definition at line 39 of file Matrice_Morse_Sym.h.
matrice_renumerotee_
Matrice Matrice_Morse_Sym::matrice_renumerotee_ mutable private
Definition at line 100 of file Matrice_Morse_Sym.h.
Referenced by matrice_renumerotee(), and renumerote().
permutation_
ArrOfInt Matrice_Morse_Sym::permutation_ mutable private
Definition at line 98 of file Matrice_Morse_Sym.h.
Referenced by permutation().
permutation_inverse_
ArrOfInt Matrice_Morse_Sym::permutation_inverse_ mutable private
Definition at line 99 of file Matrice_Morse_Sym.h.
Referenced by permutation_inverse().
The documentation for this class was generated from the following files:
src/Kernel/Math/Matrices/Matrice_Morse_Sym.h
src/Kernel/Math/Matrices/Matrice_Morse_Sym.cpp