TRUST: Deriv_Champ_Generique_base Class Reference
Deriv_Champ_Generique_base Class Reference
#include <Champ_Generique.h>
Public Member Functions
~Deriv_Champ_Generique_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Champ_Generique_base ()
Deriv_Champ_Generique_base (const Deriv_Champ_Generique_base &)
const Champ_Generique_base & valeur () const
Champ_Generique_base & valeur ()
const Champ_Generique_base * operator-> () const
Champ_Generique_base * operator-> ()
const Deriv_Champ_Generique_base & operator= (const Champ_Generique_base &)
const Deriv_Champ_Generique_base & operator= (const Deriv_Champ_Generique_base &)
operator const Champ_Generique_base & () const
operator Champ_Generique_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Champ_Generique_base & self_cast (Objet_U &)
static const
Deriv_Champ_Generique_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Champ_Generique_base * pointeur_
Detailed Description
Definition at line 27 of file Champ_Generique.h.
Constructor & Destructor Documentation
Deriv_Champ_Generique_base::~Deriv_Champ_Generique_base ()
Definition at line 25 of file Champ_Generique.cpp.
Deriv_Champ_Generique_base::Deriv_Champ_Generique_base ()
Definition at line 25 of file Champ_Generique.cpp.
Deriv_Champ_Generique_base::Deriv_Champ_Generique_base (const Deriv_Champ_Generique_base & t)
Definition at line 25 of file Champ_Generique.cpp.
Member Function Documentation
Objet_U * Deriv_Champ_Generique_base::cree_instance () [static]
Reimplemented in Champ_Generique.
Definition at line 25 of file Champ_Generique.cpp.
int Deriv_Champ_Generique_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Champ_Generique.
Definition at line 25 of file Champ_Generique.cpp.
const Type_info * Deriv_Champ_Generique_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Champ_Generique.
Definition at line 25 of file Champ_Generique.cpp.
const Type_info & Deriv_Champ_Generique_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Champ_Generique.cpp.
const Type_info * Deriv_Champ_Generique_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Champ_Generique.
Definition at line 25 of file Champ_Generique.cpp.
Deriv_Champ_Generique_base::operator Champ_Generique_base & ()
Definition at line 25 of file Champ_Generique.cpp.
Deriv_Champ_Generique_base::operator const Champ_Generique_base & () const
Definition at line 25 of file Champ_Generique.cpp.
const Champ_Generique_base * Deriv_Champ_Generique_base::operator-> () const [inline]
Definition at line 27 of file Champ_Generique.h.
: public DERIV(Champ_Generique_base)
Champ_Generique_base * Deriv_Champ_Generique_base::operator-> () [inline]
Definition at line 27 of file Champ_Generique.h.
: public DERIV(Champ_Generique_base)
const Deriv_Champ_Generique_base & Deriv_Champ_Generique_base::operator= (const Deriv_Champ_Generique_base & t)
Definition at line 25 of file Champ_Generique.cpp.
const Deriv_Champ_Generique_base & Deriv_Champ_Generique_base::operator= (const Champ_Generique_base & t)
Definition at line 25 of file Champ_Generique.cpp.
Sortie & Deriv_Champ_Generique_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Champ_Generique.
Definition at line 25 of file Champ_Generique.cpp.
Entree & Deriv_Champ_Generique_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Champ_Generique.
Definition at line 25 of file Champ_Generique.cpp.
const Deriv_Champ_Generique_base & Deriv_Champ_Generique_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Champ_Generique.
Definition at line 25 of file Champ_Generique.cpp.
Deriv_Champ_Generique_base & Deriv_Champ_Generique_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Champ_Generique.
Definition at line 25 of file Champ_Generique.cpp.
void Deriv_Champ_Generique_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Champ_Generique.cpp.
unsigned Deriv_Champ_Generique_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Champ_Generique.
Definition at line 25 of file Champ_Generique.cpp.
const Champ_Generique_base & Deriv_Champ_Generique_base::valeur () const [inline]
Definition at line 27 of file Champ_Generique.h.
Referenced by Postraitement::complete_champ(), Postraitement::creer_champ_post_stat(), Postraitement::get_champ_post(), Champ_Generique_Predefini::get_source(), Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), and Champ_Generique_Predefini::nommer_source().
: public DERIV(Champ_Generique_base)
Champ_Generique_base & Deriv_Champ_Generique_base::valeur () [inline]
Definition at line 27 of file Champ_Generique.h.
: public DERIV(Champ_Generique_base)
Member Data Documentation
const Type_info Deriv_Champ_Generique_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Champ_Generique.
Definition at line 27 of file Champ_Generique.h.
Champ_Generique_base* Deriv_Champ_Generique_base::pointeur_ [private]
Definition at line 27 of file Champ_Generique.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_Generique.h
src/Kernel/Framework/Champ_Generique.cpp