TRUST: Terme_Source_CoviMAC_base Class Reference
Terme_Source_CoviMAC_base Class Reference
CoviMAC implementation of Source_base class.
#include <Terme_Source_CoviMAC_base.h>
Public Member Functions
Terme_Source_CoviMAC_base ()
~Terme_Source_CoviMAC_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Terme_Source_CoviMAC_base (const Iterateur_Source_CoviMAC_base &)
constructeur
int has_interface_blocs () const
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Terme_Source_CoviMAC_base & self_cast (Objet_U &)
static const
Terme_Source_CoviMAC_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Protected Attributes
Iterateur_Source_CoviMAC iter
Detailed Description
CoviMAC implementation of Source_base class.
Definition at line 38 of file Terme_Source_CoviMAC_base.h.
Constructor & Destructor Documentation
Terme_Source_CoviMAC_base::Terme_Source_CoviMAC_base ()
Definition at line 25 of file Terme_Source_CoviMAC_base.cpp.
Terme_Source_CoviMAC_base::~Terme_Source_CoviMAC_base ()
Definition at line 25 of file Terme_Source_CoviMAC_base.cpp.
Terme_Source_CoviMAC_base::Terme_Source_CoviMAC_base (const Iterateur_Source_CoviMAC_base & iter_base) [inline]
constructeur
Definition at line 65 of file Terme_Source_CoviMAC_base.h.
                                                                                                          :
  iter(iter_base)
{}
Member Function Documentation
void Terme_Source_CoviMAC_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) [inline, virtual]
Reimplemented from Source_base.
void Terme_Source_CoviMAC_base::completer () [virtual]
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
Definition at line 45 of file Terme_Source_CoviMAC_base.cpp.
References Iterateur_Source_CoviMAC::associer(), Iterateur_Source_CoviMAC::completer_(), and iter.
{
  Source_base::completer();
  iter.associer(*this);
  iter.completer_();
}
void Terme_Source_CoviMAC_base::dimensionner_blocs (matrices_t matrices) const [inline, virtual]
Reimplemented from Source_base.
Definition at line 50 of file Terme_Source_CoviMAC_base.h.
{}) const { }; //rien
virtual int Terme_Source_CoviMAC_base::duplique () const [pure virtual]
Implements Source_base.
Implemented in Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, and Terme_Source_Constituant_CoviMAC_Elem.
const Type_info * Terme_Source_CoviMAC_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, and Terme_Source_Constituant_CoviMAC_Elem.
Definition at line 25 of file Terme_Source_CoviMAC_base.cpp.
int Terme_Source_CoviMAC_base::has_interface_blocs () const [inline, virtual]
Reimplemented from Source_base.
Definition at line 46 of file Terme_Source_CoviMAC_base.h.
  {
    return 1;
  };
const Type_info * Terme_Source_CoviMAC_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, and Terme_Source_Constituant_CoviMAC_Elem.
Definition at line 25 of file Terme_Source_CoviMAC_base.cpp.
Sortie & Terme_Source_CoviMAC_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, and Terme_Source_Constituant_CoviMAC_Elem.
Definition at line 31 of file Terme_Source_CoviMAC_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Terme_Source_CoviMAC_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, and Terme_Source_Constituant_CoviMAC_Elem.
Definition at line 40 of file Terme_Source_CoviMAC_base.cpp.
{
  return s ;
}
const Terme_Source_CoviMAC_base & Terme_Source_CoviMAC_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, and Terme_Source_Constituant_CoviMAC_Elem.
Definition at line 25 of file Terme_Source_CoviMAC_base.cpp.
Terme_Source_CoviMAC_base & Terme_Source_CoviMAC_base::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, and Terme_Source_Constituant_CoviMAC_Elem.
Definition at line 25 of file Terme_Source_CoviMAC_base.cpp.
Member Data Documentation
const Type_info Terme_Source_CoviMAC_base::info_obj [static]
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, and Terme_Source_Constituant_CoviMAC_Elem.
Definition at line 41 of file Terme_Source_CoviMAC_base.h.
Iterateur_Source_CoviMAC Terme_Source_CoviMAC_base::iter [protected]
Definition at line 56 of file Terme_Source_CoviMAC_base.h.
Referenced by Terme_Source_Constituant_CoviMAC_Elem::associer_pb(), Terme_Puissance_Thermique_CoviMAC_Elem::associer_pb(), Terme_Source_Constituant_CoviMAC_Elem::associer_zones(), Terme_Puissance_Thermique_CoviMAC_Elem::associer_zones(), Terme_Puissance_Thermique_CoviMAC_base::associer_zones(), and completer().
The documentation for this class was generated from the following files:
src/CoviMAC/Sources/Terme_Source_CoviMAC_base.h
src/CoviMAC/Sources/Terme_Source_CoviMAC_base.cpp