TRUST: PE_Groups Class Reference
PE_Groups Class Reference
:
Cette classe regroupe des fonctions permettant la creation, la
destruction et le changement du groupe de processeurs actif.
La creation du groupe principal doit etre dans le MAIN.cpp
et il faut initialiser PE_Groups en lui donnant le groupe principal.
Les autres groupes crees seront du meme type.
Voir aussi la class Comm_Group
#include <PE_Groups.h>
Static Public Member Functions
static const Comm_Group & current_group ()
renvoie une reference au groupe de processeurs actif courant
static void create_group (const ArrOfInt &liste_pe, Deriv_Comm_Group &group, int force_Comm_Group_NoParallel=0)
Creation d'un nouveau groupe de processeurs
(utilisation possible n'importe ou dans le code)
Il faut l'appeler simultanement sur tous les processeurs du groupe current_group()
avec le meme tableau liste_pe. liste_pe est la liste des rangs dans le groupe
courant des processeurs que l'on veut inclure dans le groupe. Le premier de la
liste sera le maitre du groupe. La liste ne doit pas comporter de doublon et
doit contenir au moins un processeur.
La methode type et initialize l'objet group.
Il faut ensuite appeler enter_group() et exit_group() (autant de fois qu'on veut)
static int enter_group (const Comm_Group &group)
Si le processeur local appartient au groupe, le groupe courant
pour ce processeur devient "group" et on renvoie 1, sinon on renvoie 0.
Une reference au groupe actuel est sauvegardee et sera restauree quand on
appellera exit_group().
Cette methode doit etre appelee simultanement sur tous les processeurs
du groupe "group".
Attention: a chaque enter_group() doit correspondre un exit_group().
Cependant, il n'est pas interdit d'entrer plusieurs fois de suite dans le
meme groupe, ni d'entrer dans un groupe plus grand que le groupe actuel.
Exemple : group1 et group2 forment une partition du groupe_TRUST()
int sync_point(int x)
{
PE_Groups::enter_group(groupe_TRUST());
int i = mp_sum(x);
PE_Groups::exit_group();
return i;
}
if (PE_Groups::enter_group(group1)) {
s1 = mp_sum(x); // Somme sur le groupe 2
// Point de synchro avec l'autre groupe:
s_all = sync_point(x);
} else if (PE_Groups::enter_group(group2)) {
s2 = mp_sum(x);
// Point de synchro avec l'autre groupe:
s_all = sync_point(x);
} else {
Cerr << "Error: processor " << me() << " is not within a subgroup.";
exit();
}
PE_Groups::exit_group(); // Sort du sous-groupe.
static void exit_group ()
Retourne dans le groupe ou l'on etait avant le dernier
enter_group() reussi (dont le resultat a ete 1).
Cette methode doit etre appelee simultanement sur tous les processeurs
du current_group() actif juste avant exit_group()).
static const int & get_nb_groups ()
static int rank_translate (int rank, const Comm_Group &group, const Comm_Group &dest_group=current_group())
Calcule le rank dans le groupe courant du processeur de rang "rank" dans le "group".
Il faut que 0 <= rank < group.nproc()
Si le processeur en question n'appartient pas au groupe courant, renvoie -1.
static const Comm_Group & groupe_TRUST ()
Renvoie une reference au groupe de tous les processeurs TRUST.
static void initialize (const Comm_Group &groupe_trio_u)
Methode a appeler au debut de l'execution (MAIN.cpp)
Elle initialise current_group() avec groupe_trio_u.
static void finalize ()
Methode a appeler en fin d'execution, une fois qu'on est revenu
dans le groupe_TRUST() et juste avant de detruire de Comm_Group
principal.
Static Private Member Functions
static int check_current_group ()
Static Private Attributes
static const Comm_Group * current_group_ = 0
Detailed Description
:
Cette classe regroupe des fonctions permettant la creation, la
destruction et le changement du groupe de processeurs actif.
La creation du groupe principal doit etre dans le MAIN.cpp
et il faut initialiser PE_Groups en lui donnant le groupe principal.
Les autres groupes crees seront du meme type.
Voir aussi la class Comm_Group
Definition at line 29 of file PE_Groups.h.
Member Function Documentation
check_current_group()
int PE_Groups::check_current_group () static private
Definition at line 28 of file PE_Groups.cpp.
{
  assert(ngroups > 0);
  assert(current_group_ == &(groups[ngroups-1].valeur()));
  return 1;
}
References current_group_, groups, ngroups, and valeur().
Referenced by current_group().
create_group()
void PE_Groups::create_group (const ArrOfInt & liste_pe, Deriv_Comm_Group & group, int force_Comm_Group_NoParallel = 0) static
Creation d'un nouveau groupe de processeurs
(utilisation possible n'importe ou dans le code)
Il faut l'appeler simultanement sur tous les processeurs du groupe current_group()
avec le meme tableau liste_pe. liste_pe est la liste des rangs dans le groupe
courant des processeurs que l'on veut inclure dans le groupe. Le premier de la
liste sera le maitre du groupe. La liste ne doit pas comporter de doublon et
doit contenir au moins un processeur.
La methode type et initialize l'objet group.
Il faut ensuite appeler enter_group() et exit_group() (autant de fois qu'on veut)
Definition at line 44 of file PE_Groups.cpp.
{
  if (liste_pe.size_array()==1 && force_Comm_Group_NoParallel)
    {
// On cree un groupe non parallele si c'est possible et si c'est impose
      group.typer("Comm_Group_NoParallel");
    }
  else
    {
// On cree un groupe du meme type que le groupe_TRUST
      group.typer(groups[0].valeur().que_suis_je());
    }
  group.valeur().init_group(liste_pe);
}
References groups, Comm_Group::init_group(), TRUSTArray< _TYPE_ >::size_array(), and valeur().
Referenced by Execute_parallel::interpreter(), latatoother::interpreter(), and Debog_Pb::read_geometry_data().
current_group()
const Comm_Group & PE_Groups::current_group () inline static
renvoie une reference au groupe de processeurs actif courant
Definition at line 50 of file PE_Groups.h.
{
  assert(check_current_group());
  return *current_group_;
}
References check_current_group(), and current_group_.
Referenced by Process::barrier(), Schema_Comm::begin_comm(), Solv_Petsc::create_solver(), Schema_Comm::echange_messages(), Schema_Comm::echange_taille(), Schema_Comm::end_comm(), enter_group(), envoyer_all_to_all(), envoyer_all_to_all_(), envoyer_array(), envoyer_broadcast_array(), envoyer_broadcast_buffered_(), envoyer_buffered_(), Schema_Comm_Vecteurs::exchange(), exit_group(), mon_main::finalize(), Comm_Group::init_group(), Comm_Group_MPI::init_group(), is_parallel_object(), Process::je_suis_maitre(), Process::me(), Process::mp_and(), mp_collective_op(), Process::mp_max(), Process::mp_min(), mp_operations_commun_(), Process::mp_sum(), mpsum_multiple(), Process::nproc(), Schema_Comm::operator=(), EcrFicPartageMPIIO::ouvrir(), recevoir_array(), recevoir_buffered_(), reverse_send_recv_pe_list(), Schema_Comm::Schema_Comm(), Schema_Comm::set_group(), Schema_Comm::set_send_recv_pe_list(), and EcrFicPartage::syncfile().
enter_group()
int PE_Groups::enter_group (const Comm_Group & group) static
Si le processeur local appartient au groupe, le groupe courant
pour ce processeur devient "group" et on renvoie 1, sinon on renvoie 0.
Une reference au groupe actuel est sauvegardee et sera restauree quand on
appellera exit_group().
Cette methode doit etre appelee simultanement sur tous les processeurs
du groupe "group".
Attention: a chaque enter_group() doit correspondre un exit_group().
Cependant, il n'est pas interdit d'entrer plusieurs fois de suite dans le
meme groupe, ni d'entrer dans un groupe plus grand que le groupe actuel.
Exemple : group1 et group2 forment une partition du groupe_TRUST()
int sync_point(int x)
{
PE_Groups::enter_group(groupe_TRUST());
int i = mp_sum(x);
PE_Groups::exit_group();
return i;
}
if (PE_Groups::enter_group(group1)) {
s1 = mp_sum(x); // Somme sur le groupe 2
// Point de synchro avec l'autre groupe:
s_all = sync_point(x);
} else if (PE_Groups::enter_group(group2)) {
s2 = mp_sum(x);
// Point de synchro avec l'autre groupe:
s_all = sync_point(x);
} else {
Cerr << "Error: processor " << me() << " is not within a subgroup.";
exit();
}
PE_Groups::exit_group(); // Sort du sous-groupe.
Definition at line 90 of file PE_Groups.cpp.
{
  assert(&group != &current_group());
  if (ngroups >= max_ngroups-1)
    {
      Cerr << "Comm_Group::enter_group : fatal, too many groups" << finl;
      Process::exit();
    }
  int my_rank_in_group = rank_translate(current_group().rank(), current_group(), group);
  if (my_rank_in_group >= 0)
    {
// Sauvegarde du pointeur sur le groupe actuel et changement du
// current_group() :
      groups[ngroups] = group;
      current_group_ = &group;
      ngroups++;
// Attention, on a change de current_group() !
// On verifie que tous les processeurs du nouveau groupe sont la:
      if (Comm_Group::check_enabled())
        current_group().barrier(0);
      return 1;
    }
  else
    {
      return 0;
    }
}
References Comm_Group::barrier(), Cerr, Comm_Group::check_enabled(), current_group(), current_group_, Process::exit(), finl, groups, max_ngroups, ngroups, and rank_translate().
Referenced by Execute_parallel::interpreter(), latatoother::interpreter(), and Debog_Pb::read_geometry_data().
exit_group()
void PE_Groups::exit_group () static
Retourne dans le groupe ou l'on etait avant le dernier
enter_group() reussi (dont le resultat a ete 1).
Cette methode doit etre appelee simultanement sur tous les processeurs
du current_group() actif juste avant exit_group()).
Definition at line 124 of file PE_Groups.cpp.
{
  if (Comm_Group::check_enabled())
    current_group().barrier(0);
  if (ngroups <= 1)
    {
      Cerr << "Comm_Group::exit_group() error : trying to exit from TRUST main group." << finl;
      Process::exit();
    }
  ngroups--;
  current_group_ = &(groups[ngroups-1].valeur());
}
References Comm_Group::barrier(), Cerr, Comm_Group::check_enabled(), current_group(), current_group_, Process::exit(), finl, groups, ngroups, and Ref_Comm_Group::valeur().
Referenced by Execute_parallel::interpreter(), latatoother::interpreter(), and Debog_Pb::read_geometry_data().
finalize()
void PE_Groups::finalize () static
Methode a appeler en fin d'execution, une fois qu'on est revenu
dans le groupe_TRUST() et juste avant de detruire de Comm_Group
principal.
Definition at line 173 of file PE_Groups.cpp.
{
  assert(ngroups == 1);
  groups[0].reset();
  ngroups = 0;
  current_group_ = 0;
}
References current_group_, groups, ngroups, and Ref_::reset().
Referenced by Process::exit(), and mon_main::~mon_main().
get_nb_groups()
const int & PE_Groups::get_nb_groups () static
Definition at line 180 of file PE_Groups.cpp.
{
  return ngroups ;
}
References ngroups.
Referenced by Solv_Petsc::create_solver(), and get_Cerr().
groupe_TRUST()
const Comm_Group & PE_Groups::groupe_TRUST () static
Renvoie une reference au groupe de tous les processeurs TRUST.
< Initialized ?
Definition at line 152 of file PE_Groups.cpp.
{
  assert(ngroups > 0); //!< Initialized ?
  return groups[0].valeur();
}
References groups, ngroups, and Ref_Comm_Group::valeur().
Referenced by build_medfield(), Process::exit(), Schema_Comm_Vecteurs_Static_Data::init(), Comm_Group::init_group(), Postraitement_lata::postraiter(), and Postraitement_lata::postraiter_liste_champs().
initialize()
void PE_Groups::initialize (const Comm_Group & groupe_trio_u) static
Methode a appeler au debut de l'execution (MAIN.cpp)
Elle initialise current_group() avec groupe_trio_u.
Definition at line 161 of file PE_Groups.cpp.
{
  assert(ngroups == 0);
  ngroups = 1;
  groups[0] = groupe_trio_u;
  current_group_ = &groupe_trio_u;
}
References current_group_, groups, and ngroups.
Referenced by mon_main::init_parallel().
rank_translate()
int PE_Groups::rank_translate (int rank, const Comm_Group & group, const Comm_Group & dest_group = current_group()) static
Calcule le rank dans le groupe courant du processeur de rang "rank" dans le "group".
Il faut que 0 <= rank < group.nproc()
Si le processeur en question n'appartient pas au groupe courant, renvoie -1.
Definition at line 142 of file PE_Groups.cpp.
{
  const int world_rank = group.world_ranks_[rank];
  const int local_rank = dest_group.local_ranks_[world_rank];
  return local_rank;
}
References Comm_Group::local_ranks_, and Comm_Group::world_ranks_.
Referenced by enter_group().
Member Data Documentation
current_group_
const Comm_Group * PE_Groups::current_group_ = 0 static private
Definition at line 46 of file PE_Groups.h.
Referenced by check_current_group(), current_group(), enter_group(), exit_group(), finalize(), and initialize().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/PE_Groups.h
src/Kernel/Utilitaires/PE_Groups.cpp