TRUST: Loi_Etat_rhoT_GP_QC Class Reference
Loi_Etat_rhoT_GP_QC Class Reference
: class Loi_Etat_rhoT_GP_QC
<Description of class Loi_Etat_rhoT_GP_QC>
#include <Loi_Etat_rhoT_GP_QC.h>
Public Member Functions
~Loi_Etat_rhoT_GP_QC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Loi_Etat_rhoT_GP_QC ()
void initialiser_inco_ch ()
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
void initialiser_rho ()
void calculer_masse_volumique ()
Recalcule la masse volumique.
double calculer_masse_volumique (double, double) const
overrided
double calculer_masse_volumique (double, double, int) const
overloaded
double inverser_Pth (double T, double rho)
forbidden
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Loi_Etat_rhoT_GP_QC & self_cast (Objet_U &)
static const Loi_Etat_rhoT_GP_QC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
bool is_exp_
Champ_Don rho_xyz_
DoubleTab rho_
Parser_U parser_
Detailed Description
: class Loi_Etat_rhoT_GP_QC
<Description of class Loi_Etat_rhoT_GP_QC>
Definition at line 39 of file Loi_Etat_rhoT_GP_QC.h.
Constructor & Destructor Documentation
Loi_Etat_rhoT_GP_QC::~Loi_Etat_rhoT_GP_QC ()
Definition at line 27 of file Loi_Etat_rhoT_GP_QC.cpp.
Loi_Etat_rhoT_GP_QC::Loi_Etat_rhoT_GP_QC ()
Definition at line 30 of file Loi_Etat_rhoT_GP_QC.cpp.
: is_exp_(false) { }
Member Function Documentation
void Loi_Etat_rhoT_GP_QC::calculer_masse_volumique () [virtual]
Recalcule la masse volumique.
Reimplemented from Loi_Etat_GP_base.
Definition at line 164 of file Loi_Etat_rhoT_GP_QC.cpp.
References DoubleVect::echange_espace_virtuel(), Loi_Etat_base::le_fluide, DoubleVect::size(), Loi_Etat_base::tab_rho_n, and Loi_Etat_base::tab_rho_np1.
{
  const DoubleTab& tab_ICh = le_fluide->inco_chaleur().valeurs();
  DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  double Pth = le_fluide->pression_th();
  int n=tab_rho.size();
  for (int som=0 ; som<n ; som++)
    {
      tab_rho_np1(som) =  calculer_masse_volumique(Pth,tab_ICh(som,0),som);
      tab_rho(som,0) = 0.5 * (tab_rho_n(som) + tab_rho_np1(som));
    }
  tab_rho.echange_espace_virtuel();
  tab_rho_np1.echange_espace_virtuel();
  le_fluide->calculer_rho_face(tab_rho_np1);
}
double Loi_Etat_rhoT_GP_QC::calculer_masse_volumique (double P, double T) const [virtual]
overrided
Reimplemented from Loi_Etat_GP_base.
Definition at line 112 of file Loi_Etat_rhoT_GP_QC.cpp.
{
  /* Not useful for this state law */
  return -3000.;
}
double Loi_Etat_rhoT_GP_QC::calculer_masse_volumique (double P, double T, int ind) const
overloaded
Definition at line 119 of file Loi_Etat_rhoT_GP_QC.cpp.
References Cerr, Parser_U::eval(), Process::exit(), finl, inf_ou_egal(), is_exp_, parser_, rho_, and Parser_U::setVar().
{
  if (inf_ou_egal(T,-1000))
    {
      Cerr << finl << "Error, we find a temperature of " << T << " !" << finl;
      Cerr << "Either your calculation has diverged or you don't define" << finl;
      Cerr << "temperature in Kelvin somewhere in your data file." << finl;
      Cerr << "It is mandatory for Quasi compressible model." << finl;
      Cerr << "Check your data file." << finl;
      Process::exit();
    }
  if (is_exp_)
    {
      parser_.setVar(0,T);
      return parser_.eval();
    }
  else
    {
// Initialized from Champ_Fonc_xyz
// dont change, return what is saved in rho_
      return rho_(ind,0);
    }
}
Objet_U * Loi_Etat_rhoT_GP_QC::cree_instance () [static]
Definition at line 27 of file Loi_Etat_rhoT_GP_QC.cpp.
int Loi_Etat_rhoT_GP_QC::duplique () const [virtual]
Implements Loi_Etat_GP_base.
Definition at line 27 of file Loi_Etat_rhoT_GP_QC.cpp.
const Type_info * Loi_Etat_rhoT_GP_QC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_GP_base.
Definition at line 27 of file Loi_Etat_rhoT_GP_QC.cpp.
const Type_info * Loi_Etat_rhoT_GP_QC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_GP_base.
Definition at line 27 of file Loi_Etat_rhoT_GP_QC.cpp.
void Loi_Etat_rhoT_GP_QC::initialiser_inco_ch () [virtual]
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
Reimplemented from Loi_Etat_base.
Definition at line 104 of file Loi_Etat_rhoT_GP_QC.cpp.
References initialiser_rho(), and is_exp_.
{
// required here for xyz !
  if ( !is_exp_ ) initialiser_rho();
  Loi_Etat_base::initialiser_inco_ch();
}
void Loi_Etat_rhoT_GP_QC::initialiser_rho ()
< rho on faces in VEF
Definition at line 75 of file Loi_Etat_rhoT_GP_QC.cpp.
References Champ_base::affecter_(), Loi_Etat_base::le_fluide, Objet_U::que_suis_je(), DoubleTab::resize(), rho_, rho_xyz_, DoubleVect::size(), Deriv_Champ_Don_base::valeur(), Champ_Proto::valeurs(), and Champ_Don_base::valeurs().
Referenced by initialiser_inco_ch().
{
  int isVDF = 0;
  if (le_fluide->masse_volumique().que_suis_je()=="Champ_Fonc_P0_VDF") isVDF = 1;
// We know that mu is always stored on elems
  int nb_elems = le_fluide->viscosite_dynamique().valeurs().size();
// The Champ_Don rho_xyz_ is evaluated on elements
  assert (rho_xyz_.valeur().valeurs().size() == nb_elems);
  if (isVDF)
    {
// Disc VDF => rho_ & rho_xyz_ on elems => we do nothing
      rho_.resize(nb_elems, 1);
      DoubleTab& fld = rho_xyz_.valeur().valeurs();
      for (int i=0; i<nb_elems; i++) rho_(i,0)=fld(i,0);
    }
  else
    {
// Disc VEF => rho on faces ...
      int nb_faces =  le_fluide->masse_volumique().valeurs().size(); //!< rho on faces in VEF
      rho_.resize(nb_faces, 1);
      Champ_base& ch_rho = le_fluide->masse_volumique();
      ch_rho.affecter_(rho_xyz_);
      DoubleTab& fld = ch_rho.valeurs();
      for (int i = 0; i < nb_faces; i++) rho_(i,0)= fld(i,0);
    }
}
double Loi_Etat_rhoT_GP_QC::inverser_Pth (double T, double rho) [virtual]
forbidden
Reimplemented from Loi_Etat_GP_base.
Definition at line 144 of file Loi_Etat_rhoT_GP_QC.cpp.
References Process::abort().
{
  abort();
  throw;
}
Sortie & Loi_Etat_rhoT_GP_QC::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Loi_Etat_GP_base.
Definition at line 32 of file Loi_Etat_rhoT_GP_QC.cpp.
{
  Loi_Etat_GP_base::printOn( os );
  return os;
}
Entree & Loi_Etat_rhoT_GP_QC::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
< XD_ADD_P double Specific heat at constant pressure of the gas Cp.
< XD_ADD_P double Prandtl number of the gas Pr=mu*Cp/lambda
< XD_ADD_P field_base Defined with a Champ_Fonc_xyz to define a constant rho with time (space dependent)
< XD_ADD_P chaine Expression of T used to calculate rho. This can lead to a variable rho, both in space and in time.
Reimplemented from Loi_Etat_GP_base.
Definition at line 38 of file Loi_Etat_rhoT_GP_QC.cpp.
References Parser_U::addVar(), Param::ajouter(), Cerr, Loi_Etat_GP_base::Cp_, Process::exit(), finl, is_exp_, Param::lire_avec_accolades(), O_U_Ptr::non_nul(), parser_, Parser_U::parseString(), Loi_Etat_base::Pr_, Objet_U::que_suis_je(), Param::REQUIRED, rho_xyz_, Parser_U::setNbVar(), Parser_U::setString(), and Deriv_Champ_Don_base::valeur().
{
  Nom expression_;
  Param param(que_suis_je());
  param.ajouter("Cp",&Cp_,Param::REQUIRED);//!< XD_ADD_P double Specific heat at constant pressure of the gas Cp.
  param.ajouter("Prandtl",&Pr_); //!< XD_ADD_P double Prandtl number of the gas Pr=mu*Cp/lambda
  param.ajouter("rho_xyz",&rho_xyz_); //!< XD_ADD_P field_base Defined with a Champ_Fonc_xyz to define a constant rho with time (space dependent)
  param.ajouter("rho_t",&expression_); //!< XD_ADD_P chaine Expression of T used to calculate rho. This can lead to a variable rho, both in space and in time.
  param.lire_avec_accolades(is);
  if (expression_ == "??" && !rho_xyz_.non_nul())
    {
      Cerr << "Error in Loi_Etat_rhoT_GP_QC::readOn !" << finl;
      Cerr << "The closure equation of rho is not read in your data file !" << finl;
      Cerr << "Either use rho_t followed by an expression of T," << finl;
      Cerr << "or use rho_xyz followed by a Champ_Fonc_xyz !" << finl;
      Process::exit();
    }
  if (expression_ != "??")
    {
      is_exp_ = true;
      Cerr << "Parsing the expression " << expression_ << finl;
      parser_.setNbVar(1);
      parser_.setString(expression_);
      parser_.addVar("T");
      parser_.parseString();
    }
  else
    assert(rho_xyz_.valeur().que_suis_je() == "Champ_Fonc_xyz" );
  return is;
}
const Loi_Etat_rhoT_GP_QC & Loi_Etat_rhoT_GP_QC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Loi_Etat_GP_base.
Definition at line 27 of file Loi_Etat_rhoT_GP_QC.cpp.
Loi_Etat_rhoT_GP_QC & Loi_Etat_rhoT_GP_QC::self_cast (Objet_U & r) [static]
Reimplemented from Loi_Etat_GP_base.
Definition at line 27 of file Loi_Etat_rhoT_GP_QC.cpp.
unsigned Loi_Etat_rhoT_GP_QC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 27 of file Loi_Etat_rhoT_GP_QC.cpp.
Member Data Documentation
const Type_info Loi_Etat_rhoT_GP_QC::info_obj [static]
Reimplemented from Loi_Etat_GP_base.
Definition at line 41 of file Loi_Etat_rhoT_GP_QC.h.
bool Loi_Etat_rhoT_GP_QC::is_exp_ [protected]
Definition at line 53 of file Loi_Etat_rhoT_GP_QC.h.
Referenced by calculer_masse_volumique(), initialiser_inco_ch(), and readOn().
Parser_U Loi_Etat_rhoT_GP_QC::parser_ [mutable, protected]
Definition at line 56 of file Loi_Etat_rhoT_GP_QC.h.
Referenced by calculer_masse_volumique(), and readOn().
DoubleTab Loi_Etat_rhoT_GP_QC::rho_ [protected]
Definition at line 55 of file Loi_Etat_rhoT_GP_QC.h.
Referenced by calculer_masse_volumique(), and initialiser_rho().
Champ_Don Loi_Etat_rhoT_GP_QC::rho_xyz_ [protected]
Definition at line 54 of file Loi_Etat_rhoT_GP_QC.h.
Referenced by initialiser_rho(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/Loi_Etat/Loi_Etat_rhoT_GP_QC.h
src/ThHyd/Dilatable/Quasi_Compressible/Loi_Etat/Loi_Etat_rhoT_GP_QC.cpp