TRUST: Champ_implementation_base Class Reference
Champ_implementation_base Class Reference abstract
: class Champ_implementation_base
Decrire ici la classe Champ_implementation_base
#include <Champ_implementation_base.h>
Public Member Functions
virtual ~Champ_implementation_base ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &domain, DoubleTab &result) const
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &domain, DoubleVect &result, int ncomp) const
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Protected Member Functions
virtual DoubleTab & valeur_aux_sommets_impl (DoubleTab &result) const =0
virtual DoubleVect & valeur_aux_sommets_compo_impl (DoubleVect &result, int ncomp) const =0
const Zone_VF & get_zone_dis (void) const
const Zone & get_zone_geom (void) const
virtual Champ_base & le_champ (void)=0
virtual const Champ_base & le_champ (void) const =0
Detailed Description
: class Champ_implementation_base
Decrire ici la classe Champ_implementation_base
Definition at line 32 of file Champ_implementation_base.h.
Constructor & Destructor Documentation
~Champ_implementation_base()
virtual Champ_implementation_base::~Champ_implementation_base () inline virtual
Definition at line 36 of file Champ_implementation_base.h.
{ }
Member Function Documentation
get_zone_dis()
const Zone_VF & Champ_implementation_base::get_zone_dis (void) const protected
Definition at line 58 of file Champ_implementation_base.cpp.
{
  const Champ_base& ch_base = le_champ();
  if(sub_type(Champ_Inc_base, ch_base))
    {
      const Champ_Inc_base& ch_inc = ref_cast(Champ_Inc_base, ch_base);
      return ref_cast(Zone_VF,ch_inc.zone_dis_base());
    }
  else if(sub_type(Champ_Fonc_base, ch_base))
    {
      const Champ_Fonc_base& ch_fonc = ref_cast(Champ_Fonc_base, ch_base);
      return ref_cast(Zone_VF,ch_fonc.zone_dis_base());
    }
  else
    {
      Cerr << le_champ().que_suis_je() << "do not know refer a Zone_VF" << finl;
      Process::exit();
      return get_zone_dis();
    }
}
References Cerr, Process::exit(), finl, get_zone_dis(), le_champ(), Objet_U::que_suis_je(), ref_cast, sub_type, and Champ_base::zone_dis_base().
Referenced by get_zone_dis(), and get_zone_geom().
get_zone_geom()
const Zone & Champ_implementation_base::get_zone_geom (void) const protected
Definition at line 80 of file Champ_implementation_base.cpp.
{
  return get_zone_dis().zone();
}
References get_zone_dis(), and Zone_dis_base::zone().
Referenced by Champ_implementation_Q1::form_function(), Champ_implementation_P0::imprime_P0(), Champ_implementation_P0::remplir_coord_noeuds(), Champ_implementation_sommet_base::remplir_coord_noeuds(), Champ_implementation_P0::remplir_coord_noeuds_et_polys(), Champ_implementation_sommet_base::remplir_coord_noeuds_et_polys(), valeur_aux_sommets(), valeur_aux_sommets_compo(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_implementation_P1::value_interpolation(), and Champ_implementation_Q1::value_interpolation().
le_champ() [1/2]
virtual const Champ_base & Champ_implementation_base::le_champ (void) const protected pure virtual
Implemented in Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_implementation_P0, Champ_implementation_P1, Champ_implementation_Q1, and Champ_implementation_sommet_base.
le_champ() [2/2]
virtual Champ_base & Champ_implementation_base::le_champ (void) protected pure virtual
Implemented in Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_implementation_P0, Champ_implementation_P1, Champ_implementation_Q1, and Champ_implementation_sommet_base.
Referenced by get_zone_dis(), valeur_aux_sommets(), and valeur_aux_sommets_compo().
remplir_coord_noeuds()
virtual DoubleTab & Champ_implementation_base::remplir_coord_noeuds (DoubleTab & positions) const pure virtual
Implemented in Champ_P0_VDF, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_implementation_P0, Champ_implementation_sommet_base, Champ_Inc_P0_base, Champ_Inc_P1_base, and Champ_Inc_Q1_base.
remplir_coord_noeuds_et_polys()
virtual int Champ_implementation_base::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const pure virtual
Implemented in Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_implementation_P0, Champ_implementation_sommet_base, Champ_Inc_P0_base, Champ_Inc_P1_base, and Champ_Inc_Q1_base.
valeur_a_elem()
virtual DoubleVect & Champ_implementation_base::valeur_a_elem (const DoubleVect & position, DoubleVect & result, int poly) const pure virtual
Implemented in Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_implementation_P0, Champ_implementation_sommet_base, Champ_Inc_P0_base, Champ_Inc_P1_base, and Champ_Inc_Q1_base.
valeur_a_elem_compo()
virtual double Champ_implementation_base::valeur_a_elem_compo (const DoubleVect & position, int poly, int ncomp) const pure virtual
Implemented in Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_implementation_P0, Champ_implementation_sommet_base, Champ_Inc_P0_base, Champ_Inc_P1_base, and Champ_Inc_Q1_base.
valeur_aux_elems()
virtual DoubleTab & Champ_implementation_base::valeur_aux_elems (const DoubleTab & positions, const IntVect & polys, DoubleTab & result) const pure virtual
Implemented in Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_implementation_P0, Champ_implementation_sommet_base, Champ_Inc_P0_base, Champ_Inc_P1_base, and Champ_Inc_Q1_base.
valeur_aux_elems_compo()
virtual DoubleVect & Champ_implementation_base::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & polys, DoubleVect & result, int ncomp) const pure virtual
Implemented in Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_implementation_P0, Champ_implementation_sommet_base, Champ_Inc_P0_base, Champ_Inc_P1_base, and Champ_Inc_Q1_base.
valeur_aux_sommets()
DoubleTab & Champ_implementation_base::valeur_aux_sommets (const Domaine & domain, DoubleTab & result) const virtual
Reimplemented in Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, and Champ_Inc_Q1_base.
Definition at line 22 of file Champ_implementation_base.cpp.
{
  Nom domain_name  = domain.le_nom();
  Nom support_name = get_zone_geom().domaine().le_nom();
  if(domain_name == support_name)
    {
      valeur_aux_sommets_impl(result);
    }
  else
    {
      const DoubleTab& positions = domain.coord_sommets();
      le_champ().valeur_aux(positions, result);
    }
  return result;
}
References Domaine::coord_sommets(), Zone::domaine(), get_zone_geom(), le_champ(), Domaine::le_nom(), Champ_base::valeur_aux(), and valeur_aux_sommets_impl().
Referenced by Champ_Fonc_P0_base::valeur_aux_sommets(), Champ_Fonc_P1_base::valeur_aux_sommets(), Champ_Fonc_Q1_base::valeur_aux_sommets(), Champ_Inc_P0_base::valeur_aux_sommets(), Champ_Inc_P1_base::valeur_aux_sommets(), and Champ_Inc_Q1_base::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_implementation_base::valeur_aux_sommets_compo (const Domaine & domain, DoubleVect & result, int ncomp) const virtual
Reimplemented in Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, and Champ_Inc_Q1_base.
Definition at line 40 of file Champ_implementation_base.cpp.
{
  Nom domain_name  = domain.le_nom();
  Nom support_name = get_zone_geom().domaine().le_nom();
  if(domain_name == support_name)
    {
      valeur_aux_sommets_compo_impl(result,ncomp);
    }
  else
    {
      const DoubleTab& positions = domain.coord_sommets();
      le_champ().valeur_aux_compo(positions, result, ncomp);
    }
  return result;
}
References Domaine::coord_sommets(), Zone::domaine(), get_zone_geom(), le_champ(), Domaine::le_nom(), Champ_base::valeur_aux_compo(), and valeur_aux_sommets_compo_impl().
Referenced by Champ_Fonc_P0_base::valeur_aux_sommets_compo(), Champ_Fonc_P1_base::valeur_aux_sommets_compo(), Champ_Fonc_Q1_base::valeur_aux_sommets_compo(), Champ_Inc_P0_base::valeur_aux_sommets_compo(), Champ_Inc_P1_base::valeur_aux_sommets_compo(), and Champ_Inc_Q1_base::valeur_aux_sommets_compo().
valeur_aux_sommets_compo_impl()
virtual DoubleVect & Champ_implementation_base::valeur_aux_sommets_compo_impl (DoubleVect & result, int ncomp) const protected pure virtual
Implemented in Champ_implementation_P0, and Champ_implementation_sommet_base.
Referenced by valeur_aux_sommets_compo().
valeur_aux_sommets_impl()
virtual DoubleTab & Champ_implementation_base::valeur_aux_sommets_impl (DoubleTab & result) const protected pure virtual
Implemented in Champ_implementation_P0, and Champ_implementation_sommet_base.
Referenced by valeur_aux_sommets().
The documentation for this class was generated from the following files:
src/Kernel/Champs_dis/Champ_implementation_base.h
src/Kernel/Champs_dis/Champ_implementation_base.cpp