TRUST: liste_curseur Class Reference
liste_curseur Class Reference
Les classes liste et liste_curseur representent
une liste de Deriv<Objet_U> et un curseur associe.
List<T> et List_Curseur<T> en heritent.
#include <liste.h>
Public Member Functions
liste_curseur (const liste &)
Constructeur
Construit une liste_curseur a partir d'une liste.
operator bool () const
Teste si le curseur est non nul.
void operator++ ()
Avance le curseur dans la liste
Si le curseur est sur le dernier element, il devient nul.
const Objet_U & valeur () const
Retourne l'Objet_U associe au curseur de la liste.
Objet_U & valeur ()
Retourne l'Objet_U associe au curseur de la liste.
Objet_U * operator-> ()
Retourne un pointeur sur l'Objet_U du curseur de la liste.
const Objet_U * operator-> () const
Retourne un pointeur sur l'Objet_U du curseur de la liste.
liste & operator= (const liste &)
Affectation d'une liste a une liste_curseur.
const liste & list () const
Retourne la liste associee a la liste_curseur.
liste & list ()
Retourne la liste associee a la liste_curseur.
Private Attributes
liste * curseur
Detailed Description
Les classes liste et liste_curseur representent
une liste de Deriv<Objet_U> et un curseur associe.
List<T> et List_Curseur<T> en heritent.
Definition at line 107 of file liste.h.
Constructor & Destructor Documentation
liste_curseur::liste_curseur (const liste & a_list) [inline]
Constructeur
Construit une liste_curseur a partir d'une liste.
Definition at line 495 of file liste.h.
References curseur, and liste::est_vide().
  : curseur((liste*) &a_list)
{
  if(a_list.est_vide())
    curseur=0;
}
Member Function Documentation
const liste & liste_curseur::list () const [inline]
Retourne la liste associee a la liste_curseur.
Returns:
const liste&
Signification: la liste associee
Contraintes:
Reimplemented in list_curseurTable, const_list_curseurTable, list_curseurChamp_Fonc_Tabule, const_list_curseurChamp_Fonc_Tabule, list_curseurRef_Champ_base, const_list_curseurRef_Champ_base, list_curseurChamp_Fonc, const_list_curseurChamp_Fonc, list_curseurRefObjU, const_list_curseurRefObjU, list_curseurEquation, const_list_curseurEquation, list_curseurRef_Champ_Generique_base, const_list_curseurRef_Champ_Generique_base, list_curseurRef_Equation_base, const_list_curseurRef_Equation_base, list_curseurRef_Field_base, const_list_curseurRef_Field_base, list_curseurRef_IntVect, const_list_curseurRef_IntVect, list_curseurRef_Loi_Fermeture_base, const_list_curseurRef_Loi_Fermeture_base, list_curseurRef_Postraitement, const_list_curseurRef_Postraitement, list_curseurRef_Probleme_U, const_list_curseurRef_Probleme_U, list_curseurChamp_Generique, const_list_curseurChamp_Generique, list_curseurDeriv_Postraitement_base, const_list_curseurDeriv_Postraitement_base, list_curseurSonde, const_list_curseurSonde, list_curseurChamp, const_list_curseurChamp, list_curseurSonde_Int, const_list_curseurSonde_Int, list_curseurSource, const_list_curseurSource, list_curseurBord, const_list_curseurBord, list_curseurDomaine, const_list_curseurDomaine, list_curseurFaces_Interne, const_list_curseurFaces_Interne, list_curseurRef_Domaine, const_list_curseurRef_Domaine, list_curseurJoint, const_list_curseurJoint, list_curseurRef_Sous_Zone, const_list_curseurRef_Sous_Zone, list_curseurRaccord, const_list_curseurRaccord, list_curseurRef_Frontiere, const_list_curseurRef_Frontiere, list_curseurZone, const_list_curseurZone, list_curseurConstante, const_list_curseurConstante, list_curseurDoubleVect, const_list_curseurDoubleVect, list_curseurDeriv_UnaryFunction, const_list_curseurDeriv_UnaryFunction, list_curseurMatrice_Morse_Sym, const_list_curseurMatrice_Morse_Sym, list_curseurPolynome, const_list_curseurPolynome, list_curseurOperateur_Statistique_tps, const_list_curseurOperateur_Statistique_tps, list_curseurList_Nom, const_list_curseurList_Nom, list_curseurMotcle, const_list_curseurMotcle, list_curseurNom, const_list_curseurNom, list_curseurNoms, const_list_curseurNoms, list_curseurObjet_a_lire, const_list_curseurObjet_a_lire, list_curseurReaction, const_list_curseurReaction, list_curseurRef_Champ_Inc_base, const_list_curseurRef_Champ_Inc_base, list_curseurRef_Espece, const_list_curseurRef_Espece, list_curseurFluide_base, and const_list_curseurFluide_base.
Definition at line 653 of file liste.h.
References curseur.
Referenced by liste::add_if_not(), liste::dernier(), liste::printOn(), liste::search(), and liste::suppr().
{
  return *curseur;
}
liste & liste_curseur::list () [inline]
Retourne la liste associee a la liste_curseur.
Returns:
liste&
Signification: la liste associee
Contraintes:
Reimplemented in list_curseurTable, list_curseurChamp_Fonc_Tabule, list_curseurRef_Champ_base, list_curseurChamp_Fonc, list_curseurRefObjU, list_curseurEquation, list_curseurRef_Champ_Generique_base, list_curseurRef_Equation_base, list_curseurRef_Field_base, list_curseurRef_IntVect, list_curseurRef_Loi_Fermeture_base, list_curseurRef_Postraitement, list_curseurRef_Probleme_U, list_curseurChamp_Generique, list_curseurDeriv_Postraitement_base, list_curseurSonde, list_curseurChamp, list_curseurSonde_Int, list_curseurSource, list_curseurBord, list_curseurDomaine, list_curseurFaces_Interne, list_curseurRef_Domaine, list_curseurJoint, list_curseurRef_Sous_Zone, list_curseurRaccord, list_curseurRef_Frontiere, list_curseurZone, list_curseurConstante, list_curseurDoubleVect, list_curseurDeriv_UnaryFunction, list_curseurMatrice_Morse_Sym, list_curseurPolynome, list_curseurOperateur_Statistique_tps, list_curseurList_Nom, list_curseurMotcle, list_curseurNom, list_curseurNoms, list_curseurObjet_a_lire, list_curseurReaction, list_curseurRef_Champ_Inc_base, list_curseurRef_Espece, and list_curseurFluide_base.
Definition at line 672 of file liste.h.
References curseur.
{
  return *curseur;
}
liste_curseur::operator bool () const [inline]
Teste si le curseur est non nul.
Returns:
int
Signification: 1 si le curseur est non nul, 0 si il est nul
Contraintes:
Definition at line 516 of file liste.h.
References curseur.
{
  return (curseur!=0);
}
void liste_curseur::operator++ () [inline]
Avance le curseur dans la liste
Si le curseur est sur le dernier element, il devient nul.
Definition at line 536 of file liste.h.
References curseur, liste::est_dernier(), and liste::suivant().
{
  if (curseur->est_dernier()) curseur=0;
  else curseur=&(curseur->suivant());
}
Objet_U * liste_curseur::operator-> () [inline]
Retourne un pointeur sur l'Objet_U du curseur de la liste.
Returns:
Objet_U*
Signification: pointeur sur l'Objet_U du curseur
Contraintes:
Reimplemented in list_curseurTable, const_list_curseurTable, list_curseurChamp_Fonc_Tabule, const_list_curseurChamp_Fonc_Tabule, list_curseurRef_Champ_base, const_list_curseurRef_Champ_base, list_curseurChamp_Fonc, const_list_curseurChamp_Fonc, list_curseurRefObjU, const_list_curseurRefObjU, list_curseurEquation, const_list_curseurEquation, list_curseurRef_Champ_Generique_base, const_list_curseurRef_Champ_Generique_base, list_curseurRef_Equation_base, const_list_curseurRef_Equation_base, list_curseurRef_Field_base, const_list_curseurRef_Field_base, list_curseurRef_IntVect, const_list_curseurRef_IntVect, list_curseurRef_Loi_Fermeture_base, const_list_curseurRef_Loi_Fermeture_base, list_curseurRef_Postraitement, const_list_curseurRef_Postraitement, list_curseurRef_Probleme_U, const_list_curseurRef_Probleme_U, list_curseurChamp_Generique, const_list_curseurChamp_Generique, list_curseurDeriv_Postraitement_base, const_list_curseurDeriv_Postraitement_base, list_curseurSonde, const_list_curseurSonde, list_curseurChamp, const_list_curseurChamp, list_curseurSonde_Int, const_list_curseurSonde_Int, list_curseurSource, const_list_curseurSource, list_curseurBord, const_list_curseurBord, list_curseurDomaine, const_list_curseurDomaine, list_curseurFaces_Interne, const_list_curseurFaces_Interne, list_curseurRef_Domaine, const_list_curseurRef_Domaine, list_curseurJoint, const_list_curseurJoint, list_curseurRef_Sous_Zone, const_list_curseurRef_Sous_Zone, list_curseurRaccord, const_list_curseurRaccord, list_curseurRef_Frontiere, const_list_curseurRef_Frontiere, list_curseurZone, const_list_curseurZone, list_curseurConstante, const_list_curseurConstante, list_curseurDoubleVect, const_list_curseurDoubleVect, list_curseurDeriv_UnaryFunction, const_list_curseurDeriv_UnaryFunction, list_curseurMatrice_Morse_Sym, const_list_curseurMatrice_Morse_Sym, list_curseurPolynome, const_list_curseurPolynome, list_curseurOperateur_Statistique_tps, const_list_curseurOperateur_Statistique_tps, list_curseurList_Nom, const_list_curseurList_Nom, list_curseurMotcle, const_list_curseurMotcle, list_curseurNom, const_list_curseurNom, list_curseurNoms, const_list_curseurNoms, list_curseurObjet_a_lire, const_list_curseurObjet_a_lire, list_curseurReaction, const_list_curseurReaction, list_curseurRef_Champ_Inc_base, const_list_curseurRef_Champ_Inc_base, list_curseurRef_Espece, const_list_curseurRef_Espece, list_curseurFluide_base, and const_list_curseurFluide_base.
Definition at line 594 of file liste.h.
References curseur.
{
  return curseur->operator->();
}
const Objet_U * liste_curseur::operator-> () const [inline]
Retourne un pointeur sur l'Objet_U du curseur de la liste.
Returns:
const Objet_U*
Signification: pointeur sur l'Objet_U du curseur
Contraintes:
Definition at line 613 of file liste.h.
References curseur.
{
  return curseur->operator->();
}
liste & liste_curseur::operator= (const liste & a_list) [inline]
Affectation d'une liste a une liste_curseur.
Returns:
liste&
Signification: la liste affectee
Contraintes:
Definition at line 633 of file liste.h.
References curseur.
{
  curseur=(liste*) (&a_list);
  return *curseur;
}
const Objet_U & liste_curseur::valeur () const [inline]
Retourne l'Objet_U associe au curseur de la liste.
Returns:
const Objet_U&
Signification: l'Objet_U associe au curseur
Contraintes:
Reimplemented in list_curseurTable, const_list_curseurTable, list_curseurChamp_Fonc_Tabule, const_list_curseurChamp_Fonc_Tabule, list_curseurRef_Champ_base, const_list_curseurRef_Champ_base, list_curseurChamp_Fonc, const_list_curseurChamp_Fonc, list_curseurRefObjU, const_list_curseurRefObjU, list_curseurEquation, const_list_curseurEquation, list_curseurRef_Champ_Generique_base, const_list_curseurRef_Champ_Generique_base, list_curseurRef_Equation_base, const_list_curseurRef_Equation_base, list_curseurRef_Field_base, const_list_curseurRef_Field_base, list_curseurRef_IntVect, const_list_curseurRef_IntVect, list_curseurRef_Loi_Fermeture_base, const_list_curseurRef_Loi_Fermeture_base, list_curseurRef_Postraitement, const_list_curseurRef_Postraitement, list_curseurRef_Probleme_U, const_list_curseurRef_Probleme_U, list_curseurChamp_Generique, const_list_curseurChamp_Generique, list_curseurDeriv_Postraitement_base, const_list_curseurDeriv_Postraitement_base, list_curseurSonde, const_list_curseurSonde, list_curseurChamp, const_list_curseurChamp, list_curseurSonde_Int, const_list_curseurSonde_Int, list_curseurSource, const_list_curseurSource, list_curseurBord, const_list_curseurBord, list_curseurDomaine, const_list_curseurDomaine, list_curseurFaces_Interne, const_list_curseurFaces_Interne, list_curseurRef_Domaine, const_list_curseurRef_Domaine, list_curseurJoint, const_list_curseurJoint, list_curseurRef_Sous_Zone, const_list_curseurRef_Sous_Zone, list_curseurRaccord, const_list_curseurRaccord, list_curseurRef_Frontiere, const_list_curseurRef_Frontiere, list_curseurZone, const_list_curseurZone, list_curseurConstante, const_list_curseurConstante, list_curseurDoubleVect, const_list_curseurDoubleVect, list_curseurDeriv_UnaryFunction, const_list_curseurDeriv_UnaryFunction, list_curseurMatrice_Morse_Sym, const_list_curseurMatrice_Morse_Sym, list_curseurPolynome, const_list_curseurPolynome, list_curseurOperateur_Statistique_tps, const_list_curseurOperateur_Statistique_tps, list_curseurList_Nom, const_list_curseurList_Nom, list_curseurMotcle, const_list_curseurMotcle, list_curseurNom, const_list_curseurNom, list_curseurNoms, const_list_curseurNoms, list_curseurObjet_a_lire, const_list_curseurObjet_a_lire, list_curseurReaction, const_list_curseurReaction, list_curseurRef_Champ_Inc_base, const_list_curseurRef_Champ_Inc_base, list_curseurRef_Espece, const_list_curseurRef_Espece, list_curseurFluide_base, and const_list_curseurFluide_base.
Definition at line 556 of file liste.h.
References curseur, and liste::valeur().
Referenced by liste::add(), liste::add_if_not(), liste::contient(), operator==(), liste::operator[](), liste::printOn(), liste::rang(), liste::search(), and liste::suppr().
{
  return curseur->valeur();
}
Objet_U & liste_curseur::valeur () [inline]
Retourne l'Objet_U associe au curseur de la liste.
Returns:
Objet_U&
Signification: l'Objet_U associe au curseur
Contraintes:
Reimplemented in list_curseurTable, list_curseurChamp_Fonc_Tabule, list_curseurRef_Champ_base, list_curseurChamp_Fonc, list_curseurRefObjU, list_curseurEquation, list_curseurRef_Champ_Generique_base, list_curseurRef_Equation_base, list_curseurRef_Field_base, list_curseurRef_IntVect, list_curseurRef_Loi_Fermeture_base, list_curseurRef_Postraitement, list_curseurRef_Probleme_U, list_curseurChamp_Generique, list_curseurDeriv_Postraitement_base, list_curseurSonde, list_curseurChamp, list_curseurSonde_Int, list_curseurSource, list_curseurBord, list_curseurDomaine, list_curseurFaces_Interne, list_curseurRef_Domaine, list_curseurJoint, list_curseurRef_Sous_Zone, list_curseurRaccord, list_curseurRef_Frontiere, list_curseurZone, list_curseurConstante, list_curseurDoubleVect, list_curseurDeriv_UnaryFunction, list_curseurMatrice_Morse_Sym, list_curseurPolynome, list_curseurOperateur_Statistique_tps, list_curseurList_Nom, list_curseurMotcle, list_curseurNom, list_curseurNoms, list_curseurObjet_a_lire, list_curseurReaction, list_curseurRef_Champ_Inc_base, list_curseurRef_Espece, and list_curseurFluide_base.
Definition at line 575 of file liste.h.
References curseur, and liste::valeur().
{
  return curseur->valeur();
}
Member Data Documentation
liste* liste_curseur::curseur [private]
Definition at line 121 of file liste.h.
Referenced by list(), liste_curseur(), operator bool(), operator++(), operator->(), operator=(), and valeur().
The documentation for this class was generated from the following file:
src/Kernel/Utilitaires/liste.h