TRUST: Multiplicateur_diphasique_Muhler_Steinhagen Class Reference
Multiplicateur_diphasique_Muhler_Steinhagen Class Reference
classe Multiplicateur_diphasique_Muhler_Steinhagen
multiplicateur diphasique par la correlation de Muhler-Steinhagen :
Phi^2 f_m / rho_m = (f_lo / rho_l + C (f_go / rho_g - f_lo / rho_l) x) (1 - x)^(1/3) + f_go / rho_g x^3
avec C = 2 par defaut
- applique a la phase liquide pour alpha < alpha_min
- applique a la phase vapeur pour alpha > alpha_max
#include <Multiplicateur_diphasique_Muhler_Steinhagen.h>
Public Member Functions
Multiplicateur_diphasique_Muhler_Steinhagen ()
~Multiplicateur_diphasique_Muhler_Steinhagen ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void coefficient (const double *alpha, const double *rho, const double *v, const double *f, const double *mu, const double Dh, const double gamma, const double *Fk, const double Fm, DoubleTab &coeff) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Multiplicateur_diphasique_Muhler_Steinhagen & self_cast (Objet_U &)
static const
Multiplicateur_diphasique_Muhler_Steinhagen & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
double alpha_min_ = 1
double alpha_max_ = 1.1
double a_ = 2
double b_ = 1
double c_ = 3
int n_l = -1
int n_g = -1
int min_lottes_flinn_ = 0
int min_sensas_ = 0
Detailed Description
classe Multiplicateur_diphasique_Muhler_Steinhagen
multiplicateur diphasique par la correlation de Muhler-Steinhagen :
Phi^2 f_m / rho_m = (f_lo / rho_l + C (f_go / rho_g - f_lo / rho_l) x) (1 - x)^(1/3) + f_go / rho_g x^3
avec C = 2 par defaut
- applique a la phase liquide pour alpha < alpha_min
- applique a la phase vapeur pour alpha > alpha_max
Definition at line 38 of file Multiplicateur_diphasique_Muhler_Steinhagen.h.
Constructor & Destructor Documentation
Multiplicateur_diphasique_Muhler_Steinhagen::Multiplicateur_diphasique_Muhler_Steinhagen ()
Definition at line 26 of file Multiplicateur_diphasique_Muhler_Steinhagen.cpp.
Multiplicateur_diphasique_Muhler_Steinhagen::~Multiplicateur_diphasique_Muhler_Steinhagen ()
Definition at line 26 of file Multiplicateur_diphasique_Muhler_Steinhagen.cpp.
Member Function Documentation
void Multiplicateur_diphasique_Muhler_Steinhagen::coefficient (const double * alpha, const double * rho, const double * v, const double * f, const double * mu, const double Dh, const double gamma, const double * Fk, const double Fm, DoubleTab & coeff) const [virtual]
Implements Multiplicateur_diphasique_base.
Definition at line 57 of file Multiplicateur_diphasique_Muhler_Steinhagen.cpp.
References a_, alpha_max_, alpha_min_, b_, c_, coeff, dabs(), max(), min(), min_lottes_flinn_, min_sensas_, n_g, and n_l.
{
  int min_ = min_sensas_ || min_lottes_flinn_;
  double G = alpha[n_l] * rho[n_l] * dabs(v[n_l]) + alpha[n_g] * rho[n_g] * dabs(v[n_g]), //debit total
         x = G ? alpha[n_g] * rho[n_g] * v[n_g] / G : 0, //titre
         fm_sur_rhom = (f[n_l] / rho[n_l] + a_ * (f[n_g] / rho[n_g] - f[n_l] / rho[n_l]) * std::pow(x, b_)) * std::pow(1 - x, 1. / c_) + f[n_g] / rho[n_g] * std::pow(x, c_),
         frac_g = min(max((alpha[n_g] - alpha_min_) / (alpha_max_ - alpha_min_), 0.), 1.), frac_l = 1 - frac_g, //fraction appliquee au liquide
         mul = min_sensas_ ? min(1., 1.4429 * std::pow(alpha[n_l], 0.6492)) : 1;
  coeff = 0;
  /* si min_ == 1 et si Lottes-Flinn/SENSAS donne un frottement plus bas -> on le prend */
  if (min_ && Fk[n_l] * mul < rho[n_l] / f[n_l] * fm_sur_rhom * Fm * (alpha[n_l] * alpha[n_l]))
    coeff(n_l, 0) = mul / (alpha[n_l] * alpha[n_l]);
  else coeff(n_l, 1) = frac_l * rho[n_l] / f[n_l] * fm_sur_rhom, coeff(n_g, 1) = frac_g * rho[n_g] / f[n_g] * fm_sur_rhom;
}
Objet_U * Multiplicateur_diphasique_Muhler_Steinhagen::cree_instance () [static]
Definition at line 26 of file Multiplicateur_diphasique_Muhler_Steinhagen.cpp.
int Multiplicateur_diphasique_Muhler_Steinhagen::duplique () const [virtual]
Implements Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_Muhler_Steinhagen.cpp.
const Type_info * Multiplicateur_diphasique_Muhler_Steinhagen::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_Muhler_Steinhagen.cpp.
const Type_info * Multiplicateur_diphasique_Muhler_Steinhagen::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_Muhler_Steinhagen.cpp.
Sortie & Multiplicateur_diphasique_Muhler_Steinhagen::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 28 of file Multiplicateur_diphasique_Muhler_Steinhagen.cpp.
{
  return os;
}
Entree & Multiplicateur_diphasique_Muhler_Steinhagen::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 33 of file Multiplicateur_diphasique_Muhler_Steinhagen.cpp.
References a_, Param::ajouter(), alpha_max_, alpha_min_, b_, c_, Nom::debute_par(), Process::exit(), Nom::finit_par(), Param::lire_avec_accolades_depuis(), min_lottes_flinn_, min_sensas_, n_g, n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), ref_cast, sub_type, and Ref_Probleme_base::valeur().
{
  Param param(que_suis_je());
  param.ajouter("alpha_min", &alpha_min_);
  param.ajouter("alpha_max", &alpha_max_);
  param.ajouter("min_lottes_flinn", &min_lottes_flinn_);
  param.ajouter("min_sensas", &min_sensas_);
  param.ajouter("a", &a_);
  param.ajouter("b", &b_);
  param.ajouter("c", &c_);
  param.lire_avec_accolades_depuis(is);
  const Pb_Multiphase *pbm = sub_type(Pb_Multiphase, pb_.valeur()) ? &ref_cast(Pb_Multiphase, pb_.valeur()) : NULL;
  if (!pbm || pbm->nb_phases() == 1) n_l = 0, n_g = -1; //pas un Pb_Multiphase -> monophasique liquide
  else for (int n = 0; n < pbm->nb_phases(); n++) //recherche de n_l, n_g : phase {liquide,gaz}_continu en priorite
      if (pbm->nom_phase(n).debute_par("liquide") && (n_l < 0 || pbm->nom_phase(n).finit_par("continu")))  n_l = n;
      else if (pbm->nom_phase(n).debute_par("gaz") && (n_g < 0 || pbm->nom_phase(n).finit_par("continu"))) n_g = n;
  if (n_l < 0) Process::exit(que_suis_je() + " : main phase not found!");
  return is;
}
const Multiplicateur_diphasique_Muhler_Steinhagen & Multiplicateur_diphasique_Muhler_Steinhagen::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_Muhler_Steinhagen.cpp.
Multiplicateur_diphasique_Muhler_Steinhagen & Multiplicateur_diphasique_Muhler_Steinhagen::self_cast (Objet_U & r) [static]
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_Muhler_Steinhagen.cpp.
unsigned Multiplicateur_diphasique_Muhler_Steinhagen::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Multiplicateur_diphasique_Muhler_Steinhagen.cpp.
Member Data Documentation
double Multiplicateur_diphasique_Muhler_Steinhagen::a_ = 2 [protected]
Definition at line 46 of file Multiplicateur_diphasique_Muhler_Steinhagen.h.
Referenced by coefficient(), and readOn().
double Multiplicateur_diphasique_Muhler_Steinhagen::alpha_max_ = 1.1 [protected]
Definition at line 46 of file Multiplicateur_diphasique_Muhler_Steinhagen.h.
Referenced by coefficient(), and readOn().
double Multiplicateur_diphasique_Muhler_Steinhagen::alpha_min_ = 1 [protected]
Definition at line 46 of file Multiplicateur_diphasique_Muhler_Steinhagen.h.
Referenced by coefficient(), and readOn().
double Multiplicateur_diphasique_Muhler_Steinhagen::b_ = 1 [protected]
Definition at line 46 of file Multiplicateur_diphasique_Muhler_Steinhagen.h.
Referenced by coefficient(), and readOn().
double Multiplicateur_diphasique_Muhler_Steinhagen::c_ = 3 [protected]
Definition at line 46 of file Multiplicateur_diphasique_Muhler_Steinhagen.h.
Referenced by coefficient(), and readOn().
const Type_info Multiplicateur_diphasique_Muhler_Steinhagen::info_obj [static]
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 40 of file Multiplicateur_diphasique_Muhler_Steinhagen.h.
int Multiplicateur_diphasique_Muhler_Steinhagen::min_lottes_flinn_ = 0 [protected]
Definition at line 47 of file Multiplicateur_diphasique_Muhler_Steinhagen.h.
Referenced by coefficient(), and readOn().
int Multiplicateur_diphasique_Muhler_Steinhagen::min_sensas_ = 0 [protected]
Definition at line 47 of file Multiplicateur_diphasique_Muhler_Steinhagen.h.
Referenced by coefficient(), and readOn().
int Multiplicateur_diphasique_Muhler_Steinhagen::n_g = -1 [protected]
Definition at line 47 of file Multiplicateur_diphasique_Muhler_Steinhagen.h.
Referenced by coefficient(), and readOn().
int Multiplicateur_diphasique_Muhler_Steinhagen::n_l = -1 [protected]
Definition at line 47 of file Multiplicateur_diphasique_Muhler_Steinhagen.h.
Referenced by coefficient(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Correlations/Multiplicateur_diphasique_Muhler_Steinhagen.h
src/ThHyd/Multiphase/Correlations/Multiplicateur_diphasique_Muhler_Steinhagen.cpp