TRUST: Champ_front_debit_massique Class Reference
Champ_front_debit_massique Class Reference
class Champ_front_debit_massique
Classe derivee de Champ_front_debit pour les amateurs de kg/s
#include <Champ_front_debit_massique.h>
Public Member Functions
Champ_front_debit_massique ()
~Champ_front_debit_massique ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void update_coeff (double temps)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_front_debit_massique & self_cast (Objet_U &)
static const
Champ_front_debit_massique & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le nom du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void initialiser_coefficient (const Champ_Inc_base &inco, double temps)
Protected Attributes
const Champ_base * ch_rho
Detailed Description
class Champ_front_debit_massique
Classe derivee de Champ_front_debit pour les amateurs de kg/s
Definition at line 39 of file Champ_front_debit_massique.h.
Constructor & Destructor Documentation
Champ_front_debit_massique::Champ_front_debit_massique ()
Definition at line 33 of file Champ_front_debit_massique.cpp.
Champ_front_debit_massique::~Champ_front_debit_massique ()
Definition at line 33 of file Champ_front_debit_massique.cpp.
Member Function Documentation
Objet_U * Champ_front_debit_massique::cree_instance () [static]
Reimplemented from Champ_front_debit.
Definition at line 33 of file Champ_front_debit_massique.cpp.
int Champ_front_debit_massique::duplique () const [virtual]
Reimplemented from Champ_front_debit.
Definition at line 33 of file Champ_front_debit_massique.cpp.
const Type_info * Champ_front_debit_massique::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_debit.
Definition at line 33 of file Champ_front_debit_massique.cpp.
const Type_info * Champ_front_debit_massique::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_debit.
Definition at line 33 of file Champ_front_debit_massique.cpp.
void Champ_front_debit_massique::initialiser_coefficient (const Champ_Inc_base & inco, double temps) [protected, virtual]
Reimplemented from Champ_front_xyz_debit.
Definition at line 46 of file Champ_front_debit_massique.cpp.
References ch_rho, MorEqn::equation(), Milieu_base::masse_volumique(), Equation_base::milieu(), sub_type, update_coeff(), and Champ_front_xyz_debit::update_coeff_.
{
  Champ_front_debit::initialiser_coefficient(inco, temps);
  ch_rho = &inco.equation().milieu().masse_volumique();
  if (sub_type(Champ_Uniforme, *ch_rho)) //rho constant : on calcule le coeff maintenant, puis on ne le fait plus
    update_coeff(temps), update_coeff_ = false;
  else update_coeff_ = true;
}
Sortie & Champ_front_debit_massique::printOn (Sortie & s) const [protected, virtual]
Imprime le nom du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_debit.
Definition at line 36 of file Champ_front_debit_massique.cpp.
{
  return Champ_front_debit::printOn(os);
}
Entree & Champ_front_debit_massique::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_debit.
Definition at line 41 of file Champ_front_debit_massique.cpp.
{
  return Champ_front_debit::readOn(is);
}
const Champ_front_debit_massique & Champ_front_debit_massique::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_front_debit.
Definition at line 33 of file Champ_front_debit_massique.cpp.
Champ_front_debit_massique & Champ_front_debit_massique::self_cast (Objet_U & r) [static]
Reimplemented from Champ_front_debit.
Definition at line 33 of file Champ_front_debit_massique.cpp.
unsigned Champ_front_debit_massique::taille_memoire () const [virtual]
Reimplemented from Champ_front_debit.
Definition at line 33 of file Champ_front_debit_massique.cpp.
void Champ_front_debit_massique::update_coeff (double temps) [virtual]
Reimplemented from Champ_front_xyz_debit.
Definition at line 55 of file Champ_front_debit_massique.cpp.
References ch_rho, Champ_front_xyz_debit::coeff_, Zone_VF::fbord(), Champ_front_base::frontiere_dis(), DoubleVect::line_size(), Front_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, sub_type, Champ_base::valeur_aux_bords(), Champ_Proto::valeurs(), and Champ_front_base::zone_dis().
Referenced by initialiser_coefficient().
{
  int i, fb, n, N = coeff_.line_size(), cR = sub_type(Champ_Uniforme, *ch_rho);
  DoubleTab rho_bord = cR ? ch_rho->valeurs() : ch_rho->valeur_aux_bords(); /* si rho uniforme, on ne peut pas appeler valeur_aux_bords() */
  const Zone_VF& zone = ref_cast(Zone_VF, zone_dis());
  const Front_VF& le_bord= ref_cast(Front_VF,frontiere_dis());
  for(i = 0; i < le_bord.nb_faces_tot(); i++) for (fb = zone.fbord(le_bord.num_face(i)), n = 0; n < N; ++n)
      coeff_(i, n) = 1. / rho_bord(!cR * fb, n);
}
Member Data Documentation
const Champ_base* Champ_front_debit_massique::ch_rho [protected]
Definition at line 47 of file Champ_front_debit_massique.h.
Referenced by initialiser_coefficient(), and update_coeff().
const Type_info Champ_front_debit_massique::info_obj [static]
Reimplemented from Champ_front_debit.
Definition at line 41 of file Champ_front_debit_massique.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_front_debit_massique.h
src/Kernel/Champs/Champ_front_debit_massique.cpp