TRUST: Point_EF Class Reference
Point_EF Class Reference
#include <Point_EF.h>
Public Member Functions
~Point_EF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Point_EF ()
void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int) const override
void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const override
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=2, n1 est le numero du sommet confondu avec G
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const override
remplit le tableau face_normales dans la Zone_EF
Public Member Functions inherited from Elem_EF_base
Elem_EF_base ()
~Elem_EF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int) const =0
virtual void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const =0
virtual void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Point_EF & self_cast (Objet_U &)
static const Point_EF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Elem_EF_base
static const Type_info * info ()
static Elem_EF_base & self_cast (Objet_U &)
static const Elem_EF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Elem_EF_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Definition at line 21 of file Point_EF.h.
Constructor & Destructor Documentation
~Point_EF()
Point_EF::~Point_EF ()
Definition at line 21 of file Point_EF.cpp.
Point_EF()
Point_EF::Point_EF ()
Definition at line 21 of file Point_EF.cpp.
Member Function Documentation
calcul_vc()
void Point_EF::calcul_vc (const ArrOfInt & Face, ArrOfDouble & vc, const ArrOfDouble & vs, const DoubleTab & vsom, const Champ_Inc_base & vitesse, int type_cl) const override virtual
< le triangle n'a pas de Face de Dirichlet
< le triangle a une Face de Dirichlet :la Face 2
< le triangle a une Face de Dirichlet :la Face 1
< le triangle a une Face de Dirichlet :la Face 0
< le triangle a deux faces de Dirichlet :les faces 1 et 2
< le triangle a deux faces de Dirichlet :les faces 0 et 2
< le triangle a deux faces de Dirichlet :les faces 0 et 1
Implements Elem_EF_base.
Definition at line 134 of file Point_EF.cpp.
{
  abort();
  const Zone_EF& zone_EF = ref_cast(Zone_EF,vitesse.zone_dis_base());
  const DoubleVect& porosite_face = zone_EF.porosite_face();
// Cerr << " type_cl " <<  type_cl << finl;
  switch(type_cl)
    {
    case 0: //!< le triangle n'a pas de Face de Dirichlet
      {
        vc[0] = vs[0]/3;
        vc[1] = vs[1]/3;
        break;
      }
    case 1: //!< le triangle a une Face de Dirichlet :la Face 2
      {
        vc[0]= vitesse(Face[2],0)*porosite_face[Face[2]];
        vc[1]= vitesse(Face[2],1)*porosite_face[Face[2]];
// vc[0]= vitesse(Face[2],0);
// vc[1]= vitesse(Face[2],1);
        break;
      }
    case 2: //!< le triangle a une Face de Dirichlet :la Face 1
      {
        vc[0]= vitesse(Face[1],0)*porosite_face[Face[1]];
        vc[1]= vitesse(Face[1],1)*porosite_face[Face[1]];
// vc[0]= vitesse(Face[1],0);
// vc[1]= vitesse(Face[1],1);
        break;
      }
    case 4: //!< le triangle a une Face de Dirichlet :la Face 0
      {
        vc[0]= vitesse(Face[0],0)*porosite_face[Face[0]];
        vc[1]= vitesse(Face[0],1)*porosite_face[Face[0]];
// vc[0]= vitesse(Face[0],0);
// vc[1]= vitesse(Face[0],1);
        break;
      }
    case 3: //!< le triangle a deux faces de Dirichlet :les faces 1 et 2
      {
        vc[0]= vsom(0,0);
        vc[1]= vsom(0,1);
        break;
      }
    case 5: //!< le triangle a deux faces de Dirichlet :les faces 0 et 2
      {
        vc[0]= vsom(1,0);
        vc[1]= vsom(1,1);
        break;
      }
    case 6: //!< le triangle a deux faces de Dirichlet :les faces 0 et 1
      {
        vc[0]= vsom(2,0);
        vc[1]= vsom(2,1);
        break;
      }
    } //!< fin du switch
}
References Process::abort(), Zone_VF::porosite_face(), ref_cast, and Champ_base::zone_dis_base().
calcul_xg()
void Point_EF::calcul_xg (DoubleVect & xg, const DoubleTab & x, const int type_elem_Cl, int & idirichlet, int & n1, int & , int &) const override virtual
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=2, n1 est le numero du sommet confondu avec G
< le triangle n'a pas de Face de dirichlet: il a 3 Facettes le point G est le barycentre des sommets du triangle
< le triangle a une Face de dirichlet: la Face 2 le point G est le barycentre des sommets de la Face 2
< le triangle a une Face de dirichlet: la Face 1 le point G est le barycentre des sommets de la Face 1
< le triangle a une Face de dirichlet: la Face 0 le point G est le barycentre des sommets de la Face 0
< le triangle a deux faces de Dirichlet : les faces 0,1 le point G est le sommet 2 du triangle
< le triangle a deux faces de Dirichlet : les faces 0,2 le point G est le sommet 1 du triangle
< le triangle a deux faces de Dirichlet : les faces 1,2 le point G est le sommet 0 du triangle
Implements Elem_EF_base.
Definition at line 207 of file Point_EF.cpp.
{
  abort();
  int j,dim=xg.size();
  switch(type_elem_Cl)
    {
    case 0:  //!< le triangle n'a pas de Face de dirichlet: il a 3 Facettes  le point G est le barycentre des sommets du triangle
//
      {
        for (j=0; j<dim; j++)
          xg[j]=(x(0,j)+x(1,j)+x(2,j))/3;
        idirichlet=0;
        break;
      }
    case 1:  //!< le triangle a une Face de dirichlet: la Face 2 le point G est le barycentre des sommets de la Face 2
//
      {
        for (j=0; j<dim; j++)
          xg[j]=(x(0,j)+x(1,j))/2;
        idirichlet=1;
        break;
      }
    case 2:  //!< le triangle a une Face de dirichlet: la Face 1 le point G est le barycentre des sommets de la Face 1
//
      {
        for (j=0; j<dim; j++)
          xg[j]=(x(0,j)+x(2,j))/2;
        idirichlet=1;
        break;
      }
    case 4:  //!< le triangle a une Face de dirichlet: la Face 0 le point G est le barycentre des sommets de la Face 0
//
      {
        for (j=0; j<dim; j++)
          xg[j]=(x(1,j)+x(2,j))/2;
        idirichlet=1;
        break;
      }
    case 6 : //!< le triangle a deux faces de Dirichlet : les faces 0,1 le point G est le sommet 2 du triangle
//
      {
        for (j=0; j<dim; j++)
          xg[j]=x(2,j);
        idirichlet=2;
        n1 = 2;
        break;
      }
    case 5 : //!< le triangle a deux faces de Dirichlet : les faces 0,2 le point G est le sommet 1 du triangle
//
      {
        for (j=0; j<dim; j++)
          xg[j]=x(1,j);
        idirichlet=2;
        n1 = 1;
        break;
      }
    case 3 : //!< le triangle a deux faces de Dirichlet : les faces 1,2 le point G est le sommet 0 du triangle
//
      {
        for (j=0; j<dim; j++)
          xg[j]=x(0,j);
        idirichlet=2;
        n1 = 0;
        break;
      }
    } //!< fin du switch
}
References Process::abort(), and TRUSTVect< _TYPE_ >::size().
cree_instance()
Objet_U * Point_EF::cree_instance () static
Definition at line 21 of file Point_EF.cpp.
duplique()
int Point_EF::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Point_EF.cpp.
get_info()
const Type_info * Point_EF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_EF_base.
Definition at line 21 of file Point_EF.cpp.
info()
const Type_info * Point_EF::info () static
Definition at line 21 of file Point_EF.cpp.
normale()
void Point_EF::normale (int num_Face, DoubleTab & Face_normales, const IntTab & Face_sommets, const IntTab & Face_voisins, const IntTab & elem_faces, const Zone & zone_geom) const override virtual
remplit le tableau face_normales dans la Zone_EF
Implements Elem_EF_base.
Definition at line 39 of file Point_EF.cpp.
{
  abort();
// pas de sens simple a normale
  Face_normales(num_Face,0) = 1;
  {
// int n0 = Face_sommets(num_Face,0);
    int elem1 = Face_voisins(num_Face,0);
// int elem2 = Face_voisins(num_Face,1);
    int n2=elem_faces(elem1,0);
    if (n2==num_Face) Face_normales(num_Face,0) = -1;
    /*
    const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
    //     const IntTab& elem = zone_geom.elems();
       {
    int n2=elem_faces(elem1,0);
    if ( n2 == num_Face )
    n2 = elem_faces(elem1,1);
    n2=Face_sommets(n2,0);
    for (int i=0;i<dim;i++)
    d(i) =les_coords(n0,i)- les_coords(n2,i);
    d/=d.norm();
    Face_normales(num_Face,0) = -1;
    }
    //int n1 = Face_sommets(num_Face,1);
    // Orientation de la normale de elem1 vers elem2
    // pour cela recherche du sommet de elem1 qui n'est pas sur la Face
    int f0,no3;
    int elem1 = Face_voisins(num_Face,0);
    Cerr<<num_Face<<" iii "<<elem1<< " "<<Face_voisins(num_Face,1)<<" "<<(Face_voisins(num_Face,0)==elem1)        <<finl;
    if ( (f0 = elem_faces(elem1,0)) == num_Face )
    f0 = elem_faces(elem1,1);
    if ( (no3 = Face_sommets(f0,0)) != n0  )
    Cerr<<"oo "<<finl;
    else
    {
    Cerr<<"ii"<<finl;
    no3 = Face_sommets(f0,1);
    }
    Cerr<<n0 << " "<<finl;
    */
  }
  return;
  /*
  double x1,y1;
  double nx,ny;
  int no3; int f0;
  int n0 = Face_sommets(num_Face,0);
  int n1 = Face_sommets(num_Face,1);
  x1 = les_coords(n0,0)-les_coords(n1,0);
  y1 = les_coords(n0,1)-les_coords(n1,1);
  nx = -y1;
  ny = x1;
  // Orientation de la normale de elem1 vers elem2
  // pour cela recherche du sommet de elem1 qui n'est pas sur la Face
  int elem1 = Face_voisins(num_Face,0);
  if ( (f0 = elem_faces(elem1,0)) == num_Face )
    f0 = elem_faces(elem1,1);
  if ( (no3 = Face_sommets(f0,0)) != n0 && no3 != n1 )
    ;
  else
    no3 = Face_sommets(f0,1);
  x1 = les_coords(no3,0) - les_coords(n0,0);
  y1 = les_coords(no3,1) - les_coords(n0,1);
  if ( (nx*x1+ny*y1) > 0 ) {
    Face_normales(num_Face,0) = - nx;
    Face_normales(num_Face,1) = - ny;
  }
  else {
    Face_normales(num_Face,0) = nx;
    Face_normales(num_Face,1) = ny;
  }
  */
}
References Process::abort().
printOn()
Sortie & Point_EF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Elem_EF_base.
Definition at line 26 of file Point_EF.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Point_EF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Elem_EF_base.
Definition at line 31 of file Point_EF.cpp.
{
  return s ;
}
self_cast() [1/2]
const Point_EF & Point_EF::self_cast (const Objet_U & r) static
Definition at line 21 of file Point_EF.cpp.
self_cast() [2/2]
Point_EF & Point_EF::self_cast (Objet_U & r) static
Definition at line 21 of file Point_EF.cpp.
taille_memoire()
unsigned Point_EF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Point_EF.cpp.
Member Data Documentation
info_obj
const Type_info Point_EF::info_obj static
Definition at line 24 of file Point_EF.h.
The documentation for this class was generated from the following files:
src/EF/Zones/Point_EF.h
src/EF/Zones/Point_EF.cpp