TRUST: Deriv_Loi_Etat_base Class Reference
Deriv_Loi_Etat_base Class Reference
class Loi_Etat
Cette classe est la derivee de la classe Loi_Etat_base
#include <Loi_Etat.h>
Public Member Functions
~Deriv_Loi_Etat_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Loi_Etat_base ()
Deriv_Loi_Etat_base (const Deriv_Loi_Etat_base &)
const Loi_Etat_base & valeur () const
Loi_Etat_base & valeur ()
const Loi_Etat_base * operator-> () const
Loi_Etat_base * operator-> ()
const Deriv_Loi_Etat_base & operator= (const Loi_Etat_base &)
const Deriv_Loi_Etat_base & operator= (const Deriv_Loi_Etat_base &)
operator const Loi_Etat_base & () const
operator Loi_Etat_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Loi_Etat_base & self_cast (Objet_U &)
static const Deriv_Loi_Etat_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Loi_Etat_base * pointeur_
Detailed Description
class Loi_Etat
Cette classe est la derivee de la classe Loi_Etat_base
Definition at line 38 of file Loi_Etat.h.
Constructor & Destructor Documentation
Deriv_Loi_Etat_base::~Deriv_Loi_Etat_base ()
Definition at line 26 of file Loi_Etat.cpp.
Deriv_Loi_Etat_base::Deriv_Loi_Etat_base ()
Definition at line 26 of file Loi_Etat.cpp.
Deriv_Loi_Etat_base::Deriv_Loi_Etat_base (const Deriv_Loi_Etat_base & t)
Definition at line 26 of file Loi_Etat.cpp.
Member Function Documentation
Objet_U * Deriv_Loi_Etat_base::cree_instance () [static]
Reimplemented in Loi_Etat.
Definition at line 26 of file Loi_Etat.cpp.
int Deriv_Loi_Etat_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Loi_Etat.
Definition at line 26 of file Loi_Etat.cpp.
const Type_info * Deriv_Loi_Etat_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Loi_Etat.
Definition at line 26 of file Loi_Etat.cpp.
const Type_info & Deriv_Loi_Etat_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Loi_Etat.cpp.
const Type_info * Deriv_Loi_Etat_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Loi_Etat.
Definition at line 26 of file Loi_Etat.cpp.
Deriv_Loi_Etat_base::operator const Loi_Etat_base & () const
Definition at line 26 of file Loi_Etat.cpp.
Deriv_Loi_Etat_base::operator Loi_Etat_base & ()
Definition at line 26 of file Loi_Etat.cpp.
const Loi_Etat_base * Deriv_Loi_Etat_base::operator-> () const [inline]
Definition at line 38 of file Loi_Etat.h.
: public DERIV(Loi_Etat_base)
Loi_Etat_base * Deriv_Loi_Etat_base::operator-> () [inline]
Definition at line 38 of file Loi_Etat.h.
: public DERIV(Loi_Etat_base)
const Deriv_Loi_Etat_base & Deriv_Loi_Etat_base::operator= (const Deriv_Loi_Etat_base & t)
Definition at line 26 of file Loi_Etat.cpp.
const Deriv_Loi_Etat_base & Deriv_Loi_Etat_base::operator= (const Loi_Etat_base & t)
Definition at line 26 of file Loi_Etat.cpp.
Sortie & Deriv_Loi_Etat_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Loi_Etat.
Definition at line 26 of file Loi_Etat.cpp.
Entree & Deriv_Loi_Etat_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Loi_Etat.
Definition at line 26 of file Loi_Etat.cpp.
const Deriv_Loi_Etat_base & Deriv_Loi_Etat_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Loi_Etat.
Definition at line 26 of file Loi_Etat.cpp.
Deriv_Loi_Etat_base & Deriv_Loi_Etat_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Loi_Etat.
Definition at line 26 of file Loi_Etat.cpp.
void Deriv_Loi_Etat_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Loi_Etat.cpp.
unsigned Deriv_Loi_Etat_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Loi_Etat.
Definition at line 26 of file Loi_Etat.cpp.
const Loi_Etat_base & Deriv_Loi_Etat_base::valeur () const [inline]
Definition at line 38 of file Loi_Etat.h.
Referenced by Convection_Diffusion_Espece_Multi_WC::completer(), Convection_Diffusion_Espece_Multi_QC::completer(), Fluide_Dilatable_base::creer_champs_non_lus(), Fluide_Quasi_Compressible::discretiser(), Loi_Etat::readOn(), and Loi_Etat::typer().
: public DERIV(Loi_Etat_base)
Loi_Etat_base & Deriv_Loi_Etat_base::valeur () [inline]
Definition at line 38 of file Loi_Etat.h.
: public DERIV(Loi_Etat_base)
Member Data Documentation
const Type_info Deriv_Loi_Etat_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Loi_Etat.
Definition at line 38 of file Loi_Etat.h.
Loi_Etat_base* Deriv_Loi_Etat_base::pointeur_ [private]
Definition at line 38 of file Loi_Etat.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat.h
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat.cpp