TRUST: Schema_Adams_Bashforth_order_2 Class Reference
Schema_Adams_Bashforth_order_2 Class Reference
classe Schema_Adams_Bashforth_order_2
Cette classe represente un schema en temps d'Adams-Bashforth d'ordre 2
a pas de temps variable :
U(n+1) = U(n) + dt*(3/2*(dU/dt)(n)-1/2(dU/dt)(n-1)) si le pas de temps
est constant
#include <Schema_Adams_Bashforth_order_2.h>
Public Member Functions
Schema_Adams_Bashforth_order_2 ()
~Schema_Adams_Bashforth_order_2 ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int nb_pas_dt_seuil () const
Renvoie le nombre de pas de temps strictement au dela duquel on applique le schema d Adams-Bahshforth.
Ici : on a besoin d'au moins 1 temps du passe donc 0.
int nb_valeurs_passees () const
Renvoie le nombre de valeurs temporelles du passe.
Ici : n-1 donc 1.
int nb_valeurs_temporelles () const
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n-1, n et n+1 donc 3.
void compute_adams_bashforth_coefficients (double time_step, const DoubleTab &times)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Schema_Adams_Bashforth_order_2 & self_cast (Objet_U &)
static const
Schema_Adams_Bashforth_order_2 & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Detailed Description
classe Schema_Adams_Bashforth_order_2
Cette classe represente un schema en temps d'Adams-Bashforth d'ordre 2
a pas de temps variable :
U(n+1) = U(n) + dt*(3/2*(dU/dt)(n)-1/2(dU/dt)(n-1)) si le pas de temps
est constant
Definition at line 39 of file Schema_Adams_Bashforth_order_2.h.
Constructor & Destructor Documentation
Schema_Adams_Bashforth_order_2::Schema_Adams_Bashforth_order_2 ()
Definition at line 28 of file Schema_Adams_Bashforth_order_2.cpp.
Schema_Adams_Bashforth_order_2::~Schema_Adams_Bashforth_order_2 ()
Definition at line 28 of file Schema_Adams_Bashforth_order_2.cpp.
Member Function Documentation
void Schema_Adams_Bashforth_order_2::compute_adams_bashforth_coefficients (double time_step, const DoubleTab & times) [virtual]
Implements Schema_Adams_Bashforth_base.
Definition at line 110 of file Schema_Adams_Bashforth_order_2.cpp.
References Schema_Adams_Bashforth_base::coefficients(), Array_base::NOCOPY_NOINIT, DoubleTab::resize(), and ArrOfDouble::size_array().
{
  assert(times.size_array() == 3); //past, present and future times, stored in ascending order inside "times" table
  if (coefficients().size_array() != 2)
    {
      coefficients().resize(2,Array_base::NOCOPY_NOINIT);
    }
  double past_time          = times[0];
  double present_time       = times[1];
  double future_time        = times[2];
  double past_time_step     = present_time-past_time;
  coefficients()[1] = 1./past_time_step;
  coefficients()[1] *= (future_time+present_time-2*past_time);
  coefficients()[1] *= 0.5;
  assert(coefficients()[1] >= 0.);
  coefficients()[0] = 1-coefficients()[1];
  assert(coefficients()[0] <= 1.);
}
Objet_U * Schema_Adams_Bashforth_order_2::cree_instance () [static]
Definition at line 28 of file Schema_Adams_Bashforth_order_2.cpp.
int Schema_Adams_Bashforth_order_2::duplique () const [virtual]
Implements Schema_Adams_Bashforth_base.
Definition at line 28 of file Schema_Adams_Bashforth_order_2.cpp.
const Type_info * Schema_Adams_Bashforth_order_2::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Adams_Bashforth_base.
Definition at line 28 of file Schema_Adams_Bashforth_order_2.cpp.
const Type_info * Schema_Adams_Bashforth_order_2::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Adams_Bashforth_base.
Definition at line 28 of file Schema_Adams_Bashforth_order_2.cpp.
int Schema_Adams_Bashforth_order_2::nb_pas_dt_seuil () const [inline, virtual]
Renvoie le nombre de pas de temps strictement au dela duquel on applique le schema d Adams-Bahshforth.
Ici : on a besoin d'au moins 1 temps du passe donc 0.
Implements Schema_Explicite_Multi_TimeStep_base.
Definition at line 91 of file Schema_Adams_Bashforth_order_2.cpp.
{
  return 0 ;
}
int Schema_Adams_Bashforth_order_2::nb_valeurs_passees () const [inline, virtual]
Renvoie le nombre de valeurs temporelles du passe.
Ici : n-1 donc 1.
Implements Schema_Explicite_Multi_TimeStep_base.
Definition at line 99 of file Schema_Adams_Bashforth_order_2.cpp.
{
  return 1 ;
}
int Schema_Adams_Bashforth_order_2::nb_valeurs_temporelles () const [virtual]
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n-1, n et n+1 donc 3.
Implements Schema_Temps_base.
Definition at line 83 of file Schema_Adams_Bashforth_order_2.cpp.
{
  return 3 ;
}
Sortie & Schema_Adams_Bashforth_order_2::printOn (Sortie & s) const [protected, virtual]
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Schema_Adams_Bashforth_base.
Definition at line 46 of file Schema_Adams_Bashforth_order_2.cpp.
{
  return  Schema_Adams_Bashforth_base::printOn(s);
}
Entree & Schema_Adams_Bashforth_order_2::readOn (Entree & s) [protected, virtual]
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Schema_Adams_Bashforth_base.
Definition at line 67 of file Schema_Adams_Bashforth_order_2.cpp.
{
  return Schema_Adams_Bashforth_base::readOn(s) ;
}
Schema_Adams_Bashforth_order_2 & Schema_Adams_Bashforth_order_2::self_cast (Objet_U & r) [static]
Reimplemented from Schema_Adams_Bashforth_base.
Definition at line 28 of file Schema_Adams_Bashforth_order_2.cpp.
const Schema_Adams_Bashforth_order_2 & Schema_Adams_Bashforth_order_2::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Schema_Adams_Bashforth_base.
Definition at line 28 of file Schema_Adams_Bashforth_order_2.cpp.
unsigned Schema_Adams_Bashforth_order_2::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 28 of file Schema_Adams_Bashforth_order_2.cpp.
Member Data Documentation
const Type_info Schema_Adams_Bashforth_order_2::info_obj [static]
Reimplemented from Schema_Adams_Bashforth_base.
Definition at line 42 of file Schema_Adams_Bashforth_order_2.h.
The documentation for this class was generated from the following files:
src/Kernel/Schemas_Temps/Schema_Adams_Bashforth_order_2.h
src/Kernel/Schemas_Temps/Schema_Adams_Bashforth_order_2.cpp