TRUST: Eval_Quick_VDF_Elem Class Reference
Eval_Quick_VDF_Elem Class Reference
class Eval_Quick_VDF_Elem
Evaluateur VDF pour la convection
Le champ convecte est scalaire (Champ_P0_VDF)
Schema de convection Quick
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
#include <Eval_Quick_VDF_Elem.h>
Public Member Functions
Eval_Quick_VDF_Elem ()
int calculer_flux_faces_echange_externe_impose () const
int calculer_flux_faces_echange_global_impose () const
int calculer_flux_faces_entree_fluide () const
int calculer_flux_faces_paroi () const
int calculer_flux_faces_paroi_adiabatique () const
int calculer_flux_faces_paroi_defilante () const
int calculer_flux_faces_paroi_fixe () const
int calculer_flux_faces_sortie_libre () const
int calculer_flux_faces_symetrie () const
int calculer_flux_faces_periodique () const
int calculer_flux_faces_NSCBC () const
double flux_face (const DoubleTab &, int, const Dirichlet_entree_fluide &, int) const
double flux_face (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int) const
double flux_face (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int) const
double flux_face (const DoubleTab &, int, int, int, const Echange_externe_impose &, int) const
double flux_face (const DoubleTab &, int, const Echange_global_impose &, int) const
double flux_face (const DoubleTab &, int, const Neumann_paroi &, int) const
double flux_face (const DoubleTab &, int, const Neumann_paroi_adiabatique &, int) const
double flux_face (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double flux_face (const DoubleTab &, int, const Symetrie &, int) const
double flux_face (const DoubleTab &, int, const Periodique &, int) const
double flux_face (const DoubleTab &, int, const NSCBC &, int) const
double flux_faces_interne (const DoubleTab &, int) const
void flux_face (const DoubleTab &, int, const Symetrie &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Periodique &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_entree_fluide &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_paroi_adiabatique &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_paroi &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, int, int, const Echange_externe_impose &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Echange_global_impose &, int, DoubleVect &flux) const
void flux_faces_interne (const DoubleTab &, int, DoubleVect &flux) const
Protected Member Functions
double dim_elem (int, int) const
double dist_elem (int, int, int) const
int amont_amont (int, int) const
double quick_fram (const double &, const int, const int, const int, const int, const int, const DoubleTab &) const
void quick_fram (const double &, const int, const int, const int, const int, const int, const DoubleTab &, ArrOfDouble &) const
Detailed Description
class Eval_Quick_VDF_Elem
Evaluateur VDF pour la convection
Le champ convecte est scalaire (Champ_P0_VDF)
Schema de convection Quick
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
See also:
Eval_Conv_VDF
Definition at line 47 of file Eval_Quick_VDF_Elem.h.
Constructor & Destructor Documentation
Eval_Quick_VDF_Elem::Eval_Quick_VDF_Elem () [inline]
Definition at line 130 of file Eval_Quick_VDF_Elem.h.
{
}
Member Function Documentation
int Eval_Quick_VDF_Elem::amont_amont (int face, int i) const [inline, protected]
Definition at line 661 of file Eval_Quick_VDF_Elem.h.
References Evaluateur_VDF::la_zone.
Referenced by flux_face(), and flux_faces_interne().
{
  return la_zone->amont_amont(face, i);
}
int Eval_Quick_VDF_Elem::calculer_flux_faces_echange_externe_impose () const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 138 of file Eval_Quick_VDF_Elem.h.
{
  return 0;
}
int Eval_Quick_VDF_Elem::calculer_flux_faces_echange_global_impose () const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 147 of file Eval_Quick_VDF_Elem.h.
{
  return 0;
}
int Eval_Quick_VDF_Elem::calculer_flux_faces_entree_fluide () const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 156 of file Eval_Quick_VDF_Elem.h.
{
  return 1;
}
int Eval_Quick_VDF_Elem::calculer_flux_faces_NSCBC () const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 227 of file Eval_Quick_VDF_Elem.h.
{
  return 1;
}
int Eval_Quick_VDF_Elem::calculer_flux_faces_paroi () const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 165 of file Eval_Quick_VDF_Elem.h.
{
  return 0;
}
int Eval_Quick_VDF_Elem::calculer_flux_faces_paroi_adiabatique () const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 174 of file Eval_Quick_VDF_Elem.h.
{
  return 0;
}
int Eval_Quick_VDF_Elem::calculer_flux_faces_paroi_defilante () const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 183 of file Eval_Quick_VDF_Elem.h.
{
  return 0;
}
int Eval_Quick_VDF_Elem::calculer_flux_faces_paroi_fixe () const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 192 of file Eval_Quick_VDF_Elem.h.
{
  return 0;
}
int Eval_Quick_VDF_Elem::calculer_flux_faces_periodique () const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 218 of file Eval_Quick_VDF_Elem.h.
{
  return 1;
}
int Eval_Quick_VDF_Elem::calculer_flux_faces_sortie_libre () const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 201 of file Eval_Quick_VDF_Elem.h.
{
  return 1;
}
int Eval_Quick_VDF_Elem::calculer_flux_faces_symetrie () const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 210 of file Eval_Quick_VDF_Elem.h.
{
  return 0;
}
double Eval_Quick_VDF_Elem::dim_elem (int n1, int k) const [inline, protected]
Definition at line 757 of file Eval_Quick_VDF_Elem.h.
References Evaluateur_VDF::la_zone.
Referenced by quick_fram().
{
  return la_zone->dim_elem(n1,k);
}
double Eval_Quick_VDF_Elem::dist_elem (int n1, int n2, int k) const [inline, protected]
Definition at line 763 of file Eval_Quick_VDF_Elem.h.
References Evaluateur_VDF::la_zone.
Referenced by quick_fram().
{
  return la_zone->dist_elem_period(n1,n2,k);
}
void Eval_Quick_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const [inline]
< n1 != -1
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 529 of file Eval_Quick_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  int k;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (n0 != -1)
    {
      if (psc > 0)
        for (k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n0,k);
      else
        for (k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1,k);
    }
  else  //!< n1 != -1
    {
      if (psc > 0)
        for (k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1,k);
      else
        for (k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n1,k);
    }
}
void Eval_Quick_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Periodique & la_cl, int , DoubleVect & flux) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 569 of file Eval_Quick_VDF_Elem.h.
References amont_amont(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, quick_fram(), DoubleVect::size(), and Evaluateur_VDF::surface.
{
// Codage Periodique
// 30/05/2002
// ALEX C.
  int k;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  int n0_0 = amont_amont(face,0);
  int n1_1 = amont_amont(face,1);
// on applique le schema Quick
  quick_fram(psc,n0,n1,n0_0,n1_1,face,inco,flux);
  for (k=0; k<flux.size(); k++)
    flux(k) *= -1;
}
void Eval_Quick_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1, DoubleVect & flux) const [inline]
< n1 != -1
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 440 of file Eval_Quick_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), Evaluateur_VDF::surface, and Dirichlet::val_imp().
{
  int k;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = dt_vitesse(face)*surface(face)*porosite(face);
  if (n0 != -1)
    {
      if (psc > 0)
        for (k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n0,k);
      else
        for (k=0; k<flux.size(); k++)
          flux(k)= -psc*la_cl.val_imp(face-num1,k);
    }
  else //!< n1 != -1
    {
      if (psc>0)
        for (k=0; k<flux.size(); k++)
          flux(k)= -psc*la_cl.val_imp(face-num1,k);
      else
        for (k=0; k<flux.size(); k++)
          flux(k)= -psc*inco(n1,k);
    }
}
void Eval_Quick_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 481 of file Eval_Quick_VDF_Elem.h.
{
  ;
}
void Eval_Quick_VDF_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 519 of file Eval_Quick_VDF_Elem.h.
{
  ;
}
double Eval_Quick_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Periodique & la_cl, int) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 361 of file Eval_Quick_VDF_Elem.h.
References amont_amont(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, quick_fram(), and Evaluateur_VDF::surface.
{
// 31/05/2002
// ALEX C.
  double flux;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  int n0_0 = amont_amont(face,0);
  int n1_1 = amont_amont(face,1);
// on applique le schema Quick_fram
  flux = quick_fram(psc,n0,n1,n0_0,n1_1,face,inco);
  return -flux;
}
double Eval_Quick_VDF_Elem::flux_face (const DoubleTab & , int , const Echange_global_impose & , int) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 297 of file Eval_Quick_VDF_Elem.h.
{
  return 0;
}
double Eval_Quick_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1) const [inline]
< n1 != -1
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 325 of file Eval_Quick_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double flux;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (n0 != -1)
    {
      if (psc > 0)
        flux= psc*inco[n0];
      else
        flux= psc*la_cl.val_ext(face-num1);
    }
  else   //!< n1 != -1
    {
      if (psc > 0)
        flux=psc*la_cl.val_ext(face-num1);
      else
        flux= psc*inco[n1];
    }
  return -flux;
}
double Eval_Quick_VDF_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 315 of file Eval_Quick_VDF_Elem.h.
{
  return 0;
}
void Eval_Quick_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 471 of file Eval_Quick_VDF_Elem.h.
{
  ;
}
void Eval_Quick_VDF_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi & , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 509 of file Eval_Quick_VDF_Elem.h.
{
  ;
}
double Eval_Quick_VDF_Elem::flux_face (const DoubleTab & , int , int , int , const Echange_externe_impose & , int) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 288 of file Eval_Quick_VDF_Elem.h.
{
  return 0;
}
double Eval_Quick_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 276 of file Eval_Quick_VDF_Elem.h.
{
  return 0;
}
double Eval_Quick_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 267 of file Eval_Quick_VDF_Elem.h.
{
  return 0;
}
void Eval_Quick_VDF_Elem::flux_face (const DoubleTab & , int , const Symetrie & , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 559 of file Eval_Quick_VDF_Elem.h.
{
  ;
}
double Eval_Quick_VDF_Elem::flux_face (const DoubleTab & inco, int face, const NSCBC & la_cl, int num1) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 380 of file Eval_Quick_VDF_Elem.h.
References Cerr, Process::exit(), and finl.
{
  double flux=0;
  Cerr<<"Eval_Quick_VDF_Elem::flux_face n'est pas codee"<<finl;
  Cerr<<"pour la condition NSCBC"<<finl;
  Process::exit();
  return -flux;
}
double Eval_Quick_VDF_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi & , int) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 306 of file Eval_Quick_VDF_Elem.h.
{
  return 0;
}
double Eval_Quick_VDF_Elem::flux_face (const DoubleTab & , int , const Symetrie & , int) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 352 of file Eval_Quick_VDF_Elem.h.
{
  return 0;
}
void Eval_Quick_VDF_Elem::flux_face (const DoubleTab & , int , int , int , const Echange_externe_impose & , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 490 of file Eval_Quick_VDF_Elem.h.
{
  ;
}
void Eval_Quick_VDF_Elem::flux_face (const DoubleTab & , int , const Echange_global_impose & , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 500 of file Eval_Quick_VDF_Elem.h.
{
  ;
}
double Eval_Quick_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1) const [inline]
< n1 != -1
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 239 of file Eval_Quick_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Dirichlet::val_imp().
{
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double flux;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  double T_imp = la_cl.val_imp(face-num1);
  if (n0 != -1)
    {
      if (psc > 0)
        flux= psc*inco[n0];
      else
        flux= psc*T_imp;
    }
  else   //!< n1 != -1
    {
      if (psc>0)
        flux= psc*T_imp;
      else
        flux= psc*inco[n1];
    }
  return -flux;
}
void Eval_Quick_VDF_Elem::flux_faces_interne (const DoubleTab & inco, int face, DoubleVect & flux) const [inline]
< on applique le schema Quick
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 593 of file Eval_Quick_VDF_Elem.h.
References amont_amont(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, quick_fram(), DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  int n0_0 = amont_amont(face,0);
  int n1_1 = amont_amont(face,1);
  /*
    if ((n0_0 == -1)||(n1_1 == -1))
    // Alexandre C. : 19/02/2003
    // We do not use the first order upwind scheme as it was done before
    // because in LES computations all turbulence is damped and we can not
    // recover a proper behaviour of physical turbulent characteristics,
    // especially when using wall-functions !
    // Therefore we use the 2nd order centered scheme.
    for (k=0; k<flux.size(); k++)
    flux(k) = -psc*(inco(n0,k)+inco(n1,k))/2.;
    Pierre L. 14/10/04: Correction car le centre explose sur le cas VALIDA
    On revient au quick en essayant d'ameliorer: on prend le quick si psc
    est encore favorable pour avoir les 3 points necessaires au calcul du
    quick. Cela est deja ce qui est fait pour le quick-sharp de l'evaluateur
    aux faces.
  */
  if ( (n0_0 == -1 && psc >= 0 ) || (n1_1 == -1 && psc <= 0 ) )
    {
      if (psc > 0)
        for (k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n0,k);
      else
        for (k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n1,k);
    }
  else //!< on applique le schema Quick
    {
      quick_fram(psc,n0,n1,n0_0,n1_1,face,inco,flux);
      for (k=0; k<flux.size(); k++)
        flux(k) *= -1;
    }
}
double Eval_Quick_VDF_Elem::flux_faces_interne (const DoubleTab & inco, int face) const [inline]
< on applique le schema Quick_fram
Reimplemented from Eval_Amont_VDF_Elem.
Definition at line 396 of file Eval_Quick_VDF_Elem.h.
References amont_amont(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, quick_fram(), and Evaluateur_VDF::surface.
{
  double flux;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  int n0_0 = amont_amont(face,0);
  int n1_1 = amont_amont(face,1);
  /*
       if ( (n0_0 == -1) || (n1_1 == -1) )
       // Alexandre C. : 19/02/2003
       // We do not use the first order upwind scheme as it was done before
       // because in LES computations all turbulence is damped and we can not
       // recover a proper behaviour of physical turbulent characteristics,
       // especially when using wall-functions.
       // Therefore we use the 2nd order centered scheme.
       flux = psc*(inco(n0)+inco(n1))/2.;
       Pierre L. 14/10/04: Correction car le centre explose sur le cas VALIDA
       On revient au quick en essayant d'ameliorer: on prend le quick si psc
       est encore favorable pour avoir les 3 points necessaires au calcul du
       quick. Cela est deja ce qui est fait pour le quick-sharp de l'evaluateur
       aux faces.
  */
  if ( (n0_0 == -1 && psc >= 0 ) || (n1_1 == -1 && psc <= 0 ) )
    {
      if (psc > 0)
        flux = psc*inco(n0);
      else
        flux = psc*inco(n1);
    }
  else  //!< on applique le schema Quick_fram
    flux = quick_fram(psc,n0,n1,n0_0,n1_1,face,inco);
  return -flux;
}
double Eval_Quick_VDF_Elem::quick_fram (const double & psc, const int num0, const int num1, const int num0_0, const int num1_1, const int face, const DoubleTab & transporte) const [inline, protected]
Definition at line 670 of file Eval_Quick_VDF_Elem.h.
References dim_elem(), dist_elem(), Fram(), and Evaluateur_VDF::orientation.
Referenced by flux_face(), and flux_faces_interne().
{
  double flux,trans_amont,fr;
  int ori = orientation(face);
  double dx = dist_elem(num0, num1, ori);
  double curv;
  double T0 = transporte[num0];
  double T1 = transporte[num1];
  double T0_0=-1,T1_1=-1;
  if (num0_0 != -1) T0_0 = transporte[num0_0];
  if (num1_1 != -1) T1_1 = transporte[num1_1];
  if (psc > 0)
    {
      assert(num0_0!=-1);
      trans_amont = T0;
      double dm = dim_elem(num0, ori);
      double dxam = dist_elem(num0_0, num0, ori);
      curv = ( (T1 - T0)/dx - (T0 - T0_0)/dxam )/dm ;
    }
  else
    {
      assert(num1_1!=-1);
      trans_amont = T1;
      double dm = dim_elem(num1, ori);
      double dxam = dist_elem(num1, num1_1, ori);
      curv = ( (T1_1 - T1)/dxam - (T1 - T0)/dx )/dm;
    }
  flux = 0.5*(T0+T1) - 0.125*(dx*dx)*curv;
  if ( num0_0 != -1 && num1_1 != -1 )
    fr = Fram(T0_0,T0,T1,T1_1);
  else
    fr = 1.;
  flux = ((1.-fr)*flux + fr*trans_amont)*psc;
  return flux;
}
void Eval_Quick_VDF_Elem::quick_fram (const double & psc, const int num0, const int num1, const int num0_0, const int num1_1, const int face, const DoubleTab & transporte, ArrOfDouble & flux) const [inline, protected]
Definition at line 714 of file Eval_Quick_VDF_Elem.h.
References dim_elem(), dist_elem(), Fram(), Evaluateur_VDF::orientation, and ArrOfDouble::size_array().
{
  int ori = orientation(face);
  double dx = dist_elem(num0, num1, ori);
  double T0,T0_0=0,T1,T1_1=0,trans_amont,curv;
  double fr;
  double dm0 = dim_elem(num0, ori);
  double dxam0 = (num0_0!=-1?dist_elem(num0_0, num0, ori):0);
  double dm1 = dim_elem(num1, ori);
  double dxam1 = (num1_1!=-1?dist_elem(num1, num1_1, ori):0);
  int ncomp = flux.size_array();
  for (int k=0; k<ncomp; k++)
    {
      T0 = transporte(num0,k);
      T0_0 = (num0_0!=-1?transporte(num0_0,k):0);
      T1 = transporte(num1,k);
      T1_1 = (num1_1!=-1?transporte(num1_1,k):0);
      if (psc > 0)
        {
          assert(num0_0!=-1);
          trans_amont = T0;
          curv = ( (T1 - T0)/dx - (T0 - T0_0)/dxam0 )/dm0 ;
        }
      else
        {
          assert(num1_1!=-1);
          trans_amont = T1;
          curv = ( (T1_1 - T1)/dxam1 - (T1 - T0)/dx )/dm1;
        }
      flux(k) = 0.5*(T0+T1) - 0.125*(dx*dx)*curv;
// On applique le filtre Fram:
      if ( num0_0 != -1 && num1_1 != -1 )
        fr = Fram(T0_0,T0,T1,T1_1);
      else
        fr = 1.;
      flux(k) = ((1.-fr)*flux(k) + fr*trans_amont)*psc;
    }
}
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs/Eval_Quick_VDF_Elem.h