TRUST: Eval_Conv_VDF Class Reference
Eval_Conv_VDF Class Reference
class Eval_Conv_VDF
classe de base des evaluateurs de convection VDF
#include <Eval_Conv_VDF.h>
Public Member Functions
Eval_Conv_VDF ()
Eval_Conv_VDF (const Eval_Conv_VDF &eval)
void associer (const Champ_Face &)
associe le champ de vitesse transportante
void mettre_a_jour ()
const Champ_Inc_base & vitesse () const
Champ_Inc_base & vitesse ()
int get_elem (int i, int j) const
int get_orientation (int i) const
int get_premiere_face_bord () const
double get_dt_vitesse (int face) const
double get_surface_porosite (int face) const
double get_surface (int face) const
double get_porosite (int face) const
const Zone_Cl_VDF & get_la_zcl () const
Public Member Functions inherited from Evaluateur_VDF
Evaluateur_VDF ()
virtual ~Evaluateur_VDF ()
Evaluateur_VDF (const Evaluateur_VDF &)
virtual void associer_zones (const Zone_VDF &, const Zone_Cl_VDF &)
virtual void associer_porosite (const DoubleVect &)
double dist_face_period (int fac1, int fac2, int k) const
double dist_face (int fac1, int fac2, int k) const
Public Member Functions inherited from Eval_Conv_VDF_tools
virtual ~Eval_Conv_VDF_tools ()
virtual int amont_amont (int face, int i) const
virtual int face_amont_conj (int, int, int) const
virtual int face_amont_princ (int, int) const
virtual double dim_elem (int, int) const
virtual double dim_face (int, int) const
virtual double dist_elem (int, int, int) const
virtual double dist_elem_period (int, int, int) const
virtual double conv_centre (const double, const double, const double, const double, const double, double, double, double, double) const
virtual double conv_quick_sharp_plus (const double, const double, const double, const double, const double, const double, const double) const
virtual double conv_quick_sharp_moins (const double, const double, const double, const double, const double, const double, const double) const
virtual void calcul_g (const double, const double, const double, double &, double &, double &, double &) const
template<typename Type_Double >
void qcentre (const double, const int, const int, const int, const int, const int, const DoubleTab &, Type_Double &) const
template<typename Type_Double >
void quick_fram (const double, const int, const int, const int, const int, const int, const DoubleTab &, Type_Double &) const
Protected Attributes
Ref_Champ_Face vitesse_
DoubleTab dt_vitesse
Protected Attributes inherited from Evaluateur_VDF
Ref_Zone_VDF la_zone
Ref_Zone_Cl_VDF la_zcl
int dimension
int premiere_face_bord
IntTab elem_
les 2 elements voisins d'une face
DoubleVect surface
surfaces des faces
IntVect orientation
orientations des faces
DoubleVect porosite
porosites surfaciques
DoubleVect volume_entrelaces
DoubleTab xv
coord des centres des faces
Additional Inherited Members
Protected Member Functions inherited from Evaluateur_VDF
double dist_norm_bord (int) const
Protected Member Functions inherited from Eval_Conv_VDF_tools
int face_amont_conj_axi_impl (int, int, int, int, const IntTab &, const IntTab &, const IntVect &) const
double dist_face_axi_impl (int, int, int, const DoubleTab &) const
double dist_elem_axi_impl (int, int, int, const DoubleTab &) const
double conv_quick_sharp_plus_impl (const double, const double, const double, const double, const double, const double, const double) const
double conv_quick_sharp_moins_impl (const double, const double, const double, const double, const double, const double, const double) const
void calcul_g_impl (const double, const double, const double, double &, double &, double &, double &) const
template<typename Type_Double >
void qcentre2_impl (const double, const int, const int, const int, const int, const int, const DoubleTab &, Type_Double &) const
template<typename Type_Double >
void qcentre4_impl (const int, const double, const double, const double, const double, const int, const int, const int, const int, const int, const DoubleTab &, Type_Double &) const
template<typename Type_Double >
void quick_fram_impl (const int, const double, const double, const double, const double, const double, const double, const int, const int, const int, const int, const int, const DoubleTab &, Type_Double &) const
Detailed Description
class Eval_Conv_VDF
classe de base des evaluateurs de convection VDF
Definition at line 29 of file Eval_Conv_VDF.h.
Constructor & Destructor Documentation
Eval_Conv_VDF() [1/2]
Eval_Conv_VDF::Eval_Conv_VDF () inline
Definition at line 34 of file Eval_Conv_VDF.h.
{}
Eval_Conv_VDF() [2/2]
Eval_Conv_VDF::Eval_Conv_VDF (const Eval_Conv_VDF & eval) inline
Definition at line 35 of file Eval_Conv_VDF.h.
: Evaluateur_VDF(eval), vitesse_(eval.vitesse_) { dt_vitesse.ref(eval.dt_vitesse); }
References dt_vitesse, and TRUSTTab< _TYPE_ >::ref().
Member Function Documentation
associer()
void Eval_Conv_VDF::associer (const Champ_Face & vit) inline
associe le champ de vitesse transportante
Definition at line 59 of file Eval_Conv_VDF.h.
{
  vitesse_=vit;
  dt_vitesse.ref(vit.valeurs());
}
References dt_vitesse, TRUSTTab< _TYPE_ >::ref(), Champ_Inc_base::valeurs(), and vitesse_.
get_dt_vitesse()
double Eval_Conv_VDF::get_dt_vitesse (int face) const inline
Definition at line 46 of file Eval_Conv_VDF.h.
{ return dt_vitesse(face); }
References dt_vitesse.
get_elem()
int Eval_Conv_VDF::get_elem (int i, int j) const inline
Definition at line 43 of file Eval_Conv_VDF.h.
{ return elem_(i,j); }
References Evaluateur_VDF::elem_.
get_la_zcl()
const Zone_Cl_VDF & Eval_Conv_VDF::get_la_zcl () const inline
Definition at line 50 of file Eval_Conv_VDF.h.
{ return la_zcl.valeur(); }
References Evaluateur_VDF::la_zcl, and Ref_Zone_Cl_VDF::valeur().
get_orientation()
int Eval_Conv_VDF::get_orientation (int i) const inline
Definition at line 44 of file Eval_Conv_VDF.h.
{ return orientation(i); }
References Evaluateur_VDF::orientation.
get_porosite()
double Eval_Conv_VDF::get_porosite (int face) const inline
Definition at line 49 of file Eval_Conv_VDF.h.
{ return porosite(face); }
References Evaluateur_VDF::porosite.
get_premiere_face_bord()
int Eval_Conv_VDF::get_premiere_face_bord () const inline
Definition at line 45 of file Eval_Conv_VDF.h.
{ return premiere_face_bord; }
References Evaluateur_VDF::premiere_face_bord.
get_surface()
double Eval_Conv_VDF::get_surface (int face) const inline
Definition at line 48 of file Eval_Conv_VDF.h.
{ return surface(face); }
References Evaluateur_VDF::surface.
get_surface_porosite()
double Eval_Conv_VDF::get_surface_porosite (int face) const inline
Definition at line 47 of file Eval_Conv_VDF.h.
{ return surface(face)*porosite(face); }
References Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
mettre_a_jour()
void Eval_Conv_VDF::mettre_a_jour () inline
Definition at line 38 of file Eval_Conv_VDF.h.
{ dt_vitesse.ref(vitesse_->valeurs()); }
References dt_vitesse, TRUSTTab< _TYPE_ >::ref(), Champ_Inc_base::valeurs(), and vitesse_.
vitesse() [1/2]
Champ_Inc_base & Eval_Conv_VDF::vitesse () inline
Definition at line 40 of file Eval_Conv_VDF.h.
{ return vitesse_.valeur(); }
References Ref_Champ_Face::valeur(), and vitesse_.
vitesse() [2/2]
const Champ_Inc_base & Eval_Conv_VDF::vitesse () const inline
Definition at line 39 of file Eval_Conv_VDF.h.
{ return vitesse_.valeur(); }
References Ref_Champ_Face::valeur(), and vitesse_.
Member Data Documentation
dt_vitesse
DoubleTab Eval_Conv_VDF::dt_vitesse protected
Definition at line 54 of file Eval_Conv_VDF.h.
Referenced by associer(), Eval_Conv_VDF(), get_dt_vitesse(), and mettre_a_jour().
vitesse_
Ref_Champ_Face Eval_Conv_VDF::vitesse_ protected
Definition at line 53 of file Eval_Conv_VDF.h.
Referenced by associer(), mettre_a_jour(), and vitesse().
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Eval_Conv/Eval_Conv_VDF.h