TRUST: DP_Impose Class Reference
DP_Impose Class Reference
Classe DP_Impose
Cette classe derivee de Perte_Charge_Singuliere est utilisee lorsque l'on veut
impose un Delta P (pour simuler une pompe) depuis un champ exterieur
par exemple)
#include <DP_Impose.h>
Public Member Functions
~DP_Impose () override
Entree & lire_donnees (Entree &)
Lit les specifications d'un Delta P impose
a partir d'un flot d'entree.
void mettre_a_jour (double temps)
Public Member Functions inherited from Perte_Charge_Singuliere
virtual ~Perte_Charge_Singuliere ()
Entree & lire_donnees (Entree &)
Lit les specifications d'une perte de charge singuliere
a partir d'un flot d'entree.
virtual void lire_surfaces (Entree &, const Domaine &, const Zone_dis_base &, IntVect &, IntVect &)
double K () const
double calculate_Q (const Equation_base &eqn, const IntVect &num_faces, const IntVect &sgn) const
void update_K (const Equation_base &eqn, double deb, DoubleVect &bilan)
Public Member Functions inherited from Perte_Charge
int direction_perte_charge () const
Renvoie la direction de perte de charge.
(X,Y ou Z), ou -1 si toutes les directions.
Protected Attributes
Champ_Don DP_
Protected Attributes inherited from Perte_Charge_Singuliere
double K_
Nom identifiant_
int regul_
Parser_U deb_cible_
Parser_U eps_
Protected Attributes inherited from Perte_Charge
int direction_perte_charge_
Detailed Description
Classe DP_Impose
Cette classe derivee de Perte_Charge_Singuliere est utilisee lorsque l'on veut
impose un Delta P (pour simuler une pompe) depuis un champ exterieur
par exemple)
Definition at line 32 of file DP_Impose.h.
Constructor & Destructor Documentation
~DP_Impose()
DP_Impose::~DP_Impose () inline override
Definition at line 37 of file DP_Impose.h.
{}
Member Function Documentation
lire_donnees()
Entree & DP_Impose::lire_donnees (Entree & is)
Lit les specifications d'un Delta P impose
a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Definition at line 33 of file DP_Impose.cpp.
{
  Motcle acc_ouverte("{");
  Motcle motlu;
  is >> motlu;
  if (motlu != acc_ouverte)
    {
      Cerr << "On attendait le mot cle" << acc_ouverte << " a la place de " << motlu << finl;
      Process::exit();
    }
// juste le champ de DP!
  is >> motlu;
  if (motlu != "dp")
    {
      Cerr << "On attendait le mot cle dp a la place de " << motlu << finl;
      Process::exit();
    }
  is >> DP_;
  regul_ = 0;
  return is;
}
References Cerr, DP_, Process::exit(), finl, and Perte_Charge_Singuliere::regul_.
Referenced by DP_Impose_PolyMAC_Face::readOn().
mettre_a_jour()
void DP_Impose::mettre_a_jour (double temps)
Definition at line 55 of file DP_Impose.cpp.
{
  DP_.mettre_a_jour(temps);
}
References DP_, and Champ_Don::mettre_a_jour().
Referenced by DP_Impose_PolyMAC_Face::mettre_a_jour().
Member Data Documentation
DP_
Champ_Don DP_Impose::DP_ protected
Definition at line 43 of file DP_Impose.h.
Referenced by DP_Impose_PolyMAC_Face::ajouter_blocs(), lire_donnees(), and mettre_a_jour().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Sources/DP_Impose.h
src/ThHyd/Incompressible/Sources/DP_Impose.cpp