TRUST: Assembleur_P_VEF Class Reference
Assembleur_P_VEF Class Reference
#include <Assembleur_P_VEF.h>
Public Member Functions
Assembleur_P_VEF ()
~Assembleur_P_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &) override
const Zone_dis_base & zone_dis_base () const override
const Zone_Cl_dis_base & zone_Cl_dis_base () const override
int assembler (Matrice &) override
int assembler_mat (Matrice &, const DoubleVect &, int, int) override
int remplir (Matrice &, const DoubleTab &)
int remplir (Matrice &, const DoubleVect &)
int assembler_QC (const DoubleTab &, Matrice &) override
Assemble la matrice de pression pour un fluide quasi compressible
laplacein(P) est remplace par div(grad(P)/rho).
int modifier_secmem (DoubleTab &) override
int modifier_solution (DoubleTab &) override
virtual int modifier_matrice (Matrice &)
Modifier eventuellement la matrice pour la rendre definie si elle ne l'est pas
Valeurs par defaut:
Contraintes:
Acces: lecture.
void completer (const Equation_base &) override
const Equation_base & equation () const
Public Member Functions inherited from Assembleur_base
Assembleur_base ()
~Assembleur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int set_resoudre_increment_pression (int flag)
Definit la valeur du drapeau resoudre_increment_pression_.
Ce drapeau determine si le solveur en pression calcule un increment de
pression entre deux pas de temps ou la pression totale (cela affecte
en particulier le calcul des conditions aux limites).
flag = 0 : resolution en pression
flag = 1 : resolution en increment de pression.
int get_resoudre_increment_pression () const
Renvoie la valeur du drapeau resoudre_increment_pression_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
int set_resoudre_en_u (int flag)
Definit la valeur du drapeau resoudre_en_u__.
Ce drapeau determine si le solveur en pression resou en u ou en rho*u
(cela affecte
en particulier le calcul des conditions aux limites Dirichlet).
flag = 1 : resolution en u
flag = 0 : resolution en rho_u.
int get_resoudre_en_u () const
Renvoie la valeur du drapeau resoudre_en_u_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
virtual int assembler (Matrice &)=0
virtual int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u)
virtual int assembler_rho_variable (Matrice &, const Champ_Don_base &rho)
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
virtual int assembler_QC (const DoubleTab &, Matrice &)
virtual void completer (const Equation_base &)=0
virtual void associer_zone_dis_base (const Zone_dis_base &)=0
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)=0
virtual const Zone_dis_base & zone_dis_base () const =0
virtual const Zone_Cl_dis_base & zone_Cl_dis_base () const =0
virtual int modifier_secmem (DoubleTab &)=0
virtual void modifier_secmem_pour_incr_p (const DoubleTab &press, const double fac, DoubleTab &incr) const
virtual int modifier_solution (DoubleTab &)=0
virtual void dimensionner_continuite (matrices_t matrices, int aux_only=0) const
virtual void assembler_continuite (matrices_t matrices, DoubleTab &secmem, int aux_only=0) const
virtual DoubleTab norme_continuite () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Assembleur_P_VEF & self_cast (Objet_U &)
static const Assembleur_P_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Assembleur_base
static const Type_info * info ()
static Assembleur_base & self_cast (Objet_U &)
static const Assembleur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Assembleur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void calculer_inv_volume (DoubleTab &inv_volumes_entrelaces, const Zone_Cl_VEF &zone_Cl_VEF, const DoubleVect &volumes_entrelaces)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Equation_base mon_equation
Ref_Zone_VEF la_zone_VEF
Ref_Zone_Cl_VEF la_zone_Cl_VEF
DoubleTab les_coeff_pression
int has_P_ref
Detailed Description
Definition at line 31 of file Assembleur_P_VEF.h.
Constructor & Destructor Documentation
Assembleur_P_VEF()
Assembleur_P_VEF::Assembleur_P_VEF ()
Definition at line 27 of file Assembleur_P_VEF.cpp.
~Assembleur_P_VEF()
Assembleur_P_VEF::~Assembleur_P_VEF ()
Definition at line 27 of file Assembleur_P_VEF.cpp.
Member Function Documentation
assembler()
int Assembleur_P_VEF::assembler (Matrice & la_matrice) override virtual
Implements Assembleur_base.
Definition at line 39 of file Assembleur_P_VEF.cpp.
{
// Si rho est constant, on resout avec la pression P*=P/rho
  const DoubleVect& volumes_entrelaces_ref=la_zone_VEF->volumes_entrelaces();
  DoubleVect volumes_entrelaces(volumes_entrelaces_ref);
  const DoubleVect& volumes_entrelaces_cl=la_zone_Cl_VEF.valeur().volumes_entrelaces_Cl();
  int size=volumes_entrelaces_cl.size();
  for (int f=0; f<size; f++)
    if (volumes_entrelaces_cl(f)!=0)
      {
// if (volumes_entrelaces(f)!=volumes_entrelaces_cl(f))   Cerr<<f <<" vl" << volumes_entrelaces(f)<< " "<<volumes_entrelaces_cl(f)<<finl;
        volumes_entrelaces(f)=volumes_entrelaces_cl(f);
      }
  volumes_entrelaces.echange_espace_virtuel();
// On assemble la matrice
  return assembler_mat(la_matrice,volumes_entrelaces,1,1);
}
References assembler_mat(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), la_zone_Cl_VEF, la_zone_VEF, TRUSTVect< _TYPE_ >::size(), Ref_Zone_Cl_VEF::valeur(), Zone_VF::volumes_entrelaces(), and Zone_Cl_VEF::volumes_entrelaces_Cl().
Referenced by Assembleur_P_VEFPreP1B::assembler(), and assembler_QC().
assembler_mat()
int Assembleur_P_VEF::assembler_mat (Matrice & la_matrice, const DoubleVect & volumes_entrelaces, int incr_pression, int resoudre_en_u) override virtual
Reimplemented from Assembleur_base.
Definition at line 111 of file Assembleur_P_VEF.cpp.
{
// On fixe les drapeaux de Assembleur_base
  set_resoudre_increment_pression(incr_pression);
  set_resoudre_en_u(resoudre_en_u);
  DoubleTab inv_volumes_entrelaces;
  const Zone_Cl_VEF& zone_Cl_VEF = la_zone_Cl_VEF.valeur();
  DoubleTab inverse_quantitee_entrelacee;
  calculer_inv_volume(inverse_quantitee_entrelacee, zone_Cl_VEF, volumes_entrelaces);
  remplir(la_matrice, inverse_quantitee_entrelacee);
  modifier_matrice(la_matrice);
  return 1;
}
References calculer_inv_volume(), la_zone_Cl_VEF, modifier_matrice(), remplir(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), and Ref_Zone_Cl_VEF::valeur().
Referenced by assembler().
assembler_QC()
int Assembleur_P_VEF::assembler_QC (const DoubleTab & tab_rho, Matrice & matrice) override virtual
Assemble la matrice de pression pour un fluide quasi compressible
laplacein(P) est remplace par div(grad(P)/rho).
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 585 of file Assembleur_P_VEF.cpp.
{
  Cerr << "Assemblage de la matrice de pression pour Quasi Compressible en cours..." << finl;
  int stat=assembler(matrice);
  set_resoudre_en_u(0);
  return stat;
}
References assembler(), Cerr, finl, and Assembleur_base::set_resoudre_en_u().
associer_zone_cl_dis_base()
void Assembleur_P_VEF::associer_zone_cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis) override virtual
Implements Assembleur_base.
Definition at line 746 of file Assembleur_P_VEF.cpp.
{
  la_zone_Cl_VEF = ref_cast(Zone_Cl_VEF, la_zone_Cl_dis);
}
References la_zone_Cl_VEF, and ref_cast.
Referenced by assemblerP0P0(), and updateP0P0().
associer_zone_dis_base()
void Assembleur_P_VEF::associer_zone_dis_base (const Zone_dis_base & la_zone_dis) override virtual
Implements Assembleur_base.
Definition at line 741 of file Assembleur_P_VEF.cpp.
{
  la_zone_VEF = ref_cast(Zone_VEF,la_zone_dis);
}
References la_zone_VEF, and ref_cast.
Referenced by assemblerP0P0(), and updateP0P0().
calculer_inv_volume()
void Assembleur_P_VEF::calculer_inv_volume (DoubleTab & inv_volumes_entrelaces, const Zone_Cl_VEF & zone_Cl_VEF, const DoubleVect & volumes_entrelaces) protected
Definition at line 69 of file Assembleur_P_VEF.cpp.
{
// maintenant l 'inverse du volume est un DoubleTab
// c'est pour faire fonctionner le Piso
  const DoubleTab* doubleT = dynamic_cast<const DoubleTab*>(&volumes_entrelaces);
  if (doubleT)
    {
      calculer_inv_volume_special(inv_volumes_entrelaces, zone_Cl_VEF,*doubleT);
      return;
    }
  int taille=volumes_entrelaces.size_totale();
  inv_volumes_entrelaces.resize(taille,Objet_U::dimension);
  if (0)
    {
// cette facon de calculer le volume entrelace pourra etre bonne dans
// l'avenir a condition de reflechir au pb des porosites
// et SURTOUT au pb du simpler ou l'on ne veut pas passer par la
      DoubleTab tmp;
      tmp=(inv_volumes_entrelaces);
      tmp=1;
      zone_Cl_VEF.equation().solv_masse().appliquer(tmp);
      int sz=inv_volumes_entrelaces.size_totale();
      for (int i=0; i<sz; i++)
        {
          inv_volumes_entrelaces(i)=tmp(i);
          if (!est_egal(inv_volumes_entrelaces(i),1./volumes_entrelaces(i)))
            Cerr<<i<<" "<<inv_volumes_entrelaces(i)-1./volumes_entrelaces(i)<<" "<<inv_volumes_entrelaces(i)<<finl;;
        }
      Process::exit();
    }
  else
    {
      const DoubleVect& porosite_face=la_zone_VEF->porosite_face();
      for (int i=0; i<taille; i++)
        for (int comp=0; comp<Objet_U::dimension; comp++)
          inv_volumes_entrelaces(i,comp)=1./volumes_entrelaces(i)*porosite_face(i);
    }
}
References Solveur_Masse::appliquer(), calculer_inv_volume_special(), Cerr, Objet_U::dimension, MorEqn::equation(), est_egal(), Process::exit(), finl, la_zone_VEF, Zone_VF::porosite_face(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size_totale(), and Equation_base::solv_masse().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), and assembler_mat().
completer()
void Assembleur_P_VEF::completer (const Equation_base & Eqn) override virtual
Implements Assembleur_base.
Definition at line 751 of file Assembleur_P_VEF.cpp.
{
  mon_equation=Eqn;
}
References mon_equation.
Referenced by Assembleur_P_VEFPreP1B::completer().
cree_instance()
Objet_U * Assembleur_P_VEF::cree_instance () static
Definition at line 27 of file Assembleur_P_VEF.cpp.
duplique()
int Assembleur_P_VEF::duplique () const override virtual
Implements Objet_U.
Definition at line 27 of file Assembleur_P_VEF.cpp.
equation()
const Equation_base & Assembleur_P_VEF::equation () const inline
Definition at line 66 of file Assembleur_P_VEF.h.
{
  if (mon_equation.non_nul()==0)
    {
      Cerr << "\nError in Assembleur_P_VEF::equation() : The equation is unknown !" << finl;
      Process::exit();
    }
  return  mon_equation.valeur();
}
References Cerr, Process::exit(), finl, mon_equation, O_U_Ptr::non_nul(), and Ref_Equation_base::valeur().
get_info()
const Type_info * Assembleur_P_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 27 of file Assembleur_P_VEF.cpp.
info()
const Type_info * Assembleur_P_VEF::info () static
Definition at line 27 of file Assembleur_P_VEF.cpp.
modifier_matrice()
int Assembleur_P_VEF::modifier_matrice (Matrice & matrice) virtual
Modifier eventuellement la matrice pour la rendre definie si elle ne l'est pas
Valeurs par defaut:
Contraintes:
Acces: lecture.
Returns
int
Signification: renvoie 1 si la matrice est modifiee 0 sinon
Contraintes:
Reimplemented in Assembleur_P_VEFPreP1B.
Definition at line 699 of file Assembleur_P_VEF.cpp.
{
  int matrice_modifiee=0;
  Matrice_Bloc& mat_bloc = ref_cast(Matrice_Bloc, matrice.valeur());
  Matrice_Morse_Sym& A00RR = ref_cast(Matrice_Morse_Sym,mat_bloc.get_bloc(0,0).valeur());
// Recherche de l'element sur lequel on impose la pression de reference
  if (Process::je_suis_maitre() && !A00RR.get_est_definie())
    {
      int element_referent=0;
      double distance=DMAXFLOAT;
      const DoubleTab& coord=la_zone_VEF->xp();
      int n = la_zone_VEF.valeur().nb_elem();
      for(int i=0; i<n; i++)
        {
          double tmp=0;
          for (int j=0; j<dimension; j++)
            tmp+=coord(i,j)*coord(i,j);
          if (inf_strict(tmp,distance) && !est_egal(A00RR(i,i),0.))
            {
              distance=tmp;
              element_referent=i;
            }
        }
// Cerr << "On modifie la ligne (element) " << element_referent << finl;
      A00RR(element_referent,element_referent)*=2;
      matrice_modifiee=1;
    }
// has_P_ref=1;
  A00RR.set_est_definie(1);
  return matrice_modifiee;
}
References Objet_U::dimension, DMAXFLOAT, est_egal(), Matrice_Bloc::get_bloc(), Matrice_Sym::get_est_definie(), inf_strict(), Process::je_suis_maitre(), la_zone_VEF, Zone_dis_base::nb_elem(), ref_cast, Matrice_Sym::set_est_definie(), Deriv_Matrice_Base::valeur(), Ref_Zone_VEF::valeur(), and Zone_VF::xp().
Referenced by assembler_mat(), and Assembleur_P_VEFPreP1B::modifier_matrice().
modifier_secmem()
int Assembleur_P_VEF::modifier_secmem (DoubleTab & secmem) override virtual
Implements Assembleur_base.
Definition at line 593 of file Assembleur_P_VEF.cpp.
{
  const Zone_VEF& la_zone = la_zone_VEF.valeur();
  const Zone_Cl_VEF& la_zone_cl = la_zone_Cl_VEF.valeur();
  int nb_cond_lim = la_zone_cl.nb_cond_lim();
  const IntTab& face_voisins = la_zone.face_voisins();
// Modification du second membre :
  for (int i=0; i<nb_cond_lim; i++)
    {
      const Cond_lim_base& la_cl_base = la_zone_cl.les_conditions_limites(i).valeur();
      const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl_base.frontiere_dis());
      int ndeb = la_front_dis.num_premiere_face();
      int nfin = ndeb + la_front_dis.nb_faces();
// GF on est passe en increment de pression
      if ((sub_type(Neumann_sortie_libre,la_cl_base)) && (!get_resoudre_increment_pression()))
        {
          double Pimp, coef;
          const Neumann_sortie_libre& la_cl_Neumann = ref_cast(Neumann_sortie_libre, la_cl_base);
// const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl_base.frontiere_dis());
// int ndeb = la_front_dis.num_premiere_face();
// int nfin = ndeb + la_front_dis.nb_faces();
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
              Pimp = la_cl_Neumann.flux_impose(num_face-ndeb);
              coef = les_coeff_pression[num_face]*Pimp;
              secmem[face_voisins(num_face,0)] += coef;
            }
        }
      else if (sub_type(Champ_front_instationnaire_base,
                        la_cl_base.champ_front().valeur())&&(get_resoudre_en_u()))
        {
// Cas Dirichlet variable dans le temps
// N'est utile que pour des champs front. variables dans le temps
          const Champ_front_instationnaire_base& le_ch_front =
            ref_cast( Champ_front_instationnaire_base,
                      la_cl_base.champ_front().valeur());
          const DoubleTab& Gpt = le_ch_front.Gpoint();
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
// for num_face
              double Stt = 0.;
              for (int k=0; k<dimension; k++)
                Stt -= Gpt(k) * la_zone.face_normales(num_face, k);
              secmem(face_voisins(num_face,0)) += Stt;
            }
        }
      else if (sub_type(Champ_front_var_instationnaire,
                        la_cl_base.champ_front().valeur())&&(get_resoudre_en_u()))
        {
// cas instationaire et variable
          const Champ_front_var_instationnaire& le_ch_front =
            ref_cast( Champ_front_var_instationnaire, la_cl_base.champ_front().valeur());
          const DoubleTab& Gpt = le_ch_front.Gpoint();
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
              double Stt = 0.;
              for (int k=0; k<dimension; k++)
                Stt -= Gpt(num_face - ndeb, k) *
                       la_zone.face_normales(num_face, k);
              secmem(face_voisins(num_face,0)) += Stt;
            }
        }
    }
  secmem.echange_espace_virtuel();
  return 1;
}
References Cond_lim_base::champ_front(), Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Neumann::flux_impose(), Cond_lim_base::frontiere_dis(), Assembleur_base::get_resoudre_en_u(), Assembleur_base::get_resoudre_increment_pression(), Champ_front_instationnaire_base::Gpoint(), Champ_front_var_instationnaire::Gpoint(), la_zone_Cl_VEF, la_zone_VEF, les_coeff_pression, Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, sub_type, Deriv_Champ_front_base::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
modifier_solution()
int Assembleur_P_VEF::modifier_solution (DoubleTab & pression) override virtual
Implements Assembleur_base.
Definition at line 665 of file Assembleur_P_VEF.cpp.
{
// Projection :
  double press_0;
  if(!has_P_ref)
    {
// On prend la pression minimale comme pression de reference
// afin d'avoir la meme pression de reference en sequentiel et parallele
      press_0=DMAXFLOAT;
      int n,nb_elem=la_zone_VEF.valeur().zone().nb_elem();
      for(n=0; n<nb_elem; n++)
        if (pression[n] < press_0)
          press_0 = pression[n];
      press_0 = Process::mp_min(press_0);
      for(n=0; n<nb_elem; n++)
        pression[n] -=press_0;
      pression.echange_espace_virtuel();
    }
  return 1;
}
References DMAXFLOAT, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), has_P_ref, la_zone_VEF, Process::mp_min(), Zone::nb_elem(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by Assembleur_P_VEFPreP1B::modifier_solution().
printOn()
Sortie & Assembleur_P_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 29 of file Assembleur_P_VEF.cpp.
{
  return s << que_suis_je() << " " << le_nom() ;
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Assembleur_P_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 34 of file Assembleur_P_VEF.cpp.
{
  return Assembleur_base::readOn(s);
}
References Assembleur_base::readOn().
remplir() [1/2]
int Assembleur_P_VEF::remplir (Matrice & la_matrice, const DoubleTab & inverse_quantitee_entrelacee)
< En fait Matrice_Bloc_Sym ?
< En fait Matrice_Morse_Sym ?
< Diagonale
< Pas de diagonale
< Diagonale
< elem2 >= elem1
< elem2 >= elem1
< Diagonale
< Diagonale
Definition at line 125 of file Assembleur_P_VEF.cpp.
{
  has_P_ref=0;
// Matrice de pression :matrice creuse de taille nb_poly x nb_poly
// Cette fonction range la matrice dans une structure de matrice morse
// bien adaptee aux matrices creuses.
// On commence par calculer les tailles des tableaux tab1 et tab2
// (coeff_ a la meme taille que tab2)
// A chaque polyedre on associe :
// - une liste d'entiers voisins[i] = {j>i t.q Mij est non nul }
// - une liste de reels  valeurs[i] = {Mij pour j dans Voisins[i]}
// - un reel terme_diag
// Implementation temporaire:
// On assemble une matrice de pression pour une equation d'hydraulique
// On injecte dans cette matrice les conditions aux limites
// On peut faire cela car a priori la matrice de pression n'est pas
// partagee par plusieurs equations sur une meme zone.
  const Zone_VEF& la_zone = la_zone_VEF.valeur();
  const Zone_Cl_VEF& la_zone_cl = la_zone_Cl_VEF.valeur();
  les_coeff_pression.resize(la_zone_cl.nb_faces_Cl());
  int n1 = la_zone.zone().nb_elem_tot();
  int n2 = la_zone.zone().nb_elem();
  int elem1,elem2;
  double val;
  int i;
  const IntTab& face_voisins = la_zone.face_voisins();
  const DoubleTab& face_normales = la_zone.face_normales();
  const Conds_lim& les_cl = la_zone_cl.les_conditions_limites();
// int premiere_face_std=la_zone.premiere_face_std();
// Rajout des porosites.
// const DoubleVect& porosite_face = la_zone.porosite_face();
  la_matrice.typer("Matrice_Bloc"); //!< En fait Matrice_Bloc_Sym ?
  Matrice_Bloc& matrice=ref_cast(Matrice_Bloc, la_matrice.valeur());
  matrice.dimensionner(2,2);
  matrice.get_bloc(0,0).typer("Matrice_Morse_Sym");
  matrice.get_bloc(0,1).typer("Matrice_Morse");
  matrice.get_bloc(1,0).typer("Matrice_Morse");
  matrice.get_bloc(1,1).typer("Matrice_Morse"); //!< En fait Matrice_Morse_Sym ?
  Matrice_Morse_Sym& MBrr = ref_cast(Matrice_Morse_Sym,matrice.get_bloc(0,0).valeur());
  Matrice_Morse& MBrv = ref_cast (Matrice_Morse,matrice.get_bloc(0,1).valeur());
  Matrice_Morse& MBvr = ref_cast (Matrice_Morse, matrice.get_bloc(1,0).valeur());
  Matrice_Morse& MBvv = ref_cast (Matrice_Morse, matrice.get_bloc(1,1).valeur());
  MBrr.dimensionner(n2,0);
  MBrv.dimensionner(n2,0);
  MBvv.dimensionner(n1-n2,0);
// Le sous blocs vr est dimensionne et nul
  MBvr.dimensionner(n1-n2,n2,0);
  MBvr.get_set_tab1() = 1;
  IntVect& tab1RR=MBrr.get_set_tab1();
  IntVect& tab2RR=MBrr.get_set_tab2();
  DoubleVect& coeffRR=MBrr.get_set_coeff();
  IntVect& tab1RV=MBrv.get_set_tab1();
  IntVect& tab2RV=MBrv.get_set_tab2();
  DoubleVect& coeffRV=MBrv.get_set_coeff();
  IntVect& tab1VV=MBvv.get_set_tab1();
  IntVect& tab2VV=MBvv.get_set_tab2();
  DoubleVect& coeffVV=MBvv.get_set_coeff();
// On traite les faces internes:
  int ndeb = la_zone_VEF->premiere_face_int();
  int nfin = la_zone_VEF->nb_faces_tot();
  IntVect rang_voisinRR(n2);
  IntVect rang_voisinRV(n2);
  IntVect rang_voisinVV(n1-n2);
  rang_voisinRR=1; //!< Diagonale
  rang_voisinRV=0; //!< Pas de diagonale
  rang_voisinVV=1; //!< Diagonale
  has_P_ref=0;
  for (int num_face=ndeb; num_face<nfin; num_face++)
    {
      elem1 = face_voisins(num_face,0);
      elem2 = face_voisins(num_face,1);
      if (!la_zone_VEF->est_une_face_virt_bord(num_face) && elem1 != -1 && elem2 != -1)
        {
          if (elem1 > elem2)
            {
              if(elem1<n2)
                {
                  (rang_voisinRR(elem2))++;
                }
              else
                {
                  if(elem2<n2)
                    {
                      (rang_voisinRV(elem2))++;
                    }
                  else
                    {
                      (rang_voisinVV(elem2-n2))++;
                    }
                }
            }
          else //!< elem2 >= elem1
            {
              if(elem2<n2)
                {
                  (rang_voisinRR(elem1))++;
                }
              else
                {
                  if(elem1<n2)
                    {
                      (rang_voisinRV(elem1))++;
                    }
                  else
                    {
                      (rang_voisinVV(elem1-n2))++;
                    }
                }
            }
        }
    }
// Prise en compte des conditions de type periodicite
  for (i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int nb_faces_bord_tot = le_bord.nb_faces_tot();
          IntVect fait(nb_faces_bord_tot);
          fait = 0;
          for(int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
            {
              int num_face = le_bord.num_face(ind_face);
              if (fait[ind_face] == 0)
                {
                  fait[ind_face] = 1;
                  fait[la_cl_perio.face_associee(ind_face)] = 1;
                  elem1 = face_voisins(num_face,0);
                  elem2 = face_voisins(num_face,1);
                  if (elem1 !=-1 && elem2 != -1)
                    {
                      if (elem1 > elem2)
{
                          if(elem1<n2)
{
                              (rang_voisinRR(elem2))++;
                            }
                          else
{
                              if(elem2<n2)
{
                                  (rang_voisinRV(elem2))++;
                                }
                              else
{
                                  (rang_voisinVV(elem2-n2))++;
                                }
                            }
                        }
                      else //!< elem2 >= elem1
{
                          if(elem2<n2)
{
                              (rang_voisinRR(elem1))++;
                            }
                          else
{
                              if(elem1<n2)
{
                                  (rang_voisinRV(elem1))++;
                                }
                              else
{
                                  (rang_voisinVV(elem1-n2))++;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
  tab1RR(0)=1;
  tab1RV(0)=1;
  tab1VV(0)=1;
  for(i=0; i<n2; i++)
    {
      tab1RR(i+1)=rang_voisinRR(i)+tab1RR(i);
      tab1RV(i+1)=rang_voisinRV(i)+tab1RV(i);
    }
  for(i=0; i<n1-n2; i++)
    {
      tab1VV(i+1)=rang_voisinVV(i)+tab1VV(i);
    }
  MBrr.dimensionner(n2,tab1RR(n2)-1);
  MBrv.dimensionner(n2,n1-n2,tab1RV(n2)-1);
  MBvv.dimensionner(n1-n2,n1-n2,tab1VV(n1-n2)-1);
  for(i=0; i<n2; i++)
    {
      tab2RR[tab1RR[i]-1]=i+1; //!< Diagonale
      rang_voisinRR[i]=tab1RR[i];
      rang_voisinRV[i]=tab1RV[i]-1;
    }
  for(i=0; i<n1-n2; i++)
    {
      tab2VV[tab1VV[i]-1]=i+1; //!< Diagonale
      rang_voisinVV[i]=tab1VV[i];
    }
  int affichage_progression=0;
  int pourcent=0;
  for (int num_face=ndeb; num_face<nfin; num_face++)
    {
      if (affichage_progression)
        {
          int tmp =(num_face*100)/nfin;
          if(tmp>pourcent)
            {
              double dpourcent = tmp;
              Cerr << dpourcent << "% de la matrice de pression P0 a ete assemblee\r " << flush;
            }
        }
      elem1 = face_voisins(num_face,0);
      elem2 = face_voisins(num_face,1);
// On ne traite que les faces internes virtuelles ou non
      if (!la_zone_VEF->est_une_face_virt_bord(num_face) && elem1 != -1 && elem2 != -1)
        {
          if(dimension==2)
            {
              val = (face_normales(num_face,0)*face_normales(num_face,0)*inverse_quantitee_entrelacee(num_face,0)
                     + face_normales(num_face,1)*face_normales(num_face,1)*inverse_quantitee_entrelacee(num_face,1));
            }
          else
            {
              val = (face_normales(num_face,0)*face_normales(num_face,0)*inverse_quantitee_entrelacee(num_face,0)
                     +face_normales(num_face,1)*face_normales(num_face,1)*inverse_quantitee_entrelacee(num_face,1)
                     +face_normales(num_face,2)*face_normales(num_face,2)*inverse_quantitee_entrelacee(num_face,2));
            }
// if(num_face<premiere_face_std)
// val*=volumes_entrelaces(num_face)/volumes_entrelaces_Cl(num_face);
// diagonale :
          if(elem1<n2) coeffRR[tab1RR[elem1]-1]+= val;
          else coeffVV[tab1VV[elem1-n2]-1]+= val;
          if(elem2<n2) coeffRR[tab1RR[elem2]-1]+= val;
          else coeffVV[tab1VV[elem2-n2]-1]+= val;
          if (elem1 > elem2)
            {
              if(elem1<n2)
                {
                  tab2RR[rang_voisinRR[elem2]]=elem1+1;
                  coeffRR[rang_voisinRR[elem2]]-=val;
                  rang_voisinRR[elem2]++;
                }
              else
                {
                  if(elem2<n2)
                    {
                      tab2RV[rang_voisinRV[elem2]]=(elem1-n2)+1;
                      coeffRV[rang_voisinRV[elem2]]-=val;
                      rang_voisinRV[elem2]++;
                    }
                  else
                    {
                      tab2VV[rang_voisinVV[elem2-n2]]=(elem1-n2)+1;
                      coeffVV[rang_voisinVV[elem2-n2]]-=val;
                      rang_voisinVV[elem2-n2]++;
                    }
                }
            }
          else
            {
              if(elem2<n2)
                {
                  tab2RR[rang_voisinRR[elem1]]=elem2+1;
                  coeffRR[rang_voisinRR[elem1]]-=val;
                  rang_voisinRR[elem1]++;
                }
              else
                {
                  if(elem1<n2)
                    {
                      tab2RV[rang_voisinRV[elem1]]=(elem2-n2)+1;
                      coeffRV[rang_voisinRV[elem1]]-=val;
                      rang_voisinRV[elem1]++;
                    }
                  else
                    {
                      tab2VV[rang_voisinVV[elem1-n2]]=(elem2-n2)+1;
                      coeffVV[rang_voisinVV[elem1-n2]]-=val;
                      rang_voisinVV[elem1-n2]++;
                    }
                }
            }
        }
    }
  if (affichage_progression) Cerr << finl;
// On traite les conditions aux limites
  for (i=0; i<les_cl.size(); i++)
    {
// Le traitement depend du type de la condition aux limites :
// - Si condition de Neumann_sortie_libre
// il faut calculer le coefficient sur la face et le prendre
// en compte dans le terme diagonal associe a l'element voisin.
// - Si face de Cl avec une autre condition aux limites pas de
// contribution a la matrice de pression.
      const Cond_lim& la_cl = les_cl[i];
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_bord_tot = le_bord.nb_faces_tot();
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()) )
        {
          has_P_ref=1;
          MBrr.set_est_definie(1);
          for(int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
            {
              int num_face = le_bord.num_face(ind_face);
              if(dimension==2)
                {
                  val = ( face_normales(num_face,0)*face_normales(num_face,0)*inverse_quantitee_entrelacee(num_face,0)
                          +face_normales(num_face,1)*face_normales(num_face,1)*inverse_quantitee_entrelacee(num_face,1));
                }
              else
                {
                  val = ( face_normales(num_face,0)*face_normales(num_face,0)*inverse_quantitee_entrelacee(num_face,0)
                          +face_normales(num_face,1)*face_normales(num_face,1)*inverse_quantitee_entrelacee(num_face,1)
                          +face_normales(num_face,2)*face_normales(num_face,2)*inverse_quantitee_entrelacee(num_face,2));
                }
// if(num_face<premiere_face_std)
// val*=volumes_entrelaces(num_face)/volumes_entrelaces_Cl(num_face);
              int elem=face_voisins(num_face,0);
              if(elem<n2)
                coeffRR[tab1RR[elem]-1] += val;
              else
                coeffVV[tab1VV[elem-n2]-1] += val;
// On stocke les coefficients de pression sur les faces reelles
              if (num_face<les_coeff_pression.size_array())
                les_coeff_pression[num_face] = val;
            }
        }
      else if (sub_type(Periodique,la_cl.valeur()) )
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          IntVect fait(nb_faces_bord_tot);
          fait = 0;
          for(int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
            {
              int num_face = le_bord.num_face(ind_face);
              if (fait[ind_face] == 0)
                {
                  fait[ind_face] = 1;
                  fait[la_cl_perio.face_associee(ind_face)] = 1;
                  elem1 = face_voisins(num_face,0);
                  elem2 = face_voisins(num_face,1);
                  if(dimension==2)
                    {
                      val = (face_normales(num_face,0)*face_normales(num_face,0)*inverse_quantitee_entrelacee(num_face,0)
                             +face_normales(num_face,1)*face_normales(num_face,1)*inverse_quantitee_entrelacee(num_face,1));
                    }
                  else
                    {
                      val = (face_normales(num_face,0)*face_normales(num_face,0)*inverse_quantitee_entrelacee(num_face,0)
                             +face_normales(num_face,1)*face_normales(num_face,1)*inverse_quantitee_entrelacee(num_face,1)
                             +face_normales(num_face,2)*face_normales(num_face,2)*inverse_quantitee_entrelacee(num_face,2));
                    }
// if(num_face<premiere_face_std)
// val*=volumes_entrelaces(num_face)/volumes_entrelaces_Cl(num_face);
// diagonale :
                  if(elem1<n2)
                    coeffRR[tab1RR[elem1]-1]+= val;
                  else
                    coeffVV[tab1VV[elem1-n2]-1]+= val;
                  if(elem2<n2)
                    coeffRR[tab1RR[elem2]-1]+= val;
                  else
                    coeffVV[tab1VV[elem2-n2]-1]+= val;
                  if (elem1 > elem2)
                    {
                      if(elem1<n2)
{
                          tab2RR[rang_voisinRR[elem2]]=elem1+1;
                          coeffRR[rang_voisinRR[elem2]]-=val;
                          rang_voisinRR[elem2]++;
                        }
                      else
{
                          if(elem2<n2)
{
                              tab2RV[rang_voisinRV[elem2]]=elem1-n2+1;
                              coeffRV[rang_voisinRV[elem2]]-=val;
                              rang_voisinRV[elem2]++;
                            }
                          else
{
                              tab2VV[rang_voisinVV[elem2-n2]]=elem1-n2+1;
                              coeffVV[rang_voisinVV[elem2-n2]]-=val;
                              rang_voisinVV[elem2-n2]++;
                            }
                        }
                    }
                  else
                    {
                      if(elem2<n2)
{
                          tab2RR[rang_voisinRR[elem1]]=elem2+1;
                          coeffRR[rang_voisinRR[elem1]]-=val;
                          rang_voisinRR[elem1]++;
                        }
                      else
{
                          if(elem1<n2)
{
                              tab2RV[rang_voisinRV[elem1]]=elem2-n2+1;
                              coeffRV[rang_voisinRV[elem1]]-=val;
                              rang_voisinRV[elem1]++;
                            }
                          else
{
                              tab2VV[rang_voisinVV[elem1-n2]]=elem2-n2+1;
                              coeffVV[rang_voisinVV[elem1-n2]]-=val;
                              rang_voisinVV[elem1-n2]++;
                            }
                        }
                    }
                }
            }
        }
    }
  has_P_ref = (int)mp_max(has_P_ref);
  return 1;
}
References Cerr, Objet_U::dimension, Matrice_Bloc::dimensionner(), Matrice_Morse::dimensionner(), Zone_VF::est_une_face_virt_bord(), Periodique::face_associee(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Matrice_Bloc::get_bloc(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), has_P_ref, la_zone_Cl_VEF, la_zone_VEF, les_coeff_pression, Zone_Cl_dis_base::les_conditions_limites(), Process::mp_max(), Zone::nb_elem(), Zone::nb_elem_tot(), Zone_Cl_dis_base::nb_faces_Cl(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Front_VF::num_face(), Zone_VF::premiere_face_int(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Matrice_Sym::set_est_definie(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), sub_type, Deriv_::typer(), Deriv_Cond_lim_base::valeur(), Deriv_Matrice_Base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by assembler_mat(), assemblerP0P0(), and updateP0P0().
remplir() [2/2]
int Assembleur_P_VEF::remplir (Matrice & , const DoubleVect &) inline
Definition at line 43 of file Assembleur_P_VEF.h.
  {
    assert(0);
    exit();
    return 1;
  };
References Process::exit().
self_cast() [1/2]
const Assembleur_P_VEF & Assembleur_P_VEF::self_cast (const Objet_U & r) static
Definition at line 27 of file Assembleur_P_VEF.cpp.
self_cast() [2/2]
Assembleur_P_VEF & Assembleur_P_VEF::self_cast (Objet_U & r) static
Definition at line 27 of file Assembleur_P_VEF.cpp.
taille_memoire()
unsigned Assembleur_P_VEF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 27 of file Assembleur_P_VEF.cpp.
zone_Cl_dis_base()
const Zone_Cl_dis_base & Assembleur_P_VEF::zone_Cl_dis_base () const override virtual
Implements Assembleur_base.
Definition at line 736 of file Assembleur_P_VEF.cpp.
{
  return la_zone_Cl_VEF.valeur();
}
References la_zone_Cl_VEF, and Ref_Zone_Cl_VEF::valeur().
zone_dis_base()
const Zone_dis_base & Assembleur_P_VEF::zone_dis_base () const override virtual
Implements Assembleur_base.
Definition at line 731 of file Assembleur_P_VEF.cpp.
{
  return la_zone_VEF.valeur();
}
References la_zone_VEF, and Ref_Zone_VEF::valeur().
Member Data Documentation
has_P_ref
int Assembleur_P_VEF::has_P_ref protected
Definition at line 61 of file Assembleur_P_VEF.h.
Referenced by Assembleur_P_VEFPreP1B::modifier_matrice(), modifier_solution(), and remplir().
info_obj
const Type_info Assembleur_P_VEF::info_obj static
Definition at line 33 of file Assembleur_P_VEF.h.
la_zone_Cl_VEF
Ref_Zone_Cl_VEF Assembleur_P_VEF::la_zone_Cl_VEF protected
Definition at line 59 of file Assembleur_P_VEF.h.
Referenced by assembler(), Assembleur_P_VEFPreP1B::assembler_mat(), assembler_mat(), associer_zone_cl_dis_base(), Assembleur_P_VEFPreP1B::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_secmem(), modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), remplir(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), and zone_Cl_dis_base().
la_zone_VEF
Ref_Zone_VEF Assembleur_P_VEF::la_zone_VEF protected
Definition at line 58 of file Assembleur_P_VEF.h.
Referenced by assembler(), associer_zone_dis_base(), calculer_inv_volume(), modifier_matrice(), modifier_secmem(), modifier_solution(), remplir(), zone_dis_base(), and Assembleur_P_VEFPreP1B::zone_Vef().
les_coeff_pression
DoubleTab Assembleur_P_VEF::les_coeff_pression protected
Definition at line 60 of file Assembleur_P_VEF.h.
Referenced by modifier_secmem(), and remplir().
mon_equation
Ref_Equation_base Assembleur_P_VEF::mon_equation protected
Definition at line 57 of file Assembleur_P_VEF.h.
Referenced by completer(), and equation().
The documentation for this class was generated from the following files:
src/VEF/Solveurs/Assembleur_P_VEF.h
src/VEF/Solveurs/Assembleur_P_VEF.cpp