TRUST: Schema_Temps Class Reference
Schema_Temps Class Reference
classe Schema_Temps
Classe generique de la hierarchie des schemas en temps, un objet
Schema_Temps peut referencer n'importe quel objet derivant de
Schema_Temps_base.
La plupart des methodes appellent les methodes de l'objet
Schema_Temps_base sous-jacent via la methode valeur() declaree grace
alamacroDeclare_deriv().;
#include <Schema_Temps.h>
Public Member Functions
Schema_Temps ()
~Schema_Temps ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int sauvegarder (Sortie &) const override
Appel a l'objet sous-jacent.
Sauvegarde le schema en temps sur un flot de sortie.
int reprendre (Entree &) override
Appel a l'objet sous-jacent.
Effectue une reprise (lecture) du schema en temps a partir
d'un flot d'entree.
int faire_un_pas_de_temps_eqn_base (Equation_base &)
Appel a l'objet sous-jacent.
Effectue un pas de temps sur une equation.
bool iterateTimeStep (bool &converged)
Appel a l'objet sous-jacent.
Effectue un pas de temps sur le probleme.
int mettre_a_jour ()
Appel a l'objet sous-jacent
Mise a jour du temps et du nombre de pas de temps..
void imprimer (Sortie &os) const
Appel a l'objet sous-jacent
Imprime le schema en temp sur un flot de sortie (si il y a lieu).
double pas_de_temps () const
Appel a l'objet sous-jacent
Renvoie le pas en temps courant.
void corriger_dt_calcule (double &) const
Appel a l'objet sous-jacent
Corrige le pas de temps : dtmin <= dt <= dtmax.
bool initTimeStep (double dt)
Appel a l'objet sous-jacent
Pretraitement eventuel.
double pas_temps_min () const
Appel a l'objet sous-jacent
Renvoie le pas de temps minimum.
double & pas_temps_min ()
Appel a l'objet sous-jacent
Renvoie une reference sur le pas de temps minimum.
double pas_temps_max () const
Appel a l'objet sous-jacent
Renvoie le pas de temps maximum.
double & pas_temps_max ()
Appel a l'objet sous-jacent
Renvoie une reference sur le pas de temps maximum.
int nb_pas_dt () const
Appel a l'objet sous-jacent
Renvoie le nombre de pas de temps effectues.
double temps_courant () const
Appel a l'objet sous-jacent
Renvoie le temps courant.
double temps_calcul () const
Appel a l'objet sous-jacent
Renvoie le temps ecoule calcule: (temps courant - temps debut)
void changer_temps_courant (const double)
Appel a l'objet sous-jacent
Change le temps courant.
double facteur_securite_pas () const
Appel a l'objet sous-jacent
Renvoie le facteur de securite ou multiplicateur de pas de temps.
double & facteur_securite_pas ()
Appel a l'objet sous-jacent
Renvoie une reference sur le facteur de securite ou multiplicateur de
pas de temps.
int stop ()
Appel a l'objet sous-jacent
Renvoie 1 si il y lieu de stopper le calcul pour differente raisons:
- le temps final est atteint
- le nombre de pas de temps maximum est depasse
- l'etat stationnaire est atteint
- indicateur d'arret fichier
Renvoie 0 sinon.
int impr (Sortie &) const
Appel a l'objet sous-jacent
Renvoie 1 s'il y a lieu de faire une impression.
int lsauv () const
Schema_Temps & operator= (const Schema_Temps_base &)
Operateur d'affectation d'un Schema_Temp_base dans un
Schema_temps.
Public Member Functions inherited from Deriv_Schema_Temps_base
~Deriv_Schema_Temps_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Schema_Temps_base ()
Deriv_Schema_Temps_base (const Deriv_Schema_Temps_base &)
const Schema_Temps_base & valeur () const
Schema_Temps_base & valeur ()
const Schema_Temps_base * operator-> () const
Schema_Temps_base * operator-> ()
const Deriv_Schema_Temps_base & operator= (const Schema_Temps_base &)
const Deriv_Schema_Temps_base & operator= (const Deriv_Schema_Temps_base &)
operator const Schema_Temps_base & () const
operator Schema_Temps_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Schema_Temps & self_cast (Objet_U &)
static const Schema_Temps & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Schema_Temps_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Schema_Temps_base & self_cast (Objet_U &)
static const Deriv_Schema_Temps_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Schema_Temps_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Impression du schema en temps sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du schema en temps sur un flot d'entree.
Protected Member Functions inherited from Deriv_Schema_Temps_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
classe Schema_Temps
Classe generique de la hierarchie des schemas en temps, un objet
Schema_Temps peut referencer n'importe quel objet derivant de
Schema_Temps_base.
La plupart des methodes appellent les methodes de l'objet
Schema_Temps_base sous-jacent via la methode valeur() declaree grace
alamacroDeclare_deriv().;
Definition at line 37 of file Schema_Temps.h.
Constructor & Destructor Documentation
Schema_Temps()
Schema_Temps::Schema_Temps ()
Definition at line 19 of file Schema_Temps.cpp.
~Schema_Temps()
Schema_Temps::~Schema_Temps ()
Definition at line 19 of file Schema_Temps.cpp.
Member Function Documentation
changer_temps_courant()
void Schema_Temps::changer_temps_courant (const double t) inline
Appel a l'objet sous-jacent
Change le temps courant.
Definition at line 403 of file Schema_Temps.h.
{
  valeur().changer_temps_courant(t);
}
References Schema_Temps_base::changer_temps_courant(), and Deriv_Schema_Temps_base::valeur().
corriger_dt_calcule()
void Schema_Temps::corriger_dt_calcule (double & dt) const inline
Appel a l'objet sous-jacent
Corrige le pas de temps : dtmin <= dt <= dtmax.
Definition at line 232 of file Schema_Temps.h.
{
  valeur().corriger_dt_calcule(dt);
}
References Schema_Temps_base::corriger_dt_calcule(), and Deriv_Schema_Temps_base::valeur().
cree_instance()
Objet_U * Schema_Temps::cree_instance () static
Definition at line 19 of file Schema_Temps.cpp.
duplique()
int Schema_Temps::duplique () const override virtual
Reimplemented from Deriv_Schema_Temps_base.
Definition at line 19 of file Schema_Temps.cpp.
facteur_securite_pas() [1/2]
double & Schema_Temps::facteur_securite_pas () inline
Appel a l'objet sous-jacent
Renvoie une reference sur le facteur de securite ou multiplicateur de
pas de temps.
Returns
double&
Signification: le facteur de securite du schema en temps
Contraintes:
Definition at line 442 of file Schema_Temps.h.
{
  return valeur().facteur_securite_pas();
}
References Schema_Temps_base::facteur_securite_pas(), and Deriv_Schema_Temps_base::valeur().
facteur_securite_pas() [2/2]
double Schema_Temps::facteur_securite_pas () const inline
Appel a l'objet sous-jacent
Renvoie le facteur de securite ou multiplicateur de pas de temps.
Returns
double
Signification: le facteur de securite du schema en temps
Contraintes:
Definition at line 422 of file Schema_Temps.h.
{
  return valeur().facteur_securite_pas();
}
References Schema_Temps_base::facteur_securite_pas(), and Deriv_Schema_Temps_base::valeur().
Referenced by Multi_Sch_ThHyd::faire_un_pas_de_temps_eqn_base().
faire_un_pas_de_temps_eqn_base()
int Schema_Temps::faire_un_pas_de_temps_eqn_base (Equation_base & eqn) inline
Appel a l'objet sous-jacent.
Effectue un pas de temps sur une equation.
Returns
int
Signification: code de retour sous-jacent
Contraintes:
Definition at line 154 of file Schema_Temps.h.
{
  return valeur().faire_un_pas_de_temps_eqn_base(eqn);
}
References Schema_Temps_base::faire_un_pas_de_temps_eqn_base(), and Deriv_Schema_Temps_base::valeur().
Referenced by Multi_Sch_ThHyd::faire_un_pas_de_temps_eqn_base().
get_info()
const Type_info * Schema_Temps::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Schema_Temps_base.
Definition at line 19 of file Schema_Temps.cpp.
impr()
int Schema_Temps::impr (Sortie & os) const inline
Appel a l'objet sous-jacent
Renvoie 1 s'il y a lieu de faire une impression.
Returns
int
Signification: code de retour sous-jacent
Contraintes:
Definition at line 485 of file Schema_Temps.h.
{
  return valeur().impr(os);
}
References Schema_Temps_base::impr(), and Deriv_Schema_Temps_base::valeur().
imprimer()
void Schema_Temps::imprimer (Sortie & os) const inline
Appel a l'objet sous-jacent
Imprime le schema en temp sur un flot de sortie (si il y a lieu).
Definition at line 504 of file Schema_Temps.h.
{
  valeur().imprimer(os);
}
References Schema_Temps_base::imprimer(), and Deriv_Schema_Temps_base::valeur().
info()
const Type_info * Schema_Temps::info () static
Definition at line 19 of file Schema_Temps.cpp.
initTimeStep()
bool Schema_Temps::initTimeStep (double dt) inline
Appel a l'objet sous-jacent
Pretraitement eventuel.
Definition at line 251 of file Schema_Temps.h.
{
  return valeur().initTimeStep(dt);
}
References Schema_Temps_base::initTimeStep(), and Deriv_Schema_Temps_base::valeur().
iterateTimeStep()
bool Schema_Temps::iterateTimeStep (bool & converged) inline
Appel a l'objet sous-jacent.
Effectue un pas de temps sur le probleme.
Returns
int
Signification: code de retour sous-jacent
Contraintes:
Definition at line 174 of file Schema_Temps.h.
{
  return valeur().iterateTimeStep(converged);
}
References Schema_Temps_base::iterateTimeStep(), and Deriv_Schema_Temps_base::valeur().
lsauv()
int Schema_Temps::lsauv () const inline
Returns
int
Signification: 1 si il faut faire une sauvegarde 0 sinon
Contraintes:
Definition at line 524 of file Schema_Temps.h.
{
  return valeur().lsauv();
}
References Schema_Temps_base::lsauv(), and Deriv_Schema_Temps_base::valeur().
mettre_a_jour()
int Schema_Temps::mettre_a_jour () inline
Appel a l'objet sous-jacent
Mise a jour du temps et du nombre de pas de temps..
Returns
int
Signification: code de retour sous-jacent
Contraintes:
Definition at line 194 of file Schema_Temps.h.
{
  return valeur().mettre_a_jour();
}
References Schema_Temps_base::mettre_a_jour(), and Deriv_Schema_Temps_base::valeur().
Referenced by Multi_Sch_ThHyd::mettre_a_jour().
nb_pas_dt()
int Schema_Temps::nb_pas_dt () const inline
Appel a l'objet sous-jacent
Renvoie le nombre de pas de temps effectues.
Returns
int
Signification: le nombre de pas de temps effectues
Contraintes:
Definition at line 346 of file Schema_Temps.h.
{
  return valeur().nb_pas_dt();
}
References Schema_Temps_base::nb_pas_dt(), and Deriv_Schema_Temps_base::valeur().
operator=()
Schema_Temps & Schema_Temps::operator= (const Schema_Temps_base & sch) inline
Operateur d'affectation d'un Schema_Temp_base dans un
Schema_temps.
Returns
Schema_Temps&
Signification: renvoie une reference sur *this: le schema nouvellement
affecte.
Contraintes:
Definition at line 87 of file Schema_Temps.h.
{
  DERIV(Schema_Temps_base)::operator=(sch);
  return *this;
}
References DERIV, and operator=().
Referenced by operator=().
pas_de_temps()
double Schema_Temps::pas_de_temps () const inline
Appel a l'objet sous-jacent
Renvoie le pas en temps courant.
Returns
double
Signification: le pas de temps courant.
Contraintes:
Definition at line 213 of file Schema_Temps.h.
{
  return valeur().pas_de_temps();
}
References Schema_Temps_base::pas_de_temps(), and Deriv_Schema_Temps_base::valeur().
pas_temps_max() [1/2]
double & Schema_Temps::pas_temps_max () inline
Appel a l'objet sous-jacent
Renvoie une reference sur le pas de temps maximum.
Returns
double&
Signification: le pas de temps maximum
Contraintes:
Definition at line 327 of file Schema_Temps.h.
{
  return valeur().pas_temps_max();
}
References Schema_Temps_base::pas_temps_max(), and Deriv_Schema_Temps_base::valeur().
pas_temps_max() [2/2]
double Schema_Temps::pas_temps_max () const inline
Appel a l'objet sous-jacent
Renvoie le pas de temps maximum.
Returns
double
Signification: le pas de temps maximum
Contraintes:
Definition at line 308 of file Schema_Temps.h.
{
  return valeur().pas_temps_max();
}
References Schema_Temps_base::pas_temps_max(), and Deriv_Schema_Temps_base::valeur().
pas_temps_min() [1/2]
double & Schema_Temps::pas_temps_min () inline
Appel a l'objet sous-jacent
Renvoie une reference sur le pas de temps minimum.
Returns
double&
Signification: le pas de temps minimum
Contraintes:
Definition at line 289 of file Schema_Temps.h.
{
  return valeur().pas_temps_min();
}
References Schema_Temps_base::pas_temps_min(), and Deriv_Schema_Temps_base::valeur().
pas_temps_min() [2/2]
double Schema_Temps::pas_temps_min () const inline
Appel a l'objet sous-jacent
Renvoie le pas de temps minimum.
Returns
double
Signification: le pas de temps minimum
Contraintes:
Definition at line 270 of file Schema_Temps.h.
{
  return valeur().pas_temps_min();
}
References Schema_Temps_base::pas_temps_min(), and Deriv_Schema_Temps_base::valeur().
printOn()
Sortie & Schema_Temps::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Impression du schema en temps sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Schema_Temps_base.
Definition at line 37 of file Schema_Temps.cpp.
{
  return DERIV(Schema_Temps_base)::printOn(os);
}
References DERIV, and printOn().
Referenced by printOn().
readOn()
Entree & Schema_Temps::readOn (Entree & is) override protected virtual
Lecture du schema en temps sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Schema_Temps_base.
Definition at line 57 of file Schema_Temps.cpp.
{
  return DERIV(Schema_Temps_base)::readOn(is);
}
References DERIV, and readOn().
Referenced by readOn().
reprendre()
int Schema_Temps::reprendre (Entree & is) inline override virtual
Appel a l'objet sous-jacent.
Effectue une reprise (lecture) du schema en temps a partir
d'un flot d'entree.
Returns
int
Signification: code de retour sous-jacent
Contraintes:
Reimplemented from Objet_U.
Definition at line 134 of file Schema_Temps.h.
{
  return valeur().reprendre(is);
}
References Schema_Temps_base::reprendre(), and Deriv_Schema_Temps_base::valeur().
sauvegarder()
int Schema_Temps::sauvegarder (Sortie & os) const inline override virtual
Appel a l'objet sous-jacent.
Sauvegarde le schema en temps sur un flot de sortie.
Returns
int
Signification: code de retour sous-jacent
Contraintes:
Reimplemented from Objet_U.
Definition at line 114 of file Schema_Temps.h.
{
  return valeur().sauvegarder(os);
}
References Schema_Temps_base::sauvegarder(), and Deriv_Schema_Temps_base::valeur().
self_cast() [1/2]
const Schema_Temps & Schema_Temps::self_cast (const Objet_U & r) static
Definition at line 19 of file Schema_Temps.cpp.
self_cast() [2/2]
Schema_Temps & Schema_Temps::self_cast (Objet_U & r) static
Definition at line 19 of file Schema_Temps.cpp.
stop()
int Schema_Temps::stop () inline
Appel a l'objet sous-jacent
Renvoie 1 si il y lieu de stopper le calcul pour differente raisons:
- le temps final est atteint
- le nombre de pas de temps maximum est depasse
- l'etat stationnaire est atteint
- indicateur d'arret fichier
Renvoie 0 sinon.
Returns
entier
Signification: 1 si il y a lieu de s'arreter 0 sinon
Contraintes:
Definition at line 466 of file Schema_Temps.h.
{
  return valeur().stop();
}
References Schema_Temps_base::stop(), and Deriv_Schema_Temps_base::valeur().
taille_memoire()
unsigned Schema_Temps::taille_memoire () const override virtual
Reimplemented from Deriv_Schema_Temps_base.
Definition at line 19 of file Schema_Temps.cpp.
temps_calcul()
double Schema_Temps::temps_calcul () const inline
Appel a l'objet sous-jacent
Renvoie le temps ecoule calcule: (temps courant - temps debut)
Returns
double
Signification: le temps ecoule calcule
Contraintes:
Definition at line 384 of file Schema_Temps.h.
{
  return valeur().temps_calcul();
}
References Schema_Temps_base::temps_calcul(), and Deriv_Schema_Temps_base::valeur().
temps_courant()
double Schema_Temps::temps_courant () const inline
Appel a l'objet sous-jacent
Renvoie le temps courant.
Returns
double
Signification: le temps courant
Contraintes:
Definition at line 365 of file Schema_Temps.h.
{
  return valeur().temps_courant();
}
References Schema_Temps_base::temps_courant(), and Deriv_Schema_Temps_base::valeur().
Member Data Documentation
info_obj
const Type_info Schema_Temps::info_obj static
Definition at line 39 of file Schema_Temps.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Schema_Temps.h
src/Kernel/Framework/Schema_Temps.cpp