TRUST: Interprete_bloc Class Reference
Interprete_bloc Class Reference
Interprete un bloc d'instructions dans le jeu de donnees.
Voir Interprete_bloc::interpreter()
#include <Interprete_bloc.h>
Public Types
enum Bloc_Type { ACCOLADE , BLOC_EOF , FIN }
Public Member Functions
Interprete_bloc ()
~Interprete_bloc ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_bloc (Entree &is, Bloc_Type bloc_type, int verifier_sans_interpreter)
Interpretation d'un bloc d'instructions prises dans l'entree is.
Si le bloc commence par {, on suppose que l'accolade a deja ete lue.
Le bloc se termine soit par }, soit par la fin du fichier, soit par
le mot FIN en fonction de bloc_type (voir mon_main.cpp par exemple)
Si verifie_sans_interpreter!=0, on ne cree aucun objet et on ne
lance aucun interprete, on se contente de verifier la coherence des
accolades (meme nombre de { que de }).
Objet_U & ajouter (const Nom &nom, DerObjU &object_to_add)
Ajoute l'objet ob a la liste des objets de l'interprete,
et nomme l'objet avec nom. Si l'objet existe deja, exit()
Objet_U & objet_local (const Nom &nom)
Renvoie l'Objet_U correspondant a nom contenu dans cet interprete_bloc
Si l'objet n'existe pas, exit() (on ne cherche pas dans le pere).
int objet_local_existant (const Nom &nom)
renvoie un drapeau indiquant si un objet de ce nom
est enregistre dans cet inteprete (ne teste pas le pere).
Public Member Functions inherited from liste
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
liste ()
Constructeur par defaut
Construit une liste vide.
liste (const liste &)
Constructeur
Ajoute les elements contenus dans la liste passe en parametre.
liste (const Objet_U &)
Constructeur
Construit une liste singleton.
~liste () override
Destructeur de liste.
int size () const
Renvoie la taille de la liste
Une liste vide est de taille nulle.
int rang (const char *const) const
Renvoie le rang d'une chaine de caracteres contenue dans la liste
Recherche un Objet_U de Nom ch.
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
void suppr (const char *const)
Supprime l'Objet de Nom ch contenu dans la liste.
int est_vide () const
Teste si la liste est vide.
int est_dernier () const
Teste si la liste comporte des elements suivants ou non.
Retourne 1 si la liste est vide.
void vide ()
Vide la liste.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete_bloc & self_cast (Objet_U &)
static const Interprete_bloc & self_cast (const Objet_U &)
static Interprete_bloc & interprete_courant ()
renvoie l'interprete_bloc en train d'etre
lu dans le jeu de donnees. On change d'interprete courant
quand on cree et on detruit un objet de type Interprete_bloc
(par exemple quand on entre ou qu'on sort d'un bloc { })
static Objet_U & objet_global (const Nom &nom)
cherche l'objet demande dans l'Interprete_bloc
courant (Interprete_bloc::interprete_courant()) et dans tous
ses peres successifs. Si l'objet n'existe pas, exit()
static int objet_global_existant (const Nom &nom)
renvoie un drapeau indiquant si un objet de ce
nom existe dans inteprete_courant() ou l'un de ses parents.
Static Public Member Functions inherited from liste
static Objet_U * cree_instance ()
static const Type_info * info ()
static liste & self_cast (Objet_U &)
static const liste & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from liste
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from liste
Sortie & printOn (Sortie &x) const override
Ecriture d'une liste sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une liste sur un flot d'entree.
Objet_U & operator() (int)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Objet_U & operator() (int) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Objet_U & operator() (const Nom &)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Objet_U & operator() (const Nom &) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Objet_U & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Objet_U & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
liste & operator+= (const Objet_U &)
Ajoute un Objet_U a la fin de la liste.
liste & operator+= (const liste &)
Ajoute une list d'Objet_U a la fin de la liste.
liste & operator-= (const Objet_U &)
Supprime un Objet_U de la liste
Affiche un message d'erreur si l'objet n'est pas trouve.
const liste & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
liste & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
Objet_U * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
const Objet_U * operator-> () const
Retourne un pointeur sur l'Objet_U premier element de la liste.
Objet_U & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Objet_U & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Objet_U & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Objet_U & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Objet_U & add (const Objet_U &)
Ajout d'un Objet_U a la liste.
Objet_U & add_deplace (DerObjU &)
Ajout d'un Objet_U a la liste
to_add est libere en sortie.
Objet_U & inserer (const Objet_U &)
Insertion d'un Objet_U dans la liste.
liste & add (const liste &)
Ajout d'une liste a la liste.
liste & inserer (const liste &)
Insertion d'une liste
NON CODE - SORT SYSTEMATIQUEMENT EN ERREUR.
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Objet_U & add_if_not (const Objet_U &)
Ajout d'un Objet_U a la liste ssi il n'existe pas deja.
liste & search (const Objet_U &) const
Recherche d'un Objet_U dans la liste.
liste & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
int contient (const Objet_U &) const
Verifie si un Objet_U appartient ou non a la liste.
int rang (const Objet_U &) const
Renvoie le rang d'un Objet_U dans la liste.
void suppr (const Objet_U &)
Supprime un Objet_U contenu dans la liste.
liste & operator= (const liste &)
Operateur d'affectation de liste.
const liste & dernier () const
Renvoie le dernier element de la liste.
liste & dernier ()
Renvoie le dernier element de la liste.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Noms les_noms_
Ref_Interprete_bloc pere_
Protected Attributes inherited from liste
DerObjU data
liste * suivant_
Detailed Description
Interprete un bloc d'instructions dans le jeu de donnees.
Voir Interprete_bloc::interpreter()
Definition at line 31 of file Interprete_bloc.h.
Member Enumeration Documentation
Bloc_Type
enum Interprete_bloc::Bloc_Type
Enumerator
ACCOLADE
BLOC_EOF
FIN
Definition at line 36 of file Interprete_bloc.h.
{ ACCOLADE, BLOC_EOF, FIN };
Constructor & Destructor Documentation
Interprete_bloc()
Interprete_bloc::Interprete_bloc ()
Definition at line 34 of file Interprete_bloc.cpp.
{
// S'il existe un interprete courant, il devient le pere
// de l'interprete en cours de construction:
  if (interprete_courant_.non_nul())
    pere_ = interprete_courant_;
  interprete_courant_ = *this;
}
References interprete_courant_, O_U_Ptr::non_nul(), and pere_.
~Interprete_bloc()
Interprete_bloc::~Interprete_bloc ()
Definition at line 44 of file Interprete_bloc.cpp.
{
// Restaure la valeur de l'interprete courant precedent
  interprete_courant_ = pere_;
}
References interprete_courant_, and pere_.
Member Function Documentation
ajouter()
Objet_U & Interprete_bloc::ajouter (const Nom & nom, DerObjU & object_to_add)
Ajoute l'objet ob a la liste des objets de l'interprete,
et nomme l'objet avec nom. Si l'objet existe deja, exit()
Definition at line 237 of file Interprete_bloc.cpp.
{
  Journal(3) << "Interprete::ajouter(" << nom << ") de type "
             << ob.valeur().que_suis_je() << finl;
  if (les_noms_.search(nom) >= 0)
    {
      Cerr << "Error in Interprete::ajouter: object " << nom << " already exists." << finl;
      exit();
    }
  les_noms_.add(nom);
  Objet_U& obu = add_deplace(ob);
  obu.nommer(nom);
  return obu;
}
References Vect_Nom::add(), liste::add_deplace(), Cerr, Process::exit(), finl, Process::Journal(), les_noms_, Objet_U::nommer(), Objet_U::que_suis_je(), Noms::search(), and Deriv_Objet_U::valeur().
Referenced by Domaine::creer_mes_domaines_frontieres(), Pb_Multiphase::creer_milieu(), Lire::interpreter(), Typer_Lire::interpreter(), TroisDto2D::interpreter_(), interpreter_bloc(), and Pbc_MED::readOn().
cree_instance()
Objet_U * Interprete_bloc::cree_instance () static
Definition at line 19 of file Interprete_bloc.cpp.
duplique()
int Interprete_bloc::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Interprete_bloc.cpp.
get_info()
const Type_info * Interprete_bloc::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 19 of file Interprete_bloc.cpp.
info()
const Type_info * Interprete_bloc::info () static
Definition at line 19 of file Interprete_bloc.cpp.
interprete_courant()
Interprete_bloc & Interprete_bloc::interprete_courant () static
renvoie l'interprete_bloc en train d'etre
lu dans le jeu de donnees. On change d'interprete courant
quand on cree et on detruit un objet de type Interprete_bloc
(par exemple quand on entre ou qu'on sort d'un bloc { })
Definition at line 29 of file Interprete_bloc.cpp.
{
  return interprete_courant_.valeur();
}
References interprete_courant_, and Ref_Interprete_bloc::valeur().
Referenced by Domaine::creer_mes_domaines_frontieres(), Pb_Multiphase::creer_milieu(), Lire::interpreter(), Typer_Lire::interpreter(), Debog_Pb_Wrapper::interpreter(), TroisDto2D::interpreter_(), objet_global(), and objet_global_existant().
interpreter_bloc()
Entree & Interprete_bloc::interpreter_bloc (Entree & is, Bloc_Type bloc_type, int verifier_sans_interpreter)
Interpretation d'un bloc d'instructions prises dans l'entree is.
Si le bloc commence par {, on suppose que l'accolade a deja ete lue.
Le bloc se termine soit par }, soit par la fin du fichier, soit par
le mot FIN en fonction de bloc_type (voir mon_main.cpp par exemple)
Si verifie_sans_interpreter!=0, on ne cree aucun objet et on ne
lance aucun interprete, on se contente de verifier la coherence des
accolades (meme nombre de { que de }).
< On retient les 8 premiers mots du commentaire
Definition at line 70 of file Interprete_bloc.cpp.
{
// Le niveau de sortie des messages journal
  const int jlevel = 3;
  Journal(jlevel) << "Interprete_bloc::interpreter_bloc bloc_type=" << (int)bloc_type << finl;
  Motcle motlu;
  is >> motlu;
  while(1)
    {
// Est-ce qu'on est a la fin du bloc ?
      if (is.eof())
        {
// Certains fichiers .data ne se terminent pas par FIN, on accepte aussi d'arriver a eof
// sans avoir trouve "FIN".
          if (bloc_type == BLOC_EOF || bloc_type == FIN)
            {
              Journal(jlevel) << "Interprete_bloc: end of file => end of bloc" << finl;
              break;
            }
          else
            {
              Cerr << "Error in Interprete_bloc: unexpected end of file\n"
                   << "check for missig \"}\" or missing FIN keyword"
                   << finl;
              exit();
            }
        }
// Autres fins possibles:
      if (motlu == "}" || motlu == "FIN|END")
        {
          if ((motlu == "}" && bloc_type == ACCOLADE)
              || (motlu == "FIN|END" && bloc_type == FIN))
            {
              Journal(jlevel) << "Interprete_bloc: reading " << motlu << " => end of bloc" << finl;
              break;
            }
          else
            {
              if (motlu == "}")
                Cerr << "Error in Interprete_bloc: extra \"}\" in data file" << finl;
              else
                Cerr << "Error in Interprete_bloc: unexpected FIN, check for missing \"}\""
                     << finl;
              exit();
            }
        }
// Est-ce que c'est un commentaire ?
      if (motlu == "#")
        {
          Nom commentaire("# ");
          Nom nom_lu;
          int countleft = 8; //!< On retient les 8 premiers mots du commentaire
          do
            {
              is >> nom_lu;
              if (is.eof())
                break;
              if ((countleft--) > 0)
                {
                  commentaire += nom_lu;
                  commentaire += " ";
                }
            }
          while (nom_lu != "#");
          if (is.eof())
            {
              Cerr << "Error in Interprete_bloc: end of file while reading a comment :\n"
                   << commentaire << "..." << finl;
            }
// Prochain mot a interpreter:
          motlu = nom_lu;
        }
      else if (motlu == "{")
        {
          Journal(jlevel) << "Interprete_bloc: reading { => creating new Interprete_bloc"
                          << finl;
// Est-ce que c'est un debut de bloc ?
// Nouvel interprete:
          Interprete_bloc inter;
          inter.interpreter_bloc(is, ACCOLADE, verifie_sans_interpreter);
        }
      else
        {
          if (verifie_sans_interpreter)
            {
// Si on veut seulement verifier le nombre d'accolades,
// il suffit d'ignorer le motcle... on ouvre recursivement
// de nouveaux interprete si on rencontre { et on les ferme
// si on trouve }. S'il manque une } a la fin, on obtiendra le message
// "check for missing }" et s'il y en a une en trop on aura
// le message "extra }"
              Journal(jlevel) << "Interprete_bloc: just checking {} => ignore keyword "
                              << motlu << finl;
              verifie(motlu);
            }
          else
            {
// Dans le bloc suivant, s'il y a une erreur de lecture sur is, c'est une erreur:
              is.set_error_action(Entree::ERROR_EXIT);
              int export_object = 0;
              if (motlu == "export")
                {
                  Journal(jlevel) << "Exporting object, reading object type..." << finl;
                  export_object = 1;
                  is >> motlu;
                }
// Le mot cle doit etre un type d'objet instanciable
              Journal(jlevel) << "Interprete_bloc: reading " << motlu
                              << " => trying to instanciate object" << finl;
              DerObjU objet;
              objet.typer(motlu);
              if (sub_type(Interprete, objet.valeur()))
                {
// Si c'est un interprete, on appelle la methode interprete de l'objet:
                  Journal(jlevel) << " Calling object.interpreter()" << finl;
                  Interprete& inter = ref_cast(Interprete, objet.valeur());
                  inter.interpreter(is);
                }
              else
                {
// Ce n'est pas un interprete, on lit le nom de l'objet et on le stocke
                  Journal(jlevel) << " Reading object name" << finl;
                  Nom nom_objet;
                  is >> nom_objet;
                  Journal(jlevel) << " Storing object " << nom_objet << " of type " << motlu << finl;
                  if (!export_object || !pere_.non_nul())
                    ajouter(nom_objet, objet);
                  else
                    pere_.valeur().ajouter(nom_objet, objet);
                }
              is.set_error_action(Entree::ERROR_CONTINUE);
            }
        }
      is >> motlu;
    }
  return is;
}
References ACCOLADE, ajouter(), BLOC_EOF, Cerr, Entree::eof(), Entree::ERROR_CONTINUE, Entree::ERROR_EXIT, Process::exit(), FIN, finl, Interprete::interpreter(), interpreter_bloc(), Process::Journal(), O_U_Ptr::non_nul(), pere_, ref_cast, Entree::set_error_action(), sub_type, Deriv_::typer(), Deriv_Objet_U::valeur(), Ref_Interprete_bloc::valeur(), and verifie().
Referenced by mon_main::dowork(), Execute_parallel::interpreter(), Lire_Fichier::interpreter(), Debog_Pb_Wrapper::interpreter(), and interpreter_bloc().
objet_global()
Objet_U & Interprete_bloc::objet_global (const Nom & nom) static
cherche l'objet demande dans l'Interprete_bloc
courant (Interprete_bloc::interprete_courant()) et dans tous
ses peres successifs. Si l'objet n'existe pas, exit()
< Pour le compilo
Definition at line 255 of file Interprete_bloc.cpp.
{
  REF(Interprete_bloc) ptr(interprete_courant());
  while (ptr.non_nul())
    {
      Interprete_bloc& interp = ptr.valeur();
      if (interp.objet_local_existant(nom))
        {
          Objet_U& objet = interp.objet_local(nom);
          return objet;
        }
      ptr = interp.pere_;
    }
// Objet non trouve !
  Cerr << "Error in Interprete::objet: object " << nom
       << " does not exist." << finl;
  Process::exit();
  return objet_global(nom); //!< Pour le compilo
}
References Cerr, Process::exit(), finl, interprete_courant(), objet_global(), objet_local(), objet_local_existant(), pere_, REF, and liste::valeur().
Referenced by TroisDto2D::interpreter_(), Interprete::objet(), objet_global(), and Pbc_MED::readOn().
objet_global_existant()
int Interprete_bloc::objet_global_existant (const Nom & nom) static
renvoie un drapeau indiquant si un objet de ce
nom existe dans inteprete_courant() ou l'un de ses parents.
Definition at line 277 of file Interprete_bloc.cpp.
{
  REF(Interprete_bloc) ptr(interprete_courant());
  while (ptr.non_nul())
    {
      Interprete_bloc& interp = ptr.valeur();
      if (interp.objet_local_existant(nom))
        return 1;
      ptr = interp.pere_;
    }
// Objet non trouve !
  return 0;
}
References interprete_courant(), objet_local_existant(), pere_, REF, and liste::valeur().
Referenced by Domaine::creer_mes_domaines_frontieres(), TroisDto2D::interpreter_(), and Interprete::objet_existant().
objet_local()
Objet_U & Interprete_bloc::objet_local (const Nom & nom)
Renvoie l'Objet_U correspondant a nom contenu dans cet interprete_bloc
Si l'objet n'existe pas, exit() (on ne cherche pas dans le pere).
Definition at line 215 of file Interprete_bloc.cpp.
{
  const int i = les_noms_.search(nom);
  if (i < 0)
    {
      Cerr << "Internal error in Interprete::objet_local() : object " << nom
           << " does not exist" << finl;
      exit();
    }
  return operator[](i);
}
References Cerr, Process::exit(), finl, les_noms_, liste::operator[](), and Noms::search().
Referenced by objet_global().
objet_local_existant()
int Interprete_bloc::objet_local_existant (const Nom & nom)
renvoie un drapeau indiquant si un objet de ce nom
est enregistre dans cet inteprete (ne teste pas le pere).
Definition at line 229 of file Interprete_bloc.cpp.
{
  const int i = les_noms_.search(nom);
  return (i >= 0);
}
References les_noms_, and Noms::search().
Referenced by objet_global(), and objet_global_existant().
printOn()
Sortie & Interprete_bloc::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 50 of file Interprete_bloc.cpp.
{
  exit();
  return os;
}
References Process::exit().
readOn()
Entree & Interprete_bloc::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 56 of file Interprete_bloc.cpp.
{
  exit();
  return is;
}
References Process::exit().
self_cast() [1/2]
const Interprete_bloc & Interprete_bloc::self_cast (const Objet_U & r) static
Definition at line 19 of file Interprete_bloc.cpp.
self_cast() [2/2]
Interprete_bloc & Interprete_bloc::self_cast (Objet_U & r) static
Definition at line 19 of file Interprete_bloc.cpp.
taille_memoire()
unsigned Interprete_bloc::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Interprete_bloc.cpp.
Member Data Documentation
info_obj
const Type_info Interprete_bloc::info_obj static
Definition at line 33 of file Interprete_bloc.h.
les_noms_
Noms Interprete_bloc::les_noms_ protected
Definition at line 49 of file Interprete_bloc.h.
Referenced by ajouter(), objet_local(), and objet_local_existant().
pere_
Ref_Interprete_bloc Interprete_bloc::pere_ protected
Definition at line 51 of file Interprete_bloc.h.
Referenced by Interprete_bloc(), interpreter_bloc(), objet_global(), objet_global_existant(), and ~Interprete_bloc().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Interprete_bloc.h
src/Kernel/Utilitaires/Interprete_bloc.cpp