TRUST: Perte_Charge_Singuliere_PolyMAC_Face Class Reference
Perte_Charge_Singuliere_PolyMAC_Face Class Reference
class Perte_Charge_Singuliere_PolyMAC_Face
#include <Perte_Charge_Singuliere_PolyMAC_Face.h>
Public Member Functions
Perte_Charge_Singuliere_PolyMAC_Face ()
~Perte_Charge_Singuliere_PolyMAC_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & calculer (DoubleTab &) const
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
void remplir_num_faces (Entree &)
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Perte_Charge_Singuliere_PolyMAC_Face & self_cast (Objet_U &)
static const
Perte_Charge_Singuliere_PolyMAC_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Protected Attributes
IntVect sgn
Detailed Description
class Perte_Charge_Singuliere_PolyMAC_Face
See also:
Perte_Charge_PolyMAC_Face
Definition at line 42 of file Perte_Charge_Singuliere_PolyMAC_Face.h.
Constructor & Destructor Documentation
Perte_Charge_Singuliere_PolyMAC_Face::Perte_Charge_Singuliere_PolyMAC_Face ()
Definition at line 32 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
Perte_Charge_Singuliere_PolyMAC_Face::~Perte_Charge_Singuliere_PolyMAC_Face ()
Definition at line 32 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
Member Function Documentation
DoubleTab & Perte_Charge_Singuliere_PolyMAC_Face::ajouter (DoubleTab & resu) const [virtual]
< Taking account of inclined plane
Implements Perte_Charge_PolyMAC_Face.
Definition at line 86 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
References dabs(), Perte_Charge::direction_perte_charge(), Zone_PolyMAC::face_normales(), Zone_VF::face_surfaces(), Perte_Charge_Singuliere::K(), Perte_Charge_PolyMAC_Face::la_vitesse, Perte_Charge_PolyMAC_Face::la_zone_PolyMAC, Zone_VF::nb_faces(), Perte_Charge_PolyMAC_Face::num_faces, Zone_VF::porosite_face(), IntVect::size(), and Ref_Zone_PolyMAC::valeur().
Referenced by calculer().
{
  const Zone_PolyMAC& zone_PolyMAC = la_zone_PolyMAC.valeur();
// const DoubleVect& volumes_entrelaces = zone_PolyMAC.volumes_entrelaces();
  const DoubleVect& p_f = zone_PolyMAC.porosite_face();
  const DoubleTab& vit = la_vitesse->valeurs();
  for (int i = 0, f; i < num_faces.size(); i++) if ((f = num_faces(i)) < zone_PolyMAC.nb_faces())
      {
        double Ud = vit(f) * p_f(f),
               surf = direction_perte_charge() < 0 ? zone_PolyMAC.face_surfaces(f) : dabs(zone_PolyMAC.face_normales(f,direction_perte_charge())); //!< Taking account of inclined plane
        resu(f) -= 0.5 * surf * p_f(f) * K() * Ud * dabs(Ud);
      }
  return resu;
}
DoubleTab & Perte_Charge_Singuliere_PolyMAC_Face::calculer (DoubleTab & resu) const [virtual]
Implements Perte_Charge_PolyMAC_Face.
Definition at line 102 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
References ajouter().
{
  resu = 0;
  return ajouter(resu);
}
void Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const [virtual]
contribution a la matrice implicite des termes sources
par defaut pas de contribution
< Taking account of inclined plane
Reimplemented from Source_base.
Definition at line 108 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
References Matrice_Morse::coef(), dabs(), Perte_Charge::direction_perte_charge(), Zone_PolyMAC::face_normales(), Zone_VF::face_surfaces(), Perte_Charge_Singuliere::K(), Perte_Charge_PolyMAC_Face::la_vitesse, Perte_Charge_PolyMAC_Face::la_zone_PolyMAC, Zone_VF::nb_faces(), Perte_Charge_PolyMAC_Face::num_faces, Zone_VF::porosite_face(), IntVect::size(), and Ref_Zone_PolyMAC::valeur().
{
  const Zone_PolyMAC& zone_PolyMAC = la_zone_PolyMAC.valeur();
  const DoubleVect& p_f = zone_PolyMAC.porosite_face();
  const DoubleTab& vit = la_vitesse->valeurs();
  for (int i = 0, f; i < num_faces.size(); i++) if ((f = num_faces(i)) < zone_PolyMAC.nb_faces())
      {
        double Ud = vit(f) * p_f(f),
               surf = direction_perte_charge() < 0 ? zone_PolyMAC.face_surfaces(f) : dabs(zone_PolyMAC.face_normales(f,direction_perte_charge())); //!< Taking account of inclined plane
        matrice.coef(f, f) += surf * p_f(f) * K() * p_f(f) * dabs(Ud);
      }
}
Objet_U * Perte_Charge_Singuliere_PolyMAC_Face::cree_instance () [static]
Definition at line 32 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
int Perte_Charge_Singuliere_PolyMAC_Face::duplique () const [virtual]
Implements Perte_Charge_PolyMAC_Face.
Definition at line 32 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
const Type_info * Perte_Charge_Singuliere_PolyMAC_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_PolyMAC_Face.
Definition at line 32 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
const Type_info * Perte_Charge_Singuliere_PolyMAC_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_PolyMAC_Face.
Definition at line 32 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
void Perte_Charge_Singuliere_PolyMAC_Face::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Perte_Charge_PolyMAC_Face.
Definition at line 122 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
References Source_base::bilan(), Perte_Charge_Singuliere::calculate_Q(), MorEqn::equation(), Perte_Charge_PolyMAC_Face::num_faces, sgn, and Perte_Charge_Singuliere::update_K().
{
  Perte_Charge_PolyMAC_Face::mettre_a_jour(temps);
  update_K(equation(), calculate_Q(equation(), num_faces, sgn), bilan());
}
Sortie & Perte_Charge_Singuliere_PolyMAC_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Perte_Charge_PolyMAC_Face.
Definition at line 37 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Perte_Charge_Singuliere_PolyMAC_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Perte_Charge_PolyMAC_Face.
Definition at line 45 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
References Source_base::bilan(), Perte_Charge_Singuliere::identifiant_, Perte_Charge_Singuliere::lire_donnees(), Perte_Charge_Singuliere::regul_, remplir_num_faces(), DoubleVect::resize(), Source_base::set_description(), and Source_base::set_fichier().
{
  Perte_Charge_Singuliere::lire_donnees(s);
  remplir_num_faces(s);
  if (regul_) //fichier de sortie si regulation
    {
      bilan().resize(3); //K deb cible
      set_fichier(Nom("K_") + identifiant_);
      set_description(Nom("Regulation du Ksing de la surface ") + identifiant_ + "\nt K deb cible");
    }
  return s;
}
void Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces (Entree & s)
< not to count several (number of processes) times the same face
Definition at line 67 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
References Cerr, Probleme_base::domaine(), MorEqn::equation(), Process::exit(), finl, Process::je_suis_maitre(), Perte_Charge_Singuliere::lire_surfaces(), Process::mp_max(), Zone_dis_base::nb_elem(), Perte_Charge_PolyMAC_Face::num_faces, Equation_base::probleme(), ref_cast, IntVect::resize(), sgn, IntVect::size(), and valeur().
Referenced by readOn().
{
  const Domaine& le_domaine = equation().probleme().domaine();
  const Zone_PolyMAC& zone_PolyMAC = ref_cast(Zone_PolyMAC,equation().zone_dis().valeur());
  int taille_bloc = zone_PolyMAC.nb_elem();
  num_faces.resize(taille_bloc);
  lire_surfaces(s,le_domaine,zone_PolyMAC,num_faces, sgn);
// int nfac_tot = mp_sum(num_faces.size());
  int nfac_max = (int)mp_max(num_faces.size()); //!< not to count several (number of processes) times the same face
  if(je_suis_maitre() && nfac_max == 0)
    {
      Cerr << "Error when defining the surface plane for the singular porosity :" << finl;
      Cerr << "No mesh faces has been found for the surface plane." << finl;
      Cerr << "Check the coordinate of the surface plane which should match mesh coordinates." << finl;
      exit();
    }
}
const Perte_Charge_Singuliere_PolyMAC_Face & Perte_Charge_Singuliere_PolyMAC_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Perte_Charge_PolyMAC_Face.
Definition at line 32 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
Perte_Charge_Singuliere_PolyMAC_Face & Perte_Charge_Singuliere_PolyMAC_Face::self_cast (Objet_U & r) [static]
Reimplemented from Perte_Charge_PolyMAC_Face.
Definition at line 32 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
unsigned Perte_Charge_Singuliere_PolyMAC_Face::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 32 of file Perte_Charge_Singuliere_PolyMAC_Face.cpp.
Member Data Documentation
const Type_info Perte_Charge_Singuliere_PolyMAC_Face::info_obj [static]
Reimplemented from Perte_Charge_PolyMAC_Face.
Definition at line 46 of file Perte_Charge_Singuliere_PolyMAC_Face.h.
IntVect Perte_Charge_Singuliere_PolyMAC_Face::sgn [protected]
Definition at line 57 of file Perte_Charge_Singuliere_PolyMAC_Face.h.
Referenced by mettre_a_jour(), and remplir_num_faces().
The documentation for this class was generated from the following files:
src/PolyMAC/Sources/Perte_Charge_Singuliere_PolyMAC_Face.h
src/PolyMAC/Sources/Perte_Charge_Singuliere_PolyMAC_Face.cpp