TRUST: Moyenne_volumique Class Reference
Moyenne_volumique Class Reference
: cet interprete permet, a la fin du calcul (apres "resoudre"),
de calculer et de stocker dans un fichier lata le produit de convolution
de certains champs d'un probleme avec une fonction filtre arbitraire.
On peut l'utiliser comme un interprete (voir Moyenne_volumique::interpreter())
ou n'importe ou a l'interieur du code comme ceci:
Moyenne_volumique moy;
is >> moy; // lecture de la fonction filtre
moy.calculer_convolution_champ_elem/face(...)
#include <Moyenne_volumique.h>
Public Member Functions
Moyenne_volumique ()
~Moyenne_volumique ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &) override
Lecture des parametres dans le jeu de donnees. Format attendu:
Moyenne_volumique {
nom_pb NOM_DU_PROBLEME (ou chercher les champs sources)
nom_domaine DOMAINE_CIBLE (on evalue la convolution aux elements de ce domaine)
noms_champs N CHAMP1 CHAMP2 ... (noms des champs a filtrer dans le probleme)
[ nom_fichier_post NOM_SANS_EXTENSION ] (soit on donne nom_fichier et format_post,
soit on donne fichier_post)
[ format_post lata|meshtv|lml|med|... ] (par defaut lata)
[ fichier_post Format_Post_XXX { ... } ] (lecture par readOn du Format_Post_XXX)
fonction_filtre ... (format : voir Moyenne_volumique::readOn())
[ localisation ELEM|SOM ]
}.
virtual void calculer_convolution_champ_elem (const Zone_VF &zone_source, const DoubleTab &champ_source, const DoubleTab &coords_to_compute, DoubleTab &resu) const
Calcule le produit de convolution entre la fonction filtre et
le champ "champ_source" qui doit etre discretise aux elements de la "zone_source".
Le tableau resu aura le meme nombre de colonnes que le tableau "champ_source", et
le meme nombre de lignes que le tableau coords_to_compute.
On suppose que la fonction filtre a un support inclu dans un cube de demi-cote box-size
centre sur l'origine (on ne calcule pas la contribution des elements hors de ce cube).
virtual void calculer_convolution_champ_face (const Zone_VF &zone_source, const DoubleTab &champ_source, const DoubleTab &coords_to_compute, DoubleTab &resu) const
Idem que calculer_convolution_champ_elem pour un champ VDF aux faces.
(on suppose que le champ source est un champ vectoriel contenant pour chaque face
la composante normale du champ a cette face)
Pour chaque colonne du tableau champ_source, on remplit "dimension" colonnes
du tableau resu : la premiere utilisant uniquement les faces de normale X, la deuxieme
avec les faces de normale Y, etc...
virtual void eval_filtre (const DoubleTab &coords, ArrOfDouble &result) const
Evalue la fonction filtre en chaque coordonnee coord
Methode appelee dans la classe Calcul_integrale_locale.
double box_size () const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Moyenne_volumique & self_cast (Objet_U &)
static const Moyenne_volumique & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Types
enum Type {
ERROR , BOITE , CHAPEAU , GAUSSIENNE ,
PARSER , QUADRA
}
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
lecture de la fonction de filtrage.
{
type BOITE|CHAPEAU|QUADRA|GAUSSIENNE|PARSER
demie-largeur L
[ omega W ]
[ expression FORMULE ]
}
void traiter_champs (const Motcles &noms_champs, const Nom &nom_pb, const Nom &nom_dom, const DoubleTab &coords, Format_Post_base &post, double temps, const Motcle &localisation)
fonction outil permettant de faire les calculs et d'ecrire le resultat
dans un fichier lata pour tous les champs d'un type donne de la liste noms_champs.
Methode appelee par interpreter()
type_champ=0 => traiter les champs aux elements
type_champ=1 => traiter les champs aux faces
int get_champ (const Nom &nom_pb, const Nom &nom_champ, Ref_Champ_base &ref_champ)
Cherche le champ de nom "nom_champ" dans le probleme de nom "nom_pb"
dans les objers de l'interprete.
Methode appelee par traiter_champs()
virtual void calculer_convolution (const Zone_VF &zone_source, const DoubleTab &champ_source, const DoubleTab &coords_to_compute, DoubleTab &resu) const
methode generale pour calculer une convolution a partir d'un
champ aux elements ou aux faces. Methode appelee par calculer_convolution_champ_elem()
et calculer_convolution_champ_face()
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Type type_
double l_
double box_size_
Nom expression_parser_
Parser parser_
Detailed Description
: cet interprete permet, a la fin du calcul (apres "resoudre"),
de calculer et de stocker dans un fichier lata le produit de convolution
de certains champs d'un probleme avec une fonction filtre arbitraire.
On peut l'utiliser comme un interprete (voir Moyenne_volumique::interpreter())
ou n'importe ou a l'interieur du code comme ceci:
Moyenne_volumique moy;
is >> moy; // lecture de la fonction filtre
moy.calculer_convolution_champ_elem/face(...)
Definition at line 37 of file Moyenne_volumique.h.
Member Enumeration Documentation
Type
enum Moyenne_volumique::Type protected
Enumerator
ERROR
BOITE
CHAPEAU
GAUSSIENNE
PARSER
QUADRA
Definition at line 59 of file Moyenne_volumique.h.
{ ERROR, BOITE, CHAPEAU, GAUSSIENNE, PARSER, QUADRA };
Constructor & Destructor Documentation
Moyenne_volumique()
Moyenne_volumique::Moyenne_volumique ()
Definition at line 25 of file Moyenne_volumique.cpp.
~Moyenne_volumique()
Moyenne_volumique::~Moyenne_volumique ()
Definition at line 25 of file Moyenne_volumique.cpp.
Member Function Documentation
box_size()
double Moyenne_volumique::box_size () const inline
Definition at line 49 of file Moyenne_volumique.h.
{ return box_size_;  }
References box_size_.
Referenced by Calcul_integrale_locale::calculer().
calculer_convolution()
void Moyenne_volumique::calculer_convolution (const Zone_VF & zone_source, const DoubleTab & champ_source, const DoubleTab & coords_to_compute, DoubleTab & resu) const protected virtual
methode generale pour calculer une convolution a partir d'un
champ aux elements ou aux faces. Methode appelee par calculer_convolution_champ_elem()
et calculer_convolution_champ_face()
Definition at line 621 of file Moyenne_volumique.cpp.
{
  assert(resu.dimension(0) == coords_to_compute.dimension(0));
  const int dim = Objet_U::dimension;
  const int nbproc = Process::nproc();
  const int nb_coords_to_compute = coords_to_compute.dimension(0);
  const int nb_coords_max = ::mp_max(nb_coords_to_compute);
  int nb_comp;
  nb_comp = champ_source.line_size();
  assert(resu.line_size() == nb_comp);
  DoubleTab coords(nbproc, 3);
  ArrOfInt flag(nbproc);
  ArrOfDouble resu_partiel(nb_comp);
  DoubleTab resu_partiels(nbproc, nb_comp);
  Calcul_integrale_locale integrale_locale(zone_source,
                                           *this,
                                           champ_source);
// Boucle sur les coordonnees x locales pour lesquelles on veut calculer l'integrale I(x).
// Si x est pres du bord, le support de la fonction filtre couvre des processeurs voisins
// qu'il faut ajouter. Pour chaque coordonnees, on demande a tous les autres processeurs
// de calculer la contribution. Donc on boucle sur le max du nombre de coordonnees pour
// synchroniser les procs:
  int i, j;
  for (int i_coord = 0; i_coord < nb_coords_max; i_coord++)
    {
// Chaque processeur envoie la coordonnee a calculer a tous les processeurs:
      if (i_coord < nb_coords_to_compute)
        {
          for (j = 0; j < dim; j++)
            {
              double x = coords_to_compute(i_coord, j);
              for (i = 0; i < nbproc; i++)
                coords(i, j) = x;
            }
          flag = 1;
        }
      else
        {
          flag = 0;
        }
      envoyer_all_to_all(coords, coords);
      envoyer_all_to_all(flag, flag);
// On a dans coord(pe, i) les coordonnees demandees par chaque processeur et
// flag[pe] indique si le processeur a demande une coordonnee ou s'il a fini
// sa liste coords_to_compute.
// On calcule maintenant la contribution du processeur local aux integrales I(x)
// pour ces coordonnees. En general, le processeur qui a cette coordonnee chez lui
// a beaucoup de travail pour celle-ci et presque rien a faire pour les autres coordonnees
// (si la coordonnee est loin du domaine, l'octree trouve tres rapidement la liste vide).
// Donc les calculs sont a peu pres equilibres sur les processeurs.
      for (i = 0; i < nbproc; i++)
        {
          if (flag[i])
            {
              integrale_locale.calculer(coords(i, 0), coords(i, 1), coords(i, 2), resu_partiel);
              for (j = 0; j < nb_comp; j++)
                resu_partiels(i, j) = resu_partiel[j];
            }
        }
// On renvoie a chaque processeur la contribution du processeur local pour la coordonnee
// qu'il a demande:
      envoyer_all_to_all(resu_partiels, resu_partiels);
// Le resultat est la somme des contributions de tous les processeurs:
      if (i_coord < nb_coords_to_compute)
        {
          for (j = 0; j < nb_comp; j++)
            {
              double x = 0.;
              for (i = 0; i < nbproc; i++)
                x += resu_partiels(i, j);
              resu(i_coord, j) = x;
            }
        }
    }
}
References Calcul_integrale_locale::calculer(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, envoyer_all_to_all(), TRUSTVect< _TYPE_ >::line_size(), Process::mp_max(), and Process::nproc().
Referenced by calculer_convolution_champ_elem().
calculer_convolution_champ_elem()
void Moyenne_volumique::calculer_convolution_champ_elem (const Zone_VF & zone_source, const DoubleTab & champ_source, const DoubleTab & coords_to_compute, DoubleTab & resu) const virtual
Calcule le produit de convolution entre la fonction filtre et
le champ "champ_source" qui doit etre discretise aux elements de la "zone_source".
Le tableau resu aura le meme nombre de colonnes que le tableau "champ_source", et
le meme nombre de lignes que le tableau coords_to_compute.
On suppose que la fonction filtre a un support inclu dans un cube de demi-cote box-size
centre sur l'origine (on ne calcule pas la contribution des elements hors de ce cube).
Definition at line 710 of file Moyenne_volumique.cpp.
{
  assert(champ_source.dimension(0) == zone_source.zone().nb_elem());
  calculer_convolution(zone_source, champ_source,
                       coords_to_compute, resu);
}
References calculer_convolution(), TRUSTTab< _TYPE_ >::dimension(), Zone::nb_elem(), and Zone_dis_base::zone().
Referenced by traiter_champs().
calculer_convolution_champ_face()
void Moyenne_volumique::calculer_convolution_champ_face (const Zone_VF & zone_source, const DoubleTab & champ_source, const DoubleTab & coords_to_compute, DoubleTab & resu) const virtual
Idem que calculer_convolution_champ_elem pour un champ VDF aux faces.
(on suppose que le champ source est un champ vectoriel contenant pour chaque face
la composante normale du champ a cette face)
Pour chaque colonne du tableau champ_source, on remplit "dimension" colonnes
du tableau resu : la premiere utilisant uniquement les faces de normale X, la deuxieme
avec les faces de normale Y, etc...
Definition at line 726 of file Moyenne_volumique.cpp.
{
  Cerr << " Moyenne_volumique::calculer_convolution_champ_face is not coded" << finl;
  exit();
}
References Cerr, Process::exit(), and finl.
cree_instance()
Objet_U * Moyenne_volumique::cree_instance () static
Definition at line 25 of file Moyenne_volumique.cpp.
duplique()
int Moyenne_volumique::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file Moyenne_volumique.cpp.
eval_filtre()
void Moyenne_volumique::eval_filtre (const DoubleTab & coords, ArrOfDouble & result) const virtual
Evalue la fonction filtre en chaque coordonnee coord
Methode appelee dans la classe Calcul_integrale_locale.
Definition at line 120 of file Moyenne_volumique.cpp.
{
  const int dim = Objet_U::dimension;
  assert(dim == coords.dimension(1));
  const int n = coords.dimension(0);
  assert(result.size_array() == n);
  switch(type_)
    {
    case PARSER:
      {
        for (int i = 0; i < n; i++)
          {
            for (int j = 0; j < dim; j++)
              parser_.setVar(j, coords(i,j));
            result[i] = parser_.eval();
          }
        break;
      }
    case BOITE:
      {
        double facteur = 0.;
        if (dim == 2)
          facteur = 1. / (l_ * l_ * 4.);
        else
          facteur = 1. / (l_ * l_ * l_ * 8.);
        for (int i = 0; i < n; i++)
          {
            const double x = coords(i,0);
            const double y = coords(i,1);
            const double z = (dim==3) ? coords(i,2) : 0.;
            double r = facteur;
            if (x > l_ || x < -l_
                || y > l_ || y < -l_
                || z > l_ || z < -l_)
              r = 0.;
            result[i] = r;
          }
        break;
      }
    case CHAPEAU:
      {
        const double L2D = l_*l_*l_*l_;
        const double L3D = L2D*l_*l_;
        double facteur;
        if (dim==3)
          facteur = 1. / L3D;
        else
          facteur = 1. / (L2D * l_);
        const int nbis = coords.dimension(0);
        for (int i = 0; i < nbis; i++)
          {
            const double x = coords(i, 0);
            const double y = coords(i, 1);
            const double z = (dim == 3) ? coords(i, 2) : 0.;
            double resu = 0.;
            const double ax = std::fabs(x);
            const double ay = std::fabs(y);
            const double az = std::fabs(z);
            if (ax <= l_ && ay <= l_ && az <= l_)
              resu = (l_-ax) * (l_-ay) * (l_-az) * facteur;
            result[i] = resu;
          }
        break;
      }
    case GAUSSIENNE:
      {
        double facteur1 = - 0.5 / (l_ * l_);
        double facteur2 = 1. / (l_ * sqrt(2 * M_PI));
        if (dim == 2)
          facteur2 = facteur2 * facteur2;
        else
          facteur2 = facteur2 * facteur2 * facteur2;
        for (int i = 0; i < n; i++)
          {
            const double x = coords(i, 0);
            const double y = coords(i, 1);
            const double z = (dim == 3) ? coords(i, 2) : 0.;
            const double k = (x*x + y*y + z*z) * facteur1;
            result[i] = exp(k) * facteur2;
          }
        break;
      }
    case QUADRA:
      {
        for (int i = 0; i < n; i++)
          {
            const double x = coords(i, 0);
            const double y = coords(i, 1);
            const double z = (dim == 3) ? coords(i, 2) : 0.;
            double resu = 0;
            if (std::fabs(x) < l_ && std::fabs(y) < l_ && std::fabs(z) < l_)
              {
                resu = fonction_quadra(x,l_) * fonction_quadra(y,l_);
                if (dim == 3)
                  resu *= fonction_quadra(z,l_);
              }
            result[i] = resu;
          }
        break;
      }
    default:
      {
        Cerr << "Error in Moyenne_volumique::eval() : filter function is not initialized." << finl;
        exit();
      }
    }
}
References BOITE, Cerr, CHAPEAU, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Parser::eval(), Process::exit(), finl, fonction_quadra(), GAUSSIENNE, l_, M_PI, PARSER, parser_, QUADRA, Parser::setVar(), TRUSTArray< _TYPE_ >::size_array(), and type_.
Referenced by Calcul_integrale_locale::calculer().
get_champ()
int Moyenne_volumique::get_champ (const Nom & nom_pb, const Nom & nom_champ, Ref_Champ_base & ref_champ) protected
Cherche le champ de nom "nom_champ" dans le probleme de nom "nom_pb"
dans les objers de l'interprete.
Methode appelee par traiter_champs()
Definition at line 233 of file Moyenne_volumique.cpp.
{
  Probleme_base& pb = ref_cast(Probleme_base, objet(nom_pb));
// Le champ est-il defini dans les postraitements (statistiques) ?
  const int nb_post = pb.postraitements().size();
  Motcle mc_nom_champ(nom_champ);
  for (int i_post = 0; i_post < nb_post; i_post++)
    {
      if (sub_type(Postraitement_base, pb.postraitements()[i_post].valeur()))
        {
          Postraitement& post = ref_cast(Postraitement, pb.postraitements()[i_post].valeur());
          Operateurs_Statistique_tps& stats = post.les_statistiques();
          const int nstat = stats.size();
          for (int i_stat = 0; i_stat < nstat; i_stat++)
            {
              Motcle tmp(stats[i_stat].valeur().le_nom() );
              if (tmp == mc_nom_champ)
                {
                  Operateur_Statistique_tps_base& stat = stats[i_stat].valeur();
                  ref_cast_non_const(DoubleTab, stat.integrale().valeurs()) = stat.calculer_valeurs();
                  ref_champ = stat.integrale();
                  return 1;
                }
            }
        }
    }
  ref_champ = pb.get_champ(nom_champ);
  return 1;
}
References Operateur_Statistique_tps_base::calculer_valeurs(), Probleme_base::get_champ(), Operateur_Statistique_tps_base::integrale(), Objet_U::le_nom(), Postraitement::les_statistiques(), Interprete::objet(), Probleme_base::postraitements(), ref_cast, ref_cast_non_const, liste::size(), sub_type, List_Deriv_Postraitement_base::valeur(), List_Operateur_Statistique_tps::valeur(), valeur(), and Champ_Fonc::valeurs().
Referenced by interpreter(), and traiter_champs().
get_info()
const Type_info * Moyenne_volumique::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 25 of file Moyenne_volumique.cpp.
info()
const Type_info * Moyenne_volumique::info () static
Definition at line 25 of file Moyenne_volumique.cpp.
interpreter()
Entree & Moyenne_volumique::interpreter (Entree & is) override virtual
Lecture des parametres dans le jeu de donnees. Format attendu:
Moyenne_volumique {
nom_pb NOM_DU_PROBLEME (ou chercher les champs sources)
nom_domaine DOMAINE_CIBLE (on evalue la convolution aux elements de ce domaine)
noms_champs N CHAMP1 CHAMP2 ... (noms des champs a filtrer dans le probleme)
[ nom_fichier_post NOM_SANS_EXTENSION ] (soit on donne nom_fichier et format_post,
soit on donne fichier_post)
[ format_post lata|meshtv|lml|med|... ] (par defaut lata)
[ fichier_post Format_Post_XXX { ... } ] (lecture par readOn du Format_Post_XXX)
fonction_filtre ... (format : voir Moyenne_volumique::readOn())
[ localisation ELEM|SOM ]
}.
< par defaut
Reimplemented from Interprete.
Definition at line 417 of file Moyenne_volumique.cpp.
{
  Cerr << "Starting of Moyenne_volumique::interpreter" << finl;
  Nom nom_pb, nom_dom;
  Motcles noms_champs;
  Param param(que_suis_je() + Nom("::interpreter()"));
  const int id_elem = 0;
  const int id_som = 1;
  int localisation = id_elem; //!< par defaut
  Motcle format_post("lata_v1");
  Nom nom_fichier_post;
  DERIV(Format_Post_base) fichier_post;
  param.ajouter("nom_pb", & nom_pb, Param::REQUIRED);
  param.ajouter("nom_domaine", & nom_dom, Param::REQUIRED);
  param.ajouter("noms_champs", & noms_champs, Param::REQUIRED);
  param.ajouter("fichier_post", & fichier_post);
  param.ajouter("format_post", & format_post);
  param.ajouter("nom_fichier_post", & nom_fichier_post);
// L'objet Moyenne_volumique est un interprete, mais c'est aussi un objet
// dont la seule propriete est la fonction filtre a utiliser... astuce:
// on appelle le readOn de la classe pour lire la fonction filtre.
  param.ajouter("fonction_filtre", this, Param::REQUIRED);
  param.ajouter("localisation", & localisation);
  param.dictionnaire("ELEM", id_elem);
  param.dictionnaire("SOM", id_som);
  param.lire_avec_accolades_depuis(is);
// on recupere le domaine
  const Domaine& dom = ref_cast(Domaine, objet(nom_dom));
  if (noms_champs.size() == 0)
    {
      Cerr << "Moyenne_volumique : no field to treat" << finl;
      return is;
    }
  Cerr << "Writing of the post-processing domain : " << nom_dom << finl;
  REF(Champ_base) ref_champ;
  get_champ(nom_pb, noms_champs[0], ref_champ);
  const double temps = ref_champ.valeur().temps();
  if (!fichier_post.non_nul())
    {
      if (nom_fichier_post == "??")
        {
          Cerr << "Error in Moyenne_volumique::interpreter:\n"
               << " missing NOM_FICHIER_POST or FICHIER_POST keyword" << finl;
          barrier();
          exit();
        }
      if (format_post == "lata")
        format_post = "lata_v1";
// Astuce pour permettre le cas test de non regression en sequentiel et en parallele:
// (il faut que le nom du fichier de sortie soit le nom du cas)
      if (nom_fichier_post == "NOM_DU_CAS")
        {
          Cerr << "Post filename = NOM_DU_CAS => using " << nom_du_cas() << " instead" << finl;
          nom_fichier_post = nom_du_cas();
        }
      fichier_post.typer(Motcle("FORMAT_POST_") + format_post);
      fichier_post.valeur().initialize(nom_fichier_post, 1 /* binaire */, "SIMPLE");
    }
  else
    {
      if (nom_fichier_post != "??")
        {
          Cerr << "Error in Moyenne_volumique::interpreter:\n"
               << " you cannot give NOM_FICHIER_POST and FICHIER_POST. Choose one" << finl;
          barrier();
          exit();
        }
    }
  Format_Post_base& post = fichier_post.valeur();
  post.ecrire_entete(temps, 0 /*reprise*/, 1 /* premier post */);
  post.ecrire_domaine(dom, 1 /* premier_post */);
  post.ecrire_temps(temps);
// Coordonnees des centres des elements du domaine destination
  DoubleTab coords;
  if (localisation == id_elem)
    {
      dom.zone(0).calculer_centres_gravite(coords);
// Le tableau contient aussi les elements virtuels et pas d'espace virtuel. bouh.
      coords.resize(dom.zone(0).nb_elem(), coords.dimension(1));
    }
  else
    {
      coords = dom.les_sommets();
    }
  Motcle loc("ELEM");
  if (localisation == id_som)
    loc = "SOM";
  traiter_champs(noms_champs,
                 nom_pb,
                 nom_dom,
                 coords,
                 post,
                 temps,
                 loc);
  int fin=1;
  post.finir(fin);
  return is;
}
References Param::ajouter(), Process::barrier(), Zone::calculer_centres_gravite(), Cerr, DERIV, Param::dictionnaire(), TRUSTTab< _TYPE_ >::dimension(), Format_Post_base::ecrire_domaine(), Format_Post_base::ecrire_entete(), Format_Post_base::ecrire_temps(), Process::exit(), Format_Post_base::finir(), finl, get_champ(), Domaine::les_sommets(), Param::lire_avec_accolades_depuis(), Zone::nb_elem(), Objet_U::nom_du_cas(), Interprete::objet(), Objet_U::que_suis_je(), REF, ref_cast, Param::REQUIRED, TRUSTTab< _TYPE_ >::resize(), vect_impl::size(), traiter_champs(), and Domaine::zone().
printOn()
Sortie & Moyenne_volumique::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 27 of file Moyenne_volumique.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Moyenne_volumique::readOn (Entree & is) override protected virtual
lecture de la fonction de filtrage.
{
type BOITE|CHAPEAU|QUADRA|GAUSSIENNE|PARSER
demie-largeur L
[ omega W ]
[ expression FORMULE ]
}
< Erreur interne !
Reimplemented from Objet_U.
Definition at line 39 of file Moyenne_volumique.cpp.
{
  l_ = -1;
  expression_parser_ = "??";
  int type;
  Param param(que_suis_je());
  param.ajouter("type", & type, Param::REQUIRED /* obligatoire */);
  param.dictionnaire("BOITE", BOITE);
  param.dictionnaire("CHAPEAU", CHAPEAU);
  param.dictionnaire("GAUSSIENNE", GAUSSIENNE);
  param.dictionnaire("QUADRA", QUADRA);
  param.dictionnaire("PARSER", PARSER);
  param.ajouter("demie-largeur", & box_size_, Param::REQUIRED /* obligatoire */);
  param.ajouter("omega", & l_);
  param.ajouter("expression", & expression_parser_);
  param.lire_avec_accolades_depuis(is);
  switch(type)
    {
    case BOITE:
      type_ = BOITE;
      l_ = box_size_;
      break;
    case CHAPEAU:
      type_ = CHAPEAU;
      l_ = box_size_;
      break;
    case GAUSSIENNE:
      type_ = GAUSSIENNE;
      if (l_ < 0.)
        {
          Cerr << "Error : OMEGA must be set to >= 0" << finl;
          barrier();
          exit();
        }
      break;
    case PARSER:
      type_ = PARSER;
      if (expression_parser_ == "??")
        {
          Cerr << "Error : EXPRESSION must be specified for the parser." << finl;
          barrier();
          exit();
        }
      {
        std::string s(expression_parser_);
        for (auto & c: s) c = toupper(c);
        parser_.setString(s);
        parser_.setNbVar(Objet_U::dimension);
        parser_.addVar("x");
        parser_.addVar("y");
        if (Objet_U::dimension == 3)
          parser_.addVar("z");
        parser_.parseString();
      }
      break;
    case QUADRA:
      type_ = QUADRA;
      l_ = box_size_;
      Cerr << "l_ = " << l_ << "box_size_ = " << box_size_ << finl;
      break;
    default:
      exit(); //!< Erreur interne !
    }
// Pour que l'octree trouve bien les elements qui sont pile-poil a la limite.
  box_size_ += precision_geom;
  return is;
}
References Parser::addVar(), Param::ajouter(), Process::barrier(), BOITE, box_size_, Cerr, CHAPEAU, Param::dictionnaire(), Objet_U::dimension, Process::exit(), expression_parser_, finl, GAUSSIENNE, l_, Param::lire_avec_accolades_depuis(), PARSER, parser_, Parser::parseString(), Objet_U::precision_geom, QUADRA, Objet_U::que_suis_je(), Param::REQUIRED, Parser::setNbVar(), Parser::setString(), and type_.
self_cast() [1/2]
const Moyenne_volumique & Moyenne_volumique::self_cast (const Objet_U & r) static
Definition at line 25 of file Moyenne_volumique.cpp.
self_cast() [2/2]
Moyenne_volumique & Moyenne_volumique::self_cast (Objet_U & r) static
Definition at line 25 of file Moyenne_volumique.cpp.
taille_memoire()
unsigned Moyenne_volumique::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file Moyenne_volumique.cpp.
traiter_champs()
void Moyenne_volumique::traiter_champs (const Motcles & noms_champs, const Nom & nom_pb, const Nom & nom_dom, const DoubleTab & coords, Format_Post_base & post, double temps, const Motcle & localisation) protected
fonction outil permettant de faire les calculs et d'ecrire le resultat
dans un fichier lata pour tous les champs d'un type donne de la liste noms_champs.
Methode appelee par interpreter()
type_champ=0 => traiter les champs aux elements
type_champ=1 => traiter les champs aux faces
Definition at line 272 of file Moyenne_volumique.cpp.
{
  const Domaine& dom_post = ref_cast(Domaine, objet(nom_dom));
  const int nb_champs = noms_champs.size();
  if (nb_champs == 0)
    return;
  REF(Champ_base) ref_champ;
  REF(Zone_VF) ref_zone_vf;
  int i_champ;
// ************************************
// Calcul du nombre total de composantes et de ref_zone_vf
  int nb_compo_tot = 0;
  for (i_champ = 0; i_champ < nb_champs; i_champ++)
    {
      get_champ(nom_pb, noms_champs[i_champ], ref_champ);
      const Champ_base& champ = ref_champ.valeur();
      const Zone_VF& zvf = ref_cast(Zone_VF, champ.zone_dis_base());
      if (i_champ == 0)
        {
          ref_zone_vf = zvf;
        }
      else
        {
          if (& (ref_zone_vf.valeur()) != & zvf)
            {
              Cerr << "Error in Moyenne_volumique::traiter_champs all the fields must be discretized on the same Zone." << finl;
              barrier();
              exit();
            }
        }
      const int nb_compo = champ.nb_comp();
      nb_compo_tot += nb_compo;
    }
  const Zone_VF& zone_source = ref_zone_vf.valeur();
// ************************************
// Construction d'un gros tableau contenant toutes les valeurs a traiter plus la porosite
  DoubleTab valeurs_src;
  const int nb_lignes = zone_source.nb_elem();
  valeurs_src.resize(nb_lignes, nb_compo_tot + 1);
  int count = 0;
  {
    DoubleTab tmp_val;
    IntVect liste_elems(nb_lignes);
    for (int i = 0; i < nb_lignes; i++)
      liste_elems[i] = i;
    const DoubleTab& xp = zone_source.xp();
    for (i_champ = 0; i_champ < nb_champs; i_champ++)
      {
        get_champ(nom_pb, noms_champs[i_champ], ref_champ);
        const Champ_base& champ = ref_champ.valeur();
        const int nb_compo = champ.nb_comp();
        tmp_val.reset();
        tmp_val.resize(nb_lignes, nb_compo);
        champ.valeur_aux_elems(xp, liste_elems, tmp_val);
        for (int i = 0; i < nb_lignes; i++)
          for (int j = 0; j < nb_compo; j++)
            valeurs_src(i, count+j) = tmp_val(i, j);
        count += nb_compo;
        Cout << "Field name = " << ref_champ->le_nom()
             << " Field type = " << ref_champ->que_suis_je() << finl;
      }
  }
// et une colonne de 1:
  for (int i = 0; i < nb_lignes; i++)
    valeurs_src(i, count) = 1.;
// Tableau de resultats:
  const int nb_coords = coords.dimension(0);
  DoubleTab resu(nb_coords, nb_compo_tot + 1);
// ************************************
// Calcul de tous les produits de convolution
  calculer_convolution_champ_elem(zone_source,
                                  valeurs_src,
                                  coords,
                                  resu);
  Noms nom_dir;
  nom_dir.add("_X");
  nom_dir.add("_Y");
  nom_dir.add("_Z");
  count = 0;
  for (i_champ = 0; i_champ < nb_champs; i_champ++)
    {
      get_champ(nom_pb, noms_champs[i_champ], ref_champ);
      const Champ_base& champ = ref_champ.valeur();
      const int nb_compo = champ.nb_comp();
      DoubleTab extrait(nb_coords, nb_compo);
      for (int i = 0; i < nb_coords; i++)
        for (int j = 0; j < nb_compo; j++)
          extrait(i, j) = resu(i, count + j);
      Cout << "Post writting " << champ.le_nom() << finl;
      Nom nature("scalar");
      if (champ.nature_du_champ()==vectoriel) nature="vector";
      post.ecrire_champ(dom_post,
                        champ.unites(),
                        champ.noms_compo(),
                        -1 /* ecrire toutes les composantes */, temps, temps,
                        noms_champs[i_champ], nom_dom, localisation,nature, extrait);
      count += nb_compo;
    }
// Derniere colonne (porosite)
  const int nb_compo = 1;
  DoubleTab extrait(nb_coords, nb_compo);
  for (int i = 0; i < nb_coords; i++)
    for (int j = 0; j < nb_compo; j++)
      extrait(i, j) = resu(i, count + j);
  Noms noms_compo;
  Noms unites;
  Nom nom_moyenne;
  unites.add("m3");
  noms_compo.add("porosite");
  nom_moyenne = "porosite";
  Cout << "Porosity post writing" << finl;
  post.ecrire_champ(dom_post, unites, noms_compo, -1 /* ecrire toutes les composantes */,
                    temps, temps,
                    nom_moyenne, nom_dom, localisation, "scalar",extrait);
}
References Vect_Nom::add(), Process::barrier(), calculer_convolution_champ_elem(), Cerr, Cout, TRUSTTab< _TYPE_ >::dimension(), Format_Post_base::ecrire_champ(), Process::exit(), finl, get_champ(), Field_base::le_nom(), Field_base::nature_du_champ(), Field_base::nb_comp(), Zone_dis_base::nb_elem(), Field_base::noms_compo(), Interprete::objet(), REF, ref_cast, TRUSTTab< _TYPE_ >::reset(), TRUSTTab< _TYPE_ >::resize(), vect_impl::size(), Field_base::unites(), Champ_base::valeur_aux_elems(), vectoriel, Zone_VF::xp(), and Champ_base::zone_dis_base().
Referenced by interpreter().
Member Data Documentation
box_size_
double Moyenne_volumique::box_size_ protected
Definition at line 65 of file Moyenne_volumique.h.
Referenced by box_size(), and readOn().
expression_parser_
Nom Moyenne_volumique::expression_parser_ protected
Definition at line 66 of file Moyenne_volumique.h.
Referenced by readOn().
info_obj
const Type_info Moyenne_volumique::info_obj static
Definition at line 39 of file Moyenne_volumique.h.
l_
double Moyenne_volumique::l_ protected
Definition at line 63 of file Moyenne_volumique.h.
Referenced by eval_filtre(), and readOn().
parser_
Parser Moyenne_volumique::parser_ mutable protected
Definition at line 67 of file Moyenne_volumique.h.
Referenced by eval_filtre(), and readOn().
type_
Type Moyenne_volumique::type_ protected
Definition at line 61 of file Moyenne_volumique.h.
Referenced by eval_filtre(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Statistiques_temps/Moyenne_volumique.h
src/Kernel/Statistiques_temps/Moyenne_volumique.cpp