TRUST: Noms Class Reference
Noms Class Reference
Un tableau de chaine de caracteres (VECT(Nom))
#include <Noms.h>
Public Member Functions
Noms ()
~Noms ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Noms (int)
Constructeur
Construit un tableau de i noms.
int rang (const char *const ch) const
int contient_ (const char *const ch) const
int search (const Nom &t) const
int search_without_checking_Motcle (const Nom &t) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Noms & self_cast (Objet_U &)
static const Noms & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture d'un tableau de noms sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'un tableau de nomss sur un flot d'entree.
Detailed Description
Un tableau de chaine de caracteres (VECT(Nom))
Definition at line 36 of file Noms.h.
Constructor & Destructor Documentation
Noms::Noms ()
Definition at line 25 of file Noms.cpp.
Noms::~Noms ()
Definition at line 25 of file Noms.cpp.
Noms::Noms (int i) [inline]
Constructeur
Construit un tableau de i noms.
Definition at line 63 of file Noms.h.
: VECT(Nom)(i) {}
Member Function Documentation
int Noms::contient_ (const char *const ch) const
Definition at line 88 of file Noms.cpp.
References rang().
Referenced by Partitionneur_base::calculer_graphe_connexions_periodiques(), Partitionneur_Sous_Zones::construire_partition(), Partitionneur_base::corriger_sommets_bord(), Champ_Fonc_MED::creer(), Probleme_base::discretiser(), and Postraitement::init().
{
  return (rang(ch)!=-1);
}
Objet_U * Noms::cree_instance () [static]
Reimplemented from Vect_Nom.
Definition at line 25 of file Noms.cpp.
int Noms::duplique () const [virtual]
Reimplemented from Vect_Nom.
Definition at line 25 of file Noms.cpp.
const Type_info * Noms::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Vect_Nom.
Definition at line 25 of file Noms.cpp.
const Type_info * Noms::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Vect_Nom.
Definition at line 25 of file Noms.cpp.
Sortie & Noms::printOn (Sortie & s) const [protected, virtual]
Ecriture d'un tableau de noms sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Vect_Nom.
Definition at line 42 of file Noms.cpp.
References VECT.
{
  return VECT(Nom)::printOn(s);
}
int Noms::rang (const char *const ch) const
Definition at line 93 of file Noms.cpp.
References vect_impl::size().
Referenced by contient_(), Zone_Cl_EF::imposer_symetrie_partiellement(), Create_domain_from_sous_zone::interpreter_(), Postraitement::readOn(), and search().
{
// Optimization to avoid creating an object Nom:
  assert(size()>=0);
  int i=size();
  while(i--)
    if (operator()(i).getString()==ch)
      {
        return i;
      }
  return -1;
}
Entree & Noms::readOn (Entree & s) [protected, virtual]
Lecture d'un tableau de nomss sur un flot d'entree.
Returns:
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Vect_Nom.
Definition at line 62 of file Noms.cpp.
References VECT.
{
  return VECT(Nom)::readOn(s);
}
int Noms::search (const Nom & t) const
Definition at line 67 of file Noms.cpp.
References Nom::getString(), and rang().
Referenced by Interprete_bloc::ajouter(), create_listb_from_domaine2(), create_listb_from_xyz(), create_listb_geom(), create_listb_naif(), Interprete_bloc::objet_local(), and Interprete_bloc::objet_local_existant().
{
// Use rang() now
  return rang(t.getString().c_str());
}
int Noms::search_without_checking_Motcle (const Nom & t) const
Definition at line 73 of file Noms.cpp.
References Nom::getString(), Vect_Nom::operator()(), and vect_impl::size().
{
  assert(size()>=0);
  int i=size();
  while(i--)
    {
      const Nom& unnom=operator()(i);
      if (unnom.getString().compare(t)==0)
        {
          return i;
        }
    }
  return -1;
}
const Noms & Noms::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Vect_Nom.
Definition at line 25 of file Noms.cpp.
Noms & Noms::self_cast (Objet_U & r) [static]
Reimplemented from Vect_Nom.
Definition at line 25 of file Noms.cpp.
unsigned Noms::taille_memoire () const [virtual]
Reimplemented from Vect_Nom.
Definition at line 25 of file Noms.cpp.
Member Data Documentation
const Type_info Noms::info_obj [static]
Reimplemented from Vect_Nom.
Definition at line 38 of file Noms.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Noms.h
src/Kernel/Utilitaires/Noms.cpp