TRUST: Entree_fluide_temperature_imposee Class Reference
Entree_fluide_temperature_imposee Class Reference
classe Entree_fluide_temperature_imposee
Cas particulier de la classe Dirichlet_entree_fluide
pour la temperature imposee: impose la temperature d'entree du fluide
dans une equation de type Convection_Diffusion_Temperature
#include <Entree_fluide_temperature_imposee.h>
Public Member Functions
Entree_fluide_temperature_imposee ()
~Entree_fluide_temperature_imposee ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int compatible_avec_eqn (const Equation_base &) const
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Entree_fluide_temperature_imposee sont compatibles
avec une equation dont le domaine est la Thermique
ou bien indetermine.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Entree_fluide_temperature_imposee & self_cast (Objet_U &)
static const
Entree_fluide_temperature_imposee & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a: Cond_lim_base::readOn(Entree&)
Detailed Description
classe Entree_fluide_temperature_imposee
Cas particulier de la classe Dirichlet_entree_fluide
pour la temperature imposee: impose la temperature d'entree du fluide
dans une equation de type Convection_Diffusion_Temperature
Definition at line 40 of file Entree_fluide_temperature_imposee.h.
Constructor & Destructor Documentation
Entree_fluide_temperature_imposee::Entree_fluide_temperature_imposee ()
Definition at line 27 of file Entree_fluide_temperature_imposee.cpp.
Entree_fluide_temperature_imposee::~Entree_fluide_temperature_imposee ()
Definition at line 27 of file Entree_fluide_temperature_imposee.cpp.
Member Function Documentation
int Entree_fluide_temperature_imposee::compatible_avec_eqn (const Equation_base & eqn) const [virtual]
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Entree_fluide_temperature_imposee sont compatibles
avec une equation dont le domaine est la Thermique
ou bien indetermine.
Returns:
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Implements Cond_lim_base.
Reimplemented in Entree_fluide_temperature_imposee_H.
Definition at line 88 of file Entree_fluide_temperature_imposee.cpp.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Thermique="Thermique";
  Motcle indetermine="indetermine";
  if ( (dom_app==Thermique) || (dom_app==indetermine) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
Objet_U * Entree_fluide_temperature_imposee::cree_instance () [static]
Reimplemented in Entree_fluide_temperature_imposee_H.
Definition at line 27 of file Entree_fluide_temperature_imposee.cpp.
int Entree_fluide_temperature_imposee::duplique () const [virtual]
Implements Dirichlet_entree_fluide.
Reimplemented in Entree_fluide_temperature_imposee_H.
Definition at line 27 of file Entree_fluide_temperature_imposee.cpp.
const Type_info * Entree_fluide_temperature_imposee::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Dirichlet_entree_fluide.
Reimplemented in Entree_fluide_temperature_imposee_H.
Definition at line 27 of file Entree_fluide_temperature_imposee.cpp.
const Type_info * Entree_fluide_temperature_imposee::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Dirichlet_entree_fluide.
Reimplemented in Entree_fluide_temperature_imposee_H.
Definition at line 27 of file Entree_fluide_temperature_imposee.cpp.
Sortie & Entree_fluide_temperature_imposee::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Dirichlet_entree_fluide.
Reimplemented in Entree_fluide_temperature_imposee_H.
Definition at line 44 of file Entree_fluide_temperature_imposee.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Entree_fluide_temperature_imposee::readOn (Entree & s) [protected, virtual]
Simple appel a: Cond_lim_base::readOn(Entree&)
Returns:
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Dirichlet_entree_fluide.
Reimplemented in Entree_fluide_temperature_imposee_H.
Definition at line 63 of file Entree_fluide_temperature_imposee.cpp.
{
  return Cond_lim_base::readOn(s);
}
const Entree_fluide_temperature_imposee & Entree_fluide_temperature_imposee::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Dirichlet_entree_fluide.
Reimplemented in Entree_fluide_temperature_imposee_H.
Definition at line 27 of file Entree_fluide_temperature_imposee.cpp.
Entree_fluide_temperature_imposee & Entree_fluide_temperature_imposee::self_cast (Objet_U & r) [static]
Reimplemented from Dirichlet_entree_fluide.
Reimplemented in Entree_fluide_temperature_imposee_H.
Definition at line 27 of file Entree_fluide_temperature_imposee.cpp.
unsigned Entree_fluide_temperature_imposee::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Entree_fluide_temperature_imposee_H.
Definition at line 27 of file Entree_fluide_temperature_imposee.cpp.
Member Data Documentation
const Type_info Entree_fluide_temperature_imposee::info_obj [static]
Reimplemented from Dirichlet_entree_fluide.
Reimplemented in Entree_fluide_temperature_imposee_H.
Definition at line 43 of file Entree_fluide_temperature_imposee.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Cond_Lim/Entree_fluide_temperature_imposee.h
src/ThHyd/Incompressible/Cond_Lim/Entree_fluide_temperature_imposee.cpp