TRUST: Champ_front_fonc_gradient_VDF Class Reference
Champ_front_fonc_gradient_VDF Class Reference
class Champ_front_fonc_gradient_VDF
Classe derivee de Champ_front_base
#include <Champ_front_fonc_gradient_VDF.h>
Public Member Functions
Champ_front_fonc_gradient_VDF ()
~Champ_front_fonc_gradient_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double) override
Mise a jour du temps.
Public Member Functions inherited from Champ_front_fonc_gradient
Champ_front_fonc_gradient ()
~Champ_front_fonc_gradient ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_ch_inc_base (const Champ_Inc_base &)
const Cond_lim_base & condition_limite (const Nom &)
Public Member Functions inherited from Champ_front_tangentiel
Champ_front_tangentiel ()
~Champ_front_tangentiel ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base & affecter_ (const Champ_front_base &ch) override
Pas code !!
Public Member Functions inherited from Ch_front_var_instationnaire_dep
Ch_front_var_instationnaire_dep ()
~Ch_front_var_instationnaire_dep ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Champ_front_base & affecter_ (const Champ_front_base &ch) override
Public Member Functions inherited from Champ_front_var_instationnaire
Champ_front_var_instationnaire ()
~Champ_front_var_instationnaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialise le temps courant et Gpoint.
DoubleTab & Gpoint ()
const DoubleTab & Gpoint () const
void Gpoint (double t1, double t2)
DoubleTab & valeurs_au_temps (double temps) override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
const DoubleTab & valeurs_au_temps (double temps) const override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
int avancer (double temps) override
Avance jusqu'au temps desire.
Sinon, sort en erreur.
int reculer (double temps) override
Recule jusqu'au temps desire.
Sinon, sort en erreur.
virtual double valeur_au_temps_et_au_point (double temps, int som, double x, double y, double z, int comp) const
virtual int valeur_au_temps_et_au_point_disponible () const
Public Member Functions inherited from Champ_front_var
Champ_front_var ()
~Champ_front_var () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Public Member Functions inherited from Champ_front_base
~Champ_front_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base ()
virtual void completer ()
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe une frontiere discretisee au champ.
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
virtual DoubleTab & valeurs_au_temps (double temps)=0
virtual const DoubleTab & valeurs_au_temps (double temps) const =0
const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee associee au champ.
(version const)
Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee associee au champ.
const Zone_dis_base & zone_dis () const
virtual Champ_front_base & affecter_ (const Champ_front_base &ch)=0
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
virtual void calculer_coeffs_echange (double temps)
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
virtual void valeurs_face (int, DoubleVect &) const
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
virtual void verifier (const Cond_lim_base &la_cl) const
double get_temps_defaut () const
void set_temps_defaut (double temps)
virtual void changer_temps_futur (double temps, int i)
virtual int avancer (double temps)
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe
en parametre.
virtual int reculer (double temps)
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe
en parametre.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_front_fonc_gradient_VDF & self_cast (Objet_U &)
static const Champ_front_fonc_gradient_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_fonc_gradient
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_front_fonc_gradient & self_cast (Objet_U &)
static const Champ_front_fonc_gradient & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_tangentiel
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_front_tangentiel & self_cast (Objet_U &)
static const Champ_front_tangentiel & self_cast (const Objet_U &)
Static Public Member Functions inherited from Ch_front_var_instationnaire_dep
static Objet_U * cree_instance ()
static const Type_info * info ()
static Ch_front_var_instationnaire_dep & self_cast (Objet_U &)
static const Ch_front_var_instationnaire_dep & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var_instationnaire
static const Type_info * info ()
static Champ_front_var_instationnaire & self_cast (Objet_U &)
static const Champ_front_var_instationnaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var
static const Type_info * info ()
static Champ_front_var & self_cast (Objet_U &)
static const Champ_front_var & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_base
static const Type_info * info ()
static Champ_front_base & self_cast (Objet_U &)
static const Champ_front_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_fonc_gradient
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_tangentiel
static const Type_info info_obj
Static Public Attributes inherited from Ch_front_var_instationnaire_dep
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var_instationnaire
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void associer_ch_inc_base (const Champ_Inc_base &)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Champ_front_fonc_gradient
Ref_Champ_Inc_base inconnue
Protected Attributes inherited from Champ_front_tangentiel
double vit_tang
Protected Attributes inherited from Champ_front_var_instationnaire
DoubleTab Gpoint_
Taux d'accroissement du champ.
Protected Attributes inherited from Champ_front_base
double temps_defaut
Le temps pris par defaut quand le parametre n'est pas specifie. Ce sera en particulier celui utilise par les operateurs et les solveurs.
Ref_Frontiere_dis_base la_frontiere_dis
Roue_ptr les_valeurs
Les valeurs du champ.
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
class Champ_front_fonc_gradient_VDF
Classe derivee de Champ_front_base
Definition at line 30 of file Champ_front_fonc_gradient_VDF.h.
Constructor & Destructor Documentation
Champ_front_fonc_gradient_VDF()
Champ_front_fonc_gradient_VDF::Champ_front_fonc_gradient_VDF ()
Definition at line 22 of file Champ_front_fonc_gradient_VDF.cpp.
~Champ_front_fonc_gradient_VDF()
Champ_front_fonc_gradient_VDF::~Champ_front_fonc_gradient_VDF ()
Definition at line 22 of file Champ_front_fonc_gradient_VDF.cpp.
Member Function Documentation
associer_ch_inc_base()
void Champ_front_fonc_gradient_VDF::associer_ch_inc_base (const Champ_Inc_base &) protected
cree_instance()
Objet_U * Champ_front_fonc_gradient_VDF::cree_instance () static
Definition at line 22 of file Champ_front_fonc_gradient_VDF.cpp.
duplique()
int Champ_front_fonc_gradient_VDF::duplique () const override virtual
Reimplemented from Champ_front_fonc_gradient.
Definition at line 22 of file Champ_front_fonc_gradient_VDF.cpp.
get_info()
const Type_info * Champ_front_fonc_gradient_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_fonc_gradient.
Definition at line 22 of file Champ_front_fonc_gradient_VDF.cpp.
info()
const Type_info * Champ_front_fonc_gradient_VDF::info () static
Definition at line 22 of file Champ_front_fonc_gradient_VDF.cpp.
mettre_a_jour()
void Champ_front_fonc_gradient_VDF::mettre_a_jour (double temps) override virtual
Mise a jour du temps.
Reimplemented from Champ_front_base.
Definition at line 39 of file Champ_front_fonc_gradient_VDF.cpp.
{
// Cerr << "Champ_front_fonc_gradient_VDF::mettre_a_jour" << finl;
  const Front_VF& la_front=ref_cast(Front_VF, frontiere_dis());
  int nb_faces = la_front.nb_faces();
  int ndeb = la_front.num_premiere_face();
  DoubleTab& tab=valeurs_au_temps(temps);
  const Zone_VDF& la_zone_VDF = ref_cast(Zone_VDF,zone_dis());
  const IntVect& orientation = la_zone_VDF.orientation();
// On recupere la CL et les champs associes
  const Paroi_Knudsen_non_negligeable& la_condition_limite=ref_cast(Paroi_Knudsen_non_negligeable,condition_limite(la_front.le_nom()));
  const DoubleTab& la_inconnue_paroi_=la_condition_limite.vitesse_paroi();
  const DoubleTab& k_=la_condition_limite.k();
  const DoubleVect& la_inconnue=inconnue->valeurs();
  int elem,iro,ori,i,j;
// double inconnue_moyenne1,inconnue_moyenne2;
  DoubleTab la_inconnue_paroi(nb_faces,dimension);
  DoubleVect k(nb_faces);
  DoubleVect inconnue_moyenne(dimension-1);
  if (la_inconnue_paroi_.dimension(0)==1)
    for (i=0; i<nb_faces; i++)
      for (j=0; j<dimension; j++)
        la_inconnue_paroi(i,j)=la_inconnue_paroi_(0,j);
  else
    for (i=0; i<nb_faces; i++)
      for (j=0; j<dimension; j++)
        la_inconnue_paroi(i,j)=la_inconnue_paroi_(i,j);
  if (k_.dimension(0)==1)
    for (i=0; i<nb_faces; i++)
      k(i)=k_(0,0);
  else
    for (i=0; i<nb_faces; i++)
      k(i)=k_(i,0);
  for (i=0; i<nb_faces; i++)
    {
      int num_face=ndeb+i;
      double k_sur_e;
      if (axi)
        k_sur_e=k(i)/la_zone_VDF.dist_norm_bord_axi(num_face);
      else
        k_sur_e=k(i)/la_zone_VDF.dist_norm_bord(num_face);
      elem = la_zone_VDF.face_voisins(num_face,0);
      if ( elem == -1 )
        elem = la_zone_VDF.face_voisins(num_face,1);
// Calcul de la inconnue a la paroi en fonction
// de l'orientation
      ori = orientation(num_face);
      tab(i,ori) = la_inconnue_paroi(i,ori);
      if (dimension==2)
        {
          moy_2D_vit(la_inconnue,elem,ori,la_zone_VDF,inconnue_moyenne[0]);
          iro=1-ori;
          tab(i,iro)=(la_inconnue_paroi(i,iro)+k_sur_e*inconnue_moyenne[0])/(1+k_sur_e);
        }
      else if (dimension==3)
        {
          moy_3D_vit(la_inconnue,elem,ori,la_zone_VDF,inconnue_moyenne[0],inconnue_moyenne[1]);
          if (ori==0)
            {
              iro=1;
              tab(i,iro)=(la_inconnue_paroi(i,iro)+k_sur_e*inconnue_moyenne[0])/(1+k_sur_e);
              iro=2;
              tab(i,iro)=(la_inconnue_paroi(i,iro)+k_sur_e*inconnue_moyenne[1])/(1+k_sur_e);
            }
          else if (ori==1)
            {
              iro=0;
              tab(i,iro)=(la_inconnue_paroi(i,iro)+k_sur_e*inconnue_moyenne[0])/(1+k_sur_e);
              iro=2;
              tab(i,iro)=(la_inconnue_paroi(i,iro)+k_sur_e*inconnue_moyenne[1])/(1+k_sur_e);
            }
          else if (ori==2)
            {
              iro=0;
              tab(i,iro)=(la_inconnue_paroi(i,iro)+k_sur_e*inconnue_moyenne[0])/(1+k_sur_e);
              iro=1;
              tab(i,iro)=(la_inconnue_paroi(i,iro)+k_sur_e*inconnue_moyenne[1])/(1+k_sur_e);
            }
        }
    }
  tab.echange_espace_virtuel();
}
References Objet_U::axi, Champ_front_fonc_gradient::condition_limite(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VDF::dist_norm_bord(), Zone_VDF::dist_norm_bord_axi(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::face_voisins(), Champ_front_base::frontiere_dis(), Champ_front_fonc_gradient::inconnue, Paroi_Knudsen_non_negligeable::k(), Frontiere_dis_base::le_nom(), moy_2D_vit(), moy_3D_vit(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), ref_cast, Champ_Inc_base::valeurs(), Champ_front_var_instationnaire::valeurs_au_temps(), Paroi_Knudsen_non_negligeable::vitesse_paroi(), and Champ_front_base::zone_dis().
printOn()
Sortie & Champ_front_fonc_gradient_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_fonc_gradient.
Definition at line 24 of file Champ_front_fonc_gradient_VDF.cpp.
{
  return Champ_front_fonc_gradient::printOn(os);
}
References Champ_front_fonc_gradient::printOn().
readOn()
Entree & Champ_front_fonc_gradient_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_fonc_gradient.
Definition at line 30 of file Champ_front_fonc_gradient_VDF.cpp.
{
  fixer_nb_comp(dimension);
  return s;
}
References Objet_U::dimension, and Field_base::fixer_nb_comp().
self_cast() [1/2]
const Champ_front_fonc_gradient_VDF & Champ_front_fonc_gradient_VDF::self_cast (const Objet_U & r) static
Definition at line 22 of file Champ_front_fonc_gradient_VDF.cpp.
self_cast() [2/2]
Champ_front_fonc_gradient_VDF & Champ_front_fonc_gradient_VDF::self_cast (Objet_U & r) static
Definition at line 22 of file Champ_front_fonc_gradient_VDF.cpp.
taille_memoire()
unsigned Champ_front_fonc_gradient_VDF::taille_memoire () const override virtual
Reimplemented from Champ_front_fonc_gradient.
Definition at line 22 of file Champ_front_fonc_gradient_VDF.cpp.
Member Data Documentation
info_obj
const Type_info Champ_front_fonc_gradient_VDF::info_obj static
Definition at line 32 of file Champ_front_fonc_gradient_VDF.h.
The documentation for this class was generated from the following files:
src/VDF/Champs/Champ_front_fonc_gradient_VDF.h
src/VDF/Champs/Champ_front_fonc_gradient_VDF.cpp