TRUST: Motcles Class Reference
Motcles Class Reference
Un tableau d'objets de la classe Motcle.
#include <Motcle.h>
Public Member Functions
Motcles ()
~Motcles ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Motcles (int)
Constructeur
Cree un tableau de i elements.
int rang (const char *const ch) const
int contient_ (const char *const ch) const
int search (const Motcle &t) const
Public Member Functions inherited from Vect_Motcle
~Vect_Motcle ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Vect_Motcle ()
Vect_Motcle (int)
const Motcle & operator[] (int) const
const Motcle & operator() (int i) const
Motcle & operator[] (int)
Motcle & operator() (int i)
Vect_Motcle (const Vect_Motcle &)
Vect_Motcle & operator= (const Vect_Motcle &)
Motcle & add (const Motcle &titi)
Motcle & add ()
void add (const Vect_Motcle &)
Entree & lit (Entree &)
Public Member Functions inherited from vect_impl
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
vect_impl ()
int size () const
void build_vect_impl (int)
const Objet_U & operator[] (int) const
Objet_U & operator[] (int)
vect_impl (const vect_impl &)
~vect_impl () override
vect_impl & operator= (const vect_impl &)
void dimensionner (int)
void dimensionner_force (int)
void reset ()
vect_impl & add (const Objet_U &)
vect_impl & add (const vect_impl &)
Entree & lit (Entree &)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Motcles & self_cast (Objet_U &)
static const Motcles & self_cast (const Objet_U &)
Static Public Member Functions inherited from Vect_Motcle
static Objet_U * cree_instance ()
static const Type_info * info ()
static Vect_Motcle & self_cast (Objet_U &)
static const Vect_Motcle & self_cast (const Objet_U &)
Static Public Member Functions inherited from vect_impl
static Objet_U * cree_instance ()
static const Type_info * info ()
static vect_impl & self_cast (Objet_U &)
static const vect_impl & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Vect_Motcle
static const Type_info info_obj
Static Public Attributes inherited from vect_impl
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture d'un tableau Motcles sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un tableau Motcles sur un flot d'entree.
Protected Member Functions inherited from Vect_Motcle
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Objet_U * cree_une_instance () const override
methhode surcharge par les classes filles pour fournir la bonne
instance aux constructeurs au readOn....
Protected Member Functions inherited from vect_impl
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual Objet_U * cree_une_instance () const
methhode surcharge par les classes filles pour fournir la bonne
instance aux constructeurs au readOn....
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from vect_impl
int sz
DerObjU * data
Detailed Description
Un tableau d'objets de la classe Motcle.
Definition at line 70 of file Motcle.h.
Constructor & Destructor Documentation
Motcles() [1/2]
Motcles::Motcles ()
Definition at line 21 of file Motcle.cpp.
~Motcles()
Motcles::~Motcles ()
Definition at line 21 of file Motcle.cpp.
Motcles() [2/2]
Motcles::Motcles (int i)
Constructeur
Cree un tableau de i elements.
Definition at line 273 of file Motcle.cpp.
                     :
  VECT(Motcle)(i)
{
}
Member Function Documentation
contient_()
int Motcles::contient_ (const char *const ch) const
Definition at line 478 of file Motcle.cpp.
{
  return (rang(ch)!=-1);
}
References rang().
Referenced by Sonde::completer(), Postraitement::lire_champs_a_postraiter(), Sonde::readOn(), and Postraitement::verifie_nom_et_sources().
cree_instance()
Objet_U * Motcles::cree_instance () static
Definition at line 21 of file Motcle.cpp.
duplique()
int Motcles::duplique () const override virtual
Reimplemented from Vect_Motcle.
Definition at line 21 of file Motcle.cpp.
get_info()
const Type_info * Motcles::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Vect_Motcle.
Definition at line 21 of file Motcle.cpp.
info()
const Type_info * Motcles::info () static
Definition at line 21 of file Motcle.cpp.
printOn()
Sortie & Motcles::printOn (Sortie & s) const override protected virtual
Ecriture d'un tableau Motcles sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Vect_Motcle.
Definition at line 59 of file Motcle.cpp.
{
  return VECT(Motcle)::printOn(s);
}
References printOn(), and VECT.
Referenced by printOn().
rang()
int Motcles::rang (const char *const ch) const
Definition at line 483 of file Motcle.cpp.
{
  Nom nom(ch);
  assert(size()>=0);
  int i=size();
  while(i--)
    if (operator()(i)==nom)
      {
        return i;
      }
  return -1;
}
References vect_impl::size().
Referenced by contient_(), Op_Conv_EF_Stab_PolyMAC_Elem::creer_champ(), Op_Diff_Turbulent_PolyMAC_P0_Face::creer_champ(), QDM_Multiphase::creer_champ(), Navier_Stokes_std::lire_cond_init(), Navier_Stokes_std::lire_motcle_non_standard(), and Debog_Pb::test_ignore_msg().
readOn()
Entree & Motcles::readOn (Entree & s) override protected virtual
Lecture d'un tableau Motcles sur un flot d'entree.
Returns
Entree&
Signification: le flux d'entree modifie
Contraintes:
Reimplemented from Vect_Motcle.
Definition at line 222 of file Motcle.cpp.
{
  return VECT(Motcle)::readOn(s);
}
References readOn(), and VECT.
Referenced by readOn().
search()
int Motcles::search (const Motcle & t) const
Definition at line 466 of file Motcle.cpp.
{
  assert(size()>=0);
  int i=size();
  while(i--)
    if (operator()(i)==t)
      {
        return i;
      }
  return -1;
}
References vect_impl::size().
Referenced by Objet_a_lire::add_dict(), check_internal_diagonal(), check_positive_volumes(), choose_internal_diagonal(), composante(), Champ_Generique_base::composante(), compute_cell_qualities(), Champ_Generique_Predefini::construit_expression(), Solv_Petsc::create_solver(), EF_discretisation::discretiser_champ(), VEFPreP1B::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ_fonc_don(), VEFPreP1B::discretiser_champ_fonc_don(), PolyMAC_discretisation::discretiser_champ_fonc_don(), VEF_discretisation::discretiser_champ_fonc_don(), Discr_inst::discretiser_champ_fonc_don(), VDF_discretisation::discretiser_champ_fonc_don(), ensure_positive_volumes(), Champ_Gen_de_Champs_Gen::get_property(), Champ_Generique_Correlation::get_property(), Champ_Generique_Divergence::get_property(), Champ_Generique_Ecart_Type::get_property(), Champ_Generique_Extraction::get_property(), Champ_Generique_Gradient::get_property(), Champ_Generique_Interpolation::get_property(), Champ_Generique_Morceau_Equation::get_property(), Champ_Generique_Moyenne::get_property(), Champ_Generique_Predefini::get_property(), Champ_Generique_refChamp::get_property(), Champ_Generique_Transformation::get_property(), Champ_Post_Operateur_Eqn::get_property(), Champ_Generique_Tparoi_VEF::get_property(), Piso::lire(), Simple::lire(), Traitement_particulier_NS_Pression_VEF::lire(), Traitement_particulier_NS_canal::lire(), Traitement_particulier_NS_chmoy_faceperio::lire(), Traitement_particulier_NS_EC::lire(), Traitement_particulier_NS_Profils::lire(), Traitement_particulier_NS_temperature::lire(), Traitement_particulier_NS_THI::lire(), Traitement_particulier_NS_THI_new::lire(), Traitement_particulier_Solide_canal::lire(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Brech_VEF::lire(), Terme_Source_Acceleration::lire_data(), Perte_Charge_Reguliere::lire_donnees(), Perte_Charge_Singuliere::lire_donnees(), Terme_Boussinesq_base::lire_donnees(), Terme_Source_Canal_perio::lire_donnees(), Champ_front_recyclage::lire_info_moyenne_imposee(), Champ_front_recyclage::lire_info_moyenne_recyclee(), Schema_Temps_base::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), Fluide_Weakly_Compressible::lire_motcle_non_standard(), Postraitements::lire_postraitements(), Objet_a_lire::read(), Sutherland::readOn(), Champ_front_bruite::readOn(), champ_init_canal_sinal::readOn(), Sonde::readOn(), Sonde_Int::readOn(), Pave::readOn(), Sous_Zone::readOn(), PrecondA::readOn(), Solv_Cholesky::readOn(), Solv_GCP_NS::readOn(), Solv_Gen::readOn(), Solv_Gmres::readOn(), Solveur_Lineaire_Std::readOn(), Champ_front_recyclage::readOn(), Op_Diff_VEFP1NCP1B_Face::readOn(), Perte_Charge_Anisotrope_PolyMAC_Face::readOn(), Perte_Charge_Circulaire_PolyMAC_Face::readOn(), Perte_Charge_Directionnelle_PolyMAC_Face::readOn(), Perte_Charge_Isotrope_PolyMAC_Face::readOn(), Loi_Etat::readOn(), Loi_Etat_rhoT_GR_QC::readOn(), Champ_front_synt::readOn(), Entree_fluide_T_h_imposee::readOn(), Neumann_sortie_libre::readOn(), Paroi_Knudsen_non_negligeable::readOn(), Sortie_libre_Text_H_ext::readOn(), Echange_impose_base::readOn(), Source_Neutronique::readOn(), Echange_contact_Correlation_VDF::readOn(), Source_Darcy_VDF_Face::readOn(), Source_Forchheimer_VDF_Face::readOn(), Terme_Source_Canal_RANS_LES_VDF_Elem::readOn(), Terme_Source_Canal_RANS_LES_VDF_Face::readOn(), Echange_contact_Correlation_VEF::readOn(), Op_Conv_EF_VEF_P1NC_Stab::readOn(), Op_Conv_Muscl3_VEF_Face::readOn(), Op_Diff_VEF_Face_Stab::readOn(), Op_Dift_Stab_VEF_Face::readOn(), Perte_Charge_Anisotrope_VEF_P1NC::readOn(), Perte_Charge_Circulaire_VEF_P1NC::readOn(), Perte_Charge_Directionnelle_VEF_P1NC::readOn(), Perte_Charge_Isotrope_VEF_P1NC::readOn(), Source_Darcy_VEF_Face::readOn(), Source_Forchheimer_VEF_Face::readOn(), Terme_Source_Canal_RANS_LES_VEF_Face::readOn(), Terme_Source_Qdm_lambdaup_VEF_Face::readOn(), Terme_Source_Rappel_T_VEF_Face::readOn(), Champ_Generique_Interpolation::set_localisation(), Champ_Generique_Interpolation::set_methode(), Option_VDF::test_mot(), Faces::type(), type_elem(), verifie(), Champ_Generique_Transformation::verifier_coherence_donnees(), and Champ_Generique_Transformation::verifier_localisation().
self_cast() [1/2]
const Motcles & Motcles::self_cast (const Objet_U & r) static
Definition at line 21 of file Motcle.cpp.
self_cast() [2/2]
Motcles & Motcles::self_cast (Objet_U & r) static
Definition at line 21 of file Motcle.cpp.
taille_memoire()
unsigned Motcles::taille_memoire () const override virtual
Reimplemented from Vect_Motcle.
Definition at line 21 of file Motcle.cpp.
Member Data Documentation
info_obj
const Type_info Motcles::info_obj static
Definition at line 72 of file Motcle.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Motcle.h
src/Kernel/Utilitaires/Motcle.cpp