TRUST: Champ_Q4_implementation Class Reference
Champ_Q4_implementation Class Reference
#include <Champ_Q4_implementation.h>
Public Member Functions
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const override
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
int imprime_Q4 (Sortie &, int) const
Public Member Functions inherited from Champ_implementation
virtual ~Champ_implementation ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const =0
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const =0
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Additional Inherited Members
Protected Member Functions inherited from Champ_implementation
virtual const Champ_base & le_champ () const =0
virtual Champ_base & le_champ ()=0
const Zone & zone () const
virtual const Zone_dis_base & zone_dis_base () const
Detailed Description
Definition at line 22 of file Champ_Q4_implementation.h.
Member Function Documentation
imprime_Q4()
int Champ_Q4_implementation::imprime_Q4 (Sortie & os, int ncomp) const
Definition at line 242 of file Champ_Q4_implementation.cpp.
{
  const Champ_base& cha=le_champ();
  int nb_compo_=cha.nb_comp();
  const Zone& la_zone=zone();
  int nb_som_tot = la_zone.nb_som_tot();
  const DoubleTab& val = cha.valeurs();
  int som;
// On recalcule les centres de gravite :
  const DoubleTab pos_som = la_zone.domaine().coord_sommets();
  os << nb_som_tot << finl;
  for (som=0; som<nb_som_tot; som++)
    {
      if (Objet_U::dimension==3)
        os << pos_som(som,0) << " " << pos_som(som,1) << " " << pos_som(som,2) << " " ;
      if (Objet_U::dimension==2)
        os << pos_som(som,0) << " " << pos_som(som,1) << " " ;
      if (nb_compo_ == 1)
        os << val(som) << finl;
      else
        os << val(som,ncomp) << finl;
    }
  os << finl;
  Cout << "Champ_Q4_implementation::imprime_Q4 END >>>>>>>>>> " << finl;
  return 1;
}
References Domaine::coord_sommets(), Cout, Objet_U::dimension, Zone::domaine(), finl, Champ_implementation::le_champ(), Field_base::nb_comp(), Zone::nb_som_tot(), Champ_Proto::valeurs(), and Champ_implementation::zone().
remplir_coord_noeuds()
DoubleTab & Champ_Q4_implementation::remplir_coord_noeuds (DoubleTab & positions) const override virtual
Implements Champ_implementation.
Definition at line 222 of file Champ_Q4_implementation.cpp.
{
  const DoubleTab& coordsom = zone().domaine().coord_sommets();
  positions = coordsom;
  return positions;
}
References Domaine::coord_sommets(), Zone::domaine(), and Champ_implementation::zone().
remplir_coord_noeuds_et_polys()
int Champ_Q4_implementation::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const override virtual
Implements Champ_implementation.
Definition at line 229 of file Champ_Q4_implementation.cpp.
{
  Cerr<<"Champ_Q4_implementation::remplir_coord_noeuds_et_polys not implemented"<<finl;
  assert(0);
  int nb_elem=zone().nb_elem();
  polys.resize(nb_elem);
  for(int i=0; i<nb_elem; i++)
    polys(i)=i;
  return 1;
}
References Cerr, finl, Zone::nb_elem(), TRUSTVect< _TYPE_ >::resize(), and Champ_implementation::zone().
valeur_a_elem()
DoubleVect & Champ_Q4_implementation::valeur_a_elem (const DoubleVect & position, DoubleVect & val, int le_poly) const override virtual
Implements Champ_implementation.
Definition at line 20 of file Champ_Q4_implementation.cpp.
{
  val = 0.;
  const Champ_base& cha=le_champ();
  const DoubleTab& ch = cha.valeurs();
  int nb_compo_=cha.nb_comp();
  int j,ncomp, num_som,nb_som_elem = zone().nb_som_elem();
  if (nb_compo_ == 1)
    {
      for (j=0 ; j<nb_som_elem ; j++)
        {
          num_som = zone().sommet_elem(num_elem,j);
          val(0) += ch(num_som);
        }
      val(0) /= nb_som_elem;
    }
  else
    {
      for (ncomp=0 ; ncomp<nb_compo_ ; ncomp++)
        {
          for (j=0 ; j<nb_som_elem ; j++)
            {
              num_som = zone().sommet_elem(num_elem,j);
              val(ncomp) += ch(num_som,ncomp);
            }
          val(ncomp) /= nb_som_elem;
        }
    }
  return val;
}
References Champ_implementation::le_champ(), Field_base::nb_comp(), Zone::nb_som_elem(), Zone::sommet_elem(), Champ_Proto::valeurs(), and Champ_implementation::zone().
valeur_a_elem_compo()
double Champ_Q4_implementation::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const override virtual
Implements Champ_implementation.
Definition at line 52 of file Champ_Q4_implementation.cpp.
{
  double val = 0.;
  const Champ_base& cha=le_champ();
  const DoubleTab& ch = cha.valeurs();
  int nb_compo_=cha.nb_comp();
  int j, num_som,nb_som_elem = zone().nb_som_elem();
  if (nb_compo_ == 1)
    {
      assert(ncomp==0);
      for (j=0 ; j<nb_som_elem ; j++)
        {
          num_som = zone().sommet_elem(num_elem,j);
          val += ch(num_som);
        }
      val /= nb_som_elem;
    }
  else
    {
      for (j=0 ; j<nb_som_elem ; j++)
        {
          num_som = zone().sommet_elem(num_elem,j);
          val += ch(num_som,ncomp);
        }
      val /= nb_som_elem;
    }
  return val;
}
References Champ_implementation::le_champ(), Field_base::nb_comp(), Zone::nb_som_elem(), Zone::sommet_elem(), Champ_Proto::valeurs(), and Champ_implementation::zone().
valeur_aux_elems()
DoubleTab & Champ_Q4_implementation::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) const override virtual
Implements Champ_implementation.
Definition at line 84 of file Champ_Q4_implementation.cpp.
{
  val = 0.;
  const Champ_base& cha=le_champ();
  const DoubleTab& ch = cha.valeurs();
  int nb_compo_=cha.nb_comp();
  int j,ncomp, num_som,nb_som_elem = zone().nb_som_elem(), ielem, num_elem,nb_elems=les_elems.size();
  assert(val.size()==nb_elems);
  if (nb_compo_ == 1)
    {
      for (ielem=0 ; ielem<nb_elems ; ielem++)
        {
          num_elem = les_elems(ielem);
          for (j=0 ; j<nb_som_elem ; j++)
            {
              num_som = zone().sommet_elem(num_elem,j);
              val(ielem,0) += ch(num_som);
            }
          val(ielem,0) /= nb_som_elem;
        }
    }
  else
    {
      for (ielem=0 ; ielem<nb_elems ; ielem++)
        {
          num_elem = les_elems(ielem);
          for (ncomp=0 ; ncomp<nb_compo_ ; ncomp++)
            {
              for (j=0 ; j<nb_som_elem ; j++)
                {
                  num_som = zone().sommet_elem(num_elem,j);
                  val(ielem,ncomp) += ch(num_som,ncomp);
                }
              val(ielem,ncomp) /= nb_som_elem;
            }
        }
    }
  return val;
}
References Champ_implementation::le_champ(), Field_base::nb_comp(), Zone::nb_som_elem(), TRUSTVect< _TYPE_ >::size(), Zone::sommet_elem(), Champ_Proto::valeurs(), and Champ_implementation::zone().
valeur_aux_elems_compo()
DoubleVect & Champ_Q4_implementation::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & valeurs, int ncomp) const override virtual
Implements Champ_implementation.
Definition at line 127 of file Champ_Q4_implementation.cpp.
{
  val = 0.;
  const Champ_base& cha=le_champ();
  const DoubleTab& ch = cha.valeurs();
  int nb_compo_=cha.nb_comp();
  int j, num_som,nb_som_elem = zone().nb_som_elem(), ielem, num_elem,nb_elems=les_elems.size();
  assert(val.size()==nb_elems);
  if (nb_compo_ == 1)
    {
      assert(ncomp==0);
      for (ielem=0 ; ielem<nb_elems ; ielem++)
        {
          num_elem = les_elems(ielem);
          for (j=0 ; j<nb_som_elem ; j++)
            {
              num_som = zone().sommet_elem(num_elem,j);
              val(ielem) += ch(num_som);
            }
          val(ielem) /= nb_som_elem;
        }
    }
  else
    {
      for (ielem=0 ; ielem<nb_elems ; ielem++)
        {
          num_elem = les_elems(ielem);
          for (j=0 ; j<nb_som_elem ; j++)
            {
              num_som = zone().sommet_elem(num_elem,j);
              val(ielem) += ch(num_som,ncomp);
            }
          val(ielem) /= nb_som_elem;
        }
    }
  return val;
}
References Champ_implementation::le_champ(), Field_base::nb_comp(), Zone::nb_som_elem(), TRUSTVect< _TYPE_ >::size(), Zone::sommet_elem(), Champ_Proto::valeurs(), and Champ_implementation::zone().
valeur_aux_sommets()
DoubleTab & Champ_Q4_implementation::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const override virtual
Implements Champ_implementation.
Definition at line 168 of file Champ_Q4_implementation.cpp.
{
  const Champ_base& cha=le_champ();
  const DoubleTab& ch = cha.valeurs();
// val = cha.valeurs();
  int nb_compo_=cha.nb_comp();
  if (nb_compo_==1)
    {
      int isom,nbsom = ch.size();
      for (isom=0 ; isom<nbsom ; isom++)
        {
          val(isom,0) = ch(isom);
        }
    }
  else
    {
      int isom,nbsom = ch.size();
      for (int ncomp=0 ; ncomp<nb_compo_ ; ncomp++)
        {
          for (isom=0 ; isom<nbsom ; isom++)
            {
              val(isom,ncomp) = ch(isom,ncomp);
            }
        }
    }
  return val;
}
References Champ_implementation::le_champ(), Field_base::nb_comp(), TRUSTVect< _TYPE_ >::size(), and Champ_Proto::valeurs().
valeur_aux_sommets_compo()
DoubleVect & Champ_Q4_implementation::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int ncomp) const override virtual
Implements Champ_implementation.
Definition at line 196 of file Champ_Q4_implementation.cpp.
{
  const Champ_base& cha=le_champ();
  const DoubleTab& ch = cha.valeurs();
  int nb_compo_=cha.nb_comp();
  if (nb_compo_==1)
    {
      assert(ncomp==0);
      int isom,nbsom = ch.size();
      for (isom=0 ; isom<nbsom ; isom++)
        {
          val(isom) = ch(isom);
        }
    }
  else
    {
      int isom,nbsom = ch.size();
      for (isom=0 ; isom<nbsom ; isom++)
        {
          val(isom) = ch(isom,ncomp);
        }
    }
  return val;
}
References Champ_implementation::le_champ(), Field_base::nb_comp(), TRUSTVect< _TYPE_ >::size(), and Champ_Proto::valeurs().
The documentation for this class was generated from the following files:
src/Kernel/Champs_dis/Champ_Q4_implementation.h
src/Kernel/Champs_dis/Champ_Q4_implementation.cpp