TRUST: Op_Div_PolyMAC Class Reference
Op_Div_PolyMAC Class Reference
class Op_Div_PolyMAC
Cette classe represente l'operateur de divergence
La discretisation est PolyMAC
On calcule la divergence d'un champ_P1NC (la vitesse)
#include <Op_Div_PolyMAC.h>
Public Member Functions
Op_Div_PolyMAC ()
~Op_Div_PolyMAC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
virtual int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void volumique (DoubleTab &) const override
Public Member Functions inherited from Operateur_Div_base
Operateur_Div_base ()
~Operateur_Div_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleVect & multvect (const DoubleTab &, DoubleTab &) const
virtual void volumique (DoubleTab &) const =0
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Div_PolyMAC & self_cast (Objet_U &)
static const Op_Div_PolyMAC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Div_base
static const Type_info * info ()
static Operateur_Div_base & self_cast (Objet_U &)
static const Operateur_Div_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Div_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Attributes
Ref_Zone_PolyMAC la_zone_PolyMAC
Ref_Zone_Cl_PolyMAC la_zcl_PolyMAC
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Div_PolyMAC
Cette classe represente l'operateur de divergence
La discretisation est PolyMAC
On calcule la divergence d'un champ_P1NC (la vitesse)
Definition at line 45 of file Op_Div_PolyMAC.h.
Constructor & Destructor Documentation
Op_Div_PolyMAC()
Op_Div_PolyMAC::Op_Div_PolyMAC ()
Definition at line 31 of file Op_Div_PolyMAC.cpp.
~Op_Div_PolyMAC()
Op_Div_PolyMAC::~Op_Div_PolyMAC ()
Definition at line 31 of file Op_Div_PolyMAC.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Div_PolyMAC::ajouter (const DoubleTab & vit, DoubleTab & div) const override virtual
Reimplemented from Operateur_base.
Definition at line 150 of file Op_Div_PolyMAC.cpp.
{
  const Zone_PolyMAC& zone = la_zone_PolyMAC.valeur();
  const DoubleVect& fs = zone.face_surfaces(), &pf = zone.porosite_face();
  const DoubleTab& nf = zone.face_normales();
  const Conds_lim& cls = la_zcl_PolyMAC->les_conditions_limites();
  const IntTab& f_e = zone.face_voisins(), &fcl = ref_cast(Champ_Face_PolyMAC, equation().inconnue().valeur()).fcl();
  int i, e, f, ne_tot = zone.nb_elem_tot(), d, D = dimension, has_f = div.dimension_tot(0) > ne_tot;
  DoubleTab& tab_flux_bords = flux_bords_;
  tab_flux_bords.resize(zone.nb_faces_bord(),1);
  tab_flux_bords=0;
  for (f = 0; f < zone.nb_faces(); f++)
    {
      for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
        if (e < zone.nb_elem()) /* aux elements */
          div(e) += (i ? -1 : 1) * fs(f) * pf(f) * vit(f);
      if (f >= zone.premiere_face_int()) continue;
      /* si "div" a des valeurs aux faces : bilan de masse avec la CL imposee aux faces de bord de Dirichlet */
      if (has_f && fcl(f, 0) != 1) div(ne_tot + f) -= fs(f) * pf(f) * vit(f);
      if (has_f && fcl(f, 0) == 3)
        for (d = 0; d < D; d++) div(ne_tot + f) += nf(f, d) * pf(f) * ref_cast(Dirichlet, cls[fcl(f, 1)].valeur()).val_imp(fcl(f, 2), d);
      /* a toutes les faces de bord : contribution a tab_flux_bords */
      tab_flux_bords(f) = fs(f) * pf(f) * vit(f); //flux aux bords
    }
  div.echange_espace_virtuel();
  return div;
}
References Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), Zone_Poly_base::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Operateur_base::flux_bords_, la_zcl_PolyMAC, la_zone_PolyMAC, Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Ref_Zone_PolyMAC::valeur(), and valeur().
Referenced by calculer().
ajouter_blocs()
void Op_Div_PolyMAC::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
Definition at line 96 of file Op_Div_PolyMAC.cpp.
{
  const Zone_PolyMAC& zone = la_zone_PolyMAC.valeur();
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, equation().inconnue().valeur());
  const Conds_lim& cls = la_zcl_PolyMAC->les_conditions_limites();
  const DoubleTab& inco = ch.valeurs(), &press = ref_cast(Navier_Stokes_std, equation()).pression().valeurs(), &nf = zone.face_normales();
  const IntTab& e_f = zone.elem_faces(), &f_e = zone.face_voisins(), &fcl = ch.fcl();
  const DoubleVect& fs = zone.face_surfaces(), &pf = zone.porosite_face();
  int i, j, e, f, fb, ne_tot = zone.nb_elem_tot(), d, D = dimension;
  Matrice_Morse *matv = matrices.count("vitesse") ? matrices["vitesse"] : NULL, *matp = matrices.count("pression") ? matrices["pression"] : NULL, matv2, matp2;
  DoubleTrav w2; //matrice w2 aux elements (la meme que dans Op_Grad et Assembleur_P)
  w2.set_smart_resize(1);
  for (f = 0; f < zone.nb_faces(); f++) /* divergence aux elements + equations aux bords */
    {
      for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
        if (e < zone.nb_elem()) /* divergence aux elems */
          {
            secmem(e) -= (i ? 1 : -1) * fs(f) * pf(f) * inco(f);
            if (fcl(f, 0) < 2 && matv) (*matv)(e, f) += (i ? 1 : -1) * fs(f) * pf(f);
          }
      /* equations v = v_imp ou p = p_imp aux faces de bord */
      if (fcl(f, 0) > 1)
        {
          if (fcl(f, 0) == 3)
            for (d = 0; d < D; d++) secmem(ne_tot + f) += nf(f, d) * pf(f) * ref_cast(Dirichlet, cls[fcl(f, 1)].valeur()).val_imp(fcl(f, 2), d);
          secmem(ne_tot + f) -= fs(f) * pf(f) * inco(f);
          if (matv) (*matv)(ne_tot + f, f) += fs(f) * pf(f);
        }
      else if (fcl(f, 0) == 1)
        {
          secmem(ne_tot + f) += ref_cast(Neumann, cls[fcl(f, 1)].valeur()).flux_impose(fcl(f, 2), 0) - press(ne_tot + f);
          if (matp) (*matp)(ne_tot + f, ne_tot + f) += 1;
        }
    }
  /* equations aux faces internes : egalite des gradients */
  for (e = 0; e < zone.nb_elem_tot(); e++)
    for (zone.W2(NULL, e, w2), i = 0; i < w2.dimension(0); i++)
      if ((f = e_f(e, i)) < zone.nb_faces() && !fcl(f, 0))
        {
          double coeff_e = 0;
          for (j = 0; j < w2.dimension(1); j++)
            if (w2(i, j, 0))
              {
                fb = e_f(e, j);
                secmem(ne_tot + f) -= pf(f) * w2(i, j, 0) * (press(ne_tot + fb) - press(e));
                if (matp) (*matp)(ne_tot + f, ne_tot + fb) += pf(f) * w2(i, j, 0), coeff_e += pf(f) * w2(i, j, 0);
              }
          if (matp) (*matp)(ne_tot + f, e) -= coeff_e;
        }
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Zone_Poly_base::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Champ_Face_PolyMAC::fcl(), la_zcl_PolyMAC, la_zone_PolyMAC, Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::porosite_face(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), Ref_Zone_PolyMAC::valeur(), valeur(), Champ_Inc_base::valeurs(), and Zone_PolyMAC::W2().
associer()
void Op_Div_PolyMAC::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis, const Champ_Inc &) override virtual
Implements Operateur_base.
Definition at line 53 of file Op_Div_PolyMAC.cpp.
{
  const Zone_PolyMAC& zPolyMAC = ref_cast(Zone_PolyMAC, zone_dis.valeur());
  const Zone_Cl_PolyMAC& zclPolyMAC = ref_cast(Zone_Cl_PolyMAC, zone_Cl_dis.valeur());
  la_zone_PolyMAC = zPolyMAC;
  la_zcl_PolyMAC = zclPolyMAC;
}
References la_zcl_PolyMAC, la_zone_PolyMAC, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
calculer()
DoubleTab & Op_Div_PolyMAC::calculer (const DoubleTab & vit, DoubleTab & div) const override virtual
Reimplemented from Operateur_base.
Definition at line 182 of file Op_Div_PolyMAC.cpp.
{
  div = 0;
  return ajouter(vit,div);
}
References ajouter().
cree_instance()
Objet_U * Op_Div_PolyMAC::cree_instance () static
Definition at line 31 of file Op_Div_PolyMAC.cpp.
dimensionner_blocs()
void Op_Div_PolyMAC::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
Definition at line 63 of file Op_Div_PolyMAC.cpp.
{
  const Zone_PolyMAC& zone = la_zone_PolyMAC.valeur();
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, equation().inconnue().valeur());
  const DoubleTab& inco = ch.valeurs(), &press = ref_cast(Navier_Stokes_std, equation()).pression().valeurs();
  const IntTab& e_f = zone.elem_faces(), &f_e = zone.face_voisins(), &fcl = ch.fcl();
  int i, j, e, f, ne_tot = zone.nb_elem_tot();
  Matrice_Morse *matv = matrices.count("vitesse") ? matrices["vitesse"] : NULL, *matp = matrices.count("pression") ? matrices["pression"] : NULL, matv2, matp2;
  IntTab sten_v(0,2), sten_p(0, 2);
  DoubleTab w2; //matrice w2 aux elements (la meme que dans Op_Grad et Assembleur_P)
  sten_v.set_smart_resize(1), sten_p.set_smart_resize(1), w2.set_smart_resize(1);
  for (f = 0; matv && f < zone.nb_faces(); f++) /* dependance en v : divergence par elem + v = v_imp aux faces de Dirichlet */
    if (fcl(f, 0) > 1) sten_v.append_line(ne_tot + f, f); /* v impose par CLs : contribution a l'equation v = v_imp a la paroi */
    else for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
        if (e < zone.nb_elem()) sten_v.append_line(e, f); /* v calcule : contribution a la divergence aux elems */
  for (e = 0; matp && e < zone.nb_elem_tot(); e++)
    for (zone.W2(NULL, e, w2), i = 0; i < w2.dimension(0); i++) /* dependance en p : equation sur p_f */
      if (fcl(f = e_f(e, i), 0) == 1) sten_p.append_line(ne_tot + f, ne_tot + f); /* aux faces de Neumann : p_f = p_imp */
      else if (!fcl(f, 0))
        for (sten_p.append_line(ne_tot + f, e), j = 0; j < w2.dimension(1); j++) /* aux faces internes : egalite des deux gradients */
          if (w2(i, j, 0)) sten_p.append_line(ne_tot + f, ne_tot + e_f(e, j));
  if (matp)
    for (e = 0; e < zone.nb_elem(); e++) sten_p.append_line(e, e); //diagonale du vide!
  if (matv) tableau_trier_retirer_doublons(sten_v), Matrix_tools::allocate_morse_matrix(press.size_totale(), inco.size_totale(), sten_v, matv2);
  if (matp) tableau_trier_retirer_doublons(sten_p), Matrix_tools::allocate_morse_matrix(press.size_totale(), press.size_totale(), sten_p, matp2);
  if (matv) matv->nb_colonnes() ? *matv += matv2 : *matv = matv2;
  if (matp) matp->nb_colonnes() ? *matp += matp2 : *matp = matp2;
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_voisins(), Champ_Face_PolyMAC::fcl(), la_zone_PolyMAC, Matrice_Morse::nb_colonnes(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTVect< _TYPE_ >::size_totale(), tableau_trier_retirer_doublons(), Ref_Zone_PolyMAC::valeur(), valeur(), Champ_Inc_base::valeurs(), and Zone_PolyMAC::W2().
duplique()
int Op_Div_PolyMAC::duplique () const override virtual
Implements Objet_U.
Definition at line 31 of file Op_Div_PolyMAC.cpp.
get_info()
const Type_info * Op_Div_PolyMAC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Div_base.
Definition at line 31 of file Op_Div_PolyMAC.cpp.
has_interface_blocs()
int Op_Div_PolyMAC::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
Definition at line 55 of file Op_Div_PolyMAC.h.
  {
    return 1;
  };
impr()
int Op_Div_PolyMAC::impr (Sortie & os) const override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 189 of file Op_Div_PolyMAC.cpp.
{
  const int impr_bord=(la_zone_PolyMAC->zone().Bords_a_imprimer().est_vide() ? 0:1);
  SFichier Flux_div;
  ouvrir_fichier(Flux_div,"",je_suis_maitre());
  EcrFicPartage Flux_face;
  ouvrir_fichier_partage(Flux_face,"",impr_bord);
  const Schema_Temps_base& sch = equation().probleme().schema_temps();
  double temps = sch.temps_courant();
  if (je_suis_maitre()) Flux_div.add_col(temps);
  int nb_compo=flux_bords_.dimension(1);
// On parcours les frontieres pour sommer les flux par frontiere dans le tableau flux_bord
  DoubleVect flux_bord(nb_compo);
  DoubleVect bilan(nb_compo);
  bilan = 0;
  for (int num_cl=0; num_cl<la_zone_PolyMAC->nb_front_Cl(); num_cl++)
    {
      flux_bord=0;
      const Cond_lim& la_cl = la_zcl_PolyMAC->les_conditions_limites(num_cl);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = frontiere_dis.num_premiere_face();
      int nfin = ndeb + frontiere_dis.nb_faces();
      for (int face=ndeb; face<nfin; face++)
        for(int k=0; k<nb_compo; k++)
          flux_bord(k)+=flux_bords_(face, k);
      for(int k=0; k<nb_compo; k++)
        flux_bord(k)=Process::mp_sum(flux_bord(k));
      if(je_suis_maitre())
        {
          for(int k=0; k<nb_compo; k++)
            {
// Ajout pour impression sur fichiers separes
              Flux_div.add_col(flux_bord(k));
              bilan(k)+=flux_bord(k);
            }
        }
    }
  if(je_suis_maitre())
    {
      for(int k=0; k<nb_compo; k++)
        {
          Flux_div.add_col(bilan(k));
        }
      Flux_div << finl;
    }
  for (int num_cl=0; num_cl<la_zone_PolyMAC->nb_front_Cl(); num_cl++)
    {
      const Frontiere_dis_base& la_fr = la_zcl_PolyMAC->les_conditions_limites(num_cl).frontiere_dis();
      const Cond_lim& la_cl = la_zcl_PolyMAC->les_conditions_limites(num_cl);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = frontiere_dis.num_premiere_face();
      int nfin = ndeb + frontiere_dis.nb_faces();
      if (la_zone_PolyMAC->zone().Bords_a_imprimer().contient(la_fr.le_nom()))
        {
          Flux_face << "# Flux par face sur " << la_fr.le_nom() << " au temps " << temps << " : " << finl;
          for (int face=ndeb; face<nfin; face++)
            {
              if (dimension==2)
                Flux_face << "# Face a x= " << la_zone_PolyMAC->xv(face,0) << " y= " << la_zone_PolyMAC->xv(face,1) << " flux=" ;
              else if (dimension==3)
                Flux_face << "# Face a x= " << la_zone_PolyMAC->xv(face,0) << " y= " << la_zone_PolyMAC->xv(face,1) << " z= " << la_zone_PolyMAC->xv(face,2) << " flux=" ;
              for(int k=0; k<nb_compo; k++)
                Flux_face << " " << flux_bords_(face, k);
              Flux_face << finl;
            }
          Flux_face.syncfile();
        }
    }
  return 1;
}
References Sortie::add_col(), Zone::Bords_a_imprimer(), List_Nom::contient(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), liste::est_vide(), finl, Operateur_base::flux_bords_, Cond_lim::frontiere_dis(), Process::je_suis_maitre(), la_zcl_PolyMAC, la_zone_PolyMAC, Frontiere_dis_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Process::mp_sum(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Operateur_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), Equation_base::probleme(), ref_cast, Probleme_base::schema_temps(), EcrFicPartage::syncfile(), Schema_Temps_base::temps_courant(), Zone_VF::xv(), and Zone_dis_base::zone().
info()
const Type_info * Op_Div_PolyMAC::info () static
Definition at line 31 of file Op_Div_PolyMAC.cpp.
printOn()
Sortie & Op_Div_PolyMAC::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Div_base.
Definition at line 37 of file Op_Div_PolyMAC.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Div_PolyMAC::readOn (Entree & is) override protected virtual
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Div_base.
Definition at line 45 of file Op_Div_PolyMAC.cpp.
{
  return s ;
}
self_cast() [1/2]
const Op_Div_PolyMAC & Op_Div_PolyMAC::self_cast (const Objet_U & r) static
Definition at line 31 of file Op_Div_PolyMAC.cpp.
self_cast() [2/2]
Op_Div_PolyMAC & Op_Div_PolyMAC::self_cast (Objet_U & r) static
Definition at line 31 of file Op_Div_PolyMAC.cpp.
taille_memoire()
unsigned Op_Div_PolyMAC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 31 of file Op_Div_PolyMAC.cpp.
volumique()
void Op_Div_PolyMAC::volumique (DoubleTab & div) const override virtual
Implements Operateur_Div_base.
Definition at line 267 of file Op_Div_PolyMAC.cpp.
{
  const Zone_PolyMAC& zone_PolyMAC = la_zone_PolyMAC.valeur();
  const DoubleVect& vol = zone_PolyMAC.volumes();
  int nb_elem=zone_PolyMAC.zone().nb_elem_tot();
  int num_elem;
  for(num_elem=0; num_elem<nb_elem; num_elem++)
    div(num_elem)/=vol(num_elem);
}
References la_zone_PolyMAC, Zone::nb_elem_tot(), Ref_Zone_PolyMAC::valeur(), Zone_VF::volumes(), and Zone_dis_base::zone().
Member Data Documentation
info_obj
const Type_info Op_Div_PolyMAC::info_obj static
Definition at line 48 of file Op_Div_PolyMAC.h.
la_zcl_PolyMAC
Ref_Zone_Cl_PolyMAC Op_Div_PolyMAC::la_zcl_PolyMAC protected
Definition at line 73 of file Op_Div_PolyMAC.h.
Referenced by ajouter(), ajouter_blocs(), associer(), and impr().
la_zone_PolyMAC
Ref_Zone_PolyMAC Op_Div_PolyMAC::la_zone_PolyMAC protected
Definition at line 72 of file Op_Div_PolyMAC.h.
Referenced by ajouter(), ajouter_blocs(), associer(), dimensionner_blocs(), impr(), and volumique().
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Op_Div_PolyMAC.h
src/PolyMAC/Operateurs/Op_Div_PolyMAC.cpp