TRUST: Multi_Sch_ThHyd Class Reference
Multi_Sch_ThHyd Class Reference
classe Multi_Sch_ThHyd
#include <Multi_Sch_ThHyd.h>
Public Member Functions
Multi_Sch_ThHyd ()
~Multi_Sch_ThHyd ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int nb_valeurs_temporelles () const
Renvoie le nombre de valeurs temporelles a conserver.
Ici : le max des deux schemas utilises.
virtual int nb_valeurs_futures () const
Renvoie le nombre de valeurs temporelles futures.
Ici : la valeur commune aux deux schemas utilises.
virtual double temps_futur (int i) const
Renvoie le le temps a la i-eme valeur future.
Ici : la valeur commune aux deux schemas utilises.
virtual double temps_defaut () const
Renvoie le le temps le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : la valeur commune aux deux schemas utilises.
virtual int faire_un_pas_de_temps_eqn_base (Equation_base &)
Effectue un pas de temps d'Euler explicite
sur l'equation passee en parametre.
virtual bool iterateTimeStep (bool &converged)
Calculate the U(n+1) unknown for each equation (if solved) of the problem with the selected time scheme.
virtual void set_param (Param &titi)
virtual int mettre_a_jour ()
Mise a jour du temps courant (t+=dt)
et du nombre de pas de temps effectue (nb_pas_dt_++).
virtual bool corriger_dt_calcule (double &) const
Corrige le pas de temps dt_min <= dt <= dt_max.
virtual void completer ()
virtual void changer_temps_courant (const double &)
Appel a l'objet sous-jacent
Change le temps courant.
virtual int stop () const
Appel a l'objet sous-jacent
Renvoie 1 si il y lieu de stopper le calcul pour differente raisons:
- le temps final est atteint
- le nombre de pas de temps maximum est depasse
- l'etat stationnaire est atteint
- indicateur d'arret fichier
Renvoie 0 sinon.
virtual void imprimer (Sortie &) const
Appel a l'objet sous-jacent
Imprime le schema en temp sur un flot de sortie (si il y a lieu).
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Multi_Sch_ThHyd & self_cast (Objet_U &)
static const Multi_Sch_ThHyd & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Private Attributes
int nb_ss_pas_dt
Schema_Temps sch_ns
Schema_Temps sch_scalaires
Detailed Description
classe Multi_Sch_ThHyd
Definition at line 35 of file Multi_Sch_ThHyd.h.
Constructor & Destructor Documentation
Multi_Sch_ThHyd::Multi_Sch_ThHyd ()
Definition at line 28 of file Multi_Sch_ThHyd.cpp.
Multi_Sch_ThHyd::~Multi_Sch_ThHyd ()
Definition at line 28 of file Multi_Sch_ThHyd.cpp.
Member Function Documentation
void Multi_Sch_ThHyd::changer_temps_courant (const double & t) [virtual]
Appel a l'objet sous-jacent
Change le temps courant.
Reimplemented from Schema_Temps_base.
Definition at line 305 of file Multi_Sch_ThHyd.cpp.
References Schema_Temps_base::changer_temps_courant(), sch_ns, sch_scalaires, and Deriv_Schema_Temps_base::valeur().
{
  sch_ns.valeur().changer_temps_courant(t);
  sch_scalaires.valeur().changer_temps_courant(t);
  Schema_Temps_base::changer_temps_courant(t);
}
void Multi_Sch_ThHyd::completer (void) [virtual]
Implements Schema_Temps_base.
Definition at line 128 of file Multi_Sch_ThHyd.cpp.
References Schema_Temps_base::diffusion_implicite(), Schema_Temps_base::facteur_securite_pas(), Schema_Temps_base::indice_nb_pas_dt_max_atteint(), Schema_Temps_base::indice_tps_final_atteint(), Schema_Temps_base::isStationary(), Schema_Temps_base::lu(), Schema_Temps_base::mode_dt_start(), Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::nb_pas_dt_max(), Schema_Temps_base::niter_max_diffusion_implicite(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_max(), Schema_Temps_base::pas_temps_min(), sch_ns, sch_scalaires, Schema_Temps_base::set_diffusion_implicite(), Schema_Temps_base::set_dt(), Schema_Temps_base::set_dt_impr(), Schema_Temps_base::set_dt_max(), Schema_Temps_base::set_dt_min(), Schema_Temps_base::set_dt_sauv(), Schema_Temps_base::set_facsec(), Schema_Temps_base::set_indice_nb_pas_dt_max_atteint(), Schema_Temps_base::set_indice_tps_final_atteint(), Schema_Temps_base::set_lu(), Schema_Temps_base::set_mode_dt_start(), Schema_Temps_base::set_nb_pas_dt(), Schema_Temps_base::set_nb_pas_dt_max(), Schema_Temps_base::set_niter_max_diffusion_implicite(), Schema_Temps_base::set_seuil_diffusion_implicite(), Schema_Temps_base::set_seuil_statio(), Schema_Temps_base::set_stationnaire_atteint(), Schema_Temps_base::set_temps_courant(), Schema_Temps_base::set_temps_init(), Schema_Temps_base::set_temps_max(), Schema_Temps_base::seuil_diffusion_implicite(), Schema_Temps_base::seuil_statio(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_impr(), Schema_Temps_base::temps_init(), Schema_Temps_base::temps_max(), Schema_Temps_base::temps_sauv(), and Deriv_Schema_Temps_base::valeur().
{
  /*  double dts=dt_;
      dt_=0;
      mettre_a_jour();
      nb_pas_dt_--;
      dt_=dts;
// OC : je comprends pas ces lignes :
  */
// OC : je verrai plutot une methode  "completer" de ce genre :
  Schema_Temps_base& le_sch_ns = sch_ns.valeur();
  le_sch_ns.set_temps_init()=temps_init();
  le_sch_ns.set_temps_max()=temps_max();
  le_sch_ns.set_temps_courant()=temps_courant();
  le_sch_ns.set_nb_pas_dt()=nb_pas_dt();
  le_sch_ns.set_nb_pas_dt_max()=nb_pas_dt_max();
  le_sch_ns.set_dt_min()=pas_temps_min();
  le_sch_ns.set_dt_max()=pas_temps_max();
  le_sch_ns.set_dt_sauv()=temps_sauv();
  le_sch_ns.set_dt_impr()=temps_impr();
  le_sch_ns.set_facsec()=facteur_securite_pas();
  le_sch_ns.set_seuil_statio()=seuil_statio();
  le_sch_ns.set_stationnaire_atteint()=isStationary();
  le_sch_ns.set_diffusion_implicite()=diffusion_implicite();
  le_sch_ns.set_seuil_diffusion_implicite()=seuil_diffusion_implicite();
  le_sch_ns.set_niter_max_diffusion_implicite()=niter_max_diffusion_implicite();
  le_sch_ns.set_dt()=pas_de_temps();
  le_sch_ns.set_mode_dt_start()=mode_dt_start();
  le_sch_ns.set_indice_tps_final_atteint()=indice_tps_final_atteint();
  le_sch_ns.set_indice_nb_pas_dt_max_atteint()=indice_nb_pas_dt_max_atteint();
  le_sch_ns.set_lu()=lu();
  Schema_Temps_base& le_sch_scalaires = sch_scalaires.valeur();
  le_sch_scalaires.set_temps_init()=temps_init();
  le_sch_scalaires.set_temps_max()=temps_max();
  le_sch_scalaires.set_temps_courant()=temps_courant();
  le_sch_scalaires.set_nb_pas_dt()=nb_pas_dt();
  le_sch_scalaires.set_nb_pas_dt_max()=nb_pas_dt_max();
  le_sch_scalaires.set_dt_min()=pas_temps_min();
  le_sch_scalaires.set_dt_max()=pas_temps_max();
  le_sch_scalaires.set_dt_sauv()=temps_sauv();
  le_sch_scalaires.set_dt_impr()=temps_impr();
  le_sch_scalaires.set_facsec()=facteur_securite_pas();
  le_sch_scalaires.set_seuil_statio()=seuil_statio();
  le_sch_scalaires.set_stationnaire_atteint()=isStationary();
  le_sch_scalaires.set_diffusion_implicite()=diffusion_implicite();
  le_sch_scalaires.set_seuil_diffusion_implicite()=seuil_diffusion_implicite();
  le_sch_scalaires.set_niter_max_diffusion_implicite()=niter_max_diffusion_implicite();
  le_sch_scalaires.set_dt()=pas_de_temps();
  le_sch_scalaires.set_mode_dt_start()=mode_dt_start();
  le_sch_scalaires.set_indice_tps_final_atteint()=indice_tps_final_atteint();
  le_sch_scalaires.set_indice_nb_pas_dt_max_atteint()=indice_nb_pas_dt_max_atteint();
  le_sch_scalaires.set_lu()=lu();
}
bool Multi_Sch_ThHyd::corriger_dt_calcule (double & dt) const [virtual]
Corrige le pas de temps dt_min <= dt <= dt_max.
Returns:
int
Signification: retourne corriger_pas_temps de la classe mere
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 281 of file Multi_Sch_ThHyd.cpp.
References Schema_Temps_base::corriger_dt_calcule(), sch_ns, sch_scalaires, and Deriv_Schema_Temps_base::valeur().
{
  bool ok=sch_ns.valeur().corriger_dt_calcule(dt);
  ok = ok && sch_scalaires.valeur().corriger_dt_calcule(dt);
  ok = ok && Schema_Temps_base::corriger_dt_calcule(dt);
  return ok;
}
Objet_U * Multi_Sch_ThHyd::cree_instance () [static]
Definition at line 28 of file Multi_Sch_ThHyd.cpp.
int Multi_Sch_ThHyd::duplique () const [virtual]
Implements Schema_Temps_base.
Definition at line 28 of file Multi_Sch_ThHyd.cpp.
int Multi_Sch_ThHyd::faire_un_pas_de_temps_eqn_base (Equation_base & eqn) [virtual]
Effectue un pas de temps d'Euler explicite
sur l'equation passee en parametre.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Implements Schema_Temps_base.
Definition at line 217 of file Multi_Sch_ThHyd.cpp.
References Schema_Temps::facteur_securite_pas(), Schema_Temps_base::facteur_securite_pas(), Schema_Temps::faire_un_pas_de_temps_eqn_base(), Schema_Temps_base::isStationary(), Schema_Temps_base::pas_de_temps(), sch_ns, sch_scalaires, Schema_Temps_base::set_stationnaire_atteint(), sub_type, and Deriv_Schema_Temps_base::valeur().
Referenced by iterateTimeStep().
{
// double dtok=dt_;
  if(sub_type(Navier_Stokes_std, eqn))
    {
      sch_ns->set_dt()=pas_de_temps();
      sch_ns.faire_un_pas_de_temps_eqn_base(eqn);
      facteur_securite_pas()=sch_ns.facteur_securite_pas();
    }
  else
    {
// sch_scalaires.preparer_pas_temps();
      sch_scalaires->set_dt()=pas_de_temps();
      sch_scalaires.faire_un_pas_de_temps_eqn_base(eqn);
    }
  set_stationnaire_atteint()=sch_ns.valeur().isStationary() && sch_scalaires.valeur().isStationary() ;
  return 1;
}
const Type_info * Multi_Sch_ThHyd::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 28 of file Multi_Sch_ThHyd.cpp.
void Multi_Sch_ThHyd::imprimer (Sortie & os) const [virtual]
Appel a l'objet sous-jacent
Imprime le schema en temp sur un flot de sortie (si il y a lieu).
Reimplemented from Schema_Temps_base.
Definition at line 358 of file Multi_Sch_ThHyd.cpp.
References Schema_Temps_base::imprimer(), sch_ns, sch_scalaires, and Deriv_Schema_Temps_base::valeur().
{
  sch_ns.valeur().imprimer(os);
  sch_scalaires.valeur().imprimer(os);
  Schema_Temps_base::imprimer(os);
}
const Type_info * Multi_Sch_ThHyd::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 28 of file Multi_Sch_ThHyd.cpp.
bool Multi_Sch_ThHyd::iterateTimeStep (bool & converged) [virtual]
Calculate the U(n+1) unknown for each equation (if solved) of the problem with the selected time scheme.
Reimplemented from Schema_Temps_base.
Definition at line 236 of file Multi_Sch_ThHyd.cpp.
References Cout, Equation_base::derivee_en_temps_inco(), Schema_Temps_base::dt_, Probleme_base::equation(), Equation_base::equation_non_resolue(), faire_un_pas_de_temps_eqn_base(), finl, Equation_base::inconnue(), Zone_Cl_dis::mettre_a_jour(), Schema_Temps_base::nb_pas_dt(), Probleme_base::nombre_d_equations(), Schema_Temps_base::pb_base(), Objet_U::que_suis_je(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant_, Champ_Inc::valeurs(), and Equation_base::zone_Cl_dis().
{
  Probleme_base& prob=pb_base();
  double temps=temps_courant_+dt_;
  int nb_eqn=pb_base().nombre_d_equations();
  for(int i=nb_eqn-1; i>-1; i--)
    {
      Equation_base& eqn_i=prob.equation(i);
      if (eqn_i.equation_non_resolue())
        {
          Cout<< "====================================================" << finl;
          Cout<< eqn_i.que_suis_je()<<" equation is not solved."<<finl;
          Cout<< "====================================================" << finl;
// On calcule une fois la derivee pour avoir les flux bord
          if (eqn_i.schema_temps().nb_pas_dt()==0)
            {
              DoubleTab inconnue_valeurs(eqn_i.inconnue().valeurs());
              eqn_i.derivee_en_temps_inco(inconnue_valeurs);
            }
        }
      else
        {
          eqn_i.zone_Cl_dis().mettre_a_jour(temps);
          faire_un_pas_de_temps_eqn_base(eqn_i);
        }
    }
  converged=true;
  return true;
}
int Multi_Sch_ThHyd::mettre_a_jour () [virtual]
Mise a jour du temps courant (t+=dt)
et du nombre de pas de temps effectue (nb_pas_dt_++).
Returns:
int
Signification: retourne toujours 1
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 185 of file Multi_Sch_ThHyd.cpp.
References Schema_Temps::mettre_a_jour(), sch_ns, and sch_scalaires.
{
  Schema_Temps_base::mettre_a_jour();
  sch_ns.mettre_a_jour();
  sch_scalaires.mettre_a_jour();
  return 1;
}
int Multi_Sch_ThHyd::nb_valeurs_futures () const [virtual]
Renvoie le nombre de valeurs temporelles futures.
Ici : la valeur commune aux deux schemas utilises.
Implements Schema_Temps_base.
Definition at line 93 of file Multi_Sch_ThHyd.cpp.
References Schema_Temps_base::nb_valeurs_futures(), sch_ns, sch_scalaires, and Deriv_Schema_Temps_base::valeur().
{
  int n=sch_ns.valeur().nb_valeurs_futures();
  assert (n==sch_scalaires.valeur().nb_valeurs_futures());
  return n;
}
int Multi_Sch_ThHyd::nb_valeurs_temporelles () const [virtual]
Renvoie le nombre de valeurs temporelles a conserver.
Ici : le max des deux schemas utilises.
Implements Schema_Temps_base.
Definition at line 84 of file Multi_Sch_ThHyd.cpp.
References max(), Schema_Temps_base::nb_valeurs_temporelles(), sch_ns, sch_scalaires, and Deriv_Schema_Temps_base::valeur().
{
  return max(sch_ns.valeur().nb_valeurs_temporelles(),sch_scalaires.valeur().nb_valeurs_temporelles());
}
Sortie & Multi_Sch_ThHyd::printOn (Sortie & s) const [protected, virtual]
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 46 of file Multi_Sch_ThHyd.cpp.
{
  return  Schema_Temps_base::printOn(s);
}
Entree & Multi_Sch_ThHyd::readOn (Entree & s) [protected, virtual]
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 67 of file Multi_Sch_ThHyd.cpp.
References nb_ss_pas_dt.
{
  nb_ss_pas_dt=0;
  return Schema_Temps_base::readOn(s) ;
}
Multi_Sch_ThHyd & Multi_Sch_ThHyd::self_cast (Objet_U & r) [static]
Reimplemented from Schema_Temps_base.
Definition at line 28 of file Multi_Sch_ThHyd.cpp.
const Multi_Sch_ThHyd & Multi_Sch_ThHyd::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Schema_Temps_base.
Definition at line 28 of file Multi_Sch_ThHyd.cpp.
void Multi_Sch_ThHyd::set_param (Param & titi) [virtual]
Reimplemented from Schema_Temps_base.
Definition at line 192 of file Multi_Sch_ThHyd.cpp.
References Param::ajouter(), nb_ss_pas_dt, sch_ns, and sch_scalaires.
{
  param.ajouter("nb_ss_pas_dt",&nb_ss_pas_dt);
  param.ajouter("Schema_Temps_NS",&sch_ns);
  param.ajouter("Schema_Temps_scalaires",&sch_scalaires);
  Schema_Temps_base::set_param(param);
}
int Multi_Sch_ThHyd::stop () const [virtual]
Appel a l'objet sous-jacent
Renvoie 1 si il y lieu de stopper le calcul pour differente raisons:
- le temps final est atteint
- le nombre de pas de temps maximum est depasse
- l'etat stationnaire est atteint
- indicateur d'arret fichier
Renvoie 0 sinon.
Returns:
entier
Signification: 1 si il y a lieu de s'arreter 0 sinon
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 333 of file Multi_Sch_ThHyd.cpp.
References sch_ns, sch_scalaires, Schema_Temps_base::stop(), and Deriv_Schema_Temps_base::valeur().
{
  int ls2 = sch_ns.valeur().stop();
  int ls3 = sch_scalaires.valeur().stop();
  return (ls2 | ls3 | Schema_Temps_base::stop());
}
unsigned Multi_Sch_ThHyd::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 28 of file Multi_Sch_ThHyd.cpp.
double Multi_Sch_ThHyd::temps_defaut () const [virtual]
Renvoie le le temps le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : la valeur commune aux deux schemas utilises.
Implements Schema_Temps_base.
Definition at line 114 of file Multi_Sch_ThHyd.cpp.
References sch_ns, sch_scalaires, Schema_Temps_base::temps_defaut(), and Deriv_Schema_Temps_base::valeur().
{
  double t=sch_ns.valeur().temps_defaut();
  assert(t==sch_scalaires.valeur().temps_defaut());
  return t;
}
double Multi_Sch_ThHyd::temps_futur (int i) const [virtual]
Renvoie le le temps a la i-eme valeur future.
Ici : la valeur commune aux deux schemas utilises.
Implements Schema_Temps_base.
Definition at line 103 of file Multi_Sch_ThHyd.cpp.
References sch_ns, sch_scalaires, Schema_Temps_base::temps_futur(), and Deriv_Schema_Temps_base::valeur().
{
  double t=sch_ns.valeur().temps_futur(i);
  assert(t==sch_scalaires.valeur().temps_futur(i));
  return t;
}
Member Data Documentation
const Type_info Multi_Sch_ThHyd::info_obj [static]
Reimplemented from Schema_Temps_base.
Definition at line 38 of file Multi_Sch_ThHyd.h.
int Multi_Sch_ThHyd::nb_ss_pas_dt [private]
Definition at line 74 of file Multi_Sch_ThHyd.h.
Referenced by readOn(), and set_param().
Schema_Temps Multi_Sch_ThHyd::sch_ns [private]
Definition at line 75 of file Multi_Sch_ThHyd.h.
Referenced by changer_temps_courant(), completer(), corriger_dt_calcule(), faire_un_pas_de_temps_eqn_base(), imprimer(), mettre_a_jour(), nb_valeurs_futures(), nb_valeurs_temporelles(), set_param(), stop(), temps_defaut(), and temps_futur().
Schema_Temps Multi_Sch_ThHyd::sch_scalaires [private]
Definition at line 76 of file Multi_Sch_ThHyd.h.
Referenced by changer_temps_courant(), completer(), corriger_dt_calcule(), faire_un_pas_de_temps_eqn_base(), imprimer(), mettre_a_jour(), nb_valeurs_futures(), nb_valeurs_temporelles(), set_param(), stop(), temps_defaut(), and temps_futur().
The documentation for this class was generated from the following files:
src/ThHyd/Schemas_Temps/Multi_Sch_ThHyd.h
src/ThHyd/Schemas_Temps/Multi_Sch_ThHyd.cpp