TRUST: Ref_Objet_U Class Reference
Ref_Objet_U Class Reference
#include <Ref_Objet_U.h>
Public Member Functions
~Ref_Objet_U ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Objet_U ()
Ref_Objet_U (const Objet_U &)
Ref_Objet_U (const Ref_Objet_U &)
const Objet_U & valeur () const
Objet_U & valeur ()
const Objet_U * operator-> () const
Objet_U * operator-> ()
const Ref_Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
const Ref_Objet_U & operator= (const Ref_Objet_U &)
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Objet_U & self_cast (Objet_U &)
static const Ref_Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Objet_U * pointeur_
Detailed Description
Definition at line 92 of file Ref_Objet_U.h.
Constructor & Destructor Documentation
Ref_Objet_U::~Ref_Objet_U ()
Definition at line 88 of file Ref_Objet_U.cpp.
Ref_Objet_U::Ref_Objet_U ()
Definition at line 88 of file Ref_Objet_U.cpp.
Ref_Objet_U::Ref_Objet_U (const Objet_U & t)
Definition at line 88 of file Ref_Objet_U.cpp.
Ref_Objet_U::Ref_Objet_U (const Ref_Objet_U & t)
Definition at line 88 of file Ref_Objet_U.cpp.
Member Function Documentation
Objet_U * Ref_Objet_U::cree_instance () [static]
Definition at line 88 of file Ref_Objet_U.cpp.
int Ref_Objet_U::duplique () const [virtual]
Implements Ref_.
Definition at line 88 of file Ref_Objet_U.cpp.
const Type_info * Ref_Objet_U::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 88 of file Ref_Objet_U.cpp.
const Type_info & Ref_Objet_U::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 88 of file Ref_Objet_U.cpp.
const Type_info * Ref_Objet_U::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 88 of file Ref_Objet_U.cpp.
const Objet_U * Ref_Objet_U::operator-> () const [inline]
Definition at line 92 of file Ref_Objet_U.h.
Objet_U * Ref_Objet_U::operator-> () [inline]
Definition at line 92 of file Ref_Objet_U.h.
const Ref_Objet_U & Ref_Objet_U::operator= (const Ref_Objet_U & t)
Definition at line 88 of file Ref_Objet_U.cpp.
const Ref_Objet_U & Ref_Objet_U::operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Reimplemented from Objet_U.
Definition at line 88 of file Ref_Objet_U.cpp.
Sortie & Ref_Objet_U::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 88 of file Ref_Objet_U.cpp.
Entree & Ref_Objet_U::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 88 of file Ref_Objet_U.cpp.
const Ref_Objet_U & Ref_Objet_U::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 88 of file Ref_Objet_U.cpp.
Ref_Objet_U & Ref_Objet_U::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 88 of file Ref_Objet_U.cpp.
void Ref_Objet_U::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 88 of file Ref_Objet_U.cpp.
unsigned Ref_Objet_U::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 88 of file Ref_Objet_U.cpp.
const Objet_U & Ref_Objet_U::valeur () const [inline]
Definition at line 92 of file Ref_Objet_U.h.
Referenced by Op_Dift_VDF_base::ajouter(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Champ_front_contact_VEF::calcul_grads_locaux(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), calculer_h_distant(), calculer_h_local(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Op_Dift_VEF_base::completer(), Op_Dift_VDF_var_Face_Axi::completer(), Op_Dift_VDF_var_Face::completer(), Op_Dift_VDF_var_Elem_Axi::completer(), Op_Dift_VDF_var_Elem::completer(), Op_Dift_VDF_Multi_inco_var_Elem_Axi::completer(), Op_Dift_VDF_Multi_inco_var_Elem::completer(), Op_Dift_VDF_Multi_inco_Elem_Axi::completer(), Op_Dift_VDF_Multi_inco_Elem::completer(), Op_Dift_VDF_Face_Axi::completer(), Op_Dift_VDF_Face::completer(), Op_Dift_VDF_Elem_Axi::completer(), Op_Dift_VDF_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_CoviMAC_Face::completer(), Op_Diff_CoviMAC_Elem::completer(), Champ_P1NC_implementation::filtrer_L2(), Champ_Generique_Tparoi_VEF::get_champ(), Traitement_particulier_NS_Profils::lire(), PlaqThVDF::mettre_a_jour(), Champ_Inc_base::mettre_a_jour(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), Turbulence_paroi_scal::readOn(), Modele_turbulence_scal_base::readOn(), Op_Diff_PolyMAC_base::update_nu(), and Op_Diff_CoviMAC_base::update_nu_invh().
Objet_U & Ref_Objet_U::valeur () [inline]
Definition at line 92 of file Ref_Objet_U.h.
Member Data Documentation
const Type_info Ref_Objet_U::info_obj [static]
Reimplemented from Ref_.
Definition at line 92 of file Ref_Objet_U.h.
Objet_U* Ref_Objet_U::pointeur_ [private]
Definition at line 92 of file Ref_Objet_U.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Ref_Objet_U.h
src/Kernel/Utilitaires/Ref_Objet_U.cpp