TRUST: Ref_Zone_PolyMAC Class Reference
Ref_Zone_PolyMAC Class Reference
#include <Ref_Zone_PolyMAC.h>
Public Member Functions
~Ref_Zone_PolyMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Zone_PolyMAC ()
Ref_Zone_PolyMAC (const Zone_PolyMAC &)
Ref_Zone_PolyMAC (const Ref_Zone_PolyMAC &)
const Zone_PolyMAC & valeur () const
Zone_PolyMAC & valeur ()
const Zone_PolyMAC * operator-> () const
Zone_PolyMAC * operator-> ()
const Ref_Zone_PolyMAC & operator= (const Zone_PolyMAC &)
const Ref_Zone_PolyMAC & operator= (const Ref_Zone_PolyMAC &)
operator const Zone_PolyMAC & () const
operator Zone_PolyMAC & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Zone_PolyMAC & self_cast (Objet_U &)
static const Ref_Zone_PolyMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Zone_PolyMAC * pointeur_
Detailed Description
Definition at line 28 of file Ref_Zone_PolyMAC.h.
Constructor & Destructor Documentation
Ref_Zone_PolyMAC::~Ref_Zone_PolyMAC ()
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
Ref_Zone_PolyMAC::Ref_Zone_PolyMAC ()
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
Ref_Zone_PolyMAC::Ref_Zone_PolyMAC (const Zone_PolyMAC & t)
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
Ref_Zone_PolyMAC::Ref_Zone_PolyMAC (const Ref_Zone_PolyMAC & t)
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
Member Function Documentation
Objet_U * Ref_Zone_PolyMAC::cree_instance () [static]
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
int Ref_Zone_PolyMAC::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
const Type_info * Ref_Zone_PolyMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
const Type_info & Ref_Zone_PolyMAC::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
const Type_info * Ref_Zone_PolyMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
Ref_Zone_PolyMAC::operator const Zone_PolyMAC & () const
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
Ref_Zone_PolyMAC::operator Zone_PolyMAC & ()
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
const Zone_PolyMAC * Ref_Zone_PolyMAC::operator-> () const [inline]
Definition at line 28 of file Ref_Zone_PolyMAC.h.
Zone_PolyMAC * Ref_Zone_PolyMAC::operator-> () [inline]
Definition at line 28 of file Ref_Zone_PolyMAC.h.
const Ref_Zone_PolyMAC & Ref_Zone_PolyMAC::operator= (const Ref_Zone_PolyMAC & t)
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
const Ref_Zone_PolyMAC & Ref_Zone_PolyMAC::operator= (const Zone_PolyMAC & t)
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
Sortie & Ref_Zone_PolyMAC::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
Entree & Ref_Zone_PolyMAC::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
const Ref_Zone_PolyMAC & Ref_Zone_PolyMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
Ref_Zone_PolyMAC & Ref_Zone_PolyMAC::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
void Ref_Zone_PolyMAC::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
unsigned Ref_Zone_PolyMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Zone_PolyMAC.cpp.
const Zone_PolyMAC & Ref_Zone_PolyMAC::valeur () const [inline]
Definition at line 28 of file Ref_Zone_PolyMAC.h.
Referenced by Terme_Source_Qdm_Face_PolyMAC::ajouter(), Terme_Source_Decroissance_Radioactive_P0_PolyMAC::ajouter(), Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC::ajouter(), Terme_Boussinesq_PolyMAC_Face::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), Perte_Charge_PolyMAC::ajouter(), DP_Impose_PolyMAC_Face::ajouter(), Op_Grad_PolyMAC_Face::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Diff_PolyMAC_Face::ajouter(), Op_Diff_PolyMAC_Elem::ajouter(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter(), Masse_PolyMAC_Elem::ajouter_masse(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Masse_PolyMAC_Face::appliquer_impl(), Masse_PolyMAC_Elem::appliquer_impl(), Assembleur_P_PolyMAC::assembler_mat(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_base::completer(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Terme_Source_Decroissance_Radioactive_P0_PolyMAC::contribuer_a_avec(), Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC::contribuer_a_avec(), Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec(), Perte_Charge_PolyMAC::contribuer_a_avec(), DP_Impose_PolyMAC_Face::contribuer_a_avec(), Op_Grad_PolyMAC_Face::contribuer_a_avec(), Op_Div_PolyMAC::contribuer_a_avec(), Op_Diff_PolyMAC_Face::contribuer_a_avec(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Op_Conv_EF_Stab_PolyMAC_Face::contribuer_a_avec(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Masse_PolyMAC_Elem::dimensionner(), Op_Grad_PolyMAC_Face::dimensionner(), Op_Div_PolyMAC::dimensionner(), Op_Diff_PolyMAC_Face::dimensionner(), Op_Diff_PolyMAC_Elem::dimensionner(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Op_Grad_PolyMAC_Face::impr(), Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_PolyMAC::mettre_a_jour(), Assembleur_P_PolyMAC::modifier_secmem(), Champ_Fonc_P0_PolyMAC::moyenne(), Op_Diff_PolyMAC_Elem::update_delta(), Op_Diff_PolyMAC_Elem::update_delta_int(), Op_Diff_PolyMAC_base::update_nu(), Champ_Fonc_P0_PolyMAC::valeur_au_bord(), Op_Div_PolyMAC::volumique(), Iterateur_PolyMAC_base::zone(), Assembleur_P_PolyMAC::zone_dis_base(), Champ_Fonc_P0_PolyMAC::zone_dis_base(), and Op_Grad_PolyMAC_Face::zone_PolyMAC().
Zone_PolyMAC & Ref_Zone_PolyMAC::valeur () [inline]
Definition at line 28 of file Ref_Zone_PolyMAC.h.
Member Data Documentation
const Type_info Ref_Zone_PolyMAC::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Zone_PolyMAC.h.
Zone_PolyMAC* Ref_Zone_PolyMAC::pointeur_ [private]
Definition at line 28 of file Ref_Zone_PolyMAC.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Zones/Ref_Zone_PolyMAC.h
src/PolyMAC/Zones/Ref_Zone_PolyMAC.cpp