TRUST: Polyedre_PolyMAC Class Reference
Polyedre_PolyMAC Class Reference
#include <Polyedre_PolyMAC.h>
Public Member Functions
Polyedre_PolyMAC ()
~Polyedre_PolyMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Polyedre_PolyMAC & self_cast (Objet_U &)
static const Polyedre_PolyMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 29 of file Polyedre_PolyMAC.h.
Constructor & Destructor Documentation
Polyedre_PolyMAC::Polyedre_PolyMAC ()
Definition at line 30 of file Polyedre_PolyMAC.cpp.
Polyedre_PolyMAC::~Polyedre_PolyMAC ()
Definition at line 30 of file Polyedre_PolyMAC.cpp.
Member Function Documentation
Objet_U * Polyedre_PolyMAC::cree_instance () [static]
Definition at line 30 of file Polyedre_PolyMAC.cpp.
int Polyedre_PolyMAC::duplique () const [virtual]
Implements Elem_PolyMAC_base.
Definition at line 30 of file Polyedre_PolyMAC.cpp.
const Type_info * Polyedre_PolyMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_PolyMAC_base.
Definition at line 30 of file Polyedre_PolyMAC.cpp.
const Type_info * Polyedre_PolyMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_PolyMAC_base.
Definition at line 30 of file Polyedre_PolyMAC.cpp.
void Polyedre_PolyMAC::normale (int num_Face, DoubleTab & Face_normales, const IntTab & Face_sommets, const IntTab & Face_voisins, const IntTab & elem_faces, const Zone & zone_geom) const [virtual]
Implements Elem_PolyMAC_base.
Definition at line 45 of file Polyedre_PolyMAC.cpp.
References Domaine::coord_sommets(), IntTab::dimension(), Zone::domaine(), Zone::les_elems(), Vecteur3::produit_scalaire(), and Vecteur3::produit_vectoriel().
{
// Cerr << " num_Face " << num_Face << finl;
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
// Cerr << "les face sommet " << Face_sommets << finl;
  int nb_som_face_max= Face_sommets.dimension(1);
  int n0 = Face_sommets(num_Face,0);
  const IntTab& elem=zone_geom.les_elems();
  Vecteur3 n(0,0,0);
  Vecteur3 moinsS0(les_coords(n0,0),les_coords(n0,1),les_coords(n0,2));
  moinsS0*=-1;
  for (int s=1; s<nb_som_face_max-1 ; s++)
    {
      int n1 = Face_sommets(num_Face,s);
      int n2 = Face_sommets(num_Face,s+1);
      if (n2<0)
        {
          break;
        }
      Vecteur3 S1(les_coords(n1,0),les_coords(n1,1),les_coords(n1,2));
      Vecteur3 S2(les_coords(n2,0),les_coords(n2,1),les_coords(n2,2));
      S1+=moinsS0;
      S2+=moinsS0;
      Vecteur3 nTr;
      Vecteur3::produit_vectoriel(S1,S2,nTr);
      n+=nTr;
    }
  n*=0.5;
  /*
    int elem1=Face_voisins(num_Face,0);
  DoubleVect xp;
  ref_cast(Poly_geom_base,zone_geom.type_elem().valeur()).calculer_un_centre_gravite(elem1,xp);
  Vecteur3 M(xp(0),xp(1),xp(2));
  */
// on prend un point a l'interieur (pas le cg trop long)
  int num_poly=Face_voisins(num_Face,0);
  Vecteur3 xg(0,0,0);
  int nb_som_max=elem.dimension(1);
  int nb_som_reel;
  for (nb_som_reel=0; nb_som_reel<nb_som_max; nb_som_reel++)
    {
      int ns=elem(num_poly,nb_som_reel);
      if (ns<0)
        break;
      Vecteur3 S(les_coords(ns,0),les_coords(ns,1),les_coords(ns,2));
      xg+=S;
    }
  xg*=1./nb_som_reel;
  xg+=moinsS0;
  double prod_scal=Vecteur3::produit_scalaire(n,xg);
  if ( (prod_scal) > 0 )
    {
      n*=-1;
    }
  Face_normales(num_Face,0) = n[0];
  Face_normales(num_Face,1) = n[1];
  Face_normales(num_Face,2) = n[2];
// double s=sqrt(Vecteur3::produit_scalaire(n,n));
// Cerr << "Face_normales " << num_Face<< " s "<< s << finl;
// assert(s>0);
// Cerr << "Face_normales " << num_Face<< " s "<< s << finl;
}
Sortie & Polyedre_PolyMAC::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Elem_PolyMAC_base.
Definition at line 35 of file Polyedre_PolyMAC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Polyedre_PolyMAC::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Elem_PolyMAC_base.
Definition at line 40 of file Polyedre_PolyMAC.cpp.
{
  return s ;
}
Polyedre_PolyMAC & Polyedre_PolyMAC::self_cast (Objet_U & r) [static]
Reimplemented from Elem_PolyMAC_base.
Definition at line 30 of file Polyedre_PolyMAC.cpp.
const Polyedre_PolyMAC & Polyedre_PolyMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Elem_PolyMAC_base.
Definition at line 30 of file Polyedre_PolyMAC.cpp.
unsigned Polyedre_PolyMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 30 of file Polyedre_PolyMAC.cpp.
Member Data Documentation
const Type_info Polyedre_PolyMAC::info_obj [static]
Reimplemented from Elem_PolyMAC_base.
Definition at line 32 of file Polyedre_PolyMAC.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Zones/Polyedre_PolyMAC.h
src/PolyMAC/Zones/Polyedre_PolyMAC.cpp