TRUST: Eval_Conv_VDF_Face< DERIVED_T > Class Template Reference
Eval_Conv_VDF_Face< DERIVED_T > Class Template Reference
templates specializations ici ;)
#include <Eval_Conv_VDF_Face.h>
Public Member Functions
template<Type_Flux_Fa7 Fa7_Type, typename Type_Double >
enable_if_t< Fa7_Type==Type_Flux_Fa7::SORTIE_LIBRE, void > flux_fa7 (const DoubleTab &, int, const Neumann_sortie_libre &, int, Type_Double &) const
template<Type_Flux_Fa7 Fa7_Type, typename Type_Double >
enable_if_t< Fa7_Type==Type_Flux_Fa7::ELEM, void > flux_fa7 (const DoubleTab &, int, int, int, Type_Double &) const
template<Type_Flux_Arete Arete_Type, typename Type_Double >
enable_if_t< Arete_Type==Type_Flux_Arete::INTERNE, void > flux_arete (const DoubleTab &, int, int, int, int, Type_Double &) const
template<Type_Flux_Arete Arete_Type, typename Type_Double >
enable_if_t< Arete_Type==Type_Flux_Arete::MIXTE, void > flux_arete (const DoubleTab &, int, int, int, int, Type_Double &) const
template<Type_Flux_Arete Arete_Type, typename Type_Double >
enable_if_t<(Arete_Type==Type_Flux_Arete::PAROI||Arete_Type==Type_Flux_Arete::SYMETRIE||Arete_Type==Type_Flux_Arete::SYMETRIE_PAROI), void > flux_arete (const DoubleTab &, int, int, int, int, Type_Double &) const
template<Type_Flux_Arete Arete_Type, typename Type_Double >
enable_if_t< Arete_Type==Type_Flux_Arete::FLUIDE||Arete_Type==Type_Flux_Arete::SYMETRIE_FLUIDE||Arete_Type==Type_Flux_Arete::PAROI_FLUIDE, void > flux_arete (const DoubleTab &, int, int, int, int, Type_Double &, Type_Double &) const
template<Type_Flux_Arete Arete_Type, typename Type_Double >
enable_if_t< Arete_Type==Type_Flux_Arete::PERIODICITE, void > flux_arete (const DoubleTab &, int, int, int, int, Type_Double &, Type_Double &) const
template<Type_Flux_Arete Arete_Type, typename Type_Double >
enable_if_t< Arete_Type==Type_Flux_Arete::COIN_FLUIDE, void > flux_arete (const DoubleTab &, int, int, int, int, Type_Double &, Type_Double &) const
template<Type_Flux_Fa7 Fa7_Type, typename Type_Double >
enable_if_t< Fa7_Type==Type_Flux_Fa7::SORTIE_LIBRE, void > coeffs_fa7 (int, const Neumann_sortie_libre &, Type_Double &, Type_Double &) const
template<Type_Flux_Fa7 Fa7_Type, typename Type_Double >
enable_if_t< Fa7_Type==Type_Flux_Fa7::ELEM, void > coeffs_fa7 (int, int, int, Type_Double &, Type_Double &) const
template<Type_Flux_Arete Arete_Type, typename Type_Double >
enable_if_t< Arete_Type==Type_Flux_Arete::INTERNE||Arete_Type==Type_Flux_Arete::MIXTE||Arete_Type==Type_Flux_Arete::PERIODICITE, void > coeffs_arete (int, int, int, int, Type_Double &, Type_Double &) const
template<Type_Flux_Arete Arete_Type, typename Type_Double >
enable_if_t< Arete_Type==Type_Flux_Arete::FLUIDE||Arete_Type==Type_Flux_Arete::SYMETRIE_FLUIDE||Arete_Type==Type_Flux_Arete::PAROI_FLUIDE||Arete_Type==Type_Flux_Arete::COIN_FLUIDE, void > coeffs_arete (int, int, int, int, Type_Double &, Type_Double &, Type_Double &) const
template<Type_Flux_Arete Arete_Type, typename Type_Double >
enable_if_t<(Arete_Type==Type_Flux_Arete::PAROI||Arete_Type==Type_Flux_Arete::SYMETRIE||Arete_Type==Type_Flux_Arete::SYMETRIE_PAROI), void > coeffs_arete (int, int, int, int, Type_Double &, Type_Double &, Type_Double &) const
template<Type_Flux_Fa7 Fa7_Type, typename Type_Double >
enable_if_t< Fa7_Type==Type_Flux_Fa7::SORTIE_LIBRE, void > secmem_fa7 (int, const Neumann_sortie_libre &, int, Type_Double &) const
template<Type_Flux_Fa7 Fa7_Type, typename Type_Double >
enable_if_t< Fa7_Type==Type_Flux_Fa7::ELEM, void > secmem_fa7 (int, int, int, Type_Double &) const
template<Type_Flux_Arete Arete_Type, typename Type_Double >
enable_if_t<(Arete_Type==Type_Flux_Arete::INTERNE||Arete_Type==Type_Flux_Arete::MIXTE||Arete_Type==Type_Flux_Arete::PAROI||Arete_Type==Type_Flux_Arete::SYMETRIE||Arete_Type==Type_Flux_Arete::SYMETRIE_PAROI), void > secmem_arete (int, int, int, int, Type_Double &) const
template<Type_Flux_Arete Arete_Type, typename Type_Double >
enable_if_t< Arete_Type==Type_Flux_Arete::FLUIDE||Arete_Type==Type_Flux_Arete::SYMETRIE_FLUIDE||Arete_Type==Type_Flux_Arete::PAROI_FLUIDE||Arete_Type==Type_Flux_Arete::COIN_FLUIDE, void > secmem_arete (int, int, int, int, Type_Double &, Type_Double &) const
template<Type_Flux_Arete Arete_Type, typename Type_Double >
enable_if_t< Arete_Type==Type_Flux_Arete::PERIODICITE, void > secmem_arete (int, int, int, int, Type_Double &, Type_Double &) const
Public Member Functions inherited from Eval_VDF_Face
void associer_inconnue (const Champ_base &)
Static Public Attributes
static constexpr bool IS_AMONT = false
static constexpr bool IS_CENTRE = false
static constexpr bool IS_CENTRE4 = false
static constexpr bool IS_QUICK = false
static constexpr bool IS_AXI = false
static constexpr bool CALC_FA7_SORTIE_LIB = true
static constexpr bool CALC_ARR_PAR = false
static constexpr bool CALC_ARR_SYMM_PAR = false
Static Public Attributes inherited from Eval_VDF_Face
static constexpr bool CALC_FA7_SORTIE_LIB = false
static constexpr bool CALC_ARR_FL = true
static constexpr bool CALC_ARR_BORD = true
static constexpr bool CALC_ARR_COIN_FL = false
static constexpr bool CALC_ARR_INT = true
static constexpr bool CALC_ARR_MIXTE = true
static constexpr bool CALC_ARR_PERIO = true
static constexpr bool CALC_ARR_PAR_FL = true
static constexpr bool CALC_ARR_PAR = true
static constexpr bool CALC_ARR_SYMM_PAR = true
static constexpr bool CALC_ARR_SYMM_FL = true
static constexpr bool CALC_ARR_SYMM = false
Private Member Functions
template<typename Type_Double >
void fill_coeffs_proto (const double, const double, Type_Double &, Type_Double &) const
int premiere_face_bord () const
int orientation (int face) const
int elem_ (int i, int j) const
int face_amont_princ_ (int num_face, int i) const
int face_amont_conj_ (int num_face, int i, int k) const
double dt_vitesse (int face) const
double surface_porosite (int face) const
double surface (int face) const
double porosite (int face) const
double dim_face_ (int n1, int k) const
double dim_elem_ (int n1, int k) const
double dist_face_ (int n1, int n2, int k) const
double dist_face_period_ (int n1, int n2, int k) const
double dist_elem_period_ (int n1, int n2, int k) const
const Zone_Cl_VDF & la_zcl () const
double conv_quick_sharp_plus_ (const double psc, const double vit_0, const double vit_1, const double vit_0_0, const double dx, const double dm, const double dxam) const
double conv_quick_sharp_moins_ (const double psc, const double vit_0, const double vit_1, const double vit_1_1, const double dx, const double dm, const double dxam) const
double conv_centre_ (const double psc, const double vit_0_0, const double vit_0, const double vit_1, const double vit1_1, double g1, double g2, double g3, double g4) const
void calcul_g_ (const double dxam, const double dx, const double dxav, double &g1, double &g2, double &g3, double &g4) const
Additional Inherited Members
Protected Attributes inherited from Eval_VDF_Face
Ref_Champ_base inconnue
Detailed Description
template<typename DERIVED_T>
class Eval_Conv_VDF_Face< DERIVED_T >
templates specializations ici ;)
Definition at line 23 of file Eval_Conv_VDF_Face.h.
Member Function Documentation
calcul_g_()
template<typename DERIVED_T > void Eval_Conv_VDF_Face< DERIVED_T >::calcul_g_ (const double dxam, const double dx, const double dxav, double & g1, double & g2, double & g3, double & g4) const inline private
Definition at line 137 of file Eval_Conv_VDF_Face.h.
  { static_cast<const DERIVED_T *>(this)->calcul_g(dxam,dx,dxav,g1,g2,g3,g4); }
coeffs_arete() [1/3]
template<typename DERIVED_T > template<Type_Flux_Arete Arete_Type, typename Type_Double > enable_if_t< Arete_Type==Type_Flux_Arete::INTERNE||Arete_Type==Type_Flux_Arete::MIXTE||Arete_Type==Type_Flux_Arete::PERIODICITE, void > Eval_Conv_VDF_Face< DERIVED_T >::coeffs_arete (int fac1, int fac2, int fac3, int fac4, Type_Double & aii, Type_Double & ajj) const inline
Definition at line 370 of file Eval_Conv_VDF_Face.tpp.
{
  assert(aii.size_array() == ajj.size_array());
  if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_AXI || DERIVED_T::IS_CENTRE4) return;
  const double psc = 0.25*((dt_vitesse(fac1)*porosite(fac1)+dt_vitesse(fac2)*porosite(fac2))*(surface(fac1)+surface(fac2)));
  fill_coeffs_proto<Type_Double>(psc,psc,aii,ajj);
}
coeffs_arete() [2/3]
template<typename DERIVED_T > template<Type_Flux_Arete Arete_Type, typename Type_Double > enable_if_t< Arete_Type==Type_Flux_Arete::FLUIDE||Arete_Type==Type_Flux_Arete::SYMETRIE_FLUIDE||Arete_Type==Type_Flux_Arete::PAROI_FLUIDE||Arete_Type==Type_Flux_Arete::COIN_FLUIDE, void > Eval_Conv_VDF_Face< DERIVED_T >::coeffs_arete (int fac1, int fac2, int fac3, int signe, Type_Double & aii1_2, Type_Double & aii3_4, Type_Double & ajj1_2) const inline
Definition at line 381 of file Eval_Conv_VDF_Face.tpp.
{
  assert(aii1_2.size_array() == aii3_4.size_array() && aii1_2.size_array() == ajj1_2.size_array());
  if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_AXI || DERIVED_T::IS_CENTRE4) return;
  constexpr bool is_COIN = (Arete_Type == Type_Flux_Arete::COIN_FLUIDE);
  const int ncomp = aii1_2.size_array();
  double psc = is_COIN ? 0.5*dt_vitesse(fac1)*porosite(fac1)*surface(fac1) : 0.25 * ((dt_vitesse(fac1)*porosite(fac1)+dt_vitesse(fac2)*porosite(fac2))*(surface(fac1)+surface(fac2)));
  if ((psc*signe)>0)
    for (int k = 0; k < ncomp; k++) aii3_4[k] = psc ;
  else for (int k = 0; k < ncomp; k++) aii3_4[k] = 0.;
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  fill_coeffs_proto<Type_Double>(psc,psc,aii1_2,ajj1_2);
}
References COIN_FLUIDE.
coeffs_arete() [3/3]
template<typename DERIVED_T > template<Type_Flux_Arete Arete_Type, typename Type_Double > enable_if_t<(Arete_Type==Type_Flux_Arete::PAROI||Arete_Type==Type_Flux_Arete::SYMETRIE||Arete_Type==Type_Flux_Arete::SYMETRIE_PAROI), void > Eval_Conv_VDF_Face< DERIVED_T >::coeffs_arete (int , int , int , int , Type_Double & , Type_Double & , Type_Double &) const inline
Definition at line 83 of file Eval_Conv_VDF_Face.h.
{ /* do nothing */ }
coeffs_fa7() [1/2]
template<typename DERIVED_T > template<Type_Flux_Fa7 Fa7_Type, typename Type_Double > enable_if_t< Fa7_Type==Type_Flux_Fa7::SORTIE_LIBRE, void > Eval_Conv_VDF_Face< DERIVED_T >::coeffs_fa7 (int face, const Neumann_sortie_libre & la_cl, Type_Double & aii, Type_Double & ajj) const inline
Definition at line 349 of file Eval_Conv_VDF_Face.tpp.
{
  assert(aii.size_array() == ajj.size_array());
  if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_AXI || DERIVED_T::IS_CENTRE4) return;
  const double psc = dt_vitesse(face)*surface(face)*porosite(face);
  fill_coeffs_proto<Type_Double>(psc,psc,aii,ajj);
}
coeffs_fa7() [2/2]
template<typename DERIVED_T > template<Type_Flux_Fa7 Fa7_Type, typename Type_Double > enable_if_t< Fa7_Type==Type_Flux_Fa7::ELEM, void > Eval_Conv_VDF_Face< DERIVED_T >::coeffs_fa7 (int , int fac1, int fac2, Type_Double & aii, Type_Double & ajj) const inline
Definition at line 359 of file Eval_Conv_VDF_Face.tpp.
{
  assert(aii.size_array() == ajj.size_array());
  if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_AXI || DERIVED_T::IS_CENTRE4) return;
  const double psc = 0.25*(dt_vitesse(fac1)+dt_vitesse(fac2))*(surface(fac1)+surface(fac2)), psc1 = psc*porosite(fac1), psc2 = psc*porosite(fac2);
  fill_coeffs_proto<Type_Double>(psc1,psc2,aii,ajj);
}
conv_centre_()
template<typename DERIVED_T > double Eval_Conv_VDF_Face< DERIVED_T >::conv_centre_ (const double psc, const double vit_0_0, const double vit_0, const double vit_1, const double vit1_1, double g1, double g2, double g3, double g4) const inline private
Definition at line 134 of file Eval_Conv_VDF_Face.h.
  { return static_cast<const DERIVED_T *>(this)->conv_centre(psc,vit_0_0,vit_0,vit_1,vit1_1,g1,g2,g3,g4); }
conv_quick_sharp_moins_()
template<typename DERIVED_T > double Eval_Conv_VDF_Face< DERIVED_T >::conv_quick_sharp_moins_ (const double psc, const double vit_0, const double vit_1, const double vit_1_1, const double dx, const double dm, const double dxam) const inline private
Definition at line 131 of file Eval_Conv_VDF_Face.h.
  { return static_cast<const DERIVED_T *>(this)->conv_quick_sharp_moins(psc,vit_0,vit_1,vit_1_1,dx,dm,dxam); }
conv_quick_sharp_plus_()
template<typename DERIVED_T > double Eval_Conv_VDF_Face< DERIVED_T >::conv_quick_sharp_plus_ (const double psc, const double vit_0, const double vit_1, const double vit_0_0, const double dx, const double dm, const double dxam) const inline private
Definition at line 128 of file Eval_Conv_VDF_Face.h.
  { return static_cast<const DERIVED_T *>(this)->conv_quick_sharp_plus(psc,vit_0,vit_1,vit_0_0,dx,dm,dxam); }
dim_elem_()
template<typename DERIVED_T > double Eval_Conv_VDF_Face< DERIVED_T >::dim_elem_ (int n1, int k) const inline private
Definition at line 122 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->dim_elem(n1,k); }
dim_face_()
template<typename DERIVED_T > double Eval_Conv_VDF_Face< DERIVED_T >::dim_face_ (int n1, int k) const inline private
Definition at line 121 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->dim_face(n1,k); }
dist_elem_period_()
template<typename DERIVED_T > double Eval_Conv_VDF_Face< DERIVED_T >::dist_elem_period_ (int n1, int n2, int k) const inline private
Definition at line 125 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->dist_elem_period(n1,n2,k); }
dist_face_()
template<typename DERIVED_T > double Eval_Conv_VDF_Face< DERIVED_T >::dist_face_ (int n1, int n2, int k) const inline private
Definition at line 123 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->dist_face(n1,n2,k); }
dist_face_period_()
template<typename DERIVED_T > double Eval_Conv_VDF_Face< DERIVED_T >::dist_face_period_ (int n1, int n2, int k) const inline private
Definition at line 124 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->dist_face_period(n1,n2,k); }
dt_vitesse()
template<typename DERIVED_T > double Eval_Conv_VDF_Face< DERIVED_T >::dt_vitesse (int face) const inline private
Definition at line 117 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->get_dt_vitesse(face); }
elem_()
template<typename DERIVED_T > int Eval_Conv_VDF_Face< DERIVED_T >::elem_ (int i, int j) const inline private
Definition at line 114 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->get_elem(i,j); }
face_amont_conj_()
template<typename DERIVED_T > int Eval_Conv_VDF_Face< DERIVED_T >::face_amont_conj_ (int num_face, int i, int k) const inline private
Definition at line 116 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->face_amont_conj(num_face,i,k); }
face_amont_princ_()
template<typename DERIVED_T > int Eval_Conv_VDF_Face< DERIVED_T >::face_amont_princ_ (int num_face, int i) const inline private
Definition at line 115 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->face_amont_princ(num_face,i); }
fill_coeffs_proto()
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Face< DERIVED_T >::fill_coeffs_proto (const double psc1, const double psc2, Type_Double & A, Type_Double & B) const inline private
Definition at line 399 of file Eval_Conv_VDF_Face.tpp.
{
  if (psc1 > 0)
    {
      for (int k = 0; k < A.size_array(); k++) A[k] = psc1;
      for (int k = 0; k < B.size_array(); k++) B[k] = 0.;
    }
  else
    {
      for (int k = 0; k < A.size_array(); k++) A[k] = 0.;
      for (int k = 0; k < B.size_array(); k++) B[k] = -psc2;
    }
}
flux_arete() [1/6]
template<typename DERIVED_T > template<Type_Flux_Arete Arete_Type, typename Type_Double > enable_if_t< Arete_Type==Type_Flux_Arete::INTERNE, void > Eval_Conv_VDF_Face< DERIVED_T >::flux_arete (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, Type_Double & flux) const inline
< Schema centre 2 (pas assez de faces)
< Schema Centre 4
< IS_QUICK
< Schema amont
< Schema quick
< (psc <= 0)
< Schema amont
< Schema quick
Definition at line 122 of file Eval_Conv_VDF_Face.tpp.
{
  const int ncomp = flux.size_array();
  const double psc = 0.25 * ((dt_vitesse(fac1)*porosite(fac1)+dt_vitesse(fac2)*porosite(fac2))*(surface(fac1)+surface(fac2)));
  if (DERIVED_T::IS_AMONT)
    {
      if (psc>0)
        for (int k = 0; k < ncomp; k++) flux[k] = -psc*inco(fac3,k);
      else for (int k = 0; k < ncomp; k++) flux[k] = -psc*inco(fac4,k);
    }
  else if (DERIVED_T::IS_CENTRE)
    for (int k = 0; k < ncomp; k++) flux[k] = -0.5*(inco(fac3,k)+inco(fac4,k))*psc ;
  else
    {
      const int ori = orientation(fac1), num0_0 = face_amont_conj_(fac3,ori,0), num1_1 = face_amont_conj_(fac4,ori,1);
      if (DERIVED_T::IS_CENTRE4)
        {
          if ( (num0_0 == -1)||(num1_1== -1) )
            for (int k = 0; k < ncomp; k++) flux[k] = -0.5*(inco(fac3,k)+inco(fac4,k))*psc ; //!< Schema centre 2 (pas assez de faces)
          else  //!< Schema Centre 4
            {
              Type_Double vit_0(ncomp), vit_0_0(ncomp), vit_1_1(ncomp), vit_1(ncomp);
// Inutile de prendre dist_face_period pour dx car fac3 et fac4 ne peuvent etre periodiques (arete interne)
              const double dx = dist_face_(fac3,fac4,ori), dxam = dist_face_period_(num0_0,fac3,ori), dxav = dist_face_period_(fac4,num1_1,ori);
              double g1, g2, g3, g4;
              calcul_g_(dxam,dx,dxav,g1,g2,g3,g4);
              for (int k = 0; k < ncomp; k++)
                {
                  vit_0_0[k] = inco(num0_0,k);
                  vit_0[k] = inco(fac3,k);
                  vit_1[k] = inco(fac4,k);
                  vit_1_1[k] = inco(num1_1,k);
                  flux[k] = -conv_centre_(psc,vit_0_0[k],vit_0[k],vit_1[k],vit_1_1[k],g1,g2,g3,g4);
                }
            }
        }
      else //!< IS_QUICK
        {
          if (psc > 0)
            {
              if (num0_0 == -1)
                for (int k = 0; k < ncomp; k++) flux[k] = -psc*inco(fac3,k); //!< Schema amont
              else //!< Schema quick
                {
                  Type_Double vit_0(ncomp), vit_0_0(ncomp), vit_1(ncomp);
                  const double dx = dist_face_period_(fac3,fac4,ori), dm = dim_face_(fac3,ori), dxam = dist_face_period_(num0_0,fac3,ori);
                  for (int k = 0; k < ncomp; k++)
                    {
                      vit_0[k] = inco(fac3,k);
                      vit_1[k] = inco(fac4,k);
                      vit_0_0[k] = inco(num0_0,k);
                      flux[k] = -conv_quick_sharp_plus_(psc,vit_0[k],vit_1[k],vit_0_0[k],dx,dm,dxam);
                    }
                }
            }
          else //!< (psc <= 0)
            {
              if (num1_1 == -1)
                for (int k = 0; k < ncomp; k++) flux[k] = -psc*inco(fac4,k); //!< Schema amont
              else //!< Schema quick
                {
                  Type_Double vit_0(ncomp), vit_1(ncomp), vit_1_1(ncomp);
                  const double dx = dist_face_period_(fac3,fac4,ori), dm = dim_face_(fac4,ori), dxam = dist_face_period_(fac4,num1_1,ori);
                  for (int k = 0; k < ncomp; k++)
                    {
                      vit_0[k] = inco(fac3,k);
                      vit_1[k] = inco(fac4,k);
                      vit_1_1[k] = inco(num1_1,k);
                      flux[k] = -conv_quick_sharp_moins_(psc,vit_0[k],vit_1[k],vit_1_1[k],dx,dm,dxam);
                    }
                }
            }
        }
    }
}
flux_arete() [2/6]
template<typename DERIVED_T > template<Type_Flux_Arete Arete_Type, typename Type_Double > enable_if_t< Arete_Type==Type_Flux_Arete::MIXTE, void > Eval_Conv_VDF_Face< DERIVED_T >::flux_arete (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, Type_Double & flux) const inline
Definition at line 199 of file Eval_Conv_VDF_Face.tpp.
{
  const double psc = 0.25*((dt_vitesse(fac1)*porosite(fac1)+dt_vitesse(fac2)*porosite(fac2))*(surface(fac1)+surface(fac2)));
  if (DERIVED_T::IS_CENTRE)
    for (int k = 0; k < flux.size_array(); k++) flux[k] = -psc*0.5*(inco(fac3,k)+inco(fac4,k));
  else
    {
      if (psc>0)
        for (int k = 0; k < flux.size_array(); k++) flux[k] = -psc*inco(fac3,k);
      else for (int k = 0; k < flux.size_array(); k++) flux[k] = -psc*inco(fac4,k);
    }
}
flux_arete() [3/6]
template<typename DERIVED_T > template<Type_Flux_Arete Arete_Type, typename Type_Double > enable_if_t<(Arete_Type==Type_Flux_Arete::PAROI||Arete_Type==Type_Flux_Arete::SYMETRIE||Arete_Type==Type_Flux_Arete::SYMETRIE_PAROI), void > Eval_Conv_VDF_Face< DERIVED_T >::flux_arete (const DoubleTab & , int , int , int , int , Type_Double &) const inline
Definition at line 51 of file Eval_Conv_VDF_Face.h.
{ /* do nothing */ }
flux_arete() [4/6]
template<typename DERIVED_T > template<Type_Flux_Arete Arete_Type, typename Type_Double > enable_if_t< Arete_Type==Type_Flux_Arete::FLUIDE||Arete_Type==Type_Flux_Arete::SYMETRIE_FLUIDE||Arete_Type==Type_Flux_Arete::PAROI_FLUIDE, void > Eval_Conv_VDF_Face< DERIVED_T >::flux_arete (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, Type_Double & flux3, Type_Double & flux1_2) const inline
< TODO : FIXME : euh ? pourquoi ca ?
Definition at line 214 of file Eval_Conv_VDF_Face.tpp.
{
  assert(flux3.size_array() == flux1_2.size_array());
  constexpr bool is_SYM = (Arete_Type == Type_Flux_Arete::SYMETRIE_FLUIDE);
  if (DERIVED_T::IS_AXI && is_SYM) return;
  const int ncomp = flux3.size_array();
  double psc = 0.25*((dt_vitesse(fac1)*porosite(fac1)+dt_vitesse(fac2)*porosite(fac2))*(surface(fac1)+surface(fac2)));
  if ((psc*signe)>0)
    for (int k = 0; k < ncomp; k++) flux3[k] = -inco(fac3,k)*psc ;
  else
    {
      const int pfb = premiere_face_bord(), ori = orientation(fac3), rang1 = DERIVED_T::IS_QUICK ? fac1 : (fac1-pfb), rang2 = DERIVED_T::IS_QUICK ? fac2 :(fac2-pfb); //!< TODO : FIXME : euh ? pourquoi ca ?
      for (int k = 0; k < ncomp; k++)
        flux3[k] = -0.5*(Champ_Face_get_val_imp_face_bord_sym(inco,inconnue->temps(),rang1,ori,la_zcl())
                         +  Champ_Face_get_val_imp_face_bord_sym(inco,inconnue->temps(),rang2,ori,la_zcl()))*psc ;
    }
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (int k = 0; k < ncomp; k++) flux1_2[k] = -psc*inco(fac1,k);
  else for (int k = 0; k < ncomp; k++) flux1_2[k] = (DERIVED_T::IS_CENTRE || DERIVED_T::IS_CENTRE4) ? -psc*0.5*(inco(fac1,k)+inco(fac2,k)) : -psc*inco(fac2,k);
}
References Champ_Face_get_val_imp_face_bord_sym(), and SYMETRIE_FLUIDE.
flux_arete() [5/6]
template<typename DERIVED_T > template<Type_Flux_Arete Arete_Type, typename Type_Double > enable_if_t< Arete_Type==Type_Flux_Arete::PERIODICITE, void > Eval_Conv_VDF_Face< DERIVED_T >::flux_arete (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, Type_Double & flux3_4, Type_Double & flux1_2) const inline
< XXX : LOL
< Schema centre 2 (pas assez de faces)
< Schema Centre4
< Schema centre 2 (pas assez de faces)
< Schema Centre4
Definition at line 239 of file Eval_Conv_VDF_Face.tpp.
{
  assert(flux3_4.size_array() == flux1_2.size_array());
  if (DERIVED_T::IS_QUICK) //!< XXX : LOL
    {
      if (DERIVED_T::IS_AXI) return;
      flux_arete<Type_Flux_Arete::INTERNE>(inco,fac1,fac2,fac3,fac4,flux3_4);
      flux_arete<Type_Flux_Arete::INTERNE>(inco,fac3,fac4,fac1,fac2,flux1_2);
      return;
    }
  const int ncomp = flux3_4.size_array();
  double psc = 0.25*(dt_vitesse(fac1)*porosite(fac1)+dt_vitesse(fac2)*porosite(fac2))*(surface(fac1) +surface(fac2));
  if (DERIVED_T::IS_CENTRE)
    for (int k = 0; k < ncomp; k++) flux3_4[k] = -psc*0.5*(inco(fac3,k)+inco(fac4,k));
  else if (DERIVED_T::IS_CENTRE4)
    {
      const int ori = orientation(fac1), num0_0 = face_amont_conj_(fac3,ori,0),num1_1 = face_amont_conj_(fac4,ori,1);
      if ( (num0_0 == -1)||(num1_1== -1) )
        for (int k = 0; k < ncomp; k++) flux3_4[k] = -psc*0.5*(inco(fac3,k)+inco(fac4,k)); //!< Schema centre 2 (pas assez de faces)
      else //!< Schema Centre4
        {
          Type_Double vit_0(ncomp), vit_0_0(ncomp), vit_1_1(ncomp), vit_1(ncomp);
          const double dx = dist_face_period_(fac3,fac4,ori), dxam = dist_face_period_(num0_0,fac3,ori), dxav = dist_face_period_(fac4,num1_1,ori);
          double g1, g2, g3, g4;
          calcul_g_(dxam,dx,dxav,g1,g2,g3,g4);
          for (int k = 0; k < ncomp; k++)
            {
              vit_0_0[k] = inco(num0_0,k);
              vit_0[k] = inco(fac3,k);
              vit_1[k] = inco(fac4,k);
              vit_1_1[k] = inco(num1_1,k);
              flux3_4[k] = -conv_centre_(psc,vit_0_0[k],vit_0[k],vit_1[k],vit_1_1[k],g1,g2,g3,g4);
            }
        }
    }
  else
    {
      if (psc>0)
        for (int k = 0; k < ncomp; k++) flux3_4[k] = -psc*inco(fac3,k);
      else for (int k = 0; k < ncomp; k++) flux3_4[k] = -psc*inco(fac4,k);
    }
  psc = 0.25*(dt_vitesse(fac3)*porosite(fac3)+dt_vitesse(fac4)*porosite(fac4))*(surface(fac3)+surface(fac4));
  if (DERIVED_T::IS_CENTRE)
    for (int k = 0; k < ncomp; k++) flux1_2[k] = -psc*0.5*(inco(fac1,k)+inco(fac2,k));
  else if (DERIVED_T::IS_CENTRE4)
    {
      const int ori = orientation(fac3), num0_0 = face_amont_conj_(fac1,ori,0), num1_1 = face_amont_conj_(fac2,ori,1);
      if ( (num0_0 == -1)||(num1_1== -1) )
        for (int k=0; k<ncomp; k++)  flux1_2[k] = -psc*0.5*(inco(fac1,k)+inco(fac2,k)); //!< Schema centre 2 (pas assez de faces)
      else //!< Schema Centre4
        {
          Type_Double vit_0(ncomp), vit_0_0(ncomp), vit_1_1(ncomp), vit_1(ncomp);
          const double dx = dist_face_period_(fac1,fac2,ori),dxam = dist_face_period_(num0_0,fac1,ori), dxav = dist_face_period_(fac2,num1_1,ori);
          double g1, g2, g3, g4;
          calcul_g_(dxam,dx,dxav,g1,g2,g3,g4);
          for (int k = 0; k < ncomp; k++)
            {
              vit_0_0[k] = inco(num0_0,k);
              vit_0[k] = inco(fac1,k);
              vit_1[k] = inco(fac2,k);
              vit_1_1[k]=inco(num1_1,k);
              flux1_2[k] = -conv_centre_(psc,vit_0_0[k],vit_0[k],vit_1[k],vit_1_1[k],g1,g2,g3,g4);
            }
        }
    }
  else
    {
      if (psc>0)
        for (int k = 0; k < ncomp; k++) flux1_2[k] = -psc*inco(fac1,k);
      else for (int k = 0; k < ncomp; k++) flux1_2[k] = -psc*inco(fac2,k);
    }
}
flux_arete() [6/6]
template<typename DERIVED_T > template<Type_Flux_Arete Arete_Type, typename Type_Double > enable_if_t< Arete_Type==Type_Flux_Arete::COIN_FLUIDE, void > Eval_Conv_VDF_Face< DERIVED_T >::flux_arete (const DoubleTab & inco, int fac1, int , int fac3, int signe, Type_Double & flux3, Type_Double & flux1_2) const inline
Definition at line 316 of file Eval_Conv_VDF_Face.tpp.
{
  assert(flux3.size_array() == flux1_2.size_array());
  if (!DERIVED_T::IS_AMONT)
    {
      Cerr << "Flux_arete with Type_Flux_Arete::COIN_FLUIDE is only coded for amont scheme !" <<finl;
      Process::exit();
    }
  const int ncomp = flux3.size_array();
  double psc = 0.5 * dt_vitesse(fac1) * porosite(fac1) * surface(fac1);
  if ((psc * signe) > 0)
    for (int k = 0; k < ncomp; k++) flux3[k] = -inco(fac3,k) * psc;
  else
    {
      const int pfb = premiere_face_bord(), rang1 = (fac1 - pfb), ori = orientation(fac3);
      for (int k = 0; k < ncomp; k++) flux3[k] = -Champ_Face_get_val_imp_face_bord(inconnue->temps(), rang1, ori, la_zcl()) * psc;
    }
  psc = 0.5 * dt_vitesse(fac3) * surface(fac3) * porosite(fac3);
  if (psc > 0)
    for (int k = 0; k < ncomp; k++) flux1_2[k] = -psc * inco(fac1,k);
  else
    {
      const int pfb = premiere_face_bord(), rang3 = (fac3 - pfb), ori = orientation(fac1);
      for (int k = 0; k < ncomp; k++) flux1_2[k] = -psc * Champ_Face_get_val_imp_face_bord(inconnue->temps(), rang3, ori, la_zcl());
    }
}
References Cerr, Champ_Face_get_val_imp_face_bord(), Process::exit(), and finl.
flux_fa7() [1/2]
template<typename DERIVED_T > template<Type_Flux_Fa7 Fa7_Type, typename Type_Double > enable_if_t< Fa7_Type==Type_Flux_Fa7::SORTIE_LIBRE, void > Eval_Conv_VDF_Face< DERIVED_T >::flux_fa7 (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1, Type_Double & flux) const inline
< : -psc*la_cl.val_ext(face-num1,k); // TODO : FIXME : Yannick help :/
< : -psc*la_cl.val_ext(face-num1,k);
Definition at line 24 of file Eval_Conv_VDF_Face.tpp.
{
  const int elem1 = elem_(face,0), ncomp = flux.size_array();
  const double psc = dt_vitesse(face)*surface(face);
  if (elem1 != -1)
    {
      if (psc > 0)
        for (int k = 0; k < flux.size_array(); k++) flux[k] = -psc*inco(face,k)*porosite(face);
      else for (int k = 0; k < ncomp; k++) flux[k] = -psc*la_cl.val_ext(face-num1,orientation(face)); //!< : -psc*la_cl.val_ext(face-num1,k); // TODO : FIXME : Yannick help :/
    }
  else
    {
      if (psc < 0)
        for (int k = 0; k < flux.size_array(); k++) flux[k] = -psc*inco(face,k)*porosite(face);
      else for (int k = 0; k < ncomp; k++) flux[k] = -psc*la_cl.val_ext(face-num1,orientation(face)); //!< : -psc*la_cl.val_ext(face-num1,k);
    }
}
References Neumann_sortie_libre::val_ext().
flux_fa7() [2/2]
template<typename DERIVED_T > template<Type_Flux_Fa7 Fa7_Type, typename Type_Double > enable_if_t< Fa7_Type==Type_Flux_Fa7::ELEM, void > Eval_Conv_VDF_Face< DERIVED_T >::flux_fa7 (const DoubleTab & inco, int num_elem, int fac1, int fac2, Type_Double & flux) const inline
< Schema centre 2
< Schema centre 4
< QUICK
< Schema amont
< (psc < 0)
< Schema amont
Definition at line 43 of file Eval_Conv_VDF_Face.tpp.
{
  const int ncomp = flux.size_array();
  const double psc = 0.25*(dt_vitesse(fac1)+dt_vitesse(fac2))*(surface(fac1)+surface(fac2));
  if (DERIVED_T::IS_AMONT)
    {
      if (psc>0)
        for (int k = 0; k < ncomp; k++) flux[k] = -psc*inco(fac1,k)*porosite(fac1);
      else for (int k = 0; k < ncomp; k++) flux[k] = -psc*inco(fac2,k)*porosite(fac2);
    }
  else if (DERIVED_T::IS_CENTRE)
    for (int k = 0; k < ncomp; k++) flux[k] = -psc*0.5*(inco(fac1,k)*porosite(fac1)+inco(fac2,k)*porosite(fac2));
  else
    {
      const int num0_0 = face_amont_princ_(fac1,0), num1_1 = face_amont_princ_(fac2,1);
      if (DERIVED_T::IS_CENTRE4)
        {
          const int ori = orientation(fac1);
          if  ( (num0_0 == -1) || (num1_1== -1) )
            for (int k = 0; k < ncomp; k++) flux[k] = -psc*0.5*(inco(fac1,k)*porosite(fac1)+inco(fac2,k)*porosite(fac2)); //!< Schema centre 2
          else //!< Schema centre 4
            {
              Type_Double vit_0(ncomp),vit_0_0(ncomp),vit_1_1(ncomp),vit_1(ncomp);
              const double dx = dim_elem_(num_elem,ori), dxam = dim_elem_(elem_(fac1,0),ori), dxav = dim_elem_(elem_(fac2,1),ori);
              double g1, g2, g3, g4;
              calcul_g_(dxam,dx,dxav,g1,g2,g3,g4);
              for (int k = 0; k < ncomp; k++)
                {
                  vit_0_0[k] = inco(num0_0,k)*porosite(num0_0);
                  vit_0[k] = inco(fac1,k)*porosite(fac1);
                  vit_1[k] = inco(fac2,k)*porosite(fac2);
                  vit_1_1[k] = inco(num1_1,k)*porosite(num1_1);
                  flux[k] = -conv_centre_(psc,vit_0_0[k],vit_0[k],vit_1[k],vit_1_1[k],g1,g2,g3,g4);
                }
            }
        }
      else //!< QUICK
        {
          if  (psc > 0)
            {
              if (num0_0 == -1)
                for (int k=0; k<ncomp; k++) flux[k] = -psc*inco(fac1,k)*porosite(fac1); //!< Schema amont
              else
                {
                  Type_Double vit_0(ncomp), vit_0_0(ncomp), vit_1(ncomp);
                  const int ori = orientation(fac1), elem_amont = elem_(fac1,0);
                  const double dx = dim_elem_(num_elem,ori), dm = dist_elem_period_(elem_amont,num_elem,ori), dxam = dim_elem_(elem_amont,ori);
                  for (int k = 0; k < ncomp; k++)
                    {
                      vit_0[k] = inco(fac1,k)*porosite(fac1);
                      vit_1[k] = inco(fac2,k)*porosite(fac2);
                      vit_0_0[k] = inco(num0_0,k)*porosite(num0_0);
                      flux[k] = -conv_quick_sharp_plus_(psc,vit_0[k],vit_1[k],vit_0_0[k],dx,dm,dxam);
                    }
                }
            }
          else //!< (psc < 0)
            {
              if (num1_1 == -1)
                for (int k = 0; k < ncomp; k++) flux[k] = -psc*inco(fac2,k)*porosite(fac2); //!< Schema amont
              else
                {
                  Type_Double vit_0(ncomp), vit_1(ncomp), vit_1_1(ncomp);
                  const int ori = orientation(fac2), elem_amont = elem_(fac2,1);
                  const double dx = dim_elem_(num_elem,ori), dm = dist_elem_period_(num_elem,elem_amont,ori), dxam = dim_elem_(elem_amont,ori);
                  for (int k = 0; k < ncomp; k++)
                    {
                      vit_0[k] = inco(fac1,k)*porosite(fac1);
                      vit_1[k] = inco(fac2,k)*porosite(fac2);
                      vit_1_1[k] = inco(num1_1,k)*porosite(num1_1);
                      flux[k] = -conv_quick_sharp_moins_(psc,vit_0[k],vit_1[k],vit_1_1[k],dx,dm,dxam);
                    }
                }
            }
        }
    }
}
la_zcl()
template<typename DERIVED_T > const Zone_Cl_VDF & Eval_Conv_VDF_Face< DERIVED_T >::la_zcl () const inline private
Definition at line 126 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->get_la_zcl(); }
orientation()
template<typename DERIVED_T > int Eval_Conv_VDF_Face< DERIVED_T >::orientation (int face) const inline private
Definition at line 113 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->get_orientation(face); }
porosite()
template<typename DERIVED_T > double Eval_Conv_VDF_Face< DERIVED_T >::porosite (int face) const inline private
Definition at line 120 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->get_porosite(face); }
premiere_face_bord()
template<typename DERIVED_T > int Eval_Conv_VDF_Face< DERIVED_T >::premiere_face_bord () const inline private
Definition at line 112 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->get_premiere_face_bord(); }
secmem_arete() [1/3]
template<typename DERIVED_T > template<Type_Flux_Arete Arete_Type, typename Type_Double > enable_if_t<(Arete_Type==Type_Flux_Arete::INTERNE||Arete_Type==Type_Flux_Arete::MIXTE||Arete_Type==Type_Flux_Arete::PAROI|| Arete_Type==Type_Flux_Arete::SYMETRIE||Arete_Type==Type_Flux_Arete::SYMETRIE_PAROI), void > Eval_Conv_VDF_Face< DERIVED_T >::secmem_arete (int , int , int , int , Type_Double &) const inline
Definition at line 98 of file Eval_Conv_VDF_Face.h.
{ /* do nothing */ }
secmem_arete() [2/3]
template<typename DERIVED_T > template<Type_Flux_Arete Arete_Type, typename Type_Double > enable_if_t< Arete_Type==Type_Flux_Arete::FLUIDE||Arete_Type==Type_Flux_Arete::SYMETRIE_FLUIDE||Arete_Type==Type_Flux_Arete::PAROI_FLUIDE||Arete_Type==Type_Flux_Arete::COIN_FLUIDE, void > Eval_Conv_VDF_Face< DERIVED_T >::secmem_arete (int fac1, int fac2, int fac3, int signe, Type_Double & flux3, Type_Double & flux1_2) const inline
Definition at line 440 of file Eval_Conv_VDF_Face.tpp.
{
  assert(flux3.size_array() == flux1_2.size_array());
  if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_AXI || DERIVED_T::IS_CENTRE4) return;
  constexpr bool is_COIN = (Arete_Type == Type_Flux_Arete::COIN_FLUIDE);
  const int ncomp = flux3.size_array();
  const double tps = inconnue->temps(), psc = is_COIN ? 0.5*dt_vitesse(fac1)*porosite(fac1)*surface(fac1) :
                                              0.25*((dt_vitesse(fac1)*porosite(fac1)+dt_vitesse(fac2)*porosite(fac2))*(surface(fac1)+surface(fac2)));
  if ((psc*signe)<0)
    {
      const int pfb = premiere_face_bord(), rang1 = (fac1-pfb), rang2 = (fac2-pfb), ori = orientation(fac3);
      for (int k = 0; k < ncomp; k++)
        flux3[k] = is_COIN ? -Champ_Face_get_val_imp_face_bord(tps,rang1,ori,la_zcl()) * psc :
                   -0.5*(Champ_Face_get_val_imp_face_bord(tps,rang1,ori,la_zcl())+Champ_Face_get_val_imp_face_bord(tps,rang2,ori,la_zcl()))*psc ;
    }
  else for (int k = 0; k < ncomp; k++) flux3[k] = 0.;
  for (int k = 0; k < ncomp; k++) flux1_2[k] = 0.;
}
References Champ_Face_get_val_imp_face_bord(), and COIN_FLUIDE.
secmem_arete() [3/3]
template<typename DERIVED_T > template<Type_Flux_Arete Arete_Type, typename Type_Double > enable_if_t< Arete_Type==Type_Flux_Arete::PERIODICITE, void > Eval_Conv_VDF_Face< DERIVED_T >::secmem_arete (int , int , int , int , Type_Double & , Type_Double &) const inline
Definition at line 105 of file Eval_Conv_VDF_Face.h.
{ /* do nothing */ }
secmem_fa7() [1/2]
template<typename DERIVED_T > template<Type_Flux_Fa7 Fa7_Type, typename Type_Double > enable_if_t< Fa7_Type==Type_Flux_Fa7::SORTIE_LIBRE, void > Eval_Conv_VDF_Face< DERIVED_T >::secmem_fa7 (int face, const Neumann_sortie_libre & la_cl, int num1, Type_Double & flux) const inline
< : -psc*la_cl.val_ext(face-num1,k); // TODO : FIXME : Yannick help :/
< (elem2 != -1)
< : -psc*la_cl.val_ext(face-num1,k);
Definition at line 418 of file Eval_Conv_VDF_Face.tpp.
{
  if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_AXI || DERIVED_T::IS_CENTRE4) return;
  const int i = elem_(face,0), ncomp = flux.size_array();
  const double psc = dt_vitesse(face)*surface(face);
  if (i != -1)
    {
      if (psc < 0)
        for (int k = 0; k < ncomp; k++) flux[k] = -psc*la_cl.val_ext(face-num1,orientation(face)); //!< : -psc*la_cl.val_ext(face-num1,k); // TODO : FIXME : Yannick help :/
      else for (int k = 0; k < ncomp; k++) flux[k] = 0.;
    }
  else //!< (elem2 != -1)
    {
      if (psc > 0)
        for (int k = 0; k < ncomp; k++) flux[k] = -psc*la_cl.val_ext(face-num1,orientation(face)); //!< : -psc*la_cl.val_ext(face-num1,k);
      else for (int k = 0; k < ncomp; k++) flux[k] = 0.;
    }
}
References Neumann_sortie_libre::val_ext().
secmem_fa7() [2/2]
template<typename DERIVED_T > template<Type_Flux_Fa7 Fa7_Type, typename Type_Double > enable_if_t< Fa7_Type==Type_Flux_Fa7::ELEM, void > Eval_Conv_VDF_Face< DERIVED_T >::secmem_fa7 (int , int , int , Type_Double &) const inline
Definition at line 93 of file Eval_Conv_VDF_Face.h.
{ /* do nothing */ }
surface()
template<typename DERIVED_T > double Eval_Conv_VDF_Face< DERIVED_T >::surface (int face) const inline private
Definition at line 119 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->get_surface(face); }
surface_porosite()
template<typename DERIVED_T > double Eval_Conv_VDF_Face< DERIVED_T >::surface_porosite (int face) const inline private
Definition at line 118 of file Eval_Conv_VDF_Face.h.
{ return static_cast<const DERIVED_T *>(this)->get_surface_porosite(face); }
Member Data Documentation
CALC_ARR_PAR
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Face< DERIVED_T >::CALC_ARR_PAR = false static
Definition at line 27 of file Eval_Conv_VDF_Face.h.
CALC_ARR_SYMM_PAR
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Face< DERIVED_T >::CALC_ARR_SYMM_PAR = false static
Definition at line 27 of file Eval_Conv_VDF_Face.h.
CALC_FA7_SORTIE_LIB
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Face< DERIVED_T >::CALC_FA7_SORTIE_LIB = true static constexpr
Definition at line 27 of file Eval_Conv_VDF_Face.h.
IS_AMONT
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Face< DERIVED_T >::IS_AMONT = false static constexpr
Definition at line 26 of file Eval_Conv_VDF_Face.h.
IS_AXI
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Face< DERIVED_T >::IS_AXI = false static
Definition at line 26 of file Eval_Conv_VDF_Face.h.
IS_CENTRE
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Face< DERIVED_T >::IS_CENTRE = false static
Definition at line 26 of file Eval_Conv_VDF_Face.h.
IS_CENTRE4
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Face< DERIVED_T >::IS_CENTRE4 = false static
Definition at line 26 of file Eval_Conv_VDF_Face.h.
IS_QUICK
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Face< DERIVED_T >::IS_QUICK = false static
Definition at line 26 of file Eval_Conv_VDF_Face.h.
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Eval_Conv/Eval_Conv_VDF_Face.h
src/VDF/Operateurs/Eval_Conv/Eval_Conv_VDF_Face.tpp