TRUST: Operateurs_Statistique_tps Class Reference
Operateurs_Statistique_tps Class Reference
classe Operateurs_Statistique_tps
Cette classe represente une liste d'operateurs statistiques en temps.
Les objets Postraitement portent un objet de ce type.
#include <Operateurs_Statistique_tps.h>
Public Member Functions
Operateurs_Statistique_tps ()
~Operateurs_Statistique_tps ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
double tstat_deb () const
double tstat_fin () const
double tstat_dernier_calcul () const
int lserie () const
double dt_integr_serie () const
int sauvegarder (Sortie &os) const override
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
int reprendre (Entree &is) override
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
Public Member Functions inherited from List_Operateur_Statistique_tps
List_Operateur_Statistique_tps ()
~List_Operateur_Statistique_tps ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
List_Operateur_Statistique_tps (const Operateur_Statistique_tps &t)
List_Operateur_Statistique_tps (const List_Operateur_Statistique_tps &t)
Operateur_Statistique_tps & operator[] (int)
const Operateur_Statistique_tps & operator[] (int) const
Operateur_Statistique_tps & operator[] (const Nom &)
const Operateur_Statistique_tps & operator[] (const Nom &) const
Operateur_Statistique_tps & operator() (int i)
const Operateur_Statistique_tps & operator() (int i) const
Operateur_Statistique_tps & operator() (const Nom &n)
const Operateur_Statistique_tps & operator() (const Nom &n) const
Operateur_Statistique_tps & valeur ()
const Operateur_Statistique_tps & valeur () const
List_Operateur_Statistique_tps & operator= (const Operateur_Statistique_tps &t)
Operateur_Statistique_tps * operator-> ()
List_Operateur_Statistique_tps & operator= (const List_Operateur_Statistique_tps &)
List_Operateur_Statistique_tps & add (const List_Operateur_Statistique_tps &)
Operateur_Statistique_tps & add (const Operateur_Statistique_tps &)
List_Operateur_Statistique_tps & inserer (const List_Operateur_Statistique_tps &)
Operateur_Statistique_tps & inserer (const Operateur_Statistique_tps &)
void supprimer ()
List_Operateur_Statistique_tps & operator+= (const List_Operateur_Statistique_tps &)
List_Operateur_Statistique_tps & operator+= (const Operateur_Statistique_tps &)
Operateur_Statistique_tps & add_if_not (const Operateur_Statistique_tps &)
Operateur_Statistique_tps & add_if_not (const char *const)
List_Operateur_Statistique_tps & search (const Operateur_Statistique_tps &) const
List_Operateur_Statistique_tps & search (const char *const) const
List_Operateur_Statistique_tps & suivant ()
const List_Operateur_Statistique_tps & suivant () const
const List_Operateur_Statistique_tps & dernier () const
List_Operateur_Statistique_tps & dernier ()
List_Operateur_Statistique_tps & operator-= (const Operateur_Statistique_tps &)
int est_egal_a (const Objet_U &) const override
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
int contient (const Operateur_Statistique_tps &) const
int contient (const char *const) const
int rang (const Operateur_Statistique_tps &) const
void suppr (const Operateur_Statistique_tps &)
Public Member Functions inherited from liste
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
liste ()
Constructeur par defaut
Construit une liste vide.
liste (const liste &)
Constructeur
Ajoute les elements contenus dans la liste passe en parametre.
liste (const Objet_U &)
Constructeur
Construit une liste singleton.
~liste () override
Destructeur de liste.
int size () const
Renvoie la taille de la liste
Une liste vide est de taille nulle.
int rang (const char *const) const
Renvoie le rang d'une chaine de caracteres contenue dans la liste
Recherche un Objet_U de Nom ch.
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
void suppr (const char *const)
Supprime l'Objet de Nom ch contenu dans la liste.
int est_vide () const
Teste si la liste est vide.
int est_dernier () const
Teste si la liste comporte des elements suivants ou non.
Retourne 1 si la liste est vide.
void vide ()
Vide la liste.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Operateurs_Statistique_tps & self_cast (Objet_U &)
static const Operateurs_Statistique_tps & self_cast (const Objet_U &)
Static Public Member Functions inherited from List_Operateur_Statistique_tps
static Objet_U * cree_instance ()
static const Type_info * info ()
static List_Operateur_Statistique_tps & self_cast (Objet_U &)
static const List_Operateur_Statistique_tps & self_cast (const Objet_U &)
Static Public Member Functions inherited from liste
static Objet_U * cree_instance ()
static const Type_info * info ()
static liste & self_cast (Objet_U &)
static const liste & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from List_Operateur_Statistique_tps
static const Type_info info_obj
Static Public Attributes inherited from liste
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime le type et le nom de la liste d'operateurs
sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les specifications d'une liste d'operateurs statistiques a
partir d'un flot d'entree.
Protected Member Functions inherited from List_Operateur_Statistique_tps
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
int est_egal_a (const List_Operateur_Statistique_tps &) const
Protected Member Functions inherited from liste
Sortie & printOn (Sortie &x) const override
Ecriture d'une liste sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une liste sur un flot d'entree.
Objet_U & operator() (int)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Objet_U & operator() (int) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Objet_U & operator() (const Nom &)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Objet_U & operator() (const Nom &) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Objet_U & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Objet_U & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
liste & operator+= (const Objet_U &)
Ajoute un Objet_U a la fin de la liste.
liste & operator+= (const liste &)
Ajoute une list d'Objet_U a la fin de la liste.
liste & operator-= (const Objet_U &)
Supprime un Objet_U de la liste
Affiche un message d'erreur si l'objet n'est pas trouve.
const liste & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
liste & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
Objet_U * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
const Objet_U * operator-> () const
Retourne un pointeur sur l'Objet_U premier element de la liste.
Objet_U & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Objet_U & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Objet_U & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Objet_U & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Objet_U & add (const Objet_U &)
Ajout d'un Objet_U a la liste.
Objet_U & add_deplace (DerObjU &)
Ajout d'un Objet_U a la liste
to_add est libere en sortie.
Objet_U & inserer (const Objet_U &)
Insertion d'un Objet_U dans la liste.
liste & add (const liste &)
Ajout d'une liste a la liste.
liste & inserer (const liste &)
Insertion d'une liste
NON CODE - SORT SYSTEMATIQUEMENT EN ERREUR.
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Objet_U & add_if_not (const Objet_U &)
Ajout d'un Objet_U a la liste ssi il n'existe pas deja.
liste & search (const Objet_U &) const
Recherche d'un Objet_U dans la liste.
liste & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
int contient (const Objet_U &) const
Verifie si un Objet_U appartient ou non a la liste.
int rang (const Objet_U &) const
Renvoie le rang d'un Objet_U dans la liste.
void suppr (const Objet_U &)
Supprime un Objet_U contenu dans la liste.
liste & operator= (const liste &)
Operateur d'affectation de liste.
const liste & dernier () const
Renvoie le dernier element de la liste.
liste & dernier ()
Renvoie le dernier element de la liste.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Postraitement mon_post
double tstat_deb_
double tstat_dernier_calcul_
dernier temps auquel les statistiques ont ete calcules
double tstat_fin_
valeur choisie par l'utilisateur
int lserie_
double dt_integr_serie_
Protected Attributes inherited from liste
DerObjU data
liste * suivant_
Detailed Description
classe Operateurs_Statistique_tps
Cette classe represente une liste d'operateurs statistiques en temps.
Les objets Postraitement portent un objet de ce type.
Definition at line 33 of file Operateurs_Statistique_tps.h.
Constructor & Destructor Documentation
Operateurs_Statistique_tps()
Operateurs_Statistique_tps::Operateurs_Statistique_tps ()
Definition at line 25 of file Operateurs_Statistique_tps.cpp.
: tstat_deb_(-123.), tstat_dernier_calcul_(-123.), tstat_fin_(-123.), lserie_(-123),dt_integr_serie_(-123.) {}
~Operateurs_Statistique_tps()
Operateurs_Statistique_tps::~Operateurs_Statistique_tps ()
Definition at line 23 of file Operateurs_Statistique_tps.cpp.
Member Function Documentation
cree_instance()
Objet_U * Operateurs_Statistique_tps::cree_instance () static
Definition at line 23 of file Operateurs_Statistique_tps.cpp.
dt_integr_serie()
double Operateurs_Statistique_tps::dt_integr_serie () const inline
Definition at line 78 of file Operateurs_Statistique_tps.h.
{
  return dt_integr_serie_;
}
References dt_integr_serie_.
duplique()
int Operateurs_Statistique_tps::duplique () const override virtual
Reimplemented from List_Operateur_Statistique_tps.
Definition at line 23 of file Operateurs_Statistique_tps.cpp.
get_info()
const Type_info * Operateurs_Statistique_tps::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from List_Operateur_Statistique_tps.
Definition at line 23 of file Operateurs_Statistique_tps.cpp.
info()
const Type_info * Operateurs_Statistique_tps::info () static
Definition at line 23 of file Operateurs_Statistique_tps.cpp.
lserie()
int Operateurs_Statistique_tps::lserie () const inline
Definition at line 73 of file Operateurs_Statistique_tps.h.
{
  return lserie_;
}
References lserie_.
printOn()
Sortie & Operateurs_Statistique_tps::printOn (Sortie & s) const override protected virtual
Imprime le type et le nom de la liste d'operateurs
sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from List_Operateur_Statistique_tps.
Definition at line 42 of file Operateurs_Statistique_tps.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Operateurs_Statistique_tps::readOn (Entree & s) override protected virtual
Lit les specifications d'une liste d'operateurs statistiques a
partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from List_Operateur_Statistique_tps.
Definition at line 78 of file Operateurs_Statistique_tps.cpp.
{
  return s;
}
reprendre()
int Operateurs_Statistique_tps::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
< On saute les champs
< sinon erreur sur la taille dans lit()
< tinit=>temps_derniere_mise_a_jour_stats : on fait la reprise
< On saute l'identificateur et le type des champs
< lecture pour sauter le bloc
< sinon erreur sur la taille dans lit()
Reimplemented from Objet_U.
Definition at line 113 of file Operateurs_Statistique_tps.cpp.
{
// Cerr << "Operateurs_Statistique_tps::reprendre" << finl;
  if (mon_post.non_nul())
    {
      Nom bidon;
      is >> bidon;
      if (bidon=="fin")
        {
// Ce test evite un beau segmentation fault a la lecture
// du deuxieme bidon lors d'une sauvegarde/reprise au format binaire
          Cerr << "The end of the restarting file is reached." << finl;
          Cerr << "This file does not contain statistics." << finl;
          Cerr << "The restarting time tinit must therefore be lower" << finl;
          Cerr << "than the statistics begining time t_deb." << finl;
          exit();
        }
      is >> bidon;
      int n;
      is >> n;
      double tstat_deb_sauv,temps_derniere_mise_a_jour_stats;
      is >> tstat_deb_sauv;
      is >> temps_derniere_mise_a_jour_stats;
// Cerr << "temps_derniere_mise_a_jour_stats" << temps_derniere_mise_a_jour_stats << finl;
      double tinit = mon_post->probleme().schema_temps().temps_courant();
// Plusieurs cas possibles:
      if (inf_strict(tinit,temps_derniere_mise_a_jour_stats,1.e-5))
        {
          Cerr << "The initial time " << tinit << " of the restarting calculation is lower" << finl;
          Cerr << "than the last statistics update time " << temps_derniere_mise_a_jour_stats << finl;
          Cerr << "One is not able to treat this case." << finl;
          exit();
        }
      else if (!est_egal(tstat_deb_sauv,tstat_deb_))
        {
// t_deb est modifie : on refait une statistique sans reprendre dans certains cas
          if (inf_strict(tstat_deb_,tinit,1.e-5))
            {
              Cerr << "t_deb has been modified to carry out a new statistics calculation without restarting" << finl;
              Cerr << "but t_deb is lower than tinit : it is not possible." << finl;
              exit();
            }
          Cerr << "Statistics are not restarted and therefore the statistics calculation" << finl;
          Cerr << "will restart a t_deb =" << tstat_deb_ << finl;
          LIST_CURSEUR(Operateur_Statistique_tps) curseur=*this;
          Nom bidon2;
          double dbidon;
          DoubleTab tab_bidon;
          while(curseur)   //!< On saute les champs
            {
              is >> bidon2 >> bidon2;
              is >> dbidon;
              tab_bidon.reset(); //!< sinon erreur sur la taille dans lit()
              tab_bidon.jump(is);
              ++curseur;
            }
        }
      else //!< tinit=>temps_derniere_mise_a_jour_stats : on fait la reprise
        {
          Nom bidon2;
          LIST_CURSEUR(Operateur_Statistique_tps) curseur=*this;
          while(curseur)
            {
              is >> bidon2 >> bidon2; //!< On saute l'identificateur et le type des champs
              curseur->reprendre(is);
              ++curseur;
            }
// On modifie l'attribut tstat_deb_ et l'attribut t_debut_ des champs
// pour tenir compte de la reprise
          tstat_deb_ = tstat_deb_sauv;
          curseur=*this;
          while(curseur)
            {
              curseur->fixer_tstat_deb(tstat_deb_,temps_derniere_mise_a_jour_stats);
              ++curseur;
            }
        }
    }
  else  //!< lecture pour sauter le bloc
    {
      int n;
      is >> n;
      double tstat_deb_sauv,temps_derniere_mise_a_jour_stats;
      is >> tstat_deb_sauv;
      is >> temps_derniere_mise_a_jour_stats;
      Nom bidon;
      double dbidon;
      DoubleTab tab_bidon;
      for (int i=0; i<n; i++)
        {
          is >> bidon >> bidon;
          is >> dbidon;
          tab_bidon.reset(); //!< sinon erreur sur la taille dans lit()
          tab_bidon.jump(is);
        }
    }
  return 1;
}
References Cerr, est_egal(), Process::exit(), finl, inf_strict(), TRUSTTab< _TYPE_ >::jump(), LIST_CURSEUR, mon_post, O_U_Ptr::non_nul(), Postraitement::probleme(), Objet_U::reprendre(), TRUSTTab< _TYPE_ >::reset(), Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), and tstat_deb_.
sauvegarder()
int Operateurs_Statistique_tps::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 83 of file Operateurs_Statistique_tps.cpp.
{
// en mode ecriture special seul le maitre ecrit l'entete
  int a_faire,special;
  EcritureLectureSpecial::is_ecriture_special(special,a_faire);
  if (a_faire)
    {
      Nom mon_ident(que_suis_je());
      mon_ident += mon_post->probleme().domaine().le_nom();
      double temps = mon_post->probleme().schema_temps().temps_courant();
      mon_ident += Nom(temps,"%e");
      os << mon_ident << finl;
      os << que_suis_je() << finl;
      os << size() << finl;
      os << Nom(tstat_deb_,"%e") << finl;
      os << Nom(tstat_dernier_calcul_,"%e") << finl ;
    }
  CONST_LIST_CURSEUR(Operateur_Statistique_tps) curseur=*this;
  int bytes=0;
  while(curseur)
    {
      bytes += curseur->sauvegarder(os);
      ++curseur;
    }
  if (a_faire) os.flush();
  return bytes;
}
References CONST_LIST_CURSEUR, Probleme_base::domaine(), finl, Sortie::flush(), EcritureLectureSpecial::is_ecriture_special(), Domaine::le_nom(), mon_post, Postraitement::probleme(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), liste::size(), Schema_Temps_base::temps_courant(), tstat_deb_, and tstat_dernier_calcul_.
self_cast() [1/2]
const Operateurs_Statistique_tps & Operateurs_Statistique_tps::self_cast (const Objet_U & r) static
Definition at line 23 of file Operateurs_Statistique_tps.cpp.
self_cast() [2/2]
Operateurs_Statistique_tps & Operateurs_Statistique_tps::self_cast (Objet_U & r) static
Definition at line 23 of file Operateurs_Statistique_tps.cpp.
taille_memoire()
unsigned Operateurs_Statistique_tps::taille_memoire () const override virtual
Reimplemented from List_Operateur_Statistique_tps.
Definition at line 23 of file Operateurs_Statistique_tps.cpp.
tstat_deb()
double Operateurs_Statistique_tps::tstat_deb () const inline
Definition at line 58 of file Operateurs_Statistique_tps.h.
{
  return tstat_deb_;
}
References tstat_deb_.
tstat_dernier_calcul()
double Operateurs_Statistique_tps::tstat_dernier_calcul () const inline
Definition at line 68 of file Operateurs_Statistique_tps.h.
{
  return tstat_dernier_calcul_;
}
References tstat_dernier_calcul_.
tstat_fin()
double Operateurs_Statistique_tps::tstat_fin () const inline
Definition at line 63 of file Operateurs_Statistique_tps.h.
{
  return tstat_fin_;
}
References tstat_fin_.
Member Data Documentation
dt_integr_serie_
double Operateurs_Statistique_tps::dt_integr_serie_ protected
Definition at line 54 of file Operateurs_Statistique_tps.h.
Referenced by dt_integr_serie().
info_obj
const Type_info Operateurs_Statistique_tps::info_obj static
Definition at line 35 of file Operateurs_Statistique_tps.h.
lserie_
int Operateurs_Statistique_tps::lserie_ protected
Definition at line 53 of file Operateurs_Statistique_tps.h.
Referenced by lserie().
mon_post
Ref_Postraitement Operateurs_Statistique_tps::mon_post protected
Definition at line 49 of file Operateurs_Statistique_tps.h.
Referenced by reprendre(), and sauvegarder().
tstat_deb_
double Operateurs_Statistique_tps::tstat_deb_ protected
Definition at line 50 of file Operateurs_Statistique_tps.h.
Referenced by reprendre(), sauvegarder(), and tstat_deb().
tstat_dernier_calcul_
double Operateurs_Statistique_tps::tstat_dernier_calcul_ protected
dernier temps auquel les statistiques ont ete calcules
Definition at line 51 of file Operateurs_Statistique_tps.h.
Referenced by sauvegarder(), and tstat_dernier_calcul().
tstat_fin_
double Operateurs_Statistique_tps::tstat_fin_ protected
valeur choisie par l'utilisateur
Definition at line 52 of file Operateurs_Statistique_tps.h.
Referenced by tstat_fin().
The documentation for this class was generated from the following files:
src/Kernel/Statistiques_temps/Operateurs_Statistique_tps.h
src/Kernel/Statistiques_temps/Operateurs_Statistique_tps.cpp