TRUST: Champ_Generique_modifier_pour_QC Class Reference
Champ_Generique_modifier_pour_QC Class Reference
class Champ_Generique_modifier_pour_QC
Champ destine a post-traiter un champ d un probleme en quasi-compressible
que l on souhaite multiplier ou diviser par la masse volumique (rho).
La classe porte une REF au milieu qui doit etre de type Fluide_Quasi_Compressible.
#include <Champ_Generique_modifier_pour_QC.h>
Public Member Functions
~Champ_Generique_modifier_pour_QC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Champ_Generique_modifier_pour_QC ()
void set_param (Param &param)
void completer (const Postraitement_base &post)
virtual const Champ_base & get_champ (Champ &espace_stockage) const
virtual const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const
void nommer_source ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Champ_Generique_modifier_pour_QC & self_cast (Objet_U &)
static const
Champ_Generique_modifier_pour_QC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
int diviser_
Ref_Milieu_base mon_milieu_
Detailed Description
class Champ_Generique_modifier_pour_QC
Champ destine a post-traiter un champ d un probleme en quasi-compressible
que l on souhaite multiplier ou diviser par la masse volumique (rho).
La classe porte une REF au milieu qui doit etre de type Fluide_Quasi_Compressible.
Definition at line 45 of file Champ_Generique_modifier_pour_QC.h.
Constructor & Destructor Documentation
Champ_Generique_modifier_pour_QC::~Champ_Generique_modifier_pour_QC ()
Definition at line 30 of file Champ_Generique_modifier_pour_QC.cpp.
Champ_Generique_modifier_pour_QC::Champ_Generique_modifier_pour_QC ()
Definition at line 32 of file Champ_Generique_modifier_pour_QC.cpp.
References diviser_.
{
  diviser_=0;
}
Member Function Documentation
void Champ_Generique_modifier_pour_QC::completer (const Postraitement_base & post) [virtual]
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 54 of file Champ_Generique_modifier_pour_QC.cpp.
References Probleme_base::equation(), Equation_base::milieu(), mon_milieu_, Postraitement::probleme(), and ref_cast.
{
  Champ_Gen_de_Champs_Gen::completer(post);
  const Postraitement& mon_post = ref_cast(Postraitement,post);
  mon_milieu_ = mon_post.probleme().equation(0).milieu();
}
Objet_U * Champ_Generique_modifier_pour_QC::cree_instance () [static]
Definition at line 30 of file Champ_Generique_modifier_pour_QC.cpp.
int Champ_Generique_modifier_pour_QC::duplique () const [virtual]
Implements Champ_Gen_de_Champs_Gen.
Definition at line 30 of file Champ_Generique_modifier_pour_QC.cpp.
const Champ_base & Champ_Generique_modifier_pour_QC::get_champ (Champ & espace_stockage) const [virtual]
Implements Champ_Generique_base.
Definition at line 71 of file Champ_Generique_modifier_pour_QC.cpp.
References Champ_Gen_de_Champs_Gen::creer_espace_stockage(), diviser_, DoubleVect::echange_espace_virtuel(), Champ_Generique_base::get_champ(), Champ_Gen_de_Champs_Gen::get_source(), mon_milieu_, multiplier_diviser_rho(), Field_base::nature_du_champ(), Field_base::nb_comp(), ref_cast, Deriv_Champ_base::valeur(), Ref_Milieu_base::valeur(), Champ_Proto::valeurs(), and Champ::valeurs().
{
  Champ source_espace_stockage;
  const Champ_base& source = get_source(0).get_champ(source_espace_stockage);
  Nature_du_champ nature_source = source.nature_du_champ();
  int nb_comp = source.nb_comp();
  Champ_Fonc es_tmp;
  espace_stockage = creer_espace_stockage(nature_source,nb_comp,es_tmp);
  DoubleTab& val = espace_stockage.valeurs();
  val = source.valeurs();
  const Fluide_Quasi_Compressible& fluide = ref_cast(Fluide_Quasi_Compressible,mon_milieu_.valeur());
  multiplier_diviser_rho(val,fluide,diviser_);
  val.echange_espace_virtuel();
  return espace_stockage.valeur();
}
const Champ_base & Champ_Generique_modifier_pour_QC::get_champ_without_evaluation (Champ & espace_stockage) const [virtual]
Implements Champ_Generique_base.
Definition at line 61 of file Champ_Generique_modifier_pour_QC.cpp.
References Champ_Gen_de_Champs_Gen::creer_espace_stockage(), Champ_Generique_base::get_champ_without_evaluation(), Champ_Gen_de_Champs_Gen::get_source(), Field_base::nature_du_champ(), Field_base::nb_comp(), and Deriv_Champ_base::valeur().
{
  Champ source_espace_stockage;
  const Champ_base& source = get_source(0).get_champ_without_evaluation(source_espace_stockage);
  Nature_du_champ nature_source = source.nature_du_champ();
  int nb_comp = source.nb_comp();
  Champ_Fonc es_tmp;
  espace_stockage = creer_espace_stockage(nature_source,nb_comp,es_tmp);
  return espace_stockage.valeur();
}
const Type_info * Champ_Generique_modifier_pour_QC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 30 of file Champ_Generique_modifier_pour_QC.cpp.
const Type_info * Champ_Generique_modifier_pour_QC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 30 of file Champ_Generique_modifier_pour_QC.cpp.
void Champ_Generique_modifier_pour_QC::nommer_source () [virtual]
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 90 of file Champ_Generique_modifier_pour_QC.cpp.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
{
  if (nom_post_=="??")
    {
      Nom nom_post_source, nom_champ_source;
      const Noms nom = get_source(0).get_property("nom");
      nom_champ_source = nom[0];
      nom_post_source = "Modifier_pour_QC_";
      nom_post_source +=  nom_champ_source;
      nommer(nom_post_source);
    }
}
Sortie & Champ_Generique_modifier_pour_QC::printOn (Sortie & os) const [protected, virtual]
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 37 of file Champ_Generique_modifier_pour_QC.cpp.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Champ_Generique_modifier_pour_QC::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 42 of file Champ_Generique_modifier_pour_QC.cpp.
{
  Champ_Gen_de_Champs_Gen::readOn(s);
  return s ;
}
const Champ_Generique_modifier_pour_QC & Champ_Generique_modifier_pour_QC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 30 of file Champ_Generique_modifier_pour_QC.cpp.
Champ_Generique_modifier_pour_QC & Champ_Generique_modifier_pour_QC::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 30 of file Champ_Generique_modifier_pour_QC.cpp.
void Champ_Generique_modifier_pour_QC::set_param (Param & param) [virtual]
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 48 of file Champ_Generique_modifier_pour_QC.cpp.
References Param::ajouter_flag(), and diviser_.
{
  Champ_Gen_de_Champs_Gen::set_param(param);
  param.ajouter_flag("division",&diviser_);
}
unsigned Champ_Generique_modifier_pour_QC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 30 of file Champ_Generique_modifier_pour_QC.cpp.
Member Data Documentation
int Champ_Generique_modifier_pour_QC::diviser_ [protected]
Definition at line 60 of file Champ_Generique_modifier_pour_QC.h.
Referenced by Champ_Generique_modifier_pour_QC(), get_champ(), and set_param().
const Type_info Champ_Generique_modifier_pour_QC::info_obj [static]
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 47 of file Champ_Generique_modifier_pour_QC.h.
Ref_Milieu_base Champ_Generique_modifier_pour_QC::mon_milieu_ [protected]
Definition at line 61 of file Champ_Generique_modifier_pour_QC.h.
Referenced by completer(), and get_champ().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/Champ_Generique_modifier_pour_QC.h
src/ThHyd/Dilatable/Quasi_Compressible/Champ_Generique_modifier_pour_QC.cpp