TRUST: Deriv_Elem_VEF_base Class Reference
Deriv_Elem_VEF_base Class Reference
#include <Elem_VEF.h>
Public Member Functions
~Deriv_Elem_VEF_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Elem_VEF_base ()
Deriv_Elem_VEF_base (const Deriv_Elem_VEF_base &)
const Elem_VEF_base & valeur () const
Elem_VEF_base & valeur ()
const Elem_VEF_base * operator-> () const
Elem_VEF_base * operator-> ()
const Deriv_Elem_VEF_base & operator= (const Elem_VEF_base &)
const Deriv_Elem_VEF_base & operator= (const Deriv_Elem_VEF_base &)
operator const Elem_VEF_base & () const
operator Elem_VEF_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Elem_VEF_base & self_cast (Objet_U &)
static const Deriv_Elem_VEF_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Elem_VEF_base * pointeur_
Detailed Description
Definition at line 41 of file Elem_VEF.h.
Constructor & Destructor Documentation
Deriv_Elem_VEF_base::~Deriv_Elem_VEF_base ()
Definition at line 30 of file Elem_VEF.cpp.
Deriv_Elem_VEF_base::Deriv_Elem_VEF_base ()
Definition at line 30 of file Elem_VEF.cpp.
Deriv_Elem_VEF_base::Deriv_Elem_VEF_base (const Deriv_Elem_VEF_base & t)
Definition at line 30 of file Elem_VEF.cpp.
Member Function Documentation
Objet_U * Deriv_Elem_VEF_base::cree_instance () [static]
Reimplemented in Elem_VEF.
Definition at line 30 of file Elem_VEF.cpp.
int Deriv_Elem_VEF_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Elem_VEF.
Definition at line 30 of file Elem_VEF.cpp.
const Type_info * Deriv_Elem_VEF_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Elem_VEF.
Definition at line 30 of file Elem_VEF.cpp.
const Type_info & Deriv_Elem_VEF_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 30 of file Elem_VEF.cpp.
const Type_info * Deriv_Elem_VEF_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Elem_VEF.
Definition at line 30 of file Elem_VEF.cpp.
Deriv_Elem_VEF_base::operator const Elem_VEF_base & () const
Definition at line 30 of file Elem_VEF.cpp.
Deriv_Elem_VEF_base::operator Elem_VEF_base & ()
Definition at line 30 of file Elem_VEF.cpp.
const Elem_VEF_base * Deriv_Elem_VEF_base::operator-> () const [inline]
Definition at line 41 of file Elem_VEF.h.
: public DERIV(Elem_VEF_base)
Elem_VEF_base * Deriv_Elem_VEF_base::operator-> () [inline]
Definition at line 41 of file Elem_VEF.h.
: public DERIV(Elem_VEF_base)
const Deriv_Elem_VEF_base & Deriv_Elem_VEF_base::operator= (const Deriv_Elem_VEF_base & t)
Definition at line 30 of file Elem_VEF.cpp.
const Deriv_Elem_VEF_base & Deriv_Elem_VEF_base::operator= (const Elem_VEF_base & t)
Reimplemented in Elem_VEF.
Definition at line 30 of file Elem_VEF.cpp.
Sortie & Deriv_Elem_VEF_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Elem_VEF.
Definition at line 30 of file Elem_VEF.cpp.
Entree & Deriv_Elem_VEF_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Elem_VEF.
Definition at line 30 of file Elem_VEF.cpp.
const Deriv_Elem_VEF_base & Deriv_Elem_VEF_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Elem_VEF.
Definition at line 30 of file Elem_VEF.cpp.
Deriv_Elem_VEF_base & Deriv_Elem_VEF_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Elem_VEF.
Definition at line 30 of file Elem_VEF.cpp.
void Deriv_Elem_VEF_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 30 of file Elem_VEF.cpp.
unsigned Deriv_Elem_VEF_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Elem_VEF.
Definition at line 30 of file Elem_VEF.cpp.
const Elem_VEF_base & Deriv_Elem_VEF_base::valeur () const [inline]
Definition at line 41 of file Elem_VEF.h.
Referenced by Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_Muscl_New_VEF_Face::ajouter_diffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Elem_VEF::calcul_vc(), Elem_VEF::calcul_xg(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), Elem_VEF::creer_facette_normales(), Elem_VEF::creer_normales_facettes_Cl(), Zone_VEF::discretiser(), VEF_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ_fonc_don(), Elem_VEF::modif_normales_facettes_Cl(), Elem_VEF::modif_volumes_entrelaces(), Elem_VEF::modif_volumes_entrelaces_faces_joints(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Elem_VEF::nb_facette(), Elem_VEF::normale(), Elem_VEF::printOn(), Op_Conv_VEF_Face::remplir_fluent(), Zone_Cl_VEF::remplir_normales_facettes_Cl(), Zone_Cl_VEF::remplir_type_elem_Cl(), Zone_VEF::vecteur_face_facette(), VEF_1D::vitesse(), and VEF_discretisation::vorticite().
: public DERIV(Elem_VEF_base)
Elem_VEF_base & Deriv_Elem_VEF_base::valeur () [inline]
Definition at line 41 of file Elem_VEF.h.
: public DERIV(Elem_VEF_base)
Member Data Documentation
const Type_info Deriv_Elem_VEF_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Elem_VEF.
Definition at line 41 of file Elem_VEF.h.
Elem_VEF_base* Deriv_Elem_VEF_base::pointeur_ [private]
Definition at line 41 of file Elem_VEF.h.
The documentation for this class was generated from the following files:
src/VEF/Zones/Elem_VEF.h
src/VEF/Zones/Elem_VEF.cpp