TRUST: Faces_VDF Class Reference
Faces_VDF Class Reference
class Faces_VDF
#include <Faces_VDF.h>
Public Member Functions
Faces_VDF ()
~Faces_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int orientation (int) const
int orientation (int)
void associer (const Zone_VDF &)
se lie a la zone
const Zone_VDF & zone_VDF () const
Renvoie la zone.
void calculer_orientation (IntVect &, int &, int &, int &)
void reordonner (IntVect &)
void reordonner_pour_debog (IntVect &)
Public Member Functions inherited from Faces
Faces ()
~Faces ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Type_Face type_face () const
Renvoie le type des Faces.
int nb_faces () const
Renvoie le nombre de Faces.
int nb_faces_tot () const
Renvoie le nombre total de Faces
i.e. Le nombre de faces reelles et virtuelles
sur le processeur courant.
int nb_som_faces () const
Renvoie le nombre de sommet par face.
int sommet (int, int) const
Renvoie le numero du j-ieme sommet de la i-ieme face.
int & sommet (int, int)
Renvoie une reference sur le numero
du j-ieme sommet de la i-ieme face.
IntTab & les_sommets ()
const IntTab & les_sommets () const
Renvoie le tableau des sommets de toutes les faces.
Type_Face type (const Motcle &) const
Renvoie un objet de Type_Face representant
le type de nom specifie.
Les noms de types reconnus sont:
"vide_0D"
"point_1D"
"point_1D_axi"
"segment_2D"
"triangle_3D"
"quadrangle_3D"
"segment_2D_axi"
"quadrangle_3D_axi"
"quadrilatere_2D_axi".
Motcle & type (const Type_Face &) const
Renvoie le nom associe a un type de face.
(inverse de Type_Face Faces::type(const Motcle&) const)
void ajouter (const IntTab &)
Ajoute des faces.
Ajouter des faces revient a ajouter des sommets.
void typer (const Motcle &)
Type les faces.
void typer (const Type_Face &)
Type les faces.
int dimensionner (int)
(Re-)dimensionne les faces
On redimensionne les voisins en consequence.
Les sommets implicitement ajoutes sont initialises a -1.
int voisin (int, int) const
Renvoie le numero du i-ieme voisin de face.
int & voisin (int, int)
Renvoie une reference le numero du i-ieme voisin de face.
IntTab & voisins ()
Renvoie le tableau des voisins (des faces).
const IntTab & voisins () const
void completer (int, int)
Complete la face specifie: met a jour
ses voisins.
void associer_zone (const Zone &)
Associe les faces a une Zone.
const Zone & zone () const
Renvoie la zone associee.
void calculer_surfaces (DoubleVect &) const
Calcule la surface des faces.
void calculer_centres_gravite (DoubleTab &) const
Calcule les centres de gravite de chaque face.
void reordonner ()
Reordonne les faces.
(on ne reordonne que les quadrangles)
IntVect & compare (const Faces &, IntVect &)
Compare l'objet Faces passe en parametre avec
l'objet Faces lui-meme (this)
void initialiser_faces_joint (int)
Initialise les voisins des faces joints a -1.
void initialiser_sommets_faces_joint (int)
Initialise les sommets des faces joints a -1.
Entree & lit (Entree &)
Lit les specifications d'un objet face a
partir d'un flot d'entree.
On lit:
- le type des faces
- les sommets
- les voisins
Et on reordonne les sommets.
Ne fait rien si le type lu est "vide_0D".
Sortie & ecrit (Sortie &) const
Ecrit les faces sur un flots de sortie.
On ecrit:
- le type des faces
- les sommets
- les voisins
On ecrit juste le type Faces::vide_0D, si le nombre de
faces est nul.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Faces_VDF & self_cast (Objet_U &)
static const Faces_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Faces
static Objet_U * cree_instance ()
static const Type_info * info ()
static Faces & self_cast (Objet_U &)
static const Faces & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Faces
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit les faces sur un flots de sortie.
On ecrit:
- le type des faces
- les sommets
- les voisins
On ecrit juste le type Faces::vide_0D, si le nombre de
faces est nul.
Entree & readOn (Entree &) override
Lit les specifications d'un objet face a
partir d'un flot d'entree.
On lit:
- le type des faces
- les sommets
- les voisins
Et on reordonne les sommets.
Cree un objets Faces avec 0 faces si le type est "vide_0D".
Sortie & printOn (Sortie &x) const override
Ecrit les faces sur un flots de sortie.
On ecrit:
- le type des faces
- les sommets
- les voisins
On ecrit juste le type Faces::vide_0D, si le nombre de
faces est nul.
Entree & readOn (Entree &) override
Lit les specifications d'un objet face a
partir d'un flot d'entree.
On lit:
- le type des faces
- les sommets
- les voisins
Et on reordonne les sommets.
Cree un objets Faces avec 0 faces si le type est "vide_0D".
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void swap (int, int)
Private Attributes
IntVect orientation_
orientation des faces : 0 pour une face d'equation x = cte 1 pour une face d'equation y = cte 2 pour une face d'equation z = cte
Ref_Zone_VDF la_zone_VDF
Additional Inherited Members
Public Types inherited from Faces
enum Type_Face {
vide_0D , point_1D , point_1D_axi , segment_2D ,
segment_2D_axi , triangle_3D , quadrilatere_2D_axi , quadrangle_3D ,
quadrangle_3D_axi , polygone_3D
}
Detailed Description
class Faces_VDF
Definition at line 31 of file Faces_VDF.h.
Constructor & Destructor Documentation
Faces_VDF()
Faces_VDF::Faces_VDF ()
Definition at line 19 of file Faces_VDF.cpp.
~Faces_VDF()
Faces_VDF::~Faces_VDF ()
Definition at line 19 of file Faces_VDF.cpp.
Member Function Documentation
associer()
void Faces_VDF::associer (const Zone_VDF & une_zone_VDF) inline
se lie a la zone
Definition at line 68 of file Faces_VDF.h.
{
  la_zone_VDF=une_zone_VDF;
}
References la_zone_VDF.
calculer_orientation()
void Faces_VDF::calculer_orientation (IntVect & tab_orientation, int & nx, int & ny, int & nz)
Definition at line 38 of file Faces_VDF.cpp.
{
  tab_orientation.resize(nb_faces_tot());
  orientation_.ref(tab_orientation);
  nx=ny=nz=0;
  const Zone& mazone=zone();
  const Domaine& dom=mazone.domaine();
  double dx=0, dy=0, dz=1.e30;
  for(int face=0; face<nb_faces_tot(); face++)
    {
      if(dimension == 2)
        {
          dx = std::fabs(dom.coord(sommet(face, 1), 0)-dom.coord(sommet(face, 0), 0));
          dy = std::fabs(dom.coord(sommet(face, 1), 1)-dom.coord(sommet(face, 0), 1));
        }
      else if(dimension == 3)
        {
          if (nb_som_faces() != 4 )
            {
              Cerr << "We found a VDF face with nb_som_faces = " << nb_som_faces() << ". Aren't you trying to read a VEF mesh in VDF ?" << finl;
              Cerr << "There is a problem with mesh or with chosen discretization." << finl;
              exit();
            }
          dx = std::fabs(dom.coord(sommet(face, 3), 0)-dom.coord(sommet(face, 0), 0));
          dy = std::fabs(dom.coord(sommet(face, 3), 1)-dom.coord(sommet(face, 0), 1));
          dz = std::fabs(dom.coord(sommet(face, 3), 2)-dom.coord(sommet(face, 0), 2));
        }
      if(axi)
        {
          if(dy<0) dy+=2.*M_PI;
        }
      if ( (dx<=dy) && (dx<=dz) )
        {
          tab_orientation(face)=0;
          nx++;
        }
      else if ( (dy<=dx) && (dy<=dz) )
        {
          tab_orientation(face)=1;
          ny++;
        }
      else if ( (dz<=dx) && (dz<=dy) )
        {
          tab_orientation(face)=2;
          nz++;
        }
    }
}
References Objet_U::axi, Cerr, Domaine::coord(), Objet_U::dimension, Zone::domaine(), Process::exit(), finl, M_PI, Faces::nb_faces_tot(), Faces::nb_som_faces(), orientation_, TRUSTVect< _TYPE_ >::ref(), TRUSTVect< _TYPE_ >::resize(), Faces::sommet(), and Faces::zone().
Referenced by Zone_VDF::reordonner().
cree_instance()
Objet_U * Faces_VDF::cree_instance () static
Definition at line 19 of file Faces_VDF.cpp.
duplique()
int Faces_VDF::duplique () const override virtual
Reimplemented from Faces.
Definition at line 19 of file Faces_VDF.cpp.
get_info()
const Type_info * Faces_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Faces.
Definition at line 19 of file Faces_VDF.cpp.
info()
const Type_info * Faces_VDF::info () static
Definition at line 19 of file Faces_VDF.cpp.
orientation() [1/2]
int Faces_VDF::orientation (int i) inline
Definition at line 61 of file Faces_VDF.h.
{
  return orientation_(i);
}
References orientation_.
orientation() [2/2]
int Faces_VDF::orientation (int i) const inline
Definition at line 56 of file Faces_VDF.h.
{
  return orientation_(i);
}
References orientation_.
printOn()
Sortie & Faces_VDF::printOn (Sortie & s) const override protected virtual
Ecrit les faces sur un flots de sortie.
On ecrit:
- le type des faces
- les sommets
- les voisins
On ecrit juste le type Faces::vide_0D, si le nombre de
faces est nul.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Faces.
Definition at line 23 of file Faces_VDF.cpp.
{
  return Faces::printOn(s) ;
}
References Faces::printOn().
readOn()
Entree & Faces_VDF::readOn (Entree & s) override protected virtual
Lit les specifications d'un objet face a
partir d'un flot d'entree.
On lit:
- le type des faces
- les sommets
- les voisins
Et on reordonne les sommets.
Cree un objets Faces avec 0 faces si le type est "vide_0D".
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Faces.
Definition at line 32 of file Faces_VDF.cpp.
{
  return Faces::readOn(s) ;
}
References Faces::readOn().
reordonner()
void Faces_VDF::reordonner (IntVect & tab_orientation)
Definition at line 90 of file Faces_VDF.cpp.
{
  const Zone& mazone=zone();
  int face, derniere, courante, ori;
  int nb_faces_bord=mazone.nb_faces_bord();
  int nb_faces_raccord=mazone.nb_faces_raccord();
  int nb_faces_int=mazone.nb_faces_int();
// On ne trie que les faces interieures :
// #     derniere+=(nb_faces_bord+nb_faces_raccord);
  derniere=(nb_faces_bord+nb_faces_raccord);
  derniere+=nb_faces_int;
  courante=derniere;
  derniere=nb_faces();
// On trie les  faces non frontieres en fonction de leur orientation
  for(ori=0; ori<dimension; ori++)
    {
      while( (courante<derniere)&&(tab_orientation(courante)==ori) )
        courante++;
      for(face=courante; face<derniere; face++)
        {
          if(tab_orientation(face)==ori)
            {
              swap(face, courante);
              while( (courante<derniere)&&(tab_orientation(courante)==ori) )
                courante++;
// face=courante;
            }
        }
    }
}
References Objet_U::dimension, Faces::nb_faces(), Zone::nb_faces_bord(), Zone::nb_faces_int(), Zone::nb_faces_raccord(), swap(), and Faces::zone().
reordonner_pour_debog()
void Faces_VDF::reordonner_pour_debog (IntVect & tab_orientation)
Definition at line 124 of file Faces_VDF.cpp.
{
  const Zone& mazone=zone();
  int face, derniere;
  int nb_faces_bord=mazone.nb_faces_bord();
  int nb_faces_raccord=mazone.nb_faces_raccord();
  int nb_faces_int=mazone.nb_faces_int();
// On ne trie que les faces interieures :
// #     derniere+=(nb_faces_bord+nb_faces_raccord);
  derniere=(nb_faces_bord+nb_faces_raccord);
  derniere+=nb_faces_int;
  derniere=nb_faces();
  /*
  // On trie les  faces non frontieres en fonction de leur orientation
  for(ori=0; ori<dimension; ori++)
  {
  while( (courante<derniere)&&(orientation(courante)==ori) )
  courante++;
  for(face=courante; face<derniere; face++)
  {
  if(orientation(face)==ori)
  {
  swap(face, courante);
  while( (courante<derniere)&&(orientation(courante)==ori) )
  courante++;
  //face=courante;
  }
  }
  }
  */
  Cerr << "ON FAIT UN TRI EXTREMENT CHER POUR AVOIR DES FACES COMME EN SEQUENTIEL"<<finl;
  DoubleTab xv;
  calculer_centres_gravite(xv);
  int ok=0,ordre;
  int marq=0;
// for(marq=(dimension-1)*0;marq>-1*0;marq--)
  for(marq=0; marq<dimension; marq++)
    {
      ok=0;
      Cerr << " ON recommence direction"<<marq<<finl;
      while(ok==0)
        {
          Cerr<<"on recommence"<<finl;
          ok=1;
          for (face=nb_faces_bord+nb_faces_raccord; face<derniere-1; face++)
            {
// assert(dimension==3);
              ordre=-1;
              if (xv(face,marq)>xv(face+1,marq))
                {
                  ordre=marq;
// for (int marq2=dimension-1;marq2<marq;marq2++)
                  for (int marq2=marq+1; marq2<dimension; marq2++)
                    if (xv(face,marq2)<xv(face+1,marq2)) ordre=-1;
                }
// else if ((xv(face,1)>xv(face+1,1))&&(marq>0)) ordre=1;
// else if ((xv(face,0)>xv(face+1,0))&&(marq>1)) ordre=0;
              if (ordre!=-1)
                {
// il faut echanger face et face+1
// Cerr<<"on echange "<<face <<" et " <<face+1 <<" ordre "<<ordre<<" "<<xv(face,ordre)<<" "<<xv(face+1,ordre)<<finl;
                  ok=0;
                  swap(face,face+1);
                  double x;
                  for (int yy=0; yy<dimension; yy++)
                    {
                      x=xv(face,yy);
                      xv(face,yy)=xv(face+1,yy);
                      xv(face+1,yy)=x;
                    }
                }
            }
        }
    }
}
References Faces::calculer_centres_gravite(), Cerr, Objet_U::dimension, finl, Faces::nb_faces(), Zone::nb_faces_bord(), Zone::nb_faces_int(), Zone::nb_faces_raccord(), swap(), and Faces::zone().
self_cast() [1/2]
const Faces_VDF & Faces_VDF::self_cast (const Objet_U & r) static
Definition at line 19 of file Faces_VDF.cpp.
self_cast() [2/2]
Faces_VDF & Faces_VDF::self_cast (Objet_U & r) static
Definition at line 19 of file Faces_VDF.cpp.
swap()
void Faces_VDF::swap (int fac1, int fac2) private
Definition at line 204 of file Faces_VDF.cpp.
{
  assert(fac1 < nb_faces());
  assert(fac2 < nb_faces());
  int tmp=voisin(fac1,0);
  voisin(fac1,0)=voisin(fac2,0);
  voisin(fac2,0)=tmp;
  tmp=voisin(fac1,1);
  voisin(fac1,1)=voisin(fac2,1);
  voisin(fac2,1)=tmp;
  for(int som=0; som<nb_som_faces(); som++)
    {
      tmp=sommet(fac1, som) ;
      sommet(fac1,som)=sommet(fac2,som);
      sommet(fac2,som)=tmp;
    }
  tmp=orientation_(fac1);
  orientation_(fac1)=orientation_(fac2);
  orientation_(fac2)=tmp;
}
References Faces::nb_faces(), Faces::nb_som_faces(), orientation_, Faces::sommet(), and Faces::voisin().
Referenced by reordonner(), and reordonner_pour_debog().
taille_memoire()
unsigned Faces_VDF::taille_memoire () const override virtual
Reimplemented from Faces.
Definition at line 19 of file Faces_VDF.cpp.
zone_VDF()
const Zone_VDF & Faces_VDF::zone_VDF () const inline
Renvoie la zone.
Definition at line 75 of file Faces_VDF.h.
{
  return la_zone_VDF.valeur();
}
References la_zone_VDF, and Ref_Zone_VDF::valeur().
Member Data Documentation
info_obj
const Type_info Faces_VDF::info_obj static
Definition at line 33 of file Faces_VDF.h.
la_zone_VDF
Ref_Zone_VDF Faces_VDF::la_zone_VDF private
Definition at line 51 of file Faces_VDF.h.
Referenced by associer(), and zone_VDF().
orientation_
IntVect Faces_VDF::orientation_ private
orientation des faces : 0 pour une face d'equation x = cte 1 pour une face d'equation y = cte 2 pour une face d'equation z = cte
Definition at line 47 of file Faces_VDF.h.
Referenced by calculer_orientation(), orientation(), and swap().
The documentation for this class was generated from the following files:
src/VDF/Elements/Faces_VDF.h
src/VDF/Elements/Faces_VDF.cpp