TRUST: Ref_Op_Moyenne Class Reference
Ref_Op_Moyenne Class Reference
#include <Ref_Op_Moyenne.h>
Public Member Functions
~Ref_Op_Moyenne ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Op_Moyenne ()
Ref_Op_Moyenne (const Op_Moyenne &)
Ref_Op_Moyenne (const Ref_Op_Moyenne &)
const Op_Moyenne & valeur () const
Op_Moyenne & valeur ()
const Op_Moyenne * operator-> () const
Op_Moyenne * operator-> ()
const Ref_Op_Moyenne & operator= (const Op_Moyenne &)
const Ref_Op_Moyenne & operator= (const Ref_Op_Moyenne &)
operator const Op_Moyenne & () const
operator Op_Moyenne & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Op_Moyenne & self_cast (Objet_U &)
static const Ref_Op_Moyenne & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Op_Moyenne * pointeur_
Detailed Description
Definition at line 28 of file Ref_Op_Moyenne.h.
Constructor & Destructor Documentation
Ref_Op_Moyenne::~Ref_Op_Moyenne ()
Definition at line 26 of file Ref_Op_Moyenne.cpp.
Ref_Op_Moyenne::Ref_Op_Moyenne ()
Definition at line 26 of file Ref_Op_Moyenne.cpp.
Ref_Op_Moyenne::Ref_Op_Moyenne (const Op_Moyenne & t)
Definition at line 26 of file Ref_Op_Moyenne.cpp.
Ref_Op_Moyenne::Ref_Op_Moyenne (const Ref_Op_Moyenne & t)
Definition at line 26 of file Ref_Op_Moyenne.cpp.
Member Function Documentation
Objet_U * Ref_Op_Moyenne::cree_instance () [static]
Definition at line 26 of file Ref_Op_Moyenne.cpp.
int Ref_Op_Moyenne::duplique () const [virtual]
Implements Ref_.
Definition at line 26 of file Ref_Op_Moyenne.cpp.
const Type_info * Ref_Op_Moyenne::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Op_Moyenne.cpp.
const Type_info & Ref_Op_Moyenne::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Ref_Op_Moyenne.cpp.
const Type_info * Ref_Op_Moyenne::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Op_Moyenne.cpp.
Ref_Op_Moyenne::operator const Op_Moyenne & () const
Definition at line 26 of file Ref_Op_Moyenne.cpp.
Ref_Op_Moyenne::operator Op_Moyenne & ()
Definition at line 26 of file Ref_Op_Moyenne.cpp.
const Op_Moyenne * Ref_Op_Moyenne::operator-> () const [inline]
Definition at line 28 of file Ref_Op_Moyenne.h.
Op_Moyenne * Ref_Op_Moyenne::operator-> () [inline]
Definition at line 28 of file Ref_Op_Moyenne.h.
const Ref_Op_Moyenne & Ref_Op_Moyenne::operator= (const Ref_Op_Moyenne & t)
Definition at line 26 of file Ref_Op_Moyenne.cpp.
const Ref_Op_Moyenne & Ref_Op_Moyenne::operator= (const Op_Moyenne & t)
Definition at line 26 of file Ref_Op_Moyenne.cpp.
Sortie & Ref_Op_Moyenne::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Op_Moyenne.cpp.
Entree & Ref_Op_Moyenne::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Op_Moyenne.cpp.
const Ref_Op_Moyenne & Ref_Op_Moyenne::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 26 of file Ref_Op_Moyenne.cpp.
Ref_Op_Moyenne & Ref_Op_Moyenne::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 26 of file Ref_Op_Moyenne.cpp.
void Ref_Op_Moyenne::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Ref_Op_Moyenne.cpp.
unsigned Ref_Op_Moyenne::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Ref_Op_Moyenne.cpp.
const Op_Moyenne & Ref_Op_Moyenne::valeur () const [inline]
Definition at line 28 of file Ref_Op_Moyenne.h.
Referenced by Op_Correlation::la_moyenne_a(), Op_Correlation::la_moyenne_b(), and Op_Ecart_type::moyenne().
Op_Moyenne & Ref_Op_Moyenne::valeur () [inline]
Definition at line 28 of file Ref_Op_Moyenne.h.
Member Data Documentation
const Type_info Ref_Op_Moyenne::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Op_Moyenne.h.
Op_Moyenne* Ref_Op_Moyenne::pointeur_ [private]
Definition at line 28 of file Ref_Op_Moyenne.h.
The documentation for this class was generated from the following files:
src/Kernel/Statistiques_temps/Ref_Op_Moyenne.h
src/Kernel/Statistiques_temps/Ref_Op_Moyenne.cpp