TRUST: Eval_Quick_VDF_Face Class Reference
Eval_Quick_VDF_Face Class Reference
class Eval_Quick_VDF_Face
Evaluateur VDF pour la convection
Le champ convecte est un Champ_Face
Schema de convection Quick
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
#include <Eval_Quick_VDF_Face.h>
Public Member Functions
Eval_Quick_VDF_Face ()
int calculer_arete_fluide () const
int calculer_arete_paroi () const
int calculer_arete_paroi_fluide () const
int calculer_arete_symetrie () const
int calculer_arete_interne () const
int calculer_arete_mixte () const
int calculer_fa7_sortie_libre () const
int calculer_arete_periodicite () const
int calculer_arete_symetrie_paroi () const
int calculer_arete_symetrie_fluide () const
double flux_fa7_sortie_libre (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double flux_fa7_elem (const DoubleTab &, int, int, int) const
double flux_arete_interne (const DoubleTab &, int, int, int, int) const
double flux_arete_mixte (const DoubleTab &, int, int, int, int) const
double flux_arete_paroi (const DoubleTab &, int, int, int, int) const
double flux_arete_symetrie (const DoubleTab &, int, int, int, int) const
void flux_arete_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_paroi_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_periodicite (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_symetrie_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
double flux_arete_symetrie_paroi (const DoubleTab &, int, int, int, int) const
void flux_fa7_elem (const DoubleTab &, int, int, int, DoubleVect &flux) const
void flux_fa7_sortie_libre (const DoubleTab &, int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void flux_arete_interne (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_mixte (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_symetrie (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_paroi (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_paroi_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_periodicite (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_symetrie_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_symetrie_paroi (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
Private Member Functions
double dist_face (int n1, int n2, int k) const
double dist_face_period (int n1, int n2, int k) const
double dim_face (int, int) const
int face_amont_conj (int, int, int) const
int face_amont_princ (int, int) const
double dist_elem (int n1, int n2, int k) const
double dist_elem_period (int n1, int n2, int k) const
double dim_elem (int, int) const
Detailed Description
class Eval_Quick_VDF_Face
Evaluateur VDF pour la convection
Le champ convecte est un Champ_Face
Schema de convection Quick
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
See also:
Eval_Conv_VDF
Definition at line 45 of file Eval_Quick_VDF_Face.h.
Constructor & Destructor Documentation
Eval_Quick_VDF_Face::Eval_Quick_VDF_Face () [inline]
Definition at line 137 of file Eval_Quick_VDF_Face.h.
{
}
Member Function Documentation
int Eval_Quick_VDF_Face::calculer_arete_fluide () const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 145 of file Eval_Quick_VDF_Face.h.
{
  return 1;
}
int Eval_Quick_VDF_Face::calculer_arete_interne () const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 180 of file Eval_Quick_VDF_Face.h.
{
  return 1;
}
int Eval_Quick_VDF_Face::calculer_arete_mixte () const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 188 of file Eval_Quick_VDF_Face.h.
{
  return 1;
}
int Eval_Quick_VDF_Face::calculer_arete_paroi () const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 154 of file Eval_Quick_VDF_Face.h.
{
  return 0;
}
int Eval_Quick_VDF_Face::calculer_arete_paroi_fluide () const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 163 of file Eval_Quick_VDF_Face.h.
{
  return 1;
}
int Eval_Quick_VDF_Face::calculer_arete_periodicite () const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 204 of file Eval_Quick_VDF_Face.h.
{
  return 1;
}
int Eval_Quick_VDF_Face::calculer_arete_symetrie () const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 172 of file Eval_Quick_VDF_Face.h.
{
  return 0;
}
int Eval_Quick_VDF_Face::calculer_arete_symetrie_fluide () const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 220 of file Eval_Quick_VDF_Face.h.
{
  return 1;
}
int Eval_Quick_VDF_Face::calculer_arete_symetrie_paroi () const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 212 of file Eval_Quick_VDF_Face.h.
{
  return 0;
}
int Eval_Quick_VDF_Face::calculer_fa7_sortie_libre () const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 196 of file Eval_Quick_VDF_Face.h.
{
  return 1;
}
double Eval_Quick_VDF_Face::dim_elem (int n1, int k) const [inline, private]
Definition at line 301 of file Eval_Quick_VDF_Face.h.
References Evaluateur_VDF::la_zone.
Referenced by flux_fa7_elem().
{
  return la_zone->dim_elem(n1,k);
}
double Eval_Quick_VDF_Face::dim_face (int n1, int k) const [inline, private]
Definition at line 306 of file Eval_Quick_VDF_Face.h.
References Evaluateur_VDF::la_zone.
Referenced by flux_arete_interne().
{
  return la_zone->dim_face(n1,k);
}
double Eval_Quick_VDF_Face::dist_elem (int n1, int n2, int k) const [inline, private]
Definition at line 121 of file Eval_Quick_VDF_Face.h.
References Evaluateur_VDF::la_zone.
  {
    return la_zone->dist_elem(n1,n2,k);
  };
double Eval_Quick_VDF_Face::dist_elem_period (int n1, int n2, int k) const [inline, private]
Definition at line 125 of file Eval_Quick_VDF_Face.h.
References Evaluateur_VDF::la_zone.
Referenced by flux_fa7_elem().
  {
    return la_zone->dist_elem_period(n1,n2,k);
  };
double Eval_Quick_VDF_Face::dist_face (int n1, int n2, int k) const [inline, private]
Reimplemented from Evaluateur_VDF.
Definition at line 110 of file Eval_Quick_VDF_Face.h.
References Evaluateur_VDF::la_zone.
Referenced by flux_arete_interne().
  {
    return la_zone->dist_face(n1,n2,k);
  };
double Eval_Quick_VDF_Face::dist_face_period (int n1, int n2, int k) const [inline, private]
Reimplemented from Evaluateur_VDF.
Definition at line 114 of file Eval_Quick_VDF_Face.h.
References Evaluateur_VDF::la_zone.
Referenced by flux_arete_interne().
  {
    return la_zone->dist_face_period(n1,n2,k);
  };
int Eval_Quick_VDF_Face::face_amont_conj (int num_face, int i, int k) const [inline, private]
Definition at line 311 of file Eval_Quick_VDF_Face.h.
References Evaluateur_VDF::la_zone.
Referenced by flux_arete_interne().
{
  return la_zone->face_amont_conj(num_face, i, k);
}
int Eval_Quick_VDF_Face::face_amont_princ (int num_face, int i) const [inline, private]
Definition at line 316 of file Eval_Quick_VDF_Face.h.
References Evaluateur_VDF::la_zone.
Referenced by flux_fa7_elem().
{
  return la_zone->face_amont_princ(num_face, i);
}
void Eval_Quick_VDF_Face::flux_arete_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 326 of file Eval_Quick_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux,psc;
  int ori;
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    flux=inco[fac3]*psc ;
  else
    {
      ori =orientation(fac3);
      flux = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac1,ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac2,ori,la_zcl)) * psc ;
    }
  flux3 = -flux;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*inco[fac2];
  flux1_2 = -flux;
}
void Eval_Quick_VDF_Face::flux_arete_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 644 of file Eval_Quick_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<flux3.size(); k++)
      flux3(k) = -inco(fac3,k)*psc ;
  else
    {
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac1,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac2,k,ori,la_zcl)) * psc ;
    }
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_Quick_VDF_Face::flux_arete_interne (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, DoubleVect & flux) const [inline]
< Schema amont
< Schema quick
< (psc <= 0)
< Schema amont
< Schema quick
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 680 of file Eval_Quick_VDF_Face.h.
References conv_quick_sharp_moins(), conv_quick_sharp_plus(), dim_face(), dist_face(), dist_face_period(), Eval_Conv_VDF::dt_vitesse, face_amont_conj(), Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  int ncomp = flux.size();
  double psc = 0.25* (dt_vitesse[fac1]*porosite(fac1) + dt_vitesse[fac2]*porosite(fac2))
               * (surface(fac1) + surface(fac2));
  int ori = orientation(fac1);
  int num0_0 = face_amont_conj(fac3,ori,0);
  int num1_1 = face_amont_conj(fac4,ori,1);
  if (psc > 0)
    if (num0_0 == -1) //!< Schema amont
      for (k=0; k<ncomp; k++)
        flux(k) = -psc*inco(fac3,k);
    else //!< Schema quick
      {
        double dx = dist_face(fac3,fac4,ori);
        double dm = dim_face(fac3,ori);
        double dxam = dist_face_period(num0_0,fac3,ori);
        ArrOfDouble vit_0(ncomp);
        ArrOfDouble vit_0_0(ncomp);
        ArrOfDouble vit_1(ncomp);
        for (k=0; k<ncomp; k++)
          {
            vit_0(k) = inco(fac3,k);
            vit_0_0(k) = inco(num0_0,k);
            vit_1(k) = inco(fac4,k);
            flux(k) = -conv_quick_sharp_plus(psc,vit_0(k),vit_1(k),vit_0_0(k),dx,dm,dxam);
          }
      }
  else //!< (psc <= 0)
    if (num1_1 == -1) //!< Schema amont
      for (k=0; k<ncomp; k++)
        flux(k) = -psc*inco(fac4,k);
    else //!< Schema quick
      {
        double dx = dist_face(fac3,fac4,ori);
        double dm = dim_face(fac4,ori);
        double dxam = dist_face_period(fac4,num1_1,ori);
        ArrOfDouble vit_0(ncomp);
        ArrOfDouble vit_1(ncomp);
        ArrOfDouble vit_1_1(ncomp);
        for (k=0; k<ncomp; k++)
          {
            vit_0(k) = inco(fac3,k);
            vit_1(k) = inco(fac4,k);
            vit_1_1(k) = inco(num1_1,k);
            flux(k) = -conv_quick_sharp_moins(psc,vit_0(k),vit_1(k),vit_1_1(k),dx,dm,dxam);
          }
      }
}
double Eval_Quick_VDF_Face::flux_arete_interne (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4) const [inline]
< Schema amont
< Schema quick
< (psc <= 0)
< Schema amont
< Schema quick
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 362 of file Eval_Quick_VDF_Face.h.
References conv_quick_sharp_moins(), conv_quick_sharp_plus(), dim_face(), dist_face_period(), Eval_Conv_VDF::dt_vitesse, face_amont_conj(), Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
Referenced by flux_arete_periodicite().
{
  double flux;
  double psc = 0.25* (dt_vitesse[fac1]*porosite(fac1) + dt_vitesse[fac2]*porosite(fac2))
               * (surface(fac1) + surface(fac2));
  int ori = orientation(fac1);
  int num0_0 = face_amont_conj(fac3,ori,0);
  int num1_1 = face_amont_conj(fac4,ori,1);
  if (psc > 0)
    if (num0_0 == -1) //!< Schema amont
      flux = psc*inco[fac3];
    else //!< Schema quick
      {
        double dx = dist_face_period(fac3,fac4,ori);
        double dm = dim_face(fac3,ori);
        double dxam = dist_face_period(num0_0,fac3,ori);
        double vit_0 = inco[fac3];
        double vit_0_0 = inco[num0_0];
        double vit_1 = inco[fac4];
// Cerr<<dx <<" tailles1 "<<dm<<" "<<dxam<<finl;
        flux = conv_quick_sharp_plus(psc,vit_0,vit_1,vit_0_0,dx,dm,dxam);
      }
  else //!< (psc <= 0)
    if (num1_1 == -1) //!< Schema amont
      flux = psc*inco[fac4];
    else //!< Schema quick
      {
        double dx = dist_face_period(fac3,fac4,ori);
        double dm = dim_face(fac4,ori);
        double dxam = dist_face_period(fac4,num1_1,ori);
// Cerr<<dx <<" tailles "<<dm<<" "<<dxam<<finl;
        double vit_0 = inco[fac3];
        double vit_1 = inco[fac4];
        double vit_1_1 = inco[num1_1];
        flux = conv_quick_sharp_moins(psc,vit_0,vit_1,vit_1_1,dx,dm,dxam);
      }
  return -flux;
}
void Eval_Quick_VDF_Face::flux_arete_mixte (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, DoubleVect & flux) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 739 of file Eval_Quick_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] )  *
               ( surface[fac1] + surface[fac2] );
  if (psc>0)
    for (k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(fac3,k);
  else
    for (k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(fac4,k);
}
double Eval_Quick_VDF_Face::flux_arete_mixte (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 410 of file Eval_Quick_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] )  *
               ( surface[fac1] + surface[fac2] );
  if (psc>0)
    flux = psc*inco[fac3];
  else
    flux = psc*inco[fac4];
  return -flux;
}
void Eval_Quick_VDF_Face::flux_arete_paroi (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 759 of file Eval_Quick_VDF_Face.h.
{
  ;
}
double Eval_Quick_VDF_Face::flux_arete_paroi (const DoubleTab & , int , int , int , int) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 430 of file Eval_Quick_VDF_Face.h.
{
  return 0;
}
void Eval_Quick_VDF_Face::flux_arete_paroi_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 769 of file Eval_Quick_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<flux3.size(); k++)
      flux3(k) = -inco(fac3,k)*psc;
  else
    {
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac1-premiere_face_bord,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac2-premiere_face_bord,k,ori,la_zcl))* psc ;
    }
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_Quick_VDF_Face::flux_arete_paroi_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 439 of file Eval_Quick_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double flux,psc;
  int ori;
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    flux=inco[fac3]*psc ;
  else
    {
      ori =orientation(fac3);
      flux = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac1-premiere_face_bord, ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac2-premiere_face_bord, ori,la_zcl))* psc ;
    }
  flux3 = -flux;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*inco[fac2];
  flux1_2 = -flux;
}
void Eval_Quick_VDF_Face::flux_arete_periodicite (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, DoubleVect & flux3_4, DoubleVect & flux1_2) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 804 of file Eval_Quick_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  double psc;
  int k;
// On calcule le flux convectif entre les volumes de controle associes a fac3 et fac4:
  psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                 dt_vitesse[fac2]*porosite[fac2] ) *
        ( surface[fac1] + surface[fac2] );
  if (psc>0)
    for (k=0; k<flux3_4.size(); k++)
      flux3_4(k) = -psc*inco(fac3,k);
  else
    for (k=0; k<flux3_4.size(); k++)
      flux3_4(k) = -psc*inco(fac4,k);
// On calcule le flux convectifs entre les volumes de controle associes a fac1 et fac2:
  psc = 0.25 * ( dt_vitesse[fac3]*porosite[fac3] +
                 dt_vitesse[fac4]*porosite[fac4] ) *
        ( surface[fac3] + surface[fac4] );
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux3_4.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_Quick_VDF_Face::flux_arete_periodicite (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, double & flux3_4, double & flux1_2) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 475 of file Eval_Quick_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, flux_arete_interne(), Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  flux3_4=flux_arete_interne(inco,fac1, fac2,fac3, fac4) ;
  flux1_2=flux_arete_interne(inco,fac3, fac4,fac1, fac2) ;
  return;
  double flux;
  double psc;
// On calcule le flux convectif entre les volumes de controle associes a fac3 et fac4:
  psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                 dt_vitesse[fac2]*porosite[fac2] ) *
        ( surface[fac1] + surface[fac2] );
  if (psc>0)
    flux = psc*inco[fac3];
  else
    flux = psc*inco[fac4];
  flux3_4 = -flux;
// On calcule le flux convectif entre les volumes de controle associes a fac1 et fac2:
  psc = 0.25 * ( dt_vitesse[fac3]*porosite[fac3] +
                 dt_vitesse[fac4]*porosite[fac4] ) *
        ( surface[fac3] + surface[fac4] );
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*inco[fac2];
  flux1_2 = -flux;
}
double Eval_Quick_VDF_Face::flux_arete_symetrie (const DoubleTab & , int , int , int , int) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 517 of file Eval_Quick_VDF_Face.h.
{
  return 0;
}
void Eval_Quick_VDF_Face::flux_arete_symetrie (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 842 of file Eval_Quick_VDF_Face.h.
{
  ;
}
void Eval_Quick_VDF_Face::flux_arete_symetrie_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 525 of file Eval_Quick_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord_sym(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux,psc;
  int ori;
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    flux=inco[fac3]*psc ;
  else
    {
      ori =orientation(fac3);
      flux = 0.5*(Champ_Face_get_val_imp_face_bord_sym(inco,inconnue->temps(),fac1,ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord_sym(inco,inconnue->temps(),fac2,ori,la_zcl)) * psc ;
    }
  flux3 = -flux;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*inco[fac2];
  flux1_2 = -flux;
}
void Eval_Quick_VDF_Face::flux_arete_symetrie_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 851 of file Eval_Quick_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<flux3.size(); k++)
      flux3(k) = -inco(fac3,k)*psc ;
  else
    {
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac1,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac2,k,ori,la_zcl)) * psc ;
    }
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_Quick_VDF_Face::flux_arete_symetrie_paroi (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 886 of file Eval_Quick_VDF_Face.h.
{
  ;
}
double Eval_Quick_VDF_Face::flux_arete_symetrie_paroi (const DoubleTab & , int , int , int , int) const [inline]
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 560 of file Eval_Quick_VDF_Face.h.
{
  return 0;
}
void Eval_Quick_VDF_Face::flux_fa7_elem (const DoubleTab & inco, int num_elem, int fac1, int fac2, DoubleVect & flux) const [inline]
< Schema amont
< (psc < 0)
< Schema amont
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 895 of file Eval_Quick_VDF_Face.h.
References conv_quick_sharp_moins(), conv_quick_sharp_plus(), dim_elem(), dist_elem_period(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, face_amont_princ(), Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  int num0_0 = face_amont_princ(fac1,0);
  int num1_1 = face_amont_princ(fac2,1);
  int ncomp = flux.size();
  double psc = 0.25 * (dt_vitesse[fac1]+dt_vitesse[fac2])*(surface(fac1)+surface(fac2));
  if  (psc > 0)
    {
      if (num0_0 == -1) //!< Schema amont
        for (k=0; k<ncomp; k++)
          flux(k) = -psc*inco(fac1,k)*porosite(fac1);
      else
        {
          int ori = orientation(fac1);
          double dx = dim_elem(num_elem,ori);
          int elem_amont = elem_(fac1,0);
          double dm = dist_elem_period(elem_amont,num_elem,ori);
          double dxam = dim_elem(elem_amont,ori);
          ArrOfDouble vit_0(ncomp);
          ArrOfDouble vit_0_0(ncomp);
          ArrOfDouble vit_1(ncomp);
          for (k=0; k<ncomp; k++)
            {
              vit_0(k) = inco(fac1,k)*porosite(fac1);
              vit_0_0(k) = inco(num0_0,k)*porosite(num0_0);
              vit_1(k) = inco(fac2,k)*porosite(fac2);
              flux(k) = -conv_quick_sharp_plus(psc,vit_0(k),vit_1(k),vit_0_0(k),dx,dm,dxam);
            }
        }
    }
  else //!< (psc < 0)
    {
      if (num1_1 == -1) //!< Schema amont
        for (k=0; k<ncomp; k++)
          flux(k) = -psc*inco(fac2,k)*porosite(fac2);
      else
        {
          int ori = orientation(fac2);
          double dx = dim_elem(num_elem,ori);
          int elem_amont = elem_(fac2,1);
          double dm = dist_elem_period(num_elem,elem_amont,ori);
          double dxam = dim_elem(elem_amont,ori);
          ArrOfDouble vit_0(ncomp);
          ArrOfDouble vit_1(ncomp);
          ArrOfDouble vit_1_1(ncomp);
          for (k=0; k<ncomp; k++)
            {
              vit_0(k) = inco(fac1,k)*porosite(fac1);
              vit_1(k) = inco(fac2,k)*porosite(fac2);
              vit_1_1(k) = inco(num1_1,k)*porosite(num1_1);
              flux(k) = -conv_quick_sharp_moins(psc,vit_0(k),vit_1(k),vit_1_1(k),dx,dm,dxam);
            }
        }
    }
}
double Eval_Quick_VDF_Face::flux_fa7_elem (const DoubleTab & inco, int num_elem, int fac1, int fac2) const [inline]
< Schema amont
< (psc < 0)
< Schema amont
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 569 of file Eval_Quick_VDF_Face.h.
References conv_quick_sharp_moins(), conv_quick_sharp_plus(), dim_elem(), dist_elem_period(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, face_amont_princ(), Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  int num0_0 = face_amont_princ(fac1,0);
  int num1_1 = face_amont_princ(fac2,1);
  double psc = 0.25 * (dt_vitesse[fac1]+dt_vitesse[fac2])*(surface(fac1)+surface(fac2));
  if  (psc > 0)
    {
      if (num0_0 == -1) //!< Schema amont
        flux = psc*inco[fac1]*porosite(fac1);
      else
        {
          int ori = orientation(fac1);
          double dx = dim_elem(num_elem,ori);
          int elem_amont = elem_(fac1,0);
          double dm = dist_elem_period(elem_amont,num_elem,ori);
          double dxam = dim_elem(elem_amont,ori);
          double vit_0 = inco[fac1]*porosite(fac1);
          double vit_0_0 = inco[num0_0]*porosite(num0_0);
          double vit_1 = inco[fac2]*porosite(fac2);
          flux = conv_quick_sharp_plus(psc,vit_0,vit_1,vit_0_0,dx,dm,dxam);
        }
    }
  else //!< (psc < 0)
    {
      if (num1_1 == -1) //!< Schema amont
        flux = psc*inco[fac2]*porosite(fac2);
      else
        {
          int ori = orientation(fac2);
          double dx = dim_elem(num_elem,ori);
          int elem_amont = elem_(fac2,1);
          double dm = dist_elem_period(num_elem,elem_amont,ori);
          double dxam = dim_elem(elem_amont,ori);
          double vit_0 = inco[fac1]*porosite(fac1);
          double vit_1 = inco[fac2]*porosite(fac2);
          double vit_1_1 = inco[num1_1]*porosite(num1_1);
          flux = conv_quick_sharp_moins(psc,vit_0,vit_1,vit_1_1,dx,dm,dxam);
        }
    }
  return -flux;
}
double Eval_Quick_VDF_Face::flux_fa7_sortie_libre (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1) const [inline]
< (elem2 != -1)
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 617 of file Eval_Quick_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::orientation, Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  double flux;
  double psc = dt_vitesse[face]*surface(face);
  int elem1 = elem_(face,0);
  if (elem1 != -1)
    if (psc > 0)
      flux = psc*inco[face];
    else
      flux = psc*la_cl.val_ext(face-num1,orientation(face));
  else //!< (elem2 != -1)
    if (psc < 0)
      flux = psc*inco[face];
    else
      flux = psc*la_cl.val_ext(face-num1,orientation(face));
  return -flux;
}
void Eval_Quick_VDF_Face::flux_fa7_sortie_libre (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const [inline]
< (elem2 != -1)
Reimplemented from Eval_Amont_VDF_Face.
Definition at line 954 of file Eval_Quick_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, DoubleVect::size(), Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  int k;
  double psc = dt_vitesse[face]*surface(face);
  int elem1 = elem_(face,0);
  if (elem1 != -1)
    if (psc > 0)
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*inco(face,k);
    else
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*la_cl.val_ext(face-num1,k);
  else //!< (elem2 != -1)
    if (psc < 0)
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*inco(face,k);
    else
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*la_cl.val_ext(face-num1,k);
}
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs/Eval_Quick_VDF_Face.h