TRUST: Extruder_en3 Class Reference
Extruder_en3 Class Reference
Classe Extruder_en3
Cette classe est un interprete qui sert a lire et executer
la directive Extruder_en3 :
Extruder_en3 { nb_domaine nom_domaine1 nom_domaine2 .. direction nb_tranches }
Cette directive est a utiliser en discretisation VEF 2D pour obtenir
un maillage 3D par extrusion puis decoupage.
Ici chaque triangle est extruder en prisme, puis decoupe en 3 tetras.
#include <Extruder_en3.h>
Public Member Functions
~Extruder_en3 ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Extruder_en3 ()
Entree & interpreter_ (Entree &) override
Fonction principale de l'interprete Extruder_en3
Triangule 1 a 1 toutes les zones du domaine
specifie par la directive.
On triangule la zone grace a la methode:
void Extruder_en3::extruder(Zone& zone) const
Extruder_en3 signifie ici transformer en triangle des
elements geometrique d'une zone.
void setDirection (double lx, double ly, double lz)
void setNbTranches (int n)
void extruder (Domaine &, const IntVect &)
Extrusion d'un domaine surfacique.
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Extruder_en3 & self_cast (Objet_U &)
static const Extruder_en3 & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Protected Member Functions inherited from Interprete_geometrique_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void construire_bords (Domaine &, Faces &, int, int, const IntVect &)
Creation des bords du domaine extrude.
void construire_bord_lateral (Faces &, Faces &, int, const IntVect &)
Creation d'un bord lateral.
Private Attributes
ArrOfDouble direction_
int NZ_
Nom nom_dvt_
Nom nom_derriere_
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Classe Extruder_en3
Cette classe est un interprete qui sert a lire et executer
la directive Extruder_en3 :
Extruder_en3 { nb_domaine nom_domaine1 nom_domaine2 .. direction nb_tranches }
Cette directive est a utiliser en discretisation VEF 2D pour obtenir
un maillage 3D par extrusion puis decoupage.
Ici chaque triangle est extruder en prisme, puis decoupe en 3 tetras.
Definition at line 39 of file Extruder_en3.h.
Constructor & Destructor Documentation
~Extruder_en3()
Extruder_en3::~Extruder_en3 ()
Definition at line 24 of file Extruder_en3.cpp.
Extruder_en3()
Extruder_en3::Extruder_en3 ()
Definition at line 26 of file Extruder_en3.cpp.
{
  nom_dvt_ = "devant";
  nom_derriere_ = "derriere";
  direction_.resize(3,Array_base::NOCOPY_NOINIT);
}
References direction_, Array_base::NOCOPY_NOINIT, nom_derriere_, nom_dvt_, and TRUSTArray< _TYPE_ >::resize().
Member Function Documentation
construire_bord_lateral()
void Extruder_en3::construire_bord_lateral (Faces & les_faces_du_bord, Faces & les_faces, int oldnbsom, const IntVect & num) private
Creation d'un bord lateral.
Definition at line 445 of file Extruder_en3.cpp.
{
// oldnbsom = number of nodes of the 2D mesh
  int nb_faces = les_faces_du_bord.nb_faces();
  IntTab les_sommets(2*nb_faces*NZ_,3);
  for (int i=0; i<nb_faces; i++)
    {
      int i0=les_faces_du_bord.sommet(i,0);
      int i1=les_faces_du_bord.sommet(i,1);
      int ii0= num[i0];
      int ii1= num[i1];
      for (int k=0; k<NZ_; k++)
        {
          int j=2*nb_faces*k+2*i;
          if (ii0>ii1)
            {
              les_sommets(j,0) = i0;
              les_sommets(j,1) = i1;
              les_sommets(j,2) = i0+oldnbsom;
              les_sommets(j+1,0) = i1;
              les_sommets(j+1,1) = i0+oldnbsom;
              les_sommets(j+1,2) = i1+oldnbsom;
            }
          else
            {
              les_sommets(j,0) = i0;
              les_sommets(j,1) = i1;
              les_sommets(j,2) = i1+oldnbsom;
              les_sommets(j+1,0) = i0;
              les_sommets(j+1,1) = i0+oldnbsom;
              les_sommets(j+1,2) = i1+oldnbsom;
            }
          i0+=oldnbsom;
          i1+=oldnbsom;
        }
    }
  les_faces_du_bord.typer(Faces::triangle_3D);
  les_faces_du_bord.les_sommets().ref(les_sommets);
  les_faces_du_bord.voisins().resize(2*nb_faces*NZ_, 2);
  les_faces_du_bord.voisins()=-1;
}
References Faces::les_sommets(), Faces::nb_faces(), NZ_, TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), Faces::sommet(), Faces::triangle_3D, Faces::typer(), and Faces::voisins().
Referenced by construire_bords().
construire_bords()
void Extruder_en3::construire_bords (Domaine & dom, Faces & les_faces, int oldnbsom, int oldsz, const IntVect & num) private
Creation des bords du domaine extrude.
Definition at line 359 of file Extruder_en3.cpp.
{
  Zone& zone = dom.zone(0);
  IntTab& les_elems=zone.les_elems();
// Les bords:
  {
    LIST_CURSEUR(Bord) curseur(zone.faces_bord());
    while(curseur)
      {
        Faces& les_faces_du_bord=curseur->faces();
        construire_bord_lateral(les_faces_du_bord, les_faces, oldnbsom, num);
        ++curseur;
      }
  }
// Les raccords:
  {
    LIST_CURSEUR(Raccord) curseur(zone.faces_raccord());
    while(curseur)
      {
        Faces& les_faces_du_bord=curseur.valeur()->faces();
        construire_bord_lateral(les_faces_du_bord, les_faces, oldnbsom, num);
        ++curseur;
      }
  }
// Devant
  if(nom_dvt_=="NULL")
    {
      Cerr << "We don't associate any boundary to the front of the domain " << dom.le_nom() << finl;
    }
  else
    {
      Bord& devant = zone.faces_bord().add(Bord());
      devant.nommer(nom_dvt_);
      Faces& les_faces_dvt=devant.faces();
      les_faces_dvt.typer(Faces::triangle_3D);
      IntTab som_dvt(oldsz, 3);
      les_faces_dvt.voisins().resize(oldsz, 2);
      les_faces_dvt.voisins()=-1;
      for (int i=0; i<oldsz; i++)
        {
          int i0=les_elems(3*i,0);
          int i1=les_elems(3*i,1);
          int i2=les_elems(3*i,2);
          som_dvt(i,0) = i0;
          som_dvt(i,1) = i1;
          som_dvt(i,2) = i2;
        }
      les_faces_dvt.les_sommets().ref(som_dvt);
    }
// Derriere
  if(nom_derriere_=="NULL")
    {
      Cerr << "We don't associate any boundary to the back of the domain " << dom.le_nom() << finl;
    }
  else
    {
      Bord& derriere = zone.faces_bord().add(Bord());
      derriere.nommer(nom_derriere_);
      Faces& les_faces_der=derriere.faces();
      les_faces_der.typer(Faces::triangle_3D);
      IntTab som_der(oldsz, 3);
      les_faces_der.voisins().resize(oldsz, 2);
      les_faces_der.voisins()=-1;
      for (int i=0; i<oldsz; i++)
        {
          int i0=les_elems(3*i,0);
          int i1=les_elems(3*i,1);
          int i2=les_elems(3*i,2);
          som_der(i,0) = i0+oldnbsom*NZ_;
          som_der(i,1) = i1+oldnbsom*NZ_;
          som_der(i,2) = i2+oldnbsom*NZ_;
        }
      les_faces_der.les_sommets().ref(som_der);
    }
}
References List_Bord::add(), Cerr, construire_bord_lateral(), Frontiere::faces(), Zone::faces_bord(), Zone::faces_raccord(), finl, Domaine::le_nom(), Zone::les_elems(), Faces::les_sommets(), LIST_CURSEUR, nom_derriere_, nom_dvt_, Frontiere::nommer(), NZ_, TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), Faces::triangle_3D, Faces::typer(), Faces::voisins(), and Domaine::zone().
Referenced by extruder().
cree_instance()
Objet_U * Extruder_en3::cree_instance () static
Definition at line 24 of file Extruder_en3.cpp.
duplique()
int Extruder_en3::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Extruder_en3.cpp.
extruder()
void Extruder_en3::extruder (Domaine & dom, const IntVect & num)
Extrusion d'un domaine surfacique.
< Tableau dont on aura pas besoin
< les nouveaux elements
Definition at line 156 of file Extruder_en3.cpp.
{
  Zone& zone = dom.zone(0);
  if(zone.type_elem()->que_suis_je() == "Triangle")
    {
      int oldnbsom = zone.nb_som();
      IntTab& les_elems=zone.les_elems();
      int oldsz=les_elems.dimension(0);
      double dx = direction_[0]/NZ_;
      double dy = direction_[1]/NZ_;
      double dz = direction_[2]/NZ_;
      Faces les_faces;
      {
// bloc a factoriser avec Zone_VF.cpp :
        Type_Face type_face = zone.type_elem().type_face(0);
        les_faces.typer(type_face);
        les_faces.associer_zone(zone);
        Static_Int_Lists connectivite_som_elem;
        const int     nb_sommets_tot = zone.domaine().nb_som_tot();
        const IntTab&    elements       = zone.les_elems();
        construire_connectivite_som_elem(nb_sommets_tot,
                                         elements,
                                         connectivite_som_elem,
                                         1 /* include virtual elements */);
        Faces_builder faces_builder;
        IntTab elem_faces; //!< Tableau dont on aura pas besoin
        faces_builder.creer_faces_reeles(zone,
                                         connectivite_som_elem,
                                         les_faces,
                                         elem_faces);
      }
      int newnbsom = oldnbsom*(NZ_+1);
      DoubleTab new_soms(newnbsom, 3);
      DoubleTab& coord_sommets=dom.les_sommets();
      Objet_U::dimension=3;
// les sommets du maillage 2D sont translates en premier
      for (int i=0; i<oldnbsom; i++)
        {
          double x = coord_sommets(i,0);
          double y = coord_sommets(i,1);
          double z=0.;
          if (coord_sommets.dimension(1)>2)
            z=coord_sommets(i,2);
          for (int k=0; k<=NZ_; k++)
            {
              new_soms(k*oldnbsom+i,0)=x;
              new_soms(k*oldnbsom+i,1)=y;
              new_soms(k*oldnbsom+i,2)=z;
              x += dx;
              y += dy;
              z += dz;
            }
        }
      coord_sommets.resize(0);
      dom.ajouter(new_soms);
      int newnbelem = 3*NZ_*oldsz;
      IntTab new_elems(newnbelem, 4); //!< les nouveaux elements
      for (int i=0; i<oldsz; i++)
        {
          int i1=les_elems(i,0);
          int i2=les_elems(i,1);
          int i3=les_elems(i,2);
          int ii1 = num[i1];
          int ii2 = num[i2];
          int ii3 = num[i3];
          int i4=i1+oldnbsom;
          int i5=i2+oldnbsom;
          int i6=i3+oldnbsom;
          for (int k=0; k<NZ_; k++)
            {
              int j=3*k*oldsz+3*i;
              if (ii1>ii2 && ii1>ii3)
                {
                  new_elems(j,0) = i1;
                  new_elems(j,1) = i2;
                  new_elems(j,2) = i3;
                  new_elems(j,3) = i4;
                  if (ii3>ii2)
                    {
                      new_elems(j+1,0) = i2;
                      new_elems(j+1,1) = i3;
                      new_elems(j+1,2) = i4;
                      new_elems(j+1,3) = i6;
                      new_elems(j+2,0) = i2;
                      new_elems(j+2,1) = i4;
                      new_elems(j+2,2) = i5;
                      new_elems(j+2,3) = i6;
                    }
                  else
                    {
                      new_elems(j+1,0) = i2;
                      new_elems(j+1,1) = i3;
                      new_elems(j+1,2) = i4;
                      new_elems(j+1,3) = i5;
                      new_elems(j+2,0) = i3;
                      new_elems(j+2,1) = i4;
                      new_elems(j+2,2) = i5;
                      new_elems(j+2,3) = i6;
                    }
                }
              if (ii2>ii1 && ii2>ii3)
                {
                  new_elems(j,0) = i1;
                  new_elems(j,1) = i2;
                  new_elems(j,2) = i3;
                  new_elems(j,3) = i5;
                  if (ii1>ii3)
                    {
                      new_elems(j+1,0) = i1;
                      new_elems(j+1,1) = i3;
                      new_elems(j+1,2) = i4;
                      new_elems(j+1,3) = i5;
                      new_elems(j+2,0) = i3;
                      new_elems(j+2,1) = i4;
                      new_elems(j+2,2) = i5;
                      new_elems(j+2,3) = i6;
                    }
                  else
                    {
                      new_elems(j+1,0) = i1;
                      new_elems(j+1,1) = i3;
                      new_elems(j+1,2) = i5;
                      new_elems(j+1,3) = i6;
                      new_elems(j+2,0) = i1;
                      new_elems(j+2,1) = i4;
                      new_elems(j+2,2) = i5;
                      new_elems(j+2,3) = i6;
                    }
                }
              if (ii3>ii1 && ii3>ii2)
                {
                  new_elems(j,0) = i1;
                  new_elems(j,1) = i2;
                  new_elems(j,2) = i3;
                  new_elems(j,3) = i6;
                  if (ii2>ii1)
                    {
                      new_elems(j+1,0) = i1;
                      new_elems(j+1,1) = i2;
                      new_elems(j+1,2) = i5;
                      new_elems(j+1,3) = i6;
                      new_elems(j+2,0) = i1;
                      new_elems(j+2,1) = i4;
                      new_elems(j+2,2) = i5;
                      new_elems(j+2,3) = i6;
                    }
                  else
                    {
                      new_elems(j+1,0) = i1;
                      new_elems(j+1,1) = i2;
                      new_elems(j+1,2) = i4;
                      new_elems(j+1,3) = i6;
                      new_elems(j+2,0) = i2;
                      new_elems(j+2,1) = i4;
                      new_elems(j+2,2) = i5;
                      new_elems(j+2,3) = i6;
                    }
                }
              mettre_a_jour_sous_zone(zone,i,j,3);
              i1+=oldnbsom;
              i2+=oldnbsom;
              i3+=oldnbsom;
              i4+=oldnbsom;
              i5+=oldnbsom;
              i6+=oldnbsom;
            }
        }
// Reconstruction de l'octree
      zone.invalide_octree();
      zone.typer("Tetraedre");
      les_elems.ref(new_elems);
      construire_bords(dom, les_faces,oldnbsom, oldsz, num);
    }
  else
    {
      Cerr << "It is not known yet how to extrude "
           << zone.type_elem()->que_suis_je() <<"s"<<finl;
    }
}
References Domaine::ajouter(), Faces::associer_zone(), Cerr, construire_bords(), construire_connectivite_som_elem(), Faces_builder::creer_faces_reeles(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, direction_, Zone::domaine(), finl, Zone::invalide_octree(), Zone::les_elems(), Domaine::les_sommets(), Interprete_geometrique_base::mettre_a_jour_sous_zone(), Zone::nb_som(), Domaine::nb_som_tot(), NZ_, Objet_U::que_suis_je(), TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), Zone::type_elem(), Elem_geom::type_face(), Faces::typer(), Zone::typer(), and Domaine::zone().
Referenced by ExtrudeBord::extruder_bord(), and interpreter_().
get_info()
const Type_info * Extruder_en3::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 24 of file Extruder_en3.cpp.
info()
const Type_info * Extruder_en3::info () static
Definition at line 24 of file Extruder_en3.cpp.
interpreter_()
Entree & Extruder_en3::interpreter_ (Entree & is) override virtual
Fonction principale de l'interprete Extruder_en3
Triangule 1 a 1 toutes les zones du domaine
specifie par la directive.
On triangule la zone grace a la methode:
void Extruder_en3::extruder(Zone& zone) const
Extruder_en3 signifie ici transformer en triangle des
elements geometrique d'une zone.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Implements Interprete_geometrique_base.
Definition at line 93 of file Extruder_en3.cpp.
{
  if (Objet_U::dimension!=2)
    {
      Cerr << " We only can extruder_en3 the 2D meshes ! " << finl;
      exit();
    }
  int nb_dom=0;
  Noms nom_dom;
  Cerr << "The format has changed after the 1.5.3. A list of domains must now be readen as follows :" << finl;
  Cerr << "domaine N dom1 dom2 domN" << finl;
  Param param(que_suis_je());
  param.ajouter("domaine",&nom_dom,Param::REQUIRED);
  param.ajouter("nb_tranches",&NZ_,Param::REQUIRED);
  param.ajouter_arr_size_predefinie("direction",&direction_,Param::REQUIRED);
  param.ajouter("nom_cl_devant",&nom_dvt_);
  param.ajouter("nom_cl_derriere",&nom_derriere_);
  param.lire_avec_accolades_depuis(is);
  nb_dom=nom_dom.size();
// creation du tableau de correspondance des indices
// pour assurer le decoupage conforme entre domaines
//
// PQ : 07/09/08 : le decoupage des prismes apres extrusion est base sur une numerotation
// globale des indices qui permet d'assurer la conformite des maillages. Ces indices references
// dans le tableau nums sont issus du regroupement des domaines en un seul suivant la methode
// se trouvant dans Mailler.cpp.
// On procede par concatenation des domaines dans "dom_tot" de maniere a ne pas interferer
// avec les domaines et les zones d'origines.
  Domaine dom_tot;
  for(int i=0; i<nb_dom; i++)
    {
// on parcourt les domaines a l'envers pour retrouver l'ancien comportement
      associer_domaine(nom_dom[nb_dom-1-i]);
      Domaine& domi=domaine(i);
      Zone& zone_tot=dom_tot.add(domi.zone(0));
      zone_tot.associer_domaine(dom_tot);
      int nb_som=domi.coord_sommets().dimension(0);
      IntVect num(nb_som);
      dom_tot.ajouter(domi.coord_sommets(), num);
      zone_tot.renum(num);
      zone_tot.associer_domaine(dom_tot);
      Scatter::uninit_sequential_domain(dom_tot);
      dom_tot.comprimer();
      dom_tot.zone(0).fixer_premieres_faces_frontiere();
      dom_tot.zone(0).type_elem().associer_zone(dom_tot.zone(0));
//
// extrusion des domaines
//
      Scatter::uninit_sequential_domain(domi);
      extruder(domi,num);
      Scatter::init_sequential_domain(domi);
    }
  return is;
}
References Domaine::add(), Param::ajouter(), Domaine::ajouter(), Param::ajouter_arr_size_predefinie(), Zone::associer_domaine(), Interprete_geometrique_base::associer_domaine(), Elem_geom::associer_zone(), Cerr, Domaine::comprimer(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, direction_, Interprete_geometrique_base::domaine(), Process::exit(), extruder(), finl, Zone::fixer_premieres_faces_frontiere(), Scatter::init_sequential_domain(), Param::lire_avec_accolades_depuis(), nom_derriere_, nom_dvt_, NZ_, Objet_U::que_suis_je(), Zone::renum(), Param::REQUIRED, vect_impl::size(), Zone::type_elem(), Scatter::uninit_sequential_domain(), and Domaine::zone().
printOn()
Sortie & Extruder_en3::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 47 of file Extruder_en3.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Extruder_en3::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 67 of file Extruder_en3.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Extruder_en3 & Extruder_en3::self_cast (const Objet_U & r) static
Definition at line 24 of file Extruder_en3.cpp.
self_cast() [2/2]
Extruder_en3 & Extruder_en3::self_cast (Objet_U & r) static
Definition at line 24 of file Extruder_en3.cpp.
setDirection()
void Extruder_en3::setDirection (double lx, double ly, double lz) inline
Definition at line 47 of file Extruder_en3.h.
  {
    direction_[0]=lx;
    direction_[1]=ly;
    direction_[2]=lz;
  };
References direction_.
Referenced by ExtrudeBord::extruder_bord().
setNbTranches()
void Extruder_en3::setNbTranches (int n) inline
Definition at line 53 of file Extruder_en3.h.
  {
    NZ_ = n;
  };
References NZ_.
Referenced by ExtrudeBord::extruder_bord().
taille_memoire()
unsigned Extruder_en3::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Extruder_en3.cpp.
Member Data Documentation
direction_
ArrOfDouble Extruder_en3::direction_ private
Definition at line 65 of file Extruder_en3.h.
Referenced by extruder(), Extruder_en3(), interpreter_(), and setDirection().
info_obj
const Type_info Extruder_en3::info_obj static
Definition at line 41 of file Extruder_en3.h.
nom_derriere_
Nom Extruder_en3::nom_derriere_ private
Definition at line 67 of file Extruder_en3.h.
Referenced by construire_bords(), Extruder_en3(), and interpreter_().
nom_dvt_
Nom Extruder_en3::nom_dvt_ private
Definition at line 67 of file Extruder_en3.h.
Referenced by construire_bords(), Extruder_en3(), and interpreter_().
NZ_
int Extruder_en3::NZ_ private
Definition at line 66 of file Extruder_en3.h.
Referenced by construire_bord_lateral(), construire_bords(), extruder(), interpreter_(), and setNbTranches().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Extruder_en3.h
src/Kernel/Geometrie/Extruder_en3.cpp