TRUST: Postraitement_base Class Reference
Postraitement_base Class Reference abstract
Classe de base pour l'ensemble des postraitements.
#include <Postraitement_base.h>
Public Types
enum Format { ASCII , BINAIRE }
enum Type_Champ { CHAMP =0 , STATISTIQUE =1 }
enum Localisation { SOMMETS =0 , ELEMENTS =1 , FACES =2 }
enum Type_Post { ERREUR =-1 , ENTIER =0 , REEL =1 , DOUBLE =2 }
Public Member Functions
~Postraitement_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Postraitement_base ()
virtual void associer_nom_et_pb_base (const Nom &, const Probleme_base &)
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void postraiter (int forcer)=0
virtual void mettre_a_jour (double temps)
virtual void init ()
virtual void finir ()
int sauvegarder (Sortie &os) const override
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
int reprendre (Entree &is) override
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual void completer ()=0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Postraitement_base & self_cast (Objet_U &)
static const Postraitement_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
static const char *const demande_description = "DESCRIPTION"
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom le_nom_
Ref_Probleme_base mon_probleme
double temps_
Detailed Description
Classe de base pour l'ensemble des postraitements.
Definition at line 35 of file Postraitement_base.h.
Member Enumeration Documentation
Format
enum Postraitement_base::Format
Enumerator
ASCII
BINAIRE
Definition at line 52 of file Postraitement_base.h.
{ ASCII, BINAIRE };
Localisation
enum Postraitement_base::Localisation
Enumerator
SOMMETS
ELEMENTS
FACES
Definition at line 54 of file Postraitement_base.h.
{ SOMMETS=0, ELEMENTS=1, FACES=2 };
Type_Champ
enum Postraitement_base::Type_Champ
Enumerator
CHAMP
STATISTIQUE
Definition at line 53 of file Postraitement_base.h.
{ CHAMP=0, STATISTIQUE=1 };
Type_Post
enum Postraitement_base::Type_Post
Enumerator
ERREUR
ENTIER
REEL
DOUBLE
Definition at line 55 of file Postraitement_base.h.
{ ERREUR=-1, ENTIER=0, REEL=1, DOUBLE=2 };
Constructor & Destructor Documentation
~Postraitement_base()
Postraitement_base::~Postraitement_base () override
Definition at line 19 of file Postraitement_base.cpp.
Postraitement_base()
Postraitement_base::Postraitement_base ()
Definition at line 23 of file Postraitement_base.cpp.
                                       :
  temps_(0.)
{
}
Member Function Documentation
associer_nom_et_pb_base()
void Postraitement_base::associer_nom_et_pb_base (const Nom & nom, const Probleme_base & mon_pb) virtual
Reimplemented in Postraitement.
Definition at line 49 of file Postraitement_base.cpp.
{
  le_nom_ = nom;
  mon_probleme = mon_pb;
}
References le_nom_, and mon_probleme.
Referenced by Postraitement::associer_nom_et_pb_base().
completer()
virtual void Postraitement_base::completer () pure virtual
Implemented in Postraitement, and Postraitement_lata.
Referenced by Postraitements::completer().
finir()
virtual void Postraitement_base::finir () inline virtual
Reimplemented in Postraitement.
Definition at line 47 of file Postraitement_base.h.
{};
Referenced by Postraitements::finir().
get_info()
const Type_info * Postraitement_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Postraitement_lata.
Definition at line 19 of file Postraitement_base.cpp.
info()
const Type_info * Postraitement_base::info () static
Definition at line 19 of file Postraitement_base.cpp.
init()
virtual void Postraitement_base::init () inline virtual
Reimplemented in Postraitement.
Definition at line 46 of file Postraitement_base.h.
{};
Referenced by Postraitements::init().
le_nom()
const Nom & Postraitement_base::le_nom () const override virtual
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
Nom&
Signification: le nom de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 56 of file Postraitement_base.cpp.
{
  return le_nom_;
}
References le_nom_.
Referenced by Postraitement::readOn().
lire_motcle_non_standard()
int Postraitement_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Objet_U.
Reimplemented in Postraitement_lata.
Definition at line 42 of file Postraitement_base.cpp.
{
  Cerr << mot << " is not a keyword understood by " << que_suis_je() << " in lire_motcle_non_standard"<< finl;
  exit();
  return -1;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Postraitement_lata::lire_motcle_non_standard().
mettre_a_jour()
void Postraitement_base::mettre_a_jour (double temps) virtual
Reimplemented in Postraitement.
Definition at line 61 of file Postraitement_base.cpp.
{
  temps_ = temps;
}
References temps_.
Referenced by Postraitements::mettre_a_jour().
postraiter()
virtual void Postraitement_base::postraiter (int forcer) pure virtual
Implemented in Postraitement, and Postraitement_lata.
Referenced by Postraitements::postraiter(), and Postraitements::traiter_postraitement().
printOn()
Sortie & Postraitement_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Postraitement_lata.
Definition at line 28 of file Postraitement_base.cpp.
{
  return os;
}
readOn()
Entree & Postraitement_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Postraitement_lata.
Definition at line 33 of file Postraitement_base.cpp.
{
  Cerr<<"Reading of data for a "<<que_suis_je()<<" post-processing object "<<finl;
  Param param(que_suis_je());
  set_param(param);
  param.lire_avec_accolades_depuis(is);
  return is;
}
References Cerr, finl, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and set_param().
Referenced by Postraitement::readOn(), and Postraitement_lata::readOn().
reprendre()
int Postraitement_base::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 71 of file Postraitement_base.cpp.
{
  return 0;
}
Referenced by Postraitements::reprendre().
sauvegarder()
int Postraitement_base::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 66 of file Postraitement_base.cpp.
{
  return 0;
}
Referenced by Postraitements::sauvegarder().
self_cast() [1/2]
const Postraitement_base & Postraitement_base::self_cast (const Objet_U & r) static
Definition at line 19 of file Postraitement_base.cpp.
self_cast() [2/2]
Postraitement_base & Postraitement_base::self_cast (Objet_U & r) static
Definition at line 19 of file Postraitement_base.cpp.
set_param()
virtual void Postraitement_base::set_param (Param & param) pure virtual
Implemented in Postraitement, and Postraitement_lata.
Referenced by readOn().
Member Data Documentation
demande_description
const char *const Postraitement_base::demande_description = "DESCRIPTION" static
Definition at line 57 of file Postraitement_base.h.
info_obj
const Type_info Postraitement_base::info_obj static
Definition at line 37 of file Postraitement_base.h.
le_nom_
Nom Postraitement_base::le_nom_ protected
Definition at line 60 of file Postraitement_base.h.
Referenced by associer_nom_et_pb_base(), and le_nom().
mon_probleme
Ref_Probleme_base Postraitement_base::mon_probleme protected
Definition at line 61 of file Postraitement_base.h.
Referenced by associer_nom_et_pb_base(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_moreqn(), Postraitement::finir(), Postraitement::init(), Postraitement_lata::lire_champs(), Postraitement::lire_champs_a_postraiter(), Postraitement::lire_champs_stat_a_postraiter(), Postraitement::lire_motcle_non_standard(), Postraitement::lire_tableaux_a_postraiter(), Postraitement::postraiter(), Postraitement_lata::postraiter(), Postraitement::postraiter_champs(), Postraitement_lata::postraiter_liste_champs(), Postraitement::postraiter_sondes(), Postraitement::postraiter_tableaux(), Postraitement::probleme(), Postraitement::readOn(), Postraitement::reprendre(), Postraitement::sauvegarder(), Postraitement::traiter_champs(), and Postraitement::traiter_sondes().
temps_
double Postraitement_base::temps_ protected
Definition at line 62 of file Postraitement_base.h.
Referenced by Postraitement_lata::dt_post_ecoule(), mettre_a_jour(), Postraitement_lata::postraiter(), and Postraitement_lata::postraiter_liste_champs().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Postraitement_base.h
src/Kernel/Framework/Postraitement_base.cpp