TRUST: Solveur_U_P Class Reference
Solveur_U_P Class Reference
#include <Solveur_U_P.h>
Public Member Functions
Solveur_U_P ()
~Solveur_U_P ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok) override
Public Member Functions inherited from Simple
~Simple ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Simple ()
bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok) override
void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok) override
bool iterer_eqs (List_Ref_Equation_base eqs, int compteur, int &ok) override
Public Member Functions inherited from Simpler_Base
~Simpler_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int max_iter_implicite ()
int max_iter_implicite () const
bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok) override=0
virtual void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok)=0
void assembler_matrice_pression_implicite (Equation_base &eqn_NS, const Matrice_Morse &matrice, Matrice &matrice_en_pression_2)
Parametre_equation & get_and_set_parametre_equation (Equation_base &) override
retourne le parametre_implicte de l'equation si il existe si il n'existe pas le cree...
si les params sont vides on copie ceux du simpler
Parametre_implicite & get_and_set_parametre_implicite (Equation_base &eqn)
Public Member Functions inherited from Solveur_non_lineaire
Solveur_non_lineaire ()
~Solveur_non_lineaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Solveur_Implicite_Base
Solveur_Implicite_Base ()
~Solveur_Implicite_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok)=0
virtual bool iterer_eqs (List_Ref_Equation_base eqs, int n, int &ok)
virtual bool est_compatible_avec_th_mono () const
virtual int nb_valeurs_temporelles_pression () const
virtual double get_default_facsec_max () const
virtual double get_default_growth_factor () const
virtual Parametre_equation & get_and_set_parametre_equation (Equation_base &eqn)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Solveur_U_P & self_cast (Objet_U &)
static const Solveur_U_P & self_cast (const Objet_U &)
Static Public Member Functions inherited from Simple
static Objet_U * cree_instance ()
static const Type_info * info ()
static Simple & self_cast (Objet_U &)
static const Simple & self_cast (const Objet_U &)
Static Public Member Functions inherited from Simpler_Base
static const Type_info * info ()
static Simpler_Base & self_cast (Objet_U &)
static const Simpler_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_non_lineaire
static const Type_info * info ()
static Solveur_non_lineaire & self_cast (Objet_U &)
static const Solveur_non_lineaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_Implicite_Base
static const Type_info * info ()
static Solveur_Implicite_Base & self_cast (Objet_U &)
static const Solveur_Implicite_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Simple
static const Type_info info_obj
Static Public Attributes inherited from Simpler_Base
static const Type_info info_obj
Static Public Attributes inherited from Solveur_non_lineaire
static const Type_info info_obj
Static Public Attributes inherited from Solveur_Implicite_Base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Simple
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Entree & lire (const Motcle &, Entree &) override
void calculer_correction_en_vitesse (const DoubleTrav &correction_en_pression, DoubleTrav &gradP, DoubleTrav &correction_en_vitesse, const Matrice_Morse &matrice, const Operateur_Grad &gradient)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual Entree & lire (const Motcle &, Entree &)=0
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Simple
DoubleTab Ustar_old
double alpha_
double beta_
int with_d_rho_dt_
std::map< std::vector< intptr_t >, Matrice_Bloc > mbloc
Protected Attributes inherited from Simpler_Base
Parametre_implicite param_defaut_
int is_seuil_convg_variable
double facteur_convg_
int no_qdm_
int controle_residu_
Detailed Description
Definition at line 24 of file Solveur_U_P.h.
Constructor & Destructor Documentation
Solveur_U_P()
Solveur_U_P::Solveur_U_P ()
Definition at line 36 of file Solveur_U_P.cpp.
~Solveur_U_P()
Solveur_U_P::~Solveur_U_P ()
Definition at line 36 of file Solveur_U_P.cpp.
Member Function Documentation
cree_instance()
Objet_U * Solveur_U_P::cree_instance () static
Definition at line 36 of file Solveur_U_P.cpp.
duplique()
int Solveur_U_P::duplique () const override virtual
Reimplemented from Simple.
Definition at line 36 of file Solveur_U_P.cpp.
get_info()
const Type_info * Solveur_U_P::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Simple.
Definition at line 36 of file Solveur_U_P.cpp.
info()
const Type_info * Solveur_U_P::info () static
Definition at line 36 of file Solveur_U_P.cpp.
iterer_NS()
void Solveur_U_P::iterer_NS (Equation_base & eqn, DoubleTab & current, DoubleTab & pression, double dt, Matrice_Morse & matrice_inut, double seuil_resol, DoubleTrav & secmem, int nb_iter, int & converge, int & ok) override virtual
Reimplemented from Simple.
Definition at line 51 of file Solveur_U_P.cpp.
{
  if (eqn.probleme().is_dilatable())
    {
      Cerr<<" Solveur_U_P cannot be used with a quasi-compressible fluid."<<finl;
      Cerr<<__FILE__<<(int)__LINE__<<" non code" <<finl;
      Process::exit();
    }
  Parametre_implicite& param = get_and_set_parametre_implicite(eqn);
  SolveurSys& le_solveur_ = param.solveur();
  Navier_Stokes_std& eqnNS = ref_cast(Navier_Stokes_std,eqn);
  /* MD_Vector (vitesse, pression) */
  MD_Vector_composite mds;
  mds.add_part(current.get_md_vector(), current.line_size());
  mds.add_part(pression.get_md_vector(), pression.line_size());
  MD_Vector md_UP;
  md_UP.copy(mds);
  DoubleTab Inconnues,residu;
  MD_Vector_tools::creer_tableau_distribue(md_UP, Inconnues);
  MD_Vector_tools::creer_tableau_distribue(md_UP, residu);
  DoubleTab_parts residu_parts(residu);
  DoubleTab_parts Inconnues_parts(Inconnues);
  Inconnues_parts[0] = current, Inconnues_parts[1] = pression;
  Matrice_Bloc Matrice_global(2,2) ; //matrice M.(du, dp) = (Navier-Stokes, divergence)
  /* ligne Navier-Stokes : blocs N-S, bloc gradient */
  Matrice_global.get_bloc(0,0).typer("Matrice_Morse");
  Matrice_Morse& matrice=ref_cast(Matrice_Morse, Matrice_global.get_bloc(0,0).valeur());
  Matrice_global.get_bloc(0,1).typer("Matrice_Morse");
  Matrice_Morse& mat_grad=ref_cast(Matrice_Morse, Matrice_global.get_bloc(0,1).valeur());
  if (eqnNS.has_interface_blocs()) /* si interface_blocs : on peut remplir les deux d'un coup */
    {
      eqnNS.dimensionner_blocs({{ "vitesse", &matrice }, { "pression", &mat_grad }});
      eqnNS.assembler_blocs_avec_inertie({{ "vitesse", &matrice }, { "pression", &mat_grad }}, residu_parts[0]);
    }
  else /* sinon : moins elegant */
    {
      Operateur_Grad& gradient = eqnNS.operateur_gradient();
      eqnNS.dimensionner_matrice(matrice);
      eqnNS.assembler_avec_inertie(matrice,current,residu_parts[0]);
      gradient.valeur().dimensionner( mat_grad);
      gradient.valeur().contribuer_a_avec(pression, mat_grad);
      mat_grad.get_set_coeff()*=-1;
      /* pour repasser en increments */
      residu_parts[0]*=-1;
      matrice.ajouter_multvect(current, residu_parts[0]);
      gradient.valeur().ajouter(pression,residu_parts[0]);
      residu_parts[0]*=-1;
    }
  /* doit-on fixer P(elem 0) = 0 ? */
  int has_P_ref=0;
  const Conds_lim& cls = eqnNS.zone_Cl_dis().les_conditions_limites();
  for (int n_bord=0; n_bord < cls.size(); n_bord++)
    if (sub_type(Neumann_sortie_libre,cls[n_bord].valeur())) has_P_ref=1;
  /* ligne de masse : (div, 0) */
  Operateur_Div_base& divergence = eqnNS.operateur_divergence().valeur();
  Matrice_global.get_bloc(1,0).typer("Matrice_Morse");
  Matrice_Morse& mat_div_v = ref_cast(Matrice_Morse, Matrice_global.get_bloc(1,0).valeur());
  if (divergence.has_interface_blocs()) /* si interface_blocs : direct */
    {
      Matrice_global.get_bloc(1,1).typer("Matrice_Morse");
      Matrice_Morse& mat_div_p = ref_cast(Matrice_Morse, Matrice_global.get_bloc(1,1).valeur());
      divergence.dimensionner_blocs({ { "vitesse", &mat_div_v } , { "pression", &mat_div_p}});
      divergence.ajouter_blocs({ { "vitesse", &mat_div_v } , { "pression", &mat_div_p}}, residu_parts[1]);
      if (!has_P_ref && !Process::me()) mat_div_p(0, 0) += 1; //revient a imposer P(0) = 0
    }
  else /* sinon : l'operateur remplit mat_div_v, on construit a la main mat_div_p = 0 */
    {
      divergence.dimensionner(mat_div_v);
      divergence.contribuer_a_avec(current, mat_div_v);
      divergence.calculer(current, residu_parts[1]);
      Matrice_global.get_bloc(1,1).typer("Matrice_Diagonale");
      Matrice_Diagonale& mat_div_p = ref_cast(Matrice_Diagonale,Matrice_global.get_bloc(1,1).valeur());
      mat_div_p.dimensionner(mat_div_v.nb_lignes());
      if (!has_P_ref && !Process::me()) mat_div_p.coeff(0, 0) += 1; //revient a imposer P(0) = 0
    }
  le_solveur_.valeur().reinit();
  le_solveur_.valeur().resoudre_systeme(Matrice_global,residu,Inconnues);
// Calcul de Uk = U*_k + U'k
  current  += Inconnues_parts[0];
  pression += Inconnues_parts[1];
// current.echange_espace_virtuel();
  Debog::verifier("Solveur_U_P::iterer_NS current",current);
  eqn.solv_masse().corriger_solution(current, current);    //PolyMAC_P0 : mise en coherence de ve avec vf
  eqnNS.assembleur_pression().modifier_solution(pression);
  if (1)
    {
// DoubleTrav secmem(current);
      divergence.calculer(current, secmem);
      Cerr<<" apresdiv "<<mp_max_abs_vect(secmem)<<finl;;
    }
}
References MD_Vector_composite::add_part(), Operateur_Grad_base::ajouter(), Operateur_base::ajouter_blocs(), Matrice_Base::ajouter_multvect(), Equation_base::assembler_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Navier_Stokes_std::assembleur_pression(), Operateur_base::calculer(), Cerr, Matrice_Diagonale::coeff(), Operateur_base::contribuer_a_avec(), Operateur_Grad_base::contribuer_a_avec(), MD_Vector::copy(), Solveur_Masse::corriger_solution(), MD_Vector_tools::creer_tableau_distribue(), Matrice_Diagonale::dimensionner(), Operateur_base::dimensionner(), Operateur_Grad_base::dimensionner(), Operateur_base::dimensionner_blocs(), Navier_Stokes_std::dimensionner_blocs(), Equation_base::dimensionner_matrice(), Process::exit(), finl, Simpler_Base::get_and_set_parametre_implicite(), Matrice_Bloc::get_bloc(), TRUSTVect< _TYPE_ >::get_md_vector(), Matrice_Morse::get_set_coeff(), Operateur_base::has_interface_blocs(), Navier_Stokes_std::has_interface_blocs(), Probleme_base::is_dilatable(), Zone_Cl_dis::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Process::me(), Assembleur::modifier_solution(), mp_max_abs_vect(), Matrice_Morse::nb_lignes(), Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::operateur_gradient(), Equation_base::probleme(), ref_cast, SolveurSys_base::reinit(), SolveurSys_base::resoudre_systeme(), vect_impl::size(), Equation_base::solv_masse(), Parametre_implicite::solveur(), sub_type, Deriv_::typer(), Deriv_Matrice_Base::valeur(), Deriv_SolveurSys_base::valeur(), Deriv_Operateur_Div_base::valeur(), Deriv_Operateur_Grad_base::valeur(), valeur(), Debog::verifier(), and Equation_base::zone_Cl_dis().
printOn()
Sortie & Solveur_U_P::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Simple.
Definition at line 38 of file Solveur_U_P.cpp.
{
  return Simple::printOn(os);
}
References Simple::printOn().
readOn()
Entree & Solveur_U_P::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Simple.
Definition at line 43 of file Solveur_U_P.cpp.
{
  return Simple::readOn(is);
}
References Simple::readOn().
self_cast() [1/2]
const Solveur_U_P & Solveur_U_P::self_cast (const Objet_U & r) static
Definition at line 36 of file Solveur_U_P.cpp.
self_cast() [2/2]
Solveur_U_P & Solveur_U_P::self_cast (Objet_U & r) static
Definition at line 36 of file Solveur_U_P.cpp.
taille_memoire()
unsigned Solveur_U_P::taille_memoire () const override virtual
Reimplemented from Simple.
Definition at line 36 of file Solveur_U_P.cpp.
Member Data Documentation
info_obj
const Type_info Solveur_U_P::info_obj static
Definition at line 27 of file Solveur_U_P.h.
The documentation for this class was generated from the following files:
src/ThHyd/Schemas_Temps/Solveur_U_P.h
src/ThHyd/Schemas_Temps/Solveur_U_P.cpp