TRUST: Loi_Etat_rhoT_GR_QC Class Reference
Loi_Etat_rhoT_GR_QC Class Reference
classe Loi_Etat_rhoT_GR_QC
Cette classe represente la loi d'etat pour les gaz reels.
Associe a un fluide incompressible, elle definit un fluide quasi compressible
dont la loi d'etat est :
rho=rho(Pth,H)
T = T(Pth,H)
#include <Loi_Etat_rhoT_GR_QC.h>
Public Member Functions
Loi_Etat_rhoT_GR_QC ()
~Loi_Etat_rhoT_GR_QC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void calculer_masse_volumique () override
Recalcule la masse volumique.
double calculer_temperature (double, double) override
Calcule la temperature ponctuelle.
double calculer_H (double, double) const override
Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
double Drho_DP (double, double) const override
double Drho_DT (double, double) const override
double DT_DH (double, double) const override
double calculer_masse_volumique (double, double) const override
Calcule la masse volumique ponctuelle.
Public Member Functions inherited from Loi_Etat_GR_base
~Loi_Etat_GR_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_GR_base ()
void initialiser_inco_ch () override
Initialise l'enthalpie.
void calculer_lambda () override
Calcule la conductivite /Cp : equivlent a k*dT/dh
pour utiliser l'enthalpie dans l'operatur de diffusion.
void initialiser () override
Initialise la loi d'etat : calcul Pth.
void remplir_T () override
Remplit le tableau de la temperature : T=temp+273.15.
void calculer_Cp () override
Calcule le Cp avec le polynome PolyCp_.
const Nom type_fluide () const override
Renvoie le type de fluide associe.
double De_DP (double, double) const override
double De_DT (double, double) const override
double Cp_calc (double, double) const
Calcule le Cp en fonction des grandeurs physiques P, T, rho
Cp = dh/dT = de/dT - 1/rho^2*drho/dT.
double inverser_Pth (double, double) override
Calcule la pression avec la temperature et la masse volumique.
void calculer_masse_volumique () override
Recalcule la masse volumique.
virtual double calculer_temperature (double, double)=0
double calculer_H (double, double) const override=0
Cas gaz parfait : ne fait rien
Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
double Drho_DP (double, double) const override=0
double Drho_DT (double, double) const override=0
virtual double DT_DH (double, double) const =0
double calculer_masse_volumique (double, double) const override=0
double masse_molaire () const
Public Member Functions inherited from Loi_Etat_base
~Loi_Etat_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_base ()
void assoscier_probleme (const Probleme_base &pb)
Associe le probleme a la loi d'etat.
void mettre_a_jour (double)
Met a jour la loi d'etat et le champ rho.
void calculer_nu ()
Calcule la viscosite cinematique.
Champ_Don & ch_temperature ()
const Champ_Don & ch_temperature () const
Renvoie le champ de le temperature.
virtual void associer_fluide (const Fluide_Dilatable_base &)
Associe le fluide a la loi d'etat.
virtual void preparer_calcul ()
Prepare le fluide au calcul.
virtual void abortTimeStep ()
virtual void initialiser_inco_ch ()
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
virtual void calculer_mu ()
Calcule la viscosite.
virtual void calculer_lambda ()
Calcule la conductivite.
virtual void calculer_alpha ()
Calcule la diffusivite.
virtual void calculer_mu_sur_Sc ()
Ne fait rien
Surcharge dans Loi_Etat_Melange_GP.
virtual void calculer_nu_sur_Sc ()
Ne fait rien
Surcharge dans Loi_Etat_Melange_Binaire.
virtual void calculer_masse_volumique ()
Recalcule la masse volumique.
virtual double calculer_H (double, double) const
Cas gaz parfait : ne fait rien
Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
virtual double Drho_DP (double, double) const
virtual double Drho_DT (double, double) const
virtual double De_DP (double, double) const
virtual double De_DT (double, double) const
const Champ_base & get_champ (const Motcle &nom) const override
void creer_champ (const Motcle &motlu) override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Nom type_fluide () const =0
virtual void initialiser ()=0
virtual void remplir_T ()=0
virtual void calculer_Cp ()=0
virtual double calculer_masse_volumique (double, double) const =0
virtual double inverser_Pth (double, double)=0
Champs_compris & champs_compris ()
const DoubleTab & temperature () const
const DoubleTab & rho_n () const
const DoubleTab & rho_np1 () const
double Prandt () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Loi_Etat_rhoT_GR_QC & self_cast (Objet_U &)
static const Loi_Etat_rhoT_GR_QC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_GR_base
static const Type_info * info ()
static Loi_Etat_GR_base & self_cast (Objet_U &)
static const Loi_Etat_GR_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_base
static const Type_info * info ()
static Loi_Etat_base & self_cast (Objet_U &)
static const Loi_Etat_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_GR_base
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
DoubleTab PolyRho_
DoubleTab PolyT_
Protected Attributes inherited from Loi_Etat_GR_base
double MMole_
double Cp_
double R
DoubleTab tab_TempC
DoubleTab tab_Cp
Protected Attributes inherited from Loi_Etat_base
Ref_Fluide_Dilatable_base le_fluide
Ref_Probleme_base le_prob_
Champ_Don temperature_
DoubleTab tab_rho_n
DoubleTab tab_rho_np1
double Pr_
int debug
Detailed Description
classe Loi_Etat_rhoT_GR_QC
Cette classe represente la loi d'etat pour les gaz reels.
Associe a un fluide incompressible, elle definit un fluide quasi compressible
dont la loi d'etat est :
rho=rho(Pth,H)
T = T(Pth,H)
Definition at line 39 of file Loi_Etat_rhoT_GR_QC.h.
Constructor & Destructor Documentation
Loi_Etat_rhoT_GR_QC()
Loi_Etat_rhoT_GR_QC::Loi_Etat_rhoT_GR_QC ()
Definition at line 21 of file Loi_Etat_rhoT_GR_QC.cpp.
~Loi_Etat_rhoT_GR_QC()
Loi_Etat_rhoT_GR_QC::~Loi_Etat_rhoT_GR_QC ()
Definition at line 21 of file Loi_Etat_rhoT_GR_QC.cpp.
Member Function Documentation
calculer_H()
double Loi_Etat_rhoT_GR_QC::calculer_H (double Pth_, double T_) const override virtual
Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
Implements Loi_Etat_GR_base.
Definition at line 263 of file Loi_Etat_rhoT_GR_QC.cpp.
{
  double res=0;
  if (R==-1)
    {
// il faut resoudre c0-T_ + c1.H + c2.H^2 +...=0
      int i,j, it,max_iter = 1000;
      double eps = 1.e-6;
      DoubleVect coef(PolyT_.line_size());
      coef = 0;
      for (i=0 ; i<PolyT_.dimension(0) ; i++)
        for (j=0 ; j<PolyT_.line_size() ; j++)
          coef(j) += PolyT_(i,j) * pow(Pth_,i);
      coef(0) -= T_;
      double dH, H = -coef(0)/coef(1), num=coef(0), den=0;
      for (j=1 ; j<PolyT_.line_size() ; j++)
        {
          num += coef(j) * pow(H,j);
          den += j*coef(j) * pow(H,j-1);
        }
      dH = num/den;
      H -= dH;
      it=0;
      while (dH/H>eps && it<max_iter)
        {
          num=coef(0);
          den=0;
          for (j=1 ; j<PolyT_.line_size() ; j++)
            {
              num += coef(j) * pow(H,j);
              den += j*coef(j) * pow(H,j-1);
            }
          dH = num / den;
          H -= dH;
          it++;
        }
      if (dH/H>eps)
        {
          Cerr<<"PB Loi_Etat_rhoT_GR_QC::calculer_H: resolution Newton impossible "<<finl;
          Cerr<<"Pth= "<<Pth_<<" t="<<T_<<" H="<<H<<finl;
          abort();
        }
      res = H;
    }
  else
    {
// debuggage
      res = Cp_*T_;
    }
  return res;
}
References Process::abort(), Cerr, Loi_Etat_GR_base::Cp_, TRUSTTab< _TYPE_ >::dimension(), finl, TRUSTVect< _TYPE_ >::line_size(), PolyT_, and Loi_Etat_GR_base::R.
calculer_masse_volumique() [1/2]
void Loi_Etat_rhoT_GR_QC::calculer_masse_volumique () override virtual
Recalcule la masse volumique.
Reimplemented from Loi_Etat_GR_base.
Definition at line 377 of file Loi_Etat_rhoT_GR_QC.cpp.
{
  Loi_Etat_GR_base::calculer_masse_volumique();
}
References Loi_Etat_GR_base::calculer_masse_volumique().
calculer_masse_volumique() [2/2]
double Loi_Etat_rhoT_GR_QC::calculer_masse_volumique (double P, double h) const override virtual
Calcule la masse volumique ponctuelle.
Returns
double
Signification: masse volumique correspondante
Contraintes:
Implements Loi_Etat_GR_base.
Definition at line 192 of file Loi_Etat_rhoT_GR_QC.cpp.
{
  double res = 0;
  if (R==-1)
    {
      double H = h;
      int i,j;
      for (i=0 ; i<PolyRho_.dimension(0) ; i++)
        for (j=0 ; j<PolyRho_.line_size() ; j++)
          res += PolyRho_(i,j) *pow(P,j) *pow(H,i);
    }
  else
    {
// debuggage
      res = P*Cp_/(R*h);
    }
  return res;
}
References Loi_Etat_GR_base::Cp_, TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::line_size(), PolyRho_, and Loi_Etat_GR_base::R.
calculer_temperature()
double Loi_Etat_rhoT_GR_QC::calculer_temperature (double P, double h) override virtual
Calcule la temperature ponctuelle.
Returns
double
Signification: masse volumique correspondante
Contraintes:
Implements Loi_Etat_GR_base.
Definition at line 230 of file Loi_Etat_rhoT_GR_QC.cpp.
{
  double res = 0;
  if (R==-1)
    {
      int i,j;
      double H = h;
      for (i=0 ; i<PolyT_.dimension(0) ; i++)
        for (j=0 ; j<PolyT_.line_size() ; j++)
          res += PolyT_(i,j) *pow(P,i) *pow(H,j);
    }
  else
    {
// debuggage
      res = h/Cp_;
    }
  return res;
}
References Loi_Etat_GR_base::Cp_, TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::line_size(), PolyT_, and Loi_Etat_GR_base::R.
cree_instance()
Objet_U * Loi_Etat_rhoT_GR_QC::cree_instance () static
Definition at line 21 of file Loi_Etat_rhoT_GR_QC.cpp.
Drho_DP()
double Loi_Etat_rhoT_GR_QC::Drho_DP (double P, double h) const override virtual
Implements Loi_Etat_GR_base.
Definition at line 319 of file Loi_Etat_rhoT_GR_QC.cpp.
{
  double res = 0;
  if (R==-1)
    {
      int i,j;
      double H =h;
      for (i=1 ; i<PolyRho_.dimension(0) ; i++)
        for (j=0 ; j<PolyRho_.line_size() ; j++)
          res += i* PolyRho_(i,j) *pow(P,i-1) *pow(H,j);
    }
  else
    {
// debuggage
      res = 1/(R*h/Cp_);
    }
  return res;
}
References Loi_Etat_GR_base::Cp_, TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::line_size(), PolyRho_, and Loi_Etat_GR_base::R.
Drho_DT()
double Loi_Etat_rhoT_GR_QC::Drho_DT (double P, double h) const override virtual
Implements Loi_Etat_GR_base.
Definition at line 339 of file Loi_Etat_rhoT_GR_QC.cpp.
{
  double res = 0;
  if (R==-1)
    {
      int i,j;
      double H = h;
      for (i=1 ; i<PolyRho_.dimension(0) ; i++)
        for (j=0 ; j<PolyRho_.line_size() ; j++)
          res += i* PolyRho_(i,j) *pow(P,j) *pow(H,i-1);
    }
  else
    {
// debuggage
      res = -P*Cp_/(R*h*h);
    }
  return res;
}
References Loi_Etat_GR_base::Cp_, TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::line_size(), PolyRho_, and Loi_Etat_GR_base::R.
DT_DH()
double Loi_Etat_rhoT_GR_QC::DT_DH (double P, double h) const override virtual
Implements Loi_Etat_GR_base.
Definition at line 358 of file Loi_Etat_rhoT_GR_QC.cpp.
{
  double res = 0;
  if (R==-1)
    {
      int i,j;
      double H = h;
      for (i=0 ; i<PolyT_.dimension(0) ; i++)
        for (j=1 ; j<PolyT_.line_size() ; j++)
          res += j* PolyT_(i,j) *pow(P,i) *pow(H,j-1);
    }
  else
    {
// debuggage
      res = Cp_-R;
    }
  return res;
}
References Loi_Etat_GR_base::Cp_, TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::line_size(), PolyT_, and Loi_Etat_GR_base::R.
duplique()
int Loi_Etat_rhoT_GR_QC::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Loi_Etat_rhoT_GR_QC.cpp.
get_info()
const Type_info * Loi_Etat_rhoT_GR_QC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_GR_base.
Definition at line 21 of file Loi_Etat_rhoT_GR_QC.cpp.
info()
const Type_info * Loi_Etat_rhoT_GR_QC::info () static
Definition at line 21 of file Loi_Etat_rhoT_GR_QC.cpp.
printOn()
Sortie & Loi_Etat_rhoT_GR_QC::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Loi_Etat_GR_base.
Definition at line 26 of file Loi_Etat_rhoT_GR_QC.cpp.
{
  os <<que_suis_je()<< finl;
  return os;
}
References finl, and Objet_U::que_suis_je().
readOn()
Entree & Loi_Etat_rhoT_GR_QC::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Loi_Etat_GR_base.
Definition at line 32 of file Loi_Etat_rhoT_GR_QC.cpp.
{
  double PolyRho_lu=-1, PolyT_lu=-1, MMole_lu=-1, Pr_lu=-1;
  Motcle accferme="}";
  Motcle accouverte="{";
  Motcle motlu;
  is >> motlu;
  Cerr<<"Lecture de la loi d'etat Gaz Reel rhoT"<<finl;
  if (motlu != accouverte)
    {
      Cerr<<" On attendait "<<accouverte<<" au lieu de "<<motlu<<finl;
      abort();
    }
  Motcles les_mots(4);
  {
    les_mots[0] = "Prandtl";
    les_mots[1] = "masse_molaire";
    les_mots[2] = "Poly_rho";
    les_mots[3] = "Poly_T";
// les_mots[4] = "Cp";   //pour debuggage
  }
  is >> motlu;
  while(motlu != accferme )
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          {
            is>>Pr_;
            Pr_lu=1;
            break;
          }
        case 1 :
          {
            is>>MMole_;
            MMole_lu=1;
            break;
          }
        case 2 :
          {
            int i,j,im,jm;
            is>>im;
            is>>jm;
            PolyRho_.resize(im,jm);
            for (i=0 ; i<im ; i++)
              for (j=0 ; j<jm ; j++)
                is>>PolyRho_(i,j);
            PolyRho_lu=1;
            break;
          }
        case 3 :
          {
            int i,j,im,jm;
            is>>im;
            is>>jm;
            PolyT_.resize(im,jm);
            for (i=0 ; i<im ; i++)
              for (j=0 ; j<jm ; j++)
                is>>PolyT_(i,j);
            PolyT_lu=1;
            break;
          }
        case 4 :
          {
            is>>Cp_;
            PolyRho_lu=1;
            PolyT_lu=1;
            MMole_lu=1;
            if (Cp_<0)
              {
                Cp_ = -Cp_;
                debug=1;
              }
            else
              debug=0;
            R = Cp_ *(1.-1./1.4);
            Cerr<<"Debogage Gaz Reel : Cp="<<Cp_<<" R="<<R<<finl;
            break;
          }
        default :
          {
            Cerr<<"Une loi d'etat "<<que_suis_je()<<" n'a pas la propriete "<<motlu<<finl;
            Cerr<<"On attendait un mot dans :"<<finl<<les_mots<<finl;
            abort();
          }
        }
      is >> motlu;
    }
  if (Pr_lu==-1)
    {
      Cerr<<"ERREUR : on attendait la definition du nombre de Prandtl (Prandtl pr)"<<finl;
      abort();
    }
  if (PolyRho_lu==-1)
    {
      Cerr<<"ERREUR : on attendait la definition du polynome de la masse volumique (Poly_Rho nb_coeff1 nb_coeff2 a00 a01 a02 ...)"<<finl;
      abort();
    }
  else
    {
      int i,j;
      Cerr<<"Polynome de rho :"<<finl;
      for (i=0 ; i<PolyRho_.dimension(0) ; i++)
        {
          for (j=0 ; j<PolyRho_.dimension(1) ; j++)
            {
              Cerr<<"   f("<<i<<","<<j<<")= "<<PolyRho_(i,j);
            }
          Cerr<<finl;
        }
    }
  if (PolyT_lu==-1)
    {
      Cerr<<"ERREUR : on attendait la definition du polynome de la temperature (Poly_T nb_coeff1 nb_coeff2 a00 a01 a02 ...)"<<finl;
      abort();
    }
  else
    {
      int i,j;
      Cerr<<"Polynome de T :"<<finl;
      for (i=0 ; i<PolyT_.dimension(0) ; i++)
        {
          for (j=0 ; j<PolyT_.dimension(1) ; j++)
            {
              Cerr<<"   f("<<i<<","<<j<<")= "<<PolyT_(i,j);
            }
          Cerr<<finl;
        }
    }
  if (MMole_lu==-1)
    {
      Cerr<<"ERREUR : on attendait la definition de la masse molaire (masse_molaire m)"<<finl;
      abort();
    }
  return is;
}
References Process::abort(), Cerr, Loi_Etat_GR_base::Cp_, Loi_Etat_base::debug, TRUSTTab< _TYPE_ >::dimension(), finl, Loi_Etat_GR_base::MMole_, PolyRho_, PolyT_, Loi_Etat_base::Pr_, Objet_U::que_suis_je(), Loi_Etat_GR_base::R, TRUSTTab< _TYPE_ >::resize(), and Motcles::search().
self_cast() [1/2]
const Loi_Etat_rhoT_GR_QC & Loi_Etat_rhoT_GR_QC::self_cast (const Objet_U & r) static
Definition at line 21 of file Loi_Etat_rhoT_GR_QC.cpp.
self_cast() [2/2]
Loi_Etat_rhoT_GR_QC & Loi_Etat_rhoT_GR_QC::self_cast (Objet_U & r) static
Definition at line 21 of file Loi_Etat_rhoT_GR_QC.cpp.
taille_memoire()
unsigned Loi_Etat_rhoT_GR_QC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Loi_Etat_rhoT_GR_QC.cpp.
Member Data Documentation
info_obj
const Type_info Loi_Etat_rhoT_GR_QC::info_obj static
Definition at line 41 of file Loi_Etat_rhoT_GR_QC.h.
PolyRho_
DoubleTab Loi_Etat_rhoT_GR_QC::PolyRho_ protected
Definition at line 53 of file Loi_Etat_rhoT_GR_QC.h.
Referenced by calculer_masse_volumique(), Drho_DP(), Drho_DT(), and readOn().
PolyT_
DoubleTab Loi_Etat_rhoT_GR_QC::PolyT_ protected
Definition at line 53 of file Loi_Etat_rhoT_GR_QC.h.
Referenced by calculer_H(), calculer_temperature(), DT_DH(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/Loi_Etat/Loi_Etat_rhoT_GR_QC.h
src/ThHyd/Dilatable/Quasi_Compressible/Loi_Etat/Loi_Etat_rhoT_GR_QC.cpp