TRUST: Reorienter_tetraedres Class Reference
Reorienter_tetraedres Class Reference
#include <Reorienter_tetraedres.h>
Public Member Functions
Reorienter_tetraedres ()
~Reorienter_tetraedres ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
void Reorienter (Domaine &) const
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Reorienter_tetraedres & self_cast (Objet_U &)
static const Reorienter_tetraedres & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Types
enum Sens { DIRECT , INDIRECT }
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Reorienter_tetraedres::Sens test_orientation_tetra (IntTab &les_elems, int ielem, const DoubleTab &coord_sommets) const
Reorienter_tetraedres::Sens reorienter_tetra (IntTab &les_elems, int ielem) const
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Definition at line 33 of file Reorienter_tetraedres.h.
Member Enumeration Documentation
Sens
enum Reorienter_tetraedres::Sens protected
Enumerator
DIRECT
INDIRECT
Definition at line 43 of file Reorienter_tetraedres.h.
{DIRECT , INDIRECT};
Constructor & Destructor Documentation
Reorienter_tetraedres()
Reorienter_tetraedres::Reorienter_tetraedres ()
Definition at line 19 of file Reorienter_tetraedres.cpp.
~Reorienter_tetraedres()
Reorienter_tetraedres::~Reorienter_tetraedres ()
Definition at line 19 of file Reorienter_tetraedres.cpp.
Member Function Documentation
cree_instance()
Objet_U * Reorienter_tetraedres::cree_instance () static
Definition at line 19 of file Reorienter_tetraedres.cpp.
duplique()
int Reorienter_tetraedres::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Reorienter_tetraedres.cpp.
get_info()
const Type_info * Reorienter_tetraedres::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 19 of file Reorienter_tetraedres.cpp.
info()
const Type_info * Reorienter_tetraedres::info () static
Definition at line 19 of file Reorienter_tetraedres.cpp.
interpreter_()
Entree & Reorienter_tetraedres::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base.
Definition at line 31 of file Reorienter_tetraedres.cpp.
{
  Cerr << "Reorientation of tetrahedra for either direct..." << finl;
  if (dimension != 3)
    {
      Cerr << "we can not reorientate (Reorienter) in dimension " << dimension <<finl;
      exit();
    }
  associer_domaine(is);
  Domaine& dom=domaine();
  Scatter::uninit_sequential_domain(dom);
  Reorienter(dom);
  Scatter::init_sequential_domain(dom);
  Cerr << "Reorientation of tetrahedra... OK" << finl;
  return is;
}
References Interprete_geometrique_base::associer_domaine(), Cerr, Objet_U::dimension, Interprete_geometrique_base::domaine(), Process::exit(), finl, Scatter::init_sequential_domain(), Reorienter(), and Scatter::uninit_sequential_domain().
printOn()
Sortie & Reorienter_tetraedres::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 21 of file Reorienter_tetraedres.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Reorienter_tetraedres::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Reorienter_tetraedres.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
Reorienter()
void Reorienter_tetraedres::Reorienter (Domaine & dom) const
Definition at line 117 of file Reorienter_tetraedres.cpp.
{
  const DoubleTab& coord_sommets = dom.coord_sommets();
  int nb_zones = dom.nb_zones();
  int iz;
// on balaye les zones du domaine
  for(iz=0 ; iz<nb_zones ; iz++)
    {
      Zone& zone = dom.zone(iz);
      if (zone.type_elem()->que_suis_je() == "Tetraedre" )
        {
// zone de tetraedres
          IntTab& les_elems = zone.les_elems();
          int nb_elems = les_elems.dimension(0);
          int ielem;
// balaye les tetraedres
          for (ielem=0 ; ielem<nb_elems ; ielem++)
            {
              if (test_orientation_tetra(les_elems, ielem, coord_sommets)==INDIRECT)
                {
// tetraedre oriente en sens indirect -> a reorienter
                  reorienter_tetra(les_elems, ielem);
#ifdef _AFFDEBUG
                  {
                    Process::Journal<<"  #element reoriente "<<ielem<<finl;
                    static const int SOM_Z = 0;  //!< indice du sommet qui servira d'origine
                    static const int SOM_A = 1;     //!< indice du sommet qui servira pour le premier vecteur
                    static const int SOM_B = 2;     //!< indice du sommet qui servira pour le second vecteur
                    static const int SOM_C = 3;     //!< indice du sommet qui servira pour le troisieme vecteur
                    const int som_Z = les_elems(ielem,SOM_Z);
                    const int som_A = les_elems(ielem,SOM_A);
                    const int som_B = les_elems(ielem,SOM_B);
                    const int som_C = les_elems(ielem,SOM_C);
                    Process::Journal<<"    somA= "<<som_A<<"  coords= "<<coord_sommets(som_A, 0)<<" "<<coord_sommets(som_A, 1)<<" "<<coord_sommets(som_A, 2)<<finl;
                    Process::Journal<<"    somB= "<<som_B<<"  coords= "<<coord_sommets(som_B, 0)<<" "<<coord_sommets(som_B, 1)<<" "<<coord_sommets(som_B, 2)<<finl;
                    Process::Journal<<"    somC= "<<som_C<<"  coords= "<<coord_sommets(som_C, 0)<<" "<<coord_sommets(som_C, 1)<<" "<<coord_sommets(som_C, 2)<<finl;
                    Process::Journal<<"    somA= "<<som_A<<"  coords= "<<coord_sommets(som_A, 0)<<" "<<coord_sommets(som_A, 1)<<" "<<coord_sommets(som_A, 2)<<finl<<finl;
                    Process::Journal<<"    somZ= "<<som_Z<<"  coords= "<<coord_sommets(som_Z, 0)<<" "<<coord_sommets(som_Z, 1)<<" "<<coord_sommets(som_Z, 2)<<finl;
                    Process::Journal<<"    somA= "<<som_A<<"  coords= "<<coord_sommets(som_A, 0)<<" "<<coord_sommets(som_A, 1)<<" "<<coord_sommets(som_A, 2)<<finl<<finl;
                    Process::Journal<<"    somZ= "<<som_Z<<"  coords= "<<coord_sommets(som_Z, 0)<<" "<<coord_sommets(som_Z, 1)<<" "<<coord_sommets(som_Z, 2)<<finl;
                    Process::Journal<<"    somB= "<<som_B<<"  coords= "<<coord_sommets(som_B, 0)<<" "<<coord_sommets(som_B, 1)<<" "<<coord_sommets(som_B, 2)<<finl<<finl;
                    Process::Journal<<"    somZ= "<<som_Z<<"  coords= "<<coord_sommets(som_Z, 0)<<" "<<coord_sommets(som_Z, 1)<<" "<<coord_sommets(som_Z, 2)<<finl;
                    Process::Journal<<"    somC= "<<som_C<<"  coords= "<<coord_sommets(som_C, 0)<<" "<<coord_sommets(som_C, 1)<<" "<<coord_sommets(som_C, 2)<<finl<<finl;
                  }
#endif
                }
            }
        }
    }//fin balayage zones
}
References Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), finl, INDIRECT, Process::Journal(), Zone::les_elems(), Domaine::nb_zones(), Objet_U::que_suis_je(), reorienter_tetra(), test_orientation_tetra(), Zone::type_elem(), and Domaine::zone().
Referenced by interpreter_().
reorienter_tetra()
Reorienter_tetraedres::Sens Reorienter_tetraedres::reorienter_tetra (IntTab & les_elems, int ielem) const protected
Definition at line 101 of file Reorienter_tetraedres.cpp.
{
  static const int SOM_A = 1;
  static const int SOM_B = 2;
// pour reorienter le tetraedre, on va permuter les sommets 1 et 2
  int tmp;
  tmp = les_elems(num_element,SOM_A);
  les_elems(num_element,SOM_A) = les_elems(num_element,SOM_B);
  les_elems(num_element,SOM_B) = tmp;
  return DIRECT;
}
References DIRECT.
Referenced by Reorienter().
self_cast() [1/2]
const Reorienter_tetraedres & Reorienter_tetraedres::self_cast (const Objet_U & r) static
Definition at line 19 of file Reorienter_tetraedres.cpp.
self_cast() [2/2]
Reorienter_tetraedres & Reorienter_tetraedres::self_cast (Objet_U & r) static
Definition at line 19 of file Reorienter_tetraedres.cpp.
taille_memoire()
unsigned Reorienter_tetraedres::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Reorienter_tetraedres.cpp.
test_orientation_tetra()
Reorienter_tetraedres::Sens Reorienter_tetraedres::test_orientation_tetra (IntTab & les_elems, int ielem, const DoubleTab & coord_sommets) const protected
Definition at line 49 of file Reorienter_tetraedres.cpp.
{
  static const int SOM_Z = 0;
  static const int SOM_A = 1;
  static const int SOM_B = 2;
  static const int SOM_C = 3;
  const int som_Z = les_elems(num_element,SOM_Z);
  const int som_A = les_elems(num_element,SOM_A);
  const int som_B = les_elems(num_element,SOM_B);
  const int som_C = les_elems(num_element,SOM_C);
  double ZA[3], ZB[3], ZC[3], pdtvect[3], pdtscal;
  int k;
  for (k=0 ; k<dimension ; k++)
    {
      ZA[k] = coord_sommets(som_A,k) - coord_sommets(som_Z,k);
      ZB[k] = coord_sommets(som_B,k) - coord_sommets(som_Z,k);
      ZC[k] = coord_sommets(som_C,k) - coord_sommets(som_Z,k);
    }
// calcul pdt vect ZAxZB
  pdtvect[0] = ZA[1]*ZB[2] - ZA[2]*ZB[1];
  pdtvect[1] = ZA[2]*ZB[0] - ZA[0]*ZB[2];
  pdtvect[2] = ZA[0]*ZB[1] - ZA[1]*ZB[0];
// calcul du pdtscal pdtvect.ZC
  pdtscal = 0.;
  for (k=0 ; k<dimension ; k++)
    {
      pdtscal += pdtvect[k] * ZC[k];
    }
  if (pdtscal<0.)
    {
// le pdt scalaire est negatif : il s'agit d'un tetraedre mal oriente
#ifdef _AFFDEBUG
      {
        Process::Journal<<"  element "<<num_element<<"  indirect"<<finl;
      }
#endif
      return INDIRECT;
    }
#ifdef _AFFDEBUG
  {
    Process::Journal<<"  element "<<num_element<<"  direct"<<finl;
  }
#endif
  return DIRECT;
}
References Objet_U::dimension, DIRECT, finl, INDIRECT, and Process::Journal().
Referenced by Reorienter().
Member Data Documentation
info_obj
const Type_info Reorienter_tetraedres::info_obj static
Definition at line 35 of file Reorienter_tetraedres.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Reorienter_tetraedres.h
src/Kernel/Geometrie/Reorienter_tetraedres.cpp