TRUST: Deriv_Assembleur_base Class Reference
Deriv_Assembleur_base Class Reference
#include <Assembleur.h>
Public Member Functions
~Deriv_Assembleur_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Assembleur_base ()
Deriv_Assembleur_base (const Deriv_Assembleur_base &)
const Assembleur_base & valeur () const
Assembleur_base & valeur ()
const Assembleur_base * operator-> () const
Assembleur_base * operator-> ()
const Deriv_Assembleur_base & operator= (const Assembleur_base &)
const Deriv_Assembleur_base & operator= (const Deriv_Assembleur_base &)
operator const Assembleur_base & () const
operator Assembleur_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Assembleur_base & self_cast (Objet_U &)
static const
Deriv_Assembleur_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Assembleur_base * pointeur_
Detailed Description
Definition at line 46 of file Assembleur.h.
Constructor & Destructor Documentation
Deriv_Assembleur_base::~Deriv_Assembleur_base ()
Definition at line 26 of file Assembleur.cpp.
Deriv_Assembleur_base::Deriv_Assembleur_base ()
Definition at line 26 of file Assembleur.cpp.
Deriv_Assembleur_base::Deriv_Assembleur_base (const Deriv_Assembleur_base & t)
Definition at line 26 of file Assembleur.cpp.
Member Function Documentation
Objet_U * Deriv_Assembleur_base::cree_instance () [static]
Reimplemented in Assembleur.
Definition at line 26 of file Assembleur.cpp.
int Deriv_Assembleur_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Assembleur.
Definition at line 26 of file Assembleur.cpp.
const Type_info * Deriv_Assembleur_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Assembleur.
Definition at line 26 of file Assembleur.cpp.
const Type_info & Deriv_Assembleur_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Assembleur.cpp.
const Type_info * Deriv_Assembleur_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Assembleur.
Definition at line 26 of file Assembleur.cpp.
Deriv_Assembleur_base::operator Assembleur_base & ()
Definition at line 26 of file Assembleur.cpp.
Deriv_Assembleur_base::operator const Assembleur_base & () const
Definition at line 26 of file Assembleur.cpp.
const Assembleur_base * Deriv_Assembleur_base::operator-> () const [inline]
Definition at line 46 of file Assembleur.h.
: public DERIV(Assembleur_base)
Assembleur_base * Deriv_Assembleur_base::operator-> () [inline]
Definition at line 46 of file Assembleur.h.
: public DERIV(Assembleur_base)
const Deriv_Assembleur_base & Deriv_Assembleur_base::operator= (const Deriv_Assembleur_base & t)
Definition at line 26 of file Assembleur.cpp.
const Deriv_Assembleur_base & Deriv_Assembleur_base::operator= (const Assembleur_base & t)
Definition at line 26 of file Assembleur.cpp.
Sortie & Deriv_Assembleur_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Assembleur.
Definition at line 26 of file Assembleur.cpp.
Entree & Deriv_Assembleur_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Assembleur.
Definition at line 26 of file Assembleur.cpp.
const Deriv_Assembleur_base & Deriv_Assembleur_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Assembleur.
Definition at line 26 of file Assembleur.cpp.
Deriv_Assembleur_base & Deriv_Assembleur_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Assembleur.
Definition at line 26 of file Assembleur.cpp.
void Deriv_Assembleur_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Assembleur.cpp.
unsigned Deriv_Assembleur_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Assembleur.
Definition at line 26 of file Assembleur.cpp.
const Assembleur_base & Deriv_Assembleur_base::valeur () const [inline]
Definition at line 46 of file Assembleur.h.
Referenced by Assembleur::assembler(), Simpler_Base::assembler_matrice_pression_implicite(), Assembleur::assembler_QC(), Assembleur::associer_zone_cl_dis_base(), Assembleur::associer_zone_dis_base(), Assembleur::completer(), Navier_Stokes_std::corriger_derivee_expl(), Navier_Stokes_std::corriger_derivee_impl(), Navier_Stokes_std::initTimeStep(), Simpler::iterer_NS(), Simple::iterer_NS(), Piso::iterer_NS(), Piso::iterer_NS_PolyMAC(), Assembleur::modifier_secmem(), Assembleur::modifier_solution(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projeter(), Assembleur::zone_Cl_dis_base(), and Assembleur::zone_dis_base().
: public DERIV(Assembleur_base)
Assembleur_base & Deriv_Assembleur_base::valeur () [inline]
Definition at line 46 of file Assembleur.h.
: public DERIV(Assembleur_base)
Member Data Documentation
const Type_info Deriv_Assembleur_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Assembleur.
Definition at line 46 of file Assembleur.h.
Assembleur_base* Deriv_Assembleur_base::pointeur_ [private]
Definition at line 46 of file Assembleur.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Assembleur.h
src/Kernel/Framework/Assembleur.cpp