TRUST: Eval_Diff_VDF_var Class Reference
Eval_Diff_VDF_var Class Reference
class Eval_Diff_VDF_var
Cette classe represente un evaluateur de flux diffusif
avec un coefficient de diffusivite qui n'est pas constant en espace.
#include <Eval_Diff_VDF_var.h>
Public Member Functions
void associer (const Champ_base &) override
void mettre_a_jour () override
const Champ_base & get_diffusivite () const override
const Champ_base & diffusivite () const
double nu_1_impl (int i, int compo) const
double nu_2_impl (int i, int compo) const
double nu_t_impl (int i, int compo) const
double nu_lam_impl_face (int i, int j, int k, int l, int compo) const
double nu_lam_impl_face2 (int i, int j, int compo) const
double tau_tan_impl (int i, int j) const
bool uses_wall () const
bool uses_mod () const
const DoubleTab & get_k_elem () const
pour F5 seulement ...
double compute_heq_impl (double d0, int i, double d1, int j, int compo) const
double nu_1_impl_face (int i, int j, int compo) const
double nu_2_impl_face (int i, int j, int k, int l, int compo) const
Public Member Functions inherited from Eval_Diff_VDF
virtual ~Eval_Diff_VDF ()
virtual const Champ_base & get_diffusivite () const =0
virtual void associer (const Champ_base &)=0
virtual void mettre_a_jour ()
int get_ind_Fluctu_Term () const
double get_dv_mvol (const int i) const
virtual double get_equivalent_distance (int boundary_index, int local_face) const
Protected Attributes
Ref_Champ_base diffusivite_
DoubleVect dv_diffusivite
Detailed Description
class Eval_Diff_VDF_var
Cette classe represente un evaluateur de flux diffusif
avec un coefficient de diffusivite qui n'est pas constant en espace.
See also
Evaluateur_VDF
Definition at line 29 of file Eval_Diff_VDF_var.h.
Member Function Documentation
associer()
void Eval_Diff_VDF_var::associer (const Champ_base & diffu) inline override virtual
Implements Eval_Diff_VDF.
Definition at line 64 of file Eval_Diff_VDF_var.h.
{
  diffusivite_ = diffu;
  dv_diffusivite.ref(diffu.valeurs());
}
References diffusivite_, dv_diffusivite, TRUSTVect< _TYPE_ >::ref(), and Champ_Proto::valeurs().
compute_heq_impl()
double Eval_Diff_VDF_var::compute_heq_impl (double d0, int i, double d1, int j, int compo) const inline
Definition at line 48 of file Eval_Diff_VDF_var.h.
  {
    return 1./(d0/dv_diffusivite(i) + d1/dv_diffusivite(j));
  }
References dv_diffusivite.
Referenced by Eval_Dift_VDF_var::compute_heq_impl().
diffusivite()
const Champ_base & Eval_Diff_VDF_var::diffusivite () const inline
Definition at line 35 of file Eval_Diff_VDF_var.h.
{ return get_diffusivite(); }
References get_diffusivite().
get_diffusivite()
const Champ_base & Eval_Diff_VDF_var::get_diffusivite () const inline override virtual
Implements Eval_Diff_VDF.
Definition at line 76 of file Eval_Diff_VDF_var.h.
{
  assert(diffusivite_.non_nul());
  return diffusivite_.valeur();
}
References diffusivite_, O_U_Ptr::non_nul(), and Ref_Champ_base::valeur().
Referenced by diffusivite().
get_k_elem()
const DoubleTab & Eval_Diff_VDF_var::get_k_elem () const inline
pour F5 seulement ...
Definition at line 46 of file Eval_Diff_VDF_var.h.
mettre_a_jour()
void Eval_Diff_VDF_var::mettre_a_jour () inline override virtual
Reimplemented from Eval_Diff_VDF.
Reimplemented in Eval_Dift_VDF_var_Face, and Eval_Dift_VDF_var.
Definition at line 70 of file Eval_Diff_VDF_var.h.
{
  diffusivite_->valeurs().echange_espace_virtuel();
  dv_diffusivite.ref(diffusivite_->valeurs());
}
References diffusivite_, dv_diffusivite, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_ >::ref(), and Champ_Proto::valeurs().
Referenced by Eval_Dift_VDF_var::mettre_a_jour().
nu_1_impl()
double Eval_Diff_VDF_var::nu_1_impl (int i, int compo) const inline
Definition at line 38 of file Eval_Diff_VDF_var.h.
{ return dv_diffusivite(i); }
References dv_diffusivite.
Referenced by Eval_Dift_VDF_var::nu_1_impl().
nu_1_impl_face()
double Eval_Diff_VDF_var::nu_1_impl_face (int i, int j, int compo) const inline
Definition at line 53 of file Eval_Diff_VDF_var.h.
{ return 0.5*(dv_diffusivite(i)+dv_diffusivite(j)); }
References dv_diffusivite.
Referenced by nu_lam_impl_face2(), and Eval_Dift_VDF_var::nu_lam_impl_face2().
nu_2_impl()
double Eval_Diff_VDF_var::nu_2_impl (int i, int compo) const inline
Definition at line 39 of file Eval_Diff_VDF_var.h.
{ return dv_diffusivite(i); }
References dv_diffusivite.
Referenced by Eval_Dift_VDF_var::nu_2_impl().
nu_2_impl_face()
double Eval_Diff_VDF_var::nu_2_impl_face (int i, int j, int k, int l, int compo) const inline
Definition at line 54 of file Eval_Diff_VDF_var.h.
  {
    return 0.25*(dv_diffusivite(i)+dv_diffusivite(j)+dv_diffusivite(k)+dv_diffusivite(l));
  }
References dv_diffusivite.
Referenced by nu_lam_impl_face(), and Eval_Dift_VDF_var::nu_lam_impl_face().
nu_lam_impl_face()
double Eval_Diff_VDF_var::nu_lam_impl_face (int i, int j, int k, int l, int compo) const inline
Definition at line 41 of file Eval_Diff_VDF_var.h.
{ return nu_2_impl_face(i,j,k,l,compo); }
References nu_2_impl_face().
nu_lam_impl_face2()
double Eval_Diff_VDF_var::nu_lam_impl_face2 (int i, int j, int compo) const inline
Definition at line 42 of file Eval_Diff_VDF_var.h.
{ return nu_1_impl_face(i,j,compo); }
References nu_1_impl_face().
nu_t_impl()
double Eval_Diff_VDF_var::nu_t_impl (int i, int compo) const inline
Definition at line 40 of file Eval_Diff_VDF_var.h.
{ return 0.; }
tau_tan_impl()
double Eval_Diff_VDF_var::tau_tan_impl (int i, int j) const inline
Definition at line 43 of file Eval_Diff_VDF_var.h.
{ return 0.; }
uses_mod()
bool Eval_Diff_VDF_var::uses_mod () const inline
Definition at line 45 of file Eval_Diff_VDF_var.h.
{ return false; }
uses_wall()
bool Eval_Diff_VDF_var::uses_wall () const inline
Definition at line 44 of file Eval_Diff_VDF_var.h.
{ return false; }
Member Data Documentation
diffusivite_
Ref_Champ_base Eval_Diff_VDF_var::diffusivite_ protected
Definition at line 60 of file Eval_Diff_VDF_var.h.
Referenced by associer(), get_diffusivite(), and mettre_a_jour().
dv_diffusivite
DoubleVect Eval_Diff_VDF_var::dv_diffusivite protected
Definition at line 61 of file Eval_Diff_VDF_var.h.
Referenced by associer(), compute_heq_impl(), mettre_a_jour(), nu_1_impl(), nu_1_impl_face(), nu_2_impl(), and nu_2_impl_face().
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Eval_Diff_Dift/Eval_Diff_VDF_var.h