TRUST: Forchheimer_QC_VDF_Face Class Reference
Forchheimer_QC_VDF_Face Class Reference
#include <Source_QC_VDF_Face.h>
Public Member Functions
Forchheimer_QC_VDF_Face ()
~Forchheimer_QC_VDF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & ajouter_mere (DoubleTab &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Forchheimer_QC_VDF_Face & self_cast (Objet_U &)
static const
Forchheimer_QC_VDF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Detailed Description
Definition at line 90 of file Source_QC_VDF_Face.h.
Constructor & Destructor Documentation
Forchheimer_QC_VDF_Face::Forchheimer_QC_VDF_Face ()
Definition at line 60 of file Source_QC_VDF_Face.cpp.
Forchheimer_QC_VDF_Face::~Forchheimer_QC_VDF_Face ()
Definition at line 60 of file Source_QC_VDF_Face.cpp.
Member Function Documentation
DoubleTab & Forchheimer_QC_VDF_Face::ajouter (DoubleTab & resu) const [virtual]
Reimplemented from Terme_Source_VDF_base.
Definition at line 64 of file Source_QC_VDF_Face.cpp.
References Source_Fluide_Dilatable_Face< Forchheimer_QC_VDF_Face >::ajouter_impl().
Referenced by ajouter_mere().
{ return ajouter_impl(resu); }
DoubleTab & Forchheimer_QC_VDF_Face::ajouter_mere (DoubleTab & resu) const
Definition at line 63 of file Source_QC_VDF_Face.cpp.
References ajouter().
{ return Source_Forchheimer_VDF_Face::ajouter(resu); }
void Forchheimer_QC_VDF_Face::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const [virtual]
contribution a la matrice implicite des termes sources
par defaut pas de contribution
Reimplemented from Source_base.
Definition at line 65 of file Source_QC_VDF_Face.cpp.
References Source_Fluide_Dilatable_Face< Forchheimer_QC_VDF_Face >::contribuer_a_avec_impl().
{ contribuer_a_avec_impl(resu,mat); }
Objet_U * Forchheimer_QC_VDF_Face::cree_instance () [static]
Reimplemented from Source_Forchheimer_VDF_Face.
Definition at line 60 of file Source_QC_VDF_Face.cpp.
int Forchheimer_QC_VDF_Face::duplique () const [virtual]
Reimplemented from Source_Forchheimer_VDF_Face.
Definition at line 60 of file Source_QC_VDF_Face.cpp.
const Type_info * Forchheimer_QC_VDF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_Forchheimer_VDF_Face.
Definition at line 60 of file Source_QC_VDF_Face.cpp.
const Type_info * Forchheimer_QC_VDF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_Forchheimer_VDF_Face.
Definition at line 60 of file Source_QC_VDF_Face.cpp.
Sortie & Forchheimer_QC_VDF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_Forchheimer_VDF_Face.
Definition at line 61 of file Source_QC_VDF_Face.cpp.
{ return Source_Forchheimer_VDF_Face::printOn(os); }
Entree & Forchheimer_QC_VDF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_Forchheimer_VDF_Face.
Definition at line 62 of file Source_QC_VDF_Face.cpp.
{ return Source_Forchheimer_VDF_Face::readOn(is); }
const Forchheimer_QC_VDF_Face & Forchheimer_QC_VDF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_Forchheimer_VDF_Face.
Definition at line 60 of file Source_QC_VDF_Face.cpp.
Forchheimer_QC_VDF_Face & Forchheimer_QC_VDF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Source_Forchheimer_VDF_Face.
Definition at line 60 of file Source_QC_VDF_Face.cpp.
unsigned Forchheimer_QC_VDF_Face::taille_memoire () const [virtual]
Reimplemented from Source_Forchheimer_VDF_Face.
Definition at line 60 of file Source_QC_VDF_Face.cpp.
Member Data Documentation
const Type_info Forchheimer_QC_VDF_Face::info_obj [static]
Reimplemented from Source_Forchheimer_VDF_Face.
Definition at line 92 of file Source_QC_VDF_Face.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VDF/Source_QC_VDF_Face.h
src/ThHyd/Dilatable/Quasi_Compressible/VDF/Source_QC_VDF_Face.cpp