TRUST: Raffiner_isotrope_parallele Class Reference
Raffiner_isotrope_parallele Class Reference
: class Raffiner_isotrope_parallele
<Description of class Raffiner_isotrope_parallele>
#include <Raffiner_isotrope_parallele.h>
Public Member Functions
Raffiner_isotrope_parallele ()
~Raffiner_isotrope_parallele ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Raffiner_isotrope_parallele & self_cast (Objet_U &)
static const
Raffiner_isotrope_parallele & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Entree & interpreter (Entree &is)
Detailed Description
: class Raffiner_isotrope_parallele
<Description of class Raffiner_isotrope_parallele>
Definition at line 36 of file Raffiner_isotrope_parallele.h.
Constructor & Destructor Documentation
Raffiner_isotrope_parallele::Raffiner_isotrope_parallele ()
Definition at line 40 of file Raffiner_isotrope_parallele.cpp.
Raffiner_isotrope_parallele::~Raffiner_isotrope_parallele ()
Definition at line 40 of file Raffiner_isotrope_parallele.cpp.
Member Function Documentation
Objet_U * Raffiner_isotrope_parallele::cree_instance () [static]
Reimplemented from Raffiner_Simplexes.
Definition at line 40 of file Raffiner_isotrope_parallele.cpp.
int Raffiner_isotrope_parallele::duplique () const [virtual]
Reimplemented from Raffiner_Simplexes.
Definition at line 40 of file Raffiner_isotrope_parallele.cpp.
const Type_info * Raffiner_isotrope_parallele::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Raffiner_Simplexes.
Definition at line 40 of file Raffiner_isotrope_parallele.cpp.
const Type_info * Raffiner_isotrope_parallele::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Raffiner_Simplexes.
Definition at line 40 of file Raffiner_isotrope_parallele.cpp.
Entree & Raffiner_isotrope_parallele::interpreter (Entree & is) [protected, virtual]
< XD_ADD_P chaine name of initial Zones
< XD_ADD_P chaine name of new Zones
< XD_ADD_P flag writing Zones in ascii format
< XD_ADD_P flag writing Zones in hdf format
Reimplemented from Interprete_geometrique_base.
Definition at line 198 of file Raffiner_isotrope_parallele.cpp.
References Param::ajouter(), Param::ajouter_flag(), Statistiques::begin_count(), Scatter::calculer_renum_items_communs(), Cerr, FichierHDF::close(), Scatter::construire_correspondance_sommets_par_coordonnees(), Scatter::construire_structures_paralleles(), FichierHDF::create(), FichierHDF::create_and_fill_dataset_MW(), debug(), Objet_U::dimension, IntTab::dimension(), ecrit(), Statistiques::end_count(), Process::exit(), Zone::faces_joint(), finl, Process::force_single_file(), Objet_U::format_precision_geom, Scatter::init_sequential_domain(), FichierHDF::is_hdf5(), Zone::les_elems(), Domaine::les_sommets(), Param::lire_avec_accolades(), Process::me(), mon_construire_correspondance_sommets_par_coordonnees(), Process::mp_max(), Zone::nb_elem(), Domaine::nb_som(), Statistiques::new_counter(), Nom::nom_me(), Process::nproc(), FichierHDF::open(), EcrFicCollecte::ouvrir(), LecFicDistribue::ouvrir(), LecFicDiffuse::ouvrir(), Sortie_Fichier_base::precision(), Objet_U::que_suis_je(), FichierHDF::read_dataset(), Raffiner_Simplexes::refine_domain(), Param::REQUIRED, DoubleTab::resize(), IntTab::resize(), Sortie::set_bin(), Entree::set_bin(), Domaine::set_fichier_lu(), Sortie_Fichier_base::setf(), Joint::SOMMET, statistiques(), test(), Scatter::trier_les_joints(), Scatter::uninit_sequential_domain(), and Domaine::zone().
{
  int form=0, format_hdf = 0;
  Nom org,newd;
  Param param(que_suis_je());
// XD Raffiner_isotrope_parallele interprete Raffiner_isotrope_parallele 1 Refine parallel mesh in parallel
  param.ajouter("name_of_initial_zones",&org,Param::REQUIRED); //!< XD_ADD_P chaine name of initial Zones
  param.ajouter("name_of_new_zones",&newd,Param::REQUIRED); //!< XD_ADD_P chaine name of new Zones
  param.ajouter("ascii",&form);  //!< XD_ADD_P flag writing Zones in ascii format
  param.ajouter_flag("single_hdf",&format_hdf); //!< XD_ADD_P flag writing Zones in hdf format
  param.lire_avec_accolades(is);
// Force un fichier unique au dela d'un certain nombre de rangs MPI:
  if (Process::force_single_file(Process::nproc(), org+".Zones"))
    format_hdf = 1;
  int binaire=!form;
  if (form && format_hdf)
    {
      Cerr << "Raffiner_isotrope_parallele::interpreter(): options 'ascii' and 'single_hdf' are mutually exclusive!" << finl;
      Process::exit(1);
    }
  Domaine dom_org;
  Noms liste_bords_periodiques;
  org+=".Zones";
  Nom copy(org);
  copy = copy.nom_me(Process::nproc(), "p", 1);
// bool is_hdf = FichierHDF::is_hdf5(copy);
  LecFicDiffuse test;
  bool is_hdf = test.ouvrir(copy) && FichierHDF::is_hdf5(copy);
  if (!is_hdf)
    {
      LecFicDistribue    fichier;
      fichier.set_bin(binaire);
      fichier.ouvrir(org);
      fichier >> dom_org;
      dom_org.set_fichier_lu(org);
      fichier >> liste_bords_periodiques;
    }
  else
    {
      FichierHDFPar fic_hdf;
// FichierHDF fic_hdf;
      org = copy;
      fic_hdf.open(org, true);
      Entree_Brute data;
      fic_hdf.read_dataset("/zone", Process::me(), data);
// Feed TRUST objects:
      data >> dom_org;
      dom_org.set_fichier_lu(org);
      data >> liste_bords_periodiques;
      fic_hdf.close();
    }
  Scatter::uninit_sequential_domain(dom_org);
  Domaine dom_new(dom_org);
  refine_domain(dom_org,dom_new);
  static Stat_Counter_Id stats = statistiques().new_counter(0 /* Level */, "Mailler_Parallel", 0 /* Group */);
  if (nproc() > 1)
    {
      Scatter::uninit_sequential_domain(dom_new);
      int nb_sommet_avant_completion=dom_new.nb_som();
      Scatter::trier_les_joints(dom_new.zone(0).faces_joint());
      statistiques().begin_count(stats);
      mon_construire_correspondance_sommets_par_coordonnees(dom_new);
      if (0)
        {
          Nom debug(newd);
          debug+="_debug.Zones";
          EcrFicCollecte os;
          os.set_bin(binaire);
          os.ouvrir(debug);
          if (!binaire)
            {
              os.setf(ios::scientific);
              os.precision(Objet_U::format_precision_geom);
            }
          os << dom_new;
          os << liste_bords_periodiques;
        }
// else
      {
        Scatter::construire_correspondance_sommets_par_coordonnees(dom_new);
        Scatter::calculer_renum_items_communs(dom_new.zone(0).faces_joint(), Joint::SOMMET);
        statistiques().end_count(stats);
        double maxtime = mp_max(statistiques().last_time(stats));
        Cerr << "Scatter::construire_correspondance_sommets_par_coordonnees fin, time:"
             << maxtime
             << finl;
        statistiques().begin_count(stats);
        Scatter::construire_structures_paralleles(dom_new, liste_bords_periodiques);
        statistiques().end_count(stats);
        maxtime = mp_max(statistiques().last_time(stats));
        Cerr << "Scatter::construire_structures_paralleles, time:" << maxtime << finl;
        int ecrit=1;
        if (ecrit)
          {
            int nb_elem_reel=dom_new.zone(0).nb_elem();
            Scatter::uninit_sequential_domain(dom_new);
            dom_new.zone(0).les_elems().resize( nb_elem_reel,dom_new.zone(0).les_elems().dimension(1));
            dom_new.les_sommets().resize(nb_sommet_avant_completion,dimension);
            Scatter::uninit_sequential_domain(dom_new);
            newd+=".Zones";
            if( !format_hdf )
              {
                EcrFicCollecte os;
                os.set_bin(binaire);
                os.ouvrir(newd);
                if (!binaire)
                  {
                    os.setf(ios::scientific);
                    os.precision(Objet_U::format_precision_geom);
                  }
                os << dom_new;
                os << liste_bords_periodiques;
              }
            else
              {
                Sortie_Brute os_hdf;
                os_hdf << dom_new;
                os_hdf << liste_bords_periodiques;
                FichierHDFPar fic_hdf;
                newd = newd.nom_me(Process::nproc(), "p", 1);
                fic_hdf.create(newd);
                fic_hdf.create_and_fill_dataset_MW("/zone", os_hdf);
                fic_hdf.close();
              }
          }
      }
    }
  else
    {
      Scatter::init_sequential_domain(dom_new);
    }
  return is;
}
Sortie & Raffiner_isotrope_parallele::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Raffiner_Simplexes.
Definition at line 42 of file Raffiner_isotrope_parallele.cpp.
{
  Raffiner_Simplexes::printOn( os );
  return os;
}
Entree & Raffiner_isotrope_parallele::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Raffiner_Simplexes.
Definition at line 48 of file Raffiner_isotrope_parallele.cpp.
{
  Raffiner_Simplexes::readOn( is );
  return is;
}
Raffiner_isotrope_parallele & Raffiner_isotrope_parallele::self_cast (Objet_U & r) [static]
Reimplemented from Raffiner_Simplexes.
Definition at line 40 of file Raffiner_isotrope_parallele.cpp.
const Raffiner_isotrope_parallele & Raffiner_isotrope_parallele::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Raffiner_Simplexes.
Definition at line 40 of file Raffiner_isotrope_parallele.cpp.
unsigned Raffiner_isotrope_parallele::taille_memoire () const [virtual]
Reimplemented from Raffiner_Simplexes.
Definition at line 40 of file Raffiner_isotrope_parallele.cpp.
Member Data Documentation
const Type_info Raffiner_isotrope_parallele::info_obj [static]
Reimplemented from Raffiner_Simplexes.
Definition at line 39 of file Raffiner_isotrope_parallele.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Raffiner_isotrope_parallele.h
src/Kernel/Geometrie/Raffiner_isotrope_parallele.cpp