TRUST: Eval_Forchheimer_VEF_Face Class Reference
Eval_Forchheimer_VEF_Face Class Reference
class Eval_Forchheimer_VEF_Face
#include <Eval_Forchheimer_VEF_Face.h>
Public Member Functions
Eval_Forchheimer_VEF_Face ()
Eval_Forchheimer_VEF_Face (const Eval_Forchheimer_VEF_Face &eval)
void mettre_a_jour () override
double calculer_terme_source_standard (int) const override
void calculer_terme_source_standard (int, DoubleVect &) const override
double calculer_terme_source_non_standard (int) const override
void calculer_terme_source_non_standard (int, DoubleVect &) const override
void setCf (double)
void associer (const Champ_Inc &)
void setPorosite (double p)
Public Member Functions inherited from Evaluateur_Source_VEF_Face
Evaluateur_Source_VEF_Face ()
Evaluateur_Source_VEF_Face (const Evaluateur_Source_VEF_Face &)
void completer () override
virtual double calculer_terme_source_standard (int) const =0
virtual double calculer_terme_source_non_standard (int) const =0
virtual void calculer_terme_source_standard (int, DoubleVect &) const =0
virtual void calculer_terme_source_non_standard (int, DoubleVect &) const =0
void changer_volumes_entrelaces_Cl (DoubleVect &) override
Public Member Functions inherited from Evaluateur_Source_VEF
Evaluateur_Source_VEF ()
virtual ~Evaluateur_Source_VEF ()
Evaluateur_Source_VEF (const Evaluateur_Source_VEF &)
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
virtual void changer_volumes_entrelaces_Cl (DoubleVect &)=0
Public Attributes
Modele_Permeabilite modK
Protected Member Functions
void calculer_terme_source (int, DoubleVect &, const DoubleVect &) const
Protected Attributes
Ref_Champ_Inc vitesse
double Cf
double porosite
Protected Attributes inherited from Evaluateur_Source_VEF_Face
DoubleVect volumes_entrelaces
DoubleVect volumes_entrelaces_Cl
DoubleVect porosite_surf
IntTab face_voisins
Protected Attributes inherited from Evaluateur_Source_VEF
Ref_Zone_VEF la_zone
Ref_Zone_Cl_VEF la_zone_cl
Detailed Description
class Eval_Forchheimer_VEF_Face
Definition at line 29 of file Eval_Forchheimer_VEF_Face.h.
Constructor & Destructor Documentation
Eval_Forchheimer_VEF_Face() [1/2]
Eval_Forchheimer_VEF_Face::Eval_Forchheimer_VEF_Face () inline
Definition at line 61 of file Eval_Forchheimer_VEF_Face.h.
                                                            : Cf(1.), porosite(1)
{}
Eval_Forchheimer_VEF_Face() [2/2]
Eval_Forchheimer_VEF_Face::Eval_Forchheimer_VEF_Face (const Eval_Forchheimer_VEF_Face & eval) inline
Definition at line 64 of file Eval_Forchheimer_VEF_Face.h.
  : Evaluateur_Source_VEF_Face(eval),Cf(1.), porosite(1)
{
}
Member Function Documentation
associer()
void Eval_Forchheimer_VEF_Face::associer (const Champ_Inc & v) inline
Definition at line 76 of file Eval_Forchheimer_VEF_Face.h.
{
  vitesse = v;
}
References vitesse.
Referenced by Source_Forchheimer_VEF_Face::associer_pb().
calculer_terme_source()
void Eval_Forchheimer_VEF_Face::calculer_terme_source (int num_face, DoubleVect & source, const DoubleVect & volumes) const inline protected
Definition at line 88 of file Eval_Forchheimer_VEF_Face.h.
{
  int size=source.size();
  for (int i=0; i<size; i++)
    {
      double U = vitesse->valeurs()(num_face,i);
      source(i) = -Cf/sqrt(modK->getK(porosite))*volumes(num_face)*porosite_surf(num_face)*std::fabs(U)*U;
    }
}
References Cf, Modele_Permeabilite::getK(), modK, porosite, Evaluateur_Source_VEF_Face::porosite_surf, TRUSTVect< _TYPE_ >::size(), Champ_Inc::valeurs(), and vitesse.
Referenced by calculer_terme_source_non_standard(), and calculer_terme_source_standard().
calculer_terme_source_non_standard() [1/2]
double Eval_Forchheimer_VEF_Face::calculer_terme_source_non_standard (int num_face) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 112 of file Eval_Forchheimer_VEF_Face.h.
{
  Cerr << "Eval_Forchheimer_VEF_Face::calculer_terme_source_non_standard(int num_face) can't be used on a vector source term." << finl;
  Process::exit();
  return 0;
}
References Cerr, Process::exit(), and finl.
calculer_terme_source_non_standard() [2/2]
void Eval_Forchheimer_VEF_Face::calculer_terme_source_non_standard (int num_face, DoubleVect & source) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 102 of file Eval_Forchheimer_VEF_Face.h.
{
  calculer_terme_source(num_face, source, volumes_entrelaces_Cl);
}
References calculer_terme_source(), and Evaluateur_Source_VEF_Face::volumes_entrelaces_Cl.
calculer_terme_source_standard() [1/2]
double Eval_Forchheimer_VEF_Face::calculer_terme_source_standard (int num_face) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 106 of file Eval_Forchheimer_VEF_Face.h.
{
  Cerr << "Eval_Forchheimer_VEF_Face::calculer_terme_source_standard(int num_face) can't be used on a vector source term." << finl;
  Process::exit();
  return 0;
}
References Cerr, Process::exit(), and finl.
calculer_terme_source_standard() [2/2]
void Eval_Forchheimer_VEF_Face::calculer_terme_source_standard (int num_face, DoubleVect & source) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 98 of file Eval_Forchheimer_VEF_Face.h.
{
  calculer_terme_source(num_face, source, volumes_entrelaces);
}
References calculer_terme_source(), and Evaluateur_Source_VEF_Face::volumes_entrelaces.
mettre_a_jour()
void Eval_Forchheimer_VEF_Face::mettre_a_jour () inline override virtual
Implements Evaluateur_Source_VEF.
Definition at line 82 of file Eval_Forchheimer_VEF_Face.h.
{
  ;
}
setCf()
void Eval_Forchheimer_VEF_Face::setCf (double c) inline
Definition at line 70 of file Eval_Forchheimer_VEF_Face.h.
{
  Cf = c;
}
References Cf.
Referenced by Source_Forchheimer_VEF_Face::readOn().
setPorosite()
void Eval_Forchheimer_VEF_Face::setPorosite (double p) inline
Definition at line 45 of file Eval_Forchheimer_VEF_Face.h.
  {
    porosite = p;
  }
References porosite.
Referenced by Source_Forchheimer_VEF_Face::readOn().
Member Data Documentation
Cf
double Eval_Forchheimer_VEF_Face::Cf protected
Definition at line 52 of file Eval_Forchheimer_VEF_Face.h.
Referenced by calculer_terme_source(), and setCf().
modK
Modele_Permeabilite Eval_Forchheimer_VEF_Face::modK
Definition at line 43 of file Eval_Forchheimer_VEF_Face.h.
Referenced by calculer_terme_source(), and Source_Forchheimer_VEF_Face::readOn().
porosite
double Eval_Forchheimer_VEF_Face::porosite protected
Definition at line 53 of file Eval_Forchheimer_VEF_Face.h.
Referenced by calculer_terme_source(), and setPorosite().
vitesse
Ref_Champ_Inc Eval_Forchheimer_VEF_Face::vitesse protected
Definition at line 51 of file Eval_Forchheimer_VEF_Face.h.
Referenced by associer(), and calculer_terme_source().
The documentation for this class was generated from the following file:
src/VEF/Sources/Evaluateurs/Eval_Forchheimer_VEF_Face.h