TRUST: Hexa_VEF Class Reference
Hexa_VEF Class Reference
#include <Hexa_VEF.h>
Public Member Functions
~Hexa_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Hexa_VEF ()
KEL_(0,fa7),KEL_(1,fa7) sont les numeros locaux des 2 faces
qui entourent la facette de numero local fa7
le numero local de la fa7 est celui du sommet qui la porte.
int nb_facette () const override
void creer_facette_normales (const Zone &, DoubleTab &, const IntVect &) const override
// calcule les normales des facettes pour des elem standards
void creer_normales_facettes_Cl (DoubleTab &, int, int, const DoubleTab &, const DoubleVect &, const Zone &) const override
void modif_volumes_entrelaces (int, int, const Zone_VEF &, DoubleVect &, int) const override
modifie les volumes entrelaces pour la face j d'un elem
non standard
void modif_volumes_entrelaces_faces_joints (int, int, const Zone_VEF &, DoubleVect &, int) const override
modifie les volumes entrelaces pour la face joint j d'un elem
non standard
void modif_normales_facettes_Cl (DoubleTab &, int, int, int, int, int, int) const override
modifie normales_facettes_Cl quand idirichlet=3
idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=3, n1 est le numero du sommet confondu avec G
void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int, const DoubleVect &) const override
void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const override
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=2, n1 est le numero du sommet confondu avec G
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const override
remplit le tableau face_normales dans la Zone_VEF
void traiter_normales_facettes_Cl (DoubleTab &, int, int, const DoubleTab &, const DoubleVect &, int, int, int, int, int) const
Public Member Functions inherited from Elem_VEF_base
Elem_VEF_base ()
~Elem_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual int nb_facette () const =0
const IntTab & KEL () const
virtual void creer_facette_normales (const Zone &, DoubleTab &, const IntVect &) const =0
virtual void creer_normales_facettes_Cl (DoubleTab &, int, int, const DoubleTab &, const DoubleVect &, const Zone &) const =0
virtual void modif_volumes_entrelaces (int, int, const Zone_VEF &, DoubleVect &, int) const =0
virtual void modif_volumes_entrelaces_faces_joints (int, int, const Zone_VEF &, DoubleVect &, int) const =0
virtual void modif_normales_facettes_Cl (DoubleTab &, int, int, int, int, int, int) const =0
virtual void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int, const DoubleVect &) const =0
virtual void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const =0
virtual void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Hexa_VEF & self_cast (Objet_U &)
static const Hexa_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Elem_VEF_base
static const Type_info * info ()
static Elem_VEF_base & self_cast (Objet_U &)
static const Elem_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Elem_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Elem_VEF_base
IntTab KEL_
Detailed Description
Definition at line 22 of file Hexa_VEF.h.
Constructor & Destructor Documentation
~Hexa_VEF()
Hexa_VEF::~Hexa_VEF ()
Definition at line 19 of file Hexa_VEF.cpp.
Hexa_VEF()
Hexa_VEF::Hexa_VEF ()
KEL_(0,fa7),KEL_(1,fa7) sont les numeros locaux des 2 faces
qui entourent la facette de numero local fa7
le numero local de la fa7 est celui du sommet qui la porte.
Definition at line 37 of file Hexa_VEF.cpp.
{
  int tmp[4][12]=
  {
    {1, 3, 4, 0,  5, 5, 5, 5,  0, 1, 3, 4},
    {2, 2, 2, 2,  1, 3, 4, 0,  1, 3, 4, 0},
    {0, 1, 3, 2,  4, 5, 7, 6,  4, 5, 7, 6},
    {1, 3, 2, 0,  5, 7, 6, 4,  0, 1, 3, 2}
  };
  KEL_.resize(4,12);
  for (int i=0; i<4; i++)
    for (int j=0; j<12; j++)
      KEL_(i,j)=tmp[i][j];
}
References Elem_VEF_base::KEL_, and TRUSTTab< _TYPE_ >::resize().
Member Function Documentation
calcul_vc()
void Hexa_VEF::calcul_vc (const ArrOfInt & Face, ArrOfDouble & vc, const ArrOfDouble & vs, const DoubleTab & vsom, const Champ_Inc_base & vitesse, int type_cl, const DoubleVect & porosite_face) const override virtual
Implements Elem_VEF_base.
Definition at line 669 of file Hexa_VEF.cpp.
{
  vc[0] = vs[0]/6;
  vc[1] = vs[1]/6;
  vc[2] = vs[2]/6;
}
calcul_xg()
void Hexa_VEF::calcul_xg (DoubleVect & xg, const DoubleTab & x, const int type_elem_Cl, int & idirichlet, int & n1, int & , int &) const override virtual
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=2, n1 est le numero du sommet confondu avec G
Implements Elem_VEF_base.
Definition at line 683 of file Hexa_VEF.cpp.
{
  int dim=xg.size();
  for (int j=0; j<dim; j++)
    xg[j]=(x(0,j)+x(1,j)+x(2,j)+x(3,j)+x(4,j)+x(5,j)+x(6,j)+x(7,j))*0.125;
  idirichlet=0;
}
References TRUSTVect< _TYPE_ >::size().
cree_instance()
Objet_U * Hexa_VEF::cree_instance () static
Definition at line 19 of file Hexa_VEF.cpp.
creer_facette_normales()
void Hexa_VEF::creer_facette_normales (const Zone & zone_geom, DoubleTab & facette_normales, const IntVect & rang_elem_non_std) const override virtual
// calcule les normales des facettes pour des elem standards
Implements Elem_VEF_base.
Definition at line 187 of file Hexa_VEF.cpp.
{
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
  const IntTab& les_Polys = zone_geom.les_elems();
  int nb_elem = zone_geom.nb_elem();
  int i, fa7;
  int num_som[8];
  double x[8][3];
  double x_[4][3];
  double xg[3];
  double xj0[3];
  double xjnum1[3];
  double xjnum2[3];
  double u[3];
  double v[3];
  double psc;
  double pv[3];
  facette_normales.reset();
  facette_normales.resize(0, nb_facette(), 3);
  zone_geom.creer_tableau_elements(facette_normales);
  for(i=0; i<nb_elem; i++)
    {
      if (rang_elem_non_std(i)==-1)
        {
          num_som[0]=les_Polys(i,0);
          num_som[1]=les_Polys(i,1);
          num_som[2]=les_Polys(i,2);
          num_som[3]=les_Polys(i,3);
          num_som[4]=les_Polys(i,4);
          num_som[5]=les_Polys(i,5);
          num_som[6]=les_Polys(i,6);
          num_som[7]=les_Polys(i,7);
          x[0][0]=les_coords(num_som[0],0);
          x[0][1]=les_coords(num_som[0],1);
          x[0][2]=les_coords(num_som[0],2);
          x[1][0]=les_coords(num_som[1],0);
          x[1][1]=les_coords(num_som[1],1);
          x[1][2]=les_coords(num_som[1],2);
          x[2][0]=les_coords(num_som[2],0);
          x[2][1]=les_coords(num_som[2],1);
          x[2][2]=les_coords(num_som[2],2);
          x[3][0]=les_coords(num_som[3],0);
          x[3][1]=les_coords(num_som[3],1);
          x[3][2]=les_coords(num_som[3],2);
          x[4][0]=les_coords(num_som[4],0);
          x[4][1]=les_coords(num_som[4],1);
          x[4][2]=les_coords(num_som[4],2);
          x[5][0]=les_coords(num_som[5],0);
          x[5][1]=les_coords(num_som[5],1);
          x[5][2]=les_coords(num_som[5],2);
          x[6][0]=les_coords(num_som[6],0);
          x[6][1]=les_coords(num_som[6],1);
          x[6][2]=les_coords(num_som[6],2);
          x[7][0]=les_coords(num_som[7],0);
          x[7][1]=les_coords(num_som[7],1);
          x[7][2]=les_coords(num_som[7],2);
          xg[0]=(x[0][0]+x[1][0]+x[2][0]+x[3][0]+x[4][0]+x[5][0]+x[6][0]+x[7][0])*0.125;
          xg[1]=(x[0][1]+x[1][1]+x[2][1]+x[3][1]+x[4][1]+x[5][1]+x[6][1]+x[7][1])*0.125;
          xg[2]=(x[0][2]+x[1][2]+x[2][2]+x[3][2]+x[4][2]+x[5][2]+x[6][2]+x[7][2])*0.125;
          for (fa7=0; fa7<nb_facette(); fa7++)
            {
// la fa7 d'un element standard a pour sommets
// fa7 et G de coordonnees xg :
              u[0]=x[KEL_(2,fa7)][0]-xg[0];
              u[1]=x[KEL_(2,fa7)][1]-xg[1];
              u[2]=x[KEL_(2,fa7)][2]-xg[2];
              v[0]=x[KEL_(3,fa7)][0]-xg[0];
              v[1]=x[KEL_(3,fa7)][1]-xg[1];
              v[2]=x[KEL_(3,fa7)][2]-xg[2];
              prodvect(u,v,pv);
// Orientation des normales :
// recuperation du numero de la face, puis de sommets et calcul du centre de gravite de la face
              int num1 = KEL_(0,fa7);
              int num2 = KEL_(1,fa7);
              switch (num1)
                {
                case 0:
                  {
                    num_som[0]=les_Polys(i,0);
                    num_som[1]=les_Polys(i,2);
                    num_som[2]=les_Polys(i,4);
                    num_som[3]=les_Polys(i,6);
                  }
                  break;
                case 1:
                  {
                    num_som[0]=les_Polys(i,0);
                    num_som[1]=les_Polys(i,1);
                    num_som[2]=les_Polys(i,4);
                    num_som[3]=les_Polys(i,5);
                  }
                  break;
                case 2:
                  {
                    num_som[0]=les_Polys(i,0);
                    num_som[1]=les_Polys(i,1);
                    num_som[2]=les_Polys(i,2);
                    num_som[3]=les_Polys(i,3);
                  }
                  break;
                case 3:
                  {
                    num_som[0]=les_Polys(i,1);
                    num_som[1]=les_Polys(i,3);
                    num_som[2]=les_Polys(i,5);
                    num_som[3]=les_Polys(i,7);
                  }
                  break;
                case 4:
                  {
                    num_som[0]=les_Polys(i,2);
                    num_som[1]=les_Polys(i,3);
                    num_som[2]=les_Polys(i,6);
                    num_som[3]=les_Polys(i,7);
                  }
                  break;
                case 5:
                  {
                    num_som[0]=les_Polys(i,4);
                    num_som[1]=les_Polys(i,5);
                    num_som[2]=les_Polys(i,6);
                    num_som[3]=les_Polys(i,7);
                  }
                  break;
                }
              x_[0][0]=les_coords(num_som[0],0);
              x_[0][1]=les_coords(num_som[0],1);
              x_[0][2]=les_coords(num_som[0],2);
              x_[1][0]=les_coords(num_som[1],0);
              x_[1][1]=les_coords(num_som[1],1);
              x_[1][2]=les_coords(num_som[1],2);
              x_[2][0]=les_coords(num_som[2],0);
              x_[2][1]=les_coords(num_som[2],1);
              x_[2][2]=les_coords(num_som[2],2);
              x_[3][0]=les_coords(num_som[3],0);
              x_[3][1]=les_coords(num_som[3],1);
              x_[3][2]=les_coords(num_som[3],2);
              xjnum1[0]=(x_[0][0]+x_[1][0]+x_[2][0]+x_[3][0])*0.25;
              xjnum1[1]=(x_[0][1]+x_[1][1]+x_[2][1]+x_[3][1])*0.25;
              xjnum1[2]=(x_[0][2]+x_[1][2]+x_[2][2]+x_[3][2])*0.25;
              switch (num2)
                {
                case 0:
                  {
                    num_som[0]=les_Polys(i,0);
                    num_som[1]=les_Polys(i,2);
                    num_som[2]=les_Polys(i,4);
                    num_som[3]=les_Polys(i,6);
                  }
                  break;
                case 1:
                  {
                    num_som[0]=les_Polys(i,0);
                    num_som[1]=les_Polys(i,1);
                    num_som[2]=les_Polys(i,4);
                    num_som[3]=les_Polys(i,5);
                  }
                  break;
                case 2:
                  {
                    num_som[0]=les_Polys(i,0);
                    num_som[1]=les_Polys(i,1);
                    num_som[2]=les_Polys(i,2);
                    num_som[3]=les_Polys(i,3);
                  }
                  break;
                case 3:
                  {
                    num_som[0]=les_Polys(i,1);
                    num_som[1]=les_Polys(i,3);
                    num_som[2]=les_Polys(i,5);
                    num_som[3]=les_Polys(i,7);
                  }
                  break;
                case 4:
                  {
                    num_som[0]=les_Polys(i,2);
                    num_som[1]=les_Polys(i,3);
                    num_som[2]=les_Polys(i,6);
                    num_som[3]=les_Polys(i,7);
                  }
                  break;
                case 5:
                  {
                    num_som[0]=les_Polys(i,4);
                    num_som[1]=les_Polys(i,5);
                    num_som[2]=les_Polys(i,6);
                    num_som[3]=les_Polys(i,7);
                  }
                  break;
                }
              x_[0][0]=les_coords(num_som[0],0);
              x_[0][1]=les_coords(num_som[0],1);
              x_[0][2]=les_coords(num_som[0],2);
              x_[1][0]=les_coords(num_som[1],0);
              x_[1][1]=les_coords(num_som[1],1);
              x_[1][2]=les_coords(num_som[1],2);
              x_[2][0]=les_coords(num_som[2],0);
              x_[2][1]=les_coords(num_som[2],1);
              x_[2][2]=les_coords(num_som[2],2);
              x_[3][0]=les_coords(num_som[3],0);
              x_[3][1]=les_coords(num_som[3],1);
              x_[3][2]=les_coords(num_som[3],2);
              xjnum2[0]=(x_[0][0]+x_[1][0]+x_[2][0]+x_[3][0])*0.25;
              xjnum2[1]=(x_[0][1]+x_[1][1]+x_[2][1]+x_[3][1])*0.25;
              xjnum2[2]=(x_[0][2]+x_[1][2]+x_[2][2]+x_[3][2])*0.25;
              xj0[0]= xjnum1[0]-xjnum2[0];
              xj0[1]= xjnum1[1]-xjnum2[1];
              xj0[2]= xjnum1[2]-xjnum2[2];
              psc=xj0[0]*pv[0] + xj0[1]*pv[1] + xj0[2]*pv[2] ;
              if (psc < 0)
                {
                  facette_normales(i,fa7,0) = pv[0]/2;
                  facette_normales(i,fa7,1) = pv[1]/2;
                  facette_normales(i,fa7,2) = pv[2]/2;
                }
              else
                {
                  facette_normales(i,fa7,0)= -pv[0]/2;
                  facette_normales(i,fa7,1)= -pv[1]/2;
                  facette_normales(i,fa7,2)= -pv[2]/2;
                }
            }
        }
    }
  facette_normales.echange_espace_virtuel();
}
References Domaine::coord_sommets(), Zone::creer_tableau_elements(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Elem_VEF_base::KEL_, Zone::les_elems(), Zone::nb_elem(), nb_facette(), prodvect(), TRUSTTab< _TYPE_ >::reset(), and TRUSTTab< _TYPE_ >::resize().
creer_normales_facettes_Cl()
void Hexa_VEF::creer_normales_facettes_Cl (DoubleTab & normales_facettes_Cl, int fa7, int num_elem, const DoubleTab & x, const DoubleVect & xg, const Zone & zone_geom) const override virtual
Implements Elem_VEF_base.
Definition at line 434 of file Hexa_VEF.cpp.
{
  double u[3];
  double v[3];
  double xj0[3];
  double xjnum1[3];
  double xjnum2[3];
  int num_som[8];
  double x_[4][3];
  double pv[3];
  double psc;
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
  const IntTab& les_Polys = zone_geom.les_elems();
  int i2 = KEL_(2,fa7);
  int i3 = KEL_(3,fa7);
  u[0]=x(i2,0)-xg[0];
  u[1]=x(i2,1)-xg[1];
  u[2]=x(i2,2)-xg[2];
  v[0]=x(i3,0)-xg[0];
  v[1]=x(i3,1)-xg[1];
  v[2]=x(i3,2)-xg[2];
  prodvect(u,v,pv);
// Orientation des normales :
// recuperation du numero de la face, puis de sommets et calcul du centre de gravite de la face
  int num1 = KEL_(0,fa7);
  int num2 = KEL_(1,fa7);
  switch (num1)
    {
    case 0:
      {
        num_som[0]=les_Polys(num_elem,0);
        num_som[1]=les_Polys(num_elem,2);
        num_som[2]=les_Polys(num_elem,4);
        num_som[3]=les_Polys(num_elem,6);
      }
      break;
    case 1:
      {
        num_som[0]=les_Polys(num_elem,0);
        num_som[1]=les_Polys(num_elem,1);
        num_som[2]=les_Polys(num_elem,4);
        num_som[3]=les_Polys(num_elem,5);
      }
      break;
    case 2:
      {
        num_som[0]=les_Polys(num_elem,0);
        num_som[1]=les_Polys(num_elem,1);
        num_som[2]=les_Polys(num_elem,2);
        num_som[3]=les_Polys(num_elem,3);
      }
      break;
    case 3:
      {
        num_som[0]=les_Polys(num_elem,1);
        num_som[1]=les_Polys(num_elem,3);
        num_som[2]=les_Polys(num_elem,5);
        num_som[3]=les_Polys(num_elem,7);
      }
      break;
    case 4:
      {
        num_som[0]=les_Polys(num_elem,2);
        num_som[1]=les_Polys(num_elem,3);
        num_som[2]=les_Polys(num_elem,6);
        num_som[3]=les_Polys(num_elem,7);
      }
      break;
    case 5:
      {
        num_som[0]=les_Polys(num_elem,4);
        num_som[1]=les_Polys(num_elem,5);
        num_som[2]=les_Polys(num_elem,6);
        num_som[3]=les_Polys(num_elem,7);
      }
      break;
    default:
      {
        exit();
        num_som[0]=-1;
        num_som[1]=-1;
        num_som[2]=-1;
        num_som[3]=-1;
      }
      break;
    }
  x_[0][0]=les_coords(num_som[0],0);
  x_[0][1]=les_coords(num_som[0],1);
  x_[0][2]=les_coords(num_som[0],2);
  x_[1][0]=les_coords(num_som[1],0);
  x_[1][1]=les_coords(num_som[1],1);
  x_[1][2]=les_coords(num_som[1],2);
  x_[2][0]=les_coords(num_som[2],0);
  x_[2][1]=les_coords(num_som[2],1);
  x_[2][2]=les_coords(num_som[2],2);
  x_[3][0]=les_coords(num_som[3],0);
  x_[3][1]=les_coords(num_som[3],1);
  x_[3][2]=les_coords(num_som[3],2);
  xjnum1[0]=(x_[0][0]+x_[1][0]+x_[2][0]+x_[3][0])*0.25;
  xjnum1[1]=(x_[0][1]+x_[1][1]+x_[2][1]+x_[3][1])*0.25;
  xjnum1[2]=(x_[0][2]+x_[1][2]+x_[2][2]+x_[3][2])*0.25;
  switch (num2)
    {
    case 0:
      {
        num_som[0]=les_Polys(num_elem,0);
        num_som[1]=les_Polys(num_elem,2);
        num_som[2]=les_Polys(num_elem,4);
        num_som[3]=les_Polys(num_elem,6);
      }
      break;
    case 1:
      {
        num_som[0]=les_Polys(num_elem,0);
        num_som[1]=les_Polys(num_elem,1);
        num_som[2]=les_Polys(num_elem,4);
        num_som[3]=les_Polys(num_elem,5);
      }
      break;
    case 2:
      {
        num_som[0]=les_Polys(num_elem,0);
        num_som[1]=les_Polys(num_elem,1);
        num_som[2]=les_Polys(num_elem,2);
        num_som[3]=les_Polys(num_elem,3);
      }
      break;
    case 3:
      {
        num_som[0]=les_Polys(num_elem,1);
        num_som[1]=les_Polys(num_elem,3);
        num_som[2]=les_Polys(num_elem,5);
        num_som[3]=les_Polys(num_elem,7);
      }
      break;
    case 4:
      {
        num_som[0]=les_Polys(num_elem,2);
        num_som[1]=les_Polys(num_elem,3);
        num_som[2]=les_Polys(num_elem,6);
        num_som[3]=les_Polys(num_elem,7);
      }
      break;
    case 5:
      {
        num_som[0]=les_Polys(num_elem,4);
        num_som[1]=les_Polys(num_elem,5);
        num_som[2]=les_Polys(num_elem,6);
        num_som[3]=les_Polys(num_elem,7);
      }
      break;
    }
  x_[0][0]=les_coords(num_som[0],0);
  x_[0][1]=les_coords(num_som[0],1);
  x_[0][2]=les_coords(num_som[0],2);
  x_[1][0]=les_coords(num_som[1],0);
  x_[1][1]=les_coords(num_som[1],1);
  x_[1][2]=les_coords(num_som[1],2);
  x_[2][0]=les_coords(num_som[2],0);
  x_[2][1]=les_coords(num_som[2],1);
  x_[2][2]=les_coords(num_som[2],2);
  x_[3][0]=les_coords(num_som[3],0);
  x_[3][1]=les_coords(num_som[3],1);
  x_[3][2]=les_coords(num_som[3],2);
  xjnum2[0]=(x_[0][0]+x_[1][0]+x_[2][0]+x_[3][0])*0.25;
  xjnum2[1]=(x_[0][1]+x_[1][1]+x_[2][1]+x_[3][1])*0.25;
  xjnum2[2]=(x_[0][2]+x_[1][2]+x_[2][2]+x_[3][2])*0.25;
  xj0[0]= xjnum1[0]-xjnum2[0];
  xj0[1]= xjnum1[1]-xjnum2[1];
  xj0[2]= xjnum1[2]-xjnum2[2];
  psc=xj0[0]*pv[0] + xj0[1]*pv[1] + xj0[2]*pv[2] ;
  if (psc < 0)
    {
      normales_facettes_Cl(num_elem,fa7,0) = -pv[0]/2;
      normales_facettes_Cl(num_elem,fa7,1) = -pv[1]/2;
      normales_facettes_Cl(num_elem,fa7,2) = -pv[2]/2;
    }
  else
    {
      normales_facettes_Cl(num_elem,fa7,0) = pv[0]/2;
      normales_facettes_Cl(num_elem,fa7,1) = pv[1]/2;
      normales_facettes_Cl(num_elem,fa7,2) = pv[2]/2;
    }
}
References Domaine::coord_sommets(), Zone::domaine(), Process::exit(), Elem_VEF_base::KEL_, Zone::les_elems(), and prodvect().
duplique()
int Hexa_VEF::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Hexa_VEF.cpp.
get_info()
const Type_info * Hexa_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_VEF_base.
Definition at line 19 of file Hexa_VEF.cpp.
info()
const Type_info * Hexa_VEF::info () static
Definition at line 19 of file Hexa_VEF.cpp.
modif_normales_facettes_Cl()
void Hexa_VEF::modif_normales_facettes_Cl (DoubleTab & normales_facettes_Cl, int fa7, int num_elem, int idirichlet, int n1, int , int) const override virtual
modifie normales_facettes_Cl quand idirichlet=3
idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=3, n1 est le numero du sommet confondu avec G
Implements Elem_VEF_base.
Definition at line 697 of file Hexa_VEF.cpp.
{
  switch (idirichlet)
    {
    case 0:
      break;
    case 1:
      break;
    case 2:
      break;
    case 3:
      {
// normales_facettes_Cl(num_elem,n1,0) = 0;
// normales_facettes_Cl(num_elem,n1,1) = 0;
        break;
      }
    }
}
modif_volumes_entrelaces()
void Hexa_VEF::modif_volumes_entrelaces (int j, int elem, const Zone_VEF & la_zone_VEF, DoubleVect & volumes_entrelaces_Cl, int type_cl) const override virtual
modifie les volumes entrelaces pour la face j d'un elem
non standard
Implements Elem_VEF_base.
Definition at line 646 of file Hexa_VEF.cpp.
{
  Cerr << "Hexa_VEF::modif_volumes_entrelaces() ne fait rien pour le moment " << finl;
}
References Cerr, and finl.
modif_volumes_entrelaces_faces_joints()
void Hexa_VEF::modif_volumes_entrelaces_faces_joints (int j, int elem, const Zone_VEF & la_zone_VEF, DoubleVect & volumes_entrelaces_Cl, int type_cl) const override virtual
modifie les volumes entrelaces pour la face joint j d'un elem
non standard
Implements Elem_VEF_base.
Definition at line 658 of file Hexa_VEF.cpp.
{
}
nb_facette()
int Hexa_VEF::nb_facette () const inline override virtual
Implements Elem_VEF_base.
Definition at line 29 of file Hexa_VEF.h.
  {
    return 12;
  };
Referenced by creer_facette_normales().
normale()
void Hexa_VEF::normale (int num_Face, DoubleTab & Face_normales, const IntTab & Face_sommets, const IntTab & Face_voisins, const IntTab & elem_faces, const Zone & zone_geom) const override virtual
remplit le tableau face_normales dans la Zone_VEF
Implements Elem_VEF_base.
Definition at line 55 of file Hexa_VEF.cpp.
{
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
  double x1,y1,z1,x2,y2,z2;
  double nx,ny,nz;
  int f0,no4;
  int elem1;
// on a les 4 sommets de la face
  int n0 = Face_sommets(num_Face,0);
  int n1 = Face_sommets(num_Face,1);
  int n2 = Face_sommets(num_Face,2);
  int n3 = Face_sommets(num_Face,3);
// on va decouper la face en deux triangles
// on initialise Face_normales(num_face,dimension) a 0
// car on va sommer les deux face_normale des triangles
  Face_normales(num_Face,0) =  0;
  Face_normales(num_Face,1) =  0;
  Face_normales(num_Face,2) =  0;
// on prend les sommet S1,S2 et S4
  x1 = les_coords(n0,0) - les_coords(n1,0);
  y1 = les_coords(n0,1) - les_coords(n1,1);
  z1 = les_coords(n0,2) - les_coords(n1,2);
  x2 = les_coords(n3,0) - les_coords(n1,0);
  y2 = les_coords(n3,1) - les_coords(n1,1);
  z2 = les_coords(n3,2) - les_coords(n1,2);
  nx = (y1*z2 - y2*z1)/2;
  ny = (-x1*z2 + x2*z1)/2;
  nz = (x1*y2 - x2*y1)/2;
// Orientation de la normale de elem1 vers elem2
// pour cela recherche du sommet de elem1 qui n'est pas sur la Face
  elem1=Face_voisins(num_Face,0);
  if ( (f0 = elem_faces(elem1,0)) == num_Face )
    f0 = elem_faces(elem1,1);
  if ( (no4 = Face_sommets(f0,0)) != n0    &&   no4 != n1
       &&   no4 != n2 &&   no4 != n3)
    ;
  else if ( (no4 = Face_sommets(f0,1)) != n0 && no4 != n1
            && no4 != n2 &&   no4 != n3)
    ;
  else if ( (no4 = Face_sommets(f0,2)) != n0 && no4 != n1
            && no4 != n2 &&   no4 != n3)
    ;
  else
    no4 = Face_sommets(f0,3);
  x1 = les_coords(no4,0) - les_coords(n0,0);
  y1 = les_coords(no4,1) - les_coords(n0,1);
  z1 = les_coords(no4,2) - les_coords(n0,2);
  if ( (nx*x1+ny*y1+nz*z1) > 0 )
    {
      Face_normales(num_Face,0) +=  -nx;
      Face_normales(num_Face,1) +=  -ny;
      Face_normales(num_Face,2) +=  -nz;
    }
  else
    {
      Face_normales(num_Face,0) += nx;
      Face_normales(num_Face,1) += ny;
      Face_normales(num_Face,2) += nz;
    }
// on prend les sommet S1,S4 et S3
  x1 = les_coords(n0,0) - les_coords(n2,0);
  y1 = les_coords(n0,1) - les_coords(n2,1);
  z1 = les_coords(n0,2) - les_coords(n2,2);
  x2 = les_coords(n3,0) - les_coords(n2,0);
  y2 = les_coords(n3,1) - les_coords(n2,1);
  z2 = les_coords(n3,2) - les_coords(n2,2);
  nx = (y1*z2 - y2*z1)/2;
  ny = (-x1*z2 + x2*z1)/2;
  nz = (x1*y2 - x2*y1)/2;
// Orientation de la normale de elem1 vers elem2
// pour cela recherche du sommet de elem1 qui n'est pas sur la Face
  elem1=Face_voisins(num_Face,0);
  if ( (f0 = elem_faces(elem1,0)) == num_Face )
    f0 = elem_faces(elem1,1);
  if ( (no4 = Face_sommets(f0,0)) != n0    &&   no4 != n1
       &&   no4 != n2 &&   no4 != n3)
    ;
  else if ( (no4 = Face_sommets(f0,1)) != n0 && no4 != n1
            && no4 != n2 &&   no4 != n3)
    ;
  else if ( (no4 = Face_sommets(f0,2)) != n0 && no4 != n1
            && no4 != n2 &&   no4 != n3)
    ;
  else
    no4 = Face_sommets(f0,3);
  x1 = les_coords(no4,0) - les_coords(n0,0);
  y1 = les_coords(no4,1) - les_coords(n0,1);
  z1 = les_coords(no4,2) - les_coords(n0,2);
  if ( (nx*x1+ny*y1+nz*z1) > 0 )
    {
      Face_normales(num_Face,0) +=  -nx;
      Face_normales(num_Face,1) +=  -ny;
      Face_normales(num_Face,2) +=  -nz;
    }
  else
    {
      Face_normales(num_Face,0) += nx;
      Face_normales(num_Face,1) += ny;
      Face_normales(num_Face,2) += nz;
    }
}
References Domaine::coord_sommets(), and Zone::domaine().
printOn()
Sortie & Hexa_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Elem_VEF_base.
Definition at line 23 of file Hexa_VEF.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Hexa_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Elem_VEF_base.
Definition at line 28 of file Hexa_VEF.cpp.
{
  return s ;
}
self_cast() [1/2]
const Hexa_VEF & Hexa_VEF::self_cast (const Objet_U & r) static
Definition at line 19 of file Hexa_VEF.cpp.
self_cast() [2/2]
Hexa_VEF & Hexa_VEF::self_cast (Objet_U & r) static
Definition at line 19 of file Hexa_VEF.cpp.
taille_memoire()
unsigned Hexa_VEF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Hexa_VEF.cpp.
traiter_normales_facettes_Cl()
void Hexa_VEF::traiter_normales_facettes_Cl (DoubleTab & , int , int , const DoubleTab & , const DoubleVect & , int , int , int , int , int) const
Member Data Documentation
info_obj
const Type_info Hexa_VEF::info_obj static
Definition at line 25 of file Hexa_VEF.h.
The documentation for this class was generated from the following files:
src/VEF/Zones/Hexa_VEF.h
src/VEF/Zones/Hexa_VEF.cpp