TRUST: ptrParam Class Reference
ptrParam Class Reference
class Objet_a_lire : contient un nom, et une reference vers un int,double,flag,un Objet_U a lire,ou un Objet_u sur lequel il faut appeler lire_motcle_non_standard
#include <ptrParam.h>
Public Member Functions
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
ptrParam ()
~ptrParam ()
ptrParam (const ptrParam &)
const ptrParam & operator= (const ptrParam &)
int non_nul () const
void create (const char *)
Param & valeur ()
const Param & valeur () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static ptrParam & self_cast (Objet_U &)
static const ptrParam & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
Param * param_
Detailed Description
class Objet_a_lire : contient un nom, et une reference vers un int,double,flag,un Objet_U a lire,ou un Objet_u sur lequel il faut appeler lire_motcle_non_standard
Definition at line 33 of file ptrParam.h.
Constructor & Destructor Documentation
ptrParam::ptrParam ()
Definition at line 37 of file ptrParam.cpp.
                   :param_(0)
{
}
ptrParam::~ptrParam ()
Definition at line 40 of file ptrParam.cpp.
References param_.
{
  delete param_;
  param_=0;
}
ptrParam::ptrParam (const ptrParam & p)
Definition at line 69 of file ptrParam.cpp.
References Process::abort(), non_nul(), and param_.
                                   :Objet_U(p)
{
  if (p.non_nul())
    abort();
  param_=0;
}
Member Function Documentation
void ptrParam::create (const char * name)
Definition at line 46 of file ptrParam.cpp.
References param_.
Referenced by Objet_a_lire::add_dict(), and Objet_a_lire::create_param().
{
  param_=new Param(name);
}
Objet_U * ptrParam::cree_instance () [static]
Definition at line 25 of file ptrParam.cpp.
int ptrParam::duplique () const [virtual]
Implements Objet_U.
Definition at line 25 of file ptrParam.cpp.
const Type_info * ptrParam::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 25 of file ptrParam.cpp.
const Type_info * ptrParam::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 25 of file ptrParam.cpp.
int ptrParam::non_nul () const [inline]
Definition at line 41 of file ptrParam.h.
References param_.
Referenced by ptrParam(), and Objet_a_lire::read().
  {
    return (param_!=0);
  } ;
const ptrParam & ptrParam::operator= (const ptrParam & p)
Definition at line 75 of file ptrParam.cpp.
References Process::abort().
{
  abort();
  return (*this);
}
Sortie & ptrParam::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 32 of file ptrParam.cpp.
{
  return Objet_U::printOn(os);
}
Entree & ptrParam::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 28 of file ptrParam.cpp.
{
  return Objet_U::readOn(is);
}
const ptrParam & ptrParam::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Definition at line 25 of file ptrParam.cpp.
ptrParam & ptrParam::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Definition at line 25 of file ptrParam.cpp.
unsigned ptrParam::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file ptrParam.cpp.
const Param & ptrParam::valeur () const
Definition at line 59 of file ptrParam.cpp.
References Cerr, Process::exit(), finl, and param_.
{
  if (param_==0)
    {
      Cerr<<"param not defined" <<finl;
      exit();
    }
  return *param_;
}
Param & ptrParam::valeur ()
Definition at line 50 of file ptrParam.cpp.
References Cerr, Process::exit(), finl, and param_.
Referenced by Objet_a_lire::create_param(), Param::dictionnaire_param(), and Objet_a_lire::read().
{
  if (param_==0)
    {
      Cerr<<"param not defined" <<finl;
      exit();
    }
  return *param_;
}
Member Data Documentation
const Type_info ptrParam::info_obj [static]
Reimplemented from Objet_U.
Definition at line 35 of file ptrParam.h.
Param* ptrParam::param_ [protected]
Definition at line 49 of file ptrParam.h.
Referenced by create(), non_nul(), ptrParam(), valeur(), and ~ptrParam().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/ptrParam.h
src/Kernel/Utilitaires/ptrParam.cpp