TRUST: Evaluateur_Source_CoviMAC_Face Class Reference
Evaluateur_Source_CoviMAC_Face Class Reference
#include <Evaluateur_Source_CoviMAC_Face.h>
Public Member Functions
Evaluateur_Source_CoviMAC_Face ()
Evaluateur_Source_CoviMAC_Face (const Evaluateur_Source_CoviMAC_Face &)
void completer ()
virtual double calculer_terme_source_bord (int) const =0
virtual void calculer_terme_source_bord (int, DoubleVect &) const =0
Protected Attributes
IntVect orientation
orientations des faces
DoubleVect volumes_entrelaces
DoubleVect porosite_surf
porosites surfaciques
Detailed Description
Definition at line 37 of file Evaluateur_Source_CoviMAC_Face.h.
Constructor & Destructor Documentation
Evaluateur_Source_CoviMAC_Face::Evaluateur_Source_CoviMAC_Face () [inline]
Definition at line 56 of file Evaluateur_Source_CoviMAC_Face.h.
{}
Evaluateur_Source_CoviMAC_Face::Evaluateur_Source_CoviMAC_Face (const Evaluateur_Source_CoviMAC_Face & eval)
Definition at line 30 of file Evaluateur_Source_CoviMAC_Face.cpp.
References orientation, porosite_surf, DoubleVect::ref(), IntVect::ref(), and volumes_entrelaces.
  : Evaluateur_Source_CoviMAC(eval)
{
  orientation.ref(eval.orientation);
  volumes_entrelaces.ref(eval.volumes_entrelaces);
  porosite_surf.ref(eval.porosite_surf);
}
Member Function Documentation
virtual double Evaluateur_Source_CoviMAC_Face::calculer_terme_source_bord (int) const [pure virtual]
virtual void Evaluateur_Source_CoviMAC_Face::calculer_terme_source_bord (int , DoubleVect &) const [pure virtual]
void Evaluateur_Source_CoviMAC_Face::completer () [virtual]
Implements Evaluateur_Source_CoviMAC.
Definition at line 38 of file Evaluateur_Source_CoviMAC_Face.cpp.
References Evaluateur_Source_CoviMAC::la_zone, orientation, porosite_surf, DoubleVect::ref(), IntVect::ref(), and volumes_entrelaces.
{
  orientation.ref(la_zone->orientation());
  volumes_entrelaces.ref(la_zone->volumes_entrelaces());
  porosite_surf.ref(la_zone->porosite_face());
}
Member Data Documentation
IntVect Evaluateur_Source_CoviMAC_Face::orientation [protected]
orientations des faces
Definition at line 50 of file Evaluateur_Source_CoviMAC_Face.h.
Referenced by completer(), and Evaluateur_Source_CoviMAC_Face().
DoubleVect Evaluateur_Source_CoviMAC_Face::porosite_surf [protected]
porosites surfaciques
Definition at line 52 of file Evaluateur_Source_CoviMAC_Face.h.
Referenced by completer(), and Evaluateur_Source_CoviMAC_Face().
DoubleVect Evaluateur_Source_CoviMAC_Face::volumes_entrelaces [protected]
Definition at line 51 of file Evaluateur_Source_CoviMAC_Face.h.
Referenced by completer(), and Evaluateur_Source_CoviMAC_Face().
The documentation for this class was generated from the following files:
src/CoviMAC/Sources/Evaluateur_Source_CoviMAC_Face.h
src/CoviMAC/Sources/Evaluateur_Source_CoviMAC_Face.cpp