TRUST: EDO_Pression_th_VEF_Gaz_Reel Class Reference
EDO_Pression_th_VEF_Gaz_Reel Class Reference
classe EDO_Pression_th_VEF_Gaz_Reel
Cette classe represente l'EDO sur la pression associee au schema de
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VEF et pour les gaz reels.
#include <EDO_Pression_th_VEF_Gaz_Reel.h>
Public Member Functions
EDO_Pression_th_VEF_Gaz_Reel ()
~EDO_Pression_th_VEF_Gaz_Reel ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
double resoudre (double) override
Resoud l'EDO.
Public Member Functions inherited from EDO_Pression_th_VEF
~EDO_Pression_th_VEF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
EDO_Pression_th_VEF ()
const Fluide_Quasi_Compressible & le_fluide () const
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Associe les zones a l'EDO.
void completer () override
Complete l'EDO : calcule rho sur les faces.
void calculer_grad (const DoubleTab &, DoubleTab &)
double masse_totale (double P, const DoubleTab &T) override
void mettre_a_jour_CL (double P) override
double getM0 ()
Public Member Functions inherited from EDO_Pression_th_base
EDO_Pression_th_base ()
~EDO_Pression_th_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_fluide (const Fluide_Quasi_Compressible &)
Associe le fluide a l'EDO.
virtual void completer ()=0
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void mettre_a_jour_CL (double)=0
virtual double masse_totale (double P, const DoubleTab &T)=0
virtual double resoudre (double)=0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static EDO_Pression_th_VEF_Gaz_Reel & self_cast (Objet_U &)
static const EDO_Pression_th_VEF_Gaz_Reel & self_cast (const Objet_U &)
Static Public Member Functions inherited from EDO_Pression_th_VEF
static const Type_info * info ()
static EDO_Pression_th_VEF & self_cast (Objet_U &)
static const EDO_Pression_th_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from EDO_Pression_th_base
static const Type_info * info ()
static EDO_Pression_th_base & self_cast (Objet_U &)
static const EDO_Pression_th_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from EDO_Pression_th_VEF
static const Type_info info_obj
Static Public Attributes inherited from EDO_Pression_th_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from EDO_Pression_th_VEF
Ref_Zone_VEF la_zone
Ref_Zone_Cl_dis la_zone_Cl
double M0
la masse totale initiale
Protected Attributes inherited from EDO_Pression_th_base
Ref_Fluide_Quasi_Compressible le_fluide_
Detailed Description
classe EDO_Pression_th_VEF_Gaz_Reel
Cette classe represente l'EDO sur la pression associee au schema de
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VEF et pour les gaz reels.
Definition at line 32 of file EDO_Pression_th_VEF_Gaz_Reel.h.
Constructor & Destructor Documentation
EDO_Pression_th_VEF_Gaz_Reel()
EDO_Pression_th_VEF_Gaz_Reel::EDO_Pression_th_VEF_Gaz_Reel ()
Definition at line 26 of file EDO_Pression_th_VEF_Gaz_Reel.cpp.
~EDO_Pression_th_VEF_Gaz_Reel()
EDO_Pression_th_VEF_Gaz_Reel::~EDO_Pression_th_VEF_Gaz_Reel ()
Definition at line 26 of file EDO_Pression_th_VEF_Gaz_Reel.cpp.
Member Function Documentation
cree_instance()
Objet_U * EDO_Pression_th_VEF_Gaz_Reel::cree_instance () static
Definition at line 26 of file EDO_Pression_th_VEF_Gaz_Reel.cpp.
duplique()
int EDO_Pression_th_VEF_Gaz_Reel::duplique () const override virtual
Implements Objet_U.
Definition at line 26 of file EDO_Pression_th_VEF_Gaz_Reel.cpp.
get_info()
const Type_info * EDO_Pression_th_VEF_Gaz_Reel::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from EDO_Pression_th_VEF.
Definition at line 26 of file EDO_Pression_th_VEF_Gaz_Reel.cpp.
info()
const Type_info * EDO_Pression_th_VEF_Gaz_Reel::info () static
Definition at line 26 of file EDO_Pression_th_VEF_Gaz_Reel.cpp.
printOn()
Sortie & EDO_Pression_th_VEF_Gaz_Reel::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from EDO_Pression_th_VEF.
Definition at line 28 of file EDO_Pression_th_VEF_Gaz_Reel.cpp.
{
  os <<que_suis_je()<< finl;
  return os;
}
References finl, and Objet_U::que_suis_je().
readOn()
Entree & EDO_Pression_th_VEF_Gaz_Reel::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from EDO_Pression_th_VEF.
Definition at line 34 of file EDO_Pression_th_VEF_Gaz_Reel.cpp.
{
  return is;
}
resoudre()
double EDO_Pression_th_VEF_Gaz_Reel::resoudre (double Pth_n) override virtual
Resoud l'EDO.
Returns
double
Signification: La nouvelle valeur de la pression
Contraintes:
Implements EDO_Pression_th_base.
Definition at line 53 of file EDO_Pression_th_VEF_Gaz_Reel.cpp.
{
  int n_bord ;
  for (n_bord=0; n_bord<la_zone->nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = la_zone_Cl->les_conditions_limites(n_bord);
      if (sub_type(Neumann_sortie_libre, la_cl.valeur()))
        return Pth_n;
    }
  double Pth;
  const DoubleTab& tab_vit = ref_cast(Navier_Stokes_std,le_fluide_->vitesse()->equation()).vitesse()->valeurs();
  const DoubleTab& tab_hnp1 = le_fluide_->inco_chaleur().valeurs();       //actuel
  const DoubleTab& tab_hn = le_fluide_->inco_chaleur().passe();        //passe
  const DoubleTab& tab_rho = le_fluide_->masse_volumique().valeurs();    //actuel
  const Loi_Etat& loi_ = le_fluide_->loi_etat();
// const DoubleVect& tab_rhon = loi_->rho_n();                       //passe
  int elem, nb_elem=la_zone->nb_elem();
  double V = 0; //mesure du domaine
  double Fn = 0; //integrale 1 a l'etape n
  double Fnp1 = 0; //integrale 1 a l'etape n+1
  double S = 0; //second membre
  double dt = le_fluide_->vitesse()->equation().schema_temps().pas_de_temps();
  double v,al,bn, bnp1, hn,hnp1, divu;
  int i, face,nb_faces=la_zone->nb_faces();
// calcul T* aux elements
  DoubleTab HstarP0(nb_elem);
  DoubleTab gradh(nb_faces,dimension);
  DoubleTab u_gradh(nb_faces);
  int nfe = la_zone->zone().nb_faces_elem();
  const IntTab& elem_faces = la_zone->elem_faces();
  for (elem=0 ; elem<nb_elem ; elem++)
    {
      HstarP0(elem) = 0;
      for (face=0 ; face<nfe ; face++)
        {
          hn = tab_hn(elem_faces(elem,face));
          hnp1 = tab_hnp1(elem_faces(elem,face));
          HstarP0(elem) += .5*(hn+hnp1);
        }
      HstarP0(elem) /= nfe;
    }
// calcul gradT*
  calculer_grad(HstarP0,gradh);
// calcul u.gradT*
  for (face=0 ; face<nb_faces ; face++)
    {
      u_gradh(face)=0;
      for (i=0 ; i<dimension ; i++)
        {
          u_gradh(face) += gradh(face,i) * tab_vit(face,i);
        }
    }
// calcul divU en P0 et P1
  DoubleTrav divUP0(nb_elem);
  ref_cast(Navier_Stokes_std,le_fluide_->vitesse()->equation()).operateur_divergence().calculer(tab_vit,divUP0);
  DoubleTrav divU(nb_faces);
  int e0,e1;
  for (face=0 ; face<nb_faces ; face++)
    {
      e0 = la_zone->face_voisins(face,0);
      e1 = la_zone->face_voisins(face,1);
      if (e0!=-1 && e1!=-1)
        {
          divU(face) = .5*(divUP0(e0)+divUP0(e1));
        }
      else if (e0!=-1)
        {
          divU(face) = divUP0(e0);
        }
      else
        {
          divU(face) = divUP0(e1);
        }
    }
  for (face=0 ; face<nb_faces ; face++)
    {
      v = la_zone->volumes_entrelaces(face);
      V += v;
      hn   = tab_hn(face);
      hnp1 = tab_hnp1(face);
      al = loi_->Drho_DT(Pth_n,hn) / loi_->Drho_DP(Pth_n,hn);
      bn = tab_rho(face)/ loi_->Drho_DP(Pth_n,hn);
      bnp1 = loi_->calculer_masse_volumique(Pth_n,hnp1) / loi_->Drho_DP(Pth_n,hnp1);
      divu = divU(face);
      S -= v *al *((hnp1-hn)/dt + u_gradh(face));
      Fn += v * bn * divu;
      Fnp1 += v * bnp1 * divu;
    }
  Pth = Pth_n + dt/V *(S-Fn);
// Cerr<<"Volume="<<V<<finl;
// Cerr<<"Fn="<<Fn<<finl;
// Cerr<<"S="<<S<<finl;
// Cerr<<"Pression thermo recalculee (expl) = "<<Pth<<finl;
  Pth = Pth_n + dt/V *(S-.5*(Fn+Fnp1));
// Cerr<<"Fnp1="<<Fnp1<<finl;
// Cerr<<"Pression thermo recalculee (impl) = "<<Pth<<finl;
  double tmp=0,r;
  int k=0;
  while (std::fabs(tmp-Pth)/Pth>1e-9 && k++<20)
    {
      tmp = Pth;
      Fnp1 = 0;
      for (face=0 ; face<nb_faces ; face++)
        {
          v = la_zone->volumes_entrelaces(face);
          hnp1 = tab_hnp1(face);
          r = loi_->calculer_masse_volumique(Pth,hnp1);
          bnp1 = r / loi_->Drho_DP(Pth,hnp1);
          Fnp1 += v * bnp1 * divU(face);
        }
      Pth = Pth_n + dt/V *(S-.5*(Fn+Fnp1));
// Cerr<<"Fnp1="<<Fnp1<<finl;
      Cerr<<"Pression thermo recalculee (impl"<<k<<") = "<<Pth<<finl;
    }
  return Pth;
}
References EDO_Pression_th_VEF::calculer_grad(), Cerr, Objet_U::dimension, Zone_VF::elem_faces(), Zone_VF::face_voisins(), finl, Fluide_Dilatable_base::inco_chaleur(), EDO_Pression_th_VEF::la_zone, EDO_Pression_th_VEF::la_zone_Cl, EDO_Pression_th_base::le_fluide_, Zone_Cl_dis::les_conditions_limites(), Fluide_Dilatable_base::loi_etat(), Milieu_base::masse_volumique(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Zone_dis_base::nb_front_Cl(), Champ_Inc::passe(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Champ::valeurs(), Champ_Inc::valeurs(), Fluide_Dilatable_base::vitesse(), Zone_VF::volumes_entrelaces(), and Zone_dis_base::zone().
self_cast() [1/2]
const EDO_Pression_th_VEF_Gaz_Reel & EDO_Pression_th_VEF_Gaz_Reel::self_cast (const Objet_U & r) static
Definition at line 26 of file EDO_Pression_th_VEF_Gaz_Reel.cpp.
self_cast() [2/2]
EDO_Pression_th_VEF_Gaz_Reel & EDO_Pression_th_VEF_Gaz_Reel::self_cast (Objet_U & r) static
Definition at line 26 of file EDO_Pression_th_VEF_Gaz_Reel.cpp.
taille_memoire()
unsigned EDO_Pression_th_VEF_Gaz_Reel::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 26 of file EDO_Pression_th_VEF_Gaz_Reel.cpp.
Member Data Documentation
info_obj
const Type_info EDO_Pression_th_VEF_Gaz_Reel::info_obj static
Definition at line 34 of file EDO_Pression_th_VEF_Gaz_Reel.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VEF/EDO_Pression_th_VEF_Gaz_Reel.h
src/ThHyd/Dilatable/Quasi_Compressible/VEF/EDO_Pression_th_VEF_Gaz_Reel.cpp