TRUST: EChaine Class Reference
EChaine Class Reference
Une entree dont la source est une chaine de caracteres.
Le constructeur cree sa propre copie de la chaine, de sorte
que la chaine d'origine peut etre modifiee ensuite sans modifier
la EChaine.
#include <EChaine.h>
Public Member Functions
EChaine ()
EChaine (const char *str)
~EChaine () override
void init (const char *str)
Public Member Functions inherited from Entree
Entree ()
Entree (istream &is)
Entree (const Entree &is)
Entree & operator= (istream &is)
Entree & operator= (Entree &is)
virtual istream & get_istream ()
virtual const istream & get_istream () const
void set_istream (istream *is)
void set_different_int_size (bool is_different_int_size)
Entree & operator>> (Entree &(*f)(Entree &))
Entree & operator>> (istream &(*f)(istream &))
Entree & operator>> (ios &(*f)(ios &))
virtual Entree & operator>> (int &ob)
virtual Entree & operator>> (long &ob)
virtual Entree & operator>> (float &ob)
virtual Entree & operator>> (double &ob)
virtual int get (int *ob, int n)
virtual int get (long *ob, int n)
virtual int get (float *ob, int n)
virtual int get (double *ob, int n)
virtual int get (char *buf, int bufsize)
Lecture d'une chaine dans ostream_
bufsize est la taille du buffer alloue pour ob (y compris
le caractere 0 final).
La chaine contient toujours un 0 meme en cas d'echec.
La methode renvoie 1 si la lecture est bonne, 0 sinon.
Si le buffer est trop petit, pour l'instant on fait exit() mais
par la suite on pourra tester: si strlen(ob)==bufsize-1, alors
refaire lire() jusqu'a arriver au bout. Si le lire() suivant
renvoie une chaine de longueur nulle, cela signifie que la taille de la
chaine etait exactement bufsize-1.
Attention: le comportement est different en binaire et en ascii.
En binaire, on lit la chaine jusqu'au prochain '\0'.
En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
virtual int eof ()
virtual int fail ()
virtual int good ()
virtual ~Entree ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand.
int is_bin () const
virtual void set_check_types (int flag)
indique si le stream doit verifier les types des objets lus<br>(ints et nombres flottants). Exemple : l'entree contient 123.456 123.456
int i;
check_types(0);
is >> i; // i contient 123
check_types(1);
is >> i; // Erreur : on lit la chaine 123.456 et on essaye de la convertir en int
Voir operator>>(int &)
int check_types () const
renvoie la valeur actuelle du drapeau, voir set_check_types()
virtual void set_error_action (Error_Action)
Change le comportement en cas d'erreur de l'entree,
voir error_handle_() et get_error_action()
Error_Action get_error_action ()
renvoie error_action_ pour cette entree<br>(permet de la modifier et de restaurer ensuite la valeur anterieure)
operator istream & ()
istream & putback (char ch)
istream & ignore (int n=1, int delim=EOF)
int get_diffuse ()
virtual void set_diffuse (int diffuse)
ToDo TMA : commenter.
Protected Attributes
istringstream * istrstream_
Protected Attributes inherited from Entree
int bin_
bool is_different_int_size_
File with int32 (or int64) whereas version is int64 (or int32)
int check_types_
Error_Action error_action_
int diffuse_
By default 1, but some child classes (eg: LecFicDiffuse) could set temporary to 0 to not diffuse to other processes.
Additional Inherited Members
Public Types inherited from Entree
enum Error_Action { ERROR_EXIT , ERROR_CONTINUE , ERROR_EXCEPTION }
Protected Member Functions inherited from Entree
int error_handle (int fail_flag)
virtual int error_handle_ (int fail_flag)
Cette fonction est appellee par operateur>>, get, get_nom
ouvrir, fermer, lire, etc... en cas d'echec (lorsque fail() est mis)
Elle renvoie 0 s'il y a eu une erreur (passer par error_handle() qui
traite en inline le cas ou il n'y a pas d'erreur), et 1 s'il n'y a pas
d'erreur.
(par commodite de codage des methodes qui l'utilisent, on
ecrira "return error_handle(fail());"
Elle peut etre configuree pour
- renvoyer "0" en cas d'erreur et continuer l'execution du code
(cas d'un ancien code qui ne gere pas les exceptions mais teste
le drapeau fail() de temps en temps)
Dans ce cas les methodes operator>> continuent l'execution du code
meme en cas d'echec, le contenu des variables lues est indefini !
- faire Process::exit() (cas d'une portion de code dans laquelle
on ne veut pas faire de gestion d'erreur du tout et ou on suppose
que tout va toujours bien)
- lever une exception (permet une gestion rigoureuse des erreurs
et une information utilisateur optimale en fonction du contexte)
Voir aussi set_error_action()
Detailed Description
Une entree dont la source est une chaine de caracteres.
Le constructeur cree sa propre copie de la chaine, de sorte
que la chaine d'origine peut etre modifiee ensuite sans modifier
la EChaine.
Definition at line 32 of file EChaine.h.
Constructor & Destructor Documentation
EChaine() [1/2]
EChaine::EChaine ()
Definition at line 18 of file EChaine.cpp.
                 :
  Entree(), istrstream_(0)
{
  set_check_types(1);
}
References Entree::set_check_types().
EChaine() [2/2]
EChaine::EChaine (const char * str)
Definition at line 24 of file EChaine.cpp.
                                :
  Entree(),  istrstream_(0)
{
  set_check_types(1);
  init(str);
}
References init(), and Entree::set_check_types().
~EChaine()
EChaine::~EChaine () override
Definition at line 31 of file EChaine.cpp.
{ }
Member Function Documentation
init()
void EChaine::init (const char * str)
< a copy of str is taken
Definition at line 33 of file EChaine.cpp.
{
  if (istrstream_)
    delete istrstream_;
  istrstream_ = new istringstream(str);  //!< a copy of str is taken
  set_istream(istrstream_);
}
References istrstream_, and Entree::set_istream().
Referenced by EChaine(), Entree_complete::Entree_complete(), and LecFicDiffuse_JDD::ouvrir().
Member Data Documentation
istrstream_
istringstream* EChaine::istrstream_ protected
Definition at line 42 of file EChaine.h.
Referenced by init().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/EChaine.h
src/Kernel/Utilitaires/EChaine.cpp