TRUST: Op_Diff_PolyMAC_Elem Class Reference
Op_Diff_PolyMAC_Elem Class Reference
: class Op_Diff_PolyMAC_Elem
<Description of class Op_Diff_PolyMAC_Elem>
#include <Op_Diff_PolyMAC_Elem.h>
Public Member Functions
~Op_Diff_PolyMAC_Elem ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Op_Diff_PolyMAC_Elem ()
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
void init_op_ext () const
double calculer_dt_stab () const override
Calcul dt_stab.
void dimensionner_blocs_ext (int aux_only, matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs_ext (int aux_only, matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
void modifier_pour_Cl (Matrice_Morse &la_matrice, DoubleTab &secmem) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Public Member Functions inherited from Op_Diff_PolyMAC_base
Op_Diff_PolyMAC_base ()
~Op_Diff_PolyMAC_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void associer_diffusivite (const Champ_base &) override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
const Champ_base & diffusivite () const override
void mettre_a_jour (double t) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual int dimension_min_nu () const
virtual void modifier_nu (DoubleTab &) const
virtual void dimensionner_blocs_ext (int aux_only, matrices_t matrices, const tabs_t &semi_impl={}) const =0
virtual void ajouter_blocs_ext (int aux_only, matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const =0
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
const DoubleTab & nu () const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
calcule la contribution de la diffusion, la range dans resu
renvoie resu
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Diff_PolyMAC_Elem & self_cast (Objet_U &)
static const Op_Diff_PolyMAC_Elem & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_PolyMAC_base
static const Type_info * info ()
static Op_Diff_PolyMAC_base & self_cast (Objet_U &)
static const Op_Diff_PolyMAC_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_PolyMAC_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Diff_PolyMAC_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
void update_nu () const
void update_aux (double t) const
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Protected Attributes inherited from Op_Diff_PolyMAC_base
Ref_Zone_PolyMAC la_zone_poly_
Ref_Zone_Cl_PolyMAC la_zcl_poly_
Ref_Champ_base diffusivite_
double t_last_nu_ = -1e10
DoubleTab nu_
int nu_constant_ = 0
int nu_a_jour_ = 0
double t_last_aux_ = -1e10
int use_aux_
Matrice_Bloc mat_aux
DoubleTab var_aux
SolveurSys solv_aux
SFichier Flux
SFichier Flux_moment
SFichier Flux_sum
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
: class Op_Diff_PolyMAC_Elem
<Description of class Op_Diff_PolyMAC_Elem>
Definition at line 30 of file Op_Diff_PolyMAC_Elem.h.
Constructor & Destructor Documentation
~Op_Diff_PolyMAC_Elem()
Op_Diff_PolyMAC_Elem::~Op_Diff_PolyMAC_Elem ()
Definition at line 41 of file Op_Diff_PolyMAC_Elem.cpp.
Op_Diff_PolyMAC_Elem()
Op_Diff_PolyMAC_Elem::Op_Diff_PolyMAC_Elem ()
Definition at line 44 of file Op_Diff_PolyMAC_Elem.cpp.
{
  declare_support_masse_volumique(1);
}
References Support_Champ_Masse_Volumique::declare_support_masse_volumique().
Member Function Documentation
ajouter_blocs_ext()
void Op_Diff_PolyMAC_Elem::ajouter_blocs_ext (int aux_only, matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Implements Op_Diff_PolyMAC_base.
Definition at line 205 of file Op_Diff_PolyMAC_Elem.cpp.
{
  init_op_ext();
  const std::string& nom_inco = (le_champ_inco.non_nul() ? le_champ_inco.valeur() : equation().inconnue()).le_nom().getString();
  int i, j, k1, k2, e, f, fb, n, M, n_ext = op_ext.size(), semi = semi_impl.count(nom_inco), d, D = dimension;
  std::vector<Matrice_Morse *> mat(n_ext); //matrices
  std::vector<int> N, ne_tot; //composantes
  std::vector<std::reference_wrapper<const Zone_PolyMAC>> zone; //zones
  std::vector<std::reference_wrapper<const Conds_lim>> cls; //conditions aux limites
  std::vector<std::reference_wrapper<const IntTab>> fcl, e_f, f_e, f_s; //tableaux "fcl", "elem_faces", "faces_voisins"
  std::vector<std::reference_wrapper<const DoubleVect>> fs, pf, pe, ve; //surfaces
  std::vector<std::reference_wrapper<const DoubleTab>> inco, xp, xv, diffu, v_aux; //inconnues, normales aux faces, positions elems / faces / sommets
  std::deque<ConstDoubleTab_parts> v_part; //blocs de chaque inconnue
  std::vector<const Flux_parietal_base *> corr; //correlations de flux parietal (si elles existent)
  for (i = 0, M = 0; i < n_ext; M = std::max(M, N[i]), i++)
    {
      std::string nom_mat = i ? nom_inco + "/" + op_ext[i]->equation().probleme().le_nom().getString() : nom_inco;
      mat[i] = matrices.count(nom_mat) ? matrices.at(nom_mat) : NULL;
      zone.push_back(std::ref(ref_cast(Zone_PolyMAC, op_ext[i]->equation().zone_dis().valeur())));
      f_e.push_back(std::ref(zone[i].get().face_voisins())), e_f.push_back(std::ref(zone[i].get().elem_faces())), f_s.push_back(std::ref(zone[i].get().face_sommets()));
      fs.push_back(std::ref(zone[i].get().face_surfaces()));
      xp.push_back(std::ref(zone[i].get().xp())), xv.push_back(std::ref(zone[i].get().xv()));
      pe.push_back(std::ref(zone[i].get().porosite_elem())), pf.push_back(std::ref(zone[i].get().porosite_face())), ve.push_back(std::ref(zone[i].get().volumes()));
      cls.push_back(std::ref(op_ext[i]->equation().zone_Cl_dis().les_conditions_limites()));
      diffu.push_back(ref_cast(Op_Diff_PolyMAC_Elem, *op_ext[i]).nu());
      const Champ_Elem_PolyMAC& ch = ref_cast(Champ_Elem_PolyMAC, op_ext[i]->has_champ_inco() ? op_ext[i]->mon_inconnue().valeur() : op_ext[i]->equation().inconnue().valeur());
      inco.push_back(std::ref(semi_impl.count(nom_mat) ? semi_impl.at(nom_mat) : ch.valeurs())), v_part.emplace_back(inco.back());
      corr.push_back(sub_type(Energie_Multiphase, op_ext[i]->equation()) && ref_cast(Pb_Multiphase, op_ext[i]->equation().probleme()).has_correlation("flux_parietal")
                     ? &ref_cast(Flux_parietal_base, ref_cast(Pb_Multiphase, op_ext[i]->equation().probleme()).get_correlation("flux_parietal").valeur()) : NULL);
      N.push_back(inco[i].get().line_size()), ne_tot.push_back(zone[i].get().nb_elem_tot()), fcl.push_back(std::ref(ch.fcl()));
    }
  /* que faire avec les variables auxiliaires ? */
  double t = equation().schema_temps().temps_courant(), dt = equation().schema_temps().pas_de_temps(), fac, prefac;
  if (aux_only) use_aux_ = 0; /* 1) on est en train d'assembler le systeme de resolution des variables auxiliaires lui-meme */
  else if (mat[0] && !semi) t_last_aux_ = t + dt, use_aux_ = 0; /* 2) on est en implicite complet : pas besoin de mat_aux / var_aux, on aura les variables a t + dt */
  else if (t_last_aux_ < t) update_aux(t); /* 3) premier pas a ce temps en semi-implicite : on calcule les variables auxiliaires a t et on les stocke dans var_aux */
  for (i = 0; i < n_ext; i++) v_aux.push_back(use_aux_ ? ref_cast(Op_Diff_PolyMAC_Elem, *op_ext[i]).var_aux : v_part[i][1]); /* les variables auxiliaires peuvent etre soit dans inco/semi_impl (cas 1), soit dans var_aux (cas 2) */
  DoubleTrav w2, flux(N[0]), acc(N[0]);
  for (w2.set_smart_resize(1), e = 0; e < ne_tot[0]; e++)
    {
      zone[0].get().W2(&diffu[0].get(), e, w2); //interpolation : [n_ef.nu grad T]_f = w2_{ff'} (T_f' - T_e)
      for (i = 0; i < w2.dimension(0); i++) //seconds membres
        {
          for (f = e_f[0](e, i), flux = 0, j = 0; j < w2.dimension(1); j++)
            for (fb = e_f[0](e, j), n = 0; n < N[0]; n++)
              flux(n) += w2(i, j, n) * (v_aux[0](fb, n) - inco[0](e, n));
          if (!semi && fcl[0](f, 0) < 6)
            for (n = 0; n < N[0]; n++)
              secmem(!aux_only * ne_tot[0] + f, n) -= flux(n);
          if (!aux_only)
            for (n = 0; n < N[0]; n++) secmem(e, n) += flux(n);
          if (!aux_only && f < zone[0].get().premiere_face_int())
            for (n = 0; n < N[0]; n++) flux_bords_(f, n) = -flux(n); //flux aux bords
        }
      if (semi || !mat[0]) continue;
// matrice: elem-elem
      for (acc = 0, i = 0; i < w2.dimension(0); i++)
        for (j = 0; j < w2.dimension(1); j++)
          for (n = 0; n < N[0]; n++) acc(n) += w2(i, j, n);
      if (!aux_only && e < zone[0].get().nb_elem())
        for (n = 0; n < N[0]; n++) (*mat[0])(N[0] * e + n, N[0] * e + n) += acc(n);
// matrice: elem-face
      if (!aux_only)
        for (i = 0; i < w2.dimension(0); i++)
          if (fcl[0](f = e_f[0](e, i), 0) < 6)
            {
              for (acc = 0, j = 0; j < w2.dimension(1); j++)
                for (n = 0; n < N[0]; n++) acc(n) += w2(i, j, n);
              if (f < zone[0].get().nb_faces())
                for (n = 0; n < N[0]; n++) (*mat[0])(N[0] * (ne_tot[0] + f) + n, N[0] * e + n) -= acc(n);
              if (e < zone[0].get().nb_elem())
                for (n = 0; n < N[0]; n++) (*mat[0])(N[0] * e + n, N[0] * (ne_tot[0] + f) + n) -= acc(n);
            }
// matrice : face-face
      for (i = 0; i < w2.dimension(0); i++)
        if (fcl[0](f = e_f[0](e, i), 0) < 6 && f < zone[0].get().nb_faces())
          for (j = 0; j < w2.dimension(1); j++)
            if (fcl[0](fb = e_f[0](e, j), 0) < 6)
              for (n = 0; n < N[0]; n++)
                if (w2(i, j, n))
                  (*mat[0])(N[0] * (!aux_only * ne_tot[0] + f) + n, N[0] * (!aux_only * ne_tot[0] + fb) + n) += w2(i, j, n);
    }
// contributions restantes aux equations aux faces
  for (f = 0; f < zone[0].get().nb_faces(); f++)
    if (!aux_only && semi && mat[0])
      for (n = 0; n < N[0]; n++) //semi-implicite : T_f^+ = var_aux
        secmem(ne_tot[0] + f, n) += v_aux[0](f, n) - (le_champ_inco.non_nul() ? le_champ_inco->valeurs() : equation().inconnue().valeurs())(ne_tot[0] + f, n), (*mat[0])(N[0] * (ne_tot[0] + f) + n, N[0] * (ne_tot[0] + f) + n)++;
    else if (fcl[0](f, 0) == 0 || fcl[0](f, 0) == 5) continue; //face interne ou Neumann_val_ext -> rien
    else if (corr[0]) //Pb_Multiphase avec flux parietal -> on ne traite (pour le moment) que Dirichlet et Echange_contact
      {
        if (fcl[0](f, 0) == 2) abort(); //Echange_global_impose -> on ne sait pas faire (que vaut T_paroi dans l'element?)
        const Echange_contact_PolyMAC *ech = fcl[0](f, 0) == 3 ? &ref_cast(Echange_contact_PolyMAC, cls[0].get()[fcl[0](f, 1)].valeur()) : NULL;
        int o_p = ech ? ech->o_idx : -1, o_f = ech ? ech->f_dist(fcl[0](f, 2)) : -1;
        const Pb_Multiphase& pbm = ref_cast(Pb_Multiphase, equation().probleme());
        const DoubleTab& alpha = pbm.eq_masse.inconnue().passe(), &dh = zone[0].get().diametre_hydraulique_elem(), &press = pbm.eq_qdm.pression().passe(),
                         &vit = pbm.eq_qdm.inconnue().passe(), &lambda = pbm.milieu().conductivite().passe(), &mu = ref_cast(Fluide_base, pbm.milieu()).viscosite_dynamique().passe(),
                          &rho = pbm.milieu().masse_volumique().passe(), &Cp = pbm.milieu().capacite_calorifique().passe();
        DoubleTrav qpk(N[0]), dTf_qpk(N[0], N[0]), dTp_qpk(N[0]), qpi(N[0], N[0]), dTf_qpi(N[0], N[0], N[0]), dTp_qpi(N[0], N[0]), v(N[0], D), nv(N[0]);
        for (e = f_e[0](f, 0), i = 0; i < e_f[0].get().dimension(1) && (fb = e_f[0](e, i)) >= 0; i++)
          for (prefac = fs[0](fb) * pf[0](fb) * (e == f_e[0](fb, 0) ? 1 : -1) / (pe[0](e) * ve[0](e)), n = 0; n < N[0]; n++)
            for (fac = prefac * vit(fb, n), d = 0; d < D; d++)
              v(n, d) += fac * (xv[0](fb, d) - xp[0](e, d));
        for (n = 0; n < N[0]; n++) nv(n) = sqrt(zone[0].get().dot(&v(n, 0), &v(n, 0)));
// Tparoi : estimation initiale + Newton si on ne la connait pas
        double h_imp = fcl[0](f, 0) == 1 ? ref_cast(Echange_impose_base, cls[0].get()[fcl[0](f, 1)].valeur()).h_imp(fcl[0](f, 2), 0) : 0,
               T_ext = fcl[0](f, 0) == 1 ? ref_cast(Echange_impose_base, cls[0].get()[fcl[0](f, 1)].valeur()).T_ext(fcl[0](f, 2), 0) : 0,
               Tp = ech ? v_aux[o_p](o_f, 0) : fcl[0](f, 0) == 5 ? 0 : fcl[0](f, 0) == 6 ? ref_cast(Dirichlet, cls[0].get()[fcl[0](f, 1)].valeur()).val_imp(fcl[0](f, 2), 0)
                    :  fcl[0](f, 0) == 1 ? T_ext : v_aux[0](f, 0), dTp, FT, dFTp;
// appel : on n'est implicite qu'en les temperatures
        for (int it = 0; it < 10 && (!it || std::abs(dTp) > 1e-5); Tp += dTp, it++)
          {
            corr[0]->qp(N[0], f, dh(e), dh(e), &alpha(e, 0), &v_aux[0](f, 0), press(e), nv.addr(), Tp, &lambda(e, 0), &mu(e, 0), &rho(e, 0), &Cp(e, 0),
                        &qpk, NULL, NULL, NULL, &dTf_qpk, &dTp_qpk, &qpi, NULL, NULL, NULL, &dTf_qpi, &dTp_qpi, NULL, j);
            for (FT = 0, dFTp = 0; n < N[0]; n++) FT += qpk(n), dFTp += dTp_qpk(n);
            dTp = fcl[0](f, 0) == 5 ? (ref_cast(Neumann, cls[0].get()[fcl[0](f, 1)].valeur()).flux_impose(fcl[0](f, 2), 0) - FT) / dFTp :
                  fcl[0](f, 0) == 1 ? (h_imp * (T_ext - Tp) - FT) / (dFTp + h_imp) : 0;
          }
        for (n = 0; n < N[0]; n++) secmem(!aux_only * ne_tot[0] + f, n) += fs[0](f) * qpk(n);//second membre
        if (mat[0])
          for (k1 = 0; k1 < N[0]; k1++)
            for (k2 = 0; k2 < N[0]; k2++) //derivees en Tfluide
              (*mat[0])(N[0] * (!aux_only * ne_tot[0] + f) + k1, N[0] * (!aux_only * ne_tot[0] + f) + k2) -= fs[0](f) * dTf_qpk(k1, k2);
        if (ech && mat[o_p])
          for (n = 0; n < N[0]; n++) /* derivees en Tparoi (si Echange_contact) */
            (*mat[o_p])(N[0] * (!aux_only * ne_tot[0] + f) + n, !aux_only * ne_tot[o_p] + o_f) -= fs[0](f) * dTp_qpk(n);
      }
    else if (fcl[0](f, 0) > 5)
      for (n = 0; n < N[0]; n++) //Dirichlet : T_f^+ = T_b
        {
          secmem(!aux_only * ne_tot[0] + f, n) += (fcl[0](f, 0) == 6 ? ref_cast(Dirichlet, cls[0].get()[fcl[0](f, 1)].valeur()).val_imp(fcl[0](f, 2), n) : 0) - v_aux[0](f, n);
          if (mat[0]) (*mat[0])(N[0] * (!aux_only * ne_tot[0] + f) + n, N[0] * (!aux_only * ne_tot[0] + f) + n)++;
        }
    else if (fcl[0](f, 0) == 3) //Echange_contact
      {
        const Echange_contact_PolyMAC& ech = ref_cast(Echange_contact_PolyMAC, cls[0].get()[fcl[0](f, 1)].valeur());
        int o_p = ech.o_idx, o_f = ech.f_dist(fcl[0](f, 2)), o_e = f_e[o_p](o_f, 0); //autre pb/face/elem
        if (corr[o_p] || N[o_p] != N[0]) /* correlation de l'autre cote */
          {
            const Pb_Multiphase& pbm = ref_cast(Pb_Multiphase, op_ext[o_p]->equation().probleme());
            const DoubleTab& alpha = pbm.eq_masse.inconnue().passe(), &dh = zone[o_p].get().diametre_hydraulique_elem(), &press = pbm.eq_qdm.pression().passe(),
                             &vit = pbm.eq_qdm.inconnue().passe(), &lambda = pbm.milieu().conductivite().passe(), &mu = ref_cast(Fluide_base, pbm.milieu()).viscosite_dynamique().passe(),
                              &rho = pbm.milieu().masse_volumique().passe(), &Cp = pbm.milieu().capacite_calorifique().passe();
            DoubleTrav qpk(N[o_p]), dTf_qpk(N[o_p], N[o_p]), dTp_qpk(N[o_p]), qpi(N[o_p], N[o_p]), dTf_qpi(N[o_p], N[o_p], N[o_p]), dTp_qpi(N[o_p], N[o_p]), v(N[o_p], D), nv(N[o_p]);
            for (i = 0; i < e_f[o_p].get().dimension(1) && (fb = e_f[o_p](o_e, i)) >= 0; i++)
              for (prefac = fs[o_p](fb) * pf[o_p](fb) * (o_e == f_e[o_p](fb, 0) ? 1 : -1) / (pe[o_p](o_e) * ve[o_p](o_e)), n = 0; n < N[o_p]; n++)
                for (fac = prefac * vit(fb, n), d = 0; d < D; d++)
                  v(n, d) += fac * (xv[o_p](fb, d) - xp[o_p](o_e, d));
            for (n = 0; n < N[o_p]; n++) nv(n) = sqrt(zone[0].get().dot(&v(n, 0), &v(n, 0)));
// appel : on n'est implicite qu'en les temperatures
            corr[o_p]->qp(N[o_p], o_f, dh(o_e), dh(o_e), &alpha(o_e, 0), &v_aux[o_p](o_f, 0), press(e), nv.addr(), v_aux[0](f, 0), &lambda(o_e, 0), &mu(o_e, 0), &rho(o_e, 0), &Cp(o_e, 0),
                          &qpk, NULL, NULL, NULL, &dTf_qpk, &dTp_qpk, &qpi, NULL, NULL, NULL, &dTf_qpi, &dTp_qpi, NULL, j);
            for (n = 0; n < N[o_p]; n++) secmem(!aux_only * ne_tot[0] + f, 0) -= fs[0](f) * qpk(n);//second membre
            if (mat[o_p])
              for (k1 = 0; k1 < N[o_p]; k1++)
                for (k2 = 0; k2 < N[o_p]; k2++) //derivees en Tfluide
                  (*mat[o_p])(!aux_only * ne_tot[0] + f, N[o_p] * (!aux_only * ne_tot[o_p] + o_f) + k2) += fs[0](f) * dTf_qpk(k1, k2);
            if (mat[0])
              for (n = 0; n < N[o_p]; n++) /* derivees en Tparoi */
                (*mat[0])(!aux_only * ne_tot[0] + f, !aux_only * ne_tot[0] + f) += fs[0](f) * dTp_qpk(n);
          }
        else if (ech.invh_paroi)
          for (n = 0; n < N[0]; n++)/* resistance de la paroi -> ajout du h(T'-T) */
            {
              secmem(!aux_only * ne_tot[0] + f, n) -= fs[0](f) / ech.invh_paroi * (v_aux[0](f, n) - v_aux[o_p](o_f, n)); //second membre
              if (mat[0])   (*mat[0])(N[0] * (!aux_only * ne_tot[0] + f) + n, N[0] * (!aux_only * ne_tot[0] + f) + n) += fs[0](f) / ech.invh_paroi; //derivees
              if (mat[o_p]) (*mat[o_p])(N[0] * (!aux_only * ne_tot[0] + f) + n, N[o_p] * (!aux_only * ne_tot[o_p] + o_f) + n) -= fs[0](f) / ech.invh_paroi;
            }
        else for (zone[o_p].get().W2(&diffu[o_p].get(), o_e, w2), i = 0; i < w2.dimension(0); i++) /* pas de resistance -> ajout du flux de l'autre cote */
            if (e_f[o_p](o_e, i) == o_f)
              for (j = 0; j < w2.dimension(1); j++)
                for (n = 0; n < N[0]; n++)
                  if (w2(i, j, n))
                    {
                      secmem(!aux_only * ne_tot[0] + f, n) -= w2(i, j, n) * (v_aux[o_p * (j != i)](j != i ? e_f[o_p](o_e, j) : f, n) - inco[o_p](o_e, n)); //second membre
                      if (mat[o_p * (j != i)] && (j == i || fcl[o_p](o_f, 0) < 6)) //autre face: on substitue T_fb par T_f
                        (*mat[o_p * (j != i)])(N[0] * (!aux_only * ne_tot[0] + f) + n, N[0] * (!aux_only * ne_tot[o_p * (j != i)] + (j != i ? e_f[o_p](o_e, j) : f)) + n) += w2(i, j, n);
                      if (!aux_only && mat[o_p]) (*mat[o_p])(N[0] * (ne_tot[0] + f) + n, N[0] * o_e + n) -= w2(i, j, n); //autre element
                    }
      }
    else if (fcl[0](f, 0) == 4)
      for (n = 0; n < N[0]; n++) //Neumann
        secmem(!aux_only * ne_tot[0] + f, n) -= fs[0](f) * ref_cast(Neumann, cls[0].get()[fcl[0](f, 1)].valeur()).flux_impose(fcl[0](f, 2), n);
    else if (fcl[0](f, 0) && fcl[0](f, 0) < 3)
      for (e = f_e[0](f, 0), n = 0; n < N[0]; n++) //Echange_global_impose
        {
          const Echange_impose_base& ech = ref_cast(Echange_impose_base, cls[0].get()[fcl[0](f, 1)].valeur());
          double h = ech.h_imp(fcl[0](f, 2), n), T = ech.T_ext(fcl[0](f, 2), n);
          secmem(!aux_only * ne_tot[0] + f, n) -= fs[0](f) * h * ((fcl[0](f, 0) == 1 ? v_aux[0](f, n) : inco[0](e, n)) - T);
          if (mat[0] && fcl[0](f, 0) == 1) (*mat[0])(N[0] * (!aux_only * ne_tot[0] + f) + n, N[0] * (!aux_only * ne_tot[0] + f) + n) += h * fs[0](f);
          if (mat[0] && fcl[0](f, 0) == 2 && !aux_only) (*mat[0])(N[0] * (ne_tot[0] + f) + n, N[0] * e + n) += h * fs[0](f);
        }
}
References Process::abort(), TRUSTArray< _TYPE_ >::addr(), Milieu_base::capacite_calorifique(), Milieu_base::conductivite(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Pb_Multiphase::eq_masse, Pb_Multiphase::eq_qdm, MorEqn::equation(), Echange_contact_PolyMAC::f_dist, Champ_Elem_PolyMAC::fcl(), Operateur_base::flux_bords_, Nom::getString(), Echange_impose_base::h_imp(), Operateur_base::has_champ_inco(), Equation_base::inconnue(), Navier_Stokes_std::inconnue(), Masse_Multiphase::inconnue(), init_op_ext(), Echange_contact_PolyMAC::invh_paroi, Operateur_base::le_champ_inco, Objet_U::le_nom(), Milieu_base::masse_volumique(), Probleme_base::milieu(), Operateur_base::mon_inconnue(), O_U_Ptr::non_nul(), Echange_contact_PolyMAC::o_idx, Operateur_Diff_base::op_ext, Schema_Temps_base::pas_de_temps(), Champ_Proto::passe(), Champ_Inc::passe(), Navier_Stokes_std::pression(), ref_cast, Equation_base::schema_temps(), TRUSTArray< _TYPE_ >::set_smart_resize(), sub_type, Echange_impose_base::T_ext(), Op_Diff_PolyMAC_base::t_last_aux_, Schema_Temps_base::temps_courant(), Op_Diff_PolyMAC_base::update_aux(), Op_Diff_PolyMAC_base::use_aux_, Ref_Champ_Inc::valeur(), valeur(), Champ_Inc::valeurs(), Champ_Inc_base::valeurs(), and Op_Diff_PolyMAC_base::var_aux.
calculer_dt_stab()
double Op_Diff_PolyMAC_Elem::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 87 of file Op_Diff_PolyMAC_Elem.cpp.
{
  const Zone_PolyMAC& zone = la_zone_poly_.valeur();
  const IntTab& e_f = zone.elem_faces();
  const DoubleTab& nf = zone.face_normales(),
                   *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL,
                    &diffu = diffusivite_pour_pas_de_temps().valeurs(), &lambda = diffusivite().valeurs();
  const DoubleVect& pe = zone.porosite_elem(), &vf = zone.volumes_entrelaces(), &ve = zone.volumes();
  update_nu();
  int i, e, f, n, N = equation().inconnue().valeurs().dimension(1), cD = diffu.dimension(0) == 1, cL = lambda.dimension(0) == 1;
  double dt = 1e10;
  DoubleTrav flux(N);
  for (e = 0; e < zone.nb_elem(); e++)
    {
      for (flux = 0, i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++)
        for (n = 0; n < N; n++)
          flux(n) += zone.nu_dot(&nu_, e, n, &nf(f, 0), &nf(f, 0)) / vf(f);
      for (n = 0; n < N; n++)
        if ((!alp || (*alp)(e, n) > 1e-3) && flux(n)) /* sous 0.5e-6, on suppose que l'evanescence fait le job */
          dt = std::min(dt, pe(e) * ve(e) * (alp ? (*alp)(e, n) : 1) * (lambda(!cL * e, n) / diffu(!cD * e, n)) / flux(n));
      if (dt < 0) abort();
    }
  return Process::mp_min(dt);
}
References Process::abort(), Op_Diff_PolyMAC_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_Poly_base::face_normales(), Equation_base::inconnue(), Op_Diff_PolyMAC_base::la_zone_poly_, Process::mp_min(), Zone_dis_base::nb_elem(), Op_Diff_PolyMAC_base::nu_, Zone_Poly_base::nu_dot(), Zone_VF::porosite_elem(), ref_cast, sub_type, Op_Diff_PolyMAC_base::update_nu(), Ref_Zone_PolyMAC::valeur(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), Zone_VF::volumes(), and Zone_VF::volumes_entrelaces().
completer()
void Op_Diff_PolyMAC_Elem::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Op_Diff_PolyMAC_base.
Definition at line 59 of file Op_Diff_PolyMAC_Elem.cpp.
{
  Op_Diff_PolyMAC_base::completer();
  Equation_base& eq = equation();
  Champ_Elem_PolyMAC& ch = ref_cast(Champ_Elem_PolyMAC, le_champ_inco.non_nul() ? le_champ_inco.valeur() : eq.inconnue().valeur());
  ch.init_auxiliary_variables();
  const Zone_PolyMAC& zone = la_zone_poly_.valeur();
  if (zone.zone().nb_joints() && zone.zone().joint(0).epaisseur() < 1)
    Cerr << "Op_Diff_PolyMAC_Elem : largeur de joint insuffisante (minimum 1)!" << finl, Process::exit();
  flux_bords_.resize(zone.premiere_face_int(), ch.valeurs().line_size());
}
References Cerr, Op_Diff_PolyMAC_base::completer(), Joint::epaisseur(), MorEqn::equation(), Process::exit(), finl, Operateur_base::flux_bords_, Equation_base::inconnue(), Champ_Elem_PolyMAC::init_auxiliary_variables(), Zone::joint(), Op_Diff_PolyMAC_base::la_zone_poly_, Operateur_base::le_champ_inco, TRUSTVect< _TYPE_ >::line_size(), Zone::nb_joints(), O_U_Ptr::non_nul(), Zone_VF::premiere_face_int(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Deriv_Champ_Inc_base::valeur(), Ref_Champ_Inc::valeur(), Ref_Zone_PolyMAC::valeur(), Champ_Inc_base::valeurs(), and Zone_dis_base::zone().
cree_instance()
Objet_U * Op_Diff_PolyMAC_Elem::cree_instance () static
Definition at line 41 of file Op_Diff_PolyMAC_Elem.cpp.
dimensionner_blocs_ext()
void Op_Diff_PolyMAC_Elem::dimensionner_blocs_ext (int aux_only, matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Implements Op_Diff_PolyMAC_base.
Definition at line 113 of file Op_Diff_PolyMAC_Elem.cpp.
{
  init_op_ext();
  const std::string& nom_inco = (le_champ_inco.non_nul() ? le_champ_inco.valeur() : equation().inconnue()).le_nom().getString();
  int i, j, k, l, e, o_e, f, o_f, fb, m, n, M, n_ext = op_ext.size(), n_sten = 0, p, semi = semi_impl.count(nom_inco);
  std::vector<Matrice_Morse *> mat(n_ext); //matrices
  std::vector<int> N, ne_tot; //composantes, nombre d'elements total par pb
  std::vector<std::reference_wrapper<const Zone_PolyMAC>> zone; //zones
  std::vector<std::reference_wrapper<const Conds_lim>> cls; //conditions aux limites
  std::vector<std::reference_wrapper<const IntTab>> fcl, e_f, f_e; //tableaux "fcl", "elem_faces", "faces_voisins"
  std::vector<std::reference_wrapper<const DoubleTab>> diffu, inco; //inconnues, normales aux faces, positions elems / faces / sommets
  std::deque<ConstDoubleTab_parts> v_part; //blocs de chaque inconnue
  std::vector<IntTrav> stencil(n_ext); //stencils par matrice
  for (i = 0, M = 0; i < n_ext; M = std::max(M, N[i]), i++)
    {
      std::string nom_mat = i ? nom_inco + "/" + op_ext[i]->equation().probleme().le_nom().getString() : nom_inco;
      mat[i] = matrices.count(nom_mat) ? matrices.at(nom_mat) : NULL;
      zone.push_back(std::ref(ref_cast(Zone_PolyMAC, op_ext[i]->equation().zone_dis().valeur())));
      f_e.push_back(std::ref(zone[i].get().face_voisins())), e_f.push_back(std::ref(zone[i].get().elem_faces()));
      cls.push_back(std::ref(op_ext[i]->equation().zone_Cl_dis().les_conditions_limites()));
      diffu.push_back(ref_cast(Op_Diff_PolyMAC_Elem, *op_ext[i]).nu());
      const Champ_Elem_PolyMAC& ch = ref_cast(Champ_Elem_PolyMAC, op_ext[i]->has_champ_inco() ? op_ext[i]->mon_inconnue().valeur() : op_ext[i]->equation().inconnue().valeur());
      N.push_back(ch.valeurs().line_size()), fcl.push_back(std::ref(ch.fcl())), ne_tot.push_back(zone[i].get().nb_elem_tot());
      inco.push_back(ch.valeurs()), v_part.emplace_back(ch.valeurs());
      stencil[i].resize(0, 2), stencil[i].set_smart_resize(1);
    }
  IntTrav tpfa(0, N[0]); //pour suivre quels flux sont a deux points
  zone[0].get().creer_tableau_faces(tpfa), tpfa = 1;
  if (!aux_only) Cerr << "Op_Diff_PolyMAC_Elem::dimensionner() : ";
  DoubleTrav w2;
  /* probleme local */
  for (w2.set_smart_resize(1), e = 0; e < ne_tot[0]; e++)
    {
      zone[0].get().W2(&diffu[0].get(), e, w2); //interpolation : [n_ef.nu grad T]_f = w2_{ff'} (T_f' - T_e)
// element <-> toutes ses faces (non Dirichlet)
      if (!aux_only && !semi)
        for (i = 0; i < w2.dimension(0); i++)
          if (!semi && fcl[0](f = e_f[0](e, i), 0) < 6)
            {
              if (e < zone[0].get().nb_elem())
                for (n = 0; n < N[0]; n++) stencil[0].append_line(N[0] * e + n, N[0] * (ne_tot[0] + f) + n);
              if (f < zone[0].get().nb_faces())
                for (n = 0; n < N[0]; n++) stencil[0].append_line(N[0] * (ne_tot[0] + f) + n, N[0] * e + n);
            }
// face <-> face (si les deux sont non Dirichlet)
      for (i = 0; i < w2.dimension(0); i++)
        if ((f = e_f[0](e, i)) >= zone[0].get().nb_faces()) continue; //face virtuelle -> rien
        else if (semi || fcl[0](f = e_f[0](e, i), 0) > 5)
          for (n = 0; n < N[0]; n++) //Dirichlet ou semi-implicite -> diagonale
            stencil[0].append_line(N[0] * (!aux_only * ne_tot[0] + f) + n, N[0] * (!aux_only * ne_tot[0] + f) + n);
        else for (j = 0; j < w2.dimension(1); j++)
            for (fb = e_f[0](e, j), n = 0; n < N[0]; n++) //cas reel
              if (fcl[0](fb, 0) < 6 && w2(i, j, n)) stencil[0].append_line(N[0] * (!aux_only * ne_tot[0] + f) + n, N[0] * (!aux_only * ne_tot[0] + fb) + n), tpfa(f, n) &= (i == j);
    }
  /* problemes distants : pour les Echange_contact */
  const Echange_contact_PolyMAC *pcl;
  if (!semi)
    for (i = 0; i < cls[0].get().size(); i++)
      if ((pcl = sub_type(Echange_contact_PolyMAC, cls[0].get()[i].valeur()) ? &ref_cast(Echange_contact_PolyMAC, cls[0].get()[i].valeur()) : NULL))
        for (pcl->init_f_dist(), j = 0, p = std::find(op_ext.begin(), op_ext.end(), &pcl->o_diff.valeur()) - op_ext.begin(); j < pcl->fvf->nb_faces(); j++)
          {
            f = pcl->fvf->num_face(j), o_f = pcl->f_dist(j), o_e = f_e[p](o_f, 0); //faces cote local/distant, elem cote distant
            zone[p].get().W2(&diffu[p].get(), o_e, w2); //matrice w2 de l'autre cote
            k = std::find(&e_f[p](o_e, 0), &e_f[p](o_e, 0) + w2.dimension(0), o_f) - &e_f[p](o_e, 0); //indice de o_f dans o_e
            if (!aux_only)
              for (n = 0; n < N[0]; n++)
                for (m = (N[0] == N[p]) * n; m < (N[0] == N[p] ? n + 1 : N[p]); m++)
                  stencil[p].append_line(N[0] * (ne_tot[0] + f) + n, N[p] * o_e + m); //face <-> elem : compo par compo si N[0] == N[p], tout sinon
            for (l = 0; l < w2.dimension(0); l++)
              if (fcl[p](fb = e_f[p](o_e, l), 0) < 6)
                for (n = 0; n < N[0]; n++)
                  for (m = (N[0] == N[p]) * n; m < (N[0] == N[p] ? n + 1 : N[p]); m++)
                    if (w2(k, l, m)) stencil[p].append_line(N[0] * (!aux_only * ne_tot[0] + f) + n, N[p] * (!aux_only * ne_tot[p] + fb) + m);
          }
  for (i = 0; i < n_ext; i++)
    if (mat[i])
      {
        tableau_trier_retirer_doublons(stencil[i]);
        Matrice_Morse mat2;
        Matrix_tools::allocate_morse_matrix(aux_only ? v_part[0][1].size_totale() : inco[0].get().size_totale(), aux_only ? v_part[i][1].size_totale() : inco[i].get().size_totale(), stencil[i], mat2);
        mat[i]->nb_colonnes() ? *mat[i] += mat2 : *mat[i] = mat2;
      }
  for (auto &&st : stencil) n_sten += st.dimension(0); //n_sten : nombre total de points du stencil de l'operateur
  if (!aux_only) Cerr << "width " << Process::mp_sum(n_sten) * 1. / (N[0] * zone[0].get().mdv_elems_faces.valeur().nb_items_seq_tot())
                        << " " << mp_somme_vect(tpfa) * 100. / (N[0] * zone[0].get().md_vector_faces().valeur().nb_items_seq_tot()) << "% TPFA " << finl;
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Echange_contact_PolyMAC::f_dist, Champ_Elem_PolyMAC::fcl(), finl, Echange_contact_PolyMAC::fvf, Nom::getString(), Operateur_base::has_champ_inco(), Equation_base::inconnue(), Echange_contact_PolyMAC::init_f_dist(), init_op_ext(), Operateur_base::le_champ_inco, Objet_U::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Operateur_base::mon_inconnue(), mp_somme_vect(), Process::mp_sum(), Front_VF::nb_faces(), O_U_Ptr::non_nul(), Front_VF::num_face(), Echange_contact_PolyMAC::o_diff, Operateur_Diff_base::op_ext, ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), sub_type, tableau_trier_retirer_doublons(), Ref_Champ_Inc::valeur(), Ref_Op_Diff_PolyMAC_Elem::valeur(), valeur(), and Champ_Inc_base::valeurs().
duplique()
int Op_Diff_PolyMAC_Elem::duplique () const override virtual
Implements Objet_U.
Definition at line 41 of file Op_Diff_PolyMAC_Elem.cpp.
get_info()
const Type_info * Op_Diff_PolyMAC_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_PolyMAC_base.
Definition at line 41 of file Op_Diff_PolyMAC_Elem.cpp.
info()
const Type_info * Op_Diff_PolyMAC_Elem::info () static
Definition at line 41 of file Op_Diff_PolyMAC_Elem.cpp.
init_op_ext()
void Op_Diff_PolyMAC_Elem::init_op_ext () const
Definition at line 71 of file Op_Diff_PolyMAC_Elem.cpp.
{
  if (op_ext.size()) return; //deja fait
  op_ext = { this };
  const Conds_lim& cls = equation().zone_Cl_dis().les_conditions_limites();
  for (int i = 0; i < cls.size(); i++)
    if (sub_type(Echange_contact_PolyMAC, cls[i].valeur()))
      {
        const Echange_contact_PolyMAC& cl = ref_cast(Echange_contact_PolyMAC, cls[i].valeur());
        cl.init_op();
        const Op_Diff_PolyMAC_Elem *o_op = &cl.o_diff.valeur();
        if (std::find(op_ext.begin(), op_ext.end(), o_op) == op_ext.end()) op_ext.push_back(o_op);
        cl.o_idx = std::find(op_ext.begin(), op_ext.end(), o_op) - op_ext.begin();
      }
}
References MorEqn::equation(), Echange_contact_PolyMAC::init_op(), Zone_Cl_dis::les_conditions_limites(), Echange_contact_PolyMAC::o_diff, Echange_contact_PolyMAC::o_idx, Operateur_Diff_base::op_ext, ref_cast, vect_impl::size(), sub_type, Ref_Op_Diff_PolyMAC_Elem::valeur(), valeur(), and Equation_base::zone_Cl_dis().
Referenced by ajouter_blocs_ext(), and dimensionner_blocs_ext().
modifier_pour_Cl()
void Op_Diff_PolyMAC_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 46 of file Op_Diff_PolyMAC_Elem.h.
{ };
printOn()
Sortie & Op_Diff_PolyMAC_Elem::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_PolyMAC_base.
Definition at line 49 of file Op_Diff_PolyMAC_Elem.cpp.
{
  return Op_Diff_PolyMAC_base::printOn( os );
}
References Op_Diff_PolyMAC_base::printOn().
readOn()
Entree & Op_Diff_PolyMAC_Elem::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_PolyMAC_base.
Definition at line 54 of file Op_Diff_PolyMAC_Elem.cpp.
{
  return Op_Diff_PolyMAC_base::readOn( is );
}
References Op_Diff_PolyMAC_base::readOn().
self_cast() [1/2]
const Op_Diff_PolyMAC_Elem & Op_Diff_PolyMAC_Elem::self_cast (const Objet_U & r) static
Definition at line 41 of file Op_Diff_PolyMAC_Elem.cpp.
self_cast() [2/2]
Op_Diff_PolyMAC_Elem & Op_Diff_PolyMAC_Elem::self_cast (Objet_U & r) static
Definition at line 41 of file Op_Diff_PolyMAC_Elem.cpp.
taille_memoire()
unsigned Op_Diff_PolyMAC_Elem::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 41 of file Op_Diff_PolyMAC_Elem.cpp.
Member Data Documentation
info_obj
const Type_info Op_Diff_PolyMAC_Elem::info_obj static
Definition at line 33 of file Op_Diff_PolyMAC_Elem.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Op_Diff_PolyMAC_Elem.h
src/PolyMAC/Operateurs/Op_Diff_PolyMAC_Elem.cpp