TRUST: Deriv_Sous_zone_dis_base Class Reference
Deriv_Sous_zone_dis_base Class Reference
#include <Sous_zone_dis.h>
Public Member Functions
~Deriv_Sous_zone_dis_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Sous_zone_dis_base ()
Deriv_Sous_zone_dis_base (const Deriv_Sous_zone_dis_base &)
const Sous_zone_dis_base & valeur () const
Sous_zone_dis_base & valeur ()
const Sous_zone_dis_base * operator-> () const
Sous_zone_dis_base * operator-> ()
const Deriv_Sous_zone_dis_base & operator= (const Sous_zone_dis_base &)
const Deriv_Sous_zone_dis_base & operator= (const Deriv_Sous_zone_dis_base &)
operator const Sous_zone_dis_base & () const
operator Sous_zone_dis_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Sous_zone_dis_base & self_cast (Objet_U &)
static const
Deriv_Sous_zone_dis_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Sous_zone_dis_base * pointeur_
Detailed Description
Definition at line 28 of file Sous_zone_dis.h.
Constructor & Destructor Documentation
Deriv_Sous_zone_dis_base::~Deriv_Sous_zone_dis_base ()
Definition at line 25 of file Sous_zone_dis.cpp.
Deriv_Sous_zone_dis_base::Deriv_Sous_zone_dis_base ()
Definition at line 25 of file Sous_zone_dis.cpp.
Deriv_Sous_zone_dis_base::Deriv_Sous_zone_dis_base (const Deriv_Sous_zone_dis_base & t)
Definition at line 25 of file Sous_zone_dis.cpp.
Member Function Documentation
Objet_U * Deriv_Sous_zone_dis_base::cree_instance () [static]
Reimplemented in Sous_zone_dis.
Definition at line 25 of file Sous_zone_dis.cpp.
int Deriv_Sous_zone_dis_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Sous_zone_dis.
Definition at line 25 of file Sous_zone_dis.cpp.
const Type_info * Deriv_Sous_zone_dis_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Sous_zone_dis.
Definition at line 25 of file Sous_zone_dis.cpp.
const Type_info & Deriv_Sous_zone_dis_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Sous_zone_dis.cpp.
const Type_info * Deriv_Sous_zone_dis_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Sous_zone_dis.
Definition at line 25 of file Sous_zone_dis.cpp.
Deriv_Sous_zone_dis_base::operator const Sous_zone_dis_base & () const
Definition at line 25 of file Sous_zone_dis.cpp.
Deriv_Sous_zone_dis_base::operator Sous_zone_dis_base & ()
Definition at line 25 of file Sous_zone_dis.cpp.
const Sous_zone_dis_base * Deriv_Sous_zone_dis_base::operator-> () const [inline]
Definition at line 28 of file Sous_zone_dis.h.
: public DERIV(Sous_zone_dis_base)
Sous_zone_dis_base * Deriv_Sous_zone_dis_base::operator-> () [inline]
Definition at line 28 of file Sous_zone_dis.h.
: public DERIV(Sous_zone_dis_base)
const Deriv_Sous_zone_dis_base & Deriv_Sous_zone_dis_base::operator= (const Deriv_Sous_zone_dis_base & t)
Definition at line 25 of file Sous_zone_dis.cpp.
const Deriv_Sous_zone_dis_base & Deriv_Sous_zone_dis_base::operator= (const Sous_zone_dis_base & t)
Definition at line 25 of file Sous_zone_dis.cpp.
Sortie & Deriv_Sous_zone_dis_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Sous_zone_dis.
Definition at line 25 of file Sous_zone_dis.cpp.
Entree & Deriv_Sous_zone_dis_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Sous_zone_dis.
Definition at line 25 of file Sous_zone_dis.cpp.
const Deriv_Sous_zone_dis_base & Deriv_Sous_zone_dis_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Sous_zone_dis.
Definition at line 25 of file Sous_zone_dis.cpp.
Deriv_Sous_zone_dis_base & Deriv_Sous_zone_dis_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Sous_zone_dis.
Definition at line 25 of file Sous_zone_dis.cpp.
void Deriv_Sous_zone_dis_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Sous_zone_dis.cpp.
unsigned Deriv_Sous_zone_dis_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Sous_zone_dis.
Definition at line 25 of file Sous_zone_dis.cpp.
const Sous_zone_dis_base & Deriv_Sous_zone_dis_base::valeur () const [inline]
Definition at line 28 of file Sous_zone_dis.h.
Referenced by Sous_zone_dis::associer_sous_zone(), Sous_zone_dis::associer_zone_dis(), Perte_Charge_VEF::completer(), Op_Conv_EF_VEF_P1NC_Stab::completer(), and Sous_zone_dis::discretiser().
: public DERIV(Sous_zone_dis_base)
Sous_zone_dis_base & Deriv_Sous_zone_dis_base::valeur () [inline]
Definition at line 28 of file Sous_zone_dis.h.
: public DERIV(Sous_zone_dis_base)
Member Data Documentation
const Type_info Deriv_Sous_zone_dis_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Sous_zone_dis.
Definition at line 28 of file Sous_zone_dis.h.
Sous_zone_dis_base* Deriv_Sous_zone_dis_base::pointeur_ [private]
Definition at line 28 of file Sous_zone_dis.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Sous_zone_dis.h
src/Kernel/Framework/Sous_zone_dis.cpp