TRUST: SolvElem_Gmres Class Reference
SolvElem_Gmres Class Reference
#include <SolvElem_Gmres.h>
Public Member Functions
SolvElem_Gmres ()
~SolvElem_Gmres ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void iteration (int n, const DoubleVect &secmem, DoubleVect &solution, ArrOfInt &ipar, ArrOfDouble &fpar, ArrOfDouble &w)
ArrOfDouble & dimensionne_wks (int n, ArrOfDouble &w)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static SolvElem_Gmres & self_cast (Objet_U &)
static const SolvElem_Gmres & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 30 of file SolvElem_Gmres.h.
Constructor & Destructor Documentation
SolvElem_Gmres::SolvElem_Gmres ()
Definition at line 25 of file SolvElem_Gmres.cpp.
SolvElem_Gmres::~SolvElem_Gmres ()
Definition at line 25 of file SolvElem_Gmres.cpp.
Member Function Documentation
Objet_U * SolvElem_Gmres::cree_instance () [static]
Definition at line 25 of file SolvElem_Gmres.cpp.
ArrOfDouble & SolvElem_Gmres::dimensionne_wks (int n, ArrOfDouble & w) [inline, virtual]
Implements SolvElem_base.
Definition at line 54 of file SolvElem_Gmres.h.
References ArrOfDouble::resize_array().
{
  int m=10;
  w.resize_array(((n+3)*(m+2))+((m+1)*m/2));
  return w;
}
int SolvElem_Gmres::duplique () const [virtual]
Implements SolvElem_base.
Definition at line 25 of file SolvElem_Gmres.cpp.
const Type_info * SolvElem_Gmres::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from SolvElem_base.
Definition at line 25 of file SolvElem_Gmres.cpp.
const Type_info * SolvElem_Gmres::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from SolvElem_base.
Definition at line 25 of file SolvElem_Gmres.cpp.
void SolvElem_Gmres::iteration (int n, const DoubleVect & secmem, DoubleVect & solution, ArrOfInt & ipar, ArrOfDouble & fpar, ArrOfDouble & w) [inline, virtual]
Implements SolvElem_base.
Definition at line 44 of file SolvElem_Gmres.h.
References ArrOfInt::addr(), ArrOfDouble::addr(), F77NAME, and GMRESV2().
{
  F77NAME(GMRESV2)(&n,secmem.addr(),solution.addr(),ipar.addr(),fpar.addr(),w.addr());
}
Sortie & SolvElem_Gmres::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from SolvElem_base.
Definition at line 29 of file SolvElem_Gmres.cpp.
{
  return s  ;
}
Entree & SolvElem_Gmres::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from SolvElem_base.
Definition at line 37 of file SolvElem_Gmres.cpp.
{
  return is;
}
SolvElem_Gmres & SolvElem_Gmres::self_cast (Objet_U & r) [static]
Reimplemented from SolvElem_base.
Definition at line 25 of file SolvElem_Gmres.cpp.
const SolvElem_Gmres & SolvElem_Gmres::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from SolvElem_base.
Definition at line 25 of file SolvElem_Gmres.cpp.
unsigned SolvElem_Gmres::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file SolvElem_Gmres.cpp.
Member Data Documentation
const Type_info SolvElem_Gmres::info_obj [static]
Reimplemented from SolvElem_base.
Definition at line 32 of file SolvElem_Gmres.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/SolvElem_Gmres.h
src/Kernel/Math/SolvSys/SolvElem_Gmres.cpp