TRUST: Eval_Dift_VDF_var_Face Class Reference
Eval_Dift_VDF_var_Face Class Reference
class Eval_Dift_VDF_var_Face
Evaluateur VDF pour la diffusion totale (laminaire et turbulente)
Le champ diffuse est un Champ_Face
Le champ de diffusivite n'est pas constant.
#include <Eval_Dift_VDF_var_Face.h>
Public Member Functions
void associer_modele_turbulence (const Mod_turb_hyd_base &mod)
void mettre_a_jour ()
double tau_tan_impl (int face, int k) const
bool uses_wall () const
Static Public Attributes
static constexpr bool IS_VAR = true
static constexpr bool IS_TURB = true
Private Attributes
Ref_Mod_turb_hyd_base le_modele_turbulence
Ref_Turbulence_paroi_base loipar
DoubleTab tau_tan_
Detailed Description
class Eval_Dift_VDF_var_Face
Evaluateur VDF pour la diffusion totale (laminaire et turbulente)
Le champ diffuse est un Champ_Face
Le champ de diffusivite n'est pas constant.
See also:
Eval_Dift_VDF_var
Definition at line 42 of file Eval_Dift_VDF_var_Face.h.
Member Function Documentation
void Eval_Dift_VDF_var_Face::associer_modele_turbulence (const Mod_turb_hyd_base & mod) [inline]
Definition at line 49 of file Eval_Dift_VDF_var_Face.h.
References le_modele_turbulence.
Referenced by Op_Dift_VDF_var_Face::completer().
  {
    le_modele_turbulence = mod;
  }
void Eval_Dift_VDF_var_Face::mettre_a_jour () [inline, virtual]
Reimplemented from Eval_Dift_VDF_var.
Definition at line 54 of file Eval_Dift_VDF_var_Face.h.
References le_modele_turbulence, O_U_Ptr::non_nul(), DoubleTab::ref(), ArrOfDouble::size_array(), tau_tan_, and Ref_Mod_turb_hyd_base::valeur().
  {
    Eval_Dift_VDF_var::mettre_a_jour();
    if (le_modele_turbulence->loi_paroi().non_nul())
      {
// Modif E. Saikali : on fait le ref seulement si le tableau a ete initialise, sinon pointeur nulle
        const DoubleTab& tab = le_modele_turbulence->loi_paroi().valeur().Cisaillement_paroi();
        if (tab.size_array() > 0)
          tau_tan_.ref(tab);
      }
  }
double Eval_Dift_VDF_var_Face::tau_tan_impl (int face, int k) const [inline]
Reimplemented from Eval_Diff_VDF_var.
Definition at line 80 of file Eval_Dift_VDF_var_Face.h.
References Cerr, DoubleTab::dimension(), DoubleTab::dimension_tot(), Process::exit(), finl, Zone_VF::ind_faces_virt_bord(), Evaluateur_VDF::la_zone, Zone_VF::nb_faces(), tau_tan_, and Ref_Zone_VDF::valeur().
{
  int nb_faces = la_zone.valeur().nb_faces();
  const ArrOfInt& ind_faces_virt_bord = la_zone.valeur().ind_faces_virt_bord();
  int f;
  if(face>=tau_tan_.dimension(0))
    f = ind_faces_virt_bord[face-nb_faces];
  else
    f=face;
  if(f>=tau_tan_.dimension_tot(0))
    {
      Cerr << "Erreur dans tau_tan " << finl;
      Cerr << "dimension : " << tau_tan_.dimension(0) << finl;
      Cerr << "dimension_tot : " << tau_tan_.dimension_tot(0) << finl;
      Cerr << "face : " << face << finl;
      Process::exit();
    }
  return tau_tan_(f,k);
}
bool Eval_Dift_VDF_var_Face::uses_wall () const [inline]
Reimplemented from Eval_Diff_VDF_var.
Definition at line 68 of file Eval_Dift_VDF_var_Face.h.
References le_modele_turbulence, Mod_turb_hyd_base::utiliser_loi_paroi(), and Ref_Mod_turb_hyd_base::valeur().
  {
    return le_modele_turbulence.valeur().utiliser_loi_paroi();
  }
Member Data Documentation
constexpr bool Eval_Dift_VDF_var_Face::IS_TURB = true [static]
Reimplemented from Eval_Diff_VDF_Face< Eval_Dift_VDF_var_Face >.
Definition at line 47 of file Eval_Dift_VDF_var_Face.h.
constexpr bool Eval_Dift_VDF_var_Face::IS_VAR = true [static]
Reimplemented from Eval_Diff_VDF_Face< Eval_Dift_VDF_var_Face >.
Definition at line 46 of file Eval_Dift_VDF_var_Face.h.
Ref_Mod_turb_hyd_base Eval_Dift_VDF_var_Face::le_modele_turbulence [private]
Definition at line 74 of file Eval_Dift_VDF_var_Face.h.
Referenced by associer_modele_turbulence(), mettre_a_jour(), and uses_wall().
Ref_Turbulence_paroi_base Eval_Dift_VDF_var_Face::loipar [private]
Reimplemented from Eval_Turbulence.
Definition at line 75 of file Eval_Dift_VDF_var_Face.h.
DoubleTab Eval_Dift_VDF_var_Face::tau_tan_ [private]
Definition at line 76 of file Eval_Dift_VDF_var_Face.h.
Referenced by mettre_a_jour(), and tau_tan_impl().
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs_Diff/Eval_Dift_VDF_var_Face.h