TRUST: Trianguler_fin Class Reference
Trianguler_fin Class Reference
Classe Trianguler_fin
Cette classe est un interprete qui sert a lire et executer
la directive Trianguler_fin:
Trianguler_fin nom_domaine
Cette directive est a utiliser en discretisation VEF pour obtenir
un maillage triangulaire a partir d'un maillage constitue de rectangles.
#include <Trianguler_fin.h>
Public Member Functions
Trianguler_fin ()
~Trianguler_fin ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void trianguler (Zone &) const
Triangule tous les element d'une zone: transforme
les elements goemetriques de la zone en triangles.
Pour l'instant on ne sait trianguler que des Rectangles<br>(on les coupe en 8).
virtual int dimension_application () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Trianguler_fin & self_cast (Objet_U &)
static const Trianguler_fin & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Interprete::printOn(Sortie&)
virtual Entree & readOn (Entree &)
Simple appel a: Interprete::readOn(Entree&)
Detailed Description
Classe Trianguler_fin
Cette classe est un interprete qui sert a lire et executer
la directive Trianguler_fin:
Trianguler_fin nom_domaine
Cette directive est a utiliser en discretisation VEF pour obtenir
un maillage triangulaire a partir d'un maillage constitue de rectangles.
Definition at line 42 of file Trianguler_fin.h.
Constructor & Destructor Documentation
Trianguler_fin::Trianguler_fin ()
Definition at line 26 of file Trianguler_fin.cpp.
Trianguler_fin::~Trianguler_fin ()
Definition at line 26 of file Trianguler_fin.cpp.
Member Function Documentation
Objet_U * Trianguler_fin::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 26 of file Trianguler_fin.cpp.
int Trianguler_fin::dimension_application () const [inline, virtual]
Implements Triangulation_base.
Definition at line 52 of file Trianguler_fin.h.
{
  return 2;
}
int Trianguler_fin::duplique () const [virtual]
Implements Triangulation_base.
Definition at line 26 of file Trianguler_fin.cpp.
const Type_info * Trianguler_fin::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 26 of file Trianguler_fin.cpp.
const Type_info * Trianguler_fin::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 26 of file Trianguler_fin.cpp.
Sortie & Trianguler_fin::printOn (Sortie & os) const [protected, virtual]
Simple appel a: Interprete::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 43 of file Trianguler_fin.cpp.
{
  return Interprete::printOn(os);
}
Entree & Trianguler_fin::readOn (Entree & is) [protected, virtual]
Simple appel a: Interprete::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Triangulation_base.
Definition at line 63 of file Trianguler_fin.cpp.
{
  return Interprete::readOn(is);
}
const Trianguler_fin & Trianguler_fin::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Triangulation_base.
Definition at line 26 of file Trianguler_fin.cpp.
Trianguler_fin & Trianguler_fin::self_cast (Objet_U & r) [static]
Reimplemented from Triangulation_base.
Definition at line 26 of file Trianguler_fin.cpp.
unsigned Trianguler_fin::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 26 of file Trianguler_fin.cpp.
void Trianguler_fin::trianguler (Zone & zone) const [virtual]
Triangule tous les element d'une zone: transforme
les elements goemetriques de la zone en triangles.
Pour l'instant on ne sait trianguler que des Rectangles<br>(on les coupe en 8).
Implements Triangulation_base.
Definition at line 85 of file Trianguler_fin.cpp.
References Elem_geom::calculer_centres_gravite(), Cerr, Zone::construit_octree(), Domaine::coord_sommets(), Objet_U::dimension, DoubleTab::dimension(), IntTab::dimension(), Zone::domaine(), Process::exit(), Zone::faces_bord(), Zone::faces_int(), Zone::faces_raccord(), finl, Zone::invalide_octree(), Zone::les_elems(), Faces::les_sommets(), Domaine::les_sommets(), LIST_CURSEUR, Interprete_geometrique_base::mettre_a_jour_sous_zone(), Objet_U::que_suis_je(), IntTab::ref(), IntTab::resize(), DoubleTab::resize(), Faces::segment_2D, Zone::type_elem(), Faces::typer(), Zone::typer(), and Faces::voisins().
{
  Domaine& dom=zone.domaine();
  const DoubleTab& xs=dom.coord_sommets();
  IntTab& les_elems=zone.les_elems();
  int oldsz=les_elems.dimension(0);
  DoubleTab& sommets=dom.les_sommets();
  int nbs=sommets.dimension(0);
  {
    DoubleTab sommets_ajoutes(oldsz, dimension);
    zone.type_elem()->calculer_centres_gravite(sommets_ajoutes);
    sommets.resize(4*nbs, dimension);
    for(int i=0; i<oldsz; i++)
      for(int j=0; j<dimension; j++)
        sommets(nbs+i,j)=sommets_ajoutes(i,j);
  }
  if ((zone.type_elem()->que_suis_je() == "Rectangle") || (zone.type_elem()->que_suis_je() == "Quadrangle"))
    {
      zone.typer("Triangle");
      IntTab new_elems(8*oldsz,3);
      IntTab fait_sommet_arete(4*nbs,3);
      fait_sommet_arete=-1;
      int j=0;
      for(int i=0; i< oldsz; i++)
        {
          int i0=les_elems(i,0);
          int i1=les_elems(i,1);
          int i2=les_elems(i,2);
          int i3=les_elems(i,3);
          int i01=-1;
          int i02=-1;
          int i13=-1;
          int i23=-1;
          for (int ii=0 ; ii<j ; ii++)
            {
              if ( fait_sommet_arete(ii,0)==i0 && fait_sommet_arete(ii,1)==i1 ) i01=nbs+oldsz+ii ;
              if ( fait_sommet_arete(ii,0)==i0 && fait_sommet_arete(ii,1)==i2 ) i02=nbs+oldsz+ii ;
              if ( fait_sommet_arete(ii,0)==i1 && fait_sommet_arete(ii,1)==i3 ) i13=nbs+oldsz+ii ;
              if ( fait_sommet_arete(ii,0)==i2 && fait_sommet_arete(ii,1)==i3 ) i23=nbs+oldsz+ii ;
            }
          if(i01==-1)
            {
              fait_sommet_arete(j,0)=i0;
              fait_sommet_arete(j,1)=i1;
              i01=nbs+oldsz+j;
              sommets(i01,0)=0.5*(xs(i0,0)+xs(i1,0));
              sommets(i01,1)=0.5*(xs(i0,1)+xs(i1,1));
              j++;
            }
          if(i02==-1)
            {
              fait_sommet_arete(j,0)=i0;
              fait_sommet_arete(j,1)=i2;
              i02=nbs+oldsz+j;
              sommets(i02,0)=0.5*(xs(i0,0)+xs(i2,0));
              sommets(i02,1)=0.5*(xs(i0,1)+xs(i2,1));
              j++;
            }
          if(i13==-1)
            {
              fait_sommet_arete(j,0)=i1;
              fait_sommet_arete(j,1)=i3;
              i13=nbs+oldsz+j;
              sommets(i13,0)=0.5*(xs(i1,0)+xs(i3,0));
              sommets(i13,1)=0.5*(xs(i1,1)+xs(i3,1));
              j++;
            }
          if(i23==-1)
            {
              fait_sommet_arete(j,0)=i2;
              fait_sommet_arete(j,1)=i3;
              i23=nbs+oldsz+j;
              sommets(i23,0)=0.5*(xs(i2,0)+xs(i3,0));
              sommets(i23,1)=0.5*(xs(i2,1)+xs(i3,1));
              j++;
            }
          new_elems(i,0)=    i+nbs;
          new_elems(i,1)=    i0;
          new_elems(i,2)=    i01;
          new_elems(i+oldsz,0)=  i+nbs;
          new_elems(i+oldsz,1)=  i01;
          new_elems(i+oldsz,2)=  i1;
          mettre_a_jour_sous_zone(zone,i,i+oldsz,1);
          new_elems(i+2*oldsz,0)=  i+nbs;
          new_elems(i+2*oldsz,1)=  i1;
          new_elems(i+2*oldsz,2)=  i13;
          mettre_a_jour_sous_zone(zone,i,i+2*oldsz,1);
          new_elems(i+3*oldsz,0)=  i+nbs;
          new_elems(i+3*oldsz,1)=  i13;
          new_elems(i+3*oldsz,2)=  i3;
          mettre_a_jour_sous_zone(zone,i,i+3*oldsz,1);
          new_elems(i+4*oldsz,0)=  i+nbs;
          new_elems(i+4*oldsz,1)=  i3;
          new_elems(i+4*oldsz,2)=  i23;
          mettre_a_jour_sous_zone(zone,i,i+4*oldsz,1);
          new_elems(i+5*oldsz,0)=  i+nbs;
          new_elems(i+5*oldsz,1)=  i23;
          new_elems(i+5*oldsz,2)=  i2;
          mettre_a_jour_sous_zone(zone,i,i+5*oldsz,1);
          new_elems(i+6*oldsz,0)=  i+nbs;
          new_elems(i+6*oldsz,1)=  i2;
          new_elems(i+6*oldsz,2)=  i02;
          mettre_a_jour_sous_zone(zone,i,i+6*oldsz,1);
          new_elems(i+7*oldsz,0)=  i+nbs;
          new_elems(i+7*oldsz,1)=  i02;
          new_elems(i+7*oldsz,2)=  i0;
          mettre_a_jour_sous_zone(zone,i,i+7*oldsz,1);
        }
      if(nbs+oldsz+j>4*nbs)
        {
          Cerr << " Review the sizing of sommets() in Trianguler_fin " << finl;
          exit();
        }
      sommets.resize(nbs+oldsz+j,dimension);
      les_elems.ref(new_elems);
// Reconstruction de l'octree
      Cerr << "We have split the rectangles..." << finl;
      zone.invalide_octree();
      zone.typer("Triangle");
      Cerr << "  Reconstruction of the Octree" << finl;
      zone.construit_octree();
      Cerr << "  Octree rebuilt" << finl;
      {
        Cerr << "Splitting of the boundaries" << finl;
        LIST_CURSEUR(Bord) curseur(zone.faces_bord());;;
        while(curseur)
          {
            Faces& les_faces=curseur->faces();
            les_faces.typer(Faces::segment_2D);
            IntTab& sommetsfaces=les_faces.les_sommets();
            int nb_faces=sommetsfaces.dimension(0);
            IntTab nouveaux(2*nb_faces,2);
            les_faces.voisins().resize(2*nb_faces,2);
            les_faces.voisins()=-1;
            for(int i=0; i<nb_faces; i++)
              {
                int i0=sommetsfaces(i,0);
                int i1=sommetsfaces(i,1);
                int i01=-1;
                for (int ii=0 ; ii<nbs+oldsz+j ; ii++)
                  if ( fait_sommet_arete(ii,0)==i0 && fait_sommet_arete(ii,1)==i1 ) i01=nbs+oldsz+ii ;
                assert(i01>=0);
                nouveaux(2*i  ,0)=i0;
                nouveaux(2*i  ,1)=i01;
                nouveaux(2*i+1,0)=i01;
                nouveaux(2*i+1,1)=i1;
              }
            sommetsfaces.ref(nouveaux);
            ++curseur;
          }
      }
      {
        Cerr << "Splitting of the connectors" << finl;
        LIST_CURSEUR(Raccord) curseur(zone.faces_raccord());;;
        while(curseur)
          {
            Faces& les_faces=curseur.valeur()->faces();
            les_faces.typer(Faces::segment_2D);
            IntTab& sommetsfaces=les_faces.les_sommets();
            int nb_faces=sommetsfaces.dimension(0);
            IntTab nouveaux(2*nb_faces,2);
            les_faces.voisins().resize(2*nb_faces,2);
            les_faces.voisins()=-1;
            for(int i=0; i<nb_faces; i++)
              {
                int i0=sommetsfaces(i,0);
                int i1=sommetsfaces(i,1);
                int i01=-1;
                for (int ii=0 ; ii<nbs+oldsz+j ; ii++)
                  if ( fait_sommet_arete(ii,0)==i0 && fait_sommet_arete(ii,1)==i1 ) i01=nbs+oldsz+ii ;
                assert(i01>=0);
                nouveaux(2*i  ,0)=i0;
                nouveaux(2*i  ,1)=i01;
                nouveaux(2*i+1,0)=i01;
                nouveaux(2*i+1,1)=i1;
              }
            sommetsfaces.ref(nouveaux);
            ++curseur;
          }
      }
      {
        Cerr << "Splitting of the internal faces" << finl;
        LIST_CURSEUR(Faces_Interne) curseur(zone.faces_int());;;
        while(curseur)
          {
            Faces& les_faces=curseur->faces();
            les_faces.typer(Faces::segment_2D);
            IntTab& sommetsfaces=les_faces.les_sommets();
            int nb_faces=sommetsfaces.dimension(0);
            IntTab nouveaux(2*nb_faces,2);
            les_faces.voisins().resize(2*nb_faces,2);
            les_faces.voisins()=-1;
            for(int i=0; i<nb_faces; i++)
              {
                int i0=sommetsfaces(i,0);
                int i1=sommetsfaces(i,1);
                int i01=-1;
                for (int ii=0 ; ii<nbs+oldsz+j ; ii++)
                  if ( fait_sommet_arete(ii,0)==i0 && fait_sommet_arete(ii,1)==i1 ) i01=nbs+oldsz+ii ;
                assert(i01>=0);
                nouveaux(2*i  ,0)=i0;
                nouveaux(2*i  ,1)=i01;
                nouveaux(2*i+1,0)=i01;
                nouveaux(2*i+1,1)=i1;
              }
            sommetsfaces.ref(nouveaux);
            ++curseur;
          }
      }
    }
  else
    {
      Cerr << "We do not yet know how to Trianguler_fin the "
           << zone.type_elem()->que_suis_je() <<"s"<<finl;
      exit();
    }
}
Member Data Documentation
const Type_info Trianguler_fin::info_obj [static]
Reimplemented from Triangulation_base.
Definition at line 44 of file Trianguler_fin.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Trianguler_fin.h
src/Kernel/Geometrie/Trianguler_fin.cpp