TRUST: Zone_Cl_dis_base Class Reference
Zone_Cl_dis_base Class Reference abstract
classe Zone_Cl_dis_base
Les objets Zone_Cl_dis_base representent les conditions aux limites
discretisees. Zone_Cl_dis_base est un morceau d'equation donc elle
herite de MorEqn, c'est grace a cet heritage que chaque objet
Zone_Cl_dis_base contient une reference vers l'equation a laquelle il
se rapporte. Les conditions aux limites discretisees representent les
conditions aux limites de la zone discretisee associee a l'equation
reference par Zone_Cl_dis_base.
Zone_Cl_dis_base a un membre representant les conditions aux limites.
#include <Zone_Cl_dis_base.h>
Public Member Functions
Zone_Cl_dis_base ()
~Zone_Cl_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Cond_lim & les_conditions_limites (int) const
Renvoie la i-ieme condition aux limites.
(version const)
Cond_lim & les_conditions_limites (int)
Renvoie la i-ieme condition aux limites.
Conds_lim & les_conditions_limites ()
Renvoie le tableaux des conditions aux limites.
const Conds_lim & les_conditions_limites () const
Renvoie le tableaux des conditions aux limites.
(version const)
int nb_cond_lim () const
Renvoie le nombre de conditions aux limites.
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de toutes les conditions
aux limites.
virtual void mettre_a_jour_ss_pas_dt (double temps)
Effectue une mise a jour pour des sous pas de temps
d'un schema en temps (par exemple dans RungeKutta)
pour toutes les Cond Lims renvoyant 1 par le biais de la methode
int Cond_Lim_base::a_mettre_a_jour_ss_pas_dt();.
void completer ()
Appel Cond_lim_base::completer() sur chaque
condition aux limites.
int contient_Cl (const Nom &)
Renvoie 1 si l'objet contient une condition aux limites
du Nom specifie.
Renvoie 0 sinon.
Zone_dis & zone_dis ()
Renvoie une reference sur la zone discretisee associee aux conditions
aux limites. Cette Zone_dis est associee au travers de l'equation
associee et pas directement a l'objet Zone_Cl_dis_base.
const Zone_dis & zone_dis () const
Renvoie une reference sur la zone discretisee associee aux conditions
aux limites. Cette Zone_dis est associee au travers de l'equation
associee et pas directement a l'objet Zone_Cl_dis_base.
(version const)
Zone & zone ()
const Zone & zone () const
virtual int calculer_coeffs_echange (double temps)
Calcul des coefficients d'echange pour les problemes couples thermiques.
virtual void imposer_cond_lim (Champ_Inc &, double)=0
int nb_faces_Cl () const
virtual const Cond_lim & la_cl_de_la_face (int num_face) const
A partir d'un indice de face de bord dans la Zone_VF,
renvoie la condition aux limites a laquelle cette face
appartient, pour 0 <= num_face < nb_faces_Cl().
const Cond_lim_base & condition_limite_de_la_face_reelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_face_virtuelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere) const
Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere)
void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de toutes les CLs.
void Gpoint (double t1, double t2)
void set_temps_defaut (double temps)
Change le i-eme temps futur de toutes les CLs.
int avancer (double temps)
Tourne la roue des CLs jusqu'au temps donne.
int reculer (double temps)
Tourne la roue des CLsj usqu'au temps donne.
virtual int initialiser (double temps)
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
virtual void associer_inconnue (const Champ_Inc &)
virtual const Champ_Inc & inconnue () const
virtual Champ_Inc & inconnue ()
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Zone_Cl_dis_base & self_cast (Objet_U &)
static const Zone_Cl_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
virtual void completer (const Zone_dis &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom nom_
Conds_lim les_conditions_limites_
Ref_Champ_Inc mon_inconnue
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
classe Zone_Cl_dis_base
Les objets Zone_Cl_dis_base representent les conditions aux limites
discretisees. Zone_Cl_dis_base est un morceau d'equation donc elle
herite de MorEqn, c'est grace a cet heritage que chaque objet
Zone_Cl_dis_base contient une reference vers l'equation a laquelle il
se rapporte. Les conditions aux limites discretisees representent les
conditions aux limites de la zone discretisee associee a l'equation
reference par Zone_Cl_dis_base.
Zone_Cl_dis_base a un membre representant les conditions aux limites.
Definition at line 45 of file Zone_Cl_dis_base.h.
Constructor & Destructor Documentation
Zone_Cl_dis_base()
Zone_Cl_dis_base::Zone_Cl_dis_base ()
Definition at line 25 of file Zone_Cl_dis_base.cpp.
~Zone_Cl_dis_base()
Zone_Cl_dis_base::~Zone_Cl_dis_base () override
Definition at line 25 of file Zone_Cl_dis_base.cpp.
Member Function Documentation
associer_inconnue()
void Zone_Cl_dis_base::associer_inconnue (const Champ_Inc & inco) virtual
Definition at line 653 of file Zone_Cl_dis_base.cpp.
{
  mon_inconnue=inco;
}
References mon_inconnue.
avancer()
int Zone_Cl_dis_base::avancer (double temps)
Tourne la roue des CLs jusqu'au temps donne.
Definition at line 266 of file Zone_Cl_dis_base.cpp.
{
  int ok=1;
  for (int j=0; j<nb_cond_lim(); j++)
    ok = ok && les_conditions_limites_[j]->avancer(temps);
  return ok;
}
References avancer(), les_conditions_limites_, and nb_cond_lim().
Referenced by avancer().
calculer_coeffs_echange()
int Zone_Cl_dis_base::calculer_coeffs_echange (double temps) virtual
Calcul des coefficients d'echange pour les problemes couples thermiques.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Definition at line 374 of file Zone_Cl_dis_base.cpp.
{
  les_conditions_limites_.calculer_coeffs_echange(temps);
  return 1;
}
References Conds_lim::calculer_coeffs_echange(), and les_conditions_limites_.
changer_temps_futur()
void Zone_Cl_dis_base::changer_temps_futur (double temps, int i)
Change le i-eme temps futur de toutes les CLs.
Definition at line 250 of file Zone_Cl_dis_base.cpp.
{
  for (int j=0; j<nb_cond_lim(); j++)
    les_conditions_limites_[j]->changer_temps_futur(temps,i);
}
References changer_temps_futur(), les_conditions_limites_, and nb_cond_lim().
Referenced by changer_temps_futur().
completer() [1/2]
void Zone_Cl_dis_base::completer (void)
Appel Cond_lim_base::completer() sur chaque
condition aux limites.
Definition at line 395 of file Zone_Cl_dis_base.cpp.
{
  les_conditions_limites_.completer(zone_dis());
  completer(zone_dis());
}
References completer(), Conds_lim::completer(), les_conditions_limites_, and zone_dis().
Referenced by completer().
completer() [2/2]
virtual void Zone_Cl_dis_base::completer (const Zone_dis &) protected pure virtual
Implemented in Zone_Cl_EF, Zone_Cl_PolyMAC, Zone_Cl_VDF, and Zone_Cl_VEF.
condition_limite_de_la_face_reelle()
const Cond_lim_base & Zone_Cl_dis_base::condition_limite_de_la_face_reelle (int face_globale, int & face_locale) const
< la face ne porte pas de CL
< Pour compilo
Definition at line 405 of file Zone_Cl_dis_base.cpp.
{
  for (int i=0; i<nb_cond_lim(); i++)
    {
      const Frontiere& fr=les_conditions_limites(i).frontiere_dis().frontiere();
      if (face_globale>=fr.num_premiere_face() && face_globale < fr.num_premiere_face()+fr.nb_faces())
        {
          face_locale=face_globale-fr.num_premiere_face();
          return les_conditions_limites(i).valeur();
        }
    }
  assert(0); //!< la face ne porte pas de CL
  return les_conditions_limites(0).valeur(); //!< Pour compilo
}
References les_conditions_limites(), nb_cond_lim(), Frontiere::nb_faces(), and Frontiere::num_premiere_face().
Referenced by Champ_Face_get_val_imp_face_bord(), and Champ_Face_get_val_imp_face_bord_sym().
condition_limite_de_la_face_virtuelle()
const Cond_lim_base & Zone_Cl_dis_base::condition_limite_de_la_face_virtuelle (int face_globale, int & face_locale) const
< la face ne porte pas de CL
< Pour compilo
Definition at line 425 of file Zone_Cl_dis_base.cpp.
{
  for (int i=0; i<nb_cond_lim(); i++)
    {
      const Frontiere& fr=les_conditions_limites(i).frontiere_dis().frontiere();
      const ArrOfInt& faces_virt=fr.get_faces_virt();
      for (int j=0; j<faces_virt.size_array(); j++)
        if (face_globale==faces_virt[j])
          {
            face_locale=fr.nb_faces()+j;
            return les_conditions_limites(i).valeur();
          }
    }
  assert(0); //!< la face ne porte pas de CL
  return les_conditions_limites(0).valeur(); //!< Pour compilo
}
References Frontiere::get_faces_virt(), les_conditions_limites(), nb_cond_lim(), Frontiere::nb_faces(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Champ_Face_get_val_imp_face_bord(), and Champ_Face_get_val_imp_face_bord_sym().
condition_limite_de_la_frontiere() [1/2]
Cond_lim_base & Zone_Cl_dis_base::condition_limite_de_la_frontiere (Nom frontiere)
< Aucune frontiere de ce nom
< Pour compilo
Definition at line 445 of file Zone_Cl_dis_base.cpp.
{
  for (int i=0; i<nb_cond_lim(); i++)
    {
      const Frontiere& fr=les_conditions_limites(i).frontiere_dis().frontiere();
      if (fr.le_nom()==frontiere)
        return les_conditions_limites(i).valeur();
    }
  assert(0); //!< Aucune frontiere de ce nom
  exit();
  return les_conditions_limites(0).valeur(); //!< Pour compilo
}
References Process::exit(), Frontiere::le_nom(), les_conditions_limites(), and nb_cond_lim().
condition_limite_de_la_frontiere() [2/2]
const Cond_lim_base & Zone_Cl_dis_base::condition_limite_de_la_frontiere (Nom frontiere) const
< Aucune frontiere de ce nom
< Pour compilo
Definition at line 461 of file Zone_Cl_dis_base.cpp.
{
  for (int i=0; i<nb_cond_lim(); i++)
    {
      const Frontiere& fr=les_conditions_limites(i).frontiere_dis().frontiere();
      if (fr.le_nom()==frontiere)
        return les_conditions_limites(i).valeur();
    }
  assert(0); //!< Aucune frontiere de ce nom
  exit();
  return les_conditions_limites(0).valeur(); //!< Pour compilo
}
References Process::exit(), Frontiere::le_nom(), les_conditions_limites(), and nb_cond_lim().
contient_Cl()
int Zone_Cl_dis_base::contient_Cl (const Nom & type)
Renvoie 1 si l'objet contient une condition aux limites
du Nom specifie.
Renvoie 0 sinon.
Returns
int
Signification: 1 si la condition aux limites de nom specifie a ete
trouve, 0 sinon.
Contraintes:
Definition at line 192 of file Zone_Cl_dis_base.cpp.
{
  for(int i=0; i< les_conditions_limites_.size(); i++)
    if(les_conditions_limites_[i].get_info()->has_base(type))
      return 1;
  return 0;
}
References get_info(), les_conditions_limites_, and vect_impl::size().
get_info()
const Type_info * Zone_Cl_dis_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Zone_Cl_VEFP1B, Zone_Cl_PolyMAC, Zone_Cl_VDF, and Zone_Cl_VEF.
Definition at line 25 of file Zone_Cl_dis_base.cpp.
Referenced by contient_Cl().
Gpoint()
void Zone_Cl_dis_base::Gpoint (double t1, double t2)
Definition at line 478 of file Zone_Cl_dis_base.cpp.
{
  for (int i=0; i<nb_cond_lim(); i++)
    {
      Champ_front_base& champ=les_conditions_limites(i)->champ_front().valeur();
      if (sub_type(Champ_front_var_instationnaire,champ))
        {
          Champ_front_var_instationnaire& champ_insta=ref_cast(Champ_front_var_instationnaire,champ);
          champ_insta.Gpoint(t1,t2);
        }
      if (sub_type(Champ_front_instationnaire_base,champ))
        {
          Champ_front_instationnaire_base& champ_insta=ref_cast(Champ_front_instationnaire_base,champ);
          champ_insta.Gpoint(t1,t2);
        }
    }
}
References Champ_front_instationnaire_base::Gpoint(), Champ_front_var_instationnaire::Gpoint(), les_conditions_limites(), nb_cond_lim(), ref_cast, and sub_type.
imposer_cond_lim()
virtual void Zone_Cl_dis_base::imposer_cond_lim (Champ_Inc & , double) pure virtual
Implemented in Zone_Cl_EF, Zone_Cl_VEFP1B, Zone_Cl_PolyMAC, Zone_Cl_VDF, and Zone_Cl_VEF.
Referenced by Zone_Cl_dis::imposer_cond_lim().
inconnue() [1/2]
Champ_Inc & Zone_Cl_dis_base::inconnue () virtual
Definition at line 663 of file Zone_Cl_dis_base.cpp.
{
  return mon_inconnue;
}
References mon_inconnue.
inconnue() [2/2]
const Champ_Inc & Zone_Cl_dis_base::inconnue () const virtual
Definition at line 658 of file Zone_Cl_dis_base.cpp.
{
  return mon_inconnue;
}
References mon_inconnue.
info()
const Type_info * Zone_Cl_dis_base::info () static
Definition at line 25 of file Zone_Cl_dis_base.cpp.
initialiser()
int Zone_Cl_dis_base::initialiser (double temps) virtual
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Returns
int
Signification: 1 si OK, 0 sinon
Contraintes:
Reimplemented in Zone_Cl_EF, Zone_Cl_PolyMAC, and Zone_Cl_VEF.
Definition at line 353 of file Zone_Cl_dis_base.cpp.
{
  return les_conditions_limites_.initialiser(temps);
}
References Conds_lim::initialiser(), and les_conditions_limites_.
Referenced by Zone_Cl_EF::initialiser(), Zone_Cl_PolyMAC::initialiser(), and Zone_Cl_VEF::initialiser().
la_cl_de_la_face()
const Cond_lim & Zone_Cl_dis_base::la_cl_de_la_face (int num_face) const virtual
A partir d'un indice de face de bord dans la Zone_VF,
renvoie la condition aux limites a laquelle cette face
appartient, pour 0 <= num_face < nb_faces_Cl().
Reimplemented in Zone_Cl_VDF.
Definition at line 619 of file Zone_Cl_dis_base.cpp.
{
// Algorithme generique: on parcourt les bords jusqu'a trouver
// celui qui contient la face.
// Les faces du bord 0, puis celle du bord 1, etc... se suivent
// dans la Zone_VF.
  assert(num_face >= 0);
  int i = 0;
  const int nb_cl = les_conditions_limites_.size();
  for (i = 0; i < nb_cl; i++)
    {
      const Cond_lim_base& cl = les_conditions_limites_[i].valeur();
      const Frontiere&      fr = cl.frontiere_dis().frontiere();
      int num_premiere_face = fr.num_premiere_face();
      int nb_faces          = fr.nb_faces();
      if (num_face >= num_premiere_face && num_face < num_premiere_face + nb_faces)
        break;
    }
  if (i == nb_cl)
    {
      Cerr << "Error in Zone_Cl_dis_base::la_cl_de_la_face(num_face="
           << num_face << ")\n This face is not on a boundary of cond_lim."
           << finl;
      exit();
    }
  return les_conditions_limites_[i];
}
References Cerr, Process::exit(), finl, Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), les_conditions_limites_, Frontiere::nb_faces(), Frontiere::num_premiere_face(), and vect_impl::size().
le_nom()
const Nom & Zone_Cl_dis_base::le_nom () const inline override virtual
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
Nom&
Signification: le nom de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 99 of file Zone_Cl_dis_base.h.
{
  return nom_;
}
References nom_.
les_conditions_limites() [1/4]
Conds_lim & Zone_Cl_dis_base::les_conditions_limites ()
Renvoie le tableaux des conditions aux limites.
Returns
Conds_lim&
Signification: le tableau des conditions aux limites
Contraintes:
Definition at line 555 of file Zone_Cl_dis_base.cpp.
{
  return les_conditions_limites_;
}
References les_conditions_limites_.
Referenced by condition_limite_de_la_face_reelle(), condition_limite_de_la_face_virtuelle(), condition_limite_de_la_frontiere(), Gpoint(), Zone_Cl_EF::imposer_cond_lim(), Zone_Cl_VEFP1B::imposer_cond_lim(), Zone_Cl_PolyMAC::imposer_cond_lim(), Zone_Cl_VDF::imposer_cond_lim(), Zone_Cl_VEF::imposer_cond_lim(), Zone_Cl_EF::imposer_symetrie_partiellement(), and readOn().
les_conditions_limites() [2/4]
const Conds_lim & Zone_Cl_dis_base::les_conditions_limites () const
Renvoie le tableaux des conditions aux limites.
(version const)
Returns
Conds_lim&
Signification: le tableau des conditions aux limites
Contraintes: reference constante
Definition at line 576 of file Zone_Cl_dis_base.cpp.
{
  return les_conditions_limites_;
}
References les_conditions_limites_.
les_conditions_limites() [3/4]
Cond_lim & Zone_Cl_dis_base::les_conditions_limites (int i)
Renvoie la i-ieme condition aux limites.
Returns
Cond_lim&
Signification: la i-ieme condition aux limites
Contraintes:
Definition at line 535 of file Zone_Cl_dis_base.cpp.
{
  return les_conditions_limites_[i];
}
References les_conditions_limites_.
les_conditions_limites() [4/4]
const Cond_lim & Zone_Cl_dis_base::les_conditions_limites (int i) const
Renvoie la i-ieme condition aux limites.
(version const)
Returns
Cond_lim&
Signification: la i-ieme condition aux limites
Contraintes: reference constante
Definition at line 515 of file Zone_Cl_dis_base.cpp.
{
  return les_conditions_limites_[i];
}
References les_conditions_limites_.
Referenced by Op_Grad_EF::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Source_Generique_VEF::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Div_PolyMAC::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), ajouter_bord(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Fluide_Dilatable_VDF_Proto::ajouter_impl(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Solveur_Masse_EF::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Assembleur_P_PolyMAC::assembler_continuite(), Assembleur_P_EF::assembler_mat(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), assemblerP0P1(), assemblerP0Pa(), assemblerP1P1(), assemblerP1Pa(), assemblerPaPa(), Op_Diff_VEFP1NCP1B_Face::associer(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Op_Dift_standard_VEF_Face::calcul_divergence(), Champ_P1NC::calcul_duidxj_paroi(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::calculer_data_pour_dirichlet(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Conv_EF_VEF_P1NC_Stab::calculer_flux_bords(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), calculer_gradientP1NC(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Dift_Stab_VEF_Face::calculer_min(), Operateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Traitement_particulier_NS_Brech_VEF::calculer_terme_destruction_K(), Traitement_particulier_NS_Brech_VEF::calculer_terme_production_K(), Equation_base::completer(), Terme_Source_Canal_perio::completer(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Champ_P1iP1B_implementation::completer(), Terme_Source_Canal_perio::compute_heat_flux(), Champ_front_fonc_gradient::condition_limite(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Masse_PolyMAC_Face::corriger_solution(), Zone_VDF::creer_elements_fictifs(), Op_EF_base::dimensionner(), Op_VDF_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Equation_base::ecrire_fichier_xyz(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Champ_Generique_Tparoi_VEF::get_champ(), Op_Grad_VEF_P1B_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), Op_Div_PolyMAC::impr(), Op_Div_PolyMAC_P0::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEF_Elem::impr(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Op_Diff_VDF_base::init_op_ext(), Op_Diff_PolyMAC_P0_Elem::init_s_dist(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Zone_Cl_dis::les_conditions_limites(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Assembleur_P_VDF::liste_faces_periodiques(), Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite(), Op_Conv_EF_VEF_P1NC_Stab::mettre_a_jour_pour_periodicite(), modif_matrice_pour_periodique_apres_contribuer(), modif_matrice_pour_periodique_avant_contribuer(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), modifieP1P1neumann(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_matrice(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_EF_base::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VDF::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_PolyMAC::modifier_secmem_pour_incr_p(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Terme_Source_Th_TdivU_VEF_Face::modifier_zone_cl(), Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul(), Op_Conv_EF_VEF_P1NC_Stab::reinit_conv_pour_Cl(), Assembleur_P_VEF::remplir(), Assembleur_P_VDF::remplir(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee(), Champ_front_contact_VEF::remplir_faces_coin(), Op_Conv_VEF_Face::remplir_fluent(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), remplir_marqueur_sommet_neumann(), Op_Diff_VEFP1NCP1B_Face::test(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Champ_front_contact_VEF::test_faces_coin(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), Op_Grad_PolyMAC_P0_Face::update_grad(), Op_Diff_PolyMAC_P0_base::update_phif(), updateP0P1(), updateP0Pa(), updateP1P1(), updateP1Pa(), updatePaPa(), Champ_Inc_base::valeur_aux_bords(), Champ_Face::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), Champ_Q1NC::verifie_valeurs_cl(), and Assembleur_P_VEFPreP1B::verifier_dirichlet().
mettre_a_jour()
void Zone_Cl_dis_base::mettre_a_jour (double temps) virtual
Effectue une mise a jour en temps de toutes les conditions
aux limites.
Definition at line 299 of file Zone_Cl_dis_base.cpp.
{
  les_conditions_limites_.mettre_a_jour(temps);
}
References les_conditions_limites_, and Conds_lim::mettre_a_jour().
Referenced by Zone_Cl_dis::mettre_a_jour().
mettre_a_jour_ss_pas_dt()
void Zone_Cl_dis_base::mettre_a_jour_ss_pas_dt (double temps) virtual
Effectue une mise a jour pour des sous pas de temps
d'un schema en temps (par exemple dans RungeKutta)
pour toutes les Cond Lims renvoyant 1 par le biais de la methode
int Cond_Lim_base::a_mettre_a_jour_ss_pas_dt();.
Definition at line 322 of file Zone_Cl_dis_base.cpp.
{
  const int nb_cl = les_conditions_limites_.size();
  for (int i=0; i<nb_cl; i++)
    {
      Cond_lim_base& la_cl = les_conditions_limites_[i].valeur();
      if (la_cl.a_mettre_a_jour_ss_pas_dt()==1)
        {
          la_cl.mettre_a_jour(temps);
        }
    }
}
References Cond_lim_base::a_mettre_a_jour_ss_pas_dt(), les_conditions_limites_, Cond_lim_base::mettre_a_jour(), and vect_impl::size().
nb_cond_lim()
int Zone_Cl_dis_base::nb_cond_lim () const
Renvoie le nombre de conditions aux limites.
Returns
int
Signification: le nombre de conditions aux limites
Contraintes:
Definition at line 596 of file Zone_Cl_dis_base.cpp.
{
  return les_conditions_limites_.size();
}
References les_conditions_limites_, and vect_impl::size().
Referenced by Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Solveur_Masse_EF::appliquer_impl(), Op_Diff_VEFP1NCP1B_Face::associer(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), avancer(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::calculer_data_pour_dirichlet(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Conv_EF_VEF_P1NC_Stab::calculer_flux_bords(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), changer_temps_futur(), Champ_front_fonc_gradient::condition_limite(), condition_limite_de_la_face_reelle(), condition_limite_de_la_face_virtuelle(), condition_limite_de_la_frontiere(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), Op_EF_base::dimensionner(), Gpoint(), Zone_Cl_EF::imposer_cond_lim(), Zone_Cl_VEFP1B::imposer_cond_lim(), Zone_Cl_PolyMAC::imposer_cond_lim(), Zone_Cl_VDF::imposer_cond_lim(), Zone_Cl_VEF::imposer_cond_lim(), Zone_Cl_EF::imposer_symetrie_partiellement(), Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite(), Op_Conv_EF_VEF_P1NC_Stab::mettre_a_jour_pour_periodicite(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VDF::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Zone_Cl_dis::nb_cond_lim(), reculer(), Op_Conv_EF_VEF_P1NC_Stab::reinit_conv_pour_Cl(), set_temps_defaut(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), Champ_Face::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), and Champ_Q1NC::verifie_valeurs_cl().
nb_faces_Cl()
int Zone_Cl_dis_base::nb_faces_Cl () const
Definition at line 601 of file Zone_Cl_dis_base.cpp.
{
  return zone().nb_faces_frontiere();
}
References Zone::nb_faces_frontiere(), and zone().
Referenced by Assembleur_P_EF::assembler_mat(), Zone_Cl_dis::nb_faces_Cl(), and Assembleur_P_VEF::remplir().
nommer()
void Zone_Cl_dis_base::nommer (const Nom &) override virtual
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
Reimplemented from Objet_U.
Definition at line 648 of file Zone_Cl_dis_base.cpp.
{
  nom_ = un_nom;
}
References nom_.
printOn()
Sortie & Zone_Cl_dis_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Zone_Cl_VEFP1B, Zone_Cl_PolyMAC, Zone_Cl_VDF, and Zone_Cl_VEF.
Definition at line 45 of file Zone_Cl_dis_base.cpp.
{
  return os;
}
Referenced by Zone_Cl_VDF::printOn().
readOn()
Entree & Zone_Cl_dis_base::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Zone_Cl_VEFP1B, Zone_Cl_PolyMAC, Zone_Cl_VDF, and Zone_Cl_VEF.
Definition at line 71 of file Zone_Cl_dis_base.cpp.
{
  assert(mon_equation.non_nul());
  const Zone& lazone=equation().zone_dis()->zone();
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Nom nomlu;
  Motcle motlu;
  is >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "Error while reading the boundaries conditions\n";
      Cerr << "We expected a " << accolade_ouverte << " instead of \n"
           << motlu;
      exit();
    }
  int n = lazone.nb_front_Cl();
  IntTab front_deja_lu(n);
  front_deja_lu = 0;
  les_conditions_limites().dimensionner(n);
  int nb_clim=0;
  while(1)
    {
// lecture d'un nom de bord ou de }
      is >> nomlu;
      motlu=nomlu;
      if (motlu == accolade_fermee)
        break;
      Cerr << "Reading the " << nomlu << " boundary condition of the " << equation().que_suis_je() << " equation from the problem " << equation().probleme().le_nom() << finl;
      Journal()<< "Reading the boundary condition " << nomlu <<finl;
      int rang=lazone.rang_frontiere(nomlu);
// Test supplementaire sur les conditions aux limites qui ont ete lues :
// on test si deux frontieres ont le meme nom
      if (front_deja_lu(rang) == 0)
        front_deja_lu(rang) = 1;
      else
        {
          Cerr <<finl;
          Cerr <<"Error in the data set "<<finl;
          Cerr <<"the boundary condition associated"<<finl;
          Cerr <<"to the boundary "<< nomlu <<"is read twice !!"<<finl;
          exit();
        }
// const Frontiere& frontiere=zone.frontiere(rang);
      is >> les_conditions_limites(rang);
// Si on avait une condition_limite_utilisateur
// Il faut recuperer la cl stockee dans celle ci
// la copier et detruire celle contenue dans la cond_utilisateur
      if (sub_type(Cond_lim_utilisateur_base,les_conditions_limites(rang).valeur()))
        {
          Cond_lim_utilisateur_base& la_cl=ref_cast(Cond_lim_utilisateur_base,les_conditions_limites(rang).valeur());
          la_cl.lire(is,equation(),nomlu);
          Cond_lim* sa=&(la_cl.la_cl());
// WEC : La nouvelle formulation evite la copie de l'objet Cond_lim_base
// Cette copie peut poser probleme aux champs qui s'enregistrent dans un vecteur
// (Champ_Inputs). Le vecteur pointe sur n'importe quoi...
// Adopte la nouvelle et detruit l'ancienne (Cond_lim_utilisateur)
          les_conditions_limites(rang).adopt(*sa);
// les_conditions_limites(rang)=(*sa);
          delete sa;
        }
      les_conditions_limites(rang)->
      associer_fr_dis_base(zone_dis().frontiere_dis(rang));
// Test pour empecher l utilisation de 'Raccord_distant_homogene' en calcul sequentiel
      const Frontiere& frontiere=lazone.frontiere(rang);
      if ((frontiere.que_suis_je()=="Raccord_distant_homogene") && (Process::nproc()==1))
        {
          Cerr<<"At least one connection (adjacent boundary on two domains) is of type 'Raccord distant homogene'." << finl;
          Cerr<<"Use 'Raccord local homogene' to define the connections in sequential computing"<<finl;
          Cerr<<"And 'Raccord distant homogene' for the connections in parallel computing." << finl;
          exit();
        }
      nb_clim++;
    }
  if (nb_clim!=n)
    {
      zone_dis()->ecrire_noms_bords(Cerr);
      Cerr << "It misses " << n-nb_clim << " boundaries conditions " << finl;
      Cerr << "We read " << nb_clim << " boundaries conditions " << finl;
      Cerr << "We waited " << n << " boundary conditions " << finl;
      exit();
    }
  for (int num_cl=0; num_cl<nb_clim; num_cl++)
    {
      les_conditions_limites(num_cl)->associer_zone_cl_dis_base(*this);
      les_conditions_limites(num_cl)->verifie_ch_init_nb_comp();
// const Frontiere_dis_base& la_fr_dis = les_conditions_limites(num_cl).frontiere_dis();
// const Frontiere& frontiere=la_fr_dis.frontiere();
// const Zone& zone2=frontiere.zone();
    }
  return is;
}
References Cerr, vect_impl::dimensionner(), MorEqn::equation(), Process::exit(), finl, Zone::frontiere(), Process::Journal(), Cond_lim_utilisateur_base::la_cl(), Probleme_base::le_nom(), les_conditions_limites(), Cond_lim_utilisateur_base::lire(), MorEqn::mon_equation, Zone::nb_front_Cl(), O_U_Ptr::non_nul(), Process::nproc(), Equation_base::probleme(), Objet_U::que_suis_je(), Zone::rang_frontiere(), ref_cast, sub_type, valeur(), Zone_dis::zone(), Equation_base::zone_dis(), and zone_dis().
Referenced by Zone_Cl_EF::readOn(), Zone_Cl_PolyMAC::readOn(), Zone_Cl_VDF::readOn(), and Zone_Cl_VEF::readOn().
reculer()
int Zone_Cl_dis_base::reculer (double temps)
Tourne la roue des CLsj usqu'au temps donne.
Definition at line 276 of file Zone_Cl_dis_base.cpp.
{
  int ok=1;
  for (int j=0; j<nb_cond_lim(); j++)
    ok = ok && les_conditions_limites_[j]->reculer(temps);
  return ok;
}
References les_conditions_limites_, nb_cond_lim(), and reculer().
Referenced by reculer().
self_cast() [1/2]
const Zone_Cl_dis_base & Zone_Cl_dis_base::self_cast (const Objet_U & r) static
Definition at line 25 of file Zone_Cl_dis_base.cpp.
self_cast() [2/2]
Zone_Cl_dis_base & Zone_Cl_dis_base::self_cast (Objet_U & r) static
Definition at line 25 of file Zone_Cl_dis_base.cpp.
set_temps_defaut()
void Zone_Cl_dis_base::set_temps_defaut (double temps)
Change le i-eme temps futur de toutes les CLs.
Definition at line 258 of file Zone_Cl_dis_base.cpp.
{
  for (int j=0; j<nb_cond_lim(); j++)
    les_conditions_limites_[j]->set_temps_defaut(temps);
}
References les_conditions_limites_, nb_cond_lim(), and set_temps_defaut().
Referenced by set_temps_defaut().
zone() [1/2]
Zone & Zone_Cl_dis_base::zone ()
Definition at line 606 of file Zone_Cl_dis_base.cpp.
{
  return zone_dis().zone();
}
References Zone_dis::zone(), and zone_dis().
Referenced by Echange_contact_Correlation_VDF::calculer_CL(), Echange_contact_Correlation_VEF::calculer_CL(), Echange_contact_Correlation_VDF::init_tab_echange(), nb_faces_Cl(), and Zone_Cl_dis::zone().
zone() [2/2]
const Zone & Zone_Cl_dis_base::zone () const
Definition at line 610 of file Zone_Cl_dis_base.cpp.
{
  return zone_dis().zone();
}
References Zone_dis::zone(), and zone_dis().
zone_dis() [1/2]
Zone_dis & Zone_Cl_dis_base::zone_dis ()
Renvoie une reference sur la zone discretisee associee aux conditions
aux limites. Cette Zone_dis est associee au travers de l'equation
associee et pas directement a l'objet Zone_Cl_dis_base.
Returns
Zone_dis&
Signification: la zone discretisee associee a l'equation associe
aux conditions aux limites.
Contraintes:
Definition at line 218 of file Zone_Cl_dis_base.cpp.
{
  return equation().zone_dis();
}
References MorEqn::equation(), and Equation_base::zone_dis().
Referenced by BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Echange_contact_VDF::calculer_h_autre_pb(), completer(), Periodique::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Zone_Cl_VEFP1B::imposer_cond_lim(), Zone_Cl_EF::imposer_symetrie(), Zone_Cl_EF::imposer_symetrie_matrice_secmem(), Echange_contact_VDF::initialiser(), Zone_Cl_VEF::initialiser(), readOn(), zone(), Zone_Cl_EF::zone_EF(), Zone_Cl_PolyMAC::zone_PolyMAC(), Zone_Cl_VDF::zone_VDF(), and Zone_Cl_VEF::zone_VEF().
zone_dis() [2/2]
const Zone_dis & Zone_Cl_dis_base::zone_dis () const
Renvoie une reference sur la zone discretisee associee aux conditions
aux limites. Cette Zone_dis est associee au travers de l'equation
associee et pas directement a l'objet Zone_Cl_dis_base.
(version const)
Returns
Zone_dis&
Signification: la zone discretisee associee a l'equation associe
aux conditions aux limites.
Contraintes: reference constante
Definition at line 242 of file Zone_Cl_dis_base.cpp.
{
  return equation().zone_dis();
}
References MorEqn::equation(), and Equation_base::zone_dis().
Member Data Documentation
info_obj
const Type_info Zone_Cl_dis_base::info_obj static
Definition at line 48 of file Zone_Cl_dis_base.h.
les_conditions_limites_
Conds_lim Zone_Cl_dis_base::les_conditions_limites_ protected
Definition at line 94 of file Zone_Cl_dis_base.h.
Referenced by avancer(), calculer_coeffs_echange(), changer_temps_futur(), completer(), Zone_Cl_VDF::completer(), contient_Cl(), initialiser(), Zone_Cl_VEF::initialiser(), la_cl_de_la_face(), Zone_Cl_VDF::la_cl_de_la_face(), les_conditions_limites(), mettre_a_jour(), mettre_a_jour_ss_pas_dt(), Zone_Cl_EF::nb_bord_periodicite(), Zone_Cl_PolyMAC::nb_bord_periodicite(), Zone_Cl_VEF::nb_bord_periodicite(), nb_cond_lim(), Zone_Cl_VDF::nb_faces_sortie_libre(), Zone_Cl_VEF::nb_faces_sortie_libre(), reculer(), Zone_Cl_EF::remplir_type_elem_Cl(), Zone_Cl_VEF::remplir_type_elem_Cl(), Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(), and set_temps_defaut().
mon_inconnue
Ref_Champ_Inc Zone_Cl_dis_base::mon_inconnue protected
Definition at line 95 of file Zone_Cl_dis_base.h.
Referenced by associer_inconnue(), and inconnue().
nom_
Nom Zone_Cl_dis_base::nom_ protected
Definition at line 93 of file Zone_Cl_dis_base.h.
Referenced by le_nom(), and nommer().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Zone_Cl_dis_base.h
src/Kernel/Framework/Zone_Cl_dis_base.cpp