TRUST: Ensemble_Lagrange_base Class Reference
Ensemble_Lagrange_base Class Reference abstract
classe Ensemble_Lagrange_base
Classe de base des classes representant une structure geometrique constituee
d un ensemble de points dont on realise un suivi Lagrangien
Actuellement une seule classe derivant instanciable : Maillage_FT_Disc
-un ensemble Lagrangien est caracterise par les coordonnees de ses points
#include <Ensemble_Lagrange_base.h>
Public Member Functions
~Ensemble_Lagrange_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Ensemble_Lagrange_base ()
virtual void associer_equation_transport (const Equation_base &equation)=0
virtual const Equation_base & equation_associee () const =0
void associer_zone (const Zone &zone)
virtual const Zone & zone () const
void remplir_sommets_tmp (DoubleTab &soms_tmp)
void generer_marqueurs_sz (DoubleTab &soms_tmp)
const IntVect & nb_marqs_par_sz () const
const DoubleTab & sommets_lu () const
DoubleTab & sommets_lu ()
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Ensemble_Lagrange_base & self_cast (Objet_U &)
static const Ensemble_Lagrange_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Noms nom_sz
IntVect nb_marqs_sz
IntTab nb_marqs_par_dir
Ref_Zone ma_zone_
DoubleTab sommets_lu_
Detailed Description
classe Ensemble_Lagrange_base
Classe de base des classes representant une structure geometrique constituee
d un ensemble de points dont on realise un suivi Lagrangien
Actuellement une seule classe derivant instanciable : Maillage_FT_Disc
-un ensemble Lagrangien est caracterise par les coordonnees de ses points
Definition at line 37 of file Ensemble_Lagrange_base.h.
Constructor & Destructor Documentation
~Ensemble_Lagrange_base()
Ensemble_Lagrange_base::~Ensemble_Lagrange_base () override
Definition at line 20 of file Ensemble_Lagrange_base.cpp.
Ensemble_Lagrange_base()
Ensemble_Lagrange_base::Ensemble_Lagrange_base ()
Definition at line 22 of file Ensemble_Lagrange_base.cpp.
{
  nb_marqs_sz.resize(0);
  nb_marqs_par_dir.resize(0,0);
}
References nb_marqs_par_dir, nb_marqs_sz, TRUSTTab< _TYPE_ >::resize(), and TRUSTVect< _TYPE_ >::resize().
Member Function Documentation
associer_equation_transport()
virtual void Ensemble_Lagrange_base::associer_equation_transport (const Equation_base & equation) pure virtual
associer_zone()
void Ensemble_Lagrange_base::associer_zone (const Zone & zone)
Definition at line 38 of file Ensemble_Lagrange_base.cpp.
{
  ma_zone_=une_zone;
}
References ma_zone_.
Referenced by Marqueur_Lagrange_base::discretiser().
equation_associee()
virtual const Equation_base & Ensemble_Lagrange_base::equation_associee () const pure virtual
generer_marqueurs_sz()
void Ensemble_Lagrange_base::generer_marqueurs_sz (DoubleTab & soms_tmp)
Definition at line 72 of file Ensemble_Lagrange_base.cpp.
{
  const Zone& mazone = ma_zone_.valeur();
  const Domaine& dom = mazone.domaine();
  int nb_sz,nb_marq_sz, old_size, dim;
  soms_tmp.resize(0);
  dim=Objet_U::dimension;
  nb_sz=nb_marqs_sz.size();
  for (int i=0; i<nb_sz; i++)
    {
      const Nom& nom = nom_sz[i];
      const Sous_Zone& sz = dom.ss_zone(nom);
      int nb_elem = sz.nb_elem_tot();
      int nb_som = mazone.nb_som_elem();
      int le_poly,poly,le_som;
      double xmoy,ymoy,zmoy,deltax,deltay,deltaz;
      double xmin,xmax,ymin,ymax,zmin,zmax;
      xmin = ymin = zmin = 1.e8;
      xmax = ymax = zmax= -1.e8;
      if (dim==2)
        {
          zmin = zmax = 0.;
        }
// Etape 1 : On determine le min et max en tenant compte de tous les processeurs
      if (nb_elem!=0)
        {
          poly = sz(0);
          le_som = 0;
          xmin=dom.coord(mazone.sommet_elem(poly,le_som),0);
          ymin=dom.coord(mazone.sommet_elem(poly,le_som),1);
          if (dim==3)
            zmin=dom.coord(mazone.sommet_elem(poly,le_som),2);
          xmax=xmin;
          ymax=ymin;
          if (dim==3)
            zmax=zmin;
          for (le_poly=0; le_poly<nb_elem; le_poly++)
            for(le_som=0; le_som<nb_som; le_som++)
              {
                poly = sz(le_poly);
                xmin=std::min(xmin,dom.coord(mazone.sommet_elem(poly,le_som),0));
                ymin=std::min(ymin,dom.coord(mazone.sommet_elem(poly,le_som),1));
                if (dim==3)
                  zmin=std::min(zmin,dom.coord(mazone.sommet_elem(poly,le_som),2));
                xmax=std::max(xmax,dom.coord(mazone.sommet_elem(poly,le_som),0));
                ymax=std::max(ymax,dom.coord(mazone.sommet_elem(poly,le_som),1));
                if (dim==3)
                  zmax=std::max(zmax,dom.coord(mazone.sommet_elem(poly,le_som),2));
              }
        } //Fin if (nb_elem!=0)
      xmin = Process::mp_min(xmin);
      xmax = Process::mp_max(xmax);
      ymin = Process::mp_min(ymin);
      ymax = Process::mp_max(ymax);
      if (dim==3)
        {
          zmin = Process::mp_min(zmin);
          zmax = Process::mp_max(zmax);
        }
// Etape 2 : Le processeur maitre va calculer les coordonnees des particules
      if (je_suis_maitre())
        {
          xmoy = (xmax+xmin)/2.;
          ymoy = (ymax+ymin)/2.;
          zmoy = (zmax+zmin)/2.;
          deltax = (xmax-xmin)/2.;
          deltay = (ymax-ymin)/2.;
          deltaz = (zmax-zmin)/2.;
          nb_marq_sz = nb_marqs_sz(i);
          old_size = soms_tmp.dimension(0);
          soms_tmp.resize(old_size+nb_marq_sz,dim);
          int marq;
// Cas d une distribution aleatoire
          if (nb_marqs_par_dir(i,0)==0)
            {
// double a,b,c;
              srand48(1);
              for (marq=0; marq<nb_marq_sz; marq++)
                {
                  soms_tmp(old_size+marq,0) = xmoy + deltax*(-1.+2.*drand48());
                  soms_tmp(old_size+marq,1) = ymoy + deltay*(-1.+2.*drand48());
                  if (dim==3)
                    soms_tmp(old_size+marq,2) = zmoy + deltaz*(-1.+2.*drand48());
                }
            }
// Cas d une distribution uniforme
          else
            {
              double dx, dy, dz;
              int nx_max = nb_marqs_par_dir(i,0);
              int ny_max = nb_marqs_par_dir(i,1);
              dx = 2.*deltax/double(nx_max+1);
              dy = 2.*deltay/double(ny_max+1);
              if (dim==2)
                {
                  for (int ny=1; ny<ny_max+1; ny++)
                    for (int nx=1; nx<nx_max+1; nx++)
                      {
                        marq = nx + (ny-1)*nx_max-1;
                        soms_tmp(old_size+marq,0) = xmin + nx*dx;
                        soms_tmp(old_size+marq,1) = ymin + ny*dy;
                      }
                }
              else if (dim==3)
                {
                  int nz_max = nb_marqs_par_dir(i,2);
                  dz = 2.*deltaz/double(nz_max+1);
                  for (int nz=1; nz<nz_max+1; nz++)
                    for (int ny=1; ny<ny_max+1; ny++)
                      for (int nx=1; nx<nx_max+1; nx++)
{
                          marq = nx + (ny-1)*nx_max + (nz-1)*nx_max*ny_max-1;
                          soms_tmp(old_size+marq,0) = xmin + nx*dx;
                          soms_tmp(old_size+marq,1) = ymin + ny*dy;
                          soms_tmp(old_size+marq,2) = zmin + nz*dz;
                        }
                }
            }
        }//Fin de if je_suis_maitre()
// Etape 3 : Le processeur maitre envoie les valeurs des coordonnees calculees (soms_tmp)
// aux autres processeurs
      if (je_suis_maitre())
        for(int p=1; p<Process::nproc(); p++)
          envoyer(soms_tmp,0, p, 0);
      for(int p=1; p<Process::nproc(); p++)
        recevoir(soms_tmp,0,p,0);
    }
}
References Domaine::coord(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), envoyer(), Process::je_suis_maitre(), ma_zone_, Process::mp_max(), Process::mp_min(), Sous_Zone::nb_elem_tot(), nb_marqs_par_dir, nb_marqs_sz, Zone::nb_som_elem(), nom_sz, Process::nproc(), recevoir(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), Zone::sommet_elem(), Domaine::ss_zone(), and Ref_Zone::valeur().
Referenced by remplir_sommets_tmp().
get_info()
const Type_info * Ensemble_Lagrange_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 20 of file Ensemble_Lagrange_base.cpp.
info()
const Type_info * Ensemble_Lagrange_base::info () static
Definition at line 20 of file Ensemble_Lagrange_base.cpp.
nb_marqs_par_sz()
const IntVect & Ensemble_Lagrange_base::nb_marqs_par_sz () const inline
Definition at line 73 of file Ensemble_Lagrange_base.h.
{
  return nb_marqs_sz;
}
References nb_marqs_sz.
Referenced by remplir_sommets_tmp().
printOn()
Sortie & Ensemble_Lagrange_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 28 of file Ensemble_Lagrange_base.cpp.
{
  return os;
}
readOn()
Entree & Ensemble_Lagrange_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 33 of file Ensemble_Lagrange_base.cpp.
{
  return is;
}
remplir_sommets_tmp()
void Ensemble_Lagrange_base::remplir_sommets_tmp (DoubleTab & soms_tmp)
Definition at line 43 of file Ensemble_Lagrange_base.cpp.
{
// Premier cas : les sommets ont ete lus dans un fichier
// On copie sommets_lu_ dans un tableau temporaire sommets_tmp
  if (sommets_lu_.dimension(0)!=0)
    {
      const DoubleTab& som_lu = sommets_lu() ;
      int dim0=som_lu.dimension(0);
      int dim1=som_lu.dimension(1);
      soms_tmp.resize(dim0,dim1);
      soms_tmp = som_lu;
    }
  else if (nb_marqs_par_sz().size()!=0)
// Deuxieme cas : les sommets sont crees dans des sous zones
// On remplit le tableau temporaire
    generer_marqueurs_sz(soms_tmp);
  else
    soms_tmp.resize(0,0);
}
References TRUSTTab< _TYPE_ >::dimension(), generer_marqueurs_sz(), nb_marqs_par_sz(), TRUSTTab< _TYPE_ >::resize(), sommets_lu(), and sommets_lu_.
self_cast() [1/2]
const Ensemble_Lagrange_base & Ensemble_Lagrange_base::self_cast (const Objet_U & r) static
Definition at line 20 of file Ensemble_Lagrange_base.cpp.
self_cast() [2/2]
Ensemble_Lagrange_base & Ensemble_Lagrange_base::self_cast (Objet_U & r) static
Definition at line 20 of file Ensemble_Lagrange_base.cpp.
sommets_lu() [1/2]
DoubleTab & Ensemble_Lagrange_base::sommets_lu () inline
Definition at line 83 of file Ensemble_Lagrange_base.h.
{
  return sommets_lu_;
}
References sommets_lu_.
sommets_lu() [2/2]
const DoubleTab & Ensemble_Lagrange_base::sommets_lu () const inline
Definition at line 78 of file Ensemble_Lagrange_base.h.
{
  return sommets_lu_;
}
References sommets_lu_.
Referenced by remplir_sommets_tmp().
zone()
const Zone & Ensemble_Lagrange_base::zone () const inline virtual
Definition at line 68 of file Ensemble_Lagrange_base.h.
{
  return ma_zone_.valeur();
}
References ma_zone_, and Ref_Zone::valeur().
Member Data Documentation
info_obj
const Type_info Ensemble_Lagrange_base::info_obj static
Definition at line 39 of file Ensemble_Lagrange_base.h.
ma_zone_
Ref_Zone Ensemble_Lagrange_base::ma_zone_ protected
Definition at line 60 of file Ensemble_Lagrange_base.h.
Referenced by associer_zone(), generer_marqueurs_sz(), and zone().
nb_marqs_par_dir
IntTab Ensemble_Lagrange_base::nb_marqs_par_dir protected
Definition at line 58 of file Ensemble_Lagrange_base.h.
Referenced by Ensemble_Lagrange_base(), and generer_marqueurs_sz().
nb_marqs_sz
IntVect Ensemble_Lagrange_base::nb_marqs_sz protected
Definition at line 57 of file Ensemble_Lagrange_base.h.
Referenced by Ensemble_Lagrange_base(), generer_marqueurs_sz(), and nb_marqs_par_sz().
nom_sz
Noms Ensemble_Lagrange_base::nom_sz protected
Definition at line 56 of file Ensemble_Lagrange_base.h.
Referenced by generer_marqueurs_sz().
sommets_lu_
DoubleTab Ensemble_Lagrange_base::sommets_lu_ protected
Definition at line 62 of file Ensemble_Lagrange_base.h.
Referenced by remplir_sommets_tmp(), and sommets_lu().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Ensemble_Lagrange_base.h
src/Kernel/Geometrie/Ensemble_Lagrange_base.cpp