TRUST: Postraiter_domaine Class Reference
Postraiter_domaine Class Reference
Classe Postraiter_domaine
Lecture d'un fichier.
#include <Postraiter_domaine.h>
Public Member Functions
Postraiter_domaine ()
~Postraiter_domaine ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
Fonction principale de l'interprete.
void ecrire (Nom &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Postraiter_domaine & self_cast (Objet_U &)
static const Postraiter_domaine & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int nb_domaine_
Nom commande_
Nom format_post_
int joint_non_ecrit_
int format_binaire_
int ecrire_frontiere_
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Classe Postraiter_domaine
Lecture d'un fichier.
Definition at line 36 of file Postraiter_domaine.h.
Constructor & Destructor Documentation
Postraiter_domaine()
Postraiter_domaine::Postraiter_domaine ()
Definition at line 22 of file Postraiter_domaine.cpp.
~Postraiter_domaine()
Postraiter_domaine::~Postraiter_domaine ()
Definition at line 22 of file Postraiter_domaine.cpp.
Member Function Documentation
cree_instance()
Objet_U * Postraiter_domaine::cree_instance () static
Definition at line 22 of file Postraiter_domaine.cpp.
duplique()
int Postraiter_domaine::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file Postraiter_domaine.cpp.
ecrire()
void Postraiter_domaine::ecrire (Nom & nom_pdb)
Definition at line 284 of file Postraiter_domaine.cpp.
{
  Nom fichier=nom_pdb.nom_me(Process::me());
  int compteur=-123;
  int compteur0=-123;
  int compteur_reel=0;
  Nom type("Format_Post_");
  type+=format_post_;
  Format_Post  post_typer;
  post_typer.typer_direct(type);
  Format_Post_base& post=ref_cast(Format_Post_base,post_typer.valeur());
  Nom nom_2(nom_pdb);
  Nom format_post_bis(format_post_);
  if (format_post_bis.debute_par("lata"))
    format_post_bis="lata";
  Nom suffix(".");
  suffix+=format_post_bis;
  nom_2.prefix(suffix);
  int est_le_premie_post=0;
  if (format_post_bis!="lata")
    post.initialize_by_default(nom_2);
  else
    post.initialize(nom_2,format_binaire_,"SIMPLE");
  for (int numero_domaine=0; numero_domaine<nb_domaine_; numero_domaine++)
    {
      if (numero_domaine==0)
        est_le_premie_post=1;
      else
        est_le_premie_post=0;
      post.ecrire_entete(0.,0,est_le_premie_post);
      const Domaine& dom=domaine(numero_domaine);
      int reprise = 0;
      double t_init = 0.;
      post.preparer_post(dom.le_nom(),est_le_premie_post,reprise,t_init);
      post.ecrire_domaine(dom, est_le_premie_post);
    }
  post.ecrire_temps(0.);
  for (int numero_domaine=0; numero_domaine<nb_domaine_; numero_domaine++)
    {
      if (numero_domaine==0)
        est_le_premie_post=1;
      else
        est_le_premie_post=0;
      const Domaine& dom=domaine(numero_domaine);
      compteur=-1;
      post.init_ecriture(0.,-1.,est_le_premie_post,dom);
    }
  int moi=Process::me();
  if (joint_non_ecrit_)
    moi=0;
  for (int numero_domaine=0; numero_domaine<nb_domaine_; numero_domaine++)
    {
      Domaine& dom=domaine(numero_domaine);
      Nom nom_dom(dom.le_nom());
      Zone& zone=dom.zone(0);
      const IntTab& les_elems = zone.les_elems();
      IntVect ch_som(zone.nb_som());
      int nb_elem=zone.nb_elem();
      IntVect ch_elem2(nb_elem);
      int num=0;
// En format LATA V2, les frontieres et joints
// sont ecrits par defaut depuis la 1.6.6 lors
// de l'ecriture des domaines si le domaine a ete discretise <=> indice_domaines_frontieres>0
      if (format_post_!="lata_V2" || dom.domaines_frontieres().size()==0)
        {
          if (dom.domaines_frontieres().size()==0) Cerr << "Warning: it could be faster and nicer to discretize your domain before using Postraiter_domaine." << finl;
//
// Ecriture des frontieres
//
          if (ecrire_frontiere_)
            {
              int nglob=1;
              int nb_bords = zone.nb_bords();
              for (int i=0; i<nb_bords; i++)
                {
                  num=i+nglob;
                  Nom nom_fr=zone.bord(i).le_nom();
// le maitre envoit le nom de la frontiere
// afin que les processeurs traitent les bords dans le meme ordre
                  if (je_suis_maitre())
                    envoyer(nom_fr,0,-1,11);
                  else
                    recevoir(nom_fr,0,me(),11);
                  Nom nom_bord;
                  if (nb_domaine_==1)
                    nom_bord = nom_fr;
                  else
                    nom_bord = zone.domaine().le_nom()+"_"+nom_fr;
                  Faces& faces=zone.frontiere(zone.rang_frontiere(nom_fr)).faces();
                  traite_bord(zone, ch_som,ch_elem2, num, faces, nom_bord, fichier, les_elems, post,compteur,compteur0,compteur_reel,moi);
                }
              nglob+=zone.nb_bords();
              int nb_raccords = zone.nb_raccords();
              for (int i=0; i<nb_raccords; i++)
                {
                  num=i+nglob;
                  Nom nom_fr=zone.raccord(i).valeur().le_nom();
                  if (je_suis_maitre())
                    envoyer(nom_fr,0,-1,11);
                  else
                    recevoir(nom_fr,0,me(),11);
                  Nom nom_bord;
                  if (nb_domaine_==1)
                    nom_bord = Nom("Raccord_")+nom_fr;
                  else
                    nom_bord = zone.domaine().le_nom()+Nom("_Raccord_")+nom_fr;
                  Faces& faces=zone.frontiere(zone.rang_frontiere(nom_fr)).faces();
                  traite_bord(zone, ch_som,ch_elem2, num, faces, nom_bord, fichier, les_elems, post,compteur,compteur0,compteur_reel,moi);
                }
              nglob+=zone.nb_raccords();
// On ecrit un champ global
              Noms noms_post(1);
              if (nb_domaine_==1)
                noms_post[0] = "Bord";
              else
                noms_post[0] = zone.domaine().le_nom()+"_Bord";
              Noms unites(1);
              unites[0]="1";
              int nb_som=zone.nb_som();
              DoubleTab ch_som2(nb_som,1);
              for (int j=0; j<nb_som; j++)
                ch_som2(j,0)=(ch_som(j));
              post.ecrire_champ(dom,unites,noms_post,-1,0.,0.,noms_post[0], nom_dom, "SOM","scalar",ch_som2);
            }
//
// Ecriture des joints
//
          if (!joint_non_ecrit_)
            for (int p=0; p<nproc(); p++)
              {
                int nb_joint=zone.nb_joints();
                envoyer_broadcast(nb_joint, p);
                for (int i=0; i<nb_joint; i++)
                  {
                    Nom nom_bord;
                    if (me()==p)
                      {
                        if (nb_domaine_==1)
                          nom_bord="Joint_Proc_";
                        else
                          nom_bord=zone.domaine().le_nom()+"Joint_Proc_";
                        Nom namep(p);
                        nom_bord+=namep;
                        nom_bord+="_avec_Proc_";
                        nom_bord+=Nom(zone.joint(i).PEvoisin());
                      }
// Le processeur p envoie nom_bord a tout le monde
                    envoyer_broadcast(nom_bord, p);
                    Faces toto;
                    Cerr<< me()<<" INFO " << p<<" "<<nom_bord<<finl;
                    Faces& faces=(me()==p?zone.joint(i).faces():toto);
                    barrier();
                    traite_bord(zone, ch_som,ch_elem2, num, faces, nom_bord, fichier, les_elems,post,compteur,compteur0,compteur_reel,moi,1);
                    barrier();
                  }
              }
        }
//
// Ecriture des sous_zones
//
      int nb_ss_zones=dom.nb_ss_zones();
      int nb_elem_tot=zone.nb_elem_tot();
      for (int i=0; i<nb_ss_zones; i++)
        {
          const Sous_Zone& la_ss_zone=dom.ss_zone(i);
          int nbpoly=la_ss_zone.nb_elem_tot();
          IntVect ch_elemb2(nb_elem);
          int cell=0;
          for (int pol=0; pol<nbpoly; pol++)
            {
              int elem=la_ss_zone[pol];
              if (elem<nb_elem)
                {
                  ch_elemb2[elem]=(i+1);
                  cell++;
                }
              else if (elem>=nb_elem_tot)
                {
                  Cerr << "This subzone is poorly defined." << finl;
                  Cerr << "It is composed of elements which do not belong" << finl;
                  Cerr << "to the domain!" << finl;
                  Process::exit();
                }
            }
          int subzone_cells=mp_sum(cell);
          Cerr<<"We handle of the subzone " << i <<" who have " << subzone_cells << " cells." << finl;
          Faces bidon;
          Nom nom_post;
          nom_post="Sous_Zone_";
          nom_post+=la_ss_zone.le_nom();
          traite_bord(zone,ch_som,ch_elemb2,1,bidon,nom_post,fichier,les_elems,post,compteur,compteur0,compteur_reel,moi,2);
        }
    }
  int fin=1;
  post.finir(fin);
}
References Process::barrier(), Zone::bord(), Cerr, compteur, Nom::debute_par(), Zone::domaine(), Interprete_geometrique_base::domaine(), Domaine::domaines_frontieres(), Format_Post_base::ecrire_champ(), Format_Post_base::ecrire_domaine(), Format_Post_base::ecrire_entete(), ecrire_frontiere_, Format_Post_base::ecrire_temps(), envoyer(), envoyer_broadcast(), Process::exit(), Frontiere::faces(), Format_Post_base::finir(), finl, format_binaire_, format_post_, Zone::frontiere(), Format_Post_base::init_ecriture(), Format_Post_base::initialize(), Format_Post_base::initialize_by_default(), Process::je_suis_maitre(), Zone::joint(), joint_non_ecrit_, Domaine::le_nom(), Frontiere::le_nom(), Sous_Zone::le_nom(), Zone::les_elems(), Process::me(), Process::mp_sum(), Zone::nb_bords(), nb_domaine_, Zone::nb_elem(), Sous_Zone::nb_elem_tot(), Zone::nb_elem_tot(), Zone::nb_joints(), Zone::nb_raccords(), Zone::nb_som(), Domaine::nb_ss_zones(), Nom::nom_me(), Process::nproc(), Joint::PEvoisin(), Nom::prefix(), Format_Post_base::preparer_post(), Zone::raccord(), Zone::rang_frontiere(), recevoir(), ref_cast, liste::size(), Domaine::ss_zone(), traite_bord(), Format_Post::typer_direct(), Deriv_Format_Post_base::valeur(), Deriv_Raccord_base::valeur(), and Domaine::zone().
Referenced by interpreter_().
get_info()
const Type_info * Postraiter_domaine::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 22 of file Postraiter_domaine.cpp.
info()
const Type_info * Postraiter_domaine::info () static
Definition at line 22 of file Postraiter_domaine.cpp.
interpreter_()
Entree & Postraiter_domaine::interpreter_ (Entree & is) override virtual
Fonction principale de l'interprete.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
< desactive l'ecriture des joints pratique pour comparer parallele et sequentielle
Implements Interprete_geometrique_base.
Definition at line 215 of file Postraiter_domaine.cpp.
{
  Nom nom_pdb;
  Nom un_dom;
  Param param(que_suis_je());
  param.ajouter("format",&format_post_,Param::REQUIRED);
  format_binaire_=1;
  param.ajouter("binaire",&format_binaire_);
  ecrire_frontiere_=1;
  param.ajouter("ecrire_frontiere",&ecrire_frontiere_);
  nom_pdb="NOM_DU_CAS";
  param.ajouter("fichier|file",&nom_pdb);
  joint_non_ecrit_=1;
  param.ajouter("joints_non_postraites",&joint_non_ecrit_); //!< desactive l'ecriture des joints pratique pour comparer parallele et sequentielle
  param.ajouter("domaine",&un_dom);
  param.ajouter_non_std("domaines",(this));
  param.ajouter_condition("is_read_domaine_or_is_read_domaines","Vous devez preciser domaine ou domaines dans Postraiter_domaine");
  param.ajouter_condition("is_read_domaine_or_is_read_domaines","Interpreter Postraiter_domaine : one of the keywords domaine or domaines must be specified.");
  param.lire_avec_accolades_depuis(is);
  if (un_dom!=Nom())
    {
      associer_domaine(un_dom);
    }
  nb_domaine_=domaines().size();
  if(nb_domaine_==0)
    {
      Cerr << "You must specify one or several domains" << finl;
      exit();
    }
  if (nom_pdb=="NOM_DU_CAS")
    {
      nom_pdb=nom_du_cas();
      nom_pdb+=".";
      nom_pdb+=format_post_;
    }
  if (format_post_=="lata")
    format_post_+="_V2";
// On deplace la boucle sur les domaines lus
  ecrire(nom_pdb);
  return is;
}
References Param::ajouter(), Param::ajouter_condition(), Param::ajouter_non_std(), Interprete_geometrique_base::associer_domaine(), Cerr, Interprete_geometrique_base::domaines(), ecrire(), ecrire_frontiere_, Process::exit(), finl, format_binaire_, format_post_, joint_non_ecrit_, Param::lire_avec_accolades_depuis(), nb_domaine_, Objet_U::nom_du_cas(), Objet_U::que_suis_je(), Param::REQUIRED, and liste::size().
lire_motcle_non_standard()
int Postraiter_domaine::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Objet_U.
Definition at line 257 of file Postraiter_domaine.cpp.
{
  if (motcle=="domaines")
    {
      Nom mot;
      is>>mot;
      if (mot!="{")
        {
          Cerr<< "we expected { and not "<<mot<<finl;
          exit();
        }
      is>>mot;
      while (mot!="}")
        {
          associer_domaine(mot);
          is>>mot;
        }
      return 1;
    }
  else
    {
      Cerr<<motcle <<" not understood by Postraiter_domaine::lire_motcle_non_standard"<<finl;
      exit();
    }
  return -1;
}
References Interprete_geometrique_base::associer_domaine(), Cerr, Process::exit(), and finl.
printOn()
Sortie & Postraiter_domaine::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 38 of file Postraiter_domaine.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Postraiter_domaine::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 57 of file Postraiter_domaine.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Postraiter_domaine & Postraiter_domaine::self_cast (const Objet_U & r) static
Definition at line 22 of file Postraiter_domaine.cpp.
self_cast() [2/2]
Postraiter_domaine & Postraiter_domaine::self_cast (Objet_U & r) static
Definition at line 22 of file Postraiter_domaine.cpp.
taille_memoire()
unsigned Postraiter_domaine::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file Postraiter_domaine.cpp.
Member Data Documentation
commande_
Nom Postraiter_domaine::commande_ protected
Definition at line 45 of file Postraiter_domaine.h.
ecrire_frontiere_
int Postraiter_domaine::ecrire_frontiere_ protected
Definition at line 48 of file Postraiter_domaine.h.
Referenced by ecrire(), and interpreter_().
format_binaire_
int Postraiter_domaine::format_binaire_ protected
Definition at line 47 of file Postraiter_domaine.h.
Referenced by ecrire(), and interpreter_().
format_post_
Nom Postraiter_domaine::format_post_ protected
Definition at line 45 of file Postraiter_domaine.h.
Referenced by ecrire(), and interpreter_().
info_obj
const Type_info Postraiter_domaine::info_obj static
Definition at line 38 of file Postraiter_domaine.h.
joint_non_ecrit_
int Postraiter_domaine::joint_non_ecrit_ protected
Definition at line 46 of file Postraiter_domaine.h.
Referenced by ecrire(), and interpreter_().
nb_domaine_
int Postraiter_domaine::nb_domaine_ protected
Definition at line 44 of file Postraiter_domaine.h.
Referenced by ecrire(), and interpreter_().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Postraiter_domaine.h
src/Kernel/Geometrie/Postraiter_domaine.cpp