TRUST: Traduction_Indice_Global_Local Class Reference
Traduction_Indice_Global_Local Class Reference
Cette classe fournit les outils pour construire l'espace
virtuel d'un tableau contenant des indices d'entites geometriques<br>(sommets, elements, faces). Elle gere en particulier la
renumerotation des elements virtuels.
Public Member Functions
Traduction_Indice_Global_Local ()
void initialiser (const MD_Vector &md_items)
Initialise le dictionnaire
Precontition:
Les espaces distants des entites utilisees doivent avoir ete calculees.
void reset ()
void traduire_indice_local_vers_global (const ArrOfInt &indices_locaux, ArrOfInt &indices_globaux, int n) const
Transforme les indices locaux en indices globaux a l'aide la
"table_" (voir initialiser). On fait :
Pour debut <= i < debut+nb
indices_globaux[i] = table_[indices_locaux[i]]
si indices_locaux[i] < 0 alors indices_globaux[i] = -1.
int traduire_indice_global_vers_local (const ArrOfInt &indices_globaux, ArrOfInt &indices_locaux) const
Pour debut <= i < debut+nb
indices_locaux[i] = chercher l'indice local de "indices_globaux[i]"
Parametre: indices_globaux
Signification: le tableau des indices globaux a traduire
Parametre: indices_locaux
Signification: en sortie, les indices locaux ou -1 si l'indice global
n'a pas ete trouve.
Valeur de retour: nombre d'indices non trouves (indices globaux qui
ne correspondent a aucun indice local).
int traduire_espace_virtuel (IntVect &tableau) const
A partir d'un tableau dont la structure d'espace virtuel est initialisee<br>(descripteurs elements distants et virtuels, items communs)
et contenant des indices compatibles avec le contenu des tables
(indices de sommets ou d'elements selon type_table_),
on remplit les elements virtuels du "tableau" en fonction des elements
distants et on traduit les indices en indices locaux.
(exemple, voir construire_espace_virtuel_elements et
construire_espace_virtuel_faces).
Valeur de retour: nombre d'indices qui n'ont pas pu etre traduits
(par exemple, le sommet reference n'existe pas sur le processeur voisin)
Static Public Member Functions
static int chercher_table_inverse (const IntTab &table_inverse, const int sommet_global)
Cherche i tel que table_inverse(i, 0) == sommet_global,
et renvoie table_inverse(i, 1) (l'indice local du sommet).
Si le sommet n'est pas trouve dans la table, renvoie -1.
La table_inverse doit etre triee par ordre croissant de la colonne 0.
La table_inverse ne doit pas avoir d'espace virtuel.
Private Attributes
MD_Vector md_items_
int premier_indice_global_
IntVect table_
IntTab table_inverse_
Detailed Description
Cette classe fournit les outils pour construire l'espace
virtuel d'un tableau contenant des indices d'entites geometriques<br>(sommets, elements, faces). Elle gere en particulier la
renumerotation des elements virtuels.
Definition at line 1519 of file Scatter.cpp.
Constructor & Destructor Documentation
Traduction_Indice_Global_Local()
Traduction_Indice_Global_Local::Traduction_Indice_Global_Local () inline
Definition at line 1522 of file Scatter.cpp.
{};
Member Function Documentation
chercher_table_inverse()
int Traduction_Indice_Global_Local::chercher_table_inverse (const IntTab & table_inverse, const int sommet_global) static
Cherche i tel que table_inverse(i, 0) == sommet_global,
et renvoie table_inverse(i, 1) (l'indice local du sommet).
Si le sommet n'est pas trouve dans la table, renvoie -1.
La table_inverse doit etre triee par ordre croissant de la colonne 0.
La table_inverse ne doit pas avoir d'espace virtuel.
< (min+max)/2
Definition at line 1605 of file Scatter.cpp.
{
// Algorithme : recherche par dichotomie:
  int imin = 0;
  int imax = table_inverse.dimension(0) - 1;
// Si un seul element dans la table, on ne passe pas dans while
// (donc initialisation a table_inverse(0, 0))
// Sinon, si aucun element, il ne faut pas que valeur == sommet_global,
// sinon, valeur quelconque, elle sera ecrasee dans le while.
  int valeur;
  if (imax == 0)
    valeur = table_inverse(0, 0);
  else
    valeur = sommet_global - 1;
  while (imax > imin)
    {
      const int milieu = (imin + imax) >> 1; //!< (min+max)/2
      valeur = table_inverse(milieu, 0);
      const int compare = valeur - sommet_global;
      if (compare < 0)
        imin = milieu + 1;
      else if (compare > 0)
        imax = milieu - 1;
      else
        imin = imax = milieu;
    }
  int resu = -1;
  valeur = table_inverse(imin, 0);
  if (valeur == sommet_global)
    resu = table_inverse(imin, 1);
  return resu;
}
References compare(), TRUSTTab< _TYPE_ >::dimension(), and valeur().
Referenced by traduire_indice_global_vers_local().
initialiser()
void Traduction_Indice_Global_Local::initialiser (const MD_Vector & md_items)
Initialise le dictionnaire
Precontition:
Les espaces distants des entites utilisees doivent avoir ete calculees.
Definition at line 1552 of file Scatter.cpp.
{
  md_items_ = md_items;
// Construction de "table" : on cree un numero global pour les entites reelles
// (indice de l'entite + nombre total d'entites sur les processeurs de rang inferieur)
// puis on echange l'espace virtuel de ce tableau, on obtient pour chaque entite
// reelle ou virtuelle son numero global.
  table_.reset();
  MD_Vector_tools::creer_tableau_distribue(md_items, table_);
  const int nb_entites = md_items.valeur().get_nb_items_tot();
  const int decal = mppartial_sum(nb_entites);
  premier_indice_global_ = decal;
  int i;
  for (i = 0; i < nb_entites; i++)
    table_[i] = i + decal;
  table_.echange_espace_virtuel();
// Construction de la table_inverse contenant les indices non triviaux
// (pour lesquels table_[i] != i + decal apres l'echange)
// tri par ordre croissant du numero global.
  const int nb_entites_tot = table_.size_totale();
  table_inverse_.resize(0, 2);
  table_inverse_.set_smart_resize(1);
  for (i = 0; i < nb_entites_tot; i++)
    {
      if (table_[i] != i + decal)
        table_inverse_.append_line(table_[i], i);
    }
// insure se plaint .. regarder si il a raison
  if (table_inverse_.size_array()>0)
    qsort(table_inverse_.addr(),
          table_inverse_.dimension(0),
          2 * sizeof(int),
          fct_tri_table_inverse);
}
References TRUSTArray< _TYPE_ >::addr(), TRUSTTab< _TYPE_ >::append_line(), MD_Vector_tools::creer_tableau_distribue(), TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), fct_tri_table_inverse(), MD_Vector_base::get_nb_items_tot(), md_items_, mppartial_sum(), premier_indice_global_, TRUSTVect< _TYPE_ >::reset(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), table_, table_inverse_, and MD_Vector::valeur().
Referenced by Scatter::construire_espace_virtuel_traduction(), and Scatter::reordonner_faces_de_joint().
reset()
void Traduction_Indice_Global_Local::reset ()
Definition at line 1592 of file Scatter.cpp.
{
  md_items_.detach();
  table_.reset();
  table_inverse_.reset();
}
References MD_Vector::detach(), md_items_, TRUSTTab< _TYPE_ >::reset(), TRUSTVect< _TYPE_ >::reset(), table_, and table_inverse_.
traduire_espace_virtuel()
int Traduction_Indice_Global_Local::traduire_espace_virtuel (IntVect & tableau) const
A partir d'un tableau dont la structure d'espace virtuel est initialisee<br>(descripteurs elements distants et virtuels, items communs)
et contenant des indices compatibles avec le contenu des tables
(indices de sommets ou d'elements selon type_table_),
on remplit les elements virtuels du "tableau" en fonction des elements
distants et on traduit les indices en indices locaux.
(exemple, voir construire_espace_virtuel_elements et
construire_espace_virtuel_faces).
Valeur de retour: nombre d'indices qui n'ont pas pu etre traduits
(par exemple, le sommet reference n'existe pas sur le processeur voisin)
Definition at line 1716 of file Scatter.cpp.
{
// On cree une copie du tableau, dans laquelle on met les indices globaux:
  IntVect indices_globaux;
// Ne copier que la structure
  indices_globaux.copy(tableau, ArrOfInt::NOCOPY_NOINIT);
  const int nb_items_reels    = tableau.size_reelle();
  const int nb_items_tot      = tableau.size_totale();
  const int nb_items_virtuels = nb_items_tot - nb_items_reels;
// On traduit les items reels en indices globaux:
  traduire_indice_local_vers_global(tableau, indices_globaux, nb_items_reels);
// On remplit les cases virtuelles
  indices_globaux.echange_espace_virtuel();
// On retraduit uniquement les items virtuels du "tableau" en indices locaux:
  ArrOfInt src;
  ArrOfInt dest;
  src.ref_array(indices_globaux, nb_items_reels /*debut*/, nb_items_virtuels /*taille*/);
  dest.ref_array(tableau, nb_items_reels /*debut*/, nb_items_virtuels /*taille*/);
  const int nb_erreurs = traduire_indice_global_vers_local(src, dest);
  return nb_erreurs;
}
References TRUSTVect< _TYPE_ >::copy(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Array_base::NOCOPY_NOINIT, TRUSTArray< _TYPE_ >::ref_array(), TRUSTVect< _TYPE_ >::size_reelle(), TRUSTVect< _TYPE_ >::size_totale(), traduire_indice_global_vers_local(), and traduire_indice_local_vers_global().
Referenced by Scatter::construire_espace_virtuel_traduction().
traduire_indice_global_vers_local()
int Traduction_Indice_Global_Local::traduire_indice_global_vers_local (const ArrOfInt & indices_globaux, ArrOfInt & indices_locaux) const
Pour debut <= i < debut+nb
indices_locaux[i] = chercher l'indice local de "indices_globaux[i]"
Parametre: indices_globaux
Signification: le tableau des indices globaux a traduire
Parametre: indices_locaux
Signification: en sortie, les indices locaux ou -1 si l'indice global
n'a pas ete trouve.
Valeur de retour: nombre d'indices non trouves (indices globaux qui
ne correspondent a aucun indice local).
Definition at line 1669 of file Scatter.cpp.
{
  assert(indices_globaux.size_array() == indices_locaux.size_array());
  int i;
  int nb_erreurs = 0;
  const int nb_indices = indices_globaux.size_array();
  const int size_table = table_.size_array();
  for (i = 0; i < nb_indices; i++)
    {
      const int i_glob = indices_globaux[i];
      int i_loc;
      if (i_glob < 0)
        {
// Indice negatif, on considere que c'est normal,
// c'est un marqueur "indice vide".
          i_loc = -1;
        }
      else
        {
// On teste si l'item n'est pas renumerote
          i_loc = i_glob - premier_indice_global_;
          if (i_loc < 0 || i_loc >= size_table || table_[i_loc] != i_glob)
            {
// non, il faut inverser la table:
              i_loc = chercher_table_inverse(table_inverse_, i_glob);
            }
          if (i_loc < 0)
            nb_erreurs++;
        }
      indices_locaux[i] = i_loc;
    }
  return nb_erreurs;
}
References chercher_table_inverse(), premier_indice_global_, TRUSTArray< _TYPE_ >::size_array(), table_, and table_inverse_.
Referenced by Scatter::reordonner_faces_de_joint(), and traduire_espace_virtuel().
traduire_indice_local_vers_global()
void Traduction_Indice_Global_Local::traduire_indice_local_vers_global (const ArrOfInt & indices_locaux, ArrOfInt & indices_globaux, int n) const
Transforme les indices locaux en indices globaux a l'aide la
"table_" (voir initialiser). On fait :
Pour debut <= i < debut+nb
indices_globaux[i] = table_[indices_locaux[i]]
si indices_locaux[i] < 0 alors indices_globaux[i] = -1.
Definition at line 1646 of file Scatter.cpp.
{
  for (int i = 0; i < nb_items_a_traiter; i++)
    {
      const int i_loc = indices_locaux[i];
      const int i_glob = (i_loc < 0) ? -1 : table_[i_loc];
      indices_globaux[i] = i_glob;
    }
}
References table_.
Referenced by Scatter::reordonner_faces_de_joint(), and traduire_espace_virtuel().
Member Data Documentation
md_items_
MD_Vector Traduction_Indice_Global_Local::md_items_ private
Definition at line 1534 of file Scatter.cpp.
Referenced by initialiser(), and reset().
premier_indice_global_
int Traduction_Indice_Global_Local::premier_indice_global_ private
Definition at line 1535 of file Scatter.cpp.
Referenced by initialiser(), and traduire_indice_global_vers_local().
table_
IntVect Traduction_Indice_Global_Local::table_ private
Definition at line 1540 of file Scatter.cpp.
Referenced by initialiser(), reset(), traduire_indice_global_vers_local(), and traduire_indice_local_vers_global().
table_inverse_
IntTab Traduction_Indice_Global_Local::table_inverse_ private
Definition at line 1545 of file Scatter.cpp.
Referenced by initialiser(), reset(), and traduire_indice_global_vers_local().
The documentation for this class was generated from the following file:
src/Kernel/Geometrie/Scatter.cpp