TRUST: Ecrire_Fichier Class Reference
Ecrire_Fichier Class Reference
Ecriture d'un fichier.
#include <Ecrire_Fichier.h>
Public Member Functions
Ecrire_Fichier ()
~Ecrire_Fichier ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ecrire_Fichier & self_cast (Objet_U &)
static const Ecrire_Fichier & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Appel a la methode printOn de la classe Interprete.
virtual Entree & readOn (Entree &)
Appel a la methode readOn de la classe Interprete.
void interpreter_ (Entree &, int format_binaire)
Detailed Description
Ecriture d'un fichier.
Definition at line 34 of file Ecrire_Fichier.h.
Constructor & Destructor Documentation
Ecrire_Fichier::Ecrire_Fichier ()
Definition at line 27 of file Ecrire_Fichier.cpp.
Ecrire_Fichier::~Ecrire_Fichier ()
Definition at line 27 of file Ecrire_Fichier.cpp.
Member Function Documentation
Objet_U * Ecrire_Fichier::cree_instance () [static]
Reimplemented from Interprete.
Reimplemented in Ecrire_Fichier_Formatte.
Definition at line 27 of file Ecrire_Fichier.cpp.
int Ecrire_Fichier::duplique () const [virtual]
Reimplemented from Interprete.
Reimplemented in Ecrire_Fichier_Formatte.
Definition at line 27 of file Ecrire_Fichier.cpp.
const Type_info * Ecrire_Fichier::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Reimplemented in Ecrire_Fichier_Formatte.
Definition at line 27 of file Ecrire_Fichier.cpp.
const Type_info * Ecrire_Fichier::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Reimplemented in Ecrire_Fichier_Formatte.
Definition at line 27 of file Ecrire_Fichier.cpp.
Entree & Ecrire_Fichier::interpreter (Entree & is) [virtual]
Reimplemented from Interprete.
Reimplemented in Ecrire_Fichier_Formatte.
Definition at line 80 of file Ecrire_Fichier.cpp.
References interpreter_().
{
  Ecrire_Fichier::interpreter_(is, 1 /* binaire */);
  return is;
}
void Ecrire_Fichier::interpreter_ (Entree & is, int format_binaire) [protected]
Definition at line 44 of file Ecrire_Fichier.cpp.
References Process::barrier(), Cerr, Process::exit(), finl, Sortie_Fichier_base::get_ofstream(), Sortie::get_ostream(), Process::nproc(), Interprete::objet(), Sortie_Fichier_base::ouvrir(), and Sortie::set_bin().
Referenced by Ecrire_Fichier_Formatte::interpreter(), and interpreter().
{
  if (nproc() > 1)
    {
      Cerr << "Error: keyword Ecrire_Fichier_Bin cannot be used in parallel calculation. What do you mean ?" << finl;
      barrier();
      exit();
    }
  SFichier fic;
  Nom nom1, nom2;
  is >> nom1 >> nom2;
  Cerr << "Ecrire_Fichier_Bin: writing object " << nom1 << " in file " << nom2;
  if (format_binaire)
    Cerr << " in binary format." << finl;
  else
    Cerr << " in ascii format." << finl;
  Objet_U& obj = objet(nom1);
  fic.set_bin(format_binaire);
  if (!fic.ouvrir(nom2))
    {
      Cerr << " Error opening file: " << nom2 << finl;
      exit();
    }
  if (!format_binaire)
    {
      fic.get_ofstream().setf(ios::scientific);
      fic.get_ofstream().precision(8);
    }
  fic << obj;
  if (!fic.get_ostream().good())
    {
      Cerr << " An error occured while writing the file." << finl;
      exit();
    }
}
Sortie & Ecrire_Fichier::printOn (Sortie & x) const [protected, virtual]
Appel a la methode printOn de la classe Interprete.
Reimplemented from Interprete.
Reimplemented in Ecrire_Fichier_Formatte.
Definition at line 32 of file Ecrire_Fichier.cpp.
{
  return Interprete::printOn(os);
}
Entree & Ecrire_Fichier::readOn (Entree & is) [protected, virtual]
Appel a la methode readOn de la classe Interprete.
Reimplemented from Interprete.
Reimplemented in Ecrire_Fichier_Formatte.
Definition at line 39 of file Ecrire_Fichier.cpp.
{
  return Interprete::readOn(is);
}
Ecrire_Fichier & Ecrire_Fichier::self_cast (Objet_U & r) [static]
Reimplemented from Interprete.
Reimplemented in Ecrire_Fichier_Formatte.
Definition at line 27 of file Ecrire_Fichier.cpp.
const Ecrire_Fichier & Ecrire_Fichier::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete.
Reimplemented in Ecrire_Fichier_Formatte.
Definition at line 27 of file Ecrire_Fichier.cpp.
unsigned Ecrire_Fichier::taille_memoire () const [virtual]
Reimplemented from Interprete.
Reimplemented in Ecrire_Fichier_Formatte.
Definition at line 27 of file Ecrire_Fichier.cpp.
Member Data Documentation
const Type_info Ecrire_Fichier::info_obj [static]
Reimplemented from Interprete.
Reimplemented in Ecrire_Fichier_Formatte.
Definition at line 36 of file Ecrire_Fichier.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Ecrire_Fichier.h
src/Kernel/Utilitaires/Ecrire_Fichier.cpp