TRUST: Segment_EF_axi Class Reference
Segment_EF_axi Class Reference
: class Segment_EF_axi
<Description of class Segment_EF_axi>
#include <Segment_EF_axi.h>
Public Member Functions
Segment_EF_axi ()
~Segment_EF_axi ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const override
remplit le tableau face_normales dans la Zone_EF
Public Member Functions inherited from Segment_EF
~Segment_EF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Segment_EF ()
void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int) const override
void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const override
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=2, n1 est le numero du sommet confondu avec G
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const override
remplit le tableau face_normales dans la Zone_EF
Public Member Functions inherited from Elem_EF_base
Elem_EF_base ()
~Elem_EF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int) const =0
virtual void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const =0
virtual void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Segment_EF_axi & self_cast (Objet_U &)
static const Segment_EF_axi & self_cast (const Objet_U &)
Static Public Member Functions inherited from Segment_EF
static Objet_U * cree_instance ()
static const Type_info * info ()
static Segment_EF & self_cast (Objet_U &)
static const Segment_EF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Elem_EF_base
static const Type_info * info ()
static Elem_EF_base & self_cast (Objet_U &)
static const Elem_EF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Segment_EF
static const Type_info info_obj
Static Public Attributes inherited from Elem_EF_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
: class Segment_EF_axi
<Description of class Segment_EF_axi>
Definition at line 29 of file Segment_EF_axi.h.
Constructor & Destructor Documentation
Segment_EF_axi()
Segment_EF_axi::Segment_EF_axi ()
Definition at line 20 of file Segment_EF_axi.cpp.
~Segment_EF_axi()
Segment_EF_axi::~Segment_EF_axi ()
Definition at line 20 of file Segment_EF_axi.cpp.
Member Function Documentation
cree_instance()
Objet_U * Segment_EF_axi::cree_instance () static
Definition at line 20 of file Segment_EF_axi.cpp.
duplique()
int Segment_EF_axi::duplique () const override virtual
Reimplemented from Segment_EF.
Definition at line 20 of file Segment_EF_axi.cpp.
get_info()
const Type_info * Segment_EF_axi::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Segment_EF.
Definition at line 20 of file Segment_EF_axi.cpp.
info()
const Type_info * Segment_EF_axi::info () static
Definition at line 20 of file Segment_EF_axi.cpp.
normale()
void Segment_EF_axi::normale (int num_Face, DoubleTab & Face_normales, const IntTab & Face_sommets, const IntTab & Face_voisins, const IntTab & elem_faces, const Zone & zone_geom) const override virtual
remplit le tableau face_normales dans la Zone_EF
Reimplemented from Segment_EF.
Definition at line 34 of file Segment_EF_axi.cpp.
{
  Segment_EF::normale(num_Face,Face_normales,Face_sommets,Face_voisins,elem_faces,zone_geom);
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
  const DomaineAxi1d& domax = ref_cast(DomaineAxi1d,zone_geom.domaine());
  int elem = Face_voisins(num_Face,0)==-1 ? Face_voisins(num_Face,1) : Face_voisins(num_Face,0);
  double x0 = domax.origine_repere(elem,0);
  double y0 = domax.origine_repere(elem,1);
  int som = Face_sommets(num_Face,0);
  double x = les_coords(som,0);
  double y = les_coords(som,1);
  double r = sqrt((x-x0)*(x-x0)+(y-y0)*(y-y0));
  double surf = 2.*M_PI*r;
  if (surf>0.)
    Face_normales(num_Face,0)*=surf;
}
References Domaine::coord_sommets(), Zone::domaine(), M_PI, Segment_EF::normale(), DomaineAxi1d::origine_repere(), and ref_cast.
printOn()
Sortie & Segment_EF_axi::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Segment_EF.
Definition at line 22 of file Segment_EF_axi.cpp.
{
  Segment_EF::printOn( os );
  return os;
}
References Segment_EF::printOn().
readOn()
Entree & Segment_EF_axi::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Segment_EF.
Definition at line 28 of file Segment_EF_axi.cpp.
{
  Segment_EF::readOn( is );
  return is;
}
References Segment_EF::readOn().
self_cast() [1/2]
const Segment_EF_axi & Segment_EF_axi::self_cast (const Objet_U & r) static
Definition at line 20 of file Segment_EF_axi.cpp.
self_cast() [2/2]
Segment_EF_axi & Segment_EF_axi::self_cast (Objet_U & r) static
Definition at line 20 of file Segment_EF_axi.cpp.
taille_memoire()
unsigned Segment_EF_axi::taille_memoire () const override virtual
Reimplemented from Segment_EF.
Definition at line 20 of file Segment_EF_axi.cpp.
Member Data Documentation
info_obj
const Type_info Segment_EF_axi::info_obj static
Definition at line 32 of file Segment_EF_axi.h.
The documentation for this class was generated from the following files:
src/EF/Zones/Segment_EF_axi.h
src/EF/Zones/Segment_EF_axi.cpp