TRUST: Champ_Fonc_P1_isoP1Bulle Class Reference
Champ_Fonc_P1_isoP1Bulle Class Reference
classe Champ_Fonc_P1_isoP1Bulle
#include <Champ_Fonc_P1_isoP1Bulle.h>
Public Member Functions
Champ_Fonc_P1_isoP1Bulle ()
~Champ_Fonc_P1_isoP1Bulle ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int fixer_nb_valeurs_nodales (int) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
const Zone_dis_base & zone_dis_base () const override
void associer_zone_dis_base (const Zone_dis_base &) override
const Zone_VEF_PreP1b & zone_vef () const override
void mettre_a_jour (double) override
Mise a jour en temps du champ.
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &tab_valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &tab_valeurs, int ncomp) const override
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const override
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Public Member Functions inherited from Champ_Fonc_base
Champ_Fonc_base ()
~Champ_Fonc_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps du champ.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
Reprise a partir d'un flot d'entree
Lit le temps et les valeurs du champ.
Saute un bloc si le nom du champ est "anonyme".
int sauvegarder (Sortie &) const override
Sauvegarde le champ sur un flot de sortie
Ecrit le nom, le temps et les valeurs.
Champ_base & affecter_ (const Champ_base &) override
Affecte un Champ_base dans un Champ_Fonc_base.
Champ_base & affecter_compo (const Champ_base &, int compo) override
Affecte une composante d'un Champ_base dans la meme composnate
d'un Champ_Fonc_base.
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
const Domaine & domaine () const
int a_une_zone_dis_base () const override
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void creer_espace_distant (int dummy)
Public Member Functions inherited from Champ_Don_base
Champ_Don_base ()
~Champ_Don_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps.
Parametre: double
Signification: le temps de mise a jour.
void dimensionner (int, int)
Fixe le nombre de composantes et le nombre de valeurs nodales.
Parametre: int
Signification: le nombre de noeud par composante du champ (le nombre de dl par composante)
Parametre: int
Signification: le nombre de composante du champ.
int imprime (Sortie &, int) const override
NE FAIT RIEN. EXIT ! A surcharger dans les classes derivees.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
NE FAIT RIEN. A surcharger dans les classes derivees.
int sauvegarder (Sortie &) const override
NE FAIT RIEN. A surcharger dans les classes derivees.
DoubleTab & valeurs () override
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
const DoubleTab & valeurs () const override
Champ_base & affecter_ (const Champ_base &) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
Champ_base & affecter_compo (const Champ_base &, int) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
virtual int initialiser (const double temps)
NE FAIT RIEN. A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire.
int nb_valeurs_nodales () const override
Renvoie le nombre de degre de liberte par composante: le nombre de noeuds.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Public Member Functions inherited from Champ_P1iP1B_implementation
Champ_P1iP1B_implementation ()
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const override
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
int imprime_P1B (Sortie &, int) const
DoubleTab & filtrage (const Zone_VEF_PreP1b &, const Champ_base &) const
Methode pour filtrer le champ.
const DoubleTab & champ_filtre () const
Public Member Functions inherited from Champ_implementation
virtual ~Champ_implementation ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const =0
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const =0
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Fonc_P1_isoP1Bulle & self_cast (Objet_U &)
static const Champ_Fonc_P1_isoP1Bulle & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Fonc_base
static const Type_info * info ()
static Champ_Fonc_base & self_cast (Objet_U &)
static const Champ_Fonc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Don_base
static const Type_info * info ()
static Champ_Don_base & self_cast (Objet_U &)
static const Champ_Don_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Fonc_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_Don_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
void completer (const Zone_Cl_dis_base &zcl) override
const Champ_base & le_champ () const override
Champ_base & le_champ () override
Protected Member Functions inherited from Champ_Fonc_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void creer_tableau_distribue (const MD_Vector &, Array_base::Resize_Options=Array_base::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Champ_P1iP1B_implementation
void completer (const Zone_Cl_dis_base &zcl)
virtual const Zone_VEF_PreP1b & zone_vef () const =0
DoubleTab & trace (const Frontiere_dis_base &fr, const DoubleTab &y, DoubleTab &x, int distant) const
Protected Member Functions inherited from Champ_implementation
virtual const Champ_base & le_champ () const =0
virtual Champ_base & le_champ ()=0
const Zone & zone () const
virtual const Zone_dis_base & zone_dis_base () const
Protected Attributes
Ref_Zone_VEF_PreP1b la_zone_VEFP1B
Protected Attributes inherited from Champ_Don_base
DoubleTab valeurs_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Protected Attributes inherited from Champ_P1iP1B_implementation
DoubleTab champ_filtre_
Contient les valeurs du champ filtre.
Matrice matrice_filtrage_
Contient la matrice necessaire au filtrage (evite d'avoir a la recalculer)
double temps_filtrage_
Temps du dernier filtrage (va servir a ne pas refiltrer inutilement)
const double * adresse_champ_filtre_
Adresse du champ filtre (va servir a ne pas refiltrer inutilement)
Additional Inherited Members
Public Attributes inherited from Champ_P1iP1B_implementation
int Condition_Neumann_imposee_
Drapeau pour savoir s'il y'a des CL de Neumann (influe sur le filtrage)
Detailed Description
classe Champ_Fonc_P1_isoP1Bulle
Definition at line 29 of file Champ_Fonc_P1_isoP1Bulle.h.
Constructor & Destructor Documentation
Champ_Fonc_P1_isoP1Bulle()
Champ_Fonc_P1_isoP1Bulle::Champ_Fonc_P1_isoP1Bulle ()
Definition at line 20 of file Champ_Fonc_P1_isoP1Bulle.cpp.
~Champ_Fonc_P1_isoP1Bulle()
Champ_Fonc_P1_isoP1Bulle::~Champ_Fonc_P1_isoP1Bulle ()
Definition at line 20 of file Champ_Fonc_P1_isoP1Bulle.cpp.
Member Function Documentation
associer_zone_dis_base()
void Champ_Fonc_P1_isoP1Bulle::associer_zone_dis_base (const Zone_dis_base & z_dis) override virtual
Reimplemented from Champ_base.
Definition at line 65 of file Champ_Fonc_P1_isoP1Bulle.cpp.
{
  la_zone_VEFP1B=ref_cast(Zone_VEF_PreP1b, z_dis);
}
References la_zone_VEFP1B, and ref_cast.
completer()
void Champ_Fonc_P1_isoP1Bulle::completer (const Zone_Cl_dis_base & zcl) override protected virtual
Reimplemented from Champ_base.
Definition at line 84 of file Champ_Fonc_P1_isoP1Bulle.cpp.
{
  Champ_P1iP1B_implementation::completer(zcl);
}
References Champ_P1iP1B_implementation::completer().
cree_instance()
Objet_U * Champ_Fonc_P1_isoP1Bulle::cree_instance () static
Definition at line 20 of file Champ_Fonc_P1_isoP1Bulle.cpp.
duplique()
int Champ_Fonc_P1_isoP1Bulle::duplique () const override virtual
Implements Objet_U.
Definition at line 20 of file Champ_Fonc_P1_isoP1Bulle.cpp.
fixer_nb_valeurs_nodales()
int Champ_Fonc_P1_isoP1Bulle::fixer_nb_valeurs_nodales (int nb_noeuds) override virtual
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
Reimplemented from Champ_Fonc_base.
Definition at line 39 of file Champ_Fonc_P1_isoP1Bulle.cpp.
{
// On ne doit pas specifier nb_ddl !
  assert(n < 0);
  const Zone_VEF_PreP1b& zvef = zone_vef();
  const MD_Vector& md = zvef.md_vector_p1b();
  creer_tableau_distribue(md);
  return n;
}
References Champ_Fonc_base::creer_tableau_distribue(), Zone_VEF_PreP1b::md_vector_p1b(), and zone_vef().
get_info()
const Type_info * Champ_Fonc_P1_isoP1Bulle::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 20 of file Champ_Fonc_P1_isoP1Bulle.cpp.
info()
const Type_info * Champ_Fonc_P1_isoP1Bulle::info () static
Definition at line 20 of file Champ_Fonc_P1_isoP1Bulle.cpp.
le_champ() [1/2]
const Champ_base & Champ_Fonc_P1_isoP1Bulle::le_champ (void) const inline override protected virtual
Implements Champ_implementation.
Definition at line 69 of file Champ_Fonc_P1_isoP1Bulle.h.
{
  return *this;
}
le_champ() [2/2]
Champ_base & Champ_Fonc_P1_isoP1Bulle::le_champ (void) inline override protected virtual
Implements Champ_implementation.
Definition at line 74 of file Champ_Fonc_P1_isoP1Bulle.h.
{
  return *this;
}
mettre_a_jour()
void Champ_Fonc_P1_isoP1Bulle::mettre_a_jour (double temps) override virtual
Mise a jour en temps du champ.
Reimplemented from Champ_Fonc_base.
Definition at line 72 of file Champ_Fonc_P1_isoP1Bulle.cpp.
{
  Champ_Fonc_base::mettre_a_jour(t);
}
References Champ_Fonc_base::mettre_a_jour().
printOn()
Sortie & Champ_Fonc_P1_isoP1Bulle::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 26 of file Champ_Fonc_P1_isoP1Bulle.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Fonc_P1_isoP1Bulle::readOn (Entree & s) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 34 of file Champ_Fonc_P1_isoP1Bulle.cpp.
{
  return s ;
}
remplir_coord_noeuds()
DoubleTab & Champ_Fonc_P1_isoP1Bulle::remplir_coord_noeuds (DoubleTab & coord) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
DoubleTab&
Signification: renvoie toujours le parametre coord
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 113 of file Champ_Fonc_P1_isoP1Bulle.h.
{
  return Champ_P1iP1B_implementation::remplir_coord_noeuds(positions);
}
References Champ_P1iP1B_implementation::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
int Champ_Fonc_P1_isoP1Bulle::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
int
Signification: renvoie toujours 0
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 117 of file Champ_Fonc_P1_isoP1Bulle.h.
{
  return Champ_P1iP1B_implementation::remplir_coord_noeuds_et_polys(positions,
                                                                    polys);
}
References Champ_P1iP1B_implementation::remplir_coord_noeuds_et_polys().
self_cast() [1/2]
const Champ_Fonc_P1_isoP1Bulle & Champ_Fonc_P1_isoP1Bulle::self_cast (const Objet_U & r) static
Definition at line 20 of file Champ_Fonc_P1_isoP1Bulle.cpp.
self_cast() [2/2]
Champ_Fonc_P1_isoP1Bulle & Champ_Fonc_P1_isoP1Bulle::self_cast (Objet_U & r) static
Definition at line 20 of file Champ_Fonc_P1_isoP1Bulle.cpp.
taille_memoire()
unsigned Champ_Fonc_P1_isoP1Bulle::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 20 of file Champ_Fonc_P1_isoP1Bulle.cpp.
trace()
DoubleTab & Champ_Fonc_P1_isoP1Bulle::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const override virtual
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
Returns
DoubleTab&
Signification: les valeurs du champ sur la frontiere au temps tps
Contraintes:
Reimplemented from Champ_base.
Definition at line 79 of file Champ_Fonc_P1_isoP1Bulle.cpp.
{
  return Champ_P1iP1B_implementation::trace(fr, valeurs(), x,distant);
}
References Champ_P1iP1B_implementation::trace(), and Champ_Don_base::valeurs().
valeur_a_elem()
DoubleVect & Champ_Fonc_P1_isoP1Bulle::valeur_a_elem (const DoubleVect & position, DoubleVect & val, int le_poly) const inline override virtual
Implements Champ_implementation.
Definition at line 79 of file Champ_Fonc_P1_isoP1Bulle.h.
{
  return Champ_P1iP1B_implementation::valeur_a_elem(position, val, le_poly);
}
References Champ_P1iP1B_implementation::valeur_a_elem().
valeur_a_elem_compo()
double Champ_Fonc_P1_isoP1Bulle::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline override virtual
Implements Champ_implementation.
Definition at line 85 of file Champ_Fonc_P1_isoP1Bulle.h.
{
  return Champ_P1iP1B_implementation::valeur_a_elem_compo(position, le_poly, ncomp);
}
References Champ_P1iP1B_implementation::valeur_a_elem_compo().
valeur_aux_elems()
DoubleTab & Champ_Fonc_P1_isoP1Bulle::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & tab_valeurs) const inline override virtual
Implements Champ_implementation.
Definition at line 90 of file Champ_Fonc_P1_isoP1Bulle.h.
{
  return Champ_P1iP1B_implementation::valeur_aux_elems(positions, les_polys, tab_valeurs);
}
References Champ_P1iP1B_implementation::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_Fonc_P1_isoP1Bulle::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & tab_valeurs, int ncomp) const inline override virtual
Implements Champ_implementation.
Definition at line 96 of file Champ_Fonc_P1_isoP1Bulle.h.
{
  return Champ_P1iP1B_implementation::valeur_aux_elems_compo(positions, les_polys,
                                                             tab_valeurs, ncomp);
}
References Champ_P1iP1B_implementation::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_Fonc_P1_isoP1Bulle::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const inline override virtual
Implements Champ_implementation.
Definition at line 104 of file Champ_Fonc_P1_isoP1Bulle.h.
{
  return Champ_P1iP1B_implementation::valeur_aux_sommets(dom, val);
}
References Champ_P1iP1B_implementation::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Fonc_P1_isoP1Bulle::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int comp) const inline override virtual
Implements Champ_implementation.
Definition at line 108 of file Champ_Fonc_P1_isoP1Bulle.h.
{
  return Champ_P1iP1B_implementation::valeur_aux_sommets_compo(dom, val, comp);
}
References Champ_P1iP1B_implementation::valeur_aux_sommets_compo().
zone_dis_base()
const Zone_dis_base & Champ_Fonc_P1_isoP1Bulle::zone_dis_base () const override virtual
Reimplemented from Champ_implementation.
Definition at line 57 of file Champ_Fonc_P1_isoP1Bulle.cpp.
{
  return la_zone_VEFP1B.valeur();
}
References la_zone_VEFP1B, and Ref_Zone_VEF_PreP1b::valeur().
zone_vef()
const Zone_VEF_PreP1b & Champ_Fonc_P1_isoP1Bulle::zone_vef () const inline override virtual
Implements Champ_P1iP1B_implementation.
Definition at line 126 of file Champ_Fonc_P1_isoP1Bulle.h.
{
  return la_zone_VEFP1B.valeur();
}
References la_zone_VEFP1B, and Ref_Zone_VEF_PreP1b::valeur().
Referenced by fixer_nb_valeurs_nodales().
Member Data Documentation
info_obj
const Type_info Champ_Fonc_P1_isoP1Bulle::info_obj static
Definition at line 31 of file Champ_Fonc_P1_isoP1Bulle.h.
la_zone_VEFP1B
Ref_Zone_VEF_PreP1b Champ_Fonc_P1_isoP1Bulle::la_zone_VEFP1B protected
Definition at line 61 of file Champ_Fonc_P1_isoP1Bulle.h.
Referenced by associer_zone_dis_base(), zone_dis_base(), and zone_vef().
The documentation for this class was generated from the following files:
src/P1NCP1B/Champs/Champ_Fonc_P1_isoP1Bulle.h
src/P1NCP1B/Champs/Champ_Fonc_P1_isoP1Bulle.cpp