TRUST: Op_Div_VEFP1B_Elem Class Reference
Op_Div_VEFP1B_Elem Class Reference
#include <Op_Div_VEFP1B_Elem.h>
Public Member Functions
Op_Div_VEFP1B_Elem ()
~Op_Div_VEFP1B_Elem ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & ajouter_elem (const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_som (const DoubleTab &, DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_aretes (const DoubleTab &, DoubleTab &) const
void degres_liberte () const
void volumique (DoubleTab &) const override
void dimensionner (FMatrice_Morse &) const
void dimensionner (Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void modifier_pour_Cl (FMatrice_Morse &, DoubleTab &) const
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, FMatrice_Morse &) const
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_au_second_membre (DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Public Member Functions inherited from Op_Div_VEF_Elem
Op_Div_VEF_Elem ()
~Op_Div_VEF_Elem ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void volumique (DoubleTab &) const override
Public Member Functions inherited from Operateur_Div_base
Operateur_Div_base ()
~Operateur_Div_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleVect & multvect (const DoubleTab &, DoubleTab &) const
virtual void volumique (DoubleTab &) const =0
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Div_VEFP1B_Elem & self_cast (Objet_U &)
static const Op_Div_VEFP1B_Elem & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Div_VEF_Elem
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Div_VEF_Elem & self_cast (Objet_U &)
static const Op_Div_VEF_Elem & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Div_base
static const Type_info * info ()
static Operateur_Div_base & self_cast (Objet_U &)
static const Operateur_Div_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Div_VEF_Elem
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Div_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
Protected Member Functions inherited from Op_Div_VEF_Elem
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Private Attributes
IntVect nb_degres_liberte
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Protected Attributes inherited from Op_Div_VEF_Elem
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 25 of file Op_Div_VEFP1B_Elem.h.
Constructor & Destructor Documentation
Op_Div_VEFP1B_Elem()
Op_Div_VEFP1B_Elem::Op_Div_VEFP1B_Elem ()
Definition at line 36 of file Op_Div_VEFP1B_Elem.cpp.
~Op_Div_VEFP1B_Elem()
Op_Div_VEFP1B_Elem::~Op_Div_VEFP1B_Elem ()
Definition at line 36 of file Op_Div_VEFP1B_Elem.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Div_VEFP1B_Elem::ajouter (const DoubleTab & vitesse_face_absolue, DoubleTab & div) const override virtual
Reimplemented from Operateur_base.
Definition at line 566 of file Op_Div_VEFP1B_Elem.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,la_zone_vef.valeur());
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
// Quelques verifications:
// L'espace virtuel de vitesse_face_absolue doit etre a jour (Le test est fait si check_enabled==1)
  assert_espace_virtuel_vect(vitesse_face_absolue);
// On s'en fiche de l'espace virtuel de div a l'entree, mais on fait += dessus.
  assert_invalide_items_non_calcules(div, 0.);
#ifndef NDEBUG
// On s'assure que la periodicite est respectee sur vitesse_face_absolue (Voir FA814)
  int nb_comp=vitesse_face_absolue.dimension(1);
  for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int nb_faces_bord=le_bord.nb_faces();
          for (int ind_face=0; ind_face<nb_faces_bord; ind_face++)
            {
              int ind_face_associee = la_cl_perio.face_associee(ind_face);
              int face = le_bord.num_face(ind_face);
              int face_associee = le_bord.num_face(ind_face_associee);
// PL : test a 1.e-4 car certains cas ne respectent pas strictement (lente derive?)
              for (int comp=0; comp<nb_comp; comp++)
                if (!est_egal(vitesse_face_absolue(face, comp),vitesse_face_absolue(face_associee, comp),1.e-4))
                  {
                    Cerr << "vit1("<<face<<","<<comp<<")=" << vitesse_face_absolue(face, comp) << finl;
                    Cerr << "vit2("<<face_associee<<","<<comp<<")=" << vitesse_face_absolue(face_associee, comp) << finl;
                    Cerr << "Delta=" << vitesse_face_absolue(face, comp)-vitesse_face_absolue(face_associee, comp) << finl;
                    Cerr << "Periodic boundary condition is not correct in Op_Div_VEFP1B_Elem::ajouter" << finl;
                    Cerr << "Contact TRUST support." << finl;
                    exit();
                  }
            }//!< for face
        }//!< sub_type Perio
    }
#endif
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  DoubleTab phi_vitesse_face_;
  const DoubleTab& vit=modif_par_porosite_si_flag(vitesse_face_absolue,phi_vitesse_face_,1,porosite_face);
// Tableau des degres de liberte
  int nps=zone_VEF.numero_premier_sommet();
  nb_degres_liberte.resize(zone_VEF.zone().nb_som_tot());
  nb_degres_liberte=-1;
  DoubleTab& flux_b = flux_bords_;
  flux_b.resize(zone_VEF.nb_faces_bord(),1);
  flux_b = 0.;
  static int init=1;
  if(!init) ::verifier(*this, init, zone_VEF, vit, div);
  if(zone_VEF.get_alphaE()) ajouter_elem(vit, div);
  if(zone_VEF.get_alphaS()) ajouter_som(vit, div, flux_b);
  if(zone_VEF.get_alphaA()) ajouter_aretes(vit, div);
// correction de de div u si pression sommet imposee de maniere forte
  if ((zone_VEF.get_alphaS())&&((zone_VEF.get_cl_pression_sommet_faible()==0)))
    {
      const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
      int nb_bords =les_cl.size();
      for (int n_bord=0; n_bord<nb_bords; n_bord++)
        {
          const Cond_lim& la_cl = les_cl[n_bord];
          if (sub_type(Neumann,la_cl.valeur()) || sub_type(Neumann_val_ext,la_cl.valeur()))
            {
              const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
              const IntTab& faces_sommets = zone_VEF.face_sommets();
              int nb_faces=la_front_dis.nb_faces_tot();
              int nsf=0;
              if(nb_faces!=0)
                nsf=faces_sommets.dimension(1);
              int num2 = nb_faces;
              for (int ind_face=0; ind_face<num2; ind_face++)
                {
                  int face=la_front_dis.num_face(ind_face);
                  for(int som=0; som<nsf; som++)
                    {
                      int som1=faces_sommets(face, som);
                      div(nps+som1) = 0.;
                    }
                }
            }
        }
    }
  degres_liberte();
// Optimisation, pas necessaire:
// div.echange_espace_virtuel();
  return div;
}
References ajouter_aretes(), ajouter_elem(), ajouter_som(), assert_espace_virtuel_vect(), assert_invalide_items_non_calcules(), Cerr, degres_liberte(), TRUSTTab< _TYPE_ >::dimension(), est_egal(), Process::exit(), Periodique::face_associee(), face_associee, Zone_VF::face_sommets(), finl, Operateur_base::flux_bords_, Cond_lim::frontiere_dis(), Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Zone_VEF_PreP1b::get_cl_pression_sommet_faible(), Op_Div_VEF_Elem::la_zcl_vef, Op_Div_VEF_Elem::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), modif_par_porosite_si_flag(), nb_degres_liberte, Front_VF::nb_faces(), Zone_VF::nb_faces_bord(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Zone::nb_som_tot(), Front_VF::num_face(), Zone_VEF_PreP1b::numero_premier_sommet(), Zone_VF::porosite_face(), ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), verifier(), and Zone_dis_base::zone().
Referenced by verifier().
ajouter_aretes()
DoubleTab & Op_Div_VEFP1B_Elem::ajouter_aretes (const DoubleTab & vit, DoubleTab & div) const
Definition at line 428 of file Op_Div_VEFP1B_Elem.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,la_zone_vef.valeur());
  assert(zone_VEF.get_alphaA());
  const Zone& zone = zone_VEF.zone();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const IntTab& som_elem=zone.les_elems();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const ArrOfInt& renum_arete_perio=zone_VEF.get_renum_arete_perio();
  const ArrOfInt& ok_arete=zone_VEF.get_ok_arete();
  int npa=zone_VEF.numero_premiere_arete();
  int nb_elem_tot=zone.nb_elem_tot();
  int elem,comp;
  ArrOfDouble sigma(dimension);
  const IntTab& aretes_som=zone_VEF.zone().aretes_som();
  const IntTab& elem_aretes=zone_VEF.zone().elem_aretes();
  for(elem=0; elem<nb_elem_tot; elem++)
    {
      for(int isom=0; isom<3; isom++)
        {
          int somi = som_elem(elem,isom);
          int facei = elem_faces(elem,isom);
          double signei=1.;
          if (face_voisins(facei,0) != elem)
            signei=-1.;
          for(int jsom=isom+1; jsom<4; jsom++)
            {
              int somj = som_elem(elem,jsom);
              int facej = elem_faces(elem,jsom);
              double signej=1.;
              if (face_voisins(facej,0) != elem)
                signej=-1.;
              int arete = renum_arete_perio[chercher_arete(elem, somi, somj,
                                                           elem_aretes, aretes_som)];
              if(ok_arete[arete])
                {
                  int niinij=0;
                  for(int ksom=0; ksom<4; ksom++)
                    {
                      if((ksom==isom)||(ksom==jsom))
{
                          if(niinij==ksom)
                            niinij++;
                          double psc=0;
                          for(comp=0; comp<3; comp++)
                            psc+=(signei*face_normales(facei,comp)+
                                  signej*face_normales(facej,comp))
                                 *vit(elem_faces(elem,ksom),comp);
                          div(npa+arete)-=1./15.*psc;
                        }
                      else
{
                          if(niinij==ksom)
                            niinij++;
                          while((niinij==jsom)||(niinij==isom))
                            niinij++;
                          assert(niinij<4);
                          assert(niinij!=isom);
                          assert(niinij!=jsom);
                          assert(niinij!=ksom);
                          int facek = elem_faces(elem,niinij);
                          double signek=1.;
                          if (face_voisins(facek,0) != elem)
                            signek=-1.;
                          double psc=0;
                          for(comp=0; comp<3; comp++)
                            psc+=signek*face_normales(facek,comp)
                                 *vit(elem_faces(elem,ksom),comp);
                          div(npa+arete)-=2./15.*psc;
                          niinij=ksom;
                        }
                    }
                }
            }
        }
    }
  return div;
}
References Zone::aretes_som(), chercher_arete(), Objet_U::dimension, Zone::elem_aretes(), Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_ok_arete(), Zone_VEF_PreP1b::get_renum_arete_perio(), Op_Div_VEF_Elem::la_zone_vef, Zone::les_elems(), Zone::nb_elem_tot(), Zone_VEF_PreP1b::numero_premiere_arete(), ref_cast, Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_elem()
DoubleTab & Op_Div_VEFP1B_Elem::ajouter_elem (const DoubleTab & vit, DoubleTab & div) const
Definition at line 101 of file Op_Div_VEFP1B_Elem.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,la_zone_vef.valeur());
  assert(zone_VEF.get_alphaE());
  const Zone& zone = zone_VEF.zone();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  int nfe=zone.nb_faces_elem();
  int nb_elem=zone.nb_elem();
  int elem,indice,face,comp;
  double pscf,signe;
  for(elem=0; elem<nb_elem; elem++)
    {
      pscf=0;
      for(indice=0; indice<nfe; indice++)
        {
          face = elem_faces(elem,indice);
          signe=1;
          if(elem!=face_voisins(face,0))
            signe=-1;
          for(comp=0; comp<dimension; comp++)
            pscf+=signe*vit(face, comp)*
                  face_normales(face,comp);
        }
      div(elem)+=pscf;
    }
  assert_invalide_items_non_calcules(div);
  return div;
}
References assert_invalide_items_non_calcules(), Objet_U::dimension, Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Zone_VEF_PreP1b::get_alphaE(), Op_Div_VEF_Elem::la_zone_vef, Zone::nb_elem(), Zone::nb_faces_elem(), ref_cast, Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_som()
DoubleTab & Op_Div_VEFP1B_Elem::ajouter_som (const DoubleTab & vit, DoubleTab & div, DoubleTab & flux_b) const
Definition at line 299 of file Op_Div_VEFP1B_Elem.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,la_zone_vef.valeur());
  assert(zone_VEF.get_alphaS());
  const Zone& zone = zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const IntTab& som_elem=zone.les_elems();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  int nfe=zone.nb_faces_elem();
  int nb_elem_tot=zone.nb_elem_tot();
  int nps=zone_VEF.numero_premier_sommet();
  int elem,indice,face,comp,som;
  ArrOfDouble sigma(dimension);
  int nb_face_diri=0;
  double coeff_som=1./(dimension*(dimension+1));
  int modif_traitement_diri=zone_VEF.get_modif_div_face_dirichlet();
  double psc, signe;
  const Zone_Cl_VEF& zcl=ref_cast(Zone_Cl_VEF,la_zcl_vef.valeur());
  ArrOfInt indice_diri(dimension+1);
  for(elem=0; elem<nb_elem_tot; elem++)
    {
      if (modif_traitement_diri)
        coeff_som=calculer_coef_som(elem,nb_face_diri,indice_diri,zcl,zone_VEF);
      sigma = 0;
      for(indice=0; indice<nfe; indice++)
        {
          face = elem_faces(elem,indice);
          for(comp=0; comp<dimension; comp++)
            {
              sigma[comp]+=vit(face, comp);
            }
        }
// on retire la contribution des faces dirichlets
      for (int fdiri=0; fdiri<nb_face_diri; fdiri++)
        {
          int indice2=indice_diri[fdiri];
          face = elem_faces(elem,indice2);
          for(comp=0; comp<dimension; comp++)
            {
              sigma[comp]-=vit(face, comp);
            }
        }
      for(indice=0; indice<nfe; indice++)
        {
          som = nps+dom.get_renum_som_perio(som_elem(elem,indice));
          face = elem_faces(elem,indice);
          psc=0;
          signe=1;
          if(elem!=face_voisins(face,0))
            signe=-1;
          for(comp=0; comp<dimension; comp++)
            {
              psc+=sigma[comp]*face_normales(face,comp);
            }
          div(som)+=signe*coeff_som*psc;
          nb_degres_liberte(som-nps)++;
        }
    }
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_sommets = zone_VEF.face_sommets();
  int nb_bords =les_cl.size();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      {
        const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
        int nb_faces_bord = le_bord.nb_faces();
        int nb_faces_bord_tot = le_bord.nb_faces_tot();
        assert(le_bord.nb_faces()==zone_VEF.zone().frontiere(n_bord).nb_faces());
        if (!sub_type(Periodique,la_cl.valeur()))
          {
            int libre=1;
            if (sub_type(Dirichlet,la_cl.valeur())
                ||sub_type(Dirichlet_homogene,la_cl.valeur())
                ||sub_type(Dirichlet_entree_fluide,la_cl.valeur())
                ||sub_type(Symetrie,la_cl.valeur()))
              libre=0;
// On boucle sur les faces de bord reelles et virtuelles
            for (int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
              {
                face = le_bord.num_face(ind_face);
                double flux = 0. ;
                for (comp=0; comp<dimension; comp++)
                  {
                    flux += vit(face,comp) * face_normales(face,comp) ;
                  }
                if (ind_face<nb_faces_bord) flux_b(face,0) = flux;
                flux*=1./dimension;
                for(indice=0; indice<(nfe-1); indice++)
                  {
                    som=dom.get_renum_som_perio(face_sommets(face,indice));
                    div(nps+som)+=flux;
                    if (libre) nb_degres_liberte(som)++;
                  }
              }
          }
        else
          {
            const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
// On boucle sur les faces de bord reelles et virtuelles
            for (int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
              {
                face = le_bord.num_face(ind_face);
                int face_associee = le_bord.num_face(la_cl_perio.face_associee(ind_face));
                double flux = 0. ;
                double flux_perio = 0. ;
                for (comp=0; comp<dimension; comp++)
                  {
                    flux += vit(face,comp) * face_normales(face,comp) ;
                    flux_perio += vit(face_associee,comp) * face_normales(face_associee,comp) ;
                  }
                if (ind_face<(nb_faces_bord/2))
                  {
                    flux_b(face,0) = -flux;
                    flux_b(face_associee,0) = flux_perio;
                  }
              }
          }
      }
    }
  return div;
}
References calculer_coef_som(), Objet_U::dimension, Zone::domaine(), Zone_VF::elem_faces(), Periodique::face_associee(), face_associee, Zone_VEF::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), Zone::frontiere(), Cond_lim::frontiere_dis(), Zone_VEF_PreP1b::get_alphaS(), Zone_VEF_PreP1b::get_modif_div_face_dirichlet(), Domaine::get_renum_som_perio(), Op_Div_VEF_Elem::la_zcl_vef, Op_Div_VEF_Elem::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), nb_degres_liberte, Zone::nb_elem_tot(), Frontiere::nb_faces(), Front_VF::nb_faces(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Zone_VEF_PreP1b::numero_premier_sommet(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
contribuer_a_avec() [1/2]
void Op_Div_VEFP1B_Elem::contribuer_a_avec (const DoubleTab & , FMatrice_Morse &) const inline
Definition at line 44 of file Op_Div_VEFP1B_Elem.h.
{};
contribuer_a_avec() [2/2]
void Op_Div_VEFP1B_Elem::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 45 of file Op_Div_VEFP1B_Elem.h.
{};
contribuer_au_second_membre()
void Op_Div_VEFP1B_Elem::contribuer_au_second_membre (DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 46 of file Op_Div_VEFP1B_Elem.h.
{};
cree_instance()
Objet_U * Op_Div_VEFP1B_Elem::cree_instance () static
Definition at line 36 of file Op_Div_VEFP1B_Elem.cpp.
degres_liberte()
void Op_Div_VEFP1B_Elem::degres_liberte () const
< on parcourt les sommets de elem_opp
< on parcourt les sommets de elem
< sommets de la face commune
< Face virtuelle
Definition at line 725 of file Op_Div_VEFP1B_Elem.cpp.
{
// On annulle la divergence aux sommets sans degre de liberte
// (sommet uniquement commun a des faces avec des CL Diriclet)
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,la_zone_vef.valeur());
  const Zone& zone = zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  const IntTab& som_elem=zone.les_elems();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const int nse=zone.nb_som_elem();
  int nb_faces_tot = zone_VEF.nb_faces_tot();
  Sortie& journal = Process::Journal();
  int afficher_message = 0;
  int nb_som=zone.nb_som();
  int ecrire_decoupage_som=0;
  int decoupage_som=0;
// On n'ecrit qu'une seule fois le fichier decoupage_som
// et uniquement en sequentiel
  if (Process::nproc()==1 && equation().schema_temps().nb_pas_dt()==0)
    decoupage_som=1;
// SFichier* os=NULL;
  SChaine decoup_som;
  decoup_som << "1" << finl;
  decoup_som << Objet_U::dimension << " " << nb_som << finl;
  IntVect somm(dimension+2);
  for (int k=0; k<nb_som; k++)
    {
      int sommet = dom.get_renum_som_perio(k);
      if (nb_degres_liberte(sommet) != 0)
        continue;
      if (!afficher_message && VerifierCoin::expert_only==0)
        {
          afficher_message = 1;
          Cerr << finl << "Problem with the mesh used for the VEF P1Bulle discretization." << finl;
          journal << "List of nodes with no degrees of freedom :" << finl;
        }
      const double x = dom.coord(sommet, 0);
      const double y = dom.coord(sommet, 1);
      const double z = (Objet_U::dimension==3) ? dom.coord(sommet, 2) : 0.;
      journal << "Error node " << sommet << " ( " << x << " " << y << " " << z << " )\n";
// On affiche la liste des indices d'elements reels et virtuels qui contiennent
// ce sommet. On affiche la lettre "v" pour les elements virtuels.
      journal << "Elements ";
      const int nb_elem_tot = zone.nb_elem_tot();
      const int nb_elem     = zone.nb_elem();
      for (int elem = 0; elem < nb_elem_tot; elem++)
        for(int som = 0; som < nse; som++)
          if (som_elem(elem, som) == sommet)
            {
              journal << elem << ((elem>=nb_elem)?"v ":" ");
// Ecriture dans le fichier decoupage_som
              int face_opp=elem_faces(elem,som);
              int elem_opp;
              somm=-1;
              somm(0)=sommet;
              int elem1 = face_voisins(face_opp,0);
              int elem2 = face_voisins(face_opp,1);
              if (elem1==elem)
                elem_opp=elem2;
              else
                elem_opp=elem1;
              int i=2;
              for(int som1=0; som1<nse; som1++)  //!< on parcourt les sommets de elem_opp
                {
                  int ok=1;
                  for(int som2=0; som2<nse; som2++)  //!< on parcourt les sommets de elem
                    if ( som_elem(elem, som2)==som_elem(elem_opp, som1) )
                      ok=0;
                  if (ok) somm(1)=som_elem(elem_opp, som1);
                  else
                    {
                      somm(i)=som_elem(elem_opp, som1);  //!< sommets de la face commune
                      i++;
                    }
                }
              if (decoupage_som)
                {
                  ecrire_decoupage_som=1;
                  for (int j=0; j<dimension+2; j++)
                    decoup_som << somm(j) << " " ;
                  decoup_som << elem << " " << elem_opp << finl;
                }
            }
      journal << "\n";
// On affiche la liste des faces qui contiennent ce sommet.
// Pour les faces de bord, on affiche la condlim,
// pour les faces virtuelles, la lettre "v"
      journal << "\nFaces ";
      const int nb_faces = zone_VEF.nb_faces();
      const int nb_som_face = zone_VEF.face_sommets().dimension(1);
      for (int face = 0; face < nb_faces_tot; face++)
        {
          for (int som = 0; som < nb_som_face; som++)
            {
              if (zone_VEF.face_sommets(face, som) == sommet)
                {
                  journal << face;
                  if (face >= nb_faces) //!< Face virtuelle
                    journal << "v";
                  const int cl = find_cl_face(zone, face);
// Face de bord reelle:
                  if (cl >= 0)
                    {
                      const Nom& nom_bord = zone.frontiere(cl).le_nom();
                      journal << "(boundary=" << nom_bord << ")";
                    }
                  journal << " ";
                }
            }
        }
      journal << finl;
    }
  if (ecrire_decoupage_som)
    {
      decoup_som << "-1";
      SFichier fic(Objet_U::nom_du_cas()+".decoupage_som");
      fic << decoup_som.get_str() << finl;
      fic.close();
    }
  if (afficher_message && VerifierCoin::expert_only==0)
    {
      Nom nom_fichier(nom_du_cas());
      Cerr << "Look at the .log file of processor " << Process::me() << " to know which nodes" << finl;
      Cerr << "do not have enough degrees of freedom. You can also visualize" << finl;
      Cerr << "your mesh to identify which elements have a problem and" << finl;
      Cerr << "remesh your domain close to these nodes so that these have" << finl;
      Cerr << "at least a degree of freedom." << finl;
      Cerr << "The VEF P1Bulle discretization is not compatible with this type" << finl;
      Cerr << "of mesh and boundary conditions used (Dirichlet, Symmetry ,...)" << finl << finl;
      Cerr << "Other possibility, in your data file:"<<finl;
      if (dimension==2)
        Cerr << "If you have used \"Trianguler\", substituted by \"Trianguler_H\"." << finl << finl;
      if (dimension==3)
        Cerr << "If you have used \"Tetraedriser\", substituted by \"Tetraedriser_homogene\" or \"Tetraedriser_par_prisme\"." << finl << finl;
      Cerr << "Or insert the line:" << finl;
      Cerr << "VerifierCoin " << dom.le_nom() << " { [Read_file " << nom_fichier << ".decoupage_som] }" << finl;
      Cerr << "after the mesh is finished to be read and built." << finl;
      if (Process::nproc()>1)
        Cerr << "and BEFORE the keyword \"Decouper\" during the partition of the mesh." << finl;
      else
        Cerr << "and BEFORE the keyword \"Discretiser\"." << finl;
      Cerr << "A few cells will be divided into 3 (2D) or 4 (3D)." << finl;
      Cerr << finl;
      Cerr << "Last possibility, it is possible now for experimented users to not check if there is enough degrees of freedom" << finl;
      Cerr << "by adding the next line BEFORE the keyword \"Discretiser\":" << finl;
      Cerr << "VerifierCoin " << dom.le_nom() << " { expert_only } " << finl;
      Cerr << "In this case, check the results carefully." << finl;
      exit();
    }
}
References Cerr, Sortie_Fichier_base::close(), Domaine::coord(), Objet_U::dimension, Zone::domaine(), Zone_VF::elem_faces(), MorEqn::equation(), Process::exit(), VerifierCoin::expert_only, Zone_VF::face_sommets(), Zone_VF::face_voisins(), find_cl_face(), finl, Zone::frontiere(), Domaine::get_renum_som_perio(), SChaine::get_str(), Process::Journal(), Op_Div_VEF_Elem::la_zone_vef, Domaine::le_nom(), Frontiere::le_nom(), Zone::les_elems(), Process::me(), nb_degres_liberte, Zone::nb_elem(), Zone::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Zone::nb_som(), Zone::nb_som_elem(), Objet_U::nom_du_cas(), nom_fichier(), Process::nproc(), ref_cast, Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
dimensionner() [1/2]
void Op_Div_VEFP1B_Elem::dimensionner (FMatrice_Morse &) const inline
Definition at line 40 of file Op_Div_VEFP1B_Elem.h.
{};
dimensionner() [2/2]
void Op_Div_VEFP1B_Elem::dimensionner (Matrice_Morse & mat) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 41 of file Op_Div_VEFP1B_Elem.h.
{};
duplique()
int Op_Div_VEFP1B_Elem::duplique () const override virtual
Implements Objet_U.
Definition at line 36 of file Op_Div_VEFP1B_Elem.cpp.
get_info()
const Type_info * Op_Div_VEFP1B_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Div_base.
Definition at line 36 of file Op_Div_VEFP1B_Elem.cpp.
info()
const Type_info * Op_Div_VEFP1B_Elem::info () static
Definition at line 36 of file Op_Div_VEFP1B_Elem.cpp.
modifier_pour_Cl() [1/2]
void Op_Div_VEFP1B_Elem::modifier_pour_Cl (FMatrice_Morse & , DoubleTab &) const inline
Definition at line 42 of file Op_Div_VEFP1B_Elem.h.
{};
modifier_pour_Cl() [2/2]
void Op_Div_VEFP1B_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 43 of file Op_Div_VEFP1B_Elem.h.
{};
printOn()
Sortie & Op_Div_VEFP1B_Elem::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Div_base.
Definition at line 40 of file Op_Div_VEFP1B_Elem.cpp.
{
  return s;
}
readOn()
Entree & Op_Div_VEFP1B_Elem::readOn (Entree & is) override protected virtual
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Div_base.
Definition at line 45 of file Op_Div_VEFP1B_Elem.cpp.
{
  return is;
}
self_cast() [1/2]
const Op_Div_VEFP1B_Elem & Op_Div_VEFP1B_Elem::self_cast (const Objet_U & r) static
Definition at line 36 of file Op_Div_VEFP1B_Elem.cpp.
self_cast() [2/2]
Op_Div_VEFP1B_Elem & Op_Div_VEFP1B_Elem::self_cast (Objet_U & r) static
Definition at line 36 of file Op_Div_VEFP1B_Elem.cpp.
taille_memoire()
unsigned Op_Div_VEFP1B_Elem::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 36 of file Op_Div_VEFP1B_Elem.cpp.
volumique()
void Op_Div_VEFP1B_Elem::volumique (DoubleTab & div) const override virtual
Implements Operateur_Div_base.
Definition at line 699 of file Op_Div_VEFP1B_Elem.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,la_zone_vef.valeur());
  int n=0;
  if (zone_VEF.get_alphaE())
    {
      Op_Div_VEF_Elem::volumique(div);
      n+=zone_VEF.nb_elem_tot();
    }
  if (zone_VEF.get_alphaS())
    {
      const DoubleVect& vol = zone_VEF.volume_aux_sommets();
      int size_tot = vol.size_totale();
      for (int i=0; i<size_tot; i++)
        div(n+i)/=vol(i);
      n+=zone_VEF.nb_som_tot();
    }
  if (zone_VEF.get_alphaA())
    {
      const DoubleVect& vol = zone_VEF.get_volumes_aretes();
      int size_tot = vol.size_totale();
      for (int i=0; i<size_tot; i++)
        div(n+i)/=vol(i);
    }
}
References Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Zone_VEF_PreP1b::get_volumes_aretes(), Op_Div_VEF_Elem::la_zone_vef, Zone_dis_base::nb_elem_tot(), Zone_dis_base::nb_som_tot(), ref_cast, TRUSTVect< _TYPE_ >::size_totale(), Ref_Zone_VEF::valeur(), Zone_VEF_PreP1b::volume_aux_sommets(), and Op_Div_VEF_Elem::volumique().
Member Data Documentation
info_obj
const Type_info Op_Div_VEFP1B_Elem::info_obj static
Definition at line 28 of file Op_Div_VEFP1B_Elem.h.
nb_degres_liberte
IntVect Op_Div_VEFP1B_Elem::nb_degres_liberte mutable private
Definition at line 48 of file Op_Div_VEFP1B_Elem.h.
Referenced by ajouter(), ajouter_som(), and degres_liberte().
The documentation for this class was generated from the following files:
src/P1NCP1B/Operateurs/Op_Div_VEFP1B_Elem.h
src/P1NCP1B/Operateurs/Op_Div_VEFP1B_Elem.cpp