TRUST: Rotation Class Reference
Rotation Class Reference
Classe Rotation
Applique une rotation autour d un axe aligne avec un des axes du repere.
Structure du jeu de donnee :
Rotation nom_domaine nom_axe coord1 coord2 angle
nom_domaine : nom du domaine auquelon applique une rotation
nom_axe : axe (X, Y ou Z) avec lequel est aligne l axe de rotation
coord1 coord2 : coordonnees (sens dtrigonometrique direct) du centre de rotation
dans le plan orthogonal a l axe de rotation.
#include <Rotation.h>
Public Member Functions
Rotation ()
~Rotation ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
Public Member Functions inherited from Transformer
Transformer ()
~Transformer ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
void transformer (Domaine &, Noms &)
void transformation_complete (Noms &les_fcts)
void verifie_type_elem ()
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Rotation & self_cast (Objet_U &)
static const Rotation & self_cast (const Objet_U &)
Static Public Member Functions inherited from Transformer
static Objet_U * cree_instance ()
static const Type_info * info ()
static Transformer & self_cast (Objet_U &)
static const Transformer & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Transformer
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Transformer::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Transformer::ReadOn(Sortie&)
Protected Member Functions inherited from Transformer
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Classe Rotation
Applique une rotation autour d un axe aligne avec un des axes du repere.
Structure du jeu de donnee :
Rotation nom_domaine nom_axe coord1 coord2 angle
nom_domaine : nom du domaine auquelon applique une rotation
nom_axe : axe (X, Y ou Z) avec lequel est aligne l axe de rotation
coord1 coord2 : coordonnees (sens dtrigonometrique direct) du centre de rotation
dans le plan orthogonal a l axe de rotation.
Definition at line 34 of file Rotation.h.
Constructor & Destructor Documentation
Rotation()
Rotation::Rotation ()
Definition at line 18 of file Rotation.cpp.
~Rotation()
Rotation::~Rotation ()
Definition at line 18 of file Rotation.cpp.
Member Function Documentation
cree_instance()
Objet_U * Rotation::cree_instance () static
Definition at line 18 of file Rotation.cpp.
duplique()
int Rotation::duplique () const override virtual
Implements Objet_U.
Definition at line 18 of file Rotation.cpp.
get_info()
const Type_info * Rotation::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 18 of file Rotation.cpp.
info()
const Type_info * Rotation::info () static
Definition at line 18 of file Rotation.cpp.
interpreter_()
Entree & Rotation::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base.
Definition at line 59 of file Rotation.cpp.
{
  associer_domaine(is);
  verifie_type_elem();
  Noms les_fcts;
  les_fcts.dimensionner(dimension);
  int dir_axe,dir1,dir2;
  double coor1,coor2,angle;
  Nom axe_direction,nomc1,nomc2,nomang;
  Nom var1,var2,var_axe;
  double pi = M_PI;
  is>>axe_direction;
//
  dir_axe=-1;
  if (Motcle(axe_direction)=="X")
    dir_axe=0;
  else if (Motcle(axe_direction)=="Y")
    dir_axe=1;
  else if (Motcle(axe_direction)=="Z")
    dir_axe=2;
  else
    {
      Cerr<<"The direction of the rotation axis must be specified by X, Y or Z"<<finl;
      exit();
    }
  is>>coor1>>coor2>>angle;
  angle = (2*pi)*(angle/360.);
  nomc1 = Nom(coor1);
  nomc2 = Nom(coor2);
  nomang = Nom(angle);
  dir1=-1;
  dir2=-1;
  if (dimension==3)
    {
      if (dir_axe==0)
        {
          var1="(y-";
          var2="(z-";
          var_axe="x";
          dir1=1;
          dir2=2;
        }
      else if (dir_axe==1)
        {
          var1="(z-";
          var2="(x-";
          var_axe="y";
          dir1=2;
          dir2=0;
        }
      else if (dir_axe==2)
        {
          var1="(x-";
          var2="(y-";
          var_axe="z";
          dir1=0;
          dir2=1;
        }
      les_fcts[dir_axe] = var_axe;
    }
  else
    {
      var1="(x-";
      var2="(y-";
      dir1=0;
      dir2=1;
    }
  les_fcts[dir1] = var1;
  les_fcts[dir1] += "(";
  les_fcts[dir1] += nomc1;
  les_fcts[dir1] += ")";
  les_fcts[dir1] += ")*cos(";
  les_fcts[dir1] += nomang;
  les_fcts[dir1] += ")-";
  les_fcts[dir1] += var2;
  les_fcts[dir1] += "(";
  les_fcts[dir1] += nomc2;
  les_fcts[dir1] += ")";
  les_fcts[dir1] += ")*sin(";
  les_fcts[dir1] += nomang;
  les_fcts[dir1] += ")";
  les_fcts[dir1] += "+(";
  les_fcts[dir1] += nomc1;
  les_fcts[dir1] += ")";
  les_fcts[dir2] = var1;
  les_fcts[dir2] += "(";
  les_fcts[dir2] += nomc1;
  les_fcts[dir2] += ")";
  les_fcts[dir2] += ")*sin(";
  les_fcts[dir2] += nomang;
  les_fcts[dir2] += ")+";
  les_fcts[dir2] += var2;
  les_fcts[dir2] += "(";
  les_fcts[dir2] += nomc2;
  les_fcts[dir2] += ")";
  les_fcts[dir2] += ")*cos(";
  les_fcts[dir2] += nomang;
  les_fcts[dir2] += ")";
  les_fcts[dir2] += "+(";
  les_fcts[dir2] += nomc2;
  les_fcts[dir2] += ")";
  transformation_complete(les_fcts);
  return is;
}
References Interprete_geometrique_base::associer_domaine(), Cerr, Objet_U::dimension, vect_impl::dimensionner(), Process::exit(), finl, M_PI, Transformer::transformation_complete(), and Transformer::verifie_type_elem().
printOn()
Sortie & Rotation::printOn (Sortie & os) const override protected virtual
Simple appel a: Transformer::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 35 of file Rotation.cpp.
{
  return Transformer::printOn(os);
}
References Transformer::printOn().
readOn()
Entree & Rotation::readOn (Entree & is) override protected virtual
Simple appel a: Transformer::ReadOn(Sortie&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 54 of file Rotation.cpp.
{
  return Transformer::readOn(is);
}
References Transformer::readOn().
self_cast() [1/2]
const Rotation & Rotation::self_cast (const Objet_U & r) static
Definition at line 18 of file Rotation.cpp.
self_cast() [2/2]
Rotation & Rotation::self_cast (Objet_U & r) static
Definition at line 18 of file Rotation.cpp.
taille_memoire()
unsigned Rotation::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 18 of file Rotation.cpp.
Member Data Documentation
info_obj
const Type_info Rotation::info_obj static
Definition at line 36 of file Rotation.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Rotation.h
src/Kernel/Geometrie/Rotation.cpp