TRUST: Sonde Class Reference
Sonde Class Reference
classe Sonde
Cette classe permet d'effectuer l'evolution d'un champ au cours du temps.
On choisit l'ensemble des points sur lesquels on veut sonder un champ et
la periodicite des observations. Les objets Postraitement porte des
des sondes sur les champs a observer, une sonde porte d'ailleurs une
reference sur un postraitement.
#include <Sonde.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Sonde ()
Constructeur d'une sonde sans paramètre.
Sonde (const Nom &)
Constructeur d'une sonde a partir de son nom.
void associer_post (const Postraitement &)
Associer le postraitement a la sonde.
void initialiser ()
Initialise la sonde. Dimensionne les tableaux,
de valeurs, verifie si les points specifies sont
bien dans la zone de calcul.
void mettre_a_jour (double temps, double tinit)
Effectue une mise a jour en temps de la sonde
effectue le postraitement.
void postraiter ()
Effectue un postraitement.
Calcul les valeurs du champ aux position demandees
et les imprime sur le fichier associe.
void ouvrir_fichier ()
Ouvre le fichier associe a la sonde. (*.son)
void completer ()
void fermer_fichier ()
Ferme le fichier sur laquelle la sonde ecrit.
const Champ_Generique_base & le_champ () const
Renvoie le champ associe.
const DoubleTab & les_positions_sondes_initiales () const
Positions initiales.
const DoubleTab & les_positions_sondes () const
Positions apres deplacement.
const DoubleTab & les_positions () const
Positions locales au proc.
const IntVect & les_poly () const
Renvoie le tableau des elements qui sont sondes.
void fixer_periode (double)
Fixe la periode avec laquelle on sonde le champ.
double temps () const
Le temps ecoule.
SFichier & fichier ()
Renvoie un flot de sortie Fichier, pointant sur
le fichier de sortie utilise par la sonde.
~Sonde () override
Destructeur. Ferme le fichier avant de detruire l'objet.
const Nom & get_nom () const
const Nom & get_type () const
const int & get_dim () const
void ajouter_bords (const DoubleTab &coords_bords)
void init_bords ()
void mettre_a_jour_bords ()
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Sonde & self_cast (Objet_U &)
static const Sonde & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les specifications d'une sonde a partir d'un flot d'entree.
Format:
Sondes
{
[nom_sonde nom_champ Periode dts Points n x1 y1 [z1] ... xn yn [zn]
[nom_sonde nom_champ Periode dts Segment ns x1 y1 [z1] x2 y2 [z2]
...
}.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Postraitement mon_post
Nom nom_
le nom de la sonde
Nom nom_fichier_
le nom du fichier contenant la sonde
int dim
la dimension de la sone (point:0,segment:1,plan:2,volume:3)
int nbre_points1
int nbre_points2
int nbre_points3
faire des sonde_segment,sonde_plan,etc...
Ref_Champ_Generique_base mon_champ
Ref_Operateur_Statistique_tps_base operateur_statistique_
Reference vers un operateur statistique eventuel.
int ncomp
Numero de la composante a sonder Si ncomp = -1 la sonde s'applique a toutes les composantes du champ.
DoubleTab les_positions_sondes_initiales_
les coordonnees des sondes ponctuelles initiales
DoubleTab les_positions_sondes_
les coordonnees des sondes sur tout le domaine apres deplacement (uniquement sur le maitre)
DoubleTab les_positions_
les coordonnees des sondes locales sur chaque proc
int numero_elem_
vaut -1 si pas defini et vaut le numero de l'elem sur le maitre
IntVect elem_
les elements contenant les sondes ponctuelles locales
double periode
periode d'echantillonnage cles pour typage des sondes (sondes redefinies aux noeuds ou d'apres les valeurs aux sommets ou au centre de gravite ou aux sommets)
bool nodes
bool chsom
bool grav
bool gravcl
bool som
DoubleTab valeurs_locales
DoubleTab valeurs_sur_maitre
valeurs_locales les valeurs sur chaque proc, valeurs_sur_maitre les valeurs regroupes sur le maitre
double nb_bip
SFichier le_fichier_
Motcle nom_champ_lu_
ArrsOfInt participant
vecteur d'ArrOfInt sur le maitre ; participant[pe][i] -> le ieme point sur pe correspond la participant [pe][i] eme position
int reprise
si reprise=0, on cree la sonde, sinon on ecrit a la suite
Nom type_
int orientation_faces_
ArrOfInt faces_bords_
array containing the indices of the boundary faces hit by the probe
IntTab rang_cl_
for a given face, index of the CL that this face bears
Detailed Description
classe Sonde
Cette classe permet d'effectuer l'evolution d'un champ au cours du temps.
On choisit l'ensemble des points sur lesquels on veut sonder un champ et
la periodicite des observations. Les objets Postraitement porte des
des sondes sur les champs a observer, une sonde porte d'ailleurs une
reference sur un postraitement.
Definition at line 41 of file Sonde.h.
Constructor & Destructor Documentation
Sonde() [1/2]
Sonde::Sonde ()
Constructeur d'une sonde sans paramètre.
Definition at line 94 of file Sonde.cpp.
             :
  Sonde(Nom())    //!< thank you C++11
{}
Sonde() [2/2]
Sonde::Sonde (const Nom & nom)
Constructeur d'une sonde a partir de son nom.
Definition at line 76 of file Sonde.cpp.
                            :
  nom_(nom),
  dim(-1),
  ncomp(-1),
  numero_elem_(-1),
  periode(1.e10),   //!< initialisation de periode par defaut
  nodes(false),
  chsom(false),
  grav(false),
  gravcl(false),  //!< Valeurs aux centres de gravite (comme grav) mais avec ajout eventuel des valeurs aux bords via la zone Cl du champ post-traite
  som(false),
  nb_bip(0.),
  reprise(0),
  orientation_faces_(-1)
{}
~Sonde()
Sonde::~Sonde () inline override
Destructeur. Ferme le fichier avant de detruire l'objet.
Definition at line 286 of file Sonde.h.
{
  fermer_fichier();
}
References fermer_fichier().
Member Function Documentation
ajouter_bords()
void Sonde::ajouter_bords (const DoubleTab & coords_bords)
Definition at line 1494 of file Sonde.cpp.
{
  double eps = mon_champ->get_ref_domain().epsilon();
  const Zone_VF& zoneVF = ref_cast(Zone_VF,mon_champ->get_ref_zone_dis_base());
  const DoubleTab& xv = zoneVF.xv();
  const IntTab& e_f = zoneVF.elem_faces(), &f_e = zoneVF.face_voisins();
  int nbre_points = les_positions_sondes_.dimension(0), face;
  faces_bords_.set_smart_resize(1);
  IntTab tmp(2);
  tmp[0] = 0;
  tmp[1] = nbre_points-1;
  for (int i = 0; i<coords_bords.dimension(0); i++)
    {
      int e = tmp[i];
      int elem = elem_[e];
      if (elem !=-1)
        {
          for (int j = 0; j < e_f.dimension(1) && (face = e_f(elem, j)) >= 0; j++)
            {
              if(f_e(face, 1) == -1 || f_e(face, 0) == -1)
                {
                  double dist=0.;
                  for (int idim=0; idim<dimension; idim++)
                    dist+=((xv(face,idim)-coords_bords(i,idim))*(xv(face,idim)-coords_bords(i,idim)));
                  if (sqrt(dist) < eps)
                    {
                      faces_bords_.append_array(face);
                      for (int idim=0; idim<dimension; idim++)
                        les_positions_sondes_(e,idim) = coords_bords(i,idim);
                    }
                }
            }
        }
    }
// [ABN] skiping the assert below. On funny shaped domains (e.g. U-shape) a probe might
// re-enter the domain, and hence hit more than two faces overall:
// assert(mp_sum(faces_bords_.size_array())<=2);
}
References TRUSTArray< _TYPE_ >::append_array(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, elem_, Zone_VF::elem_faces(), Domaine::epsilon(), Zone_VF::face_voisins(), faces_bords_, Champ_Generique_base::get_ref_domain(), Champ_Generique_base::get_ref_zone_dis_base(), les_positions_sondes_, mon_champ, ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), and Zone_VF::xv().
Referenced by initialiser().
associer_post()
void Sonde::associer_post (const Postraitement & le_post)
Associer le postraitement a la sonde.
Definition at line 690 of file Sonde.cpp.
{
  mon_post=le_post;
  if (mon_post->noms_fichiers_sondes().contient(nom_)==0)
    mon_post->noms_fichiers_sondes().add(nom_);
  else
    {
      Cerr << "The filename " << nom_ << " is used several times for probes." << finl;
      Cerr << "A probe must have a unique filename to avoid writing conflicts." << finl;
      exit();
    }
}
References List_Nom::add(), Cerr, List_Nom::contient(), Process::exit(), finl, mon_post, nom_, and Postraitement::noms_fichiers_sondes().
Referenced by Sondes::lire_fichier(), and Sondes::readOn().
completer()
void Sonde::completer (void)
Definition at line 117 of file Sonde.cpp.
{
// Recherche du champ sonde
// Remplissage de la reference au champ
  Cerr << "Reading of the probe: " << nom_ << " on the field: " << nom_champ_lu_ << finl;
// On devrait acceder au domaine par le champ generique
// Mais reference pas encore faite
  Probleme_base& Pb = mon_post->probleme();
  const Motcle& nom_domaine = Pb.domaine().le_nom();
  Motcle nom_champ_ref;
  Motcle nom_macro=nom_champ_lu_;
  Motcle nom_macro_test, nom1("_not_def"), nom2("_not_def");
  const Motcles& noms_champs_postraitables = mon_post->les_sondes().get_noms_champs_postraitables();
  if (!(noms_champs_postraitables.contient_(nom_champ_lu_)||mon_post->comprend_champ_post(nom_champ_lu_)))
    {
      if (nom_champ_lu_.debute_par("MOYENNE_"))
        nom_macro = nom_macro.suffix("MOYENNE_");
      else if (nom_champ_lu_.debute_par("ECART_TYPE_"))
        nom_macro = nom_macro.suffix("ECART_TYPE_");
      if (nom_champ_lu_.debute_par("CORRELATION_"))
        {
          nom_macro_test = nom_champ_lu_;
          nom_macro_test = nom_macro_test.suffix("CORRELATION_");
          for (int i=0; i<noms_champs_postraitables.size(); i++)
            {
              nom_macro_test = nom_macro_test.suffix(noms_champs_postraitables[i]);
              if (nom_macro_test.debute_par("_"))
                {
                  nom1 = noms_champs_postraitables[i];
                  nom2 = nom_macro_test.suffix("_");
                }
            }
        }
    }
  if (noms_champs_postraitables.contient_(nom_macro))
    {
      if (nom_macro==Motcle(nom_champ_lu_))
        {
          REF(Champ_base) champ_ref = Pb.get_champ(nom_champ_lu_);
          const Nom& nom_champ_base = champ_ref->le_nom();
          const Noms& compos_base = champ_ref->noms_compo();
          int ncomposante = Champ_Generique_base::composante(nom_champ_lu_,nom_champ_base,compos_base,champ_ref->get_synonyms());
          if (ncomposante==-1)
            nom_champ_ref = nom_champ_base +"_natif_"+ nom_domaine;
          else
            {
              Nom nume(ncomposante);
              nom_champ_ref = nom_champ_base+"_natif_"+ nom_domaine+nume;
            }
        }
      else
        nom_champ_ref = nom_champ_lu_+"_natif_"+nom_domaine;
    }
  else
    {
// Cas des correlations
      if ((noms_champs_postraitables.contient_(nom1)) && (noms_champs_postraitables.contient_(nom2)))
        {
          nom_champ_ref = "Correlation_";
          nom_champ_ref += nom1+"_natif_"+nom_domaine+"_"+nom2+"_natif_"+nom_domaine;
        }
      else
// Cas d un champ generique general
        nom_champ_ref = nom_champ_lu_;
    }
  mon_champ = mon_post->get_champ_post(nom_champ_ref);
// Remplissage de l'attribut ncomp (il vaut -1 par defaut)
  const Noms nom_champ = mon_champ->get_property("nom");
  const Noms noms_comp = mon_champ->get_property("composantes");
  ncomp = Champ_Generique_base::composante(nom_champ_ref,nom_champ[0],noms_comp,mon_champ->get_property("synonyms"));
  initialiser();
}
References Cerr, Champ_Generique_base::composante(), Postraitement::comprend_champ_post(), Motcles::contient_(), Motcle::debute_par(), Probleme_base::domaine(), finl, Probleme_base::get_champ(), Postraitement::get_champ_post(), Sondes::get_noms_champs_postraitables(), Champ_Generique_base::get_property(), initialiser(), Domaine::le_nom(), Nom::le_nom(), Postraitement::les_sondes(), mon_champ, mon_post, ncomp, nom_, nom_champ_lu_, Postraitement::probleme(), REF, vect_impl::size(), and Nom::suffix().
cree_instance()
Objet_U * Sonde::cree_instance () static
Definition at line 29 of file Sonde.cpp.
duplique()
int Sonde::duplique () const override virtual
Implements Objet_U.
Definition at line 29 of file Sonde.cpp.
fermer_fichier()
void Sonde::fermer_fichier () inline
Ferme le fichier sur laquelle la sonde ecrit.
Definition at line 153 of file Sonde.h.
{
  if (fichier().is_open())
    {
      le_fichier_.close();
    }
}
References Sortie_Fichier_base::close(), fichier(), and le_fichier_.
Referenced by ~Sonde().
fichier()
SFichier & Sonde::fichier () inline
Renvoie un flot de sortie Fichier, pointant sur
le fichier de sortie utilise par la sonde.
Returns
SFichier&
Signification: le fichier de sortie utilise par la sonde
Contraintes:
Definition at line 267 of file Sonde.h.
{
  return le_fichier_;
}
References le_fichier_.
Referenced by fermer_fichier(), ouvrir_fichier(), and postraiter().
fixer_periode()
void Sonde::fixer_periode (double pe) inline
Fixe la periode avec laquelle on sonde le champ.
Definition at line 176 of file Sonde.h.
{
  periode=pe;
}
References periode.
get_dim()
const int & Sonde::get_dim () const inline
Definition at line 73 of file Sonde.h.
  {
    return dim ;
  } ;
References dim.
Referenced by readOn().
get_info()
const Type_info * Sonde::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 29 of file Sonde.cpp.
get_nom()
const Nom & Sonde::get_nom () const inline
Definition at line 65 of file Sonde.h.
  {
    return nom_;
  };
References nom_.
Referenced by readOn().
get_type()
const Nom & Sonde::get_type () const inline
Definition at line 69 of file Sonde.h.
  {
    return type_;
  };
References type_.
Referenced by ouvrir_fichier(), and readOn().
info()
const Type_info * Sonde::info () static
Definition at line 29 of file Sonde.cpp.
init_bords()
void Sonde::init_bords ()
Definition at line 1457 of file Sonde.cpp.
{
  if (!gravcl)
    return;
  const int nbf = faces_bords_.size_array();
  rang_cl_.resize(nbf);
  if (sub_type(Champ_Generique_refChamp,mon_champ.valeur()))
    {
      Probleme_base& Pb = mon_post->probleme();
      REF(Champ_base) chref = Pb.get_champ(nom_champ_lu_);
      const Champ_Inc_base& ch_inc = ref_cast(Champ_Inc_base,chref.valeur());
      const Zone_Cl_dis& zcl = ch_inc.zone_Cl_dis();
      if (zcl.non_nul())
        {
          for (int iface=0; iface<nbf; iface++)
            {
              int face = faces_bords_[iface];
              for (int icl=0; icl<zcl.nb_cond_lim(); icl++)
                {
                  const Cond_lim& cl = zcl.les_conditions_limites(icl);
                  const Front_VF& le_bord = ref_cast(Front_VF,cl.frontiere_dis());
                  const int ndeb = le_bord.num_premiere_face();
                  const int nfin = ndeb + le_bord.nb_faces();
                  for (int i=ndeb; i<nfin; i++)
                    {
                      if (i==face)
                        rang_cl_[iface] = icl;
                    }
                }
            }
        }
    }
}
References faces_bords_, Cond_lim::frontiere_dis(), Probleme_base::get_champ(), gravcl, Zone_Cl_dis::les_conditions_limites(), mon_champ, mon_post, Zone_Cl_dis::nb_cond_lim(), Front_VF::nb_faces(), nom_champ_lu_, O_U_Ptr::non_nul(), Front_VF::num_premiere_face(), Postraitement::probleme(), rang_cl_, REF, ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::size_array(), sub_type, Ref_Champ_Generique_base::valeur(), and Champ_Inc_base::zone_Cl_dis().
initialiser()
void Sonde::initialiser ()
Initialise la sonde. Dimensionne les tableaux,
de valeurs, verifie si les points specifies sont
bien dans la zone de calcul.
< Nouveaute 1.8.4 (unicite des points de sondes)
< Par defaut c'est le maitre le proprio (en particulier pour les sondes en dehors)
< Tableau uniquement sur le maitre:
Definition at line 720 of file Sonde.cpp.
{
// Calcul des positions exactes a partir des positions initiales des sondes:
  les_positions_sondes_ = les_positions_sondes_initiales_;
// Dimension the elem_ array:
  int nbre_points_tot = les_positions_sondes_.dimension(0);
  if(elem_.size() != nbre_points_tot)
    elem_.resize(nbre_points_tot);
  const Zone& zone_geom = mon_champ->get_ref_domain().zone(0);
  if (numero_elem_==-1)
    {
// Location of probes is given by coordinates in the les_positions_ array:
      int nb_coord = les_positions_sondes_.dimension(1);
      if (nb_coord != Objet_U::dimension)
        {
          Cerr << "You can't specify the probe named " << nom_ << " with "<< nb_coord << " coordinates on the domain named " <<zone_geom.domaine().le_nom()<<finl;
          Cerr << "which has spatial dimension " << Objet_U::dimension << finl;
          Cerr << "Change the probe coordinates or use numero_elem_sur_maitre keyword (see documentation)" << finl;
          Cerr << "to specify a cell containing the probe and not its coordinates." << finl;
// [ABN] : we should exit, otherwise we just don't see the warning:
          Process::exit();
        }
// Fill the elem_ array (which list real cells containing all the probes):
      zone_geom.chercher_elements(les_positions_sondes_,elem_,1);
    }
  else
    {
// Location of the probe is given by an element number:
      elem_[0]= numero_elem_;
      const IntTab& les_elems=mon_champ->get_ref_zone_dis_base().zone().les_elems();
      if (numero_elem_<les_elems.dimension_tot(0))
        {
          const DoubleTab& coord=mon_champ->get_ref_zone_dis_base().zone().domaine().les_sommets();
          int nb_som=les_elems.dimension(1);
// Fill les_positions_ with the cog of the cell numero_elem_
          for (int s=0; s<nb_som; s++)
            {
              int soml=les_elems(numero_elem_,s);
              if (soml>-1)
                for (int dir=0; dir<dimension; dir++)
                  les_positions_sondes_(0,dir)+=coord(soml,dir)/nb_som;
            }
        }
      else
        {
          if (je_suis_maitre())
            {
              Cerr<<" On the probe named " << nom_ << " , the element number "<<numero_elem_<<" does not exist on the master processor, we put the position to zero"<<finl;
              les_positions_sondes_=0;
            }
          elem_[0]=-1;
        }
    }
// Check if some probes are outside the domain:
  ArrOfDouble tmp(nbre_points_tot);
  for (int i=0; i<nbre_points_tot; i++)
    tmp[i] = elem_[i];
  mp_max_for_each_item(tmp);
  for (int i=0; i<nbre_points_tot; i++)
    if (tmp[i]==-1)
      Cerr << "WARNING: The point number " << i+1 << " of the probe named " << nom_ << " is outside the computational domain " << zone_geom.domaine().le_nom() << finl;
// Probes may be moved to cog, face, vertex:
  const Zone& zone = mon_champ->get_ref_domain().zone(0);
  const Noms nom_champ = mon_champ->get_property("nom");
  if (grav || gravcl)
    {
      DoubleTab coords_bords(2,dimension);
      for (int idim=0; idim<dimension; idim++)
        {
          coords_bords(0,idim) = les_positions_sondes_(0,idim);
          coords_bords(1,idim) = les_positions_sondes_(nbre_points_tot-1,idim);
        }
      Cerr<<"The location of the probe named "<<nom_<<" are modified (to centers of gravity). Check the .log files to see the new location."<<finl;
      const Zone_VF& zoneVF = ref_cast(Zone_VF,mon_champ->get_ref_zone_dis_base());
      const DoubleTab& xp = zoneVF.xp();
      for (int i=0; i<nbre_points_tot; i++)
        {
          if(elem_[i]!=-1)
            {
              Journal()<<"The point " << i << " of the probe "<<nom_<<" is moved:";
              for (int dir=0; dir<dimension; dir++)
                {
                  Journal() << " x(" << dir << "): " << les_positions_sondes_(i,dir) << " -> " << xp(elem_[i],dir);
                  les_positions_sondes_(i,dir)=xp(elem_[i],dir);
                }
              Journal() << finl;
            }
        }
      if (gravcl)
        ajouter_bords(coords_bords);
    }
  else if (nodes)
    {
      const Zone_VF& zoneVF = ref_cast(Zone_VF,mon_champ->get_ref_zone_dis_base());
      const DoubleTab& xv = zoneVF.xv();
      const IntTab& elem_faces = zoneVF.elem_faces();
      if (mp_max(elem_faces.size_array())==0)
        {
          Cerr << "Error: the domain " << zoneVF.zone().domaine().le_nom() << " is not discretized." << finl;
          exit();
        }
      if (sub_type(Champ_Generique_Interpolation,mon_champ.valeur()))
        {
          Motcle dom_interp=mon_champ->get_ref_domain().le_nom();
          Cerr << finl;
          Cerr << "Error in your probe : " << nom_ << finl;
          Cerr << "You can not project to nodes, the field " << nom_champ[0] << finl;
          Cerr << "which is interpolated on the domain " << dom_interp << finl;
          exit();
        }
      Cerr<<"The location of the probe named "<<nom_<<" are modified (to faces). Check the .log files to see the new location."<<finl;
      const int nfaces_par_element = zone.nb_faces_elem() ;
      for (int i=0; i<nbre_points_tot; i++)
        {
          double dist_min=DMAXFLOAT;
          int face_min=-1;
          if(elem_[i]!=-1)
            {
              Journal()<<"The point " << i << " of the probe "<<nom_<<" is moved:";
              for(int fac=0; fac<nfaces_par_element; fac++)
                {
                  int face=elem_faces(elem_[i],fac);
// Sonde de type segmentfaces : on recherche seulement parmi les faces orientees selon
// orientation_faces_
                  if (face >= 0 &&
                      (orientation_faces_ == -1 || zoneVF.orientation_si_definie(face)==orientation_faces_))
                    {
                      double dist=0.;
                      for (int dir=0; dir<dimension; dir++)
                        dist+=(xv(face,dir)-les_positions_sondes_(i,dir))*(xv(face,dir)-les_positions_sondes_(i,dir));
                      if(dist<=dist_min)
{
                          dist_min=dist;
                          face_min=face;
                        }
                    }
                }
              for (int dir=0; dir<dimension; dir++)
                {
                  Journal() << " x(" << dir << "): " << les_positions_sondes_(i,dir) << " -> " << xv(face_min,dir);
                  les_positions_sondes_(i,dir)=xv(face_min,dir);
                }
              Journal() << " (" << (face_min < zoneVF.premiere_face_int() ? "boundary face " : "internal face ") << face_min<<")" << finl;
            }
        }
    }
  else if (som)
    {
      if (sub_type(Champ_Generique_Interpolation,mon_champ.valeur()))
        {
          Motcle dom_interp=mon_champ->get_ref_domain().le_nom();
          Cerr << finl;
          Cerr << "Error in your probe : " << nom_ << finl;
          Cerr << "You can not project to vertexes, the field " << nom_champ[0] << finl;
          Cerr << "which is interpolated on the domain " << dom_interp << finl;
          exit();
        }
      Cerr<<"The location of the probe named "<<nom_<<" are modified (to vertexes). Check the .log files to see the new location."<<finl;
      const IntTab& sommet_elem = zone.les_elems();
      const int sommets_par_element = zone.les_elems().dimension(1);
      const DoubleTab& coord = zone.domaine().les_sommets();
      for (int i=0; i<nbre_points_tot; i++)
        {
          double dist_min=DMAXFLOAT;
          int sommet_min=-1;
          if(elem_[i]!=-1)
            {
              Journal()<<"The point " << i << " of the probe "<<nom_<<" is moved:";
              for(int isom=0, sommet; isom<sommets_par_element && (sommet = sommet_elem(elem_[i],isom)) >= 0; isom++)
                {
                  double dist=0.;
                  for (int dir=0; dir<dimension; dir++)
                    dist+=(coord(sommet,dir)-les_positions_sondes_(i,dir))*(coord(sommet,dir)-les_positions_sondes_(i,dir));
                  if(dist<=dist_min)
                    {
                      dist_min=dist;
                      sommet_min=sommet;
                    }
                }
              for (int dir=0; dir<dimension; dir++)
                {
                  Journal() << " x(" << dir << "): " << les_positions_sondes_(i,dir) << " -> " << coord(sommet_min,dir);
                  les_positions_sondes_(i,dir)=coord(sommet_min,dir);
                }
              Journal() << finl;
            }
        }
    }
  bool supprime_doublons = true; //!< Nouveaute 1.8.4 (unicite des points de sondes)
  if (mon_post->DeprecatedKeepDuplicatedProbes) supprime_doublons = false;
  ArrOfInt doublon(elem_.size_array());
  if (supprime_doublons)
    {
      int doublons=0;
      int size = elem_.size();
      for (int i=0; i<size; i++)
        {
          for (int j=i+1; j<size; j++)
            {
              bool same = true;
              if (elem_[i]!=elem_[j])
                same = false;
              else
                for (int dir = 0; dir < dimension; dir++)
                  if (les_positions_sondes_(i, dir) != les_positions_sondes_(j, dir))
                    {
                      same = false;
                      break;
                    }
              if (same)
                {
                  doublon[i] = 1;
                  doublons++;
                  break;
                }
            }
        }
      if (doublons)
        Cerr << "We remove " << doublons << " duplicated points from the probe " << nom_ << finl;
    }
// chaque processeur a regarde s'il avait le point
// le maitre construit un tableau (prop) determinant qui
// va donner la valeur au maitre
// Le maitre construit aussi le ArrsOfInt participant
// lui donnant pour un proc les differents elements de celui-ci
  IntVect prop(elem_);
  if (je_suis_maitre())
    {
      ArrOfInt elems2(elem_);
      prop=0; //!< Par defaut c'est le maitre le proprio (en particulier pour les sondes en dehors)
      ArrOfInt elem_recu, doublon_recu;
      DoubleTab positions_recu;
      int nbproc=Process::nproc();
      for(int p=1; p<nbproc; p++)
        {
          recevoir(doublon_recu,p,2003+p);
          recevoir(elem_recu,p,0,2002+p);
          recevoir(positions_recu,p,0,2001+p);
          for (int el=0; el<nbre_points_tot; el++)
            if (elems2[el]==-1 && elem_recu[el]!=-1)
              {
                elems2[el]=elem_recu[el];
                doublon[el]=doublon_recu[el];
                prop[el]=p;
                for (int j=0; j<dimension; j++)
                  les_positions_sondes_(el,j)=positions_recu(el,j);
              }
        }
// OK On a rempli le tableau prop;
// le maitre dimensionne participant;
      participant.dimensionner(nbproc);
      for(int p=0; p<nbproc; p++)
        {
          int size=0;
          for (int el=0; el<nbre_points_tot; el++)
            if (prop[el]==p&&!doublon[el]) size++;
          participant[p].resize_array(size);
          participant[p]=-1;
          int pos=0;
          int pt=0;
          for (int el=0; el<nbre_points_tot; el++)
            if (!doublon[el])
              {
                if (prop[el] == p)
                  {
                    participant[p][pos] = pt;
                    pos++;
                  }
                pt++;
              }
          assert((size==0)||(min_array(participant[p])>-1));
        }
    }
  else
    {
      envoyer(doublon, Process::me(),0,2003+Process::me());
      envoyer(elem_,Process::me(),0,2002+Process::me());
      envoyer(les_positions_sondes_,Process::me(),0,2001+Process::me());
    }
  envoyer_broadcast(prop, 0);
//
// on redimensionne les tableaux a la taille locale a partir de prop et en supprimant les doublons
  int nbre_points=0;
  nbre_points_tot=0;
  les_positions_=les_positions_sondes_;
  for (int el=0; el<prop.size(); el++)
    {
      if (!doublon[el])
        {
          if (prop(el) == me())
            {
              elem_(nbre_points) = elem_(el);
              for (int dir = 0; dir < dimension; dir++)
                les_positions_(nbre_points, dir) = les_positions_(el, dir);
              nbre_points++;
            }
          for (int dir = 0; dir < dimension; dir++)
            les_positions_sondes_(nbre_points_tot, dir) = les_positions_sondes_(el, dir);
          nbre_points_tot++;
        }
    }
#ifndef NDEBUG
  int test=mp_sum(nbre_points);
// cerr << "Remove " << Process::me() << " " << nbre_points << " " << nbre_points_tot << " = " << test << endl;
  if (je_suis_maitre()) assert(test==nbre_points_tot);
#endif
  elem_.resize(nbre_points);
  les_positions_.resize(nbre_points, dimension);
  if (je_suis_maitre()) //!< Tableau uniquement sur le maitre:
    les_positions_sondes_.resize(nbre_points_tot, dimension);
  else
    les_positions_sondes_.resize(0,0);
// Dimensionnement de valeurs_sur_maitre
  if (je_suis_maitre()&&(nproc()>1))
    {
      if (ncomp == -1)
        {
          const Noms noms_comp = mon_champ->get_property("composantes");
          int nb_comp = noms_comp.size();
          valeurs_sur_maitre.resize(nbre_points_tot,nb_comp);
        }
      else
        valeurs_sur_maitre.resize(nbre_points_tot, 1);
    }
// Dimensionnement de valeurs_locales
  if (ncomp == -1)
    {
      const Noms noms_comp = mon_champ->get_property("composantes");
      int nb_comp = noms_comp.size();
      valeurs_locales.resize(nbre_points,nb_comp);
    }
  else
    valeurs_locales.resize(nbre_points, 1);
}
References ajouter_bords(), Cerr, Zone::chercher_elements(), Postraitement::DeprecatedKeepDuplicatedProbes, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), vect_impl::dimensionner(), DMAXFLOAT, Zone::domaine(), elem_, Zone_VF::elem_faces(), envoyer(), envoyer_broadcast(), Process::exit(), finl, Champ_Generique_base::get_property(), Champ_Generique_base::get_ref_domain(), Champ_Generique_base::get_ref_zone_dis_base(), grav, gravcl, Process::je_suis_maitre(), Process::Journal(), Domaine::le_nom(), Zone::les_elems(), les_positions_, les_positions_sondes_, les_positions_sondes_initiales_, Domaine::les_sommets(), Process::me(), min_array(), mon_champ, mon_post, Process::mp_max(), mp_max_for_each_item(), Process::mp_sum(), Zone::nb_faces_elem(), ncomp, nodes, nom_, Process::nproc(), numero_elem_, orientation_faces_, Zone_VF::orientation_si_definie(), participant, Zone_VF::premiere_face_int(), recevoir(), ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), same(), TRUSTVect< _TYPE_ >::size(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), som, sub_type, test(), Ref_Champ_Generique_base::valeur(), valeurs_locales, valeurs_sur_maitre, Zone_VF::xp(), Zone_VF::xv(), Zone_dis_base::zone(), and Domaine::zone().
Referenced by completer(), and mettre_a_jour().
le_champ()
const Champ_Generique_base & Sonde::le_champ (void) const inline
Renvoie le champ associe.
Returns
Champ_base&
Signification: le champ associe
Contraintes: reference constante
Definition at line 196 of file Sonde.h.
{
  return mon_champ.valeur();
}
References mon_champ, and Ref_Champ_Generique_base::valeur().
les_poly()
const IntVect & Sonde::les_poly () const inline
Renvoie le tableau des elements qui sont sondes.
Returns
IntVect&
Signification: les ments qui sont sondes
Contraintes: reference constante
Definition at line 246 of file Sonde.h.
{
  return elem_;
}
References elem_.
les_positions()
const DoubleTab & Sonde::les_positions () const inline
Positions locales au proc.
Definition at line 227 of file Sonde.h.
{
  return les_positions_;
}
References les_positions_.
Referenced by postraiter().
les_positions_sondes()
const DoubleTab & Sonde::les_positions_sondes () const inline
Positions apres deplacement.
Definition at line 222 of file Sonde.h.
{
  return les_positions_sondes_;
}
References les_positions_sondes_.
Referenced by ouvrir_fichier().
les_positions_sondes_initiales()
const DoubleTab & Sonde::les_positions_sondes_initiales () const inline
Positions initiales.
Renvoie le tableau des positions du champ qui sont sondees.
Returns
DoubleTab&
Signification: les positions sondees
Contraintes: reference constante
Definition at line 217 of file Sonde.h.
{
  return les_positions_sondes_initiales_;
}
References les_positions_sondes_initiales_.
Referenced by readOn().
mettre_a_jour()
void Sonde::mettre_a_jour (double temps, double tinit)
Effectue une mise a jour en temps de la sonde
effectue le postraitement.
Definition at line 1268 of file Sonde.cpp.
{
// La mise a jour du champ est a supprimer car elle doit deja etre faite dans Post::mettre_a_jour()
  double temps_courant = mon_champ->get_time();
  double dt=mon_post->probleme().schema_temps().pas_de_temps();
  double nb;
// Le *(1+Objet_U::precision_geom) est pour eviter des erreurs d'arrondi selon les machines
  if (periode<=dt)
    nb=nb_bip+1.;
  else
    modf(temps_courant*(1+Objet_U::precision_geom)/periode, &nb);
// On doit ecrire les sondes
  if (nb>nb_bip)
    {
// Mecanisme de cache du champ Source derriere le champ postraite (mon_champ)
// Implemente au niveau de Sondes
      REF(Champ_base) ma_source = mon_post->les_sondes().get_from_cache(mon_champ, nom_champ_lu_);
// Champ espace_stockage;
// Champ_base& ma_source_mod = ref_cast_non_const(Champ_base,mon_champ->get_champ(espace_stockage));
// ma_source_mod.mettre_a_jour(un_temps);
      ma_source.valeur().mettre_a_jour(un_temps);
// Si le maillage est deformable il faut reconstruire les sondes
      if (mon_post->probleme().domaine().deformable())
        {
// Fait desormais dans ::initialiser:
// if (les_positions_sondes_initiales_.dimension(0) > 0)
// les_positions_sondes_ = les_positions_sondes_initiales_;
          initialiser();
        }
      nb_bip=nb;
      reprise=1;
      postraiter();
    }
}
References Domaine::deformable(), Probleme_base::domaine(), Sondes::get_from_cache(), Champ_Generique_base::get_time(), initialiser(), Postraitement::les_sondes(), Champ_base::mettre_a_jour(), mon_champ, mon_post, nb_bip, nom_champ_lu_, Schema_Temps_base::pas_de_temps(), periode, postraiter(), Objet_U::precision_geom, Postraitement::probleme(), REF, reprise, Probleme_base::schema_temps(), and Ref_Champ_base::valeur().
mettre_a_jour_bords()
void Sonde::mettre_a_jour_bords ()
Definition at line 1538 of file Sonde.cpp.
{
  if (sub_type(Champ_Generique_refChamp,mon_champ.valeur()))
    {
      Probleme_base& Pb = mon_post->probleme();
      REF(Champ_base) chref = Pb.get_champ(nom_champ_lu_);
      const Champ_Inc_base& ch_inc = ref_cast(Champ_Inc_base,chref.valeur());
      const Zone_Cl_dis& zcl = ch_inc.zone_Cl_dis();
      const DoubleTab& vals_ch = ch_inc.valeurs();
      if (zcl.non_nul())
        {
          const Zone_VF& zoneVF = ref_cast(Zone_VF,mon_champ->get_ref_zone_dis_base());
          const IntTab& face_voisins = zoneVF.face_voisins();
          int nbval = valeurs_locales.dimension(0);
          for (int iface=0; iface<faces_bords_.size_array(); iface++)
            {
              int face = faces_bords_[iface];
              int icl = rang_cl_[iface];
              const Cond_lim& cl = zcl.les_conditions_limites(icl);
              const Front_VF& le_bord = ref_cast(Front_VF,cl.frontiere_dis());
              const int ndeb = le_bord.num_premiere_face();
              DoubleVect valcl;
              cl->champ_front()->valeurs_face(face-ndeb,valcl);
              if (valcl.size() == 0)
                {
                  int elem0 = face_voisins(face,0);
                  int elem1 = face_voisins(face,1);
                  if (elem0 != -1)
                    valeurs_locales(nbval-1) = vals_ch[elem0];
                  else
                    valeurs_locales(0) = vals_ch[elem1];
                }
              else
                {
                  if (face_voisins(face,0) != -1)
                    valeurs_locales(nbval-1) = valcl[0];
                  else
                    valeurs_locales(0) = valcl[0];
                }
            }
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::face_voisins(), faces_bords_, Cond_lim::frontiere_dis(), Probleme_base::get_champ(), Champ_Generique_base::get_ref_zone_dis_base(), Zone_Cl_dis::les_conditions_limites(), mon_champ, mon_post, nom_champ_lu_, O_U_Ptr::non_nul(), Front_VF::num_premiere_face(), Postraitement::probleme(), rang_cl_, REF, ref_cast, TRUSTVect< _TYPE_ >::size(), TRUSTArray< _TYPE_ >::size_array(), sub_type, Ref_Champ_Generique_base::valeur(), Champ_Inc_base::valeurs(), valeurs_locales, and Champ_Inc_base::zone_Cl_dis().
Referenced by postraiter().
ouvrir_fichier()
void Sonde::ouvrir_fichier ()
Ouvre le fichier associe a la sonde. (*.son)
Definition at line 1082 of file Sonde.cpp.
{
  if(je_suis_maitre())
    {
      if (!le_fichier_.is_open())
        {
// struct stat f {}; Pb sur 4.8.5
          struct stat f;
          const char *sonde_file = nom_fichier_;
          if (stat(sonde_file, &f))
            reprise = 0;
          else if (reprise == 0)
            reprise = mon_post->probleme().reprise_effectuee();
          if (reprise == 0)
            le_fichier_.ouvrir(nom_fichier_);
          else
            le_fichier_.ouvrir(nom_fichier_, ios::app);
          le_fichier_.setf(ios::scientific);
          le_fichier_.precision(8);
        }
      SFichier& s = le_fichier_;
// Ecriture de l'en tete des fichiers sondes :
      if ((dim==0 || dim==1) && reprise==0)
        {
          reprise=1;
          const DoubleTab& p=les_positions_sondes();
          int nbre_points = les_positions_sondes_.dimension(0);
          s << "# " << nom_fichier_ << finl;
          s << "# Temps";
          for(int i=0; i<nbre_points; i++)
            {
              s << " x= " << p(i,0) << " y= " << p(i,1) ;
              if (dimension==3) fichier() << " z= " << p(i,2) ;
            }
          s << finl;
// La 1.5.6 ajoute des informations supplementaires
          s << "# Champ " << nom_champ_lu_ << finl;
          s << "# Type " << get_type() << finl;
        }
// Ecriture de l'en tete des fichiers plan :
      if (dim>1 && reprise==0)
        {
          reprise=1;
          s << "TRUST   Version1  01/09/96" << finl;
          s << nom_du_cas() << finl;
          s << "TRUST" << finl;
          s << "GRILLE";
          const DoubleTab& p = les_positions_sondes();
// Nouveau on ajoute des informations pour Run_sonde
          s << " " << get_type() << " " << nom_champ_lu_ << " " << nbre_points1 << " " << nbre_points2;
          for (int j=0; j<dimension; j++) s << " " << p(0,j);
          for (int j=0; j<dimension; j++) s << " " << p((nbre_points1-1)*nbre_points2,j);
          for (int j=0; j<dimension; j++) s << " " << p(nbre_points2-1,j);
          s << finl;
          Nom nom_grille("Grille");
          Nom nom_topologie("Topologie");
          nom_grille += "_";
          nom_grille += nom_;
          nom_topologie += "_";
          nom_topologie += nom_;
          int k,kn;
          int nbre_points = les_positions_sondes_.dimension(0);
          if (dim==2)
            {
              double xn=0.,yn=0.,zn=0.,norme=0.;
              int p1=1 ,p_nbre_points2=nbre_points2;
              while (p(0,0)==p(p1,0) && p(0,1)==p(p1,1) && p(0,2)==p(p1,2))
                {
                  p1+=1;
                  assert(p1<nbre_points);
                }
              while (p(0,0)==p(p_nbre_points2,0) && p(0,1)==p(p_nbre_points2,1) && p(0,2)==p(p_nbre_points2,2))
                {
                  p_nbre_points2+=1;
                  assert(p_nbre_points2<nbre_points);
                }
              while (p(p1,0)==p(p_nbre_points2,0) && p(p1,1)==p(p_nbre_points2,1) && p(p1,2)==p(p_nbre_points2,2))
                {
                  p_nbre_points2+=1;
                  assert(p_nbre_points2<nbre_points);
                }
              if (dimension==3)
                {
                  xn=(p(p1,2)-p(0,2))*(p(p_nbre_points2,1)-p(0,1))
                     -(p(p1,1)-p(0,1))*(p(p_nbre_points2,2)-p(0,2));
                  yn=(p(p1,0)-p(0,0))*(p(p_nbre_points2,2)-p(0,2))
                     -(p(p1,2)-p(0,2))*(p(p_nbre_points2,0)-p(0,0));
                }
              else if (dimension==2)
                {
                  xn=0.;
                  yn=0.;
                }
              zn=(p(p1,1)-p(0,1))*(p(p_nbre_points2,0)-p(0,0))
                 -(p(p1,0)-p(0,0))*(p(p_nbre_points2,1)-p(0,1));
              norme=std::fabs(xn)+std::fabs(yn)+std::fabs(zn);
              xn/=norme;
              yn/=norme;
              zn/=norme;
              s << nom_grille << " 3 " << 2*nbre_points << finl;
              int i;
              for(i=0; i<nbre_points; i++)
                {
                  s << p(i,0) << " " << p(i,1) ;
                  if (dimension==3) fichier() << " " << p(i,2) << finl;
                  else if (dimension==2) s << " 0." << finl;
                }
              for(i=0; i<nbre_points; i++)
                {
                  s << p(i,0)+xn << " " << p(i,1)+yn ;
                  if (dimension==3) s << " " << p(i,2)+zn << finl;
                  else if (dimension==2) s << " " << zn << finl;
                }
              s << "TOPOLOGIE" << finl;
              s << nom_topologie << " " << nom_grille << finl;
              s << "MAILLE" << finl;
              s << (nbre_points1-1)*(nbre_points2-1) << finl;
              for(int j=0; j<nbre_points2-1; j++)
                for(i=0; i<nbre_points1-1; i++)
                  {
                    k=j*nbre_points1+i+1;
                    kn=k+nbre_points;
                    s << "VOXEL8 " << k << " " << k+1 << " ";
                    s<< k+nbre_points1 << " " << k+nbre_points1+1;
                    s<< " " << kn << " " << kn+1 << " " << kn+nbre_points1;
                    s  << " " << kn+nbre_points1+1 << finl;
                  }
              s << "FACE" << finl;
              s << "0" << finl;
            }
          else if (dim==3)
            {
              const DoubleTab& pbis=les_positions_sondes();
              s << nom_grille << " 3 " << nbre_points << finl;
              int i;
              for(i=0; i<nbre_points; i++)
                {
                  s << pbis(i,0) << " " << pbis(i,1) ;
                  s << " " << pbis(i,2) << finl;
                }
              s << "TOPOLOGIE" << finl;
              s << nom_topologie << " " << nom_grille << finl;
              s << "MAILLE" << finl;
              s << (nbre_points1-1)*(nbre_points2-1)*(nbre_points3-1) << finl;
              for(int m=0; m<nbre_points3-1; m++)
                for(int j=0; j<nbre_points2-1; j++)
                  for(i=0; i<nbre_points1-1; i++)
                    {
                      k=m*nbre_points2*nbre_points1+j*nbre_points1+i+1;
                      kn=k+nbre_points2*nbre_points1;
                      s << "VOXEL8 " << k << " " << k+1 << " ";
                      s  << k+nbre_points1 << " " << k+nbre_points1+1;
                      s  << " " << kn << " " << kn+1 << " " << kn+nbre_points1;
                      s  << " " << kn+nbre_points1+1 << finl;
                    }
              s << "FACE" << finl;
              s << "0" << finl;
            }
        }
    }
}
References dim, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, fichier(), finl, get_type(), Sortie_Fichier_base::is_open(), Process::je_suis_maitre(), le_fichier_, les_positions_sondes(), les_positions_sondes_, mon_post, nbre_points1, nbre_points2, nbre_points3, nom_, nom_champ_lu_, Objet_U::nom_du_cas(), nom_fichier_, norme(), Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), Postraitement::probleme(), reprise, Probleme_base::reprise_effectuee(), and Sortie_Fichier_base::setf().
Referenced by postraiter().
postraiter()
void Sonde::postraiter ()
Effectue un postraitement.
Calcul les valeurs du champ aux position demandees
et les imprime sur le fichier associe.
Definition at line 1322 of file Sonde.cpp.
{
// Mecanisme de cache du champ Source derriere le champ postraite (mon_champ)
// Implemente au niveau de Sondes
  REF(Champ_base) ma_source = mon_post->les_sondes().get_from_cache(mon_champ, nom_champ_lu_);
  if (chsom)
    {
      Champ_base& ma_source_mod =ref_cast_non_const(Champ_base,ma_source.valeur());
      if (ncomp == -1)
        ma_source_mod.valeur_aux_elems_smooth(les_positions(),elem_, valeurs_locales);
      else
        ma_source_mod.valeur_aux_elems_compo_smooth(les_positions(),elem_,valeurs_locales, ncomp);
    }
  else
    {
      if (ncomp == -1)
        ma_source.valeur().valeur_aux_elems(les_positions(),elem_, valeurs_locales);
      else
        ma_source.valeur().valeur_aux_elems_compo(les_positions(),elem_,valeurs_locales, ncomp);
    }
  if (gravcl)
    mettre_a_jour_bords();
  const int N = valeurs_locales.line_size();
// le maitre reconstruit le tableau valeurs a partir des differents contributeurs
  if(je_suis_maitre())
    {
      ouvrir_fichier();
      int nbproc = Process::nproc();
      DoubleTab valeurs_pe;
      DoubleTab& valeurs=(nbproc==1?valeurs_locales:valeurs_sur_maitre);
      if (nbproc==1)
        ;//valeurs=valeurs_locales;
      else
        {
          int nb_val = valeurs_locales.dimension(0);
          for (int i = 0; i < nb_val; i++)
            for (int n = 0; n < N; n++)
              valeurs(participant[0][i], n) = valeurs_locales(i, n);
        }
      for(int p=1; p<nbproc; p++)
        {
// le message n'est envoye que si le proc participe
          if (participant[p].size_array()!=0)
            {
              recevoir(valeurs_pe,p,0,2002+p);
              int nb_val1=valeurs_pe.dimension(0);
              assert(N == valeurs_pe.line_size());
              for(int i=0; i<nb_val1; i++)
                for(int n = 0; n < N; n++)
                  {
                    valeurs(participant[p][i], n)=valeurs_pe(i, n);
// val_max = std::max(std::fabs(valeurs(i,k)),std::fabs(valeurs_pe(i,k)));
// if(val_max==(std::fabs(valeurs_pe(i,k))))
// valeurs(i,k)=valeurs_pe(i,k);
                  }
            }
        }
      double temps_courant = mon_post->probleme().schema_temps().temps_courant();
      if (dim==0 || dim==1)
        {
          fichier() << temps_courant;
          for(int i=0; i<valeurs.dimension(0); i++)
            for(int k=0; k<N; k++)
              fichier() << " " << valeurs(i,k);
          fichier() << finl;
        }
// Pour les sondes type plan, impression au format lml :
// num_sommet comp1 [comp2] [comp3]
// et dans la troisieme direction :
      else if (dim==2 || dim==3)
        {
          Nom nom_post;
          int nbre_points = valeurs.dimension(0);
          const Noms noms_comp = mon_champ->get_property("composantes");
          int nb_comp = noms_comp.size();
          const Noms unites = mon_champ->get_property("unites");
          if (ncomp==-1)
            {
              const Noms noms_champ = mon_champ->get_property("nom");
              nom_post = noms_champ[0];
            }
          else
            nom_post = noms_comp[ncomp];
          Nom nom_topologie("Topologie");
          nom_topologie += "_";
          nom_topologie += nom_;
          fichier() << "TEMPS " << temps_courant << "\n";
          fichier() << "CHAMPPOINT " << nom_post << " " << nom_topologie
                    << " " << temps_courant << "\n";
          fichier() << nom_post << " " << nb_comp << " " << unites[0] << "\n";
          int nbp=nbre_points;
          if (dim==2) nbp*=2;
          if (nb_comp>1)
            fichier() << "type1 " << nbp << "\n";
          else fichier() << "type0 " << nbp << "\n";
          int i;
          for(i=0; i<nbre_points; i++)
            {
              fichier() << i+1;
              for(int j=0; j<N; j++)
                fichier() << " " << valeurs(i,j);
// Pour ne pas flusher :
              fichier() << "\n";
            }
// Pour le 2D, on rajoute une direction
          if (dim==2)
            {
              for(i=0; i<nbre_points; i++)
                {
                  fichier() << nbre_points+i+1;
                  for(int j=0; j<N; j++)
                    fichier() << " " << valeurs(i,j);
// Pour ne pas flusher :
                  fichier() << "\n";
                }
            }
        }
      fichier().flush();
    }
  else
    {
// le processeur envoye un message que si il participe
      if (valeurs_locales.dimension(0)!=0)
        envoyer(valeurs_locales,Process::me(),0,2002+Process::me());
    }
}
References chsom, dim, TRUSTTab< _TYPE_ >::dimension(), elem_, envoyer(), fichier(), finl, Sortie_Fichier_base::flush(), Sondes::get_from_cache(), Champ_Generique_base::get_property(), gravcl, Process::je_suis_maitre(), les_positions(), Postraitement::les_sondes(), TRUSTVect< _TYPE_ >::line_size(), Process::me(), mettre_a_jour_bords(), mon_champ, mon_post, ncomp, nom_, nom_champ_lu_, Process::nproc(), ouvrir_fichier(), participant, Postraitement::probleme(), recevoir(), REF, ref_cast_non_const, Probleme_base::schema_temps(), vect_impl::size(), Schema_Temps_base::temps_courant(), Champ_base::valeur_aux_elems_compo_smooth(), Champ_base::valeur_aux_elems_smooth(), valeurs_locales, and valeurs_sur_maitre.
Referenced by mettre_a_jour().
printOn()
Sortie & Sonde::printOn (Sortie & s) const override protected virtual
Imprime le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 112 of file Sonde.cpp.
{
  return s << que_suis_je();
}
References Objet_U::que_suis_je().
readOn()
Entree & Sonde::readOn (Entree & is) override protected virtual
Lit les specifications d'une sonde a partir d'un flot d'entree.
Format:
Sondes
{
[nom_sonde nom_champ Periode dts Points n x1 y1 [z1] ... xn yn [zn]
[nom_sonde nom_champ Periode dts Segment ns x1 y1 [z1] x2 y2 [z2]
...
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 220 of file Sonde.cpp.
{
  assert(mon_post.non_nul());
  Motcle motlu;
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  int nbre_points;
  is >> motlu;
// Lecture d'un mot cle qui n'est pas le champ
  if (motlu=="nodes")
    {
      nodes = true;
      is >> motlu;
    }
  else if (motlu=="chsom")
    {
      chsom = true;
      is >> motlu;
    }
  else if (motlu=="grav")
    {
      grav = true;
      is >> motlu;
    }
  else if (motlu=="gravcl")
    {
      gravcl = true;
      is >> motlu;
    }
  else if (motlu=="som")
    {
      som = true;
      is >> motlu;
    }
// Affectation du nom du champ
  nom_champ_lu_ = motlu;
// Creation des Champ_Generique_refChamp necessaire pour l initialisation de la REF a Champ_Generique_base
// Si le champ demande est un Champ_base connu du probleme on cree le Champ_Generique_refChamp correspondant
  Probleme_base& Pb = mon_post->probleme();
  const Motcles& noms_champs_postraitables = mon_post->les_sondes().get_noms_champs_postraitables();
  if (noms_champs_postraitables.contient_(nom_champ_lu_))
    {
      Pb.creer_champ(nom_champ_lu_);
// On va creer un Champ_Generique_refChamp dont le nom a pour base
// le nom du champ auquel on fait reference et non pas une composante de ce champ
      REF(Champ_base) champ_ref = Pb.get_champ(nom_champ_lu_);
      const Nom& le_nom_champ = champ_ref->le_nom();
      const Motcle& nom_domaine = Pb.domaine().le_nom();
      Motcle identifiant;
      identifiant = Motcle(le_nom_champ)+"_natif_"+nom_domaine;
      if (!mon_post->comprend_champ_post(identifiant))
        {
          mon_post->creer_champ_post(le_nom_champ,"natif",is);
        }
    }
  else
    {
      Nom expression;
      int is_champ_predefini = Pb.expression_predefini(motlu,expression);
      if ((is_champ_predefini) && (!mon_post->comprend_champ_post(nom_champ_lu_)))
        {
          Champ_Generique champ;
          Entree_complete s_complete(expression,is);
          s_complete>>champ;
          mon_post->complete_champ(champ,nom_champ_lu_);
        }
    }
// Lecture des caracteristiques de la sonde
  IntVect fait(2);
  Motcles les_motcles(16);
  {
    les_motcles[0] = "periode";
    les_motcles[1] = "point";
    les_motcles[2] = "points";
    les_motcles[3] = "segment";
    les_motcles[4] = "plan";
    les_motcles[5] = "volume";
    les_motcles[6] = "segmentxdx";
    les_motcles[7] = "planxdxdy";
    les_motcles[8] = "circle";
    les_motcles[9] = "position_like";
    les_motcles[10] = "numero_elem_sur_maitre";
    les_motcles[11] = "segmentpoints";
    les_motcles[12] = "segmentfacesx";
    les_motcles[13] = "segmentfacesy";
    les_motcles[14] = "segmentfacesz";
    les_motcles[15] = "radius";
  }
  while ((fait(0) != 1) || (fait(1) != 1))
    {
      is >> motlu;
      if (motlu == accolade_fermee)
        {
          Cerr << "Error while reading the probe " << nom_ <<finl;
          Cerr << "The data of the probe were not defined" << finl;
          exit();
        }
      int rang=les_motcles.search(motlu);
      if (rang == -1)
        {
          Cerr << "Error while reading the probe " << nom_ <<finl;
          Cerr << motlu << " is not understood; the keywords understood are : " << finl;
          Cerr << les_motcles;
          exit();
        }
      switch(rang)
        {
        case 0:
          {
            is >> periode;
            break;
          }
        case 1:
        case 2:
        case 11:
          {
            type_ = les_motcles[rang];
            rang = 1;
            dim = 0;
            is >> nbre_points;
            les_positions_sondes_initiales_.resize(nbre_points,dimension);
            for (int i=0; i<nbre_points; i++)
              for (int j=0; j<dimension; j++)
                is >> les_positions_sondes_initiales_(i,j);
            break;
          }
        case 10:
          {
            type_ = les_motcles[rang];
            rang=1;
            dim=0;
            gravcl = false;
            is >> numero_elem_;
            les_positions_sondes_initiales_.resize(1,dimension);
            break;
          }
        case 3:
        case 6:
        case 12:
        case 13:
        case 14:
          {
            type_ = les_motcles[rang];
            int rang2=rang;
            rang = 1;
            dim = 1;
            if (rang2==12 || rang2==13 || rang2==14)
              {
                nodes = true;
                grav = false;
                gravcl = false;
                som = false;
              }
            const Motcle mot = type_.getSuffix("SEGMENTFACES");
            Motcles nom_dir(3);
            nom_dir[0] = "X";
            nom_dir[1] = "Y";
            nom_dir[2] = "Z";
            orientation_faces_ = nom_dir.search(mot);
            DoubleVect origine(dimension);
            DoubleVect extremite(dimension);
            DoubleVect dx(dimension);
            int i=0,j=0;
            is >> nbre_points;
            les_positions_sondes_initiales_.resize(nbre_points,dimension);
            for (; i<dimension; i++)
              {
                is >> origine(i);
                type_+=" ";
                type_+=(Nom)origine(i);
              }
            for (i=0; i<dimension; i++)
              {
                is >> extremite(i);
                type_+=" ";
                type_+=(Nom)extremite(i);
              }
            for (i=0; i<dimension; i++)
              if (rang2==6)
                dx(i)=(extremite(i))/(nbre_points-1);
              else
                dx(i)=(extremite(i)-origine(i))/(nbre_points-1);
            for (i=0; i<nbre_points; i++)
              for (j=0; j<dimension; j++)
                les_positions_sondes_initiales_(i,j)=origine(j)+i*dx(j);
            break;
          }
        case 4:
        case 7:
          {
            type_ = les_motcles[rang];
            int rang2=rang;
            rang = 1;
            dim = 2;
            gravcl = false;
            DoubleVect origine(dimension);
            DoubleVect extremite1(dimension);
            DoubleVect extremite2(dimension);
            DoubleVect dx1(dimension);
            DoubleVect dx2(dimension);
            int i=0,j=0,k=0;
            is >> nbre_points1;
            is >> nbre_points2;
            nbre_points=nbre_points1*nbre_points2;
            les_positions_sondes_initiales_.resize(nbre_points,dimension);
            for (; i<dimension; i++)
              is >> origine(i);
            for (i=0; i<dimension; i++)
              is >> extremite1(i);
            for (i=0; i<dimension; i++)
              is >> extremite2(i);
            if (rang2==7)
              {
                for (i=0; i<dimension; i++)
                  dx1(i)=(extremite1(i))/(nbre_points1-1);
                for (i=0; i<dimension; i++)
                  dx2(i)=(extremite2(i))/(nbre_points2-1);
              }
            else
              {
                for (i=0; i<dimension; i++)
                  dx1(i)=(extremite1(i)-origine(i))/(nbre_points1-1);
                for (i=0; i<dimension; i++)
                  dx2(i)=(extremite2(i)-origine(i))/(nbre_points2-1);
              }
            for (i=0; i<nbre_points1; i++)
              for (j=0; j<nbre_points2; j++)
                for (k=0; k<dimension; k++)
                  les_positions_sondes_initiales_(i*nbre_points2+j,k)=origine(k)+i*dx1(k)+j*dx2(k);
            break;
          }
        case 5:
          {
            type_ = les_motcles[rang];
            rang = 1;
            dim = 3;
            gravcl = false;
            ArrOfDouble origine(dimension);
            ArrOfDouble extremite1(dimension);
            ArrOfDouble extremite2(dimension);
            ArrOfDouble extremite3(dimension);
            ArrOfDouble dx1(dimension);
            ArrOfDouble dx2(dimension);
            ArrOfDouble dx3(dimension);
            int i=0,j=0,k=0;
            is >> nbre_points1;
            is >> nbre_points2;
            is >> nbre_points3;
            nbre_points=nbre_points1*nbre_points2*nbre_points3;
            les_positions_sondes_initiales_.resize(nbre_points,dimension);
            for (; i<dimension; i++)
              is >> origine[i];
            for (i=0; i<dimension; i++)
              is >> extremite1[i];
            for (i=0; i<dimension; i++)
              is >> extremite2[i];
            for (i=0; i<dimension; i++)
              is >> extremite3[i];
            for (i=0; i<dimension; i++)
              dx1[i]=(extremite1[i]-origine[i])/(nbre_points1-1);
            for (i=0; i<dimension; i++)
              dx2[i]=(extremite2[i]-origine[i])/(nbre_points2-1);
            for (i=0; i<dimension; i++)
              dx3[i]=(extremite3[i]-origine[i])/(nbre_points3-1);
            for (i=0; i<nbre_points1; i++)
              for (j=0; j<nbre_points2; j++)
                for (int m=0; m<nbre_points3; m++)
                  for (k=0; k<dimension; k++)
                    les_positions_sondes_initiales_(i+j*nbre_points1+m*nbre_points1*nbre_points2,k)=origine[k]+i*dx1[k]+j*dx2[k]+m*dx3[k];
            break;
          }
        case 8:
          {
            type_ = les_motcles[rang];
// circle nbre_points x0 y0 [z0 dir] radius teta1 teta2
            rang = 1;
            dim = 1;
            gravcl = false;
            int dir;
            double radius, teta1, teta2;
            DoubleVect origine(dimension);
            is >> nbre_points;
            les_positions_sondes_initiales_.resize(nbre_points,dimension);
            for (int i=0; i<dimension; i++)
              is >> origine(i);
            if (dimension==3) is >> dir;
            is >> radius >> teta1 >> teta2;
// Ajout des informations
            for (int i=0; i<dimension; i++)
              {
                type_+=" ";
                type_+=(Nom)origine(i);
              }
            type_+=" ";
            type_+=(Nom)radius;
            type_+=" ";
            type_+=(Nom)teta1;
            type_+=" ";
            type_+=(Nom)teta2;
// We calculate the positions
            for (int i=0; i<nbre_points; i++)
              {
                double angle=teta1+(teta2-teta1)*i/(nbre_points-1);
                angle*=M_PI/180;
                if (dimension==2)
                  {
                    les_positions_sondes_initiales_(i,0)=origine(0)+radius*cos(angle);
                    les_positions_sondes_initiales_(i,1)=origine(1)+radius*sin(angle);
                  }
                else if (dimension==3)
                  {
                    if (dir==0)
                      {
                        les_positions_sondes_initiales_(i,0)=origine(0);
                        les_positions_sondes_initiales_(i,1)=origine(1)+radius*cos(angle);
                        les_positions_sondes_initiales_(i,2)=origine(2)+radius*sin(angle);
                      }
                    else if (dir==1)
                      {
                        les_positions_sondes_initiales_(i,0)=origine(0)+radius*cos(angle);
                        les_positions_sondes_initiales_(i,1)=origine(1);
                        les_positions_sondes_initiales_(i,2)=origine(2)+radius*sin(angle);
                      }
                    else if (dir==2)
                      {
                        les_positions_sondes_initiales_(i,0)=origine(0)+radius*cos(angle);
                        les_positions_sondes_initiales_(i,1)=origine(1)+radius*sin(angle);
                        les_positions_sondes_initiales_(i,2)=origine(2);
                      }
                  }
              }
            break;
          }
        case 15:
          {
            assert(dimension==3);
            type_ = les_motcles[rang];
// radius nbre_points x0 y0 z0 theta radius1 radius2
            rang = 1;
            dim = 1;
            gravcl = false;
            double theta, radius1, radius2;
            DoubleVect origine(dimension);
            is >> nbre_points;
            les_positions_sondes_initiales_.resize(nbre_points,dimension);
            for (int i=0; i<dimension; i++)
              is >> origine(i);
            is >> theta >> radius1 >> radius2;
// Ajout des informations
            for (int i=0; i<dimension; i++)
              {
                type_+=" ";
                type_+=(Nom)origine(i);
              }
            type_+=" ";
            type_+=(Nom)theta;
            type_+=" ";
            type_+=(Nom)radius1;
            type_+=" ";
            type_+=(Nom)radius2;
// We calculate the positions
            theta*=M_PI/180;
            for (int i=0; i<nbre_points; i++)
              {
                double radius = radius1+(radius2-radius1)*i/(nbre_points-1);
                les_positions_sondes_initiales_(i,0)=origine(0)+radius*cos(theta);
                les_positions_sondes_initiales_(i,1)=origine(1)+radius*sin(theta);
                les_positions_sondes_initiales_(i,2)=origine(2);
              }
            break;
          }
        case 9:
          {
            Motcle autre_sonde;
            is >> autre_sonde;
// on cherche la sonde correspondante
            int m=-1;
            const Sondes& les_sondes=mon_post->les_sondes();
            for (int i=0; i<les_sondes.size(); i++)
              if (les_sondes(i).get_nom()==autre_sonde)
                {
                  m=i;
                  break;
                }
// else Cerr<<les_sondes(i).get_nom()<<finl;
            if (m==-1)
              {
                Cerr<<" The probe name "<<autre_sonde<< " was not found"<<finl;
                exit();
              }
// on recupere  les_positions_
            const Sonde& la_sonde_ref=les_sondes(m);
            type_ = la_sonde_ref.get_type();
            les_positions_sondes_initiales_=la_sonde_ref.les_positions_sondes_initiales();
            dim =  la_sonde_ref.get_dim();
            rang=1;
            break;
          }
        default:
          {
            Cerr << motlu <<"is not yet understood!" << finl;
            exit();
          }
        }
      fait(rang) = 1;
    }
  if ( (fait[0] == 0) || (fait[1] == 0) || (dim==-1))
    {
      Cerr << "Error while reading the probe " << nom_ << finl;
      Cerr << "The data of the probe have not been properly defined" << finl;
      exit();
    }
// Construction du fichier associe a la sonde
  nom_fichier_=nom_du_cas();
  nom_fichier_+= "_";
  nom_fichier_+= nom_;
  if (dim==2)
    nom_fichier_+= ".plan";
  else
    nom_fichier_+= ".son";
  if (Process::je_suis_maitre())
    {
// Ajout du nom du fichier sonde dans le fichier listant les sondes
// Ce fichier sera utilise par Run_sonde
      SFichier fichier_sondes;
      Nom nom_fich=nom_du_cas();
      nom_fich+=".sons";
      if (!fichier_sondes_cree)
        fichier_sondes.ouvrir(nom_fich);
      else
        fichier_sondes.ouvrir(nom_fich,ios::app);
      fichier_sondes << nom_fichier_ << finl;
      fichier_sondes_cree=1;
    }
  return is;
}
References Cerr, chsom, Postraitement::complete_champ(), Postraitement::comprend_champ_post(), Motcles::contient_(), Probleme_base::creer_champ(), Postraitement::creer_champ_post(), dim, Objet_U::dimension, Probleme_base::domaine(), Process::exit(), Probleme_base::expression_predefini(), fichier_sondes_cree, finl, Probleme_base::get_champ(), get_dim(), get_nom(), Sondes::get_noms_champs_postraitables(), get_type(), Nom::getSuffix(), grav, gravcl, Process::je_suis_maitre(), Domaine::le_nom(), Nom::le_nom(), les_positions_sondes_initiales(), les_positions_sondes_initiales_, Postraitement::les_sondes(), M_PI, mon_post, nbre_points1, nbre_points2, nbre_points3, nodes, nom_, nom_champ_lu_, Objet_U::nom_du_cas(), nom_fichier_, O_U_Ptr::non_nul(), numero_elem_, orientation_faces_, Sortie_Fichier_base::ouvrir(), periode, Postraitement::probleme(), REF, TRUSTTab< _TYPE_ >::resize(), Motcles::search(), liste::size(), som, and type_.
self_cast() [1/2]
const Sonde & Sonde::self_cast (const Objet_U & r) static
Definition at line 29 of file Sonde.cpp.
self_cast() [2/2]
Sonde & Sonde::self_cast (Objet_U & r) static
Definition at line 29 of file Sonde.cpp.
taille_memoire()
unsigned Sonde::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 29 of file Sonde.cpp.
temps()
double Sonde::temps () const inline
Le temps ecoule.
Returns
double
Signification: le temps ecoule
Contraintes:
Definition at line 132 of file Sonde.h.
{
  return nb_bip*periode;
}
References nb_bip, and periode.
Member Data Documentation
chsom
bool Sonde::chsom protected
Definition at line 102 of file Sonde.h.
Referenced by postraiter(), and readOn().
dim
int Sonde::dim protected
la dimension de la sone (point:0,segment:1,plan:2,volume:3)
Definition at line 88 of file Sonde.h.
Referenced by get_dim(), ouvrir_fichier(), postraiter(), and readOn().
elem_
IntVect Sonde::elem_ protected
les elements contenant les sondes ponctuelles locales
Definition at line 99 of file Sonde.h.
Referenced by ajouter_bords(), initialiser(), les_poly(), and postraiter().
faces_bords_
ArrOfInt Sonde::faces_bords_ protected
array containing the indices of the boundary faces hit by the probe
Definition at line 113 of file Sonde.h.
Referenced by ajouter_bords(), init_bords(), and mettre_a_jour_bords().
grav
bool Sonde::grav protected
Definition at line 102 of file Sonde.h.
Referenced by initialiser(), and readOn().
gravcl
bool Sonde::gravcl protected
Definition at line 102 of file Sonde.h.
Referenced by init_bords(), initialiser(), postraiter(), and readOn().
info_obj
const Type_info Sonde::info_obj static
Definition at line 43 of file Sonde.h.
le_fichier_
SFichier Sonde::le_fichier_ protected
Definition at line 105 of file Sonde.h.
Referenced by fermer_fichier(), fichier(), and ouvrir_fichier().
les_positions_
DoubleTab Sonde::les_positions_ protected
les coordonnees des sondes locales sur chaque proc
Definition at line 97 of file Sonde.h.
Referenced by initialiser(), and les_positions().
les_positions_sondes_
DoubleTab Sonde::les_positions_sondes_ protected
les coordonnees des sondes sur tout le domaine apres deplacement (uniquement sur le maitre)
Definition at line 96 of file Sonde.h.
Referenced by ajouter_bords(), initialiser(), les_positions_sondes(), and ouvrir_fichier().
les_positions_sondes_initiales_
DoubleTab Sonde::les_positions_sondes_initiales_ protected
les coordonnees des sondes ponctuelles initiales
Definition at line 95 of file Sonde.h.
Referenced by initialiser(), les_positions_sondes_initiales(), and readOn().
mon_champ
Ref_Champ_Generique_base Sonde::mon_champ protected
Definition at line 90 of file Sonde.h.
Referenced by ajouter_bords(), completer(), init_bords(), initialiser(), le_champ(), mettre_a_jour(), mettre_a_jour_bords(), and postraiter().
mon_post
Ref_Postraitement Sonde::mon_post protected
Definition at line 85 of file Sonde.h.
Referenced by associer_post(), completer(), init_bords(), initialiser(), mettre_a_jour(), mettre_a_jour_bords(), ouvrir_fichier(), postraiter(), and readOn().
nb_bip
double Sonde::nb_bip protected
Definition at line 104 of file Sonde.h.
Referenced by mettre_a_jour(), and temps().
nbre_points1
int Sonde::nbre_points1 protected
Definition at line 89 of file Sonde.h.
Referenced by ouvrir_fichier(), and readOn().
nbre_points2
int Sonde::nbre_points2 protected
Definition at line 89 of file Sonde.h.
Referenced by ouvrir_fichier(), and readOn().
nbre_points3
int Sonde::nbre_points3 protected
faire des sonde_segment,sonde_plan,etc...
Definition at line 89 of file Sonde.h.
Referenced by ouvrir_fichier(), and readOn().
ncomp
int Sonde::ncomp protected
Numero de la composante a sonder Si ncomp = -1 la sonde s'applique a toutes les composantes du champ.
Definition at line 92 of file Sonde.h.
Referenced by completer(), initialiser(), and postraiter().
nodes
bool Sonde::nodes protected
Definition at line 102 of file Sonde.h.
Referenced by initialiser(), and readOn().
nom_
Nom Sonde::nom_ protected
le nom de la sonde
Definition at line 86 of file Sonde.h.
Referenced by associer_post(), completer(), get_nom(), initialiser(), ouvrir_fichier(), postraiter(), and readOn().
nom_champ_lu_
Motcle Sonde::nom_champ_lu_ protected
Definition at line 106 of file Sonde.h.
Referenced by completer(), init_bords(), mettre_a_jour(), mettre_a_jour_bords(), ouvrir_fichier(), postraiter(), and readOn().
nom_fichier_
Nom Sonde::nom_fichier_ protected
le nom du fichier contenant la sonde
Definition at line 87 of file Sonde.h.
Referenced by ouvrir_fichier(), and readOn().
numero_elem_
int Sonde::numero_elem_ protected
vaut -1 si pas defini et vaut le numero de l'elem sur le maitre
Definition at line 98 of file Sonde.h.
Referenced by initialiser(), and readOn().
operateur_statistique_
Ref_Operateur_Statistique_tps_base Sonde::operateur_statistique_ protected
Reference vers un operateur statistique eventuel.
Definition at line 91 of file Sonde.h.
orientation_faces_
int Sonde::orientation_faces_ protected
Definition at line 110 of file Sonde.h.
Referenced by initialiser(), and readOn().
participant
ArrsOfInt Sonde::participant protected
vecteur d'ArrOfInt sur le maitre ; participant[pe][i] -> le ieme point sur pe correspond la participant [pe][i] eme position
Definition at line 107 of file Sonde.h.
Referenced by initialiser(), and postraiter().
periode
double Sonde::periode protected
periode d'echantillonnage cles pour typage des sondes (sondes redefinies aux noeuds ou d'apres les valeurs aux sommets ou au centre de gravite ou aux sommets)
Definition at line 100 of file Sonde.h.
Referenced by fixer_periode(), mettre_a_jour(), readOn(), and temps().
rang_cl_
IntTab Sonde::rang_cl_ protected
for a given face, index of the CL that this face bears
Definition at line 114 of file Sonde.h.
Referenced by init_bords(), and mettre_a_jour_bords().
reprise
int Sonde::reprise protected
si reprise=0, on cree la sonde, sinon on ecrit a la suite
Definition at line 108 of file Sonde.h.
Referenced by mettre_a_jour(), and ouvrir_fichier().
som
bool Sonde::som protected
Definition at line 102 of file Sonde.h.
Referenced by initialiser(), and readOn().
type_
Nom Sonde::type_ protected
Definition at line 109 of file Sonde.h.
Referenced by get_type(), and readOn().
valeurs_locales
DoubleTab Sonde::valeurs_locales protected
Definition at line 103 of file Sonde.h.
Referenced by initialiser(), mettre_a_jour_bords(), and postraiter().
valeurs_sur_maitre
DoubleTab Sonde::valeurs_sur_maitre protected
valeurs_locales les valeurs sur chaque proc, valeurs_sur_maitre les valeurs regroupes sur le maitre
Definition at line 103 of file Sonde.h.
Referenced by initialiser(), and postraiter().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Sonde.h
src/Kernel/Framework/Sonde.cpp