TRUST: Evaluateur_Source_EF Class Reference
Evaluateur_Source_EF Class Reference abstract
#include <Evaluateur_Source_EF.h>
Public Member Functions
Evaluateur_Source_EF ()
virtual ~Evaluateur_Source_EF ()
Evaluateur_Source_EF (const Evaluateur_Source_EF &)
void associer_zones (const Zone_EF &, const Zone_Cl_EF &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
Protected Attributes
Ref_Zone_EF la_zone
Ref_Zone_Cl_EF la_zone_cl
Detailed Description
Definition at line 30 of file Evaluateur_Source_EF.h.
Constructor & Destructor Documentation
Evaluateur_Source_EF() [1/2]
Evaluateur_Source_EF::Evaluateur_Source_EF () inline
Definition at line 53 of file Evaluateur_Source_EF.h.
{}
~Evaluateur_Source_EF()
virtual Evaluateur_Source_EF::~Evaluateur_Source_EF () inline virtual
Definition at line 36 of file Evaluateur_Source_EF.h.
{};
Evaluateur_Source_EF() [2/2]
Evaluateur_Source_EF::Evaluateur_Source_EF (const Evaluateur_Source_EF & eval) inline
Definition at line 55 of file Evaluateur_Source_EF.h.
  : la_zone(eval.la_zone),la_zone_cl(eval.la_zone_cl)
{
}
Member Function Documentation
associer_zones()
void Evaluateur_Source_EF::associer_zones (const Zone_EF & zone_EF, const Zone_Cl_EF & zone_cl_EF) inline
Definition at line 60 of file Evaluateur_Source_EF.h.
{
  la_zone = zone_EF;
  la_zone_cl = zone_cl_EF;
  completer();
}
References completer(), la_zone, and la_zone_cl.
Referenced by Puissance_Thermique_EF::associer_zones(), and Puissance_Thermique_QC_EF::associer_zones().
completer()
virtual void Evaluateur_Source_EF::completer () pure virtual
Implemented in Eval_Puiss_Th_EF, Evaluateur_Source_EF_Som, and Eval_Puiss_Th_QC_EF.
Referenced by associer_zones().
mettre_a_jour()
virtual void Evaluateur_Source_EF::mettre_a_jour () pure virtual
Implemented in Eval_Puiss_Th_EF, and Eval_Puiss_Th_QC_EF.
Member Data Documentation
la_zone
Ref_Zone_EF Evaluateur_Source_EF::la_zone protected
Definition at line 44 of file Evaluateur_Source_EF.h.
Referenced by associer_zones().
la_zone_cl
Ref_Zone_Cl_EF Evaluateur_Source_EF::la_zone_cl protected
Definition at line 45 of file Evaluateur_Source_EF.h.
Referenced by associer_zones().
The documentation for this class was generated from the following file:
src/EF/Sources/Evaluateur_Source_EF.h