TRUST: Assembleur_P_VDF_Q4 Class Reference
Assembleur_P_VDF_Q4 Class Reference
#include <Assembleur_P_VDF_Q4.h>
Public Member Functions
Assembleur_P_VDF_Q4 ()
~Assembleur_P_VDF_Q4 ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &) override
const Zone_dis_base & zone_dis_base () const override
const Zone_Cl_dis_base & zone_Cl_dis_base () const override
int assembler (Matrice &) override
int modifier_secmem (DoubleTab &) override
int modifier_secmem (const DoubleTab &tab_secmem_, DoubleVect &)
int modifier_solution (DoubleTab &) override
void completer (const Equation_base &) override
Public Member Functions inherited from Assembleur_base
Assembleur_base ()
~Assembleur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int set_resoudre_increment_pression (int flag)
Definit la valeur du drapeau resoudre_increment_pression_.
Ce drapeau determine si le solveur en pression calcule un increment de
pression entre deux pas de temps ou la pression totale (cela affecte
en particulier le calcul des conditions aux limites).
flag = 0 : resolution en pression
flag = 1 : resolution en increment de pression.
int get_resoudre_increment_pression () const
Renvoie la valeur du drapeau resoudre_increment_pression_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
int set_resoudre_en_u (int flag)
Definit la valeur du drapeau resoudre_en_u__.
Ce drapeau determine si le solveur en pression resou en u ou en rho*u
(cela affecte
en particulier le calcul des conditions aux limites Dirichlet).
flag = 1 : resolution en u
flag = 0 : resolution en rho_u.
int get_resoudre_en_u () const
Renvoie la valeur du drapeau resoudre_en_u_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
virtual int assembler (Matrice &)=0
virtual int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u)
virtual int assembler_rho_variable (Matrice &, const Champ_Don_base &rho)
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
virtual int assembler_QC (const DoubleTab &, Matrice &)
virtual void completer (const Equation_base &)=0
virtual void associer_zone_dis_base (const Zone_dis_base &)=0
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)=0
virtual const Zone_dis_base & zone_dis_base () const =0
virtual const Zone_Cl_dis_base & zone_Cl_dis_base () const =0
virtual int modifier_secmem (DoubleTab &)=0
virtual void modifier_secmem_pour_incr_p (const DoubleTab &press, const double fac, DoubleTab &incr) const
virtual int modifier_solution (DoubleTab &)=0
virtual void dimensionner_continuite (matrices_t matrices, int aux_only=0) const
virtual void assembler_continuite (matrices_t matrices, DoubleTab &secmem, int aux_only=0) const
virtual DoubleTab norme_continuite () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Assembleur_P_VDF_Q4 & self_cast (Objet_U &)
static const Assembleur_P_VDF_Q4 & self_cast (const Objet_U &)
Static Public Member Functions inherited from Assembleur_base
static const Type_info * info ()
static Assembleur_base & self_cast (Objet_U &)
static const Assembleur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Assembleur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VDF la_zone_VDF
Ref_Zone_Cl_VDF la_zone_Cl_VDF
Ref_Equation_base eqn_
Detailed Description
Definition at line 30 of file Assembleur_P_VDF_Q4.h.
Constructor & Destructor Documentation
Assembleur_P_VDF_Q4()
Assembleur_P_VDF_Q4::Assembleur_P_VDF_Q4 ()
Definition at line 21 of file Assembleur_P_VDF_Q4.cpp.
~Assembleur_P_VDF_Q4()
Assembleur_P_VDF_Q4::~Assembleur_P_VDF_Q4 ()
Definition at line 21 of file Assembleur_P_VDF_Q4.cpp.
Member Function Documentation
assembler()
int Assembleur_P_VDF_Q4::assembler (Matrice & la_matrice) override virtual
Implements Assembleur_base.
Definition at line 33 of file Assembleur_P_VDF_Q4.cpp.
{
  Cerr << "Assembleur_P_VDF_Q4::assembler " << finl;
  Cerr << "Assemblage de la matrice Q4 en cours..." << finl;
  const IntTab& FaceSoms = la_zone_VDF->face_sommets();
  const IntTab& FaceVois = la_zone_VDF->face_voisins();
  const IntVect& Orientation = la_zone_VDF->orientation();
  int face, som0,som1;
  int nbfaces = la_zone_VDF->nb_faces(),  nbsom = la_zone_VDF->nb_som();
  const DoubleVect& volumes_entrelaces = la_zone_VDF->volumes_entrelaces();
  const DoubleVect& porosite_face = la_zone_VDF->porosite_face();
  const DoubleTab& CoordSom = la_zone_VDF->zone().domaine().coord_sommets();
  double surf,vol,por,val, r;
  int ori, elem0,elem1;
// construction matrice
  la_matrice.typer("Matrice_Morse");
  Matrice_Morse& mat = ref_cast(Matrice_Morse,la_matrice.valeur());
  mat.dimensionner(nbsom,0);
  IntVect rang_voisins(nbsom);
  IntVect& tab1 = mat.get_set_tab1();
  IntVect& tab2 = mat.get_set_tab2();
  DoubleVect& coeff = mat.get_set_coeff();
  tab1 = 0;
  tab2 = 0;
  coeff = 0;
  rang_voisins = 1;
  for (face=0 ; face<nbfaces ; face++)
    {
      som0 = FaceSoms(face,0);
      som1 = FaceSoms(face,1);
      rang_voisins(som0)++;
      rang_voisins(som1)++;
    }
  tab1(0) = 1;
  for (som0=0 ; som0<nbsom ; som0++)
    {
      tab1(som0+1) = rang_voisins(som0) + tab1(som0);
    }
  rang_voisins = 1;
  mat.dimensionner(nbsom,tab1(nbsom)-1);
// calcul coefficient matrice
  for (face=0 ; face<nbfaces ; face++)
    {
      ori = Orientation(face);
      som0 = FaceSoms(face,0);
      som1 = FaceSoms(face,1);
      elem0 = FaceVois(face,0);
      elem1 = FaceVois(face,1);
      if (elem0>-1 && elem1>-1)
        {
          surf = 0.5* (la_zone_VDF->dim_elem(elem0,ori) + la_zone_VDF->dim_elem(elem1,ori));
        }
      else if (elem0>-1)
        {
          surf = la_zone_VDF->dim_elem(elem0,ori);
        }
      else
        {
          surf = 0.;
          surf = la_zone_VDF->dim_elem(elem1,ori);
        }
      if (bidim_axi/* && ori==1*/)
        {
          r = 0.5*(CoordSom(som0,0)+CoordSom(som1,0));
          surf = r * surf * 2 * M_PI;
        }
      vol = volumes_entrelaces(face);
      por = porosite_face(face);
      val = surf*surf /vol * por;
#ifdef _AFFDEBUG
      if (la_zone_VDF->nb_som()<400)
        {
          Cerr<<"face="<<face<<"  ori="<<ori<<"  soms="<<som0<<"/"<<som1<<" coordsom="<<CoordSom(som0,0)<<"/"<<CoordSom(som0,1);
          Cerr<<" "<<CoordSom(som1,0)<<"/"<<CoordSom(som1,1)<<"  elems="<<FaceVois(face,0)<<"/"<<FaceVois(face,1)<<"  dim_elems/2=";
          if (FaceVois(face,0)>-1)
            Cerr<<la_zone_VDF->dim_elem(FaceVois(face,0),ori)/2.<<" / ";
          else
            Cerr<<"--- / ";
          if (FaceVois(face,1)>-1)
            Cerr<<la_zone_VDF->dim_elem(FaceVois(face,1),ori)/2.<<"  ";
          else
            Cerr<<"---  ";
          Cerr<<"  surf="<<surf<<"  vol="<<vol<<"  val="<<val<<finl;
        }
#endif
      tab2(tab1(som0)-1) = som0+1;
      tab2(tab1(som1)-1) = som1+1;
      mat(som0,som0) += val;
      mat(som1,som1) += val;
// if (coeff(tab1(som0)+rang_voisins(som0)-1)!=-1) {
      tab2(tab1(som0)+rang_voisins(som0)-1) = som1+1;
      mat(som0,som1) -= val;
      rang_voisins(som0)++;
      tab2(tab1(som1)+rang_voisins(som1)-1) = som0+1;
      mat(som1,som0) -= val;
      rang_voisins(som1)++;
// }
    }
  Cerr << "Fin de l'assemblage de la matrice Q4" << finl;
  return 1;
}
References Objet_U::bidim_axi, Cerr, coeff, Domaine::coord_sommets(), Zone_VDF::dim_elem(), Matrice_Morse::dimensionner(), Zone::domaine(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), finl, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), la_zone_VDF, M_PI, Zone_VF::nb_faces(), Zone_dis_base::nb_som(), Zone_VDF::orientation(), Zone_VF::porosite_face(), ref_cast, Deriv_::typer(), Deriv_Matrice_Base::valeur(), Zone_VF::volumes_entrelaces(), and Zone_dis_base::zone().
associer_zone_cl_dis_base()
void Assembleur_P_VDF_Q4::associer_zone_cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis) override virtual
Implements Assembleur_base.
Definition at line 226 of file Assembleur_P_VDF_Q4.cpp.
{
  la_zone_Cl_VDF =ref_cast(Zone_Cl_VDF, la_zone_Cl_dis);
}
References la_zone_Cl_VDF, and ref_cast.
associer_zone_dis_base()
void Assembleur_P_VDF_Q4::associer_zone_dis_base (const Zone_dis_base & la_zone_dis) override virtual
Implements Assembleur_base.
Definition at line 221 of file Assembleur_P_VDF_Q4.cpp.
{
  la_zone_VDF = ref_cast(Zone_VDF, la_zone_dis);
}
References la_zone_VDF, and ref_cast.
completer()
void Assembleur_P_VDF_Q4::completer (const Equation_base & Eqn) override virtual
Implements Assembleur_base.
Definition at line 231 of file Assembleur_P_VDF_Q4.cpp.
{
  eqn_ = Eqn;
}
References eqn_.
cree_instance()
Objet_U * Assembleur_P_VDF_Q4::cree_instance () static
Definition at line 21 of file Assembleur_P_VDF_Q4.cpp.
duplique()
int Assembleur_P_VDF_Q4::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Assembleur_P_VDF_Q4.cpp.
get_info()
const Type_info * Assembleur_P_VDF_Q4::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 21 of file Assembleur_P_VDF_Q4.cpp.
info()
const Type_info * Assembleur_P_VDF_Q4::info () static
Definition at line 21 of file Assembleur_P_VDF_Q4.cpp.
modifier_secmem() [1/2]
int Assembleur_P_VDF_Q4::modifier_secmem (const DoubleTab & tab_secmem_, DoubleVect & secmem)
Definition at line 142 of file Assembleur_P_VDF_Q4.cpp.
{
  const DoubleTab& CoordSommets = la_zone_VDF->zone().domaine().coord_sommets();
  const IntTab& FaceSoms = la_zone_VDF->face_sommets();
  const IntTab& FaceVois = la_zone_VDF->face_voisins();
  const IntVect& Orientation = la_zone_VDF->orientation();
  const DoubleTab& CoordSom = la_zone_VDF->zone().domaine().coord_sommets();
  int face, som0,som1, ori, invori, elem0,elem1;
  int nbfaces = la_zone_VDF->nb_faces(),  nbsom = la_zone_VDF->nb_som();
  double surf, r;
  secmem.resize(nbsom);
  secmem = 0.;
  for (face=0 ; face<nbfaces ; face++)
    {
      surf = 0.;
      ori = Orientation(face);
      som0 = FaceSoms(face,0);
      som1 = FaceSoms(face,1);
      elem0 = FaceVois(face,0);
      elem1 = FaceVois(face,1);
      if (elem0>-1 && elem1>-1)
        {
          surf = 0.5* (la_zone_VDF->dim_elem(elem0,ori) + la_zone_VDF->dim_elem(elem1,ori));
        }
      else if (elem0>-1)
        {
          surf = la_zone_VDF->dim_elem(elem0,ori);
        }
      else if (elem1>-1)
        {
          surf = la_zone_VDF->dim_elem(elem1,ori);
        }
      else
        {
          assert(0==1);
        }
      if (bidim_axi/* && ori==1*/)
        {
          r = 0.5*(CoordSom(som0,0)+CoordSom(som1,0));
          surf = r * surf * 2 * M_PI;
        }
      if (ori==0)
        invori = 1;
      else
        invori = 0;
      if (CoordSommets(som1,invori)>CoordSommets(som0,invori))
        {
          secmem(som0) += tab_secmem_(face) * surf;
          secmem(som1) -= tab_secmem_(face) * surf;
        }
      else
        {
          secmem(som0) -= tab_secmem_(face) * surf;
          secmem(som1) += tab_secmem_(face) * surf;
        }
      secmem.echange_espace_virtuel();
    }
  return 1;
}
References Objet_U::bidim_axi, Domaine::coord_sommets(), Zone_VDF::dim_elem(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), la_zone_VDF, M_PI, Zone_VF::nb_faces(), Zone_dis_base::nb_som(), Zone_VDF::orientation(), TRUSTVect< _TYPE_ >::resize(), and Zone_dis_base::zone().
modifier_secmem() [2/2]
int Assembleur_P_VDF_Q4::modifier_secmem (DoubleTab & secmem) override virtual
Implements Assembleur_base.
Definition at line 137 of file Assembleur_P_VDF_Q4.cpp.
{
  return 1;
}
modifier_solution()
int Assembleur_P_VDF_Q4::modifier_solution (DoubleTab & pression) override virtual
Implements Assembleur_base.
Definition at line 205 of file Assembleur_P_VDF_Q4.cpp.
{
  Cerr<<"Assembleur_P_VDF_Q4::modifier_solution"<<finl;
  return 1;
}
References Cerr, and finl.
printOn()
Sortie & Assembleur_P_VDF_Q4::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 23 of file Assembleur_P_VDF_Q4.cpp.
{
  return s << que_suis_je() << " " << le_nom() ;
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Assembleur_P_VDF_Q4::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 28 of file Assembleur_P_VDF_Q4.cpp.
{
  return Assembleur_base::readOn(s);
}
References Assembleur_base::readOn().
self_cast() [1/2]
const Assembleur_P_VDF_Q4 & Assembleur_P_VDF_Q4::self_cast (const Objet_U & r) static
Definition at line 21 of file Assembleur_P_VDF_Q4.cpp.
self_cast() [2/2]
Assembleur_P_VDF_Q4 & Assembleur_P_VDF_Q4::self_cast (Objet_U & r) static
Definition at line 21 of file Assembleur_P_VDF_Q4.cpp.
taille_memoire()
unsigned Assembleur_P_VDF_Q4::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Assembleur_P_VDF_Q4.cpp.
zone_Cl_dis_base()
const Zone_Cl_dis_base & Assembleur_P_VDF_Q4::zone_Cl_dis_base () const override virtual
Implements Assembleur_base.
Definition at line 216 of file Assembleur_P_VDF_Q4.cpp.
{
  return la_zone_Cl_VDF.valeur();
}
References la_zone_Cl_VDF, and Ref_Zone_Cl_VDF::valeur().
zone_dis_base()
const Zone_dis_base & Assembleur_P_VDF_Q4::zone_dis_base () const override virtual
Implements Assembleur_base.
Definition at line 211 of file Assembleur_P_VDF_Q4.cpp.
{
  return la_zone_VDF.valeur();
}
References la_zone_VDF, and Ref_Zone_VDF::valeur().
Member Data Documentation
eqn_
Ref_Equation_base Assembleur_P_VDF_Q4::eqn_ protected
Definition at line 48 of file Assembleur_P_VDF_Q4.h.
Referenced by completer().
info_obj
const Type_info Assembleur_P_VDF_Q4::info_obj static
Definition at line 32 of file Assembleur_P_VDF_Q4.h.
la_zone_Cl_VDF
Ref_Zone_Cl_VDF Assembleur_P_VDF_Q4::la_zone_Cl_VDF protected
Definition at line 47 of file Assembleur_P_VDF_Q4.h.
Referenced by associer_zone_cl_dis_base(), and zone_Cl_dis_base().
la_zone_VDF
Ref_Zone_VDF Assembleur_P_VDF_Q4::la_zone_VDF protected
Definition at line 46 of file Assembleur_P_VDF_Q4.h.
Referenced by assembler(), associer_zone_dis_base(), modifier_secmem(), and zone_dis_base().
The documentation for this class was generated from the following files:
src/VDF/Solveurs/Assembleur_P_VDF_Q4.h
src/VDF/Solveurs/Assembleur_P_VDF_Q4.cpp