TRUST: Masse_PolyMAC_Elem Class Reference
Masse_PolyMAC_Elem Class Reference
#include <Masse_PolyMAC_Elem.h>
Public Member Functions
Masse_PolyMAC_Elem ()
~Masse_PolyMAC_Elem ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &) override
void preparer_calcul () override
DoubleTab & appliquer_impl (DoubleTab &) const override
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, double dt, const tabs_t &semi_impl, int resoudre_en_increments) const override
Public Member Functions inherited from Solveur_Masse_base
Solveur_Masse_base ()
~Solveur_Masse_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & appliquer (DoubleTab &) const
renvoie appliquer_impl(x/coeffient_temporelle)
si on a un coefficient temporelle
sinon renvoie appliquer_impl(x)
Return M-1.x
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du solveur de masse.
virtual void associer_zone_dis_base (const Zone_dis_base &)=0
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)=0
virtual void assembler ()
NE FAIT RIEN
Eventuellement a surcharger dans les classes derivees
si la matrice de masse necessite un assemblage.
Assemble le solveur de masse (en general la matrice de masse)
virtual Matrice_Base & ajouter_masse (double dt, Matrice_Base &matrice, int penalisation=1) const
virtual DoubleTab & ajouter_masse (double dt, DoubleTab &x, const DoubleTab &y, int penalisation=1) const
virtual Matrice_Base & ajouter_masse_dt_local (DoubleVect &dt_locaux, Matrice_Base &matrice, int penalisation=1) const
virtual DoubleTab & ajouter_masse_dt_local (DoubleVect &dt_locaux, DoubleTab &x, const DoubleTab &y, int penalisation=1) const
virtual void get_masse_dt_local (DoubleVect &m_dt_locaux, DoubleVect &dt_locaux, int penalisation=1)
virtual void get_masse_divide_by_local_dt (DoubleVect &m_dt_locaux, DoubleVect &dt_locaux, int penalisation=1)
virtual DoubleTab & corriger_solution (DoubleTab &x, const DoubleTab &y, int incr=0) const
void set_name_of_coefficient_temporel (const Nom &)
permet de choisir le nom du coefficient temporelle
que l'on veut utiliser pour appliquer
verifie que le champ exsite bien
int has_coefficient_temporel () const
const Nom & get_name_of_coefficient_temporel () const
virtual DoubleTab & appliquer_impl (DoubleTab &x) const =0
virtual void dimensionner (Matrice_Morse &matrix) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, double dt, const tabs_t &semi_impl, int resoudre_en_increments) const
virtual void completer (void)
virtual void preparer_calcul (void)
void set_penalisation_flag (int pen)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Masse_PolyMAC_Elem & self_cast (Objet_U &)
static const Masse_PolyMAC_Elem & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_Masse_base
static const Type_info * info ()
static Solveur_Masse_base & self_cast (Objet_U &)
static const Solveur_Masse_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Solveur_Masse_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Private Attributes
Ref_Zone_PolyMAC la_zone_PolyMAC
Ref_Zone_Cl_PolyMAC la_zone_Cl_PolyMAC
Additional Inherited Members
Protected Attributes inherited from Solveur_Masse_base
Nom name_of_coefficient_temporel_
nom du coefficient temporelle
int has_coefficient_temporel_
int penalisation_flag_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 30 of file Masse_PolyMAC_Elem.h.
Constructor & Destructor Documentation
Masse_PolyMAC_Elem()
Masse_PolyMAC_Elem::Masse_PolyMAC_Elem ()
Definition at line 33 of file Masse_PolyMAC_Elem.cpp.
~Masse_PolyMAC_Elem()
Masse_PolyMAC_Elem::~Masse_PolyMAC_Elem ()
Definition at line 33 of file Masse_PolyMAC_Elem.cpp.
Member Function Documentation
ajouter_blocs()
void Masse_PolyMAC_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, double dt, const tabs_t & semi_impl, int resoudre_en_increments) const override virtual
Reimplemented from Solveur_Masse_base.
Definition at line 105 of file Masse_PolyMAC_Elem.cpp.
{
  const Zone_PolyMAC& zone = la_zone_PolyMAC.valeur();
  const Champ_Inc_base& cc = equation().champ_conserve();
  const Conds_lim& cls = equation().zone_Cl_dis()->les_conditions_limites();
  const IntTab& fcl = ref_cast(Champ_Elem_PolyMAC, equation().inconnue().valeur()).fcl(), &f_e = zone.face_voisins();
  const DoubleTab& present = cc.valeurs(), &passe = cc.passe();
  const DoubleVect& ve = zone.volumes(), &pe = zone.porosite_elem(), &fs = zone.face_surfaces();
  int e, f, n, N = cc.valeurs().line_size(), ne = zone.nb_elem();
  /* second membre : avec ou sans resolution en increments*/
  for (e = 0; e < ne; e++)
    for (n = 0; n < N; n++)
      secmem(e, n) += pe(e) * ve(e) * (passe(e, n) - resoudre_en_increments * present(e, n)) / dt;
  /* si on n'a pas d'operateur de diffusion (operateur(0) negligeable ou operateur(0) convectif pour Masse_Multiphase), alors ajout des flux aux faces de Neumann */
  if ( (sub_type(Op_Diff_negligeable, equation().operateur(0).l_op_base())) || (!sub_type(Operateur_Diff_base, equation().operateur(0).l_op_base())) )
    for (f = 0; f < zone.premiere_face_int(); f++)
      if (fcl(f, 0) == 4)
        for (e = f_e(f, 0), n = 0; n < N; n++)
          secmem(e, n) += fs(f) * ref_cast(Neumann_paroi, cls[fcl(f, 1)].valeur()).flux_impose(fcl(f, 2), n);
  /* matrices */
  for (auto &&i_m : matrices)
    if (cc.derivees().count(i_m.first))
      {
        int m, M = equation().probleme().get_champ(i_m.first.c_str()).valeurs().line_size();
        const DoubleTab& der = cc.derivees().at(i_m.first);
        for (e = 0; e < ne; e++)
          for (n = 0, m = 0; n < N; n++, m += (M > 1))
            (*i_m.second)(N * e + n, M * e + m) += pe(e) * ve(e) * der(e, n) / dt;
      }
}
References Equation_base::champ_conserve(), Champ_Inc_base::derivees(), MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Probleme_base::get_champ(), la_zone_PolyMAC, Zone_Cl_dis::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem(), Champ_Inc_base::passe(), Zone_VF::porosite_elem(), Zone_VF::premiere_face_int(), Equation_base::probleme(), ref_cast, sub_type, Ref_Zone_PolyMAC::valeur(), valeur(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Zone_VF::volumes(), and Equation_base::zone_Cl_dis().
appliquer_impl()
DoubleTab & Masse_PolyMAC_Elem::appliquer_impl (DoubleTab & sm) const override virtual
Implements Solveur_Masse_base.
Definition at line 61 of file Masse_PolyMAC_Elem.cpp.
{
  const Zone_PolyMAC& zone = la_zone_PolyMAC.valeur();
  const DoubleVect& ve = zone.volumes(), &pe = zone.porosite_elem();
  const DoubleTab& der = equation().champ_conserve().derivees().at(equation().inconnue().le_nom().getString());
  int e, ne_tot = zone.nb_elem_tot(), n, N = sm.line_size();
  assert(sm.dimension_tot(0) >= ne_tot && N == der.line_size());
  /* partie elem */
  for (e = 0; e < ne_tot; e++)
    for (n = 0; n < N; n++)
      if (der(e, n) > 1e-10) sm(e, n) /= pe(e) * ve(e) * der(e, n);
      else sm(e, n) = 0; //cas d'une evanescence
  return sm;
}
References Equation_base::champ_conserve(), Champ_Inc_base::derivees(), TRUSTTab< _TYPE_ >::dimension_tot(), MorEqn::equation(), la_zone_PolyMAC, Objet_U::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem_tot(), Zone_VF::porosite_elem(), Ref_Zone_PolyMAC::valeur(), and Zone_VF::volumes().
associer_zone_cl_dis_base()
void Masse_PolyMAC_Elem::associer_zone_cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis_base) override virtual
Implements Solveur_Masse_base.
Definition at line 144 of file Masse_PolyMAC_Elem.cpp.
{
  la_zone_Cl_PolyMAC = ref_cast(Zone_Cl_PolyMAC, la_zone_Cl_dis_base);
}
References la_zone_Cl_PolyMAC, and ref_cast.
associer_zone_dis_base()
void Masse_PolyMAC_Elem::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) override virtual
Implements Solveur_Masse_base.
Definition at line 139 of file Masse_PolyMAC_Elem.cpp.
{
  la_zone_PolyMAC = ref_cast(Zone_PolyMAC, la_zone_dis_base);
}
References la_zone_PolyMAC, and ref_cast.
cree_instance()
Objet_U * Masse_PolyMAC_Elem::cree_instance () static
Definition at line 33 of file Masse_PolyMAC_Elem.cpp.
dimensionner_blocs()
void Masse_PolyMAC_Elem::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Solveur_Masse_base.
Definition at line 79 of file Masse_PolyMAC_Elem.cpp.
{
  equation().init_champ_conserve();
  /* une diagonale par derivee de champ_conserve_ presente dans matrices */
  const Zone_PolyMAC& zone = la_zone_PolyMAC.valeur();
  const Champ_Inc_base& cc = equation().champ_conserve();
  int e, ne = zone.nb_elem(), n, N = cc.valeurs().line_size();
  for (auto &&i_m : matrices)
    if (cc.derivees().count(i_m.first))
      {
        /* nombre de composantes de la variable : autant que le champ par defaut, mais peut etre different pour la pression */
        const DoubleTab& col = equation().probleme().get_champ(i_m.first.c_str()).valeurs(); //tableau de l'inconnue par rapport a laquelle on derive
        int m, M = col.line_size();
        IntTrav stencil(0, 2);
        stencil.set_smart_resize(1);
        for (e = 0; e < ne; e++)
          for (n = 0, m = 0; n < N; n++, m += (M > 1)) stencil.append_line(N * e + n, M * e + m);
        Matrice_Morse mat;
        Matrix_tools::allocate_morse_matrix(N * equation().inconnue().valeurs().dimension_tot(0), M * col.dimension_tot(0), stencil, mat);
        i_m.second->nb_colonnes() ? *i_m.second += mat : *i_m.second = mat;
      }
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), Equation_base::champ_conserve(), Champ_Inc_base::derivees(), TRUSTTab< _TYPE_ >::dimension_tot(), MorEqn::equation(), Probleme_base::get_champ(), Equation_base::init_champ_conserve(), la_zone_PolyMAC, TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem(), Equation_base::probleme(), TRUSTArray< _TYPE_ >::set_smart_resize(), Ref_Zone_PolyMAC::valeur(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
duplique()
int Masse_PolyMAC_Elem::duplique () const override virtual
Implements Objet_U.
Definition at line 33 of file Masse_PolyMAC_Elem.cpp.
get_info()
const Type_info * Masse_PolyMAC_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 33 of file Masse_PolyMAC_Elem.cpp.
has_interface_blocs()
int Masse_PolyMAC_Elem::has_interface_blocs () const inline override virtual
Reimplemented from Solveur_Masse_base.
Definition at line 44 of file Masse_PolyMAC_Elem.h.
  {
    return 1;
  };
info()
const Type_info * Masse_PolyMAC_Elem::info () static
Definition at line 33 of file Masse_PolyMAC_Elem.cpp.
preparer_calcul()
void Masse_PolyMAC_Elem::preparer_calcul (void) override virtual
Reimplemented from Solveur_Masse_base.
Definition at line 56 of file Masse_PolyMAC_Elem.cpp.
{
  equation().init_champ_conserve();
}
References MorEqn::equation(), and Equation_base::init_champ_conserve().
printOn()
Sortie & Masse_PolyMAC_Elem::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 39 of file Masse_PolyMAC_Elem.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Masse_PolyMAC_Elem::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 44 of file Masse_PolyMAC_Elem.cpp.
{
  return s ;
}
self_cast() [1/2]
const Masse_PolyMAC_Elem & Masse_PolyMAC_Elem::self_cast (const Objet_U & r) static
Definition at line 33 of file Masse_PolyMAC_Elem.cpp.
self_cast() [2/2]
Masse_PolyMAC_Elem & Masse_PolyMAC_Elem::self_cast (Objet_U & r) static
Definition at line 33 of file Masse_PolyMAC_Elem.cpp.
taille_memoire()
unsigned Masse_PolyMAC_Elem::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 33 of file Masse_PolyMAC_Elem.cpp.
Member Data Documentation
info_obj
const Type_info Masse_PolyMAC_Elem::info_obj static
Definition at line 33 of file Masse_PolyMAC_Elem.h.
la_zone_Cl_PolyMAC
Ref_Zone_Cl_PolyMAC Masse_PolyMAC_Elem::la_zone_Cl_PolyMAC private
Definition at line 54 of file Masse_PolyMAC_Elem.h.
Referenced by associer_zone_cl_dis_base().
la_zone_PolyMAC
Ref_Zone_PolyMAC Masse_PolyMAC_Elem::la_zone_PolyMAC private
Definition at line 53 of file Masse_PolyMAC_Elem.h.
Referenced by ajouter_blocs(), appliquer_impl(), associer_zone_dis_base(), and dimensionner_blocs().
The documentation for this class was generated from the following files:
src/PolyMAC/Solveurs/Masse_PolyMAC_Elem.h
src/PolyMAC/Solveurs/Masse_PolyMAC_Elem.cpp