TRUST: Cond_lim Class Reference
Cond_lim Class Reference
classe Cond_lim
Classe generique servant a representer n'importe quelle classe
derivee de la classe Cond_lim_base
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
#include <Cond_lim.h>
Public Member Functions
Cond_lim ()
~Cond_lim ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Cond_lim (const Cond_lim &)=default
Cond_lim & operator= (const Cond_lim_base &cl_base)
Operateur d'affectation d'un objet de type Cond_lim_base&
dans une objet de type Cond_lim& .
Cond_lim & operator= (const Cond_lim &cl)
Operateur d'affectation d'un objet de type Cond_lim&
dans une objet de type Cond_lim& .
void adopt (Cond_lim &cl)
Adopte la Cond_lim passee en parametre.
Il n'y a pas de copie.
La Cond_lim_base eventuellement detenue avant l'appel est detruite.
ATTENTION cl est nul ensuite.
Frontiere_dis_base & frontiere_dis ()
Appel a l'objet sous-jacent
Renvoie la frontiere discretisee associee a la condition aux limites.
const Frontiere_dis_base & frontiere_dis () const
Appel a l'objet sous-jacent
Renvoie la frontiere discretisee associee a la condition aux limites.
(version const)
int operator== (const Cond_lim &x) const
Operateur d'egalite logique (comparaison) entre 2
conditions aux limites.
void mettre_a_jour (double temps)
Appel a l'objet sous-jacent
Mise a jour en temps de la condition aux limites.
void calculer_coeffs_echange (double temps)
Appel a l'objet sous-jacent
Calcul des coeffs d'echange de la condition aux limites.
void completer ()
Appel a l'objet sous-jacent.
void injecter_dans_champ_inc (Champ_Inc &) const
Appel a l'objet sous-jacent.
permet a une condition aux limites de s'injecter dans le Champ_Inc
avec l'equation passee en paramtre.
int compatible_avec_eqn (const Equation_base &) const
Appel a l'objet sous-jacent.
Renvoie 1 si les conditions aux limites sont compatibles
avec l'equation passee en paramtre.
int compatible_avec_discr (const Discretisation_base &) const
Appel a l'objet sous-jacent.
Renvoie 1 si les conditions aux limites sont compatibles
avec la discretisation passee en paramtre.
void set_modifier_val_imp (int)
Appel a l'objet sous-jacent.
Positionnement du drapeau modifier_val_imp.
Public Member Functions inherited from Deriv_Cond_lim_base
~Deriv_Cond_lim_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Cond_lim_base ()
Deriv_Cond_lim_base (const Deriv_Cond_lim_base &)
const Cond_lim_base & valeur () const
Cond_lim_base & valeur ()
const Cond_lim_base * operator-> () const
Cond_lim_base * operator-> ()
const Deriv_Cond_lim_base & operator= (const Cond_lim_base &)
const Deriv_Cond_lim_base & operator= (const Deriv_Cond_lim_base &)
operator const Cond_lim_base & () const
operator Cond_lim_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Cond_lim & self_cast (Objet_U &)
static const Cond_lim & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Cond_lim_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Cond_lim_base & self_cast (Objet_U &)
static const Deriv_Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime seulement le nom de la condition aux limites.
Entree & readOn (Entree &) override
Lit la condition aux limites sur un flot d'entree.
Protected Member Functions inherited from Deriv_Cond_lim_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
classe Cond_lim
Classe generique servant a representer n'importe quelle classe
derivee de la classe Cond_lim_base
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
Definition at line 38 of file Cond_lim.h.
Constructor & Destructor Documentation
Cond_lim() [1/2]
Cond_lim::Cond_lim ()
Definition at line 19 of file Cond_lim.cpp.
~Cond_lim()
Cond_lim::~Cond_lim ()
Definition at line 19 of file Cond_lim.cpp.
Cond_lim() [2/2]
Cond_lim::Cond_lim (const Cond_lim &) default
Member Function Documentation
adopt()
void Cond_lim::adopt (Cond_lim & cl)
Adopte la Cond_lim passee en parametre.
Il n'y a pas de copie.
La Cond_lim_base eventuellement detenue avant l'appel est detruite.
ATTENTION cl est nul ensuite.
Definition at line 79 of file Cond_lim.cpp.
{
  detach();
  set_O_U_Ptr(&(cl.valeur()));
  cl.set_O_U_Ptr(NULL);
}
References Deriv_::detach(), Deriv_Cond_lim_base::set_O_U_Ptr(), and Deriv_Cond_lim_base::valeur().
calculer_coeffs_echange()
void Cond_lim::calculer_coeffs_echange (double temps) inline
Appel a l'objet sous-jacent
Calcul des coeffs d'echange de la condition aux limites.
Definition at line 208 of file Cond_lim.h.
{
  valeur().calculer_coeffs_echange(temps);
}
References Cond_lim_base::calculer_coeffs_echange(), and Deriv_Cond_lim_base::valeur().
compatible_avec_discr()
int Cond_lim::compatible_avec_discr (const Discretisation_base & dis) const inline
Appel a l'objet sous-jacent.
Renvoie 1 si les conditions aux limites sont compatibles
avec la discretisation passee en paramtre.
Returns
int
Signification: 1 si compatible 0 sinon
Contraintes:
Definition at line 292 of file Cond_lim.h.
{
  return valeur().compatible_avec_discr(dis);
}
References Cond_lim_base::compatible_avec_discr(), and Deriv_Cond_lim_base::valeur().
compatible_avec_eqn()
int Cond_lim::compatible_avec_eqn (const Equation_base & eqn) const inline
Appel a l'objet sous-jacent.
Renvoie 1 si les conditions aux limites sont compatibles
avec l'equation passee en paramtre.
Returns
int
Signification: 1 si compatible 0 sinon.
Contraintes:
Definition at line 270 of file Cond_lim.h.
{
  return valeur().compatible_avec_eqn(eqn);
}
References Cond_lim_base::compatible_avec_eqn(), and Deriv_Cond_lim_base::valeur().
completer()
void Cond_lim::completer () inline
Appel a l'objet sous-jacent.
Definition at line 228 of file Cond_lim.h.
{
  valeur().completer();
}
References Cond_lim_base::completer(), and Deriv_Cond_lim_base::valeur().
cree_instance()
Objet_U * Cond_lim::cree_instance () static
Definition at line 19 of file Cond_lim.cpp.
duplique()
int Cond_lim::duplique () const override virtual
Reimplemented from Deriv_Cond_lim_base.
Definition at line 19 of file Cond_lim.cpp.
frontiere_dis() [1/2]
Frontiere_dis_base & Cond_lim::frontiere_dis () inline
Appel a l'objet sous-jacent
Renvoie la frontiere discretisee associee a la condition aux limites.
Returns
Frontiere_dis_base&
Signification: la frontiere discretisee associee a la condition aux limites
Contraintes:
Definition at line 123 of file Cond_lim.h.
{
  return valeur().frontiere_dis();
}
References Cond_lim_base::frontiere_dis(), and Deriv_Cond_lim_base::valeur().
Referenced by Op_Grad_EF::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Source_Generique_VEF::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), ajouter_bord(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), T_It_VDF_Elem< _TYPE_ >::ajouter_bords(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_autre_pb(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_bords(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_bords_vitesse(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), T_It_VDF_Face< _TYPE_ >::ajouter_contribution_fa7_sortie_libre(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Grad_VEF_P1B_Face::ajouter_elem(), T_It_VDF_Face< _TYPE_ >::ajouter_fa7_sortie_libre(), T_It_Sou_VDF_Face< _TYPE_ >::ajouter_faces_bords(), Source_Fluide_Dilatable_VDF_Proto::ajouter_impl(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Solveur_Masse_EF::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), assemblerP0P1(), assemblerP0Pa(), assemblerP1P1(), assemblerP1Pa(), assemblerPaPa(), Op_Diff_VEFP1NCP1B_Face::associer(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Op_Dift_standard_VEF_Face::calcul_divergence(), Champ_P1NC::calcul_duidxj_paroi(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::calculer_data_pour_dirichlet(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), T_It_VDF_Elem< _TYPE_ >::calculer_flux_bord2(), Op_Conv_EF_VEF_P1NC_Stab::calculer_flux_bords(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), calculer_gradientP1NC(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Dift_Stab_VEF_Face::calculer_min(), Operateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Traitement_particulier_NS_Brech_VEF::calculer_terme_destruction_K(), Traitement_particulier_NS_Brech_VEF::calculer_terme_production_K(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Terme_Source_Canal_perio::completer(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Terme_Source_Canal_perio::compute_heat_flux(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Champ_front_fonc_gradient::condition_limite(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), T_It_VDF_Elem< _TYPE_ >::contribuer_au_second_membre_bords(), T_It_VDF_Face< _TYPE_ >::contribuer_au_second_membre_fa7_sortie_libre(), Source_WC_Chaleur::correct_grad_boundary(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Zone_VDF::creer_elements_fictifs(), Op_VDF_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Champ_Generique_Tparoi_VEF::get_champ(), Turbulence_paroi_base::get_champ(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), Op_Div_PolyMAC::impr(), Op_Div_PolyMAC_P0::impr(), T_It_VDF_Elem< _TYPE_ >::impr(), T_It_VDF_Face< _TYPE_ >::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEF_Elem::impr(), Sonde::init_bords(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Op_Diff_VEFP1NCP1B_Face::liste_face(), message_erreur_conc(), message_erreur_fraction_massique(), message_erreur_therm(), Sonde::mettre_a_jour_bords(), Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite(), Op_Conv_EF_VEF_P1NC_Stab::mettre_a_jour_pour_periodicite(), modif_matrice_pour_periodique_apres_contribuer(), modif_matrice_pour_periodique_avant_contribuer(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_EF_base::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), okface(), Op_Conv_EF_VEF_P1NC_Stab::reinit_conv_pour_Cl(), Assembleur_P_VEF::remplir(), Op_Conv_VEF_Face::remplir_fluent(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), remplir_marqueur_sommet_neumann(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Op_Diff_VEFP1NCP1B_Face::test(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), updateP0P1(), updateP0Pa(), updateP1P1(), updateP1Pa(), updatePaPa(), and Assembleur_P_VEFPreP1B::verifier_dirichlet().
frontiere_dis() [2/2]
const Frontiere_dis_base & Cond_lim::frontiere_dis () const inline
Appel a l'objet sous-jacent
Renvoie la frontiere discretisee associee a la condition aux limites.
(version const)
Returns
Frontiere_dis_base&
Signification: la frontiere discretisee associee a la condition aux limites
Contraintes: reference constante
Definition at line 145 of file Cond_lim.h.
{
  return valeur().frontiere_dis();
}
References Cond_lim_base::frontiere_dis(), and Deriv_Cond_lim_base::valeur().
get_info()
const Type_info * Cond_lim::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Cond_lim_base.
Definition at line 19 of file Cond_lim.cpp.
info()
const Type_info * Cond_lim::info () static
Definition at line 19 of file Cond_lim.cpp.
injecter_dans_champ_inc()
void Cond_lim::injecter_dans_champ_inc (Champ_Inc & ch) const inline
Appel a l'objet sous-jacent.
permet a une condition aux limites de s'injecter dans le Champ_Inc
avec l'equation passee en paramtre.
Definition at line 249 of file Cond_lim.h.
{
  valeur().injecter_dans_champ_inc(ch);
}
References Cond_lim_base::injecter_dans_champ_inc(), and Deriv_Cond_lim_base::valeur().
mettre_a_jour()
void Cond_lim::mettre_a_jour (double temps) inline
Appel a l'objet sous-jacent
Mise a jour en temps de la condition aux limites.
Definition at line 187 of file Cond_lim.h.
{
  valeur().mettre_a_jour(temps);
}
References Cond_lim_base::mettre_a_jour(), and Deriv_Cond_lim_base::valeur().
operator=() [1/2]
Cond_lim & Cond_lim::operator= (const Cond_lim & cl) inline
Operateur d'affectation d'un objet de type Cond_lim&
dans une objet de type Cond_lim& .
Returns
Cond_lim&
Signification: renvoie (*this)
Contraintes:
Definition at line 101 of file Cond_lim.h.
{
  DERIV(Cond_lim_base)::operator=(cl.valeur());
  return *this;
}
References DERIV, operator=(), and Deriv_Cond_lim_base::valeur().
operator=() [2/2]
Cond_lim & Cond_lim::operator= (const Cond_lim_base & cl_base) inline
Operateur d'affectation d'un objet de type Cond_lim_base&
dans une objet de type Cond_lim& .
Returns
Cond_lim&
Signification: renvoie (*this)
Contraintes:
Definition at line 80 of file Cond_lim.h.
{
  DERIV(Cond_lim_base)::operator=(cl_base);
  return *this;
}
References DERIV, and operator=().
Referenced by operator=().
operator==()
int Cond_lim::operator== (const Cond_lim & x) const inline
Operateur d'egalite logique (comparaison) entre 2
conditions aux limites.
Returns
int
Signification: 1 si l'objet est egal a l'objet condition aux limites
passe en parametre 0 sinon.
Contraintes:
Definition at line 166 of file Cond_lim.h.
{
  return (DERIV(Cond_lim_base)&) x == (DERIV(Cond_lim_base)&) *this ;
}
References DERIV.
printOn()
Sortie & Cond_lim::printOn (Sortie & s) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime seulement le nom de la condition aux limites.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Cond_lim_base.
Definition at line 37 of file Cond_lim.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References O_U_Ptr::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Cond_lim::readOn (Entree & s) override protected virtual
Lit la condition aux limites sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Cond_lim_base.
Definition at line 57 of file Cond_lim.cpp.
{
  return DERIV(Cond_lim_base)::readOn(s) ;
}
References DERIV, and readOn().
Referenced by readOn().
self_cast() [1/2]
const Cond_lim & Cond_lim::self_cast (const Objet_U & r) static
Definition at line 19 of file Cond_lim.cpp.
self_cast() [2/2]
Cond_lim & Cond_lim::self_cast (Objet_U & r) static
Definition at line 19 of file Cond_lim.cpp.
set_modifier_val_imp()
void Cond_lim::set_modifier_val_imp (int drap) inline
Appel a l'objet sous-jacent.
Positionnement du drapeau modifier_val_imp.
Definition at line 312 of file Cond_lim.h.
{
  valeur().set_modifier_val_imp(drap);
}
References Cond_lim_base::set_modifier_val_imp(), and Deriv_Cond_lim_base::valeur().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Convection_Diffusion_Espece_Binaire_base::preparer_calcul(), Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul(), and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee().
taille_memoire()
unsigned Cond_lim::taille_memoire () const override virtual
Reimplemented from Deriv_Cond_lim_base.
Definition at line 19 of file Cond_lim.cpp.
Member Data Documentation
info_obj
const Type_info Cond_lim::info_obj static
Definition at line 41 of file Cond_lim.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Cond_lim.h
src/Kernel/Framework/Cond_lim.cpp