TRUST: Champ_front_bruite Class Reference
Champ_front_bruite Class Reference
classe Champ_front_bruite
Classe derivee de Champ_front_base qui represente les
champs aux frontieres bruites : ch(*,i)=m(i)+alea*amplitude(i)
ou alea est une variable aleatoire de loi uniforme sur [0,1]
#include <Champ_front_bruite.h>
Public Member Functions
Champ_front_bruite ()
~Champ_front_bruite ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Champ_front_base & affecter_ (const Champ_front_base &ch)
Pas code !!
virtual void mettre_a_jour (double temps)
Mise a jour du temps
et retirage aleatoire des valeurs du bruit.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_front_bruite & self_cast (Objet_U &)
static const Champ_front_bruite & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Impression sur un flot de sortie au format:
taille
valeur(0) ... valeur(i) ... valeur(taille-1)
virtual Entree & readOn (Entree &)
Lecture a partir d'un flot d'entree au format:
nombre_de_composantes
moyenne moyenne(0) ... moyenne(nombre_de_composantes-1)
moyenne amplitude(0) ... amplitude(nombre_de_composantes-1)
Protected Attributes
int nx
double lx
DoubleVect amplitude
DoubleVect moyenne
Detailed Description
classe Champ_front_bruite
Classe derivee de Champ_front_base qui represente les
champs aux frontieres bruites : ch(*,i)=m(i)+alea*amplitude(i)
ou alea est une variable aleatoire de loi uniforme sur [0,1]
Definition at line 41 of file Champ_front_bruite.h.
Constructor & Destructor Documentation
Champ_front_bruite::Champ_front_bruite ()
Definition at line 27 of file Champ_front_bruite.cpp.
Champ_front_bruite::~Champ_front_bruite ()
Definition at line 27 of file Champ_front_bruite.cpp.
Member Function Documentation
Champ_front_base & Champ_front_bruite::affecter_ (const Champ_front_base & ch) [virtual]
Pas code !!
Returns:
Champ_front_base&
Signification:
Contraintes:
Implements Champ_front_base.
Definition at line 151 of file Champ_front_bruite.cpp.
{
  return *this;
}
Objet_U * Champ_front_bruite::cree_instance () [static]
Definition at line 27 of file Champ_front_bruite.cpp.
int Champ_front_bruite::duplique () const [virtual]
Implements Ch_front_var_instationnaire_indep.
Definition at line 27 of file Champ_front_bruite.cpp.
const Type_info * Champ_front_bruite::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 27 of file Champ_front_bruite.cpp.
const Type_info * Champ_front_bruite::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 27 of file Champ_front_bruite.cpp.
void Champ_front_bruite::mettre_a_jour (double temps) [virtual]
Mise a jour du temps
et retirage aleatoire des valeurs du bruit.
Reimplemented from Champ_front_base.
Definition at line 171 of file Champ_front_bruite.cpp.
References amplitude, DoubleVect::echange_espace_virtuel(), Champ_front_base::la_frontiere_dis, lx, moyenne, Field_base::nb_comp(), Frontiere::nb_faces(), nx, and Champ_front_var_instationnaire::valeurs_au_temps().
{
  const Frontiere& front=la_frontiere_dis->frontiere();
  int nb_faces=front.nb_faces();
  DoubleTab& tab=valeurs_au_temps(temps);
  if (nx!=0)
    {
//
// N!=0 modelisation du bruit blanc (R. Howard)
//
      double onde, bruit_blanc, pi, invx, d_x, tot_vel;
      pi=2.*acos(0.);
      invx=1./nx;
      d_x=lx/nx;
      for(int i=0; i<nb_faces; i++)
        for(int j=0; j<nb_comp(); j++)
          {
            tot_vel=moyenne(j)+amplitude(j);
            onde=0.;
            for (int in_x=0; in_x<nx; in_x++)
              onde=onde+sin((2.*pi*temps/(4*d_x+in_x*d_x)+(10.2*i+5.3*j))*tot_vel+5.6*pi);
            bruit_blanc=onde*invx;
            tab(i,j)=moyenne(j)+2.*amplitude(j)*bruit_blanc;
          }
    }
  else
//
// N=0 donc modelisation bruit aleatoire
//
    for(int i=0; i<nb_faces; i++)
      for(int j=0; j<nb_comp(); j++)
        {
          tab(i,j)=moyenne(j)+amplitude(j)*(-1.+2.*drand48());
        }
  tab.echange_espace_virtuel();
}
Sortie & Champ_front_bruite::printOn (Sortie & os) const [protected, virtual]
Impression sur un flot de sortie au format:
taille
valeur(0) ... valeur(i) ... valeur(taille-1)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 45 of file Champ_front_bruite.cpp.
References DoubleVect::size(), and Champ_front_base::valeurs().
{
  const DoubleTab& tab=valeurs();
  os << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    os << tab(0,i);
  return os;
}
Entree & Champ_front_bruite::readOn (Entree & is) [protected, virtual]
Lecture a partir d'un flot d'entree au format:
nombre_de_composantes
moyenne moyenne(0) ... moyenne(nombre_de_composantes-1)
moyenne amplitude(0) ... amplitude(nombre_de_composantes-1)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 73 of file Champ_front_bruite.cpp.
References amplitude, Cerr, Process::exit(), finl, Field_base::fixer_nb_comp(), Champ_Proto::lire_dimension(), lx, moyenne, nx, Objet_U::que_suis_je(), DoubleVect::resize(), and Motcles::search().
{
  nx=0;
  lx=0.;
  int dim;
  dim=lire_dimension(is,que_suis_je());
  Motcle motlu;
  Motcles les_mots(4);
  les_mots[0]="moyenne";
  les_mots[1]="amplitude";
  les_mots[2]="L";
  les_mots[3]="N";
  is >> motlu;
  if (motlu != "{")
    {
      Cerr << "Error while reading a Champ_front_bruite" << finl;
      Cerr << "We expected a { instead of " << motlu << finl;
      exit();
    }
  is >> motlu;
  while (motlu!="}")
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          {
            moyenne.resize(dim);
            fixer_nb_comp(dim);
            for(int i=0; i<dim; i++)
              is >> moyenne(i);
            break;
          }
        case 1:
          {
            amplitude.resize(dim);
            for(int i=0; i<dim; i++)
              is >> amplitude(i);
            break;
          }
        case 2:
          {
            is >> lx;
            break;
          }
        case 3:
          {
            is >> nx;
            break;
          }
        default :
          {
            Cerr << "Error while reading a Champ_front_bruite" << finl;
            Cerr << motlu << "is not understand here "<< finl;
            Cerr << "We were expecting a word from " << les_mots << finl;
            exit();
          }
        }
      is >> motlu;
    }
  return is;
}
Champ_front_bruite & Champ_front_bruite::self_cast (Objet_U & r) [static]
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 27 of file Champ_front_bruite.cpp.
const Champ_front_bruite & Champ_front_bruite::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 27 of file Champ_front_bruite.cpp.
unsigned Champ_front_bruite::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 27 of file Champ_front_bruite.cpp.
Member Data Documentation
DoubleVect Champ_front_bruite::amplitude [protected]
Definition at line 53 of file Champ_front_bruite.h.
Referenced by mettre_a_jour(), and readOn().
const Type_info Champ_front_bruite::info_obj [static]
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 43 of file Champ_front_bruite.h.
double Champ_front_bruite::lx [protected]
Definition at line 52 of file Champ_front_bruite.h.
Referenced by mettre_a_jour(), and readOn().
DoubleVect Champ_front_bruite::moyenne [protected]
Definition at line 54 of file Champ_front_bruite.h.
Referenced by mettre_a_jour(), and readOn().
int Champ_front_bruite::nx [protected]
Definition at line 51 of file Champ_front_bruite.h.
Referenced by mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_front_bruite.h
src/Kernel/Champs/Champ_front_bruite.cpp