TRUST: Op_Diff_Turbulent_PolyMAC_P0_Face Class Reference
Op_Diff_Turbulent_PolyMAC_P0_Face Class Reference
: class Op_Diff_Turbulent_PolyMAC_P0_Face
Operateur de diffusion de vitesse prenant en compte l'effet de la turbulence
par le biais d'une correlation de type Viscosite_turbulente_base.
#include <Op_Diff_Turbulent_PolyMAC_P0_Face.h>
Public Member Functions
Op_Diff_Turbulent_PolyMAC_P0_Face ()
~Op_Diff_Turbulent_PolyMAC_P0_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void creer_champ (const Motcle &motlu) override
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
void modifier_nu (DoubleTab &) const override
const Correlation & correlation () const
Public Member Functions inherited from Op_Diff_PolyMAC_P0_Face
Op_Diff_PolyMAC_P0_Face ()
~Op_Diff_PolyMAC_P0_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
int has_interface_blocs () const override
double calculer_dt_stab () const override
Calcul dt_stab.
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
void check_multiphase_compatibility () const override
Public Member Functions inherited from Op_Diff_PolyMAC_P0_base
Op_Diff_PolyMAC_P0_base ()
~Op_Diff_PolyMAC_P0_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void associer_diffusivite (const Champ_base &) override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
const Champ_base & diffusivite () const override
void mettre_a_jour (double t) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual int dimension_min_nu () const
virtual void modifier_nu (DoubleTab &) const
const DoubleTab & nu () const
void update_phif (int full_stencil=0) const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
calcule la contribution de la diffusion, la range dans resu
renvoie resu
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Diff_Turbulent_PolyMAC_P0_Face & self_cast (Objet_U &)
static const Op_Diff_Turbulent_PolyMAC_P0_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_PolyMAC_P0_Face
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Diff_PolyMAC_P0_Face & self_cast (Objet_U &)
static const Op_Diff_PolyMAC_P0_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_PolyMAC_P0_base
static const Type_info * info ()
static Op_Diff_PolyMAC_P0_base & self_cast (Objet_U &)
static const Op_Diff_PolyMAC_P0_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_PolyMAC_P0_Face
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_PolyMAC_P0_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Diff_PolyMAC_P0_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
void update_nu () const
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
Correlation corr
std::vector< Champ_Fonc > nu_t_post_
Motcles noms_nu_t_post_
Protected Attributes inherited from Op_Diff_PolyMAC_P0_Face
DoubleVect porosite_e
DoubleVect porosite_f
Protected Attributes inherited from Op_Diff_PolyMAC_P0_base
Ref_Zone_PolyMAC_P0 la_zone_poly_
Ref_Zone_Cl_PolyMAC la_zcl_poly_
Ref_Champ_base diffusivite_
double t_last_maj_ = -1e10
DoubleTab nu_
IntTab som_ext
int nu_constant_ = 0
int nu_a_jour_ = 0
int s_dist_init_ = 0
int som_ext_init_ = 0
int phif_a_jour_ = 0
SFichier Flux
SFichier Flux_moment
SFichier Flux_sum
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Op_Diff_PolyMAC_P0_base
IntTab pe_ext
tableau aux faces de bord : (indice dans op_ext, indice d'element) pour les faces de type Echange_contact
IntTab phif_d
IntTab phif_e
DoubleTab phif_c
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
: class Op_Diff_Turbulent_PolyMAC_P0_Face
Operateur de diffusion de vitesse prenant en compte l'effet de la turbulence
par le biais d'une correlation de type Viscosite_turbulente_base.
Definition at line 34 of file Op_Diff_Turbulent_PolyMAC_P0_Face.h.
Constructor & Destructor Documentation
Op_Diff_Turbulent_PolyMAC_P0_Face()
Op_Diff_Turbulent_PolyMAC_P0_Face::Op_Diff_Turbulent_PolyMAC_P0_Face ()
Definition at line 25 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
~Op_Diff_Turbulent_PolyMAC_P0_Face()
Op_Diff_Turbulent_PolyMAC_P0_Face::~Op_Diff_Turbulent_PolyMAC_P0_Face ()
Definition at line 25 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
Member Function Documentation
completer()
void Op_Diff_Turbulent_PolyMAC_P0_Face::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< cas flica5 : ce n'est pas l'inconnue qui est utilisee, donc on cree les variables auxiliaires ici
< pour ajout _Mx (moment)
Reimplemented from Op_Diff_PolyMAC_P0_Face.
Definition at line 49 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
{
  Op_Diff_PolyMAC_P0_Face::completer();
// si la correlation a besoin du gradient de u, on doit le creer maintenant
  if (corr.non_nul() && ref_cast(Viscosite_turbulente_base, corr.valeur()).gradu_required())
    equation().probleme().creer_champ("gradient_vitesse");
}
References Op_Diff_PolyMAC_P0_Face::completer(), corr, Probleme_base::creer_champ(), MorEqn::equation(), O_U_Ptr::non_nul(), Equation_base::probleme(), ref_cast, and Deriv_Correlation_base::valeur().
correlation()
const Correlation & Op_Diff_Turbulent_PolyMAC_P0_Face::correlation () const inline
Definition at line 43 of file Op_Diff_Turbulent_PolyMAC_P0_Face.h.
{ return corr ;};
References corr.
cree_instance()
Objet_U * Op_Diff_Turbulent_PolyMAC_P0_Face::cree_instance () static
Definition at line 25 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
creer_champ()
void Op_Diff_Turbulent_PolyMAC_P0_Face::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Operateur_base.
Definition at line 57 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
{
  Op_Diff_PolyMAC_P0_Face::creer_champ(motlu);
  int i = noms_nu_t_post_.rang(motlu);
  if (i >= 0 && !(nu_t_post_[i].non_nul()))
    {
      const PolyMAC_P0_discretisation dis = ref_cast(PolyMAC_P0_discretisation, equation().discretisation());
      Noms noms(1), unites(1);
      noms[0] = noms_nu_t_post_[i];
      Motcle typeChamp = "champ_elem" ;
      dis.discretiser_champ(typeChamp, equation().zone_dis(), scalaire, noms , unites, 1, 0, nu_t_post_[0]);
      champs_compris_.ajoute_champ(nu_t_post_[i]);
    }
}
References Champs_compris::ajoute_champ(), Operateur_base::champs_compris_, Operateur_base::creer_champ(), PolyMAC_discretisation::discretiser_champ(), MorEqn::equation(), noms_nu_t_post_, nu_t_post_, Motcles::rang(), ref_cast, and scalaire.
duplique()
int Op_Diff_Turbulent_PolyMAC_P0_Face::duplique () const override virtual
Reimplemented from Op_Diff_PolyMAC_P0_Face.
Definition at line 25 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
get_info()
const Type_info * Op_Diff_Turbulent_PolyMAC_P0_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_PolyMAC_P0_Face.
Definition at line 25 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
info()
const Type_info * Op_Diff_Turbulent_PolyMAC_P0_Face::info () static
Definition at line 25 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
mettre_a_jour()
void Op_Diff_Turbulent_PolyMAC_P0_Face::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
Reimplemented from Op_Diff_PolyMAC_P0_base.
Definition at line 72 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
{
  Op_Diff_PolyMAC_P0_Face::mettre_a_jour(temps);
  int N = ref_cast(Pb_Multiphase, equation().probleme()).nb_phases();
  for (int n = 0; n < N; n++)
    if (nu_t_post_[n].non_nul()) //viscosite turbulente : toujours scalaire
      {
        const DoubleTab& rho = equation().milieu().masse_volumique().passe() ;
        DoubleTab& val = nu_t_post_[n]->valeurs();
        int nl = val.dimension(0);
        int cR = (rho.dimension(0) == 1);
        DoubleTrav nu_t(nl, N);
        ref_cast(Viscosite_turbulente_base, corr.valeur()).eddy_viscosity(nu_t); //remplissage par la correlation
        for (int i = 0; i < nl; i++) val(i, 0) = rho(!cR * i, n) * nu_t(i, n);
      }
}
References corr, TRUSTTab< _TYPE_ >::dimension(), MorEqn::equation(), Milieu_base::masse_volumique(), Op_Diff_PolyMAC_P0_base::mettre_a_jour(), Equation_base::milieu(), nu_t_post_, Champ_Proto::passe(), ref_cast, and Deriv_Correlation_base::valeur().
modifier_nu()
void Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_nu (DoubleTab & mu) const override virtual
Reimplemented from Op_Diff_PolyMAC_P0_base.
Definition at line 90 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
{
  if (!corr.non_nul()) return; //rien a faire
  const DoubleTab& rho = equation().milieu().masse_volumique().passe(),
                   *alpha = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL;
  int i, nl = mu.dimension(0), n, N = equation().inconnue().valeurs().line_size(), cR = rho.dimension(0) == 1, d, D = dimension;
  DoubleTrav nu_t(nl, N); //viscosite turbulente : toujours scalaire
  ref_cast(Viscosite_turbulente_base, corr.valeur()).eddy_viscosity(nu_t); //remplissage par la correlation
  if (mu.nb_dim() == 2) //nu scalaire
    for (i = 0; i < nl; i++)
      for (n = 0; n < N; n++) mu(i, n) += (alpha ? (*alpha)(i, n) : 1) * rho(!cR * i, n) * nu_t(i, n);
  else if (mu.nb_dim() == 3) //nu anisotrope diagonal
    for (i = 0; i < nl; i++)
      for (n = 0; n < N; n++)
        for (d = 0; d < D; d++) mu(i, n, d) += (alpha ? (*alpha)(i, n) : 1) * rho(!cR * i, n) * nu_t(i, n);
  else if (mu.nb_dim() == 4) //nu anisotrope complet
    for (i = 0; i < nl; i++)
      for (n = 0; n < N; n++)
        for (d = 0; d < D; d++) mu(i, n, d, d) += (alpha ? (*alpha)(i, n) : 1) * rho(!cR * i, n) * nu_t(i, n);
  else abort();
  mu.echange_espace_virtuel();
}
References Process::abort(), corr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), Equation_base::inconnue(), TRUSTVect< _TYPE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), TRUSTTab< _TYPE_ >::nb_dim(), O_U_Ptr::non_nul(), Champ_Proto::passe(), ref_cast, sub_type, Deriv_Correlation_base::valeur(), and Champ_Inc::valeurs().
printOn()
Sortie & Op_Diff_Turbulent_PolyMAC_P0_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_PolyMAC_P0_Face.
Definition at line 27 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
{
  Op_Diff_PolyMAC_P0_base::printOn( os );
  return os;
}
References Op_Diff_PolyMAC_P0_base::printOn().
readOn()
Entree & Op_Diff_Turbulent_PolyMAC_P0_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_PolyMAC_P0_Face.
Definition at line 34 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
{
// lecture de la correlation de viscosite turbulente
  corr.typer_lire(equation().probleme(), "viscosite_turbulente", is);
  const Pb_Multiphase& pb = ref_cast(Pb_Multiphase, equation().probleme());
  noms_nu_t_post_.dimensionner(pb.nb_phases()), nu_t_post_.resize(pb.nb_phases());
  for (int i = 0; i < pb.nb_phases(); i++)
    {
      champs_compris_.ajoute_nom_compris(noms_nu_t_post_[i] = Nom("viscosite_turbulente_") + pb.nom_phase(i));
    }
  return is;
}
References Champs_compris::ajoute_nom_compris(), Operateur_base::champs_compris_, corr, vect_impl::dimensionner(), MorEqn::equation(), Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), noms_nu_t_post_, nu_t_post_, ref_cast, and Correlation::typer_lire().
self_cast() [1/2]
const Op_Diff_Turbulent_PolyMAC_P0_Face & Op_Diff_Turbulent_PolyMAC_P0_Face::self_cast (const Objet_U & r) static
Definition at line 25 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
self_cast() [2/2]
Op_Diff_Turbulent_PolyMAC_P0_Face & Op_Diff_Turbulent_PolyMAC_P0_Face::self_cast (Objet_U & r) static
Definition at line 25 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
taille_memoire()
unsigned Op_Diff_Turbulent_PolyMAC_P0_Face::taille_memoire () const override virtual
Reimplemented from Op_Diff_PolyMAC_P0_Face.
Definition at line 25 of file Op_Diff_Turbulent_PolyMAC_P0_Face.cpp.
Member Data Documentation
corr
Correlation Op_Diff_Turbulent_PolyMAC_P0_Face::corr protected
Definition at line 46 of file Op_Diff_Turbulent_PolyMAC_P0_Face.h.
Referenced by completer(), correlation(), mettre_a_jour(), modifier_nu(), and readOn().
info_obj
const Type_info Op_Diff_Turbulent_PolyMAC_P0_Face::info_obj static
Definition at line 36 of file Op_Diff_Turbulent_PolyMAC_P0_Face.h.
noms_nu_t_post_
Motcles Op_Diff_Turbulent_PolyMAC_P0_Face::noms_nu_t_post_ protected
Definition at line 49 of file Op_Diff_Turbulent_PolyMAC_P0_Face.h.
Referenced by creer_champ(), and readOn().
nu_t_post_
std::vector<Champ_Fonc> Op_Diff_Turbulent_PolyMAC_P0_Face::nu_t_post_ protected
Definition at line 48 of file Op_Diff_Turbulent_PolyMAC_P0_Face.h.
Referenced by creer_champ(), mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Op_Diff_Turbulent_PolyMAC_P0_Face.h
src/PolyMAC/Operateurs/Op_Diff_Turbulent_PolyMAC_P0_Face.cpp