TRUST: Matrice_Morse_Diag Class Reference
Matrice_Morse_Diag Class Reference
Classe Matrice_Morse_Diag
Represente une matrice M (creuse) symetrique stockee au format Morse
Diagetrique: on ne stocke que la partie triangulaire superieure de la
matrice. Important: Tous les coefficients diagonaux doivent etre stockes
meme s'ils sont nuls (hypothese TRUST pour plusieurs methodes dont multvect).
Cette classe derive de Matrice_Morse_Sym.
#include <Matrice_Morse_Diag.h>
Public Member Functions
~Matrice_Morse_Diag ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Matrice_Morse_Diag ()
void dimensionne_diag (int n)
DoubleVect & ajouter_multvect_ (const DoubleVect &x, DoubleVect &y) const override
provoquue une erreur le but de cette matrice est juste de calculer la diagonale
DoubleVect & ajouter_multvectT_ (const DoubleVect &, DoubleVect &) const override
provoquue une erreur le but de cette matrice est juste de calculer la diagonale
DoubleTab & ajouter_multTab_ (const DoubleTab &, DoubleTab &) const override
provoquue une erreur le but de cette matrice est juste de calculer la diagonale
Public Member Functions inherited from Matrice_Morse_Sym
~Matrice_Morse_Sym ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Matrice_Morse_Sym (int n1=1, int n2=1)
Matrice_Morse_Sym (int, int, const IntLists &, const DoubleLists &, const DoubleVect &)
Constructeur d'une Matrice_Morse_Sym comportant
n1 lignes et pouvant stocker n2 elements non-nuls (au maximum).
Les elements de la matrice et la table des connectivites
sont donnes dans les 3 derniers parametres.
Matrice_Morse_Sym (const Matrice &)
Matrice_Morse_Sym (const Matrice_Morse &)
Constructeur d'une Matrice_Morse_Sym par copie
d'une Matrice_Morse.
Matrice_Morse_Sym (const Matrice_Morse_Sym &)
Constructeur d'une Matrice_Morse_Sym par copie
d'une Matrice_Morse.
Matrice_Morse_Sym & operator= (const Matrice_Morse_Sym &)
Operateur d'affectatiob d'une Matrice_Morse_Sym
dans une Matrice_Morse_Sym.
Matrice_Morse_Sym & operator= (const Matrice_Morse &)
Matrice_Morse_Sym & operator= (const Matrice &)
Matrice_Morse_Sym & operator*= (double)
NE FAIT RIEN : NON CODE.
void scale (const double x) override
void get_stencil (IntTab &stencil) const override
void get_symmetric_stencil (IntTab &stencil) const override
void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const override
void get_symmetric_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const override
Matrice_Morse_Sym operator- () const
Operateur de negation unaire,
renvoie l'opposee de la matrice: - A.
Appelle operator*(const Matrice_Morse_Sym&,double)
DoubleTab & ajouter_multTab_ (const DoubleTab &, DoubleTab &) const override
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice represente par un tableau)
Operation: RESU = RESU + A*X.
DoubleVect & ajouter_multvect_ (const DoubleVect &, DoubleVect &) const override
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: resu = resu + A*x.
DoubleVect & ajouter_multvectT_ (const DoubleVect &, DoubleVect &) const override
Operation de multiplication-accumulation (saxpy) matrice vecteur,
par la matrice transposee.
Operation: resu = resu + A^{T}*x.
virtual double multvect_et_prodscal (const DoubleVect &, DoubleVect &) const
int inverse (const DoubleVect &, DoubleVect &, double) const override
Calcule la solution du systeme lineaire: A * solution = secmem.
La methode utilisee est GMRES preconditionnee avec ILUT.
ATTENTION: cette methode n'a vraisemblablement jamais ete testee en parallele.
int inverse (const DoubleVect &, DoubleVect &, double, int) const override
Sortie & imprimer_formatte (Sortie &s) const override
void compacte (int elim_coeff_nul=0)
Suppression des doublons
on ordonne tab2;
Verification de la diagonale: tous ses elements doivent etre stockes.
void renumerote () const
Creation d'une matrice renumerotee pour reduire la largeur de bande.
Matrice & matrice_renumerotee ()
Renvoie la matrice renumerotee.
Matrice & matrice_renumerotee () const
Renvoie la matrice renumerotee.
ArrOfInt & permutation ()
ArrOfInt & permutation_inverse ()
ArrOfInt & permutation () const
ArrOfInt & permutation_inverse () const
bool check_symmetric_morse_matrix_structure (void) const
bool check_sorted_symmetric_morse_matrix_structure (void) const
void assert_check_symmetric_morse_matrix_structure (void) const
void assert_check_sorted_symmetric_morse_matrix_structure (void) const
Public Member Functions inherited from Matrice_Morse
~Matrice_Morse ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Matrice_Morse ()
Matrice_Morse (int n, int nnz)
Constructeur d'une matrice Morse carree d'ordre n
et pouvant stocker au maximum nnz elements non nuls.
Egalement constructeur par defaut car les 2 parametres
ont une valeur par defaut.
Matrice_Morse (int n, int m, int nnz)
Constructeur d'une matrice Morse avec n lignes et m colonnes
pouvant stocker au maximum nnz elements non nuls.
Matrice_Morse (const Matrice_Morse &)
Constructeur par copie d'une Matrice_Morse.
Copie de chaque membre donne du paramtre.
Matrice_Morse (int, int, const IntLists &, const DoubleLists &, const DoubleVect &)
Sortie & imprimer (Sortie &s) const override
Sortie & imprimer_formatte (Sortie &s) const override
Sortie & imprimer_formatte (Sortie &s, int symetrie) const
Sortie & imprimer_image (Sortie &s) const
Sortie & imprimer_image (Sortie &s, int symetrie) const
int largeur_de_bande () const
Retourne la largeur de bande.
void remplir (const IntLists &, const DoubleLists &, const DoubleVect &)
void remplir (const IntLists &, const DoubleLists &)
void remplir (const int, const int, const int, const int, const Matrice_Morse &)
Remplissage d'une matrice morse par une matrice morse plus petite.
void dimensionner (int n, int nnz)
Size the matrix with n lines and n columns and nnz zero-values coefficients.
void dimensionner (int n, int m, int nnz)
Size the matrix with n lines, m columns with nnz zero-values coefficients.
void dimensionner (const IntTab &)
int ordre () const override
Renvoie l'ordre de la matrice:
- le nombre de lignes si la matrice est carree
- 0 sinon.
int nb_lignes () const override
nb_lignes retourne n
int nb_colonnes () const override
nb_colonnes retourne m
int nb_coeff () const
nb_coeff retourne nnz
void set_nb_columns (const int)
void set_symmetric (const int)
int get_symmetric () const
IntVect & get_set_tab1 (void)
IntVect & get_set_tab2 (void)
DoubleVect & get_set_coeff (void)
const IntVect & get_tab1 (void) const
const IntVect & get_tab2 (void) const
const DoubleVect & get_coeff (void) const
int nb_vois (int i) const
void clean ()
Remplit la matrice avec des zeros.
double & operator() (int i, int j)
double operator() (int i, int j) const
double coef (int i, int j) const
double & coef (int i, int j)
Matrice_Morse & operator= (const Matrice_Morse &)
Operateur d'affectation d'une Matrice_Morse dans une
autre Matrice_Morse.
Matrice_Morse & operator+= (const Matrice_Morse &)
NE FAIT RIEN.
Matrice_Morse & operator*= (double)
Operateur de multiplication (de tous les elements)
d'une matrice par un scalaire.
Operation: A = x * A.
void scale (const double x) override
void get_stencil (IntTab &stencil) const override
void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const override
Matrice_Morse & operator/= (double)
Operateur de division (de tous les elements)
d'une matrice par un scalaire.
Operation: A = A / x.
Matrice_Morse & operator*= (const DoubleVect &)
Operateur de multiplication d'une matrice par un vecteur:
scaling des lignes de la matrice par les coefficients
correspondants du vecteur passe en parametre.
A *= x, effectue les scaling suivants:
A(i,:) = A(i,:) * x(i), pour toutes les lignes i de A.
Matrice_Morse operator- () const
Operateur de negation unaire, renvoie l'opposee de la matrice: - A
Appelle operator*(double,const Matrice_Morse&)
virtual int inverse (const DoubleVect &, DoubleVect &, double) const
Calcule la solution du systeme lineaire: A * solution = secmem.
La methode utilisee est GMRES preconditionnee avec ILUT.
ATTENTION: cette methode n'a vraisemblablement jamais ete testee en parallele.
virtual int inverse (const DoubleVect &, DoubleVect &, double, int) const
Matrice_Morse & affecte_prod (const Matrice_Morse &A, const Matrice_Morse &B)
Affecte le produit de 2 matrices Morse A et B a l'objet (this).
Operation: this = A * B.
void compacte (int elim_coeff_nul=0)
Method to check/clean the Matrice_Morse matrix:
-Suppress coefficient defined several times
-elim_coeff_nul=0, on ne supprime pas les coefficients nuls de la matrice
-elim_coeff_nul=1, on supprime les coefficients nuls de la matrice
-elim_coeff_nul=2, on supprime les coefficients nuls et quasi-nuls de la matrice.
DoubleVect & ajouter_multvect_ (const DoubleVect &, DoubleVect &) const override
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: resu = resu + A*x.
ArrOfDouble & ajouter_multvect_ (const ArrOfDouble &, ArrOfDouble &, ArrOfInt &) const
DoubleTab & ajouter_multTab_ (const DoubleTab &, DoubleTab &) const override
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice X representee par un tableau)
Operation: RESU = RESU + A*X.
DoubleVect & ajouter_multvectT_ (const DoubleVect &, DoubleVect &) const override
Operation de multiplication-accumulation (saxpy) matrice vecteur,
par la matrice transposee.
Operation: resu = resu + A^{T}*x.
ArrOfDouble & ajouter_multvectT_ (const ArrOfDouble &, ArrOfDouble &, ArrOfInt &) const
virtual Matrice_Morse & transpose (const Matrice_Morse &a)
*this = a transposee.
virtual Matrice_Morse & diagmulmat (const DoubleVect &x)
virtual Matrice_Morse & partie_sup (const Matrice_Morse &a)
void unite ()
void construire_sous_bloc (int nl0, int nc0, int nl1, int nc1, Matrice_Morse &result) const
void formeC ()
void formeF ()
bool has_same_morse_matrix_structure (const Matrice_Morse &) const
bool check_morse_matrix_structure (void) const
bool check_sorted_morse_matrix_structure (void) const
void assert_check_morse_matrix_structure (void) const
void assert_check_sorted_morse_matrix_structure (void) const
void sort_stencil ()
Public Member Functions inherited from Matrice_Base
Matrice_Base ()
~Matrice_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual int ordre () const =0
virtual int nb_lignes () const =0
virtual int nb_colonnes () const =0
virtual DoubleVect & ajouter_multvect_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleVect & ajouter_multvectT_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleTab & ajouter_multTab_ (const DoubleTab &x, DoubleTab &r) const =0
virtual DoubleVect & ajouter_multvect (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleVect & ajouter_multvectT (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleTab & ajouter_multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice represente par un tableau)
Operation: R = R + A*X.
virtual DoubleVect & multvect_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvect (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice.
Operation: r = A*x.
virtual DoubleVect & multvectT_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvectT (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice transposee.
Operation: r = AT*x.
virtual DoubleTab & multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Multiplication d'une matrice representee par un tableau par la matrice.
Operation: R = A*X.
virtual Sortie & imprimer (Sortie &) const
virtual Sortie & imprimer_formatte (Sortie &s) const
virtual void scale (const double x)=0
virtual void get_stencil (IntTab &stencil) const
virtual void get_symmetric_stencil (IntTab &stencil) const
virtual void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
virtual void get_symmetric_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
int get_stencil_size (void) const
virtual void build_stencil (void)
void set_stencil (const IntTab &stencil)
bool is_stencil_up_to_date (void) const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Matrice_Sym
virtual ~Matrice_Sym ()
Matrice_Sym ()
int get_est_definie () const
void set_est_definie (int)
void unsymmetrize_stencil (const int nb_lines, const IntTab &symmetric_stencil, IntTab &stencil) const
void unsymmetrize_stencil_and_coefficients (const int nb_lines, const IntTab &symmetric_stencil, const ArrOfDouble &symmetric_coefficients, IntTab &stencil, ArrOfDouble &coefficients) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Matrice_Morse_Diag & self_cast (Objet_U &)
static const Matrice_Morse_Diag & self_cast (const Objet_U &)
Static Public Member Functions inherited from Matrice_Morse_Sym
static Objet_U * cree_instance ()
static const Type_info * info ()
static Matrice_Morse_Sym & self_cast (Objet_U &)
static const Matrice_Morse_Sym & self_cast (const Objet_U &)
Static Public Member Functions inherited from Matrice_Morse
static Objet_U * cree_instance ()
static const Type_info * info ()
static Matrice_Morse & self_cast (Objet_U &)
static const Matrice_Morse & self_cast (const Objet_U &)
Static Public Member Functions inherited from Matrice_Base
static const Type_info * info ()
static Matrice_Base & self_cast (Objet_U &)
static const Matrice_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Matrice_Morse_Sym
static const Type_info info_obj
Static Public Attributes inherited from Matrice_Morse
static const Type_info info_obj
Static Public Attributes inherited from Matrice_Base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit les trois tableaux de la structure de stockage
Morse sur un flot de sortie.
Entree & readOn (Entree &) override
NON CODE.
Protected Member Functions inherited from Matrice_Morse_Sym
Sortie & printOn (Sortie &x) const override
Ecrit les trois tableaux de la structure de stockage
Morse sur un flot de sortie.
Entree & readOn (Entree &) override
NON CODE.
Sortie & printOn (Sortie &x) const override
Ecrit les trois tableaux de la structure de stockage
Morse sur un flot de sortie.
Entree & readOn (Entree &) override
NON CODE.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
virtual DoubleTab & ajouter_multTab_ (const DoubleTab &, DoubleTab &) const =0
virtual DoubleVect & ajouter_multvect_ (const DoubleVect &, DoubleVect &) const =0
virtual DoubleVect & ajouter_multvectT_ (const DoubleVect &, DoubleVect &) const =0
Additional Inherited Members
Public Attributes inherited from Matrice_Morse
int morse_matrix_structure_has_changed_
Flag if matrix structure changes.
int sorted_
Protected Attributes inherited from Matrice_Morse
IntVect tab1_
IntVect tab2_
DoubleVect coeff_
int m_
Number of columns.
int symetrique_
Pour inliner operator()(i,j) afin d'optimiser.
Protected Attributes inherited from Matrice_Base
bool is_stencil_up_to_date_
IntTab stencil_
Detailed Description
Classe Matrice_Morse_Diag
Represente une matrice M (creuse) symetrique stockee au format Morse
Diagetrique: on ne stocke que la partie triangulaire superieure de la
matrice. Important: Tous les coefficients diagonaux doivent etre stockes
meme s'ils sont nuls (hypothese TRUST pour plusieurs methodes dont multvect).
Cette classe derive de Matrice_Morse_Sym.
Definition at line 37 of file Matrice_Morse_Diag.h.
Constructor & Destructor Documentation
~Matrice_Morse_Diag()
Matrice_Morse_Diag::~Matrice_Morse_Diag ()
Definition at line 18 of file Matrice_Morse_Diag.cpp.
Matrice_Morse_Diag()
Matrice_Morse_Diag::Matrice_Morse_Diag () inline
Definition at line 43 of file Matrice_Morse_Diag.h.
  {
    symetrique_=2;
  };
References Matrice_Morse::symetrique_.
Member Function Documentation
ajouter_multTab_()
DoubleTab & Matrice_Morse_Diag::ajouter_multTab_ (const DoubleTab & x, DoubleTab & y) const override virtual
provoquue une erreur le but de cette matrice est juste de calculer la diagonale
Reimplemented from Matrice_Morse.
Definition at line 74 of file Matrice_Morse_Diag.cpp.
{
  Cerr<<" not implemented "<<finl;
  exit();
  return y;
}
References Cerr, Process::exit(), and finl.
ajouter_multvect_()
DoubleVect & Matrice_Morse_Diag::ajouter_multvect_ (const DoubleVect & x, DoubleVect & y) const override virtual
provoquue une erreur le but de cette matrice est juste de calculer la diagonale
Reimplemented from Matrice_Morse.
Definition at line 61 of file Matrice_Morse_Diag.cpp.
{
  return Matrice_Morse::ajouter_multvect_(x,y);
}
References Matrice_Morse::ajouter_multvect_().
ajouter_multvectT_()
DoubleVect & Matrice_Morse_Diag::ajouter_multvectT_ (const DoubleVect & x, DoubleVect & y) const override virtual
provoquue une erreur le but de cette matrice est juste de calculer la diagonale
Reimplemented from Matrice_Morse.
Definition at line 67 of file Matrice_Morse_Diag.cpp.
{
  Cerr<<" not implemented "<<finl;
  exit();
  return y;
}
References Cerr, Process::exit(), and finl.
cree_instance()
Objet_U * Matrice_Morse_Diag::cree_instance () static
Definition at line 18 of file Matrice_Morse_Diag.cpp.
dimensionne_diag()
void Matrice_Morse_Diag::dimensionne_diag (int n)
Definition at line 81 of file Matrice_Morse_Diag.cpp.
{
  IntTab indice(nb_case_tot,2);
  for( int c=0; c<nb_case_tot; c++) indice(c,0)=indice(c,1)=c;
  dimensionner( nb_case_tot, 0);
  dimensionner(indice);
}
References Matrice_Morse::dimensionner().
Referenced by Equation_base::Gradient_conjugue_diff_impl().
duplique()
int Matrice_Morse_Diag::duplique () const override virtual
Reimplemented from Matrice_Morse.
Definition at line 18 of file Matrice_Morse_Diag.cpp.
get_info()
const Type_info * Matrice_Morse_Diag::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Matrice_Morse.
Definition at line 18 of file Matrice_Morse_Diag.cpp.
info()
const Type_info * Matrice_Morse_Diag::info () static
Definition at line 18 of file Matrice_Morse_Diag.cpp.
printOn()
Sortie & Matrice_Morse_Diag::printOn (Sortie & s) const override protected virtual
Ecrit les trois tableaux de la structure de stockage
Morse sur un flot de sortie.
Returns
Sortie& s
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Matrice_Morse.
Definition at line 35 of file Matrice_Morse_Diag.cpp.
{
  return  Matrice_Morse::printOn(s);
}
References Matrice_Morse::printOn().
readOn()
Entree & Matrice_Morse_Diag::readOn (Entree & s) override protected virtual
NON CODE.
Returns
Entree& s
Signification: le flot d'entree
Contraintes:
Reimplemented from Matrice_Morse.
Definition at line 55 of file Matrice_Morse_Diag.cpp.
{
  return  Matrice_Morse::readOn(s) ;
}
References Matrice_Morse::readOn().
self_cast() [1/2]
const Matrice_Morse_Diag & Matrice_Morse_Diag::self_cast (const Objet_U & r) static
Definition at line 18 of file Matrice_Morse_Diag.cpp.
self_cast() [2/2]
Matrice_Morse_Diag & Matrice_Morse_Diag::self_cast (Objet_U & r) static
Definition at line 18 of file Matrice_Morse_Diag.cpp.
taille_memoire()
unsigned Matrice_Morse_Diag::taille_memoire () const override virtual
Reimplemented from Matrice_Morse.
Definition at line 18 of file Matrice_Morse_Diag.cpp.
Member Data Documentation
info_obj
const Type_info Matrice_Morse_Diag::info_obj static
Definition at line 40 of file Matrice_Morse_Diag.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/Matrices/Matrice_Morse_Diag.h
src/Kernel/Math/Matrices/Matrice_Morse_Diag.cpp