TRUST: Segment_EF Class Reference
Segment_EF Class Reference
#include <Segment_EF.h>
Public Member Functions
~Segment_EF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Segment_EF ()
void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int) const
void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=2, n1 est le numero du sommet confondu avec G
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const
remplit le tableau face_normales dans la Zone_EF
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Segment_EF & self_cast (Objet_U &)
static const Segment_EF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 28 of file Segment_EF.h.
Constructor & Destructor Documentation
Segment_EF::~Segment_EF ()
Definition at line 29 of file Segment_EF.cpp.
Segment_EF::Segment_EF ()
Definition at line 29 of file Segment_EF.cpp.
Member Function Documentation
void Segment_EF::calcul_vc (const ArrOfInt & Face, ArrOfDouble & vc, const ArrOfDouble & vs, const DoubleTab & vsom, const Champ_Inc_base & vitesse, int type_cl) const [virtual]
< le triangle n'a pas de Face de Dirichlet
< le triangle a une Face de Dirichlet :la Face 2
< le triangle a une Face de Dirichlet :la Face 1
< le triangle a une Face de Dirichlet :la Face 0
< le triangle a deux faces de Dirichlet :les faces 1 et 2
< le triangle a deux faces de Dirichlet :les faces 0 et 2
< le triangle a deux faces de Dirichlet :les faces 0 et 1
Implements Elem_EF_base.
Definition at line 141 of file Segment_EF.cpp.
References Zone_VF::porosite_face(), ref_cast, and Champ_base::zone_dis_base().
{
  const Zone_EF& zone_EF = ref_cast(Zone_EF,vitesse.zone_dis_base());
  const DoubleVect& porosite_face = zone_EF.porosite_face();
// Cerr << " type_cl " <<  type_cl << finl;
  switch(type_cl)
    {
    case 0: //!< le triangle n'a pas de Face de Dirichlet
      {
        vc[0] = vs[0]/3;
        vc[1] = vs[1]/3;
        break;
      }
    case 1: //!< le triangle a une Face de Dirichlet :la Face 2
      {
        vc[0]= vitesse(Face[2],0)*porosite_face(Face[2]);
        vc[1]= vitesse(Face[2],1)*porosite_face(Face[2]);
// vc[0]= vitesse(Face[2],0);
// vc[1]= vitesse(Face[2],1);
        break;
      }
    case 2: //!< le triangle a une Face de Dirichlet :la Face 1
      {
        vc[0]= vitesse(Face[1],0)*porosite_face(Face[1]);
        vc[1]= vitesse(Face[1],1)*porosite_face(Face[1]);
// vc[0]= vitesse(Face[1],0);
// vc[1]= vitesse(Face[1],1);
        break;
      }
    case 4: //!< le triangle a une Face de Dirichlet :la Face 0
      {
        vc[0]= vitesse(Face[0],0)*porosite_face(Face[0]);
        vc[1]= vitesse(Face[0],1)*porosite_face(Face[0]);
// vc[0]= vitesse(Face[0],0);
// vc[1]= vitesse(Face[0],1);
        break;
      }
    case 3: //!< le triangle a deux faces de Dirichlet :les faces 1 et 2
      {
        vc[0]= vsom(0,0);
        vc[1]= vsom(0,1);
        break;
      }
    case 5: //!< le triangle a deux faces de Dirichlet :les faces 0 et 2
      {
        vc[0]= vsom(1,0);
        vc[1]= vsom(1,1);
        break;
      }
    case 6: //!< le triangle a deux faces de Dirichlet :les faces 0 et 1
      {
        vc[0]= vsom(2,0);
        vc[1]= vsom(2,1);
        break;
      }
    } //!< fin du switch
}
void Segment_EF::calcul_xg (DoubleVect & xg, const DoubleTab & x, const int type_elem_Cl, int & idirichlet, int & n1, int & , int &) const [virtual]
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=2, n1 est le numero du sommet confondu avec G
< le triangle n'a pas de Face de dirichlet: il a 3 Facettes le point G est le barycentre des sommets du triangle
< le triangle a une Face de dirichlet: la Face 2 le point G est le barycentre des sommets de la Face 2
< le triangle a une Face de dirichlet: la Face 1 le point G est le barycentre des sommets de la Face 1
< le triangle a une Face de dirichlet: la Face 0 le point G est le barycentre des sommets de la Face 0
< le triangle a deux faces de Dirichlet : les faces 0,1 le point G est le sommet 2 du triangle
< le triangle a deux faces de Dirichlet : les faces 0,2 le point G est le sommet 1 du triangle
< le triangle a deux faces de Dirichlet : les faces 1,2 le point G est le sommet 0 du triangle
Implements Elem_EF_base.
Definition at line 213 of file Segment_EF.cpp.
References DoubleVect::size().
{
  int j,dim=xg.size();
  switch(type_elem_Cl)
    {
    case 0:  //!< le triangle n'a pas de Face de dirichlet: il a 3 Facettes  le point G est le barycentre des sommets du triangle
//
      {
        for (j=0; j<dim; j++)
          xg[j]=(x(0,j)+x(1,j)+x(2,j))/3;
        idirichlet=0;
        break;
      }
    case 1:  //!< le triangle a une Face de dirichlet: la Face 2 le point G est le barycentre des sommets de la Face 2
//
      {
        for (j=0; j<dim; j++)
          xg[j]=(x(0,j)+x(1,j))/2;
        idirichlet=1;
        break;
      }
    case 2:  //!< le triangle a une Face de dirichlet: la Face 1 le point G est le barycentre des sommets de la Face 1
//
      {
        for (j=0; j<dim; j++)
          xg[j]=(x(0,j)+x(2,j))/2;
        idirichlet=1;
        break;
      }
    case 4:  //!< le triangle a une Face de dirichlet: la Face 0 le point G est le barycentre des sommets de la Face 0
//
      {
        for (j=0; j<dim; j++)
          xg[j]=(x(1,j)+x(2,j))/2;
        idirichlet=1;
        break;
      }
    case 6 : //!< le triangle a deux faces de Dirichlet : les faces 0,1 le point G est le sommet 2 du triangle
//
      {
        for (j=0; j<dim; j++)
          xg[j]=x(2,j);
        idirichlet=2;
        n1 = 2;
        break;
      }
    case 5 : //!< le triangle a deux faces de Dirichlet : les faces 0,2 le point G est le sommet 1 du triangle
//
      {
        for (j=0; j<dim; j++)
          xg[j]=x(1,j);
        idirichlet=2;
        n1 = 1;
        break;
      }
    case 3 : //!< le triangle a deux faces de Dirichlet : les faces 1,2 le point G est le sommet 0 du triangle
//
      {
        for (j=0; j<dim; j++)
          xg[j]=x(0,j);
        idirichlet=2;
        n1 = 0;
        break;
      }
    } //!< fin du switch
}
Objet_U * Segment_EF::cree_instance () [static]
Reimplemented in Segment_EF_axi.
Definition at line 29 of file Segment_EF.cpp.
int Segment_EF::duplique () const [virtual]
Implements Elem_EF_base.
Reimplemented in Segment_EF_axi.
Definition at line 29 of file Segment_EF.cpp.
const Type_info * Segment_EF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_EF_base.
Reimplemented in Segment_EF_axi.
Definition at line 29 of file Segment_EF.cpp.
const Type_info * Segment_EF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_EF_base.
Reimplemented in Segment_EF_axi.
Definition at line 29 of file Segment_EF.cpp.
void Segment_EF::normale (int num_Face, DoubleTab & Face_normales, const IntTab & Face_sommets, const IntTab & Face_voisins, const IntTab & elem_faces, const Zone & zone_geom) const [virtual]
remplit le tableau face_normales dans la Zone_EF
Implements Elem_EF_base.
Reimplemented in Segment_EF_axi.
Definition at line 47 of file Segment_EF.cpp.
References Zone_VF::elem_faces().
{
// pas de sens simple a normale
  Face_normales(num_Face,0) = 1;
  {
// int n0 = Face_sommets(num_Face,0);
    int elem1 = Face_voisins(num_Face,0);
// int elem2 = Face_voisins(num_Face,1);
    int n2=elem_faces(elem1,0);
    if (n2==num_Face) Face_normales(num_Face,0) = -1;
    /*
    const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
    //     const IntTab& elem = zone_geom.elems();
       {
    int n2=elem_faces(elem1,0);
    if ( n2 == num_Face )
    n2 = elem_faces(elem1,1);
    n2=Face_sommets(n2,0);
    for (int i=0;i<dim;i++)
    d(i) =les_coords(n0,i)- les_coords(n2,i);
    d/=d.norm();
    Face_normales(num_Face,0) = -1;
    }
    //int n1 = Face_sommets(num_Face,1);
    // Orientation de la normale de elem1 vers elem2
    // pour cela recherche du sommet de elem1 qui n'est pas sur la Face
    int f0,no3;
    int elem1 = Face_voisins(num_Face,0);
    Cerr<<num_Face<<" iii "<<elem1<< " "<<Face_voisins(num_Face,1)<<" "<<(Face_voisins(num_Face,0)==elem1)        <<finl;
    if ( (f0 = elem_faces(elem1,0)) == num_Face )
    f0 = elem_faces(elem1,1);
    if ( (no3 = Face_sommets(f0,0)) != n0  )
    Cerr<<"oo "<<finl;
    else
    {
    Cerr<<"ii"<<finl;
    no3 = Face_sommets(f0,1);
    }
    Cerr<<n0 << " "<<finl;
    */
  }
  return;
  /*
  double x1,y1;
  double nx,ny;
  int no3; int f0;
  int n0 = Face_sommets(num_Face,0);
  int n1 = Face_sommets(num_Face,1);
  x1 = les_coords(n0,0)-les_coords(n1,0);
  y1 = les_coords(n0,1)-les_coords(n1,1);
  nx = -y1;
  ny = x1;
  // Orientation de la normale de elem1 vers elem2
  // pour cela recherche du sommet de elem1 qui n'est pas sur la Face
  int elem1 = Face_voisins(num_Face,0);
  if ( (f0 = elem_faces(elem1,0)) == num_Face )
    f0 = elem_faces(elem1,1);
  if ( (no3 = Face_sommets(f0,0)) != n0 && no3 != n1 )
    ;
  else
    no3 = Face_sommets(f0,1);
  x1 = les_coords(no3,0) - les_coords(n0,0);
  y1 = les_coords(no3,1) - les_coords(n0,1);
  if ( (nx*x1+ny*y1) > 0 ) {
    Face_normales(num_Face,0) = - nx;
    Face_normales(num_Face,1) = - ny;
  }
  else {
    Face_normales(num_Face,0) = nx;
    Face_normales(num_Face,1) = ny;
  }
  */
}
Sortie & Segment_EF::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Elem_EF_base.
Reimplemented in Segment_EF_axi.
Definition at line 34 of file Segment_EF.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Segment_EF::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Elem_EF_base.
Reimplemented in Segment_EF_axi.
Definition at line 39 of file Segment_EF.cpp.
{
  return s ;
}
Segment_EF & Segment_EF::self_cast (Objet_U & r) [static]
Reimplemented from Elem_EF_base.
Reimplemented in Segment_EF_axi.
Definition at line 29 of file Segment_EF.cpp.
const Segment_EF & Segment_EF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Elem_EF_base.
Reimplemented in Segment_EF_axi.
Definition at line 29 of file Segment_EF.cpp.
unsigned Segment_EF::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Segment_EF_axi.
Definition at line 29 of file Segment_EF.cpp.
Member Data Documentation
const Type_info Segment_EF::info_obj [static]
Reimplemented from Elem_EF_base.
Reimplemented in Segment_EF_axi.
Definition at line 31 of file Segment_EF.h.
The documentation for this class was generated from the following files:
src/EF/Zones/Segment_EF.h
src/EF/Zones/Segment_EF.cpp