TRUST: Modele_turbulence_hyd_nul Class Reference
Modele_turbulence_hyd_nul Class Reference
#include <Modele_turbulence_hyd_nul.h>
Public Member Functions
Modele_turbulence_hyd_nul ()
~Modele_turbulence_hyd_nul ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double) override
int sauvegarder (Sortie &) const override
Les operations qui suivent correspondent a ce qu'on trouve
dans Navier_Stokes_Turbulent::reprendre...
Public Member Functions inherited from Mod_turb_hyd_base
~Mod_turb_hyd_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Mod_turb_hyd_base ()
const Champ_Fonc & viscosite_turbulente () const
Renvoie la viscosite turbulente.
Equation_base & equation ()
Renvoie l'equation associee au modele de turbulence.
(c'est une equation du type Equation_base)
const Equation_base & equation () const
const Turbulence_paroi & loi_paroi () const
Turbulence_paroi & loi_paroi ()
bool utiliser_loi_paroi () const
virtual bool calcul_tenseur_Re (const DoubleTab &nu_turb, const DoubleTab &grad, DoubleTab &Re) const
virtual void set_param (Param &param)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int preparer_calcul ()
Prepare le calcul.
Initialise la loi de paroi.
Remplit le champ wall_length en cas de post traitemetn de la distance_paroi.
virtual bool initTimeStep (double dt)
virtual void mettre_a_jour (double)=0
virtual void discretiser ()
Discretise le modele de turbulence.
void discretiser_visc_turb (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
void discretiser_corr_visc_turb (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
void discretiser_K (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
Utilise par les modeles de tubulence dans TrioCFD.
virtual void completer ()
NE FAIT RIEN.
void associer_eqn (const Equation_base &)
Associe l'equation passe en parametre au modele de turbulence.
virtual void associer (const Zone_dis &, const Zone_Cl_dis &)
NE FAIT RIEN
a surcharger dans les classes derivees.
Associe la zone discretisee et la zone des conditions
aux limites discretisees au modele de turbulence.
int reprendre (Entree &) override
Reprend la loi de paroi.
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Champs_compris & champs_compris ()
virtual void imprimer (Sortie &) const
Effectue l'impression si cela est necessaire.
void a_faire (Sortie &) const
Effectue l'ecriture d'une identite si cela est necessaire.
int sauvegarder (Sortie &) const override
Sauvegarde le modele de turbulence sur un flot de sortie.
Sauvegarde le type de l'objet.
int limpr_ustar (double, double, double, double) const
double get_Cmu () const
Renvoie de la valeur de Cmu.
void lire_distance_paroi ()
Lit le fichier dom_Wall_length.xyz pour remplir le champs wall_length en vue d'un post-traitement de distance_paroi.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Modele_turbulence_hyd_nul & self_cast (Objet_U &)
static const Modele_turbulence_hyd_nul & self_cast (const Objet_U &)
Static Public Member Functions inherited from Mod_turb_hyd_base
static const Type_info * info ()
static Mod_turb_hyd_base & self_cast (Objet_U &)
static const Mod_turb_hyd_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Mod_turb_hyd_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type et le nom de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les specifications d'un modele de turbulence
a partir d'un flot d'entree.
Format:
Modele_turbulence type_modele
{
[Turbulence_paroi la_loi_de_paroi]
bloc de lecture specifique du type de turbulence
}.
Protected Member Functions inherited from Mod_turb_hyd_base
Sortie & printOn (Sortie &x) const override
Ecrit le type et le nom de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les specifications d'un modele de turbulence
a partir d'un flot d'entree.
Format:
Modele_turbulence type_modele
{
[Turbulence_paroi la_loi_de_paroi]
bloc de lecture specifique du type de turbulence
}.
void limiter_viscosite_turbulente ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Additional Inherited Members
Protected Attributes inherited from Mod_turb_hyd_base
double LeCmu
Champ_Fonc la_viscosite_turbulente
Champ_Fonc wall_length_
Ref_Equation_base mon_equation
Turbulence_paroi loipar
double dt_impr_ustar
double dt_impr_ustar_mean_only
int boundaries_
List_Nom boundaries_list
Nom nom_fichier_
Champs_compris champs_compris_
Detailed Description
Definition at line 21 of file Modele_turbulence_hyd_nul.h.
Constructor & Destructor Documentation
Modele_turbulence_hyd_nul()
Modele_turbulence_hyd_nul::Modele_turbulence_hyd_nul ()
Definition at line 25 of file Modele_turbulence_hyd_nul.cpp.
{
// Le modele supporte rho variable :
  declare_support_masse_volumique(1);
}
References Support_Champ_Masse_Volumique::declare_support_masse_volumique().
~Modele_turbulence_hyd_nul()
Modele_turbulence_hyd_nul::~Modele_turbulence_hyd_nul ()
Definition at line 23 of file Modele_turbulence_hyd_nul.cpp.
Member Function Documentation
cree_instance()
Objet_U * Modele_turbulence_hyd_nul::cree_instance () static
Definition at line 23 of file Modele_turbulence_hyd_nul.cpp.
duplique()
int Modele_turbulence_hyd_nul::duplique () const override virtual
Implements Objet_U.
Definition at line 23 of file Modele_turbulence_hyd_nul.cpp.
get_info()
const Type_info * Modele_turbulence_hyd_nul::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Mod_turb_hyd_base.
Definition at line 23 of file Modele_turbulence_hyd_nul.cpp.
info()
const Type_info * Modele_turbulence_hyd_nul::info () static
Definition at line 23 of file Modele_turbulence_hyd_nul.cpp.
mettre_a_jour()
void Modele_turbulence_hyd_nul::mettre_a_jour (double temps) override virtual
Implements Mod_turb_hyd_base.
Definition at line 68 of file Modele_turbulence_hyd_nul.cpp.
{
}
printOn()
Sortie & Modele_turbulence_hyd_nul::printOn (Sortie & s) const override protected virtual
Ecrit le type et le nom de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Mod_turb_hyd_base.
Definition at line 63 of file Modele_turbulence_hyd_nul.cpp.
{
  return os;
}
readOn()
Entree & Modele_turbulence_hyd_nul::readOn (Entree & is) override protected virtual
Lit les specifications d'un modele de turbulence
a partir d'un flot d'entree.
Format:
Modele_turbulence type_modele
{
[Turbulence_paroi la_loi_de_paroi]
bloc de lecture specifique du type de turbulence
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Mod_turb_hyd_base.
Definition at line 31 of file Modele_turbulence_hyd_nul.cpp.
{
// Creation d'une loi de paroi nulle:
  const Equation_base& eqn = equation();
  const Nom& discr = eqn.discretisation().que_suis_je();
  loipar.associer_modele(*this);
  if (discr == "VEF" || discr == "VEFPreP1B")
    {
      loipar.typer("negligeable_VEF");
    }
  else if (discr == "VDF")
    {
      loipar.typer("negligeable_VDF");
    }
  else if (discr == "EF")
    {
      loipar.typer("negligeable_EF");
    }
  else
    {
      Cerr << "Erreur dans Modele_turbulence_hyd_nul::readOn\n";
      Cerr << " la discretisation " << discr << " n'est pas prise en charge";
      Cerr << finl;
      assert(0);
      exit();
    }
  loipar.valeur().associer_modele(*this);
  loipar.valeur().associer(eqn.zone_dis(),eqn.zone_Cl_dis());
  return is;
}
References Turbulence_paroi_base::associer(), Turbulence_paroi::associer_modele(), Turbulence_paroi_base::associer_modele(), Cerr, Equation_base::discretisation(), Mod_turb_hyd_base::equation(), Process::exit(), finl, Mod_turb_hyd_base::loipar, Objet_U::que_suis_je(), Deriv_::typer(), Deriv_Turbulence_paroi_base::valeur(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
sauvegarder()
int Modele_turbulence_hyd_nul::sauvegarder (Sortie & os) const override virtual
Les operations qui suivent correspondent a ce qu'on trouve
dans Navier_Stokes_Turbulent::reprendre...
Reimplemented from Mod_turb_hyd_base.
Definition at line 75 of file Modele_turbulence_hyd_nul.cpp.
{
// en mode ecriture special seul le maitre ecrit l'entete
  int write,special;
  EcritureLectureSpecial::is_ecriture_special(special,write);
  if (write)
    {
      Nom mon_ident(que_suis_je());
      mon_ident += equation().probleme().domaine().le_nom();
      double temps = equation().schema_temps().temps_courant();
      mon_ident += Nom(temps,"%e");
      os << mon_ident << finl;
      os << que_suis_je() << finl;
      os.flush();
    }
  return 0;
}
References Probleme_base::domaine(), Mod_turb_hyd_base::equation(), finl, Sortie::flush(), EcritureLectureSpecial::is_ecriture_special(), Domaine::le_nom(), Equation_base::probleme(), Objet_U::que_suis_je(), Equation_base::schema_temps(), and Schema_Temps_base::temps_courant().
self_cast() [1/2]
const Modele_turbulence_hyd_nul & Modele_turbulence_hyd_nul::self_cast (const Objet_U & r) static
Definition at line 23 of file Modele_turbulence_hyd_nul.cpp.
self_cast() [2/2]
Modele_turbulence_hyd_nul & Modele_turbulence_hyd_nul::self_cast (Objet_U & r) static
Definition at line 23 of file Modele_turbulence_hyd_nul.cpp.
taille_memoire()
unsigned Modele_turbulence_hyd_nul::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 23 of file Modele_turbulence_hyd_nul.cpp.
Member Data Documentation
info_obj
const Type_info Modele_turbulence_hyd_nul::info_obj static
Definition at line 23 of file Modele_turbulence_hyd_nul.h.
The documentation for this class was generated from the following files:
src/ThHyd/Turbulence/Modele_turbulence_hyd_nul.h
src/ThHyd/Turbulence/Modele_turbulence_hyd_nul.cpp