TRUST: Joints Class Reference
Joints Class Reference
Classe Joints
Cette classe represente une liste d'objet de type Joint.
#include <Joints.h>
Public Member Functions
Joints ()
~Joints ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Associe une zone a tous les joints de la liste.
Les joints de la liste feront partie de cette zone.
int nb_faces () const
Renvoie le nombre de face total des Joints
de la liste. (la somme des faces de tous les
joints de la liste).
int nb_faces (Type_Face type) const
Renvoie le nombre de faces du type specifie
contenues dans la liste de joints.
(somme des faces de ce type sur tous les
joints de la liste)
int nb_joints () const
Renvoie le nombre de Joint de la liste.
void comprimer ()
Comprime la liste de joints.
Joint & joint_PE (int pe)
Renvoie une reference sur le joint qui a
pour voisin le PE specifie.
Public Member Functions inherited from List_Joint
List_Joint ()
~List_Joint ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
List_Joint (const Joint &t)
List_Joint (const List_Joint &t)
Joint & operator[] (int)
const Joint & operator[] (int) const
Joint & operator[] (const Nom &)
const Joint & operator[] (const Nom &) const
Joint & operator() (int i)
const Joint & operator() (int i) const
Joint & operator() (const Nom &n)
const Joint & operator() (const Nom &n) const
Joint & valeur ()
const Joint & valeur () const
List_Joint & operator= (const Joint &t)
Joint * operator-> ()
List_Joint & operator= (const List_Joint &)
List_Joint & add (const List_Joint &)
Joint & add (const Joint &)
List_Joint & inserer (const List_Joint &)
Joint & inserer (const Joint &)
void supprimer ()
List_Joint & operator+= (const List_Joint &)
List_Joint & operator+= (const Joint &)
Joint & add_if_not (const Joint &)
Joint & add_if_not (const char *const)
List_Joint & search (const Joint &) const
List_Joint & search (const char *const) const
List_Joint & suivant ()
const List_Joint & suivant () const
const List_Joint & dernier () const
List_Joint & dernier ()
List_Joint & operator-= (const Joint &)
int est_egal_a (const Objet_U &) const override
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
int contient (const Joint &) const
int contient (const char *const) const
int rang (const Joint &) const
void suppr (const Joint &)
Public Member Functions inherited from liste
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
liste ()
Constructeur par defaut
Construit une liste vide.
liste (const liste &)
Constructeur
Ajoute les elements contenus dans la liste passe en parametre.
liste (const Objet_U &)
Constructeur
Construit une liste singleton.
~liste () override
Destructeur de liste.
int size () const
Renvoie la taille de la liste
Une liste vide est de taille nulle.
int rang (const char *const) const
Renvoie le rang d'une chaine de caracteres contenue dans la liste
Recherche un Objet_U de Nom ch.
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
void suppr (const char *const)
Supprime l'Objet de Nom ch contenu dans la liste.
int est_vide () const
Teste si la liste est vide.
int est_dernier () const
Teste si la liste comporte des elements suivants ou non.
Retourne 1 si la liste est vide.
void vide ()
Vide la liste.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Joints & self_cast (Objet_U &)
static const Joints & self_cast (const Objet_U &)
Static Public Member Functions inherited from List_Joint
static Objet_U * cree_instance ()
static const Type_info * info ()
static List_Joint & self_cast (Objet_U &)
static const List_Joint & self_cast (const Objet_U &)
Static Public Member Functions inherited from liste
static Objet_U * cree_instance ()
static const Type_info * info ()
static liste & self_cast (Objet_U &)
static const liste & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from List_Joint
static const Type_info info_obj
Static Public Attributes inherited from liste
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
Protected Member Functions inherited from List_Joint
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
int est_egal_a (const List_Joint &) const
Protected Member Functions inherited from liste
Sortie & printOn (Sortie &x) const override
Ecriture d'une liste sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une liste sur un flot d'entree.
Objet_U & operator() (int)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Objet_U & operator() (int) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Objet_U & operator() (const Nom &)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Objet_U & operator() (const Nom &) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Objet_U & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Objet_U & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
liste & operator+= (const Objet_U &)
Ajoute un Objet_U a la fin de la liste.
liste & operator+= (const liste &)
Ajoute une list d'Objet_U a la fin de la liste.
liste & operator-= (const Objet_U &)
Supprime un Objet_U de la liste
Affiche un message d'erreur si l'objet n'est pas trouve.
const liste & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
liste & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
Objet_U * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
const Objet_U * operator-> () const
Retourne un pointeur sur l'Objet_U premier element de la liste.
Objet_U & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Objet_U & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Objet_U & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Objet_U & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Objet_U & add (const Objet_U &)
Ajout d'un Objet_U a la liste.
Objet_U & add_deplace (DerObjU &)
Ajout d'un Objet_U a la liste
to_add est libere en sortie.
Objet_U & inserer (const Objet_U &)
Insertion d'un Objet_U dans la liste.
liste & add (const liste &)
Ajout d'une liste a la liste.
liste & inserer (const liste &)
Insertion d'une liste
NON CODE - SORT SYSTEMATIQUEMENT EN ERREUR.
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Objet_U & add_if_not (const Objet_U &)
Ajout d'un Objet_U a la liste ssi il n'existe pas deja.
liste & search (const Objet_U &) const
Recherche d'un Objet_U dans la liste.
liste & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
int contient (const Objet_U &) const
Verifie si un Objet_U appartient ou non a la liste.
int rang (const Objet_U &) const
Renvoie le rang d'un Objet_U dans la liste.
void suppr (const Objet_U &)
Supprime un Objet_U contenu dans la liste.
liste & operator= (const liste &)
Operateur d'affectation de liste.
const liste & dernier () const
Renvoie le dernier element de la liste.
liste & dernier ()
Renvoie le dernier element de la liste.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from liste
DerObjU data
liste * suivant_
Detailed Description
Classe Joints
Cette classe represente une liste d'objet de type Joint.
Definition at line 32 of file Joints.h.
Constructor & Destructor Documentation
Joints()
Joints::Joints ()
Definition at line 18 of file Joints.cpp.
~Joints()
Joints::~Joints ()
Definition at line 18 of file Joints.cpp.
Member Function Documentation
associer_zone()
void Joints::associer_zone (const Zone & une_zone)
Associe une zone a tous les joints de la liste.
Les joints de la liste feront partie de cette zone.
Definition at line 74 of file Joints.cpp.
{
  LIST_CURSEUR(Joint) curseur(*this);;;
  while(curseur)
    {
      curseur->associer_zone(une_zone);
      ++curseur;
    }
}
References LIST_CURSEUR.
Referenced by Zone::check_zone(), Zones::comprimer(), convert_domain_to_Domaine(), Interprete_geometrique_base::interpreter(), and Zones::merge().
comprimer()
void Joints::comprimer ()
Comprime la liste de joints.
Definition at line 161 of file Joints.cpp.
{
  Cerr << "Joints::comprimer() - Start" << finl;
  IntVect fait(size());
  int rang1=0, rang2=0;
  LIST_CURSEUR(Joint) curseur1(*this);;
  while(curseur1)
    {
      if (!fait(rang1) )
        {
          fait(rang1)=1;
          Joint& joint1=curseur1.valeur();
          rang2=rang1;
          LIST_CURSEUR(Joint) curseur2(curseur1.list());;
          while(curseur2)
            {
              if (!fait(rang2) )
                {
                  Joint& joint2=curseur2.valeur();
                  if(joint1.PEvoisin() == joint2.PEvoisin())
                    {
                      Cerr << "agglomeration of joints " << joint1.le_nom()
                           << " and " << joint2.le_nom() << finl;
                      fait(rang2)=1;
                      joint1.nommer(joint1.le_nom()+joint2.le_nom());
// Concatenation des faces
                      joint1.ajouter_faces(joint2.les_sommets_des_faces());
// Concatenation des sommets ???
                      Cerr << "Concatenation of nodes ?" << finl;
                      exit();
                      joint2.dimensionner(0);
                    }
                }
              ++curseur2;
              rang2++;
            }
        }
      ++curseur1;
      ++rang1;
    }
  curseur1=*this;
  while(curseur1)
    {
      Joint& joint1=curseur1.valeur();
      if (joint1.nb_faces()==0)
        {
          suppr(curseur1.valeur());
          curseur1=*this;
        }
      else
        ++curseur1;
    }
  Cerr << "Joints::comprimer() - End" << finl;
}
References Joint::ajouter_faces(), Cerr, Joint::dimensionner(), Process::exit(), finl, Frontiere::le_nom(), Frontiere::les_sommets_des_faces(), LIST_CURSEUR, Frontiere::nb_faces(), Frontiere::nommer(), Joint::PEvoisin(), liste::size(), and List_Joint::suppr().
cree_instance()
Objet_U * Joints::cree_instance () static
Definition at line 18 of file Joints.cpp.
duplique()
int Joints::duplique () const override virtual
Reimplemented from List_Joint.
Definition at line 18 of file Joints.cpp.
get_info()
const Type_info * Joints::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from List_Joint.
Definition at line 18 of file Joints.cpp.
info()
const Type_info * Joints::info () static
Definition at line 18 of file Joints.cpp.
joint_PE()
Joint & Joints::joint_PE (int pe)
Renvoie une reference sur le joint qui a
pour voisin le PE specifie.
Returns
Joint&
Signification: le joint qui a pour voisin le PE specifie
Contraintes:
Definition at line 253 of file Joints.cpp.
{
  LIST_CURSEUR(Joint) curseur(*this);
  for (; curseur; ++curseur)
    {
      Joint& joint = curseur.valeur();
      int pe_joint = joint.PEvoisin();
      if (pe == pe_joint)
        return joint;
    }
  Cerr << "Error in Joints::joint_PE : joint not found" << finl;
  assert(0);
  exit();
  return curseur.valeur();
}
References Cerr, Process::exit(), finl, LIST_CURSEUR, and Joint::PEvoisin().
nb_faces() [1/2]
int Joints::nb_faces () const
Renvoie le nombre de face total des Joints
de la liste. (la somme des faces de tous les
joints de la liste).
Returns
int
Signification: le nombre de face total des Joints
de la liste
Contraintes:
Definition at line 102 of file Joints.cpp.
{
  CONST_LIST_CURSEUR(Joint) curseur(*this);;;
  int nombre=0;
  while(curseur)
    {
      nombre+=curseur->nb_faces();
      ++curseur;
    }
  return nombre;
}
References CONST_LIST_CURSEUR.
Referenced by Zone::nb_faces_joint().
nb_faces() [2/2]
int Joints::nb_faces (Type_Face type) const
Renvoie le nombre de faces du type specifie
contenues dans la liste de joints.
(somme des faces de ce type sur tous les
joints de la liste)
Returns
int
Signification: le nombre de faces du type specifie
contenues dans la liste de joints
Contraintes:
Definition at line 133 of file Joints.cpp.
{
  CONST_LIST_CURSEUR(Joint) curseur(*this);
  int nombre=0;
  while(curseur)
    {
      if (type == curseur->faces().type_face())
        nombre+=curseur->nb_faces();
      ++curseur;
    }
  return nombre;
}
References CONST_LIST_CURSEUR.
nb_joints()
int Joints::nb_joints () const
Renvoie le nombre de Joint de la liste.
Returns
int
Signification: le nombre de Joint de la liste
Contraintes:
Definition at line 233 of file Joints.cpp.
{
  return size();
}
References liste::size().
Referenced by Zone::nb_joints().
printOn()
Sortie & Joints::printOn (Sortie & os) const override protected virtual
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from List_Joint.
Definition at line 34 of file Joints.cpp.
{
  return LIST(Joint)::printOn(os);
}
References LIST, and printOn().
Referenced by printOn().
readOn()
Entree & Joints::readOn (Entree & is) override protected virtual
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from List_Joint.
Definition at line 53 of file Joints.cpp.
{
  return LIST(Joint)::readOn(is);
}
References LIST, and readOn().
Referenced by readOn().
self_cast() [1/2]
const Joints & Joints::self_cast (const Objet_U & r) static
Definition at line 18 of file Joints.cpp.
self_cast() [2/2]
Joints & Joints::self_cast (Objet_U & r) static
Definition at line 18 of file Joints.cpp.
taille_memoire()
unsigned Joints::taille_memoire () const override virtual
Reimplemented from List_Joint.
Definition at line 18 of file Joints.cpp.
Member Data Documentation
info_obj
const Type_info Joints::info_obj static
Definition at line 34 of file Joints.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Joints.h
src/Kernel/Geometrie/Joints.cpp