TRUST: Fluide_Ostwald Class Reference
Fluide_Ostwald Class Reference
class Fluide_Ostwald
Possede les proprietes d'un fluide incompressible plus:
N : indice de structure
K : consistance du fluide
La viscosite dynamique dans ce cas depend de K, N et Grad(U)
Nouveau fluide. c'est un fluide incompressible non newtonien. Il derive donc
de fluide_Incompressible et possede quelques proprietes de plus (K, N)
mu depend de K, N, et de grad(U)
#include <Fluide_Ostwald.h>
Public Member Functions
~Fluide_Ostwald ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Fluide_Ostwald ()
const Champ_Don & consistance () const
Champ_Don & consistance ()
const Champ_Don & indice_struct () const
Champ_Don & indice_struct ()
void set_param (Param &param)
void creer_champs_non_lus ()
void mettre_a_jour (double)
Effectue une mise a jour en temps du milieu,
et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le
nouveau temps specifie, les autres sont mis a
par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
int initialiser (const double &temps)
Initialise les parametres du fluide.
virtual void discretiser (const Probleme_base &pb, const Discretisation_base &dis)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Fluide_Ostwald & self_cast (Objet_U &)
static const Fluide_Ostwald & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit les proprietes du fluide sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
Protected Attributes
Champ_Don K_
consistance lue
Champ_Don N_
indice de structure lue
Detailed Description
class Fluide_Ostwald
Possede les proprietes d'un fluide incompressible plus:
N : indice de structure
K : consistance du fluide
La viscosite dynamique dans ce cas depend de K, N et Grad(U)
Nouveau fluide. c'est un fluide incompressible non newtonien. Il derive donc
de fluide_Incompressible et possede quelques proprietes de plus (K, N)
mu depend de K, N, et de grad(U)
Definition at line 41 of file Fluide_Ostwald.h.
Constructor & Destructor Documentation
Fluide_Ostwald::~Fluide_Ostwald ()
Definition at line 33 of file Fluide_Ostwald.cpp.
Fluide_Ostwald::Fluide_Ostwald ()
Definition at line 38 of file Fluide_Ostwald.cpp.
{ }
Member Function Documentation
const Champ_Don & Fluide_Ostwald::consistance () const [inline]
Definition at line 68 of file Fluide_Ostwald.h.
References K_.
Referenced by discretiser().
{
  return K_;
}
Champ_Don & Fluide_Ostwald::consistance () [inline]
Definition at line 73 of file Fluide_Ostwald.h.
References K_.
{
  return K_;
}
Objet_U * Fluide_Ostwald::cree_instance () [static]
Reimplemented from Fluide_Incompressible.
Definition at line 33 of file Fluide_Ostwald.cpp.
void Fluide_Ostwald::creer_champs_non_lus () [virtual]
Reimplemented from Fluide_base.
Definition at line 83 of file Fluide_Ostwald.cpp.
{
  Milieu_base::creer_champs_non_lus();
}
void Fluide_Ostwald::discretiser (const Probleme_base & pb, const Discretisation_base & dis) [virtual]
Reimplemented from Fluide_base.
Definition at line 65 of file Fluide_Ostwald.cpp.
References Champs_compris::ajoute_champ(), Milieu_base::champs_compris_, consistance(), Probleme_base::equation(), Navier_Stokes_std::inconnue(), Discretisation_base::nommer_completer_champ_physique(), O_U_Ptr::non_nul(), Discret_Thyd::proprietes_physiques_fluide_Ostwald(), ref_cast, Deriv_Champ_Don_base::valeur(), and Equation_base::zone_dis().
{
  const Zone_dis_base& zone_dis=pb.equation(0).zone_dis();
  const Discret_Thyd& dis2=ref_cast(Discret_Thyd, dis);
// avec la signature de Ostwald....
  const Navier_Stokes_std& eqn_hydr=ref_cast(Navier_Stokes_std,pb.equation(0));
  dis2.proprietes_physiques_fluide_Ostwald(eqn_hydr.zone_dis(),(*this),eqn_hydr,eqn_hydr.inconnue());
  Champ_Don& K = consistance();
  if (K.non_nul())
    {
      dis.nommer_completer_champ_physique(zone_dis,"consistance","kg/m/s",K.valeur(),pb);
      champs_compris_.ajoute_champ(K.valeur());
    }
  Fluide_Incompressible::discretiser(pb,dis);
}
int Fluide_Ostwald::duplique () const [virtual]
Reimplemented from Fluide_Incompressible.
Definition at line 33 of file Fluide_Ostwald.cpp.
const Type_info * Fluide_Ostwald::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Fluide_Incompressible.
Definition at line 33 of file Fluide_Ostwald.cpp.
const Champ_Don & Fluide_Ostwald::indice_struct () const [inline]
Definition at line 78 of file Fluide_Ostwald.h.
References N_.
{
  return N_;
}
Champ_Don & Fluide_Ostwald::indice_struct () [inline]
Definition at line 83 of file Fluide_Ostwald.h.
References N_.
{
  return N_;
}
const Type_info * Fluide_Ostwald::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Fluide_Incompressible.
Definition at line 33 of file Fluide_Ostwald.cpp.
int Fluide_Ostwald::initialiser (const double & temps) [virtual]
Initialise les parametres du fluide.
Reimplemented from Fluide_base.
Definition at line 96 of file Fluide_Ostwald.cpp.
{
  return Fluide_Incompressible::initialiser(temps);
}
void Fluide_Ostwald::mettre_a_jour (double temps) [virtual]
Effectue une mise a jour en temps du milieu,
et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le
nouveau temps specifie, les autres sont mis a
par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
Reimplemented from Fluide_base.
Definition at line 88 of file Fluide_Ostwald.cpp.
References K_, Champ_Don::mettre_a_jour(), N_, and O_U_Ptr::non_nul().
{
  K_.mettre_a_jour(tps);
  if (N_.non_nul() )
    N_.mettre_a_jour(tps);
  Fluide_Incompressible::mettre_a_jour(tps);
}
Sortie & Fluide_Ostwald::printOn (Sortie & os) const [protected, virtual]
Ecrit les proprietes du fluide sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Fluide_Incompressible.
Definition at line 40 of file Fluide_Ostwald.cpp.
References Milieu_base::ecrire(), finl, K_, and N_.
{
  s<<"{"<<finl;
  s<<"K"<<K_<<finl;
// s<<"beta_co"<<beta_co<<finl;
  s<<"N"<<N_<<finl;
  Milieu_base::ecrire(s);
  s<<"}"<<finl;
  return s;
}
Entree & Fluide_Ostwald::readOn (Entree & is) [protected, virtual]
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Fluide_Incompressible.
Definition at line 51 of file Fluide_Ostwald.cpp.
{
  Fluide_Incompressible::readOn(is);
  return is;
}
const Fluide_Ostwald & Fluide_Ostwald::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Fluide_Incompressible.
Definition at line 33 of file Fluide_Ostwald.cpp.
Fluide_Ostwald & Fluide_Ostwald::self_cast (Objet_U & r) [static]
Reimplemented from Fluide_Incompressible.
Definition at line 33 of file Fluide_Ostwald.cpp.
void Fluide_Ostwald::set_param (Param & param) [virtual]
Reimplemented from Fluide_base.
Definition at line 57 of file Fluide_Ostwald.cpp.
References Param::ajouter(), Param::ajouter_condition(), K_, N_, and Param::REQUIRED.
{
  Fluide_Incompressible::set_param(param);
  param.ajouter_condition("is_read_rho","Density rho has not been read for a Fluide_Ostwald type medium.");
  param.ajouter("K",&K_,Param::REQUIRED);
  param.ajouter("n",&N_,Param::REQUIRED);
}
unsigned Fluide_Ostwald::taille_memoire () const [virtual]
Reimplemented from Fluide_Incompressible.
Definition at line 33 of file Fluide_Ostwald.cpp.
Member Data Documentation
const Type_info Fluide_Ostwald::info_obj [static]
Reimplemented from Fluide_Incompressible.
Definition at line 43 of file Fluide_Ostwald.h.
Champ_Don Fluide_Ostwald::K_ [protected]
consistance lue
Definition at line 61 of file Fluide_Ostwald.h.
Referenced by consistance(), mettre_a_jour(), printOn(), and set_param().
Champ_Don Fluide_Ostwald::N_ [protected]
indice de structure lue
Definition at line 62 of file Fluide_Ostwald.h.
Referenced by indice_struct(), mettre_a_jour(), printOn(), and set_param().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Milieu/Fluide_Ostwald.h
src/ThHyd/Incompressible/Milieu/Fluide_Ostwald.cpp