TRUST: Op_Conv_EF_VEF_P1NC_Stab Class Reference
Op_Conv_EF_VEF_P1NC_Stab Class Reference
class Op_Conv_EF_VEF_P1NC_Stab
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VEF
Le champ convecte est scalaire ou vecteur de type Champ_P1NC
Le schema de convection est isu du papier
"High-resolution FEM-TVD schemes based on a fully multidimensional flux limiter"
D.Kuzmin and S.Turek.
On herite de Op pour recuperer l'implicitation amont
#include <Op_Conv_EF_VEF_P1NC_Stab.h>
Public Member Functions
Op_Conv_EF_VEF_P1NC_Stab ()
~Op_Conv_EF_VEF_P1NC_Stab ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void remplir_fluent (DoubleVect &) const override
int is_compressible () const
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Public Member Functions inherited from Op_Conv_VEF_Face
~Op_Conv_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Op_Conv_VEF_Face ()
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
void remplir_fluent (DoubleVect &) const override
void dimensionner (Matrice_Morse &) const override
on dimensionne notre matrice au moyen de la methode dimensionner de la classe
Op_VEF_Face.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
On modifie le second membre et la matrice dans le cas des
conditions de dirichlet.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
on assemble la matrice des inconnues implicite.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void get_ordre (int &) const
void get_type_lim (Motcle &) const
void get_alpha (double &) const
void get_type_op (int &) const
Public Member Functions inherited from Op_Conv_VEF_base
Op_Conv_VEF_base ()
~Op_Conv_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_vitesse (const Champ_base &) override
const Champ_Inc_base & vitesse () const
Champ_Inc_base & vitesse ()
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
void abortTimeStep () override
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_dt_local (DoubleTab &) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_fluent (DoubleVect &) const
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_zone_cl_dis (const Zone_Cl_dis_base &) override
int phi_u_transportant (const Equation_base &eq) const
definit si l'on convecte psi avec phi*u ou avec u
Public Member Functions inherited from Operateur_Conv_base
Operateur_Conv_base ()
initialise dt_stab_conv a -123
~Operateur_Conv_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_vitesse (const Champ_base &vit)=0
double dt_stab_conv () const
void fixer_dt_stab_conv (double dt)
virtual void associer_norme_vitesse (const Champ_base &norme_vitesse)
virtual void associer_vitesse_pour_pas_de_temps (const Champ_base &vitesse)
virtual void set_incompressible (const int)
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Conv_EF_VEF_P1NC_Stab & self_cast (Objet_U &)
static const Op_Conv_EF_VEF_P1NC_Stab & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Conv_VEF_Face
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Conv_VEF_Face & self_cast (Objet_U &)
static const Op_Conv_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Conv_VEF_base
static const Type_info * info ()
static Op_Conv_VEF_base & self_cast (Objet_U &)
static const Op_Conv_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Conv_base
static const Type_info * info ()
static Operateur_Conv_base & self_cast (Objet_U &)
static const Operateur_Conv_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Conv_VEF_Face
static const Type_info info_obj
Static Public Attributes inherited from Op_Conv_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Conv_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Conv_VEF_Face
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Private Member Functions
void calculer_flux_bords (const DoubleTab &, const DoubleTab &, const DoubleTab &) const
void reinit_conv_pour_Cl (const DoubleTab &, const IntList &, const DoubleTabs &, const DoubleTab &, DoubleTab &) const
void calculer_coefficients_operateur_centre (DoubleTab &, const int, const DoubleTab &vitesse) const
DoubleTab & ajouter_partie_compressible (const DoubleTab &, DoubleTab &, const DoubleTab &vitesse) const
DoubleTab & ajouter_operateur_centre (const DoubleTab &, const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_diffusion (const DoubleTab &, const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_antidiffusion (const DoubleTab &, const DoubleTab &, DoubleTab &) const
void calculer_senseur (const DoubleTab &, const DoubleVect &, const int, const int, const IntTab &, const IntTab &, const IntTab &, ArrOfDouble &, ArrOfDouble &, ArrOfDouble &, ArrOfDouble &) const
void mettre_a_jour_pour_periodicite (DoubleTab &) const
void ajouter_old (const DoubleTab &, DoubleTab &, const DoubleTab &vitesse) const
void calculer_data_pour_dirichlet ()
void ajouter_contribution_operateur_centre (const DoubleTab &, const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_diffusion (const DoubleTab &, const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_antidiffusion (const DoubleTab &, const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_partie_compressible (const DoubleTab &, const DoubleTab &, Matrice_Morse &) const
void test (const DoubleTab &, const DoubleTab &, const DoubleTab &vitesse) const
void test_difference_Kij (const DoubleTab &, DoubleTab &, DoubleTab &, const DoubleTab &vitesse) const
void test_difference_resu (const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &vitesse) const
void test_implicite () const
Private Attributes
IntTab elem_nb_faces_dirichlet_
IntTab elem_faces_dirichlet_
ArrOfDouble alpha_tab
ArrOfDouble beta
vaut zero pour les faces ou l'on souhaite degenerer en Amont. mutable DoubleTab limiteurs_;//tableau stockant pour chaque face la moyenne algebrique du limiteur
double alpha_
int is_compressible_
int test_
int old_
int volumes_etendus_
bool sous_zone
Cas d'une sous-zone a definir pour que l'EF_Stab degenere en Amont.
int new_jacobienne_
Nom nom_sous_zone
Ref_Sous_zone_VF la_sous_zone_dis
int nb_ssz_alpha
DoubleVect alpha_ssz
Noms noms_ssz_alpha
bool ssz_alpha
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Protected Types inherited from Op_Conv_VEF_Face
enum type_operateur { amont , muscl , centre }
Protected Attributes inherited from Op_Conv_VEF_Face
Motcle type_lim
int ordre
double alpha_
type_operateur type_op
double(* LIMITEUR)(double, double)
ArrOfInt traitement_pres_bord_
ArrOfInt est_une_face_de_dirichlet_
Protected Attributes inherited from Op_Conv_VEF_base
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base vitesse_
DoubleVect fluent
tableau qui sert pour le calcul du pas de temps de stabilite
int jeton
int roue
Protected Attributes inherited from Operateur_Conv_base
Ref_Champ_base la_norme_vitesse
Ref_Champ_base vitesse_pour_pas_de_temps_
double dt_stab_conv_
int incompressible_ = 1
incompressible_= 1 -> l'operateur discretise div(v x inco), incompressible_ = 0 -> il discretise v.grad(inco)
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Op_Conv_EF_VEF_P1NC_Stab
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VEF
Le champ convecte est scalaire ou vecteur de type Champ_P1NC
Le schema de convection est isu du papier
"High-resolution FEM-TVD schemes based on a fully multidimensional flux limiter"
D.Kuzmin and S.Turek.
On herite de Op pour recuperer l'implicitation amont
Definition at line 43 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Constructor & Destructor Documentation
Op_Conv_EF_VEF_P1NC_Stab()
Op_Conv_EF_VEF_P1NC_Stab::Op_Conv_EF_VEF_P1NC_Stab ()
Definition at line 37 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
~Op_Conv_EF_VEF_P1NC_Stab()
Op_Conv_EF_VEF_P1NC_Stab::~Op_Conv_EF_VEF_P1NC_Stab ()
Definition at line 37 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Conv_EF_VEF_P1NC_Stab::ajouter (const DoubleTab & transporte_2, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 550 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  DoubleTab sauv(resu);
  resu=0;
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Champ_P1NC& la_vitesse=ref_cast( Champ_P1NC, vitesse_.valeur());
  const DoubleTab& vitesse_2=la_vitesse.valeurs();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const int marq=phi_u_transportant(equation());
  const int nb_faces_elem=elem_faces.dimension(1);
  assert(nb_faces_elem==(dimension+1));
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  int nb_comp=resu.line_size();
  DoubleTab transporte_;
  DoubleTab vitesse_face_;
// soit on a transporte=phi*transporte_ et vitesse=vitesse_
// soit transporte=transporte_ et vitesse=phi*vitesse_
// cela depend si on transporte avec phi u ou avec u.
  const DoubleTab& tab_vitesse=modif_par_porosite_si_flag(vitesse_2,vitesse_face_,marq,porosite_face);
  DoubleTab Kij(nb_elem_tot,nb_faces_elem,nb_faces_elem);
// Pour tenir compte des conditions de Neumann sortie libre
  IntList NeumannFaces;
  DoubleTabs ValeursNeumannFaces;
// soit on a transporte=phi*transporte_ et vitesse=vitesse_
// soit transporte=transporte_ et vitesse=phi*vitesse_
// cela depend si on transporte avec phi u ou avec u.
  const DoubleTab& transporte=modif_par_porosite_si_flag(transporte_2,transporte_,!marq,porosite_face);
// Initialisation du tableau flux_bords_ pour le calcul des pertes de charge
  flux_bords_.resize(zone_VEF.nb_faces_bord(),nb_comp);
  calculer_flux_bords(Kij,tab_vitesse,transporte);
  if (!old_)
    {
// statistiques().begin_count(m1);
      calculer_coefficients_operateur_centre(Kij,nb_comp,tab_vitesse);
// statistiques().end_count(m1);
// statistiques().begin_count(m2);
      if (is_compressible_) ajouter_partie_compressible(transporte,resu,tab_vitesse);
      ajouter_operateur_centre(Kij,transporte,resu);
      ajouter_diffusion(Kij,transporte,resu);
// statistiques().end_count(m2);
// statistiques().begin_count(m3);
      ajouter_antidiffusion(Kij,transporte,resu);
// statistiques().end_count(m3);
      mettre_a_jour_pour_periodicite(resu);
    }
  else
    {
      assert(old_==1);
      ajouter_old(transporte,resu,tab_vitesse);
    }
  reinit_conv_pour_Cl(transporte,NeumannFaces,ValeursNeumannFaces,tab_vitesse,resu);
  resu+=sauv;
  if (test_) test(transporte,resu,tab_vitesse);
  modifier_flux(*this);
  return resu;
}
References ajouter_antidiffusion(), ajouter_diffusion(), ajouter_old(), ajouter_operateur_centre(), ajouter_partie_compressible(), calculer_coefficients_operateur_centre(), calculer_flux_bords(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Operateur_base::flux_bords_, is_compressible_, Op_Conv_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), mettre_a_jour_pour_periodicite(), modif_par_porosite_si_flag(), Op_VEF_Face::modifier_flux(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces_bord(), old_, Op_Conv_VEF_base::phi_u_transportant(), Zone_VF::porosite_face(), ref_cast, reinit_conv_pour_Cl(), TRUSTTab< _TYPE_ >::resize(), test(), test_, transporte_, Ref_Champ_Inc_base::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc_base::valeurs(), and Op_Conv_VEF_base::vitesse_.
ajouter_antidiffusion()
DoubleTab & Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion (const DoubleTab & Kij, const DoubleTab & transporte, DoubleTab & resu) const private
Definition at line 844 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=elem_faces.line_size();
  const int nb_comp=transporte.line_size();
  int elem=0, facei=0,facei_loc=0, facej=0,facej_loc=0, ligne=0,colonne=0, dim=0, face_amont=0,face_aval=0;
  double kij=0.,kji=0.,dij=0.,lij=0.,lji=0., limit=0.,daij=0., delta=0.;
  double coeffij=0.,coeffji=0., coeff=0., R=0.;
// Pour le limiteur
  ArrOfDouble P_plus(nb_comp),P_moins(nb_comp);
  ArrOfDouble Q_plus(nb_comp),Q_moins(nb_comp);
  P_plus=0., P_moins=0.;
  Q_plus=0., Q_moins=0.;
  const DoubleVect& transporteV = transporte;
  DoubleVect& resuV = resu;
  const IntTab& num_fac_loc = zone_VEF.get_num_fac_loc();
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        P_plus=0., P_moins=0.;
        Q_plus=0., Q_moins=0.;
        calculer_senseur(Kij,transporteV,nb_comp,facei,elem_faces,face_voisins,num_fac_loc,P_plus,P_moins,Q_plus,Q_moins);
        for (facej_loc=0; facej_loc<nb_faces_elem; facej_loc++)
          if (facej_loc!=facei_loc)
            {
              facej=elem_faces(elem,facej_loc);
              kij = Kij(elem,facei_loc,facej_loc);
              kji = Kij(elem,facej_loc,facei_loc);
              dij = Dij(elem,facei_loc,facej_loc,Kij);
              lij = kij+dij;
              lji = kji+dij;
              assert(lij>=0);
              assert(lji>=0);
              if (lij<=lji) //facei est amont
                {
                  face_amont = facei;
                  face_aval = facej;
// Si lij==lji, on passe deux foix dans la boucle
// d'ou la presence du coefficient 1/2
                  coeff = 1.*(lij<lji)+0.5*(lij==lji);
                  assert(coeff==1. || coeff==0.5);
                  for (dim=0; dim<nb_comp; dim++)
                    {
                      ligne=face_aval*nb_comp+dim;
                      colonne=face_amont*nb_comp+dim;
                      delta = transporteV[colonne]-transporteV[ligne];
// Limiteur de pente
// if (delta>=0.) R = (P_plus(dim)==0.) ? 0. : Q_plus(dim)/P_plus(dim);
// else R = (P_moins(dim)==0.) ? 0. : Q_moins(dim)/P_moins(dim);
// if (delta>=0.) R = (P_plus(dim)==0.) ? 0. : Q_plus(dim)/(P_plus(dim)+DMINFLOAT);
// else R = (P_moins(dim)==0.) ? 0. : Q_moins(dim)/(P_moins(dim)+DMINFLOAT);
                      if (delta>=0.) R = (std::fabs(P_plus[dim])<DMINFLOAT) ? 0. : Q_plus[dim]/P_plus[dim];
                      else R = (std::fabs(P_moins[dim])<DMINFLOAT) ? 0. : Q_moins[dim]/P_moins[dim];
                      limit=limiteur(R);
// limiteurs_(facei,dim)+=limit;
// limiteurs_(facej,dim)+=limit;
                      daij=minimum(limit*dij,lji);
                      assert(daij>=0);
                      assert(daij<=lji);
                      coeffij=alpha_tab[face_amont]*beta[face_amont]*daij;
                      coeffji=alpha_tab[face_aval]*beta[face_aval]*daij;
// Calcul de resu
                      resuV[colonne]+=coeffij*coeff*delta;
                      resuV[ligne]-=coeffji*coeff*delta;
                    }
                }
            }
      }
  return resu;
}
References alpha_tab, beta, calculer_senseur(), coeff, Dij(), DMINFLOAT, Zone_VF::elem_faces(), Zone_VF::face_voisins(), Zone_VF::get_num_fac_loc(), Op_Conv_VEF_base::la_zone_vef, limiteur(), TRUSTVect< _TYPE_ >::line_size(), minimum(), Zone_dis_base::nb_elem_tot(), and Ref_Zone_VEF::valeur().
Referenced by ajouter(), test_difference_resu(), and test_implicite().
ajouter_contribution()
void Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution (const DoubleTab & transporte_2, Matrice_Morse & matrice) const
Definition at line 2182 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  if (new_jacobienne_==0)
    {
      Op_Conv_VEF_Face::ajouter_contribution(transporte_2, matrice) ;
      return;
    }
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  const int nb_comp=transporte_2.line_size();
  DoubleTab Kij(nb_elem_tot,nb_faces_elem,nb_faces_elem);
  Kij=0.;
//
// Pour tenir compte de la porosite
//
  const Champ_P1NC& la_vitesse=ref_cast( Champ_P1NC, vitesse_.valeur());
  const DoubleTab& vitesse_2=la_vitesse.valeurs();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  DoubleTab transporte_;
  DoubleTab vitesse_face_;
// soit on a transporte=phi*transporte_ et vitesse=vitesse_
// soit transporte=transporte_ et vitesse=phi*vitesse_
// cela depend si on transporte avec phi u ou avec u.
  const int marq=phi_u_transportant(equation());
  const DoubleTab& transporte=modif_par_porosite_si_flag(transporte_2,transporte_,!marq,porosite_face);
  const DoubleTab& tab_vitesse=modif_par_porosite_si_flag(vitesse_2,vitesse_face_,marq,porosite_face);
  calculer_coefficients_operateur_centre(Kij,nb_comp,tab_vitesse);
  if (is_compressible_) ajouter_contribution_partie_compressible(transporte,tab_vitesse,matrice);
  ajouter_contribution_operateur_centre(Kij,transporte,matrice);
  ajouter_contribution_diffusion(Kij,transporte,matrice);
  if (test_) test_implicite();
}
References Op_Conv_VEF_Face::ajouter_contribution(), ajouter_contribution_diffusion(), ajouter_contribution_operateur_centre(), ajouter_contribution_partie_compressible(), calculer_coefficients_operateur_centre(), MorEqn::equation(), is_compressible_, Op_Conv_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), modif_par_porosite_si_flag(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), new_jacobienne_, Op_Conv_VEF_base::phi_u_transportant(), Zone_VF::porosite_face(), ref_cast, test_, test_implicite(), transporte_, Ref_Champ_Inc_base::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc_base::valeurs(), Op_Conv_VEF_base::vitesse_, and Zone_dis_base::zone().
Referenced by contribuer_a_avec().
ajouter_contribution_antidiffusion()
void Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion (const DoubleTab & Kij, const DoubleTab & transporte, Matrice_Morse & matrice) const private
Definition at line 2601 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=elem_faces.line_size();
  const int nb_bord=zone_Cl_VEF.nb_cond_lim();
  const int nb_comp=transporte.line_size();
  int elem=0, elem_loc=0, facei=0,facei_loc=0, faceiAss=0, ind_face=0,ind_faceiAss=0;
  int facej=0,facej_loc=0, ligne=0,colonne=0, dim=0, face_amont=0,face_aval=0;
  int faceToComplete=0, num1=0,num2=0, n_bord=0;
  double kij=0.,kji=0.,dij=0., lij=0.,lji=0., daij=0.;
  double delta=0., coeffij=0.,coeffji=0., coeff=0., R=0.;
// Pour le limiteur
  ArrOfDouble P_plus(nb_comp),P_moins(nb_comp);
  ArrOfDouble Q_plus(nb_comp),Q_moins(nb_comp);
  P_plus=0., P_moins=0., Q_plus=0., Q_moins=0.;
  const DoubleVect& transporteV = transporte;
  const IntTab& num_fac_loc = zone_VEF.get_num_fac_loc();
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        P_plus=0., P_moins=0., Q_plus=0., Q_moins=0.;
        calculer_senseur(Kij,transporteV,nb_comp,facei,elem_faces,face_voisins,num_fac_loc,P_plus,P_moins,Q_plus,Q_moins);
        for (facej_loc=0; facej_loc<nb_faces_elem; facej_loc++)
          if (facej_loc!=facei_loc)
            {
              facej=elem_faces(elem,facej_loc);
              kij = Kij(elem,facei_loc,facej_loc);
              kji = Kij(elem,facej_loc,facei_loc);
              dij = Dij(elem,facei_loc,facej_loc,Kij);
              lij = kij+dij;
              lji = kji+dij;
              assert(lij>=0);
              assert(lji>=0);
              if (lij<=lji) //facei est amont
                {
                  face_amont = facei;
                  face_aval = facej;
// Si lij==lji, on passe deux foix dans la boucle
// d'ou la presence du coefficient 1/2
                  coeff = 1.*(lij<lji)+0.5*(lij==lji);
                  assert(coeff==1. || coeff==0.5);
                  for (dim=0; dim<nb_comp; dim++)
                    {
                      ligne=face_amont*nb_comp+dim;
                      colonne=face_aval*nb_comp+dim;
                      delta=transporteV[ligne]-transporteV[colonne];
// Limiteur de pente
// if (delta>=0.) R=(P_plus(dim)==0.) ? 0. : Q_plus(dim)/P_plus(dim);
// else  R=(P_moins(dim)==0.) ? 0. : Q_moins(dim)/P_moins(dim);
// if (delta>=0.) R=(P_plus(dim)==0.) ? 0. : Q_plus(dim)/(P_plus(dim)+DMINFLOAT);
// else  R=(P_moins(dim)==0.) ? 0. : Q_moins(dim)/(P_moins(dim)+DMINFLOAT);
                      if (delta>=0.) R=(std::fabs(P_plus[dim])<DMINFLOAT) ? 0. : Q_plus[dim]/P_plus[dim];
                      else  R=(std::fabs(P_moins[dim])<DMINFLOAT) ? 0. : Q_moins[dim]/P_moins[dim];
                      daij=minimum(limiteur(R)*dij,lji);
                      assert(daij>=0);
                      assert(daij<=lji);
                      coeffij=alpha_tab[face_amont]*beta[face_amont]*daij;
                      coeffji=alpha_tab[face_aval]*beta[face_aval]*daij;
// Calcul de la matrice
                      matrice(ligne,ligne)-=coeffij*coeff;
                      matrice(ligne,colonne)+=coeffij*coeff;
                      matrice(colonne,colonne)-=coeffji*coeff;
                      matrice(colonne,ligne)+=coeffji*coeff;
                    }
                }
            }
      }
//
// Pour la periodicite
//
  for (n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2=le_bord.nb_faces();//pour ne parcourir que les faces reelles
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
// Pour le limiteur
          ArrOfDouble Pj_plus(nb_comp),Pj_moins(nb_comp);
          ArrOfDouble Qj_plus(nb_comp),Qj_moins(nb_comp);
          Pj_plus=0., Pj_moins=0.;
          Qj_plus=0., Qj_moins=0.;
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei=le_bord.num_face(ind_face);
              ind_faceiAss=la_cl_perio.face_associee(ind_face);
              faceiAss=le_bord.num_face(ind_faceiAss);
// Pour ne parcourir qu'une seule fois les faces perio
              if (facei<faceiAss)
                for (elem_loc=0; elem_loc<2; elem_loc++)
                  {
                    elem=face_voisins(facei,elem_loc);
                    assert(elem!=-1);
// Calcul du numero local de la face dans "elem"
                    facei_loc=num_fac_loc(facei,elem_loc);
                    if (facei_loc!=-1)
                      faceToComplete=faceiAss;
                    else
                      {
                        faceToComplete=facei;
                        facei_loc=num_fac_loc(faceiAss,elem_loc);
                        assert(facei_loc!=-1);
                      }
// Calcul du coefficient a rajouter dans la matrice
                    P_plus=0., P_moins=0.;
                    Q_plus=0., Q_moins=0.;
                    calculer_senseur(Kij,transporteV,nb_comp,faceToComplete,elem_faces,face_voisins,num_fac_loc,P_plus,P_moins,Q_plus,Q_moins);
                    for (facej_loc=0; facej_loc<nb_faces_elem; facej_loc++)
                      if (facej_loc!=facei_loc)
{
                          facej=elem_faces(elem,facej_loc);
                          kij = Kij(elem,facei_loc,facej_loc);
                          kji = Kij(elem,facej_loc,facei_loc);
                          dij = Dij(elem,facei_loc,facej_loc,Kij);
                          lij = kij+dij;
                          lji = kji+dij;
                          assert(lij>=0);
                          assert(lji>=0);
                          if (lij<=lji) //faceToComplete est amont
{
                              face_amont=faceToComplete;
                              face_aval=facej;
// Si lij==lji, on passe deux foix dans la boucle
// d'ou la presence du coefficient 1/2
                              coeff = 1.*(lij<lji)+0.5*(lij==lji);
                              assert(coeff==1. || coeff==0.5);
                              for (dim=0; dim<nb_comp; dim++)
{
                                  ligne=face_amont*nb_comp+dim;
                                  colonne=face_aval*nb_comp+dim;
                                  delta=transporteV[ligne]-transporteV[colonne];
// Limiteur de pente
// if (delta>=0.) R=(P_plus(dim)==0.) ? 0. : Q_plus(dim)/P_plus(dim);
// else  R=(P_moins(dim)==0.) ? 0. : Q_moins(dim)/P_moins(dim);
// if (delta>=0.) R=(P_plus(dim)==0.) ? 0. : Q_plus(dim)/(P_plus(dim)+DMINFLOAT);
// else  R=(P_moins(dim)==0.) ? 0. : Q_moins(dim)/(P_moins(dim)+DMINFLOAT);
                                  if (delta>=0.) R=(std::fabs(P_plus[dim])<DMINFLOAT) ? 0. : Q_plus[dim]/P_plus[dim];
                                  else  R=(std::fabs(P_moins[dim])<DMINFLOAT) ? 0. : Q_moins[dim]/P_moins[dim];
                                  daij=minimum(limiteur(R)*dij,lji);
                                  assert(daij>=0);
                                  assert(daij<=lji);
                                  coeffij=alpha_tab[face_amont]*beta[face_amont]*daij;
// Calcul de la matrice
                                  matrice(ligne,ligne)-=coeffij*coeff;
                                  matrice(ligne,colonne)+=coeffij*coeff;
                                }
                            }
                          else  //faceToComplete est aval
{
                              face_aval=faceToComplete;
                              face_amont=facej;
                              coeff=1.;
                              Pj_plus=0., Pj_moins=0., Qj_plus=0., Qj_moins=0.;
                              calculer_senseur(Kij,transporteV,nb_comp,facej,elem_faces,face_voisins,num_fac_loc,Pj_plus,Pj_moins,Qj_plus,Qj_moins);
                              for (dim=0; dim<nb_comp; dim++)
{
                                  ligne=face_amont*nb_comp+dim;
                                  colonne=face_aval*nb_comp+dim;
                                  delta=transporteV[ligne]-transporteV[colonne];
// Limiteur de pente
// if (delta>=0.) R=(Pj_plus(dim)==0.) ? 0. : Qj_plus(dim)/Pj_plus(dim);
// else  R=(Pj_moins(dim)==0.) ? 0. : Qj_moins(dim)/Pj_moins(dim);
// if (delta>=0.) R=(Pj_plus(dim)==0.) ? 0. : Qj_plus(dim)/(Pj_plus(dim)+DMINFLOAT);
// else  R=(Pj_moins(dim)==0.) ? 0. : Qj_moins(dim)/(Pj_moins(dim)+DMINFLOAT);
                                  if (delta>=0.) R=(std::fabs(Pj_plus[dim])<DMINFLOAT) ? 0. : Qj_plus[dim]/Pj_plus[dim];
                                  else  R=(std::fabs(Pj_moins[dim])<DMINFLOAT) ? 0. : Qj_moins[dim]/Pj_moins[dim];
                                  daij=minimum(limiteur(R)*dij,lij);
                                  assert(daij>=0);
                                  assert(daij<=lij);
                                  coeffij=alpha_tab[face_aval]*beta[face_aval]*daij;
// Calcul de la matrice
                                  matrice(colonne,colonne)-=coeffij*coeff;
                                  matrice(colonne,ligne)+=coeffij*coeff;
                                }
                            }
                        }
                  }
            }
        }
    }
}
References alpha_tab, beta, calculer_senseur(), coeff, Dij(), DMINFLOAT, Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Zone_VF::get_num_fac_loc(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), limiteur(), TRUSTVect< _TYPE_ >::line_size(), minimum(), Zone_Cl_dis_base::nb_cond_lim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Front_VF::num_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
Referenced by test_implicite().
ajouter_contribution_diffusion()
void Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion (const DoubleTab & Kij, const DoubleTab & transporte, Matrice_Morse & matrice) const private
Definition at line 2341 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=elem_faces.line_size();
  const int nb_bord=zone_Cl_VEF.nb_cond_lim();
  const int nb_comp=transporte.line_size();
  int elem=0, facei=0,facei_loc=0, facej=0,facej_loc=0;
  int ligne=0,colonne=0, dim=0, ind_face=0, num1=0,num2=0;
  int faceToComplete=0, elem_loc=0;
  double dij=0., coeffij=0.,coeffji=0.;
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
          {
            facej=elem_faces(elem,facej_loc);
            assert(facej!=facei);
            dij=Dij(elem,facei_loc,facej_loc,Kij);
            assert(dij>=0);
            coeffij=alpha_tab[facei]*dij;
            coeffji=alpha_tab[facej]*dij;
            for (dim=0; dim<nb_comp; dim++)
              {
                ligne=facei*nb_comp+dim;
                colonne=facej*nb_comp+dim;
// ATTENTION AU SIGNE : ici on code +div(uT)
// REMARQUE : on utilise la symetrie de l'operateur
                matrice(ligne,ligne)+=coeffij;
                matrice(ligne,colonne)-=coeffij;
                matrice(colonne,colonne)+=coeffji;
                matrice(colonne,ligne)-=coeffji;
              }
          }
      }
//
// Pour la periodicite
//
  const IntTab& num_fac_loc = zone_VEF.get_num_fac_loc();
  for (int n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2=le_bord.nb_faces_tot();//et surtout pas nb_faces() sinon on oublie certains coefficiens
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int faceiAss=0,ind_faceiAss=0;
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei=le_bord.num_face(ind_face);
              ind_faceiAss=la_cl_perio.face_associee(ind_face);
              faceiAss=le_bord.num_face(ind_faceiAss);
// Pour ne parcourir qu'une seule fois les faces perio
              if (facei<faceiAss)
                for (elem_loc=0; elem_loc<2; elem_loc++)
                  {
                    elem=face_voisins(facei,elem_loc);
                    assert(elem!=-1);
// Calcul du numero local de la face dans "elem"
                    facei_loc=num_fac_loc(facei,elem_loc);
                    if (facei_loc!=-1)
                      faceToComplete=faceiAss;
                    else
                      {
                        faceToComplete=facei;
                        facei_loc=num_fac_loc(faceiAss,elem_loc);
                        assert(facei_loc!=-1);
                      }
// Calcul des coefficients de la matrice dus a "elem"
                    for (facej_loc=0; facej_loc<nb_faces_elem; facej_loc++)
                      {
                        facej=elem_faces(elem,facej_loc);
                        if (facej_loc!=facei_loc)
{
                            dij=Dij(elem,facei_loc,facej_loc,Kij);
                            assert(dij>=0);
                            coeffij=alpha_tab[faceToComplete]*dij;
                            coeffji=alpha_tab[facej]*dij;
                            for (dim=0; dim<nb_comp; dim++)
{
                                ligne=faceToComplete*nb_comp+dim;
                                colonne=facej*nb_comp+dim;
// ATTENTION AU SIGNE : ici on code +div(uT)
                                matrice(ligne,ligne)+=coeffij;
                                matrice(ligne,colonne)-=coeffij;
                              }
                          }
                      }
                  }
            }
        }
    }
}
References alpha_tab, Dij(), Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Zone_VF::get_num_fac_loc(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Zone_Cl_dis_base::nb_cond_lim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
Referenced by ajouter_contribution(), and test_implicite().
ajouter_contribution_operateur_centre()
void Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre (const DoubleTab & Kij, const DoubleTab & transporte, Matrice_Morse & matrice) const private
Definition at line 2227 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=elem_faces.dimension(1);
  const int nb_bord=zone_Cl_VEF.nb_cond_lim();
  const int nb_comp=transporte.line_size();
  int elem=0, facei=0,facei_loc=0, facej=0,facej_loc=0;
  int ligne=0,colonne=0, dim=0, ind_face=0, num1=0,num2=0;
  int faceToComplete=0, elem_loc=0;
  double kij=0.,kji=0.;
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
          {
            facej=elem_faces(elem,facej_loc);
            assert(facej!=facei);
            kij=Kij(elem,facei_loc,facej_loc);
            kji=Kij(elem,facej_loc,facei_loc);
            for (dim=0; dim<nb_comp; dim++)
              {
                ligne=facei*nb_comp+dim;
                colonne=facej*nb_comp+dim;
// ATTENTION AU SIGNE : ici on code +div(uT)
                matrice(ligne,ligne)+=kij;
                matrice(ligne,colonne)-=kij;
                matrice(colonne,colonne)+=kji;
                matrice(colonne,ligne)-=kji;
              }
          }
      }
//
// Pour la periodicite
//
  const IntTab& num_fac_loc = zone_VEF.get_num_fac_loc();
  for (int n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2=le_bord.nb_faces_tot();//et surtout pas nb_faces sinon on oublie certains coefficients
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int faceiAss=0,ind_faceiAss=0;
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              ind_faceiAss=la_cl_perio.face_associee(ind_face);
              facei=le_bord.num_face(ind_face);
              faceiAss=le_bord.num_face(ind_faceiAss);
// Pour ne parcourir qu'une seule fois les faces perio
              if (facei<faceiAss)
                for (elem_loc=0; elem_loc<2; elem_loc++)
                  {
                    elem=face_voisins(facei,elem_loc);
                    assert(elem!=-1);
// Calcul du numero local de la face dans "elem"
                    facei_loc=num_fac_loc(facei,elem_loc);
                    if (facei_loc!=-1)
                      faceToComplete=faceiAss;
                    else
                      {
                        faceToComplete=facei;
                        facei_loc=num_fac_loc(faceiAss,elem_loc);
                        assert(facei_loc!=-1);
                      }
// Calcul des coefficients de la matrice dus a "elem"
                    for (facej_loc=0; facej_loc<nb_faces_elem; facej_loc++)
                      {
                        facej=elem_faces(elem,facej_loc);
                        if (facej_loc!=facei_loc)
{
                            kij=Kij(elem,facei_loc,facej_loc);
                            kji=Kij(elem,facej_loc,facei_loc);
                            for (dim=0; dim<nb_comp; dim++)
{
                                ligne=faceToComplete*nb_comp+dim;
                                colonne=facej*nb_comp+dim;
// ATTENTION AU SIGNE : ici on code +div(uT)
                                matrice(ligne,ligne)+=kij;
                                matrice(ligne,colonne)-=kij;
                              }
                          }
                      }
                  }
            }
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Zone_VF::get_num_fac_loc(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Zone_Cl_dis_base::nb_cond_lim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
Referenced by ajouter_contribution(), and test_implicite().
ajouter_contribution_partie_compressible()
void Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible (const DoubleTab & transporte, const DoubleTab & vitesse_2, Matrice_Morse & matrice) const private
Definition at line 2465 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=elem_faces.line_size();
  const int nb_bord=zone_Cl_VEF.nb_cond_lim();
// Pour tenir compte de la porosite
  const int marq = phi_u_transportant(equation());
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  DoubleTab tab_vitesse(vitesse_.valeur().valeurs());
  for (int i=0; i<tab_vitesse.dimension(0); i++)
    for (int j=0; j<tab_vitesse.line_size(); j++)
      tab_vitesse(i,j)*=porosite_face(i);
  const int nb_comp=transporte.line_size();
  int elem=0,type_elem=0, facei=0,facei_loc=0, faceiAss=0,ind_faceiAss=0;
  int ligne=0, dim=0, ind_face=0, num1=0,num2=0, faceToComplete=0, elem_loc=0, n_bord=0;
  double coeff=0., signe=0., div=0.;
  double (*formule)(int);
  if (!volumes_etendus_)
    formule= (dimension==2) ? &formule_Id_2D : &formule_Id_3D;
  else
    formule= (dimension==2) ? &formule_2D : &formule_3D;
  for (elem=0; elem<nb_elem_tot; elem++)
    {
// Type de l'element : le nombre de faces de Dirichlet
// qu'il contient
      type_elem=elem_nb_faces_dirichlet_(elem);
      coeff=formule(type_elem);
// Calcul de la divergence par element
      div=0.;
      for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
        {
          facei=elem_faces(elem,facei_loc);
          signe=(face_voisins(facei,0)==elem)? 1.:-1.;
          for (dim=0; dim<dimension; dim++)
            div+=signe*face_normales(facei,dim)*tab_vitesse(facei,dim);
        }
      div*=coeff;
      if (!marq) div/=porosite_elem(elem);
// Calcul de la partie compressible
      for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
        {
          facei=elem_faces(elem,facei_loc);
          for (dim=0; dim<nb_comp; dim++)
            {
              ligne=facei*nb_comp+dim;
              matrice(ligne,ligne)+=div;
            }
        }
    }
//
// Pour la periodicite
//
  const IntTab& num_fac_loc = zone_VEF.get_num_fac_loc();
  for (n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2=le_bord.nb_faces();//pour ne parcourir que les faces reelles
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei=le_bord.num_face(ind_face);
              ind_faceiAss=la_cl_perio.face_associee(ind_face);
              faceiAss=le_bord.num_face(ind_faceiAss);
// Pour ne parcourir qu'une seule fois les faces perio
              if (facei<faceiAss)
                for (elem_loc=0; elem_loc<2; elem_loc++)
                  {
                    elem=face_voisins(facei,elem_loc);
                    assert(elem!=-1);
// Calcul du numero local de la face dans "elem"
                    facei_loc=num_fac_loc(facei,elem_loc);
                    if (facei_loc!=-1)
                      faceToComplete=faceiAss;
                    else
                      {
                        faceToComplete=facei;
                        facei_loc=num_fac_loc(faceiAss,elem_loc);
                        assert(facei_loc!=-1);
                      }
// Type de l'element : le nombre de faces de Dirichlet
// qu'il contient
                    type_elem=elem_nb_faces_dirichlet_(elem);
                    coeff=formule(type_elem);
// Calcul de la divergence par element
                    div=0.;
                    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
                      {
                        facei=elem_faces(elem,facei_loc);
                        signe=(face_voisins(facei,0)==elem)? 1.:-1.;
                        for (dim=0; dim<dimension; dim++)
                          div+=signe*face_normales(facei,dim)*tab_vitesse(facei,dim);
                      }
                    div*=coeff;
                    if (!marq) div/=porosite_elem(elem);
// Calcul de la partie compressible
                    for (dim=0; dim<nb_comp; dim++)
                      {
                        ligne=faceToComplete*nb_comp+dim;
                        matrice(ligne,ligne)+=div;
                      }
                  }
            }
        }
    }
}
References coeff, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), elem_nb_faces_dirichlet_, MorEqn::equation(), Periodique::face_associee(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), formule_2D(), formule_3D(), formule_Id_2D(), formule_Id_3D(), Cond_lim::frontiere_dis(), Zone_VF::get_num_fac_loc(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Zone_Cl_dis_base::nb_cond_lim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Front_VF::num_face(), Op_Conv_VEF_base::phi_u_transportant(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, sub_type, type_elem(), Deriv_Cond_lim_base::valeur(), Ref_Champ_Inc_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc_base::valeurs(), Op_Conv_VEF_base::vitesse_, and volumes_etendus_.
Referenced by ajouter_contribution(), and test_implicite().
ajouter_diffusion()
DoubleTab & Op_Conv_EF_VEF_P1NC_Stab::ajouter_diffusion (const DoubleTab & Kij, const DoubleTab & transporte, DoubleTab & resu) const private
Definition at line 799 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=elem_faces.line_size();
  const int nb_comp=transporte.line_size();
  int elem=0, facei=0,facei_loc=0, facej=0,facej_loc=0, ligne=0,colonne=0, dim=0;
  double dij=0., delta=0., coeffij=0.,coeffji=0.;
  const DoubleVect& transporteV = transporte;
  DoubleVect& resuV = resu;
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
          {
            facej=elem_faces(elem,facej_loc);
            assert(facej!=facei);
            dij=Dij(elem,facei_loc,facej_loc,Kij);
            assert(dij>=0);
            coeffij=alpha_tab[facei]*dij;
            coeffji=alpha_tab[facej]*dij;
            for (dim=0; dim<nb_comp; dim++)
              {
                ligne=facei*nb_comp+dim;
                colonne=facej*nb_comp+dim;
                delta=transporteV[colonne]-transporteV[ligne];
// ATTENTION AU SIGNE : ici on code +div(uT)
// REMARQUE : on utilise la symetrie de l'operateur
                resuV[ligne]+=coeffij*delta;
                resuV[colonne]-=coeffji*delta;
              }
          }
      }
  return resu;
}
References alpha_tab, Dij(), Zone_VF::elem_faces(), Op_Conv_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem_tot(), and Ref_Zone_VEF::valeur().
Referenced by ajouter(), test_difference_resu(), and test_implicite().
ajouter_old()
void Op_Conv_EF_VEF_P1NC_Stab::ajouter_old (const DoubleTab & transporte, DoubleTab & resu, const DoubleTab & vitesse) const private
Definition at line 1602 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
// const Champ_P1NC& la_vitesse=ref_cast(Champ_P1NC, vitesse_.valeur());
// const DoubleTab& vitesse=la_vitesse.valeurs();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const int nb_faces_elem=elem_faces.dimension(1);
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  assert(nb_faces_elem==(dimension+1));
  int nb_comp=resu.line_size();
  int face_i0, face_j0, elem0, comp0;
  DoubleTab Kij(nb_elem_tot,nb_faces_elem, nb_faces_elem);
//
// Calcul des Kij :
//
  for(elem0=0; elem0<nb_elem_tot; elem0++)
    {
      int face_loci=0;
      int face_locj=0;
      for(; face_loci<nb_faces_elem; face_loci++)
        {
          face_i0=elem_faces(elem0,face_loci);
          double signei=1.0;
          if(face_voisins(face_i0,0)!=elem0)
            signei=-1.0;
          double psci=0;
          for(comp0=0; comp0<dimension; comp0++)
            psci+=tab_vitesse(face_i0,comp0)*face_normales(face_i0,comp0);
          psci*=signei;
// Kij(elem,face_loci,face_loci)=0.;
          for(face_locj=face_loci+1; face_locj<nb_faces_elem; face_locj++)
            {
              face_j0=elem_faces(elem0,face_locj);
              double signej=1.0;
              if(face_voisins(face_j0,0)!=elem0)
                signej=-1.0;
              double pscj=0;
// psci=0;
              for(comp0=0; comp0<dimension; comp0++)
                pscj+=tab_vitesse(face_j0,comp0)*face_normales(face_j0,comp0);
              pscj*=signej;
              Kij(elem0,face_loci,face_locj)=-1./nb_faces_elem*pscj;
              Kij(elem0,face_loci,face_loci)+=1./nb_faces_elem*pscj;
              Kij(elem0,face_locj,face_loci)=-1./nb_faces_elem*psci;
              Kij(elem0,face_locj,face_locj)+=1./nb_faces_elem*psci;
            }
        }
    }
//
// Correction des Kij pour Dirichlet !
//
  {
    int nb_bord=zone_Cl_VEF.nb_cond_lim();
    int face;
    double coeff=1./dimension;
    for (int n_bord=0; n_bord<nb_bord; n_bord++)
      {
        const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
        const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
        int nb_faces_tot=le_bord.nb_faces_tot();
        if (( (sub_type(Dirichlet,la_cl.valeur())) || (sub_type(Dirichlet_homogene,la_cl.valeur())) )
            && ( volumes_etendus_))
          {
            for (int ind_face=0; ind_face<nb_faces_tot; ind_face++)
              {
                face=le_bord.num_face(ind_face);
                int elem=face_voisins(face,0);
                assert(elem!=-1);
                int face_loc_j;
                int face_j=-1;
                for (face_loc_j=0; (face_loc_j<nb_faces_elem && face_j!=face); face_loc_j++)
                  {
                    face_j=elem_faces(elem,face_loc_j);
                  }
                face_loc_j--;
                assert(face_loc_j>=0);
                assert(face_loc_j<nb_faces_elem);
                assert(elem_faces(elem,face_loc_j)==face);
                const double kjj=Kij(elem,face_loc_j,face_loc_j);
                for (int face_loc_i=0; face_loc_i<nb_faces_elem; face_loc_i++)
                  {
                    int face_i=elem_faces(elem,face_loc_i);
                    if(face_i!=face)
                      {
                        double& kii=Kij(elem,face_loc_i,face_loc_i);
                        const double kji=Kij(elem,face_loc_j,face_loc_i);
                        kii+=coeff*kji;
                        double& kij=Kij(elem,face_loc_i,face_loc_j);
                        kij+=coeff*kjj;
                        for (int face_loc_k=(face_loc_i+1); face_loc_k<nb_faces_elem; face_loc_k++)
{
                            int face_k=elem_faces(elem,face_loc_k);
                            if(face_k!=face)
{
                                double& kik=Kij(elem,face_loc_i,face_loc_k);
                                const double kjk=Kij(elem,face_loc_j,face_loc_k);
                                double& kki=Kij(elem,face_loc_k,face_loc_i);
                                kik+=coeff*kjk;
                                kki+=coeff*kji;
                              }
                          }
                      }
                  }
                {
                  for (int face_loc_i=0; face_loc_i<nb_faces_elem; face_loc_i++)
                    Kij(elem,face_loc_j,face_loc_i)=0;
                }
                {
                  for (int face_loc_i=0; face_loc_i<nb_faces_elem; face_loc_i++)
                    {
                      double sum=0.;
                      for (int face_loc_k=0; face_loc_k<nb_faces_elem; face_loc_k++)
{
                          sum+=Kij(elem,face_loc_i,face_loc_k);
                        }
// Cerr << "somme apres : " << sum << finl;
                      Kij(elem,face_loc_i,face_loc_i)-=sum;//car div(u)=0!
                    }
                }
              }//!< for face
          }//!< sub_type Dirichlet
      }
  }
//
// Calcul de resu
//
  ArrOfDouble pplusi(nb_comp);
  ArrOfDouble qplusi(nb_comp);
  ArrOfDouble pmoinsi(nb_comp);
  ArrOfDouble qmoinsi(nb_comp);
  for(elem0=0; elem0<nb_elem_tot; elem0++)
    {
      int face_loci=0;
      int face_locj=0;
      for(; face_loci<nb_faces_elem; face_loci++)
        {
          face_i0=elem_faces(elem0,face_loci);
          for(comp0=0; comp0<nb_comp; comp0++)
            resu(face_i0,comp0)+=Kij(elem0,face_loci,face_loci)*transporte(face_i0,comp0);
          pplusi=0., qplusi=0., pmoinsi=0., qmoinsi=0.;
          int elem1=face_voisins(face_i0,0);
          int elem2=face_voisins(face_i0,1);
          int face_loc_i=0;
          int face_loc_j=0;
          double dT,min_dT,max_dT;
          double K,min_K,max_K;
//
// dans elem1 :
//
          while((face_loc_i<nb_faces_elem)&&(elem_faces(elem1,face_loc_i)!=face_i0))
            face_loc_i++;
          if(face_loc_i==nb_faces_elem)
            {
// Periodique!!
              assert(elem2!=-1);
              face_loc_i=0;
              while( (face_loc_i<nb_faces_elem) &&
                     (face_voisins(elem_faces(elem1,face_loc_i),0)!=elem2) &&
                     (face_voisins(elem_faces(elem1,face_loc_i),1)!=elem2) )
                face_loc_i++;
            }
          assert(face_loc_i<nb_faces_elem);
          for(face_loc_j=0; face_loc_j<nb_faces_elem; face_loc_j++)
            {
              int face_j=elem_faces(elem1,face_loc_j);
              if(face_j!=face_i0)
                {
                  K=Kij(elem1,face_loc_i,face_loc_j);
                  if(K>0.)
                    {
                      max_K=K ;
                      min_K=0.;
                    }
                  else
                    {
                      max_K=0.;
                      min_K=K ;
                    }
                  for(comp0=0; comp0<nb_comp; comp0++)
                    {
                      dT =transporte(face_j,comp0);
                      dT-=transporte(face_i0,comp0);
                      if(dT>0.)
{
                          max_dT=dT ;
                          min_dT=0 ;
                        }
                      else
{
                          max_dT=0. ;
                          min_dT=dT ;
                        }
                      pplusi[comp0] +=min_K*min_dT;
                      pmoinsi[comp0]+=min_K*max_dT;
                      qplusi[comp0] +=max_K*max_dT;
                      qmoinsi[comp0]+=max_K*min_dT;
                    }
                }
            }
//
// dans elem2 :
//
          if(elem2!=-1)
            {
              face_loc_i=0;
              while((face_loc_i<nb_faces_elem)&&(elem_faces(elem2,face_loc_i)!=face_i0))
                face_loc_i++;
              if(face_loc_i==nb_faces_elem)
                {
// Periodique!!
                  face_loc_i=0;
                  while( (face_loc_i<nb_faces_elem) &&
                         (face_voisins(elem_faces(elem2,face_loc_i),0)!=elem1) &&
                         (face_voisins(elem_faces(elem2,face_loc_i),1)!=elem1) )
                    face_loc_i++;
                }
              assert(face_loc_i<nb_faces_elem);
              for(face_loc_j=0; face_loc_j<nb_faces_elem; face_loc_j++)
                {
                  int face_j=elem_faces(elem2,face_loc_j);
                  if(face_j!=face_i0)
                    {
                      K=Kij(elem2,face_loc_i,face_loc_j);
                      if(K>0.)
{
                          max_K=K ;
                          min_K=0.;
                        }
                      else
{
                          max_K=0.;
                          min_K=K ;
                        }
                      for(comp0=0; comp0<nb_comp; comp0++)
{
                          dT =transporte(face_j,comp0);
                          dT-=transporte(face_i0,comp0);
                          if(dT>0.)
{
                              max_dT=dT ;
                              min_dT=0 ;
                            }
                          else
{
                              max_dT=0. ;
                              min_dT=dT ;
                            }
                          pplusi[comp0] +=min_K*min_dT;
                          pmoinsi[comp0]+=min_K*max_dT;
                          qplusi[comp0] +=max_K*max_dT;
                          qmoinsi[comp0]+=max_K*min_dT;
                        }
                    }
                }
            }
          for(face_locj=0; face_locj<nb_faces_elem; face_locj++)
            if(face_locj!=face_loci)
              {
                face_j0=elem_faces(elem0,face_locj);
                const double kij=Kij(elem0,face_loci,face_locj);
                const double kji=Kij(elem0,face_locj,face_loci);
                double dij=Dij(elem0,face_loci,face_locj,Kij);
                double lji=kji+dij;
                double lij=kij+dij;
                assert(lij>=0);
                assert(lji>=0);
                for(comp0=0; comp0<nb_comp; comp0++)
                  {
                    const double Ti=transporte(face_i0,comp0);
                    const double Tj=transporte(face_j0,comp0);
                    double deltaij=Ti-Tj;
                    double Fij=0;
                    if(lij<=lji)
                      {
                        double coef=1;
                        if (lij==lji)  coef=.5;
                        if(deltaij)
{
                            if(Ti >= Tj)
{
                                if(pplusi[comp0])
{
                                    double R=qplusi[comp0]/pplusi[comp0];
                                    Fij=minimum(limiteur(R)*dij,lji);
                                  }
                              }
                            else if(pmoinsi[comp0])
{
                                double R=qmoinsi[comp0]/pmoinsi[comp0];
                                Fij=minimum(limiteur(R)*dij,lji);
                              }
                            assert(Fij*dij>=0);
                            Fij-=dij;
                            Fij*=deltaij;
                          }
                        resu(face_i0,comp0)+=coef*(kij*Tj+Fij);
                        resu(face_j0,comp0)+=coef*(kji*Ti-Fij);
                      }
                  }
              }
        }
    }
// On reprend ici le traitement qui est fait pour la CL de Neumann_sortie_libre dans Op_Conv_VEF_Face
  int nb_bord=zone_Cl_VEF.nb_cond_lim();
  int face;
  const int ncomp_ch_transporte = transporte.line_size();
  for (int n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_tot=le_bord.nb_faces_tot();
      double psc;
      int num_face,i;
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Neumann_sortie_libre& la_sortie_libre = ref_cast(Neumann_sortie_libre, la_cl.valeur());
// const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          DoubleVect& fluent_ = fluent;
          for (num_face=num1; num_face<num2; num_face++)
            {
              psc =0;
              for (i=0; i<dimension; i++)
                psc += tab_vitesse(num_face,i)*face_normales(num_face,i);
              if (psc>0)
                {
                  for (i=0; i<ncomp_ch_transporte; i++)
                    resu(num_face,i) -= psc*transporte(num_face,i);
                }
              else
                {
                  for (i=0; i<ncomp_ch_transporte; i++)
                    resu(num_face,i) -= psc*la_sortie_libre.val_ext(num_face-num1,i);
                  fluent_(num_face) -= psc;
                }
            }
        }
// Pour periodique
      else if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int face_associee,ind_face_associee;
          IntVect fait(nb_faces_tot);
          fait = 0;
          for (int ind_face=0; ind_face<nb_faces_tot; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              if (fait(ind_face) == 0)
                {
                  fait(ind_face) = 1;
                  ind_face_associee=la_cl_perio.face_associee(ind_face);
                  fait(ind_face_associee) = 1;
                  face_associee=le_bord.num_face(ind_face_associee);
                  for (int comp=0; comp<nb_comp; comp++)
                    resu(face_associee, comp)=(resu(face,comp)+=resu(face_associee,comp));
                }//!< if fait
            }//!< for face
        }//!< sub_type Perio
    }
  /*
    ArrOfDouble bilan(nb_comp);
    BilanQdmVEF::bilan_qdm(resu, zone_Cl_VEF, bilan);
    if(nb_comp==1)
    Cout << "Scalaire Bilan Convectif : " << bilan[0] << finl;
    else
    for (int comp=0; comp<nb_comp; comp++)
    Cout << "Vecteur Bilan Convectif " << comp << " : " << bilan[comp] << finl;
    bilan=0;
    BilanQdmVEF::bilan_energie(resu, transporte, zone_Cl_VEF, bilan);
    if(nb_comp==1)
    Cout << "Scalaire Bilan Convectif Energie : " << bilan[0] << finl;
    else
    for (int comp=0; comp<nb_comp; comp++)
    Cout << "Vecteur Bilan Convectif Energie " << comp << " : " << bilan[comp] << finl;
    if(nb_comp==1)
    {
    Cout << "min = " << min(transporte);
    Cout << " max = " << std::max(transporte) << finl;
    }
    //  else
    //    for (int comp=0; comp<nb_comp; comp++)
    //    {
    //      Cout << "min("<<comp<<") = " << transporte.min(comp);
    //      Cout << " std::max("<<comp<<") = " << transporte.max(comp) << finl;
    //    }
    Cout << " Ratio Antidiffusion/Diffusion = " << sigma_fija/sigma_fijd << finl;
  */
}
References coeff, Dij(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), Periodique::face_associee(), face_associee, Zone_VEF::face_normales(), Zone_VF::face_voisins(), Op_Conv_VEF_base::fluent, Cond_lim::frontiere_dis(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), limiteur(), TRUSTVect< _TYPE_ >::line_size(), minimum(), Zone_Cl_dis_base::nb_cond_lim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Front_VF::num_premiere_face(), ref_cast, sub_type, Neumann_sortie_libre::val_ext(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and volumes_etendus_.
Referenced by ajouter().
ajouter_operateur_centre()
DoubleTab & Op_Conv_EF_VEF_P1NC_Stab::ajouter_operateur_centre (const DoubleTab & Kij, const DoubleTab & transporte, DoubleTab & resu) const private
Definition at line 761 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=elem_faces.line_size();
  const int nb_comp=transporte.line_size();
  int elem=0,facei=0,facei_loc=0, facej=0,facej_loc=0, ligne=0,colonne=0, dim=0;
  double kij=0.,kji=0.,delta=0.;
  const DoubleVect& transporteV = transporte;
  DoubleVect& resuV = resu;
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
          {
            facej=elem_faces(elem,facej_loc);
            assert(facej!=facei);
            kij=Kij(elem,facei_loc,facej_loc);
            kji=Kij(elem,facej_loc,facei_loc);
            for (dim=0; dim<nb_comp; dim++)
              {
                ligne=facei*nb_comp+dim;
                colonne=facej*nb_comp+dim;
                delta=transporteV[colonne]-transporteV[ligne];
                resuV[ligne]+=kij*delta;
                resuV[colonne]-=kji*delta;
              }
          }
      }
  return resu;
}
References Zone_VF::elem_faces(), Op_Conv_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem_tot(), and Ref_Zone_VEF::valeur().
Referenced by ajouter(), test_difference_resu(), and test_implicite().
ajouter_partie_compressible()
DoubleTab & Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible (const DoubleTab & transporte, DoubleTab & resu, const DoubleTab & vitesse) const private
Definition at line 632 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=elem_faces.line_size();
// Pour tenir compte de la porosite
  const int marq = phi_u_transportant(equation());
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  DoubleTab tab_vitesse(vitesse_.valeur().valeurs());
  for (int i=0; i<tab_vitesse.dimension(0); i++)
    for (int j=0; j<tab_vitesse.dimension(1); j++)
      tab_vitesse(i,j)*=porosite_face(i);
  const int nb_comp=transporte.line_size();
  int elem=0,type_elem=0, facei=0,facei_loc=0, ligne=0, dim=0;
  double coeff=0., signe=0., div=0.;
  const DoubleVect& transporteV = transporte;
  DoubleVect& resuV = resu;
  double (*formule)(int);
  if (!volumes_etendus_)
    formule= (dimension==2) ? &formule_Id_2D : &formule_Id_3D;
  else
    formule= (dimension==2) ? &formule_2D : &formule_3D;
  for (elem=0; elem<nb_elem_tot; elem++)
    {
// Type de l'element : le nombre de faces de Dirichlet
// qu'il contient
      type_elem=elem_nb_faces_dirichlet_(elem);
      coeff=formule(type_elem);
// Calcul de la divergence par element
      div=0.;
      for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
        {
          facei=elem_faces(elem,facei_loc);
          signe=(face_voisins(facei,0)==elem)? 1.:-1.;
          for (dim=0; dim<dimension; dim++)
            div+=signe*face_normales(facei,dim)*tab_vitesse(facei,dim);
        }
      div*=coeff;
      if (!marq) div/=porosite_elem(elem);
// Calcul de la partie compressible
      for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
        {
          facei=elem_faces(elem,facei_loc);
          for (dim=0; dim<nb_comp; dim++)
            {
              ligne=facei*nb_comp+dim;
              resuV[ligne]-=div*transporteV[ligne];
            }
        }
    }
  return resu;
}
References coeff, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), elem_nb_faces_dirichlet_, MorEqn::equation(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), formule_2D(), formule_3D(), formule_Id_2D(), formule_Id_3D(), Op_Conv_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem_tot(), Op_Conv_VEF_base::phi_u_transportant(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), type_elem(), Ref_Champ_Inc_base::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc_base::valeurs(), Op_Conv_VEF_base::vitesse_, and volumes_etendus_.
Referenced by ajouter(), test_difference_resu(), and test_implicite().
calculer_coefficients_operateur_centre()
void Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre (DoubleTab & Kij, const int nb_comp, const DoubleTab & vitesse) const private
Definition at line 312 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const int nb_faces_elem=elem_faces.line_size();
  assert(Kij.nb_dim()==3);
  assert(Kij.dimension(0)==nb_elem_tot);
  assert(Kij.dimension(1)==Kij.dimension(2));
  assert(Kij.dimension(1)==nb_faces_elem);
//
// Calcul des coefficients de l'operateur
//
  for(int elem=0; elem<nb_elem_tot; elem++)
    {
      for(int face_loci=0; face_loci<nb_faces_elem; face_loci++)
        {
          int face_i=elem_faces(elem,face_loci);
          double signei=1.0;
          if(face_voisins(face_i,0)!=elem) signei=-1.0;
          double psci=0;
          for(int comp=0; comp<dimension; comp++)
            psci+=tab_vitesse(face_i,comp)*face_normales(face_i,comp);
          psci*=signei;
// Kij(elem,face_loci,face_loci)=0.;
          for(int face_locj=face_loci+1; face_locj<nb_faces_elem; face_locj++)
            {
              int face_j=elem_faces(elem,face_locj);
              double signej=1.0;
              if(face_voisins(face_j,0)!=elem)
                signej=-1.0;
              double pscj=0;
// psci=0;
              for(int comp=0; comp<dimension; comp++)
                pscj+=tab_vitesse(face_j,comp)*face_normales(face_j,comp);
              pscj*=signej;
              Kij(elem,face_loci,face_locj)=-1./nb_faces_elem*pscj;
              Kij(elem,face_loci,face_loci)+=1./nb_faces_elem*pscj;
              Kij(elem,face_locj,face_loci)=-1./nb_faces_elem*psci;
              Kij(elem,face_locj,face_locj)+=1./nb_faces_elem*psci;
            }//fin du for sur "face_locj"
        }//fin du for sur "face_loci"
    }//fin du for sur "elem"
//
// Correction des Kij pour Dirichlet !
//
  {
    int nb_bord=zone_Cl_VEF.nb_cond_lim();
    const IntTab& num_fac_loc = zone_VEF.get_num_fac_loc();
    for (int n_bord=0; n_bord<nb_bord; n_bord++)
      {
        const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
        const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
        int nb_faces_tot=le_bord.nb_faces_tot();
        int face;
        if ( (sub_type(Dirichlet,la_cl.valeur()))
             || (sub_type(Dirichlet_homogene,la_cl.valeur()))
           )
          {
// GF on retire le test sur nb_comp car sinon en scalaire on fait tjs du volume etendu
            if ( volumes_etendus_ )
              {
//
// Modification des coefficients de la matrice
//
                for (int ind_face=0; ind_face<nb_faces_tot; ind_face++)
                  {
                    face = le_bord.num_face(ind_face);
                    const int elem=face_voisins(face,0);
                    assert(elem!=-1);
                    const int nb_faces_bord = elem_nb_faces_dirichlet_(elem);
//
// Calcul du coefficient ponderateur
//
                    const double coeff = (Objet_U::dimension==2) ?
                                         nb_faces_bord/2. : nb_faces_bord*nb_faces_bord/6.-nb_faces_bord/3.+1./2;
//
// Fin du calcul du coefficient ponderateur
//
                    for (int face_loc_i=0; face_loc_i<nb_faces_elem; face_loc_i++)
                      {
                        const int face_i = elem_faces(elem,face_loc_i);
                        /* On determine si "face_i" est une face de Dirichlet */
                        bool is_not_on_boundary = true;
                        for (int f_loc=0; f_loc<nb_faces_bord; f_loc++)
                          is_not_on_boundary&=(face_i!=elem_faces_dirichlet_(elem,f_loc));
                        if (is_not_on_boundary) /* si "face_i" n'est pas de Dirichlet */
{
                            for (int face_loc_j=0; face_loc_j<nb_faces_elem; face_loc_j++)
{
                                /* Modification des coefficients de la matrice */
                                /* selon les fonctions de formes etendues */
                                for (int f_loc=0; f_loc<nb_faces_bord; f_loc++)
{
                                    const int face_bord = elem_faces_dirichlet_(elem,f_loc);
                                    const int face_loc_k = num_fac_loc(face_bord,0);
                                    assert(face_loc_k>=0);
                                    assert(face_loc_k<nb_faces_elem);
                                    double& kij = Kij(elem,face_loc_i,face_loc_j);
                                    const double kkj = Kij(elem,face_loc_k,face_loc_j);
                                    kij+=coeff*kkj;
                                  }//fin du for sur "f_loc"
                              }//fin du for sur "face_loc_k"
                          }//fin du if
                      }//fin du for sur "face_loc_i"
//
// Remise a zero des coefficients associes aux noeuds
// qui se situent sur la frontiere de Dirichlet
//
                    {
                      for (int f_loc=0; f_loc<nb_faces_bord; f_loc++)
{
                          const int face_bord = elem_faces_dirichlet_(elem,f_loc);
                          const int face_loc_j = num_fac_loc(face_bord,0);
                          assert(face_loc_j>=0);
                          assert(face_loc_j<nb_faces_elem);
                          for (int face_loc_i=0; face_loc_i<nb_faces_elem; face_loc_i++)
                            Kij(elem,face_loc_j,face_loc_i)=0;
                        }//fin du for sur "f_loc"
                    }
//
// Fin de la remise a zero
//
//
// Pour retrouver le schema LED
//
                    {
                      for (int face_loc_i=0; face_loc_i<nb_faces_elem; face_loc_i++)
{
                          double sum=0.;
                          for (int face_loc_k=0; face_loc_k<nb_faces_elem; face_loc_k++)
{
                              sum+=Kij(elem,face_loc_i,face_loc_k);
                            }
// Cerr << "somme apres : " << sum << finl;
                          Kij(elem,face_loc_i,face_loc_i)-=sum;//car div(u)=0!
                        }
                    }
//
// Fin du schema LED
//
                  }//!< for face  Fin de la modification des coefficients de la matrice
//
//
//
              }//fin du if sur "volumes_etendus_"
          }//!< sub_type Dirichlet
        else if (sub_type(Neumann,la_cl.valeur()) || sub_type(Neumann_homogene,la_cl.valeur()) || sub_type(Neumann_val_ext,la_cl.valeur()))
          {
// On ne fait rien
          }//fin du if sur Neumann
        else if (sub_type(Symetrie,la_cl.valeur()))
          {
// On ne fait rien
          }//fin du if sur Symetrie
        else if (sub_type(Periodique,la_cl.valeur()))
          {
// On ne fait rien
          }//fin du if sur Periodique
        else if (sub_type(Echange_impose_base,la_cl.valeur()))
          {
// On ne fait rien
          }//fin du if sur Echange_impose_base
        else
          {
            Cerr << "Erreur Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre()" << finl;
            Cerr << "Condition aux limites " << la_cl.que_suis_je() << " non codee."   << finl;
            Cerr << "Sortie du programme." << finl;
            Process::exit();
          }//fin du else sur les autres conditions aux limites
      }//fin des conditions aux limites
  }
//
// Fin de la correction des Kij
//
}
References Cerr, coeff, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), elem_faces_dirichlet_, elem_nb_faces_dirichlet_, Process::exit(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Zone_VF::get_num_fac_loc(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Zone_Cl_dis_base::nb_cond_lim(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Objet_U::que_suis_je(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and volumes_etendus_.
Referenced by ajouter(), ajouter_contribution(), test_difference_Kij(), and test_implicite().
calculer_data_pour_dirichlet()
void Op_Conv_EF_VEF_P1NC_Stab::calculer_data_pour_dirichlet () private
Definition at line 2033 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const int nb_bord=zone_Cl_VEF.nb_cond_lim();
// Dimensionnement et initialisation des attributs
// REMARQUE : un element ne peut pas avoir plus de
// (dimension) faces de Dirichlet
  elem_nb_faces_dirichlet_.resize(nb_elem_tot);
  elem_faces_dirichlet_.resize(nb_elem_tot,Objet_U::dimension);
  elem_nb_faces_dirichlet_=0;
  elem_faces_dirichlet_=-1;
  for (int n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int face, nb_faces_tot=le_bord.nb_faces_tot();
      if ( (sub_type(Dirichlet,la_cl.valeur()))
           || (sub_type(Dirichlet_homogene,la_cl.valeur()))
         )
        {
//
// Remplissage des tableaux
//
          for (int ind_face=0; ind_face<nb_faces_tot; ind_face++)
            {
              face = le_bord.num_face(ind_face);
              const int elem=face_voisins(face,0);
              assert(elem!=-1);
              elem_nb_faces_dirichlet_(elem)+=1;
              assert(elem_nb_faces_dirichlet_(elem)<=Objet_U::dimension);
              if (elem_faces_dirichlet_(elem,0)==-1) elem_faces_dirichlet_(elem,0)=face;
              else if (elem_faces_dirichlet_(elem,1)==-1) elem_faces_dirichlet_(elem,1)=face;
              else if (Objet_U::dimension==3 && elem_faces_dirichlet_(elem,2)==-1) elem_faces_dirichlet_(elem,2)=face;
              else
                {
                  Cerr << "Erreur Op_Conv_EF_VEF_P1NC_Stab::calculer_data_pour_dirichlet()" << finl;
                  Cerr << "L'element numero " << elem << " contient plus de "
                       << Objet_U::dimension << " faces de Dirichlet" << finl;
                  Cerr << "Sortie du programme." << finl;
                  Process::exit();
                }
            }//fin du for sur "face"
//
// Fin du remplissage des tableaux
//
        }//fin du if sur "Dirichlet"
    }//fin du for sur "n_bord"
}
References Cerr, Objet_U::dimension, elem_faces_dirichlet_, elem_nb_faces_dirichlet_, Process::exit(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
Referenced by completer().
calculer_flux_bords()
void Op_Conv_EF_VEF_P1NC_Stab::calculer_flux_bords (const DoubleTab & Kij, const DoubleTab & tab_vitesse, const DoubleTab & transporte) const private
Definition at line 701 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
#ifndef NDEBUG
  const IntTab& face_voisins = zone_VEF.face_voisins();
#endif
  const DoubleVect& transporteV=transporte;
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const int nb_bord = zone_Cl_VEF.nb_cond_lim();
  const int nb_comp=transporte.line_size();
// int elem=0;
  int facei=0, dim=0, n_bord=0, num1=0,num2=0, ind_face=0;
  double psc=0.;
  for (n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2 = le_bord.nb_faces();//il ne faut boucler que sur les faces reelles ici
      if ( sub_type(Dirichlet_homogene,la_cl.valeur()) )
        {
// On ne calcule pas le flux aux bords Dirichlet_homogene
        }
      else if ( sub_type(Neumann,la_cl.valeur())
                || sub_type(Neumann_val_ext,la_cl.valeur())
                || sub_type(Neumann_homogene,la_cl.valeur())
                || sub_type(Symetrie,la_cl.valeur())
                || sub_type(Echange_impose_base,la_cl.valeur())
                || sub_type(Dirichlet,la_cl.valeur())
                || sub_type(Periodique,la_cl.valeur()) )
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei = le_bord.num_face(ind_face);
              assert(face_voisins(facei,0)!=-1);
              psc=0.;
              for (dim=0; dim<dimension; dim++)
                psc-=tab_vitesse(facei,dim)*face_normales(facei,dim);
              for (dim=0; dim<nb_comp; dim++)
                flux_bords_(facei,dim)=psc*transporteV[facei*nb_comp+dim];
            }
        }//fin du if sur "Neumann", "Neumann_homogene", "Symetrie", "Echange_impose_base"
      else
        {
          Cerr << "Erreur Op_Conv_EF_VEF_P1NC_Stab::calculer_flux_bords()" << finl;
          Cerr << "Condition aux limites " << la_cl.que_suis_je() << " non codee."   << finl;
          Cerr << "Sortie du programme." << finl;
          Process::exit();
        }//fin du else sur les autres conditions aux limites
    }
}
References Cerr, Objet_U::dimension, Process::exit(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), finl, Operateur_base::flux_bords_, Cond_lim::frontiere_dis(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_face(), Objet_U::que_suis_je(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
Referenced by ajouter().
calculer_senseur()
void Op_Conv_EF_VEF_P1NC_Stab::calculer_senseur (const DoubleTab & Kij, const DoubleVect & transporteV, const int nb_comp, const int face_i, const IntTab & elem_faces, const IntTab & face_voisins, const IntTab & num_fac_loc, ArrOfDouble & P_plus, ArrOfDouble & P_moins, ArrOfDouble & Q_plus, ArrOfDouble & Q_moins) const inline private
Definition at line 940 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  assert(P_plus.size_array()==nb_comp);
  assert(Q_plus.size_array()==nb_comp);
  assert(P_moins.size_array()==nb_comp);
  assert(Q_moins.size_array()==nb_comp);
  const int nb_faces_elem=elem_faces.dimension(1);
  for (int elem_voisin=0; elem_voisin<2; elem_voisin++)
    {
      int elem = face_voisins(face_i,elem_voisin);
      if (elem!=-1)
        {
          int face_i_loc = num_fac_loc(face_i,elem_voisin);
          assert(face_i_loc>=0);
          assert(face_i_loc<nb_faces_elem);
// On travaille sur les faces de "elem"
          for (int face_k_loc=0; face_k_loc<nb_faces_elem; face_k_loc++)
            {
              int face_k=elem_faces(elem,face_k_loc);
              double kik=Kij(elem,face_i_loc,face_k_loc);
//
// Calcul des variables intermediaires
//
              for (int dim=0; dim<nb_comp; dim++)
                {
                  double deltaki = transporteV[face_k*nb_comp+dim]-transporteV[face_i*nb_comp+dim];
                  /* Codage initial:
                     P_plus(dim)+=minimum(0.,kik)*minimum(0.,deltaki);
                     P_moins(dim)+=minimum(0.,kik)*maximum(0.,deltaki);
                     Q_plus(dim)+=maximum(0.,kik)*maximum(0.,deltaki);
                     Q_moins(dim)+=maximum(0.,kik)*minimum(0.,deltaki);
// Calcul de P_plus et P_moins
// Calcul de Q_plus et Q_moins
                  */
// Codage optimise:
                  double tmp = kik*deltaki;
                  if (kik>0)
                    {
                      if (tmp>0) Q_plus[dim]+=tmp;
                      else       Q_moins[dim]+=tmp;
                    }
                  else
                    {
                      if (tmp>0) P_plus[dim]+=tmp;
                      else       P_moins[dim]+=tmp;
                    }
                  assert(P_plus[dim]>=0);
                  assert(Q_plus[dim]>=0);
                  assert(P_moins[dim]<=0);
                  assert(Q_moins[dim]<=0);
                }//fin du for sur "dim"
//
// Fin du calcul des variables intermediaires
//
            }//fin du for sur "face_k_loc"
        }//fin du if sur "elem!=-1"
    }//fin du for sur "elem_voisin"
}
References TRUSTTab< _TYPE_ >::dimension(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by ajouter_antidiffusion(), and ajouter_contribution_antidiffusion().
completer()
void Op_Conv_EF_VEF_P1NC_Stab::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Definition at line 2095 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  Op_Conv_VEF_Face::completer();
  calculer_data_pour_dirichlet();
// int nb_comp=1;
// if (equation().inconnue().valeurs().nb_dim()>1)
// nb_comp=equation().inconnue().valeurs().dimension(1);
// limiteurs_.resize(la_zone_vef->nb_faces_tot(),nb_comp);
// limiteurs_=0.;
  alpha_tab.resize_array(la_zone_vef->nb_faces_tot());
  alpha_tab = alpha_;
  beta.resize_array(la_zone_vef->nb_faces_tot());
  beta=1.;
  if (ssz_alpha)
    {
      for (int i=0; i<nb_ssz_alpha; i++)
        {
          REF(Sous_zone_VF) la_ssz;
          const Sous_Zone& la_sous_zone=equation().probleme().domaine().ss_zone(noms_ssz_alpha[i]);
          const Domaine_dis& le_domaine_dis=la_zone_vef->domaine_dis();
          bool trouve=false;
          for (int ssz=0; ssz<le_domaine_dis.nombre_de_sous_zones_dis(); ssz++)
            {
              if (le_domaine_dis.sous_zone_dis(ssz)->sous_zone().est_egal_a(la_sous_zone))
                {
                  trouve=true;
                  la_ssz=ref_cast(Sous_zone_VF,le_domaine_dis.sous_zone_dis(ssz).valeur());
                }
            }
          if(!trouve)
            {
              Cerr << "On ne trouve pas la sous_zone discretisee associee a " << noms_ssz_alpha[i] << finl;
              Process::exit();
            }
          const Sous_zone_VF& ssz=la_ssz.valeur();
          int nb_faces = ssz.les_faces().size();
          for (int face=0; face<nb_faces; face++)
            {
              int la_face=ssz.les_faces()[face];
              beta[la_face] = 1.;
              alpha_tab[la_face] = alpha_ssz(i);
            }
        }
    }
  if (sous_zone)
    {
      sous_zone=false;
      const Sous_Zone& la_sous_zone=equation().probleme().domaine().ss_zone(nom_sous_zone);
      const Domaine_dis& le_domaine_dis=la_zone_vef->domaine_dis();
      for (int ssz=0; ssz<le_domaine_dis.nombre_de_sous_zones_dis(); ssz++)
        {
          if (le_domaine_dis.sous_zone_dis(ssz)->sous_zone().est_egal_a(la_sous_zone))
            {
              sous_zone=true;
              la_sous_zone_dis=ref_cast(Sous_zone_VF,le_domaine_dis.sous_zone_dis(ssz).valeur());
            }
        }
      if(!sous_zone)
        {
          Cerr << "On ne trouve pas la sous_zone discretisee associee a " << nom_sous_zone << finl;
          Process::exit();
        }
      const Sous_zone_VF& ssz=la_sous_zone_dis.valeur();
      int nb_faces = ssz.les_faces().size();
      for (int face=0; face<nb_faces; face++)
        {
          int la_face=ssz.les_faces()[face];
          beta[la_face] = 0.;
          alpha_tab[la_face] = 1.;
        }
    }
}
References alpha_, alpha_ssz, alpha_tab, beta, calculer_data_pour_dirichlet(), Cerr, Operateur_base::completer(), Probleme_base::domaine(), Zone_dis_base::domaine_dis(), MorEqn::equation(), Objet_U::est_egal_a(), Process::exit(), finl, la_sous_zone_dis, Op_Conv_VEF_base::la_zone_vef, Sous_zone_VF::les_faces(), Zone_VF::nb_faces_tot(), nb_ssz_alpha, nom_sous_zone, Domaine_dis::nombre_de_sous_zones_dis(), noms_ssz_alpha, Equation_base::probleme(), REF, ref_cast, TRUSTArray< _TYPE_ >::resize_array(), TRUSTVect< _TYPE_ >::size(), sous_zone, Domaine_dis::sous_zone_dis(), Domaine::ss_zone(), ssz_alpha, Deriv_Sous_zone_dis_base::valeur(), and Ref_Sous_zone_VF::valeur().
contribuer_a_avec()
void Op_Conv_EF_VEF_P1NC_Stab::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 122 of file Op_Conv_EF_VEF_P1NC_Stab.h.
{
  ajouter_contribution(inco, matrice);
}
References ajouter_contribution().
cree_instance()
Objet_U * Op_Conv_EF_VEF_P1NC_Stab::cree_instance () static
Definition at line 37 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
duplique()
int Op_Conv_EF_VEF_P1NC_Stab::duplique () const override virtual
Implements Objet_U.
Definition at line 37 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
get_info()
const Type_info * Op_Conv_EF_VEF_P1NC_Stab::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Conv_base.
Definition at line 37 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
info()
const Type_info * Op_Conv_EF_VEF_P1NC_Stab::info () static
Definition at line 37 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
is_compressible()
int Op_Conv_EF_VEF_P1NC_Stab::is_compressible () const inline
Definition at line 128 of file Op_Conv_EF_VEF_P1NC_Stab.h.
{
  return is_compressible_;
}
References is_compressible_.
mettre_a_jour_pour_periodicite()
void Op_Conv_EF_VEF_P1NC_Stab::mettre_a_jour_pour_periodicite (DoubleTab & resu) const private
Definition at line 1558 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const int nb_bord = zone_Cl_VEF.nb_cond_lim();
  const int nb_comp = (resu.nb_dim()==1) ? 1 : resu.dimension(1);
  DoubleVect& resuV = resu;
  int ligne=0,ligneAss=0,facei=0,faceiAss=0, ind_face=0;
  int num1=0,num2=0, ind_face_associee=0, dim=0;
// Faces de bord
  for (int n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei=le_bord.num_face(ind_face);
              ind_face_associee=la_cl_perio.face_associee(ind_face);
              faceiAss=le_bord.num_face(ind_face_associee);
              if (facei<faceiAss)
                for (dim=0; dim<nb_comp; dim++)
                  {
                    ligne=facei*nb_comp+dim;
                    ligneAss=faceiAss*nb_comp+dim;
                    resuV[ligneAss]+=resuV[ligne];
                    resuV[ligne]=resuV[ligneAss];
                  }
            }//fin du for sur "face_i"
        }//fin du if sur "Periodique"
    }//fin du for sur "n_bord"
}
References TRUSTTab< _TYPE_ >::dimension(), Periodique::face_associee(), Cond_lim::frontiere_dis(), Op_Conv_VEF_base::la_zcl_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), TRUSTTab< _TYPE_ >::nb_dim(), Front_VF::nb_faces(), Front_VF::num_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), and Ref_Zone_Cl_VEF::valeur().
Referenced by ajouter(), test_difference_resu(), and test_implicite().
modifier_pour_Cl()
void Op_Conv_EF_VEF_P1NC_Stab::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 2222 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  Op_Conv_VEF_Face::modifier_pour_Cl(matrice,secmem);
}
References Op_Conv_VEF_Face::modifier_pour_Cl().
printOn()
Sortie & Op_Conv_EF_VEF_P1NC_Stab::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Conv_base.
Definition at line 43 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  return s << que_suis_je();
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Conv_EF_VEF_P1NC_Stab::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Conv_base.
Definition at line 51 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
// Les mots a reconnaitre
  Motcle motlu, accouverte = "{" , accfermee = "}" ;
  Motcles les_mots(9);
  {
    les_mots[0] = "alpha";
    les_mots[1] = "test";
    les_mots[2] = "TdivU";
    les_mots[3] = "old";
    les_mots[4] = "volumes_etendus";
    les_mots[5] = "volumes_non_etendus";
    les_mots[6] = "amont_sous_zone";
    les_mots[7] = "nouvelle_matrice_implicite";
    les_mots[8] = "alpha_sous_zone";
  }
// Les variables a instancier
  alpha_=1.;
  test_=0;
  is_compressible_=0;
  old_=0;
  volumes_etendus_=1;
  sous_zone=false;
  ssz_alpha=false;
  new_jacobienne_=0;
  s >> motlu;
  if (motlu!=accouverte)
    {
      if (Process::je_suis_maitre())
        {
          Cerr << "Erreur Op_Conv_EF_VEF_P1NC_Stab::readOn()" << finl;
          Cerr << "Depuis la 1.5.3, la syntaxe du mot cle EF_stab a change." << finl;
          Cerr << "Il faut commencer par une accolade ouvrante {" << finl;
          Cerr << "et les options eventuelles sont entre les accolades:" << finl;
          Cerr << "Convection { EF_stab } -> Convection { EF_stab { } }" << finl;
        }
      Process::exit();
    }
  s >> motlu;
  while(motlu!=accfermee)
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          s >> alpha_;
          break;
        case 1 :
          test_=1;
          break;
        case 2 :
          is_compressible_=1;
          break;
        case 3 :
          old_=1;
          break;
        case 4 :
          volumes_etendus_=1;
          break;
        case 5 :
          volumes_etendus_=0;
          break;
        case 6 :
          sous_zone=true;
          s >> nom_sous_zone;
          break;
        case 7 :
          s >> new_jacobienne_;
          break;
        case 8 :
          ssz_alpha=true;
          s >> nb_ssz_alpha;
          noms_ssz_alpha.dimensionner(nb_ssz_alpha);
          alpha_ssz.resize(nb_ssz_alpha);
          for (int i=0; i<nb_ssz_alpha; i++)
            {
              s>>noms_ssz_alpha[i];
              s>>alpha_ssz(i);
            }
          break;
        default :
          Cerr << "Erreur Op_Conv_EF_VEF_P1NC_Stab::readOn()" << finl;
          Cerr << "Mot clef " << motlu << " non connu." << finl;
          Cerr << "Sortie du programme." << finl;
          Process::exit();
          break;
        }//fin du switch
// Suite de la lecture
      s >> motlu;
    }//fin du while
  return s ;
}
References alpha_, alpha_ssz, Cerr, vect_impl::dimensionner(), Process::exit(), finl, is_compressible_, Process::je_suis_maitre(), nb_ssz_alpha, new_jacobienne_, nom_sous_zone, noms_ssz_alpha, old_, TRUSTVect< _TYPE_ >::resize(), Motcles::search(), sous_zone, ssz_alpha, test_, and volumes_etendus_.
reinit_conv_pour_Cl()
void Op_Conv_EF_VEF_P1NC_Stab::reinit_conv_pour_Cl (const DoubleTab & transporte, const IntList & faces, const DoubleTabs & valeurs_faces, const DoubleTab & tab_vitesse, DoubleTab & resu) const private
Definition at line 270 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF=la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF=la_zcl_vef.valeur();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const int nb_bord=zone_Cl_VEF.nb_cond_lim();
  const int nb_comp=transporte.line_size();
  int n_bord=0, num1=0, num2=0, ind_face=0,facei=0, dim=0;
  double psc=0.;
  const DoubleVect& transporteV= transporte;
// Boucle pour dimensionner la liste "faces"
  for (n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2 = le_bord.nb_faces_tot();
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Neumann_sortie_libre& la_sortie_libre
            = ref_cast(Neumann_sortie_libre, la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei = le_bord.num_face(ind_face);
              psc=0.;
              for (dim=0; dim<dimension; dim++)
                psc-=tab_vitesse(facei,dim)*face_normales(facei,dim);
              if (psc>0)
                for (dim=0; dim<nb_comp; dim++)
                  resu(facei,dim)+=psc*(la_sortie_libre.val_ext(facei-num1,dim)-transporteV[facei*nb_comp+dim]);
            }
        }//fin du if sur "Neumann_sortie_libre"
    }
}
References Objet_U::dimension, Zone_VEF::face_normales(), Cond_lim::frontiere_dis(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, sub_type, Neumann_sortie_libre::val_ext(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
Referenced by ajouter().
remplir_fluent()
void Op_Conv_EF_VEF_P1NC_Stab::remplir_fluent (DoubleVect & fluent_) const override virtual
Reimplemented from Op_Conv_VEF_base.
Definition at line 527 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Champ_Inc_base& la_vitesse=vitesse_.valeur();
  const DoubleTab& tab_vitesse=la_vitesse.valeurs();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const int nb_faces = zone_VEF.nb_faces();
// calcul de la CFL.
  double psc;
// On remet a zero le tableau qui sert pour
// le calcul du pas de temps de stabilite
  fluent_ = 0;
  for(int num_face=0; num_face<nb_faces; num_face++)
    {
      psc=0.;
      for (int i=0; i<dimension; i++)
        psc+=tab_vitesse(num_face,i)*face_normales(num_face,i);
      fluent_(num_face)=std::fabs(psc);
    }
}
References Objet_U::dimension, Zone_VEF::face_normales(), Op_Conv_VEF_base::la_zone_vef, Zone_VF::nb_faces(), Ref_Champ_Inc_base::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc_base::valeurs(), and Op_Conv_VEF_base::vitesse_.
self_cast() [1/2]
const Op_Conv_EF_VEF_P1NC_Stab & Op_Conv_EF_VEF_P1NC_Stab::self_cast (const Objet_U & r) static
Definition at line 37 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
self_cast() [2/2]
Op_Conv_EF_VEF_P1NC_Stab & Op_Conv_EF_VEF_P1NC_Stab::self_cast (Objet_U & r) static
Definition at line 37 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
taille_memoire()
unsigned Op_Conv_EF_VEF_P1NC_Stab::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 37 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
test()
void Op_Conv_EF_VEF_P1NC_Stab::test (const DoubleTab & transporte, const DoubleTab & resu, const DoubleTab & vitesse) const private
Definition at line 1003 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const int nb_faces_elem=elem_faces.dimension(1);
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  DoubleTab Kij2(nb_elem_tot,nb_faces_elem, nb_faces_elem);
  Kij2=0.;
  DoubleTab Kij_ancien(nb_elem_tot,nb_faces_elem, nb_faces_elem);
  Kij_ancien=0.;
  test_difference_Kij(transporte,Kij2,Kij_ancien,tab_vitesse);
  test_difference_resu(Kij2,Kij_ancien,transporte,resu,tab_vitesse);
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), Op_Conv_VEF_base::la_zone_vef, Zone_dis_base::nb_elem_tot(), test_difference_Kij(), test_difference_resu(), and Ref_Zone_VEF::valeur().
Referenced by ajouter().
test_difference_Kij()
void Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij (const DoubleTab & transporte, DoubleTab & Kij, DoubleTab & Kij_ancien, const DoubleTab & vitesse) const private
Definition at line 1020 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
// const Champ_P1NC& la_vitesse=ref_cast(Champ_P1NC, vitesse_.valeur());
// const DoubleTab& vitesse=la_vitesse.valeurs();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const int nb_faces_elem=elem_faces.dimension(1);
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const int nb_comp = (transporte.nb_dim()!=1) ? transporte.dimension(1) : 1;
  int face_i0, face_j0, elem0, comp;
  calculer_coefficients_operateur_centre(Kij,nb_comp,tab_vitesse);
//
// Calcul des Kij_ancien :
//
  for(elem0=0; elem0<nb_elem_tot; elem0++)
    {
      int face_loci=0;
      int face_locj=0;
      for(; face_loci<nb_faces_elem; face_loci++)
        {
          face_i0=elem_faces(elem0,face_loci);
          double signei=1.0;
          if(face_voisins(face_i0,0)!=elem0)
            signei=-1.0;
          double psci=0;
          for(comp=0; comp<dimension; comp++)
            psci+=tab_vitesse(face_i0,comp)*face_normales(face_i0,comp);
          psci*=signei;
// Kij_ancien(elem,face_loci,face_loci)=0.;
          for(face_locj=face_loci+1; face_locj<nb_faces_elem; face_locj++)
            {
              face_j0=elem_faces(elem0,face_locj);
              double signej=1.0;
              if(face_voisins(face_j0,0)!=elem0)
                signej=-1.0;
              double pscj=0;
// psci=0;
              for(comp=0; comp<dimension; comp++)
                pscj+=tab_vitesse(face_j0,comp)*face_normales(face_j0,comp);
              pscj*=signej;
              Kij_ancien(elem0,face_loci,face_locj)=-1./nb_faces_elem*pscj;
              Kij_ancien(elem0,face_loci,face_loci)+=1./nb_faces_elem*pscj;
              Kij_ancien(elem0,face_locj,face_loci)=-1./nb_faces_elem*psci;
              Kij_ancien(elem0,face_locj,face_locj)+=1./nb_faces_elem*psci;
            }
        }
    }
// Correction des Kij_ancien pour Dirichlet !
  {
    int nb_bord=zone_Cl_VEF.nb_cond_lim();
    int face;
    double coeff=1./dimension;
    for (int n_bord=0; n_bord<nb_bord; n_bord++)
      {
        const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
        const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
        int nb_faces_tot=le_bord.nb_faces_tot();
        if ( (sub_type(Dirichlet,la_cl.valeur()))
             || (sub_type(Dirichlet_homogene,la_cl.valeur()))
           )
          {
            if ( volumes_etendus_ )
              {
                for (int ind_face=0; ind_face<nb_faces_tot; ind_face++)
                  {
                    face = le_bord.num_face(ind_face);
                    int elem=face_voisins(face,0);
                    assert(elem!=-1);
                    int face_loc_j;
                    int face_j=-1;
                    for (face_loc_j=0; (face_loc_j<nb_faces_elem && face_j!=face); face_loc_j++)
                      {
                        face_j=elem_faces(elem,face_loc_j);
                      }
                    face_loc_j--;
                    assert(face_loc_j>=0);
                    assert(face_loc_j<nb_faces_elem);
                    assert(elem_faces(elem,face_loc_j)==face);
                    const double kjj=Kij_ancien(elem,face_loc_j,face_loc_j);
                    for (int face_loc_i=0; face_loc_i<nb_faces_elem; face_loc_i++)
                      {
                        int face_i=elem_faces(elem,face_loc_i);
                        if(face_i!=face)
{
                            double& kii=Kij_ancien(elem,face_loc_i,face_loc_i);
                            const double kji=Kij_ancien(elem,face_loc_j,face_loc_i);
                            kii+=coeff*kji;
                            double& kij=Kij_ancien(elem,face_loc_i,face_loc_j);
                            kij+=coeff*kjj;
                            for (int face_loc_k=(face_loc_i+1); face_loc_k<nb_faces_elem; face_loc_k++)
{
                                int face_k=elem_faces(elem,face_loc_k);
                                if(face_k!=face)
{
                                    double& kik=Kij_ancien(elem,face_loc_i,face_loc_k);
                                    const double kjk=Kij_ancien(elem,face_loc_j,face_loc_k);
                                    double& kki=Kij_ancien(elem,face_loc_k,face_loc_i);
                                    kik+=coeff*kjk;
                                    kki+=coeff*kji;
                                  }
                              }
                          }
                      }
                    {
                      for (int face_loc_i=0; face_loc_i<nb_faces_elem; face_loc_i++)
                        Kij_ancien(elem,face_loc_j,face_loc_i)=0;
                    }
                    {
                      for (int face_loc_i=0; face_loc_i<nb_faces_elem; face_loc_i++)
{
                          double sum=0.;
                          for (int face_loc_k=0; face_loc_k<nb_faces_elem; face_loc_k++)
{
                              sum+=Kij_ancien(elem,face_loc_i,face_loc_k);
                            }
// Cerr << "somme apres : " << sum << finl;
                          Kij_ancien(elem,face_loc_i,face_loc_i)-=sum;//car div(u)=0!
                        }
                    }
                  }//!< for face
              }//fin du if sur "volumes_etendus_"
          }//!< sub_type Dirichlet
      }
  }
  Kij-=Kij_ancien;
  const double max_kij = local_max_abs_vect(Kij);
  if (max_kij > 1.e-15)
    {
      Cerr << "Erreur dans le calcul des Kij : " << max_kij << finl;
      Cerr << "Sortie du programme" << finl;
      Process::exit();
    }
  Kij+=Kij_ancien;
}
References calculer_coefficients_operateur_centre(), Cerr, coeff, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), Process::exit(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), local_max_abs_vect(), Zone_Cl_dis_base::nb_cond_lim(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and volumes_etendus_.
Referenced by test().
test_difference_resu()
void Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu (const DoubleTab & Kij, const DoubleTab & Kij_ancien, const DoubleTab & transporte, const DoubleTab & resu, const DoubleTab & vitesse) const private
Definition at line 1168 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  DoubleTab resu1(resu);
  resu1=0;
  if (is_compressible_) ajouter_partie_compressible(transporte,resu1,tab_vitesse);
  ajouter_operateur_centre(Kij,transporte,resu1);
  ajouter_diffusion(Kij,transporte,resu1);
  ajouter_antidiffusion(Kij,transporte,resu1);
  mettre_a_jour_pour_periodicite(resu1);
  DoubleTab resu2(resu);
  resu2=0;
//
// Calcul de resu2
//
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const int nb_faces_elem=elem_faces.line_size();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const int nb_comp=resu.line_size();
  int face_i0, face_j0, elem, comp0;
  const int nb_faces0 = transporte.dimension(0);
  ArrOfDouble pplusi(nb_comp);
  ArrOfDouble qplusi(nb_comp);
  ArrOfDouble pmoinsi(nb_comp);
  ArrOfDouble qmoinsi(nb_comp);
  for(elem=0; elem<nb_elem_tot; elem++)
    {
      int face_loci=0, face_locj=0;
      for(; face_loci<nb_faces_elem; face_loci++)
        {
          face_i0=elem_faces(elem,face_loci);
          for(comp0=0; comp0<nb_comp; comp0++)
            resu2(face_i0,comp0)+=Kij_ancien(elem,face_loci,face_loci)*transporte(face_i0,comp0);
          pplusi=0.;
          qplusi=0.;
          pmoinsi=0.;
          qmoinsi=0.;
          int elem1=face_voisins(face_i0,0), elem2=face_voisins(face_i0,1);
          int face_loc_i=0, face_loc_j=0;
          double dT,min_dT,max_dT, K,min_K,max_K;
//
// dans elem1 :
//
          while((face_loc_i<nb_faces_elem)&&(elem_faces(elem1,face_loc_i)!=face_i0))
            face_loc_i++;
          if(face_loc_i==nb_faces_elem)
            {
// Periodique!!
              assert(elem2!=-1);
              face_loc_i=0;
              while( (face_loc_i<nb_faces_elem) &&
                     (face_voisins(elem_faces(elem1,face_loc_i),0)!=elem2) &&
                     (face_voisins(elem_faces(elem1,face_loc_i),1)!=elem2) )
                face_loc_i++;
            }
          assert(face_loc_i<nb_faces_elem);
          for(face_loc_j=0; face_loc_j<nb_faces_elem; face_loc_j++)
            {
              int face_j=elem_faces(elem1,face_loc_j);
              if(face_j!=face_i0)
                {
                  K=Kij_ancien(elem1,face_loc_i,face_loc_j);
                  if(K>0.)
                    {
                      max_K=K ;
                      min_K=0.;
                    }
                  else
                    {
                      max_K=0.;
                      min_K=K ;
                    }
                  for(comp0=0; comp0<nb_comp; comp0++)
                    {
                      dT =transporte(face_j,comp0);
                      dT-=transporte(face_i0,comp0);
                      if(dT>0.)
{
                          max_dT=dT ;
                          min_dT=0 ;
                        }
                      else
{
                          max_dT=0. ;
                          min_dT=dT ;
                        }
                      pplusi[comp0] +=min_K*min_dT;
                      pmoinsi[comp0]+=min_K*max_dT;
                      qplusi[comp0] +=max_K*max_dT;
                      qmoinsi[comp0]+=max_K*min_dT;
                    }
                }
            }
//
// dans elem2 :
//
          if(elem2!=-1)
            {
              face_loc_i=0;
              while((face_loc_i<nb_faces_elem)&&(elem_faces(elem2,face_loc_i)!=face_i0))
                face_loc_i++;
              if(face_loc_i==nb_faces_elem)
                {
// Periodique!!
                  face_loc_i=0;
                  while( (face_loc_i<nb_faces_elem) &&
                         (face_voisins(elem_faces(elem2,face_loc_i),0)!=elem1) &&
                         (face_voisins(elem_faces(elem2,face_loc_i),1)!=elem1) )
                    face_loc_i++;
                }
              assert(face_loc_i<nb_faces_elem);
              for(face_loc_j=0; face_loc_j<nb_faces_elem; face_loc_j++)
                {
                  int face_j=elem_faces(elem2,face_loc_j);
                  if(face_j!=face_i0)
                    {
                      K=Kij_ancien(elem2,face_loc_i,face_loc_j);
                      if(K>0.)
{
                          max_K=K ;
                          min_K=0.;
                        }
                      else
{
                          max_K=0.;
                          min_K=K ;
                        }
                      for(comp0=0; comp0<nb_comp; comp0++)
{
                          dT =transporte(face_j,comp0);
                          dT-=transporte(face_i0,comp0);
                          if(dT>0.)
{
                              max_dT=dT ;
                              min_dT=0 ;
                            }
                          else
{
                              max_dT=0. ;
                              min_dT=dT ;
                            }
                          pplusi[comp0] +=min_K*min_dT;
                          pmoinsi[comp0]+=min_K*max_dT;
                          qplusi[comp0] +=max_K*max_dT;
                          qmoinsi[comp0]+=max_K*min_dT;
                        }
                    }
                }
            }
          for(face_locj=0; face_locj<nb_faces_elem; face_locj++)
            if(face_locj!=face_loci)
              {
                face_j0=elem_faces(elem,face_locj);
                const double kij=Kij_ancien(elem,face_loci,face_locj);
                const double kji=Kij_ancien(elem,face_locj,face_loci);
                double dij=Dij(elem,face_loci,face_locj,Kij_ancien);
                double lji=kji+dij;
                double lij=kij+dij;
                assert(lij>=0);
                assert(lji>=0);
                for(comp0=0; comp0<nb_comp; comp0++)
                  {
                    const double Ti=transporte(face_i0,comp0);
                    const double Tj=transporte(face_j0,comp0);
                    double deltaij=Ti-Tj;
                    double Fij=0;
                    if(lij<=lji)
                      {
                        double coef=1;
                        if (lij==lji)  coef=.5;
                        if(deltaij)
{
                            if(Ti >= Tj)
{
                                if(pplusi[comp0])
{
                                    double R=qplusi[comp0]/pplusi[comp0];
                                    Fij=minimum(limiteur(R)*dij,lji);
                                  }
                              }
                            else if(pmoinsi[comp0])
{
                                double R=qmoinsi[comp0]/pmoinsi[comp0];
                                Fij=minimum(limiteur(R)*dij,lji);
                              }
                            assert(Fij*dij>=0);
                            Fij-=dij;
                            Fij*=deltaij;
                          }
                        resu2(face_i0,comp0)+=coef*(kij*Tj+Fij);
                        resu2(face_j0,comp0)+=coef*(kji*Ti-Fij);
                      }
                  }
              }
        }
    }
// Pour periodique
  int nb_bord=zone_Cl_VEF.nb_cond_lim();
  int face;
  for (int n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = le_bord.num_premiere_face();
      int nb_faces_b=le_bord.nb_faces();
      int num2 = num1 + nb_faces_b;
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int face_associee;
          IntVect fait(nb_faces_b);
          fait = 0;
          for (face=num1; face<num2; face++)
            {
              if (fait(face-num1) == 0)
                {
                  fait(face-num1) = 1;
                  face_associee=la_cl_perio.face_associee(face-num1);
                  fait(face_associee) = 1;
                  for (int comp=0; comp<nb_comp; comp++)
                    resu2(face_associee+num1, comp)=(resu2(face,comp)+=resu2(face_associee+num1,comp));
                }//!< if fait
            }//!< for face
        }//!< sub_type Perio
    }
  resu1-=resu2;
// Dans le cas des faces de Dirichlet, notre algorithme ne calcule aucune
// valeur sur les faces de Dirichlet car de toute facon, elles sont ecrasees
// par la matrice de masse. Mais ce n'est pas le cas de l'ancien algorithme
// d'ou la modification apportee ici pour eviter de ne voir que les erreurs
// commises sur les bords de Dirichlet qui n'ont aucune importance
  for (int n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = le_bord.num_premiere_face();
      int nb_faces=le_bord.nb_faces();
      int num2 = num1 + nb_faces;
      if (sub_type(Dirichlet,la_cl.valeur()) || sub_type(Dirichlet_homogene,la_cl.valeur()))
        {
          for (face=num1; face<num2; face++)
            for (int dim=0; dim<nb_comp; dim++)
              resu1(face,dim)=0;
        }//fin du if sur Dirichlet
    }//fin du for sur "n_bord"
  const double max_abs_resu1 = local_max_abs_vect(resu1);
  Journal() << "local_max_abs_vect(resu1) = " << max_abs_resu1
            << " " << equation().schema_temps().temps_courant() << finl;
  if (max_abs_resu1 > 1.e-15)
    {
      Cerr << "Erreur dans le calcul des resu : " << max_abs_resu1 << finl;
      Cerr << "Affichage des faces de bord" << finl;
      /**************************************************/
      Cerr << "Affichage des faces de bord." << finl;
      for (int n_bord=0; n_bord<nb_bord; n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int nb_faces=le_bord.nb_faces();
          int num2 = num1 + nb_faces;
          if (sub_type(Periodique,la_cl.valeur()))
            {
              Cerr << "Bord periodique : ";
              for (face=num1; face<num2; face++)
                {
                  Cerr << face << ",";
                }//!< for face
              Cerr << finl;
            }//!< sub_type Perio
          else if (sub_type(Dirichlet,la_cl.valeur()) || (sub_type(Dirichlet_homogene,la_cl.valeur())) )
            {
              Cerr << "Bord de Dirichlet : ";
              for (face=num1; face<num2; face++)
                {
                  Cerr << face << ",";
                }//!< for face
              Cerr << finl;
            }
        }//fin du for sur "nbord"
      /**************************************************/
      /**************************************************/
      Cerr << "Affichage des faces qui posent probleme : " << finl;
      if (nb_comp==1)
        {
          for (int face_i=0; face_i<nb_faces0; face_i++)
            {
              if (resu1(face_i)>1.e-15)
                Cerr << face_i << "(" << face_voisins(face_i,0) << ","
                     << face_voisins(face_i,1) << ") ; ";
            }//fin du for sur "face_i"
        }
      else
        {
          for (int face_i=0; face_i<nb_faces0; face_i++)
            {
              Cerr << face_i << "(" << face_voisins(face_i,0) << ","
                   << face_voisins(face_i,1) << ") ";
              for (int dim=0; dim<nb_comp; dim++)
                {
                  Cerr  << ", resu1("
                        << face_i << "," << dim << ")= "
                        << resu1(face_i,dim);
                }
              Cerr << finl;
            }
        }
      Cerr << finl;
      /**************************************************/
      /**************************************************/
      resu1+=resu2;
      for (int n_bord=0; n_bord<nb_bord; n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int nb_faces=le_bord.nb_faces();
          int num2 = num1 + nb_faces;
          if (sub_type(Periodique,la_cl.valeur()))
            {
              Cerr << "Affichage des valeurs des resu au bord perio" << finl;
              for (face=num1; face<num2; face++)
                {
                  Cerr << "resu1(" << face << ") : " << resu1(face) << finl;
                  Cerr << "resu2(" << face << ") : " << resu2(face) << finl;
                }//!< for face
              Cerr << finl;
            }//!< sub_type Perio
        }//fin du for sur "nbord"
      /**************************************************/
      static int count = 0;
      count++;
      if (count==2)
        {
          Cerr << "Sortie du programme" << finl;
          Process::exit();
        }
    }
}
References ajouter_antidiffusion(), ajouter_diffusion(), ajouter_operateur_centre(), ajouter_partie_compressible(), Cerr, Dij(), TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Process::exit(), Periodique::face_associee(), face_associee, Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), is_compressible_, Process::Journal(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), limiteur(), TRUSTVect< _TYPE_ >::line_size(), local_max_abs_vect(), mettre_a_jour_pour_periodicite(), minimum(), Zone_Cl_dis_base::nb_cond_lim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, Equation_base::schema_temps(), sub_type, Schema_Temps_base::temps_courant(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
Referenced by test().
test_implicite()
void Op_Conv_EF_VEF_P1NC_Stab::test_implicite () const private
Definition at line 2829 of file Op_Conv_EF_VEF_P1NC_Stab.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const DoubleTab& unknown=equation().inconnue().valeurs();
  const DoubleTab& tab_vitesse=vitesse_.valeur().valeurs();
  DoubleTab tab_test(unknown);
  DoubleVect& test2 = tab_test;
  test2 = 0.;
  DoubleTab resuExp(unknown);
  DoubleVect& resu2Exp = resuExp;
  resu2Exp = 0.;
  DoubleTab resuImp(unknown);
  DoubleVect& resu2Imp = resuImp;
  resu2Imp = 0.;
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  const int nb_faces_tot=zone_VEF.nb_faces_tot();
  const int nb_bord=zone_Cl_VEF.nb_cond_lim();
  DoubleTab Kij(nb_elem_tot,nb_faces_elem,nb_faces_elem);
  Kij=0.;
  const int nb_comp=unknown.line_size();
  int size=unknown.dimension(0);
  int face=0,face2=0, faceAss=0, ind_face=0,ind_faceAss=0, n_bord=0, num1=0,num2=0;
  SFichier testResu("test.txt");
  SFichier testMat("matrice.txt");
//
// Pour la periodicite
//
  IntTab faces_associees(nb_faces_tot);
  for (face=0; face<nb_faces_tot; face++)
    faces_associees(face)=face;
  for (n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2=le_bord.nb_faces_tot();//pour ne pas en oublier
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              ind_faceAss=la_cl_perio.face_associee(ind_face);
              faceAss=le_bord.num_face(ind_faceAss);
// Pour ne parcourir que la moitie des faces periodiques
              if (face<faceAss)
                {
                  faces_associees(face)=faceAss;
                  faces_associees(faceAss)=face;
                }
            }
        }
    }
//
// Fin du traitement pour la periodicite
//
  calculer_coefficients_operateur_centre(Kij,nb_comp,tab_vitesse);
//
// Construction de la matrice
//
  Matrice_Morse matrice;
  dimensionner(matrice);
  if (is_compressible_)
    ajouter_contribution_partie_compressible(unknown,tab_vitesse,matrice);
  ajouter_contribution_operateur_centre(Kij,unknown,matrice);
  ajouter_contribution_diffusion(Kij,unknown,matrice);
  ajouter_contribution_antidiffusion(Kij,unknown,matrice);
  matrice.imprimer_formatte(testMat);
//
// Fin de la construction de la matrice
//
//
// Calcul de l'operateur explicite et comparaison
//
  for (face=0; face<size; face++)
    {
      test2[face]=1.;
      test2[faces_associees(face)]=1.;
      /* Calcul de l'operateur explicite */
      resuExp=0.;
      if (is_compressible_)
        ajouter_partie_compressible(tab_test,resuExp,tab_vitesse);
      ajouter_operateur_centre(Kij,tab_test,resuExp);
      ajouter_diffusion(Kij,tab_test,resuExp);
      ajouter_antidiffusion(Kij,tab_test,resuExp);
      mettre_a_jour_pour_periodicite(resuExp);
      /* Calcul de l'operateur implicite */
      resuImp=0.;
      matrice.ajouter_multvect_(tab_test,resuImp);
      /* Calcul de la difference */
      resuExp+=resuImp;
      /* Affichage de la difference */
      testResu<<"*************************"<<finl;
      testResu<<"Face test : "<<face<<finl;
      for (face2=0; face2<size; face2++)
        if (resu2Exp[face2]<=1.e-13)
          testResu<<face2<<" OK"<<finl;
        else
          testResu<<face2<<" residu : "<<resu2Exp[face2]<<finl;
      testResu<<"*************************"<<finl;
      test2[face]=0.;
      test2[faces_associees(face)]=0.;
    }
//
// Fin du calcul de l'operateur explicite et comparaison
//
  Process::exit();
}
References ajouter_antidiffusion(), ajouter_contribution_antidiffusion(), ajouter_contribution_diffusion(), ajouter_contribution_operateur_centre(), ajouter_contribution_partie_compressible(), ajouter_diffusion(), Matrice_Morse::ajouter_multvect_(), ajouter_operateur_centre(), ajouter_partie_compressible(), calculer_coefficients_operateur_centre(), TRUSTTab< _TYPE_ >::dimension(), Op_Conv_VEF_Face::dimensionner(), MorEqn::equation(), Process::exit(), Periodique::face_associee(), finl, Cond_lim::frontiere_dis(), Matrice_Morse::imprimer_formatte(), Equation_base::inconnue(), is_compressible_, Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), mettre_a_jour_pour_periodicite(), Zone_Cl_dis_base::nb_cond_lim(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Champ_Inc_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc::valeurs(), Champ_Inc_base::valeurs(), Op_Conv_VEF_base::vitesse_, and Zone_dis_base::zone().
Referenced by ajouter_contribution().
Member Data Documentation
alpha_
double Op_Conv_EF_VEF_P1NC_Stab::alpha_ private
Definition at line 103 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by completer(), and readOn().
alpha_ssz
DoubleVect Op_Conv_EF_VEF_P1NC_Stab::alpha_ssz private
Definition at line 116 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by completer(), and readOn().
alpha_tab
ArrOfDouble Op_Conv_EF_VEF_P1NC_Stab::alpha_tab private
Definition at line 99 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by ajouter_antidiffusion(), ajouter_contribution_antidiffusion(), ajouter_contribution_diffusion(), ajouter_diffusion(), and completer().
beta
ArrOfDouble Op_Conv_EF_VEF_P1NC_Stab::beta private
vaut zero pour les faces ou l'on souhaite degenerer en Amont. mutable DoubleTab limiteurs_;//tableau stockant pour chaque face la moyenne algebrique du limiteur
Definition at line 100 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by ajouter_antidiffusion(), ajouter_contribution_antidiffusion(), and completer().
elem_faces_dirichlet_
IntTab Op_Conv_EF_VEF_P1NC_Stab::elem_faces_dirichlet_ private
Definition at line 97 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by calculer_coefficients_operateur_centre(), and calculer_data_pour_dirichlet().
elem_nb_faces_dirichlet_
IntTab Op_Conv_EF_VEF_P1NC_Stab::elem_nb_faces_dirichlet_ private
Definition at line 96 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by ajouter_contribution_partie_compressible(), ajouter_partie_compressible(), calculer_coefficients_operateur_centre(), and calculer_data_pour_dirichlet().
info_obj
const Type_info Op_Conv_EF_VEF_P1NC_Stab::info_obj static
Definition at line 46 of file Op_Conv_EF_VEF_P1NC_Stab.h.
is_compressible_
int Op_Conv_EF_VEF_P1NC_Stab::is_compressible_ private
Definition at line 105 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by ajouter(), ajouter_contribution(), is_compressible(), readOn(), test_difference_resu(), and test_implicite().
la_sous_zone_dis
Ref_Sous_zone_VF Op_Conv_EF_VEF_P1NC_Stab::la_sous_zone_dis private
Definition at line 113 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by completer().
nb_ssz_alpha
int Op_Conv_EF_VEF_P1NC_Stab::nb_ssz_alpha private
Definition at line 115 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by completer(), and readOn().
new_jacobienne_
int Op_Conv_EF_VEF_P1NC_Stab::new_jacobienne_ private
Definition at line 111 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by ajouter_contribution(), and readOn().
nom_sous_zone
Nom Op_Conv_EF_VEF_P1NC_Stab::nom_sous_zone private
Definition at line 112 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by completer(), and readOn().
noms_ssz_alpha
Noms Op_Conv_EF_VEF_P1NC_Stab::noms_ssz_alpha private
Definition at line 117 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by completer(), and readOn().
old_
int Op_Conv_EF_VEF_P1NC_Stab::old_ private
Definition at line 107 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by ajouter(), and readOn().
sous_zone
bool Op_Conv_EF_VEF_P1NC_Stab::sous_zone private
Cas d'une sous-zone a definir pour que l'EF_Stab degenere en Amont.
Definition at line 110 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by completer(), and readOn().
ssz_alpha
bool Op_Conv_EF_VEF_P1NC_Stab::ssz_alpha private
Definition at line 118 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by completer(), and readOn().
test_
int Op_Conv_EF_VEF_P1NC_Stab::test_ private
Definition at line 106 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by ajouter(), ajouter_contribution(), and readOn().
volumes_etendus_
int Op_Conv_EF_VEF_P1NC_Stab::volumes_etendus_ private
Definition at line 108 of file Op_Conv_EF_VEF_P1NC_Stab.h.
Referenced by ajouter_contribution_partie_compressible(), ajouter_old(), ajouter_partie_compressible(), calculer_coefficients_operateur_centre(), readOn(), and test_difference_Kij().
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Conv_EF_VEF_P1NC_Stab.h
src/VEF/Operateurs/Op_Conv_EF_VEF_P1NC_Stab.cpp