TRUST: Eval_Dirac_VDF_Elem Class Reference
Eval_Dirac_VDF_Elem Class Reference
#include <Eval_Dirac_VDF_Elem.h>
Public Member Functions
Eval_Dirac_VDF_Elem ()
~Eval_Dirac_VDF_Elem () override
template<typename Type_Double >
void calculer_terme_source (const int, Type_Double &source) const
void associer_nb_elem_dirac (int n)
void associer_champs (const Champ_Don &)
void mettre_a_jour () override
Public Member Functions inherited from Evaluateur_Source_VDF_Elem
Evaluateur_Source_VDF_Elem ()
Evaluateur_Source_VDF_Elem (const Evaluateur_Source_VDF_Elem &)
void completer () override
Public Member Functions inherited from Evaluateur_Source_VDF
Evaluateur_Source_VDF ()
Evaluateur_Source_VDF (const Evaluateur_Source_VDF &eval)
virtual ~Evaluateur_Source_VDF ()
template<typename Type_Double >
void calculer_terme_source (int, Type_Double &) const
virtual void mettre_a_jour ()=0
virtual void completer ()=0
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
Public Attributes
DoubleVect le_point
Protected Attributes
Ref_Champ_Don la_puissance
Ref_Zone ma_zone
double puissance
double nb_dirac
Protected Attributes inherited from Evaluateur_Source_VDF_Elem
DoubleVect volumes
DoubleVect porosite_vol
porosites volumiques
Protected Attributes inherited from Evaluateur_Source_VDF
Ref_Zone_VDF la_zone
Ref_Zone_Cl_VDF la_zcl
Detailed Description
Definition at line 24 of file Eval_Dirac_VDF_Elem.h.
Constructor & Destructor Documentation
Eval_Dirac_VDF_Elem()
Eval_Dirac_VDF_Elem::Eval_Dirac_VDF_Elem () inline
Definition at line 27 of file Eval_Dirac_VDF_Elem.h.
: puissance(-100.), nb_dirac(-1.) { }
~Eval_Dirac_VDF_Elem()
Eval_Dirac_VDF_Elem::~Eval_Dirac_VDF_Elem () inline override
Definition at line 28 of file Eval_Dirac_VDF_Elem.h.
{ }
Member Function Documentation
associer_champs()
void Eval_Dirac_VDF_Elem::associer_champs (const Champ_Don & Q) inline
Definition at line 42 of file Eval_Dirac_VDF_Elem.h.
{
  la_puissance = Q;
  puissance = Q(0);
}
References la_puissance, and puissance.
Referenced by Source_Dirac_VDF_Elem::associer_pb().
associer_nb_elem_dirac()
void Eval_Dirac_VDF_Elem::associer_nb_elem_dirac (int n) inline
Definition at line 30 of file Eval_Dirac_VDF_Elem.h.
{ nb_dirac = 1./n; }
References nb_dirac.
Referenced by Source_Dirac_VDF_Elem::associer_zones().
calculer_terme_source()
template<typename Type_Double > void Eval_Dirac_VDF_Elem::calculer_terme_source (const int num_elem, Type_Double & source) const
Definition at line 55 of file Eval_Dirac_VDF_Elem.h.
{
  const int size = source.size_array(), test = ma_zone.valeur().type_elem().contient(le_point,num_elem);
  for (int i = 0; i < size; i++) source[i] = (test == 1) ? nb_dirac*puissance : 0.;
}
References Elem_geom::contient(), le_point, ma_zone, nb_dirac, puissance, test(), Zone::type_elem(), and Ref_Zone::valeur().
mettre_a_jour()
void Eval_Dirac_VDF_Elem::mettre_a_jour () inline override virtual
Implements Evaluateur_Source_VDF.
Definition at line 48 of file Eval_Dirac_VDF_Elem.h.
{
  puissance = la_puissance.valeur()(0);
  ma_zone = la_zone.valeur().zone();
}
References la_puissance, Evaluateur_Source_VDF::la_zone, ma_zone, puissance, Ref_Champ_Don::valeur(), Ref_Zone_VDF::valeur(), and Zone_dis_base::zone().
Member Data Documentation
la_puissance
Ref_Champ_Don Eval_Dirac_VDF_Elem::la_puissance protected
Definition at line 37 of file Eval_Dirac_VDF_Elem.h.
Referenced by associer_champs(), and mettre_a_jour().
le_point
DoubleVect Eval_Dirac_VDF_Elem::le_point
Definition at line 34 of file Eval_Dirac_VDF_Elem.h.
Referenced by Source_Dirac_VDF_Elem::associer_pb(), and calculer_terme_source().
ma_zone
Ref_Zone Eval_Dirac_VDF_Elem::ma_zone protected
Definition at line 38 of file Eval_Dirac_VDF_Elem.h.
Referenced by calculer_terme_source(), and mettre_a_jour().
nb_dirac
double Eval_Dirac_VDF_Elem::nb_dirac protected
Definition at line 39 of file Eval_Dirac_VDF_Elem.h.
Referenced by associer_nb_elem_dirac(), and calculer_terme_source().
puissance
double Eval_Dirac_VDF_Elem::puissance protected
Definition at line 39 of file Eval_Dirac_VDF_Elem.h.
Referenced by associer_champs(), calculer_terme_source(), and mettre_a_jour().
The documentation for this class was generated from the following file:
src/VDF/Sources/Evaluateurs/Eval_Dirac_VDF_Elem.h