TRUST: Champ_front_tangentiel_VEF Class Reference
Champ_front_tangentiel_VEF Class Reference
class Champ_front_tangentiel_VEF
Classe derivee de Champ_front_base qui represente les
champs aux frontieres tangentiels :
#include <Champ_front_tangentiel_VEF.h>
Public Member Functions
Champ_front_tangentiel_VEF ()
~Champ_front_tangentiel_VEF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialise le temps courant et Gpoint.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_front_tangentiel_VEF & self_cast (Objet_U &)
static const
Champ_front_tangentiel_VEF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le nom du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Detailed Description
class Champ_front_tangentiel_VEF
Classe derivee de Champ_front_base qui represente les
champs aux frontieres tangentiels :
Definition at line 36 of file Champ_front_tangentiel_VEF.h.
Constructor & Destructor Documentation
Champ_front_tangentiel_VEF::Champ_front_tangentiel_VEF ()
Definition at line 26 of file Champ_front_tangentiel_VEF.cpp.
Champ_front_tangentiel_VEF::~Champ_front_tangentiel_VEF ()
Definition at line 26 of file Champ_front_tangentiel_VEF.cpp.
Member Function Documentation
Objet_U * Champ_front_tangentiel_VEF::cree_instance () [static]
Reimplemented from Champ_front_tangentiel.
Definition at line 26 of file Champ_front_tangentiel_VEF.cpp.
int Champ_front_tangentiel_VEF::duplique () const [virtual]
Reimplemented from Champ_front_tangentiel.
Definition at line 26 of file Champ_front_tangentiel_VEF.cpp.
const Type_info * Champ_front_tangentiel_VEF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_tangentiel.
Definition at line 26 of file Champ_front_tangentiel_VEF.cpp.
const Type_info * Champ_front_tangentiel_VEF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_tangentiel.
Definition at line 26 of file Champ_front_tangentiel_VEF.cpp.
int Champ_front_tangentiel_VEF::initialiser (double temps, const Champ_Inc_base & inco) [virtual]
Initialise le temps courant et Gpoint.
< pour dimensionner
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 50 of file Champ_front_tangentiel_VEF.cpp.
References Zone_VEF::face_normales(), Zone_VF::face_voisins(), Champ_front_base::frontiere_dis(), Ch_front_var_instationnaire_dep::initialiser(), Champ_front_base::les_valeurs, Front_VF::nb_faces(), norme(), Front_VF::num_premiere_face(), Zone_VEF::oriente_normale(), ref_cast, Champ_front_tangentiel::vit_tang, and Champ_front_base::zone_dis().
{
  if (!Champ_front_tangentiel::initialiser(temps,inco))
    return 0;
  const Zone_VEF& zone_VEF = ref_cast(Zone_VEF,zone_dis());
  const Front_VF& le_bord= ref_cast(Front_VF,frontiere_dis());
  int premiere=le_bord.num_premiere_face();
// int derniere=premiere+le_bord.nb_faces();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nb_cases=les_valeurs->nb_cases();
// on traite les faces sur la frontiere
  DoubleTab vecteur_tang(le_bord.nb_faces(),3);
  for(int i=0; i<le_bord.nb_faces(); i++)
    {
      int elem1=face_voisins(i+premiere,0);
      if (elem1 == -1)
        elem1=face_voisins(i+premiere,1);
      int signe = zone_VEF.oriente_normale(i+premiere,elem1);
      vecteur_tang(i,2) = 0.0;
      vecteur_tang (i,0) = -face_normales(i+premiere,1)*signe;
      vecteur_tang (i,1) =face_normales(i+premiere,0)*signe;
      double norme=0.0;
      for (int k=0; k<2; k++)
        norme += vecteur_tang(i,k)* vecteur_tang(i,k);
      norme = sqrt(norme);
// Remplissage de tous les instants
      for (int t=0; t<nb_cases; t++)
        {
          DoubleTab& tab=les_valeurs[t].valeurs();
          tab(i,2)=0.0;
// WEC : Les indices etaient i+premiere.
// Supprime car manifestement un bug !!
// Change aussi dans la zone_Cl_VEF
          for(int j=0; j<2; j++)
            {
              tab(i,j)=vecteur_tang(i,j);
              tab(i,j)*=vit_tang;
              tab(i,j)=tab(i,j)/norme;
            }
        }
    }
  return 1;
}
Sortie & Champ_front_tangentiel_VEF::printOn (Sortie & s) const [protected, virtual]
Imprime le nom du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_tangentiel.
Definition at line 29 of file Champ_front_tangentiel_VEF.cpp.
{
  return Champ_front_tangentiel::printOn(os);
}
Entree & Champ_front_tangentiel_VEF::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_tangentiel.
Definition at line 35 of file Champ_front_tangentiel_VEF.cpp.
References Objet_U::dimension, and Field_base::fixer_nb_comp().
{
  fixer_nb_comp(dimension);
  return Champ_front_tangentiel::readOn(is);
}
Champ_front_tangentiel_VEF & Champ_front_tangentiel_VEF::self_cast (Objet_U & r) [static]
Reimplemented from Champ_front_tangentiel.
Definition at line 26 of file Champ_front_tangentiel_VEF.cpp.
const Champ_front_tangentiel_VEF & Champ_front_tangentiel_VEF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_front_tangentiel.
Definition at line 26 of file Champ_front_tangentiel_VEF.cpp.
unsigned Champ_front_tangentiel_VEF::taille_memoire () const [virtual]
Reimplemented from Champ_front_tangentiel.
Definition at line 26 of file Champ_front_tangentiel_VEF.cpp.
Member Data Documentation
const Type_info Champ_front_tangentiel_VEF::info_obj [static]
Reimplemented from Champ_front_tangentiel.
Definition at line 38 of file Champ_front_tangentiel_VEF.h.
The documentation for this class was generated from the following files:
src/VEF/Champs/Champ_front_tangentiel_VEF.h
src/VEF/Champs/Champ_front_tangentiel_VEF.cpp