TRUST: Champ_Q1_EF Class Reference
Champ_Q1_EF Class Reference
#include <Champ_Q1_EF.h>
Public Member Functions
Champ_Q1_EF ()
~Champ_Q1_EF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Zone_EF & zone_EF () const
void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
int imprime (Sortie &, int) const
void gradient (DoubleTab &)
void cal_rot_ordre1 (DoubleTab &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Q1_EF & self_cast (Objet_U &)
static const Champ_Q1_EF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
virtual Entree & readOn (Entree &)
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Protected Attributes
Ref_Zone_VF la_zone_VF
Detailed Description
Definition at line 31 of file Champ_Q1_EF.h.
Constructor & Destructor Documentation
Champ_Q1_EF::Champ_Q1_EF ()
Definition at line 31 of file Champ_Q1_EF.cpp.
Champ_Q1_EF::~Champ_Q1_EF ()
Definition at line 31 of file Champ_Q1_EF.cpp.
Member Function Documentation
void Champ_Q1_EF::associer_zone_dis_base (const Zone_dis_base & z_dis) [virtual]
Returns:
z_dis
Signification: la zone discretise
Contraintes:
Reimplemented from Champ_base.
Definition at line 79 of file Champ_Q1_EF.cpp.
References la_zone_VF, and ref_cast.
{
  la_zone_VF=ref_cast(Zone_VF, z_dis);
}
void Champ_Q1_EF::cal_rot_ordre1 (DoubleTab & vorticite)
Definition at line 163 of file Champ_Q1_EF.cpp.
References Zone::creer_tableau_elements(), Objet_U::dimension, gradient(), Zone::nb_elem_tot(), Array_base::NOCOPY_NOINIT, verifier(), Zone_dis_base::zone(), and zone_EF().
{
  const Zone_EF& zone_EF_ = zone_EF();
  int nb_elems=zone_EF_.zone().nb_elem_tot();
  DoubleTab gradient_elem(0, dimension, dimension);
// le tableau est initialise dans la methode gradient():
  zone_EF_.zone().creer_tableau_elements(gradient_elem, Array_base::NOCOPY_NOINIT);
  gradient(gradient_elem);
  Debog::verifier("apres calcul gradient",gradient_elem);
  int num_elem;
  switch(dimension)
    {
    case 2 :
      {
        for (num_elem=0; num_elem<nb_elems; num_elem++)
          {
            vorticite(num_elem)=gradient_elem(num_elem,1,0)-gradient_elem(num_elem,0,1);
          }
      }
      break;
    case 3 :
      {
        for (num_elem=0; num_elem<nb_elems; num_elem++)
          {
            vorticite(num_elem,0)=gradient_elem(num_elem,2,1)-gradient_elem(num_elem,1,2);
            vorticite(num_elem,1)=gradient_elem(num_elem,0,2)-gradient_elem(num_elem,2,0);
            vorticite(num_elem,2)=gradient_elem(num_elem,1,0)-gradient_elem(num_elem,0,1);
          }
      }
    }
  Debog::verifier("apres calcul vort",vorticite);
  return ;
}
Objet_U * Champ_Q1_EF::cree_instance () [static]
Definition at line 31 of file Champ_Q1_EF.cpp.
int Champ_Q1_EF::duplique () const [virtual]
Implements Champ_Inc_Q1_base.
Definition at line 31 of file Champ_Q1_EF.cpp.
const Type_info * Champ_Q1_EF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Inc_Q1_base.
Definition at line 31 of file Champ_Q1_EF.cpp.
void Champ_Q1_EF::gradient (DoubleTab & gradient_elem)
< line
< column
< Espace reel uniquement
< composante numero 1, component number 1
< composante numero 2, component number 2
Definition at line 127 of file Champ_Q1_EF.cpp.
References Zone_EF::Bij_thilde(), Objet_U::dimension, DoubleTab::dimension(), MorEqn::equation(), Equation_base::inconnue(), Zone::les_elems(), Zone::nb_elem_tot(), Zone::nb_som_elem(), operator_egal(), Champ_Inc::valeurs(), Zone_EF::volumes_thilde(), Zone_dis_base::zone(), and zone_EF().
Referenced by cal_rot_ordre1().
{
// Calcul du gradient de la vitesse pour le calcul de la vorticite
// Gradient ordre 1 (valeur moyenne dans un element)
// Order 1 gradient (mean value within an element)
  const Zone_EF& zone_EF_ = zone_EF();
  const DoubleTab& vitesse = equation().inconnue().valeurs();
  const IntTab& elems= zone_EF_.zone().les_elems();
  int nb_som_elem=zone_EF_.zone().nb_som_elem();
  int nb_elems=zone_EF_.zone().nb_elem_tot();
  const DoubleVect& volume_thilde=zone_EF_.volumes_thilde();
  const DoubleTab& Bij_thilde=zone_EF_.Bij_thilde();
  assert(gradient_elem.dimension(0) == nb_elems);
  assert(gradient_elem.dimension(1) == dimension); //!< line
  assert(gradient_elem.dimension(2) == dimension); //!< column
  operator_egal(gradient_elem, 0.); //!< Espace reel uniquement
  for (int num_elem=0; num_elem<nb_elems; num_elem++)
    {
      for (int a=0; a<dimension; a++) //!< composante numero 1, component number 1
        {
          for (int b=0; b<dimension; b++) //!< composante numero 2, component number 2
            {
              for (int j=0; j<nb_som_elem; j++)
                {
                  int s = elems(num_elem,j);
                  gradient_elem(num_elem,a,b) += vitesse(s,a)*Bij_thilde(num_elem,j,b);
                }
              gradient_elem(num_elem,a,b) /= volume_thilde(num_elem);
            }
        }
    }
}
int Champ_Q1_EF::imprime (Sortie & os, int ncomp) const [virtual]
Reimplemented from Champ_Inc_base.
Definition at line 102 of file Champ_Q1_EF.cpp.
References Domaine::coord_sommets(), Cout, Objet_U::dimension, Zone::domaine(), finl, Field_base::nb_compo_, Domaine::nb_som(), Champ_Inc_base::valeurs(), Zone_dis_base::zone(), and zone_dis_base().
{
  const Zone_dis_base& zone_dis = zone_dis_base();
  const Zone& zone = zone_dis.zone();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  const int nb_som = zone.domaine().nb_som();
  const DoubleTab& val = valeurs();
  int som;
  os << nb_som << finl;
  for (som=0; som<nb_som; som++)
    {
      if (dimension==3)
        os << coord(som,0) << " " << coord(som,1) << " " << coord(som,2) << " " ;
      if (dimension==2)
        os << coord(som,0) << " " << coord(som,1) << " " ;
      if (nb_compo_ == 1)
        os << val(som) << finl;
      else
        os << val(som,ncomp) << finl;
    }
  os << finl;
  Cout << "Champ_Q1_EF::imprime FIN >>>>>>>>>> " << finl;
  return 1;
}
const Type_info * Champ_Q1_EF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Inc_Q1_base.
Definition at line 31 of file Champ_Q1_EF.cpp.
Sortie & Champ_Q1_EF::printOn (Sortie & os) const [protected, virtual]
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Inc_Q1_base.
Definition at line 35 of file Champ_Q1_EF.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Champ_Q1_EF::readOn (Entree & is) [protected, virtual]
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Inc_Q1_base.
Definition at line 43 of file Champ_Q1_EF.cpp.
References Champ_Inc_base::lire_donnees().
{
  lire_donnees(s) ;
  return s ;
}
const Champ_Q1_EF & Champ_Q1_EF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Inc_Q1_base.
Definition at line 31 of file Champ_Q1_EF.cpp.
Champ_Q1_EF & Champ_Q1_EF::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Inc_Q1_base.
Definition at line 31 of file Champ_Q1_EF.cpp.
unsigned Champ_Q1_EF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 31 of file Champ_Q1_EF.cpp.
const Zone_dis_base & Champ_Q1_EF::zone_dis_base () const [virtual]
Reimplemented from Champ_base.
Definition at line 62 of file Champ_Q1_EF.cpp.
References la_zone_VF, and Ref_Zone_VF::valeur().
Referenced by EF_discretisation::creer_champ_vorticite(), and imprime().
{
  return la_zone_VF.valeur();
}
const Zone_EF & Champ_Q1_EF::zone_EF () const
Returns:
la_zone_EF_Q1.valeur()
Signification:
Contraintes:
Definition at line 97 of file Champ_Q1_EF.cpp.
References la_zone_VF, ref_cast, and Ref_Zone_VF::valeur().
Referenced by cal_rot_ordre1(), and gradient().
{
  return ref_cast(Zone_EF, la_zone_VF.valeur());
}
Member Data Documentation
const Type_info Champ_Q1_EF::info_obj [static]
Reimplemented from Champ_Inc_Q1_base.
Definition at line 33 of file Champ_Q1_EF.h.
Ref_Zone_VF Champ_Q1_EF::la_zone_VF [protected]
Definition at line 46 of file Champ_Q1_EF.h.
Referenced by associer_zone_dis_base(), zone_dis_base(), and zone_EF().
The documentation for this class was generated from the following files:
src/EF/Champs/Champ_Q1_EF.h
src/EF/Champs/Champ_Q1_EF.cpp