TRUST: Traitement_particulier_NS_Profils_VDF Class Reference
Traitement_particulier_NS_Profils_VDF Class Reference
class Trait_part_NS_Profils_VDF
This classe enables a particular treatment
for computations which have a periodic BC (ie homogeneous direction)
and on which we want profiles in a specific direction and position :
+ mean velocity profiles
+ fluctuations<br>.SECTION see also
Navier_Stokes_Turbulent, Traitement_particulier_base,
Traitement_particulier_VDF
#include <Traitement_particulier_NS_Profils_VDF.h>
Public Member Functions
Traitement_particulier_NS_Profils_VDF ()
~Traitement_particulier_NS_Profils_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void post_traitement_particulier (void) override
Entree & lire (const Motcle &, Entree &) override
Entree & lire (Entree &) override
Public Member Functions inherited from Traitement_particulier_NS_Profils
Traitement_particulier_NS_Profils ()
~Traitement_particulier_NS_Profils () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & lire (Entree &) override
void preparer_calcul_particulier (void) override
virtual Entree & lire (const Motcle &, Entree &)=0
void post_traitement_particulier (void) override=0
void reprendre_stat () override
void sauver_stat () const override
void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double) override
Public Member Functions inherited from Traitement_particulier_NS_base
Traitement_particulier_NS_base ()
~Traitement_particulier_NS_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_eqn (const Equation_base &)
virtual void preparer_calcul_particulier (void)=0
virtual void post_traitement_particulier (void)=0
virtual Entree & lire (Entree &is)=0
virtual void sauver_stat (void) const =0
virtual void reprendre_stat (void)=0
virtual void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double)=0
void creer_champ (const Motcle &) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Traitement_particulier_NS_Profils_VDF & self_cast (Objet_U &)
static const Traitement_particulier_NS_Profils_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_Profils
static const Type_info * info ()
static Traitement_particulier_NS_Profils & self_cast (Objet_U &)
static const Traitement_particulier_NS_Profils & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_base
static const Type_info * info ()
static Traitement_particulier_NS_base & self_cast (Objet_U &)
static const Traitement_particulier_NS_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_Profils
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void init_calcul_moyenne (void) override
void calculer_moyenne_spatiale_vitesse (DoubleTab &, DoubleTab &, DoubleTab &, DoubleTab &, const IntTab &, const IntTab &, const IntVect &, const int, const DoubleTab &)
void calculer_moyenne_spatiale_uv (DoubleTab &, const IntTab &, const IntTab &, const IntVect &, const DoubleTab &)
void ecriture_fichiers_moy_spat (const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleVect &, const DoubleVect &, const IntVect &, const DoubleTab &, const int)
void ecriture_fichiers_moy_spat_1col (const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleVect &, const DoubleVect &, const IntVect &, const int)
void calculer_moyenne_spatiale_nut (DoubleTab &, const IntTab &, const IntTab &, const IntVect &, const DoubleTab &)
void calculer_integrale_temporelle (DoubleTab &, DoubleTab &, DoubleTab &, const DoubleVect &, const DoubleVect &)
void ecriture_fichiers_moy_temp (const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const DoubleTab &, const IntVect &, const int, const double)
void ecriture_fichiers_moy_temp_1col (const DoubleTab &, const DoubleTab &, const IntVect &, const int, const double)
Protected Member Functions inherited from Traitement_particulier_NS_Profils
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void init_calcul_stats (void)
virtual void init_calcul_moyenne (void)=0
Sortie & printOn (Sortie &x) const override
Impression de l'equation sur un flot de sortie.
Simple appel a Equation_base::printOn(Sortie&).
Entree & readOn (Entree &) override
Lit les specifications de l'equation de Navier Stokes a
partir d'un flot d'entree.
Simple appel a Navier_Stokes_std::readOn(Entree&)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
DoubleTab Yu_m
DoubleTab Yv_m
DoubleTab Yw_m
DoubleTab Yuv_m
Coordonnees des points ou est definie la vitesse.
DoubleTab Yu_p
DoubleTab Yv_p
DoubleTab Yw_p
DoubleTab Yuv_p
IntTab compt_x_m
IntTab compt_y_m
IntTab compt_z_m
IntTab compt_uv_m
Nombre de points a "meme Y" pour chaque grandeur.
IntTab compt_x_p
IntTab compt_y_p
IntTab compt_z_p
IntTab compt_uv_p
IntTab corresp_u_m
IntTab corresp_v_m
IntTab corresp_w_m
IntTab corresp_uv_m
Correspondance numerotation globale -> numerotation locale dans Yxx.
IntTab corresp_u_p
IntTab corresp_v_p
IntTab corresp_w_p
IntTab corresp_uv_p
DoubleTab xUm
DoubleTab xUp
DoubleTab xWm
DoubleTab xWp
DoubleTab xVm
DoubleTab xVp
DoubleTab xUVm
DoubleTab xUVp
Positions des points juste avant et apres.
DoubleVect delta_Um
DoubleVect delta_Up
DoubleVect delta_Wm
DoubleVect delta_Wp
DoubleVect delta_Vm
DoubleVect delta_Vp
DoubleVect delta_UVm
DoubleVect delta_UVp
Distance (tjrs positive) entre le point avant ou apres et le point du profil, pour faire les interpolations lineaires et trouver les points en question.
Protected Attributes inherited from Traitement_particulier_NS_Profils
DoubleTab u_moy_temp_x
DoubleTab u_moy_temp_y
DoubleTab u_moy_temp_z
DoubleTab uv_moy_temp
DoubleTab u2_moy_temp
DoubleTab v2_moy_temp
DoubleTab w2_moy_temp
DoubleTab u3_moy_temp
DoubleTab v3_moy_temp
DoubleTab w3_moy_temp
DoubleTab u4_moy_temp
DoubleTab v4_moy_temp
DoubleTab w4_moy_temp
DoubleTab nu_t_temp
double temps_deb
double temps_fin
double dt_post_stat
double dt_post_inst
IntVect Nxy
IntVect Nyy
IntVect Nzy
IntVect Nuv
int Nap
Nom fich_repr_u
Nom fich_repr_nu_t
int oui_repr
int oui_u_inst
int oui_stat
int oui_profil_nu_t
int oui_repr_nu_t
int n_probes
DoubleVect positions
int homo_dir
int dir_profil
Protected Attributes inherited from Traitement_particulier_NS_base
Ref_Navier_Stokes_std mon_equation
Champs_compris champs_compris_
Detailed Description
class Trait_part_NS_Profils_VDF
This classe enables a particular treatment
for computations which have a periodic BC (ie homogeneous direction)
and on which we want profiles in a specific direction and position :
+ mean velocity profiles
+ fluctuations<br>.SECTION see also
Navier_Stokes_Turbulent, Traitement_particulier_base,
Traitement_particulier_VDF
Definition at line 37 of file Traitement_particulier_NS_Profils_VDF.h.
Constructor & Destructor Documentation
Traitement_particulier_NS_Profils_VDF()
Traitement_particulier_NS_Profils_VDF::Traitement_particulier_NS_Profils_VDF ()
Definition at line 24 of file Traitement_particulier_NS_Profils_VDF.cpp.
~Traitement_particulier_NS_Profils_VDF()
Traitement_particulier_NS_Profils_VDF::~Traitement_particulier_NS_Profils_VDF ()
Definition at line 24 of file Traitement_particulier_NS_Profils_VDF.cpp.
Member Function Documentation
calculer_integrale_temporelle()
void Traitement_particulier_NS_Profils_VDF::calculer_integrale_temporelle (DoubleTab & u_moy_temp, DoubleTab & umoy_m, DoubleTab & umoy_p, const DoubleVect & delta_m, const DoubleVect & delta_p) protected
Definition at line 1105 of file Traitement_particulier_NS_Profils_VDF.cpp.
{
  int i,j;
  double dt_v = mon_equation->schema_temps().pas_de_temps();
  DoubleTab umoy(u_moy_temp);
  for(i=0; i<n_probes; i++)
    {
      for(j=0; j<Nap; j++)
        {
          umoy(i,j)=umoy_m(i,j)*delta_m(i)/(delta_m(i)+delta_p(i));
          umoy(i,j)+=umoy_p(i,j)*delta_p(i)/(delta_m(i)+delta_p(i));
        }
    }
  if(je_suis_maitre())
//
    u_moy_temp.ajoute_sans_ech_esp_virt(dt_v,umoy);
}
References TRUSTVect< _TYPE_ >::ajoute_sans_ech_esp_virt(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, Schema_Temps_base::pas_de_temps(), and Equation_base::schema_temps().
Referenced by post_traitement_particulier().
calculer_moyenne_spatiale_nut()
void Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut (DoubleTab & u_moy, const IntTab & corresp, const IntTab & compt, const IntVect & tab_Nuv, const DoubleTab & xUV) protected
Definition at line 839 of file Traitement_particulier_NS_Profils_VDF.cpp.
{
  int i,j;
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF=ref_cast(Zone_VDF, zdisbase);
  const DoubleTab& xp = zone_VDF.xp();
  const RefObjU& modele_turbulence = mon_equation.valeur().get_modele(TURBULENCE);
  const Mod_turb_hyd_base& mod_turb = ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur());
  const DoubleTab& nu_t = mod_turb.viscosite_turbulente()->valeurs();
  int nb_elems = zone_VDF.zone().nb_elem();
  int num_elem;
  u_moy = 0.;
  for(i=0; i<n_probes; i++)
    {
// Calcul de nut
      for (num_elem=0; num_elem<nb_elems; num_elem++)
        if(xp(num_elem,dir_profil)==xUV(i))
          {
            u_moy(i,corresp(i,num_elem)) += nu_t[num_elem];
          }
    } //!< on a parcouru tous les profils
// POUR LE PARALLELE
  IntTab compt_p(compt);
  envoyer(compt_p,Process::me(),0,Process::me());
  DoubleTab u_moy_p(u_moy);
  envoyer(u_moy_p,Process::me(),0,Process::me());
  if(je_suis_maitre())
    {
      IntTab compt_tot(compt);
      DoubleTab u_moy_tot(u_moy);
      compt_tot=0;
      u_moy_tot=0.;
      for(int p=0; p<Process::nproc(); p++)
        {
          recevoir(compt_p,p,0,p);
          compt_tot+=compt_p;
          recevoir(u_moy_p,p,0,p);
          u_moy_tot+=u_moy_p;
        }
      for(i=0; i<n_probes; i++)
        for (j=0; j<tab_Nuv(i); j++)
          u_moy(i,j) = u_moy_tot(i,j)/compt_tot(i,j);
    }
// FIN DU PARALLELE
}
References Traitement_particulier_NS_Profils::dir_profil, envoyer(), Equation_base::get_modele(), Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Process::me(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Zone::nb_elem(), Process::nproc(), recevoir(), ref_cast, TURBULENCE, Ref_Objet_U::valeur(), Ref_Navier_Stokes_std::valeur(), Champ_Fonc::valeurs(), Mod_turb_hyd_base::viscosite_turbulente(), Zone_VF::xp(), Zone_dis_base::zone(), and Champ_Inc::zone_dis_base().
Referenced by post_traitement_particulier().
calculer_moyenne_spatiale_uv()
void Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv (DoubleTab & uv_moy, const IntTab & corresp, const IntTab & compt, const IntVect & NN, const DoubleTab & xUV) protected
Definition at line 1003 of file Traitement_particulier_NS_Profils_VDF.cpp.
{
  int i,j;
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF=ref_cast(Zone_VDF, zdisbase);
  const DoubleTab& xp = zone_VDF.xp();
  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  int nb_elems = zone_VDF.zone().nb_elem();
  int num_elem;
  int face_u_0,face_u_1,face_v_0,face_v_1;
  double vitu,vitv;
  DoubleTab u_moy_cent(n_probes,Nap);
  u_moy_cent= 0.;
  DoubleTab v_moy_cent(n_probes,Nap);
  v_moy_cent= 0.;
  uv_moy = 0.;
  for(i=0; i<n_probes; i++)
    {
// Calcul de uv
      for (num_elem=0; num_elem<nb_elems; num_elem++)
        {
          if(xp(num_elem,dir_profil)==xUV(i))
            {
              face_u_0 = elem_faces(num_elem,0);
              face_u_1 = elem_faces(num_elem,dimension);
              vitu = 0.5*(vitesse[face_u_0]+vitesse[face_u_1]);
              face_v_0 = elem_faces(num_elem,1);
              face_v_1 = elem_faces(num_elem,1+dimension);
              vitv = 0.5*(vitesse[face_v_0]+vitesse[face_v_1]);
              uv_moy(i,corresp(i,num_elem)) += vitu*vitv;
              u_moy_cent(i,corresp(i,num_elem)) += vitu;
              v_moy_cent(i,corresp(i,num_elem)) += vitv;
            }
        }
    } //!< On a parcouru tous les profils
// POUR LE PARALLELE
  IntTab compt_p(compt);
  envoyer(compt_p,Process::me(),0,Process::me());
  DoubleTab uv_moy_p(uv_moy);
  envoyer(uv_moy_p,Process::me(),0,Process::me());
  DoubleTab u_moy_cent_p(u_moy_cent);
  envoyer(u_moy_cent_p,Process::me(),0,Process::me());
  DoubleTab v_moy_cent_p(v_moy_cent);
  envoyer(v_moy_cent_p,Process::me(),0,Process::me());
  if(je_suis_maitre())
    {
      IntTab compt_tot(compt);
      DoubleTab uv_moy_tot(uv_moy);
      DoubleTab u_moy_cent_tot(u_moy_cent);
      DoubleTab v_moy_cent_tot(v_moy_cent);
      compt_tot=0;
      uv_moy_tot=0.;
      u_moy_cent_tot=0.;
      v_moy_cent_tot=0.;
      for(int p=0; p<Process::nproc(); p++)
        {
          recevoir(compt_p,p,0,p);
          compt_tot+=compt_p;
          recevoir(uv_moy_p,p,0,p);
          uv_moy_tot+=uv_moy_p;
          recevoir(u_moy_cent_p,p,0,p);
          u_moy_cent_tot+=u_moy_cent_p;
          recevoir(v_moy_cent_p,p,0,p);
          v_moy_cent_tot+=v_moy_cent_p;
        }
      for(i=0; i<n_probes; i++)
        {
          for (j=0; j<NN(i); j++)
            {
              uv_moy(i,j) = uv_moy_tot(i,j)/compt_tot(i,j);
              u_moy_cent(i,j) = u_moy_cent_tot(i,j)/compt_tot(i,j);
              v_moy_cent(i,j) = v_moy_cent_tot(i,j)/compt_tot(i,j);
              uv_moy(i,j) *= -1.;
            }
          for (j=0; j<NN(i); j++)
            uv_moy(i,j) += u_moy_cent(i,j)*v_moy_cent(i,j);
        }
    }
// FIN DU PARALLELE
}
References Objet_U::dimension, Traitement_particulier_NS_Profils::dir_profil, Zone_VF::elem_faces(), envoyer(), Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Process::me(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, Zone::nb_elem(), Process::nproc(), recevoir(), ref_cast, Champ_Inc::valeurs(), Zone_VF::xp(), Zone_dis_base::zone(), and Champ_Inc::zone_dis_base().
Referenced by post_traitement_particulier().
calculer_moyenne_spatiale_vitesse()
void Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse (DoubleTab & u_moy, DoubleTab & u_moy_2, DoubleTab & u_moy_3, DoubleTab & u_moy_4, const IntTab & corresp, const IntTab & compt, const IntVect & NN, const int ori, const DoubleTab & xU) protected
Definition at line 901 of file Traitement_particulier_NS_Profils_VDF.cpp.
{
  int i,j;
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF=ref_cast(Zone_VDF, zdisbase);
  const DoubleTab& xv = zone_VDF.xv();
  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
  int nb_faces = zone_VDF.nb_faces();
  const IntVect& orientation = zone_VDF.orientation();
  int num_face,ori_face;
  double vit;
  u_moy = 0.;
  u_moy_2 = 0.;
  for(i=0; i<n_probes; i++)
    {
      for(num_face=0; num_face<nb_faces; num_face++)
        {
          ori_face = orientation[num_face];
          if ((ori_face==ori)&&(xv(num_face,dir_profil)==xU(i)))
            {
              vit = vitesse[num_face];
              u_moy(i,corresp(i,num_face)) += vit;
              u_moy_2(i,corresp(i,num_face)) += vit*vit;
              u_moy_3(i,corresp(i,num_face)) += vit*vit*vit;
              u_moy_4(i,corresp(i,num_face)) += vit*vit*vit*vit;
            }
        }
    }//!< On a parcouru tous les profils
// POUR LE PARALLELE
  IntTab compt_p(compt);
  envoyer(compt_p,Process::me(),0,Process::me());
  DoubleTab u_moy_p(u_moy);
  envoyer(u_moy_p,Process::me(),0,Process::me());
  DoubleTab u_moy_2_p(u_moy_2);
  envoyer(u_moy_2_p,Process::me(),0,Process::me());
  DoubleTab u_moy_3_p(u_moy_3);
  envoyer(u_moy_3_p,Process::me(),0,Process::me());
  DoubleTab u_moy_4_p(u_moy_4);
  envoyer(u_moy_4_p,Process::me(),0,Process::me());
  if(je_suis_maitre())
    {
      IntTab compt_tot(compt);
      DoubleTab u_moy_tot(u_moy);
      DoubleTab u_moy_2_tot(u_moy_2);
      DoubleTab u_moy_3_tot(u_moy_3);
      DoubleTab u_moy_4_tot(u_moy_4);
      compt_tot=0;
      u_moy_tot=0.;
      u_moy_2_tot=0.;
      u_moy_3_tot=0.;
      u_moy_4_tot=0.;
      for(int p=0; p<Process::nproc(); p++)
        {
          recevoir(compt_p,p,0,p);
          compt_tot+=compt_p;
          recevoir(u_moy_p,p,0,p);
          u_moy_tot+=u_moy_p;
          recevoir(u_moy_2_p,p,0,p);
          u_moy_2_tot+=u_moy_2_p;
          recevoir(u_moy_3_p,p,0,p);
          u_moy_3_tot+=u_moy_3_p;
          recevoir(u_moy_4_p,p,0,p);
          u_moy_4_tot+=u_moy_4_p;
        }
      for(i=0; i<n_probes; i++)
        for (j=0; j<NN(i); j++)
          {
            u_moy(i,j) = u_moy_tot(i,j)/compt_tot(i,j);
            u_moy_2(i,j) = u_moy_2_tot(i,j)/compt_tot(i,j);
            u_moy_3(i,j) = u_moy_3_tot(i,j)/compt_tot(i,j);
            u_moy_4(i,j) = u_moy_4_tot(i,j)/compt_tot(i,j);
          }
    }
// FIN DU PARALLELE
// commente par guillaume
// Calcul de uprime2 ou vprime2 ou wprime2
// for (j=0;j<NN(i);j++)
// u_moy_2(i,j) -= u_moy(i,j)*u_moy(i,j);
}
References Traitement_particulier_NS_Profils::dir_profil, envoyer(), Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Process::me(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Zone_VF::nb_faces(), Process::nproc(), Zone_VDF::orientation(), recevoir(), ref_cast, Champ_Inc::valeurs(), Zone_VF::xv(), and Champ_Inc::zone_dis_base().
Referenced by post_traitement_particulier().
cree_instance()
Objet_U * Traitement_particulier_NS_Profils_VDF::cree_instance () static
Definition at line 24 of file Traitement_particulier_NS_Profils_VDF.cpp.
duplique()
int Traitement_particulier_NS_Profils_VDF::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Traitement_particulier_NS_Profils_VDF.cpp.
ecriture_fichiers_moy_spat()
void Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat (const DoubleTab & umoy_m, const DoubleTab & umoy_2_m, const DoubleTab & umoy_3_m, const DoubleTab & umoy_4_m, const DoubleTab & umoy_p, const DoubleTab & umoy_2_p, const DoubleTab & umoy_3_p, const DoubleTab & umoy_4_p, const DoubleVect & delta_m, const DoubleVect & delta_p, const IntVect & NN, const DoubleTab & Y, const int ori) protected
Definition at line 1127 of file Traitement_particulier_NS_Profils_VDF.cpp.
{
  int i,j;
  for(i=0; i<n_probes; i++)
    {
      Nom nom_fic ="./Space_Avg/Avg_vel_";
      switch(ori)
        {
        case 0:
          {
            nom_fic +="U_";
            break;
          }
        case 1:
          {
            nom_fic +="V_";
            break;
          }
        case 2:
          {
            nom_fic +="W_";
            break;
          }
        }
      switch(dir_profil)
        {
        case 0:
          {
            nom_fic +="X_";
            break;
          }
        case 1:
          {
            nom_fic +="Y_";
            break;
          }
        case 2:
          {
            nom_fic +="Z_";
            break;
          }
        }
      Nom pos  = Nom(positions(i));
      nom_fic += pos;
      nom_fic += "_t_";
      double tps = mon_equation->inconnue().temps();
      Nom temps  = Nom(tps);
      nom_fic   += temps;
      nom_fic   += ".dat";
// Pour calculer les interpolations lineaires...
      DoubleTab umoy(umoy_m);
      DoubleTab umoy_2(umoy_2_m);
      DoubleTab umoy_3(umoy_3_m);
      DoubleTab umoy_4(umoy_4_m);
      for(j=0; j<NN(i); j++)
        {
          umoy(i,j)=umoy_m(i,j)*delta_m(i)/(delta_m(i)+delta_p(i));
          umoy(i,j)+=umoy_p(i,j)*delta_p(i)/(delta_m(i)+delta_p(i));
          umoy_2(i,j)=umoy_2_m(i,j)*delta_m(i)/(delta_m(i)+delta_p(i));
          umoy_2(i,j)+=umoy_2_p(i,j)*delta_p(i)/(delta_m(i)+delta_p(i));
          umoy_3(i,j)=umoy_3_m(i,j)*delta_m(i)/(delta_m(i)+delta_p(i));
          umoy_3(i,j)+=umoy_3_p(i,j)*delta_p(i)/(delta_m(i)+delta_p(i));
          umoy_4(i,j)=umoy_4_m(i,j)*delta_m(i)/(delta_m(i)+delta_p(i));
          umoy_4(i,j)+=umoy_4_p(i,j)*delta_p(i)/(delta_m(i)+delta_p(i));
        }
      if(je_suis_maitre())
        {
          SFichier fic (nom_fic);
          double val_moy, val2,val3,val4;
          fic << "# Space Averaged Statistics" << finl ;
          fic << "# Y       <U>       Urms       S=MOY[(u-umoy)^3]/(MOY[(u-umoy)^2])^3/2       F=MOY[(u-umoy)^4]/(MOY[(u-umoy)^2])^2       " << finl ;
          for (j=0; j<NN(i)  ; j++)
            {
              val_moy = umoy(i,j);
// Pour eviter NAN, on prend le std::max(,0):
              val2 = sqrt(std::max(umoy_2(i,j)-val_moy*val_moy,0.0));
              if (val2 ==0 )
                {
                  val3=0.;
                  val4=0.;
                }
              else
                {
                  val3 = umoy_3(i,j)+2*val_moy*val_moy*val_moy-3*umoy_2(i,j)*val_moy;
                  val3 = val3/pow(val2,3);
                  val4 = umoy_4(i,j)-4*umoy_3(i,j)*val_moy+6*umoy_2(i,j)*val_moy*val_moy-3*val_moy*val_moy*val_moy*val_moy;
                  val4 = val4/pow(val2,4);
                }
              if ((val_moy<0.)&&(std::fabs(val_moy)<1.e-10)) val_moy=0.;
              fic << Y (i,j) << "   " << umoy(i,j) << "   " << val2 << "   " << val3 << "   " << val4 << finl;
            }
          fic.flush();
          fic.close();
        } //!< Fin du si je suis maitre
    }//FIN boucle sur les probes
}
References Sortie_Fichier_base::close(), Traitement_particulier_NS_Profils::dir_profil, finl, Sortie_Fichier_base::flush(), Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::positions, and Champ_Inc::temps().
Referenced by post_traitement_particulier().
ecriture_fichiers_moy_spat_1col()
void Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat_1col (const DoubleTab & umoy_m, const DoubleTab & umoy_p, const DoubleTab & Y, const DoubleVect & delta_m, const DoubleVect & delta_p, const IntVect & NN, const int ori) protected
Definition at line 1235 of file Traitement_particulier_NS_Profils_VDF.cpp.
{
  int i,j;
  Nom nom_fic;
  for(i=0; i<n_probes; i++)
    {
      switch(ori)
        {
        case 3:
          {
            nom_fic ="./Space_Avg/Avg_vel_uvp_";
            break;
          }
        case 4:
          {
            nom_fic ="./Space_Avg/Avg_nut_";
            break;
          }
        }
      switch(dir_profil)
        {
        case 0:
          {
            nom_fic +="X_";
            break;
          }
        case 1:
          {
            nom_fic +="Y_";
            break;
          }
        case 2:
          {
            nom_fic +="Z_";
            break;
          }
        }
      Nom pos  = Nom(positions(i));
      nom_fic += pos;
      nom_fic += "_t_";
      double tps = mon_equation->inconnue().temps();
      Nom temps = Nom(tps);
      nom_fic+= temps;
      nom_fic+= ".dat";
      if(je_suis_maitre())
        {
          SFichier fic (nom_fic);
// Pour calculer les interpolations lineaires...
          DoubleTab umoy(umoy_m);
          for(j=0; j<NN(i); j++)
            {
              umoy(i,j)=umoy_m(i,j)*delta_m(i)/(delta_m(i)+delta_p(i));
              umoy(i,j)+=umoy_p(i,j)*delta_p(i)/(delta_m(i)+delta_p(i));
            }
          for (j=0; j<NN(i); j++)
            fic << Y (i,j) << " " << umoy(i,j) << finl;
          fic.flush();
          fic.close();
        } //!< Fin de si je suis maitre
    }//FIN boucle sur les probes
}
References Sortie_Fichier_base::close(), Traitement_particulier_NS_Profils::dir_profil, finl, Sortie_Fichier_base::flush(), Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::positions, and Champ_Inc::temps().
Referenced by post_traitement_particulier().
ecriture_fichiers_moy_temp()
void Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp (const DoubleTab & umoy, const DoubleTab & umoy_2, const DoubleTab & umoy_3, const DoubleTab & umoy_4, const DoubleTab & Y, const IntVect & NN, const int ori, const double dt) protected
Definition at line 1304 of file Traitement_particulier_NS_Profils_VDF.cpp.
{
  int i,j;
  Nom nom_fic;
  for(i=0; i<n_probes; i++)
    {
      nom_fic ="./Time_Avg/Avg_time_vel_";
      switch(ori)
        {
        case 0:
          {
            nom_fic +="U_";
            break;
          }
        case 1:
          {
            nom_fic +="V_";
            break;
          }
        case 2:
          {
            nom_fic +="W_";
            break;
          }
        }
      switch(dir_profil)
        {
        case 0:
          {
            nom_fic +="X_";
            break;
          }
        case 1:
          {
            nom_fic +="Y_";
            break;
          }
        case 2:
          {
            nom_fic +="Z_";
            break;
          }
        }
      Nom pos  = Nom(positions(i));
      nom_fic += pos;
      nom_fic += "_t_";
      double tps = mon_equation->inconnue().temps();
      Nom temps = Nom(tps);
      nom_fic+= temps;
      nom_fic+= ".dat";
      if(je_suis_maitre())
        {
          SFichier fic (nom_fic);
          double val_moy,val2,val3,val4;
          fic << "# Time Averaged Statistics" << finl ;
          fic << "# Y       <U>       Urms       S=MOY[(u-umoy)^3]/(MOY[(u-umoy)^2])^3/2       F=MOY[(u-umoy)^4]/(MOY[(u-umoy)^2])^2       " << finl ;
          for (j=0; j<NN(i)  ; j++)
            {
              val_moy = umoy(i,j)/dt;
              val2 = umoy_2(i,j)/dt -val_moy*val_moy;
// Pour eviter NAN, on prend le std::max(,0):
              val2 = sqrt(std::max(val2,0.0));
              if (val2 ==0.0 )
                {
                  val3=0.;
                  val4=0.;
                }
              else
                {
                  val3 = umoy_3(i,j)/dt+2*val_moy*val_moy*val_moy-3*umoy_2(i,j)/dt*val_moy;
                  val3 = val3/pow(val2,3);
                  val4 = umoy_4(i,j)/dt-4*umoy_3(i,j)/dt*val_moy+6*umoy_2(i,j)/dt*val_moy*val_moy-3*val_moy*val_moy*val_moy*val_moy;
                  val4 = val4/pow(val2,4);
                }
              if ((val_moy<0.)&&(std::fabs(val_moy)<1.e-10)) val_moy=0.;
              fic << Y (i,j) << "   " << val_moy << "   "  << val2 <<  "   " << val3 <<  "   " << val4 << finl;
            }
          fic.flush();
          fic.close();
        } //!< Fin de si je suis maitre
    }//FIN boucle sur les probes
}
References Sortie_Fichier_base::close(), Traitement_particulier_NS_Profils::dir_profil, finl, Sortie_Fichier_base::flush(), Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::positions, and Champ_Inc::temps().
Referenced by post_traitement_particulier().
ecriture_fichiers_moy_temp_1col()
void Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp_1col (const DoubleTab & umoy, const DoubleTab & Y, const IntVect & NN, const int ori, const double dt) protected
Definition at line 1396 of file Traitement_particulier_NS_Profils_VDF.cpp.
{
  int i,j;
  Nom nom_fic;
  for(i=0; i<n_probes; i++)
    {
      switch(ori)
        {
        case 3:
          {
            nom_fic ="./Time_Avg/Avg_time_vel_uvp_";
            break;
          }
        case 4:
          {
            nom_fic ="./Time_Avg/Avg_time_nut_";
            break;
          }
        }
      switch(dir_profil)
        {
        case 0:
          {
            nom_fic +="X_";
            break;
          }
        case 1:
          {
            nom_fic +="Y_";
            break;
          }
        case 2:
          {
            nom_fic +="Z_";
            break;
          }
        }
      Nom pos  = Nom(positions(i));
      nom_fic += pos;
      nom_fic += "_t_";
      double tps = mon_equation->inconnue().temps();
      Nom temps = Nom(tps);
      nom_fic+= temps;
      nom_fic+= ".dat";
      if(je_suis_maitre())
        {
          SFichier fic (nom_fic);
          for (j=0; j<NN(i)  ; j++)
            fic << Y (i,j) << " " << umoy(i,j)/dt << finl;
          fic.flush();
          fic.close();
        } //!< Fin de si je suis maitre
    }//FIN boucle sur les probes
}
References Sortie_Fichier_base::close(), Traitement_particulier_NS_Profils::dir_profil, finl, Sortie_Fichier_base::flush(), Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::positions, and Champ_Inc::temps().
Referenced by post_traitement_particulier().
get_info()
const Type_info * Traitement_particulier_NS_Profils_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Traitement_particulier_NS_Profils.
Definition at line 24 of file Traitement_particulier_NS_Profils_VDF.cpp.
info()
const Type_info * Traitement_particulier_NS_Profils_VDF::info () static
Definition at line 24 of file Traitement_particulier_NS_Profils_VDF.cpp.
init_calcul_moyenne()
void Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne (void) override protected virtual
< nombre de y pour umoy
< nombre de y pour uv_moy (et pour nu_t!!)
Implements Traitement_particulier_NS_Profils.
Definition at line 245 of file Traitement_particulier_NS_Profils_VDF.cpp.
{
// On va initialiser les differents parametres membres de la classe
// utiles au calcul des differentes moyennes
// Initialisation de : Yu,Yv,Yw,Yuv + compt_x,compt_y,compt_z,compt_uv
// + corresp_u,corresp_v,corresp_w,corresp_uv
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF=ref_cast(Zone_VDF, zdisbase);
  const DoubleTab& xv = zone_VDF.xv();
  const DoubleTab& xp = zone_VDF.xp();
  int nb_faces = zone_VDF.nb_faces();
  int nb_elems = zone_VDF.zone().nb_elem();
  const IntVect& orientation = zone_VDF.orientation();
  int num_face,num_elem,ori,indic_m,indicv_m,indicw_m,indicuv_m,indic_p,indicv_p,indicw_p,indicuv_p,trouve;
  int i,j;
  double y;
  j=0;
  indic_m = indic_p = 0;
  indicv_m = indicv_p = 0;
  indicw_m = indicw_p = 0;
  indicuv_m = indicuv_p = 0;
// initialisation des differentes tailles de tableaux
  Nxy.resize(n_probes);
  Nyy.resize(n_probes);
  Nzy.resize(n_probes);
  Nuv.resize(n_probes);
  Nxy = Nap;
  Nyy = Nap;
  Nzy = Nap;
  Nuv = Nap;
// dimensionnement aux valeurs rentrees dans le jeu de donnees
// The points before the value of the probe
  xUm.resize(n_probes);
  xWm.resize(n_probes);
  xVm.resize(n_probes);
  xUVm.resize(n_probes);
  delta_Um.resize(n_probes);
  delta_Wm.resize(n_probes);
  delta_Vm.resize(n_probes);
  delta_UVm.resize(n_probes);
// The points after the value of the probe
  xUp.resize(n_probes);
  xWp.resize(n_probes);
  xVp.resize(n_probes);
  xUVp.resize(n_probes);
  delta_Up.resize(n_probes);
  delta_Wp.resize(n_probes);
  delta_Vp.resize(n_probes);
  delta_UVp.resize(n_probes);
// initialisation
// The points before the value of the probe
  Yu_m = -100.;
  Yv_m = -100.;
  Yw_m = -100.;
  Yuv_m = -100.;
  compt_x_m = 0;
  compt_y_m = 0;
  compt_z_m = 0;
  compt_uv_m = 0;
  corresp_u_m = -1;
  corresp_v_m = -1;
  corresp_w_m = -1;
  corresp_uv_m = -1;
// The points after the value of the probe
  Yu_p = -100.;
  Yv_p = -100.;
  Yw_p = -100.;
  Yuv_p = -100.;
  compt_x_p = 0;
  compt_y_p = 0;
  compt_z_p = 0;
  compt_uv_p = 0;
  corresp_u_p = -1;
  corresp_v_p = -1;
  corresp_w_p = -1;
  corresp_uv_p = -1;
  delta_Um=delta_Up=delta_Wm=delta_Wp=delta_Vm=delta_Vp=delta_UVm=delta_UVp=10000000.;
  Cerr << (int)system("mkdir Space_Avg") << finl;
  Cerr << (int)system("mkdir Time_Avg") << finl;
// remplissage des tableaux ci-dessus
// On cherche tout d'abord les coordonnees des points les plus proches de chaque cote et on les stocke
  for(i=0; i<n_probes; i++)
    {
// Boucle sur les faces
      for (num_face=0; num_face<nb_faces; num_face++)
        {
          ori = orientation(num_face);
          if((xv(num_face,dir_profil)-positions(i))>=0)
            {
              if(ori==0)
                {
                  if((xv(num_face,dir_profil)-positions(i))<delta_Up(i))
                    {
                      xUp(i)=xv(num_face,dir_profil);
                      delta_Up(i)=xv(num_face,dir_profil)-positions(i);
                    }
                }
              else if(ori==2)
                {
                  if((xv(num_face,dir_profil)-positions(i))<delta_Wp(i))
                    {
                      xWp(i)=xv(num_face,dir_profil);
                      delta_Wp(i)=xv(num_face,dir_profil)-positions(i);
                    }
                }
              else if(ori==1)
                {
                  if((xv(num_face,dir_profil)-positions(i))<delta_Vp(i))
                    {
                      xVp(i)=xv(num_face,dir_profil);
                      delta_Vp(i)=xv(num_face,dir_profil)-positions(i);
                    }
                }
              else
                {
                  Cerr << "Pb dans Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne" << finl;
                  Cerr << "Pb avec la direction de la face!" << finl;
                  exit();
                }
            }
          else
            {
              if(ori==0)
                {
                  if((positions(i)-xv(num_face,dir_profil))<delta_Um(i))
                    {
                      xUm(i)=xv(num_face,dir_profil);
                      delta_Um(i)=positions(i)-xv(num_face,dir_profil);
                    }
                }
              else if(ori==2)
                {
                  if((positions(i)-xv(num_face,dir_profil))<delta_Wm(i))
                    {
                      xWm(i)=xv(num_face,dir_profil);
                      delta_Wm(i)=positions(i)-xv(num_face,dir_profil);
                    }
                }
              else if(ori==1)
                {
                  if((positions(i)-xv(num_face,dir_profil))<delta_Vm(i))
                    {
                      xVm(i)=xv(num_face,dir_profil);
                      delta_Vm(i)=positions(i)-xv(num_face,dir_profil);
                    }
                }
              else
                {
                  Cerr << "Pb dans Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne" << finl;
                  Cerr << "Pb avec la direction de la face!" << finl;
                  exit();
                }
            }
        }
// Boucle sur les elements
      for (num_elem=0; num_elem<nb_elems; num_elem++)
        {
          if((xp(num_elem,dir_profil)-positions(i))>=0)
            {
              if((xp(num_elem,dir_profil)-positions(i))<delta_UVp(i))
                {
                  xUVp(i)=xp(num_elem,dir_profil);
                  delta_UVp(i)=xp(num_elem,dir_profil)-positions(i);
                }
            }
          else
            {
              if((positions(i)-xp(num_elem,dir_profil))<delta_UVm(i))
                {
                  xUVm(i)=xp(num_elem,dir_profil);
                  delta_UVm(i)=positions(i)-xp(num_elem,dir_profil);
                }
            }
        }//Fin boucle sur les elements
    }
  int numb_del_probes=0;
// Verification des sondes pour voir si elles sont bien toutes definies
// dans le domaine de calcul
  for(i=0; i<n_probes; i++)
    {
      if((delta_Um(i)==10000000)||(delta_Up(i)==10000000)||
          (delta_Wm(i)==10000000)||(delta_Wp(i)==10000000)||
          (delta_Vm(i)==10000000)||(delta_Vp(i)==10000000)||
          (delta_UVm(i)==10000000)||(delta_UVp(i)==10000000))
        {
          Cerr << "Probe Number " << i+1+numb_del_probes << " undefined in computational domain." << finl;
          Cerr << "It will be deleted from profile list !" << finl;
          n_probes--;
          numb_del_probes++;
          for(j=i; j<n_probes; j++)
            {
              delta_Um(j)=delta_Um(j+1);
              delta_Up(j)=delta_Up(j+1);
              delta_Wm(j)=delta_Wm(j+1);
              delta_Wp(j)=delta_Wp(j+1);
              delta_Vm(j)=delta_Vm(j+1);
              delta_Vp(j)=delta_Vp(j+1);
              delta_UVm(j)=delta_UVm(j+1);
              delta_UVp(j)=delta_UVp(j+1);
              xUm(j)=xUm(j+1);
              xUp(j)=xUp(j+1);
              xWm(j)=xWm(j+1);
              xWp(j)=xWp(j+1);
              xVm(j)=xVm(j+1);
              xVp(j)=xVp(j+1);
              xUVm(j)=xUVm(j+1);
              xUVp(j)=xUVp(j+1);
              positions(j)=positions(j+1);
            }
          i=i-1;
        }
    }
// Dimensionnement maintenant que l'on connait le nombre exact de probes
  Yu_m.resize(n_probes,Nap);
  Yv_m.resize(n_probes,Nap);
  Yw_m.resize(n_probes,Nap);
  Yuv_m.resize(n_probes,Nap);
  compt_x_m.resize(n_probes,Nap);
  compt_y_m.resize(n_probes,Nap);
  compt_z_m.resize(n_probes,Nap);
  compt_uv_m.resize(n_probes,Nap);
  corresp_u_m.resize(n_probes,nb_faces);
  corresp_v_m.resize(n_probes,nb_faces);
  corresp_w_m.resize(n_probes,nb_faces);
  corresp_uv_m.resize(n_probes,nb_elems);
  Yu_p.resize(n_probes,Nap);
  Yv_p.resize(n_probes,Nap);
  Yw_p.resize(n_probes,Nap);
  Yuv_p.resize(n_probes,Nap);
  compt_x_p.resize(n_probes,Nap);
  compt_y_p.resize(n_probes,Nap);
  compt_z_p.resize(n_probes,Nap);
  compt_uv_p.resize(n_probes,Nap);
  corresp_u_p.resize(n_probes,nb_faces);
  corresp_v_p.resize(n_probes,nb_faces);
  corresp_w_p.resize(n_probes,nb_faces);
  corresp_uv_p.resize(n_probes,nb_elems);
// Impression dans le Cerr pour verifications
  Cerr << finl;
  Cerr << "       UPPER/LOWER BOUNDS FOR PROFILES :" << finl;
  for(i=0; i<n_probes; i++)
    {
      Cerr << "Profile " << i+1 << " : X= " << positions(i) << finl;
      Cerr << "xUm= " << xUm(i) << " xUp= " << xUp(i) << finl;
      Cerr << "xElm= " << xUVm(i) << " xElp= " << xUVp(i) << finl;
      Cerr << finl;
    }
// On remplit les tableaux de correspondances
  for(i=0; i<n_probes; i++)
    {
      indic_m = indic_p = 0;
      indicv_m = indicv_p = 0;
      indicw_m = indicw_p = 0;
      indicuv_m = indicuv_p = 0;
// Boucle sur les faces pour avoir la correspondance pour les composantes de la vitesse.
      for (num_face=0; num_face<nb_faces; num_face++)
        {
          ori = orientation(num_face);
          switch(ori)
            {
// Pour la composante de vitesse U
            case 0:
              {
// Point avant
                if(xv(num_face,dir_profil)==xUm(i))
                  {
                    y = xv(num_face,3-homo_dir-dir_profil);
                    trouve = 0;
                    for (j=0; j-(indic_m+1)<0; j++)
                      {
                        if (j==Nap)
{
                            Cerr << "Erreur dans la valeur du nombre de points pour le traitement particulier"<<finl;
                            Cerr <<"qui est trop petite dans votre jeu de donnees=" << Nap << finl;
                            exit();
                          }
                        if(est_egal(y,Yu_m(i,j)))
{
                            corresp_u_m(i,num_face) = j;
                            compt_x_m(i,j) ++;
                            j=indic_m+1;
                            trouve = 1;
                          }
                      }
                    if (trouve==0)
                      {
                        corresp_u_m(i,num_face) = indic_m;
                        Yu_m(i,indic_m)=y;
                        compt_x_m(i,indic_m) ++;
                        indic_m++;
                      }
                  }
// Point apres
                else if(xv(num_face,dir_profil)==xUp(i))
                  {
                    y = xv(num_face,3-homo_dir-dir_profil);
                    trouve = 0;
                    for (j=0; j-(indic_p+1)<0; j++)
                      {
                        if (j==Nap)
{
                            Cerr << "Erreur dans la valeur du nombre de points pour le traitement particulier"<<finl;
                            Cerr <<"qui est trop petite dans votre jeu de donnees=" << Nap << finl;
                            exit();
                          }
                        if(est_egal(y,Yu_p(i,j)))
{
                            corresp_u_p(i,num_face) = j;
                            compt_x_p(i,j) ++;
                            j=indic_p+1;
                            trouve = 1;
                          }
                      }
                    if (trouve==0)
                      {
                        corresp_u_p(i,num_face) = indic_p;
                        Yu_p(i,indic_p)=y;
                        compt_x_p(i,indic_p) ++;
                        indic_p++;
                      }
                  }
                break;
              }
// Pour la composante de vitesse V
            case 1 :
              {
// Point avant
                if(xv(num_face,dir_profil)==xVm(i))
                  {
                    y = xv(num_face,3-homo_dir-dir_profil);
                    trouve = 0;
                    for (j=0; j-(indicv_m+1)<0; j++)
                      {
                        if (j==Nap)
{
                            Cerr << "Erreur dans la valeur du nombre de points pour le traitement particulier"<<finl;
                            Cerr <<"qui est trop petite dans votre jeu de donnees=" << Nap << finl;
                            exit();
                          }
                        if(est_egal(y,Yv_m(i,j)))
{
                            corresp_v_m(i,num_face) = j;
                            compt_y_m(i,j) ++;
                            j=indicv_m+1;
                            trouve = 1;
                          }
                      }
                    if (trouve==0)
                      {
                        corresp_v_m(i,num_face) = indicv_m;
                        Yv_m(i,indicv_m)=y;
                        compt_y_m(i,indicv_m) ++;
                        indicv_m++;
                      }
                  }
// Point apres
                else if(xv(num_face,dir_profil)==xVp(i))
                  {
                    y = xv(num_face,3-homo_dir-dir_profil);
                    trouve = 0;
                    for (j=0; j-(indicv_p+1)<0; j++)
                      {
                        if (j==Nap)
{
                            Cerr << "Erreur dans la valeur du nombre de points pour le traitement particulier"<<finl;
                            Cerr <<"qui est trop petite dans votre jeu de donnees=" << Nap << finl;
                            exit();
                          }
                        if(est_egal(y,Yv_p(i,j)))
{
                            corresp_v_p(i,num_face) = j;
                            compt_y_p(i,j) ++;
                            j=indicv_p+1;
                            trouve = 1;
                          }
                      }
                    if (trouve==0)
                      {
                        corresp_v_p(i,num_face) = indicv_p;
                        Yv_p(i,indicv_p)=y;
                        compt_y_p(i,indicv_p) ++;
                        indicv_p++;
                      }
                  }
                break;
              }
// Pour la composante de vitesse W
            case 2 :
              {
// Point avant
                if(xv(num_face,dir_profil)==xWm(i))
                  {
                    y = xv(num_face,3-homo_dir-dir_profil);
                    trouve = 0;
                    for (j=0; j-(indicw_m+1)<0; j++)
                      {
                        if (j==Nap)
{
                            Cerr << "Erreur dans la valeur du nombre de points pour le traitement particulier"<<finl;
                            Cerr <<"qui est trop petite dans votre jeu de donnees=" << Nap << finl;
                            exit();
                          }
                        if(est_egal(y,Yw_m(i,j)))
{
                            corresp_w_m(i,num_face) = j;
                            compt_z_m(i,j) ++;
                            j=indicw_m+1;
                            trouve = 1;
                          }
                      }
                    if (trouve==0)
                      {
                        corresp_w_m(i,num_face) = indicw_m;
                        Yw_m(i,indicw_m)=y;
                        compt_z_m(i,indicw_m) ++;
                        indicw_m++;
                      }
                  }
// Point apres
                else if(xv(num_face,dir_profil)==xWp(i))
                  {
                    y = xv(num_face,3-homo_dir-dir_profil);
                    trouve = 0;
                    for (j=0; j-(indicw_p+1)<0; j++)
                      {
                        if (j==Nap)
{
                            Cerr << "Erreur dans la valeur du nombre de points pour le traitement particulier"<<finl;
                            Cerr <<"qui est trop petite dans votre jeu de donnees=" << Nap << finl;
                            exit();
                          }
                        if(est_egal(y,Yw_p(i,j)))
{
                            corresp_w_p(i,num_face) = j;
                            compt_z_p(i,j) ++;
                            j=indicw_p+1;
                            trouve = 1;
                          }
                      }
                    if (trouve==0)
                      {
                        corresp_w_p(i,num_face) = indicw_p;
                        Yw_p(i,indicw_p)=y;
                        compt_z_p(i,indicw_p) ++;
                        indicw_p++;
                      }
                  }
                break;
              }
            default :
              {
                Cerr << "Cas de figure impossible..." << finl;
                exit();
                break;
              }
            }//Fin du switch
        }//Fin de boucle sur faces
// Boucle sur les elements pour table de correspondance pour nu_t et temperature
      for (num_elem=0; num_elem<nb_elems; num_elem++)
        {
// Point avant
          if(xp(num_elem,dir_profil)==xUVm(i))
            {
              y = xp(num_elem,3-homo_dir-dir_profil);
              trouve = 0;
              for (j=0; j-(indicuv_m+1)<0; j++)
                {
                  if(y==Yuv_m(i,j))
                    {
                      corresp_uv_m(i,num_elem) = j;
                      compt_uv_m(i,j) ++;
                      j=indicuv_m+1;
                      trouve = 1;
                    }
                }
              if (trouve==0)
                {
                  corresp_uv_m(i,num_elem) = indicuv_m;
                  Yuv_m(i,indicuv_m)=y;
                  compt_uv_m(i,indicuv_m) ++;
                  indicuv_m++;
                }
            }
// Point apres
          if(xp(num_elem,dir_profil)==xUVp(i))
            {
              y = xp(num_elem,3-homo_dir-dir_profil);
              trouve = 0;
              for (j=0; j-(indicuv_p+1)<0; j++)
                {
                  if(y==Yuv_p(i,j))
                    {
                      corresp_uv_p(i,num_elem) = j;
                      compt_uv_p(i,j) ++;
                      j=indicuv_p+1;
                      trouve = 1;
                    }
                }
              if (trouve==0)
                {
                  corresp_uv_p(i,num_elem) = indicuv_p;
                  Yuv_p(i,indicuv_p)=y;
                  compt_uv_p(i,indicuv_p) ++;
                  indicuv_p++;
                }
            }
        }//Fin de boucle sur elements
// Verification pour voir si avant et apres le profil on a le meme nombre de points...
// Ce n'est pas le cas si par exemple on a une marche et un profil juste sur l'arete :
// dans ce cas, on a plus de points du cote du bas de la marche que du cote du haut de la marche.
      if(indic_p!=indic_m)
        {
          Cerr << "indic_m = " << indic_m << " != indic_p = " << indic_p << finl;
          Cerr << "Problem : move profile at position " << positions(i) <<" !" << finl;
          exit();
        }
      if(indicv_p!=indicv_m)
        {
          Cerr << "indicv_m = " << indicv_m << " != indicv_p = " << indicv_p << finl;
          Cerr << "Problem : move profile at position " << positions(i) <<" !" << finl;
          exit();
        }
      if(indicw_p!=indicw_m)
        {
          Cerr << "indicw_m = " << indicw_m << " != indicw_p = " << indicw_p << finl;
          Cerr << "Problem : move profile at position " << positions(i) <<" !" << finl;
          exit();
        }
      if(indicuv_p!=indicuv_m)
        {
          Cerr << "indicuv_m = " << indicuv_m << " != indicuv_p = " << indicuv_p << finl;
          Cerr << "Problem : move profile at position " << positions(i) <<" !" << finl;
          exit();
        }
      Nxy(i) = indic_m;    //!< nombre de y pour umoy
      Nyy(i) = indicv_m;
      Nzy(i) = indicw_m;
      Nuv(i) = indicuv_m;  //!< nombre de y pour uv_moy (et pour nu_t!!)
    }//Fin de boucle sur probes
}
References Cerr, compt_uv_m, compt_uv_p, compt_x_m, compt_x_p, compt_y_m, compt_y_p, compt_z_m, compt_z_p, corresp_u_m, corresp_u_p, corresp_uv_m, corresp_uv_p, corresp_v_m, corresp_v_p, corresp_w_m, corresp_w_p, delta_Um, delta_Up, delta_UVm, delta_UVp, delta_Vm, delta_Vp, delta_Wm, delta_Wp, Traitement_particulier_NS_Profils::dir_profil, est_egal(), Process::exit(), finl, Traitement_particulier_NS_Profils::homo_dir, Navier_Stokes_std::inconnue(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, Zone::nb_elem(), Zone_VF::nb_faces(), Traitement_particulier_NS_Profils::Nuv, Traitement_particulier_NS_Profils::Nxy, Traitement_particulier_NS_Profils::Nyy, Traitement_particulier_NS_Profils::Nzy, Zone_VDF::orientation(), Traitement_particulier_NS_Profils::positions, ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), Zone_VF::xp(), xUm, xUp, xUVm, xUVp, Zone_VF::xv(), xVm, xVp, xWm, xWp, Yu_m, Yu_p, Yuv_m, Yuv_p, Yv_m, Yv_p, Yw_m, Yw_p, Zone_dis_base::zone(), and Champ_Inc::zone_dis_base().
Referenced by Traitement_particulier_NS_Profils_thermo_VDF::init_calcul_moyenne(), and Traitement_particulier_NS_Profils_thermo_VDF::preparer_calcul_particulier().
lire() [1/2]
Entree & Traitement_particulier_NS_Profils_VDF::lire (const Motcle & motlu, Entree & is) override virtual
Implements Traitement_particulier_NS_Profils.
Definition at line 71 of file Traitement_particulier_NS_Profils_VDF.cpp.
{
  if (motlu=="nb_points")
    {
      is >> Nap;
    }
  else
    {
      Cerr << "Error while reading in Traitement_particulier_NS_Profils_VDF::readOn" << finl;
      Cerr << "Possible key-words are : nb_points , { and } " << finl;
      Cerr << "User specified :" << motlu << finl;
      exit();
    }
  return is;
}
References Cerr, Process::exit(), finl, and Traitement_particulier_NS_Profils::Nap.
Referenced by Traitement_particulier_NS_Profils_thermo_VDF::lire().
lire() [2/2]
Entree & Traitement_particulier_NS_Profils_VDF::lire (Entree & is) override virtual
Reimplemented from Traitement_particulier_NS_Profils.
Definition at line 66 of file Traitement_particulier_NS_Profils_VDF.cpp.
{
  return Traitement_particulier_NS_Profils::lire(is);
}
References Traitement_particulier_NS_Profils::lire().
post_traitement_particulier()
void Traitement_particulier_NS_Profils_VDF::post_traitement_particulier (void) override virtual
< si ce n est pas une reprise : sinon valeurs lues dans le fichier de reprise
Implements Traitement_particulier_NS_Profils.
Definition at line 87 of file Traitement_particulier_NS_Profils_VDF.cpp.
{
  DoubleTab umoy_x_m(n_probes,Nap);
  umoy_x_m=0.;
  DoubleTab umoy_y_m(n_probes,Nap);
  umoy_y_m=0.;
  DoubleTab umoy_z_m(n_probes,Nap);
  umoy_z_m=0.;
  DoubleTab umoy_2_m(n_probes,Nap);
  umoy_2_m=0.;
  DoubleTab vmoy_2_m(n_probes,Nap);
  vmoy_2_m=0.;
  DoubleTab wmoy_2_m(n_probes,Nap);
  wmoy_2_m=0.;
  DoubleTab umoy_3_m(n_probes,Nap);
  umoy_3_m=0.;
  DoubleTab vmoy_3_m(n_probes,Nap);
  vmoy_3_m=0.;
  DoubleTab wmoy_3_m(n_probes,Nap);
  wmoy_3_m=0.;
  DoubleTab umoy_4_m(n_probes,Nap);
  umoy_4_m=0.;
  DoubleTab vmoy_4_m(n_probes,Nap);
  vmoy_4_m=0.;
  DoubleTab wmoy_4_m(n_probes,Nap);
  wmoy_4_m=0.;
  DoubleTab uv_moy_m(n_probes,Nap);
  uv_moy_m=0.;
  DoubleTab nu_t_inst_m(n_probes,Nap);
  nu_t_inst_m=0.;
  DoubleTab umoy_x_p(n_probes,Nap);
  umoy_x_p=0.;
  DoubleTab umoy_y_p(n_probes,Nap);
  umoy_y_p=0.;
  DoubleTab umoy_z_p(n_probes,Nap);
  umoy_z_p=0.;
  DoubleTab umoy_2_p(n_probes,Nap);
  umoy_2_p=0.;
  DoubleTab vmoy_2_p(n_probes,Nap);
  vmoy_2_p=0.;
  DoubleTab wmoy_2_p(n_probes,Nap);
  wmoy_2_p=0.;
  DoubleTab umoy_3_p(n_probes,Nap);
  umoy_3_p=0.;
  DoubleTab vmoy_3_p(n_probes,Nap);
  vmoy_3_p=0.;
  DoubleTab wmoy_3_p(n_probes,Nap);
  wmoy_3_p=0.;
  DoubleTab umoy_4_p(n_probes,Nap);
  umoy_4_p=0.;
  DoubleTab vmoy_4_p(n_probes,Nap);
  vmoy_4_p=0.;
  DoubleTab wmoy_4_p(n_probes,Nap);
  wmoy_4_p=0.;
  DoubleTab uv_moy_p(n_probes,Nap);
  uv_moy_p=0.;
  DoubleTab nu_t_inst_p(n_probes,Nap);
  nu_t_inst_p=0.;
  double tps = mon_equation->inconnue().temps();
  if (oui_u_inst != 0)
    {
      calculer_moyenne_spatiale_vitesse(umoy_x_m,umoy_2_m,umoy_3_m,umoy_4_m,corresp_u_m,compt_x_m,Nxy,0,xUm);
      calculer_moyenne_spatiale_vitesse(umoy_x_p,umoy_2_p,umoy_3_p,umoy_4_p,corresp_u_p,compt_x_p,Nxy,0,xUp);
      calculer_moyenne_spatiale_vitesse(umoy_y_m,vmoy_2_m,vmoy_3_m,vmoy_4_m,corresp_v_m,compt_y_m,Nyy,1,xVm);
      calculer_moyenne_spatiale_vitesse(umoy_y_p,vmoy_2_p,vmoy_3_p,vmoy_4_p,corresp_v_p,compt_y_p,Nyy,1,xVp);
      calculer_moyenne_spatiale_vitesse(umoy_z_m,wmoy_2_m,wmoy_3_m,wmoy_4_m,corresp_w_m,compt_z_m,Nzy,2,xWm);
      calculer_moyenne_spatiale_vitesse(umoy_z_p,wmoy_2_p,wmoy_3_p,wmoy_4_p,corresp_w_p,compt_z_p,Nzy,2,xWp);
      calculer_moyenne_spatiale_uv(uv_moy_m,corresp_uv_m,compt_uv_m,Nuv,xUVm);
      calculer_moyenne_spatiale_uv(uv_moy_p,corresp_uv_p,compt_uv_p,Nuv,xUVp);
      static double temps_dern_post_inst = -100.;
      if (std::fabs(tps-temps_dern_post_inst)>=dt_post_inst)
        {
          ecriture_fichiers_moy_spat(umoy_x_m,umoy_2_m,umoy_3_m,umoy_4_m,umoy_x_p,umoy_2_p,umoy_3_p,umoy_4_p,delta_Um,delta_Up,Nxy,Yu_m,0);
          ecriture_fichiers_moy_spat(umoy_y_m,vmoy_2_m,vmoy_3_m,vmoy_4_m,umoy_y_p,vmoy_2_p,vmoy_3_p,vmoy_4_p,delta_Vm,delta_Vp,Nyy,Yv_m,1);
          ecriture_fichiers_moy_spat(umoy_z_m,wmoy_2_m,wmoy_3_m,wmoy_4_m,umoy_z_p,wmoy_2_p,wmoy_3_p,wmoy_4_p,delta_Wm,delta_Wp,Nzy,Yw_m,2);
          ecriture_fichiers_moy_spat_1col(uv_moy_m,uv_moy_p,Yuv_m,delta_UVm,delta_UVp,Nuv,3);
          temps_dern_post_inst = tps;
        }
    }
  if (oui_profil_nu_t != 0)
    {
      calculer_moyenne_spatiale_nut(nu_t_inst_m,corresp_uv_m,compt_uv_m,Nuv,xUVm);
      calculer_moyenne_spatiale_nut(nu_t_inst_p,corresp_uv_p,compt_uv_p,Nuv,xUVp);
      static double temps_dern_post_inst_nut = -100.;
      if (std::fabs(tps-temps_dern_post_inst_nut)>=dt_post_inst)
        {
          ecriture_fichiers_moy_spat_1col(nu_t_inst_m,nu_t_inst_p,Yuv_m,delta_UVm,delta_UVp,Nuv,4);
          temps_dern_post_inst_nut = tps;
        }
    }
  //////!< Moyenne temporelle*********************************************//
  if (oui_stat != 0)
    {
      double tpsbis = mon_equation->inconnue().temps();
      if ((tpsbis>=temps_deb)&&(tpsbis<=temps_fin))
        {
          static int init_stat_temps = 0;
          if((init_stat_temps==0)&&( oui_repr != 1))  //!< si ce n est pas une reprise : sinon valeurs lues dans le fichier de reprise
            {
              double dt_v = mon_equation->schema_temps().pas_de_temps();
              temps_deb = tpsbis-dt_v;
              init_stat_temps++;
            }
          calculer_integrale_temporelle(u_moy_temp_x,umoy_x_m,umoy_x_p,delta_Um,delta_Up);
          calculer_integrale_temporelle(u_moy_temp_y,umoy_y_m,umoy_y_p,delta_Vm,delta_Vp);
          calculer_integrale_temporelle(u_moy_temp_z,umoy_z_m,umoy_z_p,delta_Wm,delta_Wp);
          calculer_integrale_temporelle(uv_moy_temp,uv_moy_m,uv_moy_p,delta_UVm,delta_UVp);
          calculer_integrale_temporelle(u2_moy_temp,umoy_2_m,umoy_2_p,delta_Um,delta_Up);
          calculer_integrale_temporelle(v2_moy_temp,vmoy_2_m,vmoy_2_p,delta_Vm,delta_Vp);
          calculer_integrale_temporelle(w2_moy_temp,wmoy_2_m,wmoy_2_p,delta_Wm,delta_Wp);
          calculer_integrale_temporelle(u3_moy_temp,umoy_3_m,umoy_3_p,delta_Um,delta_Up);
          calculer_integrale_temporelle(v3_moy_temp,vmoy_3_m,vmoy_3_p,delta_Vm,delta_Vp);
          calculer_integrale_temporelle(w3_moy_temp,wmoy_3_m,wmoy_3_p,delta_Wm,delta_Wp);
          calculer_integrale_temporelle(u4_moy_temp,umoy_4_m,umoy_4_p,delta_Um,delta_Up);
          calculer_integrale_temporelle(v4_moy_temp,vmoy_4_m,vmoy_4_p,delta_Vm,delta_Vp);
          calculer_integrale_temporelle(w4_moy_temp,wmoy_4_m,wmoy_4_p,delta_Wm,delta_Wp);
          if (oui_profil_nu_t != 0)
            calculer_integrale_temporelle(nu_t_temp,nu_t_inst_m,nu_t_inst_p,delta_UVm,delta_UVp);
          static double temps_dern_post_stat = -100.;
          if (std::fabs(tpsbis-temps_dern_post_stat)>=dt_post_stat)
            {
              double dt = tpsbis-temps_deb;
              ecriture_fichiers_moy_temp(u_moy_temp_x,u2_moy_temp,u3_moy_temp,u4_moy_temp,Yu_m,Nxy,0,dt);
              ecriture_fichiers_moy_temp(u_moy_temp_y,v2_moy_temp,v3_moy_temp,v4_moy_temp,Yv_m,Nyy,1,dt);
              ecriture_fichiers_moy_temp(u_moy_temp_z,w2_moy_temp,w3_moy_temp,w4_moy_temp,Yw_m,Nzy,2,dt);
              ecriture_fichiers_moy_temp_1col(uv_moy_temp,Yuv_m,Nuv,3,dt);
              if (oui_profil_nu_t != 0)
                ecriture_fichiers_moy_temp_1col(nu_t_temp,Yuv_m,Nuv,4,dt);
              temps_dern_post_stat = tpsbis;
            }
        }
    }
}
References calculer_integrale_temporelle(), calculer_moyenne_spatiale_nut(), calculer_moyenne_spatiale_uv(), calculer_moyenne_spatiale_vitesse(), compt_uv_m, compt_uv_p, compt_x_m, compt_x_p, compt_y_m, compt_y_p, compt_z_m, compt_z_p, corresp_u_m, corresp_u_p, corresp_uv_m, corresp_uv_p, corresp_v_m, corresp_v_p, corresp_w_m, corresp_w_p, delta_Um, delta_Up, delta_UVm, delta_UVp, delta_Vm, delta_Vp, delta_Wm, delta_Wp, Traitement_particulier_NS_Profils::dt_post_inst, Traitement_particulier_NS_Profils::dt_post_stat, ecriture_fichiers_moy_spat(), ecriture_fichiers_moy_spat_1col(), ecriture_fichiers_moy_temp(), ecriture_fichiers_moy_temp_1col(), Navier_Stokes_std::inconnue(), Traitement_particulier_NS_base::mon_equation, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, Traitement_particulier_NS_Profils::nu_t_temp, Traitement_particulier_NS_Profils::Nuv, Traitement_particulier_NS_Profils::Nxy, Traitement_particulier_NS_Profils::Nyy, Traitement_particulier_NS_Profils::Nzy, Traitement_particulier_NS_Profils::oui_profil_nu_t, Traitement_particulier_NS_Profils::oui_repr, Traitement_particulier_NS_Profils::oui_stat, Traitement_particulier_NS_Profils::oui_u_inst, Schema_Temps_base::pas_de_temps(), Equation_base::schema_temps(), Champ_Inc::temps(), Traitement_particulier_NS_Profils::temps_deb, Traitement_particulier_NS_Profils::temps_fin, Traitement_particulier_NS_Profils::u2_moy_temp, Traitement_particulier_NS_Profils::u3_moy_temp, Traitement_particulier_NS_Profils::u4_moy_temp, Traitement_particulier_NS_Profils::u_moy_temp_x, Traitement_particulier_NS_Profils::u_moy_temp_y, Traitement_particulier_NS_Profils::u_moy_temp_z, Traitement_particulier_NS_Profils::uv_moy_temp, Traitement_particulier_NS_Profils::v2_moy_temp, Traitement_particulier_NS_Profils::v3_moy_temp, Traitement_particulier_NS_Profils::v4_moy_temp, Traitement_particulier_NS_Profils::w2_moy_temp, Traitement_particulier_NS_Profils::w3_moy_temp, Traitement_particulier_NS_Profils::w4_moy_temp, xUm, xUp, xUVm, xUVp, xVm, xVp, xWm, xWp, Yu_m, Yuv_m, Yv_m, and Yw_m.
Referenced by Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier().
printOn()
Sortie & Traitement_particulier_NS_Profils_VDF::printOn (Sortie & is) const override protected virtual
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_Profils.
Definition at line 41 of file Traitement_particulier_NS_Profils_VDF.cpp.
{
  return is;
}
readOn()
Entree & Traitement_particulier_NS_Profils_VDF::readOn (Entree & is) override protected virtual
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_Profils.
Definition at line 61 of file Traitement_particulier_NS_Profils_VDF.cpp.
{
  return is;
}
self_cast() [1/2]
const Traitement_particulier_NS_Profils_VDF & Traitement_particulier_NS_Profils_VDF::self_cast (const Objet_U & r) static
Definition at line 24 of file Traitement_particulier_NS_Profils_VDF.cpp.
self_cast() [2/2]
Traitement_particulier_NS_Profils_VDF & Traitement_particulier_NS_Profils_VDF::self_cast (Objet_U & r) static
Definition at line 24 of file Traitement_particulier_NS_Profils_VDF.cpp.
taille_memoire()
unsigned Traitement_particulier_NS_Profils_VDF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Traitement_particulier_NS_Profils_VDF.cpp.
Member Data Documentation
compt_uv_m
IntTab Traitement_particulier_NS_Profils_VDF::compt_uv_m protected
Nombre de points a "meme Y" pour chaque grandeur.
Definition at line 62 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
compt_uv_p
IntTab Traitement_particulier_NS_Profils_VDF::compt_uv_p protected
Definition at line 63 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
compt_x_m
IntTab Traitement_particulier_NS_Profils_VDF::compt_x_m protected
Definition at line 62 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
compt_x_p
IntTab Traitement_particulier_NS_Profils_VDF::compt_x_p protected
Definition at line 63 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
compt_y_m
IntTab Traitement_particulier_NS_Profils_VDF::compt_y_m protected
Definition at line 62 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
compt_y_p
IntTab Traitement_particulier_NS_Profils_VDF::compt_y_p protected
Definition at line 63 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
compt_z_m
IntTab Traitement_particulier_NS_Profils_VDF::compt_z_m protected
Definition at line 62 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
compt_z_p
IntTab Traitement_particulier_NS_Profils_VDF::compt_z_p protected
Definition at line 63 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
corresp_u_m
IntTab Traitement_particulier_NS_Profils_VDF::corresp_u_m protected
Definition at line 64 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
corresp_u_p
IntTab Traitement_particulier_NS_Profils_VDF::corresp_u_p protected
Definition at line 65 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
corresp_uv_m
IntTab Traitement_particulier_NS_Profils_VDF::corresp_uv_m protected
Correspondance numerotation globale -> numerotation locale dans Yxx.
Definition at line 64 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
corresp_uv_p
IntTab Traitement_particulier_NS_Profils_VDF::corresp_uv_p protected
Definition at line 65 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
corresp_v_m
IntTab Traitement_particulier_NS_Profils_VDF::corresp_v_m protected
Definition at line 64 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
corresp_v_p
IntTab Traitement_particulier_NS_Profils_VDF::corresp_v_p protected
Definition at line 65 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
corresp_w_m
IntTab Traitement_particulier_NS_Profils_VDF::corresp_w_m protected
Definition at line 64 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
corresp_w_p
IntTab Traitement_particulier_NS_Profils_VDF::corresp_w_p protected
Definition at line 65 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
delta_Um
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_Um protected
Definition at line 68 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
delta_Up
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_Up protected
Definition at line 68 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
delta_UVm
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_UVm protected
Definition at line 68 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
delta_UVp
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_UVp protected
Distance (tjrs positive) entre le point avant ou apres et le point du profil, pour faire les interpolations lineaires et trouver les points en question.
Definition at line 68 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
delta_Vm
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_Vm protected
Definition at line 68 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
delta_Vp
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_Vp protected
Definition at line 68 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
delta_Wm
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_Wm protected
Definition at line 68 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
delta_Wp
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_Wp protected
Definition at line 68 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
info_obj
const Type_info Traitement_particulier_NS_Profils_VDF::info_obj static
Definition at line 39 of file Traitement_particulier_NS_Profils_VDF.h.
xUm
DoubleTab Traitement_particulier_NS_Profils_VDF::xUm protected
Definition at line 67 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
xUp
DoubleTab Traitement_particulier_NS_Profils_VDF::xUp protected
Definition at line 67 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
xUVm
DoubleTab Traitement_particulier_NS_Profils_VDF::xUVm protected
Definition at line 67 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
xUVp
DoubleTab Traitement_particulier_NS_Profils_VDF::xUVp protected
Positions des points juste avant et apres.
Definition at line 67 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
xVm
DoubleTab Traitement_particulier_NS_Profils_VDF::xVm protected
Definition at line 67 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
xVp
DoubleTab Traitement_particulier_NS_Profils_VDF::xVp protected
Definition at line 67 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
xWm
DoubleTab Traitement_particulier_NS_Profils_VDF::xWm protected
Definition at line 67 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
xWp
DoubleTab Traitement_particulier_NS_Profils_VDF::xWp protected
Definition at line 67 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
Yu_m
DoubleTab Traitement_particulier_NS_Profils_VDF::Yu_m protected
Definition at line 60 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
Yu_p
DoubleTab Traitement_particulier_NS_Profils_VDF::Yu_p protected
Definition at line 61 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne().
Yuv_m
DoubleTab Traitement_particulier_NS_Profils_VDF::Yuv_m protected
Coordonnees des points ou est definie la vitesse.
Definition at line 60 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
Yuv_p
DoubleTab Traitement_particulier_NS_Profils_VDF::Yuv_p protected
Definition at line 61 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne().
Yv_m
DoubleTab Traitement_particulier_NS_Profils_VDF::Yv_m protected
Definition at line 60 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
Yv_p
DoubleTab Traitement_particulier_NS_Profils_VDF::Yv_p protected
Definition at line 61 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne().
Yw_m
DoubleTab Traitement_particulier_NS_Profils_VDF::Yw_m protected
Definition at line 60 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
Yw_p
DoubleTab Traitement_particulier_NS_Profils_VDF::Yw_p protected
Definition at line 61 of file Traitement_particulier_NS_Profils_VDF.h.
Referenced by init_calcul_moyenne().
The documentation for this class was generated from the following files:
src/VDF/Traitement_particulier/Traitement_particulier_NS_Profils_VDF.h
src/VDF/Traitement_particulier/Traitement_particulier_NS_Profils_VDF.cpp