TRUST: Eval_Puiss_Th_VDF_Elem Class Reference
Eval_Puiss_Th_VDF_Elem Class Reference
#include <Eval_Puiss_Th_VDF_Elem.h>
Public Member Functions
template<typename Type_Double >
void calculer_terme_source (const int, Type_Double &) const
void associer_champs (const Champ_Don &)
void mettre_a_jour () override
Public Member Functions inherited from Evaluateur_Source_VDF_Elem
Evaluateur_Source_VDF_Elem ()
Evaluateur_Source_VDF_Elem (const Evaluateur_Source_VDF_Elem &)
void completer () override
Public Member Functions inherited from Evaluateur_Source_VDF
Evaluateur_Source_VDF ()
Evaluateur_Source_VDF (const Evaluateur_Source_VDF &eval)
virtual ~Evaluateur_Source_VDF ()
template<typename Type_Double >
void calculer_terme_source (int, Type_Double &) const
virtual void mettre_a_jour ()=0
virtual void completer ()=0
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
Protected Attributes
Ref_Champ_Don la_puissance
DoubleTab puissance
Protected Attributes inherited from Evaluateur_Source_VDF_Elem
DoubleVect volumes
DoubleVect porosite_vol
porosites volumiques
Protected Attributes inherited from Evaluateur_Source_VDF
Ref_Zone_VDF la_zone
Ref_Zone_Cl_VDF la_zcl
Detailed Description
Definition at line 24 of file Eval_Puiss_Th_VDF_Elem.h.
Member Function Documentation
associer_champs()
void Eval_Puiss_Th_VDF_Elem::associer_champs (const Champ_Don & Q) inline
Definition at line 36 of file Eval_Puiss_Th_VDF_Elem.h.
{
  la_puissance = Q;
  puissance.ref(Q.valeurs());
}
References la_puissance, puissance, TRUSTTab< _TYPE_ >::ref(), and Champ_Don::valeurs().
Referenced by Terme_Puissance_Thermique_VDF_Elem::associer_pb().
calculer_terme_source()
template<typename Type_Double > void Eval_Puiss_Th_VDF_Elem::calculer_terme_source (const int num_elem, Type_Double & source) const
Definition at line 43 of file Eval_Puiss_Th_VDF_Elem.h.
{
  const int k = sub_type(Champ_Uniforme,la_puissance.valeur().valeur()) ? 0 : num_elem, size = source.size_array();
  for (int i = 0; i < size; i++) source[i] = puissance(k, i) * volumes(num_elem) * porosite_vol(num_elem);
}
References la_puissance, Evaluateur_Source_VDF_Elem::porosite_vol, puissance, sub_type, Deriv_Champ_Don_base::valeur(), Ref_Champ_Don::valeur(), and Evaluateur_Source_VDF_Elem::volumes.
mettre_a_jour()
void Eval_Puiss_Th_VDF_Elem::mettre_a_jour () inline override virtual
Implements Evaluateur_Source_VDF.
Definition at line 29 of file Eval_Puiss_Th_VDF_Elem.h.
{ /* Do nothing */}
Member Data Documentation
la_puissance
Ref_Champ_Don Eval_Puiss_Th_VDF_Elem::la_puissance protected
Definition at line 32 of file Eval_Puiss_Th_VDF_Elem.h.
Referenced by associer_champs(), and calculer_terme_source().
puissance
DoubleTab Eval_Puiss_Th_VDF_Elem::puissance protected
Definition at line 33 of file Eval_Puiss_Th_VDF_Elem.h.
Referenced by associer_champs(), and calculer_terme_source().
The documentation for this class was generated from the following file:
src/VDF/Sources/Evaluateurs/Eval_Puiss_Th_VDF_Elem.h