TRUST: ExtrudeBord Class Reference
ExtrudeBord Class Reference
#include <ExtrudeBord.h>
Public Member Functions
~ExtrudeBord ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
ExtrudeBord ()
Entree & interpreter_ (Entree &) override
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static ExtrudeBord & self_cast (Objet_U &)
static const ExtrudeBord & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete_geometrique_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void extruder_bord (Nom &nom_front, Nom &nom_dom2, DoubleVect &vect_dir, int nbpas)
void extruder_hexa_old (Nom &nom_front, Nom &nom_dom2, DoubleVect &vect_dir, int nbpas)
Private Attributes
int hexa_old
flag pour ancienne version de l'extrusion des hexas : 0 = ancienne version
int Trois_Tetra
flag pour extrusion en trois tetraedres plutot qu'en 14 (option par defaut)
int Vingt_Tetra
flag pour extrusion en vingr tetraedres plutot qu'en 14 (option par defaut)
int en3D_
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Realise une extrusion d'un bord. ExtrudeBord peut extruder un bord maille soit en triangle soit en quadrangle
si le bord est maille en quadrangle, le domaine extrude sera compose d'hexaedre
si le bord est maille en triangle, le domaine extrude sera compose de tetraedres La syntaxte est la suivante : ExtrudeBord { domaine_init NOM_DOMAINE_DE_DEPART direction X Y Z nb_tranches N domaine_final NOM_DU_DOMAINE_EXTRUDE nom_bord NOM_BORD_A_EXTRUDER hexa_old //mot cle a mettre pour utiliser l'ancienne version de l'extrusion des hexas }
(MODIF OC 12/2004)
! class ExtrudeBord
Definition at line 45 of file ExtrudeBord.h.
Constructor & Destructor Documentation
~ExtrudeBord()
ExtrudeBord::~ExtrudeBord ()
Definition at line 28 of file ExtrudeBord.cpp.
ExtrudeBord()
ExtrudeBord::ExtrudeBord ()
Definition at line 30 of file ExtrudeBord.cpp.
{
  hexa_old=0;
  Trois_Tetra=0;
}
References hexa_old, and Trois_Tetra.
Member Function Documentation
cree_instance()
Objet_U * ExtrudeBord::cree_instance () static
Definition at line 28 of file ExtrudeBord.cpp.
duplique()
int ExtrudeBord::duplique () const override virtual
Implements Objet_U.
Definition at line 28 of file ExtrudeBord.cpp.
extruder_bord()
void ExtrudeBord::extruder_bord (Nom & nom_front, Nom & nom_dom2, DoubleVect & vect_dir, int nbpas) private
< Evolution de la methode Extrude bord pour l'adapter a 3tetra
Definition at line 91 of file ExtrudeBord.cpp.
{
  const Domaine& dom=domaine();
  const Zone& zone=dom.zone(0);
  const Bord& front=zone.bord(nom_front);
  Domaine& dom_surfacique=ref_cast(Domaine, objet(nom_dom_surfacique));
// Extract from the volume domain dom the boundary front and fill the dom_surfacique domain:
  TroisDto2D tD2dD;
  int& coupe=tD2dD.coupe();
  coupe=0;
  if (en3D_)
    coupe=2;
  tD2dD.extraire_2D(dom,dom_surfacique,front,nom_front,0);
  if (0)
    {
      SFichier test("bord.geom");
      test<<dom_surfacique;
    }
  double xa = tD2dD.getXa();
  double ya = tD2dD.getYa();
  double za = tD2dD.getZa();
  double Ix = tD2dD.getIx();
  double Iy = tD2dD.getIy();
  double Iz = tD2dD.getIz();
  double Jx = tD2dD.getJx();
  double Jy = tD2dD.getJy();
  double Jz = tD2dD.getJz();
  double Kx = tD2dD.getKx();
  double Ky = tD2dD.getKy();
  double Kz = tD2dD.getKz();
  if (!en3D_)
    {
      dimension=2;
    }
  else
    {
      Ix=1;
      Iy=0;
      Iz=0;
      Jx=0;
      Jy=1;
      Jz=0;
      Kx=0;
      Ky=0;
      Kz=1;
    }
  if (Trois_Tetra==1)  //!< Evolution de la methode Extrude bord pour l'adapter a 3tetra
    {
      Extruder_en3 extr3;
      extr3.setNbTranches(nbpas);
      extr3.setDirection(vect_dir(0)*Ix+vect_dir(1)*Iy+vect_dir(2)*Iz,
                         vect_dir(0)*Jx+vect_dir(1)*Jy+vect_dir(2)*Jz,
                         vect_dir(0)*Kx+vect_dir(1)*Ky+vect_dir(2)*Kz);
      int nb_som=dom_surfacique.coord_sommets().dimension(0);
      IntVect num(nb_som);
      dom_surfacique.ajouter(dom_surfacique.coord_sommets(), num);
      extr3.extruder(dom_surfacique,num);
      Zone& zone2 = dom_surfacique.zone(0);
      if ((zone2.type_elem()->que_suis_je())== "Rectangle")
        {
          Cerr << "It is not possible to apply ExtrudeBord with 3Tetra option to : "   <<  zone2.type_elem()->que_suis_je() << " mesh cells" << finl;
// exit();
        }
    }
  else if (Vingt_Tetra==1)
    {
      Extruder_en20 extr;
      extr.setNbTranches(nbpas);
      extr.setDirection(vect_dir(0)*Ix+vect_dir(1)*Iy+vect_dir(2)*Iz,
                        vect_dir(0)*Jx+vect_dir(1)*Jy+vect_dir(2)*Jz,
                        vect_dir(0)*Kx+vect_dir(1)*Ky+vect_dir(2)*Kz);
      extr.extruder(dom_surfacique);
    }
  else
    {
      Extruder extr;
      extr.setNbTranches(nbpas);
      extr.setDirection(vect_dir(0)*Ix+vect_dir(1)*Iy+vect_dir(2)*Iz,
                        vect_dir(0)*Jx+vect_dir(1)*Jy+vect_dir(2)*Jz,
                        vect_dir(0)*Kx+vect_dir(1)*Ky+vect_dir(2)*Kz);
      extr.extruder(dom_surfacique);
    }
  if (en3D_)
    {
// en 3D on ne tourne pas le bord
      return;
    }
// on remet le nouveau domaine 3D dans le repere du domaine 3D initial
  dimension = 3;
  Noms les_fcts(3);
  les_fcts[0] = Nom(xa,"%.16e")+Nom("+x*(")+Nom(Ix,"%.16e")+Nom(")+y*(")+Nom(Jx,"%.16e")+Nom(")+z*(")+Nom(Kx,"%.16e")+Nom(")");
  les_fcts[1] = Nom(ya,"%.16e")+Nom("+x*(")+Nom(Iy,"%.16e")+Nom(")+y*(")+Nom(Jy,"%.16e")+Nom(")+z*(")+Nom(Ky,"%.16e")+Nom(")");
  les_fcts[2] = Nom(za,"%.16e")+Nom("+x*(")+Nom(Iz,"%.16e")+Nom(")+y*(")+Nom(Jz,"%.16e")+Nom(")+z*(")+Nom(Kz,"%.16e")+Nom(")");
  Transformer transf;
  transf.transformer(dom_surfacique,les_fcts);
// Pour que l'on ait plus de problemes de precision ensuite quand on manipule
// le domaine extrude, on impose les coordonnes de la frontiere nom_front du domaine
// initial sur les coordonnees de la frontiere devant du domaine extrude
// Il faut egalement recalculer proprement pour la frontiere derriere
  const Faces& faces=zone.frontiere(zone.rang_frontiere(nom_front)).faces();
  int nb_faces=faces.nb_faces();
  int nb_som_faces=faces.nb_som_faces();
  const Zone& zone2=dom_surfacique.zone(0);
  const Faces& faces2=zone2.frontiere(zone2.rang_frontiere("devant")).faces();
  const Faces& faces3=zone2.frontiere(zone2.rang_frontiere("derriere")).faces();
  for (int j=0; j<nb_faces; j++)
    for (int k=0; k<nb_som_faces; k++)
      {
        int som = faces.sommet(j,k);
        int som2 = faces2.sommet(j,k);
        int som3 = faces3.sommet(j,k);
        for (int i=0; i<3; i++)
          {
            dom_surfacique.coord(som2,i) = dom.coord(som,i);
            dom_surfacique.coord(som3,i) = dom.coord(som,i) + vect_dir(i);
          }
      }
  Cerr << "ExtrudeBord does not create any more PERIO boundary." << finl;
  Cerr << "Use RegroupeBord if you want to create periodic boundary condition..." << finl;
}
References Domaine::ajouter(), Zone::bord(), Cerr, Domaine::coord(), Domaine::coord_sommets(), TroisDto2D::coupe(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Interprete_geometrique_base::domaine(), en3D_, TroisDto2D::extraire_2D(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Frontiere::faces(), finl, Zone::frontiere(), TroisDto2D::getIx(), TroisDto2D::getIy(), TroisDto2D::getIz(), TroisDto2D::getJx(), TroisDto2D::getJy(), TroisDto2D::getJz(), TroisDto2D::getKx(), TroisDto2D::getKy(), TroisDto2D::getKz(), TroisDto2D::getXa(), TroisDto2D::getYa(), TroisDto2D::getZa(), Faces::nb_faces(), Faces::nb_som_faces(), Interprete::objet(), Objet_U::que_suis_je(), Zone::rang_frontiere(), ref_cast, Extruder::setDirection(), Extruder_en20::setDirection(), Extruder_en3::setDirection(), Extruder::setNbTranches(), Extruder_en20::setNbTranches(), Extruder_en3::setNbTranches(), Faces::sommet(), test(), Transformer::transformer(), Trois_Tetra, Zone::type_elem(), Vingt_Tetra, and Domaine::zone().
Referenced by interpreter_().
extruder_hexa_old()
void ExtrudeBord::extruder_hexa_old (Nom & nom_front, Nom & nom_dom2, DoubleVect & vect_dir, int nbpas) private
< nb de faces se rapportant a chacun des sommets
< nb de sommets a extruder pour constituer les faces de parois
< arete[0-1]
< arete[1-3]
< arete[3-2]
< arete[2-0]
Definition at line 226 of file ExtrudeBord.cpp.
{
  const Domaine& dom=domaine();
  const Zone& zone=dom.zone(0);
  int nbfr=zone.nb_front_Cl();
  Domaine& dom_surfacique=ref_cast(Domaine, objet(nom_dom_surfacique));
  Zone& zone2=dom_surfacique.add(*(new Zone()));
  zone2.associer_domaine(dom_surfacique);
  zone2.typer("Hexaedre");
  zone2.nommer(nom_dom_surfacique);
  DoubleTab& sommets2=dom_surfacique.les_sommets();
  IntTab& les_elems2=zone2.les_elems();
  int i;
  for (int l=0; l<nbfr; l++)
    {
      const Frontiere& fr=zone.frontiere(l);
      const Nom& nomfr=fr.le_nom();
      if(nomfr==nom_front)
        {
          int nbfaces=fr.nb_faces();
          const IntTab& som=fr.les_sommets_des_faces();
          IntTab newsom(4*nbfaces);
          IntTab compt(4*nbfaces);
          newsom=-100;
          compt=0;
          int nbsombord,trouve;
          nbsombord = 0;
// ******** Table de correspondance des sommets de bords : dom_volumique - dom_surfacique
          for (i=0; i<nbfaces; i++)
            for (int j=0; j<4; j++)
              {
                trouve = 0;
                int sommet=som(i,j);
                for (int k=0; k<nbsombord+1; k++)
                  {
                    if(sommet==newsom(k))
                      {
                        k=nbsombord+1;
                        trouve = 1;
                        break;
                      }
                  }
                if (trouve==0)
                  {
                    newsom[nbsombord]=sommet;
                    nbsombord++;
                  }
              }
          newsom.resize(nbsombord);
          compt.resize(nbsombord);
          sommets2.resize((nbpas+1)*nbsombord,3);
// ******** Creation des sommets deduits par translation
          for (int j=0; j<nbpas+1; j++)
            for (i=0; i<nbsombord; i++)
              {
                sommets2(i+j*nbsombord,0)=dom.coord(newsom(i),0)+j*vect_dir(0)/nbpas;
                sommets2(i+j*nbsombord,1)=dom.coord(newsom(i),1)+j*vect_dir(1)/nbpas;
                sommets2(i+j*nbsombord,2)=dom.coord(newsom(i),2)+j*vect_dir(2)/nbpas;
              }
// ******** Definition des tableaux de correspondance ELEM<->SOMMETS
          les_elems2.resize(nbpas*nbfaces,8);
          int  sommet0,sommet1,sommet2,sommet3;
          int  newsom0=-1,newsom1=-1,newsom2=-1,newsom3=-1;
          for (i=0; i<nbfaces; i++)
            {
              sommet0=som(i,0);
              sommet1=som(i,1);
              sommet2=som(i,2);
              sommet3=som(i,3);
              for(int j=0; j<nbsombord; j++)
                {
                  if(newsom[j]==sommet0) newsom0=j;
                  if(newsom[j]==sommet1) newsom1=j;
                  if(newsom[j]==sommet2) newsom2=j;
                  if(newsom[j]==sommet3) newsom3=j;
                }
              for(int k=0; k<nbpas; k++)
                {
                  les_elems2(i+k*nbfaces,0)=newsom0+k*nbsombord;
                  les_elems2(i+k*nbfaces,1)=newsom1+k*nbsombord;
                  les_elems2(i+k*nbfaces,2)=newsom2+k*nbsombord;
                  les_elems2(i+k*nbfaces,3)=newsom3+k*nbsombord;
                  les_elems2(i+k*nbfaces,4)=newsom0+(k+1)*nbsombord;
                  les_elems2(i+k*nbfaces,5)=newsom1+(k+1)*nbsombord;
                  les_elems2(i+k*nbfaces,6)=newsom2+(k+1)*nbsombord;
                  les_elems2(i+k*nbfaces,7)=newsom3+(k+1)*nbsombord;
                }
            }
// ******** Definition des frontieres periodiques
          Bord& bordperio=zone2.faces_bord().add(Bord());
          bordperio.nommer("PERIO");
          bordperio.typer_faces("QUADRANGLE_3D");
          bordperio.dimensionner(0);
          IntTab faces_perio(2*nbfaces,4);
          for (i=0; i<nbfaces; i++)
            {
              sommet0=som(i,0);
              sommet1=som(i,1);
              sommet2=som(i,2);
              sommet3=som(i,3);
              for(int j=0; j<nbsombord; j++)
                {
                  if(newsom[j]==sommet0) newsom0=j;
                  if(newsom[j]==sommet1) newsom1=j;
                  if(newsom[j]==sommet2) newsom2=j;
                  if(newsom[j]==sommet3) newsom3=j;
                }
              faces_perio(i,0)=newsom0;
              faces_perio(i,1)=newsom1;
              faces_perio(i,2)=newsom2;
              faces_perio(i,3)=newsom3;
              faces_perio(i+nbfaces,0)=newsom0+nbpas*nbsombord;
              faces_perio(i+nbfaces,1)=newsom1+nbpas*nbsombord;
              faces_perio(i+nbfaces,2)=newsom2+nbpas*nbsombord;
              faces_perio(i+nbfaces,3)=newsom3+nbpas*nbsombord;
            }
          bordperio.ajouter_faces(faces_perio);
// ******** Definition des frontieres parois
          Bord& bordparoi=zone2.faces_bord().add(Bord());
          bordparoi.nommer("PAROI");
          bordparoi.typer_faces("QUADRANGLE_3D");
          bordparoi.dimensionner(0);
          int nbsombordparoi=0;
// ***** recherche des sommets appartenant au contour de la face de bord *****
          for (i=0; i<nbfaces; i++)
            for (int j=0; j<4; j++)
              for (int k=0; k<nbsombord; k++)
                if(som(i,j)==newsom(k))  compt(k)++; //!< nb de faces se rapportant a chacun des sommets
          for (int k=0; k<nbsombord; k++)
            if(compt(k)<3) nbsombordparoi++; //!< nb de sommets a extruder pour constituer les faces de parois
// PQ : 05/05/04 : ATTENTION : des sommets internes peuvant etre connectes qu'a
// 3 faces (cf. maillage en "O" d'un cylindre)
// -> on se place donc dans le cas ou les sommets de bords ne sont connectes qu'a
// 2 elements (excluant de fait les bords types VDF en marche d'escalier).
// **** Extension des aretes pour former les faces de la frontiere paroi
          IntTab faces_paroi(nbsombordparoi*nbpas,4);
          int ip=0;
          for (i=0; i<nbfaces; i++)
            {
              sommet0=som(i,0);
              sommet1=som(i,1);
              sommet2=som(i,2);
              sommet3=som(i,3);
              int compt0=4,compt1=4,compt2=4,compt3=4;
              for(int j=0; j<nbsombord; j++)
                {
                  if(newsom[j]==sommet0)
                    {
                      newsom0=j;
                      compt0=compt(j);
                    }
                  if(newsom[j]==sommet1)
                    {
                      newsom1=j;
                      compt1=compt(j);
                    }
                  if(newsom[j]==sommet2)
                    {
                      newsom2=j;
                      compt2=compt(j);
                    }
                  if(newsom[j]==sommet3)
                    {
                      newsom3=j;
                      compt3=compt(j);
                    }
                }
              if( (compt0<3) && (compt1<3) ) //!< arete[0-1]
                {
                  for(int k=0; k<nbpas; k++)
                    {
                      faces_paroi(ip+k,0)=newsom0+k*nbsombord;
                      faces_paroi(ip+k,1)=newsom0+(k+1)*nbsombord;
                      faces_paroi(ip+k,2)=newsom1+k*nbsombord;
                      faces_paroi(ip+k,3)=newsom1+(k+1)*nbsombord;
                    }
                  ip+=nbpas;
                }
              if( (compt1<3) && (compt3<3) ) //!< arete[1-3]
                {
                  for(int k=0; k<nbpas; k++)
                    {
                      faces_paroi(ip+k,0)=newsom1+k*nbsombord;
                      faces_paroi(ip+k,1)=newsom1+(k+1)*nbsombord;
                      faces_paroi(ip+k,2)=newsom3+k*nbsombord;
                      faces_paroi(ip+k,3)=newsom3+(k+1)*nbsombord;
                    }
                  ip+=nbpas;
                }
              if( (compt3<3) && (compt2<3) ) //!< arete[3-2]
                {
                  for(int k=0; k<nbpas; k++)
                    {
                      faces_paroi(ip+k,0)=newsom3+k*nbsombord;
                      faces_paroi(ip+k,1)=newsom3+(k+1)*nbsombord;
                      faces_paroi(ip+k,2)=newsom2+k*nbsombord;
                      faces_paroi(ip+k,3)=newsom2+(k+1)*nbsombord;
                    }
                  ip+=nbpas;
                }
              if( (compt2<3) && (compt0<3) ) //!< arete[2-0]
                {
                  for(int k=0; k<nbpas; k++)
                    {
                      faces_paroi(ip+k,0)=newsom2+k*nbsombord;
                      faces_paroi(ip+k,1)=newsom2+(k+1)*nbsombord;
                      faces_paroi(ip+k,2)=newsom0+k*nbsombord;
                      faces_paroi(ip+k,3)=newsom0+(k+1)*nbsombord;
                    }
                  ip+=nbpas;
                }
            }
          bordparoi.ajouter_faces(faces_paroi);
        }//fin de la condition sur la frontiere a extruder
    }//fin de parcours de toutes les frontieres
  Nom mfile=nom_dom_surfacique;
  mfile+=".geom";
  {
    SFichier file(mfile);
    file<<dom_surfacique;
    file.close();
  }
  {
    EFichier file(mfile);
    file>>dom_surfacique;
    file.close();
  }
}
References List_Bord::add(), Domaine::add(), Frontiere::ajouter_faces(), Zone::associer_domaine(), Entree_Fichier_base::close(), Sortie_Fichier_base::close(), Domaine::coord(), Frontiere::dimensionner(), Interprete_geometrique_base::domaine(), Zone::faces_bord(), Zone::frontiere(), Frontiere::le_nom(), Zone::les_elems(), Domaine::les_sommets(), Frontiere::les_sommets_des_faces(), Frontiere::nb_faces(), Zone::nb_front_Cl(), Frontiere::nommer(), Zone::nommer(), Interprete::objet(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Zone::typer(), Frontiere::typer_faces(), and Domaine::zone().
Referenced by interpreter_().
get_info()
const Type_info * ExtrudeBord::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 28 of file ExtrudeBord.cpp.
info()
const Type_info * ExtrudeBord::info () static
Definition at line 28 of file ExtrudeBord.cpp.
interpreter_()
Entree & ExtrudeBord::interpreter_ (Entree & is) override virtual
< XD_ADD_P ref_domaine Initial domain with hexaedras or tetrahedras.
< XD_ADD_P listf Directions for the extrusion.
< XD_ADD_P int Number of elements in the extrusion direction.
< XD_ADD_P chaine Extruded domain.
< XD_ADD_P chaine Name of the boundary of the initial domain where extrusion will be applied.
< XD_ADD_P rien Old algorithm for boundary extrusion from a hexahedral mesh.
< XD_ADD_P rien To extrude in 3 tetrahedras instead of 14 tetrahedras.
< XD_ADD_P rien To extrude in 20 tetrahedras instead of 14 tetrahedras.
< XD_ADD_P int Only for non-regression
Implements Interprete_geometrique_base.
Definition at line 46 of file ExtrudeBord.cpp.
{
  Nom nom_dom_volumique;
  Nom nom_front,nom_dom_surfacique;
  DoubleVect vect_dir(3);
  en3D_=1;
  int nbpas;
  if(dimension!=3)
    {
      Cerr << "Interpreter "<<que_suis_je()<<" can be used only in 3 dimensions." <<finl;
      exit();
    }
  Param param(que_suis_je());
  param.ajouter("domaine_init",&nom_dom_volumique,Param::REQUIRED);//!< XD_ADD_P ref_domaine Initial domain with hexaedras or tetrahedras.
  param.ajouter_arr_size_predefinie("direction",&vect_dir,Param::REQUIRED);//!< XD_ADD_P  listf Directions for the extrusion.
  param.ajouter("nb_tranches",&nbpas,Param::REQUIRED);//!< XD_ADD_P  int Number of elements in the extrusion direction.
  param.ajouter("domaine_final",&nom_dom_surfacique,Param::REQUIRED);//!< XD_ADD_P  chaine Extruded domain.
  param.ajouter("nom_bord",&nom_front,Param::REQUIRED);//!< XD_ADD_P  chaine Name of the boundary of the initial domain where extrusion will be applied.
  param.ajouter_flag("hexa_old",&hexa_old);//!< XD_ADD_P  rien Old algorithm for boundary extrusion from a hexahedral mesh.
  param.ajouter_flag("Trois_Tetra",&Trois_Tetra);//!< XD_ADD_P  rien To extrude in 3 tetrahedras instead of 14 tetrahedras.
  param.ajouter_flag("Vingt_Tetra",&Vingt_Tetra);//!< XD_ADD_P  rien To extrude in 20 tetrahedras instead of 14 tetrahedras.
  param.ajouter("sans_passer_par_le2D",&en3D_);//!< XD_ADD_P  int Only for non-regression
  param.lire_avec_accolades_depuis(is);
  associer_domaine(nom_dom_volumique);
  const Domaine& dom=domaine();
  const Zone& zone=dom.zone(0);
  if (zone.nb_som_elem()==8 && (hexa_old == 1))
    {
      extruder_hexa_old(nom_front, nom_dom_surfacique, vect_dir, nbpas);
    }
  else if (zone.nb_som_elem()==4 || zone.nb_som_elem()==8)
    {
      extruder_bord(nom_front, nom_dom_surfacique, vect_dir, nbpas);
    }
  Domaine& dom_surfacique=ref_cast(Domaine, objet(nom_dom_surfacique));
  Scatter::init_sequential_domain(dom_surfacique);
  return is;
}
References Param::ajouter(), Param::ajouter_arr_size_predefinie(), Param::ajouter_flag(), Interprete_geometrique_base::associer_domaine(), Cerr, Objet_U::dimension, Interprete_geometrique_base::domaine(), en3D_, Process::exit(), extruder_bord(), extruder_hexa_old(), finl, hexa_old, Scatter::init_sequential_domain(), Param::lire_avec_accolades_depuis(), Zone::nb_som_elem(), Interprete::objet(), Objet_U::que_suis_je(), ref_cast, Param::REQUIRED, Trois_Tetra, Vingt_Tetra, and Domaine::zone().
printOn()
Sortie & ExtrudeBord::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 36 of file ExtrudeBord.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & ExtrudeBord::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 41 of file ExtrudeBord.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const ExtrudeBord & ExtrudeBord::self_cast (const Objet_U & r) static
Definition at line 28 of file ExtrudeBord.cpp.
self_cast() [2/2]
ExtrudeBord & ExtrudeBord::self_cast (Objet_U & r) static
Definition at line 28 of file ExtrudeBord.cpp.
taille_memoire()
unsigned ExtrudeBord::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 28 of file ExtrudeBord.cpp.
Member Data Documentation
en3D_
int ExtrudeBord::en3D_ private
Definition at line 61 of file ExtrudeBord.h.
Referenced by extruder_bord(), and interpreter_().
hexa_old
int ExtrudeBord::hexa_old private
flag pour ancienne version de l'extrusion des hexas : 0 = ancienne version
Definition at line 58 of file ExtrudeBord.h.
Referenced by ExtrudeBord(), and interpreter_().
info_obj
const Type_info ExtrudeBord::info_obj static
Definition at line 47 of file ExtrudeBord.h.
Trois_Tetra
int ExtrudeBord::Trois_Tetra private
flag pour extrusion en trois tetraedres plutot qu'en 14 (option par defaut)
Definition at line 59 of file ExtrudeBord.h.
Referenced by ExtrudeBord(), extruder_bord(), and interpreter_().
Vingt_Tetra
int ExtrudeBord::Vingt_Tetra private
flag pour extrusion en vingr tetraedres plutot qu'en 14 (option par defaut)
Definition at line 60 of file ExtrudeBord.h.
Referenced by extruder_bord(), and interpreter_().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/ExtrudeBord.h
src/Kernel/Geometrie/ExtrudeBord.cpp