TRUST: InputCommBuffer Class Reference
InputCommBuffer Class Reference
:
Classe outil utilisee exclusivement par Schema_Comm. C'est une classe
derivee de Entree dont le stream est de type istringstream (les donnees
lues par operator>> sont prises dans un buffer).
On utilise la classe comme suit:
(1) on reserve un buffer d'une certaine taille avec
char * buf = input_comm_buffer.reserve_buffer(taille);
(2) on remplit le buffer avec des donnees:
for (i=0; i<taille; i++)
buf[i] = .....;
(3) on cree un stream a partir du buffer:
input_comm_buffer.create_stream();
(4) on peut ensuite lire les donnees a travers l'operateur>>:
input_comm_buffer >> x >> y >> chaine >> ... ;
(5) quand on a fini de lire avec operateur>> on fait
input_comm_buffer.clear();
et on peut refaire (1)
#include <InputCommBuffer.h>
Public Member Functions
InputCommBuffer ()
~InputCommBuffer () override
char * reserve_buffer (int bufsize)
void create_stream_from_output_stream (OutputCommBuffer &)
void create_stream ()
void clear ()
Public Member Functions inherited from Entree
Entree ()
Entree (istream &is)
Entree (const Entree &is)
Entree & operator= (istream &is)
Entree & operator= (Entree &is)
virtual istream & get_istream ()
virtual const istream & get_istream () const
void set_istream (istream *is)
void set_different_int_size (bool is_different_int_size)
Entree & operator>> (Entree &(*f)(Entree &))
Entree & operator>> (istream &(*f)(istream &))
Entree & operator>> (ios &(*f)(ios &))
virtual Entree & operator>> (int &ob)
virtual Entree & operator>> (long &ob)
virtual Entree & operator>> (float &ob)
virtual Entree & operator>> (double &ob)
virtual int get (int *ob, int n)
virtual int get (long *ob, int n)
virtual int get (float *ob, int n)
virtual int get (double *ob, int n)
virtual int get (char *buf, int bufsize)
Lecture d'une chaine dans ostream_
bufsize est la taille du buffer alloue pour ob (y compris
le caractere 0 final).
La chaine contient toujours un 0 meme en cas d'echec.
La methode renvoie 1 si la lecture est bonne, 0 sinon.
Si le buffer est trop petit, pour l'instant on fait exit() mais
par la suite on pourra tester: si strlen(ob)==bufsize-1, alors
refaire lire() jusqu'a arriver au bout. Si le lire() suivant
renvoie une chaine de longueur nulle, cela signifie que la taille de la
chaine etait exactement bufsize-1.
Attention: le comportement est different en binaire et en ascii.
En binaire, on lit la chaine jusqu'au prochain '\0'.
En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
virtual int eof ()
virtual int fail ()
virtual int good ()
virtual ~Entree ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand.
int is_bin () const
virtual void set_check_types (int flag)
indique si le stream doit verifier les types des objets lus<br>(ints et nombres flottants). Exemple : l'entree contient 123.456 123.456
int i;
check_types(0);
is >> i; // i contient 123
check_types(1);
is >> i; // Erreur : on lit la chaine 123.456 et on essaye de la convertir en int
Voir operator>>(int &)
int check_types () const
renvoie la valeur actuelle du drapeau, voir set_check_types()
virtual void set_error_action (Error_Action)
Change le comportement en cas d'erreur de l'entree,
voir error_handle_() et get_error_action()
Error_Action get_error_action ()
renvoie error_action_ pour cette entree<br>(permet de la modifier et de restaurer ensuite la valeur anterieure)
operator istream & ()
istream & putback (char ch)
istream & ignore (int n=1, int delim=EOF)
int get_diffuse ()
virtual void set_diffuse (int diffuse)
ToDo TMA : commenter.
Private Attributes
istringstream * stream_
char * buffer_
int size_
int memorysize_
memorysize_ >= size_
Additional Inherited Members
Public Types inherited from Entree
enum Error_Action { ERROR_EXIT , ERROR_CONTINUE , ERROR_EXCEPTION }
Protected Member Functions inherited from Entree
int error_handle (int fail_flag)
virtual int error_handle_ (int fail_flag)
Cette fonction est appellee par operateur>>, get, get_nom
ouvrir, fermer, lire, etc... en cas d'echec (lorsque fail() est mis)
Elle renvoie 0 s'il y a eu une erreur (passer par error_handle() qui
traite en inline le cas ou il n'y a pas d'erreur), et 1 s'il n'y a pas
d'erreur.
(par commodite de codage des methodes qui l'utilisent, on
ecrira "return error_handle(fail());"
Elle peut etre configuree pour
- renvoyer "0" en cas d'erreur et continuer l'execution du code
(cas d'un ancien code qui ne gere pas les exceptions mais teste
le drapeau fail() de temps en temps)
Dans ce cas les methodes operator>> continuent l'execution du code
meme en cas d'echec, le contenu des variables lues est indefini !
- faire Process::exit() (cas d'une portion de code dans laquelle
on ne veut pas faire de gestion d'erreur du tout et ou on suppose
que tout va toujours bien)
- lever une exception (permet une gestion rigoureuse des erreurs
et une information utilisateur optimale en fonction du contexte)
Voir aussi set_error_action()
Protected Attributes inherited from Entree
int bin_
bool is_different_int_size_
File with int32 (or int64) whereas version is int64 (or int32)
int check_types_
Error_Action error_action_
int diffuse_
By default 1, but some child classes (eg: LecFicDiffuse) could set temporary to 0 to not diffuse to other processes.
Detailed Description
:
Classe outil utilisee exclusivement par Schema_Comm. C'est une classe
derivee de Entree dont le stream est de type istringstream (les donnees
lues par operator>> sont prises dans un buffer).
On utilise la classe comme suit:
(1) on reserve un buffer d'une certaine taille avec
char * buf = input_comm_buffer.reserve_buffer(taille);
(2) on remplit le buffer avec des donnees:
for (i=0; i<taille; i++)
buf[i] = .....;
(3) on cree un stream a partir du buffer:
input_comm_buffer.create_stream();
(4) on peut ensuite lire les donnees a travers l'operateur>>:
input_comm_buffer >> x >> y >> chaine >> ... ;
(5) quand on a fini de lire avec operateur>> on fait
input_comm_buffer.clear();
et on peut refaire (1)
Definition at line 39 of file InputCommBuffer.h.
Constructor & Destructor Documentation
InputCommBuffer()
InputCommBuffer::InputCommBuffer ()
Definition at line 19 of file InputCommBuffer.cpp.
{
  set_error_action(ERROR_CONTINUE);
  bin_ = 1;
  memorysize_ = 16;
  size_ = 0;
// On alloue toujours quelque chose (create_stream a besoin d'un octet au moins
// pour creer un stream de taille nulle)
  buffer_ = new char[memorysize_];
  stream_ = 0;
}
References Entree::bin_, buffer_, Entree::ERROR_CONTINUE, memorysize_, Entree::set_error_action(), size_, and stream_.
~InputCommBuffer()
InputCommBuffer::~InputCommBuffer () override
Definition at line 31 of file InputCommBuffer.cpp.
{
  assert(stream_ == 0);
  delete[] buffer_;
  buffer_ = 0;
  size_ = 0;
  memorysize_ = 0;
}
References buffer_, memorysize_, size_, and stream_.
Member Function Documentation
clear()
void InputCommBuffer::clear ()
Definition at line 85 of file InputCommBuffer.cpp.
{
  assert(stream_);
  delete stream_;
  stream_ = 0;
  set_istream(stream_);
  size_ = -1;
}
References Entree::set_istream(), size_, and stream_.
Referenced by Schema_Comm::end_comm(), envoyer_broadcast_buffered_(), and recevoir_buffered_().
create_stream()
void InputCommBuffer::create_stream ()
Definition at line 53 of file InputCommBuffer.cpp.
{
  assert(stream_ == 0);
  assert(size_ >= 0);
// (Voir documentation de istrstream) :
// Si size_ > 0 istrstream(buf, size_) cree un buffer de taille size_.
// Si size_ = 0, istrstream(buf, size_) suppose que buf est une chaine
// de caracteres terminee par zero. Pour creer un stream de taille nulle,
// il faut donc faire ceci:
  if (size_ == 0)
    buffer_[0] = 0;
  stream_ = new istringstream(std::string(buffer_, size_));
  set_istream(stream_);
}
References buffer_, Entree::set_istream(), size_, and stream_.
Referenced by envoyer_broadcast_buffered_(), and recevoir_buffered_().
create_stream_from_output_stream()
void InputCommBuffer::create_stream_from_output_stream (OutputCommBuffer & output_buf)
Definition at line 68 of file InputCommBuffer.cpp.
{
  assert(stream_ == 0);
  const char nullchar = 0;
  const char * buffer = output_buf.get_buffer();
  const int size = output_buf.get_buffer_size();
// (Voir documentation de istrstream) :
// Si size_ > 0 istrstream(buf, size_) cree un buffer de taille size_.
// Si size_ = 0, istrstream(buf, size_) suppose que buf est une chaine
// de caracteres terminee par zero. Pour creer un stream de taille nulle,
// il faut donc faire ceci:
  if (size == 0)
    buffer = &nullchar;
  stream_ = new istringstream(std::string(buffer, size));
  set_istream(stream_);
}
References OutputCommBuffer::get_buffer(), OutputCommBuffer::get_buffer_size(), Entree::set_istream(), and stream_.
reserve_buffer()
char * InputCommBuffer::reserve_buffer (int bufsize)
Definition at line 40 of file InputCommBuffer.cpp.
{
  assert(stream_ == 0);
  size_ = bufsize;
  if (size_ > memorysize_)
    {
      delete[] buffer_;
      memorysize_ = size_ * 2;
      buffer_ = new char[memorysize_];
    }
  return buffer_;
}
References buffer_, memorysize_, size_, and stream_.
Referenced by envoyer_broadcast_buffered_(), and recevoir_buffered_().
Member Data Documentation
buffer_
char* InputCommBuffer::buffer_ private
Definition at line 54 of file InputCommBuffer.h.
Referenced by create_stream(), InputCommBuffer(), reserve_buffer(), and ~InputCommBuffer().
memorysize_
int InputCommBuffer::memorysize_ private
memorysize_ >= size_
Definition at line 56 of file InputCommBuffer.h.
Referenced by InputCommBuffer(), reserve_buffer(), and ~InputCommBuffer().
size_
int InputCommBuffer::size_ private
Definition at line 55 of file InputCommBuffer.h.
Referenced by clear(), create_stream(), InputCommBuffer(), reserve_buffer(), and ~InputCommBuffer().
stream_
istringstream* InputCommBuffer::stream_ private
Definition at line 53 of file InputCommBuffer.h.
Referenced by clear(), create_stream(), create_stream_from_output_stream(), InputCommBuffer(), reserve_buffer(), and ~InputCommBuffer().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/InputCommBuffer.h
src/Kernel/Utilitaires/InputCommBuffer.cpp