TRUST: Joint Class Reference
Joint Class Reference
La classe Joint est une Frontiere qui contient les faces
et les sommets de joint avec la zone PEvoisin() (pour les maillages
distribues en parallele).
Elle porte en plus dans les Joint_Items les informations
permettant de construire les tableaux distribues indexes
par les items geometriques (sommets, faces, elements, aretes,
faces_frontieres)
#include <Joint.h>
Public Types
enum Type_Item {
SOMMET , ELEMENT , FACE , ARETE ,
FACE_FRONT
}
Public Member Functions
Joint ()
~Joint ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void affecte_PEvoisin (int)
Fixe le numero du PE voisin.
void affecte_epaisseur (int)
Fixe l'epaisseur du joint.
int PEvoisin () const
Renvoie PEvoisin (numero de la zone voisine)
int epaisseur () const
Renvoie l'epaisseur du joint.
void dimensionner (int)
void ajouter_faces (const IntTab &)
Ajoute des faces a la frontiere (au joint)
voir Frontiere::ajouter_faces(const IntTab&)
const IntTab & renum_virt_loc () const
const ArrOfInt & esp_dist_elems () const
const ArrOfInt & esp_dist_sommets () const
const ArrOfInt & esp_dist_faces () const
Joint_Items & set_joint_item (Type_Item type)
Renvoie les informations de joint pour un type d'item
geometrique donne, pour remplissage des structures. Ces structures
sont generalement remplies par la classe Scatter. Exceptions notables:
Zone_VDF et Zone_VF pour la renumerotation des faces.
const Joint_Items & joint_item (Type_Item type) const
Renvoie les informations de joint pour le type demande.
Public Member Functions inherited from Frontiere
Frontiere ()
~Frontiere () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Associe la frontiere a la zone dont elle depend.
const Zone & zone () const
Renvoie la Zone associee a la frontiere.
(version const)
Zone & zone ()
Renvoie la Zone associee a la frontiere.
void nommer (const Nom &) override
Donne un nom a la frontiere.
void ajouter_faces (const IntTab &)
Ajoute une (ou plusieurs) face(s) a la frontiere,
la (les) face(s) est (sont) specifiee(s) par un tableau
contenant les numeros des sommets.
void typer_faces (const Motcle &)
Type les faces de la frontiere.
void typer_faces (const Type_Face &)
Type les faces de la frontiere.
const Faces & faces () const
Renvoie les faces de la frontiere<br>(version const)
Faces & faces ()
Renvoie les faces de la frontiere.
IntTab & les_sommets_des_faces ()
Renvoie les sommets des faces de la frontiere.
const IntTab & les_sommets_des_faces () const
Renvoie les sommets des faces de la frontiere.
int nb_faces () const
Renvoie le nombre de faces de la frontiere.
void dimensionner (int)
Dimensionne la frontiere, i.e. fixe
son nombre de faces.
const Nom & le_nom () const override
Renvoie le nom de la frontiere.
void renum (const IntVect &)
Renumerote les noeuds (sommets) des faces.
Le noeud de numero k devient le noeud de numero Les_Nums[k].
void add (const Frontiere &)
Ajoute les sommets (et faces) de la frontiere
passee en parametre a l'objet (Frontiere).
int nb_faces_virt () const
int face_virt (int i) const
int num_premiere_face () const
void fixer_num_premiere_face (int)
const ArrOfInt & get_faces_virt () const
ArrOfInt & get_faces_virt ()
const double & get_aire () const
void set_aire (double &aire)
virtual void creer_tableau_faces (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
Cree un tableau ayant une "ligne" par face de cette frontiere
Voir MD_Vector_tools::creer_tableau_distribue()
virtual void trace_elem_local (const DoubleTab &, DoubleTab &) const
Renvoie la trace sur la frontiere du tableau aux elements y.
virtual void trace_face_local (const DoubleTab &, DoubleTab &) const
Renvoie la trace sur la frontiere du tableau aux faces y.
virtual void trace_face_local (const DoubleVect &, DoubleVect &) const
Renvoie la trace sur la frontiere du tableau aux faces y.
virtual void trace_elem_distant (const DoubleTab &, DoubleTab &) const
virtual void trace_som_distant (const DoubleTab &, DoubleTab &) const
virtual void trace_face_distant (const DoubleTab &, DoubleTab &) const
virtual void trace_face_distant (const DoubleVect &, DoubleVect &) const
virtual void trace_som_local (const DoubleTab &y, DoubleTab &x) const
Renvoie la trace sur la frontiere du tableau aux noeuds y.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Joint & self_cast (Objet_U &)
static const Joint & self_cast (const Objet_U &)
Static Public Member Functions inherited from Frontiere
static const Type_info * info ()
static Frontiere & self_cast (Objet_U &)
static const Frontiere & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Frontiere
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le joint sur un flot de sortie.
On ecrit:
- la frontiere
- le PE voisin
- l'epaisseur
- les sommets.
Entree & readOn (Entree &) override
Lit un joint a partir d'un flot d'entree.
Sortie & printOn (Sortie &x) const override
Ecrit la frontiere sur un flot de sortie.
On ecrit:
le nom de la frontiere
les faces.
Entree & readOn (Entree &) override
Lit les specification d'une frontiere
a partir d'un flot d'entree.
On lit:
le nom
les faces.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
int PEvoisin_
int epaisseur_
Joint_Items joint_sommets_
Joint_Items joint_elements_
Joint_Items joint_faces_
Joint_Items joint_faces_front_
Joint_Items joint_aretes_
Detailed Description
La classe Joint est une Frontiere qui contient les faces
et les sommets de joint avec la zone PEvoisin() (pour les maillages
distribues en parallele).
Elle porte en plus dans les Joint_Items les informations
permettant de construire les tableaux distribues indexes
par les items geometriques (sommets, faces, elements, aretes,
faces_frontieres)
Definition at line 37 of file Joint.h.
Member Enumeration Documentation
Type_Item
enum Joint::Type_Item
Enumerator
SOMMET
ELEMENT
FACE
ARETE
FACE_FRONT
Definition at line 59 of file Joint.h.
{ SOMMET, ELEMENT, FACE, ARETE, FACE_FRONT };
Constructor & Destructor Documentation
Joint()
Joint::Joint ()
Definition at line 19 of file Joint.cpp.
~Joint()
Joint::~Joint ()
Definition at line 19 of file Joint.cpp.
Member Function Documentation
affecte_epaisseur()
void Joint::affecte_epaisseur (int ep)
Fixe l'epaisseur du joint.
Definition at line 85 of file Joint.cpp.
{
  epaisseur_ = ep;
}
References epaisseur_.
Referenced by ajouter_joint(), ajouter_joints(), auto_build_joints(), DomaineCutter::construire_sommets_joints_ssdom(), and Raffiner_Simplexes::refine_domain().
affecte_PEvoisin()
void Joint::affecte_PEvoisin (int num)
Fixe le numero du PE voisin.
Definition at line 78 of file Joint.cpp.
{
  PEvoisin_ = num;
}
References PEvoisin_.
Referenced by ajouter_joint(), ajouter_joints(), auto_build_joints(), DomaineCutter::construire_sommets_joints_ssdom(), and Raffiner_Simplexes::refine_domain().
ajouter_faces()
void Joint::ajouter_faces (const IntTab & sommets)
Ajoute des faces a la frontiere (au joint)
voir Frontiere::ajouter_faces(const IntTab&)
Definition at line 121 of file Joint.cpp.
{
  faces().ajouter(sommets);
  faces().voisins() = -1;
}
References Faces::ajouter(), Frontiere::faces(), and Faces::voisins().
Referenced by Joints::comprimer().
cree_instance()
Objet_U * Joint::cree_instance () static
Definition at line 19 of file Joint.cpp.
dimensionner()
void Joint::dimensionner (int i)
Definition at line 68 of file Joint.cpp.
{
  faces().dimensionner(i);
  faces().voisins() = -1;
  faces().les_sommets() = -1;
}
References Faces::dimensionner(), Frontiere::faces(), Faces::les_sommets(), and Faces::voisins().
Referenced by Joints::comprimer(), and DomaineCutter::construire_faces_joints_ssdom().
duplique()
int Joint::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Joint.cpp.
epaisseur()
int Joint::epaisseur () const
Renvoie l'epaisseur du joint.
Definition at line 99 of file Joint.cpp.
{
  return epaisseur_;
}
References epaisseur_.
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), Op_Conv_VDF< OP_TYPE >::associer_(), Scatter::calculer_espace_distant_elements(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Op_Conv_EF_Stab_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Grad_PolyMAC_Face::completer(), Op_Grad_PolyMAC_P0_Face::completer(), and Op_Conv_EF_Stab_PolyMAC_Elem::preparer_calcul().
esp_dist_elems()
const ArrOfInt & Joint::esp_dist_elems () const
Definition at line 132 of file Joint.cpp.
{
  return joint_item(ELEMENT).items_distants();
}
References ELEMENT, Joint_Items::items_distants(), and joint_item().
esp_dist_faces()
const ArrOfInt & Joint::esp_dist_faces () const
Definition at line 142 of file Joint.cpp.
{
  return joint_item(FACE).items_distants();
}
References FACE, Joint_Items::items_distants(), and joint_item().
Referenced by Zone_EF::creer_faces_virtuelles_non_std(), and Zone_VEF::creer_faces_virtuelles_non_std().
esp_dist_sommets()
const ArrOfInt & Joint::esp_dist_sommets () const
Definition at line 137 of file Joint.cpp.
{
  return joint_item(SOMMET).items_distants();
}
References Joint_Items::items_distants(), joint_item(), and SOMMET.
get_info()
const Type_info * Joint::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Frontiere.
Definition at line 19 of file Joint.cpp.
info()
const Type_info * Joint::info () static
Definition at line 19 of file Joint.cpp.
joint_item()
const Joint_Items & Joint::joint_item (Type_Item type) const
Renvoie les informations de joint pour le type demande.
< never arrive here
Definition at line 179 of file Joint.cpp.
{
  switch(item)
    {
    case SOMMET:
      return joint_sommets_;
      break;
    case ELEMENT:
      return joint_elements_;
      break;
    case FACE:
      return joint_faces_;
      break;
    case ARETE:
      return joint_aretes_;
      break;
    case FACE_FRONT:
      return joint_faces_front_;
      break;
    default:
      Cerr << "Error in Joint::set_joint_item, invalid item number : " << (int)item << finl;
      exit();
    }
  return joint_sommets_; //!< never arrive here
}
References ARETE, Cerr, ELEMENT, Process::exit(), FACE, FACE_FRONT, finl, joint_aretes_, joint_elements_, joint_faces_, joint_faces_front_, joint_sommets_, and SOMMET.
Referenced by add_sommets_communs(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), calculer_liste_complete_sommets_joint(), Scatter::calculer_nb_items_virtuels(), Scatter::calculer_renum_items_communs(), Scatter::check_consistancy_remote_items(), DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_faces_joints_ssdom(), dump_lata(), DomaineCutter::ecrire_zones(), esp_dist_elems(), esp_dist_faces(), esp_dist_sommets(), Extraire_surface::extraire_surface(), Extraire_plan::interpreter_(), Zone_VF::marquer_faces_double_contrib(), Scatter::mergeDomains(), mon_construire_correspondance_items_par_coordonnees(), printOn(), and renum_virt_loc().
PEvoisin()
int Joint::PEvoisin () const
Renvoie PEvoisin (numero de la zone voisine)
Definition at line 92 of file Joint.cpp.
{
  return PEvoisin_;
}
References PEvoisin_.
Referenced by add_sommets_communs(), auto_build_joints(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), calculer_liste_complete_aretes_joint(), Scatter::calculer_nb_items_virtuels(), Scatter::calculer_renum_items_communs(), Joints::comprimer(), Scatter::construire_correspondance_items_par_coordonnees(), DomaineCutter::construire_faces_joints_ssdom(), Zone_EF::creer_faces_virtuelles_non_std(), Zone_VEF::creer_faces_virtuelles_non_std(), dump_lata(), Postraiter_domaine::ecrire(), DomaineCutter::ecrire_zones(), Extraire_surface::extraire_surface(), Extraire_plan::interpreter_(), Joints::joint_PE(), Scatter::mergeDomains(), mon_construire_correspondance_items_par_coordonnees(), and Scatter::reordonner_faces_de_joint().
printOn()
Sortie & Joint::printOn (Sortie & x) const override protected virtual
Ecrit le joint sur un flot de sortie.
On ecrit:
- la frontiere
- le PE voisin
- l'epaisseur
- les sommets.
Reimplemented from Frontiere.
Definition at line 32 of file Joint.cpp.
{
  Frontiere::printOn(s) ;
  s << "format_joint_250507" << finl;
  s << PEvoisin_ << finl;
  s << epaisseur_ << finl;
  s << joint_item(Joint::SOMMET).items_communs() << finl;
  s << joint_item(Joint::ELEMENT).items_distants() << finl;
  return s ;
}
References ELEMENT, epaisseur_, finl, Joint_Items::items_communs(), Joint_Items::items_distants(), joint_item(), PEvoisin_, Frontiere::printOn(), and SOMMET.
readOn()
Entree & Joint::readOn (Entree & s) override protected virtual
Lit un joint a partir d'un flot d'entree.
Reimplemented from Frontiere.
Definition at line 45 of file Joint.cpp.
{
  Frontiere::readOn(s) ;
  Nom format;
  s >> format;
  if (format!="format_joint_250507")
    {
      if (Process::je_suis_maitre())
        {
          Cerr << "The format of .Zones is not recognized because probably too old." << finl;
          Cerr << "Split your mesh with an executable which is more recent" << finl;
          Cerr << "than the version 1.5.2 build 240507." << finl;
        }
      exit();
    }
  s >> PEvoisin_;
  s >> epaisseur_;
  s >> set_joint_item(Joint::SOMMET).set_items_communs();
  s >> set_joint_item(Joint::ELEMENT).set_items_distants();
  return s ;
}
References Cerr, ELEMENT, epaisseur_, Process::exit(), finl, Process::je_suis_maitre(), PEvoisin_, Frontiere::readOn(), Joint_Items::set_items_communs(), Joint_Items::set_items_distants(), set_joint_item(), and SOMMET.
renum_virt_loc()
const IntTab & Joint::renum_virt_loc () const
Definition at line 127 of file Joint.cpp.
{
  return joint_item(SOMMET).renum_items_communs();;
}
References joint_item(), Joint_Items::renum_items_communs(), and SOMMET.
self_cast() [1/2]
const Joint & Joint::self_cast (const Objet_U & r) static
Definition at line 19 of file Joint.cpp.
self_cast() [2/2]
Joint & Joint::self_cast (Objet_U & r) static
Definition at line 19 of file Joint.cpp.
set_joint_item()
Joint_Items & Joint::set_joint_item (Type_Item type)
Renvoie les informations de joint pour un type d'item
geometrique donne, pour remplissage des structures. Ces structures
sont generalement remplies par la classe Scatter. Exceptions notables:
Zone_VDF et Zone_VF pour la renumerotation des faces.
< never arrive here
Definition at line 152 of file Joint.cpp.
{
  switch(item)
    {
    case SOMMET:
      return joint_sommets_;
      break;
    case ELEMENT:
      return joint_elements_;
      break;
    case FACE:
      return joint_faces_;
      break;
    case ARETE:
      return joint_aretes_;
      break;
    case FACE_FRONT:
      return joint_faces_front_;
      break;
    default:
      Cerr << "Error in Joint::set_joint_item, invalid item number : " << (int)item << finl;
      exit();
    }
  return joint_sommets_; //!< never arrive here
}
References ARETE, Cerr, ELEMENT, Process::exit(), FACE, FACE_FRONT, finl, joint_aretes_, joint_elements_, joint_faces_, joint_faces_front_, joint_sommets_, and SOMMET.
Referenced by ajouter_joint(), ajouter_joints(), auto_build_joints(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_nb_items_virtuels(), Scatter::calculer_renum_items_communs(), Scatter::construire_correspondance_items_par_coordonnees(), DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_sommets_joints_ssdom(), DomaineCutter::construire_sous_domaine(), Scatter::corriger_espace_distant_elements_perio(), Faces_builder::creer_faces_reeles(), mon_construire_correspondance_items_par_coordonnees(), readOn(), Raffiner_Simplexes::refine_domain(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Zone_VEF::reordonner(), and reordonner_vdf().
taille_memoire()
unsigned Joint::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Joint.cpp.
Member Data Documentation
epaisseur_
int Joint::epaisseur_ private
Definition at line 68 of file Joint.h.
Referenced by affecte_epaisseur(), epaisseur(), printOn(), and readOn().
info_obj
const Type_info Joint::info_obj static
Definition at line 40 of file Joint.h.
joint_aretes_
Joint_Items Joint::joint_aretes_ private
Definition at line 74 of file Joint.h.
Referenced by joint_item(), and set_joint_item().
joint_elements_
Joint_Items Joint::joint_elements_ private
Definition at line 71 of file Joint.h.
Referenced by joint_item(), and set_joint_item().
joint_faces_
Joint_Items Joint::joint_faces_ private
Definition at line 72 of file Joint.h.
Referenced by joint_item(), and set_joint_item().
joint_faces_front_
Joint_Items Joint::joint_faces_front_ private
Definition at line 73 of file Joint.h.
Referenced by joint_item(), and set_joint_item().
joint_sommets_
Joint_Items Joint::joint_sommets_ private
Definition at line 70 of file Joint.h.
Referenced by joint_item(), and set_joint_item().
PEvoisin_
int Joint::PEvoisin_ private
Definition at line 65 of file Joint.h.
Referenced by affecte_PEvoisin(), PEvoisin(), printOn(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Joint.h
src/Kernel/Geometrie/Joint.cpp