TRUST: Modele_turbulence_scal_base Class Reference
Modele_turbulence_scal_base Class Reference abstract
Classe Modele_turbulence_scal_base
Cette classe represente un modele de turbulence pour une equation de
convection-diffusion d'un scalaire couplee a Navier_Stokes. On utilise
deux classes derivees de cette classe de base qui representent le
modele de turbulence (k,eps) et le modele de turbulence sous maille.
Ces deux modeles ont en commun le calcul d'une diffusivite turbulente.
#include <Modele_turbulence_scal_base.h>
Public Member Functions
~Modele_turbulence_scal_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Modele_turbulence_scal_base ()
virtual int preparer_calcul ()
NE FAIT RIEN.
virtual bool initTimeStep (double dt)
A surcharger dans les classes derivees qui possedent une ou des equations
Appeler preparer_pas_de_temps sur ces equations.
virtual void mettre_a_jour (double)=0
const Champ_Fonc & conductivite_turbulente () const
const Champ_Fonc & diffusivite_turbulente () const
const Turbulence_paroi_scal & loi_paroi () const
Renvoie la loi de turbulence sur la paroi<br>(version const)
int loi_paroi_non_nulle () const
Renvoie si oui ou non loi de paroi<br>(version const)
Turbulence_paroi_scal & loi_paroi ()
Renvoie la loi de turbulence sur la paroi.
virtual void discretiser ()
Discretise le modele de turbulence.
void associer_eqn (const Equation_base &)
Associe l'equation passe en parametre au modele de turbulence.
L'equation est caste en Convection_Diffusion_std.
virtual void completer ()
Complete le modele de turbulence:
met a jour des references de l'objet.
virtual void associer (const Zone_dis &, const Zone_Cl_dis &)
NE FAIT RIEN.
void a_faire (Sortie &) const
Effectue l'ecriture d'une identite si cela est necessaire.
int sauvegarder (Sortie &) const override
NE FAIT RIEN.
int reprendre (Entree &) override
NE FAIT RIEN.
Convection_Diffusion_std & equation ()
const Convection_Diffusion_std & equation () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
int limpr_nusselt (double, double, double) const
Indique s'il faut imprimer ou non le Nusselt local.
virtual void imprimer (Sortie &) const
Effectue l'impression si cela est necessaire.
virtual void set_param (Param &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Modele_turbulence_scal_base & self_cast (Objet_U &)
static const Modele_turbulence_scal_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type et le nom de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les specifications d'un modele de turbulence
a partir d'un flot d'entree.
Appelle Entree& lire(const Motcle&,Entree&)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_Fonc conductivite_turbulente_
Champ_Fonc diffusivite_turbulente_
Ref_Convection_Diffusion_std mon_equation
Turbulence_paroi_scal loipar
double dt_impr_nusselt_
Champs_compris champs_compris_
Detailed Description
Classe Modele_turbulence_scal_base
Cette classe represente un modele de turbulence pour une equation de
convection-diffusion d'un scalaire couplee a Navier_Stokes. On utilise
deux classes derivees de cette classe de base qui representent le
modele de turbulence (k,eps) et le modele de turbulence sous maille.
Ces deux modeles ont en commun le calcul d'une diffusivite turbulente.
Definition at line 47 of file Modele_turbulence_scal_base.h.
Constructor & Destructor Documentation
~Modele_turbulence_scal_base()
Modele_turbulence_scal_base::~Modele_turbulence_scal_base () override
Definition at line 25 of file Modele_turbulence_scal_base.cpp.
Modele_turbulence_scal_base()
Modele_turbulence_scal_base::Modele_turbulence_scal_base ()
Definition at line 27 of file Modele_turbulence_scal_base.cpp.
{
  /*
    Noms& nom=champs_compris_.liste_noms_compris();
    nom.dimensionner(1);
    nom[0]="diffusivite_turbulente";
  */
}
Member Function Documentation
a_faire()
void Modele_turbulence_scal_base::a_faire (Sortie & os) const
Effectue l'ecriture d'une identite si cela est necessaire.
Definition at line 283 of file Modele_turbulence_scal_base.cpp.
{
  int afaire,special;
  EcritureLectureSpecial::is_ecriture_special(special,afaire);
  if (afaire)
    {
      Nom mon_ident(que_suis_je());
      mon_ident += equation().probleme().domaine().le_nom();
      double temps = equation().inconnue().temps();
      mon_ident += Nom(temps,"%e");
      os << mon_ident << finl;
      os << que_suis_je() << finl;
      os.flush();
    }
}
References Probleme_base::domaine(), equation(), finl, Sortie::flush(), Convection_Diffusion_std::inconnue(), EcritureLectureSpecial::is_ecriture_special(), Domaine::le_nom(), Equation_base::probleme(), Objet_U::que_suis_je(), and Champ_Inc::temps().
associer()
void Modele_turbulence_scal_base::associer (const Zone_dis & , const Zone_Cl_dis &) virtual
NE FAIT RIEN.
Definition at line 166 of file Modele_turbulence_scal_base.cpp.
{
  ;
}
Referenced by Modele_turbulence_scal::readOn().
associer_eqn()
void Modele_turbulence_scal_base::associer_eqn (const Equation_base & eqn)
Associe l'equation passe en parametre au modele de turbulence.
L'equation est caste en Convection_Diffusion_std.
Definition at line 141 of file Modele_turbulence_scal_base.cpp.
{
  mon_equation = ref_cast(Convection_Diffusion_std,eqn);
}
References mon_equation, and ref_cast.
Referenced by Modele_turbulence_scal::readOn().
completer()
void Modele_turbulence_scal_base::completer (void) virtual
Complete le modele de turbulence:
met a jour des references de l'objet.
Definition at line 212 of file Modele_turbulence_scal_base.cpp.
{
}
Referenced by Modele_turbulence_scal::completer().
conductivite_turbulente()
const Champ_Fonc & Modele_turbulence_scal_base::conductivite_turbulente () const inline
Definition at line 58 of file Modele_turbulence_scal_base.h.
  {
    return conductivite_turbulente_;
  };
References conductivite_turbulente_.
Referenced by Champ_front_contact_VEF::calcul_grads_locaux(), Op_Dift_EF_base::completer(), Op_Dift_VEF_base::completer(), Op_Diff_Dift_VDF< OP_TYPE >::completer_impl(), and Modele_turbulence_scal::conductivite_turbulente().
creer_champ()
void Modele_turbulence_scal_base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
Definition at line 330 of file Modele_turbulence_scal_base.cpp.
{
  if (loipar.non_nul())
    {
      loipar->creer_champ(motlu);
    }
}
References loipar, and O_U_Ptr::non_nul().
diffusivite_turbulente()
const Champ_Fonc & Modele_turbulence_scal_base::diffusivite_turbulente () const inline
Definition at line 62 of file Modele_turbulence_scal_base.h.
  {
    return diffusivite_turbulente_;
  };
References diffusivite_turbulente_.
discretiser()
void Modele_turbulence_scal_base::discretiser () virtual
Discretise le modele de turbulence.
Definition at line 186 of file Modele_turbulence_scal_base.cpp.
{
  Cerr << "Turbulence scalar model discretization" << finl;
  const Schema_Temps_base& sch = mon_equation->schema_temps();
  const Discretisation_base& dis = mon_equation->discretisation();
  const Zone_dis& z = mon_equation->zone_dis();
  dis.discretiser_champ("champ_elem",z.valeur(),"diffusivite_turbulente","m2/s",1, sch.temps_courant(),diffusivite_turbulente_);
  dis.discretiser_champ("champ_elem",z.valeur(),"conductivite_turbulente","W/m/K",1, sch.temps_courant(),conductivite_turbulente_);
  champs_compris_.ajoute_champ(diffusivite_turbulente_);
}
References Champs_compris::ajoute_champ(), Cerr, champs_compris_, conductivite_turbulente_, diffusivite_turbulente_, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), finl, mon_equation, Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), Deriv_Zone_dis_base::valeur(), and Equation_base::zone_dis().
Referenced by Modele_turbulence_scal::discretiser().
equation() [1/2]
Convection_Diffusion_std & Modele_turbulence_scal_base::equation () inline
Returns
Convection_Diffusion_std&
Signification: l'equation associee au modele de turbulence
Contraintes:
Definition at line 178 of file Modele_turbulence_scal_base.h.
{
  if (mon_equation.non_nul()==0)
    {
      Cerr << "\nError in Modele_turbulence_scal_base::equation() : The equation is unknown !" << finl;
      Process::exit();
    }
  return mon_equation.valeur();
}
References Cerr, Process::exit(), finl, mon_equation, O_U_Ptr::non_nul(), and Ref_Convection_Diffusion_std::valeur().
Referenced by a_faire(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), and Turbulence_paroi_scal::readOn().
equation() [2/2]
const Convection_Diffusion_std & Modele_turbulence_scal_base::equation () const inline
Returns
Convection_Diffusion_std&
Signification: l'equation associee au modele de turbulence
Contraintes: reference constante
Definition at line 203 of file Modele_turbulence_scal_base.h.
{
  if (mon_equation.non_nul()==0)
    {
      Cerr << "\nError in Modele_turbulence_scal_base::equation() : The equation is unknown !" << finl;
      Process::exit();
    }
  return mon_equation.valeur();
}
References Cerr, Process::exit(), finl, mon_equation, O_U_Ptr::non_nul(), and Ref_Convection_Diffusion_std::valeur().
get_champ()
const Champ_base & Modele_turbulence_scal_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Definition at line 338 of file Modele_turbulence_scal_base.cpp.
{
// return champs_compris_.get_champ(nom);
  REF(Champ_base) ref_champ;
  try
    {
      return champs_compris_.get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  if (loipar.non_nul())
    {
      try
        {
          return loipar->get_champ(nom);
        }
      catch (Champs_compris_erreur)
        {
        }
    }
  throw Champs_compris_erreur();
}
References champs_compris_, Champs_compris::get_champ(), loipar, O_U_Ptr::non_nul(), and REF.
get_info()
const Type_info * Modele_turbulence_scal_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 25 of file Modele_turbulence_scal_base.cpp.
get_noms_champs_postraitables()
void Modele_turbulence_scal_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
Definition at line 363 of file Modele_turbulence_scal_base.cpp.
{
  if (opt==DESCRIPTION)
    Cerr<<que_suis_je()<<" : "<<champs_compris_.liste_noms_compris()<<finl;
  else
    nom.add(champs_compris_.liste_noms_compris());
  if (loipar.non_nul())
    loipar->get_noms_champs_postraitables(nom,opt);
}
References Vect_Nom::add(), Cerr, champs_compris_, DESCRIPTION, finl, Champs_compris::liste_noms_compris(), loipar, O_U_Ptr::non_nul(), and Objet_U::que_suis_je().
imprimer()
void Modele_turbulence_scal_base::imprimer (Sortie & os) const virtual
Effectue l'impression si cela est necessaire.
Definition at line 419 of file Modele_turbulence_scal_base.cpp.
{
  const Schema_Temps_base& sch = mon_equation->schema_temps();
  double temps_courant = sch.temps_courant();
  double dt= sch.pas_de_temps() ;
  if (limpr_nusselt(temps_courant,sch.temps_precedent(),dt) )
    loipar.imprimer_nusselt(os);
}
References Turbulence_paroi_scal::imprimer_nusselt(), limpr_nusselt(), loipar, mon_equation, Schema_Temps_base::pas_de_temps(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), and Schema_Temps_base::temps_precedent().
Referenced by Modele_turbulence_scal::imprimer().
info()
const Type_info * Modele_turbulence_scal_base::info () static
Definition at line 25 of file Modele_turbulence_scal_base.cpp.
initTimeStep()
bool Modele_turbulence_scal_base::initTimeStep (double dt) virtual
A surcharger dans les classes derivees qui possedent une ou des equations
Appeler preparer_pas_de_temps sur ces equations.
Definition at line 219 of file Modele_turbulence_scal_base.cpp.
{
  return true;
}
limpr_nusselt()
int Modele_turbulence_scal_base::limpr_nusselt (double temps_courant, double temps_prec, double dt) const
Indique s'il faut imprimer ou non le Nusselt local.
Returns
int
Signification: renvoie 1 si on imprime, 0 sinon
Contraintes:
Definition at line 388 of file Modele_turbulence_scal_base.cpp.
{
  const Schema_Temps_base& sch = mon_equation->schema_temps();
  if (sch.nb_pas_dt()==0)
    return 0;
  if (dt_impr_nusselt_<=dt || ((sch.temps_final_atteint() || sch.nb_pas_dt_max_atteint() || sch.nb_pas_dt()==1 || sch.stationnaire_atteint()) && dt_impr_nusselt_!=DMAXFLOAT))
    return 1;
  else
    {
// Voir Schema_Temps_base::limpr pour information sur epsilon et modf
      double i, j, epsilon = 1.e-8;
      modf(temps_courant/dt_impr_nusselt_ + epsilon, &i);
      modf(temps_prec/dt_impr_nusselt_ + epsilon, &j);
      return ( i>j );
    }
}
References DMAXFLOAT, dt_impr_nusselt_, mon_equation, Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::nb_pas_dt_max_atteint(), Equation_base::schema_temps(), Schema_Temps_base::stationnaire_atteint(), and Schema_Temps_base::temps_final_atteint().
Referenced by imprimer().
lire_motcle_non_standard()
int Modele_turbulence_scal_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Objet_U.
Definition at line 101 of file Modele_turbulence_scal_base.cpp.
{
  Motcle mot = "turbulence_paroi",accolade_ouverte="{";
  if (motlu == mot)
    {
      loipar.associer_modele(*this);
      is >> loipar;
      is >> loipar.valeur();
      /*  is >> motlu;
          if (motlu==accolade_ouverte)
          {
          }
      */
      return 1;
    }
  else
    {
      Cerr << mot << "n'est pas un mot compris par " << que_suis_je() << "dans lire_motcle_non_standard"<< finl;
      exit();
    }
  return -1;
}
References Turbulence_paroi_scal::associer_modele(), Cerr, Process::exit(), finl, loipar, Objet_U::que_suis_je(), and Deriv_Turbulence_paroi_scal_base::valeur().
loi_paroi() [1/2]
Turbulence_paroi_scal & Modele_turbulence_scal_base::loi_paroi () inline
Renvoie la loi de turbulence sur la paroi.
Returns
Turbulence_paroi_scal&
Signification: la loi de turbulence sur la paroi
Contraintes:
Definition at line 159 of file Modele_turbulence_scal_base.h.
{
  return loipar;
}
References loipar.
loi_paroi() [2/2]
const Turbulence_paroi_scal & Modele_turbulence_scal_base::loi_paroi () const inline
Renvoie la loi de turbulence sur la paroi<br>(version const)
Returns
Turbulence_paroi_scal&
Signification: la loi de turbulence sur la paroi
Contraintes: reference constante
Definition at line 120 of file Modele_turbulence_scal_base.h.
{
  return loipar;
}
References loipar.
Referenced by Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Champ_front_contact_VEF::calcul_grads_locaux(), calculer_h_distant(), calculer_h_local(), Op_Diff_Dift_VDF< OP_TYPE >::completer_impl(), Champ_Generique_Tparoi_VEF::get_champ(), Modele_turbulence_scal::loi_paroi(), and PlaqThVDF::mettre_a_jour().
loi_paroi_non_nulle()
int Modele_turbulence_scal_base::loi_paroi_non_nulle () const inline
Renvoie si oui ou non loi de paroi<br>(version const)
Returns
int
Signification:
Contraintes:
Definition at line 140 of file Modele_turbulence_scal_base.h.
{
  return loipar.non_nul();
}
References loipar, and O_U_Ptr::non_nul().
Referenced by Modele_turbulence_scal::loi_paroi_non_nulle().
mettre_a_jour()
virtual void Modele_turbulence_scal_base::mettre_a_jour (double) pure virtual
Referenced by Modele_turbulence_scal::mettre_a_jour(), and preparer_calcul().
preparer_calcul()
int Modele_turbulence_scal_base::preparer_calcul (void) virtual
NE FAIT RIEN.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Definition at line 238 of file Modele_turbulence_scal_base.cpp.
{
  if (loipar.non_nul())
    loipar.init_lois_paroi();
  mettre_a_jour(0.);
  return 1;
}
References Turbulence_paroi_scal::init_lois_paroi(), loipar, mettre_a_jour(), and O_U_Ptr::non_nul().
Referenced by Modele_turbulence_scal::preparer_calcul().
printOn()
Sortie & Modele_turbulence_scal_base::printOn (Sortie & s) const override protected virtual
Ecrit le type et le nom de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 50 of file Modele_turbulence_scal_base.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Modele_turbulence_scal_base::readOn (Entree & is) override protected virtual
Lit les specifications d'un modele de turbulence
a partir d'un flot d'entree.
Appelle Entree& lire(const Motcle&,Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 72 of file Modele_turbulence_scal_base.cpp.
{
  Cerr<<"Reading of data for a "<<que_suis_je()<<" scalar turbulence model"<<finl;
  Param param(que_suis_je());
  Motcle  mot = "turbulence_paroi";
  dt_impr_nusselt_=DMAXFLOAT;
  set_param(param);
  param.lire_avec_accolades_depuis(is);
  const Probleme_base& le_pb = mon_equation->probleme();
// lp loi de paroi du modele de turbulence de l'hydraulique
  const RefObjU& modele_turbulence = le_pb.equation(0).get_modele(TURBULENCE);
  const Mod_turb_hyd_base& mod_turb_hydr = ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur());
  const Turbulence_paroi& lp = mod_turb_hydr.loi_paroi();
  if (!loipar.non_nul() && lp.non_nul())
    {
      Cerr << finl;
      Cerr << "Mot cle " << mot << "non trouve !" << finl;
      Cerr << "On doit lire une loi de paroi dans le modele de turbulence pour un scalaire." << finl;
      Cerr << finl;
      exit();
    }
  return is;
}
References Cerr, DMAXFLOAT, dt_impr_nusselt_, Probleme_base::equation(), Process::exit(), finl, Equation_base::get_modele(), Param::lire_avec_accolades_depuis(), Mod_turb_hyd_base::loi_paroi(), loipar, mon_equation, O_U_Ptr::non_nul(), Equation_base::probleme(), Objet_U::que_suis_je(), ref_cast, set_param(), TURBULENCE, and Ref_Objet_U::valeur().
reprendre()
int Modele_turbulence_scal_base::reprendre (Entree & is) override virtual
NE FAIT RIEN.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Objet_U.
Definition at line 317 of file Modele_turbulence_scal_base.cpp.
{
  /*Nom typ ;
    is>>typ;
    if (!loipar.non_nul())
// Pour l'instant on ne lit plus dans le .sauv
    loipar.typer(typ);        */
  if (loipar.non_nul())
    loipar->reprendre(is);
  return 1;
}
References loipar, O_U_Ptr::non_nul(), and Objet_U::reprendre().
Referenced by Modele_turbulence_scal::reprendre().
sauvegarder()
int Modele_turbulence_scal_base::sauvegarder (Sortie & os) const override virtual
NE FAIT RIEN.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Objet_U.
Definition at line 261 of file Modele_turbulence_scal_base.cpp.
{
  if (loipar.non_nul())
    return loipar->sauvegarder(os);
  else
    return 0;
}
References loipar, O_U_Ptr::non_nul(), and Objet_U::sauvegarder().
Referenced by Modele_turbulence_scal::sauvegarder().
self_cast() [1/2]
const Modele_turbulence_scal_base & Modele_turbulence_scal_base::self_cast (const Objet_U & r) static
Definition at line 25 of file Modele_turbulence_scal_base.cpp.
self_cast() [2/2]
Modele_turbulence_scal_base & Modele_turbulence_scal_base::self_cast (Objet_U & r) static
Definition at line 25 of file Modele_turbulence_scal_base.cpp.
set_param()
void Modele_turbulence_scal_base::set_param (Param & param) virtual
Definition at line 96 of file Modele_turbulence_scal_base.cpp.
{
  param.ajouter("dt_impr_nusselt",&dt_impr_nusselt_);
  param.ajouter_non_std("turbulence_paroi",this);
}
References Param::ajouter(), Param::ajouter_non_std(), and dt_impr_nusselt_.
Referenced by readOn().
Member Data Documentation
champs_compris_
Champs_compris Modele_turbulence_scal_base::champs_compris_ protected
Definition at line 101 of file Modele_turbulence_scal_base.h.
Referenced by discretiser(), get_champ(), and get_noms_champs_postraitables().
conductivite_turbulente_
Champ_Fonc Modele_turbulence_scal_base::conductivite_turbulente_ protected
Definition at line 94 of file Modele_turbulence_scal_base.h.
Referenced by conductivite_turbulente(), and discretiser().
diffusivite_turbulente_
Champ_Fonc Modele_turbulence_scal_base::diffusivite_turbulente_ protected
Definition at line 94 of file Modele_turbulence_scal_base.h.
Referenced by diffusivite_turbulente(), and discretiser().
dt_impr_nusselt_
double Modele_turbulence_scal_base::dt_impr_nusselt_ protected
Definition at line 97 of file Modele_turbulence_scal_base.h.
Referenced by limpr_nusselt(), readOn(), and set_param().
info_obj
const Type_info Modele_turbulence_scal_base::info_obj static
Definition at line 50 of file Modele_turbulence_scal_base.h.
loipar
Turbulence_paroi_scal Modele_turbulence_scal_base::loipar protected
Definition at line 96 of file Modele_turbulence_scal_base.h.
Referenced by creer_champ(), get_champ(), get_noms_champs_postraitables(), imprimer(), lire_motcle_non_standard(), loi_paroi(), loi_paroi_non_nulle(), preparer_calcul(), readOn(), reprendre(), and sauvegarder().
mon_equation
Ref_Convection_Diffusion_std Modele_turbulence_scal_base::mon_equation protected
Definition at line 95 of file Modele_turbulence_scal_base.h.
Referenced by associer_eqn(), discretiser(), equation(), imprimer(), limpr_nusselt(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Modele_turbulence_base/Modele_turbulence_scal_base.h
src/ThHyd/Modele_turbulence_base/Modele_turbulence_scal_base.cpp