TRUST: Eval_Conv_VDF_tools Class Reference
Eval_Conv_VDF_tools Class Reference
#include <Eval_Conv_VDF_tools.h>
Public Member Functions
virtual ~Eval_Conv_VDF_tools ()
virtual int amont_amont (int face, int i) const
virtual int face_amont_conj (int, int, int) const
virtual int face_amont_princ (int, int) const
virtual double dim_elem (int, int) const
virtual double dim_face (int, int) const
virtual double dist_elem (int, int, int) const
virtual double dist_elem_period (int, int, int) const
virtual double conv_centre (const double, const double, const double, const double, const double, double, double, double, double) const
virtual double conv_quick_sharp_plus (const double, const double, const double, const double, const double, const double, const double) const
virtual double conv_quick_sharp_moins (const double, const double, const double, const double, const double, const double, const double) const
virtual void calcul_g (const double, const double, const double, double &, double &, double &, double &) const
template<typename Type_Double >
void qcentre (const double, const int, const int, const int, const int, const int, const DoubleTab &, Type_Double &) const
template<typename Type_Double >
void quick_fram (const double, const int, const int, const int, const int, const int, const DoubleTab &, Type_Double &) const
Protected Member Functions
int face_amont_conj_axi_impl (int, int, int, int, const IntTab &, const IntTab &, const IntVect &) const
double dist_face_axi_impl (int, int, int, const DoubleTab &) const
double dist_elem_axi_impl (int, int, int, const DoubleTab &) const
double conv_quick_sharp_plus_impl (const double, const double, const double, const double, const double, const double, const double) const
double conv_quick_sharp_moins_impl (const double, const double, const double, const double, const double, const double, const double) const
void calcul_g_impl (const double, const double, const double, double &, double &, double &, double &) const
template<typename Type_Double >
void qcentre2_impl (const double, const int, const int, const int, const int, const int, const DoubleTab &, Type_Double &) const
template<typename Type_Double >
void qcentre4_impl (const int, const double, const double, const double, const double, const int, const int, const int, const int, const int, const DoubleTab &, Type_Double &) const
template<typename Type_Double >
void quick_fram_impl (const int, const double, const double, const double, const double, const double, const double, const int, const int, const int, const int, const int, const DoubleTab &, Type_Double &) const
Private Member Functions
template<typename type >
type dont_call (const char *nom_fct) const
Detailed Description
Definition at line 22 of file Eval_Conv_VDF_tools.h.
Constructor & Destructor Documentation
~Eval_Conv_VDF_tools()
virtual Eval_Conv_VDF_tools::~Eval_Conv_VDF_tools () inline virtual
Definition at line 25 of file Eval_Conv_VDF_tools.h.
{}
Member Function Documentation
amont_amont()
virtual int Eval_Conv_VDF_tools::amont_amont (int face, int i) const inline virtual
Reimplemented in Eval_Centre_VDF_Elem, Eval_Centre4_VDF_Elem, and Eval_Quick_VDF_Elem.
Definition at line 27 of file Eval_Conv_VDF_tools.h.
{ return dont_call<int>(__func__); }
calcul_g()
virtual void Eval_Conv_VDF_tools::calcul_g (const double , const double , const double , double & , double & , double & , double &) const inline virtual
Reimplemented in Eval_Centre4_VDF_Face.
Definition at line 37 of file Eval_Conv_VDF_tools.h.
{ return dont_call<void>(__func__); }
calcul_g_impl()
void Eval_Conv_VDF_tools::calcul_g_impl (const double dxam, const double dx, const double dxav, double & g1, double & g2, double & g3, double & g4) const protected
Definition at line 113 of file Eval_Conv_VDF_tools.cpp.
{
  g1 = -dx*dx*(dx/2+dxav)/(4*(dx+dxam+dxav)*(dx+dxam)*dxam);
  g2 =  (dx+2*dxam)*(dx+2*dxav)/(8*dxam*(dx+dxav));
  g3 =  (dx+2*dxam)*(dx+2*dxav)/(8*dxav*(dx+dxam));
  g4 = -dx*dx*(dx/2+dxam)/(4*(dx+dxam+dxav)*dxav*(dx+dxav));
}
Referenced by Eval_Centre4_VDF_Face::calcul_g().
conv_centre()
virtual double Eval_Conv_VDF_tools::conv_centre (const double , const double , const double , const double , const double , double , double , double , double) const inline virtual
Reimplemented in Eval_Centre4_VDF_Face.
Definition at line 34 of file Eval_Conv_VDF_tools.h.
{ return dont_call<double>(__func__); }
conv_quick_sharp_moins()
virtual double Eval_Conv_VDF_tools::conv_quick_sharp_moins (const double , const double , const double , const double , const double , const double , const double) const inline virtual
Reimplemented in Eval_Quick_VDF_Face, and Eval_Quick_VDF_Face_Axi.
Definition at line 36 of file Eval_Conv_VDF_tools.h.
{ return dont_call<double>(__func__); }
conv_quick_sharp_moins_impl()
double Eval_Conv_VDF_tools::conv_quick_sharp_moins_impl (const double psc, const double vit_0, const double vit_1, const double vit_1_1, const double dx, const double dm, const double dxam) const protected
Definition at line 38 of file Eval_Conv_VDF_tools.cpp.
{
  double cf, curv, delta_1 = vit_1_1 - vit_1, delta = vit_1 - vit_0, dd1,utc, delta_delta;
  curv = ( delta_1/dxam - delta/dx )/dm ;
// Calcul de cf:
  delta_delta = delta_1+delta;
  dd1 = std::fabs(delta_delta);
  if (dd1 < 1.e-5) cf = 0.125;
  else
    {
      utc = delta_1/delta_delta;
      cf = sharp2(utc);
    }
  return (0.5*(vit_0 + vit_1) - cf*(dx*dx)*curv)*psc;
}
References sharp2().
Referenced by Eval_Quick_VDF_Face::conv_quick_sharp_moins(), and Eval_Quick_VDF_Face_Axi::conv_quick_sharp_moins().
conv_quick_sharp_plus()
virtual double Eval_Conv_VDF_tools::conv_quick_sharp_plus (const double , const double , const double , const double , const double , const double , const double) const inline virtual
Reimplemented in Eval_Quick_VDF_Face, and Eval_Quick_VDF_Face_Axi.
Definition at line 35 of file Eval_Conv_VDF_tools.h.
{ return dont_call<double>(__func__); }
conv_quick_sharp_plus_impl()
double Eval_Conv_VDF_tools::conv_quick_sharp_plus_impl (const double psc, const double vit_0, const double vit_1, const double vit_0_0, const double dx, const double dm, const double dxam) const protected
Definition at line 19 of file Eval_Conv_VDF_tools.cpp.
{
  double cf, curv, delta_0 = vit_0 - vit_0_0, delta = vit_1 - vit_0, dd1,utc, delta_delta;
  curv = (delta/dx - delta_0/dxam)/dm ;
// Calcul de cf:
  delta_delta = delta_0+delta;
  dd1 = std::fabs(delta_delta);
  if (dd1 < 1.e-5) cf = 0.125;
  else
    {
      utc = delta_0/delta_delta;
      cf = sharp2(utc);
    }
  return (0.5*(vit_0 + vit_1) - cf*(dx*dx)*curv)*psc;
}
References sharp2().
Referenced by Eval_Quick_VDF_Face::conv_quick_sharp_plus(), and Eval_Quick_VDF_Face_Axi::conv_quick_sharp_plus().
dim_elem()
virtual double Eval_Conv_VDF_tools::dim_elem (int , int) const inline virtual
Reimplemented in Eval_Centre_VDF_Elem, Eval_Quick_VDF_Elem, Eval_Centre4_VDF_Face, Eval_Quick_VDF_Face, and Eval_Quick_VDF_Face_Axi.
Definition at line 30 of file Eval_Conv_VDF_tools.h.
{ return dont_call<double>(__func__); }
dim_face()
virtual double Eval_Conv_VDF_tools::dim_face (int , int) const inline virtual
Reimplemented in Eval_Quick_VDF_Face, and Eval_Quick_VDF_Face_Axi.
Definition at line 31 of file Eval_Conv_VDF_tools.h.
{ return dont_call<double>(__func__); }
dist_elem()
virtual double Eval_Conv_VDF_tools::dist_elem (int , int , int) const inline virtual
Reimplemented in Eval_Centre_VDF_Elem, Eval_Centre4_VDF_Elem, Eval_Quick_VDF_Elem, Eval_Quick_VDF_Face, and Eval_Quick_VDF_Face_Axi.
Definition at line 32 of file Eval_Conv_VDF_tools.h.
{ return dont_call<double>(__func__); }
dist_elem_axi_impl()
double Eval_Conv_VDF_tools::dist_elem_axi_impl (int n1, int n2, int k, const DoubleTab & xp) const protected
Definition at line 99 of file Eval_Conv_VDF_tools.cpp.
{
  double d_teta, dist ;
  if (k != 1) dist = xp(n2,k)-xp(n1,k) ;
  else
    {
      d_teta = xp(n2,1) - xp(n1,1);
      if (d_teta < 0) d_teta += 2.0*M_PI;
      dist = d_teta * xp(n1,0);
    }
  return dist ;
}
References M_PI.
Referenced by Eval_Quick_VDF_Face_Axi::dist_elem().
dist_elem_period()
virtual double Eval_Conv_VDF_tools::dist_elem_period (int , int , int) const inline virtual
Reimplemented in Eval_Centre4_VDF_Face, Eval_Quick_VDF_Face, and Eval_Quick_VDF_Face_Axi.
Definition at line 33 of file Eval_Conv_VDF_tools.h.
{ return dont_call<double>(__func__); }
dist_face_axi_impl()
double Eval_Conv_VDF_tools::dist_face_axi_impl (int n1, int n2, int k, const DoubleTab & xv) const protected
Definition at line 85 of file Eval_Conv_VDF_tools.cpp.
{
  double d_teta , dist ;
  if (k != 1) dist =  xv(n2,k) - xv(n1,k);
  else
    {
      d_teta = xv(n2,1) - xv(n1,1);
      if (d_teta < 0) d_teta += 2.0*M_PI;
      if (d_teta > M_PI) d_teta -= M_PI ;
      dist = d_teta*xv(n1,0);
    }
  return dist ;
}
References M_PI.
Referenced by Eval_Quick_VDF_Face_Axi::dist_face().
dont_call()
template<typename type > type Eval_Conv_VDF_tools::dont_call (const char * nom_fct) const inline private
Definition at line 64 of file Eval_Conv_VDF_tools.h.
  {
    Cerr << "What ??? You should not call the function " << nom_fct << finl;
    throw;
  }
References Cerr, and finl.
face_amont_conj()
virtual int Eval_Conv_VDF_tools::face_amont_conj (int , int , int) const inline virtual
Reimplemented in Eval_Centre4_VDF_Face, Eval_Quick_VDF_Face, and Eval_Quick_VDF_Face_Axi.
Definition at line 28 of file Eval_Conv_VDF_tools.h.
{ return dont_call<int>(__func__); }
face_amont_conj_axi_impl()
int Eval_Conv_VDF_tools::face_amont_conj_axi_impl (int num_face, int k, int i, int dimension, const IntTab & face_voisins, const IntTab & elem_faces, const IntVect & orientation) const protected
Definition at line 56 of file Eval_Conv_VDF_tools.cpp.
{
  int ori = orientation(num_face), elem1 = face_voisins(num_face,1);
  int face,elem_bis = -2, face_conj = -1 ;
  if(elem1 != -1)
    {
      face = elem_faces(elem1, k+i*dimension);
      elem_bis = face_voisins(face,i);
      if (elem_bis != -1) face_conj = elem_faces(elem_bis, ori);
      else face_conj = -1;
    }
  if ((elem1==-1) || (elem_bis==-1))
    {
      elem1 = face_voisins(num_face,0);
      if(elem1 != -1)
        {
          face = elem_faces(elem1, k+i*dimension);
          elem_bis = face_voisins(face,i);
          assert(elem_bis!=-2);
          if (elem_bis != -1) face_conj = elem_faces(elem_bis, ori);
          else face_conj = -1;
        }
    }
  return face_conj;
}
Referenced by Eval_Quick_VDF_Face_Axi::face_amont_conj().
face_amont_princ()
virtual int Eval_Conv_VDF_tools::face_amont_princ (int , int) const inline virtual
Reimplemented in Eval_Centre4_VDF_Face, Eval_Quick_VDF_Face, and Eval_Quick_VDF_Face_Axi.
Definition at line 29 of file Eval_Conv_VDF_tools.h.
{ return dont_call<int>(__func__); }
qcentre()
template<typename Type_Double > void Eval_Conv_VDF_tools::qcentre (const double , const int , const int , const int , const int , const int , const DoubleTab & , Type_Double &) const inline
Definition at line 40 of file Eval_Conv_VDF_tools.h.
{ return dont_call<void>(__func__); }
qcentre2_impl()
template<typename Type_Double > void Eval_Conv_VDF_tools::qcentre2_impl (const double psc, const int num0, const int num1, const int num0_0, const int num1_1, const int face, const DoubleTab & transporte, Type_Double & flux) const protected
Definition at line 107 of file Eval_Conv_VDF_tools.h.
{
  int k, ncomp = flux.size_array();
  Type_Double T0(ncomp), T1(ncomp);
  for (k=0; k<ncomp; k++)
    {
      T0[k] = transporte(num0,k);
      T1[k] = transporte(num1,k);
    }
  for (k=0; k<ncomp; k++) flux[k] =0.5 * (T0[k] + T1[k]) * psc ;
}
qcentre4_impl()
template<typename Type_Double > void Eval_Conv_VDF_tools::qcentre4_impl (const int ori, const double dx, const double dxam, const double dxav, const double psc, const int num0, const int num1, const int num0_0, const int num1_1, const int face, const DoubleTab & transporte, Type_Double & flux) const protected
Definition at line 121 of file Eval_Conv_VDF_tools.h.
{
  int k, ncomp = flux.size_array();
  Type_Double T0(ncomp), T0_0(ncomp), T1(ncomp), T1_1(ncomp);
  for (k=0; k<ncomp; k++)
    {
      T0[k] = transporte(num0,k);
      T0_0[k] = transporte(num0_0,k);
      T1[k] = transporte(num1,k);
      T1_1[k] = transporte(num1_1,k);
    }
  const double g1 = -dx*dx*(dx/2+dxav)/(4*(dx+dxam+dxav)*(dx+dxam)*dxam), g2 = (dx+2*dxam)*(dx+2*dxav)/(8*dxam*(dx+dxav));
  const double g3 = (dx+2*dxam)*(dx+2*dxav)/(8*dxav*(dx+dxam)), g4 = -dx*dx*(dx/2+dxam)/(4*(dx+dxam+dxav)*dxav*(dx+dxav));
  for (k=0; k<ncomp; k++) flux[k] =( g1*T0_0[k] + g2*T0[k] + g3*T1[k] + g4*T1_1[k] ) * psc ;
}
quick_fram()
template<typename Type_Double > void Eval_Conv_VDF_tools::quick_fram (const double , const int , const int , const int , const int , const int , const DoubleTab & , Type_Double &) const inline
Definition at line 43 of file Eval_Conv_VDF_tools.h.
{ return dont_call<void>(__func__); }
quick_fram_impl()
template<typename Type_Double > void Eval_Conv_VDF_tools::quick_fram_impl (const int ori, const double dx, const double dm0, const double dxam0, const double dm1, const double dxam1, const double psc, const int num0, const int num1, const int num0_0, const int num1_1, const int face, const DoubleTab & transporte, Type_Double & flux) const protected
Definition at line 139 of file Eval_Conv_VDF_tools.h.
{
  const int ncomp = flux.size_array();
  double fr, T0,T0_0=0,T1,T1_1=0,trans_amont,curv;
  for (int k=0; k<ncomp; k++)
    {
      T0 = transporte(num0,k);
      T0_0 = (num0_0!=-1?transporte(num0_0,k):0);
      T1 = transporte(num1,k);
      T1_1 = (num1_1!=-1?transporte(num1_1,k):0);
      if (psc > 0)
        {
          assert(num0_0!=-1);
          trans_amont = T0;
          curv = ( (T1 - T0)/dx - (T0 - T0_0)/dxam0 )/dm0 ;
        }
      else
        {
          assert(num1_1!=-1);
          trans_amont = T1;
          curv = ( (T1_1 - T1)/dxam1 - (T1 - T0)/dx )/dm1;
        }
      flux[k] = 0.5*(T0+T1) - 0.125*(dx*dx)*curv;
// On applique le filtre Fram:
      fr = ( num0_0 != -1 && num1_1 != -1 ) ? Fram(T0_0,T0,T1,T1_1) : 1.;
      flux[k] = ((1.-fr)*flux[k] + fr*trans_amont)*psc;
    }
}
References Fram().
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Eval_Conv/Eval_Conv_VDF_tools.h
src/VDF/Operateurs/Eval_Conv/Eval_Conv_VDF_tools.cpp