TRUST: Schema_Adams_Bashforth_order_3 Class Reference
Schema_Adams_Bashforth_order_3 Class Reference
classe Schema_Adams_Bashforth_order_3
Cette classe represente un schema en temps d'Adams-Bashforth d'ordre 3
a pas de temps variable :
U(n+1) = U(n) + dt*(23/12*(dU/dt)(n)-4/3(dU/dt)(n-1)+5/12(dU/dt)(n-2))
si le pas de temps est constant
#include <Schema_Adams_Bashforth_order_3.h>
Public Member Functions
Schema_Adams_Bashforth_order_3 ()
~Schema_Adams_Bashforth_order_3 ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int nb_pas_dt_seuil () const
Renvoie le nombre de pas de temps strictement au dela duquel on applique le schema d Adams-Bahshforth.
Ici : on a besoin d'au moins 2 temps du passe donc 1.
int nb_valeurs_passees () const
Renvoie le nombre de valeurs temporelles du passe.
Ici : n-2 et n-1 donc 1.
int nb_valeurs_temporelles () const
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n-2, n-1, n et n+1 donc 4.
void compute_adams_bashforth_coefficients (double time_step, const DoubleTab &times)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Schema_Adams_Bashforth_order_3 & self_cast (Objet_U &)
static const
Schema_Adams_Bashforth_order_3 & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Detailed Description
classe Schema_Adams_Bashforth_order_3
Cette classe represente un schema en temps d'Adams-Bashforth d'ordre 3
a pas de temps variable :
U(n+1) = U(n) + dt*(23/12*(dU/dt)(n)-4/3(dU/dt)(n-1)+5/12(dU/dt)(n-2))
si le pas de temps est constant
Definition at line 39 of file Schema_Adams_Bashforth_order_3.h.
Constructor & Destructor Documentation
Schema_Adams_Bashforth_order_3::Schema_Adams_Bashforth_order_3 ()
Definition at line 29 of file Schema_Adams_Bashforth_order_3.cpp.
Schema_Adams_Bashforth_order_3::~Schema_Adams_Bashforth_order_3 ()
Definition at line 29 of file Schema_Adams_Bashforth_order_3.cpp.
Member Function Documentation
void Schema_Adams_Bashforth_order_3::compute_adams_bashforth_coefficients (double time_step, const DoubleTab & times) [virtual]
Implements Schema_Adams_Bashforth_base.
Definition at line 165 of file Schema_Adams_Bashforth_order_3.cpp.
References Cerr, Schema_Adams_Bashforth_base::coefficients(), Schema_Temps_base::facteur_securite_pas(), finl, Schema_Temps_base::limpr(), Ln02(), Ln12(), Schema_Temps_base::nb_pas_dt(), Array_base::NOCOPY_NOINIT, DoubleTab::resize(), and ArrOfDouble::size_array().
{
  if (nb_pas_dt()<100 && limpr() && facteur_securite_pas()==1.0)
    {
      Cerr << finl;
      Cerr << "********************* Warning (printed only on the first 100 time steps) **********************"<< finl;
      Cerr << "The Adams Bashforth order 3 scheme is recommended with a facsec lower than 1.0 for example 0.5."<< finl;
      Cerr << "***********************************************************************************************"<< finl;
// See $TRUST_ROOT/tests/Reference/Schema_Adams_Bashforth_order_3 test case.
    }
  assert(times.size_array() == 4); //2 past times, present and future times, stored in ascending order inside "times" table
  if (coefficients().size_array() != 3)
    {
      coefficients().resize(3,Array_base::NOCOPY_NOINIT);
    }
  double inv_time_step  = 1./time_step;
  double time_n_minus_2 = times[0];
  double time_n_minus_1 = times[1];
  double time_n         = times[2];
  double time_n_plus_1  = times[3];
  coefficients()[2] = Ln02(time_n_plus_1,time_n,time_n_minus_1,time_n_minus_2) * inv_time_step;
  coefficients()[1] = Ln12(time_n_plus_1,time_n,time_n_minus_1,time_n_minus_2) * inv_time_step;
  coefficients()[0] = 1-coefficients()[2]-coefficients()[1];
}
Objet_U * Schema_Adams_Bashforth_order_3::cree_instance () [static]
Definition at line 29 of file Schema_Adams_Bashforth_order_3.cpp.
int Schema_Adams_Bashforth_order_3::duplique () const [virtual]
Implements Schema_Adams_Bashforth_base.
Definition at line 29 of file Schema_Adams_Bashforth_order_3.cpp.
const Type_info * Schema_Adams_Bashforth_order_3::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Adams_Bashforth_base.
Definition at line 29 of file Schema_Adams_Bashforth_order_3.cpp.
const Type_info * Schema_Adams_Bashforth_order_3::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Adams_Bashforth_base.
Definition at line 29 of file Schema_Adams_Bashforth_order_3.cpp.
int Schema_Adams_Bashforth_order_3::nb_pas_dt_seuil () const [inline, virtual]
Renvoie le nombre de pas de temps strictement au dela duquel on applique le schema d Adams-Bahshforth.
Ici : on a besoin d'au moins 2 temps du passe donc 1.
Implements Schema_Explicite_Multi_TimeStep_base.
Definition at line 92 of file Schema_Adams_Bashforth_order_3.cpp.
{
  return 1 ;
}
int Schema_Adams_Bashforth_order_3::nb_valeurs_passees () const [inline, virtual]
Renvoie le nombre de valeurs temporelles du passe.
Ici : n-2 et n-1 donc 1.
Implements Schema_Explicite_Multi_TimeStep_base.
Definition at line 100 of file Schema_Adams_Bashforth_order_3.cpp.
{
  return 2 ;
}
int Schema_Adams_Bashforth_order_3::nb_valeurs_temporelles () const [virtual]
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n-2, n-1, n et n+1 donc 4.
Implements Schema_Temps_base.
Definition at line 84 of file Schema_Adams_Bashforth_order_3.cpp.
{
  return 4 ;
}
Sortie & Schema_Adams_Bashforth_order_3::printOn (Sortie & s) const [protected, virtual]
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Schema_Adams_Bashforth_base.
Definition at line 47 of file Schema_Adams_Bashforth_order_3.cpp.
{
  return  Schema_Adams_Bashforth_base::printOn(s);
}
Entree & Schema_Adams_Bashforth_order_3::readOn (Entree & s) [protected, virtual]
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Schema_Adams_Bashforth_base.
Definition at line 68 of file Schema_Adams_Bashforth_order_3.cpp.
{
  return Schema_Adams_Bashforth_base::readOn(s) ;
}
Schema_Adams_Bashforth_order_3 & Schema_Adams_Bashforth_order_3::self_cast (Objet_U & r) [static]
Reimplemented from Schema_Adams_Bashforth_base.
Definition at line 29 of file Schema_Adams_Bashforth_order_3.cpp.
const Schema_Adams_Bashforth_order_3 & Schema_Adams_Bashforth_order_3::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Schema_Adams_Bashforth_base.
Definition at line 29 of file Schema_Adams_Bashforth_order_3.cpp.
unsigned Schema_Adams_Bashforth_order_3::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 29 of file Schema_Adams_Bashforth_order_3.cpp.
Member Data Documentation
const Type_info Schema_Adams_Bashforth_order_3::info_obj [static]
Reimplemented from Schema_Adams_Bashforth_base.
Definition at line 42 of file Schema_Adams_Bashforth_order_3.h.
The documentation for this class was generated from the following files:
src/Kernel/Schemas_Temps/Schema_Adams_Bashforth_order_3.h
src/Kernel/Schemas_Temps/Schema_Adams_Bashforth_order_3.cpp