TRUST: Champ_front_debit_QC Class Reference
Champ_front_debit_QC Class Reference
classe Champ_front_debit_QC
Classe derivee de Champ_front_base qui represente les
champs aux frontieres debit_QCs : ch(*,i)=m(i)+alea*amplitude(i)
ou alea est une variable aleatoire de loi uniforme sur [0,1]
#include <Champ_front_debit_QC.h>
Public Member Functions
Champ_front_debit_QC ()
~Champ_front_debit_QC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Champ_front_base & affecter_ (const Champ_front_base &ch)
Pas code !!
virtual void mettre_a_jour (double temps)
Mise a jour du temps
et retirage aleatoire des valeurs du bruit.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_front_debit_QC & self_cast (Objet_U &)
static const Champ_front_debit_QC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Impression sur un flot de sortie au format:
taille
valeur(0) ... valeur(i) ... valeur(taille-1)
virtual Entree & readOn (Entree &)
Lecture a partir d'un flot d'entree au format:
nombre_de_composantes
moyenne moyenne(0) ... moyenne(nombre_de_composantes-1)
moyenne amplitude(0) ... amplitude(nombre_de_composantes-1)
Protected Attributes
int ismoyen
DoubleVect Debit
Ref_Fluide_Quasi_Compressible fluide
Detailed Description
classe Champ_front_debit_QC
Classe derivee de Champ_front_base qui represente les
champs aux frontieres debit_QCs : ch(*,i)=m(i)+alea*amplitude(i)
ou alea est une variable aleatoire de loi uniforme sur [0,1]
Definition at line 41 of file Champ_front_debit_QC.h.
Constructor & Destructor Documentation
Champ_front_debit_QC::Champ_front_debit_QC ()
Definition at line 31 of file Champ_front_debit_QC.cpp.
Champ_front_debit_QC::~Champ_front_debit_QC ()
Definition at line 31 of file Champ_front_debit_QC.cpp.
Member Function Documentation
Champ_front_base & Champ_front_debit_QC::affecter_ (const Champ_front_base & ch) [virtual]
Pas code !!
Returns:
Champ_front_base&
Signification:
Contraintes:
Implements Champ_front_base.
Definition at line 142 of file Champ_front_debit_QC.cpp.
{
  return *this;
}
Objet_U * Champ_front_debit_QC::cree_instance () [static]
Definition at line 31 of file Champ_front_debit_QC.cpp.
int Champ_front_debit_QC::duplique () const [virtual]
Implements Ch_front_var_instationnaire_indep.
Definition at line 31 of file Champ_front_debit_QC.cpp.
const Type_info * Champ_front_debit_QC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 31 of file Champ_front_debit_QC.cpp.
const Type_info * Champ_front_debit_QC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 31 of file Champ_front_debit_QC.cpp.
void Champ_front_debit_QC::mettre_a_jour (double temps) [virtual]
Mise a jour du temps
et retirage aleatoire des valeurs du bruit.
Reimplemented from Champ_front_base.
Definition at line 162 of file Champ_front_debit_QC.cpp.
References Debit, Zone_VF::face_surfaces(), Zone_VF::face_voisins(), fluide, ismoyen, Champ_front_base::la_frontiere_dis, Fluide_Dilatable_base::loi_etat(), Process::mp_sum(), Field_base::nb_comp(), Frontiere::nb_faces(), Front_VF::num_premiere_face(), ref_cast, Ref_Fluide_Quasi_Compressible::valeur(), Ref_Frontiere_dis_base::valeur(), Champ_front_base::valeurs(), and Champ_front_base::zone_dis().
{
  const Frontiere& front=la_frontiere_dis->frontiere();
  int nb_faces=front.nb_faces();
  DoubleTab& tab=valeurs();
  int dim=nb_comp();
  const Zone_VDF& la_zone_VDF = ref_cast(Zone_VDF,zone_dis());
  const IntTab& face_voisins=la_zone_VDF.face_voisins();
  const Front_VF& front_vf=ref_cast(Front_VF,la_frontiere_dis.valeur());
  int ndeb = front_vf.num_premiere_face();
  int nfin = ndeb + nb_faces;
  const DoubleTab& tab_rhonp1P0 =fluide.valeur().loi_etat()->rho_np1();
  if (ismoyen==0)
    for (int num_face=ndeb; num_face<nfin; num_face++)
      {
        int n0 = face_voisins(num_face, 0);
        if (n0 == -1)
          n0 = face_voisins(num_face, 1);
        for (int ori=0; ori<dim; ori++)
          tab(num_face-ndeb,ori)=Debit(ori)/tab_rhonp1P0(n0);
      }
  else
    {
      int num_face;
      double rho_moy=0,S=0,s;
      const DoubleVect& surface=la_zone_VDF.face_surfaces();
      for ( num_face=ndeb; num_face<nfin; num_face++)
        {
          int n0 = face_voisins(num_face, 0);
          if (n0 == -1)
            n0 = face_voisins(num_face, 1);
          s=surface(num_face);
          S+=s;
          rho_moy+=s*tab_rhonp1P0(n0);
        }
      S = mp_sum(S);
      rho_moy = mp_sum(rho_moy);
      rho_moy/=S;
      for ( num_face=ndeb; num_face<nfin; num_face++)
        for (int ori=0; ori<dim; ori++)
          tab(num_face-ndeb,ori)=Debit(ori)/rho_moy;
    }
}
Sortie & Champ_front_debit_QC::printOn (Sortie & os) const [protected, virtual]
Impression sur un flot de sortie au format:
taille
valeur(0) ... valeur(i) ... valeur(taille-1)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 56 of file Champ_front_debit_QC.cpp.
References DoubleVect::size(), and Champ_front_base::valeurs().
{
  const DoubleTab& tab=valeurs();
  os << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    os << tab(0,i);
  return os;
}
Entree & Champ_front_debit_QC::readOn (Entree & is) [protected, virtual]
Lecture a partir d'un flot d'entree au format:
nombre_de_composantes
moyenne moyenne(0) ... moyenne(nombre_de_composantes-1)
moyenne amplitude(0) ... amplitude(nombre_de_composantes-1)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 84 of file Champ_front_debit_QC.cpp.
References Cerr, Debit, Probleme_base::equation(), Process::exit(), finl, Field_base::fixer_nb_comp(), fluide, ismoyen, Equation_base::milieu(), Interprete::objet(), ref_cast, and DoubleVect::resize().
{
  Cerr<<"Champ_front_debit_QC_VDF usage : dim { val1 .. valdim } [ moyen ] nom_pb"<<finl;
  ismoyen=0;
  int dim;
  is >> dim;
  Motcle motlu;
  Motcles les_mots(2);
  les_mots[0]="{";
  les_mots[1]="}";
  is >> motlu;
  if (motlu != les_mots[0])
    {
      Cerr << "Erreur a la lecture d'un Champ_front_debit_QC" << finl;
      Cerr << "On attendait { a la place de " << motlu << finl;
      exit();
    }
  fixer_nb_comp(dim);
  Debit.resize(dim);
  for(int i=0; i<dim; i++)
    is >> Debit(i);
  is >> motlu;
  if (motlu != les_mots[1])
    {
      Cerr << "Erreur a la lecture d'un Champ_front_debit_QC" << finl;
      Cerr << "On attendait } a la place de " << finl;
      exit();
    }
  Nom nom_pb;
  is>>nom_pb;
  Motcle nom;
  nom=nom_pb;
  if (nom=="moyen")
    {
      ismoyen=1;
      is >> nom_pb;
    }
  Objet_U& ob1=Interprete::objet(nom_pb);
  const Probleme_base& pb=ref_cast(Probleme_base,ob1);
  fluide=ref_cast(Fluide_Quasi_Compressible,pb.equation(0).milieu());
  return is;
}
Champ_front_debit_QC & Champ_front_debit_QC::self_cast (Objet_U & r) [static]
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 31 of file Champ_front_debit_QC.cpp.
const Champ_front_debit_QC & Champ_front_debit_QC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 31 of file Champ_front_debit_QC.cpp.
unsigned Champ_front_debit_QC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 31 of file Champ_front_debit_QC.cpp.
Member Data Documentation
DoubleVect Champ_front_debit_QC::Debit [protected]
Definition at line 52 of file Champ_front_debit_QC.h.
Referenced by mettre_a_jour(), and readOn().
Ref_Fluide_Quasi_Compressible Champ_front_debit_QC::fluide [protected]
Definition at line 53 of file Champ_front_debit_QC.h.
Referenced by mettre_a_jour(), and readOn().
const Type_info Champ_front_debit_QC::info_obj [static]
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 43 of file Champ_front_debit_QC.h.
int Champ_front_debit_QC::ismoyen [protected]
Definition at line 51 of file Champ_front_debit_QC.h.
Referenced by mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VDF/Champ_front_debit_QC.h
src/ThHyd/Dilatable/Quasi_Compressible/VDF/Champ_front_debit_QC.cpp