TRUST: Op_Evanescence_Homogene_CoviMAC_Elem Class Reference
Op_Evanescence_Homogene_CoviMAC_Elem Class Reference
Classe Op_Evanescence_Homogene_CoviMAC_Elem
gestion dans CoviMAC de l'evanescence dans une equation aux elements (masse, energie...)
#include <Op_Evanescence_Homogene_CoviMAC_Elem.h>
Public Member Functions
Op_Evanescence_Homogene_CoviMAC_Elem ()
~Op_Evanescence_Homogene_CoviMAC_Elem ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int has_interface_blocs () const
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Op_Evanescence_Homogene_CoviMAC_Elem & self_cast (Objet_U &)
static const
Op_Evanescence_Homogene_CoviMAC_Elem & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Private Attributes
double alpha_res_
double alpha_res_min_ = 0
Detailed Description
Classe Op_Evanescence_Homogene_CoviMAC_Elem
gestion dans CoviMAC de l'evanescence dans une equation aux elements (masse, energie...)
Definition at line 36 of file Op_Evanescence_Homogene_CoviMAC_Elem.h.
Constructor & Destructor Documentation
Op_Evanescence_Homogene_CoviMAC_Elem::Op_Evanescence_Homogene_CoviMAC_Elem ()
Definition at line 35 of file Op_Evanescence_Homogene_CoviMAC_Elem.cpp.
Op_Evanescence_Homogene_CoviMAC_Elem::~Op_Evanescence_Homogene_CoviMAC_Elem ()
Definition at line 35 of file Op_Evanescence_Homogene_CoviMAC_Elem.cpp.
Member Function Documentation
void Op_Evanescence_Homogene_CoviMAC_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) [virtual]
Reimplemented from Operateur_base.
Objet_U * Op_Evanescence_Homogene_CoviMAC_Elem::cree_instance () [static]
Definition at line 35 of file Op_Evanescence_Homogene_CoviMAC_Elem.cpp.
void Op_Evanescence_Homogene_CoviMAC_Elem::dimensionner_blocs (matrices_t matrices) [virtual]
Reimplemented from Operateur_base.
int Op_Evanescence_Homogene_CoviMAC_Elem::duplique () const [virtual]
Implements Operateur_Evanescence_base.
Definition at line 35 of file Op_Evanescence_Homogene_CoviMAC_Elem.cpp.
const Type_info * Op_Evanescence_Homogene_CoviMAC_Elem::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Evanescence_base.
Definition at line 35 of file Op_Evanescence_Homogene_CoviMAC_Elem.cpp.
int Op_Evanescence_Homogene_CoviMAC_Elem::has_interface_blocs () const [inline, virtual]
Reimplemented from Operateur_base.
Definition at line 40 of file Op_Evanescence_Homogene_CoviMAC_Elem.h.
  {
    return 1;
  };
const Type_info * Op_Evanescence_Homogene_CoviMAC_Elem::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Evanescence_base.
Definition at line 35 of file Op_Evanescence_Homogene_CoviMAC_Elem.cpp.
Sortie & Op_Evanescence_Homogene_CoviMAC_Elem::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Evanescence_base.
Definition at line 37 of file Op_Evanescence_Homogene_CoviMAC_Elem.cpp.
{
  return os;
}
Entree & Op_Evanescence_Homogene_CoviMAC_Elem::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Evanescence_base.
Definition at line 42 of file Op_Evanescence_Homogene_CoviMAC_Elem.cpp.
References Param::ajouter(), alpha_res_, alpha_res_min_, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and Param::REQUIRED.
{
  Param param(que_suis_je());
  param.ajouter("alpha_res", &alpha_res_, Param::REQUIRED);
  param.ajouter("alpha_res_min", &alpha_res_min_);
  param.lire_avec_accolades_depuis(is);
  return is;
}
Op_Evanescence_Homogene_CoviMAC_Elem & Op_Evanescence_Homogene_CoviMAC_Elem::self_cast (Objet_U & r) [static]
Reimplemented from Operateur_Evanescence_base.
Definition at line 35 of file Op_Evanescence_Homogene_CoviMAC_Elem.cpp.
const Op_Evanescence_Homogene_CoviMAC_Elem & Op_Evanescence_Homogene_CoviMAC_Elem::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Operateur_Evanescence_base.
Definition at line 35 of file Op_Evanescence_Homogene_CoviMAC_Elem.cpp.
unsigned Op_Evanescence_Homogene_CoviMAC_Elem::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 35 of file Op_Evanescence_Homogene_CoviMAC_Elem.cpp.
Member Data Documentation
double Op_Evanescence_Homogene_CoviMAC_Elem::alpha_res_ [private]
Definition at line 48 of file Op_Evanescence_Homogene_CoviMAC_Elem.h.
Referenced by readOn().
double Op_Evanescence_Homogene_CoviMAC_Elem::alpha_res_min_ = 0 [private]
Definition at line 48 of file Op_Evanescence_Homogene_CoviMAC_Elem.h.
Referenced by readOn().
const Type_info Op_Evanescence_Homogene_CoviMAC_Elem::info_obj [static]
Reimplemented from Operateur_Evanescence_base.
Definition at line 38 of file Op_Evanescence_Homogene_CoviMAC_Elem.h.
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/CoviMAC/Op_Evanescence_Homogene_CoviMAC_Elem.h
src/ThHyd/Multiphase/CoviMAC/Op_Evanescence_Homogene_CoviMAC_Elem.cpp