TRUST: VIntdata Class Reference
VIntdata Class Reference
VIntdata alloue une zone de memoire de la taille specifiee au
constructeur, et libere la zone de memoire a la destruction.
La memoire peut etre allouee sur le tas (avec new) ou par le
mecanisme Memoire::add_trav_int.
"ref_count" compte le nombre de pointeurs qui font reference a "this".
(permet au dernier utilisateur de l'objet de le detruire), voir
ArrOfInt.
Public Member Functions
VIntdata (int size, ArrOfInt::Storage storage)
Construit un VIntdata de taille size >= 0
Parametre: int s
Signification: taille du VIntdata, il faut size >= 0
Parametre: Storage storage
Signification: indique si la memoire doit etre allouee
avec "new" ou avec "memoire.add_trav_int()"
Valeurs par defaut: STANDARD (allocation avec "new")
~VIntdata ()
Detruit la zone de memoire allouee.
int add_one_ref ()
Un nouveau tableau utilise cette zone memoire :
incremente ref_count.
int suppr_one_ref ()
Un tableau de moins utilise cette zone memoire
decremente ref_count.
int * get_data ()
renvoie data_
const int * get_data () const
renvoie data_
int ref_count () const
renvoie ref_count_
int get_size () const
renvoie size_
Private Member Functions
VIntdata (const VIntdata &v)
Constructeur par copie. Interdit : genere une erreur !
VIntdata & operator= (const VIntdata &v)
Operateur= interdit. Genere une erreur !
Private Attributes
int * data_
int ref_count_
int size_
Int_ptr_trav * d_ptr_trav_
Detailed Description
VIntdata alloue une zone de memoire de la taille specifiee au
constructeur, et libere la zone de memoire a la destruction.
La memoire peut etre allouee sur le tas (avec new) ou par le
mecanisme Memoire::add_trav_int.
"ref_count" compte le nombre de pointeurs qui font reference a "this".
(permet au dernier utilisateur de l'objet de le detruire), voir
ArrOfInt.
Definition at line 64 of file ArrOfInt.cpp.
Constructor & Destructor Documentation
VIntdata::VIntdata (int size, ArrOfInt::Storage storage)
Construit un VIntdata de taille size >= 0
Parametre: int s
Signification: taille du VIntdata, il faut size >= 0
Parametre: Storage storage
Signification: indique si la memoire doit etre allouee
avec "new" ou avec "memoire.add_trav_int()"
Valeurs par defaut: STANDARD (allocation avec "new")
Definition at line 108 of file ArrOfInt.cpp.
References Memoire::add_trav_int(), Cerr, d_ptr_trav_, data_, Process::exit(), finl, Int_ptr_trav::i_ptr_(), Memoire::Instance(), ref_count_, size_, ArrOfInt::STANDARD, and ArrOfInt::TEMP_STORAGE.
{
  int size_warning=100000000;
  assert(size >= 0);
  if (size == 0)
    storage = ArrOfInt::STANDARD;
  switch (storage)
    {
    case ArrOfInt::STANDARD:
      {
        d_ptr_trav_ = 0;
        if (size>size_warning) Cerr << "Warning: Allocating an array of " << size << " Int ...";
#ifdef _EXCEPTION_
// Allocation de la memoire sur le tas
        try
          {
            data_ = new int[size];
          }
        catch(...)
          {
            Cerr << "unable to allocate " << size << " int " << finl;
            Process::exit();
          }
#else
        data_ = new int[size];
        if(!data_)
          {
            Cerr << "unable to allocate " << size << "int " << finl;
            Process::exit();
          }
#endif
        if (size>size_warning) Cerr << " OK" << finl;
        break;
      }
    case ArrOfInt::TEMP_STORAGE:
      {
// Allocation de la memoire sur un tas special.
// La memoire ne sera pas rendue au systeme mais conservee pour une
// reutilisation ulterieure.
        Memoire& memoire = Memoire::Instance();
        if (size>size_warning) Cerr << "Warning: Allocating or reusing a IntTrav of " << size << " elements ...";
        d_ptr_trav_ = memoire.add_trav_int(size);
        assert(d_ptr_trav_ != 0);
        data_ = d_ptr_trav_->i_ptr_();
        if (size>size_warning) Cerr << " OK" << finl;
        break;
      }
    default:
      Process::exit();
    }
  ref_count_ = 1;
  size_ = size;
  assert(data_ != 0);
}
VIntdata::~VIntdata ()
Detruit la zone de memoire allouee.
< paranoia: si size_==-1 c'est qu'on pointe sur un zombie
< (pointeur vers un objet qui a ete detruit)
Definition at line 170 of file ArrOfInt.cpp.
References d_ptr_trav_, data_, ref_count_, size_, and Int_ptr_trav::unlock().
{
  assert(ref_count_ == 0);
  if (d_ptr_trav_ == 0)
    {
// Stockage STANDARD
      delete[] data_;
    }
  else
    {
// Stockage TEMP_STORAGE
      d_ptr_trav_->unlock();
      d_ptr_trav_ = 0;
    }
  data_ = 0;  //!< paranoia: si size_==-1 c'est qu'on pointe sur un zombie
  size_ = -1; //!<  (pointeur vers un objet qui a ete detruit)
}
VIntdata::VIntdata (const VIntdata & v) [private]
Constructeur par copie. Interdit : genere une erreur !
Definition at line 236 of file ArrOfInt.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Error in VIntdata: VIntdata (const VIntdata & v)" << finl;
  Process::exit();
}
Member Function Documentation
int VIntdata::add_one_ref () [inline]
Un nouveau tableau utilise cette zone memoire :
incremente ref_count.
Returns:
int
Signification: ref_count
Definition at line 205 of file ArrOfInt.cpp.
References ref_count_.
Referenced by ArrOfInt::attach_array().
{
  return ++ref_count_;
}
const int * VIntdata::get_data () const [inline]
renvoie data_
Definition at line 230 of file ArrOfInt.cpp.
References data_.
{
  return data_;
}
int * VIntdata::get_data () [inline]
renvoie data_
Definition at line 224 of file ArrOfInt.cpp.
References data_.
Referenced by ArrOfInt::ArrOfInt(), and ArrOfInt::memory_resize().
{
  return data_;
}
int VIntdata::get_size () const [inline]
renvoie size_
Definition at line 195 of file ArrOfInt.cpp.
References size_.
Referenced by ArrOfInt::memory_resize().
{
  return size_;
}
VIntdata & VIntdata::operator= (const VIntdata & v) [private]
Operateur= interdit. Genere une erreur !
Definition at line 243 of file ArrOfInt.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Error in VIntdata::operator=(const VIntdata & v)" << finl;
  Process::exit();
  return *this;
}
int VIntdata::ref_count () const [inline]
renvoie ref_count_
Definition at line 189 of file ArrOfInt.cpp.
References ref_count_.
Referenced by ArrOfInt::ref_count().
{
  return ref_count_;
}
int VIntdata::suppr_one_ref () [inline]
Un tableau de moins utilise cette zone memoire
decremente ref_count.
Returns:
int
Signification: ref_count
Definition at line 217 of file ArrOfInt.cpp.
References ref_count_.
Referenced by ArrOfInt::detach_array().
{
  assert(ref_count_ > 0);
  return (--ref_count_);
}
Member Data Documentation
Int_ptr_trav* VIntdata::d_ptr_trav_ [private]
Definition at line 94 of file ArrOfInt.cpp.
Referenced by VIntdata(), and ~VIntdata().
int* VIntdata::data_ [private]
Definition at line 84 of file ArrOfInt.cpp.
Referenced by get_data(), VIntdata(), and ~VIntdata().
int VIntdata::ref_count_ [private]
Definition at line 88 of file ArrOfInt.cpp.
Referenced by add_one_ref(), ref_count(), suppr_one_ref(), VIntdata(), and ~VIntdata().
int VIntdata::size_ [private]
Definition at line 91 of file ArrOfInt.cpp.
Referenced by get_size(), VIntdata(), and ~VIntdata().
The documentation for this class was generated from the following file:
src/Kernel/Math/ArrOfInt.cpp