TRUST: Domain_Graph Class Reference
Domain_Graph Class Reference
Build the graph of the domain that the METIS/PARMETIS/PTSCOTCH libraries need.
#include <Domain_Graph.h>
Public Member Functions
void construire_graph_from_segment (const Domaine &dom, const int use_weights)
void construire_graph_elem_elem (const Domaine &dom, const Noms &liste_bords_periodiques, const int use_weights, Static_Int_Lists &graph_elements_perio)
Private Attributes
int nvtxs
int nedges
int weightflag
ArrOfInt xadj
ArrOfInt adjncy
ArrOfInt vwgts
ArrOfInt ewgts
ArrOfInt vtxdist
ArrOfInt edgegsttab
Friends
class Partitionneur_Metis
class Partitionneur_Parmetis
class Partitionneur_Ptscotch
Detailed Description
Build the graph of the domain that the METIS/PARMETIS/PTSCOTCH libraries need.
Definition at line 21 of file Domain_Graph.h.
Member Function Documentation
construire_graph_elem_elem()
void Domain_Graph::construire_graph_elem_elem (const Domaine & dom, const Noms & liste_bords_periodiques, const int use_weights, Static_Int_Lists & graph_elements_perio)
< Les sommets de la face en cours
< Les elements voisins d'une_face
< l'element i_elem n'est pas voisin: erreur interne
< l'element i_elem n'est pas voisin: erreur interne
< -1 peut faire des partitions discontinues ou pas equilibrees du tout
Definition at line 163 of file Domain_Graph.cpp.
{
  Static_Int_Lists som_elem;
  const Zone& zone = dom.zone(0);
  const Elem_geom_base& type_elem = zone.type_elem().valeur();
  IntTab faces_element_reference;
  const int is_regular =
    type_elem.get_tab_faces_sommets_locaux(faces_element_reference);
  if (! is_regular)
    {
      Cerr << "Error in Domain_Graph::construire_graph_elem_elem\n"
           << " The type of element is not supported" << finl;
      ref_cast(Poly_geom_base,type_elem).get_tab_faces_sommets_locaux(faces_element_reference,0);
    }
  int nb_faces_par_element = faces_element_reference.dimension(0);
  const int nb_sommets_par_face = faces_element_reference.dimension(1);
  const IntTab& elem_som = zone.les_elems();
  const int nb_elem = zone.nb_elem();
  ArrOfInt offsets(Process::nproc());
  offsets = mppartial_sum(nb_elem);
  envoyer_all_to_all(offsets, offsets);
  int my_offset = offsets[Process::me()];
  Cerr << " Construction of the som_elem connectivity" << finl;
  if(Process::nproc() > 1)
    {
// what we're doing here is not equivalent to construire_connectivite_som_elem with virtual elements set to 1
// in the latter, we also build the connectivity for virtual nodes
// here, we add the connectivity of real nodes only with virtual elements
// + we want som_elem to contain global numerotation for elements
      IntTab elem_virt_pe_num;
      zone.construire_elem_virt_pe_num(elem_virt_pe_num);
      construire_connectivite_real_som_virtual_elem(dom.nb_som(),
                                                    elem_som,
                                                    som_elem,
                                                    elem_virt_pe_num,
                                                    offsets);
    }
  else
    construire_connectivite_som_elem(dom.nb_som(),
                                     elem_som,
                                     som_elem,
                                     0 /* ne pas inclure les elements virtuels */);
  int nb_connexions_perio = 0;
  if (liste_bords_periodiques.size() > 0)
    {
      Cerr << " Construction of graph connectivity for periodic boundaries" << finl;
      nb_connexions_perio = Partitionneur_base::calculer_graphe_connexions_periodiques(dom.zone(0),
                                                                                       liste_bords_periodiques,
                                                                                       som_elem,
                                                                                       my_offset,
                                                                                       graph_elements_perio);
    }
// ****************************************************************
// PREMIERE ETAPE: calcul du nombre de vertex et edges du graph:
// Nombre total de faces de bord:
  const int nb_faces_bord = zone.nb_faces_frontiere();
// Chaque element du maillage est un "vertex" du graph.
// Les "edges" du graph relient chaque element a ses voisins par une face.
// Il y a autant d'edges que de faces ayant deux voisins, fois 2
// Formule classique: nb_faces internes = nnn/2 avec :
  int nnn = nb_elem * nb_faces_par_element - nb_faces_bord + nb_connexions_perio;
  if (sub_type(Poly_geom_base,zone.type_elem().valeur()))
    {
      const Poly_geom_base& poly=ref_cast(Poly_geom_base,zone.type_elem().valeur());
      nnn= poly.get_somme_nb_faces_elem() - nb_faces_bord + nb_connexions_perio;
    }
  const int nb_edges = nnn + nb_faces_bord;
  nvtxs = nb_elem + zone.nb_faces_joint(); //each joint face is linked to a virtual element
  xadj.resize_array(nb_elem+1);
  xadj = -1;
  adjncy.resize_array(nb_edges+nb_faces_bord);
  adjncy = -1;
  edgegsttab.resize_array(nb_edges+nb_faces_bord);
  edgegsttab = -1;
  vwgts.resize_array(0); //NULL
  if (! use_weights)
    {
      weightflag = 0;
      ewgts.resize_array(0); //NULL
    }
  else
    {
      weightflag = 1;
      ewgts.resize_array(nb_edges + nb_faces_bord);
    }
  vtxdist.resize_array(Process::nproc()+1);
  for(int p = 0; p < Process::nproc(); p++)
    vtxdist[p] = offsets[p];
  vtxdist[Process::nproc()] = Process::mp_sum(nb_elem);
  Cerr << " Construction of the elem_elem connectivity" << finl;
// ***************************************************************
// DEUXIEME ETAPE: remplissage du graph
// Algorithme: Pour chaque element, boucle sur les faces de l'element
// et on ajoute un "edge" entre l'element et ses voisins. On cherche
// l'element voisin par une face a l'aide de la fonction find_adjacent_elements.
//
// Deux tableaux de travail:
  ArrOfInt une_face(nb_sommets_par_face); //!< Les sommets de la face en cours
  ArrOfInt voisins; //!< Les elements voisins d'une_face
  voisins.set_smart_resize(1);
  int error = 0;
  int edge_count = 0;
  int i_elem;
  for (i_elem = 0; i_elem < nb_elem; i_elem++)
    {
      xadj[i_elem] = edge_count;
      int i_face;
      if (!is_regular)
        {
          ref_cast(Poly_geom_base,type_elem).get_tab_faces_sommets_locaux(faces_element_reference,i_elem);
          int nb_faces_elem       = faces_element_reference.dimension(0);
          while ( faces_element_reference(nb_faces_elem-1,0)==-1)
            nb_faces_elem--;
          nb_faces_par_element= nb_faces_elem;
        }
      for (i_face = 0; i_face < nb_faces_par_element; i_face++)
        {
// Construction de cette face de l'element:
// (indice des sommets de la face dans le domaine)
          {
            int i;
            for (i = 0; i < nb_sommets_par_face; i++)
              {
                const int i_som = faces_element_reference(i_face, i);
                if (i_som<0)
                  une_face[i] = i_som;
                else
                  {
                    const int sommet = elem_som(i_elem, i_som);
                    une_face[i] = sommet;
                  }
              }
          }
// Recherche des elements voisins de cette face:
// (indices des elements contenant les sommets de la face)
          find_adjacent_elements(som_elem, une_face, voisins);
          const int nb_voisins = voisins.size_array();
          int elem_voisin = -1;
          switch (nb_voisins)
            {
            case 0:
              {
// Aucun voisin: erreur interne
                error = 3;
                break;
              }
            case 1:
              {
// Un seul voisin, c'est une face frontiere
                const int elem = voisins[0];
                if (elem != i_elem + my_offset)
                  error = 3; //!< l'element i_elem n'est pas voisin: erreur interne
                else
                  elem_voisin = -1;
                break;
              }
            case 2:
              {
// Le cas le plus courant:
                const int elem0 = voisins[0];
                const int elem1 = voisins[1];
                if (elem0 == i_elem + my_offset) //neighbours contain global numerotation
                  elem_voisin = elem1;
                else if (elem1 == i_elem + my_offset)
                  elem_voisin = elem0;
                else
                  error = 3; //!< l'element i_elem n'est pas voisin: erreur interne
                break;
              }
            default:
              {
// Plus de deux voisins
                error = 2;
              }
            }
          if (error)
            break;
          if (elem_voisin >= 0)
            {
              if (edge_count >= nb_edges)
                {
                  error = 1;
                  break;
                }
              adjncy[edge_count] = elem_voisin;
              if (use_weights)
                {
// internal connection have more weight:
// it's better if the generated partition is not dispatched on several processors
                  if( my_offset <= elem_voisin && elem_voisin < nb_elem+my_offset) //neighbour belongs to me = strong connection
                    ewgts[edge_count] = 4;
                  else
                    ewgts[edge_count] = 1; //!< -1 peut faire des partitions discontinues ou pas equilibrees du tout
                }
              edge_count++;
            }
        }
// Ajout des connexions supplementaires pour les faces periodiques
      if (nb_connexions_perio > 0)
        {
          const int n = graph_elements_perio.get_list_size(i_elem);
          for (int i = 0; i < n; i++)
            {
              const int elem_voisin = graph_elements_perio(i_elem, i);
              if (edge_count >= nb_edges)
                {
                  error = 1;
                  break;
                }
              adjncy[edge_count] = elem_voisin;
// Les connexions entre faces periodiques sont fortes:
// on veut que ces elements soient sur le meme processeur
// Attention, si on met un poids nettement plus eleve que les autres
// edges, on degrade la qualite du decoupage !
              if (use_weights)
                {
                  ewgts[edge_count] = 4;
                }
              edge_count++;
            }
        }
      else if (use_weights)
        {
          if(Process::nproc() == 1)
            {
              Cerr << "Warning: You specify use_weights option with Metis but you didn't use Periodique keyword" << finl;
              Cerr << "to define the boundary where periodicity apply." << finl;
              Cerr << "Either suppress use_weight or add Periodique keyword." << finl;
              Process::exit();
            }
        }
      if (error > 0)
        break;
    }
  xadj[nb_elem] = edge_count;
  nedges = edge_count;
  std::map<int,int> global_to_local_index;
  int cnt=nb_elem;
  for(int e=0; e<nb_edges + nb_faces_bord; e++)
    {
      int vertex = adjncy[e];
      if( my_offset <= vertex && vertex < nb_elem+my_offset) //neighbour belongs to me
        {
          edgegsttab[e] = vertex - my_offset;
        }
      else
        {
          std::map<int,int>::iterator it = global_to_local_index.find(vertex);
          if(it != global_to_local_index.end())
            {
              edgegsttab[e] = global_to_local_index[vertex];
            }
          else
            {
              global_to_local_index[vertex] =cnt++;
              edgegsttab[e] = global_to_local_index[vertex];
            }
        }
    }
  if (error == 1)
    {
      Cerr << "Error in Domaine_Graph::construire_graph_elem_elem\n"
           << " The number of element-element connections is greater than expected\n"
           << " The number of boundary faces is wrong.\n"
           << " You must discretize the domain to check." << finl;
      Process::exit();
    }
  else if (error == 2)
    {
      Cerr << "Error in Domain_Graph::construire_graph_elem_elem\n"
           << " Problem in the mesh: one internal face has more than two neighboring elements\n"
           << " List of neighboring elements:" << voisins
           << "\n Nodes of the face:" << une_face;
      Process::exit();
    }
  else if (error)
    {
      Cerr << "Internal error in Domain_Graph::construire_graph_elem_elem\n"
           << " (error " << error << ") Problem in neighborhood algorithms"
           << finl;
      Process::exit();
    }
}
References adjncy, Partitionneur_base::calculer_graphe_connexions_periodiques(), Cerr, construire_connectivite_real_som_virtual_elem(), construire_connectivite_som_elem(), Zone::construire_elem_virt_pe_num(), TRUSTTab< _TYPE_ >::dimension(), edgegsttab, envoyer_all_to_all(), ewgts, Process::exit(), find_adjacent_elements(), finl, Static_Int_Lists::get_list_size(), Poly_geom_base::get_somme_nb_faces_elem(), Zone::les_elems(), Process::me(), Process::mp_sum(), mppartial_sum(), Zone::nb_elem(), Zone::nb_faces_frontiere(), Zone::nb_faces_joint(), Domaine::nb_som(), nedges, Process::nproc(), nvtxs, ref_cast, TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::set_smart_resize(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), sub_type, Zone::type_elem(), type_elem(), Deriv_Elem_geom_base::valeur(), vtxdist, vwgts, weightflag, xadj, and Domaine::zone().
Referenced by Partitionneur_Metis::construire_partition(), Partitionneur_Parmetis::construire_partition(), and Partitionneur_Ptscotch::construire_partition().
construire_graph_from_segment()
void Domain_Graph::construire_graph_from_segment (const Domaine & dom, const int use_weights)
< 2 liens par liaison
< mouif
< des liens peuvent etre doubles
Definition at line 95 of file Domain_Graph.cpp.
{
  const IntTab& liaisons = dom.zone(0).les_elems();
// ****************************************************************
// PREMIERE ETAPE: calcul du nombre de vertex et edges du graph:
  int nb_edges = liaisons.size_array(); //!< 2 liens par liaison
  int nb_elem=liaisons.local_max_vect()+1;  //!< mouif
  nvtxs = nb_elem;
  xadj.resize_array(nb_elem+1);
  vwgts.resize_array(0);
  if (! use_weights)
    {
      weightflag = 0;
      ewgts.resize_array(0);
    }
  else
    {
      abort();
      weightflag = 1;
      ewgts.resize_array(nb_edges);
    }
// on construit connectivite item item
  IntTab stencyl(0,2);
  stencyl.set_smart_resize(1);
  int size=0;
  int nbl=liaisons.dimension(0);
  for (int i=0; i<nbl; i++)
    {
      stencyl.resize(size+2,2);
      int n1=liaisons(i,0);
      int n2=liaisons(i,1);
      {
        stencyl(size,0)=n1;
        stencyl(size,1)=n2;
        size++;
        stencyl(size,0)=n2;
        stencyl(size,1)=n1;
        size++;
      }
    }
  tableau_trier_retirer_doublons(stencyl);
  Matrice_Morse A;
  Matrix_tools::allocate_morse_matrix(nb_elem,nb_elem,stencyl,A);
  nb_edges=A.get_tab2().size_array(); //!< des liens peuvent etre doubles
  nedges = nb_edges;
  adjncy.resize_array(nb_edges);
//
  assert(A.get_tab1().size_array()==nvtxs+1);
  for (int c=0; c<nvtxs+1; c++)
    {
      xadj[c]=A.get_tab1()(c)-1;
    }
  for (int c=0; c<nedges; c++)
    {
      adjncy[c]=A.get_tab2()(c)-1;
    }
}
References adjncy, Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::dimension(), ewgts, Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Zone::les_elems(), TRUSTVect< _TYPE_ >::local_max_vect(), nedges, nvtxs, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), tableau_trier_retirer_doublons(), vwgts, weightflag, xadj, and Domaine::zone().
Referenced by Partitionneur_Metis::construire_partition().
Friends And Related Function Documentation
Partitionneur_Metis
friend class Partitionneur_Metis friend
Definition at line 24 of file Domain_Graph.h.
Partitionneur_Parmetis
friend class Partitionneur_Parmetis friend
Definition at line 25 of file Domain_Graph.h.
Partitionneur_Ptscotch
friend class Partitionneur_Ptscotch friend
Definition at line 26 of file Domain_Graph.h.
Member Data Documentation
adjncy
ArrOfInt Domain_Graph::adjncy private
Definition at line 45 of file Domain_Graph.h.
Referenced by construire_graph_elem_elem(), construire_graph_from_segment(), Partitionneur_Metis::construire_partition(), Partitionneur_Parmetis::construire_partition(), and Partitionneur_Ptscotch::construire_partition().
edgegsttab
ArrOfInt Domain_Graph::edgegsttab private
Definition at line 49 of file Domain_Graph.h.
Referenced by construire_graph_elem_elem(), and Partitionneur_Ptscotch::construire_partition().
ewgts
ArrOfInt Domain_Graph::ewgts private
Definition at line 47 of file Domain_Graph.h.
Referenced by construire_graph_elem_elem(), construire_graph_from_segment(), Partitionneur_Metis::construire_partition(), Partitionneur_Parmetis::construire_partition(), and Partitionneur_Ptscotch::construire_partition().
nedges
int Domain_Graph::nedges private
Definition at line 42 of file Domain_Graph.h.
Referenced by construire_graph_elem_elem(), and construire_graph_from_segment().
nvtxs
int Domain_Graph::nvtxs private
Definition at line 41 of file Domain_Graph.h.
Referenced by construire_graph_elem_elem(), construire_graph_from_segment(), Partitionneur_Metis::construire_partition(), and Partitionneur_Parmetis::construire_partition().
vtxdist
ArrOfInt Domain_Graph::vtxdist private
Definition at line 48 of file Domain_Graph.h.
Referenced by construire_graph_elem_elem(), and Partitionneur_Parmetis::construire_partition().
vwgts
ArrOfInt Domain_Graph::vwgts private
Definition at line 46 of file Domain_Graph.h.
Referenced by construire_graph_elem_elem(), construire_graph_from_segment(), Partitionneur_Metis::construire_partition(), and Partitionneur_Parmetis::construire_partition().
weightflag
int Domain_Graph::weightflag private
Definition at line 43 of file Domain_Graph.h.
Referenced by construire_graph_elem_elem(), construire_graph_from_segment(), and Partitionneur_Parmetis::construire_partition().
xadj
ArrOfInt Domain_Graph::xadj private
Definition at line 44 of file Domain_Graph.h.
Referenced by construire_graph_elem_elem(), construire_graph_from_segment(), Partitionneur_Metis::construire_partition(), Partitionneur_Parmetis::construire_partition(), and Partitionneur_Ptscotch::construire_partition().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Decoupeur/Domain_Graph.h
src/Kernel/Geometrie/Decoupeur/Domain_Graph.cpp