TRUST: Deriv_Mod_turb_hyd_base Class Reference
Deriv_Mod_turb_hyd_base Class Reference
#include <Mod_turb_hyd.h>
Public Member Functions
~Deriv_Mod_turb_hyd_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Mod_turb_hyd_base ()
Deriv_Mod_turb_hyd_base (const Deriv_Mod_turb_hyd_base &)
const Mod_turb_hyd_base & valeur () const
Mod_turb_hyd_base & valeur ()
const Mod_turb_hyd_base * operator-> () const
Mod_turb_hyd_base * operator-> ()
const Deriv_Mod_turb_hyd_base & operator= (const Mod_turb_hyd_base &)
const Deriv_Mod_turb_hyd_base & operator= (const Deriv_Mod_turb_hyd_base &)
operator const Mod_turb_hyd_base & () const
operator Mod_turb_hyd_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Mod_turb_hyd_base & self_cast (Objet_U &)
static const
Deriv_Mod_turb_hyd_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Mod_turb_hyd_base * pointeur_
Detailed Description
Definition at line 29 of file Mod_turb_hyd.h.
Constructor & Destructor Documentation
Deriv_Mod_turb_hyd_base::~Deriv_Mod_turb_hyd_base ()
Definition at line 28 of file Mod_turb_hyd.cpp.
Deriv_Mod_turb_hyd_base::Deriv_Mod_turb_hyd_base ()
Definition at line 28 of file Mod_turb_hyd.cpp.
Deriv_Mod_turb_hyd_base::Deriv_Mod_turb_hyd_base (const Deriv_Mod_turb_hyd_base & t)
Definition at line 28 of file Mod_turb_hyd.cpp.
Member Function Documentation
Objet_U * Deriv_Mod_turb_hyd_base::cree_instance () [static]
Reimplemented in Mod_turb_hyd.
Definition at line 28 of file Mod_turb_hyd.cpp.
int Deriv_Mod_turb_hyd_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Mod_turb_hyd.
Definition at line 28 of file Mod_turb_hyd.cpp.
const Type_info * Deriv_Mod_turb_hyd_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Mod_turb_hyd.
Definition at line 28 of file Mod_turb_hyd.cpp.
const Type_info & Deriv_Mod_turb_hyd_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 28 of file Mod_turb_hyd.cpp.
const Type_info * Deriv_Mod_turb_hyd_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Mod_turb_hyd.
Definition at line 28 of file Mod_turb_hyd.cpp.
Deriv_Mod_turb_hyd_base::operator const Mod_turb_hyd_base & () const
Definition at line 28 of file Mod_turb_hyd.cpp.
Deriv_Mod_turb_hyd_base::operator Mod_turb_hyd_base & ()
Definition at line 28 of file Mod_turb_hyd.cpp.
const Mod_turb_hyd_base * Deriv_Mod_turb_hyd_base::operator-> () const [inline]
Definition at line 29 of file Mod_turb_hyd.h.
: public MorEqn , public DERIV(Mod_turb_hyd_base)
Mod_turb_hyd_base * Deriv_Mod_turb_hyd_base::operator-> () [inline]
Definition at line 29 of file Mod_turb_hyd.h.
: public MorEqn , public DERIV(Mod_turb_hyd_base)
const Deriv_Mod_turb_hyd_base & Deriv_Mod_turb_hyd_base::operator= (const Deriv_Mod_turb_hyd_base & t)
Definition at line 28 of file Mod_turb_hyd.cpp.
const Deriv_Mod_turb_hyd_base & Deriv_Mod_turb_hyd_base::operator= (const Mod_turb_hyd_base & t)
Reimplemented in Mod_turb_hyd.
Definition at line 28 of file Mod_turb_hyd.cpp.
Sortie & Deriv_Mod_turb_hyd_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Mod_turb_hyd.
Definition at line 28 of file Mod_turb_hyd.cpp.
Entree & Deriv_Mod_turb_hyd_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Mod_turb_hyd.
Definition at line 28 of file Mod_turb_hyd.cpp.
const Deriv_Mod_turb_hyd_base & Deriv_Mod_turb_hyd_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Mod_turb_hyd.
Definition at line 28 of file Mod_turb_hyd.cpp.
Deriv_Mod_turb_hyd_base & Deriv_Mod_turb_hyd_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Mod_turb_hyd.
Definition at line 28 of file Mod_turb_hyd.cpp.
void Deriv_Mod_turb_hyd_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 28 of file Mod_turb_hyd.cpp.
unsigned Deriv_Mod_turb_hyd_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Mod_turb_hyd.
Definition at line 28 of file Mod_turb_hyd.cpp.
const Mod_turb_hyd_base & Deriv_Mod_turb_hyd_base::valeur () const [inline]
Definition at line 29 of file Mod_turb_hyd.h.
Referenced by Mod_turb_hyd::completer(), Mod_turb_hyd::discretiser(), Mod_turb_hyd::imprimer(), Mod_turb_hyd::loi_paroi(), Mod_turb_hyd::mettre_a_jour(), Mod_turb_hyd::preparer_calcul(), Mod_turb_hyd::readOn(), Mod_turb_hyd::reprendre(), Mod_turb_hyd::sauvegarder(), and Mod_turb_hyd::viscosite_turbulente().
: public MorEqn , public DERIV(Mod_turb_hyd_base)
Mod_turb_hyd_base & Deriv_Mod_turb_hyd_base::valeur () [inline]
Definition at line 29 of file Mod_turb_hyd.h.
: public MorEqn , public DERIV(Mod_turb_hyd_base)
Member Data Documentation
const Type_info Deriv_Mod_turb_hyd_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Mod_turb_hyd.
Definition at line 29 of file Mod_turb_hyd.h.
Mod_turb_hyd_base* Deriv_Mod_turb_hyd_base::pointeur_ [private]
Definition at line 29 of file Mod_turb_hyd.h.
The documentation for this class was generated from the following files:
src/ThHyd/Modele_turbulence_base/Mod_turb_hyd.h
src/ThHyd/Modele_turbulence_base/Mod_turb_hyd.cpp