TRUST: Comm_Group_MPI Class Reference
Comm_Group_MPI Class Reference
:
Classe Comm_Group_MPI, derivee de la classe abstraite Comm_Group.
Cette classe represente un groupe de communication qui repose sur MPI.
Construction de l'objet : voir init_group_trio() pour le groupe_TRUST
et init_group() pour les autres.
#include <Comm_Group_MPI.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Comm_Group_MPI ()
Constructeur par defaut. Il faut ensuite appeler init_group()
ou init_group_trio() pour finir la construction du groupe.
~Comm_Group_MPI () override
void abort () const override
appel a MPI_Abort et rend la main
void mp_collective_op (const double *x, double *resu, int n, Collective_Op op) const override
void mp_collective_op (const double *x, double *resu, const Collective_Op *op, int n) const override
void mp_collective_op (const int *x, int *resu, int n, Collective_Op op) const override
void mp_collective_op (const int *x, int *resu, const Collective_Op *op, int n) const override
void barrier (int tag) const override
Point de synchronisation de tous les processeurs du groupe (permet
de verifier que tout le monde est la...). Si check_enabled() est
non nul, on utilise le tag pour verifier que tous les processeurs
sont bien en train d'attendre le meme tag, sinon c'est une barriere
simple. Le tag doit verifier 0 <= tag < max_tag (soit 32).
void send_recv_start (const ArrOfInt &send_list, const ArrOfInt &send_size, const char *const *const send_buffers, const ArrOfInt &recv_list, const ArrOfInt &recv_size, char *const *const recv_buffers, TypeHint typehint=CHAR) const override
Demarre l'envoi et la reception des buffers.
Les buffers doivent rester valide jusqu'au retour de send_recv_finish().
Le graphe de communication et la taille des buffers doivent etre corrects !
send_list : liste des processeurs (numerotation sur groupe courant) a qui envoyer
send_size : taille en octets de chaque message
send_buffers : adresse des donnees a envoyer.
recv_... : idem pour les donnees en reception.
void send_recv_finish () const override
Attend que l'ensemble des communications lancees par send_recv_start
soient finie.
void send (int pe, const void *buffer, int size, int tag) const override
Envoi bloquant.
void recv (int pe, void *buffer, int size, int tag) const override
Reception bloquante.
void broadcast (void *buffer, int size, int pe_source) const override
void all_to_all (const void *src_buffer, void *dest_buffer, int data_size) const override
void init_group_trio ()
constructeur du groupe "tous"
Attention, ce constructeur ne doit etre appele qu'une seule fois.
Le groupe est associe a trio_u_world_
Si must_mpi_initialize_==0, on suppose que MPI_Init a deja ete appele.
Apres l'appel a init_group_trio, il faut enregistrer le groupe dans PE_Groups
Voir PE_Groups::initialize()
void free ()
void all_to_allv (const void *src_buffer, int *send_data_size, int *send_data_offset, void *dest_buffer, int *recv_data_size, int *recv_data_offset) const
void ptop_send_recv (const void *send_buf, int send_buf_size, int send_proc, void *recv_buf, int recv_buf_size, int recv_proc) const
void set_must_finalize (int flag)
MPI_Comm get_mpi_comm () const
Public Member Functions inherited from Comm_Group
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Comm_Group ()
~Comm_Group () override
Destructeur (pour l'instant, rien a faire)
virtual void abort () const =0
virtual void mp_collective_op (const double *x, double *resu, int n, Collective_Op op) const =0
virtual void mp_collective_op (const double *x, double *resu, const Collective_Op *op, int n) const =0
virtual void mp_collective_op (const int *x, int *resu, int n, Collective_Op op) const =0
virtual void mp_collective_op (const int *x, int *resu, const Collective_Op *op, int n) const =0
virtual void barrier (int tag) const =0
int get_new_tag () const
Cette fonction renvoie un nouveau tag de communication pour le groupe.
Effet de bord : incremente le membre group_communication_tag_.
int rank () const
Renvoie le rang du processeur local dans le groupe *this.
ou -1 si je ne suis pas dans le groupe.
int nproc () const
Renvoie le nombre de processeurs dans le groupe *this.
virtual void send_recv_start (const ArrOfInt &send_list, const ArrOfInt &send_size, const char *const *const send_buffers, const ArrOfInt &recv_list, const ArrOfInt &recv_size, char *const *const recv_buffers, TypeHint typehint=CHAR) const =0
virtual void send_recv_finish () const =0
virtual void send (int pe, const void *buffer, int size, int tag) const =0
Envoi bloquant.
virtual void recv (int pe, void *buffer, int size, int tag) const =0
Reception bloquante.
virtual void broadcast (void *buffer, int size, int pe_source) const =0
virtual void all_to_all (const void *src_buffer, void *dest_buffer, int data_size) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Comm_Group_MPI & self_cast (Objet_U &)
static const Comm_Group_MPI & self_cast (const Objet_U &)
static void set_trio_u_world (MPI_Comm world)
pour que trio_u n'utilise qu'une partie des processeurs
de MPI_COMM_WORLD, il faut donner un communicateur a utiliser avant
d'appeler init_group_trio.
static MPI_Comm get_trio_u_world ()
static void set_must_mpi_initialize (int flag)
Static Public Member Functions inherited from Comm_Group
static const Type_info * info ()
static Comm_Group & self_cast (Objet_U &)
static const Comm_Group & self_cast (const Objet_U &)
static int check_enabled ()
static void set_check_enabled (int flag)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Comm_Group
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void init_group (const ArrOfInt &pe_list) override
Construction du groupe de processeurs a partir de la liste.
Voir Comm_Group::init_group(const ArrOfInt &)
Methode appelee par PE_Groups::create_group()
void internal_collective (const int *x, int *resu, int nx, const Collective_Op *op, int nop, int level) const
void internal_collective (const double *x, double *resu, int nx, const Collective_Op *op, int nop, int level) const
int mppartial_sum (int x) const
Renvoie la somme des x sur les processeurs precedents du groupe (moi non
compris). Le resultat sur le premier processeur du groupe est donc toujours 0.
Le resultat depend de l'ordre dans lequel les processeurs ont ete
fournis dans le constructeur.
Protected Member Functions inherited from Comm_Group
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Comm_Group (const Comm_Group &)
interdit !
const Comm_Group & operator= (const Comm_Group &)
interdit !
virtual void init_group (const ArrOfInt &pe_list)
Cette fonction doit etre appelee simultanement
par tous les PEs du groupe current_group avec les memes parametres.
Les processeurs de la pe_list sont les rangs dans current_group() des
processeurs du nouveau groupe. Le maitre du groupe est le premier de la liste,
le rang du processeur courant, s'il est dans le groupe est determine par
son rang dans la liste. Il ne doit pas y avoir de doublon.
Cette fonction est appelee par les methodes init_group des classes derivees.
void init_group_trio (int nproc, int rank)
Initialise le groupe_TRUST().
Cette methode est appelee par init_group_trio() des classes derivees.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
MPI_Group mpi_group_
Handle sur le groupe mpi.
MPI_Comm mpi_comm_
Handle sur le communicateur mpi.
int must_finalize_
Faut-il le faire dans le destructeur ?
Ref_Comm_Group groupe_pere_
Static Private Attributes
static int must_mpi_initialize_ = 1
static MPI_Comm trio_u_world_ = MPI_COMM_WORLD
static MPI_Status * mpi_status_ = 0
static MPI_Request * mpi_requests_ = 0
static int mpi_nrequests_ = -1
static int mpi_maxrequests_ = -1
static int current_msg_size_
La taille des donnees envoyees/recues pour le send_recv_start courant.
Additional Inherited Members
Public Types inherited from Comm_Group
enum Collective_Op { COLL_SUM , COLL_MIN , COLL_MAX , COLL_PARTIAL_SUM }
enum TypeHint { CHAR , INT , DOUBLE }
Detailed Description
:
Classe Comm_Group_MPI, derivee de la classe abstraite Comm_Group.
Cette classe represente un groupe de communication qui repose sur MPI.
Construction de l'objet : voir init_group_trio() pour le groupe_TRUST
et init_group() pour les autres.
Definition at line 34 of file Comm_Group_MPI.h.
Constructor & Destructor Documentation
Comm_Group_MPI()
Comm_Group_MPI::Comm_Group_MPI ()
Constructeur par defaut. Il faut ensuite appeler init_group()
ou init_group_trio() pour finir la construction du groupe.
Definition at line 92 of file Comm_Group_MPI.cpp.
{
#ifdef MPI_
// -1 indique que le groupe n'a pas ete initialise
  must_finalize_ = -1;
  mpi_comm_=MPI_COMM_NULL;
  mpi_group_=MPI_GROUP_NULL;
#endif
}
References mpi_comm_, mpi_group_, and must_finalize_.
~Comm_Group_MPI()
Comm_Group_MPI::~Comm_Group_MPI () override
< on detruit les groupes non prinicpaux
Definition at line 102 of file Comm_Group_MPI.cpp.
{
#ifdef MPI_
// Si groupe non initialise, ne rien faire:
// Modif par BM (20/08/2012): ne detruire ces membres statiques que si c'est le groupe principal (fin de l'execution)
  if ((mpi_comm_!=MPI_COMM_NULL) && (mpi_comm_ == trio_u_world_))
    {
      delete [] mpi_status_;
      mpi_status_=0;
      for (int r=0; r<mpi_maxrequests_; r++)
        {
          if(mpi_requests_[r]!=MPI_REQUEST_NULL)
            {
              MPI_Request_free(&(mpi_requests_[r]));
            }
        }
      delete [] mpi_requests_;
      mpi_requests_=0;
    }
  else //!< on detruit les groupes non prinicpaux
    {
      if (mpi_comm_!=MPI_COMM_NULL)
        {
// on detruit le group puis le mpi_comm
          mpi_error(MPI_Comm_free(&mpi_comm_));
          assert(mpi_comm_==MPI_COMM_NULL);
        }
      if (mpi_group_!=MPI_GROUP_NULL)
        {
          mpi_error(MPI_Group_free( &mpi_group_));
          assert(mpi_group_==MPI_GROUP_NULL);
        }
    }
#endif
}
References mpi_comm_, mpi_error(), mpi_group_, mpi_maxrequests_, mpi_requests_, mpi_status_, and trio_u_world_.
Member Function Documentation
abort()
void Comm_Group_MPI::abort () const override virtual
appel a MPI_Abort et rend la main
Implements Comm_Group.
Definition at line 144 of file Comm_Group_MPI.cpp.
{
#ifdef MPI_
  MPI_Abort(trio_u_world_,-1);
#endif
}
References trio_u_world_.
all_to_all()
void Comm_Group_MPI::all_to_all (const void * src_buffer, void * dest_buffer, int data_size) const override virtual
< Cast a cause de l'interface de MPI_Alltoall
Implements Comm_Group.
Definition at line 434 of file Comm_Group_MPI.cpp.
{
#ifdef MPI_
  statistiques().begin_count(mpi_alltoall_counter_);
  assert(src_buffer != dest_buffer);
  void * ptr = (void *) src_buffer; //!< Cast a cause de l'interface de MPI_Alltoall
  mpi_error(MPI_Alltoall(ptr, data_size, MPI_CHAR, dest_buffer, data_size, MPI_CHAR, mpi_comm_));
  statistiques().end_count(mpi_alltoall_counter_, data_size);
#endif
}
References Statistiques::begin_count(), Statistiques::end_count(), mpi_alltoall_counter_, mpi_comm_, mpi_error(), and statistiques().
all_to_allv()
void Comm_Group_MPI::all_to_allv (const void * src_buffer, int * send_data_size, int * send_data_offset, void * dest_buffer, int * recv_data_size, int * recv_data_offset) const
< Cast a cause de l'interface de MPI_Alltoall
Definition at line 528 of file Comm_Group_MPI.cpp.
{
  statistiques().begin_count(mpi_alltoall_counter_);
  assert(src_buffer != dest_buffer);
  void * ptr = (void *) src_buffer; //!< Cast a cause de l'interface de MPI_Alltoall
  const int n = nproc();
  int size;
#ifdef INT_is_64_
  std::vector<True_int> send_data_size_int(n);
  std::vector<True_int> send_data_offset_int(n);
  std::vector<True_int> recv_data_size_int(n);
  std::vector<True_int> recv_data_offset_int(n);
  auto cast_func = [](int i) -> True_int { return static_cast<True_int>(i); };
  std::transform(send_data_size,   send_data_size + n,   send_data_size_int.begin(),   cast_func);
  std::transform(send_data_offset, send_data_offset + n, send_data_offset_int.begin(), cast_func);
  std::transform(recv_data_size,   recv_data_size + n,   recv_data_size_int.begin(),   cast_func);
  std::transform(recv_data_offset, recv_data_offset + n, recv_data_offset_int.begin(), cast_func);
  mpi_error(MPI_Alltoallv(ptr, send_data_size_int.data(), send_data_offset_int.data(), MPI_CHAR,
                          dest_buffer, recv_data_size_int.data(), recv_data_offset_int.data(), MPI_CHAR, mpi_comm_));
  size = send_data_offset_int[n-1] + send_data_size_int[n-1] + recv_data_size_int[n-1] + recv_data_offset_int[n-1];
#else
  mpi_error(MPI_Alltoallv(ptr, send_data_size, send_data_offset, MPI_CHAR,
                          dest_buffer, recv_data_size, recv_data_offset, MPI_CHAR, mpi_comm_));
  size = send_data_offset[n-1] + send_data_size[n-1] + recv_data_size[n-1] + recv_data_offset[n-1];
#endif
  statistiques().end_count(mpi_alltoall_counter_, size);
}
References Statistiques::begin_count(), Statistiques::end_count(), mpi_alltoall_counter_, mpi_comm_, mpi_error(), Comm_Group::nproc(), and statistiques().
barrier()
void Comm_Group_MPI::barrier (int tag) const override virtual
Point de synchronisation de tous les processeurs du groupe (permet
de verifier que tout le monde est la...). Si check_enabled() est
non nul, on utilise le tag pour verifier que tous les processeurs
sont bien en train d'attendre le meme tag, sinon c'est une barriere
simple. Le tag doit verifier 0 <= tag < max_tag (soit 32).
Implements Comm_Group.
Definition at line 239 of file Comm_Group_MPI.cpp.
{
#ifdef MPI_
  static const int max_tag = 32;
  statistiques().begin_count(mpi_barrier_counter_);
  assert(tag >= 0 && tag < max_tag);
  if (check_enabled())
    {
// On fait la barriere avec des mpmin et mpmax pour verifier
// que le tag est le meme sur tous les processeurs :
// ATTENTION : il faut "int" et pas "entier" !!!
      int tag_complet = get_new_tag() * max_tag + tag;
      int min_tag, amax_tag;
      mpi_error(MPI_Allreduce(& tag_complet, & min_tag, 1, MPI_ENTIER, MPI_MIN, mpi_comm_));
      mpi_error(MPI_Allreduce(& tag_complet, & amax_tag, 1, MPI_ENTIER, MPI_MAX, mpi_comm_));
      if (min_tag != tag_complet || amax_tag != tag_complet)
        {
          Cerr << "Error in Comm_Group_MPI::barrier(int tag)\n";
          Cerr << " the tag is not identical on all the processes.\n";
          Cerr << " (Loss of communications synchronisation)." << finl;
          Process::Journal() << "Comm_Group_MPI::barrier\n Error : tag = " << tag << finl;
          assert(0);
          exit();
        }
    }
  else
    {
// Barriere simple sans le tag :
      mpi_error(MPI_Barrier(mpi_comm_));
    }
  statistiques().end_count(mpi_barrier_counter_);
#endif
}
References Statistiques::begin_count(), Cerr, Comm_Group::check_enabled(), Statistiques::end_count(), Process::exit(), finl, Comm_Group::get_new_tag(), Process::Journal(), mpi_barrier_counter_, mpi_comm_, MPI_ENTIER, mpi_error(), and statistiques().
broadcast()
void Comm_Group_MPI::broadcast (void * buffer, int size, int pe_source) const override virtual
Implements Comm_Group.
Definition at line 424 of file Comm_Group_MPI.cpp.
{
#ifdef MPI_
  statistiques().begin_count(mpi_bcast_counter_);
  assert(mpi_nrequests_ < 0);
  mpi_error(MPI_Bcast (buffer, size, MPI_CHAR, pe_source, mpi_comm_));
  statistiques().end_count(mpi_bcast_counter_, size);
#endif
}
References Statistiques::begin_count(), Statistiques::end_count(), mpi_bcast_counter_, mpi_comm_, mpi_error(), mpi_nrequests_, and statistiques().
cree_instance()
Objet_U * Comm_Group_MPI::cree_instance () static
Definition at line 26 of file Comm_Group_MPI.cpp.
duplique()
int Comm_Group_MPI::duplique () const override virtual
Implements Objet_U.
Definition at line 26 of file Comm_Group_MPI.cpp.
free()
void Comm_Group_MPI::free ()
< Group is created when mpi_maxrequests_>0 (avoid a crash with verifie_pere script)
Definition at line 521 of file Comm_Group_MPI.cpp.
{
  if (mpi_maxrequests_!=-1) //!< Group is created when mpi_maxrequests_>0 (avoid a crash with verifie_pere script)
    mpi_error(MPI_Group_free(& mpi_group_));
}
References mpi_error(), mpi_group_, and mpi_maxrequests_.
get_info()
const Type_info * Comm_Group_MPI::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Comm_Group.
Definition at line 26 of file Comm_Group_MPI.cpp.
get_mpi_comm()
MPI_Comm Comm_Group_MPI::get_mpi_comm () const inline
Definition at line 77 of file Comm_Group_MPI.h.
  {
    return mpi_comm_;
  };
References mpi_comm_.
get_trio_u_world()
MPI_Comm Comm_Group_MPI::get_trio_u_world () static
Definition at line 581 of file Comm_Group_MPI.cpp.
{
  return trio_u_world_;
}
References trio_u_world_.
Referenced by Partitionneur_Parmetis::construire_partition(), Partitionneur_Ptscotch::construire_partition(), and FichierHDFPar::prepare_file_props().
info()
const Type_info * Comm_Group_MPI::info () static
Definition at line 26 of file Comm_Group_MPI.cpp.
init_group()
void Comm_Group_MPI::init_group (const ArrOfInt & pe_list) override protected virtual
Construction du groupe de processeurs a partir de la liste.
Voir Comm_Group::init_group(const ArrOfInt &)
Methode appelee par PE_Groups::create_group()
Reimplemented from Comm_Group.
Definition at line 637 of file Comm_Group_MPI.cpp.
{
  must_finalize_ = 0;
// Le groupe "tous" doit exister
  assert(mpi_status_);
  Comm_Group::init_group(pe_list);
  const Comm_Group_MPI& cg = ref_cast(Comm_Group_MPI, PE_Groups::current_group());
// On stocke une reference au groupe pere : c'est le groupe courant au moment
// de l'appel a init_group. Le destructeur devra etre appele simultanement
// sur tous les processeurs du meme groupe.
  groupe_pere_ = PE_Groups::current_group();
// Construction du groupe MPI
  const MPI_Group& current_mpi_group = cg.mpi_group_;
  const MPI_Comm& current_mpi_comm  = cg.mpi_comm_;
// Copie de pe_list au cas ou int != int...
  const True_int nbproc = this->nproc();
  True_int *ranks = new True_int[nbproc];
  for (int i = 0; i < nbproc; i++)
    ranks[i] = pe_list[i];
  assert(mpi_group_==MPI_GROUP_NULL);
  mpi_error(MPI_Group_incl(current_mpi_group, nbproc, ranks, & mpi_group_));
  delete[] ranks;
// Construction du communicator
// MPI_Comm_create renvoie MPI_COMM_NULL si le processeur courant
// n'est pas dans le groupe.
  mpi_error(MPI_Comm_create(current_mpi_comm, mpi_group_, & mpi_comm_));
}
References PE_Groups::current_group(), groupe_pere_, Comm_Group::init_group(), mpi_comm_, mpi_error(), mpi_group_, mpi_status_, must_finalize_, Comm_Group::nproc(), and ref_cast.
init_group_trio()
void Comm_Group_MPI::init_group_trio ()
constructeur du groupe "tous"
Attention, ce constructeur ne doit etre appele qu'une seule fois.
Le groupe est associe a trio_u_world_
Si must_mpi_initialize_==0, on suppose que MPI_Init a deja ete appele.
Apres l'appel a init_group_trio, il faut enregistrer le groupe dans PE_Groups
Voir PE_Groups::initialize()
Definition at line 453 of file Comm_Group_MPI.cpp.
{
  must_finalize_ = 0;
  if (mpi_status_ != 0)
    {
      Cerr << "Error : the construction of the global Comm_Group_MPI has already been done." << finl;
      exit();
    }
  if (must_mpi_initialize_)
    {
      if (trio_u_world_ != MPI_COMM_WORLD)
        {
          Cerr << "Error in Comm_Group_MPI::init_group_trio(...) : you cannot ask to initialize MPI\n"
               << " with something else than MPI_COMM_WORLD !" << finl;
          exit();
        }
      must_finalize_ = 1;
      True_int argc=0;
      char** argv=NULL;
      int errcode = MPI_Init(&argc, &argv);
// int errcode = MPI_Init(0,0); Message d'erreur sur MPI Voltaire
      if (errcode != MPI_SUCCESS)
        {
          Cerr << "Error in Comm_Group_MPI::init_group_trio()\n"
               << " MPI_Init() failed (forget to run with mpirun ?)" << finl;
          mpi_error(errcode);
        }
    }
  True_int arank;
  True_int nbproc;
  mpi_error(MPI_Comm_size (trio_u_world_, & nbproc));
  mpi_error(MPI_Comm_rank (trio_u_world_, & arank));
  Comm_Group::init_group_trio(nbproc, arank);
  mpi_comm_ = trio_u_world_;
  MPI_Comm_group(mpi_comm_, &mpi_group_);
// Initialisation des variables statiques de la classe
// Un buffer a envoyer et un a recevoir par processeur
// d'ou le maximum...
  mpi_maxrequests_ = nbproc * 2;
  mpi_status_ = new MPI_Status[mpi_maxrequests_];
  mpi_requests_ = new MPI_Request[mpi_maxrequests_];
  for (int r=0; r<mpi_maxrequests_; r++)
    {
      mpi_requests_[r]=MPI_REQUEST_NULL;
    }
  if (arank == 0)
    {
      if (trio_u_world_ == MPI_COMM_WORLD)
        {
          Cerr << "Initialized MPI with MPI_COMM_WORLD (using all processors)" << finl;
        }
      else
        {
          Cerr << "Initialized MPI with communicator!=MPI_COMM_WORLD: using " << (int)nbproc << " processors" << finl;
        }
    }
}
References Cerr, Process::exit(), finl, Comm_Group::init_group_trio(), mpi_comm_, mpi_error(), mpi_group_, mpi_maxrequests_, mpi_requests_, mpi_status_, must_finalize_, must_mpi_initialize_, and trio_u_world_.
Referenced by init_parallel_mpi().
internal_collective() [1/2]
void Comm_Group_MPI::internal_collective (const double * x, double * resu, int nx, const Collective_Op * op, int nop, int level) const protected
Definition at line 680 of file Comm_Group_MPI.cpp.
{
// Pour l'instant algo bourrin, a optimiser...
  for (int i = 0; i < nx; i++)
    {
      int j = (nop < 0) ? 0 : i;
      if (op[j] != COLL_PARTIAL_SUM)
        mp_collective_op(x+i, resu+i, 1, op[j]);
      else
        {
          Cerr << "Error in Comm_Group_MPI: COLL_PARTIAL_SUM not coded for double" << finl;
          exit();
        }
    }
}
References Cerr, Comm_Group::COLL_PARTIAL_SUM, Process::exit(), finl, and mp_collective_op().
internal_collective() [2/2]
void Comm_Group_MPI::internal_collective (const int * x, int * resu, int nx, const Collective_Op * op, int nop, int level) const protected
Definition at line 667 of file Comm_Group_MPI.cpp.
{
// Pour l'instant algo bourrin, a optimiser...
  for (int i = 0; i < nx; i++)
    {
      int j = (nop < 0) ? 0 : i;
      if (op[j] != COLL_PARTIAL_SUM)
        mp_collective_op(x+i, resu+i, 1, op[j]);
      else
        resu[i] = mppartial_sum(x[i]);
    }
}
References Comm_Group::COLL_PARTIAL_SUM, mp_collective_op(), and mppartial_sum().
Referenced by mp_collective_op().
mp_collective_op() [1/4]
void Comm_Group_MPI::mp_collective_op (const double * x, double * resu, const Collective_Op * op, int n) const override virtual
Implements Comm_Group.
Definition at line 183 of file Comm_Group_MPI.cpp.
{
#ifdef MPI_
  if (n <= 0)
    return;
  internal_collective(x, resu, n, op, n /* n different operations */, 0 /* recursion level */);
#endif
}
References internal_collective().
mp_collective_op() [2/4]
void Comm_Group_MPI::mp_collective_op (const double * x, double * resu, int n, Collective_Op op) const override virtual
Implements Comm_Group.
Definition at line 151 of file Comm_Group_MPI.cpp.
{
#ifdef MPI_
  if (n <= 0)
    return;
  switch(op)
    {
// Note B.M.: cast en non const a cause de l'interface de MPI,
// plusieurs posts sur newsgroups incitent a penser que c'est ok
// (x ne sera jamais modifie par la librairie, sauf bug !)
    case COLL_SUM:
      statistiques().begin_count(mpi_sumdouble_counter_);
      mpi_error(MPI_Allreduce((int*) x, resu, n, MPI_DOUBLE, MPI_SUM, mpi_comm_));
      statistiques().end_count(mpi_sumdouble_counter_);
      break;
    case COLL_MIN:
      statistiques().begin_count(mpi_mindouble_counter_);
      mpi_error(MPI_Allreduce((int*) x, resu, n, MPI_DOUBLE, MPI_MIN, mpi_comm_));
      statistiques().end_count(mpi_mindouble_counter_);
      break;
    case COLL_MAX:
      statistiques().begin_count(mpi_maxdouble_counter_);
      mpi_error(MPI_Allreduce((int*) x, resu, n, MPI_DOUBLE, MPI_MAX, mpi_comm_));
      statistiques().end_count(mpi_maxdouble_counter_);
      break;
    case COLL_PARTIAL_SUM:
      internal_collective(x, resu, n, &op, -1 /* only one operation */, 0 /* recursion level */);
      break;
    }
#endif
}
References Statistiques::begin_count(), Comm_Group::COLL_MAX, Comm_Group::COLL_MIN, Comm_Group::COLL_PARTIAL_SUM, Comm_Group::COLL_SUM, Statistiques::end_count(), internal_collective(), mpi_comm_, mpi_error(), mpi_maxdouble_counter_, mpi_mindouble_counter_, mpi_sumdouble_counter_, and statistiques().
Referenced by internal_collective().
mp_collective_op() [3/4]
void Comm_Group_MPI::mp_collective_op (const int * x, int * resu, const Collective_Op * op, int n) const override virtual
Implements Comm_Group.
Definition at line 224 of file Comm_Group_MPI.cpp.
{
#ifdef MPI_
  if (n <= 0)
    return;
  internal_collective(x, resu, n, op, n /* n different operations */, 0 /* recursion level */);
#endif
}
References internal_collective().
mp_collective_op() [4/4]
void Comm_Group_MPI::mp_collective_op (const int * x, int * resu, int n, Collective_Op op) const override virtual
Implements Comm_Group.
Definition at line 192 of file Comm_Group_MPI.cpp.
{
#ifdef MPI_
  if (n <= 0)
    return;
  switch(op)
    {
// Note B.M.: cast en non const a cause de l'interface de MPI,
// plusieurs posts sur newsgroups incitent a penser que c'est ok
// (x ne sera jamais modifie par la librairie, sauf bug !)
    case COLL_SUM:
      statistiques().begin_count(mpi_sumint_counter_);
      mpi_error(MPI_Allreduce((int*) x, resu, n, MPI_ENTIER, MPI_SUM, mpi_comm_));
      statistiques().end_count(mpi_sumint_counter_);
      break;
    case COLL_MIN:
      statistiques().begin_count(mpi_minint_counter_);
      mpi_error(MPI_Allreduce((int*) x, resu, n, MPI_ENTIER, MPI_MIN, mpi_comm_));
      statistiques().end_count(mpi_minint_counter_);
      break;
    case COLL_MAX:
      statistiques().begin_count(mpi_maxint_counter_);
      mpi_error(MPI_Allreduce((int*) x, resu, n, MPI_ENTIER, MPI_MAX, mpi_comm_));
      statistiques().end_count(mpi_maxint_counter_);
      break;
    case COLL_PARTIAL_SUM:
      internal_collective(x, resu, n, &op, -1 /* only one operation */, 0 /* recursion level */);
      break;
    }
#endif
}
References Statistiques::begin_count(), Comm_Group::COLL_MAX, Comm_Group::COLL_MIN, Comm_Group::COLL_PARTIAL_SUM, Comm_Group::COLL_SUM, Statistiques::end_count(), internal_collective(), mpi_comm_, MPI_ENTIER, mpi_error(), mpi_maxint_counter_, mpi_minint_counter_, mpi_sumint_counter_, and statistiques().
mppartial_sum()
int Comm_Group_MPI::mppartial_sum (int x) const protected
Renvoie la somme des x sur les processeurs precedents du groupe (moi non
compris). Le resultat sur le premier processeur du groupe est donc toujours 0.
Le resultat depend de l'ordre dans lequel les processeurs ont ete
fournis dans le constructeur.
Definition at line 701 of file Comm_Group_MPI.cpp.
{
  statistiques().begin_count(mpi_partialsum_counter_);
// ATTENTION : il faut "int" et pas "entier" !!!
  int somme = 0;
  MPI_Status status;
  int tag = get_new_tag();
  int rang = rank();
  int np = nproc();
  if (rang > 0)
    {
// Recoit la somme partielle du precedent
      mpi_error(MPI_Recv(& somme, 1, MPI_ENTIER, rang-1, tag, mpi_comm_, &status));
    }
  if (rang+1 < np)
    {
// Envoie la somme partielle au suivant
// ATTENTION : il faut "int" et pas "entier" !!!
      int s = somme + x;
      mpi_error(MPI_Send(& s, 1, MPI_ENTIER, rang+1, tag, mpi_comm_));
    }
  statistiques().end_count(mpi_partialsum_counter_);
  return somme;
}
References Statistiques::begin_count(), Statistiques::end_count(), Comm_Group::get_new_tag(), mpi_comm_, MPI_ENTIER, mpi_error(), mpi_partialsum_counter_, Comm_Group::nproc(), Comm_Group::rank(), and statistiques().
Referenced by internal_collective().
printOn()
Sortie & Comm_Group_MPI::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Comm_Group.
Definition at line 78 of file Comm_Group_MPI.cpp.
{
  exit();
  return os;
}
References Process::exit().
ptop_send_recv()
void Comm_Group_MPI::ptop_send_recv (const void * send_buf, int send_buf_size, int send_proc, void * recv_buf, int recv_buf_size, int recv_proc) const
Definition at line 599 of file Comm_Group_MPI.cpp.
{
  statistiques().begin_count(mpi_sendrecv_counter_);
  assert(mpi_nrequests_ < 0);
  int dest = send_proc;
  int src = recv_proc;
  int tag = 1;
  MPI_Status status;
  if (send_proc < 0 && recv_proc < 0)
    {
// do nothing
    }
  else if (send_proc < 0 && recv_proc >= 0)
    {
      mpi_error(MPI_Recv (recv_buf, recv_buf_size, MPI_CHAR, src, tag, mpi_comm_, &status));
    }
  else if (recv_proc < 0 && send_proc >= 0)
    {
      mpi_error(MPI_Send ((void*)send_buf, send_buf_size, MPI_CHAR, dest, tag, mpi_comm_));
    }
  else
    {
      assert(dest >= 0 && dest < nproc());
      assert(src >= 0 && src < nproc());
// Probleme: oblige de faire un cast de (const void*) en (void*) a cause
// du prototype de MPI_Send
      mpi_error(MPI_Sendrecv((void*)send_buf, send_buf_size, MPI_CHAR, dest, tag,
                             recv_buf, recv_buf_size, MPI_CHAR, src, tag, mpi_comm_,
                             &status));
    }
  statistiques().end_count(mpi_sendrecv_counter_, send_buf_size + recv_buf_size);
}
References Statistiques::begin_count(), Statistiques::end_count(), mpi_comm_, mpi_error(), mpi_nrequests_, mpi_sendrecv_counter_, Comm_Group::nproc(), and statistiques().
readOn()
Entree & Comm_Group_MPI::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Comm_Group.
Definition at line 84 of file Comm_Group_MPI.cpp.
{
  exit();
  return is;
}
References Process::exit().
recv()
void Comm_Group_MPI::recv (int pe, void * buffer, int size, int tag) const override virtual
Reception bloquante.
Reception blocante d'un message.
Implements Comm_Group.
Definition at line 411 of file Comm_Group_MPI.cpp.
{
#ifdef MPI_
  statistiques().begin_count(mpi_recv_counter_);
  assert(mpi_nrequests_ < 0);
  MPI_Status status;
  int source = pe;
  assert(source >= 0 && source < nproc());
  mpi_error(MPI_Recv (buffer, size, MPI_CHAR, source, tag, mpi_comm_, & status));
  statistiques().end_count(mpi_recv_counter_, size);
#endif
}
References Statistiques::begin_count(), Statistiques::end_count(), mpi_comm_, mpi_error(), mpi_nrequests_, mpi_recv_counter_, Comm_Group::nproc(), and statistiques().
self_cast() [1/2]
const Comm_Group_MPI & Comm_Group_MPI::self_cast (const Objet_U & r) static
Definition at line 26 of file Comm_Group_MPI.cpp.
self_cast() [2/2]
Comm_Group_MPI & Comm_Group_MPI::self_cast (Objet_U & r) static
Definition at line 26 of file Comm_Group_MPI.cpp.
send()
void Comm_Group_MPI::send (int pe, const void * buffer, int size, int tag) const override virtual
Envoi bloquant.
Envoi blocant.
Pour etre bien certain que le code est safe, on force
une communication synchrone pour forcer le blocage en mode check (voir check_enabled()).
Sinon, on utilise MPI_Send qui est en general non blocant pour les petits messages<br>(donc de meilleures performances).
Implements Comm_Group.
Definition at line 392 of file Comm_Group_MPI.cpp.
{
#ifdef MPI_
  statistiques().begin_count(mpi_send_counter_);
  assert(mpi_nrequests_ < 0);
  int dest = pe;
  assert(dest >= 0 && dest < nproc());
// Probleme: oblige de faire un cast de (const void*) en (void*) a cause
// du prototype de MPI_Send
  if (check_enabled())
    mpi_error(MPI_Ssend ((void*)buffer, size, MPI_CHAR, dest, tag, mpi_comm_));
  else
    mpi_error(MPI_Send ((void*)buffer, size, MPI_CHAR, dest, tag, mpi_comm_));
  statistiques().end_count(mpi_send_counter_, size);
#endif
}
References Statistiques::begin_count(), Comm_Group::check_enabled(), Statistiques::end_count(), mpi_comm_, mpi_error(), mpi_nrequests_, mpi_send_counter_, Comm_Group::nproc(), and statistiques().
send_recv_finish()
void Comm_Group_MPI::send_recv_finish () const override virtual
Attend que l'ensemble des communications lancees par send_recv_start
soient finie.
Implements Comm_Group.
Definition at line 365 of file Comm_Group_MPI.cpp.
{
#ifdef MPI_
  assert(mpi_nrequests_ >= 0);
  mpi_error(MPI_Waitall(mpi_nrequests_, mpi_requests_, mpi_status_));
  statistiques().end_count(mpi_sendrecv_counter_, current_msg_size_, mpi_nrequests_);
  /*
  for (int r=0;r<mpi_nrequests_;r++)
    {
      if ( mpi_requests_[r]!=MPI_REQUEST_NULL)
  {
    MPI_Request_free(&(mpi_requests_[r]));
  }
      mpi_requests_[r]=MPI_REQUEST_NULL;
      }
  */
  mpi_nrequests_ = -1;
#endif
}
References current_msg_size_, Statistiques::end_count(), mpi_error(), mpi_nrequests_, mpi_requests_, mpi_sendrecv_counter_, mpi_status_, and statistiques().
send_recv_start()
void Comm_Group_MPI::send_recv_start (const ArrOfInt & send_list, const ArrOfInt & send_size, const char *const *const send_buffers, const ArrOfInt & recv_list, const ArrOfInt & recv_size, char *const *const recv_buffers, TypeHint typehint = CHAR) const override virtual
Demarre l'envoi et la reception des buffers.
Les buffers doivent rester valide jusqu'au retour de send_recv_finish().
Le graphe de communication et la taille des buffers doivent etre corrects !
send_list : liste des processeurs (numerotation sur groupe courant) a qui envoyer
send_size : taille en octets de chaque message
send_buffers : adresse des donnees a envoyer.
recv_... : idem pour les donnees en reception.
< Sinon il faut changer MPI_ENTIER !!!
Implements Comm_Group.
Definition at line 285 of file Comm_Group_MPI.cpp.
{
#ifdef MPI_
  statistiques().begin_count(mpi_sendrecv_counter_);
  assert(mpi_nrequests_ < 0);
  const int tag = get_new_tag();
  int i, n;
  mpi_nrequests_ = 0;
  int msg_size = 0;
  int divisor = 0;
  MPI_Datatype datatype = MPI_CHAR;
  assert(sizeof(int) == sizeof(int)); //!< Sinon il faut changer MPI_ENTIER !!!
  switch(typehint)
    {
    case CHAR:
      divisor = 1;
      break;
    case INT:
      divisor = sizeof(int);
      datatype = MPI_ENTIER;
      break;
    case DOUBLE:
      divisor = sizeof(double);
      datatype = MPI_DOUBLE;
      break;
    default:
      Process::exit();
    }
// Astuce pour maximiser les chances que ca marche : on declare
// la reception d'abord et l'envoi ensuite.
  n = recv_list.size_array();
  for (i = 0; i < n; i++)
    {
      int source = recv_list[i];
      int sz   = recv_size[i];
      msg_size += sz;
      assert(source >= 0 && source < nproc());
      assert(mpi_nrequests_ < mpi_maxrequests_);
      assert(sz % divisor == 0);
      assert(mpi_requests_[mpi_nrequests_]==MPI_REQUEST_NULL);
      mpi_error(MPI_Irecv(recv_buffers[i], sz / divisor,
                          datatype,
                          source, tag, mpi_comm_,
                          & mpi_requests_[mpi_nrequests_]));
      mpi_nrequests_++;
    }
  n = send_list.size_array();
  for (i = 0; i < n; i++)
    {
      int dest = send_list[i];
      int sz   = send_size[i];
      msg_size += sz;
      assert(dest >= 0 && dest < nproc());
      assert(mpi_nrequests_ < mpi_maxrequests_);
      assert(sz % divisor == 0);
      mpi_error(MPI_Isend((char*) send_buffers[i], sz / divisor,
                          datatype,
                          dest, tag, mpi_comm_,
                          & mpi_requests_[mpi_nrequests_]));
      mpi_nrequests_++;
    }
  current_msg_size_ = msg_size;
#endif
}
References Statistiques::begin_count(), Comm_Group::CHAR, current_msg_size_, Comm_Group::DOUBLE, Process::exit(), Comm_Group::get_new_tag(), Comm_Group::INT, mpi_comm_, MPI_ENTIER, mpi_error(), mpi_maxrequests_, mpi_nrequests_, mpi_requests_, mpi_sendrecv_counter_, Comm_Group::nproc(), TRUSTArray< _TYPE_ >::size_array(), and statistiques().
set_must_finalize()
void Comm_Group_MPI::set_must_finalize (int flag) inline
Definition at line 73 of file Comm_Group_MPI.h.
  {
    must_finalize_=flag;
  };
References must_finalize_.
set_must_mpi_initialize()
void Comm_Group_MPI::set_must_mpi_initialize (int flag) static
Definition at line 588 of file Comm_Group_MPI.cpp.
{
  if (mpi_status_ != 0)
    {
      Cerr << "Error : the construction of the global Comm_Group_MPI has already been done\n"
           << " set_must_mpi_initialize() call is forbidden." << finl;
      exit();
    }
  must_mpi_initialize_ = flag;
}
References Cerr, Process::exit(), finl, mpi_status_, and must_mpi_initialize_.
Referenced by mon_main::init_parallel(), and ICoCo::ProblemTrio::initialize().
set_trio_u_world()
void Comm_Group_MPI::set_trio_u_world (MPI_Comm world) static
pour que trio_u n'utilise qu'une partie des processeurs
de MPI_COMM_WORLD, il faut donner un communicateur a utiliser avant
d'appeler init_group_trio.
Definition at line 567 of file Comm_Group_MPI.cpp.
{
  if (mpi_status_ != 0)
    {
      Cerr << "Error : the construction of the global Comm_Group_MPI has already been done\n"
           << " set_trio_u_world call is forbidden" << finl;
      exit();
    }
#ifdef PETSCKSP_H
  PETSC_COMM_WORLD= world;
#endif
  trio_u_world_ = world;
}
References Cerr, Process::exit(), finl, mpi_status_, and trio_u_world_.
Referenced by ICoCo::ProblemTrio::initialize().
taille_memoire()
unsigned Comm_Group_MPI::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 26 of file Comm_Group_MPI.cpp.
Member Data Documentation
current_msg_size_
int Comm_Group_MPI::current_msg_size_ static private
La taille des donnees envoyees/recues pour le send_recv_start courant.
Definition at line 97 of file Comm_Group_MPI.h.
Referenced by send_recv_finish(), and send_recv_start().
groupe_pere_
Ref_Comm_Group Comm_Group_MPI::groupe_pere_ private
Definition at line 103 of file Comm_Group_MPI.h.
Referenced by init_group().
info_obj
const Type_info Comm_Group_MPI::info_obj static
Definition at line 36 of file Comm_Group_MPI.h.
mpi_comm_
MPI_Comm Comm_Group_MPI::mpi_comm_ private
Handle sur le communicateur mpi.
Definition at line 100 of file Comm_Group_MPI.h.
Referenced by all_to_all(), all_to_allv(), barrier(), broadcast(), Comm_Group_MPI(), get_mpi_comm(), init_group(), init_group_trio(), mp_collective_op(), mppartial_sum(), ptop_send_recv(), recv(), send(), send_recv_start(), and ~Comm_Group_MPI().
mpi_group_
MPI_Group Comm_Group_MPI::mpi_group_ private
Handle sur le groupe mpi.
Definition at line 99 of file Comm_Group_MPI.h.
Referenced by Comm_Group_MPI(), free(), init_group(), init_group_trio(), and ~Comm_Group_MPI().
mpi_maxrequests_
int Comm_Group_MPI::mpi_maxrequests_ = -1 static private
Definition at line 96 of file Comm_Group_MPI.h.
Referenced by free(), init_group_trio(), send_recv_start(), and ~Comm_Group_MPI().
mpi_nrequests_
int Comm_Group_MPI::mpi_nrequests_ = -1 static private
Definition at line 95 of file Comm_Group_MPI.h.
Referenced by broadcast(), ptop_send_recv(), recv(), send(), send_recv_finish(), and send_recv_start().
mpi_requests_
MPI_Request * Comm_Group_MPI::mpi_requests_ = 0 static private
Definition at line 94 of file Comm_Group_MPI.h.
Referenced by init_group_trio(), send_recv_finish(), send_recv_start(), and ~Comm_Group_MPI().
mpi_status_
MPI_Status * Comm_Group_MPI::mpi_status_ = 0 static private
Definition at line 93 of file Comm_Group_MPI.h.
Referenced by init_group(), init_group_trio(), send_recv_finish(), set_must_mpi_initialize(), set_trio_u_world(), and ~Comm_Group_MPI().
must_finalize_
int Comm_Group_MPI::must_finalize_ private
Faut-il le faire dans le destructeur ?
Definition at line 102 of file Comm_Group_MPI.h.
Referenced by Comm_Group_MPI(), init_group(), init_group_trio(), and set_must_finalize().
must_mpi_initialize_
int Comm_Group_MPI::must_mpi_initialize_ = 1 static private
Definition at line 89 of file Comm_Group_MPI.h.
Referenced by init_group_trio(), and set_must_mpi_initialize().
trio_u_world_
MPI_Comm Comm_Group_MPI::trio_u_world_ = MPI_COMM_WORLD static private
Definition at line 92 of file Comm_Group_MPI.h.
Referenced by abort(), get_trio_u_world(), init_group_trio(), set_trio_u_world(), and ~Comm_Group_MPI().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Comm_Group_MPI.h
src/Kernel/Utilitaires/Comm_Group_MPI.cpp