TRUST: Zone_VEF_PreP1b Class Reference
Zone_VEF_PreP1b Class Reference
#include <Zone_VEF_PreP1b.h>
Public Member Functions
Zone_VEF_PreP1b ()
~Zone_VEF_PreP1b ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretiser () override
Les volumes calcules dans discretiser() ne tiennent pas compte de
la periodicite. Pour les sommets periodiques, on fait la somme
de tous les volumes des sommets "identiques" au sens de la periodicite.
virtual void discretiser_suite (const VEFPreP1B &)
void modifier_pour_Cl (const Conds_lim &) override
int nb_som () const
int nb_elem () const
double volume_au_sommet (int som) const
const DoubleVect & volume_aux_sommets () const
int get_P1Bulle () const
int get_alphaE () const
int get_alphaS () const
int get_alphaA () const
int get_modif_div_face_dirichlet () const
int get_cl_pression_sommet_faible () const
const ArrOfInt & get_renum_arete_perio () const
const IntVect & get_ok_arete () const
const DoubleVect & get_volumes_aretes () const
void discretiser_arete ()
void construire_ok_arete ()
int lecture_ok_arete ()
void verifie_ok_arete (int) const
void construire_renum_arete_perio (const Conds_lim &)
int numero_premier_element () const
int numero_premier_sommet () const
int numero_premiere_arete () const
virtual void creer_tableau_p1bulle (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual const MD_Vector & md_vector_p1b () const
Public Member Functions inherited from Zone_VEF
Zone_VEF ()
~Zone_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretiser () override
Genere les faces
construits les frontieres.
void swap (int, int, int)
void reordonner (Faces &) override
Methode appelee par Zone_VF::discretiser apres la creation
des faces reelles.
On reordonne les faces de sorte a placer les faces "non standard"
au debut de la liste des faces. Les faces non standard sont celles
dont les volumes de controles sont modifies par les conditions aux
limites.
void modifier_pour_Cl (const Conds_lim &) override
void typer_elem (Zone &) override
const Elem_VEF & type_elem () const
int nb_elem_Cl () const
int nb_faces_joint () const
int nb_faces_std () const
int nb_elem_std () const
int premiere_face_std () const
int nb_faces_non_std () const
double carre_pas_du_maillage () const
double carre_pas_maille (int i) const
double face_normales (int, int) const override
DoubleTab & face_normales ()
const DoubleTab & face_normales () const
DoubleTab & facette_normales ()
const DoubleTab & facette_normales () const
IntVect & rang_elem_non_std ()
const IntVect & rang_elem_non_std () const
int oriente_normale (int face_opp, int elem2) const
DoubleTab & vecteur_face_facette ()
const ArrOfInt & ind_faces_virt_non_std () const
void calculer_volumes_entrelaces ()
void calculer_h_carre ()
Public Member Functions inherited from Zone_VF
Zone_VF ()
~Zone_VF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double face_normales (int, int) const =0
void calculer_face_surfaces (const DoubleVect &surfaces)
virtual const DoubleVect & face_surfaces () const
virtual double face_surfaces (int i) const
virtual double surface (int i) const
void discretiser () override
Genere les faces
construits les frontieres.
void infobord ()
void info_elem_som ()
void calculer_porosites ()
void calculer_diametres_hydrauliques ()
void calculer_sections_passage ()
void calculer_coefficient_echange_thermique ()
void calculer_coefficient_frottement ()
void marquer_faces_double_contrib (const Conds_lim &)
virtual void typer_elem (Zone &)
virtual void remplir_face_voisins_fictifs (const Zone_Cl_dis_base &)
virtual Faces * creer_faces ()
renvoie new(Faces) !
elle est surchargee par Zone_VDF par ex.
virtual void reordonner (Faces &)
cette methode ne fait rien
elle est surchargee par Zone_VDF par ex.
int nb_joints () const
renvoie le nombre de joints
int premiere_face_int () const
une face est interne ssi elle separe deux elements.
renvoie le numero de la premiere face interne.
int nb_faces () const
renvoie le nombre global de faces.
int nb_faces_tot () const
renvoie le nombre total de faces.
C'est-a-dire faces reelles + faces virtuelles
int nb_som_face () const
renvoie le nombre de sommets par face.
Rque : on a suppose que toutes les faces avait
le meme nombre de sommet ce qui exclue des elements
comme le prisme.
int nb_faces_bord () const
renvoie le nombre de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_bord_tot () const
renvoie le nombre total de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int premiere_face_bord () const
renvoie le numero de la premiere des faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_internes () const
une face est interne ssi elle separe deux elements.
renvoie le nombre de faces internes.
double xv (int, int) const
double xp (int, int) const
double xa (int, int) const
double porosite_face (int) const
double porosite_elem (int) const
double diametre_hydraulique_face (int) const
double section_passage_face (int) const
double coefficient_frottement (int) const
double coefficient_echange_thermique (int) const
int face_numero_bord (int num_face) const
IntTab & face_numero_bord ()
const IntTab & face_numero_bord () const
void remplir_face_numero_bord ()
virtual const IntVect & orientation () const
virtual int orientation (int) const
virtual int orientation_si_definie (int) const
DoubleTab normalized_boundaries_outward_vector (int global_face_number, double scale_factor) const
Compute the normalized boundary outward vector associated to the face global_face_number
and eventually scaled by scale_factor.
DoubleTab & xv ()
const DoubleTab & xv () const
DoubleTab & xp ()
const DoubleTab & xp () const
DoubleTab & xa ()
const DoubleTab & xa () const
DoubleVect & volumes_entrelaces ()
const DoubleVect & volumes_entrelaces () const
double volumes_entrelaces (int num_face) const
const DoubleTab & volumes_entrelaces_dir () const
DoubleTab & volumes_entrelaces_dir ()
DoubleVect & porosite_face ()
const DoubleVect & porosite_face () const
DoubleVect & porosite_elem ()
const DoubleVect & porosite_elem () const
DoubleVect & diametre_hydraulique_face ()
const DoubleVect & diametre_hydraulique_face () const
const DoubleVect section_passage_face () const
DoubleTab & diametre_hydraulique_elem ()
const DoubleTab & diametre_hydraulique_elem () const
DoubleVect & coefficient_frottement ()
const DoubleVect & coefficient_frottement () const
DoubleVect & coefficient_echange_thermique ()
const DoubleVect & coefficient_echange_thermique () const
const Joint & joint (int i) const
renvoie le ieme joint.
Joint & joint (int i)
renvoie le ieme joint.
Frontiere_dis_base & frontiere_dis (int) override
renvoie la ieme frontiere_discrete.
const Frontiere_dis_base & frontiere_dis (int) const override
renvoie la ieme frontiere_discrete.
int nb_frontiere_dis () const
const Front_VF & front_VF (int) const
renvoie la ieme frontiere_discrete.
double volumes (int i) const
renvoie le volume de la maille i.
double inverse_volumes (int i) const
int face_voisins (int num_face, int i) const
renvoie l'element voisin de numface dans la direction i.
i=0 : dans le sens oppose de l'axe orthogonal a la face numface.
i=1 : dans le sens de l'axe orthogonal a la face numface.
exemple :
| 0 | 1 |
numface
renvoie -1 si l'element n'existe pas (au bord).
int elem_faces (int i, int j) const
renvoie le numero de le ieme face de la maille num_elem
la facon dont ces faces sont numerotees est
laisse a la responsabilite des classes derivees
int face_sommets (int i, int j) const
renvoie le numero du ieme sommet de la face num_face.
DoubleVect & volumes ()
renvoie le tableaux des volumes des mailles.
DoubleVect & inverse_volumes ()
Tableau pour optimiser le code.
const DoubleVect & volumes () const
renvoie le tableaux des volumes des mailles.
const DoubleVect & inverse_volumes () const
Tableau pour optimiser le code.
IntTab & face_voisins () override
renvoie le tableaux des volumes des connectivites face elements
cf au dessus.
const IntTab & face_voisins () const override
cf au dessus.
const IntTab & face_voisins_fictifs () const
void face_voisins_reel_fictif (int face, int &el0, int &elf) const
renvoie dans el0 le numero de l'elt a l'interieur
renvoie dans elf le numero de l'elt fictif (-1 si il n'existe pas)
IntTab & elem_faces ()
renvoie le tableau de connectivite element/faces
const IntTab & elem_faces () const
cf au dessus.
ArrOfInt & faces_doubles ()
renvoie 1 pour les faces appartenant a un bord perio ou un item commun, 0 par defaut
const ArrOfInt & faces_doubles () const
cf au dessus
IntTab & face_sommets () override
renvoie le tableau de connectivite faces/sommets.
const IntTab & face_sommets () const override
cf au dessus.
void modifier_pour_Cl (const Conds_lim &) override
int numero_face_local (int face, int elem) const
int numero_sommet_local (int som, int elem) const
const IntTab & get_num_fac_loc () const
int get_num_fac_loc (int, int) const
void construire_num_fac_loc ()
const ArrOfInt & ind_faces_virt_bord () const
int est_une_face_virt_bord (int) const
renvoie 1 si face est une face virtuelle de bord, 0 sinon
int fbord (int f) const
void construire_face_virt_pe_num ()
Remplissage du tableau face_virt_pe_num_ (voir commentaire dans Zone_VF.h)
const IntTab & face_virt_pe_num () const
virtual void creer_tableau_faces (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_aretes (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_faces_bord (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual const MD_Vector & md_vector_faces_bord () const
virtual const MD_Vector & md_vector_faces () const
virtual const MD_Vector & md_vector_aretes () const
virtual const DoubleTab & xv_bord () const
Public Member Functions inherited from Zone_dis_base
Zone_dis_base ()
~Zone_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Associe une Zone a l'objet.
const Zone & zone () const
Renvoie la Zone associee a l'objet.
(version const)
Zone & zone ()
Renvoie la Zone associee a l'objet.
void associer_domaine_dis (const Domaine_dis &)
Associe un Domaine_dis a l'objet.
const Domaine_dis & domaine_dis () const
Domaine_dis & domaine_dis ()
virtual void discretiser ()=0
virtual void creer_elements_fictifs (const Zone_Cl_dis_base &)
virtual Frontiere_dis_base & frontiere_dis (int)=0
virtual const Frontiere_dis_base & frontiere_dis (int) const =0
int rang_frontiere (const Nom &)
int rang_frontiere (const Nom &) const
Renvoie le rang de la frontiere de Nom nom
Renvoie -1 si aucune frontiere ne s'appelle nom.
Frontiere_dis_base & frontiere_dis (const Nom &)
const Frontiere_dis_base & frontiere_dis (const Nom &) const
Renvoie la frontiere de Nom nom.
(On indexe les frontiere avec leur nom)
void ecrire_noms_bords (Sortie &) const
Ecriture des noms des bords sur un flot de sortie.
virtual void modifier_pour_Cl (const Conds_lim &)=0
virtual IntTab & face_sommets ()
virtual const IntTab & face_sommets () const
virtual IntTab & face_voisins ()
virtual const IntTab & face_voisins () const
int nb_elem () const
int nb_elem_tot () const
int nb_som () const
int nb_som_tot () const
int nb_front_Cl () const
virtual void init_dist_paroi_globale (const Conds_lim &conds_lim)
virtual const DoubleTab & y_elem () const
virtual const DoubleTab & y_faces () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_VEF_PreP1b & self_cast (Objet_U &)
static const Zone_VEF_PreP1b & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_VEF
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_VEF & self_cast (Objet_U &)
static const Zone_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_VF
static const Type_info * info ()
static Zone_VF & self_cast (Objet_U &)
static const Zone_VF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_dis_base
static const Type_info * info ()
static Zone_dis_base & self_cast (Objet_U &)
static const Zone_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Zone_VEF
static const Type_info info_obj
Static Public Attributes inherited from Zone_VF
static const Type_info info_obj
Static Public Attributes inherited from Zone_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Protected Member Functions inherited from Zone_VEF
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
virtual void remplir_elem_faces ()=0
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
DoubleVect volumes_som
DoubleVect volumes_aretes
ArrOfInt renum_arete_perio
IntVect ok_arete
int P1Bulle
int alphaE
int alphaS
int alphaA
int modif_div_face_dirichlet
int cl_pression_sommet_faible
determine si les cl de pression sont imposees de facon faible ou forte -> voir divergence et assembleur Descripteur pour les tableaux p1b (selon alphaE, alphaS et alphaA) (construit dans Zone_VEF_PreP1b::discretiser())
MD_Vector md_vector_p1b_
Protected Attributes inherited from Zone_VF
DoubleVect volumes_
volumes des elements
DoubleVect inverse_volumes_
inverse du volumes des elements
DoubleVect volumes_entrelaces_
volumes entrelaces pour l'integration des Qdm
DoubleTab volumes_entrelaces_dir_
volumes entrelaces par cote
DoubleVect porosite_elem_
Porosites volumiques pour les volumes de controle de masse.
DoubleVect porosite_face_
Porosites surfaciques en masse et volumiques.
DoubleVect diametre_hydraulique_face_
DoubleTab diametre_hydraulique_elem_
DoubleVect coefficient_echange_thermique_
remplissage des coefficients d'echange_thermique
DoubleVect coefficient_frottement_
remplissage des coefficient de frottement
IntTab face_voisins_
connectivite face/elements
IntTab face_voisins_fictifs_
connectivite face/elements fictifs
DoubleTab xp_
centres de gravite des elements
DoubleTab xv_
centres de gravite des faces
DoubleTab xv_bord_
IntTab elem_faces_
connectivite element/faces
IntTab face_sommets_
sommets des faces
DoubleTab xa_
centres de gravite des aretes
IntTab face_numero_bord_
connectivite face/numero_bord
MD_Vector md_vector_faces_
MD_Vector md_vector_faces_front_
MD_Vector md_vector_aretes_
Vect_Front_VF les_bords_
IntTab num_fac_loc_
ArrOfInt faces_doubles_
faces a double contribution (faces periodiques et items communs)
IntTab face_virt_pe_num_
Protected Attributes inherited from Zone_dis_base
Ref_Zone la_zone
Ref_Domaine_dis le_domaine_dis
DoubleTab y_elem_
DoubleTab y_faces_
int dist_paroi_initialisee_ = 0
Detailed Description
Definition at line 24 of file Zone_VEF_PreP1b.h.
Constructor & Destructor Documentation
Zone_VEF_PreP1b()
Zone_VEF_PreP1b::Zone_VEF_PreP1b ()
Definition at line 36 of file Zone_VEF_PreP1b.cpp.
:P1Bulle(-1), alphaE(-1), alphaS(-1), alphaA(-1), modif_div_face_dirichlet(-1),cl_pression_sommet_faible(-1) {}
~Zone_VEF_PreP1b()
Zone_VEF_PreP1b::~Zone_VEF_PreP1b ()
Definition at line 34 of file Zone_VEF_PreP1b.cpp.
Member Function Documentation
construire_ok_arete()
void Zone_VEF_PreP1b::construire_ok_arete ()
< lockee
< lockee
< libre
Definition at line 320 of file Zone_VEF_PreP1b.cpp.
{
  Cerr << "Build array ok_arete..." << finl;
  const Domaine& dom=zone().domaine();
  const IntTab& aretes_som=zone().aretes_som();
  const int nb_som_reel=nb_som();
// Connectivite sommets-aretes (pour chaque sommet, liste des aretes adjacentes)
// B.M.: je remplace IntTab(n, 64) par une Static_Int_List et je reutilise
// la methode de calcul des connectivites... plus econome en memoire !
// som_aretes contient une connectivite modifiee pour les sommets periodiques
// (les aretes sont toujours rattachees au sommet get_renum_som_perio(),
// les aretes periodiques opposees sont remplacees par une arete [nb_som_reel,nb_som_reel]
// fictive, et les sommets perio opposes ne sont rattaches a aucune arete)
  const int nb_aretes = aretes_som.dimension(0);
  Static_Int_Lists som_aretes;
  {
// Creation d'un tableau d'aretes ou les sommets sont remplaces par le sommet
// periodique associe et sans les aretes periodiques opposees
    IntTab aretes_som2;
    aretes_som2.copy(aretes_som, Array_base::NOCOPY_NOINIT);
    for (int i = 0; i < nb_aretes; i++)
      {
        if (renum_arete_perio[i] == i)
          {
            aretes_som2(i, 0) = dom.get_renum_som_perio(aretes_som(i,0));
            aretes_som2(i, 1) = dom.get_renum_som_perio(aretes_som(i,1));
          }
        else
          {
// arete periodique opposee, non conservee, on cree une arete fictive pour
// construire_connectivite_som_elem: le sommet d'indice nb_som_reel
// sera connecte a toutes les aretes periodiques supprimees
            aretes_som2(i, 0) = nb_som_reel;
            aretes_som2(i, 1) = nb_som_reel;
          }
      }
// On donne un sommet de plus (le sommet fictif connecte aux aretes supprimees)
    construire_connectivite_som_elem(nb_som_reel+1, aretes_som2, som_aretes, 0 /* do not include virtual items */);
  }
// Creation et initialisation du tableau contenu, initialise a zero par defaut
  ArrOfInt contenu(nb_som_reel);
// Initialisation pour le parallele: contenu est mis a 2
// pour les sommets communs recus d'un autre processeur
  {
    ArrOfBit flags;
    MD_Vector_tools::get_sequential_items_flags(dom.les_sommets().get_md_vector(), flags);
    for (int i = 0; i < nb_som_reel; i++)
      {
        if (!flags[i])
          {
// Ce sommet est recu d'un autre processeur
            const int i2 = dom.get_renum_som_perio(i);
            contenu[i] = 2;
            if (i2 != i)
              contenu[i2] = 2;
          }
      }
  }
// Estimation du nombre d'aretes superflues a trouver sur la zone
// en comptant les sommets reels non periodiques dont le contenu vaut 0
  int nombre_aretes_superflues_prevues_sur_la_zone=0;
  for (int i=0; i<nb_som_reel; i++)
    if (i==dom.get_renum_som_perio(i) && contenu[i]==0)
      nombre_aretes_superflues_prevues_sur_la_zone++;
  ok_arete = -1;
// On boucle tant qu'il y'a des sommets avec le contenu 0
  while (min_array(contenu)==0)
    {
// On cherche le premier sommet avec contenu 0 en bouclant sur les aretes
      int Aroot=-1,Sroot=-1;
      int S0,S1;
      do
        {
          while (ok_arete(++Aroot)==0) {};
          S0=dom.get_renum_som_perio(aretes_som(Aroot,0));
          S1=dom.get_renum_som_perio(aretes_som(Aroot,1));
        }
      while (Aroot<nb_aretes && contenu[S0]!=0 && contenu[S1]!=0);
      assert(Aroot<nb_aretes);
      Aroot=renum_arete_perio[Aroot];
      ok_arete(Aroot)=0; //!< lockee
      if (!contenu[S0])
        {
          contenu[S0]=1;
          Sroot=S0;
        }
      else if (!contenu[S1])
        {
          contenu[S1]=1;
          Sroot=S1;
        }
// Boucle sur les sommets
      do
        {
          const int nb_aretes_voisines = som_aretes.get_list_size(Sroot);
          for(int i=0; i<nb_aretes_voisines; i++)
            {
              int A=renum_arete_perio[som_aretes(Sroot,i)];
              if(ok_arete(A)==-1)
                {
                  int S=dom.get_renum_som_perio(aretes_som(A,0));
                  if(S==Sroot)
                    {
                      S=dom.get_renum_som_perio(aretes_som(A,1));
                    }
                  if(!contenu[S])
                    {
                      ok_arete(A)=0; //!< lockee
                      contenu[S]=1;
                    }
                  else
                    {
                      ok_arete(A)=1; //!< libre
                    }
                }
            }
          contenu[Sroot]=2;
        }
      while((Sroot=next(Sroot, contenu))!=-1);
// Correction pour des tableaux ok_arete et contenu pour la periodicite
      for(int i=0; i<nb_aretes; i++)
        ok_arete(i)=ok_arete[renum_arete_perio[i]];
      for(int i=0; i<nb_som_reel; i++)
        contenu[i]=contenu[dom.get_renum_som_perio(i)];
    }
// Mise a jour des parties virtuelles du tableau ok_arete
  ok_arete.echange_espace_virtuel();
// Verification des aretes superflues
  verifie_ok_arete(nombre_aretes_superflues_prevues_sur_la_zone);
// Ecriture des aretes superflues dans un fichier nom_du_cas.ok_arete afin de le relire la fois suivante
  Nom fichier(nom_du_cas());
  fichier+="_";
  fichier+=zone().domaine().le_nom()+".ok_arete";
  Cerr << "Writing file " << fichier << finl;
  EcrFicPartageBin fic_ok_arete_;
  if (!fic_ok_arete_.ouvrir(fichier,ios::out))
    {
      Cerr << "Error: cannot open file " << fichier << " for writing." << finl;
      exit();
    }
  ArrOfBit marqueurs_aretes;
  const MD_Vector& md_aretes = md_vector_aretes();
  MD_Vector_tools::get_sequential_items_flags(md_aretes, marqueurs_aretes);
  const int nb_aretes_seq = md_aretes.valeur().nb_items_seq_tot();
  if (Process::je_suis_maitre())
    fic_ok_arete_ << nb_aretes_seq << finl;
// Chaque processeur ecrit ses aretes non communes:
  const int n = marqueurs_aretes.size_array();
  for (int i = 0; i < n; i++)
    {
      if (marqueurs_aretes[i])
        fic_ok_arete_ << xa_(i,0) << space << xa_(i,1) << space << xa_(i,2) << space << ok_arete(i) << finl;
    }
  fic_ok_arete_.syncfile();
  fic_ok_arete_.close();
}
References Zone::aretes_som(), Cerr, EcrFicPartage::close(), construire_connectivite_som_elem(), TRUSTTab< _TYPE_ >::copy(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, Static_Int_Lists::get_list_size(), TRUSTVect< _TYPE_ >::get_md_vector(), Domaine::get_renum_som_perio(), MD_Vector_tools::get_sequential_items_flags(), Process::je_suis_maitre(), Domaine::le_nom(), Domaine::les_sommets(), Zone_VF::md_vector_aretes(), min_array(), MD_Vector_base::nb_items_seq_tot(), nb_som(), next(), Array_base::NOCOPY_NOINIT, Objet_U::nom_du_cas(), ok_arete, EcrFicPartage::ouvrir(), renum_arete_perio, ArrOfBit::size_array(), space, EcrFicPartage::syncfile(), MD_Vector::valeur(), verifie_ok_arete(), Zone_VF::xa_, and Zone_dis_base::zone().
Referenced by modifier_pour_Cl().
construire_renum_arete_perio()
void Zone_VEF_PreP1b::construire_renum_arete_perio (const Conds_lim & conds_lim)
Definition at line 496 of file Zone_VEF_PreP1b.cpp.
{
  Cerr << "Build array renum_arete_perio..." << finl;
  const IntTab& aretes_som=zone().aretes_som();
  const int nb_aretes_tot=zone().nb_aretes_tot();
  const Domaine& dom=zone().domaine();
// Initialisation de renum_arete_perio
  renum_arete_perio.resize_array(nb_aretes_tot);
  for (int i=0; i<nb_aretes_tot; i++)
    renum_arete_perio[i]=i;
  const IntTab& elem_aretes=zone().elem_aretes();
  ArrOfInt aretes1(6);
  ArrOfInt aretes2(6);
  int nb_cond_lim=conds_lim.size();
// Premiere etape: faire pointer tous les aretes periodiques liees entre elles vers la meme arete
  for (int num_cond_lim=0; num_cond_lim<nb_cond_lim; num_cond_lim++)
    {
// for cl
      const Cond_lim_base& cl = conds_lim[num_cond_lim].valeur();
      if (sub_type(Periodique, cl))
        {
// if Perio
          const Periodique& la_cl_perio = ref_cast(Periodique,cl);
          const Front_VF& le_bord = ref_cast(Front_VF,cl.frontiere_dis());
          int nf_bord_tot = le_bord.nb_faces_tot();
          IntVect fait(nf_bord_tot);
          fait = 0;
          for(int ind_face=0; ind_face<nf_bord_tot; ind_face++)
            if(!fait(ind_face))
              {
                int face=le_bord.num_face(ind_face);
                int ind_faassociee=la_cl_perio.face_associee(ind_face);
                int face_assciee=le_bord.num_face(ind_faassociee);
                fait(ind_faassociee)=fait(ind_face)=1;
                int elem1 = face_voisins_(face,0);
                int elem2 = face_voisins_(face,1);
                for(int j=0; j<6; j++)
                  {
                    aretes1[j]=elem_aretes(elem1,j);
                    aretes2[j]=elem_aretes(elem2,j);
                  }
                for(int j1=0; j1<6; j1++)
                  {
                    int ar1=aretes1[j1];
                    int& ar1_perio = renum_arete_perio[ar1];
// On verifie que l'arete appartient a la face (ok==2)
                    int som11=aretes_som(ar1, 0);
                    int som12=aretes_som(ar1, 1);
                    int ok=0;
                    int nbf = zone().type_elem().nb_som_face();
                    const IntTab& sommet = face_sommets();
                    for (int k=0; k<nbf; k++)
                      if (sommet(face,k)==som11 || sommet(face,k)==som12) ok++;
                    assert(ok>0);
                    if (ok==2)
                      {
                        int s11=dom.get_renum_som_perio(som11);
                        int s12=dom.get_renum_som_perio(som12);
                        for(int j2=0; j2<6; j2++)
{
                            int ar2=aretes2[j2];
                            int& ar2_perio = renum_arete_perio[ar2];
                            int som21=aretes_som(ar2, 0);
                            int som22=aretes_som(ar2, 1);
                            ok=0;
// On verifie que l'arete appartient a la face_assciee (ok==2)
                            for (int k=0; k<nbf; k++)
                              if (sommet(face_assciee,k)==som21 || sommet(face_assciee,k)==som22) ok++;
                            assert(ok>0);
                            if (ok==2)
{
                                int s21=dom.get_renum_som_perio(som21);
                                int s22=dom.get_renum_som_perio(som22);
                                assert(ar1!=ar2);
// Les aretes sont donc periodiques si on rentre dans le "if"
                                if ( ( (s21==s11)||(s22==s11) ) && ( (s22==s12)||(s21==s12) ) )
{
// Critere I : choix de l'arete perio en fonction d'un critere geometrique
                                    int dir_perio = la_cl_perio.direction_periodicite();
                                    int arete_perio = (xa(ar1_perio,dir_perio)<=xa(ar2_perio,dir_perio)) ? ar1_perio : ar2_perio;
                                    /*
                                    // Critere II : choix de l'arete perio en fonction des sommets periodiques
                                    int arete_perio;
                                    if (som11!=s11 && som12!=s12) // Les sommets de l'arete 1 sont periodiques
                                    arete_perio = ar2_perio;
                                    else if (som21!=s21 && som22!=s22) // Les sommets de l'arete 2 sont periodiques
                                    arete_perio = ar1_perio;
                                    else
{
                                    Cerr << "Cas non prevu." << finl;
                                    exit();
                                    } */
                                    ar2_perio = arete_perio;
                                    ar1_perio = arete_perio;
                                    volumes_aretes(ar2)+=volumes_aretes(ar1);
                                    volumes_aretes(ar1)+=volumes_aretes(ar2);
                                  }//fin du if sur "s21==s11"
                              }
                          }//fin du for sur "j2"
                      }
                  }//fin du if sur "renum_arete_perio(aretes1)" et du for sur "j1"
              }//fin du if sur "fait"
        }//fin if Perio
    }//!< fin for cl
// Deuxieme etape: faire pointer tous les aretes periodiques liees entre elles vers la meme arete
  for (int i = 0; i < nb_aretes_tot; i++)
    {
      int j = renum_arete_perio[i];
// Parcourir les aretes reliees pour cette chaine:
      while (j != renum_arete_perio[j])
        j = renum_arete_perio[j];
      renum_arete_perio[i] = j;
    }
  if (Debog::active())
    {
      IntVect tmp;
      creer_tableau_aretes(tmp, Array_base::NOCOPY_NOINIT);
      const int n = tmp.size_array();
      for (int i=0; i<n; i++)
        tmp[i] = renum_arete_perio[i];
      Debog::verifier_indices_items("renum_arete_perio",tmp.get_md_vector(),tmp);
    }
  /*
  // Verification complete du tableau renum_arete_perio
  // Chaque arete periodique a 2 sommets periodiques
  // si on utilise le critere II
  int ok=1;
  for (int i=0;i<nb_aretes_tot;i++)
  {
  int arete=renum_arete_perio(i);
  if (arete!=i)
  {
  assert(arete==renum_arete_perio(arete));
  // i est une arete periodique donc ses deux sommets doivent etre periodiques
  int S0=aretes_som(i,0);
  int S1=aretes_som(i,1);
  int som0=dom.get_renum_som_perio(S0);
  int som1=dom.get_renum_som_perio(S1);
  if (S0==som0 || S1==som1)
  {
  Cerr << "[" << Process::me() << "] Probleme avec l'arete periodique " << i << " qui pointe sur l'arete " << arete << " car" << finl;
  if (S0==som0) Cerr << "son sommet " << S0 << " n'est pas periodique." << finl;
  if (S1==som1) Cerr << "son sommet " << S1 << " n'est pas periodique." << finl;
  ok=0;
  }
  else
  {
  S0=dom.get_renum_som_perio(aretes_som(arete,0));
  S1=dom.get_renum_som_perio(aretes_som(arete,1));
  if ( (S0!=som0 && S0!=som1) || (S1!=som0 && S1!=som1) )
  {
  Cerr << "[" << Process::me() << "] Probleme avec l'arete periodique " << i << " car il n'y a pas coherence avec les sommets periodiques." << finl;
  ok=0;
  }
  }
  }
  }
  // Il semble qu'il puisse y'a avoir un probleme sur les aretes periodiques et memes les sommets
  // periodiques sur des petits maillages lorsque la largeur de joint recouvre des bords de direction
  // de periodicite differente
  if (!ok) Process::exit();
  */
}
References Debog::active(), Zone::aretes_som(), Cerr, Zone_VF::creer_tableau_aretes(), Periodique::direction_periodicite(), Zone::domaine(), Zone::elem_aretes(), Periodique::face_associee(), Zone_VF::face_sommets(), Zone_VF::face_voisins_, finl, Cond_lim_base::frontiere_dis(), TRUSTVect< _TYPE_ >::get_md_vector(), Domaine::get_renum_som_perio(), Zone::nb_aretes_tot(), Front_VF::nb_faces_tot(), Elem_geom::nb_som_face(), Array_base::NOCOPY_NOINIT, Front_VF::num_face(), ref_cast, renum_arete_perio, TRUSTArray< _TYPE_ >::resize_array(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), sub_type, Zone::type_elem(), Debog::verifier_indices_items(), volumes_aretes, Zone_VF::xa(), and Zone_dis_base::zone().
Referenced by modifier_pour_Cl().
cree_instance()
Objet_U * Zone_VEF_PreP1b::cree_instance () static
Definition at line 34 of file Zone_VEF_PreP1b.cpp.
creer_tableau_p1bulle()
void Zone_VEF_PreP1b::creer_tableau_p1bulle (Array_base & x, Array_base::Resize_Options opt = Array_base::COPY_INIT) const virtual
Definition at line 873 of file Zone_VEF_PreP1b.cpp.
{
  const MD_Vector& md = md_vector_p1b();
  MD_Vector_tools::creer_tableau_distribue(md, x, opt);
}
References MD_Vector_tools::creer_tableau_distribue(), and md_vector_p1b().
discretiser()
void Zone_VEF_PreP1b::discretiser () override virtual
Les volumes calcules dans discretiser() ne tiennent pas compte de
la periodicite. Pour les sommets periodiques, on fait la somme
de tous les volumes des sommets "identiques" au sens de la periodicite.
Reimplemented from Zone_VF.
Definition at line 53 of file Zone_VEF_PreP1b.cpp.
{
  Zone_VEF::discretiser();
  zone().domaine().creer_tableau_sommets(volumes_som, Array_base::NOCOPY_NOINIT);
  double coeff=1./3.;
  if (dimension==3)
    coeff=1./4.;
  const IntTab& elements = zone().les_elems();
  const int nb_som_elem = elements.dimension(1);
// Boucle sur tous les elements car on ajoute des contributions aux sommets de joints:
  const int n = nb_elem_tot();
// On a besoin de l'espace virtuel des volumes
  const DoubleVect& volume_elem = volumes();
  assert_espace_virtuel_vect(volume_elem);
// Annule tout le tableau car on va faire += sur des items virtuels
// (sinon acces a des cases non initialisees)
  operator_egal(volumes_som, 0., VECT_ALL_ITEMS);
  for(int k=0; k<n; k++)
    {
      double volume = coeff * volume_elem(k);
      for(int isom=0; isom<nb_som_elem; isom++)
        {
          int som = elements(k, isom);
          volumes_som(som)+=volume;
        }
    }
  volumes_som.echange_espace_virtuel();
}
References assert_espace_virtuel_vect(), coeff, Domaine::creer_tableau_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VEF::discretiser(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone::les_elems(), Zone_dis_base::nb_elem_tot(), Array_base::NOCOPY_NOINIT, operator_egal(), VECT_ALL_ITEMS, Zone_VF::volumes(), volumes_som, and Zone_dis_base::zone().
discretiser_arete()
void Zone_VEF_PreP1b::discretiser_arete ()
Definition at line 123 of file Zone_VEF_PreP1b.cpp.
{
  const Domaine& dom = zone().domaine();
// Creation des aretes reelles (informations geometriques construites et stockees dans la zone)
  zone().creer_aretes();
  md_vector_aretes_ = zone().aretes_som().get_md_vector();
// Calcul des centres de gravite des aretes xa_ stockes dans la Zone_VF
  const IntTab& aretes_som = zone().aretes_som();
  const int nb_aretes = aretes_som.dimension(0);
  const DoubleTab& coord = dom.les_sommets();
  const int dim = coord.dimension(1);
  xa_.resize(0, dim);
  creer_tableau_aretes(xa_, ArrOfDouble::NOCOPY_NOINIT);
  for (int i = 0; i < nb_aretes; i++)
    {
      const int s0 = aretes_som(i, 0);
      const int s1 = aretes_som(i, 1);
      for (int j = 0; j < dim; j++)
        xa_(i, j) = (coord(s0, j) + coord(s1, j)) * 0.5;
    }
  xa_.echange_espace_virtuel();
  const IntTab& elem_aretes = zone().elem_aretes();
// Calcul du volume des aretes
// Creation d'un tableau initialise a zero:
  creer_tableau_aretes(volumes_aretes);
  const int nbr_elem = zone().nb_elem();
  const int nb_aretes_elem = elem_aretes.dimension(1);
// facteur 6 pour le calcul des volumes des aretes, est-ce correct pour autre chose qu'un tetra ?
  assert(nb_aretes_elem == 6);
// Essai d'une autre facon de coder: calcul des contributions aux aretes par les elements reels,
// puis sommation des contributions des aretes partagees:
  for (int elem = 0; elem < nbr_elem; elem++)
    {
      double vol = volumes(elem) / 6.0;
      for(int j = 0; j < nb_aretes_elem; j++)
        {
          int arete = elem_aretes(elem, j);
          volumes_aretes[arete] += vol;
        }
    }
// Sommation des contributions des aretes joint et echange des espaces virtuels
  MD_Vector_tools::echange_espace_virtuel(volumes_aretes, MD_Vector_tools::EV_SOMME_ECHANGE);
}
References Zone::aretes_som(), Zone::creer_aretes(), Zone_VF::creer_tableau_aretes(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MD_Vector_tools::echange_espace_virtuel(), Zone::elem_aretes(), MD_Vector_tools::EV_SOMME_ECHANGE, TRUSTVect< _TYPE_ >::get_md_vector(), Domaine::les_sommets(), Zone_VF::md_vector_aretes_, Zone::nb_elem(), Array_base::NOCOPY_NOINIT, TRUSTTab< _TYPE_ >::resize(), Zone_VF::volumes(), volumes_aretes, Zone_VF::xa_, and Zone_dis_base::zone().
Referenced by discretiser_suite().
discretiser_suite()
void Zone_VEF_PreP1b::discretiser_suite (const VEFPreP1B & discr) virtual
Definition at line 86 of file Zone_VEF_PreP1b.cpp.
{
// Recuperation des parametres de la discretisation
  alphaE = discr.get_alphaE();
  alphaS = discr.get_alphaS();
  alphaA = discr.get_alphaA();
  P1Bulle = discr.get_P1Bulle();
  modif_div_face_dirichlet= discr.get_modif_div_face_dirichlet();
  cl_pression_sommet_faible = discr.get_cl_pression_sommet_faible();
  if (alphaA)
    discretiser_arete();
// Construction du descripteur pour les tableaux p1bulle
  {
    MD_Vector_composite md_p1b;
    if (alphaE)
      {
        const MD_Vector& md = zone().md_vector_elements();
        md_p1b.add_part(md, 0, "P0");
      }
    if (alphaS)
      {
        const MD_Vector& md = zone().domaine().md_vector_sommets();
        md_p1b.add_part(md, 0, "P1");
      }
    if (alphaA)
      {
        const MD_Vector& md = md_vector_aretes();
        md_p1b.add_part(md, 0, "Pa");
      }
    md_vector_p1b_.copy(md_p1b);
  }
  Cerr << "La Zone_VEF_PreP1b a ete remplie avec succes" << finl;
}
References MD_Vector_composite::add_part(), alphaA, alphaE, alphaS, Cerr, cl_pression_sommet_faible, MD_Vector::copy(), discretiser_arete(), Zone::domaine(), finl, VEFPreP1B::get_alphaA(), VEFPreP1B::get_alphaE(), VEFPreP1B::get_alphaS(), VEFPreP1B::get_cl_pression_sommet_faible(), VEFPreP1B::get_modif_div_face_dirichlet(), VEFPreP1B::get_P1Bulle(), Zone_VF::md_vector_aretes(), Zone::md_vector_elements(), md_vector_p1b_, Domaine::md_vector_sommets(), modif_div_face_dirichlet, P1Bulle, and Zone_dis_base::zone().
Referenced by VEFPreP1B::discretiser().
duplique()
int Zone_VEF_PreP1b::duplique () const override virtual
Implements Objet_U.
Definition at line 34 of file Zone_VEF_PreP1b.cpp.
get_alphaA()
int Zone_VEF_PreP1b::get_alphaA () const inline
Definition at line 64 of file Zone_VEF_PreP1b.h.
  {
    assert(alphaA!=-1);
    return alphaA;
  };
References alphaA.
Referenced by Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_VEF_P1B_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Assembleur_P_VEFPreP1B::assembler_mat(), corriger(), Op_Grad_VEF_P1B_Face::impr(), Assembleur_P_VEFPreP1B::modifier_matrice(), modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_solution(), Zone_Cl_VEFP1B::remplir_volumes_entrelaces_Cl(), EOS_Tools_VEF::secmembre_divU_Z(), verifier(), and Op_Div_VEFP1B_Elem::volumique().
get_alphaE()
int Zone_VEF_PreP1b::get_alphaE () const inline
Definition at line 54 of file Zone_VEF_PreP1b.h.
  {
    assert(alphaE!=-1);
    return alphaE;
  };
References alphaE.
Referenced by Champ_P1_isoP1Bulle::affecter_(), Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_VEF_P1B_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Assembleur_P_VEFPreP1B::assembler_mat(), corriger(), Champ_P1iP1B_implementation::filtrage(), Op_Grad_VEF_P1B_Face::impr(), Assembleur_P_VEFPreP1B::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Assembleur_P_VEFPreP1B::modifier_solution(), Zone_Cl_VEFP1B::remplir_volumes_entrelaces_Cl(), EOS_Tools_VEF::secmembre_divU_Z(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_sommets(), verifier(), and Op_Div_VEFP1B_Elem::volumique().
get_alphaS()
int Zone_VEF_PreP1b::get_alphaS () const inline
Definition at line 59 of file Zone_VEF_PreP1b.h.
  {
    assert(alphaS!=-1);
    return alphaS;
  };
References alphaS.
Referenced by Champ_P1_isoP1Bulle::affecter_(), Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_VEF_P1B_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Assembleur_P_VEFPreP1B::assembler_mat(), corriger(), Champ_P1iP1B_implementation::filtrage(), Zone_Cl_VEFP1B::imposer_cond_lim(), Op_Grad_VEF_P1B_Face::impr(), Assembleur_P_VEFPreP1B::modifier_matrice(), modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_solution(), Zone_Cl_VEFP1B::remplir_volumes_entrelaces_Cl(), EOS_Tools_VEF::secmembre_divU_Z(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_sommets(), verifier(), and Op_Div_VEFP1B_Elem::volumique().
get_cl_pression_sommet_faible()
int Zone_VEF_PreP1b::get_cl_pression_sommet_faible () const inline
Definition at line 74 of file Zone_VEF_PreP1b.h.
  {
    assert(cl_pression_sommet_faible!=-1);
    return cl_pression_sommet_faible;
  };
References cl_pression_sommet_faible.
Referenced by Op_Div_VEFP1B_Elem::ajouter(), Assembleur_P_VEFPreP1B::assembler_mat(), Zone_Cl_VEFP1B::imposer_cond_lim(), and Assembleur_P_VEFPreP1B::modifier_matrice().
get_info()
const Type_info * Zone_VEF_PreP1b::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_VF.
Definition at line 34 of file Zone_VEF_PreP1b.cpp.
get_modif_div_face_dirichlet()
int Zone_VEF_PreP1b::get_modif_div_face_dirichlet () const inline
Definition at line 69 of file Zone_VEF_PreP1b.h.
  {
    assert(modif_div_face_dirichlet!=-1);
    return modif_div_face_dirichlet;
  };
References modif_div_face_dirichlet.
Referenced by Op_Div_VEFP1B_Elem::ajouter_som(), Op_Grad_VEF_P1B_Face::calculer_coef_som(), and Zone_Cl_VEFP1B::remplir_volumes_entrelaces_Cl().
get_ok_arete()
const IntVect & Zone_VEF_PreP1b::get_ok_arete () const inline
Definition at line 83 of file Zone_VEF_PreP1b.h.
  {
    return ok_arete;
  };
References ok_arete.
Referenced by Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), contribuer_matrice_NeumannP0Pa(), contribuer_matrice_NeumannP1Pa(), contribuer_matrice_NeumannPaPa(), contribuer_matrice_SymetrieP1Pa(), contribuer_matrice_SymetriePaPa(), contribuer_matriceP0Pa(), contribuer_matriceP1Pa(), contribuer_matricePaPa(), corriger(), exemple_champ_non_homogene(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_solution(), update_matrice_NeumannP0Pa(), update_matrice_NeumannP1Pa(), update_matrice_NeumannPaPa(), update_matrice_SymetrieP1Pa(), update_matrice_SymetriePaPa(), update_matriceP0Pa(), update_matriceP1Pa(), update_matricePaPa(), verifier(), and Assembleur_P_VEFPreP1B::verifier_dirichlet().
get_P1Bulle()
int Zone_VEF_PreP1b::get_P1Bulle () const inline
Definition at line 49 of file Zone_VEF_PreP1b.h.
  {
    assert(P1Bulle!=-1);
    return P1Bulle;
  };
References P1Bulle.
get_renum_arete_perio()
const ArrOfInt & Zone_VEF_PreP1b::get_renum_arete_perio () const inline
Definition at line 79 of file Zone_VEF_PreP1b.h.
  {
    return renum_arete_perio;
  };
References renum_arete_perio.
Referenced by Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), assembler(), chercher_arete(), corriger(), exemple_champ_non_homogene(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_solution(), second_membre(), and verifier().
get_volumes_aretes()
const DoubleVect & Zone_VEF_PreP1b::get_volumes_aretes () const inline
Definition at line 87 of file Zone_VEF_PreP1b.h.
  {
    return volumes_aretes;
  };
References volumes_aretes.
Referenced by Op_Div_VEFP1B_Elem::volumique().
info()
const Type_info * Zone_VEF_PreP1b::info () static
Definition at line 34 of file Zone_VEF_PreP1b.cpp.
lecture_ok_arete()
int Zone_VEF_PreP1b::lecture_ok_arete ()
< initialise a zero par defaut
Definition at line 802 of file Zone_VEF_PreP1b.cpp.
{
  Nom fichier(nom_du_cas());
  fichier+="_";
  fichier+=zone().domaine().le_nom()+".ok_arete";
  Cerr << "Trying to read file " << fichier << " (edges to remove from the set of degrees of freedom)" << finl;
  EFichierBin fic_ok_arete_;
// Lecture de ok_arete dans un fichier pour comparaison sequentiel-parallele
  if (!fic_ok_arete_.ouvrir(fichier,ios::out))
    {
      Cerr << "File " << fichier << " does not exist." << finl;
      return 0;
    }
  int n;
  fic_ok_arete_ >> n;
  if (n != md_vector_aretes().valeur().nb_items_seq_tot())
    {
      Cerr << "File " << fichier << " is not compatible with the current mesh." << finl;
      return 0;
    }
  Octree_Double octree;
  octree.build_nodes(xa_, 1 /* include virtual nodes */);
  const double eps = precision_geom;
  ArrOfInt liste_aretes;
  liste_aretes.set_smart_resize(1);
  IntVect marqueurs;
  creer_tableau_aretes(marqueurs); //!< initialise a zero par defaut
  for (int i = 0; i < n; i++)
    {
      double x, y, z;
      int flag;
      fic_ok_arete_ >> x >> y >> z >> flag;
      octree.search_elements_box(x-eps, y-eps, z-eps, x+eps, y+eps, z+eps, liste_aretes);
      octree.search_nodes_close_to(x, y, z, xa_, liste_aretes, eps);
      const int m = liste_aretes.size_array();
      if (m > 1)
        {
          Cerr << "File " << fichier << " is not compatible with the current mesh." << finl;
          return 0;
        }
      if (m == 1)
        {
          const int arete = liste_aretes[0];
          ok_arete[arete] = flag;
          marqueurs[arete]++;
        }
      else
        {
// Normal en parallele: on n'a pas toutes les aretes sur tous les procs...
        }
    }
// On doit avoir trouve exactement une fois toutes les aretes:
  if (max_array(marqueurs) > 1 || min_array(marqueurs) < 1)
    {
      Cerr << "File " << fichier << " is not compatible with the current mesh." << finl;
      return 0;
    }
  else
    Cerr << "File " << fichier << " is OK." << finl;
  fic_ok_arete_.close();
  assert_espace_virtuel_vect(ok_arete);
  return 1;
}
References assert_espace_virtuel_vect(), Octree_Double::build_nodes(), Cerr, Entree_Fichier_base::close(), Zone_VF::creer_tableau_aretes(), Zone::domaine(), finl, Domaine::le_nom(), max_array(), Zone_VF::md_vector_aretes(), min_array(), Objet_U::nom_du_cas(), ok_arete, Entree_Fichier_base::ouvrir(), Objet_U::precision_geom, Octree_Double::search_elements_box(), Octree_Double::search_nodes_close_to(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), valeur(), Zone_VF::xa_, and Zone_dis_base::zone().
Referenced by modifier_pour_Cl().
md_vector_p1b()
virtual const MD_Vector & Zone_VEF_PreP1b::md_vector_p1b () const inline virtual
Definition at line 101 of file Zone_VEF_PreP1b.h.
  {
    assert(md_vector_p1b_.non_nul());
    return md_vector_p1b_;
  }
References md_vector_p1b_, and MD_Vector::non_nul().
Referenced by creer_tableau_p1bulle(), Champ_Fonc_P1_isoP1Bulle::fixer_nb_valeurs_nodales(), and Champ_P1_isoP1Bulle::fixer_nb_valeurs_nodales().
modifier_pour_Cl()
void Zone_VEF_PreP1b::modifier_pour_Cl (const Conds_lim & conds_lim) override virtual
Reimplemented from Zone_VF.
Definition at line 215 of file Zone_VEF_PreP1b.cpp.
{
  Zone_VEF::modifier_pour_Cl(conds_lim);
  static DoubleVect* ptr=0;
  if(ptr!=&volumes_som)
    {
      const Domaine& dom=zone().domaine();
      int i;
      const int ns = nb_som();
      for(i=0; i<ns; i++)
        {
          int j=(dom.get_renum_som_perio(i));
          if(i!=j)
            volumes_som(j)+=volumes_som(i);
        }
      for(i=0; i<ns; i++)
        {
          int j=(dom.get_renum_som_perio(i));
          if(i!=j)
            volumes_som(i)=volumes_som(j);
        }
      volumes_som.echange_espace_virtuel();
      ptr = &volumes_som;
    }
// Verification du tableau renum_som_perio
  if (Debog::active())
    {
      IntVect tmp;
      const Domaine& dom = zone().domaine();
      dom.creer_tableau_sommets(tmp, Array_base::NOCOPY_NOINIT);
      const int n = tmp.size_array();
      for (int i=0; i<n; i++)
        tmp[i] = dom.get_renum_som_perio(i);
      Debog::verifier_indices_items("renum_som_perio",tmp.get_md_vector(),tmp);
    }
  if(get_alphaA())
    {
// Construction de renum_arete_perio
      construire_renum_arete_perio(conds_lim);
// Creation d'un tableau distribue pour ok_arete
      creer_tableau_aretes(ok_arete, ArrOfInt::NOCOPY_NOINIT);
// Si P1 alors on doit trouver les aretes superflues:
      if (get_alphaS())
        {
// On essaie de lire un fichier .ok_arete d'un precedant calcul
// S'il n'existe pas ou est incoherent avec le maillage, on reconstruit ok_arete
          if (!lecture_ok_arete())
            construire_ok_arete();
        }
      else
        {
// Toutes les aretes sont necessaires si pas support P1
          ok_arete=1;
        }
      Debog::verifier_getref("ok_arete", ok_arete, ok_arete);
// Debog::verifier("ok_arete (identique seulement si ok_arete relu dans le fichier .ok_arete):",ok_arete);
    }//!< fin if 3D
}
References Debog::active(), construire_ok_arete(), construire_renum_arete_perio(), Zone_VF::creer_tableau_aretes(), Domaine::creer_tableau_sommets(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), get_alphaA(), get_alphaS(), TRUSTVect< _TYPE_ >::get_md_vector(), Domaine::get_renum_som_perio(), lecture_ok_arete(), Zone_VEF::modifier_pour_Cl(), nb_som(), Array_base::NOCOPY_NOINIT, ok_arete, TRUSTArray< _TYPE_ >::size_array(), Debog::verifier_getref(), Debog::verifier_indices_items(), volumes_som, and Zone_dis_base::zone().
nb_elem()
int Zone_VEF_PreP1b::nb_elem () const inline
Definition at line 37 of file Zone_VEF_PreP1b.h.
  {
    return zone().nb_elem();
  };
References Zone::nb_elem(), and Zone_dis_base::zone().
Referenced by corriger().
nb_som()
int Zone_VEF_PreP1b::nb_som () const inline
Definition at line 33 of file Zone_VEF_PreP1b.h.
  {
    return zone().nb_som();
  };
References Zone::nb_som(), and Zone_dis_base::zone().
Referenced by Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), construire_ok_arete(), corriger(), modifier_pour_Cl(), Champ_P1iP1B_implementation::valeur_aux_sommets(), and verifie_ok_arete().
numero_premier_element()
int Zone_VEF_PreP1b::numero_premier_element () const inline
Definition at line 123 of file Zone_VEF_PreP1b.h.
{
  if (!alphaE)
    return -1;
  else
    return 0;
}
References alphaE.
Referenced by Champ_P1iP1B_implementation::remplir_coord_noeuds().
numero_premier_sommet()
int Zone_VEF_PreP1b::numero_premier_sommet () const inline
Definition at line 130 of file Zone_VEF_PreP1b.h.
{
  if (!alphaS)
    return -1;
  else if (!alphaE)
    return 0;
  else
    return nb_elem_tot();
}
References alphaE, alphaS, and Zone_dis_base::nb_elem_tot().
Referenced by Champ_P1_isoP1Bulle::affecter_(), Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Zone_Cl_VEFP1B::imposer_cond_lim(), Op_Grad_VEF_P1B_Face::impr(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_solution(), Champ_P1_isoP1Bulle::norme_L2(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Champ_P1_isoP1Bulle::valeur_au_bord(), Champ_P1iP1B_implementation::valeur_aux_elems(), and Champ_P1iP1B_implementation::valeur_aux_sommets().
numero_premiere_arete()
int Zone_VEF_PreP1b::numero_premiere_arete () const inline
Definition at line 139 of file Zone_VEF_PreP1b.h.
{
  if (!alphaA)
    return -1;
  else if (!alphaE && !alphaS)
    return 0;
  else if (!alphaE && alphaS)
    return nb_som_tot();
  else if (!alphaS && alphaE)
    return nb_elem_tot();
  else
    return nb_elem_tot()+nb_som_tot();
}
References alphaA, alphaE, alphaS, Zone_dis_base::nb_elem_tot(), and Zone_dis_base::nb_som_tot().
Referenced by Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Grad_VEF_P1B_Face::impr(), Assembleur_P_VEFPreP1B::modifier_secmem(), and Assembleur_P_VEFPreP1B::modifier_solution().
printOn()
Sortie & Zone_VEF_PreP1b::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
< PQ : 12/10/05 : a voir ce qu'il faut faire ici ???
Reimplemented from Zone_VF.
Definition at line 39 of file Zone_VEF_PreP1b.cpp.
{
  return Zone_VEF::printOn(s);
}
References Zone_VEF::printOn().
readOn()
Entree & Zone_VEF_PreP1b::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Zone_VF.
Definition at line 44 of file Zone_VEF_PreP1b.cpp.
{
  return Zone_VEF::readOn(is);
}
References Zone_VEF::readOn().
self_cast() [1/2]
const Zone_VEF_PreP1b & Zone_VEF_PreP1b::self_cast (const Objet_U & r) static
Definition at line 34 of file Zone_VEF_PreP1b.cpp.
self_cast() [2/2]
Zone_VEF_PreP1b & Zone_VEF_PreP1b::self_cast (Objet_U & r) static
Definition at line 34 of file Zone_VEF_PreP1b.cpp.
taille_memoire()
unsigned Zone_VEF_PreP1b::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 34 of file Zone_VEF_PreP1b.cpp.
verifie_ok_arete()
void Zone_VEF_PreP1b::verifie_ok_arete (int nombre_aretes_superflues_prevues_sur_la_zone) const
< Pour verbose
< Si i est un sommet periodique:
< il suffit de faire la verification sur le sommet dom.get_renum_som_perio(i)
< donc on ne verifie pas i
< arete superflue
< Pour ne compter les aretes periodiques qu'une fois
< Sommet non periodique
< On se limite au sequentiel car il y'a un soucis pour le calcul de total_nombre_aretes_superflues (les items communs pour les aretes n'est pas construit!)
Definition at line 669 of file Zone_VEF_PreP1b.cpp.
{
  Cerr << "Check array ok_arete..." << finl;
// Algorithme de verification du tableau des aretes superflues
// ok_arete(i)==0 : i arete superflue
// ok_arete(i)==2 : i arete necessaire
// ...
// contenu doit contenir uniquement 2 ce qui implique que tous les
// sommets ont ete analyses.
  const Domaine& dom=zone().domaine();
  const int nb_som_reel=nb_som();
  const IntTab& aretes_som=zone().aretes_som();
  int nb_aretes_pour_verbose=60; //!< Pour verbose
  ArrOfInt sommet_relie_arete_superflue(nb_som_reel);
  sommet_relie_arete_superflue=0;
  for (int i=0; i<nb_som_reel; i++) //!< Si i est un sommet periodique:
    if (dom.get_renum_som_perio(i)!=i) //!< il suffit de faire la verification sur le sommet dom.get_renum_som_perio(i)
      sommet_relie_arete_superflue[i]=1; //!< donc on ne verifie pas i
  double nombre_aretes_reelles_superflues=0;
// On parcourt toutes les aretes mais on ne regarde que les sommets reels
  int nb_aretes_tot=zone().nb_aretes_tot();
  int nb_aretes_reelles=zone().nb_aretes();
  for (int i=0; i<nb_aretes_tot; i++)
    {
      if (!ok_arete(i)) //!< arete superflue
        {
          int S0=aretes_som(i,0);
          if (S0<nb_som_reel)
            {
              sommet_relie_arete_superflue[S0]=1;
              sommet_relie_arete_superflue[dom.get_renum_som_perio(S0)]=1;
            }
          int S1=aretes_som(i,1);
          if (S1<nb_som_reel)
            {
              sommet_relie_arete_superflue[S1]=1;
              sommet_relie_arete_superflue[dom.get_renum_som_perio(S1)]=1;
            }
          if (renum_arete_perio[i]==i) //!< Pour ne compter les aretes periodiques qu'une fois
            {
              if (nb_aretes_tot<nb_aretes_pour_verbose)
                {
                  if (renum_arete_perio[i]==i) Cerr << "[" << Process::me() << "] Arete " << i << " superflue non perio: " << S0 << " " << S1 << finl;
                  else Cerr << "[" << Process::me() << "] Arete " << i << " superflue perio: " << S0 << " " << S1 << " Periodique avec " << renum_arete_perio[i] << finl;
                }
              int aretes_superflues_communes=1;
// Si l'arete superflue est commune on en tient compte
              for (int j=0; j<dom.zone(0).faces_joint().size(); j++)
                {
                  int nb_aretes_sur_le_joint = dom.zone(0).faces_joint()(j).joint_item(Joint::ARETE).items_communs().size_array();
                  for (int k=0; k<nb_aretes_sur_le_joint; k++)
                    if (dom.zone(0).faces_joint()(j).joint_item(Joint::ARETE).items_communs()[k]==i) aretes_superflues_communes++;
                }
// On compte les aretes reelles superflues
              if (i<nb_aretes_reelles)
                nombre_aretes_reelles_superflues+=1./aretes_superflues_communes;
            }
        }
    }
  if (nb_som_reel > 0 && min_array(sommet_relie_arete_superflue)==0)
    {
      Cerr << finl << "[" << Process::me() << "] Il y'a au moins un sommet qui n'est pas relie a une arete superflue :" << finl;
      for (int i=0; i<sommet_relie_arete_superflue.size_array(); i++)
        if (sommet_relie_arete_superflue[i]==0) Cerr << "Sommet " << i << finl;
      Process::exit();
    }
  Cerr << "[" << Process::me() << "] Verification que chaque sommet non periodique est bien relie a au moins une arete superflue: OK!" << finl;
// On compte le nombre total de sommets en tenant compte de la periodicite et des sommets communs
  double nb_sommets_non_periodiques=0;
  for (int i=0; i<nb_som_reel; i++)
    if (dom.get_renum_som_perio(i)==i) //!< Sommet non periodique
      {
        int sommets_communs=1;
// On tient compte des sommets communs
        for (int j=0; j<dom.zone(0).faces_joint().size(); j++)
          for (int k=0; k<dom.zone(0).faces_joint()(j).joint_item(Joint::SOMMET).items_communs().size_array(); k++)
            if (dom.zone(0).faces_joint()(j).joint_item(Joint::SOMMET).items_communs()[k]==i) sommets_communs++;
        nb_sommets_non_periodiques+=1./sommets_communs;
      }
  double total_nombre_aretes_superflues=mp_sum(nombre_aretes_reelles_superflues);
  double somme_nombre_aretes_superflues_prevues_par_zone=mp_sum(nombre_aretes_superflues_prevues_sur_la_zone);
  double total_nb_sommets_non_periodiques=mp_sum(nb_sommets_non_periodiques);
// Cerr << "Nombre de sommets non periodiques           = " << total_nb_sommets_non_periodiques << finl;
// Cerr << "Nombre de sommets periodiques               =  " << nb_som_reel-total_nb_sommets_non_periodiques << finl;
  int nb_aretes_periodiques=0;
  int nb_aretes_perio_superflues=0;
  for (int i=0; i<nb_aretes_tot; i++)
    {
      if (renum_arete_perio[i]!=i)
        {
          nb_aretes_periodiques++;
          assert(ok_arete(i)==ok_arete(renum_arete_perio[i]));
          if (!ok_arete(i))
            nb_aretes_perio_superflues++;
        }
    }
// Cerr << "Nombre d'aretes non periodiques             = " << nb_aretes_tot-nb_aretes_periodiques << finl;
// Cerr << "Nombre d'aretes periodiques                 =  " << nb_aretes_periodiques << finl;
// Cerr << "Nombre d'aretes superflues                  =  " << total_nombre_aretes_superflues << finl;
// Cerr << "Nombre d'aretes superflues periodiques      =  " << nb_aretes_perio_superflues << finl;
// Cerr << "Nombre d'aretes non superflues periodiques  =  " << nb_aretes_periodiques-nb_aretes_perio_superflues << finl;
  if (Process::nproc()==1) //!< On se limite au sequentiel car il y'a un soucis pour le calcul de total_nombre_aretes_superflues (les items communs pour les aretes n'est pas construit!)
    if (!est_egal(somme_nombre_aretes_superflues_prevues_par_zone,total_nombre_aretes_superflues) && je_suis_maitre())
      {
        Cerr << "La somme des aretes superflues prevues par zone n'est pas egale au nombre d'aretes superflues trouvees sur le domaine." << finl;
        Cerr << somme_nombre_aretes_superflues_prevues_par_zone << " != " << total_nombre_aretes_superflues << finl;
        Process::exit();
      }
  if (Process::je_suis_maitre())
    {
      Cerr << "Nombre total d'aretes superflues: " << somme_nombre_aretes_superflues_prevues_par_zone << finl;
      Cerr << "Nombre total de sommets non periodiques = " << total_nb_sommets_non_periodiques << finl;
      Cerr << "Verification de l'egalite du nombre total d'aretes superflues et du nombre total de sommets: ";
    }
// Verification que le nombre d'aretes superflues et egal au nombre de sommets
  if (!est_egal(somme_nombre_aretes_superflues_prevues_par_zone,total_nb_sommets_non_periodiques) && je_suis_maitre())
    {
      Cerr << "Non correspondance. Echec de l'algorithme de recherche des aretes superflues." << finl;
      Process::exit();
    }
  Cerr << "OK!" << finl << "Verification correcte des aretes superflues." << finl;
}
References Joint::ARETE, Zone::aretes_som(), Cerr, Zone::domaine(), est_egal(), Process::exit(), Zone::faces_joint(), finl, Domaine::get_renum_som_perio(), Process::je_suis_maitre(), Process::me(), min_array(), Process::mp_sum(), Zone::nb_aretes(), Zone::nb_aretes_tot(), nb_som(), Process::nproc(), ok_arete, renum_arete_perio, TRUSTArray< _TYPE_ >::size_array(), Joint::SOMMET, Zone_dis_base::zone(), and Domaine::zone().
Referenced by construire_ok_arete().
volume_au_sommet()
double Zone_VEF_PreP1b::volume_au_sommet (int som) const inline
Definition at line 41 of file Zone_VEF_PreP1b.h.
  {
    return volumes_som[som];
  };
References volumes_som.
volume_aux_sommets()
const DoubleVect & Zone_VEF_PreP1b::volume_aux_sommets () const inline
Definition at line 45 of file Zone_VEF_PreP1b.h.
  {
    return volumes_som;
  };
References volumes_som.
Referenced by Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), EOS_Tools_VEF::secmembre_divU_Z(), and Op_Div_VEFP1B_Elem::volumique().
Member Data Documentation
alphaA
int Zone_VEF_PreP1b::alphaA protected
Definition at line 114 of file Zone_VEF_PreP1b.h.
Referenced by discretiser_suite(), get_alphaA(), and numero_premiere_arete().
alphaE
int Zone_VEF_PreP1b::alphaE protected
Definition at line 112 of file Zone_VEF_PreP1b.h.
Referenced by discretiser_suite(), get_alphaE(), numero_premier_element(), numero_premier_sommet(), and numero_premiere_arete().
alphaS
int Zone_VEF_PreP1b::alphaS protected
Definition at line 113 of file Zone_VEF_PreP1b.h.
Referenced by discretiser_suite(), get_alphaS(), numero_premier_sommet(), and numero_premiere_arete().
cl_pression_sommet_faible
int Zone_VEF_PreP1b::cl_pression_sommet_faible protected
determine si les cl de pression sont imposees de facon faible ou forte -> voir divergence et assembleur Descripteur pour les tableaux p1b (selon alphaE, alphaS et alphaA) (construit dans Zone_VEF_PreP1b::discretiser())
Definition at line 116 of file Zone_VEF_PreP1b.h.
Referenced by discretiser_suite(), and get_cl_pression_sommet_faible().
info_obj
const Type_info Zone_VEF_PreP1b::info_obj static
Definition at line 27 of file Zone_VEF_PreP1b.h.
md_vector_p1b_
MD_Vector Zone_VEF_PreP1b::md_vector_p1b_ protected
Definition at line 119 of file Zone_VEF_PreP1b.h.
Referenced by discretiser_suite(), and md_vector_p1b().
modif_div_face_dirichlet
int Zone_VEF_PreP1b::modif_div_face_dirichlet protected
Definition at line 115 of file Zone_VEF_PreP1b.h.
Referenced by discretiser_suite(), and get_modif_div_face_dirichlet().
ok_arete
IntVect Zone_VEF_PreP1b::ok_arete protected
Definition at line 110 of file Zone_VEF_PreP1b.h.
Referenced by construire_ok_arete(), get_ok_arete(), lecture_ok_arete(), modifier_pour_Cl(), and verifie_ok_arete().
P1Bulle
int Zone_VEF_PreP1b::P1Bulle protected
Definition at line 111 of file Zone_VEF_PreP1b.h.
Referenced by discretiser_suite(), and get_P1Bulle().
renum_arete_perio
ArrOfInt Zone_VEF_PreP1b::renum_arete_perio protected
Definition at line 109 of file Zone_VEF_PreP1b.h.
Referenced by construire_ok_arete(), construire_renum_arete_perio(), get_renum_arete_perio(), and verifie_ok_arete().
volumes_aretes
DoubleVect Zone_VEF_PreP1b::volumes_aretes protected
Definition at line 108 of file Zone_VEF_PreP1b.h.
Referenced by construire_renum_arete_perio(), discretiser_arete(), and get_volumes_aretes().
volumes_som
DoubleVect Zone_VEF_PreP1b::volumes_som protected
Definition at line 107 of file Zone_VEF_PreP1b.h.
Referenced by discretiser(), modifier_pour_Cl(), volume_au_sommet(), and volume_aux_sommets().
The documentation for this class was generated from the following files:
src/P1NCP1B/Zones/Zone_VEF_PreP1b.h
src/P1NCP1B/Zones/Zone_VEF_PreP1b.cpp