TRUST: Champ_Generique_Correlation Class Reference
Champ_Generique_Correlation Class Reference
class Champ_Generique_Correlation
Champ destine a post-traiter une correlation d un champ generique
La classe porte un operateur statistique "Op_Correlation"
#include <Champ_Generique_Correlation.h>
Public Member Functions
Champ_Generique_Correlation ()
~Champ_Generique_Correlation ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
double temps () const override
const Integrale_tps_Champ & integrale () const override
const Operateur_Statistique_tps_base & Operateur_Statistique () const override
Operateur_Statistique_tps_base & Operateur_Statistique () override
void completer (const Postraitement_base &post) override
const Motcle get_directive_pour_discr () const override
const Champ_base & get_champ (Champ &espace_stockage) const override
void nommer_source () override
int get_info_type_post () const override
Public Member Functions inherited from Champ_Generique_Statistiques_base
~Champ_Generique_Statistiques_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
Champ_Generique_Statistiques_base ()
virtual void associer_op_stat (const Champ_Generique_Statistiques_base &)
virtual double temps () const =0
virtual const Integrale_tps_Champ & integrale () const =0
virtual int completer_post_statistiques (const Domaine &dom, const int is_axi, Format_Post_base &format)
virtual const Operateur_Statistique_tps_base & Operateur_Statistique () const =0
virtual Operateur_Statistique_tps_base & Operateur_Statistique ()=0
int sauvegarder (Sortie &os) const override
sauvegarde des differentes sources
int reprendre (Entree &is) override
reprise des differentes sources
void mettre_a_jour (double temps) override
void fixer_tdeb_tfin (const double t_deb, const double t_fin)
void fixer_serie (const double t1, const double t2) override
void fixer_tstat_deb (const double t1, const double t2) override
void lire_bidon (Entree &is) const override
const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const override
double tstat_deb () const
double tstat_fin () const
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
Champ_Gen_de_Champs_Gen ()
~Champ_Gen_de_Champs_Gen () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual List_Champ_Generique & get_set_sources ()
virtual Champ_Generique & get_set_source ()
void reset () override
int sauvegarder (Sortie &os) const override
sauvegarde des differentes sources
int reprendre (Entree &is) override
reprise des differentes sources
void completer (const Postraitement_base &post) override
void mettre_a_jour (double temps) override
virtual Champ_Fonc & creer_espace_stockage (const Nature_du_champ &nature, const int nb_comp, Champ_Fonc &es_tmp) const
virtual const Champ_Generique_base & get_source (int i) const
virtual Champ_Generique_base & set_source (int i)
virtual int get_nb_sources () const
int get_dimension () const override
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
void get_property_names (Motcles &list) const override
Renvoie la liste des "query" possibles pour le champ.
double get_time () const override
Renvoie le temps du Champ_Generique.
const Probleme_base & get_ref_pb_base () const override
const Discretisation_base & get_discretisation () const override
const Motcle get_directive_pour_discr () const override
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Entity get_localisation (const int index=-1) const override
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
const DoubleTab & get_ref_values () const override
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_copy_values (DoubleTab &) const override
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
const Domaine & get_ref_domain () const override
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
void get_copy_domain (Domaine &) const override
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_dis_base & get_ref_zone_dis_base () const override
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_Cl_dis_base & get_ref_zcl_dis_base () const override
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
const DoubleTab & get_ref_coordinates () const override
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
void get_copy_coordinates (DoubleTab &) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const override
void nommer_sources ()
virtual void nommer_source ()
int get_info_type_post () const override
const Champ_Generique_base & get_champ_post (const Motcle &nom) const override
int comprend_champ_post (const Motcle &identifiant) const override
virtual void fixer_serie (const double t1, const double t2)
virtual void fixer_tstat_deb (const double t1, const double t2)
virtual void lire_bidon (Entree &is) const
Public Member Functions inherited from Champ_Generique_base
Champ_Generique_base ()
~Champ_Generique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int get_dimension () const
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
virtual double get_time () const
Renvoie le temps du Champ_Generique.
virtual const Probleme_base & get_ref_pb_base () const
virtual const Discretisation_base & get_discretisation () const
virtual const Motcle get_directive_pour_discr () const
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
virtual const Nom & get_nom_post () const
virtual void get_property_names (Motcles &list) const
Renvoie la liste des "query" possibles pour le champ.
virtual const Noms get_property (const Motcle &query) const
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
virtual Entity get_localisation (const int index=-1) const
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
virtual int get_nb_localisations () const
virtual const DoubleTab & get_ref_values () const
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_copy_values (DoubleTab &) const
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const
virtual const Domaine & get_ref_domain () const
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual void get_copy_domain (Domaine &) const
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_dis_base & get_ref_zone_dis_base () const
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_Cl_dis_base & get_ref_zcl_dis_base () const
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
virtual const DoubleTab & get_ref_coordinates () const
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
virtual void get_copy_coordinates (DoubleTab &) const
virtual const IntTab & get_ref_connectivity (Entity index1, Entity index2) const
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
virtual void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const
virtual void reset ()=0
virtual void completer (const Postraitement_base &post)=0
virtual void mettre_a_jour (double temps)=0
virtual const Champ_base & get_champ (Champ &espace_stockage) const =0
virtual const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const =0
virtual const Champ_Generique_base & get_champ_post (const Motcle &nom) const
virtual int comprend_champ_post (const Motcle &identifiant) const
virtual int get_info_type_post () const =0
void fixer_identifiant_appel (const Nom &identifiant)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Generique_Correlation & self_cast (Objet_U &)
static const Champ_Generique_Correlation & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Generique_Statistiques_base
static const Type_info * info ()
static Champ_Generique_Statistiques_base & self_cast (Objet_U &)
static const Champ_Generique_Statistiques_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Gen_de_Champs_Gen
static const Type_info * info ()
static Champ_Gen_de_Champs_Gen & self_cast (Objet_U &)
static const Champ_Gen_de_Champs_Gen & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Generique_base
static const Type_info * info ()
static Champ_Generique_base & self_cast (Objet_U &)
static const Champ_Generique_base & self_cast (const Objet_U &)
static int composante (const Nom &nom_test, const Nom &nom, const Noms &composantes, const Noms &synonyms)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Generique_Statistiques_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_Gen_de_Champs_Gen
static const Type_info info_obj
Static Public Attributes inherited from Champ_Generique_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Champ_Generique_Statistiques_base
Sortie & printOn (Sortie &x) const override
Imprime le nom et le type de l'operateur sur
un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Champ_Generique_base
Sortie & printOn (Sortie &x) const override
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Op_Correlation Op_Correlation_
Protected Attributes inherited from Champ_Generique_Statistiques_base
double tstat_deb_
double tstat_fin_
Protected Attributes inherited from Champ_Gen_de_Champs_Gen
List_Nom noms_sources_ref_
List_Ref_Champ_Generique_base sources_reference_
Protected Attributes inherited from Champ_Generique_base
Nom nom_post_
Nom identifiant_appel_
Nom nom_pb_
Ref_Probleme_base ref_pb_
Additional Inherited Members
Static Protected Member Functions inherited from Champ_Generique_base
static void assert_parallel (int)
Detailed Description
class Champ_Generique_Correlation
Champ destine a post-traiter une correlation d un champ generique
La classe porte un operateur statistique "Op_Correlation"
Definition at line 42 of file Champ_Generique_Correlation.h.
Constructor & Destructor Documentation
Champ_Generique_Correlation()
Champ_Generique_Correlation::Champ_Generique_Correlation ()
Definition at line 23 of file Champ_Generique_Correlation.cpp.
~Champ_Generique_Correlation()
Champ_Generique_Correlation::~Champ_Generique_Correlation ()
Definition at line 23 of file Champ_Generique_Correlation.cpp.
Member Function Documentation
completer()
void Champ_Generique_Correlation::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 36 of file Champ_Generique_Correlation.cpp.
{
  Champ_Gen_de_Champs_Gen::completer(post);
  const Probleme_base& Pb = get_ref_pb_base();
  Noms nom = get_source(0).get_property("nom");
  Motcle nom_champ = nom[0];
  Noms nom2 = get_source(1).get_property("nom");
  Motcle nom_champ2 = nom2[0];
  const Champ_Generique_base& ch_integre = get_source(0);
  const Champ_Generique_base& ch_integre2 = get_source(1);
  const Zone_dis_base& zdis = get_ref_zone_dis_base();
  Op_Correlation_.associer(zdis,ch_integre,ch_integre2,tstat_deb_,tstat_fin_);
  const Postraitement& mon_post = ref_cast(Postraitement,post);
  Motcle nom_champ_moyenne("Moyenne_");
  nom_champ_moyenne += nom_champ;
  nom_champ_moyenne += "_";
  nom_champ_moyenne += Nom(tstat_deb_,"%e");
  nom_champ_moyenne += "_";
  nom_champ_moyenne += Nom(tstat_fin_,"%e");
  Motcle nom_champ_moyenne2("Moyenne_");
  nom_champ_moyenne2 += nom_champ2;
  nom_champ_moyenne2 += "_";
  nom_champ_moyenne2 += Nom(tstat_deb_,"%e");
  nom_champ_moyenne2 += "_";
  nom_champ_moyenne2 += Nom(tstat_fin_,"%e");
  if ((mon_post.comprend_champ_post(nom_champ_moyenne)) && (mon_post.comprend_champ_post(nom_champ_moyenne2)))
    {
      const Champ_Generique_base& champ_stat_base = mon_post.get_champ_post(nom_champ_moyenne);
      const Operateur_Statistique_tps_base& operateur = ref_cast(Champ_Generique_Moyenne,champ_stat_base).Operateur_Statistique();
      const Op_Moyenne& op_moyenne = ref_cast(Op_Moyenne,operateur);
      Op_Correlation_.associer_op_stat(op_moyenne);
      const Champ_Generique_base& champ_stat_base2 = mon_post.get_champ_post(nom_champ_moyenne2);
      const Operateur_Statistique_tps_base& operateur2 = ref_cast(Champ_Generique_Moyenne,champ_stat_base2).Operateur_Statistique();
      const Op_Moyenne& op_moyenne2 = ref_cast(Op_Moyenne,operateur2);
      Op_Correlation_.associer_op_stat(op_moyenne2);
    }
  else
    {
      Cerr<<"The specification of the post-processing correlation field "<<finl;
      Cerr<<get_property("nom")[0]<<finl;
      Cerr<<"implies to specify before the corresponding "<<finl;
      Cerr<<"post-processing statistics average fields."<<finl;
      Cerr<<"Please, modify your data set to specify the post-processing statistics"<<finl;
      Cerr<<"average fields before (instead of after) the post-processing correlation field"<<finl;
      Cerr<<get_property("nom")[0]<<finl;
      exit();
    }
  Op_Correlation_.completer(Pb);
}
References Op_Correlation::associer(), Op_Correlation::associer_op_stat(), Cerr, Champ_Gen_de_Champs_Gen::completer(), Op_Correlation::completer(), Postraitement::comprend_champ_post(), Process::exit(), finl, Postraitement::get_champ_post(), Champ_Generique_base::get_property(), get_property(), Champ_Gen_de_Champs_Gen::get_ref_pb_base(), Champ_Gen_de_Champs_Gen::get_ref_zone_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Op_Correlation_, ref_cast, Champ_Generique_Statistiques_base::tstat_deb_, and Champ_Generique_Statistiques_base::tstat_fin_.
cree_instance()
Objet_U * Champ_Generique_Correlation::cree_instance () static
Definition at line 23 of file Champ_Generique_Correlation.cpp.
duplique()
int Champ_Generique_Correlation::duplique () const override virtual
Implements Objet_U.
Definition at line 23 of file Champ_Generique_Correlation.cpp.
get_champ()
const Champ_base & Champ_Generique_Correlation::get_champ (Champ & espace_stockage) const override virtual
Implements Champ_Generique_base.
Definition at line 93 of file Champ_Generique_Correlation.cpp.
{
  int nb_comp = integrale().valeur().nb_comp();
// Nature_du_champ nature_source = source.nature_du_champ();
// Pas completement exact car il y a le cas de la correlation vecteur-vecteur et dans
// ce cas c est un tenseur qui est manipule (la nature n est pas scalaire ou vectorielle)
  Nature_du_champ nature_source = (nb_comp==1)?scalaire:vectoriel;
  Champ_Fonc es_tmp;
  espace_stockage = creer_espace_stockage(nature_source,nb_comp,es_tmp);
  DoubleTab& tab_correlation = espace_stockage.valeurs();
  tab_correlation = Op_Correlation_.calculer_valeurs();
  tab_correlation.echange_espace_virtuel();
  return espace_stockage.valeur();
}
References Op_Correlation::calculer_valeurs(), Champ_Gen_de_Champs_Gen::creer_espace_stockage(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), integrale(), Field_base::nb_comp(), Op_Correlation_, scalaire, Deriv_Champ_base::valeur(), Deriv_Champ_Fonc_base::valeur(), Champ::valeurs(), and vectoriel.
get_directive_pour_discr()
const Motcle Champ_Generique_Correlation::get_directive_pour_discr () const override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 196 of file Champ_Generique_Correlation.cpp.
{
  Motcle directive;
  int support_corr = ref_cast(Integrale_tps_produit_champs,integrale()).get_support_different();
  if (support_corr==1)
    directive = "champ_elem";
  else
    directive = Op_Correlation_.la_moyenne_a().integrale().le_champ().valeur().get_directive_pour_discr();
  return directive;
}
References Champ_Generique_base::get_directive_pour_discr(), integrale(), Op_Moyenne::integrale(), Op_Correlation::la_moyenne_a(), Integrale_tps_Champ::le_champ(), Op_Correlation_, ref_cast, and Ref_Champ_Generique_base::valeur().
get_info()
const Type_info * Champ_Generique_Correlation::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 23 of file Champ_Generique_Correlation.cpp.
get_info_type_post()
int Champ_Generique_Correlation::get_info_type_post () const override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 187 of file Champ_Generique_Correlation.cpp.
{
  const Noms compo = get_property("composantes");
  if (compo.size()>1)
    return 1;
  else
    return 0;
}
References get_property(), and vect_impl::size().
get_property()
const Noms Champ_Generique_Correlation::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 109 of file Champ_Generique_Correlation.cpp.
{
// Creation des composantes serait a faire de maniere dynamique (Correlation_...)
  Motcles motcles(2);
  motcles[0] = "unites";
  motcles[1] = "composantes";
  int rang = motcles.search(query);
  switch(rang)
    {
    case 0:
      {
        const Noms noms_unites = integrale()->unites();
        return noms_unites;
        break;
      }
    case 1:
      {
// On fixe les composantes specifiques pour le Champ_Generique_Moyenne
// car dans Format_Post_Lml::ecrire_champ_lml() dans le cas d une localisation ELEM
// elles sont utilisees
        /*
          const Noms compo_cibles = get_source(0).get_property("composantes");
          int size = compo_cibles.size();
          Noms mots(size);
          for (int i=0; i<size; i++) {
          mots[i] = "Moyenne_";
          mots[i] += compo_cibles[i];
          }
          return mots;
          break;
        */
        /*
          const Noms source_compos = get_source(0).get_property("composantes");
          int nb_comp = source_compos.size();
          Noms compo(nb_comp);
          for (int i=0; i<nb_comp; i++) {
          Nom nume(i);
          compo[i] = nom_post_+nume;
          }
        */
        const Noms noms_compo = integrale()->noms_compo();
        return noms_compo;
        break;
      }
    }
  return Champ_Gen_de_Champs_Gen::get_property(query);
}
References Champ_Gen_de_Champs_Gen::get_property(), integrale(), and Motcles::search().
Referenced by completer(), and get_info_type_post().
info()
const Type_info * Champ_Generique_Correlation::info () static
Definition at line 23 of file Champ_Generique_Correlation.cpp.
integrale()
const Integrale_tps_Champ & Champ_Generique_Correlation::integrale () const inline override virtual
Implements Champ_Generique_Statistiques_base.
Definition at line 55 of file Champ_Generique_Correlation.h.
  {
    return Op_Correlation_.integrale();
  };
References Op_Correlation::integrale(), and Op_Correlation_.
Referenced by Postraitement::creer_champ_post_stat(), get_champ(), get_directive_pour_discr(), and get_property().
nommer_source()
void Champ_Generique_Correlation::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 169 of file Champ_Generique_Correlation.cpp.
{
  if (nom_post_=="??")
    {
      Nom nom_post_source, nom_champ_source_1, nom_champ_source_2;
      const Noms nom_1 = get_source(0).get_property("nom");
      const Noms nom_2 = get_source(1).get_property("nom");
      nom_champ_source_1 = nom_1[0];
      nom_champ_source_2 = nom_2[0];
      nom_post_source =  "Correlation_";
      nom_post_source += nom_champ_source_1;
      nom_post_source += "_";
      nom_post_source += nom_champ_source_2;
      nommer(nom_post_source);
    }
}
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
Operateur_Statistique() [1/2]
const Operateur_Statistique_tps_base & Champ_Generique_Correlation::Operateur_Statistique () const inline override virtual
Implements Champ_Generique_Statistiques_base.
Definition at line 74 of file Champ_Generique_Correlation.h.
{
  return Op_Correlation_;
}
References Op_Correlation_.
Operateur_Statistique() [2/2]
Operateur_Statistique_tps_base & Champ_Generique_Correlation::Operateur_Statistique () inline override virtual
Implements Champ_Generique_Statistiques_base.
Definition at line 79 of file Champ_Generique_Correlation.h.
{
  return Op_Correlation_;
}
References Op_Correlation_.
printOn()
Sortie & Champ_Generique_Correlation::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 25 of file Champ_Generique_Correlation.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Generique_Correlation::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 30 of file Champ_Generique_Correlation.cpp.
{
  Champ_Generique_Statistiques_base::readOn(s);
  return s ;
}
References Champ_Generique_Statistiques_base::readOn().
self_cast() [1/2]
const Champ_Generique_Correlation & Champ_Generique_Correlation::self_cast (const Objet_U & r) static
Definition at line 23 of file Champ_Generique_Correlation.cpp.
self_cast() [2/2]
Champ_Generique_Correlation & Champ_Generique_Correlation::self_cast (Objet_U & r) static
Definition at line 23 of file Champ_Generique_Correlation.cpp.
taille_memoire()
unsigned Champ_Generique_Correlation::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 23 of file Champ_Generique_Correlation.cpp.
temps()
double Champ_Generique_Correlation::temps () const inline override virtual
Implements Champ_Generique_Statistiques_base.
Definition at line 51 of file Champ_Generique_Correlation.h.
  {
    return Op_Correlation_.integrale().temps();
  };
References Op_Correlation::integrale(), Op_Correlation_, and Champ_Fonc::temps().
Member Data Documentation
info_obj
const Type_info Champ_Generique_Correlation::info_obj static
Definition at line 45 of file Champ_Generique_Correlation.h.
Op_Correlation_
Op_Correlation Champ_Generique_Correlation::Op_Correlation_ protected
Definition at line 71 of file Champ_Generique_Correlation.h.
Referenced by completer(), get_champ(), get_directive_pour_discr(), integrale(), Operateur_Statistique(), and temps().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Generique_Correlation.h
src/Kernel/Champs/Champ_Generique_Correlation.cpp