TRUST: Echange_interne_impose Class Reference
Echange_interne_impose Class Reference
Classe Echange_interne_impose:
Cette classe represente le cas particulier de la classe
Echange_externe_impose ou la paroi d'echange est interne au domaine.
La temperature exterieures definie dans Echange_externe_impose devient alors la
temperature situee de l'autre cote de la paroi interne.
Lorsque la température est au centre de l'élément (VDF par ex), on modifie aussi le h_gap
fourni pour prendre en compte la demi-maille située de l'autre côté de la paroi.
#include <Echange_interne_impose.h>
Public Member Functions
Echange_interne_impose ()
~Echange_interne_impose ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
void completer () override
NE FAIT RIEN
A surcharger dans les classes derivees.
void mettre_a_jour (double tps) override
Effectue une mise a jour en temps
des conditions aux limites.
Lors du premier appel des initialisations sont effectuees:
h_imp(0,0) = (rho(0,0)*Cp(0,0))
virtual void init ()
void verifie_ch_init_nb_comp () const override
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual double calcul_h_imp (const double h_gap, const double invLambda) const
const DoubleTab & inv_lambda () const
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
void associer_fr_dis_base (const Frontiere_dis_base &fr) override
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Public Member Functions inherited from Echange_externe_impose
Echange_externe_impose ()
~Echange_externe_impose ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Echange_impose_base
~Echange_impose_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double h_imp (int num) const
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
virtual double h_imp (int num, int k) const
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
virtual double T_ext (int num) const
Renvoie la valeur de la temperature imposee
sur la i-eme composante du champ de frontiere.
virtual double T_ext (int num, int k) const
Renvoie la valeur de la temperature imposee
sur la (i,j)-eme composante du champ de frontiere.
void mettre_a_jour (double) override
Effectue une mise a jour en temps
des conditions aux limites.
Lors du premier appel des initialisations sont effectuees:
h_imp(0,0) = (rho(0,0)*Cp(0,0))
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
int a_mettre_a_jour_ss_pas_dt () override
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
void associer_fr_dis_base (const Frontiere_dis_base &) override
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
virtual Champ_front & T_ext ()
Renvoie le champ T_ext de temperature imposee a la frontiere.
virtual const Champ_front & T_ext () const
Renvoie le champ T_ext de temperature imposee a la frontiere.
(version const)
virtual Champ_front & h_imp ()
Constructeur par defaut de la classe Echange_impose_base.
Ne construit rien, initialise le champ init a 0.
virtual const Champ_front & h_imp () const
int compatible_avec_eqn (const Equation_base &) const override
Verifie la compatibilite des conditions aux limites avec
l'equation passee en parametre.
Les conditions aux limites de type Ech_imp_base sont
compatibles avec des equations de type:
- Thermique
- indetermine.
int compatible_avec_discr (const Discretisation_base &) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void liste_faces_loi_paroi (IntTab &)
Public Member Functions inherited from Cond_lim_base
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Echange_interne_impose & self_cast (Objet_U &)
static const Echange_interne_impose & self_cast (const Objet_U &)
Static Public Member Functions inherited from Echange_externe_impose
static Objet_U * cree_instance ()
static const Type_info * info ()
static Echange_externe_impose & self_cast (Objet_U &)
static const Echange_externe_impose & self_cast (const Objet_U &)
Static Public Member Functions inherited from Echange_impose_base
static const Type_info * info ()
static Echange_impose_base & self_cast (Objet_U &)
static const Echange_impose_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Cond_lim_base
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Echange_externe_impose
static const Type_info info_obj
Static Public Attributes inherited from Echange_impose_base
static const Type_info info_obj
Static Public Attributes inherited from Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
virtual void update_inv_lambda ()
Protected Member Functions inherited from Echange_externe_impose
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
int compatible_avec_discr (const Discretisation_base &) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
void verifie_ch_init_nb_comp () const override
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une condition aux limite de type Echange_impose_base
a partir d'un flot d'entree.
On doit lire le coefficient d'echange global H_imp et la temperature
a la frontiere T_ext.
Format:
"h_imp" type_champ_front bloc de lecture champ
"T_ext" type_champ_front bloc de lecture champ.
Protected Member Functions inherited from Cond_lim_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_front h_gap_
Ref_Champ_Don lambda_ref_
reference to the field of thermic conductivity
DoubleTab inv_lambda_
= e/lambda on the internal boundary
Protected Attributes inherited from Echange_impose_base
Champ_front h_imp_
Protected Attributes inherited from Cond_lim_base
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Detailed Description
Classe Echange_interne_impose:
Cette classe represente le cas particulier de la classe
Echange_externe_impose ou la paroi d'echange est interne au domaine.
La temperature exterieures definie dans Echange_externe_impose devient alors la
temperature situee de l'autre cote de la paroi interne.
Lorsque la température est au centre de l'élément (VDF par ex), on modifie aussi le h_gap
fourni pour prendre en compte la demi-maille située de l'autre côté de la paroi.
Definition at line 35 of file Echange_interne_impose.h.
Constructor & Destructor Documentation
Echange_interne_impose()
Echange_interne_impose::Echange_interne_impose ()
Definition at line 28 of file Echange_interne_impose.cpp.
~Echange_interne_impose()
Echange_interne_impose::~Echange_interne_impose ()
Definition at line 28 of file Echange_interne_impose.cpp.
Member Function Documentation
associer_fr_dis_base()
void Echange_interne_impose::associer_fr_dis_base (const Frontiere_dis_base & fr) override virtual
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Reimplemented from Echange_impose_base.
Definition at line 134 of file Echange_interne_impose.cpp.
{
  if (h_gap_.non_nul())
    h_gap_.valeur().associer_fr_dis_base(fr);
  Echange_externe_impose::associer_fr_dis_base(fr);
}
References Champ_front_base::associer_fr_dis_base(), Echange_impose_base::associer_fr_dis_base(), h_gap_, O_U_Ptr::non_nul(), and Deriv_Champ_front_base::valeur().
avancer()
int Echange_interne_impose::avancer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Echange_impose_base.
Definition at line 121 of file Echange_interne_impose.cpp.
{
  if (h_gap_.non_nul())
    h_gap_.valeur().avancer(temps);
  return Echange_externe_impose::avancer(temps);
}
References Champ_front_base::avancer(), Echange_impose_base::avancer(), h_gap_, O_U_Ptr::non_nul(), and Deriv_Champ_front_base::valeur().
calcul_h_imp()
double Echange_interne_impose::calcul_h_imp (const double h_gap, const double invLambda) const virtual
< harmonic mean
Reimplemented in Echange_interne_parfait.
Definition at line 158 of file Echange_interne_impose.cpp.
{
  return 1./(1./h_gap + invLambda);      //!< harmonic mean
}
Referenced by mettre_a_jour().
changer_temps_futur()
void Echange_interne_impose::changer_temps_futur (double temps, int i) override virtual
Change le i-eme temps futur de la CL.
Reimplemented from Echange_impose_base.
Definition at line 115 of file Echange_interne_impose.cpp.
{
  if (h_gap_.non_nul())
    h_gap_.valeur().changer_temps_futur(temps,i);
  Echange_externe_impose::changer_temps_futur(temps,i);
}
References Champ_front_base::changer_temps_futur(), Echange_impose_base::changer_temps_futur(), h_gap_, O_U_Ptr::non_nul(), and Deriv_Champ_front_base::valeur().
completer()
void Echange_interne_impose::completer (void) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Cond_lim_base.
Definition at line 142 of file Echange_interne_impose.cpp.
{
  Nom nom_pb(zone_Cl_dis().equation().probleme().le_nom());
  Nom nom_bord(frontiere_dis().le_nom());
  lambda_ref_ = zone_Cl_dis().equation().probleme().milieu().conductivite();
  Champ_front_calc_interne& t_ext = ref_cast(Champ_front_calc_interne, T_ext().valeur());
  t_ext.creer(nom_pb, nom_bord, "temperature");
  const Front_VF& fvf = ref_cast(Front_VF, frontiere_dis());
  inv_lambda_.resize(fvf.nb_faces());
  Echange_externe_impose::completer();
}
References Cond_lim_base::completer(), Milieu_base::conductivite(), Champ_front_calc::creer(), MorEqn::equation(), Cond_lim_base::frontiere_dis(), inv_lambda_, lambda_ref_, Objet_U::le_nom(), Probleme_base::milieu(), Front_VF::nb_faces(), Equation_base::probleme(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Echange_impose_base::T_ext(), valeur(), and Cond_lim_base::zone_Cl_dis().
cree_instance()
Objet_U * Echange_interne_impose::cree_instance () static
Definition at line 28 of file Echange_interne_impose.cpp.
duplique()
int Echange_interne_impose::duplique () const override virtual
Reimplemented from Echange_externe_impose.
Reimplemented in Echange_interne_parfait.
Definition at line 28 of file Echange_interne_impose.cpp.
fixer_nb_valeurs_temporelles()
void Echange_interne_impose::fixer_nb_valeurs_temporelles (int nb_cases) override virtual
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
Reimplemented from Echange_impose_base.
Definition at line 108 of file Echange_interne_impose.cpp.
{
  if (h_gap_.non_nul())
    h_gap_.valeur().fixer_nb_valeurs_temporelles(nb_cases);
  Echange_externe_impose::fixer_nb_valeurs_temporelles(nb_cases);
}
References Champ_front_base::fixer_nb_valeurs_temporelles(), Echange_impose_base::fixer_nb_valeurs_temporelles(), h_gap_, O_U_Ptr::non_nul(), and Deriv_Champ_front_base::valeur().
get_info()
const Type_info * Echange_interne_impose::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Echange_externe_impose.
Reimplemented in Echange_interne_parfait.
Definition at line 28 of file Echange_interne_impose.cpp.
info()
const Type_info * Echange_interne_impose::info () static
Definition at line 28 of file Echange_interne_impose.cpp.
init()
void Echange_interne_impose::init () virtual
< preparation of T_ext
< won't be used anyway, just make sure we have a big enough array to store future values of h
Definition at line 88 of file Echange_interne_impose.cpp.
{
  le_champ_front.typer("Champ_front_calc_interne"); //!< preparation of T_ext
  EChaine e("Champ_front_fonc_xyz 1 1e-10");
  e >> h_imp_;        //!< won't be used anyway, just make sure we have a big enough array to store future values of h
}
References Echange_impose_base::h_imp_, Cond_lim_base::le_champ_front, and Deriv_::typer().
Referenced by readOn(), and Echange_interne_parfait::readOn().
initialiser()
int Echange_interne_impose::initialiser (double temps) override virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Echange_impose_base.
Definition at line 225 of file Echange_interne_impose.cpp.
{
  int ret = Echange_externe_impose::initialiser(temps);
  update_inv_lambda();
  return ret;
}
References Echange_impose_base::initialiser(), and update_inv_lambda().
inv_lambda()
const DoubleTab & Echange_interne_impose::inv_lambda () const inline
Definition at line 52 of file Echange_interne_impose.h.
  {
    return inv_lambda_;
  }
References inv_lambda_.
mettre_a_jour()
void Echange_interne_impose::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps
des conditions aux limites.
Lors du premier appel des initialisations sont effectuees:
h_imp(0,0) = (rho(0,0)*Cp(0,0))
< opposite face
< inv lambda from the opposite side
Reimplemented from Echange_impose_base.
Definition at line 188 of file Echange_interne_impose.cpp.
{
  Echange_externe_impose::mettre_a_jour(tps);
  h_gap_.mettre_a_jour(tps);
  update_inv_lambda();
  bool isVDF = sub_type(Zone_VDF, frontiere_dis().zone_dis());
  DoubleTab& h_impose = h_imp_.valeurs();
  DoubleTab& h_gap = h_gap_.valeurs();
// If VDF, fix h_imp to take into account half cell on the other side of the wall:
  if (isVDF)
    {
      const Champ_front_calc_interne& t_ext = ref_cast(Champ_front_calc_interne, T_ext().valeur());
      const IntTab& face_map = t_ext.face_map();
      const Front_VF& fvf = ref_cast(Front_VF, frontiere_dis());
      for (int numf=0; numf < fvf.nb_faces(); numf++)
        {
          int opp_face = face_map(numf);  //!< opposite face
          if (sub_type(Champ_front_uniforme, h_gap_.valeur()))
            h_impose(numf,0) = calcul_h_imp(h_gap(0,0), inv_lambda_(opp_face));  //!< inv lambda from the **opposite** side
          else
            h_impose(numf,0) = calcul_h_imp(h_gap(numf,0), inv_lambda_(opp_face));
        }
    }
  else
    {
      if (sub_type(Champ_front_uniforme, h_gap_.valeur()))
        h_impose = h_gap(0,0);
      else
        h_impose = h_gap;
    }
}
References calcul_h_imp(), Champ_front_calc_interne::face_map(), Cond_lim_base::frontiere_dis(), h_gap_, Echange_impose_base::h_imp_, inv_lambda_, Champ_front::mettre_a_jour(), Echange_impose_base::mettre_a_jour(), Front_VF::nb_faces(), ref_cast, sub_type, Echange_impose_base::T_ext(), update_inv_lambda(), Deriv_Champ_front_base::valeur(), valeur(), and Champ_front::valeurs().
printOn()
Sortie & Echange_interne_impose::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Echange_externe_impose.
Reimplemented in Echange_interne_parfait.
Definition at line 47 of file Echange_interne_impose.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Echange_interne_impose::readOn (Entree & s) override protected virtual
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Echange_externe_impose.
Reimplemented in Echange_interne_parfait.
Definition at line 68 of file Echange_interne_impose.cpp.
{
  Motcle motlu;
  Motcle motcle("h_gap");
  s >> motlu;
  if (motlu ==motcle)
    s >> h_gap_;
  else
    {
      Cerr << "Error when reading boundary condition with type Echange_interne_impose " << finl;
      Cerr << "We expected " << motcle << " instead of " <<  motlu << finl;
      exit();
    }
  init();
  return s;
}
References Cerr, Process::exit(), finl, h_gap_, and init().
reculer()
int Echange_interne_impose::reculer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Echange_impose_base.
Definition at line 128 of file Echange_interne_impose.cpp.
{
  if (h_gap_.non_nul())
    h_gap_.valeur().reculer(temps);
  return Echange_externe_impose::reculer(temps);
}
References h_gap_, O_U_Ptr::non_nul(), Champ_front_base::reculer(), Echange_impose_base::reculer(), and Deriv_Champ_front_base::valeur().
self_cast() [1/2]
const Echange_interne_impose & Echange_interne_impose::self_cast (const Objet_U & r) static
Definition at line 28 of file Echange_interne_impose.cpp.
self_cast() [2/2]
Echange_interne_impose & Echange_interne_impose::self_cast (Objet_U & r) static
Definition at line 28 of file Echange_interne_impose.cpp.
set_temps_defaut()
void Echange_interne_impose::set_temps_defaut (double temps) override virtual
Change le i-eme temps futur de la cl.
Reimplemented from Echange_impose_base.
Definition at line 102 of file Echange_interne_impose.cpp.
{
  if (h_gap_.non_nul())
    h_gap_.valeur().set_temps_defaut(temps);
  Echange_externe_impose::set_temps_defaut(temps);
}
References h_gap_, O_U_Ptr::non_nul(), Champ_front_base::set_temps_defaut(), Echange_impose_base::set_temps_defaut(), and Deriv_Champ_front_base::valeur().
taille_memoire()
unsigned Echange_interne_impose::taille_memoire () const override virtual
Reimplemented from Echange_externe_impose.
Reimplemented in Echange_interne_parfait.
Definition at line 28 of file Echange_interne_impose.cpp.
update_inv_lambda()
void Echange_interne_impose::update_inv_lambda () protected virtual
Definition at line 166 of file Echange_interne_impose.cpp.
{
  bool isVDF = sub_type(Zone_VDF, frontiere_dis().zone_dis());
  const Front_VF& fvf = ref_cast(Front_VF, frontiere_dis());
  inv_lambda_ = 0.0;
  if (isVDF)
    {
      DoubleTab& lambdas = lambda_ref_->valeurs();
      const Zone_VDF& zon = ref_cast(Zone_VDF, frontiere_dis().zone_dis());
      for (int numf=0; numf < fvf.nb_faces(); numf++)
        {
          int facei = fvf.num_face(numf);
          int vois0 = zon.face_voisins(facei, 0);
          int elem = (vois0 != -1) ? vois0 : zon.face_voisins(facei, 1);
          inv_lambda_(numf) = zon.dist_norm_bord(facei)/lambdas(elem, 0);
        }
    }
}
References Zone_VDF::dist_norm_bord(), Zone_VF::face_voisins(), Cond_lim_base::frontiere_dis(), inv_lambda_, lambda_ref_, Front_VF::nb_faces(), Front_VF::num_face(), ref_cast, sub_type, and Champ_Don::valeurs().
Referenced by initialiser(), and mettre_a_jour().
verifie_ch_init_nb_comp()
void Echange_interne_impose::verifie_ch_init_nb_comp () const override virtual
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
Reimplemented from Echange_externe_impose.
Definition at line 98 of file Echange_interne_impose.cpp.
{
}
Member Data Documentation
h_gap_
Champ_front Echange_interne_impose::h_gap_ protected
Definition at line 70 of file Echange_interne_impose.h.
Referenced by associer_fr_dis_base(), avancer(), changer_temps_futur(), fixer_nb_valeurs_temporelles(), mettre_a_jour(), readOn(), Echange_interne_parfait::readOn(), reculer(), and set_temps_defaut().
info_obj
const Type_info Echange_interne_impose::info_obj static
Definition at line 38 of file Echange_interne_impose.h.
inv_lambda_
DoubleTab Echange_interne_impose::inv_lambda_ protected
= e/lambda on the internal boundary
Definition at line 72 of file Echange_interne_impose.h.
Referenced by completer(), inv_lambda(), mettre_a_jour(), and update_inv_lambda().
lambda_ref_
Ref_Champ_Don Echange_interne_impose::lambda_ref_ protected
reference to the field of thermic conductivity
Definition at line 71 of file Echange_interne_impose.h.
Referenced by completer(), and update_inv_lambda().
The documentation for this class was generated from the following files:
src/VDF/Cond_Lim/Echange_interne_impose.h
src/VDF/Cond_Lim/Echange_interne_impose.cpp