TRUST: Zone Class Reference
Zone Class Reference
classe Zone
Une Zone est un maillage compose d'un ensemble d'elements geometriques
de meme type. Les differents types d'elements sont des objets de
classes derivees de Elem_geom_base.
Une zone a un domaine associe (chaque Zone peut referencer son domaine)
elle a aussi un Nom.
Une zone est constituee d'elements, de bords, de bords periodiques,
de joints, de raccords et de face internes.
#include <Zone.h>
Public Member Functions
Zone ()
~Zone ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Elem_geom & type_elem () const
Renvoie un element geometrique du type de ceux
qui constituent la zone.
(version const)
Elem_geom & type_elem ()
Renvoie un element geometrique du type de ceux
qui constituent la zone.
void typer (const Nom &)
Type les elements de la zone avec le
nom passe en parametre. Et associe le type
d'element a la zone.
int nb_elem () const
Renvoie le nombre d'elements de la zone.
int nb_elem_tot () const
Renvoie le nombre total d'elements de la zone.
int nb_aretes () const
renvoie le nombre d'aretes reelles.
int nb_aretes_tot () const
renvoie le nombre d'aretes total (reelles+virtuelles).
int nb_som () const
Renvoie le nombre de sommets de la zone.
int nb_som_tot () const
Renvoie le nombre total de sommets de la zone.
i.e. le nombre de sommets reels et virtuels
sur le processeur courant.
int nb_som_elem () const
Renvoie le nombre de sommets des elements geometriques
constituants la zone. Tous les elements de la zone etant
du meme type ils ont tous le meme nombre de sommets
qui est le nombre de sommet du type des elements geometriques
de la zone.
int nb_faces_elem (int=0) const
Renvoie le nombre de face de type i
des elements geometriques constituants la zone.
Ex: les objets de la classe Prisme ont 2 types
de faces: triangle ou quadrangle.
int sommet_elem (int, int) const
Renvoie le numero (global) j-ieme sommet du i-ieme element.
const Nom & le_nom () const override
Renvoie le nom de la zone.
void nommer (const Nom &) override
Donne un nom a la zone.
const Domaine & domaine () const
Renvoie le domaine dont la zone fait partie.
(version const)
Domaine & domaine ()
Renvoie le domaine dont la zone fait partie.
void fixer_premieres_faces_frontiere ()
ArrOfInt & chercher_elements (const DoubleTab &, ArrOfInt &, int reel=0) const
ArrOfInt & chercher_elements (const DoubleVect &, ArrOfInt &, int reel=0) const
Recherche des elements contenant les points dont les
coordonnees sont specifiees.
ArrOfInt & indice_elements (const IntTab &, ArrOfInt &, int reel=0) const
che les numeros (indices) des elements contenants les sommets
specifies par le parametre "sommets".
Utilise:
ArrOfInt& Zone::chercher_elements(const DoubleTab&,ArrOfInt&) const
int chercher_elements (double x, double y=0, double z=0, int reel=0) const
Renvoie le rang de l'element contenant
le point dont les coordonnees sont specifiees.
ArrOfInt & chercher_sommets (const DoubleTab &, ArrOfInt &, int reel=0) const
int chercher_sommets (double x, double y=0, double z=0, int reel=0) const
ArrOfInt & chercher_aretes (const DoubleTab &, ArrOfInt &, int reel=0) const
virtual void associer_domaine (const Domaine &)
Specifie le domaine dont la zone fait partie.
void init_faces_virt_bord (const MD_Vector &md_vect_faces, MD_Vector &md_vect_faces_bord)
Methode appelee par Zone_VF::discretiser().
Construction du descripteur pour les faces de bord
Remplissage de ind_faces_virt_bord et des tableaux get_faces_virt() des frontieres
a partir du descripteur parallele des faces.
Note B.M.: le fait d'avoir mis les faces dans la Zone_VF, les aretes dans la Zone,
certaines parties des proprites des faces de bord dans la Zone_VF et d'autres dans la Zone
fait que l'initialisation passe par des chemins un peu tordus... il faudra nettoyer ca.
void calculer_centres_gravite (DoubleTab &) const
Calcule les centres de gravites des elements de la zone.
void calculer_centres_gravite_aretes (DoubleTab &) const
Calcule les centres de gravites des aretes de la zone.
void creer_aretes ()
void calculer_volumes (DoubleVect &, DoubleVect &) const
Calcule les volumes des elements de la zone.
void calculer_mon_centre_de_gravite (ArrOfDouble &)
Calcule le centre de gravite de la zone.
IntTab & les_elems ()
Renvoie le tableau des sommets des elements.
const IntTab & les_elems () const
Renvoie le tableau des sommets des elements<br>(version const)
int arete_sommets (int i, int j) const
renvoie le numero du jeme sommet de la ieme arete.
int elem_aretes (int i, int j) const
renvoie le numero de la jeme arete du ieme element.
const IntTab & aretes_som () const
renvoie le tableau de connectivite aretes/sommets.
const IntTab & elem_aretes () const
renvoie le tableau de connectivite elements/aretes.
IntTab & set_aretes_som ()
IntTab & set_elem_aretes ()
int nb_bords () const
Renvoie le nombre de bords de la zone.
int nb_joints () const
Renvoie le nombre de joints de la zone.
int nb_raccords () const
Renvoie le nombre de raccords de la zone.
int nb_frontieres_internes () const
Renvoie le nombre de frontieres internes de la zone.
int nb_front_Cl () const
Renvoie le nombre de bords
+ le nombre de raccords
+ le nombre de faces frontieres internes.
int nb_faces_bord () const
Renvoie le nombre de faces qui sont des bords.
int nb_faces_joint () const
Renvoie le nombre de joints de la zone.
int nb_faces_raccord () const
Renvoie le nombre de raccords de la zone.
int nb_faces_int () const
Renvoie le nombre de face internes de la zone.
int nb_faces_bord (int) const
Renvoie le nombre de faces du i-ieme bord.
int nb_faces_joint (int) const
Renvoie le nombre de faces du i-ieme joint.
int nb_faces_raccord (int) const
Renvoie le nombre de faces du i-ieme raccord.
int nb_faces_int (int) const
Renvoie le nombre de faces de la i-ieme
liste de faces internes.
int nb_faces_frontiere (Type_Face type) const
Renvoie le nombre de faces frontiere de la zone
du type specifie.
C'est la somme des nombres de bords, de raccords
et de faces internes du type specifie.
int nb_faces_frontiere () const
Renvoie le nombre de faces frontiere de la zone.
C'est la somme des nombres de bords, de raccords et de faces internes.
const Bord & bord (int) const
Renvoie le i-ieme bord de la zone<br>(version const)
Bord & bord (int)
Renvoie le i-ieme bord de la zone.
const Joint & joint (int) const
Renvoie le i-ieme joint de la zone<br>(version const)
Joint & joint (int)
Renvoie le i-ieme joint de la zone.
Joint & joint_of_pe (int)
const Joint & joint_of_pe (int) const
Renvoie le joint correspondant au PE specifie.
(PE = Processeur Elementaire, ou numero de processus)
Un joint est une frontiere entre 2 PE.
const Raccord & raccord (int) const
Renvoie le i-ieme raccord de la zone<br>(version const)
Raccord & raccord (int)
Renvoie le i-ieme raccord de la zone.
const Faces_Interne & faces_interne (int) const
Renvoie les i-ieme faces internes de la zone<br>(version const)
Faces_Interne & faces_interne (int)
Renvoie les i-ieme faces internes de la zone.
const Bord & bord (const Nom &) const
Renvoie le bord dont le nom est specifie.
(version const)
Bord & bord (const Nom &)
Renvoie le bord dont le nom est specifie.
const Frontiere & frontiere (int i) const
Frontiere & frontiere (int i)
int rang_frontiere (const Nom &) const
const Frontiere & frontiere (const Nom &) const
Frontiere & frontiere (const Nom &)
const Joint & joint (const Nom &) const
Renvoie le joint dont le nom est specifie<br>(version const)
Joint & joint (const Nom &)
Renvoie le joint dont le nom est specifie.
const Raccord & raccord (const Nom &) const
Renvoie le raccord dont le nom est specifie<br>(version const)
Raccord & raccord (const Nom &)
Renvoie le raccord dont le nom est specifie.
const Faces_Interne & faces_interne (const Nom &) const
Renvoie les faces_internes dont le nom est specifie<br>(version const)
Faces_Interne & faces_interne (const Nom &)
Renvoie les faces_internes dont le nom est specifie.
const Bords & faces_bord () const
Renvoie la liste des bords de la zone.
(version const)
Bords & faces_bord ()
Renvoie la liste des bords de la zone.
const Joints & faces_joint () const
Renvoie la liste des joints de la zone.
(version const)
Joints & faces_joint ()
Renvoie la liste des joints de la zone.
const Raccords & faces_raccord () const
Renvoie la liste des racoords de la zone.
(version const)
Raccords & faces_raccord ()
Renvoie la liste des racoords de la zone.
const Faces_Internes & faces_int () const
Renvoie la liste des faces internes de la zone.
(version const)
Faces_Internes & faces_int ()
Renvoie la liste des faces internes de la zone.
void renum (const IntVect &)
Renumerotation des noeuds:
Le noeud de numero k devient le noeud de numero Les_Nums[k].
void renum_joint_common_items (const IntVect &Les_Nums, const int elem_offset)
Renumerotation des noeuds et des elements presents dans les items communs des joints
Le noeud de numero k devient le noeud de numero Les_Nums[k]
l'element de numero e devient l'element de numero e+elem_offset.
void reordonner ()
Reordonne les elements suivant la convention
employe par Trio-U.
int face_interne_conjuguee (int) const
Renvoie -1 si face n'est pas une face interne
Renvoie le numero de la face dupliquee sinon.
int comprimer ()
Concatene les bords de meme nom et ceci pour:
les bords, les bords periodiques et les faces internes.
int comprimer_joints ()
Concatene les joints de meme nom.
void ecrire_noms_bords (Sortie &) const
Ecriture des noms des bords sur un flot de sortie
Ecrit les noms des: bords, bords periodiques, raccords
et faces internes.
double epsilon () const
void associer_Bords_a_imprimer (List_Nom)
void associer_Bords_a_imprimer_sum (List_Nom)
Entree & Lire_Bords_a_imprimer (Entree &s)
Entree & Lire_Bords_a_imprimer_sum (Entree &s)
const List_Nom & Bords_a_imprimer () const
const List_Nom & Bords_a_imprimer_sum () const
int Moments_a_imprimer () const
int & Moments_a_imprimer ()
const ArrOfDouble & cg_moments () const
ArrOfDouble & cg_moments ()
void exporter_mon_centre_de_gravite (ArrOfDouble c)
double volume_total () const
int nb_faces_bord (Type_Face type) const
Renvoie le nombre de faces du type specifie.
int nb_faces_joint (Type_Face type) const
Renvoie le nombre de joints du type specifie.
int nb_faces_raccord (Type_Face type) const
Renvoie le nombre de raccords du type specifie.
int nb_faces_int (Type_Face type) const
Renvoie le nombre de faces interieures du type specifie.
int rang_elem_depuis (const DoubleTab &, const ArrOfInt &, ArrOfInt &) const
void rang_elems_sommet (ArrOfInt &, double x, double y=0, double z=0) const
void invalide_octree ()
const OctreeRoot & construit_octree () const
const OctreeRoot & construit_octree (int &) const
construction de l'octree si pas deja fait
const ArrOfInt & ind_faces_virt_bord () const
void construire_elem_virt_pe_num ()
void construire_elem_virt_pe_num (IntTab &elem_virt_pe_num_cpy) const
const IntTab & elem_virt_pe_num () const
virtual void creer_tableau_elements (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
creation d'un tableau parallele de valeurs aux elements.
Voir MD_Vector_tools::creer_tableau_distribue()
virtual const MD_Vector & md_vector_elements () const
renvoie le descripteur parallele des tableaux aux elements de la zone
void read_zone (Entree &s)
read zone from the input stream
void check_zone ()
associate the read objects to the zone
and check that the reading objects are coherent
void correct_type_of_borders_after_merge ()
Correcting type of borders if they were empty before merge (ie equal to vide_0D)
difference with corriger_type is that we don't want to delete faces inside borders afterwards.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone & self_cast (Objet_U &)
static const Zone & self_cast (const Objet_U &)
static int identifie_item_unique (IntList &item_possible, DoubleTab &coord_possible, const DoubleVect &coord_ref)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit la Zone sur un flot de sortie.
On ecrit le nom, le type des elements, les elements
et les bords, les bords periodiques, les joints, les
raccords et les faces internes.
Entree & readOn (Entree &) override
Lit les objets constituant une Zone
a partir d'un flot d'entree. Une fois les objets
lus on les associe a la zone.
void duplique_faces_internes ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom nom
Ref_Domaine le_domaine
Elem_geom elem
IntTab mes_elems
IntTab Aretes_som
IntTab Elem_Aretes
Bords mes_faces_bord
Raccords mes_faces_raccord
Faces_Internes mes_faces_int
Joints mes_faces_joint
ArrOfInt ind_faces_virt_bord_
contient les indices des faces virtuelles de bord
Deriv_OctreeRoot deriv_octree_
ArrOfDouble cg_moments_
IntTab elem_virt_pe_num_
List_Nom Bords_a_imprimer_
List_Nom Bords_a_imprimer_sum_
int Moments_a_imprimer_
Private Attributes
double volume_total_
DoubleTabs cached_positions_
ArrsOfInt cached_elements_
Detailed Description
classe Zone
Une Zone est un maillage compose d'un ensemble d'elements geometriques
de meme type. Les differents types d'elements sont des objets de
classes derivees de Elem_geom_base.
Une zone a un domaine associe (chaque Zone peut referencer son domaine)
elle a aussi un Nom.
Une zone est constituee d'elements, de bords, de bords periodiques,
de joints, de raccords et de face internes.
Definition at line 49 of file Zone.h.
Constructor & Destructor Documentation
Zone()
Zone::Zone ()
< pas encore calcule
Definition at line 26 of file Zone.cpp.
           :
  Moments_a_imprimer_(0)
{
  volume_total_ = -1.; //!< pas encore calcule
}
References volume_total_.
~Zone()
Zone::~Zone ()
Definition at line 24 of file Zone.cpp.
Member Function Documentation
arete_sommets()
int Zone::arete_sommets (int i, int j) const inline
renvoie le numero du jeme sommet de la ieme arete.
Definition at line 1266 of file Zone.h.
{
  return Aretes_som(i, j);
}
References Aretes_som.
aretes_som()
const IntTab & Zone::aretes_som () const inline
renvoie le tableau de connectivite aretes/sommets.
Definition at line 1282 of file Zone.h.
{
  return Aretes_som;
}
References Aretes_som.
Referenced by Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), assembler(), calculer_liste_complete_aretes_joint(), Zone_VEF_PreP1b::construire_ok_arete(), Zone_VEF_PreP1b::construire_renum_arete_perio(), contribuer_matrice_NeumannP0Pa(), contribuer_matrice_NeumannP1Pa(), contribuer_matrice_NeumannPaPa(), contribuer_matrice_SymetrieP1Pa(), contribuer_matrice_SymetriePaPa(), contribuer_matriceP0Pa(), contribuer_matriceP1Pa(), contribuer_matricePaPa(), corriger(), Zone_PolyMAC::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), Op_Grad_VEF_P1B_Face::impr(), Zone_PolyMAC::M1(), OctreeRoot::rang_arete(), second_membre(), update_matrice_NeumannP0Pa(), update_matrice_NeumannP1Pa(), update_matrice_NeumannPaPa(), update_matrice_SymetrieP1Pa(), update_matrice_SymetriePaPa(), update_matriceP0Pa(), update_matriceP1Pa(), update_matricePaPa(), Zone_VEF_PreP1b::verifie_ok_arete(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), and Zone_PolyMAC::W1().
associer_Bords_a_imprimer()
void Zone::associer_Bords_a_imprimer (List_Nom liste) inline
Definition at line 268 of file Zone.h.
{
  Bords_a_imprimer_=liste;
}
References Bords_a_imprimer_.
associer_Bords_a_imprimer_sum()
void Zone::associer_Bords_a_imprimer_sum (List_Nom liste) inline
Definition at line 273 of file Zone.h.
{
  Bords_a_imprimer_sum_=liste;
}
References Bords_a_imprimer_sum_.
associer_domaine()
void Zone::associer_domaine (const Domaine & un_domaine) virtual
Specifie le domaine dont la zone fait partie.
Reimplemented in Pave.
Definition at line 482 of file Zone.cpp.
{
  le_domaine=un_domaine;
}
References le_domaine.
Referenced by Pave::associer_domaine(), Champ_Generique_Extraction::completer(), DomaineCutter::construire_sous_domaine(), convert_domain_to_Domaine(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), Extraire_surface::extraire_surface(), ExtrudeBord::extruder_hexa_old(), Interprete_geometrique_base::interpreter(), MaillerParallel::interpreter(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extruder_en3::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), Mailler::interpreter_(), and Scatter::mergeDomains().
bord() [1/4]
Bord & Zone::bord (const Nom & nom_) inline
Renvoie le bord dont le nom est specifie.
Returns
Bord&
Signification: le bord dont le nom est specifie
Contraintes:
Definition at line 692 of file Zone.h.
{
  return mes_faces_bord(nom_);
}
References mes_faces_bord.
bord() [2/4]
const Bord & Zone::bord (const Nom & nom_) const inline
Renvoie le bord dont le nom est specifie.
(version const)
Returns
Bord&
Signification: le bord dont le nom est specifie
Contraintes: reference constante
Definition at line 673 of file Zone.h.
{
  return mes_faces_bord(nom_);
}
References mes_faces_bord.
bord() [3/4]
Bord & Zone::bord (int i) inline
Renvoie le i-ieme bord de la zone.
Returns
Bord&
Signification: le i-ieme bord de la zone
Contraintes:
Definition at line 882 of file Zone.h.
{
  return mes_faces_bord(i);
}
References mes_faces_bord.
bord() [4/4]
const Bord & Zone::bord (int i) const inline
Renvoie le i-ieme bord de la zone<br>(version const)
Returns
Bord&
Signification: le i-ieme bord de la zone
Contraintes: reference constante
Definition at line 829 of file Zone.h.
{
  return mes_faces_bord(i);
}
References mes_faces_bord.
Referenced by Partitionneur_base::calculer_graphe_connexions_periodiques(), Partitionneur_Tranche::chercher_direction_perio(), Scatter::corriger_espace_distant_elements_perio(), Partitionneur_base::corriger_multiperiodique(), Partitionneur_base::corriger_sommets_bord(), DecoupeBord::Decouper(), Zone_VF::discretiser(), Postraiter_domaine::ecrire(), ExtrudeBord::extruder_bord(), MaillerParallel::interpreter(), Modif_bord_to_raccord::interpreter_(), SupprimeBord::interpreter_(), TroisDto2D::interpreter_(), Corriger_frontiere_periodique::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Scatter::lire_domaine(), OrienteFacesBord::oriente_faces_bord(), RegroupeBord::regroupe_bord(), Zone_VF::remplir_face_numero_bord(), and Reordonner_faces_periodiques::renum_som_perio().
Bords_a_imprimer()
const List_Nom & Zone::Bords_a_imprimer () const inline
Definition at line 258 of file Zone.h.
{
  return Bords_a_imprimer_;
}
References Bords_a_imprimer_.
Referenced by Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), Op_Div_PolyMAC::impr(), Op_Div_PolyMAC_P0::impr(), T_It_VDF_Elem< _TYPE_ >::impr(), T_It_VDF_Face< _TYPE_ >::impr(), Op_Grad_VDF_Face::impr(), and Op_Div_VEF_Elem::impr().
Bords_a_imprimer_sum()
const List_Nom & Zone::Bords_a_imprimer_sum () const inline
Definition at line 263 of file Zone.h.
{
  return Bords_a_imprimer_sum_;
}
References Bords_a_imprimer_sum_.
Referenced by Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), T_It_VDF_Face< _TYPE_ >::impr(), Op_Grad_VDF_Face::impr(), and Operateur_base::ouvrir_fichier().
calculer_centres_gravite()
void Zone::calculer_centres_gravite (DoubleTab & xp) const inline
Calcule les centres de gravites des elements de la zone.
Definition at line 653 of file Zone.h.
{
  elem.calculer_centres_gravite(xp);
}
References Elem_geom::calculer_centres_gravite(), and elem.
Referenced by calculer_mon_centre_de_gravite(), Champ_base::calculer_valeurs_elem_compo_post(), Champ_base::calculer_valeurs_elem_post(), Partitionneur_Partition::construire_partition(), Partitionneur_Sous_Zones::construire_partition(), Partitionneur_Tranche::construire_partition(), Zone_VF::discretiser(), Champ_Generique_Transformation::get_champ(), Champ_implementation_P0::imprime_P0(), Moyenne_volumique::interpreter(), Distanceparoi::interpreter_(), VerifierCoin::interpreter_(), Perte_Charge_Singuliere::lire_surfaces(), Postraitement::postraiter_tableau(), Champ_P0_VDF::remplir_coord_noeuds(), and Champ_implementation_P0::remplir_coord_noeuds().
calculer_centres_gravite_aretes()
void Zone::calculer_centres_gravite_aretes (DoubleTab & xa) const
Calcule les centres de gravites des aretes de la zone.
Definition at line 1532 of file Zone.cpp.
{
  const DoubleTab& coord = domaine().coord_sommets();
// Calcule les centres de gravite des aretes reelles seulement
  xa.resize(nb_aretes(),dimension);
  for (int i=0; i<nb_aretes(); i++)
    for (int j=0; j<dimension; j++)
      xa(i,j) = 0.5*(coord(Aretes_som(i,0),j)+coord(Aretes_som(i,1),j));
}
References Aretes_som, Domaine::coord_sommets(), Objet_U::dimension, domaine(), nb_aretes(), and TRUSTTab< _TYPE_ >::resize().
calculer_mon_centre_de_gravite()
void Zone::calculer_mon_centre_de_gravite (ArrOfDouble & c)
Calcule le centre de gravite de la zone.
Definition at line 1456 of file Zone.cpp.
{
  c=0;
// Volumes computed cause stored in Zone_VF and so not available in Zone...
  DoubleVect volumes;
  DoubleVect inverse_volumes;
  calculer_volumes(volumes,inverse_volumes);
  DoubleTab xp;
  calculer_centres_gravite(xp);
  double volume=0;
  for (int i=0; i<nb_elem(); i++)
    for (int j=0; j<dimension; j++)
      {
        c[j]+=xp(i,j)*volumes(i);
        volume+=volumes(i);
      }
// Cas de Zone vide:
  if (volume>0)
    c/=volume;
  cg_moments_=c;
  volume_total_ = mp_somme_vect(volumes);
}
References calculer_centres_gravite(), calculer_volumes(), cg_moments_, Objet_U::dimension, mp_somme_vect(), nb_elem(), and volume_total_.
Referenced by Zone_VF::discretiser(), and Calculer_Moments::interpreter_().
calculer_volumes()
void Zone::calculer_volumes (DoubleVect & volumes, DoubleVect & inverse_volumes) const
Calcule les volumes des elements de la zone.
< Dimensionne et calcule le DoubleVect volumes Check and fill inverse_volumes
Definition at line 1494 of file Zone.cpp.
{
  if (!volumes.get_md_vector().non_nul())
    creer_tableau_elements(volumes, Array_base::NOCOPY_NOINIT);
  elem.calculer_volumes(volumes); //!< Dimensionne et calcule le DoubleVect volumes Check and fill inverse_volumes
//
  if (!inverse_volumes.get_md_vector().non_nul())
    creer_tableau_elements(inverse_volumes, Array_base::NOCOPY_NOINIT);
  int size = volumes.size_totale();
  for (int i=0; i<size; i++)
    {
      double v = volumes(i);
      if (v<=0.)
        {
          Cerr << "Volume[" << i << "]=" << v << finl;
          Cerr << "Several volumes of the mesh are not positive." << finl;
          Cerr << "Something is wrong in the mesh..." << finl;
          exit();
        }
      inverse_volumes(i)=1./v;
    }
}
References Elem_geom::calculer_volumes(), Cerr, creer_tableau_elements(), elem, Process::exit(), finl, TRUSTVect< _TYPE_ >::get_md_vector(), Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), and TRUSTVect< _TYPE_ >::size_totale().
Referenced by calculer_mon_centre_de_gravite(), Zone_VF::discretiser(), Domaine_dis::discretiser(), and Domaine::imprimer().
cg_moments() [1/2]
ArrOfDouble & Zone::cg_moments () inline
Definition at line 171 of file Zone.h.
  {
    return cg_moments_;
  };
References cg_moments_.
cg_moments() [2/2]
const ArrOfDouble & Zone::cg_moments () const inline
Definition at line 167 of file Zone.h.
  {
    return cg_moments_;
  };
References cg_moments_.
Referenced by Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), T_It_VDF_Face< _TYPE_ >::impr(), and Op_Grad_VDF_Face::impr().
check_zone()
void Zone::check_zone ()
associate the read objects to the zone
and check that the reading objects are coherent
Definition at line 151 of file Zone.cpp.
{
// remplacer Faces::vide_0D par le bon type pour les procs qui n'ont pas de faces de bord:
  {
    int i;
    int n = nb_front_Cl();
    for (i = 0; i < n; i++)
      {
        corriger_type(frontiere(i).faces(),type_elem().valeur());
      }
  }
  if (mes_faces_bord.size()==0 && mes_faces_raccord.size()==0 && Process::nproc()==1)
    {
      Cerr << "Warning, the reread zone " << nom
           << " has no defined boundaries (none boundary or connector)." << finl;
    }
  mes_faces_bord.associer_zone(*this);
  mes_faces_joint.associer_zone(*this);
  mes_faces_raccord.associer_zone(*this);
  mes_faces_int.associer_zone(*this);
  elem.associer_zone(*this);
  fixer_premieres_faces_frontiere();
  const int nbelem = mp_sum(mes_elems.dimension(0));
  Cerr << "  Number of elements: " << nbelem << finl;
// Verifications sanitaires:
// On doit avoir le meme nombre de frontieres et les memes noms sur tous les procs
  check_frontiere(mes_faces_bord, "(Bord)");
  check_frontiere(mes_faces_raccord, "(Raccord)");
  check_frontiere(mes_faces_int, "(Face_Interne)");
}
References Bords::associer_zone(), Elem_geom::associer_zone(), Faces_Internes::associer_zone(), Joints::associer_zone(), Raccords::associer_zone(), Cerr, check_frontiere(), corriger_type(), TRUSTTab< _TYPE_ >::dimension(), elem, finl, fixer_premieres_faces_frontiere(), frontiere(), mes_elems, mes_faces_bord, mes_faces_int, mes_faces_joint, mes_faces_raccord, Process::mp_sum(), nb_front_Cl(), nom, Process::nproc(), liste::size(), type_elem(), and valeur().
Referenced by Scatter::lire_domaine(), and readOn().
chercher_aretes()
ArrOfInt & Zone::chercher_aretes (const DoubleTab & pos, ArrOfInt & aretes, int reel = 0) const
Returns
ArrOfInt& aretes
Signification: Liste des aretes trouvees
Contraintes:
Definition at line 1255 of file Zone.cpp.
{
  const OctreeRoot& octree = construit_octree(reel);
  octree.rang_arete(pos, aretes);
  return aretes;
}
References construit_octree(), and OctreeRoot::rang_arete().
Referenced by calculer_liste_complete_aretes_joint().
chercher_elements() [1/3]
ArrOfInt & Zone::chercher_elements (const DoubleTab & positions, ArrOfInt & elements, int reel = 0) const
< Recherche dans le cache:
< 10Mo
Definition at line 353 of file Zone.cpp.
{
  bool set_cache = false;
// PL: On devrait faire un appel a chercher_elements(x,y,z,elem) si positions.dimension(0)=1 ...
  if (!domaine().deformable() && positions.dimension(0)>1)
    {
      set_cache = true;
      if (!deriv_octree_.non_nul() || !deriv_octree_.valeur().construit())
        {
// Vide le cache
          cached_elements_.reset();
          cached_positions_.reset();
        }
      else //!< Recherche dans le cache:
        for (int i = 0; i < cached_positions_.size(); i++)
          if (sameDoubleTab(positions, cached_positions_[i]))
            {
              elements.resize_tab(cached_positions_[i].dimension(0), ArrOfInt::NOCOPY_NOINIT);
              elements = cached_elements_[i];
              /*
              //Cerr << "Reuse " << i << "th array cached in memory for Zone::chercher_elements(...): " << finl;
              if (i!=0)
                {
                  // Permute pour avoir le tableau en premier
                  cached_elements_[i].resize_tab(cached_positions_[0].dimension(0), ArrOfInt::NOCOPY_NOINIT);
                  cached_elements_[i] = cached_elements_[0];
                  cached_elements_[0].resize_tab(cached_positions_[i].dimension(0), ArrOfInt::NOCOPY_NOINIT);
                  cached_elements_[0] = elements;
                  DoubleTab tmp(cached_positions_[i]);
                  cached_positions_[i] = cached_positions_[0];
                  cached_positions_[0] = tmp;
                }
                */
              return elements;
            }
    }
  const OctreeRoot& octree = construit_octree(reel);
  int sz=positions.dimension(0);
  const int dim = positions.dimension(1);
// resize_tab est virtuelle, si c'est un Vect ou un Tab elle appelle le
// resize de la classe derivee:
  elements.resize_tab(sz, ArrOfInt::NOCOPY_NOINIT);
  double x, y=0, z=0;
  for (int i=0; i<sz; i++)
    {
      x = positions(i,0);
      if (dim > 1) y = positions(i,1);
      if (dim > 2) z = positions(i,2);
      elements[i] = octree.rang_elem(x, y, z);
    }
  if (set_cache)
    {
// Met en cache
      cached_positions_.add(positions);
      cached_elements_.add(elements);
      cached_memory += positions.size_array() * sizeof(double);
      cached_memory += elements.size_array() * sizeof(int);
      if (cached_memory>1e7)   //!< 10Mo
        {
          Cerr << 2 * cached_positions_.size() << " arrays cached in memory for Zone::chercher_elements(...): ";
          if (cached_memory < 1e6)
            Cerr << int(cached_memory / 1024) << " KBytes" << finl;
          else if (cached_memory < 1e9)
            Cerr << int(cached_memory / 1024 / 1024) << " MBytes" << finl;
          else
            Cerr << int(cached_memory / 1024 / 1024 / 1024) << " GBytes" << finl;
        }
    }
  return elements;
}
References TRUST_Vector< _TRUST_TABL_, _TYPE_ >::add(), cached_elements_, cached_memory, cached_positions_, Cerr, OctreeRoot::construit(), construit_octree(), deriv_octree_, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, domaine(), finl, Array_base::NOCOPY_NOINIT, O_U_Ptr::non_nul(), OctreeRoot::rang_elem(), vect_impl::reset(), TRUSTArray< _TYPE_ >::resize_tab(), sameDoubleTab(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), and Deriv_OctreeRoot::valeur().
Referenced by chercher_elements(), Terme_Source_Rappel_T_VEF_Face::completer(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Champ_front_contact_VEF::connectivity_failed(), Partitionneur_Sous_Zones::construire_partition(), Tetraedriser_homogene_fin::creer_sommet(), creer_sommet(), Zone_VDF::genere_aretes(), indice_elements(), Sonde::initialiser(), Sonde_Int::initialiser(), Champ_front_lu::initialiser(), Distanceparoi::interpreter_(), Extraire_plan::interpreter_(), OrienteFacesBord::oriente_faces_bord(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), Champ_Don_lu::readOn(), Champ_implementation_sommet_base::remplir_coord_noeuds_et_polys(), traite_bord(), Champ_Inc_base::valeur_a(), Champ_Fonc_MED::valeur_a(), Champ_Fonc_base::valeur_aux(), Champ_Inc_base::valeur_aux(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux(), TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_(), Champ_Fonc_Face::valeur_aux_compo(), Champ_Inc_base::valeur_aux_compo(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux_compo(), TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_compo_(), Champ_base::valeur_aux_sommets(), and Champ_base::valeur_aux_sommets_compo().
chercher_elements() [2/3]
ArrOfInt & Zone::chercher_elements (const DoubleVect & positions, ArrOfInt & elements, int reel = 0) const
Recherche des elements contenant les points dont les
coordonnees sont specifiees.
Returns
ArrOfInt&
Signification: le tableau des numeros des elements contenant
les points specifies
Contraintes:
Definition at line 449 of file Zone.cpp.
{
// Cerr<<"Dans Zone::chercher_elements(const DoubleVect&"<<finl;
// Cerr<<"codage lourd....."<<finl;
  int n=positions.size();
  if (n!=dimension)
    {
      Cerr<<"Zone::chercher_elements(const DoubleVect& positions, ArrOfInt& elements, int reel) const -> Coding is made to copy a doublevect(dimesnion) in a DoubleTab(1,dimension)"<<finl;
      Cerr<<"But, it comes with a DoubleVect of size "<<n << " instead of "<<dimension<<finl;
      assert(0);
      exit();
    }
  DoubleTab positions2(1,n);
  for (int ii=0; ii<n; ii++) positions2(0,ii)=positions(ii);
  return chercher_elements( positions2, elements, reel) ;
}
References Cerr, chercher_elements(), Objet_U::dimension, Process::exit(), finl, and TRUSTVect< _TYPE_ >::size().
chercher_elements() [3/3]
int Zone::chercher_elements (double x, double y = 0, double z = 0, int reel = 0) const
Renvoie le rang de l'element contenant
le point dont les coordonnees sont specifiees.
Returns
int
Signification: le rang de l'element contenant
le point dont les coordonnees sont specifiees.
Contraintes:
Definition at line 1204 of file Zone.cpp.
{
  const OctreeRoot& octree = construit_octree(reel);
  return octree.rang_elem(x, y, z);
}
References construit_octree(), and OctreeRoot::rang_elem().
chercher_sommets() [1/2]
ArrOfInt & Zone::chercher_sommets (const DoubleTab & pos, ArrOfInt & som, int reel = 0) const
Returns
ArrOfInt&
Signification:
Contraintes:
Definition at line 1228 of file Zone.cpp.
{
  const OctreeRoot& octree = construit_octree(reel);
  octree.rang_sommet(pos, som);
  return som;
}
References construit_octree(), and OctreeRoot::rang_sommet().
Referenced by decoupe().
chercher_sommets() [2/2]
int Zone::chercher_sommets (double x, double y = 0, double z = 0, int reel = 0) const
Definition at line 1287 of file Zone.cpp.
{
  const OctreeRoot& octree = construit_octree(reel);
  return octree.rang_sommet(x, y, z);
}
References construit_octree(), and OctreeRoot::rang_sommet().
comprimer()
int Zone::comprimer ()
Concatene les bords de meme nom et ceci pour:
les bords, les bords periodiques et les faces internes.
Definition at line 971 of file Zone.cpp.
{
  {
// Les Bords
    LIST_CURSEUR(Bord) curseur(mes_faces_bord);;;
    while(curseur)
      {
        Frontiere& front=curseur.valeur();
// Au cas ou la zone de la frontiere n'est pas la bonne zone
        front.associer_zone(*this);
        LIST_CURSEUR(Bord) curseur2(curseur.list());;;
        Journal() << "Zone::comprimer() bord : " << front.le_nom() << finl;
        while(!curseur2.list().est_dernier())
          {
            Frontiere& front2=curseur2.list().suivant().valeur();
            if(front.le_nom() == front2.le_nom())
              {
                Journal() << "On agglomere le bord : " << front.le_nom() << finl;
                front.add(front2);
                curseur2.list().supprimer();
              }
            else
              ++curseur2;
          }
        Journal() << front.le_nom() << " est associee a : " << front.zone().le_nom() << finl;
        ++curseur;
      }
  }
  {
// Les Faces Internes :
    LIST_CURSEUR(Faces_Interne) curseur(mes_faces_int);;;
    while(curseur)
      {
        Frontiere& front=curseur.valeur();
        LIST_CURSEUR(Faces_Interne) curseur2(curseur.list());;;
        while(!curseur2.list().est_dernier())
          {
            Frontiere& front2=curseur2.list().suivant().valeur();
            if(front.le_nom() == front2.le_nom())
              {
                front.add(front2);
                curseur2.list().supprimer();
              }
            else
              ++curseur2;
          }
        ++curseur;
      }
  }
  {
// Les Raccords
    LIST_CURSEUR(Raccord) curseur(mes_faces_raccord);;;
    while(curseur)
      {
        Frontiere& front=curseur->valeur();
        LIST_CURSEUR(Raccord) curseur2(curseur.list());;;
        Journal() << "Raccord : " << front.le_nom() << finl;
        while(!curseur2.list().est_dernier())
          {
            Frontiere& front2=curseur2.list().suivant()->valeur();
            if(front.le_nom() == front2.le_nom())
              {
                front.add(front2);
                curseur2.list().supprimer();
              }
            else
              ++curseur2;
          }
        ++curseur;
      }
  }
  return 1;
}
References Frontiere::add(), Frontiere::associer_zone(), finl, Process::Journal(), Frontiere::le_nom(), le_nom(), LIST_CURSEUR, mes_faces_bord, mes_faces_int, mes_faces_raccord, and Frontiere::zone().
Referenced by Zones::comprimer(), and Zones::merge().
comprimer_joints()
int Zone::comprimer_joints ()
Concatene les joints de meme nom.
Definition at line 930 of file Zone.cpp.
{
  LIST_CURSEUR(Joint) curseur(mes_faces_joint);;;
  while(curseur)
    {
      Frontiere& front=curseur.valeur();
      LIST_CURSEUR(Joint) curseur2(curseur.list());;;
      while(!curseur2.list().est_dernier())
        {
          Frontiere& front2=curseur2.list().suivant().valeur();
          if(front.le_nom() == front2.le_nom())
            {
              front.add(front2);
              curseur2.list().supprimer();
            }
          else
            ++curseur2;
        }
      ++curseur;
    }
  return 1;
}
References Frontiere::add(), Frontiere::le_nom(), LIST_CURSEUR, and mes_faces_joint.
Referenced by Zones::merge().
construire_elem_virt_pe_num() [1/2]
void Zone::construire_elem_virt_pe_num ()
Definition at line 1391 of file Zone.cpp.
{
  IntTab tableau_echange(mes_elems);
  assert(tableau_echange.dimension(1) >= 2);
  int i;
  const int n = nb_elem();
  const int n_virt = nb_elem_tot() - n;
  const int moi = me();
  for (i = 0; i < n; i++)
    {
      tableau_echange(i, 0) = moi;
      tableau_echange(i, 1) = i;
    }
  tableau_echange.echange_espace_virtuel();
  elem_virt_pe_num_.resize(n_virt, 2);
  for (i = 0; i < n_virt; i++)
    {
      elem_virt_pe_num_(i, 0) = tableau_echange(n + i, 0);
      elem_virt_pe_num_(i, 1) = tableau_echange(n + i, 1);
    }
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), elem_virt_pe_num_, Process::me(), mes_elems, nb_elem(), nb_elem_tot(), and TRUSTTab< _TYPE_ >::resize().
Referenced by Domain_Graph::construire_graph_elem_elem().
construire_elem_virt_pe_num() [2/2]
void Zone::construire_elem_virt_pe_num (IntTab & elem_virt_pe_num_cpy) const
Definition at line 1414 of file Zone.cpp.
{
  IntTab tableau_echange(mes_elems);
  assert(tableau_echange.dimension(1) >= 2);
  int i;
  const int n = nb_elem();
  const int n_virt = nb_elem_tot() - n;
  const int moi = me();
  for (i = 0; i < n; i++)
    {
      tableau_echange(i, 0) = moi;
      tableau_echange(i, 1) = i;
    }
  tableau_echange.echange_espace_virtuel();
  elem_virt_pe_num_cpy.resize(n_virt, 2);
  for (i = 0; i < n_virt; i++)
    {
      elem_virt_pe_num_cpy(i, 0) = tableau_echange(n + i, 0);
      elem_virt_pe_num_cpy(i, 1) = tableau_echange(n + i, 1);
    }
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::me(), mes_elems, nb_elem(), nb_elem_tot(), and TRUSTTab< _TYPE_ >::resize().
construit_octree() [1/2]
const OctreeRoot & Zone::construit_octree () const
Definition at line 1564 of file Zone.cpp.
{
  if (!deriv_octree_.non_nul())
    deriv_octree_.typer("OctreeRoot");
  OctreeRoot& octree = deriv_octree_.valeur();
  if (!octree.construit())
    {
      octree.associer_Zone(*this);
      octree.construire();
    }
  return octree;
}
References OctreeRoot::associer_Zone(), OctreeRoot::construire(), OctreeRoot::construit(), deriv_octree_, O_U_Ptr::non_nul(), Deriv_::typer(), and Deriv_OctreeRoot::valeur().
Referenced by chercher_aretes(), chercher_elements(), chercher_sommets(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), ExtrudeParoi::extrude(), Champ_front_recyclage::initialiser(), Perte_Charge_Singuliere::lire_surfaces(), rang_elems_sommet(), Remove_elem::Remove_elem_(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Trianguler_fin::trianguler(), and Refine_Mesh::update_octree().
construit_octree() [2/2]
const OctreeRoot & Zone::construit_octree (int & reel) const
construction de l'octree si pas deja fait
Definition at line 1578 of file Zone.cpp.
{
  if (!deriv_octree_.non_nul())
    deriv_octree_.typer("OctreeRoot");
  OctreeRoot& octree = deriv_octree_.valeur();
  if (!octree.construit() || (reel != octree.reel()))
    {
      octree.associer_Zone(*this);
      octree.construire(reel);
    }
  return octree;
}
References OctreeRoot::associer_Zone(), OctreeRoot::construire(), OctreeRoot::construit(), deriv_octree_, O_U_Ptr::non_nul(), OctreeRoot::reel(), Deriv_::typer(), and Deriv_OctreeRoot::valeur().
correct_type_of_borders_after_merge()
void Zone::correct_type_of_borders_after_merge ()
Correcting type of borders if they were empty before merge (ie equal to vide_0D)
difference with corriger_type is that we don't want to delete faces inside borders afterwards.
Definition at line 814 of file Zone.cpp.
{
  {
// Les Bords
    LIST_CURSEUR(Bord) curseur(mes_faces_bord);;;
    while(curseur)
      {
        Frontiere& front=curseur.valeur();
        if(front.faces().type_face() == Faces::vide_0D)
          {
            LIST_CURSEUR(Bord) curseur2(curseur.list());;;
            while(!curseur2.list().est_dernier())
              {
                Frontiere& front2=curseur2.list().suivant().valeur();
                if(front.le_nom() == front2.le_nom())
                  {
                    front.faces().typer(front2.faces().type_face());
                    break;
                  }
                else
                  ++curseur2;
              }
          }
        ++curseur;
      }
  }
  {
// Les Faces Internes :
    LIST_CURSEUR(Faces_Interne) curseur(mes_faces_int);;;
    while(curseur)
      {
        Frontiere& front=curseur.valeur();
        if(front.faces().type_face() == Faces::vide_0D)
          {
            LIST_CURSEUR(Faces_Interne) curseur2(curseur.list());;;
            while(!curseur2.list().est_dernier())
              {
                Frontiere& front2=curseur2.list().suivant().valeur();
                if(front.le_nom() == front2.le_nom())
                  {
                    front.faces().typer(front2.faces().type_face());
                    break;
                  }
                else
                  ++curseur2;
              }
          }
        ++curseur;
      }
  }
  {
// Les Raccords
    LIST_CURSEUR(Raccord) curseur(mes_faces_raccord);;;
    while(curseur)
      {
        Frontiere& front=curseur.valeur();
        if(front.faces().type_face() == Faces::vide_0D)
          {
            LIST_CURSEUR(Raccord) curseur2(curseur.list());;;
            while(!curseur2.list().est_dernier())
              {
                Frontiere& front2=curseur2.list().suivant().valeur();
                if(front.le_nom() == front2.le_nom())
                  {
                    front.faces().typer(front2.faces().type_face());
                    break;
                  }
                else
                  ++curseur2;
              }
          }
        ++curseur;
      }
  }
  {
// Les joints
    LIST_CURSEUR(Joint) curseur(mes_faces_joint);;;
    while(curseur)
      {
        Frontiere& front=curseur.valeur();
        if(front.faces().type_face() == Faces::vide_0D)
          {
            LIST_CURSEUR(Joint) curseur2(curseur.list());;;
            while(!curseur2.list().est_dernier())
              {
                Frontiere& front2=curseur2.list().suivant().valeur();
                if(front.le_nom() == front2.le_nom())
                  {
                    front.faces().typer(front2.faces().type_face());
                    break;
                  }
                else
                  ++curseur2;
              }
          }
        ++curseur;
      }
  }
}
References Frontiere::faces(), Frontiere::le_nom(), LIST_CURSEUR, mes_faces_bord, mes_faces_int, mes_faces_joint, mes_faces_raccord, Faces::type_face(), Faces::typer(), and Faces::vide_0D.
Referenced by Zones::merge().
cree_instance()
Objet_U * Zone::cree_instance () static
Definition at line 24 of file Zone.cpp.
creer_aretes()
void Zone::creer_aretes ()
< attention, nb_aretes_tot est une methode !
< car le resize suivant ne fait quelque chose que si on change de taille
< indice sur le pe voisin
< indice local de l'arete
< indice sur le pe voisin
Definition at line 925 of file Faces_builder.cpp.
{
  const IntTab& elem_som = les_elems();
// Nombre d'elements reels:
  const int nbelem = elem_som.dimension(0);
// Les elements virtuels sont deja construits:
  const int nbelem_tot = elem_som.dimension_tot(0);
  Aretes_som.set_smart_resize(1);
  Aretes_som.resize(0, 2);
  bool is_poly = sub_type(Poly_geom_base, type_elem().valeur());
  std::vector<std::vector<int> > v_e_a(nbelem_tot);//liste des aretes de chaque element
  int nb_aretes_reelles = 0, i, j;
  {
// Une liste chainee pour retrouver, pour chaque sommet, la liste des aretes
// attachees a ce sommet. Le tableau est de meme taille que Aretes_som.dimension(0)
// chaine_aretes_sommets[i] contient l'indice de la prochaine arete attachee au
// meme sommet ou -1 si c'est la derniere
    ArrOfInt chaine_aretes_sommets;
    chaine_aretes_sommets.set_smart_resize(1);
// Indice de la premiere arete attachee a chaque sommet dans chaine_aretes_sommets
    ArrOfInt premiere_arete_som(nb_som_tot());
    premiere_arete_som= -1;
    std::map<std::array<double, 3>, std::array<int, 2> > aretes_loc; //aretes de l'element considere : aretes_loc[{xa, ya, za}] = { s1, s2}
// l'utilisation d'un map permet de s'assurer que les aretes soient dans le meme ordre sur tous les procs!
    for (int i_elem = 0; i_elem < nbelem_tot; aretes_loc.clear(), i_elem++)
      {
        /* 1. on retrouve les aretes de l'element en iterant sur ses faces */
        const Elem_geom_base& elem_g = ref_cast(Elem_geom_base, type_elem().valeur());
        IntTrav f_e_r;
        if (is_poly)
          {
            const Poly_geom_base& poly_g = ref_cast(Poly_geom_base, type_elem().valeur());
            poly_g.get_tab_faces_sommets_locaux(f_e_r, i_elem);
          }
        else elem_g.get_tab_faces_sommets_locaux(f_e_r);
        for (i = 0; i < f_e_r.dimension(0) && f_e_r(i, 0) >= 0; i++)
          for (j = 0; j < f_e_r.dimension(1) && f_e_r(i, j) >= 0; j++)
            {
              int s1 = elem_som(i_elem, f_e_r(i, j)),
                  s2 = elem_som(i_elem, f_e_r(i, j + 1 < f_e_r.dimension(1) && f_e_r(i, j + 1) >= 0 ? j + 1 : 0));
              std::array<double, 3> key;
              for (int l = 0; l < 3; l++) key[l] = (domaine().coord_sommets()(s1, l) + domaine().coord_sommets()(s2, l)) / 2;
              aretes_loc[key] = {{ std::min(s1, s2), std::max(s1, s2) }};
            }
        for (auto && kv : aretes_loc)
          {
// a-t-on deja vu cette arete ?
            int k = premiere_arete_som[kv.second[0]];
            while (k >= 0 && (Aretes_som(k, 0) != kv.second[0] || Aretes_som(k, 1) != kv.second[1])) k = chaine_aretes_sommets[k];
            if (k < 0) //on n'a pas encore trouve l'arete -> maj de premiere_arete_som et chaine_arete_sommets
              {
// L'arete n'existe pas encore
                k = chaine_aretes_sommets.size_array();
                assert(k == Aretes_som.dimension(0));
                Aretes_som.append_line(kv.second[0], kv.second[1]);
// Insertion de l'arete en tete de la liste chainee
                int old_head = premiere_arete_som[kv.second[0]];
// Indice de la nouvelle arete
                int new_head = chaine_aretes_sommets.size_array();
                chaine_aretes_sommets.append_array(old_head);
                premiere_arete_som[kv.second[0]] = new_head;
              }
            v_e_a[i_elem].push_back(k); //ajout de l'arete a la liste des aretes de l'element
          }
        if (i_elem == nbelem - 1)
          {
// On vient de finir les aretes reelles
            nb_aretes_reelles = Aretes_som.dimension(0);
          }
      }
  }
  /* remplissage du tableau elem_aretes a l'aide de v_e_a */
  int nb_aretes_elem = 0;
  for (i = 0; i < nbelem_tot; i++) nb_aretes_elem = std::max(nb_aretes_elem, (int) v_e_a[i].size());
  nb_aretes_elem = mp_max(nb_aretes_elem);
  Elem_Aretes.resize(0, nb_aretes_elem);
  creer_tableau_elements(Elem_Aretes, Array_base::NOCOPY_NOINIT);
  for (i = 0, Elem_Aretes = -1; i < nbelem_tot; i++)
    for (j = 0; j < (int) v_e_a[i].size(); j++)
      Elem_Aretes(i, j) = v_e_a[i][j];
// Ajuste la taille du tableau Aretes_som
  const int n_aretes_tot = Aretes_som.dimension(0); //!< attention, nb_aretes_tot est une methode !
  Aretes_som.append_line(-1, -1); //!< car le resize suivant ne fait quelque chose que si on change de taille
  Aretes_som.set_smart_resize(0);
  Aretes_som.resize(n_aretes_tot, 2);
  Journal() << "Domaine " << domaine().le_nom() << " nb_aretes=" << nb_aretes_reelles
            << " nb_aretes_tot=" << n_aretes_tot << finl;
// Construction du descripteur parallele
  {
// Pour chaque arete, indice du processeur proprietaire de l'arete
    const int moi = Process::me();
    ArrOfInt pe_aretes(n_aretes_tot);
    pe_aretes=moi;
    echanger_tableau_aretes(Elem_Aretes, nb_aretes_reelles, pe_aretes);
// Pour chaque arete, indice de l'arete sur le processeur proprietaire
    ArrOfInt indice_aretes_owner;
    indice_aretes_owner.resize_array(n_aretes_tot, Array_base::NOCOPY_NOINIT);
    for (i = 0; i < nb_aretes_reelles; i++)
      indice_aretes_owner[i] = i;
    echanger_tableau_aretes(Elem_Aretes, nb_aretes_reelles, indice_aretes_owner);
// Construction de pe_voisins
    ArrOfInt pe_voisins;
    pe_voisins.set_smart_resize(1);
    for (i=0; i<n_aretes_tot; i++)
      if (pe_aretes[i]!=moi)
        pe_voisins.append_array(pe_aretes[i]);
    ArrOfInt liste_pe;
    liste_pe.set_smart_resize(1);
    reverse_send_recv_pe_list(pe_voisins, liste_pe);
// On concatene les deux listes.
    for (i = 0; i < liste_pe.size_array(); i++)
      pe_voisins.append_array(liste_pe[i]);
    array_trier_retirer_doublons(pe_voisins);
    int nb_voisins = pe_voisins.size_array();
    ArrOfInt indices_pe(nproc());
    indices_pe= -1;
    for (i = 0; i < nb_voisins; i++)
      indices_pe[pe_voisins[i]] = i;
    ArrsOfInt aretes_communes_to_recv(nb_voisins);
    ArrsOfInt blocs_aretes_virt(nb_voisins);
    ArrsOfInt aretes_to_send(nb_voisins);
    for (i = 0; i < nb_voisins; i++)
      {
        aretes_communes_to_recv[i].set_smart_resize(1);
        blocs_aretes_virt[i].set_smart_resize(1);
        aretes_to_send[i].set_smart_resize(1);
      }
// Parcours des aretes: recherche des aretes a recevoir d'un autre processeur.
// Aretes reeles (items communs)
    for (i = 0; i < nb_aretes_reelles; i++)
      {
        const int pe = pe_aretes[i];
        if (pe != moi)
          {
            const int indice_pe = indices_pe[pe];
            if (indice_pe < 0)
              {
                Cerr << "Error: indice_pe=" << indice_pe << " shouldn't be negative in Zone::creer_aretes." << finl;
                Cerr << "It is a TRUST bug on this mesh with the Pa discretization, contact support." << finl;
                Cerr << "You could also try another partitioned mesh to get around this issue." << finl;
                exit();
              }
// Je recois cette arete d'un autre proc
            const int indice_distant = indice_aretes_owner[i];
            aretes_to_send[indice_pe].append_array(indice_distant); //!< indice sur le pe voisin
            aretes_communes_to_recv[indice_pe].append_array(i); //!< indice local de l'arete
          }
      }
// Aretes virtuelles
    for (i = nb_aretes_reelles; i < n_aretes_tot; i++)
      {
        const int pe = pe_aretes[i];
        assert(pe < nproc() && pe != moi);
        const int indice_pe = indices_pe[pe];
        if (indice_pe < 0)
          {
            Cerr << "Error: indice_pe=" << indice_pe << " shouldn't be negative in Zone::creer_aretes." << finl;
            Cerr << "It is a TRUST bug on this mesh with the Pa discretization, contact support." << finl;
            Cerr << "You could also try another partitioned mesh to get around this issue." << finl;
            exit();
          }
        const int indice_distant = indice_aretes_owner[i];
        aretes_to_send[indice_pe].append_array(indice_distant); //!< indice sur le pe voisin
        MD_Vector_base2::append_item_to_blocs(blocs_aretes_virt[indice_pe], i);
      }
    {
      Schema_Comm schema;
      schema.set_send_recv_pe_list(pe_voisins, pe_voisins);
      schema.begin_comm();
// On empile le tableau aretes_to_send et le nombre d'aretes commune avec ce pe:
      for (i = 0; i < nb_voisins; i++)
        schema.send_buffer(pe_voisins[i]) << aretes_to_send[i];
      schema.echange_taille_et_messages();
// Reception
      for (i = 0; i < nb_voisins; i++)
        schema.recv_buffer(pe_voisins[i]) >> aretes_to_send[i];
      schema.end_comm();
    }
// Construit l'objet descripteur
    MD_Vector_std md_aretes(n_aretes_tot,
                            nb_aretes_reelles,
                            pe_voisins,
                            aretes_to_send,
                            aretes_communes_to_recv,
                            blocs_aretes_virt);
    Cerr << "Total number of edges = " << md_aretes.nb_items_seq_tot_ << finl;
// Range l'objet dans un MD_Vector (devient const)
    MD_Vector md;
    md.copy(md_aretes);
// Attache le descripteur au tableau
    Aretes_som.set_md_vector(md);
  }
}
References TRUSTArray< _TYPE_ >::append_array(), MD_Vector_base2::append_item_to_blocs(), TRUSTTab< _TYPE_ >::append_line(), Aretes_som, array_trier_retirer_doublons(), Schema_Comm::begin_comm(), Cerr, MD_Vector::copy(), creer_tableau_elements(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), domaine(), Schema_Comm::echange_taille_et_messages(), echanger_tableau_aretes(), Elem_Aretes, Schema_Comm::end_comm(), Process::exit(), finl, Elem_geom_base::get_tab_faces_sommets_locaux(), Poly_geom_base::get_tab_faces_sommets_locaux(), Process::Journal(), Domaine::le_nom(), les_elems(), Process::me(), Process::mp_max(), MD_Vector_base2::nb_items_seq_tot_, nb_som_tot(), Array_base::NOCOPY_NOINIT, Process::nproc(), Schema_Comm::recv_buffer(), ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), reverse_send_recv_pe_list(), Schema_Comm::send_buffer(), TRUSTTab< _TYPE_ >::set_md_vector(), Schema_Comm::set_send_recv_pe_list(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), sub_type, type_elem(), and valeur().
Referenced by Zone_PolyMAC::discretiser(), and Zone_VEF_PreP1b::discretiser_arete().
creer_tableau_elements()
void Zone::creer_tableau_elements (Array_base & x, Array_base::Resize_Options opt = Array_base::COPY_INIT) const virtual
creation d'un tableau parallele de valeurs aux elements.
Voir MD_Vector_tools::creer_tableau_distribue()
Definition at line 1593 of file Zone.cpp.
{
  const MD_Vector& md = md_vector_elements();
  MD_Vector_tools::creer_tableau_distribue(md, x, opt);
}
References MD_Vector_tools::creer_tableau_distribue(), and md_vector_elements().
Referenced by Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Assembleur_P_VEFPreP1B::assembler_mat(), Terme_Source_Coriolis_VDF_Face::associer_pb(), Champ_Q1_EF::cal_rot_ordre1(), Champ_Q1NC::cal_rot_ordre1(), Zone_VF::calculer_diametres_hydrauliques(), Op_Conv_VDF_base::calculer_dt_stab(), Zone_VF::calculer_porosites(), calculer_volumes(), Op_Diff_PolyMAC_base::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Flux_interfacial_PolyMAC::completer(), Polyedre::compute_virtual_index(), creer_aretes(), Hexa_VEF::creer_facette_normales(), Quadri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), Domaine::creer_tableau_elements(), Extraire_surface::extraire_surface(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Zone_Poly_base::init_dist_paroi_globale(), Zone_VDF::init_virt_e_map(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Extraire_domaine::interpreter_(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), multiplier_diviser_rho(), Zone_PolyMAC::orthocentrer(), Champ_input_P0::readOn(), Op_Diff_VEF_base::remplir_nu(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), and Zone_VEF::reordonner().
domaine() [1/2]
Domaine & Zone::domaine ()
Renvoie le domaine dont la zone fait partie.
Returns
Domaine&
Signification: le domaine dont la zone fait partie
Contraintes:
Definition at line 274 of file Zone.cpp.
{
  return le_domaine.valeur();
}
References le_domaine, and Ref_Domaine::valeur().
domaine() [2/2]
const Domaine & Zone::domaine () const
Renvoie le domaine dont la zone fait partie.
(version const)
Returns
Domaine&
Signification: le domaine dont la zone fait partie
Contraintes: reference constante
Definition at line 255 of file Zone.cpp.
{
  return le_domaine.valeur();
}
References le_domaine, and Ref_Domaine::valeur().
Referenced by Champ_implementation_P0::affecter_(), Champ_P1_isoP1Bulle::affecter_(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), ajouter_bord(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), assembler(), Assembleur_P_VDF_Q4::assembler(), Source_PDF_EF::associer_pb(), Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), auto_build_joints(), Octree_Zone::build(), build_triofield(), calcul_longueur_filtre(), Traitement_particulier_NS_THI::calcul_nb_som_dir(), Traitement_particulier_NS_THI_new::calcul_nb_som_dir(), Zone_EF::calculer_Bij(), Aretes::calculer_centre_de_gravite(), Elem_geom_base::calculer_centres_gravite(), Faces::calculer_centres_gravite(), Hexaedre_axi::calculer_centres_gravite(), Rectangle_axi::calculer_centres_gravite(), Polyedre::calculer_centres_gravite(), Polygone::calculer_centres_gravite(), calculer_centres_gravite_aretes(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Zone_EF::calculer_IPhi(), calculer_liste_complete_aretes_joint(), Hexaedre::calculer_normales(), Rectangle::calculer_normales(), Tetraedre::calculer_normales(), Triangle::calculer_normales(), Faces_VDF::calculer_orientation(), Navier_Stokes_std::calculer_pression_hydrostatique(), Faces::calculer_surfaces(), Polyedre::calculer_un_centre_gravite(), Polygone::calculer_un_centre_gravite(), Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Hexaedre::calculer_volumes(), Hexaedre_axi::calculer_volumes(), Hexaedre_VEF::calculer_volumes(), Polyedre::calculer_volumes(), Polygone::calculer_volumes(), Prisme::calculer_volumes(), Quadrangle_VEF::calculer_volumes(), Rectangle::calculer_volumes(), Rectangle_2D_axi::calculer_volumes(), Rectangle_axi::calculer_volumes(), Segment::calculer_volumes(), Segment_axi::calculer_volumes(), Tetraedre::calculer_volumes(), Triangle::calculer_volumes(), Assembleur_P_VEFPreP1B::changer_base_pression(), Assembleur_P_VEFPreP1B::changer_base_pression_inverse(), Assembleur_P_VEFPreP1B::changer_base_second_membre(), Faces_builder::check_erreur_faces(), Reordonner_faces_periodiques::check_faces_periodiques(), chercher_arete(), Partitionneur_Tranche::chercher_direction_perio(), chercher_elements(), Faces::compare(), Champ_front_calc::completer(), Echange_interne_global_impose::completer(), Champ_front_contact_VEF::completer(), Champ_Generique_Transformation::completer(), Champ_Post_Operateur_Eqn::completer(), Conds_lim::completer(), Source_PDF_EF::compute_vitesse_imposee_projete(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Champ_front_contact_VEF::connectivity_failed(), OctreeRoot::construire(), Octree::construire(), Zone_VEF_PreP1b::construire_ok_arete(), Zone_VEF_PreP1b::construire_renum_arete_perio(), Hexaedre::contient(), Hexaedre_axi::contient(), Hexaedre_VEF::contient(), Point::contient(), Polyedre::contient(), Polygone::contient(), Prisme::contient(), Quadrangle_VEF::contient(), Rectangle::contient(), Rectangle_axi::contient(), Segment::contient(), Tetraedre::contient(), Triangle::contient(), corriger(), creer_aretes(), Hexa_VEF::creer_facette_normales(), Quadri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), Hexa_VEF::creer_normales_facettes_Cl(), decoupe(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Op_Div_VEFP1B_Elem::degres_liberte(), Zone_Poly_base::detecter_faces_non_planes(), Zone_EF::discretiser(), Zone_Poly_base::discretiser(), Zone_VF::discretiser(), Zone_VEF_PreP1b::discretiser(), Zone_PolyMAC::discretiser(), Zone_VEF::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), Discr_inst::discretiser_champ_fonc_don(), Zone_VEF_PreP1b::discretiser_suite(), Zone_VDF::dist_face_period(), distance_sommets(), Champ_Fonc_base::domaine(), Champ_Inc_base::domaine(), Op_Diff_VEF_Face_Penalise::domaine(), Postraiter_domaine::ecrire(), Postraitement_lata::ecrire_zone(), epsilon(), exemple_champ_non_homogene(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Zone_PolyMAC_P0::fgrad(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), find_joint_faces(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Champ_implementation_Q1::form_function(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Octree::get_epsilon(), get_ref_coordinates_items(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Zone_Cl_EF::imposer_cond_lim(), Champ_Fonc_P1_EF::imprime(), Champ_Fonc_Q1_EF::imprime(), Champ_P0_EF::imprime(), Champ_P1_EF::imprime(), Champ_Q1_EF::imprime(), Champ_Elem_PolyMAC::imprime(), Champ_Fonc_Som_PolyMAC::imprime(), Champ_Som_PolyMAC::imprime(), Champ_Fonc_Q1_VDF::imprime(), Champ_Fonc_Q1_VEF::imprime(), Champ_Q4_implementation::imprime_Q4(), indice_elements(), Zone_VF::info_elem_som(), Zone_VF::infobord(), Zone_Poly_base::init_dist_paroi_globale(), Zone_Poly_base::init_equiv(), init_faces_virt_bord(), Echange_contact_PolyMAC_P0::init_fs_dist(), Zone_PolyMAC_P0::init_stencils(), Raccord_distant_homogene::initialise(), Sonde::initialiser(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Integrer_champ_med::interpreter(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), Op_Diff_VEFP1NCP1B_Face::isInStencil(), Zone_VEF_PreP1b::lecture_ok_arete(), lecture_special_part2(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Zone_PolyMAC::M1(), md_vector_elements(), Interprete_geometrique_base::mettre_a_jour_sous_zone(), Assembleur_P_VEFPreP1B::modifier_matrice(), Zone_VEF_PreP1b::modifier_pour_Cl(), Assembleur_P_VDF_Q4::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Assembleur_P_VEFPreP1B::modifier_solution(), nb_som(), nb_som_tot(), Hexa_EF::normale(), Quadri_EF::normale(), Segment_EF_axi::normale(), Tetra_EF::normale(), Tri_EF::normale(), Hexa_poly::normale(), Polyedre_poly::normale(), Polygone_poly::normale(), Quadri_poly::normale(), Tetra_poly::normale(), Tri_poly::normale(), Hexa_VEF::normale(), Quadri_VEF::normale(), Tetra_VEF::normale(), Tri_VEF::normale(), operation01(), operation11(), Zone_PolyMAC::orthocentrer(), Polyedriser::polyedriser(), projette(), Raffiner_anisotrope::Raffiner_anisotrope_(), OctreeRoot::rang_arete(), Zone_dis_base::rang_frontiere(), OctreeRoot::rang_sommet(), Sous_Zone::readOn(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_implementation_sommet_base::remplir_coord_noeuds(), Champ_Q4_implementation::remplir_coord_noeuds(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Champ_implementation_sommet_base::remplir_coord_noeuds_et_polys(), Zone_Cl_VEF::remplir_normales_facettes_Cl(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), remplir_sommets(), Champ_front_MED::remplir_tab(), Faces::reordonner(), Hexaedre_VEF::reordonner(), Quadrangle_VEF::reordonner(), Segment::reordonner(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Hexaedre::reordonner_elem(), Rectangle::reordonner_elem(), Champ_Fonc_base::sauvegarder(), EOS_Tools_VEF::secmembre_divU_Z(), second_membre(), som_pscal(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_Face_PolyMAC::trace(), traite_bord(), Champ_Q1NC_impl::transforme_coord2D(), Champ_Q1NC_impl::transforme_coord3D(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), Champ_Face_implementation::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem(), Champ_Face_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_elem_compo(), Champ_Q1NC_impl::valeur_a_sommet_compo(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_som_lu_VEF::valeur_aux_elems_compo(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_P1iP1B_implementation::valeur_aux_sommets(), Champ_implementation_base::valeur_aux_sommets(), Champ_implementation_base::valeur_aux_sommets_compo(), Champ_implementation_P1::value_interpolation(), Champ_implementation_Q1::value_interpolation(), Zone_VEF::vecteur_face_facette(), Zone_EF::verifie_compatibilite_domaine(), Zone_EF_axi::verifie_compatibilite_domaine(), Zone_VEF_PreP1b::verifie_ok_arete(), verifier(), and Zone_PolyMAC::W1().
duplique()
int Zone::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Zone.cpp.
duplique_faces_internes()
void Zone::duplique_faces_internes () protected
ecrire_noms_bords()
void Zone::ecrire_noms_bords (Sortie & os) const
Ecriture des noms des bords sur un flot de sortie
Ecrit les noms des: bords, bords periodiques, raccords
et faces internes.
Definition at line 1063 of file Zone.cpp.
{
  {
// Les Bords
    CONST_LIST_CURSEUR(Bord) curseur(mes_faces_bord);
    while(curseur)
      {
        os << curseur->le_nom() << finl;
        ++curseur;
      }
  }
  {
// Les Faces Internes :
    CONST_LIST_CURSEUR(Raccord) curseur(mes_faces_raccord);
    while(curseur)
      {
        os << curseur.valeur()->le_nom() << finl;
        ++curseur;
      }
  }
  {
// Les Faces Internes :
    CONST_LIST_CURSEUR(Faces_Interne) curseur(mes_faces_int);
    while(curseur)
      {
        os << curseur->le_nom() << finl;
        ++curseur;
      }
  }
}
References CONST_LIST_CURSEUR, finl, mes_faces_bord, mes_faces_int, and mes_faces_raccord.
Referenced by Zone_dis_base::ecrire_noms_bords().
elem_aretes() [1/2]
const IntTab & Zone::elem_aretes () const inline
renvoie le tableau de connectivite elements/aretes.
Definition at line 1295 of file Zone.h.
{
  return Elem_Aretes;
}
References Elem_Aretes.
elem_aretes() [2/2]
int Zone::elem_aretes (int i, int j) const inline
renvoie le numero de la jeme arete du ieme element.
Definition at line 1274 of file Zone.h.
{
  return Elem_Aretes(i, j);
}
References Elem_Aretes.
Referenced by Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Zone_VEF_PreP1b::construire_renum_arete_perio(), contribuer_matrice_NeumannP0Pa(), contribuer_matrice_NeumannP1Pa(), contribuer_matrice_NeumannPaPa(), contribuer_matrice_SymetrieP1Pa(), contribuer_matrice_SymetriePaPa(), contribuer_matriceP0Pa(), contribuer_matriceP1Pa(), contribuer_matricePaPa(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Zone_VEF_PreP1b::discretiser_arete(), Op_Grad_VEF_P1B_Face::impr(), Zone_PolyMAC::M1(), OctreeRoot::rang_arete(), update_matrice_NeumannP0Pa(), update_matrice_NeumannP1Pa(), update_matrice_NeumannPaPa(), update_matrice_SymetrieP1Pa(), update_matrice_SymetriePaPa(), update_matriceP0Pa(), update_matriceP1Pa(), update_matricePaPa(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), and Zone_PolyMAC::W1().
elem_virt_pe_num()
const IntTab & Zone::elem_virt_pe_num () const
Definition at line 1438 of file Zone.cpp.
{
  return elem_virt_pe_num_;
}
References elem_virt_pe_num_.
epsilon()
double Zone::epsilon () const
Definition at line 1096 of file Zone.cpp.
{
  return domaine().epsilon();
}
References domaine(), and Domaine::epsilon().
Referenced by Pave::lire_front(), and Pave::lire_Longueurs().
exporter_mon_centre_de_gravite()
void Zone::exporter_mon_centre_de_gravite (ArrOfDouble c) inline
Definition at line 175 of file Zone.h.
  {
    cg_moments_=c;
  };
References cg_moments_.
Referenced by Calculer_Moments::interpreter_().
face_interne_conjuguee()
int Zone::face_interne_conjuguee (int face) const
Renvoie -1 si face n'est pas une face interne
Renvoie le numero de la face dupliquee sinon.
Returns
int
Signification: -1 si la face specifiee n'est pas une face interne
le numero de la face dupliquee sinon
Contraintes:
Definition at line 770 of file Zone.cpp.
{
  if( (face)>=nb_faces_frontiere())
    return -1;
  int compteur=nb_faces_frontiere()-nb_faces_int();
  if( (face)<compteur)
    return -1;
  CONST_LIST_CURSEUR(Faces_Interne) curseur(mes_faces_int);;;
  while(curseur)
    {
      const Faces& les_faces=curseur->faces();
      int nbf=les_faces.nb_faces();
      if(face < nbf + compteur)
        {
          nbf/=2;
          if( (face-compteur)<nbf) return face+nbf;
          else return face-nbf;
        }
      compteur+=(2*nbf);
      ++curseur;
    }
  Cerr << "TRUST error " << finl;
  assert(0);
  exit();
  return -1;
}
References Cerr, compteur, CONST_LIST_CURSEUR, Process::exit(), finl, mes_faces_int, Faces::nb_faces(), nb_faces_frontiere(), and nb_faces_int().
Referenced by face_vois().
faces_bord() [1/2]
Bords & Zone::faces_bord () inline
Renvoie la liste des bords de la zone.
Returns
Bords&
Signification: la liste des bords de la zone
Contraintes:
Definition at line 1071 of file Zone.h.
{
  return mes_faces_bord;
}
References mes_faces_bord.
faces_bord() [2/2]
const Bords & Zone::faces_bord () const inline
Renvoie la liste des bords de la zone.
(version const)
Returns
Bords&
Signification: la liste des bords de la zone
Contraintes: reference constante
Definition at line 1052 of file Zone.h.
{
  return mes_faces_bord;
}
References mes_faces_bord.
Referenced by Zones::comprimer(), Extruder_en3::construire_bords(), DomaineCutter::construire_faces_bords_ssdom(), convert_domain_to_Domaine(), Faces_builder::creer_faces_reeles(), DecoupeBord::Decouper(), TroisDto2D::extraire_2D(), ExtrudeParoi::extrude(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), ExtrudeBord::extruder_hexa_old(), Zone_VF::info_elem_som(), Zone_VF::infobord(), Interprete_geometrique_base::interpreter(), MaillerParallel::interpreter(), Create_domain_from_sous_zone::interpreter_(), Extraire_domaine::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), Modif_bord_to_raccord::interpreter_(), SupprimeBord::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Zones::merge(), NettoieNoeuds::nettoie(), Polyedriser::polyedriser(), Raffiner_Simplexes::refine_domain(), RegroupeBord::regroupe_bord(), Remove_elem::Remove_elem_(), Transformer::transformation_complete(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), and Trianguler_fin::trianguler().
faces_int() [1/2]
Faces_Internes & Zone::faces_int () inline
Renvoie la liste des faces internes de la zone.
Returns
Faces_Internes&
Signification: la liste des faces internes de la zone
Contraintes:
Definition at line 1188 of file Zone.h.
{
  return mes_faces_int;
}
References mes_faces_int.
faces_int() [2/2]
const Faces_Internes & Zone::faces_int () const inline
Renvoie la liste des faces internes de la zone.
(version const)
Returns
Faces_Internes&
Signification: la liste des faces internes de la zone
Contraintes: reference constante
Definition at line 1169 of file Zone.h.
{
  return mes_faces_int;
}
References mes_faces_int.
Referenced by Zones::comprimer(), DomaineCutter::construire_faces_internes_ssdom(), Faces_builder::creer_faces_reeles(), Interprete_geometrique_base::interpreter(), Zones::merge(), NettoieNoeuds::nettoie(), Polyedriser::polyedriser(), Raffiner_Simplexes::refine_domain(), Remove_elem::Remove_elem_(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), and Trianguler_fin::trianguler().
faces_interne() [1/4]
Faces_Interne & Zone::faces_interne (const Nom & nom_) inline
Renvoie les faces_internes dont le nom est specifie.
Returns
Faces_Interne&
Signification: les faces_internes dont le nom est specifie
Contraintes:
Definition at line 809 of file Zone.h.
{
  return mes_faces_int(nom_);
}
References mes_faces_int.
faces_interne() [2/4]
const Faces_Interne & Zone::faces_interne (const Nom & nom_) const inline
Renvoie les faces_internes dont le nom est specifie<br>(version const)
Returns
Faces_Interne&
Signification: les faces_internes dont le nom est specifie
Contraintes: reference constante
Definition at line 790 of file Zone.h.
{
  return mes_faces_int(nom_);
}
References mes_faces_int.
faces_interne() [3/4]
Faces_Interne & Zone::faces_interne (int i) inline
Renvoie les i-ieme faces internes de la zone.
Returns
Facesr_Internes&
Signification: les i-ieme faces internes de la zone
Contraintes:
Definition at line 1032 of file Zone.h.
{
  return mes_faces_int(i);
}
References mes_faces_int.
faces_interne() [4/4]
const Faces_Interne & Zone::faces_interne (int i) const inline
Renvoie les i-ieme faces internes de la zone<br>(version const)
Returns
Faces_Internes&
Signification: les i-ieme faces internes de la zone
Contraintes: reference constante
Definition at line 1013 of file Zone.h.
{
  return mes_faces_int(i);
}
References mes_faces_int.
Referenced by Zone_VF::discretiser().
faces_joint() [1/2]
Joints & Zone::faces_joint () inline
Renvoie la liste des joints de la zone.
Returns
Joints&
Signification: la liste des joints de la zone
Contraintes:
Definition at line 1110 of file Zone.h.
{
  return mes_faces_joint;
}
References mes_faces_joint.
faces_joint() [2/2]
const Joints & Zone::faces_joint () const inline
Renvoie la liste des joints de la zone.
(version const)
Returns
Joints&
Signification: la liste des joints de la zone
Contraintes: reference constante
Definition at line 1091 of file Zone.h.
{
  return mes_faces_joint;
}
References mes_faces_joint.
Referenced by add_sommets_communs(), ajouter_joint(), Scatter::ajouter_joints(), ajouter_joints(), auto_build_joints(), Echange_contact_Correlation_VDF::calculer_CL(), Echange_contact_Correlation_VEF::calculer_CL(), Scatter::calculer_espace_distant(), calculer_espace_distant_item(), Scatter::check_consistancy_remote_items(), Zones::comprimer(), Scatter::construire_correspondance_aretes_par_coordonnees(), Scatter::construire_correspondance_sommets_par_coordonnees(), DomaineCutter::construire_faces_joints_ssdom(), Scatter::construire_md_vector(), DomaineCutter::construire_sommets_joints_ssdom(), DomaineCutter::construire_sous_domaine(), Scatter::construire_structures_paralleles(), convert_domain_to_Domaine(), Faces_builder::creer_faces_reeles(), Zone_VF::discretiser(), DomaineCutter::ecrire_zones(), Echange_contact_Correlation_VDF::init_tab_echange(), Scatter::interpreter(), Interprete_geometrique_base::interpreter(), MaillerParallel::interpreter(), Raffiner_isotrope_parallele::interpreter(), Create_domain_from_sous_zone::interpreter_(), Scatter::lire_domaine(), Zones::merge(), Scatter::mergeDomains(), mon_construire_correspondance_sommets_par_coordonnees(), Raffiner_Simplexes::refine_domain(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Zone_VDF::reordonner(), Zone_VEF::reordonner(), Scatter::reordonner_faces_de_joint(), and Zone_VEF_PreP1b::verifie_ok_arete().
faces_raccord() [1/2]
Raccords & Zone::faces_raccord () inline
Renvoie la liste des racoords de la zone.
Returns
Raccords&
Signification: la liste des raccords de la zone
Contraintes:
Definition at line 1149 of file Zone.h.
{
  return mes_faces_raccord;
}
References mes_faces_raccord.
faces_raccord() [2/2]
const Raccords & Zone::faces_raccord () const inline
Renvoie la liste des racoords de la zone.
(version const)
Returns
Raccords&
Signification: la liste des raccords de la zone
Contraintes: reference constante
Definition at line 1130 of file Zone.h.
{
  return mes_faces_raccord;
}
References mes_faces_raccord.
Referenced by Zones::comprimer(), Extruder_en3::construire_bords(), DomaineCutter::construire_faces_raccords_ssdom(), convert_domain_to_Domaine(), Faces_builder::creer_faces_reeles(), DecoupeBord::Decouper(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), TroisDto2D::extraire_2D(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), Zone_VF::info_elem_som(), Zone_VF::infobord(), Interprete_geometrique_base::interpreter(), Create_domain_from_sous_zone::interpreter_(), Modif_bord_to_raccord::interpreter_(), SupprimeBord::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Zones::merge(), NettoieNoeuds::nettoie(), Polyedriser::polyedriser(), Raffiner_Simplexes::refine_domain(), RegroupeBord::regroupe_bord(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), and Trianguler_fin::trianguler().
fixer_premieres_faces_frontiere()
void Zone::fixer_premieres_faces_frontiere ()
Definition at line 1345 of file Zone.cpp.
{
  Journal() << "Zone::fixer_premieres_faces_frontiere()" << finl;
  int compteur=0;
  {
    LIST_CURSEUR(Bord) curseur(mes_faces_bord);
    while(curseur)
      {
        curseur->fixer_num_premiere_face(compteur);
        compteur+=curseur->nb_faces();
        Journal() << "Le bord " << curseur->le_nom() << " commence a la face : "
                  << curseur->num_premiere_face() << finl;
        ++curseur;
      }
  }
  {
    LIST_CURSEUR(Raccord) curseur(mes_faces_raccord);
    while(curseur)
      {
        curseur.valeur()->fixer_num_premiere_face(compteur);
        compteur+=curseur.valeur()->nb_faces();
        Journal() << "Le raccord " << curseur->le_nom() << " commence a la face : "
                  << curseur.valeur()->num_premiere_face() << finl;
        ++curseur;
      }
  }
  {
    LIST_CURSEUR(Joint) curseur(mes_faces_joint);
    while(curseur)
      {
        curseur->fixer_num_premiere_face(compteur);
        compteur+=curseur->nb_faces();
        Journal() << "Le joint " << curseur->le_nom() << " commence a la face : "
                  << curseur->num_premiere_face() << finl;
        ++curseur;
      }
  }
// GF recalcul de nb_faces_Cl (inutile dans la 1.5.8)
// nb_faces_Cl = nb_faces_bord() + nb_faces_raccord() + nb_faces_int();
}
References compteur, finl, Process::Journal(), LIST_CURSEUR, mes_faces_bord, mes_faces_joint, and mes_faces_raccord.
Referenced by check_zone(), convert_domain_to_Domaine(), Interprete_geometrique_base::interpreter(), Extraire_domaine::interpreter_(), Extruder_en3::interpreter_(), Lire_Ideas::interpreter_(), Mailler::interpreter_(), Modif_bord_to_raccord::interpreter_(), and RegroupeBord::regroupe_bord().
frontiere() [1/4]
Frontiere & Zone::frontiere (const Nom & un_nom)
Definition at line 1339 of file Zone.cpp.
{
  int i = rang_frontiere(un_nom);
  return frontiere(i);
}
References frontiere(), and rang_frontiere().
frontiere() [2/4]
const Frontiere & Zone::frontiere (const Nom & un_nom) const
Definition at line 1333 of file Zone.cpp.
{
  int i = rang_frontiere(un_nom);
  return frontiere(i);
}
References frontiere(), and rang_frontiere().
frontiere() [3/4]
Frontiere & Zone::frontiere (int i) inline
Definition at line 850 of file Zone.h.
{
  int fin=nb_bords();
  if(i<fin)
    return mes_faces_bord(i);
  i-=fin;
  fin=nb_raccords();
  if(i<fin)
    return mes_faces_raccord(i).valeur();
  i-=fin;
  fin=nb_frontieres_internes();
  if(i<fin)
    return mes_faces_int(i);
  assert(0);
  exit();
  return frontiere(i);
}
References Process::exit(), frontiere(), mes_faces_bord, mes_faces_int, mes_faces_raccord, nb_bords(), nb_frontieres_internes(), nb_raccords(), and List_Raccord::valeur().
frontiere() [4/4]
const Frontiere & Zone::frontiere (int i) const inline
Definition at line 833 of file Zone.h.
{
  int fin=nb_bords();
  if(i<fin)
    return mes_faces_bord(i);
  i-=fin;
  fin=nb_raccords();
  if(i<fin)
    return mes_faces_raccord(i).valeur();
  i-=fin;
  fin=nb_frontieres_internes();
  if(i<fin)
    return mes_faces_int(i);
  assert(0);
  exit();
  return frontiere(i);
}
References Process::exit(), frontiere(), mes_faces_bord, mes_faces_int, mes_faces_raccord, nb_bords(), nb_frontieres_internes(), nb_raccords(), and List_Raccord::valeur().
Referenced by BlocData::add_faces(), Op_Div_VEFP1B_Elem::ajouter_som(), calculer_elements_voisins_bords(), check_zone(), Reordonner_faces_periodiques::chercher_direction_perio(), create_listb_from_domaine2(), create_listb_from_xyz(), create_listb_geom(), create_listb_naif(), Domaine::creer_mes_domaines_frontieres(), DecoupeBord::Decouper(), Op_Div_VEFP1B_Elem::degres_liberte(), Zone_VF::discretiser(), Postraiter_domaine::ecrire(), Domaine_bord::extraire_domaine_bord(), ExtrudeParoi::extrude(), ExtrudeBord::extruder_bord(), ExtrudeBord::extruder_hexa_old(), find_cl_face(), find_joint_faces(), frontiere(), init_faces_virt_bord(), Distanceparoi::interpreter_(), RegroupeBord::interpreter_(), Mod_turb_hyd_base::lire_motcle_non_standard(), NettoieNoeuds::nettoie(), RegroupeBord::rassemble_bords(), Zone_Cl_dis_base::readOn(), and RegroupeBord::regroupe_bord().
get_info()
const Type_info * Zone::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 24 of file Zone.cpp.
identifie_item_unique()
int Zone::identifie_item_unique (IntList & item_possible, DoubleTab & coord_possible, const DoubleVect & coord_ref) static
Definition at line 1630 of file Zone.cpp.
{
  int it_selection = -1;
  DoubleTab decentre_face(4,Objet_U::dimension);
  decentre_face = 0.;
  for (int t=1; t<4; t++)
    for (int dir=0; dir<Objet_U::dimension; dir++)
      if (dir==(t-1))
        decentre_face(t,dir) = 1.;
// decentre_face(0,0:dim)={0,0,0}
// decentre_face(1,0:dim)={1,0,0}
// decentre_face(2,0:dim)={0,1,0}
// decentre_face(3,0:dim)={0,0,1}
// Au premier passage (t=0) pas de translation effectuee
  DoubleVect dist;
  assert (item_possible.size()!=0);
  int t = 0;
  while ((item_possible.size()!=1) && (t<4))
    {
      double distmin = DMAXFLOAT;
      int size_initiale = item_possible.size();
      dist.resize(size_initiale);
      dist = 0.;
      for (int ind_it=0; ind_it<size_initiale; ind_it++)
        {
          for (int dir=0; dir<Objet_U::dimension; dir++)
            dist[ind_it] += (coord_possible(ind_it,dir)-(coord_ref(dir)+decentre_face(t,dir)))*(coord_possible(ind_it,dir)-(coord_ref(dir)+decentre_face(t,dir)));
          if (dist[ind_it]<=distmin)
            distmin = dist[ind_it];
        }
      int ind_it = 0;
      int nb_it_suppr = 0;
      while (ind_it<size_initiale)
        {
          if (!est_egal(dist[ind_it],distmin))
            {
              int ind_it_suppr = ind_it-nb_it_suppr;
              int it_suppr = item_possible[ind_it_suppr];
              item_possible.suppr(it_suppr);
              int size_actuelle = item_possible.size();
              for (int ind=ind_it_suppr; ind<size_actuelle; ind++)
                for (int dir=0; dir<dimension; dir++)
                  coord_possible(ind,dir) = coord_possible(ind+1,dir);
              coord_possible.resize(size_actuelle,dimension,Array_base::COPY_NOINIT);
              nb_it_suppr++;
            }
          ind_it++;
        }
      t++;
    }
  if (item_possible.size()==1)
    it_selection = item_possible[0];
  else
    {
      Cerr<<"Zone::identifie_item_unique()"<<finl;
      Cerr<<"An item has not been found among the list."<<finl;
      Cerr<<"Please contact TRUST support."<<finl;
      Process::exit();
    }
  return it_selection;
}
References Cerr, Array_base::COPY_NOINIT, Objet_U::dimension, DMAXFLOAT, est_egal(), Process::exit(), finl, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), TRUSTList< _TYPE_ >::size(), and TRUSTList< _TYPE_ >::suppr().
Referenced by Champ_front_recyclage::initialiser().
ind_faces_virt_bord()
const ArrOfInt & Zone::ind_faces_virt_bord () const inline
Definition at line 1243 of file Zone.h.
{
  return ind_faces_virt_bord_;
}
References ind_faces_virt_bord_.
Referenced by Periodique::completer(), Zone_Cl_VDF::completer(), Zone_EF::creer_faces_virtuelles_non_std(), Zone_VEF::creer_faces_virtuelles_non_std(), and Zone_VF::ind_faces_virt_bord().
indice_elements()
ArrOfInt & Zone::indice_elements (const IntTab & sommets, ArrOfInt & elem_, int reel = 0) const
che les numeros (indices) des elements contenants les sommets
specifies par le parametre "sommets".
Utilise:
ArrOfInt& Zone::chercher_elements(const DoubleTab&,ArrOfInt&) const
Returns
ArrOfInt&
Signification: le tableau des numeros des sommets dont
on cherche les elements correspondants
Contraintes:
Definition at line 304 of file Zone.cpp.
{
  int i,j,k;
  const DoubleTab& les_coord = domaine().coord_sommets();
  int sz_sommets = sommets.dimension(0);
  DoubleTab xg(sz_sommets,Objet_U::dimension);
  for(i=0; i<sz_sommets; i++)
    for(j=0; j<nb_som_elem(); j++)
      for(k=0; k<Objet_U::dimension; k++)
        xg(i,k)+=les_coord(sommets(i,j),k);
  xg/=nb_som_elem();
  return chercher_elements(xg,elem_,reel);
}
References chercher_elements(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, domaine(), and nb_som_elem().
info()
const Type_info * Zone::info () static
Definition at line 24 of file Zone.cpp.
init_faces_virt_bord()
void Zone::init_faces_virt_bord (const MD_Vector & md_vect_faces, MD_Vector & md_vect_faces_bord)
Methode appelee par Zone_VF::discretiser().
Construction du descripteur pour les faces de bord
Remplissage de ind_faces_virt_bord et des tableaux get_faces_virt() des frontieres
a partir du descripteur parallele des faces.
Note B.M.: le fait d'avoir mis les faces dans la Zone_VF, les aretes dans la Zone,
certaines parties des proprites des faces de bord dans la Zone_VF et d'autres dans la Zone
fait que l'initialisation passe par des chemins un peu tordus... il faudra nettoyer ca.
< nombre de faces de la Zone !
< idem !
Definition at line 736 of file Faces_builder.cpp.
{
// ***************************************
// 1) Construction des structures de tableaux pour toutes les faces de bord
// (faces de 0 a nb_faces_frontiere())
  const int nb_faces_fr = nb_faces_frontiere();
// Marquage des faces de bord (-1=>pas une face de bord, 0=>face de bord)
  IntVect vect_renum;
  MD_Vector_tools::creer_tableau_distribue(md_vect_faces, vect_renum, Array_base::NOCOPY_NOINIT);
  vect_renum = -1;
  for (int i = 0; i < nb_faces_fr; i++)
    vect_renum[i] = 0;
  vect_renum.echange_espace_virtuel();
// Creation du descripteur pour les faces de bord (par extraction d'un sous ensemble du descripteur
// des faces). On utilise la numerotation par defaut dans l'ordre croissant:
  MD_Vector_tools::creer_md_vect_renum_auto(vect_renum, md_vect_faces_front);
// Remplissage du tableau ind_faces_virt_bord. C'est juste la partie virtuelle du tableau renum.
// (la partie reelle est triviale: c'est une numerotation contigue de 0 a nb_faces_frontiere()
  const int nb_faces = vect_renum.size();
  const int nb_faces_tot = vect_renum.size_totale();
  const int nb_faces_virt = nb_faces_tot - nb_faces;
  ind_faces_virt_bord_.resize_array(nb_faces_virt, Array_base::NOCOPY_NOINIT);
  for (int i = 0; i < nb_faces_virt; i++)
    ind_faces_virt_bord_[i] = vect_renum[nb_faces + i];
// **************************************
// 2) Construction des structures de tableaux pour chaque frontiere
// Remplissage des tableaux
// frontiere(i).get_faces_virt() pour 0 <= i < nb_front_Cl()
// Ce tableau contient les indices dans la Zone_VF des faces virtuelles
// qui sont sur la frontiere i.
// Calcul de l'espace virtuel des faces de chaque frontiere
// Nombre de frontieres:
  const int nb_frontieres = nb_front_Cl();
  int i_frontiere;
// Remplissage des tableaux get_faces_virt():
// et constructrion des MD_Vector de chaque frontiere (associe au tableau des faces)
  for (i_frontiere = 0; i_frontiere < nb_frontieres; i_frontiere++)
    {
      Frontiere& front = frontiere(i_frontiere);
      IntTab& faces_sommets_frontiere = front.les_sommets_des_faces();
// Certains problemes ont plusieurs objets Zone_VF attaches a la meme Zone (rayonnement)
// Si on est deja passe par ici, ne pas refaire le travail:
      if (faces_sommets_frontiere.get_md_vector().non_nul())
        {
          continue;
        }
// les tableaux faces_sommets_frontiere doivent faire la meme largeur sur tous les procs avant echange
      int nb_som_faces = Process::mp_max(faces_sommets_frontiere.dimension(1));
      if (faces_sommets_frontiere.dimension(1) < nb_som_faces)
        {
          IntTrav fsf_old;
          fsf_old = faces_sommets_frontiere;
          faces_sommets_frontiere.resize(fsf_old.dimension_tot(0), nb_som_faces);
          faces_sommets_frontiere = -1;
          for (int i = 0, j; i < fsf_old.dimension_tot(0); i++)
            for (j = 0; j < fsf_old.dimension(1); j++)
              faces_sommets_frontiere(i, j) = fsf_old(i, j);
        }
      vect_renum = -1;
      const int i_premiere_face = front.num_premiere_face();
      const int nb_faces_front = front.nb_faces();
// Marquage des faces de cette frontiere
      for (int i = i_premiere_face; i < i_premiere_face + nb_faces_front; i++)
        vect_renum[i] = 0;
      vect_renum.echange_espace_virtuel();
// Construction d'un descripteur contenant le sous-ensemble des faces de cette frontiere
      MD_Vector md_frontiere;
      MD_Vector_tools::creer_md_vect_renum_auto(vect_renum, md_frontiere);
// Creation de l'espace virtuel des faces de la frontiere
// (c'est ici qu'on associe le descripteur md_frontiere au tableau des faces)
      const MD_Vector& md_sommets = domaine().les_sommets().get_md_vector();
      Scatter::construire_espace_virtuel_traduction(md_frontiere, /* tableau indexe par des numeros de faces de bord */
                                                    md_sommets, /* contenant des indices de sommets du domaine */
                                                    faces_sommets_frontiere, /* tableau a traiter */
                                                    1 /* erreur fatale: si un sommet est manquant, c'est une erreur */);
// On recupere dans renum l'indice renumerote de chaque face:
// on extrait les indices des faces virtuelles de cette frontiere
      ArrOfInt& tab = front.get_faces_virt();
      assert(faces_sommets_frontiere.dimension(0) == nb_faces_front);
      const int nb_faces_tot_frontiere = faces_sommets_frontiere.dimension_tot(0);
      const int nb_faces_virt_frontiere = nb_faces_tot_frontiere - nb_faces_front;
      tab.resize_array(nb_faces_virt_frontiere);
      const int ndebut = nb_faces; //!< nombre de faces de la Zone !
      const int nfin = nb_faces_tot; //!< idem !
      for (int i = ndebut; i < nfin; i++)
        {
          const int j = vect_renum[i];
          if (j >= 0)
            {
              assert(j >= nb_faces_front && j < nb_faces_tot_frontiere);
// La face i est virtuelle et sur cette frontiere
              tab[j - nb_faces_front] = i;
            }
        }
    }
}
References Scatter::construire_espace_virtuel_traduction(), MD_Vector_tools::creer_md_vect_renum_auto(), MD_Vector_tools::creer_tableau_distribue(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), frontiere(), Frontiere::get_faces_virt(), TRUSTVect< _TYPE_ >::get_md_vector(), ind_faces_virt_bord_, Domaine::les_sommets(), Frontiere::les_sommets_des_faces(), Process::mp_max(), Frontiere::nb_faces(), nb_faces_frontiere(), nb_front_Cl(), Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), Frontiere::num_premiere_face(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTVect< _TYPE_ >::size(), and TRUSTVect< _TYPE_ >::size_totale().
Referenced by Zone_VF::discretiser().
invalide_octree()
void Zone::invalide_octree ()
Definition at line 1558 of file Zone.cpp.
{
  if (deriv_octree_.non_nul())
    deriv_octree_.detach();
}
References deriv_octree_, Deriv_::detach(), and O_U_Ptr::non_nul().
Referenced by Decouper_Bord_coincident::Decouper_Bord_coincident_(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Interprete_geometrique_base::interpreter(), Raffiner_anisotrope::Raffiner_anisotrope_(), Remove_elem::Remove_elem_(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Trianguler_fin::trianguler(), and Refine_Mesh::update_octree().
joint() [1/4]
Joint & Zone::joint (const Nom & nom_) inline
Renvoie le joint dont le nom est specifie.
Returns
Joint&
Signification: le joint dont le nom est specifie
Contraintes:
Definition at line 731 of file Zone.h.
{
  return mes_faces_joint(nom_);
}
References mes_faces_joint.
joint() [2/4]
const Joint & Zone::joint (const Nom & nom_) const inline
Renvoie le joint dont le nom est specifie<br>(version const)
Returns
Joint&
Signification: le joint dont le nom est specifie
Contraintes: reference constante
Definition at line 712 of file Zone.h.
{
  return mes_faces_joint(nom_);
}
References mes_faces_joint.
joint() [3/4]
Joint & Zone::joint (int i) inline
Renvoie le i-ieme joint de la zone.
Returns
Joint&
Signification: le i-ieme joint de la zone
Contraintes:
Definition at line 921 of file Zone.h.
{
  return mes_faces_joint(i);
}
References mes_faces_joint.
joint() [4/4]
const Joint & Zone::joint (int i) const inline
Renvoie le i-ieme joint de la zone<br>(version const)
Returns
Joint&
Signification: le i-ieme joint de la zone
Contraintes: reference constante
Definition at line 902 of file Zone.h.
{
  return mes_faces_joint(i);
}
References mes_faces_joint.
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), Op_Conv_VDF< OP_TYPE >::associer_(), Scatter::calculer_espace_distant_elements(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Op_Conv_EF_Stab_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Grad_PolyMAC_Face::completer(), Op_Grad_PolyMAC_P0_Face::completer(), DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_sous_domaine(), Scatter::corriger_espace_distant_elements_perio(), dump_lata(), Postraiter_domaine::ecrire(), Zone_VF::joint(), and Op_Conv_EF_Stab_PolyMAC_Elem::preparer_calcul().
joint_of_pe() [1/2]
Joint & Zone::joint_of_pe (int pe) inline
Definition at line 950 of file Zone.h.
{
  int i;
  for(i=0; i<nb_joints(); i++)
    if(mes_faces_joint(i).PEvoisin()==pe)
      break;
  return mes_faces_joint(i);
}
References mes_faces_joint, and nb_joints().
Referenced by DomaineCutter::construire_elements_distants_ssdom().
joint_of_pe() [2/2]
const Joint & Zone::joint_of_pe (int pe) const inline
Renvoie le joint correspondant au PE specifie.
(PE = Processeur Elementaire, ou numero de processus)
Un joint est une frontiere entre 2 PE.
Returns
Joint&
Signification: le joint correspondant au PE specifie
Contraintes: reference constante
Definition at line 942 of file Zone.h.
{
  int i;
  for(i=0; i<nb_joints(); i++)
    if(mes_faces_joint(i).PEvoisin()==pe)
      break;
  return mes_faces_joint(i);
}
References mes_faces_joint, and nb_joints().
le_nom()
const Nom & Zone::le_nom () const inline override virtual
Renvoie le nom de la zone.
Returns
Nom&
Signification: le nom de la zone
Contraintes: reference constante
Reimplemented from Objet_U.
Definition at line 356 of file Zone.h.
{
  return nom;
}
References nom.
Referenced by comprimer(), Zones::comprimer(), DomaineCutter::construire_sous_domaine(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_Lml::ecrire_domaine_lml(), Postraitement::init(), Zones::merge(), Postraitement::postraiter_champs(), Format_Post_base::postraiter_debug_valeurs_un_instant(), Postraitement::postraiter_tableaux(), and read_zone().
les_elems() [1/2]
IntTab & Zone::les_elems () inline
Renvoie le tableau des sommets des elements.
Returns
IntTab&
Signification: le tableau des sommets des elements
Contraintes:
Definition at line 395 of file Zone.h.
{
  return mes_elems;
}
References mes_elems.
Referenced by BlocData::add_bloc(), Champ_P1_isoP1Bulle::affecter_(), Op_Div_EF::ajouter(), Op_Grad_EF::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_VEF_Face::ajouter(), Source_Qdm_EF::ajouter(), Source_Scalaire_EF::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Source_PDF_EF::ajouter_(), Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Diff_EF::ajouter_scalaire_template(), Op_Dift_EF_Q1::ajouter_scalaire_template(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Conv_EF::ajouter_sous_cond_template(), Op_Diff_EF::ajouter_vectoriel_template(), Op_Dift_EF_Q1::ajouter_vectoriel_template(), Assembleur_P_EF::assembler_mat(), Octree_Zone::build(), Refine_Mesh::build_edges(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Polygone::build_reduced(), build_triofield(), calcul_longueur_filtre(), Zone_EF::calculer_Bij(), Zone_EF::calculer_Bij_gen(), Zone_EF_axi::calculer_Bij_gen(), Elem_geom_base::calculer_centres_gravite(), Hexaedre_axi::calculer_centres_gravite(), Rectangle_axi::calculer_centres_gravite(), Polyedre::calculer_centres_gravite(), Polygone::calculer_centres_gravite(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_espace_distant_sommets(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Zone_EF_axi::calculer_IPhi(), Polyedre::calculer_un_centre_gravite(), Polygone::calculer_un_centre_gravite(), Polyedre::calculer_volumes(), Polygone::calculer_volumes(), Prisme::calculer_volumes(), Zone_EF::calculer_volumes_sommets(), Discretisation_tools::cells_to_nodes(), Assembleur_P_VEFPreP1B::changer_base_pression(), Assembleur_P_VEFPreP1B::changer_base_pression_inverse(), Assembleur_P_VEFPreP1B::changer_base_second_membre(), Rectify_Mesh::check_cell_enumeration_3D(), Rectify_Mesh::check_cell_orientation_2D(), Rectify_Mesh::check_cell_orientation_3D(), check_internal_diagonal_for_tetrahedron(), check_positive_volumes_for_tetrahedron(), check_positive_volumes_for_triangle(), choose_internal_diagonal_for_tetrahedron(), Champ_Generique_Extraction::completer(), Champ_Generique_Transformation::completer(), Champ_Post_Operateur_Eqn::completer(), Zones::comprimer(), compute_cell_qualities_for_tetrahedron(), compute_cell_qualities_for_triangle(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Octree::construire(), Extruder_en3::construire_bords(), DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_faces_joints_ssdom(), Domain_Graph::construire_graph_elem_elem(), Domain_Graph::construire_graph_from_segment(), DomaineCutter::construire_sous_domaine(), Scatter::construire_structures_paralleles(), Point::contient(), Polyedre::contient(), Polygone::contient(), Segment::contient(), Source_PDF_EF::contribuer_a_avec(), convert_domain_to_Domaine(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), corriger(), Partitionneur_base::corriger_bords_avec_liste(), Scatter::corriger_espace_distant_elements_perio(), Partitionneur_base::corriger_multiperiodique(), Partitionneur_base::corriger_sommets_bord(), creer_aretes(), Elem_geom_base::creer_faces_elem(), Faces_builder::creer_faces_reeles(), Hexa_VEF::creer_facette_normales(), Quadri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), Hexa_VEF::creer_normales_facettes_Cl(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Op_Div_VEFP1B_Elem::degres_liberte(), Op_EF_base::dimensionner(), Zone_VF::discretiser(), Zone_VEF_PreP1b::discretiser(), Postraiter_domaine::ecrire(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine(), Format_Post_Lml::ecrire_domaine_lml(), Postraitement_lata::ecrire_zone(), ensure_positive_volumes_for_tetrahedron(), ensure_positive_volumes_for_triangle(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), Extruder::extruder_hexa(), ExtrudeBord::extruder_hexa_old(), find_joint_faces(), Champ_implementation_Q1::form_function(), Polyedre::get_nb_som_elem_max(), Polygone::get_nb_som_elem_max(), Champ_Generique_refChamp::get_ref_connectivity(), get_ref_coordinates_items(), Champ_input_P0::getTemplate(), Champ_Q1_EF::gradient(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), histogramme_angle(), Op_Grad_VEF_P1B_Face::impr(), Zone_VF::info_elem_som(), Scatter::init_sequential_domain(), Zone_PolyMAC_P0::init_stencils(), Champ_Face_PolyMAC_P0::init_ve2(), Sonde::initialiser(), DomaineCutter::initialiser(), Integrer_champ_med::interpreter(), Decouper_multi::interpreter(), Raffiner_isotrope_parallele::interpreter(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), VerifierCoin::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Op_Diff_VEFP1NCP1B_Face::isInStencil(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Zones::merge(), Champ_Fonc_Tabule_Morceaux::mettre_a_jour(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), multiplier_diviser_rho(), NettoieNoeuds::nettoie(), Discretisation_tools::nodes_to_cells(), Polyedre_poly::normale(), Champ_P1_isoP1Bulle::norme_L2(), Zone_VF::numero_sommet_local(), operation01(), operation11(), Zone_PolyMAC::orthocentrer(), Polyedriser::polyedriser(), Assembleur_P_VEFPreP1B::projete_L2(), projette(), Raffiner_anisotrope::Raffiner_anisotrope_(), Debog_Pb::read_geometry_data(), Champ_input_P0::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Fonc_MED::readOn(), Polygone::rebuild_index(), Raffiner_Simplexes::refine_domain(), Remove_elem::Remove_elem_(), Op_Conv_VEF_Face::remplir_fluent(), Zone_Cl_VEF::remplir_normales_facettes_Cl(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), remplir_sommets(), Hexaedre_VEF::reordonner(), Quadrangle_VEF::reordonner(), Segment::reordonner(), Hexaedre::reordonner_elem(), Rectangle::reordonner_elem(), Reorienter_tetraedres::Reorienter(), Reorienter_triangles::Reorienter(), Source_PDF_EF::rotate_imposed_velocity(), Op_Diff_VEFP1NCP1B_Face::test(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), Scatter::uninit_sequential_domain(), Refine_Mesh::update_cells(), Champ_P1NC_implementation::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_sommet_compo(), Champ_P1_isoP1Bulle::valeur_au_bord(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_som_lu_VEF::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_implementation_P1::value_interpolation(), Champ_implementation_Q1::value_interpolation(), Zone_VEF::vecteur_face_facette(), and Source_PDF_EF::verif_ajouter_contrib().
les_elems() [2/2]
const IntTab & Zone::les_elems () const inline
Renvoie le tableau des sommets des elements<br>(version const)
Returns
IntTab&
Signification: le tableau des sommets des elements
Contraintes: reference constante
Definition at line 415 of file Zone.h.
{
  return mes_elems;
}
References mes_elems.
Lire_Bords_a_imprimer()
Entree & Zone::Lire_Bords_a_imprimer (Entree & s)
Definition at line 187 of file Zone.cpp.
{
  Nom nom_lu;
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
  is >> motlu;
  Cerr << "Reading boundaries to be print:"  << finl;
  if(motlu!=accolade_ouverte)
    {
      Cerr << "We expected a list { ... } of boundaries to be print" << finl;
      Cerr << "and not : " << motlu << finl;
      exit();
    }
  is >> nom_lu;
  while (nom_lu != "}")
    {
      Cerr << nom_lu << " ";
      Bords_a_imprimer_.add(Nom(nom_lu));
      is >> nom_lu;
    }
  Cerr << finl;
  return is ;
}
References List_Nom::add(), Bords_a_imprimer_, Cerr, Process::exit(), and finl.
Referenced by Imprimer_flux::interpreter_().
Lire_Bords_a_imprimer_sum()
Entree & Zone::Lire_Bords_a_imprimer_sum (Entree & s)
Definition at line 210 of file Zone.cpp.
{
  Nom nom_lu;
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
  is >> motlu;
  Cerr << "Reading boundaries to be print:"  << finl;
  if(motlu!=accolade_ouverte)
    {
      Cerr << "We expected a list { ... } of boundaries to be print" << finl;
      Cerr << "and not : " << motlu << finl;
      exit();
    }
  is >> nom_lu;
  while (nom_lu != "}")
    {
      Cerr << nom_lu << " ";
      Bords_a_imprimer_sum_.add(Nom(nom_lu));
      is >> nom_lu;
    }
  Cerr << finl;
  return is ;
}
References List_Nom::add(), Bords_a_imprimer_sum_, Cerr, Process::exit(), and finl.
Referenced by Imprimer_flux_sum::interpreter_().
md_vector_elements()
const MD_Vector & Zone::md_vector_elements () const virtual
renvoie le descripteur parallele des tableaux aux elements de la zone
Definition at line 1600 of file Zone.cpp.
{
  const MD_Vector& md = mes_elems.get_md_vector();
  if (!md.non_nul())
    {
      Cerr << "Internal error in Zone::md_vector_elements(): descriptor for elements not initialized\n"
           << " You might use a buggy Domain constructor that does not build descriptors,\n"
           << " Use the following syntax to finish the domain construction\n"
           << "  Scatter ; " << domaine().le_nom() << finl;
      exit();
    }
// Pour l'instant je prends le descripteur dans le tableau mes_elems, mais on
// pourrait en stocker une copie dans la zone si ca a un interet...
  return md;
}
References Cerr, domaine(), Process::exit(), finl, TRUSTVect< _TYPE_ >::get_md_vector(), Domaine::le_nom(), mes_elems, and MD_Vector::non_nul().
Referenced by Partitionneur_Parmetis::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), creer_tableau_elements(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Zone_VEF_PreP1b::discretiser_suite(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Champ_Inc_P0_base::fixer_nb_valeurs_nodales(), Echange_contact_VDF::initialiser(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), Champ_Elem_PolyMAC::reprendre(), and Debog_Pb::write_geometry_data().
Moments_a_imprimer() [1/2]
int & Zone::Moments_a_imprimer () inline
Definition at line 163 of file Zone.h.
  {
    return Moments_a_imprimer_;
  };
References Moments_a_imprimer_.
Moments_a_imprimer() [2/2]
int Zone::Moments_a_imprimer () const inline
Definition at line 159 of file Zone.h.
  {
    return Moments_a_imprimer_;
  };
References Moments_a_imprimer_.
Referenced by Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), T_It_VDF_Face< _TYPE_ >::impr(), Op_Grad_VDF_Face::impr(), and Calculer_Moments::interpreter_().
nb_aretes()
int Zone::nb_aretes () const inline
renvoie le nombre d'aretes reelles.
Definition at line 1250 of file Zone.h.
{
  return Aretes_som.dimension(0);
}
References Aretes_som, and TRUSTTab< _TYPE_ >::dimension().
Referenced by Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), assemblerP0Pa(), assemblerP1Pa(), assemblerPaPa(), calculer_centres_gravite_aretes(), corriger(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), exemple_champ_non_homogene(), Assembleur_P_VEFPreP1B::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_secmem(), update_matrice_NeumannP0Pa(), update_matrice_NeumannP1Pa(), update_matrice_NeumannPaPa(), update_matrice_SymetrieP1Pa(), update_matrice_SymetriePaPa(), update_matriceP0Pa(), update_matriceP1Pa(), update_matricePaPa(), updatePaPa(), Zone_VEF_PreP1b::verifie_ok_arete(), and verifier().
nb_aretes_tot()
int Zone::nb_aretes_tot () const inline
renvoie le nombre d'aretes total (reelles+virtuelles).
Definition at line 1258 of file Zone.h.
{
  return Aretes_som.dimension_tot(0);
}
References Aretes_som, and TRUSTTab< _TYPE_ >::dimension_tot().
Referenced by Op_Diff_VEFP1NCP1B_Face::ajouter(), assembler(), assemblerP0Pa(), assemblerP1Pa(), assemblerPaPa(), Zone_VEF_PreP1b::construire_renum_arete_perio(), Zone_PolyMAC::discretiser(), EOS_Tools_VEF::secmembre_divU_Z(), second_membre(), and Zone_VEF_PreP1b::verifie_ok_arete().
nb_bords()
int Zone::nb_bords () const inline
Renvoie le nombre de bords de la zone.
Returns
int
Signification: le nombre de bords de la zone
Contraintes:
Definition at line 524 of file Zone.h.
{
  return mes_faces_bord.nb_bords();
}
References mes_faces_bord, and Bords::nb_bords().
Referenced by Refine_Mesh::build_new_boundary_faces_2D(), Refine_Mesh::build_new_boundary_faces_3D(), Partitionneur_base::calculer_graphe_connexions_periodiques(), Partitionneur_Tranche::chercher_direction_perio(), DomaineCutter::construire_faces_internes_ssdom(), DomaineCutter::construire_faces_raccords_ssdom(), Partitionneur_base::corriger_sommets_bord(), DecoupeBord::Decouper(), Zone_VF::discretiser(), Postraiter_domaine::ecrire(), frontiere(), nb_front_Cl(), OrienteFacesBord::oriente_faces_bord(), Zone_VF::remplir_face_numero_bord(), and renum().
nb_elem()
int Zone::nb_elem () const inline
Renvoie le nombre d'elements de la zone.
Returns
int
Signification: le nombre d'elements de la zone
Contraintes:
Definition at line 293 of file Zone.h.
{
  return mes_elems.dimension(0);
}
References TRUSTTab< _TYPE_ >::dimension(), and mes_elems.
Referenced by Op_Div_EF::ajouter(), Op_Curl_VEFP1B::ajouter(), Op_Rot_VEFP1B::ajouter(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Op_Div_VEFP1B_Elem::ajouter_elem(), Assembleur_P_EF::assembler_mat(), Op_Diff_RotRot::assembler_matrice(), assemblerP0P1(), assemblerP0Pa(), build_triofield(), Zone_VDF::calcul_h(), Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), Traitement_particulier_NS_THI::calcul_nb_elem_dir(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Hexaedre_axi::calculer_centres_gravite(), Rectangle_axi::calculer_centres_gravite(), Moyenne_volumique::calculer_convolution_champ_elem(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Dift_VEF_P1NCP1B_Face::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Dift_VEF_Face_Q1::calculer_dt_stab(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Partitionneur_base::calculer_graphe_connexions_periodiques(), Zone_EF::calculer_IPhi(), Zone_EF_axi::calculer_IPhi(), calculer_mon_centre_de_gravite(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), Op_Dift_VEF_Face::calculer_pour_post(), Polygone::calculer_volumes(), Polyedre::compute_virtual_index(), OctreeRoot::construire(), construire_elem_virt_pe_num(), DomaineCutter::construire_faces_joints_ssdom(), Domain_Graph::construire_graph_elem_elem(), Partitionneur_Fichier_Decoupage::construire_partition(), Partitionneur_Fichier_MED::construire_partition(), Partitionneur_Metis::construire_partition(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_Tranche::construire_partition(), Partitionneur_Union::construire_partition(), Scatter::corriger_espace_distant_elements_perio(), Partitionneur_base::corriger_multiperiodique(), Partitionneur_base::corriger_sommets_bord(), Champ_Fonc_MED::creer(), Hexa_VEF::creer_facette_normales(), Quadri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), Op_Div_VEFP1B_Elem::degres_liberte(), Sous_zone_VF::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), Discr_inst::discretiser_champ_fonc_don(), dump_lata(), Postraiter_domaine::ecrire(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_Lml::ecrire_domaine_lml(), DomaineCutter::ecrire_zones(), Op_Curl_VEFP1B::elements_pour_sommet(), Op_Diff_RotRot::elements_pour_sommet(), exemple_champ_non_homogene(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Champ_Inc_P0_base::fixer_nb_valeurs_nodales(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Polyedre::get_somme_nb_faces_elem(), Polygone::get_somme_nb_faces_elem(), histogramme_angle(), Domaine::imprimer(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Traitement_particulier_Solide_canal_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), Scatter::init_sequential_domain(), Champ_front_lu::initialiser(), Champ_front_recyclage::initialiser(), Scatter::interpreter(), Integrer_champ_med::interpreter(), Moyenne_volumique::interpreter(), Raffiner_isotrope_parallele::interpreter(), Create_domain_from_sous_zone::interpreter_(), VerifierCoin::interpreter_(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Scatter::mergeDomains(), Correlation_Vec_Sca_VDF::mettre_a_jour(), Assembleur_P_EF::modifier_solution(), Assembleur_P_VDF::modifier_solution(), Assembleur_P_VEF::modifier_solution(), Zone_dis_base::nb_elem(), Zone_VEF_PreP1b::nb_elem(), Champ_P1NC::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), Postraitement_lata::postraiter_liste_champs(), printOn(), Assembleur_P_VEFPreP1B::projete_L2(), Champ_Don_Fonc_txyz::readOn(), Champ_Don_Fonc_xyz::readOn(), Champ_Don_lu::readOn(), Sous_Zone::readOn(), Sous_Zone::remove_poly(), Assembleur_P_VEF::remplir(), Champ_implementation_P0::remplir_coord_noeuds(), Champ_implementation_P0::remplir_coord_noeuds_et_polys(), Champ_Q4_implementation::remplir_coord_noeuds_et_polys(), Zone_Cl_VEF::remplir_normales_facettes_Cl(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Traitement_particulier_NS_canal_VDF::remplir_Y(), Hexaedre_VEF::reordonner(), Quadrangle_VEF::reordonner(), Segment::reordonner(), Hexaedre::reordonner_elem(), Rectangle::reordonner_elem(), Precond_local::res_syst_loc_hybride(), update_matrice_NeumannP0Pa(), update_matriceP0Pa(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux(), TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux_compo(), TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_compo_(), and verifier().
nb_elem_tot()
int Zone::nb_elem_tot () const inline
Renvoie le nombre total d'elements de la zone.
Returns
int
Signification: le nombre total d'elements de la zone
Contraintes:
Definition at line 312 of file Zone.h.
{
  return mes_elems.dimension_tot(0);
}
References TRUSTTab< _TYPE_ >::dimension_tot(), and mes_elems.
Referenced by Op_Grad_EF::ajouter(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), Source_Qdm_EF::ajouter(), Source_Scalaire_EF::ajouter(), Source_PDF_EF::ajouter_(), Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Diff_EF::ajouter_scalaire_template(), Op_Dift_EF_Q1::ajouter_scalaire_template(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Conv_EF::ajouter_sous_cond_template(), Op_Diff_EF::ajouter_vectoriel_template(), Op_Dift_EF_Q1::ajouter_vectoriel_template(), Assembleur_P_EF::assembler_mat(), assemblerP0P1(), assemblerP0Pa(), Champ_Q1_EF::cal_rot_ordre1(), Champ_Face::calcul_duidxj(), Op_Diff_P1NC_barprim::calculer(), Elem_geom_base::calculer_centres_gravite(), Polyedre::calculer_centres_gravite(), Polygone::calculer_centres_gravite(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Conv_VDF_base::calculer_pour_post(), Hexaedre::calculer_volumes(), Hexaedre_axi::calculer_volumes(), Hexaedre_VEF::calculer_volumes(), Polyedre::calculer_volumes(), Polygone::calculer_volumes(), Prisme::calculer_volumes(), Quadrangle_VEF::calculer_volumes(), Rectangle::calculer_volumes(), Rectangle_2D_axi::calculer_volumes(), Rectangle_axi::calculer_volumes(), Segment::calculer_volumes(), Segment_axi::calculer_volumes(), Tetraedre::calculer_volumes(), Triangle::calculer_volumes(), Zone_EF::calculer_volumes_sommets(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), Polyedre::compute_virtual_index(), OctreeRoot::construire(), construire_elem_virt_pe_num(), Partitionneur_Metis::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_Sous_Zones::construire_partition(), Triangle::contient(), Source_PDF_EF::contribuer_a_avec(), Partitionneur_base::corriger_sommets_bord(), Op_Div_VEFP1B_Elem::degres_liberte(), Op_EF_base::dimensionner(), Op_VDF_Elem::dimensionner(), Postraiter_domaine::ecrire(), exemple_champ_non_homogene(), Zone_VDF::genere_aretes(), Champ_Q1_EF::gradient(), Champ_implementation_P0::imprime_P0(), DomaineCutter::initialiser(), Porosites::interpreter(), Porosites_champ::interpreter(), Perte_Charge_Singuliere::lire_surfaces(), Champ_Fonc_Tabule_Morceaux::mettre_a_jour(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), multiplier_diviser_rho(), Zone_dis_base::nb_elem_tot(), Assembleur_P_VEFPreP1B::projete_L2(), Sous_Zone::readOn(), Assembleur_P_VEF::remplir(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(), Precond_local::res_syst_loc_hybride(), Source_PDF_EF::rotate_imposed_velocity(), traite_bord(), Champ_Face_implementation::valeur_aux_sommets(), Champ_Q1NC_impl::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_Face_implementation::valeur_aux_sommets_compo(), Champ_Q1NC_impl::valeur_aux_sommets_compo(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Source_PDF_EF::verif_ajouter_contrib(), verifier(), Op_Div_EF::volumique(), Op_Div_PolyMAC::volumique(), Op_Div_PolyMAC_P0::volumique(), Op_Div_VDF_Elem::volumique(), and Op_Div_VEF_Elem::volumique().
nb_faces_bord() [1/3]
int Zone::nb_faces_bord () const
Renvoie le nombre de faces qui sont des bords.
Returns
int
Signification: le nombre de faces qui sont des bords
Contraintes:
Definition at line 501 of file Zone.cpp.
{
  return mes_faces_bord.nb_faces();
}
References mes_faces_bord, and Bords::nb_faces().
Referenced by DecoupeBord::Decouper(), nb_faces_frontiere(), Faces_VDF::reordonner(), and Faces_VDF::reordonner_pour_debog().
nb_faces_bord() [2/3]
int Zone::nb_faces_bord (int i) const
Renvoie le nombre de faces du i-ieme bord.
Returns
int
Signification: le nombre de faces du i-ieme bord
Contraintes:
Definition at line 622 of file Zone.cpp.
{
  return mes_faces_bord(i).nb_faces();
}
References mes_faces_bord, and Bords::nb_faces().
nb_faces_bord() [3/3]
int Zone::nb_faces_bord (Type_Face type) const
Renvoie le nombre de faces du type specifie.
Returns
int
Signification: le nombre de faces du type specifie
Contraintes:
Definition at line 1116 of file Zone.cpp.
{
  return mes_faces_bord.nb_faces(type);
}
References mes_faces_bord, and Bords::nb_faces().
nb_faces_elem()
int Zone::nb_faces_elem (int i = 0) const inline
Renvoie le nombre de face de type i
des elements geometriques constituants la zone.
Ex: les objets de la classe Prisme ont 2 types
de faces: triangle ou quadrangle.
Returns
int
Signification: le nombre de face de type i des
elements geometriques constituants la zone
Contraintes:
Definition at line 462 of file Zone.h.
{
  return elem.nb_faces(i);
}
References elem, and Elem_geom::nb_faces().
Referenced by Op_Curl_VEFP1B::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion_vectoriel(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Dift_EF_Q1::ajouter_bords(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_cas_multiscalaire(), Op_Dift_Stab_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Op_Dift_Stab_VEF_Face::ajouter_diffusion(), Op_Dift_Stab_VEF_Face::ajouter_diffusion_vectoriel(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Op_Dift_Stab_VEF_Face::ajouter_operateur_centre(), Op_Dift_Stab_VEF_Face::ajouter_operateur_centre_vectoriel(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Diff_VEF_Face_Penalise::autre_face(), Champ_front_contact_VEF::calcul_grads_locaux(), Zone_VDF::calcul_h(), Zone_EF::calculer_Bij_gen(), Zone_EF_axi::calculer_Bij_gen(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Dift_Stab_VEF_Face::calculer_coefficients(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Dift_VEF_P1NCP1B_Face::calculer_dt_stab(), Op_Dift_VEF_Face_Q1::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Op_Dift_Stab_VEF_Face::calculer_gradients(), Zone_EF::calculer_h_carre(), Zone_Poly_base::calculer_h_carre(), Zone_VEF::calculer_h_carre(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Dift_Stab_VEF_Face::calculer_min(), Zone_EF::calculer_volumes_entrelaces(), Zone_VEF::calculer_volumes_entrelaces(), Eval_Puiss_Th_QC_VEF_Face::completer(), Eval_Puiss_Th_VEF_Face::completer(), Eval_Source_C_VEF_Face::completer(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Op_VEF_Face::dimensionner(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_P1NC_implementation::filtrer_L2(), Champ_Generique_Tparoi_VEF::get_champ(), Sonde::initialiser(), Champ_front_lu::initialiser(), Porosites::interpreter(), Perte_Charge_Singuliere::lire_surfaces(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Zone_EF::modifier_pour_Cl(), Zone_VEF::modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), norm_2D_vit1(), norm_2D_vit2(), norm_3D_vit1(), norm_3D_vit2(), Champ_P1NC::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Op_Conv_VEF_Face::remplir_fluent(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), EOS_Tools_VEF::secmembre_divU_Z(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), and Op_Diff_VEF_Face_Penalise::voisinage().
nb_faces_frontiere() [1/2]
int Zone::nb_faces_frontiere () const inline
Renvoie le nombre de faces frontiere de la zone.
C'est la somme des nombres de bords, de raccords et de faces internes.
Definition at line 589 of file Zone.h.
{
  return nb_faces_bord() + nb_faces_raccord() + nb_faces_int();
}
References nb_faces_bord(), nb_faces_int(), and nb_faces_raccord().
Referenced by face_interne_conjuguee(), and init_faces_virt_bord().
nb_faces_frontiere() [2/2]
int Zone::nb_faces_frontiere (Type_Face type) const inline
Renvoie le nombre de faces frontiere de la zone
du type specifie.
C'est la somme des nombres de bords, de raccords
et de faces internes du type specifie.
Returns
int
Signification: le nombre de faces frontiere de la zone du type specifie
Contraintes:
Definition at line 1233 of file Zone.h.
{
  return
    nb_faces_bord(type) +
    nb_faces_int(type) +
    nb_faces_raccord(type);
}
References nb_faces_bord(), nb_faces_int(), and nb_faces_raccord().
Referenced by Domain_Graph::construire_graph_elem_elem(), Faces_builder::creer_faces_reeles(), Zone_VF::nb_faces_bord(), Zone_Cl_dis_base::nb_faces_Cl(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), and Zone_VEF::reordonner().
nb_faces_int() [1/3]
int Zone::nb_faces_int () const
Renvoie le nombre de face internes de la zone.
Returns
int
Signification: le nombre de face internes de la zone
Contraintes:
Definition at line 558 of file Zone.cpp.
{
  return mes_faces_int.nb_faces();
}
References mes_faces_int, and Faces_Internes::nb_faces().
Referenced by face_interne_conjuguee(), nb_faces_frontiere(), Faces_VDF::reordonner(), and Faces_VDF::reordonner_pour_debog().
nb_faces_int() [2/3]
int Zone::nb_faces_int (int i) const
Renvoie le nombre de faces de la i-ieme
liste de faces internes.
Returns
int i
Signification: le nombre de faces de la i-ieme liste
de faces internes
Contraintes:
Definition at line 683 of file Zone.cpp.
{
  return mes_faces_int(i).nb_faces();
}
References mes_faces_int, and Faces_Internes::nb_faces().
nb_faces_int() [3/3]
int Zone::nb_faces_int (Type_Face type) const
Renvoie le nombre de faces interieures du type specifie.
Returns
int
Signification: le nombre de faces interieures du type specifie
Contraintes:
Definition at line 1173 of file Zone.cpp.
{
  return mes_faces_int.nb_faces(type);
}
References mes_faces_int, and Faces_Internes::nb_faces().
nb_faces_joint() [1/3]
int Zone::nb_faces_joint () const
Renvoie le nombre de joints de la zone.
Returns
int
Signification: le nombre de joints de la zone
Contraintes:
Definition at line 520 of file Zone.cpp.
{
  return mes_faces_joint.nb_faces();
}
References mes_faces_joint, and Joints::nb_faces().
Referenced by Domain_Graph::construire_graph_elem_elem(), and Faces_builder::creer_faces_reeles().
nb_faces_joint() [2/3]
int Zone::nb_faces_joint (int i) const
Renvoie le nombre de faces du i-ieme joint.
Returns
int
Signification: nombre de faces du i-ieme joint
Contraintes:
Definition at line 642 of file Zone.cpp.
{
  return mes_faces_joint(i).nb_faces();
}
References mes_faces_joint, and Joints::nb_faces().
nb_faces_joint() [3/3]
int Zone::nb_faces_joint (Type_Face type) const
Renvoie le nombre de joints du type specifie.
Returns
int
Signification: le nombre de joints du type specifie
Contraintes:
Definition at line 1135 of file Zone.cpp.
{
  return mes_faces_joint.nb_faces(type);
}
References mes_faces_joint, and Joints::nb_faces().
nb_faces_raccord() [1/3]
int Zone::nb_faces_raccord () const
Renvoie le nombre de raccords de la zone.
Returns
int
Signification: le nombre de raccords de la zone
Contraintes:
Definition at line 539 of file Zone.cpp.
{
  return mes_faces_raccord.nb_faces();
}
References mes_faces_raccord, and Raccords::nb_faces().
Referenced by DecoupeBord::Decouper(), nb_faces_frontiere(), Faces_VDF::reordonner(), and Faces_VDF::reordonner_pour_debog().
nb_faces_raccord() [2/3]
int Zone::nb_faces_raccord (int i) const
Renvoie le nombre de faces du i-ieme raccord.
Returns
int
Signification: le nombre de faces du i-ieme raccord
Contraintes:
Definition at line 662 of file Zone.cpp.
{
  return mes_faces_raccord(i)->nb_faces();
}
References mes_faces_raccord, and Raccords::nb_faces().
nb_faces_raccord() [3/3]
int Zone::nb_faces_raccord (Type_Face type) const
Renvoie le nombre de raccords du type specifie.
Returns
int
Signification: le nombre de raccords du type specifie
Contraintes:
Definition at line 1154 of file Zone.cpp.
{
  return mes_faces_raccord.nb_faces(type);
}
References mes_faces_raccord, and Raccords::nb_faces().
nb_front_Cl()
int Zone::nb_front_Cl () const inline
Renvoie le nombre de bords
+ le nombre de raccords
+ le nombre de faces frontieres internes.
Returns
int
Signification: le nombre de frontieres ayant des
conditions aux limites.
Contraintes:
Definition at line 611 of file Zone.h.
{
  return nb_bords() +nb_raccords() + nb_frontieres_internes();
}
References nb_bords(), nb_frontieres_internes(), and nb_raccords().
Referenced by calculer_elements_voisins_bords(), calculer_h_local(), check_zone(), create_listb_from_domaine2(), create_listb_from_xyz(), create_listb_geom(), create_listb_naif(), Domaine::creer_mes_domaines_frontieres(), DecoupeBord::Decouper(), Zone_VF::discretiser(), ExtrudeParoi::extrude(), ExtrudeBord::extruder_hexa_old(), find_cl_face(), find_joint_faces(), init_faces_virt_bord(), RegroupeBord::interpreter_(), Mod_turb_hyd_base::lire_motcle_non_standard(), PlaqThVDF::mettre_a_jour(), Zone_dis_base::nb_front_Cl(), NettoieNoeuds::nettoie(), RegroupeBord::rassemble_bords(), Zone_Cl_dis_base::readOn(), and RegroupeBord::regroupe_bord().
nb_frontieres_internes()
int Zone::nb_frontieres_internes () const inline
Renvoie le nombre de frontieres internes de la zone.
Returns
int
Signification: le nombre de frontieres internes de la zone
Contraintes:
Definition at line 581 of file Zone.h.
{
  return mes_faces_int.nb_faces_internes();
}
References mes_faces_int, and Faces_Internes::nb_faces_internes().
Referenced by Refine_Mesh::build_new_internal_frontier_faces_2D(), Refine_Mesh::build_new_internal_frontier_faces_3D(), Zone_VF::discretiser(), frontiere(), nb_front_Cl(), and renum().
nb_joints()
int Zone::nb_joints () const inline
Renvoie le nombre de joints de la zone.
Returns
int
Signification: le nombre de joints de la zone
Contraintes:
Definition at line 543 of file Zone.h.
{
  return mes_faces_joint.nb_joints();
}
References mes_faces_joint, and Joints::nb_joints().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), Op_Conv_VDF< OP_TYPE >::associer_(), Scatter::calculer_espace_distant_elements(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Op_Conv_EF_Stab_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Grad_PolyMAC_Face::completer(), Op_Grad_PolyMAC_P0_Face::completer(), DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_sous_domaine(), Scatter::corriger_espace_distant_elements_perio(), dump_lata(), Postraiter_domaine::ecrire(), joint_of_pe(), Scatter::mergeDomains(), Zone_VF::nb_joints(), Op_Conv_EF_Stab_PolyMAC_Elem::preparer_calcul(), renum(), and renum_joint_common_items().
nb_raccords()
int Zone::nb_raccords () const inline
Renvoie le nombre de raccords de la zone.
Returns
int
Signification: le nombre de raccords de la zone
Contraintes:
Definition at line 562 of file Zone.h.
{
  return mes_faces_raccord.nb_raccords();
}
References mes_faces_raccord, and Raccords::nb_raccords().
Referenced by Refine_Mesh::build_new_connector_faces_2D(), Refine_Mesh::build_new_connector_faces_3D(), DomaineCutter::construire_faces_internes_ssdom(), Zone_VF::discretiser(), Postraiter_domaine::ecrire(), frontiere(), nb_front_Cl(), OrienteFacesBord::oriente_faces_bord(), and renum().
nb_som()
int Zone::nb_som () const
Renvoie le nombre de sommets de la zone.
Returns
int
Signification: le nombre de sommets de la zone
Contraintes:
Definition at line 579 of file Zone.cpp.
{
// MONOZONE pour le moment!
  return domaine().nb_som();
}
References domaine(), and Domaine::nb_som().
Referenced by Op_Curl_VEFP1B::ajouter(), Op_Rot_VEFP1B::ajouter(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Assembleur_P_EF::assembler_mat(), Op_Diff_RotRot::assembler_matrice(), assemblerP0P1(), assemblerP1P1(), assemblerP1Pa(), EDO_Pression_th_VEF::calculer_grad(), Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Op_Diff_RotRot::calculer_vorticite(), Source_PDF_EF::compute_vitesse_imposee_projete(), DomaineCutter::construire_faces_joints_ssdom(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Op_Div_VEFP1B_Elem::degres_liberte(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Postraiter_domaine::ecrire(), Op_Curl_VEFP1B::elements_pour_sommet(), exemple_champ_non_homogene(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Zone_VDF::genere_aretes(), Zone_Cl_EF::imposer_symetrie_matrice_secmem(), Source_PDF_EF::impr(), Champ_Face_PolyMAC_P0::init_ve2(), Assembleur_P_VEFPreP1B::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_solution(), Zone_dis_base::nb_som(), Zone_VEF_PreP1b::nb_som(), Postraitement_lata::postraiter_liste_champs(), Raffiner_anisotrope::Raffiner_anisotrope_(), Remove_elem::Remove_elem_(), Champ_implementation_sommet_base::remplir_coord_noeuds(), Champ_implementation_sommet_base::remplir_coord_noeuds_et_polys(), Precond_local::res_syst_loc_hybride(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), update_matrice_NeumannP1Pa(), update_matrice_SymetrieP1Pa(), update_matriceP1Pa(), updateP1P1(), Champ_Face_implementation::valeur_aux_sommets(), Champ_Q1NC_impl::valeur_aux_sommets(), Champ_Face_implementation::valeur_aux_sommets_compo(), Champ_Q1NC_impl::valeur_aux_sommets_compo(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), and Champ_implementation_P0::valeur_aux_sommets_impl().
nb_som_elem()
int Zone::nb_som_elem () const inline
Renvoie le nombre de sommets des elements geometriques
constituants la zone. Tous les elements de la zone etant
du meme type ils ont tous le meme nombre de sommets
qui est le nombre de sommet du type des elements geometriques
de la zone.
Returns
int
Signification: le nombre de sommets par element
Contraintes:
Definition at line 438 of file Zone.h.
{
  return elem.nb_som();
}
References elem, and Elem_geom::nb_som().
Referenced by Op_Diff_EF::ajouter(), Op_Dift_EF_Q1::ajouter(), Op_Div_EF::ajouter(), Op_Grad_EF::ajouter(), Op_Rot_VEFP1B::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Source_Qdm_EF::ajouter(), Source_Scalaire_EF::ajouter(), Source_PDF_EF::ajouter_(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Diff_EF::ajouter_scalaire_template(), Op_Dift_EF_Q1::ajouter_scalaire_template(), Op_Conv_EF::ajouter_sous_cond(), Op_Conv_EF::ajouter_sous_cond_template(), Op_Diff_EF::ajouter_vectoriel_template(), Op_Dift_EF_Q1::ajouter_vectoriel_template(), Op_Diff_RotRot::assembler_matrice(), Zone_EF::calculer_Bij(), Zone_EF::calculer_Bij_gen(), Zone_EF_axi::calculer_Bij_gen(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Op_Conv_EF::calculer_dt_stab(), Scatter::calculer_espace_distant_elements(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Zone_EF::calculer_IPhi(), Zone_EF_axi::calculer_IPhi(), Zone_EF::calculer_volumes_sommets(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Octree::construire(), Source_PDF_EF::contribuer_a_avec(), convert_domain_to_Domaine(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), Op_Div_VEFP1B_Elem::degres_liberte(), Op_EF_base::dimensionner(), Discr_inst::discretiser_champ_fonc_don(), Format_Post_Lml::ecrire_domaine_lml(), Op_Curl_VEFP1B::elements_pour_sommet(), Op_Diff_RotRot::elements_pour_sommet(), Champ_implementation_Q1::form_function(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Champ_Q1_EF::gradient(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Op_Grad_VEF_P1B_Face::impr(), indice_elements(), ExtrudeBord::interpreter_(), Op_Diff_VEFP1NCP1B_Face::isInStencil(), Perte_Charge_Singuliere::lire_surfaces(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Champ_Fonc_Tabule_Morceaux::mettre_a_jour(), Zone_VF::numero_sommet_local(), Assembleur_P_VEFPreP1B::projete_L2(), OctreeRoot::rang_sommet(), Champ_Uniforme_Morceaux::readOn(), Sous_Zone::readOn(), Op_Conv_VEF_Face::remplir_fluent(), Zone_Cl_VEF::remplir_normales_facettes_Cl(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), Source_PDF_EF::rotate_imposed_velocity(), Op_Diff_RotRot::sommets_pour_element(), Op_Diff_RotRot::sommets_voisins(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_Q4_implementation::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem_compo(), Champ_Q4_implementation::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_Face_implementation::valeur_aux_sommets(), Champ_Q1NC_impl::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_Face_implementation::valeur_aux_sommets_compo(), Champ_Q1NC_impl::valeur_aux_sommets_compo(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_implementation_P1::value_interpolation(), and Source_PDF_EF::verif_ajouter_contrib().
nb_som_tot()
int Zone::nb_som_tot () const
Renvoie le nombre total de sommets de la zone.
i.e. le nombre de sommets reels et virtuels
sur le processeur courant.
Returns
int
Signification: le nombre total de sommets de la zone
Contraintes:
Definition at line 601 of file Zone.cpp.
{
// MONOZONE pour le moment!
  return domaine().nb_som_tot();
}
References domaine(), and Domaine::nb_som_tot().
Referenced by Op_Div_VEFP1B_Elem::ajouter(), assembler(), Assembleur_P_EF::assembler_mat(), assemblerP0P1(), assemblerP1P1(), assemblerP1Pa(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), creer_aretes(), Faces_builder::creer_faces_reeles(), exemple_champ_non_homogene(), Champ_P1NC_implementation::filtrer_H1(), Zone_Cl_EF::imposer_symetrie(), Champ_Q4_implementation::imprime_Q4(), Zone_dis_base::nb_som_tot(), Assembleur_P_VEFPreP1B::projete_L2(), Zone_Cl_EF::remplir_type_elem_Cl(), Source_PDF_EF::rotate_imposed_velocity(), EOS_Tools_VEF::secmembre_divU_Z(), updateP1Pa(), and Champ_P1NC_implementation::valeur_aux_sommets().
nommer()
void Zone::nommer (const Nom & nom_) inline override virtual
Donne un nom a la zone.
Reimplemented from Objet_U.
Definition at line 375 of file Zone.h.
{
  nom = nom_;
}
References nom.
Referenced by Zones::comprimer(), DomaineCutter::construire_sous_domaine(), convert_domain_to_Domaine(), TroisDto2D::extraire_2D(), Extraire_surface::extraire_surface(), ExtrudeBord::extruder_hexa_old(), MaillerParallel::interpreter(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), and ScatterMED::lire_domaine().
printOn()
Sortie & Zone::printOn (Sortie & s) const override protected virtual
Ecrit la Zone sur un flot de sortie.
On ecrit le nom, le type des elements, les elements
et les bords, les bords periodiques, les joints, les
raccords et les faces internes.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 49 of file Zone.cpp.
{
  Cerr << "Writing of " << nb_elem() << " elements." << finl;
  s << nom << finl;
  s << elem << finl;
  s << mes_elems;
  s << mes_faces_bord;
  s << mes_faces_joint;
  s << mes_faces_raccord;
  s << mes_faces_int;
  return s;
}
References Cerr, elem, finl, mes_elems, mes_faces_bord, mes_faces_int, mes_faces_joint, mes_faces_raccord, nb_elem(), and nom.
Referenced by Pave::printOn().
raccord() [1/4]
Raccord & Zone::raccord (const Nom & nom_) inline
Renvoie le raccord dont le nom est specifie.
Returns
Raccord&
Signification: le raccord dont le nom est specifie
Contraintes:
Definition at line 770 of file Zone.h.
{
  return mes_faces_raccord(nom_);
}
References mes_faces_raccord.
raccord() [2/4]
const Raccord & Zone::raccord (const Nom & nom_) const inline
Renvoie le raccord dont le nom est specifie<br>(version const)
Returns
Raccord&
Signification: le raccord dont le nom est specifie
Contraintes: reference constante
Definition at line 751 of file Zone.h.
{
  return mes_faces_raccord(nom_);
}
References mes_faces_raccord.
raccord() [3/4]
Raccord & Zone::raccord (int i) inline
Renvoie le i-ieme raccord de la zone.
Returns
Raccord&
Signification: le i-ieme raccord de la zone
Contraintes:
Definition at line 993 of file Zone.h.
{
  return mes_faces_raccord(i);
}
References mes_faces_raccord.
raccord() [4/4]
const Raccord & Zone::raccord (int i) const inline
Renvoie le i-ieme raccord de la zone<br>(version const)
Returns
Raccord&
Signification: le i-ieme raccord de la zone
Contraintes: reference constante
Definition at line 974 of file Zone.h.
{
  return mes_faces_raccord(i);
}
References mes_faces_raccord.
Referenced by Echange_contact_VDF::calculer_h_autre_pb(), DecoupeBord::Decouper(), Zone_VF::discretiser(), Postraiter_domaine::ecrire(), Echange_contact_VDF::initialiser(), SupprimeBord::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), OrienteFacesBord::oriente_faces_bord(), and RegroupeBord::regroupe_bord().
rang_elem_depuis()
int Zone::rang_elem_depuis (const DoubleTab & coord, const ArrOfInt & elems, ArrOfInt & prems) const
Definition at line 1542 of file Zone.cpp.
{
  Cerr << "Zone::rang_elem_depuis: function not any more implemented" << finl;
  exit();
  return -1;
}
References Cerr, Process::exit(), and finl.
rang_elems_sommet()
void Zone::rang_elems_sommet (ArrOfInt & elems, double x, double y = 0, double z = 0) const
Definition at line 1551 of file Zone.cpp.
{
  const OctreeRoot octree = construit_octree();
  octree.rang_elems_sommet(elems,x,y,z);
}
References construit_octree(), and OctreeRoot::rang_elems_sommet().
rang_frontiere()
int Zone::rang_frontiere (const Nom & un_nom) const
Definition at line 1293 of file Zone.cpp.
{
  int i=0;
  {
    CONST_LIST_CURSEUR(Bord) curseur(mes_faces_bord);
    while(curseur)
      {
        if(curseur->le_nom() == un_nom)
          return i;
        ++curseur;
        ++i;
      }
  }
  {
    CONST_LIST_CURSEUR(Raccord) curseur(mes_faces_raccord);
    while(curseur)
      {
        if(curseur.valeur()->le_nom() == un_nom)
          return i;
        ++curseur;
        ++i;
      }
  }
  {
// Les Faces Internes :
    CONST_LIST_CURSEUR(Faces_Interne) curseur(mes_faces_int);
    while(curseur)
      {
        if(curseur->le_nom() == un_nom)
          return i;
        ++curseur;
        ++i;
      }
  }
  Cerr << "Zone::rang_frontiere(): We have not found a boundary with name " << un_nom << finl;
  exit();
  return -1;
}
References Cerr, CONST_LIST_CURSEUR, Process::exit(), finl, mes_faces_bord, mes_faces_int, and mes_faces_raccord.
Referenced by create_listb_from_domaine2(), Postraiter_domaine::ecrire(), ExtrudeBord::extruder_bord(), frontiere(), Distanceparoi::interpreter_(), SupprimeBord::interpreter_(), Zone_Cl_dis_base::readOn(), and RegroupeBord::regroupe_bord().
read_zone()
void Zone::read_zone (Entree & s)
read zone from the input stream
Definition at line 136 of file Zone.cpp.
{
  s >> nom ;
  Cerr << " Reading zone " << le_nom() << finl;
  s >> elem;
  s >> mes_elems;
  s >> mes_faces_bord;
  s >> mes_faces_joint;
  s >> mes_faces_raccord;
  s >> mes_faces_int;
}
References Cerr, elem, finl, le_nom(), mes_elems, mes_faces_bord, mes_faces_int, mes_faces_joint, mes_faces_raccord, and nom.
Referenced by Scatter::readDomainWithoutCollComm(), and readOn().
readOn()
Entree & Zone::readOn (Entree & s) override protected virtual
Lit les objets constituant une Zone
a partir d'un flot d'entree. Une fois les objets
lus on les associe a la zone.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 126 of file Zone.cpp.
{
  read_zone(s);
  check_zone();
  return s ;
}
References check_zone(), and read_zone().
renum()
void Zone::renum (const IntVect & Les_Nums)
Renumerotation des noeuds:
Le noeud de numero k devient le noeud de numero Les_Nums[k].
Definition at line 704 of file Zone.cpp.
{
  int dim0 = mes_elems.dimension(0);
  int dim1 = mes_elems.dimension(1);
  for(int i=0; i<dim0; i++)
    for(int j=0; j<dim1; j++)
      mes_elems(i,j)=Les_Nums[mes_elems(i,j)];
  for(int i=0; i<nb_bords(); i++)
    mes_faces_bord(i).renum(Les_Nums);
  for(int i=0; i<nb_joints(); i++)
    mes_faces_joint(i).renum(Les_Nums);
  for(int i=0; i<nb_raccords(); i++)
    mes_faces_raccord(i)->renum(Les_Nums);
  for(int i=0; i<nb_frontieres_internes(); i++)
    mes_faces_int(i).renum(Les_Nums);
}
References TRUSTTab< _TYPE_ >::dimension(), mes_elems, mes_faces_bord, mes_faces_int, mes_faces_joint, mes_faces_raccord, nb_bords(), nb_frontieres_internes(), nb_joints(), and nb_raccords().
Referenced by Pave::associer_domaine(), Extruder_en3::interpreter_(), Mailler::interpreter_(), and Scatter::mergeDomains().
renum_joint_common_items()
void Zone::renum_joint_common_items (const IntVect & Les_Nums, const int elem_offset)
Renumerotation des noeuds et des elements presents dans les items communs des joints
Le noeud de numero k devient le noeud de numero Les_Nums[k]
l'element de numero e devient l'element de numero e+elem_offset.
Definition at line 740 of file Zone.cpp.
{
  for (int i_joint = 0; i_joint < nb_joints(); i_joint++)
    {
      ArrOfInt& sommets_communs = mes_faces_joint[i_joint].set_joint_item(Joint::SOMMET).set_items_communs();
      for(int index=0; index<sommets_communs.size_array(); index++)
        sommets_communs[index] = Les_Nums[sommets_communs[index]];
      ArrOfInt& elements_distants = mes_faces_joint[i_joint].set_joint_item(Joint::ELEMENT).set_items_distants();
      elements_distants+= elem_offset;
    }
}
References Joint::ELEMENT, mes_faces_joint, nb_joints(), TRUSTArray< _TYPE_ >::size_array(), and Joint::SOMMET.
Referenced by Scatter::mergeDomains().
reordonner()
void Zone::reordonner () inline
Reordonne les elements suivant la convention
employe par Trio-U.
Definition at line 1208 of file Zone.h.
{
  elem.reordonner();
}
References elem, and Elem_geom::reordonner().
Referenced by Remove_elem::Remove_elem_().
self_cast() [1/2]
const Zone & Zone::self_cast (const Objet_U & r) static
Definition at line 24 of file Zone.cpp.
self_cast() [2/2]
Zone & Zone::self_cast (Objet_U & r) static
Definition at line 24 of file Zone.cpp.
set_aretes_som()
IntTab & Zone::set_aretes_som () inline
Definition at line 1287 of file Zone.h.
{
  return Aretes_som;
}
References Aretes_som.
Referenced by Zone_PolyMAC::discretiser().
set_elem_aretes()
IntTab & Zone::set_elem_aretes () inline
Definition at line 1300 of file Zone.h.
{
  return Elem_Aretes;
}
References Elem_Aretes.
Referenced by Zone_PolyMAC::discretiser().
sommet_elem()
int Zone::sommet_elem (int i, int j) const inline
Renvoie le numero (global) j-ieme sommet du i-ieme element.
Returns
int
Signification: le numero (global) j-ieme sommet du i-ieme element
Contraintes:
Definition at line 337 of file Zone.h.
{
  return mes_elems(i,j);
}
References mes_elems.
Referenced by Op_Rot_VEFP1B::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), Hexaedre::calculer_volumes(), Hexaedre_axi::calculer_volumes(), Hexaedre_VEF::calculer_volumes(), Quadrangle_VEF::calculer_volumes(), Rectangle::calculer_volumes(), Rectangle_2D_axi::calculer_volumes(), Rectangle_axi::calculer_volumes(), Segment::calculer_volumes(), Segment_axi::calculer_volumes(), Tetraedre::calculer_volumes(), Triangle::calculer_volumes(), Hexaedre::contient(), Hexaedre_axi::contient(), Hexaedre_VEF::contient(), Prisme::contient(), Quadrangle_VEF::contient(), Rectangle::contient(), Rectangle_axi::contient(), Tetraedre::contient(), Triangle::contient(), Point::contient(), Segment::contient(), Op_Curl_VEFP1B::elements_pour_sommet(), Op_Diff_RotRot::elements_pour_sommet(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Perte_Charge_Singuliere::lire_surfaces(), OctreeRoot::rang_sommet(), Sous_Zone::readOn(), Op_Diff_RotRot::sommets_pour_element(), Op_Diff_RotRot::sommets_voisins(), Champ_Q4_implementation::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem_compo(), Champ_som_lu::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems_compo(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_Face_implementation::valeur_aux_sommets(), Champ_Q1NC_impl::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_Face_implementation::valeur_aux_sommets_compo(), Champ_Q1NC_impl::valeur_aux_sommets_compo(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), and Champ_implementation_P0::valeur_aux_sommets_impl().
taille_memoire()
unsigned Zone::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Zone.cpp.
type_elem() [1/2]
Elem_geom & Zone::type_elem () inline
Renvoie un element geometrique du type de ceux
qui constituent la zone.
Returns
Elem_geom&
Signification: un element geometrique du type de ceux
qui constituent la zone
Contraintes:
Definition at line 505 of file Zone.h.
{
  return elem;
}
References elem.
type_elem() [2/2]
const Elem_geom & Zone::type_elem () const inline
Renvoie un element geometrique du type de ceux
qui constituent la zone.
(version const)
Returns
Elem_geom&
Signification: un element geometrique du type de ceux
qui constituent la zone
Contraintes: reference constante
Definition at line 484 of file Zone.h.
{
  return elem;
}
References elem.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Rectify_Mesh::apply_2D(), Refine_Mesh::apply_2D(), Rectify_Mesh::apply_3D(), Refine_Mesh::apply_3D(), Source_Dirac_VDF_Elem::associer_zones(), Source_Dirac_VEF_Face::associer_zones(), auto_build_joints(), build_triofield(), Eval_Dirac_VDF_Elem::calculer_terme_source(), Eval_Dirac_VEF_Face::calculer_terme_source_non_standard(), Eval_Dirac_VEF_Face::calculer_terme_source_standard(), Rectify_Mesh::check_cell_type(), Refine_Mesh::check_cell_type(), check_internal_diagonal(), check_positive_volumes(), check_zone(), Reordonner_faces_periodiques::chercher_direction_perio(), choose_internal_diagonal(), Zones::comprimer(), compute_cell_qualities(), DomaineCutter::construire_faces_joints_ssdom(), Domain_Graph::construire_graph_elem_elem(), Zone_VEF_PreP1b::construire_renum_arete_perio(), DomaineCutter::construire_sous_domaine(), convert_domain_to_Domaine(), Scatter::corriger_espace_distant_elements_perio(), Champ_Fonc_MED::creer(), creer_aretes(), Faces_builder::creer_faces_reeles(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Zone_EF::discretiser(), Zone_Poly_base::discretiser(), Zone_VF::discretiser(), Zone_VDF::discretiser(), Zone_VEF::discretiser(), VEF_discretisation::discretiser_champ_fonc_don(), Champ_Generique_Interpolation::discretiser_domaine(), Format_Post_Med::ecrire_champ_med(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine(), Format_Post_Lml::ecrire_domaine_lml(), Postraitement_lata::ecrire_zone(), ensure_positive_volumes(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), ExtrudeBord::extruder_bord(), Extruder::extruder_hexa(), Faces_builder::faces_element_reference(), Octree_Zone::find_elements(), find_joint_faces(), Champ_input_P0::getTemplate(), histogramme_angle(), Scatter::interpreter(), Interprete_geometrique_base::interpreter(), MaillerParallel::interpreter(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extruder_en3::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), Mailler::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), VerifierCoin::interpreter_(), Polygone_poly::normale(), OrienteFacesBord::oriente_faces_bord(), Polyedriser::polyedriser(), projette(), Raffiner_anisotrope::Raffiner_anisotrope_(), OctreeFloor::rang_elem_depuis_loc(), OctreeFloor::rang_elem_loc(), Debog_Pb::read_geometry_data(), Raffiner_Simplexes::refine_domain(), Remove_elem::Remove_elem_(), Zone_Cl_VEF::remplir_type_elem_Cl(), Reorienter_tetraedres::Reorienter(), Reorienter_triangles::Reorienter(), Transformer::transformation_complete(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), Zone_VEF::typer_elem(), Zone_EF::typer_elem(), Zone_Poly_base::typer_elem(), and Transformer::verifie_type_elem().
typer()
void Zone::typer (const Nom & typ) inline
Type les elements de la zone avec le
nom passe en parametre. Et associe le type
d'element a la zone.
Definition at line 632 of file Zone.h.
{
  elem.typer(typ);
  elem.associer_zone(*this);
}
References Elem_geom::associer_zone(), elem, and Deriv_::typer().
Referenced by Champ_Generique_Extraction::completer(), convert_domain_to_Domaine(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), TroisDto2D::extraire_2D(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), ExtrudeBord::extruder_hexa_old(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Polyedriser::polyedriser(), Raffiner_anisotrope::Raffiner_anisotrope_(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), Pave::typer_(), Zone_VEF::typer_elem(), Zone_EF::typer_elem(), Zone_Poly_base::typer_elem(), and Refine_Mesh::update_octree().
volume_total()
double Zone::volume_total () const
< Pas calcule ???
Definition at line 1616 of file Zone.cpp.
{
  assert(volume_total_ >= 0.); //!< Pas calcule ???
  return volume_total_;
}
References volume_total_.
Referenced by Navier_Stokes_std::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Terme_Source_Canal_perio::source_convection_diffusion(), and Terme_Source_Canal_perio_VDF_P0::source_convection_diffusion().
Member Data Documentation
Aretes_som
IntTab Zone::Aretes_som protected
Definition at line 221 of file Zone.h.
Referenced by arete_sommets(), aretes_som(), calculer_centres_gravite_aretes(), creer_aretes(), nb_aretes(), nb_aretes_tot(), and set_aretes_som().
Bords_a_imprimer_
List_Nom Zone::Bords_a_imprimer_ protected
Definition at line 246 of file Zone.h.
Referenced by associer_Bords_a_imprimer(), Bords_a_imprimer(), and Lire_Bords_a_imprimer().
Bords_a_imprimer_sum_
List_Nom Zone::Bords_a_imprimer_sum_ protected
Definition at line 247 of file Zone.h.
Referenced by associer_Bords_a_imprimer_sum(), Bords_a_imprimer_sum(), and Lire_Bords_a_imprimer_sum().
cached_elements_
ArrsOfInt Zone::cached_elements_ mutable private
Definition at line 255 of file Zone.h.
Referenced by chercher_elements().
cached_positions_
DoubleTabs Zone::cached_positions_ mutable private
Definition at line 254 of file Zone.h.
Referenced by chercher_elements().
cg_moments_
ArrOfDouble Zone::cg_moments_ protected
Definition at line 238 of file Zone.h.
Referenced by calculer_mon_centre_de_gravite(), cg_moments(), and exporter_mon_centre_de_gravite().
deriv_octree_
Deriv_OctreeRoot Zone::deriv_octree_ mutable protected
Definition at line 237 of file Zone.h.
Referenced by chercher_elements(), construit_octree(), and invalide_octree().
elem
Elem_geom Zone::elem protected
Definition at line 216 of file Zone.h.
Referenced by calculer_centres_gravite(), calculer_volumes(), check_zone(), Pave::lire_front(), nb_faces_elem(), nb_som_elem(), printOn(), read_zone(), reordonner(), type_elem(), and typer().
Elem_Aretes
IntTab Zone::Elem_Aretes protected
Definition at line 223 of file Zone.h.
Referenced by creer_aretes(), elem_aretes(), and set_elem_aretes().
elem_virt_pe_num_
IntTab Zone::elem_virt_pe_num_ protected
Definition at line 243 of file Zone.h.
Referenced by construire_elem_virt_pe_num(), and elem_virt_pe_num().
ind_faces_virt_bord_
ArrOfInt Zone::ind_faces_virt_bord_ protected
contient les indices des faces virtuelles de bord
Definition at line 234 of file Zone.h.
Referenced by ind_faces_virt_bord(), and init_faces_virt_bord().
info_obj
const Type_info Zone::info_obj static
Definition at line 51 of file Zone.h.
le_domaine
Ref_Domaine Zone::le_domaine protected
Definition at line 214 of file Zone.h.
Referenced by associer_domaine(), Pave::associer_domaine(), and domaine().
mes_elems
IntTab Zone::mes_elems protected
Definition at line 218 of file Zone.h.
Referenced by check_zone(), construire_elem_virt_pe_num(), les_elems(), Pave::lire_Noeuds(), Pave::maille_sommet(), md_vector_elements(), nb_elem(), nb_elem_tot(), printOn(), read_zone(), renum(), and sommet_elem().
mes_faces_bord
Bords Zone::mes_faces_bord protected
Definition at line 226 of file Zone.h.
Referenced by bord(), check_zone(), comprimer(), correct_type_of_borders_after_merge(), ecrire_noms_bords(), faces_bord(), fixer_premieres_faces_frontiere(), frontiere(), nb_bords(), nb_faces_bord(), printOn(), rang_frontiere(), read_zone(), Pave::readOn(), and renum().
mes_faces_int
Faces_Internes Zone::mes_faces_int protected
Definition at line 228 of file Zone.h.
Referenced by check_zone(), comprimer(), correct_type_of_borders_after_merge(), ecrire_noms_bords(), face_interne_conjuguee(), faces_int(), faces_interne(), frontiere(), nb_faces_int(), nb_frontieres_internes(), printOn(), rang_frontiere(), read_zone(), Pave::readOn(), and renum().
mes_faces_joint
Joints Zone::mes_faces_joint protected
Definition at line 231 of file Zone.h.
Referenced by check_zone(), comprimer_joints(), correct_type_of_borders_after_merge(), faces_joint(), fixer_premieres_faces_frontiere(), joint(), joint_of_pe(), nb_faces_joint(), nb_joints(), printOn(), read_zone(), Pave::readOn(), renum(), and renum_joint_common_items().
mes_faces_raccord
Raccords Zone::mes_faces_raccord protected
Definition at line 227 of file Zone.h.
Referenced by check_zone(), comprimer(), correct_type_of_borders_after_merge(), ecrire_noms_bords(), faces_raccord(), fixer_premieres_faces_frontiere(), frontiere(), nb_faces_raccord(), nb_raccords(), printOn(), raccord(), rang_frontiere(), read_zone(), Pave::readOn(), and renum().
Moments_a_imprimer_
int Zone::Moments_a_imprimer_ protected
Definition at line 248 of file Zone.h.
Referenced by Moments_a_imprimer().
nom
Nom Zone::nom protected
Definition at line 213 of file Zone.h.
Referenced by check_zone(), le_nom(), Pave::lire_Noeuds(), nommer(), printOn(), read_zone(), and Pave::readOn().
volume_total_
double Zone::volume_total_ private
Definition at line 252 of file Zone.h.
Referenced by calculer_mon_centre_de_gravite(), volume_total(), and Zone().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Zone.h
src/Kernel/Geometrie/Faces_builder.cpp
src/Kernel/Geometrie/Zone.cpp