TRUST: Memoire_ptr Class Reference
Memoire_ptr Class Reference
Pointeur dans la Memoire de TRUST pour un Objet_U.
#include <Memoire_ptr.h>
Public Member Functions
Memoire_ptr (Objet_U *ptr=0)
Constructeur.
int libre () const
Indique si le pointeur memoire est libre, c'est-a-dire s'il pointe sur un
Objet_U non nul.
void set (Objet_U *ptr)
Affecte un Objet_U a un pointeur memoire.
Objet_U & obj ()
Retourne une reference sur l'Objet_U pointe par le pointeur memoire.
Memoire_ptr & operator= (const Memoire_ptr &)
Operateur d'affectation entre pointeurs memoire
Dans le cas A=B, l'Objet_U pointe par A est l'Objet_U pointe par B.
Public Attributes
int next
Private Attributes
Objet_U * o_ptr
Detailed Description
Pointeur dans la Memoire de TRUST pour un Objet_U.
See also
Objet_U Memoire
Definition at line 25 of file Memoire_ptr.h.
Constructor & Destructor Documentation
Memoire_ptr()
Memoire_ptr::Memoire_ptr (Objet_U * ptr = 0)
Constructeur.
Definition at line 33 of file Memoire_ptr.cpp.
                                     : o_ptr(ptr)
{
  next=-1;
}
References next.
Member Function Documentation
libre()
int Memoire_ptr::libre () const inline
Indique si le pointeur memoire est libre, c'est-a-dire s'il pointe sur un
Objet_U non nul.
Returns
int
Signification: 1 si le pointeur est libre
Contraintes:
Definition at line 145 of file Memoire_ptr.h.
{
  return o_ptr==0;
}
References o_ptr.
Referenced by Memoire::rang().
obj()
Objet_U & Memoire_ptr::obj () inline
Retourne une reference sur l'Objet_U pointe par le pointeur memoire.
Returns
Objet_U&
Signification: reference sur l'Objet_U pointe
Contraintes:
Definition at line 184 of file Memoire_ptr.h.
{
  assert(o_ptr!=0);
  return *o_ptr;
}
References o_ptr.
Referenced by Memoire::imprime(), Memoire::objet_u(), Memoire::objet_u_ptr(), and Memoire::rang().
operator=()
Memoire_ptr & Memoire_ptr::operator= (const Memoire_ptr & mptr) inline
Operateur d'affectation entre pointeurs memoire
Dans le cas A=B, l'Objet_U pointe par A est l'Objet_U pointe par B.
Returns
Memoire_ptr&
Signification: le pointeur memoire A
Contraintes:
Definition at line 206 of file Memoire_ptr.h.
{
  o_ptr=mptr.o_ptr;
  next=mptr.next;
  return *this;
}
References next, and o_ptr.
set()
void Memoire_ptr::set (Objet_U * ptr) inline
Affecte un Objet_U a un pointeur memoire.
Definition at line 164 of file Memoire_ptr.h.
{
  o_ptr=ptr;
}
References o_ptr.
Referenced by Memoire::add(), and Memoire::suppr().
Member Data Documentation
next
int Memoire_ptr::next
Definition at line 29 of file Memoire_ptr.h.
Referenced by Memoire::add(), Memoire_ptr(), operator=(), and Memoire::suppr().
o_ptr
Objet_U* Memoire_ptr::o_ptr private
Definition at line 37 of file Memoire_ptr.h.
Referenced by libre(), obj(), operator=(), and set().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Memoire_ptr.h
src/Kernel/Utilitaires/Memoire_ptr.cpp