TRUST: Echange_contact_Correlation_VEF Class Reference
Echange_contact_Correlation_VEF Class Reference
#include <Echange_contact_Correlation_VEF.h>
Public Member Functions
Echange_contact_Correlation_VEF ()
~Echange_contact_Correlation_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double) override
int compatible_avec_eqn (const Equation_base &) const override
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Temperature_imposee_paroi sont compatibles
avec une equation dont le domaine est la Thermique
ou bien indetermine.
void completer () override
virtual void imprimer (double) const
virtual int limpr (double, double) const
virtual double calculer_coefficient_echange (int i)
double getU (int i) const
double getT (int i) const
double getMu (int i) const
double getLambda (int i) const
double getRho (int i) const
double getCp () const
double getDh (int i) const
double getQh () const
Public Member Functions inherited from Temperature_imposee_paroi
Temperature_imposee_paroi ()
~Temperature_imposee_paroi ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int compatible_avec_eqn (const Equation_base &) const override
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Temperature_imposee_paroi sont compatibles
avec une equation dont le domaine est la Thermique
ou bien indetermine.
Public Member Functions inherited from Scalaire_impose_paroi
Scalaire_impose_paroi ()
~Scalaire_impose_paroi ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int compatible_avec_eqn (const Equation_base &) const override
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Scalaire_imposee_paroi sont compatibles
avec une equation dont le domaine est la Thermique, la Concentration
ou bien indetermine.
int compatible_avec_discr (const Discretisation_base &) const override
Verifie que les conditions aux limites sont
compatiblea avec la discretisation specifiees en parametre.
Des CL de type Scalaire_imposee_paroi sont compatibles
avec une discretisation de type VEF.
Public Member Functions inherited from Dirichlet
Dirichlet ()
~Dirichlet () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double val_imp (int i) const
Renvoie la valeur imposee sur la i-eme composante
du champ a la frontiere au temps par defaut du champ_front.
virtual double val_imp (int i, int j) const
Renvoie la valeur imposee sur la (i,j)-eme composante
du champ a la frontiere au temps par defaut du champ_front.
virtual double val_imp_au_temps (double temps, int i) const
Renvoie la valeur imposee sur la i-eme composante
du champ a la frontiere au temps precise.
virtual double val_imp_au_temps (double temps, int i, int j) const
Renvoie la valeur imposee sur la (i,j)-eme composante
du champ a la frontiere au temps precise.
void verifie_ch_init_nb_comp () const override
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
Public Member Functions inherited from Cond_lim_base
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Echange_contact_Correlation_VEF & self_cast (Objet_U &)
static const Echange_contact_Correlation_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Temperature_imposee_paroi
static Objet_U * cree_instance ()
static const Type_info * info ()
static Temperature_imposee_paroi & self_cast (Objet_U &)
static const Temperature_imposee_paroi & self_cast (const Objet_U &)
Static Public Member Functions inherited from Scalaire_impose_paroi
static Objet_U * cree_instance ()
static const Type_info * info ()
static Scalaire_impose_paroi & self_cast (Objet_U &)
static const Scalaire_impose_paroi & self_cast (const Objet_U &)
Static Public Member Functions inherited from Dirichlet
static const Type_info * info ()
static Dirichlet & self_cast (Objet_U &)
static const Dirichlet & self_cast (const Objet_U &)
Static Public Member Functions inherited from Cond_lim_base
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Temperature_imposee_paroi
static const Type_info info_obj
Static Public Attributes inherited from Scalaire_impose_paroi
static const Type_info info_obj
Static Public Attributes inherited from Dirichlet
static const Type_info info_obj
Static Public Attributes inherited from Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a: Dirichlet::readOn(Entree&)
void calculer_CL ()
void calculer_Q ()
void calculer_prop_physique ()
void init ()
void calculer_Vitesse ()
void calculer_Tfluide ()
void calculer_h_solide (DoubleTab &)
double pdt_scalSqrt (const Zone_VEF &, int, int, int, int, double)
double pdt_scal (const Zone_VEF &, int, int, int, int, double)
double surfacesVEF (const Zone_VEF &, int, int)
void init_tab_echange ()
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a: Dirichlet::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a: Dirichlet::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a: Cond_lim_base::readOn(Entree&)
Protected Member Functions inherited from Cond_lim_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
IntVect correspondance_solide_fluide
DoubleTab autre_h
int Reprise_temperature
double T_CL0
double T_CL1
CL sur le domaine. En seq. = Tinf et Tsup ; En parallele = Tvoisin.
double Tinf
double Tsup
Temperature entree, sortie.
int dir
Direction du cylindre.
Parser_U lambda_T
Parser_U mu_T
Parser_U rho_T
Parser_U fct_Nu
Parser_U fct_vol
Parser_U fct_Dh
double dt_impr
double Cp
double debit
double xinf
double xsup
DoubleVect vol
volumes des tranches Sdz du volume suivant la direction de l'ecoulement
DoubleVect coord
coordonnees des points de discretisation 1D
int N
nb de points du maillage 1D pour la vitesse et la temperature
DoubleVect U
DoubleVect T
inconnues fluides vitesse et temperature
DoubleVect Qvol
puissance volumique dans le fluide 1D
DoubleVect rho
DoubleVect mu
DoubleVect lambda
DoubleVect diam
tableau des proprietes physiques du fluide a un instant donne
DoubleVect h_correlation
le coeff d'echange par correlation
DoubleTab h_solide
le coeff d'echange par correlation
DoubleVect flux_radiatif
le flux radiatif entre patch
Protected Attributes inherited from Cond_lim_base
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Private Attributes
int avec_rayo
double emissivite
IntTab patches_rayo
IntVect nb_faces_patch
IntVect correspondance_face_patch
IntTab correspondance_fluide_patch
Detailed Description
Definition at line 36 of file Echange_contact_Correlation_VEF.h.
Constructor & Destructor Documentation
Echange_contact_Correlation_VEF()
Echange_contact_Correlation_VEF::Echange_contact_Correlation_VEF ()
Definition at line 30 of file Echange_contact_Correlation_VEF.cpp.
~Echange_contact_Correlation_VEF()
Echange_contact_Correlation_VEF::~Echange_contact_Correlation_VEF ()
Definition at line 30 of file Echange_contact_Correlation_VEF.cpp.
Member Function Documentation
calculer_CL()
void Echange_contact_Correlation_VEF::calculer_CL () protected
Calcule les CL a appliquer sur l'equation d'energie
Definition at line 375 of file Echange_contact_Correlation_VEF.cpp.
{
  Schema_Comm schema_comm;
  const Joints& joints = zone_Cl_dis().zone().faces_joint();
  const int nb_voisins = joints.size();
  ArrOfInt send_pe_list(nb_voisins);
  int i;
  for (i = 0; i < nb_voisins; i++)
    send_pe_list[i] = joints[i].PEvoisin();
  schema_comm.set_send_recv_pe_list(send_pe_list, send_pe_list);
  const double ymin = coord(1);
  const double ymax = coord(N-2);
  const double Tmin = T(1);
  const double Tmax = T(N-2);
  T_CL0 = Tinf;
  T_CL1 = Tsup;
  schema_comm.begin_comm();
  for (i = 0; i < nb_voisins; i++)
    {
      const int pe = send_pe_list[i];
      schema_comm.send_buffer(pe) << ymin << ymax << Tmin << Tmax;
    }
  schema_comm.echange_taille_et_messages();
  for (i = 0; i < nb_voisins; i++)
    {
      const int pe = send_pe_list[i];
      double ymin_voisin, ymax_voisin, Tmin_voisin, Tmax_voisin;
      schema_comm.recv_buffer(pe) >> ymin_voisin >> ymax_voisin >> Tmin_voisin >> Tmax_voisin;
      if (ymax_voisin < ymin)
        T(0) = T_CL0 = 0.5 * (Tmax_voisin + Tmin);
      else if (ymin_voisin > ymax)
        T(N-1) = T_CL1 = 0.5 * (Tmin_voisin + Tmax);
      else
        {
          Cerr << "Erreur dans Echange_contact_Correlation_VEF::calculer_CL() (decoupage incompatible ?)";
          exit();
        }
    }
  schema_comm.end_comm();
}
References Schema_Comm::begin_comm(), Cerr, coord, Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Process::exit(), Zone::faces_joint(), N, Schema_Comm::recv_buffer(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), liste::size(), T, T_CL0, T_CL1, Tinf, Tsup, Zone_Cl_dis_base::zone(), and Cond_lim_base::zone_Cl_dis().
Referenced by mettre_a_jour().
calculer_coefficient_echange()
double Echange_contact_Correlation_VEF::calculer_coefficient_echange (int i) virtual
Calcule le coeff d echange suivant la correlation entree dans le jdd
Definition at line 438 of file Echange_contact_Correlation_VEF.cpp.
{
  double Re,Pr;
  Re = std::fabs(getQh()*getDh(i)/getMu(i));
  Pr = getMu(i)*getCp()/getLambda(i);
  fct_Nu.setVar("Re",Re);
  fct_Nu.setVar("Pr",Pr);
  return fct_Nu.eval()*getLambda(i)/getDh(i);
}
References Parser_U::eval(), fct_Nu, getCp(), getDh(), getLambda(), getMu(), getQh(), and Parser_U::setVar().
Referenced by completer(), and mettre_a_jour().
calculer_h_solide()
void Echange_contact_Correlation_VEF::calculer_h_solide (DoubleTab & tab) protected
Calcule le coeff d echange local dans la maille solide.
< la conductivite est un Champ uniforme
Definition at line 230 of file Echange_contact_Correlation_VEF.cpp.
{
// forcement local
  const Equation_base& mon_eqn = zone_Cl_dis().equation();
  const Milieu_base& mon_milieu = mon_eqn.milieu();
  const Zone_VEF& zvef = ref_cast(Zone_VEF,zone_Cl_dis().zone_dis().valeur());
  const Front_VF& ma_front_vf = ref_cast(Front_VF,frontiere_dis());
  const IntTab& face_voisins = zvef.face_voisins();
  int nb_comp = mon_milieu.conductivite()->nb_comp();
  const int nb_faces_bord = ma_front_vf.nb_faces();
  const int ndeb = ma_front_vf.num_premiere_face();
  const int nfin = ndeb + nb_faces_bord;
  if(!sub_type(Champ_Uniforme,mon_milieu.conductivite().valeur()))
    {
      const DoubleTab& tab_lambda = mon_milieu.conductivite().valeurs();
      for (int face=ndeb; face<nfin; face++)
        {
          int elem =  face_voisins(face,0);
          if(elem == -1)
            elem =  face_voisins(face,1);
          for(int i=0; i<nb_comp; i++)
            tab(face-ndeb,i) = pdt_scalSqrt(zvef,face,face,elem,dimension,tab_lambda(elem,i)) ;
        }
    }
  else  //!< la conductivite est un Champ uniforme
    {
      const DoubleTab& tab_lambda = mon_milieu.conductivite().valeurs();
      for (int face=ndeb; face<nfin; face++)
        {
          int elem =  face_voisins(face,0);
          if(elem == -1)
            elem =  face_voisins(face,1);
          for(int i=0; i<nb_comp; i++)
            {
              tab(face-ndeb,i) = pdt_scalSqrt(zvef,face,face,elem,dimension,tab_lambda(0,i));
            }
        }
    }
}
References Milieu_base::conductivite(), Objet_U::dimension, MorEqn::equation(), Zone_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Equation_base::milieu(), Champ_Don::nb_comp(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), pdt_scalSqrt(), ref_cast, sub_type, Deriv_Champ_Don_base::valeur(), valeur(), Champ_Don::valeurs(), and Cond_lim_base::zone_Cl_dis().
Referenced by completer(), and mettre_a_jour().
calculer_prop_physique()
void Echange_contact_Correlation_VEF::calculer_prop_physique () protected
Calcule rho, mu et lambda du fluide pour la temperature courante
Definition at line 422 of file Echange_contact_Correlation_VEF.cpp.
{
  for (int i=0; i<N; i++)
    {
      rho_T.setVar("T",T(i));
      mu_T.setVar("T",T(i));
      lambda_T.setVar("T",T(i));
      rho(i) = rho_T.eval();
      mu(i) = mu_T.eval();
      lambda(i) = lambda_T.eval();
    }
}
References Parser_U::eval(), lambda, lambda_T, mu, mu_T, N, rho, rho_T, Parser_U::setVar(), and T.
Referenced by completer(), and mettre_a_jour().
calculer_Q()
void Echange_contact_Correlation_VEF::calculer_Q () protected
Calcul du terme source de puissance volumique dans l'equation d'energie 1D fluide.
Definition at line 452 of file Echange_contact_Correlation_VEF.cpp.
{
  const Zone_VEF& ma_zvef = ref_cast(Zone_VEF,zone_Cl_dis().zone_dis().valeur());
  const Front_VF& ma_front_vf = ref_cast(Front_VF,frontiere_dis());
  const int ndeb = ma_front_vf.num_premiere_face();
  const int nb_faces_bord = ma_front_vf.nb_faces();
  const IntTab& face_voisins = ma_zvef.face_voisins();
  DoubleTab& Tp= champ_front()->valeurs();
  Qvol=0.;
  for(int iface=0; iface<nb_faces_bord; iface++)
    {
      int face = ndeb+iface;
      int corresp = correspondance_solide_fluide(iface);
      int elem =  face_voisins(face,0);
      if(elem == -1)
        elem =  face_voisins(face,1);
      Qvol(corresp)+=h_correlation(corresp)*(Tp(iface,0)-T(corresp))*surfacesVEF(ma_zvef,face,dimension);
    }
  for (int i=0; i<N; i++)
    Qvol(i)/=vol(i);
}
References Cond_lim_base::champ_front(), correspondance_solide_fluide, Objet_U::dimension, Zone_VF::face_voisins(), Cond_lim_base::frontiere_dis(), h_correlation, N, Front_VF::nb_faces(), Front_VF::num_premiere_face(), Qvol, ref_cast, surfacesVEF(), T, valeur(), Champ_front::valeurs(), vol, and Cond_lim_base::zone_Cl_dis().
Referenced by mettre_a_jour().
calculer_Tfluide()
void Echange_contact_Correlation_VEF::calculer_Tfluide () protected
Calcule la temperature 1D dans le fluide en resolvant la conservation de l'energie
< diagonale
< sous-diagonale
< sur-diagonale
< schema amont pour le transport
Definition at line 654 of file Echange_contact_Correlation_VEF.cpp.
{
  const Equation_base& mon_eqn = zone_Cl_dis().equation();
  const double dt = mon_eqn.schema_temps().pas_de_temps();
  DoubleVect ma(N); //!< diagonale
  DoubleVect mb(N-1); //!< sous-diagonale
  DoubleVect mc(N-1); //!< sur-diagonale
  DoubleVect sm(N);
  const int sgn = (debit>0) ? 1 : -1; //!< schema amont pour le transport
  ma(0) = 1.;
  ma(N-1) = 1.;
  sm(0) = T_CL0;
  sm(N-1) = T_CL1;
  mc(0) = 0.;
  mb(N-2) = 0.;
  int i;
  for (i=1; i<N-1; i++)
    {
      const double dtrhoCp = dt/rho(i)/Cp;
      const double dz1 = coord(i+1)-coord(i);
      const double dz2 = coord(i)-coord(i-1);
      const double l1 = 0.5*(lambda(i+1)+lambda(i));
      const double l2 = 0.5*(lambda(i)+lambda(i-1));
      ma(i)=1+dtrhoCp*(sgn*Cp*debit/dz1+2*(l1/dz1+l2/dz2)/(dz1+dz2));
      sm(i) = T(i)+dtrhoCp*Qvol(i);
      mc(i) = dtrhoCp*(0.5*(1-sgn)*Cp*debit/dz1-2*l1/dz1/(dz1+dz2));
      mb(i-1) = dtrhoCp*(-2*l2/dz2/(dz1+dz2));
      mb(i-1) += dtrhoCp*(-0.5*(1+sgn)*Cp*debit/dz1);
    }
  DoubleVect xx(N);
  xx=0.;
  Solv_TDMA::resoudre(ma,mb,mc,sm,xx,N);
  for (i=0; i<N; i++)
    T(i) = xx(i);
}
References coord, Cp, debit, MorEqn::equation(), lambda, N, Schema_Temps_base::pas_de_temps(), Qvol, Solv_TDMA::resoudre(), rho, Equation_base::schema_temps(), sgn, T, T_CL0, T_CL1, and Cond_lim_base::zone_Cl_dis().
Referenced by mettre_a_jour().
calculer_Vitesse()
void Echange_contact_Correlation_VEF::calculer_Vitesse () protected
Calcule la vitesse par conservation de la masse
Definition at line 644 of file Echange_contact_Correlation_VEF.cpp.
{
  for (int i=0; i<N; i++)
    U(i) = debit/rho(i);
}
References debit, N, rho, and U.
Referenced by mettre_a_jour().
compatible_avec_eqn()
int Echange_contact_Correlation_VEF::compatible_avec_eqn (const Equation_base & eqn) const override virtual
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Temperature_imposee_paroi sont compatibles
avec une equation dont le domaine est la Thermique
ou bien indetermine.
Returns
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Reimplemented from Temperature_imposee_paroi.
Definition at line 913 of file Echange_contact_Correlation_VEF.cpp.
{
  if ( sub_type(Conduction, eqn) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
References Cond_lim_base::err_pas_compatible(), and sub_type.
completer()
void Echange_contact_Correlation_VEF::completer (void) override virtual
Complete et initialise les attributs de la classe
Reimplemented from Cond_lim_base.
Definition at line 289 of file Echange_contact_Correlation_VEF.cpp.
{
  init();
  T=std::min(Tinf,Tsup);
  calculer_prop_physique();
  if (T(0)==Tinf)
    U=debit/rho(0);
  else U = debit/rho(N-1);
  const Equation_base& mon_eqn = zone_Cl_dis().equation();
  const Milieu_base& mon_milieu = mon_eqn.milieu();
  const Front_VF& ma_front_vf = ref_cast(Front_VF,frontiere_dis());
  const int nb_faces_bord = ma_front_vf.nb_faces();
  int nb_comp = mon_milieu.conductivite()->nb_comp();
  h_solide.resize(nb_faces_bord,nb_comp);
  for (int i=0; i<N; i++)
    {
      h_correlation(i) = calculer_coefficient_echange(i);
    }
  calculer_h_solide(h_solide);
  DoubleTab& Tparoi =champ_front().valeur().valeurs();
  Tparoi.resize(nb_faces_bord,nb_comp);
  const DoubleTab& Ts = mon_eqn.inconnue().valeurs();
  const Zone_VEF& zvef = ref_cast(Zone_VEF,zone_Cl_dis().zone_dis().valeur());
  const IntTab& face_voisins = zvef.face_voisins();
  const int ndeb = ma_front_vf.num_premiere_face();
  for (int ii=0; ii<nb_faces_bord; ii++)
    {
      double Tint=0.;
      int face = ndeb+ii;
      int elem =  face_voisins(face,0);
      if(elem == -1)
        elem =  face_voisins(face,1);
// on recupere les faces 2, 3 et 4 de l'element contenant "face"
      int face2 = zvef.elem_faces(elem,0);
      int face3 = zvef.elem_faces(elem,1);
      if (face2 == face)
        face2 = zvef.elem_faces(elem,dimension);
      else if (face3 == face)
        face3 = zvef.elem_faces(elem,dimension);
      Tint += pdt_scal(zvef,face,face2,elem,dimension,1.)*Ts(face2) + pdt_scal(zvef,face,face3,elem,dimension,1.)*Ts(face3);
      if(dimension == 3)
        {
          int face4 = zvef.elem_faces(elem,2);
          if (face4 == face)
            face4 = zvef.elem_faces(elem,dimension);
          Tint += pdt_scal(zvef,face,face4,elem,dimension,1.)*Ts(face4);
        }
      Tint *= -1./pdt_scal(zvef,face,face,elem,dimension,1.);
      Tparoi(ii,0) = (h_solide(ii,0)*Tint+ h_correlation(correspondance_solide_fluide(ii))*T(correspondance_solide_fluide(ii)))/(h_solide(ii,0)+h_correlation(correspondance_solide_fluide(ii)));
    }
  init_tab_echange();
// Mise a jour car pas de dependance a des donnees d un autre probleme
// dans le cas de probleme couple
// Methode completer() peut etre a remplacer par methode initialiser()
  const double temps = mon_eqn.schema_temps().temps_courant();
  mettre_a_jour(temps);
}
References calculer_coefficient_echange(), calculer_h_solide(), calculer_prop_physique(), Cond_lim_base::champ_front(), Milieu_base::conductivite(), correspondance_solide_fluide, debit, Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_voisins(), Cond_lim_base::frontiere_dis(), h_correlation, h_solide, Equation_base::inconnue(), init(), init_tab_echange(), mettre_a_jour(), Equation_base::milieu(), N, Champ_Don::nb_comp(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), pdt_scal(), ref_cast, TRUSTTab< _TYPE_ >::resize(), rho, Equation_base::schema_temps(), T, Schema_Temps_base::temps_courant(), Tinf, Tsup, U, Deriv_Champ_front_base::valeur(), valeur(), Champ_front_base::valeurs(), Champ_Inc::valeurs(), and Cond_lim_base::zone_Cl_dis().
cree_instance()
Objet_U * Echange_contact_Correlation_VEF::cree_instance () static
Definition at line 30 of file Echange_contact_Correlation_VEF.cpp.
duplique()
int Echange_contact_Correlation_VEF::duplique () const override virtual
Reimplemented from Temperature_imposee_paroi.
Definition at line 30 of file Echange_contact_Correlation_VEF.cpp.
get_info()
const Type_info * Echange_contact_Correlation_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Temperature_imposee_paroi.
Definition at line 30 of file Echange_contact_Correlation_VEF.cpp.
getCp()
double Echange_contact_Correlation_VEF::getCp () const inline
Definition at line 79 of file Echange_contact_Correlation_VEF.h.
  {
    return Cp;
  }
References Cp.
Referenced by calculer_coefficient_echange().
getDh()
double Echange_contact_Correlation_VEF::getDh (int i) const inline
Definition at line 83 of file Echange_contact_Correlation_VEF.h.
  {
    return diam(i);
  }
References diam.
Referenced by calculer_coefficient_echange(), and init().
getLambda()
double Echange_contact_Correlation_VEF::getLambda (int i) const inline
Definition at line 71 of file Echange_contact_Correlation_VEF.h.
  {
    return lambda(i);
  }
References lambda.
Referenced by calculer_coefficient_echange().
getMu()
double Echange_contact_Correlation_VEF::getMu (int i) const inline
Definition at line 67 of file Echange_contact_Correlation_VEF.h.
  {
    return mu(i);
  }
References mu.
Referenced by calculer_coefficient_echange().
getQh()
double Echange_contact_Correlation_VEF::getQh () const inline
< le debit
Definition at line 87 of file Echange_contact_Correlation_VEF.h.
  {
    return debit;  //!< le debit
  }
References debit.
Referenced by calculer_coefficient_echange().
getRho()
double Echange_contact_Correlation_VEF::getRho (int i) const inline
Definition at line 75 of file Echange_contact_Correlation_VEF.h.
  {
    return rho(i);
  }
References rho.
getT()
double Echange_contact_Correlation_VEF::getT (int i) const inline
Definition at line 63 of file Echange_contact_Correlation_VEF.h.
  {
    return T(i);
  }
References T.
getU()
double Echange_contact_Correlation_VEF::getU (int i) const inline
Definition at line 59 of file Echange_contact_Correlation_VEF.h.
  {
    return U(i);
  }
References U.
imprimer()
void Echange_contact_Correlation_VEF::imprimer (double temps) const virtual
Imprime les resultats
Definition at line 949 of file Echange_contact_Correlation_VEF.cpp.
{
  const int ME = Process::me();
  const int nbproc = Process::nproc();
  if (nbproc>1)
    {
      envoyer(coord,ME,0,ME);
      envoyer(T,ME,0,ME);
      envoyer(U,ME,0,ME);
      envoyer(h_correlation,ME,0,ME);
      envoyer(rho,ME,0,ME);
      envoyer(mu,ME,0,ME);
      envoyer(lambda,ME,0,ME);
      envoyer(Qvol,ME,0,ME);
      envoyer(vol,ME,0,ME);
      envoyer(flux_radiatif,ME,0,ME);
      if (je_suis_maitre())
        {
          Nom nom_bord=frontiere_dis().frontiere().le_nom();
          nom_bord+="_";
          nom_bord+=Nom(temps);
          nom_bord+=".dat";
          SFichier fic(nom_bord);
          fic.precision(zone_Cl_dis().equation().schema_temps().precision_impr());
          fic.setf(ios::scientific);
          double Qt=0.;
          fic << "# X                T                U                h                rho                mu                lambda                Q[W]";
          if (avec_rayo) fic << "                Flux_radiatif(W/m2)";
          fic << finl;
          for (int p=0; p<nbproc; p++)
            {
              DoubleVect coord_tmp;
              DoubleVect T_tmp;
              DoubleVect U_tmp;
              DoubleVect h_tmp;
              DoubleVect rho_tmp;
              DoubleVect mu_tmp;
              DoubleVect lambda_tmp;
              DoubleVect Qvol_tmp;
              DoubleVect vol_tmp;
              DoubleVect flux_radiatif_tmp;
              recevoir(coord_tmp,p,0,p);
              recevoir(T_tmp,p,0,p);
              recevoir(U_tmp,p,0,p);
              recevoir(h_tmp,p,0,p);
              recevoir(rho_tmp,p,0,p);
              recevoir(mu_tmp,p,0,p);
              recevoir(lambda_tmp,p,0,p);
              recevoir(Qvol_tmp,p,0,p);
              recevoir(vol_tmp,p,0,p);
              recevoir(flux_radiatif_tmp,p,0,p);
              for (int i=0; i<coord_tmp.size(); i++)
                {
                  fic << coord_tmp(i) << " \t" << T_tmp(i) << " \t" << U_tmp(i) << " \t" << h_tmp(i) << " \t" ;
                  fic  << rho_tmp(i) << " \t" << mu_tmp(i) << " \t" << lambda_tmp(i) << " \t" << Qvol_tmp(i)*vol_tmp(i);
                  if (avec_rayo && i>0 && i<coord_tmp.size()-1) fic << " \t" << flux_radiatif_tmp(i-1);
                  fic << finl;
                  Qt+=Qvol_tmp(i)*vol_tmp(i);
                }
            }
          fic << "# Q total[W] = " << Qt << finl;
          fic << finl;
        }
    }
  else
    {
      Nom nom_bord=frontiere_dis().frontiere().le_nom();
      nom_bord+="_";
      nom_bord+=Nom(temps);
      nom_bord+=".dat";
      SFichier fic(nom_bord);
      fic.precision(zone_Cl_dis().equation().schema_temps().precision_impr());
      fic.setf(ios::scientific);
      double Qt=0.;
      fic << "# X                 T                 U                 h                 rho                 mu                 lambda                  Q[W]";
      if (avec_rayo) fic << "                Flux_radiatif(W/m2)";
      fic << finl;
      for (int i =0; i<N; i++)
        {
          fic << coord(i) << " \t" << T(i) << " \t" << U(i) << " \t" << h_correlation(i) << " \t" << rho(i) << " \t" ;
          fic <<    mu(i) << " \t" << lambda(i) << " \t" << Qvol(i)*vol(i);
          if (avec_rayo && i>0 && i<N-1) fic << " \t" << flux_radiatif(i-1);
          fic << finl;
          Qt+=Qvol(i)*vol(i);
        }
      fic << "# Q total[W] = " << Qt << finl;
      fic << finl;
    }
}
References avec_rayo, coord, envoyer(), finl, flux_radiatif, Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), h_correlation, Process::je_suis_maitre(), lambda, Frontiere::le_nom(), Process::me(), mu, N, Process::nproc(), Sortie_Fichier_base::precision(), Qvol, recevoir(), rho, Sortie_Fichier_base::setf(), TRUSTVect< _TYPE_ >::size(), T, U, vol, and Cond_lim_base::zone_Cl_dis().
Referenced by mettre_a_jour().
info()
const Type_info * Echange_contact_Correlation_VEF::info () static
Definition at line 30 of file Echange_contact_Correlation_VEF.cpp.
init()
void Echange_contact_Correlation_VEF::init () protected
!! a revoir
< en dur, deux patches associes a un point fluide
< fournit pour chaque face du bord, le numero du patch auquel elle appartient
< pour l'instant dz est constant, le maillage fluide est regulier (hormis pour le premier et dernier point)
< ne sert pas mais evite une division par zero dans le calcul de Qvol.
Definition at line 480 of file Echange_contact_Correlation_VEF.cpp.
{
  const Zone_VEF& ma_zvef = ref_cast(Zone_VEF,zone_Cl_dis().zone_dis().valeur());
  const Front_VF& ma_front_vf = ref_cast(Front_VF,frontiere_dis());
  const DoubleTab& xv = ma_zvef.xv();
  const IntTab& face_sommets = ma_zvef.face_sommets();
  const DoubleTab& coord_som = ma_zvef.domaine_dis().domaine().coord_sommets();
  const int ndeb = ma_front_vf.num_premiere_face();
  const int nb_faces_bord = ma_front_vf.nb_faces();
// N entre par l'utilisateur = Nombre de mailles 1D
  N=N/Process::nproc()+2;
// N modifie pour que cela soit le nombre de noeuds 1D par processeur
// Ici, on suppose que l'utilisateur a decoupe en tranche selon la direction 1D
  double delta=(xsup-xinf)/Process::nproc();
  xinf=xinf+Process::me()*delta;
  xsup=xinf+delta;
// on dimensionne
  coord.resize(N);
  U.resize(N);
  T.resize(N);
  Qvol.resize(N);
  rho.resize(N);
  mu.resize(N);
  lambda.resize(N);
  vol.resize(N);
  diam.resize(N);
  h_correlation.resize(N);
// on remplit les coordonnees des noeuds du maillages 1D dans le fluide
  coord(0)=xinf;
  coord(N-1)=xsup;
  double dx = (xsup-xinf)/(N-2);
  for(int i=1; i<N-1; i++)
    {
      coord(i) = xinf+dx*(i-0.5);
    }
// on remplit les correspondances elements solides -> elements fluides
  correspondance_solide_fluide.resize(nb_faces_bord);
  for(int i=0; i<nb_faces_bord; i++)
    {
      double min=std::fabs(xv(i+ndeb,dir)-coord(1));
      double tmp=0.;
      int jmin=1;
      for (int j=2; j<N-1; j++)
        {
          if ((tmp=std::fabs(xv(i+ndeb,dir)-coord(j))) < min)
            {
              min = tmp;
              jmin = j;
            }
        }
// Cerr << "min=" << min << " jmin=" << jmin << finl;
      correspondance_solide_fluide(i) = jmin;
    }
// Cerr << Process::me() << finl;
// Cerr << correspondance_solide_fluide << finl;
  if (avec_rayo == 1)
    {
      const double precision = 1.e-6;
      const int MAX_FACES_PATCH = 500; //!!! a revoir
      int nb_patches = 2*(N-2);
      patches_rayo.resize(nb_patches,MAX_FACES_PATCH);
      nb_faces_patch.resize(nb_patches);
      IntVect traite(nb_faces_bord);
      correspondance_fluide_patch.resize(N,2); //!< en dur, deux patches associes a un point fluide
      correspondance_face_patch.resize(nb_faces_bord); //!< fournit pour chaque face du bord, le numero du patch auquel elle appartient
      traite=0;
      correspondance_fluide_patch=-1;
      int compteur_patches = 0;
      for(int i=0; i<nb_faces_bord; i++)
        {
          int face_corresp = correspondance_solide_fluide(i);
          if (traite(i) == 0)
            {
              int compteur_face=1;
              traite(i)=1;
              if (compteur_patches==nb_patches)
                {
                  Cerr << "Erreur dans Echange_contact_Correlation_VEF::initialiser" << finl;
                  Cerr << "Le nombre de patches est depasse." << finl;
                  Cerr << "Contacter le support TRUST." << finl;
                  exit();
                }
              patches_rayo(compteur_patches,0) = i;
              correspondance_face_patch(i)=compteur_patches;
              if (correspondance_fluide_patch(face_corresp,0) == -1)
                correspondance_fluide_patch(face_corresp,0) = compteur_patches;
              else
                correspondance_fluide_patch(face_corresp,1) = compteur_patches;
              int s0 = face_sommets(ndeb+i,0);
              int s1 = face_sommets(ndeb+i,1);
              int s2 = face_sommets(ndeb+i,2);
              ArrOfDouble v01(dimension);
              ArrOfDouble v02(dimension);
              for (int idim=0; idim<dimension; idim++)
                {
                  v01[idim] = coord_som(s1,idim)-coord_som(s0,idim);
                  v02[idim] = coord_som(s2,idim)-coord_som(s0,idim);
                }
              ArrOfDouble normale(dimension);
              normale[0] = v01[1]*v02[2]-v01[2]*v02[1];
              normale[1] = -v01[0]*v02[2]+v01[2]*v02[0];
              normale[2] = v01[0]*v02[1]-v01[1]*v02[0];
              for(int j=0; j<nb_faces_bord; j++)
                {
                  if ((traite(j) == 0) && (correspondance_solide_fluide(j) == face_corresp))
                    {
                      int sj_0 = face_sommets(ndeb+j,0);
                      double pscal = 0.;
                      for (int idim=0; idim<dimension; idim++)
{
                          pscal += normale[idim]*(coord_som(sj_0,idim)-coord_som(s0,idim));
                        }
                      if (std::fabs(pscal) < precision)
{
                          traite(j) = 1;
                          if (compteur_face==MAX_FACES_PATCH)
{
                              Cerr << "Erreur dans Echange_contact_Correlation_VEF::initialiser" << finl;
                              Cerr << "Le nombre maximal de faces de patches est depasse." << finl;
                              Cerr << "Contacter le support TRUST." << finl;
                              exit();
                            }
                          patches_rayo(compteur_patches,compteur_face++) = j;
                          correspondance_face_patch(j)=compteur_patches;
                        }
                    }
                }
              nb_faces_patch(compteur_patches) = compteur_face;
              compteur_patches++;
            }
        }
    }
// calcul du diametre hydraulique
  for (int i=0; i<N; i++)
    {
      fct_Dh.setVar("x",coord(i));
      diam(i)=fct_Dh.eval();
    }
// calcul des volumes des tranches
  vol=0.;
  const double dz = (coord(2)-coord(1)); //!< pour l'instant dz est constant, le maillage fluide est regulier (hormis pour le premier et dernier point)
  for (int i=1; i<N-1; i++)
    {
      fct_vol.setVar("Dh",getDh(i));
      fct_vol.setVar("x",coord(i));
      vol(i)=fct_vol.eval()*dz;
    }
  vol(0) = vol(N-1) = 1.; //!< ne sert pas mais evite une division par zero dans le calcul de Qvol.
}
References avec_rayo, Cerr, coord, Domaine::coord_sommets(), correspondance_face_patch, correspondance_fluide_patch, correspondance_solide_fluide, diam, Objet_U::dimension, dir, Domaine_dis::domaine(), Zone_dis_base::domaine_dis(), Parser_U::eval(), Process::exit(), Zone_VF::face_sommets(), fct_Dh, fct_vol, finl, Cond_lim_base::frontiere_dis(), getDh(), h_correlation, lambda, Process::me(), mu, N, Front_VF::nb_faces(), nb_faces_patch, Process::nproc(), Front_VF::num_premiere_face(), patches_rayo, Qvol, ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), rho, Parser_U::setVar(), T, U, valeur(), vol, xinf, xsup, Zone_VF::xv(), and Cond_lim_base::zone_Cl_dis().
Referenced by completer().
init_tab_echange()
void Echange_contact_Correlation_VEF::init_tab_echange () protected
Initialise le tab tab_ech pour le parallele
Definition at line 369 of file Echange_contact_Correlation_VEF.cpp.
{
}
Referenced by completer().
limpr()
int Echange_contact_Correlation_VEF::limpr (double temps_courant, double dt) const virtual
Teste si l'impression est demandee
Definition at line 928 of file Echange_contact_Correlation_VEF.cpp.
{
  const Schema_Temps_base& sch = zone_Cl_dis().equation().schema_temps();
// Test un peu tordu, mais ca fonctionne !!!! (CM 05/07/2007)
  if (dt_impr<=dt || ((sch.temps_max()<=temps_courant || sch.nb_pas_dt_max()<=(sch.nb_pas_dt()+1) || (temps_courant!=sch.temps_courant() && sch.nb_pas_dt()==0)) && dt_impr!=1e10))
    return 1;
  else
    {
// Voir Schema_Temps_base::limpr pour information sur epsilon et modf
      static const double epsilon = 1.e-9;
      double i, j;
      modf(temps_courant/dt_impr + epsilon, &i);
      modf((temps_courant-dt)/dt_impr + epsilon, &j);
      return ( i>j );
    }
}
References dt_impr, MorEqn::equation(), Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::nb_pas_dt_max(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_max(), and Cond_lim_base::zone_Cl_dis().
Referenced by mettre_a_jour().
mettre_a_jour()
void Echange_contact_Correlation_VEF::mettre_a_jour (double temps) override virtual
Mise a jour de la vitesse, temperature fluide et coeff d'echange
Reimplemented from Cond_lim_base.
Definition at line 785 of file Echange_contact_Correlation_VEF.cpp.
{
// Nom des fichiers de sauvegarde
  Nom Fichier_sauv_nom = zone_Cl_dis().equation().probleme().le_nom();
  Fichier_sauv_nom+="_";
  Fichier_sauv_nom+=frontiere_dis().frontiere().le_nom();
  Fichier_sauv_nom+=".sauv";
// Operation de reprise du champ de temperature dans le fluide
  if (Reprise_temperature==1)
    {
      Echange_contact_Correlation_VEF_reprendre(Fichier_sauv_nom, temps, T);
      Reprise_temperature=0;
    }
  calculer_CL();
  calculer_prop_physique();
  calculer_Q();
  calculer_Vitesse();
  calculer_Tfluide();
  for (int i=0; i<N; i++)
    h_correlation(i) = calculer_coefficient_echange(i);
  calculer_h_solide(h_solide);
  const int taille = h_solide.dimension(0);
  DoubleTab& Tparoi = champ_front().valeur().valeurs();
  const Equation_base& mon_eqn = zone_Cl_dis().equation();
  const DoubleTab& Ts = mon_eqn.inconnue().valeurs();
  Zone_VEF& zvef = ref_cast(Zone_VEF,zone_Cl_dis().zone_dis().valeur());
  const Front_VF& ma_front_vf = ref_cast(Front_VF,frontiere_dis());
  const IntTab& face_voisins = zvef.face_voisins();
  const int ndeb = ma_front_vf.num_premiere_face();
  const double sigma = 5.67e-8;
  const DoubleVect& face_surfaces = zvef.face_surfaces();
  int nb_patches=2*(N-2);
  flux_radiatif.resize(nb_patches);
  flux_radiatif=0;
  IntVect patch_calcule(nb_patches);
  patch_calcule=0;
  for (int ii=0; ii<taille; ii++)
    {
      double Tint=0.;
      int face = ndeb+ii;
      int elem =  face_voisins(face,0);
      if(elem == -1)
        elem =  face_voisins(face,1);
// on recupere les faces 2, 3 et 4 de l'element contenant "face"
      int face2 = zvef.elem_faces(elem,0);
      int face3 = zvef.elem_faces(elem,1);
      if (face2 == face)
        face2 = zvef.elem_faces(elem,dimension);
      else if (face3 == face)
        face3 = zvef.elem_faces(elem,dimension);
      Tint += pdt_scal(zvef,face,face2,elem,dimension,1.)*Ts(face2) + pdt_scal(zvef,face,face3,elem,dimension,1.)*Ts(face3);
      if(dimension == 3)
        {
          int face4 = zvef.elem_faces(elem,2);
          if (face4 == face)
            face4 = zvef.elem_faces(elem,dimension);
          Tint += pdt_scal(zvef,face,face4,elem,dimension,1.)*Ts(face4);
        }
      Tint *= -1./pdt_scal(zvef,face,face,elem,dimension,1.);
      int patch_courant = 0;
      if (avec_rayo == 1)
        {
          patch_courant = correspondance_face_patch(ii);
          if (!patch_calcule(patch_courant))
            {
              int patch_en_face = correspondance_fluide_patch(correspondance_solide_fluide(ii),0);
              if (patch_en_face == patch_courant)
                patch_en_face = correspondance_fluide_patch(correspondance_solide_fluide(ii),1);
              double Tp14 = 0.;
              double surf1_tot = 0.;
              for (int face_patch=0; face_patch<nb_faces_patch(patch_courant); face_patch++)
                {
                  int f = ndeb+patches_rayo(patch_courant,face_patch);
                  double surf = face_surfaces(f);
                  Tp14 += surf*pow(Ts(f),4);
                  surf1_tot += surf;
                }
              Tp14 /= surf1_tot;
              double Tp24 = 0.;
              double surf2_tot = 0.;
              for (int face_patch=0; face_patch<nb_faces_patch(patch_en_face); face_patch++)
                {
                  int f = ndeb+patches_rayo(patch_en_face,face_patch);
                  double surf = face_surfaces(f);
                  Tp24 += surf*pow(Ts(f),4);
                  surf2_tot += surf;
                }
              Tp24 /= surf2_tot;
              flux_radiatif(patch_courant) = sigma*emissivite/(2-emissivite)*(Tp24-Tp14);
              patch_calcule(patch_courant) = 1;
              if (limpr(temps,mon_eqn.schema_temps().pas_de_temps()))
                {
// Cout << ii << " " << patch_courant << finl;
                  if (Process::nproc()>1) Cout << "Processeur " << Process::me() << " ";
                  Cout << ma_front_vf.le_nom() << " patch " << patch_courant;
                  Cout << " : flux radiatif=sigma*eps/(2-eps)*(TP2^4-TP1^4)= " << flux_radiatif(patch_courant) << " W/m2";
                  Cout << " TP2= " << pow(Tp24,0.25) << " K";
                  Cout << " TP1= " << pow(Tp14,0.25) << " K" << finl;
                }
            }
        }
      Tparoi(ii,0) = (h_solide(ii,0)*Tint+flux_radiatif(patch_courant)+ h_correlation(correspondance_solide_fluide(ii))*T(correspondance_solide_fluide(ii)))/(h_solide(ii,0)+h_correlation(correspondance_solide_fluide(ii)));
    }
// Mise a jour des CLs pour avoir une impression correcte des resultats
  calculer_CL();
  if (limpr(temps,mon_eqn.schema_temps().pas_de_temps())) imprimer(temps);
  Temperature_imposee_paroi::mettre_a_jour(temps);
  Echange_contact_Correlation_VEF_sauvegarder(Fichier_sauv_nom, temps, T);
}
References avec_rayo, calculer_CL(), calculer_coefficient_echange(), calculer_h_solide(), calculer_prop_physique(), calculer_Q(), calculer_Tfluide(), calculer_Vitesse(), Cond_lim_base::champ_front(), correspondance_face_patch, correspondance_fluide_patch, correspondance_solide_fluide, Cout, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Echange_contact_Correlation_VEF_reprendre(), Echange_contact_Correlation_VEF_sauvegarder(), Zone_VF::elem_faces(), emissivite, MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), finl, flux_radiatif, Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), h_correlation, h_solide, imprimer(), Equation_base::inconnue(), Frontiere_dis_base::le_nom(), Probleme_base::le_nom(), Frontiere::le_nom(), limpr(), Process::me(), Cond_lim_base::mettre_a_jour(), N, nb_faces_patch, Process::nproc(), Front_VF::num_premiere_face(), Schema_Temps_base::pas_de_temps(), patches_rayo, pdt_scal(), Equation_base::probleme(), ref_cast, Reprise_temperature, TRUSTVect< _TYPE_ >::resize(), Equation_base::schema_temps(), T, Deriv_Champ_front_base::valeur(), valeur(), Champ_front_base::valeurs(), Champ_Inc::valeurs(), and Cond_lim_base::zone_Cl_dis().
Referenced by completer().
pdt_scal()
double Echange_contact_Correlation_VEF::pdt_scal (const Zone_VEF & la_zone, int num_face, int num2, int num_elem, int dim, double diffu) protected
Definition at line 1068 of file Echange_contact_Correlation_VEF.cpp.
{
  double pscal;
  const IntTab& face_voisinsF = la_zone.face_voisins();
  pscal = la_zone.face_normales(num_face,0)*la_zone.face_normales(num2,0)
          + la_zone.face_normales(num_face,1)*la_zone.face_normales(num2,1);
  if (dim == 3)
    pscal += la_zone.face_normales(num_face,2)*la_zone.face_normales(num2,2);
  if ( (face_voisinsF(num_face,0) == face_voisinsF(num2,0)) ||
       (face_voisinsF(num_face,1) == face_voisinsF(num2,1))) pscal = -pscal;
  return (pscal*diffu)/la_zone.volumes(num_elem);
}
References Zone_VEF::face_normales(), Zone_VF::face_voisins(), and Zone_VF::volumes().
Referenced by completer(), and mettre_a_jour().
pdt_scalSqrt()
double Echange_contact_Correlation_VEF::pdt_scalSqrt (const Zone_VEF & la_zone, int num_face, int num2, int num_elem, int dim, double diffu) protected
Definition at line 1051 of file Echange_contact_Correlation_VEF.cpp.
{
  double pscal;
  pscal = la_zone.face_normales(num_face,0)*la_zone.face_normales(num2,0)
          + la_zone.face_normales(num_face,1)*la_zone.face_normales(num2,1);
  if (dim == 3)
    pscal += la_zone.face_normales(num_face,2)*la_zone.face_normales(num2,2);
  pscal = sqrt(std::fabs(pscal));
  return (pscal*diffu)/la_zone.volumes(num_elem);
}
References Zone_VEF::face_normales(), and Zone_VF::volumes().
Referenced by calculer_h_solide().
printOn()
Sortie & Echange_contact_Correlation_VEF::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Temperature_imposee_paroi.
Definition at line 35 of file Echange_contact_Correlation_VEF.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Echange_contact_Correlation_VEF::readOn (Entree & s) override protected virtual
Simple appel a: Dirichlet::readOn(Entree&)
Returns
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Temperature_imposee_paroi.
Definition at line 40 of file Echange_contact_Correlation_VEF.cpp.
{
// Motcles les_mots(16);
// Rajout Cyril MALOD (14/09/2006)
  Reprise_temperature=0;
  Motcles les_mots(17);
  {
    les_mots[0] = "dir";
    les_mots[1] = "Tinf";
    les_mots[2] = "Tsup";
    les_mots[3] = "lambda";
    les_mots[4] = "rho";
    les_mots[5] = "Cp";
    les_mots[6] = "dt_impr";
    les_mots[7] = "mu";
    les_mots[8] = "debit";
    les_mots[9] = "Dh";
    les_mots[10] = "N";
    les_mots[11] = "surface";
    les_mots[12] = "Nu";
    les_mots[13] = "xinf";
    les_mots[14] = "xsup";
// Le mot cle suivant n'est pas encore commente car les hypotheses sur ce rayonnement sont restrictives
    les_mots[15] = "emissivite_pour_rayonnement_entre_deux_plaques_quasi_infinies";
// Rajout Cyril MALOD (14/09/2006)
    les_mots[16] = "Reprise_correlation";
  }
  dt_impr = 1e10;
  avec_rayo=0;
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
  is >> motlu;
  if(motlu!=accolade_ouverte)
    {
      Cerr << "On attendait une { a la lecture d'une " << que_suis_je() << finl;
      Cerr << "et non : " << motlu << finl;
      exit();
    }
  is >> motlu;
  while (motlu != accolade_fermee)
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          {
            is >> dir;
            if (dir<0 ||dir>2)
              {
                Cerr << "La direction doit etre 0, 1 ou 2 dans  " << que_suis_je() << finl;
                exit();
              }
            break;
          }
        case 1 :
          {
            is >> Tinf;
            break;
          }
        case 2 :
          {
            is >> Tsup;
            break;
          }
        case 3 :
          {
            Nom tmp;
            is >> tmp;
            lambda_T.setNbVar(1);
            lambda_T.setString(tmp);
            lambda_T.addVar("T");
            lambda_T.parseString();
            break;
          }
        case 4 :
          {
            Nom tmp;
            is >> tmp;
            rho_T.setNbVar(1);
            rho_T.setString(tmp);
            rho_T.addVar("T");
            rho_T.parseString();
            break;
          }
        case 5 :
          {
            is >> Cp;
            break;
          }
        case 6 :
          {
            is >> dt_impr;
            break;
          }
        case 7 :
          {
            Nom tmp;
            is >> tmp;
            mu_T.setNbVar(1);
            mu_T.setString(tmp);
            mu_T.addVar("T");
            mu_T.parseString();
            break;
          }
        case 8 :
          {
            is >> debit;
            break;
          }
        case 9 :
          {
            Nom tmp;
            is >> tmp;
            fct_Dh.setNbVar(1);
            fct_Dh.setString(tmp);
            fct_Dh.addVar("x");
            fct_Dh.parseString();
            break;
          }
        case 10 :
          {
            is >> N;
            break;
          }
        case 11 :
          {
            Nom tmp;
            is >> tmp;
            fct_vol.setNbVar(2);
            fct_vol.setString(tmp);
            fct_vol.addVar("Dh");
            fct_vol.addVar("x");
            fct_vol.parseString();
            break;
          }
        case 12 :
          {
            Nom tmp;
            is >> tmp;
            fct_Nu.setNbVar(2);
            fct_Nu.setString(tmp);
            fct_Nu.addVar("Re");
            fct_Nu.addVar("Pr");
            fct_Nu.parseString();
            break;
          }
        case 13 :
          {
            is >> xinf;
            break;
          }
        case 14 :
          {
            is >> xsup;
            break;
          }
        case 15 :
          {
            avec_rayo = 1;
            is >> emissivite;
            break;
          }
// Rajout Cyril MALOD (14/09/2006)
        case 16 :
          {
            Reprise_temperature=1;
            break;
          }
        default :
          {
            Cerr << "On ne comprend le mot : " << motlu << "dans " << que_suis_je() << finl;
            exit();
          }
        }
      is >> motlu;
    }
  champ_front().typer("Champ_front_fonc");
  champ_front()->fixer_nb_comp(1);
  return is ;
}
References Parser_U::addVar(), avec_rayo, Cerr, Cond_lim_base::champ_front(), Cp, debit, dir, dt_impr, emissivite, Process::exit(), fct_Dh, fct_Nu, fct_vol, finl, lambda_T, mu_T, N, Parser_U::parseString(), Objet_U::que_suis_je(), Reprise_temperature, rho_T, Motcles::search(), Parser_U::setNbVar(), Parser_U::setString(), Tinf, Tsup, Deriv_::typer(), xinf, and xsup.
self_cast() [1/2]
const Echange_contact_Correlation_VEF & Echange_contact_Correlation_VEF::self_cast (const Objet_U & r) static
Definition at line 30 of file Echange_contact_Correlation_VEF.cpp.
self_cast() [2/2]
Echange_contact_Correlation_VEF & Echange_contact_Correlation_VEF::self_cast (Objet_U & r) static
Definition at line 30 of file Echange_contact_Correlation_VEF.cpp.
surfacesVEF()
double Echange_contact_Correlation_VEF::surfacesVEF (const Zone_VEF & la_zone, int num_face, int dim) protected
Definition at line 1084 of file Echange_contact_Correlation_VEF.cpp.
{
  double pscal;
  pscal = la_zone.face_normales(num_face,0)*la_zone.face_normales(num_face,0)
          + la_zone.face_normales(num_face,1)*la_zone.face_normales(num_face,1);
  if (dim == 3)
    pscal += la_zone.face_normales(num_face,2)*la_zone.face_normales(num_face,2);
  pscal = sqrt(pscal);
  return pscal;
}
References Zone_VEF::face_normales().
Referenced by calculer_Q().
taille_memoire()
unsigned Echange_contact_Correlation_VEF::taille_memoire () const override virtual
Reimplemented from Temperature_imposee_paroi.
Definition at line 30 of file Echange_contact_Correlation_VEF.cpp.
Member Data Documentation
autre_h
DoubleTab Echange_contact_Correlation_VEF::autre_h protected
Definition at line 108 of file Echange_contact_Correlation_VEF.h.
avec_rayo
int Echange_contact_Correlation_VEF::avec_rayo private
Definition at line 137 of file Echange_contact_Correlation_VEF.h.
Referenced by imprimer(), init(), mettre_a_jour(), and readOn().
coord
DoubleVect Echange_contact_Correlation_VEF::coord protected
coordonnees des points de discretisation 1D
Definition at line 126 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_CL(), calculer_Tfluide(), imprimer(), and init().
correspondance_face_patch
IntVect Echange_contact_Correlation_VEF::correspondance_face_patch private
Definition at line 141 of file Echange_contact_Correlation_VEF.h.
Referenced by init(), and mettre_a_jour().
correspondance_fluide_patch
IntTab Echange_contact_Correlation_VEF::correspondance_fluide_patch private
Definition at line 142 of file Echange_contact_Correlation_VEF.h.
Referenced by init(), and mettre_a_jour().
correspondance_solide_fluide
IntVect Echange_contact_Correlation_VEF::correspondance_solide_fluide protected
Definition at line 107 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_Q(), completer(), init(), and mettre_a_jour().
Cp
double Echange_contact_Correlation_VEF::Cp protected
Definition at line 121 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_Tfluide(), getCp(), and readOn().
debit
double Echange_contact_Correlation_VEF::debit protected
Definition at line 122 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_Tfluide(), calculer_Vitesse(), completer(), getQh(), and readOn().
diam
DoubleVect Echange_contact_Correlation_VEF::diam protected
tableau des proprietes physiques du fluide a un instant donne
Definition at line 131 of file Echange_contact_Correlation_VEF.h.
Referenced by getDh(), and init().
dir
int Echange_contact_Correlation_VEF::dir protected
Direction du cylindre.
Definition at line 113 of file Echange_contact_Correlation_VEF.h.
Referenced by init(), and readOn().
dt_impr
double Echange_contact_Correlation_VEF::dt_impr protected
Definition at line 120 of file Echange_contact_Correlation_VEF.h.
Referenced by limpr(), and readOn().
emissivite
double Echange_contact_Correlation_VEF::emissivite private
Definition at line 138 of file Echange_contact_Correlation_VEF.h.
Referenced by mettre_a_jour(), and readOn().
fct_Dh
Parser_U Echange_contact_Correlation_VEF::fct_Dh protected
Definition at line 119 of file Echange_contact_Correlation_VEF.h.
Referenced by init(), and readOn().
fct_Nu
Parser_U Echange_contact_Correlation_VEF::fct_Nu protected
Definition at line 117 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_coefficient_echange(), and readOn().
fct_vol
Parser_U Echange_contact_Correlation_VEF::fct_vol protected
Definition at line 118 of file Echange_contact_Correlation_VEF.h.
Referenced by init(), and readOn().
flux_radiatif
DoubleVect Echange_contact_Correlation_VEF::flux_radiatif protected
le flux radiatif entre patch
Definition at line 134 of file Echange_contact_Correlation_VEF.h.
Referenced by imprimer(), and mettre_a_jour().
h_correlation
DoubleVect Echange_contact_Correlation_VEF::h_correlation protected
le coeff d'echange par correlation
Definition at line 132 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_Q(), completer(), imprimer(), init(), and mettre_a_jour().
h_solide
DoubleTab Echange_contact_Correlation_VEF::h_solide protected
le coeff d'echange par correlation
Definition at line 133 of file Echange_contact_Correlation_VEF.h.
Referenced by completer(), and mettre_a_jour().
info_obj
const Type_info Echange_contact_Correlation_VEF::info_obj static
Definition at line 39 of file Echange_contact_Correlation_VEF.h.
lambda
DoubleVect Echange_contact_Correlation_VEF::lambda protected
Definition at line 131 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_prop_physique(), calculer_Tfluide(), getLambda(), imprimer(), and init().
lambda_T
Parser_U Echange_contact_Correlation_VEF::lambda_T protected
Definition at line 114 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_prop_physique(), and readOn().
mu
DoubleVect Echange_contact_Correlation_VEF::mu protected
Definition at line 131 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_prop_physique(), getMu(), imprimer(), and init().
mu_T
Parser_U Echange_contact_Correlation_VEF::mu_T protected
Definition at line 115 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_prop_physique(), and readOn().
N
int Echange_contact_Correlation_VEF::N protected
nb de points du maillage 1D pour la vitesse et la temperature
Definition at line 128 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_CL(), calculer_prop_physique(), calculer_Q(), calculer_Tfluide(), calculer_Vitesse(), completer(), imprimer(), init(), mettre_a_jour(), and readOn().
nb_faces_patch
IntVect Echange_contact_Correlation_VEF::nb_faces_patch private
Definition at line 140 of file Echange_contact_Correlation_VEF.h.
Referenced by init(), and mettre_a_jour().
patches_rayo
IntTab Echange_contact_Correlation_VEF::patches_rayo private
Definition at line 139 of file Echange_contact_Correlation_VEF.h.
Referenced by init(), and mettre_a_jour().
Qvol
DoubleVect Echange_contact_Correlation_VEF::Qvol protected
puissance volumique dans le fluide 1D
Definition at line 130 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_Q(), calculer_Tfluide(), imprimer(), and init().
Reprise_temperature
int Echange_contact_Correlation_VEF::Reprise_temperature protected
Definition at line 109 of file Echange_contact_Correlation_VEF.h.
Referenced by mettre_a_jour(), and readOn().
rho
DoubleVect Echange_contact_Correlation_VEF::rho protected
Definition at line 131 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_prop_physique(), calculer_Tfluide(), calculer_Vitesse(), completer(), getRho(), imprimer(), and init().
rho_T
Parser_U Echange_contact_Correlation_VEF::rho_T protected
Definition at line 116 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_prop_physique(), and readOn().
T
DoubleVect Echange_contact_Correlation_VEF::T protected
inconnues fluides vitesse et temperature
Definition at line 129 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_CL(), calculer_prop_physique(), calculer_Q(), calculer_Tfluide(), completer(), getT(), imprimer(), init(), and mettre_a_jour().
T_CL0
double Echange_contact_Correlation_VEF::T_CL0 protected
Definition at line 111 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_CL(), and calculer_Tfluide().
T_CL1
double Echange_contact_Correlation_VEF::T_CL1 protected
CL sur le domaine. En seq. = Tinf et Tsup ; En parallele = Tvoisin.
Definition at line 111 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_CL(), and calculer_Tfluide().
Tinf
double Echange_contact_Correlation_VEF::Tinf protected
Definition at line 112 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_CL(), completer(), and readOn().
Tsup
double Echange_contact_Correlation_VEF::Tsup protected
Temperature entree, sortie.
Definition at line 112 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_CL(), completer(), and readOn().
U
DoubleVect Echange_contact_Correlation_VEF::U protected
Definition at line 129 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_Vitesse(), completer(), getU(), imprimer(), and init().
vol
DoubleVect Echange_contact_Correlation_VEF::vol protected
volumes des tranches Sdz du volume suivant la direction de l'ecoulement
Definition at line 125 of file Echange_contact_Correlation_VEF.h.
Referenced by calculer_Q(), imprimer(), and init().
xinf
double Echange_contact_Correlation_VEF::xinf protected
Definition at line 123 of file Echange_contact_Correlation_VEF.h.
Referenced by init(), and readOn().
xsup
double Echange_contact_Correlation_VEF::xsup protected
Definition at line 123 of file Echange_contact_Correlation_VEF.h.
Referenced by init(), and readOn().
The documentation for this class was generated from the following files:
src/VEF/Cond_Lim/Echange_contact_Correlation_VEF.h
src/VEF/Cond_Lim/Echange_contact_Correlation_VEF.cpp