TRUST: Eval_Forchheimer_VDF_Face Class Reference
Eval_Forchheimer_VDF_Face Class Reference
#include <Eval_Forchheimer_VDF_Face.h>
Public Member Functions
Eval_Forchheimer_VDF_Face ()
Eval_Forchheimer_VDF_Face (const Eval_Forchheimer_VDF_Face &eval)
template<typename Type_Double >
void calculer_terme_source (const int, Type_Double &) const
template<typename Type_Double >
void calculer_terme_source_bord (const int num_face, Type_Double &source) const
void mettre_a_jour () override
void setCf (double c)
void associer (const Champ_Inc &vit)
void setPorosite (double p)
Public Member Functions inherited from Evaluateur_Source_VDF_Face
Evaluateur_Source_VDF_Face ()
Evaluateur_Source_VDF_Face (const Evaluateur_Source_VDF_Face &)
void completer () override
template<typename Type_Double >
void calculer_terme_source_bord (int, Type_Double &) const
Public Member Functions inherited from Evaluateur_Source_VDF
Evaluateur_Source_VDF ()
Evaluateur_Source_VDF (const Evaluateur_Source_VDF &eval)
virtual ~Evaluateur_Source_VDF ()
template<typename Type_Double >
void calculer_terme_source (int, Type_Double &) const
virtual void mettre_a_jour ()=0
virtual void completer ()=0
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
Public Attributes
Modele_Permeabilite modK
Protected Attributes
Ref_Champ_Inc vitesse
double Cf
double porosite
Protected Attributes inherited from Evaluateur_Source_VDF_Face
IntVect orientation
orientations des faces
DoubleVect volumes_entrelaces
DoubleVect porosite_surf
porosites surfaciques
Protected Attributes inherited from Evaluateur_Source_VDF
Ref_Zone_VDF la_zone
Ref_Zone_Cl_VDF la_zcl
Detailed Description
Definition at line 23 of file Eval_Forchheimer_VDF_Face.h.
Constructor & Destructor Documentation
Eval_Forchheimer_VDF_Face() [1/2]
Eval_Forchheimer_VDF_Face::Eval_Forchheimer_VDF_Face () inline
Definition at line 26 of file Eval_Forchheimer_VDF_Face.h.
: Cf(1.), porosite(1) { }
Eval_Forchheimer_VDF_Face() [2/2]
Eval_Forchheimer_VDF_Face::Eval_Forchheimer_VDF_Face (const Eval_Forchheimer_VDF_Face & eval) inline
Definition at line 27 of file Eval_Forchheimer_VDF_Face.h.
: Evaluateur_Source_VDF_Face(eval), Cf(1.), porosite(1) { }
Member Function Documentation
associer()
void Eval_Forchheimer_VDF_Face::associer (const Champ_Inc & vit) inline
Definition at line 32 of file Eval_Forchheimer_VDF_Face.h.
{ vitesse = vit;}
References vitesse.
Referenced by Source_Forchheimer_VDF_Face::associer_pb().
calculer_terme_source()
template<typename Type_Double > void Eval_Forchheimer_VDF_Face::calculer_terme_source (const int num_face, Type_Double & source) const
Definition at line 43 of file Eval_Forchheimer_VDF_Face.h.
{
  const int size = source.size_array();
  for (int i = 0; i < size; i++)
    {
      const double U = (vitesse->valeurs())(num_face,i);
      source[i] = -Cf/sqrt(modK->getK(porosite))*volumes_entrelaces(num_face)*porosite_surf(num_face)*std::fabs(U)*U;
    }
}
References Cf, Modele_Permeabilite::getK(), modK, porosite, Evaluateur_Source_VDF_Face::porosite_surf, Champ_Inc::valeurs(), vitesse, and Evaluateur_Source_VDF_Face::volumes_entrelaces.
Referenced by calculer_terme_source_bord().
calculer_terme_source_bord()
template<typename Type_Double > void Eval_Forchheimer_VDF_Face::calculer_terme_source_bord (const int num_face, Type_Double & source) const inline
Definition at line 29 of file Eval_Forchheimer_VDF_Face.h.
{ calculer_terme_source(num_face,source); }
References calculer_terme_source().
mettre_a_jour()
void Eval_Forchheimer_VDF_Face::mettre_a_jour () inline override virtual
Implements Evaluateur_Source_VDF.
Definition at line 30 of file Eval_Forchheimer_VDF_Face.h.
{ /* Do nothing */}
setCf()
void Eval_Forchheimer_VDF_Face::setCf (double c) inline
Definition at line 31 of file Eval_Forchheimer_VDF_Face.h.
{ Cf = c; }
References Cf.
Referenced by Source_Forchheimer_VDF_Face::readOn().
setPorosite()
void Eval_Forchheimer_VDF_Face::setPorosite (double p) inline
Definition at line 33 of file Eval_Forchheimer_VDF_Face.h.
{ porosite = p; }
References porosite.
Referenced by Source_Forchheimer_VDF_Face::readOn().
Member Data Documentation
Cf
double Eval_Forchheimer_VDF_Face::Cf protected
Definition at line 39 of file Eval_Forchheimer_VDF_Face.h.
Referenced by calculer_terme_source(), and setCf().
modK
Modele_Permeabilite Eval_Forchheimer_VDF_Face::modK
Definition at line 35 of file Eval_Forchheimer_VDF_Face.h.
Referenced by calculer_terme_source(), and Source_Forchheimer_VDF_Face::readOn().
porosite
double Eval_Forchheimer_VDF_Face::porosite protected
Definition at line 39 of file Eval_Forchheimer_VDF_Face.h.
Referenced by calculer_terme_source(), and setPorosite().
vitesse
Ref_Champ_Inc Eval_Forchheimer_VDF_Face::vitesse protected
Definition at line 38 of file Eval_Forchheimer_VDF_Face.h.
Referenced by associer(), and calculer_terme_source().
The documentation for this class was generated from the following file:
src/VDF/Sources/Evaluateurs/Eval_Forchheimer_VDF_Face.h