TRUST: Pb_MED Class Reference
Pb_MED Class Reference
Classe Pb_MED
Classe pour postraiter relire des fichiers med et les postraiter.
#include <Pb_MED.h>
Public Member Functions
Pb_MED ()
~Pb_MED ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int nombre_d_equations () const override
Renvoie le nombre d'equations du probleme.
Toujours egal a 1 pour un probleme de conduction standart.
const Equation_base & equation (int) const override
Renvoie l'equation de type MED
si i = 0,
Provoque une erreur sinon car le probleme
n'a qu'une seule equation.
(version const)
Equation_base & equation (int) override
Renvoie l'equation de type MED
si i = 0,
Provoque une erreur sinon car le probleme
n'a qu'une seule equation.
int comprend_champ (const Motcle &) const
const ArrOfDouble & temps_sauv () const
Champs_Fonc & get_champs_fonc_post ()
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Probleme_base
~Probleme_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void initialize () override
This method is called once at the beginning, before any other one of
the interface Problem.
void terminate () override
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
double presentTime () const override
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
double computeTimeStep (bool &stop) const override
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
bool initTimeStep (double dt) override
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
bool solveTimeStep () override
pour recodage eventuel et appel unifie en python
void validateTimeStep () override
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
bool isStationary () const override
Tells if the Problem unknowns have changed during the last time step.
void setStationary (bool) override
Tells to the Problem that stationary is reached or not.
void abortTimeStep () override
Aborts the resolution of the current time step.
bool iterateTimeStep (bool &converged) override
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
void getInputFieldsNames (Noms &noms) const override
This method is used to find the names of input fields understood by the Problem.
void getOutputFieldsNames (Noms &noms) const override
This method is used to find the names of output fields understood by the Problem.
int postraiter (int force=1) override
Si force=1, effectue le postraitement sans tenir compte des
frequences de postraitement.
Le postraitement est mis a jour et les traitements eventuels sur
les sondes, champs et statistiques sont effectues.
Si force=0, tient compte des frequences d'impression demandees.
int limpr () const override
Demande au schema en temps s'il faut faire une impression.
int lsauv () const override
Demande au schema en temps s'il faut faire une sauvegarde.
void sauver () const override
Ecriture sur fichier en vue d'une reprise (sauvegarde)
virtual void allocation () const
Verifie que la place necessaire existe sur le disque dur.
bool updateGivenFields () override
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
double futureTime () const override
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
Ref_Field_base findInputField (const Nom &name) const override
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
Ref_Champ_Generique_base findOutputField (const Nom &name) const override
Probleme_base ()
virtual void associer ()
Associe le probleme a toutes ses equations.
virtual Entree & lire_equations (Entree &is, Motcle &dernier_mot)
Lecture des equations du probleme.
virtual void completer ()
Complete les equations associees au probleme.
Remplissage des references, deleguee aux equations.
virtual int verifier ()
Verifie que l'objet est complet, coherent, ...
NON DEVELOPPE RENVOIE TOUJOURS 1.
virtual int nombre_d_equations () const =0
virtual const Equation_base & equation (int) const =0
virtual Equation_base & equation (int)=0
const Equation_base & equation (const Nom &) const
Renvoie l'equation dont le nom est specifie.
On indexe les equations avec leur nom associe.
On cherche dans toutes les equations du probleme celle
qui porte le nom specifie.
(version const)
Equation_base & equation (const Nom &)
Renvoie l'equation dont le nom est specifie.
On indexe les equations avec leur nom associe.
On cherche dans toutes les equations du probleme celle
qui porte le nom specifie.
virtual const Equation_base & get_equation_by_name (const Nom &) const
virtual Equation_base & getset_equation_by_name (const Nom &)
virtual const Milieu_base & milieu () const
Renvoie le milieu physique associe au probleme.
(version const)
On renvoie le milieu associe a la premiere equation.
virtual Milieu_base & milieu ()
Renvoie le milieu physique associe au probleme.
On renvoie le milieu associe a la premiere equation.
int sauvegarder (Sortie &) const override
Ecriture du probleme sur fichier en vue d'une reprise.
Ecrit le nom du probleme et sauvegarde les equations.
int reprendre (Entree &) override
Lecture d'un flot d'entree (fichier) pour reprise apres
une sauvegarde avec Probleme_base::sauvegarder(Sortie& os).
virtual void imprimer (Sortie &os) const
Appelle imprimer sur chaque equation.
virtual double calculer_pas_de_temps () const
Calcul la valeur du prochain pas de temps du probleme.
On calcule le minimum des pas de temps des equations associees
au probleme.
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps du probleme.
Effectue la mise a jour sur toutes les equations du probleme.
virtual void preparer_calcul ()
Prepare le calcul: initialise les parametres du milieu et
prepare le calcul de chacune des equations.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
Associe un schema en temps au probleme.
Associe ensuite le schema en temps a toutes
les equations du probleme.
virtual void associer_domaine (const Domaine &)
Associe un domaine au probleme.
Prend un_domaine comme support.
apelle Domaine_dis::associer_dom(const Domaine&)
virtual void associer_milieu_base (const Milieu_base &)
Associe un milieu physique aux equations du probleme.
Choix du milieu physique.
int associer_ (Objet_U &) override
surcharge Objet_U::associer_(Objet_U& ob)
Associe differents objets au probleme en controlant
le type de l'objet a associer a l'execution.
On peut ainsi associer: un schema en temps, un domaine de calcul ou
un milieu physique.
Utilise les routine de la classe Type_Info (Utilitaires)
virtual void discretiser (const Discretisation_base &)
Affecte une discretisation au probleme
Discretise le Domaine associe au probleme avec la discretisation
Associe la premiere zone du Domaine aux equations du probleme
Discretise les equations associees au probleme
NOTE: TRUST V1 une seule Zone_dis pas Domaine_dis est traitee.
virtual void finir ()
Finit le postraitement et sauve le probleme dans un fichier.
Fermeture du fichier associe au postraitement.(Postraitement::finir())
const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe au probleme. (si il est non nul)
(version const)
Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe au probleme. (si il est non nul)
const Domaine & domaine () const
Renvoie le domaine associe au probleme.
(version const)
Domaine & domaine ()
Renvoie le domaine associe au probleme.
const Domaine_dis & domaine_dis () const
Renvoie le domaine discretise associe au probleme.
(version const)
Domaine_dis & domaine_dis ()
Renvoie le domaine discretise associe au probleme.
int is_dilatable () const
virtual int allocate_file_size (long int &size) const
Verifie que la place necessaire existe sur le disque dur.
virtual int file_size_xyz () const
Ecrit le probleme dans un fichier *.calcul_xyz
et calcul la place disque prise par ce fichier.
void nommer (const Nom &) override
surcharge Objet_U::nommer(const Nom&)
Donne un nom au probleme
const Nom & le_nom () const override
surcharge Objet_U::le_nom()
Renvoie le nom du probleme
const Discretisation_base & discretisation () const
Renvoie la discretisation associee au probleme.
Postraitements & postraitements ()
const Postraitements & postraitements () const
void init_postraitements ()
virtual int expression_predefini (const Motcle &motlu, Nom &expression)
const char * reprise_format_temps () const
int & reprise_effectuee ()
int reprise_effectuee () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual bool has_champ (const Motcle &nom) const
virtual const Champ_Generique_base & get_champ_post (const Motcle &nom) const
virtual int comprend_champ_post (const Motcle &nom) const
virtual int verifie_tdeb_tfin (const Motcle &nom) const
On verifie que le temps de debut et de fin des statistiques est identique sur tous les champsde tous les postraitements.
virtual int a_pour_IntVect (const Motcle &, Ref_IntVect &) const
virtual void lire_postraitement_interfaces (Entree &is)
virtual void postraiter_interfaces (const Nom &nom_fich, Sortie &s, const Nom &format, double temps)
virtual void addInputField (Field_base &f)
void sauver_xyz (int) const
void set_coupled (int i)
int get_coupled () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Probleme_U
Probleme_U ()
~Probleme_U () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void initialize ()
This method is called once at the beginning, before any other one of
the interface Problem.
virtual void terminate ()
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
virtual double presentTime () const
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
virtual double computeTimeStep (bool &stop) const
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
virtual bool initTimeStep (double dt)
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
virtual bool solveTimeStep ()
pour recodage eventuel et appel unifie en python
virtual void validateTimeStep ()
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
virtual bool isStationary () const
Tells if the Problem unknowns have changed during the last time step.
virtual void setStationary (bool)
Tells to the Problem that stationary is reached or not.
virtual void abortTimeStep ()
Aborts the resolution of the current time step.
virtual bool iterateTimeStep (bool &converged)
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
virtual void getInputFieldsNames (Noms &noms) const
This method is used to find the names of input fields understood by the Problem.
virtual void getInputFieldTemplate (const Nom &name, ICoCo::TrioField &afield) const
This method is used to get a template of a field expected for the given name.
virtual void setInputField (const Nom &name, const ICoCo::TrioField &afield)
This method is used to provide the Problem with an input field.
virtual void getOutputFieldsNames (Noms &noms) const
This method is used to find the names of output fields understood by the Problem.
virtual void getOutputField (const Nom &nameField, ICoCo::TrioField &afield) const
virtual void setInputIntValue (const Nom &name, const int &val)
virtual int getOutputIntValue (const Nom &name) const
virtual void setInputDoubleValue (const Nom &name, const double val)
virtual int postraiter (int force=1)
Demande au probleme de postraiter ses champs, sondes,...
Dans Probleme_U::run(), postraiter() est appele a chaque pas de
temps avec force=0 et au debut et a la fin du calcul avec force=1.
WEC : il serait bon que, un jour, postraiter soit const.
virtual int limpr () const
Doit-on imprimer les statistiques d'execution maintenant ?
virtual int lsauv () const
Doit-on sauvegarder l'etat du probleme sur disque maintenant ?
virtual void sauver () const
Sauvegarder l'etat du probleme sur disque.
virtual bool updateGivenFields ()
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
virtual double futureTime () const
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
virtual bool run ()
Cette methode est une sorte de main() du Problem
Elle peut etre utilisee si le probleme n'est couple a aucun autre.
(s'il n'a besoin d'aucun champ d'entree).
virtual bool runUntil (double time)
This method has the same role as the method run, but it stops
when reaching the time given in parameter.
If this time cannot be reached, the method returns false.
virtual Ref_Field_base findInputField (const Nom &name) const
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
virtual Ref_Champ_Generique_base findOutputField (const Nom &name) const
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Pb_MED & self_cast (Objet_U &)
static const Pb_MED & self_cast (const Objet_U &)
Static Public Member Functions inherited from Probleme_base
static const Type_info * info ()
static Probleme_base & self_cast (Objet_U &)
static const Probleme_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Probleme_U
static const Type_info * info ()
static Probleme_U & self_cast (Objet_U &)
static const Probleme_U & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Probleme_base
static const Type_info info_obj
Static Public Attributes inherited from Probleme_U
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
Simple appel a: Probleme_base::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un probleme sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les equations, le postraitement et le domaine
discretise.
Entree & readOn (Entree &) override
Lecture d'un probleme dans un flot d'entree, et ouverture du
flot de sauvegarde.
Format:
{
nom_equation bloc de lecture d'une equation
Postraitement bloc de lecture postraitement
reprise | sauvegarde | sauvegarde_simple
formatte | binaire
nom_de_fichier
}
L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi
en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Sortie & printOn (Sortie &x) const override
A surcharger...
Entree & readOn (Entree &) override
A surcharger...
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champs_Fonc champs_fonc_post
Protected Attributes inherited from Probleme_base
Domaine_dis le_domaine_dis
Postraitements les_postraitements
Ref_Schema_Temps_base le_schema_en_temps
Ref_Discretisation_base la_discretisation
List_Ref_Field_base input_fields
List of input fields inside this problem.
Deriv_Sortie_Fichier_base ficsauv_
Sortie_Brute * osauv_hdf_
int reprise_effectuee_
int reprise_version_
Nom nom_fich
Nom format_sauv
int restart_file
bool initialized
true if initialize was called
bool terminated
true if terminate was called
bool dt_defined
true if computation interval is defined set to true by initTimeStep, to false by validateTimeStep & abortTimeStep
bool dt_validated
true if last computation was validated set to true by validateTimeStep, to false by initTimeStep
double tstat_deb_
double tstat_fin_
Nom error
Erreur d'allocation.
int coupled_
Flag to indicate it is a part of a coupled problem.
List_Ref_Loi_Fermeture_base liste_loi_fermeture_
liste des fermetures associees au probleme
Protected Attributes inherited from Probleme_U
Nom nom
ScalarRegister reg
Private Attributes
Nom nom_fic
Noms nomschampmed
Discretisation dis_bidon
ArrOfDouble temps_sauv_
Additional Inherited Members
Static Protected Attributes inherited from Probleme_base
static long int file_size =0
Espace disque pris par les sauvegarde XYZ.
static int bad_allocate =1
1 si allocation reussi, 0 sinon
static int nb_pb_total =0
Nombre total de probleme.
static int num_pb =1
numero du probleme
Detailed Description
Classe Pb_MED
Classe pour postraiter relire des fichiers med et les postraiter.
Definition at line 33 of file Pb_MED.h.
Constructor & Destructor Documentation
Pb_MED()
Pb_MED::Pb_MED ()
Definition at line 22 of file Pb_MED.cpp.
~Pb_MED()
Pb_MED::~Pb_MED ()
Definition at line 22 of file Pb_MED.cpp.
Member Function Documentation
comprend_champ()
int Pb_MED::comprend_champ (const Motcle & mot) const
Definition at line 257 of file Pb_MED.cpp.
{
// Cerr<<" Pb_MED::comprend_champ"<<mot <<" " <<nomschampmed<<finl;
  int nbchampmed=nomschampmed.size();
  int ind=0;
  for (int ch=0; ch<nbchampmed; ch++)
    {
      if (mot==nomschampmed[ch]) ind= 1;
    }
  if (ind == 1)
    return ind;
  if (ind == 0)
    {
      Cerr << "Error when reading the data for post-processing" << finl;
      Cerr << "The field " << mot << " is not recognized by the problem" << finl;
      Cerr << "recognized words are "<<nomschampmed<<finl;
      exit();
    }
  return -1;
}
References Cerr, Process::exit(), finl, nomschampmed, and vect_impl::size().
cree_instance()
Objet_U * Pb_MED::cree_instance () static
Definition at line 22 of file Pb_MED.cpp.
creer_champ()
void Pb_MED::creer_champ (const Motcle & motlu) override virtual
< on ajoute toto et on le type apres pour eviter des copies qui ne marchent pas ...
Reimplemented from Probleme_base.
Definition at line 280 of file Pb_MED.cpp.
{
  Cerr<<"Pb_MED::creer_champ "<< motlu<<finl;
  Noms liste_noms;
  get_noms_champs_postraitables(liste_noms);
  Champ_Fonc toto; //!< on ajoute toto et on le type apres pour eviter des copies qui ne marchent pas ...
  Champ_Fonc& le_ch_fonc= champs_fonc_post.add(toto);
  le_ch_fonc.typer("Champ_Fonc_MED");
  int nbchampmed=nomschampmed.size();
  Nom localisation;
  Motcle es;
  le_ch_fonc.valeur().nommer(motlu);
  int flag=0;
  Nom test("_");
  test+=domaine().le_nom();
  for (int ch=0; ch<nbchampmed; ch++)
    {
      Nom pp(nomschampmed[ch]);
      pp.prefix(test);
// Cerr<<test<<" ICI "<<pp<<" "<<motlu<<finl;
      if (motlu==pp)
        {
          es=pp;
          es.prefix("_SOM");
          if (es!=pp)
            localisation="som";
          else
            {
              es.prefix("_ELEM");
              if (es!=pp)
                localisation="elem";
            }
          Cerr<<"One wishes to read the field "<<es<<" choice "<<localisation<<" readen word in the data set "<<motlu<<finl;
          le_ch_fonc.valeur().nommer(es);
          flag=1;
        }
    }
  Champ_Fonc_MED& chmed=ref_cast(Champ_Fonc_MED,le_ch_fonc.valeur());
  const Domaine& dom_med = domaine();
  chmed.creer(nom_fic,dom_med,localisation, temps_sauv_);
  if (flag)
    {
      chmed.le_champ().nommer(le_ch_fonc.valeur().le_nom());
      chmed.le_champ().corriger_unite_nom_compo();
      chmed.le_champ().nommer(motlu);
    }
  le_ch_fonc.valeur().nommer(motlu);
  chmed.le_champ().nommer(motlu);
  if (!le_ch_fonc.non_nul())
    {
      Cerr << "Error when reading data for post-processing" << finl;
      Cerr << "The creation of the field " << motlu << " has failed." << finl;
      exit();
    }
}
References List_Champ_Fonc::add(), Cerr, champs_fonc_post, Champ_base::corriger_unite_nom_compo(), Champ_Fonc_MED::creer(), Probleme_base::domaine(), Process::exit(), finl, get_noms_champs_postraitables(), Champ_Fonc_MED::le_champ(), Field_base::le_nom(), Domaine::le_nom(), nom_fic, Field_base::nommer(), nomschampmed, O_U_Ptr::non_nul(), Nom::prefix(), ref_cast, vect_impl::size(), temps_sauv_, test(), Deriv_::typer(), and Deriv_Champ_Fonc_base::valeur().
duplique()
int Pb_MED::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file Pb_MED.cpp.
equation() [1/2]
const Equation_base & Pb_MED::equation (int i) const override virtual
Renvoie l'equation de type MED
si i = 0,
Provoque une erreur sinon car le probleme
n'a qu'une seule equation.
(version const)
Returns
Equation_base&
Signification: l'equation de type MED
Contraintes: reference constante
Implements Probleme_base.
Definition at line 219 of file Pb_MED.cpp.
{
  assert(0);
  exit();
  assert (i==0);
// pour les compilos
  return Probleme_base::equation("bidon");
}
References Probleme_base::equation(), and Process::exit().
equation() [2/2]
Equation_base & Pb_MED::equation (int i) override virtual
Renvoie l'equation de type MED
si i = 0,
Provoque une erreur sinon car le probleme
n'a qu'une seule equation.
Returns
Equation_base&
Signification: l'equation de type MED
Contraintes:
Implements Probleme_base.
Definition at line 246 of file Pb_MED.cpp.
{
  assert(0);
  exit();
  assert (i==0);
// pour les compilos
  return Probleme_base::equation("bidon") ;
}
References Probleme_base::equation(), and Process::exit().
get_champ()
const Champ_base & Pb_MED::get_champ (const Motcle & nom) const override virtual
Reimplemented from Probleme_base.
Definition at line 341 of file Pb_MED.cpp.
{
  REF(Champ_base) ref_champ;
  double temps_courant = schema_temps().temps_courant();
  CONST_LIST_CURSEUR(Champ_Fonc) curseur = champs_fonc_post ;
  Motcle nom_champ;
  int ok_post=1;
  while(curseur)
    {
      Champ_Fonc_MED& ch_med = ref_cast_non_const(Champ_Fonc_MED,curseur.valeur().valeur());
      nom_champ = Motcle(curseur.valeur().le_nom());
// nom_champ=ch_med.le_champ().le_nom();
// Cerr<<(int)__LINE__<<nom_champ<<finl;
// nom_champ = Motcle(curseur.valeur().valeur().le_nom());
      if ((nom_champ==un_nom) && (ok_post==1))
        {
          ref_champ = curseur.valeur();
          if (ch_med.temps()!=temps_courant)
            ch_med.mettre_a_jour(temps_courant);
          return ch_med.le_champ();
// return ref_champ.valeur();
        }
      else
        {
          int nb_composantes = curseur.valeur().valeur().nb_comp();
          for (int i=0; i<nb_composantes; i++)
            {
              nom_champ = Motcle(curseur.valeur().valeur().nom_compo(i));
              if ((nom_champ==un_nom) && (ok_post==1))
                {
                  ref_champ = curseur.valeur();
                  if (ch_med.temps()!=temps_courant)
                    ch_med.mettre_a_jour(temps_courant);
// return ref_champ.valeur();
                  return ch_med.le_champ();
                }
            }
        }
      ++curseur;
    }
  Cerr<<"The indicated name "<<un_nom<<" do not correspond to a field understood by the problem"<<finl;
  Cerr<<"Check the field name to indicate in the post-processing set"<<finl;
  exit();
// Pour compilation
  return ref_champ;
}
References Cerr, champs_fonc_post, CONST_LIST_CURSEUR, Process::exit(), finl, Champ_Fonc_MED::le_champ(), Champ_Fonc_MED::mettre_a_jour(), Field_base::nb_comp(), REF, ref_cast_non_const, Probleme_base::schema_temps(), Champ_base::temps(), and Schema_Temps_base::temps_courant().
get_champs_fonc_post()
Champs_Fonc & Pb_MED::get_champs_fonc_post () inline
Definition at line 49 of file Pb_MED.h.
  {
    return champs_fonc_post;
  };
References champs_fonc_post.
get_info()
const Type_info * Pb_MED::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Probleme_base.
Definition at line 22 of file Pb_MED.cpp.
get_noms_champs_postraitables()
void Pb_MED::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Probleme_base.
Definition at line 392 of file Pb_MED.cpp.
{
// La methode surcharge celle de Probleme_base
  if (opt==DESCRIPTION)
    Cerr<<"Pb_MED : : "<<nomschampmed<<finl;
  else
    noms.add(nomschampmed);
}
References Vect_Nom::add(), Cerr, DESCRIPTION, finl, and nomschampmed.
Referenced by creer_champ().
info()
const Type_info * Pb_MED::info () static
Definition at line 22 of file Pb_MED.cpp.
nombre_d_equations()
int Pb_MED::nombre_d_equations () const override virtual
Renvoie le nombre d'equations du probleme.
Toujours egal a 1 pour un probleme de conduction standart.
Returns
int
Signification: le nombre d'equations du probleme
Contraintes: toujours egal a 1
Implements Probleme_base.
Definition at line 196 of file Pb_MED.cpp.
{
  return 0;
}
printOn()
Sortie & Pb_MED::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Probleme_base.
Definition at line 40 of file Pb_MED.cpp.
{
  return s;
}
readOn()
Entree & Pb_MED::readOn (Entree & is) override protected virtual
Simple appel a: Probleme_base::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Probleme_base.
Definition at line 147 of file Pb_MED.cpp.
{
  dis_bidon.typer("VF_inst");
  la_discretisation=dis_bidon.valeur();
  is >> nom_fic;
  Nom nom_dom;
  is >> nom_dom;
// on retire _0000 si il existe et on cree le bon fichier
  traite_nom_fichier_med(nom_fic);
  Domaine& dom=ref_cast(Domaine, Interprete::objet(nom_dom));
  associer_domaine(dom);
// Read domain in MED file:
  LireMED lire;
  lire.lire_geom(nom_fic, dom, nom_dom, nom_dom);
  dom.reordonner();
  le_domaine_dis.associer_domaine(dom);
  le_domaine_dis.discretiser("NO_FACE_Zone_VF_inst");
  Cerr<<"Reading the name of existing fields in "<<nom_fic<<finl;
#ifdef MED_
  medinfochamp_existe(nom_fic, nomschampmed, domaine(), temps_sauv_);
#else
  med_non_installe();
#endif
  Cerr<<"temps_sauv "<<temps_sauv_<<finl;
  Probleme_base::readOn(is);
  return is;
}
References Domaine_dis::associer_domaine(), Probleme_base::associer_domaine(), Cerr, dis_bidon, Domaine_dis::discretiser(), Probleme_base::domaine(), finl, Probleme_base::la_discretisation, Probleme_base::le_domaine_dis, LireMED::lire_geom(), med_non_installe(), medinfochamp_existe(), nom_fic, nomschampmed, Interprete::objet(), Probleme_base::readOn(), ref_cast, Domaine::reordonner(), temps_sauv_, traite_nom_fichier_med(), Deriv_::typer(), and Deriv_Discretisation_base::valeur().
self_cast() [1/2]
const Pb_MED & Pb_MED::self_cast (const Objet_U & r) static
Definition at line 22 of file Pb_MED.cpp.
self_cast() [2/2]
Pb_MED & Pb_MED::self_cast (Objet_U & r) static
Definition at line 22 of file Pb_MED.cpp.
taille_memoire()
unsigned Pb_MED::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file Pb_MED.cpp.
temps_sauv()
const ArrOfDouble & Pb_MED::temps_sauv () const inline
Definition at line 45 of file Pb_MED.h.
  {
    return temps_sauv_ ;
  };
References temps_sauv_.
Member Data Documentation
champs_fonc_post
Champs_Fonc Pb_MED::champs_fonc_post protected
Definition at line 63 of file Pb_MED.h.
Referenced by creer_champ(), get_champ(), and get_champs_fonc_post().
dis_bidon
Discretisation Pb_MED::dis_bidon private
Definition at line 68 of file Pb_MED.h.
Referenced by readOn().
info_obj
const Type_info Pb_MED::info_obj static
Definition at line 36 of file Pb_MED.h.
nom_fic
Nom Pb_MED::nom_fic private
Definition at line 66 of file Pb_MED.h.
Referenced by creer_champ(), and readOn().
nomschampmed
Noms Pb_MED::nomschampmed private
Definition at line 67 of file Pb_MED.h.
Referenced by comprend_champ(), creer_champ(), get_noms_champs_postraitables(), and readOn().
temps_sauv_
ArrOfDouble Pb_MED::temps_sauv_ private
Definition at line 69 of file Pb_MED.h.
Referenced by creer_champ(), readOn(), and temps_sauv().
The documentation for this class was generated from the following files:
src/Kernel/MEDimpl/Pb_MED.h
src/Kernel/MEDimpl/Pb_MED.cpp