TRUST: Pb_Thermohydraulique_WC Class Reference
Pb_Thermohydraulique_WC Class Reference
classe Pb_Thermohydraulique_WC
Cette classe represente un probleme de thermohydraulique en fluide weakly compressible:
- Equations de Navier_Stokes en regime laminaire
- Equation d'energie exprimee en temperature (gaz parfait) ou enthalpie (gaz reel)
en regime laminaire
#include <Pb_Thermohydraulique_WC.h>
Public Member Functions
Pb_Thermohydraulique_WC ()
~Pb_Thermohydraulique_WC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int verifier ()
Teste la compatibilite des equations de la thermique et de l'hydraulique.
int nombre_d_equations () const
Renvoie 2 car il y a 2 equations : Navier_Stokes_WC et Convection_Diffusion_Chaleur_WC.
const Equation_base & equation (int) const
Renvoie l'equation d'hydraulique de type Navier_Stokes_WC si i=0
Renvoie l'equation de la thermique de type Convection_Diffusion_Chaleur_WC si i=1.
Equation_base & equation (int)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Pb_Thermohydraulique_WC & self_cast (Objet_U &)
static const
Pb_Thermohydraulique_WC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un probleme sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les equations, le postraitement et le domaine
discretise.
virtual Entree & readOn (Entree &)
Lecture d'un probleme dans un flot d'entree, et ouverture du
flot de sauvegarde.
Format:
{
nom_equation bloc de lecture d'une equation
Postraitement bloc de lecture postraitement
reprise | sauvegarde | sauvegarde_simple
formatte | binaire
nom_de_fichier
}
L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi
en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Protected Attributes
Navier_Stokes_WC eq_hydraulique
Convection_Diffusion_Chaleur_WC eq_thermique
Detailed Description
classe Pb_Thermohydraulique_WC
Cette classe represente un probleme de thermohydraulique en fluide weakly compressible:
- Equations de Navier_Stokes en regime laminaire
- Equation d'energie exprimee en temperature (gaz parfait) ou enthalpie (gaz reel)
en regime laminaire
Definition at line 43 of file Pb_Thermohydraulique_WC.h.
Constructor & Destructor Documentation
Pb_Thermohydraulique_WC::Pb_Thermohydraulique_WC ()
Definition at line 25 of file Pb_Thermohydraulique_WC.cpp.
Pb_Thermohydraulique_WC::~Pb_Thermohydraulique_WC ()
Definition at line 25 of file Pb_Thermohydraulique_WC.cpp.
Member Function Documentation
Objet_U * Pb_Thermohydraulique_WC::cree_instance () [static]
Reimplemented in Pb_Thermohydraulique_Especes_WC.
Definition at line 25 of file Pb_Thermohydraulique_WC.cpp.
int Pb_Thermohydraulique_WC::duplique () const [virtual]
Implements Pb_WC_base.
Reimplemented in Pb_Thermohydraulique_Especes_WC.
Definition at line 25 of file Pb_Thermohydraulique_WC.cpp.
Equation_base & Pb_Thermohydraulique_WC::equation (int i) [virtual]
Implements Probleme_base.
Reimplemented in Pb_Thermohydraulique_Especes_WC.
Definition at line 46 of file Pb_Thermohydraulique_WC.cpp.
References eq_hydraulique, eq_thermique, and Pb_Dilatable_Proto::equation_impl().
{
  return equation_impl(i,eq_hydraulique,eq_thermique);
}
const Equation_base & Pb_Thermohydraulique_WC::equation (int i) const [virtual]
Renvoie l'equation d'hydraulique de type Navier_Stokes_WC si i=0
Renvoie l'equation de la thermique de type Convection_Diffusion_Chaleur_WC si i=1.
Implements Probleme_base.
Reimplemented in Pb_Thermohydraulique_Especes_WC.
Definition at line 41 of file Pb_Thermohydraulique_WC.cpp.
References eq_hydraulique, eq_thermique, and Pb_Dilatable_Proto::equation_impl().
{
  return equation_impl(i,eq_hydraulique,eq_thermique);
}
const Type_info * Pb_Thermohydraulique_WC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Pb_WC_base.
Reimplemented in Pb_Thermohydraulique_Especes_WC.
Definition at line 25 of file Pb_Thermohydraulique_WC.cpp.
const Type_info * Pb_Thermohydraulique_WC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Pb_WC_base.
Reimplemented in Pb_Thermohydraulique_Especes_WC.
Definition at line 25 of file Pb_Thermohydraulique_WC.cpp.
int Pb_Thermohydraulique_WC::nombre_d_equations () const [virtual]
Renvoie 2 car il y a 2 equations : Navier_Stokes_WC et Convection_Diffusion_Chaleur_WC.
Implements Probleme_base.
Reimplemented in Pb_Thermohydraulique_Especes_WC.
Definition at line 36 of file Pb_Thermohydraulique_WC.cpp.
{ return 2; }
Sortie & Pb_Thermohydraulique_WC::printOn (Sortie & os) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un probleme sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les equations, le postraitement et le domaine
discretise.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Pb_WC_base.
Reimplemented in Pb_Thermohydraulique_Especes_WC.
Definition at line 30 of file Pb_Thermohydraulique_WC.cpp.
{ return Probleme_base::printOn(os); }
Entree & Pb_Thermohydraulique_WC::readOn (Entree & is) [protected, virtual]
Lecture d'un probleme dans un flot d'entree, et ouverture du
flot de sauvegarde.
Format:
{
nom_equation bloc de lecture d'une equation
Postraitement bloc de lecture postraitement
reprise | sauvegarde | sauvegarde_simple
formatte | binaire
nom_de_fichier
}
L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi
en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Returns:
Entree&
Signification: le flot d'entre modifie
Contraintes:
Reimplemented from Pb_WC_base.
Reimplemented in Pb_Thermohydraulique_Especes_WC.
Definition at line 32 of file Pb_Thermohydraulique_WC.cpp.
{ return Probleme_base::readOn(is); }
const Pb_Thermohydraulique_WC & Pb_Thermohydraulique_WC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Pb_WC_base.
Reimplemented in Pb_Thermohydraulique_Especes_WC.
Definition at line 25 of file Pb_Thermohydraulique_WC.cpp.
Pb_Thermohydraulique_WC & Pb_Thermohydraulique_WC::self_cast (Objet_U & r) [static]
Reimplemented from Pb_WC_base.
Reimplemented in Pb_Thermohydraulique_Especes_WC.
Definition at line 25 of file Pb_Thermohydraulique_WC.cpp.
unsigned Pb_Thermohydraulique_WC::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Pb_Thermohydraulique_Especes_WC.
Definition at line 25 of file Pb_Thermohydraulique_WC.cpp.
int Pb_Thermohydraulique_WC::verifier () [virtual]
Teste la compatibilite des equations de la thermique et de l'hydraulique.
Reimplemented from Probleme_base.
Definition at line 53 of file Pb_Thermohydraulique_WC.cpp.
References eq_hydraulique, eq_thermique, and Pb_Dilatable_Proto::verifier_impl().
{
  return verifier_impl(eq_hydraulique,eq_thermique, true /* is_thermal */);
}
Member Data Documentation
Navier_Stokes_WC Pb_Thermohydraulique_WC::eq_hydraulique [protected]
Definition at line 53 of file Pb_Thermohydraulique_WC.h.
Referenced by equation(), and verifier().
Convection_Diffusion_Chaleur_WC Pb_Thermohydraulique_WC::eq_thermique [protected]
Definition at line 54 of file Pb_Thermohydraulique_WC.h.
Referenced by equation(), and verifier().
const Type_info Pb_Thermohydraulique_WC::info_obj [static]
Reimplemented from Pb_WC_base.
Reimplemented in Pb_Thermohydraulique_Especes_WC.
Definition at line 45 of file Pb_Thermohydraulique_WC.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Weakly_Compressible/Problems/Pb_Thermohydraulique_WC.h
src/ThHyd/Dilatable/Weakly_Compressible/Problems/Pb_Thermohydraulique_WC.cpp