TRUST: Partitionneur_Tranche Class Reference
Partitionneur_Tranche Class Reference
Partitionneur de domaine en tranches paralleles aux directions
de l'espace. Voir construire_partition.
#include <Partitionneur_Tranche.h>
Public Member Functions
Partitionneur_Tranche ()
~Partitionneur_Tranche ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
void associer_domaine (const Domaine &domaine) override
Premiere etape d'initialisation du partitionneur: on associe un domaine.
void initialiser (const ArrOfInt &nb_tranches)
Deuxieme etape d'initialisation: on definit le nombre de tranches.
(on peut utiliser readOn a la place).
void construire_partition (IntVect &elem_part, int &nb_parts_tot) const override
Public Member Functions inherited from Partitionneur_base
Partitionneur_base ()
~Partitionneur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void associer_domaine (const Domaine &domaine)=0
virtual void declarer_bords_periodiques (const Noms &noms_bords_periodiques)
virtual void construire_partition (IntVect &elem_part, int &nb_parts_tot) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Partitionneur_Tranche & self_cast (Objet_U &)
static const Partitionneur_Tranche & self_cast (const Objet_U &)
static void chercher_direction_perio (const Zone &zone, const Noms &liste_bords_perio, ArrOfInt &directions_perio)
Remplissage du tableau directions perio a partir des noms des bords
periodiques. Pour 0 <= i < Objet_U::dimension directions_perio[i] vaut 1 s'il
existe un bord periodique pour lequel le vecteur delta est dirige dans la direction i.
Static Public Member Functions inherited from Partitionneur_base
static const Type_info * info ()
static Partitionneur_base & self_cast (Objet_U &)
static const Partitionneur_base & self_cast (const Objet_U &)
static void corriger_elem0_sur_proc0 (IntVect &elem_part)
corrige la partition pour que l'element 0 du domaine initial
se trouve sur le premier sous-domaine de la partition.
On echange le premier sous-domaine et celui qui contient l'element 0.
static int calculer_graphe_connexions_periodiques (const Zone &zone, const Noms &liste_bords_periodiques, const Static_Int_Lists &som_elem, const int my_offset, Static_Int_Lists &graph)
Calcul d'un graphe de connectivite entre les elements lies par des faces periodiques.
Si l'element i est voisin de l'element j par une face periodique, alors il existe
k tel que graph(i,k)==j et il existe k2 tel que graph(j,k2)==i.
Parametre: zone
Signification: la zone a traiter
Parametre: liste_bords_periodiques
Signification: liste des noms des bords periodiques. ATTENTION: on suppose que les
faces des bords periodiques sont rangees selon la convention des bords periodiques.
Voir check_faces_periodiques().
Parametre: som_elem
Signification: la connectivite sommets-elements pour la zone donnee.
Parametre: graph
Signification: On y stocke le resultat.
Valeur de retour: nombre d'elements dans le graphe (egal au nombre de faces periodiques)
static int corriger_bords_avec_graphe (const Static_Int_Lists &graph_elements_perio, const Static_Int_Lists &som_elem, const Domaine &domaine, const Noms &liste_bords_perio, IntVect &elem_part)
corrige la partition elem_part pour qu'un element i se trouve sur la meme
partition elem_part[i] que tous les elements auxquels il est lie dans le graphe
(elements d'indices graph_elements_perio(i, j) pour tout j).
Parametre: graph_elements_perio
Signification: graphe calcule par la methode calculer_graphe_connexions_periodiques
Parametre: elem_part
Signification: pour chaque element, a quelle partie appartient-il.
Valeur de retour: nombre d'elements dont la partition a ete corrigee.
static void corriger_bords_avec_liste (const Domaine &dom, const Noms &liste_bords_periodiques, const int my_offset, IntVect &elem_part)
Calcul des graphes de connectivite elements periodiques et appel a
corriger_periodique_avec_graphe. (Methode a utiliser quand on ne dispose
pas encore du graphe de de connectivite, si on a le graphe sous la main,
appeler directement corriger_periodique_avec_graphe)
static int corriger_sommets_bord (const Domaine &domaine, const Noms &liste_bords_perio, const ArrOfInt &renum_som_perio, const Static_Int_Lists &som_elem, IntVect &elem_part)
Modifie elem_part pour assurer les proprietes suivantes :
1) Les elements possedant un sommet de bord sont associes
a un processeur possedant une face de bord adjacente a ce sommet.
2) Si un processeur possede un sommet periodique reel, il
possede forcement le renum_som_perio associe (donc un element
qui possede ce sommet et un face periodique).
Cette propriete est indispensable pour le periodique (existence
de renum_som_perio pour tous les sommets).
Pour les autres bords, cette correction est peut-etre inutile, mais
pas sur. Sans cette correction, il peut exister des sommets de bord
isoles (un processeur possede un sommet de bord mais aucune face).
Si on cherche les sommets de bord en parcourant les faces de bord,
c'est faux. Avec cette correction, cet algorithme est correct.
static int corriger_multiperiodique (const Domaine &domaine, const Noms &liste_bords_perio, const ArrOfInt &renum_som_perio, const Static_Int_Lists &som_elem, IntVect &elem_part)
applique des corrections a elem_part pour que le
multi-periodique soit correct :
Si un sommet appartient a plusieurs frontieres periodiques,
tous les elements adjacents sont rattaches au meme processeur.
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Partitionneur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Ref_Domaine ref_domaine_
ArrOfInt nb_tranches_
Additional Inherited Members
Protected Attributes inherited from Partitionneur_base
Noms liste_bords_periodiques_
Detailed Description
Partitionneur de domaine en tranches paralleles aux directions
de l'espace. Voir construire_partition.
Definition at line 25 of file Partitionneur_Tranche.h.
Constructor & Destructor Documentation
Partitionneur_Tranche()
Partitionneur_Tranche::Partitionneur_Tranche ()
Definition at line 24 of file Partitionneur_Tranche.cpp.
{
}
~Partitionneur_Tranche()
Partitionneur_Tranche::~Partitionneur_Tranche ()
Definition at line 22 of file Partitionneur_Tranche.cpp.
Member Function Documentation
associer_domaine()
void Partitionneur_Tranche::associer_domaine (const Domaine & domaine) override virtual
Premiere etape d'initialisation du partitionneur: on associe un domaine.
Implements Partitionneur_base.
Definition at line 62 of file Partitionneur_Tranche.cpp.
{
  ref_domaine_ = domaine;
  nb_tranches_.resize(domaine.dimension);
  nb_tranches_ = -1;
}
References Objet_U::dimension, nb_tranches_, ref_domaine_, and TRUSTArray< _TYPE_ >::resize().
chercher_direction_perio()
void Partitionneur_Tranche::chercher_direction_perio (const Zone & zone, const Noms & liste_bords_perio, ArrOfInt & directions_perio) static
Remplissage du tableau directions perio a partir des noms des bords
periodiques. Pour 0 <= i < Objet_U::dimension directions_perio[i] vaut 1 s'il
existe un bord periodique pour lequel le vecteur delta est dirige dans la direction i.
Definition at line 123 of file Partitionneur_Tranche.cpp.
{
  Cerr << "Search of periodic directions of domain " << zone.domaine().le_nom() << finl;
  const int dim = Objet_U::dimension;
  directions_perio.resize_array(dim);
  directions_perio = 0;
  const int n = liste_bords_perio.size();
  for (int i = 0; i < n; i++)
    {
      int num_bord = 0;
      const Nom& nom_bord = liste_bords_perio[i];
      const int nb_bords = zone.nb_bords();
      while (num_bord < nb_bords)
        {
          if (zone.bord(num_bord).le_nom() == nom_bord)
            break;
          num_bord++;
        }
      if (num_bord == nb_bords)
        {
          Cerr << "Error in Partitionneur_Tranche::chercher_direction_perio\n"
               << " boundary not found : " << nom_bord << finl;
          exit();
        }
      ArrOfDouble delta;
      ArrOfDouble erreur;
      const double epsilon = Objet_U::precision_geom;
      Reordonner_faces_periodiques::check_faces_periodiques(zone.bord(num_bord), delta, erreur);
      int count = 0;
      for (int j = 0; j < dim; j++)
        {
          if (std::fabs(delta[j]) > epsilon)
            {
              directions_perio[j]++;
              Cerr << " Boundary : " << nom_bord << " periodic direction : " << j << finl;
              count++;
            }
        }
      if (count != 1)
        {
          Cerr << "Error in Partitionneur_Tranche::chercher_direction_perio\n"
               << " periodic direction not found for the boundary " << nom_bord
               << "\n Vector delta found between faces twin : " << delta
               << "\n with a maximum error : " << erreur << finl;
          exit();
        }
    }
  if (max_array(directions_perio) > 1)
    {
      Cerr << "Error in Partitionneur_Tranche::chercher_direction_perio\n"
           << " several boundaries have the same periodic direction" << finl;
      exit();
    }
}
References Zone::bord(), Cerr, Reordonner_faces_periodiques::check_faces_periodiques(), Objet_U::dimension, Zone::domaine(), erreur(), Process::exit(), finl, Domaine::le_nom(), Frontiere::le_nom(), max_array(), Zone::nb_bords(), Objet_U::precision_geom, TRUSTArray< _TYPE_ >::resize_array(), and vect_impl::size().
Referenced by construire_partition().
construire_partition()
void Partitionneur_Tranche::construire_partition (IntVect & elem_part, int & nb_parts_tot) const override virtual
Implements Partitionneur_base.
Definition at line 180 of file Partitionneur_Tranche.cpp.
{
  assert(ref_domaine_.non_nul());
  assert(nb_tranches_[0] > 0);
  const Domaine& dom = ref_domaine_.valeur();
  const Zone& zone = dom.zone(0);
  const int nb_elem = zone.nb_elem();
  const int dim = dom.dimension;
// Centre de gravite des elements:
  DoubleTab coord_g;
// Index utilise pour trier les elements
  ArrOfInt index;
// Pour chaque dimension d'espace, cette direction est-elle
// une direction de periodicite
  ArrOfInt directions_perio;
  chercher_direction_perio(zone, liste_bords_periodiques_, directions_perio);
  Cerr << "Calculation of centers of gravity of the elements" << finl;
  zone.calculer_centres_gravite(coord_g);
  assert(coord_g.dimension(0) == nb_elem);
  assert(coord_g.dimension(1) == dim);
  Cerr << "Moving of centers of gravity" << finl;
// Deplacement des coordonnees pour qu'il y ait une vraie relation d'ordre
// dans chaque direction (en VDF, eviter les coordonnees identiques)
  {
    for (int i = 0; i < nb_elem; i++)
      {
        double x = coord_g(i,0);
        double y = coord_g(i,1);
        double z = (dim == 3) ? coord_g(i,2) : 0.;
        coord_g(i,0) = x + y*1e-6 + z*1e-12;
        coord_g(i,1) = y + x*1e-6 + z*1e-12;
        if (dim == 3)
          coord_g(i,2) = z + x*1e-6 + y*1e-12;
      }
  }
// Nombre d'elements dans chaque partie
// (initialisation: une partie contenant nb_elem elements)
  ArrOfInt nb_elem_part(1);
  nb_elem_part= nb_elem;
// Dans l'ordre croissant des parties, liste des elements
// contenus dans la partie
// (exemple:
// de 0..nb_elem_part[0]-1                (elements de la partie 0)
// de nb_elem_part[0]..nb_elem_part[0]+nb_elem_part[1]-1 (partie 1)
// Initialisation: une seule grosse partie, tous les elements
  ArrOfInt listes_elem(nb_elem);
  for (int i = 0; i < nb_elem; i++)
    listes_elem[i] = i;
  ArrOfInt new_nb_elem_part;
  new_nb_elem_part.set_smart_resize(1);
// Algorithme: on cree nb_tranches[0] tranches dans la direction x,
// chaque tranche compte le meme nombre d'elements du domaine.
// Puis on prend chacune de ces tranches et on la decoupe en nb_tranches[1]
// parties dans la direction y, elles aussi equilibrees.
// Enfin, on prend chacune des parties obtenues et on la coupe en nb_tranches[2]
// parties dans la direction z.
// Attention: si le domaine n'est pas un parallelipipede, le decoupage
// n'est pas forcement cartesien:
// ------------------
// |       |        |
// |-------|        |
// |       |--------| <- les coins des tranches ne coincident pas forcement
// ------------------
  for (int direction = 0; direction < dim; direction++)
    {
// Nombre de tranches a creer dans cette direction
      const int nb_tranches = nb_tranches_[direction];
      int index_debut_partie = 0;
      new_nb_elem_part.resize_array(0);
      const int nb_parts = nb_elem_part.size_array();
      Cerr << "The mesh contains " << nb_parts << " parts. ";
      Cerr << "Splitting in the direction " << direction << finl;
// Boucle sur les parties deja creees. On divise chaque partie
// en nb_tranches sous-parties:
      for (int part = 0; part < nb_parts; part++)
        {
          Cerr << " Splitting of subpart " << part << finl;
// Extraction de la liste des elements de cette partie:
// on fait pointer le tableau index vers une sous-partie de listes_elem
          const int nb_elem_partie = nb_elem_part[part];
          assert(index_debut_partie >= 0 && index_debut_partie + nb_elem_partie <= nb_elem);
          index.ref_data(listes_elem.addr()+index_debut_partie, nb_elem_partie);
// Tri des elements de cette partie dans l'ordre croissant
// de la coordonnee (index pointe sur une partie de liste_elem, on trie
// donc en realite une partie du tableau liste_elem)
          trier_index_colonne_i(coord_g, index, direction);
// Si cette direction est periodique, permutation circulaire de
// nb_elem_partie/(nb_tranches*2) elements pour que les elements de l'extremite
// se retrouvent sur la meme partie que ceux de l'extremite opposee
          if (directions_perio[direction])
            {
              ArrOfInt copie(nb_elem_partie);
              copie.inject_array(index);
              int j = nb_elem_partie/(nb_tranches*2);
              for (int i = 0; i < nb_elem_partie; i++)
                {
                  index[j++] = copie[i];
                  if (j >= nb_elem_partie)
                    j = 0;
                }
            }
// Construction d'une partition en nb_tranches parties, par
// ordre croissant des coordonnees
          {
            int n = 0;
            for (int i = 0; i < nb_tranches; i++)
              {
// const int new_n = nb_elem_partie * (i+1) / nb_tranches;
// Rewritten cause nb_elem_partie * (i+1) > 2^31 for big meshes
                const int new_n = (int) ((double)nb_elem_partie * (i+1) / nb_tranches);
                new_nb_elem_part.append_array(new_n - n);
                n = new_n;
              }
          }
          index_debut_partie += nb_elem_partie;
        }
      nb_elem_part = new_nb_elem_part;
    }
// Partition initiale du domaine: au depart tout dans 0
  elem_part.resize(nb_elem);
  elem_part = 0;
// Construction de elem_part
  const int nb_parts = nb_elem_part.size_array();
  int index_fin = 0;
  int i = 0;
  for (int part = 0; part < nb_parts; part++)
    {
      index_fin += nb_elem_part[part];
      for (; i < index_fin; i++)
        {
          const int elem = listes_elem[i];
          elem_part[elem] = part;
        }
    }
  if (liste_bords_periodiques_.size() > 0)
    corriger_bords_avec_liste(dom, liste_bords_periodiques_, 0, elem_part);
  Cerr << "Correction elem0 on processor 0" << finl;
  corriger_elem0_sur_proc0(elem_part);
}
References TRUSTArray< _TYPE_ >::addr(), TRUSTArray< _TYPE_ >::append_array(), Zone::calculer_centres_gravite(), Cerr, chercher_direction_perio(), Partitionneur_base::corriger_bords_avec_liste(), Partitionneur_base::corriger_elem0_sur_proc0(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, finl, TRUSTArray< _TYPE_ >::inject_array(), Partitionneur_base::liste_bords_periodiques_, Zone::nb_elem(), nb_tranches_, O_U_Ptr::non_nul(), TRUSTArray< _TYPE_ >::ref_data(), ref_domaine_, TRUSTVect< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::set_smart_resize(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), trier_index_colonne_i(), Ref_Domaine::valeur(), and Domaine::zone().
cree_instance()
Objet_U * Partitionneur_Tranche::cree_instance () static
Definition at line 22 of file Partitionneur_Tranche.cpp.
duplique()
int Partitionneur_Tranche::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file Partitionneur_Tranche.cpp.
get_info()
const Type_info * Partitionneur_Tranche::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 22 of file Partitionneur_Tranche.cpp.
info()
const Type_info * Partitionneur_Tranche::info () static
Definition at line 22 of file Partitionneur_Tranche.cpp.
initialiser()
void Partitionneur_Tranche::initialiser (const ArrOfInt & nb_tranches)
Deuxieme etape d'initialisation: on definit le nombre de tranches.
(on peut utiliser readOn a la place).
Definition at line 72 of file Partitionneur_Tranche.cpp.
{
  assert(ref_domaine_.non_nul());
  assert(nb_tranches.size_array() == nb_tranches_.size_array());
  assert(min_array(nb_tranches) > 0);
  nb_tranches_ = nb_tranches;
}
References min_array(), nb_tranches_, O_U_Ptr::non_nul(), ref_domaine_, and TRUSTArray< _TYPE_ >::size_array().
printOn()
Sortie & Partitionneur_Tranche::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 48 of file Partitionneur_Tranche.cpp.
{
  Cerr << "Partitionneur_Tranche::printOn invalid\n" << finl;
  exit();
  return os;
}
References Cerr, Process::exit(), and finl.
readOn()
Entree & Partitionneur_Tranche::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 30 of file Partitionneur_Tranche.cpp.
{
  if (! ref_domaine_.non_nul())
    {
      Cerr << " Error: the domain has not been associated" << finl;
      exit();
    }
  Partitionneur_base::readOn(is);
  if (min_array(nb_tranches_)<1)
    {
      Cerr << "Error for the cutting domain tool (Tranche) specifications : " <<finl;
      Cerr<< " the number of slice must be greater than 0 for each direction. " << finl;
      exit();
    }
  return is;
}
References Cerr, Process::exit(), finl, min_array(), nb_tranches_, O_U_Ptr::non_nul(), Partitionneur_base::readOn(), and ref_domaine_.
self_cast() [1/2]
const Partitionneur_Tranche & Partitionneur_Tranche::self_cast (const Objet_U & r) static
Definition at line 22 of file Partitionneur_Tranche.cpp.
self_cast() [2/2]
Partitionneur_Tranche & Partitionneur_Tranche::self_cast (Objet_U & r) static
Definition at line 22 of file Partitionneur_Tranche.cpp.
set_param()
void Partitionneur_Tranche::set_param (Param & param) override virtual
Implements Partitionneur_base.
Definition at line 55 of file Partitionneur_Tranche.cpp.
{
  param.ajouter_arr_size_predefinie("tranches",&nb_tranches_,Param::REQUIRED);
}
References Param::ajouter_arr_size_predefinie(), nb_tranches_, and Param::REQUIRED.
taille_memoire()
unsigned Partitionneur_Tranche::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file Partitionneur_Tranche.cpp.
Member Data Documentation
info_obj
const Type_info Partitionneur_Tranche::info_obj static
Definition at line 27 of file Partitionneur_Tranche.h.
nb_tranches_
ArrOfInt Partitionneur_Tranche::nb_tranches_ private
Definition at line 40 of file Partitionneur_Tranche.h.
Referenced by associer_domaine(), construire_partition(), initialiser(), readOn(), and set_param().
ref_domaine_
Ref_Domaine Partitionneur_Tranche::ref_domaine_ private
Definition at line 37 of file Partitionneur_Tranche.h.
Referenced by associer_domaine(), construire_partition(), initialiser(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Decoupeur/Partitionneur_Tranche.h
src/Kernel/Geometrie/Decoupeur/Partitionneur_Tranche.cpp