TRUST: Solv_Optimal Class Reference
Solv_Optimal Class Reference
#include <Solv_Optimal.h>
Public Member Functions
Solv_Optimal ()
~Solv_Optimal ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int resoudre_systeme (const Matrice_Base &, const DoubleVect &, DoubleVect &)
int resoudre_systeme (const Matrice_Base &, const DoubleVect &, DoubleVect &, int)
void reinit ()
void prepare_resol (const Matrice_Base &matrice, const DoubleVect &secmem, DoubleVect &solution, int nmax=100)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Solv_Optimal & self_cast (Objet_U &)
static const Solv_Optimal & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
SolveurSys le_solveur_
int n_resol_
int n_reinit_
int freq_recalc_
int fichier_solveur_non_recree_
Nom fichier_solveur_
Detailed Description
Definition at line 30 of file Solv_Optimal.h.
Constructor & Destructor Documentation
Solv_Optimal::Solv_Optimal ()
Definition at line 268 of file Solv_Optimal.cpp.
References fichier_solveur_, fichier_solveur_non_recree_, freq_recalc_, and numero_solv_optimal.
                          :n_resol_(0),n_reinit_(0)
{
  freq_recalc_ = (int)(pow(2.0,(double)((sizeof(True_int)*8)-1))-1);
  freq_recalc_ = 100;
  fichier_solveur_="solveurs_";
  fichier_solveur_+=Nom(numero_solv_optimal);
  fichier_solveur_non_recree_=0;
  numero_solv_optimal++;
}
Solv_Optimal::~Solv_Optimal ()
Definition at line 278 of file Solv_Optimal.cpp.
References Cerr, finl, le_solveur_, and O_U_Ptr::non_nul().
{
  if (le_solveur_.non_nul()) Cerr<<" The solver used by Solv_Optimal was "<<le_solveur_<<finl;
}
Member Function Documentation
Objet_U * Solv_Optimal::cree_instance () [static]
Definition at line 36 of file Solv_Optimal.cpp.
int Solv_Optimal::duplique () const [virtual]
Implements solv_iteratif.
Definition at line 36 of file Solv_Optimal.cpp.
const Type_info * Solv_Optimal::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from solv_iteratif.
Definition at line 36 of file Solv_Optimal.cpp.
const Type_info * Solv_Optimal::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from solv_iteratif.
Definition at line 36 of file Solv_Optimal.cpp.
void Solv_Optimal::prepare_resol (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution, int nmax = 100)
< Matrice constante (on resout 2 fois pour ne retenir que le 2eme temps exempt d'eventuel preconditionnement)
< Matrice non constante (on resout 1 seul fois)
Definition at line 312 of file Solv_Optimal.cpp.
References Cout, fichier_solveur_, fichier_solveur_non_recree_, finl, freq_recalc_, generate_defaut(), Process::je_suis_maitre(), le_solveur_, SolveurSys_base::limpr(), n_reinit_, n_resol_, solv_iteratif::seuil_, and test_solveur().
Referenced by resoudre_systeme().
{
  if (n_resol_==0)
    {
// premiere chose on genere le fichier par defaut, puis on cree le solveur avec le premier du fichier
      if ((!fichier_solveur_non_recree_)&&(je_suis_maitre()))
        {
          SFichier list_solveur(fichier_solveur_);
          generate_defaut(matrice,seuil_,list_solveur,limpr());
        }
      LecFicDiffuse list_solveur2(fichier_solveur_);
      Nom mot;
      list_solveur2>>mot;
      list_solveur2>>le_solveur_;
    }
// OK
  n_resol_++;
  if ((n_resol_>=3)&&((n_resol_-3)%freq_recalc_==0))
    {
      LecFicDiffuse list_solveur(fichier_solveur_);
      int nb_ite;
      if (n_reinit_<2)
        nb_ite=2; //!< Matrice constante (on resout 2 fois pour ne retenir que le 2eme temps exempt d'eventuel preconditionnement)
      else
        nb_ite=1; //!< Matrice non constante (on resout 1 seul fois)
      ArrOfDouble temps(nb_ite);
      int numero_best=test_solveur(le_solveur_,  matrice , secmem , solution  , nmax, temps,list_solveur,seuil_);
      Cout <<"------------------------------------------------"<<finl;
      Cout <<"Best solver : number "<<numero_best<<" "<<le_solveur_<<finl;
      Cout <<"Best CPU time = "<<temps(0)<<finl;
      Cout <<"------------------------------------------------"<<finl;
      if (je_suis_maitre())
        {
          Nom best("best_");
          best+=fichier_solveur_;
          SFichier sf(best);
          sf << le_solveur_ <<finl;
        }
    }
}
Sortie & Solv_Optimal::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from solv_iteratif.
Definition at line 282 of file Solv_Optimal.cpp.
{
  return s;
}
Entree & Solv_Optimal::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
< seuil de resolution
< active impression des solveurs
< pour sauvegarder A,x,b
< frequence pour reevaluer le solveur optimal
< si flag mis alors le fichier n'est pas cree au debut du calcul
Reimplemented from solv_iteratif.
Definition at line 287 of file Solv_Optimal.cpp.
References Param::ajouter(), fichier_solveur_, fichier_solveur_non_recree_, SolveurSys_base::fixer_limpr(), freq_recalc_, Param::REQUIRED, SolveurSys_base::save_matrice_, and solv_iteratif::seuil_.
{
  int impr,quiet;
  Param param((*this).que_suis_je());
  param.ajouter("seuil",&seuil_,Param::REQUIRED); //!< seuil de resolution
  param.ajouter_flag("impr",&impr); //!< active impression des solveurs
  param.ajouter_flag("quiet",&quiet);
  param.ajouter_flag("save_matrice|save_matrix",&save_matrice_); //!< pour sauvegarder A,x,b
  param.ajouter("frequence_recalc",&freq_recalc_); //!< frequence pour reevaluer le solveur optimal
  param.ajouter("nom_fichier_solveur",&fichier_solveur_); //nom du fichier contenant les solveurs testes
  param.ajouter_flag("fichier_solveur_non_recree",&fichier_solveur_non_recree_); //!<  si flag mis alors le fichier n'est pas cree au debut du calcul
  param.lire_avec_accolades_depuis(is);
  fixer_limpr(impr);
  if (quiet)
    fixer_limpr(-1);
  return is;
}
void Solv_Optimal::reinit () [virtual]
Reimplemented from SolveurSys_base.
Definition at line 365 of file Solv_Optimal.cpp.
References le_solveur_, n_reinit_, and O_U_Ptr::non_nul().
{
  n_reinit_++;
  if (le_solveur_.non_nul())
    le_solveur_->reinit();
}
int Solv_Optimal::resoudre_systeme (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution, int nmax) [virtual]
Reimplemented from SolveurSys_base.
Definition at line 358 of file Solv_Optimal.cpp.
References le_solveur_, prepare_resol(), and SolveurSys::resoudre_systeme().
{
  prepare_resol(matrice,secmem,solution, nmax);
  return le_solveur_->resoudre_systeme( matrice, secmem,  solution, nmax );
}
int Solv_Optimal::resoudre_systeme (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution) [virtual]
Implements SolveurSys_base.
Definition at line 353 of file Solv_Optimal.cpp.
References le_solveur_, prepare_resol(), and SolveurSys::resoudre_systeme().
{
  prepare_resol(matrice,secmem,solution,-20);
  return le_solveur_->resoudre_systeme( matrice, secmem,  solution);
}
Solv_Optimal & Solv_Optimal::self_cast (Objet_U & r) [static]
Reimplemented from solv_iteratif.
Definition at line 36 of file Solv_Optimal.cpp.
const Solv_Optimal & Solv_Optimal::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from solv_iteratif.
Definition at line 36 of file Solv_Optimal.cpp.
unsigned Solv_Optimal::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 36 of file Solv_Optimal.cpp.
Member Data Documentation
Nom Solv_Optimal::fichier_solveur_ [protected]
Definition at line 42 of file Solv_Optimal.h.
Referenced by prepare_resol(), readOn(), and Solv_Optimal().
int Solv_Optimal::fichier_solveur_non_recree_ [protected]
Definition at line 41 of file Solv_Optimal.h.
Referenced by prepare_resol(), readOn(), and Solv_Optimal().
int Solv_Optimal::freq_recalc_ [protected]
Definition at line 41 of file Solv_Optimal.h.
Referenced by prepare_resol(), readOn(), and Solv_Optimal().
const Type_info Solv_Optimal::info_obj [static]
Reimplemented from solv_iteratif.
Definition at line 32 of file Solv_Optimal.h.
SolveurSys Solv_Optimal::le_solveur_ [protected]
Definition at line 40 of file Solv_Optimal.h.
Referenced by prepare_resol(), reinit(), resoudre_systeme(), and ~Solv_Optimal().
int Solv_Optimal::n_reinit_ [protected]
Definition at line 41 of file Solv_Optimal.h.
Referenced by prepare_resol(), and reinit().
int Solv_Optimal::n_resol_ [protected]
Definition at line 41 of file Solv_Optimal.h.
Referenced by prepare_resol().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/Solv_Optimal.h
src/Kernel/Math/SolvSys/Solv_Optimal.cpp