TRUST: TRUSTSchema_RK< _ORDRE_ > Class Template Reference
TRUSTSchema_RK< _ORDRE_ > Class Template Reference
#include <TRUSTSchema_RK.h>
Protected Member Functions
void print_warning (const int nw)
Protected Member Functions inherited from Schema_Temps_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Entree & readOn (Entree &) override
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Static Protected Attributes
static constexpr int NW = 100
Private Member Functions
int nb_valeurs_temporelles () const override
int nb_valeurs_futures () const override
double temps_futur (int i) const override
double temps_defaut () const override
void completer () override
int faire_un_pas_de_temps_eqn_base (Equation_base &eq) override
SFINAE :-)
template<Ordre_RK _O_ = _ORDRE_, int NB>
enable_if_t< _O_==Ordre_RK::DEUX_WILLIAMSON, std::array< double, NB > > const get_a ()
template<Ordre_RK _O_ = _ORDRE_, int NB>
enable_if_t< _O_ !=Ordre_RK::DEUX_WILLIAMSON, std::array< double, NB > > const get_a ()
template<Ordre_RK _O_ = _ORDRE_, int NB>
enable_if_t< _O_==Ordre_RK::DEUX_WILLIAMSON, std::array< double, NB > > const get_b ()
template<Ordre_RK _O_ = _ORDRE_, int NB>
enable_if_t< _O_ !=Ordre_RK::DEUX_WILLIAMSON, std::array< double, NB > > const get_b ()
template<Ordre_RK _O_ = _ORDRE_>
enable_if_t< _O_==Ordre_RK::DEUX_WILLIAMSON||_O_==Ordre_RK::TROIS_WILLIAMSON||_O_==Ordre_RK::QUATRE_WILLIAMSON, int > faire_un_pas_de_temps_eqn_base_generique (Equation_base &eq)
template<Ordre_RK _O_ = _ORDRE_, int NB>
enable_if_t< _O_==Ordre_RK::DEUX_CLASSIQUE, std::array< std::array< double, NB >, NB > > const get_butcher_coeff ()
template<Ordre_RK _O_ = _ORDRE_, int NB>
enable_if_t< _O_==Ordre_RK::TROIS_CLASSIQUE, std::array< std::array< double, NB >, NB > > const get_butcher_coeff ()
template<Ordre_RK _O_ = _ORDRE_, int NB>
enable_if_t< _O_==Ordre_RK::QUATRE_CLASSIQUE||_O_==Ordre_RK::QUATRE_CLASSIQUE_3_8, std::array< std::array< double, NB >, NB > > const get_butcher_coeff ()
template<Ordre_RK _O_ = _ORDRE_>
enable_if_t< _O_==Ordre_RK::DEUX_CLASSIQUE||_O_==Ordre_RK::TROIS_CLASSIQUE||_O_==Ordre_RK::QUATRE_CLASSIQUE||_O_==Ordre_RK::QUATRE_CLASSIQUE_3_8, int > faire_un_pas_de_temps_eqn_base_generique (Equation_base &eq)
template<Ordre_RK _O_ = _ORDRE_>
enable_if_t< _O_==Ordre_RK::UN||_O_==Ordre_RK::RATIO_DEUX, int > faire_un_pas_de_temps_eqn_base_generique (Equation_base &eq)
From VTABLE.
Static Private Attributes
static constexpr double SQRT2 = 1.4142135623730950488016887242096980785696718753769480731766797
static constexpr double SQRT2_2 = SQRT2 / 2.
static constexpr ARR2 A2 = { 0.0, SQRT2 - 2. }
static constexpr ARR2 B2 = { SQRT2_2, SQRT2_2 }
static constexpr ARR3 A3 = { 0.0, -5. / 9., -153. / 128. }
static constexpr ARR3 B3 = { 1. / 3., 15. / 16., 8. / 15. }
static constexpr ARR3 A4 = { 0.0, -1. /2. , -2. }
static constexpr ARR3 B4 = { 1. / 2., 1. , 1. / 6. }
static constexpr std::array< ARR1, 1 > BUTCHER_2 = { { { 1. / 2. } } }
static constexpr std::array< ARR2, 2 > BUTCHER_3 = { { { 1. / 2., 0. }, { -1., 2. } } }
static constexpr std::array< ARR3, 3 > BUTCHER_4 = { { { 1. / 2., 0. , 0.}, { 0., 1. / 2., 0.}, { 0. , 0., 1. } } }
static constexpr std::array< ARR3, 3 > BUTCHER_4_3_8 = { { { 1. / 3., 0. , 0.}, { -1. / 3., 1., 0.}, { 1. , -1., 1. } } }
static constexpr std::array< ARR4, 4 > BUTCHER_TAB
Friends
class RK3_FT
pour trio
Additional Inherited Members
Public Member Functions inherited from Schema_Temps_base
~Schema_Temps_base () override
< necessaire pour visual
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void initialize ()
virtual void terminate ()
virtual double computeTimeStep (bool &stop) const
virtual bool initTimeStep (double dt)
virtual void validateTimeStep ()
virtual bool isStationary () const
Retourne 1 si lors du dernier pas de temps, le probleme n'a pas evolue.
virtual void abortTimeStep ()
virtual bool iterateTimeStep (bool &converged)
Calculate the U(n+1) unknown for each equation (if solved) of the problem with the selected time scheme.
int limpr () const
Renvoie 1 s'il y a lieu d'effectuer une impression (cf dt_impr)
Renvoie 0 sinon.
virtual int nb_valeurs_temporelles () const =0
virtual int nb_valeurs_futures () const =0
virtual double temps_futur (int i) const =0
virtual double temps_defaut () const =0
Schema_Temps_base ()
Constructeur par defaut d'un schema en temps.
Initialise differents membres de la classe.
void nommer (const Nom &) override
surcharge Objet_U::nommer(const Nom&)
Donne un nom au shema en temps
const Nom & le_nom () const override
surcharge Objet_U::le_nom()
Renvoie le nom du shema en temps
virtual int faire_un_pas_de_temps_eqn_base (Equation_base &)=0
virtual void set_param (Param &titi)
int sauvegarder (Sortie &) const override
Sauvegarde le temps courant et le nombre de pas de temps
sur un flot de sortie.
int reprendre (Entree &) override
Reprise (lecture) du temps courant et du nombre de pas de
temps effectues a partir d'un flot d'entree.
virtual int mettre_a_jour ()
Mise a jour du temps courant (t+=dt)
et du nombre de pas de temps effectue (nb_pas_dt_++).
virtual void mettre_a_jour_dt (double toto)
virtual void mettre_a_jour_dt_stab ()
double pas_de_temps () const
Renvoie le pas de temps (delta_t) courant.
const DoubleTab & pas_de_temps_locaux () const
virtual bool corriger_dt_calcule (double &dt) const
Corrige le pas de temps calcule que l'on passe en parametre
et verifie qu'il n'est pas "trop" petit (< dt-min_).
La correction est la suivante:
delta_t = min((facteur de securite * dt_calc), dt_max)
Et on verifie que delta_t est "suffisamment" plus grand que dt_min_.
virtual void imprimer (Sortie &os) const
Imprime le pas de temps sur un flot de sortie s'il y a lieu.
virtual int impr (Sortie &os) const
Impression du numero du pas de temps, la valeur du pas de temps.
et du temps courant.
void imprimer (Sortie &os, Probleme_base &pb) const
Imprime le pas de temps sur un flot de sortie s'il y a lieu.
void imprimer (Sortie &os, const Probleme_base &pb) const
virtual int impr (Sortie &os, Probleme_base &pb) const
Impression du numero du pas de temps, la valeur du pas de temps.
et du temps courant.
virtual int impr (Sortie &os, const Probleme_base &pb) const
void imprimer_temps_courant (SFichier &) const
double pas_temps_min () const
Renvoie le pas de temps minimum.
(version const)
double & pas_temps_min ()
Renvoie une reference sur le pas de temps minimum.
double pas_temps_max () const
Renvoie le pas de temps maximum.
(version const)
double & pas_temps_max ()
Renvoie une reference sur le pas de temps maximum.
int nb_impr () const
Renvoie le nombre d'impressions effectuees.
double temps_courant () const
Renvoie le temps courant.
double temps_precedent () const
Renvoie le temps courant.
double temps_calcul () const
Renvoie le temps de calcul ecoule i.e. (temps courant - temps initial).
virtual void changer_temps_courant (const double)
Change le temps courant.
void update_critere_statio (const DoubleTab &tab_critere, Equation_base &equation)
//Actualisation de stationnaire_atteint_ et residu_
(critere residu_<seuil_statio_)
double facteur_securite_pas () const
Renvoie le facteur de securite ou multiplicateur de delta_t.
Ce facteur est utilise lors de la correction/verification du
pas de temps. Voir Schema_Temps_base::corriger_dt_calcule(double&)
(version const)
double & facteur_securite_pas ()
Renvoie une reference sur le facteur de securite ou multiplicateur de delta_t.
Ce facteur est utilise lors de la correction/verification du
pas de temps. Voir Schema_Temps_base::corriger_dt_calcule(double&)
virtual int stop () const
Renvoie 1 si il y lieu de stopper le calcul pour differente raisons:
- le temps final est atteint
- le nombre de pas de temps maximum est depasse
- l'etat stationnaire est atteint
- indicateur d'arret fichier (voir int Schema_Temps_base::stop_lu())
Renvoie 0 sinon.
int lsauv () const
int temps_final_atteint () const
Renvoie 1 si le temps final est atteint (ou depasse).
Renvoie 1 si temps_courant_ >= tmax
Renvoie 0 sinon.
int nb_pas_dt_max_atteint () const
Renvoie 1 si (le nombre de pas de temps >= nombre de pas de temps maximum).
Renvoie 0 sinon.
int temps_cpu_max_atteint () const
int stationnaire_atteint () const
int stop_lu () const
Renvoie 1 si le fichier (d'extension) .stop contient un 1
Renvoie 0 sinon.
int diffusion_implicite () const
Renvoie 1 si le schema en temps a ete lu diffusion_implicite.
double seuil_diffusion_implicite () const
int impr_diffusion_implicite () const
Seuil pour implicitation de la diffusion par GC.
int impr_extremums () const
Impression ou non de GC implicitation.
int niter_max_diffusion_implicite () const
int no_conv_subiteration_diffusion_implicite () const
Iterations maximale pour GC implicitation.
int no_error_if_not_converged_diffusion_implicite () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_nb_pas_dt_max (Entree &)
virtual Entree & lire_periode_sauvegarde_securite_en_heures (Entree &)
virtual Entree & lire_temps_cpu_max (Entree &)
virtual void completer ()=0
double temps_init () const
Renvoie le temps initial.
double temps_max () const
Renvoie une reference sur le temps maximum.
double temps_sauv () const
Renvoie une reference sur le temps de sauvegarde.
double temps_impr () const
Renvoie une reference sur le temps d'impression.
int precision_impr () const
int wcol () const
int gnuplot_header () const
double seuil_statio () const
Renvoie une reference sur le seuil stationnaire.
int nb_pas_dt_max () const
Renvoie une reference sur le nombre de pas maxi.
int nb_pas_dt () const
Renvoie le nombre de pas de temps effectues.
double mode_dt_start () const
int indice_tps_final_atteint () const
int indice_nb_pas_dt_max_atteint () const
int lu () const
int file_allocation () const
double & set_temps_init ()
double & set_temps_max ()
double & set_temps_courant ()
double & set_temps_precedent ()
int & set_nb_pas_dt ()
int & set_nb_pas_dt_max ()
double & set_dt_min ()
double & set_dt_max ()
double & set_dt_sauv ()
double & set_dt_impr ()
int & set_precision_impr ()
double & set_dt ()
double & set_facsec ()
double & set_seuil_statio ()
int & set_stationnaire_atteint ()
void set_stationnaires_atteints (bool flag)
int & set_diffusion_implicite ()
double & set_seuil_diffusion_implicite ()
int & set_niter_max_diffusion_implicite ()
double & set_mode_dt_start ()
int & set_indice_tps_final_atteint ()
int & set_indice_nb_pas_dt_max_atteint ()
int & set_lu ()
const double & residu () const
double & residu ()
int & schema_impr ()
const int & schema_impr () const
virtual void associer_pb (const Probleme_base &)
Probleme_base & pb_base ()
const Probleme_base & pb_base () const
virtual void modifier_second_membre (const Equation_base &eqn, DoubleTab &secmem)
virtual void ajouter_inertie (Matrice_Base &mat_morse, DoubleTab &secmem, const Equation_base &eqn) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const Equation_base &eqn, const tabs_t &semi_impl={}) const
int disable_progress () const
int disable_dt_ev () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions inherited from Schema_Temps_base
static const Type_info * info ()
static Schema_Temps_base & self_cast (Objet_U &)
static const Schema_Temps_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes inherited from Schema_Temps_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Attributes inherited from Schema_Temps_base
Ref_Probleme_base mon_probleme
Nom nom_
double dt_
Pas de temps de calcul.
DoubleTab dt_locaux_
Local time steps: Vector of size nb faces of the mesh.
double temps_courant_
double temps_precedent_
double dt_failed_
double dt_gf_
double tinit_
double tmax_
double tcpumax_
int nb_pas_dt_
int nb_pas_dt_max_
int nb_impr_
double dt_min_
Pas de temps min fixe par l'utilisateur.
double dt_max_
Pas de temps max fixe par l'utilisateur.
Nom dt_max_str_
Parser_U dt_max_fn_
double dt_stab_
Pas de temps de stabilite.
double facsec_
double seuil_statio_
int seuil_statio_relatif_deconseille_
Drapeau pour specifier si seuil_statio_ est une valeur absolue (defaut) ou relative.
double dt_sauv_
double limite_cpu_sans_sauvegarde_
double periode_cpu_sans_sauvegarde_
double temps_cpu_ecoule_
double dt_impr_
Pas de temps d'impression.
int precision_impr_
Nombre de chiffres significatifs impression.
double mode_dt_start_
mode calcul du pas de temps de depart
double residu_
Residu.
double residu_old_slope_
double cumul_slope_
int gnuplot_header_
int ind_tps_final_atteint
int ind_nb_pas_dt_max_atteint
int ind_temps_cpu_max_atteint
int lu_
int ind_diff_impl_
double seuil_diff_impl_
int impr_diff_impl_
int impr_extremums_
int niter_max_diff_impl_
int no_conv_subiteration_diff_impl_
int no_error_if_not_converged_diff_impl_
int schema_impr_
1 si le schema a le droit d'imprimer dans le .out et dt_ev
int file_allocation_
1 = allocation espace disque (par defaut), 0 sinon
int max_length_cl_
Detailed Description
template<Ordre_RK _ORDRE_>
class TRUSTSchema_RK< _ORDRE_ >
Definition at line 33 of file TRUSTSchema_RK.h.
Member Function Documentation
completer()
template<Ordre_RK _ORDRE_> void TRUSTSchema_RK< _ORDRE_ >::completer (void) inline override private virtual
Implements Schema_Temps_base.
Definition at line 52 of file TRUSTSchema_RK.h.
{ /* Do nothing */ }
faire_un_pas_de_temps_eqn_base()
template<Ordre_RK _ORDRE_> int TRUSTSchema_RK< _ORDRE_ >::faire_un_pas_de_temps_eqn_base (Equation_base & eq) inline override private virtual
SFINAE :-)
Implements Schema_Temps_base.
Definition at line 55 of file TRUSTSchema_RK.h.
faire_un_pas_de_temps_eqn_base_generique() [1/3]
template<Ordre_RK _ORDRE_> template<Ordre_RK _O_> enable_if_t< _O_==Ordre_RK::DEUX_WILLIAMSON||_O_==Ordre_RK::TROIS_WILLIAMSON||_O_==Ordre_RK::QUATRE_WILLIAMSON, int > TRUSTSchema_RK< _ORDRE_ >::faire_un_pas_de_temps_eqn_base_generique (Equation_base & eq) private
Definition at line 21 of file TRUSTSchema_RK.tpp.
{
  static constexpr int NB_PTS = (_ORDRE_ == Ordre_RK::DEUX_WILLIAMSON) ? 2 : 3;
// Warning sur les 100 premiers pas de temps si facsec est egal a 1 pour faire reflechir l'utilisateur
  if (nb_pas_dt() >= 0 && nb_pas_dt() <= NW && facsec_ == 1) print_warning(NW);
  DoubleTab& xi = eqn.inconnue().valeurs(), &xip1 = eqn.inconnue().futur();
  DoubleTab present(xi), qi(xi);
  for (int i = 0; i < NB_PTS; i++)
    {
// on fait ca : q_i = a_{i-1} * q_{i-1} + dt * f(x_{i-1})
      qi *= get_a<_ORDRE_,NB_PTS>()[i];
      qi.ajoute(dt_, eqn.derivee_en_temps_inco(xip1));
// on fait ca : x_i = x_{i-1} + b_i * q_i
      xi.ajoute(get_b<_ORDRE_,NB_PTS>()[i], qi);
    }
  xip1 = xi;
  xi -= present;
  xi /= dt_;
  update_critere_statio(xi, eqn);
// Update boundary condition on futur:
  eqn.zone_Cl_dis().imposer_cond_lim(eqn.inconnue(), temps_courant() + pas_de_temps());
  xip1.echange_espace_virtuel();
// xi = x0;
  xi = present;
  return 1;
}
References TRUSTVect< _TYPE_ >::ajoute(), Equation_base::derivee_en_temps_inco(), DEUX_WILLIAMSON, Champ_Inc::futur(), Zone_Cl_dis::imposer_cond_lim(), Equation_base::inconnue(), Champ_Inc::valeurs(), and Equation_base::zone_Cl_dis().
faire_un_pas_de_temps_eqn_base_generique() [2/3]
template<Ordre_RK _ORDRE_> template<Ordre_RK _O_> enable_if_t< _O_==Ordre_RK::DEUX_CLASSIQUE||_O_==Ordre_RK::TROIS_CLASSIQUE||_O_==Ordre_RK::QUATRE_CLASSIQUE||_O_==Ordre_RK::QUATRE_CLASSIQUE_3_8, int > TRUSTSchema_RK< _ORDRE_ >::faire_un_pas_de_temps_eqn_base_generique (Equation_base & eq) private
< just for initializing the array structure ...
< sauv = y0
< ki[0] = f(y0)
< ki[0] = h * f(y0)
< ATTENTION : ne touche pas !
< back to y0
< Et ouiiiiiiii :-)
< futur = y1 = y0
< back to y0
Definition at line 58 of file TRUSTSchema_RK.tpp.
{
// Warning sur les 100 premiers pas de temps si facsec est egal a 1 pour faire reflechir l'utilisateur
  if (nb_pas_dt() >= 0 && nb_pas_dt() <= NW && facsec_ == 1) print_warning(NW);
  static constexpr bool IS_DEUX = (_O_ == Ordre_RK::DEUX_CLASSIQUE) , IS_TROIS = (_O_ == Ordre_RK::TROIS_CLASSIQUE), IS_QUATRE = (_O_ == Ordre_RK::QUATRE_CLASSIQUE);
  static constexpr int NB_PTS = IS_DEUX ? 2 : ( IS_TROIS ? 3 : 4);
  static constexpr int NB_BUTCHER = IS_DEUX ? 0 : ( IS_TROIS ? 1 : ( IS_QUATRE ? 2 : 3 ));
  DoubleTab& present = eqn.inconnue().valeurs(), &futur = eqn.inconnue().futur();
  DoubleTabs ki(NB_PTS); //!< just for initializing the array structure ...
  for (int i = 0; i < NB_PTS; i++) ki[i] = present;
  DoubleTrav sauv(present);
  sauv = present; //!< sauv = y0
// Step 1
  eqn.derivee_en_temps_inco(ki[0]); //!< ki[0] = f(y0)
  ki[0] *= dt_; //!< ki[0] = h * f(y0)
  for (int step = 1; step < NB_PTS; step++ ) //!< ATTENTION : ne touche pas !
    {
      present = sauv; //!< back to y0
      for (int i = 0; i < step; i++) present.ajoute(get_butcher_coeff<_ORDRE_,NB_PTS-1>().at(step-1).at(i), ki[i]); //!< Et ouiiiiiiii :-)
      eqn.derivee_en_temps_inco(ki[step]);
      ki[step] *= dt_;
    }
  futur = sauv; //!< futur = y1 = y0
  for (int i = 0; i < NB_PTS; i++) futur.ajoute(BUTCHER_TAB.at(NB_BUTCHER).at(i), ki[i]);
  update_critere_statio(futur, eqn);
// Update boundary condition on futur:
  eqn.zone_Cl_dis().imposer_cond_lim(eqn.inconnue(), temps_courant() + pas_de_temps());
  futur.echange_espace_virtuel();
  present = sauv; //!< back to y0
  return 1;
}
References TRUSTVect< _TYPE_ >::ajoute(), Equation_base::derivee_en_temps_inco(), DEUX_CLASSIQUE, Champ_Inc::futur(), Zone_Cl_dis::imposer_cond_lim(), Equation_base::inconnue(), QUATRE_CLASSIQUE, TROIS_CLASSIQUE, Champ_Inc::valeurs(), and Equation_base::zone_Cl_dis().
faire_un_pas_de_temps_eqn_base_generique() [3/3]
template<Ordre_RK _ORDRE_> template<Ordre_RK _O_ = _ORDRE_> enable_if_t< _O_==Ordre_RK::UN||_O_==Ordre_RK::RATIO_DEUX, int > TRUSTSchema_RK< _ORDRE_ >::faire_un_pas_de_temps_eqn_base_generique (Equation_base & eq) inline private
From VTABLE.
Definition at line 132 of file TRUSTSchema_RK.h.
get_a() [1/2]
template<Ordre_RK _ORDRE_> template<Ordre_RK _O_ = _ORDRE_, int NB> enable_if_t< _O_==Ordre_RK::DEUX_WILLIAMSON, std::array< double, NB > > const TRUSTSchema_RK< _ORDRE_ >::get_a () inline private
Definition at line 96 of file TRUSTSchema_RK.h.
{ return A2; }
References TRUSTSchema_RK< _ORDRE_ >::A2.
get_a() [2/2]
template<Ordre_RK _ORDRE_> template<Ordre_RK _O_ = _ORDRE_, int NB> enable_if_t< _O_ !=Ordre_RK::DEUX_WILLIAMSON, std::array< double, NB > > const TRUSTSchema_RK< _ORDRE_ >::get_a () inline private
Definition at line 100 of file TRUSTSchema_RK.h.
{ return _ORDRE_ == Ordre_RK::TROIS_WILLIAMSON ? A3 : A4; }
References TRUSTSchema_RK< _ORDRE_ >::A3, TRUSTSchema_RK< _ORDRE_ >::A4, and TROIS_WILLIAMSON.
get_b() [1/2]
template<Ordre_RK _ORDRE_> template<Ordre_RK _O_ = _ORDRE_, int NB> enable_if_t< _O_==Ordre_RK::DEUX_WILLIAMSON, std::array< double, NB > > const TRUSTSchema_RK< _ORDRE_ >::get_b () inline private
Definition at line 104 of file TRUSTSchema_RK.h.
{ return B2; }
References TRUSTSchema_RK< _ORDRE_ >::B2.
get_b() [2/2]
template<Ordre_RK _ORDRE_> template<Ordre_RK _O_ = _ORDRE_, int NB> enable_if_t< _O_ !=Ordre_RK::DEUX_WILLIAMSON, std::array< double, NB > > const TRUSTSchema_RK< _ORDRE_ >::get_b () inline private
Definition at line 108 of file TRUSTSchema_RK.h.
{ return _ORDRE_ == Ordre_RK::TROIS_WILLIAMSON ? B3 : B4; }
References TRUSTSchema_RK< _ORDRE_ >::B3, TRUSTSchema_RK< _ORDRE_ >::B4, and TROIS_WILLIAMSON.
get_butcher_coeff() [1/3]
template<Ordre_RK _ORDRE_> template<Ordre_RK _O_ = _ORDRE_, int NB> enable_if_t< _O_==Ordre_RK::DEUX_CLASSIQUE, std::array< std::array< double, NB >, NB > > const TRUSTSchema_RK< _ORDRE_ >::get_butcher_coeff () inline private
Definition at line 116 of file TRUSTSchema_RK.h.
{ return BUTCHER_2; }
References TRUSTSchema_RK< _ORDRE_ >::BUTCHER_2.
get_butcher_coeff() [2/3]
template<Ordre_RK _ORDRE_> template<Ordre_RK _O_ = _ORDRE_, int NB> enable_if_t< _O_==Ordre_RK::TROIS_CLASSIQUE, std::array< std::array< double, NB >, NB > > const TRUSTSchema_RK< _ORDRE_ >::get_butcher_coeff () inline private
Definition at line 120 of file TRUSTSchema_RK.h.
{ return BUTCHER_3; }
References TRUSTSchema_RK< _ORDRE_ >::BUTCHER_3.
get_butcher_coeff() [3/3]
template<Ordre_RK _ORDRE_> template<Ordre_RK _O_ = _ORDRE_, int NB> enable_if_t< _O_==Ordre_RK::QUATRE_CLASSIQUE||_O_==Ordre_RK::QUATRE_CLASSIQUE_3_8, std::array< std::array< double, NB >, NB > > const TRUSTSchema_RK< _ORDRE_ >::get_butcher_coeff () inline private
Definition at line 124 of file TRUSTSchema_RK.h.
{ return _O_ == Ordre_RK::QUATRE_CLASSIQUE ? BUTCHER_4 : BUTCHER_4_3_8; }
References TRUSTSchema_RK< _ORDRE_ >::BUTCHER_4, TRUSTSchema_RK< _ORDRE_ >::BUTCHER_4_3_8, and QUATRE_CLASSIQUE.
nb_valeurs_futures()
template<Ordre_RK _ORDRE_> int TRUSTSchema_RK< _ORDRE_ >::nb_valeurs_futures () const inline override private virtual
Implements Schema_Temps_base.
Definition at line 39 of file TRUSTSchema_RK.h.
{ return 1 ; }
nb_valeurs_temporelles()
template<Ordre_RK _ORDRE_> int TRUSTSchema_RK< _ORDRE_ >::nb_valeurs_temporelles () const inline override private virtual
Implements Schema_Temps_base.
Definition at line 36 of file TRUSTSchema_RK.h.
{ return 2 ; }
print_warning()
template<Ordre_RK _ORDRE_> void TRUSTSchema_RK< _ORDRE_ >::print_warning (const int nw) inline protected
Definition at line 60 of file TRUSTSchema_RK.h.
  {
    Cerr << finl << "**** Advice (printed only on the first " << nw << " time steps) ****" << finl;
    Cerr << "You are using Runge Kutta schema ! If you wish to increase the time step, try facsec between 1 and 2/3/4 (depends on the order of the scheme)." << finl;
  }
References Cerr, and finl.
temps_defaut()
template<Ordre_RK _ORDRE_> double TRUSTSchema_RK< _ORDRE_ >::temps_defaut () const inline override private virtual
Implements Schema_Temps_base.
Definition at line 49 of file TRUSTSchema_RK.h.
{ return temps_courant() + pas_de_temps(); }
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
temps_futur()
template<Ordre_RK _ORDRE_> double TRUSTSchema_RK< _ORDRE_ >::temps_futur (int i) const inline override private virtual
Implements Schema_Temps_base.
Definition at line 42 of file TRUSTSchema_RK.h.
  {
    assert(i == 1);
    return temps_courant() + pas_de_temps();
  }
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
Friends And Related Function Documentation
RK3_FT
template<Ordre_RK _ORDRE_> friend class RK3_FT friend
pour trio
Definition at line 54 of file TRUSTSchema_RK.h.
Member Data Documentation
A2
template<Ordre_RK _ORDRE_> constexpr ARR2 TRUSTSchema_RK< _ORDRE_ >::A2 = { 0.0, SQRT2 - 2. } static constexpr private
Definition at line 70 of file TRUSTSchema_RK.h.
Referenced by TRUSTSchema_RK< _ORDRE_ >::get_a().
A3
template<Ordre_RK _ORDRE_> constexpr ARR3 TRUSTSchema_RK< _ORDRE_ >::A3 = { 0.0, -5. / 9., -153. / 128. } static constexpr private
Definition at line 73 of file TRUSTSchema_RK.h.
Referenced by TRUSTSchema_RK< _ORDRE_ >::get_a().
A4
template<Ordre_RK _ORDRE_> constexpr ARR3 TRUSTSchema_RK< _ORDRE_ >::A4 = { 0.0, -1. /2. , -2. } static constexpr private
Definition at line 76 of file TRUSTSchema_RK.h.
Referenced by TRUSTSchema_RK< _ORDRE_ >::get_a().
B2
template<Ordre_RK _ORDRE_> constexpr ARR2 TRUSTSchema_RK< _ORDRE_ >::B2 = { SQRT2_2, SQRT2_2 } static constexpr private
Definition at line 71 of file TRUSTSchema_RK.h.
Referenced by TRUSTSchema_RK< _ORDRE_ >::get_b().
B3
template<Ordre_RK _ORDRE_> constexpr ARR3 TRUSTSchema_RK< _ORDRE_ >::B3 = { 1. / 3., 15. / 16., 8. / 15. } static constexpr private
Definition at line 74 of file TRUSTSchema_RK.h.
Referenced by TRUSTSchema_RK< _ORDRE_ >::get_b().
B4
template<Ordre_RK _ORDRE_> constexpr ARR3 TRUSTSchema_RK< _ORDRE_ >::B4 = { 1. / 2., 1. , 1. / 6. } static constexpr private
Definition at line 77 of file TRUSTSchema_RK.h.
Referenced by TRUSTSchema_RK< _ORDRE_ >::get_b().
BUTCHER_2
template<Ordre_RK _ORDRE_> constexpr std::array< ARR1, 1 > TRUSTSchema_RK< _ORDRE_ >::BUTCHER_2 = { { { 1. / 2. } } } static constexpr private
Definition at line 80 of file TRUSTSchema_RK.h.
Referenced by TRUSTSchema_RK< _ORDRE_ >::get_butcher_coeff().
BUTCHER_3
template<Ordre_RK _ORDRE_> constexpr std::array< ARR2, 2 > TRUSTSchema_RK< _ORDRE_ >::BUTCHER_3 = { { { 1. / 2., 0. }, { -1., 2. } } } static constexpr private
Definition at line 81 of file TRUSTSchema_RK.h.
Referenced by TRUSTSchema_RK< _ORDRE_ >::get_butcher_coeff().
BUTCHER_4
template<Ordre_RK _ORDRE_> constexpr std::array< ARR3, 3 > TRUSTSchema_RK< _ORDRE_ >::BUTCHER_4 = { { { 1. / 2., 0. , 0.}, { 0., 1. / 2., 0.}, { 0. , 0., 1. } } } static constexpr private
Definition at line 82 of file TRUSTSchema_RK.h.
Referenced by TRUSTSchema_RK< _ORDRE_ >::get_butcher_coeff().
BUTCHER_4_3_8
template<Ordre_RK _ORDRE_> constexpr std::array< ARR3, 3 > TRUSTSchema_RK< _ORDRE_ >::BUTCHER_4_3_8 = { { { 1. / 3., 0. , 0.}, { -1. / 3., 1., 0.}, { 1. , -1., 1. } } } static constexpr private
Definition at line 83 of file TRUSTSchema_RK.h.
Referenced by TRUSTSchema_RK< _ORDRE_ >::get_butcher_coeff().
BUTCHER_TAB
template<Ordre_RK _ORDRE_> constexpr std::array< ARR4, 4 > TRUSTSchema_RK< _ORDRE_ >::BUTCHER_TAB static constexpr private
Initial value:
= { {
      { 0., 1., 0., 0. },
      { 1. / 6., 2. / 3., 1. / 6., 0. },
      { 1. / 6., 1. / 3., 1. / 3., 1. / 6. },
      { 1. / 8., 3. / 8., 3. / 8., 1. / 8. }
    }
  }
Definition at line 85 of file TRUSTSchema_RK.h.
NW
template<Ordre_RK _ORDRE_> constexpr int TRUSTSchema_RK< _ORDRE_ >::NW = 100 static constexpr protected
Definition at line 58 of file TRUSTSchema_RK.h.
SQRT2
template<Ordre_RK _ORDRE_> constexpr double TRUSTSchema_RK< _ORDRE_ >::SQRT2 = 1.4142135623730950488016887242096980785696718753769480731766797 static constexpr private
Definition at line 67 of file TRUSTSchema_RK.h.
SQRT2_2
template<Ordre_RK _ORDRE_> constexpr double TRUSTSchema_RK< _ORDRE_ >::SQRT2_2 = SQRT2 / 2. static private
Definition at line 67 of file TRUSTSchema_RK.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/TRUSTSchema_RK.h
src/Kernel/Framework/TRUSTSchema_RK.tpp