TRUST: Masse_CoviMAC_Face Class Reference
Masse_CoviMAC_Face Class Reference
#include <Masse_CoviMAC_Face.h>
Public Member Functions
Masse_CoviMAC_Face ()
~Masse_CoviMAC_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &)
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
DoubleTab & appliquer_impl (DoubleTab &) const
virtual DoubleTab & corriger_solution (DoubleTab &x, const DoubleTab &y, int incr=0) const
int has_interface_blocs () const
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, double dt, const tabs_t &semi_impl, int resoudre_en_increments) const
void check_multiphase_compatibility () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Masse_CoviMAC_Face & self_cast (Objet_U &)
static const Masse_CoviMAC_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Private Attributes
Ref_Zone_CoviMAC la_zone_CoviMAC
Ref_Zone_Cl_CoviMAC la_zone_Cl_CoviMAC
Detailed Description
Definition at line 38 of file Masse_CoviMAC_Face.h.
Constructor & Destructor Documentation
Masse_CoviMAC_Face::Masse_CoviMAC_Face ()
Definition at line 45 of file Masse_CoviMAC_Face.cpp.
Masse_CoviMAC_Face::~Masse_CoviMAC_Face ()
Definition at line 45 of file Masse_CoviMAC_Face.cpp.
Member Function Documentation
void Masse_CoviMAC_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, double dt, const tabs_t & semi_impl, int resoudre_en_increments) const [virtual]
Reimplemented from Solveur_Masse_base.
Definition at line 119 of file Masse_CoviMAC_Face.cpp.
References Masse_ajoutee_base::ajouter(), Equation_base::champ_conserve(), Objet_U::dimension, Pb_Multiphase::eq_masse, MorEqn::equation(), Zone_CoviMAC::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Pb_Multiphase::get_correlation(), Nom::getString(), Pb_Multiphase::has_correlation(), Masse_Multiphase::inconnue(), Equation_base::inconnue(), la_zone_Cl_CoviMAC, la_zone_CoviMAC, O_U_Ptr::le_nom(), DoubleVect::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Champ_Inc_base::passe(), Champ_Proto::passe(), Champ_Inc::passe(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, sub_type, Deriv_Correlation_base::valeur(), valeur(), Champ_Inc::valeurs(), Zone_VF::volumes(), and Zone_VF::volumes_entrelaces().
{
  const DoubleTab& inco = equation().inconnue().valeurs(), &passe = equation().inconnue().passe();
  Matrice_Morse *mat = matrices[equation().inconnue().le_nom().getString()]; //facultatif
  const Zone_CoviMAC& zone = la_zone_CoviMAC;
  const Conds_lim& cls = la_zone_Cl_CoviMAC->les_conditions_limites();
  const IntTab& f_e = zone.face_voisins(), &fcl = ref_cast(Champ_Face_CoviMAC, equation().inconnue().valeur()).fcl();
  const DoubleVect& pf = zone.porosite_face(), &pe = zone.porosite_elem(), &vf = zone.volumes_entrelaces(), &ve = zone.volumes(), &fs = zone.face_surfaces();
  const Pb_Multiphase *pbm = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()) : NULL;
  const DoubleTab& nf = zone.face_normales(), &rho = equation().milieu().masse_volumique().passe(),
                   *alpha = pbm ? &pbm->eq_masse.inconnue().passe() : NULL, *a_r = pbm ? &pbm->eq_masse.champ_conserve().passe() : NULL,
                    &mu_f = ref_cast(Op_Grad_CoviMAC_Face, ref_cast(Navier_Stokes_std, equation()).operateur_gradient().valeur()).mu_f();
  const Masse_ajoutee_base *corr = pbm && pbm->has_correlation("masse_ajoutee") ? &ref_cast(Masse_ajoutee_base, pbm->get_correlation("masse_ajoutee").valeur()) : NULL;
  int i, e, f, nf_tot = zone.nb_faces_tot(), m, n, N = inco.line_size(), d, D = dimension, cR = rho.dimension_tot(0) == 1;
  /* faces : si CLs, pas de produit par alpha * rho en multiphase */
  DoubleTrav masse(N, N), masse_e(N, N); //masse alpha * rho, contribution
  for (f = 0; f < zone.nb_faces(); f++) //faces reelles
    {
      if (!pbm || fcl(f, 0) >= 2) for (masse = 0, n = 0; n < N; n++) masse(n, n) = 1; //pas Pb_Multiphase ou CL -> pas de alpha * rho
      else for (masse = 0, i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
          {
            for (masse_e = 0, n = 0; n < N; n++) masse_e(n, n) = (*a_r)(e, n); //partie diagonale
            if (corr) corr->ajouter(&(*alpha)(e, 0), &rho(!cR * e, 0), masse_e); //partie masse ajoutee
            for (n = 0; n < N; n++) for (m = 0; m < N; m++) masse(n, m) += mu_f(f, n, i) * masse_e(n, m); //contribution au alpha * rho de la face
          }
      for (n = 0; n < N; n++)
        {
          double fac = pf(f) * vf(f) / dt;
          for (m = 0; m < N; m++) secmem(f, n) -= fac * resoudre_en_increments * masse(n, m) * inco(f, m);
          if (fcl(f, 0) < 2) for (m = 0; m < N; m++) secmem(f, n) += fac * masse(n, m) * passe(f, m);
          else if (fcl(f, 0) == 3) for (d = 0; d < D; d++)
              secmem(f, n) += fac * masse(n, n) * ref_cast(Dirichlet, cls[fcl(f, 1)].valeur()).val_imp(fcl(f, 2), N * d + n) * nf(f, d) / fs(f);
          if (mat) for (m = 0; m < N; m++) if (masse(n, m)) (*mat)(N * f + n, N * f + m) += fac * masse(n, m);
        }
    }
  for (e = 0, i = nf_tot; e < zone.nb_elem_tot(); e++) //tous les elems (pour Op_Grad_CoviMAC_Face)
    {
      for (masse = 0, n = 0; n < N; n++) masse(n, n) = a_r ? (*a_r)(e, n) : 1; //partie diagonale
      if (corr) corr->ajouter(&(*alpha)(e, 0), &rho(!cR * e, 0), masse); //partie masse ajoutee
      for (d = 0; d < D; d++, i++) for (n = 0; n < N; n++)
          {
            double fac = pe(e) * ve(e) / dt;
            for (m = 0; m < N; m++) secmem(i, n) -= fac * masse(n, m) * (resoudre_en_increments * inco(i, m) - passe(i, m));
            if (mat) for (m = 0; m < N; m++) if (masse(n, m)) (*mat)(N * i + n, N * i + m) += fac * masse(n, m);
          }
    }
}
DoubleTab & Masse_CoviMAC_Face::appliquer_impl (DoubleTab & sm) const [virtual]
Implements Solveur_Masse_base.
Definition at line 71 of file Masse_CoviMAC_Face.cpp.
References Objet_U::dimension, DoubleVect::echange_espace_virtuel(), MorEqn::equation(), Zone_VF::face_voisins(), Equation_base::inconnue(), la_zone_CoviMAC, DoubleVect::line_size(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, sub_type, valeur(), Ref_Zone_CoviMAC::valeur(), Champ_Inc::valeurs(), Zone_VF::volumes(), and Zone_VF::volumes_entrelaces().
{
  const Zone_CoviMAC& zone = la_zone_CoviMAC.valeur();
  const IntTab& f_e = zone.face_voisins();
  const DoubleVect& pf = zone.porosite_face(), &pe = zone.porosite_elem(), &vf = zone.volumes_entrelaces(), &ve = zone.volumes();
  int i, e, f, nf_tot = zone.nb_faces_tot(), n, N = equation().inconnue().valeurs().line_size(), d, D = dimension;
  const DoubleTab *a_r = sub_type(QDM_Multiphase, equation()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.champ_conserve().passe() : NULL,
                   &mu_f = ref_cast(Op_Grad_CoviMAC_Face, ref_cast(Navier_Stokes_std, equation()).operateur_gradient().valeur()).mu_f();
  double fac;
// vitesses aux faces
  for (f = 0; f < zone.nb_faces(); f++) for (n = 0; n < N; n++)
      {
        for (fac = 0, i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++) fac += mu_f(f, n, i) * (a_r ? (*a_r)(e, n) : 1);
        sm(f, n) /= pf(f) * vf(f) * fac; //vitesse calculee
      }
// vitesses aux elements
  for (e = 0; e < zone.nb_elem(); e++) for (d = 0; d < D; d++) for (n = 0; n < N; n++)
        sm(nf_tot + D * e + d, n) /= pe(e) * ve(e) * (a_r ? (*a_r)(e, n) : 1);
  sm.echange_espace_virtuel();
  return sm;
}
void Masse_CoviMAC_Face::associer_zone_cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis_base) [virtual]
Implements Solveur_Masse_base.
Definition at line 176 of file Masse_CoviMAC_Face.cpp.
References la_zone_Cl_CoviMAC, and ref_cast.
{
  la_zone_Cl_CoviMAC = ref_cast(Zone_Cl_CoviMAC, la_zone_Cl_dis_base);
}
void Masse_CoviMAC_Face::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) [virtual]
Implements Solveur_Masse_base.
Definition at line 171 of file Masse_CoviMAC_Face.cpp.
References la_zone_CoviMAC, and ref_cast.
{
  la_zone_CoviMAC = ref_cast(Zone_CoviMAC, la_zone_dis_base);
}
void Masse_CoviMAC_Face::check_multiphase_compatibility () const [inline, virtual]
Reimplemented from MorEqn.
Definition at line 60 of file Masse_CoviMAC_Face.h.
{ };
DoubleTab & Masse_CoviMAC_Face::corriger_solution (DoubleTab & x, const DoubleTab & y, int incr = 0) const [virtual]
Reimplemented from Solveur_Masse_base.
Definition at line 182 of file Masse_CoviMAC_Face.cpp.
References MorEqn::equation(), Option_CoviMAC::interp_ve1, ref_cast, Champ_Face_CoviMAC::update_ve(), Champ_Face_CoviMAC::update_ve2(), and valeur().
{
  const Champ_Face_CoviMAC& ch = ref_cast(Champ_Face_CoviMAC, equation().inconnue().valeur());
  Option_CoviMAC::interp_ve1 ? ch.update_ve(x) : ch.update_ve2(x, incr);
  return x;
}
Objet_U * Masse_CoviMAC_Face::cree_instance () [static]
Definition at line 45 of file Masse_CoviMAC_Face.cpp.
void Masse_CoviMAC_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const
Definition at line 96 of file Masse_CoviMAC_Face.cpp.
References Matrix_tools::allocate_morse_matrix(), IntTab::append_line(), Objet_U::dimension, MorEqn::equation(), Pb_Multiphase::get_correlation(), Nom::getString(), Pb_Multiphase::has_correlation(), Equation_base::inconnue(), la_zone_CoviMAC, O_U_Ptr::le_nom(), DoubleVect::line_size(), Matrice_Morse::nb_colonnes(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), ref_cast, ArrOfInt::set_smart_resize(), DoubleVect::size_totale(), sub_type, Deriv_Correlation_base::valeur(), and Champ_Inc::valeurs().
{
  const std::string& nom_inc = equation().inconnue().le_nom().getString();
  if (!matrices.count(nom_inc)) return; //rien a faire
  Matrice_Morse& mat = *matrices.at(nom_inc), mat2;
  const Zone_CoviMAC& zone = la_zone_CoviMAC;
  const DoubleTab& inco = equation().inconnue().valeurs();
  const Pb_Multiphase *pbm = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()) : NULL;
  const Masse_ajoutee_base *corr = pbm && pbm->has_correlation("masse_ajoutee") ? &ref_cast(Masse_ajoutee_base, pbm->get_correlation("masse_ajoutee").valeur()) : NULL;
  int i, e, f, nf_tot = zone.nb_faces_tot(), m, n, N = inco.line_size(), d, D = dimension;
  IntTrav sten(0, 2);
  sten.set_smart_resize(1);
  for (f = 0, i = 0; f < zone.nb_faces(); f++) for (n = 0; n < N; n++, i++) //faces reelles
      if (corr) for (m = 0; m < N; m++) sten.append_line(i, N * f + m);
      else sten.append_line(i, i);
  for (e = 0, i = N * nf_tot; e < zone.nb_elem_tot(); e++) for (d = 0; d < D; d++) for (n = 0; n < N; n++, i++) //tous les elems (pour Op_Grad_CoviMAC_Face)
        if (corr) for (m = 0; m < N; m++) sten.append_line(i, N * (nf_tot + D * e + d) + m);
        else sten.append_line(i, i);
  Matrix_tools::allocate_morse_matrix(inco.size_totale(), inco.size_totale(), sten, mat2);
  mat.nb_colonnes() ? mat += mat2 : mat = mat2;
}
int Masse_CoviMAC_Face::duplique () const [virtual]
Implements Solveur_Masse_base.
Definition at line 45 of file Masse_CoviMAC_Face.cpp.
const Type_info * Masse_CoviMAC_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 45 of file Masse_CoviMAC_Face.cpp.
int Masse_CoviMAC_Face::has_interface_blocs () const [inline, virtual]
Reimplemented from Solveur_Masse_base.
Definition at line 53 of file Masse_CoviMAC_Face.h.
  {
    return 1;
  };
const Type_info * Masse_CoviMAC_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 45 of file Masse_CoviMAC_Face.cpp.
Sortie & Masse_CoviMAC_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 51 of file Masse_CoviMAC_Face.cpp.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Masse_CoviMAC_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 59 of file Masse_CoviMAC_Face.cpp.
{
  return s ;
}
const Masse_CoviMAC_Face & Masse_CoviMAC_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Solveur_Masse_base.
Definition at line 45 of file Masse_CoviMAC_Face.cpp.
Masse_CoviMAC_Face & Masse_CoviMAC_Face::self_cast (Objet_U & r) [static]
Reimplemented from Solveur_Masse_base.
Definition at line 45 of file Masse_CoviMAC_Face.cpp.
unsigned Masse_CoviMAC_Face::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 45 of file Masse_CoviMAC_Face.cpp.
Member Data Documentation
const Type_info Masse_CoviMAC_Face::info_obj [static]
Reimplemented from Solveur_Masse_base.
Definition at line 41 of file Masse_CoviMAC_Face.h.
Ref_Zone_Cl_CoviMAC Masse_CoviMAC_Face::la_zone_Cl_CoviMAC [private]
Definition at line 64 of file Masse_CoviMAC_Face.h.
Referenced by ajouter_blocs(), and associer_zone_cl_dis_base().
Ref_Zone_CoviMAC Masse_CoviMAC_Face::la_zone_CoviMAC [private]
Definition at line 60 of file Masse_CoviMAC_Face.h.
Referenced by ajouter_blocs(), appliquer_impl(), associer_zone_dis_base(), and dimensionner_blocs().
The documentation for this class was generated from the following files:
src/CoviMAC/Solveurs/Masse_CoviMAC_Face.h
src/CoviMAC/Solveurs/Masse_CoviMAC_Face.cpp