TRUST: List_Bord Class Reference
List_Bord Class Reference
#include <Bords.h>
Public Member Functions
List_Bord ()
~List_Bord ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
List_Bord (const Bord &t)
List_Bord (const List_Bord &t)
Bord & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Bord & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Bord & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Bord & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Bord & operator() (int i)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Bord & operator() (int i) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Bord & operator() (const Nom &n)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Bord & operator() (const Nom &n) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Bord & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Bord & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
List_Bord & operator= (const Bord &t)
Bord * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
List_Bord & operator= (const List_Bord &)
List_Bord & add (const List_Bord &)
Bord & add (const Bord &)
List_Bord & inserer (const List_Bord &)
Bord & inserer (const Bord &)
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
List_Bord & operator+= (const List_Bord &)
List_Bord & operator+= (const Bord &)
Bord & add_if_not (const Bord &)
Bord & add_if_not (const char *const)
List_Bord & search (const Bord &) const
List_Bord & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
List_Bord & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
const List_Bord & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
const List_Bord & dernier () const
Renvoie le dernier element de la liste.
List_Bord & dernier ()
Renvoie le dernier element de la liste.
List_Bord & operator-= (const Bord &)
int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
int contient (const Bord &) const
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
int rang (const Bord &) const
void suppr (const Bord &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static List_Bord & self_cast (Objet_U &)
static const List_Bord & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture d'une liste sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'une liste sur un flot d'entree.
int est_egal_a (const List_Bord &) const
Detailed Description
Definition at line 30 of file Bords.h.
Constructor & Destructor Documentation
List_Bord::List_Bord ()
Definition at line 25 of file Bords.cpp.
List_Bord::~List_Bord ()
Definition at line 25 of file Bords.cpp.
List_Bord::List_Bord (const Bord & t) [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
List_Bord::List_Bord (const List_Bord & t) [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
Member Function Documentation
List_Bord & List_Bord::add (const List_Bord & a_list) [inline]
Definition at line 30 of file Bords.h.
Referenced by Zones::comprimer(), Extruder_en3::construire_bords(), DomaineCutter::construire_faces_bords_ssdom(), DecoupeBord::Decouper(), TroisDto2D::extraire_2D(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt(), Extruder::extruder_dvt_hexa(), ExtrudeBord::extruder_hexa_old(), MaillerParallel::interpreter(), Lire_Tgrid::interpreter_(), Lire_Ideas::interpreter_(), Extraire_domaine::interpreter_(), Create_domain_from_sous_zone::interpreter_(), Zones::merge(), Pave::readOn(), Raffiner_Simplexes::refine_domain(), and Remove_elem::Remove_elem_().
: public LIST(Bord)
Bord & List_Bord::add (const Bord & t) [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
Bord & List_Bord::add_if_not (const Bord & t) [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
Bord & List_Bord::add_if_not (const char * const t) [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
int List_Bord::contient (const Bord & t) const [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
int List_Bord::contient (const char * const ch) const [inline]
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
Returns:
int
Signification: 1 si la liste contient un Objet_U de Nom ch, 0 sinon
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
Objet_U * List_Bord::cree_instance () [static]
Reimplemented from liste.
Reimplemented in Bords.
Definition at line 25 of file Bords.cpp.
const List_Bord& List_Bord::dernier () const [inline]
Renvoie le dernier element de la liste.
Returns:
const liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented from liste.
List_Bord & List_Bord::dernier () [inline]
Renvoie le dernier element de la liste.
Returns:
liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
int List_Bord::duplique () const [virtual]
Reimplemented from liste.
Reimplemented in Bords.
Definition at line 25 of file Bords.cpp.
int List_Bord::est_egal_a (const Objet_U & x) const [virtual]
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
Reimplemented from Objet_U.
Definition at line 25 of file Bords.cpp.
int List_Bord::est_egal_a (const List_Bord &) const [inline, protected]
const Type_info * List_Bord::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from liste.
Reimplemented in Bords.
Definition at line 25 of file Bords.cpp.
const Type_info * List_Bord::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from liste.
Reimplemented in Bords.
Definition at line 25 of file Bords.cpp.
List_Bord & List_Bord::inserer (const List_Bord & a_list) [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
Bord & List_Bord::inserer (const Bord & t) [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
const Bord & List_Bord::operator() (const Nom & nom) const [inline]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
Bord & List_Bord::operator() (const Nom & nom) [inline]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
const Bord & List_Bord::operator() (int i) const [inline]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
Bord & List_Bord::operator() (int i) [inline]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
List_Bord & List_Bord::operator+= (const Bord & t) [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
List_Bord & List_Bord::operator+= (const List_Bord & a_list) [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
List_Bord & List_Bord::operator-= (const Bord & t) [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
Bord * List_Bord::operator-> () [inline]
Retourne un pointeur sur l'Objet_U premier element de la liste.
Returns:
Objet_U*
Signification: pointeur sur l'Objet_U premier element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
List_Bord & List_Bord::operator= (const Bord & t) [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
List_Bord & List_Bord::operator= (const List_Bord & a_list) [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
Bord & List_Bord::operator[] (int i) [inline]
Operateur d'acces au ieme element de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
Bord & List_Bord::operator[] (const Nom & nom) [inline]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
const Bord & List_Bord::operator[] (const Nom & nom) const [inline]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
const Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
const Bord & List_Bord::operator[] (int i) const [inline]
Operateur d'acces au ieme element de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
Sortie & List_Bord::printOn (Sortie & os) const [protected, virtual]
Ecriture d'une liste sur un flot de sortie.
Returns:
Sortie&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from liste.
Reimplemented in Bords.
Definition at line 25 of file Bords.cpp.
int List_Bord::rang (const Bord & t) const [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
Entree & List_Bord::readOn (Entree & is) [protected, virtual]
Lecture d'une liste sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from liste.
Reimplemented in Bords.
Definition at line 25 of file Bords.cpp.
List_Bord & List_Bord::search (const Bord & t) const [inline]
Definition at line 30 of file Bords.h.
: public LIST(Bord)
List_Bord & List_Bord::search (const char * const ch) const [inline]
Recherche d'un Objet_U de Nom ch dans la liste.
Returns:
liste&
Signification: L'element de la liste trouve
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
const List_Bord & List_Bord::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from liste.
Reimplemented in Bords.
Definition at line 25 of file Bords.cpp.
List_Bord & List_Bord::self_cast (Objet_U & r) [static]
Reimplemented from liste.
Reimplemented in Bords.
Definition at line 25 of file Bords.cpp.
const List_Bord & List_Bord::suivant () const [inline]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
const liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
List_Bord & List_Bord::suivant () [inline]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
void List_Bord::suppr (const Bord & t) [inline]
Definition at line 30 of file Bords.h.
Referenced by DecoupeBord::Decouper(), TroisDto2D::extraire_2D(), SupprimeBord::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Modif_bord_to_raccord::interpreter_(), Create_domain_from_sous_zone::interpreter_(), and RegroupeBord::regroupe_bord().
: public LIST(Bord)
void List_Bord::supprimer () [inline]
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
unsigned List_Bord::taille_memoire () const [virtual]
Reimplemented from liste.
Reimplemented in Bords.
Definition at line 25 of file Bords.cpp.
const Bord & List_Bord::valeur () const [inline]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
const Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
Bord & List_Bord::valeur () [inline]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented from liste.
Definition at line 30 of file Bords.h.
: public LIST(Bord)
Member Data Documentation
const Type_info List_Bord::info_obj [static]
Reimplemented from liste.
Reimplemented in Bords.
Definition at line 30 of file Bords.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Bords.h
src/Kernel/Geometrie/Bords.cpp