TRUST: Partitionneur_Parmetis Class Reference
Partitionneur_Parmetis Class Reference
Partition d'un domaine en nb_parties parties equilibrees en utilisant
la librairie PARMETIS. Voir construire_partition.
#include <Partitionneur_Parmetis.h>
Public Member Functions
Partitionneur_Parmetis ()
~Partitionneur_Parmetis ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void associer_domaine (const Domaine &domaine) override
void construire_partition (IntVect &elem_part, int &nb_parts_tot) const override
Calcule le graphe de connectivite pour parmetis, appelle le partitionneur
et remplit elem_part (pour chaque element, numero de la partie qui lui
est attribuee).
Public Member Functions inherited from Partitionneur_base
Partitionneur_base ()
~Partitionneur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void associer_domaine (const Domaine &domaine)=0
virtual void declarer_bords_periodiques (const Noms &noms_bords_periodiques)
virtual void construire_partition (IntVect &elem_part, int &nb_parts_tot) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Partitionneur_Parmetis & self_cast (Objet_U &)
static const Partitionneur_Parmetis & self_cast (const Objet_U &)
Static Public Member Functions inherited from Partitionneur_base
static const Type_info * info ()
static Partitionneur_base & self_cast (Objet_U &)
static const Partitionneur_base & self_cast (const Objet_U &)
static void corriger_elem0_sur_proc0 (IntVect &elem_part)
corrige la partition pour que l'element 0 du domaine initial
se trouve sur le premier sous-domaine de la partition.
On echange le premier sous-domaine et celui qui contient l'element 0.
static int calculer_graphe_connexions_periodiques (const Zone &zone, const Noms &liste_bords_periodiques, const Static_Int_Lists &som_elem, const int my_offset, Static_Int_Lists &graph)
Calcul d'un graphe de connectivite entre les elements lies par des faces periodiques.
Si l'element i est voisin de l'element j par une face periodique, alors il existe
k tel que graph(i,k)==j et il existe k2 tel que graph(j,k2)==i.
Parametre: zone
Signification: la zone a traiter
Parametre: liste_bords_periodiques
Signification: liste des noms des bords periodiques. ATTENTION: on suppose que les
faces des bords periodiques sont rangees selon la convention des bords periodiques.
Voir check_faces_periodiques().
Parametre: som_elem
Signification: la connectivite sommets-elements pour la zone donnee.
Parametre: graph
Signification: On y stocke le resultat.
Valeur de retour: nombre d'elements dans le graphe (egal au nombre de faces periodiques)
static int corriger_bords_avec_graphe (const Static_Int_Lists &graph_elements_perio, const Static_Int_Lists &som_elem, const Domaine &domaine, const Noms &liste_bords_perio, IntVect &elem_part)
corrige la partition elem_part pour qu'un element i se trouve sur la meme
partition elem_part[i] que tous les elements auxquels il est lie dans le graphe
(elements d'indices graph_elements_perio(i, j) pour tout j).
Parametre: graph_elements_perio
Signification: graphe calcule par la methode calculer_graphe_connexions_periodiques
Parametre: elem_part
Signification: pour chaque element, a quelle partie appartient-il.
Valeur de retour: nombre d'elements dont la partition a ete corrigee.
static void corriger_bords_avec_liste (const Domaine &dom, const Noms &liste_bords_periodiques, const int my_offset, IntVect &elem_part)
Calcul des graphes de connectivite elements periodiques et appel a
corriger_periodique_avec_graphe. (Methode a utiliser quand on ne dispose
pas encore du graphe de de connectivite, si on a le graphe sous la main,
appeler directement corriger_periodique_avec_graphe)
static int corriger_sommets_bord (const Domaine &domaine, const Noms &liste_bords_perio, const ArrOfInt &renum_som_perio, const Static_Int_Lists &som_elem, IntVect &elem_part)
Modifie elem_part pour assurer les proprietes suivantes :
1) Les elements possedant un sommet de bord sont associes
a un processeur possedant une face de bord adjacente a ce sommet.
2) Si un processeur possede un sommet periodique reel, il
possede forcement le renum_som_perio associe (donc un element
qui possede ce sommet et un face periodique).
Cette propriete est indispensable pour le periodique (existence
de renum_som_perio pour tous les sommets).
Pour les autres bords, cette correction est peut-etre inutile, mais
pas sur. Sans cette correction, il peut exister des sommets de bord
isoles (un processeur possede un sommet de bord mais aucune face).
Si on cherche les sommets de bord en parcourant les faces de bord,
c'est faux. Avec cette correction, cet algorithme est correct.
static int corriger_multiperiodique (const Domaine &domaine, const Noms &liste_bords_perio, const ArrOfInt &renum_som_perio, const Static_Int_Lists &som_elem, IntVect &elem_part)
applique des corrections a elem_part pour que le
multi-periodique soit correct :
Si un sommet appartient a plusieurs frontieres periodiques,
tous les elements adjacents sont rattaches au meme processeur.
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Partitionneur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Ref_Domaine ref_domaine_
int nb_parties_
int use_weights_
Additional Inherited Members
Protected Attributes inherited from Partitionneur_base
Noms liste_bords_periodiques_
Detailed Description
Partition d'un domaine en nb_parties parties equilibrees en utilisant
la librairie PARMETIS. Voir construire_partition.
Definition at line 25 of file Partitionneur_Parmetis.h.
Constructor & Destructor Documentation
Partitionneur_Parmetis()
Partitionneur_Parmetis::Partitionneur_Parmetis ()
Definition at line 39 of file Partitionneur_Parmetis.cpp.
{
  nb_parties_ = -1;
  use_weights_ = 0;
}
References nb_parties_, and use_weights_.
~Partitionneur_Parmetis()
Partitionneur_Parmetis::~Partitionneur_Parmetis ()
Definition at line 37 of file Partitionneur_Parmetis.cpp.
Member Function Documentation
associer_domaine()
void Partitionneur_Parmetis::associer_domaine (const Domaine & domaine) override virtual
Implements Partitionneur_base.
Definition at line 70 of file Partitionneur_Parmetis.cpp.
{
  ref_domaine_ = domaine;
}
References ref_domaine_.
construire_partition()
void Partitionneur_Parmetis::construire_partition (IntVect & elem_part, int & nb_parts_tot) const override virtual
Calcule le graphe de connectivite pour parmetis, appelle le partitionneur
et remplit elem_part (pour chaque element, numero de la partie qui lui
est attribuee).
Implements Partitionneur_base.
Definition at line 79 of file Partitionneur_Parmetis.cpp.
{
#ifndef PARMETIS_
  Cerr << "PARMETIS is not compiled with this version. Use another partition tool like Tranche." << finl;
  Process::exit();
#else
  if (!ref_domaine_.non_nul())
    {
      Cerr << "Error in Partitionneur_Parmetis::construire_partition\n";
      Cerr << " The domain has not been associated" << finl;
      exit();
    }
  if (nb_parties_ <= 0)
    {
      Cerr << "Error in Partitionneur_Parmetis::construire_partition\n";
      Cerr << " The parts number has not been initialized" << finl;
      exit();
    }
// Cas particulier: si nb_parts == 1, METIS ne veut rien faire...
// ToDo: I don't know is that's the case with ParMetis
  if (nb_parties_ == 1)
    {
      int nb_elem = ref_domaine_.valeur().zone(0).nb_elem();
      elem_part.resize_array(nb_elem);
      elem_part = 0;
      return;
    }
  if (ref_domaine_.valeur().zone(0).nb_elem() == 0)
    return;
  Cerr << "Partitionneur_Parmetis::construire_partition" << finl;
  Cerr << " Construction of graph connectivity..." << finl;
  Static_Int_Lists graph_elements_perio;
// const Domaine& dom = ref_domaine_.valeur();
  Domain_Graph graph;
  graph.construire_graph_elem_elem(ref_domaine_.valeur(), liste_bords_periodiques_,
                                   use_weights_,
                                   graph_elements_perio);
  std::vector<idx_t> partition(graph.nvtxs);
  idx_t int_parts = nb_parties_;
  idx_t edgecut = 0; //!< valeur renvoyee par parmetis (nombre total de faces de joint)
  Cerr << " Call for PARMETIS" << finl;
  idx_t options[3];
  options[0] = 1; //personnalized options
  options[1] = 111111111; //!< Mode verbose maximal;
  options[2] = 0; //random seed
  idx_t ncon=1;
  real_t ubvec = 1.05; //recommanded value
  idx_t numflag = 0; //numerotation C
  std::vector<real_t> tpwgts(ncon*int_parts, 1./int_parts); //we want the weight to be equally distributed on each sub_somain
  MPI_Comm comm = Comm_Group_MPI::get_trio_u_world();
  int status = ParMETIS_V3_PartKway(graph.vtxdist.addr(), graph.xadj.addr(), graph.adjncy.addr(),
                                    graph.vwgts.addr(), graph.ewgts.addr(), &graph.weightflag,
                                    &numflag, &ncon, &int_parts, tpwgts.data(), &ubvec, options ,
                                    &edgecut, partition.data(), &comm);
  if (status != METIS_OK)
    {
      Cerr << "Call to PARMETIS failed." << finl;
      if (status == METIS_ERROR)        Cerr << "It seems there is a PARMETIS internal error." << finl;
      Cerr << "Contact TRUST support." << finl;
      exit();
    }
  Cerr << "Partitioning quality : edgecut = " << edgecut << finl;
  Cerr << "-> It is roughly the total number of edges (faces) which will be shared by the processors." << finl;
  Cerr << "-> The lesser this number is, the lesser the total volume of communication between processors." << finl;
  Cerr << "-> You can increase nb_essais option (default 1) to try to reduce (but at a higher CPU cost) this number." << finl;
  Cerr << "===============" << finl;
  MD_Vector_tools::creer_tableau_distribue(ref_domaine_.valeur().zone(0).md_vector_elements(), elem_part);
  const int n = ref_domaine_.valeur().zone(0).nb_elem();
  for (int i = 0; i < n; i++)
    elem_part[i] = partition[i];
// Correction de la partition pour la periodicite. (***)
  if (graph_elements_perio.get_nb_lists() > 0)
    {
      Cerr << "Correction of the partition for the periodicity" << finl;
      corriger_bords_avec_liste(ref_domaine_.valeur(),
                                liste_bords_periodiques_,
                                0,
                                elem_part);
      Cerr << "  If this number is high, we can improve the splitting with the option use_weights\n"
           << "  but it takes more memory)" << finl;
    }
  Cerr << "Correction elem0 on processor 0" << finl;
  corriger_elem0_sur_proc0(elem_part);
  elem_part.echange_espace_virtuel();
#endif
}
References TRUSTArray< _TYPE_ >::addr(), Domain_Graph::adjncy, Cerr, comm, Domain_Graph::construire_graph_elem_elem(), Partitionneur_base::corriger_bords_avec_liste(), Partitionneur_base::corriger_elem0_sur_proc0(), MD_Vector_tools::creer_tableau_distribue(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Domain_Graph::ewgts, Process::exit(), finl, Static_Int_Lists::get_nb_lists(), Comm_Group_MPI::get_trio_u_world(), Partitionneur_base::liste_bords_periodiques_, Zone::md_vector_elements(), Zone::nb_elem(), nb_parties_, O_U_Ptr::non_nul(), Domain_Graph::nvtxs, ref_domaine_, TRUSTArray< _TYPE_ >::resize_array(), use_weights_, Ref_Domaine::valeur(), Domain_Graph::vtxdist, Domain_Graph::vwgts, Domain_Graph::weightflag, Domain_Graph::xadj, and Domaine::zone().
cree_instance()
Objet_U * Partitionneur_Parmetis::cree_instance () static
Definition at line 37 of file Partitionneur_Parmetis.cpp.
duplique()
int Partitionneur_Parmetis::duplique () const override virtual
Implements Objet_U.
Definition at line 37 of file Partitionneur_Parmetis.cpp.
get_info()
const Type_info * Partitionneur_Parmetis::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 37 of file Partitionneur_Parmetis.cpp.
info()
const Type_info * Partitionneur_Parmetis::info () static
Definition at line 37 of file Partitionneur_Parmetis.cpp.
lire_motcle_non_standard()
int Partitionneur_Parmetis::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Partitionneur_base.
Definition at line 65 of file Partitionneur_Parmetis.cpp.
{
  return Partitionneur_base::lire_motcle_non_standard(mot,is);
}
References Partitionneur_base::lire_motcle_non_standard().
printOn()
Sortie & Partitionneur_Parmetis::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 45 of file Partitionneur_Parmetis.cpp.
{
  Cerr << "Partitionneur_Parmetis::printOn invalid\n" << finl;
  exit();
  return os;
}
References Cerr, Process::exit(), and finl.
readOn()
Entree & Partitionneur_Parmetis::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 52 of file Partitionneur_Parmetis.cpp.
{
  Partitionneur_base::readOn(is);
  return is;
}
References Partitionneur_base::readOn().
self_cast() [1/2]
const Partitionneur_Parmetis & Partitionneur_Parmetis::self_cast (const Objet_U & r) static
Definition at line 37 of file Partitionneur_Parmetis.cpp.
self_cast() [2/2]
Partitionneur_Parmetis & Partitionneur_Parmetis::self_cast (Objet_U & r) static
Definition at line 37 of file Partitionneur_Parmetis.cpp.
set_param()
void Partitionneur_Parmetis::set_param (Param & param) override virtual
Implements Partitionneur_base.
Definition at line 58 of file Partitionneur_Parmetis.cpp.
{
  param.ajouter("nb_parts",&nb_parties_,Param::REQUIRED);
  param.ajouter_condition("(value_of_nb_parts_ge_1)_and_(value_of_nb_parts_le_100000)","The following condition must be satisfied : 1 <= nb_parties <= 100000");
  param.ajouter_flag("use_weights",&use_weights_);
}
References Param::ajouter(), Param::ajouter_condition(), Param::ajouter_flag(), nb_parties_, Param::REQUIRED, and use_weights_.
taille_memoire()
unsigned Partitionneur_Parmetis::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 37 of file Partitionneur_Parmetis.cpp.
Member Data Documentation
info_obj
const Type_info Partitionneur_Parmetis::info_obj static
Definition at line 27 of file Partitionneur_Parmetis.h.
nb_parties_
int Partitionneur_Parmetis::nb_parties_ private
Definition at line 39 of file Partitionneur_Parmetis.h.
Referenced by construire_partition(), Partitionneur_Parmetis(), and set_param().
ref_domaine_
Ref_Domaine Partitionneur_Parmetis::ref_domaine_ private
Definition at line 38 of file Partitionneur_Parmetis.h.
Referenced by associer_domaine(), and construire_partition().
use_weights_
int Partitionneur_Parmetis::use_weights_ private
Definition at line 42 of file Partitionneur_Parmetis.h.
Referenced by construire_partition(), Partitionneur_Parmetis(), and set_param().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Decoupeur/Partitionneur_Parmetis.h
src/Kernel/Geometrie/Decoupeur/Partitionneur_Parmetis.cpp