TRUST: Perte_Charge_PolyMAC Class Reference
Perte_Charge_PolyMAC Class Reference
#include <Perte_Charge_PolyMAC.h>
Public Member Functions
Perte_Charge_PolyMAC ()
~Perte_Charge_PolyMAC ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const
Appelle perte_charge pour chaque face ou cela est necessaire.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
copie de ajouter sauf la derniere ligne
DoubleTab & calculer (DoubleTab &) const
void associer_pb (const Probleme_base &)
associe le_fluide et la_vitesse
void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Perte_Charge_PolyMAC & self_cast (Objet_U &)
static const Perte_Charge_PolyMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
associe la_Zone_PolyMAC et la_Zone_Cl_PolyMAC
virtual void coeffs_perte_charge (const DoubleVect &u, const DoubleVect &pos, double t, double norme_u, double dh, double nu, double reynolds, double &coeff_ortho, double &coeff_long, double &u_l, DoubleVect &v_valeur) const =0
Protected Attributes
Champ_Don diam_hydr
Ref_Fluide_base le_fluide
Ref_Champ_Inc_base la_vitesse
Ref_Zone_PolyMAC la_Zone_PolyMAC
Ref_Zone_Cl_PolyMAC la_Zone_Cl_PolyMAC
bool sous_zone
Le terme est-il limite a une sous-zone ?
Nom nom_sous_zone
Nom de la sous-zone, initialise dans readOn()
Ref_Sous_Zone la_sous_zone
Initialise dans completer()
int implicite_
Detailed Description
Perte_Charge_Isotrope, Perte_Charge_Directionnelle et Perte_Charge_Anisotrope heritent de Perte_Charge_PolyMAC. Elles doivent surcharger essentiellement readOn() et perte_charge(). readOn() est suppose lire au moins diam_hydr et sous_zone.
Ces classes sont censees remplacer Perte_Charge_PolyMAC_Face et Perte_Charge_PolyMAC_P1NC. ! Factorise les fonctionnalites de plusieurs pertes de charge en VEF, vitesse aux faces
Definition at line 45 of file Perte_Charge_PolyMAC.h.
Constructor & Destructor Documentation
Perte_Charge_PolyMAC::Perte_Charge_PolyMAC ()
Definition at line 40 of file Perte_Charge_PolyMAC.cpp.
:implicite_(1) { }
Perte_Charge_PolyMAC::~Perte_Charge_PolyMAC ()
Definition at line 38 of file Perte_Charge_PolyMAC.cpp.
Member Function Documentation
DoubleTab & Perte_Charge_PolyMAC::ajouter (DoubleTab & resu) const [virtual]
Appelle perte_charge pour chaque face ou cela est necessaire.
Reimplemented from Source_base.
Definition at line 64 of file Perte_Charge_PolyMAC.cpp.
References coeffs_perte_charge(), diam_hydr, IntTab::dimension(), Objet_U::dimension, Zone_PolyMAC::dot(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Champ_Face_PolyMAC::icl, la_sous_zone, la_vitesse, la_Zone_PolyMAC, le_fluide, Zone_PolyMAC::m2c, Zone_PolyMAC::m2d, Zone_PolyMAC::m2i, Zone_PolyMAC::m2j, max(), min(), Zone_dis_base::nb_elem_tot(), Sous_Zone::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, Equation_base::schema_temps(), sous_zone, sub_type, Schema_Temps_base::temps_courant(), Deriv_Champ_Don_base::valeur(), Ref_Sous_Zone::valeur(), valeur(), Ref_Zone_PolyMAC::valeur(), Zone_PolyMAC::veci, Zone_PolyMAC::vedeb, Zone_PolyMAC::veji, Zone_VF::volumes(), Zone_VF::xp(), and Zone_VF::xv().
Referenced by calculer().
{
  const Zone_PolyMAC& zone = la_Zone_PolyMAC.valeur();
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, equation().inconnue().valeur());
  const Champ_Don& nu = le_fluide->viscosite_cinematique(), &dh = diam_hydr;
  const DoubleTab& xp = zone.xp(), &xv = zone.xv(), &vit = la_vitesse->valeurs();
  const DoubleVect& pe = zone.porosite_elem(), &pf = zone.porosite_face(), &fs = zone.face_surfaces();
  const Sous_Zone *pssz = sous_zone ? &la_sous_zone.valeur() : NULL;
  const IntTab& e_f = zone.elem_faces(), &f_e = zone.face_voisins();
  int i, j, k, f, fb, r, C_nu = sub_type(Champ_Uniforme,nu.valeur()), C_dh = sub_type(Champ_Uniforme,diam_hydr.valeur());
  double t = equation().schema_temps().temps_courant();
  DoubleVect pos(dimension), ve(dimension), ved(dimension), vep(dimension) , dir(dimension);
  /* contribution de chaque element ou on applique la perte de charge */
  for (i = 0; i < (pssz ? pssz->nb_elem_tot() : zone.nb_elem_tot()); i++)
    {
      int e = pssz ? (*pssz)[i] : i;
      for (r = 0; r < dimension; r++) pos(r) = xp(e, r);
      /* valeurs evaluees en l'element : nu, Dh, vecteur vitesse, Re, coefficients de perte de charge isotrope et directionel + la direction */
      double nu_e = C_nu ? nu(0, 0) : nu->valeur_a_compo(pos, 0),
             dh_e = C_dh ? dh(0, 0) : dh->valeur_a_compo(pos, 0);
      for (j = zone.vedeb(e), ve = 0; j < zone.vedeb(e + 1); j++) for (r = 0; r < dimension; r++)
          fb = zone.veji(j), ve(r) += zone.veci(j, r) * vit(fb) * pf(fb) / pe(e);
      double n_ve = sqrt(zone.dot(ve.addr(), ve.addr())), Re = max( n_ve * dh_e / nu_e, 1e-10), C_iso, C_dir, v_dir;
      coeffs_perte_charge(ve, pos, t, n_ve, dh_e, nu_e, Re, C_iso, C_dir, v_dir, dir);
      /* contributions aux faces de e */
      for (j = 0; j < e_f.dimension(1) && (f = e_f(e, j)) >= 0; j++) if (f < zone.nb_faces() && ch.icl(f, 0) < 2)
          {
            double m2vf = 0, contrib;
            for (k = zone.m2i(zone.m2d(e) + j); k < zone.m2i(zone.m2d(e) + j + 1); k++)
              fb = e_f(e, zone.m2j(k)), m2vf += pf(f) * (e == f_e(f, 0) ? 1 : -1) * (e == f_e(fb, 0) ? 1 : -1) * zone.volumes(e) * zone.m2c(k) * vit(fb) * pf(fb) / pe(e);
            contrib = C_iso * m2vf + fs(f) * pf(f) * (C_dir - C_iso) * zone.dot(&ve(0), &dir(0)) * (e == f_e(f, 0) ? 1 : -1) * zone.dot(&xv(f, 0), &dir(0), &xp(e, 0));
            if (contrib <= min(C_dir, C_iso) * m2vf) contrib = min(C_dir, C_iso) * m2vf; //pour garantir un frottement minimal
            resu(f) -= contrib;
          }
    }
  return resu;
}
void Perte_Charge_PolyMAC::associer_pb (const Probleme_base & pb) [virtual]
associe le_fluide et la_vitesse
Implements Source_base.
Definition at line 175 of file Perte_Charge_PolyMAC.cpp.
References MorEqn::equation(), la_vitesse, le_fluide, ref_cast, and valeur().
{
  la_vitesse = ref_cast(Champ_Face_PolyMAC,equation().inconnue().valeur());
  le_fluide = ref_cast(Fluide_base,equation().milieu());
}
void Perte_Charge_PolyMAC::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) [protected, virtual]
associe la_Zone_PolyMAC et la_Zone_Cl_PolyMAC
Implements Source_base.
Definition at line 181 of file Perte_Charge_PolyMAC.cpp.
References la_Zone_Cl_PolyMAC, la_Zone_PolyMAC, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  la_Zone_PolyMAC = ref_cast(Zone_PolyMAC, zone_dis.valeur());
  la_Zone_Cl_PolyMAC = ref_cast(Zone_Cl_PolyMAC, zone_Cl_dis.valeur());
}
DoubleTab & Perte_Charge_PolyMAC::calculer (DoubleTab & resu) const [virtual]
Reimplemented from Source_base.
Definition at line 155 of file Perte_Charge_PolyMAC.cpp.
References ajouter().
{
  resu=0;
  return ajouter(resu);
}
virtual void Perte_Charge_PolyMAC::coeffs_perte_charge (const DoubleVect & u, const DoubleVect & pos, double t, double norme_u, double dh, double nu, double reynolds, double & coeff_ortho, double & coeff_long, double & u_l, DoubleVect & v_valeur) const [protected, pure virtual]
Utilise les intermediaires de calcul : u, norme_u, dh_valeur, reynolds Retourne le resultat calcule dans p_charge.
Avantage : bonne factorisation. Inconvenient : cout de l'appel d'une methode virtuelle a l'interieur d'une boucle.
Parameters:
u La vitesse a la face courante. 2 ou 3 composantes
pos toto
t titi
norme_u La norme de la vitesse a la face courante
dh Le diametre hydraulique a la face courante (tire de diam_hydr)
nu la viscosite cinematique
reynolds Le nombre de reynolds a la face courante : norme_u * dh_valeur / nu
coeff_ortho coefficient dans la direction orthogonale
coeff_long coefficient dans la direction longitudinale
u_l vitesse dans la direction longitudinale
v_valeur direction_longitudinale p_charge a 2 ou 3 composantes La perte de charge vaut -coeff_long*u_l*v_valeur -coeff_ortho(u -u_v*v_valeur) ! Appele pour chaque face par ajouter()
Implemented in Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, and Perte_Charge_Isotrope_PolyMAC_Face.
Referenced by ajouter(), and contribuer_a_avec().
void Perte_Charge_PolyMAC::completer (void) [virtual]
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
Definition at line 162 of file Perte_Charge_PolyMAC.cpp.
References Probleme_base::domaine(), MorEqn::equation(), la_sous_zone, nom_sous_zone, Equation_base::probleme(), sous_zone, and Domaine::ss_zone().
{
  Source_base::completer();
  if (sous_zone) la_sous_zone = equation().probleme().domaine().ss_zone(nom_sous_zone);
}
void Perte_Charge_PolyMAC::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const [virtual]
copie de ajouter sauf la derniere ligne
Reimplemented from Source_base.
Definition at line 106 of file Perte_Charge_PolyMAC.cpp.
References coeffs_perte_charge(), diam_hydr, IntTab::dimension(), Objet_U::dimension, Zone_PolyMAC::dot(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Champ_Face_PolyMAC::icl, la_sous_zone, la_Zone_PolyMAC, le_fluide, Zone_PolyMAC::m2c, Zone_PolyMAC::m2d, Zone_PolyMAC::m2i, Zone_PolyMAC::m2j, max(), min(), Zone_dis_base::nb_elem_tot(), Sous_Zone::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, Equation_base::schema_temps(), sous_zone, sub_type, Schema_Temps_base::temps_courant(), Deriv_Champ_Don_base::valeur(), Ref_Sous_Zone::valeur(), valeur(), Ref_Zone_PolyMAC::valeur(), Zone_PolyMAC::veci, Zone_PolyMAC::vedeb, Zone_PolyMAC::veji, Zone_VF::volumes(), Zone_VF::xp(), and Zone_VF::xv().
{
  const Zone_PolyMAC& zone = la_Zone_PolyMAC.valeur();
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, equation().inconnue().valeur());
  const Champ_Don& nu = le_fluide->viscosite_cinematique(), &dh = diam_hydr;
  const DoubleTab& xp = zone.xp(), &xv = zone.xv(), &vit = inco;
  const DoubleVect& pe = zone.porosite_elem(), &pf = zone.porosite_face(), &fs = zone.face_surfaces();
  const Sous_Zone *pssz = sous_zone ? &la_sous_zone.valeur() : NULL;
  const IntTab& e_f = zone.elem_faces(), &f_e = zone.face_voisins();
  int i, j, k, f, fb, r, C_nu = sub_type(Champ_Uniforme,nu.valeur()), C_dh = sub_type(Champ_Uniforme,diam_hydr.valeur());
  double t = equation().schema_temps().temps_courant();
  DoubleVect pos(dimension), ve(dimension), vf(dimension), dir(dimension);
  for (i = 0; i < (pssz ? pssz->nb_elem_tot() : zone.nb_elem_tot()); i++)
    {
      int e = pssz ? (*pssz)[i] : i;
      for (r = 0; r < dimension; r++) pos(r) = xp(e, r);
      /* valeurs evaluees en l'element : nu, Dh, vecteur vitesse, Re, coefficients de perte de charge isotrope et directionel + la direction */
      double nu_e = C_nu ? nu(0, 0) : nu->valeur_a_compo(pos, 0),
             dh_e = C_dh ? dh(0, 0) : dh->valeur_a_compo(pos, 0);
      for (j = zone.vedeb(e), ve = 0; j < zone.vedeb(e + 1); j++) for (r = 0; r < dimension; r++)
          fb = zone.veji(j), ve(r) += zone.veci(j, r) * vit(fb) * pf(fb) / pe(e);
      double n_ve = sqrt(zone.dot(ve.addr(), ve.addr())), Re = max( n_ve * dh_e / nu_e, 1e-10), C_iso, C_dir, v_dir;
      coeffs_perte_charge(ve, pos, t, n_ve, dh_e, nu_e, Re, C_iso, C_dir, v_dir, dir);
      /* contributions aux faces de e */
      for (j = 0; j < e_f.dimension(1) && (f = e_f(e, j)) >= 0; j++) if (f < zone.nb_faces() && ch.icl(f, 0) < 2)
          {
            double m2vf = 0, contrib;
            for (k = zone.m2i(zone.m2d(e) + j); k < zone.m2i(zone.m2d(e) + j + 1); k++)
              fb = e_f(e, zone.m2j(k)), m2vf += pf(f) * (e == f_e(f, 0) ? 1 : -1) * (e == f_e(fb, 0) ? 1 : -1) * zone.volumes(e) * zone.m2c(k) * vit(fb) * pf(fb) / pe(e);
            contrib = C_iso * m2vf + fs(f) * pf(f) * (C_dir - C_iso) * zone.dot(&ve(0), &dir(0)) * (e == f_e(f, 0) ? 1 : -1) * zone.dot(&xv(f, 0), &dir(0), &xp(e, 0));
            if (contrib >= min(C_dir, C_iso) * m2vf)
              {
                for (k = zone.m2i(zone.m2d(e) + j); k < zone.m2i(zone.m2d(e) + j + 1); k++) if (ch.icl(fb = e_f(e, zone.m2j(k)), 0) < 2)
                    matrice(f, fb) += C_iso * pf(f) * (e == f_e(f, 0) ? 1 : -1) * (e == f_e(fb, 0) ? 1 : -1) * zone.volumes(e) * zone.m2c(k) * pf(fb) / pe(e);
                for (k = zone.vedeb(e); k < zone.vedeb(e + 1); k++) if (ch.icl(fb = zone.veji(k), 0) < 2)
                    matrice(f, fb) += fs(f) * pf(f) * (C_dir - C_iso) * zone.dot(&zone.veci(k, 0), &dir(0)) * pf(fb) / pe(e) * (e == f_e(f, 0) ? 1 : -1) * zone.dot(&xv(f, 0), &dir(0), &xp(e, 0));
              }
            else
              {
                for (k = zone.m2i(zone.m2d(e) + j); k < zone.m2i(zone.m2d(e) + j + 1); k++) if (ch.icl(fb = e_f(e, zone.m2j(k)), 0) < 2)
                    matrice(f, fb) += min(C_dir, C_iso) * pf(f) * (e == f_e(f, 0) ? 1 : -1) * (e == f_e(fb, 0) ? 1 : -1) * zone.volumes(e) * zone.m2c(k) * pf(fb) / pe(e);
              }
          }
    }
}
virtual int Perte_Charge_PolyMAC::duplique () const [pure virtual]
Implements Source_base.
Implemented in Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, and Perte_Charge_Isotrope_PolyMAC_Face.
const Type_info * Perte_Charge_PolyMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, and Perte_Charge_Isotrope_PolyMAC_Face.
Definition at line 38 of file Perte_Charge_PolyMAC.cpp.
const Type_info * Perte_Charge_PolyMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, and Perte_Charge_Isotrope_PolyMAC_Face.
Definition at line 38 of file Perte_Charge_PolyMAC.cpp.
Sortie & Perte_Charge_PolyMAC::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, and Perte_Charge_Isotrope_PolyMAC_Face.
Definition at line 45 of file Perte_Charge_PolyMAC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << endl;
}
Entree & Perte_Charge_PolyMAC::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, and Perte_Charge_Isotrope_PolyMAC_Face.
Definition at line 53 of file Perte_Charge_PolyMAC.cpp.
{
  return s;
}
Perte_Charge_PolyMAC & Perte_Charge_PolyMAC::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Reimplemented in Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, and Perte_Charge_Isotrope_PolyMAC_Face.
Definition at line 38 of file Perte_Charge_PolyMAC.cpp.
const Perte_Charge_PolyMAC & Perte_Charge_PolyMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Reimplemented in Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, and Perte_Charge_Isotrope_PolyMAC_Face.
Definition at line 38 of file Perte_Charge_PolyMAC.cpp.
Member Data Documentation
Champ_Don Perte_Charge_PolyMAC::diam_hydr [protected]
Definition at line 87 of file Perte_Charge_PolyMAC.h.
Referenced by ajouter(), contribuer_a_avec(), Perte_Charge_Isotrope_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Directionnelle_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Circulaire_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Anisotrope_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Isotrope_PolyMAC_Face::readOn(), Perte_Charge_Directionnelle_PolyMAC_Face::readOn(), Perte_Charge_Circulaire_PolyMAC_Face::readOn(), and Perte_Charge_Anisotrope_PolyMAC_Face::readOn().
int Perte_Charge_PolyMAC::implicite_ [protected]
Definition at line 100 of file Perte_Charge_PolyMAC.h.
Referenced by Perte_Charge_Isotrope_PolyMAC_Face::readOn(), Perte_Charge_Directionnelle_PolyMAC_Face::readOn(), Perte_Charge_Circulaire_PolyMAC_Face::readOn(), and Perte_Charge_Anisotrope_PolyMAC_Face::readOn().
const Type_info Perte_Charge_PolyMAC::info_obj [static]
Reimplemented from Source_base.
Reimplemented in Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, and Perte_Charge_Isotrope_PolyMAC_Face.
Definition at line 47 of file Perte_Charge_PolyMAC.h.
Ref_Sous_Zone Perte_Charge_PolyMAC::la_sous_zone [protected]
Initialise dans completer()
Definition at line 99 of file Perte_Charge_PolyMAC.h.
Referenced by ajouter(), completer(), and contribuer_a_avec().
Ref_Champ_Inc_base Perte_Charge_PolyMAC::la_vitesse [protected]
Definition at line 91 of file Perte_Charge_PolyMAC.h.
Referenced by ajouter(), and associer_pb().
Ref_Zone_Cl_PolyMAC Perte_Charge_PolyMAC::la_Zone_Cl_PolyMAC [protected]
Definition at line 94 of file Perte_Charge_PolyMAC.h.
Referenced by associer_zones().
Ref_Zone_PolyMAC Perte_Charge_PolyMAC::la_Zone_PolyMAC [protected]
Definition at line 93 of file Perte_Charge_PolyMAC.h.
Referenced by ajouter(), associer_zones(), and contribuer_a_avec().
Ref_Fluide_base Perte_Charge_PolyMAC::le_fluide [protected]
Definition at line 89 of file Perte_Charge_PolyMAC.h.
Referenced by ajouter(), associer_pb(), and contribuer_a_avec().
Nom Perte_Charge_PolyMAC::nom_sous_zone [protected]
Nom de la sous-zone, initialise dans readOn()
Definition at line 98 of file Perte_Charge_PolyMAC.h.
Referenced by completer(), Perte_Charge_Isotrope_PolyMAC_Face::readOn(), Perte_Charge_Directionnelle_PolyMAC_Face::readOn(), Perte_Charge_Circulaire_PolyMAC_Face::readOn(), and Perte_Charge_Anisotrope_PolyMAC_Face::readOn().
bool Perte_Charge_PolyMAC::sous_zone [protected]
Le terme est-il limite a une sous-zone ?
Definition at line 97 of file Perte_Charge_PolyMAC.h.
Referenced by ajouter(), completer(), contribuer_a_avec(), Perte_Charge_Isotrope_PolyMAC_Face::readOn(), Perte_Charge_Directionnelle_PolyMAC_Face::readOn(), Perte_Charge_Circulaire_PolyMAC_Face::readOn(), and Perte_Charge_Anisotrope_PolyMAC_Face::readOn().
The documentation for this class was generated from the following files:
src/PolyMAC/Sources/Perte_Charge_PolyMAC.h
src/PolyMAC/Sources/Perte_Charge_PolyMAC.cpp