TRUST: Op_Dift_VEF_Face_Q1 Class Reference
Op_Dift_VEF_Face_Q1 Class Reference
class Op_Dift_VEF_FaceQ1
#include <Op_Dift_VEF_Face_Q1.h>
Public Member Functions
Op_Dift_VEF_Face_Q1 ()
~Op_Dift_VEF_Face_Q1 ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_diffusivite (const Champ_base &) override
const Champ_base & diffusivite () const override
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
double calculer_dt_stab () const override
Calcul dt_stab.
void dimensionner (Matrice_Morse &) const override
on dimensionne notre matrice.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
on assemble la matrice.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void remplir_nu (DoubleTab &) const override
Public Member Functions inherited from Op_Dift_VEF_base
Op_Dift_VEF_base ()
~Op_Dift_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void calculer_borne_locale (DoubleVect &, double, double) const override
void associer_modele_turbulence (const Mod_turb_hyd_base &)
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
Public Member Functions inherited from Op_Diff_VEF_base
Op_Diff_VEF_base ()
~Op_Diff_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
double viscA (int face_i, int face_j, int num_elem, double diffu) const
double viscA (int face_i, int face_j, int num_elem, DoubleTab &diffu) const
double viscA (int face_i, int face_j, int num_elem, ArrOfDouble &diffu_ci_cj_elem) const
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_nu (DoubleTab &) const
int phi_psi_diffuse (const Equation_base &eq) const
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Public Member Functions inherited from Op_Diff_Turbulent_base
virtual ~Op_Diff_Turbulent_base ()
void associer_diffusivite_turbulente (const Champ_Fonc &)
const Champ_Fonc & diffusivite_turbulente () const
bool has_diffusivite_turbulente () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Dift_VEF_Face_Q1 & self_cast (Objet_U &)
static const Op_Dift_VEF_Face_Q1 & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Dift_VEF_base
static const Type_info * info ()
static Op_Dift_VEF_base & self_cast (Objet_U &)
static const Op_Dift_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_VEF_base
static const Type_info * info ()
static Op_Diff_VEF_base & self_cast (Objet_U &)
static const Op_Diff_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Dift_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
Ref_Champ_Uniforme diffusivite_
Protected Attributes inherited from Op_Dift_VEF_base
Ref_Mod_turb_hyd_base le_modele_turbulence
A deplacer dans Op_Diff_turb ?
DoubleTab tau_tan_
Protected Attributes inherited from Op_Diff_VEF_base
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base inconnue_
DoubleTab nu_
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Dift_VEF_FaceQ1
Definition at line 30 of file Op_Dift_VEF_Face_Q1.h.
Constructor & Destructor Documentation
Op_Dift_VEF_Face_Q1()
Op_Dift_VEF_Face_Q1::Op_Dift_VEF_Face_Q1 ()
Definition at line 30 of file Op_Dift_VEF_Face_Q1.cpp.
~Op_Dift_VEF_Face_Q1()
Op_Dift_VEF_Face_Q1::~Op_Dift_VEF_Face_Q1 ()
Definition at line 30 of file Op_Dift_VEF_Face_Q1.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Dift_VEF_Face_Q1::ajouter (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
< nb_comp > 1
Reimplemented from Operateur_base.
Definition at line 136 of file Op_Dift_VEF_Face_Q1.cpp.
{
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const IntVect& rang_elem_non_std = zone_VEF.rang_elem_non_std();
  int i,j,num_face;
  int n1 = zone_VEF.nb_faces();
  int elem0,elem1,elem2;
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  const int nb_comp=resu.line_size();
  double valA, d_mu;
  double mu=(diffusivite_.valeur())(0,0);
  const DoubleTab& mu_turb=diffusivite_turbulente()->valeurs();
  const DoubleTab& face_normale = zone_VEF.face_normales();
  DoubleVect n(dimension);
  DoubleTrav Tgrad(dimension,dimension);
// On traite les faces bord
  if (nb_comp==1)
    for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
      {
        Debog::verifier("Op_Dift_VEF_Face_Q1::ajouter apres nb_compo= 1 nbords, resu",resu);
        const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
        const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// const IntTab& elem_faces = zone_VEF.elem_faces();
        int nb_faces_bord = le_bord.nb_faces();
        int num1=0;
        int num2=nb_faces_bord;
        if (sub_type(Periodique,la_cl.valeur()))
          {
            const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
            int fac_asso;
            for (int ind_face=num1; ind_face<num2; ind_face++)
              {
                num_face = le_bord.num_face(ind_face);
                fac_asso = le_bord.num_face(la_cl_perio.face_associee(ind_face));
                elem1 = face_voisins(num_face,0);
                d_mu = mu+mu_turb(elem1);
                for (i=0; i<nb_faces_elem; i++)
                  {
                    if ( ( (j= elem_faces(elem1,i)) > num_face ) && (j != fac_asso) )
                      {
                        valA = viscA_Q1(zone_VEF,num_face,j,dimension,elem1,d_mu);
                        resu(num_face,0)+=valA*inconnue(j,0)*porosite_face(num_face);
                        resu(num_face,0)-=valA*inconnue(num_face,0)*porosite_face(num_face);
                        resu(j,0)+=0.5*valA*inconnue(num_face,0)*porosite_face(j);
                        resu(j,0)-=0.5*valA*inconnue(j,0)*porosite_face(j);
                      }
                  }
                elem2 = face_voisins(num_face,1);
                d_mu = mu+mu_turb(elem2);
                for (i=0; i<nb_faces_elem; i++)
                  {
                    if ( ( (j= elem_faces(elem2,i)) > num_face ) && ( j != fac_asso ) )
                      {
                        valA = viscA_Q1(zone_VEF,num_face,j,dimension,elem2,d_mu);
                        resu(num_face,0)+=valA*inconnue(j,0)*porosite_face(num_face);
                        resu(num_face,0)-=valA*inconnue(num_face,0)*porosite_face(num_face);
                        resu(j,0)+=0.5*valA*inconnue(num_face,0)*porosite_face(j);
                        resu(j,0)-=0.5*valA*inconnue(j,0)*porosite_face(j);
                      }
                  }
              }
          }
        else
          for (int ind_face=num1; ind_face<num2; ind_face++)
            {
              num_face = le_bord.num_face(ind_face);
              elem1 = face_voisins(num_face,0);
              d_mu = mu+mu_turb(elem1);
              for (i=0; i<nb_faces_elem; i++)
                {
                  if ( (j= elem_faces(elem1,i)) > num_face )
                    {
                      valA = viscA_Q1(zone_VEF,num_face,j,dimension,elem1,d_mu);
                      resu(num_face,0)+=valA*inconnue(j,0)*porosite_face(num_face);
                      resu(num_face,0)-=valA*inconnue(num_face,0)*porosite_face(num_face);
                      resu(j,0)+=valA*inconnue(num_face,0)*porosite_face(j);
                      resu(j,0)-=valA*inconnue(j,0)*porosite_face(j);
                    }
                }
            }
      }
  else //!< nb_comp > 1
    for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
      {
        Debog::verifier("Op_Dift_VEF_Face_Q1::ajouter apres nb_compo> 1 nbords, resu",resu);
        const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
        const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// const IntTab& elem_faces = zone_VEF.elem_faces();
        int nb_faces_bord_tot = le_bord.nb_faces_tot();
        int nb_faces_bord = le_bord.nb_faces();
        int num1=0;
        int num2=nb_faces_bord;
        if (sub_type(Periodique,la_cl.valeur()))
          {
            const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
            int fac_asso;
            for (int ind_face=num1; ind_face<num2; ind_face++)
              {
                num_face = le_bord.num_face(ind_face);
                fac_asso = le_bord.num_face(la_cl_perio.face_associee(ind_face));
                elem1 = face_voisins(num_face,0);
                d_mu = mu+mu_turb(elem1);
                for (i=0; i<nb_faces_elem; i++)
                  {
                    if ( ( (j= elem_faces(elem1,i)) > num_face ) && (j != fac_asso ) )
                      {
                        valA = viscA_Q1(zone_VEF,num_face,j,dimension,elem1,d_mu);
                        for (int nc=0; nc<nb_comp; nc++)
{
                            resu(num_face,nc)+=valA*inconnue(j,nc)*porosite_face(num_face);
                            resu(num_face,nc)-=valA*inconnue(num_face,nc)*porosite_face(num_face);
                            resu(j,nc)+=0.5*valA*inconnue(num_face,nc)*porosite_face(j);
                            resu(j,nc)-=0.5*valA*inconnue(j,nc)*porosite_face(j);
                          }
                      }
                  }
                elem2 = face_voisins(num_face,1);
                d_mu = mu+mu_turb(elem2);
                for (i=0; i<nb_faces_elem; i++)
                  {
                    if ( ( (j= elem_faces(elem2,i)) > num_face ) && (j!= fac_asso ) )
                      {
                        valA = viscA_Q1(zone_VEF,num_face,j,dimension,elem2,d_mu);
                        for (int nc=0; nc<nb_comp; nc++)
{
                            resu(num_face,nc)+=valA*inconnue(j,nc)*porosite_face(num_face);
                            resu(num_face,nc)-=valA*inconnue(num_face,nc)*porosite_face(num_face);
                            resu(j,nc)+=0.5*valA*inconnue(num_face,nc)*porosite_face(j);
                            resu(j,nc)-=0.5*valA*inconnue(j,nc)*porosite_face(j);
                          }
                      }
                  }
              }
            Debog::verifier("Op_Dift_VEF_Face_Q1::ajouter apres periodique , resu",resu);
          }
        else if (sub_type(Dirichlet_paroi_fixe,la_cl.valeur()) ||
                 sub_type(Dirichlet_paroi_defilante,la_cl.valeur()) )
          {
            if (le_modele_turbulence.valeur().utiliser_loi_paroi())
              {
                if (dimension == 2 )
                  {
                    for (int ind_face=num1; ind_face<num2; ind_face++)
                      {
                        num_face = le_bord.num_face(ind_face);
                        int elem=face_voisins(num_face,0);
// Calcul du gradient gradU=tau*Ny*N
// Au bord, n toujours oriente vers l'exterieur
                        n[0]=face_normale(num_face,0);
                        n[1]=face_normale(num_face,1);
                        n/=norme_array(n);
                        double signe=0;
                        Tgrad(0,0)=tau_tan_(num_face,0)*n[1]*n[0];
                        Tgrad(0,1)=tau_tan_(num_face,0)*n[1]*n[1];
                        Tgrad(1,0)=-tau_tan_(num_face,0)*n[0]*n[0];
                        Tgrad(1,1)=-tau_tan_(num_face,0)*n[0]*n[1];
// On determine le sens du frottement parietal :
                        signe=0;
                        for (i=0; i<nb_faces_elem; i++)
{
                            j=elem_faces(elem,i);
// Calcul du signe de (Utan-Uparoi)*tan :
                            signe+=(inconnue(j,1)-inconnue(num_face,1))*face_normale(num_face,0)
                                   -(inconnue(j,0)-inconnue(num_face,0))*face_normale(num_face,1);
                          }
                        if (signe<0) signe=-1.;
                        else signe=1.;
// On calcule la contribution sur chaque face de l'element :
                        for (i=0; i<nb_faces_elem; i++)
{
                            j=elem_faces(elem,i);
                            double ori=1.;
                            if ( zone_VEF.face_voisins(j,0) != elem ) ori=-1;
                            if (j != num_face)
                              for (int nc=0; nc<nb_comp; nc++)
                                resu(j,nc)-=ori*signe*(Tgrad(nc,0)*face_normale(j,0)+Tgrad(nc,1)*face_normale(j,1))*porosite_face(j);
                          }
                      }
                    Debog::verifier("Op_Dift_VEF_Face_Q1::ajouter apres dirichlet dim2, resu",resu);
                  }
                else if (dimension==3)
                  {
                    for (int ind_face=num1; ind_face<num2; ind_face++)
                      {
                        num_face = le_bord.num_face(ind_face);
                        int elem=face_voisins(num_face,0);
// Calcul du gradient gradU
// Au bord, n toujours oriente vers l'exterieur
                        n[0]=face_normale(num_face,0);
                        n[1]=face_normale(num_face,1);
                        n[2]=face_normale(num_face,2);
                        n/=norme_array(n);
// Difference avec le 2D car ici tau_tan est signe !
// A tester malgre tout !
                        Tgrad(0,0)=tau_tan_(num_face,0)*n[0];
                        Tgrad(0,1)=tau_tan_(num_face,0)*n[1];
                        Tgrad(0,2)=tau_tan_(num_face,0)*n[2];
                        Tgrad(1,0)=tau_tan_(num_face,1)*n[0];
                        Tgrad(1,1)=tau_tan_(num_face,1)*n[1];
                        Tgrad(1,2)=tau_tan_(num_face,1)*n[2];
                        Tgrad(2,0)=tau_tan_(num_face,2)*n[0];
                        Tgrad(2,1)=tau_tan_(num_face,2)*n[1];
                        Tgrad(2,2)=tau_tan_(num_face,2)*n[2];
                        d_mu = mu+mu_turb(elem);
// On calcule la contribution sur chaque face de l'element :
                        for (i=0; i<nb_faces_elem; i++)
{
                            j=elem_faces(elem,i);
                            double ori=1.;
                            if ( zone_VEF.face_voisins(j,0) != elem ) ori=-1;
                            if (j != num_face)
                              for (int nc=0; nc<nb_comp; nc++)
                                resu(j,nc)-=ori*(Tgrad(nc,0)*face_normale(j,0)
                                                 +Tgrad(nc,1)*face_normale(j,1)
                                                 +Tgrad(nc,2)*face_normale(j,2))*porosite_face(j);
                          }
                      }
                    Debog::verifier("Op_Dift_VEF_Face_Q1::ajouter apres dirichlet dim3, resu",resu);
                  }
              }
            Debog::verifier("Op_Dift_VEF_Face_Q1::ajouter apres dirichlet (je crois), resu",resu);
          }
        else
          {
            Debog::verifier("Op_Dift_VEF_Face_Q1::ajouter avant else des bords, resu",resu);
            num1 = 0;
            num2 = nb_faces_bord_tot;
            for (int ind_face=num1; ind_face<num2; ind_face++)
              {
                num_face = le_bord.num_face(ind_face);
                int elem=face_voisins(num_face,0);
                d_mu = mu+mu_turb(elem);
// Boucle sur les faces :
                for (int ii=0; ii<nb_faces_elem; ii++)
                  {
                    j= elem_faces(elem,ii);
                    if (((j > num_face) && (ind_face<nb_faces_bord)) || ((j!=num_face) && (ind_face>=nb_faces_bord)))
                      {
                        valA = viscA_Q1(zone_VEF,num_face,j,dimension,elem,d_mu);
                        for (int nc=0; nc<nb_comp; nc++)
{
                            resu(num_face,nc)+=valA*inconnue(j,nc)*porosite_face(num_face);
                            resu(num_face,nc)-=valA*inconnue(num_face,nc)*porosite_face(num_face);
                            resu(j,nc)+=valA*inconnue(num_face,nc)*porosite_face(j);
                            resu(j,nc)-=valA*inconnue(j,nc)*porosite_face(j);
                          }
                      }
                  }
              }
            Debog::verifier("Op_Dift_VEF_Face_Q1::ajouter apres else des bords, resu",resu);
          }
      }
  Debog::verifier("Op_Dift_VEF_Face_Q1::ajouter apres bords, resu",resu);
// On traite les faces internes
  for (num_face=zone_VEF.premiere_face_int(); num_face<n1; num_face++)
    {
      for (int kk=0; kk<2; kk++)
        {
          elem0 = face_voisins(num_face,kk);
          d_mu = mu+mu_turb(elem0);
// On elimine les elements avec CL de paroi (rang>=1)
          int rang = rang_elem_non_std(elem0);
          if (rang<1)
            {
              for (i=0; i<nb_faces_elem; i++)
                {
                  if ( (j= elem_faces(elem0,i)) > num_face )
                    {
                      valA = viscA_Q1(zone_VEF,num_face,j,dimension,elem0,d_mu);
                      for (int nc=0; nc<nb_comp; nc++)
{
                          resu(num_face,nc)+=valA*inconnue(j,nc)*porosite_face(num_face);
                          resu(num_face,nc)-=valA*inconnue(num_face,nc)*porosite_face(num_face);
                          resu(j,nc)+=valA*inconnue(num_face,nc)*porosite_face(j);
                          resu(j,nc)-=valA*inconnue(j,nc)*porosite_face(j);
                        }
                    }
                }
            }
        }
    }
  Debog::verifier("Op_Dift_VEF_Face_Q1::ajouter apres interne, resu",resu);
  int nb_comp_bis = resu.line_size();
  for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            for (int comp=0; comp<nb_comp_bis; comp++)
              resu(face,comp) += la_cl_paroi.flux_impose(face-ndeb,comp)*zone_VEF.surface(face)*porosite_face(face);
        }
      else if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Echange_externe_impose& la_cl_paroi = ref_cast(Echange_externe_impose, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            for (int comp=0; comp<nb_comp_bis; comp++)
              resu(face,comp) += la_cl_paroi.h_imp(face-ndeb,comp)*(la_cl_paroi.T_ext(face-ndeb)-inconnue(face,comp))*zone_VEF.surface(face)*porosite_face(face);
        }
    }
  Debog::verifier("Op_Dift_VEF_Face_Q1::ajouter apres fin, resu",resu);
  modifier_flux(*this);
  return resu;
}
References diffusivite_, Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Echange_impose_base::h_imp(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Op_Dift_VEF_base::le_modele_turbulence, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Op_VEF_Face::modifier_flux(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), norme_array(), Front_VF::num_face(), Front_VF::num_premiere_face(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), Zone_VEF::rang_elem_non_std(), ref_cast, sub_type, Zone_VF::surface(), Echange_impose_base::T_ext(), Op_Dift_VEF_base::tau_tan_, Mod_turb_hyd_base::utiliser_loi_paroi(), Ref_Champ_Uniforme::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Mod_turb_hyd_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_Fonc::valeurs(), Debog::verifier(), viscA_Q1(), and Zone_dis_base::zone().
Referenced by calculer().
ajouter_contribution()
void Op_Dift_VEF_Face_Q1::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
Definition at line 480 of file Op_Dift_VEF_Face_Q1.cpp.
{
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const IntVect& rang_elem_non_std = zone_VEF.rang_elem_non_std();
  int i,j,kk,num_face0;
  int n1 = zone_VEF.nb_faces();
  int elem,elem1,elem2;
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  const int nb_comp = transporte.line_size();
  double valA, d_mu;
  double mu=(diffusivite_.valeur())(0,0);
  const DoubleTab& mu_turb=diffusivite_turbulente()->valeurs();
  DoubleVect n(dimension);
  DoubleTrav Tgrad(dimension,dimension);
  IntVect& tab1 = matrice.get_set_tab1();
  IntVect& tab2 = matrice.get_set_tab2();
  DoubleVect& coeff = matrice.get_set_coeff();
// On traite les faces bord
  for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// const IntTab& elem_faces = zone_VEF.elem_faces();
      int num1 = le_bord.num_premiere_face();
      int num2 = num1 + le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int fac_asso;
          for (num_face0=num1; num_face0<num2; num_face0++)
            {
              fac_asso = la_cl_perio.face_associee(num_face0-num1)+num1;
              elem1 = face_voisins(num_face0,0);
              d_mu = mu+mu_turb(elem1);
              for (i=0; i<nb_faces_elem; i++)
                {
                  if ( ( (j= elem_faces(elem1,i)) > num_face0 ) && (j != fac_asso ) )
                    {
                      valA = viscA_Q1(zone_VEF,num_face0,j,dimension,elem1,d_mu);
                      for (int nc=0; nc<nb_comp; nc++)
{
                          for (kk=tab1[num_face0*nb_comp+nc]-1; kk<tab1[num_face0*nb_comp+nc+1]-1; kk++)
{
                              if (tab2[kk]-1==num_face0*nb_comp+nc)
                                coeff(kk)+=valA*porosite_face(num_face0*nb_comp+nc);
                              if (tab2[kk]-1==j*nb_comp+nc)
                                coeff(kk)-=0.5*valA*porosite_face(j*nb_comp+nc);
                            }
                          for (kk=tab1[j*nb_comp+nc]-1; kk<tab1[j*nb_comp+nc+1]-1; kk++)
{
                              if (tab2[kk]-1==num_face0*nb_comp+nc)
                                coeff(kk)-=valA*porosite_face(num_face0*nb_comp+nc);
                              if (tab2[kk]-1==j*nb_comp+nc)
                                coeff(kk)+=0.5*valA*porosite_face(j*nb_comp+nc);
                            }
                        }
                    }
                }
              elem2 = face_voisins(num_face0,1);
              d_mu = mu+mu_turb(elem2);
              for (i=0; i<nb_faces_elem; i++)
                {
                  if ( ( (j= elem_faces(elem2,i)) > num_face0 ) && (j!= fac_asso ) )
                    {
                      valA = viscA_Q1(zone_VEF,num_face0,j,dimension,elem2,d_mu);
                      for (int nc=0; nc<nb_comp; nc++)
{
                          for (kk=tab1[num_face0*nb_comp+nc]-1; kk<tab1[num_face0*nb_comp+nc+1]-1; kk++)
{
                              if (tab2[kk]-1==num_face0*nb_comp+nc)
                                coeff(kk)+=valA*porosite_face(num_face0*nb_comp+nc);
                              if (tab2[kk]-1==j*nb_comp+nc)
                                coeff(kk)-=0.5*valA*porosite_face(j*nb_comp+nc);
                            }
                          for (kk=tab1[j*nb_comp+nc]-1; kk<tab1[j*nb_comp+nc+1]-1; kk++)
{
                              if (tab2[kk]-1==num_face0*nb_comp+nc)
                                coeff(kk)-=valA*porosite_face(num_face0*nb_comp+nc);
                              if (tab2[kk]-1==j*nb_comp+nc)
                                coeff(kk)+=0.5*valA*porosite_face(j*nb_comp+nc);
                            }
                        }
                    }
                }
            }
        }
      else
        for (int num_face=num1; num_face<num2; num_face++)
          {
            int elembis=face_voisins(num_face,0);
            d_mu = mu+mu_turb(elembis);
// Boucle sur les faces :
            for (int ii=0; ii<nb_faces_elem; ii++)
              if ( (j= elem_faces(elembis,ii)) > num_face )
                {
                  valA = viscA_Q1(zone_VEF,num_face,j,dimension,elembis,d_mu);
                  for (int nc=0; nc<nb_comp; nc++)
                    {
                      for (kk=tab1[num_face*nb_comp+nc]-1; kk<tab1[num_face*nb_comp+nc+1]-1; kk++)
{
                          if (tab2[kk]-1==num_face*nb_comp+nc)
                            coeff(kk)+=valA*porosite_face(num_face*nb_comp+nc);
                          if (tab2[kk]-1==j*nb_comp+nc)
                            coeff(kk)-=valA*porosite_face(j*nb_comp+nc);
                        }
                      for (kk=tab1[j*nb_comp+nc]-1; kk<tab1[j*nb_comp+nc+1]-1; kk++)
{
                          if (tab2[kk]-1==num_face*nb_comp+nc)
                            coeff(kk)-=valA*porosite_face(num_face*nb_comp+nc);
                          if (tab2[kk]-1==j*nb_comp+nc)
                            coeff(kk)+=valA*porosite_face(j*nb_comp+nc);
                        }
                    }
                }
          }
    }
// On traite les faces internes
  for (num_face0=zone_VEF.premiere_face_int(); num_face0<n1; num_face0++)
    {
      for (int ll=0; ll<2; ll++)
        {
          elem = face_voisins(num_face0,ll);
          d_mu = mu+mu_turb(elem);
// On elimine les elements avec CL de paroi (rang>=1)
          int rang = rang_elem_non_std(elem);
          if (rang<1)
            {
              for (i=0; i<nb_faces_elem; i++)
                {
                  if ( (j= elem_faces(elem,i)) > num_face0 )
                    {
                      valA = viscA_Q1(zone_VEF,num_face0,j,dimension,elem,d_mu);
                      for (int nc=0; nc<nb_comp; nc++)
{
                          for (kk=tab1[num_face0*nb_comp+nc]-1; kk<tab1[num_face0*nb_comp+nc+1]-1; kk++)
{
                              if (tab2[kk]-1==num_face0*nb_comp+nc)
                                coeff(kk) += valA*porosite_face(num_face0*nb_comp+nc);
                              if (tab2[kk]-1==j*nb_comp+nc)
                                coeff(kk) -= valA*porosite_face(j*nb_comp+nc);
                            }
                          for (kk=tab1[j*nb_comp+nc]-1; kk<tab1[j*nb_comp+nc+1]-1; kk++)
{
                              if (tab2[kk]-1==num_face0*nb_comp+nc)
                                coeff(kk) -= valA*porosite_face(num_face0*nb_comp+nc);
                              if (tab2[kk]-1==j*nb_comp+nc)
                                coeff(kk) += valA*porosite_face(j*nb_comp+nc);
                            }
                        }
                    }
                }
            }
        }
    }
}
References coeff, diffusivite_, Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), Zone_VEF::rang_elem_non_std(), ref_cast, sub_type, Ref_Champ_Uniforme::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_Fonc::valeurs(), viscA_Q1(), and Zone_dis_base::zone().
Referenced by contribuer_a_avec().
associer_diffusivite()
void Op_Dift_VEF_Face_Q1::associer_diffusivite (const Champ_base & diffu) override virtual
Implements Operateur_Diff_base.
Definition at line 49 of file Op_Dift_VEF_Face_Q1.cpp.
{
  diffusivite_ = ref_cast(Champ_Uniforme, diffu);
}
References diffusivite_, and ref_cast.
calculer()
DoubleTab & Op_Dift_VEF_Face_Q1::calculer (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 468 of file Op_Dift_VEF_Face_Q1.cpp.
{
  resu = 0;
  return ajouter(inconnue,resu);
}
References ajouter().
calculer_dt_stab()
double Op_Dift_VEF_Face_Q1::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
double
Signification: renvoie toujours 1.e30
Contraintes:
< get h_imp from datafile
< we should take the absolute value since it can be negative!
< Should we take the max if more than one bc has h_imp ?
Reimplemented from Op_Diff_VEF_base.
Definition at line 59 of file Op_Dift_VEF_Face_Q1.cpp.
{
// Calcul de dt_stab
// La diffusivite est constante par elements donc
// il faut calculer dt_diff pour chaque element et
// dt_stab=Min(dt_diff (K) = h(K)*h(K)/(2*dimension*diffu2_(K)))
// ou diffu2_ est la somme des 2 diffusivite laminaire et turbulente
  int num_face;
  double vol,surf;
  double surf_max=0;
  double dt_stab=1.e30;
  double coef;
  const Zone_VEF& la_zone_VEF = la_zone_vef.valeur();
  const DoubleVect& volumes = la_zone_VEF.volumes();
  const IntTab& elem_faces = la_zone_VEF.elem_faces();
  const DoubleTab& face_normales = la_zone_VEF.face_normales();
  const Zone& la_zone= la_zone_VEF.zone();
  int nb_faces_elem = la_zone.nb_faces_elem();
  double diffu = (diffusivite_.valeur())(0,0);
  const DoubleVect& diffu_turb=diffusivite_turbulente()->valeurs();
  double diffu2_;
  int la_zone_nb_elem=la_zone.nb_elem();
  for (int num_elem=0; num_elem<la_zone_nb_elem; num_elem++)
    {
      surf_max = 1.e-30;
      for (int i=0; i<nb_faces_elem; i++)
        {
          num_face = elem_faces(num_elem,i);
          surf = face_normales(num_face,0)*face_normales(num_face,0);
          for (int j=1; j<dimension; j++)
            surf += face_normales(num_face,j)*face_normales(num_face,j);
          surf_max = (surf > surf_max)? surf : surf_max;
        }
      vol = volumes(num_elem);
      vol *=vol/surf_max;
      diffu2_ = diffu + diffu_turb[num_elem];
      coef=vol/(2.*dimension*(diffu2_+DMINFLOAT));
      dt_stab = (coef < dt_stab )? coef : dt_stab;
    }
  return Process::mp_min(dt_stab);
}
References diffusivite_, Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, DMINFLOAT, Zone_VF::elem_faces(), Zone_VEF::face_normales(), Op_Diff_VEF_base::la_zone_vef, Process::mp_min(), Zone::nb_elem(), Zone::nb_faces_elem(), Ref_Champ_Uniforme::valeur(), Ref_Zone_VEF::valeur(), Champ_Fonc::valeurs(), Zone_VF::volumes(), and Zone_dis_base::zone().
contribue_au_second_membre()
void Op_Dift_VEF_Face_Q1::contribue_au_second_membre (DoubleTab & resu) const
Definition at line 648 of file Op_Dift_VEF_Face_Q1.cpp.
{
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  int elem,i,j;
  const int nb_comp = resu.line_size();
  const DoubleTab& face_normale = zone_VEF.face_normales();
  DoubleVect n(dimension);
  DoubleTrav Tgrad(dimension,dimension);
// On traite les faces bord
  if (nb_comp!=1)
    {
      for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          const IntTab& elem_faces = zone_VEF.elem_faces();
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          if (sub_type(Dirichlet_paroi_fixe,la_cl.valeur()) ||
              sub_type(Dirichlet_paroi_defilante,la_cl.valeur()) )
            {
              if (dimension == 2 )
                {
                  for (int num_face=num1; num_face<num2; num_face++)
                    {
                      int elembis=face_voisins(num_face,0);
// Calcul du gradient gradU=tau*Ny*N
// Au bord, n toujours oriente vers l'exterieur
                      n[0]=face_normale(num_face,0);
                      n[1]=face_normale(num_face,1);
                      n/=norme_array(n);
                      double signe=0;
                      Tgrad(0,0)=tau_tan_(num_face,0)*n[1]*n[0];
                      Tgrad(0,1)=tau_tan_(num_face,0)*n[1]*n[1];
                      Tgrad(1,0)=-tau_tan_(num_face,0)*n[0]*n[0];
                      Tgrad(1,1)=-tau_tan_(num_face,0)*n[0]*n[1];
// On determine le sens du frottement parietal :
                      signe=0;
                      for (i=0; i<nb_faces_elem; i++)
{
                          j=elem_faces(elembis,i);
// Calcul du signe de (Utan-Uparoi)*tan :
                          signe+=(inconnue_->valeurs()(j,1)-inconnue_->valeurs()(num_face,1))*face_normale(num_face,0)
                                 -(inconnue_->valeurs()(j,0)-inconnue_->valeurs()(num_face,0))*face_normale(num_face,1);
                        }
                      if (signe<0) signe=-1.;
                      else signe=1.;
// On calcule la contribution sur chaque face de l'element :
                      for (i=0; i<nb_faces_elem; i++)
{
                          j=elem_faces(elembis,i);
                          double ori=1.;
                          if ( zone_VEF.face_voisins(j,0) != elembis ) ori=-1;
                          if (j != num_face)
                            for (int nc=0; nc<nb_comp; nc++)
                              resu(j,nc)-=ori*signe*(Tgrad(nc,0)*face_normale(j,0)+Tgrad(nc,1)*face_normale(j,1));
                        }
                    }
                }
              else if (dimension==3)
                {
                  for (int num_face=num1; num_face<num2; num_face++)
                    {
                      elem=face_voisins(num_face,0);
// Calcul du gradient gradU
// Au bord, n toujours oriente vers l'exterieur
                      n[0]=face_normale(num_face,0);
                      n[1]=face_normale(num_face,1);
                      n[2]=face_normale(num_face,2);
                      n/=norme_array(n);
// Difference avec le 2D car ici tau_tan est signe !
// A tester malgre tout !
                      Tgrad(0,0)=tau_tan_(num_face,0)*n[0];
                      Tgrad(0,1)=tau_tan_(num_face,0)*n[1];
                      Tgrad(0,2)=tau_tan_(num_face,0)*n[2];
                      Tgrad(1,0)=tau_tan_(num_face,1)*n[0];
                      Tgrad(1,1)=tau_tan_(num_face,1)*n[1];
                      Tgrad(1,2)=tau_tan_(num_face,1)*n[2];
                      Tgrad(2,0)=tau_tan_(num_face,2)*n[0];
                      Tgrad(2,1)=tau_tan_(num_face,2)*n[1];
                      Tgrad(2,2)=tau_tan_(num_face,2)*n[2];
// On calcule la contribution sur chaque face de l'element :
                      for (i=0; i<nb_faces_elem; i++)
{
                          j=elem_faces(elem,i);
                          double ori=1.;
                          if ( zone_VEF.face_voisins(j,0) != elem ) ori=-1;
                          if (j != num_face)
                            for (int nc=0; nc<nb_comp; nc++)
                              resu(j,nc)-=ori*(Tgrad(nc,0)*face_normale(j,0)
                                               +Tgrad(nc,1)*face_normale(j,1)
                                               +Tgrad(nc,2)*face_normale(j,2));
                        }
                    }
                }
            }
        }
    }
  for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            for (int comp=0; comp<nb_comp; comp++)
              resu(face,comp) += la_cl_paroi.flux_impose(face-ndeb,comp)*zone_VEF.surface(face);
        }
      else if ( nb_comp == 1 && sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          Cerr << "Non code pour Echange_externe_impose" << finl;
          assert(0);
        }
    }
}
References Cerr, Objet_U::dimension, Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), finl, Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::inconnue_, Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Front_VF::nb_faces(), Zone::nb_faces_elem(), Zone_dis_base::nb_front_Cl(), norme_array(), Front_VF::num_premiere_face(), ref_cast, sub_type, Zone_VF::surface(), Op_Dift_VEF_base::tau_tan_, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc_base::valeurs(), and Zone_dis_base::zone().
Referenced by contribuer_au_second_membre().
contribuer_a_avec()
void Op_Dift_VEF_Face_Q1::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
on assemble la matrice.
Reimplemented from Operateur_base.
Definition at line 79 of file Op_Dift_VEF_Face_Q1.h.
{
  ajouter_contribution(inco, matrice);
}
References ajouter_contribution().
contribuer_au_second_membre()
void Op_Dift_VEF_Face_Q1::contribuer_au_second_membre (DoubleTab & resu) const inline override virtual
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
Definition at line 88 of file Op_Dift_VEF_Face_Q1.h.
{
  contribue_au_second_membre(resu);
}
References contribue_au_second_membre().
cree_instance()
Objet_U * Op_Dift_VEF_Face_Q1::cree_instance () static
Definition at line 30 of file Op_Dift_VEF_Face_Q1.cpp.
diffusivite()
const Champ_base & Op_Dift_VEF_Face_Q1::diffusivite () const override virtual
Implements Operateur_Diff_base.
Definition at line 54 of file Op_Dift_VEF_Face_Q1.cpp.
{
  return diffusivite_.valeur();
}
References diffusivite_, and Ref_Champ_Uniforme::valeur().
dimensionner()
void Op_Dift_VEF_Face_Q1::dimensionner (Matrice_Morse & matrice) const inline override virtual
on dimensionne notre matrice.
Reimplemented from Operateur_base.
Definition at line 65 of file Op_Dift_VEF_Face_Q1.h.
{
  Op_VEF_Face::dimensionner(la_zone_vef.valeur(), la_zcl_vef.valeur(), matrice);
}
References Op_VEF_Face::dimensionner(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
duplique()
int Op_Dift_VEF_Face_Q1::duplique () const override virtual
Implements Objet_U.
Definition at line 30 of file Op_Dift_VEF_Face_Q1.cpp.
get_info()
const Type_info * Op_Dift_VEF_Face_Q1::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Dift_VEF_base.
Definition at line 30 of file Op_Dift_VEF_Face_Q1.cpp.
info()
const Type_info * Op_Dift_VEF_Face_Q1::info () static
Definition at line 30 of file Op_Dift_VEF_Face_Q1.cpp.
modifier_pour_Cl()
void Op_Dift_VEF_Face_Q1::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 70 of file Op_Dift_VEF_Face_Q1.h.
{
  Op_VEF_Face::modifier_pour_Cl(la_zone_vef.valeur(),la_zcl_vef.valeur(), matrice, secmem);
}
References Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Op_VEF_Face::modifier_pour_Cl(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
printOn()
Sortie & Op_Dift_VEF_Face_Q1::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Dift_VEF_base.
Definition at line 35 of file Op_Dift_VEF_Face_Q1.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Dift_VEF_Face_Q1::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Dift_VEF_base.
Definition at line 43 of file Op_Dift_VEF_Face_Q1.cpp.
{
  return s ;
}
remplir_nu()
void Op_Dift_VEF_Face_Q1::remplir_nu (DoubleTab &) const inline override virtual
Reimplemented from Op_Diff_VEF_base.
Definition at line 52 of file Op_Dift_VEF_Face_Q1.h.
  {
    Cerr<<__FILE__<<":"<<(int)__LINE__<<finl;
    exit();
  } ;
References Cerr, Process::exit(), and finl.
self_cast() [1/2]
const Op_Dift_VEF_Face_Q1 & Op_Dift_VEF_Face_Q1::self_cast (const Objet_U & r) static
Definition at line 30 of file Op_Dift_VEF_Face_Q1.cpp.
self_cast() [2/2]
Op_Dift_VEF_Face_Q1 & Op_Dift_VEF_Face_Q1::self_cast (Objet_U & r) static
Definition at line 30 of file Op_Dift_VEF_Face_Q1.cpp.
taille_memoire()
unsigned Op_Dift_VEF_Face_Q1::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 30 of file Op_Dift_VEF_Face_Q1.cpp.
Member Data Documentation
diffusivite_
Ref_Champ_Uniforme Op_Dift_VEF_Face_Q1::diffusivite_ protected
Definition at line 60 of file Op_Dift_VEF_Face_Q1.h.
Referenced by ajouter(), ajouter_contribution(), associer_diffusivite(), calculer_dt_stab(), and diffusivite().
info_obj
const Type_info Op_Dift_VEF_Face_Q1::info_obj static
Definition at line 32 of file Op_Dift_VEF_Face_Q1.h.
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Dift_VEF_Face_Q1.h
src/VEF/Operateurs/Op_Dift_VEF_Face_Q1.cpp