TRUST: IntList Class Reference
IntList Class Reference
Classe qui sert a representer une liste de reels int
precision. On ne peut pas utiliser la classe container
List avec des objets du type int car int est un type
predefini du C++ qui ne possede pas les fonctions exigees
par List< >.
#include <IntList.h>
Public Member Functions
IntList (const IntList &)
Constructeur par copie.
IntList ()
Construit une liste vide.
Sortie & printOn (Sortie &os) const
Ecriture d'une liste sur un flot de sortie
les elements separes par des virgules figurent entre des accolades.
Entree & readOn (Entree &is)
Lecture d'une liste sur un flot d'entree
les elements separes par des virgules figurent entre des accolades.
int size () const
Renvoie la taille de la liste
Une liste vide est de taille nulle.
int contient (int) const
Verifie si un element appartient ou non a la liste.
int rang (int) const
renvoie le rang d'un element dans la liste
si un element apparait plusieurs fois, renvoie le rang du premier.
IntListElem & dernier ()
Renvoie le dernier element de la liste.
const IntListElem & dernier () const
Renvoie le dernier element de la liste.
int & operator[] (int)
Operateur d'acces au ieme int de la liste.
const int & operator[] (int) const
Operateur d'acces au ieme int de la liste.
IntList & add (int)
insertion en queue
IntList & add_if_not (int)
Ajout d'un element a la liste ssi il n'existe pas deja.
IntList & operator= (const IntList &)
Affectation
Les elements sont copies.
void suppr (int)
Supprime un element contenu dans la liste.
void vide ()
Vide la liste.
void calcule_min_max ()
Private Attributes
IntListElem * dernier_
int min_data
int max_data
Friends
class IntList_Curseur
int operator== (const IntList &, const IntList &)
Operateur de comparaison de deux listes.
Detailed Description
Classe qui sert a representer une liste de reels int
precision. On ne peut pas utiliser la classe container
List avec des objets du type int car int est un type
predefini du C++ qui ne possede pas les fonctions exigees
par List< >.
Definition at line 45 of file IntList.h.
Constructor & Destructor Documentation
IntList::IntList (const IntList & a_list)
Constructeur par copie.
Definition at line 114 of file IntList.cpp.
References IntListElem::data, dernier_, IntListElem::est_vide(), IntListElem::IntListElem(), max_data, min_data, next(), and IntListElem::suivant_.
                                      : IntListElem()
{
  min_data=a_list.min_data;
  max_data=a_list.max_data;
  if(a_list.est_vide() )
    {
      suivant_=this;
    }
  else
    {
      data=a_list.data;
      dernier_=this;
      if(a_list.suivant_)
        {
          IntListElem* next = new IntListElem(*a_list.suivant_); //Recursif !!
          suivant_ = next;
        }
      else
        suivant_ =0;
    }
}
IntList::IntList () [inline]
Construit une liste vide.
Definition at line 116 of file IntList.h.
References dernier_.
                        :
  IntListElem(),min_data(IMAX),max_data(-IMAX)
{
  dernier_=this;
}
Member Function Documentation
IntList & IntList::add (int int_to_add)
insertion en queue
Returns:
IntList&
Signification: *this
Contraintes:
Reimplemented from IntListElem.
Definition at line 236 of file IntList.cpp.
References IntListElem::add(), IntListElem::data, dernier(), dernier_, IntListElem::est_dernier(), IntListElem::est_vide(), IntListElem::IntListElem(), max_data, min_data, next(), IntListElem::suivant(), and IntListElem::suivant_.
Referenced by add_if_not(), Remove_elem::lire_motcle_non_standard(), operator=(), readOn(), Op_Diff_VEF_Face_Penalise::reduction(), and Op_Diff_VEF_Face_Penalise::signe().
{
  if (int_to_add<min_data)
    min_data=int_to_add;
  if (int_to_add>max_data)
    max_data=int_to_add;
  if( est_vide())
    {
      data=int_to_add;
      suivant_=0;
      return *this;
    }
  else
    {
      if(est_dernier())
        {
          IntListElem* next=new IntListElem(int_to_add);
          suivant_ = next;
          dernier_ = next;
        }
      else
        {
          dernier().add(int_to_add);
          dernier_ = &dernier_->suivant();
        }
      return *this;
    }
}
IntList & IntList::add_if_not (int x)
Ajout d'un element a la liste ssi il n'existe pas deja.
Returns:
IntList&
Signification: *this
Contraintes:
Definition at line 308 of file IntList.cpp.
References add(), and contient().
Referenced by Polygone::affecte_connectivite_numero_global(), Polyedre::affecte_connectivite_numero_global(), Op_Rot_VEFP1B::ajouter(), Op_Diff_RotRot::elements_pour_sommet(), ExtrudeParoi::extrude(), Op_Diff_VEF_Face_Penalise::faces_communes(), Champ_front_recyclage::initialiser(), Op_Diff_RotRot::sommets_pour_element(), Op_Diff_RotRot::sommets_voisins(), Op_Diff_RotRot::Tri(), and Op_Diff_VEF_Face_Penalise::voisinage().
{
  if (!contient(x))
    return add(x);
  else
    return *this;
}
void IntList::calcule_min_max ()
Definition at line 522 of file IntList.cpp.
References IMAX, max_data, min_data, and IntList_Curseur::valeur().
Referenced by suppr(), and vide().
{
  min_data=IMAX;
  max_data=-IMAX;
  IntList_Curseur curseur=*this;
  while(curseur)
    {
      int la_valeur=curseur.valeur();
      if (la_valeur<min_data)
        min_data=la_valeur;
      if (la_valeur>max_data)
        max_data=la_valeur;
      ++curseur;
    }
}
int IntList::contient (int x) const
Verifie si un element appartient ou non a la liste.
Returns:
int
Signification: 1 si la liste contient l'element, 0 sinon
Contraintes:
Definition at line 331 of file IntList.cpp.
References IntListElem::est_vide(), max_data, min_data, and IntList_Curseur::valeur().
Referenced by add_if_not(), Op_Diff_VEF_Face_Penalise::faces_communes(), Op_Diff_VEF_Face_Penalise::reduction(), Op_Diff_RotRot::remplir_som_som_EF(), and Op_Diff_VEF_Face_Penalise::signe().
{
  if(est_vide() || x>max_data || x<min_data)
    return 0;
  IntList_Curseur curseur(*this);
  while(curseur)
    {
      if (curseur.valeur()==x)
        return 1;
      ++curseur;
    }
  return 0;
}
const IntListElem & IntList::dernier () const
Renvoie le dernier element de la liste.
Returns:
const IntList&
Signification: le dernier element de la liste
Contraintes:
Definition at line 184 of file IntList.cpp.
References dernier_.
{
  return *dernier_;
  /*  if (est_dernier()) return *this;
      IntList_Curseur curseur(*this);
      while(curseur)
      if (curseur.list().est_dernier()) break;
      else ++curseur;
      return curseur.list(); */
}
IntListElem & IntList::dernier ()
Renvoie le dernier element de la liste.
Returns:
IntList&
Signification: le dernier element de la liste
Contraintes:
Definition at line 209 of file IntList.cpp.
References dernier_.
Referenced by add().
{
  return *dernier_;
  /*
    if (est_dernier()) return *this;
    IntList_Curseur curseur(*this);
    while(curseur)
    if (curseur.list().est_dernier()) break;
    else ++curseur;
    return curseur.list();
  */
}
IntList & IntList::operator= (const IntList & a_list)
Affectation
Les elements sont copies.
Returns:
IntList&
Signification: *this
Contraintes:
Definition at line 151 of file IntList.cpp.
References add(), IntListElem::est_vide(), IntListElem::suivant_, IntList_Curseur::valeur(), and vide().
{
  if(a_list.est_vide())
    {
      suivant_=this;
    }
  else
    {
      vide();
      IntList_Curseur curseur(a_list);
      while(curseur)
        {
          add(curseur.valeur());
          ++curseur;
        }
    }
  return *this;
}
const int & IntList::operator[] (int i) const
Operateur d'acces au ieme int de la liste.
Returns:
const int&
Signification: le ieme element de la liste
Contraintes:
Definition at line 419 of file IntList.cpp.
References Cerr, Process::exit(), finl, and IntList_Curseur::valeur().
{
  IntList_Curseur curseur(*this);
  while(curseur && i--)
    ++curseur;
  if(i!=-1)
    {
      Cerr << "Overflow list " << finl;
      Process::exit();
    }
  return curseur.valeur();
}
int & IntList::operator[] (int i)
Operateur d'acces au ieme int de la liste.
Returns:
int&
Signification: le ieme element de la liste
Contraintes:
Definition at line 392 of file IntList.cpp.
References Cerr, Process::exit(), finl, and IntList_Curseur::valeur().
{
  IntList_Curseur curseur(*this);
  while(curseur && i--)
    ++curseur;
  if(i!=-1)
    {
      Cerr << "Overflow list " << finl;
      Process::exit();
    }
  return curseur.valeur();
}
Sortie & IntList::printOn (Sortie & os) const
Ecriture d'une liste sur un flot de sortie
les elements separes par des virgules figurent entre des accolades.
Returns:
Sortie&
Signification: le flot d'entree modifie
Contraintes:
Definition at line 44 of file IntList.cpp.
References IntListElem::est_dernier(), IntList_Curseur::list(), and IntList_Curseur::valeur().
Referenced by IntLists::printOn().
{
  IntList_Curseur curseur(*this);
  Nom accouverte = "{";
  Nom accfermee = "}";
  Nom virgule = ",";
  os << accouverte << " " ;
  while(curseur)
    {
// if(est_dernier()) GF sinon on a une virgule de trop
      if(curseur.list().est_dernier())
        os << curseur.valeur() << " " ;
      else
        os << curseur.valeur() << " " << virgule << " " ;
      ++curseur;
    }
  os << accfermee;
  return os;
}
int IntList::rang (int x) const
renvoie le rang d'un element dans la liste
si un element apparait plusieurs fois, renvoie le rang du premier.
Returns:
int
Signification: le rang du premier element de la liste valant i,
-1 si la liste ne contient pas i.
Contraintes:
Definition at line 362 of file IntList.cpp.
References compteur, IntListElem::est_vide(), max_data, min_data, and IntList_Curseur::valeur().
Referenced by ExtrudeParoi::extrude().
{
  if(est_vide() || x>max_data || x<min_data)
    return -1;
  int compteur=0;
  IntList_Curseur curseur(*this);
  while(curseur)
    {
      if (curseur.valeur()==x)
        return compteur;
      ++compteur;
      ++curseur;
    }
  return -1;
}
Entree & IntList::readOn (Entree & is)
Lecture d'une liste sur un flot d'entree
les elements separes par des virgules figurent entre des accolades.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Definition at line 81 of file IntList.cpp.
References add().
{
  Nom accouverte = "{";
  Nom accfermee = "}";
  Nom virgule = ",";
  Nom nom;
  int t;
  is >> nom;
  assert(nom==accouverte);
  while(nom != accfermee)
    {
      is >> t;
      add(t);
      is >> nom;
      assert((nom==accfermee)||(nom==virgule));
    }
  return is ;
}
int IntList::size () const
Renvoie la taille de la liste
Une liste vide est de taille nulle.
Returns:
int
Signification: nombre d'elements de la liste
Contraintes:
Definition at line 280 of file IntList.cpp.
References IntListElem::est_vide().
Referenced by Polygone::affecte_connectivite_numero_global(), Polyedre::affecte_connectivite_numero_global(), Op_Diff_VEF_Face_Penalise::ajouter(), Op_Rot_VEFP1B::ajouter(), Op_Diff_RotRot::assembler_matrice(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), ExtrudeParoi::extrude(), Op_Diff_VEF_Face_Penalise::faces_communes(), Zone::identifie_item_unique(), Op_Diff_VEF_Face_Penalise::reduction(), Remove_elem::Remove_elem_(), Op_Diff_RotRot::remplir_som_som_EF(), Op_Diff_RotRot::sommets_voisins(), Op_Diff_RotRot::Tri(), and Op_Diff_VEF_Face_Penalise::voisinage().
{
  if(est_vide())
    return 0;
  int i=0;
  IntList_Curseur curseur(*this);
  while(curseur)
    {
      ++i;
      ++curseur;
    }
  return i;
}
void IntList::suppr (int obj)
Supprime un element contenu dans la liste.
Definition at line 479 of file IntList.cpp.
References calcule_min_max(), Cerr, IntListElem::data, dernier_, finl, IntList_Curseur::list(), next(), IntListElem::suivant(), IntListElem::suivant_, IntList_Curseur::valeur(), and IntListElem::valeur().
Referenced by Zone::identifie_item_unique(), Op_Diff_VEF_Face_Penalise::reduction(), and Op_Diff_RotRot::Tri().
{
  if(valeur()==obj)
    {
      if(suivant_)
        {
          IntListElem* next=suivant_;
          suivant_=next->suivant_;
          data=next->valeur();
          next->suivant_=0;
          delete next;
        }
      else
        {
          suivant_=this;
          dernier_=this;
        }
      calcule_min_max();
      return;
    }
  IntList_Curseur curseur_pre=*this;
  IntList_Curseur curseur=*suivant_;
  while(curseur)
    {
      if(curseur.valeur()==obj)
        {
          IntListElem* next=&curseur_pre.list().suivant();
          curseur_pre.list().suivant_=curseur.list().suivant_;
          if (next->suivant_==0)
            dernier_=&curseur_pre.list();
          else
            next->suivant_=0;
          delete next;
          calcule_min_max();
          return ;
        }
      ++curseur;
      ++curseur_pre;
    }
  Cerr << "WARNING during deletion of an element in a list " << finl;
  Cerr << "One has not found object == : " << obj << finl;
}
void IntList::vide ()
Vide la liste.
Definition at line 552 of file IntList.cpp.
References calcule_min_max(), dernier_, IntListElem::est_vide(), and IntListElem::suivant_.
Referenced by Polygone::affecte_connectivite_numero_global(), Polyedre::affecte_connectivite_numero_global(), Op_Rot_VEFP1B::ajouter(), Op_Diff_RotRot::elements_pour_sommet(), Op_Diff_VEF_Face_Penalise::faces_communes(), operator=(), Op_Diff_VEF_Face_Penalise::reduction(), Op_Diff_RotRot::sommets_pour_element(), and Op_Diff_VEF_Face_Penalise::voisinage().
{
  if (!est_vide())
    if(suivant_)
      delete suivant_;
  suivant_=this;
  dernier_=this;
  calcule_min_max();
}
Friends And Related Function Documentation
friend class IntList_Curseur [friend]
Definition at line 49 of file IntList.h.
int operator== (const IntList & list1, const IntList & list2) [friend]
Operateur de comparaison de deux listes.
Returns:
int
Signification: 1 si les listes sont egales, 0 sinon
Contraintes:
Definition at line 451 of file IntList.cpp.
{
  int retour=1;
  if(list1.data != list2.data)
    retour= 0;
  if( (!list1.est_dernier()) && (list2.est_dernier()) )
    retour= 0;
  if( (list1.est_dernier()) && (!list2.est_dernier()) )
    retour= 0;
  if( (!list1.est_dernier()) && (!list2.est_dernier()) )
    retour= (*list1.suivant_ == *list2.suivant_);
  return retour;
}
Member Data Documentation
IntListElem* IntList::dernier_ [private]
Definition at line 73 of file IntList.h.
Referenced by add(), dernier(), IntList(), suppr(), and vide().
int IntList::max_data [private]
Definition at line 75 of file IntList.h.
Referenced by add(), calcule_min_max(), contient(), IntList(), and rang().
int IntList::min_data [private]
Definition at line 74 of file IntList.h.
Referenced by add(), calcule_min_max(), contient(), IntList(), and rang().
The documentation for this class was generated from the following files:
src/Kernel/Math/IntList.h
src/Kernel/Math/IntList.cpp