TRUST: Terme_Source_Solide_SWIFT_VDF Class Reference
Terme_Source_Solide_SWIFT_VDF Class Reference
#include <Terme_Source_Solide_SWIFT_VDF.h>
Public Member Functions
Terme_Source_Solide_SWIFT_VDF ()
~Terme_Source_Solide_SWIFT_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & calculer (DoubleTab &) const override
void init_calcul_moyenne (const Conduction &my_eqn, DoubleVect &Y, IntVect &corresp, IntVect &compt)
void calcul_moyenne (const Conduction &my_eqn, DoubleVect &T_moy, const IntVect &corresp, const IntVect &compt) const
void correspondance_SWIFT_coarse ()
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void associer_pb (const Probleme_base &) override
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) const override
int has_interface_blocs () const override
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Terme_Source_Solide_SWIFT_VDF & self_cast (Objet_U &)
static const Terme_Source_Solide_SWIFT_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Probleme_base pb_swift
Ref_Probleme_base pb_corse
Ref_Conduction eq_swift
Ref_Conduction eq_corse
double tau
tau est la constante de temps du forcage.
DoubleVect Y_swift
Coordonnees des points ou est definie la temperature dans le solide.
DoubleVect Y_corse
ou doit etre fait le forcage.
IntVect compt_swift
Nombre de points a meme Y.
IntVect compt_corse
IntVect corresp_swift
Correspondance numerotation globale -> numerotation locale dans Y.
IntVect corresp_corse
IntVect corresp_SC
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 37 of file Terme_Source_Solide_SWIFT_VDF.h.
Constructor & Destructor Documentation
Terme_Source_Solide_SWIFT_VDF()
Terme_Source_Solide_SWIFT_VDF::Terme_Source_Solide_SWIFT_VDF ()
Definition at line 25 of file Terme_Source_Solide_SWIFT_VDF.cpp.
~Terme_Source_Solide_SWIFT_VDF()
Terme_Source_Solide_SWIFT_VDF::~Terme_Source_Solide_SWIFT_VDF ()
Definition at line 25 of file Terme_Source_Solide_SWIFT_VDF.cpp.
Member Function Documentation
ajouter_blocs()
void Terme_Source_Solide_SWIFT_VDF::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
< Profils de temperature moyenne.
Reimplemented from Source_base.
Definition at line 289 of file Terme_Source_Solide_SWIFT_VDF.cpp.
{
  const Zone_dis_base& zdisbase = eq_swift->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF      = ref_cast(Zone_VDF, zdisbase);
  int nb_elems                   = zone_VDF.nb_elem();
  const DoubleVect& volume         = zone_VDF.volumes();
  DoubleVect Tmoy_swift;        //!< Profils de temperature moyenne.
  DoubleVect Tmoy_corse;
  /*  const Champ_base& rho_don = pb_swift->milieu().masse_volumique();
      const Champ_Don& Cp_don  = pb_swift->milieu().capacite_calorifique();
      double rho=1.,Cp=1.;
      if (sub_type(Champ_Uniforme,rho_don.valeur()))  rho = rho_don(0,0);
      else
      {
      Cerr << "### Rho is not uniform in the solid !" << finl;
      Cerr << "### Problem in Terme_Source_Solide_SWIFT_VDF..." << finl;
      exit();
      }
      if (sub_type(Champ_Uniforme,Cp_don.valeur()))  Cp = Cp_don(0,0);
      else
      {
      Cerr << "### Cp is not uniform in the solid !" << finl;
      Cerr << "### Problem in Terme_Source_Solide_SWIFT_VDF..." << finl;
      exit();
      }
      Cerr << "Rho = " << rho << finl;
      Cerr << "Cp = " << Cp << finl; */
// On calcule les profils de temperature moyenne dans les deux solides.
  calcul_moyenne(eq_swift.valeur(),Tmoy_swift,corresp_swift,compt_swift);
  calcul_moyenne(eq_corse.valeur(),Tmoy_corse,corresp_corse,compt_corse);
  for(int num_elem = 0 ; num_elem<nb_elems ; num_elem++)
    {
      resu(num_elem) += volume(num_elem)*(Tmoy_corse(corresp_SC[corresp_swift[num_elem]])-Tmoy_swift(corresp_swift[num_elem]))/tau;
    }
}
References calcul_moyenne(), compt_corse, compt_swift, corresp_corse, corresp_SC, corresp_swift, eq_corse, eq_swift, Conduction::inconnue(), Zone_dis_base::nb_elem(), ref_cast, tau, Ref_Conduction::valeur(), Zone_VF::volumes(), and Champ_Inc::zone_dis_base().
associer_pb()
void Terme_Source_Solide_SWIFT_VDF::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Definition at line 152 of file Terme_Source_Solide_SWIFT_VDF.cpp.
{
  ;
}
associer_zones()
void Terme_Source_Solide_SWIFT_VDF::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override virtual
Implements Source_base.
Definition at line 144 of file Terme_Source_Solide_SWIFT_VDF.cpp.
{
  /*    la_zone_VDF = ref_cast(Zone_VDF, zone_dis.valeur());
        la_zone_Cl_VDF = ref_cast(Zone_Cl_VDF, zone_Cl_dis.valeur()) */
  ;
}
calcul_moyenne()
void Terme_Source_Solide_SWIFT_VDF::calcul_moyenne (const Conduction & my_eqn, DoubleVect & T_moy, const IntVect & corresp, const IntVect & compt) const
Definition at line 260 of file Terme_Source_Solide_SWIFT_VDF.cpp.
{
  const Zone_dis_base& zdisbase = my_eqn.inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF      = ref_cast(Zone_VDF, zdisbase);
  const DoubleTab& Temp         = my_eqn.inconnue().valeurs();
  int nb_elems   = zone_VDF.zone().nb_elem();
  int nb_faces_x = zone_VDF.nb_faces_X();
  int nb_faces_z = zone_VDF.nb_faces_Z();
  int Nx        = nb_elems/(nb_faces_x-nb_elems);
  int Nz        = nb_elems/(nb_faces_z-nb_elems);
  int Ny        = nb_elems/Nx/Nz;
  int j=0;
  T_moy.resize(Ny);
  T_moy = 0.;
  for (j=0; j<nb_elems; j++)  T_moy[corresp[j]] += Temp[j];
  for (j=0; j<Ny; j++)  T_moy[j] /= compt[j];
}
References Conduction::inconnue(), Zone::nb_elem(), Zone_VDF::nb_faces_X(), Zone_VDF::nb_faces_Z(), ref_cast, TRUSTVect< _TYPE_ >::resize(), Champ_Inc::valeurs(), Zone_dis_base::zone(), and Champ_Inc::zone_dis_base().
Referenced by ajouter_blocs().
calculer()
DoubleTab & Terme_Source_Solide_SWIFT_VDF::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 341 of file Terme_Source_Solide_SWIFT_VDF.cpp.
{
  resu = 0;
  return ajouter(resu);
}
References Source_base::ajouter().
correspondance_SWIFT_coarse()
void Terme_Source_Solide_SWIFT_VDF::correspondance_SWIFT_coarse ()
Definition at line 226 of file Terme_Source_Solide_SWIFT_VDF.cpp.
{
  int t_S = Y_swift.size();
  int t_C = Y_corse.size();
  corresp_SC.resize(t_S);
  for(int j=0; j<t_S; j++)
    {
      int burk=1;
      for(int i=0; i<t_C; i++)
        {
          if(std::fabs(Y_swift[j]-Y_corse[i])<=1e-8)
            {
              burk=0;
              corresp_SC[j]=i;
            }
        }
      if(burk)
        {
          Cerr << "## ACHTUNG !!! On n'a pas trouve l'equivalence entre" << finl;
          Cerr << "## les deux domaines au niveau des Y !" << finl;
        }
    }
}
References Cerr, corresp_SC, finl, TRUSTVect< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), Y_corse, and Y_swift.
Referenced by readOn().
cree_instance()
Objet_U * Terme_Source_Solide_SWIFT_VDF::cree_instance () static
Definition at line 25 of file Terme_Source_Solide_SWIFT_VDF.cpp.
dimensionner_blocs()
void Terme_Source_Solide_SWIFT_VDF::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
Definition at line 51 of file Terme_Source_Solide_SWIFT_VDF.h.
{}
duplique()
int Terme_Source_Solide_SWIFT_VDF::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file Terme_Source_Solide_SWIFT_VDF.cpp.
get_info()
const Type_info * Terme_Source_Solide_SWIFT_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 25 of file Terme_Source_Solide_SWIFT_VDF.cpp.
has_interface_blocs()
int Terme_Source_Solide_SWIFT_VDF::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Definition at line 53 of file Terme_Source_Solide_SWIFT_VDF.h.
  {
    return 1;
  };
info()
const Type_info * Terme_Source_Solide_SWIFT_VDF::info () static
Definition at line 25 of file Terme_Source_Solide_SWIFT_VDF.cpp.
init_calcul_moyenne()
void Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne (const Conduction & my_eqn, DoubleVect & Y, IntVect & corresp, IntVect & compt)
Definition at line 165 of file Terme_Source_Solide_SWIFT_VDF.cpp.
{
  int num_elem,j,indic,trouve;
  double y;
  const Zone_dis_base& zdisbase = my_eqn.inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF      = ref_cast(Zone_VDF, zdisbase);
  const DoubleTab& xp           = zone_VDF.xp();
  int nb_elems   = zone_VDF.zone().nb_elem();
  int nb_faces_x = zone_VDF.nb_faces_X();
  int nb_faces_z = zone_VDF.nb_faces_Z();
  int Nx        = nb_elems/(nb_faces_x-nb_elems);
  int Nz        = nb_elems/(nb_faces_z-nb_elems);
  int Ny        = nb_elems/Nx/Nz;
  Y.resize(Ny);
  compt.resize(Ny);
  corresp.resize(nb_elems);
  Y = -100.;
  compt = 0;
  corresp = -1;
  j=0;
  indic = 0;
  for (num_elem=0; num_elem<nb_elems; num_elem++)
    {
      y = xp(num_elem,1);
      trouve = 0;
      for (j=0; j<indic+1; j++)
        {
          if(std::fabs(y-Y[j])<=1e-8)
            {
              corresp[num_elem] = j;
              compt[j] ++;
              j=indic+1;
              trouve = 1;
              break;
            }
        }
      if (trouve==0)
        {
          corresp[num_elem] = indic;
          Y[indic]=y;
          compt[indic] ++;
          indic++;
        }
    }
}
References Conduction::inconnue(), Zone::nb_elem(), Zone_VDF::nb_faces_X(), Zone_VDF::nb_faces_Z(), ref_cast, TRUSTVect< _TYPE_ >::resize(), Zone_VF::xp(), Zone_dis_base::zone(), and Champ_Inc::zone_dis_base().
Referenced by readOn().
mettre_a_jour()
void Terme_Source_Solide_SWIFT_VDF::mettre_a_jour (double temps) inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 46 of file Terme_Source_Solide_SWIFT_VDF.h.
{ }
printOn()
Sortie & Terme_Source_Solide_SWIFT_VDF::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 30 of file Terme_Source_Solide_SWIFT_VDF.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_Solide_SWIFT_VDF::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 39 of file Terme_Source_Solide_SWIFT_VDF.cpp.
{
  int i,compteur = 0;
  Motcle motlu;
  Cerr << "         ######### Warning ! #########" << finl;
  Cerr << " For the moment, this forcing term is only available" << finl;
  Cerr << "     for recovering identical solid meshes." << finl;
  Cerr << " If otherwise, it will produce a beautiful core-dump..." << finl;
  for(i=0 ; i<3 ; i++)
    {
      is >> motlu;
      if(motlu == "TAU")
        {
          compteur++;
          is >> tau;
          if(tau==0)
            {
              Cerr << "TAU can not be equal to 0." << finl;
              exit();
            }
          Cerr << "Characteristic time TAU is : " << tau << finl;
        }
      else if(motlu == "pb_swift")
        {
          compteur++;
          Nom swift;
          is >> swift;
          pb_swift=ref_cast(Probleme_base, Interprete::objet(swift));
          Cerr << "pb_swift is: " << pb_swift.le_nom() << finl;
        }
      else if(motlu == "pb_corse")
        {
          compteur++;
          Nom corse;
          is >> corse;
          pb_corse=ref_cast(Probleme_base, Interprete::objet(corse));
          Cerr << "pb_coarse is: " << pb_corse.le_nom() << finl;
        }
      else
        {
          Cerr << "An argument of Terme_Source_Solide_SWIFT_VDF is not correct !" << finl;
          exit();
        }
    }
  if(compteur != 3)
    {
      Cerr << "The forcing term for the mean solid temperature field with the SWIFT method needs 3 arguments" << finl;
      Cerr << "Syntax : " << finl;
      Cerr << "Solide_SWIFT SWIFT pb_sol_SWIFT COARSE pb_sol_coarse TAU tau " << finl;
      exit();
    }
// On recupere les equations de conduction des deux domaines (SWIFT et grossier)
  int flag=0;
  for(i=0; i<pb_swift->nombre_d_equations(); i++)
    {
      if(sub_type(Conduction,pb_swift->equation(i)))
        {
          eq_swift = ref_cast(Conduction,pb_swift->equation(i));
          flag=1;
        }
    }
  if (flag==0)
    {
      Cerr << "Error : The Conduction equation was not found...!" << finl;
      Cerr << "for the SWIFT solid forcing term (in pb_swift)." << finl;
      exit();
    }
  flag=0;
  for(i=0; i<pb_corse->nombre_d_equations(); i++)
    {
      if(sub_type(Conduction,pb_corse->equation(i)))
        {
          eq_corse = ref_cast(Conduction,pb_corse->equation(i));
          flag=1;
        }
    }
  if (flag==0)
    {
      Cerr << "Error : The Conduction equation was not found...!" << finl;
      Cerr << "for the SWIFT solid forcing term (in pb_coarse)." << finl;
      exit();
    }
  init_calcul_moyenne(eq_swift.valeur(),Y_swift,corresp_swift,compt_swift);
  init_calcul_moyenne(eq_corse.valeur(),Y_corse,corresp_corse,compt_corse);
// Calcul du tableau de correspondance entre un element de Tmoy_swift et l'element de Tmoy_corse correspondant
// pour calculer le terme de forcage.
  correspondance_SWIFT_coarse();
  return is;
}
References Cerr, compt_corse, compt_swift, compteur, corresp_corse, corresp_swift, correspondance_SWIFT_coarse(), eq_corse, eq_swift, Probleme_base::equation(), Process::exit(), finl, init_calcul_moyenne(), O_U_Ptr::le_nom(), Probleme_base::nombre_d_equations(), Interprete::objet(), pb_corse, pb_swift, ref_cast, sub_type, tau, Ref_Conduction::valeur(), Y_corse, and Y_swift.
self_cast() [1/2]
const Terme_Source_Solide_SWIFT_VDF & Terme_Source_Solide_SWIFT_VDF::self_cast (const Objet_U & r) static
Definition at line 25 of file Terme_Source_Solide_SWIFT_VDF.cpp.
self_cast() [2/2]
Terme_Source_Solide_SWIFT_VDF & Terme_Source_Solide_SWIFT_VDF::self_cast (Objet_U & r) static
Definition at line 25 of file Terme_Source_Solide_SWIFT_VDF.cpp.
taille_memoire()
unsigned Terme_Source_Solide_SWIFT_VDF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file Terme_Source_Solide_SWIFT_VDF.cpp.
Member Data Documentation
compt_corse
IntVect Terme_Source_Solide_SWIFT_VDF::compt_corse protected
Definition at line 71 of file Terme_Source_Solide_SWIFT_VDF.h.
Referenced by ajouter_blocs(), and readOn().
compt_swift
IntVect Terme_Source_Solide_SWIFT_VDF::compt_swift protected
Nombre de points a meme Y.
Definition at line 70 of file Terme_Source_Solide_SWIFT_VDF.h.
Referenced by ajouter_blocs(), and readOn().
corresp_corse
IntVect Terme_Source_Solide_SWIFT_VDF::corresp_corse protected
Definition at line 74 of file Terme_Source_Solide_SWIFT_VDF.h.
Referenced by ajouter_blocs(), and readOn().
corresp_SC
IntVect Terme_Source_Solide_SWIFT_VDF::corresp_SC protected
Definition at line 75 of file Terme_Source_Solide_SWIFT_VDF.h.
Referenced by ajouter_blocs(), and correspondance_SWIFT_coarse().
corresp_swift
IntVect Terme_Source_Solide_SWIFT_VDF::corresp_swift protected
Correspondance numerotation globale -> numerotation locale dans Y.
Definition at line 73 of file Terme_Source_Solide_SWIFT_VDF.h.
Referenced by ajouter_blocs(), and readOn().
eq_corse
Ref_Conduction Terme_Source_Solide_SWIFT_VDF::eq_corse protected
Definition at line 63 of file Terme_Source_Solide_SWIFT_VDF.h.
Referenced by ajouter_blocs(), and readOn().
eq_swift
Ref_Conduction Terme_Source_Solide_SWIFT_VDF::eq_swift protected
Definition at line 62 of file Terme_Source_Solide_SWIFT_VDF.h.
Referenced by ajouter_blocs(), and readOn().
info_obj
const Type_info Terme_Source_Solide_SWIFT_VDF::info_obj static
Definition at line 39 of file Terme_Source_Solide_SWIFT_VDF.h.
pb_corse
Ref_Probleme_base Terme_Source_Solide_SWIFT_VDF::pb_corse protected
Definition at line 61 of file Terme_Source_Solide_SWIFT_VDF.h.
Referenced by readOn().
pb_swift
Ref_Probleme_base Terme_Source_Solide_SWIFT_VDF::pb_swift protected
Definition at line 60 of file Terme_Source_Solide_SWIFT_VDF.h.
Referenced by readOn().
tau
double Terme_Source_Solide_SWIFT_VDF::tau protected
tau est la constante de temps du forcage.
Definition at line 65 of file Terme_Source_Solide_SWIFT_VDF.h.
Referenced by ajouter_blocs(), and readOn().
Y_corse
DoubleVect Terme_Source_Solide_SWIFT_VDF::Y_corse protected
ou doit etre fait le forcage.
Definition at line 68 of file Terme_Source_Solide_SWIFT_VDF.h.
Referenced by correspondance_SWIFT_coarse(), and readOn().
Y_swift
DoubleVect Terme_Source_Solide_SWIFT_VDF::Y_swift protected
Coordonnees des points ou est definie la temperature dans le solide.
Definition at line 67 of file Terme_Source_Solide_SWIFT_VDF.h.
Referenced by correspondance_SWIFT_coarse(), and readOn().
The documentation for this class was generated from the following files:
src/VDF/Sources/Terme_Source_Solide_SWIFT_VDF.h
src/VDF/Sources/Terme_Source_Solide_SWIFT_VDF.cpp