TRUST: Cond_lim_utilisateur_base Class Reference
Cond_lim_utilisateur_base Class Reference
#include <Cond_lim_utilisateur_base.h>
Public Member Functions
~Cond_lim_utilisateur_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void lire (Entree &, Equation_base &, const Nom &nom_bord)
virtual void complement (Nom &)
int compatible_avec_eqn (const Equation_base &) const
Cond_lim & la_cl ()
Cond_lim_utilisateur_base ()
int is_pb_VDF ()
int is_pb_PolyMAC ()
int is_pb_CoviMAC ()
int is_pb_VEF ()
int is_pb_rayo ()
virtual void ecrire (const Nom &)
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Cond_lim_utilisateur_base & self_cast (Objet_U &)
static const
Cond_lim_utilisateur_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'une condition aux limite de type Cond_lim_utilisateur_base
a partir d'un flot d'entree.
Protected Attributes
Cond_lim * la_cl_
Ref_Equation_base mon_equation
Nom nom_bord_
Detailed Description
Definition at line 44 of file Cond_lim_utilisateur_base.h.
Constructor & Destructor Documentation
Cond_lim_utilisateur_base::~Cond_lim_utilisateur_base ()
Definition at line 33 of file Cond_lim_utilisateur_base.cpp.
Cond_lim_utilisateur_base::Cond_lim_utilisateur_base ()
Definition at line 187 of file Cond_lim_utilisateur_base.cpp.
:la_cl_(0) { }
Member Function Documentation
int Cond_lim_utilisateur_base::compatible_avec_eqn (const Equation_base &) const [inline, virtual]
Implements Cond_lim_base.
Definition at line 53 of file Cond_lim_utilisateur_base.h.
References Cerr, Process::exit(), and finl.
  {
    Cerr<<"we should not be here"<<(int)__LINE__<<__FILE__ <<finl;
    exit();
    return 0;
  };
void Cond_lim_utilisateur_base::complement (Nom & ajout) [virtual]
Reimplemented in cl_timp, paroi_adiabatique, paroi_flux_impose, paroi_contact, and paroi_contact_fictif.
Definition at line 195 of file Cond_lim_utilisateur_base.cpp.
References Cerr, and finl.
Referenced by lire().
{
  Cerr<<"Cond_lim_utilisateur_base::complement(Nom& toto) does nothing"<<finl;
}
virtual int Cond_lim_utilisateur_base::duplique () const [pure virtual]
Implements Cond_lim_base.
Implemented in cl_timp, paroi_adiabatique, paroi_flux_impose, paroi_contact, and paroi_contact_fictif.
void Cond_lim_utilisateur_base::ecrire (const Nom & ajout) [virtual]
Definition at line 162 of file Cond_lim_utilisateur_base.cpp.
References finl, and Process::je_suis_maitre().
Referenced by lire().
{
  if (je_suis_maitre())
    {
      SFichier conv("convert_jdd",ios::app);
      conv<<(*this)<<" # "<<ajout<<finl;
    }
}
const Type_info * Cond_lim_utilisateur_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in cl_timp, paroi_adiabatique, paroi_flux_impose, paroi_contact, and paroi_contact_fictif.
Definition at line 33 of file Cond_lim_utilisateur_base.cpp.
const Type_info * Cond_lim_utilisateur_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in cl_timp, paroi_adiabatique, paroi_flux_impose, paroi_contact, and paroi_contact_fictif.
Definition at line 33 of file Cond_lim_utilisateur_base.cpp.
int Cond_lim_utilisateur_base::is_pb_CoviMAC ()
Definition at line 223 of file Cond_lim_utilisateur_base.cpp.
References mon_equation, and Objet_U::que_suis_je().
Referenced by paroi_contact_fictif::complement(), and paroi_contact::complement().
{
  const Discretisation_base& discr=mon_equation->discretisation();
  Nom nom_discr=discr.que_suis_je();
  if (nom_discr=="CoviMAC")
    return 1;
  else
    return 0;
}
int Cond_lim_utilisateur_base::is_pb_PolyMAC ()
Definition at line 214 of file Cond_lim_utilisateur_base.cpp.
References mon_equation, and Objet_U::que_suis_je().
Referenced by paroi_contact_fictif::complement(), and paroi_contact::complement().
{
  const Discretisation_base& discr=mon_equation->discretisation();
  Nom nom_discr=discr.que_suis_je();
  if (nom_discr=="PolyMAC")
    return 1;
  else
    return 0;
}
int Cond_lim_utilisateur_base::is_pb_rayo ()
Definition at line 243 of file Cond_lim_utilisateur_base.cpp.
References Milieu_base::is_rayo_semi_transp(), Milieu_base::is_rayo_transp(), Probleme_base::milieu(), mon_equation, and ref_cast.
Referenced by paroi_contact_fictif::complement(), paroi_contact::complement(), cl_timp::complement(), paroi_flux_impose::complement(), and paroi_adiabatique::complement().
{
  Probleme_base& pb=mon_equation->probleme();
  Milieu_base& milieu = ref_cast(Milieu_base,pb.milieu());
  if (milieu.is_rayo_transp())
    return 2;
  else if (milieu.is_rayo_semi_transp())
    return 1;
  else
    return 0;
}
int Cond_lim_utilisateur_base::is_pb_VDF ()
Definition at line 201 of file Cond_lim_utilisateur_base.cpp.
References mon_equation, and Objet_U::que_suis_je().
Referenced by paroi_contact_fictif::complement(), paroi_contact::complement(), cl_timp::complement(), paroi_flux_impose::complement(), and paroi_adiabatique::complement().
{
  const Discretisation_base& discr=mon_equation->discretisation();
  Nom nom_discr=discr.que_suis_je();
  if (nom_discr=="VDF_Front_Tracking")
    {
      nom_discr="VDF";
    }
  if  (nom_discr=="VDF")
    return 1;
  else
    return 0;
}
int Cond_lim_utilisateur_base::is_pb_VEF ()
Definition at line 232 of file Cond_lim_utilisateur_base.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr<<"Cond_lim_utilisateur_base::is_pb_VEF not coded" <<finl;
  exit();
  return 0;
}
Cond_lim & Cond_lim_utilisateur_base::la_cl ()
Definition at line 189 of file Cond_lim_utilisateur_base.cpp.
References la_cl_.
Referenced by Zone_Cl_dis_base::readOn().
{
  return *(la_cl_);
}
void Cond_lim_utilisateur_base::lire (Entree & s, Equation_base & mon_eq, const Nom & nom_bord)
Definition at line 171 of file Cond_lim_utilisateur_base.cpp.
References Cerr, complement(), ecrire(), finl, la_cl_, mon_equation, and nom_bord_.
Referenced by Zone_Cl_dis_base::readOn().
{
  nom_bord_=nom_bord;
  mon_equation=mon_eq;
  la_cl_=new Cond_lim;
  Nom ajout("");
  complement(ajout);
#ifndef NDEBUG
  ecrire(ajout);
#endif
  Entree_complete s_complete(ajout,s);
  s_complete>>*(la_cl_);
  Cerr<<"end reading condmimutil"<<finl;
}
Sortie & Cond_lim_utilisateur_base::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in cl_timp, paroi_adiabatique, paroi_flux_impose, paroi_contact, and paroi_contact_fictif.
Definition at line 134 of file Cond_lim_utilisateur_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Cond_lim_utilisateur_base::readOn (Entree & s) [protected, virtual]
Lecture d'une condition aux limite de type Cond_lim_utilisateur_base
a partir d'un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in cl_timp, paroi_adiabatique, paroi_flux_impose, paroi_contact, and paroi_contact_fictif.
Definition at line 155 of file Cond_lim_utilisateur_base.cpp.
{
// la_cl=new Cond_lim;
  return s ;
}
const Cond_lim_utilisateur_base & Cond_lim_utilisateur_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Cond_lim_base.
Reimplemented in cl_timp, paroi_adiabatique, paroi_flux_impose, paroi_contact, and paroi_contact_fictif.
Definition at line 33 of file Cond_lim_utilisateur_base.cpp.
Cond_lim_utilisateur_base & Cond_lim_utilisateur_base::self_cast (Objet_U & r) [static]
Reimplemented from Cond_lim_base.
Reimplemented in cl_timp, paroi_adiabatique, paroi_flux_impose, paroi_contact, and paroi_contact_fictif.
Definition at line 33 of file Cond_lim_utilisateur_base.cpp.
Member Data Documentation
const Type_info Cond_lim_utilisateur_base::info_obj [static]
Reimplemented from Cond_lim_base.
Reimplemented in cl_timp, paroi_adiabatique, paroi_flux_impose, paroi_contact, and paroi_contact_fictif.
Definition at line 47 of file Cond_lim_utilisateur_base.h.
Cond_lim* Cond_lim_utilisateur_base::la_cl_ [protected]
Definition at line 69 of file Cond_lim_utilisateur_base.h.
Referenced by la_cl(), and lire().
Ref_Equation_base Cond_lim_utilisateur_base::mon_equation [protected]
Definition at line 70 of file Cond_lim_utilisateur_base.h.
Referenced by paroi_contact_fictif::complement(), paroi_contact::complement(), is_pb_CoviMAC(), is_pb_PolyMAC(), is_pb_rayo(), is_pb_VDF(), and lire().
Nom Cond_lim_utilisateur_base::nom_bord_ [protected]
Definition at line 71 of file Cond_lim_utilisateur_base.h.
Referenced by paroi_contact_fictif::complement(), paroi_contact::complement(), and lire().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Cond_lim_utilisateur_base.h
src/Kernel/Framework/Cond_lim_utilisateur_base.cpp