TRUST: Champ_front_base Class Reference
Champ_front_base Class Reference abstract
classe Champ_front_base
Classe de base pour la hierarchie des champs aux frontieres. Un
objet Champ_front_base definit un champ sur la frontiere d'un
domaine. Un objet de type Champ_front_base sera associe a
chaque condition aux limites.
Champ_front_base derive de Champ_Proto, afin d'avoir une interface
conforme a tous les champs, et d'heriter des operations courantes sur
les Champs.
Les deux methodes principales sont initialiser et
mettre_a_jour. Ce sont les deux seules qui peuvent modifier les
valeurs du champ.
La methode initialiser est appelee une fois au debut du
calcul. Elle ne doit pas dependre de donnees exterieures a
l'equation qui porte la CL (en effet, rien ne garantit que ces
donnees sont initialisees). En revanche, les valeurs de
l'inconnue sur laquelle porte la CL peuvent etre utiles pour
l'initialisation => l'inconnue est passee en parametre en
lecture seule.
La methode mettre_a_jour est appelee au debut de chaque pas de
temps ou sous-pas-de-temps, elle peut utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Dans le cas de champs stationnaires, la methode mettre_a_jour
n'a rien a faire et les valeurs sont remplies une fois pour
toutes par la methode initialiser.
Dans le cas de champs instationnaires, il y a plusieurs valeurs en temps
et chacune peut etre mise a jour.
Les Champ_front sont divises en :
* Champ_front_uniforme, constant dans le temps et l'espace
* Champ_front_instationnaire_base, uniformes en espace mais variables en temps
* Champ_front_var, variables en espace.
Les Champ_front_var sont ensuite classes selon qu'ils sont
stationnaires ou instationnaires.
Les valeurs sont stockees dans une roue de DoubleTab.
Si le champ est uniforme en espace, les DoubleTab sont
dimensionnes a 1.
S'il est stationnaire, la roue n'a qu'une valeur temporelle
et le temps qui lui est assigne n'a pas de sens.
S'il est instationnaire, les valeurs temporelles sont celles
de l'inconnue de l'equation a laquelle se rapporte le champ.
#include <Champ_front_base.h>
Public Member Functions
~Champ_front_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base ()
virtual void completer ()
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe une frontiere discretisee au champ.
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
virtual DoubleTab & valeurs_au_temps (double temps)=0
virtual const DoubleTab & valeurs_au_temps (double temps) const =0
const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee associee au champ.
(version const)
Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee associee au champ.
const Zone_dis_base & zone_dis () const
virtual Champ_front_base & affecter_ (const Champ_front_base &ch)=0
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
virtual void calculer_coeffs_echange (double temps)
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
virtual void valeurs_face (int, DoubleVect &) const
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
virtual void verifier (const Cond_lim_base &la_cl) const
double get_temps_defaut () const
void set_temps_defaut (double temps)
virtual void changer_temps_futur (double temps, int i)
virtual int avancer (double temps)
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe
en parametre.
virtual int reculer (double temps)
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe
en parametre.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static const Type_info * info ()
static Champ_front_base & self_cast (Objet_U &)
static const Champ_front_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double temps_defaut
Le temps pris par defaut quand le parametre n'est pas specifie. Ce sera en particulier celui utilise par les operateurs et les solveurs.
Ref_Frontiere_dis_base la_frontiere_dis
Roue_ptr les_valeurs
Les valeurs du champ.
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
classe Champ_front_base
Classe de base pour la hierarchie des champs aux frontieres. Un
objet Champ_front_base definit un champ sur la frontiere d'un
domaine. Un objet de type Champ_front_base sera associe a
chaque condition aux limites.
Champ_front_base derive de Champ_Proto, afin d'avoir une interface
conforme a tous les champs, et d'heriter des operations courantes sur
les Champs.
Les deux methodes principales sont initialiser et
mettre_a_jour. Ce sont les deux seules qui peuvent modifier les
valeurs du champ.
La methode initialiser est appelee une fois au debut du
calcul. Elle ne doit pas dependre de donnees exterieures a
l'equation qui porte la CL (en effet, rien ne garantit que ces
donnees sont initialisees). En revanche, les valeurs de
l'inconnue sur laquelle porte la CL peuvent etre utiles pour
l'initialisation => l'inconnue est passee en parametre en
lecture seule.
La methode mettre_a_jour est appelee au debut de chaque pas de
temps ou sous-pas-de-temps, elle peut utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Dans le cas de champs stationnaires, la methode mettre_a_jour
n'a rien a faire et les valeurs sont remplies une fois pour
toutes par la methode initialiser.
Dans le cas de champs instationnaires, il y a plusieurs valeurs en temps
et chacune peut etre mise a jour.
Les Champ_front sont divises en :
* Champ_front_uniforme, constant dans le temps et l'espace
* Champ_front_instationnaire_base, uniformes en espace mais variables en temps
* Champ_front_var, variables en espace.
Les Champ_front_var sont ensuite classes selon qu'ils sont
stationnaires ou instationnaires.
Les valeurs sont stockees dans une roue de DoubleTab.
Si le champ est uniforme en espace, les DoubleTab sont
dimensionnes a 1.
S'il est stationnaire, la roue n'a qu'une valeur temporelle
et le temps qui lui est assigne n'a pas de sens.
S'il est instationnaire, les valeurs temporelles sont celles
de l'inconnue de l'equation a laquelle se rapporte le champ.
Definition at line 81 of file Champ_front_base.h.
Constructor & Destructor Documentation
~Champ_front_base()
Champ_front_base::~Champ_front_base () override
Definition at line 20 of file Champ_front_base.cpp.
Champ_front_base()
Champ_front_base::Champ_front_base ()
Definition at line 22 of file Champ_front_base.cpp.
{
  temps_defaut = -1.;
}
References temps_defaut.
Member Function Documentation
affecter_()
virtual Champ_front_base & Champ_front_base::affecter_ (const Champ_front_base & ch) pure virtual
Implemented in Ch_front_input, Ch_front_input_uniforme, Ch_front_Vortex, Champ_front_bruite, Champ_front_calc, Champ_Front_Fonction, Champ_front_normal, Champ_front_t, Champ_front_Tabule, Champ_front_tangentiel, Champ_front_txyz, Champ_front_uniforme, Champ_front_vide, Ch_front_var_instationnaire_dep, Ch_front_var_stationnaire, Champ_front_MED, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_synt, and Champ_front_contact_VEF.
associer_fr_dis_base()
void Champ_front_base::associer_fr_dis_base (const Frontiere_dis_base & fr) virtual
Associe une frontiere discretisee au champ.
Reimplemented in Champ_front_xyz_debit.
Definition at line 103 of file Champ_front_base.cpp.
{
  la_frontiere_dis=fr;
}
References la_frontiere_dis.
Referenced by Champ_front::associer_fr_dis_base(), Echange_impose_base::associer_fr_dis_base(), Champ_front_xyz_debit::associer_fr_dis_base(), and Echange_interne_impose::associer_fr_dis_base().
avancer()
int Champ_front_base::avancer (double temps) virtual
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe
en parametre.
Returns
int
Signification: 1 si OK, 0 sinon
Contraintes:
Reimplemented in Champ_front_uniforme, Champ_front_vide, Champ_front_xyz_debit, Ch_front_var_stationnaire, Champ_front_instationnaire_base, and Champ_front_var_instationnaire.
Definition at line 211 of file Champ_front_base.cpp.
{
  Cerr << "Champ_front_base::avancer(double temps) should be overloaded"
       << finl;
  exit();
  return 0;
}
References Cerr, Process::exit(), and finl.
Referenced by Champ_front_xyz_debit::avancer(), Echange_impose_base::avancer(), and Echange_interne_impose::avancer().
calculer_coeffs_echange()
void Champ_front_base::calculer_coeffs_echange (double temps) virtual
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
Reimplemented in Champ_front_contact_VEF.
Definition at line 158 of file Champ_front_base.cpp.
{
}
Referenced by Champ_front::calculer_coeffs_echange().
changer_temps_futur()
void Champ_front_base::changer_temps_futur (double temps, int i) virtual
Reimplemented in Champ_front_uniforme, Champ_front_vide, Champ_front_xyz_debit, and Ch_front_var_stationnaire.
Definition at line 245 of file Champ_front_base.cpp.
{
  les_valeurs->futur(i).changer_temps(temps);
}
References Roue::changer_temps(), Roue::futur(), and les_valeurs.
Referenced by Champ_front_xyz_debit::changer_temps_futur(), Echange_impose_base::changer_temps_futur(), Echange_interne_impose::changer_temps_futur(), Champ_front_instationnaire_base::initialiser(), and Champ_front_var_instationnaire::initialiser().
completer()
virtual void Champ_front_base::completer () inline virtual
Reimplemented in Champ_front_calc, Champ_front_calc_interne, and Champ_front_contact_VEF.
Definition at line 89 of file Champ_front_base.h.
{};
fixer_nb_valeurs_temporelles()
void Champ_front_base::fixer_nb_valeurs_temporelles (int nb_cases) virtual
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
Reimplemented in Champ_front_xyz_debit, Champ_front_instationnaire_base, and Champ_front_var_instationnaire.
Definition at line 136 of file Champ_front_base.cpp.
{
}
Referenced by Champ_front_xyz_debit::fixer_nb_valeurs_temporelles(), Echange_impose_base::fixer_nb_valeurs_temporelles(), and Echange_interne_impose::fixer_nb_valeurs_temporelles().
frontiere_dis() [1/2]
Frontiere_dis_base & Champ_front_base::frontiere_dis () inline
Renvoie la frontiere discretisee associee au champ.
Returns
Frontiere_dis_base&
Signification: la frontiere discretisee associee au champ
Contraintes:
Definition at line 164 of file Champ_front_base.h.
{
  return la_frontiere_dis.valeur();
}
References la_frontiere_dis, and Ref_Frontiere_dis_base::valeur().
frontiere_dis() [2/2]
const Frontiere_dis_base & Champ_front_base::frontiere_dis () const inline
Renvoie la frontiere discretisee associee au champ.
(version const)
Returns
Frontiere_dis_base&
Signification: la frontiere discretisee associee au champ
Contraintes: reference constante
Definition at line 144 of file Champ_front_base.h.
{
  return la_frontiere_dis.valeur();
}
References la_frontiere_dis, and Ref_Frontiere_dis_base::valeur().
Referenced by Ch_front_input::buildSommetsFaces(), Champ_front_calc::completer(), Champ_front_contact_VEF::completer(), Champ_front::frontiere_dis(), Ch_front_input::getTemplate(), Ch_front_Vortex::initialiser(), Champ_front_lu::initialiser(), Ch_front_var_instationnaire_dep::initialiser(), Champ_front_var::initialiser(), Champ_front_softanalytique::initialiser(), Champ_front_contact_VEF::initialiser(), Champ_front_tangentiel_VEF::initialiser(), Champ_front_xyz_debit::initialiser(), Champ_front_xyz_debit::initialiser_coefficient(), Champ_Front_Fonction::mettre_a_jour(), Champ_front_t::mettre_a_jour(), Champ_front_txyz::mettre_a_jour(), Champ_front_xyz_debit::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Boundary_field_inward::mettre_a_jour(), Ch_front_Vortex::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), Champ_front_MED::remplir_tab(), Champ_front_debit_massique::update_coeff(), valeurs_face(), and zone_dis().
get_info()
const Type_info * Champ_front_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_front_instationnaire_base, Champ_front_var, Champ_front_var_instationnaire, Champ_front_MED, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 20 of file Champ_front_base.cpp.
get_temps_defaut()
double Champ_front_base::get_temps_defaut () const inline
Definition at line 106 of file Champ_front_base.h.
  {
    return temps_defaut;
  }
References temps_defaut.
info()
const Type_info * Champ_front_base::info () static
Definition at line 20 of file Champ_front_base.cpp.
initialiser()
int Champ_front_base::initialiser (double temps, const Champ_Inc_base & inco) virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented in Ch_front_input, Ch_front_input_uniforme, Ch_front_Vortex, Champ_front_debit, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_Tabule, Ch_front_input_P1, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Champ_front_instationnaire_base, Champ_front_var, Champ_front_var_instationnaire, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_pression_from_u, Champ_front_synt, Champ_front_contact_VEF, Champ_front_tangentiel_VEF, Boundary_field_inward, Champ_front_xyz_debit, and Champ_front_calc.
Definition at line 84 of file Champ_front_base.cpp.
{
  return 1;
}
Referenced by Echange_impose_base::initialiser(), Champ_front_instationnaire_base::initialiser(), and Champ_front_xyz_debit::initialiser().
mettre_a_jour()
void Champ_front_base::mettre_a_jour (double temps) virtual
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
Reimplemented in Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_Front_Fonction, Champ_front_t, Champ_front_Tabule, Champ_front_txyz, Champ_front_xyz_debit, Champ_Front_xyz_Tabule, Champ_front_MED, Champ_front_recyclage, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, Boundary_field_inward, Ch_front_Vortex, and Champ_front_fonc_gradient_VDF.
Definition at line 128 of file Champ_front_base.cpp.
{
}
Referenced by Ch_front_var_instationnaire_indep::initialiser(), Champ_front::mettre_a_jour(), and Champ_front_xyz_debit::mettre_a_jour().
printOn()
Sortie & Champ_front_base::printOn (Sortie & s) const override protected virtual
Imprime le nom du champ sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_front_instationnaire_base, Champ_front_var, Champ_front_var_instationnaire, Champ_front_MED, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 40 of file Champ_front_base.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_front_base::readOn (Entree & s) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_front_instationnaire_base, Champ_front_var, Champ_front_var_instationnaire, Champ_front_MED, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 61 of file Champ_front_base.cpp.
{
  return s ;
}
reculer()
int Champ_front_base::reculer (double temps) virtual
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe
en parametre.
Returns
int
Signification: 1 si OK, 0 sinon
Contraintes:
Reimplemented in Champ_front_uniforme, Champ_front_vide, Champ_front_xyz_debit, Ch_front_var_stationnaire, Champ_front_instationnaire_base, and Champ_front_var_instationnaire.
Definition at line 235 of file Champ_front_base.cpp.
{
  Cerr << "Champ_front_base::reculer(double temps) should be overloaded "
       << "by " << que_suis_je() << finl;
  exit();
  return 0;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Champ_front_xyz_debit::reculer(), Echange_impose_base::reculer(), and Echange_interne_impose::reculer().
self_cast() [1/2]
const Champ_front_base & Champ_front_base::self_cast (const Objet_U & r) static
Definition at line 20 of file Champ_front_base.cpp.
self_cast() [2/2]
Champ_front_base & Champ_front_base::self_cast (Objet_U & r) static
Definition at line 20 of file Champ_front_base.cpp.
set_temps_defaut()
void Champ_front_base::set_temps_defaut (double temps) inline
Definition at line 110 of file Champ_front_base.h.
  {
    temps_defaut=temps;
  }
References temps_defaut.
Referenced by Champ_front_xyz_debit::set_temps_defaut(), Echange_impose_base::set_temps_defaut(), and Echange_interne_impose::set_temps_defaut().
valeurs() [1/6]
const DoubleTab & Champ_front_base::valeurs () const inline override virtual
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
Returns
DoubleTab&
Signification: le tableau des valeurs du champ
Contraintes: reference constante
Implements Champ_Proto.
Definition at line 205 of file Champ_front_base.h.
{
  return valeurs_au_temps(temps_defaut);
}
References temps_defaut, and valeurs_au_temps().
valeurs() [2/6]
virtual const DoubleTab & Champ_Proto::valeurs () const virtual
Implements Champ_Proto.
valeurs() [3/6]
DoubleTab & Champ_front_base::valeurs () inline override virtual
Renvoie le tableau des valeurs du champ.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ au temps par defaut.
Contraintes:
Implements Champ_Proto.
Definition at line 184 of file Champ_front_base.h.
{
  return valeurs_au_temps(temps_defaut);
}
References temps_defaut, and valeurs_au_temps().
Referenced by Op_Diff_VEF_base::calculer_dt_stab(), Echange_contact_Correlation_VDF::completer(), Echange_contact_Correlation_VEF::completer(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Champ_front_lu::initialiser(), Ch_front_input_P1::initialiser(), Champ_front_instationnaire_base::initialiser(), Champ_front_var_instationnaire::initialiser(), Champ_front_softanalytique::initialiser(), Champ_front_xyz_debit::initialiser(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_contact_fictif_VEF::mettre_a_jour(), Ch_front_Vortex::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Ch_front_Vortex::printOn(), Champ_front_bruite::printOn(), Champ_front_fonc_pois_ipsn::printOn(), Champ_front_fonc_pois_tube::printOn(), Champ_front_lu::printOn(), Champ_front_normal::printOn(), Champ_front_t::printOn(), Champ_front_Tabule::printOn(), Champ_front_tangentiel::printOn(), Champ_front_txyz::printOn(), Champ_front_uniforme::printOn(), Champ_front_softanalytique::printOn(), Champ_front_debit_QC::printOn(), Champ_front_debit_QC_fonc_t::printOn(), Champ_front_synt::printOn(), Ch_front_input::setDoubleValue(), Ch_front_input::setValue(), Ch_front_input_uniforme::setValue(), Ch_front_input_P1::setValue(), Champ_front::valeurs(), Champ_front_instationnaire_base::valeurs_au_temps(), Champ_front_var_instationnaire::valeurs_au_temps(), valeurs_face(), Champ_front_uniforme::valeurs_face(), and Champ_front_instationnaire_base::valeurs_face().
valeurs() [4/6]
virtual DoubleTab & Champ_Proto::valeurs () virtual
Implements Champ_Proto.
valeurs() [5/6]
virtual DoubleTab & Champ_Proto::valeurs (double temps) inline virtual
Reimplemented from Champ_Proto.
Definition at line 50 of file Champ_Proto.h.
{ return valeurs(); }
valeurs() [6/6]
virtual const DoubleTab & Champ_Proto::valeurs (double temps) const inline virtual
Reimplemented from Champ_Proto.
Definition at line 51 of file Champ_Proto.h.
{ return valeurs(); }
valeurs_au_temps() [1/2]
virtual const DoubleTab & Champ_front_base::valeurs_au_temps (double temps) const pure virtual
Implemented in Champ_front_uniforme, Champ_front_vide, Ch_front_var_stationnaire, Champ_front_instationnaire_base, and Champ_front_var_instationnaire.
valeurs_au_temps() [2/2]
virtual DoubleTab & Champ_front_base::valeurs_au_temps (double temps) pure virtual
Implemented in Champ_front_uniforme, Champ_front_vide, Ch_front_var_stationnaire, Champ_front_instationnaire_base, and Champ_front_var_instationnaire.
Referenced by Champ_front_xyz_debit::calculer_champ_vitesse(), Champ_front_xyz_debit::mettre_a_jour(), and valeurs().
valeurs_face()
void Champ_front_base::valeurs_face (int num_face, DoubleVect & val) const virtual
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
Reimplemented in Champ_front_uniforme, Champ_front_vide, and Champ_front_instationnaire_base.
Definition at line 172 of file Champ_front_base.cpp.
{
#ifndef NDEBUG
  const int nb_faces = frontiere_dis().frontiere().nb_faces();
// Si plantage ici, c'est que le tableau des valeurs ne contient pas une
// valeur pour chaque face, il faut reimplementer la methode dans la
// classe derivee...
  assert(num_face >= 0 && num_face < nb_faces);
  assert(valeurs().dimension(0) == nb_faces);
#endif
  const int n = nb_compo_;
  val.resize(n);
  const DoubleTab& valeurs_a_copier=valeurs();
  for (int i = 0; i < n; i++)
    val[i] = valeurs_a_copier(num_face, i);
}
References Objet_U::dimension, Frontiere_dis_base::frontiere(), frontiere_dis(), Field_base::nb_compo_, Frontiere::nb_faces(), TRUSTVect< _TYPE_ >::resize(), and valeurs().
verifier()
void Champ_front_base::verifier (const Cond_lim_base & la_cl) const inline virtual
Reimplemented in Champ_front_calc.
Definition at line 211 of file Champ_front_base.h.
{
  return;
}
Referenced by Cond_lim_base::associer_zone_cl_dis_base().
zone_dis()
const Zone_dis_base & Champ_front_base::zone_dis () const
Definition at line 189 of file Champ_front_base.cpp.
{
  return frontiere_dis().zone_dis();
}
References frontiere_dis(), and Frontiere_dis_base::zone_dis().
Referenced by Champ_front_xyz_debit::calculer_normales_et_integrale(), Ch_front_Vortex::initialiser(), Champ_front_lu::initialiser(), Champ_front_softanalytique::initialiser(), Champ_front_tangentiel_VEF::initialiser(), Champ_Front_Fonction::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Boundary_field_inward::mettre_a_jour(), Ch_front_Vortex::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), and Champ_front_debit_massique::update_coeff().
Member Data Documentation
info_obj
const Type_info Champ_front_base::info_obj static
Definition at line 84 of file Champ_front_base.h.
la_frontiere_dis
Ref_Frontiere_dis_base Champ_front_base::la_frontiere_dis protected
Definition at line 124 of file Champ_front_base.h.
Referenced by associer_fr_dis_base(), Champ_front_recyclage::calcul_moyenne_imposee(), Champ_front_recyclage::calcul_moyenne_recyclee(), frontiere_dis(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Champ_front_recyclage::initialiser(), Champ_front_recyclage::initialiser_moyenne_imposee(), Champ_front_recyclage::initialiser_moyenne_recyclee(), Champ_front_bruite::mettre_a_jour(), Champ_front_recyclage::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Champ_front_contact_fictif_VEF::mettre_a_jour(), Champ_front_contact_VEF::mettre_a_jour(), Champ_front_contact_VEF::remplir_connect_bords(), Ch_front_Vortex::reprendre_vortex(), Ch_front_Vortex::sauvegarder_vortex(), and Champ_front_contact_VEF::verifier_scalaire_bord().
les_valeurs
Roue_ptr Champ_front_base::les_valeurs protected
Les valeurs du champ.
Definition at line 125 of file Champ_front_base.h.
Referenced by Champ_front_instationnaire_base::avancer(), Champ_front_var_instationnaire::avancer(), changer_temps_futur(), Champ_front_instationnaire_base::fixer_nb_valeurs_temporelles(), Champ_front_var_instationnaire::fixer_nb_valeurs_temporelles(), Ch_front_input_uniforme::initialiser(), Ch_front_input_P1::initialiser(), Ch_front_var_instationnaire_dep::initialiser(), Champ_front_instationnaire_base::initialiser(), Champ_front_var::initialiser(), Champ_front_tangentiel_VEF::initialiser(), Champ_front_xyz_debit::initialiser(), Champ_front_pression_from_u::mettre_a_jour(), Boundary_field_inward::mettre_a_jour(), Champ_front_uniforme::readOn(), Champ_front_instationnaire_base::reculer(), Champ_front_var_instationnaire::reculer(), Ch_front_input::setDoubleValue(), Ch_front_input::setValue(), Ch_front_input_uniforme::setValue(), Champ_front_uniforme::valeurs_au_temps(), Champ_front_vide::valeurs_au_temps(), Ch_front_var_stationnaire::valeurs_au_temps(), Champ_front_instationnaire_base::valeurs_au_temps(), and Champ_front_var_instationnaire::valeurs_au_temps().
temps_defaut
double Champ_front_base::temps_defaut protected
Le temps pris par defaut quand le parametre n'est pas specifie. Ce sera en particulier celui utilise par les operateurs et les solveurs.
Definition at line 120 of file Champ_front_base.h.
Referenced by Champ_front_base(), get_temps_defaut(), Champ_front_instationnaire_base::initialiser(), Champ_front_var_instationnaire::initialiser(), set_temps_defaut(), and valeurs().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_front_base.h
src/Kernel/Framework/Champ_front_base.cpp