TRUST: Solv_Gen Class Reference
Solv_Gen Class Reference
#include <Solv_Gen.h>
Public Member Functions
~Solv_Gen ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Solv_Gen ()
int resoudre_systeme (const Matrice_Base &, const DoubleVect &, DoubleVect &) override
int resoudre_systeme (const Matrice_Base &M, const DoubleVect &A, DoubleVect &B, int niter_max) override
SolvElem & le_solveur_elem ()
const SolvElem & le_solveur_elem () const
const Precond & get_precond () const
void set_precond (const Precond &pre)
void reinit () override
Public Member Functions inherited from solv_iteratif
~solv_iteratif () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
solv_iteratif ()
void set_seuil (double s)
double get_seuil () const
int solveur_direct () const override
Public Member Functions inherited from SolveurSys_base
~SolveurSys_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
SolveurSys_base ()
virtual int solveur_direct () const =0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x)=0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x, int niter_max)
virtual void fixer_schema_temps_limpr (int l)
void fixer_limpr (int l)
void set_return_on_error (int ret)
int limpr () const
virtual void reinit ()
int nouvelle_matrice () const
void fixer_nouvelle_matrice (int i)
virtual int supporte_matrice_morse_sym ()
virtual int get_flag_updated_input () const
void set_flag_updated_result (int flag)
int get_flag_updated_result () const
void save_matrice_secmem_conditionnel (const Matrice_Base &la_matrice, const DoubleVect &secmem, const DoubleVect &solution, int binaire=1)
void set_reuse_preconditioner (bool flag)
bool reuse_preconditioner ()
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Solv_Gen & self_cast (Objet_U &)
static const Solv_Gen & self_cast (const Objet_U &)
Static Public Member Functions inherited from solv_iteratif
static const Type_info * info ()
static solv_iteratif & self_cast (Objet_U &)
static const solv_iteratif & self_cast (const Objet_U &)
Static Public Member Functions inherited from SolveurSys_base
static const Type_info * info ()
static SolveurSys_base & self_cast (Objet_U &)
static const SolveurSys_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from solv_iteratif
static const Type_info info_obj
Static Public Attributes inherited from SolveurSys_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
int solve (const Matrice_Base &matrice, const Matrice_Base &mat_loc, const DoubleVect &secmem, DoubleVect &solution)
Protected Member Functions inherited from solv_iteratif
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from SolveurSys_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Precond le_precond_
SolvElem le_solveur_elem_
int nb_it_max_
int nb_it_max_flag
int force_
Protected Attributes inherited from solv_iteratif
double seuil_
Protected Attributes inherited from SolveurSys_base
int nouvelle_matrice_
Drapeau pour savoir si un stockage ou une factorisation est a refaire.
int save_matrice_
Drapeau pour savoir si un stockage disque est a refaire.
int return_on_error_ = 0
Detailed Description
Definition at line 26 of file Solv_Gen.h.
Constructor & Destructor Documentation
~Solv_Gen()
Solv_Gen::~Solv_Gen ()
Definition at line 22 of file Solv_Gen.cpp.
Solv_Gen()
Solv_Gen::Solv_Gen ()
Definition at line 24 of file Solv_Gen.cpp.
{
  seuil_ = _SEUIL_Gen_;
  nb_it_max_ = 1000000;
  nb_it_max_flag = 0;
  force_ = 0;
}
References _SEUIL_Gen_, force_, nb_it_max_, nb_it_max_flag, and solv_iteratif::seuil_.
Member Function Documentation
cree_instance()
Objet_U * Solv_Gen::cree_instance () static
Definition at line 22 of file Solv_Gen.cpp.
duplique()
int Solv_Gen::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file Solv_Gen.cpp.
get_info()
const Type_info * Solv_Gen::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 22 of file Solv_Gen.cpp.
get_precond()
const Precond & Solv_Gen::get_precond () const inline
Definition at line 38 of file Solv_Gen.h.
{ return le_precond_; }
References le_precond_.
info()
const Type_info * Solv_Gen::info () static
Definition at line 22 of file Solv_Gen.cpp.
le_solveur_elem() [1/2]
SolvElem & Solv_Gen::le_solveur_elem () inline
Definition at line 36 of file Solv_Gen.h.
{ return le_solveur_elem_; }
References le_solveur_elem_.
le_solveur_elem() [2/2]
const SolvElem & Solv_Gen::le_solveur_elem () const inline
Definition at line 37 of file Solv_Gen.h.
{ return le_solveur_elem_; }
References le_solveur_elem_.
printOn()
Sortie & Solv_Gen::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 40 of file Solv_Gen.cpp.
{
  s<<" { seuil "<<seuil_<< " solv_elem "<<le_solveur_elem_ << " precond "<< le_precond_;
  if (limpr()==1)
    s<< " impr ";
  if (limpr()==-1)
    s<< " quiet ";
  s <<" } ";
  return s ;
}
References le_precond_, le_solveur_elem_, SolveurSys_base::limpr(), and solv_iteratif::seuil_.
readOn()
Entree & Solv_Gen::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 51 of file Solv_Gen.cpp.
{
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Motcles les_parametres(9);
  {
    les_parametres[0] = "seuil";
    les_parametres[1] = "impr";
    les_parametres[2] = "solv_elem";
    les_parametres[3] = "precond";
    les_parametres[4] = "save_matrice|save_matrix";
    les_parametres[5] = "quiet";
    les_parametres[6] = "nb_it_max";
    les_parametres[7] = "force";
    les_parametres[8] = "return";
  }
  int rang;
  Motcle motlu;
  is >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "Error when reading the parameters for the generic solver " << finl;
      Cerr << "One expected : " << accolade_ouverte << finl;
      exit();
    }
  is >> motlu;
  save_matrice_=0;
  while (motlu != accolade_fermee)
    {
      rang = les_parametres.search(motlu);
      switch(rang)
        {
        case 0:
          {
            is >> seuil_;
            break;
          }
        case 1:
          {
            fixer_limpr(1);
            break;
          }
        case 2:
          {
            is >> le_solveur_elem_;
            break;
          }
        case 3:
          {
            is >> le_precond_;
            break;
          }
        case 4:
          {
            save_matrice_=1;
            break;
          }
        case 5:
          {
            fixer_limpr(-1);
            break;
          }
        case 6:
          {
            is>>nb_it_max_;
            nb_it_max_flag = 1;
            break;
          }
        case 7:
          {
            force_ = 1;
            break;
          }
        case 8:
          {
            return_on_error_ = 1;
            break;
          }
        default :
          {
            Cerr << "Error when reading the parameters of the generic solver " << finl;
            Cerr << "One expected " << les_parametres << " instead of " << motlu << finl;
            exit();
          }
        }
      is >> motlu;
    }
  if ((nb_it_max_flag ==0) && (force_==1) )
    {
      Cerr << "Error while reading the parameters of the generic solver " << finl;
      Cerr << "When you choose to 'force' negative ipar[5], you should specify nb_it_max in your datafile" << finl;
      exit();
    }
  return is;
}
References Cerr, Process::exit(), finl, SolveurSys_base::fixer_limpr(), force_, le_precond_, le_solveur_elem_, nb_it_max_, nb_it_max_flag, SolveurSys_base::return_on_error_, SolveurSys_base::save_matrice_, Motcles::search(), and solv_iteratif::seuil_.
reinit()
void Solv_Gen::reinit () override virtual
Reimplemented from SolveurSys_base.
Definition at line 32 of file Solv_Gen.cpp.
{
  if(le_precond_.non_nul())
    {
      le_precond_.valeur().reinit();
    }
}
References le_precond_, O_U_Ptr::non_nul(), Precond_base::reinit(), and Deriv_Precond_base::valeur().
resoudre_systeme() [1/2]
int Solv_Gen::resoudre_systeme (const Matrice_Base & la_matrice, const DoubleVect & secmem, DoubleVect & solution) override virtual
Implements SolveurSys_base.
Definition at line 148 of file Solv_Gen.cpp.
{
// On definit tout nos vecteurs et leur dimension respective et nos constantes
// n : la taille du systeme lineaire
  int n = secmem.size();
  if(solution.size() != n)
    {
      if( solution.size() ==0)
        solution.resize(n);
      else
        {
          Cerr << "Solv_Gen::resoudre_systeme : wrong dimension of the vectors" << finl;
          return(-1);
        }
    }
// Cerr<<"La matrice : "<<la_matrice.que_suis_je()<<finl;
  if(sub_type(Matrice_Bloc,la_matrice))
    {
      const Matrice_Bloc& MB = ref_cast(Matrice_Bloc,la_matrice);
      const Matrice& MB00 = MB.get_bloc(0,0);
      if(sub_type(Matrice_Morse_Sym,MB00.valeur()))
        {
          const Matrice_Morse_Sym& M = ref_cast(Matrice_Morse_Sym,MB00.valeur());
          return solve(la_matrice,M,secmem,solution);
        }
      else if(sub_type(Matrice_Morse,MB00.valeur()))
        {
          const Matrice_Morse& mat = ref_cast(Matrice_Morse,MB00.valeur());
          return solve(la_matrice,mat,secmem,solution);
        }
      else
        {
          Cerr<<"ERROR SolvGen : one is not able to treat the case of a matrix"<<finl;
          Cerr<<"of type : "<<MB00.que_suis_je()<<finl;
          exit();
          return -1;
        }
    }
  else if(sub_type(Matrice_Morse_Sym,la_matrice))
    {
      const Matrice_Morse_Sym& M = ref_cast(Matrice_Morse_Sym,la_matrice);
      return solve(M,M,secmem,solution);
    }
  else if(sub_type(Matrice_Morse,la_matrice))
    {
      const Matrice_Morse& mat = ref_cast(Matrice_Morse,la_matrice);
      return solve(mat,mat,secmem,solution);
    }
  else
    {
      Cerr<<"ERROR SolvGen : one is not able to treat the case of a matrix"<<finl;
      Cerr<<"of type : "<<la_matrice.que_suis_je()<<finl;
      exit();
      return -1;
    }
}
References Cerr, Process::exit(), finl, Matrice_Bloc::get_bloc(), Objet_U::que_suis_je(), ref_cast, TRUSTVect< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), solve(), sub_type, and Deriv_Matrice_Base::valeur().
Referenced by resoudre_systeme().
resoudre_systeme() [2/2]
int Solv_Gen::resoudre_systeme (const Matrice_Base & M, const DoubleVect & A, DoubleVect & B, int niter_max) inline override virtual
Reimplemented from SolveurSys_base.
Definition at line 32 of file Solv_Gen.h.
  {
    return resoudre_systeme(M, A, B);
  }
References resoudre_systeme().
self_cast() [1/2]
const Solv_Gen & Solv_Gen::self_cast (const Objet_U & r) static
Definition at line 22 of file Solv_Gen.cpp.
self_cast() [2/2]
Solv_Gen & Solv_Gen::self_cast (Objet_U & r) static
Definition at line 22 of file Solv_Gen.cpp.
set_precond()
void Solv_Gen::set_precond (const Precond & pre) inline
Definition at line 39 of file Solv_Gen.h.
{ le_precond_ = pre; }
References le_precond_.
solve()
int Solv_Gen::solve (const Matrice_Base & matrice, const Matrice_Base & mat_loc, const DoubleVect & secmem, DoubleVect & solution) protected
< pour le test de convergence
< nb max de produit matrice vect si nb negatif on s arrete a la convergence Si gros calcul (Process::mp_sum(n)>2147483647), specifier nb_it_max et imposer ipar[5] = -1 on le fait desormais en specifiant le mot cle 'force' dans le jdd
< tolerance relative
< GF les autres solveurs n'ont pas de tol relative
< tolerance absolue
< initialisation du compteur
Definition at line 208 of file Solv_Gen.cpp.
{
// n : la taille du systeme lineaire
  int n = secmem.size();
  int ntot = secmem.size_array();
  int niter=0;
// definition de ipar et fpar
  ArrOfInt ipar(16);
  ArrOfDouble fpar(16);
// definition de w : vecteur de travail de taille 9*n
  ArrOfDouble w;
  le_solveur_elem_.dimensionne_wks(ntot,w);
// Initialisation
  ipar[0] = 0; //on def tjrs cela pour commencer le calcul
  if(le_precond_.non_nul())
    {
      if(sub_type(ILU,le_precond_.valeur()))
        {
          ILU& pilu = ref_cast(ILU,le_precond_.valeur());
          ipar[1] = pilu.type_precond();
        }
      else
        ipar[1]=1;
    }
  else
    ipar[1]=0;
  ipar[2] = 1; //!< pour le test de convergence
  ipar[2] = 2;
  ipar[3] = w.size_array();; //taille maximale de w
  ipar[4] = 10;
  int nmax_min = 100;
  int nmax = std::max(Process::mp_sum(n), nmax_min);
  ipar[5] = nmax; //!< nb max de produit matrice vect si nb negatif on s arrete a la convergence Si gros calcul (Process::mp_sum(n)>2147483647), specifier nb_it_max et imposer ipar[5] = -1 on le fait desormais en specifiant le mot cle 'force' dans le jdd
//
//
//
  if (force_ ==1) ipar[5] = -1;
  fpar[0] = seuil_; //!< tolerance relative
  fpar[0]= 1e-50 ; //!< GF les autres solveurs n'ont pas de tol relative
  fpar[1] = seuil_; //!< tolerance absolue
  fpar[10] = 0; //!< initialisation du compteur
// solution = 1.0;
  le_solveur_elem_.iteration(ntot,secmem,solution,ipar,fpar,w);
  solution.echange_espace_virtuel();
  DoubleTab W7, W8;
  {
// fait pointer v sur la sous partie qui commence a ipar[7]-1, de taille ntot:
    W7.ref_array(w, ipar[7]-1, ntot);
// Remarque TUTU: resize autorise car il ne change pas la taille et necessaire
// pour initialiser line_size() du tableau W7:
    W7.resize(ntot/secmem.line_size(), secmem.line_size());
    W7.set_md_vector(secmem.get_md_vector());
    W7.echange_espace_virtuel();
  }
  int ret = ipar[0];
  while(ret != 0 && niter < nb_it_max_ )
    {
      niter++;
      W7.ref_array(w, ipar[7]-1, ntot);
      W7.resize(ntot/secmem.line_size(), secmem.line_size()); //idem remarque TUTU
      W7.set_md_vector(secmem.get_md_vector());
      W8.ref_array(w, ipar[8]-1, ntot);
      W8.resize(ntot/secmem.line_size(), secmem.line_size()); //idem remarque TUTU
      W8.set_md_vector(secmem.get_md_vector());
      if (ret != 4 && ret != 6)
        W7.echange_espace_virtuel();
      if(ret==1)
        {
// on doit calculer le produit A*u
// int ii;
          matrice.multvect(W7, W8);
          le_solveur_elem_.iteration(ntot,secmem,solution,ipar,fpar,w);
          solution.echange_espace_virtuel();
        }
      else if(ret==2)
        {
          exit();
// on doit calculer le produit At*u
// matrice.multvectT(u, s);
// int ii;
          matrice.multvectT(W7, W8);
          le_solveur_elem_.iteration(ntot,secmem,solution,ipar,fpar,w);
          solution.echange_espace_virtuel();
        }
      else if((ret == 3) || (ret == 5))
        {
// On preconditionne
// int ii;
          if(sub_type(ILU,le_precond_.valeur()))
            le_precond_.preconditionner(mat_loc, W7, W8);
          else
            le_precond_.preconditionner(mat_loc,secmem,solution);
// le_precond_.preconditionner(matrice,secmem,solution);
          le_solveur_elem_.iteration(ntot,secmem,solution,ipar,fpar,w);
          solution.echange_espace_virtuel();
        }
      else if((ret == 4) || (ret == 6))
        {
          exit();
// On preconditionne
          if(sub_type(ILU,le_precond_.valeur()))
            le_precond_.preconditionner(mat_loc, W7, W8);
          else
            le_precond_.preconditionner(mat_loc,secmem,solution);
          le_solveur_elem_.iteration(ntot,secmem,solution,ipar,fpar,w);
          solution.echange_espace_virtuel();
        }
      else if(ret == 10)
        {
          Cout<<"Case 10"<<finl;
          Cout<<"The predefined stop test is retained"<<finl;
          le_solveur_elem_.iteration(ntot,secmem,solution,ipar,fpar,w);
          solution.echange_espace_virtuel();
        }
      else if(ret > 0)
        {
          Cerr<<"Case > 0"<<finl;
          Cerr<<"That code does not exist "<<finl;
          exit();
          return(-1);
        }
      else if(ret < 0)
        {
          Cerr<<"ERROR in SolvGen"<<finl;
          Cerr<<" The solver terminates with code number "<<ret<<finl;
          if(ret==-1)
            {
              Cerr<<"Stop since the iteration number "<<finl;
              Cerr<<"is greater than the preset limit"<<finl;
            }
          else if(ret==-2)
            {
              Cerr<<"return due to insufficient work space"<<finl;
            }
          else if(ret==-3)
            {
              Cerr<<"return due to anticipated break-down / divide by zero"<<finl;
              Cerr<<"ipar[11] : "<<ipar[11]<<finl;
              Cerr<<"w : "<<w<<finl;
              Cerr<<"ind = fpar[1O] : "<<fpar[10]<<finl;
            }
          else if(ret==-4)
            {
              Cerr<<"the values of fpar(1) and fpar(2) are both <= 0, "<<finl;
              Cerr<<"the valid ranges are 0 <= fpar(1) < 1, 0 <= fpar(2), "<<finl;
              Cerr<<"and they can not be zero at the same time"<<finl;
            }
          else if(ret==-9)
            {
              Cerr<<"while trying to detect a break-down, "<<finl;
              Cerr<<"an abnormal number is detected"<<finl;
            }
          else if(ret==-10)
            {
              Cerr<<"return due to some non-numerical reasons, "<<finl;
              Cerr<<"e.g. invalid floating-point numbers etc."<<finl;
            }
          if (!return_on_error_) exit();
          return(-1);
        }
      ret = ipar[0];
      if(limpr()==1)
        {
// Cerr<<"++ Cas : "<<ret<<finl;
// Cerr<<"fpar(5) -- current residual norm (if available) : "<<fpar[4]<<finl;
// Cerr<<"fpar(6) -- current residual/error norm : "<<fpar[5]<<finl;
          Cout<< fpar[5]<<" ";
          if (niter%10==0) Cout<<finl;
        }
    }
  if (je_suis_maitre())
    {
// Cerr<<"--------------------------------------------------"<<finl;
      if (limpr()>-1)
        {
          if (niter == nb_it_max_)
            {
              Cout<<finl<<"Maximum number of iteration nb_it_max for SolvGen = "<<nb_it_max_ << " reached..." <<finl;
              if (nb_it_max_flag == 0) Cout<<"Advice: You can modify nb_it_max by setting it in your datafile..." <<finl;
            }
// Cout<<finl<<"End of the resolution by SolvGen after "<<niter <<" iterations, current residual/error norm "<<fpar[5]<<" initial residual/error norm "<<fpar[2]<<finl;
          double residu_relatif = (fpar[2] > 0 ? fpar[5] / fpar[2] : fpar[5]);
          Cout << finl << "Final residue: " << fpar[5] << " ( " << residu_relatif << " )"<<finl;
        }
// Cerr<<"fpar(3) -- initial residual/error norm : "<<fpar[2]<<finl;
// Cerr<<"fpar(4) -- target residual/error norm : "<<fpar[3]<<finl;
// Cerr<<"fpar(5) -- current residual norm (if available) : "<<fpar[4]<<finl;
// Cerr<<"fpar(6) -- current residual/error norm : "<<fpar[5]<<finl;
// Cerr<<"fpar(7) -- convergence rate : "<<fpar[6]<<finl;
    }
  if (0)
    {
      DoubleVect tmp(solution);
      matrice.multvect(solution,tmp);
      int ii;
      /*
        Process::Journal()<<" A = "<<matrice<<finl;
        Process::Journal()<<" ipar = "<<finl;
        for(ii=0;ii<ipar.size_array();ii++)
        Process::Journal()<<ii<<": "<<ipar[ii]<<finl;
        Process::Journal()<<" w = "<<finl;
        for(ii=0;ii<w.size_array();ii++)
        Process::Journal()<<ii<<": "<<w[ii]<<finl;
        Process::Journal()<<" x = "<<solution<<finl;
        //     solution.ecrit(Process::Journal());
        Process::Journal()<<" A*x = "<<tmp<<finl;
        Process::Journal()<<" b = "<<secmem<<finl;
        tmp.ecrit(Process::Journal());
      */
      for(ii=0; ii<solution.size(); ii++)
        tmp(ii)-=secmem(ii);
      tmp.echange_espace_virtuel();
      double err=0.;
      for(ii=0; ii<solution.size(); ii++)
        err+=(tmp(ii)*tmp(ii));
      err = Process::mp_sum(err);
      Cerr<<"ERROR: "<<sqrt(err)<<finl;
    }
  return niter;
}
References Cerr, Cout, SolvElem::dimensionne_wks(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, force_, TRUSTVect< _TYPE_ >::get_md_vector(), SolvElem::iteration(), Process::je_suis_maitre(), le_precond_, le_solveur_elem_, SolveurSys_base::limpr(), TRUSTVect< _TYPE_ >::line_size(), Process::mp_sum(), Matrice_Base::multvect(), Matrice_Base::multvectT(), nb_it_max_, nb_it_max_flag, O_U_Ptr::non_nul(), Precond::preconditionner(), TRUSTTab< _TYPE_ >::ref_array(), ref_cast, TRUSTTab< _TYPE_ >::resize(), SolveurSys_base::return_on_error_, TRUSTTab< _TYPE_ >::set_md_vector(), solv_iteratif::seuil_, TRUSTVect< _TYPE_ >::size(), TRUSTArray< _TYPE_ >::size_array(), sub_type, ILU::type_precond(), and Deriv_Precond_base::valeur().
Referenced by resoudre_systeme().
taille_memoire()
unsigned Solv_Gen::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file Solv_Gen.cpp.
Member Data Documentation
force_
int Solv_Gen::force_ protected
Definition at line 47 of file Solv_Gen.h.
Referenced by readOn(), Solv_Gen(), and solve().
info_obj
const Type_info Solv_Gen::info_obj static
Definition at line 28 of file Solv_Gen.h.
le_precond_
Precond Solv_Gen::le_precond_ protected
Definition at line 45 of file Solv_Gen.h.
Referenced by get_precond(), printOn(), readOn(), reinit(), set_precond(), and solve().
le_solveur_elem_
SolvElem Solv_Gen::le_solveur_elem_ protected
Definition at line 46 of file Solv_Gen.h.
Referenced by le_solveur_elem(), printOn(), readOn(), and solve().
nb_it_max_
int Solv_Gen::nb_it_max_ protected
Definition at line 47 of file Solv_Gen.h.
Referenced by readOn(), Solv_Gen(), and solve().
nb_it_max_flag
int Solv_Gen::nb_it_max_flag protected
Definition at line 47 of file Solv_Gen.h.
Referenced by readOn(), Solv_Gen(), and solve().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/Solv_Gen.h
src/Kernel/Math/SolvSys/Solv_Gen.cpp