TRUST: Zone_Cl_PolyMAC Class Reference
Zone_Cl_PolyMAC Class Reference
#include <Zone_Cl_PolyMAC.h>
Public Member Functions
Zone_Cl_PolyMAC ()
~Zone_Cl_PolyMAC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_PolyMAC &)
etape de discretisation : dimensionnement des tableaux
void completer (const Zone_dis &) override
remplissage des tableaux
int initialiser (double temps) override
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
void imposer_cond_lim (Champ_Inc &, double) override
Impose les conditions aux limites a la valeur temporelle "temps" du
Champ_Inc.
int nb_faces_sortie_libre () const
Zone_PolyMAC & zone_PolyMAC ()
const Zone_PolyMAC & zone_PolyMAC () const
int nb_bord_periodicite () const
Public Member Functions inherited from Zone_Cl_dis_base
Zone_Cl_dis_base ()
~Zone_Cl_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Cond_lim & les_conditions_limites (int) const
Renvoie la i-ieme condition aux limites.
(version const)
Cond_lim & les_conditions_limites (int)
Renvoie la i-ieme condition aux limites.
Conds_lim & les_conditions_limites ()
Renvoie le tableaux des conditions aux limites.
const Conds_lim & les_conditions_limites () const
Renvoie le tableaux des conditions aux limites.
(version const)
int nb_cond_lim () const
Renvoie le nombre de conditions aux limites.
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de toutes les conditions
aux limites.
virtual void mettre_a_jour_ss_pas_dt (double temps)
Effectue une mise a jour pour des sous pas de temps
d'un schema en temps (par exemple dans RungeKutta)
pour toutes les Cond Lims renvoyant 1 par le biais de la methode
int Cond_Lim_base::a_mettre_a_jour_ss_pas_dt();.
void completer ()
Appel Cond_lim_base::completer() sur chaque
condition aux limites.
int contient_Cl (const Nom &)
Renvoie 1 si l'objet contient une condition aux limites
du Nom specifie.
Renvoie 0 sinon.
Zone_dis & zone_dis ()
Renvoie une reference sur la zone discretisee associee aux conditions
aux limites. Cette Zone_dis est associee au travers de l'equation
associee et pas directement a l'objet Zone_Cl_dis_base.
const Zone_dis & zone_dis () const
Renvoie une reference sur la zone discretisee associee aux conditions
aux limites. Cette Zone_dis est associee au travers de l'equation
associee et pas directement a l'objet Zone_Cl_dis_base.
(version const)
Zone & zone ()
const Zone & zone () const
virtual int calculer_coeffs_echange (double temps)
Calcul des coefficients d'echange pour les problemes couples thermiques.
virtual void imposer_cond_lim (Champ_Inc &, double)=0
int nb_faces_Cl () const
virtual const Cond_lim & la_cl_de_la_face (int num_face) const
A partir d'un indice de face de bord dans la Zone_VF,
renvoie la condition aux limites a laquelle cette face
appartient, pour 0 <= num_face < nb_faces_Cl().
const Cond_lim_base & condition_limite_de_la_face_reelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_face_virtuelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere) const
Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere)
void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de toutes les CLs.
void Gpoint (double t1, double t2)
void set_temps_defaut (double temps)
Change le i-eme temps futur de toutes les CLs.
int avancer (double temps)
Tourne la roue des CLs jusqu'au temps donne.
int reculer (double temps)
Tourne la roue des CLsj usqu'au temps donne.
virtual int initialiser (double temps)
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
virtual void associer_inconnue (const Champ_Inc &)
virtual const Champ_Inc & inconnue () const
virtual Champ_Inc & inconnue ()
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_Cl_PolyMAC & self_cast (Objet_U &)
static const Zone_Cl_PolyMAC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_Cl_dis_base
static const Type_info * info ()
static Zone_Cl_dis_base & self_cast (Objet_U &)
static const Zone_Cl_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Zone_Cl_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
void remplir_type_elem_Cl (const Zone_PolyMAC &)
appele par remplir_volumes_entrelaces_Cl() : remplissage de type_elem_Cl_
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
virtual void completer (const Zone_dis &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int modif_perio_fait_
Protected Attributes inherited from Zone_Cl_dis_base
Nom nom_
Conds_lim les_conditions_limites_
Ref_Champ_Inc mon_inconnue
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 39 of file Zone_Cl_PolyMAC.h.
Constructor & Destructor Documentation
Zone_Cl_PolyMAC()
Zone_Cl_PolyMAC::Zone_Cl_PolyMAC ()
Definition at line 34 of file Zone_Cl_PolyMAC.cpp.
~Zone_Cl_PolyMAC()
Zone_Cl_PolyMAC::~Zone_Cl_PolyMAC ()
Definition at line 34 of file Zone_Cl_PolyMAC.cpp.
Member Function Documentation
associer()
void Zone_Cl_PolyMAC::associer (const Zone_PolyMAC & la_zone_PolyMAC)
etape de discretisation : dimensionnement des tableaux
Definition at line 60 of file Zone_Cl_PolyMAC.cpp.
{
// int nb_elem_Cl  = la_zone_PolyMAC.nb_elem_Cl();
}
Referenced by PolyMAC_discretisation::zone_Cl_dis().
completer()
void Zone_Cl_PolyMAC::completer (const Zone_dis & une_zone_dis) override virtual
remplissage des tableaux
Implements Zone_Cl_dis_base.
Definition at line 67 of file Zone_Cl_PolyMAC.cpp.
{
  modif_perio_fait_ =0;
  if (sub_type(Zone_PolyMAC,une_zone_dis.valeur()))
    {
      const Zone_PolyMAC& la_zone_poly = ref_cast(Zone_PolyMAC, une_zone_dis.valeur());
      remplir_type_elem_Cl(la_zone_poly);
    }
  else
    {
      cerr << "Zone_Cl_PolyMAC::completer() prend comme argument une Zone_PolyMAC\n";
      exit();
    }
}
References Process::exit(), modif_perio_fait_, ref_cast, remplir_type_elem_Cl(), sub_type, and Deriv_Zone_dis_base::valeur().
cree_instance()
Objet_U * Zone_Cl_PolyMAC::cree_instance () static
Definition at line 34 of file Zone_Cl_PolyMAC.cpp.
duplique()
int Zone_Cl_PolyMAC::duplique () const override virtual
Implements Objet_U.
Definition at line 34 of file Zone_Cl_PolyMAC.cpp.
get_info()
const Type_info * Zone_Cl_PolyMAC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 34 of file Zone_Cl_PolyMAC.cpp.
imposer_cond_lim()
void Zone_Cl_PolyMAC::imposer_cond_lim (Champ_Inc & ch, double temps) override virtual
Impose les conditions aux limites a la valeur temporelle "temps" du
Champ_Inc.
Implements Zone_Cl_dis_base.
Definition at line 90 of file Zone_Cl_PolyMAC.cpp.
{
  Champ_Inc_base& ch_base=ch.valeur();
  DoubleTab& ch_tab = ch_base.valeurs(temps);
  int n, N = ch_tab.line_size();
  if (sub_type(Champ_Inc_P0_base,ch_base))
    ;
  else if(ch_base.nature_du_champ()==scalaire)
    ;
  else if (sub_type(Champ_Face_PolyMAC,ch_base))
    {
      Champ_Face_PolyMAC& ch_face = ref_cast(Champ_Face_PolyMAC, ch_base);
      const Zone_VF& ma_zone_VF = ch_face.zone_vf();
      int ndeb,nfin, num_face;
      for(int i=0; i<nb_cond_lim(); i++)
        {
          const Cond_lim_base& la_cl = les_conditions_limites(i).valeur();
          if (sub_type(Periodique,la_cl)) abort(); //nope
          else if( sub_type(Symetrie,la_cl) )
            {
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              ndeb = le_bord.num_premiere_face();
              nfin = ndeb + le_bord.nb_faces();
              for (num_face=ndeb; num_face<nfin; num_face++)
                for (n = 0; n < N; n++)
                  ch_tab(num_face, n) = 0;
            }
          else if ( sub_type(Dirichlet_entree_fluide,la_cl) )
            {
              const Dirichlet_entree_fluide& la_cl_diri = ref_cast(Dirichlet_entree_fluide,la_cl);
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              ndeb = le_bord.num_premiere_face();
              nfin = ndeb + le_bord.nb_faces();
              for (num_face=ndeb; num_face<nfin; num_face++)
                for (n = 0; n < N; n++)
                  {
// WEC : optimisable (pour chaque face recherche le bon temps !)
// vn
                    double vn=0;
                    for (int d=0; d<dimension; d++)
                      vn+=ma_zone_VF.face_normales(num_face,d)*la_cl_diri.val_imp_au_temps(temps,num_face-ndeb, N * d + n);
                    vn/=ma_zone_VF.face_surfaces(num_face);
                    ch_tab(num_face, n) = vn;
                  }
            }
          else if ( sub_type(Dirichlet_paroi_fixe,la_cl) )
            {
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              ndeb = le_bord.num_premiere_face();
              nfin = ndeb + le_bord.nb_faces();
              for (num_face=ndeb; num_face<nfin; num_face++)
                for (n = 0; n < N; n++)
                  ch_tab(num_face, n) = 0;
            }
          else if ( sub_type(Dirichlet_paroi_defilante,la_cl) )
            {
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              ndeb = le_bord.num_premiere_face();
              nfin = ndeb + le_bord.nb_faces();
              for (num_face=ndeb; num_face<nfin; num_face++)
                for (n = 0; n < N; n++)
                  ch_tab(num_face, n) = 0;
            }
        }
      modif_perio_fait_  = 1;
    }
  else
    {
      Cerr << "Le type de Champ_Inc " <<  ch->que_suis_je() << " n'est pas prevu en PolyMAC\n";
      exit();
    }
  ch_tab.echange_espace_virtuel();
  Debog::verifier("Zone_Cl_PolyMAC::imposer_cond_lim ch_tab",ch_tab);
}
References Process::abort(), Cerr, Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), Zone_VF::face_normales(), Zone_VF::face_surfaces(), Cond_lim_base::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), modif_perio_fait_, Field_base::nature_du_champ(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), ref_cast, scalaire, sub_type, Dirichlet::val_imp_au_temps(), Deriv_Champ_Inc_base::valeur(), Champ_Inc_base::valeurs(), Debog::verifier(), and Champ_Face_PolyMAC::zone_vf().
info()
const Type_info * Zone_Cl_PolyMAC::info () static
Definition at line 34 of file Zone_Cl_PolyMAC.cpp.
initialiser()
int Zone_Cl_PolyMAC::initialiser (double temps) override virtual
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Returns
int
Signification: 1 si OK, 0 sinon
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 198 of file Zone_Cl_PolyMAC.cpp.
{
  Zone_Cl_dis_base::initialiser(temps);
  if (nb_bord_periodicite()>0)
    {
      Cerr<<" La periodicite n'est pas code !!!"<<finl;
      abort();
    }
  return 1;
}
References Process::abort(), Cerr, finl, Zone_Cl_dis_base::initialiser(), and nb_bord_periodicite().
nb_bord_periodicite()
int Zone_Cl_PolyMAC::nb_bord_periodicite () const
Definition at line 186 of file Zone_Cl_PolyMAC.cpp.
{
  int compteur=0;
  for(int cl=0; cl<les_conditions_limites_.size(); cl++)
    {
      if (sub_type(Periodique,les_conditions_limites_[cl].valeur()))
        compteur++;
    }
  return compteur;
}
References compteur, Zone_Cl_dis_base::les_conditions_limites_, vect_impl::size(), sub_type, and valeur().
Referenced by initialiser().
nb_faces_sortie_libre()
int Zone_Cl_PolyMAC::nb_faces_sortie_libre () const
Definition at line 168 of file Zone_Cl_PolyMAC.cpp.
{
  exit();
  /*
  int compteur=0;
  for(int cl=0; cl<les_conditions_limites_.size(); cl++)
    {
      if(sub_type(Neumann_sortie_libre, les_conditions_limites_[cl].valeur()))
  {
    const Front_VF& le_bord=ref_cast(Front_VF,les_conditions_limites_[cl]->frontiere_dis());
    compteur+=le_bord.nb_faces();
  }
    }
  return compteur;
  */
  return -1;
}
References Process::exit().
printOn()
Sortie & Zone_Cl_PolyMAC::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 38 of file Zone_Cl_PolyMAC.cpp.
{
  return os;
}
readOn()
Entree & Zone_Cl_PolyMAC::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 46 of file Zone_Cl_PolyMAC.cpp.
{
  return Zone_Cl_dis_base::readOn(is) ;
}
References Zone_Cl_dis_base::readOn().
remplir_type_elem_Cl()
void Zone_Cl_PolyMAC::remplir_type_elem_Cl (const Zone_PolyMAC & la_zone_PolyMAC) protected
appele par remplir_volumes_entrelaces_Cl() : remplissage de type_elem_Cl_
Definition at line 83 of file Zone_Cl_PolyMAC.cpp.
{
}
Referenced by completer().
self_cast() [1/2]
const Zone_Cl_PolyMAC & Zone_Cl_PolyMAC::self_cast (const Objet_U & r) static
Definition at line 34 of file Zone_Cl_PolyMAC.cpp.
self_cast() [2/2]
Zone_Cl_PolyMAC & Zone_Cl_PolyMAC::self_cast (Objet_U & r) static
Definition at line 34 of file Zone_Cl_PolyMAC.cpp.
taille_memoire()
unsigned Zone_Cl_PolyMAC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 34 of file Zone_Cl_PolyMAC.cpp.
zone_PolyMAC() [1/2]
Zone_PolyMAC & Zone_Cl_PolyMAC::zone_PolyMAC ()
Definition at line 210 of file Zone_Cl_PolyMAC.cpp.
{
  return ref_cast(Zone_PolyMAC, zone_dis().valeur());
}
References ref_cast, valeur(), and Zone_Cl_dis_base::zone_dis().
zone_PolyMAC() [2/2]
const Zone_PolyMAC & Zone_Cl_PolyMAC::zone_PolyMAC () const
Definition at line 215 of file Zone_Cl_PolyMAC.cpp.
{
  return ref_cast(Zone_PolyMAC, zone_dis().valeur());
}
References ref_cast, valeur(), and Zone_Cl_dis_base::zone_dis().
Member Data Documentation
info_obj
const Type_info Zone_Cl_PolyMAC::info_obj static
Definition at line 42 of file Zone_Cl_PolyMAC.h.
modif_perio_fait_
int Zone_Cl_PolyMAC::modif_perio_fait_ protected
Definition at line 63 of file Zone_Cl_PolyMAC.h.
Referenced by completer(), and imposer_cond_lim().
The documentation for this class was generated from the following files:
src/PolyMAC/Zones/Zone_Cl_PolyMAC.h
src/PolyMAC/Zones/Zone_Cl_PolyMAC.cpp