TRUST: Champ_Uniforme Class Reference
Champ_Uniforme Class Reference
classe Champ_Uniforme
Represente un champ constant dans l'espace et dans le temps.
#include <Champ_Uniforme.h>
Public Member Functions
Champ_Uniforme ()
~Champ_Uniforme ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Champ_base & affecter_ (const Champ_base &ch)
Renvoie l'objet upcaste en Champ_base.
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Renvoie la valeur du champ au point specifie
par ses coordonnees.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
Renvoie la valeur d'une composante du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees.
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Renvoie la valeur de la composante du champ au point specifie
par ses coordonnees.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Uniforme & self_cast (Objet_U &)
static const Champ_Uniforme & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le champ sur un flot de sortie.
Imprime la taille du tableau et les valeurs.
virtual Entree & readOn (Entree &)
Lit un champ a partir d'un flot d'entree.
On lit le nombre de composante du champ (nb_comp)
et les valeurs de ces composantes.
Format:
Champ_Uniforme nb_comp vrel_1 ... [vrel_i].
Detailed Description
classe Champ_Uniforme
Represente un champ constant dans l'espace et dans le temps.
Definition at line 39 of file Champ_Uniforme.h.
Constructor & Destructor Documentation
Champ_Uniforme::Champ_Uniforme ()
Definition at line 26 of file Champ_Uniforme.cpp.
Champ_Uniforme::~Champ_Uniforme ()
Definition at line 26 of file Champ_Uniforme.cpp.
Member Function Documentation
Champ_base & Champ_Uniforme::affecter_ (const Champ_base & ch) [virtual]
Renvoie l'objet upcaste en Champ_base.
Returns:
Champ_base&
Signification: renvoie (*this) upcaste en Champ_base
Contraintes:
Reimplemented from Champ_Don_base.
Reimplemented in Ch_input_uniforme.
Definition at line 100 of file Champ_Uniforme.cpp.
References Cerr, Process::exit(), finl, Objet_U::que_suis_je(), sub_type, Champ_Proto::valeurs(), and Champ_Don_base::valeurs().
{
  if(sub_type(Champ_Uniforme, ch))
    {
      valeurs()=ch.valeurs();
    }
  else
    {
      Cerr << "We do not know how to make Champ_Uniforme::affecter_("<<ch.que_suis_je() << finl;
      exit();
    }
  return *this;
}
Objet_U * Champ_Uniforme::cree_instance () [static]
Reimplemented in Ch_input_uniforme, Champ_Fonc_t, and Champ_Tabule_Temps.
Definition at line 26 of file Champ_Uniforme.cpp.
int Champ_Uniforme::duplique () const [virtual]
Implements Champ_Don_base.
Reimplemented in Ch_input_uniforme, Champ_Fonc_t, Champ_Tabule_Temps, and Champ_Uniforme_inst.
Definition at line 26 of file Champ_Uniforme.cpp.
const Type_info * Champ_Uniforme::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Reimplemented in Ch_input_uniforme, Champ_Fonc_t, Champ_Tabule_Temps, and Champ_Uniforme_inst.
Definition at line 26 of file Champ_Uniforme.cpp.
const Type_info * Champ_Uniforme::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Reimplemented in Ch_input_uniforme, Champ_Fonc_t, Champ_Tabule_Temps, and Champ_Uniforme_inst.
Definition at line 26 of file Champ_Uniforme.cpp.
Sortie & Champ_Uniforme::printOn (Sortie & os) const [protected, virtual]
Imprime le champ sur un flot de sortie.
Imprime la taille du tableau et les valeurs.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Don_base.
Reimplemented in Ch_input_uniforme, Champ_Fonc_t, Champ_Tabule_Temps, and Champ_Uniforme_inst.
Definition at line 44 of file Champ_Uniforme.cpp.
References DoubleVect::size(), and Champ_Don_base::valeurs().
{
  const DoubleTab& tab=valeurs();
  os << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    os << tab(0,i);
  return os;
}
Entree & Champ_Uniforme::readOn (Entree & is) [protected, virtual]
Lit un champ a partir d'un flot d'entree.
On lit le nombre de composante du champ (nb_comp)
et les valeurs de ces composantes.
Format:
Champ_Uniforme nb_comp vrel_1 ... [vrel_i].
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Don_base.
Reimplemented in Ch_input_uniforme, Champ_Fonc_t, Champ_Tabule_Temps, and Champ_Uniforme_inst.
Definition at line 72 of file Champ_Uniforme.cpp.
References Champ_Don_base::dimensionner(), Champ_Proto::lire_dimension(), Objet_U::que_suis_je(), and Champ_Don_base::valeurs().
{
  int dim;
  DoubleTab& tab=valeurs();
// is >> dim;
  dim=lire_dimension(is,que_suis_je());
  dimensionner(1,dim);
  for(int i=0; i<dim; i++)
    is >> tab(0,i);
  return is;
}
Champ_Uniforme & Champ_Uniforme::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Don_base.
Reimplemented in Ch_input_uniforme, Champ_Fonc_t, Champ_Tabule_Temps, and Champ_Uniforme_inst.
Definition at line 26 of file Champ_Uniforme.cpp.
const Champ_Uniforme & Champ_Uniforme::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Don_base.
Reimplemented in Ch_input_uniforme, Champ_Fonc_t, Champ_Tabule_Temps, and Champ_Uniforme_inst.
Definition at line 26 of file Champ_Uniforme.cpp.
unsigned Champ_Uniforme::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Ch_input_uniforme, Champ_Fonc_t, and Champ_Tabule_Temps.
Definition at line 26 of file Champ_Uniforme.cpp.
DoubleVect & Champ_Uniforme::valeur_a (const DoubleVect & position, DoubleVect & tab_valeurs) const [virtual]
Renvoie la valeur du champ au point specifie
par ses coordonnees.
Returns:
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 135 of file Champ_Uniforme.cpp.
References Field_base::nb_comp(), and Champ_Don_base::valeurs_.
{
  for(int j=0; j<nb_comp(); j++)
    tab_valeurs(j)=valeurs_(0,j);
  return tab_valeurs;
}
double Champ_Uniforme::valeur_a_compo (const DoubleVect & position, int ncomp) const [virtual]
Renvoie la valeur de la composante du champ au point specifie
par ses coordonnees.
Returns:
double
Signification: la valeur de la composante du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 169 of file Champ_Uniforme.cpp.
References Champ_Don_base::valeurs_.
{
  return valeurs_(0,ncomp);
}
DoubleVect & Champ_Uniforme::valeur_a_elem (const DoubleVect & position, DoubleVect & tab_valeurs, int le_poly) const [virtual]
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Returns:
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 202 of file Champ_Uniforme.cpp.
References Field_base::nb_comp(), and Champ_Don_base::valeurs_.
{
  for(int j=0; j<nb_comp(); j++)
    tab_valeurs(j)=valeurs_(0,j);
  return tab_valeurs;
}
double Champ_Uniforme::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const [virtual]
Renvoie la valeur d'une composante du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Returns:
double
Signification: la valeur de la composante du champ specifiee au
point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 239 of file Champ_Uniforme.cpp.
References Champ_Don_base::valeurs_.
{
  return valeurs_(0,ncomp);
}
DoubleTab & Champ_Uniforme::valeur_aux (const DoubleTab & positions, DoubleTab & tab_valeurs) const [virtual]
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 266 of file Champ_Uniforme.cpp.
References DoubleTab::dimension(), DoubleTab::dimension_tot(), DoubleTab::nb_dim(), and Champ_Don_base::valeurs_.
{
// GF dimension_tot pour que la ligne soit valide pour les champs P1B
  for(int i=0; i<tab_valeurs.dimension_tot(0); i++)
    if (tab_valeurs.nb_dim()==1)
      tab_valeurs(i)=valeurs_(0,0);
    else
      for(int j=0; j<tab_valeurs.dimension(1); j++)
        tab_valeurs(i,j)=valeurs_(0,j);
  return tab_valeurs;
}
DoubleVect & Champ_Uniforme::valeur_aux_compo (const DoubleTab & positions, DoubleVect & tab_valeurs, int ncomp) const [virtual]
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees.
Returns:
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 307 of file Champ_Uniforme.cpp.
References Champ_Don_base::valeurs_.
{
  return tab_valeurs=valeurs_(0,ncomp);
}
DoubleTab & Champ_Uniforme::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & tab_valeurs) const [virtual]
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 341 of file Champ_Uniforme.cpp.
References DoubleTab::dimension(), DoubleTab::nb_dim(), and Champ_Don_base::valeurs_.
{
  for(int i=0; i<tab_valeurs.dimension(0); i++)
    if (tab_valeurs.nb_dim()==1)
      tab_valeurs(i)=valeurs_(0,0);
    else
      for(int j=0; j<tab_valeurs.dimension(1); j++)
        tab_valeurs(i,j)=valeurs_(0,j);
  return tab_valeurs;
}
DoubleVect & Champ_Uniforme::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & tab_valeurs, int ncomp) const [virtual]
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 389 of file Champ_Uniforme.cpp.
References Champ_Don_base::valeurs_.
{
  return tab_valeurs=valeurs_(0,ncomp);
}
Member Data Documentation
const Type_info Champ_Uniforme::info_obj [static]
Reimplemented from Champ_Don_base.
Reimplemented in Ch_input_uniforme, Champ_Fonc_t, Champ_Tabule_Temps, and Champ_Uniforme_inst.
Definition at line 42 of file Champ_Uniforme.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Uniforme.h
src/Kernel/Champs/Champ_Uniforme.cpp