TRUST: Matrix_tools Class Reference
Matrix_tools Class Reference
#include <Matrix_tools.h>
Static Public Member Functions
static void convert_to_morse_matrix (const Matrice_Base &in, Matrice_Morse &out)
static void convert_to_symmetric_morse_matrix (const Matrice_Base &in, Matrice_Morse_Sym &out)
static bool is_normalized_stencil (const IntTab &stencil)
static bool is_normalized_symmetric_stencil (const IntTab &stencil)
static void allocate_morse_matrix (const int nb_lines, const int nb_columns, const IntTab &stencil, Matrice_Morse &matrix, const bool &attach_stencil_to_matrix=false)
static void build_morse_matrix (const int nb_lines, const int nb_columns, const IntTab &stencil, const ArrOfDouble &coefficients, Matrice_Morse &matrix)
static void allocate_symmetric_morse_matrix (const int order, const IntTab &stencil, Matrice_Morse_Sym &matrix)
static void build_symmetric_morse_matrix (const int order, const IntTab &stencil, const ArrOfDouble &coefficients, Matrice_Morse_Sym &matrix)
static void allocate_for_scaled_addition (const Matrice &A, const Matrice &B, Matrice &C)
static void allocate_for_symmetric_scaled_addition (const Matrice &A, const Matrice &B, Matrice &C)
static void add_scaled_matrices (const Matrice &A, const double alpha, const Matrice &B, const double beta, Matrice &C)
static void add_symmetric_scaled_matrices (const Matrice &A, const double alpha, const Matrice &B, const double beta, Matrice &C)
static bool is_null_stencil (const IntTab &stencil)
static bool is_diagonal_stencil (const int nb_lines, const int nb_columns, const IntTab &stencil)
static void allocate_from_stencil (const int nb_lines, const int nb_columns, const IntTab &stencil, Matrice &matrix, const bool &attach_stencil_to_matrix=false)
static void extend_matrix_stencil (const IntTab &stencil, Matrice &matrix, const bool &attach_stencil_to_matrix=false)
static void matdiag_mult_matmorse (const DoubleTab &diag, Matrice_Morse &mat, const bool &inverse)
static void matmorse_mult_matdiag (const DoubleTab &diag, Matrice_Morse &mat, const bool &inverse)
static void uniform_matdiag_mult_matmorse (const double diag, Matrice_Morse &mat, const bool &inverse)
static void matmorse_mult_uniform_matdiag (const double diag, Matrice_Morse &mat, const bool &inverse)
static void extend_matrix (Matrice_Morse &mat, int nl, int nc)
Detailed Description
Definition at line 26 of file Matrix_tools.h.
Member Function Documentation
add_scaled_matrices()
void Matrix_tools::add_scaled_matrices (const Matrice & A, const double alpha, const Matrice & B, const double beta, Matrice & C) static
Definition at line 348 of file Matrix_tools.cpp.
{
  assert( sub_type( Matrice_Morse, C.valeur( ) ) );
  Matrice_Morse& C_ = ref_cast( Matrice_Morse, C.valeur( ) );
  assert( C_.check_sorted_morse_matrix_structure( ) );
  IntTab A_stencil;
  ArrOfDouble A_coefficients;
  A.valeur( ).get_stencil_and_coefficients( A_stencil,
                                            A_coefficients );
  IntTab B_stencil;
  ArrOfDouble B_coefficients;
  B.valeur( ).get_stencil_and_coefficients( B_stencil,
                                            B_coefficients );
  int A_k = 0;
  int B_k = 0;
  C_.get_set_coeff() = 0.0 ;
  const int nb_lines = C_.nb_lignes( );
  for ( int i=0; i<nb_lines; ++i )
    {
      int k0   = C_.get_tab1()( i ) - 1;
      int k1   = C_.get_tab1()( i + 1 ) - 1;
      for ( int k=k0; k<k1; ++k )
        {
          int j = C_.get_tab2()( k ) - 1;
          if ( ( A_k < A_stencil.dimension( 0 ) ) && ( A_stencil( A_k, 0 ) == i ) && ( A_stencil( A_k, 1 ) == j ) )
            {
              C_.get_set_coeff()( k ) += alpha * A_coefficients[ A_k ];
              ++A_k;
            }
          if ( ( B_k < B_stencil.dimension( 0 ) ) && ( B_stencil( B_k, 0 ) == i ) && ( B_stencil( B_k, 1 ) == j ) )
            {
              C_.get_set_coeff()( k ) += beta * B_coefficients[ B_k ];
              ++B_k;
            }
        }
    }
  assert( A_k == A_coefficients.size_array( ) );
  assert( B_k == B_coefficients.size_array( ) );
}
References Matrice_Morse::check_sorted_morse_matrix_structure(), TRUSTTab< _TYPE_ >::dimension(), Matrice_Morse::get_set_coeff(), Matrice_Base::get_stencil_and_coefficients(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::nb_lignes(), ref_cast, TRUSTArray< _TYPE_ >::size_array(), sub_type, and Deriv_Matrice_Base::valeur().
add_symmetric_scaled_matrices()
void Matrix_tools::add_symmetric_scaled_matrices (const Matrice & A, const double alpha, const Matrice & B, const double beta, Matrice & C) static
Definition at line 402 of file Matrix_tools.cpp.
{
  assert( sub_type( Matrice_Morse_Sym, C.valeur( ) ) );
  Matrice_Morse_Sym& C_ = ref_cast( Matrice_Morse_Sym, C.valeur( ) );
  assert( C_.check_sorted_symmetric_morse_matrix_structure( ) );
  IntTab A_stencil;
  ArrOfDouble A_coefficients;
  A.valeur( ).get_symmetric_stencil_and_coefficients( A_stencil,
                                                      A_coefficients );
  IntTab B_stencil;
  ArrOfDouble B_coefficients;
  B.valeur( ).get_symmetric_stencil_and_coefficients( B_stencil,
                                                      B_coefficients );
  int A_k = 0;
  int B_k = 0;
  C_.get_set_coeff() = 0.0 ;
  const int nb_lines = C_.nb_lignes( );
  for ( int i=0; i<nb_lines; ++i )
    {
      int k0   = C_.get_tab1()( i ) - 1;
      int k1   = C_.get_tab1()( i + 1 ) - 1;
      for ( int k=k0; k<k1; ++k )
        {
          int j = C_.get_tab2()( k ) - 1;
          if ( ( A_k < A_stencil.dimension( 0 ) ) && ( A_stencil( A_k, 0 ) == i ) && ( A_stencil( A_k, 1 ) == j ) )
            {
              C_.get_set_coeff()( k ) += alpha * A_coefficients[ A_k ];
              ++A_k;
            }
          if ( ( B_k < B_stencil.dimension( 0 ) ) && ( B_stencil( B_k, 0 ) == i ) && ( B_stencil( B_k, 1 ) == j ) )
            {
              C_.get_set_coeff()( k ) += beta * B_coefficients[ B_k ];
              ++B_k;
            }
        }
    }
  assert( A_k == A_coefficients.size_array( ) );
  assert( B_k == B_coefficients.size_array( ) );
}
References Matrice_Morse_Sym::check_sorted_symmetric_morse_matrix_structure(), TRUSTTab< _TYPE_ >::dimension(), Matrice_Morse::get_set_coeff(), Matrice_Base::get_symmetric_stencil_and_coefficients(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::nb_lignes(), ref_cast, TRUSTArray< _TYPE_ >::size_array(), sub_type, and Deriv_Matrice_Base::valeur().
allocate_for_scaled_addition()
void Matrix_tools::allocate_for_scaled_addition (const Matrice & A, const Matrice & B, Matrice & C) static
Definition at line 260 of file Matrix_tools.cpp.
{
  assert( A.valeur( ).nb_lignes( )   == B.valeur( ).nb_lignes( )   );
  assert( A.valeur( ).nb_colonnes( ) == B.valeur( ).nb_colonnes( ) );
  IntTab A_stencil;
  A.valeur( ).get_stencil( A_stencil );
  const int A_size = A_stencil.dimension( 0 );
  IntTab B_stencil;
  B.valeur( ).get_stencil( B_stencil );
  const int B_size = B_stencil.dimension( 0 );
  int size = A_size + B_size;
  IntTab stencil;
  stencil.set_smart_resize( 1 );
  stencil.resize( size, 2 );
  for ( int i=0; i<A_size; ++i )
    {
      stencil( i , 0 ) = A_stencil( i, 0 );
      stencil( i , 1 ) = A_stencil( i, 1 ) ;
    }
  for ( int i=0; i<B_size; ++i )
    {
      stencil( i+A_size , 0 ) = B_stencil( i, 0 );
      stencil( i+A_size , 1 ) = B_stencil( i, 1 ) ;
    }
  tableau_trier_retirer_doublons( stencil );
  C.typer( "Matrice_Morse" );
  Matrice_Morse& C_ = ref_cast( Matrice_Morse, C.valeur( ) );
  allocate_morse_matrix( A.valeur( ).nb_lignes( ),
                         A.valeur( ).nb_colonnes( ),
                         stencil,
                         C_ );
}
References allocate_morse_matrix(), TRUSTTab< _TYPE_ >::dimension(), Matrice_Base::get_stencil(), Matrice_Base::nb_colonnes(), Matrice_Base::nb_lignes(), ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), tableau_trier_retirer_doublons(), Deriv_::typer(), and Deriv_Matrice_Base::valeur().
allocate_for_symmetric_scaled_addition()
void Matrix_tools::allocate_for_symmetric_scaled_addition (const Matrice & A, const Matrice & B, Matrice & C) static
Definition at line 303 of file Matrix_tools.cpp.
{
  assert( A.valeur( ).nb_lignes( )   == A.valeur( ).nb_lignes( )   );
  assert( A.valeur( ).nb_lignes( )   == B.valeur( ).nb_lignes( )   );
  assert( A.valeur( ).nb_colonnes( ) == B.valeur( ).nb_colonnes( ) );
  IntTab A_stencil;
  A.valeur( ).get_symmetric_stencil( A_stencil );
  const int A_size = A_stencil.dimension( 0 );
  IntTab B_stencil;
  B.valeur( ).get_symmetric_stencil( B_stencil );
  const int B_size = B_stencil.dimension( 0 );
  int size = A_size + B_size;
  IntTab stencil;
  stencil.set_smart_resize( 1 );
  stencil.resize( size, 2 );
  for ( int i=0; i<A_size; ++i )
    {
      stencil( i , 0 ) = A_stencil( i, 0 );
      stencil( i , 1 ) = A_stencil( i, 1 ) ;
    }
  for ( int i=0; i<B_size; ++i )
    {
      stencil( i+A_size , 0 ) = B_stencil( i, 0 );
      stencil( i+A_size , 1 ) = B_stencil( i, 1 ) ;
    }
  tableau_trier_retirer_doublons( stencil );
  C.typer( "Matrice_Morse_Sym" );
  Matrice_Morse_Sym& C_ = ref_cast( Matrice_Morse_Sym, C.valeur( ) );
  allocate_symmetric_morse_matrix( A.valeur( ).nb_lignes( ),
                                   stencil,
                                   C_ );
}
References allocate_symmetric_morse_matrix(), TRUSTTab< _TYPE_ >::dimension(), Matrice_Base::get_symmetric_stencil(), Matrice_Base::nb_colonnes(), Matrice_Base::nb_lignes(), ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), tableau_trier_retirer_doublons(), Deriv_::typer(), and Deriv_Matrice_Base::valeur().
allocate_from_stencil()
void Matrix_tools::allocate_from_stencil (const int nb_lines, const int nb_columns, const IntTab & stencil, Matrice & matrix, const bool & attach_stencil_to_matrix = false) static
Definition at line 499 of file Matrix_tools.cpp.
{
  if ( is_null_stencil( stencil ) )
    {
      matrix.typer( "Matrice_Nulle" );
      Matrice_Nulle& matrix_ = ref_cast( Matrice_Nulle, matrix.valeur( ) );
      matrix_.dimensionner( nb_lines, nb_columns );
    }
  else if ( is_diagonal_stencil( nb_lines,
                                 nb_columns,
                                 stencil ) )
    {
      matrix.typer( "Matrice_Diagonale" );
      Matrice_Diagonale& matrix_ = ref_cast( Matrice_Diagonale, matrix.valeur( ) );
      matrix_.dimensionner( nb_lines );
      if( attach_stencil_to_matrix )
        {
          matrix_.set_stencil( stencil );
        }
    }
  else
    {
      matrix.typer( "Matrice_Morse" );
      Matrice_Morse& matrix_ = ref_cast( Matrice_Morse, matrix.valeur( ) );
      allocate_morse_matrix( nb_lines,
                             nb_columns,
                             stencil,
                             matrix_,
                             attach_stencil_to_matrix );
    }
}
References allocate_morse_matrix(), Matrice_Nulle::dimensionner(), Matrice_Diagonale::dimensionner(), is_diagonal_stencil(), is_null_stencil(), ref_cast, Matrice_Base::set_stencil(), Deriv_::typer(), and Deriv_Matrice_Base::valeur().
Referenced by extend_matrix_stencil().
allocate_morse_matrix()
void Matrix_tools::allocate_morse_matrix (const int nb_lines, const int nb_columns, const IntTab & stencil, Matrice_Morse & matrix, const bool & attach_stencil_to_matrix = false) static
Definition at line 104 of file Matrix_tools.cpp.
{
  assert( is_normalized_stencil( stencil ) );
  const int nb_coefficients = stencil.dimension( 0 );
  matrix.dimensionner( nb_lines,
                       nb_columns,
                       nb_coefficients );
  if ( nb_coefficients > 0 )
    {
      matrix.get_set_tab1( ) = 0 ;
      matrix.get_set_tab1( )( 0 ) = 1;
      for ( int i=0; i<nb_coefficients; ++i )
        {
          assert( stencil( i ,0 ) >= 0         );
          assert( stencil( i ,0 ) < nb_lines   );
          assert( stencil( i ,1 ) >= 0         );
          assert( stencil( i ,1 ) < nb_columns );
          matrix.get_set_tab1( )( stencil( i, 0 ) + 1 ) += 1;
          matrix.get_set_tab2( )( i ) = stencil( i, 1 ) + 1;
        }
      for ( int i=0; i<nb_lines; ++i )
        {
          matrix.get_set_tab1()( i + 1 ) += matrix.get_tab1()( i );
        }
    }
  if( attach_stencil_to_matrix )
    {
      matrix.set_stencil( stencil );
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Matrice_Morse::dimensionner(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), is_normalized_stencil(), and Matrice_Base::set_stencil().
Referenced by allocate_for_scaled_addition(), allocate_from_stencil(), SETS::assembler(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Domain_Graph::construire_graph_from_segment(), Op_Div_PolyMAC_P0::dimensionner(), Op_VDF_Elem::dimensionner_bloc_vitesse(), Masse_PolyMAC_Face::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_VDF_Face::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Div_PolyMAC::dimensionner_blocs(), Op_Grad_PolyMAC_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Masse_PolyMAC_Elem::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::dimensionner_blocs(), Flux_interfacial_PolyMAC::dimensionner_blocs(), Force_Tchen_PolyMAC_P0::dimensionner_blocs(), Frottement_interfacial_PolyMAC_P0::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs(), Travail_pression_PolyMAC::dimensionner_blocs(), Op_Diff_PolyMAC_Elem::dimensionner_blocs_ext(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Assembleur_P_PolyMAC::dimensionner_continuite(), Assembleur_P_PolyMAC_P0::dimensionner_continuite(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), and SETS::eliminer().
allocate_symmetric_morse_matrix()
void Matrix_tools::allocate_symmetric_morse_matrix (const int order, const IntTab & stencil, Matrice_Morse_Sym & matrix) static
Definition at line 184 of file Matrix_tools.cpp.
{
  assert( is_normalized_symmetric_stencil( stencil ) );
  const int nb_coefficients = stencil.dimension( 0 );
  matrix.dimensionner( order,
                       order,
                       nb_coefficients );
  if ( nb_coefficients > 0 )
    {
      matrix.get_set_tab1()= 0 ;
      matrix.get_set_tab1()( 0 ) = 1;
      for ( int i=0; i<nb_coefficients; ++i )
        {
          assert( stencil( i ,0 ) >= 0               );
          assert( stencil( i ,0 ) < order            );
          assert( stencil( i ,1 ) >= 0               );
          assert( stencil( i ,1 ) < order            );
          assert( stencil( i, 0 ) <= stencil( i, 1 ) );
          matrix.get_set_tab1()( stencil( i, 0 ) + 1 ) += 1;
          matrix.get_set_tab2()( i ) = stencil( i, 1 ) + 1;
        }
      for ( int i=0; i<order; ++i )
        {
          matrix.get_set_tab1()( i + 1 ) += matrix.get_tab1()( i );
        }
    }
  matrix.set_symmetric( 1 );
}
References TRUSTTab< _TYPE_ >::dimension(), Matrice_Morse::dimensionner(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), is_normalized_symmetric_stencil(), and Matrice_Morse::set_symmetric().
Referenced by allocate_for_symmetric_scaled_addition().
build_morse_matrix()
void Matrix_tools::build_morse_matrix (const int nb_lines, const int nb_columns, const IntTab & stencil, const ArrOfDouble & coefficients, Matrice_Morse & matrix) static
Definition at line 144 of file Matrix_tools.cpp.
{
  assert( is_normalized_stencil( stencil ) );
  const int nb_coefficients = stencil.dimension( 0 );
  assert( nb_coefficients == coefficients.size_array( ) );
  matrix.dimensionner( nb_lines,
                       nb_columns,
                       nb_coefficients );
  if ( nb_coefficients > 0 )
    {
      matrix.get_set_tab1() =0  ;
      matrix.get_set_tab1()( 0 ) = 1;
      for ( int i=0; i<nb_coefficients; ++i )
        {
          assert( stencil( i ,0 ) >= 0         );
          assert( stencil( i ,0 ) < nb_lines   );
          assert( stencil( i ,1 ) >= 0         );
          assert( stencil( i ,1 ) < nb_columns );
          matrix.get_set_tab1()( stencil( i, 0 ) + 1 ) += 1;
          matrix.get_set_tab2()( i ) = stencil( i, 1 ) + 1;
          matrix.get_set_coeff()( i ) = coefficients[ i ];
        }
      for ( int i=0; i<nb_lines; ++i )
        {
          matrix.get_set_tab1()( i + 1 ) += matrix.get_tab1()( i );
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Matrice_Morse::dimensionner(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), is_normalized_stencil(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by convert_to_morse_matrix().
build_symmetric_morse_matrix()
void Matrix_tools::build_symmetric_morse_matrix (const int order, const IntTab & stencil, const ArrOfDouble & coefficients, Matrice_Morse_Sym & matrix) static
Definition at line 220 of file Matrix_tools.cpp.
{
  assert( is_normalized_symmetric_stencil( stencil ) );
  const int nb_coefficients = stencil.dimension( 0 );
  assert( nb_coefficients == coefficients.size_array( ) );
  matrix.dimensionner( order,
                       order,
                       nb_coefficients );
  if ( nb_coefficients > 0 )
    {
      matrix.get_set_tab1() = 0 ;
      matrix.get_set_tab1()( 0 ) = 1;
      for ( int i=0; i<nb_coefficients; ++i )
        {
          assert( stencil( i ,0 ) >= 0               );
          assert( stencil( i ,0 ) < order            );
          assert( stencil( i ,1 ) >= 0               );
          assert( stencil( i ,1 ) < order            );
          assert( stencil( i, 0 ) <= stencil( i, 1 ) );
          matrix.get_set_tab1()( stencil( i, 0 ) + 1 ) += 1;
          matrix.get_set_tab2()( i )  = stencil( i, 1 ) + 1;
          matrix.get_set_coeff()( i ) = coefficients[ i ];
        }
      for ( int i=0; i<order; ++i )
        {
          matrix.get_set_tab1()( i + 1 ) += matrix.get_tab1()( i );
        }
    }
  matrix.set_symmetric( 1 );
}
References TRUSTTab< _TYPE_ >::dimension(), Matrice_Morse::dimensionner(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), is_normalized_symmetric_stencil(), Matrice_Morse::set_symmetric(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by convert_to_symmetric_morse_matrix().
convert_to_morse_matrix()
void Matrix_tools::convert_to_morse_matrix (const Matrice_Base & in, Matrice_Morse & out) static
Definition at line 27 of file Matrix_tools.cpp.
{
  IntTab stencil;
  ArrOfDouble coefficients;
  in.get_stencil_and_coefficients( stencil, coefficients );
  Matrix_tools::build_morse_matrix( in.nb_lignes( ),
                                    in.nb_colonnes( ),
                                    stencil,
                                    coefficients,
                                    out );
}
References build_morse_matrix(), Matrice_Base::get_stencil_and_coefficients(), Matrice_Base::nb_colonnes(), and Matrice_Base::nb_lignes().
Referenced by Matrice_Bloc::BlocToMatMorse(), disp_m(), Matrice_Base::get_symmetric_stencil(), and Matrice_Base::get_symmetric_stencil_and_coefficients().
convert_to_symmetric_morse_matrix()
void Matrix_tools::convert_to_symmetric_morse_matrix (const Matrice_Base & in, Matrice_Morse_Sym & out) static
Definition at line 45 of file Matrix_tools.cpp.
{
  assert( in.nb_lignes( ) == in.nb_colonnes( ) );
  IntTab stencil;
  ArrOfDouble coefficients;
  in.get_symmetric_stencil_and_coefficients( stencil, coefficients );
  Matrix_tools::build_symmetric_morse_matrix( in.nb_lignes( ),
                                              stencil,
                                              coefficients,
                                              out );
}
References build_symmetric_morse_matrix(), Matrice_Base::get_symmetric_stencil_and_coefficients(), Matrice_Base::nb_colonnes(), and Matrice_Base::nb_lignes().
Referenced by Matrice_Bloc_Sym::BlocSymToMatMorseSym().
extend_matrix()
void Matrix_tools::extend_matrix (Matrice_Morse & mat, int nl, int nc) static
Definition at line 652 of file Matrix_tools.cpp.
{
  IntVect& tab1 = mat.get_set_tab1(), old_tab1 = tab1;
  tab1.reset(), tab1.resize(nl + 1);
  for (int i = 0; i <= nl; i++) tab1(i) = old_tab1(std::min(i, old_tab1.size() - 1));
  mat.set_nb_columns(nc); //plus facile
}
References Matrice_Morse::get_set_tab1(), TRUSTVect< _TYPE_ >::reset(), TRUSTVect< _TYPE_ >::resize(), and Matrice_Morse::set_nb_columns().
extend_matrix_stencil()
void Matrix_tools::extend_matrix_stencil (const IntTab & stencil, Matrice & matrix, const bool & attach_stencil_to_matrix = false) static
Definition at line 536 of file Matrix_tools.cpp.
{
  if ( ! ( is_null_stencil( stencil ) ) )
    {
      const int nb_lines   = matrix.valeur( ).nb_lignes( );
      const int nb_columns = matrix.valeur( ).nb_colonnes( );
      IntTab full_stencil;
      matrix.valeur( ).get_stencil( full_stencil );
      full_stencil.set_smart_resize( 1 );
      const int size = stencil.dimension( 0 );
      const int old_size = full_stencil.size( ) / 2 ;
      full_stencil.resize( old_size + size, 2);
      for ( int i=0; i<size; ++i )
        {
          full_stencil( old_size + i , 0 ) = stencil( i, 0 );
          full_stencil( old_size + i , 1 ) = stencil( i, 1 );
        }
      tableau_trier_retirer_doublons( full_stencil );
      allocate_from_stencil( nb_lines,
                             nb_columns,
                             full_stencil,
                             matrix ,
                             attach_stencil_to_matrix );
    }
}
References allocate_from_stencil(), TRUSTTab< _TYPE_ >::dimension(), Matrice_Base::get_stencil(), is_null_stencil(), Matrice_Base::nb_colonnes(), Matrice_Base::nb_lignes(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTVect< _TYPE_ >::size(), tableau_trier_retirer_doublons(), and Deriv_Matrice_Base::valeur().
is_diagonal_stencil()
bool Matrix_tools::is_diagonal_stencil (const int nb_lines, const int nb_columns, const IntTab & stencil) static
Definition at line 462 of file Matrix_tools.cpp.
{
  if ( nb_lines != nb_columns )
    {
      return false;
    }
  const int size = stencil.dimension( 0 );
  if ( size == 0 )
    {
      return false;
    }
  for ( int i=0; i<size; ++i )
    {
      if ( stencil( i, 0 ) != stencil( i, 1 ) )
        {
          return false;
        }
      if ( stencil( i, 0 ) >= nb_lines )
        {
          return false;
        }
      if ( stencil( i, 1 ) >= nb_columns )
        {
          return false;
        }
    }
  return true;
}
References TRUSTTab< _TYPE_ >::dimension().
Referenced by allocate_from_stencil().
is_normalized_stencil()
bool Matrix_tools::is_normalized_stencil (const IntTab & stencil) static
Definition at line 62 of file Matrix_tools.cpp.
{
  const int size = stencil.dimension( 0 );
  for ( int i=1; i<size; ++i )
    {
      int delta1 = stencil( i-1, 0 ) - stencil( i, 0 );
      int delta2 = stencil( i-1, 1 ) - stencil( i, 1 );
      int delta  = ( delta1 == 0 ) ? delta2 : delta1;
      if ( delta >= 0 )
        {
          return false;
        }
    }
  return true;
}
References TRUSTTab< _TYPE_ >::dimension().
Referenced by allocate_morse_matrix(), build_morse_matrix(), and is_normalized_symmetric_stencil().
is_normalized_symmetric_stencil()
bool Matrix_tools::is_normalized_symmetric_stencil (const IntTab & stencil) static
Definition at line 80 of file Matrix_tools.cpp.
{
  if ( ! ( is_normalized_stencil( stencil ) ) )
    {
      Cerr << "non-normalized stencil" << finl;
      return false;
    }
  const int size = stencil.dimension( 0 );
  for ( int i=0; i<size; ++i )
    {
      int delta = stencil( i, 0 ) - stencil( i, 1 );
      if ( delta > 0 )
        {
          Cerr << "( " << i << " ) line index > column index : ( " << stencil( i, 0 ) << ", " << stencil( i, 1 ) << " )" << finl;
          return false;
        }
    }
  return true;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), finl, and is_normalized_stencil().
Referenced by allocate_symmetric_morse_matrix(), and build_symmetric_morse_matrix().
is_null_stencil()
bool Matrix_tools::is_null_stencil (const IntTab & stencil) static
Definition at line 457 of file Matrix_tools.cpp.
{
  return ( stencil.dimension( 0 ) == 0 );
}
References TRUSTTab< _TYPE_ >::dimension().
Referenced by allocate_from_stencil(), and extend_matrix_stencil().
matdiag_mult_matmorse()
void Matrix_tools::matdiag_mult_matmorse (const DoubleTab & diag, Matrice_Morse & mat, const bool & inverse) static
< nnz sur la ligne i
< indice de la colonne
Definition at line 572 of file Matrix_tools.cpp.
{
  const int nb_lignes = mat.nb_lignes( );
  const IntVect& tab1 = mat.get_tab1( );
  const IntVect& tab2 = mat.get_tab2( );
  int nnz_tot = 0;
  for( int i=0; i<nb_lignes; i++ )
    {
      const int nnz_i = tab1[ i+1 ] - tab1[ i ]; //!< nnz sur la ligne i
      for(int k=0; k<nnz_i; k++)
        {
          const int j = tab2[nnz_tot + k] - 1 ; //!< indice de la colonne
          double& coefficient = mat.coef( i, j );
          if( inverse )
            coefficient *= 1./diag[ i ] ;
          else
            coefficient *= diag[ i ] ;
        }
      nnz_tot += nnz_i;
    }
}
References Matrice_Morse::coef(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), inverse(), and Matrice_Morse::nb_lignes().
matmorse_mult_matdiag()
void Matrix_tools::matmorse_mult_matdiag (const DoubleTab & diag, Matrice_Morse & mat, const bool & inverse) static
< nnz sur la ligne i
< indice de la colonne
Definition at line 596 of file Matrix_tools.cpp.
{
  const int nb_lignes = mat.nb_lignes( );
  const IntVect& tab1 = mat.get_tab1( );
  const IntVect& tab2 = mat.get_tab2( );
  int nnz_tot = 0;
  for( int i=0; i<nb_lignes; i++ )
    {
      const int nnz_i = tab1[ i+1 ] - tab1[ i ]; //!< nnz sur la ligne i
      for(int k=0; k<nnz_i; k++)
        {
          const int j = tab2[nnz_tot + k] - 1 ; //!< indice de la colonne
          double& coefficient = mat.coef( i, j );
          if( inverse )
            coefficient *= 1./diag[ j ] ;
          else
            coefficient *= diag[ j ] ;
        }
      nnz_tot += nnz_i;
    }
}
References Matrice_Morse::coef(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), inverse(), and Matrice_Morse::nb_lignes().
matmorse_mult_uniform_matdiag()
void Matrix_tools::matmorse_mult_uniform_matdiag (const double diag, Matrice_Morse & mat, const bool & inverse) static
Definition at line 645 of file Matrix_tools.cpp.
{
  uniform_matdiag_mult_matmorse( diag, mat, inverse );
}
References inverse(), and uniform_matdiag_mult_matmorse().
uniform_matdiag_mult_matmorse()
void Matrix_tools::uniform_matdiag_mult_matmorse (const double diag, Matrice_Morse & mat, const bool & inverse) static
< nnz sur la ligne i
< indice de la colonne
Definition at line 621 of file Matrix_tools.cpp.
{
  const int nb_lignes = mat.nb_lignes( );
  const IntVect& tab1 = mat.get_tab1( );
  const IntVect& tab2 = mat.get_tab2( );
  int nnz_tot = 0;
  for( int i=0; i<nb_lignes; i++ )
    {
      const int nnz_i = tab1[ i+1 ] - tab1[ i ]; //!< nnz sur la ligne i
      for(int k=0; k<nnz_i; k++)
        {
          const int j = tab2[nnz_tot + k] - 1 ; //!< indice de la colonne
          double& coefficient = mat.coef( i, j );
          if( inverse )
            coefficient *= 1./diag ;
          else
            coefficient *= diag ;
        }
      nnz_tot += nnz_i;
    }
}
References Matrice_Morse::coef(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), inverse(), and Matrice_Morse::nb_lignes().
Referenced by matmorse_mult_uniform_matdiag().
The documentation for this class was generated from the following files:
src/Kernel/Math/Matrices/Matrix_tools.h
src/Kernel/Math/Matrices/Matrix_tools.cpp