TRUST: BilanQdmVEF Class Reference
BilanQdmVEF Class Reference
#include <BilanQdmVEF.h>
Static Public Member Functions
static void bilan_qdm (const DoubleTab &dudt, const Zone_Cl_VEF &zone_Cl_VEF, ArrOfDouble &bilan)
static void bilan_energie (const DoubleTab &dudt, const DoubleTab &u, const Zone_Cl_VEF &zone_Cl_VEF, ArrOfDouble &bilan)
Detailed Description
Definition at line 21 of file BilanQdmVEF.h.
Member Function Documentation
bilan_energie()
void BilanQdmVEF::bilan_energie (const DoubleTab & dudt, const DoubleTab & u, const Zone_Cl_VEF & zone_Cl_VEF, ArrOfDouble & bilan) static
Definition at line 108 of file BilanQdmVEF.cpp.
{
  int nb_bord=zone_Cl_VEF.nb_cond_lim();
  int face;
  int nb_comp=bilan.size_array();
  for (int n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = le_bord.num_premiere_face();
      int nb_faces=le_bord.nb_faces();
      int num2 = num1 + nb_faces;
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int face_associee;
          IntVect fait(nb_faces);
          fait = 0;
          for (face=num1; face<num2; face++)
            {
              if (fait(face-num1) == 0)
                {
                  fait(face-num1) = 1;
                  face_associee=la_cl_perio.face_associee(face-num1);
                  fait(face_associee) = 1;
                  for (int comp=0; comp<nb_comp; comp++)
                    {
                      if(nb_comp==1)
                        bilan[comp]+=dudt(face)*u(face);
                      else
                        bilan[comp]+=dudt(face,comp)*u(face,comp);
                    }
                }//!< if fait
            }//!< for face
        }//!< sub_type Perio
      else if ( (sub_type(Dirichlet,la_cl.valeur())) ||
                (sub_type(Dirichlet_homogene,la_cl.valeur())) )
        {
// for (face=num1; face<num2; face++)
// {
// if(nb_comp==1)
// {
// dudt(face)=0;
// }
// else
// for (int comp=0; comp<nb_comp; comp++)
// {
// dudt(face,comp)=0.;
// }
// }
        }
      else
        {
          for (face=num1; face<num2; face++)
            {
              for (int comp=0; comp<nb_comp; comp++)
                {
                  if(nb_comp==1)
                    bilan[comp]+=dudt(face)*u(face);
                  else
                    bilan[comp]+=dudt(face,comp)*u(face,comp);
                }
            }//!< for face
        }
    }//!< for nbord
  {
    const Zone_VEF& zone_VEF=ref_cast(Zone_VEF, zone_Cl_VEF.zone_dis().valeur());
    const int prems=zone_VEF.premiere_face_int();
    const int nb_faces=zone_VEF.nb_faces_tot();
    for(face=prems; face<nb_faces; face++)
      {
        for (int comp=0; comp<nb_comp; comp++)
          {
            if(nb_comp==1)
              bilan[comp]+=dudt(face)*u(face);
            else
              bilan[comp]+=dudt(face,comp)*u(face,comp);
          }
      }
  }
}
References Periodique::face_associee(), face_associee, Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Zone_VF::nb_faces_tot(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, TRUSTArray< _TYPE_ >::size_array(), sub_type, Deriv_Cond_lim_base::valeur(), Deriv_Zone_dis_base::valeur(), and Zone_Cl_dis_base::zone_dis().
Referenced by Terme_Source_Qdm_VEF_Face::ajouter().
bilan_qdm()
void BilanQdmVEF::bilan_qdm (const DoubleTab & dudt, const Zone_Cl_VEF & zone_Cl_VEF, ArrOfDouble & bilan) static
Definition at line 25 of file BilanQdmVEF.cpp.
{
  int nb_bord=zone_Cl_VEF.nb_cond_lim();
  int face;
  int nb_comp=bilan.size_array();
  for (int n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = le_bord.num_premiere_face();
      int nb_faces=le_bord.nb_faces();
      int num2 = num1 + nb_faces;
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int face_associee;
          IntVect fait(nb_faces);
          fait = 0;
          for (face=num1; face<num2; face++)
            {
              if (fait(face-num1) == 0)
                {
                  fait(face-num1) = 1;
                  face_associee=la_cl_perio.face_associee(face-num1);
                  fait(face_associee) = 1;
                  for (int comp=0; comp<nb_comp; comp++)
                    {
                      if(nb_comp==1)
                        bilan[comp]+=dudt(face);
                      else
                        bilan[comp]+=dudt(face,comp);
                    }
                }//!< if fait
            }//!< for face
        }//!< sub_type Perio
      else if ( (sub_type(Dirichlet,la_cl.valeur())) ||
                (sub_type(Dirichlet_homogene,la_cl.valeur())) )
        {
// for (face=num1; face<num2; face++)
// {
// if(nb_comp==1)
// {
// dudt(face)=0;
// }
// else
// for (int comp=0; comp<nb_comp; comp++)
// {
// dudt(face,comp)=0.;
// }
// }
        }
      else
        {
          for (face=num1; face<num2; face++)
            {
              for (int comp=0; comp<nb_comp; comp++)
                {
                  if(nb_comp==1)
                    bilan[comp]+=dudt(face);
                  else
                    bilan[comp]+=dudt(face,comp);
                }
            }//!< for face
        }
    }//!< for nbord
  {
    const Zone_VEF& zone_VEF=ref_cast(Zone_VEF, zone_Cl_VEF.zone_dis().valeur());
    const int prems=zone_VEF.premiere_face_int();
    const int nb_faces=zone_VEF.nb_faces_tot();
    for(face=prems; face<nb_faces; face++)
      {
        for (int comp=0; comp<nb_comp; comp++)
          {
            if(nb_comp==1)
              bilan[comp]+=dudt(face);
            else
              bilan[comp]+=dudt(face,comp);
          }
      }
  }
}
References Periodique::face_associee(), face_associee, Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Zone_VF::nb_faces_tot(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, TRUSTArray< _TYPE_ >::size_array(), sub_type, Deriv_Cond_lim_base::valeur(), Deriv_Zone_dis_base::valeur(), and Zone_Cl_dis_base::zone_dis().
Referenced by Terme_Source_Qdm_VEF_Face::ajouter().
The documentation for this class was generated from the following files:
src/VEF/Operateurs/BilanQdmVEF.h
src/VEF/Operateurs/BilanQdmVEF.cpp