TRUST: Ch_front_input Class Reference
Ch_front_input Class Reference
class Ch_front_input
Cette classe represente un champ accessible par setInputField
defini sur une frontiere avec une valeur par face.
#include <Ch_front_input.h>
Public Member Functions
Ch_front_input ()
~Ch_front_input ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual Champ_front_base & affecter_ (const Champ_front_base &)
virtual void getTemplate (TrioField &afield) const
virtual void setValue (const TrioField &afield)
virtual void setDoubleValue (const double &val)
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialise le temps courant et Gpoint.
void buildSommetsFaces () const
const because used in Ch_Front_input_ALE::getTemplate() which is const - actually updates the 2 members below due to ALE mesh movement:
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ch_front_input & self_cast (Objet_U &)
static const Ch_front_input & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le nom du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void set_nb_comp (int i)
calls fixer_nb_comp
virtual void set_name (const Nom &)
calls nommer
virtual const Nom & get_name () const
calls le_nom
Protected Attributes
DoubleTab sommets_
mutable because of buildSommetsFaces function used in ALE
IntTab faces_
mutable because of buildSommetsFaces function used in ALE
Detailed Description
class Ch_front_input
Cette classe represente un champ accessible par setInputField
defini sur une frontiere avec une valeur par face.
Definition at line 44 of file Ch_front_input.h.
Constructor & Destructor Documentation
Ch_front_input::Ch_front_input ()
Definition at line 32 of file Ch_front_input.cpp.
Ch_front_input::~Ch_front_input ()
Definition at line 32 of file Ch_front_input.cpp.
Member Function Documentation
virtual Champ_front_base& Ch_front_input::affecter_ (const Champ_front_base &) [inline, virtual]
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 50 of file Ch_front_input.h.
  {
    return *this;
  }
void Ch_front_input::buildSommetsFaces () const
const because used in Ch_Front_input_ALE::getTemplate() which is const - actually updates the 2 members below due to ALE mesh movement:
Definition at line 104 of file Ch_front_input.cpp.
References Objet_U::dimension, IntTab::dimension(), DoubleTab::dimension(), DoubleTab::dimension_tot(), Frontiere::faces(), faces_, Frontiere_dis_base::frontiere(), Champ_front_base::frontiere_dis(), Faces::les_sommets(), Champ_Input_Proto::mon_pb, DoubleTab::resize(), ArrOfDouble::set_smart_resize(), and sommets_.
Referenced by initialiser().
{
  const DoubleTab& sommets_org=(mon_pb->domaine().les_sommets());
  DoubleTab& sommets=sommets_;
  sommets.resize(sommets_org.dimension_tot(0),sommets_org.dimension(1));
  sommets.set_smart_resize(1);
  IntTab& faces=faces_;
  const IntTab& faces_org=(frontiere_dis().frontiere().faces().les_sommets());
  faces=faces_org;
  int ntot=0;
  ArrOfInt marqueur(sommets_org.dimension(0));
  marqueur=-1;
  for (int f=0; f<faces.dimension(0); f++)
    {
      for (int s=0; s<faces.dimension(1); s++)
        {
          int som=faces(f,s);
          if (som >= 0 && marqueur(som)==-1)
            {
              marqueur(som)=ntot;
              for (int dir=0; dir<dimension; dir++)
                {
                  sommets(ntot,dir)=sommets_org(som,dir);
                }
              ntot++;
            }
        }
    }
  sommets.resize(ntot,dimension);
// on refait les faces
  for (int f=0; f<faces.dimension(0); f++)
    for (int s=0; s<faces.dimension(1); s++)
      faces(f,s) = faces_org(f, s) >= 0 ? marqueur(faces_org(f,s)) : -1;
}
Objet_U * Ch_front_input::cree_instance () [static]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Ch_front_input_P1.
Definition at line 32 of file Ch_front_input.cpp.
int Ch_front_input::duplique () const [virtual]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Ch_front_input_P1.
Definition at line 32 of file Ch_front_input.cpp.
const Type_info * Ch_front_input::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Ch_front_input_P1.
Definition at line 32 of file Ch_front_input.cpp.
const Nom & Ch_front_input::get_name () const [protected, virtual]
calls le_nom
Definition at line 58 of file Ch_front_input.cpp.
References Field_base::le_nom().
{
  return le_nom();
}
void Ch_front_input::getTemplate (TrioField & afield) const [virtual]
Implements Champ_Input_Proto.
Reimplemented in Ch_front_input_P1.
Definition at line 67 of file Ch_front_input.cpp.
References affecte_double_avec_doubletab(), affecte_int_avec_inttab(), DoubleTab::dimension(), IntTab::dimension(), Frontiere::faces(), faces_, Frontiere_dis_base::frontiere(), Champ_front_base::frontiere_dis(), Field_base::le_nom(), Faces::les_sommets(), Champ_Input_Proto::mon_pb, Process::mp_max(), Field_base::nb_comp(), IntTab::nb_dim(), DoubleTab::nb_dim(), and sommets_.
{
  afield.clear();
  afield.setName(le_nom().getChar());
  afield._time1=mon_pb->presentTime();
  afield._time2=mon_pb->futureTime();
  afield._nb_field_components=nb_comp();
  int org=1;
  if (faces_.dimension(1)==4) org=0;
  org=0;
// en mettant org a o1 on revient a l'ancien codage
  const DoubleTab& sommets=org==1?mon_pb->domaine().les_sommets():sommets_;
  const IntTab& faces=org==1?frontiere_dis().frontiere().faces().les_sommets():faces_;
  assert(sommets.nb_dim()==2);
  assert(faces.nb_dim()==2);
  afield._space_dim=sommets.dimension(1);
  afield._mesh_dim=afield._space_dim-1;
  afield._nbnodes=sommets.dimension(0);
  afield._nodes_per_elem=::mp_max(faces.dimension(1));
  afield._nb_elems=faces.dimension(0);
// Includes all the nodes, even those not used in connectivity
// order is  x y z  x y z  x y z
  affecte_double_avec_doubletab(&afield._coords,sommets);
  affecte_int_avec_inttab(&afield._connectivity,faces);
}
const Type_info * Ch_front_input::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Ch_front_input_P1.
Definition at line 32 of file Ch_front_input.cpp.
int Ch_front_input::initialiser (double temps, const Champ_Inc_base & inco) [virtual]
Initialise le temps courant et Gpoint.
< pour dimensionner
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Ch_front_input_P1.
Definition at line 153 of file Ch_front_input.cpp.
References buildSommetsFaces(), and Ch_front_var_instationnaire_dep::initialiser().
Referenced by Ch_front_input_P1::initialiser().
{
  if (!Ch_front_var_instationnaire_dep::initialiser(temps,inco))
    return 0;
  /*
    if (nb_comp()==1)
    for (int i=0;i<les_valeurs->nb_cases();i++)
    les_valeurs[i].valeurs()=9.9e5;
  */
  buildSommetsFaces();
  return 1;
}
Sortie & Ch_front_input::printOn (Sortie & s) const [protected, virtual]
Imprime le nom du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Ch_front_input_P1.
Definition at line 43 of file Ch_front_input.cpp.
{
  return os;
}
Entree & Ch_front_input::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Ch_front_input_P1.
Definition at line 35 of file Ch_front_input.cpp.
References Champ_Input_Proto::mon_pb, Champ_Input_Proto::read(), and Champ_Input_Proto::sous_zone_ok.
{
  sous_zone_ok=false;
  read(is);
  mon_pb->addInputField(*this);
  return is;
}
const Ch_front_input & Ch_front_input::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Ch_front_input_P1.
Definition at line 32 of file Ch_front_input.cpp.
Ch_front_input & Ch_front_input::self_cast (Objet_U & r) [static]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Ch_front_input_P1.
Definition at line 32 of file Ch_front_input.cpp.
void Ch_front_input::set_name (const Nom & name) [protected, virtual]
calls nommer
Implements Champ_Input_Proto.
Definition at line 53 of file Ch_front_input.cpp.
References Field_base::nommer().
{
  nommer(name);
}
void Ch_front_input::set_nb_comp (int i) [protected, virtual]
calls fixer_nb_comp
Implements Champ_Input_Proto.
Definition at line 48 of file Ch_front_input.cpp.
References Field_base::fixer_nb_comp().
{
  fixer_nb_comp(i);
}
void Ch_front_input::setDoubleValue (const double & val) [virtual]
Reimplemented from Champ_Input_Proto.
Definition at line 170 of file Ch_front_input.cpp.
References Champ_front_base::les_valeurs, and Champ_front_base::valeurs().
{
  assert(les_valeurs[0].valeurs().size() == 1);
  for (int i=1; i<les_valeurs->nb_cases(); i++)
    les_valeurs[i].valeurs()(0,0) = val;
}
void Ch_front_input::setValue (const TrioField & afield) [virtual]
Implements Champ_Input_Proto.
Reimplemented in Ch_front_input_P1.
Definition at line 146 of file Ch_front_input.cpp.
References Champ_front_var_instationnaire::Gpoint(), Champ_front_base::les_valeurs, Champ_Input_Proto::setValueOnTab(), and Champ_front_base::valeurs().
{
  for (int i=1; i<les_valeurs->nb_cases(); i++)
    Champ_Input_Proto::setValueOnTab(afield,les_valeurs[i].valeurs());
  Gpoint(afield._time1,afield._time2);
}
unsigned Ch_front_input::taille_memoire () const [virtual]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Ch_front_input_P1.
Definition at line 32 of file Ch_front_input.cpp.
Member Data Documentation
IntTab Ch_front_input::faces_ [mutable, protected]
mutable because of buildSommetsFaces function used in ALE
Definition at line 68 of file Ch_front_input.h.
Referenced by buildSommetsFaces(), Ch_front_input_P1::getTemplate(), and getTemplate().
const Type_info Ch_front_input::info_obj [static]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Ch_front_input_P1.
Definition at line 46 of file Ch_front_input.h.
DoubleTab Ch_front_input::sommets_ [mutable, protected]
mutable because of buildSommetsFaces function used in ALE
Definition at line 67 of file Ch_front_input.h.
Referenced by buildSommetsFaces(), Ch_front_input_P1::getTemplate(), getTemplate(), Ch_front_input_P1::initialiser(), and Ch_front_input_P1::valeur_au_temps_et_au_point().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Ch_front_input.h
src/Kernel/Champs/Ch_front_input.cpp