TRUST: IntLists Class Reference
IntLists Class Reference
Un tableau de listes de type IntList.
#include <IntLists.h>
Public Member Functions
IntLists ()
Construit un tableau vide de listes.
Sortie & printOn (Sortie &os) const
Ecriture sur un flot de sortie
Ecrit successivement toutes les listes du tableau.
Entree & readOn (Entree &is)
Lecture dans un flot d'entree
ne fait rien.
int size () const
retourne le nombre de listes dans le tableau
IntLists (int)
Construit un tableau de i listes.
const IntList & operator[] (int) const
Acces a la ieme liste du tableau.
IntList & operator[] (int)
Acces a la ieme liste du tableau.
IntLists (const IntLists &)
Constructeur par copie.
virtual ~IntLists ()
Destructeur.
IntLists & operator= (const IntLists &)
Copie et affectation.
Les anciennes donnees sont perdues.
int search (const IntList &) const
Recherche d'une liste dans le tableau.
void dimensionner (int)
Redimensionne un tableau de listes.
Protected Attributes
int sz
IntList * data
Detailed Description
Un tableau de listes de type IntList.
Definition at line 34 of file IntLists.h.
Constructor & Destructor Documentation
IntLists::IntLists ()
Construit un tableau vide de listes.
Definition at line 111 of file IntLists.cpp.
: sz(0), data(0) {}
IntLists::IntLists (int i)
Construit un tableau de i listes.
Definition at line 127 of file IntLists.cpp.
References Cerr, data, Process::exit(), and finl.
                       : sz(i)
{
  if(i==0) data=0;
  else
    {
      data= new IntList[i];
      if(!data)
        {
          Cerr << "Unable to carry out allocation " << finl;
          Process::exit();
        }
    }
}
IntLists::IntLists (const IntLists & vect)
Constructeur par copie.
Definition at line 83 of file IntLists.cpp.
References Cerr, data, Process::exit(), finl, and sz.
  : sz(vect.sz), data(new IntList[vect.sz])
{
  if(!data)
    {
      Cerr << "Unable to carry out allocation " << finl;
      Process::exit();
    }
  int i=sz;
  if(i==0) data=0;
  else while(i--)
      data[i]=vect[i];
}
IntLists::~IntLists () [virtual]
Destructeur.
Definition at line 155 of file IntLists.cpp.
References data, and sz.
{
  if(sz)
    {
      assert(data);
      delete[] data;
    }
  else
    assert (data==0) ;
}
Member Function Documentation
void IntLists::dimensionner (int i)
Redimensionne un tableau de listes.
Definition at line 286 of file IntLists.cpp.
References Cerr, data, Process::exit(), finl, and sz.
Referenced by Op_Curl_VEFP1B::elements_pour_sommet(), and Op_Diff_VEFP1NCP1B_Face::liste_face().
{
  assert(sz==0);
  assert(data==0);
  sz =i;
  if(i==0)
    data=0;
  else
    {
      data = new IntList[i];
      if(!data)
        {
          Cerr << "Unable to carry out allocation " << finl;
          Process::exit();
        }
    }
}
IntLists & IntLists::operator= (const IntLists & vect)
Copie et affectation.
Les anciennes donnees sont perdues.
Returns:
IntLists&
Signification: *this
Contraintes:
Definition at line 181 of file IntLists.cpp.
References Cerr, data, Process::exit(), finl, and sz.
{
  sz=vect.sz;
  if(data)
    delete[] data;
  if(sz)
    {
      data = new IntList[sz];
      if(!data)
        {
          Cerr << "Unable to carry out allocation " << finl;
          Process::exit();
        }
      int i=sz;
      while(i--)
        data[i]=vect[i];
    }
  else data=0;
  return *this;
}
IntList & IntLists::operator[] (int i)
Acces a la ieme liste du tableau.
Returns:
IntList&
Signification: la ieme liste du tableau
Contraintes:
Definition at line 265 of file IntLists.cpp.
References data, and sz.
{
  assert( (i>=0) && (i<sz) );
  return data[i];
}
const IntList & IntLists::operator[] (int i) const
Acces a la ieme liste du tableau.
Returns:
const IntList&
Signification: la ieme liste du tableau
Contraintes:
Definition at line 244 of file IntLists.cpp.
References data, and sz.
{
  assert( (i>=0) && (i<sz) );
  return data[i];
}
Sortie & IntLists::printOn (Sortie & s) const
Ecriture sur un flot de sortie
Ecrit successivement toutes les listes du tableau.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Definition at line 41 of file IntLists.cpp.
References data, finl, IntList::printOn(), and sz.
Referenced by IntListsListe::printOn().
{
  int i=sz;
  while(i--)
    data[i].printOn(s);
  return s<<finl;
}
Entree & IntLists::readOn (Entree & s)
Lecture dans un flot d'entree
ne fait rien.
Returns:
Entree&
Signification: flot d'entree inchange
Contraintes:
Definition at line 64 of file IntLists.cpp.
{
  return s;
}
int IntLists::search (const IntList & t) const
Recherche d'une liste dans le tableau.
Returns:
int
Signification: indice de la liste ou -1 si elle est introuvable
Contraintes:
Definition at line 216 of file IntLists.cpp.
References data, and sz.
{
  int i=sz;
  int retour=-1;
  while(i--)
    if( data[i] == t )
      {
        retour=i;
        i=0;
      }
  return retour;
}
int IntLists::size () const [inline]
retourne le nombre de listes dans le tableau
Returns:
int
Signification: nombre de listes dans le tableau
Contraintes:
Definition at line 69 of file IntLists.h.
References sz.
Referenced by Partitionneur_base::corriger_multiperiodique(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Op_Curl_VEFP1B::elem_som_size(), VerifierCoin::interpreter_(), and Op_Diff_VEFP1NCP1B_Face::liste_face().
{
  return sz;
}
Member Data Documentation
IntList* IntLists::data [protected]
Definition at line 51 of file IntLists.h.
Referenced by dimensionner(), IntLists(), operator=(), operator[](), printOn(), search(), and ~IntLists().
int IntLists::sz [protected]
Definition at line 50 of file IntLists.h.
Referenced by dimensionner(), IntLists(), operator=(), operator[](), printOn(), search(), size(), and ~IntLists().
The documentation for this class was generated from the following files:
src/Kernel/Math/IntLists.h
src/Kernel/Math/IntLists.cpp