TRUST: Multiplicateur_diphasique_homogene Class Reference
Multiplicateur_diphasique_homogene Class Reference
classe Multiplicateur_diphasique_homogene
multiplicateur diphasique homogene : Phi^2 = 1 + x (rho_l / rho_g - 1)
raccord vers la phase vapeur a partir de alpha_min et jusqu'a alpha_max
#include <Multiplicateur_diphasique_homogene.h>
Public Member Functions
Multiplicateur_diphasique_homogene ()
~Multiplicateur_diphasique_homogene ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void coefficient (const double *alpha, const double *rho, const double *v, const double *f, const double *mu, const double Dh, const double gamma, const double *Fk, const double Fm, DoubleTab &coeff) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Multiplicateur_diphasique_homogene & self_cast (Objet_U &)
static const
Multiplicateur_diphasique_homogene & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
double alpha_min_ = 0.9995
double alpha_max_ = 1
int n_l = -1
int n_g = -1
Detailed Description
classe Multiplicateur_diphasique_homogene
multiplicateur diphasique homogene : Phi^2 = 1 + x (rho_l / rho_g - 1)
raccord vers la phase vapeur a partir de alpha_min et jusqu'a alpha_max
Definition at line 35 of file Multiplicateur_diphasique_homogene.h.
Constructor & Destructor Documentation
Multiplicateur_diphasique_homogene::Multiplicateur_diphasique_homogene ()
Definition at line 26 of file Multiplicateur_diphasique_homogene.cpp.
Multiplicateur_diphasique_homogene::~Multiplicateur_diphasique_homogene ()
Definition at line 26 of file Multiplicateur_diphasique_homogene.cpp.
Member Function Documentation
void Multiplicateur_diphasique_homogene::coefficient (const double * alpha, const double * rho, const double * v, const double * f, const double * mu, const double Dh, const double gamma, const double * Fk, const double Fm, DoubleTab & coeff) const [virtual]
Implements Multiplicateur_diphasique_base.
Definition at line 52 of file Multiplicateur_diphasique_homogene.cpp.
References alpha_max_, alpha_min_, coeff, dabs(), max(), min(), n_g, and n_l.
{
  double G = alpha[n_l] * rho[n_l] * dabs(v[n_l]) + alpha[n_g] * rho[n_g] * dabs(v[n_g]), //debit total
         x = G ? alpha[n_g] * rho[n_g] * v[n_g] / G : 0, //titre
         Phi2 = 1 + x * (rho[n_l] / rho[n_g] - 1), //le multiplicateur!
         frac_g = min(max((alpha[n_g] - alpha_min_) / (alpha_max_ - alpha_min_), 0.), 1.), frac_l = 1 - frac_g; //fraction appliquee a la vapeur
  coeff = 0;
  coeff(n_l, 0) = frac_l * Phi2;
  coeff(n_g, 0) = frac_g ? frac_g / (alpha[n_g] * alpha[n_g]) : 0; //basculement vers le frottement "vapeur seule"
}
Objet_U * Multiplicateur_diphasique_homogene::cree_instance () [static]
Definition at line 26 of file Multiplicateur_diphasique_homogene.cpp.
int Multiplicateur_diphasique_homogene::duplique () const [virtual]
Implements Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_homogene.cpp.
const Type_info * Multiplicateur_diphasique_homogene::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_homogene.cpp.
const Type_info * Multiplicateur_diphasique_homogene::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_homogene.cpp.
Sortie & Multiplicateur_diphasique_homogene::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 28 of file Multiplicateur_diphasique_homogene.cpp.
{
  return os;
}
Entree & Multiplicateur_diphasique_homogene::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 33 of file Multiplicateur_diphasique_homogene.cpp.
References Param::ajouter(), alpha_max_, alpha_min_, Nom::debute_par(), Process::exit(), Nom::finit_par(), Param::lire_avec_accolades_depuis(), n_g, n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), ref_cast, sub_type, and Ref_Probleme_base::valeur().
{
  Param param(que_suis_je());
  param.ajouter("alpha_min", &alpha_min_);
  param.ajouter("alpha_max", &alpha_max_);
  param.lire_avec_accolades_depuis(is);
  const Pb_Multiphase *pbm = sub_type(Pb_Multiphase, pb_.valeur()) ? &ref_cast(Pb_Multiphase, pb_.valeur()) : NULL;
  if (!pbm || pbm->nb_phases() == 1) n_l = 0, n_g = -1; //pas un Pb_Multiphase -> monophasique liquide
  else for (int n = 0; n < pbm->nb_phases(); n++) //recherche de n_l, n_g : phase {liquide,gaz}_continu en priorite
      if (pbm->nom_phase(n).debute_par("liquide") && (n_l < 0 || pbm->nom_phase(n).finit_par("continu")))  n_l = n;
      else if (pbm->nom_phase(n).debute_par("gaz") && (n_g < 0 || pbm->nom_phase(n).finit_par("continu"))) n_g = n;
  if (n_l < 0) Process::exit(que_suis_je() + " : main phase not found!");
  return is;
}
const Multiplicateur_diphasique_homogene & Multiplicateur_diphasique_homogene::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_homogene.cpp.
Multiplicateur_diphasique_homogene & Multiplicateur_diphasique_homogene::self_cast (Objet_U & r) [static]
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_homogene.cpp.
unsigned Multiplicateur_diphasique_homogene::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Multiplicateur_diphasique_homogene.cpp.
Member Data Documentation
double Multiplicateur_diphasique_homogene::alpha_max_ = 1 [protected]
Definition at line 43 of file Multiplicateur_diphasique_homogene.h.
Referenced by coefficient(), and readOn().
double Multiplicateur_diphasique_homogene::alpha_min_ = 0.9995 [protected]
Definition at line 43 of file Multiplicateur_diphasique_homogene.h.
Referenced by coefficient(), and readOn().
const Type_info Multiplicateur_diphasique_homogene::info_obj [static]
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 37 of file Multiplicateur_diphasique_homogene.h.
int Multiplicateur_diphasique_homogene::n_g = -1 [protected]
Definition at line 44 of file Multiplicateur_diphasique_homogene.h.
Referenced by coefficient(), and readOn().
int Multiplicateur_diphasique_homogene::n_l = -1 [protected]
Definition at line 44 of file Multiplicateur_diphasique_homogene.h.
Referenced by coefficient(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Correlations/Multiplicateur_diphasique_homogene.h
src/ThHyd/Multiphase/Correlations/Multiplicateur_diphasique_homogene.cpp