TRUST: Source_Forchheimer_VEF_Face Class Reference
Source_Forchheimer_VEF_Face Class Reference
#include <Source_Forchheimer_VEF_Face.h>
Public Member Functions
~Source_Forchheimer_VEF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Source_Forchheimer_VEF_Face ()
void associer_pb (const Probleme_base &)
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Eval_Forchheimer_VEF_Face & eval ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Source_Forchheimer_VEF_Face & self_cast (Objet_U &)
static const
Source_Forchheimer_VEF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Detailed Description
Definition at line 53 of file Source_Forchheimer_VEF_Face.h.
Constructor & Destructor Documentation
Source_Forchheimer_VEF_Face::~Source_Forchheimer_VEF_Face ()
Definition at line 28 of file Source_Forchheimer_VEF_Face.cpp.
Source_Forchheimer_VEF_Face::Source_Forchheimer_VEF_Face () [inline]
Definition at line 76 of file Source_Forchheimer_VEF_Face.h.
                                                                :
  Terme_Source_VEF_base(It_Sou_VEF_Face(Eval_Forchheimer_VEF_Face)())
{
}
Member Function Documentation
void Source_Forchheimer_VEF_Face::associer_pb (const Probleme_base & pb) [virtual]
Implements Source_base.
Definition at line 110 of file Source_Forchheimer_VEF_Face.cpp.
References Eval_Forchheimer_VEF_Face::associer(), Probleme_base::equation(), eval(), and Equation_base::inconnue().
{
  const Champ_Inc& vit = pb.equation(0).inconnue();
  eval().associer(vit);
}
void Source_Forchheimer_VEF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis) [virtual]
Implements Source_base.
Definition at line 101 of file Source_Forchheimer_VEF_Face.cpp.
References Evaluateur_Source_VEF::associer_zones(), eval(), Terme_Source_VEF_base::iter, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  const Zone_VEF& zvdf = ref_cast(Zone_VEF,zone_dis.valeur());
  const Zone_Cl_VEF& zclvdf = ref_cast(Zone_Cl_VEF,zone_cl_dis.valeur());
  iter->associer_zones(zvdf, zclvdf);
  eval().associer_zones(zvdf, zclvdf );
}
Objet_U * Source_Forchheimer_VEF_Face::cree_instance () [static]
Reimplemented in Forchheimer_QC_VEF_P1NC.
Definition at line 28 of file Source_Forchheimer_VEF_Face.cpp.
int Source_Forchheimer_VEF_Face::duplique () const [virtual]
Implements Terme_Source_VEF_base.
Reimplemented in Forchheimer_QC_VEF_P1NC.
Definition at line 28 of file Source_Forchheimer_VEF_Face.cpp.
Eval_Forchheimer_VEF_Face& Source_Forchheimer_VEF_Face::eval () [inline]
Definition at line 66 of file Source_Forchheimer_VEF_Face.h.
Referenced by associer_pb(), associer_zones(), and readOn().
  {
    return (Eval_Forchheimer_VEF_Face&) iter.evaluateur();
  }
const Type_info * Source_Forchheimer_VEF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_VEF_base.
Reimplemented in Forchheimer_QC_VEF_P1NC.
Definition at line 28 of file Source_Forchheimer_VEF_Face.cpp.
const Type_info * Source_Forchheimer_VEF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_VEF_base.
Reimplemented in Forchheimer_QC_VEF_P1NC.
Definition at line 28 of file Source_Forchheimer_VEF_Face.cpp.
void Source_Forchheimer_VEF_Face::mettre_a_jour (double temps) [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 62 of file Source_Forchheimer_VEF_Face.h.
  {
    ;
  }
Sortie & Source_Forchheimer_VEF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Source_VEF_base.
Reimplemented in Forchheimer_QC_VEF_P1NC.
Definition at line 35 of file Source_Forchheimer_VEF_Face.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Source_Forchheimer_VEF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Terme_Source_VEF_base.
Reimplemented in Forchheimer_QC_VEF_P1NC.
Definition at line 43 of file Source_Forchheimer_VEF_Face.cpp.
References Cerr, eval(), Process::exit(), finl, Eval_Forchheimer_VEF_Face::modK, Objet_U::que_suis_je(), Motcles::search(), Source_base::set_description(), Source_base::set_fichier(), Eval_Forchheimer_VEF_Face::setCf(), Eval_Forchheimer_VEF_Face::setPorosite(), Deriv_::typer(), and Deriv_Modele_Permeabilite_base::valeur().
{
  Motcles les_mots(3);
  {
    les_mots[0] = "modele_K";
    les_mots[1] = "Cf";
    les_mots[2] = "porosite";
  }
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
  is >> motlu;
  if(motlu!=accolade_ouverte)
    {
      Cerr << "On attendait une { a la lecture d'une " << que_suis_je() << finl;
      Cerr << "et non : " << motlu << finl;
      exit();
    }
  is >> motlu;
  while (motlu != accolade_fermee)
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          {
            Motcle mot;
            is >> mot;
            eval().modK.typer(mot);
            is >> eval().modK.valeur();
            break;
          }
        case 1 :
          {
            double c;
            is >> c;
            eval().setCf(c);
            break;
          }
        case 2 :
          {
            double c;
            is >> c;
            eval().setPorosite(c);
            break;
          }
        default :
          {
            Cerr << "Unknown keyword in Source_Forchheimer_VEF_Face " << finl;
            exit();
          }
        }
      is >> motlu;
    }
  set_fichier("Forcheimer");
  set_description("Forchheimer term = Integral(-Cf/K*abs(vitesse)*vitesse*dv) [m/s2]");
  return is;
}
Source_Forchheimer_VEF_Face & Source_Forchheimer_VEF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Terme_Source_VEF_base.
Reimplemented in Forchheimer_QC_VEF_P1NC.
Definition at line 28 of file Source_Forchheimer_VEF_Face.cpp.
const Source_Forchheimer_VEF_Face & Source_Forchheimer_VEF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Terme_Source_VEF_base.
Reimplemented in Forchheimer_QC_VEF_P1NC.
Definition at line 28 of file Source_Forchheimer_VEF_Face.cpp.
unsigned Source_Forchheimer_VEF_Face::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Forchheimer_QC_VEF_P1NC.
Definition at line 28 of file Source_Forchheimer_VEF_Face.cpp.
Member Data Documentation
const Type_info Source_Forchheimer_VEF_Face::info_obj [static]
Reimplemented from Terme_Source_VEF_base.
Reimplemented in Forchheimer_QC_VEF_P1NC.
Definition at line 55 of file Source_Forchheimer_VEF_Face.h.
The documentation for this class was generated from the following files:
src/VEF/Sources/Source_Forchheimer_VEF_Face.h
src/VEF/Sources/Source_Forchheimer_VEF_Face.cpp