TRUST: EcrMED Class Reference
EcrMED Class Reference
Classe EcrMED
Ecr un fichier MED
Structure du jeu de donnee (en dimension 2) :
EcrMED dom medfile.
#include <EcrMED.h>
Public Member Functions
~EcrMED ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
EcrMED ()
void setMajorMode (bool majorMod)
bool getMajorMode ()
void setMEDCoupling (bool mc)
Nom version ()
Entree & interpreter (Entree &) override
void ecrire_domaine (const Nom &nom_fic, const Domaine &dom, const Nom &nom_dom, int mode=0)
void ecrire_domaine_dis (const Nom &nom_fic, const Domaine &dom, const Ref_Zone_dis_base &zone_dis_base, const Nom &nom_dom, int mode=0)
void ecrire_champ (const Nom &type, const Nom &nom_fic, const Domaine &dom, const Nom &nom_cha1, const DoubleTab &val, const Noms &unite, const Noms &noms_compo, const Nom &type_elem, double time, int compteur)
void ecrire_champ (const Nom &type, const Nom &nom_fic, const Domaine &dom, const Nom &nom_cha1, const DoubleTab &val, const Noms &unite, const Nom &type_elem, double time, int compteur, const Champ_Inc_base &le_champ)
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static EcrMED & self_cast (Objet_U &)
static const EcrMED & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
bool use_medcoupling_
Private Attributes
bool major_mode
std::map< std::string, int > timestep_
Detailed Description
Classe EcrMED
Ecr un fichier MED
Structure du jeu de donnee (en dimension 2) :
EcrMED dom medfile.
Definition at line 36 of file EcrMED.h.
Constructor & Destructor Documentation
~EcrMED()
EcrMED::~EcrMED ()
Definition at line 48 of file EcrMED.cpp.
EcrMED()
EcrMED::EcrMED ()
Definition at line 50 of file EcrMED.cpp.
               : major_mode(false)
{
#ifdef MEDCOUPLING_
  use_medcoupling_ = true;
#else
  use_medcoupling_ = false;
#endif
}
References use_medcoupling_.
Member Function Documentation
cree_instance()
Objet_U * EcrMED::cree_instance () static
Definition at line 48 of file EcrMED.cpp.
duplique()
int EcrMED::duplique () const override virtual
Implements Objet_U.
Reimplemented in EcrMEDfile.
Definition at line 48 of file EcrMED.cpp.
ecrire_champ() [1/2]
void EcrMED::ecrire_champ (const Nom & type, const Nom & nom_fic, const Domaine & dom, const Nom & nom_cha1, const DoubleTab & val, const Noms & unite, const Nom & type_elem, double time, int compteur, const Champ_Inc_base & le_champ)
ecrire_champ() [2/2]
void EcrMED::ecrire_champ (const Nom & type, const Nom & nom_fic, const Domaine & dom, const Nom & nom_cha1, const DoubleTab & val, const Noms & unite, const Noms & noms_compo, const Nom & type_elem, double time, int compteur)
Definition at line 126 of file EcrMED.cpp.
{
  med_non_installe();
}
References med_non_installe().
Referenced by Format_Post_Med::ecrire_champ_med().
ecrire_domaine()
void EcrMED::ecrire_domaine (const Nom & nom_fic, const Domaine & dom, const Nom & nom_dom, int mode = 0)
Definition at line 130 of file EcrMED.cpp.
{
  med_non_installe();
}
References med_non_installe().
Referenced by interpreter().
ecrire_domaine_dis()
void EcrMED::ecrire_domaine_dis (const Nom & nom_fic, const Domaine & dom, const Ref_Zone_dis_base & zone_dis_base, const Nom & nom_dom, int mode = 0)
Referenced by Format_Post_Med::ecrire_domaine_med().
get_info()
const Type_info * EcrMED::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in EcrMEDfile.
Definition at line 48 of file EcrMED.cpp.
getMajorMode()
bool EcrMED::getMajorMode () inline
Definition at line 46 of file EcrMED.h.
  {
    return major_mode;
  }
References major_mode.
Referenced by Format_Post_Med::ecrire_domaine_med().
info()
const Type_info * EcrMED::info () static
Definition at line 48 of file EcrMED.cpp.
interpreter()
Entree & EcrMED::interpreter (Entree & is) override virtual
Reimplemented from Interprete.
Definition at line 100 of file EcrMED.cpp.
{
  Cerr<<"syntax : EcrMED [ append ] nom_dom nom_fic "<<finl;
  int mode=-1;
  Nom nom_dom, nom_fic;
  is >> nom_dom ;
  Motcle app("append");
  if (app==nom_dom)
    {
      mode=0;
      is >> nom_dom;
      Cerr<<" Adding "<<nom_dom<<finl;
    }
  is >> nom_fic;
  if(! sub_type(Domaine, objet(nom_dom)))
    {
      Cerr << nom_dom << " type is " << objet(nom_dom).que_suis_je() << finl;
      Cerr << "Only Domaine type objects can be meshed" << finl;
      exit();
    }
  const Domaine& dom=ref_cast(Domaine, objet(nom_dom));
  ecrire_domaine(nom_fic,dom,nom_dom,mode);
  return is;
}
References Cerr, ecrire_domaine(), Process::exit(), finl, Interprete::objet(), Objet_U::que_suis_je(), ref_cast, and sub_type.
printOn()
Sortie & EcrMED::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in EcrMEDfile.
Definition at line 73 of file EcrMED.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
Referenced by EcrMEDfile::printOn().
readOn()
Entree & EcrMED::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in EcrMEDfile.
Definition at line 93 of file EcrMED.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
Referenced by EcrMEDfile::readOn().
self_cast() [1/2]
const EcrMED & EcrMED::self_cast (const Objet_U & r) static
Definition at line 48 of file EcrMED.cpp.
self_cast() [2/2]
EcrMED & EcrMED::self_cast (Objet_U & r) static
Definition at line 48 of file EcrMED.cpp.
setMajorMode()
void EcrMED::setMajorMode (bool majorMod) inline
Definition at line 42 of file EcrMED.h.
  {
    major_mode = majorMod;
  };
References major_mode.
Referenced by Format_Post_Med_major::Format_Post_Med_major(), and Format_Post_Med::reset().
setMEDCoupling()
void EcrMED::setMEDCoupling (bool mc) inline
Definition at line 51 of file EcrMED.h.
  {
    use_medcoupling_ = mc;
  }
References use_medcoupling_.
Referenced by Format_Post_Med_major::Format_Post_Med_major(), and Format_Post_Medfile::Format_Post_Medfile().
taille_memoire()
unsigned EcrMED::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in EcrMEDfile.
Definition at line 48 of file EcrMED.cpp.
version()
Nom EcrMED::version () inline
Definition at line 55 of file EcrMED.h.
  {
    return major_mode ? _MED_VERSION(MED_NUM_MAJEUR,0,0) : MED_VERSION_STR;
  }
References major_mode.
Referenced by Format_Post_Med::ecrire_domaine_med().
Member Data Documentation
info_obj
const Type_info EcrMED::info_obj static
Definition at line 38 of file EcrMED.h.
major_mode
bool EcrMED::major_mode private
Definition at line 70 of file EcrMED.h.
Referenced by getMajorMode(), setMajorMode(), and version().
timestep_
std::map<std::string, int> EcrMED::timestep_ private
Definition at line 71 of file EcrMED.h.
use_medcoupling_
bool EcrMED::use_medcoupling_ protected
Definition at line 66 of file EcrMED.h.
Referenced by EcrMED(), EcrMEDfile::EcrMEDfile(), and setMEDCoupling().
The documentation for this class was generated from the following files:
src/Kernel/MEDimpl/EcrMED.h
src/Kernel/MEDimpl/EcrMED.cpp