TRUST: Champ_val_tot_sur_vol_VDF Class Reference
Champ_val_tot_sur_vol_VDF Class Reference
classe Champ_val_tot_sur_vol_VDF derivee de Champ_val_tot_sur_vol_base
Evaluation de Somme_vol_poro_loc :
sommation de vol_element*poro_volumique pour les elements contenus dans la localisation loc
#include <Champ_val_tot_sur_vol_VDF.h>
Public Member Functions
Champ_val_tot_sur_vol_VDF ()
~Champ_val_tot_sur_vol_VDF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleVect & eval_contrib_loc (const Zone_dis_base &zdis, const Zone_Cl_dis_base &zcldis, DoubleVect &vol)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_val_tot_sur_vol_VDF & self_cast (Objet_U &)
static const
Champ_val_tot_sur_vol_VDF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime les valeurs du champs sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit les valeurs du champ uniforme par morceaux
a partir d'un flot d'entree.
On lit le nom du domaine (nom_domaine) le nombre de
composantes du champ (nb_comp) la valeur par defaut
du champ ainsi que les valeurs sur les sous zones.
Format:
Champ_Uniforme_Morceaux nom_domaine nb_comp
{ Defaut val_def sous_zone_1 val_1 ... sous_zone_i val_i }.
Detailed Description
classe Champ_val_tot_sur_vol_VDF derivee de Champ_val_tot_sur_vol_base
Evaluation de Somme_vol_poro_loc :
sommation de vol_element*poro_volumique pour les elements contenus dans la localisation loc
Definition at line 36 of file Champ_val_tot_sur_vol_VDF.h.
Constructor & Destructor Documentation
Champ_val_tot_sur_vol_VDF::Champ_val_tot_sur_vol_VDF ()
Definition at line 27 of file Champ_val_tot_sur_vol_VDF.cpp.
Champ_val_tot_sur_vol_VDF::~Champ_val_tot_sur_vol_VDF ()
Definition at line 27 of file Champ_val_tot_sur_vol_VDF.cpp.
Member Function Documentation
Objet_U * Champ_val_tot_sur_vol_VDF::cree_instance () [static]
Reimplemented from Champ_Uniforme_Morceaux.
Definition at line 27 of file Champ_val_tot_sur_vol_VDF.cpp.
int Champ_val_tot_sur_vol_VDF::duplique () const [virtual]
Implements Champ_val_tot_sur_vol_base.
Definition at line 27 of file Champ_val_tot_sur_vol_VDF.cpp.
DoubleVect & Champ_val_tot_sur_vol_VDF::eval_contrib_loc (const Zone_dis_base & zdis, const Zone_Cl_dis_base & zcldis, DoubleVect & vol) [virtual]
Implements Champ_val_tot_sur_vol_base.
Definition at line 42 of file Champ_val_tot_sur_vol_VDF.cpp.
References Champ_Uniforme_Morceaux::les_sous_zones, LIST_CURSEUR, Process::mp_sum(), Zone_dis_base::nb_elem(), Sous_Zone::nb_elem_tot(), Zone_VF::porosite_elem(), REF, ref_cast, DoubleVect::resize(), liste::size(), sz, and Zone_VF::volumes().
{
  const Zone_VF& zvf = ref_cast(Zone_VF,zdis);
  const int nb_elem = zvf.nb_elem();
  int size_vol = les_sous_zones.size()+1;
  vol_glob_pond.resize(size_vol);
  const DoubleVect& vol = zvf.volumes();
  const DoubleVect& por_elem = zvf.porosite_elem();
  int cpt=1;
  LIST_CURSEUR(REF(Sous_Zone)) curseur1 = les_sous_zones;
  while(curseur1)
    {
      const Sous_Zone& sz = curseur1.valeur().valeur();
      int size_sz = sz.nb_elem_tot();
      int el;
      for (int elem=0; elem<size_sz; elem++)
        {
          el = sz(elem);
// On ne retient que les elements reels
          if (el<nb_elem)
            vol_glob_pond(cpt) += vol(el)*por_elem(el);
        }
      cpt++;
      ++curseur1;
    }
  for (int elem=0; elem<nb_elem; elem++)
    vol_glob_pond(0) += vol(elem)*por_elem(elem);
  vol_glob_pond(0) = mp_sum(vol_glob_pond(0));
  for (int i=1; i<size_vol; i++)
    {
      vol_glob_pond(i) = mp_sum(vol_glob_pond(i));
      vol_glob_pond(0) -= vol_glob_pond(i);
    }
  return vol_glob_pond;
}
const Type_info * Champ_val_tot_sur_vol_VDF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_val_tot_sur_vol_base.
Definition at line 27 of file Champ_val_tot_sur_vol_VDF.cpp.
const Type_info * Champ_val_tot_sur_vol_VDF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_val_tot_sur_vol_base.
Definition at line 27 of file Champ_val_tot_sur_vol_VDF.cpp.
Sortie & Champ_val_tot_sur_vol_VDF::printOn (Sortie & os) const [protected, virtual]
Imprime les valeurs du champs sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_val_tot_sur_vol_base.
Definition at line 30 of file Champ_val_tot_sur_vol_VDF.cpp.
{
  Champ_val_tot_sur_vol_base::printOn(os);
  return os;
}
Entree & Champ_val_tot_sur_vol_VDF::readOn (Entree & is) [protected, virtual]
Lit les valeurs du champ uniforme par morceaux
a partir d'un flot d'entree.
On lit le nom du domaine (nom_domaine) le nombre de
composantes du champ (nb_comp) la valeur par defaut
du champ ainsi que les valeurs sur les sous zones.
Format:
Champ_Uniforme_Morceaux nom_domaine nb_comp
{ Defaut val_def sous_zone_1 val_1 ... sous_zone_i val_i }.
Returns:
Entree&
Signification: le champ d'entree modifie
Contraintes:
Reimplemented from Champ_val_tot_sur_vol_base.
Definition at line 36 of file Champ_val_tot_sur_vol_VDF.cpp.
{
  Champ_val_tot_sur_vol_base::readOn(is);
  return is;
}
Champ_val_tot_sur_vol_VDF & Champ_val_tot_sur_vol_VDF::self_cast (Objet_U & r) [static]
Reimplemented from Champ_val_tot_sur_vol_base.
Definition at line 27 of file Champ_val_tot_sur_vol_VDF.cpp.
const Champ_val_tot_sur_vol_VDF & Champ_val_tot_sur_vol_VDF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_val_tot_sur_vol_base.
Definition at line 27 of file Champ_val_tot_sur_vol_VDF.cpp.
unsigned Champ_val_tot_sur_vol_VDF::taille_memoire () const [virtual]
Reimplemented from Champ_Uniforme_Morceaux.
Definition at line 27 of file Champ_val_tot_sur_vol_VDF.cpp.
Member Data Documentation
const Type_info Champ_val_tot_sur_vol_VDF::info_obj [static]
Reimplemented from Champ_val_tot_sur_vol_base.
Definition at line 39 of file Champ_val_tot_sur_vol_VDF.h.
The documentation for this class was generated from the following files:
src/VDF/Champs/Champ_val_tot_sur_vol_VDF.h
src/VDF/Champs/Champ_val_tot_sur_vol_VDF.cpp