TRUST: Loi_Etat_Multi_GP_base Class Reference
Loi_Etat_Multi_GP_base Class Reference abstract
#include <Loi_Etat_Multi_GP_base.h>
Public Member Functions
Loi_Etat_Multi_GP_base ()
~Loi_Etat_Multi_GP_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void calculer_masse_molaire ()
void calculer_Cp () override
Calcule le Cp
NE FAIT RIEN : le Cp est constant.
void calculer_lambda () override
Calcule la conductivite.
void calculer_alpha () override
Calcule la diffusivite.
void calculer_mu () override
Calcule la viscosite dynamique.
virtual void associer_inconnue (const Champ_Inc_base &inconnue)
Associe l inconnue de chaque equation de
fraction massique a la loi d'etat.
void initialiser_inco_ch () override
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
double calculer_masse_volumique (double, double) const override
void calculer_masse_volumique () override=0
Calcule la masse volumique.
virtual void calculer_masse_molaire (DoubleTab &M) const =0
virtual void calculer_tab_Cp (DoubleTab &cp) const =0
virtual void calculer_mu_wilke ()=0
const DoubleTab & masse_molaire () const
DoubleTab & masse_molaire ()
virtual double calculer_masse_volumique (double P, double T, double r) const
Public Member Functions inherited from Loi_Etat_Melange_GP_base
Loi_Etat_Melange_GP_base ()
~Loi_Etat_Melange_GP_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_fluide (const Fluide_Dilatable_base &) override
Associe le fluide a la loi d'etat.
Public Member Functions inherited from Loi_Etat_GP_base
~Loi_Etat_GP_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_GP_base ()
const Nom type_fluide () const override
Renvoie le type de fluide associe.
void associer_fluide (const Fluide_Dilatable_base &) override
Associe le fluide a la loi d'etat.
void calculer_lambda () override
Calcule la conductivite.
void calculer_alpha () override
Calcule la diffusivite.
void remplir_T () override
Remplit le tableau de la temperature : T=temp+273.15.
void calculer_Cp () override
Calcule le Cp
NE FAIT RIEN : le Cp est constant.
void calculer_masse_volumique () override
Calcule la masse volumique.
void initialiser () override
Initialise la loi d'etat : calcul Pth.
double calculer_masse_volumique (double, double) const override
double inverser_Pth (double, double) override
Calcule la pression avec la temperature et la masse volumique.
double R () const
Public Member Functions inherited from Loi_Etat_base
~Loi_Etat_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_base ()
void assoscier_probleme (const Probleme_base &pb)
Associe le probleme a la loi d'etat.
void mettre_a_jour (double)
Met a jour la loi d'etat et le champ rho.
void calculer_nu ()
Calcule la viscosite cinematique.
Champ_Don & ch_temperature ()
const Champ_Don & ch_temperature () const
Renvoie le champ de le temperature.
virtual void associer_fluide (const Fluide_Dilatable_base &)
Associe le fluide a la loi d'etat.
virtual void preparer_calcul ()
Prepare le fluide au calcul.
virtual void abortTimeStep ()
virtual void initialiser_inco_ch ()
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
virtual void calculer_mu ()
Calcule la viscosite.
virtual void calculer_lambda ()
Calcule la conductivite.
virtual void calculer_alpha ()
Calcule la diffusivite.
virtual void calculer_mu_sur_Sc ()
Ne fait rien
Surcharge dans Loi_Etat_Melange_GP.
virtual void calculer_nu_sur_Sc ()
Ne fait rien
Surcharge dans Loi_Etat_Melange_Binaire.
virtual void calculer_masse_volumique ()
Recalcule la masse volumique.
virtual double calculer_H (double, double) const
Cas gaz parfait : ne fait rien
Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
virtual double Drho_DP (double, double) const
virtual double Drho_DT (double, double) const
virtual double De_DP (double, double) const
virtual double De_DT (double, double) const
const Champ_base & get_champ (const Motcle &nom) const override
void creer_champ (const Motcle &motlu) override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Nom type_fluide () const =0
virtual void initialiser ()=0
virtual void remplir_T ()=0
virtual void calculer_Cp ()=0
virtual double calculer_masse_volumique (double, double) const =0
virtual double inverser_Pth (double, double)=0
Champs_compris & champs_compris ()
const DoubleTab & temperature () const
const DoubleTab & rho_n () const
const DoubleTab & rho_np1 () const
double Prandt () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static const Type_info * info ()
static Loi_Etat_Multi_GP_base & self_cast (Objet_U &)
static const Loi_Etat_Multi_GP_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_Melange_GP_base
static const Type_info * info ()
static Loi_Etat_Melange_GP_base & self_cast (Objet_U &)
static const Loi_Etat_Melange_GP_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_GP_base
static const Type_info * info ()
static Loi_Etat_GP_base & self_cast (Objet_U &)
static const Loi_Etat_GP_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_base
static const Type_info * info ()
static Loi_Etat_base & self_cast (Objet_U &)
static const Loi_Etat_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_Melange_GP_base
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_GP_base
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void calculer_tab_mu (const DoubleTab &mu, int size)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
List_Ref_Champ_Inc_base liste_Y
DoubleTab masse_mol_mel
Protected Attributes inherited from Loi_Etat_GP_base
double Cp_
double R_
Protected Attributes inherited from Loi_Etat_base
Ref_Fluide_Dilatable_base le_fluide
Ref_Probleme_base le_prob_
Champ_Don temperature_
DoubleTab tab_rho_n
DoubleTab tab_rho_np1
double Pr_
int debug
Additional Inherited Members
Static Protected Attributes inherited from Loi_Etat_Melange_GP_base
static constexpr double R_GAS = 8.314472
Detailed Description
Definition at line 37 of file Loi_Etat_Multi_GP_base.h.
Constructor & Destructor Documentation
Loi_Etat_Multi_GP_base()
Loi_Etat_Multi_GP_base::Loi_Etat_Multi_GP_base ()
Definition at line 25 of file Loi_Etat_Multi_GP_base.cpp.
~Loi_Etat_Multi_GP_base()
Loi_Etat_Multi_GP_base::~Loi_Etat_Multi_GP_base () override
Definition at line 25 of file Loi_Etat_Multi_GP_base.cpp.
Member Function Documentation
associer_inconnue()
void Loi_Etat_Multi_GP_base::associer_inconnue (const Champ_Inc_base & inconnue) virtual
Associe l inconnue de chaque equation de
fraction massique a la loi d'etat.
Definition at line 68 of file Loi_Etat_Multi_GP_base.cpp.
{
  REF(Champ_Inc_base) inco;
  inco = inconnue;
  liste_Y.add(inco);
}
References List_Ref_Champ_Inc_base::add(), liste_Y, and REF.
Referenced by Convection_Diffusion_Espece_Multi_QC::completer(), and Convection_Diffusion_Espece_Multi_WC::completer().
calculer_alpha()
void Loi_Etat_Multi_GP_base::calculer_alpha () override virtual
Calcule la diffusivite.
< VEF
Reimplemented from Loi_Etat_GP_base.
Definition at line 141 of file Loi_Etat_Multi_GP_base.cpp.
{
  const Champ_Don& lambda = le_fluide->conductivite();
  const DoubleTab& tab_lambda = lambda.valeurs();
  Champ_Don& alpha=le_fluide->diffusivite();
  DoubleTab& tab_alpha = le_fluide->diffusivite().valeurs();
  const DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  const DoubleTab& tab_Cp = le_fluide->capacite_calorifique().valeurs();
  int i, n = tab_alpha.size(), isVDF = 0;
  if (alpha.valeur().que_suis_je()=="Champ_Fonc_P0_VDF") isVDF = 1;
  if (isVDF)
    {
      if (sub_type(Champ_Uniforme,lambda.valeur()))
        {
          double lambda0 = tab_lambda(0,0);
          for (i=0 ; i<n ; i++)  tab_alpha(i,0) = lambda0 / ( tab_rho(i,0) * tab_Cp(i,0) );
        }
      else
        {
          for (i=0 ; i<n ; i++) tab_alpha(i,0) = tab_lambda(i,0) / ( tab_rho(i,0) * tab_Cp(i,0) );
        }
    }
  else //!< VEF
    {
      const IntTab& elem_faces=ref_cast(Zone_VF,le_fluide->vitesse().zone_dis_base()).elem_faces();
      double rhoelem, Cpelem;
      int face, nfe = elem_faces.line_size();
      if (sub_type(Champ_Uniforme,lambda.valeur()))
        {
          double lambda0 = tab_lambda(0,0);
          for (i=0 ; i<n ; i++)
            {
              rhoelem = 0;
              Cpelem = 0;
              for (face=0; face<nfe; face++)
                {
                  rhoelem += tab_rho(elem_faces(i,face),0);
                  Cpelem += tab_Cp(elem_faces(i,face),0);
                }
              rhoelem /= nfe;
              Cpelem /= nfe;
              tab_alpha(i,0) = lambda0 / ( rhoelem * Cpelem );
            }
        }
      else
        {
          for (i=0 ; i<n ; i++)
            {
              rhoelem = 0;
              Cpelem = 0;
              for (face=0; face<nfe; face++)
                {
                  rhoelem += tab_rho(elem_faces(i,face),0);
                  Cpelem += tab_Cp(elem_faces(i,face),0);
                }
              rhoelem /= nfe;
              Cpelem /= nfe;
              tab_alpha(i,0) = tab_lambda(i,0) / ( rhoelem * Cpelem );
            }
        }
    }
  tab_alpha.echange_espace_virtuel();
  Debog::verifier("alpha",tab_alpha);
}
References Milieu_base::capacite_calorifique(), Milieu_base::conductivite(), Milieu_base::diffusivite(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Loi_Etat_base::le_fluide, TRUSTVect< _TYPE_ >::line_size(), Milieu_base::masse_volumique(), Objet_U::que_suis_je(), ref_cast, TRUSTVect< _TYPE_ >::size(), sub_type, Deriv_Champ_Don_base::valeur(), Champ::valeurs(), Champ_Don::valeurs(), Debog::verifier(), Fluide_Dilatable_base::vitesse(), and Champ_Inc::zone_dis_base().
calculer_Cp()
void Loi_Etat_Multi_GP_base::calculer_Cp () override virtual
Calcule le Cp
NE FAIT RIEN : le Cp est constant.
Reimplemented from Loi_Etat_GP_base.
Definition at line 75 of file Loi_Etat_Multi_GP_base.cpp.
{
  Champ_Don& Cp = le_fluide->capacite_calorifique();
  DoubleTab& tab_Cp = Cp.valeurs();
  calculer_tab_Cp(tab_Cp);
  tab_Cp.echange_espace_virtuel();
  Debog::verifier("tab_Cp",tab_Cp);
}
References calculer_tab_Cp(), Milieu_base::capacite_calorifique(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Loi_Etat_base::le_fluide, Champ_Don::valeurs(), and Debog::verifier().
calculer_lambda()
void Loi_Etat_Multi_GP_base::calculer_lambda () override virtual
Calcule la conductivite.
Reimplemented from Loi_Etat_GP_base.
Definition at line 98 of file Loi_Etat_Multi_GP_base.cpp.
{
  const Champ_Don& mu = le_fluide->viscosite_dynamique();
  const DoubleTab& tab_mu = mu.valeurs();
  Champ_Don& lambda = le_fluide->conductivite();
  DoubleTab& tab_lambda = lambda.valeurs();
  const DoubleTab& tab_Cp = le_fluide->capacite_calorifique().valeurs();
  int i, n = tab_lambda.size();
// La conductivite est soit un champ uniforme soit calculee a partir de la viscosite dynamique et du Pr
  if (sub_type(Champ_Fonc_Tabule,lambda.valeur()))
    {
      lambda.valeur().mettre_a_jour(temperature_.valeur().temps());
      return;
    }
  if (!sub_type(Champ_Uniforme,lambda.valeur()))
    {
      if (sub_type(Champ_Uniforme,mu.valeur()))
        {
          double mu0 = tab_mu(0,0);
          for (i=0 ; i<n ; i++)  tab_lambda(i,0) = mu0 * Cp_ / Pr_;
        }
      else
        for (i=0 ; i<n ; i++) tab_lambda(i,0) = tab_mu(i,0) * tab_Cp(i,0) / Pr_;
    }
  tab_lambda.echange_espace_virtuel();
  Debog::verifier("tab_lambda",tab_lambda);
}
References Milieu_base::capacite_calorifique(), Milieu_base::conductivite(), Loi_Etat_GP_base::Cp_, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Loi_Etat_base::le_fluide, Champ_Don_base::mettre_a_jour(), Loi_Etat_base::Pr_, TRUSTVect< _TYPE_ >::size(), sub_type, Loi_Etat_base::temperature_, Champ_base::temps(), Deriv_Champ_Don_base::valeur(), Champ_Don::valeurs(), Debog::verifier(), and Fluide_base::viscosite_dynamique().
calculer_masse_molaire() [1/2]
void Loi_Etat_Multi_GP_base::calculer_masse_molaire ()
Definition at line 47 of file Loi_Etat_Multi_GP_base.cpp.
{
  calculer_masse_molaire(masse_mol_mel);
  Debog::verifier("Masse_mol_mel",masse_mol_mel);
}
References calculer_masse_molaire(), masse_mol_mel, and Debog::verifier().
Referenced by calculer_masse_molaire(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), and initialiser_inco_ch().
calculer_masse_molaire() [2/2]
virtual void Loi_Etat_Multi_GP_base::calculer_masse_molaire (DoubleTab & M) const pure virtual
Implemented in Loi_Etat_Multi_GP_QC, and Loi_Etat_Multi_GP_WC.
calculer_masse_volumique() [1/3]
void Loi_Etat_Multi_GP_base::calculer_masse_volumique () override pure virtual
Calcule la masse volumique.
Reimplemented from Loi_Etat_GP_base.
Implemented in Loi_Etat_Multi_GP_QC, and Loi_Etat_Multi_GP_WC.
Referenced by Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), and Loi_Etat_Multi_GP_WC::calculer_masse_volumique().
calculer_masse_volumique() [2/3]
double Loi_Etat_Multi_GP_base::calculer_masse_volumique (double P, double T, double r) const virtual
Reimplemented in Loi_Etat_Multi_GP_QC, and Loi_Etat_Multi_GP_WC.
Definition at line 208 of file Loi_Etat_Multi_GP_base.cpp.
{
  if (inf_ou_egal(T,0))
    {
      Cerr << finl << "Warning: Temperature T must be defined in Kelvin." << finl;
      Cerr << "Check your data file." << finl;
      Process::exit();
    }
  return P / ( r * T );
}
References Cerr, Process::exit(), finl, and inf_ou_egal().
calculer_masse_volumique() [3/3]
double Loi_Etat_Multi_GP_base::calculer_masse_volumique (double P, double T) const override virtual
Reimplemented from Loi_Etat_GP_base.
Reimplemented in Loi_Etat_Multi_GP_QC, and Loi_Etat_Multi_GP_WC.
Definition at line 219 of file Loi_Etat_Multi_GP_base.cpp.
{
  Cerr << "You should not call the method Loi_Etat_Multi_GP_base::calculer_masse_volumique(double P, double T) !" << finl;
  Process::exit();
  return -1000.;
}
References Cerr, Process::exit(), and finl.
calculer_mu()
void Loi_Etat_Multi_GP_base::calculer_mu () override virtual
Calcule la viscosite dynamique.
Reimplemented from Loi_Etat_base.
Definition at line 240 of file Loi_Etat_Multi_GP_base.cpp.
{
  Champ_Don& mu = le_fluide->viscosite_dynamique();
  if (!sub_type(Champ_Uniforme,mu.valeur()))
    {
      if (sub_type(Champ_Fonc_Tabule,mu.valeur())) mu.mettre_a_jour(temperature_.valeur().temps());
      else calculer_mu_wilke();
    }
}
References calculer_mu_wilke(), Loi_Etat_base::le_fluide, Champ_Don::mettre_a_jour(), sub_type, Loi_Etat_base::temperature_, Champ_base::temps(), Deriv_Champ_Don_base::valeur(), and Fluide_base::viscosite_dynamique().
calculer_mu_wilke()
virtual void Loi_Etat_Multi_GP_base::calculer_mu_wilke () pure virtual
Implemented in Loi_Etat_Multi_GP_QC, and Loi_Etat_Multi_GP_WC.
Referenced by calculer_mu().
calculer_tab_Cp()
virtual void Loi_Etat_Multi_GP_base::calculer_tab_Cp (DoubleTab & cp) const pure virtual
Implemented in Loi_Etat_Multi_GP_QC, and Loi_Etat_Multi_GP_WC.
Referenced by calculer_Cp().
calculer_tab_mu()
void Loi_Etat_Multi_GP_base::calculer_tab_mu (const DoubleTab & mu, int size) protected
< VDF
< VEF (average on elem from values on face);
Definition at line 250 of file Loi_Etat_Multi_GP_base.cpp.
{
// Dynamic viscosity is on elem
  DoubleTab& tab_mu = le_fluide->viscosite_dynamique().valeurs();
  const int nb_elem = tab_mu.size();
  if (nb_elem==size) //!< VDF
    {
      for (int elem=0; elem < nb_elem; elem++) tab_mu(elem,0) = mu(elem);
    }
  else //!< VEF (average on elem from values on face);
    {
      const IntTab& elem_faces=ref_cast(Zone_VF,le_fluide->vitesse().zone_dis_base()).elem_faces();
      const int nfe = elem_faces.line_size();
      tab_mu = 0;
      for (int elem=0; elem<nb_elem; elem++)
        {
          for (int face = 0; face < nfe; face++) tab_mu(elem,0) += mu(elem_faces(elem, face));
          tab_mu(elem,0) /= nfe;
        }
    }
  tab_mu.echange_espace_virtuel();
  Debog::verifier("tab_mu", tab_mu);
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Loi_Etat_base::le_fluide, TRUSTVect< _TYPE_ >::line_size(), ref_cast, TRUSTVect< _TYPE_ >::size(), Champ_Don::valeurs(), Debog::verifier(), Fluide_base::viscosite_dynamique(), Fluide_Dilatable_base::vitesse(), and Champ_Inc::zone_dis_base().
Referenced by Loi_Etat_Multi_GP_QC::calculer_mu_wilke(), and Loi_Etat_Multi_GP_WC::calculer_mu_wilke().
get_info()
const Type_info * Loi_Etat_Multi_GP_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_Melange_GP_base.
Reimplemented in Loi_Etat_Multi_GP_QC, and Loi_Etat_Multi_GP_WC.
Definition at line 25 of file Loi_Etat_Multi_GP_base.cpp.
info()
const Type_info * Loi_Etat_Multi_GP_base::info () static
Definition at line 25 of file Loi_Etat_Multi_GP_base.cpp.
initialiser_inco_ch()
void Loi_Etat_Multi_GP_base::initialiser_inco_ch () override virtual
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_Multi_GP_WC.
Definition at line 39 of file Loi_Etat_Multi_GP_base.cpp.
{
  const int num = liste_Y(0).valeur().valeurs().size();
  masse_mol_mel.resize(num,1);
  calculer_masse_molaire();
  Loi_Etat_base::initialiser_inco_ch();
}
References calculer_masse_molaire(), Loi_Etat_base::initialiser_inco_ch(), liste_Y, masse_mol_mel, TRUSTTab< _TYPE_ >::resize(), and List_Ref_Champ_Inc_base::valeur().
Referenced by Loi_Etat_Multi_GP_WC::initialiser_inco_ch().
masse_molaire() [1/2]
DoubleTab & Loi_Etat_Multi_GP_base::masse_molaire () inline
Definition at line 58 of file Loi_Etat_Multi_GP_base.h.
{ return masse_mol_mel; }
References masse_mol_mel.
masse_molaire() [2/2]
const DoubleTab & Loi_Etat_Multi_GP_base::masse_molaire () const inline
Definition at line 57 of file Loi_Etat_Multi_GP_base.h.
{ return masse_mol_mel; }
References masse_mol_mel.
Referenced by EDO_Pression_th_VDF::masse_totale(), and EDO_Pression_th_VEF::masse_totale().
printOn()
Sortie & Loi_Etat_Multi_GP_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Loi_Etat_Melange_GP_base.
Reimplemented in Loi_Etat_Multi_GP_QC, and Loi_Etat_Multi_GP_WC.
Definition at line 27 of file Loi_Etat_Multi_GP_base.cpp.
{
  os <<que_suis_je()<< finl;
  return os;
}
References finl, and Objet_U::que_suis_je().
readOn()
Entree & Loi_Etat_Multi_GP_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Loi_Etat_Melange_GP_base.
Reimplemented in Loi_Etat_Multi_GP_QC, and Loi_Etat_Multi_GP_WC.
Definition at line 33 of file Loi_Etat_Multi_GP_base.cpp.
{
  return is;
}
self_cast() [1/2]
const Loi_Etat_Multi_GP_base & Loi_Etat_Multi_GP_base::self_cast (const Objet_U & r) static
Definition at line 25 of file Loi_Etat_Multi_GP_base.cpp.
self_cast() [2/2]
Loi_Etat_Multi_GP_base & Loi_Etat_Multi_GP_base::self_cast (Objet_U & r) static
Definition at line 25 of file Loi_Etat_Multi_GP_base.cpp.
Member Data Documentation
info_obj
const Type_info Loi_Etat_Multi_GP_base::info_obj static
Definition at line 39 of file Loi_Etat_Multi_GP_base.h.
liste_Y
List_Ref_Champ_Inc_base Loi_Etat_Multi_GP_base::liste_Y protected
Definition at line 63 of file Loi_Etat_Multi_GP_base.h.
Referenced by associer_inconnue(), Loi_Etat_Multi_GP_QC::calculer_masse_molaire(), Loi_Etat_Multi_GP_WC::calculer_masse_molaire(), Loi_Etat_Multi_GP_QC::calculer_mu_wilke(), Loi_Etat_Multi_GP_WC::calculer_mu_wilke(), Loi_Etat_Multi_GP_QC::calculer_tab_Cp(), Loi_Etat_Multi_GP_WC::calculer_tab_Cp(), initialiser_inco_ch(), Loi_Etat_Multi_GP_WC::initialiser_inco_ch(), Loi_Etat_Multi_GP_QC::rabot(), and Loi_Etat_Multi_GP_WC::update_Yn_values().
masse_mol_mel
DoubleTab Loi_Etat_Multi_GP_base::masse_mol_mel protected
Definition at line 64 of file Loi_Etat_Multi_GP_base.h.
Referenced by calculer_masse_molaire(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), initialiser_inco_ch(), and masse_molaire().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat_Multi_GP_base.h
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat_Multi_GP_base.cpp