TRUST: Elem_PolyMAC Class Reference
Elem_PolyMAC Class Reference
#include <Elem_PolyMAC.h>
Public Member Functions
Elem_PolyMAC ()
~Elem_PolyMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Elem_PolyMAC & operator= (const Elem_PolyMAC_base &)
void typer (Nom)
determination du type
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Elem_PolyMAC & self_cast (Objet_U &)
static const Elem_PolyMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Detailed Description
Definition at line 42 of file Elem_PolyMAC.h.
Constructor & Destructor Documentation
Elem_PolyMAC::Elem_PolyMAC ()
Definition at line 30 of file Elem_PolyMAC.cpp.
Elem_PolyMAC::~Elem_PolyMAC ()
Definition at line 30 of file Elem_PolyMAC.cpp.
Member Function Documentation
Objet_U * Elem_PolyMAC::cree_instance () [static]
Reimplemented from Deriv_Elem_PolyMAC_base.
Definition at line 30 of file Elem_PolyMAC.cpp.
int Elem_PolyMAC::duplique () const [virtual]
Reimplemented from Deriv_Elem_PolyMAC_base.
Definition at line 30 of file Elem_PolyMAC.cpp.
const Type_info * Elem_PolyMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Elem_PolyMAC_base.
Definition at line 30 of file Elem_PolyMAC.cpp.
const Type_info * Elem_PolyMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Elem_PolyMAC_base.
Definition at line 30 of file Elem_PolyMAC.cpp.
void Elem_PolyMAC::normale (int num_face, DoubleTab & Face_normales, const IntTab & Face_sommets, const IntTab & Face_voisins, const IntTab & elem_faces, const Zone & zone_geom) const [inline]
Definition at line 69 of file Elem_PolyMAC.h.
References Elem_PolyMAC_base::normale(), and Deriv_Elem_PolyMAC_base::valeur().
Referenced by Zone_PolyMAC::discretiser().
{
  valeur().normale(num_face,Face_normales,Face_sommets,Face_voisins,
                   elem_faces,zone_geom);
}
Elem_PolyMAC & Elem_PolyMAC::operator= (const Elem_PolyMAC_base & elem_base) [inline]
Reimplemented from Deriv_Elem_PolyMAC_base.
Definition at line 61 of file Elem_PolyMAC.h.
References DERIV.
{
  DERIV(Elem_PolyMAC_base)::operator=(elem_base);
  return *this;
}
Sortie & Elem_PolyMAC::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_Elem_PolyMAC_base.
Definition at line 36 of file Elem_PolyMAC.cpp.
References Deriv_Elem_PolyMAC_base::valeur().
{
  return s << valeur() ;
}
Entree & Elem_PolyMAC::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_Elem_PolyMAC_base.
Definition at line 41 of file Elem_PolyMAC.cpp.
References Cerr, Process::exit(), and finl.
{
  Nom type;
  s >> type;
  if(type == "Tri_PolyMAC")
    *this =  Tri_PolyMAC();
  else if(type == "Tetra_PolyMAC")
    *this =  Tetra_PolyMAC();
  else if(type == "Quadri_PolyMAC")
    *this =  Quadri_PolyMAC();
  else if(type == "Hexa_PolyMAC")
    *this =  Hexa_PolyMAC();
  else
    {
      Cerr << type << " n'est pas un Elem_PolyMAC" << finl;
      exit();
    }
  return s ;
}
const Elem_PolyMAC & Elem_PolyMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Elem_PolyMAC_base.
Definition at line 30 of file Elem_PolyMAC.cpp.
Elem_PolyMAC & Elem_PolyMAC::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Elem_PolyMAC_base.
Definition at line 30 of file Elem_PolyMAC.cpp.
unsigned Elem_PolyMAC::taille_memoire () const [virtual]
Reimplemented from Deriv_Elem_PolyMAC_base.
Definition at line 30 of file Elem_PolyMAC.cpp.
void Elem_PolyMAC::typer (Nom type_elem_geom)
determination du type
Definition at line 63 of file Elem_PolyMAC.cpp.
References Cerr, DERIV, Process::exit(), finl, Objet_U::que_suis_je(), and Deriv_Elem_PolyMAC_base::valeur().
Referenced by Zone_PolyMAC::typer_elem().
{
  Cerr << "Elem_PolyMAC::typer()" << finl ;
  Cerr << "type geometrique : " << type_elem_geom << finl;
  Nom type;
  if(type_elem_geom=="Triangle")
    type="Tri_PolyMAC";
  else if(type_elem_geom=="Tetraedre")
    type="Tetra_PolyMAC";
  else if(type_elem_geom=="Quadrangle")
    type="Quadri_PolyMAC";
  else if(type_elem_geom=="Hexaedre_VEF")
    type="Hexa_PolyMAC";
  else if(type_elem_geom=="Segment")
    type="Segment_PolyMAC";
  else if(type_elem_geom=="Polygone")
    type="Polygone_PolyMAC";
  else if(type_elem_geom=="Polyedre")
    type="Polyedre_PolyMAC";
  else
    {
      Cerr << "probleme de typage dans Elem_PolyMAC::typer" << finl;
      exit();
    }
  DERIV(Elem_PolyMAC_base)::typer(type);
  Cerr << "type retenu : " << valeur().que_suis_je() << finl ;
}
Member Data Documentation
const Type_info Elem_PolyMAC::info_obj [static]
Reimplemented from Deriv_Elem_PolyMAC_base.
Definition at line 44 of file Elem_PolyMAC.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Zones/Elem_PolyMAC.h
src/PolyMAC/Zones/Elem_PolyMAC.cpp