TRUST: Ref_Postraitement Class Reference
Ref_Postraitement Class Reference
#include <Ref_Postraitement.h>
Public Member Functions
~Ref_Postraitement ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Postraitement ()
Ref_Postraitement (const Postraitement &)
Ref_Postraitement (const Ref_Postraitement &)
const Postraitement & valeur () const
Postraitement & valeur ()
const Postraitement * operator-> () const
Postraitement * operator-> ()
const Ref_Postraitement & operator= (const Postraitement &)
const Ref_Postraitement & operator= (const Ref_Postraitement &)
operator const Postraitement & () const
operator Postraitement & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Postraitement & self_cast (Objet_U &)
static const Ref_Postraitement & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Postraitement * pointeur_
Detailed Description
Definition at line 29 of file Ref_Postraitement.h.
Constructor & Destructor Documentation
Ref_Postraitement::~Ref_Postraitement ()
Definition at line 26 of file Ref_Postraitement.cpp.
Ref_Postraitement::Ref_Postraitement ()
Definition at line 26 of file Ref_Postraitement.cpp.
Ref_Postraitement::Ref_Postraitement (const Postraitement & t)
Definition at line 26 of file Ref_Postraitement.cpp.
Ref_Postraitement::Ref_Postraitement (const Ref_Postraitement & t)
Definition at line 26 of file Ref_Postraitement.cpp.
Member Function Documentation
Objet_U * Ref_Postraitement::cree_instance () [static]
Definition at line 26 of file Ref_Postraitement.cpp.
int Ref_Postraitement::duplique () const [virtual]
Implements Ref_.
Definition at line 26 of file Ref_Postraitement.cpp.
const Type_info * Ref_Postraitement::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Postraitement.cpp.
const Type_info & Ref_Postraitement::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Ref_Postraitement.cpp.
const Type_info * Ref_Postraitement::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Postraitement.cpp.
Ref_Postraitement::operator const Postraitement & () const
Definition at line 26 of file Ref_Postraitement.cpp.
Ref_Postraitement::operator Postraitement & ()
Definition at line 26 of file Ref_Postraitement.cpp.
const Postraitement * Ref_Postraitement::operator-> () const [inline]
Definition at line 29 of file Ref_Postraitement.h.
Postraitement * Ref_Postraitement::operator-> () [inline]
Definition at line 29 of file Ref_Postraitement.h.
const Ref_Postraitement & Ref_Postraitement::operator= (const Ref_Postraitement & t)
Definition at line 26 of file Ref_Postraitement.cpp.
const Ref_Postraitement & Ref_Postraitement::operator= (const Postraitement & t)
Definition at line 26 of file Ref_Postraitement.cpp.
Sortie & Ref_Postraitement::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Postraitement.cpp.
Entree & Ref_Postraitement::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Postraitement.cpp.
const Ref_Postraitement & Ref_Postraitement::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 26 of file Ref_Postraitement.cpp.
Ref_Postraitement & Ref_Postraitement::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 26 of file Ref_Postraitement.cpp.
void Ref_Postraitement::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Ref_Postraitement.cpp.
unsigned Ref_Postraitement::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Ref_Postraitement.cpp.
const Postraitement & Ref_Postraitement::valeur () const [inline]
Definition at line 29 of file Ref_Postraitement.h.
Referenced by Sondes::lire_fichier(), Sonde::mettre_a_jour(), Sondes_Int::readOn(), and Sondes::readOn().
Postraitement & Ref_Postraitement::valeur () [inline]
Definition at line 29 of file Ref_Postraitement.h.
Member Data Documentation
const Type_info Ref_Postraitement::info_obj [static]
Reimplemented from Ref_.
Definition at line 29 of file Ref_Postraitement.h.
Postraitement* Ref_Postraitement::pointeur_ [private]
Definition at line 29 of file Ref_Postraitement.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Ref_Postraitement.h
src/Kernel/Framework/Ref_Postraitement.cpp