TRUST: MergeMEDfiles Class Reference
MergeMEDfiles Class Reference
Class MergeMEDfiles
Merge several MED files written by several procs into a single field object
with a proper underlying mesh (no duplicate nodes)
Usage in data file
Merge_MED [NOM_DU_CAS||med_files_base_name] [all_times||last_time].
#include <MergeMEDfiles.h>
Public Member Functions
MergeMEDfiles ()
~MergeMEDfiles ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static MergeMEDfiles & self_cast (Objet_U &)
static const MergeMEDfiles & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Interprete::printOn(Sortie&)
virtual Entree & readOn (Entree &)
Simple appel a: Interprete::readOn(Entree&)
Private Member Functions
void mergeFields (const std::vector< std::string > &field_names, const std::vector< std::string > &meshes_names, const std::vector< std::string > &listmed, const std::vector< std::pair< std::pair< True_int, True_int >, double >> &lst_dt, const int mesh_numb, const int iter_numb, Nom out_file, bool &first_time, const bool isCell) const
Detailed Description
Class MergeMEDfiles
Merge several MED files written by several procs into a single field object
with a proper underlying mesh (no duplicate nodes)
Usage in data file
Merge_MED [NOM_DU_CAS||med_files_base_name] [all_times||last_time].
Definition at line 45 of file MergeMEDfiles.h.
Constructor & Destructor Documentation
MergeMEDfiles::MergeMEDfiles ()
Definition at line 36 of file MergeMEDfiles.cpp.
MergeMEDfiles::~MergeMEDfiles ()
Definition at line 36 of file MergeMEDfiles.cpp.
Member Function Documentation
Objet_U * MergeMEDfiles::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 36 of file MergeMEDfiles.cpp.
int MergeMEDfiles::duplique () const [virtual]
Reimplemented from Interprete.
Definition at line 36 of file MergeMEDfiles.cpp.
const Type_info * MergeMEDfiles::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 36 of file MergeMEDfiles.cpp.
const Type_info * MergeMEDfiles::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 36 of file MergeMEDfiles.cpp.
Entree & MergeMEDfiles::interpreter (Entree & is) [virtual]
Reimplemented from Interprete.
Definition at line 267 of file MergeMEDfiles.cpp.
References Cerr, and Process::exit().
{
  Cerr << "Version compiled without MEDCoupling" << finl;
  Process::exit();
  return is;
}
void MergeMEDfiles::mergeFields (const std::vector< std::string > & field_names, const std::vector< std::string > & meshes_names, const std::vector< std::string > & listmed, const std::vector< std::pair< std::pair< True_int, True_int >, double >> & lst_dt, const int mesh_numb, const int iter_numb, Nom out_file, bool & first_time, const bool isCell) const [private]
Definition at line 275 of file MergeMEDfiles.cpp.
References Cerr, and Process::exit().
{
  Cerr << "Version compiled without MEDCoupling" << finl;
  Process::exit();
}
Sortie & MergeMEDfiles::printOn (Sortie & os) const [protected, virtual]
Simple appel a: Interprete::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 56 of file MergeMEDfiles.cpp.
References Interprete::printOn().
{
  return Interprete::printOn(os);
}
Entree & MergeMEDfiles::readOn (Entree & is) [protected, virtual]
Simple appel a: Interprete::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 76 of file MergeMEDfiles.cpp.
References Interprete::readOn().
{
  return Interprete::readOn(is);
}
MergeMEDfiles & MergeMEDfiles::self_cast (Objet_U & r) [static]
Reimplemented from Interprete.
Definition at line 36 of file MergeMEDfiles.cpp.
const MergeMEDfiles & MergeMEDfiles::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete.
Definition at line 36 of file MergeMEDfiles.cpp.
unsigned MergeMEDfiles::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 36 of file MergeMEDfiles.cpp.
Member Data Documentation
const Type_info MergeMEDfiles::info_obj [static]
Reimplemented from Interprete.
Definition at line 47 of file MergeMEDfiles.h.
The documentation for this class was generated from the following files:
src/Kernel/MEDimpl/MergeMEDfiles.h
src/Kernel/MEDimpl/MergeMEDfiles.cpp