TRUST: Remove_Invalid_Internal_Boundaries Class Reference
Remove_Invalid_Internal_Boundaries Class Reference
: class Remove_Invalid_Internal_Boundaries
<Description of class Remove_Invalid_Internal_Boundaries>
#include <Remove_Invalid_Internal_Boundaries.h>
Public Member Functions
Remove_Invalid_Internal_Boundaries ()
~Remove_Invalid_Internal_Boundaries ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &is) override
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Remove_Invalid_Internal_Boundaries & self_cast (Objet_U &)
static const Remove_Invalid_Internal_Boundaries & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
: class Remove_Invalid_Internal_Boundaries
<Description of class Remove_Invalid_Internal_Boundaries>
Definition at line 31 of file Remove_Invalid_Internal_Boundaries.h.
Constructor & Destructor Documentation
Remove_Invalid_Internal_Boundaries()
Remove_Invalid_Internal_Boundaries::Remove_Invalid_Internal_Boundaries ()
Definition at line 23 of file Remove_Invalid_Internal_Boundaries.cpp.
~Remove_Invalid_Internal_Boundaries()
Remove_Invalid_Internal_Boundaries::~Remove_Invalid_Internal_Boundaries ()
Definition at line 23 of file Remove_Invalid_Internal_Boundaries.cpp.
Member Function Documentation
cree_instance()
Objet_U * Remove_Invalid_Internal_Boundaries::cree_instance () static
Definition at line 23 of file Remove_Invalid_Internal_Boundaries.cpp.
duplique()
int Remove_Invalid_Internal_Boundaries::duplique () const override virtual
Implements Objet_U.
Definition at line 23 of file Remove_Invalid_Internal_Boundaries.cpp.
get_info()
const Type_info * Remove_Invalid_Internal_Boundaries::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 23 of file Remove_Invalid_Internal_Boundaries.cpp.
info()
const Type_info * Remove_Invalid_Internal_Boundaries::info () static
Definition at line 23 of file Remove_Invalid_Internal_Boundaries.cpp.
interpreter_()
Entree & Remove_Invalid_Internal_Boundaries::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base.
Definition at line 37 of file Remove_Invalid_Internal_Boundaries.cpp.
{
  associer_domaine(is);
  Domaine& domain = domaine(0);
  Zone&    zone   = domain.zone(0);
  Scatter::uninit_sequential_domain(domain);
  Static_Int_Lists incidence;
  construire_connectivite_som_elem(domain.nb_som_tot(), zone.les_elems(), incidence, 1);
  LIST(Nom) name_of_useless_boundaries;
  LIST(Nom) name_of_useless_connectors;
  ArrOfInt nodes_of_frontier_face;
  ArrOfInt cells_on_frontier_face;
  cells_on_frontier_face.set_smart_resize(1);
  {
    LIST_CURSEUR(Bord) cursor(zone.faces_bord());
    while (cursor)
      {
        const Faces& frontier_faces    = cursor.valeur().faces();
        const int nb_frontier_faces = frontier_faces.nb_faces_tot();
        const int nb_nodes_per_face = frontier_faces.nb_som_faces();
        nodes_of_frontier_face.resize_array(nb_nodes_per_face);
        cells_on_frontier_face.resize_array(0);
        for (int i=0; i<nb_nodes_per_face; ++i)
          {
            nodes_of_frontier_face[i] = frontier_faces.sommet(0,i);
          }
        find_adjacent_elements(incidence,nodes_of_frontier_face,cells_on_frontier_face);
        bool remove_frontier = false;
        if (cells_on_frontier_face.size_array() == 1)
          {
            remove_frontier = false;
          }
        else if (cells_on_frontier_face.size_array() == 2)
          {
            remove_frontier = true;
            Nom dummy;
            Nom& new_useless_frontier_name = name_of_useless_boundaries.add(dummy);
            new_useless_frontier_name = cursor.valeur().le_nom();
          }
        else
          {
            Cerr << "Error in 'Remove_Invalid_Internal_Boundaries::interpreter_()' :" << finl;
            Cerr << "  Invalid incidence" << finl;
            Process::exit();
          }
        for (int f=0; f<nb_frontier_faces; ++f)
          {
            for (int i=0; i<nb_nodes_per_face; ++i)
              {
                nodes_of_frontier_face[i] = frontier_faces.sommet(0,i);
              }
            find_adjacent_elements(incidence,nodes_of_frontier_face,cells_on_frontier_face);
            if (remove_frontier)
              {
                if (cells_on_frontier_face.size_array() != 2)
                  {
                    Cerr << "Error in 'Remove_Invalid_Internal_Boundaries::interpreter_()' :" << finl;
                    Cerr << "  Invalid incidence" << finl;
                    Process::exit();
                  }
              }
            else
              {
                if (cells_on_frontier_face.size_array() != 1)
                  {
                    Cerr << "Error in 'Remove_Invalid_Internal_Boundaries::interpreter_()' :" << finl;
                    Cerr << "  Invalid incidence" << finl;
                    Process::exit();
                  }
              }
          }
        ++cursor;
      }
  }
  {
    LIST_CURSEUR(Raccord) cursor(zone.faces_raccord());
    while (cursor)
      {
        const Faces& frontier_faces    = cursor.valeur().valeur().faces();
        const int nb_frontier_faces = frontier_faces.nb_faces_tot();
        const int nb_nodes_per_face = frontier_faces.nb_som_faces();
        nodes_of_frontier_face.resize_array(nb_nodes_per_face);
        cells_on_frontier_face.resize_array(0);
        for (int i=0; i<nb_nodes_per_face; ++i)
          {
            nodes_of_frontier_face[i] = frontier_faces.sommet(0,i);
          }
        find_adjacent_elements(incidence,nodes_of_frontier_face,cells_on_frontier_face);
        bool remove_frontier = false;
        if (cells_on_frontier_face.size_array() == 1)
          {
            remove_frontier = false;
          }
        else if (cells_on_frontier_face.size_array() == 2)
          {
            remove_frontier = true;
            Nom dummy;
            Nom& new_useless_frontier_name = name_of_useless_connectors.add(dummy);
            new_useless_frontier_name = cursor.valeur().valeur().le_nom();
          }
        else
          {
            Cerr << "Error in 'Remove_Invalid_Internal_Boundaries::interpreter_()' :" << finl;
            Cerr << "  Invalid incidence" << finl;
            Process::exit();
          }
        for (int f=0; f<nb_frontier_faces; ++f)
          {
            for (int i=0; i<nb_nodes_per_face; ++i)
              {
                nodes_of_frontier_face[i] = frontier_faces.sommet(0,i);
              }
            find_adjacent_elements(incidence,nodes_of_frontier_face,cells_on_frontier_face);
            if (remove_frontier)
              {
                if (cells_on_frontier_face.size_array() != 2)
                  {
                    Cerr << "Error in 'Remove_Invalid_Internal_Boundaries::interpreter_()' :" << finl;
                    Cerr << "  Invalid incidence" << finl;
                    Process::exit();
                  }
              }
            else
              {
                if (cells_on_frontier_face.size_array() != 1)
                  {
                    Cerr << "Error in 'Remove_Invalid_Internal_Boundaries::interpreter_()' :" << finl;
                    Cerr << "  Invalid incidence" << finl;
                    Process::exit();
                  }
              }
          }
        ++cursor;
      }
  }
  {
    LIST_CURSEUR(Nom) cursor(name_of_useless_boundaries);
    while (cursor)
      {
        Bords& boundaries = zone.faces_bord();
        boundaries.suppr(zone.bord(cursor.valeur()));
        ++cursor;
      }
  }
  {
    LIST_CURSEUR(Nom) cursor(name_of_useless_connectors);
    while (cursor)
      {
        Raccords& connectors = zone.faces_raccord();
        connectors.suppr(zone.raccord(cursor.valeur()));
        ++cursor;
      }
  }
  Scatter::init_sequential_domain(domain);
  return is;
}
References Interprete_geometrique_base::associer_domaine(), Zone::bord(), Cerr, construire_connectivite_som_elem(), Interprete_geometrique_base::domaine(), Process::exit(), Zone::faces_bord(), Zone::faces_raccord(), find_adjacent_elements(), finl, Scatter::init_sequential_domain(), Nom::le_nom(), Zone::les_elems(), LIST, LIST_CURSEUR, Faces::nb_faces_tot(), Faces::nb_som_faces(), Domaine::nb_som_tot(), Zone::raccord(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), Faces::sommet(), List_Bord::suppr(), List_Raccord::suppr(), Scatter::uninit_sequential_domain(), and Domaine::zone().
printOn()
Sortie & Remove_Invalid_Internal_Boundaries::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 25 of file Remove_Invalid_Internal_Boundaries.cpp.
{
  Interprete::printOn(os);
  return os;
}
References Interprete::printOn().
readOn()
Entree & Remove_Invalid_Internal_Boundaries::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 31 of file Remove_Invalid_Internal_Boundaries.cpp.
{
  Interprete::readOn(is);
  return is;
}
References Interprete::readOn().
self_cast() [1/2]
const Remove_Invalid_Internal_Boundaries & Remove_Invalid_Internal_Boundaries::self_cast (const Objet_U & r) static
Definition at line 23 of file Remove_Invalid_Internal_Boundaries.cpp.
self_cast() [2/2]
Remove_Invalid_Internal_Boundaries & Remove_Invalid_Internal_Boundaries::self_cast (Objet_U & r) static
Definition at line 23 of file Remove_Invalid_Internal_Boundaries.cpp.
taille_memoire()
unsigned Remove_Invalid_Internal_Boundaries::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 23 of file Remove_Invalid_Internal_Boundaries.cpp.
Member Data Documentation
info_obj
const Type_info Remove_Invalid_Internal_Boundaries::info_obj static
Definition at line 34 of file Remove_Invalid_Internal_Boundaries.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Remove_Invalid_Internal_Boundaries.h
src/Kernel/Geometrie/Remove_Invalid_Internal_Boundaries.cpp