TRUST: List_Sonde Class Reference
List_Sonde Class Reference
#include <Sondes.h>
Public Member Functions
List_Sonde ()
~List_Sonde ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
List_Sonde (const Sonde &t)
List_Sonde (const List_Sonde &t)
Sonde & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Sonde & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Sonde & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Sonde & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Sonde & operator() (int i)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Sonde & operator() (int i) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Sonde & operator() (const Nom &n)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Sonde & operator() (const Nom &n) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Sonde & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Sonde & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
List_Sonde & operator= (const Sonde &t)
Sonde * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
List_Sonde & operator= (const List_Sonde &)
List_Sonde & add (const List_Sonde &)
Sonde & add (const Sonde &)
List_Sonde & inserer (const List_Sonde &)
Sonde & inserer (const Sonde &)
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
List_Sonde & operator+= (const List_Sonde &)
List_Sonde & operator+= (const Sonde &)
Sonde & add_if_not (const Sonde &)
Sonde & add_if_not (const char *const)
List_Sonde & search (const Sonde &) const
List_Sonde & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
List_Sonde & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
const List_Sonde & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
const List_Sonde & dernier () const
Renvoie le dernier element de la liste.
List_Sonde & dernier ()
Renvoie le dernier element de la liste.
List_Sonde & operator-= (const Sonde &)
int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
int contient (const Sonde &) const
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
int rang (const Sonde &) const
void suppr (const Sonde &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static List_Sonde & self_cast (Objet_U &)
static const List_Sonde & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture d'une liste sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'une liste sur un flot d'entree.
int est_egal_a (const List_Sonde &) const
Detailed Description
Definition at line 36 of file Sondes.h.
Constructor & Destructor Documentation
List_Sonde::List_Sonde ()
Definition at line 27 of file Sondes.cpp.
List_Sonde::~List_Sonde ()
Definition at line 27 of file Sondes.cpp.
List_Sonde::List_Sonde (const Sonde & t) [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
List_Sonde::List_Sonde (const List_Sonde & t) [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
Member Function Documentation
List_Sonde & List_Sonde::add (const List_Sonde & a_list) [inline]
Definition at line 36 of file Sondes.h.
Referenced by Sondes::lire_fichier(), and Sondes::readOn().
: public LIST(Sonde)
Sonde & List_Sonde::add (const Sonde & t) [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
Sonde & List_Sonde::add_if_not (const Sonde & t) [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
Sonde & List_Sonde::add_if_not (const char * const t) [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
int List_Sonde::contient (const Sonde & t) const [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
int List_Sonde::contient (const char * const ch) const [inline]
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
Returns:
int
Signification: 1 si la liste contient un Objet_U de Nom ch, 0 sinon
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
Objet_U * List_Sonde::cree_instance () [static]
Reimplemented from liste.
Reimplemented in Sondes.
Definition at line 27 of file Sondes.cpp.
const List_Sonde& List_Sonde::dernier () const [inline]
Renvoie le dernier element de la liste.
Returns:
const liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented from liste.
List_Sonde & List_Sonde::dernier () [inline]
Renvoie le dernier element de la liste.
Returns:
liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
int List_Sonde::duplique () const [virtual]
Reimplemented from liste.
Reimplemented in Sondes.
Definition at line 27 of file Sondes.cpp.
int List_Sonde::est_egal_a (const Objet_U & x) const [virtual]
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
Reimplemented from Objet_U.
Definition at line 27 of file Sondes.cpp.
int List_Sonde::est_egal_a (const List_Sonde &) const [inline, protected]
const Type_info * List_Sonde::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from liste.
Reimplemented in Sondes.
Definition at line 27 of file Sondes.cpp.
const Type_info * List_Sonde::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from liste.
Reimplemented in Sondes.
Definition at line 27 of file Sondes.cpp.
List_Sonde & List_Sonde::inserer (const List_Sonde & a_list) [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
Sonde & List_Sonde::inserer (const Sonde & t) [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
const Sonde & List_Sonde::operator() (const Nom & nom) const [inline]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
Sonde & List_Sonde::operator() (const Nom & nom) [inline]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
const Sonde & List_Sonde::operator() (int i) const [inline]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
Sonde & List_Sonde::operator() (int i) [inline]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
List_Sonde & List_Sonde::operator+= (const Sonde & t) [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
List_Sonde & List_Sonde::operator+= (const List_Sonde & a_list) [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
List_Sonde & List_Sonde::operator-= (const Sonde & t) [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
Sonde * List_Sonde::operator-> () [inline]
Retourne un pointeur sur l'Objet_U premier element de la liste.
Returns:
Objet_U*
Signification: pointeur sur l'Objet_U premier element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
List_Sonde & List_Sonde::operator= (const Sonde & t) [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
List_Sonde & List_Sonde::operator= (const List_Sonde & a_list) [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
Sonde & List_Sonde::operator[] (int i) [inline]
Operateur d'acces au ieme element de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
Sonde & List_Sonde::operator[] (const Nom & nom) [inline]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
const Sonde & List_Sonde::operator[] (const Nom & nom) const [inline]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
const Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
const Sonde & List_Sonde::operator[] (int i) const [inline]
Operateur d'acces au ieme element de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
Sortie & List_Sonde::printOn (Sortie & os) const [protected, virtual]
Ecriture d'une liste sur un flot de sortie.
Returns:
Sortie&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from liste.
Reimplemented in Sondes.
Definition at line 27 of file Sondes.cpp.
int List_Sonde::rang (const Sonde & t) const [inline]
Definition at line 36 of file Sondes.h.
Referenced by Sondes::get_from_cache().
: public LIST(Sonde)
Entree & List_Sonde::readOn (Entree & is) [protected, virtual]
Lecture d'une liste sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from liste.
Reimplemented in Sondes.
Definition at line 27 of file Sondes.cpp.
List_Sonde & List_Sonde::search (const Sonde & t) const [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
List_Sonde & List_Sonde::search (const char * const ch) const [inline]
Recherche d'un Objet_U de Nom ch dans la liste.
Returns:
liste&
Signification: L'element de la liste trouve
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
const List_Sonde & List_Sonde::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from liste.
Reimplemented in Sondes.
Definition at line 27 of file Sondes.cpp.
List_Sonde & List_Sonde::self_cast (Objet_U & r) [static]
Reimplemented from liste.
Reimplemented in Sondes.
Definition at line 27 of file Sondes.cpp.
const List_Sonde & List_Sonde::suivant () const [inline]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
const liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
List_Sonde & List_Sonde::suivant () [inline]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
void List_Sonde::suppr (const Sonde & t) [inline]
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
void List_Sonde::supprimer () [inline]
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
unsigned List_Sonde::taille_memoire () const [virtual]
Reimplemented from liste.
Reimplemented in Sondes.
Definition at line 27 of file Sondes.cpp.
const Sonde & List_Sonde::valeur () const [inline]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
const Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
Sonde & List_Sonde::valeur () [inline]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented from liste.
Definition at line 36 of file Sondes.h.
: public LIST(Sonde)
Member Data Documentation
const Type_info List_Sonde::info_obj [static]
Reimplemented from liste.
Reimplemented in Sondes.
Definition at line 36 of file Sondes.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Sondes.h
src/Kernel/Framework/Sondes.cpp