TRUST: Ch_front_Vortex Class Reference
Ch_front_Vortex Class Reference
classe Ch_fr_Vortex
Classe derivee de Champ_front_var qui represente les
champs aux frontieres calcules suivant la methode des vortex
nval
xi yi zi val_i
#include <Ch_front_Vortex.h>
Public Member Functions
Ch_front_Vortex ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
~Ch_front_Vortex () override
Champ_front_base & affecter_ (const Champ_front_base &ch) override
Renvoie l'objet upcaste en Champ_front_base&.
int my_rand ()
void sauvegarder_vortex ()
void reprendre_vortex ()
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
void deplacement_vortex (double, double, double, double, double, double &, double &)
void mettre_a_jour (double) override
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
Public Member Functions inherited from Champ_front_var_instationnaire
Champ_front_var_instationnaire ()
~Champ_front_var_instationnaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialise le temps courant et Gpoint.
DoubleTab & Gpoint ()
const DoubleTab & Gpoint () const
void Gpoint (double t1, double t2)
DoubleTab & valeurs_au_temps (double temps) override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
const DoubleTab & valeurs_au_temps (double temps) const override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
int avancer (double temps) override
Avance jusqu'au temps desire.
Sinon, sort en erreur.
int reculer (double temps) override
Recule jusqu'au temps desire.
Sinon, sort en erreur.
virtual double valeur_au_temps_et_au_point (double temps, int som, double x, double y, double z, int comp) const
virtual int valeur_au_temps_et_au_point_disponible () const
Public Member Functions inherited from Champ_front_var
Champ_front_var ()
~Champ_front_var () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Public Member Functions inherited from Champ_front_base
~Champ_front_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base ()
virtual void completer ()
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe une frontiere discretisee au champ.
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
virtual DoubleTab & valeurs_au_temps (double temps)=0
virtual const DoubleTab & valeurs_au_temps (double temps) const =0
const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee associee au champ.
(version const)
Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee associee au champ.
const Zone_dis_base & zone_dis () const
virtual Champ_front_base & affecter_ (const Champ_front_base &ch)=0
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
virtual void calculer_coeffs_echange (double temps)
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
virtual void valeurs_face (int, DoubleVect &) const
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
virtual void verifier (const Cond_lim_base &la_cl) const
double get_temps_defaut () const
void set_temps_defaut (double temps)
virtual void changer_temps_futur (double temps, int i)
virtual int avancer (double temps)
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe
en parametre.
virtual int reculer (double temps)
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe
en parametre.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Ch_front_Vortex & self_cast (Objet_U &)
static const Ch_front_Vortex & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var_instationnaire
static const Type_info * info ()
static Champ_front_var_instationnaire & self_cast (Objet_U &)
static const Champ_front_var_instationnaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var
static const Type_info * info ()
static Champ_front_var & self_cast (Objet_U &)
static const Champ_front_var & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_base
static const Type_info * info ()
static Champ_front_base & self_cast (Objet_U &)
static const Champ_front_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var_instationnaire
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime le champ sur flot de sortie.
Imprime la taille du champ et la valeur (constante) sur
la frontiere.
Entree & readOn (Entree &) override
Lit le champ a partir d'un flot d'entree.
Format:
Champ_front_Vortex nb_compo vrel_1 ... [vrel_i].
Protected Member Functions inherited from Champ_front_var_instationnaire
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int init
int first_rand
Ref_Domaine mon_domaine
Nom geom
double nu
double utau
double R
double Ox
double Oy
double Oz
double surf
int nb_vortex
double temps
double nx
double ny
double nz
composantes normales du repere associe a la frontiere
double t1x
double t1y
double t1z
composantes tangentielles : n.t1 = 0
double t2x
double t2y
double t2z
composantes tangentielles : t2 = n ^ t1 = 0
DoubleVect xvort
coordonnees x des vortex
DoubleVect yvort
coordonnees y des vortex
DoubleVect zvort
coordonnees z des vortex
DoubleVect tvort
durees de vie des vortex
DoubleVect svort
signes de la vorticite des vortex
ArrOfInt fvort
numero faces contenant le centre du vortex
DoubleVect gamma
intensite du vortex
DoubleVect sigma
longeur caracteristique du vortex
DoubleVect u
DoubleVect v
DoubleVect w
DoubleVect u_moy
DoubleVect dudy
DoubleVect k
DoubleVect eps
DoubleVect Wk
processus de Wiener
Protected Attributes inherited from Champ_front_var_instationnaire
DoubleTab Gpoint_
Taux d'accroissement du champ.
Protected Attributes inherited from Champ_front_base
double temps_defaut
Le temps pris par defaut quand le parametre n'est pas specifie. Ce sera en particulier celui utilise par les operateurs et les solveurs.
Ref_Frontiere_dis_base la_frontiere_dis
Roue_ptr les_valeurs
Les valeurs du champ.
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
classe Ch_fr_Vortex
Classe derivee de Champ_front_var qui represente les
champs aux frontieres calcules suivant la methode des vortex
nval
xi yi zi val_i
Definition at line 36 of file Ch_front_Vortex.h.
Constructor & Destructor Documentation
Ch_front_Vortex()
Ch_front_Vortex::Ch_front_Vortex ()
Definition at line 24 of file Ch_front_Vortex.cpp.
~Ch_front_Vortex()
Ch_front_Vortex::~Ch_front_Vortex () override
Definition at line 27 of file Ch_front_Vortex.cpp.
{
  sauvegarder_vortex();
}
References sauvegarder_vortex().
Member Function Documentation
affecter_()
Champ_front_base & Ch_front_Vortex::affecter_ (const Champ_front_base & ch) override virtual
Renvoie l'objet upcaste en Champ_front_base&.
Returns
Champ_front_base&
Signification: (*this) upcaste en Champ_front_base&
Contraintes:
Implements Champ_front_base.
Definition at line 109 of file Ch_front_Vortex.cpp.
{
  return *this;
}
cree_instance()
Objet_U * Ch_front_Vortex::cree_instance () static
Definition at line 24 of file Ch_front_Vortex.cpp.
deplacement_vortex()
void Ch_front_Vortex::deplacement_vortex (double dx, double dy, double dz, double asigma, double agamma, double & vv, double & ww)
Definition at line 537 of file Ch_front_Vortex.cpp.
{
  double norme2 = dx*dx + dy*dy + dz*dz ;
  if(norme2<(4.*asigma) && norme2>1.e-8)
    {
      double e1 = exp(-norme2/(2.*asigma*asigma));
      double f  = (1.-e1) * agamma * e1 / (2.* M_PI * norme2 );
      double dt1 = dx*t1x + dy*t1y + dz*t1z ;
      double dt2 = dx*t2x + dy*t2y + dz*t2z ;
      vv += dt2*f;
      ww -= dt1*f;
    }
}
References M_PI, t1x, t1y, t1z, t2x, t2y, and t2z.
Referenced by mettre_a_jour().
duplique()
int Ch_front_Vortex::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Ch_front_Vortex.cpp.
get_info()
const Type_info * Ch_front_Vortex::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 24 of file Ch_front_Vortex.cpp.
info()
const Type_info * Ch_front_Vortex::info () static
Definition at line 24 of file Ch_front_Vortex.cpp.
initialiser()
int Ch_front_Vortex::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
< normales orientees vers l'interieur du domaine
< distance a la paroi
< distance a la paroi
< -> gradient dudy discontinu a dplus = 11
< -> genere une discontinuite sur u' en cette position
< estimation du dt_min requis
< random identique a chaque nouveau tirage
Reimplemented from Champ_front_base.
Definition at line 191 of file Ch_front_Vortex.cpp.
{
  if (!Champ_front_var_instationnaire::initialiser(un_temps,inco))
    return 0;
  Domaine& domaine=mon_domaine.valeur();
  const Frontiere_dis_base& fr_dis=frontiere_dis();
  const Frontiere& frontiere=fr_dis.frontiere();
  const int nb_faces=frontiere.nb_faces();
  const int ndeb=frontiere.num_premiere_face();
  const int nfin=ndeb+nb_faces;
  const Faces& faces=frontiere.faces();
  int nbsf=faces.nb_som_faces();
  const Zone_VF& zvf = ref_cast(Zone_VF, zone_dis());
  const DoubleTab& xv=zvf.xv();
  double x,y,z;
  double dx,dy,dz;
  double norme;
  double  C_mu = 0.09;
  u.resize(nb_faces);
  v.resize(nb_faces);
  w.resize(nb_faces);
  u_moy.resize(nb_faces);
  dudy.resize(nb_faces);
  k.resize(nb_faces);
  eps.resize(nb_faces);
  Wk.resize(nb_faces);
  for(int face=ndeb; face<nfin; face++)
    {
      Wk(face) = 2.*drand48()-1.;
    }
//
// caracteristiques geometriques associees a la frontiere
//
  if(geom=="circle")
    {
      double x_xmin=1.e6;
      double x_xmax=-1.e6;
      double y_xmin=1.e6;
      double y_xmax=-1.e6;
      double z_xmin=1.e6;
      double z_xmax=-1.e6;
      double x_ymin=1.e6;
      double x_ymax=-1.e6;
      double y_ymin=1.e6;
      double y_ymax=-1.e6;
      double z_ymin=1.e6;
      double z_ymax=-1.e6;
      for(int face=ndeb; face<nfin; face++)
        {
          for(int kk=0; kk<nbsf; kk++)
            {
              x=domaine.coord(faces.sommet(face,kk),0);
              y=domaine.coord(faces.sommet(face,kk),1);
              z=domaine.coord(faces.sommet(face,kk),2);
              if(y<y_ymin)
                {
                  y_ymin=y;
                  x_ymin=x;
                  z_ymin=z;
                }
              if(y>y_ymax)
                {
                  y_ymax=y;
                  x_ymax=x;
                  z_ymax=z;
                }
              if(x<x_xmin)
                {
                  x_xmin=x;
                  y_xmin=y;
                  z_xmin=z;
                }
              if(x>x_xmax)
                {
                  x_xmax=x;
                  y_xmax=y;
                  z_xmax=z;
                }
            }
        }
      if(!est_egal(y_ymin,y_ymax))
        {
          dx=x_ymax-x_ymin;
          dy=y_ymax-y_ymin;
          dz=z_ymax-z_ymin;
          Ox=0.5*(x_ymax+x_ymin);
          Oy=0.5*(y_ymax+y_ymin);
          Oz=0.5*(z_ymax+z_ymin);
        }
      else
        {
          dx=x_xmax-x_xmin;
          dy=y_xmax-y_xmin;
          dz=z_xmax-z_xmin;
          Ox=0.5*(x_xmax+x_xmin);
          Oy=0.5*(y_xmax+y_xmin);
          Oz=0.5*(z_xmax+z_xmin);
        }
      R=0.5*sqrt(dx*dx+dy*dy+dz*dz);
      surf = M_PI*R*R;
      Cerr << " Coordinates associated with the boundary : " << Ox << " " << Oy << " " << Oz << finl;
      Cerr << " Radius computed : " << R << finl;
    }
  else if(geom=="channel")
    {
//
// le canal est suppose etre oriente suivant x,
// periodique suivant z (et x)
// la frontiere d'entree centree sur l'origine
// de hauteur et largeur: 2
// soit (x,y,z) : [0;0]x[-1;+1]x[-1;+1]
      R=1.;
      Ox=0.;
      Oy=0.;
      Oz=0.;
      surf = 4.;
    }
//
// repere local (t1;t2) associe a la frontiere (supposee plane)
//
  if (nb_faces==0)
    {
      nb_vortex=0;
    }
  else
    {
      nx=-zvf.face_normales(ndeb,0);  //!< normales orientees vers l'interieur du domaine
      ny=-zvf.face_normales(ndeb,1);
      nz=-zvf.face_normales(ndeb,2);
      norme = sqrt( nx*nx + ny*ny + nz*nz );
      nx/=norme;
      ny/=norme;
      nz/=norme;
      t1x = -ny;
      t1y =  nx;
      t1z =  0.;
      if( (est_egal(nx,0.)) && (est_egal(ny,0.)) )
        {
          t1x =  0.;
          t1y =  nz;
          t1z = -ny;
        }
      norme = sqrt( t1x*t1x + t1y*t1y + t1z*t1z );
      t1x/=norme;
      t1y/=norme;
      t1z/=norme;
      t2x =  ny*t1z - nz*t1y;
      t2y =  nz*t1x - nx*t1z;
      t2z =  nx*t1y - ny*t1x;
      /*
           Cerr << " t1x " << t1x << finl;
           Cerr << " t1y " << t1y << finl;
           Cerr << " t1z " << t1z << finl;
           Cerr << " t2x " << t2x << finl;
           Cerr << " t2y " << t2y << finl;
           Cerr << " t2z " << t2z << finl;
      */
//
// initialisation des champ de : vitesse - k - epsilon (analytique)
//
      double d,dplus,Reytau;
      double kappa = 0.41;
      double beta = 5.1;
      double tmp=15*15*15*15;
      for(int face=ndeb; face<nfin; face++)
        {
          x=xv(face,0);
          y=xv(face,1);
          z=xv(face,2);
          dx=x-Ox;
          dy=y-Oy;
          dz=z-Oz;
          if(geom=="circle")
            {
              d = R - sqrt(dx*dx+dy*dy+dz*dz) ;  //!< distance a la paroi
            }
          else
            {
              d = R - std::fabs(y) ;  //!< distance a la paroi
            }
          if(d<=0.)
            {
              Cerr << " the computation of a zero or negative distance is prejudicial for the rest of the calculation" << finl;
              Cerr << " Problem certainly related to the calculation of the size of domain or origin related to the bondary" << finl;
              exit();
            }
          dplus   = d*utau/nu;
          Reytau  = R*utau/nu;
          if(dplus<11.)
            {
              u_moy(face) = utau*dplus ;
            }
          else
            {
              u_moy(face) = utau*((1./kappa)*log(dplus)+beta) ;
            }
          if(dplus<11.)
            {
              dudy(face) = utau*utau/nu ;  //!< -> gradient dudy discontinu a dplus = 11
            }
          else
            {
              dudy(face) = utau/(kappa*d) ;  //!< -> genere une discontinuite sur u' en cette position
            }
          k(face)   = utau*utau * ( 0.07*dplus*dplus*exp(-dplus/8)+4.5*(1.-exp(-dplus/20.))/(1.+4.*dplus/Reytau) ) ;
          eps(face) = (utau*utau*utau*utau/nu) * (1./(0.41 *(pow(dplus*dplus*dplus*dplus+tmp,0.25)))) ;
        }
      u = u_moy;
//
// evaluation du nombre de vortex
//
      double sigma_moy = 0.;
      for(int face=ndeb; face<nfin; face++)
        {
          double sx=zvf.face_normales(face,0);
          double sy=zvf.face_normales(face,1);
          double sz=zvf.face_normales(face,2);
          sigma_moy += sqrt(sx*sx+sy*sy+sz*sz) * pow(k(face),1.5) / eps(face);
        }
      sigma_moy *= pow(C_mu,0.75);
      sigma_moy /= surf;
// On ne peut pas utiliser modf (voir Schema_Temps_base::limpr) car
// nb_vortex sert a dimensionner des tableaux !
      nb_vortex = (int) ( surf / (M_PI * sigma_moy *sigma_moy) );
    }
  Cerr << "nb_vortex " <<nb_vortex << finl;
// nb_vortex=1;
// nb_vortex=nb_faces;
  xvort.resize(nb_vortex);
  yvort.resize(nb_vortex);
  zvort.resize(nb_vortex);
  tvort.resize(nb_vortex);
  svort.resize(nb_vortex);
  fvort.resize_array(nb_vortex);
  gamma.resize(nb_vortex);
  sigma.resize(nb_vortex);
//
// Calcul du temps de duree de vie minimum des vortex
//
  double dt_vortex,dt_min=1.e6;
  for (int i=0; i<nb_faces; i++) //!< estimation du dt_min requis
    {
      dt_vortex=5.*C_mu*pow(k(i),3./2.)/(eps(i)*u_moy(i));
      if(dt_vortex<dt_min) dt_min=dt_vortex;
    }
  Cerr << " DT_MIN VORTEX " << dt_min << finl;
//
// initialisation des vortex par tirage aleatoire
//
  /*
           for (int i=0;i<nb_vortex;i++)  // random different a chaque nouveau tirage
           {
           int face = my_rand() % nb_faces;
           double rand1 = (my_rand() % 100)/100.;
           double rand2 = (my_rand() % 100)/100.;
           xvort(i)=xv(face,0);
           yvort(i)=xv(face,1);
           zvort(i)=xv(face,2);
           tvort(i)=rand1*5.*C_mu*pow(k(face),3./2.)/(eps(face)*u_moy(face));
           if (rand2<0.5) svort(i)=-1.;
           else svort(i)=1.;
           Cerr << " Vortex " << i << finl;
           Cerr << " Face " << face << " " << xvort(i) << " " <<yvort(i) << " " <<zvort(i) << finl;
           Cerr <<" " << tvort(i) << " " <<svort(i) << finl;
           Cerr << " " << finl;
           }
  */
  for (int i=0; i<nb_vortex; i++) //!< random identique a chaque nouveau tirage
    {
      int face = (int)(nb_faces*drand48());
      xvort(i)=xv(face,0);
      yvort(i)=xv(face,1);
      zvort(i)=xv(face,2);
      tvort(i)=drand48()*5.*C_mu*pow(k(face),3./2.)/(eps(face)*u_moy(face));
      if (drand48()<0.5) svort(i)=-1.;
      else svort(i)=1.;
      /*
             Cerr << " Vortex " << i << finl;
             Cerr << " Face " << face << " " << xvort(i) << " " <<yvort(i) << " " <<zvort(i) << finl;
             Cerr <<" " << tvort(i) << " " <<svort(i) << finl;
             Cerr << " " << finl;
      */
    }
  mettre_a_jour(un_temps);
  return 1;
}
References Cerr, Domaine::coord(), dudy, eps, est_egal(), Process::exit(), Zone_VF::face_normales(), Frontiere::faces(), finl, Frontiere_dis_base::frontiere(), Champ_front_base::frontiere_dis(), fvort, gamma, geom, Champ_front_var_instationnaire::initialiser(), k, M_PI, mettre_a_jour(), mon_domaine, Frontiere::nb_faces(), Faces::nb_som_faces(), nb_vortex, norme(), nu, Frontiere::num_premiere_face(), nx, ny, nz, Ox, Oy, Oz, R, ref_cast, TRUSTVect< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), sigma, Faces::sommet(), surf, svort, t1x, t1y, t1z, t2x, t2y, t2z, tvort, u, u_moy, utau, v, Ref_Domaine::valeur(), w, Wk, Zone_VF::xv(), xvort, yvort, Champ_front_base::zone_dis(), and zvort.
mettre_a_jour()
void Ch_front_Vortex::mettre_a_jour (double temps) override virtual
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
< il s'agit d'une reprise
< ATTENTION : Pour des raisons pratiques,
< les coordonnees des points sont exprimees
< en fonction de l'origine Ox,Oy,Oz de la frontiere
< vitesse induite par les vortex a la face suivant t1
< vitesse induite par les vortex a la face suivant t2
Reimplemented from Champ_front_base.
Definition at line 555 of file Ch_front_Vortex.cpp.
{
  const Frontiere_dis_base& fr_dis=frontiere_dis();
  const Frontiere& frontiere=fr_dis.frontiere();
  const int nb_faces=frontiere.nb_faces();
  const int ndeb=frontiere.num_premiere_face();
  const int nfin=ndeb+nb_faces;
  DoubleTab& les_val=valeurs();
  const Zone_VF& zvf = ref_cast(Zone_VF, zone_dis());
  const DoubleTab& xv=zvf.xv();
  double alpha=0;
  double dist,dist2;
  double x,yter,z;
  double xp,yp,zp;
  double xvort_mir,yvort_mir,zvort_mir;
  double xvort_per,yvort_per,zvort_per;
  double dx,dy,dz;
  double  C_mu = 0.09;
  if(init)
    {
      init=0;
      temps=tps;
      if(temps!=0.) //!< il s'agit d'une reprise
        reprendre_vortex();
    }
//
// caracteristiques des vortex (position-vorticite)
//
  if (nb_vortex!=0)
    alpha = 4.*sqrt(M_PI*surf/(3.*nb_vortex*(2.*log(3.)-3.*log(2.))));
  for (int i=0; i<nb_vortex; i++)
    {
      x=xvort(i);
      yter=yvort(i);
      z=zvort(i);
      dist=1.e6;
      int face=-1;
      for(int j=ndeb; j<nfin; j++)
        {
          dist2=(xv(j,0)-x)*(xv(j,0)-x)+(xv(j,1)-yter)*(xv(j,1)-yter)+(xv(j,2)-z)*(xv(j,2)-z);
          if(dist2<dist)
            {
              dist=dist2;
              face=j;
            }
        }
      gamma(i)     = alpha * sqrt(k(face)) * svort(i);
      sigma(i)     = pow(C_mu,0.75) * pow(k(face),1.5) / eps(face);
      fvort[i]     = face ;
    }
//
// calcul de la vitesse induite par les vortex en chacune des faces de la frontiere
//
  for(int face=ndeb; face<nfin; face++)
    {
      x=xv(face,0);
      yter=xv(face,1);
      z=xv(face,2);
      x -= Ox ;  //!< ATTENTION : Pour des raisons pratiques,
      yter -= Oy ;  //!< les coordonnees des points sont exprimees
      z -= Oz ;  //!< en fonction de l'origine Ox,Oy,Oz de la frontiere
      v(face) = 0.;  //!< vitesse induite par les vortex a la face suivant t1
      w(face) = 0.;  //!< vitesse induite par les vortex a la face suivant t2
      for (int i=0; i<nb_vortex; i++)
        {
          dx = (xvort(i)-Ox) - x;
          dy = (yvort(i)-Oy) - yter;
          dz = (zvort(i)-Oz) - z;
          deplacement_vortex(dx,dy,dz,sigma(i),gamma(i),v(face),w(face));
//
// traitement des conditions limites
//
          //***************************************
          // Parois : traitement des vortex miroirs
          //***************************************
          if(geom=="circle")
            {
              xp = x * R / (sqrt(x*x+yter*yter+z*z)) ;
              yp = yter * R / (sqrt(x*x+yter*yter+z*z)) ;
              zp = z * R / (sqrt(x*x+yter*yter+z*z)) ;
            }
          else //channel
            {
              xp = x;
              yp = R;
              if(yter<0) yp = -R;
              zp = z;
            }
          xvort_mir = 2. * xp - (xvort(i)-Ox);
          yvort_mir = 2. * yp - (yvort(i)-Oy);
          zvort_mir = 2. * zp - (zvort(i)-Oz);
          dx = xvort_mir - x;
          dy = yvort_mir - yter;
          dz = zvort_mir - z;
          deplacement_vortex(dx,dy,dz,sigma(i),gamma(i),v(face),w(face));
          //***************************************
          // Periodicite : canal plan uniquement
          //***************************************
          if(geom=="channel")
            {
              xvort_per = (xvort(i)-Ox);
              yvort_per = (yvort(i)-Oy);
              if( (zvort(i)-Oz) >0.) zvort_per = -2.*R + (zvort(i)-Oz) ;
              else                            zvort_per =  2.*R + (zvort(i)-Oz);
              dx = xvort_per - x;
              dy = yvort_per - yter;
              dz = zvort_per - z;
              deplacement_vortex(dx,dy,dz,sigma(i),gamma(i),v(face),w(face));
            }
        }//boucle sur vortex
      ////////////////////////////////////////////////////////////////////////////
      // calcul de la fluctuation de vitesse logitudinale par equation de Langevin
      ////////////////////////////////////////////////////////////////////////////
      //     double up = u(face) - u_moy(face);
      double up= u(face);
      if(tps==0.) up=0.;
      double vp;
      if(geom=="channel") vp = w(face);
      else //(geom=="circle")
        {
          double norme = sqrt(x*x+yter*yter+z*z);
          double costheta = ( x*t1x + yter*t1y + z*t1z ) / norme;
          double sintheta = ( x*t2x + yter*t2y + z*t2z ) / norme;
          vp = costheta*v(face) + sintheta*w(face) ;
        }
      ///// processus de Wiener : tirage aleatoire "gaussien" verifiant <dW>=0 et <dW^2>=1 /////////
      /////
      ///// http://www.taygeta.com/random/gaussian.html
      double x1,x2,ybis,Wkp1,dW;
      do
        {
          x1 = 2. * drand48() - 1. ;
          x2 = 2. * drand48() - 1. ;
          ybis = x1 * x1 + x2 * x2;
        }
      while ( ybis >= 1. );
      Wkp1     =  x1 * sqrt( (-1.0 * log( ybis ) ) / ybis );  // On travaille sur dW -> pour assurer <dW^2>=1, on doit modifier le coef
      dW       =  Wkp1 - Wk(face) ;                       // par rapport a la formulation proposee dans 'taygeta'
      Wk(face) =  Wkp1 ;
      /*
        double Wkp1,dW;
        Wkp1     =  2.*drand48()-1.;
        dW       = (Wkp1 - Wk(face))*sqrt(3./2.) ;
        Wk(face) =  Wkp1 ;
        double W,Wp1,dW;
        W     =  2.*drand48()-1.;
        Wp1   =  2.*drand48()-1.;
        dW    = (Wp1 - W)*sqrt(3./2.) ;
      */
      //////////////////////////////////
      double C0,C1,C2;
      C0=14./15.;
      C1=1.8;
      C2=0.6;
      double T=k(face)/eps(face);
      double dt = tps - temps;
      if(dt!=0.) // codage conforme a these Sergent + papier eDF (au coef 2/3 pres vis-a-vis de C2)
        {
          up += dt*( -(C1/(2.*T))*up  + (C2-1.)*dudy(face)*vp + sqrt(C0*eps(face))*dW/dt );
          //        up += dt*( -(C1/(2.*T))*up  + ((2./3.)*C2-1.)*dudy(face)*vp + sqrt(C0*eps(face))*dW/dt );
        }
      /*
             if(dt!=0.) // codage conforme a ce qui est code dans Saturne
             {
             up += dt*(-(1.-(2./3.)*C2)*dudy(face)*vp)  + 2.*sqrt((2./3.)*(C1-1.)*eps(face)*dt)*dW;
             up /= (1.+5.*C1*dt/T);
             }
      */
      //     u(face) = u_moy(face) + up;
      u(face) = up;
      les_val(face,0) = u(face)*nx + v(face)*t1x + w(face)*t2x ;
      les_val(face,1) = u(face)*ny + v(face)*t1y + w(face)*t2y ;
      les_val(face,2) = u(face)*nz + v(face)*t1z + w(face)*t2z ;
      /*
        les_val(face,0) =  gamma(face) ;
        les_val(face,1) =  sigma(face) ;
        les_val(face,2) =  fvort(face) ;
        les_val(face,0) =  k(face)  ;
        les_val(face,1) =  eps(face)  ;
        les_val(face,2) =  u_moy(face)  ;
      */
    }//boucle sur face
  //////////////////////////
  // deplacement des vortex
  //////////////////////////
  double dt = tps - temps;
  temps=tps;
  for (int i=0; i<nb_vortex; i++)
    {
      int face = fvort[i];
      x = xvort(i) + dt * ( v(face)*t1x + w(face)*t2x ); // Les deplacements des vortex ne s'operent
      yter = yvort(i) + dt * ( v(face)*t1y + w(face)*t2y ); // que dans le plan d'entree. D'ou les composantes
      z = zvort(i) + dt * ( v(face)*t1z + w(face)*t2z ); // u.n proscrites
      x -= Ox ;  // ATTENTION : Pour des raisons pratiques,
      yter -= Oy ;  // les coordonnees des points sont exprimees
      z -= Oz ;  // en fonction de l'origine Ox,Oy,Oz de la frontiere
      if( (geom=="circle") && ((x*x+yter*yter+z*z)>=(R*R)) ) //paroi
        {
          // paroi : On ne fait rien - on laisse le vortex a sa position
        }
      else if( (geom=="channel") && (std::fabs(yter)>R) ) //paroi
        {
          // paroi : On ne fait rien - on laisse le vortex a sa position
        }
      else if( (geom=="channel") && (z>R) ) //periodicite
        {
          xvort(i) = x + Ox;
          yvort(i) = yter + Oy;
          zvort(i) = -2.*R + z + Oz;
        }
      else if( (geom=="channel") && (z<-R) ) //periodicite
        {
          xvort(i) = x + Ox;
          yvort(i) = yter + Oy;
          zvort(i) = 2.*R - z + Oz;
        }
      else
        {
          xvort(i) = x + Ox;
          yvort(i) = yter + Oy;
          zvort(i) = z + Oz;
        }
    }
  ///////////////////////////////////////////////////////
  // fin de vie des vortex - generation de nouveau vortex
  ///////////////////////////////////////////////////////
  for (int i=0; i<nb_vortex; i++)
    {
      tvort(i) -= dt ;
      if(tvort(i)<=0.)// fin de vie du vortex
        {
          /*
            int face = my_rand() % nb_faces;            // random different a chaque nouveau tirage
            //       double rand1 = (my_rand() % 100)/100.;
            double rand2 = (my_rand() % 100)/100.;
            xvort(i)=xv(face,0);
            yvort(i)=xv(face,1);
            zvort(i)=xv(face,2);
            tvort(i)=5.*C_mu*pow(k(face),3./2.)/(eps(face)*u_moy(face));
            if (rand2<0.5) svort(i)=-1.;
            else svort(i)=1.;
          */
          int face = (int)(nb_faces*drand48());       // random identique a chaque execution
          xvort(i)=xv(face,0);
          yvort(i)=xv(face,1);
          zvort(i)=xv(face,2);
          tvort(i)=5.*C_mu*pow(k(face),3./2.)/(eps(face)*u_moy(face));
          if (drand48()<0.5) svort(i)=-1.;
          else svort(i)=1.;
          Cerr << " Time " << temps << " Vortex " << i << finl;
          Cerr << " Face " << face << " " << xvort(i) << " " <<yvort(i) << " " <<zvort(i) << finl;
          Cerr <<" " << tvort(i) << " " <<svort(i) << finl;
          Cerr << " " << finl;
        }
    }
}
References Cerr, deplacement_vortex(), dudy, eps, finl, Frontiere_dis_base::frontiere(), Champ_front_base::frontiere_dis(), fvort, gamma, geom, init, k, M_PI, Frontiere::nb_faces(), nb_vortex, norme(), Frontiere::num_premiere_face(), nx, ny, nz, Ox, Oy, Oz, R, ref_cast, reprendre_vortex(), sigma, surf, svort, t1x, t1y, t1z, t2x, t2y, t2z, temps, tvort, u, u_moy, v, Champ_front_base::valeurs(), w, Wk, Zone_VF::xv(), xvort, yvort, Champ_front_base::zone_dis(), and zvort.
Referenced by initialiser().
my_rand()
int Ch_front_Vortex::my_rand ()
Definition at line 115 of file Ch_front_Vortex.cpp.
{
  if (first_rand == 1)
    {
      srand(time (NULL));
      first_rand = 0;
    }
  return (rand ());
}
References first_rand.
printOn()
Sortie & Ch_front_Vortex::printOn (Sortie & os) const override protected virtual
Imprime le champ sur flot de sortie.
Imprime la taille du champ et la valeur (constante) sur
la frontiere.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 48 of file Ch_front_Vortex.cpp.
{
  const DoubleTab& tab=valeurs();
  os << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    os << tab(0,i);
  return os;
}
References TRUSTVect< _TYPE_ >::size(), and Champ_front_base::valeurs().
readOn()
Entree & Ch_front_Vortex::readOn (Entree & is) override protected virtual
Lit le champ a partir d'un flot d'entree.
Format:
Champ_front_Vortex nb_compo vrel_1 ... [vrel_i].
Returns
Entree& is
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 73 of file Ch_front_Vortex.cpp.
{
  if(dimension!=3)
    {
      Cerr << " Vortex Boundary condition requests 3D problem " << finl;
      exit();
    }
  fixer_nb_comp(dimension);
  init = 1;
  first_rand = 1;
  Nom nom;
  is >> nom >> geom >> nu >> utau;
  mon_domaine = ref_cast(Domaine, Interprete::objet(nom));
  return is;
}
References Cerr, Objet_U::dimension, Process::exit(), finl, first_rand, Field_base::fixer_nb_comp(), geom, init, mon_domaine, nu, Interprete::objet(), ref_cast, and utau.
reprendre_vortex()
void Ch_front_Vortex::reprendre_vortex ()
Definition at line 148 of file Ch_front_Vortex.cpp.
{
  Cerr << " Ch_front_Vortex::reprendre_vortex" << finl;
  Nom fichier = "vortex.sauv";
  if (nproc()>1) fichier=fichier.nom_me(me());
  if(la_frontiere_dis.non_nul())
    {
      Cerr << "Resumption of vortices in " << fichier << finl;
      EFichier fic(fichier);
      fic.setf(ios::scientific);
      if(fic.fail())
        {
          Cerr << "Unable to open file " << fichier << finl;
          exit();
        }
      double tps;
      int nbvortex;
      fic >> tps;
      fic >> nbvortex;
      if(!(std::fabs(temps-tps)/(std::fabs(tps)+1.e-24)<1.e-6))
        {
          Cerr << " time : " << tps << " in " << fichier << " does not match the time of resumed " << temps << finl;
          exit();
        }
      Cerr << " resumed " << nbvortex << " vortex at time " << temps << finl;
      for (int i=0; i<nbvortex; i++)
        {
          fic >> xvort(i) >> yvort(i) >> zvort(i) >> tvort(i);
          fic >> svort(i) >> fvort[i] >> gamma(i) >> sigma(i);
        }
      Cerr << " resumed made " << finl;
    }
}
References Cerr, Process::exit(), Entree_Fichier_base::fail(), finl, fvort, gamma, Champ_front_base::la_frontiere_dis, Process::me(), Nom::nom_me(), O_U_Ptr::non_nul(), Process::nproc(), Entree_Fichier_base::setf(), sigma, svort, temps, tvort, xvort, yvort, and zvort.
Referenced by mettre_a_jour().
sauvegarder_vortex()
void Ch_front_Vortex::sauvegarder_vortex ()
Definition at line 125 of file Ch_front_Vortex.cpp.
{
  Nom fichier = "vortex.sauv";
  if (nproc()>1) fichier=fichier.nom_me(me());
  if(la_frontiere_dis.non_nul())
    {
      Cerr << "Saving vortices in " << fichier << finl;
      SFichier fic(fichier);
      fic.setf(ios::scientific);
      int nbvortex =  xvort.size();
      fic << temps << finl;
      fic << nbvortex << finl;
      for (int i=0; i<nbvortex; i++)
        {
          fic << xvort(i) << " " << yvort(i) << " " << zvort(i) << " " << tvort(i) << " " ;
          fic << svort(i) << " " << fvort[i] << " " << gamma(i) << " " << sigma(i) << finl;
        }
    }
}
References Cerr, finl, fvort, gamma, Champ_front_base::la_frontiere_dis, Process::me(), Nom::nom_me(), O_U_Ptr::non_nul(), Process::nproc(), Sortie_Fichier_base::setf(), sigma, TRUSTVect< _TYPE_ >::size(), svort, temps, tvort, xvort, yvort, and zvort.
Referenced by ~Ch_front_Vortex().
self_cast() [1/2]
const Ch_front_Vortex & Ch_front_Vortex::self_cast (const Objet_U & r) static
Definition at line 24 of file Ch_front_Vortex.cpp.
self_cast() [2/2]
Ch_front_Vortex & Ch_front_Vortex::self_cast (Objet_U & r) static
Definition at line 24 of file Ch_front_Vortex.cpp.
taille_memoire()
unsigned Ch_front_Vortex::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Ch_front_Vortex.cpp.
Member Data Documentation
dudy
DoubleVect Ch_front_Vortex::dudy protected
Definition at line 76 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
eps
DoubleVect Ch_front_Vortex::eps protected
Definition at line 76 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
first_rand
int Ch_front_Vortex::first_rand protected
Definition at line 54 of file Ch_front_Vortex.h.
Referenced by my_rand(), and readOn().
fvort
ArrOfInt Ch_front_Vortex::fvort protected
numero faces contenant le centre du vortex
Definition at line 71 of file Ch_front_Vortex.h.
Referenced by initialiser(), mettre_a_jour(), reprendre_vortex(), and sauvegarder_vortex().
gamma
DoubleVect Ch_front_Vortex::gamma protected
intensite du vortex
Definition at line 72 of file Ch_front_Vortex.h.
Referenced by initialiser(), mettre_a_jour(), reprendre_vortex(), and sauvegarder_vortex().
geom
Nom Ch_front_Vortex::geom protected
Definition at line 56 of file Ch_front_Vortex.h.
Referenced by initialiser(), mettre_a_jour(), and readOn().
info_obj
const Type_info Ch_front_Vortex::info_obj static
Definition at line 38 of file Ch_front_Vortex.h.
init
int Ch_front_Vortex::init protected
Definition at line 53 of file Ch_front_Vortex.h.
Referenced by mettre_a_jour(), and readOn().
k
DoubleVect Ch_front_Vortex::k protected
Definition at line 76 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
mon_domaine
Ref_Domaine Ch_front_Vortex::mon_domaine protected
Definition at line 55 of file Ch_front_Vortex.h.
Referenced by initialiser(), and readOn().
nb_vortex
int Ch_front_Vortex::nb_vortex protected
Definition at line 59 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
nu
double Ch_front_Vortex::nu protected
Definition at line 57 of file Ch_front_Vortex.h.
Referenced by initialiser(), and readOn().
nx
double Ch_front_Vortex::nx protected
Definition at line 62 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
ny
double Ch_front_Vortex::ny protected
Definition at line 62 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
nz
double Ch_front_Vortex::nz protected
composantes normales du repere associe a la frontiere
Definition at line 62 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
Ox
double Ch_front_Vortex::Ox protected
Definition at line 58 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
Oy
double Ch_front_Vortex::Oy protected
Definition at line 58 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
Oz
double Ch_front_Vortex::Oz protected
Definition at line 58 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
R
double Ch_front_Vortex::R protected
Definition at line 58 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
sigma
DoubleVect Ch_front_Vortex::sigma protected
longeur caracteristique du vortex
Definition at line 73 of file Ch_front_Vortex.h.
Referenced by initialiser(), mettre_a_jour(), reprendre_vortex(), and sauvegarder_vortex().
surf
double Ch_front_Vortex::surf protected
Definition at line 58 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
svort
DoubleVect Ch_front_Vortex::svort protected
signes de la vorticite des vortex
Definition at line 70 of file Ch_front_Vortex.h.
Referenced by initialiser(), mettre_a_jour(), reprendre_vortex(), and sauvegarder_vortex().
t1x
double Ch_front_Vortex::t1x protected
Definition at line 63 of file Ch_front_Vortex.h.
Referenced by deplacement_vortex(), initialiser(), and mettre_a_jour().
t1y
double Ch_front_Vortex::t1y protected
Definition at line 63 of file Ch_front_Vortex.h.
Referenced by deplacement_vortex(), initialiser(), and mettre_a_jour().
t1z
double Ch_front_Vortex::t1z protected
composantes tangentielles : n.t1 = 0
Definition at line 63 of file Ch_front_Vortex.h.
Referenced by deplacement_vortex(), initialiser(), and mettre_a_jour().
t2x
double Ch_front_Vortex::t2x protected
Definition at line 64 of file Ch_front_Vortex.h.
Referenced by deplacement_vortex(), initialiser(), and mettre_a_jour().
t2y
double Ch_front_Vortex::t2y protected
Definition at line 64 of file Ch_front_Vortex.h.
Referenced by deplacement_vortex(), initialiser(), and mettre_a_jour().
t2z
double Ch_front_Vortex::t2z protected
composantes tangentielles : t2 = n ^ t1 = 0
Definition at line 64 of file Ch_front_Vortex.h.
Referenced by deplacement_vortex(), initialiser(), and mettre_a_jour().
temps
double Ch_front_Vortex::temps protected
Definition at line 60 of file Ch_front_Vortex.h.
Referenced by mettre_a_jour(), reprendre_vortex(), and sauvegarder_vortex().
tvort
DoubleVect Ch_front_Vortex::tvort protected
durees de vie des vortex
Definition at line 69 of file Ch_front_Vortex.h.
Referenced by initialiser(), mettre_a_jour(), reprendre_vortex(), and sauvegarder_vortex().
u
DoubleVect Ch_front_Vortex::u protected
Definition at line 76 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
u_moy
DoubleVect Ch_front_Vortex::u_moy protected
Definition at line 76 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
utau
double Ch_front_Vortex::utau protected
Definition at line 57 of file Ch_front_Vortex.h.
Referenced by initialiser(), and readOn().
v
DoubleVect Ch_front_Vortex::v protected
Definition at line 76 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
w
DoubleVect Ch_front_Vortex::w protected
Definition at line 76 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
Wk
DoubleVect Ch_front_Vortex::Wk protected
processus de Wiener
Definition at line 78 of file Ch_front_Vortex.h.
Referenced by initialiser(), and mettre_a_jour().
xvort
DoubleVect Ch_front_Vortex::xvort protected
coordonnees x des vortex
Definition at line 66 of file Ch_front_Vortex.h.
Referenced by initialiser(), mettre_a_jour(), reprendre_vortex(), and sauvegarder_vortex().
yvort
DoubleVect Ch_front_Vortex::yvort protected
coordonnees y des vortex
Definition at line 67 of file Ch_front_Vortex.h.
Referenced by initialiser(), mettre_a_jour(), reprendre_vortex(), and sauvegarder_vortex().
zvort
DoubleVect Ch_front_Vortex::zvort protected
coordonnees z des vortex
Definition at line 68 of file Ch_front_Vortex.h.
Referenced by initialiser(), mettre_a_jour(), reprendre_vortex(), and sauvegarder_vortex().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Ch_front_Vortex.h
src/Kernel/Champs/Ch_front_Vortex.cpp