TRUST: Eval_Conv_VDF_Elem< DERIVED_T > Class Template Reference
Eval_Conv_VDF_Elem< DERIVED_T > Class Template Reference
templates specializations ici ;)
#include <Eval_Conv_VDF_Elem.h>
Public Member Functions
template<typename BC , typename Type_Double >
void flux_face (const DoubleTab &, const int, const BC &, const int, Type_Double &) const
< Generic return
template<typename Type_Double >
void flux_face (const DoubleTab &, const int, const Dirichlet_entree_fluide &, const int, Type_Double &) const
template<typename Type_Double >
void flux_face (const DoubleTab &, const int, const Neumann_sortie_libre &, const int, Type_Double &) const
template<typename Type_Double >
void flux_face (const DoubleTab &, const int, const Periodique &, const int, Type_Double &) const
template<typename Type_Double >
void flux_face (const DoubleTab &, const int, const int, const int, const Echange_externe_impose &, const int, Type_Double &) const
template<typename Type_Double >
void flux_faces_interne (const DoubleTab &, const int, Type_Double &) const
template<typename BC , typename Type_Double >
void coeffs_face (const int, const int, const BC &, Type_Double &, Type_Double &) const
< Generic return
template<typename Type_Double >
void coeffs_face (const int, const int, const Dirichlet_entree_fluide &, Type_Double &, Type_Double &) const
template<typename Type_Double >
void coeffs_face (const int, const int, const Neumann_sortie_libre &, Type_Double &, Type_Double &) const
template<typename Type_Double >
void coeffs_face (const int, const int, const Periodique &, Type_Double &, Type_Double &) const
template<typename Type_Double >
void coeffs_face (const int, const int, const int, const int, const Echange_externe_impose &, Type_Double &, Type_Double &) const
template<typename Type_Double >
void coeffs_faces_interne (const int, Type_Double &, Type_Double &) const
template<typename BC , typename Type_Double >
void coeffs_face_bloc_vitesse (const DoubleTab &, const int, const BC &, const int, Type_Double &) const
< Generic return
template<typename Type_Double >
void coeffs_face_bloc_vitesse (const DoubleTab &, const int, const Dirichlet_entree_fluide &, const int, Type_Double &) const
template<typename Type_Double >
void coeffs_face_bloc_vitesse (const DoubleTab &, const int, const Neumann_sortie_libre &, const int, Type_Double &) const
template<typename Type_Double >
void coeffs_face_bloc_vitesse (const DoubleTab &, const int, const Periodique &, const int, Type_Double &) const
template<typename Type_Double >
void coeffs_face_bloc_vitesse (const DoubleTab &, const int, const int, const int, const Echange_externe_impose &, const int, Type_Double &) const
template<typename Type_Double >
void coeffs_faces_interne_bloc_vitesse (const DoubleTab &, const int, Type_Double &) const
template<typename BC , typename Type_Double >
void secmem_face (const int, const BC &, const int, Type_Double &) const
< Generic return
template<typename Type_Double >
void secmem_face (const int, const Dirichlet_entree_fluide &, const int, Type_Double &) const
template<typename Type_Double >
void secmem_face (const int, const Neumann_sortie_libre &, const int, Type_Double &) const
template<typename Type_Double >
void secmem_face (const int, const int, const int, const Echange_externe_impose &, const int, Type_Double &) const
template<typename Type_Double >
void secmem_faces_interne (const int, Type_Double &) const
Public Member Functions inherited from Eval_VDF_Elem
template<typename BC_TYPE , typename Type_Double >
void coeffs_face_bloc_vitesse (const DoubleTab &, int, const BC_TYPE &, int, Type_Double &) const
template<typename Type_Double >
void coeffs_face_bloc_vitesse (const DoubleTab &, int, int, int, const Echange_externe_impose &, int, Type_Double &) const
template<typename Type_Double >
void coeffs_faces_interne_bloc_vitesse (const DoubleTab &, int, Type_Double &) const
void associer_inconnue (const Champ_base &)
Static Public Attributes
static constexpr bool IS_AMONT = false
static constexpr bool IS_CENTRE = false
static constexpr bool IS_CENTRE4 = false
static constexpr bool IS_QUICK = false
static constexpr bool CALC_FLUX_FACES_ECH_EXT_IMP = false
static constexpr bool CALC_FLUX_FACES_ECH_GLOB_IMP = false
static constexpr bool CALC_FLUX_FACES_PAR = false
static constexpr bool CALC_FLUX_FACES_PAR_FIXE = false
static constexpr bool CALC_FLUX_FACES_SORTIE_LIB = true
Static Public Attributes inherited from Eval_VDF_Elem
static constexpr bool CALC_FLUX_FACES_ECH_EXT_IMP = true
static constexpr bool CALC_FLUX_FACES_ECH_GLOB_IMP = true
static constexpr bool CALC_FLUX_FACES_ENTREE_FL = true
static constexpr bool CALC_FLUX_FACES_PAR = true
static constexpr bool CALC_FLUX_FACES_PAR_ADIAB = false
static constexpr bool CALC_FLUX_FACES_PAR_DEFIL = false
static constexpr bool CALC_FLUX_FACES_PAR_FIXE = true
static constexpr bool CALC_FLUX_FACES_SORTIE_LIB = false
static constexpr bool CALC_FLUX_FACES_SYMM = false
static constexpr bool CALC_FLUX_FACES_PERIO = true
Private Member Functions
template<typename Type_Double >
void coeffs_face_common (const int, Type_Double &, Type_Double &) const
template<typename Type_Double >
void coeffs_face_bloc_vitesse_common (const DoubleTab &, const int, Type_Double &) const
int elem_ (const int i, const int j) const
int amont_amont_ (const int face, const int i) const
double dt_vitesse (const int face) const
double surface_porosite (const int face) const
template<typename Type_Double >
void quick_fram_ (const double psc, const int num0, const int num1, const int num0_0, const int num1_1, const int face, const DoubleTab &transporte, Type_Double &flux) const
template<typename Type_Double >
void qcentre_ (const double psc, const int num0, const int num1, const int num0_0, const int num1_1, const int face, const DoubleTab &transporte, Type_Double &flux) const
Additional Inherited Members
Protected Attributes inherited from Eval_VDF_Elem
Ref_Champ_base inconnue
Detailed Description
template<typename DERIVED_T>
class Eval_Conv_VDF_Elem< DERIVED_T >
templates specializations ici ;)
Definition at line 23 of file Eval_Conv_VDF_Elem.h.
Member Function Documentation
amont_amont_()
template<typename DERIVED_T > int Eval_Conv_VDF_Elem< DERIVED_T >::amont_amont_ (const int face, const int i) const inline private
Definition at line 89 of file Eval_Conv_VDF_Elem.h.
{ return static_cast<const DERIVED_T *>(this)->amont_amont(face,i); }
coeffs_face() [1/5]
template<typename DERIVED_T > template<typename BC , typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_face (const int , const int , const BC & , Type_Double & , Type_Double &) const inline
< Generic return
Definition at line 50 of file Eval_Conv_VDF_Elem.h.
{ /* Do nothing */ }
coeffs_face() [2/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_face (const int face, const int , const Dirichlet_entree_fluide & la_cl, Type_Double & aii, Type_Double & ajj) const inline
Definition at line 147 of file Eval_Conv_VDF_Elem.tpp.
{
  coeffs_face_common(face,aii,ajj);
}
coeffs_face() [3/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_face (const int , const int , const int , const int , const Echange_externe_impose & , Type_Double & , Type_Double &) const inline
Definition at line 56 of file Eval_Conv_VDF_Elem.h.
{ /* Do nothing */ }
coeffs_face() [4/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_face (const int face, const int , const Neumann_sortie_libre & la_cl, Type_Double & aii, Type_Double & ajj) const inline
Definition at line 153 of file Eval_Conv_VDF_Elem.tpp.
{
  coeffs_face_common(face,aii,ajj);
}
coeffs_face() [5/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_face (const int face, const int , const Periodique & la_cl, Type_Double & aii, Type_Double & ajj) const inline
< on applique le schema centre 2 ou 4
Definition at line 159 of file Eval_Conv_VDF_Elem.tpp.
{
  assert (aii.size_array() == ajj.size_array());
  const int ncomp = aii.size_array();
  const double psc = dt_vitesse(face)*surface_porosite(face);
  if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_CENTRE4)
    {
      Type_Double flux(ncomp);
      const int i = elem_(face,0), j = elem_(face,1), i_0 = amont_amont_(face,0), j_1 = amont_amont_(face,1);
      qcentre_<Type_Double>(psc,i,j,i_0,j_1,face,inconnue->valeurs(),flux); //!< on applique le schema centre 2 ou 4
      if (psc > 0)
        for (int k = 0; k < ncomp; k++) aii[k] = -flux[k];
      else for (int k = 0; k < ncomp; k++) ajj[k] = -flux[k];
    }
  else
    for (int k = 0; k < ncomp; k++)
      {
        aii[k] = (psc > 0) ? psc : 0.;
        ajj[k] = (psc > 0) ? 0. : -psc;
      }
}
coeffs_face_bloc_vitesse() [1/5]
template<typename DERIVED_T > template<typename BC , typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_face_bloc_vitesse (const DoubleTab & , const int , const BC & , const int , Type_Double &) const inline
< Generic return
Definition at line 61 of file Eval_Conv_VDF_Elem.h.
{ /* Do nothing */ }
coeffs_face_bloc_vitesse() [2/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_face_bloc_vitesse (const DoubleTab & inco, const int face, const Dirichlet_entree_fluide & la_cl, const int num1, Type_Double & flux) const inline
< j != -1
Definition at line 214 of file Eval_Conv_VDF_Elem.tpp.
{
  if (DERIVED_T::IS_CENTRE4) return ;
  const int i = elem_(face,0), j = elem_(face,1), ncomp = flux.size_array();
  double psc = surface_porosite(face), val_imp = la_cl.val_imp(face-num1);
  if (i != -1)
    for (int k = 0; k < ncomp; k++) flux[k] = (dt_vitesse(face) > 0) ? psc*inco(i,k) : psc*val_imp;
  else for (int k = 0; k < ncomp; k++) flux[k] = (dt_vitesse(face)>0) ? psc*val_imp : psc*inco(j,k); //!< j != -1
}
References Dirichlet::val_imp().
coeffs_face_bloc_vitesse() [3/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_face_bloc_vitesse (const DoubleTab & , const int , const int , const int , const Echange_externe_impose & , const int , Type_Double &) const inline
Definition at line 67 of file Eval_Conv_VDF_Elem.h.
{ /* Do nothing */ }
coeffs_face_bloc_vitesse() [4/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_face_bloc_vitesse (const DoubleTab & inco, const int face, const Neumann_sortie_libre & la_cl, const int num1, Type_Double & flux) const inline
< j != -1
Definition at line 227 of file Eval_Conv_VDF_Elem.tpp.
{
  if (DERIVED_T::IS_CENTRE4) return;
  const int i = elem_(face,0), j = elem_(face,1), ncomp = flux.size_array();
  const double psc = surface_porosite(face), val_ext = la_cl.val_ext(face-num1);
  if (i != -1)
    for (int k = 0; k < ncomp; k++) flux[k] = (dt_vitesse(face) > 0) ? psc*inco(i,k) : psc*val_ext;
  else for (int k = 0; k < ncomp; k++) flux[k] = (dt_vitesse(face) > 0) ?  psc*val_ext : psc*inco(j,k); //!< j != -1
}
References Neumann_sortie_libre::val_ext().
coeffs_face_bloc_vitesse() [5/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_face_bloc_vitesse (const DoubleTab & inco, const int face, const Periodique & la_cl, const int , Type_Double & flux) const inline
Definition at line 256 of file Eval_Conv_VDF_Elem.tpp.
{
  coeffs_face_bloc_vitesse_common(inco,face,flux);
}
coeffs_face_bloc_vitesse_common()
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_face_bloc_vitesse_common (const DoubleTab & inco, const int face, Type_Double & flux) const inline private
Definition at line 241 of file Eval_Conv_VDF_Elem.tpp.
{
  if (DERIVED_T::IS_CENTRE4) return;
  const int i = elem_(face,0), j = elem_(face,1), ncomp = flux.size_array();
  const double psc = surface_porosite(face);
  if (DERIVED_T::IS_CENTRE)
    {
      const int i_0 = amont_amont_(face,0), j_1 = amont_amont_(face,1);
      qcentre_<Type_Double>(psc,i,j,i_0,j_1,face,inco,flux);
    }
  else for (int k = 0; k < ncomp; k++) flux[k] = (dt_vitesse(face) > 0) ? psc*inco(i,k) : psc*inco(j,k);
}
coeffs_face_common()
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_face_common (const int face, Type_Double & aii, Type_Double & ajj) const inline private
< TODO : FIXME : Yannick help :/
< j != -1
Definition at line 111 of file Eval_Conv_VDF_Elem.tpp.
{
  assert (aii.size_array() == ajj.size_array());
  const int i = elem_(face,0), ncomp = aii.size_array();
  const double psc = dt_vitesse(face)*surface_porosite(face);
  if (i != -1)
    {
      if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_CENTRE4)
        {
          if (psc > 0)
            for (int k = 0; k < ncomp; k++) aii[k] = -psc; //!< TODO : FIXME : Yannick help :/
        }
      else
        for (int k = 0; k < ncomp; k++)
          {
            aii[k] = (psc > 0) ? psc : 0.;
            ajj[k] = 0.;
          }
    }
  else //!< j != -1
    {
      if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_CENTRE4)
        {
          if (psc < 0)
            for (int k = 0; k < ncomp; k++) ajj[k] = -psc;
        }
      else
        for (int k = 0; k < ncomp; k++)
          {
            ajj[k] = (psc < 0) ? -psc : 0.;
            aii[k] = 0.;
          }
    }
}
coeffs_faces_interne()
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_faces_interne (const int face, Type_Double & aii, Type_Double & ajj) const inline
< TODO : FIXME : Yannick help :/ pourquoi pas pour centre2 egalement ?
< on applique le schema centre 2 ou 4
Definition at line 182 of file Eval_Conv_VDF_Elem.tpp.
{
  assert (aii.size_array() == ajj.size_array());
  const int ncomp = aii.size_array();
  const double psc = dt_vitesse(face)*surface_porosite(face);
  if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_CENTRE4)
    {
      const int i = elem_(face,0), j = elem_(face,1), i_0 = amont_amont_(face,0), j_1 = amont_amont_(face,1);
      if ( ((i_0 == -1) || (j_1 == -1)) &&  DERIVED_T::IS_CENTRE4) //!< TODO : FIXME : Yannick help :/ pourquoi pas pour centre2 egalement ?
        {
          if (psc > 0)
            for (int k = 0; k < ncomp; k++) aii[k] = -psc;
          else for (int k = 0; k < ncomp; k++) ajj[k] = -psc;
        }
      else
        {
          Type_Double flux(ncomp);
          qcentre_<Type_Double>(psc,i,j,i_0,j_1,face,inconnue->valeurs(),flux); //!< on applique le schema centre 2 ou 4
          if (psc > 0)
            for (int k = 0; k < ncomp; k++) aii[k] = -flux[k];
          else for (int k = 0; k < ncomp; k++) ajj[k] = -flux[k];
        }
    }
  else
    for (int k = 0; k < ncomp; k++)
      {
        aii[k] = (psc > 0) ? psc : 0.;
        ajj[k] = (psc > 0) ? 0. : -psc;
      }
}
coeffs_faces_interne_bloc_vitesse()
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_faces_interne_bloc_vitesse (const DoubleTab & inco, const int face, Type_Double & flux) const inline
Definition at line 262 of file Eval_Conv_VDF_Elem.tpp.
{
  coeffs_face_bloc_vitesse_common(inco,face,flux);
}
dt_vitesse()
template<typename DERIVED_T > double Eval_Conv_VDF_Elem< DERIVED_T >::dt_vitesse (const int face) const inline private
Definition at line 90 of file Eval_Conv_VDF_Elem.h.
{ return static_cast<const DERIVED_T *>(this)->get_dt_vitesse(face); }
elem_()
template<typename DERIVED_T > int Eval_Conv_VDF_Elem< DERIVED_T >::elem_ (const int i, const int j) const inline private
Definition at line 88 of file Eval_Conv_VDF_Elem.h.
{ return static_cast<const DERIVED_T *>(this)->get_elem(i,j); }
flux_face() [1/5]
template<typename DERIVED_T > template<typename BC , typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & , const int , const BC & , const int , Type_Double &) const inline
< Generic return
Definition at line 36 of file Eval_Conv_VDF_Elem.h.
{ /* Do nothing */ }
flux_face() [2/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & inco, const int face, const Dirichlet_entree_fluide & la_cl, const int num1, Type_Double & flux) const inline
Definition at line 24 of file Eval_Conv_VDF_Elem.tpp.
{
  const int i = elem_(face,0), j = elem_(face,1), ncomp = flux.size_array();
  const double psc = dt_vitesse(face)*surface_porosite(face);
  if (i != -1)
    for (int k = 0; k < ncomp; k++) flux[k] = (psc > 0) ? -psc*inco(i,k) : -psc*la_cl.val_imp(face-num1,k);
  else for (int k = 0; k < ncomp; k++) flux[k] = (psc > 0) ? -psc*la_cl.val_imp(face-num1,k) : -psc*inco(j,k); /* j != -1 */
}
References Dirichlet::val_imp().
flux_face() [3/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & , const int , const int , const int , const Echange_externe_impose & , const int , Type_Double &) const inline
Definition at line 42 of file Eval_Conv_VDF_Elem.h.
{ /* Do nothing */ }
flux_face() [4/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & inco, const int face, const Neumann_sortie_libre & la_cl, const int num1, Type_Double & flux) const inline
Definition at line 34 of file Eval_Conv_VDF_Elem.tpp.
{
  const int i = elem_(face,0), j = elem_(face,1), ncomp = flux.size_array();
  const double psc = dt_vitesse(face)*surface_porosite(face);
  if (i != -1)
    for (int k = 0; k < ncomp; k++) flux[k] = (psc > 0) ? -psc*inco(i,k) : -psc*la_cl.val_ext(face-num1,k);
  else for (int k = 0; k < ncomp; k++) flux[k] = (psc > 0) ? -psc*la_cl.val_ext(face-num1,k) : -psc*inco(j,k); /* j != -1 */
}
flux_face() [5/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::flux_face (const DoubleTab & inco, const int face, const Periodique & la_cl, const int num1, Type_Double & flux) const inline
< on applique le schema centre 2 ou 4
< on applique le schema Quick
Definition at line 44 of file Eval_Conv_VDF_Elem.tpp.
{
  const int i = elem_(face,0), j = elem_(face,1), ncomp = flux.size_array();
  const double psc = dt_vitesse(face)*surface_porosite(face);
  if (!DERIVED_T::IS_AMONT)
    {
      const int i_0 = amont_amont_(face,0),j_1 = amont_amont_(face,1);
      if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_CENTRE4) qcentre_<Type_Double>(psc,i,j,i_0,j_1,face,inco,flux); //!< on applique le schema centre 2 ou 4
      else quick_fram_(psc,i,j,i_0,j_1,face,inco,flux); //!< on applique le schema Quick
      for (int k = 0; k < ncomp; k++) flux[k] *= -1;
    }
  else for (int k = 0; k < ncomp; k++) flux[k] = (psc > 0) ?  -psc*inco(i,k) : -psc*inco(j,k); /* AMONT */
}
flux_faces_interne()
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::flux_faces_interne (const DoubleTab & inco, const int face, Type_Double & flux) const inline
< on applique le schema centre2
< on applique le schema centre4
< on applique le schema Quick
Definition at line 62 of file Eval_Conv_VDF_Elem.tpp.
{
  const int i = elem_(face,0), j = elem_(face,1), ncomp = flux.size_array();
  const double psc = dt_vitesse(face)*surface_porosite(face);
  if (!DERIVED_T::IS_AMONT)
    {
      const int i_0 = amont_amont_(face,0), j_1 = amont_amont_(face,1);
      if (DERIVED_T::IS_CENTRE)
        {
          qcentre_<Type_Double>(psc,i,j,i_0,j_1,face,inco,flux);
          for (int k=0; k<ncomp; k++) flux[k] *= -1;
        }
      else if (DERIVED_T::IS_CENTRE4)
        {
          if ( (i_0 == -1) || (j_1 == -1) )
            for (int k=0; k<ncomp; k++) flux[k] = -psc*(inco(i,k)+inco(j,k))/2.; //!< on applique le schema centre2
          else //!< on applique le schema centre4
            {
              qcentre_<Type_Double>(psc,i,j,i_0,j_1,face,inco,flux);
              for (int k=0; k<ncomp; k++) flux[k] *= -1;
            }
        }
      else
        {
          /* *****************************************************************************************************************************************************
           * Alexandre C. 19/02/03 : We do not use the first order upwind scheme as it was done before because in LES computations all turbulence is damped
           * and we can not recover a proper behavior of physical turbulent characteristics, especially when using wall-functions.
           * Therefore we use the 2nd order centered scheme.
           * *****************************************************************************************************************************************************
           * Pierre L. 14/10/04: Correction car le centre explose sur le cas VALIDA On revient au quick en essayant d'ameliorer: on prend le quick si psc est
           * encore favorable pour avoir les 3 points necessaires au calcul du quick. Cela est deja ce qui est fait pour le quick-sharp de l'evaluateur aux faces.
           * *****************************************************************************************************************************************************/
          if ( (i_0 == -1 && psc >= 0 ) || (j_1 == -1 && psc <= 0 ) )
            for (int k=0; k<ncomp; k++) flux[k] = (psc > 0) ? -psc*inco(i,k) : -psc*inco(j,k);
          else //!< on applique le schema Quick
            {
              quick_fram_(psc,i,j,i_0,j_1,face,inco,flux);
              for (int k=0; k<ncomp; k++) flux[k] *= -1;
            }
        }
    }
  else for(int k=0; k<ncomp; k++) flux[k] = (psc > 0) ?  -psc*inco(i,k) : -psc*inco(j,k); /* AMONT */
}
qcentre_()
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::qcentre_ (const double psc, const int num0, const int num1, const int num0_0, const int num1_1, const int face, const DoubleTab & transporte, Type_Double & flux) const inline private
Definition at line 96 of file Eval_Conv_VDF_Elem.h.
  { static_cast<const DERIVED_T *>(this)->template qcentre<Type_Double>(psc,num0,num1,num0_0,num1_1,face,transporte,flux); }
quick_fram_()
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::quick_fram_ (const double psc, const int num0, const int num1, const int num0_0, const int num1_1, const int face, const DoubleTab & transporte, Type_Double & flux) const inline private
Definition at line 93 of file Eval_Conv_VDF_Elem.h.
  { static_cast<const DERIVED_T *>(this)->template quick_fram<Type_Double>(psc, num0, num1, num0_0, num1_1, face, transporte, flux); }
secmem_face() [1/4]
template<typename DERIVED_T > template<typename BC , typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::secmem_face (const int , const BC & , const int , Type_Double &) const inline
< Generic return
Definition at line 75 of file Eval_Conv_VDF_Elem.h.
{ /* Do nothing */ }
secmem_face() [2/4]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::secmem_face (const int face, const Dirichlet_entree_fluide & la_cl, const int num1, Type_Double & flux) const inline
< TODO : FIXME : Yannick help :/ c'est quoi ca ? on a jamais fait ca pour le scalaire ...
Definition at line 272 of file Eval_Conv_VDF_Elem.tpp.
{
  const int i = elem_(face,0), ncomp = flux.size_array();
  const double psc = dt_vitesse(face)*surface_porosite(face);
  if (i != -1)
    {
      if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_CENTRE4) //!< TODO : FIXME : Yannick help :/ c'est quoi ca ? on a jamais fait ca pour le scalaire ...
        {
          if (psc < 0)
            for (int k = 0; k < ncomp; k++) flux[k] = -psc*la_cl.val_imp(face-num1,k);
        }
      else for (int k = 0; k < ncomp; k++) flux[k] = (psc < 0) ? -psc*la_cl.val_imp(face-num1,k) : 0.;
    }
  else
    {
      if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_CENTRE4)
        {
          if (psc > 0)
            for (int k = 0; k < ncomp; k++) flux[k] = -psc*la_cl.val_imp(face-num1,k);
        }
      else for (int k = 0; k < ncomp; k++) flux[k] = (psc > 0) ? -psc*la_cl.val_imp(face-num1,k) : 0.;
    }
}
References Dirichlet::val_imp().
secmem_face() [3/4]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::secmem_face (const int , const int , const int , const Echange_externe_impose & , const int , Type_Double &) const inline
Definition at line 80 of file Eval_Conv_VDF_Elem.h.
{ /* Do nothing */ }
secmem_face() [4/4]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::secmem_face (const int face, const Neumann_sortie_libre & la_cl, const int num1, Type_Double & flux) const inline
< TODO : FIXME : Yannick help :/ c'est quoi ca ? on a jamais fait ca pour le scalaire ...
Definition at line 297 of file Eval_Conv_VDF_Elem.tpp.
{
  const int i = elem_(face,0), ncomp = flux.size_array();
  const double psc = dt_vitesse(face)*surface_porosite(face);
  if (i != -1)
    {
      if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_CENTRE4) //!< TODO : FIXME : Yannick help :/ c'est quoi ca ? on a jamais fait ca pour le scalaire ...
        {
          if (psc < 0)
            for (int k = 0; k < ncomp; k++) flux[k] = -psc*la_cl.val_ext(face-num1,k);
        }
      else for (int k = 0; k < ncomp; k++) flux[k] = (psc < 0) ? -psc*la_cl.val_ext(face-num1,k) : 0.;
    }
  else
    {
      if (DERIVED_T::IS_CENTRE || DERIVED_T::IS_CENTRE4)
        {
          if (psc > 0)
            for (int k = 0; k < ncomp; k++) flux[k] = -psc*la_cl.val_ext(face-num1,k);
        }
      else for (int k = 0; k < ncomp; k++) flux[k] = (psc > 0) ? -psc*la_cl.val_ext(face-num1,k) : 0.;
    }
}
References Neumann_sortie_libre::val_ext().
secmem_faces_interne()
template<typename DERIVED_T > template<typename Type_Double > void Eval_Conv_VDF_Elem< DERIVED_T >::secmem_faces_interne (const int , Type_Double &) const inline
Definition at line 81 of file Eval_Conv_VDF_Elem.h.
{ /* Do nothing */ }
surface_porosite()
template<typename DERIVED_T > double Eval_Conv_VDF_Elem< DERIVED_T >::surface_porosite (const int face) const inline private
Definition at line 91 of file Eval_Conv_VDF_Elem.h.
{ return static_cast<const DERIVED_T *>(this)->get_surface_porosite(face); }
Member Data Documentation
CALC_FLUX_FACES_ECH_EXT_IMP
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Elem< DERIVED_T >::CALC_FLUX_FACES_ECH_EXT_IMP = false static constexpr
Definition at line 28 of file Eval_Conv_VDF_Elem.h.
CALC_FLUX_FACES_ECH_GLOB_IMP
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Elem< DERIVED_T >::CALC_FLUX_FACES_ECH_GLOB_IMP = false static
Definition at line 28 of file Eval_Conv_VDF_Elem.h.
CALC_FLUX_FACES_PAR
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Elem< DERIVED_T >::CALC_FLUX_FACES_PAR = false static
Definition at line 28 of file Eval_Conv_VDF_Elem.h.
CALC_FLUX_FACES_PAR_FIXE
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Elem< DERIVED_T >::CALC_FLUX_FACES_PAR_FIXE = false static
Definition at line 29 of file Eval_Conv_VDF_Elem.h.
CALC_FLUX_FACES_SORTIE_LIB
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Elem< DERIVED_T >::CALC_FLUX_FACES_SORTIE_LIB = true static
Definition at line 29 of file Eval_Conv_VDF_Elem.h.
IS_AMONT
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Elem< DERIVED_T >::IS_AMONT = false static constexpr
Definition at line 26 of file Eval_Conv_VDF_Elem.h.
IS_CENTRE
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Elem< DERIVED_T >::IS_CENTRE = false static
Definition at line 26 of file Eval_Conv_VDF_Elem.h.
IS_CENTRE4
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Elem< DERIVED_T >::IS_CENTRE4 = false static
Definition at line 26 of file Eval_Conv_VDF_Elem.h.
IS_QUICK
template<typename DERIVED_T > constexpr bool Eval_Conv_VDF_Elem< DERIVED_T >::IS_QUICK = false static
Definition at line 26 of file Eval_Conv_VDF_Elem.h.
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Eval_Conv/Eval_Conv_VDF_Elem.h
src/VDF/Operateurs/Eval_Conv/Eval_Conv_VDF_Elem.tpp