TRUST: vect_impl Class Reference
vect_impl Class Reference
#include <vect_impl.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
vect_impl ()
int size () const
void build_vect_impl (int)
const Objet_U & operator[] (int) const
Objet_U & operator[] (int)
vect_impl (const vect_impl &)
~vect_impl () override
vect_impl & operator= (const vect_impl &)
void dimensionner (int)
void dimensionner_force (int)
void reset ()
vect_impl & add (const Objet_U &)
vect_impl & add (const vect_impl &)
Entree & lit (Entree &)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static vect_impl & self_cast (Objet_U &)
static const vect_impl & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual Objet_U * cree_une_instance () const
methhode surcharge par les classes filles pour fournir la bonne
instance aux constructeurs au readOn....
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int sz
DerObjU * data
Detailed Description
Definition at line 23 of file vect_impl.h.
Constructor & Destructor Documentation
vect_impl() [1/2]
vect_impl::vect_impl ()
Definition at line 62 of file vect_impl.cpp.
: sz(0), data(0) {}
vect_impl() [2/2]
vect_impl::vect_impl (const vect_impl & avect_impl)
Definition at line 81 of file vect_impl.cpp.
  : Objet_U(avect_impl),sz(avect_impl.sz), data(new DerObjU[avect_impl.sz])
{
  if(!data)
    {
      Cerr << "Allocation is not possible : " << finl;
      exit();
    }
  int i=sz;
  if(i==0)
    {
      delete[] data;
      data=0;
    }
  else while(i--)
      {
        (data[i])=(avect_impl[i]);
      }
  assert(sz>=0);
  if(sz) assert(data!=0);
}
References Cerr, data, Process::exit(), finl, and sz.
~vect_impl()
vect_impl::~vect_impl () override
Definition at line 103 of file vect_impl.cpp.
{
  reset();
  assert (data==0) ;
}
References data, and reset().
Member Function Documentation
add() [1/2]
vect_impl & vect_impl::add (const Objet_U & data_to_add)
Definition at line 198 of file vect_impl.cpp.
{
  DerObjU* tempo;
  int new_size=sz+1;
  tempo = new DerObjU[new_size];
  for(int i=0; i<sz; i++)
    (tempo[i]).deplace(data[i]);
  if (data) delete [] data;
  data=tempo;
  sz=new_size;
  data[sz-1]= data_to_add;
  assert(sz>=0);
  if(sz) assert(data!=0);
  return *this;
}
References data, Deriv_Objet_U::deplace(), and sz.
Referenced by TRUST_Vector< _TRUST_TABL_, _TYPE_ >::add().
add() [2/2]
vect_impl & vect_impl::add (const vect_impl & data_to_add)
Definition at line 214 of file vect_impl.cpp.
{
  int sz_data_to_add = data_to_add.size();
  DerObjU* tempo;
  int new_size=sz+sz_data_to_add;
  tempo = new DerObjU[new_size];
  for(int i=0; i<sz; i++)
    (tempo[i]).deplace( data[i]);
  if (data) delete [] data;
  data=tempo;
  sz=new_size;
  for(int j=0; j<sz_data_to_add; j++)
    {
      data[sz-sz_data_to_add+j]= data_to_add[j];
    }
  assert(sz>=0);
  if(sz) assert(data!=0);
  return *this;
}
References data, Deriv_Objet_U::deplace(), size(), and sz.
build_vect_impl()
void vect_impl::build_vect_impl (int i)
Definition at line 63 of file vect_impl.cpp.
{
  sz=i;
  if(i==0) data=0;
  else
    {
      data=0;
      dimensionner_force(i);
      if(!data)
        {
          Cerr << "Allocation is not possible : " << finl;
          exit();
        }
    }
  assert(sz>=0);
  if(sz) assert(data!=0);
}
References Cerr, data, dimensionner_force(), Process::exit(), finl, and sz.
Referenced by TRUST_Vector< _TRUST_TABL_, _TYPE_ >::TRUST_Vector().
cree_instance()
Objet_U * vect_impl::cree_instance () static
Definition at line 18 of file vect_impl.cpp.
cree_une_instance()
Objet_U * vect_impl::cree_une_instance () const protected virtual
methhode surcharge par les classes filles pour fournir la bonne
instance aux constructeurs au readOn....
Reimplemented in Vect_Champ_front, Vect_Cond_lim, Vect_Sous_zone_dis, Vect_Champ_Don, Vect_Ref_Champ_base, Vect_Ref_Probleme_base, Vect_Schema_Temps, Vect_Zone_dis, Vect_Esp_Virt, Vect_Esp_Dist, Vect_Matrice, Vect_Precond, TRUST_Vector< _TRUST_TABL_, _TYPE_ >, TRUST_Vector< TRUSTTab, _TYPE_ >, Vect_Descripteur, Vect_Parser_U, Vect_Motcle, Vect_Nom, Vect_ptrParam, Vect_Deriv_Comm_Group, Vect_Front_VF, Vect_Ref_Champ_Inc_base, and Vect_RefObjU.
Definition at line 54 of file vect_impl.cpp.
{
  Cerr<<"cree_une_instance() must be redefined in "<<que_suis_je()<<finl;
  exit();
  throw;
  return cree_une_instance() ;
}
References Cerr, cree_une_instance(), Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by cree_une_instance(), dimensionner(), and dimensionner_force().
dimensionner()
void vect_impl::dimensionner (int i)
Definition at line 138 of file vect_impl.cpp.
{
  if(sz==i) return;
  if(sz!=0)
    {
      Cerr << "WARNING : dimensionner method of a vect_impl" << finl;
      Cerr << "old size : " << sz << finl;
      Cerr << "new size : " << i << finl;
    }
  assert(data==0);
  Objet_U* ptr_inst=cree_une_instance();
  const Objet_U& une_instance=*ptr_inst;
  sz=i;
  data = new DerObjU[i];
  if(!data)
    {
      Cerr << "Allocation is not possible. " << finl;
      exit();
    }
  for (int ii=0; ii<sz; ii++)
    data[ii]=une_instance;
  assert(sz>=0);
  if(sz) assert(data!=0);
  delete ptr_inst;
}
References Cerr, cree_une_instance(), data, Process::exit(), finl, and sz.
Referenced by Probleme_Couple::associer_sch_tps_base(), Refine_Mesh::build_new_boundary_faces_2D(), Refine_Mesh::build_new_boundary_faces_3D(), Refine_Mesh::build_new_connector_faces_2D(), Refine_Mesh::build_new_connector_faces_3D(), Refine_Mesh::build_new_internal_frontier_faces_2D(), Refine_Mesh::build_new_internal_frontier_faces_3D(), Refine_Mesh::build_new_sub_zones_descriptions(), Champ_Generique_Transformation::completer(), Op_Correlation::completer(), Chimie::completer(), Matrice_Bloc::dimensionner(), Matrice_Bloc_Sym::dimensionner(), Zone_VF::discretiser(), Domaine_dis::discretiser(), Field_base::fixer_nb_comp(), gmres_local(), Matrice_Morse::imprimer_formatte(), Matrice_Morse::imprimer_image(), init_parts(), Sonde::initialiser(), Champ_front_recyclage::initialiser(), Champ_front_recyclage::initialiser_moyenne_imposee(), Rotation::interpreter_(), Transformer::interpreter_(), Terme_Boussinesq_base::lire_donnees(), Champ_front_recyclage::lire_info_moyenne_imposee(), Champ_Generique_Transformation::lire_motcle_non_standard(), Equation_base::lire_motcle_non_standard(), PDF_model::lire_motcle_non_standard(), Champ_Generique_Transformation::preparer_macro(), Champ_front_t::readOn(), Champ_front_txyz::readOn(), Champ_Fonc_t::readOn(), Zone_Cl_dis_base::readOn(), Matrice_Bloc::readOn(), readOn(), Champ_front_softanalytique::readOn(), Op_Conv_EF_Stab_PolyMAC_Elem::readOn(), Op_Diff_Turbulent_PolyMAC_P0_Face::readOn(), Champ_front_debit_QC_fonc_t::readOn(), QDM_Multiphase::readOn(), Op_Conv_EF_VEF_P1NC_Stab::readOn(), Table::remplir(), Eval_Turbulence::update_equivalent_distance(), verifie(), and Champ_Generique_Transformation::verifier_coherence_donnees().
dimensionner_force()
void vect_impl::dimensionner_force (int i)
Definition at line 164 of file vect_impl.cpp.
{
  if(data)
    {
      reset();
    }
  Objet_U* ptr_inst=cree_une_instance();
  const Objet_U& une_instance=*ptr_inst;
  sz=i;
  data = new DerObjU[i];
  if(!data)
    {
      Cerr << "Allocation is not possible. " << finl;
      exit();
    }
  for (int ii=0; ii<sz; ii++)
    data[ii]=une_instance;
  assert(sz>=0);
  if(sz) assert(data!=0);
  delete ptr_inst;
}
References Cerr, cree_une_instance(), data, Process::exit(), finl, reset(), and sz.
Referenced by build_vect_impl(), Champ_base::corriger_unite_nom_compo(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Field_base::fixer_unites(), lit(), TRUSTTab_parts< _TYPE_ >::reset(), ConstTRUSTTab_parts< _TYPE_ >::reset(), and Sondes::set_noms_champs_postraitables().
duplique()
int vect_impl::duplique () const override virtual
Implements Objet_U.
Reimplemented in TRUST_Vector< TRUSTTab, _TYPE_ >, Vect_Front_VF, Vect_Ref_Champ_Inc_base, and Vect_RefObjU.
Definition at line 18 of file vect_impl.cpp.
get_info()
const Type_info * vect_impl::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Vect_Front_VF, Vect_Ref_Champ_Inc_base, and Vect_RefObjU.
Definition at line 18 of file vect_impl.cpp.
info()
const Type_info * vect_impl::info () static
Definition at line 18 of file vect_impl.cpp.
lit()
Entree & vect_impl::lit (Entree & s)
Definition at line 40 of file vect_impl.cpp.
{
  int i;
  s >> i;
  dimensionner_force(i);
  for(i=0; i<sz; i++)
    s>>data[i].valeur();
  assert(sz>=0);
  if(sz) assert(data!=0);
  return s;
}
References data, dimensionner_force(), sz, and valeur().
Referenced by TRUST_Vector< _TRUST_TABL_, _TYPE_ >::lit().
operator=()
vect_impl & vect_impl::operator= (const vect_impl & avect_impl)
Definition at line 109 of file vect_impl.cpp.
{
  if (this==&(ref_cast(vect_impl,avect_impl)))
    return *this;
  if(data)
    {
      reset();
    }
  sz=avect_impl.sz;
  if(sz)
    {
      data = new DerObjU[sz];
      if(!data)
        {
          Cerr << "Allocation is not possible : " << finl;
          exit();
        }
      int i=sz;
      while(i--)
        {
          data[i]=avect_impl[i];
        }
    }
  else data=0;
  assert(sz>=0);
  if(sz) assert(data!=0);
  return *this;
}
References Cerr, data, Process::exit(), finl, ref_cast, reset(), and sz.
Referenced by TRUST_Vector< _TRUST_TABL_, _TYPE_ >::operator=().
operator[]() [1/2]
Objet_U & vect_impl::operator[] (int i) inline
Definition at line 63 of file vect_impl.h.
{
  assert( (i>=0) && (i<sz) );
  assert(sz>=0);
  if(sz) assert(data!=0);
  return (Objet_U&)data[i].valeur();
}
References data, sz, and Deriv_Objet_U::valeur().
operator[]() [2/2]
const Objet_U & vect_impl::operator[] (int i) const inline
Definition at line 55 of file vect_impl.h.
{
  assert( (i>=0) && (i<sz) );
  assert(sz>=0);
  if(sz) assert(data!=0);
  return (const Objet_U&)data[i].valeur();
}
References data, sz, and Deriv_Objet_U::valeur().
Referenced by TRUST_Vector< _TRUST_TABL_, _TYPE_ >::operator[]().
printOn()
Sortie & vect_impl::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in TRUST_Vector< TRUSTTab, _TYPE_ >, Vect_Front_VF, Vect_Ref_Champ_Inc_base, and Vect_RefObjU.
Definition at line 19 of file vect_impl.cpp.
{
  int i=sz;
  s<<sz<<space;
  for(i=0; i<sz; i++)
    s<<data[i].valeur()<<space;
  assert(sz>=0);
  if(sz) assert(data!=0);
  return s<<finl;
}
References data, finl, space, sz, and valeur().
Referenced by TRUST_Vector< _TRUST_TABL_, _TYPE_ >::printOn().
readOn()
Entree & vect_impl::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Vect_Front_VF, Vect_Ref_Champ_Inc_base, Vect_RefObjU, and TRUST_Vector< TRUSTTab, _TYPE_ >.
Definition at line 29 of file vect_impl.cpp.
{
  int i;
  s >> i;
  dimensionner(i);
  for(i=0; i<sz; i++)
    s>>data[i].valeur();
  assert(sz>=0);
  if(sz) assert(data!=0);
  return s;
}
References data, dimensionner(), sz, and valeur().
Referenced by TRUST_Vector< _TRUST_TABL_, _TYPE_ >::readOn().
reset()
void vect_impl::reset ()
Definition at line 187 of file vect_impl.cpp.
{
  if (data)
    {
      delete [] data;
      data=0;
      sz=0;
    }
  assert(sz==0);
}
References data, and sz.
Referenced by Zone::chercher_elements(), Sondes::clear_cache(), dimensionner_force(), operator=(), and ~vect_impl().
self_cast() [1/2]
const vect_impl & vect_impl::self_cast (const Objet_U & r) static
Definition at line 18 of file vect_impl.cpp.
self_cast() [2/2]
vect_impl & vect_impl::self_cast (Objet_U & r) static
Definition at line 18 of file vect_impl.cpp.
size()
int vect_impl::size () const inline
Definition at line 50 of file vect_impl.h.
{
  return sz;
}
References sz.
Referenced by TRUST_Vector< _TRUST_TABL_, _TYPE_ >::add(), add(), Objet_a_lire::add_dict(), Debog_Pb::add_renum_item(), Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), assemblerP0P1(), assemblerP0Pa(), assemblerP1P1(), assemblerP1Pa(), assemblerPaPa(), auto_build_joints(), Op_Dift_standard_VEF_Face::calcul_divergence(), Champ_P1NC::calcul_duidxj_paroi(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Conds_lim::calculer_coeffs_echange(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Scatter::calculer_espace_distant(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Dift_Stab_VEF_Face::calculer_min(), Partitionneur_Tranche::chercher_direction_perio(), Zone::chercher_elements(), Conds_lim::compatible_avec_discr(), Conds_lim::compatible_avec_eqn(), Operateur_base::completer(), Sonde::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Reaction::completer(), Champ_Generique_Transformation::completer(), Op_Correlation::completer(), Chimie::completer(), Champ_P1iP1B_implementation::completer(), Conds_lim::completer(), composante(), Champ_Generique_base::composante(), Pb_MED::comprend_champ(), Champ_Generique_base::comprend_champ_post(), Domain_Graph::construire_graph_elem_elem(), Partitionneur_Fichier_Decoupage::construire_partition(), Partitionneur_Sous_Zones::construire_partition(), Partitionneur_Tranche::construire_partition(), Zone_VEF_PreP1b::construire_renum_arete_perio(), Domaine::construire_renum_som_perio(), Scatter::construire_structures_paralleles(), construit_connectivite_sommet(), Zone_Cl_dis_base::contient_Cl(), Partitionneur_base::corriger_bords_avec_graphe(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Scatter::corriger_espace_distant_elements_perio(), Partitionneur_base::corriger_multiperiodique(), Champ_base::corriger_unite_nom_compo(), create_listb_from_xyz(), create_listb_geom(), create_listb_naif(), Champ_Fonc_MED::creer(), Pb_MED::creer_champ(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_stat(), Pb_Multiphase::creer_milieu(), Op_VDF_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Pb_Multiphase::discretiser(), Zone_Poly_base::dist_norm_bord(), Zone_VDF::dist_norm_bord(), Format_Post_Med::ecrire_champ_med(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Turbulence_paroi_scal_base::equivalent_distance(), Parser_Eval::eval_fct(), Reaction::extract_coef(), extract_coef_local(), Extraire_surface::extraire_surface(), Champ_P1NC_implementation::filtrer_L2(), Debog_Pb::find_renum_vector(), Champ_Generique_Transformation::get_champ(), Champ_Generique_base::get_champ_post(), Champ_Generique_Correlation::get_info_type_post(), Champ_Generique_Ecart_Type::get_property(), Champ_Generique_Extraction::get_property(), Champ_Generique_Interpolation::get_property(), Champ_Generique_Moyenne::get_property(), Champ_Generique_refChamp::get_property(), Champ_Generique_Tparoi_VEF::get_property(), ICoCo::ProblemTrio::getInputFieldsNames(), ICoCo::ProblemTrio::getOutputFieldsNames(), gmres_local(), Champs_compris::has_champ(), Postraitement::init(), Zone_Poly_base::init_dist_paroi_globale(), Champ_Elem_PolyMAC::init_fcl(), Champ_Face_PolyMAC::init_fcl(), grad_Champ_Face_PolyMAC_P0::init_grad(), Op_Diff_PolyMAC_Elem::init_op_ext(), Op_Diff_PolyMAC_P0_Elem::init_s_dist(), Op_Diff_PolyMAC_P0_Elem::init_som_ext(), Sonde::initialiser(), Conds_lim::initialiser(), Zone_Cl_VEF::initialiser(), Moyenne_volumique::interpreter(), Execute_parallel::interpreter(), latatoother::interpreter(), Create_domain_from_sous_zone::interpreter_(), DecoupeBord::interpreter_(), Extraire_plan::interpreter_(), Extruder_en3::interpreter_(), Solveur_U_P::iterer_NS(), Zone_Cl_dis_base::la_cl_de_la_face(), Postraitement_lata::lire_champs(), Postraitement::lire_champs_a_postraiter(), Scatter::lire_domaine(), Pb_Multiphase::lire_equations(), Postraitement::lire_tableaux_a_postraiter(), Assembleur_P_VDF::liste_faces_periodiques(), Zone_VF::marquer_faces_double_contrib(), MD_Vector_std::MD_Vector_std(), Champ_Fonc_t::me_calculer(), grad_Champ_Face_PolyMAC_P0::me_calculer(), Conds_lim::mettre_a_jour(), Chimie::mettre_a_jour(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Zone_Cl_dis_base::mettre_a_jour_ss_pas_dt(), Convection_Diffusion_Temperature::mise_a_jour_tag_indicatrice_pena_glob(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), modifieP1P1neumann(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_matrice(), Zone_EF::modifier_pour_Cl(), Zone_VF::modifier_pour_Cl(), Zone_VEF::modifier_pour_Cl(), Zone_VDF::modifier_pour_Cl(), Op_EF_base::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Terme_Source_Th_TdivU_VEF_Face::modifier_zone_cl(), Zone_Cl_EF::nb_bord_periodicite(), Zone_Cl_PolyMAC::nb_bord_periodicite(), Zone_Cl_VEF::nb_bord_periodicite(), Zone_Cl_dis_base::nb_cond_lim(), Zone_Cl_VDF::nb_faces_sortie_libre(), Zone_Cl_VEF::nb_faces_sortie_libre(), Zone_VF::nb_frontiere_dis(), Pb_Multiphase::nb_phases(), Domaine_dis::nombre_de_sous_zones_dis(), Domaine_dis::nombre_de_zones(), Discretisation_base::nommer_completer_champ_physique(), noms_to_motcles(), Operateur_base::ouvrir_fichier(), Convection_Diffusion_Temperature::penalisation_L2(), Sonde::postraiter(), Postraitement_lata::postraiter(), Format_Post_base::postraiter_debug_valeurs_un_instant(), Postraitement::postraiter_tenseur(), Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul(), Champ_Generique_Transformation::preparer_macro(), Objet_a_lire::print(), Motcles::rang(), Noms::rang(), Objet_a_lire::read(), Champ_Fonc_Tabule::readOn(), Sonde_Int::readOn(), rebuild_liste_noms(), Table::remplir(), Assembleur_P_VEF::remplir(), Assembleur_P_VDF::remplir(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee(), Champ_front_contact_VEF::remplir_faces_coin(), Zone_Cl_EF::remplir_type_elem_Cl(), Zone_Cl_VEF::remplir_type_elem_Cl(), Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(), Reordonner_faces_periodiques::renum_som_perio(), Motcles::search(), Noms::search_without_checking_Motcle(), Static_Int_Lists::set(), Conds_lim::set_modifier_val_imp(), Sondes::set_noms_champs_postraitables(), TRUSTTab_parts< _TYPE_ >::size(), ConstTRUSTTab_parts< _TYPE_ >::size(), Probleme_Couple::solveTimeStep(), Turbulence_paroi_scal_base::tab_equivalent_distance(), Turbulence_paroi_scal_base::tab_equivalent_distance_size(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_front_contact_VEF::test_faces_coin(), Moyenne_volumique::traiter_champs(), Field_base::unite(), Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries(), updateP0P1(), updateP0Pa(), updateP1P1(), updateP1Pa(), updatePaPa(), Table::val(), Table::val_simple(), Champ_Inc_base::valeur_aux_bords(), Table::valeurs(), verifie(), Postraitement::verifie_nom_et_sources(), Champ_Generique_Transformation::verifier_coherence_donnees(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), Debog_Pb::verifier_Mat_elems(), and Convection_Diffusion_Temperature::verifier_tag_indicatrice_pena_glob().
taille_memoire()
unsigned vect_impl::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in TRUST_Vector< TRUSTTab, _TYPE_ >, Vect_Front_VF, Vect_Ref_Champ_Inc_base, and Vect_RefObjU.
Definition at line 18 of file vect_impl.cpp.
Member Data Documentation
data
DerObjU* vect_impl::data protected
Definition at line 46 of file vect_impl.h.
Referenced by add(), build_vect_impl(), dimensionner(), dimensionner_force(), lit(), operator=(), operator[](), printOn(), readOn(), reset(), vect_impl(), and ~vect_impl().
info_obj
const Type_info vect_impl::info_obj static
Definition at line 25 of file vect_impl.h.
sz
int vect_impl::sz protected
Definition at line 45 of file vect_impl.h.
Referenced by add(), build_vect_impl(), dimensionner(), dimensionner_force(), lit(), operator=(), operator[](), printOn(), readOn(), reset(), size(), and vect_impl().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/vect_impl.h
src/Kernel/Utilitaires/vect_impl.cpp