TRUST: Champ_Fonc_Fonction_txyz Class Reference
Champ_Fonc_Fonction_txyz Class Reference
classe Champ_Fonc_Fonction_txyz
classe derivee de Champ_Fonc_Fonction
Cette classe represente un champ de donnees fonction d une variable scalaire
et de variables d'espaces x,y,z et du temps t. La(les) fonction(s) est(sont) fournie(s)
directement dans le jeu de donnees sous la forme d'expression(s) mathematique
.......................
#include <Champ_Fonc_Fonction_txyz.h>
Public Member Functions
Champ_Fonc_Fonction_txyz ()
~Champ_Fonc_Fonction_txyz ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Fonc_Fonction_txyz & self_cast (Objet_U &)
static const
Champ_Fonc_Fonction_txyz & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
Lecture du Champ a partir d'un flot d'entree,
(On ne sait traiter que les champs scalaires.)
exemple:
Champ_Fonc_Fonction probleme ch
1 (nombre de composantes)
{
2
0 500 0 250 (ch(0)=0 && ch(500)=250
}.
Detailed Description
classe Champ_Fonc_Fonction_txyz
classe derivee de Champ_Fonc_Fonction
Cette classe represente un champ de donnees fonction d une variable scalaire
et de variables d'espaces x,y,z et du temps t. La(les) fonction(s) est(sont) fournie(s)
directement dans le jeu de donnees sous la forme d'expression(s) mathematique
.......................
Definition at line 41 of file Champ_Fonc_Fonction_txyz.h.
Constructor & Destructor Documentation
Champ_Fonc_Fonction_txyz::Champ_Fonc_Fonction_txyz ()
Definition at line 25 of file Champ_Fonc_Fonction_txyz.cpp.
Champ_Fonc_Fonction_txyz::~Champ_Fonc_Fonction_txyz ()
Definition at line 25 of file Champ_Fonc_Fonction_txyz.cpp.
Member Function Documentation
Objet_U * Champ_Fonc_Fonction_txyz::cree_instance () [static]
Reimplemented from Champ_Fonc_Fonction.
Definition at line 25 of file Champ_Fonc_Fonction_txyz.cpp.
int Champ_Fonc_Fonction_txyz::duplique () const [virtual]
Reimplemented from Champ_Fonc_Fonction.
Definition at line 25 of file Champ_Fonc_Fonction_txyz.cpp.
const Type_info * Champ_Fonc_Fonction_txyz::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_Fonction.
Definition at line 25 of file Champ_Fonc_Fonction_txyz.cpp.
const Type_info * Champ_Fonc_Fonction_txyz::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_Fonction.
Definition at line 25 of file Champ_Fonc_Fonction_txyz.cpp.
Sortie & Champ_Fonc_Fonction_txyz::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_Fonction.
Definition at line 28 of file Champ_Fonc_Fonction_txyz.cpp.
{ return os; }
Entree & Champ_Fonc_Fonction_txyz::readOn (Entree & is) [protected, virtual]
Lecture du Champ a partir d'un flot d'entree,
(On ne sait traiter que les champs scalaires.)
exemple:
Champ_Fonc_Fonction probleme ch
1 (nombre de composantes)
{
2
0 500 0 250 (ch(0)=0 && ch(500)=250
}.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Fonc_Fonction.
Definition at line 32 of file Champ_Fonc_Fonction_txyz.cpp.
References Vect_Nom::add(), Cerr, Process::exit(), finl, Field_base::fixer_nb_comp(), Champ_Fonc_Tabule::la_table, Table::lire_fxyzt(), Champ_Fonc_Tabule::noms_champs_parametre_, Champ_Fonc_Tabule::noms_pbs_, and Champ_Fonc_Tabule::Warn_old_chp_fonc_syntax_V_184().
{
  int nbcomp, nbcomp_tmp_ = -1, old_table_syntax_ = 0;
  Nom val1, val2;
  is >> val1;
  is >> val2;
// fix if user uses the old syntax ..
  Champ_Fonc_Tabule::Warn_old_chp_fonc_syntax_V_184("Champ_Fonc_Fonction_txyz", val2, nbcomp_tmp_, old_table_syntax_);
  if (old_table_syntax_)
    {
      noms_champs_parametre_.add(val1);
      nbcomp = nbcomp_tmp_;
    }
  else
    {
      noms_pbs_.add(val1);
      noms_champs_parametre_.add(val2);
      is >> nbcomp;
    }
  if(nbcomp==1)
    {
      fixer_nb_comp(nbcomp);
      la_table.lire_fxyzt(is,nbcomp);
    }
  else
    {
      Cerr << "Error reading from an object of type Champ_Fonc_Fonction_txyz" << finl;
      Cerr << "We know treating only the scalar fields " << finl;
      Process::exit();
    }
  return is;
}
const Champ_Fonc_Fonction_txyz & Champ_Fonc_Fonction_txyz::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_Fonction.
Definition at line 25 of file Champ_Fonc_Fonction_txyz.cpp.
Champ_Fonc_Fonction_txyz & Champ_Fonc_Fonction_txyz::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_Fonction.
Definition at line 25 of file Champ_Fonc_Fonction_txyz.cpp.
unsigned Champ_Fonc_Fonction_txyz::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc_Fonction.
Definition at line 25 of file Champ_Fonc_Fonction_txyz.cpp.
Member Data Documentation
const Type_info Champ_Fonc_Fonction_txyz::info_obj [static]
Reimplemented from Champ_Fonc_Fonction.
Definition at line 43 of file Champ_Fonc_Fonction_txyz.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Fonc_Fonction_txyz.h
src/Kernel/Champs/Champ_Fonc_Fonction_txyz.cpp