TRUST: Ch_front_var_instationnaire_indep Class Reference
Ch_front_var_instationnaire_indep Class Reference
classe Ch_front_var_instationnaire_indep
Cette classe abstraite represente un champ sur une frontiere,
variable en espace, instationnaire en temps, et independant de
donnees exterieures au champ.
De ce fait, la methode initialiser peut appeler la methode
mettre_a_jour. Cette classe factorise cet appel.
#include <Ch_front_var_instationnaire_indep.h>
Public Member Functions
Ch_front_var_instationnaire_indep ()
~Ch_front_var_instationnaire_indep ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialise le temps courant et Gpoint.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Ch_front_var_instationnaire_indep & self_cast (Objet_U &)
static const
Ch_front_var_instationnaire_indep & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le nom du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Detailed Description
classe Ch_front_var_instationnaire_indep
Cette classe abstraite represente un champ sur une frontiere,
variable en espace, instationnaire en temps, et independant de
donnees exterieures au champ.
De ce fait, la methode initialiser peut appeler la methode
mettre_a_jour. Cette classe factorise cet appel.
Definition at line 41 of file Ch_front_var_instationnaire_indep.h.
Constructor & Destructor Documentation
Ch_front_var_instationnaire_indep::Ch_front_var_instationnaire_indep ()
Definition at line 25 of file Ch_front_var_instationnaire_indep.cpp.
Ch_front_var_instationnaire_indep::~Ch_front_var_instationnaire_indep ()
Definition at line 25 of file Ch_front_var_instationnaire_indep.cpp.
Member Function Documentation
virtual int Ch_front_var_instationnaire_indep::duplique () const [pure virtual]
Implements Champ_front_var_instationnaire.
Implemented in Champ_front_bruite, Champ_front_t, Champ_front_txyz, Champ_front_MED, Champ_front_debit_QC, and Champ_front_debit_QC_fonc_t.
const Type_info * Ch_front_var_instationnaire_indep::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Champ_front_bruite, Champ_front_t, Champ_front_txyz, Champ_front_MED, Champ_front_debit_QC, and Champ_front_debit_QC_fonc_t.
Definition at line 25 of file Ch_front_var_instationnaire_indep.cpp.
const Type_info * Ch_front_var_instationnaire_indep::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Champ_front_bruite, Champ_front_t, Champ_front_txyz, Champ_front_MED, Champ_front_debit_QC, and Champ_front_debit_QC_fonc_t.
Definition at line 25 of file Ch_front_var_instationnaire_indep.cpp.
int Ch_front_var_instationnaire_indep::initialiser (double temps, const Champ_Inc_base & inco) [virtual]
Initialise le temps courant et Gpoint.
< pour dimensionner
Reimplemented from Champ_front_var_instationnaire.
Definition at line 40 of file Ch_front_var_instationnaire_indep.cpp.
References Champ_front_var_instationnaire::initialiser(), and Champ_front_base::mettre_a_jour().
{
  if (!Champ_front_var_instationnaire::initialiser(temps,inco))
    return 0;
  mettre_a_jour(temps);
  return 1;
}
Sortie & Ch_front_var_instationnaire_indep::printOn (Sortie & s) const [protected, virtual]
Imprime le nom du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Champ_front_bruite, Champ_front_t, Champ_front_txyz, Champ_front_MED, Champ_front_debit_QC, and Champ_front_debit_QC_fonc_t.
Definition at line 27 of file Ch_front_var_instationnaire_indep.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Ch_front_var_instationnaire_indep::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Champ_front_bruite, Champ_front_t, Champ_front_txyz, Champ_front_MED, Champ_front_debit_QC, and Champ_front_debit_QC_fonc_t.
Definition at line 32 of file Ch_front_var_instationnaire_indep.cpp.
{
  return s ;
}
const Ch_front_var_instationnaire_indep & Ch_front_var_instationnaire_indep::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Champ_front_bruite, Champ_front_t, Champ_front_txyz, Champ_front_MED, Champ_front_debit_QC, and Champ_front_debit_QC_fonc_t.
Definition at line 25 of file Ch_front_var_instationnaire_indep.cpp.
Ch_front_var_instationnaire_indep & Ch_front_var_instationnaire_indep::self_cast (Objet_U & r) [static]
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Champ_front_bruite, Champ_front_t, Champ_front_txyz, Champ_front_MED, Champ_front_debit_QC, and Champ_front_debit_QC_fonc_t.
Definition at line 25 of file Ch_front_var_instationnaire_indep.cpp.
Member Data Documentation
const Type_info Ch_front_var_instationnaire_indep::info_obj [static]
Reimplemented from Champ_front_var_instationnaire.
Reimplemented in Champ_front_bruite, Champ_front_t, Champ_front_txyz, Champ_front_MED, Champ_front_debit_QC, and Champ_front_debit_QC_fonc_t.
Definition at line 43 of file Ch_front_var_instationnaire_indep.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Ch_front_var_instationnaire_indep.h
src/Kernel/Framework/Ch_front_var_instationnaire_indep.cpp