TRUST: Champ_Inc Class Reference
Champ_Inc Class Reference
#include <Champ_Inc.h>
Public Member Functions
Champ_Inc ()
~Champ_Inc ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & valeurs () override
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs au temps courant.
const DoubleTab & valeurs () const override
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs au temps courant<br>(version const)
int reprendre (Entree &) override
Appel a l'objet sous-jacent
Effectue une reprise sur un flot d'entree.
int sauvegarder (Sortie &) const override
Appel a l'objet sous-jacent
Effectue une sauvegarde sur un flot de sortie.
int fixer_nb_valeurs_temporelles (int)
Appel a l'objet sous-jacent
Fixe le nombre de pas de temps a conserver.
int nb_valeurs_temporelles () const
Appel a l'objet sous-jacent
Renvoie le nombre de pas de temps conserve.
int fixer_nb_valeurs_nodales (int)
Appel a l'objet sous-jacent
Fixe le nombre de degres de liberte par composante.
int nb_valeurs_nodales () const
Appel a l'objet sous-jacent
Renvoie le nombre de degres de liberte par composante.
const Zone_dis_base & associer_zone_dis_base (const Zone_dis_base &)
Appel a l'objet sous-jacent
Associe le champ a une zone discretisee.
const Zone_dis_base & zone_dis_base () const
Appel a l'objet sous-jacent
Renvoie la zone discretisee associee au champ.
double changer_temps (const double)
Appel a l'objet sous-jacent
Fixe le temps courant.
double temps () const
Appel a l'objet sous-jacent
Renvoie le temps courant.
DoubleTab & futur (int i=1) override
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs au temps t+i.
const DoubleTab & futur (int i=1) const override
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs au temps t+i.
(version const)
DoubleTab & passe (int i=1) override
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs au temps t-i.
const DoubleTab & passe (int i=1) const override
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs au temps t-i.
(version const)
Champ_Inc_base & avancer (int i=1)
Appel a l'objet sous-jacent
Avance le temps courant du champ de i pas de temps.
Champ_Inc_base & reculer (int i=1)
Appel a l'objet sous-jacent
Recule le temps courant du champ de i pas de temps.
int lire_donnees (Entree &)
Appel a l'objet sous-jacent
Lit les valeurs du champs a partir d'un flot d'entree.
double integrale_espace (int) const
Appel a l'objet sous-jacent
calcule l'integrale de l'une des composantes
du champ sur le domaine qui lui correspond.
void mettre_a_jour (double temps)
void associer_eqn (const Equation_base &)
Appel a l'objet sous-jacent
Associe le champ a l'equation dont il est une inconnue.
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Appel a l'objet sous-jacent
Calcule la trace du champ sur une frontiere et renvoie
les valeurs.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Deriv_Champ_Inc_base
~Deriv_Champ_Inc_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Champ_Inc_base ()
Deriv_Champ_Inc_base (const Deriv_Champ_Inc_base &)
const Champ_Inc_base & valeur () const
Champ_Inc_base & valeur ()
const Champ_Inc_base * operator-> () const
Champ_Inc_base * operator-> ()
const Deriv_Champ_Inc_base & operator= (const Champ_Inc_base &)
const Deriv_Champ_Inc_base & operator= (const Deriv_Champ_Inc_base &)
operator const Champ_Inc_base & () const
operator Champ_Inc_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Inc & self_cast (Objet_U &)
static const Champ_Inc & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Champ_Inc_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Champ_Inc_base & self_cast (Objet_U &)
static const Deriv_Champ_Inc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Champ_Inc_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du champ a partir d'un flot d'entree.
Protected Member Functions inherited from Deriv_Champ_Inc_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Definition at line 37 of file Champ_Inc.h.
Constructor & Destructor Documentation
Champ_Inc()
Champ_Inc::Champ_Inc ()
Definition at line 19 of file Champ_Inc.cpp.
~Champ_Inc()
Champ_Inc::~Champ_Inc ()
Definition at line 19 of file Champ_Inc.cpp.
Member Function Documentation
associer_eqn()
void Champ_Inc::associer_eqn (const Equation_base & eqn)
Appel a l'objet sous-jacent
Associe le champ a l'equation dont il est une inconnue.
Definition at line 489 of file Champ_Inc.cpp.
{
  valeur().associer_eqn(eqn);
}
References Champ_Inc_base::associer_eqn(), and Deriv_Champ_Inc_base::valeur().
Referenced by Equation_base::completer(), Navier_Stokes_std::completer(), Fluide_base::creer_e_int(), Equation_base::init_champ_conserve(), and Energie_Multiphase::init_champ_convecte().
associer_zone_dis_base()
const Zone_dis_base & Champ_Inc::associer_zone_dis_base (const Zone_dis_base & z)
Appel a l'objet sous-jacent
Associe le champ a une zone discretisee.
Returns
Zone_dis_base&
Signification: la zone discretise associee au champ
Contraintes:
Definition at line 158 of file Champ_Inc.cpp.
{
  valeur().associer_zone_dis_base(z);
  return z;
}
References Champ_base::associer_zone_dis_base(), and Deriv_Champ_Inc_base::valeur().
Referenced by Champ_Fonc_reprise::readOn().
avancer()
Champ_Inc_base & Champ_Inc::avancer (int i = 1)
Appel a l'objet sous-jacent
Avance le temps courant du champ de i pas de temps.
Returns
Champ_Inc_base&
Signification: le champ inconnu place au nouveau temps courant
Contraintes:
Definition at line 361 of file Champ_Inc.cpp.
{
  return valeur().avancer(i);
}
References Champ_Inc_base::avancer(), and Deriv_Champ_Inc_base::valeur().
Referenced by Equation_base::avancer(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), and Sch_CN_EX_iteratif::iterateTimeStepOnOther().
changer_temps()
double Champ_Inc::changer_temps (const double t)
Appel a l'objet sous-jacent
Fixe le temps courant.
Definition at line 198 of file Champ_Inc.cpp.
{
  return valeur().changer_temps(t);
}
References Champ_Inc_base::changer_temps(), and Deriv_Champ_Inc_base::valeur().
Referenced by Equation_base::preparer_calcul(), and Navier_Stokes_std::preparer_calcul().
cree_instance()
Objet_U * Champ_Inc::cree_instance () static
Definition at line 19 of file Champ_Inc.cpp.
duplique()
int Champ_Inc::duplique () const override virtual
Reimplemented from Deriv_Champ_Inc_base.
Definition at line 19 of file Champ_Inc.cpp.
fixer_nb_valeurs_nodales()
int Champ_Inc::fixer_nb_valeurs_nodales (int i)
Appel a l'objet sous-jacent
Fixe le nombre de degres de liberte par composante.
Returns
int
Signification: le nombre de degres de libertee par composante
Contraintes:
Definition at line 118 of file Champ_Inc.cpp.
{
  return valeur().fixer_nb_valeurs_nodales(i);
}
References Champ_Inc_base::fixer_nb_valeurs_nodales(), and Deriv_Champ_Inc_base::valeur().
fixer_nb_valeurs_temporelles()
int Champ_Inc::fixer_nb_valeurs_temporelles (int i)
Appel a l'objet sous-jacent
Fixe le nombre de pas de temps a conserver.
Returns
int
Signification: le nombre de pas de temps a conserver
Contraintes:
Definition at line 78 of file Champ_Inc.cpp.
{
  return valeur().fixer_nb_valeurs_temporelles(i);
}
References Champ_Inc_base::fixer_nb_valeurs_temporelles(), and Deriv_Champ_Inc_base::valeur().
futur() [1/2]
const DoubleTab & Champ_Inc::futur (int i = 1) const override virtual
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs au temps t+i.
(version const)
Returns
DoubleTab&
Signification: le tableau des valeurs au temps t+i
Contraintes: reference constante
Reimplemented from Champ_Proto.
Definition at line 300 of file Champ_Inc.cpp.
{
  return valeur().futur(i);
}
References Champ_Inc_base::futur(), and Deriv_Champ_Inc_base::valeur().
futur() [2/2]
DoubleTab & Champ_Inc::futur (int i = 1) override virtual
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs au temps t+i.
Returns
DoubleTab&
Signification: le tableau des valeurs au temps t+i
Contraintes:
Reimplemented from Champ_Proto.
Definition at line 279 of file Champ_Inc.cpp.
{
  return valeur().futur(i);
}
References Champ_Inc_base::futur(), and Deriv_Champ_Inc_base::valeur().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), TRUSTSchema_RK< _ORDRE_ >::faire_un_pas_de_temps_eqn_base_generique(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), Equation_base::initTimeStep(), Navier_Stokes_std::initTimeStep(), QDM_Multiphase::initTimeStep(), Simple::iterer_eqs(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), test_imposer_cond_lim(), Schema_Implicite_Multi_TimeStep_base::test_stationnaire(), and Schema_Adams_Moulton_base::update_time_derivative().
get_info()
const Type_info * Champ_Inc::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Champ_Inc_base.
Definition at line 19 of file Champ_Inc.cpp.
info()
const Type_info * Champ_Inc::info () static
Definition at line 19 of file Champ_Inc.cpp.
integrale_espace()
double Champ_Inc::integrale_espace (int ncomp) const
Appel a l'objet sous-jacent
calcule l'integrale de l'une des composantes
du champ sur le domaine qui lui correspond.
Returns
double
Signification: valeur de l'integrale
Contraintes:
Definition at line 463 of file Champ_Inc.cpp.
{
  return valeur().integrale_espace(ncomp);
}
References Champ_Inc_base::integrale_espace(), and Deriv_Champ_Inc_base::valeur().
lire_donnees()
int Champ_Inc::lire_donnees (Entree & is)
Appel a l'objet sous-jacent
Lit les valeurs du champs a partir d'un flot d'entree.
Returns
int
Signification: code de retour propage
Contraintes:
Definition at line 402 of file Champ_Inc.cpp.
{
  return valeur().lire_donnees(is);
}
References Champ_Inc_base::lire_donnees(), and Deriv_Champ_Inc_base::valeur().
mettre_a_jour()
void Champ_Inc::mettre_a_jour (double temps)
Definition at line 469 of file Champ_Inc.cpp.
{
  valeur().mettre_a_jour(un_temps);
}
References Champ_Inc_base::mettre_a_jour(), and Deriv_Champ_Inc_base::valeur().
Referenced by Pb_Dilatable_base::iterateTimeStep(), Equation_base::mettre_a_jour(), Navier_Stokes_std::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Equation_base::mettre_a_jour_champs_conserves(), Schema_Adams_Moulton_base::mettre_a_jour_equation(), and Schema_Backward_Differentiation_base::mettre_a_jour_equation().
nb_valeurs_nodales()
int Champ_Inc::nb_valeurs_nodales () const
Appel a l'objet sous-jacent
Renvoie le nombre de degres de liberte par composante.
Returns
int
Signification: le nombre de degres de liberte par composante
Contraintes:
Definition at line 138 of file Champ_Inc.cpp.
{
  return valeur().nb_valeurs_nodales();
}
References Champ_Inc_base::nb_valeurs_nodales(), and Deriv_Champ_Inc_base::valeur().
nb_valeurs_temporelles()
int Champ_Inc::nb_valeurs_temporelles () const
Appel a l'objet sous-jacent
Renvoie le nombre de pas de temps conserve.
Returns
int
Signification: le nombre de pas de temps conserve
Contraintes:
Definition at line 98 of file Champ_Inc.cpp.
{
  return valeur().nb_valeurs_temporelles() ;
}
References Champ_Inc_base::nb_valeurs_temporelles(), and Deriv_Champ_Inc_base::valeur().
Referenced by Fluide_base::creer_e_int(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), Equation_base::init_champ_conserve(), and Energie_Multiphase::init_champ_convecte().
operator const DoubleTab &()
Champ_Inc::operator const DoubleTab & () const delete
operator DoubleTab &()
Champ_Inc::operator DoubleTab & () delete
passe() [1/2]
const DoubleTab & Champ_Inc::passe (int i = 1) const override virtual
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs au temps t-i.
(version const)
Returns
DoubleTab&
Signification: le tableau des valeurs au temps t-i
Contraintes: reference constante
Reimplemented from Champ_Proto.
Definition at line 341 of file Champ_Inc.cpp.
{
  return valeur().passe(i);
}
References Champ_Inc_base::passe(), and Deriv_Champ_Inc_base::valeur().
passe() [2/2]
DoubleTab & Champ_Inc::passe (int i = 1) override virtual
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs au temps t-i.
Returns
DoubleTab&
Signification: le tableau des valeurs au temps t-i
Contraintes:
Reimplemented from Champ_Proto.
Definition at line 320 of file Champ_Inc.cpp.
{
  return valeur().passe(i);
}
References Champ_Inc_base::passe(), and Deriv_Champ_Inc_base::valeur().
Referenced by Schema_Adams_Moulton_base::add_multi_timestep_data(), Schema_Backward_Differentiation_base::add_multi_timestep_data(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Schema_Temps_base::ajouter_inertie(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Navier_Stokes_std::corriger_derivee_impl(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Implicite_Multi_TimeStep_recommencer_pb(), Schema_Implicite_Multi_TimeStep_base::Initialiser_Champs(), Simple::iterer_eqn(), SETS::iterer_NS(), QDM_Multiphase::lire_cond_init(), Aire_interfaciale::mettre_a_jour(), Schema_Adams_Bashforth_base::modifier_second_membre(), Schema_Adams_Moulton_base::modifier_second_membre_full_impl(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), and Schema_Implicite_Multi_TimeStep_base::test_stationnaire().
printOn()
Sortie & Champ_Inc::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime le champ sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Champ_Inc_base.
Definition at line 37 of file Champ_Inc.cpp.
{
  return DERIV(Champ_Inc_base)::printOn(os);
}
References DERIV, and printOn().
Referenced by printOn().
readOn()
Entree & Champ_Inc::readOn (Entree & is) override protected virtual
Lecture du champ a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Champ_Inc_base.
Definition at line 57 of file Champ_Inc.cpp.
{
  return DERIV(Champ_Inc_base)::readOn(is);
}
References DERIV, and readOn().
Referenced by readOn().
reculer()
Champ_Inc_base & Champ_Inc::reculer (int i = 1)
Appel a l'objet sous-jacent
Recule le temps courant du champ de i pas de temps.
Returns
Champ_Inc_base&
Signification: le champ inconnu place au nouveau temps courant
Contraintes:
Definition at line 381 of file Champ_Inc.cpp.
{
  return valeur().reculer(i);
}
References Champ_Inc_base::reculer(), and Deriv_Champ_Inc_base::valeur().
Referenced by Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Pb_Dilatable_base::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), and Equation_base::reculer().
reprendre()
int Champ_Inc::reprendre (Entree & is) override virtual
Appel a l'objet sous-jacent
Effectue une reprise sur un flot d'entree.
Returns
int
Signification: code de retour propage
Contraintes:
Reimplemented from Objet_U.
Definition at line 422 of file Champ_Inc.cpp.
{
  return valeur().reprendre(is);
}
References Champ_Inc_base::reprendre(), and Deriv_Champ_Inc_base::valeur().
Referenced by Equation_base::reprendre(), Navier_Stokes_std::reprendre(), and Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC().
sauvegarder()
int Champ_Inc::sauvegarder (Sortie & os) const override virtual
Appel a l'objet sous-jacent
Effectue une sauvegarde sur un flot de sortie.
Returns
int
Signification: code de retour propage
Contraintes:
Reimplemented from Objet_U.
Definition at line 442 of file Champ_Inc.cpp.
{
  return valeur().sauvegarder(os);
}
References Champ_Inc_base::sauvegarder(), and Deriv_Champ_Inc_base::valeur().
Referenced by Equation_base::sauvegarder(), Navier_Stokes_std::sauvegarder(), and Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC().
self_cast() [1/2]
const Champ_Inc & Champ_Inc::self_cast (const Objet_U & r) static
Definition at line 19 of file Champ_Inc.cpp.
self_cast() [2/2]
Champ_Inc & Champ_Inc::self_cast (Objet_U & r) static
Definition at line 19 of file Champ_Inc.cpp.
taille_memoire()
unsigned Champ_Inc::taille_memoire () const override virtual
Reimplemented from Deriv_Champ_Inc_base.
Definition at line 19 of file Champ_Inc.cpp.
temps()
double Champ_Inc::temps () const
Appel a l'objet sous-jacent
Renvoie le temps courant.
Returns
double
Signification: le temps courant
Contraintes:
Definition at line 218 of file Champ_Inc.cpp.
{
  return valeur().temps();
}
References Champ_base::temps(), and Deriv_Champ_Inc_base::valeur().
Referenced by Mod_turb_hyd_base::a_faire(), Modele_turbulence_scal_base::a_faire(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), VDF_discretisation::courant_maille(), Fluide_base::creer_e_int(), VDF_discretisation::critere_Q(), EF_discretisation::critere_Q(), PolyMAC_discretisation::critere_Q(), VEF_discretisation::critere_Q(), Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_nut(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat_1col(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp_1col(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp_old(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu_old(), Convection_Diffusion_Temperature::get_champ(), Navier_Stokes_std::get_champ(), EF_discretisation::grad_T(), PolyMAC_discretisation::grad_T(), VEF_discretisation::grad_T(), VDF_discretisation::grad_u(), VEF_discretisation::grad_u(), EF_discretisation::h_conv(), PolyMAC_discretisation::h_conv(), VEF_discretisation::h_conv(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Traitement_particulier_NS_canal::post_traitement_particulier(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), Traitement_particulier_Solide_canal_VDF::post_traitement_particulier(), Traitement_particulier_NS_chmoy_faceperio::post_traitement_particulier(), Traitement_particulier_NS_EC::post_traitement_particulier(), Traitement_particulier_NS_Profils_VDF::post_traitement_particulier(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson(), Traitement_particulier_NS_chmoy_faceperio::preparer_calcul_particulier(), Traitement_particulier_NS_EC::preparer_calcul_particulier(), Traitement_particulier_NS_Profils::reprendre_stat(), Traitement_particulier_NS_Profils_thermo_VDF::reprendre_stat(), VDF_discretisation::residu(), VEF_discretisation::residu(), PolyMAC_discretisation::residu(), VDF_discretisation::reynolds_maille(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), Traitement_particulier_NS_canal::sauver_stat(), Traitement_particulier_NS_Profils::sauver_stat(), Traitement_particulier_NS_Profils_thermo_VDF::sauver_stat(), Traitement_particulier_NS_canal::sauver_stat_canal(), Fluide_Quasi_Compressible::secmembre_divU_Z(), VDF_discretisation::taux_cisaillement(), VEF_discretisation::taux_cisaillement(), EF_discretisation::vorticite(), PolyMAC_discretisation::vorticite(), VDF_discretisation::vorticite(), VEF_discretisation::vorticite(), VDF_discretisation::y_plus(), EF_discretisation::y_plus(), and VEF_discretisation::y_plus().
trace()
DoubleTab & Champ_Inc::trace (const Frontiere_dis_base & fr, DoubleTab & x, double tps, int distant) const
Appel a l'objet sous-jacent
Calcule la trace du champ sur une frontiere et renvoie
les valeurs.
Returns
DoubleTab&
Signification: les valeurs du champ sur la frontiere au temps tps
Contraintes:
Definition at line 516 of file Champ_Inc.cpp.
{
  return valeur().trace(fr, x, tps,distant);
}
References Champ_Inc_base::trace(), and Deriv_Champ_Inc_base::valeur().
Referenced by Echange_couplage_thermique::initialiser().
valeurs() [1/6]
const DoubleTab & Champ_Inc::valeurs () const override virtual
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs au temps courant<br>(version const)
Returns
DoubleTab&
Signification: le tableau des valeurs au temps courant
Contraintes: reference constante
Implements Champ_Proto.
Definition at line 259 of file Champ_Inc.cpp.
{
  return valeur().valeurs();
}
References Deriv_Champ_Inc_base::valeur(), and Champ_Inc_base::valeurs().
valeurs() [2/6]
virtual const DoubleTab & Champ_Proto::valeurs () const virtual
Implements Champ_Proto.
valeurs() [3/6]
DoubleTab & Champ_Inc::valeurs () override virtual
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs au temps courant.
Returns
DoubleTab&
Signification: le tableau des valeurs au temps courant
Contraintes:
Implements Champ_Proto.
Definition at line 238 of file Champ_Inc.cpp.
{
  return valeur().valeurs();
}
References Deriv_Champ_Inc_base::valeur(), and Champ_Inc_base::valeurs().
Referenced by Navier_Stokes_std::abortTimeStep(), Schema_Adams_Moulton_base::add_multi_timestep_data(), Schema_Backward_Differentiation_base::add_multi_timestep_data(), Operateur::ajouter(), Op_Diff_RotRot::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Terme_Source_Decroissance_Radioactive_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Op_Dift_VDF_base::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Elem::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Op_Conv_VDF_base::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Solveur_Masse_base::ajouter_masse(), Masse_PolyMAC_Face::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC::assembler_continuite(), Simpler_Base::assembler_matrice_pression_implicite(), Op_Diff_VEF_base::associer(), Eval_Echange_Himp_VDF_Elem::associer_champs(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Perte_Charge_Singuliere::calculate_Q(), Operateur::calculer(), Source_PDF_base::calculer(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Loi_Etat_GR_base::calculer_Cp(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Champ_Ostwald_VEF::calculer_dscald(), Op_Conv_VDF_base::calculer_dt_local(), Op_Diff_PolyMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Traitement_particulier_NS_EC::calculer_Ec(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Turbulence_paroi_base::calculer_hyd(), Navier_Stokes_std::calculer_la_pression_en_pa(), Op_Diff_VEFP1NCP1B_Face::calculer_laplacien_som(), Loi_Etat_base::calculer_masse_volumique(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), Loi_Etat_Binaire_GP_base::calculer_mu_wilke(), Fluide_Dilatable_base::calculer_pression_tot(), Eval_Darcy_VDF_Face::calculer_terme_source(), Eval_Forchheimer_VDF_Face::calculer_terme_source(), Eval_Darcy_VEF_Face::calculer_terme_source(), Eval_Forchheimer_VEF_Face::calculer_terme_source(), Echange_contact_VDF::calculer_Teta_paroi(), Source_Neutronique_VDF::calculer_Tmoyenne(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Fluide_reel_base::check_unknown_range(), Op_Diff_PolyMAC_base::completer(), Op_Diff_PolyMAC_P0_base::completer(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::completer(), EDO_Pression_th_VDF::completer(), EDO_Pression_th_VEF::completer(), Flux_interfacial_PolyMAC::completer(), Echange_contact_Correlation_VEF::completer(), Terme_Source_Decroissance_Radioactive_VEF_Face::completer(), Champ_Post_Operateur_Eqn::completer(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Diff_EF::contribuer_au_second_membre(), Op_Dift_EF_Q1::contribuer_au_second_membre(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), Navier_Stokes_std::corriger_derivee_expl(), Navier_Stokes_std::corriger_derivee_impl(), Masse_PolyMAC_Face::corriger_solution(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Op_EF_base::dimensionner(), Op_VDF_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Op_Div_PolyMAC_P0::dimensionner(), Solveur_Masse_base::dimensionner(), Masse_PolyMAC_Face::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Masse_VDF_base::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Travail_pression_PolyMAC::dimensionner_blocs(), Assembleur_P_PolyMAC::dimensionner_continuite(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), TRUSTSchema_RK< _ORDRE_ >::faire_un_pas_de_temps_eqn_base_generique(), Champ_Post_Operateur_Eqn::get_champ(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), Champ_Q1_EF::gradient(), Champ_Q1NC::gradient(), Equation_base::Gradient_conjugue_diff_impl(), Zone_Cl_EF::imposer_cond_lim(), Zone_Cl_VEF::imposer_cond_lim(), Zone_Cl_EF::imposer_symetrie_matrice_secmem(), Source_PDF_EF::impr(), Navier_Stokes_std::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Equation_base::imprime_residu(), Terme_Source_Canal_RANS_LES_VEF_Face::init(), Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Equation_base::initialise_residu(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Loi_Etat_GP_base::initialiser(), Loi_Etat_GR_base::initialiser(), Loi_Etat_GR_base::initialiser_inco_ch(), Equation_base::initTimeStep(), Navier_Stokes_Fluide_Dilatable_base::initTimeStep(), Navier_Stokes_std::initTimeStep(), QDM_Multiphase::initTimeStep(), Schema_Temps_base::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), Simple::iterer_eqn(), Simple::iterer_eqs(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), QDM_Multiphase::lire_cond_init(), Eval_Echange_Himp_VDF_Elem::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Navier_Stokes_std::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Elem::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VEF_Face::mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), modif_matrice_pour_periodique_apres_contribuer(), modif_matrice_pour_periodique_avant_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_nu(), Op_EF_base::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Schema_Adams_Bashforth_base::modifier_second_membre(), Schema_Backward_Differentiation_base::modify_equation_parameters(), Convection_Diffusion_Temperature::penalisation_L2(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), Equation_base::preparer_calcul(), Op_Conv_EF_Stab_PolyMAC_Elem::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projeter(), Champ_Fonc_reprise::readOn(), Loi_Etat_GP_base::remplir_T(), Loi_Etat_GR_base::remplir_T(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), VDF_discretisation::residu(), VEF_discretisation::residu(), PolyMAC_discretisation::residu(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(), EOS_Tools_VEF::secmembre_divU_Z(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), Schema_Backward_Differentiation_base::store_equation_parameters(), Op_Diff_VEFP1NCP1B_Face::test(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), Schema_Implicite_Multi_TimeStep_base::test_stationnaire(), Op_Grad_PolyMAC_P0_Face::update_grad(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries(), verifier(), Debog::verifier(), verifier_complet(), and Fluide_Quasi_Compressible::write_mean_edo().
valeurs() [4/6]
virtual DoubleTab & Champ_Proto::valeurs () virtual
Implements Champ_Proto.
valeurs() [5/6]
virtual DoubleTab & Champ_Proto::valeurs (double temps) inline virtual
Reimplemented from Champ_Proto.
Definition at line 50 of file Champ_Proto.h.
{ return valeurs(); }
valeurs() [6/6]
virtual const DoubleTab & Champ_Proto::valeurs (double temps) const inline virtual
Reimplemented from Champ_Proto.
Definition at line 51 of file Champ_Proto.h.
{ return valeurs(); }
zone_dis_base()
const Zone_dis_base & Champ_Inc::zone_dis_base () const
Appel a l'objet sous-jacent
Renvoie la zone discretisee associee au champ.
Returns
Zone_dis_base&
Signification:
Contraintes: reference constante
Definition at line 178 of file Champ_Inc.cpp.
{
  return valeur().zone_dis_base();
}
References Deriv_Champ_Inc_base::valeur(), and Champ_base::zone_dis_base().
Referenced by Terme_Source_Solide_SWIFT_VDF::ajouter_blocs(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Loi_Etat_GP_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_alpha(), Traitement_particulier_NS_EC::calculer_Ec(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), Loi_Etat_base::calculer_nu(), Loi_Etat_Multi_GP_base::calculer_tab_mu(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Terme_Source_Canal_RANS_LES_VDF_Elem::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Terme_Source_Canal_RANS_LES_VEF_Face::init(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Traitement_particulier_Solide_canal_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Traitement_particulier_NS_Pression_VEF::lire(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Brech_VEF::lire(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Traitement_particulier_NS_canal_VDF::remplir_Y(), and Traitement_particulier_NS_canal_VEF::remplir_Y().
Member Data Documentation
info_obj
const Type_info Champ_Inc::info_obj static
Definition at line 39 of file Champ_Inc.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_Inc.h
src/Kernel/Framework/Champ_Inc.cpp