TRUST: Lec_Diffuse_base Class Reference
Lec_Diffuse_base Class Reference
Classe de base des entrees diffusees: le processeur maitre lit
les donnees dans la classe get_entree_master() et les diffuse
sur tous les processeurs.
Attention, les methodes operator>>(), get(), eof(), good() et bad()
doivent etre appelees simultanement sur tous les processeurs.
Les classes derivees doivent reimplementer get_entree_master().
La methode get_entree_master() doit renvoyer une reference a l'entree
qui sert de source sur le processeur maitre, elle n'est jamais appellee
sur les autres processeurs.
Attention: l'entree source doit avoir set_error_action(ERROR_CONTINUE)
#include <Lec_Diffuse_base.h>
Public Member Functions
~Lec_Diffuse_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & operator>> (int &ob)
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
Entree & operator>> (long &ob)
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
Entree & operator>> (float &ob)
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
Entree & operator>> (double &ob)
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
int get (int *ob, int n)
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
int get (long *ob, int n)
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
int get (float *ob, int n)
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
int get (double *ob, int n)
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
int get (char *buf, int bufsize)
Lecture d'une chaine dans ostream_
bufsize est la taille du buffer alloue pour ob (y compris
le caractere 0 final).
La chaine contient toujours un 0 meme en cas d'echec.
La methode renvoie 1 si la lecture est bonne, 0 sinon.
Si le buffer est trop petit, pour l'instant on fait exit() mais
par la suite on pourra tester: si strlen(ob)==bufsize-1, alors
refaire lire() jusqu'a arriver au bout. Si le lire() suivant
renvoie une chaine de longueur nulle, cela signifie que la taille de la
chaine etait exactement bufsize-1.
Attention: le comportement est different en binaire et en ascii.
En binaire, on lit la chaine jusqu'au prochain '\0'.
En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
int eof ()
int good ()
int fail ()
int set_bin (int bin)
appelle get_entree_master().set_bin(bin)
void set_check_types (int flag)
appelle get_entree_master().set_check_types(flag)
virtual void set_diffuse (int diffuse)
ToDo TMA : commenter.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Lec_Diffuse_base & self_cast (Objet_U &)
static const Lec_Diffuse_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Lec_Diffuse_base ()
ne fait rien (constructeur protege car c'est une classe de base)
Lec_Diffuse_base (const Lec_Diffuse_base &)
Lec_Diffuse_base & operator= (const Lec_Diffuse_base &)
erreur
virtual Entree & get_entree_master ()=0
Detailed Description
Classe de base des entrees diffusees: le processeur maitre lit
les donnees dans la classe get_entree_master() et les diffuse
sur tous les processeurs.
Attention, les methodes operator>>(), get(), eof(), good() et bad()
doivent etre appelees simultanement sur tous les processeurs.
Les classes derivees doivent reimplementer get_entree_master().
La methode get_entree_master() doit renvoyer une reference a l'entree
qui sert de source sur le processeur maitre, elle n'est jamais appellee
sur les autres processeurs.
Attention: l'entree source doit avoir set_error_action(ERROR_CONTINUE)
Definition at line 48 of file Lec_Diffuse_base.h.
Constructor & Destructor Documentation
Lec_Diffuse_base::~Lec_Diffuse_base ()
Definition at line 32 of file Lec_Diffuse_base.cpp.
Lec_Diffuse_base::Lec_Diffuse_base () [protected]
ne fait rien (constructeur protege car c'est une classe de base)
Definition at line 47 of file Lec_Diffuse_base.cpp.
{
}
Lec_Diffuse_base::Lec_Diffuse_base (const Lec_Diffuse_base &) [protected]
Member Function Documentation
virtual int Lec_Diffuse_base::duplique () const [pure virtual]
Reimplemented from EFichier.
Implemented in LecFicDiffuse, LecFicDiffuse_JDD, and LecFicDiffuseBin.
int Lec_Diffuse_base::eof () [virtual]
Reimplemented from Entree_Fichier_base.
Definition at line 277 of file Lec_Diffuse_base.cpp.
References Entree::diffuse_, envoyer_broadcast(), Entree::eof(), get_entree_master(), and Process::je_suis_maitre().
Referenced by Sondes::lire_fichier(), and Champ_Don_lu::readOn().
{
  int flag = 0;
  if (Process::je_suis_maitre())
    {
      Entree& is = get_entree_master();
      flag = is.eof();
    }
  if (diffuse_) envoyer_broadcast(flag, 0);
  return flag;
}
int Lec_Diffuse_base::fail () [virtual]
Reimplemented from Entree_Fichier_base.
Definition at line 301 of file Lec_Diffuse_base.cpp.
References Entree::diffuse_, envoyer_broadcast(), Entree::fail(), get_entree_master(), and Process::je_suis_maitre().
{
  int flag = 0;
  if (Process::je_suis_maitre())
    {
      Entree& is = get_entree_master();
      flag = is.fail();
    }
  if (diffuse_) envoyer_broadcast(flag, 0);
  return flag;
}
int Lec_Diffuse_base::get (char * buf, int bufsize) [virtual]
Lecture d'une chaine dans ostream_
bufsize est la taille du buffer alloue pour ob (y compris
le caractere 0 final).
La chaine contient toujours un 0 meme en cas d'echec.
La methode renvoie 1 si la lecture est bonne, 0 sinon.
Si le buffer est trop petit, pour l'instant on fait exit() mais
par la suite on pourra tester: si strlen(ob)==bufsize-1, alors
refaire lire() jusqu'a arriver au bout. Si le lire() suivant
renvoie une chaine de longueur nulle, cela signifie que la taille de la
chaine etait exactement bufsize-1.
Attention: le comportement est different en binaire et en ascii.
En binaire, on lit la chaine jusqu'au prochain '\0'.
En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
Reimplemented from Entree.
Definition at line 252 of file Lec_Diffuse_base.cpp.
References Cerr, Entree::diffuse_, envoyer_broadcast(), envoyer_broadcast_array(), Entree::ERROR_CONTINUE, Entree::error_handle(), Process::exit(), finl, Entree::get(), get_entree_master(), Entree::get_error_action(), and Process::je_suis_maitre().
{
  int l = -1;
  if (Process::je_suis_maitre())
    {
      Entree& is = get_entree_master();
      assert(is.get_error_action() == ERROR_CONTINUE);
      int ok = is.get(buf, bufsize);
      if (ok)
        l = strlen(buf) + 1;
    }
  else if (!diffuse_)
    {
      Cerr << "Lec_Diffuse_base::get(...) can't be used with diffuse_=0 on non master process." << finl;
      exit();
    }
  if (diffuse_)
    {
      envoyer_broadcast(l, 0);
      if (l > 0)
        envoyer_broadcast_array(buf, l, 0);
    }
  return error_handle(l < 0);
}
int Lec_Diffuse_base::get (int * ob, int n) [virtual]
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
Reimplemented from Entree.
Definition at line 85 of file Lec_Diffuse_base.cpp.
References Cerr, Entree::diffuse_, envoyer_broadcast(), envoyer_broadcast_array(), Entree::ERROR_CONTINUE, Entree::error_handle(), Process::exit(), finl, Entree::get(), get_entree_master(), Entree::get_error_action(), and Process::je_suis_maitre().
{
  int ok = 0;
  if (Process::je_suis_maitre())
    {
      Entree& is = get_entree_master();
      assert(is.get_error_action() == ERROR_CONTINUE);
      ok = is.get(ob, n);
    }
  else if (!diffuse_)
    {
      Cerr << "Lec_Diffuse_base::get(...) can't be used with diffuse_=0 on non master process." << finl;
      exit();
    }
  if (diffuse_)
    {
      envoyer_broadcast(ok, 0);
      if (ok)
        envoyer_broadcast_array(ob, n, 0);
    }
  return error_handle(!ok);
}
int Lec_Diffuse_base::get (long * ob, int n) [virtual]
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
Reimplemented from Entree.
Definition at line 133 of file Lec_Diffuse_base.cpp.
References Cerr, Entree::diffuse_, envoyer_broadcast(), envoyer_broadcast_array(), Entree::ERROR_CONTINUE, Entree::error_handle(), Process::exit(), finl, Entree::get(), get_entree_master(), Entree::get_error_action(), and Process::je_suis_maitre().
{
  int ok = 0;
  if (Process::je_suis_maitre())
    {
      Entree& is = get_entree_master();
      assert(is.get_error_action() == ERROR_CONTINUE);
      ok = is.get(ob, n);
    }
  else if (!diffuse_)
    {
      Cerr << "Lec_Diffuse_base::get(...) can't be used with diffuse_=0 on non master process." << finl;
      exit();
    }
  if (diffuse_)
    {
      envoyer_broadcast(ok, 0);
      if (ok)
        envoyer_broadcast_array(ob, n, 0);
    }
  return error_handle(!ok);
}
int Lec_Diffuse_base::get (float * ob, int n) [virtual]
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
Reimplemented from Entree.
Definition at line 181 of file Lec_Diffuse_base.cpp.
References Cerr, Entree::diffuse_, envoyer_broadcast(), envoyer_broadcast_array(), Entree::ERROR_CONTINUE, Entree::error_handle(), Process::exit(), finl, Entree::get(), get_entree_master(), Entree::get_error_action(), and Process::je_suis_maitre().
{
  int ok = 0;
  if (Process::je_suis_maitre())
    {
      Entree& is = get_entree_master();
      assert(is.get_error_action() == ERROR_CONTINUE);
      ok = is.get(ob, n);
    }
  else if (!diffuse_)
    {
      Cerr << "Lec_Diffuse_base::get(...) can't be used with diffuse_=0 on non master process." << finl;
      exit();
    }
  if (diffuse_)
    {
      envoyer_broadcast(ok, 0);
      if (ok)
        envoyer_broadcast_array(ob, n, 0);
    }
  return error_handle(!ok);
}
int Lec_Diffuse_base::get (double * ob, int n) [virtual]
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
Reimplemented from Entree.
Definition at line 228 of file Lec_Diffuse_base.cpp.
References Cerr, Entree::diffuse_, envoyer_broadcast(), envoyer_broadcast_array(), Entree::ERROR_CONTINUE, Entree::error_handle(), Process::exit(), finl, Entree::get(), get_entree_master(), Entree::get_error_action(), and Process::je_suis_maitre().
{
  int ok = 0;
  if (Process::je_suis_maitre())
    {
      Entree& is = get_entree_master();
      assert(is.get_error_action() == ERROR_CONTINUE);
      ok = is.get(ob, n);
    }
  else if (!diffuse_)
    {
      Cerr << "Lec_Diffuse_base::get(...) can't be used with diffuse_=0 on non master process." << finl;
      exit();
    }
  if (diffuse_)
    {
      envoyer_broadcast(ok, 0);
      if (ok)
        envoyer_broadcast_array(ob, n, 0);
    }
  return error_handle(!ok);
}
virtual Entree& Lec_Diffuse_base::get_entree_master () [protected, pure virtual]
Implemented in LecFicDiffuse, and LecFicDiffuse_JDD.
Referenced by eof(), fail(), get(), good(), operator>>(), set_bin(), and set_check_types().
const Type_info * Lec_Diffuse_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from EFichier.
Reimplemented in LecFicDiffuse, LecFicDiffuse_JDD, and LecFicDiffuseBin.
Definition at line 32 of file Lec_Diffuse_base.cpp.
int Lec_Diffuse_base::good () [virtual]
Reimplemented from Entree_Fichier_base.
Definition at line 289 of file Lec_Diffuse_base.cpp.
References Entree::diffuse_, envoyer_broadcast(), get_entree_master(), Entree::good(), and Process::je_suis_maitre().
Referenced by VerifierCoin::interpreter_(), Sondes::lire_fichier(), and valeur_P1_L2().
{
  int flag = 0;
  if (Process::je_suis_maitre())
    {
      Entree& is = get_entree_master();
      flag = is.good();
    }
  if (diffuse_) envoyer_broadcast(flag, 0);
  return flag;
}
const Type_info * Lec_Diffuse_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from EFichier.
Reimplemented in LecFicDiffuse, LecFicDiffuse_JDD, and LecFicDiffuseBin.
Definition at line 32 of file Lec_Diffuse_base.cpp.
Lec_Diffuse_base & Lec_Diffuse_base::operator= (const Lec_Diffuse_base &) [protected]
erreur
Definition at line 52 of file Lec_Diffuse_base.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Error in Lec_Diffuse_base & operator=(const Lec_Diffuse_base & is)" << finl;
  Process::exit();
  return *this;
}
Entree & Lec_Diffuse_base::operator>> (int & ob) [virtual]
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
< Bien appeler get de cette classe
Reimplemented from Entree.
Definition at line 60 of file Lec_Diffuse_base.cpp.
References Cerr, Entree::diffuse_, envoyer_broadcast(), Entree::ERROR_CONTINUE, Entree::error_handle(), Process::exit(), finl, get_entree_master(), Entree::get_error_action(), Entree::good(), and Process::je_suis_maitre().
{
  int ok = 0;
  if (Process::je_suis_maitre())
    {
      Entree& is = get_entree_master();
      assert(is.get_error_action() == ERROR_CONTINUE);
      is >> ob;
      ok = is.good();
    }
  else if (!diffuse_)
    {
      Cerr << "Lec_Diffuse_base::operator>> can't be used with diffuse_=0 on non master process." << finl;
      exit();
    }
  if (diffuse_)
    {
      envoyer_broadcast(ok, 0);
      if (ok)
        envoyer_broadcast(ob, 0);
    }
  error_handle(!ok);
  return *this;
}
Entree & Lec_Diffuse_base::operator>> (double & ob) [virtual]
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
< Bien appeler get de cette classe
Reimplemented from Entree.
Definition at line 203 of file Lec_Diffuse_base.cpp.
References Cerr, Entree::diffuse_, envoyer_broadcast(), Entree::ERROR_CONTINUE, Entree::error_handle(), Process::exit(), finl, get_entree_master(), Entree::get_error_action(), Entree::good(), and Process::je_suis_maitre().
{
  int ok = 0;
  if (Process::je_suis_maitre())
    {
      Entree& is = get_entree_master();
      assert(is.get_error_action() == ERROR_CONTINUE);
      is >> ob;
      ok = is.good();
    }
  else if (!diffuse_)
    {
      Cerr << "Lec_Diffuse_base::operator>> can't be used with diffuse_=0 on non master process." << finl;
      exit();
    }
  if (diffuse_)
    {
      envoyer_broadcast(ok, 0);
      if (ok)
        envoyer_broadcast(ob, 0);
    }
  error_handle(!ok);
  return *this;
}
Entree & Lec_Diffuse_base::operator>> (float & ob) [virtual]
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
< Bien appeler get de cette classe
Reimplemented from Entree.
Definition at line 156 of file Lec_Diffuse_base.cpp.
References Cerr, Entree::diffuse_, envoyer_broadcast(), Entree::ERROR_CONTINUE, Entree::error_handle(), Process::exit(), finl, get_entree_master(), Entree::get_error_action(), Entree::good(), and Process::je_suis_maitre().
{
  int ok = 0;
  if (Process::je_suis_maitre())
    {
      Entree& is = get_entree_master();
      assert(is.get_error_action() == ERROR_CONTINUE);
      is >> ob;
      ok = is.good();
    }
  else if (!diffuse_)
    {
      Cerr << "Lec_Diffuse_base::operator>> can't be used with diffuse_=0 on non master process." << finl;
      exit();
    }
  if (diffuse_)
    {
      envoyer_broadcast(ok, 0);
      if (ok)
        envoyer_broadcast(ob, 0);
    }
  error_handle(!ok);
  return *this;
}
Entree & Lec_Diffuse_base::operator>> (long & ob) [virtual]
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
< Bien appeler get de cette classe
Reimplemented from Entree.
Definition at line 108 of file Lec_Diffuse_base.cpp.
References Cerr, Entree::diffuse_, envoyer_broadcast(), Entree::ERROR_CONTINUE, Entree::error_handle(), Process::exit(), finl, get_entree_master(), Entree::get_error_action(), Entree::good(), and Process::je_suis_maitre().
{
  int ok = 0;
  if (Process::je_suis_maitre())
    {
      Entree& is = get_entree_master();
      assert(is.get_error_action() == ERROR_CONTINUE);
      is >> ob;
      ok = is.good();
    }
  else if (!diffuse_)
    {
      Cerr << "Lec_Diffuse_base::operator>> can't be used with diffuse_=0 on non master process." << finl;
      exit();
    }
  if (diffuse_)
    {
      envoyer_broadcast(ok, 0);
      if (ok)
        envoyer_broadcast(ob, 0);
    }
  error_handle(!ok);
  return *this;
}
Sortie & Lec_Diffuse_base::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from EFichier.
Reimplemented in LecFicDiffuse, LecFicDiffuse_JDD, and LecFicDiffuseBin.
Definition at line 40 of file Lec_Diffuse_base.cpp.
{
  throw;
  return s;
}
Entree & Lec_Diffuse_base::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from EFichier.
Reimplemented in LecFicDiffuse, LecFicDiffuse_JDD, and LecFicDiffuseBin.
Definition at line 34 of file Lec_Diffuse_base.cpp.
{
  throw;
  return s;
}
const Lec_Diffuse_base & Lec_Diffuse_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from EFichier.
Reimplemented in LecFicDiffuse, LecFicDiffuse_JDD, and LecFicDiffuseBin.
Definition at line 32 of file Lec_Diffuse_base.cpp.
Lec_Diffuse_base & Lec_Diffuse_base::self_cast (Objet_U & r) [static]
Reimplemented from EFichier.
Reimplemented in LecFicDiffuse, LecFicDiffuse_JDD, and LecFicDiffuseBin.
Definition at line 32 of file Lec_Diffuse_base.cpp.
int Lec_Diffuse_base::set_bin (int bin) [virtual]
appelle get_entree_master().set_bin(bin)
Reimplemented from Entree.
Definition at line 314 of file Lec_Diffuse_base.cpp.
References Entree::diffuse_, envoyer_broadcast(), get_entree_master(), Process::je_suis_maitre(), and Entree::set_bin().
Referenced by Champ_front_lu::initialiser(), and LecFicDiffuseBin::LecFicDiffuseBin().
{
  if (Process::je_suis_maitre())
    {
      Entree& is = get_entree_master();
      bin = is.set_bin(bin);
    }
  if (diffuse_) envoyer_broadcast(bin, 0);
  Entree::set_bin(bin);
  return bin;
}
void Lec_Diffuse_base::set_check_types (int flag) [virtual]
appelle get_entree_master().set_check_types(flag)
Reimplemented from Entree.
Definition at line 327 of file Lec_Diffuse_base.cpp.
References get_entree_master(), and Entree::set_check_types().
Referenced by mon_main::dowork(), Lire_Fichier::interpreter(), and Execute_parallel::interpreter().
{
  Entree::set_check_types(flag);
  Entree& is = get_entree_master();
  is.set_check_types(flag);
}
void Lec_Diffuse_base::set_diffuse (int diffuse) [virtual]
ToDo TMA : commenter.
Reimplemented from Entree.
Definition at line 335 of file Lec_Diffuse_base.cpp.
References Entree::diffuse_.
{
  assert(diffuse==0 || diffuse==1);
  diffuse_ = diffuse;
}
Member Data Documentation
const Type_info Lec_Diffuse_base::info_obj [static]
Reimplemented from EFichier.
Reimplemented in LecFicDiffuse, LecFicDiffuse_JDD, and LecFicDiffuseBin.
Definition at line 50 of file Lec_Diffuse_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Lec_Diffuse_base.h
src/Kernel/Utilitaires/Lec_Diffuse_base.cpp