TRUST: Deriv_Champ_Fonc_base Class Reference
Deriv_Champ_Fonc_base Class Reference
#include <Champ_Fonc.h>
Public Member Functions
~Deriv_Champ_Fonc_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Champ_Fonc_base ()
Deriv_Champ_Fonc_base (const Deriv_Champ_Fonc_base &)
const Champ_Fonc_base & valeur () const
Champ_Fonc_base & valeur ()
const Champ_Fonc_base * operator-> () const
Champ_Fonc_base * operator-> ()
const Deriv_Champ_Fonc_base & operator= (const Champ_Fonc_base &)
const Deriv_Champ_Fonc_base & operator= (const Deriv_Champ_Fonc_base &)
operator const Champ_Fonc_base & () const
operator Champ_Fonc_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Champ_Fonc_base & self_cast (Objet_U &)
static const
Deriv_Champ_Fonc_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Champ_Fonc_base * pointeur_
Detailed Description
Definition at line 32 of file Champ_Fonc.h.
Constructor & Destructor Documentation
Deriv_Champ_Fonc_base::~Deriv_Champ_Fonc_base ()
Definition at line 25 of file Champ_Fonc.cpp.
Deriv_Champ_Fonc_base::Deriv_Champ_Fonc_base ()
Definition at line 25 of file Champ_Fonc.cpp.
Deriv_Champ_Fonc_base::Deriv_Champ_Fonc_base (const Deriv_Champ_Fonc_base & t)
Definition at line 25 of file Champ_Fonc.cpp.
Member Function Documentation
Objet_U * Deriv_Champ_Fonc_base::cree_instance () [static]
Reimplemented in Champ_Fonc, Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 25 of file Champ_Fonc.cpp.
int Deriv_Champ_Fonc_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Champ_Fonc, Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 25 of file Champ_Fonc.cpp.
const Type_info * Deriv_Champ_Fonc_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Champ_Fonc, Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 25 of file Champ_Fonc.cpp.
const Type_info & Deriv_Champ_Fonc_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Champ_Fonc.cpp.
const Type_info * Deriv_Champ_Fonc_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Champ_Fonc, Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 25 of file Champ_Fonc.cpp.
Deriv_Champ_Fonc_base::operator Champ_Fonc_base & ()
Definition at line 25 of file Champ_Fonc.cpp.
Deriv_Champ_Fonc_base::operator const Champ_Fonc_base & () const
Definition at line 25 of file Champ_Fonc.cpp.
const Champ_Fonc_base * Deriv_Champ_Fonc_base::operator-> () const [inline]
Definition at line 32 of file Champ_Fonc.h.
: public DERIV(Champ_Fonc_base), public Champ_Proto
Champ_Fonc_base * Deriv_Champ_Fonc_base::operator-> () [inline]
Definition at line 32 of file Champ_Fonc.h.
: public DERIV(Champ_Fonc_base), public Champ_Proto
const Deriv_Champ_Fonc_base & Deriv_Champ_Fonc_base::operator= (const Deriv_Champ_Fonc_base & t)
Definition at line 25 of file Champ_Fonc.cpp.
const Deriv_Champ_Fonc_base & Deriv_Champ_Fonc_base::operator= (const Champ_Fonc_base & t)
Reimplemented in Champ_Fonc.
Definition at line 25 of file Champ_Fonc.cpp.
Sortie & Deriv_Champ_Fonc_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Champ_Fonc, Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 25 of file Champ_Fonc.cpp.
Entree & Deriv_Champ_Fonc_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Champ_Fonc, Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 25 of file Champ_Fonc.cpp.
const Deriv_Champ_Fonc_base & Deriv_Champ_Fonc_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Champ_Fonc, Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 25 of file Champ_Fonc.cpp.
Deriv_Champ_Fonc_base & Deriv_Champ_Fonc_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Champ_Fonc, Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 25 of file Champ_Fonc.cpp.
void Deriv_Champ_Fonc_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Champ_Fonc.cpp.
unsigned Deriv_Champ_Fonc_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Champ_Fonc, Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 25 of file Champ_Fonc.cpp.
const Champ_Fonc_base & Deriv_Champ_Fonc_base::valeur () const [inline]
Definition at line 32 of file Champ_Fonc.h.
Referenced by Terme_Source_Acceleration::a_pour_Champ_Fonc(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Acceleration_VDF_Face::ajouter(), Champ_Fonc::associer_zone_dis_base(), Turbulence_paroi_scal_base::calculer_scal(), Op_Correlation::calculer_valeurs(), Champ_Fonc::changer_temps(), VDF_discretisation::courant_maille(), Pb_MED::creer_champ(), Discretisation_base::creer_champ(), VEF_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), PolyMAC_discretisation::creer_champ_vorticite(), EF_discretisation::creer_champ_vorticite(), CoviMAC_discretisation::creer_champ_vorticite(), VEF_discretisation::critere_Q(), VDF_discretisation::critere_Q(), PolyMAC_discretisation::critere_Q(), EF_discretisation::critere_Q(), CoviMAC_discretisation::critere_Q(), Discret_Thyd::diametre_hydraulique(), Marqueur_Lagrange_base::discretiser(), Milieu_base::discretiser(), VEF_discretisation::discretiser_champ_fonc_don(), VDF_discretisation::discretiser_champ_fonc_don(), PolyMAC_discretisation::discretiser_champ_fonc_don(), EF_discretisation::discretiser_champ_fonc_don(), CoviMAC_discretisation::discretiser_champ_fonc_don(), VEF_discretisation::distance_paroi(), PolyMAC_discretisation::distance_paroi(), EF_discretisation::distance_paroi(), CoviMAC_discretisation::distance_paroi(), Champ_Fonc::fixer_nb_valeurs_nodales(), Navier_Stokes_std::get_champ(), Convection_Diffusion_Temperature::get_champ(), Equation_base::get_champ(), Champ_Generique_Correlation::get_champ(), Reaction::get_omega(), Terme_Source_Acceleration::get_terme_source_post(), VEF_discretisation::grad_T(), PolyMAC_discretisation::grad_T(), EF_discretisation::grad_T(), CoviMAC_discretisation::grad_T(), VEF_discretisation::grad_u(), VDF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), CoviMAC_discretisation::grad_u(), VEF_discretisation::h_conv(), PolyMAC_discretisation::h_conv(), EF_discretisation::h_conv(), CoviMAC_discretisation::h_conv(), Champ_Fonc::initialiser(), Champ_Fonc_MED::le_champ(), Champ_Fonc_MED_Table_Temps::le_champ0(), Champ_Fonc::mettre_a_jour(), VEF_discretisation::modifier_champ_tabule(), VDF_discretisation::modifier_champ_tabule(), PolyMAC_discretisation::modifier_champ_tabule(), EF_discretisation::modifier_champ_tabule(), CoviMAC_discretisation::modifier_champ_tabule(), Champ_Fonc::nb_valeurs_nodales(), Champ_Fonc::nommer(), Champ_Fonc::operator const DoubleTab &(), Champ_Fonc::operator DoubleTab &(), Champ_Fonc::operator=(), Discret_Thyd::porosite_volumique(), Champ_Fonc::reprendre(), VEF_discretisation::residu(), VDF_discretisation::residu(), CoviMAC_discretisation::residu(), VDF_discretisation::reynolds_maille(), Champ_Fonc::sauvegarder(), Discret_Thyd::section_passage(), Equation_base::set_residuals(), VEF_discretisation::taux_cisaillement(), VDF_discretisation::taux_cisaillement(), Champ_Fonc::temps(), Fluide_Dilatable_base::update_rho_cp(), Milieu_base::update_rho_cp(), Champ_Fonc::valeur_a_elem(), Champ_Fonc::valeur_a_elem_compo(), Champ_Fonc::valeur_aux_elems(), Champ_Fonc::valeur_aux_sommets(), Champ_Fonc::valeur_aux_sommets_compo(), Champ_Fonc::valeurs(), Discretisation_base::volume_maille(), VEF_discretisation::vorticite(), VDF_discretisation::vorticite(), PolyMAC_discretisation::vorticite(), EF_discretisation::vorticite(), CoviMAC_discretisation::vorticite(), VEF_discretisation::y_plus(), VDF_discretisation::y_plus(), PolyMAC_discretisation::y_plus(), EF_discretisation::y_plus(), CoviMAC_discretisation::y_plus(), and Champ_Fonc::zone_dis_base().
: public DERIV(Champ_Fonc_base), public Champ_Proto
Champ_Fonc_base & Deriv_Champ_Fonc_base::valeur () [inline]
Definition at line 32 of file Champ_Fonc.h.
: public DERIV(Champ_Fonc_base), public Champ_Proto
Member Data Documentation
const Type_info Deriv_Champ_Fonc_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Champ_Fonc, Integrale_tps_Champ, and Integrale_tps_produit_champs.
Definition at line 32 of file Champ_Fonc.h.
Champ_Fonc_base* Deriv_Champ_Fonc_base::pointeur_ [private]
Definition at line 32 of file Champ_Fonc.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_Fonc.h
src/Kernel/Framework/Champ_Fonc.cpp