TRUST: Taux_cisaillement_P0_VEF Class Reference
Taux_cisaillement_P0_VEF Class Reference
classe Taux_cisaillement_P0_VEF
#include <Taux_cisaillement_P0_VEF.h>
Public Member Functions
Taux_cisaillement_P0_VEF ()
~Taux_cisaillement_P0_VEF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double)
Mise a jour en temps du champ.
void associer_champ (const Champ_P1NC &, const Zone_Cl_dis_base &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Taux_cisaillement_P0_VEF & self_cast (Objet_U &)
static const
Taux_cisaillement_P0_VEF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Private Attributes
Ref_Zone_Cl_VEF la_zone_Cl_VEF
Ref_Champ_P1NC vitesse_
Detailed Description
classe Taux_cisaillement_P0_VEF
Definition at line 34 of file Taux_cisaillement_P0_VEF.h.
Constructor & Destructor Documentation
Taux_cisaillement_P0_VEF::Taux_cisaillement_P0_VEF ()
Definition at line 28 of file Taux_cisaillement_P0_VEF.cpp.
Taux_cisaillement_P0_VEF::~Taux_cisaillement_P0_VEF ()
Definition at line 28 of file Taux_cisaillement_P0_VEF.cpp.
Member Function Documentation
void Taux_cisaillement_P0_VEF::associer_champ (const Champ_P1NC & la_vitesse, const Zone_Cl_dis_base & la_zone_Cl_dis_base)
Definition at line 47 of file Taux_cisaillement_P0_VEF.cpp.
References la_zone_Cl_VEF, ref_cast, and vitesse_.
Referenced by VEF_discretisation::taux_cisaillement().
{
  la_zone_Cl_VEF  = ref_cast(Zone_Cl_VEF, la_zone_Cl_dis_base);
  vitesse_= la_vitesse;
}
Objet_U * Taux_cisaillement_P0_VEF::cree_instance () [static]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 28 of file Taux_cisaillement_P0_VEF.cpp.
int Taux_cisaillement_P0_VEF::duplique () const [virtual]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 28 of file Taux_cisaillement_P0_VEF.cpp.
const Type_info * Taux_cisaillement_P0_VEF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 28 of file Taux_cisaillement_P0_VEF.cpp.
const Type_info * Taux_cisaillement_P0_VEF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 28 of file Taux_cisaillement_P0_VEF.cpp.
void Taux_cisaillement_P0_VEF::mettre_a_jour (double temps) [virtual]
Mise a jour en temps du champ.
< Shear rate
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 53 of file Taux_cisaillement_P0_VEF.cpp.
References Champ_base::changer_temps(), la_zone_Cl_VEF, Champ_Fonc_P0_VEF::la_zone_VEF, Ref_Zone_Cl_VEF::valeur(), Ref_Champ_P1NC::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and vitesse_.
{
  int nb_elem = la_zone_VEF->nb_elem();
  DoubleVect tmp(nb_elem);
  vitesse_->calcul_S_barre(vitesse_.valeur().valeurs(),tmp,la_zone_Cl_VEF.valeur());
  DoubleTab& S = valeurs(); //!< Shear rate
  for (int i=0; i<nb_elem; i++)
    S(i) = sqrt(tmp(i));
  changer_temps(tps);
  Champ_Fonc_base::mettre_a_jour(tps);
}
Sortie & Taux_cisaillement_P0_VEF::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 34 of file Taux_cisaillement_P0_VEF.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Taux_cisaillement_P0_VEF::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 42 of file Taux_cisaillement_P0_VEF.cpp.
{
  return s ;
}
Taux_cisaillement_P0_VEF & Taux_cisaillement_P0_VEF::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 28 of file Taux_cisaillement_P0_VEF.cpp.
const Taux_cisaillement_P0_VEF & Taux_cisaillement_P0_VEF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 28 of file Taux_cisaillement_P0_VEF.cpp.
unsigned Taux_cisaillement_P0_VEF::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 28 of file Taux_cisaillement_P0_VEF.cpp.
Member Data Documentation
const Type_info Taux_cisaillement_P0_VEF::info_obj [static]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 37 of file Taux_cisaillement_P0_VEF.h.
Ref_Zone_Cl_VEF Taux_cisaillement_P0_VEF::la_zone_Cl_VEF [private]
Definition at line 46 of file Taux_cisaillement_P0_VEF.h.
Referenced by associer_champ(), and mettre_a_jour().
Ref_Champ_P1NC Taux_cisaillement_P0_VEF::vitesse_ [private]
Definition at line 47 of file Taux_cisaillement_P0_VEF.h.
Referenced by associer_champ(), and mettre_a_jour().
The documentation for this class was generated from the following files:
src/VEF/Champs/Taux_cisaillement_P0_VEF.h
src/VEF/Champs/Taux_cisaillement_P0_VEF.cpp