TRUST: Champ_implementation_P1 Class Reference
Champ_implementation_P1 Class Reference abstract
#include <Champ_implementation_P1.h>
Public Member Functions
~Champ_implementation_P1 () override
Public Member Functions inherited from Champ_implementation_sommet_base
Champ_base & le_champ (void) override=0
const Champ_base & le_champ (void) const override=0
~Champ_implementation_sommet_base () override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
Public Member Functions inherited from Champ_implementation_base
virtual ~Champ_implementation_base ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &domain, DoubleTab &result) const
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &domain, DoubleVect &result, int ncomp) const
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Static Public Member Functions
static void init_from_file (DoubleTab &val, const Domaine &dom, int nb_comp, double tolerance, Entree &input)
Initialise le tableau de valeurs aux sommets du domaine dom a partir de valeurs lues dans "input".
(on dimensionne, associe la structure parallele et remplit les valeurs reelles et virtuelles)
Le fichier doit avoir le format suivant (n est le nombre de valeurs nodales
stockees, x, y, z sont les coordonnees des sommets, compo1... sont les valeurs
des composantes.
n (int)
x y [z] compo1 [compo2 [compo3 ... ]] (type double)
Protected Member Functions
Champ_base & le_champ (void) override=0
const Champ_base & le_champ (void) const override=0
void value_interpolation (const DoubleTab &positions, const ArrOfInt &cells, const DoubleTab &values, DoubleTab &resu, int ncomp=-1) const override
Protected Member Functions inherited from Champ_implementation_sommet_base
virtual void value_interpolation (const DoubleTab &positions, const ArrOfInt &cells, const DoubleTab &values, DoubleTab &resu, int ncomp=-1) const =0
DoubleTab & valeur_aux_sommets_impl (DoubleTab &result) const override
DoubleVect & valeur_aux_sommets_compo_impl (DoubleVect &result, int ncomp) const override
DoubleTab & trace (const Frontiere_dis_base &fr, const DoubleTab &y, DoubleTab &x, int distant) const
Protected Member Functions inherited from Champ_implementation_base
virtual DoubleTab & valeur_aux_sommets_impl (DoubleTab &result) const =0
virtual DoubleVect & valeur_aux_sommets_compo_impl (DoubleVect &result, int ncomp) const =0
const Zone_VF & get_zone_dis (void) const
const Zone & get_zone_geom (void) const
virtual Champ_base & le_champ (void)=0
virtual const Champ_base & le_champ (void) const =0
Private Member Functions
virtual double form_function (const ArrOfDouble &position, const IntTab &les_elems, const DoubleTab &nodes, ArrOfInt &index, int cell, int ddl) const
Detailed Description
Definition at line 22 of file Champ_implementation_P1.h.
Constructor & Destructor Documentation
~Champ_implementation_P1()
Champ_implementation_P1::~Champ_implementation_P1 () inline override
Definition at line 30 of file Champ_implementation_P1.h.
{ };
Member Function Documentation
form_function()
double Champ_implementation_P1::form_function (const ArrOfDouble & position, const IntTab & les_elems, const DoubleTab & nodes, ArrOfInt & index, int cell, int ddl) const private virtual
Definition at line 20 of file Champ_implementation_P1.cpp.
{
  int nb_nodes_per_cell = les_elems.dimension(1);
  assert(ddl < nb_nodes_per_cell);
  for (int i=0; i<nb_nodes_per_cell; i++)
    index[i] = les_elems(cell,(i+ddl)%nb_nodes_per_cell);
  if (nb_nodes_per_cell==2)
    {
      double num=0.;
      double den=0.;
      for (int d=0; d<Objet_U::dimension; d++)
        {
          num+=(position[d]-nodes(index[0],d))*(position[d]-nodes(index[0],d));
          den+=(nodes(index[1],d)-nodes(index[0],d))*(nodes(index[1],d)-nodes(index[0],d));
        }
      double res= 1.-sqrt(num/den);
// Cerr<<"ii "<<res<<" "<<index[0]<<" "<<ddl<<" "<<(ddl)%nb_nodes_per_cell<<finl;
      return res;
    }
  double num = 0.;
  double den = 0.;
  if (Objet_U::dimension == 2)
    {
      den = (nodes(index[2],0) - nodes(index[1],0)) * (nodes(index[0],1) - nodes(index[1],1))
            - (nodes(index[2],1) - nodes(index[1],1)) * (nodes(index[0],0) - nodes(index[1],0));
      num = (nodes(index[2],0) - nodes(index[1],0)) * (position[1] - nodes(index[1],1))
            - (nodes(index[2],1) - nodes(index[1],1)) * (position[0] - nodes(index[1],0));
    }
  else if (Objet_U::dimension == 3)
    {
      double xp = (nodes(index[2],1) - nodes(index[1],1)) * (nodes(index[0],2) - nodes(index[1],2))
                  - (nodes(index[2],2) - nodes(index[1],2)) * (nodes(index[0],1) - nodes(index[1],1));
      double yp = (nodes(index[2],2) - nodes(index[1],2)) * (nodes(index[0],0) - nodes(index[1],0))
                  - (nodes(index[2],0) - nodes(index[1],0)) * (nodes(index[0],2) - nodes(index[1],2));
      double zp = (nodes(index[2],0) - nodes(index[1],0)) * (nodes(index[0],1) - nodes(index[1],1))
                  - (nodes(index[2],1) - nodes(index[1],1)) * (nodes(index[0],0) - nodes(index[1],0));
      den = xp * (nodes(index[3],0) - nodes(index[1],0))
            + yp * (nodes(index[3],1) - nodes(index[1],1))
            + zp * (nodes(index[3],2) - nodes(index[1],2));
      xp = (nodes(index[2],1) - nodes(index[1],1)) * (position[2] - nodes(index[1],2))
           - (nodes(index[2],2) - nodes(index[1],2)) * (position[1] - nodes(index[1],1));
      yp = (nodes(index[2],2) - nodes(index[1],2)) * (position[0] - nodes(index[1],0))
           - (nodes(index[2],0) - nodes(index[1],0)) * (position[2] - nodes(index[1],2));
      zp = (nodes(index[2],0) - nodes(index[1],0)) * (position[1] - nodes(index[1],1))
           - (nodes(index[2],1) - nodes(index[1],1)) * (position[0] - nodes(index[1],0));
      num = xp * (nodes(index[3],0) - nodes(index[1],0))
            + yp * (nodes(index[3],1) - nodes(index[1],1))
            + zp * (nodes(index[3],2) - nodes(index[1],2));
    }
  else
    {
      Cerr << "Error in Champ_implementation_P1::form_function : Invalid dimension" << finl;
      Process::exit();
    }
  assert(den != 0.);
  double result = num/den;
  if ((result < -Objet_U::precision_geom) || (result > 1.+Objet_U::precision_geom))
    {
      Cerr << "WARNING: The barycentric coordinate of point :" << finl;
      Cerr << "x= " << position[0] << " y=" << position[1];
      if (Objet_U::dimension == 3)
        {
          Cerr << " z=" << position[3];
        }
      Cerr << finl;
      Cerr << "is not between 0 and 1 : " << result << finl;
      Cerr << "On the element " << cell << " of the processor " << Process::me() << finl;
#ifndef NDEBUG
      Process::exit();
#endif
    }
  return result;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Process::exit(), finl, Process::me(), and Objet_U::precision_geom.
Referenced by value_interpolation().
init_from_file()
void Champ_implementation_P1::init_from_file (DoubleTab & val, const Domaine & dom, int nb_comp, double tolerance, Entree & input) static
Initialise le tableau de valeurs aux sommets du domaine dom a partir de valeurs lues dans "input".
(on dimensionne, associe la structure parallele et remplit les valeurs reelles et virtuelles)
Le fichier doit avoir le format suivant (n est le nombre de valeurs nodales
stockees, x, y, z sont les coordonnees des sommets, compo1... sont les valeurs
des composantes.
n (int)
x y [z] compo1 [compo2 [compo3 ... ]] (type double)
< points to the dim first elements of "tmp" (coordinates of the node)
< number of times this coordinate has been found
Definition at line 158 of file Champ_implementation_P1.cpp.
{
  val.resize(0, nb_comp);
  dom.creer_tableau_sommets(val, Array_base::NOCOPY_NOINIT);
// Construction d'un octree avec les sommets du domaine:
  const DoubleTab& coord = dom.coord_sommets();
  Octree_Double octree;
  octree.build_nodes(coord, 0 /* do not include virtual nodes */);
// Lecture des valeurs dans input
  int nb_val_lues;
  input >> nb_val_lues;
  const int dim = coord.dimension(1);
  const int tmp_size = dim + nb_comp;
  ArrOfDouble tmp(tmp_size);
  ArrOfDouble node_coord; //!< points to the dim first elements of "tmp" (coordinates of the node)
  node_coord.ref_array(tmp, 0 /* start index */, dim /* size */);
  ArrOfInt node_list;
  node_list.set_smart_resize(1);
  ArrOfInt count(dom.nb_som()); //!< number of times this coordinate has been found
  for (int i_val = 0; i_val < nb_val_lues; i_val++)
    {
      input.get(tmp.addr(), tmp_size);
// first call returns more points (some might be at a larger distance)
      octree.search_elements_box(node_coord, tolerance, node_list);
      octree.search_nodes_close_to(node_coord, coord, node_list, tolerance);
      const int n = node_list.size_array();
      if (n > 1)
        {
          Cerr << "Error in Champ_som_lu::readOn: point " << node_coord
               << " corresponds to " << node_list.size_array()
               << " nodes in the geometry within the specified tolerance" << finl;
          Process::exit();
        }
      if (n == 1)
        {
          const int node_index = node_list[0];
          count[node_index]++;
          for (int i = 0; i < nb_comp; i++)
            val(node_index, i) = tmp[dim + i];
        }
      else
        {
// Ce sommet n'est pas sur ce processeur...
        }
    }
  if (dom.nb_som() > 0 && min_array(count) == 0)
    {
      Cerr << "Error in Champ_som_lu::readOn: some coordinates were not found in the file" << finl;
      Process::exit();
    }
  val.echange_espace_virtuel();
}
References TRUSTArray< _TYPE_ >::addr(), Octree_Double::build_nodes(), Cerr, Domaine::coord_sommets(), Domaine::creer_tableau_sommets(), TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, Entree::get(), min_array(), Domaine::nb_som(), Array_base::NOCOPY_NOINIT, TRUSTArray< _TYPE_ >::ref_array(), TRUSTTab< _TYPE_ >::resize(), Octree_Double::search_elements_box(), Octree_Double::search_nodes_close_to(), TRUSTArray< _TYPE_ >::set_smart_resize(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Champ_som_lu::readOn().
le_champ() [1/2]
const Champ_base & Champ_implementation_P1::le_champ (void) const override protected pure virtual
Implements Champ_implementation_sommet_base.
Implemented in Champ_Fonc_P1_base, and Champ_Inc_P1_base.
le_champ() [2/2]
Champ_base & Champ_implementation_P1::le_champ (void) override protected pure virtual
Implements Champ_implementation_sommet_base.
Implemented in Champ_Fonc_P1_base, and Champ_Inc_P1_base.
value_interpolation()
void Champ_implementation_P1::value_interpolation (const DoubleTab & positions, const ArrOfInt & cells, const DoubleTab & values, DoubleTab & resu, int ncomp = -1) const override protected virtual
Implements Champ_implementation_sommet_base.
Definition at line 109 of file Champ_implementation_P1.cpp.
{
  const Zone&      zone              = get_zone_geom();
  const IntTab&    les_elems         = zone.les_elems();
  const DoubleTab& nodes = zone.domaine().les_sommets();
  const int nb_nodes_per_cell = zone.nb_som_elem(), N = resu.line_size();
  ArrOfInt index(nb_nodes_per_cell);
  ArrOfDouble position(Objet_U::dimension);
  resu = 0;
  for (int ic=0; ic<cells.size_array(); ic++)
    {
      int cell = cells[ic];
      if (cell<0) continue;
      for (int k=0; k<Objet_U::dimension; k++)
        position[k] = positions(ic,k);
      assert(cell >= 0);
      assert(cell < les_elems.dimension_tot(0));
      if (ncomp != -1)
        {
          for (int j = 0; j < nb_nodes_per_cell; j++)
            {
              int node = les_elems(cell, j);
              resu(ic) += values(node, ncomp) * form_function(position,les_elems,nodes,index,cell,j);
            }
        }
      else
        {
          assert(values.line_size() == N);
          for (int j = 0; j < nb_nodes_per_cell; j++)
            {
              double weight = form_function(position,les_elems,nodes,index,cell,j);
              int node = les_elems(cell, j);
              for (int k = 0; k < N; k++)
                resu(ic, k) += values(node, k) * weight;
            }
        }
    }
}
References Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), Zone::domaine(), form_function(), Champ_implementation_base::get_zone_geom(), Zone::les_elems(), Domaine::les_sommets(), TRUSTVect< _TYPE_ >::line_size(), Zone::nb_som_elem(), and TRUSTArray< _TYPE_ >::size_array().
The documentation for this class was generated from the following files:
src/Kernel/Champs_dis/Champ_implementation_P1.h
src/Kernel/Champs_dis/Champ_implementation_P1.cpp