TRUST: Loi_Etat_GP_base Class Reference
Loi_Etat_GP_base Class Reference
classe Loi_Etat_GP_base
Cette classe represente la loi d'etat base pour les gaz parfaits.
Elle definit un fluide dilatable dont la loi d'etat est :
Pth = rho*R*T
#include <Loi_Etat_GP_base.h>
Public Member Functions
~Loi_Etat_GP_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Loi_Etat_GP_base ()
const Nom type_fluide () const
Renvoie le type de fluide associe.
void associer_fluide (const Fluide_Dilatable_base &)
Associe le fluide a la loi d'etat.
void calculer_lambda ()
Calcule la conductivite.
void calculer_alpha ()
Calcule la diffusivite.
void remplir_T ()
Remplit le tableau de la temperature : T=temp+273.15.
void calculer_Cp ()
Calcule le Cp
NE FAIT RIEN : le Cp est constant.
virtual void calculer_masse_volumique ()
Calcule la masse volumique.
virtual void initialiser ()
Initialise la loi d'etat : calcul Pth.
virtual double calculer_masse_volumique (double, double) const
virtual double inverser_Pth (double, double)
Calcule la pression avec la temperature et la masse volumique.
double R () const
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Loi_Etat_GP_base & self_cast (Objet_U &)
static const Loi_Etat_GP_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
double Cp_
double R_
Detailed Description
classe Loi_Etat_GP_base
Cette classe represente la loi d'etat base pour les gaz parfaits.
Elle definit un fluide dilatable dont la loi d'etat est :
Pth = rho*R*T
Definition at line 42 of file Loi_Etat_GP_base.h.
Constructor & Destructor Documentation
Loi_Etat_GP_base::~Loi_Etat_GP_base ()
Definition at line 30 of file Loi_Etat_GP_base.cpp.
Loi_Etat_GP_base::Loi_Etat_GP_base ()
Definition at line 33 of file Loi_Etat_GP_base.cpp.
: Cp_(-1), R_(-1) { }
Member Function Documentation
void Loi_Etat_GP_base::associer_fluide (const Fluide_Dilatable_base & fl) [virtual]
Associe le fluide a la loi d'etat.
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_Melange_GP_base.
Definition at line 79 of file Loi_Etat_GP_base.cpp.
References Cp_, and Loi_Etat_base::le_fluide.
{
  Loi_Etat_base::associer_fluide(fl);
  le_fluide->set_Cp(Cp_);
}
void Loi_Etat_GP_base::calculer_alpha () [virtual]
Calcule la diffusivite.
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_Binaire_GP_base, and Loi_Etat_Multi_GP_base.
Definition at line 230 of file Loi_Etat_GP_base.cpp.
References Cp_, DoubleVect::echange_espace_virtuel(), Loi_Etat_base::le_fluide, IntVect::line_size(), Objet_U::que_suis_je(), ref_cast, DoubleVect::size(), sub_type, Deriv_Champ_Don_base::valeur(), and Champ_Don::valeurs().
{
  const Champ_Don& lambda = le_fluide->conductivite();
  const DoubleTab& tab_lambda = lambda.valeurs();
  Champ_Don& alpha=le_fluide->diffusivite();
  DoubleTab& tab_alpha = le_fluide->diffusivite().valeurs();
  const DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  int isVDF=0;
  if (alpha.valeur().que_suis_je()=="Champ_Fonc_P0_VDF") isVDF = 1;
  int i, n=tab_alpha.size();
  if (isVDF)
    {
      if (sub_type(Champ_Uniforme,lambda.valeur()))
        {
          double lambda0 = tab_lambda(0,0);
          for (i=0 ; i<n ; i++) tab_alpha(i,0) = lambda0 / (tab_rho(i,0) * Cp_);
        }
      else
        {
          for (i=0 ; i<n ; i++) tab_alpha(i,0) = tab_lambda(i,0) / (tab_rho(i,0) * Cp_);
        }
    }
  else
    {
      const IntTab& elem_faces=ref_cast(Zone_VF,le_fluide->vitesse().zone_dis_base()).elem_faces();
      double rhoelem;
      int face, nfe = elem_faces.line_size();
      if (sub_type(Champ_Uniforme,lambda.valeur()))
        {
          double lambda0 = tab_lambda(0,0);
          for (i=0 ; i<n ; i++)
            {
              rhoelem=0;
              for (face=0; face<nfe; face++) rhoelem += tab_rho(elem_faces(i,face),0);
              rhoelem /= nfe;
              tab_alpha(i,0) = lambda0 / ( rhoelem * Cp_ );
            }
        }
      else
        {
          for (i=0 ; i<n ; i++)
            {
              rhoelem=0;
              for (face=0; face<nfe; face++) rhoelem += tab_rho(elem_faces(i,face),0);
              rhoelem /= nfe;
              tab_alpha(i,0) = tab_lambda(i,0) / ( rhoelem * Cp_ );
            }
        }
    }
  tab_alpha.echange_espace_virtuel();
}
void Loi_Etat_GP_base::calculer_Cp () [virtual]
Calcule le Cp
NE FAIT RIEN : le Cp est constant.
Implements Loi_Etat_base.
Reimplemented in Loi_Etat_Binaire_GP_base, and Loi_Etat_Multi_GP_base.
Definition at line 152 of file Loi_Etat_GP_base.cpp.
{
  /* Do nothing */
}
void Loi_Etat_GP_base::calculer_lambda () [virtual]
Calcule la conductivite.
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_Binaire_GP_base, and Loi_Etat_Multi_GP_base.
Definition at line 171 of file Loi_Etat_GP_base.cpp.
References Cerr, Cp_, DoubleVect::echange_espace_virtuel(), Process::exit(), finl, Loi_Etat_base::le_fluide, Champ_Don_base::mettre_a_jour(), Loi_Etat_base::Pr_, DoubleVect::size(), sub_type, Loi_Etat_base::temperature_, Champ_base::temps(), Deriv_Champ_Don_base::valeur(), and Champ_Don::valeurs().
{
  const Champ_Don& mu = le_fluide->viscosite_dynamique();
  const DoubleTab& tab_mu = mu.valeurs();
  Champ_Don& lambda = le_fluide->conductivite();
  DoubleTab& tab_lambda =lambda.valeurs();
  int i, n=tab_lambda.size();
// La conductivite est soit un champ uniforme soit calculee a partir de la viscosite dynamique et du Pr
  if (sub_type(Champ_Fonc_Tabule,lambda.valeur()))
    {
      lambda.valeur().mettre_a_jour(temperature_.valeur().temps());
      return;
    }
  if (!sub_type(Champ_Uniforme,lambda.valeur()))
    {
      if (sub_type(Champ_Uniforme,mu.valeur()))
        {
          double mu0 = tab_mu(0,0);
          for (i=0 ; i<n ; i++) tab_lambda(i,0) = mu0 * Cp_ / Pr_;
        }
      else
        {
          for (i=0 ; i<n ; i++) tab_lambda(i,0) = tab_mu(i,0) * Cp_ / Pr_;
        }
    }
  else
    {
      if (sub_type(Champ_Uniforme,mu.valeur()))
        {
          tab_lambda(0,0) = mu(0,0) * Cp_ / Pr_;
        }
      else
        {
          Cerr << finl ;
          Cerr << "If lambda is of type Champ_Uniform, mu must also be of type Champ_Uniforme !"<< finl;
          Cerr << "If needed, you can use a Champ_Fonc_Fonction or a Champ_Fonc_Tabule with a constant for mu."<< finl ;
          Cerr << finl ;
          Process::exit();
        }
    }
  tab_lambda.echange_espace_virtuel();
}
double Loi_Etat_GP_base::calculer_masse_volumique (double P, double T) const [virtual]
Implements Loi_Etat_base.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_WC, and Loi_Etat_Multi_GP_WC.
Definition at line 284 of file Loi_Etat_GP_base.cpp.
References Cerr, Process::exit(), finl, inf_ou_egal(), and R_.
{
  if (inf_ou_egal(T,0))
    {
      Cerr << finl << "Error, we find a temperature of " << T << " !" << finl;
      Cerr << "Either your calculation has diverged or you don't define" << finl;
      Cerr << "temperature in Kelvin somewhere in your data file." << finl;
      Cerr << "Check your data file." << finl;
      Process::exit();
    }
  return P / ( R_ * T );
}
void Loi_Etat_GP_base::calculer_masse_volumique () [virtual]
Calcule la masse volumique.
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_WC, and Loi_Etat_Multi_GP_WC.
Definition at line 330 of file Loi_Etat_GP_base.cpp.
{
  Loi_Etat_base::calculer_masse_volumique();
}
virtual int Loi_Etat_GP_base::duplique () const [pure virtual]
Implements Loi_Etat_base.
Implemented in Loi_Etat_Binaire_GP_base, Loi_Etat_Melange_GP_base, Loi_Etat_Mono_GP_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_WC, and Loi_Etat_Multi_GP_WC.
const Type_info * Loi_Etat_GP_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_Melange_GP_base, Loi_Etat_Mono_GP_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_WC, and Loi_Etat_Multi_GP_WC.
Definition at line 30 of file Loi_Etat_GP_base.cpp.
const Type_info * Loi_Etat_GP_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_Melange_GP_base, Loi_Etat_Mono_GP_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_WC, and Loi_Etat_Multi_GP_WC.
Definition at line 30 of file Loi_Etat_GP_base.cpp.
void Loi_Etat_GP_base::initialiser () [virtual]
Initialise la loi d'etat : calcul Pth.
Implements Loi_Etat_base.
Definition at line 99 of file Loi_Etat_GP_base.cpp.
References DoubleTab::dimension(), Loi_Etat_base::le_fluide, DoubleVect::size(), DoubleVect::size_totale(), Loi_Etat_base::tab_rho_n, Loi_Etat_base::temperature_, and Champ_Don::valeurs().
{
  const DoubleTab& tab_Temp = le_fluide->inco_chaleur().valeurs();
  const DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  int i, ntot=tab_Temp.size_totale();
  DoubleTab& tab_T = temperature_.valeurs();
  assert(tab_T.size()==tab_Temp.dimension(0));
  tab_rho_n=tab_Temp;
  for (i=0 ; i<ntot ; i++)
    {
      tab_rho_n(i) = tab_rho(i,0);
      tab_T(i,0) = tab_Temp(i,0);
    }
}
double Loi_Etat_GP_base::inverser_Pth (double T, double rho) [virtual]
Calcule la pression avec la temperature et la masse volumique.
Implements Loi_Etat_base.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_rhoT_GP_QC, and Loi_Etat_GP_WC.
Definition at line 311 of file Loi_Etat_GP_base.cpp.
References R_.
{
  return rho * R_ * T;
}
Sortie & Loi_Etat_GP_base::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_Melange_GP_base, Loi_Etat_Mono_GP_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_WC, and Loi_Etat_Multi_GP_WC.
Definition at line 35 of file Loi_Etat_GP_base.cpp.
References finl, and Objet_U::que_suis_je().
{
  os <<que_suis_je()<< finl;
  return os;
}
double Loi_Etat_GP_base::R () const [inline]
Definition at line 60 of file Loi_Etat_GP_base.h.
References R_.
Referenced by EDO_Pression_th_VDF_Gaz_Parfait::resoudre().
{ return R_; }
Entree & Loi_Etat_GP_base::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_Melange_GP_base, Loi_Etat_Mono_GP_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_WC, and Loi_Etat_Multi_GP_WC.
Definition at line 41 of file Loi_Etat_GP_base.cpp.
{
  return is;
}
void Loi_Etat_GP_base::remplir_T () [virtual]
Remplit le tableau de la temperature : T=temp+273.15.
Implements Loi_Etat_base.
Definition at line 129 of file Loi_Etat_GP_base.cpp.
References Loi_Etat_base::le_fluide, DoubleVect::size_totale(), Loi_Etat_base::temperature_, and Champ_Don::valeurs().
{
  const DoubleTab& tab_Temp = le_fluide->inco_chaleur().valeurs();
  int i, ntot=tab_Temp.size_totale();
  DoubleTab& tab_T = temperature_.valeurs();
  for (i=0 ; i<ntot ; i++) tab_T(i,0) = tab_Temp(i,0);
}
const Loi_Etat_GP_base & Loi_Etat_GP_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_Melange_GP_base, Loi_Etat_Mono_GP_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_WC, and Loi_Etat_Multi_GP_WC.
Definition at line 30 of file Loi_Etat_GP_base.cpp.
Loi_Etat_GP_base & Loi_Etat_GP_base::self_cast (Objet_U & r) [static]
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_Melange_GP_base, Loi_Etat_Mono_GP_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_WC, and Loi_Etat_Multi_GP_WC.
Definition at line 30 of file Loi_Etat_GP_base.cpp.
const Nom Loi_Etat_GP_base::type_fluide () const [virtual]
Renvoie le type de fluide associe.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Implements Loi_Etat_base.
Reimplemented in Loi_Etat_Binaire_GP_base.
Definition at line 60 of file Loi_Etat_GP_base.cpp.
{
  return "Gaz_Parfait";
}
Member Data Documentation
double Loi_Etat_GP_base::Cp_ [protected]
Definition at line 63 of file Loi_Etat_GP_base.h.
Referenced by associer_fluide(), calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_lambda(), calculer_lambda(), Loi_Etat_rhoT_GP_QC::readOn(), Loi_Etat_Multi_GP_QC::readOn(), and Loi_Etat_Mono_GP_base::readOn().
const Type_info Loi_Etat_GP_base::info_obj [static]
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_Melange_GP_base, Loi_Etat_Mono_GP_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_WC, and Loi_Etat_Multi_GP_WC.
Definition at line 44 of file Loi_Etat_GP_base.h.
double Loi_Etat_GP_base::R_ [protected]
Definition at line 63 of file Loi_Etat_GP_base.h.
Referenced by calculer_masse_volumique(), inverser_Pth(), R(), and Loi_Etat_Mono_GP_base::readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat_GP_base.h
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat_GP_base.cpp