TRUST: EcrFicPartageMPIIO Class Reference
EcrFicPartageMPIIO Class Reference
Class to use MPI-IO to write in a single file.
#include <EcrFicPartageMPIIO.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
EcrFicPartageMPIIO ()
~EcrFicPartageMPIIO () override
EcrFicPartageMPIIO (const char *name, std::_Ios_Openmode mode=ios::out)
int ouvrir (const char *name, std::_Ios_Openmode mode=ios::out) override
void close ()
Sortie & lockfile () override
Sortie & unlockfile () override
Sortie & syncfile () override
Sortie & flush () override
void check ()
Sortie & operator<< (const Separateur &ob) override
Sortie & operator<< (const int ob) override
Sortie & operator<< (const unsigned ob) override
Sortie & operator<< (const long ob) override
Sortie & operator<< (const float ob) override
Sortie & operator<< (const double ob) override
Sortie & operator<< (const Objet_U &ob) override
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
Sortie & operator<< (const char *ob) override
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
Sortie & operator<< (const std::string &str) override
int put (const unsigned *ob, int n, int pas) override
int put (const int *ob, int n, int pas) override
int put (const long *ob, int n, int pas) override
int put (const float *ob, int n, int pas) override
int put (const double *ob, int n, int pas) override
Public Member Functions inherited from SFichier
SFichier ()
~SFichier ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
SFichier (const char *name, std::_Ios_Openmode mode=ios::out)
Public Member Functions inherited from Sortie_Fichier_base
~Sortie_Fichier_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Sortie_Fichier_base ()
Sortie_Fichier_base (const Sortie_Fichier_base &)=default
Sortie_Fichier_base (const char *name, std::_Ios_Openmode mode=ios::out)
ofstream & get_ofstream ()
void close ()
void precision (int pre) override
virtual int get_precision ()
void setf (std::_Ios_Fmtflags code) override
bool is_open ()
virtual int ouvrir (const char *name, std::_Ios_Openmode mode=ios::out)
Sortie & flush () override
Force l'ecriture sur disque des donnees dans le tampon
Utilise l'implementation de la classe ofstream.
Public Member Functions inherited from Sortie
Sortie ()
Sortie (ostream &os)
Sortie (const Sortie &os)
Sortie & operator= (ostream &os)
Sortie & operator= (Sortie &os)
ostream & get_ostream ()
const ostream & get_ostream () const
void set_ostream (ostream *os)
void set_col_width (const int)
Sortie & operator<< (ostream &(*f)(ostream &))
Sortie & operator<< (Sortie &(*f)(Sortie &))
Sortie & operator<< (ios &(*f)(ios &))
virtual Sortie & flush ()
virtual Sortie & lockfile ()
virtual Sortie & unlockfile ()
virtual Sortie & syncfile ()
virtual void setf (std::_Ios_Fmtflags)
virtual void precision (int)
virtual Sortie & operator<< (const Separateur &)
virtual Sortie & operator<< (const Objet_U &ob)
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
virtual Sortie & operator<< (const int ob)
virtual Sortie & operator<< (const unsigned ob)
virtual Sortie & operator<< (const long ob)
virtual Sortie & operator<< (const float ob)
virtual Sortie & operator<< (const double ob)
virtual Sortie & operator<< (const char *ob)
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
virtual Sortie & operator<< (const std::string &str)
virtual int add_col (const double ob)
virtual int add_col (const char *ob)
virtual int put (const unsigned *ob, int n, int nb_colonnes=1)
virtual int put (const int *ob, int n, int nb_colonnes=1)
virtual int put (const float *ob, int n, int nb_colonnes=1)
virtual int put (const double *ob, int n, int nb_colonnes=1)
virtual int put (const long *ob, int n, int nb_colonnes=1)
virtual ~Sortie ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
int is_bin ()
bool has_ostream () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static EcrFicPartageMPIIO & self_cast (Objet_U &)
static const EcrFicPartageMPIIO & self_cast (const Objet_U &)
Static Public Member Functions inherited from SFichier
static Objet_U * cree_instance ()
static const Type_info * info ()
static SFichier & self_cast (Objet_U &)
static const SFichier & self_cast (const Objet_U &)
Static Public Member Functions inherited from Sortie_Fichier_base
static const Type_info * info ()
static Sortie_Fichier_base & self_cast (Objet_U &)
static const Sortie_Fichier_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from SFichier
static const Type_info info_obj
Static Public Attributes inherited from Sortie_Fichier_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from SFichier
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Sortie_Fichier_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void write (MPI_Datatype, const void *)
int put (MPI_Datatype, const void *, int)
Private Attributes
MPI_File mpi_file_
MPI_Status mpi_status_
MPI_Offset disp_
Displacement of the individual pointers (in bytes)
Additional Inherited Members
Protected Attributes inherited from Sortie_Fichier_base
ofstream * ofstream_
Protected Attributes inherited from Sortie
int bin_
int col_width_
Detailed Description
Class to use MPI-IO to write in a single file.
Definition at line 31 of file EcrFicPartageMPIIO.h.
Constructor & Destructor Documentation
EcrFicPartageMPIIO() [1/2]
EcrFicPartageMPIIO::EcrFicPartageMPIIO ()
< Binaire par defaut
Definition at line 55 of file EcrFicPartageMPIIO.cpp.
                                       : SFichier()
{
  bin_ = 1; //!< Binaire par defaut
#ifdef MPI_
  mpi_file_=NULL;
#endif
}
References Sortie::bin_, and mpi_file_.
~EcrFicPartageMPIIO()
EcrFicPartageMPIIO::~EcrFicPartageMPIIO () override
Definition at line 62 of file EcrFicPartageMPIIO.cpp.
{
  close();
}
References close().
EcrFicPartageMPIIO() [2/2]
EcrFicPartageMPIIO::EcrFicPartageMPIIO (const char * name, std::_Ios_Openmode mode = ios::out)
Definition at line 67 of file EcrFicPartageMPIIO.cpp.
{
  ouvrir(name, mode);
}
References ouvrir().
Member Function Documentation
check()
void EcrFicPartageMPIIO::check ()
< Relative position
< Absolute position
Definition at line 111 of file EcrFicPartageMPIIO.cpp.
{
  if (Process::me()>0)
    {
      Cerr << "Only master process can call EcrFicPartageMPIIO::operator <<(...)" << finl;
      exit();
    }
  MPI_Offset offset; //!< Relative position
  MPI_File_get_position(mpi_file_, &offset);
  MPI_Offset disp;   //!< Absolute position
  MPI_File_get_byte_offset(mpi_file_, offset, &disp);
  if (disp_!=disp)
    {
      Cerr << "Error in EcrFicPartageMPIIO::check()" << finl;
      Cerr << "Decalage : disp_= " << (int)disp_ << " disp=" << (int)disp << finl;
      Cerr << "Contact TRUST support." << finl;
    }
}
References Cerr, disp_, Process::exit(), finl, Process::me(), and mpi_file_.
Referenced by operator<<(), and write().
close()
void EcrFicPartageMPIIO::close ()
Definition at line 104 of file EcrFicPartageMPIIO.cpp.
{
  if (mpi_file_) MPI_File_close(&mpi_file_);
  disp_=0;
  return;
}
References disp_, and mpi_file_.
Referenced by ~EcrFicPartageMPIIO().
cree_instance()
Objet_U * EcrFicPartageMPIIO::cree_instance () static
Definition at line 26 of file EcrFicPartageMPIIO.cpp.
{
duplique()
int EcrFicPartageMPIIO::duplique () const override virtual
Implements Objet_U.
Definition at line 26 of file EcrFicPartageMPIIO.cpp.
{
flush()
Sortie & EcrFicPartageMPIIO::flush () inline override virtual
Reimplemented from Sortie.
Definition at line 55 of file EcrFicPartageMPIIO.h.
  {
    return *this;
  };
get_info()
const Type_info * EcrFicPartageMPIIO::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 26 of file EcrFicPartageMPIIO.cpp.
{
info()
const Type_info * EcrFicPartageMPIIO::info () static
Definition at line 26 of file EcrFicPartageMPIIO.cpp.
{
lockfile()
Sortie & EcrFicPartageMPIIO::lockfile () inline override virtual
Reimplemented from Sortie.
Definition at line 43 of file EcrFicPartageMPIIO.h.
  {
    return *this;
  };
operator<<() [1/9]
Sortie & EcrFicPartageMPIIO::operator<< (const char * ob) override virtual
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
Reimplemented from Sortie.
Definition at line 162 of file EcrFicPartageMPIIO.cpp.
{
  int size=strlen(ob) + 1;
// int size=strlen(ob);
  for (int i=0; i<size; i++)
    write(MPI_CHAR, &ob[i]);
  return *this;
}
References write().
operator<<() [2/9]
Sortie & EcrFicPartageMPIIO::operator<< (const double ob) override virtual
< ToDo utiliser sprintf
Reimplemented from Sortie.
Definition at line 207 of file EcrFicPartageMPIIO.cpp.
{
  if (bin_)
    write(MPI_DOUBLE, &ob);
  else
    (*this)<<std::to_string(ob).c_str(); //!< ToDo utiliser sprintf
  return *this;
}
References Sortie::bin_, and write().
operator<<() [3/9]
Sortie & EcrFicPartageMPIIO::operator<< (const float ob) override virtual
Reimplemented from Sortie.
Definition at line 199 of file EcrFicPartageMPIIO.cpp.
{
  if (bin_)
    write(MPI_FLOAT, &ob);
  else
    (*this)<<std::to_string(ob).c_str();
  return *this;
}
References Sortie::bin_, and write().
operator<<() [4/9]
Sortie & EcrFicPartageMPIIO::operator<< (const int ob) override virtual
Reimplemented from Sortie.
Definition at line 176 of file EcrFicPartageMPIIO.cpp.
{
  if (bin_)
    {
#ifdef INT_is_64_
      write(MPI_LONG, &ob);
#else
      write(MPI_INT, &ob);
#endif
    }
  else
    (*this)<<std::to_string(ob).c_str();
  return *this;
}
References Sortie::bin_, and write().
operator<<() [5/9]
Sortie & EcrFicPartageMPIIO::operator<< (const long ob) inline override virtual
Reimplemented from Sortie.
Definition at line 67 of file EcrFicPartageMPIIO.h.
  {
    Cerr << "EcrFicPartageMPIIO::operator<<(...) not implemented." << finl;
    exit();
    return *this;
  };
References Cerr, Process::exit(), and finl.
operator<<() [6/9]
Sortie & EcrFicPartageMPIIO::operator<< (const Objet_U & ob) override virtual
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
Reimplemented from Sortie.
Definition at line 215 of file EcrFicPartageMPIIO.cpp.
{
  ob.printOn(*this);
  check();
  return *this;
}
References check(), and Objet_U::printOn().
operator<<() [7/9]
Sortie & EcrFicPartageMPIIO::operator<< (const Separateur & ob) override virtual
Reimplemented from Sortie.
Definition at line 140 of file EcrFicPartageMPIIO.cpp.
{
  if (bin_)
    {
// On n'ecrit pas les separateurs. Voir Sortie::operator<<(const Separateur& ob)
      check();
    }
  else
    {
      if (ob.get_type() == ob.ENDL)
        (*this)<<"\n";
      else if (ob.get_type() == ob.SPACE)
        (*this)<<" ";
      else
        {
          Cerr << "Unknown separator in EcrFicPartageMPIIO::operator <<" << finl;
          Process::exit();
        }
    }
  return *this;
}
References Sortie::bin_, Cerr, check(), Separateur::ENDL, Process::exit(), finl, Separateur::get_type(), and Separateur::SPACE.
operator<<() [8/9]
Sortie & EcrFicPartageMPIIO::operator<< (const std::string & str) override virtual
Reimplemented from Sortie.
Definition at line 171 of file EcrFicPartageMPIIO.cpp.
{
  return (*this) << str.c_str();
}
operator<<() [9/9]
Sortie & EcrFicPartageMPIIO::operator<< (const unsigned ob) override virtual
Reimplemented from Sortie.
Definition at line 190 of file EcrFicPartageMPIIO.cpp.
{
  if (bin_)
    write(MPI_UNSIGNED, &ob);
  else
    (*this)<<std::to_string(ob).c_str();
  return *this;
}
References Sortie::bin_, and write().
ouvrir()
int EcrFicPartageMPIIO::ouvrir (const char * name, std::_Ios_Openmode mode = ios::out) override virtual
Reimplemented from Sortie_Fichier_base.
Definition at line 71 of file EcrFicPartageMPIIO.cpp.
{
  MPI_Comm mpi_comm;
  if (sub_type(Comm_Group_MPI,PE_Groups::current_group()))
    mpi_comm = ref_cast(Comm_Group_MPI,PE_Groups::current_group()).get_mpi_comm();
  else
    mpi_comm = MPI_COMM_WORLD;
  int MPI_OPEN = mode == ios::app ? MPI_MODE_APPEND : MPI_MODE_CREATE;
  int MPI_MODE = (mode == ios::app || ios::out) ? MPI_MODE_WRONLY : MPI_MODE_RDONLY;
  MPI_CHECK(MPI_File_open(mpi_comm, (char*)name, MPI_OPEN|MPI_MODE, MPI_INFO_NULL, &mpi_file_));
// Set MPI errors fatal:
  MPI_File_set_errhandler(mpi_file_,MPI_ERRORS_ARE_FATAL);
// Set initial displacement:
  disp_=0;
// Ecriture d'un entete specifique pour le build int64 ?
  if (mode==ios::out)
    {
      if (je_suis_maitre())
        {
          Nom marq("INT64");
#ifdef INT_is_64_
          (*this)<<marq.getChar();
#endif
        }
    }
  /*
  else
    {
      Cerr<<"not coded in EcrFicPartageMPIIO::ouvrir"<<finl;
      exit();
    }*/
  return 1;
}
References PE_Groups::current_group(), disp_, Nom::getChar(), Process::je_suis_maitre(), MPI_CHECK, mpi_file_, ref_cast, and sub_type.
Referenced by EcrFicPartageMPIIO().
printOn()
Sortie & EcrFicPartageMPIIO::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 49 of file EcrFicPartageMPIIO.cpp.
{
  throw;
  return s;
}
put() [1/6]
int EcrFicPartageMPIIO::put (const double * ob, int n, int pas) inline override virtual
Reimplemented from Sortie.
Definition at line 103 of file EcrFicPartageMPIIO.h.
  {
    return put(MPI_DOUBLE, ob, n);
  }
References put().
put() [2/6]
int EcrFicPartageMPIIO::put (const float * ob, int n, int pas) inline override virtual
Reimplemented from Sortie.
Definition at line 99 of file EcrFicPartageMPIIO.h.
  {
    return put(MPI_FLOAT, ob, n);
  }
References put().
put() [3/6]
int EcrFicPartageMPIIO::put (const int * ob, int n, int pas) inline override virtual
Reimplemented from Sortie.
Definition at line 83 of file EcrFicPartageMPIIO.h.
  {
#ifdef INT_is_64_
    return put(MPI_LONG, ob, n);
#else
    return put(MPI_INT, ob, n);
#endif
  }
References put().
put() [4/6]
int EcrFicPartageMPIIO::put (const long * ob, int n, int pas) inline override virtual
Reimplemented from Sortie.
Definition at line 92 of file EcrFicPartageMPIIO.h.
  {
    Cerr << "EcrFicPartageMPIIO::put(...) not implemented." << finl;
    exit();
    return 1;
  };
References Cerr, Process::exit(), and finl.
put() [5/6]
int EcrFicPartageMPIIO::put (const unsigned * ob, int n, int pas) inline override virtual
Reimplemented from Sortie.
Definition at line 79 of file EcrFicPartageMPIIO.h.
  {
    return put(MPI_UNSIGNED, ob, n);
  }
References put().
Referenced by put().
put() [6/6]
int EcrFicPartageMPIIO::put (MPI_Datatype MPI_TYPE, const void * ob, int n) private
Definition at line 232 of file EcrFicPartageMPIIO.cpp.
{
  MPI_Datatype etype;
  etype=MPI_TYPE;
  True_int sizeof_etype;
  MPI_Type_size(etype,&sizeof_etype);
// filetype is n etype contigous:
  MPI_Datatype filetype;
  MPI_Type_contiguous(n, etype, &filetype);
  MPI_Type_commit(&filetype);
// Before collecting operations, update disp_ on all processes:
  envoyer_broadcast(disp_, 0);
  MPI_Offset disp_me = disp_ + mppartial_sum(n) * sizeof_etype;
// ROMIO hints:
  if (Process::nproc()>1024)
    {
      char* ROMIO_HINTS=getenv("ROMIO_HINTS");
      if (ROMIO_HINTS==NULL)
        {
          Cerr << "Warning, no ROMIO_HINTS detected on your massive parallel calculation." << finl;
          Cerr << "Performances of MPI I/O could be improved with ROMIO hints." << finl;
          Cerr << "Contact TRUST support." << finl;
        }
    }
// Create info for using hints:
  MPI_Info mpi_info;
  MPI_Info_create(&mpi_info);
  /*
  MPI_Info_set(mpi_info, "romio_cb_read", "enable");
  MPI_Info_set(mpi_info, "romio_cb_write", "enable");
  // Un processus par node s'occupe du buffering:
  MPI_Info_set(mpi_info, "cb_config_list", "*:1");
  // Striping count (max 160 sur LUSTRE):
  Nom striping_factor=(Nom)min(Process::nproc(),160);
  MPI_Info_set(mpi_info, "striping_factor", (char*)striping_factor.getChar());
  // Striping units in bytes (ideal is stripe size = I/O operations):
  Nom striping_unit=(Nom)(n * sizeof_etype);
  MPI_Info_set(mpi_info, "striping_unit", (char*)striping_unit.getChar());
// Example (not used cause machine dependant):
  */
// Set a new view:
  MPI_File_set_view(mpi_file_, disp_me, etype, filetype, (char*)"native", mpi_info);
// Write all:
  statistiques().begin_count(IO_EcrireFicPartageMPIIO_counter_);
  MPI_File_write_all(mpi_file_, (void*)ob, n, etype, MPI_STATUS_IGNORE);
  statistiques().end_count(IO_EcrireFicPartageMPIIO_counter_, n * sizeof_etype);
// Update the position of the pointer file:
  disp_+=mp_sum(n) * sizeof_etype;
// Reset a simple view at this new position:
  MPI_File_set_view(mpi_file_, disp_, MPI_BYTE, MPI_BYTE, (char*)"native", MPI_INFO_NULL);
// Free
  MPI_Info_free(&mpi_info);
  MPI_Type_free(&filetype);
  return 1;
}
References Statistiques::begin_count(), Cerr, disp_, Statistiques::end_count(), envoyer_broadcast(), finl, IO_EcrireFicPartageMPIIO_counter_, Process::mp_sum(), mpi_file_, mppartial_sum(), Process::nproc(), and statistiques().
readOn()
Entree & EcrFicPartageMPIIO::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 43 of file EcrFicPartageMPIIO.cpp.
{
  throw;
  return s;
}
self_cast() [1/2]
const EcrFicPartageMPIIO & EcrFicPartageMPIIO::self_cast (const Objet_U & r) static
Definition at line 26 of file EcrFicPartageMPIIO.cpp.
{
self_cast() [2/2]
EcrFicPartageMPIIO & EcrFicPartageMPIIO::self_cast (Objet_U & r) static
Definition at line 26 of file EcrFicPartageMPIIO.cpp.
{
syncfile()
Sortie & EcrFicPartageMPIIO::syncfile () inline override virtual
Reimplemented from Sortie.
Definition at line 51 of file EcrFicPartageMPIIO.h.
  {
    return *this;
  };
taille_memoire()
unsigned EcrFicPartageMPIIO::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 26 of file EcrFicPartageMPIIO.cpp.
{
unlockfile()
Sortie & EcrFicPartageMPIIO::unlockfile () inline override virtual
Reimplemented from Sortie.
Definition at line 47 of file EcrFicPartageMPIIO.h.
  {
    return *this;
  };
write()
void EcrFicPartageMPIIO::write (MPI_Datatype MPI_TYPE, const void * ob) private
Definition at line 131 of file EcrFicPartageMPIIO.cpp.
{
  True_int size;
  MPI_Type_size(MPI_TYPE, &size);
  MPI_File_write(mpi_file_, (void*)ob, 1, MPI_TYPE, &mpi_status_);
  disp_+=size;
  check();
}
References check(), disp_, mpi_file_, and mpi_status_.
Referenced by operator<<().
Member Data Documentation
disp_
MPI_Offset EcrFicPartageMPIIO::disp_ private
Displacement of the individual pointers (in bytes)
Definition at line 113 of file EcrFicPartageMPIIO.h.
Referenced by check(), close(), ouvrir(), put(), and write().
info_obj
const Type_info EcrFicPartageMPIIO::info_obj static
Definition at line 34 of file EcrFicPartageMPIIO.h.
mpi_file_
MPI_File EcrFicPartageMPIIO::mpi_file_ private
Definition at line 111 of file EcrFicPartageMPIIO.h.
Referenced by check(), close(), EcrFicPartageMPIIO(), ouvrir(), put(), and write().
mpi_status_
MPI_Status EcrFicPartageMPIIO::mpi_status_ private
Definition at line 112 of file EcrFicPartageMPIIO.h.
Referenced by write().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/EcrFicPartageMPIIO.h
src/Kernel/Utilitaires/EcrFicPartageMPIIO.cpp