TRUST: Traitement_particulier_Solide_base Class Reference
Traitement_particulier_Solide_base Class Reference abstract
classe Traitement_particulier_Solide_base
#include <Traitement_particulier_Solide_base.h>
Public Member Functions
Traitement_particulier_Solide_base ()
~Traitement_particulier_Solide_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_eqn (const Equation_base &)
virtual void preparer_calcul_particulier (void)=0
virtual void post_traitement_particulier (void)=0
virtual Entree & lire (Entree &is)=0
virtual void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double)=0
void creer_champ (const Motcle &) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static const Type_info * info ()
static Traitement_particulier_Solide_base & self_cast (Objet_U &)
static const Traitement_particulier_Solide_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Conduction mon_equation
Private Attributes
Champs_compris champs_compris_
Detailed Description
classe Traitement_particulier_Solide_base
Definition at line 36 of file Traitement_particulier_Solide_base.h.
Constructor & Destructor Documentation
Traitement_particulier_Solide_base()
Traitement_particulier_Solide_base::Traitement_particulier_Solide_base ()
Definition at line 19 of file Traitement_particulier_Solide_base.cpp.
~Traitement_particulier_Solide_base()
Traitement_particulier_Solide_base::~Traitement_particulier_Solide_base () override
Definition at line 19 of file Traitement_particulier_Solide_base.cpp.
Member Function Documentation
associer_eqn()
void Traitement_particulier_Solide_base::associer_eqn (const Equation_base & eqn) virtual
Definition at line 33 of file Traitement_particulier_Solide_base.cpp.
{
  mon_equation = ref_cast(Conduction,eqn);
}
References mon_equation, and ref_cast.
Referenced by Traitement_particulier_Solide::associer_eqn().
creer_champ()
void Traitement_particulier_Solide_base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
Definition at line 38 of file Traitement_particulier_Solide_base.cpp.
{
}
en_cours_de_resolution()
virtual void Traitement_particulier_Solide_base::en_cours_de_resolution (int , DoubleTab & , DoubleTab & , double) pure virtual
Implemented in Traitement_particulier_Solide_canal.
Referenced by Traitement_particulier_Solide::en_cours_de_resolution().
get_champ()
const Champ_base & Traitement_particulier_Solide_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Definition at line 42 of file Traitement_particulier_Solide_base.cpp.
{
  return champs_compris_.get_champ(nom);
}
References champs_compris_, and Champs_compris::get_champ().
get_info()
const Type_info * Traitement_particulier_Solide_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Traitement_particulier_Solide_canal, and Traitement_particulier_Solide_canal_VDF.
Definition at line 19 of file Traitement_particulier_Solide_base.cpp.
get_noms_champs_postraitables()
void Traitement_particulier_Solide_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
Definition at line 47 of file Traitement_particulier_Solide_base.cpp.
{
  if (opt==DESCRIPTION)
    Cerr<<"Traitement_particulier_Solide_base : <<"<<champs_compris_.liste_noms_compris()<<finl;
  else
    nom.add(champs_compris_.liste_noms_compris());
}
References Vect_Nom::add(), Cerr, champs_compris_, DESCRIPTION, finl, and Champs_compris::liste_noms_compris().
info()
const Type_info * Traitement_particulier_Solide_base::info () static
Definition at line 19 of file Traitement_particulier_Solide_base.cpp.
lire()
virtual Entree & Traitement_particulier_Solide_base::lire (Entree & is) pure virtual
Implemented in Traitement_particulier_Solide_canal, and Traitement_particulier_Solide_canal_VDF.
Referenced by Traitement_particulier_Solide::lire().
post_traitement_particulier()
virtual void Traitement_particulier_Solide_base::post_traitement_particulier (void) pure virtual
Implemented in Traitement_particulier_Solide_canal_VDF, and Traitement_particulier_Solide_canal.
Referenced by Traitement_particulier_Solide::post_traitement_particulier().
preparer_calcul_particulier()
virtual void Traitement_particulier_Solide_base::preparer_calcul_particulier (void) pure virtual
Implemented in Traitement_particulier_Solide_canal.
Referenced by Traitement_particulier_Solide::preparer_calcul_particulier().
printOn()
Sortie & Traitement_particulier_Solide_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Traitement_particulier_Solide_canal, and Traitement_particulier_Solide_canal_VDF.
Definition at line 22 of file Traitement_particulier_Solide_base.cpp.
{
  return is;
}
readOn()
Entree & Traitement_particulier_Solide_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Traitement_particulier_Solide_canal, and Traitement_particulier_Solide_canal_VDF.
Definition at line 28 of file Traitement_particulier_Solide_base.cpp.
{
  return is;
}
self_cast() [1/2]
const Traitement_particulier_Solide_base & Traitement_particulier_Solide_base::self_cast (const Objet_U & r) static
Definition at line 19 of file Traitement_particulier_Solide_base.cpp.
self_cast() [2/2]
Traitement_particulier_Solide_base & Traitement_particulier_Solide_base::self_cast (Objet_U & r) static
Definition at line 19 of file Traitement_particulier_Solide_base.cpp.
Member Data Documentation
champs_compris_
Champs_compris Traitement_particulier_Solide_base::champs_compris_ private
Definition at line 60 of file Traitement_particulier_Solide_base.h.
Referenced by get_champ(), and get_noms_champs_postraitables().
info_obj
const Type_info Traitement_particulier_Solide_base::info_obj static
Definition at line 38 of file Traitement_particulier_Solide_base.h.
mon_equation
Ref_Conduction Traitement_particulier_Solide_base::mon_equation protected
Definition at line 56 of file Traitement_particulier_Solide_base.h.
Referenced by associer_eqn(), Traitement_particulier_Solide_canal_VDF::calculer_integrales_temporelles(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_Solide_canal_VDF::init_calcul_moyenne(), and Traitement_particulier_Solide_canal_VDF::post_traitement_particulier().
The documentation for this class was generated from the following files:
src/ThSol/Traitement_particulier_Solide_base.h
src/ThSol/Traitement_particulier_Solide_base.cpp