TRUST: Deriv_Traitement_particulier_Solide_base Class Reference
Deriv_Traitement_particulier_Solide_base Class Reference
#include <Traitement_particulier_Solide.h>
Public Member Functions
~Deriv_Traitement_particulier_Solide_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Traitement_particulier_Solide_base ()
Deriv_Traitement_particulier_Solide_base (const Deriv_Traitement_particulier_Solide_base &)
const
Traitement_particulier_Solide_base & valeur () const
Traitement_particulier_Solide_base & valeur ()
const
Traitement_particulier_Solide_base * operator-> () const
Traitement_particulier_Solide_base * operator-> ()
const
Deriv_Traitement_particulier_Solide_base & operator= (const Traitement_particulier_Solide_base &)
const
Deriv_Traitement_particulier_Solide_base & operator= (const Deriv_Traitement_particulier_Solide_base &)
operator const Traitement_particulier_Solide_base & () const
operator Traitement_particulier_Solide_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Deriv_Traitement_particulier_Solide_base & self_cast (Objet_U &)
static const
Deriv_Traitement_particulier_Solide_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Traitement_particulier_Solide_base * pointeur_
Detailed Description
Definition at line 30 of file Traitement_particulier_Solide.h.
Constructor & Destructor Documentation
Deriv_Traitement_particulier_Solide_base::~Deriv_Traitement_particulier_Solide_base ()
Definition at line 26 of file Traitement_particulier_Solide.cpp.
Deriv_Traitement_particulier_Solide_base::Deriv_Traitement_particulier_Solide_base ()
Definition at line 26 of file Traitement_particulier_Solide.cpp.
Deriv_Traitement_particulier_Solide_base::Deriv_Traitement_particulier_Solide_base (const Deriv_Traitement_particulier_Solide_base & t)
Definition at line 26 of file Traitement_particulier_Solide.cpp.
Member Function Documentation
Objet_U * Deriv_Traitement_particulier_Solide_base::cree_instance () [static]
Reimplemented in Traitement_particulier_Solide.
Definition at line 26 of file Traitement_particulier_Solide.cpp.
int Deriv_Traitement_particulier_Solide_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Traitement_particulier_Solide.
Definition at line 26 of file Traitement_particulier_Solide.cpp.
const Type_info * Deriv_Traitement_particulier_Solide_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Traitement_particulier_Solide.
Definition at line 26 of file Traitement_particulier_Solide.cpp.
const Type_info & Deriv_Traitement_particulier_Solide_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Traitement_particulier_Solide.cpp.
const Type_info * Deriv_Traitement_particulier_Solide_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Traitement_particulier_Solide.
Definition at line 26 of file Traitement_particulier_Solide.cpp.
Deriv_Traitement_particulier_Solide_base::operator const Traitement_particulier_Solide_base & () const
Definition at line 26 of file Traitement_particulier_Solide.cpp.
Deriv_Traitement_particulier_Solide_base::operator Traitement_particulier_Solide_base & ()
Definition at line 26 of file Traitement_particulier_Solide.cpp.
const Traitement_particulier_Solide_base * Deriv_Traitement_particulier_Solide_base::operator-> () const [inline]
Definition at line 30 of file Traitement_particulier_Solide.h.
: public DERIV(Traitement_particulier_Solide_base)
Traitement_particulier_Solide_base * Deriv_Traitement_particulier_Solide_base::operator-> () [inline]
Definition at line 30 of file Traitement_particulier_Solide.h.
: public DERIV(Traitement_particulier_Solide_base)
const Deriv_Traitement_particulier_Solide_base & Deriv_Traitement_particulier_Solide_base::operator= (const Deriv_Traitement_particulier_Solide_base & t)
Definition at line 26 of file Traitement_particulier_Solide.cpp.
const Deriv_Traitement_particulier_Solide_base & Deriv_Traitement_particulier_Solide_base::operator= (const Traitement_particulier_Solide_base & t)
Definition at line 26 of file Traitement_particulier_Solide.cpp.
Sortie & Deriv_Traitement_particulier_Solide_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Traitement_particulier_Solide.
Definition at line 26 of file Traitement_particulier_Solide.cpp.
Entree & Deriv_Traitement_particulier_Solide_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Traitement_particulier_Solide.
Definition at line 26 of file Traitement_particulier_Solide.cpp.
const Deriv_Traitement_particulier_Solide_base & Deriv_Traitement_particulier_Solide_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Traitement_particulier_Solide.
Definition at line 26 of file Traitement_particulier_Solide.cpp.
Deriv_Traitement_particulier_Solide_base & Deriv_Traitement_particulier_Solide_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Traitement_particulier_Solide.
Definition at line 26 of file Traitement_particulier_Solide.cpp.
void Deriv_Traitement_particulier_Solide_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Traitement_particulier_Solide.cpp.
unsigned Deriv_Traitement_particulier_Solide_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Traitement_particulier_Solide.
Definition at line 26 of file Traitement_particulier_Solide.cpp.
const Traitement_particulier_Solide_base & Deriv_Traitement_particulier_Solide_base::valeur () const [inline]
Definition at line 30 of file Traitement_particulier_Solide.h.
Referenced by Traitement_particulier_Solide::associer_eqn(), Traitement_particulier_Solide::en_cours_de_resolution(), Traitement_particulier_Solide::lire(), Traitement_particulier_Solide::post_traitement_particulier(), and Traitement_particulier_Solide::preparer_calcul_particulier().
: public DERIV(Traitement_particulier_Solide_base)
Traitement_particulier_Solide_base & Deriv_Traitement_particulier_Solide_base::valeur () [inline]
Definition at line 30 of file Traitement_particulier_Solide.h.
: public DERIV(Traitement_particulier_Solide_base)
Member Data Documentation
const Type_info Deriv_Traitement_particulier_Solide_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Traitement_particulier_Solide.
Definition at line 30 of file Traitement_particulier_Solide.h.
Traitement_particulier_Solide_base* Deriv_Traitement_particulier_Solide_base::pointeur_ [private]
Definition at line 30 of file Traitement_particulier_Solide.h.
The documentation for this class was generated from the following files:
src/ThSol/Traitement_particulier_Solide.h
src/ThSol/Traitement_particulier_Solide.cpp