TRUST: Redresser_hexaedres_vdf Class Reference
Redresser_hexaedres_vdf Class Reference
class Redresser_hexaedres_vdf
Realise un maillage en decoupant chaque tetraedre en 4 nouveaux tetraedres
Le maillage obtenu n'a pas de directions preferentielles
#include <Redresser_hexaedres_vdf.h>
Public Member Functions
Redresser_hexaedres_vdf ()
~Redresser_hexaedres_vdf ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Redresser_hexaedres_vdf & self_cast (Objet_U &)
static const Redresser_hexaedres_vdf & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
class Redresser_hexaedres_vdf
Realise un maillage en decoupant chaque tetraedre en 4 nouveaux tetraedres
Le maillage obtenu n'a pas de directions preferentielles
Definition at line 31 of file Redresser_hexaedres_vdf.h.
Constructor & Destructor Documentation
Redresser_hexaedres_vdf()
Redresser_hexaedres_vdf::Redresser_hexaedres_vdf ()
Definition at line 23 of file Redresser_hexaedres_vdf.cpp.
~Redresser_hexaedres_vdf()
Redresser_hexaedres_vdf::~Redresser_hexaedres_vdf ()
Definition at line 23 of file Redresser_hexaedres_vdf.cpp.
Member Function Documentation
cree_instance()
Objet_U * Redresser_hexaedres_vdf::cree_instance () static
Definition at line 23 of file Redresser_hexaedres_vdf.cpp.
duplique()
int Redresser_hexaedres_vdf::duplique () const override virtual
Implements Objet_U.
Definition at line 23 of file Redresser_hexaedres_vdf.cpp.
get_info()
const Type_info * Redresser_hexaedres_vdf::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 23 of file Redresser_hexaedres_vdf.cpp.
info()
const Type_info * Redresser_hexaedres_vdf::info () static
Definition at line 23 of file Redresser_hexaedres_vdf.cpp.
interpreter_()
Entree & Redresser_hexaedres_vdf::interpreter_ (Entree & is) override virtual
< initialise a zero
< sommet traite !
Implements Interprete_geometrique_base.
Definition at line 35 of file Redresser_hexaedres_vdf.cpp.
{
  if (Process::nproc()>1)
    {
      Cerr << "Redresser_hexaedres_vdf can't be used during a parallel calculation." << finl;
      exit();
    }
  associer_domaine(is);
  DoubleTab& les_sommets = domaine().les_sommets();
  int nb_sommets = les_sommets.dimension(0);
  double epsilon = Objet_U::precision_geom;
  int ok=0;
// On type en rectangle ou hexaedre
  const Elem_geom_base& elem=domaine().zone(0).type_elem().valeur();
  Cerr << "Attempt on the mesh ";
  if                 (sub_type(Rectangle,elem)) Cerr << "to correct rectangles..." << finl;
  else if          (sub_type(Quadrangle_VEF,elem)) Cerr << "to correct VEF quadrangles into rectangles..." << finl;
  else if          (sub_type(Hexaedre,elem)) Cerr << "to correct hexahedra..." << finl;
  else if          (sub_type(Hexaedre_VEF,elem)) Cerr << "to correct VEF hexahedra into regular hexahedra..." << finl;
  else
    {
      Cerr << "This type of element ("<<elem.que_suis_je()<<") is not supported by Redresser_hexaedres_vdf" << finl;
      exit();
    }
  if (dimension==2) domaine().zone(0).typer("Rectangle");
  if (dimension==3) domaine().zone(0).typer("Hexaedre");
  Elem_geom_base& new_elem=domaine().zone(0).type_elem().valeur();
  do
    {
      double correction_max = 0;
      Octree_Double octree;
      octree.build_nodes(les_sommets, 0 /* do not include virtual nodes */);
// direction indique la coordonnee qu'on va corriger
      for (int direction = 0; direction < dimension; direction++)
        {
          ArrOfInt marqueurs(nb_sommets); //!< initialise a zero
          ArrOfInt liste_sommets;
          liste_sommets.set_smart_resize(1);
          int prochain_sommet = 0;
          while (prochain_sommet < nb_sommets)
            {
// Cherche le prochain sommet non marque:
              for (; prochain_sommet < nb_sommets; prochain_sommet++)
                if (! marqueurs[prochain_sommet])
                  break;
              if (prochain_sommet == nb_sommets)
                break;
// Trouver tous les sommets qui sont dans une boite tres grande
// en dehors de la direction dir:
              double x = les_sommets(prochain_sommet, 0);
              double y = les_sommets(prochain_sommet, 1);
              double z = (dimension == 3) ? les_sommets(prochain_sommet, 2) : 0.;
              double xmin = (direction==0) ? (x-epsilon) : (-DMAXFLOAT);
              double xmax = (direction==0) ? (x+epsilon) : (+DMAXFLOAT);
              double ymin = (direction==1) ? (y-epsilon) : (-DMAXFLOAT);
              double ymax = (direction==1) ? (y+epsilon) : (+DMAXFLOAT);
              double zmin = (direction==2) ? (z-epsilon) : (-DMAXFLOAT);
              double zmax = (direction==2) ? (z+epsilon) : (+DMAXFLOAT);
              octree.search_elements_box(xmin, ymin, zmin, xmax, ymax, zmax, liste_sommets);
// Pour chaque sommet, corriger deux des coordonnees
// (on met les coordonnees du point trouve)
              const int n = liste_sommets.size_array();
              for (int i = 0; i < n; i++)
                {
                  const int j = liste_sommets[i];
// le premier sommet sert de reference, ne pas le corriger:
                  if (j == prochain_sommet)
                    continue;
// coordonnee de reference (on aligne tous les autres points du
// plan de maillage sur celui-la:
                  const double coord_ref = les_sommets(prochain_sommet, direction);
// verifier que le sommet est bien dans la boite (l'octree
// renvoie les sommets "potentiellement" a l'interieur
                  const double coord = les_sommets(j, direction);
                  if (std::fabs(coord-coord_ref) > epsilon)
                    continue;
                  correction_max=std::max(correction_max,std::fabs(coord_ref-les_sommets(j, direction)));
// Corriger:
                  les_sommets(j, direction) = coord_ref;
                  marqueurs[j] = 1; //!< sommet traite !
                }
              marqueurs[prochain_sommet] = 1;
            }
        }
      epsilon*=10;
      Cerr << "Redresser_hexaedres_vdf, epsilon=" << epsilon << " maximum_correction=" << correction_max << finl;
      if (epsilon>1)
        {
          Cerr << "Redresser_hexaedres_vdf failed" << finl;
          Cerr << "it has failed to make regular hexahedra on the mesh." << finl;
          exit();
        }
      if (dimension==2)
        ok=ref_cast(Rectangle,new_elem).reordonner_elem();
      else if (dimension==3)
        ok=ref_cast(Hexaedre,new_elem).reordonner_elem();
    }
  while (ok==-1);
  Cerr << "End and success of Redresser_hexaedres_vdf" << finl;
  return is;
}
References Interprete_geometrique_base::associer_domaine(), Octree_Double::build_nodes(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, DMAXFLOAT, Interprete_geometrique_base::domaine(), Process::exit(), finl, Domaine::les_sommets(), Process::nproc(), Objet_U::precision_geom, Objet_U::que_suis_je(), ref_cast, Octree_Double::search_elements_box(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), sub_type, Zone::type_elem(), Zone::typer(), Deriv_Elem_geom_base::valeur(), and Domaine::zone().
printOn()
Sortie & Redresser_hexaedres_vdf::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 25 of file Redresser_hexaedres_vdf.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Redresser_hexaedres_vdf::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 30 of file Redresser_hexaedres_vdf.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Redresser_hexaedres_vdf & Redresser_hexaedres_vdf::self_cast (const Objet_U & r) static
Definition at line 23 of file Redresser_hexaedres_vdf.cpp.
self_cast() [2/2]
Redresser_hexaedres_vdf & Redresser_hexaedres_vdf::self_cast (Objet_U & r) static
Definition at line 23 of file Redresser_hexaedres_vdf.cpp.
taille_memoire()
unsigned Redresser_hexaedres_vdf::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 23 of file Redresser_hexaedres_vdf.cpp.
Member Data Documentation
info_obj
const Type_info Redresser_hexaedres_vdf::info_obj static
Definition at line 33 of file Redresser_hexaedres_vdf.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Redresser_hexaedres_vdf.h
src/Kernel/Geometrie/Redresser_hexaedres_vdf.cpp