TRUST: Format_Post_Lata_V1 Class Reference
Format_Post_Lata_V1 Class Reference
: classe d'ecriture des postraitement au format lata V1
(Trio_U version 1.4.9 et anterieures). Fournie pour compatibilite
#include <Format_Post_Lata_V1.h>
Public Member Functions
~Format_Post_Lata_V1 ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void reset () override
Remet l'objet dans l'etat obtenu par le constructeur par defaut.
int ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post) override
ecriture de l'entete format LataV1
int finir (int &est_le_dernier_post) override
int ecrire_domaine (const Domaine &domaine, const int est_le_premier_post) override
1) Voir documentation de Format_Post_base::ecrire_domaine()
2) Specificites: format LATA ancienne version:
Ecriture du maillage compatible avec le postraitement Data-Visualizer (DV).
DV est un post 3D uniquement. Si le cas traite est 2D on
le rend 3D de la maniere suivante :
- On dedouble tous les noeuds du plan 2D
- On transforme les triangles en prismes
- On transforme les quadrangles en hexaedres
Rq :la numerotation des elements dans DV commence a 1.
virtual int ecrire_bords (const Nom &id_du_domaine, const Motcle &type_faces, const DoubleTab &sommets, const IntTab &faces_sommets, const IntTab &faces_num_bord, const Noms &bords_nom)
l'ecriture des bords n'est pas supportee par ce format: return 0
int ecrire_champ (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data) override
voir Format_Post_base::ecrire_champ
int ecrire_item_int (const Nom &id_item, const Nom &id_du_domaine, const Nom &id_zone, const Nom &localisation, const Nom &reference, const IntVect &data, const int reference_size) override
voir Format_Post_base::ecrire_champ
ATTENTION: si "reference" est non vide on ajoute 1 a toutes les
valeurs pour passer en numerotation fortran, et si de plus on
ecrit un fichier lata unique pour tous les processeurs, on ajoute un
decalage a toutes les valeurs (renumerotation des indices pour
passer en numerotation globale, voir le codage de ecrire_domaine
par exemple)
Format_Post_Lata_V1 ()
Public Member Functions inherited from Format_Post_Lata
~Format_Post_Lata ()
< Necessaire avec xlC pour std::getline
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void reset () override
Remet l'objet dans l'etat obtenu par le constructeur par defaut.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
int initialize_by_default (const Nom &file_basename) override
Initialisation de la classe avec des parametres par
defaut (format ASCII, SINGLE_FILE)
int initialize (const Nom &file_basename, const int format, const Nom &option_para) override
int modify_file_basename (const Nom file_basename, const int a_faire, const double tinit) override
Modification du nom du fichier de postraitement.
virtual int reconstruct (const Nom file_basename, const Nom, const double tinit)
virtual int finir_sans_reprise (const Nom file_basename)
int ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post) override
Ouvre le fichier maitre en mode ERASE et ecrit l'entete du fichier lata<br>(sur le processeur maitre seulement).
int completer_post (const Domaine &dom, const int axi, const Nature_du_champ &nature, const int nb_compo, const Noms &noms_compo, const Motcle &loc_post, const Nom &le_nom_champ_post) override
int preparer_post (const Nom &id_du_domaine, const int est_le_premier_post, const int reprise, const double t_init) override
int ecrire_domaine (const Domaine &domaine, const int est_le_premier_post) override
voir Format_Post_base::ecrire_domaine
On accepte l'ecriture d'un domaine dans un pas de temps, mais
les id_domaines doivent etre tous distincts.
Ecrit le fichier "basename(_XXXXX).lata.nom_domaine", qui contient
la liste des sommets et la liste des elements.
Si le PE est maitre, ouvre le fichier maitre en mode APPEND et
ajoute une reference a ce fichier.
int ecrire_temps (const double temps) override
commence l'ecriture d'un nouveau pas de temps
En l'occurence pour le format LATA:
Ouvre le fichier maitre en mode APPEND et ajoute une ligne
"TEMPS xxxxx" si ce temps n'a pas encore ete ecrit
int finir (int &est_le_dernier_post) override
int ecrire_champ (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data) override
voir Format_Post_base::ecrire_champ
int ecrire_item_int (const Nom &id_item, const Nom &id_du_domaine, const Nom &id_zone, const Nom &localisation, const Nom &reference, const IntVect &data, const int reference_size) override
voir Format_Post_base::ecrire_champ
ATTENTION: si "reference" est non vide on ajoute 1 a toutes les
valeurs pour passer en numerotation fortran, et si de plus on
ecrit un fichier lata unique pour tous les processeurs, on ajoute un
decalage a toutes les valeurs (renumerotation des indices pour
passer en numerotation globale, voir le codage de ecrire_domaine
par exemple)
Format_Post_Lata ()
Constructeur par defaut: format_ ASCII et options_para_ = SINGLE_FILE.
virtual int initialize_lata (const Nom &file_basename, const Format format=ASCII, const Options_Para options_para=SINGLE_FILE)
Initialisation de la classe, ouverture du fichier et ecriture
de l'entete.
Public Member Functions inherited from Format_Post_base
Format_Post_base ()
~Format_Post_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void reset ()=0
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int initialize_by_default (const Nom &file_basename)
Initialise le fichier avec des parametres appropries pour son
format (exemple: format ascii, efface le fichier existant, un
fichier unique pour tous les processeurs etc...)
Methode a surcharger dans les classes derivees.
Valeur de retour: 1 si l'operation a reussi, 0 sinon.
virtual int initialize (const Nom &file_basename, const int format, const Nom &option_para)
virtual int modify_file_basename (const Nom file_basename, const int a_faire, const double tinit)
virtual int ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post)
virtual int completer_post (const Domaine &dom, const int axi, const Nature_du_champ &nature, const int nb_compo, const Noms &noms_compo, const Motcle &loc_post, const Nom &le_nom_champ_post)
virtual int preparer_post (const Nom &id_du_domaine, const int est_le_premier_post, const int reprise, const double t_init)
virtual int test_coherence (const int champs, const int stat, const double dt_ch, const double dt_stat)
virtual int init_ecriture (double temps_courant, double temps_post, int est_le_premier_postraitement_pour_nom_fich_, const Domaine &domaine)
virtual int finir_ecriture (double temps_courant)
virtual int finir (int &est_le_dernier_post)
virtual int ecrire_domaine (const Domaine &domaine, const int est_le_premier_post)
Ecriture d'un maillage. L'ecriture du domaine a lieu soit au debut,
avant le premier appel a ecrire_temps, soit plus tard (maillage dynamique),
mais ce n'est pas forcement supporte par le postraitement.
Parametre: id_domaine
Signification: le nom affecte au domaine dans le fichier lata.
Parametre: type_elem
Signification: le type de l'element geometrique (un type supporte par
la classe derivee, en general on comprend au moins "TETRAEDRE", "HEXAEDRE",
"TRIANGLE" et "RECTANGLE")
Parametre: dimension
Signification: la dimension du domaine (nombre de coordonnees des sommets)
On peut avoir un domaine de dimension 3 et des elements de type triangle
(postraitement d'une interface ou du bord d'un domaine volumique).
Parametre: sommets
Signification:
Coordonnees des sommets. S'il n'est pas vide, il faut que dimension(1)==dimension
Parametre: elements
Signification:
Indices des sommets de chaque element. dimension(1) doit correspondre au type
de l'element (3 pour un triangle, 4 pour un rectangle ou un tetraedre, etc...)
virtual int ecrire_domaine_dis (const Domaine &domaine, const Ref_Zone_dis_base &zone_dis_base, const int est_le_premier_post)
virtual int ecrire_temps (const double temps)
Commence l'ecriture d'un pas de temps. La classe derivee doit accepter
de recevoir plusieurs appels consecutifs a cette methode avec le meme temps.
virtual int ecrire_champ (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data)
Ecriture d'un champ dans le fichier de postraitement.
Parametre: id_du_champ
Signification:
identifiant du champ (permet d'identifier un champ unique si on donne
en plus un numero de pas de temps)
Parametre: id_du_domaine
Signification:
identifiant du domaine sur lequel le champ est defini
Ce domaine doit avoir ete ecrit avant par "ecrire_domaine".
Parametre: localisation
Signification:
localisation des valeurs du champ (SOMMETS, ELEMENTS, ou tout autre id. de
tableau deja ecrit)
(tout n'est pas obligatoirement supporte par tous les postraitements)
Parametre: data
Signification:
tableau de valeurs a postraiter. Le nombre de lignes du tableau
doit etre egal au nombre de lignes du tableau "localisation"
(nombre de sommets, d'elements ou de faces ou autre).
Valeur de retour: 1 si operation reussie, 0 sinon (par exemple,
preconditions non remplies ou fonctionnalite non supportee par le
format).
virtual int ecrire_champ2 (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data, const DoubleTab &coord)
virtual int ecrire_item_int (const Nom &id_item, const Nom &id_du_domaine, const Nom &id_zone, const Nom &localisation, const Nom &reference, const IntVect &data, const int reference_size)
Ecriture d'un tableau d'entiers dans le fichier de postraitement
Voir aussi ecrire_champ
Parametre: reference
Signification: Nom d'un autre tableau deja ecrit. data[i] est un
indice dans ce tableau (exemple: on peut ecrire le tableau
FACES_VOISINS, localisation=FACES, reference=ELEMENTS
car le tableau est indexe par un numero de face et contient
des indices d'elements)
L'ecriture d'un domaine entraine automatiquement l'existence
d'une tableau SOMMETS et d'un tableau ELEMENTS
Parametre: reference_size
Signification: la taille (locale) du tableau cite en reference<br>(dimension(0) du tableau). Cette dimension est utilisee pour
renumeroter le contenu du tableau data afin de creer une numerotation
globale lorsque tous les processeurs ecrivent dans un fichier unique.
void postraiter_debug_valeurs_un_instant (const Nom &nom_fich, const Domaine &dom, const Zone_dis_base &zone_dis, double temps_champ, double temps_courant, const Nom &id_champ_post, const Nature_du_champ &nature_champ, const Noms &noms_compos, const Noms &unites, const Motcle &loc_post, const DoubleTab &data, int ncomp=-1, int axi=0, int champ=1, int stat=0, double dt_ch=1., double dt_stat=1., int reprise=0, int est_le_premier_post=1, int est_le_dernier_post=1, double t_init=0., double temps_post=-2)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Format_Post_Lata_V1 & self_cast (Objet_U &)
static const Format_Post_Lata_V1 & self_cast (const Objet_U &)
static int ecrire_domaine_lata_V1 (const Nom &id_domaine, const Motcle &type_elem, const int dimension, const DoubleTab &sommets, const IntTab &elements, const Status &stat, const Nom &basename, const Format &format, const Options_Para &option)
static int ecrire_entete_lata_V1 (const Nom &basename, const Options_Para &option, const int est_le_premier_post)
static int finir_lata_V1 (const Nom &basename, const Options_Para &option, const int est_le_dernier_post)
static int ecrire_champ_lata_V1 (const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const DoubleTab &data, const double temps, const Nom &basename, const Format &format, const Options_Para &option)
static int ecrire_faces_lata_V1 (const Nom &basename, const Format &format, const Options_Para &option, const Nom &id_du_domaine, const IntTab &faces_sommets, const IntTab &elem_faces, const int nb_sommets)
Static Public Member Functions inherited from Format_Post_Lata
static Objet_U * cree_instance ()
static const Type_info * info ()
static Format_Post_Lata & self_cast (Objet_U &)
static const Format_Post_Lata & self_cast (const Objet_U &)
static int ecrire_entete_lata (const Nom &base_name, const Options_Para &option, const Format &format, const int est_le_premier_post)
static int ecrire_temps_lata (const double temps, double &temps_format, const Nom &base_name, Status &stat, const Options_Para &option)
static const char * extension_lata ()
Renvoie l'extension conventionnelle des fichiers lata : ".lata".
static const char * remove_path (const char *filename)
Renvoie le nom d'un fichier sans le path :
on enleve les caracteres avant le dernier /.
Static Public Member Functions inherited from Format_Post_base
static const Type_info * info ()
static Format_Post_base & self_cast (Objet_U &)
static const Format_Post_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Format_Post_Lata
static const Type_info info_obj
Static Public Attributes inherited from Format_Post_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
erreur => exit
Entree & readOn (Entree &) override
les options sont identiques a celles du format V2
Voir Format_Post_Lata::readOn()
Sortie & printOn (Sortie &x) const override
erreur => exit
Entree & readOn (Entree &) override
Lecture des parametres du postraitement au format "jeu de donnees"
Le format attendu est le suivant:
{
nom_fichier nom champ obligatoire
[ format ascii|binaire ] valeur par defaut : ascii
[ parallel single_file|multiple_files ] valeur par defaut : single_file
}.
Sortie & printOn (Sortie &x) const override
erreur => exit
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
const IntTab * ref_faces_sommets
int ref_nb_som
Protected Attributes inherited from Format_Post_Lata
int deja_fait_
int file_existe_
double tinit_
Nom lata_basename_
Format format_
Options_Para options_para_
Status status
double temps_courant_
Additional Inherited Members
Public Types inherited from Format_Post_Lata
enum Format { ASCII , BINAIRE }
enum Options_Para { SINGLE_FILE , SINGLE_FILE_MPIIO , MULTIPLE_FILES }
enum Status { RESET , INITIALIZED , WRITING_TIME }
Static Protected Member Functions inherited from Format_Post_Lata
static int write_doubletab (Fichier_Lata &fichier, const DoubleTab &tab, int &nb_colonnes, const Options_Para &option, const int bloc_number=0, const int nb_blocs=1)
fichier est un fichier lata de donnees (pas le fichier maitre)
on y ecrit le tableau tab tel quel (en binaire ou ascii et sur un ou
plusieurs fichiers en parallel).
nb_colonnes est rempli avec le produit des tab.dimension(i) pour i>0
bloc_number et nb_blocs sont utilises pour les valeurs aux sommets en 2D
pour le format lataV1 : on ecrit deux fois le nombre de sommets dans le meme bloc
(bloc_number = le numero du bloc courant en cours d'ecriture,
nb_blocs = le nombre total de blocs ecrits. Le tag de debut et de fin
est ecrit au debut du premier bloc et a la fin du dernier et le nombre est
la taille du tableau multiplie par le nombre de blocs (on suppose que tous
les blocs sont identiques)).
static int write_inttab (Fichier_Lata &fichier, int decalage, int decalage_partiel, const IntTab &tab, int &nb_colonnes, const Options_Para &option)
Ecriture d'un tableau d'entiers dans le fichier fourni.
Les valeurs ecrites sont les valeurs du tableau auquelles ont ajoute
"decalage". Cette valeur est utilisee pour passer en numerotation
fortran (ajouter 1), ou pour passer en numerotation globale (ajouter
le nombre d'elements sur les processeurs precedents).
On renvoie dans nb_colonnes la somme des dimension(i) pour i>0.
Valeur de retour: somme des dimension(0) ecrits (selon que tous les
processeurs ecrivent sur le meme fichier ou pas).
Detailed Description
: classe d'ecriture des postraitement au format lata V1
(Trio_U version 1.4.9 et anterieures). Fournie pour compatibilite
Definition at line 23 of file Format_Post_Lata_V1.h.
Constructor & Destructor Documentation
~Format_Post_Lata_V1()
Format_Post_Lata_V1::~Format_Post_Lata_V1 ()
Definition at line 21 of file Format_Post_Lata_V1.cpp.
Format_Post_Lata_V1()
Format_Post_Lata_V1::Format_Post_Lata_V1 ()
Definition at line 23 of file Format_Post_Lata_V1.cpp.
{
  ref_faces_sommets = 0;
}
References ref_faces_sommets.
Member Function Documentation
cree_instance()
Objet_U * Format_Post_Lata_V1::cree_instance () static
Definition at line 21 of file Format_Post_Lata_V1.cpp.
duplique()
int Format_Post_Lata_V1::duplique () const override virtual
Reimplemented from Format_Post_Lata.
Definition at line 21 of file Format_Post_Lata_V1.cpp.
ecrire_bords()
int Format_Post_Lata_V1::ecrire_bords (const Nom & id_du_domaine, const Motcle & type_faces, const DoubleTab & sommets, const IntTab & faces_sommets, const IntTab & faces_num_bord, const Noms & bords_nom) virtual
l'ecriture des bords n'est pas supportee par ce format: return 0
Definition at line 104 of file Format_Post_Lata_V1.cpp.
{
  return 0;
}
ecrire_champ()
int Format_Post_Lata_V1::ecrire_champ (const Domaine & domaine, const Noms & unite_, const Noms & noms_compo, int ncomp, double temps_, double temps_courant, const Nom & id_du_champ, const Nom & id_du_domaine, const Nom & localisation, const Nom & nature, const DoubleTab & data) override virtual
voir Format_Post_base::ecrire_champ
Reimplemented from Format_Post_Lata.
Definition at line 89 of file Format_Post_Lata_V1.cpp.
{
  ecrire_champ_lata_V1(id_du_champ,id_du_domaine,localisation,data,temps_,lata_basename_,format_,options_para_);
  return 1;
}
References ecrire_champ_lata_V1(), Format_Post_Lata::format_, Format_Post_Lata::lata_basename_, and Format_Post_Lata::options_para_.
ecrire_champ_lata_V1()
int Format_Post_Lata_V1::ecrire_champ_lata_V1 (const Nom & id_du_champ, const Nom & id_du_domaine, const Nom & localisation, const DoubleTab & data, const double temps, const Nom & basename, const Format & format, const Options_Para & option) static
Definition at line 514 of file Format_Post_Lata_V1.cpp.
{
// Verification que le nom du champ correspond bien au
// nombre de coposante du champ grace a latav1_component_shape()
// Cette partie de codage pourra etre supprime quand le plugin
// LATA sera en mesure de gerer cela lui-meme (V2 ?)
  int nb_comp,nb_comp_du_champ;
  {
    int shape=1;
    shape=latav1_component_shape(id_du_champ);
    Nom avec_s;
    avec_s="";
    nb_comp=1;
    if (shape<0)
      {
        avec_s="s";
        if (shape==-1)
          nb_comp=dimension;
        else if (dimension==3)
          nb_comp=dimension;
      }
    else
      nb_comp=shape;
    nb_comp_du_champ=data.nb_dim();
    if (nb_comp_du_champ>1)
      nb_comp_du_champ=data.dimension(1);
// On exclus tous les cas ou le champ qui est postraite aux faces, est scalaire mais interprete comme vectoriel
// Typiquement le cas de la vitesse aux faces en VDF : nb_comp = 2 ou 3 et nb_comp_du_champ = 1 car 1 seul vitesse normal par face.
    if ((Motcle)localisation=="FACES" && nb_comp_du_champ<nb_comp)
      nb_comp_du_champ=nb_comp;
    Nom avec_ss;
    avec_ss="";
    if (nb_comp_du_champ>1)
      avec_ss="s";
  }
// Modification de id_du_champ car l interpolation modifie le nom (ajout de elem_nom_du_domaine
// ou som_nom_du_domaine, on supprime cette extension)
  Motcle id_du_champ_modifie(id_du_champ);
  Motcle iddomaine(id_du_domaine);
  if (nb_comp!=nb_comp_du_champ)
    {
      id_du_champ_modifie=Nom(nb_comp_du_champ);
      id_du_champ_modifie+="_";
      id_du_champ_modifie+=id_du_champ;
    }
// On utilise prefix avec un argument en majuscule
  if ((Motcle)localisation=="SOM")
    {
      id_du_champ_modifie.prefix(id_du_domaine);
      id_du_champ_modifie.prefix(iddomaine);
//
      id_du_champ_modifie.prefix("_SOM_");
    }
  else if ((Motcle)localisation=="ELEM")
    {
      id_du_champ_modifie.prefix(id_du_domaine);
      id_du_champ_modifie.prefix(iddomaine);
//
      id_du_champ_modifie.prefix("_ELEM_");
    }
  else if ((Motcle)localisation=="FACES")
    {
      id_du_champ_modifie.prefix(id_du_domaine);
      id_du_champ_modifie.prefix(iddomaine);
      id_du_champ_modifie.prefix("_FACES_");
    }
  if ((Motcle)id_du_champ_modifie=="VITESSEX")
    id_du_champ_modifie="VITESSEX";
  if ((Motcle)id_du_champ_modifie=="VITESSEY")
    id_du_champ_modifie="VITESSEY";
  if ((Motcle)id_du_champ_modifie=="EPS")
    id_du_champ_modifie="EPS";
  const char * point = ".";
// Construction du nom du fichier
  Nom basename_champ(basename);
  Nom extension_champ(extension_lata());
  extension_champ += point;
  extension_champ += id_du_champ_modifie;
  extension_champ += point;
  Motcle loc = localisation;
  if (loc.debute_par("SOM"))
    {
      extension_champ += "SOM";
    }
  else if (loc.debute_par("ELEM"))
    {
      extension_champ += "ELEM";
    }
  else if (loc.debute_par("FACES"))
    {
      extension_champ += "FACES";
    }
  else
    {
      return 0;
    }
  extension_champ += point;
  extension_champ += id_du_domaine;
  extension_champ += point;
  extension_champ += "pb";
  extension_champ += point;
  char str_temps[100] = "0.0";
  if (temps >= 0.)
    sprintf(str_temps, "%.10f", temps);
  extension_champ += str_temps;
  Nom filename_champ;
  {
    Fichier_Lata fichier_champ(basename_champ, extension_champ,
                               Fichier_Lata::ERASE, format,option);
    filename_champ = fichier_champ.get_filename();
    if (data.nb_dim() == 1)
      {
        int nb_colonnes;
        Format_Post_Lata::write_doubletab(fichier_champ,
                                          data,
                                          nb_colonnes,
                                          option);
      }
    else
      {
// Pour compatibilite avec la version precedente du module lata :
// si le champ a plusieurs composantes,
// on ecrit :
// valeurs(0,0) valeurs(1,0) valeurs(2,0) ...
// valeurs(0,1) valeurs(1,1) valeurs(2,1) ...
        const int nb_lignes = data.dimension(0);
        const int nb_colonnes = data.dimension(1);
        DoubleTab data_slice(nb_lignes);
// Pour voir data comme un tableau unidimensionnel :
        if (data.nb_dim() != 2)
          {
            Cerr << "Error : Format_Post_Lata_V1::ecrire_champ_lata_V1 not coded for dimensions > 2" << finl;
            exit();
          }
        for (int colonne = 0; colonne < nb_colonnes; colonne++)
          {
            for (int i = 0; i < nb_lignes; i++)
              data_slice[i] = data(i, colonne);
            int dummy;
            Format_Post_Lata::write_doubletab(fichier_champ,
                                              data_slice,
                                              dummy,
                                              option,
                                              colonne, nb_colonnes);
          }
      }
  }
// Ouverture du fichier .lata en mode append.
// Ajout de la reference au champ
  Fichier_Lata_maitre fichier(basename, extension_lata(),
                              Fichier_Lata::APPEND, option);
  SFichier& sfichier = fichier.get_SFichier();
  if (fichier.is_master())
    {
      sfichier << "Champ ";
      sfichier << id_du_champ_modifie << " ";
      sfichier << remove_path(filename_champ) << finl;
    }
  fichier.syncfile();
  return 1;
}
References Fichier_Lata::APPEND, Cerr, Motcle::debute_par(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Fichier_Lata::ERASE, Process::exit(), Format_Post_Lata::extension_lata(), finl, Fichier_Lata::get_filename(), Fichier_Lata::get_SFichier(), Fichier_Lata::is_master(), TRUSTTab< _TYPE_ >::nb_dim(), Nom::prefix(), Format_Post_Lata::remove_path(), Fichier_Lata::syncfile(), and Format_Post_Lata::write_doubletab().
Referenced by ecrire_champ(), and Postraitement_lata::ecrire_champ().
ecrire_domaine()
int Format_Post_Lata_V1::ecrire_domaine (const Domaine & domaine, const int est_le_premier_post) override virtual
1) Voir documentation de Format_Post_base::ecrire_domaine()
2) Specificites: format LATA ancienne version:
Ecriture du maillage compatible avec le postraitement Data-Visualizer (DV).
DV est un post 3D uniquement. Si le cas traite est 2D on
le rend 3D de la maniere suivante :
- On dedouble tous les noeuds du plan 2D
- On transforme les triangles en prismes
- On transforme les quadrangles en hexaedres
Rq :la numerotation des elements dans DV commence a 1.
< ok tout va bien
Reimplemented from Format_Post_Lata.
Definition at line 71 of file Format_Post_Lata_V1.cpp.
{
  const Nom& id_domaine = domaine.le_nom();
  Motcle type_elem = domaine.zone(0).type_elem()->que_suis_je();
  if (dimension==3)
    {
      if ((type_elem=="TRIANGLE") || (type_elem=="QUADRANGLE"))
        type_elem+="_3D";
    }
  const DoubleTab& sommets = domaine.les_sommets();
  const int dim = domaine.les_sommets().dimension(1);
  const IntTab& elements = domaine.zone(0).les_elems();
  ecrire_domaine_lata_V1(id_domaine,type_elem,dim,sommets,elements,status,lata_basename_,format_,options_para_);
  return 1; //!< ok tout va bien
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, ecrire_domaine_lata_V1(), Format_Post_Lata::format_, Format_Post_Lata::lata_basename_, Domaine::le_nom(), Zone::les_elems(), Domaine::les_sommets(), Format_Post_Lata::options_para_, Objet_U::que_suis_je(), Format_Post_Lata::status, Zone::type_elem(), type_elem(), and Domaine::zone().
ecrire_domaine_lata_V1()
int Format_Post_Lata_V1::ecrire_domaine_lata_V1 (const Nom & id_domaine, const Motcle & type_elem, const int dimension, const DoubleTab & sommets, const IntTab & elements, const Status & stat, const Nom & basename, const Format & format, const Options_Para & option) static
< Ecriture tardive des domaines dynamiques non supportee
< non utilise
< non utilise
Definition at line 245 of file Format_Post_Lata_V1.cpp.
{
  if (stat > INITIALIZED)
    {
      return 0; //!< Ecriture tardive des domaines dynamiques non supportee
    }
// Construction du nom du fichier de geometrie
  Nom basename_geom(basename);
  Nom extension_geom(extension_lata());
  extension_geom += ".";
  extension_geom += id_domaine;
  Nom nom_fichier_geom;
// Indice global attribue au premier sommet de ce processeur:
  int decalage_sommets = -1;
  int decalage_elements = -1;
  {
    Fichier_Lata fichier_geom(basename_geom, extension_geom,
                              Fichier_Lata::ERASE, format,option);
    nom_fichier_geom = fichier_geom.get_filename();
    int nb_col;
// Coordonnees des sommets
    const int nb_sommets = sommets.dimension(0);
    if (dim==2)
      {
// Ecriture en deux fois : tous les processeurs ecrivent une premiere rangee
// de sommets, puis tous les processeurs ecrivent une deuxieme rangee.
        for (int bloc_number = 0; bloc_number < 2; bloc_number++)
          {
            DoubleTab sommets2(nb_sommets, 3);
            const double z = (bloc_number == 0) ? 0. : 1.;
            for (int i = 0; i < nb_sommets; i++)
              {
                double x = sommets(i,0);
                double y = sommets(i,1);
                if (axi)
                  {
                    double r = x;
                    double theta = y;
                    x = r * cos(theta);
                    y = r * sin(theta);
                  }
                sommets2(i,0) = x;
                sommets2(i,1) = y;
                sommets2(i,2) = z;
              }
            Format_Post_Lata::write_doubletab(fichier_geom, sommets2, nb_col, option,
                                              bloc_number, 2);
          }
      }
    else
      {
        if (axi)
          {
            DoubleTab sommets2(sommets);
            for (int i = 0; i < nb_sommets; i++)
              {
                double r = sommets(i,0);
                double theta = sommets(i,1);
                double z = sommets(i,2);
                sommets2(i,0) = r*cos(theta);
                sommets2(i,1) = r*sin(theta);
                sommets2(i,2) = z;
              }
            Format_Post_Lata::write_doubletab(fichier_geom, sommets2, nb_col,option);
          }
        else
          {
            Format_Post_Lata::write_doubletab(fichier_geom, sommets, nb_col,option);
          }
      }
// Elements
// Les indices de sommets, elements et autres dans le fichier lata commencent a 1 :
    const int nb_elem = elements.dimension(0);
    if (option == SINGLE_FILE && Process::nproc() > 1)
      {
// Tous les processeurs ecrivent dans le meme fichier. Il faut renumeroter les
// sommets des elements pour avoir une numerotation globale.
// On ajoute un pour numerotation fortran
        decalage_sommets = 1 + mppartial_sum(nb_sommets);
        decalage_elements = 1 + mppartial_sum(nb_elem);
      }
    else
      {
// Chaque processeur ecrit dans un fichier separe avec des indices locaux.
// On ajoute un pour numerotation fortran
        decalage_sommets = 1;
        decalage_elements = 1;
      }
    if (dim==2)
      {
// Decalage a ajouter a un indice de sommet pour passer de la rangee z=0
// a la rangee z=1
        int decalage_z1 = nb_sommets;
        if (option == SINGLE_FILE && Process::nproc() > 1)
          decalage_z1 = mp_sum(nb_sommets);
        const int nsomelem = (elements.nb_dim() > 1) ? elements.dimension(1) : 1;
        IntTab elem2(nb_elem, nsomelem*2);
        for (int i = 0; i < nb_elem; i++)
          {
            for (int j = 0; j < nsomelem; j++)
              {
                const int s = elements(i,j);
                elem2(i,j) = s;
                elem2(i,j + nsomelem) = s + decalage_z1;
              }
          }
        Format_Post_Lata::write_inttab(fichier_geom, 1,decalage_sommets, elem2, nb_col, option);
      }
    else
      {
        Format_Post_Lata::write_inttab(fichier_geom, 1,decalage_sommets, elements, nb_col, option);
      }
  }
// En mode parallele, on ecrit en plus des fichiers contenant les donnees paralleles
// sur les sommets, les elements et les faces...
// On ecrit dans le fichier maitre ceci :
// joints_sommets NPROC FICHIER_NB_SOMMETS FICHIER_NB_SOMMETS_JOINTS FICHIER_JOINTS
// NPROC est le nombre de parties
// FICHIER_NB_SOMMETS est le nom du fichier contenant, pour chaque proc, le nombre de
// sommets sur ce processeur
// FICHIER_JOINTS est le nom du fichier contenant les joints
// Dans FICHIER_NB_SOMMETS, on a un tableau contenant NPROC entiers, le nombre de sommets
// ecrits par chaque processeur
// Dans FICHIER_NB_SOMMETS_JOINTS, on a un tableau de NPROC entiers contenant pour chaque
// proc le nombre de sommets de joint
// Dans FICHIER_JOINTS on a un tableau contenant les sommets de joint de chaque processeur,
// en numerotation globale : pour chaque sommet, indice du sommet local, indice du sommet
// equivalent sur une autre sous-partie, numero de la sous-partie
  Nom filename_decal_som;
  Nom filename_decal_elem;
  if (option == SINGLE_FILE && Process::nproc() > 1)
    {
      Nom extension;
      extension = extension_lata();
      extension += ".";
      extension += "decal_som_proc";
      extension += ".";
      extension += id_domaine;
      {
        Fichier_Lata fichier_champ(basename, extension,
                                   Fichier_Lata::ERASE, format, option);
        filename_decal_som = fichier_champ.get_filename();
        int nb_col = -1; //!< non utilise
        IntTab data(1,2);
        data(0, 0) = decalage_sommets;
        data(0, 1) = sommets.dimension(0);
        Format_Post_Lata::write_inttab(fichier_champ,0, 0 /* ne pas ajouter de decalage */,
                                       data, nb_col, option);
      }
      extension = extension_lata();
      extension += ".";
      extension += "decal_elem_proc";
      extension += ".";
      extension += id_domaine;
      {
        Fichier_Lata fichier_champ(basename, extension,
                                   Fichier_Lata::ERASE, format, option);
        filename_decal_elem = fichier_champ.get_filename();
        int nb_col = -1; //!< non utilise
        IntTab data(1,2);
        data(0, 0) = decalage_elements;
        data(0, 1) = elements.dimension(0);
        Format_Post_Lata::write_inttab(fichier_champ,0, 0 /* ne pas ajouter de decalage */,
                                       data, nb_col, option);
      }
    }
  Fichier_Lata_maitre fichier_lata(basename, extension_lata(),
                                   Fichier_Lata::APPEND,option);
  SFichier& sfichier = fichier_lata.get_SFichier();
  int nb_som_tot = sommets.dimension(0);
  int nb_elem_tot = elements.dimension(0);
  if (option == SINGLE_FILE && Process::nproc() > 1)
    {
      nb_som_tot = mp_sum(nb_som_tot);
      nb_elem_tot = mp_sum(nb_elem_tot);
    }
  if (fichier_lata.is_master())
    {
      sfichier << "Geometrie " << id_domaine;
      sfichier << " " << remove_path(nom_fichier_geom) << finl;
      switch(format)
        {
        case ASCII:
          sfichier << "Format=ascii" << finl;
          break;
        case BINAIRE:
          sfichier << "Format=binary" << finl;
          break;
        default:
          Cerr << "Error in Format_Post_Lata_V1::ecrire_entete\n"
               << " format not supported" << finl;
          exit();
        }
      sfichier << "nb_som_tot=" << nb_som_tot << finl;
      sfichier << "type_elem=" << type_elem << finl;
      sfichier << "nb_elem_tot=" << nb_elem_tot << finl;
      if (option == SINGLE_FILE && Process::nproc() > 1)
        {
          const int nproc = Process::nproc();
          sfichier << "joints_sommets nproc=" << nproc << " decalage=" << remove_path(filename_decal_som) << finl;
          sfichier << "joints_elements nproc=" << nproc << " decalage=" << remove_path(filename_decal_elem) << finl;
        }
    }
  fichier_lata.syncfile();
  return 1;
}
References Fichier_Lata::APPEND, Format_Post_Lata::ASCII, Objet_U::axi, Format_Post_Lata::BINAIRE, Cerr, TRUSTTab< _TYPE_ >::dimension(), Fichier_Lata::ERASE, Process::exit(), Format_Post_Lata::extension_lata(), finl, Fichier_Lata::get_filename(), Fichier_Lata::get_SFichier(), Format_Post_Lata::INITIALIZED, Fichier_Lata::is_master(), Process::mp_sum(), mppartial_sum(), TRUSTTab< _TYPE_ >::nb_dim(), Process::nproc(), Format_Post_Lata::remove_path(), Format_Post_Lata::SINGLE_FILE, Fichier_Lata::syncfile(), type_elem(), Format_Post_Lata::write_doubletab(), and Format_Post_Lata::write_inttab().
Referenced by ecrire_domaine(), and Postraitement_lata::ecrire_zone().
ecrire_entete()
int Format_Post_Lata_V1::ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post) override virtual
ecriture de l'entete format LataV1
Reimplemented from Format_Post_Lata.
Definition at line 46 of file Format_Post_Lata_V1.cpp.
{
  ecrire_entete_lata_V1(lata_basename_,options_para_,est_le_premier_post);
  return 1;
}
References ecrire_entete_lata_V1(), Format_Post_Lata::lata_basename_, and Format_Post_Lata::options_para_.
ecrire_entete_lata_V1()
int Format_Post_Lata_V1::ecrire_entete_lata_V1 (const Nom & basename, const Options_Para & option, const int est_le_premier_post) static
Definition at line 470 of file Format_Post_Lata_V1.cpp.
{
  if (est_le_premier_post)
    {
// Effacement du fichier .lata et ecriture de l'entete
      Fichier_Lata_maitre fichier(basename, extension_lata(),
                                  Fichier_Lata::ERASE,
                                  option);
      SFichier& sfichier = fichier.get_SFichier();
      if (fichier.is_master())
        {
          sfichier << "Trio_U Version1.4.9 06/2005" << finl;
          sfichier << Objet_U::nom_du_cas() << finl;
          sfichier << "Trio_U" << finl;
        }
      fichier.syncfile();
    }
  return 1;
}
References Fichier_Lata::ERASE, Format_Post_Lata::extension_lata(), finl, Fichier_Lata::get_SFichier(), Fichier_Lata::is_master(), Objet_U::nom_du_cas(), and Fichier_Lata::syncfile().
Referenced by ecrire_entete(), and Postraitement_lata::ecrire_entete().
ecrire_faces_lata_V1()
int Format_Post_Lata_V1::ecrire_faces_lata_V1 (const Nom & basename, const Format & format, const Options_Para & option, const Nom & id_du_domaine, const IntTab & faces_sommets, const IntTab & elem_faces, const int nb_sommets) static
< non utilise
< ok tout va bien
Definition at line 156 of file Format_Post_Lata_V1.cpp.
{
  Nom nom_fichier_geom;
  int nb_faces_tot = -1;
  int decalage_faces = 1;
  {
    Nom basename_geom(basename);
    Nom extension_geom(extension_lata());
    extension_geom += ".";
    extension_geom += id_du_domaine;
    Fichier_Lata fichier_geom(basename_geom, extension_geom,
                              Fichier_Lata::APPEND, format, option);
    nom_fichier_geom = fichier_geom.get_filename();
// Faces
// Les indices de sommets, elements et autres dans le fichier lata commencent a 1 :
    int nb_col;
    int decal;
    if (option == SINGLE_FILE && Process::nproc() > 1)
      {
// Decalage a ajouter aux indices pour avoir une numerotation globale.
        decal = mppartial_sum(nb_sommets) + 1;
        decalage_faces = mppartial_sum(faces.dimension(0)) + 1;
      }
    else
      {
        decal = 1;
        decalage_faces = 1;
      }
    nb_faces_tot = Format_Post_Lata::write_inttab(fichier_geom,
                                                  1, decal,
                                                  faces,
                                                  nb_col,
                                                  option);
    Format_Post_Lata::write_inttab(fichier_geom,
                                   1, decalage_faces,
                                   elem_faces,
                                   nb_col,
                                   option);
  }
  Fichier_Lata_maitre fichier_lata(basename, extension_lata(),
                                   Fichier_Lata::APPEND, option);
  SFichier& sfichier = fichier_lata.get_SFichier();
  Nom filename_joint_faces;
  if (option == SINGLE_FILE && Process::nproc() > 1)
    {
      Nom extension;
      extension = extension_lata();
      extension += ".";
      extension += "decal_faces_proc";
      extension += ".";
      extension += id_du_domaine;
      {
        Fichier_Lata fichier_champ(basename, extension,
                                   Fichier_Lata::ERASE, format, option);
        filename_joint_faces = fichier_champ.get_filename();
        int nb_col = -1; //!< non utilise
        IntTab data(1,2);
        data(0, 0) = decalage_faces;
        data(0, 1) = faces.dimension(0);
        Format_Post_Lata::write_inttab(fichier_champ,0,  0 /* ne pas ajouter de decalage */,
                                       data, nb_col, option);
      }
    }
  if (fichier_lata.is_master())
    {
      sfichier << "nb_faces_tot=" << nb_faces_tot << finl;
      if (option == SINGLE_FILE && Process::nproc() > 1)
        {
          const int nproc = Process::nproc();
          sfichier << "joints_faces nproc=" << nproc << " decalage=" << remove_path(filename_joint_faces) << finl;
        }
    }
  fichier_lata.syncfile();
  return 1; //!< ok tout va bien
}
References Fichier_Lata::APPEND, TRUSTTab< _TYPE_ >::dimension(), Fichier_Lata::ERASE, Format_Post_Lata::extension_lata(), finl, Fichier_Lata::get_filename(), Fichier_Lata::get_SFichier(), Fichier_Lata::is_master(), mppartial_sum(), Process::nproc(), Format_Post_Lata::remove_path(), Format_Post_Lata::SINGLE_FILE, Fichier_Lata::syncfile(), and Format_Post_Lata::write_inttab().
Referenced by ecrire_item_int(), and Postraitement_lata::ecrire_zone().
ecrire_item_int()
int Format_Post_Lata_V1::ecrire_item_int (const Nom & id_item, const Nom & id_du_domaine, const Nom & id_zone, const Nom & localisation, const Nom & reference, const IntVect & data, const int reference_size) override virtual
voir Format_Post_base::ecrire_champ
ATTENTION: si "reference" est non vide on ajoute 1 a toutes les
valeurs pour passer en numerotation fortran, et si de plus on
ecrit un fichier lata unique pour tous les processeurs, on ajoute un
decalage a toutes les valeurs (renumerotation des indices pour
passer en numerotation globale, voir le codage de ecrire_domaine
par exemple)
Reimplemented from Format_Post_Lata.
Definition at line 116 of file Format_Post_Lata_V1.cpp.
{
  const IntTab& data = static_cast<const IntTab&>(val);
  if (id_item == "FACES")
    {
      ref_faces_sommets = &data;
      ref_nb_som = reference_size;
      return 1;
    }
  else if (id_item == "ELEM_FACES")
    {
// continue
    }
  else
    {
      ref_faces_sommets = 0;
// not supported
      return 0;
    }
  ecrire_faces_lata_V1(lata_basename_,
                       format_,
                       options_para_,
                       id_du_domaine,
                       static_cast<const IntTab&>(*ref_faces_sommets),
                       static_cast<const IntTab&>(val),
                       ref_nb_som);
  return 0;
}
References ecrire_faces_lata_V1(), Format_Post_Lata::format_, Format_Post_Lata::lata_basename_, Format_Post_Lata::options_para_, ref_faces_sommets, and ref_nb_som.
finir()
int Format_Post_Lata_V1::finir (int & est_le_dernier_post) override virtual
Reimplemented from Format_Post_Lata.
Definition at line 53 of file Format_Post_Lata_V1.cpp.
{
  finir_lata_V1(lata_basename_,options_para_,est_le_dernier_post);
  return 1;
}
References finir_lata_V1(), Format_Post_Lata::lata_basename_, and Format_Post_Lata::options_para_.
finir_lata_V1()
int Format_Post_Lata_V1::finir_lata_V1 (const Nom & basename, const Options_Para & option, const int est_le_dernier_post) static
Definition at line 495 of file Format_Post_Lata_V1.cpp.
{
  if (est_le_dernier_post)
    {
      Fichier_Lata_maitre fichier(basename, extension_lata(),
                                  Fichier_Lata::APPEND,
                                  option);
      SFichier& sfichier = fichier.get_SFichier();
      if (fichier.is_master())
        {
          sfichier << "FIN" << finl;
        }
      fichier.syncfile();
    }
  return 1;
}
References Fichier_Lata::APPEND, Format_Post_Lata::extension_lata(), finl, Fichier_Lata::get_SFichier(), Fichier_Lata::is_master(), and Fichier_Lata::syncfile().
Referenced by finir(), and Postraitement_lata::finir_lata().
get_info()
const Type_info * Format_Post_Lata_V1::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Format_Post_Lata.
Definition at line 21 of file Format_Post_Lata_V1.cpp.
info()
const Type_info * Format_Post_Lata_V1::info () static
Definition at line 21 of file Format_Post_Lata_V1.cpp.
printOn()
Sortie & Format_Post_Lata_V1::printOn (Sortie & x) const override protected virtual
erreur => exit
Reimplemented from Format_Post_Lata.
Definition at line 40 of file Format_Post_Lata_V1.cpp.
{
  return Format_Post_Lata::printOn(os);
}
References Format_Post_Lata::printOn().
readOn()
Entree & Format_Post_Lata_V1::readOn (Entree & is) override protected virtual
les options sont identiques a celles du format V2
Voir Format_Post_Lata::readOn()
Reimplemented from Format_Post_Lata.
Definition at line 35 of file Format_Post_Lata_V1.cpp.
{
  return Format_Post_Lata::readOn(is);
}
References Format_Post_Lata::readOn().
reset()
void Format_Post_Lata_V1::reset () override virtual
Remet l'objet dans l'etat obtenu par le constructeur par defaut.
Reimplemented from Format_Post_Lata.
Definition at line 28 of file Format_Post_Lata_V1.cpp.
{
  ref_faces_sommets = 0;
}
References ref_faces_sommets.
self_cast() [1/2]
const Format_Post_Lata_V1 & Format_Post_Lata_V1::self_cast (const Objet_U & r) static
Definition at line 21 of file Format_Post_Lata_V1.cpp.
self_cast() [2/2]
Format_Post_Lata_V1 & Format_Post_Lata_V1::self_cast (Objet_U & r) static
Definition at line 21 of file Format_Post_Lata_V1.cpp.
taille_memoire()
unsigned Format_Post_Lata_V1::taille_memoire () const override virtual
Reimplemented from Format_Post_Lata.
Definition at line 21 of file Format_Post_Lata_V1.cpp.
Member Data Documentation
info_obj
const Type_info Format_Post_Lata_V1::info_obj static
Definition at line 25 of file Format_Post_Lata_V1.h.
ref_faces_sommets
const IntTab* Format_Post_Lata_V1::ref_faces_sommets protected
Definition at line 89 of file Format_Post_Lata_V1.h.
Referenced by ecrire_item_int(), Format_Post_Lata_V1(), and reset().
ref_nb_som
int Format_Post_Lata_V1::ref_nb_som protected
Definition at line 90 of file Format_Post_Lata_V1.h.
Referenced by ecrire_item_int().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Format_Post_Lata_V1.h
src/Kernel/Framework/Format_Post_Lata_V1.cpp