TRUST: Ref_Champ_Fonc Class Reference
Ref_Champ_Fonc Class Reference
#include <Ref_Champ_Fonc.h>
Public Member Functions
~Ref_Champ_Fonc ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Champ_Fonc ()
Ref_Champ_Fonc (const Champ_Fonc &)
Ref_Champ_Fonc (const Ref_Champ_Fonc &)
const Champ_Fonc & valeur () const
Champ_Fonc & valeur ()
const Champ_Fonc * operator-> () const
Champ_Fonc * operator-> ()
const Ref_Champ_Fonc & operator= (const Champ_Fonc &)
const Ref_Champ_Fonc & operator= (const Ref_Champ_Fonc &)
operator const Champ_Fonc & () const
operator Champ_Fonc & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Champ_Fonc & self_cast (Objet_U &)
static const Ref_Champ_Fonc & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Champ_Fonc * pointeur_
Detailed Description
Definition at line 28 of file Ref_Champ_Fonc.h.
Constructor & Destructor Documentation
Ref_Champ_Fonc::~Ref_Champ_Fonc ()
Definition at line 26 of file Ref_Champ_Fonc.cpp.
Ref_Champ_Fonc::Ref_Champ_Fonc ()
Definition at line 26 of file Ref_Champ_Fonc.cpp.
Ref_Champ_Fonc::Ref_Champ_Fonc (const Champ_Fonc & t)
Definition at line 26 of file Ref_Champ_Fonc.cpp.
Ref_Champ_Fonc::Ref_Champ_Fonc (const Ref_Champ_Fonc & t)
Definition at line 26 of file Ref_Champ_Fonc.cpp.
Member Function Documentation
Objet_U * Ref_Champ_Fonc::cree_instance () [static]
Definition at line 26 of file Ref_Champ_Fonc.cpp.
int Ref_Champ_Fonc::duplique () const [virtual]
Implements Ref_.
Definition at line 26 of file Ref_Champ_Fonc.cpp.
const Type_info * Ref_Champ_Fonc::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Fonc.cpp.
const Type_info & Ref_Champ_Fonc::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Ref_Champ_Fonc.cpp.
const Type_info * Ref_Champ_Fonc::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Fonc.cpp.
Ref_Champ_Fonc::operator Champ_Fonc & ()
Definition at line 26 of file Ref_Champ_Fonc.cpp.
Ref_Champ_Fonc::operator const Champ_Fonc & () const
Definition at line 26 of file Ref_Champ_Fonc.cpp.
const Champ_Fonc * Ref_Champ_Fonc::operator-> () const [inline]
Definition at line 28 of file Ref_Champ_Fonc.h.
Champ_Fonc * Ref_Champ_Fonc::operator-> () [inline]
Definition at line 28 of file Ref_Champ_Fonc.h.
const Ref_Champ_Fonc & Ref_Champ_Fonc::operator= (const Ref_Champ_Fonc & t)
Definition at line 26 of file Ref_Champ_Fonc.cpp.
const Ref_Champ_Fonc & Ref_Champ_Fonc::operator= (const Champ_Fonc & t)
Definition at line 26 of file Ref_Champ_Fonc.cpp.
Sortie & Ref_Champ_Fonc::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Fonc.cpp.
Entree & Ref_Champ_Fonc::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Fonc.cpp.
const Ref_Champ_Fonc & Ref_Champ_Fonc::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Fonc.cpp.
Ref_Champ_Fonc & Ref_Champ_Fonc::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 26 of file Ref_Champ_Fonc.cpp.
void Ref_Champ_Fonc::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Ref_Champ_Fonc.cpp.
unsigned Ref_Champ_Fonc::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Ref_Champ_Fonc.cpp.
const Champ_Fonc & Ref_Champ_Fonc::valeur () const [inline]
Definition at line 28 of file Ref_Champ_Fonc.h.
Referenced by Eval_Dift_VDF_var::diffusivite_turbulente(), Eval_Dift_VDF_Multi_inco_var::diffusivite_turbulente(), Eval_Dift_VDF_Multi_inco_const::diffusivite_turbulente(), Eval_Dift_VDF_const::diffusivite_turbulente(), and Op_Diff_Turbulent_base::diffusivite_turbulente().
Champ_Fonc & Ref_Champ_Fonc::valeur () [inline]
Definition at line 28 of file Ref_Champ_Fonc.h.
Member Data Documentation
const Type_info Ref_Champ_Fonc::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Champ_Fonc.h.
Champ_Fonc* Ref_Champ_Fonc::pointeur_ [private]
Definition at line 28 of file Ref_Champ_Fonc.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Ref_Champ_Fonc.h
src/Kernel/Framework/Ref_Champ_Fonc.cpp