TRUST: Deriv_Schema_Temps_base Class Reference
Deriv_Schema_Temps_base Class Reference
#include <Schema_Temps.h>
Public Member Functions
~Deriv_Schema_Temps_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Schema_Temps_base ()
Deriv_Schema_Temps_base (const Deriv_Schema_Temps_base &)
const Schema_Temps_base & valeur () const
Schema_Temps_base & valeur ()
const Schema_Temps_base * operator-> () const
Schema_Temps_base * operator-> ()
const Deriv_Schema_Temps_base & operator= (const Schema_Temps_base &)
const Deriv_Schema_Temps_base & operator= (const Deriv_Schema_Temps_base &)
operator const Schema_Temps_base & () const
operator Schema_Temps_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Schema_Temps_base & self_cast (Objet_U &)
static const
Deriv_Schema_Temps_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Schema_Temps_base * pointeur_
Detailed Description
Definition at line 29 of file Schema_Temps.h.
Constructor & Destructor Documentation
Deriv_Schema_Temps_base::~Deriv_Schema_Temps_base ()
Definition at line 25 of file Schema_Temps.cpp.
Deriv_Schema_Temps_base::Deriv_Schema_Temps_base ()
Definition at line 25 of file Schema_Temps.cpp.
Deriv_Schema_Temps_base::Deriv_Schema_Temps_base (const Deriv_Schema_Temps_base & t)
Definition at line 25 of file Schema_Temps.cpp.
Member Function Documentation
Objet_U * Deriv_Schema_Temps_base::cree_instance () [static]
Reimplemented in Schema_Temps.
Definition at line 25 of file Schema_Temps.cpp.
int Deriv_Schema_Temps_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Schema_Temps.
Definition at line 25 of file Schema_Temps.cpp.
const Type_info * Deriv_Schema_Temps_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Schema_Temps.
Definition at line 25 of file Schema_Temps.cpp.
const Type_info & Deriv_Schema_Temps_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Schema_Temps.cpp.
const Type_info * Deriv_Schema_Temps_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Schema_Temps.
Definition at line 25 of file Schema_Temps.cpp.
Deriv_Schema_Temps_base::operator const Schema_Temps_base & () const
Definition at line 25 of file Schema_Temps.cpp.
Deriv_Schema_Temps_base::operator Schema_Temps_base & ()
Definition at line 25 of file Schema_Temps.cpp.
const Schema_Temps_base * Deriv_Schema_Temps_base::operator-> () const [inline]
Definition at line 29 of file Schema_Temps.h.
: public DERIV(Schema_Temps_base)
Schema_Temps_base * Deriv_Schema_Temps_base::operator-> () [inline]
Definition at line 29 of file Schema_Temps.h.
: public DERIV(Schema_Temps_base)
const Deriv_Schema_Temps_base & Deriv_Schema_Temps_base::operator= (const Deriv_Schema_Temps_base & t)
Definition at line 25 of file Schema_Temps.cpp.
const Deriv_Schema_Temps_base & Deriv_Schema_Temps_base::operator= (const Schema_Temps_base & t)
Reimplemented in Schema_Temps.
Definition at line 25 of file Schema_Temps.cpp.
Sortie & Deriv_Schema_Temps_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Schema_Temps.
Definition at line 25 of file Schema_Temps.cpp.
Entree & Deriv_Schema_Temps_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Schema_Temps.
Definition at line 25 of file Schema_Temps.cpp.
const Deriv_Schema_Temps_base & Deriv_Schema_Temps_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Schema_Temps.
Definition at line 25 of file Schema_Temps.cpp.
Deriv_Schema_Temps_base & Deriv_Schema_Temps_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Schema_Temps.
Definition at line 25 of file Schema_Temps.cpp.
void Deriv_Schema_Temps_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Schema_Temps.cpp.
unsigned Deriv_Schema_Temps_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Schema_Temps.
Definition at line 25 of file Schema_Temps.cpp.
const Schema_Temps_base & Deriv_Schema_Temps_base::valeur () const [inline]
Definition at line 29 of file Schema_Temps.h.
Referenced by Multi_Sch_ThHyd::changer_temps_courant(), Schema_Temps::changer_temps_courant(), Multi_Sch_ThHyd::completer(), Multi_Sch_ThHyd::corriger_dt_calcule(), Schema_Temps::corriger_dt_calcule(), Schema_Temps::facteur_securite_pas(), Multi_Sch_ThHyd::faire_un_pas_de_temps_eqn_base(), Schema_Temps::faire_un_pas_de_temps_eqn_base(), Schema_Temps::impr(), Multi_Sch_ThHyd::imprimer(), Schema_Temps::imprimer(), Schema_Temps::initTimeStep(), Schema_Temps::iterateTimeStep(), Schema_Temps::lsauv(), Schema_Temps::mettre_a_jour(), Schema_Temps::nb_pas_dt(), Multi_Sch_ThHyd::nb_valeurs_futures(), Multi_Sch_ThHyd::nb_valeurs_temporelles(), Schema_Temps::pas_de_temps(), Schema_Temps::pas_temps_max(), Schema_Temps::pas_temps_min(), Pbc_MED::readOn(), Schema_Temps::reprendre(), Schema_Temps::sauvegarder(), Multi_Sch_ThHyd::stop(), Schema_Temps::stop(), Schema_Temps::temps_calcul(), Schema_Temps::temps_courant(), Multi_Sch_ThHyd::temps_defaut(), and Multi_Sch_ThHyd::temps_futur().
: public DERIV(Schema_Temps_base)
Schema_Temps_base & Deriv_Schema_Temps_base::valeur () [inline]
Definition at line 29 of file Schema_Temps.h.
: public DERIV(Schema_Temps_base)
Member Data Documentation
const Type_info Deriv_Schema_Temps_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Schema_Temps.
Definition at line 29 of file Schema_Temps.h.
Schema_Temps_base* Deriv_Schema_Temps_base::pointeur_ [private]
Definition at line 29 of file Schema_Temps.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Schema_Temps.h
src/Kernel/Framework/Schema_Temps.cpp