TRUST: Elem_VEF_base Class Reference
Elem_VEF_base Class Reference
#include <Elem_VEF_base.h>
Public Member Functions
Elem_VEF_base ()
~Elem_VEF_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int nb_facette () const =0
const IntTab & KEL () const
virtual void creer_facette_normales (const Zone &, DoubleTab &, const IntVect &) const =0
virtual void creer_normales_facettes_Cl (DoubleTab &, int, int, const DoubleTab &, const DoubleVect &, const Zone &) const =0
virtual void modif_volumes_entrelaces (int, int, const Zone_VEF &, DoubleVect &, int) const =0
virtual void modif_volumes_entrelaces_faces_joints (int, int, const Zone_VEF &, DoubleVect &, int) const =0
virtual void modif_normales_facettes_Cl (DoubleTab &, int, int, int, int, int, int) const =0
virtual void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int, const DoubleVect &) const =0
virtual void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const =0
virtual void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const =0
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Elem_VEF_base & self_cast (Objet_U &)
static const Elem_VEF_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
IntTab KEL_
Detailed Description
Definition at line 37 of file Elem_VEF_base.h.
Constructor & Destructor Documentation
Elem_VEF_base::Elem_VEF_base ()
Definition at line 26 of file Elem_VEF_base.cpp.
Elem_VEF_base::~Elem_VEF_base ()
Definition at line 26 of file Elem_VEF_base.cpp.
Member Function Documentation
virtual void Elem_VEF_base::calcul_vc (const ArrOfInt & , ArrOfDouble & , const ArrOfDouble & , const DoubleTab & , const Champ_Inc_base & , int , const DoubleVect &) const [pure virtual]
Implemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Referenced by Op_Conv_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter_contribution(), Elem_VEF::calcul_vc(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), and Op_Conv_VEF_Face::remplir_fluent().
virtual void Elem_VEF_base::calcul_xg (DoubleVect & , const DoubleTab & , const int , int & , int & , int & , int &) const [pure virtual]
Implemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Referenced by Op_Conv_VEF_Face::ajouter(), and Elem_VEF::calcul_xg().
virtual void Elem_VEF_base::creer_facette_normales (const Zone & , DoubleTab & , const IntVect &) const [pure virtual]
Implemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Referenced by Elem_VEF::creer_facette_normales().
virtual void Elem_VEF_base::creer_normales_facettes_Cl (DoubleTab & , int , int , const DoubleTab & , const DoubleVect & , const Zone &) const [pure virtual]
Implemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Referenced by Elem_VEF::creer_normales_facettes_Cl().
virtual int Elem_VEF_base::duplique () const [pure virtual]
Implements Objet_U.
Implemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
const Type_info * Elem_VEF_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Definition at line 26 of file Elem_VEF_base.cpp.
const Type_info * Elem_VEF_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Definition at line 26 of file Elem_VEF_base.cpp.
const IntTab& Elem_VEF_base::KEL () const [inline]
Definition at line 47 of file Elem_VEF_base.h.
References KEL_.
Referenced by Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_Muscl_New_VEF_Face::ajouter_diffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Op_Conv_VEF_Face::remplir_fluent(), Zone_Cl_VEF::remplir_normales_facettes_Cl(), and Zone_VEF::vecteur_face_facette().
  {
    return KEL_;
  };
virtual void Elem_VEF_base::modif_normales_facettes_Cl (DoubleTab & , int , int , int , int , int , int) const [pure virtual]
Implemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Referenced by Elem_VEF::modif_normales_facettes_Cl().
virtual void Elem_VEF_base::modif_volumes_entrelaces (int , int , const Zone_VEF & , DoubleVect & , int) const [pure virtual]
Implemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Referenced by Elem_VEF::modif_volumes_entrelaces().
virtual void Elem_VEF_base::modif_volumes_entrelaces_faces_joints (int , int , const Zone_VEF & , DoubleVect & , int) const [pure virtual]
Implemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Referenced by Elem_VEF::modif_volumes_entrelaces_faces_joints().
virtual int Elem_VEF_base::nb_facette () const [pure virtual]
Implemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Referenced by Elem_VEF::nb_facette().
virtual void Elem_VEF_base::normale (int , DoubleTab & , const IntTab & , const IntTab & , const IntTab & , const Zone &) const [pure virtual]
Implemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Referenced by Elem_VEF::normale().
Sortie & Elem_VEF_base::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Definition at line 30 of file Elem_VEF_base.cpp.
{
  return s;
}
Entree & Elem_VEF_base::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Definition at line 35 of file Elem_VEF_base.cpp.
{
  return is;
}
const Elem_VEF_base & Elem_VEF_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Reimplemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Definition at line 26 of file Elem_VEF_base.cpp.
Elem_VEF_base & Elem_VEF_base::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Reimplemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Definition at line 26 of file Elem_VEF_base.cpp.
Member Data Documentation
const Type_info Elem_VEF_base::info_obj [static]
Reimplemented from Objet_U.
Reimplemented in Hexa_VEF, Quadri_VEF, Tetra_VEF, and Tri_VEF.
Definition at line 40 of file Elem_VEF_base.h.
IntTab Elem_VEF_base::KEL_ [protected]
Definition at line 68 of file Elem_VEF_base.h.
Referenced by Tri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Hexa_VEF::creer_facette_normales(), Tri_VEF::creer_normales_facettes_Cl(), Tetra_VEF::creer_normales_facettes_Cl(), Hexa_VEF::creer_normales_facettes_Cl(), Hexa_VEF::Hexa_VEF(), KEL(), Quadri_VEF::Quadri_VEF(), Tetra_VEF::Tetra_VEF(), and Tri_VEF::Tri_VEF().
The documentation for this class was generated from the following files:
src/VEF/Zones/Elem_VEF_base.h
src/VEF/Zones/Elem_VEF_base.cpp