TRUST: OrienteFacesBord Class Reference
OrienteFacesBord Class Reference
#include <OrienteFacesBord.h>
Public Member Functions
OrienteFacesBord ()
~OrienteFacesBord ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static OrienteFacesBord & self_cast (Objet_U &)
static const OrienteFacesBord & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void oriente_faces_bord (const Nom &nom_dom)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Definition at line 34 of file OrienteFacesBord.h.
Constructor & Destructor Documentation
OrienteFacesBord()
OrienteFacesBord::OrienteFacesBord ()
Definition at line 21 of file OrienteFacesBord.cpp.
~OrienteFacesBord()
OrienteFacesBord::~OrienteFacesBord ()
Definition at line 21 of file OrienteFacesBord.cpp.
Member Function Documentation
cree_instance()
Objet_U * OrienteFacesBord::cree_instance () static
Definition at line 21 of file OrienteFacesBord.cpp.
duplique()
int OrienteFacesBord::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file OrienteFacesBord.cpp.
get_info()
const Type_info * OrienteFacesBord::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 21 of file OrienteFacesBord.cpp.
info()
const Type_info * OrienteFacesBord::info () static
Definition at line 21 of file OrienteFacesBord.cpp.
interpreter_()
Entree & OrienteFacesBord::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base.
Definition at line 34 of file OrienteFacesBord.cpp.
{
  associer_domaine(is);
  oriente_faces_bord(domaine().le_nom());
  return is;
}
References Interprete_geometrique_base::associer_domaine(), Interprete_geometrique_base::domaine(), Objet_U::le_nom(), and oriente_faces_bord().
oriente_faces_bord()
void OrienteFacesBord::oriente_faces_bord (const Nom & nom_dom) private
Definition at line 42 of file OrienteFacesBord.cpp.
{
  Domaine& dom=ref_cast(Domaine, objet(nom_dom));
  Zone& zone=dom.zone(0);
  Nom type=dom.zone(0).type_elem()->que_suis_je();
  double e=0.001;
  IntVect elem(1);
  DoubleTab pos(1,dimension);
  const DoubleTab& coords=dom.coord_sommets();
  int nombre_faces_rayonnantes=zone.nb_bords()+zone.nb_raccords();
  for (int iface=0; iface<nombre_faces_rayonnantes; iface++)
    {
      const IntTab& som=(iface<zone.nb_bords()?zone.bord(iface).faces().les_sommets():zone.raccord(iface-zone.nb_bords()).valeur().faces().les_sommets());
      int nb_faces=som.dimension(0);
      IntTab new_faces(nb_faces,som.dimension(1));
      for (int j=0; j<nb_faces; j++)
        {
          if (dimension==2)
            {
              if (axi)
                {
                  double r0,t0,r1,t1;
                  r0=coords(som(j,0),0);
                  t0=coords(som(j,0),1);
                  r1=coords(som(j,1),0);
                  t1=coords(som(j,1),1);
                  if (t1<t0) t1+=2*M_PI;
                  if (est_egal(r0,r1))
                    {
                      pos(0,1)=0.5*(t0+t1);
                      if (t0<t1)
                        pos(0,0)=(1-e)*r0;
                      else
                        pos(0,0)=(1+e)*r0;
                    }
                  else if (est_egal(t0,t1))
                    {
                      pos(0,0)=0.5*(r0+r1);
                      if (r0<r1)
                        pos(0,1)=(1+e)*t0;
                      else
                        pos(0,1)=(1-e)*t0;
                    }
                }
              else
                {
                  double x0,y0,x1,y1;
                  x0=coords(som(j,0),0);
                  y0=coords(som(j,0),1);
                  x1=coords(som(j,1),0);
                  y1=coords(som(j,1),1);
                  double nx=y0-y1;
                  double ny=x1-x0;
                  double alpha=10*Objet_U::precision_geom/(sqrt(nx*nx+ny*ny));
                  pos(0,0)=0.5*(x0+x1)+alpha*nx;
                  pos(0,1)=0.5*(y0+y1)+alpha*ny;
                }
              dom.zone(0).chercher_elements(pos,elem);
              if (elem(0)!=-1)
                {
                  new_faces(j,0) = som(j,0);
                  new_faces(j,1) = som(j,1);
                }
              else
                {
                  new_faces(j,0) = som(j,1);
                  new_faces(j,1) = som(j,0);
                }
            }
          else
            {
              if (axi)
                {
                  double r0,t0,z0,r3,t3,z3;
                  r0=coords(som(j,0),0);
                  t0=coords(som(j,0),1);
                  z0=coords(som(j,0),2);
                  r3=coords(som(j,3),0);
                  t3=coords(som(j,3),1);
                  z3=coords(som(j,3),2);
// Cas ou on repasse a teta=0;
                  if (t3<t0) t3+=2*M_PI;
                  if (est_egal(r0,r3))
                    {
                      pos(0,1)=0.5*(t0+t3);
                      if (t0<t3)
                        pos(0,0)=(1+e)*r0;
                      else
                        pos(0,0)=(1-e)*r0;
                      pos(0,2)=0.5*(z0+z3);
                    }
                  else if (est_egal(z0,z3))
                    {
                      pos(0,0)=0.5*(r0+r3);
                      pos(0,1)=0.5*(t0+t3);
                      if (r0<r3)
                        pos(0,2)=(1+e)*z0;
                      else
                        pos(0,2)=(1-e)*z0;
                    }
                  else if (est_egal(t0,t3))
                    {
                      pos(0,0)=0.5*(r0+r3);
                      pos(0,2)=0.5*(z0+z3);
                      if (r0<r3)
                        pos(0,1)=(1+e)*t0;
                      else
                        pos(0,1)=(1-e)*t0;
                    }
                  dom.zone(0).chercher_elements(pos,elem);
                  if (elem(0)!=-1)
                    {
                      new_faces(j,0) = som(j,0);
                      new_faces(j,1) = som(j,2);
                      new_faces(j,2) = som(j,3);
                      new_faces(j,3) = som(j,1);
                    }
                  else
                    {
                      new_faces(j,0) = som(j,0);
                      new_faces(j,1) = som(j,1);
                      new_faces(j,2) = som(j,3);
                      new_faces(j,3) = som(j,2);
                    }
                }
              else
                {
                  double x0,y0,z0,x1,y1,z1,x2,y2,z2;
                  x0=coords(som(j,0),0);
                  y0=coords(som(j,0),1);
                  z0=coords(som(j,0),2);
                  x1=coords(som(j,1),0);
                  y1=coords(som(j,1),1);
                  z1=coords(som(j,1),2);
                  x2=coords(som(j,2),0);
                  y2=coords(som(j,2),1);
                  z2=coords(som(j,2),2);
                  double nx=(y1-y0)*(z2-z0)-(z1-z0)*(y2-y0);
                  double ny=(z1-z0)*(x2-x0)-(x1-x0)*(z2-z0);
                  double nz=(x1-x0)*(y2-y0)-(y1-y0)*(x2-x0);
                  double alpha=100*Objet_U::precision_geom/(sqrt(nx*nx+ny*ny+nz*nz));
                  pos(0,0)=(x0+x1+x2)/3.+alpha*nx;
                  pos(0,1)=(y0+y1+y2)/3.+alpha*ny;
                  pos(0,2)=(z0+z1+z2)/3.+alpha*nz;
                  dom.zone(0).chercher_elements(pos,elem);
                  /*
                    if (x0>0 && y0>0 && x1>0 && y1>0 && x2>0 && y2>0)
                    {
                    Cout << "nx = " << nx << " " << ny << " " << nz << finl;
                    Cout << "pos = " << pos << finl;
                    Cout << elem(0) << finl;
                    } */
                  if (elem(0)!=-1)
                    {
// Cout << "non inversion" << finl;
                      if (type=="Tetraedre")
{
                          new_faces(j,0) = som(j,0);
                          new_faces(j,1) = som(j,1);
                          new_faces(j,2) = som(j,2);
                        }
                      else
{
                          new_faces(j,0) = som(j,0);
                          new_faces(j,1) = som(j,1);
                          new_faces(j,2) = som(j,3);
                          new_faces(j,3) = som(j,2);
                        }
                    }
                  else
                    {
// Cout << "inversion" << finl;
                      if (type=="Tetraedre")
{
                          new_faces(j,0) = som(j,0);
                          new_faces(j,1) = som(j,2);
                          new_faces(j,2) = som(j,1);
                        }
                      else
{
                          new_faces(j,0) = som(j,0);
                          new_faces(j,1) = som(j,2);
                          new_faces(j,2) = som(j,3);
                          new_faces(j,3) = som(j,1);
                        }
                    }
                  if (elem(0)!=-1)
                    {
                      int el=elem(0);
                      pos(0,0)=(x0+x1+x2)/3.-alpha*nx;
                      pos(0,1)=(y0+y1+y2)/3.-alpha*ny;
                      pos(0,2)=(z0+z1+z2)/3.-alpha*nz;
                      dom.zone(0).chercher_elements(pos,elem);
                      if (elem(0)!=-1)
{
                          Cerr << "Case not implemented in the OrienteFacesBord algorithm! " << finl;
                          Cerr << "The face " << j << " is surrounded by the two elements " << el << " " << elem(0) << finl;
                          Cerr << alpha*nx << finl;
                          Cerr << alpha*ny << finl;
                          Cerr << alpha*nz << finl;
                          Cerr << "Contact TRUST support." <<finl;
                          exit();
                        }
                    }
                }
            }
        }
      if (iface<zone.nb_bords())
        zone.bord(iface).faces().les_sommets().ref(new_faces);
      else
        zone.raccord(iface-zone.nb_bords()).valeur().faces().les_sommets().ref(new_faces);
    }
}
References Objet_U::axi, Zone::bord(), Cerr, Zone::chercher_elements(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, est_egal(), Process::exit(), Frontiere::faces(), finl, Faces::les_sommets(), M_PI, Zone::nb_bords(), Zone::nb_raccords(), Interprete::objet(), Objet_U::precision_geom, Objet_U::que_suis_je(), Zone::raccord(), TRUSTTab< _TYPE_ >::ref(), ref_cast, Zone::type_elem(), Deriv_Raccord_base::valeur(), and Domaine::zone().
Referenced by interpreter_().
printOn()
Sortie & OrienteFacesBord::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 24 of file OrienteFacesBord.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & OrienteFacesBord::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 29 of file OrienteFacesBord.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const OrienteFacesBord & OrienteFacesBord::self_cast (const Objet_U & r) static
Definition at line 21 of file OrienteFacesBord.cpp.
self_cast() [2/2]
OrienteFacesBord & OrienteFacesBord::self_cast (Objet_U & r) static
Definition at line 21 of file OrienteFacesBord.cpp.
taille_memoire()
unsigned OrienteFacesBord::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file OrienteFacesBord.cpp.
Member Data Documentation
info_obj
const Type_info OrienteFacesBord::info_obj static
Definition at line 36 of file OrienteFacesBord.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/OrienteFacesBord.h
src/Kernel/Geometrie/OrienteFacesBord.cpp