TRUST: Deriv_Operateur_Evanescence_base Class Reference
Deriv_Operateur_Evanescence_base Class Reference
#include <Operateur_Evanescence_base.h>
Public Member Functions
~Deriv_Operateur_Evanescence_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Operateur_Evanescence_base ()
Deriv_Operateur_Evanescence_base (const Deriv_Operateur_Evanescence_base &)
const Operateur_Evanescence_base & valeur () const
Operateur_Evanescence_base & valeur ()
const Operateur_Evanescence_base * operator-> () const
Operateur_Evanescence_base * operator-> ()
const
Deriv_Operateur_Evanescence_base & operator= (const Operateur_Evanescence_base &)
const
Deriv_Operateur_Evanescence_base & operator= (const Deriv_Operateur_Evanescence_base &)
operator const Operateur_Evanescence_base & () const
operator Operateur_Evanescence_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Deriv_Operateur_Evanescence_base & self_cast (Objet_U &)
static const
Deriv_Operateur_Evanescence_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Operateur_Evanescence_base * pointeur_
Detailed Description
Definition at line 44 of file Operateur_Evanescence_base.h.
Constructor & Destructor Documentation
Deriv_Operateur_Evanescence_base::~Deriv_Operateur_Evanescence_base ()
Definition at line 30 of file Operateur_Evanescence.cpp.
Deriv_Operateur_Evanescence_base::Deriv_Operateur_Evanescence_base ()
Definition at line 30 of file Operateur_Evanescence.cpp.
Deriv_Operateur_Evanescence_base::Deriv_Operateur_Evanescence_base (const Deriv_Operateur_Evanescence_base & t)
Definition at line 30 of file Operateur_Evanescence.cpp.
Member Function Documentation
Objet_U * Deriv_Operateur_Evanescence_base::cree_instance () [static]
Reimplemented in Operateur_Evanescence.
Definition at line 30 of file Operateur_Evanescence.cpp.
int Deriv_Operateur_Evanescence_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Operateur_Evanescence.
Definition at line 30 of file Operateur_Evanescence.cpp.
const Type_info * Deriv_Operateur_Evanescence_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Operateur_Evanescence.
Definition at line 30 of file Operateur_Evanescence.cpp.
const Type_info & Deriv_Operateur_Evanescence_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 30 of file Operateur_Evanescence.cpp.
const Type_info * Deriv_Operateur_Evanescence_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Operateur_Evanescence.
Definition at line 30 of file Operateur_Evanescence.cpp.
Deriv_Operateur_Evanescence_base::operator const Operateur_Evanescence_base & () const
Definition at line 30 of file Operateur_Evanescence.cpp.
Deriv_Operateur_Evanescence_base::operator Operateur_Evanescence_base & ()
Definition at line 30 of file Operateur_Evanescence.cpp.
const Operateur_Evanescence_base * Deriv_Operateur_Evanescence_base::operator-> () const [inline]
Definition at line 44 of file Operateur_Evanescence_base.h.
Operateur_Evanescence_base * Deriv_Operateur_Evanescence_base::operator-> () [inline]
Definition at line 44 of file Operateur_Evanescence_base.h.
const Deriv_Operateur_Evanescence_base & Deriv_Operateur_Evanescence_base::operator= (const Deriv_Operateur_Evanescence_base & t)
Definition at line 30 of file Operateur_Evanescence.cpp.
const Deriv_Operateur_Evanescence_base & Deriv_Operateur_Evanescence_base::operator= (const Operateur_Evanescence_base & t)
Definition at line 30 of file Operateur_Evanescence.cpp.
Sortie & Deriv_Operateur_Evanescence_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Operateur_Evanescence.
Definition at line 30 of file Operateur_Evanescence.cpp.
Entree & Deriv_Operateur_Evanescence_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Operateur_Evanescence.
Definition at line 30 of file Operateur_Evanescence.cpp.
const Deriv_Operateur_Evanescence_base & Deriv_Operateur_Evanescence_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Operateur_Evanescence.
Definition at line 30 of file Operateur_Evanescence.cpp.
Deriv_Operateur_Evanescence_base & Deriv_Operateur_Evanescence_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Operateur_Evanescence.
Definition at line 30 of file Operateur_Evanescence.cpp.
void Deriv_Operateur_Evanescence_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 30 of file Operateur_Evanescence.cpp.
unsigned Deriv_Operateur_Evanescence_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Operateur_Evanescence.
Definition at line 30 of file Operateur_Evanescence.cpp.
const Operateur_Evanescence_base & Deriv_Operateur_Evanescence_base::valeur () const [inline]
Definition at line 44 of file Operateur_Evanescence_base.h.
Referenced by Operateur_Evanescence::ajouter(), Operateur_Evanescence::calculer(), QDM_Multiphase::dimensionner_matrice_sans_mem(), Masse_Multiphase::dimensionner_matrice_sans_mem(), Energie_Multiphase::dimensionner_matrice_sans_mem(), QDM_Multiphase::has_interface_blocs(), Masse_Multiphase::has_interface_blocs(), Energie_Multiphase::has_interface_blocs(), Operateur_Evanescence::l_op_base(), and Operateur_Evanescence::typer().
Operateur_Evanescence_base & Deriv_Operateur_Evanescence_base::valeur () [inline]
Definition at line 44 of file Operateur_Evanescence_base.h.
Member Data Documentation
const Type_info Deriv_Operateur_Evanescence_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Operateur_Evanescence.
Definition at line 44 of file Operateur_Evanescence_base.h.
Operateur_Evanescence_base* Deriv_Operateur_Evanescence_base::pointeur_ [private]
Definition at line 44 of file Operateur_Evanescence_base.h.
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Operateurs/Operateur_Evanescence_base.h
src/ThHyd/Multiphase/Operateurs/Operateur_Evanescence.cpp