TRUST: Champ_Generique_Transformation Class Reference
Champ_Generique_Transformation Class Reference
class Champ_Generique_Transformation
Champ destine a post-traiter une "transformation" dependant de champs generiques et (ou) de x,y,z et t
La classe porte un :
-vecteur de Parseur (fxyz)
-la (les) expression(s) pour exprimer la transformation (les_fct)
-la methode de transformation choisie (methode_)
#include <Champ_Generique_Transformation.h>
Public Member Functions
Champ_Generique_Transformation ()
~Champ_Generique_Transformation ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void verifier_coherence_donnees ()
void verifier_localisation ()
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
const Champ_base & get_champ (Champ &espace_stockage) const override
const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const override
Entity get_localisation (const int index=-1) const override
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
const Motcle get_directive_pour_discr () const override
void completer (const Postraitement_base &post) override
void nommer_source () override
int preparer_macro ()
void creer_expression_macro ()
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
Champ_Gen_de_Champs_Gen ()
~Champ_Gen_de_Champs_Gen () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual List_Champ_Generique & get_set_sources ()
virtual Champ_Generique & get_set_source ()
void reset () override
int sauvegarder (Sortie &os) const override
sauvegarde des differentes sources
int reprendre (Entree &is) override
reprise des differentes sources
void completer (const Postraitement_base &post) override
void mettre_a_jour (double temps) override
virtual Champ_Fonc & creer_espace_stockage (const Nature_du_champ &nature, const int nb_comp, Champ_Fonc &es_tmp) const
virtual const Champ_Generique_base & get_source (int i) const
virtual Champ_Generique_base & set_source (int i)
virtual int get_nb_sources () const
int get_dimension () const override
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
void get_property_names (Motcles &list) const override
Renvoie la liste des "query" possibles pour le champ.
double get_time () const override
Renvoie le temps du Champ_Generique.
const Probleme_base & get_ref_pb_base () const override
const Discretisation_base & get_discretisation () const override
const Motcle get_directive_pour_discr () const override
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Entity get_localisation (const int index=-1) const override
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
const DoubleTab & get_ref_values () const override
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_copy_values (DoubleTab &) const override
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
const Domaine & get_ref_domain () const override
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
void get_copy_domain (Domaine &) const override
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_dis_base & get_ref_zone_dis_base () const override
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_Cl_dis_base & get_ref_zcl_dis_base () const override
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
const DoubleTab & get_ref_coordinates () const override
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
void get_copy_coordinates (DoubleTab &) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const override
void nommer_sources ()
virtual void nommer_source ()
int get_info_type_post () const override
const Champ_Generique_base & get_champ_post (const Motcle &nom) const override
int comprend_champ_post (const Motcle &identifiant) const override
virtual void fixer_serie (const double t1, const double t2)
virtual void fixer_tstat_deb (const double t1, const double t2)
virtual void lire_bidon (Entree &is) const
Public Member Functions inherited from Champ_Generique_base
Champ_Generique_base ()
~Champ_Generique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int get_dimension () const
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
virtual double get_time () const
Renvoie le temps du Champ_Generique.
virtual const Probleme_base & get_ref_pb_base () const
virtual const Discretisation_base & get_discretisation () const
virtual const Motcle get_directive_pour_discr () const
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
virtual const Nom & get_nom_post () const
virtual void get_property_names (Motcles &list) const
Renvoie la liste des "query" possibles pour le champ.
virtual const Noms get_property (const Motcle &query) const
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
virtual Entity get_localisation (const int index=-1) const
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
virtual int get_nb_localisations () const
virtual const DoubleTab & get_ref_values () const
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_copy_values (DoubleTab &) const
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const
virtual const Domaine & get_ref_domain () const
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual void get_copy_domain (Domaine &) const
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_dis_base & get_ref_zone_dis_base () const
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_Cl_dis_base & get_ref_zcl_dis_base () const
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
virtual const DoubleTab & get_ref_coordinates () const
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
virtual void get_copy_coordinates (DoubleTab &) const
virtual const IntTab & get_ref_connectivity (Entity index1, Entity index2) const
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
virtual void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const
virtual void reset ()=0
virtual void completer (const Postraitement_base &post)=0
virtual void mettre_a_jour (double temps)=0
virtual const Champ_base & get_champ (Champ &espace_stockage) const =0
virtual const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const =0
virtual const Champ_Generique_base & get_champ_post (const Motcle &nom) const
virtual int comprend_champ_post (const Motcle &identifiant) const
virtual int get_info_type_post () const =0
void fixer_identifiant_appel (const Nom &identifiant)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Generique_Transformation & self_cast (Objet_U &)
static const Champ_Generique_Transformation & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Gen_de_Champs_Gen
static const Type_info * info ()
static Champ_Gen_de_Champs_Gen & self_cast (Objet_U &)
static const Champ_Gen_de_Champs_Gen & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Generique_base
static const Type_info * info ()
static Champ_Generique_base & self_cast (Objet_U &)
static const Champ_Generique_base & self_cast (const Objet_U &)
static int composante (const Nom &nom_test, const Nom &nom, const Noms &composantes, const Noms &synonyms)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Gen_de_Champs_Gen
static const Type_info info_obj
Static Public Attributes inherited from Champ_Generique_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Champ_Generique_base
Sortie & printOn (Sortie &x) const override
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom methode_
Noms les_fct
Vect_Parser_U fxyz
int nb_comp_
Motcle localisation_
Nature_du_champ nature_ch
Protected Attributes inherited from Champ_Gen_de_Champs_Gen
List_Nom noms_sources_ref_
List_Ref_Champ_Generique_base sources_reference_
Protected Attributes inherited from Champ_Generique_base
Nom nom_post_
Nom identifiant_appel_
Nom nom_pb_
Ref_Probleme_base ref_pb_
Additional Inherited Members
Static Protected Member Functions inherited from Champ_Generique_base
static void assert_parallel (int)
Detailed Description
class Champ_Generique_Transformation
Champ destine a post-traiter une "transformation" dependant de champs generiques et (ou) de x,y,z et t
La classe porte un :
-vecteur de Parseur (fxyz)
-la (les) expression(s) pour exprimer la transformation (les_fct)
-la methode de transformation choisie (methode_)
Definition at line 79 of file Champ_Generique_Transformation.h.
Constructor & Destructor Documentation
Champ_Generique_Transformation()
Champ_Generique_Transformation::Champ_Generique_Transformation ()
Definition at line 36 of file Champ_Generique_Transformation.cpp.
~Champ_Generique_Transformation()
Champ_Generique_Transformation::~Champ_Generique_Transformation ()
Definition at line 36 of file Champ_Generique_Transformation.cpp.
Member Function Documentation
completer()
void Champ_Generique_Transformation::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 163 of file Champ_Generique_Transformation.cpp.
{
  bool sources_location_ok = true;
  bool fictive_source = false;
  int nb_source_fictive=0;
  int nb_sources = get_nb_sources();
  if (nb_sources==0)
    {
      nb_source_fictive = 1;
      Champ_Generique& new_src = get_set_sources().add(Champ_Generique());
      Nom nom_probleme = ref_cast(Postraitement,post).probleme().le_nom();
      const Objet_U& ob = interprete().objet(nom_probleme);
      const Probleme_base& pb = ref_cast(Probleme_base,ob);
      const Nom& nom_champ = pb.equation(0).inconnue().le_nom();
      Entree s_bidon;
      Nom ajout("");
      ajout += " Champ_Post_refChamp { Pb_champ ";
      ajout += pb.le_nom();
      ajout += " ";
      ajout += nom_champ;
      ajout += " }";
      Entree_complete s_complete(ajout,s_bidon);
      s_complete>>new_src;
      nb_sources = get_nb_sources();
    }
  Champ_Gen_de_Champs_Gen::completer(post);
  if (nb_source_fictive==1)
    {
      if (get_nb_sources()>1)
        {
          assert( get_set_sources().size( ) == 1 );
// on a rajoute une source pour rien ...
          get_set_sources().vide();
          nb_source_fictive = 0;
        }
    }
  nb_sources = get_nb_sources();
// On determine le nombre de composantes qui sera attribue
// a l espace de stockage rendu par ce champ de postraitement en
// recherchant la source qui possede le plus grand nombre de composantes
  nb_comp_ = 1;
  nature_ch = scalaire;
  if (nb_source_fictive==0)
    {
      for (int i=0; i<nb_sources; i++)
        {
          Champ source_espace_stockage;
          const Champ_base& source = get_source(i).get_champ_without_evaluation(source_espace_stockage);
          if ((Motcle(methode_) == "vecteur"))
            {
              if (source.nature_du_champ()!=scalaire)
                {
                  Cerr<<que_suis_je()<<" The source fields must be of scalar nature for option vecteur."<<finl;
                  exit();
                }
            }
          int nb_comp = source.nb_comp();
          nb_comp_ = (nb_comp_<nb_comp)?  nb_comp:nb_comp_;
          if (source.nature_du_champ()==vectoriel)
            nature_ch = vectoriel;
          else if (source.nature_du_champ()==multi_scalaire)
            nature_ch = multi_scalaire;
        }
    }
// Si aucun champ source n a ete specifie on en ajoute une
// pour donner acces a la zone discretisee ...
  Noms sources_location;
  if( nb_source_fictive > 0 )
    {
// special treatment when we have fictives sources
// the user needs to provide a location
      if( localisation_ == "??" )
        {
// On prend la localisation de l'inconnue
          Cerr << "Error in Champ_Generique_Transformation::completer "<<finl;
          Cerr << "No sources were specified. So you need to specify at least the location."<<finl;
          Cerr << "Aborting..."<<finl;
          Cerr << "ToDo for developer: guess location by taking the pb.equation(0).inconnue() localization." << finl;
          Process::abort( );
        }
      else
        {
          fictive_source = true;
        }
    }
  else
    {
// real sources
      for( int i=0; i<nb_sources; i++)
        {
// loop over sources to check that all sources have the same location
          bool use_directive = false;
          Champ my_field;
          const Champ_base& source_i = get_source( i ).get_champ_without_evaluation( my_field );
          if( source_i.a_une_zone_dis_base( ) )
            {
              const Zone_dis_base& zone_source_i = source_i.zone_dis_base( );
              if( ! sub_type( Zone_VF , zone_source_i ) )
                {
                  Cerr << "Warning in Champ_Generique_Transformation::completer "<<finl;
                  Cerr << "The source number "<<i<<" has a zone_dis_base but not of type Zone_VF so use directive to determine the location"<<finl;
                  use_directive=true;
                }
              if( ! use_directive )
                {
                  const DoubleTab& values_source_i = source_i.valeurs( );
                  const Zone_VF& zvf_source_i = ref_cast( Zone_VF, zone_source_i );
                  MD_Vector md;
                  md = values_source_i.get_md_vector( );
// composite case, in particular Champ_{P0,Face}_PolyMAC...
                  if (zvf_source_i.que_suis_je().debute_par("Zone_PolyMAC") && sub_type( MD_Vector_composite, md.valeur( )))
                    {
                      const MD_Vector& md0 = ref_cast(MD_Vector_composite, md.valeur()).get_desc_part(0);
                      if (md0 == zvf_source_i.zone( ).les_elems().get_md_vector( ))
                        sources_location.add( "elem" );
                      else if (md0 == zvf_source_i.face_sommets( ).get_md_vector( ))
                        sources_location.add("faces");
                    }
                  else if( ( sub_type( MD_Vector_composite, md.valeur( ) ) ) && (localisation_=="??"))
                    {
                      Cerr << "Error in Champ_Generique_Transformation::completer "<<finl;
                      Cerr << "The source number "<<i<<" is composite and the location was not provided. It is forbidden to apply a 'transformation' on a composite source without providing a location. "<<finl;
                      Cerr << "You must perform an interpolation before or specify a location."<<finl;
                      Cerr << "Aborting..."<<finl;
                      Process::abort( );
// if we want to deal with composite case we can do something like...
// MD_Vector_composite md_comp = ref_cast(MD_Vector_composite, values_source_i.get_md_vector().valeur());
// nb_parts = md_comp.nb_parts(); //to perform loop over parts and then get the considered part :
// md = md_comp.get_desc_part(part);
// when dealing with pression_pa it leads to have elem and som locations
                    }
                  else if ( md == zvf_source_i.face_sommets( ).get_md_vector( ) )
                    {
                      sources_location.add( "faces" );
                    }
                  else if( md == zvf_source_i.zone( ).les_elems( ).get_md_vector( ) )
                    {
                      sources_location.add( "elem" );
                    }
                  else if( md == zvf_source_i.zone( ).domaine( ).les_sommets( ).get_md_vector( ) )
                    {
                      sources_location.add( "som" );
                    }
                  else if( md == zvf_source_i.xa( ).get_md_vector( ) )
                    {
                      sources_location.add( "xa" );
                    }
                  else
                    {
                      Cerr << "Warning in Champ_Generique_Transformation::completer "<<finl;
                      Cerr << "Impossible to determine the localisation of the source number "<<i<<" using md_vectors so try using directive"<<finl;
                      use_directive = true;
                    }
// Cout << "sources location "<<i<<" : "<<sources_location(i)<<finl;
                }//end of not using directive case
            }//end of has zone dis
          else
            {
// in the case where there is no zone dis base, we look at the directive
              use_directive=true;
            }
          if( use_directive )
            {
              Motcle directive = get_source( i ).get_directive_pour_discr( );
              if (directive=="champ_elem")
                sources_location.add( "elem" );
              else if (directive=="champ_sommets")
                sources_location.add( "som" );
              else if (directive=="champ_face")
                sources_location.add( "faces" );
              else if (directive=="pression")
                {
                  if  (localisation_=="??")
                    {
                      Cerr << "Error in Champ_Generique_Transformation::completer"<<finl;
                      Cerr << "The directive associated to the source number "<<i<<" is pressure and the location was not provided.";
                      Cerr <<" It is forbidden to apply a 'transformation' on a composite source without providing a location. "<<finl;
                      Cerr << "You must perform an interpolation before or specify a location." <<finl;
                      Cerr << "Aborting..."<<finl;
                      Process::abort( );
                    }
                  sources_location.add( "unknown" );
                }
              else if ( directive == "champ_uniforme" )
                sources_location.add( "elem" );
              else
                {
                  Cerr<<"Error in Champ_Generique_Transformation::completer"<<finl;
                  Cerr<<"The discretization of the first source of the generic field "<<nom_post_<<finl;
                  Cerr<<"does not correspond to any TRUST field discretization."<<finl;
                  Cerr<<directive<<finl;
                  Cerr<<"Aborting..."<<finl;
                  Process::abort( );
                }
            }
        }//loop over sources
      const int nb_locations = sources_location.size( );
      if( nb_sources != nb_locations )
        {
          Cerr << "Error in Champ_Generique_Transformation::completer "<<finl;
          Cerr << nb_sources<<" were detected but "<<nb_locations<<" were found"<<finl;
          Cerr << "Aborting..."<<finl;
          Process::abort( );
        }
      Nom reference_location = sources_location( 0 );
      for(int i=1; i<nb_locations; i++)
        {
          if( sources_location( i ) != reference_location )
            {
              sources_location_ok = false;
              Cerr << "Warning in Champ_Generique_Transformation::completer "<<finl;
              Cerr << "All sources have location : "<<finl;
              Cerr <<sources_location;
              Cerr <<"But the specified location is "<<localisation_<<finl;
// Cerr << "Aborting..."<<finl;
// Process::abort();
            }
        }
    } //end dealing with nb_source_fictive <= 0
  if( localisation_ == "??" )
    {
      if( sources_location_ok  )
        {
          Cerr <<"sources have same location : "<< sources_location( 0 )<<finl;
        }
      else
        {
          Cerr << "Warning sources have not the same location, taking "<<sources_location( 0 )<<" as location"<<finl;
        }
      localisation_ = sources_location( 0 ) ;
    }
  else
    {
      if( ! fictive_source && localisation_ != sources_location( 0 ) )
        {
          Cerr << "Warning first source is located to "<<sources_location( 0 )<<" but the user has specified "<< localisation_<<finl;
        }
    }
  verifier_localisation();
  preparer_macro();
  if (Motcle(methode_)=="formule")
    {
// on redemande le nb_sources car on a ajoute des sources par completer
      nb_sources = get_nb_sources();
      fxyz.dimensionner(1);
      fxyz[0].setNbVar(4+nb_sources);
      fxyz[0].setString(les_fct[0]);
      fxyz[0].addVar("x");
      fxyz[0].addVar("y");
      fxyz[0].addVar("z");
      fxyz[0].addVar("t");
      for (int i=0; i<nb_sources; i++)
        {
          const Noms nom = get_source(i).get_property("nom");
          fxyz[0].addVar(nom[0]);
          Journal()<<" Name of source "<<nom[0]<<finl;
        }
      fxyz[0].parseString();
    }
}
References Champ_base::a_une_zone_dis_base(), Process::abort(), List_Champ_Generique::add(), Vect_Nom::add(), Cerr, Champ_Gen_de_Champs_Gen::completer(), Nom::debute_par(), vect_impl::dimensionner(), Zone::domaine(), Probleme_base::equation(), Process::exit(), Zone_VF::face_sommets(), finl, fxyz, Champ_Generique_base::get_champ_without_evaluation(), Champ_Generique_base::get_directive_pour_discr(), TRUSTVect< _TYPE_ >::get_md_vector(), Champ_Gen_de_Champs_Gen::get_nb_sources(), Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_set_sources(), Champ_Gen_de_Champs_Gen::get_source(), Equation_base::inconnue(), Objet_U::interprete(), Process::Journal(), Probleme_base::le_nom(), O_U_Ptr::le_nom(), Zone::les_elems(), les_fct, Domaine::les_sommets(), localisation_, methode_, multi_scalaire, nature_ch, Field_base::nature_du_champ(), Field_base::nb_comp(), nb_comp_, Champ_Generique_base::nom_post_, Interprete::objet(), preparer_macro(), Objet_U::que_suis_je(), ref_cast, scalaire, vect_impl::size(), sub_type, MD_Vector::valeur(), Champ_Proto::valeurs(), vectoriel, verifier_localisation(), liste::vide(), Zone_VF::xa(), Zone_dis_base::zone(), and Champ_base::zone_dis_base().
cree_instance()
Objet_U * Champ_Generique_Transformation::cree_instance () static
Definition at line 36 of file Champ_Generique_Transformation.cpp.
creer_expression_macro()
void Champ_Generique_Transformation::creer_expression_macro ()
Definition at line 1014 of file Champ_Generique_Transformation.cpp.
{
  if ((Motcle(methode_)=="produit_scalaire") || (Motcle(methode_)=="norme"))
    {
      const Noms compo0 = get_source(0).get_property("composantes");
      if (Motcle(methode_)=="norme")
        {
          les_fct[0] = "sqrt(";
          les_fct[0] += compo0[0];
          les_fct[0] += "*";
          les_fct[0] += compo0[0];
          les_fct[0] += "+";
          les_fct[0] += compo0[1];
          les_fct[0] += "*";
          les_fct[0] += compo0[1];
          if (dimension==3)
            {
              les_fct[0] += "+";
              les_fct[0] += compo0[2];
              les_fct[0] += "*";
              les_fct[0] += compo0[2];
            }
          les_fct[0] +=")";
        }
      if (Motcle(methode_)=="produit_scalaire")
        {
          const Noms compo1 = get_source(1).get_property("composantes");
          les_fct[0] = compo0[0];
          les_fct[0] += "*";
          les_fct[0] += compo1[0];
          les_fct[0] += "+";
          les_fct[0] += compo0[1];
          les_fct[0] += "*";
          les_fct[0] += compo1[1];
          if (dimension==3)
            {
              les_fct[0] += "+";
              les_fct[0] += compo0[2];
              les_fct[0] += "*";
              les_fct[0] += compo1[2];
            }
        }
    }
}
References Objet_U::dimension, Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), les_fct, and methode_.
Referenced by preparer_macro().
duplique()
int Champ_Generique_Transformation::duplique () const override virtual
Implements Objet_U.
Definition at line 36 of file Champ_Generique_Transformation.cpp.
get_champ()
const Champ_base & Champ_Generique_Transformation::get_champ (Champ & espace_stockage) const override virtual
< deplacement du parametre pour qu'il soit reconnu par l'ensemble des methodes en vue test (voir methode composante ci-dessous)
< line_size > 1
Implements Champ_Generique_base.
Definition at line 503 of file Champ_Generique_Transformation.cpp.
{
  const Zone_dis_base& zone_dis = get_ref_zone_dis_base();
  Champ_Fonc es_tmp;
  espace_stockage = creer_espace_stockage(nature_ch,nb_comp_,es_tmp);
  DoubleTab& valeurs_espace = espace_stockage->valeurs();
// Construction du tableau positions qui contient les coordonnees
// des points (support) ou vont etre evaluees les valeurs de l espace
// de stockage
  const Zone_VF& zvf = ref_cast(Zone_VF,zone_dis);
  DoubleTab positions;
  int nb_pos;
  int nb_elem_tot = zvf.nb_elem_tot();
  int nb_som_tot = get_ref_domain().nb_som_tot();
  const Motcle directive = get_directive_pour_discr();
  bool champ_normal_faces = 0;
  if (zvf.que_suis_je().debute_par("Zone_VDF") || zvf.que_suis_je().debute_par("Zone_PolyMAC"))
    champ_normal_faces = 1;
  if (localisation_ == "elem")
    {
      if (zvf.xp().nb_dim() != 2) /* xp() non initialise */
        {
          zvf.zone().calculer_centres_gravite(positions);
        }
      else
        {
          positions.resize(zvf.nb_elem(), zvf.xp().dimension(1));
          memcpy(positions.addr(), zvf.xp().addr(), positions.size() * sizeof(double));
        }
    }
  else if (localisation_ == "som")
    positions = get_ref_domain().coord_sommets();
  else if (localisation_ == "faces")
    positions = zvf.xv();
  else if (localisation_ == "elem_som")
    {
      const DoubleTab& som = get_ref_domain().coord_sommets();
      int dim = som.dimension(1);
      positions = zvf.xp();
      positions.resize(nb_elem_tot+nb_som_tot,dim);
      for (int i1=nb_elem_tot; i1<nb_elem_tot+nb_som_tot; i1++)
        for (int i2=0; i2<dim; i2++)
          positions(i1,i2) = som(i1-nb_elem_tot,i2);
    }
  else
    {
      Cerr<<"Problem in " <<que_suis_je()<<finl;
      Cerr<<"Item "<<localisation_<<" is not recognized."<<finl;
      exit();
    }
// Interpolation des valeurs des sources sur le support retenu et stockage dans sources_val
  int nb_sources = get_nb_sources();
  nb_pos = positions.dimension(0);
  assert(nb_pos>0||(methode_=="formule")||(methode_=="composante_normale")||(methode_=="vecteur"));
  double x=0;
  double y=0;
  double z=0;
  DoubleTabs sources_val(nb_sources);
  IntVect nb_comps(nb_sources);
  Noms nom_source(nb_sources);
  int dim_compo = 2*dimension;
  Noms compo(dim_compo);
  double temps;
  temps = get_time();
  int nb_compso = 0; //!< deplacement du parametre pour qu'il soit reconnu par l'ensemble des methodes en vue test (voir methode composante ci-dessous)
  for (int so=0; so<nb_sources; so++)
    {
      const Champ_Generique_base& source = get_source(so);
      Champ stockage_so;
      const Champ_base& source_so = source.get_champ(stockage_so);
      const DoubleTab& source_so_val = source_so.valeurs();
      const Motcle directive_so = source.get_directive_pour_discr();
// int nb_compso = source_so.nb_comp();
      nb_compso = source_so.nb_comp();
      nb_comps(so) = nb_compso;
      const Noms nom_champ = source.get_property("nom");
      nom_source[so] = nom_champ[0];
      if ((Motcle(methode_)=="produit_scalaire") || (Motcle(methode_)=="norme"))
        {
          const Noms compo_ch = source.get_property("composantes");
          for (int comp=0; comp<dimension; comp++)
            compo[so*dimension+comp] = compo_ch[comp];
        }
// Si VDF et traitement d un produit scalaire ou d une norme alors on interpole
// pour recuperer un tableau avec autant de composantes que la dimension du probleme
      if (directive!=directive_so)
        {
          sources_val[so].resize(nb_pos,nb_compso);
          if (directive == "CHAMP_FACE") source_so.valeur_aux_faces(sources_val[so]);
          else source_so.valeur_aux(positions,sources_val[so]);
        }
      else
        {
          if (source_so_val.line_size()==1)
            {
              int nn=source_so_val.dimension_tot(0);
              sources_val[so].resize(nn,1);
              for (int i_loc=0; i_loc<nn; i_loc++)
                sources_val[so](i_loc,0) = source_so_val(i_loc);
            }
          else
            sources_val[so] = source_so_val;
        }
      if ((nb_pos==0)&&(valeurs_espace.dimension_tot(0)!=0))
        {
          int nb_pos_tmp=valeurs_espace.dimension(0);
          if (nb_pos_tmp > sources_val[so].size())
            {
              Cerr << "\nError in Champ_Generique_Transformation::get_champ" << finl;
              Cerr << nom_source(so) << " : Wrong number of elements." << finl;
              exit();
            }
        }
    }
// Fin du remplissage de sources_val
// Calcul des valeurs de l espace de stockage en fonction de methode_ selectionne
  if ((Motcle(methode_)=="produit_scalaire") || (Motcle(methode_)=="norme"))
    {
      Parser_U& f = fxyz[0];
      for (int i=0; i<nb_pos; i++)
        {
          for (int so=0; so<nb_sources; so++)
            {
              const DoubleTab& source_so_val = sources_val[so];
              for (int j=0; j<dimension; j++)
                f.setVar(so*dimension+j,source_so_val(i,j));
// Optimisation plus rapide que:
// f.setVar(compo[so*dimension+j],source_so_val(i,j));
            }
          valeurs_espace(i) = f.eval();
        }
    }
  else if (Motcle(methode_)=="vecteur")
    {
      for (int j=0; j<nb_comp_; j++)
        fxyz[j].setVar("t",temps);
      if ((champ_normal_faces) && (localisation_=="faces"))
        {
          for (int i=0; i<nb_pos; i++)
            {
              x = positions(i,0);
              y = positions(i,1);
              z = 0;
              if (dimension>2)
                z = positions(i,2);
              valeurs_espace(i) = 0;
              for (int j=0; j<nb_comp_; j++)
                {
                  fxyz[j].setVar(0,x);
                  fxyz[j].setVar(1,y);
                  fxyz[j].setVar(2,z);
                  for (int so=0; so<nb_sources; so++)
                    {
                      const DoubleTab& source_so_val = sources_val[so];
                      fxyz[j].setVar(so+4,source_so_val(i,0));
                    }
                  valeurs_espace(i) += fxyz[j].eval() * zvf.face_normales(i, j) / zvf.surface(i);
                }
            }
        }
      else
        {
          for (int i=0; i<nb_pos; i++)
            {
              x = positions(i,0);
              y = positions(i,1);
              z = 0;
              if (dimension>2)
                z = positions(i,2);
              for (int j=0; j<nb_comp_; j++)
                {
                  fxyz[j].setVar(0,x);
                  fxyz[j].setVar(1,y);
                  fxyz[j].setVar(2,z);
                  for (int so=0; so<nb_sources; so++)
                    {
                      const DoubleTab& source_so_val = sources_val[so];
                      fxyz[j].setVar(so+4,source_so_val(i,0));
                    }
                  valeurs_espace(i,j) = fxyz[j].eval();
                }
            }
        }
    }
  else if (Motcle(methode_)=="composante_normale")
    {
      const DoubleTab& source_so_val = sources_val[0];
      projette(valeurs_espace,source_so_val,zvf,localisation_,champ_normal_faces);
    }
  else if (Motcle(methode_)=="composante")
    {
      int num_compo = les_fct.size()-1;
      if ((num_compo<0)||(num_compo>=nb_compso))
        {
          Cerr<<"Component number must be >=0 and < "<<nb_compso<<" for composante option."<<finl;
          exit();
        }
      const DoubleTab& source_so_val = sources_val[0];
      if ((champ_normal_faces) && (localisation_=="faces"))
        {
          for (int i=0; i<nb_pos; i++)
            valeurs_espace(i) = source_so_val(i,0) * zvf.face_normales(i, num_compo) / zvf.surface(i);
        }
      else
        {
          for (int i=0; i<nb_pos; i++)
            valeurs_espace(i) = source_so_val(i,num_compo);
        }
    }
  else if (Motcle(methode_)=="formule")
    {
// Evaluation des valeurs de l espace de stockage en fonction de la fonction (les_fct)
      Parser_U& f = fxyz[0];
      f.setVar("t",temps);
      int special=0;
      if ((nb_pos==0)&&(valeurs_espace.dimension_tot(0)!=0))
        {
          special=1;
          nb_pos=valeurs_espace.dimension(0);
          x=1e38;
          y=1e38;
          z=1e38;
          f.setVar(0,x);
          f.setVar(1,y);
          f.setVar(2,z);
        }
      for (int i=0; i<nb_pos; i++)
        {
          if (!special)
            {
              x = positions(i,0);
              y = positions(i,1);
              z = 0;
              if (dimension>2)
                z = positions(i,2);
              f.setVar(0,x);
              f.setVar(1,y);
              f.setVar(2,z);
            }
          /* Plus rapide que de passer par:
             f.setVar("x",x);
             f.setVar("y",y);
             f.setVar("z",z);
          */
          if (valeurs_espace.line_size() == 1)
            {
              for (int so=0; so<nb_sources; so++)
                f.setVar(so+4,sources_val[so](i,0));
              valeurs_espace(i) = f.eval();
            }
          else //!< line_size > 1
            {
              for (int j=0; j<nb_comp_; j++)
                {
                  for (int so=0; so<nb_sources; so++)
                    {
                      int nbcomp_loc = nb_comps(so);
                      if (nbcomp_loc == nb_comp_)
                        f.setVar(so+4,sources_val[so](i,j));
                      else if (nbcomp_loc == 1)
                        f.setVar(so+4,sources_val[so](i,0));
                      else
{
                          Cerr << "The arrays of values don't have compatibles dimensions in "<<que_suis_je()<< finl;
                          exit();
                        }
                    }
                  valeurs_espace(i,j) = f.eval();
                }
            }
        }
    }
// PL: Suppression d'une synchronisation couteuse tres souvent inutile
// Voir Champ_Generique_Interpolation (localisation = som) pour le report de l'echange_espace_virtuel
// valeurs_espace.echange_espace_virtuel();
  return espace_stockage.valeur();
}
References TRUSTArray< _TYPE_ >::addr(), Zone::calculer_centres_gravite(), Cerr, Domaine::coord_sommets(), Champ_Gen_de_Champs_Gen::creer_espace_stockage(), Nom::debute_par(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), Parser_U::eval(), Process::exit(), Zone_VF::face_normales(), finl, fxyz, Champ_Generique_base::get_champ(), Champ_Generique_base::get_directive_pour_discr(), get_directive_pour_discr(), Champ_Gen_de_Champs_Gen::get_nb_sources(), Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_ref_domain(), Champ_Gen_de_Champs_Gen::get_ref_zone_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Gen_de_Champs_Gen::get_time(), les_fct, TRUSTVect< _TYPE_ >::line_size(), localisation_, methode_, nature_ch, Field_base::nb_comp(), nb_comp_, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Domaine::nb_som_tot(), projette(), Objet_U::que_suis_je(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Parser_U::setVar(), TRUSTVect< _TYPE_ >::size(), vect_impl::size(), Zone_VF::surface(), Deriv_Champ_base::valeur(), Champ_base::valeur_aux(), Champ_base::valeur_aux_faces(), Champ::valeurs(), Champ_Proto::valeurs(), Zone_VF::xp(), Zone_VF::xv(), and Zone_dis_base::zone().
get_champ_without_evaluation()
const Champ_base & Champ_Generique_Transformation::get_champ_without_evaluation (Champ & espace_stockage) const override virtual
Implements Champ_Generique_base.
Definition at line 496 of file Champ_Generique_Transformation.cpp.
{
  Champ_Fonc es_tmp;
  espace_stockage = creer_espace_stockage(nature_ch,nb_comp_,es_tmp);
  return espace_stockage.valeur();
}
References Champ_Gen_de_Champs_Gen::creer_espace_stockage(), nature_ch, nb_comp_, and Deriv_Champ_base::valeur().
get_directive_pour_discr()
const Motcle Champ_Generique_Transformation::get_directive_pour_discr () const override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 845 of file Champ_Generique_Transformation.cpp.
{
  Motcle directive;
  if (localisation_=="elem")
    {
      directive = "champ_elem";
    }
  else if (localisation_=="som")
    {
      directive = "champ_sommets";
    }
  else if (localisation_=="faces")
    {
      directive = "champ_face";
    }
  else if (localisation_=="elem_som")
    {
      directive = "pression";
    }
  else
    {
      Cerr<<"Localisation "<<localisation_<<" is not recognized by "<<que_suis_je()<<finl;
      exit();
    }
  return directive;
}
References Cerr, Process::exit(), finl, localisation_, and Objet_U::que_suis_je().
Referenced by get_champ().
get_info()
const Type_info * Champ_Generique_Transformation::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 36 of file Champ_Generique_Transformation.cpp.
get_localisation()
Entity Champ_Generique_Transformation::get_localisation (const int index = -1) const override virtual
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 797 of file Champ_Generique_Transformation.cpp.
{
  Entity loc;
  if (localisation_=="elem")
    loc = ELEMENT;
  else if (localisation_=="som")
    loc = NODE;
  else if (localisation_=="faces")
    loc = FACE;
  else
    {
      Cerr << "Error of type : localisation should be specified to elem or som or faces for the defined field " << nom_post_ << finl;
      throw Champ_Generique_erreur("INVALID");
    }
  return loc;
}
References Cerr, ELEMENT, FACE, finl, localisation_, NODE, and Champ_Generique_base::nom_post_.
get_property()
const Noms Champ_Generique_Transformation::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 814 of file Champ_Generique_Transformation.cpp.
{
  Motcles motcles(2);
  motcles[0] = "composantes";
  motcles[1] = "unites";
  int rang = motcles.search(query);
  switch(rang)
    {
    case 0:
      {
        Noms compo(nb_comp_);
        for (int i=0; i<nb_comp_; i++)
          {
            Nom nume(i);
            compo[i] = nom_post_+nume;
          }
        return compo;
        break;
      }
    case 1:
      {
        Noms unites(nb_comp_);
        for (int comp=0; comp<nb_comp_; comp++)
          unites[comp] = "bidon";
        return unites;
        break;
      }
    }
  return Champ_Gen_de_Champs_Gen::get_property(query);
}
References Champ_Gen_de_Champs_Gen::get_property(), nb_comp_, Champ_Generique_base::nom_post_, and Motcles::search().
info()
const Type_info * Champ_Generique_Transformation::info () static
Definition at line 36 of file Champ_Generique_Transformation.cpp.
lire_motcle_non_standard()
int Champ_Generique_Transformation::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 70 of file Champ_Generique_Transformation.cpp.
{
  if (mot=="expression")
    {
      int dim;
      is >> dim;
      les_fct.dimensionner(dim);
      if ((Motcle(methode_) == "formule") && (dim!=1) )
        {
          Cerr << "The integer N of the expression with FORMULE method must be equal to 1." <<finl;
          Cerr << "Use the VECTEUR expression method for N="<<dim<<finl;
          exit();
        }
      for (int i=0; i<dim; i++)
        is>>les_fct[i];
      return 1;
    }
  else if (mot=="numero")
    {
      int num_compo;
      is >> num_compo;
      nb_comp_ = 1;
      nature_ch = scalaire;
      /*     test numero composante : on ne peut pas se baser sur la dimension de l'espace dans le cas d'un champ multi_scalaire
             Probleme : c'est nb_comp_ qui portera par la suite la dimension des composantes et il est ici initialise a 1 pour eviter bug
             Le test est deplace dans Champ_Generique_Transformation::get_champ
             if ((num_compo<0) || (num_compo>dimension-1))
             {
             //   Cerr<<"Component number must be >=0 and < "<<dimension<<" for composante option."<<finl;
             Cerr<<"Component number must be >=0 for composante option."<<finl;
             exit();
             } */
      les_fct.dimensionner(num_compo+1);
      return 1;
    }
  else
    return Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(mot,is);
  return 1;
}
References Cerr, vect_impl::dimensionner(), Process::exit(), finl, les_fct, Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), methode_, nature_ch, nb_comp_, and scalaire.
nommer_source()
void Champ_Generique_Transformation::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 874 of file Champ_Generique_Transformation.cpp.
{
  if (nom_post_=="??")
    {
      Nom nom_post_source;
      nom_post_source =  "Combinaison_";
      nom_post_source += les_fct[0];
      nommer(nom_post_source);
    }
}
References les_fct, Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
preparer_macro()
int Champ_Generique_Transformation::preparer_macro ()
< 1 source pas la peine de faire une boucle
Definition at line 887 of file Champ_Generique_Transformation.cpp.
{
  int nb_sources = get_nb_sources();
  int nb_var = 0;
  int erreur = 0;
  Nom msg;
  if ((Motcle(methode_)=="produit_scalaire") || (Motcle(methode_)=="norme"))
    {
      for (int i=0; i<nb_sources; i++)
        {
          Champ source_espace_stockage;
          const Champ_base& source = get_source(i).get_champ(source_espace_stockage);
          int nb_comp = source.nb_comp();
          if (source.nature_du_champ()!=vectoriel && source.nature_du_champ()!=multi_scalaire)
            {
              msg = "At least one of the source fields is not of vector nature.";
              erreur = 1;
            }
          nb_var += nb_comp;
        }
      if ((Motcle(methode_)=="produit_scalaire") && (nb_sources!=2))
        {
          msg = "Exactly two vector source fields must be specified.";
          erreur = 1;
        }
      else if ((Motcle(methode_)=="norme") && (nb_sources!=1))
        {
          msg = "Exactly one vector source field must be specified.";
          erreur = 1;
        }
// la suite est faite si on n a pas d'erreur
      if ( erreur==0 )
        {
          nb_comp_ = 1;
          nature_ch = scalaire;
// L'appel a creer_expression_macro est fait si on a un vecteur car elle fait appel aux composantes !
          creer_expression_macro();
          fxyz.dimensionner(1);
          fxyz[0].setNbVar(nb_var);
          fxyz[0].setString(les_fct[0]);
          for (int i=0; i<nb_sources; i++)
            {
              Champ source_espace_stockage;
              const Champ_base& source = get_source(i).get_champ(source_espace_stockage);
              int nb_comp = source.nb_comp();
              const Noms compo = get_source(i).get_property("composantes");
              for (int comp=0; comp<nb_comp; comp++)
                {
                  fxyz[0].addVar(compo[comp]);
                  Journal()<<" Source compo "<<compo[comp]<<finl;
                }
            }
          fxyz[0].parseString();
        }
    }
  else if (Motcle(methode_)=="vecteur")
    {
      nb_comp_ = les_fct.size();
      nature_ch = vectoriel;
      fxyz.dimensionner(nb_comp_);
      for (int comp=0; comp<nb_comp_; comp++)
        {
          fxyz[comp].setNbVar(4+nb_sources);
          fxyz[comp].setString(les_fct[comp]);
          fxyz[comp].addVar("x");
          fxyz[comp].addVar("y");
          fxyz[comp].addVar("z");
          fxyz[comp].addVar("t");
          for (int i=0; i<nb_sources; i++)
            {
              const Noms nom = get_source(i).get_property("nom");
              fxyz[comp].addVar(nom[0]);
              Journal()<<" Name of source "<<nom[0]<<finl;
            }
          fxyz[comp].parseString();
        }
    }
  else if ((Motcle(methode_)=="composante")|| ((Motcle(methode_)=="composante_normale") ))
    {
      if (nb_sources!=1)
        {
          msg = "Exactly one vector source field must be specified.";
          erreur = 1;
        }
// La suite est faite si on n'a pas d'erreur !!
      if (erreur==0) //!< 1 source pas la peine de faire une boucle
        {
          Champ source_espace_stockage;
          const Champ_base& source = get_source(0).get_champ_without_evaluation(source_espace_stockage);
          if (source.nature_du_champ()!=vectoriel && source.nature_du_champ()!=multi_scalaire)
            {
              msg = "The source field is not of vector nature.";
              erreur = 1;
            }
        }
      nb_comp_ = 1;
      nature_ch = scalaire;
    }
  else if (Motcle(methode_)=="formule")
    nb_var = -1;
  if ((nature_ch==scalaire) && (localisation_!="elem"))
    {
      const Zone_dis_base& zone_dis = get_ref_zone_dis_base();
      if (zone_dis.que_suis_je().debute_par("Zone_VDF"))
        {
          msg = "The nature of the generated storing field will be scalar.\n";
          msg += "In that case the location elem is required since VDF discretization is considered.";
          erreur = 1;
        }
    }
  if (erreur)
    {
      Cerr<<"Please check the syntax of the Transformation generic field "<<nom_post_<<finl;
      Cerr<<"for wich the selected option is : "<<methode_<<finl;
      Cerr<<msg<<finl;
      exit();
    }
  return nb_var;
}
References Cerr, creer_expression_macro(), Nom::debute_par(), vect_impl::dimensionner(), erreur(), Process::exit(), finl, fxyz, Champ_Generique_base::get_champ(), Champ_Generique_base::get_champ_without_evaluation(), Champ_Gen_de_Champs_Gen::get_nb_sources(), Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_ref_zone_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Process::Journal(), les_fct, localisation_, methode_, multi_scalaire, nature_ch, Field_base::nature_du_champ(), Field_base::nb_comp(), nb_comp_, Champ_Generique_base::nom_post_, Objet_U::que_suis_je(), scalaire, vect_impl::size(), and vectoriel.
Referenced by completer().
printOn()
Sortie & Champ_Generique_Transformation::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 39 of file Champ_Generique_Transformation.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Generique_Transformation::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 44 of file Champ_Generique_Transformation.cpp.
{
  Champ_Gen_de_Champs_Gen::readOn(s);
  verifier_coherence_donnees();
  return s ;
}
References Champ_Gen_de_Champs_Gen::readOn(), and verifier_coherence_donnees().
self_cast() [1/2]
const Champ_Generique_Transformation & Champ_Generique_Transformation::self_cast (const Objet_U & r) static
Definition at line 36 of file Champ_Generique_Transformation.cpp.
self_cast() [2/2]
Champ_Generique_Transformation & Champ_Generique_Transformation::self_cast (Objet_U & r) static
Definition at line 36 of file Champ_Generique_Transformation.cpp.
set_param()
void Champ_Generique_Transformation::set_param (Param & param) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 61 of file Champ_Generique_Transformation.cpp.
{
  Champ_Gen_de_Champs_Gen::set_param(param);
  param.ajouter("methode",&methode_,Param::REQUIRED);
  param.ajouter_non_std("expression",(this));
  param.ajouter_non_std("numero",(this));
  param.ajouter("localisation",&localisation_);
}
References Param::ajouter(), Param::ajouter_non_std(), localisation_, methode_, Param::REQUIRED, and Champ_Gen_de_Champs_Gen::set_param().
taille_memoire()
unsigned Champ_Generique_Transformation::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 36 of file Champ_Generique_Transformation.cpp.
verifier_coherence_donnees()
void Champ_Generique_Transformation::verifier_coherence_donnees ()
Definition at line 111 of file Champ_Generique_Transformation.cpp.
{
  if ((Motcle(methode_) == "produit_scalaire") || (Motcle(methode_) == "norme"))
    les_fct.dimensionner(1);
  else if ((Motcle(methode_) == "formule") || (Motcle(methode_) == "vecteur"))
    {
      if (les_fct.size()<1)
        {
          Cerr<<"The expression must be read for the methods fonction and vecteur."<<finl;
          exit();
        }
    }
  else
    {
      Motcles methods(6);
      methods[0] = "formule";
      methods[1] = "vecteur";
      methods[2] = "produit_scalaire";
      methods[3] = "norme";
      methods[4] = "composante";
      methods[5] = "composante_normale";
      if (methods.search(methode_) < 0)
        {
          Cerr<<"Error in  "<<que_suis_je()<<finl;
          Cerr<<"Read keyword : " << methode_ << "\n Allowed items are : "<<methods<<finl;
          exit();
        }
    }
  if ((Motcle(methode_) == "vecteur"))
    {
// On essaie de fixer de suite le nombre de composantes avec vecteur
      nb_comp_ = les_fct.size();
// la verification des sources est faite lors du completer pour les sources reference
    }
}
References Cerr, vect_impl::dimensionner(), Process::exit(), finl, les_fct, methode_, nb_comp_, Objet_U::que_suis_je(), Motcles::search(), and vect_impl::size().
Referenced by readOn().
verifier_localisation()
void Champ_Generique_Transformation::verifier_localisation ()
Definition at line 148 of file Champ_Generique_Transformation.cpp.
{
  Motcles localisations(4);
  localisations[0] = "elem";
  localisations[1] = "som";
  localisations[2] = "faces";
  localisations[3] = "elem_som";
  if (localisations.search(localisation_) < 0)
    {
      Cerr << "Error in "<<que_suis_je()<<finl;
      Cerr << "Read keyword : " << localisation_ << "\n Allowed items are " << localisations << finl;
      exit();
    }
}
References Cerr, Process::exit(), finl, localisation_, Objet_U::que_suis_je(), and Motcles::search().
Referenced by completer().
Member Data Documentation
fxyz
Vect_Parser_U Champ_Generique_Transformation::fxyz mutable protected
Definition at line 106 of file Champ_Generique_Transformation.h.
Referenced by completer(), get_champ(), and preparer_macro().
info_obj
const Type_info Champ_Generique_Transformation::info_obj static
Definition at line 82 of file Champ_Generique_Transformation.h.
les_fct
Noms Champ_Generique_Transformation::les_fct protected
Definition at line 105 of file Champ_Generique_Transformation.h.
Referenced by completer(), creer_expression_macro(), get_champ(), lire_motcle_non_standard(), nommer_source(), preparer_macro(), and verifier_coherence_donnees().
localisation_
Motcle Champ_Generique_Transformation::localisation_ protected
Definition at line 108 of file Champ_Generique_Transformation.h.
Referenced by completer(), get_champ(), get_directive_pour_discr(), get_localisation(), preparer_macro(), set_param(), and verifier_localisation().
methode_
Nom Champ_Generique_Transformation::methode_ protected
Definition at line 104 of file Champ_Generique_Transformation.h.
Referenced by completer(), creer_expression_macro(), get_champ(), lire_motcle_non_standard(), preparer_macro(), set_param(), and verifier_coherence_donnees().
nature_ch
Nature_du_champ Champ_Generique_Transformation::nature_ch protected
Definition at line 109 of file Champ_Generique_Transformation.h.
Referenced by completer(), get_champ(), get_champ_without_evaluation(), lire_motcle_non_standard(), and preparer_macro().
nb_comp_
int Champ_Generique_Transformation::nb_comp_ protected
Definition at line 107 of file Champ_Generique_Transformation.h.
Referenced by completer(), get_champ(), get_champ_without_evaluation(), get_property(), lire_motcle_non_standard(), preparer_macro(), and verifier_coherence_donnees().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Generique_Transformation.h
src/Kernel/Champs/Champ_Generique_Transformation.cpp