TRUST: Eval_Quick_VDF_Face_Axi Class Reference
Eval_Quick_VDF_Face_Axi Class Reference
class Eval_Quick_VDF_Face_Axi
Evaluateur VDF pour la convection en coordonnees cylindriques
Le champ convecte est un Champ_Face
Schema de convection Quick
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
#include <Eval_Quick_VDF_Face_Axi.h>
Public Member Functions
Eval_Quick_VDF_Face_Axi ()
int calculer_arete_fluide () const
int calculer_arete_paroi () const
int calculer_arete_paroi_fluide () const
int calculer_arete_symetrie () const
int calculer_arete_interne () const
int calculer_arete_mixte () const
int calculer_fa7_sortie_libre () const
int calculer_arete_periodicite () const
double flux_fa7_sortie_libre (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double flux_fa7_elem (const DoubleTab &, int, int, int) const
double flux_arete_interne (const DoubleTab &, int, int, int, int) const
double flux_arete_mixte (const DoubleTab &, int, int, int, int) const
double flux_arete_paroi (const DoubleTab &, int, int, int, int) const
double flux_arete_symetrie (const DoubleTab &, int, int, int, int) const
void flux_arete_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_paroi_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_periodicite (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_fa7_elem (const DoubleTab &, int, int, int, DoubleVect &flux) const
void flux_fa7_sortie_libre (const DoubleTab &, int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void flux_arete_interne (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_mixte (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_symetrie (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_paroi (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_paroi_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_periodicite (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
Private Member Functions
double dist_face (int, int, int) const
double dim_face (int, int) const
int face_amont_conj (int, int, int) const
int face_amont_princ (int, int) const
double dist_elem (int, int, int) const
double dim_elem (int, int) const
Detailed Description
class Eval_Quick_VDF_Face_Axi
Evaluateur VDF pour la convection en coordonnees cylindriques
Le champ convecte est un Champ_Face
Schema de convection Quick
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
See also:
Eval_Conv_VDF
Definition at line 45 of file Eval_Quick_VDF_Face_Axi.h.
Constructor & Destructor Documentation
Eval_Quick_VDF_Face_Axi::Eval_Quick_VDF_Face_Axi () [inline]
Definition at line 115 of file Eval_Quick_VDF_Face_Axi.h.
{
}
Member Function Documentation
int Eval_Quick_VDF_Face_Axi::calculer_arete_fluide () const [inline]
Definition at line 123 of file Eval_Quick_VDF_Face_Axi.h.
{
  return 1;
}
int Eval_Quick_VDF_Face_Axi::calculer_arete_interne () const [inline]
Definition at line 158 of file Eval_Quick_VDF_Face_Axi.h.
{
  return 1;
}
int Eval_Quick_VDF_Face_Axi::calculer_arete_mixte () const [inline]
Definition at line 166 of file Eval_Quick_VDF_Face_Axi.h.
{
  return 1;
}
int Eval_Quick_VDF_Face_Axi::calculer_arete_paroi () const [inline]
Definition at line 132 of file Eval_Quick_VDF_Face_Axi.h.
{
  return 0;
}
int Eval_Quick_VDF_Face_Axi::calculer_arete_paroi_fluide () const [inline]
Definition at line 141 of file Eval_Quick_VDF_Face_Axi.h.
{
  return 1;
}
int Eval_Quick_VDF_Face_Axi::calculer_arete_periodicite () const [inline]
Definition at line 182 of file Eval_Quick_VDF_Face_Axi.h.
{
  return 0;
}
int Eval_Quick_VDF_Face_Axi::calculer_arete_symetrie () const [inline]
Definition at line 150 of file Eval_Quick_VDF_Face_Axi.h.
{
  return 0;
}
int Eval_Quick_VDF_Face_Axi::calculer_fa7_sortie_libre () const [inline]
Definition at line 174 of file Eval_Quick_VDF_Face_Axi.h.
{
  return 1;
}
double Eval_Quick_VDF_Face_Axi::dim_elem (int n1, int k) const [inline, private]
Definition at line 263 of file Eval_Quick_VDF_Face_Axi.h.
References Evaluateur_VDF::dimension, dist_face(), and Evaluateur_VDF::la_zone.
Referenced by dim_face(), and flux_fa7_elem().
{
  const IntTab& elem_faces_ = la_zone->elem_faces();
  return dist_face(elem_faces_(n1,k), elem_faces_(n1,k+dimension), k) ;
// return la_zone->dim_elem_axi(n1,k);
}
double Eval_Quick_VDF_Face_Axi::dim_face (int n1, int k) const [inline, private]
Definition at line 314 of file Eval_Quick_VDF_Face_Axi.h.
References dim_elem(), and Evaluateur_VDF::la_zone.
Referenced by flux_arete_interne().
{
  const IntTab& face_voisins_ = la_zone->face_voisins();
  int elem0, elem1 ;
  elem0 = face_voisins_(n1,0) ;
  elem1 = face_voisins_(n1,1) ;
  if (elem0 < 0 )
    return  dim_elem(elem1, k) ;
  if (elem1 < 0 )
    return  dim_elem(elem0, k) ;
  return (dim_elem(elem0, k) + dim_elem(elem1, k)) * 0.5 ;
// return la_zone->dim_face_axi(n1,k);
}
double Eval_Quick_VDF_Face_Axi::dist_elem (int n1, int n2, int k) const [inline, private]
Definition at line 273 of file Eval_Quick_VDF_Face_Axi.h.
References Evaluateur_VDF::la_zone, and M_PI.
Referenced by flux_fa7_elem().
{
  const DoubleTab& xp_ = la_zone->xp();
  double d_teta, dist ;
  if (k != 1)
    dist = xp_(n2,k)-xp_(n1,k) ;
  else
    {
      d_teta = xp_(n2,1) - xp_(n1,1);
      if (d_teta < 0)
        d_teta += 2.0*M_PI;
      dist = d_teta * xp_(n1,0);
    }
  return dist ;
// return la_zone->dist_elem_axi(n1,n2,k);
}
double Eval_Quick_VDF_Face_Axi::dist_face (int n1, int n2, int k) const [inline, private]
Reimplemented from Evaluateur_VDF.
Definition at line 293 of file Eval_Quick_VDF_Face_Axi.h.
References Evaluateur_VDF::la_zone, and M_PI.
Referenced by dim_elem(), and flux_arete_interne().
{
  double d_teta , dist ;
  const DoubleTab& xv_ = la_zone->xv();
  if (k != 1)
    dist =  xv_(n2,k) - xv_(n1,k);
  else
    {
      d_teta = xv_(n2,1) - xv_(n1,1);
      if (d_teta < 0)
        d_teta += 2.0*M_PI;
      if (d_teta > M_PI)
        d_teta -= M_PI ;
      dist = d_teta*xv_(n1,0);
    }
// Cerr << " dteta " << d_teta << " xv " << xv_(n1,1) << " k " << k << "dist " << dist << finl ;
  return dist ;
// return la_zone->dist_face_axi(n1,n2,k);
}
int Eval_Quick_VDF_Face_Axi::face_amont_conj (int num_face, int k, int i) const [inline, private]
Definition at line 331 of file Eval_Quick_VDF_Face_Axi.h.
References Evaluateur_VDF::dimension, and Evaluateur_VDF::la_zone.
Referenced by flux_arete_interne().
{
  const IntTab& face_voisins_ = la_zone->face_voisins();
  const IntTab& elem_faces_   = la_zone->elem_faces();
  const IntVect& orientation_ = la_zone->orientation();
  int ori = orientation_(num_face);
  int elem1 = face_voisins_(num_face,1);
  int face,elem_bis = -2;
  int face_conj = -1 ;
  if(elem1 != -1)
    {
      face = elem_faces_(elem1, k+i*dimension);
      elem_bis = face_voisins_(face,i);
      if (elem_bis != -1)
        face_conj = elem_faces_(elem_bis, ori);
      else
        face_conj = -1;
    }
  if ((elem1==-1) || (elem_bis==-1))
    {
      elem1 = face_voisins_(num_face,0);
      if(elem1 != -1)
        {
          face = elem_faces_(elem1, k+i*dimension);
          elem_bis = face_voisins_(face,i);
          assert(elem_bis!=-2);
          if (elem_bis != -1)
            face_conj = elem_faces_(elem_bis, ori);
          else
            face_conj = -1;
        }
    }
  return face_conj;
// return la_zone->face_amont_conj(num_face, k, i);
}
int Eval_Quick_VDF_Face_Axi::face_amont_princ (int num_face, int i) const [inline, private]
Definition at line 371 of file Eval_Quick_VDF_Face_Axi.h.
References Evaluateur_VDF::la_zone.
Referenced by flux_fa7_elem().
{
// const IntTab& face_voisins_ = la_zone->face_voisins();
// const IntTab& elem_faces_   = la_zone->elem_faces();
// const IntVect& orientation_ = la_zone->orientation();
// int ori=orientation_(num_face);
// int elem=face_voisins_(num_face,i);
// if(elem !=-1)
// elem=elem_faces_(elem,ori+i*dimension);
// return elem;
  return la_zone->face_amont_princ(num_face, i);
}
void Eval_Quick_VDF_Face_Axi::flux_arete_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Definition at line 392 of file Eval_Quick_VDF_Face_Axi.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux,psc;
  int ori;
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    flux=inco[fac3]*psc ;
  else
    {
      ori =orientation(fac3);
      flux = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac1,ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac2,ori,la_zcl)) * psc ;
    }
  flux3 = -flux;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*inco[fac2];
  flux1_2 = -flux;
}
void Eval_Quick_VDF_Face_Axi::flux_arete_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Definition at line 630 of file Eval_Quick_VDF_Face_Axi.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<flux3.size(); k++)
      flux3(k) = -inco(fac3,k)*psc ;
  else
    {
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac1,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac2,k,ori,la_zcl)) * psc ;
    }
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_Quick_VDF_Face_Axi::flux_arete_interne (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, DoubleVect & flux) const [inline]
< Schema amont
< Schema quick
< (psc <= 0)
< Schema amont
< Schema quick
Definition at line 666 of file Eval_Quick_VDF_Face_Axi.h.
References conv_quick_sharp_moins(), conv_quick_sharp_plus(), dim_face(), dist_face(), Eval_Conv_VDF::dt_vitesse, face_amont_conj(), Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  int ncomp = flux.size();
  double psc = 0.25* (dt_vitesse[fac1]*porosite(fac1) + dt_vitesse[fac2]*porosite(fac2))
               * (surface(fac1) + surface(fac2));
  int ori = orientation(fac1);
  int num0_0 = face_amont_conj(fac3,ori,0);
  int num1_1 = face_amont_conj(fac4,ori,1);
  if (psc > 0)
    if (num0_0 == -1) //!< Schema amont
      for (k=0; k<ncomp; k++)
        flux(k) = -psc*inco(fac3,k);
    else //!< Schema quick
      {
        double dx = dist_face(fac3,fac4,ori);
        double dm = dim_face(fac3,ori);
        double dxam = dist_face(num0_0,fac3,ori);
        DoubleVect vit_0(ncomp);
        DoubleVect vit_0_0(ncomp);
        DoubleVect vit_1(ncomp);
        for (k=0; k<ncomp; k++)
          {
            vit_0(k) = inco(fac3,k);
            vit_0_0(k) = inco(num0_0,k);
            vit_1(k) = inco(fac4,k);
            flux(k) = -conv_quick_sharp_plus(psc,vit_0(k),vit_1(k),vit_0_0(k),dx,dm,dxam);
          }
      }
  else //!< (psc <= 0)
    if (num1_1 == -1) //!< Schema amont
      for (k=0; k<ncomp; k++)
        flux(k) = -psc*inco(fac4,k);
    else //!< Schema quick
      {
        double dx = dist_face(fac3,fac4,ori);
        double dm = dim_face(fac4,ori);
        double dxam = dist_face(fac4,num1_1,ori);
        DoubleVect vit_0(ncomp);
        DoubleVect vit_1(ncomp);
        DoubleVect vit_1_1(ncomp);
        for (k=0; k<ncomp; k++)
          {
            vit_0(k) = inco(fac3,k);
            vit_1(k) = inco(fac4,k);
            vit_1_1(k) = inco(num1_1,k);
            flux(k) = -conv_quick_sharp_moins(psc,vit_0(k),vit_1(k),vit_1_1(k),dx,dm,dxam);
          }
      }
}
double Eval_Quick_VDF_Face_Axi::flux_arete_interne (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4) const [inline]
< Schema amont
< Schema quick
< (psc <= 0)
< Schema amont
< Schema quick
Definition at line 428 of file Eval_Quick_VDF_Face_Axi.h.
References conv_quick_sharp_moins(), conv_quick_sharp_plus(), dim_face(), dist_face(), Eval_Conv_VDF::dt_vitesse, face_amont_conj(), Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  double psc = 0.25* (dt_vitesse[fac1]*porosite(fac1) + dt_vitesse[fac2]*porosite(fac2))
               * (surface(fac1) + surface(fac2));
  int ori = orientation(fac1);
  int num0_0 = face_amont_conj(fac3,ori,0);
  int num1_1 = face_amont_conj(fac4,ori,1);
  if (psc > 0)
    if (num0_0 == -1) //!< Schema amont
      flux = psc*inco[fac3];
    else //!< Schema quick
      {
        double dx = dist_face(fac3,fac4,ori);
        double dm = dim_face(fac3,ori);
        double dxam = dist_face(num0_0,fac3,ori);
        double vit_0 = inco[fac3];
        double vit_0_0 = inco[num0_0];
        double vit_1 = inco[fac4];
// Cerr << "fac3 " << fac3 << "ori " << ori << " dx " << dx << " dxam " << dxam << " dm " << dm << finl ;
        flux = conv_quick_sharp_plus(psc,vit_0,vit_1,vit_0_0,dx,dm,dxam);
      }
  else //!< (psc <= 0)
    if (num1_1 == -1) //!< Schema amont
      flux = psc*inco[fac4];
    else //!< Schema quick
      {
        double dx = dist_face(fac3,fac4,ori);
        double dm = dim_face(fac4,ori);
        double dxam = dist_face(fac4,num1_1,ori);
        double vit_0 = inco[fac3];
        double vit_1 = inco[fac4];
        double vit_1_1 = inco[num1_1];
        flux = conv_quick_sharp_moins(psc,vit_0,vit_1,vit_1_1,dx,dm,dxam);
      }
  return -flux;
}
void Eval_Quick_VDF_Face_Axi::flux_arete_mixte (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, DoubleVect & flux) const [inline]
Definition at line 725 of file Eval_Quick_VDF_Face_Axi.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] )  *
               ( surface[fac1] + surface[fac2] );
  if (psc>0)
    for (k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(fac3,k);
  else
    for (k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(fac4,k);
}
double Eval_Quick_VDF_Face_Axi::flux_arete_mixte (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4) const [inline]
Definition at line 473 of file Eval_Quick_VDF_Face_Axi.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] )  *
               ( surface[fac1] + surface[fac2] );
  if (psc>0)
    flux = psc*inco[fac3];
  else
    flux = psc*inco[fac4];
  return -flux;
}
double Eval_Quick_VDF_Face_Axi::flux_arete_paroi (const DoubleTab & , int , int , int , int) const [inline]
Definition at line 493 of file Eval_Quick_VDF_Face_Axi.h.
{
  return 0;
}
void Eval_Quick_VDF_Face_Axi::flux_arete_paroi (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 745 of file Eval_Quick_VDF_Face_Axi.h.
{
  ;
}
void Eval_Quick_VDF_Face_Axi::flux_arete_paroi_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Definition at line 755 of file Eval_Quick_VDF_Face_Axi.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<flux3.size(); k++)
      flux3(k) = -inco(fac3,k)*psc;
  else
    {
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac1-premiere_face_bord,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac2-premiere_face_bord,k,ori,la_zcl))* psc ;
    }
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_Quick_VDF_Face_Axi::flux_arete_paroi_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Definition at line 502 of file Eval_Quick_VDF_Face_Axi.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double flux,psc;
  int ori;
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    flux=inco[fac3]*psc ;
  else
    {
      ori =orientation(fac3);
      flux = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac1-premiere_face_bord, ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),fac2-premiere_face_bord, ori,la_zcl))* psc ;
    }
  flux3 = -flux;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*inco[fac2];
  flux1_2 = -flux;
}
void Eval_Quick_VDF_Face_Axi::flux_arete_periodicite (const DoubleTab & , int , int , int , int , double & , double &) const [inline]
Definition at line 538 of file Eval_Quick_VDF_Face_Axi.h.
{
}
void Eval_Quick_VDF_Face_Axi::flux_arete_periodicite (const DoubleTab & , int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Definition at line 790 of file Eval_Quick_VDF_Face_Axi.h.
{
  ;
}
double Eval_Quick_VDF_Face_Axi::flux_arete_symetrie (const DoubleTab & , int , int , int , int) const [inline]
Definition at line 547 of file Eval_Quick_VDF_Face_Axi.h.
{
  return 0;
}
void Eval_Quick_VDF_Face_Axi::flux_arete_symetrie (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 799 of file Eval_Quick_VDF_Face_Axi.h.
{
  ;
}
void Eval_Quick_VDF_Face_Axi::flux_fa7_elem (const DoubleTab & inco, int num_elem, int fac1, int fac2, DoubleVect & flux) const [inline]
< Schema amont
< (psc < 0)
< Schema amont
Definition at line 809 of file Eval_Quick_VDF_Face_Axi.h.
References conv_quick_sharp_moins(), conv_quick_sharp_plus(), dim_elem(), dist_elem(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, face_amont_princ(), Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  int num0_0 = face_amont_princ(fac1,0);
  int num1_1 = face_amont_princ(fac2,1);
  int ncomp = flux.size();
  double psc = 0.25 * (dt_vitesse[fac1]+dt_vitesse[fac2])*(surface(fac1)+surface(fac2));
  if  (psc > 0)
    {
      if (num0_0 == -1) //!< Schema amont
        for (k=0; k<ncomp; k++)
          flux(k) = -psc*inco(fac1,k)*porosite(fac1);
      else
        {
          int ori = orientation(fac1);
          double dx = dim_elem(num_elem,ori);
          int elem_amont = elem_(fac1,0);
          double dm = dist_elem(elem_amont,num_elem,ori);
          double dxam = dim_elem(elem_amont,ori);
          DoubleVect vit_0(ncomp);
          DoubleVect vit_0_0(ncomp);
          DoubleVect vit_1(ncomp);
          for (k=0; k<ncomp; k++)
            {
              vit_0(k) = inco(fac1,k)*porosite(fac1);
              vit_0_0(k) = inco(num0_0,k)*porosite(num0_0);
              vit_1(k) = inco(fac2,k)*porosite(fac2);
              flux(k) = -conv_quick_sharp_plus(psc,vit_0(k),vit_1(k),vit_0_0(k),dx,dm,dxam);
            }
        }
    }
  else //!< (psc < 0)
    {
      if (num1_1 == -1) //!< Schema amont
        for (k=0; k<ncomp; k++)
          flux(k) = -psc*inco(fac2,k)*porosite(fac2);
      else
        {
          int ori = orientation(fac2);
          double dx = dim_elem(num_elem,ori);
          int elem_amont = elem_(fac2,1);
          double dm = dist_elem(num_elem,elem_amont,ori);
          double dxam = dim_elem(elem_amont,ori);
          DoubleVect vit_0(ncomp);
          DoubleVect vit_1(ncomp);
          DoubleVect vit_1_1(ncomp);
          for (k=0; k<ncomp; k++)
            {
              vit_0(k) = inco(fac1,k)*porosite(fac1);
              vit_1(k) = inco(fac2,k)*porosite(fac2);
              vit_1_1(k) = inco(num1_1,k)*porosite(num1_1);
              flux(k) = -conv_quick_sharp_moins(psc,vit_0(k),vit_1(k),vit_1_1(k),dx,dm,dxam);
            }
        }
    }
}
double Eval_Quick_VDF_Face_Axi::flux_fa7_elem (const DoubleTab & inco, int num_elem, int fac1, int fac2) const [inline]
< Schema amont
< (psc < 0)
< Schema amont
Definition at line 556 of file Eval_Quick_VDF_Face_Axi.h.
References conv_quick_sharp_moins(), conv_quick_sharp_plus(), dim_elem(), dist_elem(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, face_amont_princ(), Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  int num0_0 = face_amont_princ(fac1,0);
  int num1_1 = face_amont_princ(fac2,1);
  double psc = 0.25 * (dt_vitesse[fac1]+dt_vitesse[fac2])*(surface(fac1)+surface(fac2));
  if  (psc > 0)
    {
      if (num0_0 == -1) //!< Schema amont
        flux = psc*inco[fac1]*porosite(fac1);
      else
        {
          int ori = orientation(fac1);
          double dx = dim_elem(num_elem,ori);
          int elem_amont = elem_(fac1,0);
          double dm = dist_elem(elem_amont,num_elem,ori);
          double dxam = dim_elem(elem_amont,ori);
          double vit_0 = inco[fac1]*porosite(fac1);
          double vit_0_0 = inco[num0_0]*porosite(num0_0);
          double vit_1 = inco[fac2]*porosite(fac2);
          flux = conv_quick_sharp_plus(psc,vit_0,vit_1,vit_0_0,dx,dm,dxam);
        }
    }
  else //!< (psc < 0)
    {
      if (num1_1 == -1) //!< Schema amont
        flux = psc*inco[fac2]*porosite(fac2);
      else
        {
          int ori = orientation(fac2);
          double dx = dim_elem(num_elem,ori);
          int elem_amont = elem_(fac2,1);
          double dm = dist_elem(num_elem,elem_amont,ori);
          double dxam = dim_elem(elem_amont,ori);
          double vit_0 = inco[fac1]*porosite(fac1);
          double vit_1 = inco[fac2]*porosite(fac2);
          double vit_1_1 = inco[num1_1]*porosite(num1_1);
          flux = conv_quick_sharp_moins(psc,vit_0,vit_1,vit_1_1,dx,dm,dxam);
        }
    }
  return -flux;
}
double Eval_Quick_VDF_Face_Axi::flux_fa7_sortie_libre (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1) const [inline]
< (elem2 != -1)
Definition at line 604 of file Eval_Quick_VDF_Face_Axi.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::orientation, Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  double flux;
  double psc = dt_vitesse[face]*surface(face);
  int elem1 = elem_(face,0);
  if (elem1 != -1)
    if (psc > 0)
      flux = psc*inco[face];
    else
      flux = psc*la_cl.val_ext(face-num1,orientation(face));
  else //!< (elem2 != -1)
    if (psc < 0)
      flux = psc*inco[face];
    else
      flux = psc*la_cl.val_ext(face-num1,orientation(face));
  return -flux;
}
void Eval_Quick_VDF_Face_Axi::flux_fa7_sortie_libre (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const [inline]
< (elem2 != -1)
Definition at line 868 of file Eval_Quick_VDF_Face_Axi.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, DoubleVect::size(), Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  int k;
  double psc = dt_vitesse[face]*surface(face);
  int elem1 = elem_(face,0);
  if (elem1 != -1)
    if (psc > 0)
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*inco(face,k);
    else
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*la_cl.val_ext(face-num1,k);
  else //!< (elem2 != -1)
    if (psc < 0)
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*inco(face,k);
    else
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*la_cl.val_ext(face-num1,k);
}
The documentation for this class was generated from the following file:
src/VDF/Axi/Operateurs/Evaluateurs/Eval_Quick_VDF_Face_Axi.h