TRUST: Mailler Class Reference
Mailler Class Reference
Classe Mailler
Un mailleur par agglomeration de zones (paves pour le moment)
Structure du jeu de donnee (en dimension 2) :
Mailler dom
{
[Epsilon eps]
Pave nompave1
{
Origine OX OY
Longueurs LX LY
Nombre_de_Noeuds NX NY
}
{
Bord nom_bord1 X = X0 Y0 <= Y <= Y1
Bord nom_bord2 X = X0 Y1 <= Y <= Y2
Bord nom_bord2 Y = Y0 X1 <= X <= X2
...
} ,
Pave nompave2 ...
}
Deux points seront confondus des que la distance entre eux est
inferieure a Epsilon.
#include <Mailler.h>
Public Member Functions
Mailler ()
~Mailler ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
Fonction principale de l'interprete Mailler
Structure du jeu de donnee (en dimension 2) :
Mailler dom
{
[Epsilon eps]
[objet1]
,
[objet2]
...
}
Deux points seront confondus des que la distance entre eux est
inferieure a Epsilon.
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Mailler & self_cast (Objet_U &)
static const Mailler & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Classe Mailler
Un mailleur par agglomeration de zones (paves pour le moment)
Structure du jeu de donnee (en dimension 2) :
Mailler dom
{
[Epsilon eps]
Pave nompave1
{
Origine OX OY
Longueurs LX LY
Nombre_de_Noeuds NX NY
}
{
Bord nom_bord1 X = X0 Y0 <= Y <= Y1
Bord nom_bord2 X = X0 Y1 <= Y <= Y2
Bord nom_bord2 Y = Y0 X1 <= X <= X2
...
} ,
Pave nompave2 ...
}
Deux points seront confondus des que la distance entre eux est
inferieure a Epsilon.
Definition at line 53 of file Mailler.h.
Constructor & Destructor Documentation
Mailler()
Mailler::Mailler ()
Definition at line 22 of file Mailler.cpp.
~Mailler()
Mailler::~Mailler ()
Definition at line 22 of file Mailler.cpp.
Member Function Documentation
cree_instance()
Objet_U * Mailler::cree_instance () static
Definition at line 22 of file Mailler.cpp.
duplique()
int Mailler::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file Mailler.cpp.
get_info()
const Type_info * Mailler::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 22 of file Mailler.cpp.
info()
const Type_info * Mailler::info () static
Definition at line 22 of file Mailler.cpp.
interpreter_()
Entree & Mailler::interpreter_ (Entree & is) override virtual
Fonction principale de l'interprete Mailler
Structure du jeu de donnee (en dimension 2) :
Mailler dom
{
[Epsilon eps]
[objet1]
,
[objet2]
...
}
Deux points seront confondus des que la distance entre eux est
inferieure a Epsilon.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
< On renumerote!
Implements Interprete_geometrique_base.
Definition at line 99 of file Mailler.cpp.
{
  if (Process::nproc()>1)
    {
      Cerr << "Mailler keyword can't be used in parallel calculation!" << finl;
      Cerr << "Use only Scatter keyword to read partitioned mesh." << finl;
      exit();
    }
  double precision_geom_sa=precision_geom;
  associer_domaine(is);
  Domaine& dom=domaine();
// On debloque les structures pour modifier le domaine
  Scatter::uninit_sequential_domain(dom);
  Motcle motlu;
  is >> motlu;
  if (motlu != "{")
    {
      Cerr << "We expected a {" << finl;
      exit();
    }
// Valeur par defaut: precision_geom
  dom.fixer_epsilon(Objet_U::precision_geom);
  Nom typ_zone;
  do
    {
      is >> typ_zone;
      motlu = typ_zone;
      if(motlu=="epsilon")
        {
          double eps;
          is >> eps;
          dom.fixer_epsilon(eps);
// GF le eps du domaine ne sert plus quand on cherche les sommets
// doubles;
          precision_geom=eps;
          is >> motlu;
          if ((motlu!="}") && (motlu!=",") )
            {
              Cerr<<"The syntax of \"Mailler\" has changed. We expected \",\" after the definition of epsilon and not \"" <<motlu << "\"" <<finl;
              exit();
            }
          verifie_syntaxe(motlu);
        }
      else if (motlu=="Domaine")
        {
          Cerr<<"The syntax of \"Mailler\" has changed. The keyword \"Domaine\" has been replaced by \"Domain\"" <<finl;
          exit();
        }
      else if(motlu=="Domain")
        {
          Nom nom_dom;
          is >> nom_dom;
          Cerr << "Adding a domain " << nom_dom << finl;
          Domaine& added_dom=ref_cast(Domaine, objet(nom_dom));
          IntVect nums;
          Zone& zone=dom.add(added_dom.zone(0));
          zone.associer_domaine(dom);
          dom.ajouter(added_dom.coord_sommets(), nums);
          Scatter::uninit_sequential_domain(dom);
          zone.renum(nums);
          zone.associer_domaine(dom);
          dom.comprimer();
          dom.zone(0).fixer_premieres_faces_frontiere();
          dom.zone(0).type_elem().associer_zone(dom.zone(0));
          is >> motlu;
          verifie_syntaxe(motlu);
        }
      else
        {
          DERIV(Zone) une_zone;
          une_zone.typer(typ_zone);
          Zone& ajoutee = dom.add(une_zone.valeur());
          ajoutee.associer_domaine(dom);
          is >> ajoutee;
          ajoutee.associer_domaine(dom); //!< On renumerote!
          is >> motlu;
          verifie_syntaxe(motlu);
        }
    }
  while(motlu != "}");
// Dans le cas ou on a modifie precision geom, on le remet a la valeur
// d'origine
  precision_geom=precision_geom_sa;
  dom.comprimer();
  dom.zone(0).fixer_premieres_faces_frontiere();
  NettoieNoeuds::nettoie(dom);
  Scatter::init_sequential_domain(dom);
  return is;
}
References Domaine::add(), Domaine::ajouter(), Zone::associer_domaine(), Interprete_geometrique_base::associer_domaine(), Elem_geom::associer_zone(), Cerr, Domaine::comprimer(), Domaine::coord_sommets(), DERIV, Interprete_geometrique_base::domaine(), Process::exit(), finl, Domaine::fixer_epsilon(), Zone::fixer_premieres_faces_frontiere(), Scatter::init_sequential_domain(), NettoieNoeuds::nettoie(), Process::nproc(), Interprete::objet(), Objet_U::precision_geom, ref_cast, Zone::renum(), Zone::type_elem(), Scatter::uninit_sequential_domain(), verifie_syntaxe(), and Domaine::zone().
printOn()
Sortie & Mailler::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 38 of file Mailler.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Mailler::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 58 of file Mailler.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Mailler & Mailler::self_cast (const Objet_U & r) static
Definition at line 22 of file Mailler.cpp.
self_cast() [2/2]
Mailler & Mailler::self_cast (Objet_U & r) static
Definition at line 22 of file Mailler.cpp.
taille_memoire()
unsigned Mailler::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file Mailler.cpp.
Member Data Documentation
info_obj
const Type_info Mailler::info_obj static
Definition at line 55 of file Mailler.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Mailler.h
src/Kernel/Geometrie/Mailler.cpp