TRUST: Deriv_Source_base Class Reference
Deriv_Source_base Class Reference
#include <Source.h>
Public Member Functions
~Deriv_Source_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Source_base ()
Deriv_Source_base (const Deriv_Source_base &)
const Source_base & valeur () const
Source_base & valeur ()
const Source_base * operator-> () const
Source_base * operator-> ()
const Deriv_Source_base & operator= (const Source_base &)
const Deriv_Source_base & operator= (const Deriv_Source_base &)
operator const Source_base & () const
operator Source_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Source_base & self_cast (Objet_U &)
static const Deriv_Source_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Source_base * pointeur_
Detailed Description
Definition at line 31 of file Source.h.
Constructor & Destructor Documentation
Deriv_Source_base::~Deriv_Source_base ()
Definition at line 32 of file Source.cpp.
Deriv_Source_base::Deriv_Source_base ()
Definition at line 32 of file Source.cpp.
Deriv_Source_base::Deriv_Source_base (const Deriv_Source_base & t)
Definition at line 32 of file Source.cpp.
Member Function Documentation
Objet_U * Deriv_Source_base::cree_instance () [static]
Reimplemented in Source.
Definition at line 32 of file Source.cpp.
int Deriv_Source_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Source.
Definition at line 32 of file Source.cpp.
const Type_info * Deriv_Source_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Source.
Definition at line 32 of file Source.cpp.
const Type_info & Deriv_Source_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 32 of file Source.cpp.
const Type_info * Deriv_Source_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Source.
Definition at line 32 of file Source.cpp.
Deriv_Source_base::operator const Source_base & () const
Definition at line 32 of file Source.cpp.
Deriv_Source_base::operator Source_base & ()
Definition at line 32 of file Source.cpp.
const Source_base * Deriv_Source_base::operator-> () const [inline]
Definition at line 31 of file Source.h.
: public DERIV(Source_base)
Source_base * Deriv_Source_base::operator-> () [inline]
Definition at line 31 of file Source.h.
: public DERIV(Source_base)
const Deriv_Source_base & Deriv_Source_base::operator= (const Deriv_Source_base & t)
Definition at line 32 of file Source.cpp.
const Deriv_Source_base & Deriv_Source_base::operator= (const Source_base & t)
Definition at line 32 of file Source.cpp.
Sortie & Deriv_Source_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Source.
Definition at line 32 of file Source.cpp.
Entree & Deriv_Source_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Source.
Definition at line 32 of file Source.cpp.
const Deriv_Source_base & Deriv_Source_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Source.
Definition at line 32 of file Source.cpp.
Deriv_Source_base & Deriv_Source_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Source.
Definition at line 32 of file Source.cpp.
void Deriv_Source_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 32 of file Source.cpp.
unsigned Deriv_Source_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Source.
Definition at line 32 of file Source.cpp.
const Source_base & Deriv_Source_base::valeur () const [inline]
Definition at line 31 of file Source.h.
Referenced by Sources::a_pour_Champ_Fonc(), Source::ajouter(), Sources::associer_champ_rho(), Source::calculer(), Sources::check_multiphase_compatibility(), Source::completer(), Sources::contribuer_a_avec(), Sources::contribuer_jacobienne(), Sources::dimensionner(), Source::impr(), Source::initialiser(), Source::mettre_a_jour(), Sources::readOn(), and Source_QC_QDM_Gen::readOn_spec().
: public DERIV(Source_base)
Source_base & Deriv_Source_base::valeur () [inline]
Definition at line 31 of file Source.h.
: public DERIV(Source_base)
Member Data Documentation
const Type_info Deriv_Source_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Source.
Definition at line 31 of file Source.h.
Source_base* Deriv_Source_base::pointeur_ [private]
Definition at line 31 of file Source.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Source.h
src/Kernel/Framework/Source.cpp