TRUST: Op_Diff_VEF_base Class Reference
Op_Diff_VEF_base Class Reference
class Op_Diff_VEF_base
Classe de base des operateurs de convection VEF
#include <Op_Diff_VEF_base.h>
Public Member Functions
Op_Diff_VEF_base ()
~Op_Diff_VEF_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
double viscA (int face_i, int face_j, int num_elem, double diffu) const
double viscA (int face_i, int face_j, int num_elem, DoubleTab &diffu) const
double viscA (int face_i, int face_j, int num_elem, ArrOfDouble &diffu_ci_cj_elem) const
double calculer_dt_stab () const
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
virtual void remplir_nu (DoubleTab &) const
int phi_psi_diffuse (const Equation_base &eq) const
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Diff_VEF_base & self_cast (Objet_U &)
static const Op_Diff_VEF_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base inconnue_
DoubleTab nu_
Detailed Description
class Op_Diff_VEF_base
Classe de base des operateurs de convection VEF
Definition at line 56 of file Op_Diff_VEF_base.h.
Constructor & Destructor Documentation
Op_Diff_VEF_base::Op_Diff_VEF_base ()
Definition at line 39 of file Op_Diff_VEF_base.cpp.
Op_Diff_VEF_base::~Op_Diff_VEF_base ()
Definition at line 39 of file Op_Diff_VEF_base.cpp.
Member Function Documentation
void Op_Diff_VEF_base::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_transporte) [virtual]
Implements Operateur_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Dift_VEF_P1NCP1B_Face, and Op_Dift_VEF_base.
Definition at line 72 of file Op_Diff_VEF_base.cpp.
References DoubleTab::dimension(), Operateur_base::flux_bords_, la_zcl_vef, la_zone_vef, DoubleTab::nb_dim(), Zone_VF::nb_faces_bord(), REF, ref_cast, sub_type, Ref_Zone_VEF::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), and Champ_Inc::valeurs().
{
  const Zone_VEF& zvef = ref_cast(Zone_VEF,zone_dis.valeur());
  const Zone_Cl_VEF& zclvef = ref_cast(Zone_Cl_VEF,zone_cl_dis.valeur());
  if (sub_type(Champ_P1NC,ch_transporte.valeur()))
    {
      const Champ_P1NC& inco = ref_cast(Champ_P1NC,ch_transporte.valeur());
      REF(Champ_P1NC) inconnue;
      inconnue = inco;
    }
  if (sub_type(Champ_Q1NC,ch_transporte.valeur()))
    {
      const Champ_Q1NC& inco = ref_cast(Champ_Q1NC,ch_transporte.valeur());
      REF(Champ_Q1NC) inconnue;
      inconnue = inco;
    }
  la_zone_vef = zvef;
  la_zcl_vef = zclvef;
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  int nb_dim = ch_transporte->valeurs().nb_dim();
  int nb_comp = 1;
  if(nb_dim==2)
    nb_comp = ch_transporte->valeurs().dimension(1);
  (ref_cast(DoubleTab,flux_bords_)).resize(zone_VEF.nb_faces_bord(),nb_comp);
  flux_bords_=0.;
}
double Op_Diff_VEF_base::calculer_dt_stab () const [virtual]
Calcul dt_stab.
Returns:
double
Signification: renvoie toujours 1.e30
Contraintes:
< get h_imp from datafile
< we should take the absolute value since it can be negative!
< Should we take the max if more than one bc has h_imp ?
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Dift_VEF_P1NCP1B_Face, Op_Diff_VEF_Face_Q1, Op_Dift_VEF_Face, and Op_Dift_VEF_Face_Q1.
Definition at line 107 of file Op_Diff_VEF_base.cpp.
References Zone_VEF::carre_pas_du_maillage(), Zone_VEF::carre_pas_maille(), Milieu_base::conductivite(), Operateur_Diff_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Objet_U::dimension, DMAXFLOAT, DMINFLOAT, MorEqn::equation(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Echange_impose_base::h_imp(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), la_zcl_vef, la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), local_max_vect(), Equation_base::milieu(), Process::mp_max(), Process::mp_min(), Zone_Cl_dis_base::nb_cond_lim(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), nu_, ref_cast, remplir_nu(), ArrOfDouble::size_array(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_Don::valeurs(), Champ_front_base::valeurs(), and Champ_Proto::valeurs().
Referenced by calculer_pour_post().
{
  remplir_nu(nu_);
// La diffusivite est constante dans le domaine donc
//
// dt_diff = h*h/diffusivite
  double dt_stab = DMAXFLOAT;
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  if (! has_champ_masse_volumique())
    {
// Methode "standard" de calcul du pas de temps
// Ce calcul est tres conservatif: si le max de la diffusivite
// n'est pas atteint a l'endroit ou le min de delta_h_carre est atteint,
// le pas de temps est sous-estime.
      const Champ_base& champ_diffusivite = diffusivite_pour_pas_de_temps();
      const DoubleVect&      valeurs_diffusivite = champ_diffusivite.valeurs();
      double alpha_max = local_max_vect(valeurs_diffusivite);
// Detect if a heat flux is imposed on a boundary through Paroi_echange_externe_impose keyword
      double h_imp_max = -1, h_imp_temp=-2, max_conductivity = 0;
      const Zone_Cl_VEF& la_zone_cl_vef = la_zcl_vef.valeur();
      const Equation_base& mon_eqn = la_zone_cl_vef.equation();
      for(int i=0; i<la_zone_cl_vef.nb_cond_lim(); i++)
        {
// loop on boundaries
          const Cond_lim_base& la_cl = la_zone_cl_vef.les_conditions_limites(i).valeur();
          if (sub_type(Echange_externe_impose,la_cl))
            {
              const Echange_externe_impose& la_cl_int = ref_cast(Echange_externe_impose,la_cl);
              const Champ_front_base& le_ch_front = ref_cast( Champ_front_base, la_cl_int.h_imp().valeur());
              const DoubleVect& tab = le_ch_front.valeurs();
              if(tab.size() > 0)
                {
                  h_imp_temp = local_max_vect(tab); //!< get h_imp from datafile
                  h_imp_temp = fabs(h_imp_temp); //!< we should take the absolute value since it can be negative!
                  h_imp_max = (h_imp_temp>h_imp_max) ? h_imp_temp : h_imp_max ; //!< Should we take the max if more than one bc has h_imp ?
                }
            }
        } //!< End loop on boundaries
      h_imp_max = Process::mp_max(h_imp_max);
      if ((alpha_max == 0.)||(zone_VEF.nb_elem()==0))
        dt_stab = DMAXFLOAT;
      else
        {
          const double min_delta_h_carre = zone_VEF.carre_pas_du_maillage();
          if (h_imp_max>0.0) //we have a BC with Paroi_echange_externe_impose
            {
// get the thermal conductivity
              const Milieu_base& mon_milieu = mon_eqn.milieu();
              const DoubleVect& tab_lambda = mon_milieu.conductivite().valeurs();
              max_conductivity = local_max_vect(tab_lambda);
// compute Biot number given by Bi = L*h/lambda.
              double Bi = h_imp_max*sqrt(min_delta_h_carre)/max_conductivity;
// if Bi>1, replace conductivity by h_imp*h in diffusivity. We are very conservative since h_imp_max is not necessarily located where max_conductivity is.
              if (Bi>1.0)
                alpha_max *= h_imp_max*sqrt(min_delta_h_carre)/max_conductivity;
            }
          dt_stab = min_delta_h_carre / (2. * dimension * alpha_max);
        }
    }
  else
    {
      const double           deux_dim      = 2. * Objet_U::dimension;
      const Champ_base& champ_diffu   = diffusivite();
      const DoubleTab&       valeurs_diffu = champ_diffu.valeurs();
      const Champ_base&      champ_rho     = get_champ_masse_volumique();
      const DoubleTab&       valeurs_rho   = champ_rho.valeurs();
      assert(sub_type(Champ_Fonc_P0_base, champ_rho));
      assert(sub_type(Champ_Fonc_P0_base, champ_diffu));
      const int nb_elem = zone_VEF.nb_elem();
      assert(valeurs_rho.size_array()==zone_VEF.nb_elem_tot());
// Champ de masse volumique variable.
      for (int elem = 0; elem < nb_elem; elem++)
        {
          const double h_carre = zone_VEF.carre_pas_maille(elem);
          const double diffu   = valeurs_diffu(elem);
          const double rho     = valeurs_rho(elem);
          const double dt      = h_carre * rho / (deux_dim * (diffu+DMINFLOAT));
          if (dt_stab > dt)
            dt_stab = dt;
        }
    }
  dt_stab = Process::mp_min(dt_stab);
  return dt_stab;
}
void Op_Diff_VEF_base::calculer_pour_post (Champ & espace_stockage, const Nom & option, int comp) const [virtual]
Reimplemented from Operateur_base.
Reimplemented in Op_Dift_VEF_Face.
Definition at line 201 of file Op_Diff_VEF_base.cpp.
References calculer_dt_stab(), Zone_VEF::carre_pas_maille(), Operateur_Diff_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Objet_U::dimension, DMAXFLOAT, Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), la_zone_vef, local_max_vect(), mp_min_vect(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), O_U_Ptr::non_nul(), nu_, remplir_nu(), ArrOfDouble::size_array(), sub_type, Ref_Zone_VEF::valeur(), Champ_Proto::valeurs(), and Champ::valeurs().
{
  if (Motcle(option)=="stabilite")
    {
      DoubleTab& es_valeurs = espace_stockage->valeurs();
      if (la_zone_vef.non_nul())
        {
          remplir_nu(nu_);
          const Zone_VEF& zone_VEF = la_zone_vef.valeur();
          if (! has_champ_masse_volumique())
            {
              const Champ_base& champ_diffusivite = diffusivite_pour_pas_de_temps();
              const DoubleVect&      valeurs_diffusivite = champ_diffusivite.valeurs();
              double alpha_max = local_max_vect(valeurs_diffusivite);
              if ((alpha_max == 0.)||(zone_VEF.nb_elem()==0))
                es_valeurs = DMAXFLOAT;
              else
                {
                  const int nb_elem = zone_VEF.nb_elem();
                  for (int elem = 0; elem < nb_elem; elem++)
                    {
                      es_valeurs(elem) = zone_VEF.carre_pas_maille(elem) / (2. * dimension * alpha_max);
                    }
                }
            }
          else
            {
              const double           deux_dim      = 2. * Objet_U::dimension;
              const Champ_base& champ_diffu   = diffusivite();
              const DoubleTab&       valeurs_diffu = champ_diffu.valeurs();
              const Champ_base&      champ_rho     = get_champ_masse_volumique();
              const DoubleTab&       valeurs_rho   = champ_rho.valeurs();
              assert(sub_type(Champ_Fonc_P0_base, champ_rho));
              assert(sub_type(Champ_Fonc_P0_base, champ_diffu));
              const int nb_elem = zone_VEF.nb_elem();
              assert(valeurs_rho.size_array()==zone_VEF.nb_elem_tot());
// Champ de masse volumique variable.
              for (int elem = 0; elem < nb_elem; elem++)
                {
                  const double h_carre = zone_VEF.carre_pas_maille(elem);
                  const double diffu   = valeurs_diffu(elem);
                  const double rho     = valeurs_rho(elem);
                  const double dt      = h_carre * rho / (deux_dim * diffu);
                  es_valeurs(elem) = dt;
                }
            }
          assert(mp_min_vect(es_valeurs)==calculer_dt_stab());
        }
    }
  else
    Operateur_Diff_base::calculer_pour_post(espace_stockage,option,comp);
}
virtual int Op_Diff_VEF_base::duplique () const [pure virtual]
Implements Operateur_Diff_base.
Implemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
const Type_info * Op_Diff_VEF_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
Definition at line 39 of file Op_Diff_VEF_base.cpp.
Motcle Op_Diff_VEF_base::get_localisation_pour_post (const Nom & option) const [virtual]
Reimplemented from Operateur_base.
Reimplemented in Op_Dift_VEF_Face.
Definition at line 258 of file Op_Diff_VEF_base.cpp.
{
  Motcle loc;
  if (Motcle(option)=="stabilite")
    loc = "elem";
  else
    return Operateur_Diff_base::get_localisation_pour_post(option);
  return loc;
}
int Op_Diff_VEF_base::impr (Sortie & os) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 67 of file Op_Diff_VEF_base.cpp.
{
  return Op_VEF_Face::impr(os, *this);
}
const Type_info * Op_Diff_VEF_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
Definition at line 39 of file Op_Diff_VEF_base.cpp.
int Op_Diff_VEF_base::phi_psi_diffuse (const Equation_base & eq) const
Definition at line 60 of file Op_Diff_VEF_base.cpp.
References Equation_base::inconnue(), and O_U_Ptr::le_nom().
Referenced by Op_Dift_VEF_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Dift_VEF_Face::contribue_au_second_membre(), and Op_Diff_VEFP1NCP1B_Face::test().
{
  if (eq.inconnue().le_nom()=="vitesse")
    return 1;
  return 0;
}
Sortie & Op_Diff_VEF_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
Definition at line 44 of file Op_Diff_VEF_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Diff_VEF_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
Definition at line 53 of file Op_Diff_VEF_base.cpp.
{
  return s ;
}
void Op_Diff_VEF_base::remplir_nu (DoubleTab & nu) const [virtual]
Reimplemented in Op_Dift_VEF_P1NCP1B_Face, and Op_Dift_VEF_Face_Q1.
Definition at line 268 of file Op_Diff_VEF_base.cpp.
References assert_espace_virtuel_vect(), Zone::creer_tableau_elements(), Operateur_Diff_base::diffusivite(), DoubleTab::dimension_tot(), DoubleVect::get_md_vector(), ArrOfDouble::inject_array(), la_zone_vef, DoubleVect::line_size(), Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), DoubleTab::resize(), Ref_Zone_VEF::valeur(), Champ_Proto::valeurs(), and Zone_dis_base::zone().
Referenced by Op_Dift_VEF_Face::ajouter(), Op_Dift_standard_VEF_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Diff_VEF_Face_Q1::calculer_dt_stab(), calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_pour_post(), calculer_pour_post(), and Op_Diff_VEFP1NCP1B_Face::test().
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
// On dimensionne nu
  const DoubleTab& diffu=diffusivite().valeurs();
  if (!nu.get_md_vector().non_nul())
    {
      nu.resize(0, diffu.line_size());
      zone_VEF.zone().creer_tableau_elements(nu, Array_base::NOCOPY_NOINIT);
    }
  if (! diffu.get_md_vector().non_nul())
    {
// diffusvite uniforme
      const int n = nu.dimension_tot(0);
      const int nb_comp = nu.line_size();
// Tableaux vus comme uni-dimenionnels:
      const DoubleVect& arr_diffu = diffu;
      DoubleVect& arr_nu = nu;
      for (int i = 0; i < n; i++)
        for (int j = 0; j < nb_comp; j++)
          arr_nu[i*nb_comp + j] = arr_diffu[j];
    }
  else
    {
      assert(nu.get_md_vector() == diffu.get_md_vector());
      assert_espace_virtuel_vect(diffu);
      nu.inject_array(diffu);
    }
}
const Op_Diff_VEF_base & Op_Diff_VEF_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
Definition at line 39 of file Op_Diff_VEF_base.cpp.
Op_Diff_VEF_base & Op_Diff_VEF_base::self_cast (Objet_U & r) [static]
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
Definition at line 39 of file Op_Diff_VEF_base.cpp.
double Op_Diff_VEF_base::viscA (int face_i, int face_j, int num_elem, double diffu) const [inline]
Definition at line 90 of file Op_Diff_VEF_base.h.
References Objet_U::dimension, Zone_VEF::face_normales(), Zone_VF::face_voisins(), and Zone_VF::inverse_volumes().
Referenced by Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), and Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire().
{
  const Zone_VEF& zone=la_zone_vef.valeur();
  const IntTab& face_voisins=zone.face_voisins();
  const DoubleTab& face_normales=zone.face_normales();
  const DoubleVect& inverse_volumes=zone.inverse_volumes();
  double pscal = face_normales(i,0)*face_normales(j,0)
                 + face_normales(i,1)*face_normales(j,1);
  if (Objet_U::dimension == 3)
    pscal += face_normales(i,2)*face_normales(j,2);
// *zone.porosite_elem(num_elem));
  if ( (face_voisins(i,0) == face_voisins(j,0)) ||
       (face_voisins(i,1) == face_voisins(j,1)) )
    return -(pscal*diffu)*inverse_volumes(num_elem);
  else
    return (pscal*diffu)*inverse_volumes(num_elem);
}
double Op_Diff_VEF_base::viscA (int face_i, int face_j, int num_elem, DoubleTab & diffu) const [inline]
< steph
Definition at line 111 of file Op_Diff_VEF_base.h.
References Objet_U::dimension, Zone_VEF::face_normales(), Zone_VF::face_voisins(), Zone_VF::inverse_volumes(), la_zone_vef, and Ref_Zone_VEF::valeur().
{
  const Zone_VEF& zone=la_zone_vef.valeur();
  const IntTab& face_voisins=zone.face_voisins();
  const DoubleTab& face_normales=zone.face_normales();
  const DoubleVect& inverse_volumes=zone.inverse_volumes();
  double DSiSj=0;
  for (int k=0; k<dimension; k++)
    for (int l=0; l<dimension; l++)
      DSiSj += diffu(num_elem,k*dimension+l)*face_normales(i,k)*face_normales(j,l); //!< steph
  if ( (face_voisins(i,0) == face_voisins(j,0)) ||
       (face_voisins(i,1) == face_voisins(j,1)) )
    return -DSiSj*inverse_volumes(num_elem);
  else
    return DSiSj*inverse_volumes(num_elem);
}
double Op_Diff_VEF_base::viscA (int face_i, int face_j, int num_elem, ArrOfDouble & diffu_ci_cj_elem) const [inline]
Definition at line 133 of file Op_Diff_VEF_base.h.
References Objet_U::dimension, Zone_VEF::face_normales(), Zone_VF::face_voisins(), Zone_VF::inverse_volumes(), la_zone_vef, and Ref_Zone_VEF::valeur().
{
  const Zone_VEF& zone=la_zone_vef.valeur();
  const IntTab& face_voisins=zone.face_voisins();
  const DoubleTab& face_normales=zone.face_normales();
  const DoubleVect& inverse_volumes=zone.inverse_volumes();
  double DSiSj=0;
  for (int k=0; k<dimension; k++)
    for (int l=0; l<dimension; l++)
      DSiSj += diffu_ci_cj_elem(k*dimension+l)*face_normales(i,k)*face_normales(j,l);
  if ( (face_voisins(i,0) == face_voisins(j,0)) ||
       (face_voisins(i,1) == face_voisins(j,1)) )
    return -DSiSj*inverse_volumes(num_elem);
  else
    return DSiSj*inverse_volumes(num_elem);
}
Member Data Documentation
Ref_Champ_Inc_base Op_Diff_VEF_base::inconnue_ [protected]
Definition at line 81 of file Op_Diff_VEF_base.h.
Referenced by Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_VEF_base::associer(), Op_Dift_VEF_P1NCP1B_Face::associer(), Op_Diff_VEFP1NCP1B_Face::associer(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), and Op_Diff_VEFP1NCP1B_Face::dimensionner().
const Type_info Op_Diff_VEF_base::info_obj [static]
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
Definition at line 59 of file Op_Diff_VEF_base.h.
Ref_Zone_Cl_VEF Op_Diff_VEF_base::la_zcl_vef [protected]
Reimplemented in Op_Dift_VEF_P1NCP1B_Face.
Definition at line 80 of file Op_Diff_VEF_base.h.
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_standard_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Op_Dift_VEF_base::associer(), associer(), Op_Diff_VEFP1NCP1B_Face::associer(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_min(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Dift_Stab_VEF_Face::completer(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Dift_VEF_Face_Q1::dimensionner(), Op_Dift_VEF_Face::dimensionner(), Op_Diff_VEF_Face_Q1::dimensionner(), Op_Diff_VEF_Face::dimensionner(), Op_Diff_VEF_Anisotrope_Face::dimensionner(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_VEF_Face_Q1::modifier_pour_Cl(), Op_Dift_VEF_Face::modifier_pour_Cl(), Op_Diff_VEF_Face_Q1::modifier_pour_Cl(), Op_Diff_VEF_Face::modifier_pour_Cl(), Op_Diff_VEF_Anisotrope_Face::modifier_pour_Cl(), Op_Diff_VEFP1NCP1B_Face::test(), Op_Diff_VEF_Face_Penalise::zone_cl(), and Op_Diff_VEFP1NCP1B_Face::zone_Cl_VEFPreP1B().
Ref_Zone_VEF Op_Diff_VEF_base::la_zone_vef [protected]
Reimplemented in Op_Dift_VEF_P1NCP1B_Face.
Definition at line 79 of file Op_Diff_VEF_base.h.
Referenced by Op_Dift_Stab_VEF_Face::aij_extradiag(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_standard_VEF_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion_vectoriel(), Op_Dift_Stab_VEF_Face::ajouter_cas_multiscalaire(), Op_Dift_Stab_VEF_Face::ajouter_cas_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_diffusion(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Op_Dift_Stab_VEF_Face::ajouter_diffusion_vectoriel(), Op_Dift_Stab_VEF_Face::ajouter_operateur_centre(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Op_Dift_Stab_VEF_Face::ajouter_operateur_centre_vectoriel(), Op_Dift_VEF_base::associer(), associer(), Op_Diff_VEFP1NCP1B_Face::associer(), Op_Dift_VEF_base::calculer_borne_locale(), Op_Dift_Stab_VEF_Face::calculer_coefficients(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Op_Dift_VEF_Face_Q1::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Diff_VEF_Face_Q1::calculer_dt_stab(), calculer_dt_stab(), Op_Dift_Stab_VEF_Face::calculer_gradients(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_min(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Dift_VEF_Face::calculer_pour_post(), calculer_pour_post(), Op_Dift_Stab_VEF_Face::completer(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::dimensionner(), Op_Dift_VEF_Face::dimensionner(), Op_Diff_VEF_Face_Q1::dimensionner(), Op_Diff_VEF_Face::dimensionner(), Op_Diff_VEF_Anisotrope_Face::dimensionner(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_VEF_Face_Q1::modifier_pour_Cl(), Op_Dift_VEF_Face::modifier_pour_Cl(), Op_Diff_VEF_Face_Q1::modifier_pour_Cl(), Op_Diff_VEF_Face::modifier_pour_Cl(), Op_Diff_VEF_Anisotrope_Face::modifier_pour_Cl(), remplir_nu(), Op_Diff_VEF_Face::verifier(), Op_Diff_VEF_Anisotrope_Face::verifier(), viscA(), Op_Diff_VEF_Face_Penalise::zone_vef(), and Op_Diff_VEFP1NCP1B_Face::zone_VEFPreP1B().
DoubleTab Op_Diff_VEF_base::nu_ [mutable, protected]
Definition at line 83 of file Op_Diff_VEF_base.h.
Referenced by Op_Dift_VEF_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Diff_VEF_Face_Q1::calculer_dt_stab(), calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Dift_VEF_Face::calculer_pour_post(), calculer_pour_post(), Op_Dift_VEF_Face::contribue_au_second_membre(), and Op_Diff_VEFP1NCP1B_Face::test().
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Diff_VEF_base.h
src/VEF/Operateurs/Op_Diff_VEF_base.cpp