TRUST: TRUSTTab< _TYPE_ > Class Template Reference
TRUSTTab< _TYPE_ > Class Template Reference
: Tableau a n entrees pour n<= 4. Repose sur un TRUSTVect avec calculs de l'indice corespondant
#include <TRUSTTab.h>
Public Member Functions
TRUSTTab ()
TRUSTTab (const TRUSTTab &dbt)
TRUSTTab (int n)
TRUSTTab (int n1, int n2)
TRUSTTab (int n1, int n2, int n3)
TRUSTTab (int n1, int n2, int n3, int n4)
void resize_dim0 (int n, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void resize (int n, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void resize (int n1, int n2, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void resize (int n1, int n2, int n3, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void resize (int n1, int n2, int n3, int n4, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void resize (const TRUSTArray< int > &tailles, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void copy (const TRUSTTab &, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void append_line (_TYPE_)
void append_line (_TYPE_, _TYPE_)
void append_line (_TYPE_, _TYPE_, _TYPE_)
void append_line (_TYPE_, _TYPE_, _TYPE_, _TYPE_)
int dimension (int) const
int dimension_tot (int) const
int nb_dim () const
TRUSTTab & operator= (const TRUSTTab &)
TRUSTTab & operator= (const TRUSTVect< _TYPE_ > &)
TRUSTTab & operator= (_TYPE_ d)
_TYPE_ & operator() (const TRUSTArray< int > &indice)
_TYPE_ operator() (const TRUSTArray< int > &indice) const
_TYPE_ & operator[] (int i)
const _TYPE_ & operator[] (int i) const
_TYPE_ & operator() (int i)
const _TYPE_ & operator() (int i) const
_TYPE_ & operator() (int i1, int i2)
const _TYPE_ & operator() (int i1, int i2) const
_TYPE_ & operator() (int i1, int i2, int i3)
const _TYPE_ & operator() (int i1, int i2, int i3) const
_TYPE_ & operator() (int i1, int i2, int i3, int i4)
const _TYPE_ & operator() (int i1, int i2, int i3, int i4) const
void ajoute_produit_tensoriel (double alpha, const TRUSTTab< double > &, const TRUSTTab< double > &)
z+=alpha*x*y;
void resoud_LU (int, TRUSTArray< int > &, const TRUSTArray< double > &, TRUSTArray< double > &)
int inverse_LU (const TRUSTArray< double > &, TRUSTArray< double > &)
int decomp_LU (int, TRUSTArray< int > &, TRUSTTab< double > &)
double max_du_u (const TRUSTTab< double > &)
virtual void ref (const TRUSTTab &)
virtual void ref_tab (TRUSTTab &, int start_line=0, int nb_lines=-1)
void set_md_vector (const MD_Vector &) override
void jump (Entree &) override
void lit (Entree &, int resize_and_read=1) override
void ecrit (Sortie &) const override
void ref (const TRUSTVect< _TYPE_ > &) override
void ref_data (_TYPE_ *ptr, int size) override
void ref_array (TRUSTArray< _TYPE_ > &, int start=0, int sz=-1) override
void reset () override
void resize_tab (int n, Array_base::Resize_Options opt=Array_base::COPY_INIT) override
Public Member Functions inherited from TRUSTVect< _TYPE_ >
virtual ~TRUSTVect ()
TRUSTVect ()
TRUSTVect (int n)
construction d'un vecteur de taille n. Les elements du vecteur sont initialises a zero par defaut. Pour ne pas initialiser les valeurs, utiliser ceci:
DoubleVect toto;
toto.resize(n, NOCOPY_NOINIT);
TRUSTVect (const TRUSTVect &v)
Constructeur par copie. Il s'agit d'un "deep copy" voir ArrOfDouble::ArrOfDouble(const ArrOfDouble &)
Remarque: il n'y a pas de constructeur par copie a partir de ArrOfDouble
Ceci est volontaire, sinon on risque de grosses pertes de performances par creation implicite d'objets, difficile a trouver.
(exemple: appel d'une methode toto(const IntVect &) avec un ArrOfInt produit une copie du tableau !)
Utiliser copy() pour copier un ArrOfDouble dans un DoubleVect.
TRUSTVect & operator= (const TRUSTVect &)
TRUSTVect & operator= (_TYPE_)
int size () const
int size_totale () const
int size_reelle () const
int size_reelle_ok () const
int line_size () const
void resize (int, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void copy (const TRUSTArray< _TYPE_ > &, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void copy (const TRUSTVect &, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void operator+= (const TRUSTVect &v)
void operator+= (const _TYPE_ x)
void operator-= (const TRUSTVect &v)
void operator-= (const _TYPE_ x)
void operator*= (const TRUSTVect &v)
void operator*= (const _TYPE_ x)
void operator/= (const TRUSTVect< double > &v)
void operator/= (const TRUSTVect< int > &v)=delete
forbidden
void operator/= (const _TYPE_ x)
void abs (Mp_vect_options opt=VECT_ALL_ITEMS)
void carre (Mp_vect_options opt=VECT_ALL_ITEMS)
void racine_carree (Mp_vect_options opt=VECT_ALL_ITEMS)
void ajoute (double alpha, const TRUSTVect< double > &y, Mp_vect_options opt=VECT_ALL_ITEMS)
void ajoute_sans_ech_esp_virt (double alpha, const TRUSTVect< double > &y, Mp_vect_options opt=VECT_REAL_ITEMS)
x+=alpha*y sans echange_espace_virtuel
void ajoute_produit_scalaire (double alpha, const TRUSTVect< double > &x, const TRUSTVect< double > &y, Mp_vect_options opt=VECT_ALL_ITEMS)
z+=alpha*x*y;
void ajoute_carre (double alpha, const TRUSTVect< double > &y, Mp_vect_options opt=VECT_ALL_ITEMS)
void ajoute (int alpha, const TRUSTVect< int > &y, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden ... a voir si besoin
void ajoute_sans_ech_esp_virt (int alpha, const TRUSTVect< int > &y, Mp_vect_options opt=VECT_REAL_ITEMS)=delete
forbidden ... a voir si besoin
void ajoute_produit_scalaire (int alpha, const TRUSTVect< int > &x, const TRUSTVect< int > &y, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden ... a voir si besoin
void ajoute_carre (int alpha, const TRUSTVect< int > &y, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden ... a voir si besoin
_TYPE_ local_max_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ local_min_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ local_max_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ local_min_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ mp_max_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ mp_min_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ mp_max_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ mp_min_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ mp_norme_vect () const
virtual void ref (const TRUSTVect &)
virtual void echange_espace_virtuel ()
virtual void set_md_vector (const MD_Vector &)
virtual void jump (Entree &)
virtual void lit (Entree &, int resize_and_read=1)
virtual void ecrit (Sortie &) const
virtual void detach_vect ()
virtual const MD_Vector & get_md_vector () const
void resize_tab (int n, Array_base::Resize_Options opt=Array_base::COPY_INIT) override
void ref_data (_TYPE_ *ptr, int new_size) override
void ref_array (TRUSTArray< _TYPE_ > &, int start=0, int sz=-1) override
void reset () override
met l'objet dans l'etat obtenu par le constructeur par defaut.
Public Member Functions inherited from TRUSTArray< _TYPE_ >
Iterator begin ()
Iterator end ()
virtual ~TRUSTArray ()
TRUSTArray ()
TRUSTArray (int n)
TRUSTArray (const TRUSTArray &A)
void resize (int new_size, Array_base::Resize_Options opt=COPY_INIT)
void resize_array (int new_size, Array_base::Resize_Options opt=COPY_INIT)
void set_smart_resize (int flag)
void set_mem_storage (const Storage storage)
Storage get_mem_storage () const
TRUSTArray & operator= (const TRUSTArray &)
TRUSTArray & operator= (_TYPE_ x)
_TYPE_ & operator[] (int i)
const _TYPE_ & operator[] (int i) const
!<
_TYPE_ & operator() (int i)
const _TYPE_ & operator() (int i) const
_TYPE_ * addr ()
!<
const _TYPE_ * addr () const
int size_array () const
int ref_count () const
void append_array (_TYPE_ valeur)
TRUSTArray & operator+= (const TRUSTArray &y)
TRUSTArray & operator+= (const _TYPE_ dy)
TRUSTArray & operator-= (const TRUSTArray &y)
TRUSTArray & operator-= (const _TYPE_ dy)
TRUSTArray & operator*= (const _TYPE_ dy)
TRUSTArray & operator/= (const _TYPE_ dy)
TRUSTArray & inject_array (const TRUSTArray &source, int nb_elements=-1, int first_element_dest=0, int first_element_source=0)
TRUSTArray & copy_array (const TRUSTArray &a)
void ordonne_array ()
void array_trier_retirer_doublons ()
!<
virtual void ref_data (_TYPE_ *ptr, int size)
virtual void reset ()
virtual void ref_array (TRUSTArray &, int start=0, int sz=-1)
virtual void resize_tab (int n, Array_base::Resize_Options opt=COPY_INIT)
Public Member Functions inherited from Array_base
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Protected Member Functions
unsigned taille_memoire () const override
int duplique () const override
Sortie & printOn (Sortie &os) const override
ecriture d'un tableau sequentiel (idem que TRUSTVect::printOn() on ne sait pas quoi faire de pertinent pour un tableau distribue).
Entree & readOn (Entree &is) override
lecture d'un tableau sequentiel
Protected Member Functions inherited from TRUSTVect< _TYPE_ >
unsigned taille_memoire () const override
int duplique () const override
Sortie & printOn (Sortie &os) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &is) override
Lecture d'un vecteur sequentiel (comme un ArrOfDouble)
Attention: appel invalide si le vecteur a un MD_Vector non nul. (pour les vecteurs paralleles, utiliser une methode de sauvegarde/reprise)
void set_line_size_ (int n)
void resize_vect_ (int n, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void copy_ (const TRUSTVect &v, Array_base::Resize_Options opt=Array_base::COPY_INIT)
Protected Member Functions inherited from TRUSTArray< _TYPE_ >
unsigned taille_memoire () const override
int duplique () const override
Sortie & printOn (Sortie &os) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &is) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void attach_array (const TRUSTArray &a, int start=0, int size=-1)
void fill_default_value (Array_base::Resize_Options opt, int first, int nb)
void resize_array_ (int n, Array_base::Resize_Options opt=COPY_INIT)
int detach_array ()
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void verifie_MAXDIM_TAB () const
bool verifie_LINE_SIZE () const
void init_dimensions (int *tab)
Private Attributes
int nb_dim_
int dimensions_ [MAXDIM_TAB]
int dimension_tot_0_
Static Private Attributes
static constexpr int MAXDIM_TAB = 4
Additional Inherited Members
Public Types inherited from TRUSTArray< _TYPE_ >
using value_type = _TYPE_
return int, double ou float
using Iterator = TRUSTIterator< TRUSTArray< _TYPE_ > >
Public Types inherited from Array_base
enum Resize_Options { NOCOPY_NOINIT = 0 , COPY_NOINIT = 1 , COPY_INIT = 2 }
enum Storage { STANDARD , TEMP_STORAGE }
Static Public Member Functions inherited from Array_base
static const Type_info * info ()
static Array_base & self_cast (Objet_U &)
static const Array_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes inherited from Array_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Detailed Description
template<typename _TYPE_>
class TRUSTTab< _TYPE_ >
: Tableau a n entrees pour n<= 4. Repose sur un TRUSTVect avec calculs de l'indice corespondant
Definition at line 25 of file TRUSTTab.h.
Constructor & Destructor Documentation
TRUSTTab() [1/6]
template<typename _TYPE_ > TRUSTTab< _TYPE_ >::TRUSTTab () inline
Definition at line 110 of file TRUSTTab.h.
             : nb_dim_(1), dimension_tot_0_(0)
  {
    init_dimensions(dimensions_);
    dimensions_[0] = 0;
  }
References TRUSTTab< _TYPE_ >::dimensions_, and TRUSTTab< _TYPE_ >::init_dimensions().
Referenced by TRUSTTab< _TYPE_ >::duplique().
TRUSTTab() [2/6]
template<typename _TYPE_ > TRUSTTab< _TYPE_ >::TRUSTTab (const TRUSTTab< _TYPE_ > & dbt) inline
Definition at line 116 of file TRUSTTab.h.
                               : TRUSTVect<_TYPE_>(dbt), nb_dim_(dbt.nb_dim_), dimension_tot_0_(dbt.dimension_tot_0_)
  {
    for (int i = 0; i < MAXDIM_TAB; i++) dimensions_[i] = dbt.dimensions_[i];
  }
References TRUSTTab< _TYPE_ >::dimensions_, and TRUSTTab< _TYPE_ >::MAXDIM_TAB.
TRUSTTab() [3/6]
template<typename _TYPE_ > TRUSTTab< _TYPE_ >::TRUSTTab (int n) inline
Definition at line 137 of file TRUSTTab.h.
                  : TRUSTVect<_TYPE_>(n), nb_dim_(1), dimension_tot_0_(n)
  {
    init_dimensions(dimensions_);
    dimensions_[0] = n;
  }
References TRUSTTab< _TYPE_ >::dimensions_, and TRUSTTab< _TYPE_ >::init_dimensions().
TRUSTTab() [4/6]
template<typename _TYPE_ > TRUSTTab< _TYPE_ >::TRUSTTab (int n1, int n2) inline
Definition at line 143 of file TRUSTTab.h.
                          : TRUSTVect<_TYPE_>(n1*n2), nb_dim_(2), dimension_tot_0_(n1)
  {
    assert(n1 >= 0 && n2 >= 0);
    if (std::is_same<_TYPE_,int>::value && n1*n2 < 0)
      {
        Cerr << "n1*n2 > 2^31. Error! Contact TRUST support, integer 32 bits limit exceeded with n1=" << n1 << " and n2=" << n2 << finl;
        Process::exit();
      }
    init_dimensions(dimensions_);
    dimensions_[0]=n1;
    dimensions_[1]=n2;
    TRUSTVect<_TYPE_>::set_line_size_(n2);
  }
References Cerr, TRUSTTab< _TYPE_ >::dimensions_, Process::exit(), finl, TRUSTTab< _TYPE_ >::init_dimensions(), and TRUSTVect< _TYPE_ >::set_line_size_().
TRUSTTab() [5/6]
template<typename _TYPE_ > TRUSTTab< _TYPE_ >::TRUSTTab (int n1, int n2, int n3) inline
Definition at line 157 of file TRUSTTab.h.
                                   : TRUSTVect<_TYPE_>(n1*n2*n3), nb_dim_(3), dimension_tot_0_(n1)
  {
    assert(n1 >= 0 && n2 >= 0 && n3 >= 0);
    if (std::is_same<_TYPE_,int>::value && n1*n2*n3 < 0)
      {
        Cerr << "n1*n2*n3 > 2^31. Error! Contact TRUST support, integer 32 bits limit exceeded with n1=" << n1 << " and n2=" << n2 << " and n3=" << n3 << finl;
        Process::exit();
      }
    init_dimensions(dimensions_);
    dimensions_[0]=n1;
    dimensions_[1]=n2;
    dimensions_[2]=n3;
    TRUSTVect<_TYPE_>::set_line_size_(n2*n3);
  }
References Cerr, TRUSTTab< _TYPE_ >::dimensions_, Process::exit(), finl, TRUSTTab< _TYPE_ >::init_dimensions(), and TRUSTVect< _TYPE_ >::set_line_size_().
TRUSTTab() [6/6]
template<typename _TYPE_ > TRUSTTab< _TYPE_ >::TRUSTTab (int n1, int n2, int n3, int n4) inline
Definition at line 172 of file TRUSTTab.h.
                                           : TRUSTVect<_TYPE_>(n1*n2*n3*n4), nb_dim_(4), dimension_tot_0_(n1)
  {
    assert(n1 >= 0 && n2 >= 0 && n3 >= 0 && n4 >= 0);
    if (std::is_same<_TYPE_,int>::value && n1*n2*n3*n4 < 0)
      {
        Cerr << "n1*n2*n3*n4 > 2^31. Error! Contact TRUST support, integer 32 bits limit exceeded with n1=" << n1 << " and n2=" << n2 << " and n3=" << n3 << " and n3=" << n3 << finl;
        Process::exit();
      }
    init_dimensions(dimensions_);
    dimensions_[0]=n1;
    dimensions_[1]=n2;
    dimensions_[2]=n3;
    dimensions_[3]=n4;
    TRUSTVect<_TYPE_>::set_line_size_(n2*n3*n4);
  }
References Cerr, TRUSTTab< _TYPE_ >::dimensions_, Process::exit(), finl, TRUSTTab< _TYPE_ >::init_dimensions(), and TRUSTVect< _TYPE_ >::set_line_size_().
Member Function Documentation
ajoute_produit_tensoriel()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::ajoute_produit_tensoriel (double alpha, const TRUSTTab< double > & x, const TRUSTTab< double > & y) inline
z+=alpha*x*y;
Definition at line 589 of file TRUSTTab.tpp.
{
// Tableaux vus comme des tableaux unidimensionnels (pour ne pas avoir a gerer nb_dim)
  const TRUSTVect<double>& vx = x, &vy = y;
  TRUSTVect<double>& v = *this;
  const int line_size_x = vx.line_size(), line_size_y = vy.line_size(), line_size_xy = v.line_size();
  assert(line_size_xy == line_size_x * line_size_y);
// Pour ne pas diviser par line_size()
  assert(vx.size_totale() * line_size_xy == v.size_totale() * line_size_x);
  assert(vy.size_totale() * line_size_xy == v.size_totale() * line_size_y);
// blocs d'items a traiter (un bloc par defaut: tout le tableau)
  int default_bloc[2];
  default_bloc[0] = 0;
  default_bloc[1] = (v.line_size() > 0) ? (v.size_totale() / v.line_size()) : 0;
  const int *blocs = default_bloc;
  int nb_blocs = 1;
  if (v.get_md_vector().non_nul())
    {
      const TRUSTArray<int>& blk = v.get_md_vector().valeur().get_items_to_compute();
      blocs = blk.addr();
      nb_blocs = blk.size_array() / 2;
    }
  for (int i_bloc = 0; i_bloc < nb_blocs; i_bloc++)
    {
      const int debut = blocs[i_bloc*2], fin = blocs[i_bloc*2+1];
      int v_index = debut * line_size_xy;
      for (int i = debut; i < fin; i++)
        for (int j = 0; j < line_size_x; j++)
          {
            double xval = vx[i * line_size_x + j];
            for (int k = 0; k < line_size_y; k++)
              {
                double yval = vy[i * line_size_y + k];
                v[v_index] += alpha * xval * yval;
                v_index++;
              }
          }
    }
}
References TRUSTArray< _TYPE_ >::addr(), MD_Vector_base::get_items_to_compute(), TRUSTVect< _TYPE_ >::get_md_vector(), TRUSTVect< _TYPE_ >::line_size(), MD_Vector::non_nul(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), and MD_Vector::valeur().
Referenced by Integrale_tps_produit_champs::ajoute_produit_tensoriel().
append_line() [1/4]
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::append_line (_TYPE_ a) inline
Definition at line 138 of file TRUSTTab.tpp.
{
  assert(TRUSTVect<_TYPE_>::line_size() == 1);
  assert(dimension_tot_0_ * TRUSTVect<_TYPE_>::line_size() == TRUSTVect<_TYPE_>::size_array());
  const int n = dimension_tot_0_;
  dimensions_[0] = ++dimension_tot_0_;
  TRUSTVect<_TYPE_>::resize_vect_(n+1, Array_base::COPY_NOINIT);
  _TYPE_ * ptr = TRUSTVect<_TYPE_>::addr() + n;
  ptr[0] = a;
}
References TRUSTArray< _TYPE_ >::addr(), Array_base::COPY_NOINIT, and TRUSTVect< _TYPE_ >::resize_vect_().
Referenced by SETS::assembler(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Zone::creer_aretes(), Op_Div_PolyMAC_P0::dimensionner(), Masse_PolyMAC_Face::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_VDF_Face::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Div_PolyMAC::dimensionner_blocs(), Op_Grad_PolyMAC_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Masse_PolyMAC_Elem::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::dimensionner_blocs(), Flux_interfacial_PolyMAC::dimensionner_blocs(), Force_Tchen_PolyMAC_P0::dimensionner_blocs(), Frottement_interfacial_PolyMAC_P0::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs(), Travail_pression_PolyMAC::dimensionner_blocs(), Op_Diff_PolyMAC_Elem::dimensionner_blocs_ext(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Assembleur_P_PolyMAC::dimensionner_continuite(), Assembleur_P_PolyMAC_P0::dimensionner_continuite(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), SETS::eliminer(), Matrice_Dense::get_stencil(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Op_Diff_PolyMAC_P0_Elem::init_som_ext(), Zone_PolyMAC_P0::init_stencils(), and Traduction_Indice_Global_Local::initialiser().
append_line() [2/4]
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::append_line (_TYPE_ a, _TYPE_ b) inline
Definition at line 152 of file TRUSTTab.tpp.
{
  assert(TRUSTVect<_TYPE_>::line_size() == 2);
  assert(dimension_tot_0_ * TRUSTVect<_TYPE_>::line_size() == TRUSTVect<_TYPE_>::size_array());
  const int n = dimension_tot_0_ * 2;
  dimensions_[0] = ++dimension_tot_0_;
  TRUSTVect<_TYPE_>::resize_vect_(n+2, Array_base::COPY_NOINIT);
  _TYPE_ * ptr = TRUSTVect<_TYPE_>::addr() + n;
  ptr[0] = a;
  ptr[1] = b;
}
References TRUSTArray< _TYPE_ >::addr(), Array_base::COPY_NOINIT, and TRUSTVect< _TYPE_ >::resize_vect_().
append_line() [3/4]
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::append_line (_TYPE_ a, _TYPE_ b, _TYPE_ c) inline
Definition at line 166 of file TRUSTTab.tpp.
{
  assert(TRUSTVect<_TYPE_>::line_size() == 3);
  assert(dimension_tot_0_  * TRUSTVect<_TYPE_>::line_size() == TRUSTVect<_TYPE_>::size_array());
  const int n = dimension_tot_0_ * 3;
  dimensions_[0] = ++dimension_tot_0_;
  TRUSTVect<_TYPE_>::resize_vect_(n+3, Array_base::COPY_NOINIT);
  _TYPE_ * ptr = TRUSTVect<_TYPE_>::addr() + n;
  ptr[0] = a;
  ptr[1] = b;
  ptr[2] = c;
}
References TRUSTArray< _TYPE_ >::addr(), Array_base::COPY_NOINIT, and TRUSTVect< _TYPE_ >::resize_vect_().
append_line() [4/4]
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::append_line (_TYPE_ a, _TYPE_ b, _TYPE_ c, _TYPE_ d) inline
Definition at line 181 of file TRUSTTab.tpp.
{
  assert(TRUSTVect<_TYPE_>::line_size() == 4);
  assert(dimension_tot_0_  * TRUSTVect<_TYPE_>::line_size() == TRUSTVect<_TYPE_>::size_array());
  const int n = dimension_tot_0_ * 4;
  dimensions_[0] = ++dimension_tot_0_;
  TRUSTVect<_TYPE_>::resize_vect_(n+4, Array_base::COPY_NOINIT);
  _TYPE_ * ptr = TRUSTVect<_TYPE_>::addr() + n;
  ptr[0] = a;
  ptr[1] = b;
  ptr[2] = c;
  ptr[3] = d;
}
References Array_base::COPY_NOINIT, and TRUSTVect< _TYPE_ >::resize_vect_().
copy()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::copy (const TRUSTTab< _TYPE_ > & src, Array_base::Resize_Options opt = Array_base::COPY_INIT) inline
Definition at line 463 of file TRUSTTab.tpp.
{
  if (&src != this)
    {
      TRUSTVect<_TYPE_>::copy_(src, opt);
      nb_dim_ = src.nb_dim_;
      for (int i = 0; i < MAXDIM_TAB; i++) dimensions_[i] = src.dimensions_[i];
      dimension_tot_0_ = src.dimension_tot_0_;
      assert(verifie_LINE_SIZE());
    }
}
References TRUSTVect< _TYPE_ >::copy_(), TRUSTTab< _TYPE_ >::dimension_tot_0_, TRUSTTab< _TYPE_ >::dimensions_, and TRUSTTab< _TYPE_ >::nb_dim_.
Referenced by Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::ajouter_masse_dt_local(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Op_Moyenne::completer(), Zone_VEF_PreP1b::construire_ok_arete(), Equation_base::derivee_en_temps_conv(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), echanger_tableau_aretes(), Solveur_Masse_base::get_masse_divide_by_local_dt(), Solveur_Masse_base::get_masse_dt_local(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), TRUSTTrav< _TYPE_ >::TRUSTTrav(), and Navier_Stokes_std::uzawa().
decomp_LU()
template<typename _TYPE_ > int TRUSTTab< _TYPE_ >::decomp_LU (int n, TRUSTArray< int > & index, TRUSTTab< double > & matLU) inline
Returns
matrice A_ = assemblage (L-diagonale)+U
Definition at line 649 of file TRUSTTab.tpp.
{
  TRUSTArray<double> vv(n);
  int i, j, k,  imax = -1, cvg = 1;
  double big, dum, sum, temp;
  matLU = (*this);
// Recupere le coeff max d'une ligne, stocke dans vv
  for (i=0 ; i<n ; i++)
    {
      big = 0;
      for (j=0 ; j<n ; j++)
        if ((temp = std::fabs(matLU(i,j))) > big) big = temp;
      if (big == 0)
        {
          Cerr <<"Singular matrix in LU decomposition"<<finl;
          cvg = 0;
          Process::exit();
        }
      vv[i] = 1./big;
    }
// calcul de la matrice matLU
  for (j=0 ; j<n ; j++)
    {
      for (i=0 ; i<j ; i++)
        {
          sum = matLU(i,j);
          for (k=0 ; k<i ; k++) sum -= matLU(i,k) * matLU(k,j);
          matLU(i,j) = sum;
        }
      big = 0;
      for (i=j ; i<n ; i++)
        {
          sum = matLU(i,j);
          for (k=0 ; k<j ; k++) sum -= matLU(i,k) * matLU(k,j);
          matLU(i,j) = sum;
          if ((dum = vv[i]*std::fabs(sum)) >= big)
            {
              big = dum;
              imax = i;
            }
        }
      if (j != imax)
        {
          for (k=0 ; k<n ; k++)
            {
              dum = matLU(imax,k);
              matLU(imax,k) = matLU(j,k);
              matLU(j,k) = dum;
            }
          vv[imax] = vv[j];
        }
      index[j] = imax;
      dum = 1./matLU(j,j);
      for (i=j+1 ; i<n ; i++) matLU(i,j) *= dum;
    }
  return cvg;
}
References Cerr, Process::exit(), and finl.
dimension()
template<typename _TYPE_ > int TRUSTTab< _TYPE_ >::dimension (int i) const inline
Definition at line 119 of file TRUSTTab.tpp.
{
  assert(i >= 0 && i < nb_dim_);
// Si dimension_[0] == -1, c'est que c'est un vecteur distribue et que l'attribut size() est invalide. Il faut alors utiliser dimension_tot pour ce tableau.
  assert(dimensions_[i] >= 0);
  return dimensions_[i];
}
Referenced by Frontiere::add(), BlocData::add_bloc(), BlocData::add_faces(), Debog_Pb::add_renum_item(), Matrix_tools::add_scaled_matrices(), Matrix_tools::add_symmetric_scaled_matrices(), Champ_Face::affecter(), Champ_Inc_base::affecter_(), Champ_P1NC::affecter_(), Champ_Uniforme_Morceaux::affecter_(), Masse_ajoutee_Coef_Constant::ajouter(), Domaine::ajouter(), Op_Grad_EF::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Faces::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Source_QC_Chaleur::ajouter_(), Source_WC_Chaleur::ajouter_(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Op_Div_PolyMAC::ajouter_blocs(), Op_Grad_PolyMAC_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), ajouter_bord(), Sonde::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Conv_Muscl_New_VEF_Face::ajouter_diffusion(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Polyedre::ajouter_elements(), Matrice_Morse::ajouter_multTab_(), Matrice_Morse_Sym::ajouter_multTab_(), Matrice_Diagonale::ajouter_multTab_(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), Faces_builder::ajouter_une_face(), Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), Matrix_tools::allocate_morse_matrix(), Matrix_tools::allocate_symmetric_morse_matrix(), Solveur_Masse_EF::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Refine_Mesh::apply_2D(), Refine_Mesh::apply_3D(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC::assembler_continuite(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Assembleur_P_EF::assembler_mat(), Assembleur_P_PolyMAC::assembler_mat(), Simpler_Base::assembler_matrice_pression_implicite(), Op_Diff_VEF_base::associer(), Pave::associer_domaine(), auto_build_joints(), bbox_intersection(), Octree_Int::build(), Octree_Zone::build(), build_cells(), build_edges(), Refine_Mesh::build_edges(), Octree_Double::build_elements(), build_frontier(), Refine_Mesh::build_incidence_from_node_to_edges(), Matrix_tools::build_morse_matrix(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), Refine_Mesh::build_new_nodes(), Octree_Double::build_nodes(), build_nodes(), Octree_Int::build_octree_recursively(), Matrice_Bloc::build_stencil(), Matrix_tools::build_symmetric_morse_matrix(), build_triofield(), Ch_front_input::buildSommetsFaces(), Domaine::buildUFacesMesh(), Champ_P1NC::calcul_h_conv(), Calcul_integrale_locale::Calcul_integrale_locale(), calcul_tab_norme(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Calcul_integrale_locale::calculer(), Op_Dift_EF_base::calculer_borne_locale(), Op_Dift_VEF_base::calculer_borne_locale(), Aretes::calculer_centre_de_gravite(), Elem_geom_base::calculer_centres_gravite(), Polyedre::calculer_centres_gravite(), Polygone::calculer_centres_gravite(), calculer_centres_gravite(), Zone_VF::calculer_coefficient_echange_thermique(), Zone_VF::calculer_coefficient_frottement(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Dift_Stab_VEF_Face::calculer_coefficients(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Moyenne_volumique::calculer_convolution(), Moyenne_volumique::calculer_convolution_champ_elem(), Simple::calculer_correction_en_vitesse(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Partitionneur_base::calculer_graphe_connexions_periodiques(), Loi_Etat_rhoT_GR_QC::calculer_H(), Echange_contact_VDF::calculer_h_autre_pb(), calculer_h_distant(), Terme_Source_Acceleration::calculer_la_source(), calculer_liste_complete_aretes_joint(), Loi_Etat_rhoT_GR_QC::calculer_masse_volumique(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Dift_Stab_VEF_Face::calculer_min(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Hexaedre::calculer_normales(), Rectangle::calculer_normales(), Tetraedre::calculer_normales(), Triangle::calculer_normales(), Navier_Stokes_std::calculer_pression_hydrostatique(), Op_Conv_EF_VEF_P1NC_Stab::calculer_senseur(), Op_Conv_Muscl_New_VEF_Face::calculer_senseur_v1(), Faces::calculer_surfaces(), Loi_Etat_rhoT_GR_QC::calculer_temperature(), Echange_contact_VDF::calculer_Teta_equiv(), calculer_vecteur_2faces(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Polyedre::calculer_volumes(), caldscaldcentelemdim2(), caldscaldcentelemdim3(), calrotord2centelemdim2(), calrotord2centelemdim3(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Echange_global_impose::champ_exterieur(), Echange_couplage_thermique::champ_exterieur(), Champ_Face_get_val_imp_face_bord(), Champ_Face_get_val_imp_face_bord_sym(), Assembleur_P_VEFPreP1B::changer_base_pression(), Assembleur_P_VEFPreP1B::changer_base_pression_inverse(), Assembleur_P_VEFPreP1B::changer_base_second_membre(), check(), Rectify_Mesh::check_cell_enumeration_3D(), Rectify_Mesh::check_cell_orientation_2D(), Rectify_Mesh::check_cell_orientation_3D(), Faces_builder::check_erreur_faces(), Reordonner_faces_periodiques::check_faces_periodiques(), check_internal_diagonal_for_tetrahedron(), check_positive_volumes_for_tetrahedron(), check_positive_volumes_for_triangle(), Fluide_reel_base::check_unknown_range(), Zone::check_zone(), Scatter::Chercher_Correspondance(), Reordonner_faces_periodiques::chercher_direction_perio(), Zone::chercher_elements(), chercher_elems_voisins_faces(), Faces_builder::chercher_face_element(), Traduction_Indice_Global_Local::chercher_table_inverse(), choose_internal_diagonal_for_tetrahedron(), clamp(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), Portance_interfaciale_Tomiyama::coefficient(), Frottement_interfacial_bulles::coefficient(), Frottement_interfacial_Tomiyama::coefficient(), Flux_interfacial_Coef_Constant::coeffs(), Flux_interfacial_Ranz_Marshall::coeffs(), Raccord_distant_homogene::completer(), Champ_front_calc_interne::completer(), Periodique::completer(), Champ_Generique_Extraction::completer(), Op_Correlation::completer(), Zones::comprimer(), compute_cell_qualities_for_tetrahedron(), compute_cell_qualities_for_triangle(), compute_global_connex_components(), compute_graph_connex_components(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Octree_Double::compute_origin_factors(), OctreeRoot::construire(), construire_connectivite_real_som_virtual_elem(), construire_connectivite_som_elem(), Zone::construire_elem_virt_pe_num(), DomaineCutter::construire_elements_distants_ssdom(), construire_elems_sous_domaine(), DomaineCutter::construire_faces_joints_ssdom(), Domain_Graph::construire_graph_elem_elem(), Domain_Graph::construire_graph_from_segment(), construire_liste_faces_sous_domaine(), construire_liste_sommets_sousdomaine(), Zone_VF::construire_num_fac_loc(), Zone_VEF_PreP1b::construire_ok_arete(), Partitionneur_Partition::construire_partition(), Partitionneur_Tranche::construire_partition(), Scatter::construire_structures_paralleles(), construit_connectivite_sommet(), Polyedre::contient(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec(), Source_Fluide_Dilatable_Face< DERIVED_T >::contribuer_a_avec_impl(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), convert_domain_to_Domaine(), coord_barycentrique(), coord_barycentrique_P1(), coord_barycentrique_P1_hexaedre(), coord_barycentrique_P1_rectangle(), coord_barycentrique_P1_tetraedre(), coord_barycentrique_P1_triangle(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), Source_PDF_EF::correct_vitesse(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Partitionneur_base::corriger_multiperiodique(), Partitionneur_base::corriger_sommets_bord(), create_listb_from_domaine2(), create_listb_from_xyz(), create_listb_geom(), Zone::creer_aretes(), Remove_elem::creer_faces(), Faces_builder::creer_faces_frontiere(), Faces_builder::creer_faces_internes(), Faces_builder::creer_faces_reeles(), decoupe(), Tetraedriser_homogene_compact::decoupe(), Tetraedriser_homogene_fin::decoupe(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Polynome::degre(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Matrice_Morse::dimensionner(), Roue::dimensionner(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Div_PolyMAC::dimensionner_blocs(), Op_Grad_PolyMAC_Face::dimensionner_blocs(), Travail_pression_PolyMAC::dimensionner_blocs(), Op_Diff_PolyMAC_Elem::dimensionner_blocs_ext(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Assembleur_P_PolyMAC::dimensionner_continuite(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Zone_Poly_base::discretiser(), Zone_VEF_PreP1b::discretiser(), Zone_PolyMAC::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), disp_dt(), disp_it(), disp_m(), diviser_par_rho_np1_face(), Loi_Etat_rhoT_GR_QC::Drho_DP(), Loi_Etat_rhoT_GR_QC::Drho_DT(), Loi_Etat_rhoT_GR_QC::DT_DH(), echanger_tableau_aretes(), Format_Post_Lata_V1::ecrire_champ_lata_V1(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_XYZ::ecrire_champ_xyz(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Med::ecrire_domaine_med(), Format_Post_Lata_V1::ecrire_faces_lata_V1(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Debog_Pb::ecrire_gen(), Format_Post_Lata::ecrire_item_int(), Format_Post_Lml::ecrire_item_int_lml(), Postraitement_lata::ecrire_zone(), ecrit(), EcritureLectureSpecial::ecriture_special(), Viscosite_turbulente_multiple::eddy_viscosity(), ensure_positive_volumes_for_tetrahedron(), ensure_positive_volumes_for_triangle(), envoyer_all_to_all(), Viscosite_turbulente_multiple::eps(), Parser_Eval::eval_fct(), Moyenne_volumique::eval_filtre(), Matrix_tools::extend_matrix_stencil(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), ExtrudeBord::extruder_bord(), Extruder::extruder_hexa(), Zone_VF::face_virt_pe_num(), Faces_builder::faces_element_reference(), Discretisation_tools::faces_to_cells(), Zone_PolyMAC_P0::fgrad(), Champ_P1NC_implementation::filtrer_H1(), Champ_P1NC_implementation::filtrer_resu(), find_joint_faces(), find_matching_coordinates(), Neumann::flux_impose(), Sortie_libre_pression_imposee_QC::flux_impose(), Neumann_paroi::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Sortie_libre_Text_H_ext::flux_impose(), Champ_implementation_P1::form_function(), Champ_implementation_Q1::form_function(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Champ_Generique_Transformation::get_champ(), Champ_Post_Operateur_Eqn::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_front_recyclage::get_coord_faces(), Champ_Generique_refChamp::get_dimension(), Champ_Generique_refChamp::get_localisation(), Polyedre::get_nb_som_elem_max(), Polygone::get_nb_som_elem_max(), Matrice_Bloc::get_stencil(), Matrice_Dense::get_stencil(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Base::get_stencil_size(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Domaine::getBoundingBox(), Ch_front_input::getTemplate(), Champ_input_P0::getTemplate(), Ch_front_input_P1::getTemplate(), Champ_front_instationnaire_base::Gpoint(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), Champ_Q1_EF::gradient(), Champ_Q1NC::gradient(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Echange_impose_base::h_imp(), histogramme_angle(), Zone_Cl_EF::imposer_cond_lim(), Zone_Cl_VEFP1B::imposer_cond_lim(), Zone_Cl_EF::imposer_symetrie(), Zone_Cl_EF::imposer_symetrie_matrice_secmem(), Zone_Cl_EF::imposer_symetrie_partiellement(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), Op_Div_PolyMAC::impr(), Op_Div_PolyMAC_P0::impr(), T_It_VDF_Elem< _TYPE_ >::impr(), T_It_VDF_Face< _TYPE_ >::impr(), Op_Div_VEF_Elem::impr(), Zone::indice_elements(), Postraitement::init(), Champ_Elem_PolyMAC::init_auxiliary_variables(), Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Zone_Poly_base::init_equiv(), Zone::init_faces_virt_bord(), Champ_implementation_P1::init_from_file(), Echange_contact_PolyMAC_P0::init_fs_dist(), Op_Diff_PolyMAC_P0_Elem::init_som_ext(), Zone_PolyMAC_P0::init_stencils(), Champ_Face_PolyMAC_P0::init_ve2(), Sonde::initialiser(), Loi_Etat_GP_base::initialiser(), Loi_Etat_GR_base::initialiser(), DomaineCutter::initialiser(), Traduction_Indice_Global_Local::initialiser(), Sonde_Int::initialiser(), Ch_front_input_uniforme::initialiser(), Ch_front_input_P1::initialiser(), Champ_front_var::initialiser(), Champ_front_recyclage::initialiser(), Loi_Etat_GR_base::initialiser_inco_ch(), Navier_Stokes_std::initTimeStep(), Champ_Face_PolyMAC::interp_ve(), Integrer_champ_med::interpreter(), Moyenne_volumique::interpreter(), Decouper_multi::interpreter(), MaillerParallel::interpreter(), Raffiner_isotrope_parallele::interpreter(), latatoother::interpreter(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extruder_en3::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), VerifierCoin::interpreter_(), Corriger_frontiere_periodique::interpreter_(), inverser_par_diagonale(), Matrix_tools::is_diagonal_stencil(), Matrix_tools::is_normalized_stencil(), Matrix_tools::is_normalized_symmetric_stencil(), Matrix_tools::is_null_stencil(), Viscosite_turbulente_multiple::k_over_eps(), kersol(), largest_angle(), Postraitement_lata::lire_champs(), Terme_Source_Acceleration::lire_data(), Scatter::lire_domaine(), Champ_front_recyclage::lire_fichier_format1(), lire_special(), Zone_PolyMAC::M1(), Zone_PolyMAC::M2(), Zone_VF::marquer_faces_double_contrib(), meme_point(), Zones::merge(), Chimie::mettre_a_jour(), Champ_front_calc_interne::mettre_a_jour(), Champ_Front_Fonction::mettre_a_jour(), Champ_Fonc_Tabule_Morceaux::mettre_a_jour(), TRUSTChamp_Morceaux_generique< _TYPE_ >::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Op_Diff_Turbulent_PolyMAC_P0_Face::mettre_a_jour(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_VDF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Sonde::mettre_a_jour_bords(), TRUSTChamp_Don_generique< _TYPE_ >::mettre_a_jour_positions(), Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite(), Op_Conv_EF_VEF_P1NC_Stab::mettre_a_jour_pour_periodicite(), Convection_Diffusion_Temperature::mise_en_place_zone_fantome(), modif_matrice_pour_periodique_apres_contribuer(), modif_matrice_pour_periodique_avant_contribuer(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), modifieP1P1neumann(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Assembleur_P_VEFPreP1B::modifier_matrice(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_nu(), Op_EF_base::modifier_pour_Cl(), EOS_Tools_VDF::moyenne_vol(), multiplier_diviser_rho(), Zone::nb_aretes(), Matrice_Dense::nb_colonnes(), Zone::nb_elem(), Faces::nb_faces(), Zone_VF::nb_faces(), Matrice_Dense::nb_lignes(), Domaine::nb_som(), Zone_VF::nb_som_face(), Faces::nb_som_faces(), Champ_Don_base::nb_valeurs_nodales(), Champ_Inc_base::nb_valeurs_nodales(), NettoieNoeuds::nettoie(), Discretisation_tools::nodes_to_cells(), Polyedre_poly::normale(), Zone_VF::numero_face_local(), operation01(), operation11(), Polynome::operator()(), OrienteFacesBord::oriente_faces_bord(), Zone_PolyMAC::orthocentrer(), Sonde::ouvrir_fichier(), Sonde_Int::ouvrir_fichier(), parcourir_epaisseurs_elements(), Convection_Diffusion_Temperature::penalisation_L2(), Polyedriser::polyedriser(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), Sonde::postraiter(), Sonde_Int::postraiter(), Postraitement::postraiter_champs(), Format_Post_base::postraiter_debug_valeurs_un_instant(), Postraitement::postraiter_tableau(), prod(), projette(), Raffiner_anisotrope::Raffiner_anisotrope_(), OctreeRoot::rang_arete(), OctreeRoot::rang_elem(), OctreeRoot::rang_elem_depuis(), OctreeRoot::rang_sommet(), Champ_input_P0::readOn(), Domaine::readOn(), Pave::readOn(), Champ_Fonc_MED::readOn(), Loi_Etat_rhoT_GR_QC::readOn(), Remove_elem::recreer_faces(), Raffiner_Simplexes::refine_domain(), Remove_elem::Remove_elem_(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_P0_VDF::remplir_coord_noeuds(), Champ_Face_implementation::remplir_coord_noeuds(), Champ_P1NC_implementation::remplir_coord_noeuds(), Champ_Q1NC_impl::remplir_coord_noeuds(), remplir_coordsommets_sous_domaine(), Remove_elem::remplir_liste(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), Ensemble_Lagrange_base::remplir_sommets_tmp(), Loi_Etat_GR_base::remplir_T(), Champ_front_MED::remplir_tab(), Zone_Cl_EF::remplir_type_elem_Cl(), Frontiere::renum(), Zone::renum(), Reordonner_faces_periodiques::renum_som_perio(), reorder_vertices(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Scatter::reordonner_faces_de_joint(), Reordonner_faces_periodiques::reordonner_faces_periodiques(), reordonner_vdf(), Reorienter_tetraedres::Reorienter(), Reorienter_triangles::Reorienter(), Traitement_particulier_NS_canal::reprendre_stat(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl(), Traitement_particulier_NS_canal::sauver_stat_canal(), search_connex_components_local(), Octree_Int::search_elements(), Octree_Int::search_elements_box(), Octree_Double::search_nodes_close_to(), Champ_input_P0::setValue(), Champ_Input_Proto::setValueOnTab(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), Echange_impose_base::T_ext(), Echange_externe_impose_H::T_ext(), tableau_trier_retirer_doublons(), Eval_Dift_VDF_const_Face::tau_tan_impl(), Eval_Dift_VDF_var_Face::tau_tan_impl(), Op_Conv_EF_VEF_P1NC_Stab::test(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), Operateur_base::tester_contribuer_a_avec(), Champ_P1iP1B_implementation::trace(), Champ_Face_implementation::trace(), Champ_Elem_PolyMAC::trace(), Raccord_distant_homogene::trace_elem_distant(), Frontiere::trace_elem_local(), Raccord_distant_homogene::trace_face_distant(), Frontiere::trace_face_local(), Frontiere::trace_som_local(), trait_part_calculer_ec_faces(), traite_bord(), Moyenne_volumique::traiter_champs(), Transformer::transformer(), transp(), Convection_Diffusion_Temperature::transport_ibc(), tri_lexicographique_tableau(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), trier_index_colonne_i(), Matrice_Sym::unsymmetrize_stencil(), Matrice_Sym::unsymmetrize_stencil_and_coefficients(), grad_Champ_Face_PolyMAC_P0::update_ge(), Champ_Face_PolyMAC_P0::update_ve(), Sortie_libre_Text_H_ext::val_ext(), Neumann_sortie_libre_Temp_H::val_ext(), Neumann_sortie_libre::val_ext(), Entree_fluide_temperature_imposee_H::val_imp(), Temperature_imposee_paroi_H::val_imp(), Entree_fluide_T_h_imposee::val_imp(), Dirichlet::val_imp_au_temps(), Frontiere_ouverte_rho_u_impose::val_imp_au_temps(), valeur(), Champ_implementation_P0::valeur_a_elem(), Ch_front_input_P1::valeur_au_temps_et_au_point(), Champ_Fonc_base::valeur_aux(), champ_init_canal_sinal::valeur_aux(), Init_par_partie::valeur_aux(), Tayl_Green::valeur_aux(), TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_(), Champ_base::valeur_aux_centres_de_gravite(), Champ_Fonc_Face::valeur_aux_compo(), Champ_base::valeur_aux_compo(), champ_init_canal_sinal::valeur_aux_compo(), Tayl_Green::valeur_aux_compo(), Champ_Inc_base::valeur_aux_compo(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems(), Champ_implementation_sommet_base::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC_P0::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_implementation_sommet_base::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Elem_PolyMAC::valeur_aux_faces(), Champ_base::valeur_aux_sommets(), Champ_base::valeur_aux_sommets_compo(), Champ_implementation_sommet_base::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_implementation_sommet_base::valeur_aux_sommets_impl(), Champ_implementation_Q1::value_interpolation(), NettoieNoeuds::verifie_noeuds(), Op_Diff_VEF_Anisotrope_Face::verifier(), Op_Diff_VEF_Face::verifier(), verifier(), Loi_horaire::verifier_derivee(), Zone_PolyMAC::W1(), Zone_PolyMAC::W2(), Format_Post_Lata::write_doubletab(), and Format_Post_Lata::write_inttab().
dimension_tot()
template<typename _TYPE_ > int TRUSTTab< _TYPE_ >::dimension_tot (int i) const inline
Definition at line 129 of file TRUSTTab.tpp.
{
  assert(i >= 0 && i < nb_dim_);
  return (i == 0) ? dimension_tot_0_ : dimensions_[i];
}
Referenced by Debog_Pb::add_renum_item(), Champ_Face_PolyMAC::affecter_(), Champ_Face_PolyMAC_P0::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Elem_PolyMAC::affecter_(), Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Op_Div_PolyMAC::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Solveur_Masse_base::ajouter_masse(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), SETS::assembler(), Source_PDF_EF::associer_pb(), Octree_Double::build_elements(), Octree_Double::build_nodes(), Ch_front_input::buildSommetsFaces(), Domaine::buildUFacesMesh(), Champ_P1NC::calcul_duidxj_paroi(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), calculer_centres_gravite(), Equation_base::calculer_champ_conserve(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Fluide_base::calculer_e_int(), Fluide_reel_base::calculer_energie_interne(), Milieu_composite::calculer_energie_interne(), Fluide_reel_base::calculer_enthalpie(), Milieu_composite::calculer_enthalpie(), calculer_inv_volume_special(), Fluide_reel_base::calculer_masse_volumique(), Milieu_composite::calculer_masse_volumique(), Fluide_base::calculer_nu(), Fluide_Weakly_Compressible::calculer_pression_hydro(), Fluide_Dilatable_base::calculer_pression_tot(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Fluide_reel_base::check_unknown_range(), Op_Correlation::completer(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Octree_Double::compute_origin_factors(), OctreeRoot::construire(), construire_connectivite_real_som_virtual_elem(), construire_connectivite_som_elem(), construire_elems_sous_domaine(), Scatter::construire_espace_virtuel_traduction(), corriger(), corriger_incr_alpha(), Solveur_Masse_base::corriger_solution(), Zone::creer_aretes(), Elem_geom_base::creer_faces_elem(), Fluide_base::creer_nu(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Solveur_Masse_base::dimensionner(), Masse_VDF_base::dimensionner_blocs(), Masse_PolyMAC_Elem::dimensionner_blocs(), Flux_interfacial_PolyMAC::dimensionner_blocs(), Zone_PolyMAC::discretiser(), Zone_VDF::discretiser(), disp_dt(), disp_it(), diviser_par_rho_np1_face(), echanger_tableau_aretes(), Format_Post_Lata::ecrire_domaine(), Viscosite_turbulente_multiple::eddy_viscosity(), Source_WC_Chaleur_VEF::elem_to_face(), Viscosite_turbulente_multiple::eps(), Source_WC_Chaleur_VDF::face_to_elem(), Discretisation_tools::faces_to_cells(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), Champ_Q1_EF::gradient(), Equation_base::Gradient_conjugue_diff_impl(), Zone_Cl_EF::imposer_symetrie(), Equation_base::imprime_residu(), Zone::init_faces_virt_bord(), init_parts(), Sonde::initialiser(), Echange_contact_VDF::initialiser(), Fluide_Weakly_Compressible::initialiser_pth(), QDM_Multiphase::initTimeStep(), Viscosite_turbulente_multiple::k_over_eps(), Zone_PolyMAC::M1(), Zone_PolyMAC::M2(), Op_EF_base::marque_elem(), Champ_Front_Fonction::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), modif_par_porosite_si_flag(), Zone::nb_aretes_tot(), Zone::nb_elem_tot(), Faces::nb_faces_tot(), Zone_VF::nb_faces_tot(), Domaine::nb_som_tot(), Discretisation_tools::nodes_to_cells(), parcourir_epaisseurs_elements(), Convection_Diffusion_Temperature::penalisation_L2(), Navier_Stokes_std::projeter(), Champ_input_P0::readOn(), Champ_Fonc_reprise::readOn(), Diametre_bulles_constant::readOn(), Polygone::rebuild_index(), Fluide_Weakly_Compressible::remplir_champ_pression_for_EOS(), Polyedre::remplir_Nodes_glob(), Op_Diff_VEF_base::remplir_nu(), Reordonner_faces_periodiques::renum_som_perio(), search_connex_components_local(), Equation_base::set_residuals(), Champ_Input_Proto::setValueOnTab(), Eval_Dift_VDF_const_Face::tau_tan_impl(), Eval_Dift_VDF_var_Face::tau_tan_impl(), Champ_Elem_PolyMAC::trace(), tri_lexicographique_tableau_indirect(), SETS::unknown_positivation(), Schema_Temps_base::update_critere_statio(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), QDM_Multiphase::update_y_plus(), Champ_implementation_P0::valeur_a_elem(), Champ_implementation_P0::valeur_a_elem_compo(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux(), Champ_Inc_base::valeur_aux(), Champ_base::valeur_aux_bords(), Champ_Inc_base::valeur_aux_bords(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_implementation_sommet_base::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC_P0::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Elem_PolyMAC::valeur_aux_faces(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_implementation_sommet_base::valeur_aux_sommets_impl(), Champ_implementation_P1::value_interpolation(), Champ_implementation_Q1::value_interpolation(), Vecteur3::Vecteur3(), verifier(), Zone_PolyMAC::W1(), Zone_PolyMAC::W2(), and PolyMAC_discretisation::y_plus().
duplique()
template<typename _TYPE_ > int TRUSTTab< _TYPE_ >::duplique () const inline override protected virtual
Reimplemented from TRUSTArray< _TYPE_ >.
Reimplemented in TRUSTTrav< _TYPE_ >.
Definition at line 30 of file TRUSTTab.h.
  {
    TRUSTTab* xxx = new  TRUSTTab(*this);
    if(!xxx)
      {
        Cerr << "Not enough memory " << finl;
        Process::exit();
      }
    return xxx->numero();
  }
References Cerr, Process::exit(), finl, Objet_U::numero(), and TRUSTTab< _TYPE_ >::TRUSTTab().
ecrit()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::ecrit (Sortie & os) const inline override virtual
Reimplemented from TRUSTVect< _TYPE_ >.
Definition at line 529 of file TRUSTTab.tpp.
{
  os << nb_dim_ << finl;
  if (nb_dim_ > 0) os.put(dimensions_, nb_dim_, nb_dim_);
  TRUSTArray<int> tmp(nb_dim_);
  for (int i = 0; i < nb_dim_; i++) tmp[i] = dimension_tot(i);
  os << tmp;
  TRUSTVect<_TYPE_>::ecrit(os);
}
References TRUSTVect< _TYPE_ >::ecrit(), finl, and Sortie::put().
Referenced by Faces::ecrit(), Zone_EF::ecrit(), Zone_Poly_base::ecrit(), Zone_VEF::ecrit(), Sous_zone_VF::printOn(), Zone_VF::printOn(), Zone_VDF::printOn(), Champ_Fonc_base::sauvegarder(), Champ_Inc_base::sauvegarder(), and verifier().
init_dimensions()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::init_dimensions (int * tab) inline private
Definition at line 266 of file TRUSTTab.h.
  {
#ifndef NDEBUG
    for (int i = 0; i < MAXDIM_TAB; i++) tab[i] = -1;
#endif
  }
References TRUSTTab< _TYPE_ >::MAXDIM_TAB.
Referenced by TRUSTTab< _TYPE_ >::TRUSTTab().
inverse_LU()
template<typename _TYPE_ > int TRUSTTab< _TYPE_ >::inverse_LU (const TRUSTArray< double > & b, TRUSTArray< double > & solution) inline
Definition at line 634 of file TRUSTTab.tpp.
{
  int n = b.size_array();
  TRUSTArray<int> index(n);
  TRUSTTab<double> lu_dec(n,n);
  int cvg = (*this).decomp_LU(n,index,lu_dec);
  if(cvg == 1) lu_dec.resoud_LU(n,index,b,solution);
  return cvg;
}
References TRUSTTab< _TYPE_ >::resoud_LU(), and TRUSTArray< _TYPE_ >::size_array().
jump()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::jump (Entree & is) inline override virtual
Reimplemented from TRUSTVect< _TYPE_ >.
Definition at line 540 of file TRUSTTab.tpp.
{
  TRUSTTab<_TYPE_>::lit(is, 0 /* Do not resize&read the array */);
}
References TRUSTTab< _TYPE_ >::lit().
Referenced by Champ_Generique_Statistiques_base::lire_bidon(), Champ_Fonc_base::reprendre(), Champ_Inc_base::reprendre(), Postraitement::reprendre(), and Operateurs_Statistique_tps::reprendre().
lit()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::lit (Entree & is, int resize_and_read = 1) inline override virtual
Reimplemented from TRUSTVect< _TYPE_ >.
Definition at line 549 of file TRUSTTab.tpp.
{
  TRUSTArray<int> tmp;
  is >> tmp;
  int ok = 1;
  if (tmp.size_array() != nb_dim_) ok = 0;
  if (ok)
    {
      if (TRUSTVect<_TYPE_>::size_reelle_ok() && dimension(0) != tmp[0]) ok = 0;
      for (int i = 1; i < nb_dim_; i++)
        if (dimension(i) != tmp[i]) ok = 0;
    }
  is >> tmp;
  if (ok && tmp.size_array() != nb_dim_) ok = 0;
  if (ok)
    for (int i = 0; i < nb_dim_; i++)
      if (dimension_tot(i) != tmp[i]) ok = 0;
// Autorisation ancien format des champs scalaire 183:
  if (tmp.size_array()==1 && nb_dim_==2 && dimension(1)==1 && dimension_tot(0) == tmp[0]) ok = 1;
  if (resize_and_read)
    {
      if (TRUSTVect<_TYPE_>::size_array() == 0 && (!TRUSTVect<_TYPE_>::get_md_vector().non_nul())) resize(tmp, Array_base::NOCOPY_NOINIT);
      else if (!ok)
        {
// Si on cherche a relire un tableau de taille inconnue, le tableau doit etre reset() a l'entree. On n'aura pas la structure parallele du tableau !
          Cerr << "Error in DoubleTab::lit: array has wrong dimensions" << finl;
          Process::exit();
        }
    }
  TRUSTVect<_TYPE_>::lit(is,resize_and_read);
}
References Cerr, Process::exit(), finl, TRUSTVect< _TYPE_ >::lit(), Array_base::NOCOPY_NOINIT, and TRUSTArray< _TYPE_ >::size_array().
Referenced by TRUSTTab< _TYPE_ >::jump(), Faces::lit(), Sous_zone_VF::readOn(), Zone_VF::readOn(), Zone_VDF::readOn(), Champ_Fonc_base::reprendre(), and Champ_Inc_base::reprendre().
max_du_u()
template<typename _TYPE_ > double TRUSTTab< _TYPE_ >::max_du_u (const TRUSTTab< double > & u) inline
Definition at line 743 of file TRUSTTab.tpp.
{
  assert(TRUSTVect<_TYPE_>::size_array() == u.size_array());
  const double *du_ptr = TRUSTVect<_TYPE_>::addr();
  const double *u_ptr = u.addr();
  const double epsilon = 1.e-8;
  double res = 0.;
  for (int n = TRUSTVect<_TYPE_>::size_array(); n; n--)
    {
      double a = std::fabs(*du_ptr), b = std::fabs(*u_ptr), c = a / (b + epsilon);
      if (b > 1.e-2 && c > res) res = c;
      du_ptr++;
      u_ptr++;
    }
  return res;
}
References TRUSTArray< _TYPE_ >::addr(), and TRUSTArray< _TYPE_ >::size_array().
nb_dim()
template<typename _TYPE_ > int TRUSTTab< _TYPE_ >::nb_dim () const inline
Definition at line 201 of file TRUSTTab.h.
{ return nb_dim_; }
References TRUSTTab< _TYPE_ >::nb_dim_.
Referenced by Frontiere::add(), Champ_Face::affecter(), T_It_VDF_Elem< _TYPE_ >::ajouter(), T_It_VDF_Face< _TYPE_ >::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), T_It_Sou_VDF_Elem< _TYPE_ >::ajouter(), T_It_Sou_VDF_Face< _TYPE_ >::ajouter(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution(), T_It_VDF_Face< _TYPE_ >::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_vitesse(), Op_Conv_Muscl_New_VEF_Face::ajouter_diffusion(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Matrice_Morse::ajouter_multTab_(), Matrice_Morse_Sym::ajouter_multTab_(), Matrice_Diagonale::ajouter_multTab_(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Solveur_Masse_EF::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Simpler_Base::assembler_matrice_pression_implicite(), Op_Diff_VEF_base::associer(), build_triofield(), Champ_front_contact_VEF::calcul_grads_locaux(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Dift_Stab_VEF_Face::calculer_coefficients(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Simple::calculer_correction_en_vitesse(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), calculer_gradientP1NC(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Dift_Stab_VEF_Face::calculer_min(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Operateur_base::calculer_pour_post(), Eval_Puiss_Th_PolyMAC_Elem::calculer_terme_source(), Eval_Source_C_PolyMAC_Elem::calculer_terme_source(), Eval_Puiss_Th_QC_VEF_Face::calculer_terme_source_non_standard(), Eval_Puiss_Th_QC_EF::calculer_terme_source_standard(), Eval_Puiss_Th_QC_VEF_Face::calculer_terme_source_standard(), Discretisation_tools::cells_to_faces(), Scatter::Chercher_Correspondance(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), Op_Correlation::completer(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), T_It_VDF_Elem< _TYPE_ >::contribuer_au_second_membre(), T_It_VDF_Face< _TYPE_ >::contribuer_au_second_membre(), Matrice_Morse::dimensionner(), Roue::dimensionner(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), disp_dt(), disp_it(), diviser_par_rho_np1_face(), Format_Post_Lata_V1::ecrire_champ_lata_V1(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_XYZ::ecrire_champ_xyz(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Debog_Pb::ecrire_gen(), ecrit(), EcritureLectureSpecial::ecriture_special(), Parser_Eval::eval_fct(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), Ch_front_input::getTemplate(), Ch_front_input_P1::getTemplate(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), init_parts(), Navier_Stokes_std::initTimeStep(), inverser_par_diagonale(), lire_special(), Champ_front_calc_interne::mettre_a_jour(), Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite(), Op_Conv_EF_VEF_P1NC_Stab::mettre_a_jour_pour_periodicite(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_VEF_Face::modifier_flux(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_nu(), Zone_EF::modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem(), Zone_Poly_base::nu_dot(), Operateur_base::ouvrir_fichier(), Format_Post_base::postraiter_debug_valeurs_un_instant(), Champ_Fonc_reprise::readOn(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Champ_Elem_PolyMAC::trace(), Raccord_distant_homogene::trace_face_distant(), QDM_Multiphase::update_y_plus(), Frontiere_ouverte_rho_u_impose::val_imp_au_temps(), valeur(), Champ_implementation_P0::valeur_a_elem(), TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_(), Champ_som_lu::valeur_aux_elems(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Q1NC_impl::valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC_P0::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_elems_(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Elem_PolyMAC::valeur_aux_faces(), Champ_implementation_sommet_base::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_implementation_Q1::value_interpolation(), Format_Post_Lata::write_doubletab(), and Format_Post_Lata::write_inttab().
operator()() [1/10]
template<typename _TYPE_ > _TYPE_ & TRUSTTab< _TYPE_ >::operator() (const TRUSTArray< int > & indice) inline
Definition at line 476 of file TRUSTTab.tpp.
{
  assert(indice.size_array() == nb_dim_);
  verifie_MAXDIM_TAB();
  switch(nb_dim_)
    {
    case 1:
      return operator()(indice[0]);
    case 2:
      return operator()(indice[0], indice[1]);
    case 3:
      return operator()(indice[0], indice[1], indice[2]);
    default:
      return operator()(indice[0], indice[1], indice[2], indice[3]);
    }
}
References TRUSTArray< _TYPE_ >::size_array().
operator()() [2/10]
template<typename _TYPE_ > _TYPE_ TRUSTTab< _TYPE_ >::operator() (const TRUSTArray< int > & indice) const inline
Definition at line 494 of file TRUSTTab.tpp.
{
  assert(indice.size_array() == nb_dim_);
  verifie_MAXDIM_TAB();
  switch(nb_dim_)
    {
    case 1:
      return operator()(indice[0]);
    case 2:
      return operator()(indice[0], indice[1]);
    case 3:
      return operator()(indice[0], indice[1], indice[2]);
    default:
      return operator()(indice[0], indice[1], indice[2], indice[3]);
    }
}
References TRUSTArray< _TYPE_ >::size_array().
operator()() [3/10]
template<typename _TYPE_ > _TYPE_ & TRUSTTab< _TYPE_ >::operator() (int i) inline
Definition at line 38 of file TRUSTTab.tpp.
{
  assert(nb_dim_ == 1 || (nb_dim_ == 2 && dimensions_[1] == 1));
  assert(i >= 0 && i < dimension_tot_0_);
  return TRUSTVect<_TYPE_>::operator[](i);
}
References TRUSTArray< _TYPE_ >::operator[]().
operator()() [4/10]
template<typename _TYPE_ > const _TYPE_ & TRUSTTab< _TYPE_ >::operator() (int i) const inline
Definition at line 46 of file TRUSTTab.tpp.
{
  assert(nb_dim_ == 1 || (nb_dim_ == 2 && dimensions_[1] == 1));
  assert(i >= 0 && i < dimension_tot_0_);
  return TRUSTVect<_TYPE_>::operator[](i);
}
References TRUSTArray< _TYPE_ >::operator[]().
operator()() [5/10]
template<typename _TYPE_ > _TYPE_ & TRUSTTab< _TYPE_ >::operator() (int i1, int i2) inline
Definition at line 55 of file TRUSTTab.tpp.
{
  assert(nb_dim_ == 2);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  return TRUSTVect<_TYPE_>::operator[](i1*dimensions_[1]+i2);
}
References TRUSTArray< _TYPE_ >::operator[]().
operator()() [6/10]
template<typename _TYPE_ > const _TYPE_ & TRUSTTab< _TYPE_ >::operator() (int i1, int i2) const inline
Definition at line 64 of file TRUSTTab.tpp.
{
  assert(nb_dim_ == 2);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  return TRUSTVect<_TYPE_>::operator[](i1*dimensions_[1]+i2);
}
References TRUSTArray< _TYPE_ >::operator[]().
operator()() [7/10]
template<typename _TYPE_ > _TYPE_ & TRUSTTab< _TYPE_ >::operator() (int i1, int i2, int i3) inline
Definition at line 73 of file TRUSTTab.tpp.
{
  assert(nb_dim_ == 3);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  assert(i3 >= 0 && i3 < dimensions_[2]);
  return TRUSTVect<_TYPE_>::operator[]((i1*dimensions_[1]+i2)*dimensions_[2]+i3);
}
References TRUSTArray< _TYPE_ >::operator[]().
operator()() [8/10]
template<typename _TYPE_ > const _TYPE_ & TRUSTTab< _TYPE_ >::operator() (int i1, int i2, int i3) const inline
Definition at line 83 of file TRUSTTab.tpp.
{
  assert(nb_dim_ == 3);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  assert(i3 >= 0 && i3 < dimensions_[2]);
  return TRUSTVect<_TYPE_>::operator[]((i1*dimensions_[1]+i2)*dimensions_[2]+i3);
}
References TRUSTArray< _TYPE_ >::operator[]().
operator()() [9/10]
template<typename _TYPE_ > _TYPE_ & TRUSTTab< _TYPE_ >::operator() (int i1, int i2, int i3, int i4) inline
Definition at line 93 of file TRUSTTab.tpp.
{
  assert(nb_dim_ == 4);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  assert(i3 >= 0 && i3 < dimensions_[2]);
  assert(i4 >= 0 && i4 < dimensions_[3]);
  return TRUSTVect<_TYPE_>::operator[](((i1*dimensions_[1]+i2)*dimensions_[2]+i3)*dimensions_[3]+i4);
}
References TRUSTArray< _TYPE_ >::operator[]().
operator()() [10/10]
template<typename _TYPE_ > const _TYPE_ & TRUSTTab< _TYPE_ >::operator() (int i1, int i2, int i3, int i4) const inline
Definition at line 104 of file TRUSTTab.tpp.
{
  assert(nb_dim_ == 4);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  assert(i3 >= 0 && i3 < dimensions_[2]);
  assert(i4 >= 0 && i4 < dimensions_[3]);
  return TRUSTVect<_TYPE_>::operator[](((i1*dimensions_[1]+i2)*dimensions_[2]+i3)*dimensions_[3]+i4);
}
References TRUSTArray< _TYPE_ >::operator[]().
operator=() [1/3]
template<typename _TYPE_ > TRUSTTab< _TYPE_ > & TRUSTTab< _TYPE_ >::operator= (_TYPE_ d) inline
Definition at line 456 of file TRUSTTab.tpp.
{
  TRUSTVect<_TYPE_>::operator=(d);
  return *this;
}
References TRUSTVect< _TYPE_ >::operator=().
operator=() [2/3]
template<typename _TYPE_ > TRUSTTab< _TYPE_ > & TRUSTTab< _TYPE_ >::operator= (const TRUSTTab< _TYPE_ > & src) inline
Definition at line 419 of file TRUSTTab.tpp.
{
  copy(src);
  return *this;
}
Referenced by TRUSTTabFT< _TYPE_ >::operator=(), TRUSTTrav< _TYPE_ >::operator=(), TRUSTTabFT< _TYPE_ >::TRUSTTabFT(), and TRUSTTrav< _TYPE_ >::TRUSTTrav().
operator=() [3/3]
template<typename _TYPE_ > TRUSTTab< _TYPE_ > & TRUSTTab< _TYPE_ >::operator= (const TRUSTVect< _TYPE_ > & src) inline
Definition at line 428 of file TRUSTTab.tpp.
{
  assert(std::string(typeid(src).name()).find("TRUSTVect") != std::string::npos);
  TRUSTVect<_TYPE_>::copy_(src);
// Idem que dans ref(TRUSTVect<_TYPE_>) pour le nombre de dimensions du tableau cree
  const int l = src.line_size();
  if (l == 1) nb_dim_ = 1;
  else
    {
      nb_dim_ = 2;
      dimensions_[1] = l;
    }
  if (src.size_reelle_ok())
    {
      int sz = src.size_reelle();
      dimensions_[0] = sz / l;
      assert(sz % l == 0);
    }
  else dimensions_[0] = -1;
  dimension_tot_0_ = TRUSTVect<_TYPE_>::size_array() / l;
  assert(verifie_LINE_SIZE());
  return *this;
}
References TRUSTVect< _TYPE_ >::copy_(), TRUSTVect< _TYPE_ >::line_size(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_reelle(), and TRUSTVect< _TYPE_ >::size_reelle_ok().
operator[]() [1/2]
template<typename _TYPE_ > _TYPE_ & TRUSTTab< _TYPE_ >::operator[] (int i) inline
Definition at line 21 of file TRUSTTab.tpp.
{
  assert(nb_dim_ == 1 || (nb_dim_ == 2 && dimensions_[1] == 1));
  assert(i >= 0 && i < dimension_tot_0_);
  return TRUSTVect<_TYPE_>::operator[](i);
}
References TRUSTArray< _TYPE_ >::operator[]().
operator[]() [2/2]
template<typename _TYPE_ > const _TYPE_ & TRUSTTab< _TYPE_ >::operator[] (int i) const inline
Definition at line 30 of file TRUSTTab.tpp.
{
  assert(nb_dim_ == 1 || (nb_dim_ == 2 && dimensions_[1] == 1));
  assert(i >= 0 && i < dimension_tot_0_);
  return TRUSTVect<_TYPE_>::operator[](i);
}
References TRUSTArray< _TYPE_ >::operator[]().
printOn()
template<typename _TYPE_ > Sortie & TRUSTTab< _TYPE_ >::printOn (Sortie & os) const inline override protected virtual
ecriture d'un tableau sequentiel (idem que TRUSTVect::printOn() on ne sait pas quoi faire de pertinent pour un tableau distribue).
Reimplemented from TRUSTArray< _TYPE_ >.
Reimplemented in TRUSTTrav< _TYPE_ >.
Definition at line 42 of file TRUSTTab.h.
  {
    assert(verifie_LINE_SIZE());
    if (TRUSTVect<_TYPE_>::nproc() > 1 && TRUSTVect<_TYPE_>::get_md_vector().non_nul())
      {
        Cerr << "Error in TRUSTTab::printOn: try to print a parallel vector" << finl;
        Process::exit();
      }
    os << nb_dim_ << finl;
    assert(dimensions_[0] == dimension_tot_0_);
    if (nb_dim_ > 0) os.put(dimensions_, nb_dim_, nb_dim_);
    const int sz = TRUSTVect<_TYPE_>::size_array();
    os << sz << finl;
    const int l_size = TRUSTVect<_TYPE_>::line_size();
    const _TYPE_ *data = TRUSTVect<_TYPE_>::addr();
    if (sz > 0)  os.put(data, sz, l_size);
    return os;
  }
References TRUSTArray< _TYPE_ >::addr(), Cerr, TRUSTTab< _TYPE_ >::dimension_tot_0_, TRUSTTab< _TYPE_ >::dimensions_, Process::exit(), finl, TRUSTVect< _TYPE_ >::line_size(), TRUSTTab< _TYPE_ >::nb_dim_, Sortie::put(), TRUSTArray< _TYPE_ >::size_array(), and TRUSTTab< _TYPE_ >::verifie_LINE_SIZE().
Referenced by TRUSTTrav< _TYPE_ >::printOn().
readOn()
template<typename _TYPE_ > Entree & TRUSTTab< _TYPE_ >::readOn (Entree & is) inline override protected virtual
lecture d'un tableau sequentiel
Reimplemented from TRUSTArray< _TYPE_ >.
Reimplemented in TRUSTTrav< _TYPE_ >.
Definition at line 65 of file TRUSTTab.h.
  {
    if (TRUSTVect<_TYPE_>::get_md_vector().non_nul())
      {
// Que veut-on faire si on lit dans un vecteur ayant deja une structure parallele ?
        Cerr << "Error in TRUSTTab::readOn: vector has a parallel structure" << finl;
        Process::exit();
      }
    is >> nb_dim_;
    if (nb_dim_ < 1 || nb_dim_ > MAXDIM_TAB)
      {
        Cerr << "Error in TRUSTTab::readOn: wrong nb_dim_ = " << nb_dim_ << finl;
        Process::exit();
      }
    is.get(dimensions_, nb_dim_);
    if (dimensions_[0] < 0)
      {
        Cerr << "Error in TRUSTTab::readOn: wrong dimension(0) = " << dimensions_[0] << finl;
        Process::exit();
      }
    int l_size = 1;
    for (int i = 1; i < nb_dim_; i++)
      {
        if (dimensions_[i] < 0)
          {
            Cerr << "Error in TRUSTTab::readOn: wrong dimension(" << i << ") = " << dimensions_[i] << finl;
            Process::exit();
          }
        l_size *= dimensions_[i];
      }
    dimension_tot_0_ = dimensions_[0];
    TRUSTVect<_TYPE_>::readOn(is);
    TRUSTVect<_TYPE_>::set_line_size_(l_size);
    if (dimension_tot_0_ * l_size != TRUSTVect<_TYPE_>::size_array())
      {
        Cerr << "Error in TRUSTTab::readOn: wrong size_array " << TRUSTVect<_TYPE_>::size_array() << ", expected " << dimension_tot_0_ * l_size << finl;
        Process::exit();
      }
    assert(verifie_LINE_SIZE());
    return is;
  }
References Cerr, TRUSTTab< _TYPE_ >::dimension_tot_0_, TRUSTTab< _TYPE_ >::dimensions_, Process::exit(), finl, Entree::get(), TRUSTTab< _TYPE_ >::MAXDIM_TAB, TRUSTTab< _TYPE_ >::nb_dim_, TRUSTVect< _TYPE_ >::readOn(), TRUSTVect< _TYPE_ >::set_line_size_(), TRUSTArray< _TYPE_ >::size_array(), and TRUSTTab< _TYPE_ >::verifie_LINE_SIZE().
Referenced by TRUSTTrav< _TYPE_ >::readOn().
ref() [1/2]
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::ref (const TRUSTTab< _TYPE_ > & src) inline virtual
Definition at line 229 of file TRUSTTab.tpp.
{
  TRUSTVect<_TYPE_>::ref(src);
  nb_dim_ = src.nb_dim_;
  for (int i = 0; i < MAXDIM_TAB; i++) dimensions_[i] = src.dimensions_[i];
  dimension_tot_0_ = src.dimension_tot_0_;
  assert(verifie_LINE_SIZE());
}
Referenced by Op_Conv_VEF_Face::ajouter(), Solveur_Masse_base::appliquer(), Eval_Diff_VDF_Multi_inco_var::associer(), Eval_Diff_VDF_var_aniso::associer(), Eval_Conv_VDF::associer(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Op_Grad_VDF_Face_base::associer(), Eval_Puiss_Th_EF::associer_champs(), Eval_Puiss_Th_PolyMAC_Elem::associer_champs(), Eval_Source_C_PolyMAC_Elem::associer_champs(), Eval_Puiss_Th_VDF_Elem::associer_champs(), Eval_Source_C_VDF_Elem::associer_champs(), Eval_Puiss_Th_VEF_Face::associer_champs(), Eval_Source_C_VEF_Face::associer_champs(), Eval_Echange_Himp_VDF_Elem::associer_champs(), Eval_Puiss_Th_QC_EF::associer_puissance(), Eval_Puiss_Th_QC_VEF_Face::associer_puissance(), Eval_Puiss_Th_QC_VDF_Elem::associer_puissance(), Force_Centrifuge_VDF_Face_Axi::associer_zones(), Evaluateur_VDF::associer_zones(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Eval_Puiss_Th_QC_VEF_Face::completer(), Eval_Puiss_Th_VEF_Face::completer(), Eval_Source_C_VEF_Face::completer(), Evaluateur_Source_VEF_Face::completer(), T_It_VDF_Elem< _TYPE_ >::completer_(), Extruder_en3::construire_bord_lateral(), Extruder_en3::construire_bords(), Remove_elem::creer_faces(), decoupe(), Tetraedriser_homogene_compact::decoupe(), Tetraedriser_homogene_fin::decoupe(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Discret_Thyd::diametre_hydraulique_elem(), Discret_Thyd::diametre_hydraulique_face(), Zone_VF::discretiser(), Eval_Conv_VDF::Eval_Conv_VDF(), Evaluateur_Source_VEF_Face::Evaluateur_Source_VEF_Face(), Evaluateur_VDF::Evaluateur_VDF(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), Extruder::extruder_hexa(), Champ_P1NC_implementation::filtrer_L2(), Zone_VDF::genere_aretes(), Equation_base::Gradient_conjugue_diff_impl(), init_parts(), Loi_Etat_GR_base::initialiser(), Eval_Conv_VDF::mettre_a_jour(), Eval_Diff_VDF_var_aniso::mettre_a_jour(), Eval_Dift_VDF_const_Face::mettre_a_jour(), Eval_Dift_VDF_var_Face::mettre_a_jour(), Eval_Echange_Himp_VDF_Elem::mettre_a_jour(), Op_Dift_EF_base::mettre_a_jour(), Op_Dift_VEF_base::mettre_a_jour(), Op_Dift_VDF_Face_Axi_base::mettre_a_jour(), modif_par_porosite_si_flag(), OrienteFacesBord::oriente_faces_bord(), Discret_Thyd::porosite_volumique(), Raffiner_anisotrope::Raffiner_anisotrope_(), Remove_elem::recreer_faces(), Remove_elem::Remove_elem_(), Table::remplir(), Champ_P0_VDF::remplir_coord_noeuds(), Champ_Face_implementation::remplir_coord_noeuds(), Champ_P1NC_implementation::remplir_coord_noeuds(), Champ_Q1NC_impl::remplir_coord_noeuds(), T_It_VDF_Elem< _TYPE_ >::T_It_VDF_Elem(), T_It_VDF_Face< _TYPE_ >::T_It_VDF_Face(), Extruder::traiter_faces_dvt(), Extruder_en20::traiter_faces_dvt(), Extruder::traiter_faces_dvt_hexa(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), Refine_Mesh::update_boundary_faces(), Refine_Mesh::update_cells(), Refine_Mesh::update_connector_faces(), Refine_Mesh::update_internal_frontier_faces(), Refine_Mesh::update_nodes(), and Champ_Inc_base::valeur_aux_bords().
ref() [2/2]
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::ref (const TRUSTVect< _TYPE_ > & v) inline override virtual
Reimplemented from TRUSTVect< _TYPE_ >.
Definition at line 200 of file TRUSTTab.tpp.
{
  assert(std::string(typeid(v).name()).find("TRUSTVect") != std::string::npos);
  TRUSTVect<_TYPE_>::ref(v);
  const int l = v.line_size();
// Attention: En prenant la ref, on est oblige de conserver l'attribut line_size du Vect (sinon echange_espace_virtuel ne fonctionnera pas car
// on n'aura pas le bon facteur multiplicatif des items geometriques). Si on voulait creer un tableau monodimensionnel avec line_size > 1,
// le tableau devient invalide car on n'a plus line_size = produit des dimensions > 1.
// On peut le faire a condition de laisser tomber le md_vector_ en faisant  tab.ref_array(v) au lieu de  tab.ref(v)
  if (l == 1)  nb_dim_ = 1;
  else
    {
      nb_dim_ = 2;
      dimensions_[1] = l;
    }
  if (v.size_reelle_ok())
    {
      int sz = v.size_reelle();
      dimensions_[0] = sz / l;
    }
  else dimensions_[0] = -1;
  dimension_tot_0_ = TRUSTVect<_TYPE_>::size_array() / l;
  assert(verifie_LINE_SIZE());
}
ref_array()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::ref_array (TRUSTArray< _TYPE_ > & m, int start = 0, int size = -1) inline override virtual
Returns
TRUSTArray<TYPE>&
Signification: *this
< pas sz qui peut valoir -1
Reimplemented from TRUSTArray< _TYPE_ >.
Definition at line 253 of file TRUSTTab.tpp.
{
  TRUSTVect<_TYPE_>::ref_array(src, start, sz);
  assert(!TRUSTVect<_TYPE_>::get_md_vector().non_nul() && TRUSTVect<_TYPE_>::size_reelle() == TRUSTVect<_TYPE_>::size_array());
  nb_dim_ = 1;
  dimensions_[0] = dimension_tot_0_ = TRUSTVect<_TYPE_>::size_array(); //!< pas sz qui peut valoir -1
  assert(verifie_LINE_SIZE());
}
References TRUSTVect< _TYPE_ >::ref_array(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by init_parts(), Solv_Gen::solve(), and Debog_Pb::verifier_partie().
ref_data()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::ref_data (_TYPE_ * ptr, int size) inline override virtual
Returns
TRUSTArray<TYPE>&
Signification: *this
< Pour passer les tests si on resize a la meme taille
Reimplemented from TRUSTArray< _TYPE_ >.
Definition at line 240 of file TRUSTTab.tpp.
{
  TRUSTVect<_TYPE_>::ref_data(ptr, new_size);
  if (new_size<0) new_size=-new_size;
  assert(!TRUSTVect<_TYPE_>::get_md_vector().non_nul() && TRUSTVect<_TYPE_>::size_reelle() == TRUSTVect<_TYPE_>::size_array());
  nb_dim_ = 1;
  dimensions_[0] = dimension_tot_0_ = new_size;
  assert(verifie_LINE_SIZE());
}
References TRUSTVect< _TYPE_ >::ref_data().
ref_tab()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::ref_tab (TRUSTTab< _TYPE_ > & t, int start_line = 0, int nb_lines = -1) inline virtual
Definition at line 266 of file TRUSTTab.tpp.
{
  if (nb_lines < 0) nb_lines = t.dimension_tot_0_ - start_line;
  assert(start_line >= 0 && nb_lines >= 0 && start_line + nb_lines <= t.dimension_tot_0_);
  const int l_size = t.line_size();
  TRUSTVect<_TYPE_>::ref_array(t, start_line * l_size, nb_lines * l_size);
  assert(!TRUSTVect<_TYPE_>::get_md_vector().non_nul() && TRUSTVect<_TYPE_>::size_reelle() == TRUSTVect<_TYPE_>::size_array());
  TRUSTVect<_TYPE_>::set_line_size_(l_size);
  nb_dim_ = t.nb_dim_;
  dimension_tot_0_ = nb_lines;
  dimensions_[0] = nb_lines;
  for (int i = 1; i < MAXDIM_TAB; i++) dimensions_[i] = t.dimensions_[i];
  assert(verifie_LINE_SIZE());
}
References TRUSTTab< _TYPE_ >::dimension_tot_0_, TRUSTTab< _TYPE_ >::dimensions_, TRUSTVect< _TYPE_ >::line_size(), TRUSTTab< _TYPE_ >::nb_dim_, TRUSTVect< _TYPE_ >::ref_array(), and TRUSTVect< _TYPE_ >::set_line_size_().
Referenced by Champ_Inc_base::affecter_().
reset()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::reset inline override virtual
Reimplemented from TRUSTArray< _TYPE_ >.
Definition at line 283 of file TRUSTTab.tpp.
{
  nb_dim_ = 1;
  dimensions_[0] = 0;
  dimension_tot_0_ = 0;
  TRUSTVect<_TYPE_>::reset();
  assert(verifie_LINE_SIZE());
}
References TRUSTVect< _TYPE_ >::reset().
Referenced by Champ_Generique_Extraction::completer(), Op_Ecart_type::completer(), Hexa_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), ExtrudeParoi::extrude(), Extruder_en20::extruder(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Postraitement_lata::postraiter_liste_champs(), SSOR::prepare_(), Domaine::read_vertices(), Domaine::readOn(), Remove_elem::recreer_faces(), Operateurs_Statistique_tps::reprendre(), Faces_builder::reset(), Joint_Items::reset(), Octree_Int::reset(), Traduction_Indice_Global_Local::reset(), Roue::supprimer_case(), and Moyenne_volumique::traiter_champs().
resize() [1/5]
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::resize (const TRUSTArray< int > & tailles, Array_base::Resize_Options opt = Array_base::COPY_INIT) inline
Definition at line 389 of file TRUSTTab.tpp.
{
  nb_dim_ = tailles.size_array();
  if (nb_dim_ <= 0 || nb_dim_ > MAXDIM_TAB)
    {
      Cerr << "Internal error in TRUSTTab::resize(const ArrOfInt & tailles, ...) \n" << " wrong dimensions number " << nb_dim_ << finl;
      Process::exit();
    }
  int l_size = 1;
  for (int i = 0; i < nb_dim_; i++)
    {
      const int n = tailles[i];
      dimensions_[i] = n;
      if (i > 0)
        l_size *= n;
      if (n < 0)
        {
          Cerr << "Internal error in TRUSTTab::resize(const ArrOfInt & tailles, ...) \n" << " wrong dimensions: " << tailles << finl;
          Process::exit();
        }
    }
  dimension_tot_0_ = dimensions_[0];
  TRUSTVect<_TYPE_>::set_line_size_(l_size);
  TRUSTVect<_TYPE_>::resize_vect_(dimensions_[0] * l_size, opt);
  assert(verifie_LINE_SIZE());
}
References Cerr, Process::exit(), finl, TRUSTVect< _TYPE_ >::resize_vect_(), TRUSTVect< _TYPE_ >::set_line_size_(), and TRUSTArray< _TYPE_ >::size_array().
resize() [2/5]
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::resize (int n, Array_base::Resize_Options opt = Array_base::COPY_INIT) inline
Definition at line 313 of file TRUSTTab.tpp.
{
  assert(n >= 0);
  TRUSTVect<_TYPE_>::set_line_size_(1);
  TRUSTVect<_TYPE_>::resize_vect_(n, opt);
  nb_dim_ = 1;
  dimensions_[0] = dimension_tot_0_ = n;
  assert(verifie_LINE_SIZE());
}
References TRUSTVect< _TYPE_ >::resize_vect_(), and TRUSTVect< _TYPE_ >::set_line_size_().
Referenced by Frontiere::add(), BlocData::add_bloc(), add_sommets_communs(), Polygone::affecte_connectivite_numero_global(), Polyedre::affecte_connectivite_numero_global(), Champ_Face_PolyMAC_P0::affecter_(), Champ_P1NC::affecter_(), Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Domaine::ajouter(), Op_Div_EF::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Div_PolyMAC_P0::ajouter(), T_It_VDF_Elem< _TYPE_ >::ajouter(), T_It_VDF_Face< _TYPE_ >::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution(), T_It_VDF_Face< _TYPE_ >::ajouter_contribution(), Polyedre::ajouter_elements(), ajouter_joint(), Faces_builder::ajouter_une_face(), Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), Assembleur_P_EF::assembler_mat(), Eval_Darcy_VDF_Face::associer(), Eval_Darcy_VEF_Face::associer(), Op_Diff_EF_base::associer(), Op_Diff_VEF_base::associer(), Zone_Cl_VEF::associer(), Pave::associer_domaine(), Terme_Source_Coriolis_VDF_Face::associer_pb(), Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), auto_build_joints(), Octree_Int::build(), build_cells(), build_edges(), Refine_Mesh::build_edges(), Octree_Double::build_elements(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), Refine_Mesh::build_new_nodes(), Octree_Double::build_nodes(), build_nodes(), Matrice_Bloc::build_stencil(), Ch_front_input::buildSommetsFaces(), Calcul_integrale_locale::Calcul_integrale_locale(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Calcul_integrale_locale::calculer(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Zone_EF::calculer_Bij(), Aretes::calculer_centre_de_gravite(), Elem_geom_base::calculer_centres_gravite(), Hexaedre_axi::calculer_centres_gravite(), Rectangle_axi::calculer_centres_gravite(), Polyedre::calculer_centres_gravite(), Polygone::calculer_centres_gravite(), calculer_centres_gravite(), Zone::calculer_centres_gravite_aretes(), Equation_base::calculer_champ_conserve(), Op_Conv_EF_VEF_P1NC_Stab::calculer_data_pour_dirichlet(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Fluide_base::calculer_e_int(), Fluide_reel_base::calculer_energie_interne(), Milieu_composite::calculer_energie_interne(), Fluide_reel_base::calculer_enthalpie(), Milieu_composite::calculer_enthalpie(), T_It_VDF_Elem< _TYPE_ >::calculer_flux_bord(), Partitionneur_base::calculer_graphe_connexions_periodiques(), Assembleur_P_VEF::calculer_inv_volume(), calculer_inv_volume(), Zone_EF::calculer_IPhi(), Zone_EF_axi::calculer_IPhi(), Fluide_reel_base::calculer_masse_volumique(), Milieu_composite::calculer_masse_volumique(), Scatter::calculer_renum_items_communs(), Echange_contact_VDF::calculer_Teta_paroi(), Champ_base::calculer_valeurs_elem_compo_post(), Champ_base::calculer_valeurs_elem_post(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Hexaedre_VEF::calculer_volumes(), Quadrangle_VEF::calculer_volumes(), Zone_VDF::calculer_volumes_entrelaces(), caldscaldcentelemdim2(), caldscaldcentelemdim3(), calrotord2centelemdim2(), calrotord2centelemdim3(), Scatter::check_consistancy_remote_items(), Champ_front_calc_interne::completer(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), Op_Diff_PolyMAC_base::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Flux_interfacial_PolyMAC::completer(), Source_Neutronique::completer(), Echange_contact_Correlation_VDF::completer(), Echange_interne_impose::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Echange_contact_Correlation_VEF::completer(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Champ_Generique_Extraction::completer(), Op_Correlation::completer(), Zones::comprimer(), Schema_Adams_Bashforth_order_2::compute_adams_bashforth_coefficients(), Schema_Adams_Bashforth_order_3::compute_adams_bashforth_coefficients(), Schema_Adams_Moulton_order_2::compute_adams_moulton_coefficients(), Schema_Adams_Moulton_order_3::compute_adams_moulton_coefficients(), Schema_Backward_Differentiation_order_2::compute_backward_differentiation_coefficients(), Schema_Backward_Differentiation_order_3::compute_backward_differentiation_coefficients(), compute_global_connex_components(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Extruder_en3::construire_bord_lateral(), Extruder_en3::construire_bords(), Scatter::construire_correspondance_items_par_coordonnees(), Zone::construire_elem_virt_pe_num(), construire_elems_sous_domaine(), Zone_VF::construire_face_virt_pe_num(), DomaineCutter::construire_faces_joints_ssdom(), Domain_Graph::construire_graph_from_segment(), construire_liste_faces_sous_domaine(), Zone_VF::construire_num_fac_loc(), Matrice_Morse::construire_sous_bloc(), Op_Conv_VEF_Face::contribue_au_second_membre(), T_It_VDF_Face< _TYPE_ >::contribuer_au_second_membre(), convert_domain_to_Domaine(), corriger_type(), Zone::creer_aretes(), Zone_VDF::creer_elements_fictifs(), Remove_elem::creer_faces(), Faces_builder::creer_faces_reeles(), Hexa_VEF::creer_facette_normales(), Quadri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), Fluide_base::creer_nu(), Champ_Fonc_base::creer_tableau_distribue(), Champ_Inc_base::creer_tableau_distribue(), decoupe(), Tetraedriser_homogene_compact::decoupe(), Tetraedriser_homogene_fin::decoupe(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Matrice_Dense::dimensionner(), Roue::dimensionner(), Faces::dimensionner(), Aretes::dimensionner(), Op_VDF_Elem::dimensionner_bloc_vitesse(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Champ_Face::dimensionner_tenseur_Grad(), Zone_EF::discretiser(), Sous_zone_VF::discretiser(), Zone_Poly_base::discretiser(), Zone_VF::discretiser(), Zone_PolyMAC::discretiser(), Zone_VEF::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), SETS::eliminer(), Ensemble_Lagrange_base::Ensemble_Lagrange_base(), Matrix_tools::extend_matrix_stencil(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en3::extruder(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), Extruder::extruder_hexa(), ExtrudeBord::extruder_hexa_old(), Zone_PolyMAC_P0::fgrad(), fill_tab_2(), fill_tab_2_new(), fill_tab_3(), find_joint_faces(), Champ_Don_base::fixer_nb_valeurs_nodales(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_front_recyclage::get_coord_faces(), Matrice_Bloc::get_stencil(), Matrice_Dense::get_stencil(), Matrice_Diagonale::get_stencil(), Matrice_Morse::get_stencil(), Matrice_Nulle::get_stencil(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Diagonale::get_stencil_and_coefficients(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Nulle::get_stencil_and_coefficients(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Tetraedre::get_tab_aretes_sommets_locaux(), Hexaedre::get_tab_faces_sommets_locaux(), Hexaedre_VEF::get_tab_faces_sommets_locaux(), Point::get_tab_faces_sommets_locaux(), Prisme::get_tab_faces_sommets_locaux(), Quadrangle_VEF::get_tab_faces_sommets_locaux(), Rectangle::get_tab_faces_sommets_locaux(), Segment::get_tab_faces_sommets_locaux(), Tetraedre::get_tab_faces_sommets_locaux(), Triangle::get_tab_faces_sommets_locaux(), Polyedre::get_tab_faces_sommets_locaux(), Polygone::get_tab_faces_sommets_locaux(), Champ_front_instationnaire_base::Gpoint(), Hexa_VEF::Hexa_VEF(), Zone::identifie_item_unique(), Op_Grad_VEF_P1B_Face::impr(), Op_Grad_EF::impr(), Op_Grad_VDF_Face::impr(), Champ_Fonc_P0_VDF::imprime(), Champ_P0_VDF::imprime(), Champ_Face_implementation::imprime_Face(), Terme_Source_Canal_RANS_LES_VDF_Elem::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Echange_contact_Correlation_VEF::init(), Terme_Source_Canal_RANS_LES_VEF_Face::init(), Sonde::init_bords(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Traitement_particulier_NS_Profils::init_calcul_stats(), Traitement_particulier_NS_Profils_thermo_VDF::init_calcul_stats(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Champ_Inc_base::init_champ_calcule(), Zone_Poly_base::init_dist_paroi_globale(), Zone_Poly_base::init_equiv(), Echange_contact_PolyMAC::init_f_dist(), Zone::init_faces_virt_bord(), Champ_Elem_PolyMAC::init_fcl(), Champ_Face_PolyMAC::init_fcl(), Champ_implementation_P1::init_from_file(), Echange_contact_PolyMAC_P0::init_fs_dist(), init_parts(), Op_Diff_PolyMAC_P0_Elem::init_som_ext(), Zone_PolyMAC_P0::init_stencils(), Echange_contact_Correlation_VDF::init_tab_echange(), Champ_Face_PolyMAC_P0::init_ve2(), Raccord_distant_homogene::initialise(), Sonde::initialiser(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Loi_Etat_GR_base::initialiser(), Traduction_Indice_Global_Local::initialiser(), Sonde_Int::initialiser(), Echange_contact_VDF::initialiser(), Ch_front_input_P1::initialiser(), Champ_front_var::initialiser(), Champ_front_recyclage::initialiser(), Champ_front_xyz_debit::initialiser(), Champ_front_xyz_debit::initialiser_coefficient(), Loi_Etat_GR_base::initialiser_inco_ch(), Loi_Etat_Multi_GP_base::initialiser_inco_ch(), Loi_Etat_rhoT_GP_QC::initialiser_rho(), Moyenne_volumique::interpreter(), Raffiner_isotrope_parallele::interpreter(), latatoother::interpreter(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), VerifierCoin::interpreter_(), Simple::iterer_eqs(), kersol(), Traitement_particulier_NS_Brech_VEF::lire(), Pave::lire_front(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Pave::lire_Noeuds(), Faces::lit(), Zones::merge(), Champ_front_xyz_debit::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), mon_construire_correspondance_items_par_coordonnees(), Zone_PolyMAC::orthocentrer(), Traitement_particulier_NS_canal::post_traitement_particulier(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), Format_Post_base::postraiter_debug_valeurs_un_instant(), Postraitement_lata::postraiter_liste_champs(), SSOR::prepare_(), Op_Conv_EF_Stab_PolyMAC_Elem::preparer_calcul(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), Quadri_VEF::Quadri_VEF(), Raffiner_anisotrope::Raffiner_anisotrope_(), Champ_front_uniforme::readOn(), Champ_input_P0::readOn(), Ch_input_uniforme::readOn(), Champ_Fonc_Tabule_Morceaux::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Uniforme_Morceaux_Tabule_Temps::readOn(), Sonde::readOn(), Sonde_Int::readOn(), Faces::readOn(), Champ_front_MED::readOn(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::readOn(), Sortie_libre_pression_imposee_QC::readOn(), Loi_Etat_rhoT_GR_QC::readOn(), Sortie_libre_pression_imposee::readOn(), Sortie_libre_pression_moyenne_imposee::readOn(), Flux_interfacial_Coef_Constant::readOn(), Sortie_libre_Gradient_Pression_impose::readOn(), Sortie_libre_Pression_imposee_Orlansky::readOn(), Sortie_libre_Gradient_Pression_impose_VEF::readOn(), Sortie_libre_Gradient_Pression_libre_VEF::readOn(), Remove_elem::recreer_faces(), Remove_elem::Remove_elem_(), Assembleur_P_VEF::remplir(), Champ_P0_VDF::remplir_coord_noeuds(), Champ_implementation_P0::remplir_coord_noeuds(), Champ_implementation_sommet_base::remplir_coord_noeuds(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Champ_implementation_sommet_base::remplir_coord_noeuds_et_polys(), remplir_coordsommets_sous_domaine(), Zone_VF::remplir_face_numero_bord(), Op_Diff_VEF_base::remplir_nu(), Ensemble_Lagrange_base::remplir_sommets_tmp(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Zone_EF_axi::remplir_tableau_origine(), Scatter::reordonner_faces_de_joint(), Champ_Elem_PolyMAC::reprendre(), Champ_Face_PolyMAC::reprendre(), Traitement_particulier_NS_Profils::reprendre_stat(), Traitement_particulier_NS_Profils_thermo_VDF::reprendre_stat(), Traitement_particulier_NS_canal::reprendre_stat_canal(), MD_Vector_tools::restore_vector_with_md(), Simple::Simple(), Solv_Gen::solve(), Tetra_VEF::Tetra_VEF(), Champ_Elem_PolyMAC::trace(), Raccord_distant_homogene::trace_elem_distant(), Frontiere::trace_elem_local(), Raccord_distant_homogene::trace_face_distant(), Frontiere::trace_som_local(), Moyenne_volumique::traiter_champs(), Extruder::traiter_faces_dvt(), Extruder_en20::traiter_faces_dvt(), Extruder::traiter_faces_dvt_hexa(), Champ_Q1NC_impl::transforme_coord2D(), Champ_Q1NC_impl::transforme_coord3D(), Tri_VEF::Tri_VEF(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), TRUSTTabFT< _TYPE_ >::TRUSTTabFT(), TRUSTTrav< _TYPE_ >::TRUSTTrav(), Matrice_Sym::unsymmetrize_stencil(), Matrice_Sym::unsymmetrize_stencil_and_coefficients(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_faces(), Champ_implementation_Q1::value_interpolation(), Zone_VEF::vecteur_face_facette(), Zone_PolyMAC::W1(), Zone_PolyMAC::W2(), and Zone_VF::xv_bord().
resize() [3/5]
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::resize (int n1, int n2, Array_base::Resize_Options opt = Array_base::COPY_INIT) inline
Definition at line 324 of file TRUSTTab.tpp.
{
  assert(n >= 0 && n2 >= 0);
  TRUSTVect<_TYPE_>::set_line_size_(n2);
  int new_size = n * n2;
  if (std::is_same<_TYPE_,int>::value && new_size < 0)
    {
      Cerr << "n1*n2 > 2^31. Error! Contact TRUST support, integer 32 bits limit exceeded with n1=" << n << " and n2=" << n2 << finl;
      Process::exit();
    }
  TRUSTVect<_TYPE_>::resize_vect_(new_size, opt);
  nb_dim_ = 2;
  dimensions_[0] = dimension_tot_0_ = n;
  dimensions_[1] = n2;
  assert(verifie_LINE_SIZE());
}
References Cerr, Process::exit(), finl, TRUSTVect< _TYPE_ >::resize_vect_(), and TRUSTVect< _TYPE_ >::set_line_size_().
resize() [4/5]
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::resize (int n1, int n2, int n3, Array_base::Resize_Options opt = Array_base::COPY_INIT) inline
Definition at line 344 of file TRUSTTab.tpp.
{
  assert(n >= 0 && n2 >= 0 && n3 >= 0);
  TRUSTVect<_TYPE_>::set_line_size_(n2 * n3);
  int new_size = n * n2 * n3;
  if (std::is_same<_TYPE_,int>::value && new_size < 0)
    {
      Cerr << "n1*n2*n3 > 2^31. Error! Contact TRUST support, integer 32 bits limit exceeded with n1=" << n << " and n2=" << n2 << " and n3=" << n3 << finl;
      Process::exit();
    }
  TRUSTVect<_TYPE_>::resize_vect_(new_size, opt);
  nb_dim_ = 3;
  dimensions_[0] = dimension_tot_0_ = n;
  dimensions_[1] = n2;
  dimensions_[2] = n3;
  assert(verifie_LINE_SIZE());
}
References Cerr, Process::exit(), finl, TRUSTVect< _TYPE_ >::resize_vect_(), and TRUSTVect< _TYPE_ >::set_line_size_().
resize() [5/5]
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::resize (int n1, int n2, int n3, int n4, Array_base::Resize_Options opt = Array_base::COPY_INIT) inline
Definition at line 365 of file TRUSTTab.tpp.
{
  assert(n >= 0 && n2 >= 0 && n3 >= 0 && n4 >= 0);
  TRUSTVect<_TYPE_>::set_line_size_(n2 * n3 * n4);
  int new_size = n * n2 * n3 * n4;
  if (std::is_same<_TYPE_,int>::value && new_size<0)
    {
      Cerr << "n1*n2*n3*n4 > 2^31. Error! Contact TRUST support, integer 32 bits limit exceeded with n1=" << n << " and n2=" << n2 << " and n3=" << n3 << " and n4=" << n4 << finl;
      Process::exit();
    }
  TRUSTVect<_TYPE_>::resize_vect_(new_size, opt);
  nb_dim_ = 4;
  dimensions_[0] = dimension_tot_0_ = n;
  dimensions_[1] = n2;
  dimensions_[2] = n3;
  dimensions_[3] = n4;
  assert(verifie_LINE_SIZE());
}
References Cerr, Process::exit(), finl, TRUSTVect< _TYPE_ >::resize_vect_(), and TRUSTVect< _TYPE_ >::set_line_size_().
resize_dim0()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::resize_dim0 (int n, Array_base::Resize_Options opt = Array_base::COPY_INIT) inline
Definition at line 303 of file TRUSTTab.tpp.
{
  assert(n >= 0);
  assert(dimension_tot_0_ * TRUSTVect<_TYPE_>::line_size() == TRUSTVect<_TYPE_>::size_array());
  TRUSTVect<_TYPE_>::resize_vect_(n * TRUSTVect<_TYPE_>::line_size(), opt);
  dimensions_[0] = dimension_tot_0_ = n;
  assert(verifie_LINE_SIZE());
}
References TRUSTVect< _TYPE_ >::resize_vect_().
Referenced by Octree_Int::build_octree_recursively(), find_joint_faces(), Champ_Elem_PolyMAC::init_auxiliary_variables(), Champ_Face_PolyMAC::init_auxiliary_variables(), Champ_Face_PolyMAC_P0::init_auxiliary_variables(), and resize_tab_lines().
resize_tab()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::resize_tab (int n, Array_base::Resize_Options opt = Array_base::COPY_INIT) inline override virtual
Reimplemented from TRUSTArray< _TYPE_ >.
Definition at line 294 of file TRUSTTab.tpp.
{
  resize(n, opt);
  assert(verifie_LINE_SIZE());
}
resoud_LU()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::resoud_LU (int n, TRUSTArray< int > & index, const TRUSTArray< double > & b, TRUSTArray< double > & solution) inline
Definition at line 715 of file TRUSTTab.tpp.
{
  int i,ii=-1,ip,j;
  double sum;
  solution = b;
  for (i=0 ; i<n ; i++)
    {
      ip = index[i];
      sum = solution[ip];
      solution[ip] = solution[i];
      if (ii!=-1)
        for (j=ii ; j<i ; j++) sum -= (*this)(i,j)*solution[j];
      else if (sum) ii =i;
      solution[i] = sum;
    }
  for (i=n-1 ; i>=0 ; i--)
    {
      sum = solution[i];
      for (j=i+1 ; j<n ; j++) sum -= (*this)(i,j)*solution[j];
      solution[i] = sum/(*this)(i,i);
    }
}
Referenced by TRUSTTab< _TYPE_ >::inverse_LU().
set_md_vector()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::set_md_vector (const MD_Vector & md_vector) inline override virtual
Reimplemented from TRUSTVect< _TYPE_ >.
Definition at line 514 of file TRUSTTab.tpp.
{
  int dim0 = dimension_tot_0_;
  if (md_vector.non_nul())
    {
// renvoie -1 si l'appel et invalide:
      dim0 = md_vector.valeur().get_nb_items_reels();
    }
  dimensions_[0] = dim0;
  assert(verifie_LINE_SIZE());
// a appeler meme pour un md_vector nul (pour remettre size_reelle_):
  TRUSTVect<_TYPE_>::set_md_vector(md_vector);
}
References MD_Vector_base::get_nb_items_reels(), MD_Vector::non_nul(), TRUSTVect< _TYPE_ >::set_md_vector(), and MD_Vector::valeur().
Referenced by Domaine::ajouter(), calculer_centres_gravite(), Scatter::construire_structures_paralleles(), Zone::creer_aretes(), Champ_Elem_PolyMAC::init_auxiliary_variables(), Champ_Face_PolyMAC::init_auxiliary_variables(), Champ_Face_PolyMAC_P0::init_auxiliary_variables(), init_parts(), Scatter::init_sequential_domain(), SSOR::prepare_(), Debog_Pb::read_geometry_data(), Champ_Fonc_MED::readOn(), Champ_Elem_PolyMAC::reprendre(), Champ_Face_PolyMAC::reprendre(), MD_Vector_tools::restore_vector_with_md(), Solv_Gen::solve(), TRUSTTrav< _TYPE_ >::TRUSTTrav(), and Scatter::uninit_sequential_domain().
taille_memoire()
template<typename _TYPE_ > unsigned TRUSTTab< _TYPE_ >::taille_memoire () const inline override protected virtual
Reimplemented from TRUSTArray< _TYPE_ >.
Reimplemented in TRUSTTrav< _TYPE_ >.
Definition at line 28 of file TRUSTTab.h.
{ throw; }
verifie_LINE_SIZE()
template<typename _TYPE_ > bool TRUSTTab< _TYPE_ >::verifie_LINE_SIZE () const inline private
Definition at line 260 of file TRUSTTab.h.
  {
    return ((TRUSTVect<_TYPE_>::line_size() == ((nb_dim_ > 1) ? dimensions_[1] : 1) * ((nb_dim_ > 2) ? dimensions_[2] : 1) * ((nb_dim_ > 3) ? dimensions_[3] : 1))
            && (TRUSTVect<_TYPE_>::line_size() * dimension_tot_0_ == TRUSTVect<_TYPE_>::size_array()));
  }
References TRUSTTab< _TYPE_ >::dimension_tot_0_, TRUSTTab< _TYPE_ >::dimensions_, and TRUSTTab< _TYPE_ >::nb_dim_.
Referenced by TRUSTTab< _TYPE_ >::printOn(), and TRUSTTab< _TYPE_ >::readOn().
verifie_MAXDIM_TAB()
template<typename _TYPE_ > void TRUSTTab< _TYPE_ >::verifie_MAXDIM_TAB () const inline private
Definition at line 251 of file TRUSTTab.h.
  {
    if (MAXDIM_TAB != 4)
      {
        Cerr << "Update code for MAXDIM_TAB for CHECK_LINE_SIZE" << finl;
        throw;
      }
  }
References Cerr, finl, and TRUSTTab< _TYPE_ >::MAXDIM_TAB.
Member Data Documentation
dimension_tot_0_
template<typename _TYPE_ > int TRUSTTab< _TYPE_ >::dimension_tot_0_ private
Definition at line 249 of file TRUSTTab.h.
Referenced by TRUSTTab< _TYPE_ >::copy(), TRUSTTab< _TYPE_ >::printOn(), TRUSTTab< _TYPE_ >::readOn(), TRUSTTab< _TYPE_ >::ref_tab(), and TRUSTTab< _TYPE_ >::verifie_LINE_SIZE().
dimensions_
template<typename _TYPE_ > int TRUSTTab< _TYPE_ >::dimensions_[MAXDIM_TAB] private
Definition at line 245 of file TRUSTTab.h.
Referenced by TRUSTTab< _TYPE_ >::copy(), TRUSTTab< _TYPE_ >::printOn(), TRUSTTab< _TYPE_ >::readOn(), TRUSTTab< _TYPE_ >::ref_tab(), TRUSTTab< _TYPE_ >::TRUSTTab(), and TRUSTTab< _TYPE_ >::verifie_LINE_SIZE().
MAXDIM_TAB
template<typename _TYPE_ > constexpr int TRUSTTab< _TYPE_ >::MAXDIM_TAB = 4 static constexpr private
Definition at line 240 of file TRUSTTab.h.
Referenced by TRUSTTab< _TYPE_ >::init_dimensions(), TRUSTTab< _TYPE_ >::readOn(), TRUSTTab< _TYPE_ >::TRUSTTab(), and TRUSTTab< _TYPE_ >::verifie_MAXDIM_TAB().
nb_dim_
template<typename _TYPE_ > int TRUSTTab< _TYPE_ >::nb_dim_ private
Definition at line 242 of file TRUSTTab.h.
Referenced by TRUSTTab< _TYPE_ >::copy(), TRUSTTab< _TYPE_ >::nb_dim(), TRUSTTab< _TYPE_ >::printOn(), TRUSTTab< _TYPE_ >::readOn(), TRUSTTab< _TYPE_ >::ref_tab(), and TRUSTTab< _TYPE_ >::verifie_LINE_SIZE().
The documentation for this class was generated from the following files:
src/Kernel/Math/TRUSTTab.h
src/Kernel/Math/TRUSTTab.tpp