TRUST: Eval_Dift_VDF_const_Elem Class Reference
Eval_Dift_VDF_const_Elem Class Reference
class Eval_Dift_VDF_const_Elem
Evaluateur VDF pour la diffusion totale (laminaire et turbulente)
Le champ diffuse est scalaire (Champ_P0_VDF)
Le champ de diffusivite est constant.
#include <Eval_Dift_VDF_leaves.h>
Public Member Functions
Eval_Dift_VDF_const_Elem ()
int get_ind_Fluctu_Term () const
void associer_loipar (const Turbulence_paroi_scal &loi_paroi)
void associer_modele_turbulence (const Modele_turbulence_scal_base &mod)
Static Public Attributes
static constexpr bool IS_MODIF_DEQ = true
Private Attributes
Ref_Modele_turbulence_scal_base le_modele_turbulence
int ind_Fluctu_Term
Detailed Description
class Eval_Dift_VDF_const_Elem
Evaluateur VDF pour la diffusion totale (laminaire et turbulente)
Le champ diffuse est scalaire (Champ_P0_VDF)
Le champ de diffusivite est constant.
Definition at line 84 of file Eval_Dift_VDF_leaves.h.
Constructor & Destructor Documentation
Eval_Dift_VDF_const_Elem::Eval_Dift_VDF_const_Elem () [inline]
Definition at line 88 of file Eval_Dift_VDF_leaves.h.
: ind_Fluctu_Term(1) {}
Member Function Documentation
void Eval_Dift_VDF_const_Elem::associer_loipar (const Turbulence_paroi_scal & loi_paroi) [inline, virtual]
Reimplemented from Eval_Turbulence.
Definition at line 96 of file Eval_Dift_VDF_leaves.h.
References Eval_Diff_VDF_Elem< Eval_Dift_VDF_const_Elem >::ind_Fluctu_Term().
Referenced by Op_Dift_VDF_Elem::associer_loipar(), and Eval_Dift_VDF_var_Elem::associer_loipar().
  {
    Eval_Dift_VDF_const::associer_loipar(loi_paroi);
    ind_Fluctu_Term = 0;
  }
void Eval_Dift_VDF_const_Elem::associer_modele_turbulence (const Modele_turbulence_scal_base & mod) [inline]
Definition at line 102 of file Eval_Dift_VDF_leaves.h.
References Eval_Diff_VDF_Elem< Eval_Dift_VDF_const_Elem >::ind_Fluctu_Term(), le_modele_turbulence, Eval_Turbulence::loipar, and O_U_Ptr::non_nul().
Referenced by Op_Dift_VDF_Elem::completer().
  {
// On remplit la reference au modele de turbulence et le tableau k:
    le_modele_turbulence = mod;
    ind_Fluctu_Term = 0;
    if (!loipar.non_nul())
      ind_Fluctu_Term = 1;
  }
int Eval_Dift_VDF_const_Elem::get_ind_Fluctu_Term () const [inline]
Reimplemented from Eval_Diff_VDF.
Definition at line 91 of file Eval_Dift_VDF_leaves.h.
References Eval_Diff_VDF_Elem< Eval_Dift_VDF_const_Elem >::ind_Fluctu_Term().
  {
    return ind_Fluctu_Term;
  }
Member Data Documentation
int Eval_Dift_VDF_const_Elem::ind_Fluctu_Term [private]
Definition at line 113 of file Eval_Dift_VDF_leaves.h.
constexpr bool Eval_Dift_VDF_const_Elem::IS_MODIF_DEQ = true [static]
Reimplemented from Eval_Diff_VDF_Elem< Eval_Dift_VDF_const_Elem >.
Definition at line 89 of file Eval_Dift_VDF_leaves.h.
Ref_Modele_turbulence_scal_base Eval_Dift_VDF_const_Elem::le_modele_turbulence [private]
Definition at line 112 of file Eval_Dift_VDF_leaves.h.
Referenced by Eval_Dift_VDF_var_Elem::associer_modele_turbulence(), and associer_modele_turbulence().
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs_Diff/Eval_Dift_VDF_leaves.h