TRUST: Terme_Source_Acceleration_VEF_Face Class Reference
Terme_Source_Acceleration_VEF_Face Class Reference
Terme source d'acceleration specialise pour la discretisation VDF.
#include <Terme_Source_Acceleration_VEF_Face.h>
Public Member Functions
Terme_Source_Acceleration_VEF_Face ()
~Terme_Source_Acceleration_VEF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const
Ajoute le terme (la_source_ * rho * volume_entrelace) au champ resu.
On suppose que resu est discretise comme la vitesse.
L'espace virtuel de "resu" n'est PAS mis a jour !
Commentaire sur le schema: L'acceleration d/dt(v) est calculee aux elements,
puis multipliee par "rho" aux elements, puis evaluee aux faces par une
moyenne sur les elements voisins de la face. C'est un premier essai, pas
forcement la meilleure idee. Comme l'acceleration depend de la vitesse qui
est aux faces, on passe par deux interpolations successives.
Effet de bord:
On met (la_source_ * rho) dans terme_source_post_.
void associer_champ_rho (const Champ_base &champ_rho)
Associe le champ de masse volumique=>
Le terme source calcule sera alors homogene a d/dt(integrale(rho*v)).
Parametre: champ_rho
Signification: un champ de type Champ_Fonc_P0_VEF qui sera utilise
lors des appels a "ajouter()" pour evaluer la masse volumique.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Terme_Source_Acceleration_VEF_Face & self_cast (Objet_U &)
static const
Terme_Source_Acceleration_VEF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
Appel a Terme_Source_Acceleration::lire_data.
const DoubleTab & calculer_vitesse_faces (DoubleTab &v_faces_stockage) const
Calcul du champ de vitesse trois composantes aux faces a partir
du champ de vitesse aux faces de eq_hydraulique_.inconnue().
En VEF: rien a faire. On ne se sert pas du stockage fourni en
parametre, on renvoie N.S.inconnue()
Parametre: v_faces_stockage
Signification: tableau ou stocker le resultat s'il y a des calculs a faire.
En vef, on ne s'en sert pas.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
Methode appelee par Source_base::completer() apres associer_zones
Remplit les ref. aux zones et zone_cl.
Private Attributes
Ref_Zone_VEF_PreP1b la_zone_VEF_
Ref_Zone_Cl_VEFP1B la_zone_Cl_VEF_
Ref_Champ_base ref_rho_
Detailed Description
Terme source d'acceleration specialise pour la discretisation VDF.
See also:
Terme_Source_Acceleration
Definition at line 35 of file Terme_Source_Acceleration_VEF_Face.h.
Constructor & Destructor Documentation
Terme_Source_Acceleration_VEF_Face::Terme_Source_Acceleration_VEF_Face ()
Definition at line 30 of file Terme_Source_Acceleration_VEF_Face.cpp.
Terme_Source_Acceleration_VEF_Face::~Terme_Source_Acceleration_VEF_Face ()
Definition at line 30 of file Terme_Source_Acceleration_VEF_Face.cpp.
Member Function Documentation
DoubleTab & Terme_Source_Acceleration_VEF_Face::ajouter (DoubleTab & resu) const [virtual]
Ajoute le terme (la_source_ * rho * volume_entrelace) au champ resu.
On suppose que resu est discretise comme la vitesse.
L'espace virtuel de "resu" n'est PAS mis a jour !
Commentaire sur le schema: L'acceleration d/dt(v) est calculee aux elements,
puis multipliee par "rho" aux elements, puis evaluee aux faces par une
moyenne sur les elements voisins de la face. C'est un premier essai, pas
forcement la meilleure idee. Comme l'acceleration depend de la vitesse qui
est aux faces, on passe par deux interpolations successives.
Effet de bord:
On met (la_source_ * rho) dans terme_source_post_.
Reimplemented from Source_base.
Reimplemented in Acceleration_QC_VEF_P1NC.
Definition at line 136 of file Terme_Source_Acceleration_VEF_Face.cpp.
References Terme_Source_Acceleration::calculer_la_source(), DoubleTab::dimension(), Objet_U::dimension, face_associee, Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Terme_Source_Acceleration::get_set_terme_source_post(), la_zone_Cl_VEF_, la_zone_VEF_, Zone_Cl_dis_base::les_conditions_limites(), DoubleVect::line_size(), Zone_VF::nb_faces(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, ref_rho_, sub_type, TSAVEF_ajouter_liste_faces(), Deriv_Cond_lim_base::valeur(), Deriv_Champ_Fonc_base::valeur(), Ref_Zone_Cl_VEFP1B::valeur(), Ref_Zone_VEF_PreP1b::valeur(), Champ_Don_base::valeurs(), Zone_VF::volumes(), and Zone_VF::volumes_entrelaces().
{
  const Zone_VF&     zone               = la_zone_VEF_.valeur();
  const Zone_Cl_dis_base& zone_Cl       = la_zone_Cl_VEF_.valeur();
  const IntTab&      face_voisins       = zone.face_voisins();
  const DoubleVect& porosite_surf      = zone.porosite_face();
  const DoubleVect& volumes_entrelaces = zone.volumes_entrelaces();
  DoubleTab& s_face = get_set_terme_source_post().valeur().valeurs();
  s_face = 0.;
// Calcul de la_source_ en fonction des champs d'acceleration et de la
// vitesse du fluide.
  const int dim     = Objet_U::dimension;
  const int nb_faces = resu.dimension(0);
  DoubleTab acceleration_aux_faces(nb_faces, dim);
  calculer_la_source(acceleration_aux_faces);
// Boucle sur les conditions limites pour traiter les faces de bord
  for (int n_bord = 0; n_bord < zone.nb_front_Cl(); n_bord++)
    {
// pour chaque Condition Limite on regarde son type
// Si face de Dirichlet on ne fait rien
// Si face de Neumann, Periodique ou de Symetrie on calcule la contribution au terme source
      const Cond_lim& la_cl = zone_Cl.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      const int ndeb = le_bord.num_premiere_face();
      const int nfin = ndeb + le_bord.nb_faces();
      TSAVEF_ajouter_liste_faces(ndeb, nfin,
                                 volumes_entrelaces,
                                 zone.volumes(),
                                 porosite_surf,
                                 face_voisins,
                                 ref_rho_,
                                 acceleration_aux_faces,
                                 s_face,
                                 resu);
    }
// Boucle sur les faces internes
  {
    const int ndeb = zone.premiere_face_int();
    const int nfin = zone.nb_faces();
    TSAVEF_ajouter_liste_faces(ndeb, nfin,
                               volumes_entrelaces,
                               zone.volumes(),
                               porosite_surf,
                               face_voisins,
                               ref_rho_,
                               acceleration_aux_faces,
                               s_face,
                               resu);
  }
  {
// Force la periodicite
    int nb_comp=resu.line_size();
    for (int n_bord=0; n_bord<zone.nb_front_Cl(); n_bord++)
      {
        const Cond_lim& la_cl = zone_Cl.les_conditions_limites(n_bord);
        if (sub_type(Periodique,la_cl.valeur()))
          {
            const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
            const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
            int nb_faces_bord=le_bord.nb_faces();
            ArrOfInt fait(nb_faces_bord);
            fait = 0;
            for (int ind_face=0; ind_face<nb_faces_bord; ind_face++)
              {
                if (fait(ind_face) == 0)
                  {
                    int ind_face_associee = la_cl_perio.face_associee(ind_face);
                    fait(ind_face) = 1;
                    fait(ind_face_associee) = 1;
                    int face = le_bord.num_face(ind_face);
                    int face_associee = le_bord.num_face(ind_face_associee);
                    for (int comp=0; comp<nb_comp; comp++)
                      {
                        double val = 0.5*(resu(face_associee, comp)+resu(face, comp));
                        resu(face, comp)=resu(face_associee, comp) = val;
                      }
                  }//!< if fait
              }//!< for face
          }//!< sub_type Perio
      }
  }
  return resu;
}
void Terme_Source_Acceleration_VEF_Face::associer_champ_rho (const Champ_base & champ_rho) [virtual]
Associe le champ de masse volumique=>
Le terme source calcule sera alors homogene a d/dt(integrale(rho*v)).
Parametre: champ_rho
Signification: un champ de type Champ_Fonc_P0_VEF qui sera utilise
lors des appels a "ajouter()" pour evaluer la masse volumique.
Reimplemented from Source_base.
Definition at line 249 of file Terme_Source_Acceleration_VEF_Face.cpp.
References Cerr, Process::exit(), finl, Field_base::le_nom(), Objet_U::que_suis_je(), ref_rho_, and sub_type.
{
// Il faut que le champ soit discretise aux elements: possibilite
// d'autoriser d'autres types si besoin (Champ_Don, Champ_Inc, etc.)
// du moment que c'est des champs P0.
  if (!sub_type(Champ_Fonc_P0_VEF, champ_rho))
    {
      Cerr << "Erreur dans Terme_Source_Acceleration_VEF_Face::associer_champ_rho" << finl;
      Cerr << " Le champ de masse volumique doit etre de type Champ_Fonc_P0_VEF" << finl;
      Cerr << " Type du champ associe : " << champ_rho.que_suis_je() << finl;
      Cerr << " Nom du champ associe :  " << champ_rho.le_nom() << finl;
      assert(0);
      exit();
    }
  ref_rho_ = champ_rho;
}
void Terme_Source_Acceleration_VEF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) [protected, virtual]
Methode appelee par Source_base::completer() apres associer_zones
Remplit les ref. aux zones et zone_cl.
Implements Source_base.
Definition at line 47 of file Terme_Source_Acceleration_VEF_Face.cpp.
References Cerr, finl, Process::je_suis_maitre(), la_zone_Cl_VEF_, la_zone_VEF_, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  if (je_suis_maitre())
    Cerr << "Terme_Source_Acceleration_VEF_Face::associer_zones" << finl;
  la_zone_VEF_    = ref_cast(Zone_VEF_PreP1b, zone_dis.valeur());
  la_zone_Cl_VEF_ = ref_cast(Zone_Cl_VEFP1B, zone_Cl_dis.valeur());
}
const DoubleTab & Terme_Source_Acceleration_VEF_Face::calculer_vitesse_faces (DoubleTab & v_faces_stockage) const [protected, virtual]
Calcul du champ de vitesse trois composantes aux faces a partir
du champ de vitesse aux faces de eq_hydraulique_.inconnue().
En VEF: rien a faire. On ne se sert pas du stockage fourni en
parametre, on renvoie N.S.inconnue()
Parametre: v_faces_stockage
Signification: tableau ou stocker le resultat s'il y a des calculs a faire.
En vef, on ne s'en sert pas.
Implements Terme_Source_Acceleration.
Definition at line 235 of file Terme_Source_Acceleration_VEF_Face.cpp.
References Terme_Source_Acceleration::get_eq_hydraulique(), Navier_Stokes_std::inconnue(), Deriv_Champ_Inc_base::valeur(), and Champ_Inc_base::valeurs().
{
  const Champ_Inc& v_faces = get_eq_hydraulique().inconnue();
  return v_faces.valeur().valeurs();
}
Objet_U * Terme_Source_Acceleration_VEF_Face::cree_instance () [static]
Reimplemented in Acceleration_QC_VEF_P1NC.
Definition at line 30 of file Terme_Source_Acceleration_VEF_Face.cpp.
int Terme_Source_Acceleration_VEF_Face::duplique () const [virtual]
Implements Terme_Source_Acceleration.
Reimplemented in Acceleration_QC_VEF_P1NC.
Definition at line 30 of file Terme_Source_Acceleration_VEF_Face.cpp.
const Type_info * Terme_Source_Acceleration_VEF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_Acceleration.
Reimplemented in Acceleration_QC_VEF_P1NC.
Definition at line 30 of file Terme_Source_Acceleration_VEF_Face.cpp.
const Type_info * Terme_Source_Acceleration_VEF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_Acceleration.
Reimplemented in Acceleration_QC_VEF_P1NC.
Definition at line 30 of file Terme_Source_Acceleration_VEF_Face.cpp.
Sortie & Terme_Source_Acceleration_VEF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Source_Acceleration.
Reimplemented in Acceleration_QC_VEF_P1NC.
Definition at line 32 of file Terme_Source_Acceleration_VEF_Face.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Terme_Source_Acceleration_VEF_Face::readOn (Entree & s) [protected, virtual]
Appel a Terme_Source_Acceleration::lire_data.
Reimplemented from Terme_Source_Acceleration.
Reimplemented in Acceleration_QC_VEF_P1NC.
Definition at line 38 of file Terme_Source_Acceleration_VEF_Face.cpp.
References Terme_Source_Acceleration::lire_data().
{
  lire_data(s);
  return s;
}
const Terme_Source_Acceleration_VEF_Face & Terme_Source_Acceleration_VEF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Terme_Source_Acceleration.
Reimplemented in Acceleration_QC_VEF_P1NC.
Definition at line 30 of file Terme_Source_Acceleration_VEF_Face.cpp.
Terme_Source_Acceleration_VEF_Face & Terme_Source_Acceleration_VEF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Terme_Source_Acceleration.
Reimplemented in Acceleration_QC_VEF_P1NC.
Definition at line 30 of file Terme_Source_Acceleration_VEF_Face.cpp.
unsigned Terme_Source_Acceleration_VEF_Face::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Acceleration_QC_VEF_P1NC.
Definition at line 30 of file Terme_Source_Acceleration_VEF_Face.cpp.
Member Data Documentation
const Type_info Terme_Source_Acceleration_VEF_Face::info_obj [static]
Reimplemented from Terme_Source_Acceleration.
Reimplemented in Acceleration_QC_VEF_P1NC.
Definition at line 37 of file Terme_Source_Acceleration_VEF_Face.h.
Ref_Zone_Cl_VEFP1B Terme_Source_Acceleration_VEF_Face::la_zone_Cl_VEF_ [private]
Definition at line 50 of file Terme_Source_Acceleration_VEF_Face.h.
Referenced by ajouter(), and associer_zones().
Ref_Zone_VEF_PreP1b Terme_Source_Acceleration_VEF_Face::la_zone_VEF_ [private]
Definition at line 49 of file Terme_Source_Acceleration_VEF_Face.h.
Referenced by ajouter(), and associer_zones().
Ref_Champ_base Terme_Source_Acceleration_VEF_Face::ref_rho_ [private]
Definition at line 53 of file Terme_Source_Acceleration_VEF_Face.h.
Referenced by ajouter(), and associer_champ_rho().
The documentation for this class was generated from the following files:
src/VEF/Sources/Terme_Source_Acceleration_VEF_Face.h
src/VEF/Sources/Terme_Source_Acceleration_VEF_Face.cpp