TRUST: Masse_CoviMAC_Elem Class Reference
Masse_CoviMAC_Elem Class Reference
#include <Masse_CoviMAC_Elem.h>
Public Member Functions
Masse_CoviMAC_Elem ()
~Masse_CoviMAC_Elem ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &)
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
void preparer_calcul ()
DoubleTab & appliquer_impl (DoubleTab &) const
int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, double dt, const tabs_t &semi_impl, int resoudre_en_increments) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Masse_CoviMAC_Elem & self_cast (Objet_U &)
static const Masse_CoviMAC_Elem & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Private Attributes
Ref_Zone_CoviMAC la_zone_CoviMAC
Ref_Zone_Cl_CoviMAC la_zone_Cl_CoviMAC
Detailed Description
Definition at line 37 of file Masse_CoviMAC_Elem.h.
Constructor & Destructor Documentation
Masse_CoviMAC_Elem::Masse_CoviMAC_Elem ()
Definition at line 40 of file Masse_CoviMAC_Elem.cpp.
Masse_CoviMAC_Elem::~Masse_CoviMAC_Elem ()
Definition at line 40 of file Masse_CoviMAC_Elem.cpp.
Member Function Documentation
void Masse_CoviMAC_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, double dt, const tabs_t & semi_impl, int resoudre_en_increments) const [virtual]
Reimplemented from Solveur_Masse_base.
Definition at line 107 of file Masse_CoviMAC_Elem.cpp.
References Equation_base::champ_conserve(), Champ_Inc_base::derivees(), MorEqn::equation(), la_zone_CoviMAC, DoubleVect::line_size(), Zone_dis_base::nb_elem(), Champ_Inc_base::passe(), Zone_VF::porosite_elem(), ref_cast, sub_type, Ref_Zone_CoviMAC::valeur(), Champ_Inc_base::valeurs(), and Zone_VF::volumes().
{
  const Zone_CoviMAC& zone = la_zone_CoviMAC.valeur();
  const Champ_Inc_base& cc = equation().champ_conserve();
  const DoubleTab& present = cc.valeurs(), &passe = cc.passe();
  const DoubleVect& ve = zone.volumes(), &pe = zone.porosite_elem();
  int e, n, N = cc.valeurs().line_size(), ne = zone.nb_elem();
  /* second membre : avec ou sans resolution en increments*/
  for (e = 0; e < ne; e++) for (n = 0; n < N; n++)
      secmem(e, n) += pe(e) * ve(e) * (passe(e, n) - resoudre_en_increments * present(e, n)) / dt;
  /* matrices */
  for (auto &&i_m : matrices) if (cc.derivees().count(i_m.first))
      {
        int M = i_m.first == "pression" && sub_type(Navier_Stokes_std, equation().probleme().equation(0)) ? ref_cast(Navier_Stokes_std, equation().probleme().equation(0)).pression().valeurs().line_size() : N;
        const DoubleTab& der = cc.derivees().at(i_m.first);
        for (e = 0; e < ne; e++) for (n = 0; n < N; n++) (*i_m.second)(N * e + n, M * e + n * (M > 1)) += pe(e) * ve(e) * der(e, n) / dt;
      }
}
DoubleTab & Masse_CoviMAC_Elem::appliquer_impl (DoubleTab & sm) const [virtual]
Implements Solveur_Masse_base.
Definition at line 68 of file Masse_CoviMAC_Elem.cpp.
References Equation_base::champ_conserve(), Champ_Inc_base::derivees(), DoubleTab::dimension_tot(), MorEqn::equation(), la_zone_CoviMAC, Objet_U::le_nom(), DoubleVect::line_size(), Zone_dis_base::nb_elem_tot(), Zone_VF::porosite_elem(), Ref_Zone_CoviMAC::valeur(), and Zone_VF::volumes().
{
  const Zone_CoviMAC& zone = la_zone_CoviMAC.valeur();
  const DoubleVect& ve = zone.volumes(), &pe = zone.porosite_elem();
  const DoubleTab& der = equation().champ_conserve().derivees().at(equation().inconnue().le_nom().getString());
  int e, ne_tot = zone.nb_elem_tot(), n, N = sm.line_size();
  assert(sm.dimension_tot(0) == ne_tot && N == der.line_size());
  for (e = 0; e < ne_tot; e++) for (n = 0; n < N; n++)
      if (der(e, n) > 1e-10) sm(e, n) /= pe(e) * ve(e) * der(e, n);
      else sm(e, n) = 0; //cas d'une evanescence
  return sm;
}
void Masse_CoviMAC_Elem::associer_zone_cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis_base) [virtual]
Implements Solveur_Masse_base.
Definition at line 134 of file Masse_CoviMAC_Elem.cpp.
References la_zone_Cl_CoviMAC, and ref_cast.
{
  la_zone_Cl_CoviMAC = ref_cast(Zone_Cl_CoviMAC, la_zone_Cl_dis_base);
}
void Masse_CoviMAC_Elem::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) [virtual]
Implements Solveur_Masse_base.
Definition at line 129 of file Masse_CoviMAC_Elem.cpp.
References la_zone_CoviMAC, and ref_cast.
{
  la_zone_CoviMAC = ref_cast(Zone_CoviMAC, la_zone_dis_base);
}
Objet_U * Masse_CoviMAC_Elem::cree_instance () [static]
Definition at line 40 of file Masse_CoviMAC_Elem.cpp.
virtual void Masse_CoviMAC_Elem::dimensionner_blocs (matrices_t matrices) [virtual]
Reimplemented from Solveur_Masse_base.
int Masse_CoviMAC_Elem::duplique () const [virtual]
Implements Solveur_Masse_base.
Definition at line 40 of file Masse_CoviMAC_Elem.cpp.
const Type_info * Masse_CoviMAC_Elem::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 40 of file Masse_CoviMAC_Elem.cpp.
int Masse_CoviMAC_Elem::has_interface_blocs () const [inline, virtual]
Reimplemented from Solveur_Masse_base.
Definition at line 51 of file Masse_CoviMAC_Elem.h.
  {
    return 1;
  };
const Type_info * Masse_CoviMAC_Elem::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 40 of file Masse_CoviMAC_Elem.cpp.
void Masse_CoviMAC_Elem::preparer_calcul (void) [virtual]
Reimplemented from Solveur_Masse_base.
Definition at line 63 of file Masse_CoviMAC_Elem.cpp.
References MorEqn::equation(), and Equation_base::init_champ_conserve().
{
  equation().init_champ_conserve();
}
Sortie & Masse_CoviMAC_Elem::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 46 of file Masse_CoviMAC_Elem.cpp.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Masse_CoviMAC_Elem::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 51 of file Masse_CoviMAC_Elem.cpp.
{
  return s ;
}
const Masse_CoviMAC_Elem & Masse_CoviMAC_Elem::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Solveur_Masse_base.
Definition at line 40 of file Masse_CoviMAC_Elem.cpp.
Masse_CoviMAC_Elem & Masse_CoviMAC_Elem::self_cast (Objet_U & r) [static]
Reimplemented from Solveur_Masse_base.
Definition at line 40 of file Masse_CoviMAC_Elem.cpp.
unsigned Masse_CoviMAC_Elem::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 40 of file Masse_CoviMAC_Elem.cpp.
Member Data Documentation
const Type_info Masse_CoviMAC_Elem::info_obj [static]
Reimplemented from Solveur_Masse_base.
Definition at line 40 of file Masse_CoviMAC_Elem.h.
Ref_Zone_Cl_CoviMAC Masse_CoviMAC_Elem::la_zone_Cl_CoviMAC [private]
Definition at line 61 of file Masse_CoviMAC_Elem.h.
Referenced by associer_zone_cl_dis_base().
Ref_Zone_CoviMAC Masse_CoviMAC_Elem::la_zone_CoviMAC [private]
Definition at line 60 of file Masse_CoviMAC_Elem.h.
Referenced by ajouter_blocs(), appliquer_impl(), and associer_zone_dis_base().
The documentation for this class was generated from the following files:
src/CoviMAC/Solveurs/Masse_CoviMAC_Elem.h
src/CoviMAC/Solveurs/Masse_CoviMAC_Elem.cpp