TRUST: Op_Conv_Quick_VDF_Elem Class Reference
Op_Conv_Quick_VDF_Elem Class Reference
class Op_Conv_Quick_VDF_Elem
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VDF
Le champ convecte est scalaire
Le schema de convection est du type Quick
L'iterateur associe est de type Iterateur_VDF_Elem
L'evaluateur associe est de type Eval_Quick_VDF_Elem
#include <Op_Conv_Quick_VDF_Elem.h>
Public Member Functions
~Op_Conv_Quick_VDF_Elem ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Op_Conv_Quick_VDF_Elem ()
constructeur
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
complete l'iterateur et l'evaluateur
void associer_vitesse (const Champ_base &)
associe le champ de vitesse a l'evaluateur
const Champ_Inc_base & vitesse () const
Champ_Inc_base & vitesse ()
void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Conv_Quick_VDF_Elem & self_cast (Objet_U &)
static const
Op_Conv_Quick_VDF_Elem & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Op_Conv_Quick_VDF_Elem (const Iterateur_VDF_base &)
Detailed Description
class Op_Conv_Quick_VDF_Elem
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VDF
Le champ convecte est scalaire
Le schema de convection est du type Quick
L'iterateur associe est de type Iterateur_VDF_Elem
L'evaluateur associe est de type Eval_Quick_VDF_Elem
Definition at line 53 of file Op_Conv_Quick_VDF_Elem.h.
Constructor & Destructor Documentation
Op_Conv_Quick_VDF_Elem::~Op_Conv_Quick_VDF_Elem ()
Definition at line 25 of file Op_Conv_Quick_VDF_Elem.cpp.
Op_Conv_Quick_VDF_Elem::Op_Conv_Quick_VDF_Elem ()
constructeur
Definition at line 87 of file Op_Conv_Quick_VDF_Elem.cpp.
                                               :
  Op_Conv_VDF_base(It_VDF_Elem(Eval_Quick_VDF_Elem)())
{
}
Op_Conv_Quick_VDF_Elem::Op_Conv_Quick_VDF_Elem (const Iterateur_VDF_base & it) [inline, protected]
Definition at line 72 of file Op_Conv_Quick_VDF_Elem.h.
  : Op_Conv_VDF_base(it)
{
}
Member Function Documentation
void Op_Conv_Quick_VDF_Elem::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_transporte) [virtual]
complete l'iterateur et l'evaluateur
< Evaluateur_VDF::associer_zones
< Eval_VDF_Elem::associer_inconnue
Implements Operateur_base.
Definition at line 48 of file Op_Conv_Quick_VDF_Elem.cpp.
References Iterateur_VDF::associer(), Eval_VDF_Elem::associer_inconnue(), Evaluateur_VDF::associer_zones(), Cerr, Joint::epaisseur(), Iterateur_VDF::evaluateur(), Process::exit(), finl, Op_Conv_VDF_base::iter, Zone::joint(), Zone::nb_joints(), Process::nproc(), ref_cast, Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), and Zone_dis_base::zone().
{
  const Zone_VDF& zvdf = ref_cast(Zone_VDF,zone_dis.valeur());
  const Zone_Cl_VDF& zclvdf = ref_cast(Zone_Cl_VDF,zone_cl_dis.valeur());
  const Champ_P0_VDF& inco = ref_cast(Champ_P0_VDF,ch_transporte.valeur());
  iter.associer(zvdf, zclvdf, *this);
  Eval_Quick_VDF_Elem& eval_conv = (Eval_Quick_VDF_Elem&) iter.evaluateur();
  eval_conv.associer_zones(zvdf, zclvdf );          //!< Evaluateur_VDF::associer_zones
  eval_conv.associer_inconnue(inco );        //!< Eval_VDF_Elem::associer_inconnue
  if (Process::nproc()>1 && zvdf.zone().nb_joints() && zvdf.zone().joint(0).epaisseur()<2)
    {
      Cerr << "Overlapping width (given by larg_joint option) of  " << zvdf.zone().joint(0).epaisseur() << finl;
      Cerr << "is not enough for Quick scheme in VDF parallel calculation." << finl;
      Cerr << "Please, partition your mesh with an overlapping width of 2 with larg_joint option." << finl;
      Process::exit();
    }
}
void Op_Conv_Quick_VDF_Elem::associer_vitesse (const Champ_base & ch_vit) [inline, virtual]
associe le champ de vitesse a l'evaluateur
< Eval_Conv_VDF::associer
Implements Operateur_Conv_base.
Definition at line 79 of file Op_Conv_Quick_VDF_Elem.h.
References Eval_Conv_VDF::associer(), Iterateur_VDF::evaluateur(), and Op_Conv_VDF_base::iter.
{
  const Champ_Face& vit = (Champ_Face&) ch_vit;
  Eval_Quick_VDF_Elem& eval_conv = (Eval_Quick_VDF_Elem&) iter.evaluateur();
  eval_conv.associer(vit );                //!< Eval_Conv_VDF::associer
}
Objet_U * Op_Conv_Quick_VDF_Elem::cree_instance () [static]
Definition at line 25 of file Op_Conv_Quick_VDF_Elem.cpp.
void Op_Conv_Quick_VDF_Elem::dimensionner (Matrice_Morse & mat) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 87 of file Op_Conv_Quick_VDF_Elem.h.
References Op_Conv_VDF_base::iter, Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
{
  Op_VDF_Elem::dimensionner(iter.zone(), iter.zone_Cl(), matrice);
}
int Op_Conv_Quick_VDF_Elem::duplique () const [virtual]
Implements Op_Conv_VDF_base.
Definition at line 25 of file Op_Conv_Quick_VDF_Elem.cpp.
const Type_info * Op_Conv_Quick_VDF_Elem::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_VDF_base.
Definition at line 25 of file Op_Conv_Quick_VDF_Elem.cpp.
const Type_info * Op_Conv_Quick_VDF_Elem::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_VDF_base.
Definition at line 25 of file Op_Conv_Quick_VDF_Elem.cpp.
void Op_Conv_Quick_VDF_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 92 of file Op_Conv_Quick_VDF_Elem.h.
References Op_Conv_VDF_base::iter, Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
{
  Op_VDF_Elem::modifier_pour_Cl(iter.zone(), iter.zone_Cl(), matrice, secmem);
}
Sortie & Op_Conv_Quick_VDF_Elem::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Conv_VDF_base.
Definition at line 32 of file Op_Conv_Quick_VDF_Elem.cpp.
{
  return s << que_suis_je() ;
}
Entree & Op_Conv_Quick_VDF_Elem::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Conv_VDF_base.
Definition at line 40 of file Op_Conv_Quick_VDF_Elem.cpp.
{
  return s ;
}
const Op_Conv_Quick_VDF_Elem & Op_Conv_Quick_VDF_Elem::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Conv_VDF_base.
Definition at line 25 of file Op_Conv_Quick_VDF_Elem.cpp.
Op_Conv_Quick_VDF_Elem & Op_Conv_Quick_VDF_Elem::self_cast (Objet_U & r) [static]
Reimplemented from Op_Conv_VDF_base.
Definition at line 25 of file Op_Conv_Quick_VDF_Elem.cpp.
unsigned Op_Conv_Quick_VDF_Elem::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Op_Conv_Quick_VDF_Elem.cpp.
Champ_Inc_base & Op_Conv_Quick_VDF_Elem::vitesse () [virtual]
Implements Op_Conv_VDF_base.
Definition at line 76 of file Op_Conv_Quick_VDF_Elem.cpp.
References Iterateur_VDF::evaluateur(), Op_Conv_VDF_base::iter, and Eval_Conv_VDF::vitesse().
{
  Eval_Quick_VDF_Elem& eval_conv = (Eval_Quick_VDF_Elem&) iter.evaluateur();
  return eval_conv.vitesse();
}
const Champ_Inc_base & Op_Conv_Quick_VDF_Elem::vitesse () const [virtual]
Implements Op_Conv_VDF_base.
Definition at line 70 of file Op_Conv_Quick_VDF_Elem.cpp.
References Iterateur_VDF::evaluateur(), Op_Conv_VDF_base::iter, and Eval_Conv_VDF::vitesse().
{
  Eval_Quick_VDF_Elem& eval_conv = (Eval_Quick_VDF_Elem&) iter.evaluateur();
  return eval_conv.vitesse();
}
Member Data Documentation
const Type_info Op_Conv_Quick_VDF_Elem::info_obj [static]
Reimplemented from Op_Conv_VDF_base.
Definition at line 55 of file Op_Conv_Quick_VDF_Elem.h.
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Op_Conv_Quick_VDF_Elem.h
src/VDF/Operateurs/Op_Conv_Quick_VDF_Elem.cpp