TRUST: VEF_discretisation Class Reference
VEF_discretisation Class Reference
#include <VEF_discretisation.h>
Public Member Functions
VEF_discretisation ()
~VEF_discretisation ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const
Discretisation d'un champ pour le VEF en fonction d'une directive
de discretisation. La directive est un Motcle comme "vitesse", "pression",
"temperature", "champ_elem" (cree un champ de type P0 ...), ...
Cette methode determine le type du champ a creer en fonction du type d'element
et de la directive de discretisation. Elle determine ensuite le nombre de ddl
et fixe l'ensemble des parametres du champ (type, nb_compo, nb_ddl, nb_pas_dt,
nom(s), unite(s), nature du champ et attribue un temps) et associe la Zone_dis au champ.
Voir le code pour avoir la correspondance entre les directives et
le type de champ cree.
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Fonc &champ) const
Idem que VEF_discretisation::discretiser_champ(... , Champ_Inc)
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Don &champ) const
Idem que VEF_discretisation::discretiser_champ(... , Champ_Inc)
void zone_Cl_dis (Zone_dis &z, Zone_Cl_dis &zcl) const
void distance_paroi (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
void proprietes_physiques_fluide_Ostwald (const Zone_dis &, Fluide_Ostwald &, const Navier_Stokes_std &, const Champ_Inc &) const
discretise en VEF le fluide incompressible, donc K e N
void vorticite (Zone_dis &, const Champ_Inc &, Champ_Fonc &) const
void creer_champ_vorticite (const Schema_Temps_base &, const Champ_Inc &, Champ_Fonc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
void critere_Q (const Zone_dis &z, const Zone_Cl_dis &, const Champ_Inc &vitesse, Champ_Fonc &ch) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
void y_plus (const Zone_dis &z, const Zone_Cl_dis &, const Champ_Inc &vitesse, Champ_Fonc &ch) const
void grad_T (const Zone_dis &z, const Zone_Cl_dis &, const Champ_Inc &temperature, Champ_Fonc &ch) const
void grad_u (const Zone_dis &z, const Zone_Cl_dis &, const Champ_Inc &temperature, Champ_Fonc &ch) const
void h_conv (const Zone_dis &z, const Zone_Cl_dis &, const Champ_Inc &temperature, Champ_Fonc &ch, Motcle &nom, int temp_ref) const
void taux_cisaillement (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
void residu (const Zone_dis &, const Champ_Inc &, Champ_Fonc &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static VEF_discretisation & self_cast (Objet_U &)
static const VEF_discretisation & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN.
virtual Entree & readOn (Entree &)
NE FAIT RIEN.
Private Member Functions
void discretiser_champ_fonc_don (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Objet_U &champ) const
Idem que VEF_discretisation::discretiser_champ(... , Champ_Inc)
Traitement commun aux champ_fonc et champ_don.
Cette methode est privee (passage d'un Objet_U pas propre vu
de l'exterieur ...)
void modifier_champ_tabule (const Zone_dis_base &zone_dis, Champ_Fonc_Tabule &ch_tab, const Vect_Ref_Champ_base &ch_inc) const
Detailed Description
Definition at line 48 of file VEF_discretisation.h.
Constructor & Destructor Documentation
VEF_discretisation::VEF_discretisation ()
Definition at line 49 of file VEF_discretisation.cpp.
VEF_discretisation::~VEF_discretisation ()
Definition at line 49 of file VEF_discretisation.cpp.
Member Function Documentation
Objet_U * VEF_discretisation::cree_instance () [static]
Reimplemented in VEFPreP1B, and VEF_1D.
Definition at line 49 of file VEF_discretisation.cpp.
void VEF_discretisation::creer_champ_vorticite (const Schema_Temps_base & , const Champ_Inc & , Champ_Fonc &) const [virtual]
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
Reimplemented from Discret_Thyd.
Definition at line 432 of file VEF_discretisation.cpp.
References Cerr, Objet_U::dimension, Process::exit(), finl, ref_cast, sub_type, Schema_Temps_base::temps_courant(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Champ_Q1NC::zone_dis_base(), and Champ_P1NC::zone_dis_base().
{
  if (sub_type(Champ_P1NC,ch_vitesse.valeur()))
    {
      ch.typer("Rotationnel_Champ_P1NC");
      const Champ_P1NC& vit = ref_cast(Champ_P1NC,ch_vitesse.valeur());
      const Zone_VEF& zone_VEF = ref_cast(Zone_VEF,vit.zone_dis_base());
      Rotationnel_Champ_P1NC& ch_W = ref_cast(Rotationnel_Champ_P1NC,ch.valeur());
      ch_W.associer_zone_dis_base(zone_VEF);
      ch_W.associer_champ(vit);
      ch_W.nommer("vorticite");
      if (dimension == 2)
        ch_W.fixer_nb_comp(1);
      else
        {
          ch_W.fixer_nb_comp(dimension);
          ch_W.fixer_nom_compo(0, "vorticitex");
          ch_W.fixer_nom_compo(1, "vorticitey");
          ch_W.fixer_nom_compo(2, "vorticitez");
        }
      ch_W.fixer_nb_valeurs_nodales(zone_VEF.nb_elem());
      ch_W.fixer_unite("s-1");
      ch_W.changer_temps(sch.temps_courant());
    }
  else if (sub_type(Champ_Q1NC,ch_vitesse.valeur()))
    {
      ch.typer("Rotationnel_Champ_Q1NC");
      const Champ_Q1NC& vit = ref_cast(Champ_Q1NC,ch_vitesse.valeur());
      const Zone_VEF& zone_VEF = ref_cast(Zone_VEF,vit.zone_dis_base());
      Rotationnel_Champ_Q1NC& ch_W = ref_cast(Rotationnel_Champ_Q1NC,ch.valeur());
      ch_W.associer_zone_dis_base(zone_VEF);
      ch_W.associer_champ(vit);
      ch_W.nommer("vorticite");
      if (dimension == 2)
        ch_W.fixer_nb_comp(1);
      else
        {
          ch_W.fixer_nb_comp(dimension);
          ch_W.fixer_nom_compo(0, "vorticitex");
          ch_W.fixer_nom_compo(1, "vorticitey");
          ch_W.fixer_nom_compo(2, "vorticitez");
        }
      ch_W.fixer_nb_valeurs_nodales(zone_VEF.nb_elem());
      ch_W.fixer_unite("s-1");
      ch_W.changer_temps(sch.temps_courant());
    }
  else
    {
      Cerr << "Pb dans le typage des elements dans VEF_discretisation::creer_champ_vorticite" << finl;
      exit();
    }
}
void VEF_discretisation::critere_Q (const Zone_dis & , const Zone_Cl_dis & , const Champ_Inc & , Champ_Fonc &) const [virtual]
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
Reimplemented from Discret_Thyd.
Definition at line 565 of file VEF_discretisation.cpp.
References Critere_Q_Champ_P1NC::associer_champ(), Champ_Fonc_P0_VEF::associer_zone_dis_base(), Cerr, Champ_base::changer_temps(), finl, Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Field_base::nommer(), ref_cast, Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Zone_dis_base::valeur(), and Deriv_Champ_Inc_base::valeur().
{
// On passe la zcl, pour qu'il n y ait qu une methode qqsoit la dsicretisation
// mais on ne s'en sert pas!!!
  Cerr << "Discretisation du critere Q " << finl;
  const Champ_P1NC& vit = ref_cast(Champ_P1NC,ch_vitesse.valeur());
  const Zone_VEF& zone_vef=ref_cast(Zone_VEF, z.valeur());
  ch.typer("Critere_Q_Champ_P1NC");
  Critere_Q_Champ_P1NC& ch_cQ=ref_cast(Critere_Q_Champ_P1NC,ch.valeur());
  ch_cQ.associer_zone_dis_base(zone_vef);
  ch_cQ.associer_champ(vit);
  ch_cQ.nommer("Critere_Q");
  ch_cQ.fixer_nb_comp(1);
  ch_cQ.fixer_nb_valeurs_nodales(zone_vef.nb_elem());
  ch_cQ.fixer_unite("s-2");
  ch_cQ.changer_temps(ch_vitesse.temps());
}
void VEF_discretisation::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc & champ, const Nom & sous_type = nom_vide) const [virtual]
Discretisation d'un champ pour le VEF en fonction d'une directive
de discretisation. La directive est un Motcle comme "vitesse", "pression",
"temperature", "champ_elem" (cree un champ de type P0 ...), ...
Cette methode determine le type du champ a creer en fonction du type d'element
et de la directive de discretisation. Elle determine ensuite le nombre de ddl
et fixe l'ensemble des parametres du champ (type, nb_compo, nb_ddl, nb_pas_dt,
nom(s), unite(s), nature du champ et attribue un temps) et associe la Zone_dis au champ.
Voir le code pour avoir la correspondance entre les directives et
le type de champ cree.
< Choix standard pour la vitesse
< Choix standard pour la pression
< Choix standard pour la temperature
< Le type de champ obtenu en calculant div v
< Le type de champ obtenu en calculant grad P
< Creer un champ aux elements (de type P0)
< Creer un champ aux sommets (type P1)
< Valeur par defaut du nombre de composantes
Reimplemented from Discretisation_base.
Reimplemented in VEFPreP1B.
Definition at line 73 of file VEF_discretisation.cpp.
References Cerr, Discretisation_base::creer_champ(), Discretisation_base::demande_description, Objet_U::dimension, Process::exit(), finl, Field_base::fixer_nature_du_champ(), Field_base::fixer_noms_compo(), Field_base::fixer_unites(), multi_scalaire, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone_dis_base::nb_som(), Objet_U::que_suis_je(), ref_cast, Motcles::search(), sub_type, Zone_VEF::type_elem(), Deriv_Champ_Inc_base::valeur(), and Deriv_Elem_VEF_base::valeur().
Referenced by discretiser_champ_fonc_don(), and residu().
{
  const Zone_VEF& zone_vef = ref_cast(Zone_VEF, z);
  Motcles motcles(7);
  motcles[0] = "vitesse";     //!< Choix standard pour la vitesse
  motcles[1] = "pression";    //!< Choix standard pour la pression
  motcles[2] = "temperature"; //!< Choix standard pour la temperature
  motcles[3] = "divergence_vitesse"; //!< Le type de champ obtenu en calculant div v
  motcles[4] = "gradient_pression";  //!< Le type de champ obtenu en calculant grad P
  motcles[5] = "champ_elem";    //!< Creer un champ aux elements (de type P0)
  motcles[6] = "champ_sommets"; //!< Creer un champ aux sommets (type P1)
// Le type de champ de vitesse depend du type d'element :
  Nom type_champ_vitesse;
  if (sub_type(Tri_VEF, zone_vef.type_elem().valeur())
      || sub_type(Tetra_VEF,zone_vef.type_elem().valeur()))
    type_champ_vitesse = "Champ_P1NC";
  else if (sub_type(Quadri_VEF,zone_vef.type_elem().valeur())
           || sub_type(Hexa_VEF,zone_vef.type_elem().valeur()))
    type_champ_vitesse = "Champ_Q1NC";
  else
    {
      Cerr << "VEF_discretisation::discretiser_champ :\n L'element geometrique ";
      Cerr << zone_vef.type_elem().valeur().que_suis_je();
      Cerr << " n'est pas supporte." << finl;
      exit();
    }
  Nom type;
  int default_nb_comp = 0; //!< Valeur par defaut du nombre de composantes
  int rang = motcles.search(directive);
  switch(rang)
    {
    case 0:
      type = type_champ_vitesse;
      default_nb_comp = dimension;
      break;
    case 1:
      type = "Champ_P0_VEF";
      default_nb_comp = 1;
      break;
    case 2:
      type = type_champ_vitesse;
      default_nb_comp = 1;
      break;
    case 3:
      type = "Champ_P0_VEF";
      default_nb_comp = 1;
      break;
    case 4:
      type = type_champ_vitesse;
      default_nb_comp = dimension;
      break;
    case 5:
      type = "Champ_P0_VEF";
      default_nb_comp = 1;
      break;
    case 6:
      type = "Champ_P1_VEF";
      default_nb_comp = 1;
      break;
    default:
      assert(rang < 0);
      break;
    }
  if (directive == demande_description)
    Cerr << "VEF_discretisation : " << motcles;
// Si on n'a pas compris la directive (ou si c'est une demande_description)
// alors on appelle l'ancetre :
  if (rang < 0)
    {
      Discret_Thyd::discretiser_champ(directive, z,
                                      nature, noms, unites,
                                      nb_comp, nb_pas_dt, temps, champ);
      return;
    }
// Calcul du nombre de ddl
  int nb_ddl = 0;
  if (type == "Champ_P0_VEF")
    nb_ddl = z.nb_elem();
  else if (type == type_champ_vitesse)
    nb_ddl = zone_vef.nb_faces();
  else if (type == "Champ_P1_VEF")
    nb_ddl = zone_vef.nb_som();
  else
    assert(0);
  if (nb_comp < 0)
    nb_comp = default_nb_comp;
  assert(nb_comp > 0);
  creer_champ(champ, z, type, noms[0], unites[0], nb_comp, nb_ddl, nb_pas_dt, temps,
              directive, que_suis_je());
  if (nature == multi_scalaire)
    {
      champ.valeur().fixer_nature_du_champ(nature);
      champ.valeur().fixer_unites(unites);
      champ.valeur().fixer_noms_compo(noms);
    }
}
void VEF_discretisation::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Champ_Fonc & champ) const [virtual]
Idem que VEF_discretisation::discretiser_champ(... , Champ_Inc)
Reimplemented from Discretisation_base.
Reimplemented in VEFPreP1B.
Definition at line 185 of file VEF_discretisation.cpp.
References discretiser_champ_fonc_don().
{
  discretiser_champ_fonc_don(directive, z,
                             nature, noms, unites,
                             nb_comp, temps, champ);
}
void VEF_discretisation::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Champ_Don & champ) const [virtual]
Idem que VEF_discretisation::discretiser_champ(... , Champ_Inc)
Reimplemented from Discretisation_base.
Reimplemented in VEFPreP1B.
Definition at line 199 of file VEF_discretisation.cpp.
References discretiser_champ_fonc_don().
{
  discretiser_champ_fonc_don(directive, z,
                             nature, noms, unites,
                             nb_comp, temps, champ);
}
void VEF_discretisation::discretiser_champ_fonc_don (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Objet_U & champ) const [private]
Idem que VEF_discretisation::discretiser_champ(... , Champ_Inc)
Traitement commun aux champ_fonc et champ_don.
Cette methode est privee (passage d'un Objet_U pas propre vu
de l'exterieur ...)
< Choix standard pour la pression
< Choix standard pour la temperature
< Le type de champ obtenu en calculant div v
< Creer un champ aux elements (de type P0)
< Choix standard pour la vitesse
< Le type de champ obtenu en calculant grad P
< Creer un champ aux sommets
< Creer un champ aux faces
< Valeur par defaut du nombre de composantes
Reimplemented in VEFPreP1B.
Definition at line 215 of file VEF_discretisation.cpp.
References Cerr, Discretisation_base::creer_champ(), Discretisation_base::demande_description, Objet_U::dimension, discretiser_champ(), Process::exit(), finl, Field_base::fixer_nature_du_champ(), Field_base::fixer_noms_compo(), Field_base::fixer_unites(), multi_scalaire, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone_dis_base::nb_som(), Objet_U::que_suis_je(), ref_cast, Motcles::search(), sub_type, Zone_VEF::type_elem(), Zone::type_elem(), Deriv_Champ_Fonc_base::valeur(), Deriv_Elem_VEF_base::valeur(), Deriv_Elem_geom_base::valeur(), and Zone_dis_base::zone().
Referenced by discretiser_champ().
{
// Deux pointeurs pour acceder facilement au champ_don ou au champ_fonc,
// suivant le type de l'objet champ.
  Champ_Fonc * champ_fonc = 0;
  Champ_Don * champ_don = 0;
  if (sub_type(Champ_Fonc, champ))
    champ_fonc = & ref_cast(Champ_Fonc, champ);
  else
    champ_don  = & ref_cast(Champ_Don, champ);
  const Zone_VEF& zone_vef = ref_cast(Zone_VEF, z);
  Motcles motcles(8);
  motcles[0] = "pression";    //!< Choix standard pour la pression
  motcles[1] = "temperature"; //!< Choix standard pour la temperature
  motcles[2] = "divergence_vitesse"; //!< Le type de champ obtenu en calculant div v
  motcles[3] = "champ_elem";  //!< Creer un champ aux elements (de type P0)
  motcles[4] = "vitesse";     //!< Choix standard pour la vitesse
  motcles[5] = "gradient_pression";  //!< Le type de champ obtenu en calculant grad P
  motcles[6] = "champ_sommets"; //!< Creer un champ aux sommets
  motcles[7] = "champ_face"; //!< Creer un champ aux faces
// Le type de champ de vitesse depend du type d'element :
  Nom type_champ_vitesse, type_champ_sommets;
  Nom type_elem_zone = zone_vef.zone().type_elem().valeur().que_suis_je();
  if (Motcle(type_elem_zone)!="Segment")
    {
      const Elem_VEF_base& elem_vef = zone_vef.type_elem().valeur();
      if (sub_type(Tri_VEF, elem_vef) || sub_type(Tetra_VEF, elem_vef))
        {
          type_champ_vitesse = "Champ_Fonc_P1NC";
          type_champ_sommets = "Champ_Fonc_P1_VEF";
        }
      else if (sub_type(Quadri_VEF, elem_vef) || sub_type(Hexa_VEF, elem_vef))
        {
          type_champ_vitesse = "Champ_Fonc_Q1NC";
          type_champ_sommets = "Champ_Fonc_Q1_VEF";
        }
      else
        {
          Cerr << "VEF_discretisation::discretiser_champ :\n L'element geometrique ";
          Cerr << elem_vef.que_suis_je();
          Cerr << " n'est pas supporte." << finl;
          exit();
        }
    }
  Nom type;
  int default_nb_comp = 0; //!< Valeur par defaut du nombre de composantes
  int rang = motcles.search(directive);
  switch(rang)
    {
    case 0:
      type = "Champ_Fonc_P0_VEF";
      default_nb_comp = 1;
      break;
    case 1:
      type = type_champ_vitesse;
      default_nb_comp = 1;
      break;
    case 2:
      type = "Champ_Fonc_P0_VEF";
      default_nb_comp = 1;
      break;
    case 3:
      type = "Champ_Fonc_P0_VEF";
      default_nb_comp = 1;
      break;
    case 4:
      type = type_champ_vitesse;
      default_nb_comp = dimension;
      break;
    case 5:
      type = type_champ_vitesse;
      default_nb_comp = dimension;
      break;
    case 6:
      type = type_champ_sommets;
      default_nb_comp = 1;
      break;
    case 7:
      type = type_champ_vitesse;
      default_nb_comp = 1;
      break;
    default:
      assert(rang < 0);
      break;
    }
  if (directive == demande_description)
    Cerr << "VEF_discretisation : " << motcles;
// Si on n'a pas compris la directive (ou si c'est une demande_description)
// alors on appelle l'ancetre :
  if (rang < 0)
    {
      if (champ_fonc)
        Discret_Thyd::discretiser_champ(directive, z, nature, noms, unites,
                                        nb_comp, temps, *champ_fonc);
      else
        Discret_Thyd::discretiser_champ(directive, z, nature, noms, unites,
                                        nb_comp, temps, *champ_don);
      return;
    }
// Calcul du nombre de ddl
  int nb_ddl = 0;
  if (type == "Champ_Fonc_P0_VEF")      nb_ddl = z.nb_elem();
  else if (type == type_champ_vitesse)  nb_ddl = zone_vef.nb_faces();
  else if ((type == "Champ_Fonc_P1_VEF") || (type == "Champ_Fonc_Q1_VEF")) nb_ddl = zone_vef.nb_som();
  else assert(0);
  if (nb_comp < 0)
    nb_comp = default_nb_comp;
  assert(nb_comp > 0);
  if (champ_fonc)
    creer_champ(*champ_fonc, z, type, noms[0], unites[0], nb_comp, nb_ddl, temps,
                directive, que_suis_je());
  else
    creer_champ(*champ_don, z, type, noms[0], unites[0], nb_comp, nb_ddl, temps,
                directive, que_suis_je());
  if ((nature == multi_scalaire) && (champ_fonc))
    {
      champ_fonc->valeur().fixer_nature_du_champ(nature);
      champ_fonc->valeur().fixer_unites(unites);
      champ_fonc->valeur().fixer_noms_compo(noms);
    }
  else if ((nature == multi_scalaire) && (champ_don))
    {
      Cerr<<"There is no field of type Champ_Don with a multi_scalaire nature."<<finl;
      exit();
    }
}
void VEF_discretisation::distance_paroi (const Schema_Temps_base & sch, Zone_dis & z, Champ_Fonc & ch) const
Definition at line 360 of file VEF_discretisation.cpp.
References Champ_Fonc_P0_VEF::associer_zone_dis_base(), Cerr, Champ_base::changer_temps(), finl, Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Zone_dis_base::nb_elem(), Field_base::nommer(), ref_cast, Schema_Temps_base::temps_courant(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  Cerr << "Discretisation de la distance paroi" << finl;
  Zone_VEF& zone_vef=ref_cast(Zone_VEF, z.valeur());
  ch.typer("Champ_Fonc_P0_VEF");
  Champ_Fonc_P0_VEF& ch_dist_paroi=ref_cast(Champ_Fonc_P0_VEF,ch.valeur());
  ch_dist_paroi.associer_zone_dis_base(zone_vef);
  ch_dist_paroi.nommer("distance_paroi");
  ch_dist_paroi.fixer_nb_comp(1);
  ch_dist_paroi.fixer_nb_valeurs_nodales(zone_vef.nb_elem());
  ch_dist_paroi.fixer_unite("m");
  ch_dist_paroi.changer_temps(sch.temps_courant());
}
int VEF_discretisation::duplique () const [virtual]
Implements Discret_Thyd.
Reimplemented in VEFPreP1B, and VEF_1D.
Definition at line 49 of file VEF_discretisation.cpp.
const Type_info * VEF_discretisation::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Discret_Thyd.
Reimplemented in VEFPreP1B, and VEF_1D.
Definition at line 49 of file VEF_discretisation.cpp.
void VEF_discretisation::grad_T (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & temperature, Champ_Fonc & ch) const [virtual]
Reimplemented from Discret_Thyd.
Definition at line 645 of file VEF_discretisation.cpp.
References Cerr, Discretisation_base::creer_champ(), Objet_U::dimension, finl, Zone_dis_base::nb_elem(), ref_cast, Champ_Inc::temps(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Champ_Fonc_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  Cerr << "Discretisation de gradient_temperature" << finl;
  const Zone_VEF& zone_vef=ref_cast(Zone_VEF, z.valeur());
  creer_champ(ch, zone_vef, "gradient_temperature_Champ_P1NC",
              "gradient_temperature", "K/m", dimension,
              zone_vef.nb_elem(),
              ch_temperature.temps()
             );
  grad_T_Champ_P1NC& ch_gt=ref_cast(grad_T_Champ_P1NC,ch.valeur());
  const Champ_P1NC& temp = ref_cast(Champ_P1NC,ch_temperature.valeur());
  const Zone_Cl_VEF& zone_cl_vef=ref_cast(Zone_Cl_VEF, zcl.valeur());
  ch_gt.associer_zone_Cl_dis_base(zone_cl_vef);
  ch_gt.associer_champ(temp);
}
void VEF_discretisation::grad_u (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & temperature, Champ_Fonc & ch) const [virtual]
< du/dx
< du/dy
< dv/dx
< dv/dy
< du/dx
< du/dy
< du/dz
< dv/dx
< dv/dy
< dv/dz
< dw/dx
< dw/dy
< dw/dz
Reimplemented from Discret_Thyd.
Definition at line 602 of file VEF_discretisation.cpp.
References grad_U_Champ_P1NC::associer_champ(), grad_U_Champ_P1NC::associer_zone_Cl_dis_base(), Champ_Fonc_P0_VEF::associer_zone_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nature_du_champ(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Field_base::nommer(), ref_cast, Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), Deriv_Champ_Inc_base::valeur(), and vectoriel.
{
  const Champ_P1NC& vit = ref_cast( Champ_P1NC, ch_vitesse.valeur( ) );
  const Zone_VEF& zone_vef=ref_cast( Zone_VEF, z.valeur( ) );
  const int nb_comp = dimension*dimension;
  const Zone_Cl_VEF& zone_cl_vef=ref_cast( Zone_Cl_VEF, zcl.valeur( ) );
  ch.typer("grad_u_Champ_P1NC");
  grad_U_Champ_P1NC& ch_grad_u=ref_cast( grad_U_Champ_P1NC, ch.valeur( ) );
  ch_grad_u.fixer_nature_du_champ( vectoriel );
  ch_grad_u.associer_zone_dis_base( zone_vef );
  ch_grad_u.associer_zone_Cl_dis_base( zone_cl_vef );
  ch_grad_u.associer_champ( vit );
  ch_grad_u.nommer("gradient_vitesse");
  ch_grad_u.fixer_nb_comp( nb_comp );
  ch_grad_u.fixer_nb_valeurs_nodales( zone_vef.nb_elem( ) );
  ch_grad_u.fixer_unite("s-1");
  ch_grad_u.changer_temps( ch_vitesse.temps( ) );
  if (dimension == 2)
    {
      ch_grad_u.fixer_nom_compo(0,"dUdX"); //!< du/dx
      ch_grad_u.fixer_nom_compo(1,"dUdY"); //!< du/dy
      ch_grad_u.fixer_nom_compo(2,"dVdX"); //!< dv/dx
      ch_grad_u.fixer_nom_compo(3,"dVdY"); //!< dv/dy
    }
  else
    {
      ch_grad_u.fixer_nom_compo(0,"dUdX"); //!< du/dx
      ch_grad_u.fixer_nom_compo(1,"dUdY"); //!< du/dy
      ch_grad_u.fixer_nom_compo(2,"dUdZ"); //!< du/dz
      ch_grad_u.fixer_nom_compo(3,"dVdX"); //!< dv/dx
      ch_grad_u.fixer_nom_compo(4,"dVdY"); //!< dv/dy
      ch_grad_u.fixer_nom_compo(5,"dVdZ"); //!< dv/dz
      ch_grad_u.fixer_nom_compo(6,"dWdX"); //!< dw/dx
      ch_grad_u.fixer_nom_compo(7,"dWdY"); //!< dw/dy
      ch_grad_u.fixer_nom_compo(8,"dWdZ"); //!< dw/dz
    }
}
void VEF_discretisation::h_conv (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & temperature, Champ_Fonc & ch, Motcle & nom, int temp_ref) const [virtual]
Reimplemented from Discret_Thyd.
Definition at line 663 of file VEF_discretisation.cpp.
References h_conv_Champ_P1NC::associer_champ(), h_conv_Champ_P1NC::associer_zone_Cl_dis_base(), Champ_Fonc_P0_VEF::associer_zone_dis_base(), Cerr, Champ_base::changer_temps(), finl, Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Field_base::nommer(), ref_cast, h_conv_Champ_P1NC::temp_ref(), Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), and Deriv_Champ_Inc_base::valeur().
{
  Cerr << "Discretisation de h_conv" << finl;
  const Champ_P1NC& temp = ref_cast(Champ_P1NC,ch_temperature.valeur());
  const Zone_VEF& zone_vef=ref_cast(Zone_VEF, z.valeur());
  const Zone_Cl_VEF& zone_cl_vef=ref_cast(Zone_Cl_VEF, zcl.valeur());
  ch.typer("h_conv_Champ_P1NC");
  h_conv_Champ_P1NC& ch_gt=ref_cast(h_conv_Champ_P1NC,ch.valeur());
  ch_gt.associer_zone_dis_base(zone_vef);
  ch_gt.associer_zone_Cl_dis_base(zone_cl_vef);
  ch_gt.associer_champ(temp);
  ch_gt.temp_ref()=temp_ref;
  ch_gt.nommer(nom);
  ch_gt.fixer_nb_comp(1);
  ch_gt.fixer_nb_valeurs_nodales(zone_vef.nb_elem());
  ch_gt.fixer_unite("W/m2.K");
  ch_gt.changer_temps(ch_temperature.temps());
}
const Type_info * VEF_discretisation::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Discret_Thyd.
Reimplemented in VEFPreP1B, and VEF_1D.
Definition at line 49 of file VEF_discretisation.cpp.
void VEF_discretisation::modifier_champ_tabule (const Zone_dis_base & zone_dis, Champ_Fonc_Tabule & ch_tab, const Vect_Ref_Champ_base & ch_inc) const [private, virtual]
< We give a name to this field, help for debug
Reimplemented from Discretisation_base.
Definition at line 698 of file VEF_discretisation.cpp.
References Champ_Fonc_Tabule_P0_VEF::associer_param(), Champ_Fonc_P0_VEF::associer_zone_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Champ_Fonc_Tabule::le_champ_tabule_discretise(), Field_base::le_nom(), Field_base::nb_comp(), Zone_dis_base::nb_elem(), Field_base::nommer(), ref_cast, Champ_Fonc_Tabule::table(), Deriv_::typer(), valeur(), and Deriv_Champ_Fonc_base::valeur().
{
  le_champ_tabule.le_champ_tabule_discretise().typer("Champ_Fonc_Tabule_P0_VEF");
  Champ_Fonc_Tabule_P0_VEF& le_champ_tabule_dis = ref_cast(Champ_Fonc_Tabule_P0_VEF,le_champ_tabule.le_champ_tabule_discretise().valeur());
  le_champ_tabule_dis.associer_zone_dis_base(zone_dis);
  le_champ_tabule_dis.associer_param(ch_inc,le_champ_tabule.table());
  le_champ_tabule_dis.nommer(le_champ_tabule.le_nom()); //!< We give a name to this field, help for debug
  le_champ_tabule_dis.fixer_nb_comp(le_champ_tabule.nb_comp());
  le_champ_tabule_dis.fixer_nb_valeurs_nodales(zone_dis.nb_elem());
  le_champ_tabule_dis.changer_temps(ch_inc[0].valeur().temps());
}
Sortie & VEF_discretisation::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Discret_Thyd.
Reimplemented in VEFPreP1B, and VEF_1D.
Definition at line 58 of file VEF_discretisation.cpp.
{
  return s ;
}
void VEF_discretisation::proprietes_physiques_fluide_Ostwald (const Zone_dis & z, Fluide_Ostwald & le_fluide, const Navier_Stokes_std & eqn_hydr, const Champ_Inc & ch_temper) const [virtual]
discretise en VEF le fluide incompressible, donc K e N
Reimplemented from Discret_Thyd.
Definition at line 518 of file VEF_discretisation.cpp.
References Champ_Ostwald_VEF::associer_champ(), Champ_Ostwald_VEF::associer_eqn(), Champ_Ostwald::associer_fluide(), Champ_Ostwald_VEF::associer_zone_dis_base(), Cerr, Champ_base::changer_temps(), finl, Field_base::fixer_nb_comp(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Navier_Stokes_std::inconnue(), Zone_dis_base::nb_elem(), ref_cast, Champ_base::temps(), Deriv_::typer(), Deriv_Zone_dis_base::valeur(), and Fluide_base::viscosite_dynamique().
{
  Cerr << "Discretisation VEF du fluide_Ostwald" << finl;
  const Zone_VEF& zone_vef=ref_cast(Zone_VEF, z.valeur());
  const Champ_Inc& ch_vitesse = eqn_hydr.inconnue();
  const Champ_P1NC& vit = ref_cast(Champ_P1NC,ch_vitesse.valeur());
  Champ_Don& mu = le_fluide.viscosite_dynamique();
// mu est toujours un champ_Ostwald_VEF , il faut toujours faire ce qui suit
  mu.typer("Champ_Ostwald_VEF");
  Champ_Ostwald_VEF& ch_mu = ref_cast(Champ_Ostwald_VEF,mu.valeur());
  Cerr<<"associe zonedisbase VEF"<<finl;
  ch_mu.associer_zone_dis_base(zone_vef);
  ch_mu.associer_fluide(le_fluide);
  ch_mu.associer_champ(vit);
  ch_mu.associer_eqn(eqn_hydr);
  Cerr<<"associations finies zone dis base, fluide, champ VEF"<<finl;
  ch_mu.fixer_nb_comp(1);
  Cerr<<"fait fixer_nb_valeurs_nodales"<<finl;
  Cerr<<"nb_valeurs_nodales VEF = "<<zone_vef.nb_elem()<<finl;
  ch_mu.fixer_nb_valeurs_nodales(zone_vef.nb_elem());
  Cerr<<"fait changer_temps"<<finl;
  ch_mu.changer_temps(vit.temps());
  Cerr<<"mu VEF est discretise "<<finl;
}
Entree & VEF_discretisation::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Discret_Thyd.
Reimplemented in VEFPreP1B, and VEF_1D.
Definition at line 53 of file VEF_discretisation.cpp.
{
  return s ;
}
void VEF_discretisation::residu (const Zone_dis & z, const Champ_Inc & ch_inco, Champ_Fonc & champ) const [virtual]
Reimplemented from Discretisation_base.
Definition at line 710 of file VEF_discretisation.cpp.
References Cerr, discretiser_champ(), finl, O_U_Ptr::le_nom(), DoubleVect::line_size(), ref_cast, Champ_Inc::temps(), Deriv_Champ_Fonc_base::valeur(), Deriv_Zone_dis_base::valeur(), and Champ_Inc::valeurs().
{
  Nom ch_name(ch_inco.le_nom());
  ch_name += "_residu";
  Cerr << "Discretization of " << ch_name << finl;
  const Zone_VEF& zone_vef = ref_cast( Zone_VEF, z.valeur( ) );
  int nb_comp =ch_inco.valeurs().line_size();
  Discretisation_base::discretiser_champ("champ_face",zone_vef, ch_name,"units_not_defined", nb_comp, ch_inco.temps(), champ);
  Champ_Fonc_base& ch_fonc = ref_cast(Champ_Fonc_base,champ.valeur());
  DoubleTab& tab=ch_fonc.valeurs();
  tab = -10000.0 ;
  Cerr << "[Information] Discretisation_base::residu : the residue is set to -10000.0 at initial time" <<finl;
}
VEF_discretisation & VEF_discretisation::self_cast (Objet_U & r) [static]
Reimplemented from Discret_Thyd.
Reimplemented in VEFPreP1B, and VEF_1D.
Definition at line 49 of file VEF_discretisation.cpp.
const VEF_discretisation & VEF_discretisation::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Discret_Thyd.
Reimplemented in VEFPreP1B, and VEF_1D.
Definition at line 49 of file VEF_discretisation.cpp.
unsigned VEF_discretisation::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in VEFPreP1B, and VEF_1D.
Definition at line 49 of file VEF_discretisation.cpp.
void VEF_discretisation::taux_cisaillement (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & ch_vitesse, Champ_Fonc & champ) const [virtual]
Reimplemented from Discret_Thyd.
Definition at line 682 of file VEF_discretisation.cpp.
References Taux_cisaillement_P0_VEF::associer_champ(), Champ_Fonc_P0_VEF::associer_zone_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Zone_dis_base::nb_elem(), Field_base::nommer(), ref_cast, Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Inc_base::valeur(), Deriv_Champ_Fonc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  const Zone_VEF& zone_vef=ref_cast(Zone_VEF, z.valeur());
  const Zone_Cl_VEF& zone_cl_vef=ref_cast(Zone_Cl_VEF, zcl.valeur());
  champ.typer("Taux_cisaillement_P0_VEF");
  Taux_cisaillement_P0_VEF& ch=ref_cast(Taux_cisaillement_P0_VEF,champ.valeur());
  ch.associer_zone_dis_base(zone_vef);
  const Champ_P1NC& vit = ref_cast(Champ_P1NC, ch_vitesse.valeur());
  ch.associer_champ(vit, zone_cl_vef);
  ch.nommer("Taux_cisaillement");
  ch.fixer_nb_comp(1);
  ch.fixer_nb_valeurs_nodales(zone_vef.nb_elem());
  ch.fixer_unite("s-1");
  ch.changer_temps(ch_vitesse.temps());
}
void VEF_discretisation::vorticite (Zone_dis & z, const Champ_Inc & ch_vitesse, Champ_Fonc & ch) const
Definition at line 377 of file VEF_discretisation.cpp.
References Cerr, Objet_U::dimension, Process::exit(), finl, Zone_dis_base::nb_elem(), ref_cast, sub_type, Champ_Inc::temps(), Zone_VEF::type_elem(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Elem_VEF_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  Cerr << "Discretisation de la vorticite " << finl;
  const Zone_VEF& zone_VEF=ref_cast(Zone_VEF, z.valeur());
  if (sub_type(Tri_VEF,zone_VEF.type_elem().valeur()) || sub_type(Tetra_VEF,zone_VEF.type_elem().valeur()))
    {
      ch.typer("Rotationnel_Champ_P1NC");
      const Champ_P1NC& vit = ref_cast(Champ_P1NC,ch_vitesse.valeur());
      Rotationnel_Champ_P1NC& ch_W=ref_cast(Rotationnel_Champ_P1NC,ch.valeur());
      ch_W.associer_zone_dis_base(zone_VEF);
      ch_W.associer_champ(vit);
      ch_W.nommer("vorticite");
      if (dimension == 2)
        ch_W.fixer_nb_comp(1);
      else
        {
          ch_W.fixer_nb_comp(dimension);
          ch_W.fixer_nom_compo(0,"vorticitex");
          ch_W.fixer_nom_compo(1,"vorticitey");
          ch_W.fixer_nom_compo(2,"vorticitez");
        }
      ch_W.fixer_nb_valeurs_nodales(zone_VEF.nb_elem());
      ch_W.fixer_unite("s-1");
      ch_W.changer_temps(ch_vitesse.temps());
    }
  else if (sub_type(Quadri_VEF,zone_VEF.type_elem().valeur()) || sub_type(Hexa_VEF,zone_VEF.type_elem().valeur()))
    {
      ch.typer("Rotationnel_Champ_Q1NC");
      const Champ_Q1NC& vit = ref_cast(Champ_Q1NC,ch_vitesse.valeur());
      Rotationnel_Champ_Q1NC& ch_W=ref_cast(Rotationnel_Champ_Q1NC,ch.valeur());
      ch_W.associer_zone_dis_base(zone_VEF);
      ch_W.associer_champ(vit);
      ch_W.nommer("vorticite");
      if (dimension == 2)
        ch_W.fixer_nb_comp(1);
      else
        {
          ch_W.fixer_nb_comp(dimension);
          ch_W.fixer_nom_compo(0,"vorticitex");
          ch_W.fixer_nom_compo(1,"vorticitey");
          ch_W.fixer_nom_compo(2,"vorticitez");
        }
      ch_W.fixer_nb_valeurs_nodales(zone_VEF.nb_elem());
      ch_W.fixer_unite("s-1");
      ch_W.changer_temps(ch_vitesse.temps());
    }
  else
    {
      Cerr << "Pb dans le typage des elements dans VEF_discretisation::vorticite" << finl;
      exit();
    }
}
void VEF_discretisation::y_plus (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & vitesse, Champ_Fonc & ch) const [virtual]
Reimplemented from Discret_Thyd.
Definition at line 584 of file VEF_discretisation.cpp.
References Y_plus_Champ_P1NC::associer_champ(), Y_plus_Champ_P1NC::associer_zone_Cl_dis_base(), Champ_Fonc_P0_VEF::associer_zone_dis_base(), Cerr, Champ_base::changer_temps(), finl, Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Field_base::nommer(), ref_cast, Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), and Deriv_Champ_Inc_base::valeur().
{
  Cerr << "Discretisation de y_plus" << finl;
  const Champ_P1NC& vit = ref_cast(Champ_P1NC,ch_vitesse.valeur());
  const Zone_VEF& zone_vef=ref_cast(Zone_VEF, z.valeur());
  const Zone_Cl_VEF& zone_cl_vef=ref_cast(Zone_Cl_VEF, zcl.valeur());
  ch.typer("Y_plus_Champ_P1NC");
  Y_plus_Champ_P1NC& ch_yp=ref_cast(Y_plus_Champ_P1NC,ch.valeur());
  ch_yp.associer_zone_dis_base(zone_vef);
  ch_yp.associer_zone_Cl_dis_base(zone_cl_vef);
  ch_yp.associer_champ(vit);
  ch_yp.nommer("Y_plus");
  ch_yp.fixer_nb_comp(1);
  ch_yp.fixer_nb_valeurs_nodales(zone_vef.nb_elem());
  ch_yp.fixer_unite("adimensionnel");
  ch_yp.changer_temps(ch_vitesse.temps());
}
void VEF_discretisation::zone_Cl_dis (Zone_dis & z, Zone_Cl_dis & zcl) const [virtual]
Implements Discretisation_base.
Reimplemented in VEFPreP1B.
Definition at line 551 of file VEF_discretisation.cpp.
References Cerr, finl, O_U_Ptr::non_nul(), ref_cast, Deriv_::typer(), Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  Cerr << "discretisation des conditions limites" << finl;
  assert(z.non_nul());
  Zone_VEF& zone_VEF=ref_cast(Zone_VEF, z.valeur());
  zcl.typer("Zone_Cl_VEF");
  assert(zcl.non_nul());
  Zone_Cl_VEF& zone_cl_VEF=ref_cast(Zone_Cl_VEF, zcl.valeur());
  zone_cl_VEF.associer(zone_VEF);
  Cerr << "discretisation des conditions limites OK" << finl;
}
Member Data Documentation
const Type_info VEF_discretisation::info_obj [static]
Reimplemented from Discret_Thyd.
Reimplemented in VEFPreP1B, and VEF_1D.
Definition at line 50 of file VEF_discretisation.h.
The documentation for this class was generated from the following files:
src/VEF/Zones/VEF_discretisation.h
src/VEF/Zones/VEF_discretisation.cpp