TRUST: Op_Dift_VDF_base Class Reference
Op_Dift_VDF_base Class Reference
class Op_Dift_VDF_base
#include <Op_Dift_VDF_base.h>
Public Member Functions
Op_Dift_VDF_base ()
~Op_Dift_VDF_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Op_Dift_VDF_base (const Iterateur_VDF_base &)
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
ajoute la contribution de la diffusion au second membre resu
renvoie resu
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
on assemble la matrice.
void contribuer_au_second_membre (DoubleTab &) const
on ajoute la contribution du second membre.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Dift_VDF_base & self_cast (Objet_U &)
static const Op_Dift_VDF_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Detailed Description
class Op_Dift_VDF_base
Definition at line 35 of file Op_Dift_VDF_base.h.
Constructor & Destructor Documentation
Op_Dift_VDF_base::Op_Dift_VDF_base ()
Definition at line 31 of file Op_Dift_VDF_base.cpp.
Op_Dift_VDF_base::~Op_Dift_VDF_base ()
Definition at line 31 of file Op_Dift_VDF_base.cpp.
Op_Dift_VDF_base::Op_Dift_VDF_base (const Iterateur_VDF_base & iter_base) [inline]
Definition at line 48 of file Op_Dift_VDF_base.h.
  : Op_Diff_VDF_base(iter_base)
{}
Member Function Documentation
DoubleTab & Op_Dift_VDF_base::ajouter (const DoubleTab & inco, DoubleTab & resu) const [virtual]
ajoute la contribution de la diffusion au second membre resu
renvoie resu
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Dift_VDF_Face_Axi, and Op_Dift_VDF_var_Face_Axi.
Definition at line 65 of file Op_Dift_VDF_base.cpp.
References Iterateur_VDF::ajouter(), Objet_U::bidim_axi, Cerr, Eval_Dift_VDF_var::diffusivite_turbulente(), Eval_Dift_VDF_const::diffusivite_turbulente(), MorEqn::equation(), Iterateur_VDF::evaluateur(), Process::exit(), Zone_VF::face_voisins(), finl, Eval_Diff_VDF::get_diffusivite(), Equation_base::get_modele(), Op_Diff_VDF_base::iter, Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VDF::orientation(), Objet_U::que_suis_je(), DoubleVect::size(), DoubleVect::size_totale(), sub_type, TURBULENCE, Ref_Objet_U::valeur(), Champ_Fonc::valeurs(), Champ_Proto::valeurs(), Zone_VF::volumes_entrelaces(), Zone_VF::xv(), and Iterateur_VDF::zone().
{
  iter.ajouter(inco, resu);
  if (equation().domaine_application() == Motcle("Hydraulique"))
// On est dans le cas des equations de Navier_Stokes
    {
// Ajout du terme supplementaire en V/(R*R) dans le cas des coordonnees axisymetriques
      if(Objet_U::bidim_axi == 1)
        {
          const Zone_VDF& zvdf=iter.zone();
          const DoubleTab& xv=zvdf.xv();
          const IntVect& ori=zvdf.orientation();
          const IntTab& face_voisins=zvdf.face_voisins();
          const DoubleVect& volumes_entrelaces=zvdf.volumes_entrelaces();
          int face, nb_faces=zvdf.nb_faces();//, cst;
          DoubleTrav diffu_tot(zvdf.nb_elem_tot());
          double db_diffusivite;
          const RefObjU& modele_turbulence = equation().get_modele(TURBULENCE);
          if (sub_type(Mod_turb_hyd_base,modele_turbulence.valeur()))
            {
              const Eval_Diff_VDF& eval=dynamic_cast<const Eval_Diff_VDF&> (iter.evaluateur());
              const Champ_base& ch=eval.get_diffusivite();
              const DoubleVect& tab_diffusivite=ch.valeurs();
              int size=diffu_tot.size_totale();
              if (tab_diffusivite.size() == 1)
                {
                  db_diffusivite = tab_diffusivite[0];
                  const Eval_Dift_VDF_const& eval_dift = dynamic_cast<const Eval_Dift_VDF_const&> (eval);
                  const Champ_Fonc& ch_diff_turb = eval_dift.diffusivite_turbulente();
                  const DoubleVect& diffusivite_turb = ch_diff_turb.valeurs();
                  for (int i=0; i<size; i++)
                    diffu_tot[i] = db_diffusivite+diffusivite_turb[i];
                }
              else
                {
                  const Eval_Dift_VDF_var& eval_dift = dynamic_cast<const Eval_Dift_VDF_var&> (eval);
                  const Champ_Fonc& ch_diff_turb = eval_dift.diffusivite_turbulente();
                  const DoubleVect& diffusivite_turb = ch_diff_turb.valeurs();
                  for (int i=0; i<size; i++)
                    diffu_tot[i] = tab_diffusivite[i]+diffusivite_turb[i];
                }
            }
          else
            {
              Cerr << "Method Op_Dift_VDF_base::ajouter" << finl;
              Cerr << "The type "<<equation().que_suis_je()<<" of the equation associated "<< finl;
              Cerr << "with the current operator "<< que_suis_je() << "is not coherent."<<finl;
              Cerr << "It must be sub typing of Navier_Stokes_Turbulent" << finl;
              exit();
            }
          for (face=0; face<nb_faces; face++)
            if(ori(face)==0)
              {
                int elem1=face_voisins(face,0);
                int elem2=face_voisins(face,1);
                if(elem1==-1)
                  db_diffusivite=diffu_tot(elem2);
                else if (elem2==-1)
                  db_diffusivite=diffu_tot(elem1);
                else
                  db_diffusivite=0.5*(diffu_tot(elem2)+diffu_tot(elem1));
                double r= xv(face,0);
                if(r>=1.e-24)
                  resu(face) -=inco(face)*db_diffusivite*volumes_entrelaces(face)/(r*r);
              }
        }
    }
  return resu;
}
void Op_Dift_VDF_base::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const [virtual]
on assemble la matrice.
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Dift_VDF_Face_Axi, and Op_Dift_VDF_var_Face_Axi.
Definition at line 140 of file Op_Dift_VDF_base.cpp.
References Iterateur_VDF::ajouter_contribution(), Objet_U::bidim_axi, Cerr, Eval_Dift_VDF_var::diffusivite_turbulente(), Eval_Dift_VDF_const::diffusivite_turbulente(), MorEqn::equation(), Iterateur_VDF::evaluateur(), Process::exit(), Zone_VF::face_voisins(), finl, Eval_Diff_VDF::get_diffusivite(), Op_Diff_VDF_base::iter, Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VDF::orientation(), Objet_U::que_suis_je(), DoubleVect::size(), Champ_Fonc::valeurs(), Champ_Proto::valeurs(), Zone_VF::volumes_entrelaces(), Zone_VF::xv(), and Iterateur_VDF::zone().
{
  iter.ajouter_contribution(inco, matrice);
  if (equation().domaine_application() == Motcle("Hydraulique"))
// On est dans le cas des equations de Navier_Stokes
    {
// Ajout du terme supplementaire en V/(R*R) dans le cas des coordonnees axisymetriques
      if(Objet_U::bidim_axi == 1)
        {
          const Zone_VDF& zvdf=iter.zone();
          const DoubleTab& xv=zvdf.xv();
          const IntVect& ori=zvdf.orientation();
          const IntTab& face_voisins=zvdf.face_voisins();
          const DoubleVect& volumes_entrelaces=zvdf.volumes_entrelaces();
          int face, nb_faces=zvdf.nb_faces();//, cst;
          DoubleTrav diffu_tot(zvdf.nb_elem_tot());
          double db_diffusivite;
          if (equation().que_suis_je() == "Navier_Stokes_Turbulent")
            {
              const Eval_Diff_VDF& eval=dynamic_cast<const Eval_Diff_VDF&> (iter.evaluateur());
              const Champ_base& ch=eval.get_diffusivite();
              const DoubleVect& tab_diffusivite=ch.valeurs();
              if (tab_diffusivite.size() == 1)
                {
                  db_diffusivite = tab_diffusivite[0];
                  const Eval_Dift_VDF_const& eval_dift = dynamic_cast<const Eval_Dift_VDF_const&> (eval);
                  const Champ_Fonc& ch_diff_turb = eval_dift.diffusivite_turbulente();
                  const DoubleVect& diffusivite_turb = ch_diff_turb.valeurs();
                  for (int i=0; i<diffusivite_turb.size(); i++)
                    diffu_tot[i] = db_diffusivite+diffusivite_turb[i];
                }
              else
                {
                  const Eval_Dift_VDF_var& eval_dift = dynamic_cast<const Eval_Dift_VDF_var&> (eval);
                  const Champ_Fonc& ch_diff_turb = eval_dift.diffusivite_turbulente();
                  const DoubleVect& diffusivite_turb = ch_diff_turb.valeurs();
                  for (int i=0; i<diffusivite_turb.size(); i++)
                    diffu_tot[i] = tab_diffusivite[i]+diffusivite_turb[i];
                }
            }
          else
            {
              Cerr << "Probleme dans Op_Dift_VDF_base::ajouter avec le type de l'equation" << finl;
              Cerr << "on n'a pas prevu d'autre cas que Navier_Stokes_Turbulent" << finl;
              exit();
            }
          for(face=0; face<nb_faces; face++)
            if(ori(face)==0)
              {
                int elem1=face_voisins(face,0);
                int elem2=face_voisins(face,1);
                if(elem1==-1)
                  db_diffusivite=diffu_tot(elem2);
                else if (elem2==-1)
                  db_diffusivite=diffu_tot(elem1);
                else
                  db_diffusivite=0.5*(diffu_tot(elem2)+diffu_tot(elem1));
                double r= xv(face,0);
                if(r>=1.e-24)
                  matrice(face,face)+=db_diffusivite*volumes_entrelaces(face)/(r*r);
              }
        }
    }
}
void Op_Dift_VDF_base::contribuer_au_second_membre (DoubleTab & resu) const [virtual]
on ajoute la contribution du second membre.
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Dift_VDF_Face_Axi, and Op_Dift_VDF_var_Face_Axi.
Definition at line 208 of file Op_Dift_VDF_base.cpp.
References Objet_U::bidim_axi, Cerr, Iterateur_VDF::contribuer_au_second_membre(), Eval_Dift_VDF_var::diffusivite_turbulente(), Eval_Dift_VDF_const::diffusivite_turbulente(), MorEqn::equation(), Iterateur_VDF::evaluateur(), Process::exit(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Eval_Diff_VDF::get_diffusivite(), Op_Diff_VDF_base::iter, Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_elem_tot(), Zone_dis_base::nb_front_Cl(), Zone_VDF::orientation(), Objet_U::que_suis_je(), ref_cast, DoubleVect::size(), sub_type, Dirichlet::val_imp(), Deriv_Cond_lim_base::valeur(), Champ_Fonc::valeurs(), Champ_Proto::valeurs(), Zone_VF::volumes_entrelaces(), Zone_VF::xv(), Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
{
  iter.contribuer_au_second_membre(resu);
  if (equation().domaine_application() == Motcle("Hydraulique"))
// On est dans le cas des equations de Navier_Stokes
    {
// Ajout du terme supplementaire en V/(R*R) dans le cas des coordonnees axisymetriques
      if(Objet_U::bidim_axi == 1)
        {
          const Zone_VDF& zvdf=iter.zone();
          const Zone_Cl_VDF& zclvdf = iter.zone_Cl();
          const DoubleTab& xv=zvdf.xv();
          const IntVect& ori=zvdf.orientation();
          const IntTab& face_voisins=zvdf.face_voisins();
          const DoubleVect& volumes_entrelaces=zvdf.volumes_entrelaces();
// int face, nb_faces=zvdf.nb_faces(), cst;
          DoubleTrav diffu_tot(zvdf.nb_elem_tot());
          double db_diffusivite;
          if (equation().que_suis_je() == "Navier_Stokes_Turbulent")
            {
              const Eval_Diff_VDF& eval=dynamic_cast<const Eval_Diff_VDF&> (iter.evaluateur());
              const Champ_base& ch=eval.get_diffusivite();
              const DoubleVect& tab_diffusivite=ch.valeurs();
              if (tab_diffusivite.size() == 1)
                {
                  db_diffusivite = tab_diffusivite[0];
                  const Eval_Dift_VDF_const& eval_dift = dynamic_cast<const Eval_Dift_VDF_const&> (eval);
                  const Champ_Fonc& ch_diff_turb = eval_dift.diffusivite_turbulente();
                  const DoubleVect& diffusivite_turb = ch_diff_turb.valeurs();
                  for (int i=0; i<diffusivite_turb.size(); i++)
                    diffu_tot[i] = db_diffusivite+diffusivite_turb[i];
                }
              else
                {
                  const Eval_Dift_VDF_var& eval_dift = dynamic_cast<const Eval_Dift_VDF_var&> (eval);
                  const Champ_Fonc& ch_diff_turb = eval_dift.diffusivite_turbulente();
                  const DoubleVect& diffusivite_turb = ch_diff_turb.valeurs();
                  for (int i=0; i<diffusivite_turb.size(); i++)
                    diffu_tot[i] = tab_diffusivite[i]+diffusivite_turb[i];
                }
            }
          else
            {
              Cerr << "Probleme dans Op_Dift_VDF_base::ajouter avec le type de l'equation" << finl;
              Cerr << "on n'a pas prevu d'autre cas que Navier_Stokes_Turbulent" << finl;
              exit();
            }
// Boucle sur les conditions limites pour traiter les faces de bord
          int ndeb,nfin,num_face;
          for (int n_bord=0; n_bord<zvdf.nb_front_Cl(); n_bord++)
            {
              const Cond_lim& la_cl = zclvdf.les_conditions_limites(n_bord);
              if (sub_type(Dirichlet,la_cl.valeur()))
                {
                  const Dirichlet& la_cl_diri = ref_cast(Dirichlet,la_cl.valeur());
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  double r_2,coef;
                  for (num_face=ndeb; num_face<nfin; num_face++)
                    {
                      if (ori(num_face) == 0)
{
                          int elem1=face_voisins(num_face,0);
                          int elem2=face_voisins(num_face,1);
                          if(elem1==-1)
                            db_diffusivite=diffu_tot(elem2);
                          else
{
                              assert (elem2==-1);
                              db_diffusivite=diffu_tot(elem1);
                            }
                          r_2 = xv(num_face,0)*xv(num_face,0);
                          coef = volumes_entrelaces(num_face)/r_2;
// resu(num_face) -=0.;
                          resu(num_face) -= (la_cl_diri.val_imp(num_face-ndeb)*coef)*db_diffusivite;
                        }
                    }
                }
            }
        }
    }
}
virtual int Op_Dift_VDF_base::duplique () const [pure virtual]
Implements Op_Diff_VDF_base.
Implemented in Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, and Op_Dift_VDF_var_Face_Axi.
const Type_info * Op_Dift_VDF_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, and Op_Dift_VDF_var_Face_Axi.
Definition at line 31 of file Op_Dift_VDF_base.cpp.
const Type_info * Op_Dift_VDF_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, and Op_Dift_VDF_var_Face_Axi.
Definition at line 31 of file Op_Dift_VDF_base.cpp.
Sortie & Op_Dift_VDF_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, and Op_Dift_VDF_var_Face_Axi.
Definition at line 33 of file Op_Dift_VDF_base.cpp.
{
  return Op_Diff_VDF_base::printOn(is);
}
Entree & Op_Dift_VDF_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, and Op_Dift_VDF_var_Face_Axi.
Definition at line 38 of file Op_Dift_VDF_base.cpp.
{
  Op_Diff_VDF_base::readOn(is);
  return is;
}
const Op_Dift_VDF_base & Op_Dift_VDF_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, and Op_Dift_VDF_var_Face_Axi.
Definition at line 31 of file Op_Dift_VDF_base.cpp.
Op_Dift_VDF_base & Op_Dift_VDF_base::self_cast (Objet_U & r) [static]
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, and Op_Dift_VDF_var_Face_Axi.
Definition at line 31 of file Op_Dift_VDF_base.cpp.
Member Data Documentation
const Type_info Op_Dift_VDF_base::info_obj [static]
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, and Op_Dift_VDF_var_Face_Axi.
Definition at line 38 of file Op_Dift_VDF_base.h.
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Operateurs_Diff/Op_Dift_VDF_base.h
src/VDF/Operateurs/Operateurs_Diff/Op_Dift_VDF_base.cpp