TRUST: Solveur_Masse Class Reference
Solveur_Masse Class Reference
classe Solveur_Masse
Classe generique de la hierarchie des solveurs de masse, un objet
Solveur_Masse peut referencer n'importe quel d'objet derivant de
Solveur_Masse_base.
La plupart des methodes appellent les methodes de l'objet Solveur_Masse
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
Contrairement a la classe de base (Solveur_Masse_base) Solveur_Masse
contient une reference vers l'equation associee car il herite de MorEqn.
#include <Solveur_Masse.h>
Public Member Functions
Solveur_Masse ()
~Solveur_Masse ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & appliquer (DoubleTab &) const
Appel a l'objet sous-jacent.
Resoud le systeme lineaire, dont la matrice est la matrice de masse.
Le second membre du systeme lineaire a resoudre est passe en parametre.
Le resultat est stocke dans ce meme parametre et renvoye par la methode.
Operation xx = M^{-1} * xx.
void mettre_a_jour (double temps)
Appel a l'objet sous-jacent.
Mise a jour en temps du solveur de masse.
void assembler ()
Appel a l'objet sous-jacent.
Assemblage de la matrice de masse.
void typer (const Nom &)
Construit le bon type de Solveur de masse.
virtual void typer ()
Construit le bon type de Solveur de masse.
Matrice_Base & ajouter_masse (double, Matrice_Base &, int penalisation=1) const
DoubleTab & ajouter_masse (double, DoubleTab &, const DoubleTab &y, int penalisation=1) const
DoubleTab & corriger_solution (DoubleTab &x, const DoubleTab &y, int incr=0) const
Matrice_Base & ajouter_masse_dt_local (DoubleVect &, Matrice_Base &, int penalisation=1) const
DoubleTab & ajouter_masse_dt_local (DoubleVect &, DoubleTab &, const DoubleTab &y, int penalisation=1) const
void get_masse_dt_local (DoubleVect &m_dt_locaux, DoubleVect &dt_locaux, int penalisation=1)
void get_masse_divide_by_local_dt (DoubleVect &m_dt_locaux, DoubleVect &dt_locaux, int penalisation=1)
Public Member Functions inherited from Deriv_Solveur_Masse_base
~Deriv_Solveur_Masse_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Solveur_Masse_base ()
Deriv_Solveur_Masse_base (const Deriv_Solveur_Masse_base &)
const Solveur_Masse_base & valeur () const
Solveur_Masse_base & valeur ()
const Solveur_Masse_base * operator-> () const
Solveur_Masse_base * operator-> ()
const Deriv_Solveur_Masse_base & operator= (const Solveur_Masse_base &)
const Deriv_Solveur_Masse_base & operator= (const Deriv_Solveur_Masse_base &)
operator const Solveur_Masse_base & () const
operator Solveur_Masse_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Solveur_Masse & self_cast (Objet_U &)
static const Solveur_Masse & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Solveur_Masse_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Solveur_Masse_base & self_cast (Objet_U &)
static const Deriv_Solveur_Masse_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Solveur_Masse_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime le solveur de masse sur un flot de sortie.
Entree & readOn (Entree &) override
Lit le solveur de masse sur un flot d'entree.
Protected Member Functions inherited from Deriv_Solveur_Masse_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Additional Inherited Members
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
classe Solveur_Masse
Classe generique de la hierarchie des solveurs de masse, un objet
Solveur_Masse peut referencer n'importe quel d'objet derivant de
Solveur_Masse_base.
La plupart des methodes appellent les methodes de l'objet Solveur_Masse
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
Contrairement a la classe de base (Solveur_Masse_base) Solveur_Masse
contient une reference vers l'equation associee car il herite de MorEqn.
Definition at line 43 of file Solveur_Masse.h.
Constructor & Destructor Documentation
Solveur_Masse()
Solveur_Masse::Solveur_Masse ()
Definition at line 23 of file Solveur_Masse.cpp.
~Solveur_Masse()
Solveur_Masse::~Solveur_Masse ()
Definition at line 23 of file Solveur_Masse.cpp.
Member Function Documentation
ajouter_masse() [1/2]
DoubleTab & Solveur_Masse::ajouter_masse (double dt, DoubleTab & x, const DoubleTab & y, int penalisation = 1) const inline
Definition at line 151 of file Solveur_Masse.h.
{
  return valeur().ajouter_masse(dt,x,y,penalisation);
}
References Solveur_Masse_base::ajouter_masse(), and Deriv_Solveur_Masse_base::valeur().
ajouter_masse() [2/2]
Matrice_Base & Solveur_Masse::ajouter_masse (double dt, Matrice_Base & matrice, int penalisation = 1) const inline
Definition at line 146 of file Solveur_Masse.h.
{
  return valeur().ajouter_masse(dt,matrice,penalisation);
}
References Solveur_Masse_base::ajouter_masse(), and Deriv_Solveur_Masse_base::valeur().
Referenced by Schema_Adams_Moulton_base::add_multi_timestep_data(), Schema_Backward_Differentiation_base::add_multi_timestep_data(), Schema_Temps_base::ajouter_inertie(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), construire_matrice_implicite(), Equation_base::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Equation_base::Gradient_conjugue_diff_impl(), and Schema_Adams_Bashforth_base::modifier_second_membre().
ajouter_masse_dt_local() [1/2]
DoubleTab & Solveur_Masse::ajouter_masse_dt_local (DoubleVect & dt_locaux, DoubleTab & x, const DoubleTab & y, int penalisation = 1) const inline
Definition at line 161 of file Solveur_Masse.h.
{
  return valeur().ajouter_masse_dt_local(dt_locaux,x,y,penalisation);
}
References Solveur_Masse_base::ajouter_masse_dt_local(), and Deriv_Solveur_Masse_base::valeur().
ajouter_masse_dt_local() [2/2]
Matrice_Base & Solveur_Masse::ajouter_masse_dt_local (DoubleVect & dt_locaux, Matrice_Base & matrice, int penalisation = 1) const inline
Definition at line 156 of file Solveur_Masse.h.
{
  return valeur().ajouter_masse_dt_local(dt_locaux,matrice,penalisation);
}
References Solveur_Masse_base::ajouter_masse_dt_local(), and Deriv_Solveur_Masse_base::valeur().
appliquer()
DoubleTab & Solveur_Masse::appliquer (DoubleTab & xx) const inline
Appel a l'objet sous-jacent.
Resoud le systeme lineaire, dont la matrice est la matrice de masse.
Le second membre du systeme lineaire a resoudre est passe en parametre.
Le resultat est stocke dans ce meme parametre et renvoye par la methode.
Operation xx = M^{-1} * xx.
Returns
DoubleTab&
Signification: la solution M^{-1} * xx
Contraintes:
Definition at line 80 of file Solveur_Masse.h.
{
  return valeur().appliquer(xx);
}
References Solveur_Masse_base::appliquer(), and Deriv_Solveur_Masse_base::valeur().
Referenced by Operateur::ajouter(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Assembleur_P_VEF::calculer_inv_volume(), calculer_inv_volume(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), Navier_Stokes_std::corriger_derivee_impl(), Equation_base::derivee_en_temps_conv(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Champ_Generique_Gradient::get_champ(), Equation_base::Gradient_conjugue_diff_impl(), Piso::iterer_NS(), Navier_Stokes_std::mettre_a_jour(), Schema_Adams_Moulton_base::modifier_second_membre_full_impl(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projeter(), Op_Diff_VEFP1NCP1B_Face::test(), Operateur_base::tester_contribuer_a_avec(), and verifier_complet().
assembler()
void Solveur_Masse::assembler () inline
Appel a l'objet sous-jacent.
Assemblage de la matrice de masse.
Definition at line 121 of file Solveur_Masse.h.
{
  valeur().assembler();
}
References Solveur_Masse_base::assembler(), and Deriv_Solveur_Masse_base::valeur().
corriger_solution()
DoubleTab & Solveur_Masse::corriger_solution (DoubleTab & x, const DoubleTab & y, int incr = 0) const inline
Definition at line 173 of file Solveur_Masse.h.
{
  return valeur().corriger_solution(x,y, incr);
}
References Solveur_Masse_base::corriger_solution(), and Deriv_Solveur_Masse_base::valeur().
Referenced by Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), SETS::iterer_NS(), Piso::iterer_NS(), Solveur_U_P::iterer_NS(), Navier_Stokes_std::projeter(), and Navier_Stokes_std::uzawa().
cree_instance()
Objet_U * Solveur_Masse::cree_instance () static
Definition at line 23 of file Solveur_Masse.cpp.
duplique()
int Solveur_Masse::duplique () const override virtual
Reimplemented from Deriv_Solveur_Masse_base.
Definition at line 23 of file Solveur_Masse.cpp.
get_info()
const Type_info * Solveur_Masse::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Solveur_Masse_base.
Definition at line 23 of file Solveur_Masse.cpp.
get_masse_divide_by_local_dt()
void Solveur_Masse::get_masse_divide_by_local_dt (DoubleVect & m_dt_locaux, DoubleVect & dt_locaux, int penalisation = 1) inline
Definition at line 169 of file Solveur_Masse.h.
{
  valeur().get_masse_divide_by_local_dt(m_dt_locaux,dt_locaux,penalisation);
}
References Solveur_Masse_base::get_masse_divide_by_local_dt(), and Deriv_Solveur_Masse_base::valeur().
get_masse_dt_local()
void Solveur_Masse::get_masse_dt_local (DoubleVect & m_dt_locaux, DoubleVect & dt_locaux, int penalisation = 1) inline
Definition at line 165 of file Solveur_Masse.h.
{
  valeur().get_masse_dt_local(m_dt_locaux,dt_locaux,penalisation);
}
References Solveur_Masse_base::get_masse_dt_local(), and Deriv_Solveur_Masse_base::valeur().
info()
const Type_info * Solveur_Masse::info () static
Definition at line 23 of file Solveur_Masse.cpp.
mettre_a_jour()
void Solveur_Masse::mettre_a_jour (double temps) inline
Appel a l'objet sous-jacent.
Mise a jour en temps du solveur de masse.
Definition at line 100 of file Solveur_Masse.h.
{
  valeur().mettre_a_jour(temps);
}
References Solveur_Masse_base::mettre_a_jour(), and Deriv_Solveur_Masse_base::valeur().
Referenced by Equation_base::initTimeStep().
printOn()
Sortie & Solveur_Masse::printOn (Sortie & os) const override protected virtual
Imprime le solveur de masse sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Solveur_Masse_base.
Definition at line 40 of file Solveur_Masse.cpp.
{
  return DERIV(Solveur_Masse_base)::printOn(os);
}
References DERIV, and printOn().
Referenced by printOn().
readOn()
Entree & Solveur_Masse::readOn (Entree & is) override protected virtual
Lit le solveur de masse sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Solveur_Masse_base.
Definition at line 60 of file Solveur_Masse.cpp.
{
  return DERIV(Solveur_Masse_base)::readOn(is);
}
References DERIV, and readOn().
Referenced by readOn().
self_cast() [1/2]
const Solveur_Masse & Solveur_Masse::self_cast (const Objet_U & r) static
Definition at line 23 of file Solveur_Masse.cpp.
self_cast() [2/2]
Solveur_Masse & Solveur_Masse::self_cast (Objet_U & r) static
Definition at line 23 of file Solveur_Masse.cpp.
taille_memoire()
unsigned Solveur_Masse::taille_memoire () const override virtual
Reimplemented from Deriv_Solveur_Masse_base.
Definition at line 23 of file Solveur_Masse.cpp.
typer() [1/2]
void Solveur_Masse::typer () virtual
Construit le bon type de Solveur de masse.
Definition at line 80 of file Solveur_Masse.cpp.
{
  Equation_base& eqn=mon_equation.valeur();
  Nom inut;
  Nom typ=eqn.discretisation().get_name_of_type_for(que_suis_je(),inut,eqn);
  DERIV(Solveur_Masse_base)::typer(typ);
  valeur().associer_eqn(eqn);
}
References MorEqn::associer_eqn(), DERIV, Equation_base::discretisation(), Discretisation_base::get_name_of_type_for(), MorEqn::mon_equation, Objet_U::que_suis_je(), typer(), Ref_Equation_base::valeur(), and Deriv_Solveur_Masse_base::valeur().
Referenced by typer().
typer() [2/2]
void Solveur_Masse::typer (const Nom & typ) inline
Construit le bon type de Solveur de masse.
Definition at line 141 of file Solveur_Masse.h.
{
  DERIV(Solveur_Masse_base)::typer(typ);
}
References DERIV, and typer().
Referenced by Equation_base::discretiser().
Member Data Documentation
info_obj
const Type_info Solveur_Masse::info_obj static
Definition at line 45 of file Solveur_Masse.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Solveur_Masse.h
src/Kernel/Framework/Solveur_Masse.cpp