TRUST: Champ_front_recyclage Class Reference
Champ_front_recyclage Class Reference
classe Champ_front_recyclage
delt_dist delt_dist
pb1 <-------—> pb2 <-----—> pb
ch_fr2 ch_fr
_____________________ ____________________________ ____________________________
| | | | | | | |
| dom1 | | | dom2 | | | dom |
| ch1 | | |bord2 | |bord | ch |
|_________________|___| |____________________________| |________|__________________|
plan1 plan
Fig. 1 Fig. 2
Cette classe a pour objectif d evaluer les valeurs d un champ_front (ch_fr2) sur le bord d un domaine (bord2)
en exploitant les valeurs d un champ 1 (ch1 dit champ evaluateur) evaluees dans un plan (plan1) distant de
delt_dist de bord2 (Fig. 1).
#include <Champ_front_recyclage.h>
Public Member Functions
~Champ_front_recyclage ()
< Pour AIX
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_recyclage ()
int lire_info_moyenne_imposee (Entree &is)
int lire_info_moyenne_recyclee (Entree &is)
void calcul_moyenne_imposee (const DoubleTab &tab, double temps)
void calcul_moyenne_recyclee (const DoubleTab &tab, double temps)
void initialiser_moyenne_imposee (DoubleTab &moyenne)
void initialiser_moyenne_recyclee (DoubleTab &moyenne)
void associer_champ_evaluateur (const Nom &, const Motcle &)
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
void mettre_a_jour (double temps) override
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
void lire_fichier_format1 (DoubleTab &moyenne, const Frontiere_dis_base &fr_vf, const Nom &nom_fich)
void lire_fichier_format2 (DoubleTab &moyenne, const Frontiere_dis_base &fr_vf, const Nom &nom_fich)
void lire_fichier_format3 (DoubleTab &moyenne, const Frontiere_dis_base &fr_vf, const Nom &nom_fich1, const Nom &nom_fich2)
double UPb (double y, Nom nom_fich)
Public Member Functions inherited from Ch_front_var_instationnaire_dep
Ch_front_var_instationnaire_dep ()
~Ch_front_var_instationnaire_dep ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Champ_front_base & affecter_ (const Champ_front_base &ch) override
Public Member Functions inherited from Champ_front_var_instationnaire
Champ_front_var_instationnaire ()
~Champ_front_var_instationnaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialise le temps courant et Gpoint.
DoubleTab & Gpoint ()
const DoubleTab & Gpoint () const
void Gpoint (double t1, double t2)
DoubleTab & valeurs_au_temps (double temps) override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
const DoubleTab & valeurs_au_temps (double temps) const override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
int avancer (double temps) override
Avance jusqu'au temps desire.
Sinon, sort en erreur.
int reculer (double temps) override
Recule jusqu'au temps desire.
Sinon, sort en erreur.
virtual double valeur_au_temps_et_au_point (double temps, int som, double x, double y, double z, int comp) const
virtual int valeur_au_temps_et_au_point_disponible () const
Public Member Functions inherited from Champ_front_var
Champ_front_var ()
~Champ_front_var () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Public Member Functions inherited from Champ_front_base
~Champ_front_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base ()
virtual void completer ()
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe une frontiere discretisee au champ.
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
virtual DoubleTab & valeurs_au_temps (double temps)=0
virtual const DoubleTab & valeurs_au_temps (double temps) const =0
const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee associee au champ.
(version const)
Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee associee au champ.
const Zone_dis_base & zone_dis () const
virtual Champ_front_base & affecter_ (const Champ_front_base &ch)=0
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
virtual void calculer_coeffs_echange (double temps)
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
virtual void valeurs_face (int, DoubleVect &) const
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
virtual void verifier (const Cond_lim_base &la_cl) const
double get_temps_defaut () const
void set_temps_defaut (double temps)
virtual void changer_temps_futur (double temps, int i)
virtual int avancer (double temps)
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe
en parametre.
virtual int reculer (double temps)
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe
en parametre.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_front_recyclage & self_cast (Objet_U &)
static const Champ_front_recyclage & self_cast (const Objet_U &)
static void get_coord_faces (const Frontiere_dis_base &fr_vf, DoubleTab &coords, const DoubleVect &delt_dist)
Static Public Member Functions inherited from Ch_front_var_instationnaire_dep
static Objet_U * cree_instance ()
static const Type_info * info ()
static Ch_front_var_instationnaire_dep & self_cast (Objet_U &)
static const Ch_front_var_instationnaire_dep & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var_instationnaire
static const Type_info * info ()
static Champ_front_var_instationnaire & self_cast (Objet_U &)
static const Champ_front_var_instationnaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var
static const Type_info * info ()
static Champ_front_var & self_cast (Objet_U &)
static const Champ_front_var & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_base
static const Type_info * info ()
static Champ_front_base & self_cast (Objet_U &)
static const Champ_front_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Ch_front_var_instationnaire_dep
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var_instationnaire
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Champ_Inc_base l_inconnue1
DoubleVect delt_dist
Nom nom_pb1
Motcle nom_inco1
DoubleTab moyenne_imposee_
DoubleTab moyenne_recyclee_
DoubleVect ampli_fluct_
DoubleVect ampli_moy_imposee_
DoubleVect ampli_moy_recyclee_
int methode_moy_impos_
int methode_moy_recycl_
Nom fich_impos_
Nom fich_recycl_
Nom fich_maillage_
int ndir
Vect_Parser_U profil_2
Noms fcts_xyz
double u_tau
double diametre
double visco_cin
DoubleTabs inconnues1_coords_to_eval_
ArrsOfInt inconnues1_elems_
ArrsOfInt inconnues2_faces_
Protected Attributes inherited from Champ_front_var_instationnaire
DoubleTab Gpoint_
Taux d'accroissement du champ.
Protected Attributes inherited from Champ_front_base
double temps_defaut
Le temps pris par defaut quand le parametre n'est pas specifie. Ce sera en particulier celui utilise par les operateurs et les solveurs.
Ref_Frontiere_dis_base la_frontiere_dis
Roue_ptr les_valeurs
Les valeurs du champ.
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
classe Champ_front_recyclage
delt_dist delt_dist
pb1 <-------—> pb2 <-----—> pb
ch_fr2 ch_fr
_____________________ ____________________________ ____________________________
| | | | | | | |
| dom1 | | | dom2 | | | dom |
| ch1 | | |bord2 | |bord | ch |
|_________________|___| |____________________________| |________|__________________|
plan1 plan
Fig. 1 Fig. 2
Cette classe a pour objectif d evaluer les valeurs d un champ_front (ch_fr2) sur le bord d un domaine (bord2)
en exploitant les valeurs d un champ 1 (ch1 dit champ evaluateur) evaluees dans un plan (plan1) distant de
delt_dist de bord2 (Fig. 1).
Definition at line 132 of file Champ_front_recyclage.h.
Constructor & Destructor Documentation
~Champ_front_recyclage()
Champ_front_recyclage::~Champ_front_recyclage ()
< Pour AIX
Definition at line 30 of file Champ_front_recyclage.cpp.
Champ_front_recyclage()
Champ_front_recyclage::Champ_front_recyclage ()
Definition at line 32 of file Champ_front_recyclage.cpp.
{
  int dim = Objet_U::dimension;
  delt_dist.resize(dim,Array_base::NOCOPY_NOINIT);
  delt_dist=0;
  ampli_fluct_.resize(1,Array_base::NOCOPY_NOINIT);
  ampli_fluct_ = 1.;
  ampli_moy_imposee_.resize(1,Array_base::NOCOPY_NOINIT);
  ampli_moy_imposee_ = 1.;
  ampli_moy_recyclee_.resize(1,Array_base::NOCOPY_NOINIT);
  ampli_moy_recyclee_ = 1.;
  methode_moy_impos_ = -1;
  methode_moy_recycl_ = -1;
  ndir = -4;
  diametre = -1.;
  u_tau = -1.;
  visco_cin = -1.;
  fich_recycl_ = "??";
  fich_impos_ = "??";
}
References ampli_fluct_, ampli_moy_imposee_, ampli_moy_recyclee_, delt_dist, diametre, Objet_U::dimension, fich_impos_, fich_recycl_, methode_moy_impos_, methode_moy_recycl_, ndir, Array_base::NOCOPY_NOINIT, TRUSTVect< _TYPE_ >::resize(), u_tau, and visco_cin.
Member Function Documentation
associer_champ_evaluateur()
void Champ_front_recyclage::associer_champ_evaluateur (const Nom & un_nom_pb1, const Motcle & un_nom_inco1)
Definition at line 413 of file Champ_front_recyclage.cpp.
{
  Objet_U& ob1 = Interprete::objet(un_nom_pb1);
  REF(Probleme_base) pb1;
  REF(Champ_base) rch1;
  if(sub_type(Probleme_base,ob1))
    {
      pb1 = ref_cast(Probleme_base,ob1);
    }
  else
    {
      Cerr <<"No problem named "<< un_nom_pb1 <<" has been found."<< finl;
      exit();
    }
  rch1 = pb1->get_champ(un_nom_inco1);
  if(sub_type(Champ_Inc_base,rch1.valeur()))
    l_inconnue1 = ref_cast(Champ_Inc_base,rch1.valeur()) ;
  else
    {
      Cerr<<pb1->le_nom()<<" has no unknown field named "<<un_nom_inco1<<finl;
      exit();
    }
}
References Cerr, Process::exit(), finl, l_inconnue1, Interprete::objet(), REF, ref_cast, and sub_type.
Referenced by initialiser().
calcul_moyenne_imposee()
void Champ_front_recyclage::calcul_moyenne_imposee (const DoubleTab & tab, double temps)
Definition at line 875 of file Champ_front_recyclage.cpp.
{
  if (methode_moy_impos_==1)
    {
      const Front_VF& fr_vf2 = ref_cast(Front_VF,la_frontiere_dis.valeur());
      const Zone_dis_base& zone_dis2 = fr_vf2.zone_dis();
      const Zone_VF&  la_zone2 = ref_cast(Zone_VF,zone_dis2);
      const DoubleTab&  xv2 = la_zone2.xv();
      int nb_faces_bord2 = fr_vf2.nb_faces();
      int ndeb = fr_vf2.num_premiere_face();
      for (int i=0; i<nb_faces_bord2; i++)
        for (int j=0; j<nb_compo_; j++)
          {
            profil_2[j].setVar(0,temps);
            for (int d=0; d<dimension; d++)
              profil_2[j].setVar(d+1,xv2(ndeb+i,d));
            moyenne_imposee_(i,j) =  profil_2[j].eval();
          }
    }
  else if (methode_moy_impos_==2)
    {
    }
  else if (methode_moy_impos_==3)
    {
    }
  else if (methode_moy_impos_==4)
    {
    }
  else if (methode_moy_impos_==5)
    {
    }
  else if (methode_moy_impos_!=-1)
    {
      Cerr<<"The method used to calculate moyenne_imposee_ is not definded."<<finl;
      exit();
    }
}
References Cerr, Objet_U::dimension, Process::exit(), finl, Champ_front_base::la_frontiere_dis, methode_moy_impos_, moyenne_imposee_, Field_base::nb_compo_, Front_VF::nb_faces(), Front_VF::num_premiere_face(), profil_2, ref_cast, Ref_Frontiere_dis_base::valeur(), Zone_VF::xv(), and Frontiere_dis_base::zone_dis().
Referenced by mettre_a_jour().
calcul_moyenne_recyclee()
void Champ_front_recyclage::calcul_moyenne_recyclee (const DoubleTab & tab, double temps)
Definition at line 924 of file Champ_front_recyclage.cpp.
{
  if (methode_moy_recycl_==1)
    {
      const Front_VF& fr_vf2 = ref_cast(Front_VF,la_frontiere_dis.valeur());
      int nb_faces_bord2 = fr_vf2.nb_faces();
      DoubleVect face_surfaces;
      const Faces& les_faces_bord = fr_vf2.frontiere().faces();
      les_faces_bord.calculer_surfaces(face_surfaces);
      DoubleVect moyenne(nb_compo_);
      double somme_si = 0.;
      moyenne = 0.;
      for (int i=0; i<nb_faces_bord2; i++)
        {
          for (int j=0; j<nb_compo_; j++)
            moyenne(j) += tab(i,j)*face_surfaces(i);
          somme_si += face_surfaces(i);
        }
      somme_si = mp_sum(somme_si);
      for (int j=0; j<nb_compo_; j++)
        moyenne(j) = mp_sum(moyenne(j));
      moyenne /= somme_si;
      for (int i=0; i<nb_faces_bord2; i++)
        for (int j=0; j<nb_compo_; j++)
          moyenne_recyclee_(i,j) = moyenne(j);
    }
  else if (methode_moy_recycl_==2)
    {
    }
  else if (methode_moy_recycl_==3)
    {
    }
  else if (methode_moy_recycl_==4)
    {
    }
  else if (methode_moy_recycl_!=-1)
    {
      Cerr<<"The method used to calculate moyenne_recyclee_ is not defined."<<finl;
      exit();
    }
}
References Faces::calculer_surfaces(), Cerr, Process::exit(), Frontiere::faces(), finl, Frontiere_dis_base::frontiere(), Champ_front_base::la_frontiere_dis, methode_moy_recycl_, moyenne_recyclee_, Process::mp_sum(), Field_base::nb_compo_, Front_VF::nb_faces(), ref_cast, and Ref_Frontiere_dis_base::valeur().
Referenced by mettre_a_jour().
cree_instance()
Objet_U * Champ_front_recyclage::cree_instance () static
Definition at line 30 of file Champ_front_recyclage.cpp.
duplique()
int Champ_front_recyclage::duplique () const override virtual
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 30 of file Champ_front_recyclage.cpp.
get_coord_faces()
void Champ_front_recyclage::get_coord_faces (const Frontiere_dis_base & fr_vf, DoubleTab & coords, const DoubleVect & delt_dist) static
Definition at line 443 of file Champ_front_recyclage.cpp.
{
  const Front_VF&   fr_vf2    = ref_cast(Front_VF,fr_vf);
  const Zone_VF&    la_zone2  = ref_cast(Zone_VF,fr_vf2.zone_dis());
  const DoubleTab&  xv2       = la_zone2.xv();
  const int      nb_faces2 = fr_vf2.nb_faces();
  const int      ndeb2     = fr_vf2.num_premiere_face();
  const int      dim       = xv2.dimension(1);
  coords.resize(nb_faces2,dim);
  for (int i = 0; i < nb_faces2; i++)
    for (int j = 0; j < dim; j++)
      coords(i,j) = xv2(i+ndeb2,j) + delt_dist(j);
}
References delt_dist, TRUSTTab< _TYPE_ >::dimension(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Zone_VF::xv(), and Frontiere_dis_base::zone_dis().
Referenced by initialiser(), and lire_fichier_format1().
get_info()
const Type_info * Champ_front_recyclage::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 30 of file Champ_front_recyclage.cpp.
info()
const Type_info * Champ_front_recyclage::info () static
Definition at line 30 of file Champ_front_recyclage.cpp.
initialiser()
int Champ_front_recyclage::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
< Remote elem
< Remote elem
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 466 of file Champ_front_recyclage.cpp.
{
  if (!Ch_front_var_instationnaire_dep::initialiser(temps,inco))
    return 0;
// 1: remote
// 2: local
  const Front_VF& fr_vf2 = ref_cast(Front_VF,la_frontiere_dis.valeur());
  const Nom& nom_bord2 = fr_vf2.frontiere().le_nom();
  int nb_faces_bord2 = fr_vf2.nb_faces();
  associer_champ_evaluateur(nom_pb1,nom_inco1);
  moyenne_imposee_.resize(nb_faces_bord2,nb_compo_,Array_base::COPY_INIT);
  moyenne_recyclee_.resize(nb_faces_bord2,nb_compo_,Array_base::COPY_INIT);
  if (ampli_fluct_.size()!=nb_compo_)
    {
      Cerr<<"The number of fluctuation amplification factors is not coherent with the component number of the field "<<nom_inco1<<finl;
      Cerr<<"This field has "<<nb_compo_<<" components and there is "<<ampli_fluct_.size()<<" amplification factors defined."<<finl;
      Cerr<<"Please check that ampli_fluctuation is well specified in your data set."<<finl;
      exit();
    }
  if (ampli_moy_imposee_.size()!=nb_compo_)
    {
      Cerr<<"The number of the amplification factors for the fixed average is not coherent with the component number of the field "<<nom_inco1<<finl;
      Cerr<<"This field has "<<nb_compo_<<" components and there is "<<ampli_moy_imposee_.size()<<" amplification factors defined."<<finl;
      Cerr<<"Please check that ampli_moyenne_imposee is well specified in your data set."<<finl;
      exit();
    }
  if (ampli_moy_recyclee_.size()!=nb_compo_)
    {
      Cerr<<"The number of the amplification factors for the recycled average is not coherent with the component number of the field "<<nom_inco1<<finl;
      Cerr<<"This field has "<<nb_compo_<<" components and there is "<<ampli_moy_recyclee_.size()<<" amplification factors defined."<<finl;
      Cerr<<"Please check that ampli_moyenne_recyclee is well specified in your data set."<<finl;
      exit();
    }
  Cerr << "Initializing Champ_front_recyclage on the boundary: " << nom_bord2 << finl;
// Pour chaque point de remote_coord, chercher le processeur dont le domaine1 contient ce point,
// et l'indice de l'element:
  const int nprocs = nproc();
  const int moi = me();
// Remplissage de remote_coords[i]: coordonnees des centres des faces du bord nom_bord2
// (bord destination) + delt_dist
// du processeur i (tous les procs possedent le meme tableau remote_coords)
// Build a DoubleTabs containing the coordinates of the remote faces on zone 1 for each processor
  DoubleTabs remote_coords(nprocs);
  /*
  if (nom_bord!="??") // Improve this test
  {
     const Front_VF& fr_vf1 = ref_cast(Front_VF,front_dis());
     get_coord_faces(fr_vf1,remote_coords[moi],delt_dist);
  }
  else */
  get_coord_faces(fr_vf2,remote_coords[moi],delt_dist);
  for (int pe = 0; pe < nprocs; pe++)
    envoyer_broadcast(remote_coords[pe],pe);
// Size the 3 arrays:
  inconnues1_coords_to_eval_.dimensionner(nprocs);
  inconnues1_elems_.dimensionner(nprocs);
  inconnues2_faces_.dimensionner(nprocs);
  ArrsOfInt indexes_to_recv(nprocs);
// tmp array for octree results:
  ArrOfInt elem_list;
  elem_list.set_smart_resize(1);
  const Zone& zone1 = l_inconnue1.valeur().equation().zone_dis().valeur().zone();
  const int nb_elem_zone1 = zone1.nb_elem();
  const int dim = remote_coords[moi].dimension(1);
  const Zone_dis_base& zdis = l_inconnue1.valeur().equation().zone_dis().valeur();
  const Zone_VF& zvf = ref_cast(Zone_VF,zdis);
  const DoubleTab& xp = zvf.xp();
  DoubleVect remote_point(3);
  const OctreeRoot& octree = zone1.construit_octree();
// Loop on processes
  for (int pe = 0; pe < nprocs; pe++)
    {
// Remote coordinates of the local faces:
      const DoubleTab& remote_coords_on_pe = remote_coords[pe];
      int nb_faces_on_pe = remote_coords_on_pe.dimension(0);
      elem_list.resize_tab(nb_faces_on_pe,ArrOfInt::NOCOPY_NOINIT);
      ArrOfInt elem_list_par_pos;
// Loop on local faces on the process pe:
      for (int ind_face=0; ind_face<nb_faces_on_pe; ind_face++)
        {
          for (int j=0; j<dimension; j++)
            remote_point(j) = remote_coords_on_pe(ind_face,j);
// Fill elem_list_par_pos by elements surrounding the remote point:
          octree.rang_elems_sommet(elem_list_par_pos,remote_point(0),remote_point(1),remote_point(2));
          int size_elem_list = elem_list_par_pos.size_array();
          if (size_elem_list==0)
            elem_list[ind_face] = -1;
          else
            {
              DoubleTrav coord_elems(size_elem_list,dimension);
              IntList elems;
// Fill a list elems and coordinates of the elems
              for (int ind_elem=0; ind_elem<size_elem_list; ind_elem++)
                {
                  int elem = elem_list_par_pos[ind_elem];
                  elems.add_if_not(elem);
                  for (int dir=0; dir<dimension; dir++)
                    coord_elems(ind_elem,dir) = xp(elem,dir);
                }
              int elem_identifie;
              if (size_elem_list==1)
                {
// Easy, one element in the list
                  elem_identifie = elems[0];
                }
              else if (size_elem_list==2 && norme_array(delt_dist)==0)
                {
// Check first if it is not 2 elements surrounding 2 internal superposed boundary faces, in this
// case, discards the element linked to the local boundary face
                  int local_face = fr_vf2.num_premiere_face()+ind_face;
                  int local_elem = zvf.face_voisins(local_face,0);
                  if (local_elem==-1) local_elem = zvf.face_voisins(local_face,1);
// Cerr << "[" << Process::me() << "<->" << pe << "] nb_faces=" << fr_vf2.nb_faces() << " face= " << ind_face << " " << local_elem << " " << elems[0] << " " << elems[1] << finl;
                  if (elems[0]==local_elem)
                    elem_identifie=elems[1]; //!< Remote elem
                  else if (elems[1]==local_elem)
                    elem_identifie=elems[0]; //!< Remote elem
                  else
                    {
// Surely 2 elements surrounding an internal face so select one element:
                      elem_identifie = Zone::identifie_item_unique(elems,coord_elems,remote_point);
                    }
                }
              else
                {
// Find a unic remote elem:
                  elem_identifie = Zone::identifie_item_unique(elems,coord_elems,remote_point);
                }
              elem_list[ind_face] = (elem_identifie < nb_elem_zone1 ? elem_identifie : -1);
            }
        }
// We fill these three arrays:
      DoubleTab& coord1 = inconnues1_coords_to_eval_[pe];
      coord1.set_smart_resize(1);
      ArrOfInt& num_elem = inconnues1_elems_[pe];
      num_elem.set_smart_resize(1);
      ArrOfInt& index_to_recv = indexes_to_recv[pe];
      index_to_recv.set_smart_resize(1);
      int nb_remote_faces = 0;
// Loop on local faces on the process pe:
      for (int face = 0; face < nb_faces_on_pe; face++)
        {
          const int elem = elem_list[face];
          if (elem < 0 || elem >= nb_elem_zone1)
            {
// This coordinate is not on this processor...
            }
          else
            {
              coord1.resize(nb_remote_faces + 1, dim);
              for (int j = 0; j < dim; j++)
                coord1(nb_remote_faces, j) = remote_coords_on_pe(face, j);
              nb_remote_faces++;
              num_elem.append_array(elem);
              index_to_recv.append_array(face);
            }
        }
    }
// Send index_to_recv data to each processor
  envoyer_all_to_all(indexes_to_recv, inconnues2_faces_);
// Check that each coordinate is received from at least one processor:
  const int nb_faces2 = remote_coords[moi].dimension(0);
  ArrOfDouble count(nb_faces2);
  for (int pe = 0; pe < nprocs; pe++)
    {
      const ArrOfInt index_to_recv = inconnues2_faces_[pe];
      const int n = index_to_recv.size_array();
      for (int i = 0; i < n; i++)
        count[index_to_recv[i]] ++;
// Cerr << index_to_recv << finl;
    }
  int error_1 = 0;
  int error_2 = 0;
  for (int i = 0; i < nb_faces2; i++)
    {
      if (count[i] < 1)
        {
          Journal() << "Champ_front_recyclage : error face (number "<< i<< ") " << remote_coords[moi](i, 0) << " " << remote_coords[moi](i, 1) << " "
                    << ((dim==3)?remote_coords[moi](i, 2):0.) << " no matching element found" << finl;
          error_1 = 1;
        }
      else if (count[i]>1)
        {
          Journal() << "Champ_front_recyclage : error face (number "<< i<< ") " << remote_coords[moi](i, 0) << " " << remote_coords[moi](i, 1) << " "
                    << ((dim==3)?remote_coords[moi](i, 2):0.) << " " << count[i] << " corresponding points" << finl;
          error_2 = 1;
        }
    }
  if (mp_sum(error_1))
    {
      Cerr << "Error in Champ_front_recyclage.\n"
           << "No matching source element found for some faces of boundary " << nom_bord2
           << " (see log files)." << finl;
      Cerr << "If you are sure that boundary faces match with faces of the other domain, try adding this keyword:" << finl;
      Cerr << "PrecisionGeom 1.e-6" << finl;
      Cerr << "Just after the following keyword in your data file:" << finl;
      Cerr << "dimension " << Objet_U::dimension << finl;
      barrier();
      exit();
    }
  if (mp_sum(error_2))
    {
      Cerr << "Error in Champ_front_recyclage.\n"
           << "At least two elements match for some faces of boundary " << nom_bord2
           << " (see log files)." << finl;
      barrier();
      exit();
    }
  initialiser_moyenne_imposee(moyenne_imposee_);
  initialiser_moyenne_recyclee(moyenne_recyclee_);
  mettre_a_jour(temps);
  return 1;
}
References TRUSTList< _TYPE_ >::add_if_not(), ampli_fluct_, ampli_moy_imposee_, ampli_moy_recyclee_, TRUSTArray< _TYPE_ >::append_array(), associer_champ_evaluateur(), Process::barrier(), Cerr, Zone::construit_octree(), Array_base::COPY_INIT, delt_dist, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, vect_impl::dimensionner(), envoyer_all_to_all(), envoyer_broadcast(), MorEqn::equation(), Process::exit(), Zone_VF::face_voisins(), finl, Frontiere_dis_base::frontiere(), get_coord_faces(), Zone::identifie_item_unique(), inconnues1_coords_to_eval_, inconnues1_elems_, inconnues2_faces_, Ch_front_var_instationnaire_dep::initialiser(), initialiser_moyenne_imposee(), initialiser_moyenne_recyclee(), Process::Journal(), l_inconnue1, Champ_front_base::la_frontiere_dis, Frontiere::le_nom(), Process::me(), mettre_a_jour(), moyenne_imposee_, moyenne_recyclee_, Process::mp_sum(), Field_base::nb_compo_, Zone::nb_elem(), Front_VF::nb_faces(), Array_base::NOCOPY_NOINIT, nom_inco1, nom_pb1, norme_array(), Process::nproc(), Front_VF::num_premiere_face(), OctreeRoot::rang_elems_sommet(), ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_tab(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTVect< _TYPE_ >::size(), TRUSTArray< _TYPE_ >::size_array(), Ref_Champ_Inc_base::valeur(), Ref_Frontiere_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), Zone_VF::xp(), Zone_dis_base::zone(), and Equation_base::zone_dis().
initialiser_moyenne_imposee()
void Champ_front_recyclage::initialiser_moyenne_imposee (DoubleTab & moyenne)
Definition at line 769 of file Champ_front_recyclage.cpp.
{
  const Front_VF& fr_vf2 = ref_cast(Front_VF,la_frontiere_dis.valeur());
  if (methode_moy_impos_==1)
    {
      profil_2.dimensionner(nb_compo_);
      for (int i=0; i<nb_compo_; i++)
        {
          profil_2[i].setNbVar(4);
          profil_2[i].setString(fcts_xyz[i]);
          profil_2[i].addVar("t");
          profil_2[i].addVar("x");
          profil_2[i].addVar("y");
          profil_2[i].addVar("z");
          profil_2[i].parseString();
        }
    }
  else if (methode_moy_impos_==2)
    {
      lire_fichier_format1(moyenne_imposee_,fr_vf2,fich_impos_);
    }
  else if (methode_moy_impos_==3)
    {
      lire_fichier_format2(moyenne_imposee_,fr_vf2,fich_impos_);
    }
  else if (methode_moy_impos_==4)
    {
      lire_fichier_format3(moyenne_imposee_,fr_vf2,fich_impos_,fich_maillage_);
    }
  else if (methode_moy_impos_==5)
    {
      const Zone_dis_base& zone_dis2 = fr_vf2.zone_dis();
      const Zone_VF& la_zone2        = ref_cast(Zone_VF,zone_dis2);
      const DoubleTab&  xv2          = la_zone2.xv();
      double Kappa = 0.41;
      double d_paroi,y_plus,U_log;
      int nbface2 = fr_vf2.nb_faces();
      int num1 = fr_vf2.num_premiere_face();
      int num2 = num1 + nbface2;
      int num_face_loc;
      for (int num_face2=num1; num_face2<num2; num_face2++)
        {
          num_face_loc = num_face2-num1;
          d_paroi = diametre/2.;
          if(dimension==3)
            {
              if(abs(ndir)==1) d_paroi -= sqrt(xv2(num_face2,1)*xv2(num_face2,1) + xv2(num_face2,2)*xv2(num_face2,2));
              if(abs(ndir)==2) d_paroi -= sqrt(xv2(num_face2,0)*xv2(num_face2,0) + xv2(num_face2,2)*xv2(num_face2,2));
              if(abs(ndir)==3) d_paroi -= sqrt(xv2(num_face2,0)*xv2(num_face2,0) + xv2(num_face2,1)*xv2(num_face2,1));
            }
          else
            {
              if(abs(ndir)==1) d_paroi -= sqrt(xv2(num_face2,1)*xv2(num_face2,1));
              if(abs(ndir)==2) d_paroi -= sqrt(xv2(num_face2,0)*xv2(num_face2,0));
            }
          y_plus = d_paroi*u_tau/visco_cin;
          U_log  = (1./Kappa)*log(y_plus) + 5.1;
          U_log *=  u_tau;
          U_log *= ndir/abs(ndir);
          for (int dir=0; dir<nb_compo_; dir++)
            moyenne(num_face_loc,dir) = ((dir+1)==abs(ndir))*U_log;
        }
    }
}
References diametre, Objet_U::dimension, vect_impl::dimensionner(), fcts_xyz, fich_impos_, fich_maillage_, Champ_front_base::la_frontiere_dis, lire_fichier_format1(), lire_fichier_format2(), lire_fichier_format3(), methode_moy_impos_, moyenne_imposee_, Field_base::nb_compo_, Front_VF::nb_faces(), ndir, Front_VF::num_premiere_face(), profil_2, ref_cast, u_tau, Ref_Frontiere_dis_base::valeur(), visco_cin, Zone_VF::xv(), and Frontiere_dis_base::zone_dis().
Referenced by initialiser().
initialiser_moyenne_recyclee()
void Champ_front_recyclage::initialiser_moyenne_recyclee (DoubleTab & moyenne)
Definition at line 845 of file Champ_front_recyclage.cpp.
{
  const Front_VF& fr_vf2 = ref_cast(Front_VF,la_frontiere_dis.valeur());
  if (methode_moy_recycl_==2)
    {
      lire_fichier_format1(moyenne_recyclee_,fr_vf2,fich_recycl_);
    }
  else if (methode_moy_recycl_==3)
    {
      lire_fichier_format2(moyenne_recyclee_,fr_vf2,fich_recycl_);
    }
  else if (methode_moy_recycl_==4)
    {
      lire_fichier_format3(moyenne_recyclee_,fr_vf2,fich_recycl_,fich_maillage_);
    }
}
References fich_maillage_, fich_recycl_, Champ_front_base::la_frontiere_dis, lire_fichier_format1(), lire_fichier_format2(), lire_fichier_format3(), methode_moy_recycl_, moyenne_recyclee_, ref_cast, and Ref_Frontiere_dis_base::valeur().
Referenced by initialiser().
lire_fichier_format1()
void Champ_front_recyclage::lire_fichier_format1 (DoubleTab & moyenne, const Frontiere_dis_base & fr_vf, const Nom & nom_fich)
Definition at line 1062 of file Champ_front_recyclage.cpp.
{
  const Front_VF& fr_vf2 = ref_cast(Front_VF,fr_vf);
  DoubleTab coords;
  get_coord_faces(fr_vf2,coords,delt_dist);
  const int nb_faces2 = coords.dimension(0);
  int dir_ortho = -1;
  if ((ndir==1) || (ndir==2))
    dir_ortho = ndir;
  else if (ndir==3)
    dir_ortho = 0;
  else
    {
      Cerr<<"For this method the anisotropic direction mut be 1 2 or 3"<<finl;
      exit();
    }
  for (int i=0; i<nb_faces2; i++)
    {
      double y = coords(i,dir_ortho);
      moyenne(i,ndir-1) = UPb(y,nom_fich);
    }
}
References Cerr, delt_dist, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, get_coord_faces(), ndir, ref_cast, and UPb().
Referenced by initialiser_moyenne_imposee(), and initialiser_moyenne_recyclee().
lire_fichier_format2()
void Champ_front_recyclage::lire_fichier_format2 (DoubleTab & moyenne, const Frontiere_dis_base & fr_vf, const Nom & nom_fich)
< test
Definition at line 1099 of file Champ_front_recyclage.cpp.
{
  int N1;
  int num_face1, indice_compo;
  int num_face2, num_face2_loc;
  double x1,y1,z1;
  double x2,y2,z2;
  z2 = 0.;
  DoubleVect val(nb_compo_);
// Read the file and keep in memory
  ifstream fic_Utargtest(nom_fich); //!< test
  if (!fic_Utargtest)
    {
      Cerr <<"No file of name : "<<nom_fich<<" is available."<<finl;
      exit();
    }
  LecFicDiffuse fic_Utarg(nom_fich, ios::in);
  fic_Utarg >> N1;
  ArrOfDouble fich_buffer(N1*(nb_compo_+dimension));
  fic_Utarg.get(fich_buffer.addr(), fich_buffer.size_array());
  fic_Utarg.close();
  const Front_VF& fr_vf2 = ref_cast(Front_VF,fr_vf);
  int num1 = fr_vf2.num_premiere_face();
  int num2 = num1 + fr_vf2.nb_faces();
  const Zone_dis_base& zone_dis2 = fr_vf2.zone_dis();
  const Zone_VF& zvf2 = ref_cast(Zone_VF,zone_dis2);
  const DoubleTab& xv2 = zvf2.xv();
  for (num_face2=num1; num_face2<num2; num_face2++)
    {
      x2 = xv2(num_face2,0);
      y2 = xv2(num_face2,1);
      if (dimension==3) z2 = xv2(num_face2,2);
      num_face2_loc = num_face2-num1;
      double dist = 1.E6;
      double dist_eval;
      for (num_face1=0; num_face1<N1; num_face1++)
        {
          x1 = fich_buffer[num_face1*(nb_compo_+dimension)];
          y1 = fich_buffer[num_face1*(nb_compo_+dimension)+1];
          if(dimension==3) z1 = fich_buffer[num_face1*(nb_compo_+dimension)+2];
          dist_eval = (x2-x1)*(x2-x1)+(y2-y1)*(y2-y1);
          if (dimension==3) dist_eval+=(z2-z1)*(z2-z1);
          if(dist_eval<dist)
            {
              for (indice_compo=0; indice_compo<nb_compo_; indice_compo++)
                val(indice_compo) = fich_buffer[num_face1*(nb_compo_+dimension)+dimension+indice_compo];
              dist = dist_eval;
              if ((abs(ndir)<4) && (abs(ndir)>0))
                moyenne(num_face2_loc,abs(ndir)-1) = val(abs(ndir)-1);
              else
                for (indice_compo=0; indice_compo<nb_compo_; indice_compo++)
                  moyenne(num_face2_loc,indice_compo) = val(indice_compo);
            }
        }
    }
}
References TRUSTArray< _TYPE_ >::addr(), Cerr, Entree_Fichier_base::close(), Objet_U::dimension, Process::exit(), finl, Lec_Diffuse_base::get(), Field_base::nb_compo_, Front_VF::nb_faces(), ndir, Front_VF::num_premiere_face(), ref_cast, TRUSTArray< _TYPE_ >::size_array(), Zone_VF::xv(), and Frontiere_dis_base::zone_dis().
Referenced by initialiser_moyenne_imposee(), and initialiser_moyenne_recyclee().
lire_fichier_format3()
void Champ_front_recyclage::lire_fichier_format3 (DoubleTab & moyenne, const Frontiere_dis_base & fr_vf, const Nom & nom_fich1, const Nom & nom_fich2)
< useless but we must read it
Definition at line 1172 of file Champ_front_recyclage.cpp.
{
  int Nbfaces,trouve,compteur;
  int num_face2,num_face2_loc;
  double x1=0.,y1=0.,z1=0.;
  double x2=0.,y2=0.,z2=0.;
  double eps=1.e-4;
  Nom fichier = "VERIF_face_perio.";
  fichier += nom_pb1;
  EcrFicCollecte fic(fichier);
  ifstream fic_geom_test(nom_fich2);
  if (!fic_geom_test)
    {
      Cerr <<"No file of name : "<<nom_fich2<<" is available."<<finl;
      exit();
    }
  ifstream fic_Umoy_test(nom_fich1);
  if (!fic_Umoy_test)
    {
      Cerr <<"No file of name : "<<nom_fich1<<" is available."<<finl;
      exit();
    }
  if (abs(ndir)!=1 && abs(ndir)!=2 && abs(ndir)!=3)
    {
      Cerr << finl;
      Cerr << "Error while reading the boundary condition " << fr_vf.le_nom() << finl;
      Cerr << "You must define the keyword \"direction_anisotrope\"" << finl;
      exit();
    }
  if (abs(ndir)==3 && dimension==2)
    {
      Cerr << finl;
      Cerr << "Error while reading the boundary condition " << fr_vf.le_nom() << finl;
      Cerr << "You must define the keyword \"direction_anisotrope\" with a direction different than 'z' in 2D" << finl;
      exit();
    }
  const Front_VF& fr_vf2 = ref_cast(Front_VF,fr_vf);
  int num1 = fr_vf2.num_premiere_face();
  int num2 = num1 + fr_vf2.nb_faces();
  const Zone_dis_base& zone_dis2 = fr_vf2.zone_dis();
  const Zone_VF& zvf2 = ref_cast(Zone_VF,zone_dis2);
  const DoubleTab& xv2 = zvf2.xv();
// Reading and buffering the two input files
  LecFicDiffuse fic_geom(nom_fich2);
  LecFicDiffuse fic_Umoy(nom_fich1);
  fic_geom >> Nbfaces;
  fic_Umoy >> Nbfaces; //!< useless but we must read it
  ArrOfDouble fich_geom_buffer(Nbfaces*(dimension+1));
  ArrOfDouble fich_Umoy_buffer(Nbfaces*(dimension+1));
  fic_geom.get(fich_geom_buffer.addr(), fich_geom_buffer.size_array());
  fic_Umoy.get(fich_Umoy_buffer.addr(), fich_Umoy_buffer.size_array());
  fic_geom.close();
  fic_Umoy.close();
  for (num_face2=num1; num_face2<num2; num_face2++)
    {
      x2 = xv2(num_face2,0);
      y2 = xv2(num_face2,1);
      if (dimension==3) z2 = xv2(num_face2,2);
      num_face2_loc = num_face2-num1;
      trouve = 0;
      compteur = 0;
// Looking for (x2,y2[,z2]) into (x1,y1[,z1])
      while (compteur<Nbfaces)
        {
          x1 = fich_geom_buffer[compteur*(dimension+1)+1];
          y1 = fich_geom_buffer[compteur*(dimension+1)+2];
          if (dimension==3)
            {
              z1 = fich_geom_buffer[compteur*(dimension+1)+3];
              if(abs(ndir)==1 && (est_egal(y1,y2,eps)) && (est_egal(z1,z2,eps))) trouve=1;
              if(abs(ndir)==2 && (est_egal(x1,x2,eps)) && (est_egal(z1,z2,eps))) trouve=1;
              if(abs(ndir)==3 && (est_egal(x1,x2,eps)) && (est_egal(y1,y2,eps))) trouve=1;
            }
          else
            {
              if(abs(ndir)==1 && (est_egal(y1,y2,eps))) trouve=1;
              if(abs(ndir)==2 && (est_egal(x1,x2,eps))) trouve=1;
            }
          if (trouve)
            {
              moyenne(num_face2_loc,0) = fich_Umoy_buffer[compteur*(dimension+1)+1];
              moyenne(num_face2_loc,1) = fich_Umoy_buffer[compteur*(dimension+1)+2];
              if (dimension==3) moyenne(num_face2_loc,2) = fich_Umoy_buffer[compteur*(dimension+1)+3];
              break;
            }
          compteur++;
        }
      if (trouve==0)
        {
          Cerr << " the face "<<num_face2<<" with coordinates : x="<<x2<<" y="<<y2;
          if (dimension==3)
            Cerr << " z="<<z2;
          Cerr << "\n has no corresponding faces in "<<nom_fich2<<finl;
          exit();
        }
      if (dimension==3)
        {
          fic <<" num_face1 " << fich_geom_buffer[compteur*(dimension+1)]  << " " << x1 << " " << y1 << " " << z1 << finl;
          fic <<" num_face2 " << num_face2  << " " << x2 << " " << y2 << " " << z2 << finl;
          fic <<" "  << finl;
        }
      else
        {
          fic <<" num_face1 " << fich_geom_buffer[compteur*(dimension+1)]  << " " << x1 << " " << y1  << finl;
          fic <<" num_face2 " << num_face2  << " " << x2 << " " << y2  << finl;
          fic <<" "  << finl;
        }
    }
  fic.close();
}
References TRUSTArray< _TYPE_ >::addr(), Cerr, Entree_Fichier_base::close(), Sortie_Fichier_base::close(), compteur, Objet_U::dimension, est_egal(), Process::exit(), finl, Lec_Diffuse_base::get(), Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), ndir, nom_pb1, Front_VF::num_premiere_face(), ref_cast, TRUSTArray< _TYPE_ >::size_array(), Zone_VF::xv(), and Frontiere_dis_base::zone_dis().
Referenced by initialiser_moyenne_imposee(), and initialiser_moyenne_recyclee().
lire_info_moyenne_imposee()
int Champ_front_recyclage::lire_info_moyenne_imposee (Entree & is)
Definition at line 199 of file Champ_front_recyclage.cpp.
{
  int methode = -1;;
  Motcle choix,motlu;
  Motcles les_mots(5);
  {
    les_mots[0] = "profil";
    les_mots[1] = "interpolation";
    les_mots[2] = "connexion_approchee";
    les_mots[3] = "connexion_exacte";
    les_mots[4] = "logarithmique";
  }
  is >> choix;
  int rang = les_mots.search(choix);
  switch(rang)
    {
    case 0 :
      {
        methode = 1;
        int nc;
        is >> nc;
        fcts_xyz.dimensionner(nc);
        for (int i=0; i<nc; i++)
          is >> fcts_xyz[i];
        break;
      }
    case 1 :
      {
        methode = 2;
        break;
      }
    case 2 :
      {
        methode = 3;
        break;
      }
    case 3 :
      {
        methode = 4;
        break;
      }
    case 4 :
      {
        int compt_mot_lu = 0;
        while (compt_mot_lu!=4)
          {
            is >> motlu;
            if (motlu=="diametre")
              is >> diametre;
            else if (motlu=="u_tau")
              is >> u_tau;
            else if (motlu=="visco_cin")
              is >> visco_cin;
            else if (motlu=="direction")
              is >> ndir;
            else
              {
                Cerr<<"The keyword "<<motlu<<" is not recognized."<<finl;
              }
            compt_mot_lu += 1;
          }
        if (diametre<=0.)
          {
            Cerr<<"Champ_front_recyclage : a positive diameter must be specified when a logarithmique injected averaged is used."<<finl;
            exit();
          }
        if (u_tau<=0.)
          {
            Cerr<<"Champ_front_recyclage : a positive shear velocity must be specified when a logarithmique injected averaged is used."<<finl;
            exit();
          }
        if (visco_cin<=0.)
          {
            Cerr<<"Champ_front_recyclage : a positive kinematic viscosity must be specified when a logarithmique injected averaged is used."<<finl;
            exit();
          }
        if (ndir<-3)
          {
            Cerr<<"Champ_front_recyclage : the direction must be specified when a logarithmique injected averaged is used."<<finl;
            exit();
          }
        methode = 5;
        break;
      }
    default :
      {
        Cerr<<"Champ_front_recyclage::lire_info_moyenne_imposee : keyword "<<choix<<" is not recognized."<<finl;
        Cerr<<"The recognized keywords are :"<<les_mots<<finl;
        exit();
      }
    }
  if ((methode == 2) || (methode == 3))
    {
      Nom nom_fich;
      is >> motlu;
      if (motlu!="fichier")
        {
          Cerr<<"Champ_front_recyclage::lire_info_moyenne_imposee : at least one file must be provided for this method."<<finl;
          exit();
        }
      else
        is >> nom_fich;
      fich_impos_ = nom_fich;
    }
  if (methode == 4)
    {
      Nom nom_fich;
      is >> motlu;
      if (motlu!="fichier")
        {
          Cerr<<"Champ_front_recyclage::lire_info_moyenne_imposee : at least one file must be provided for this method."<<finl;
          exit();
        }
      else
        is >> nom_fich;
      fich_maillage_ = nom_fich;
      is >> nom_fich;
      fich_impos_ = nom_fich;
    }
  if (methode==-1)
    {
      Cerr<<"Champ_front_recyclage::lire_info_moyenne_imposee : no method to make average evaluation has been given."<<finl;
      Cerr<<"Choose among the following keywords : les_mots"<<finl;
      exit();
    }
  return methode;
}
References Cerr, diametre, vect_impl::dimensionner(), Process::exit(), fcts_xyz, fich_impos_, fich_maillage_, finl, ndir, Motcles::search(), u_tau, and visco_cin.
Referenced by readOn().
lire_info_moyenne_recyclee()
int Champ_front_recyclage::lire_info_moyenne_recyclee (Entree & is)
Definition at line 339 of file Champ_front_recyclage.cpp.
{
  int methode = -1;
  Motcle choix,motlu;
  Motcles les_mots(4);
  {
    les_mots[0] = "surfacique";
    les_mots[1] = "interpolation";
    les_mots[2] = "connexion_approchee";
    les_mots[3] = "connexion_exacte";
  }
  is >> choix;
  int rang = les_mots.search(choix);
  switch(rang)
    {
    case 0 :
      {
        methode = 1;
        break;
      }
    case 1 :
      {
        methode = 2;
        break;
      }
    case 2 :
      {
        methode = 3;
        break;
      }
    case 3 :
      {
        methode = 4;
        break;
      }
    default :
      {
        Cerr<<"Champ_front_recyclage::lire_info_moyenne_recyclee keyword "<<choix<<" is not recognized."<<finl;
        Cerr<<"The recognized keywords are :"<<les_mots<<finl;
        exit();
      }
    }
  if ((methode == 2) || (methode == 3) || (methode == 4))
    {
      Nom nom_fich;
      is >> motlu;
      if (motlu!="fichier")
        {
          Cerr<<"Champ_front_recyclage::lire_info_moyenne_recyclee : a file must be provided for this method."<<finl;
          exit();
        }
      else
        is >> nom_fich;
      fich_recycl_  = nom_fich;
      if (methode == 4)
        is >> nom_fich;
      fich_maillage_ = nom_fich;
    }
  if (methode==-1)
    {
      Cerr<<"Champ_front_recyclage::lire_info_moyenne_recyclee : no method to make average evaluation has been given."<<finl;
      Cerr<<"Choose among the following keywords : les_mots"<<finl;
      exit();
    }
  return methode;
}
References Cerr, Process::exit(), fich_maillage_, fich_recycl_, finl, and Motcles::search().
Referenced by readOn().
mettre_a_jour()
void Champ_front_recyclage::mettre_a_jour (double temps) override virtual
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
Reimplemented from Champ_front_base.
Definition at line 715 of file Champ_front_recyclage.cpp.
{
  DoubleTab& tab = valeurs_au_temps(temps);
  const int nprocs = nproc();
  DoubleTabs values_to_send(nprocs);
  DoubleTabs values_to_recv(nprocs);
// temporary array (because valeur_aux_elems wants intvect and not arrofint)
  IntVect elems;
  elems.set_smart_resize(1);
  for (int pe = 0; pe < nprocs; pe++)
    {
      elems.resize(inconnues1_elems_[pe].size_array());
      elems.inject_array(inconnues1_elems_[pe]);
      const int n = elems.size_array();
      values_to_send[pe].resize(n,nb_compo_);
      l_inconnue1.valeur().valeur_aux_elems(inconnues1_coords_to_eval_[pe],
                                            elems,
                                            values_to_send[pe]);
    }
  envoyer_all_to_all(values_to_send, values_to_recv);
  for (int pe = 0; pe < nprocs; pe++)
    {
      const DoubleTab& values = values_to_recv[pe];
      const ArrOfInt index_to_recv = inconnues2_faces_[pe];
      const int n = index_to_recv.size_array();
      for (int i = 0; i < n; i++)
        {
          const int idx = index_to_recv[i];
          for (int j = 0; j < nb_compo_; j++)
            tab(idx, j) = values(i, j);
        }
    }
  const Front_VF& fr_vf2 = ref_cast(Front_VF,la_frontiere_dis.valeur());
  int nb_faces2 = fr_vf2.nb_faces();
  calcul_moyenne_imposee(tab,temps);
  calcul_moyenne_recyclee(tab,temps);
  for (int i=0; i<nb_faces2; i++)
    for (int dir=0; dir<nb_compo_; dir++)
      tab(i,dir) = ampli_moy_imposee_(dir)*moyenne_imposee_(i,dir) + ampli_fluct_(dir)*(tab(i,dir)-ampli_moy_recyclee_(dir)*moyenne_recyclee_(i,dir));
  tab.echange_espace_virtuel();
}
References ampli_fluct_, ampli_moy_imposee_, ampli_moy_recyclee_, calcul_moyenne_imposee(), calcul_moyenne_recyclee(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), envoyer_all_to_all(), inconnues1_coords_to_eval_, inconnues1_elems_, inconnues2_faces_, TRUSTArray< _TYPE_ >::inject_array(), l_inconnue1, Champ_front_base::la_frontiere_dis, moyenne_imposee_, moyenne_recyclee_, Field_base::nb_compo_, Front_VF::nb_faces(), Process::nproc(), ref_cast, TRUSTVect< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), Ref_Champ_Inc_base::valeur(), Ref_Frontiere_dis_base::valeur(), Champ_base::valeur_aux_elems(), and Champ_front_var_instationnaire::valeurs_au_temps().
Referenced by initialiser().
printOn()
Sortie & Champ_front_recyclage::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 54 of file Champ_front_recyclage.cpp.
{
  return os;
}
readOn()
Entree & Champ_front_recyclage::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 63 of file Champ_front_recyclage.cpp.
{
  int dim = Objet_U::dimension;
  int lu_info_evaluateur = 0;
  int nbcomp;
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
  Motcles les_mots(8);
  {
    les_mots[0] = "pb_champ_evaluateur";
    les_mots[1] = "distance_plan";
    les_mots[2] = "ampli_fluctuation";
    les_mots[3] = "ampli_moyenne_imposee";
    les_mots[4] = "ampli_moyenne_recyclee";
    les_mots[5] = "moyenne_imposee";
    les_mots[6] = "moyenne_recyclee";
    les_mots[7] = "direction_anisotrope";
  }
  is >> motlu;
  if(motlu!=accolade_ouverte)
    {
      Cerr << "We expected a { while reading of " << que_suis_je() << finl;
      Cerr << "and not : " << motlu << finl;
      exit();
    }
  is >> motlu;
  Cerr<<"word read="<<motlu<<finl;
  while (motlu != accolade_fermee)
    {
      int rang = les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          {
            is >> nom_pb1 >> nom_inco1 >> nbcomp;
            lu_info_evaluateur = 1;
            ampli_fluct_.resize(nbcomp,Array_base::NOCOPY_NOINIT);
            ampli_moy_imposee_.resize(nbcomp,Array_base::NOCOPY_NOINIT);
            ampli_moy_recyclee_.resize(nbcomp,Array_base::NOCOPY_NOINIT);
            ampli_fluct_ = 1.;
            ampli_moy_imposee_ = 1.;
            ampli_moy_recyclee_ = 1.;
            break;
          }
        case 1 :
          {
            for (int i=0; i<dim; i++)
              is >> delt_dist(i) ;
            break;
          }
        case 2 :
          {
// int nbcomp;
            is >> nbcomp;
            ampli_fluct_.resize(nbcomp);
            for (int i=0; i<nbcomp; i++)
              is >> ampli_fluct_(i) ;
            break;
          }
        case 3 :
          {
// int nbcomp;
            is >> nbcomp;
            ampli_moy_imposee_.resize(nbcomp);
            for (int i=0; i<nbcomp; i++)
              is >> ampli_moy_imposee_(i) ;
            break;
          }
        case 4 :
          {
// int nbcomp;
            is >> nbcomp;
            ampli_moy_recyclee_.resize(nbcomp);
            for (int i=0; i<nbcomp; i++)
              is >> ampli_moy_recyclee_(i) ;
            break;
          }
        case 5 :
          {
            methode_moy_impos_ = lire_info_moyenne_imposee(is);
            break;
          }
        case 6 :
          {
            methode_moy_recycl_ = lire_info_moyenne_recyclee(is);
            break;
          }
        case 7 :
          {
            is >> ndir;
            break;
          }
        default :
          {
            Cerr<<"Champ_front_recyclage::readOn: keyword "<<motlu<<" is not recognized."<<finl;
            Cerr<<"The recognized keywords are :"<<les_mots<<finl;
            exit();
          }
        }
      is >> motlu;
    }
  if (lu_info_evaluateur!=1)
    {
      Cerr<<"Keyword pb_champ_evaluateur must be specified with associated data"<<finl;
      Cerr<<"when Champ_front_recyclage field is used."<<finl;
      exit();
    }
  fixer_nb_comp(nbcomp);
  return is;
}
References ampli_fluct_, ampli_moy_imposee_, ampli_moy_recyclee_, Cerr, delt_dist, Objet_U::dimension, Process::exit(), finl, Field_base::fixer_nb_comp(), lire_info_moyenne_imposee(), lire_info_moyenne_recyclee(), methode_moy_impos_, methode_moy_recycl_, ndir, Array_base::NOCOPY_NOINIT, nom_inco1, nom_pb1, Objet_U::que_suis_je(), TRUSTVect< _TYPE_ >::resize(), and Motcles::search().
self_cast() [1/2]
const Champ_front_recyclage & Champ_front_recyclage::self_cast (const Objet_U & r) static
Definition at line 30 of file Champ_front_recyclage.cpp.
self_cast() [2/2]
Champ_front_recyclage & Champ_front_recyclage::self_cast (Objet_U & r) static
Definition at line 30 of file Champ_front_recyclage.cpp.
taille_memoire()
unsigned Champ_front_recyclage::taille_memoire () const override virtual
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 30 of file Champ_front_recyclage.cpp.
UPb()
double Champ_front_recyclage::UPb (double y, Nom nom_fich)
Definition at line 975 of file Champ_front_recyclage.cpp.
{
  int nb_pts;
  DoubleVect y_Pb2;
  DoubleVect U_Pb2;
  int l=0;
  if (Process::je_suis_maitre())
    {
      EFichier fich_Pb2(nom_fich);
      while (!fich_Pb2.eof())
        {
          y_Pb2.resize(l+1);
          U_Pb2.resize(l+1);
          fich_Pb2 >> y_Pb2(l) >> U_Pb2(l);
          l++;
        }
      fich_Pb2.close();
    }
  envoyer_broadcast(l,0);
  if (!(Process::je_suis_maitre()))
    {
      y_Pb2.resize(l);
      U_Pb2.resize(l);
    }
  envoyer_broadcast(y_Pb2,0);
  envoyer_broadcast(U_Pb2,0);
  nb_pts=l-1;
  y_Pb2.resize(nb_pts);
  U_Pb2.resize(nb_pts);
  l=0;
  int l_deb;
  while ((y>y_Pb2(l)) && (l<nb_pts))
    {
      l++;
    }
  if (l<2)
    {
      l_deb=0;
    }
  else
    {
      if (l>(nb_pts-2))
        {
          l_deb=nb_pts-3;
        }
      else
        {
          if ( (y-y_Pb2(l-1)) > (y_Pb2(l)-y) )
            {
              l_deb=l-2;
            }
          else
            {
              l_deb=l-1;
            }
        }
    }
  double ya=y_Pb2(l_deb);
  double Ua=U_Pb2(l_deb);
  double yb=y_Pb2(l_deb+1);
  double Ub=U_Pb2(l_deb+1);
  double yc=y_Pb2(l_deb+2);
  double Uc=U_Pb2(l_deb+2);
  double U;
  U=(y-ya)*(y-yb)/(yc-ya)/(yc-yb)*Uc;
  U+=(y-yb)*(y-yc)/(ya-yb)/(ya-yc)*Ua;
  U+=(y-yc)*(y-ya)/(yb-yc)/(yb-ya)*Ub;
  return U;
}
References Entree_Fichier_base::close(), envoyer_broadcast(), Entree_Fichier_base::eof(), Process::je_suis_maitre(), and TRUSTVect< _TYPE_ >::resize().
Referenced by lire_fichier_format1().
Member Data Documentation
ampli_fluct_
DoubleVect Champ_front_recyclage::ampli_fluct_ protected
Definition at line 179 of file Champ_front_recyclage.h.
Referenced by Champ_front_recyclage(), initialiser(), mettre_a_jour(), and readOn().
ampli_moy_imposee_
DoubleVect Champ_front_recyclage::ampli_moy_imposee_ protected
Definition at line 180 of file Champ_front_recyclage.h.
Referenced by Champ_front_recyclage(), initialiser(), mettre_a_jour(), and readOn().
ampli_moy_recyclee_
DoubleVect Champ_front_recyclage::ampli_moy_recyclee_ protected
Definition at line 181 of file Champ_front_recyclage.h.
Referenced by Champ_front_recyclage(), initialiser(), mettre_a_jour(), and readOn().
delt_dist
DoubleVect Champ_front_recyclage::delt_dist protected
Definition at line 170 of file Champ_front_recyclage.h.
Referenced by Champ_front_recyclage(), get_coord_faces(), initialiser(), lire_fichier_format1(), and readOn().
diametre
double Champ_front_recyclage::diametre protected
Definition at line 194 of file Champ_front_recyclage.h.
Referenced by Champ_front_recyclage(), initialiser_moyenne_imposee(), and lire_info_moyenne_imposee().
fcts_xyz
Noms Champ_front_recyclage::fcts_xyz protected
Definition at line 192 of file Champ_front_recyclage.h.
Referenced by initialiser_moyenne_imposee(), and lire_info_moyenne_imposee().
fich_impos_
Nom Champ_front_recyclage::fich_impos_ protected
Definition at line 186 of file Champ_front_recyclage.h.
Referenced by Champ_front_recyclage(), initialiser_moyenne_imposee(), and lire_info_moyenne_imposee().
fich_maillage_
Nom Champ_front_recyclage::fich_maillage_ protected
Definition at line 187 of file Champ_front_recyclage.h.
Referenced by initialiser_moyenne_imposee(), initialiser_moyenne_recyclee(), lire_info_moyenne_imposee(), and lire_info_moyenne_recyclee().
fich_recycl_
Nom Champ_front_recyclage::fich_recycl_ protected
Definition at line 186 of file Champ_front_recyclage.h.
Referenced by Champ_front_recyclage(), initialiser_moyenne_recyclee(), and lire_info_moyenne_recyclee().
inconnues1_coords_to_eval_
DoubleTabs Champ_front_recyclage::inconnues1_coords_to_eval_ protected
Definition at line 201 of file Champ_front_recyclage.h.
Referenced by initialiser(), and mettre_a_jour().
inconnues1_elems_
ArrsOfInt Champ_front_recyclage::inconnues1_elems_ protected
Definition at line 205 of file Champ_front_recyclage.h.
Referenced by initialiser(), and mettre_a_jour().
inconnues2_faces_
ArrsOfInt Champ_front_recyclage::inconnues2_faces_ protected
Definition at line 209 of file Champ_front_recyclage.h.
Referenced by initialiser(), and mettre_a_jour().
info_obj
const Type_info Champ_front_recyclage::info_obj static
Definition at line 135 of file Champ_front_recyclage.h.
l_inconnue1
Ref_Champ_Inc_base Champ_front_recyclage::l_inconnue1 protected
Definition at line 167 of file Champ_front_recyclage.h.
Referenced by associer_champ_evaluateur(), initialiser(), and mettre_a_jour().
methode_moy_impos_
int Champ_front_recyclage::methode_moy_impos_ protected
Definition at line 183 of file Champ_front_recyclage.h.
Referenced by calcul_moyenne_imposee(), Champ_front_recyclage(), initialiser_moyenne_imposee(), and readOn().
methode_moy_recycl_
int Champ_front_recyclage::methode_moy_recycl_ protected
Definition at line 184 of file Champ_front_recyclage.h.
Referenced by calcul_moyenne_recyclee(), Champ_front_recyclage(), initialiser_moyenne_recyclee(), and readOn().
moyenne_imposee_
DoubleTab Champ_front_recyclage::moyenne_imposee_ protected
Definition at line 177 of file Champ_front_recyclage.h.
Referenced by calcul_moyenne_imposee(), initialiser(), initialiser_moyenne_imposee(), and mettre_a_jour().
moyenne_recyclee_
DoubleTab Champ_front_recyclage::moyenne_recyclee_ protected
Definition at line 178 of file Champ_front_recyclage.h.
Referenced by calcul_moyenne_recyclee(), initialiser(), initialiser_moyenne_recyclee(), and mettre_a_jour().
ndir
int Champ_front_recyclage::ndir protected
Definition at line 189 of file Champ_front_recyclage.h.
Referenced by Champ_front_recyclage(), initialiser_moyenne_imposee(), lire_fichier_format1(), lire_fichier_format2(), lire_fichier_format3(), lire_info_moyenne_imposee(), and readOn().
nom_inco1
Motcle Champ_front_recyclage::nom_inco1 protected
Definition at line 175 of file Champ_front_recyclage.h.
Referenced by initialiser(), and readOn().
nom_pb1
Nom Champ_front_recyclage::nom_pb1 protected
Definition at line 173 of file Champ_front_recyclage.h.
Referenced by initialiser(), lire_fichier_format3(), and readOn().
profil_2
Vect_Parser_U Champ_front_recyclage::profil_2 protected
Definition at line 191 of file Champ_front_recyclage.h.
Referenced by calcul_moyenne_imposee(), and initialiser_moyenne_imposee().
u_tau
double Champ_front_recyclage::u_tau protected
Definition at line 194 of file Champ_front_recyclage.h.
Referenced by Champ_front_recyclage(), initialiser_moyenne_imposee(), and lire_info_moyenne_imposee().
visco_cin
double Champ_front_recyclage::visco_cin protected
Definition at line 194 of file Champ_front_recyclage.h.
Referenced by Champ_front_recyclage(), initialiser_moyenne_imposee(), and lire_info_moyenne_imposee().
The documentation for this class was generated from the following files:
src/Kernel/VF/Champs/Champ_front_recyclage.h
src/Kernel/VF/Champs/Champ_front_recyclage.cpp