TRUST: Domaine_dis Class Reference
Domaine_dis Class Reference
#include <Domaine_dis.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Domaine_dis ()
~Domaine_dis () override
int nombre_de_zones () const
Renvoie le nombre de zones contenues dans le domaine.
const Zone_dis & zone_dis (int) const
Renvoie une reference sur la i-eme zone discretisee du domaine.
(version const)
Zone_dis & zone_dis (int)
Renvoie une reference sur la i-eme zone discretisee du domaine.
int nombre_de_sous_zones_dis () const
const Sous_zone_dis & sous_zone_dis (int i) const
Sous_zone_dis & sous_zone_dis (int i)
void associer_domaine (const Domaine &)
Associe un Domaine (non discretise) a l'objet.
Dimensionne le tableau des zones discretisees associees
au domaine.
void discretiser (const Nom &)
Discretise le domaine.
On type et on discretise chaque zone discretisee du domaine discretise
grace a la discretisation passee en parametre.
Domaine & domaine ()
Renvoie une reference sur le Domaine associe au domaine
discretise.
const Domaine & domaine () const
Renvoie une reference sur le Domaine associe au domaine
discretise.
(version const)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Domaine_dis & self_cast (Objet_U &)
static const Domaine_dis & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le domaine discretise sur un flot de sortie.
Imprime le nom du domaine et les zones qu'il contient.
Entree & readOn (Entree &) override
Lit le domaine discretise a partir d'un flot d'entree.
Le format attendu est le suivant:
nom_domaine
bloc de lecture Zones_Dis.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Sous_zones_dis les_sous_zones_dis
Ref_Zones_dis les_zones
Ref_Domaine le_domaine
Private Attributes
Nom i_am_allocator_of_les_zones
Detailed Description
Definition at line 38 of file Domaine_dis.h.
Constructor & Destructor Documentation
Domaine_dis()
Domaine_dis::Domaine_dis ()
Definition at line 26 of file Domaine_dis.cpp.
                         : i_am_allocator_of_les_zones("")
{
}
~Domaine_dis()
Domaine_dis::~Domaine_dis () override
< hack to get pointer
Definition at line 32 of file Domaine_dis.cpp.
{
// [ABN] Niiiiice!!!!  TODO: review this before PolyMAC integration in TRUST!
  if (i_am_allocator_of_les_zones!="" && les_zones.non_nul() && les_sous_zones_dis.non_nul())
    {
      domaines_dis.erase(i_am_allocator_of_les_zones.getChar());
      domaines_dis.erase(Nom(Nom("NO_FACE_") + i_am_allocator_of_les_zones).getChar());
      Objet_U * ptr1 = les_zones.operator->();  //!< hack to get pointer
      Objet_U * ptr2 = les_sous_zones_dis.operator->();
      delete (ptr1);
      delete (ptr2);
    }
}
References domaines_dis, Nom::getChar(), i_am_allocator_of_les_zones, les_sous_zones_dis, les_zones, and O_U_Ptr::non_nul().
Member Function Documentation
associer_domaine()
void Domaine_dis::associer_domaine (const Domaine & un_domaine)
Associe un Domaine (non discretise) a l'objet.
Dimensionne le tableau des zones discretisees associees
au domaine.
Definition at line 219 of file Domaine_dis.cpp.
{
  le_domaine=un_domaine;
}
References le_domaine.
Referenced by Probleme_base::associer_domaine(), Champ_Generique_Extraction::discretiser_domaine(), Champ_Generique_Interpolation::discretiser_domaine(), and Pb_MED::readOn().
cree_instance()
Objet_U * Domaine_dis::cree_instance () static
Definition at line 22 of file Domaine_dis.cpp.
discretiser()
void Domaine_dis::discretiser (const Nom & type_1)
Discretise le domaine.
On type et on discretise chaque zone discretisee du domaine discretise
grace a la discretisation passee en parametre.
< Nom unique
Definition at line 108 of file Domaine_dis.cpp.
{
  Nom type(type_1);
  int face_ok=1;
  type.suffix("NO_FACE_");
  if (type!=type_1) face_ok=0;
  if (!le_domaine.non_nul())
    {
      Cerr << "The domain is not specified. Please check your data file." << finl;
      exit();
    }
  const Domaine& dom=le_domaine.valeur();
  i_am_allocator_of_les_zones = domaine().le_nom()+"_"+type; //!< Nom unique
  if (domaines_dis.find(i_am_allocator_of_les_zones.getChar()) != domaines_dis.end()) //on a deja discretise ce domaine!
    {
      *this = domaines_dis[i_am_allocator_of_les_zones.getChar()].valeur();
      i_am_allocator_of_les_zones = "";
      return;
    }
// Initialisation du tableau renum_som_perio
  const int nb_som = dom.nb_som();
  IntTab renum(nb_som);
  for (int i = 0; i < nb_som; i++)
    renum[i] = i;
  le_domaine.valeur().set_renum_som_perio(renum);
// Cree les Zone_dis, les type et leur associe la zone et le domaine
// correspondants.
  Zones_dis *zptr = new Zones_dis;
  les_zones = *zptr;
  les_zones->dimensionner(dom.nb_zones());
  for(int i=0; i<nombre_de_zones(); i++)
    {
      zone_dis(i).typer(type);
      zone_dis(i).associer_zone(dom.zone(i));
      if (face_ok)
        zone_dis(i).discretiser();
      else
        {
          Zone& zone_geom = domaine().zone(0);
          Zone_VF& zvf = ref_cast(Zone_VF,zone_dis(i).valeur());
          zvf.typer_elem(zone_geom);
// Calcul du volume de la zone discretisee
          zone_geom.calculer_volumes(zvf.volumes(),zvf.inverse_volumes());
        }
      zone_dis(i).associer_domaine_dis(*this);
    }
// Cree les sous_zones_dis, les type, et leur associe
// les zone_dis et les sous_zone correspondantes.
  Sous_zones_dis *szptr = new Sous_zones_dis;
  les_sous_zones_dis = *szptr;
  les_sous_zones_dis->dimensionner(dom.nb_ss_zones());
  for (int i=0; i<dom.nb_ss_zones(); i++)
    {
// Cherche la Zone_dis associee
      const Zone& la_zone=dom.ss_zone(i).zone();
      int z=0;
      while(z<nombre_de_zones() && !zone_dis(z).zone().est_egal_a(la_zone))
        z++;
      if (z==nombre_de_zones())
        {
          Cerr << "In Domaine_dis::discretiser, impossible to find a "
               << "zone_dis corresponding to sous_zone " << i << finl;
          exit();
        }
      const Zone_dis& la_zone_dis=zone_dis(z);
      if (face_ok)
        {
          if (sub_type(Zone_VF,la_zone_dis.valeur()))
            {
              sous_zone_dis(i).typer("Sous_zone_VF");
              sous_zone_dis(i).associer_sous_zone(dom.ss_zone(i));
              sous_zone_dis(i).associer_zone_dis(la_zone_dis.valeur());
              sous_zone_dis(i).discretiser();
            }
          else
            {
              Cerr << "Domaine_dis::discretiser : there is no sub-areas discretized "
                   << "for discretized areas which not deriving from Zone_VF : "
                   << la_zone_dis.valeur().que_suis_je() << finl;
              exit();
            }
        }
    }
// memoization
  domaines_dis[i_am_allocator_of_les_zones.getChar()] = *this;
  domaines_dis[Nom(Nom("NO_FACE_") + i_am_allocator_of_les_zones).getChar()] = *this;
}
References Zone_dis::associer_domaine_dis(), Sous_zone_dis::associer_sous_zone(), Zone_dis::associer_zone(), Sous_zone_dis::associer_zone_dis(), Zone::calculer_volumes(), Cerr, vect_impl::dimensionner(), Sous_zone_dis::discretiser(), Zone_dis::discretiser(), domaine(), domaines_dis, Objet_U::est_egal_a(), Process::exit(), finl, Nom::getChar(), i_am_allocator_of_les_zones, Zone_VF::inverse_volumes(), le_domaine, Domaine::le_nom(), les_sous_zones_dis, les_zones, Domaine::nb_som(), Domaine::nb_ss_zones(), Domaine::nb_zones(), nombre_de_zones(), O_U_Ptr::non_nul(), Objet_U::que_suis_je(), ref_cast, Domaine::set_renum_som_perio(), sous_zone_dis(), Domaine::ss_zone(), sub_type, Nom::suffix(), Deriv_::typer(), Zone_VF::typer_elem(), Deriv_Zone_dis_base::valeur(), Ref_Domaine::valeur(), valeur(), Zone_VF::volumes(), Sous_Zone::zone(), Domaine::zone(), and zone_dis().
Referenced by Discretisation_base::discretiser(), Champ_Generique_Extraction::discretiser_domaine(), Champ_Generique_Interpolation::discretiser_domaine(), and Pb_MED::readOn().
domaine() [1/2]
Domaine & Domaine_dis::domaine () inline
Renvoie une reference sur le Domaine associe au domaine
discretise.
Returns
Domaine&
Signification: le Domaine associe au domaine discretise
Contraintes:
Definition at line 149 of file Domaine_dis.h.
{
  return le_domaine.valeur();
}
References le_domaine, and Ref_Domaine::valeur().
Referenced by discretiser(), Probleme_base::domaine(), Champ_Generique_base::get_ref_domain(), Echange_contact_Correlation_VEF::init(), printOn(), Milieu_base::update_rho_cp(), and Echange_contact_VDF::verifier_correspondance().
domaine() [2/2]
const Domaine & Domaine_dis::domaine () const inline
Renvoie une reference sur le Domaine associe au domaine
discretise.
(version const)
Returns
Domaine&
Signification: le Domaine associe au domaine discretise
Contraintes: reference constante
Definition at line 170 of file Domaine_dis.h.
{
  return le_domaine.valeur();
}
References le_domaine, and Ref_Domaine::valeur().
duplique()
int Domaine_dis::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file Domaine_dis.cpp.
get_info()
const Type_info * Domaine_dis::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 22 of file Domaine_dis.cpp.
info()
const Type_info * Domaine_dis::info () static
Definition at line 22 of file Domaine_dis.cpp.
nombre_de_sous_zones_dis()
int Domaine_dis::nombre_de_sous_zones_dis () const inline
Definition at line 49 of file Domaine_dis.h.
  {
    return les_sous_zones_dis->size();
  }
References les_sous_zones_dis, and vect_impl::size().
Referenced by Op_Conv_EF_VEF_P1NC_Stab::completer(), and Perte_Charge_VEF::completer().
nombre_de_zones()
int Domaine_dis::nombre_de_zones () const inline
Renvoie le nombre de zones contenues dans le domaine.
Returns
int
Signification: le nombre de zones contenues dans le domaine
Contraintes:
Definition at line 90 of file Domaine_dis.h.
{
  return les_zones.valeur().size();
}
References les_zones, vect_impl::size(), and Ref_Zones_dis::valeur().
Referenced by discretiser(), Champ_Generique_Interpolation::get_ref_zone_dis_base(), and Debog_Pb::readOn().
printOn()
Sortie & Domaine_dis::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime le domaine discretise sur un flot de sortie.
Imprime le nom du domaine et les zones qu'il contient.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 62 of file Domaine_dis.cpp.
{
  return os << domaine().le_nom() << finl << les_zones.valeur() << les_sous_zones_dis.valeur();
}
References domaine(), finl, Domaine::le_nom(), les_sous_zones_dis, les_zones, Ref_Sous_zones_dis::valeur(), and Ref_Zones_dis::valeur().
readOn()
Entree & Domaine_dis::readOn (Entree & is) override protected virtual
Lit le domaine discretise a partir d'un flot d'entree.
Le format attendu est le suivant:
nom_domaine
bloc de lecture Zones_Dis.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 85 of file Domaine_dis.cpp.
{
  Nom nom;
  return is >> nom >> les_zones.valeur() >> les_sous_zones_dis.valeur();
}
References les_sous_zones_dis, les_zones, Ref_Sous_zones_dis::valeur(), and Ref_Zones_dis::valeur().
self_cast() [1/2]
const Domaine_dis & Domaine_dis::self_cast (const Objet_U & r) static
Definition at line 22 of file Domaine_dis.cpp.
self_cast() [2/2]
Domaine_dis & Domaine_dis::self_cast (Objet_U & r) static
Definition at line 22 of file Domaine_dis.cpp.
sous_zone_dis() [1/2]
Sous_zone_dis & Domaine_dis::sous_zone_dis (int i) inline
Definition at line 57 of file Domaine_dis.h.
  {
    return les_sous_zones_dis.valeur()[i];
  }
References les_sous_zones_dis, and Ref_Sous_zones_dis::valeur().
sous_zone_dis() [2/2]
const Sous_zone_dis & Domaine_dis::sous_zone_dis (int i) const inline
Definition at line 53 of file Domaine_dis.h.
  {
    return les_sous_zones_dis.valeur()[i];
  }
References les_sous_zones_dis, and Ref_Sous_zones_dis::valeur().
Referenced by Op_Conv_EF_VEF_P1NC_Stab::completer(), Perte_Charge_VEF::completer(), and discretiser().
taille_memoire()
unsigned Domaine_dis::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file Domaine_dis.cpp.
zone_dis() [1/2]
Zone_dis & Domaine_dis::zone_dis (int i) inline
Renvoie une reference sur la i-eme zone discretisee du domaine.
Returns
Zone_dis&
Signification: la i-eme zone discretisee du domaine
Contraintes:
Definition at line 129 of file Domaine_dis.h.
{
  return les_zones.valeur()[i];
}
References les_zones, and Ref_Zones_dis::valeur().
zone_dis() [2/2]
const Zone_dis & Domaine_dis::zone_dis (int i) const inline
Renvoie une reference sur la i-eme zone discretisee du domaine.
(version const)
Returns
Zone_dis&
Signification: la i-eme zone discretisee du domaine
Contraintes: reference constante
Definition at line 110 of file Domaine_dis.h.
{
  return les_zones.valeur()[i];
}
References les_zones, and Ref_Zones_dis::valeur().
Referenced by Terme_Source_Rappel_T_VEF_Face::completer(), Op_Ecart_type::completer(), Op_Moyenne::completer(), Loi_Fermeture_Test::discretiser(), discretiser(), VEFPreP1B::discretiser(), Champ_Generique_base::get_ref_zone_dis_base(), Champ_Generique_Extraction::get_ref_zone_dis_base(), Champ_Generique_Interpolation::get_ref_zone_dis_base(), Postraitement_lata::lire_champs(), Postraitement_lata::postraiter(), Postraitement_lata::postraiter_liste_champs(), Debog_Pb::read_geometry_data(), Champ_input_P0::readOn(), Champ_Fonc_reprise::readOn(), Diametre_bulles_champ::readOn(), Diametre_bulles_constant::readOn(), Champ_Don_Face_lu::readOn(), and Debog_Pb::write_geometry_data().
Member Data Documentation
i_am_allocator_of_les_zones
Nom Domaine_dis::i_am_allocator_of_les_zones mutable private
Definition at line 72 of file Domaine_dis.h.
Referenced by discretiser(), and ~Domaine_dis().
info_obj
const Type_info Domaine_dis::info_obj static
Definition at line 41 of file Domaine_dis.h.
le_domaine
Ref_Domaine Domaine_dis::le_domaine protected
Definition at line 69 of file Domaine_dis.h.
Referenced by associer_domaine(), discretiser(), and domaine().
les_sous_zones_dis
Ref_Sous_zones_dis Domaine_dis::les_sous_zones_dis protected
Definition at line 67 of file Domaine_dis.h.
Referenced by discretiser(), nombre_de_sous_zones_dis(), printOn(), readOn(), sous_zone_dis(), and ~Domaine_dis().
les_zones
Ref_Zones_dis Domaine_dis::les_zones protected
Definition at line 68 of file Domaine_dis.h.
Referenced by discretiser(), nombre_de_zones(), printOn(), readOn(), zone_dis(), and ~Domaine_dis().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Domaine_dis.h
src/Kernel/Framework/Domaine_dis.cpp