TRUST: Refine_Mesh Class Reference
Refine_Mesh Class Reference
#include <Refine_Mesh.h>
Public Member Functions
Refine_Mesh ()
~Refine_Mesh ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &is) override
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Refine_Mesh & self_cast (Objet_U &)
static const Refine_Mesh & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void apply (void)
void check_dimension (void) const
void check_nb_zones (void) const
void check_cell_type (void) const
void apply_2D (void)
void apply_3D (void)
void build_edges_2D (IntTab &nodes_of_edges, IntTab &edges_of_cells) const
void build_edges_3D (IntTab &nodes_of_edges, IntTab &edges_of_cells) const
void build_edges (IntTab &nodes_of_edges, IntTab &edges_of_cells, int nb_edges_per_cell, int nb_nodes_per_edge, const IntTab &local_nodes_of_edges) const
void build_new_nodes (DoubleTab &new_nodes, const IntTab &nodes_of_edges) const
void build_new_cells_2D (IntTab &new_cells, const IntTab &edges_of_cells) const
void build_new_cells_3D (IntTab &new_cells, const IntTab &edges_of_cells) const
void build_new_sub_zones_descriptions (Noms &new_sub_zones_descriptions) const
void build_incidence_from_node_to_edges (int nb_nodes, const IntTab &nodes_of_edges, Static_Int_Lists &incidence) const
void build_new_boundary_faces_2D (IntTabs &new_nodes_of_boundary_faces, IntTabs &new_cells_of_boundary_faces, const Static_Int_Lists &incidence_from_node_to_edges) const
void build_new_boundary_faces_3D (IntTabs &new_nodes_of_boundary_faces, IntTabs &new_cells_of_boundary_faces, const Static_Int_Lists &incidence_from_node_to_edges) const
void build_new_connector_faces_2D (IntTabs &new_nodes_of_connector_faces, IntTabs &new_cells_of_connector_faces, const Static_Int_Lists &incidence_from_node_to_edges) const
void build_new_connector_faces_3D (IntTabs &new_nodes_of_connector_faces, IntTabs &new_cells_of_connector_faces, const Static_Int_Lists &incidence_from_node_to_edges) const
void build_new_internal_frontier_faces_2D (IntTabs &new_nodes_of_internal_frontier_faces, IntTabs &new_cells_of_internal_frontier_faces, const Static_Int_Lists &incidence_from_node_to_edges) const
void build_new_internal_frontier_faces_3D (IntTabs &new_nodes_of_internal_frontier_faces, IntTabs &new_cells_of_internal_frontier_faces, const Static_Int_Lists &incidence_from_node_to_edges) const
void build_new_frontier_faces_2D (IntTab &new_nodes_of_frontier_faces, IntTab &new_cells_of_frontier_faces, const Static_Int_Lists &incidence_from_node_to_edges, const Faces &old_frontier_faces) const
void build_new_frontier_faces_3D (IntTab &new_nodes_of_frontier_faces, IntTab &new_cells_of_frontier_faces, const Static_Int_Lists &incidence_from_node_to_edges, const Faces &old_frontier_faces) const
int find_edge (const Static_Int_Lists &incidence_from_node_to_edges, int node0, int node1) const
void update_domain (const Nom &cell_type, const Type_Face &face_type, const DoubleTab &new_nodes, const IntTab &new_cells, const Noms &new_sub_zones_descriptions, const IntTabs &new_nodes_of_boundary_faces, const IntTabs &new_cells_of_boundary_faces, const IntTabs &new_nodes_of_connector_faces, const IntTabs &new_cells_of_connector_faces, const IntTabs &new_nodes_of_internal_frontier_faces, const IntTabs &new_cells_of_internal_frontier_faces)
void update_nodes (const DoubleTab &new_nodes)
void update_cells (const IntTab &new_cells)
void update_octree (const Nom &cell_type)
void update_sub_zones (const Noms &new_sub_zones_descriptions)
void update_boundary_faces (const Type_Face &face_type, const IntTabs &new_nodes_of_boundary_faces, const IntTabs &new_cells_of_boundary_faces)
void update_connector_faces (const Type_Face &face_type, const IntTabs &new_nodes_of_connector_faces, const IntTabs &new_cells_of_connector_faces)
void update_internal_frontier_faces (const Type_Face &face_type, const IntTabs &new_nodes_of_internal_frontier_faces, const IntTabs &new_cells_of_internal_frontier_faces)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Definition at line 34 of file Refine_Mesh.h.
Constructor & Destructor Documentation
Refine_Mesh()
Refine_Mesh::Refine_Mesh ()
Definition at line 25 of file Refine_Mesh.cpp.
~Refine_Mesh()
Refine_Mesh::~Refine_Mesh ()
Definition at line 25 of file Refine_Mesh.cpp.
Member Function Documentation
apply()
void Refine_Mesh::apply (void) protected
Definition at line 47 of file Refine_Mesh.cpp.
{
  Cerr << "Refining domain " << domaine().le_nom() << finl;
  check_dimension();
  check_nb_zones();
  check_cell_type();
  if ( Objet_U::dimension == 2 )
    {
      apply_2D();
    }
  else
    {
      apply_3D();
    }
  Cerr << "Refinement... OK" << finl;
}
References apply_2D(), apply_3D(), Cerr, check_cell_type(), check_dimension(), check_nb_zones(), Objet_U::dimension, Interprete_geometrique_base::domaine(), finl, and Domaine::le_nom().
Referenced by interpreter_().
apply_2D()
void Refine_Mesh::apply_2D (void) protected
Definition at line 103 of file Refine_Mesh.cpp.
{
  Domaine& domain = domaine();
  Scatter::uninit_sequential_domain(domain);
  assert( domain.zone(0).type_elem().valeur().que_suis_je() == Motcle("Triangle") );
  IntTab nodes_of_edges;
  IntTab edges_of_cells;
  build_edges_2D(nodes_of_edges, edges_of_cells);
  DoubleTab new_nodes;
  build_new_nodes(new_nodes, nodes_of_edges);
  IntTab new_cells;
  build_new_cells_2D(new_cells, edges_of_cells);
  Noms new_sub_zones_descriptions;
  build_new_sub_zones_descriptions(new_sub_zones_descriptions);
  Static_Int_Lists incidence_from_node_to_edges;
  build_incidence_from_node_to_edges(new_nodes.dimension(0),nodes_of_edges,incidence_from_node_to_edges);
  IntTabs new_nodes_of_boundary_faces;
  IntTabs new_cells_of_boundary_faces;
  build_new_boundary_faces_2D(new_nodes_of_boundary_faces, new_cells_of_boundary_faces, incidence_from_node_to_edges);
  IntTabs new_nodes_of_connector_faces;
  IntTabs new_cells_of_connector_faces;
  build_new_connector_faces_2D(new_nodes_of_connector_faces, new_cells_of_connector_faces, incidence_from_node_to_edges);
  IntTabs new_nodes_of_internal_frontier_faces;
  IntTabs new_cells_of_internal_frontier_faces;
  build_new_internal_frontier_faces_2D(new_nodes_of_internal_frontier_faces, new_cells_of_internal_frontier_faces, incidence_from_node_to_edges);
  update_domain(Nom("Triangle"),
                Faces::segment_2D,
                new_nodes,
                new_cells,
                new_sub_zones_descriptions,
                new_nodes_of_boundary_faces,
                new_cells_of_boundary_faces,
                new_nodes_of_connector_faces,
                new_cells_of_connector_faces,
                new_nodes_of_internal_frontier_faces,
                new_cells_of_internal_frontier_faces);
  Scatter::init_sequential_domain(domain);
}
References build_edges_2D(), build_incidence_from_node_to_edges(), build_new_boundary_faces_2D(), build_new_cells_2D(), build_new_connector_faces_2D(), build_new_internal_frontier_faces_2D(), build_new_nodes(), build_new_sub_zones_descriptions(), TRUSTTab< _TYPE_ >::dimension(), Interprete_geometrique_base::domaine(), Scatter::init_sequential_domain(), Objet_U::que_suis_je(), Faces::segment_2D, Zone::type_elem(), Scatter::uninit_sequential_domain(), update_domain(), Deriv_Elem_geom_base::valeur(), and Domaine::zone().
Referenced by apply().
apply_3D()
void Refine_Mesh::apply_3D (void) protected
Definition at line 153 of file Refine_Mesh.cpp.
{
  Domaine& domain = domaine();
  Scatter::uninit_sequential_domain(domain);
  assert( domain.zone(0).type_elem().valeur().que_suis_je() == Motcle("Tetraedre") );
  IntTab nodes_of_edges;
  IntTab edges_of_cells;
  build_edges_3D(nodes_of_edges, edges_of_cells);
  DoubleTab new_nodes;
  build_new_nodes(new_nodes, nodes_of_edges);
  IntTab new_cells;
  build_new_cells_3D(new_cells, edges_of_cells);
  Noms new_sub_zones_descriptions;
  build_new_sub_zones_descriptions(new_sub_zones_descriptions);
  Static_Int_Lists incidence_from_node_to_edges;
  build_incidence_from_node_to_edges(new_nodes.dimension(0),nodes_of_edges,incidence_from_node_to_edges);
  IntTabs new_nodes_of_boundary_faces;
  IntTabs new_cells_of_boundary_faces;
  build_new_boundary_faces_3D(new_nodes_of_boundary_faces, new_cells_of_boundary_faces, incidence_from_node_to_edges);
  IntTabs new_nodes_of_connector_faces;
  IntTabs new_cells_of_connector_faces;
  build_new_connector_faces_3D(new_nodes_of_connector_faces, new_cells_of_connector_faces, incidence_from_node_to_edges);
  IntTabs new_nodes_of_internal_frontier_faces;
  IntTabs new_cells_of_internal_frontier_faces;
  build_new_internal_frontier_faces_3D(new_nodes_of_internal_frontier_faces, new_cells_of_internal_frontier_faces, incidence_from_node_to_edges);
  update_domain(Nom("Tetraedre"),
                Faces::triangle_3D,
                new_nodes,
                new_cells,
                new_sub_zones_descriptions,
                new_nodes_of_boundary_faces,
                new_cells_of_boundary_faces,
                new_nodes_of_connector_faces,
                new_cells_of_connector_faces,
                new_nodes_of_internal_frontier_faces,
                new_cells_of_internal_frontier_faces);
  Scatter::init_sequential_domain(domain);
}
References build_edges_3D(), build_incidence_from_node_to_edges(), build_new_boundary_faces_3D(), build_new_cells_3D(), build_new_connector_faces_3D(), build_new_internal_frontier_faces_3D(), build_new_nodes(), build_new_sub_zones_descriptions(), TRUSTTab< _TYPE_ >::dimension(), Interprete_geometrique_base::domaine(), Scatter::init_sequential_domain(), Objet_U::que_suis_je(), Faces::triangle_3D, Zone::type_elem(), Scatter::uninit_sequential_domain(), update_domain(), Deriv_Elem_geom_base::valeur(), and Domaine::zone().
Referenced by apply().
build_edges()
void Refine_Mesh::build_edges (IntTab & nodes_of_edges, IntTab & edges_of_cells, int nb_edges_per_cell, int nb_nodes_per_edge, const IntTab & local_nodes_of_edges) const protected
Definition at line 241 of file Refine_Mesh.cpp.
{
  const IntTab& cells = domaine().zone(0).les_elems();
  const int nb_cells = cells.dimension(0);
  int size = nb_cells * nb_edges_per_cell;
  IntTab nodes_of_edges_tmp(size,nb_nodes_per_edge);
  edges_of_cells.resize(nb_cells, nb_edges_per_cell);
  ArrOfInt global_nodes_of_edge(nb_nodes_per_edge);
  for (int c=0; c<nb_cells; ++c)
    {
      for (int e=0; e<nb_edges_per_cell; ++e)
        {
          const int idx = c * nb_edges_per_cell + e;
          for (int n=0; n<nb_nodes_per_edge; ++n)
            {
              global_nodes_of_edge[n] = cells(c,local_nodes_of_edges(e,n));
            }
          nodes_of_edges_tmp(idx,0) = (global_nodes_of_edge[0]<global_nodes_of_edge[1]) ? global_nodes_of_edge[0] : global_nodes_of_edge[1];
          nodes_of_edges_tmp(idx,1) = (global_nodes_of_edge[0]<global_nodes_of_edge[1]) ? global_nodes_of_edge[1] : global_nodes_of_edge[0];
          edges_of_cells(c,e) = idx;
        }
    }
  ArrOfInt renum;
  ArrOfInt renum_inverse;
  calculer_renum_sans_doublons(nodes_of_edges_tmp,renum,renum_inverse);
  const int nb_edges = renum_inverse.size_array();
  nodes_of_edges.resize(nb_edges,nb_nodes_per_edge);
  for (int e=0; e<nb_edges; ++e)
    {
      for (int n=0; n<nb_nodes_per_edge; ++n)
        {
          nodes_of_edges(e,n) = nodes_of_edges_tmp(renum_inverse[e],n);
        }
    }
  for (int c=0; c<nb_cells; ++c)
    {
      for (int e=0; e<nb_edges_per_cell; ++e)
        {
          edges_of_cells(c,e) = renum[edges_of_cells(c,e)];
        }
    }
}
References calculer_renum_sans_doublons(), TRUSTTab< _TYPE_ >::dimension(), Interprete_geometrique_base::domaine(), Zone::les_elems(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::size_array(), and Domaine::zone().
Referenced by build_edges_2D(), and build_edges_3D().
build_edges_2D()
void Refine_Mesh::build_edges_2D (IntTab & nodes_of_edges, IntTab & edges_of_cells) const protected
Definition at line 203 of file Refine_Mesh.cpp.
{
  const int nb_edges_per_cell = 3;
  const int nb_nodes_per_edge = 2;
  IntTab local_nodes_of_edges(nb_edges_per_cell,nb_nodes_per_edge);
  local_nodes_of_edges(0,0) = 0;
  local_nodes_of_edges(0,1) = 1;
  local_nodes_of_edges(1,0) = 0;
  local_nodes_of_edges(1,1) = 2;
  local_nodes_of_edges(2,0) = 1;
  local_nodes_of_edges(2,1) = 2;
  build_edges(nodes_of_edges, edges_of_cells, nb_edges_per_cell, nb_nodes_per_edge, local_nodes_of_edges);
}
References build_edges().
Referenced by apply_2D().
build_edges_3D()
void Refine_Mesh::build_edges_3D (IntTab & nodes_of_edges, IntTab & edges_of_cells) const protected
Definition at line 219 of file Refine_Mesh.cpp.
{
  const int nb_edges_per_cell = 6;
  const int nb_nodes_per_edge = 2;
  IntTab local_nodes_of_edges(nb_edges_per_cell,nb_nodes_per_edge);
  local_nodes_of_edges(0,0) = 0;
  local_nodes_of_edges(0,1) = 1;
  local_nodes_of_edges(1,0) = 0;
  local_nodes_of_edges(1,1) = 2;
  local_nodes_of_edges(2,0) = 0;
  local_nodes_of_edges(2,1) = 3;
  local_nodes_of_edges(3,0) = 1;
  local_nodes_of_edges(3,1) = 2;
  local_nodes_of_edges(4,0) = 1;
  local_nodes_of_edges(4,1) = 3;
  local_nodes_of_edges(5,0) = 2;
  local_nodes_of_edges(5,1) = 3;
  build_edges(nodes_of_edges, edges_of_cells, nb_edges_per_cell, nb_nodes_per_edge, local_nodes_of_edges);
}
References build_edges().
Referenced by apply_3D().
build_incidence_from_node_to_edges()
void Refine_Mesh::build_incidence_from_node_to_edges (int nb_nodes, const IntTab & nodes_of_edges, Static_Int_Lists & incidence) const protected
Definition at line 443 of file Refine_Mesh.cpp.
{
  const int nb_edges          = nodes_of_edges.dimension(0);
  const int nb_nodes_per_edge = nodes_of_edges.dimension(1);
  ArrOfInt nb_incident_edges(nb_nodes);
  for (int edge=0; edge<nb_edges; ++edge)
    {
      for (int n=0; n<nb_nodes_per_edge; ++n)
        {
          const int node = nodes_of_edges(edge,n);
          ++nb_incident_edges[node];
        }
    }
  incidence.set_list_sizes(nb_incident_edges);
  nb_incident_edges = 0;
  for (int edge=0; edge<nb_edges; ++edge)
    {
      for (int n=0; n<nb_nodes_per_edge; ++n)
        {
          const int node  = nodes_of_edges(edge,n);
          const int index = nb_incident_edges[node];
          incidence.set_value(node, index, edge);
          ++nb_incident_edges[node];
        }
    }
  incidence.trier_liste(-1);
}
References TRUSTTab< _TYPE_ >::dimension(), Static_Int_Lists::set_list_sizes(), Static_Int_Lists::set_value(), and Static_Int_Lists::trier_liste().
Referenced by apply_2D(), and apply_3D().
build_new_boundary_faces_2D()
void Refine_Mesh::build_new_boundary_faces_2D (IntTabs & new_nodes_of_boundary_faces, IntTabs & new_cells_of_boundary_faces, const Static_Int_Lists & incidence_from_node_to_edges) const protected
Definition at line 478 of file Refine_Mesh.cpp.
{
  const int nb_boundaries = domaine().zone(0).nb_bords();
  new_nodes_of_boundary_faces.dimensionner(nb_boundaries);
  new_cells_of_boundary_faces.dimensionner(nb_boundaries);
  int boundary = 0;
  CONST_LIST_CURSEUR(Bord) cursor(domaine().zone(0).faces_bord());
  while (cursor)
    {
      IntTab& nodes = new_nodes_of_boundary_faces[boundary];
      IntTab& cells = new_cells_of_boundary_faces[boundary];
      build_new_frontier_faces_2D(nodes,cells,incidence_from_node_to_edges,cursor.valeur().faces());
      ++cursor;
      ++boundary;
    }
}
References build_new_frontier_faces_2D(), CONST_LIST_CURSEUR, vect_impl::dimensionner(), Interprete_geometrique_base::domaine(), Zone::nb_bords(), and Domaine::zone().
Referenced by apply_2D().
build_new_boundary_faces_3D()
void Refine_Mesh::build_new_boundary_faces_3D (IntTabs & new_nodes_of_boundary_faces, IntTabs & new_cells_of_boundary_faces, const Static_Int_Lists & incidence_from_node_to_edges) const protected
Definition at line 498 of file Refine_Mesh.cpp.
{
  const int nb_boundaries = domaine().zone(0).nb_bords();
  new_nodes_of_boundary_faces.dimensionner(nb_boundaries);
  new_cells_of_boundary_faces.dimensionner(nb_boundaries);
  int boundary = 0;
  CONST_LIST_CURSEUR(Bord) cursor(domaine().zone(0).faces_bord());
  while (cursor)
    {
      IntTab& nodes = new_nodes_of_boundary_faces[boundary];
      IntTab& cells = new_cells_of_boundary_faces[boundary];
      build_new_frontier_faces_3D(nodes,cells,incidence_from_node_to_edges,cursor.valeur().faces());
      ++cursor;
      ++boundary;
    }
}
References build_new_frontier_faces_3D(), CONST_LIST_CURSEUR, vect_impl::dimensionner(), Interprete_geometrique_base::domaine(), Zone::nb_bords(), and Domaine::zone().
Referenced by apply_3D().
build_new_cells_2D()
void Refine_Mesh::build_new_cells_2D (IntTab & new_cells, const IntTab & edges_of_cells) const protected
Definition at line 318 of file Refine_Mesh.cpp.
{
  const DoubleTab& nodes = domaine().les_sommets();
  const IntTab&    cells = domaine().zone(0).les_elems();
  const int nb_cells = cells.dimension(0);
  const int nb_nodes = nodes.dimension(0);
  new_cells.resize(4*nb_cells,3);
  int n0, n1, n2, n01, n02, n12;
  for (int c=0; c<nb_cells; ++c)
    {
      n0  = cells(c,0);
      n1  = cells(c,1);
      n2  = cells(c,2);
      n01 = nb_nodes + edges_of_cells(c,0);
      n02 = nb_nodes + edges_of_cells(c,1);
      n12 = nb_nodes + edges_of_cells(c,2);
      new_cells(4*c+0,0) = n0;
      new_cells(4*c+0,1) = n01;
      new_cells(4*c+0,2) = n02;
      new_cells(4*c+1,0) = n01;
      new_cells(4*c+1,1) = n1;
      new_cells(4*c+1,2) = n12;
      new_cells(4*c+2,0) = n02;
      new_cells(4*c+2,1) = n12;
      new_cells(4*c+2,2) = n2;
      new_cells(4*c+3,0) = n12;
      new_cells(4*c+3,1) = n02;
      new_cells(4*c+3,2) = n01;
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Interprete_geometrique_base::domaine(), Zone::les_elems(), Domaine::les_sommets(), TRUSTTab< _TYPE_ >::resize(), and Domaine::zone().
Referenced by apply_2D().
build_new_cells_3D()
void Refine_Mesh::build_new_cells_3D (IntTab & new_cells, const IntTab & edges_of_cells) const protected
Definition at line 353 of file Refine_Mesh.cpp.
{
  const DoubleTab& nodes = domaine().les_sommets();
  const IntTab&    cells = domaine().zone(0).les_elems();
  const int nb_cells = cells.dimension(0);
  const int nb_nodes = nodes.dimension(0);
  new_cells.resize(8*nb_cells,4);
  int n0, n1, n2, n3, n01, n02, n03, n12, n13, n23;
  for (int c=0; c<nb_cells; ++c)
    {
      n0  = cells(c,0);
      n1  = cells(c,1);
      n2  = cells(c,2);
      n3  = cells(c,3);
      n01 = nb_nodes + edges_of_cells(c,0);
      n02 = nb_nodes + edges_of_cells(c,1);
      n03 = nb_nodes + edges_of_cells(c,2);
      n12 = nb_nodes + edges_of_cells(c,3);
      n13 = nb_nodes + edges_of_cells(c,4);
      n23 = nb_nodes + edges_of_cells(c,5);
      new_cells(8*c+0,0) = n0;
      new_cells(8*c+0,1) = n01;
      new_cells(8*c+0,2) = n02;
      new_cells(8*c+0,3) = n03;
      new_cells(8*c+1,0) = n01;
      new_cells(8*c+1,1) = n1;
      new_cells(8*c+1,2) = n12;
      new_cells(8*c+1,3) = n13;
      new_cells(8*c+2,0) = n02;
      new_cells(8*c+2,1) = n12;
      new_cells(8*c+2,2) = n2;
      new_cells(8*c+2,3) = n23;
      new_cells(8*c+3,0) = n03;
      new_cells(8*c+3,1) = n13;
      new_cells(8*c+3,2) = n23;
      new_cells(8*c+3,3) = n3;
      new_cells(8*c+4,0) = n02;
      new_cells(8*c+4,1) = n23;
      new_cells(8*c+4,2) = n13;
      new_cells(8*c+4,3) = n12;
      new_cells(8*c+5,0) = n23;
      new_cells(8*c+5,1) = n13;
      new_cells(8*c+5,2) = n03;
      new_cells(8*c+5,3) = n02;
      new_cells(8*c+6,0) = n13;
      new_cells(8*c+6,1) = n03;
      new_cells(8*c+6,2) = n02;
      new_cells(8*c+6,3) = n01;
      new_cells(8*c+7,0) = n12;
      new_cells(8*c+7,1) = n02;
      new_cells(8*c+7,2) = n01;
      new_cells(8*c+7,3) = n13;
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Interprete_geometrique_base::domaine(), Zone::les_elems(), Domaine::les_sommets(), TRUSTTab< _TYPE_ >::resize(), and Domaine::zone().
Referenced by apply_3D().
build_new_connector_faces_2D()
void Refine_Mesh::build_new_connector_faces_2D (IntTabs & new_nodes_of_connector_faces, IntTabs & new_cells_of_connector_faces, const Static_Int_Lists & incidence_from_node_to_edges) const protected
Definition at line 518 of file Refine_Mesh.cpp.
{
  const int nb_connectors = domaine().zone(0).nb_raccords();
  new_nodes_of_connector_faces.dimensionner(nb_connectors);
  new_cells_of_connector_faces.dimensionner(nb_connectors);
  int connector = 0;
  CONST_LIST_CURSEUR(Raccord) cursor(domaine().zone(0).faces_raccord());
  while (cursor)
    {
      IntTab& nodes = new_nodes_of_connector_faces[connector];
      IntTab& cells = new_cells_of_connector_faces[connector];
      build_new_frontier_faces_2D(nodes,cells,incidence_from_node_to_edges,cursor.valeur().valeur().faces());
      ++cursor;
      ++connector;
    }
}
References build_new_frontier_faces_2D(), CONST_LIST_CURSEUR, vect_impl::dimensionner(), Interprete_geometrique_base::domaine(), Zone::nb_raccords(), and Domaine::zone().
Referenced by apply_2D().
build_new_connector_faces_3D()
void Refine_Mesh::build_new_connector_faces_3D (IntTabs & new_nodes_of_connector_faces, IntTabs & new_cells_of_connector_faces, const Static_Int_Lists & incidence_from_node_to_edges) const protected
Definition at line 538 of file Refine_Mesh.cpp.
{
  const int nb_connectors = domaine().zone(0).nb_raccords();
  new_nodes_of_connector_faces.dimensionner(nb_connectors);
  new_cells_of_connector_faces.dimensionner(nb_connectors);
  int connector = 0;
  CONST_LIST_CURSEUR(Raccord) cursor(domaine().zone(0).faces_raccord());
  while (cursor)
    {
      IntTab& nodes = new_nodes_of_connector_faces[connector];
      IntTab& cells = new_cells_of_connector_faces[connector];
      build_new_frontier_faces_3D(nodes,cells,incidence_from_node_to_edges,cursor.valeur().valeur().faces());
      ++cursor;
      ++connector;
    }
}
References build_new_frontier_faces_3D(), CONST_LIST_CURSEUR, vect_impl::dimensionner(), Interprete_geometrique_base::domaine(), Zone::nb_raccords(), and Domaine::zone().
Referenced by apply_3D().
build_new_frontier_faces_2D()
void Refine_Mesh::build_new_frontier_faces_2D (IntTab & new_nodes_of_frontier_faces, IntTab & new_cells_of_frontier_faces, const Static_Int_Lists & incidence_from_node_to_edges, const Faces & old_frontier_faces) const protected
Definition at line 600 of file Refine_Mesh.cpp.
{
  const int nb_nodes = domaine().les_sommets().dimension(0);
  const int old_nb_faces = old_frontier_faces.nb_faces();
  const int new_nb_faces = old_nb_faces * 2;
  const IntTab& old_nodes_of_frontier_faces = old_frontier_faces.les_sommets();
  new_nodes_of_frontier_faces.resize(new_nb_faces,2);
  for (int f=0; f<old_nb_faces; ++f)
    {
      const int node0 = old_nodes_of_frontier_faces(f,0);
      const int node1 = old_nodes_of_frontier_faces(f,1);
      const int edge  = find_edge(incidence_from_node_to_edges,node0,node1);
      new_nodes_of_frontier_faces(2*f+0,0) = node0;
      new_nodes_of_frontier_faces(2*f+0,1) = nb_nodes + edge;
      new_nodes_of_frontier_faces(2*f+1,0) = nb_nodes + edge;
      new_nodes_of_frontier_faces(2*f+1,1) = node1;
    }
  new_cells_of_frontier_faces.resize(new_nb_faces,2);
  new_cells_of_frontier_faces = -1;
}
References TRUSTTab< _TYPE_ >::dimension(), Interprete_geometrique_base::domaine(), find_edge(), Domaine::les_sommets(), Faces::les_sommets(), Faces::nb_faces(), and TRUSTTab< _TYPE_ >::resize().
Referenced by build_new_boundary_faces_2D(), build_new_connector_faces_2D(), and build_new_internal_frontier_faces_2D().
build_new_frontier_faces_3D()
void Refine_Mesh::build_new_frontier_faces_3D (IntTab & new_nodes_of_frontier_faces, IntTab & new_cells_of_frontier_faces, const Static_Int_Lists & incidence_from_node_to_edges, const Faces & old_frontier_faces) const protected
Definition at line 630 of file Refine_Mesh.cpp.
{
  const int nb_nodes = domaine().les_sommets().dimension(0);
  const int old_nb_faces = old_frontier_faces.nb_faces();
  const int new_nb_faces = old_nb_faces * 4;
  const IntTab old_nodes_of_frontier_faces = old_frontier_faces.les_sommets();
  new_nodes_of_frontier_faces.resize(new_nb_faces,3);
  for (int f=0; f<old_nb_faces; ++f)
    {
      const int node0 = old_nodes_of_frontier_faces(f,0);
      const int node1 = old_nodes_of_frontier_faces(f,1);
      const int node2 = old_nodes_of_frontier_faces(f,2);
      const int edge0  = find_edge(incidence_from_node_to_edges,node1,node2);
      const int edge1  = find_edge(incidence_from_node_to_edges,node2,node0);
      const int edge2  = find_edge(incidence_from_node_to_edges,node0,node1);
      new_nodes_of_frontier_faces(4*f+0,0) = node0;
      new_nodes_of_frontier_faces(4*f+0,1) = nb_nodes + edge2;
      new_nodes_of_frontier_faces(4*f+0,2) = nb_nodes + edge1;
      new_nodes_of_frontier_faces(4*f+1,0) = nb_nodes + edge2;
      new_nodes_of_frontier_faces(4*f+1,1) = node1;
      new_nodes_of_frontier_faces(4*f+1,2) = nb_nodes + edge0;
      new_nodes_of_frontier_faces(4*f+2,0) = nb_nodes + edge1;
      new_nodes_of_frontier_faces(4*f+2,1) = nb_nodes + edge0;
      new_nodes_of_frontier_faces(4*f+2,2) = node2;
      new_nodes_of_frontier_faces(4*f+3,0) = nb_nodes +edge0;
      new_nodes_of_frontier_faces(4*f+3,1) = nb_nodes +edge1;
      new_nodes_of_frontier_faces(4*f+3,2) = nb_nodes +edge2;
    }
  new_cells_of_frontier_faces.resize(new_nb_faces,2);
  new_cells_of_frontier_faces = -1;
}
References TRUSTTab< _TYPE_ >::dimension(), Interprete_geometrique_base::domaine(), find_edge(), Domaine::les_sommets(), Faces::les_sommets(), Faces::nb_faces(), and TRUSTTab< _TYPE_ >::resize().
Referenced by build_new_boundary_faces_3D(), build_new_connector_faces_3D(), and build_new_internal_frontier_faces_3D().
build_new_internal_frontier_faces_2D()
void Refine_Mesh::build_new_internal_frontier_faces_2D (IntTabs & new_nodes_of_internal_frontier_faces, IntTabs & new_cells_of_internal_frontier_faces, const Static_Int_Lists & incidence_from_node_to_edges) const protected
Definition at line 559 of file Refine_Mesh.cpp.
{
  const int nb_internal_frontier = domaine().zone(0).nb_frontieres_internes();
  new_nodes_of_internal_frontier_faces.dimensionner(nb_internal_frontier);
  new_cells_of_internal_frontier_faces.dimensionner(nb_internal_frontier);
  int internal_frontier = 0;
  CONST_LIST_CURSEUR(Faces_Interne) cursor(domaine().zone(0).faces_int());
  while (cursor)
    {
      IntTab& nodes = new_nodes_of_internal_frontier_faces[internal_frontier];
      IntTab& cells = new_cells_of_internal_frontier_faces[internal_frontier];
      build_new_frontier_faces_2D(nodes,cells,incidence_from_node_to_edges,cursor.valeur().faces());
      ++cursor;
      ++internal_frontier;
    }
}
References build_new_frontier_faces_2D(), CONST_LIST_CURSEUR, vect_impl::dimensionner(), Interprete_geometrique_base::domaine(), Zone::nb_frontieres_internes(), and Domaine::zone().
Referenced by apply_2D().
build_new_internal_frontier_faces_3D()
void Refine_Mesh::build_new_internal_frontier_faces_3D (IntTabs & new_nodes_of_internal_frontier_faces, IntTabs & new_cells_of_internal_frontier_faces, const Static_Int_Lists & incidence_from_node_to_edges) const protected
Definition at line 580 of file Refine_Mesh.cpp.
{
  const int nb_internal_frontier = domaine().zone(0).nb_frontieres_internes();
  new_nodes_of_internal_frontier_faces.dimensionner(nb_internal_frontier);
  new_cells_of_internal_frontier_faces.dimensionner(nb_internal_frontier);
  int internal_frontier = 0;
  CONST_LIST_CURSEUR(Faces_Interne) cursor(domaine().zone(0).faces_int());
  while (cursor)
    {
      IntTab& nodes = new_nodes_of_internal_frontier_faces[internal_frontier];
      IntTab& cells = new_cells_of_internal_frontier_faces[internal_frontier];
      build_new_frontier_faces_3D(nodes,cells,incidence_from_node_to_edges,cursor.valeur().faces());
      ++cursor;
      ++internal_frontier;
    }
}
References build_new_frontier_faces_3D(), CONST_LIST_CURSEUR, vect_impl::dimensionner(), Interprete_geometrique_base::domaine(), Zone::nb_frontieres_internes(), and Domaine::zone().
Referenced by apply_3D().
build_new_nodes()
void Refine_Mesh::build_new_nodes (DoubleTab & new_nodes, const IntTab & nodes_of_edges) const protected
Definition at line 293 of file Refine_Mesh.cpp.
{
  const DoubleTab& nodes = domaine().les_sommets();
  const int nb_nodes = nodes.dimension(0);
  const int nb_edges = nodes_of_edges.dimension(0);
  new_nodes.resize(nb_nodes+nb_edges,Objet_U::dimension);
  for (int n=0; n<nb_nodes; ++n)
    {
      for (int i=0; i<Objet_U::dimension; ++i)
        {
          new_nodes(n,i) = nodes(n,i);
        }
    }
  for (int e=0; e<nb_edges; ++e)
    {
      for (int i=0; i<Objet_U::dimension; ++i)
        {
          new_nodes(e+nb_nodes,i) = 0.5 * (nodes(nodes_of_edges(e,0),i) + nodes(nodes_of_edges(e,1),i));
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Interprete_geometrique_base::domaine(), Domaine::les_sommets(), and TRUSTTab< _TYPE_ >::resize().
Referenced by apply_2D(), and apply_3D().
build_new_sub_zones_descriptions()
void Refine_Mesh::build_new_sub_zones_descriptions (Noms & new_sub_zones_descriptions) const protected
Definition at line 413 of file Refine_Mesh.cpp.
{
  const int nb_sub_zones = domaine().nb_ss_zones();
  sub_zones_descriptions.dimensionner(nb_sub_zones);
  const int nb_new_cells_per_old_cell = (Objet_U::dimension == 2) ? 4 : 8;
  for (int i=0; i<nb_sub_zones; ++i)
    {
      const Sous_Zone& sub_zone = domaine().ss_zone(i);
      const int old_nb_cells_in_sub_zone = sub_zone.nb_elem_tot();
      const int new_nb_cells_in_sub_zone = old_nb_cells_in_sub_zone * nb_new_cells_per_old_cell;
      IntVect new_sub_zone_cells(new_nb_cells_in_sub_zone);
      int idx = 0;
      for (int c=0; c<old_nb_cells_in_sub_zone; ++c)
        {
          const int old_cell = sub_zone[c];
          for (int j=0; j<nb_new_cells_per_old_cell; ++j)
            {
              new_sub_zone_cells[idx] = old_cell*nb_new_cells_per_old_cell+j;
              ++idx;
            }
        }
      SChaine os;
      os << " { Liste " << new_sub_zone_cells << " } ";
      sub_zones_descriptions[i] = Nom(os.get_str());
    }
}
References Objet_U::dimension, vect_impl::dimensionner(), Interprete_geometrique_base::domaine(), SChaine::get_str(), Sous_Zone::nb_elem_tot(), Domaine::nb_ss_zones(), and Domaine::ss_zone().
Referenced by apply_2D(), and apply_3D().
check_cell_type()
void Refine_Mesh::check_cell_type (void) const protected
Definition at line 89 of file Refine_Mesh.cpp.
{
  const Nom& cell_type = domaine().zone(0).type_elem().valeur().que_suis_je();
  if ( ! ( (cell_type == Motcle("Triangle")) || (cell_type == Motcle("Tetraedre")) ) )
    {
      Cerr << "Error in 'Refine_Mesh::check_cell_type()':" << finl;
      Cerr << "  Invalid cell type: " << cell_type << finl;
      Cerr << "  Refine_Mesh can only deal with triangles and tetrahedrons" << finl;
      Process::exit();
    }
}
References Cerr, Interprete_geometrique_base::domaine(), Process::exit(), finl, Objet_U::que_suis_je(), Zone::type_elem(), Deriv_Elem_geom_base::valeur(), and Domaine::zone().
Referenced by apply().
check_dimension()
void Refine_Mesh::check_dimension (void) const protected
Definition at line 67 of file Refine_Mesh.cpp.
{
  if ( ! ( (Objet_U::dimension == 2) || (Objet_U::dimension == 3) ) )
    {
      Cerr << "Error in 'Refine_Mesh::check_dimension()':" << finl;
      Cerr << "  Invalid dimension: " << Objet_U::dimension << finl;
      Cerr << "  Refine_Mesh can only deal 2D or 3D domains" << finl;
      Process::exit();
    }
}
References Cerr, Objet_U::dimension, Process::exit(), and finl.
Referenced by apply().
check_nb_zones()
void Refine_Mesh::check_nb_zones (void) const protected
Definition at line 78 of file Refine_Mesh.cpp.
{
  if ( domaine().nb_zones() != 1 )
    {
      Cerr << "Error in 'Refine_Mesh::check_nb_zones()':" << finl;
      Cerr << "  Invalid number of zones: " << domaine().nb_zones() << finl;
      Cerr << "  Refine_Mesh cannot deal with domains having more than one zone" << finl;
      Process::exit();
    }
}
References Cerr, Interprete_geometrique_base::domaine(), Process::exit(), finl, and Domaine::nb_zones().
Referenced by apply().
cree_instance()
Objet_U * Refine_Mesh::cree_instance () static
Definition at line 25 of file Refine_Mesh.cpp.
duplique()
int Refine_Mesh::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file Refine_Mesh.cpp.
find_edge()
int Refine_Mesh::find_edge (const Static_Int_Lists & incidence_from_node_to_edges, int node0, int node1) const protected
Definition at line 674 of file Refine_Mesh.cpp.
{
  ArrOfInt edges0;
  incidence_from_node_to_edges.copy_list_to_array(node0, edges0);
  ArrOfInt edges1;
  incidence_from_node_to_edges.copy_list_to_array(node1, edges1);
  array_calculer_intersection(edges0,edges1);
  assert( edges0.size_array() == 1 );
  return edges0[0];
}
References array_calculer_intersection(), Static_Int_Lists::copy_list_to_array(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by build_new_frontier_faces_2D(), and build_new_frontier_faces_3D().
get_info()
const Type_info * Refine_Mesh::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 25 of file Refine_Mesh.cpp.
info()
const Type_info * Refine_Mesh::info () static
Definition at line 25 of file Refine_Mesh.cpp.
interpreter_()
Entree & Refine_Mesh::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base.
Definition at line 40 of file Refine_Mesh.cpp.
{
  associer_domaine(is);
  apply();
  return is;
}
References apply(), and Interprete_geometrique_base::associer_domaine().
printOn()
Sortie & Refine_Mesh::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 27 of file Refine_Mesh.cpp.
{
  Interprete::printOn(os);
  return os;
}
References Interprete::printOn().
readOn()
Entree & Refine_Mesh::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 33 of file Refine_Mesh.cpp.
{
  Interprete::readOn(is);
  return is;
}
References Interprete::readOn().
self_cast() [1/2]
const Refine_Mesh & Refine_Mesh::self_cast (const Objet_U & r) static
Definition at line 25 of file Refine_Mesh.cpp.
self_cast() [2/2]
Refine_Mesh & Refine_Mesh::self_cast (Objet_U & r) static
Definition at line 25 of file Refine_Mesh.cpp.
taille_memoire()
unsigned Refine_Mesh::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file Refine_Mesh.cpp.
update_boundary_faces()
void Refine_Mesh::update_boundary_faces (const Type_Face & face_type, const IntTabs & new_nodes_of_boundary_faces, const IntTabs & new_cells_of_boundary_faces) protected
Definition at line 738 of file Refine_Mesh.cpp.
{
  int boundary = 0;
  LIST_CURSEUR(Bord) cursor(domaine().zone(0).faces_bord());
  while (cursor)
    {
      Faces& faces = cursor.valeur().faces();
      faces.typer(face_type);
      faces.les_sommets().ref(new_nodes_of_boundary_faces[boundary]);
      faces.voisins().ref(new_cells_of_boundary_faces[boundary]);
      ++cursor;
      ++boundary;
    }
}
References Interprete_geometrique_base::domaine(), Faces::les_sommets(), LIST_CURSEUR, TRUSTTab< _TYPE_ >::ref(), Faces::typer(), and Faces::voisins().
Referenced by update_domain().
update_cells()
void Refine_Mesh::update_cells (const IntTab & new_cells) protected
Definition at line 714 of file Refine_Mesh.cpp.
{
  domaine().zone(0).les_elems().ref(new_cells);
}
References Interprete_geometrique_base::domaine(), Zone::les_elems(), TRUSTTab< _TYPE_ >::ref(), and Domaine::zone().
Referenced by update_domain().
update_connector_faces()
void Refine_Mesh::update_connector_faces (const Type_Face & face_type, const IntTabs & new_nodes_of_connector_faces, const IntTabs & new_cells_of_connector_faces) protected
Definition at line 755 of file Refine_Mesh.cpp.
{
  int connector = 0;
  LIST_CURSEUR(Raccord) cursor(domaine().zone(0).faces_raccord());
  while (cursor)
    {
      Faces& faces = cursor.valeur().valeur().faces();
      faces.typer(face_type);
      faces.les_sommets().ref(new_nodes_of_connector_faces[connector]);
      faces.voisins().ref(new_cells_of_connector_faces[connector]);
      ++cursor;
      ++connector;
    }
}
References Interprete_geometrique_base::domaine(), Faces::les_sommets(), LIST_CURSEUR, TRUSTTab< _TYPE_ >::ref(), Faces::typer(), and Faces::voisins().
Referenced by update_domain().
update_domain()
void Refine_Mesh::update_domain (const Nom & cell_type, const Type_Face & face_type, const DoubleTab & new_nodes, const IntTab & new_cells, const Noms & new_sub_zones_descriptions, const IntTabs & new_nodes_of_boundary_faces, const IntTabs & new_cells_of_boundary_faces, const IntTabs & new_nodes_of_connector_faces, const IntTabs & new_cells_of_connector_faces, const IntTabs & new_nodes_of_internal_frontier_faces, const IntTabs & new_cells_of_internal_frontier_faces) protected
Definition at line 688 of file Refine_Mesh.cpp.
{
  update_nodes(new_nodes);
  update_cells(new_cells);
  update_octree(cell_type);
  update_sub_zones(new_sub_zones_descriptions);
  update_boundary_faces(face_type,new_nodes_of_boundary_faces,new_cells_of_boundary_faces);
  update_connector_faces(face_type,new_nodes_of_connector_faces,new_cells_of_connector_faces);
  update_internal_frontier_faces(face_type,new_nodes_of_internal_frontier_faces,new_cells_of_internal_frontier_faces);
}
References update_boundary_faces(), update_cells(), update_connector_faces(), update_internal_frontier_faces(), update_nodes(), update_octree(), and update_sub_zones().
Referenced by apply_2D(), and apply_3D().
update_internal_frontier_faces()
void Refine_Mesh::update_internal_frontier_faces (const Type_Face & face_type, const IntTabs & new_nodes_of_internal_frontier_faces, const IntTabs & new_cells_of_internal_frontier_faces) protected
Definition at line 772 of file Refine_Mesh.cpp.
{
  int internal_frontier = 0;
  LIST_CURSEUR(Faces_Interne) cursor(domaine().zone(0).faces_int());
  while (cursor)
    {
      Faces& faces = cursor.valeur().faces();
      faces.typer(face_type);
      faces.les_sommets().ref(new_nodes_of_internal_frontier_faces[internal_frontier]);
      faces.voisins().ref(new_cells_of_internal_frontier_faces[internal_frontier]);
      ++cursor;
      ++internal_frontier;
    }
}
References Interprete_geometrique_base::domaine(), Faces::les_sommets(), LIST_CURSEUR, TRUSTTab< _TYPE_ >::ref(), Faces::typer(), and Faces::voisins().
Referenced by update_domain().
update_nodes()
void Refine_Mesh::update_nodes (const DoubleTab & new_nodes) protected
Definition at line 709 of file Refine_Mesh.cpp.
{
  domaine().les_sommets().ref(new_nodes);
}
References Interprete_geometrique_base::domaine(), Domaine::les_sommets(), and TRUSTTab< _TYPE_ >::ref().
Referenced by update_domain().
update_octree()
void Refine_Mesh::update_octree (const Nom & cell_type) protected
Definition at line 719 of file Refine_Mesh.cpp.
{
  domaine().zone(0).invalide_octree();
  domaine().zone(0).typer(cell_type);
  domaine().zone(0).construit_octree();
}
References Zone::construit_octree(), Interprete_geometrique_base::domaine(), Zone::invalide_octree(), Zone::typer(), and Domaine::zone().
Referenced by update_domain().
update_sub_zones()
void Refine_Mesh::update_sub_zones (const Noms & new_sub_zones_descriptions) protected
Definition at line 726 of file Refine_Mesh.cpp.
{
  const int nb_sub_zones = domaine().nb_ss_zones();
  for (int i=0; i<nb_sub_zones; ++i)
    {
      Sous_Zone& sub_zone    = domaine().ss_zone(i);
      const Nom& description = new_sub_zones_descriptions[i];
      EChaine is(description.getChar());
      is >> sub_zone;
    }
}
References Interprete_geometrique_base::domaine(), Nom::getChar(), Domaine::nb_ss_zones(), and Domaine::ss_zone().
Referenced by update_domain().
Member Data Documentation
info_obj
const Type_info Refine_Mesh::info_obj static
Definition at line 37 of file Refine_Mesh.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Refine_Mesh.h
src/Kernel/Geometrie/Refine_Mesh.cpp