TRUST: Matrice33 Class Reference
Matrice33 Class Reference
une matrice 3x3.
Convention pour m(i,j): i est l'indice de ligne, j l'indice de colonne entre 0 et 2 inclus.
Attention: le constructeur par defaut n'initialise pas la matrice !
#include <Matrice33.h>
Public Member Functions
Matrice33 ()
Matrice33 (double m00, double m01, double m02, double m10, double m11, double m12, double m20, double m21, double m22)
double operator() (int i, int j) const
double & operator() (int i, int j)
double norme_Linfini ()
calcul de la norme Linfini de la matrice
Propriete: on note |x| la norme Linfini de x (vecteur ou matrice)
On a |m * x| <= |m| * |x|
En pratique: c'est le max sur j de la somme sur i de std::fabs(m(i,j))
Static Public Member Functions
static void produit (const Matrice33 &m, const Vecteur3 &x, Vecteur3 &y)
produit avec de la matrice avec le vecteur x.
static double inverse (const Matrice33 &m, Matrice33 &resu, int exit_on_error=1)
calcul de l'inverse.
Si le determinant de "matrice" est nul, exit() si exit_on_error (valeur par defaut)
sinon on ne remplit pas matrice_inv et on renvoie 0.
Valeur de retour: determinant de la "matrice" (pas de l'inverse !)
Protected Attributes
double m [3][3]
Detailed Description
une matrice 3x3.
Convention pour m(i,j): i est l'indice de ligne, j l'indice de colonne entre 0 et 2 inclus.
Attention: le constructeur par defaut n'initialise pas la matrice !
Definition at line 24 of file Matrice33.h.
Constructor & Destructor Documentation
Matrice33() [1/2]
Matrice33::Matrice33 () inline
Definition at line 27 of file Matrice33.h.
{};
Matrice33() [2/2]
Matrice33::Matrice33 (double m00, double m01, double m02, double m10, double m11, double m12, double m20, double m21, double m22) inline
Definition at line 28 of file Matrice33.h.
  {
    m[0][0] = m00;
    m[0][1] = m01;
    m[0][2] = m02;
    m[1][0] = m10;
    m[1][1] = m11;
    m[1][2] = m12;
    m[2][0] = m20;
    m[2][1] = m21;
    m[2][2] = m22;
  }
References m.
Member Function Documentation
inverse()
double Matrice33::inverse (const Matrice33 & m, Matrice33 & resu, int exit_on_error = 1) inline static
calcul de l'inverse.
Si le determinant de "matrice" est nul, exit() si exit_on_error (valeur par defaut)
sinon on ne remplit pas matrice_inv et on renvoie 0.
Valeur de retour: determinant de la "matrice" (pas de l'inverse !)
Definition at line 69 of file Linear_algebra_tools_impl.h.
{
  const double a00 = matrice.m[0][0];
  const double a01 = matrice.m[0][1];
  const double a02 = matrice.m[0][2];
  const double a10 = matrice.m[1][0];
  const double a11 = matrice.m[1][1];
  const double a12 = matrice.m[1][2];
  const double a20 = matrice.m[2][0];
  const double a21 = matrice.m[2][1];
  const double a22 = matrice.m[2][2];
// calcul de valeurs temporaires pour optimisation
  const double t4 = a00*a11;
  const double t6 = a00*a12;
  const double t8 = a01*a10;
  const double t10 = a02*a10;
  const double t12 = a01*a20;
  const double t14 = a02*a20;
  const double t = t4*a22-t6*a21-t8*a22+t10*a21+t12*a12-t14*a11;
  if (t==0.)
    {
      if (exit_on_error)
        {
          Cerr << "Error in Matrice33::inverse: determinant is null" << finl;
          Process::exit();
        }
// To avoid the compiler to complain about "might be non initialized":
      for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
          matrice_inv.m[i][j] = 0.;
      return 0.;
    }
  const double t17 = 1/(t);
// calcul de la matrice inverse
  matrice_inv.m[0][0] = (a11*a22-a12*a21)*t17;
  matrice_inv.m[0][1] = -(a01*a22-a02*a21)*t17;
  matrice_inv.m[0][2] = -(-a01*a12+a02*a11)*t17;
  matrice_inv.m[1][0] = (-a10*a22+a12*a20)*t17;
  matrice_inv.m[1][1] = (a00*a22-t14)*t17;
  matrice_inv.m[1][2] = -(t6-t10)*t17;
  matrice_inv.m[2][0] = -(-a10*a21+a11*a20)*t17;
  matrice_inv.m[2][1] = -(a00*a21-t12)*t17;
  matrice_inv.m[2][2] = (t4-t8)*t17;
  return t;
}
References Cerr, Process::exit(), finl, and m.
Referenced by Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Tetraedre::coord_bary(), and Op_Diff_PolyMAC_Face::dimensionner_blocs_ext().
norme_Linfini()
double Matrice33::norme_Linfini () inline
calcul de la norme Linfini de la matrice
Propriete: on note |x| la norme Linfini de x (vecteur ou matrice)
On a |m * x| <= |m| * |x|
En pratique: c'est le max sur j de la somme sur i de std::fabs(m(i,j))
Definition at line 23 of file Linear_algebra_tools_impl.h.
{
  double x = std::fabs(m[0][0]) + std::fabs(m[0][1]) + std::fabs(m[0][2]);
  double y = std::fabs(m[1][0]) + std::fabs(m[1][1]) + std::fabs(m[1][2]);
  double z = std::fabs(m[2][0]) + std::fabs(m[2][1]) + std::fabs(m[2][2]);
  double resu = ((x > y) ? x : y);
  resu = ((resu > z) ? resu : z);
  return resu;
}
References m.
Referenced by Tetraedre::coord_bary().
operator()() [1/2]
double & Matrice33::operator() (int i, int j) inline
Definition at line 47 of file Matrice33.h.
  {
    assert(i >= 0 && i < 3 && j >= 0 && j < 3);
    return m[i][j];
  }
References m.
operator()() [2/2]
double Matrice33::operator() (int i, int j) const inline
Definition at line 42 of file Matrice33.h.
  {
    assert(i >= 0 && i < 3 && j >= 0 && j < 3);
    return m[i][j];
  }
References m.
produit()
void Matrice33::produit (const Matrice33 & m, const Vecteur3 & x, Vecteur3 & y) inline static
produit avec de la matrice avec le vecteur x.
Definition at line 34 of file Linear_algebra_tools_impl.h.
{
  y.v[0] = m.m[0][0] * x.v[0] + m.m[0][1] * x.v[1] + m.m[0][2] * x.v[2];
  y.v[1] = m.m[1][0] * x.v[0] + m.m[1][1] * x.v[1] + m.m[1][2] * x.v[2];
  y.v[2] = m.m[2][0] * x.v[0] + m.m[2][1] * x.v[1] + m.m[2][2] * x.v[2];
}
References m, and Vecteur3::v.
Referenced by Tetraedre::coord_bary().
Member Data Documentation
m
double Matrice33::m[3][3] protected
Definition at line 57 of file Matrice33.h.
Referenced by inverse(), Matrice33(), norme_Linfini(), operator()(), and produit().
The documentation for this class was generated from the following files:
src/Kernel/Math/Matrice33.h
src/Kernel/Math/Linear_algebra_tools_impl.h