TRUST: Zone_VF Class Reference
Zone_VF Class Reference abstract
class Zone_VF
Cette classe abstraite contient les informations geometriques
communes aux methodes de Volumes Finis (methodes VDF et VEF par exemple)
#include <Zone_VF.h>
Public Member Functions
Zone_VF ()
~Zone_VF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double face_normales (int, int) const =0
void calculer_face_surfaces (const DoubleVect &surfaces)
virtual const DoubleVect & face_surfaces () const
virtual double face_surfaces (int i) const
virtual double surface (int i) const
void discretiser () override
Genere les faces
construits les frontieres.
void infobord ()
void info_elem_som ()
void calculer_porosites ()
void calculer_diametres_hydrauliques ()
void calculer_sections_passage ()
void calculer_coefficient_echange_thermique ()
void calculer_coefficient_frottement ()
void marquer_faces_double_contrib (const Conds_lim &)
virtual void typer_elem (Zone &)
virtual void remplir_face_voisins_fictifs (const Zone_Cl_dis_base &)
virtual Faces * creer_faces ()
renvoie new(Faces) !
elle est surchargee par Zone_VDF par ex.
virtual void reordonner (Faces &)
cette methode ne fait rien
elle est surchargee par Zone_VDF par ex.
int nb_joints () const
renvoie le nombre de joints
int premiere_face_int () const
une face est interne ssi elle separe deux elements.
renvoie le numero de la premiere face interne.
int nb_faces () const
renvoie le nombre global de faces.
int nb_faces_tot () const
renvoie le nombre total de faces.
C'est-a-dire faces reelles + faces virtuelles
int nb_som_face () const
renvoie le nombre de sommets par face.
Rque : on a suppose que toutes les faces avait
le meme nombre de sommet ce qui exclue des elements
comme le prisme.
int nb_faces_bord () const
renvoie le nombre de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_bord_tot () const
renvoie le nombre total de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int premiere_face_bord () const
renvoie le numero de la premiere des faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_internes () const
une face est interne ssi elle separe deux elements.
renvoie le nombre de faces internes.
double xv (int, int) const
double xp (int, int) const
double xa (int, int) const
double porosite_face (int) const
double porosite_elem (int) const
double diametre_hydraulique_face (int) const
double section_passage_face (int) const
double coefficient_frottement (int) const
double coefficient_echange_thermique (int) const
int face_numero_bord (int num_face) const
IntTab & face_numero_bord ()
const IntTab & face_numero_bord () const
void remplir_face_numero_bord ()
virtual const IntVect & orientation () const
virtual int orientation (int) const
virtual int orientation_si_definie (int) const
DoubleTab normalized_boundaries_outward_vector (int global_face_number, double scale_factor) const
Compute the normalized boundary outward vector associated to the face global_face_number
and eventually scaled by scale_factor.
DoubleTab & xv ()
const DoubleTab & xv () const
DoubleTab & xp ()
const DoubleTab & xp () const
DoubleTab & xa ()
const DoubleTab & xa () const
DoubleVect & volumes_entrelaces ()
const DoubleVect & volumes_entrelaces () const
double volumes_entrelaces (int num_face) const
const DoubleTab & volumes_entrelaces_dir () const
DoubleTab & volumes_entrelaces_dir ()
DoubleVect & porosite_face ()
const DoubleVect & porosite_face () const
DoubleVect & porosite_elem ()
const DoubleVect & porosite_elem () const
DoubleVect & diametre_hydraulique_face ()
const DoubleVect & diametre_hydraulique_face () const
const DoubleVect section_passage_face () const
DoubleTab & diametre_hydraulique_elem ()
const DoubleTab & diametre_hydraulique_elem () const
DoubleVect & coefficient_frottement ()
const DoubleVect & coefficient_frottement () const
DoubleVect & coefficient_echange_thermique ()
const DoubleVect & coefficient_echange_thermique () const
const Joint & joint (int i) const
renvoie le ieme joint.
Joint & joint (int i)
renvoie le ieme joint.
Frontiere_dis_base & frontiere_dis (int) override
renvoie la ieme frontiere_discrete.
const Frontiere_dis_base & frontiere_dis (int) const override
renvoie la ieme frontiere_discrete.
int nb_frontiere_dis () const
const Front_VF & front_VF (int) const
renvoie la ieme frontiere_discrete.
double volumes (int i) const
renvoie le volume de la maille i.
double inverse_volumes (int i) const
int face_voisins (int num_face, int i) const
renvoie l'element voisin de numface dans la direction i.
i=0 : dans le sens oppose de l'axe orthogonal a la face numface.
i=1 : dans le sens de l'axe orthogonal a la face numface.
exemple :
| 0 | 1 |
numface
renvoie -1 si l'element n'existe pas (au bord).
int elem_faces (int i, int j) const
renvoie le numero de le ieme face de la maille num_elem
la facon dont ces faces sont numerotees est
laisse a la responsabilite des classes derivees
int face_sommets (int i, int j) const
renvoie le numero du ieme sommet de la face num_face.
DoubleVect & volumes ()
renvoie le tableaux des volumes des mailles.
DoubleVect & inverse_volumes ()
Tableau pour optimiser le code.
const DoubleVect & volumes () const
renvoie le tableaux des volumes des mailles.
const DoubleVect & inverse_volumes () const
Tableau pour optimiser le code.
IntTab & face_voisins () override
renvoie le tableaux des volumes des connectivites face elements
cf au dessus.
const IntTab & face_voisins () const override
cf au dessus.
const IntTab & face_voisins_fictifs () const
void face_voisins_reel_fictif (int face, int &el0, int &elf) const
renvoie dans el0 le numero de l'elt a l'interieur
renvoie dans elf le numero de l'elt fictif (-1 si il n'existe pas)
IntTab & elem_faces ()
renvoie le tableau de connectivite element/faces
const IntTab & elem_faces () const
cf au dessus.
ArrOfInt & faces_doubles ()
renvoie 1 pour les faces appartenant a un bord perio ou un item commun, 0 par defaut
const ArrOfInt & faces_doubles () const
cf au dessus
IntTab & face_sommets () override
renvoie le tableau de connectivite faces/sommets.
const IntTab & face_sommets () const override
cf au dessus.
void modifier_pour_Cl (const Conds_lim &) override
int numero_face_local (int face, int elem) const
int numero_sommet_local (int som, int elem) const
const IntTab & get_num_fac_loc () const
int get_num_fac_loc (int, int) const
void construire_num_fac_loc ()
const ArrOfInt & ind_faces_virt_bord () const
int est_une_face_virt_bord (int) const
renvoie 1 si face est une face virtuelle de bord, 0 sinon
int fbord (int f) const
void construire_face_virt_pe_num ()
Remplissage du tableau face_virt_pe_num_ (voir commentaire dans Zone_VF.h)
const IntTab & face_virt_pe_num () const
virtual void creer_tableau_faces (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_aretes (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_faces_bord (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual const MD_Vector & md_vector_faces_bord () const
virtual const MD_Vector & md_vector_faces () const
virtual const MD_Vector & md_vector_aretes () const
virtual const DoubleTab & xv_bord () const
Public Member Functions inherited from Zone_dis_base
Zone_dis_base ()
~Zone_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Associe une Zone a l'objet.
const Zone & zone () const
Renvoie la Zone associee a l'objet.
(version const)
Zone & zone ()
Renvoie la Zone associee a l'objet.
void associer_domaine_dis (const Domaine_dis &)
Associe un Domaine_dis a l'objet.
const Domaine_dis & domaine_dis () const
Domaine_dis & domaine_dis ()
virtual void discretiser ()=0
virtual void creer_elements_fictifs (const Zone_Cl_dis_base &)
virtual Frontiere_dis_base & frontiere_dis (int)=0
virtual const Frontiere_dis_base & frontiere_dis (int) const =0
int rang_frontiere (const Nom &)
int rang_frontiere (const Nom &) const
Renvoie le rang de la frontiere de Nom nom
Renvoie -1 si aucune frontiere ne s'appelle nom.
Frontiere_dis_base & frontiere_dis (const Nom &)
const Frontiere_dis_base & frontiere_dis (const Nom &) const
Renvoie la frontiere de Nom nom.
(On indexe les frontiere avec leur nom)
void ecrire_noms_bords (Sortie &) const
Ecriture des noms des bords sur un flot de sortie.
virtual void modifier_pour_Cl (const Conds_lim &)=0
virtual IntTab & face_sommets ()
virtual const IntTab & face_sommets () const
virtual IntTab & face_voisins ()
virtual const IntTab & face_voisins () const
int nb_elem () const
int nb_elem_tot () const
int nb_som () const
int nb_som_tot () const
int nb_front_Cl () const
virtual void init_dist_paroi_globale (const Conds_lim &conds_lim)
virtual const DoubleTab & y_elem () const
virtual const DoubleTab & y_faces () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Zone_VF & self_cast (Objet_U &)
static const Zone_VF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_dis_base
static const Type_info * info ()
static Zone_dis_base & self_cast (Objet_U &)
static const Zone_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Zone_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
virtual void remplir_elem_faces ()=0
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
DoubleVect volumes_
volumes des elements
DoubleVect inverse_volumes_
inverse du volumes des elements
DoubleVect volumes_entrelaces_
volumes entrelaces pour l'integration des Qdm
DoubleTab volumes_entrelaces_dir_
volumes entrelaces par cote
DoubleVect porosite_elem_
Porosites volumiques pour les volumes de controle de masse.
DoubleVect porosite_face_
Porosites surfaciques en masse et volumiques.
DoubleVect diametre_hydraulique_face_
DoubleTab diametre_hydraulique_elem_
DoubleVect coefficient_echange_thermique_
remplissage des coefficients d'echange_thermique
DoubleVect coefficient_frottement_
remplissage des coefficient de frottement
IntTab face_voisins_
connectivite face/elements
IntTab face_voisins_fictifs_
connectivite face/elements fictifs
DoubleTab xp_
centres de gravite des elements
DoubleTab xv_
centres de gravite des faces
DoubleTab xv_bord_
IntTab elem_faces_
connectivite element/faces
IntTab face_sommets_
sommets des faces
DoubleTab xa_
centres de gravite des aretes
IntTab face_numero_bord_
connectivite face/numero_bord
MD_Vector md_vector_faces_
MD_Vector md_vector_faces_front_
MD_Vector md_vector_aretes_
Vect_Front_VF les_bords_
IntTab num_fac_loc_
ArrOfInt faces_doubles_
faces a double contribution (faces periodiques et items communs)
IntTab face_virt_pe_num_
Protected Attributes inherited from Zone_dis_base
Ref_Zone la_zone
Ref_Domaine_dis le_domaine_dis
DoubleTab y_elem_
DoubleTab y_faces_
int dist_paroi_initialisee_ = 0
Private Attributes
DoubleVect face_surfaces_
surface des faces
Detailed Description
class Zone_VF
Cette classe abstraite contient les informations geometriques
communes aux methodes de Volumes Finis (methodes VDF et VEF par exemple)
Definition at line 35 of file Zone_VF.h.
Constructor & Destructor Documentation
Zone_VF()
Zone_VF::Zone_VF ()
Definition at line 30 of file Zone_VF.cpp.
~Zone_VF()
Zone_VF::~Zone_VF () override
Definition at line 30 of file Zone_VF.cpp.
Member Function Documentation
calculer_coefficient_echange_thermique()
void Zone_VF::calculer_coefficient_echange_thermique ()
Definition at line 406 of file Zone_VF.cpp.
{
// coefficient d'echange_thermique a 0
  int nbfaces = xv_.dimension(0);
  coefficient_echange_thermique_.resize(nbfaces);
  coefficient_echange_thermique_ = 0;
}
References coefficient_echange_thermique_, TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::resize(), and xv_.
Referenced by Zone_VDF::discretiser().
calculer_coefficient_frottement()
void Zone_VF::calculer_coefficient_frottement ()
Definition at line 415 of file Zone_VF.cpp.
{
// coefficient de frottement a 0
  int nbfaces = xv_.dimension(0);
  coefficient_frottement_.resize(nbfaces);
  coefficient_frottement_= 0;
}
References coefficient_frottement_, TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::resize(), and xv_.
Referenced by Zone_VDF::discretiser().
calculer_diametres_hydrauliques()
void Zone_VF::calculer_diametres_hydrauliques ()
Definition at line 393 of file Zone_VF.cpp.
{
// les diametres hydrauliques valent 0
  creer_tableau_faces(diametre_hydraulique_face_, Array_base::NOCOPY_NOINIT);
  diametre_hydraulique_face_ = 0.;
// diametre_hydraulique_elem_.resize(0,Objet_U::dimension);
// Desormais diametre_hydraulique_elem_ scalaire
  zone().creer_tableau_elements(diametre_hydraulique_elem_, Array_base::NOCOPY_NOINIT);
  diametre_hydraulique_elem_ = 0.;
}
References Zone::creer_tableau_elements(), creer_tableau_faces(), diametre_hydraulique_elem_, diametre_hydraulique_face_, Array_base::NOCOPY_NOINIT, and Zone_dis_base::zone().
Referenced by Zone_Poly_base::discretiser(), and Zone_VDF::discretiser().
calculer_face_surfaces()
void Zone_VF::calculer_face_surfaces (const DoubleVect & surfaces) inline
Definition at line 43 of file Zone_VF.h.
  {
    face_surfaces_ = surfaces;
  };
References face_surfaces_.
calculer_porosites()
void Zone_VF::calculer_porosites ()
Definition at line 380 of file Zone_VF.cpp.
{
// Les porosites volumiques et surfacique valent 1
  zone().creer_tableau_elements(porosite_elem_, Array_base::NOCOPY_NOINIT);
  porosite_elem_ = 1;
  creer_tableau_faces(porosite_face_, Array_base::NOCOPY_NOINIT);
  porosite_face_ = 1;
}
References Zone::creer_tableau_elements(), creer_tableau_faces(), Array_base::NOCOPY_NOINIT, porosite_elem_, porosite_face_, and Zone_dis_base::zone().
Referenced by Zone_EF::discretiser(), Zone_Poly_base::discretiser(), Zone_VDF::discretiser(), and Zone_VEF::discretiser().
calculer_sections_passage()
void Zone_VF::calculer_sections_passage ()
coefficient_echange_thermique() [1/3]
DoubleVect & Zone_VF::coefficient_echange_thermique () inline
Definition at line 369 of file Zone_VF.h.
{
  return coefficient_echange_thermique_;
}
References coefficient_echange_thermique_.
coefficient_echange_thermique() [2/3]
const DoubleVect & Zone_VF::coefficient_echange_thermique () const inline
Definition at line 375 of file Zone_VF.h.
{
  return coefficient_echange_thermique_;
}
References coefficient_echange_thermique_.
coefficient_echange_thermique() [3/3]
double Zone_VF::coefficient_echange_thermique (int i) const inline
Definition at line 381 of file Zone_VF.h.
{
  return coefficient_echange_thermique_[i];
}
References coefficient_echange_thermique_.
coefficient_frottement() [1/3]
DoubleVect & Zone_VF::coefficient_frottement () inline
Definition at line 351 of file Zone_VF.h.
{
  return coefficient_frottement_;
}
References coefficient_frottement_.
coefficient_frottement() [2/3]
const DoubleVect & Zone_VF::coefficient_frottement () const inline
Definition at line 357 of file Zone_VF.h.
{
  return coefficient_frottement_;
}
References coefficient_frottement_.
coefficient_frottement() [3/3]
double Zone_VF::coefficient_frottement (int i) const inline
Definition at line 363 of file Zone_VF.h.
{
  return coefficient_frottement_[i];
}
References coefficient_frottement_.
construire_face_virt_pe_num()
void Zone_VF::construire_face_virt_pe_num ()
Remplissage du tableau face_virt_pe_num_ (voir commentaire dans Zone_VF.h)
Definition at line 425 of file Zone_VF.cpp.
{
  int i;
  const int nf = nb_faces();
  const int nf_tot = nb_faces_tot();
  const int nb_faces_virt = nf_tot - nf;
  IntTab tmp(0, 2);
  creer_tableau_faces(tmp, Array_base::NOCOPY_NOINIT);
  const int moi = me();
  for (i = 0; i < nf; i++)
    {
      tmp(i, 0) = moi;
      tmp(i, 1) = i;
    }
  tmp.echange_espace_virtuel();
  face_virt_pe_num_.resize(nb_faces_virt, 2);
// Copie de la partie virtuelle de tmp dans face_virt_pe_num_
  face_virt_pe_num_.inject_array(tmp, nb_faces_virt*2, 0 /* dest offset*/, nf * 2 /* source offset*/);
}
References creer_tableau_faces(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), face_virt_pe_num_, TRUSTArray< _TYPE_ >::inject_array(), Process::me(), nb_faces(), nb_faces_tot(), Array_base::NOCOPY_NOINIT, and TRUSTTab< _TYPE_ >::resize().
construire_num_fac_loc()
void Zone_VF::construire_num_fac_loc ()
Definition at line 328 of file Zone_VF.cpp.
{
  const int size = nb_faces_tot();
  num_fac_loc_.resize(size,2);
  num_fac_loc_=-1;
  for(int face=0; face<size; face++)
    for (int voisin=0; voisin<2; voisin++)
      {
        int elem = face_voisins_(face,voisin);
        if(elem!=-1)
          {
            int face_loc = numero_face_local(face,elem);
            if (face_loc != -1) num_fac_loc_(face,voisin) = face_loc;
            else
              {
// Cas periodique
                int autre_voisin = 1 - voisin;
                int elem2 = face_voisins(face,autre_voisin);
                int nb_faces_elem = elem_faces_.dimension(1);
                for (face_loc=0; face_loc<nb_faces_elem; face_loc++)
                  {
                    const int face_glob = elem_faces(elem,face_loc);
                    const int elem_voisin1 = face_voisins(face_glob,0);
                    const int elem_voisin2 = face_voisins(face_glob,1);
                    if (elem_voisin1==elem2 || elem_voisin2==elem2)
                      {
                        num_fac_loc_(face,voisin) = face_loc;
                        break;
                      }
                  }
              }
          }
      }
}
References TRUSTTab< _TYPE_ >::dimension(), elem_faces(), elem_faces_, face_voisins(), face_voisins_, nb_faces_tot(), num_fac_loc_, numero_face_local(), and TRUSTTab< _TYPE_ >::resize().
Referenced by modifier_pour_Cl(), and Zone_VEF::modifier_pour_Cl().
creer_faces()
Faces * Zone_VF::creer_faces () virtual
renvoie new(Faces) !
elle est surchargee par Zone_VDF par ex.
Reimplemented in Zone_VDF.
Definition at line 261 of file Zone_VF.cpp.
{
  Faces* les_faces=new(Faces);
  return les_faces;
}
Referenced by discretiser().
creer_tableau_aretes()
void Zone_VF::creer_tableau_aretes (Array_base & t, Array_base::Resize_Options opt = Array_base::COPY_INIT) const virtual
Definition at line 622 of file Zone_VF.cpp.
{
  const MD_Vector& md = md_vector_aretes();
  MD_Vector_tools::creer_tableau_distribue(md, t, opt);
}
References MD_Vector_tools::creer_tableau_distribue(), and md_vector_aretes().
Referenced by Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Zone_VEF_PreP1b::construire_renum_arete_perio(), Zone_PolyMAC::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Zone_VEF_PreP1b::lecture_ok_arete(), and Zone_VEF_PreP1b::modifier_pour_Cl().
creer_tableau_faces()
void Zone_VF::creer_tableau_faces (Array_base & t, Array_base::Resize_Options opt = Array_base::COPY_INIT) const virtual
Definition at line 617 of file Zone_VF.cpp.
{
  MD_Vector_tools::creer_tableau_distribue(md_vector_faces_, t, opt);
}
References MD_Vector_tools::creer_tableau_distribue(), and md_vector_faces_.
Referenced by Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::associer(), Op_Conv_VEF_base::associer(), Zone_Cl_VEF::associer(), Perte_Charge_Singuliere::calculate_Q(), calculer_diametres_hydrauliques(), calculer_porosites(), Zone_EF::calculer_volumes_entrelaces(), Zone_VDF::calculer_volumes_entrelaces(), Zone_VEF::calculer_volumes_entrelaces(), construire_face_virt_pe_num(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Zone_EF::discretiser(), Zone_Poly_base::discretiser(), discretiser(), Zone_VDF::discretiser(), Zone_VEF::discretiser(), Zone_VDF::genere_aretes(), Zone_Poly_base::init_dist_paroi_globale(), Zone_Poly_base::init_equiv(), Echange_contact_VDF::initialiser(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Perte_Charge_Singuliere::lire_surfaces(), EOS_Tools_VEF::moyenne_vol(), Zone_PolyMAC::orthocentrer(), and DP_Impose_PolyMAC_Face::remplir_num_faces().
creer_tableau_faces_bord()
void Zone_VF::creer_tableau_faces_bord (Array_base & t, Array_base::Resize_Options opt = Array_base::COPY_INIT) const virtual
Definition at line 628 of file Zone_VF.cpp.
{
  const MD_Vector& md = md_vector_faces_bord();
  MD_Vector_tools::creer_tableau_distribue(md, t, opt);
}
References MD_Vector_tools::creer_tableau_distribue(), and md_vector_faces_bord().
Referenced by Periodique::completer(), Zone_Cl_VDF::completer(), multiplier_diviser_rho(), and xv_bord().
diametre_hydraulique_elem() [1/2]
DoubleTab & Zone_VF::diametre_hydraulique_elem () inline
Definition at line 305 of file Zone_VF.h.
{
  return diametre_hydraulique_elem_;
}
References diametre_hydraulique_elem_.
Referenced by Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Discret_Thyd::diametre_hydraulique_elem(), and Diametre_hyd_champ::interpreter().
diametre_hydraulique_elem() [2/2]
const DoubleTab & Zone_VF::diametre_hydraulique_elem () const inline
Definition at line 311 of file Zone_VF.h.
{
  return diametre_hydraulique_elem_;
}
References diametre_hydraulique_elem_.
diametre_hydraulique_face() [1/3]
DoubleVect & Zone_VF::diametre_hydraulique_face () inline
Definition at line 317 of file Zone_VF.h.
{
  return diametre_hydraulique_face_;
}
References diametre_hydraulique_face_.
diametre_hydraulique_face() [2/3]
const DoubleVect & Zone_VF::diametre_hydraulique_face () const inline
Definition at line 323 of file Zone_VF.h.
{
  return diametre_hydraulique_face_;
}
References diametre_hydraulique_face_.
diametre_hydraulique_face() [3/3]
double Zone_VF::diametre_hydraulique_face (int i) const inline
Definition at line 329 of file Zone_VF.h.
{
  return diametre_hydraulique_face_[i];
}
References diametre_hydraulique_face_.
Referenced by Discret_Thyd::diametre_hydraulique_face(), and Diametre_hyd_champ::interpreter().
discretiser()
void Zone_VF::discretiser () override virtual
Genere les faces
construits les frontieres.
< Detache la structure parallele
< Extremas du domaine et volumes
< Aires des bords
< Nombre elements et sommets
Implements Zone_dis_base.
Reimplemented in Zone_VEF_PreP1b, Zone_PolyMAC, Zone_PolyMAC_P0, Zone_VDF, and Zone_VEF.
Definition at line 105 of file Zone_VF.cpp.
{
  Cerr << "<<<<<< Discretization VF >>>>>>>>>>" << finl;
  Zone& lazone=zone();
  histogramme_angle(lazone.domaine(),Cerr);
  Faces* les_faces_ptr=creer_faces();
  Faces& les_faces= *les_faces_ptr;
  {
    {
      Type_Face type_face = zone().type_elem().type_face(0);
      les_faces.typer(type_face);
      les_faces.associer_zone(zone());
      Static_Int_Lists connectivite_som_elem;
      const int     nb_sommets_tot = zone().domaine().nb_som_tot();
      const IntTab&    elements       = zone().les_elems();
      construire_connectivite_som_elem(nb_sommets_tot,
                                       elements,
                                       connectivite_som_elem,
                                       1 /* include virtual elements */);
      Faces_builder faces_builder;
      faces_builder.creer_faces_reeles(zone(),
                                       connectivite_som_elem,
                                       les_faces,
                                       elem_faces_);
    }
    reordonner(les_faces);
// Les faces sont dans l'ordre definitif, on peut remplir
// renum_items_communs des faces:
    Scatter::calculer_renum_items_communs(lazone.faces_joint(), Joint::FACE);
// Remplissage de face_voisins des frontieres:
// a factoriser avec DomaineCut.cpp
    {
      const IntTab& facevoisins = les_faces.voisins();
      const int nb_frontieres = lazone.nb_front_Cl();
      for (int i_frontiere = 0; i_frontiere < nb_frontieres; i_frontiere++)
        {
          Frontiere&   fr               = lazone.frontiere(i_frontiere);
          IntTab&      mes_face_voisins = fr.faces().voisins();
          const int nbfaces         = fr.nb_faces();
          const int premiere_face    = fr.num_premiere_face();
          mes_face_voisins.resize(nbfaces, 2);
          for (int i = 0; i < nbfaces; i++)
            {
              mes_face_voisins(i, 0) = facevoisins(premiere_face + i, 0);
              mes_face_voisins(i, 1) = facevoisins(premiere_face + i, 1);
            }
        }
    }
    Scatter::calculer_espace_distant_faces(zone(), les_faces.nb_faces(), elem_faces_);
// Apres la methode suivante, on aura le droit d'utiliser creer_tableau_faces() :
    Scatter::construire_md_vector(zone().domaine(), les_faces.nb_faces(), Joint::FACE, md_vector_faces_);
    const MD_Vector& md_vect_sommets = zone().domaine().les_sommets().get_md_vector();
    const MD_Vector& md_vect_elements = zone().les_elems().get_md_vector();
// Construction de l'espace virtuel du tableau face_sommets
    Scatter::construire_espace_virtuel_traduction(md_vector_faces_, md_vect_sommets, les_faces.les_sommets());
// Idem pour face_voisins_
// Certaines faces des elements virtuels les plus externes n'ont pas d'element local voisin => erreurs non fatales
    Scatter::construire_espace_virtuel_traduction(md_vector_faces_, md_vect_elements, les_faces.voisins(), 0 /* error not fatal */);
// Idem pour elem_faces_
    Scatter::construire_espace_virtuel_traduction(md_vect_elements, md_vector_faces_, elem_faces_);
    lazone.init_faces_virt_bord(md_vector_faces_, md_vector_faces_front_);
// Calcul des surfaces:
    les_faces.calculer_surfaces(face_surfaces_);
// Calcul de la surface des faces virtuelles
    MD_Vector md_nul;
    creer_tableau_faces(face_surfaces_);
    face_surfaces_.echange_espace_virtuel();
    face_surfaces_.set_md_vector(md_nul); //!< Detache la structure parallele
// Changement a la v1.5.7 beta: xv_ a maintenant un descripteur parallele: dimension(0)=nb_faces
    les_faces.calculer_centres_gravite(xv_);
    face_voisins().ref(les_faces.voisins());
    face_sommets().ref(les_faces.les_sommets());
// Calcul des volumes
    lazone.calculer_volumes(volumes_, inverse_volumes_);
  }
  {
    int i=0, derniere=lazone.nb_bords();
    les_bords_.dimensionner(zone().nb_front_Cl());
    for(; i<derniere; i++)
      {
        les_bords_[i].associer_frontiere(lazone.bord(i));
        les_bords_[i].associer_Zone_dis(*this);
      }
    int decal=derniere;
    derniere+=zone().nb_raccords();
    for(; i<derniere; i++)
      {
        int j=i-decal;
        les_bords_[i].associer_frontiere(lazone.raccord(j).valeur());
        les_bords_[i].associer_Zone_dis(*this);
      }
    decal=derniere;
    derniere+=zone().nb_frontieres_internes();
    for(; i<derniere; i++)
      {
        int j=i-decal;
        les_bords_[i].associer_frontiere(lazone.faces_interne(j));
        les_bords_[i].associer_Zone_dis(*this);
      }
  }
// Centre de gravite des elements (tableau xp_)
  lazone.calculer_centres_gravite(xp_);
// Centre de gravite de la zone
  ArrOfDouble c(dimension);
  lazone.calculer_mon_centre_de_gravite(c);
// On cree les domaines frontieres
  lazone.domaine().creer_mes_domaines_frontieres(*this);
// Attention : ca ne remplit pas elem_faces, ca fait
// creer_faces_virtuelles_non_std() en VEF :
  remplir_elem_faces();
  delete les_faces_ptr;
// Fill in the table face_numero_bord
  remplir_face_numero_bord();
//
// On imprime des infos
//
  lazone.domaine().imprimer();        //!< Extremas du domaine et volumes
  infobord();                        //!< Aires des bords
  info_elem_som();                //!< Nombre elements et sommets
  Cerr << "<<<<<< End of Discretization VF >>>>>>>>>>" << finl;
}
References Faces::associer_zone(), Zone::bord(), Faces::calculer_centres_gravite(), Zone::calculer_centres_gravite(), Scatter::calculer_espace_distant_faces(), Zone::calculer_mon_centre_de_gravite(), Scatter::calculer_renum_items_communs(), Faces::calculer_surfaces(), Zone::calculer_volumes(), Cerr, construire_connectivite_som_elem(), Scatter::construire_espace_virtuel_traduction(), Scatter::construire_md_vector(), creer_faces(), Faces_builder::creer_faces_reeles(), Domaine::creer_mes_domaines_frontieres(), creer_tableau_faces(), Objet_U::dimension, vect_impl::dimensionner(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), elem_faces_, Joint::FACE, face_sommets(), face_surfaces_, face_voisins(), Frontiere::faces(), Zone::faces_interne(), Zone::faces_joint(), finl, Zone::frontiere(), TRUSTVect< _TYPE_ >::get_md_vector(), histogramme_angle(), Domaine::imprimer(), info_elem_som(), infobord(), Zone::init_faces_virt_bord(), inverse_volumes_, les_bords_, Zone::les_elems(), Domaine::les_sommets(), Faces::les_sommets(), md_vector_faces_, md_vector_faces_front_, Zone::nb_bords(), Faces::nb_faces(), Frontiere::nb_faces(), Zone_dis_base::nb_front_Cl(), Zone::nb_front_Cl(), Zone::nb_frontieres_internes(), Zone::nb_raccords(), Domaine::nb_som_tot(), Frontiere::num_premiere_face(), Zone::raccord(), TRUSTTab< _TYPE_ >::ref(), remplir_elem_faces(), remplir_face_numero_bord(), reordonner(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::set_md_vector(), Zone::type_elem(), Elem_geom::type_face(), Faces::typer(), Deriv_Raccord_base::valeur(), Faces::voisins(), volumes_, xp_, xv_, and Zone_dis_base::zone().
Referenced by Zone_EF::discretiser(), Zone_Poly_base::discretiser(), Zone_VDF::discretiser(), Zone_VEF::discretiser(), and Discretiser_domaine::interpreter_().
elem_faces() [1/3]
IntTab & Zone_VF::elem_faces () inline
renvoie le tableau de connectivite element/faces
Definition at line 565 of file Zone_VF.h.
{
  return elem_faces_;
}
References elem_faces_.
Referenced by Zone_VDF::calcul_h(), Zone_EF::calculer_h_carre(), Zone_Poly_base::calculer_h_carre(), Zone_VEF::calculer_h_carre(), construire_num_fac_loc(), Zone_EF::discretiser(), Zone_Poly_base::discretiser(), Zone_VEF::discretiser(), Zone_VDF::dist_elem_period(), Zone_PolyMAC_P0::fgrad(), Zone_VDF::genere_aretes(), Zone_Poly_base::init_equiv(), Zone_PolyMAC::M1(), Zone_PolyMAC::M2(), Zone_VDF::modifier_pour_Cl(), Zone_PolyMAC::orthocentrer(), Zone_VEF::vecteur_face_facette(), Zone_PolyMAC::W1(), and Zone_PolyMAC::W2().
elem_faces() [2/3]
const IntTab & Zone_VF::elem_faces () const inline
cf au dessus.
Definition at line 572 of file Zone_VF.h.
{
  return elem_faces_;
}
References elem_faces_.
elem_faces() [3/3]
int Zone_VF::elem_faces (int i, int j) const inline
renvoie le numero de le ieme face de la maille num_elem
la facon dont ces faces sont numerotees est
laisse a la responsabilite des classes derivees
Definition at line 558 of file Zone_VF.h.
{
  return elem_faces_(num_elem, i);
}
References elem_faces_.
Referenced by Op_Curl_VEFP1B::ajouter(), Op_Rot_VEFP1B::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion_vectoriel(), Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Grad_P0_to_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Div_PolyMAC::ajouter_blocs(), Op_Grad_PolyMAC_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Sonde::ajouter_bords(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Conv_Muscl_New_VEF_Face::ajouter_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_diffusion(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Op_Dift_Stab_VEF_Face::ajouter_diffusion(), Op_Dift_Stab_VEF_Face::ajouter_diffusion_vectoriel(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_operateur_centre(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Op_Dift_Stab_VEF_Face::ajouter_operateur_centre(), Op_Dift_Stab_VEF_Face::ajouter_operateur_centre_vectoriel(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Assembleur_P_PolyMAC::assembler_continuite(), Assembleur_P_PolyMAC::assembler_mat(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Force_Centrifuge_VDF_Face_Axi::associer_zones(), Op_Diff_VEF_Face_Penalise::autre_face(), build_triofield(), calcul_bord2D(), calcul_bord3D(), calcul_dscald_bord2D(), calcul_dscald_bord3D(), calcul_dscald_interne2D(), calcul_dscald_interne3D(), Champ_Face::calcul_duidxj(), Champ_front_contact_VEF::calcul_grads_locaux(), calcul_interne2D(), calcul_interne3D(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Champ_P1NC::calcul_y_plus(), Champ_Q1NC_impl::calcule_valeur_a_elem_compo(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Dift_Stab_VEF_Face::calculer_coefficients(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Champ_Face::calculer_dercov_axi(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Champ_Face::calculer_dscald_centre_element(), Op_Dift_VEF_P1NCP1B_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Dift_VEF_Face_Q1::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Op_Dift_Stab_VEF_Face::calculer_gradients(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Dift_Stab_VEF_Face::calculer_min(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Champ_Face::calculer_rotationnel_ordre2_centre_element(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Discretisation_tools::cells_to_faces(), Champ_Face_get_val_imp_face_bord_sym(), Echange_contact_Correlation_VEF::completer(), Champ_front_contact_VEF::connectivity_failed(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Op_Div_VEFP1B_Elem::degres_liberte(), Op_Diff_VEF_Face_Penalise::diametre(), Eval_Quick_VDF_Face_Axi::dim_elem(), Op_EF_base::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Div_PolyMAC::dimensionner_blocs(), Op_Grad_PolyMAC_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Travail_pression_PolyMAC::dimensionner_blocs(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Assembleur_P_PolyMAC::dimensionner_continuite(), Source_WC_Chaleur_VEF::elem_to_face(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Eval_Quick_VDF_Face_Axi::face_amont_conj(), face_bord_amont2(), Source_WC_Chaleur_VDF::face_to_elem(), Discretisation_tools::faces_to_cells(), Champ_P1NC_implementation::filtrer_L2(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_refChamp::get_ref_connectivity(), Champ_input_P0::getTemplate(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Postraitement::init(), Champ_Face_PolyMAC_P0::init_ve2(), Sonde::initialiser(), Champ_front_lu::initialiser(), Champ_Face_PolyMAC::interp_ve(), Porosites::interpreter(), Perte_Charge_Singuliere::lire_surfaces(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Convection_Diffusion_Temperature::mise_en_place_zone_fantome(), modif_matrice_pour_periodique_apres_contribuer(), modif_matrice_pour_periodique_avant_contribuer(), Tetra_VEF::modif_volumes_entrelaces(), Tri_VEF::modif_volumes_entrelaces(), Tetra_VEF::modif_volumes_entrelaces_faces_joints(), Tri_VEF::modif_volumes_entrelaces_faces_joints(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), moy_2D_vit(), moy_3D_vit(), multiplier_diviser_rho(), Champ_P1NC::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Terme_Source_Canal_RANS_LES_VDF_Face::norme_vit(), Convection_Diffusion_Temperature::penalisation_L2(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Postraitement::postraiter_champs(), Format_Post_base::postraiter_debug_valeurs_un_instant(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Champ_front_contact_VEF::remplir_connect_bords(), Op_Conv_VEF_Face::remplir_fluent(), Zone_Cl_VEF::remplir_normales_facettes_Cl(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), remplir_sommets(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Zone_Cl_VEF::remplir_type_elem_Cl(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), EOS_Tools_VEF::secmembre_divU_Z(), Op_Conv_EF_VEF_P1NC_Stab::test(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Champ_Face_implementation::trace(), Champ_Q1NC_impl::transforme_coord2D(), Champ_Q1NC_impl::transforme_coord3D(), Convection_Diffusion_Temperature::transport_ibc(), grad_Champ_Face_PolyMAC_P0::update_ge(), Champ_Face_PolyMAC_P0::update_ve(), Champ_Face_implementation::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem(), Champ_Q1NC_impl::valeur_a_elem(), Champ_Face_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_sommet_compo(), Champ_Face_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Q1NC_impl::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_Q1NC_impl::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), Op_Diff_VEF_Face_Penalise::voisinage(), and Debog_Pb::write_geometry_data().
est_une_face_virt_bord()
int Zone_VF::est_une_face_virt_bord (int face) const inline
renvoie 1 si face est une face virtuelle de bord, 0 sinon
Definition at line 757 of file Zone_VF.h.
{
  if (face<nb_faces() || ind_faces_virt_bord()[face-nb_faces()]==-1)
    return 0;
  else
    return 1;
}
References ind_faces_virt_bord(), and nb_faces().
Referenced by assemblerP0P1(), assemblerP0Pa(), assemblerP1P1(), assemblerP1Pa(), assemblerPaPa(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Assembleur_P_VEF::remplir(), updateP0P1(), updateP0Pa(), updateP1P1(), updateP1Pa(), and updatePaPa().
face_normales()
virtual double Zone_VF::face_normales (int , int) const pure virtual
Implemented in Zone_EF, Zone_Poly_base, Zone_VF_inst, Zone_VDF, and Zone_VEF.
Referenced by Perte_Charge_Singuliere::calculate_Q(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Discretisation_tools::cells_to_faces(), Champ_front_calc_interne::completer(), Champ_Generique_Transformation::get_champ(), Zone_Cl_PolyMAC::imposer_cond_lim(), Ch_front_Vortex::initialiser(), Porosites::interpreter(), Perte_Charge_Singuliere::lire_surfaces(), normalized_boundaries_outward_vector(), orientation(), and orientation_si_definie().
face_numero_bord() [1/3]
IntTab & Zone_VF::face_numero_bord () inline
Definition at line 774 of file Zone_VF.h.
{
  return face_numero_bord_;
}
References face_numero_bord_.
face_numero_bord() [2/3]
const IntTab & Zone_VF::face_numero_bord () const inline
Definition at line 780 of file Zone_VF.h.
{
  return face_numero_bord_;
}
References face_numero_bord_.
face_numero_bord() [3/3]
int Zone_VF::face_numero_bord (int num_face) const inline
Definition at line 767 of file Zone_VF.h.
{
  assert(num_face < nb_faces());
  return face_numero_bord_(num_face);
}
References face_numero_bord_, and nb_faces().
face_sommets() [1/3]
const IntTab & Zone_VF::face_sommets () const inline override virtual
cf au dessus.
Reimplemented from Zone_dis_base.
Definition at line 607 of file Zone_VF.h.
{
  return face_sommets_;
}
References face_sommets_.
face_sommets() [2/3]
IntTab & Zone_VF::face_sommets () inline override virtual
renvoie le tableau de connectivite faces/sommets.
Reimplemented from Zone_dis_base.
Definition at line 600 of file Zone_VF.h.
{
  return face_sommets_;
}
References face_sommets_.
Referenced by Zone_VEF_PreP1b::construire_renum_arete_perio(), Zone_EF::discretiser(), Zone_Poly_base::discretiser(), discretiser(), Zone_VEF::discretiser(), Zone_VDF::dist_face_period(), Zone_PolyMAC_P0::fgrad(), Zone_Poly_base::init_dist_paroi_globale(), Zone_PolyMAC_P0::init_stencils(), Zone_PolyMAC::M1(), Zone_PolyMAC::orthocentrer(), Zone_VEF::vecteur_face_facette(), and Zone_PolyMAC::W1().
face_sommets() [3/3]
int Zone_VF::face_sommets (int i, int j) const inline
renvoie le numero du ieme sommet de la face num_face.
Definition at line 593 of file Zone_VF.h.
{
  return face_sommets_(num_face, i);
}
References face_sommets_.
Referenced by Champ_P1NC::affecter_(), Op_Div_EF::ajouter(), Op_Grad_EF::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), ajouter_bord(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Solveur_Masse_EF::appliquer_impl(), Assembleur_P_VDF_Q4::assembler(), build_triofield(), Aretes::calculer_centre_de_gravite(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Champ_Generique_Transformation::completer(), Champ_Post_Operateur_Eqn::completer(), construit_connectivite_sommet(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), Op_Div_VEFP1B_Elem::degres_liberte(), Op_EF_base::dimensionner(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Extraire_surface::extraire_surface(), Champ_P1NC_implementation::filtrer_H1(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Champ_Generique_refChamp::get_ref_connectivity(), get_ref_coordinates_items(), Champ_input_P0::getTemplate(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Zone_Cl_EF::imposer_cond_lim(), Zone_Cl_VEFP1B::imposer_cond_lim(), Zone_Cl_EF::imposer_symetrie_partiellement(), Echange_contact_Correlation_VEF::init(), Postraitement::init(), Echange_contact_PolyMAC_P0::init_fs_dist(), Champ_Face_PolyMAC_P0::init_ve2(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Perte_Charge_Singuliere::lire_surfaces(), Op_Diff_VEF_Face_Penalise::longueur(), modifieP1P1neumann(), Op_EF_base::modifier_pour_Cl(), Assembleur_P_VDF_Q4::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), norm_2D_vit1_k(), norm_2D_vit2_k(), norm_3D_vit1(), norm_3D_vit2(), Postraitement::postraiter_champs(), Format_Post_base::postraiter_debug_valeurs_un_instant(), remplir_marqueur_sommet_neumann(), remplir_sommets(), Zone_Cl_EF::remplir_type_elem_Cl(), EOS_Tools_VEF::secmembre_divU_Z(), Champ_Q1NC_impl::transforme_coord2D(), Champ_Q1NC_impl::transforme_coord3D(), Champ_Face_implementation::valeur_a_elem(), Champ_Face_implementation::valeur_a_elem_compo(), Champ_Face_implementation::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), and Assembleur_P_VEFPreP1B::verifier_dirichlet().
face_surfaces() [1/2]
virtual const DoubleVect & Zone_VF::face_surfaces () const inline virtual
Definition at line 47 of file Zone_VF.h.
  {
    return face_surfaces_;
  }
References face_surfaces_.
Referenced by Champ_Face_PolyMAC::affecter_(), Champ_Face_PolyMAC_P0::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Op_Div_PolyMAC::ajouter(), Op_Div_PolyMAC_P0::ajouter(), Perte_Charge_Singuliere_VEF_Face::ajouter(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Div_PolyMAC::ajouter_blocs(), Op_Grad_PolyMAC_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Masse_PolyMAC_Elem::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Assembleur_P_PolyMAC::assembler_continuite(), Assembleur_P_PolyMAC_P0::assembler_mat(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Evaluateur_VDF::associer_zones(), Champ_front_contact_VEF::calcul_grads_locaux(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Perte_Charge_Singuliere::calculate_Q(), Zone_EF_axi::calculer_Bij_gen(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_EF_Stab_PolyMAC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Zone_EF::calculer_h_carre(), Zone_Poly_base::calculer_h_carre(), Zone_VEF::calculer_h_carre(), Champ_front_xyz_debit::calculer_normales_et_integrale(), Op_Conv_VDF_base::calculer_pour_post(), Echange_contact_Correlation_VDF::calculer_Q(), Discretisation_tools::cells_to_faces(), Champ_front_calc_interne::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Sortie_libre_Gradient_Pression_impose::completer(), Op_Dift_VEF_Face::contribue_au_second_membre(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Op_Div_PolyMAC_P0::contribuer_a_avec(), Masse_PolyMAC_Face::corriger_solution(), Zone_Poly_base::detecter_faces_non_planes(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Zone_Poly_base::dist_face_elem0(), Zone_Poly_base::dist_face_elem1(), Zone_Poly_base::dist_norm(), Zone_Poly_base::dist_norm_bord(), Zone_VDF::face_normales(), Zone_PolyMAC_P0::fgrad(), Champ_Generique_Tparoi_VEF::get_champ(), Zone_Cl_VEFP1B::imposer_cond_lim(), Zone_Cl_PolyMAC::imposer_cond_lim(), Op_VEF_Face::impr(), T_It_VDF_Elem< _TYPE_ >::impr(), Op_Grad_VDF_Face::impr(), Zone_Poly_base::init_dist_paroi_globale(), Zone_Poly_base::init_equiv(), Champ_Face_PolyMAC_P0::init_ve2(), Champ_Face_PolyMAC::interp_ve(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Courant_maille_Champ_Face::mettre_a_jour(), Reynolds_maille_Champ_Face::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), normalized_boundaries_outward_vector(), orientation(), orientation_si_definie(), Zone_PolyMAC::orthocentrer(), Assembleur_P_VDF::remplir(), DP_Impose_PolyMAC_Face::remplir_num_faces(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), surface(), Echange_contact_Correlation_VDF::trier_coord(), grad_Champ_Face_PolyMAC_P0::update_ge(), Champ_Face_PolyMAC_P0::update_ve(), Champ_Face_PolyMAC_P0::v_norm(), and Champ_Face_PolyMAC::valeur_aux_faces().
face_surfaces() [2/2]
virtual double Zone_VF::face_surfaces (int i) const inline virtual
Definition at line 51 of file Zone_VF.h.
  {
    return face_surfaces_(i);
  };
References face_surfaces_.
face_virt_pe_num()
const IntTab & Zone_VF::face_virt_pe_num () const
Definition at line 448 of file Zone_VF.cpp.
{
// On verifie que le tableau a ete construit (si ca plante, c'est qu'on a
// oublie d'appeler construire_face_virt_pe_num()).
  assert(face_virt_pe_num_.dimension(1) == 2);
  return face_virt_pe_num_;
}
References TRUSTTab< _TYPE_ >::dimension(), and face_virt_pe_num_.
face_voisins() [1/3]
const IntTab & Zone_VF::face_voisins () const inline override virtual
cf au dessus.
Reimplemented from Zone_dis_base.
Definition at line 457 of file Zone_VF.h.
{
  return face_voisins_;
}
References face_voisins_.
face_voisins() [2/3]
IntTab & Zone_VF::face_voisins () inline override virtual
renvoie le tableaux des volumes des connectivites face elements
cf au dessus.
Reimplemented from Zone_dis_base.
Definition at line 450 of file Zone_VF.h.
{
  return face_voisins_;
}
References face_voisins_.
Referenced by construire_num_fac_loc(), Zone_VDF::creer_elements_fictifs(), Zone_Poly_base::detecter_faces_non_planes(), Zone_EF::discretiser(), Zone_Poly_base::discretiser(), discretiser(), Zone_VEF::discretiser(), Zone_Poly_base::dist_norm(), Zone_Poly_base::dist_norm_bord(), face_voisins_reel_fictif(), Zone_PolyMAC_P0::fgrad(), info_elem_som(), Zone_Poly_base::init_dist_paroi_globale(), Zone_Poly_base::init_equiv(), Zone_PolyMAC_P0::init_stencils(), Zone_PolyMAC::M2(), Zone_VDF::modifier_pour_Cl(), normalized_boundaries_outward_vector(), Zone_EF::oriente_normale(), Zone_Poly_base::oriente_normale(), Zone_VEF::oriente_normale(), and Zone_PolyMAC::W2().
face_voisins() [3/3]
int Zone_VF::face_voisins (int num_face, int i) const inline
renvoie l'element voisin de numface dans la direction i.
i=0 : dans le sens oppose de l'axe orthogonal a la face numface.
i=1 : dans le sens de l'axe orthogonal a la face numface.
exemple :
| 0 | 1 |
numface
renvoie -1 si l'element n'existe pas (au bord).
Definition at line 442 of file Zone_VF.h.
{
  return face_voisins_(num_face,i);
}
References face_voisins_.
Referenced by Champ_Face::affecter_(), Champ_Fonc_Face::affecter_(), Op_Dift_Stab_VEF_Face::aij_extradiag(), Op_Rot_VEFP1B::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Div_PolyMAC_P0::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Div_PolyMAC::ajouter_blocs(), Op_Grad_PolyMAC_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Masse_PolyMAC_Elem::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Sonde::ajouter_bords(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Masse_PolyMAC_Face::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Assembleur_P_VDF_Q4::assembler(), Assembleur_P_PolyMAC_P0::assembler_mat(), assemblerP0P1(), assemblerP0Pa(), assemblerP1P1(), assemblerP1Pa(), assemblerPaPa(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Op_Grad_VDF_Face_base::associer(), Evaluateur_VDF::associer_zones(), Champ_front_contact_VEF::calcul_coeff_amort(), Op_Dift_standard_VEF_Face::calcul_divergence(), Champ_Face::calcul_duidxj(), Champ_P1NC::calcul_duidxj_paroi(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_h_conv(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Perte_Charge_Singuliere::calculate_Q(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Dift_Stab_VEF_Face::calculer_coefficients(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Op_Conv_EF_VEF_P1NC_Stab::calculer_data_pour_dirichlet(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Champ_Face::calculer_dscald_centre_element(), Op_Conv_EF_Stab_PolyMAC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_EF_VEF_P1NC_Stab::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), EDO_Pression_th_VDF::calculer_grad(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), calculer_gradientP1NC(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Op_Dift_Stab_VEF_Face::calculer_gradients(), calculer_h_local(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_h_solide(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Op_Conv_VDF_base::calculer_pour_post(), Echange_contact_Correlation_VDF::calculer_Q(), Echange_contact_Correlation_VEF::calculer_Q(), EOS_Tools_VDF::calculer_rho_face_np1(), Champ_Face::calculer_rotationnel_ordre2_centre_element(), Traitement_particulier_NS_Brech_VEF::calculer_terme_destruction_K(), Traitement_particulier_NS_Brech_VEF::calculer_terme_production_K(), Echange_contact_VDF::calculer_Teta_paroi(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Champ_Face_get_val_imp_face_bord_sym(), Op_Diff_VEF_Face_Penalise::coefficient_penalisation(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), Eval_Puiss_Th_QC_VEF_Face::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Echange_interne_global_impose::completer(), Sortie_libre_Gradient_Pression_impose::completer(), Echange_contact_Correlation_VEF::completer(), Eval_Puiss_Th_VEF_Face::completer(), Eval_Source_C_VEF_Face::completer(), Evaluateur_Source_VEF_Face::completer(), T_It_VDF_Elem< _TYPE_ >::completer_(), Champ_Face::compo_normale_sortante(), Champ_front_contact_VEF::connectivity_failed(), Assembleur_P_VDF::construire(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec(), Op_Div_PolyMAC_P0::contribuer_a_avec(), Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), contribuer_matrice_NeumannP0P1(), contribuer_matrice_NeumannP0Pa(), contribuer_matrice_NeumannP1P1(), contribuer_matrice_NeumannP1Pa(), contribuer_matrice_NeumannPaPa(), contribuer_matrice_SymetrieP1P1(), contribuer_matrice_SymetrieP1Pa(), contribuer_matrice_SymetriePaPa(), contribuer_matriceP0P1(), contribuer_matriceP0Pa(), contribuer_matriceP1P1(), contribuer_matriceP1Pa(), contribuer_matricePaPa(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Div_VEFP1B_Elem::degres_liberte(), Eval_Quick_VDF_Face_Axi::dim_face(), Op_EF_base::dimensionner(), Op_VDF_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Op_Div_PolyMAC_P0::dimensionner(), Op_VDF_Elem::dimensionner_bloc_vitesse(), Op_Grad_VDF_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Div_PolyMAC::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::dimensionner_blocs(), Travail_pression_PolyMAC::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Sous_zone_VF::discretiser(), EOS_Tools_VDF::divu_discvit(), EOS_Tools_VEF::divu_discvit(), Op_Diff_VEF_Face_Penalise::element_commun(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Extraire_surface::extraire_surface(), Eval_Quick_VDF_Face_Axi::face_amont_conj(), face_bord_amont2(), face_vois(), Champ_P1NC_implementation::filtrer_L2(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_refChamp::get_ref_connectivity(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Champ_Q1NC::gradient(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Op_Grad_VEF_P1B_Face::impr(), Op_Grad_EF::impr(), Champ_Elem_PolyMAC::init_auxiliary_variables(), Champ_Face_PolyMAC_P0::init_ve2(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), Echange_contact_VDF::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Champ_front_recyclage::initialiser(), Champ_front_tangentiel_VEF::initialiser(), Champ_Face_PolyMAC::interp_ve(), Diametre_hyd_champ::interpreter(), Porosites::interpreter(), Porosites_champ::interpreter(), Extraire_domaine::interpreter_(), Op_Diff_VEFP1NCP1B_Face::isInStencil(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Eval_Darcy_VDF_Face::mettre_a_jour(), Eval_Darcy_VEF_Face::mettre_a_jour(), Chimie::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Sonde::mettre_a_jour_bords(), Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite(), Convection_Diffusion_Temperature::mise_en_place_zone_fantome(), modif_matrice_pour_periodique_apres_contribuer(), modif_matrice_pour_periodique_avant_contribuer(), T_It_VDF_Elem< _TYPE_ >::modifier_flux(), Assembleur_P_VDF_Q4::modifier_secmem(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VDF::modifier_secmem_pression_imposee(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), Terme_Source_Canal_RANS_LES_VDF_Face::norme_vit(), Echange_contact_Correlation_VEF::pdt_scal(), Convection_Diffusion_Temperature::penalisation_L2(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Assembleur_P_VEF::remplir(), Assembleur_P_VDF::remplir(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_Face_implementation::remplir_coord_noeuds_et_polys(), Champ_P1NC_implementation::remplir_coord_noeuds_et_polys(), Champ_Q1NC_impl::remplir_coord_noeuds_et_polys(), Champ_front_contact_VEF::remplir_elems_voisin_bord(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Zone_Cl_VEF::remplir_type_elem_Cl(), Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), Op_Diff_VEFP1NCP1B_Face::test(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Champ_Face_PolyMAC::trace(), Champ_Face_PolyMAC_P0::trace(), Champ_P1iP1B_implementation::trace(), Champ_Face_implementation::trace(), Champ_Elem_PolyMAC::trace(), Convection_Diffusion_Temperature::transport_ibc(), grad_Champ_Face_PolyMAC_P0::update_ge(), Echange_interne_impose::update_inv_lambda(), update_matrice_NeumannP0P1(), update_matrice_NeumannP0Pa(), update_matrice_NeumannP1P1(), update_matrice_NeumannP1Pa(), update_matrice_NeumannPaPa(), update_matrice_SymetrieP1P1(), update_matrice_SymetrieP1Pa(), update_matrice_SymetriePaPa(), update_matriceP0P1(), update_matriceP0Pa(), update_matriceP1P1(), update_matriceP1Pa(), update_matricePaPa(), Champ_Face_PolyMAC_P0::update_ve(), updateP0P1(), updateP0Pa(), updateP1P1(), updateP1Pa(), updatePaPa(), valeur(), Champ_Fonc_P0_base::valeur_au_bord(), Champ_P1_isoP1Bulle::valeur_au_bord(), Champ_P0_VDF::valeur_au_bord(), Champ_P0_VEF::valeur_au_bord(), Champ_Inc_base::valeur_aux_bords(), Champ_Elem_PolyMAC::valeur_aux_faces(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), Op_Diff_VEF_base::viscA(), Op_Diff_VEF_Face_Penalise::voisinage(), and Debog_Pb::write_geometry_data().
face_voisins_fictifs()
const IntTab & Zone_VF::face_voisins_fictifs () const inline
Definition at line 462 of file Zone_VF.h.
{
  return face_voisins_fictifs_;
}
References face_voisins_fictifs_.
face_voisins_reel_fictif()
void Zone_VF::face_voisins_reel_fictif (int face, int & el0, int & elf) const inline
renvoie dans el0 le numero de l'elt a l'interieur
renvoie dans elf le numero de l'elt fictif (-1 si il n'existe pas)
Definition at line 471 of file Zone_VF.h.
{
  assert(face<premiere_face_int());
  el0 = face_voisins(face,0);
  elf = face_voisins(face,1);
  if (el0==-1)
    {
      el0=elf;
      elf=face_voisins_fictifs_(face,0);
    }
  if (elf==-1) elf=face_voisins_fictifs_(face,1);
}
References face_voisins(), face_voisins_fictifs_, and premiere_face_int().
faces_doubles() [1/2]
ArrOfInt & Zone_VF::faces_doubles () inline
renvoie 1 pour les faces appartenant a un bord perio ou un item commun, 0 par defaut
Definition at line 579 of file Zone_VF.h.
{
  return faces_doubles_;
}
References faces_doubles_.
Referenced by Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Traitement_particulier_NS_EC::calculer_Ec(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), T_It_Sou_VDF_Face< _TYPE_ >::faces_doubles(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), and Traitement_particulier_NS_canal_VEF::remplir_Y().
faces_doubles() [2/2]
const ArrOfInt & Zone_VF::faces_doubles () const inline
cf au dessus
Definition at line 586 of file Zone_VF.h.
{
  return faces_doubles_;
}
References faces_doubles_.
fbord()
int Zone_VF::fbord (int f) const inline
Definition at line 178 of file Zone_VF.h.
  {
    return f < premiere_face_int() ? f : f < nb_faces() ? -1 : ind_faces_virt_bord()[f - nb_faces()];
  }
References ind_faces_virt_bord(), nb_faces(), and premiere_face_int().
Referenced by Zone_PolyMAC_P0::fgrad(), Zone_PolyMAC_P0::init_stencils(), Champ_front_debit_massique::update_coeff(), and Champ_Inc_base::valeur_aux_bords().
front_VF()
const Front_VF & Zone_VF::front_VF (int i) const inline
renvoie la ieme frontiere_discrete.
Definition at line 628 of file Zone_VF.h.
{
  return les_bords_[i];
}
References les_bords_.
Referenced by Champ_front_contact_VEF::calcul_grads_locaux(), Traitement_particulier_NS_EC::calculer_Ec(), calculer_h_local(), construit_connectivite_sommet(), Zone_Poly_base::dist_norm_bord(), Zone_VDF::dist_norm_bord(), Zone_Cl_VEF::initialiser(), PlaqThVDF::mettre_a_jour(), Zone_Cl_EF::remplir_type_elem_Cl(), Zone_Cl_VEF::remplir_type_elem_Cl(), and Zone_Cl_VEF::remplir_volumes_entrelaces_Cl().
frontiere_dis() [1/2]
const Frontiere_dis_base & Zone_VF::frontiere_dis (int i) const inline override virtual
renvoie la ieme frontiere_discrete.
Implements Zone_dis_base.
Definition at line 614 of file Zone_VF.h.
{
  return les_bords_[i];
}
References les_bords_.
frontiere_dis() [2/2]
Frontiere_dis_base & Zone_VF::frontiere_dis (int i) inline override virtual
renvoie la ieme frontiere_discrete.
Implements Zone_dis_base.
Definition at line 621 of file Zone_VF.h.
{
  return les_bords_[i];
}
References les_bords_.
Referenced by Champ_front_contact_VEF::calcul_coeff_amort(), Extraire_surface::extraire_surface(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_front_contact_VEF::remplir_elems_voisin_bord(), and Champ_front_contact_VEF::test_faces_coin().
get_info()
const Type_info * Zone_VF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_dis_base.
Reimplemented in Zone_VF_inst, Zone_VEF_PreP1b, Zone_PolyMAC, Zone_PolyMAC_P0, Zone_VDF, and Zone_VEF.
Definition at line 30 of file Zone_VF.cpp.
get_num_fac_loc() [1/2]
const IntTab & Zone_VF::get_num_fac_loc () const inline
Definition at line 169 of file Zone_VF.h.
  {
    return num_fac_loc_;
  };
References num_fac_loc_.
Referenced by Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Op_Dift_Stab_VEF_Face::calculer_gradients(), Op_Grad_VEF_P1B_Face::impr(), Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite(), and Champ_P1_isoP1Bulle::valeur_au_bord().
get_num_fac_loc() [2/2]
int Zone_VF::get_num_fac_loc (int face, int voisin) const inline
Definition at line 250 of file Zone_VF.h.
{
  assert(voisin==0 || voisin==1);
  return num_fac_loc_(face,voisin);
}
References num_fac_loc_.
ind_faces_virt_bord()
const ArrOfInt & Zone_VF::ind_faces_virt_bord () const inline
Definition at line 750 of file Zone_VF.h.
{
  return zone().ind_faces_virt_bord();
}
References Zone::ind_faces_virt_bord(), and Zone_dis_base::zone().
Referenced by est_une_face_virt_bord(), fbord(), Eval_Dift_VDF_const_Face::tau_tan_impl(), and Eval_Dift_VDF_var_Face::tau_tan_impl().
info()
const Type_info * Zone_VF::info () static
Definition at line 30 of file Zone_VF.cpp.
info_elem_som()
void Zone_VF::info_elem_som ()
Definition at line 592 of file Zone_VF.cpp.
{
  const int nbelem = zone().les_elems().get_md_vector().valeur().nb_items_seq_tot();
  const int nbsom = zone().domaine().les_sommets().get_md_vector().valeur().nb_items_seq_tot();
  const int nbfaces = face_voisins().get_md_vector().valeur().nb_items_seq_tot();
  Cerr<<"Calculation of elements and nodes on " << zone().domaine().le_nom() << " :" << finl;
  Cerr<<"Total number of elements = "<<nbelem<<finl;
  Cerr<<"Total number of nodes = "<<nbsom<<finl;
  Cerr<<"Total number of faces = "<<nbfaces<<finl;
  Raccords& raccords=zone().faces_raccord();
  for (int i=0; i<raccords.nb_raccords(); i++)
    {
      int nb_boundary_faces = mp_sum(ref_cast(Frontiere,raccords(i).valeur()).nb_faces());
      Cerr<< nb_boundary_faces << " of them on boundary "<<raccords(i).le_nom()<<finl;
    }
  Bords& bords=zone().faces_bord();
  for (int i=0; i<bords.nb_bords(); i++)
    {
      int nb_boundary_faces = mp_sum(ref_cast(Frontiere,bords(i)).nb_faces());
      Cerr<< nb_boundary_faces << " of them on boundary "<<bords(i).le_nom()<<finl;
    }
  Cerr<<"=============================================="<<finl;
}
References Cerr, Zone::domaine(), face_voisins(), Zone::faces_bord(), Zone::faces_raccord(), finl, TRUSTVect< _TYPE_ >::get_md_vector(), Objet_U::le_nom(), Domaine::le_nom(), Zone::les_elems(), Domaine::les_sommets(), Process::mp_sum(), Bords::nb_bords(), nb_faces(), MD_Vector_base::nb_items_seq_tot(), Raccords::nb_raccords(), ref_cast, MD_Vector::valeur(), valeur(), and Zone_dis_base::zone().
Referenced by discretiser().
infobord()
void Zone_VF::infobord ()
Definition at line 554 of file Zone_VF.cpp.
{
  Cerr << "==============================================" << finl;
  Cerr << "The boundary areas of the domain " << zone().domaine().le_nom() << " are:" << finl;
  DoubleVect surfaces;
// Raccords
  Raccords& raccords=zone().faces_raccord();
  for (int i=0; i<raccords.nb_raccords(); i++)
    {
      Faces& faces=raccords(i).valeur().faces();
      faces.associer_zone(zone());
      faces.calculer_surfaces(surfaces);
      double s=0;
      for (int j=0; j<faces.nb_faces(); j++)
        s=s+surfaces(j);
      s=mp_sum(s);
      raccords(i).valeur().set_aire(s);
      Cerr<<"Area of "<<raccords(i).le_nom()<<"  \t= "<<s<<finl;
    }
// Bords
  Bords& bords=zone().faces_bord();
  for (int i=0; i<bords.nb_bords(); i++)
    {
      Faces& faces=bords(i).faces();
      faces.associer_zone(zone());
      faces.calculer_surfaces(surfaces);
      double s=0;
      for (int j=0; j<faces.nb_faces(); j++)
        s=s+surfaces(j);
      s=mp_sum(s);
      bords(i).set_aire(s);
      Cerr<<"Area of "<<bords(i).le_nom()<<"  \t= "<<s<<finl;
    }
  Cerr << "==============================================" << finl;
}
References Faces::associer_zone(), Faces::calculer_surfaces(), Cerr, Zone::domaine(), Zone::faces_bord(), Zone::faces_raccord(), finl, Objet_U::le_nom(), Domaine::le_nom(), Process::mp_sum(), Bords::nb_bords(), Faces::nb_faces(), Raccords::nb_raccords(), List_Raccord::valeur(), and Zone_dis_base::zone().
Referenced by discretiser().
inverse_volumes() [1/3]
DoubleVect & Zone_VF::inverse_volumes () inline
Tableau pour optimiser le code.
Definition at line 418 of file Zone_VF.h.
{
  return inverse_volumes_;
}
References inverse_volumes_.
inverse_volumes() [2/3]
const DoubleVect & Zone_VF::inverse_volumes () const inline
Tableau pour optimiser le code.
Definition at line 429 of file Zone_VF.h.
{
  return inverse_volumes_;
}
References inverse_volumes_.
inverse_volumes() [3/3]
double Zone_VF::inverse_volumes (int i) const inline
Definition at line 407 of file Zone_VF.h.
{
  return inverse_volumes_[i];
}
References inverse_volumes_.
Referenced by calculer_gradientP1NC(), Domaine_dis::discretiser(), and Op_Diff_VEF_base::viscA().
joint() [1/2]
Joint & Zone_VF::joint (int i) inline
renvoie le ieme joint.
Definition at line 396 of file Zone_VF.h.
{
  return zone().joint(i);
}
References Zone::joint(), and Zone_dis_base::zone().
joint() [2/2]
const Joint & Zone_VF::joint (int i) const inline
renvoie le ieme joint.
Definition at line 389 of file Zone_VF.h.
{
  return zone().joint(i);
}
References Zone::joint(), and Zone_dis_base::zone().
Referenced by Zone_EF::creer_faces_virtuelles_non_std(), Zone_VEF::creer_faces_virtuelles_non_std(), Extraire_surface::extraire_surface(), Extraire_plan::interpreter_(), and marquer_faces_double_contrib().
marquer_faces_double_contrib()
void Zone_VF::marquer_faces_double_contrib (const Conds_lim & conds_lim)
Definition at line 502 of file Zone_VF.cpp.
{
  Journal() << " Zone_VF::marquer_faces_double_contrib" << finl;
  faces_doubles_.resize_array(nb_faces());
// marquage des faces periodiques
//
  int nb_cond_lim=conds_lim.size();
  for (int i=0; i<nb_cond_lim; i++)
    {
      const Cond_lim_base& cl=conds_lim[i].valeur();
      if (sub_type(Periodique, cl))
        {
          const Periodique& la_cl_period = ref_cast(Periodique,cl);
          const Front_VF& frontieredis = ref_cast(Front_VF,la_cl_period.frontiere_dis());
          int ndeb = frontieredis.num_premiere_face();
          int nfin = ndeb + frontieredis.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              faces_doubles_[face]=1;
            }
        }
    }
// marquage des faces items communs
//
  int nbjoints=nb_joints();
  for(int njoint=0; njoint<nbjoints; njoint++)
    {
      const Joint& joint_temp = joint(njoint);
      const IntTab& indices_faces_joint = joint_temp.joint_item(Joint::FACE).renum_items_communs();
      const int nbfaces = indices_faces_joint.dimension(0);
      for (int j = 0; j < nbfaces; j++)
        {
// Pour acceder au face de joint, il existe desormais un tableau dedie renum_items_communs()
// car l'ancienne facon d'acceder a ces faces etait de passer par
// joint.num_premiere_face() et joint.nb_faces() ce qui n'est plus valable !
// En effet, la numerotation des faces de joint n'est plus continue desormais !
// joint.num_premiere_face() retourne -1 desormais pour detecter les anciens codages.
          int face_de_joint = indices_faces_joint(j, 1);
          faces_doubles_[face_de_joint] = 1;
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Joint::FACE, faces_doubles_, finl, Cond_lim_base::frontiere_dis(), joint(), Joint::joint_item(), Process::Journal(), Front_VF::nb_faces(), nb_faces(), nb_joints(), Front_VF::num_premiere_face(), ref_cast, Joint_Items::renum_items_communs(), TRUSTArray< _TYPE_ >::resize_array(), vect_impl::size(), and sub_type.
Referenced by Zone_EF::modifier_pour_Cl(), modifier_pour_Cl(), Zone_VEF::modifier_pour_Cl(), and Zone_VDF::modifier_pour_Cl().
md_vector_aretes()
virtual const MD_Vector & Zone_VF::md_vector_aretes () const inline virtual
Definition at line 192 of file Zone_VF.h.
{ return md_vector_aretes_; }
References md_vector_aretes_.
Referenced by Zone_VEF_PreP1b::construire_ok_arete(), creer_tableau_aretes(), Zone_PolyMAC::discretiser(), Zone_VEF_PreP1b::discretiser_suite(), Zone_VEF_PreP1b::lecture_ok_arete(), Debog_Pb::read_geometry_data(), and Debog_Pb::write_geometry_data().
md_vector_faces()
virtual const MD_Vector & Zone_VF::md_vector_faces () const inline virtual
Definition at line 190 of file Zone_VF.h.
{ return md_vector_faces_; }
References md_vector_faces_.
Referenced by Zone_VEF::calculer_volumes_entrelaces(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Zone_PolyMAC::discretiser(), Zone_PolyMAC_P0::discretiser(), Champ_Face_PolyMAC::fixer_nb_valeurs_nodales(), Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales(), Champ_Fonc_Face_PolyMAC::fixer_nb_valeurs_nodales(), Champ_Q1NC::fixer_nb_valeurs_nodales(), Champ_P1NC::fixer_nb_valeurs_nodales(), Champ_Face::fixer_nb_valeurs_nodales(), Champ_Fonc_Face::fixer_nb_valeurs_nodales(), Champ_Fonc_P1NC::fixer_nb_valeurs_nodales(), Champ_Fonc_Q1NC::fixer_nb_valeurs_nodales(), multiplier_diviser_rho(), Debog_Pb::read_geometry_data(), Champ_Face_PolyMAC::reprendre(), and Debog_Pb::write_geometry_data().
md_vector_faces_bord()
virtual const MD_Vector & Zone_VF::md_vector_faces_bord () const inline virtual
Definition at line 189 of file Zone_VF.h.
{ return md_vector_faces_front_; }
References md_vector_faces_front_.
Referenced by creer_tableau_faces_bord(), multiplier_diviser_rho(), nb_faces_bord_tot(), and xv_bord().
modifier_pour_Cl()
void Zone_VF::modifier_pour_Cl (const Conds_lim & conds_lim) override virtual
Implements Zone_dis_base.
Reimplemented in Zone_VEF_PreP1b, Zone_VEF, and Zone_VDF.
Definition at line 267 of file Zone_VF.cpp.
{
  Cerr << " Zone_VF::modifier_pour_Cl" << finl;
  int nb_cond_lim=conds_lim.size();
  int i=0;
  for (; i<nb_cond_lim; i++)
    {
// for(cl ...
      const Cond_lim_base& cl=conds_lim[i].valeur();
      if (sub_type(Periodique, cl))
        {
// if (perio ...
// Modifications du tableau face_voisins
// Une face de type periodicite doit avoir les memes voisins que
// sa face associee
// face_voisins(face,j) = face_voisins(face_associee(face),j)  j=1,2
//
          const Periodique& la_cl_period = ref_cast(Periodique,cl);
          const Front_VF& frontieredis = ref_cast(Front_VF,la_cl_period.frontiere_dis());
          int nb_face_bord = frontieredis.nb_faces();
          int ndeb =0;
          int nfin = frontieredis.nb_faces_tot();
#ifndef NDEBUG
          int num_premiere_face = frontieredis.num_premiere_face();
          int num_derniere_face = num_premiere_face+nfin;
#endif
          int face;
          for (int ind_face=ndeb; ind_face<nfin; ind_face++)
            {
              face = frontieredis.num_face(ind_face);
              int faassociee = la_cl_period.face_associee(ind_face);
              faassociee = frontieredis.num_face(faassociee);
              if (ind_face<nb_face_bord)
                {
                  assert(faassociee>=num_premiere_face);
                  assert(faassociee<num_derniere_face);
                }
              if (face_voisins_(face,0) == -1)
                face_voisins_(face,0) = face_voisins_(faassociee,0);
              else if (face_voisins_(face,1) == -1)
                face_voisins_(face,1) = face_voisins_(faassociee,1);
            }
        }
    }
// PQ : 10/10/05 : les faces periodiques etant a double contribution
// l'appel a marquer_faces_double_contrib s'effectue dans cette methode
// afin de pouvoir beneficier de conds_lim.
  marquer_faces_double_contrib(conds_lim);
// Construction du tableau num_fac_loc_
  construire_num_fac_loc();
}
References Cerr, construire_num_fac_loc(), Periodique::face_associee(), face_voisins_, finl, Cond_lim_base::frontiere_dis(), marquer_faces_double_contrib(), Front_VF::nb_faces(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Front_VF::num_premiere_face(), ref_cast, vect_impl::size(), and sub_type.
Referenced by Zone_VDF::modifier_pour_Cl().
nb_faces()
int Zone_VF::nb_faces () const inline
renvoie le nombre global de faces.
Definition at line 503 of file Zone_VF.h.
{
  return face_sommets_.dimension(0);
}
References TRUSTTab< _TYPE_ >::dimension(), and face_sommets_.
Referenced by Champ_Face_PolyMAC::affecter_(), Champ_Face_PolyMAC_P0::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Face::affecter_(), Champ_Fonc_Face::affecter_(), Champ_P1NC::affecter_(), Op_Rot_VEFP1B::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Div_PolyMAC_P0::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face_Penalise::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Perte_Charge_VEF::ajouter(), Source_Generique_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Terme_Source_Decroissance_Radioactive_VEF_Face::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Div_PolyMAC::ajouter_blocs(), Op_Grad_PolyMAC_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_interne(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_interne_vitesse(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Source_Fluide_Dilatable_VDF_Proto::ajouter_impl(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), T_It_VDF_Elem< _TYPE_ >::ajouter_interne(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Masse_PolyMAC_Face::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Assembleur_P_VDF_Q4::assembler(), Assembleur_P_PolyMAC::assembler_continuite(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), EOS_Tools_VDF::associer_zones(), build_triofield(), grad_Champ_Face_PolyMAC_P0::calc_gradfve(), Op_Dift_standard_VEF_Face::calcul_divergence(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_som(), Traitement_particulier_NS_EC::calculer_Ec(), EDO_Pression_th_VEF::calculer_grad(), Zone_EF::calculer_h_carre(), Zone_Poly_base::calculer_h_carre(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Traitement_particulier_NS_Brech_VEF::calculer_terme_destruction_K(), Traitement_particulier_NS_Brech_VEF::calculer_terme_production_K(), Zone_EF::calculer_volumes_entrelaces(), Zone_VDF::calculer_volumes_entrelaces(), Zone_VEF::calculer_volumes_entrelaces(), Discretisation_tools::cells_to_faces(), Champ_Face_get_val_imp_face_bord(), Champ_Face_get_val_imp_face_bord_sym(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), Zone_Cl_VDF::completer(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), construire_face_virt_pe_num(), Op_Dift_VEF_Face::contribue_au_second_membre(), Perte_Charge_VEF::contribuer_a_avec(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec(), Terme_Source_Decroissance_Radioactive_VEF_Face::contribuer_a_avec(), Op_Div_PolyMAC_P0::contribuer_a_avec(), T_It_VDF_Elem< _TYPE_ >::contribuer_au_second_membre_interne(), VDF_discretisation::courant_maille(), Op_Div_VEFP1B_Elem::degres_liberte(), Zone_Poly_base::detecter_faces_non_planes(), Op_VDF_Elem::dimensionner(), Op_VEF_Face::dimensionner(), Op_Div_PolyMAC_P0::dimensionner(), Op_VDF_Elem::dimensionner_bloc_vitesse(), Masse_PolyMAC_Face::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_VDF_Face::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Div_PolyMAC::dimensionner_blocs(), Op_Grad_PolyMAC_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::dimensionner_blocs(), Force_Tchen_PolyMAC_P0::dimensionner_blocs(), Frottement_interfacial_PolyMAC_P0::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Assembleur_P_PolyMAC::dimensionner_continuite(), Zone_EF::discretiser(), Zone_Poly_base::discretiser(), Zone_VEF::discretiser(), PolyMAC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ_fonc_don(), VEF_discretisation::discretiser_champ_fonc_don(), VDF_discretisation::discretiser_champ_fonc_don(), EOS_Tools_VEF::divu_discvit(), est_une_face_virt_bord(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Extraire_surface::extraire_surface(), face_numero_bord(), fbord(), Champ_Face_PolyMAC::fixer_nb_valeurs_nodales(), Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales(), Champ_Fonc_Face_PolyMAC::fixer_nb_valeurs_nodales(), Zone_VDF::genere_aretes(), Champ_Q1NC::gradient(), Champ_P1NC_implementation::imprime_P1NC(), info_elem_som(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Terme_Source_Canal_RANS_LES_VEF_Face::init(), Champ_Elem_PolyMAC::init_auxiliary_variables(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), Zone_Poly_base::init_dist_paroi_globale(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Traitement_particulier_NS_Brech_VEF::lire(), marquer_faces_double_contrib(), EDO_Pression_th_VEF::masse_totale(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Courant_maille_Champ_Face::mettre_a_jour(), Reynolds_maille_Champ_Face::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VEF_Face::mettre_a_jour(), Zone_EF::modifier_pour_Cl(), Zone_VEF::modifier_pour_Cl(), Assembleur_P_VDF_Q4::modifier_secmem(), Terme_Source_Canal_RANS_LES_VDF_Face::moy_spat(), nb_faces_internes(), Zone_VEF::nb_faces_non_std(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_L2(), norme_L2(), Terme_Source_Canal_RANS_LES_VDF_Face::norme_vit(), Zone_PolyMAC::orthocentrer(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson(), Zone_VEF::premiere_face_std(), printOn(), Champ_Don_Face_lu::readOn(), Champ_P1NC_implementation::remplir_coord_noeuds(), Champ_Q1NC_impl::remplir_coord_noeuds(), Champ_Face_implementation::remplir_coord_noeuds_et_polys(), Champ_P1NC_implementation::remplir_coord_noeuds_et_polys(), Champ_Q1NC_impl::remplir_coord_noeuds_et_polys(), remplir_face_numero_bord(), Op_Conv_EF_VEF_P1NC_Stab::remplir_fluent(), Op_Conv_Muscl_New_VEF_Face::remplir_fluent(), Traitement_particulier_NS_canal_VEF::remplir_Y(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), VDF_discretisation::reynolds_maille(), EOS_Tools_VDF::secmembre_divU_Z(), Terme_Source_Canal_perio::source_convection_diffusion(), Eval_Dift_VDF_const_Face::tau_tan_impl(), Eval_Dift_VDF_var_Face::tau_tan_impl(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_Elem_PolyMAC::trace(), Champ_Face_PolyMAC::valeur_aux_faces(), and VEF_1D::vitesse().
nb_faces_bord()
int Zone_VF::nb_faces_bord () const inline
renvoie le nombre de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
Definition at line 531 of file Zone_VF.h.
{
  return zone().nb_faces_frontiere();
}
References Zone::nb_faces_frontiere(), and Zone_dis_base::zone().
Referenced by Op_Div_EF::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Div_PolyMAC_P0::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Penalise::ajouter(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_EF_base::associer(), Op_Diff_VEF_base::associer(), Zone_Cl_VDF::associer(), Assembleur_P_VDF::construire(), Zone_VDF::creer_elements_fictifs(), Zone_VDF::dist_norm_bord(), Zone_VDF::dist_norm_bord_axi(), Op_Grad_VEF_P1B_Face::impr(), Op_Grad_EF::impr(), Op_Grad_VDF_Face::impr(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Assembleur_P_VDF::liste_faces_periodiques(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), T_It_VDF_Elem< _TYPE_ >::modifier_flux(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Zone_Cl_VDF::nb_faces_bord(), nb_faces_internes(), and premiere_face_int().
nb_faces_bord_tot()
int Zone_VF::nb_faces_bord_tot () const inline
renvoie le nombre total de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
Definition at line 667 of file Zone_VF.cpp.
{
  return md_vector_faces_bord().valeur().get_nb_items_tot();
}
References MD_Vector_base::get_nb_items_tot(), md_vector_faces_bord(), and MD_Vector::valeur().
nb_faces_internes()
int Zone_VF::nb_faces_internes () const inline
une face est interne ssi elle separe deux elements.
renvoie le nombre de faces internes.
Definition at line 549 of file Zone_VF.h.
{
  return nb_faces()- nb_faces_bord();
}
References nb_faces(), and nb_faces_bord().
Referenced by Traitement_particulier_NS_EC::calculer_Ec(), Assembleur_P_VDF::construire(), and Assembleur_P_VDF::remplir().
nb_faces_tot()
int Zone_VF::nb_faces_tot () const inline
renvoie le nombre total de faces.
C'est-a-dire faces reelles + faces virtuelles
Definition at line 511 of file Zone_VF.h.
{
  return face_sommets_.dimension_tot(0);
}
References TRUSTTab< _TYPE_ >::dimension_tot(), and face_sommets_.
Referenced by Champ_Face_PolyMAC_P0::affecter_(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion_vectoriel(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Masse_PolyMAC_P0_Face::appliquer_impl(), Assembleur_P_PolyMAC::assembler_mat(), assemblerP0P1(), assemblerP0Pa(), assemblerP1P1(), assemblerP1Pa(), assemblerPaPa(), Eval_Darcy_VDF_Face::associer(), Eval_Darcy_VEF_Face::associer(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), grad_Champ_Face_PolyMAC_P0::calc_gradfve(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), calculer_gradientP1NC(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Dift_Stab_VEF_Face::calculer_min(), EOS_Tools_VDF::calculer_rho_face_np1(), Discretisation_tools::cells_to_faces(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Op_Conv_Muscl_New_VEF_Face::completer(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), construire_face_virt_pe_num(), construire_num_fac_loc(), construit_connectivite_sommet(), Masse_PolyMAC_Face::corriger_solution(), Op_Div_VEFP1B_Elem::degres_liberte(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Op_Div_PolyMAC_P0::dimensionner(), Op_VDF_Elem::dimensionner_bloc_vitesse(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_VDF_Face::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::dimensionner_blocs(), Force_Tchen_PolyMAC_P0::dimensionner_blocs(), Frottement_interfacial_PolyMAC_P0::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Assembleur_P_PolyMAC::dimensionner_continuite(), Zone_EF::discretiser(), Sous_zone_VF::discretiser(), Zone_Poly_base::discretiser(), Zone_VEF::discretiser(), EOS_Tools_VDF::divu_discvit(), Source_WC_Chaleur_VEF::elem_to_face(), Source_WC_Chaleur_VDF::face_to_elem(), Discretisation_tools::faces_to_cells(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), Op_Grad_VDF_Face::impr(), Zone_Poly_base::init_equiv(), Champ_Elem_PolyMAC::init_fcl(), Champ_Face_PolyMAC::init_fcl(), Zone_PolyMAC_P0::init_stencils(), Champ_Face_PolyMAC_P0::init_ve2(), Diametre_hyd_champ::interpreter(), Porosites_champ::interpreter(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Champ_Fonc_Elem_PolyMAC_P0_TC::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_2D(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_3D(), Eval_Darcy_VDF_Face::mettre_a_jour(), Eval_Darcy_VEF_Face::mettre_a_jour(), Zone_PolyMAC::orthocentrer(), Assembleur_P_VEF::remplir(), Champ_Face_implementation::remplir_coord_noeuds(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Champ_Face_PolyMAC::reprendre(), EOS_Tools_VEF::secmembre_divU_Z(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), Champ_Face_PolyMAC_P0::trace(), grad_Champ_Face_PolyMAC_P0::update_ge(), Champ_Face_PolyMAC_P0::update_ve(), Champ_Face_PolyMAC_P0::update_ve2(), updateP0P1(), updateP0Pa(), updateP1P1(), updateP1Pa(), updatePaPa(), Champ_Face_PolyMAC_P0::v_norm(), Champ_Face_PolyMAC_P0::valeur_aux_elems(), Champ_Face_PolyMAC_P0::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_sommets(), and Champ_P1NC_implementation::valeur_aux_sommets_compo().
nb_frontiere_dis()
int Zone_VF::nb_frontiere_dis () const inline
Definition at line 139 of file Zone_VF.h.
  {
    return les_bords_.size();
  };
References les_bords_, and vect_impl::size().
Referenced by Champ_Generique_Extraction::completer().
nb_joints()
int Zone_VF::nb_joints () const inline
renvoie le nombre de joints
Definition at line 488 of file Zone_VF.h.
{
  return zone().nb_joints();
}
References Zone::nb_joints(), and Zone_dis_base::zone().
Referenced by Zone_EF::creer_faces_virtuelles_non_std(), Zone_VEF::creer_faces_virtuelles_non_std(), Extraire_surface::extraire_surface(), Extraire_plan::interpreter_(), and marquer_faces_double_contrib().
nb_som_face()
int Zone_VF::nb_som_face () const inline
renvoie le nombre de sommets par face.
Rque : on a suppose que toutes les faces avait
le meme nombre de sommet ce qui exclue des elements
comme le prisme.
Definition at line 522 of file Zone_VF.h.
{
  return face_sommets_.dimension(1);
}
References TRUSTTab< _TYPE_ >::dimension(), and face_sommets_.
Referenced by Op_Div_EF::ajouter(), ajouter_bord(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Zone_EF::calculer_Bij(), Zone_EF::calculer_Bij_gen(), Zone_EF_axi::calculer_Bij_gen(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Champ_Generique_Extraction::completer(), Op_EF_base::dimensionner(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Zone_Poly_base::init_dist_paroi_globale(), norm_2D_vit1_k(), norm_2D_vit2_k(), norm_3D_vit1(), norm_3D_vit2(), remplir_marqueur_sommet_neumann(), EOS_Tools_VEF::secmembre_divU_Z(), Op_Diff_VEF_Face_Penalise::signe(), Champ_P1NC_implementation::valeur_aux_sommets(), and Champ_P1NC_implementation::valeur_aux_sommets_compo().
normalized_boundaries_outward_vector()
DoubleTab Zone_VF::normalized_boundaries_outward_vector (int global_face_number, double scale_factor) const
Compute the normalized boundary outward vector associated to the face global_face_number
and eventually scaled by scale_factor.
Definition at line 459 of file Zone_VF.cpp.
{
  const IntTab& neighbor_faces = face_voisins();
  DoubleTab normal_vector(dimension); //result
  for (int d = 0; d < dimension; d++)
    normal_vector(d) = face_normales(global_face_number, d) / face_surfaces(global_face_number);
// now we have a normalized normal vector
// but it remains to orient it correctly (outwards)
// for this we build a vector that links middle of the face to the center of the element
// and then we do the inner product between this new vector and normal vector
// So, if the result is positive, we change the sign of normal vector
// else we do nothing
  int neighbor_elem=neighbor_faces(global_face_number,0);
  if( neighbor_elem == -1 )
    neighbor_elem = neighbor_faces(global_face_number,1);
  DoubleTab vector_face_elem(dimension);
  double inner_product=0;
  for(int i=0; i<dimension; i++)
    {
// ith component of the vector
      double vec_face_elem = xp(neighbor_elem,i)-xv(global_face_number,i);
      inner_product+=vec_face_elem*normal_vector(i);
    }
  if( inner_product > 0 )
    {
      for(int i=0; i<dimension; i++)
        {
          normal_vector(i)*=-1;
        }
    }
// now the normal vector is well oriented (outwards)
// we can multiply it by a given scale factor
  for(int i=0; i<dimension; i++)
    {
      normal_vector(i)*=scale_factor;
    }
  return normal_vector;
}
References Objet_U::dimension, face_normales(), face_surfaces(), face_voisins(), xp(), and xv().
Referenced by Champ_front_xyz_debit::calculer_normales_et_integrale(), and Boundary_field_inward::mettre_a_jour().
numero_face_local()
int Zone_VF::numero_face_local (int face, int elem) const
Definition at line 366 of file Zone_VF.cpp.
{
// int nfe=zone().nb_faces_elem();
// GF pour le cas ou on a plusieurs types de faces....
// nb_faces_elem() renvoit le nbre de sommet par face du premier type de faces
  int nfe=elem_faces_.dimension(1);
  for(int face_loc=0; face_loc<nfe; face_loc++)
    if(elem_faces_(elem, face_loc)==face)
      return face_loc;
  return -1;
}
References TRUSTTab< _TYPE_ >::dimension(), and elem_faces_.
Referenced by construire_num_fac_loc().
numero_sommet_local()
int Zone_VF::numero_sommet_local (int som, int elem) const inline
Definition at line 256 of file Zone_VF.h.
{
  int nse=zone().nb_som_elem();
  const IntTab& les_elems=zone().les_elems();
  for(int som_loc=0; som_loc<nse; som_loc++)
    {
      if(les_elems(elem, som_loc)==som)
        return som_loc;
    }
  return -1;
}
References Zone::les_elems(), Zone::nb_som_elem(), and Zone_dis_base::zone().
Referenced by Op_Curl_VEFP1B::ajouter().
orientation() [1/2]
const IntVect & Zone_VF::orientation () const inline virtual
Reimplemented in Zone_VDF.
Definition at line 639 of file Zone_VF.h.
{
  Cerr<<"Try using orientation(num_face) instead of orientation() if the mesh is axis oriented."<< finl;
  exit();
  throw;
  return orientation();
}
References Cerr, Process::exit(), finl, and orientation().
Referenced by Evaluateur_Source_PolyMAC_Face::completer(), and orientation().
orientation() [2/2]
int Zone_VF::orientation (int num_face) const inline virtual
Reimplemented in Zone_VDF.
Definition at line 657 of file Zone_VF.h.
{
  for (int dir=0; dir<dimension; dir++)
    {
      if (est_egal(std::fabs(face_normales(num_face, dir)), face_surfaces(num_face)))
        return dir;
    }
  Cerr<<"Your mesh is not axis oriented."<<finl;
  Cerr<<"Try recoding using face_normales(). Example for g(face)=gravite[orientation[face]];" << finl;
  Cerr<<"Compute something like: g(face)=Sum(i=0;i<gravite.size();i++) of gravite[i]*face_normales(face,i)/surface(face);" << finl;
  exit();
  return -1;
}
References Cerr, Objet_U::dimension, est_egal(), Process::exit(), face_normales(), face_surfaces(), and finl.
orientation_si_definie()
int Zone_VF::orientation_si_definie (int num_face) const inline virtual
Definition at line 647 of file Zone_VF.h.
{
  for (int dir=0; dir<dimension; dir++)
    {
      if (est_egal(std::fabs(face_normales(num_face, dir)), face_surfaces(num_face)))
        return dir;
    }
  return -1;
}
References Objet_U::dimension, est_egal(), face_normales(), and face_surfaces().
Referenced by Sonde::initialiser().
porosite_elem() [1/3]
DoubleVect & Zone_VF::porosite_elem () inline
Definition at line 287 of file Zone_VF.h.
{
  return porosite_elem_;
}
References porosite_elem_.
porosite_elem() [2/3]
const DoubleVect & Zone_VF::porosite_elem () const inline
Definition at line 293 of file Zone_VF.h.
{
  return porosite_elem_;
}
References porosite_elem_.
porosite_elem() [3/3]
double Zone_VF::porosite_elem (int i) const inline
Definition at line 299 of file Zone_VF.h.
{
  return porosite_elem_[i];
}
References porosite_elem_.
Referenced by Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Source_Generique_P0_Elem::ajouter(), Op_Grad_PolyMAC_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Masse_PolyMAC_Elem::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Assembleur_P_PolyMAC::assembler_continuite(), Assembleur_P_PolyMAC_P0::assembler_continuite(), Assembleur_P_PolyMAC::assembler_mat(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Op_Conv_EF_Stab_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Evaluateur_Source_PolyMAC_Elem::completer(), Evaluateur_Source_VDF_Elem::completer(), Op_Dift_VEF_Face::contribue_au_second_membre(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Champ_Face_PolyMAC_P0::init_ve2(), Champ_Face_PolyMAC::interp_ve(), Porosites::interpreter(), Porosites_champ::interpreter(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Champ_P0_VDF::moyenne(), Champ_Fonc_P0_base::moyenne(), Assembleur_P_PolyMAC::norme_continuite(), Discret_Thyd::porosite_volumique(), Op_Conv_VEF_Face::remplir_fluent(), Op_Diff_VEFP1NCP1B_Face::test(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), Champ_Face_PolyMAC_P0::update_ve(), and visc_Q1().
porosite_face() [1/3]
DoubleVect & Zone_VF::porosite_face () inline
Definition at line 275 of file Zone_VF.h.
{
  return porosite_face_;
}
References porosite_face_.
porosite_face() [2/3]
const DoubleVect & Zone_VF::porosite_face () const inline
Definition at line 281 of file Zone_VF.h.
{
  return porosite_face_;
}
References porosite_face_.
porosite_face() [3/3]
double Zone_VF::porosite_face (int i) const inline
Definition at line 269 of file Zone_VF.h.
{
  return porosite_face_[i];
}
References porosite_face_.
Referenced by Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Div_PolyMAC_P0::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_Singuliere_VEF_Face::ajouter(), Perte_Charge_VEF::ajouter(), Source_Generique_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::ajouter_blocs(), Op_Div_PolyMAC::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Fluide_Dilatable_VDF_Proto::ajouter_impl(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), Op_Grad_VEF_P1B_Face::ajouter_som(), Masse_PolyMAC_Face::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Assembleur_P_VDF_Q4::assembler(), Assembleur_P_PolyMAC_P0::assembler_mat(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Op_Grad_VDF_Face_base::associer(), Force_Centrifuge_VDF_Face_Axi::associer_zones(), Evaluateur_VDF::associer_zones(), Champ_P1NC::calcul_duidxj_paroi(), Segment_poly::calcul_vc(), Tetra_poly::calcul_vc(), Point_EF::calcul_vc(), Segment_EF::calcul_vc(), Tetra_EF::calcul_vc(), Tri_EF::calcul_vc(), Perte_Charge_Singuliere::calculate_Q(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Conv_EF_Stab_PolyMAC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), EDO_Pression_th_VDF::calculer_grad(), Assembleur_P_VEF::calculer_inv_volume(), Op_Diff_VEFP1NCP1B_Face::calculer_laplacien_som(), Champ_front_xyz_debit::calculer_normales_et_integrale(), Champ_Face_get_val_imp_face_bord_sym(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Op_Conv_EF_Stab_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Evaluateur_Source_PolyMAC_Face::completer(), Evaluateur_Source_VDF_Face::completer(), Evaluateur_Source_VEF_Face::completer(), Op_Dift_VEF_Face::contribue_au_second_membre(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Op_Div_PolyMAC_P0::contribuer_a_avec(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_Face_PolyMAC_P0::init_ve2(), Champ_Face_PolyMAC::interp_ve(), Porosites::interpreter(), Porosites_champ::interpreter(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Assembleur_P_VEFPreP1B::modifier_secmem(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), Assembleur_P_VDF::remplir(), Op_Conv_VEF_Face::remplir_fluent(), EOS_Tools_VEF::secmembre_divU_Z(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_Face_PolyMAC_P0::update_ve(), and visc_Q1().
premiere_face_bord()
int Zone_VF::premiere_face_bord () const inline
renvoie le numero de la premiere des faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
Definition at line 541 of file Zone_VF.h.
{
  return 0;
}
Referenced by Op_Diff_VDF_Face_Axi_base::ajouter_aretes_bords(), Op_Dift_VDF_Face_Axi_base::ajouter_aretes_bords(), Evaluateur_VDF::associer_zones(), Champ_Face::calculer_dercov_axi(), Champ_Face_get_val_imp_face_bord(), Champ_Face_get_val_imp_face_bord_sym(), Op_Diff_VDF_Face_Axi_base::contribue_au_second_membre(), and Op_Dift_VDF_Face_Axi_base::contribue_au_second_membre().
premiere_face_int()
int Zone_VF::premiere_face_int () const inline
une face est interne ssi elle separe deux elements.
renvoie le numero de la premiere face interne.
Definition at line 496 of file Zone_VF.h.
{
  return nb_faces_bord();
}
References nb_faces_bord().
Referenced by Champ_Face::affecter_(), Champ_Fonc_Face::affecter_(), Op_Div_EF::ajouter(), Op_Rot_VEFP1B::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Div_PolyMAC_P0::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Source_Generique_VEF::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Masse_PolyMAC_Elem::ajouter_blocs(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_interne(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_interne_vitesse(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Source_Fluide_Dilatable_VDF_Proto::ajouter_impl(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), T_It_VDF_Elem< _TYPE_ >::ajouter_interne(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), assemblerP0P1(), assemblerP0Pa(), assemblerP1P1(), assemblerP1Pa(), assemblerPaPa(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Op_Dift_standard_VEF_Face::calcul_divergence(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Traitement_particulier_NS_EC::calculer_Ec(), EDO_Pression_th_VDF::calculer_grad(), EDO_Pression_th_VEF::calculer_grad(), calculer_gradientP1NC(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Traitement_particulier_NS_Brech_VEF::calculer_terme_destruction_K(), Zone_EF::calculer_volumes_entrelaces(), Zone_VDF::calculer_volumes_entrelaces(), Zone_VEF::calculer_volumes_entrelaces(), Discretisation_tools::cells_to_faces(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Assembleur_P_VDF::construire(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), T_It_VDF_Elem< _TYPE_ >::contribuer_au_second_membre_interne(), Zone_EF::creer_faces_virtuelles_non_std(), Zone_VEF::creer_faces_virtuelles_non_std(), Op_VDF_Elem::dimensionner(), face_voisins_reel_fictif(), fbord(), Champ_P1NC_implementation::filtrer_resu(), Zone_VDF::genere_aretes(), Champ_Q1NC::gradient(), Sonde::initialiser(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Assembleur_P_PolyMAC::modifier_secmem_pour_incr_p(), Op_Conv_EF_Stab_PolyMAC_Elem::preparer_calcul(), Assembleur_P_VEF::remplir(), Assembleur_P_VDF::remplir(), Op_Diff_VEFP1NCP1B_Face::test(), updateP0P1(), updateP0Pa(), updateP1P1(), updateP1Pa(), updatePaPa(), Champ_Elem_PolyMAC::valeur_aux_faces(), and xv_bord().
printOn()
Sortie & Zone_VF::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
< PQ : 12/10/05 : a voir ce qu'il faut faire ici ???
Reimplemented from Zone_dis_base.
Reimplemented in Zone_VF_inst, Zone_VEF_PreP1b, Zone_PolyMAC, Zone_PolyMAC_P0, Zone_VDF, and Zone_VEF.
Definition at line 32 of file Zone_VF.cpp.
{
  os << "volumes_ : " << finl;
  volumes_.ecrit(os);
  os << "volumes_entrelaces_ : " << finl;
  volumes_entrelaces_.ecrit(os);
  os << "face_voisins_ : " << finl;
  face_voisins_.ecrit(os);
  os << "face_surfaces_ : "<<face_surfaces_<< finl;
  face_surfaces_.ecrit(os);
  os << "xp_ : " << finl;
  xp_.ecrit(os);
  os << "xv_ : " << finl;
  xv_.ecrit(os);
  os << "elem_faces_ : " << finl;
  elem_faces_.ecrit(os);
// os << "faces_doubles_ : " << finl; // PQ : 12/10/05 : a voir ce qu'il faut faire ici ???
// faces_doubles_.ecrit(os);
  os << "face_sommets_ : " << finl; //!< PQ : 12/10/05 : a voir ce qu'il faut faire ici ???
  face_sommets_.ecrit(os);
  os << "nb_faces_ : " << finl;
  os << nb_faces() <<finl;
  os << "les_bords_ : " << finl;
  os << les_bords_ <<finl;
  porosite_elem_.ecrit(os);
  porosite_face_.ecrit(os);
  return os ;
}
References TRUSTVect< _TYPE_ >::ecrit(), TRUSTTab< _TYPE_ >::ecrit(), elem_faces_, face_sommets_, face_surfaces_, face_voisins_, finl, les_bords_, nb_faces(), porosite_elem_, porosite_face_, volumes_, volumes_entrelaces_, xp_, and xv_.
Referenced by Zone_EF::ecrit(), Zone_Poly_base::ecrit(), Zone_VEF::ecrit(), Zone_EF::printOn(), Zone_Poly_base::printOn(), Zone_VF_inst::printOn(), Zone_VDF::printOn(), and Zone_VEF::printOn().
readOn()
Entree & Zone_VF::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Zone_dis_base.
Reimplemented in Zone_VF_inst, Zone_VEF_PreP1b, Zone_PolyMAC, Zone_PolyMAC_P0, Zone_VDF, and Zone_VEF.
Definition at line 75 of file Zone_VF.cpp.
{
  volumes_.lit(is);
  volumes_entrelaces_.lit(is);
  face_voisins_.lit(is);
  face_surfaces_.lit(is);
  xp_.lit(is);
  xv_.lit(is);
  elem_faces_.lit(is);
// faces_doubles_.lit(is); // PQ : 12/10/05 : a voir ce qu'il faut faire ici ???
  face_sommets_.lit(is);
  int nb_faces_unused;
  is >> nb_faces_unused;
  is >> les_bords_;
  porosite_elem_.lit(is);
  porosite_face_.lit(is);
  return is ;
}
References elem_faces_, face_sommets_, face_surfaces_, face_voisins_, les_bords_, TRUSTVect< _TYPE_ >::lit(), TRUSTTab< _TYPE_ >::lit(), porosite_elem_, porosite_face_, volumes_, volumes_entrelaces_, xp_, and xv_.
Referenced by Zone_EF::readOn(), Zone_Poly_base::readOn(), Zone_VF_inst::readOn(), Zone_VDF::readOn(), and Zone_VEF::readOn().
remplir_elem_faces()
virtual void Zone_VF::remplir_elem_faces () protected pure virtual
Implemented in Zone_EF, Zone_Poly_base, Zone_VF_inst, Zone_VDF, and Zone_VEF.
Referenced by discretiser().
remplir_face_numero_bord()
void Zone_VF::remplir_face_numero_bord ()
< init for inner faces.
Definition at line 634 of file Zone_VF.cpp.
{
  Cerr << " Zone_VF::remplir_face_numero_bord" << finl;
  face_numero_bord_.resize(nb_faces());
  face_numero_bord_=-1; //!< init for inner faces.
  Zone& lazone=zone();
  int ndeb, nfin, num_face;
  const int nb_bords = lazone.nb_bords();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Bord& le_bord = lazone.bord(n_bord);
      ndeb = le_bord.num_premiere_face();
      nfin = ndeb + le_bord.nb_faces();
      for (num_face=ndeb; num_face<nfin; num_face++)
        {
          face_numero_bord_[num_face] = n_bord;
        }
    }
}
References Zone::bord(), Cerr, face_numero_bord_, finl, Zone::nb_bords(), Frontiere::nb_faces(), nb_faces(), Frontiere::num_premiere_face(), TRUSTTab< _TYPE_ >::resize(), and Zone_dis_base::zone().
Referenced by discretiser().
remplir_face_voisins_fictifs()
void Zone_VF::remplir_face_voisins_fictifs (const Zone_Cl_dis_base &) virtual
Definition at line 249 of file Zone_VF.cpp.
{
  Cerr <<" Zone_VF::remplir_face_voisins_fictifs(const Zone_Cl_dis_base& ) must be overloaded by" << que_suis_je()<<finl;
  exit();
  assert(0);
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
reordonner()
void Zone_VF::reordonner (Faces &) virtual
cette methode ne fait rien
elle est surchargee par Zone_VDF par ex.
Reimplemented in Zone_EF, Zone_Poly_base, Zone_VDF, and Zone_VEF.
Definition at line 97 of file Zone_VF.cpp.
{
}
Referenced by discretiser().
section_passage_face() [1/2]
const DoubleVect Zone_VF::section_passage_face () const inline
Definition at line 335 of file Zone_VF.h.
{
// remplissage des sections de passage
  DoubleVect section_passage_face_(face_surfaces_);
  for (int i=0; i<face_surfaces_.size_array(); i++)
    section_passage_face_[i] = section_passage_face(i);
  return section_passage_face_;
}
References face_surfaces_, section_passage_face(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by section_passage_face().
section_passage_face() [2/2]
double Zone_VF::section_passage_face (int i) const inline
Definition at line 345 of file Zone_VF.h.
{
  return face_surfaces_[i] * porosite_face_[i];
}
References face_surfaces_, and porosite_face_.
Referenced by Discret_Thyd::section_passage().
self_cast() [1/2]
const Zone_VF & Zone_VF::self_cast (const Objet_U & r) static
Definition at line 30 of file Zone_VF.cpp.
self_cast() [2/2]
Zone_VF & Zone_VF::self_cast (Objet_U & r) static
Definition at line 30 of file Zone_VF.cpp.
surface()
virtual double Zone_VF::surface (int i) const inline virtual
Definition at line 55 of file Zone_VF.h.
  {
    return face_surfaces(i);
  };
References face_surfaces().
Referenced by Op_Grad_EF::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Echange_interne_global_impose::completer(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Champ_Generique_Transformation::get_champ(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), and Op_Dift_Stab_VEF_Face::modifie_pour_Cl().
typer_elem()
void Zone_VF::typer_elem (Zone & azone) virtual
Reimplemented in Zone_VEF, Zone_EF, and Zone_Poly_base.
Definition at line 549 of file Zone_VF.cpp.
{
// Ne fait rien
}
Referenced by Domaine_dis::discretiser().
volumes() [1/3]
DoubleVect & Zone_VF::volumes () inline
renvoie le tableaux des volumes des mailles.
Definition at line 414 of file Zone_VF.h.
{
  return volumes_;
}
References volumes_.
Referenced by Zone_EF::calculer_h_carre(), Zone_Poly_base::calculer_h_carre(), Zone_VEF::calculer_h_carre(), Zone_EF::calculer_IPhi(), Zone_VDF::calculer_volumes_entrelaces(), Zone_VEF::calculer_volumes_entrelaces(), Zone_VEF_PreP1b::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), Zone_PolyMAC::M1(), Zone_PolyMAC::M2(), Zone_VEF::modifier_pour_Cl(), Zone_PolyMAC::W1(), and Zone_PolyMAC::W2().
volumes() [2/3]
const DoubleVect & Zone_VF::volumes () const inline
renvoie le tableaux des volumes des mailles.
Definition at line 425 of file Zone_VF.h.
{
  return volumes_;
}
References volumes_.
volumes() [3/3]
double Zone_VF::volumes (int i) const inline
renvoie le volume de la maille i.
Definition at line 403 of file Zone_VF.h.
{
  return volumes_[i];
}
References volumes_.
Referenced by Op_Dift_Stab_VEF_Face::aij_extradiag(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Source_Generique_P0_Elem::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_P0::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Elem::ajouter_blocs(), Terme_Source_Solide_SWIFT_VDF::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Masse_PolyMAC_Elem::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Diff_EF::ajouter_scalaire_template(), Op_Dift_EF_Q1::ajouter_scalaire_template(), Op_Conv_EF::ajouter_sous_cond_template(), Op_Diff_EF::ajouter_vectoriel_template(), Op_Dift_EF_Q1::ajouter_vectoriel_template(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Assembleur_P_PolyMAC::assembler_continuite(), Assembleur_P_PolyMAC_P0::assembler_continuite(), Champ_front_contact_VEF::calcul_coeff_amort(), Champ_front_contact_VEF::calcul_grads_locaux(), calcul_longueur_filtre(), Calcul_integrale_locale::calculer(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Dift_Stab_VEF_Face::calculer_coefficients(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Op_Dift_VEF_P1NCP1B_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Dift_VEF_Face_Q1::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), EDO_Pression_th_VEF::calculer_grad(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Op_Dift_Stab_VEF_Face::calculer_gradients(), Op_Conv_VDF_base::calculer_pour_post(), Traitement_particulier_NS_Brech_VEF::calculer_terme_destruction_K(), Traitement_particulier_NS_Brech_VEF::calculer_terme_production_K(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Discretisation_tools::cells_to_faces(), Evaluateur_Source_PolyMAC_Elem::completer(), Eval_Puiss_Th_QC_VEF_Face::completer(), Evaluateur_Source_VDF_Elem::completer(), Eval_Puiss_Th_VEF_Face::completer(), Eval_Source_C_VEF_Face::completer(), Terme_Source_Rappel_T_VEF_Face::completer(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Sous_zone_VF::discretiser(), Domaine_dis::discretiser(), EOS_Tools_VEF::divu_discvit(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Source_WC_Chaleur_VEF::elem_to_face(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Q1NC::gradient(), Champ_Face_PolyMAC_P0::init_ve2(), Champ_P0_VDF::integrale_espace(), Champ_Face_PolyMAC::interp_ve(), EDO_Pression_th_VDF::masse_totale(), Eval_Darcy_VDF_Face::mettre_a_jour(), Eval_Darcy_VEF_Face::mettre_a_jour(), Chimie::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Champ_P0_VDF::moyenne(), Champ_Fonc_P0_base::moyenne(), EOS_Tools_VDF::moyenne_vol(), Assembleur_P_PolyMAC::norme_continuite(), Champ_P1NC::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Champ_P1_isoP1Bulle::norme_L2(), Echange_contact_Correlation_VEF::pdt_scal(), Echange_contact_Correlation_VEF::pdt_scalSqrt(), Assembleur_P_VEFPreP1B::projete_L2(), Op_Diff_RotRot::remplir_elem_elem_EF(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Op_Diff_RotRot::remplir_som_som_EF(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EOS_Tools_VDF::secmembre_divU_Z(), EOS_Tools_VEF::secmembre_divU_Z(), grad_Champ_Face_PolyMAC_P0::update_ge(), Champ_Face_PolyMAC_P0::update_ve(), visc_Q1(), viscA_Q1(), Discretisation_base::volume_maille(), Op_Div_EF::volumique(), Op_Div_PolyMAC::volumique(), Op_Div_PolyMAC_P0::volumique(), Op_Div_VDF_Elem::volumique(), and Op_Div_VEF_Elem::volumique().
volumes_entrelaces() [1/3]
DoubleVect & Zone_VF::volumes_entrelaces () inline
Definition at line 720 of file Zone_VF.h.
{
  return volumes_entrelaces_;
}
References volumes_entrelaces_.
Referenced by Op_Conv_EF_VEF_P1NC::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_VEF::ajouter(), Source_Generique_VEF::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Terme_Source_Decroissance_Radioactive_VEF_Face::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_Face::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Source_Fluide_Dilatable_VDF_Proto::ajouter_impl(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Assembleur_P_VDF::assembler(), Assembleur_P_VDF_Q4::assembler(), Assembleur_P_VEF::assembler(), Assembleur_P_PolyMAC::assembler_continuite(), Simpler_Base::assembler_matrice_pression_implicite(), Assembleur_P_VDF::assembler_QC(), Assembleur_P_VEFPreP1B::assembler_rho_variable(), Assembleur_P_VDF::assembler_rho_variable(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Op_Grad_VDF_Face_base::associer(), Force_Centrifuge_VDF_Face_Axi::associer_zones(), Evaluateur_VDF::associer_zones(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Traitement_particulier_NS_EC::calculer_Ec(), EDO_Pression_th_VDF::calculer_grad(), EDO_Pression_th_VEF::calculer_grad(), Op_Conv_VEF_base::calculer_pour_post(), Discretisation_tools::cells_to_faces(), Evaluateur_Source_PolyMAC_Face::completer(), Sortie_libre_Gradient_Pression_impose::completer(), Evaluateur_Source_VDF_Face::completer(), Evaluateur_Source_VEF_Face::completer(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec(), Terme_Source_Decroissance_Radioactive_VEF_Face::contribuer_a_avec(), Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), EOS_Tools_VEF::divu_discvit(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Zone_PolyMAC_P0::fgrad(), Champ_P1NC_implementation::filtrer_resu(), Zone_Cl_VEF::initialiser(), Courant_maille_Champ_Face::mettre_a_jour(), Reynolds_maille_Champ_Face::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Tetra_VEF::modif_volumes_entrelaces(), Tri_VEF::modif_volumes_entrelaces(), Tetra_VEF::modif_volumes_entrelaces_faces_joints(), Tri_VEF::modif_volumes_entrelaces_faces_joints(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_L2(), norme_L2(), Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(), Zone_Cl_VEFP1B::remplir_volumes_entrelaces_Cl(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), EOS_Tools_VEF::secmembre_divU_Z(), Op_Diff_VEF_Anisotrope_Face::verifier(), Op_Diff_VEF_Face::verifier(), verifier(), and Sous_zone_VF::volumes_entrelaces().
volumes_entrelaces() [2/3]
const DoubleVect & Zone_VF::volumes_entrelaces () const inline
Definition at line 726 of file Zone_VF.h.
{
  return volumes_entrelaces_;
}
References volumes_entrelaces_.
volumes_entrelaces() [3/3]
double Zone_VF::volumes_entrelaces (int num_face) const inline
Definition at line 732 of file Zone_VF.h.
{
  return volumes_entrelaces_[num_face];
}
References volumes_entrelaces_.
volumes_entrelaces_dir() [1/2]
DoubleTab & Zone_VF::volumes_entrelaces_dir () inline
Definition at line 739 of file Zone_VF.h.
{
  return volumes_entrelaces_dir_;
}
References volumes_entrelaces_dir_.
volumes_entrelaces_dir() [2/2]
const DoubleTab & Zone_VF::volumes_entrelaces_dir () const inline
Definition at line 745 of file Zone_VF.h.
{
  return volumes_entrelaces_dir_;
}
References volumes_entrelaces_dir_.
xa() [1/3]
DoubleTab & Zone_VF::xa () inline
Definition at line 708 of file Zone_VF.h.
{
  return xa_;
}
References xa_.
Referenced by Zone_VEF_PreP1b::construire_renum_arete_perio().
xa() [2/3]
const DoubleTab & Zone_VF::xa () const inline
Definition at line 714 of file Zone_VF.h.
{
  return xa_;
}
References xa_.
xa() [3/3]
double Zone_VF::xa (int num_arete, int k) const inline
Definition at line 702 of file Zone_VF.h.
{
  return xa_(num_arete,k);
}
References xa_.
Referenced by Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Aretes::calculer_centre_de_gravite(), Champ_Generique_Transformation::completer(), Scatter::construire_correspondance_aretes_par_coordonnees(), exemple_champ_non_homogene(), get_ref_coordinates_items(), Assembleur_P_VEFPreP1B::modifier_matrice(), Debog_Pb::read_geometry_data(), and Debog_Pb::write_geometry_data().
xp() [1/3]
DoubleTab & Zone_VF::xp () inline
Definition at line 690 of file Zone_VF.h.
{
  return xp_;
}
References xp_.
Referenced by Zone_VDF::calculer_volumes_entrelaces(), Zone_VDF::discretiser(), Zone_PolyMAC::M1(), Zone_PolyMAC::M2(), normalized_boundaries_outward_vector(), Zone_EF_axi::remplir_tableau_origine(), Zone_VEF::vecteur_face_facette(), Zone_PolyMAC::W1(), and Zone_PolyMAC::W2().
xp() [2/3]
const DoubleTab & Zone_VF::xp () const inline
Definition at line 696 of file Zone_VF.h.
{
  return xp_;
}
References xp_.
xp() [3/3]
double Zone_VF::xp (int num_elem, int k) const inline
Definition at line 684 of file Zone_VF.h.
{
  return xp_(num_elem,k);
}
References xp_.
Referenced by Champ_P1_isoP1Bulle::affecter_(), Champ_Elem_PolyMAC::affecter_(), Champ_Fonc_Elem_PolyMAC::affecter_(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Op_Grad_VDF_Face_base::associer(), Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Force_Centrifuge_VDF_Face_Axi::associer_zones(), Calcul_integrale_locale::Calcul_integrale_locale(), Calcul_integrale_locale::calculer(), Champ_Face::calculer_dercov_axi(), EDO_Pression_th_VDF::calculer_grad(), EDO_Pression_th_VEF::calculer_grad(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Fluide_Weakly_Compressible::calculer_pression_hydro(), Fluide_Dilatable_base::calculer_pression_tot(), Champ_base::calculer_valeurs_elem_compo_post(), Champ_base::calculer_valeurs_elem_post(), Terme_Source_Rappel_T_VEF_Face::completer(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Eval_Quick_VDF_Face_Axi::dist_elem(), distance_2D(), distance_3D(), exemple_champ_non_homogene(), Extraire_surface::extraire_surface(), Champ_Generique_Transformation::get_champ(), get_ref_coordinates_items(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Traitement_particulier_Solide_canal_VDF::init_calcul_moyenne(), Zone_Poly_base::init_dist_paroi_globale(), Champ_Face_PolyMAC_P0::init_ve2(), Sonde::initialiser(), Champ_front_recyclage::initialiser(), Champ_Face_PolyMAC::interp_ve(), Extraire_domaine::interpreter_(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Correlation_Vec_Sca_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Assembleur_P_VEF::modifier_matrice(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Postraitement_lata::postraiter_liste_champs(), Debog_Pb::read_geometry_data(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Champ_P0_VDF::remplir_coord_noeuds(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Traitement_particulier_NS_canal_VDF::remplir_Y(), Moyenne_volumique::traiter_champs(), grad_Champ_Face_PolyMAC_P0::update_ge(), Champ_Face_PolyMAC_P0::update_ve(), and verifier().
xv() [1/3]
DoubleTab & Zone_VF::xv () inline
Definition at line 672 of file Zone_VF.h.
{
  return xv_;
}
References xv_.
Referenced by Zone_VDF::calculer_volumes_entrelaces(), Zone_VDF::discretiser(), Zone_VDF::genere_aretes(), Zone_PolyMAC::M1(), Zone_PolyMAC::M2(), normalized_boundaries_outward_vector(), Zone_PolyMAC::W1(), and Zone_PolyMAC::W2().
xv() [2/3]
const DoubleTab & Zone_VF::xv () const inline
Definition at line 678 of file Zone_VF.h.
{
  return xv_;
}
References xv_.
xv() [3/3]
double Zone_VF::xv (int num_face, int k) const inline
Definition at line 634 of file Zone_VF.h.
{
  return xv_(num_face,k);
}
References xv_.
Referenced by Champ_Face_PolyMAC::affecter_(), Champ_Face_PolyMAC_P0::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Face::affecter_(), Champ_Fonc_Face::affecter_(), Champ_Elem_PolyMAC::affecter_(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_VEF_Face::ajouter(), Perte_Charge_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion(), Op_Dift_Stab_VEF_Face::ajouter_antidiffusion_vectoriel(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Sonde::ajouter_bords(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Force_Centrifuge_VDF_Face_Axi::associer_zones(), Evaluateur_VDF::associer_zones(), Champ_front_recyclage::calcul_moyenne_imposee(), Champ_Face::calculer_dercov_axi(), Traitement_particulier_NS_EC::calculer_Ec(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), Terme_Source_Acceleration::calculer_la_source(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Fluide_Weakly_Compressible::calculer_pression_hydro(), Champ_front_calc_interne::completer(), Echange_interne_global_impose::completer(), Champ_front_contact_VEF::connectivity_failed(), Perte_Charge_VEF::contribuer_a_avec(), Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), Op_Conv_kschemas_centre_VEF::convkschemas_centre(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Eval_Quick_VDF_Face_Axi::dist_face(), distance_2D(), distance_3D(), distance_face(), Extraire_surface::extraire_surface(), Champ_P1NC_implementation::filtrer_H1(), Champ_Generique_Transformation::get_champ(), Champ_front_recyclage::get_coord_faces(), get_ref_coordinates_items(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), Op_Div_PolyMAC::impr(), Op_Div_PolyMAC_P0::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEF_Elem::impr(), Champ_P1NC_implementation::imprime_P1NC(), Echange_contact_Correlation_VEF::init(), Terme_Source_Canal_RANS_LES_VEF_Face::init(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Zone_Poly_base::init_dist_paroi_globale(), Echange_contact_PolyMAC::init_f_dist(), Echange_contact_PolyMAC_P0::init_fs_dist(), Champ_Face_PolyMAC_P0::init_ve2(), Raccord_distant_homogene::initialise(), Sonde::initialiser(), Ch_front_Vortex::initialiser(), Champ_front_lu::initialiser(), Champ_front_softanalytique::initialiser(), Champ_front_recyclage::initialiser_moyenne_imposee(), Champ_Face_PolyMAC::interp_ve(), Extraire_plan::interpreter_(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), Perte_Charge_Singuliere::lire_surfaces(), Champ_Front_Fonction::mettre_a_jour(), Champ_front_txyz::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Ch_front_Vortex::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d(), Postraitement::postraiter_tableau(), Debog_Pb::read_geometry_data(), Champ_Don_Face_lu::readOn(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_Face_implementation::remplir_coord_noeuds(), Champ_P1NC_implementation::remplir_coord_noeuds(), Champ_Q1NC_impl::remplir_coord_noeuds(), Zone_Cl_VEF::remplir_normales_facettes_Cl(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Traitement_particulier_NS_canal_VEF::remplir_Y(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_front_contact_VEF::test_faces_coin(), Champ_P1iP1B_implementation::trace(), Echange_contact_Correlation_VDF::trier_coord(), grad_Champ_Face_PolyMAC_P0::update_ge(), Champ_Face_PolyMAC_P0::update_ve(), Champ_Elem_PolyMAC::valeur_aux_faces(), Op_Diff_VEF_Anisotrope_Face::verifier(), Op_Diff_VEF_Face::verifier(), verifier(), Echange_contact_VDF::verifier_correspondance(), and Debog_Pb::write_geometry_data().
xv_bord()
const DoubleTab & Zone_VF::xv_bord () const virtual
Definition at line 654 of file Zone_VF.cpp.
{
  if (xv_bord_.get_md_vector() == md_vector_faces_bord()) return xv_bord_; //deja cree
  xv_bord_.resize(0, dimension), creer_tableau_faces_bord(xv_bord_);
  std::copy(xv_.addr(), xv_.addr() + dimension * premiere_face_int(), xv_bord_.addr()); //faces reelles : le debut de xv_
  xv_bord_.echange_espace_virtuel();
  return xv_bord_;
}
References TRUSTArray< _TYPE_ >::addr(), creer_tableau_faces_bord(), Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_ >::get_md_vector(), md_vector_faces_bord(), premiere_face_int(), TRUSTTab< _TYPE_ >::resize(), xv_, and xv_bord_.
Referenced by Milieu_composite::calculer_masse_volumique(), and Champ_Inc_base::valeur_aux_bords().
Member Data Documentation
coefficient_echange_thermique_
DoubleVect Zone_VF::coefficient_echange_thermique_ protected
remplissage des coefficients d'echange_thermique
Definition at line 213 of file Zone_VF.h.
Referenced by calculer_coefficient_echange_thermique(), and coefficient_echange_thermique().
coefficient_frottement_
DoubleVect Zone_VF::coefficient_frottement_ protected
remplissage des coefficient de frottement
Definition at line 214 of file Zone_VF.h.
Referenced by calculer_coefficient_frottement(), and coefficient_frottement().
diametre_hydraulique_elem_
DoubleTab Zone_VF::diametre_hydraulique_elem_ protected
Definition at line 212 of file Zone_VF.h.
Referenced by calculer_diametres_hydrauliques(), and diametre_hydraulique_elem().
diametre_hydraulique_face_
DoubleVect Zone_VF::diametre_hydraulique_face_ protected
Definition at line 211 of file Zone_VF.h.
Referenced by calculer_diametres_hydrauliques(), and diametre_hydraulique_face().
elem_faces_
IntTab Zone_VF::elem_faces_ protected
connectivite element/faces
Definition at line 222 of file Zone_VF.h.
Referenced by Zone_VDF::amont_amont(), Zone_EF::calculer_Bij_gen(), Zone_EF_axi::calculer_Bij_gen(), construire_num_fac_loc(), Zone_VDF::dim_elem(), Zone_Poly_base::discretiser(), discretiser(), elem_faces(), Zone_VDF::elem_voisin(), Zone_VDF::face_amont_conj(), Zone_VDF::face_amont_princ(), Zone_VDF::face_bord_amont(), numero_face_local(), printOn(), readOn(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Zone_VDF::reordonner(), and Zone_VEF::reordonner().
face_numero_bord_
IntTab Zone_VF::face_numero_bord_ protected
connectivite face/numero_bord
Definition at line 225 of file Zone_VF.h.
Referenced by face_numero_bord(), and remplir_face_numero_bord().
face_sommets_
IntTab Zone_VF::face_sommets_ protected
sommets des faces
Definition at line 223 of file Zone_VF.h.
Referenced by Zone_EF::calculer_Bij_gen(), Zone_EF_axi::calculer_Bij_gen(), Zone_Poly_base::detecter_faces_non_planes(), Zone_Poly_base::discretiser(), face_sommets(), nb_faces(), nb_faces_tot(), nb_som_face(), printOn(), and readOn().
face_surfaces_
DoubleVect Zone_VF::face_surfaces_ private
surface des faces
Definition at line 197 of file Zone_VF.h.
Referenced by calculer_face_surfaces(), discretiser(), face_surfaces(), printOn(), readOn(), and section_passage_face().
face_virt_pe_num_
IntTab Zone_VF::face_virt_pe_num_ protected
Definition at line 242 of file Zone_VF.h.
Referenced by construire_face_virt_pe_num(), and face_virt_pe_num().
face_voisins_
IntTab Zone_VF::face_voisins_ protected
connectivite face/elements
Definition at line 216 of file Zone_VF.h.
Referenced by Zone_VDF::amont_amont(), Zone_EF::calculer_volumes_entrelaces(), Zone_VDF::calculer_volumes_entrelaces(), Zone_VEF::calculer_volumes_entrelaces(), construire_num_fac_loc(), Zone_VEF_PreP1b::construire_renum_arete_perio(), Zone_VDF::dim_face(), Zone_Poly_base::discretiser(), Zone_VDF::discretiser(), Zone_VDF::dist_norm(), Zone_VDF::dist_norm_axi(), Zone_VDF::dist_norm_bord(), Zone_VDF::dist_norm_bord_axi(), Zone_VDF::dist_norm_period(), Zone_VDF::distance_normale(), Zone_VDF::elem_voisin(), Zone_VDF::face_amont_conj(), Zone_VDF::face_amont_princ(), Zone_VDF::face_bord_amont(), face_voisins(), Zone_EF::modifier_pour_Cl(), modifier_pour_Cl(), Zone_VEF::modifier_pour_Cl(), printOn(), and readOn().
face_voisins_fictifs_
IntTab Zone_VF::face_voisins_fictifs_ protected
connectivite face/elements fictifs
Definition at line 217 of file Zone_VF.h.
Referenced by Zone_VDF::creer_elements_fictifs(), face_voisins_fictifs(), and face_voisins_reel_fictif().
faces_doubles_
ArrOfInt Zone_VF::faces_doubles_ protected
faces a double contribution (faces periodiques et items communs)
Definition at line 237 of file Zone_VF.h.
Referenced by faces_doubles(), and marquer_faces_double_contrib().
info_obj
const Type_info Zone_VF::info_obj static
Definition at line 38 of file Zone_VF.h.
inverse_volumes_
DoubleVect Zone_VF::inverse_volumes_ protected
inverse du volumes des elements
Definition at line 202 of file Zone_VF.h.
Referenced by discretiser(), and inverse_volumes().
les_bords_
Vect_Front_VF Zone_VF::les_bords_ protected
Definition at line 234 of file Zone_VF.h.
Referenced by discretiser(), Zone_Poly_base::dist_norm_bord(), Zone_VDF::dist_norm_bord(), front_VF(), frontiere_dis(), nb_frontiere_dis(), printOn(), and readOn().
md_vector_aretes_
MD_Vector Zone_VF::md_vector_aretes_ protected
Definition at line 232 of file Zone_VF.h.
Referenced by Zone_PolyMAC::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), and md_vector_aretes().
md_vector_faces_
MD_Vector Zone_VF::md_vector_faces_ protected
Definition at line 228 of file Zone_VF.h.
Referenced by creer_tableau_faces(), discretiser(), and md_vector_faces().
md_vector_faces_front_
MD_Vector Zone_VF::md_vector_faces_front_ protected
Definition at line 230 of file Zone_VF.h.
Referenced by discretiser(), and md_vector_faces_bord().
num_fac_loc_
IntTab Zone_VF::num_fac_loc_ protected
Definition at line 236 of file Zone_VF.h.
Referenced by construire_num_fac_loc(), and get_num_fac_loc().
porosite_elem_
DoubleVect Zone_VF::porosite_elem_ protected
Porosites volumiques pour les volumes de controle de masse.
Definition at line 206 of file Zone_VF.h.
Referenced by Zone_EF::calculer_IPhi(), Zone_EF_axi::calculer_IPhi(), calculer_porosites(), Zone_EF::calculer_volumes_sommets(), porosite_elem(), printOn(), and readOn().
porosite_face_
DoubleVect Zone_VF::porosite_face_ protected
Porosites surfaciques en masse et volumiques.
Definition at line 208 of file Zone_VF.h.
Referenced by calculer_porosites(), porosite_face(), printOn(), readOn(), and section_passage_face().
volumes_
DoubleVect Zone_VF::volumes_ protected
volumes des elements
Definition at line 201 of file Zone_VF.h.
Referenced by Zone_EF::calculer_Bij(), Zone_EF::calculer_volumes_entrelaces(), Zone_EF::calculer_volumes_sommets(), discretiser(), Zone_EF::modifier_pour_Cl(), printOn(), readOn(), and volumes().
volumes_entrelaces_
DoubleVect Zone_VF::volumes_entrelaces_ protected
volumes entrelaces pour l'integration des Qdm
Definition at line 203 of file Zone_VF.h.
Referenced by Zone_EF::calculer_volumes_entrelaces(), Zone_VDF::calculer_volumes_entrelaces(), Zone_VEF::calculer_volumes_entrelaces(), Zone_Poly_base::discretiser(), Zone_EF::ecrit(), Zone_Poly_base::ecrit(), Zone_VEF::ecrit(), Zone_EF::modifier_pour_Cl(), Zone_VEF::modifier_pour_Cl(), Zone_EF::printOn(), Zone_Poly_base::printOn(), printOn(), Zone_VEF::printOn(), Zone_EF::readOn(), Zone_Poly_base::readOn(), readOn(), Zone_VEF::readOn(), and volumes_entrelaces().
volumes_entrelaces_dir_
DoubleTab Zone_VF::volumes_entrelaces_dir_ protected
volumes entrelaces par cote
Definition at line 204 of file Zone_VF.h.
Referenced by Zone_VDF::calculer_volumes_entrelaces(), Zone_Poly_base::discretiser(), Zone_Poly_base::volumes_entrelaces_dir(), and volumes_entrelaces_dir().
xa_
DoubleTab Zone_VF::xa_ protected
centres de gravite des aretes
Definition at line 224 of file Zone_VF.h.
Referenced by Zone_VEF_PreP1b::construire_ok_arete(), Zone_PolyMAC::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), Zone_VEF_PreP1b::lecture_ok_arete(), Zone_PolyMAC::M1(), Zone_PolyMAC::W1(), and xa().
xp_
DoubleTab Zone_VF::xp_ protected
centres de gravite des elements
Definition at line 218 of file Zone_VF.h.
Referenced by Zone_Poly_base::discretiser(), discretiser(), Zone_VDF::dist_elem(), Zone_VDF::dist_elem_period(), Zone_Poly_base::dist_face_elem0(), Zone_VDF::dist_face_elem0(), Zone_VDF::dist_face_elem0_axi(), Zone_VDF::dist_face_elem0_period(), Zone_Poly_base::dist_face_elem1(), Zone_VDF::dist_face_elem1(), Zone_VDF::dist_face_elem1_axi(), Zone_VDF::dist_face_elem1_period(), Zone_Poly_base::dist_norm(), Zone_VDF::dist_norm(), Zone_VDF::dist_norm_axi(), Zone_Poly_base::dist_norm_bord(), Zone_VDF::dist_norm_bord(), Zone_VDF::dist_norm_bord_axi(), Zone_VDF::dist_norm_period(), Zone_VDF::distance_normale(), Zone_PolyMAC_P0::fgrad(), Zone_Poly_base::init_equiv(), Zone_EF::modifier_pour_Cl(), Zone_VEF::modifier_pour_Cl(), Zone_PolyMAC::orthocentrer(), Zone_EF::printOn(), Zone_Poly_base::printOn(), printOn(), Zone_VEF::printOn(), Zone_EF::readOn(), Zone_Poly_base::readOn(), readOn(), Zone_VEF::readOn(), and xp().
xv_
DoubleTab Zone_VF::xv_ protected
centres de gravite des faces
Definition at line 219 of file Zone_VF.h.
Referenced by Zone_VDF::calcul_h(), calculer_coefficient_echange_thermique(), calculer_coefficient_frottement(), Zone_VDF::calculer_volumes_entrelaces(), Zone_Poly_base::detecter_faces_non_planes(), Zone_VDF::dim_elem(), Zone_Poly_base::discretiser(), discretiser(), Zone_VDF::dist_elem_period(), Zone_VDF::dist_face(), Zone_VDF::dist_face_axi(), Zone_Poly_base::dist_face_elem0(), Zone_VDF::dist_face_elem0(), Zone_VDF::dist_face_elem0_axi(), Zone_VDF::dist_face_elem0_period(), Zone_Poly_base::dist_face_elem1(), Zone_VDF::dist_face_elem1(), Zone_VDF::dist_face_elem1_axi(), Zone_VDF::dist_face_elem1_period(), Zone_VDF::dist_face_period(), Zone_Poly_base::dist_norm_bord(), Zone_VDF::dist_norm_bord(), Zone_VDF::dist_norm_bord_axi(), Zone_VDF::distance_face(), Zone_VDF::distance_normale(), Zone_PolyMAC_P0::fgrad(), Zone_Poly_base::init_equiv(), Zone_EF::modifier_pour_Cl(), Zone_VEF::modifier_pour_Cl(), Zone_PolyMAC::orthocentrer(), Zone_EF::printOn(), Zone_Poly_base::printOn(), printOn(), Zone_VEF::printOn(), Zone_EF::readOn(), Zone_Poly_base::readOn(), readOn(), Zone_VEF::readOn(), xv(), and xv_bord().
xv_bord_
DoubleTab Zone_VF::xv_bord_ mutable protected
Definition at line 220 of file Zone_VF.h.
Referenced by xv_bord().
The documentation for this class was generated from the following files:
src/Kernel/VF/Zones/Zone_VF.h
src/Kernel/VF/Zones/Zone_VF.cpp