TRUST: Eval_Puiss_Th_CoviMAC_Elem Class Reference
Eval_Puiss_Th_CoviMAC_Elem Class Reference
#include <Eval_Puiss_Th_CoviMAC_Elem.h>
Public Member Functions
void associer_champs (const Champ_Don &)
virtual void mettre_a_jour ()
double calculer_terme_source (int) const
void calculer_terme_source (int, DoubleVect &) const
Protected Attributes
Ref_Champ_Don la_puissance
DoubleTab puissance
Detailed Description
Definition at line 39 of file Eval_Puiss_Th_CoviMAC_Elem.h.
Member Function Documentation
void Eval_Puiss_Th_CoviMAC_Elem::associer_champs (const Champ_Don & Q)
Definition at line 25 of file Eval_Puiss_Th_CoviMAC_Elem.cpp.
References la_puissance, puissance, DoubleTab::ref(), and Champ_Don::valeurs().
Referenced by Terme_Puissance_Thermique_CoviMAC_Elem::associer_pb().
{
  la_puissance = Q;
  puissance.ref(Q.valeurs());
}
void Eval_Puiss_Th_CoviMAC_Elem::calculer_terme_source (int e, DoubleVect & S) const [inline, virtual]
Implements Evaluateur_Source_CoviMAC.
Definition at line 74 of file Eval_Puiss_Th_CoviMAC_Elem.h.
References la_puissance, Evaluateur_Source_CoviMAC_Elem::porosite_vol, puissance, DoubleVect::size(), sub_type, Deriv_Champ_Don_base::valeur(), Ref_Champ_Don::valeur(), and Evaluateur_Source_CoviMAC_Elem::volumes.
{
  const int N = S.size(), pc = sub_type(Champ_Uniforme,la_puissance.valeur().valeur());
  for (int n = 0; n < N; n++) S[n] = puissance(!pc * e, n) * volumes(e) * porosite_vol(e);
}
double Eval_Puiss_Th_CoviMAC_Elem::calculer_terme_source (int num_elem) const [inline, virtual]
Implements Evaluateur_Source_CoviMAC.
Definition at line 61 of file Eval_Puiss_Th_CoviMAC_Elem.h.
References DoubleTab::nb_dim(), Evaluateur_Source_CoviMAC_Elem::porosite_vol, puissance, sub_type, Deriv_Champ_Don_base::valeur(), and Evaluateur_Source_CoviMAC_Elem::volumes.
{
  if (sub_type(Champ_Uniforme,la_puissance.valeur().valeur()))
    return puissance(0,0)*volumes(num_elem)*porosite_vol(num_elem);
  else
    {
      if (puissance.nb_dim()==1)
        return puissance(num_elem)*volumes(num_elem)*porosite_vol(num_elem);
      else
        return puissance(num_elem,0)*volumes(num_elem)*porosite_vol(num_elem);
    }
}
void Eval_Puiss_Th_CoviMAC_Elem::mettre_a_jour () [virtual]
Implements Evaluateur_Source_CoviMAC.
Definition at line 31 of file Eval_Puiss_Th_CoviMAC_Elem.cpp.
{
  /* int n = puissance.size();
     double pt=0.;
     for (int i =0;i<n;i++)
     {
     pt += puissance(i,0)*volumes(i);
     }
     Cout << "puissa tot "  << pt << finl;*/
}
Member Data Documentation
Ref_Champ_Don Eval_Puiss_Th_CoviMAC_Elem::la_puissance [protected]
Definition at line 51 of file Eval_Puiss_Th_CoviMAC_Elem.h.
Referenced by associer_champs(), and calculer_terme_source().
DoubleTab Eval_Puiss_Th_CoviMAC_Elem::puissance [protected]
Definition at line 52 of file Eval_Puiss_Th_CoviMAC_Elem.h.
Referenced by associer_champs(), and calculer_terme_source().
The documentation for this class was generated from the following files:
src/CoviMAC/Sources/Eval_Puiss_Th_CoviMAC_Elem.h
src/CoviMAC/Sources/Eval_Puiss_Th_CoviMAC_Elem.cpp