TRUST: Terme_Source_Decroissance_Radioactive_P0_PolyMAC Class Reference
Terme_Source_Decroissance_Radioactive_P0_PolyMAC Class Reference
class Terme_Source_Decroissance_Radioactive_P0_PolyMAC
#include <Terme_Source_Decroissance_Radioactive_P0_PolyMAC.h>
Public Member Functions
~Terme_Source_Decroissance_Radioactive_P0_PolyMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
void mettre_a_jour (double)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void associer_pb (const Probleme_base &)
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Terme_Source_Decroissance_Radioactive_P0_PolyMAC & self_cast (Objet_U &)
static const
Terme_Source_Decroissance_Radioactive_P0_PolyMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
Protected Attributes
std::vector< double > lambda
int nb_groupes = 0
Ref_Zone_PolyMAC la_zone_PolyMAC
Detailed Description
class Terme_Source_Decroissance_Radioactive_P0_PolyMAC
See also:
Source_base
Definition at line 42 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.h.
Constructor & Destructor Documentation
Terme_Source_Decroissance_Radioactive_P0_PolyMAC::~Terme_Source_Decroissance_Radioactive_P0_PolyMAC ()
Definition at line 29 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
Member Function Documentation
DoubleTab & Terme_Source_Decroissance_Radioactive_P0_PolyMAC::ajouter (DoubleTab & resu) const [virtual]
Reimplemented from Source_base.
Definition at line 76 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
References MorEqn::equation(), Equation_base::inconnue(), la_zone_PolyMAC, lambda, Zone_dis_base::nb_elem(), nb_groupes, Ref_Zone_PolyMAC::valeur(), Champ_Inc::valeurs(), and Zone_VF::volumes().
Referenced by calculer().
{
  int nb_elem = la_zone_PolyMAC.valeur().nb_elem();
  const Zone_VF& zone = la_zone_PolyMAC.valeur();
  const DoubleVect& ve = zone.volumes();
  const DoubleTab& c = equation().inconnue().valeurs();
  for (int e = 0; e < nb_elem; e++) for (int l = 0; l < nb_groupes; l++)
      resu(e, l) -= lambda[l] * c(e, l) * ve(e);
  return resu;
}
void Terme_Source_Decroissance_Radioactive_P0_PolyMAC::associer_pb (const Probleme_base &) [inline, virtual]
Implements Source_base.
Definition at line 54 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.h.
{ };
void Terme_Source_Decroissance_Radioactive_P0_PolyMAC::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) [protected, virtual]
Implements Source_base.
Definition at line 69 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
References Cerr, finl, la_zone_PolyMAC, ref_cast, and Deriv_Zone_dis_base::valeur().
{
  Cerr << " Terme_Source_Decroissance_Radioactive_P0_PolyMAC::associer_zones " << finl ;
  la_zone_PolyMAC = ref_cast(Zone_PolyMAC, zone_dis.valeur());
}
DoubleTab & Terme_Source_Decroissance_Radioactive_P0_PolyMAC::calculer (DoubleTab & resu) const [virtual]
Reimplemented from Source_base.
Definition at line 89 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
References ajouter().
{
  resu=0;
  ajouter(resu);
  return resu;
}
void Terme_Source_Decroissance_Radioactive_P0_PolyMAC::completer (void) [virtual]
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
Definition at line 58 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
References Cerr, MorEqn::equation(), Process::exit(), finl, Equation_base::inconnue(), DoubleVect::line_size(), nb_groupes, and Champ_Inc::valeurs().
{
  Source_base::completer();
  const int N = equation().inconnue().valeurs().line_size();
  if (N != nb_groupes)
    {
      Cerr << "Terme_Source_Decroissance_Radioactive_P0_PolyMAC : inconsistency between the number of radioactive decay constants ( " << nb_groupes << " ) and the number of components of the unknown of the equation ( " << N << " )" << finl;
      Process::exit();
    }
}
void Terme_Source_Decroissance_Radioactive_P0_PolyMAC::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const [virtual]
contribution a la matrice implicite des termes sources
par defaut pas de contribution
Reimplemented from Source_base.
Definition at line 96 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
References la_zone_PolyMAC, lambda, Zone_dis_base::nb_elem(), nb_groupes, Ref_Zone_PolyMAC::valeur(), and Zone_VF::volumes().
{
  int nb_elem = la_zone_PolyMAC.valeur().nb_elem();
  const Zone_VF& zone = la_zone_PolyMAC.valeur();
  const DoubleVect& ve = zone.volumes();
  for (int e = 0, k = 0; e < nb_elem; e++) for (int l = 0; l < nb_groupes; l++, k++)
      matrice(k, k) += lambda[l] * ve(e);
}
Objet_U * Terme_Source_Decroissance_Radioactive_P0_PolyMAC::cree_instance () [static]
Definition at line 29 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
int Terme_Source_Decroissance_Radioactive_P0_PolyMAC::duplique () const [virtual]
Implements Source_base.
Definition at line 29 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
const Type_info * Terme_Source_Decroissance_Radioactive_P0_PolyMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 29 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
const Type_info * Terme_Source_Decroissance_Radioactive_P0_PolyMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 29 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
void Terme_Source_Decroissance_Radioactive_P0_PolyMAC::mettre_a_jour (double temps) [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 53 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.h.
{ };
Sortie & Terme_Source_Decroissance_Radioactive_P0_PolyMAC::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 35 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je();
}
Entree & Terme_Source_Decroissance_Radioactive_P0_PolyMAC::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 43 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
References Cerr, finl, lambda, and nb_groupes.
{
  double lambda_tmp;
  s >> nb_groupes;
  Cerr << "Nombre de groupes a lire : " << nb_groupes << finl;
  for (int i = 0; i < nb_groupes; i++)
    {
      s >> lambda_tmp;
      Cerr << "lambda lu : " << lambda_tmp << finl;
      lambda.push_back(lambda_tmp);
    }
  return s ;
}
Terme_Source_Decroissance_Radioactive_P0_PolyMAC & Terme_Source_Decroissance_Radioactive_P0_PolyMAC::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Definition at line 29 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
const Terme_Source_Decroissance_Radioactive_P0_PolyMAC & Terme_Source_Decroissance_Radioactive_P0_PolyMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Definition at line 29 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
unsigned Terme_Source_Decroissance_Radioactive_P0_PolyMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 29 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp.
Member Data Documentation
const Type_info Terme_Source_Decroissance_Radioactive_P0_PolyMAC::info_obj [static]
Reimplemented from Source_base.
Definition at line 47 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.h.
Ref_Zone_PolyMAC Terme_Source_Decroissance_Radioactive_P0_PolyMAC::la_zone_PolyMAC [protected]
Definition at line 62 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.h.
Referenced by ajouter(), associer_zones(), and contribuer_a_avec().
std::vector<double> Terme_Source_Decroissance_Radioactive_P0_PolyMAC::lambda [protected]
Definition at line 60 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.h.
Referenced by ajouter(), contribuer_a_avec(), and readOn().
int Terme_Source_Decroissance_Radioactive_P0_PolyMAC::nb_groupes = 0 [protected]
Definition at line 61 of file Terme_Source_Decroissance_Radioactive_P0_PolyMAC.h.
Referenced by ajouter(), completer(), contribuer_a_avec(), and readOn().
The documentation for this class was generated from the following files:
src/PolyMAC/Sources/Terme_Source_Decroissance_Radioactive_P0_PolyMAC.h
src/PolyMAC/Sources/Terme_Source_Decroissance_Radioactive_P0_PolyMAC.cpp