TRUST: EOS_Tools_VEF Class Reference
EOS_Tools_VEF Class Reference
classe EOS_Tools_VEF
Cette classe et specifique a discretisation de type VEF.
#include <EOS_Tools_VEF.h>
Public Member Functions
EOS_Tools_VEF ()
~EOS_Tools_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const DoubleTab & rho_discvit () const override
Renvoie rho avec la meme discretisation que la vitesse :
une valeur par face en VEF.
const DoubleTab & rho_face_n () const override
const DoubleTab & rho_face_np1 () const override
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Associe les zones a l'EDO.
void divu_discvit (const DoubleTab &, DoubleTab &) override
Div(u) is computed on faces from Div(u) on elements.
double moyenne_vol (const DoubleTab &) const override
Calcule la moyenne volumique de la grandeur P1NC donnee.
void secmembre_divU_Z (DoubleTab &) const override
Calcule le second membre de l'equation de continuite pour une discretisation VEF_P1B:
div(U) = W = dZ/dT + U.grad(Z) avec Z=ln(rho)
void calculer_rho_face_np1 (const DoubleTab &rho) override
const Fluide_Dilatable_base & le_fluide () const
Public Member Functions inherited from EOS_Tools_base
EOS_Tools_base ()
~EOS_Tools_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_fluide (const Fluide_Dilatable_base &)
virtual void mettre_a_jour (double)
virtual const DoubleTab & rho_discvit () const =0
virtual const DoubleTab & rho_face_n () const =0
virtual const DoubleTab & rho_face_np1 () const =0
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void divu_discvit (const DoubleTab &, DoubleTab &)=0
virtual void secmembre_divU_Z (DoubleTab &) const =0
virtual void calculer_rho_face_np1 (const DoubleTab &rho)=0
virtual double moyenne_vol (const DoubleTab &) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static EOS_Tools_VEF & self_cast (Objet_U &)
static const EOS_Tools_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from EOS_Tools_base
static const Type_info * info ()
static EOS_Tools_base & self_cast (Objet_U &)
static const EOS_Tools_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from EOS_Tools_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VEF la_zone
Ref_Zone_Cl_dis la_zone_Cl
Protected Attributes inherited from EOS_Tools_base
Ref_Fluide_Dilatable_base le_fluide_
Detailed Description
classe EOS_Tools_VEF
Cette classe et specifique a discretisation de type VEF.
Definition at line 34 of file EOS_Tools_VEF.h.
Constructor & Destructor Documentation
EOS_Tools_VEF()
EOS_Tools_VEF::EOS_Tools_VEF ()
Definition at line 28 of file EOS_Tools_VEF.cpp.
~EOS_Tools_VEF()
EOS_Tools_VEF::~EOS_Tools_VEF ()
Definition at line 28 of file EOS_Tools_VEF.cpp.
Member Function Documentation
associer_zones()
void EOS_Tools_VEF::associer_zones (const Zone_dis & zone, const Zone_Cl_dis & zone_cl) override virtual
Associe les zones a l'EDO.
Implements EOS_Tools_base.
Definition at line 60 of file EOS_Tools_VEF.cpp.
{
  la_zone = ref_cast(Zone_VEF,zone.valeur());
  la_zone_Cl = zone_cl;
}
References la_zone, la_zone_Cl, ref_cast, and Deriv_Zone_dis_base::valeur().
calculer_rho_face_np1()
void EOS_Tools_VEF::calculer_rho_face_np1 (const DoubleTab & rho) inline override virtual
Implements EOS_Tools_base.
Definition at line 45 of file EOS_Tools_VEF.h.
{ /* Do nothing */ }
cree_instance()
Objet_U * EOS_Tools_VEF::cree_instance () static
Definition at line 28 of file EOS_Tools_VEF.cpp.
divu_discvit()
void EOS_Tools_VEF::divu_discvit (const DoubleTab & DivVelocityElements, DoubleTab & DivVelocityFaces) override virtual
Div(u) is computed on faces from Div(u) on elements.
Implements EOS_Tools_base.
Definition at line 125 of file EOS_Tools_VEF.cpp.
{
  assert_espace_virtuel_vect(DivVelocityElements);
// Corrections pour moyenner div(u) sur les faces
  const DoubleVect& volumes = la_zone->volumes();
  const DoubleVect& volumes_entrelaces = la_zone->volumes_entrelaces();
  const DoubleVect& volumes_entrelaces_Cl = ref_cast(Zone_Cl_VEF,la_zone_Cl->valeur()).volumes_entrelaces_Cl();
  IntTab& face_voisins = la_zone->face_voisins();
  int premiere_fac_std=la_zone->premiere_face_std();
// remplissage de div(u) sur les faces
  for (int face=0; face<premiere_fac_std; face++)
    {
      int nb_comp=0;
      DivVelocityFaces(face)=0;
      for (int i=0 ; i<2 ; i++)
        {
          int elem= face_voisins(face,i);
          if (elem!=-1)
            {
              nb_comp++;
              DivVelocityFaces(face) += DivVelocityElements(elem)*(volumes_entrelaces_Cl(face)/volumes(elem));
            }
        }
      DivVelocityFaces(face) /= nb_comp;
    }
  int size = la_zone->nb_faces();
  for (int face=premiere_fac_std; face<size; face++)
    {
      int nb_comp=0;
      DivVelocityFaces(face)=0;
      for (int i=0 ; i<2 ; i++)
        {
          int elem= face_voisins(face,i);
          if (elem!=-1)
            {
              nb_comp++;
              DivVelocityFaces(face) += DivVelocityElements(elem)*(volumes_entrelaces(face)/volumes(elem));
            }
        }
      DivVelocityFaces(face) /= nb_comp;
    }
}
References assert_espace_virtuel_vect(), Zone_VF::face_voisins(), la_zone, la_zone_Cl, Zone_VF::nb_faces(), Zone_VEF::premiere_face_std(), ref_cast, Deriv_Zone_Cl_dis_base::valeur(), Zone_VF::volumes(), and Zone_VF::volumes_entrelaces().
duplique()
int EOS_Tools_VEF::duplique () const override virtual
Implements Objet_U.
Definition at line 28 of file EOS_Tools_VEF.cpp.
get_info()
const Type_info * EOS_Tools_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from EOS_Tools_base.
Definition at line 28 of file EOS_Tools_VEF.cpp.
info()
const Type_info * EOS_Tools_VEF::info () static
Definition at line 28 of file EOS_Tools_VEF.cpp.
le_fluide()
const Fluide_Dilatable_base & EOS_Tools_VEF::le_fluide () const inline
Definition at line 46 of file EOS_Tools_VEF.h.
{ return le_fluide_.valeur(); }
References EOS_Tools_base::le_fluide_, and Ref_Fluide_Dilatable_base::valeur().
Referenced by secmembre_divU_Z().
moyenne_vol()
double EOS_Tools_VEF::moyenne_vol (const DoubleTab & tab) const override virtual
Calcule la moyenne volumique de la grandeur P1NC donnee.
Returns
DoubleTab&
Signification: rho discretise par face
Contraintes:
Implements EOS_Tools_base.
Definition at line 110 of file EOS_Tools_VEF.cpp.
{
  assert(tab.line_size() == 1);
  double x = Champ_P1NC::calculer_integrale_volumique(la_zone.valeur(), tab, FAUX_EN_PERIO);
// La facon simple de faire serait celle-ci, mais c'est faux a cause de FAUX_EN_PERIO
// qui compte deux fois les volumes entrelaces des faces periodiques:
  DoubleVect un;
  la_zone.valeur().creer_tableau_faces(un, Array_base::NOCOPY_NOINIT);
  un = 1.;
  double y = Champ_P1NC::calculer_integrale_volumique(la_zone.valeur(), un, FAUX_EN_PERIO);
  return x / y;
}
References Champ_P1NC::calculer_integrale_volumique(), Zone_VF::creer_tableau_faces(), FAUX_EN_PERIO, la_zone, TRUSTVect< _TYPE_ >::line_size(), Array_base::NOCOPY_NOINIT, and Ref_Zone_VEF::valeur().
printOn()
Sortie & EOS_Tools_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from EOS_Tools_base.
Definition at line 30 of file EOS_Tools_VEF.cpp.
{
  os <<que_suis_je()<< finl;
  return os;
}
References finl, and Objet_U::que_suis_je().
readOn()
Entree & EOS_Tools_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from EOS_Tools_base.
Definition at line 36 of file EOS_Tools_VEF.cpp.
{
  return is;
}
rho_discvit()
const DoubleTab & EOS_Tools_VEF::rho_discvit () const override virtual
Renvoie rho avec la meme discretisation que la vitesse :
une valeur par face en VEF.
Returns
DoubleTab&
Signification: rho discretise par face
Contraintes:
Implements EOS_Tools_base.
Definition at line 81 of file EOS_Tools_VEF.cpp.
{
  return le_fluide_->masse_volumique().valeurs();
}
References EOS_Tools_base::le_fluide_, Milieu_base::masse_volumique(), and Champ::valeurs().
rho_face_n()
const DoubleTab & EOS_Tools_VEF::rho_face_n () const override virtual
Implements EOS_Tools_base.
Definition at line 86 of file EOS_Tools_VEF.cpp.
{
  return le_fluide_->rho_n();
}
References EOS_Tools_base::le_fluide_, and Fluide_Dilatable_base::rho_n().
rho_face_np1()
const DoubleTab & EOS_Tools_VEF::rho_face_np1 () const override virtual
Implements EOS_Tools_base.
Definition at line 91 of file EOS_Tools_VEF.cpp.
{
  return le_fluide_->rho_np1();
}
References EOS_Tools_base::le_fluide_, and Fluide_Dilatable_base::rho_np1().
secmembre_divU_Z()
void EOS_Tools_VEF::secmembre_divU_Z (DoubleTab & tab_W) const override virtual
Calcule le second membre de l'equation de continuite pour une discretisation VEF_P1B:
div(U) = W = dZ/dT + U.grad(Z) avec Z=ln(rho)
< version_originale
Implements EOS_Tools_base.
Definition at line 186 of file EOS_Tools_VEF.cpp.
{
  double dt = le_fluide().vitesse()->equation().schema_temps().pas_de_temps();
  int face, elem, som,som_glob;
  const IntTab& face_sommets = la_zone->face_sommets();
  int nb_elem_tot=la_zone->nb_elem_tot();
  int nb_som_tot=la_zone->zone().nb_som_tot();
  int nb_faces_tot=la_zone->nb_faces_tot();
  const Equation_base& eq=le_fluide().vitesse()->equation();
  DoubleTab tab_dZ;
// Dimensionnement de tab_dZ
  const Navier_Stokes_std& eqns = ref_cast(Navier_Stokes_std,eq);
  const DoubleTab& pression = eqns.pression().valeurs();
  tab_dZ = pression;
  DoubleVect tab_rhon_som(nb_som_tot);
  DoubleVect volume_int_som(nb_som_tot);
  DoubleVect tab_rhonp1_som(nb_som_tot);
  const DoubleTab& tab_rhon = le_fluide().loi_etat()->rho_n();
  const DoubleTab& tab_rhonp1 = le_fluide().loi_etat()->rho_np1();
  DoubleTab tab_rhonP1_,tab_rhonp1P1_;
  const DoubleVect& porosite_face = la_zone->porosite_face();
  const DoubleTab& tab_rhonP1=modif_par_porosite_si_flag(tab_rhon,tab_rhonP1_,1,porosite_face);
  const DoubleTab& tab_rhonp1P1=modif_par_porosite_si_flag(tab_rhonp1,tab_rhonp1P1_,1,porosite_face);
  const IntTab& elem_faces = la_zone->elem_faces();
  const DoubleVect& volumes = la_zone->volumes();
  const DoubleVect& volumes_entrelaces = la_zone->volumes_entrelaces();
  const Zone_VEF_PreP1b& zp1b=ref_cast(Zone_VEF_PreP1b,la_zone.valeur());
  const DoubleVect& volumes_controle=zp1b.volume_aux_sommets();
  double rn,rnp1;
  int nfe = la_zone->zone().nb_faces_elem();
  int nsf = la_zone->nb_som_face();
  const Domaine& dom=la_zone->zone().domaine();
// calcul de la somme des volumes entrelacees autour d'un sommet
  volume_int_som=0.;
  for (face=0 ; face<nb_faces_tot ; face++)
    for (som=0 ; som<nsf ; som++)
      {
        som_glob=dom.get_renum_som_perio(face_sommets(face,som));
        volume_int_som(som_glob)+=volumes_entrelaces(face);
      }
// discretisation de rho sur les sommets
  tab_rhon_som=0;
  tab_rhonp1_som=0;
  double pond;
  pond=1./nsf; //!< version_originale
  for (face=0 ; face<nb_faces_tot ; face++)
    {
      for (som=0 ; som<nsf ; som++)
        {
          som_glob=dom.get_renum_som_perio(face_sommets(face,som));
          pond=volumes_entrelaces(face)/volume_int_som(som_glob);
          tab_rhon_som(som_glob) += tab_rhonP1(face)*pond;
          tab_rhonp1_som(som_glob) += tab_rhonp1P1(face)*pond;
        }
    }
// Corrections pour test de la moyenne de la derivee de la masse volumique
  Debog::verifier("EOS_Tools_VEF::secmembre_divU_Z tab_dZ=",tab_dZ);
  Debog::verifier("EOS_Tools_VEF::secmembre_divU_Z tab_rhonP1=",tab_rhonP1);
  Debog::verifier("EOS_Tools_VEF::secmembre_divU_Z tab_rhonp1P1=",tab_rhonp1P1);
  Debog::verifier("EOS_Tools_VEF::secmembre_divU_Z dt=",dt);
  int decal=0;
  int p_has_elem=zp1b.get_alphaE();
  int nb_case=nb_elem_tot*p_has_elem;
  for (elem=0 ; elem<nb_case ; elem++)
    {
      rn=0;
      rnp1=0;
      for (face=0 ; face<nfe ; face++)
        {
          rn += tab_rhonP1(elem_faces(elem,face));
          rnp1 += tab_rhonp1P1(elem_faces(elem,face));
        }
      tab_dZ(elem) = (rnp1-rn)/(nfe*dt);
    }
  decal+=nb_case;
  tab_dZ.echange_espace_virtuel();
  Debog::verifier("EOS_Tools_VEF::secmembre_divU_Z tab_dZ=",tab_dZ);
  int p_has_som=zp1b.get_alphaS();
  nb_case=nb_som_tot*p_has_som;
  for (som=0 ; som<nb_case ; som++)
    tab_dZ(decal+som) = ((tab_rhonp1_som(som))-(tab_rhon_som(som)))/dt;
  decal+=nb_case;
  int p_has_arrete=zp1b.get_alphaA();
  int nb_ar_tot=la_zone->zone().nb_aretes_tot();
  nb_case=nb_ar_tot*p_has_arrete;
  for (int ar=0 ; ar<nb_case ; ar++)
    tab_dZ(decal+ar) =0;
  assert(decal+nb_case==tab_W.size_totale());
  tab_dZ.echange_espace_virtuel();
  Debog::verifier("EOS_Tools_VEF::secmembre_divU_Z tab_dZ=",tab_dZ);
  double coefdivelem=1,coefdivsom=1;
  decal=0;
  nb_case=nb_elem_tot*p_has_elem;
  for (elem=0 ; elem<nb_case ; elem++)
    tab_W(elem) = -coefdivelem*tab_dZ(elem) * volumes(elem);
  Debog::verifier("EOS_Tools_VEF::secmembre_divU_Z tabW elem",tab_W);
  decal+=nb_case;
  nb_case=nb_som_tot*p_has_som;
  for (som=0 ; som<nb_case ; som++)
    tab_W(decal+som) = -coefdivsom*tab_dZ(decal+som)*volumes_controle(som)*1;
  decal+=nb_case;
  nb_case=nb_ar_tot*p_has_arrete;
  for (int ar=0 ; ar<nb_case ; ar++)
    {
// pour l'instant on n'a pas calcule tab_dZ aux aretes
      assert(tab_dZ(decal+ar)==0);
      tab_W(decal+ar) =0;
    }
  assert(decal+nb_case==tab_W.size_totale());
  tab_W.echange_espace_virtuel();
  Debog::verifier("EOS_Tools_VEF::secmembre_divU_Z tab_W=",tab_W);
}
References Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), Zone_VF::face_sommets(), Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Domaine::get_renum_som_perio(), la_zone, le_fluide(), Fluide_Dilatable_base::loi_etat(), modif_par_porosite_si_flag(), Zone::nb_aretes_tot(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Zone_VF::nb_faces_tot(), Zone_VF::nb_som_face(), Zone::nb_som_tot(), Zone_VF::porosite_face(), Navier_Stokes_std::pression(), ref_cast, TRUSTVect< _TYPE_ >::size_totale(), Ref_Zone_VEF::valeur(), Champ_Inc::valeurs(), Debog::verifier(), Fluide_Dilatable_base::vitesse(), Zone_VEF_PreP1b::volume_aux_sommets(), Zone_VF::volumes(), Zone_VF::volumes_entrelaces(), and Zone_dis_base::zone().
self_cast() [1/2]
const EOS_Tools_VEF & EOS_Tools_VEF::self_cast (const Objet_U & r) static
Definition at line 28 of file EOS_Tools_VEF.cpp.
self_cast() [2/2]
EOS_Tools_VEF & EOS_Tools_VEF::self_cast (Objet_U & r) static
Definition at line 28 of file EOS_Tools_VEF.cpp.
taille_memoire()
unsigned EOS_Tools_VEF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 28 of file EOS_Tools_VEF.cpp.
Member Data Documentation
info_obj
const Type_info EOS_Tools_VEF::info_obj static
Definition at line 36 of file EOS_Tools_VEF.h.
la_zone
Ref_Zone_VEF EOS_Tools_VEF::la_zone protected
Definition at line 49 of file EOS_Tools_VEF.h.
Referenced by associer_zones(), divu_discvit(), moyenne_vol(), and secmembre_divU_Z().
la_zone_Cl
Ref_Zone_Cl_dis EOS_Tools_VEF::la_zone_Cl protected
Definition at line 50 of file EOS_Tools_VEF.h.
Referenced by associer_zones(), and divu_discvit().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/VEF/EOS_Tools_VEF.h
src/ThHyd/Dilatable/Common/VEF/EOS_Tools_VEF.cpp