TRUST: Zone_Poly_base Class Reference
Zone_Poly_base Class Reference
class Zone_Poly_base
Classe instanciable qui derive de Zone_VF.
Cette classe contient les informations geometriques que demande
la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
La classe porte un certain nombre d'informations concernant les faces
Dans cet ensemble de faces on fait figurer aussi les faces du bord et
des joints. Pour manipuler les faces on distingue 2 categories:
- les faces non standard qui sont sur un joint, un bord ou qui sont
internes tout en appartenant a un element du bord
- les faces standard qui sont les faces internes n'appartenant pas
a un element du bord
Cette distinction correspond au traitement des conditions aux limites:les
faces standard ne "voient pas" les conditions aux limites.
L'ensemble des faces est numerote comme suit:
- les faces qui sont sur une Zone_joint apparaissent en premier
(dans l'ordre du vecteur les_joints)
- les faces qui sont sur une Zone_bord apparaissent ensuite
(dans l'ordre du vecteur les_bords)
- les faces internes non standard apparaissent ensuite
- les faces internes standard en dernier
Finalement on trouve regroupees en premier toutes les faces non standard
qui vont necessiter un traitement particulier
On distingue deux types d'elements
- les elements non standard : ils ont au moins une face de bord
- les elements standard : ils n'ont pas de face de bord
Les elements standard (resp. les elements non standard) ne sont pas ranges
de maniere consecutive dans l'objet Zone. On utilise le tableau
rang_elem_non_std pour acceder de maniere selective a l'un ou
l'autre des types d'elements
#include <Zone_Poly_base.h>
Public Member Functions
Zone_Poly_base ()
~Zone_Poly_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void typer_elem (Zone &zone_geom) override
void discretiser () override
void reordonner (Faces &) override
Methode appelee par Zone_VF::discretiser apres la creation
des faces reelles.
On reordonne les faces de sorte a placer les faces "non standard"
au debut de la liste des faces. Les faces non standard sont celles
dont les volumes de controles sont modifies par les conditions aux
limites.
void modifier_pour_Cl (const Conds_lim &) override
const Elem_poly & type_elem () const
int nb_elem_Cl () const
int nb_faces_joint () const
int nb_faces_std () const
int nb_elem_std () const
double carre_pas_du_maillage () const
double carre_pas_maille (int i) const
double face_normales (int, int) const override
DoubleTab & face_normales ()
const DoubleTab & face_normales () const
IntVect & rang_elem_non_std ()
const IntVect & rang_elem_non_std () const
int oriente_normale (int face_opp, int elem2) const
const ArrOfInt & ind_faces_virt_non_std () const
void calculer_h_carre ()
DoubleTab & volumes_entrelaces_dir ()
const DoubleTab & volumes_entrelaces_dir () const
double dot (const double *a, const double *b, const double *ma=NULL, const double *mb=NULL) const
double nu_dot (const DoubleTab *nu, int e, int n, const double *a, const double *b, const double *ma=NULL, const double *mb=NULL) const
std::array< double, 3 > cross (int dima, int dimb, const double *a, const double *b, const double *ma=NULL, const double *mb=NULL) const
double dist_norm (int num_face) const
double dist_norm_bord (int num_face) const
DoubleVect & dist_norm_bord (DoubleVect &, const Nom &nom_bord) const
double dist_face_elem0 (int num_face, int n0) const
double dist_face_elem1 (int num_face, int n1) const
double dist_face_elem0_period (int num_face, int n0, double l) const
double dist_face_elem1_period (int num_face, int n1, double l) const
void detecter_faces_non_planes () const
void init_equiv () const
void init_som_elem () const
void init_dist_paroi_globale (const Conds_lim &conds_lim) override
const DoubleTab & normale_paroi_elem () const
const DoubleTab & normale_paroi_faces () const
Public Member Functions inherited from Zone_VF
Zone_VF ()
~Zone_VF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double face_normales (int, int) const =0
void calculer_face_surfaces (const DoubleVect &surfaces)
virtual const DoubleVect & face_surfaces () const
virtual double face_surfaces (int i) const
virtual double surface (int i) const
void discretiser () override
Genere les faces
construits les frontieres.
void infobord ()
void info_elem_som ()
void calculer_porosites ()
void calculer_diametres_hydrauliques ()
void calculer_sections_passage ()
void calculer_coefficient_echange_thermique ()
void calculer_coefficient_frottement ()
void marquer_faces_double_contrib (const Conds_lim &)
virtual void typer_elem (Zone &)
virtual void remplir_face_voisins_fictifs (const Zone_Cl_dis_base &)
virtual Faces * creer_faces ()
renvoie new(Faces) !
elle est surchargee par Zone_VDF par ex.
virtual void reordonner (Faces &)
cette methode ne fait rien
elle est surchargee par Zone_VDF par ex.
int nb_joints () const
renvoie le nombre de joints
int premiere_face_int () const
une face est interne ssi elle separe deux elements.
renvoie le numero de la premiere face interne.
int nb_faces () const
renvoie le nombre global de faces.
int nb_faces_tot () const
renvoie le nombre total de faces.
C'est-a-dire faces reelles + faces virtuelles
int nb_som_face () const
renvoie le nombre de sommets par face.
Rque : on a suppose que toutes les faces avait
le meme nombre de sommet ce qui exclue des elements
comme le prisme.
int nb_faces_bord () const
renvoie le nombre de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_bord_tot () const
renvoie le nombre total de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int premiere_face_bord () const
renvoie le numero de la premiere des faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_internes () const
une face est interne ssi elle separe deux elements.
renvoie le nombre de faces internes.
double xv (int, int) const
double xp (int, int) const
double xa (int, int) const
double porosite_face (int) const
double porosite_elem (int) const
double diametre_hydraulique_face (int) const
double section_passage_face (int) const
double coefficient_frottement (int) const
double coefficient_echange_thermique (int) const
int face_numero_bord (int num_face) const
IntTab & face_numero_bord ()
const IntTab & face_numero_bord () const
void remplir_face_numero_bord ()
virtual const IntVect & orientation () const
virtual int orientation (int) const
virtual int orientation_si_definie (int) const
DoubleTab normalized_boundaries_outward_vector (int global_face_number, double scale_factor) const
Compute the normalized boundary outward vector associated to the face global_face_number
and eventually scaled by scale_factor.
DoubleTab & xv ()
const DoubleTab & xv () const
DoubleTab & xp ()
const DoubleTab & xp () const
DoubleTab & xa ()
const DoubleTab & xa () const
DoubleVect & volumes_entrelaces ()
const DoubleVect & volumes_entrelaces () const
double volumes_entrelaces (int num_face) const
const DoubleTab & volumes_entrelaces_dir () const
DoubleTab & volumes_entrelaces_dir ()
DoubleVect & porosite_face ()
const DoubleVect & porosite_face () const
DoubleVect & porosite_elem ()
const DoubleVect & porosite_elem () const
DoubleVect & diametre_hydraulique_face ()
const DoubleVect & diametre_hydraulique_face () const
const DoubleVect section_passage_face () const
DoubleTab & diametre_hydraulique_elem ()
const DoubleTab & diametre_hydraulique_elem () const
DoubleVect & coefficient_frottement ()
const DoubleVect & coefficient_frottement () const
DoubleVect & coefficient_echange_thermique ()
const DoubleVect & coefficient_echange_thermique () const
const Joint & joint (int i) const
renvoie le ieme joint.
Joint & joint (int i)
renvoie le ieme joint.
Frontiere_dis_base & frontiere_dis (int) override
renvoie la ieme frontiere_discrete.
const Frontiere_dis_base & frontiere_dis (int) const override
renvoie la ieme frontiere_discrete.
int nb_frontiere_dis () const
const Front_VF & front_VF (int) const
renvoie la ieme frontiere_discrete.
double volumes (int i) const
renvoie le volume de la maille i.
double inverse_volumes (int i) const
int face_voisins (int num_face, int i) const
renvoie l'element voisin de numface dans la direction i.
i=0 : dans le sens oppose de l'axe orthogonal a la face numface.
i=1 : dans le sens de l'axe orthogonal a la face numface.
exemple :
| 0 | 1 |
numface
renvoie -1 si l'element n'existe pas (au bord).
int elem_faces (int i, int j) const
renvoie le numero de le ieme face de la maille num_elem
la facon dont ces faces sont numerotees est
laisse a la responsabilite des classes derivees
int face_sommets (int i, int j) const
renvoie le numero du ieme sommet de la face num_face.
DoubleVect & volumes ()
renvoie le tableaux des volumes des mailles.
DoubleVect & inverse_volumes ()
Tableau pour optimiser le code.
const DoubleVect & volumes () const
renvoie le tableaux des volumes des mailles.
const DoubleVect & inverse_volumes () const
Tableau pour optimiser le code.
IntTab & face_voisins () override
renvoie le tableaux des volumes des connectivites face elements
cf au dessus.
const IntTab & face_voisins () const override
cf au dessus.
const IntTab & face_voisins_fictifs () const
void face_voisins_reel_fictif (int face, int &el0, int &elf) const
renvoie dans el0 le numero de l'elt a l'interieur
renvoie dans elf le numero de l'elt fictif (-1 si il n'existe pas)
IntTab & elem_faces ()
renvoie le tableau de connectivite element/faces
const IntTab & elem_faces () const
cf au dessus.
ArrOfInt & faces_doubles ()
renvoie 1 pour les faces appartenant a un bord perio ou un item commun, 0 par defaut
const ArrOfInt & faces_doubles () const
cf au dessus
IntTab & face_sommets () override
renvoie le tableau de connectivite faces/sommets.
const IntTab & face_sommets () const override
cf au dessus.
void modifier_pour_Cl (const Conds_lim &) override
int numero_face_local (int face, int elem) const
int numero_sommet_local (int som, int elem) const
const IntTab & get_num_fac_loc () const
int get_num_fac_loc (int, int) const
void construire_num_fac_loc ()
const ArrOfInt & ind_faces_virt_bord () const
int est_une_face_virt_bord (int) const
renvoie 1 si face est une face virtuelle de bord, 0 sinon
int fbord (int f) const
void construire_face_virt_pe_num ()
Remplissage du tableau face_virt_pe_num_ (voir commentaire dans Zone_VF.h)
const IntTab & face_virt_pe_num () const
virtual void creer_tableau_faces (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_aretes (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_faces_bord (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual const MD_Vector & md_vector_faces_bord () const
virtual const MD_Vector & md_vector_faces () const
virtual const MD_Vector & md_vector_aretes () const
virtual const DoubleTab & xv_bord () const
Public Member Functions inherited from Zone_dis_base
Zone_dis_base ()
~Zone_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Associe une Zone a l'objet.
const Zone & zone () const
Renvoie la Zone associee a l'objet.
(version const)
Zone & zone ()
Renvoie la Zone associee a l'objet.
void associer_domaine_dis (const Domaine_dis &)
Associe un Domaine_dis a l'objet.
const Domaine_dis & domaine_dis () const
Domaine_dis & domaine_dis ()
virtual void discretiser ()=0
virtual void creer_elements_fictifs (const Zone_Cl_dis_base &)
virtual Frontiere_dis_base & frontiere_dis (int)=0
virtual const Frontiere_dis_base & frontiere_dis (int) const =0
int rang_frontiere (const Nom &)
int rang_frontiere (const Nom &) const
Renvoie le rang de la frontiere de Nom nom
Renvoie -1 si aucune frontiere ne s'appelle nom.
Frontiere_dis_base & frontiere_dis (const Nom &)
const Frontiere_dis_base & frontiere_dis (const Nom &) const
Renvoie la frontiere de Nom nom.
(On indexe les frontiere avec leur nom)
void ecrire_noms_bords (Sortie &) const
Ecriture des noms des bords sur un flot de sortie.
virtual void modifier_pour_Cl (const Conds_lim &)=0
virtual IntTab & face_sommets ()
virtual const IntTab & face_sommets () const
virtual IntTab & face_voisins ()
virtual const IntTab & face_voisins () const
int nb_elem () const
int nb_elem_tot () const
int nb_som () const
int nb_som_tot () const
int nb_front_Cl () const
virtual void init_dist_paroi_globale (const Conds_lim &conds_lim)
virtual const DoubleTab & y_elem () const
virtual const DoubleTab & y_faces () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Zone_Poly_base & self_cast (Objet_U &)
static const Zone_Poly_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_VF
static const Type_info * info ()
static Zone_VF & self_cast (Objet_U &)
static const Zone_VF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_dis_base
static const Type_info * info ()
static Zone_dis_base & self_cast (Objet_U &)
static const Zone_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
std::map< std::string, int > is_init
IntTab equiv
Static_Int_Lists som_elem
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Zone_VF
static const Type_info info_obj
Static Public Attributes inherited from Zone_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
void remplir_elem_faces () override
Sortie & ecrit (Sortie &os) const
void creer_faces_virtuelles_non_std ()
Protected Member Functions inherited from Zone_VF
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
virtual void remplir_elem_faces ()=0
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double h_carre
carre du pas du maillage
DoubleVect h_carre_
carre du pas d'une maille
Elem_poly type_elem_
type de l'element de discretisation
DoubleTab face_normales_
normales aux faces
int nb_faces_std_
nombre de faces standard
int nb_elem_std_
nombre d'elements standard
IntVect rang_elem_non_std_
rang_elem_non_std_= -1 si l'element est standard rang_elem_non_std_= rang de l'element dans les tableaux relatifs aux elements non standards
ArrOfInt ind_faces_virt_non_std_
contient les indices des faces virtuelles non standard
DoubleTab n_y_elem_
vecteur normal entre le bord le plus proche et l'element
DoubleTab n_y_faces_
vecteur normal entre le bord le plus proche et la face
Protected Attributes inherited from Zone_VF
DoubleVect volumes_
volumes des elements
DoubleVect inverse_volumes_
inverse du volumes des elements
DoubleVect volumes_entrelaces_
volumes entrelaces pour l'integration des Qdm
DoubleTab volumes_entrelaces_dir_
volumes entrelaces par cote
DoubleVect porosite_elem_
Porosites volumiques pour les volumes de controle de masse.
DoubleVect porosite_face_
Porosites surfaciques en masse et volumiques.
DoubleVect diametre_hydraulique_face_
DoubleTab diametre_hydraulique_elem_
DoubleVect coefficient_echange_thermique_
remplissage des coefficients d'echange_thermique
DoubleVect coefficient_frottement_
remplissage des coefficient de frottement
IntTab face_voisins_
connectivite face/elements
IntTab face_voisins_fictifs_
connectivite face/elements fictifs
DoubleTab xp_
centres de gravite des elements
DoubleTab xv_
centres de gravite des faces
DoubleTab xv_bord_
IntTab elem_faces_
connectivite element/faces
IntTab face_sommets_
sommets des faces
DoubleTab xa_
centres de gravite des aretes
IntTab face_numero_bord_
connectivite face/numero_bord
MD_Vector md_vector_faces_
MD_Vector md_vector_faces_front_
MD_Vector md_vector_aretes_
Vect_Front_VF les_bords_
IntTab num_fac_loc_
ArrOfInt faces_doubles_
faces a double contribution (faces periodiques et items communs)
IntTab face_virt_pe_num_
Protected Attributes inherited from Zone_dis_base
Ref_Zone la_zone
Ref_Domaine_dis le_domaine_dis
DoubleTab y_elem_
DoubleTab y_faces_
int dist_paroi_initialisee_ = 0
Detailed Description
class Zone_Poly_base
Classe instanciable qui derive de Zone_VF.
Cette classe contient les informations geometriques que demande
la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
La classe porte un certain nombre d'informations concernant les faces
Dans cet ensemble de faces on fait figurer aussi les faces du bord et
des joints. Pour manipuler les faces on distingue 2 categories:
- les faces non standard qui sont sur un joint, un bord ou qui sont
internes tout en appartenant a un element du bord
- les faces standard qui sont les faces internes n'appartenant pas
a un element du bord
Cette distinction correspond au traitement des conditions aux limites:les
faces standard ne "voient pas" les conditions aux limites.
L'ensemble des faces est numerote comme suit:
- les faces qui sont sur une Zone_joint apparaissent en premier
(dans l'ordre du vecteur les_joints)
- les faces qui sont sur une Zone_bord apparaissent ensuite
(dans l'ordre du vecteur les_bords)
- les faces internes non standard apparaissent ensuite
- les faces internes standard en dernier
Finalement on trouve regroupees en premier toutes les faces non standard
qui vont necessiter un traitement particulier
On distingue deux types d'elements
- les elements non standard : ils ont au moins une face de bord
- les elements standard : ils n'ont pas de face de bord
Les elements standard (resp. les elements non standard) ne sont pas ranges
de maniere consecutive dans l'objet Zone. On utilise le tableau
rang_elem_non_std pour acceder de maniere selective a l'un ou
l'autre des types d'elements
Definition at line 77 of file Zone_Poly_base.h.
Constructor & Destructor Documentation
Zone_Poly_base()
Zone_Poly_base::Zone_Poly_base ()
Definition at line 67 of file Zone_Poly_base.cpp.
~Zone_Poly_base()
Zone_Poly_base::~Zone_Poly_base () override
Definition at line 67 of file Zone_Poly_base.cpp.
Member Function Documentation
calculer_h_carre()
void Zone_Poly_base::calculer_h_carre ()
Definition at line 533 of file Zone_Poly_base.cpp.
{
// Calcul de h_carre
  h_carre = 1.e30;
  h_carre_.resize(nb_faces());
// Calcul des surfaces
  const DoubleVect& surfaces=face_surfaces();
  const int nb_faces_elem=zone().nb_faces_elem();
  const int nbe=nb_elem();
  for (int num_elem=0; num_elem<nbe; num_elem++)
    {
      double surf_max = 0;
      for (int i=0; i<nb_faces_elem; i++)
        {
          double surf = surfaces(elem_faces(num_elem,i));
          surf_max = (surf > surf_max)? surf : surf_max;
        }
      double vol = volumes(num_elem)/surf_max;
      vol *= vol;
      h_carre_(num_elem) = vol;
      h_carre = ( vol < h_carre )? vol : h_carre;
    }
}
References Zone_VF::elem_faces(), Zone_VF::face_surfaces(), h_carre, h_carre_, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), TRUSTVect< _TYPE_ >::resize(), Zone_VF::volumes(), and Zone_dis_base::zone().
carre_pas_du_maillage()
double Zone_Poly_base::carre_pas_du_maillage () const inline
Definition at line 247 of file Zone_Poly_base.h.
{
  return h_carre;
}
References h_carre.
carre_pas_maille()
double Zone_Poly_base::carre_pas_maille (int i) const inline
Definition at line 94 of file Zone_Poly_base.h.
  {
    return h_carre_(i);
  };
References h_carre_.
creer_faces_virtuelles_non_std()
void Zone_Poly_base::creer_faces_virtuelles_non_std () protected
cross()
std::array< double, 3 > Zone_Poly_base::cross (int dima, int dimb, const double * a, const double * b, const double * ma = NULL, const double * mb = NULL) const inline
Definition at line 284 of file Zone_Poly_base.h.
{
  std::array<double, 3> va = {{ 0, 0, 0 }}, vb = {{ 0, 0, 0 }}, res;
  for (int i = 0; i < dima; i++) va[i] = a[i] - (ma ? ma[i] : 0);
  for (int i = 0; i < dimb; i++) vb[i] = b[i] - (mb ? mb[i] : 0);
  for (int i = 0; i < 3; i++) res[i] = va[(i + 1) % 3] * vb[(i + 2) % 3] - va[(i + 2) % 3] * vb[(i + 1) % 3];
  return res;
}
Referenced by Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Zone_PolyMAC_P0::fgrad(), Zone_PolyMAC::M1(), Zone_PolyMAC::orthocentrer(), and Zone_PolyMAC::W1().
detecter_faces_non_planes()
void Zone_Poly_base::detecter_faces_non_planes () const
Definition at line 508 of file Zone_Poly_base.cpp.
{
  const IntTab& f_e = face_voisins(), &f_s = face_sommets_;
  const DoubleTab& xs = zone().domaine().coord_sommets(), &nf = face_normales_;
  const DoubleVect& fs = face_surfaces();
  int i, j, f, s, rk = Process::me(), np = Process::nproc();
  double sin2;
  ArrOfDouble val(np); //sur chaque proc : { cos^2 max, indice de face, indices d'elements }
  IntTab face(np), elem1(np), elem2(np);
// sur chaque proc : on cherche l'angle le plus grand entre un sommet et le plan de sa face
  for (f = 0; f < nb_faces(); f++)
    for (i = 0; i < f_s.dimension(1) && (s = f_s(f, i)) >= 0; i++)
      if ((sin2 = std::pow(dot(&xs(s, 0), &nf(f, 0), &xv_(f, 0)) / fs(f), 2) / dot(&xs(s, 0), &xs(s, 0), &xv_(f, 0), &xv_(f, 0))) > val[rk])
        val[rk] = sin2, face(rk) = f, elem1(rk) = f_e(f, 0), elem2(rk) = f_e(f, 1);
  envoyer_all_to_all(val, val), envoyer_all_to_all(face, face), envoyer_all_to_all(elem1, elem1), envoyer_all_to_all(elem2, elem2);
  for (i = j = sin2 = 0; i < Process::nproc(); i++)
    if (val[i] > sin2) sin2 = val[i], j = i;
  double theta = asin(sqrt(sin2)) * 180 / M_PI;
  Cerr << "Zone_Poly_base : angle sommet/face max " << theta << " deg (proc " << j << " , face ";
  Cerr << face(j) << " , elems " << elem1(j) << " / " << elem2(j) << " )" << finl;
  if (theta > 1) Cerr << "Zone_Poly_base : non-planar face detected ! Please fix your mesh or call 911 ..." << finl, Process::exit();
}
References Cerr, Domaine::coord_sommets(), Zone::domaine(), dot(), envoyer_all_to_all(), Process::exit(), face_normales_, Zone_VF::face_sommets_, Zone_VF::face_surfaces(), Zone_VF::face_voisins(), finl, M_PI, Process::me(), Zone_VF::nb_faces(), Process::nproc(), Zone_VF::xv_, and Zone_dis_base::zone().
Referenced by discretiser().
discretiser()
void Zone_Poly_base::discretiser () override virtual
Implements Zone_dis_base.
Reimplemented in Zone_PolyMAC, and Zone_PolyMAC_P0.
Definition at line 322 of file Zone_Poly_base.cpp.
{
  Zone& zone_geom=zone();
  typer_elem(zone_geom);
  Elem_geom_base& elem_geom = zone_geom.type_elem().valeur();
  Zone_VF::discretiser();
// Correction du tableau facevoisins:
// A l'issue de Zone_VF::discretiser(), les elements voisins 0 et 1 d'une
// face sont les memes sur tous les processeurs qui possedent la face.
// Si la face est virtuelle et qu'un des deux elements voisins n'est
// pas connu (il n'est pas dans l'epaisseur du joint), l'element voisin
// vaut -1. Cela peut etre un voisin 0 ou un voisin 1.
// On corrige les faces virtuelles pour que, si un element voisin n'est
// pas connu, alors il est voisin1. Le voisin0 est donc toujours valide.
  {
    IntTab& face_vois = face_voisins();
    const int debut = nb_faces();
    const int fin   = nb_faces_tot();
    for (int i = debut; i < fin; i++)
      {
        if (face_voisins(i, 0) == -1)
          {
            face_vois(i, 0) = face_vois(i, 1);
            face_vois(i, 1) = -1;
          }
      }
  }
// Verification de la coherence entre l'element geometrique et
// l'elemnt de discretisation
  if (sub_type(Segment_poly,type_elem_.valeur()))
    {
      if (!sub_type(Segment,elem_geom))
        {
          Cerr << " The type of the element " << elem_geom.que_suis_je() << " is incorrect" << finl;
          Process::exit();
        }
    }
  else if (sub_type(Tri_poly,type_elem_.valeur()))
    {
      if (!sub_type(Triangle,elem_geom))
        {
          Cerr << " The type of the element " << elem_geom.que_suis_je() << " is incorrect" << finl;
          Cerr << " Only the Triangle type is compatible with the PolyMAC_P0 discretisation in dimension 2" << finl;
          Cerr << " You must triangulate the domain when using the TRUST mesher" ;
          Cerr << " This can be done by adding : Trianguler nom_dom" << finl;
          Process::exit();
        }
    }
  else if (sub_type(Tetra_poly,type_elem_.valeur()))
    {
      if (!sub_type(Tetraedre,elem_geom))
        {
          Cerr << " The type of the element " << elem_geom.que_suis_je() << " is incorrect" << finl;
          Cerr << " Only the Tetrahedral type is compatible with the PolyMAC_P0 discretisation in dimension 3" << finl;
          Cerr << " You must tetrahedrize the domain when using the TRUST mesher" ;
          Cerr << " This can be done by adding : Tetraedriser nom_dom" << finl;
          Process::exit();
        }
    }
  else if (sub_type(Quadri_poly,type_elem_.valeur()))
    {
      if (!sub_type(Quadrangle_VEF,elem_geom))
        {
          Cerr << " The type of the element " << elem_geom.que_suis_je() << " is incorrect" << finl;
          Process::exit();
        }
    }
  else if (sub_type(Hexa_poly,type_elem_.valeur()))
    {
      if (!sub_type(Hexaedre_VEF,elem_geom))
        {
          Cerr << " The type of the element " << elem_geom.que_suis_je() << " is incorrect" << finl;
          Process::exit();
        }
    }
  int num_face;
// On remplit le tableau face_normales_;
// Attention : le tableau face_voisins n'est pas exactement un
// tableau distribue. Une face n'a pas ses deux voisins dans le
// meme ordre sur tous les processeurs qui possedent la face.
// Donc la normale a la face peut changer de direction d'un
// processeur a l'autre, y compris pour les faces de joint.
  {
    const int n = nb_faces();
    face_normales_.resize(n, dimension);
// const Domaine & dom = zone().domaine();
// Scatter::creer_tableau_distribue(dom, Joint::FACE, face_normales_);
    creer_tableau_faces(face_normales_);
    const IntTab& face_som = face_sommets();
    IntTab& face_vois = face_voisins();
    const IntTab& elem_face = elem_faces();
    const int n_tot = nb_faces_tot();
    for (num_face = 0; num_face < n_tot; num_face++)
      {
        type_elem_.normale(num_face,
                           face_normales_,
                           face_som, face_vois, elem_face, zone_geom);
      }
    DoubleTab old(face_normales_);
    face_normales_.echange_espace_virtuel();
    for (num_face = 0; num_face < n_tot; num_face++)
      {
        int id=1;
        for (int d=0; d<dimension; d++)
          if (!est_egal(old(num_face,d),face_normales_(num_face,d)))
            {
              id=0;
              if (!est_egal(old(num_face,d),-face_normales_(num_face,d)))
                {
                  Cerr<<"pb in faces_normales" <<finl;
                  Process::exit();
                }
            }
        if (id==0)
          {
// on a change le sens de la normale, on inverse elem1 elem2
            std::swap(face_vois(num_face,0),face_vois(num_face,1));
          }
      }
  }
  /* recalcul de xv pour avoir les vrais CG des faces */
  const DoubleTab& coords = zone().domaine().coord_sommets();
  for (int face = 0; dimension == 3 && face < nb_faces(); face++)
    {
      double xs[3] = { 0, }, S = 0;
      for (int k = 0; k < face_sommets_.dimension(1); k++)
        if (face_sommets_(face, k) >= 0)
          {
            int s0 = face_sommets_(face, 0), s1 = face_sommets_(face, k),
                s2 = k + 1 < face_sommets_.dimension(1) && face_sommets_(face, k + 1) >= 0 ? face_sommets_(face, k +1) : s0;
            double s = 0;
            for (int r = 0; r < 3; r++)
              for (int i = 0; i < 2; i++)
                s += (i ? -1 : 1) * face_normales_(face, r) * (coords(s2, (r + 1 +  i) % 3) - coords(s0, (r + 1 +  i) % 3))
                     * (coords(s1, (r + 1 + !i) % 3) - coords(s0, (r + 1 + !i) % 3));
            for (int r = 0; r < 3; r++) xs[r] += s * (coords(s0, r) + coords(s1, r) + coords(s2, r)) / 3;
            S += s;
          }
      if (S == 0 && sub_type(Hexa_poly,type_elem_.valeur()))
        {
          Cerr << "===============================" << finl;
          Cerr << "Error in your mesh for " << que_suis_je() << "!" << finl;
          Cerr << "Add this keyword before discretization in your data file to create polyedras:" << finl;
          Cerr << "Polyedriser " << zone().domaine().le_nom() << finl;
          Process::exit();
        }
      for (int r = 0; r < 3; r++) xv_(face, r) = xs[r] / S;
    }
  xv_.echange_espace_virtuel();
  detecter_faces_non_planes();
// volumes_entrelaces_ et volumes_entrelaces_dir : par projection de l'amont/aval sur la normale a la face
  creer_tableau_faces(volumes_entrelaces_);
  volumes_entrelaces_dir_.resize(0, 2), creer_tableau_faces(volumes_entrelaces_dir_);
  for (int f = 0, i, e; f < nb_faces(); f++)
    for (i = 0; i < 2 && (e = face_voisins_(f, i)) >= 0; volumes_entrelaces_(f) += volumes_entrelaces_dir_(f, i), i++)
      volumes_entrelaces_dir_(f, i) = std::fabs(dot(&xp_(e, 0), &face_normales_(f, 0), &xv_(f, 0)));
  volumes_entrelaces_.echange_espace_virtuel(), volumes_entrelaces_dir_.echange_espace_virtuel();
  Zone_VF::calculer_porosites();
  Zone_VF::calculer_diametres_hydrauliques();
// calculer_h_carre();
  /* ordre canonique dans elem_faces_ */
  std::map<std::array<double, 3>, int> xv_fsa;
  for (int e = 0, i, j, f; e < nb_elem_tot(); e++)
    {
      for (i = 0, j = 0, xv_fsa.clear(); i < elem_faces_.dimension(1) && (f = elem_faces_(e, i)) >= 0; i++)
        xv_fsa[ {{ xv_(f, 0), xv_(f, 1), dimension < 3 ? 0 : xv_(f, 2) }}] = f;
      for (auto &&c_f : xv_fsa) elem_faces_(e, j) = c_f.second, j++;
    }
}
References Zone_VF::calculer_diametres_hydrauliques(), Zone_VF::calculer_porosites(), Cerr, Domaine::coord_sommets(), Zone_VF::creer_tableau_faces(), detecter_faces_non_planes(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::discretiser(), Zone::domaine(), dot(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), Zone_VF::elem_faces_, est_egal(), Process::exit(), face_normales_, Zone_VF::face_sommets(), Zone_VF::face_sommets_, face_vois(), Zone_VF::face_voisins(), Zone_VF::face_voisins_, finl, Domaine::le_nom(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Elem_poly::normale(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_ >::resize(), sub_type, swap(), Zone::type_elem(), type_elem_, typer_elem(), Deriv_Elem_geom_base::valeur(), Deriv_Elem_poly_base::valeur(), Zone_VF::volumes_entrelaces_, Zone_VF::volumes_entrelaces_dir_, Zone_VF::xp_, Zone_VF::xv_, and Zone_dis_base::zone().
Referenced by Zone_PolyMAC::discretiser(), and Zone_PolyMAC_P0::discretiser().
dist_face_elem0()
double Zone_Poly_base::dist_face_elem0 (int num_face, int n0) const inline
Definition at line 347 of file Zone_Poly_base.h.
{
  return std::fabs(dot(&xp_(e, 0), &face_normales_(f, 0), &xv_(f, 0))) / face_surfaces(f);
}
References dot(), face_normales_, Zone_VF::face_surfaces(), Zone_VF::xp_, and Zone_VF::xv_.
Referenced by init_dist_paroi_globale().
dist_face_elem0_period()
double Zone_Poly_base::dist_face_elem0_period (int num_face, int n0, double l) const inline
Definition at line 357 of file Zone_Poly_base.h.
{
  abort();
  return 0;
}
References Process::abort().
dist_face_elem1()
double Zone_Poly_base::dist_face_elem1 (int num_face, int n1) const inline
Definition at line 352 of file Zone_Poly_base.h.
{
  return std::fabs(dot(&xp_(e, 0), &face_normales_(f, 0), &xv_(f, 0))) / face_surfaces(f);
}
References dot(), face_normales_, Zone_VF::face_surfaces(), Zone_VF::xp_, and Zone_VF::xv_.
dist_face_elem1_period()
double Zone_Poly_base::dist_face_elem1_period (int num_face, int n1, double l) const inline
Definition at line 363 of file Zone_Poly_base.h.
{
  abort();
  return 0;
}
References Process::abort().
dist_norm()
double Zone_Poly_base::dist_norm (int num_face) const inline
Definition at line 342 of file Zone_Poly_base.h.
{
  return std::fabs(dot(&xp_(face_voisins(f, 0), 0), &face_normales_(f, 0), &xp_(face_voisins(f, 1), 0))) / face_surfaces(f);
}
References dot(), face_normales_, Zone_VF::face_surfaces(), Zone_VF::face_voisins(), and Zone_VF::xp_.
dist_norm_bord() [1/2]
DoubleVect & Zone_Poly_base::dist_norm_bord (DoubleVect & dist, const Nom & nom_bord) const
Definition at line 648 of file Zone_Poly_base.cpp.
{
  for (int n_bord=0; n_bord<les_bords_.size(); n_bord++)
    {
      const Front_VF& fr_vf = front_VF(n_bord);
      if (fr_vf.le_nom() == nom_bord)
        {
          dist.resize(fr_vf.nb_faces());
          int ndeb = fr_vf.num_premiere_face();
          for (int face=ndeb; face<ndeb+fr_vf.nb_faces(); face++)
            dist(face-ndeb) = dist_norm_bord(face);
        }
    }
  return dist;
}
References dist_norm_bord(), Zone_VF::front_VF(), Frontiere_dis_base::le_nom(), Zone_VF::les_bords_, Front_VF::nb_faces(), Front_VF::num_premiere_face(), TRUSTVect< _TYPE_ >::resize(), and vect_impl::size().
dist_norm_bord() [2/2]
double Zone_Poly_base::dist_norm_bord (int num_face) const inline
Definition at line 336 of file Zone_Poly_base.h.
{
  assert(face_voisins(f, 1) == -1);
  return std::fabs(dot(&xp_(face_voisins(f, 0), 0), &face_normales_(f, 0), &xv_(f, 0))) / face_surfaces(f);
}
References dot(), face_normales_, Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Zone_VF::xp_, and Zone_VF::xv_.
Referenced by dist_norm_bord().
dot()
double Zone_Poly_base::dot (const double * a, const double * b, const double * ma = NULL, const double * mb = NULL) const inline
Definition at line 276 of file Zone_Poly_base.h.
{
  double res = 0;
  for (int i = 0; i < dimension; i++) res += (a[i] - (ma ? ma[i] : 0)) * (b[i] - (mb ? mb[i] : 0));
  return res;
}
References Objet_U::dimension.
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), detecter_faces_non_planes(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), discretiser(), Zone_PolyMAC::discretiser(), dist_face_elem0(), dist_face_elem1(), dist_norm(), dist_norm_bord(), Zone_PolyMAC_P0::fgrad(), init_equiv(), Echange_contact_PolyMAC::init_f_dist(), Echange_contact_PolyMAC_P0::init_fs_dist(), Champ_Face_PolyMAC_P0::init_ve2(), Zone_PolyMAC::M1(), Zone_PolyMAC::M2(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), nu_dot(), Zone_PolyMAC::orthocentrer(), Champ_Face_PolyMAC_P0::v_norm(), Zone_PolyMAC::W1(), and Zone_PolyMAC::W2().
ecrit()
Sortie & Zone_Poly_base::ecrit (Sortie & os) const protected
Definition at line 73 of file Zone_Poly_base.cpp.
{
  Zone_VF::printOn(os);
  os << "____ h_carre "<<finl;
  os << h_carre << finl;
  os << "____ type_elem_ "<<finl;
  os << type_elem_ << finl;
  os << "____ nb_elem_std_ "<<finl;
  os << nb_elem_std_ << finl;
  os << "____ volumes_entrelaces_ "<<finl;
  volumes_entrelaces_.ecrit(os);
  os << "____ face_normales_ "<<finl;
  face_normales_.ecrit(os);
  os << "____ nb_faces_std_ "<<finl;
  os << nb_faces_std_ << finl;
  os << "____ rang_elem_non_std_ "<<finl;
  rang_elem_non_std_.ecrit(os);
  return os;
}
References TRUSTVect< _TYPE_ >::ecrit(), TRUSTTab< _TYPE_ >::ecrit(), face_normales_, finl, h_carre, nb_elem_std_, nb_faces_std_, Zone_VF::printOn(), rang_elem_non_std_, type_elem_, and Zone_VF::volumes_entrelaces_.
face_normales() [1/3]
DoubleTab & Zone_Poly_base::face_normales () inline
Definition at line 180 of file Zone_Poly_base.h.
{
  return face_normales_;
}
References face_normales_.
Referenced by Zone_PolyMAC_P0::fgrad(), init_dist_paroi_globale(), init_equiv(), Zone_PolyMAC::M2(), and Zone_PolyMAC::W2().
face_normales() [2/3]
const DoubleTab & Zone_Poly_base::face_normales () const inline
Definition at line 187 of file Zone_Poly_base.h.
{
  return face_normales_;
}
References face_normales_.
face_normales() [3/3]
double Zone_Poly_base::face_normales (int face, int comp) const inline override virtual
Implements Zone_VF.
Definition at line 173 of file Zone_Poly_base.h.
{
  return face_normales_(face,comp);
}
References face_normales_.
Referenced by Champ_Face_PolyMAC::affecter_(), Champ_Face_PolyMAC_P0::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Op_Div_PolyMAC::ajouter(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Div_PolyMAC::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Assembleur_P_PolyMAC::assembler_continuite(), Op_Diff_PolyMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Masse_PolyMAC_Face::corriger_solution(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Champ_Face_PolyMAC_P0::init_ve2(), Champ_Face_PolyMAC_P0::v_norm(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), and Champ_Face_PolyMAC::valeur_aux_faces().
get_info()
const Type_info * Zone_Poly_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_dis_base.
Reimplemented in Zone_PolyMAC, and Zone_PolyMAC_P0.
Definition at line 67 of file Zone_Poly_base.cpp.
ind_faces_virt_non_std()
const ArrOfInt & Zone_Poly_base::ind_faces_virt_non_std () const inline
Definition at line 270 of file Zone_Poly_base.h.
{
  return ind_faces_virt_non_std_;
}
References ind_faces_virt_non_std_.
info()
const Type_info * Zone_Poly_base::info () static
Definition at line 67 of file Zone_Poly_base.cpp.
init_dist_paroi_globale()
void Zone_Poly_base::init_dist_paroi_globale (const Conds_lim & conds_lim) override virtual
< Autant d'aretes autour d'une face que de sommets !
< indice de la face/sommet/arete dans le tableau
< Remplissage des faces
< Remplissage des aretes
< Remplissage des sommets
< Prise en compte du cas ou l'element a plusieurs faces de bord
Parameters
conds_lim Methode inspiree de Raccord_distant_homogene::initialise
Reimplemented from Zone_dis_base.
Definition at line 697 of file Zone_Poly_base.cpp.
{
  if(dist_paroi_initialisee_) return;
  const Zone_Poly_base& zone_ = *this;
  int D=Objet_U::dimension, nf = zone_.nb_faces(), ne = zone_.nb_elem();
  const IntTab& f_s = face_sommets();
  const DoubleTab& xs = zone_.zone().domaine().coord_sommets();
// On initialise les tables y_faces_ et y_elem_
  zone_.creer_tableau_faces(y_faces_);
  zone_.zone().creer_tableau_elements(y_elem_);
  n_y_elem_.resize(0,D);
  n_y_faces_.resize(0,D);
  MD_Vector_tools::creer_tableau_distribue(y_elem_.get_md_vector(), n_y_elem_);
  MD_Vector_tools::creer_tableau_distribue(y_faces_.get_md_vector(), n_y_faces_);
// On va identifier les faces par leur centres de gravite
  int parts = Process::nproc();
  int moi = Process::me();
  DoubleTabs remote_xv(parts);
// On initialise la table de faces/sommets/aretes de bords locale, on cree une table de sommets locale et on compte les aretes
  int nb_faces_bord_ = 0;
  int nb_aretes = 0;
  std::set<int> soms;
  for (int ind_cl = 0 ; ind_cl < conds_lim.size() ; ind_cl++)
    if ( sub_type(Dirichlet_paroi_defilante, conds_lim(ind_cl).valeur()) || sub_type(Dirichlet_homogene, conds_lim(ind_cl).valeur()) || sub_type(Navier, conds_lim(ind_cl).valeur()) )
      {
        int num_face_1_cl = conds_lim(ind_cl).frontiere_dis().frontiere().num_premiere_face();
        int nb_faces_cl   = conds_lim(ind_cl).frontiere_dis().frontiere().nb_faces();
        nb_faces_bord_ += conds_lim(ind_cl).frontiere_dis().frontiere().nb_faces();
        for (int f=num_face_1_cl ; f < nb_faces_cl+num_face_1_cl ; f++)
          {
            int nb_som_loc = 0;
            while ( (nb_som_loc < nb_som_face()) && (f_s(f, nb_som_loc) != -1))
              {
                soms.insert(f_s(f, nb_som_loc));
                nb_som_loc++;
              }
            nb_aretes += (D == 3 ? nb_som_loc : 0)  ; //!< Autant d'aretes autour d'une face que de sommets !
          }
      }
  remote_xv[moi].resize(nb_faces_bord_ + soms.size() + nb_aretes,D);
// On remplit les coordonnes des faces et aretes de bord locales
  int ind_tab = 0 ; //!< indice de la face/sommet/arete dans le tableau
  for (int ind_cl = 0 ; ind_cl < conds_lim.size() ; ind_cl++)
    if ( sub_type(Dirichlet_paroi_defilante, conds_lim(ind_cl).valeur()) || sub_type(Dirichlet_homogene, conds_lim(ind_cl).valeur()) || sub_type(Navier, conds_lim(ind_cl).valeur()) )
      {
        int num_face_1_cl = conds_lim(ind_cl).frontiere_dis().frontiere().num_premiere_face();
        int nb_faces_cl   = conds_lim(ind_cl).frontiere_dis().frontiere().nb_faces();
        for (int f=num_face_1_cl ; f < nb_faces_cl+num_face_1_cl ; f++)
          {
            for (int d=0 ; d<D ; d++) remote_xv[moi](ind_tab,d) = zone_.xv(f, d); //!< Remplissage des faces
            ind_tab++;
            if (D==3) //!< Remplissage des aretes
              {
                int id_som = 1 ;
                while ( (id_som < nb_som_face()) && (f_s(f, id_som) != -1))
                  {
                    for (int d=0 ; d<D ; d++) remote_xv[moi](ind_tab,d) = (xs(f_s(f, id_som), d) + xs(f_s(f, id_som-1), d)) / 2;
                    id_som++;
                    ind_tab++;
                  }
                for (int d=0 ; d<D ; d++) remote_xv[moi](ind_tab,d) = (xs(f_s(f, 0), d) + xs(f_s(f, id_som-1), d)) / 2;
                ind_tab++;
              }
          }
      }
  for (auto som:soms) //!< Remplissage des sommets
    {
      for (int d=0 ; d<D ; d++) remote_xv[moi](ind_tab,d) = xs(som, d);
      ind_tab++;
    }
// Puis on echange les tableaux des centres de gravites
// envoi des tableaux
  for (int p = 0; p < parts; p++)
    envoyer_broadcast(remote_xv[p], p);
  VECT(ArrOfInt) racc_vois(parts);
  for (int p = 0; p < parts; p++)
    racc_vois[p].set_smart_resize(1);
#ifdef MEDCOUPLING_
// On traite les informations, chaque proc connait tous les XV
// On boucle sur toutes les faces puis tous les elems
  const DoubleTab& local_xv = zone_.xv(),
                   & local_xp = zone_.xp();
// DataArrayDoubles des xv locaux et de tous les remote_xv (a la suite)
  std::vector<MCAuto<DataArrayDouble> > vxv(parts);
  std::vector<const DataArrayDouble*> cvxv(parts);
  for (int p = 0; p < parts; p++)
    {
      vxv[p] = DataArrayDouble::New();
      vxv[p]->useExternalArrayWithRWAccess(remote_xv[p].addr(), remote_xv[p].dimension(0), remote_xv[p].dimension(1));
      cvxv[p] = vxv[p];
    }
  MCAuto<DataArrayDouble> remote_xvs(DataArrayDouble::Aggregate(cvxv)), local_xs(DataArrayDouble::New());
  local_xs->alloc(nf+ne, D);
  for (int f = 0; f < nf; f++)
    for (int d = 0; d < D; d++)
      local_xs->setIJ(f, d, local_xv(f, d));
  for (int e = 0; e < ne; e++)
    for (int d = 0; d < D; d++)
      local_xs->setIJ(nf+e, d, local_xp(e, d));
// indices des points de remote_xvs les plus proches de chaque point de local_xv
  MCAuto<DataArrayInt> glob_idx(DataArrayInt::New());
  glob_idx = remote_xvs->findClosestTupleId(local_xs);
// pour chaque element et face de local_xs : remplissage des tableaux
  for (int fe = 0; fe<nf+ne; fe++)
    {
// retour de l'indice global (glob_idx(ind_face)) au couple (proc, ind_face2)
      int proc = 0, fe2 = glob_idx->getIJ(fe, 0);
      while (fe2 >= remote_xv[proc].dimension(0)) fe2 -= remote_xv[proc].dimension(0), proc++;
      assert(fe2 <  remote_xv[proc].dimension(0));
      double distance2 = 0;
      for (int d=0; d<D; d++)
        {
          double x1 = 0 ;
          if (fe<nf) x1=local_xv(fe,d);
          else if (fe<nf+ne) x1=local_xp(fe-nf,d);
          else { Cerr<<"Zone_Poly_base::init_dist_bord : problem in the ditance to the edge calculation. Contact TRUST support."<<finl; Process::exit();}
          double x2=remote_xv[proc](fe2,d);
          distance2 += (x1-x2)*(x1-x2);
        }
      if (fe<nf)
        {
          y_faces_(fe) = std::sqrt(distance2);
          if (y_faces_(fe)>1.e-8)
            for (int d = 0 ; d<D ; d++) n_y_faces_(fe, d) = ( local_xv(fe,d)-remote_xv[proc](fe2,d) )/ y_faces_(fe);
        }
      else
        {
          y_elem_(fe-nf)  = std::sqrt(distance2);
          for (int d = 0 ; d<D ; d++) n_y_elem_(fe-nf, d) = ( local_xp(fe-nf,d)-remote_xv[proc](fe2,d) )/ y_elem_(fe-nf);
        }
    }
#else
  Cerr<<"Zone_Poly_base::init_dist_bord needs TRUST compiled with MEDCoupling."<<finl;
  exit();
#endif
// Pour les elems de bord, on calcule la distance de facon propre avec le produit scalaire
  for (int ind_cl = 0 ; ind_cl < conds_lim.size() ; ind_cl++)
    if ( sub_type(Dirichlet_paroi_defilante, conds_lim(ind_cl).valeur()) || sub_type(Dirichlet_homogene, conds_lim(ind_cl).valeur()) || sub_type(Navier, conds_lim(ind_cl).valeur()) )
      {
        int num_face_1_cl = conds_lim(ind_cl).frontiere_dis().frontiere().num_premiere_face();
        int nb_faces_cl   = conds_lim(ind_cl).frontiere_dis().frontiere().nb_faces();
        for (int f=num_face_1_cl ; f < nb_faces_cl+num_face_1_cl ; f++)
          if ( dist_face_elem0(f, face_voisins(f, 0)) < y_elem_(face_voisins(f, 0)) ) //!< Prise en compte du cas ou l'element a plusieurs faces de bord
            {
              y_elem_(face_voisins(f, 0)) = dist_face_elem0(f, face_voisins(f, 0)) ;
              for (int d = 0 ; d<D ; d++)
                {
                  n_y_elem_(face_voisins(f, 0), d) = -face_normales(f,  d)/face_surfaces(f);
                  n_y_faces_ = -face_normales(f,  d)/face_surfaces(f);
                }
            }
      }
  y_faces_.echange_espace_virtuel();
  y_elem_.echange_espace_virtuel();
  dist_paroi_initialisee_ = 1;
  Cerr <<"Initialize the y table " << zone_.zone().domaine().le_nom();
}
References Cerr, Domaine::coord_sommets(), MD_Vector_tools::creer_tableau_distribue(), Zone::creer_tableau_elements(), Zone_VF::creer_tableau_faces(), Objet_U::dimension, dist_face_elem0(), Zone_dis_base::dist_paroi_initialisee_, Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), envoyer_broadcast(), Process::exit(), face_normales(), Zone_VF::face_sommets(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), finl, TRUSTVect< _TYPE_ >::get_md_vector(), Domaine::le_nom(), Process::me(), n_y_elem_, n_y_faces_, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone_VF::nb_som_face(), Process::nproc(), TRUSTTab< _TYPE_ >::resize(), vect_impl::size(), sub_type, valeur(), VECT, Zone_VF::xp(), Zone_VF::xv(), Zone_dis_base::y_elem_, Zone_dis_base::y_faces_, and Zone_dis_base::zone().
init_equiv()
void Zone_Poly_base::init_equiv () const
Definition at line 664 of file Zone_Poly_base.cpp.
{
  if (is_init["equiv"]) return;
  const IntTab& e_f = elem_faces(), &f_e = face_voisins();
  const DoubleTab& nf = face_normales();
  const DoubleVect& fs = face_surfaces();//, &vf = volumes_entrelaces();
  int i, j, e1, e2, f, f1, f2, d, D = dimension, ok;
  IntTrav ntot, nequiv;
  creer_tableau_faces(ntot), creer_tableau_faces(nequiv);
  equiv.resize(nb_faces_tot(), 2, e_f.dimension(1));
  Cerr << zone().domaine().le_nom() << " : intializing equiv... ";
  for (f = 0, equiv = -1; f < nb_faces_tot(); f++)
    if ((e1 = f_e(f, 0)) >= 0 && (e2 = f_e(f, 1)) >= 0)
      for (i = 0; i < e_f.dimension(1) && (f1 = e_f(e1, i)) >= 0; i++)
        for (j = 0, ntot(f)++; j < e_f.dimension(1) && (f2 = e_f(e2, j)) >= 0; j++)
          {
            if (std::fabs(std::fabs(dot(&nf(f1, 0), &nf(f2, 0)) / (fs(f1) * fs(f2))) - 1) > 1e-6) continue; //normales colineaires?
            for (ok = 1, d = 0; d < D; d++) ok &= std::fabs((xv_(f1, d) - xp_(e1, d)) - (xv_(f2, d) - xp_(e2, d))) < 1e-12; //xv - xp identiques?
            if (!ok) continue;
            equiv(f, 0, i) = f2, equiv(f, 1, j) = f1, nequiv(f)++; //si oui, on a equivalence
          }
  Cerr << mp_somme_vect(nequiv) * 100. / mp_somme_vect(ntot) << "% equivalent faces !" << finl;
  is_init["equiv"] = 1;
}
References Cerr, Zone_VF::creer_tableau_faces(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), dot(), Zone_VF::elem_faces(), equiv, f1, f2, face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), finl, is_init, Domaine::le_nom(), mp_somme_vect(), Zone_VF::nb_faces_tot(), TRUSTTab< _TYPE_ >::resize(), Zone_VF::xp_, Zone_VF::xv_, and Zone_dis_base::zone().
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::completer(), Op_Conv_EF_Stab_PolyMAC_P0_Face::completer(), and Op_Diff_PolyMAC_P0_Face::completer().
init_som_elem()
void Zone_Poly_base::init_som_elem () const
Definition at line 690 of file Zone_Poly_base.cpp.
{
  if (is_init["som_elem"]) return;
  construire_connectivite_som_elem(zone().domaine().nb_som_tot(), zone().les_elems(), som_elem, 1);
  is_init["som_elem"] = 1;
}
References construire_connectivite_som_elem(), is_init, Zone_dis_base::nb_som_tot(), som_elem, and Zone_dis_base::zone().
Referenced by Zone_PolyMAC_P0::fgrad().
modifier_pour_Cl()
void Zone_Poly_base::modifier_pour_Cl (const Conds_lim &) inline override virtual
Implements Zone_dis_base.
Definition at line 86 of file Zone_Poly_base.h.
{ };
nb_elem_Cl()
int Zone_Poly_base::nb_elem_Cl () const inline
Definition at line 240 of file Zone_Poly_base.h.
{
  return nb_elem() - nb_elem_std_;
}
References Zone_dis_base::nb_elem(), and nb_elem_std_.
nb_elem_std()
int Zone_Poly_base::nb_elem_std () const inline
Definition at line 234 of file Zone_Poly_base.h.
{
  return nb_elem_std_;
}
References nb_elem_std_.
nb_faces_joint()
int Zone_Poly_base::nb_faces_joint () const inline
Definition at line 221 of file Zone_Poly_base.h.
{
  return 0;
// return nb_faces_joint_;    A FAIRE
}
nb_faces_std()
int Zone_Poly_base::nb_faces_std () const inline
Definition at line 228 of file Zone_Poly_base.h.
{
  return nb_faces_std_;
}
References nb_faces_std_.
normale_paroi_elem()
const DoubleTab & Zone_Poly_base::normale_paroi_elem () const inline
Definition at line 139 of file Zone_Poly_base.h.
{return n_y_elem_;} ;
References n_y_elem_.
normale_paroi_faces()
const DoubleTab & Zone_Poly_base::normale_paroi_faces () const inline
Definition at line 140 of file Zone_Poly_base.h.
{return n_y_faces_;} ;
References n_y_faces_.
nu_dot()
double Zone_Poly_base::nu_dot (const DoubleTab * nu, int e, int n, const double * a, const double * b, const double * ma = NULL, const double * mb = NULL) const inline
Definition at line 370 of file Zone_Poly_base.h.
{
  if (!nu) return dot(a, b, ma, mb);
  int d, db, D = dimension;
  double resu = 0;
  if (nu->nb_dim() == 2) resu += (*nu)(e, n) * dot(a, b, ma, mb); //isotrope
  else if (nu->nb_dim() == 3)
    for (d = 0; d < D; d++) //anisotrope diagonal
      resu += (*nu)(e, n, d) * (a[d] - (ma ? ma[d] : 0)) * (b[d] - (mb ? mb[d] : 0));
  else for (d = 0; d < D; d++)
      for (db = 0; db < D; db++)
        resu += (*nu)(e, n, d, db) * (a[d] - (ma ? ma[d] : 0)) * (b[db] - (mb ? mb[db] : 0));
  return resu;
}
References Objet_U::dimension, dot(), and TRUSTTab< _TYPE_ >::nb_dim().
Referenced by Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Diff_PolyMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Zone_PolyMAC_P0::fgrad(), Zone_PolyMAC::M1(), Zone_PolyMAC::M2(), Zone_PolyMAC::W1(), and Zone_PolyMAC::W2().
oriente_normale()
int Zone_Poly_base::oriente_normale (int face_opp, int elem2) const inline
Definition at line 253 of file Zone_Poly_base.h.
{
  if(face_voisins(face_opp,0)==elem2)
    return 1;
  else return -1;
}
References Zone_VF::face_voisins().
printOn()
Sortie & Zone_Poly_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Zone_dis_base.
Reimplemented in Zone_PolyMAC, and Zone_PolyMAC_P0.
Definition at line 93 of file Zone_Poly_base.cpp.
{
  Zone_VF::printOn(os);
  os << h_carre << finl;
  os << type_elem_ << finl;
  os << nb_elem_std_ << finl;
  os << volumes_entrelaces_ << finl;
  os << face_normales_ << finl;
  os << xp_ << finl;
  os << xv_ << finl;
  os << nb_faces_std_ << finl;
  os << rang_elem_non_std_ << finl;
  return os;
}
References face_normales_, finl, h_carre, nb_elem_std_, nb_faces_std_, Zone_VF::printOn(), rang_elem_non_std_, type_elem_, Zone_VF::volumes_entrelaces_, Zone_VF::xp_, and Zone_VF::xv_.
Referenced by Zone_PolyMAC::printOn(), and Zone_PolyMAC_P0::printOn().
rang_elem_non_std() [1/2]
IntVect & Zone_Poly_base::rang_elem_non_std () inline
Definition at line 208 of file Zone_Poly_base.h.
{
  return rang_elem_non_std_;
}
References rang_elem_non_std_.
rang_elem_non_std() [2/2]
const IntVect & Zone_Poly_base::rang_elem_non_std () const inline
Definition at line 214 of file Zone_Poly_base.h.
{
  return rang_elem_non_std_;
}
References rang_elem_non_std_.
readOn()
Entree & Zone_Poly_base::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Zone_dis_base.
Reimplemented in Zone_PolyMAC, and Zone_PolyMAC_P0.
Definition at line 112 of file Zone_Poly_base.cpp.
{
  Zone_VF::readOn(is);
  is >> h_carre;
  is >> type_elem_;
  is >> nb_elem_std_ ;
  is >> volumes_entrelaces_ ;
  is >> face_normales_ ;
  is >> xp_;
  is >> xv_;
  is >> nb_faces_std_ ;
  is >> rang_elem_non_std_ ;
  return is;
}
References face_normales_, h_carre, nb_elem_std_, nb_faces_std_, rang_elem_non_std_, Zone_VF::readOn(), type_elem_, Zone_VF::volumes_entrelaces_, Zone_VF::xp_, and Zone_VF::xv_.
Referenced by Zone_PolyMAC::readOn(), and Zone_PolyMAC_P0::readOn().
remplir_elem_faces()
void Zone_Poly_base::remplir_elem_faces () inline override protected virtual
Implements Zone_VF.
Definition at line 154 of file Zone_Poly_base.h.
{};
reordonner()
void Zone_Poly_base::reordonner (Faces & les_faces) override virtual
Methode appelee par Zone_VF::discretiser apres la creation
des faces reelles.
On reordonne les faces de sorte a placer les faces "non standard"
au debut de la liste des faces. Les faces non standard sont celles
dont les volumes de controles sont modifies par les conditions aux
limites.
< renum_items_communs rempli ?
< ancien indice local
Reimplemented from Zone_VF.
Definition at line 134 of file Zone_Poly_base.cpp.
{
  if (Process::je_suis_maitre())
    Cerr << "Zone_Poly_base::reordonner faces " << finl;
// Construction de rang_elem_non_std_ :
// C'est un vecteur indexe par les elements du domaine.
// size() = nb_elem()
// size_tot() = nb_elem_tot()
// Valeurs dans le tableau :
// rang_elem_non_std_[i] = -1 si l'element i est standard,
// sinon
// rang_elem_non_std_[i] = j, ou j est l'indice de l'element dans
// les tableaux indexes par les elements non standards (par exemple
// le tableau Zone_Cl_Poly_base::type_elem_Cl_).
// Un element est non standard s'il est voisin d'une face frontiere.
  {
    const Domaine& dom = zone().domaine();
    const int nb_elements = nb_elem();
    const int nb_faces_front = zone().nb_faces_frontiere();
    dom.creer_tableau_elements(rang_elem_non_std_);
// rang_elem_non_std_.resize(nb_elements);
// Scatter::creer_tableau_distribue(dom, Joint::ELEMENT, rang_elem_non_std_);
    rang_elem_non_std_ = -1;
    int nb_elems_non_std = 0;
// D'abord on marque les elements non standards avec rang_elem_non_std_[i] = 0
    for (int i_face = 0; i_face < nb_faces_front; i_face++)
      {
        const int elem = les_faces.voisin(i_face, 0);
        if (rang_elem_non_std_[elem] < 0)
          {
            rang_elem_non_std_[elem] = 0;
            nb_elems_non_std++;
          }
      }
    nb_elem_std_ = nb_elements - nb_elems_non_std;
    rang_elem_non_std_.echange_espace_virtuel();
    int count = 0;
    const int size_tot = rang_elem_non_std_.size_totale();
// On remplace le marqueur "0" par l'indice j.
    for (int elem = 0; elem < size_tot; elem++)
      {
        if (rang_elem_non_std_[elem] == 0)
          {
            rang_elem_non_std_[elem] = count;
            count++;
          }
      }
  }
// Construction du tableau de renumerotation des faces. Ce tableau,
// une fois trie dans l'ordre croissant donne l'ordre des faces dans
// la zone_VF. La cle de tri est construite de sorte a pouvoir retrouver
// l'indice de la face a partir de la cle par la formule :
// indice_face = cle % nb_faces
  const int nbfaces = les_faces.nb_faces();
  ArrOfInt sort_key(nbfaces);
  {
    nb_faces_std_ =0;
    const int nb_faces_front = zone().nb_faces_frontiere();
// Attention : face_voisins_ n'est pas encore initialise, il
// faut passer par les_faces.voisins() :
    const IntTab& facevoisins = les_faces.voisins();
// On place en premier les faces de bord:
    int i_face;
    for (i_face = 0; i_face < nbfaces; i_face++)
      {
        int key = -1;
        if (i_face < nb_faces_front)
          {
// Si la face est au bord, elle doit etre placee au debut
// (en fait elle ne doit pas etre renumerotee)
            key = i_face;
          }
        else
          {
            const int elem0 = facevoisins(i_face, 0);
            const int elem1 = facevoisins(i_face, 1);
// Ces faces ont toujours deux voisins.
            assert(elem0 >= 0 && elem1 >= 0);
            if (rang_elem_non_std_[elem0] >= 0 || rang_elem_non_std_[elem1] >= 0)
              {
// Si la face est voisine d'un element non standard, elle
// doit etre classee juste apres les faces de bord:
                key = i_face;
              }
            else
              {
// Face standard : a la fin du tableau
                key = i_face + nbfaces;
                nb_faces_std_++;
              }
          }
        sort_key[i_face] = key;
      }
    sort_key.ordonne_array();
// On transforme a nouveau la cle en numero de face:
    for (i_face = 0; i_face < nbfaces; i_face++)
      {
        const int key = sort_key[i_face] % nbfaces;
        sort_key[i_face] = key;
      }
  }
// On reordonne les faces:
  {
    IntTab& faces_sommets = les_faces.les_sommets();
    IntTab old_tab(faces_sommets);
    const int nb_som_faces = faces_sommets.dimension(1);
    for (int i = 0; i < nbfaces; i++)
      {
        const int old_i = sort_key[i];
        for (int j = 0; j < nb_som_faces; j++)
          faces_sommets(i, j) = old_tab(old_i, j);
      }
  }
  {
    IntTab& faces_voisins = les_faces.voisins();
    IntTab old_tab(faces_voisins);
    for (int i = 0; i < nbfaces; i++)
      {
        const int old_i = sort_key[i];
        faces_voisins(i, 0) = old_tab(old_i, 0);
        faces_voisins(i, 1) = old_tab(old_i, 1);
      }
  }
// Calcul de la table inversee: reverse_index[ancien_numero] = nouveau numero
  ArrOfInt reverse_index(nbfaces);
  {
    for (int i = 0; i < nbfaces; i++)
      {
        const int j = sort_key[i];
        reverse_index[j] = i;
      }
  }
// Renumerotation de elem_faces:
  {
// Nombre d'indices de faces dans le tableau
    const int nb_items = elem_faces_.size();
    ArrOfInt& array = elem_faces_;
    for (int i = 0; i < nb_items; i++)
      {
        const int old = array[i];
        if (old<0)
          array[i] = -1;
        else
          array[i] = reverse_index[old];
      }
  }
// Mise a jour des indices des faces de joint:
  {
    Joints&      joints    = zone().faces_joint();
    const int nbjoints = joints.size();
    for (int i_joint = 0; i_joint < nbjoints; i_joint++)
      {
        Joint&     un_joint         = joints[i_joint];
        ArrOfInt& indices_faces = un_joint.set_joint_item(Joint::FACE).set_items_communs();
        const int nbfaces2    = indices_faces.size_array();
        assert(nbfaces2 == un_joint.nb_faces()); //!< renum_items_communs rempli ?
        for (int i = 0; i < nbfaces2; i++)
          {
            const int old = indices_faces[i]; //!< ancien indice local
            indices_faces[i] = reverse_index[old];
          }
// Les faces de joint ne sont plus consecutives dans le
// tableau: num_premiere_face n'a plus ne sens
        un_joint.fixer_num_premiere_face(-1);
      }
  }
}
References Cerr, Domaine::creer_tableau_elements(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces_, Joint::FACE, Zone::faces_joint(), finl, Frontiere::fixer_num_premiere_face(), Process::je_suis_maitre(), Faces::les_sommets(), Zone_dis_base::nb_elem(), nb_elem_std_, Faces::nb_faces(), Frontiere::nb_faces(), Zone::nb_faces_frontiere(), nb_faces_std_, TRUSTArray< _TYPE_ >::ordonne_array(), rang_elem_non_std_, Joint_Items::set_items_communs(), Joint::set_joint_item(), TRUSTVect< _TYPE_ >::size(), liste::size(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), Faces::voisin(), Faces::voisins(), and Zone_dis_base::zone().
self_cast() [1/2]
const Zone_Poly_base & Zone_Poly_base::self_cast (const Objet_U & r) static
Definition at line 67 of file Zone_Poly_base.cpp.
self_cast() [2/2]
Zone_Poly_base & Zone_Poly_base::self_cast (Objet_U & r) static
Definition at line 67 of file Zone_Poly_base.cpp.
type_elem()
const Elem_poly & Zone_Poly_base::type_elem () const inline
Definition at line 166 of file Zone_Poly_base.h.
{
  return type_elem_;
}
References type_elem_.
Referenced by PolyMAC_discretisation::vorticite().
typer_elem()
void Zone_Poly_base::typer_elem (Zone & zone_geom) override virtual
Reimplemented from Zone_VF.
Definition at line 307 of file Zone_Poly_base.cpp.
{
  const Elem_geom_base& type_elem_geom = zone_geom.type_elem().valeur();
  if (sub_type(Rectangle,type_elem_geom))
    {
      zone_geom.typer("Quadrangle");
    }
  else if (sub_type(Hexaedre,type_elem_geom))
    zone_geom.typer("Hexaedre_VEF");
  const Elem_geom_base& elem_geom = zone_geom.type_elem().valeur();
  type_elem_.typer(elem_geom.que_suis_je());
}
References Objet_U::que_suis_je(), sub_type, Zone::type_elem(), type_elem_, Zone::typer(), Elem_poly::typer(), and Deriv_Elem_geom_base::valeur().
Referenced by discretiser().
volumes_entrelaces_dir() [1/2]
DoubleTab & Zone_Poly_base::volumes_entrelaces_dir () inline
Definition at line 194 of file Zone_Poly_base.h.
{
  return volumes_entrelaces_dir_;
}
References Zone_VF::volumes_entrelaces_dir_.
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_PolyMAC_Face::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Op_Conv_EF_Stab_PolyMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), and Zone_PolyMAC_P0::fgrad().
volumes_entrelaces_dir() [2/2]
const DoubleTab & Zone_Poly_base::volumes_entrelaces_dir () const inline
Definition at line 201 of file Zone_Poly_base.h.
{
  return volumes_entrelaces_dir_;
}
References Zone_VF::volumes_entrelaces_dir_.
Member Data Documentation
equiv
IntTab Zone_Poly_base::equiv mutable
Definition at line 132 of file Zone_Poly_base.h.
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), and init_equiv().
face_normales_
DoubleTab Zone_Poly_base::face_normales_ protected
normales aux faces
Definition at line 146 of file Zone_Poly_base.h.
Referenced by detecter_faces_non_planes(), discretiser(), dist_face_elem0(), dist_face_elem1(), dist_norm(), dist_norm_bord(), ecrit(), face_normales(), Zone_PolyMAC::orthocentrer(), printOn(), and readOn().
h_carre
double Zone_Poly_base::h_carre protected
carre du pas du maillage
Definition at line 143 of file Zone_Poly_base.h.
Referenced by calculer_h_carre(), carre_pas_du_maillage(), ecrit(), printOn(), and readOn().
h_carre_
DoubleVect Zone_Poly_base::h_carre_ protected
carre du pas d'une maille
Definition at line 144 of file Zone_Poly_base.h.
Referenced by calculer_h_carre(), and carre_pas_maille().
ind_faces_virt_non_std_
ArrOfInt Zone_Poly_base::ind_faces_virt_non_std_ protected
contient les indices des faces virtuelles non standard
Definition at line 153 of file Zone_Poly_base.h.
Referenced by ind_faces_virt_non_std().
info_obj
const Type_info Zone_Poly_base::info_obj static
Definition at line 80 of file Zone_Poly_base.h.
is_init
std::map<std::string, int> Zone_Poly_base::is_init mutable
Definition at line 129 of file Zone_Poly_base.h.
Referenced by init_equiv(), init_som_elem(), and Zone_PolyMAC_P0::init_stencils().
n_y_elem_
DoubleTab Zone_Poly_base::n_y_elem_ protected
vecteur normal entre le bord le plus proche et l'element
Definition at line 158 of file Zone_Poly_base.h.
Referenced by init_dist_paroi_globale(), and normale_paroi_elem().
n_y_faces_
DoubleTab Zone_Poly_base::n_y_faces_ protected
vecteur normal entre le bord le plus proche et la face
Definition at line 159 of file Zone_Poly_base.h.
Referenced by init_dist_paroi_globale(), and normale_paroi_faces().
nb_elem_std_
int Zone_Poly_base::nb_elem_std_ protected
nombre d'elements standard
Definition at line 148 of file Zone_Poly_base.h.
Referenced by ecrit(), nb_elem_Cl(), nb_elem_std(), printOn(), readOn(), and reordonner().
nb_faces_std_
int Zone_Poly_base::nb_faces_std_ protected
nombre de faces standard
Definition at line 147 of file Zone_Poly_base.h.
Referenced by ecrit(), nb_faces_std(), printOn(), readOn(), and reordonner().
rang_elem_non_std_
IntVect Zone_Poly_base::rang_elem_non_std_ protected
rang_elem_non_std_= -1 si l'element est standard rang_elem_non_std_= rang de l'element dans les tableaux relatifs aux elements non standards
Definition at line 149 of file Zone_Poly_base.h.
Referenced by ecrit(), printOn(), rang_elem_non_std(), readOn(), and reordonner().
som_elem
Static_Int_Lists Zone_Poly_base::som_elem mutable
Definition at line 135 of file Zone_Poly_base.h.
Referenced by Zone_PolyMAC_P0::fgrad(), init_som_elem(), and Op_Diff_PolyMAC_P0_Elem::init_som_ext().
type_elem_
Elem_poly Zone_Poly_base::type_elem_ protected
type de l'element de discretisation
Definition at line 145 of file Zone_Poly_base.h.
Referenced by discretiser(), ecrit(), printOn(), readOn(), type_elem(), and typer_elem().
The documentation for this class was generated from the following files:
src/Kernel/VF/Zones/Zone_Poly_base.h
src/Kernel/VF/Zones/Zone_Poly_base.cpp