TRUST: Deriv_Sortie_Fichier_base Class Reference
Deriv_Sortie_Fichier_base Class Reference
#include <Deriv_Sortie_Fichier_base.h>
Public Member Functions
~Deriv_Sortie_Fichier_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Sortie_Fichier_base ()
Deriv_Sortie_Fichier_base (const Deriv_Sortie_Fichier_base &)
const Sortie_Fichier_base & valeur () const
Sortie_Fichier_base & valeur ()
const Sortie_Fichier_base * operator-> () const
Sortie_Fichier_base * operator-> ()
const Deriv_Sortie_Fichier_base & operator= (const Sortie_Fichier_base &)
const Deriv_Sortie_Fichier_base & operator= (const Deriv_Sortie_Fichier_base &)
operator const Sortie_Fichier_base & () const
operator Sortie_Fichier_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Sortie_Fichier_base & self_cast (Objet_U &)
static const
Deriv_Sortie_Fichier_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Sortie_Fichier_base * pointeur_
Detailed Description
Definition at line 26 of file Deriv_Sortie_Fichier_base.h.
Constructor & Destructor Documentation
Deriv_Sortie_Fichier_base::~Deriv_Sortie_Fichier_base ()
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
Deriv_Sortie_Fichier_base::Deriv_Sortie_Fichier_base ()
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
Deriv_Sortie_Fichier_base::Deriv_Sortie_Fichier_base (const Deriv_Sortie_Fichier_base & t)
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
Member Function Documentation
Objet_U * Deriv_Sortie_Fichier_base::cree_instance () [static]
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
int Deriv_Sortie_Fichier_base::duplique () const [virtual]
Implements Deriv_.
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
const Type_info * Deriv_Sortie_Fichier_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
const Type_info & Deriv_Sortie_Fichier_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
const Type_info * Deriv_Sortie_Fichier_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
Deriv_Sortie_Fichier_base::operator const Sortie_Fichier_base & () const
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
Deriv_Sortie_Fichier_base::operator Sortie_Fichier_base & ()
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
const Sortie_Fichier_base * Deriv_Sortie_Fichier_base::operator-> () const [inline]
Definition at line 26 of file Deriv_Sortie_Fichier_base.h.
Sortie_Fichier_base * Deriv_Sortie_Fichier_base::operator-> () [inline]
Definition at line 26 of file Deriv_Sortie_Fichier_base.h.
const Deriv_Sortie_Fichier_base & Deriv_Sortie_Fichier_base::operator= (const Deriv_Sortie_Fichier_base & t)
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
const Deriv_Sortie_Fichier_base & Deriv_Sortie_Fichier_base::operator= (const Sortie_Fichier_base & t)
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
Sortie & Deriv_Sortie_Fichier_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
Entree & Deriv_Sortie_Fichier_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
const Deriv_Sortie_Fichier_base & Deriv_Sortie_Fichier_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
Deriv_Sortie_Fichier_base & Deriv_Sortie_Fichier_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
void Deriv_Sortie_Fichier_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
unsigned Deriv_Sortie_Fichier_base::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 24 of file Deriv_Sortie_Fichier_base.cpp.
const Sortie_Fichier_base & Deriv_Sortie_Fichier_base::valeur () const [inline]
Definition at line 26 of file Deriv_Sortie_Fichier_base.h.
Referenced by Probleme_base::finir(), Probleme_base::sauver(), and Probleme_base::sauver_xyz().
Sortie_Fichier_base & Deriv_Sortie_Fichier_base::valeur () [inline]
Definition at line 26 of file Deriv_Sortie_Fichier_base.h.
Member Data Documentation
const Type_info Deriv_Sortie_Fichier_base::info_obj [static]
Reimplemented from Deriv_.
Definition at line 26 of file Deriv_Sortie_Fichier_base.h.
Sortie_Fichier_base* Deriv_Sortie_Fichier_base::pointeur_ [private]
Definition at line 26 of file Deriv_Sortie_Fichier_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Deriv_Sortie_Fichier_base.h
src/Kernel/Utilitaires/Deriv_Sortie_Fichier_base.cpp