TRUST: Op_Evanescence_Homogene_PolyMAC_P0_Face Class Reference
Op_Evanescence_Homogene_PolyMAC_P0_Face Class Reference
Classe Op_Evanescence_Homogene_PolyMAC_P0_Face
gestion dans PolyMAC_P0 de l'evanescence dans une equation aux faces (-> QDM)
#include <Op_Evanescence_Homogene_PolyMAC_P0_Face.h>
Public Member Functions
Op_Evanescence_Homogene_PolyMAC_P0_Face ()
~Op_Evanescence_Homogene_PolyMAC_P0_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
Public Member Functions inherited from Operateur_Evanescence_base
Operateur_Evanescence_base ()
~Operateur_Evanescence_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Evanescence_Homogene_PolyMAC_P0_Face & self_cast (Objet_U &)
static const Op_Evanescence_Homogene_PolyMAC_P0_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Evanescence_base
static const Type_info * info ()
static Operateur_Evanescence_base & self_cast (Objet_U &)
static const Operateur_Evanescence_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Evanescence_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Operateur_Evanescence_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Private Attributes
double alpha_res_
double alpha_res_min_ = 0
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Classe Op_Evanescence_Homogene_PolyMAC_P0_Face
gestion dans PolyMAC_P0 de l'evanescence dans une equation aux faces (-> QDM)
Definition at line 29 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.h.
Constructor & Destructor Documentation
Op_Evanescence_Homogene_PolyMAC_P0_Face()
Op_Evanescence_Homogene_PolyMAC_P0_Face::Op_Evanescence_Homogene_PolyMAC_P0_Face ()
Definition at line 27 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.cpp.
~Op_Evanescence_Homogene_PolyMAC_P0_Face()
Op_Evanescence_Homogene_PolyMAC_P0_Face::~Op_Evanescence_Homogene_PolyMAC_P0_Face ()
Definition at line 27 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.cpp.
Member Function Documentation
ajouter_blocs()
void Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
Definition at line 89 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.cpp.
{
  const Champ_Face_PolyMAC_P0& ch = ref_cast(Champ_Face_PolyMAC_P0, equation().inconnue().valeur());
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0, equation().zone_dis().valeur());
  const IntTab& f_e = zone.face_voisins(), &fcl = ch.fcl();
  const DoubleTab& inco = ch.valeurs(), &vfd = zone.volumes_entrelaces_dir(),
                   &alpha = ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe();
  const DoubleVect& vf = zone.volumes_entrelaces();
  int e, f, i, j, k, l, n, N = inco.line_size(), d, D = dimension, nf_tot = zone.nb_faces_tot(),
                           iter = sub_type(SETS, equation().schema_temps()) ? 0 * ref_cast(SETS, equation().schema_temps()).iteration : 0;
  if (N == 1) return; //pas d'evanescence en simple phase!
  double a_eps = alpha_res_, a_eps_min = alpha_res_min_, a_m, a_max; //seuil de declenchement du traitement de l'evanescence
  /* recherche de phases evanescentes et traitement des seconds membres */
  IntTrav maj(inco.dimension_tot(0)); //maj(i) : phase majoritaire de la ligne i
  DoubleTrav coeff(inco.dimension_tot(0), inco.line_size(), 2); //coeff(i, n, 0/1) : coeff a appliquer a l'equation existante / a l'eq. "inco = v_maj"
  Matrice_Morse& mat_diag = *matrices.at(ch.le_nom().getString());
  for (f = 0; f < zone.nb_faces(); f++)
    if (fcl(f, 0) < 2)
      {
        /* phase majoritaire : avec alpha interpole par defaut, avec alpha amont pour les ierations de SETS / ICE */
        for (a_max = 0, k = -1, n = 0; n < N; n++)
          {
            if (iter) a_m = alpha(f_e(f, f_e(f, 1) >= 0 && inco(f, n) < 0), n);
            else for (a_m = 0, i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++) a_m += vfd(f, i) / vf(f) * alpha(e, n);
            if (a_m > a_max) k = n, a_max = a_m;
          }
        if (k >= 0) maj(f) = k;
        else abort();
        /* phases evanescentes : avec alpha amont. La phase majoritaire ne peut pas etre evanescente! */
        for (n = 0; n < N; n++)
          {
            if (iter) a_m = alpha(f_e(f, f_e(f, 1) >= 0 && inco(f, n) < 0), n);
            else for (a_m = 0, i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++) a_m += vfd(f, i) / vf(f) * alpha(e, n);
            if (n != k && a_m < a_eps)
              {
                coeff(f, n, 1) = mat_diag(N * f + k, N * f + k) * (coeff(f, n, 0) = std::min(std::max((a_eps - a_m) / (a_eps - a_eps_min), 0.), 1.));
                double flux = coeff(f, n, 0) * secmem(f, n) + coeff(f, n, 1) * (inco(f, n) - inco(f, k));
                secmem(f, k) += flux, secmem(f, n) -= flux;
              }
          }
      }
  for (e = 0; e < zone.nb_elem_tot(); e++) /* elements : a faire D fois par element */
    {
      /* phase majoritaire : directement dans l'element */
      for (a_max = 0, k = -1, n = 0; n < N; n++)
        if ((a_m = alpha(e, n)) > a_max) k = n, a_max = a_m;
      if (k >= 0)
        for (i = nf_tot + D * e, d = 0; d < D; d++, i++) maj(i) = k;
      else abort();
      /* coeff d'evanescence */
      for (i = nf_tot + D * e, d = 0; d < D; d++, i++)
        for (n = 0; n < N; n++)
          if (n != k && (a_m = alpha(e, n)) < a_eps)
            {
              coeff(i, n, 1) = mat_diag(N * i + k, N * i + k) * (coeff(i, n, 0) = std::min(std::max((a_eps - a_m) / (a_eps - a_eps_min), 0.), 1.));
              double flux = coeff(i, n, 0) * secmem(i, n) + coeff(i, n, 1) * (inco(i, n) - inco(i, k));
              secmem(i, k) += flux, secmem(i, n) -= flux;
            }
    }
  /* lignes de matrices */
  for (auto &&n_m : matrices)
    if (n_m.second->nb_colonnes())
      {
        int diag = (n_m.first == ch.le_nom().getString()); //est-on sur le bloc diagonal?
        Matrice_Morse& mat = *n_m.second;
        /* faces */
        for (f = 0; f < zone.nb_faces(); f++)
          if (fcl(f, 0) < 2)
            for (n = 0; n < N; n++)
              if (coeff(f, n, 0))
                for (k = maj(f), i = mat.get_tab1()(N * f + n) - 1, j = mat.get_tab1()(N * f + k) - 1; i < mat.get_tab1()(N * f + n + 1) - 1; i++, j++)
                  {
                    assert(mat.get_tab2()(i) == mat.get_tab2()(j));
                    int c = diag * mat.get_tab2()(i) - 1; //indice de colonne (commun aux deux lignes grace au dimensionner_blocs())
                    mat.get_set_coeff()(j) +=  coeff(f, n, 0) * mat.get_set_coeff()(i) - coeff(f, n, 1) * ((c == N * f + n) - (c == N * f + k));
                    mat.get_set_coeff()(i) += -coeff(f, n, 0) * mat.get_set_coeff()(i) + coeff(f, n, 1) * ((c == N * f + n) - (c == N * f + k));
                  }
        /* elements : l est l'indice de ligne */
        for (e = 0, l = nf_tot; e < zone.nb_elem_tot(); e++)
          for (d = 0; d < D; d++, l++)
            for (n = 0; n < N; n++)
              if (coeff(l, n, 0))
                for (k = maj(l), i = mat.get_tab1()(N * l + n) - 1, j = mat.get_tab1()(N * l + k) - 1; i < mat.get_tab1()(N * l + n + 1) - 1; i++, j++)
                  {
                    assert(mat.get_tab2()(i) == mat.get_tab2()(j));
                    int c = diag * mat.get_tab2()(i) - 1; //indice de colonne (commun aux deux lignes grace au dimensionner_blocs())
                    mat.get_set_coeff()(j) +=  coeff(l, n, 0) * mat.get_set_coeff()(i) - coeff(l, n, 1) * ((c == N * l + n) - (c == N * l + k));
                    mat.get_set_coeff()(i) += -coeff(l, n, 0) * mat.get_set_coeff()(i) + coeff(l, n, 1) * ((c == N * l + n) - (c == N * l + k));
                  }
      }
}
References Process::abort(), alpha_res_, alpha_res_min_, coeff, Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), MorEqn::equation(), Zone_VF::face_voisins(), Champ_Face_PolyMAC::fcl(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Nom::getString(), Field_base::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), ref_cast, sub_type, valeur(), Champ_Inc_base::valeurs(), Zone_VF::volumes_entrelaces(), and Zone_Poly_base::volumes_entrelaces_dir().
cree_instance()
Objet_U * Op_Evanescence_Homogene_PolyMAC_P0_Face::cree_instance () static
Definition at line 27 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.cpp.
dimensionner_blocs()
void Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
Definition at line 43 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.cpp.
{
  const Champ_Face_PolyMAC_P0& ch = ref_cast(Champ_Face_PolyMAC_P0, equation().inconnue().valeur());
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0, equation().zone_dis().valeur());
  const DoubleTab& inco = ch.valeurs();
  const IntTab& fcl = ch.fcl();
  /* on doit pouvoir ajouter / soustraire les equations entre composantes */
  int i, j, l, e, f, n, N = inco.line_size(), d, D = dimension, nf_tot = zone.nb_faces_tot();
  if (N == 1) return; //pas d'evanescence en simple phase!
  for (auto &&n_m : matrices)
    if (n_m.second->nb_colonnes())
      {
        IntTrav sten(0, 2);
        sten.set_smart_resize(1);
        std::set<int> idx;
        Matrice_Morse& mat = *n_m.second, mat2;
        /* equations aux faces : celles calculees seulement */
        for (f = 0; f < zone.nb_faces(); f++, idx.clear())
          if (fcl(f, 0) < 2)
            {
              for (i = N * f, n = 0; n < N; n++, i++)
                for (j = mat.get_tab1()(i) - 1; j < mat.get_tab1()(i + 1) - 1; j++)
                  idx.insert(mat.get_tab2()(j) - 1);
              for (i = N * f, n = 0; n < N; n++, i++)
                for (auto &&c : idx) sten.append_line(i, c);
            }
          else if (n_m.first == ch.le_nom().getString()) /* CLs a valeur imposee : diagonale */
            for (n = 0, i = N * f; n < N; n++, i++) sten.append_line(i, i);
        /* equations aux elements */
        for (e = 0, l = nf_tot; e < zone.nb_elem_tot(); e++)
          for (d = 0; d < D; d++, l++, idx.clear())
            {
              for (i = N * l, n = 0; n < N; n++, i++)
                for (j = mat.get_tab1()(i) - 1; j < mat.get_tab1()(i + 1) - 1; j++)
                  idx.insert(mat.get_tab2()(j) - 1);
              for (i = N * l, n = 0; n < N; n++, i++)
                for (auto &&c : idx) sten.append_line(i, c);
            }
        Matrix_tools::allocate_morse_matrix(mat.nb_lignes(), mat.nb_colonnes(), sten, mat2);
        mat = mat2; //pour forcer l'ordre des coefficients dans la matrice (accelere les operations ligne a ligne)
      }
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), Objet_U::dimension, MorEqn::equation(), Champ_Face_PolyMAC::fcl(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Nom::getString(), Field_base::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Matrice_Morse::nb_colonnes(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Matrice_Morse::nb_lignes(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), valeur(), and Champ_Inc_base::valeurs().
duplique()
int Op_Evanescence_Homogene_PolyMAC_P0_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 27 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.cpp.
get_info()
const Type_info * Op_Evanescence_Homogene_PolyMAC_P0_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Evanescence_base.
Definition at line 27 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.cpp.
has_interface_blocs()
int Op_Evanescence_Homogene_PolyMAC_P0_Face::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
Definition at line 33 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.h.
  {
    return 1;
  };
info()
const Type_info * Op_Evanescence_Homogene_PolyMAC_P0_Face::info () static
Definition at line 27 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.cpp.
printOn()
Sortie & Op_Evanescence_Homogene_PolyMAC_P0_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Evanescence_base.
Definition at line 29 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.cpp.
{
  return os;
}
readOn()
Entree & Op_Evanescence_Homogene_PolyMAC_P0_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Evanescence_base.
Definition at line 34 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.cpp.
{
  Param param(que_suis_je());
  param.ajouter("alpha_res", &alpha_res_, Param::REQUIRED);
  param.ajouter("alpha_res_min", &alpha_res_min_);
  param.lire_avec_accolades_depuis(is);
  return is;
}
References Param::ajouter(), alpha_res_, alpha_res_min_, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and Param::REQUIRED.
self_cast() [1/2]
const Op_Evanescence_Homogene_PolyMAC_P0_Face & Op_Evanescence_Homogene_PolyMAC_P0_Face::self_cast (const Objet_U & r) static
Definition at line 27 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.cpp.
self_cast() [2/2]
Op_Evanescence_Homogene_PolyMAC_P0_Face & Op_Evanescence_Homogene_PolyMAC_P0_Face::self_cast (Objet_U & r) static
Definition at line 27 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.cpp.
taille_memoire()
unsigned Op_Evanescence_Homogene_PolyMAC_P0_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 27 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.cpp.
Member Data Documentation
alpha_res_
double Op_Evanescence_Homogene_PolyMAC_P0_Face::alpha_res_ private
Definition at line 41 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.h.
Referenced by ajouter_blocs(), and readOn().
alpha_res_min_
double Op_Evanescence_Homogene_PolyMAC_P0_Face::alpha_res_min_ = 0 private
Definition at line 41 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.h.
Referenced by ajouter_blocs(), and readOn().
info_obj
const Type_info Op_Evanescence_Homogene_PolyMAC_P0_Face::info_obj static
Definition at line 31 of file Op_Evanescence_Homogene_PolyMAC_P0_Face.h.
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/PolyMAC/Op_Evanescence_Homogene_PolyMAC_P0_Face.h
src/ThHyd/Multiphase/PolyMAC/Op_Evanescence_Homogene_PolyMAC_P0_Face.cpp