TRUST: Navier_Stokes_WC Class Reference
Navier_Stokes_WC Class Reference
classe Navier_Stokes_WC
Cette classe porte les termes de l'equation de la dynamique
pour un fluide sans modelisation de la turbulence.
On suppose l'hypothese de fluide quasi compressible.
Sous ces hypotheses, on utilise la forme suivante des equations de
Navier_Stokes:
DU/dt = div(terme visqueux) - gradP/rho + sources/rho
div U = W
avec DU/dt : derivee particulaire de la vitesse
rho : masse volumique
Rq : l'implementation de la classe permet bien sur de negliger
certains termes de l'equation (le terme visqueux, le terme
convectif, tel ou tel terme source).
L'inconnue est le champ de vitesse.
#include <Navier_Stokes_WC.h>
Public Member Functions
Navier_Stokes_WC ()
~Navier_Stokes_WC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
Complete l'equation base,
associe la pression a l'equation,
complete la divergence, le gradient et le solveur pression.
Ajout de 2 termes sources: l'un representant la force centrifuge
dans le cas axi-symetrique,l'autre intervenant dans la resolution
en 2D axisymetrique.
virtual int impr (Sortie &os) const
Effectue quelques impressions sur un flot de sortie:
- maximum de div U
- terme convectif
- terme diffusif
- divergence
- gradient.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Navier_Stokes_WC & self_cast (Objet_U &)
static const Navier_Stokes_WC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Equation_base::printOn(Sortie&)
Ecrit l'equation sur un flot de sortie.
virtual Entree & readOn (Entree &)
Appel Equation_base::readOn(Entree& is)
En sortie verifie que l'on a bien lu:
- le terme diffusif,
- le terme convectif,
- le solveur en pression.
Detailed Description
classe Navier_Stokes_WC
Cette classe porte les termes de l'equation de la dynamique
pour un fluide sans modelisation de la turbulence.
On suppose l'hypothese de fluide quasi compressible.
Sous ces hypotheses, on utilise la forme suivante des equations de
Navier_Stokes:
DU/dt = div(terme visqueux) - gradP/rho + sources/rho
div U = W
avec DU/dt : derivee particulaire de la vitesse
rho : masse volumique
Rq : l'implementation de la classe permet bien sur de negliger
certains termes de l'equation (le terme visqueux, le terme
convectif, tel ou tel terme source).
L'inconnue est le champ de vitesse.
Definition at line 50 of file Navier_Stokes_WC.h.
Constructor & Destructor Documentation
Navier_Stokes_WC::Navier_Stokes_WC ()
Definition at line 27 of file Navier_Stokes_WC.cpp.
Navier_Stokes_WC::~Navier_Stokes_WC ()
Definition at line 27 of file Navier_Stokes_WC.cpp.
Member Function Documentation
void Navier_Stokes_WC::completer (void) [virtual]
Complete l'equation base,
associe la pression a l'equation,
complete la divergence, le gradient et le solveur pression.
Ajout de 2 termes sources: l'un representant la force centrifuge
dans le cas axi-symetrique,l'autre intervenant dans la resolution
en 2D axisymetrique.
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
Definition at line 66 of file Navier_Stokes_WC.cpp.
References List_Source::add(), Cerr, Equation_base::discretisation(), finl, Navier_Stokes_std::le_fluide, Equation_base::les_sources, Objet_U::que_suis_je(), and Source::typer_direct().
{
  Cerr<<"Navier_Stokes_WC::completer"<<finl;
  if (le_fluide->a_gravite())
    {
      Cerr << "Gravity = " << le_fluide->gravite() << finl;
      Cerr << "Creation of the buoyancy source term for the Navier_Stokes_WC equation : " << finl;
      Source t;
      Source& so=les_sources.add(t);
      Nom type_so = "Source_WC_Gravite_";
      Nom disc = discretisation().que_suis_je();
      if (disc=="VEFPreP1B") disc = "VEF";
      type_so += disc;
      so.typer_direct(type_so);
      so->associer_eqn(*this);
      Cerr << so->que_suis_je() << finl;
    }
  Navier_Stokes_Fluide_Dilatable_base::completer();
}
Objet_U * Navier_Stokes_WC::cree_instance () [static]
Reimplemented from Navier_Stokes_std.
Definition at line 27 of file Navier_Stokes_WC.cpp.
int Navier_Stokes_WC::duplique () const [virtual]
Implements Navier_Stokes_Fluide_Dilatable_base.
Definition at line 27 of file Navier_Stokes_WC.cpp.
const Type_info * Navier_Stokes_WC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
Definition at line 27 of file Navier_Stokes_WC.cpp.
int Navier_Stokes_WC::impr (Sortie & os) const [virtual]
Effectue quelques impressions sur un flot de sortie:
- maximum de div U
- terme convectif
- terme diffusif
- divergence
- gradient.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
< max|sum(u.ndS)i/(vol(i)/dt)|=max|div(U)i/dt| Calculation as OpenFOAM: http://foam.sourceforge.net/docs/cpp/a04190_source.html It is relative errors (normalized by the volume/dt)
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
Definition at line 86 of file Navier_Stokes_WC.cpp.
{
  return Navier_Stokes_Fluide_Dilatable_base::impr(os);
}
const Type_info * Navier_Stokes_WC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
Definition at line 27 of file Navier_Stokes_WC.cpp.
Sortie & Navier_Stokes_WC::printOn (Sortie & is) const [protected, virtual]
Simple appel a: Equation_base::printOn(Sortie&)
Ecrit l'equation sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
Definition at line 30 of file Navier_Stokes_WC.cpp.
{
  return Navier_Stokes_Fluide_Dilatable_base::printOn(is);
}
Entree & Navier_Stokes_WC::readOn (Entree & is) [protected, virtual]
Appel Equation_base::readOn(Entree& is)
En sortie verifie que l'on a bien lu:
- le terme diffusif,
- le terme convectif,
- le solveur en pression.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
Definition at line 35 of file Navier_Stokes_WC.cpp.
References Cerr, Process::exit(), finl, Navier_Stokes_std::le_fluide, O_U_Ptr::non_nul(), sub_type, and Ref_Fluide_base::valeur().
{
  Navier_Stokes_Fluide_Dilatable_base::readOn(is);
  assert(le_fluide.non_nul());
  if (!sub_type(Fluide_Weakly_Compressible,le_fluide.valeur()))
    {
      Cerr<<"ERROR : the Navier_Stokes_WC equation can be associated only to a weakly compressible fluid."<<finl;
      Process::exit();
    }
  return is;
}
Navier_Stokes_WC & Navier_Stokes_WC::self_cast (Objet_U & r) [static]
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
Definition at line 27 of file Navier_Stokes_WC.cpp.
const Navier_Stokes_WC & Navier_Stokes_WC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
Definition at line 27 of file Navier_Stokes_WC.cpp.
unsigned Navier_Stokes_WC::taille_memoire () const [virtual]
Reimplemented from Navier_Stokes_std.
Definition at line 27 of file Navier_Stokes_WC.cpp.
Member Data Documentation
const Type_info Navier_Stokes_WC::info_obj [static]
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
Definition at line 52 of file Navier_Stokes_WC.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Weakly_Compressible/Equations/Navier_Stokes_WC.h
src/ThHyd/Dilatable/Weakly_Compressible/Equations/Navier_Stokes_WC.cpp