TRUST: Support_Champ_Masse_Volumique Class Reference
Support_Champ_Masse_Volumique Class Reference
#include <Support_Champ_Masse_Volumique.h>
Public Member Functions
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Protected Member Functions
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Private Attributes
int support_ok_
Ref_Champ_base ref_champ_rho_
Detailed Description
Definition at line 21 of file Support_Champ_Masse_Volumique.h.
Constructor & Destructor Documentation
Support_Champ_Masse_Volumique()
Support_Champ_Masse_Volumique::Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
Definition at line 24 of file Support_Champ_Masse_Volumique.cpp.
                                                             :
  support_ok_(0)
{
}
~Support_Champ_Masse_Volumique()
Support_Champ_Masse_Volumique::~Support_Champ_Masse_Volumique () virtual
Destructeur virtuel (pour eviter les warnings)
Definition at line 31 of file Support_Champ_Masse_Volumique.cpp.
{
}
Member Function Documentation
associer_champ_masse_volumique()
void Support_Champ_Masse_Volumique::associer_champ_masse_volumique (const Champ_base & ch) virtual
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
Reimplemented in Op_Diff_negligeable.
Definition at line 52 of file Support_Champ_Masse_Volumique.cpp.
{
  if (! support_ok_)
    {
      Cerr << "Error in Support_Champ_Masse_Volumique::Associer_champ_masse_volumique" << finl;
      Cerr << " Support from a density field was not coded for this object" << finl;
      assert(0);
      Process::exit();
    }
  ref_champ_rho_ = ch;
}
References Cerr, Process::exit(), finl, ref_champ_rho_, and support_ok_.
declare_support_masse_volumique()
void Support_Champ_Masse_Volumique::declare_support_masse_volumique (int ok) protected virtual
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Definition at line 40 of file Support_Champ_Masse_Volumique.cpp.
{
  support_ok_ = ok;
}
References support_ok_.
Referenced by Modele_turbulence_hyd_nul::Modele_turbulence_hyd_nul(), Op_Diff_EF_base::Op_Diff_EF_base(), Op_Diff_PolyMAC_Elem::Op_Diff_PolyMAC_Elem(), Op_Diff_PolyMAC_P0_Elem::Op_Diff_PolyMAC_P0_Elem(), Op_Diff_VDF_Elem_base::Op_Diff_VDF_Elem_base(), Op_Diff_VDF_Face_base::Op_Diff_VDF_Face_base(), Op_Diff_VDF_var_Face::Op_Diff_VDF_var_Face(), Op_Diff_VEF_Face_Stab_Var::Op_Diff_VEF_Face_Stab_Var(), Op_Diff_VEF_Face_Var::Op_Diff_VEF_Face_Var(), Op_Diff_VEFP1NCP1B_Face_Var::Op_Diff_VEFP1NCP1B_Face_Var(), Op_Dift_EF_base::Op_Dift_EF_base(), Op_Dift_VDF_var_Face::Op_Dift_VDF_var_Face(), Op_Dift_VEF_Face_Var::Op_Dift_VEF_Face_Var(), Traitement_particulier_NS_EC_VDF::Traitement_particulier_NS_EC_VDF(), and Traitement_particulier_NS_EC_VEF::Traitement_particulier_NS_EC_VEF().
dissocier_champ_masse_volumique()
void Support_Champ_Masse_Volumique::dissocier_champ_masse_volumique () virtual
Annule la reference a la masse volumique.
Definition at line 66 of file Support_Champ_Masse_Volumique.cpp.
{
  REF(Champ_base) ref_nulle;
  ref_champ_rho_ = ref_nulle;
}
References REF, and ref_champ_rho_.
get_champ_masse_volumique()
const Champ_base & Support_Champ_Masse_Volumique::get_champ_masse_volumique () const virtual
Renvoie le champ de masse volumique.
Definition at line 82 of file Support_Champ_Masse_Volumique.cpp.
{
  assert(ref_champ_rho_.non_nul());
  const Champ_base& ch = ref_champ_rho_.valeur();
  return ch;
}
References O_U_Ptr::non_nul(), ref_champ_rho_, and Ref_Champ_base::valeur().
Referenced by Op_Diff_EF_base::calculer_dt_stab(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Traitement_particulier_NS_EC::calculer_Ec(), Op_Diff_VEF_base::calculer_pour_post(), and Op_Dift_VEF_Face::calculer_pour_post().
has_champ_masse_volumique()
int Support_Champ_Masse_Volumique::has_champ_masse_volumique () const virtual
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
Definition at line 74 of file Support_Champ_Masse_Volumique.cpp.
{
  int ref_non_nulle = ref_champ_rho_.non_nul();
  return ref_non_nulle;
}
References O_U_Ptr::non_nul(), and ref_champ_rho_.
Referenced by Op_Diff_EF_base::calculer_dt_stab(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Diff_PolyMAC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Traitement_particulier_NS_EC::calculer_Ec(), Op_Diff_VEF_base::calculer_pour_post(), and Op_Dift_VEF_Face::calculer_pour_post().
support_ok()
const int & Support_Champ_Masse_Volumique::support_ok () const inline
Definition at line 43 of file Support_Champ_Masse_Volumique.h.
{
  return support_ok_;
}
References support_ok_.
Member Data Documentation
ref_champ_rho_
Ref_Champ_base Support_Champ_Masse_Volumique::ref_champ_rho_ private
Definition at line 40 of file Support_Champ_Masse_Volumique.h.
Referenced by associer_champ_masse_volumique(), dissocier_champ_masse_volumique(), get_champ_masse_volumique(), and has_champ_masse_volumique().
support_ok_
int Support_Champ_Masse_Volumique::support_ok_ private
Definition at line 37 of file Support_Champ_Masse_Volumique.h.
Referenced by associer_champ_masse_volumique(), declare_support_masse_volumique(), and support_ok().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Support_Champ_Masse_Volumique.h
src/Kernel/Framework/Support_Champ_Masse_Volumique.cpp