TRUST: Motcle Class Reference
Motcle Class Reference
Une chaine de caractere (Nom) en majuscules.
#include <Motcle.h>
Public Member Functions
~Motcle ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Motcle ()
Constructeur par defaut
Construit un Nom puis le passe en majuscule.
Motcle (const Motcle &nom)
Construction d'un Motcle par copie.
Motcle & operator= (const Motcle &)
Construction par copie
Utilise l'implementation de la classe Nom.
Motcle (const char *const nom)
Construction d'un Motcle a partie d'une chaine de caracteres
Construit un Nom puis le passe en majuscules.
Motcle (const std::string &nom)
Motcle (const Nom &)
Motcle & operator= (const char *const)
Construction a partir d'une chaine de caracteres
Utilise l'implementation de la classe Nom.
Motcle & operator= (const Nom &)
Motcle & operator+= (const char *const)
int selftest ()
Autotest de la classe Motcle
Effectue des affectations de controle
Retourne toujours 1.
int debute_par (const char *const n) const override
int finit_par (const char *const n) const override
int find (const char *const n) const override
Public Member Functions inherited from Nom
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Nom ()
construit "??"
Nom (int i)
Nom(485)="485".
Nom (const char *nom)
Construction d'un nom a partir d'une chaine de caracteres
La chaine est copiee.
Nom (const std::string &nom)
Nom (const Nom &)
Constructeur par copie d'un nom.
Nom (char c)
Construction d'un nom a partir d'un caractere.
Nom (double)
Construction d'un nom a partir d'un flottant
La chaine cree est la representation du nombre reel (sprintf)
Nom (double le_reel, const char *format)
Construction d'un nom a partir d'un flottant
La chaine cree est la representation du nombre reel (sprintf)
Le format du nombre represente par la chaine est donne par format.
~Nom () override
Destructeur.
operator const char * () const
Retourne un pointeur sur la chaine de caractere du nom.
Nom & majuscule ()
Transforme le nom en majuscules
Seules les lettres 'a'-'z' sont modifiees.
int est_egal_a (const Objet_U &) const override
Comparaison avec un Objet_U
l'Objet_U est caste en Nom pour la comparaison.
int longueur () const
Renvoie le nombre de caracteres de la chaine du Nom
y compris le caractere zero de fin de chaine.
Exemple : Nom("hello").longueur() == 6.
const Nom & le_nom () const override
Renvoie *this;.
Nom & operator= (const char *const)
Copie la chaine nom.
Modif BM pour que nom puisse pointer sur une sous-partie de nom_.
Nom & operator= (const Nom &)
Copie le Nom nom.
Nom operator+ (const Nom &) const
Concatenation avec un Nom.
Nom & operator+= (const Nom &x)
Concatenation avec un Nom.
Nom & operator+= (const char *)
Nom & operator+= (char x)
concatenation de chaine
Nom & suffix (const char *const)
Extraction de suffixe :
Nom x("azerty");
x.suffix("aze")
x contient "rty".
const Nom getSuffix (const char *const) const
Nom & prefix (const char *const)
const Nom getPrefix (const char *const) const
Nom nom_me (int, const char *prefix=0, int without_padding=0) const
Insere _prefix000n (n=me() ou nproc()) dans un nom de fichier (par ex:toto.titi) pour donner toto_prefix000n.titi.
Nom substr_old (const int, const int) const
Retourne un nom selon la commande usuelle substr
ATTENTION : deb = 1 => premier caractere de la chaine !!!
Nom basename () const
Retourne fichier si le nom est sous la forme /toto/titi/fichier.
virtual int find (const char *const n) const
virtual int debute_par (const char *const n) const
virtual int finit_par (const char *const n) const
int find (const std::string &n) const
int debute_par (const std::string &) const
int finit_par (const std::string &) const
bool contient (const Nom &nom)
const char * getChar () const
const std::string & getString () const
std::string & getString ()
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Motcle & self_cast (Objet_U &)
static const Motcle & self_cast (const Objet_U &)
Static Public Member Functions inherited from Nom
static Objet_U * cree_instance ()
static const Type_info * info ()
static Nom & self_cast (Objet_U &)
static const Nom & self_cast (const Objet_U &)
static void sed_check_case_non_sensitive (int i)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Nom
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture d'un Motcle sur un flot de sortie
Utilise l'implementation de la classe Nom.
Entree & readOn (Entree &) override
Lecture d'un Motcle dans un flot d'entree
Utilise l'implementation de la classe Nom
Passe ensuite le Nom en majuscules.
Protected Member Functions inherited from Nom
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un Nom sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un nom.
En cas d'echec, le nom vaut "??" a la sortie.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Friends
int operator== (const Motcle &, const Motcle &)
Comparaison d'un mot cle avec une chaine de caracteres.
int operator!= (const Motcle &, const Motcle &)
Comparaison d'un mot cle avec une chaine de caracteres.
int operator== (const Motcle &, const char *const)
int operator!= (const Motcle &, const char *const)
int operator== (const char *const, const Motcle &)
int operator!= (const char *const, const Motcle &)
int operator== (const Motcle &, const Nom &)
int operator!= (const Motcle &, const Nom &)
int operator== (const Nom &, const Motcle &)
int operator!= (const Nom &, const Motcle &)
Additional Inherited Members
Protected Attributes inherited from Nom
std::string nom_
Static Protected Attributes inherited from Nom
static int nb_noms =0
static int check_case_non_sensitive_ =1
pour descativer dans ==
Detailed Description
Une chaine de caractere (Nom) en majuscules.
Definition at line 27 of file Motcle.h.
Constructor & Destructor Documentation
~Motcle()
Motcle::~Motcle ()
Definition at line 20 of file Motcle.cpp.
Motcle() [1/5]
Motcle::Motcle ()
Constructeur par defaut
Construit un Nom puis le passe en majuscule.
Definition at line 104 of file Motcle.cpp.
               : Nom()
{
  majuscule();
}
References Nom::majuscule().
Motcle() [2/5]
Motcle::Motcle (const Motcle & nom)
Construction d'un Motcle par copie.
Definition at line 154 of file Motcle.cpp.
                                : Nom(nom)
{
}
Motcle() [3/5]
Motcle::Motcle (const char *const nom)
Construction d'un Motcle a partie d'une chaine de caracteres
Construit un Nom puis le passe en majuscules.
Definition at line 125 of file Motcle.cpp.
                                    : Nom(nom)
{
  majuscule();
}
References Nom::majuscule().
Motcle() [4/5]
Motcle::Motcle (const std::string & nom)
Definition at line 130 of file Motcle.cpp.
                                   : Nom(nom)
{
  majuscule();
}
References Nom::majuscule().
Motcle() [5/5]
Motcle::Motcle (const Nom & nom)
Definition at line 135 of file Motcle.cpp.
                             : Nom(nom)
{
  majuscule();
}
References Nom::majuscule().
Member Function Documentation
cree_instance()
Objet_U * Motcle::cree_instance () static
Definition at line 20 of file Motcle.cpp.
debute_par()
int Motcle::debute_par (const char *const n) const override virtual
Reimplemented from Nom.
Definition at line 454 of file Motcle.cpp.
{
  Motcle mm(mot);
  return Nom::debute_par(mm);
}
References Nom::debute_par().
Referenced by Sonde::completer(), Format_Post_Lata_V1::ecrire_champ_lata_V1(), and Mod_turb_hyd::readOn().
duplique()
int Motcle::duplique () const override virtual
Implements Objet_U.
Definition at line 20 of file Motcle.cpp.
find()
int Motcle::find (const char *const n) const override virtual
Reimplemented from Nom.
Definition at line 460 of file Motcle.cpp.
{
  Motcle mm(mot);
  return Nom::find(mm);
}
References Nom::find().
finit_par()
int Motcle::finit_par (const char *const n) const override virtual
Reimplemented from Nom.
Definition at line 447 of file Motcle.cpp.
{
  Motcle mm(mot);
  return Nom::finit_par(mm);
}
References Nom::finit_par().
get_info()
const Type_info * Motcle::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 20 of file Motcle.cpp.
info()
const Type_info * Motcle::info () static
Definition at line 20 of file Motcle.cpp.
operator+=()
Motcle & Motcle::operator+= (const char * const mot)
Definition at line 430 of file Motcle.cpp.
{
  Nom::operator+=(mot);
  majuscule();
  return *this;
}
References Nom::majuscule(), and Nom::operator+=().
operator=() [1/3]
Motcle & Motcle::operator= (const char * const mot)
Construction a partir d'une chaine de caracteres
Utilise l'implementation de la classe Nom.
Returns
Motcle&
Signification: reference sur le Motcle cree
Contraintes:
Definition at line 173 of file Motcle.cpp.
{
  Nom::operator=(mot);
  majuscule();
  return *this;
}
References Nom::majuscule(), and Nom::operator=().
operator=() [2/3]
Motcle & Motcle::operator= (const Motcle & mot)
Construction par copie
Utilise l'implementation de la classe Nom.
Returns
Motcle&
Signification: reference sur le Motcle modifie
Contraintes:
Definition at line 202 of file Motcle.cpp.
{
  Nom::operator=(mot);
  return *this;
}
References Nom::operator=().
operator=() [3/3]
Motcle & Motcle::operator= (const Nom & mot)
Definition at line 180 of file Motcle.cpp.
{
  Nom::operator=(mot);
  majuscule();
  return *this;
}
References Nom::majuscule(), and Nom::operator=().
printOn()
Sortie & Motcle::printOn (Sortie & s) const override protected virtual
Ecriture d'un Motcle sur un flot de sortie
Utilise l'implementation de la classe Nom.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 39 of file Motcle.cpp.
{
  return Nom::printOn(s);
}
References Nom::printOn().
readOn()
Entree & Motcle::readOn (Entree & s) override protected virtual
Lecture d'un Motcle dans un flot d'entree
Utilise l'implementation de la classe Nom
Passe ensuite le Nom en majuscules.
Returns
Entree&
Signification: le flux d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 81 of file Motcle.cpp.
{
  Nom::readOn(s);
  majuscule();
  return s;
}
References Nom::majuscule(), and Nom::readOn().
self_cast() [1/2]
const Motcle & Motcle::self_cast (const Objet_U & r) static
Definition at line 20 of file Motcle.cpp.
self_cast() [2/2]
Motcle & Motcle::self_cast (Objet_U & r) static
Definition at line 20 of file Motcle.cpp.
selftest()
int Motcle::selftest ()
Autotest de la classe Motcle
Effectue des affectations de controle
Retourne toujours 1.
Returns
int
Signification: code de retour; retourne toujours 1
Contraintes:
Definition at line 244 of file Motcle.cpp.
{
  Nom un_nom;
  Motcle un_motcle("PasOk");
  Motcle un_autre(un_nom);
  un_nom="Ok";
  un_motcle=un_nom;
  un_motcle="Ok";
  un_motcle=un_autre;
  return 1;
}
taille_memoire()
unsigned Motcle::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 20 of file Motcle.cpp.
Friends And Related Function Documentation
operator!= [1/5]
int operator!= (const char * const nom, const Motcle & un_mot) friend
Definition at line 415 of file Motcle.cpp.
{
  return ! (nom == un_mot);
}
operator!= [2/5]
int operator!= (const Motcle & un_mot, const char * const nom) friend
Definition at line 410 of file Motcle.cpp.
{
  return ! (un_mot == nom);
}
operator!= [3/5]
int operator!= (const Motcle & nom, const Motcle & un_mot) friend
Comparaison d'un mot cle avec une chaine de caracteres.
Returns
int
Signification: 1 si le Nom du mot est different de la chaine
Contraintes:
Definition at line 405 of file Motcle.cpp.
{
  return ! (nom == un_mot);
}
operator!= [4/5]
int operator!= (const Motcle & un_mot, const Nom & nom) friend
Definition at line 420 of file Motcle.cpp.
{
  return ! (un_mot == nom);
}
operator!= [5/5]
int operator!= (const Nom & nom, const Motcle & un_mot) friend
Definition at line 425 of file Motcle.cpp.
{
  return ! (nom == un_mot);
}
operator== [1/5]
int operator== (const char * const nom, const Motcle & un_mot) friend
Definition at line 370 of file Motcle.cpp.
{
  return (un_mot == nom);
}
operator== [2/5]
int operator== (const Motcle & un_mot, const char * const nom) friend
Definition at line 364 of file Motcle.cpp.
{
  const int resu = strcmp_uppercase((const char *)un_mot, nom);
  return (resu == 0);
}
operator== [3/5]
int operator== (const Motcle & nom, const Motcle & un_mot) friend
Comparaison d'un mot cle avec une chaine de caracteres.
Returns
int
Signification: 1 si le Nom du mot est egal a la chaine
Contraintes:
Definition at line 358 of file Motcle.cpp.
{
  const int resu = strcmp_uppercase((const char *) nom, (const char *)un_mot);
  return (resu == 0);
}
operator== [4/5]
int operator== (const Motcle & un_mot, const Nom & nom) friend
Definition at line 375 of file Motcle.cpp.
{
  const int resu = strcmp_uppercase((const char *)un_mot, (const char *) nom);
  return (resu == 0);
}
operator== [5/5]
int operator== (const Nom & nom, const Motcle & un_mot) friend
Definition at line 381 of file Motcle.cpp.
{
  return (un_mot == nom);
}
Member Data Documentation
info_obj
const Type_info Motcle::info_obj static
Definition at line 29 of file Motcle.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Motcle.h
src/Kernel/Utilitaires/Motcle.cpp