TRUST: Traitement_particulier_Solide Class Reference
Traitement_particulier_Solide Class Reference
classe Traitement_particulier_Solide
#include <Traitement_particulier_Solide.h>
Public Member Functions
Traitement_particulier_Solide ()
~Traitement_particulier_Solide ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_eqn (const Equation_base &)
void preparer_calcul_particulier (void)
void post_traitement_particulier (void)
Entree & lire (Entree &)
void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Traitement_particulier_Solide & self_cast (Objet_U &)
static const
Traitement_particulier_Solide & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Detailed Description
classe Traitement_particulier_Solide
Definition at line 39 of file Traitement_particulier_Solide.h.
Constructor & Destructor Documentation
Traitement_particulier_Solide::Traitement_particulier_Solide ()
Definition at line 27 of file Traitement_particulier_Solide.cpp.
Traitement_particulier_Solide::~Traitement_particulier_Solide ()
Definition at line 27 of file Traitement_particulier_Solide.cpp.
Member Function Documentation
void Traitement_particulier_Solide::associer_eqn (const Equation_base & eqn) [inline]
Definition at line 55 of file Traitement_particulier_Solide.h.
References Traitement_particulier_Solide_base::associer_eqn(), and Deriv_Traitement_particulier_Solide_base::valeur().
Referenced by Conduction::lire_motcle_non_standard().
{
  valeur().associer_eqn(eqn);
}
Objet_U * Traitement_particulier_Solide::cree_instance () [static]
Reimplemented from Deriv_Traitement_particulier_Solide_base.
Definition at line 27 of file Traitement_particulier_Solide.cpp.
int Traitement_particulier_Solide::duplique () const [virtual]
Reimplemented from Deriv_Traitement_particulier_Solide_base.
Definition at line 27 of file Traitement_particulier_Solide.cpp.
void Traitement_particulier_Solide::en_cours_de_resolution (int nb_op, DoubleTab & u, DoubleTab & u_av, double dt) [inline]
Definition at line 76 of file Traitement_particulier_Solide.h.
References Traitement_particulier_Solide_base::en_cours_de_resolution(), and Deriv_Traitement_particulier_Solide_base::valeur().
{
  valeur().en_cours_de_resolution(nb_op,u,u_av,dt);
}
const Type_info * Traitement_particulier_Solide::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Traitement_particulier_Solide_base.
Definition at line 27 of file Traitement_particulier_Solide.cpp.
const Type_info * Traitement_particulier_Solide::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Traitement_particulier_Solide_base.
Definition at line 27 of file Traitement_particulier_Solide.cpp.
Entree & Traitement_particulier_Solide::lire (Entree & is) [inline]
Definition at line 70 of file Traitement_particulier_Solide.h.
References Traitement_particulier_Solide_base::lire(), and Deriv_Traitement_particulier_Solide_base::valeur().
Referenced by Conduction::lire_motcle_non_standard().
{
  return valeur().lire(is);
}
void Traitement_particulier_Solide::post_traitement_particulier (void) [inline]
Definition at line 65 of file Traitement_particulier_Solide.h.
References Traitement_particulier_Solide_base::post_traitement_particulier(), and Deriv_Traitement_particulier_Solide_base::valeur().
Referenced by Conduction::mettre_a_jour().
{
  valeur().post_traitement_particulier();
}
void Traitement_particulier_Solide::preparer_calcul_particulier (void) [inline]
Definition at line 60 of file Traitement_particulier_Solide.h.
References Traitement_particulier_Solide_base::preparer_calcul_particulier(), and Deriv_Traitement_particulier_Solide_base::valeur().
Referenced by Conduction::lire_motcle_non_standard().
{
  valeur().preparer_calcul_particulier();
}
Sortie & Traitement_particulier_Solide::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_Traitement_particulier_Solide_base.
Definition at line 30 of file Traitement_particulier_Solide.cpp.
References DERIV.
{
  return DERIV(Traitement_particulier_Solide_base)::printOn(is);
}
Entree & Traitement_particulier_Solide::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_Traitement_particulier_Solide_base.
Definition at line 36 of file Traitement_particulier_Solide.cpp.
References DERIV.
{
  return DERIV(Traitement_particulier_Solide_base)::readOn(is);
}
Traitement_particulier_Solide & Traitement_particulier_Solide::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Traitement_particulier_Solide_base.
Definition at line 27 of file Traitement_particulier_Solide.cpp.
const Traitement_particulier_Solide & Traitement_particulier_Solide::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Traitement_particulier_Solide_base.
Definition at line 27 of file Traitement_particulier_Solide.cpp.
unsigned Traitement_particulier_Solide::taille_memoire () const [virtual]
Reimplemented from Deriv_Traitement_particulier_Solide_base.
Definition at line 27 of file Traitement_particulier_Solide.cpp.
Member Data Documentation
const Type_info Traitement_particulier_Solide::info_obj [static]
Reimplemented from Deriv_Traitement_particulier_Solide_base.
Definition at line 41 of file Traitement_particulier_Solide.h.
The documentation for this class was generated from the following files:
src/ThSol/Traitement_particulier_Solide.h
src/ThSol/Traitement_particulier_Solide.cpp