TRUST: Terme_Source_Coriolis Class Reference
Terme_Source_Coriolis Class Reference
#include <Terme_Source_Coriolis.h>
Public Member Functions
void associer_eqn (const Navier_Stokes_std &)
const DoubleVect & omega () const
const Navier_Stokes_std & eq_hydraulique () const
void mettre_a_jour (double temps)
Protected Member Functions
Entree & lire_donnees (Entree &)
Protected Attributes
DoubleVect omega_
Ref_Navier_Stokes_std eq_hydraulique_
double dim
Detailed Description
Definition at line 22 of file Terme_Source_Coriolis.h.
Member Function Documentation
associer_eqn()
void Terme_Source_Coriolis::associer_eqn (const Navier_Stokes_std & eq_hyd)
Definition at line 19 of file Terme_Source_Coriolis.cpp.
{
  eq_hydraulique_ = eq_hyd;
}
References eq_hydraulique_.
Referenced by Terme_Source_Coriolis_VDF_Face::associer_pb().
eq_hydraulique()
const Navier_Stokes_std & Terme_Source_Coriolis::eq_hydraulique () const inline
Definition at line 49 of file Terme_Source_Coriolis.h.
{
  return eq_hydraulique_.valeur();
}
References eq_hydraulique_, and Ref_Navier_Stokes_std::valeur().
Referenced by Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis().
lire_donnees()
Entree & Terme_Source_Coriolis::lire_donnees (Entree & is) protected
Definition at line 24 of file Terme_Source_Coriolis.cpp.
{
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Motcle motlu;
  int dim_pb=Objet_U::dimension;
  is >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "Erreur a la lecture des parametres de Terme_Source_Coriolis " << finl;
      Cerr << "On attendait " << accolade_ouverte << " a la place de "  << motlu << finl;
      Process::exit();
    }
  is >> motlu;
  if (motlu ==  Motcle("omega") )
    {
      is >> dim;
      if(dim_pb!=dim)
        {
          Cerr << "Error in Terme_Source_Coriolis::lire_donnees" << finl;
          Cerr << "Warning ! Dimension of vector after key-word 'omega'" << finl;
          Cerr << "is not correct : dimension of PB (" << dim_pb << ")!= " << dim << finl;
          Process::exit();
        }
      if (dim == 2)
        {
          omega_.resize(1);
          is >> omega_(0);
        }
      else
        {
          if (dim==3)
            {
              omega_.resize(3);
              is >> omega_(0);
              is >> omega_(1);
              is >> omega_(2);
            }
          else
            {
              Cerr << "Erreur a la lecture des parametres de Terme_Source_Coriolis" << finl;
              Cerr << "omega est de dimension 2 ou 3 et vous avez entre " << dim << finl;
              Process::exit();
            }
        }
    }
  else
    {
      Cerr << "Erreur a la lecture des parametres de Terme_Source_Coriolis " << finl;
      Cerr << "On attendait le mot cle omega a la place de  "  << motlu << finl;
      Process::exit();
    }
  is >> motlu;
  if (motlu != accolade_fermee)
    {
      Cerr << "Erreur a la lecture des parametres de Terme_Source_Coriolis " << finl;
      Cerr << "On attendait " << accolade_fermee << " a la place de "  << motlu << finl;
      Cerr << "Attention! : en 2D, omega est de dimension 1!!!" << finl;
      Process::exit();
    }
  return is;
}
References Cerr, dim, Objet_U::dimension, Process::exit(), finl, omega_, and TRUSTVect< _TYPE_ >::resize().
Referenced by Terme_Source_Coriolis_VDF_Face::readOn(), and Terme_Source_Coriolis_QC_VDF_Face::readOn().
mettre_a_jour()
void Terme_Source_Coriolis::mettre_a_jour (double temps) inline
Definition at line 30 of file Terme_Source_Coriolis.h.
{ }
Referenced by Terme_Source_Coriolis_VDF_Face::mettre_a_jour().
omega()
const DoubleVect & Terme_Source_Coriolis::omega () const inline
Definition at line 44 of file Terme_Source_Coriolis.h.
{
  return omega_;
}
References omega_.
Referenced by Terme_Source_Coriolis_VDF_Face::omega().
Member Data Documentation
dim
double Terme_Source_Coriolis::dim protected
Definition at line 36 of file Terme_Source_Coriolis.h.
Referenced by lire_donnees().
eq_hydraulique_
Ref_Navier_Stokes_std Terme_Source_Coriolis::eq_hydraulique_ protected
Definition at line 34 of file Terme_Source_Coriolis.h.
Referenced by associer_eqn(), and eq_hydraulique().
omega_
DoubleVect Terme_Source_Coriolis::omega_ protected
Definition at line 33 of file Terme_Source_Coriolis.h.
Referenced by lire_donnees(), and omega().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Sources/Terme_Source_Coriolis.h
src/ThHyd/Incompressible/Sources/Terme_Source_Coriolis.cpp