TRUST: Vect_Motcle Class Reference
Vect_Motcle Class Reference
#include <Motcle.h>
Public Member Functions
~Vect_Motcle ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Vect_Motcle ()
Vect_Motcle (int)
const Motcle & operator[] (int) const
const Motcle & operator() (int i) const
Motcle & operator[] (int)
Motcle & operator() (int i)
Vect_Motcle (const Vect_Motcle &)
Vect_Motcle & operator= (const Vect_Motcle &)
Motcle & add (const Motcle &titi)
Motcle & add ()
void add (const Vect_Motcle &)
Entree & lit (Entree &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Vect_Motcle & self_cast (Objet_U &)
static const Vect_Motcle & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Objet_U * cree_une_instance () const
methhode surcharge par les classes filles pour fournir la bonne
instance aux constructeurs au readOn....
Detailed Description
Definition at line 70 of file Motcle.h.
Constructor & Destructor Documentation
Vect_Motcle::~Vect_Motcle ()
Definition at line 26 of file Motcle.cpp.
Vect_Motcle::Vect_Motcle ()
Definition at line 26 of file Motcle.cpp.
Vect_Motcle::Vect_Motcle (int i)
Definition at line 26 of file Motcle.cpp.
Vect_Motcle::Vect_Motcle (const Vect_Motcle & avect)
Definition at line 26 of file Motcle.cpp.
Member Function Documentation
Motcle & Vect_Motcle::add (const Motcle & titi)
Definition at line 26 of file Motcle.cpp.
Referenced by Objet_a_lire::add_dict(), Champ_Generique_refChamp::get_property_names(), Postraitement_lata::lire_champs(), and Equation_base::lire_motcle_non_standard().
Motcle & Vect_Motcle::add ()
Definition at line 26 of file Motcle.cpp.
void Vect_Motcle::add (const Vect_Motcle & data_to_add)
Definition at line 26 of file Motcle.cpp.
Objet_U * Vect_Motcle::cree_instance () [static]
Reimplemented from vect_impl.
Reimplemented in Motcles.
Definition at line 26 of file Motcle.cpp.
Objet_U * Vect_Motcle::cree_une_instance () const [protected, virtual]
methhode surcharge par les classes filles pour fournir la bonne
instance aux constructeurs au readOn....
Reimplemented from vect_impl.
Definition at line 26 of file Motcle.cpp.
int Vect_Motcle::duplique () const [virtual]
Reimplemented from vect_impl.
Reimplemented in Motcles.
Definition at line 26 of file Motcle.cpp.
const Type_info * Vect_Motcle::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from vect_impl.
Reimplemented in Motcles.
Definition at line 26 of file Motcle.cpp.
const Type_info * Vect_Motcle::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from vect_impl.
Reimplemented in Motcles.
Definition at line 26 of file Motcle.cpp.
Entree & Vect_Motcle::lit (Entree & s)
Reimplemented from vect_impl.
Definition at line 26 of file Motcle.cpp.
const Motcle& Vect_Motcle::operator() (int i) const [inline]
Definition at line 70 of file Motcle.h.
: public VECT(Motcle)
Motcle& Vect_Motcle::operator() (int i) [inline]
Definition at line 70 of file Motcle.h.
: public VECT(Motcle)
Vect_Motcle & Vect_Motcle::operator= (const Vect_Motcle & avect)
Definition at line 26 of file Motcle.cpp.
const Motcle & Vect_Motcle::operator[] (int i) const [inline]
Reimplemented from vect_impl.
Definition at line 70 of file Motcle.h.
: public VECT(Motcle)
Motcle & Vect_Motcle::operator[] (int i) [inline]
Reimplemented from vect_impl.
Definition at line 70 of file Motcle.h.
: public VECT(Motcle)
Sortie & Vect_Motcle::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from vect_impl.
Reimplemented in Motcles.
Definition at line 26 of file Motcle.cpp.
Entree & Vect_Motcle::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from vect_impl.
Reimplemented in Motcles.
Definition at line 26 of file Motcle.cpp.
const Vect_Motcle & Vect_Motcle::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from vect_impl.
Reimplemented in Motcles.
Definition at line 26 of file Motcle.cpp.
Vect_Motcle & Vect_Motcle::self_cast (Objet_U & r) [static]
Reimplemented from vect_impl.
Reimplemented in Motcles.
Definition at line 26 of file Motcle.cpp.
unsigned Vect_Motcle::taille_memoire () const [virtual]
Reimplemented from vect_impl.
Reimplemented in Motcles.
Definition at line 26 of file Motcle.cpp.
Member Data Documentation
const Type_info Vect_Motcle::info_obj [static]
Reimplemented from vect_impl.
Reimplemented in Motcles.
Definition at line 70 of file Motcle.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Motcle.h
src/Kernel/Utilitaires/Motcle.cpp