TRUST: Champ_P1_PolyMAC Class Reference
Champ_P1_PolyMAC Class Reference
#include <Champ_P1_PolyMAC.h>
Public Member Functions
Champ_P1_PolyMAC ()
~Champ_P1_PolyMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Zone_PolyMAC & zone_PolyMAC () const
void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
int imprime (Sortie &, int) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_P1_PolyMAC & self_cast (Objet_U &)
static const Champ_P1_PolyMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
virtual Entree & readOn (Entree &)
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Protected Attributes
Ref_Zone_VF la_zone_VF
Detailed Description
Definition at line 31 of file Champ_P1_PolyMAC.h.
Constructor & Destructor Documentation
Champ_P1_PolyMAC::Champ_P1_PolyMAC ()
Definition at line 29 of file Champ_P1_PolyMAC.cpp.
Champ_P1_PolyMAC::~Champ_P1_PolyMAC ()
Definition at line 29 of file Champ_P1_PolyMAC.cpp.
Member Function Documentation
void Champ_P1_PolyMAC::associer_zone_dis_base (const Zone_dis_base & z_dis) [virtual]
Returns:
z_dis
Signification: la zone discretise
Contraintes:
Reimplemented from Champ_base.
Definition at line 77 of file Champ_P1_PolyMAC.cpp.
References la_zone_VF, and ref_cast.
{
  la_zone_VF=ref_cast(Zone_VF, z_dis);
}
Objet_U * Champ_P1_PolyMAC::cree_instance () [static]
Definition at line 29 of file Champ_P1_PolyMAC.cpp.
int Champ_P1_PolyMAC::duplique () const [virtual]
Implements Champ_Inc_P1_base.
Definition at line 29 of file Champ_P1_PolyMAC.cpp.
const Type_info * Champ_P1_PolyMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Inc_P1_base.
Definition at line 29 of file Champ_P1_PolyMAC.cpp.
int Champ_P1_PolyMAC::imprime (Sortie & os, int ncomp) const [virtual]
Reimplemented from Champ_Inc_base.
Definition at line 100 of file Champ_P1_PolyMAC.cpp.
References Domaine::coord_sommets(), Cout, Objet_U::dimension, Zone::domaine(), finl, Field_base::nb_compo_, Domaine::nb_som(), Champ_Inc_base::valeurs(), Zone_dis_base::zone(), and zone_dis_base().
{
  const Zone_dis_base& zone_dis = zone_dis_base();
  const Zone& zone = zone_dis.zone();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  const int nb_som = zone.domaine().nb_som();
  const DoubleTab& val = valeurs();
  int som;
  os << nb_som << finl;
  for (som=0; som<nb_som; som++)
    {
      if (dimension==3)
        os << coord(som,0) << " " << coord(som,1) << " " << coord(som,2) << " " ;
      if (dimension==2)
        os << coord(som,0) << " " << coord(som,1) << " " ;
      if (nb_compo_ == 1)
        os << val(som) << finl;
      else
        os << val(som,ncomp) << finl;
    }
  os << finl;
  Cout << "Champ_P1_PolyMAC::imprime FIN >>>>>>>>>> " << finl;
  return 1;
}
const Type_info * Champ_P1_PolyMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Inc_P1_base.
Definition at line 29 of file Champ_P1_PolyMAC.cpp.
Sortie & Champ_P1_PolyMAC::printOn (Sortie & os) const [protected, virtual]
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Inc_P1_base.
Definition at line 33 of file Champ_P1_PolyMAC.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Champ_P1_PolyMAC::readOn (Entree & is) [protected, virtual]
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Inc_P1_base.
Definition at line 41 of file Champ_P1_PolyMAC.cpp.
References Champ_Inc_base::lire_donnees().
{
  lire_donnees(s) ;
  return s ;
}
Champ_P1_PolyMAC & Champ_P1_PolyMAC::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Inc_P1_base.
Definition at line 29 of file Champ_P1_PolyMAC.cpp.
const Champ_P1_PolyMAC & Champ_P1_PolyMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Inc_P1_base.
Definition at line 29 of file Champ_P1_PolyMAC.cpp.
unsigned Champ_P1_PolyMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 29 of file Champ_P1_PolyMAC.cpp.
const Zone_dis_base & Champ_P1_PolyMAC::zone_dis_base () const [virtual]
Reimplemented from Champ_base.
Definition at line 60 of file Champ_P1_PolyMAC.cpp.
References la_zone_VF, and Ref_Zone_VF::valeur().
Referenced by PolyMAC_discretisation::creer_champ_vorticite(), and imprime().
{
  return la_zone_VF.valeur();
}
const Zone_PolyMAC & Champ_P1_PolyMAC::zone_PolyMAC () const
Returns:
la_zone_PolyMAC_P1.valeur()
Signification:
Contraintes:
Definition at line 95 of file Champ_P1_PolyMAC.cpp.
References la_zone_VF, ref_cast, and Ref_Zone_VF::valeur().
{
  return ref_cast(Zone_PolyMAC, la_zone_VF.valeur());
}
Member Data Documentation
const Type_info Champ_P1_PolyMAC::info_obj [static]
Reimplemented from Champ_Inc_P1_base.
Definition at line 33 of file Champ_P1_PolyMAC.h.
Ref_Zone_VF Champ_P1_PolyMAC::la_zone_VF [protected]
Definition at line 44 of file Champ_P1_PolyMAC.h.
Referenced by associer_zone_dis_base(), zone_dis_base(), and zone_PolyMAC().
The documentation for this class was generated from the following files:
src/PolyMAC/Champs/Champ_P1_PolyMAC.h
src/PolyMAC/Champs/Champ_P1_PolyMAC.cpp