TRUST: FichierHDFPar Class Reference
FichierHDFPar Class Reference
Parallel collective version of FichierHDF, to be used for all concurrent reading/writing on HDF files.
#include <FichierHDFPar.h>
Public Member Functions
FichierHDFPar ()
~FichierHDFPar () override
void set_collective_op (bool b)
Public Member Functions inherited from FichierHDF
FichierHDF ()
virtual ~FichierHDF ()
virtual void create (Nom filename)
virtual void open (Nom filename, bool readOnly)
virtual void close ()
virtual void create_and_fill_dataset_MW (Nom dataset_basename, Sortie_Brute &sortie)
virtual void create_and_fill_dataset_MW (Nom dataset_basename, SChaine &sortie)
virtual void create_and_fill_dataset_SW (Nom datasetname, Sortie_Brute &sortie)
virtual void read_dataset (Nom dataset_basename, int proc_rank, Entree_Brute &entree)
void fill_dataset (Nom dataset_name, Sortie_Brute &sortie)
virtual bool exists (const char *dataset_name)
void check_int_size (Nom filename)
void set_int_size ()
Protected Member Functions
void prepare_file_props () override
void prepare_dataset_props () override
virtual void prepare_file_props ()
virtual void prepare_dataset_props ()
Private Member Functions
FichierHDFPar & operator= (const FichierHDFPar &)
FichierHDFPar (const FichierHDFPar &)
Private Attributes
bool collective_op_
Additional Inherited Members
Static Public Member Functions inherited from FichierHDF
static bool is_hdf5 (const char *file_name)
Detailed Description
Parallel collective version of FichierHDF, to be used for all concurrent reading/writing on HDF files.
Definition at line 27 of file FichierHDFPar.h.
Constructor & Destructor Documentation
FichierHDFPar() [1/2]
FichierHDFPar::FichierHDFPar ()
Definition at line 22 of file FichierHDFPar.cpp.
                             :
  FichierHDF(), collective_op_(false)
{
#ifndef MPI_
  Cerr << "FichierHDFPar needs MPI to be used!" << finl;
  Process::exit(-1);
#endif
}
References Cerr, Process::exit(), and finl.
~FichierHDFPar()
FichierHDFPar::~FichierHDFPar () override
Definition at line 31 of file FichierHDFPar.cpp.
{}
FichierHDFPar() [2/2]
FichierHDFPar::FichierHDFPar (const FichierHDFPar &) private
Member Function Documentation
operator=()
FichierHDFPar & FichierHDFPar::operator= (const FichierHDFPar &) private
prepare_dataset_props()
void FichierHDFPar::prepare_dataset_props () override protected virtual
Reimplemented from FichierHDF.
Definition at line 53 of file FichierHDFPar.cpp.
{
  FichierHDF::prepare_dataset_props();
#ifdef MED_
#ifdef MPI_
  if(collective_op_)
    H5Pset_dxpl_mpio(dataset_transfer_plst_, H5FD_MPIO_COLLECTIVE);
#endif
#endif
// int rank = Process::me();
// //Build expected dataset name for the current proc (with the trailing _000x stuff)
// Nom dataset_full_name = dataset_name;
// dataset_full_name.nom_me(rank);
}
References collective_op_, and FichierHDF::prepare_dataset_props().
prepare_file_props()
void FichierHDFPar::prepare_file_props () override protected virtual
< not used for now. CCRT supports advise to leave empty.
Reimplemented from FichierHDF.
Definition at line 33 of file FichierHDFPar.cpp.
{
  FichierHDF::prepare_file_props();
#ifdef MPI_
  MPI_Info infos;
  MPI_Info_create(&infos); //!< not used for now. CCRT supports advise to leave empty.
#ifdef MED_
  H5Pset_fapl_mpio( file_access_plst_, Comm_Group_MPI::get_trio_u_world(), infos);
// on cluster, type lfs getstripe . to see the default striping of the current repository
  hsize_t stripe_size = 1048576; //1572864;
  H5Pset_alignment(file_access_plst_, 0, stripe_size);
#endif
  MPI_Info_free(&infos);
#endif
}
References Comm_Group_MPI::get_trio_u_world(), and FichierHDF::prepare_file_props().
set_collective_op()
void FichierHDFPar::set_collective_op (bool b) inline
Definition at line 32 of file FichierHDFPar.h.
  {
    collective_op_ = b;
  }
References collective_op_.
Member Data Documentation
collective_op_
bool FichierHDFPar::collective_op_ private
Definition at line 46 of file FichierHDFPar.h.
Referenced by prepare_dataset_props(), and set_collective_op().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/FichierHDFPar.h
src/Kernel/Utilitaires/FichierHDFPar.cpp