TRUST: Champ_implementation_sommet_base Class Reference
Champ_implementation_sommet_base Class Reference abstract
: class Champ_implementation_sommet_base
Decrire ici la classe Champ_implementation_sommet_base
#include <Champ_implementation_sommet_base.h>
Public Member Functions
Champ_base & le_champ (void) override=0
const Champ_base & le_champ (void) const override=0
~Champ_implementation_sommet_base () override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
Public Member Functions inherited from Champ_implementation_base
virtual ~Champ_implementation_base ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &domain, DoubleTab &result) const
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &domain, DoubleVect &result, int ncomp) const
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Protected Member Functions
virtual void value_interpolation (const DoubleTab &positions, const ArrOfInt &cells, const DoubleTab &values, DoubleTab &resu, int ncomp=-1) const =0
DoubleTab & valeur_aux_sommets_impl (DoubleTab &result) const override
DoubleVect & valeur_aux_sommets_compo_impl (DoubleVect &result, int ncomp) const override
DoubleTab & trace (const Frontiere_dis_base &fr, const DoubleTab &y, DoubleTab &x, int distant) const
Protected Member Functions inherited from Champ_implementation_base
virtual DoubleTab & valeur_aux_sommets_impl (DoubleTab &result) const =0
virtual DoubleVect & valeur_aux_sommets_compo_impl (DoubleVect &result, int ncomp) const =0
const Zone_VF & get_zone_dis (void) const
const Zone & get_zone_geom (void) const
virtual Champ_base & le_champ (void)=0
virtual const Champ_base & le_champ (void) const =0
Detailed Description
: class Champ_implementation_sommet_base
Decrire ici la classe Champ_implementation_sommet_base
Definition at line 30 of file Champ_implementation_sommet_base.h.
Constructor & Destructor Documentation
~Champ_implementation_sommet_base()
Champ_implementation_sommet_base::~Champ_implementation_sommet_base () inline override
Definition at line 40 of file Champ_implementation_sommet_base.h.
{ };
Member Function Documentation
le_champ() [1/2]
const Champ_base & Champ_implementation_sommet_base::le_champ (void) const override pure virtual
Implements Champ_implementation_base.
Implemented in Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_implementation_P1, and Champ_implementation_Q1.
le_champ() [2/2]
Champ_base & Champ_implementation_sommet_base::le_champ (void) override pure virtual
Implements Champ_implementation_base.
Implemented in Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_implementation_P1, and Champ_implementation_Q1.
Referenced by valeur_a_elem(), valeur_a_elem_compo(), valeur_aux_elems(), valeur_aux_elems_compo(), valeur_aux_sommets_compo_impl(), and valeur_aux_sommets_impl().
remplir_coord_noeuds()
DoubleTab & Champ_implementation_sommet_base::remplir_coord_noeuds (DoubleTab & positions) const override virtual
Implements Champ_implementation_base.
Reimplemented in Champ_Inc_P1_base, and Champ_Inc_Q1_base.
Definition at line 82 of file Champ_implementation_sommet_base.cpp.
{
  const Zone& zone = get_zone_geom();
  positions.resize(zone.nb_som(), Objet_U::dimension);
  positions = zone.domaine().les_sommets();
  return positions;
}
References Objet_U::dimension, Zone::domaine(), Champ_implementation_base::get_zone_geom(), Domaine::les_sommets(), Zone::nb_som(), and TRUSTTab< _TYPE_ >::resize().
Referenced by Champ_Fonc_P1_base::remplir_coord_noeuds(), Champ_Fonc_Q1_base::remplir_coord_noeuds(), Champ_Inc_P1_base::remplir_coord_noeuds(), and Champ_Inc_Q1_base::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
int Champ_implementation_sommet_base::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const override virtual
Implements Champ_implementation_base.
Reimplemented in Champ_Inc_P1_base, and Champ_Inc_Q1_base.
Definition at line 90 of file Champ_implementation_sommet_base.cpp.
{
  const Zone& zone = get_zone_geom();
  positions.resize(zone.nb_som(), Objet_U::dimension);
  positions = zone.domaine().les_sommets();
  zone.chercher_elements(positions,polys);
  return 1;
}
References Zone::chercher_elements(), Objet_U::dimension, Zone::domaine(), Champ_implementation_base::get_zone_geom(), Domaine::les_sommets(), Zone::nb_som(), and TRUSTTab< _TYPE_ >::resize().
Referenced by Champ_Fonc_P1_base::remplir_coord_noeuds_et_polys(), Champ_Fonc_Q1_base::remplir_coord_noeuds_et_polys(), Champ_Inc_P1_base::remplir_coord_noeuds_et_polys(), and Champ_Inc_Q1_base::remplir_coord_noeuds_et_polys().
trace()
DoubleTab & Champ_implementation_sommet_base::trace (const Frontiere_dis_base & fr, const DoubleTab & y, DoubleTab & x, int distant) const inline protected
Definition at line 58 of file Champ_implementation_sommet_base.h.
{
  if (distant)
    fr.frontiere().trace_som_distant(y, x);
  else
    fr.frontiere().trace_som_local(y, x);
// useless ? x.echange_espace_virtuel();
  return x;
}
References Frontiere_dis_base::frontiere(), Frontiere::trace_som_distant(), and Frontiere::trace_som_local().
Referenced by Champ_Inc_P1_base::trace().
valeur_a_elem()
DoubleVect & Champ_implementation_sommet_base::valeur_a_elem (const DoubleVect & position, DoubleVect & result, int poly) const override virtual
Implements Champ_implementation_base.
Reimplemented in Champ_Inc_P1_base, and Champ_Inc_Q1_base.
Definition at line 21 of file Champ_implementation_sommet_base.cpp.
{
  const Champ_base& ch_base       = le_champ();
  int            nb_components = ch_base.nb_comp();
  const DoubleTab&  values        = ch_base.valeurs();
  assert(result.size() == nb_components);
  assert(position.size() == Objet_U::dimension);
  DoubleTab positions;
  positions = position;
  DoubleTab resu(1, nb_components);
  ArrOfInt polys(1);
  polys[0] = poly;
  value_interpolation(positions,polys,values,resu);
  for (int j=0; j<nb_components; j++)
    result(j) = resu(j, 0) ;
  return result;
}
References Objet_U::dimension, le_champ(), Field_base::nb_comp(), TRUSTVect< _TYPE_ >::size(), Champ_Proto::valeurs(), and value_interpolation().
Referenced by Champ_Fonc_P1_base::valeur_a_elem(), Champ_Fonc_Q1_base::valeur_a_elem(), Champ_Inc_P1_base::valeur_a_elem(), and Champ_Inc_Q1_base::valeur_a_elem().
valeur_a_elem_compo()
double Champ_implementation_sommet_base::valeur_a_elem_compo (const DoubleVect & position, int poly, int ncomp) const override virtual
Implements Champ_implementation_base.
Reimplemented in Champ_Inc_P1_base, and Champ_Inc_Q1_base.
Definition at line 39 of file Champ_implementation_sommet_base.cpp.
{
  const Champ_base& ch_base       = le_champ();
  const DoubleTab&  values        = ch_base.valeurs();
  assert(ncomp>=0);
  assert(ncomp<ch_base.nb_comp());
  assert(position.size() == Objet_U::dimension);
  DoubleTab positions;
  positions = position;
  DoubleTab resu(1, 1);
  ArrOfInt polys(1);
  polys[0] = poly;
  value_interpolation(positions,polys,values,resu,ncomp);
  return resu(0, 0);
}
References Objet_U::dimension, le_champ(), Field_base::nb_comp(), TRUSTVect< _TYPE_ >::size(), Champ_Proto::valeurs(), and value_interpolation().
Referenced by Champ_Fonc_P1_base::valeur_a_elem_compo(), Champ_Fonc_Q1_base::valeur_a_elem_compo(), Champ_Inc_P1_base::valeur_a_elem_compo(), and Champ_Inc_Q1_base::valeur_a_elem_compo().
valeur_aux_elems()
DoubleTab & Champ_implementation_sommet_base::valeur_aux_elems (const DoubleTab & positions, const IntVect & polys, DoubleTab & result) const override virtual
Implements Champ_implementation_base.
Reimplemented in Champ_Inc_P1_base, and Champ_Inc_Q1_base.
Definition at line 55 of file Champ_implementation_sommet_base.cpp.
{
  const Champ_base& ch_base       = le_champ();
  const DoubleTab&  values        = ch_base.valeurs();
  assert((result.dimension(0) == polys.size())||(result.dimension_tot(0) == polys.size()));
  assert(positions.dimension(1) == Objet_U::dimension);
  value_interpolation(positions,polys,values,result);
  return result;
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), le_champ(), TRUSTVect< _TYPE_ >::size(), Champ_Proto::valeurs(), and value_interpolation().
Referenced by Champ_Fonc_P1_base::valeur_aux_elems(), Champ_Fonc_Q1_base::valeur_aux_elems(), Champ_Inc_P1_base::valeur_aux_elems(), and Champ_Inc_Q1_base::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_implementation_sommet_base::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & polys, DoubleVect & result, int ncomp) const override virtual
Implements Champ_implementation_base.
Reimplemented in Champ_Inc_P1_base, and Champ_Inc_Q1_base.
Definition at line 65 of file Champ_implementation_sommet_base.cpp.
{
  const Champ_base& ch_base       = le_champ();
  const DoubleTab&  values        = ch_base.valeurs();
  int nb_polys = polys.size();
  assert(ncomp>=0);
  assert(ncomp<ch_base.nb_comp());
  assert(result.size() == nb_polys);
  assert(positions.dimension(1) == Objet_U::dimension);
  DoubleTab resu(nb_polys, 1);
  value_interpolation(positions, polys, values, resu);
  for(int i=0; i<nb_polys; i++)
    result(i)=resu(i,0);
  return result;
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, le_champ(), Field_base::nb_comp(), TRUSTVect< _TYPE_ >::size(), Champ_Proto::valeurs(), and value_interpolation().
Referenced by Champ_Fonc_P1_base::valeur_aux_elems_compo(), Champ_Fonc_Q1_base::valeur_aux_elems_compo(), Champ_Inc_P1_base::valeur_aux_elems_compo(), and Champ_Inc_Q1_base::valeur_aux_elems_compo().
valeur_aux_sommets_compo_impl()
DoubleVect & Champ_implementation_sommet_base::valeur_aux_sommets_compo_impl (DoubleVect & result, int ncomp) const override protected virtual
Implements Champ_implementation_base.
Definition at line 114 of file Champ_implementation_sommet_base.cpp.
{
  const Champ_base& ch_base       = le_champ();
  const DoubleTab&  values        = ch_base.valeurs();
  int            size          = values.dimension(0);
  assert(ncomp>=0);
  assert(ncomp < ch_base.nb_comp());
  assert(result.size() == size);
  assert(values.nb_dim() == 2);
  assert(values.dimension(1) == ch_base.nb_comp());
  for (int i=0; i<size; i++)
    result(i) = values(i, ncomp);
  return result;
}
References TRUSTTab< _TYPE_ >::dimension(), le_champ(), Field_base::nb_comp(), TRUSTTab< _TYPE_ >::nb_dim(), TRUSTVect< _TYPE_ >::size(), and Champ_Proto::valeurs().
valeur_aux_sommets_impl()
DoubleTab & Champ_implementation_sommet_base::valeur_aux_sommets_impl (DoubleTab & result) const override protected virtual
Implements Champ_implementation_base.
Definition at line 99 of file Champ_implementation_sommet_base.cpp.
{
  const Champ_base& ch_base = le_champ();
  const DoubleTab&  values = ch_base.valeurs();
  const int size = values.dimension(0), N = values.line_size();
  assert((result.dimension(0) == size) || (result.dimension_tot(0) == size));
  assert(result.line_size() == N);
  for (int i = 0; i < size; i++)
    for (int n = 0; n < N; n++)
      result(i, n) = values(i, n);
  return result;
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), le_champ(), TRUSTVect< _TYPE_ >::line_size(), and Champ_Proto::valeurs().
value_interpolation()
virtual void Champ_implementation_sommet_base::value_interpolation (const DoubleTab & positions, const ArrOfInt & cells, const DoubleTab & values, DoubleTab & resu, int ncomp = -1) const protected pure virtual
Implemented in Champ_implementation_P1, and Champ_implementation_Q1.
Referenced by valeur_a_elem(), valeur_a_elem_compo(), valeur_aux_elems(), and valeur_aux_elems_compo().
The documentation for this class was generated from the following files:
src/Kernel/Champs_dis/Champ_implementation_sommet_base.h
src/Kernel/Champs_dis/Champ_implementation_sommet_base.cpp