TRUST: Eval_VDF_Elem2 Class Reference
Eval_VDF_Elem2 Class Reference
class Eval_VDF_Elem
Cette classe represente le prototype fonctionnel
des evaluateurs de flux associes aux equations de
conservation integrees sur les elements
#include <Eval_VDF_Elem2.h>
Public Member Functions
void associer_inconnue (const Champ_base &inco)
template<typename BC_TYPE >
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const BC_TYPE &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, int, int, const Echange_externe_impose &, int) const
double coeffs_faces_interne_bloc_vitesse (const DoubleTab &, int) const
Protected Attributes
Ref_Champ_base inconnue
Detailed Description
class Eval_VDF_Elem
Cette classe represente le prototype fonctionnel
des evaluateurs de flux associes aux equations de
conservation integrees sur les elements
Definition at line 38 of file Eval_VDF_Elem2.h.
Member Function Documentation
void Eval_VDF_Elem2::associer_inconnue (const Champ_base & inco) [inline]
Definition at line 41 of file Eval_VDF_Elem2.h.
References inconnue, and sub_type.
Referenced by Op_Dift_VDF_var_Elem_Axi::associer(), Op_Dift_VDF_var_Elem::associer(), Op_Dift_VDF_Multi_inco_var_Elem_Axi::associer(), Op_Dift_VDF_Multi_inco_var_Elem::associer(), Op_Dift_VDF_Multi_inco_Elem_Axi::associer(), Op_Dift_VDF_Multi_inco_Elem::associer(), Op_Dift_VDF_Elem_Axi::associer(), Op_Dift_VDF_Elem::associer(), and Op_Diff_VDF_Elem_base::associer().
  {
    assert(sub_type(Champ_P0_VDF,inco));
    inconnue=inco;
  }
template<typename BC_TYPE > double Eval_VDF_Elem2::coeffs_face_bloc_vitesse (const DoubleTab & , int , const BC_TYPE & , int) const [inline]
Definition at line 49 of file Eval_VDF_Elem2.h.
{ return 0.; }
double Eval_VDF_Elem2::coeffs_face_bloc_vitesse (const DoubleTab & , int , int , int , const Echange_externe_impose & , int) const [inline]
Definition at line 51 of file Eval_VDF_Elem2.h.
{ return 0.; }
double Eval_VDF_Elem2::coeffs_faces_interne_bloc_vitesse (const DoubleTab & , int) const [inline]
Definition at line 52 of file Eval_VDF_Elem2.h.
{ return 0.; }
Member Data Documentation
Ref_Champ_base Eval_VDF_Elem2::inconnue [protected]
Definition at line 55 of file Eval_VDF_Elem2.h.
Referenced by associer_inconnue().
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs_Diff/Eval_VDF_Elem2.h