TRUST: Travail_pression_CoviMAC Class Reference
Travail_pression_CoviMAC Class Reference
Classe Travail_pression_CoviMAC
Cette classe implemente dans CoviMAC le travail de la pression
- p (d alpha_k / dt + div(alpha_k v_k))
dans l'equation d'energie ecrite en energie interne (cf. CATHARE 3D)
#include <Travail_pression_CoviMAC.h>
Public Member Functions
Travail_pression_CoviMAC ()
~Travail_pression_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int has_interface_blocs () const
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void check_multiphase_compatibility () const
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
void associer_pb (const Probleme_base &)
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Travail_pression_CoviMAC & self_cast (Objet_U &)
static const
Travail_pression_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Detailed Description
Classe Travail_pression_CoviMAC
Cette classe implemente dans CoviMAC le travail de la pression
- p (d alpha_k / dt + div(alpha_k v_k))
dans l'equation d'energie ecrite en energie interne (cf. CATHARE 3D)
Definition at line 38 of file Travail_pression_CoviMAC.h.
Constructor & Destructor Documentation
Travail_pression_CoviMAC::Travail_pression_CoviMAC ()
Definition at line 32 of file Travail_pression_CoviMAC.cpp.
Travail_pression_CoviMAC::~Travail_pression_CoviMAC ()
Definition at line 32 of file Travail_pression_CoviMAC.cpp.
Member Function Documentation
void Travail_pression_CoviMAC::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) const [inline, virtual]
< memes stencils que celui de l'equation courante
< E. Saikali : initialise dP_G ici sinon fuite memoire ...
Reimplemented from Source_base.
Definition at line 178 of file Op_Conv_EF_Stab_CoviMAC_Elem.cpp.
References Op_Conv_EF_Stab_CoviMAC_Elem::alpha, Equation_base::champ_convecte(), Champ_Inc_base::derivees(), MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Nom::getString(), Op_Conv_CoviMAC_base::la_zone_poly_, Field_base::le_nom(), DoubleVect::line_size(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone_VF::porosite_face(), ref_cast, sub_type, valeur(), Ref_Zone_CoviMAC::valeur(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), and Op_Conv_CoviMAC_base::vitesse_.
{
  const Zone_CoviMAC& zone = la_zone_poly_.valeur();
  const IntTab& f_e = zone.face_voisins(), &fcl = ref_cast(Champ_P0_CoviMAC, equation().inconnue().valeur()).fcl();
  const DoubleVect& fs = zone.face_surfaces(), &pf = zone.porosite_face();
  const Champ_Inc_base& cc = equation().champ_convecte();
  const std::string& nom_cc = cc.le_nom().getString();
  const DoubleTab& vit = vitesse_->valeurs(), &vcc = semi_impl.count(nom_cc) ? semi_impl.at(nom_cc) : cc.valeurs(), bcc = cc.valeur_aux_bords();
  int i, j, e, eb, f, n, m, N = vcc.line_size(), Mp = sub_type(Navier_Stokes_std, equation().probleme().equation(0)) ? ref_cast(Navier_Stokes_std, equation().probleme().equation(0)).pression().valeurs().line_size() : N,
                            M = vit.line_size();
  Matrice_Morse *m_vit = mats.count("vitesse") ? mats.at("vitesse") : NULL;
  std::vector<std::tuple<const DoubleTab *, Matrice_Morse *, int>> d_cc; //liste des derivees de cc a renseigner : couples (derivee de cc, matrice, nb de compos de la variable)
  if (!semi_impl.count(nom_cc)) for (auto &i_m : mats) if (cc.derivees().count(i_m.first))
        d_cc.push_back(std::make_tuple(&cc.derivees().at(i_m.first), i_m.second, i_m.first == "pression" ? Mp : N));
  DoubleTrav dv_flux(N), dc_flux(2, N); //derivees du flux convectif a la face par rapport a la vitesse / au champ convecte amont / aval
  /* convection aux faces internes (fcl(f, 0) == 0), de Neumann_val_ext ou de Dirichlet */
  for (f = 0; f < zone.nb_faces(); f++) if (!fcl(f, 0) || (fcl(f, 0) > 4 && fcl(f, 0) < 7))
      {
        for (dv_flux = 0, dc_flux = 0, i = 0; i < 2; i++) for (e = f_e(f, i), n = 0, m = 0; n < N; n++, m += (M > 1))
            {
              double v = vit(f, m) ? vit(f, m) : DBL_MIN, fac = pf(f) * fs(f) * (1. + (v * (i ? -1 : 1) > 0 ? 1. : -1) * alpha) / 2;
              dv_flux(n) += fac * (e >= 0 ? vcc(e, n) : bcc(f, n)); //f est reelle -> indice trivial dans bcc
              dc_flux(i, n) = e >= 0 ? fac * vit(f, m) : 0;
            }
// second membre
        for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++) if (e < zone.nb_elem()) for (n = 0, m = 0; n < N; n++, m += (M > 1))
              secmem(e, n) -= (i ? -1 : 1) * dv_flux(n) * vit(f, m);
// derivees : vitesse
        if (m_vit) for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++) if (e < zone.nb_elem()) for (n = 0; n < N; n++)
                (*m_vit)(N * e + n, N * f + n) += (i ? -1 : 1) * dv_flux(n);
// derivees : champ convecte
        for (auto &&d_m_i : d_cc) for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++) if (e < zone.nb_elem()) for (j = 0; j < 2 && (eb = f_e(f, j)) >= 0; j++)
                for (n = 0; n < N; n++) (*std::get<1>(d_m_i))(N * e + n, std::get<2>(d_m_i) * eb + n * (std::get<2>(d_m_i) > 1)) += (i ? -1 : 1) * dc_flux(j, n) * (*std::get<0>(d_m_i))(eb, n);
      }
}
void Travail_pression_CoviMAC::associer_pb (const Probleme_base &) [inline, virtual]
Implements Source_base.
Definition at line 51 of file Travail_pression_CoviMAC.h.
{ };
void Travail_pression_CoviMAC::associer_zones (const Zone_dis & , const Zone_Cl_dis &) [inline, virtual]
Implements Source_base.
Definition at line 50 of file Travail_pression_CoviMAC.h.
{ };
void Travail_pression_CoviMAC::check_multiphase_compatibility () const [inline, virtual]
Reimplemented from MorEqn.
Definition at line 48 of file Travail_pression_CoviMAC.h.
{}; //of course
Objet_U * Travail_pression_CoviMAC::cree_instance () [static]
Definition at line 32 of file Travail_pression_CoviMAC.cpp.
void Travail_pression_CoviMAC::dimensionner_blocs (matrices_t matrices) [virtual]
Reimplemented from Source_base.
int Travail_pression_CoviMAC::duplique () const [virtual]
Implements Source_base.
Definition at line 32 of file Travail_pression_CoviMAC.cpp.
const Type_info * Travail_pression_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 32 of file Travail_pression_CoviMAC.cpp.
int Travail_pression_CoviMAC::has_interface_blocs () const [inline, virtual]
Reimplemented from Source_base.
Definition at line 42 of file Travail_pression_CoviMAC.h.
  {
    return 1;
  }
const Type_info * Travail_pression_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 32 of file Travail_pression_CoviMAC.cpp.
void Travail_pression_CoviMAC::mettre_a_jour (double temps) [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 52 of file Travail_pression_CoviMAC.h.
{ };
Sortie & Travail_pression_CoviMAC::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 35 of file Travail_pression_CoviMAC.cpp.
{
  return os;
}
Entree & Travail_pression_CoviMAC::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 40 of file Travail_pression_CoviMAC.cpp.
{
  return is;
}
const Travail_pression_CoviMAC & Travail_pression_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Definition at line 32 of file Travail_pression_CoviMAC.cpp.
Travail_pression_CoviMAC & Travail_pression_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Definition at line 32 of file Travail_pression_CoviMAC.cpp.
unsigned Travail_pression_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 32 of file Travail_pression_CoviMAC.cpp.
Member Data Documentation
const Type_info Travail_pression_CoviMAC::info_obj [static]
Reimplemented from Source_base.
Definition at line 40 of file Travail_pression_CoviMAC.h.
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/CoviMAC/Travail_pression_CoviMAC.h
src/CoviMAC/Operateurs/Op_Conv_EF_Stab_CoviMAC_Elem.cpp
src/CoviMAC/Operateurs/Op_Conv_EF_Stab_CoviMAC_Face.cpp
src/CoviMAC/Operateurs/Op_Diff_CoviMAC_Elem.cpp
src/CoviMAC/Operateurs/Op_Diff_CoviMAC_Face.cpp
src/CoviMAC/Operateurs/Op_Grad_CoviMAC_Face.cpp
src/CoviMAC/Sources/DP_Impose_CoviMAC_Face.cpp
src/CoviMAC/Sources/Perte_Charge_CoviMAC.cpp
src/CoviMAC/Sources/Perte_Charge_Singuliere_CoviMAC_Face.cpp
src/CoviMAC/Sources/Terme_Boussinesq_CoviMAC_Face.cpp
src/CoviMAC/Sources/Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC.cpp
src/CoviMAC/Sources/Terme_Source_CoviMAC_base.h
src/CoviMAC/Sources/Terme_Source_Decroissance_Radioactive_P0_CoviMAC.cpp
src/CoviMAC/Sources/Terme_Source_Qdm_Face_CoviMAC.cpp
src/Kernel/Framework/Operateur_base.cpp
src/Kernel/Framework/Schema_Temps_base.cpp
src/Kernel/Framework/Source_base.cpp
src/ThHyd/Multiphase/CoviMAC/Flux_interfacial_CoviMAC.cpp
src/ThHyd/Multiphase/CoviMAC/Frottement_interfacial_CoviMAC.cpp
src/ThHyd/Multiphase/CoviMAC/Op_Evanescence_Homogene_CoviMAC_Elem.cpp
src/ThHyd/Multiphase/CoviMAC/Op_Evanescence_Homogene_CoviMAC_Face.cpp
src/ThHyd/Multiphase/CoviMAC/Travail_pression_CoviMAC.cpp