TRUST: TRUSTList< _TYPE_ > Class Template Reference
TRUSTList< _TYPE_ > Class Template Reference
: Classe qui sert a representer une liste de reels int/double precision. On ne peut pas utiliser la classe container
List avec des objets du type int/double car int/double est un type predefini du C++ qui ne possede pas les fonctions exigees par List< >.
#include <TRUSTList.h>
Public Member Functions
TRUSTList ()
TRUSTList (const TRUSTList &a_list)
Sortie & printOn (Sortie &os) const
Ecriture d'une liste sur un flot de sortie les elements separes par des virgules figurent entre des accolades.
Entree & readOn (Entree &is)
Lecture d'une liste sur un flot d'entree les elements separes par des virgules figurent entre des accolades.
int size () const
Renvoie la taille de la liste (Une liste vide est de taille nulle)
int contient (_TYPE_) const
Verifie si un element appartient ou non a la liste.
int rang (_TYPE_) const
renvoie le rang d'un element dans la liste si un element apparait plusieurs fois, renvoie le rang du premier.
TRUSTListElem< _TYPE_ > & dernier ()
Renvoie le dernier element de la liste.
const TRUSTListElem< _TYPE_ > & dernier () const
_TYPE_ & operator[] (int)
Operateur d'acces au ieme int de la liste.
const _TYPE_ & operator[] (int) const
TRUSTList & add (_TYPE_)
insertion en queue
TRUSTList & add_if_not (_TYPE_)
Ajout d'un element a la liste ssi il n'existe pas deja.
TRUSTList & operator= (const TRUSTList &)
Affectation. Les elements sont copies.
void suppr (_TYPE_)
Supprime un element contenu dans la liste.
void vide ()
Vide la liste.
void calcule_min_max ()
Public Member Functions inherited from TRUSTListElem< _TYPE_ >
TRUSTListElem ()
Construit une liste vide.
TRUSTListElem (const _TYPE_ x)
Construit le singleton (x).
TRUSTListElem (const TRUSTListElem &)
Constructeur par copie
Parametre: const TRUSTListElem& list (la liste a copier)
~TRUSTListElem ()
int est_vide () const
renvoie 1 si la liste est vide. 0 sinon
int est_dernier () const
renvoie 1 si il n'y a pas de suivant. 0 sinon
_TYPE_ & valeur ()
_TYPE_ valeur () const
TRUSTListElem & add (_TYPE_)
insertion en queue
Parametre: int/double value_to_add (element a ajouter)
TRUSTListElem & suivant ()
const TRUSTListElem & suivant () const
Private Attributes
TRUSTListElem< _TYPE_ > * dernier_
_TYPE_ min_data
_TYPE_ max_data
Friends
class TRUSTList_Curseur< _TYPE_ >
template<typename T >
int operator== (const TRUSTList< T > &, const TRUSTList< T > &)
Additional Inherited Members
Protected Attributes inherited from TRUSTListElem< _TYPE_ >
_TYPE_ data
TRUSTListElem * suivant_
Detailed Description
template<typename _TYPE_>
class TRUSTList< _TYPE_ >
: Classe qui sert a representer une liste de reels int/double precision. On ne peut pas utiliser la classe container
List avec des objets du type int/double car int/double est un type predefini du C++ qui ne possede pas les fonctions exigees par List< >.
Definition at line 30 of file TRUSTList.h.
Constructor & Destructor Documentation
TRUSTList() [1/2]
template<typename _TYPE_ > TRUSTList< _TYPE_ >::TRUSTList () inline
Definition at line 35 of file TRUSTList.h.
              : TRUSTListElem<_TYPE_>()
  {
    min_data = std::is_same<_TYPE_, double>::value ? DMAXFLOAT : IMAX;
    max_data = std::is_same<_TYPE_, double>::value ? -DMAXFLOAT : -IMAX;
    dernier_ = this;
  }
References TRUSTList< _TYPE_ >::dernier_, DMAXFLOAT, IMAX, TRUSTList< _TYPE_ >::max_data, and TRUSTList< _TYPE_ >::min_data.
TRUSTList() [2/2]
template<typename _TYPE_ > TRUSTList< _TYPE_ >::TRUSTList (const TRUSTList< _TYPE_ > & a_list) inline
Definition at line 43 of file TRUSTList.h.
                                     : TRUSTListElem<_TYPE_>()
  {
    min_data = a_list.min_data;
    max_data = a_list.max_data;
    if (a_list.est_vide()) this->suivant_ = this;
    else
      {
        this->data = a_list.data;
        dernier_ = this;
        if (a_list.suivant_)
          {
            TRUSTListElem<_TYPE_> *next = new TRUSTListElem<_TYPE_>(*a_list.suivant_); //Recursif !!
            this->suivant_ = next;
          }
        else this->suivant_ = 0;
      }
  }
References TRUSTListElem< _TYPE_ >::data, TRUSTList< _TYPE_ >::dernier_, TRUSTListElem< _TYPE_ >::est_vide(), TRUSTList< _TYPE_ >::max_data, TRUSTList< _TYPE_ >::min_data, next(), and TRUSTListElem< _TYPE_ >::suivant_.
Member Function Documentation
add()
template<typename _TYPE_ > TRUSTList< _TYPE_ > & TRUSTList< _TYPE_ >::add (_TYPE_ value_to_add) inline
insertion en queue
Definition at line 75 of file TRUSTList.tpp.
{
  if (value_to_add < min_data) min_data = value_to_add;
  if (value_to_add > max_data) max_data = value_to_add;
  if (TRUSTListElem<_TYPE_>::est_vide())
    {
      this->data = value_to_add;
      this->suivant_ = 0;
      return *this;
    }
  else
    {
      if (TRUSTListElem<_TYPE_>::est_dernier())
        {
          TRUSTListElem<_TYPE_> *next = new TRUSTListElem<_TYPE_>(value_to_add);
          this->suivant_ = next;
          dernier_ = next;
        }
      else
        {
          dernier().add(value_to_add);
          dernier_ = &dernier_->suivant();
        }
      return *this;
    }
}
Referenced by Remove_elem::lire_motcle_non_standard(), Equation_base::preparer_calcul(), Op_Diff_VEF_Face_Penalise::reduction(), and Op_Diff_VEF_Face_Penalise::signe().
add_if_not()
template<typename _TYPE_ > TRUSTList< _TYPE_ > & TRUSTList< _TYPE_ >::add_if_not (_TYPE_ x) inline
Ajout d'un element a la liste ssi il n'existe pas deja.
Definition at line 120 of file TRUSTList.tpp.
{
  if (!contient(x)) return add(x);
  else return *this;
}
Referenced by Polygone::affecte_connectivite_numero_global(), Polyedre::affecte_connectivite_numero_global(), Op_Rot_VEFP1B::ajouter(), Op_Diff_RotRot::elements_pour_sommet(), ExtrudeParoi::extrude(), Op_Diff_VEF_Face_Penalise::faces_communes(), Champ_front_recyclage::initialiser(), Op_Diff_RotRot::sommets_pour_element(), Op_Diff_RotRot::sommets_voisins(), Op_Diff_RotRot::Tri(), and Op_Diff_VEF_Face_Penalise::voisinage().
calcule_min_max()
template<typename _TYPE_ > void TRUSTList< _TYPE_ >::calcule_min_max inline
Definition at line 245 of file TRUSTList.tpp.
{
  min_data = std::is_same<_TYPE_,double>::value ? DMAXFLOAT : IMAX;
  max_data = std::is_same<_TYPE_,double>::value ? -DMAXFLOAT : -IMAX;
  TRUSTList_Curseur<_TYPE_> curseur = *this;
  while (curseur)
    {
      _TYPE_ la_valeur = curseur.valeur();
      if (la_valeur < min_data) min_data = la_valeur;
      if (la_valeur > max_data) max_data = la_valeur;
      ++curseur;
    }
}
References DMAXFLOAT, IMAX, and TRUSTList_Curseur< _TYPE_ >::valeur().
contient()
template<typename _TYPE_ > int TRUSTList< _TYPE_ >::contient (_TYPE_ x) const inline
Verifie si un element appartient ou non a la liste.
Definition at line 128 of file TRUSTList.tpp.
{
  if (TRUSTListElem<_TYPE_>::est_vide() || x > max_data || x < min_data) return 0;
  TRUSTList_Curseur<_TYPE_> curseur(*this);
  while (curseur)
    {
      if (curseur.valeur() == x) return 1;
      ++curseur;
    }
  return 0;
}
References TRUSTList_Curseur< _TYPE_ >::valeur().
Referenced by Op_Diff_VEF_Face_Penalise::faces_communes(), Op_Diff_VEF_Face_Penalise::reduction(), Op_Diff_RotRot::remplir_som_som_EF(), and Op_Diff_VEF_Face_Penalise::signe().
dernier() [1/2]
template<typename _TYPE_ > TRUSTListElem< _TYPE_ > & TRUSTList< _TYPE_ >::dernier () inline
Renvoie le dernier element de la liste.
Definition at line 69 of file TRUSTList.h.
{ return *dernier_; }
References TRUSTList< _TYPE_ >::dernier_.
dernier() [2/2]
template<typename _TYPE_ > const TRUSTListElem< _TYPE_ > & TRUSTList< _TYPE_ >::dernier () const inline
Definition at line 70 of file TRUSTList.h.
{ return *dernier_; }
References TRUSTList< _TYPE_ >::dernier_.
operator=()
template<typename _TYPE_ > TRUSTList< _TYPE_ > & TRUSTList< _TYPE_ >::operator= (const TRUSTList< _TYPE_ > & a_list) inline
Affectation. Les elements sont copies.
Definition at line 57 of file TRUSTList.tpp.
{
  if (a_list.est_vide()) this->suivant_ = this;
  else
    {
      vide();
      TRUSTList_Curseur<_TYPE_> curseur(a_list);
      while (curseur)
        {
          add(curseur.valeur());
          ++curseur;
        }
    }
  return *this;
}
References TRUSTListElem< _TYPE_ >::est_vide().
operator[]() [1/2]
template<typename _TYPE_ > _TYPE_ & TRUSTList< _TYPE_ >::operator[] (int i) inline
Operateur d'acces au ieme int de la liste.
Definition at line 160 of file TRUSTList.tpp.
{
  TRUSTList_Curseur<_TYPE_> curseur(*this);
  while (curseur && i--) ++curseur;
  if (i != -1)
    {
      Cerr << "Overflow list " << finl;
      Process::exit();
    }
  return curseur.valeur();
}
References Cerr, Process::exit(), finl, and TRUSTList_Curseur< _TYPE_ >::valeur().
operator[]() [2/2]
template<typename _TYPE_ > const _TYPE_ & TRUSTList< _TYPE_ >::operator[] (int i) const inline
Definition at line 174 of file TRUSTList.tpp.
{
  TRUSTList_Curseur<_TYPE_> curseur(*this);
  while (curseur && i--) ++curseur;
  if (i != -1)
    {
      Cerr << "Overflow list " << finl;
      Process::exit();
    }
  return curseur.valeur();
}
References Cerr, Process::exit(), finl, and TRUSTList_Curseur< _TYPE_ >::valeur().
printOn()
template<typename _TYPE_ > Sortie & TRUSTList< _TYPE_ >::printOn (Sortie & os) const inline
Ecriture d'une liste sur un flot de sortie les elements separes par des virgules figurent entre des accolades.
Definition at line 21 of file TRUSTList.tpp.
{
  TRUSTList_Curseur<_TYPE_> curseur(*this);
  Nom accouverte = "{", accfermee = "}", virgule = ",";
  os << accouverte << " ";
  while (curseur)
    {
// if(est_dernier()) GF sinon on a une virgule de trop
      if (curseur.list().est_dernier()) os << curseur.valeur() << " ";
      else os << curseur.valeur() << " " << virgule << " ";
      ++curseur;
    }
  os << accfermee;
  return os;
}
References TRUSTList_Curseur< _TYPE_ >::list(), and TRUSTList_Curseur< _TYPE_ >::valeur().
rang()
template<typename _TYPE_ > int TRUSTList< _TYPE_ >::rang (_TYPE_ x) const inline
renvoie le rang d'un element dans la liste si un element apparait plusieurs fois, renvoie le rang du premier.
Definition at line 143 of file TRUSTList.tpp.
{
  if (TRUSTListElem<_TYPE_>::est_vide() || x > max_data || x < min_data) return -1;
  int compteur = 0;
  TRUSTList_Curseur<_TYPE_> curseur(*this);
  while (curseur)
    {
      if (curseur.valeur() == x) return compteur;
      ++compteur;
      ++curseur;
    }
  return -1;
}
References compteur, and TRUSTList_Curseur< _TYPE_ >::valeur().
Referenced by ExtrudeParoi::extrude().
readOn()
template<typename _TYPE_ > Entree & TRUSTList< _TYPE_ >::readOn (Entree & is) inline
Lecture d'une liste sur un flot d'entree les elements separes par des virgules figurent entre des accolades.
Definition at line 39 of file TRUSTList.tpp.
{
  Nom accouverte = "{", accfermee = "}", virgule = ",", nom;
  _TYPE_ t;
  is >> nom;
  assert(nom == accouverte);
  while (nom != accfermee)
    {
      is >> t;
      add(t);
      is >> nom;
      assert((nom == accfermee) || (nom == virgule));
    }
  return is;
}
size()
template<typename _TYPE_ > int TRUSTList< _TYPE_ >::size inline
Renvoie la taille de la liste (Une liste vide est de taille nulle)
Definition at line 105 of file TRUSTList.tpp.
{
  if (TRUSTListElem<_TYPE_>::est_vide()) return 0;
  int i = 0;
  TRUSTList_Curseur<_TYPE_> curseur(*this);
  while (curseur)
    {
      ++i;
      ++curseur;
    }
  return i;
}
Referenced by Polygone::affecte_connectivite_numero_global(), Polyedre::affecte_connectivite_numero_global(), Op_Rot_VEFP1B::ajouter(), Op_Diff_VEF_Face_Penalise::ajouter(), Op_Diff_RotRot::assembler_matrice(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), ExtrudeParoi::extrude(), Op_Diff_VEF_Face_Penalise::faces_communes(), Zone::identifie_item_unique(), Op_Diff_VEF_Face_Penalise::reduction(), Remove_elem::Remove_elem_(), Op_Diff_RotRot::remplir_som_som_EF(), Op_Diff_RotRot::Tri(), and Op_Diff_VEF_Face_Penalise::voisinage().
suppr()
template<typename _TYPE_ > void TRUSTList< _TYPE_ >::suppr (_TYPE_ obj) inline
Supprime un element contenu dans la liste.
Definition at line 201 of file TRUSTList.tpp.
{
  if (TRUSTListElem<_TYPE_>::valeur() == obj)
    {
      if (this->suivant_)
        {
          TRUSTListElem<_TYPE_> *next = this->suivant_;
          this->suivant_ = next->suivant_;
          this->data = next->valeur();
          next->suivant_ = 0;
          delete next;
        }
      else
        {
          this->suivant_ = this;
          dernier_ = this;
        }
      calcule_min_max();
      return;
    }
  TRUSTList_Curseur<_TYPE_> curseur_pre = *this;
  TRUSTList_Curseur<_TYPE_> curseur = *(this->suivant_);
  while (curseur)
    {
      if (curseur.valeur() == obj)
        {
          TRUSTListElem<_TYPE_> *next = &curseur_pre.list().suivant();
          curseur_pre.list().suivant_ = curseur.list().suivant_;
          if (next->suivant_ == 0) dernier_ = &curseur_pre.list();
          else next->suivant_ = 0;
          delete next;
          calcule_min_max();
          return;
        }
      ++curseur;
      ++curseur_pre;
    }
  Cerr << "WARNING during deletion of an element in a list " << finl;
  Cerr << "One has not found object == : " << obj << finl;
}
References Cerr, finl, TRUSTList_Curseur< _TYPE_ >::list(), next(), and TRUSTList_Curseur< _TYPE_ >::valeur().
Referenced by Zone::identifie_item_unique(), Op_Diff_VEF_Face_Penalise::reduction(), and Op_Diff_RotRot::Tri().
vide()
template<typename _TYPE_ > void TRUSTList< _TYPE_ >::vide inline
Vide la liste.
Definition at line 261 of file TRUSTList.tpp.
{
  if (!TRUSTListElem<_TYPE_>::est_vide())
    if (this->suivant_) delete this->suivant_;
  this->suivant_ = this;
  dernier_ = this;
  calcule_min_max();
}
Referenced by Polygone::affecte_connectivite_numero_global(), Polyedre::affecte_connectivite_numero_global(), Op_Rot_VEFP1B::ajouter(), Op_Diff_RotRot::elements_pour_sommet(), Op_Diff_VEF_Face_Penalise::faces_communes(), Op_Diff_VEF_Face_Penalise::reduction(), Op_Diff_RotRot::sommets_pour_element(), and Op_Diff_VEF_Face_Penalise::voisinage().
Friends And Related Function Documentation
operator==
template<typename _TYPE_ > template<typename T > int operator== (const TRUSTList< T > & , const TRUSTList< T > &) friend
TRUSTList_Curseur< _TYPE_ >
template<typename _TYPE_ > friend class TRUSTList_Curseur< _TYPE_ > friend
Definition at line 1 of file TRUSTList.h.
Member Data Documentation
dernier_
template<typename _TYPE_ > TRUSTListElem<_TYPE_>* TRUSTList< _TYPE_ >::dernier_ private
Definition at line 87 of file TRUSTList.h.
Referenced by TRUSTList< _TYPE_ >::dernier(), and TRUSTList< _TYPE_ >::TRUSTList().
max_data
template<typename _TYPE_ > _TYPE_ TRUSTList< _TYPE_ >::max_data private
Definition at line 88 of file TRUSTList.h.
Referenced by TRUSTList< _TYPE_ >::TRUSTList().
min_data
template<typename _TYPE_ > _TYPE_ TRUSTList< _TYPE_ >::min_data private
Definition at line 88 of file TRUSTList.h.
Referenced by TRUSTList< _TYPE_ >::TRUSTList().
The documentation for this class was generated from the following files:
src/Kernel/Math/TRUSTList.h
src/Kernel/Math/TRUSTList.tpp