TRUST: Correlation Class Reference
Correlation Class Reference
#include <Correlation.h>
Public Member Functions
Correlation ()
~Correlation ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void typer_lire (const Probleme_base &pb, const Nom &type, Entree &is)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Correlation & self_cast (Objet_U &)
static const Correlation & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Detailed Description
Definition at line 44 of file Correlation.h.
Constructor & Destructor Documentation
Correlation::Correlation ()
Definition at line 26 of file Correlation.cpp.
Correlation::~Correlation ()
Definition at line 26 of file Correlation.cpp.
Member Function Documentation
Objet_U * Correlation::cree_instance () [static]
Reimplemented from Deriv_Correlation_base.
Definition at line 26 of file Correlation.cpp.
int Correlation::duplique () const [virtual]
Reimplemented from Deriv_Correlation_base.
Definition at line 26 of file Correlation.cpp.
const Type_info * Correlation::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Correlation_base.
Definition at line 26 of file Correlation.cpp.
const Type_info * Correlation::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Correlation_base.
Definition at line 26 of file Correlation.cpp.
Sortie & Correlation::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_Correlation_base.
Definition at line 34 of file Correlation.cpp.
References DERIV.
{
  return DERIV(Correlation_base)::printOn(os);
}
Entree & Correlation::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_Correlation_base.
Definition at line 29 of file Correlation.cpp.
References DERIV.
{
  return DERIV(Correlation_base)::readOn(is);
}
const Correlation & Correlation::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Correlation_base.
Definition at line 26 of file Correlation.cpp.
Correlation & Correlation::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Correlation_base.
Definition at line 26 of file Correlation.cpp.
unsigned Correlation::taille_memoire () const [virtual]
Reimplemented from Deriv_Correlation_base.
Definition at line 26 of file Correlation.cpp.
void Correlation::typer_lire (const Probleme_base & pb, const Nom & type, Entree & is)
Definition at line 39 of file Correlation.cpp.
References Correlation_base::associer_pb(), DERIV, Correlation_base::lire(), Deriv_::typer(), and Deriv_Correlation_base::valeur().
Referenced by Pb_Multiphase::lire_correlations(), and Frottement_interfacial_CoviMAC::readOn().
{
  /* on lit le nom de la correlation : si "type" est renseigne, alors */
  Nom nom;
  is >> nom;
  DERIV(Correlation_base)::typer(type != "??" ? type + "_" + nom : nom);
  valeur().associer_pb(pb);
  valeur().lire(is);
}
Member Data Documentation
const Type_info Correlation::info_obj [static]
Reimplemented from Deriv_Correlation_base.
Definition at line 46 of file Correlation.h.
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Correlations/Correlation.h
src/ThHyd/Multiphase/Correlations/Correlation.cpp