TRUST: Loi_Fermeture_Test Class Reference
Loi_Fermeture_Test Class Reference
: class Loi_Fermeture_Test
<Description of class Loi_Fermeture_Test>
#include <Loi_Fermeture_Test.h>
Public Member Functions
Loi_Fermeture_Test ()
~Loi_Fermeture_Test ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Cette methode est appelee par le probleme apres
mettre_a_jour() des equations et du milieu. Elle doit mettre
a jour tous les champs qu'elle gere en fonction des autres
champs du probleme.
void discretiser (const Discretisation_base &) override
Cette methode est appelee par le probleme apres
la discretisation des equations et du milieu et avant
l'appel a readOn() pour lecture des parametres.
Dans les classes derivees elle doit discretiser au minimum les champs
qui seront requis dans le readOn() des equations ou des autres
lois de fermeture.
void set_param (Param &param) override
Cette methode est appelee par le readOn de la classe.
Elle doit etre reimplementee dans les classes derivees pour
ajouter dans "param" les differents parametres a lire
dans le jeu de donnees et appeler la methode de l'ancetre.
Dans la classe de base: aucun parametre.
Public Member Functions inherited from Loi_Fermeture_base
Loi_Fermeture_base ()
~Loi_Fermeture_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
void creer_champ (const Motcle &motlu) override
La classe de base ne comprend aucun champ supplementaire.
const Champ_base & get_champ (const Motcle &nom) const override
Cette methode renvoie le champ de nom "nom" s'il est
compris par la classe, sinon appelle la methode get_champ de l'ancetre.
Dans la classe de base, on leve l'exception Champ_compris_erreur.
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void associer_pb_base (const Probleme_base &)
Cette methode est la premiere appelee par le probleme
pour construire l'objet au moment ou on l'associe au probleme.
On verifie qu'on est pas encore associe.
virtual void discretiser (const Discretisation_base &)
Cette methode est appelee par le probleme apres
la discretisation des equations et du milieu et avant
l'appel a readOn() pour lecture des parametres.
Dans les classes derivees elle doit discretiser au minimum les champs
qui seront requis dans le readOn() des equations ou des autres
lois de fermeture.
virtual void set_param (Param &param)
Cette methode est appelee par le readOn de la classe.
Elle doit etre reimplementee dans les classes derivees pour
ajouter dans "param" les differents parametres a lire
dans le jeu de donnees et appeler la methode de l'ancetre.
Dans la classe de base: aucun parametre.
virtual void completer ()
Cette methode est appelee apres avoir lu toutes les equations
et les lois de fermeture (tous les champs et les conditions aux limites
du probleme sont disponibles)
virtual void preparer_calcul ()
Cette methode est appelee par le probleme apres
preparer_calcul() des equations et du milieu. Elle doit mettre
a jour tous les champs qu'elle gere en fonction des autres
champs du probleme.
virtual void mettre_a_jour (double temps)
Cette methode est appelee par le probleme apres
mettre_a_jour() des equations et du milieu. Elle doit mettre
a jour tous les champs qu'elle gere en fonction des autres
champs du probleme.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Loi_Fermeture_Test & self_cast (Objet_U &)
static const Loi_Fermeture_Test & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Fermeture_base
static const Type_info * info ()
static Loi_Fermeture_base & self_cast (Objet_U &)
static const Loi_Fermeture_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Loi_Fermeture_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Pour l'instant, exit()
Entree & readOn (Entree &) override
Cette methode appelle la methode set_param() pour
initialiser les parametres, puis lit les parametres.
Dans l'implementation des classes derivees on peut se contenter
d'appeler la methode de la classe de base et verifier les parametres.
Protected Member Functions inherited from Loi_Fermeture_base
Sortie & printOn (Sortie &x) const override
Pour l'instant, exit()
Entree & readOn (Entree &) override
Cette methode appelle la methode set_param() pour
initialiser les parametres, puis lit les parametres.
Dans l'implementation des classes derivees on peut se contenter
d'appeler la methode de la classe de base et verifier les parametres.
const Probleme_base & mon_probleme () const
Renvoie le probleme (j'ai cree cette methode pour ne pas
donner acces au probleme en ecriture par la REF)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_Don champ_test_
double coef_
Protected Attributes inherited from Loi_Fermeture_base
Champs_compris champs_compris_
Status status_
Additional Inherited Members
Protected Types inherited from Loi_Fermeture_base
enum Status {
INITIAL , PB_ASSOCIE , DISCRETISE , READON_FAIT ,
COMPLET
}
Detailed Description
: class Loi_Fermeture_Test
<Description of class Loi_Fermeture_Test>
Definition at line 30 of file Loi_Fermeture_Test.h.
Constructor & Destructor Documentation
Loi_Fermeture_Test()
Loi_Fermeture_Test::Loi_Fermeture_Test ()
Definition at line 22 of file Loi_Fermeture_Test.cpp.
~Loi_Fermeture_Test()
Loi_Fermeture_Test::~Loi_Fermeture_Test ()
Definition at line 22 of file Loi_Fermeture_Test.cpp.
Member Function Documentation
cree_instance()
Objet_U * Loi_Fermeture_Test::cree_instance () static
Definition at line 22 of file Loi_Fermeture_Test.cpp.
discretiser()
void Loi_Fermeture_Test::discretiser (const Discretisation_base &) override virtual
Cette methode est appelee par le probleme apres
la discretisation des equations et du milieu et avant
l'appel a readOn() pour lecture des parametres.
Dans les classes derivees elle doit discretiser au minimum les champs
qui seront requis dans le readOn() des equations ou des autres
lois de fermeture.
Reimplemented from Loi_Fermeture_base.
Definition at line 48 of file Loi_Fermeture_Test.cpp.
{
  Loi_Fermeture_base::discretiser(dis);
  const Probleme_base& pb = mon_probleme();
  const double temps = pb.schema_temps().temps_courant();
  const Zone_dis_base& la_zone_dis = pb.domaine_dis().zone_dis(0).valeur();
  dis.discretiser_champ("CHAMP_ELEM", la_zone_dis,"test_time", "s",1 /* nb composantes par defaut */,temps, champ_test_);
  champs_compris_.ajoute_champ(champ_test_);
}
References Champs_compris::ajoute_champ(), champ_test_, Loi_Fermeture_base::champs_compris_, Loi_Fermeture_base::discretiser(), Discretisation_base::discretiser_champ(), Probleme_base::domaine_dis(), Loi_Fermeture_base::mon_probleme(), Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), Deriv_Zone_dis_base::valeur(), and Domaine_dis::zone_dis().
duplique()
int Loi_Fermeture_Test::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file Loi_Fermeture_Test.cpp.
get_info()
const Type_info * Loi_Fermeture_Test::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Fermeture_base.
Definition at line 22 of file Loi_Fermeture_Test.cpp.
info()
const Type_info * Loi_Fermeture_Test::info () static
Definition at line 22 of file Loi_Fermeture_Test.cpp.
mettre_a_jour()
void Loi_Fermeture_Test::mettre_a_jour (double temps) override virtual
Cette methode est appelee par le probleme apres
mettre_a_jour() des equations et du milieu. Elle doit mettre
a jour tous les champs qu'elle gere en fonction des autres
champs du probleme.
Reimplemented from Loi_Fermeture_base.
Definition at line 42 of file Loi_Fermeture_Test.cpp.
{
  assert(status_ == COMPLET);
  champ_test_.valeurs()=temps*coef_;
  champ_test_.valeur().changer_temps(temps);
}
References champ_test_, Champ_base::changer_temps(), coef_, Loi_Fermeture_base::COMPLET, Loi_Fermeture_base::status_, Deriv_Champ_Don_base::valeur(), and Champ_Don::valeurs().
printOn()
Sortie & Loi_Fermeture_Test::printOn (Sortie & x) const override protected virtual
Pour l'instant, exit()
Reimplemented from Loi_Fermeture_base.
Definition at line 25 of file Loi_Fermeture_Test.cpp.
{
  Loi_Fermeture_base::printOn( os );
  return os;
}
References Loi_Fermeture_base::printOn().
readOn()
Entree & Loi_Fermeture_Test::readOn (Entree & is) override protected virtual
Cette methode appelle la methode set_param() pour
initialiser les parametres, puis lit les parametres.
Dans l'implementation des classes derivees on peut se contenter
d'appeler la methode de la classe de base et verifier les parametres.
Reimplemented from Loi_Fermeture_base.
Definition at line 31 of file Loi_Fermeture_Test.cpp.
{
  coef_=1;
  Loi_Fermeture_base::readOn( is );
  return is;
}
References coef_, and Loi_Fermeture_base::readOn().
self_cast() [1/2]
const Loi_Fermeture_Test & Loi_Fermeture_Test::self_cast (const Objet_U & r) static
Definition at line 22 of file Loi_Fermeture_Test.cpp.
self_cast() [2/2]
Loi_Fermeture_Test & Loi_Fermeture_Test::self_cast (Objet_U & r) static
Definition at line 22 of file Loi_Fermeture_Test.cpp.
set_param()
void Loi_Fermeture_Test::set_param (Param & param) override virtual
Cette methode est appelee par le readOn de la classe.
Elle doit etre reimplementee dans les classes derivees pour
ajouter dans "param" les differents parametres a lire
dans le jeu de donnees et appeler la methode de l'ancetre.
Dans la classe de base: aucun parametre.
< XD_ADD_P double coefficient
Reimplemented from Loi_Fermeture_base.
Definition at line 38 of file Loi_Fermeture_Test.cpp.
{
  param.ajouter("coef",&coef_); //!< XD_ADD_P double coefficient
}
References Param::ajouter(), and coef_.
taille_memoire()
unsigned Loi_Fermeture_Test::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file Loi_Fermeture_Test.cpp.
Member Data Documentation
champ_test_
Champ_Don Loi_Fermeture_Test::champ_test_ protected
Definition at line 40 of file Loi_Fermeture_Test.h.
Referenced by discretiser(), and mettre_a_jour().
coef_
double Loi_Fermeture_Test::coef_ protected
Definition at line 41 of file Loi_Fermeture_Test.h.
Referenced by mettre_a_jour(), readOn(), and set_param().
info_obj
const Type_info Loi_Fermeture_Test::info_obj static
Definition at line 33 of file Loi_Fermeture_Test.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Loi_Fermeture_Test.h
src/Kernel/Framework/Loi_Fermeture_Test.cpp