TRUST: Elem_VEF Class Reference
Elem_VEF Class Reference
#include <Elem_VEF.h>
Public Member Functions
Elem_VEF ()
~Elem_VEF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Elem_VEF & operator= (const Elem_VEF_base &)
void typer (Nom)
determination du type
int nb_facette () const
void creer_facette_normales (const Zone &, DoubleTab &, const IntVect &) const
void creer_normales_facettes_Cl (DoubleTab &, int, int, const DoubleTab &, const DoubleVect &, const Zone &) const
void modif_volumes_entrelaces (int, int, const Zone_VEF &, DoubleVect &, int) const
void modif_volumes_entrelaces_faces_joints (int, int, const Zone_VEF &, DoubleVect &, int) const
void modif_normales_facettes_Cl (DoubleTab &, int, int, int, int, int, int) const
void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int, const DoubleVect &) const
void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Elem_VEF & self_cast (Objet_U &)
static const Elem_VEF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Detailed Description
Definition at line 42 of file Elem_VEF.h.
Constructor & Destructor Documentation
Elem_VEF::Elem_VEF ()
Definition at line 31 of file Elem_VEF.cpp.
Elem_VEF::~Elem_VEF ()
Definition at line 31 of file Elem_VEF.cpp.
Member Function Documentation
void Elem_VEF::calcul_vc (const ArrOfInt & face, ArrOfDouble & vc, const ArrOfDouble & vs, const DoubleTab & vsom, const Champ_Inc_base & vitesse, int type_cl, const DoubleVect & porosite_face) const [inline]
Definition at line 138 of file Elem_VEF.h.
References Elem_VEF_base::calcul_vc(), and Deriv_Elem_VEF_base::valeur().
Referenced by Op_Conv_kschemas_VEF::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), and Op_Conv_Amont_old_VEF_Face::ajouter_contribution().
{
  valeur().calcul_vc(face,vc,vs,vsom,vitesse,type_cl,porosite_face);
}
void Elem_VEF::calcul_xg (DoubleVect & xg, const DoubleTab & x, const int type_elem_Cl, int & idirichlet, int & n1, int & n2, int & n3) const [inline]
Definition at line 146 of file Elem_VEF.h.
References Elem_VEF_base::calcul_xg(), and Deriv_Elem_VEF_base::valeur().
Referenced by Zone_Cl_VEF::remplir_normales_facettes_Cl().
{
  valeur().calcul_xg(xg,x,type_elem_Cl,idirichlet,n1,n2,n3);
}
Objet_U * Elem_VEF::cree_instance () [static]
Reimplemented from Deriv_Elem_VEF_base.
Definition at line 31 of file Elem_VEF.cpp.
void Elem_VEF::creer_facette_normales (const Zone & zone_geom, DoubleTab & facette_normales, const IntVect & rang_elem) const [inline]
Definition at line 100 of file Elem_VEF.h.
References Elem_VEF_base::creer_facette_normales(), and Deriv_Elem_VEF_base::valeur().
Referenced by Zone_VEF::discretiser().
{
  valeur().creer_facette_normales(zone_geom,facette_normales,rang_elem);
}
void Elem_VEF::creer_normales_facettes_Cl (DoubleTab & norm_fa7_cl, int fa7, int num_elem, const DoubleTab & x, const DoubleVect & xg, const Zone & zone_geom) const [inline]
Definition at line 107 of file Elem_VEF.h.
References Elem_VEF_base::creer_normales_facettes_Cl(), and Deriv_Elem_VEF_base::valeur().
Referenced by Zone_Cl_VEF::remplir_normales_facettes_Cl().
{
  valeur().creer_normales_facettes_Cl(norm_fa7_cl,fa7,num_elem,x,xg,zone_geom);
}
int Elem_VEF::duplique () const [virtual]
Reimplemented from Deriv_Elem_VEF_base.
Definition at line 31 of file Elem_VEF.cpp.
const Type_info * Elem_VEF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Elem_VEF_base.
Definition at line 31 of file Elem_VEF.cpp.
const Type_info * Elem_VEF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Elem_VEF_base.
Definition at line 31 of file Elem_VEF.cpp.
void Elem_VEF::modif_normales_facettes_Cl (DoubleTab & norm_fa7_cl, int fa7, int num_elem, int idirichlet, int n1, int n2, int n3) const [inline]
Definition at line 130 of file Elem_VEF.h.
References Elem_VEF_base::modif_normales_facettes_Cl(), and Deriv_Elem_VEF_base::valeur().
Referenced by Zone_Cl_VEF::remplir_normales_facettes_Cl().
{
  valeur().modif_normales_facettes_Cl(norm_fa7_cl,fa7,
                                      num_elem,idirichlet,n1,n2,n3);
}
void Elem_VEF::modif_volumes_entrelaces (int j, int elem, const Zone_VEF & la_zone_VEF, DoubleVect & vol_ent_cl, int type_cl) const [inline]
Definition at line 116 of file Elem_VEF.h.
References Elem_VEF_base::modif_volumes_entrelaces(), and Deriv_Elem_VEF_base::valeur().
Referenced by Zone_Cl_VEF::remplir_volumes_entrelaces_Cl().
{
  valeur().modif_volumes_entrelaces(j,elem,la_zone_VEF,vol_ent_cl,type_cl);
}
void Elem_VEF::modif_volumes_entrelaces_faces_joints (int j, int elem, const Zone_VEF & la_zone_VEF, DoubleVect & vol_ent_cl, int type_cl) const [inline]
Definition at line 123 of file Elem_VEF.h.
References Elem_VEF_base::modif_volumes_entrelaces_faces_joints(), and Deriv_Elem_VEF_base::valeur().
Referenced by Zone_Cl_VEF::remplir_volumes_entrelaces_Cl().
{
  valeur().modif_volumes_entrelaces_faces_joints(j,elem,la_zone_VEF,vol_ent_cl,type_cl);
}
int Elem_VEF::nb_facette () const [inline]
Definition at line 83 of file Elem_VEF.h.
References Elem_VEF_base::nb_facette(), and Deriv_Elem_VEF_base::valeur().
Referenced by Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_Muscl_New_VEF_Face::ajouter_diffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Zone_Cl_VEF::associer(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Op_Conv_VEF_Face::remplir_fluent(), Zone_Cl_VEF::remplir_normales_facettes_Cl(), and Zone_VEF::vecteur_face_facette().
{
  return valeur().nb_facette();
}
void Elem_VEF::normale (int num_face, DoubleTab & Face_normales, const IntTab & Face_sommets, const IntTab & Face_voisins, const IntTab & elem_faces, const Zone & zone_geom) const [inline]
Definition at line 88 of file Elem_VEF.h.
References Elem_VEF_base::normale(), and Deriv_Elem_VEF_base::valeur().
Referenced by Zone_VEF::discretiser().
{
  valeur().normale(num_face,Face_normales,Face_sommets,Face_voisins,
                   elem_faces,zone_geom);
}
Elem_VEF & Elem_VEF::operator= (const Elem_VEF_base & elem_base) [inline]
Reimplemented from Deriv_Elem_VEF_base.
Definition at line 76 of file Elem_VEF.h.
References DERIV.
{
  DERIV(Elem_VEF_base)::operator=(elem_base);
  return *this;
}
Sortie & Elem_VEF::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_Elem_VEF_base.
Definition at line 37 of file Elem_VEF.cpp.
References Deriv_Elem_VEF_base::valeur().
{
  return s << valeur() ;
}
Entree & Elem_VEF::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_Elem_VEF_base.
Definition at line 42 of file Elem_VEF.cpp.
References Cerr, Process::exit(), and finl.
{
  Nom type;
  s >> type;
  if(type == "Tri_VEF")
    *this =  Tri_VEF();
  else if(type == "Tetra_VEF")
    *this =  Tetra_VEF();
  else if(type == "Quadri_VEF")
    *this =  Quadri_VEF();
  else if(type == "Hexa_VEF")
    *this =  Hexa_VEF();
  else
    {
      Cerr << type << " n'est pas un Elem_VEF" << finl;
      exit();
    }
  return s ;
}
const Elem_VEF & Elem_VEF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Elem_VEF_base.
Definition at line 31 of file Elem_VEF.cpp.
Elem_VEF & Elem_VEF::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Elem_VEF_base.
Definition at line 31 of file Elem_VEF.cpp.
unsigned Elem_VEF::taille_memoire () const [virtual]
Reimplemented from Deriv_Elem_VEF_base.
Definition at line 31 of file Elem_VEF.cpp.
void Elem_VEF::typer (Nom type_elem_geom)
determination du type
Definition at line 64 of file Elem_VEF.cpp.
References Cerr, DERIV, Process::exit(), and finl.
Referenced by Zone_VEF::typer_elem().
{
  if (Motcle(type_elem_geom)!="Segment")
    {
      Nom type;
      if(type_elem_geom=="Triangle")
        type="Tri_VEF";
      else if(type_elem_geom=="Tetraedre")
        type="Tetra_VEF";
      else if(type_elem_geom=="Quadrangle")
        type="Quadri_VEF";
      else if(type_elem_geom=="Hexaedre_VEF")
        type="Hexa_VEF";
      else
        {
          Cerr << "probleme de typage dans Elem_VEF::typer" << finl;
          exit();
        }
      DERIV(Elem_VEF_base)::typer(type);
    }
}
Member Data Documentation
const Type_info Elem_VEF::info_obj [static]
Reimplemented from Deriv_Elem_VEF_base.
Definition at line 44 of file Elem_VEF.h.
The documentation for this class was generated from the following files:
src/VEF/Zones/Elem_VEF.h
src/VEF/Zones/Elem_VEF.cpp