TRUST: Convection_Diffusion_Fluide_Dilatable_Proto Class Reference
Convection_Diffusion_Fluide_Dilatable_Proto Class Reference abstract
#include <Convection_Diffusion_Fluide_Dilatable_Proto.h>
Public Member Functions
virtual ~Convection_Diffusion_Fluide_Dilatable_Proto ()
Static Public Member Functions
static int Sauvegarder_WC (Sortie &os, const Convection_Diffusion_std &eq, const Fluide_Dilatable_base &fld)
static int Reprendre_WC (Entree &is, double temps, Convection_Diffusion_std &eq, Fluide_Dilatable_base &fld, Champ_Inc &inco, Probleme_base &pb)
Protected Member Functions
void calculer_div_rho_u_impl (DoubleTab &res, const Convection_Diffusion_Fluide_Dilatable_base &eqn) const
void assembler_impl (Convection_Diffusion_Fluide_Dilatable_base &eqn, Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
void assembler_blocs (Convection_Diffusion_Fluide_Dilatable_base &eqn, matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl)
DoubleTab & derivee_en_temps_inco_sans_solveur_masse_impl (Convection_Diffusion_Fluide_Dilatable_base &eqn, DoubleTab &derivee, const bool is_expl)
Renvoie la derivee en temps de l'inconnue de l'equation.
Le calcul est le suivant:
d(inconnue)/dt = M^{-1} * (sources - somme(Op_{i}(inconnue))) / rho.
virtual void calculer_div_u_ou_div_rhou (DoubleTab &res) const =0
virtual bool is_thermal () const =0
virtual bool is_generic () const =0
Detailed Description
Definition at line 31 of file Convection_Diffusion_Fluide_Dilatable_Proto.h.
Constructor & Destructor Documentation
~Convection_Diffusion_Fluide_Dilatable_Proto()
virtual Convection_Diffusion_Fluide_Dilatable_Proto::~Convection_Diffusion_Fluide_Dilatable_Proto () inline virtual
Definition at line 42 of file Convection_Diffusion_Fluide_Dilatable_Proto.h.
{}
Member Function Documentation
assembler_blocs()
void Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs (Convection_Diffusion_Fluide_Dilatable_base & eqn, matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) protected
Definition at line 323 of file Convection_Diffusion_Fluide_Dilatable_Proto.cpp.
{
  const std::string& nom_inco = eqn.inconnue().le_nom().getString();
  Matrice_Morse *mat = matrices.count(nom_inco)?matrices.at(nom_inco):NULL;
  Fluide_Dilatable_base& fluide_dil = eqn.fluide();
  const DoubleTab& tab_rho = fluide_dil.masse_volumique().valeurs();
  const int n = tab_rho.dimension(0);
  Matrice_Morse mat_diff(*mat);
  DoubleTab secmem_tmp(secmem);
  eqn.operateur(0).l_op_base().ajouter_blocs({{nom_inco, &mat_diff}}, secmem_tmp, semi_impl);
  statistiques().end_count(assemblage_sys_counter_);
  statistiques().begin_count(source_counter_);
  for (int i = 0; i < eqn.sources().size(); i++)
    eqn.sources()(i).valeur().ajouter_blocs({{nom_inco, &mat_diff}}, secmem_tmp, semi_impl);
  statistiques().end_count(source_counter_);
  statistiques().begin_count(assemblage_sys_counter_);
  DoubleVect& coeff_diffusif=mat_diff.get_set_coeff();
  const IntVect& tab1= mat->get_tab1();
  DoubleVect& coeff=mat->get_set_coeff();
  coeff = 0;
  eqn.operateur(1).l_op_base().ajouter_blocs(matrices, secmem_tmp, semi_impl);
// on calcule div(rho * u)
  calculer_div_u_ou_div_rhou(secmem);
  if (!is_thermal()) //espece
    {
      for (int som=0 ; som<n ; som++)
        {
          double inv_rho = 1. / tab_rho(som);
          for (int k=tab1(som)-1; k<tab1(som+1)-1; k++) coeff(k)= (coeff(k)*inv_rho+coeff_diffusif(k)*inv_rho);
          if(mat) (*mat)(som,som)+=secmem(som)*inv_rho;
        }
    }
  else if (is_thermal() && fluide_dil.type_fluide()=="Gaz_Parfait")
    {
      fluide_dil.update_rho_cp(eqn.schema_temps().temps_courant());
      const DoubleTab& rhoCp = eqn.get_champ("rho_cp_comme_T").valeurs();
      for (int som=0 ; som<n ; som++)
        {
          double inv_rho = 1. / tab_rho(som);
          if (!is_generic()) inv_rho = 1.;
          double rapport = 1. / rhoCp(som);
// il faut multiplier toute la ligne de la matrice par rapport
          for (int k=tab1(som)-1; k<tab1(som+1)-1; k++) coeff(k)= (coeff(k)*inv_rho+coeff_diffusif(k)*rapport);
// ajout de Tdiv(rhou)/rho
          if(mat) (*mat)(som,som) += secmem(som)*inv_rho;
        }
    }
  else
    {
      Cerr<<"The implicit algorithm is available only for perfect gas."<<finl;
      Process::exit();
    }
// on a la matrice approchee on recalcule le residu;
  secmem=0;
  derivee_en_temps_inco_sans_solveur_masse_impl(eqn,secmem,false /* implicit */);
  if(mat) mat->ajouter_multvect(eqn.inconnue().valeurs(),secmem);
}
References Operateur_base::ajouter_blocs(), Matrice_Base::ajouter_multvect(), assemblage_sys_counter_, Statistiques::begin_count(), calculer_div_u_ou_div_rhou(), Cerr, coeff, derivee_en_temps_inco_sans_solveur_masse_impl(), TRUSTTab< _TYPE_ >::dimension(), Statistiques::end_count(), Process::exit(), finl, Convection_Diffusion_Fluide_Dilatable_base::fluide(), Equation_base::get_champ(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Nom::getString(), Convection_Diffusion_Fluide_Dilatable_base::inconnue(), is_generic(), is_thermal(), Operateur::l_op_base(), O_U_Ptr::le_nom(), Milieu_base::masse_volumique(), Convection_Diffusion_std::operateur(), Equation_base::schema_temps(), source_counter_, Equation_base::sources(), statistiques(), Schema_Temps_base::temps_courant(), Fluide_Dilatable_base::type_fluide(), Fluide_Dilatable_base::update_rho_cp(), valeur(), Champ::valeurs(), Champ_Inc::valeurs(), and Champ_Proto::valeurs().
Referenced by Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), and Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie().
assembler_impl()
void Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl (Convection_Diffusion_Fluide_Dilatable_base & eqn, Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) protected
Definition at line 197 of file Convection_Diffusion_Fluide_Dilatable_Proto.cpp.
{
  /*
   * ATEENTION : THIS IS A GENERIC METHOD THAT IS USED TO SOLVE IMPLICITLY A THERMAL OR SPECIES
   *  CONV/DIFF EQUATION. SO THE VARIABLE CAN EITHER BE THE TEMPERATURE T OR THE MASS FRACTION Y.
   *
   * See the previous method derivee_en_temps_inco_sans_solveur_masse_impl for more description
   * of the treated equations.
   */
// Elie Saikali
// Je garde ce test pour debug ... TODO : a voir si on peut virer tout a...
  int test_op=0;
  {
    char* theValue = getenv("TRUST_TEST_OPERATEUR_IMPLICITE");
    if (theValue != NULL) test_op=2;
  }
  {
    char* theValue = getenv("TRUST_TEST_OPERATEUR_IMPLICITE_BLOQUANT");
    if (theValue != NULL) test_op=1;
  }
  Fluide_Dilatable_base& fluide_dil = eqn.fluide();
  const DoubleTab& tab_rho = fluide_dil.masse_volumique().valeurs();
  const int n = tab_rho.dimension(0);
// ajout diffusion (avec rho, D et Y / ou lambda et T)
  eqn.operateur(0).l_op_base().contribuer_a_avec(inco, matrice );
// Add source term (if any)
  eqn.sources().contribuer_a_avec(inco,matrice);
  const IntVect& tab1= matrice.get_tab1();
  DoubleVect& coeff=matrice.get_set_coeff();
  DoubleVect coeff_diffusif(coeff);
// on calcule les coefficients de l'op de convection on obtient les coeff de div (rho*u*Y)
// ou div(rho*u*T). dans le cas thermique, il faudrait multiplier par cp puis divisier par rho cp
// on le fera d'un coup...
  coeff=0.;
  eqn.operateur(1).l_op_base().contribuer_a_avec(inco, matrice );
// on calcule div(rho * u)
  DoubleTrav derivee2(resu);
  calculer_div_u_ou_div_rhou(derivee2);
  if (!is_thermal()) //espece
    {
      for (int som=0 ; som<n ; som++)
        {
          double inv_rho = 1. / tab_rho(som);
          for (int k=tab1(som)-1; k<tab1(som+1)-1; k++) coeff(k)= (coeff(k)*inv_rho+coeff_diffusif(k)*inv_rho);
          matrice(som,som)+=derivee2(som)*inv_rho;
        }
    }
  else if (is_thermal() && fluide_dil.type_fluide()=="Gaz_Parfait")
    {
      fluide_dil.update_rho_cp(eqn.schema_temps().temps_courant());
      const DoubleTab& rhoCp = eqn.get_champ("rho_cp_comme_T").valeurs();
      for (int som=0 ; som<n ; som++)
        {
          double inv_rho = 1. / tab_rho(som);
          if (!is_generic()) inv_rho = 1.;
          double rapport = 1. / rhoCp(som);
// il faut multiplier toute la ligne de la matrice par rapport
          for (int k=tab1(som)-1; k<tab1(som+1)-1; k++) coeff(k)= (coeff(k)*inv_rho+coeff_diffusif(k)*rapport);
// ajout de Tdiv(rhou)/rho
          matrice(som,som) += derivee2(som)*inv_rho;
        }
    }
  else
    {
      Cerr<<"The implicit algorithm is available only for perfect gas."<<finl;
      Process::exit();
    }
// on a la matrice approchee on recalcule le residu;
  resu=0;
  derivee_en_temps_inco_sans_solveur_masse_impl(eqn,resu,false /* implicit */);
  matrice.ajouter_multvect(inco,resu);
  if (test_op)
    {
      DoubleTrav diff(resu), conv(resu);
      eqn.operateur(0).l_op_base().contribuer_au_second_membre(diff);
      eqn.operateur(1).l_op_base().contribuer_au_second_membre(conv);
      eqn.sources().ajouter(diff);
      double Cp = -5.;
      int is_cp_unif= sub_type(Champ_Uniforme,fluide_dil.capacite_calorifique().valeur());
      const DoubleTab& tab_cp = fluide_dil.capacite_calorifique().valeurs();
      if (is_cp_unif) Cp=tab_cp(0,0);
      for (int som=0 ; som<n ; som++)
        {
          if (!is_cp_unif) Cp=tab_cp(som);
          double inv_rho=1./tab_rho(som);
          if (!is_generic()) inv_rho=1;
          double rapport=1./(tab_rho(som)*Cp);
          diff(som)=resu(som)-conv(som)*inv_rho-diff(som)*rapport;
        }
      eqn.solv_masse().appliquer(diff);
      double err=mp_max_abs_vect(diff);
      Cerr << eqn.que_suis_je() <<" : Erreur assemblage = " << err << finl;;
      if (err > 1.e-5)
        {
          DoubleVect& diff_=diff;
          Cerr<<" size "<< diff_.size()<<finl;
          for (int i=0; i<diff_.size(); i++)
            if (std::fabs(diff_(i))>1e-5) Cerr<<i << " "<< diff_(i)<< " "<<finl;
          if (test_op==1)
            {
              Cerr<<" pb max case "<<imin_array(diff)<<" ou " <<imax_array(diff)<<finl;
              Process::exit();
            }
        }
    }
} /* END assembler_impl */
References Sources::ajouter(), Matrice_Base::ajouter_multvect(), Solveur_Masse::appliquer(), calculer_div_u_ou_div_rhou(), Milieu_base::capacite_calorifique(), Cerr, coeff, Operateur_base::contribuer_a_avec(), Sources::contribuer_a_avec(), Operateur_base::contribuer_au_second_membre(), derivee_en_temps_inco_sans_solveur_masse_impl(), TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, Convection_Diffusion_Fluide_Dilatable_base::fluide(), Equation_base::get_champ(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), imax_array(), imin_array(), is_generic(), is_thermal(), Operateur::l_op_base(), Milieu_base::masse_volumique(), mp_max_abs_vect(), Convection_Diffusion_std::operateur(), Objet_U::que_suis_je(), Equation_base::schema_temps(), TRUSTVect< _TYPE_ >::size(), Equation_base::solv_masse(), Equation_base::sources(), sub_type, Schema_Temps_base::temps_courant(), Fluide_Dilatable_base::type_fluide(), Fluide_Dilatable_base::update_rho_cp(), Deriv_Champ_Don_base::valeur(), Champ::valeurs(), Champ_Don::valeurs(), and Champ_Proto::valeurs().
Referenced by Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler(), Convection_Diffusion_Espece_Binaire_base::assembler(), and Convection_Diffusion_Espece_Multi_WC::assembler().
calculer_div_rho_u_impl()
void Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl (DoubleTab & res, const Convection_Diffusion_Fluide_Dilatable_base & eqn) const protected
Definition at line 37 of file Convection_Diffusion_Fluide_Dilatable_Proto.cpp.
{
  const Operateur& op_conv = eqn.operateur(1);
// No convective operator:
  if (sub_type(Op_Conv_negligeable,op_conv.l_op_base()))
    {
      Div=0;
      return;
    }
  DoubleTrav unite(eqn.inconnue().valeurs());
  unite=1;
  ref_cast_non_const(Operateur_base,op_conv.l_op_base()).associer_zone_cl_dis(eqn.zone_cl_modif());
  op_conv.ajouter(unite,Div);
  ref_cast_non_const(Operateur_base,op_conv.l_op_base()).associer_zone_cl_dis(eqn.zone_Cl_dis());
}
References Operateur::ajouter(), Convection_Diffusion_Fluide_Dilatable_base::inconnue(), Operateur::l_op_base(), Convection_Diffusion_std::operateur(), ref_cast_non_const, sub_type, Champ_Inc::valeurs(), Equation_base::zone_Cl_dis(), and Convection_Diffusion_Fluide_Dilatable_base::zone_cl_modif().
Referenced by Convection_Diffusion_Espece_Fluide_Dilatable_base::calculer_div_u_ou_div_rhou(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), and Convection_Diffusion_Chaleur_WC::calculer_div_u_ou_div_rhou().
calculer_div_u_ou_div_rhou()
virtual void Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_u_ou_div_rhou (DoubleTab & res) const protected pure virtual
Implemented in Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, and Convection_Diffusion_Fluide_Dilatable_base.
Referenced by assembler_blocs(), assembler_impl(), and derivee_en_temps_inco_sans_solveur_masse_impl().
derivee_en_temps_inco_sans_solveur_masse_impl()
DoubleTab & Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl (Convection_Diffusion_Fluide_Dilatable_base & eqn, DoubleTab & derivee, const bool is_expl) protected
Renvoie la derivee en temps de l'inconnue de l'equation.
Le calcul est le suivant:
d(inconnue)/dt = M^{-1} * (sources - somme(Op_{i}(inconnue))) / rho.
Returns
DoubleTab&
Signification: le tableau des valeurs de la derivee en temps du champ inconnu
Contraintes:
< Thermal equation + Gaz reel => No diffusion implicit ...
Definition at line 73 of file Convection_Diffusion_Fluide_Dilatable_Proto.cpp.
{
  /*
   * ATEENTION : THIS IS A GENERIC METHOD THAT IS USED TO SOLVE EXPLICITLY (OR DIFFUSION IMPLICIT)
   * A THERMAL OR SPECIES CONV/DIFF EQUATION. SO THE VARIABLE CAN EITHER BE THE TEMPERATURE T OR
   * THE MASS FRACTION Y.
   *
   * For the species equation for example, we have :
   * d(rho Y)/dt + div( rho*u*Y ) = div( rho*D*grad(Y) )
   *
   * With a non conservative formulation we write:
   * rho d(Y)/dt + Y d(rho)/dt + Y div (rho*u) + rho*u grad(Y) = div( rho*D*grad(Y) )
   *
   * Using the mass equation, we get :
   * rho d(Y)/dt + rho*u grad(Y) = div( rho*D*grad(Y) )
   *
   * divide by rho => d(Y)/dt = ( div( rho*D*grad(Y) ) + S ) / rho - u grad(Y)
   *
   * This is what we code here with derivee = d(Y)/dt
   *
   *
   * Similarly for the temperature equation, we code
   *
   * derivee = d(T)/dt = ( div( lambda*grad(T) ) + S ) / (rho*Cp) - u grad(T)
   */
  const Schema_Temps_base& sch = eqn.schema_temps();
  int diffusion_implicite=sch.diffusion_implicite();
  eqn.zone_Cl_dis().les_conditions_limites().set_modifier_val_imp(0);
  /*
   * FIRST TERM : diffusive
   * derivee = div( rho*D*grad(Y) ) or div( lambda*grad(T) )
   */
  Fluide_Dilatable_base& fluide_dil = eqn.fluide();
  if ( !is_thermal() /* species equation */ || (is_thermal() && fluide_dil.type_fluide()=="Gaz_Parfait" ))
    {
      if (!diffusion_implicite) eqn.operateur(0).ajouter(derivee);
    }
  else //!< Thermal equation + Gaz reel => No diffusion implicit ...
    {
      eqn.operateur(0).ajouter(fluide_dil.temperature(),derivee);
      if (diffusion_implicite)
        {
          Cerr << "Error: diffusion implicit not implemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base" << finl;
          Process::exit();
        }
    }
  eqn.zone_Cl_dis().les_conditions_limites().set_modifier_val_imp(1);
  derivee.echange_espace_virtuel();
// Add source term (if any, but for temperatur eit is sure !!!)
  eqn.sources().ajouter(derivee);
// On divise derivee  par rho si espece ou gaz reel... sinon par rho*Cp !
  const DoubleTab& tab_rho = fluide_dil.masse_volumique().valeurs();
  const int n = tab_rho.dimension(0);
  assert (tab_rho.line_size() == 1);
  if (is_thermal() && fluide_dil.type_fluide()=="Gaz_Parfait")
    {
      fluide_dil.update_rho_cp(sch.temps_courant());
      const DoubleTab& rhoCp = eqn.get_champ("rho_cp_comme_T").valeurs();
      for (int som=0 ; som<n ; som++) derivee(som) /= rhoCp(som);
    }
  else
    for (int som=0 ; som<n ; som++) derivee(som) /= tab_rho(som);
  derivee.echange_espace_virtuel();
  /*
   * SECOND TERM : convective
   * = - u grad(Y) = [Y div (rho*u) - div( rho*u*Y ) ]/ rho
   * or
   * = - u grad(T) = [ T div (rho*u) - div( rho*u*T ) ] / rho*Cp
   */
  DoubleTrav convection(derivee);
// Add Y div (rho*u) or T div (rho*u)
  const DoubleTab& inco = eqn.inconnue().valeurs();
  calculer_div_u_ou_div_rhou(convection);
  for (int som=0 ; som<n ; som++) convection(som) *= (-inco(som));
// Add convection operator: - div(rho*u*Y) or -div (rho*u*T)
  eqn.operateur(1).ajouter(convection);
// Divide by rho if necessary
  if (is_generic())
    for (int som=0 ; som<n ; som++) convection(som) /= tab_rho(som);
  /*
   * TOTAL TERM : diffusive + convective + sources
   */
  derivee+=convection;
  if (diffusion_implicite)
    {
      const DoubleTab& Tfutur=eqn.inconnue().futur();
      DoubleTrav secmem(derivee);
      secmem=derivee;
      eqn.solv_masse().appliquer(secmem);
      derivee = Tfutur;
      is_thermal() ? eqn.solv_masse()->set_name_of_coefficient_temporel("rho_cp_comme_T") :
      eqn.solv_masse()->set_name_of_coefficient_temporel("masse_volumique");
      eqn.Gradient_conjugue_diff_impl(secmem,derivee);
      eqn.solv_masse()->set_name_of_coefficient_temporel("no_coeff");
    }
// 100% explicite
  if (!sch.diffusion_implicite() && is_expl)
    {
      eqn.solv_masse().appliquer(derivee);
      derivee.echange_espace_virtuel();
    }
  return derivee;
} /* END derivee_en_temps_inco_sans_solveur_masse_impl */
References Operateur::ajouter(), Sources::ajouter(), Solveur_Masse::appliquer(), calculer_div_u_ou_div_rhou(), Cerr, Schema_Temps_base::diffusion_implicite(), TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, Convection_Diffusion_Fluide_Dilatable_base::fluide(), Champ_Inc::futur(), Equation_base::get_champ(), Equation_base::Gradient_conjugue_diff_impl(), Convection_Diffusion_Fluide_Dilatable_base::inconnue(), is_generic(), is_thermal(), Zone_Cl_dis::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Milieu_base::masse_volumique(), Convection_Diffusion_std::operateur(), Equation_base::schema_temps(), Cond_lim::set_modifier_val_imp(), Equation_base::solv_masse(), Equation_base::sources(), Fluide_Dilatable_base::temperature(), Schema_Temps_base::temps_courant(), Fluide_Dilatable_base::type_fluide(), Fluide_Dilatable_base::update_rho_cp(), Champ::valeurs(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), and Equation_base::zone_Cl_dis().
Referenced by assembler_blocs(), assembler_impl(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::derivee_en_temps_inco(), Convection_Diffusion_Espece_Binaire_base::derivee_en_temps_inco(), and Convection_Diffusion_Espece_Multi_WC::derivee_en_temps_inco().
is_generic()
virtual bool Convection_Diffusion_Fluide_Dilatable_Proto::is_generic () const protected pure virtual
Implemented in Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Chaleur_Fluide_Dilatable_base, and Convection_Diffusion_Fluide_Dilatable_base.
Referenced by assembler_blocs(), assembler_impl(), and derivee_en_temps_inco_sans_solveur_masse_impl().
is_thermal()
virtual bool Convection_Diffusion_Fluide_Dilatable_Proto::is_thermal () const protected pure virtual
Implemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, and Convection_Diffusion_Fluide_Dilatable_base.
Referenced by assembler_blocs(), assembler_impl(), and derivee_en_temps_inco_sans_solveur_masse_impl().
Reprendre_WC()
int Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC (Entree & is, double temps, Convection_Diffusion_std & eq, Fluide_Dilatable_base & fld, Champ_Inc & inco, Probleme_base & pb) static
< XXX : voir Convection_Diffusion_std
< Same discretization normally
Definition at line 420 of file Convection_Diffusion_Fluide_Dilatable_Proto.cpp.
{
// start resuming
  eq.reprendre_base(is); //!< XXX : voir Convection_Diffusion_std
// XXX : should be set so that Pression_EOS is read and not initialized from data file
  Fluide_Weakly_Compressible& FWC = ref_cast(Fluide_Weakly_Compressible,fld);
  FWC.set_resume_flag();
// resume EOS pressure field
  Champ_Inc p_tab = inco; //!< Same discretization normally
  p_tab->nommer("Pression_EOS");
  Nom field_tag(p_tab->le_nom());
  field_tag += p_tab.valeur().que_suis_je();
  field_tag += pb.domaine().le_nom();
  field_tag += Nom(temps,pb.reprise_format_temps());
  if (EcritureLectureSpecial::is_lecture_special() && Process::nproc() > 1)
    {
      Cerr << "Error in Convection_Diffusion_Espece_Binaire_WC::reprendre !" << finl;
      Cerr << "Use the sauv file to resume a parallel WC calculation (Pression_EOS is required) ... " << finl;
      Process::exit();
    }
  else
    {
      avancer_fichier(is, field_tag);
      p_tab->reprendre(is);
    }
// set good field
  FWC.set_pression_th_tab(p_tab->valeurs());
  return 1;
}
References avancer_fichier(), Cerr, Probleme_base::domaine(), Process::exit(), finl, EcritureLectureSpecial::is_lecture_special(), Domaine::le_nom(), O_U_Ptr::le_nom(), Objet_U::nommer(), Process::nproc(), Objet_U::que_suis_je(), ref_cast, Champ_Inc::reprendre(), Convection_Diffusion_std::reprendre_base(), Probleme_base::reprise_format_temps(), Fluide_Weakly_Compressible::set_pression_th_tab(), Fluide_Weakly_Compressible::set_resume_flag(), Deriv_Champ_Inc_base::valeur(), and Champ_Inc::valeurs().
Referenced by Convection_Diffusion_Chaleur_WC::reprendre(), and Convection_Diffusion_Espece_Binaire_WC::reprendre().
Sauvegarder_WC()
int Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC (Sortie & os, const Convection_Diffusion_std & eq, const Fluide_Dilatable_base & fld) static
< XXX : voir Convection_Diffusion_std
< Initialize with same discretization
< Use good values
Definition at line 397 of file Convection_Diffusion_Fluide_Dilatable_Proto.cpp.
{
  int bytes=0,a_faire,special;
  bytes += eq.sauvegarder_base(os); //!< XXX : voir Convection_Diffusion_std
  EcritureLectureSpecial::is_ecriture_special(special,a_faire);
  if (a_faire)
    {
      Fluide_Weakly_Compressible& FWC = ref_cast_non_const(Fluide_Weakly_Compressible,fld);
      Champ_Inc p_tab = FWC.inco_chaleur(); //!< Initialize with same discretization
      p_tab->nommer("Pression_EOS");
      p_tab->valeurs() = FWC.pression_th_tab(); //!< Use good values
      if (special && Process::nproc() > 1)
        Cerr << "ATTENTION : For a parallel calculation, the field Pression_EOS is not saved in xyz format ... " << finl;
      else
        bytes += p_tab->sauvegarder(os);
    }
  return bytes;
}
References Cerr, finl, Fluide_Dilatable_base::inco_chaleur(), EcritureLectureSpecial::is_ecriture_special(), Objet_U::nommer(), Process::nproc(), Fluide_Weakly_Compressible::pression_th_tab(), ref_cast_non_const, Champ_Inc::sauvegarder(), Convection_Diffusion_std::sauvegarder_base(), and Champ_Inc::valeurs().
Referenced by Convection_Diffusion_Chaleur_WC::sauvegarder(), and Convection_Diffusion_Espece_Binaire_WC::sauvegarder().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Equations/Convection_Diffusion_Fluide_Dilatable_Proto.h
src/ThHyd/Dilatable/Common/Equations/Convection_Diffusion_Fluide_Dilatable_Proto.cpp