TRUST: Champ_Fonc_Fonction_txyz_Morceaux Class Reference
Champ_Fonc_Fonction_txyz_Morceaux Class Reference
classe Champ_Fonc_Fonction_txyz_Morceaux
Cette classe represente un champ prenant par morceaux des valuers fonctions
de l'espace et d'un autre champ scalaire passe en parametre .
#include <Champ_Fonc_Fonction_txyz_Morceaux.h>
Public Member Functions
Champ_Fonc_Fonction_txyz_Morceaux ()
~Champ_Fonc_Fonction_txyz_Morceaux ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Champ_base & affecter_ (const Champ_base &ch)
NE FAIT RIEN.
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Renvoie la valeur du champ au point specifie
par ses coordonnees.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
Renvoie la valeur d'une composante du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees.
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
const Ref_Domaine & domaine () const
Renvoie une reference sur le domaine associe.
(version const)
Ref_Domaine & domaine ()
Renvoie une reference sur le domaine associe.
const List_Ref_Sous_Zone & sous_zones () const
Renvoie la liste des sous_zones associees.
(version const)
List_Ref_Sous_Zone & sous_zones ()
Renvoie la liste des sous_zones associees.
void mettre_a_jour (double temps)
NE FAIT RIEN
Mise a jour en temps.
int initialiser (const double &temps)
NE FAIT RIEN
A surcharger dans les classes derivees
Provoque l'initialisation du champ si necessaire.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Champ_Fonc_Fonction_txyz_Morceaux & self_cast (Objet_U &)
static const
Champ_Fonc_Fonction_txyz_Morceaux & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime les valeurs du champs sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit les valeurs du champ uniforme par morceaux
a partir d'un flot d'entree.
On lit le nom du domaine (nom_domaine) le nombre de
composantes du champ (nb_comp) la valeur par defaut
du champ ainsi que les valeurs sur les sous zones.
Format:
Champ_Fonc_Fonction_txyz_Morceaux nom_domaine nb_comp
{ Defaut val_def sous_zone_1 val_1 ... sous_zone_i val_i }.
Protected Attributes
List_Ref_Sous_Zone les_sous_zones
Ref_Domaine mon_domaine
Ref_Probleme_base ref_pb
Nom nom_champ_parametre_
Vect_Parser_U parser
IntTab parser_idx
Detailed Description
classe Champ_Fonc_Fonction_txyz_Morceaux
Cette classe represente un champ prenant par morceaux des valuers fonctions
de l'espace et d'un autre champ scalaire passe en parametre .
Definition at line 48 of file Champ_Fonc_Fonction_txyz_Morceaux.h.
Constructor & Destructor Documentation
Champ_Fonc_Fonction_txyz_Morceaux::Champ_Fonc_Fonction_txyz_Morceaux ()
Definition at line 31 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
Champ_Fonc_Fonction_txyz_Morceaux::~Champ_Fonc_Fonction_txyz_Morceaux ()
Definition at line 31 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
Member Function Documentation
Champ_base & Champ_Fonc_Fonction_txyz_Morceaux::affecter_ (const Champ_base & ch) [virtual]
NE FAIT RIEN.
Returns:
Champ_base&
Signification:
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 250 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr<<__FILE__<<(int)__LINE__<<" not coded" <<finl;
  exit();
  return (*this);
}
Objet_U * Champ_Fonc_Fonction_txyz_Morceaux::cree_instance () [static]
Definition at line 31 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
const Ref_Domaine & Champ_Fonc_Fonction_txyz_Morceaux::domaine () const
Renvoie une reference sur le domaine associe.
(version const)
Returns:
REF(Domaine)&
Signification: reference sur le domaine associe
Contraintes: reference constante
Definition at line 172 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References mon_domaine.
{
  return mon_domaine;
}
Ref_Domaine & Champ_Fonc_Fonction_txyz_Morceaux::domaine ()
Renvoie une reference sur le domaine associe.
Returns:
REF(Domaine)&
Signification: reference sur le domaine associe
Contraintes:
Definition at line 191 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References mon_domaine.
{
  return mon_domaine;
}
int Champ_Fonc_Fonction_txyz_Morceaux::duplique () const [virtual]
Implements Champ_Don_base.
Definition at line 31 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
const Type_info * Champ_Fonc_Fonction_txyz_Morceaux::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 31 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
const Type_info * Champ_Fonc_Fonction_txyz_Morceaux::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 31 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
int Champ_Fonc_Fonction_txyz_Morceaux::initialiser (const double & temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees
Provoque l'initialisation du champ si necessaire.
Reimplemented from Champ_Don_base.
Definition at line 600 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References mettre_a_jour().
{
  mettre_a_jour(time);
  return 1;
}
void Champ_Fonc_Fonction_txyz_Morceaux::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
Mise a jour en temps.
Reimplemented from Champ_Don_base.
Definition at line 566 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References ArrOfDouble::addr(), Domaine::coord(), DoubleTab::dimension(), Objet_U::dimension, Parser_U::eval(), Probleme_base::get_champ(), Zone::les_elems(), mon_domaine, Zone::nb_elem_tot(), Zone::nb_som_elem(), nom_champ_parametre_, parser, parser_idx, ref_pb, Parser_U::setVar(), Ref_Probleme_base::valeur(), Ref_Domaine::valeur(), Champ_Proto::valeurs(), Champ_Don_base::valeurs(), and Domaine::zone().
Referenced by initialiser().
{
  Domaine& le_domaine=mon_domaine.valeur();
  const IntTab& les_elems=le_domaine.zone(0).les_elems();
  const int nb_som_elem = le_domaine.zone(0).nb_som_elem();
  const Champ_base& ch=ref_pb.valeur().get_champ(nom_champ_parametre_);
  DoubleTab& tab = valeurs();
  for (int i = 0; i < le_domaine.zone(0).nb_elem_tot(); i++)
    {
      /* xs : coordonnees du poly par barycentre des sommets -> pas top */
      double xs[3] = { 0, };
      int nb_som = 0, s, r;
      for (int j = 0; j < nb_som_elem && (s = les_elems(i, j)) >= 0; j++)
        for (r = 0, nb_som++; r < dimension; r++) xs[r] += le_domaine.coord(s, r);
      for (r = 0; r < dimension; r++) xs[r] /= nb_som;
      /* calcul de chaque composante */
      double val = ch.valeurs().addr()[i];
      for (int k = 0; k < tab.dimension(1); k++)
        {
          Parser_U& psr = parser(parser_idx(i, k));
          psr.setVar("x", xs[0]);
          psr.setVar("y", xs[1]);
          psr.setVar("z", xs[2]);
          psr.setVar("t", time);
          psr.setVar("val", val);
          tab(i, k) = psr.eval();
        }
    }
}
Sortie & Champ_Fonc_Fonction_txyz_Morceaux::printOn (Sortie & os) const [protected, virtual]
Imprime les valeurs du champs sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 52 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References Champ_Don_base::valeurs().
{
  return os << valeurs();
}
Entree & Champ_Fonc_Fonction_txyz_Morceaux::readOn (Entree & is) [protected, virtual]
Lit les valeurs du champ uniforme par morceaux
a partir d'un flot d'entree.
On lit le nom du domaine (nom_domaine) le nombre de
composantes du champ (nb_comp) la valeur par defaut
du champ ainsi que les valeurs sur les sous zones.
Format:
Champ_Fonc_Fonction_txyz_Morceaux nom_domaine nb_comp
{ Defaut val_def sous_zone_1 val_1 ... sous_zone_i val_i }.
Returns:
Entree&
Signification: le champ d'entree modifie
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 81 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References List_Ref_Sous_Zone::add(), Vect_Parser_U::add(), Parser_U::addVar(), Cerr, Domaine::creer_tableau_elements(), Probleme_base::domaine(), Process::exit(), finl, Field_base::fixer_nb_comp(), les_sous_zones, Champ_Proto::lire_dimension(), mon_domaine, Sous_Zone::nb_elem_tot(), Zone::nb_elem_tot(), nom_champ_parametre_, Interprete::objet(), parser, parser_idx, Parser_U::parseString(), Objet_U::que_suis_je(), REF, ref_cast, ref_pb, DoubleTab::resize(), IntTab::resize(), Parser_U::setNbVar(), Parser_U::setString(), vect_impl::size(), Domaine::ss_zone(), Ref_Domaine::valeur(), Ref_Probleme_base::valeur(), Champ_Don_base::valeurs_, Champ_Fonc_Tabule::Warn_old_chp_fonc_syntax(), and Domaine::zone().
{
  int dim;
  Motcle motlu;
  Nom nom;
  int k, poly;
  is >> nom;
  ref_pb = ref_cast(Probleme_base, Interprete::objet(nom));
  mon_domaine = ref_pb.valeur().domaine();
  Domaine& le_domaine=mon_domaine.valeur();
  Nom val1, val2;
  is >> val1;
  is >> val2;
  Champ_Fonc_Tabule::Warn_old_chp_fonc_syntax("Champ_Fonc_Fonction_txyz_Morceaux", val1, val2, dim, nom_champ_parametre_);
  dim=lire_dimension(dim,que_suis_je());
  fixer_nb_comp(dim);
  parser_idx.resize(0, dim);
  le_domaine.creer_tableau_elements(parser_idx);
  valeurs_.resize(0, dim);
  le_domaine.creer_tableau_elements(valeurs_);
  is >> nom;
  motlu=nom;
  if(motlu != Motcle("{") )
    {
      Cerr << "Error while reading a " << que_suis_je() << finl;
      Cerr << "We expected a { instead of " << nom << finl;
      exit();
    }
  is >> motlu;
  if(motlu != Motcle("defaut") )
    {
      Cerr << "Error while reading a " << que_suis_je() << finl;
      Cerr << "We expected defaut instead of " << nom << finl;
      exit();
    }
  /* parsers par defaut */
  for(k=0; k< dim; k++)
    {
      Parser_U psr;
      Nom tmp;
      is >> tmp;
      psr.setNbVar(5);
      psr.setString(tmp);
      psr.addVar("val"), psr.addVar("t"), psr.addVar("x"), psr.addVar("y"), psr.addVar("z");
      psr.parseString();
      for (poly=0; poly<le_domaine.zone(0).nb_elem_tot(); poly++) parser_idx(poly, k) = parser.size();
      parser.add(psr);
    }
  Nom nom_zone;
  is >> nom_zone;
  while (nom_zone != Nom("}") )
    {
      REF(Sous_Zone) refssz=les_sous_zones.add(le_domaine.ss_zone(nom_zone));
      Sous_Zone& ssz = refssz.valeur();
      for( k=0; k< dim; k++)
        {
          Parser_U psr;
          Nom tmp;
          is >> tmp;
          psr.setNbVar(5);
          psr.setString(tmp);
          psr.addVar("val"), psr.addVar("t"), psr.addVar("x"), psr.addVar("y"), psr.addVar("z");
          psr.parseString();
          for (poly=0; poly < ssz.nb_elem_tot(); poly++) parser_idx(ssz(poly), k) = parser.size();
          parser.add(psr);
        }
      is >> nom_zone;
    }
  return is;
}
Champ_Fonc_Fonction_txyz_Morceaux & Champ_Fonc_Fonction_txyz_Morceaux::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Don_base.
Definition at line 31 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
const Champ_Fonc_Fonction_txyz_Morceaux & Champ_Fonc_Fonction_txyz_Morceaux::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Don_base.
Definition at line 31 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
List_Ref_Sous_Zone & Champ_Fonc_Fonction_txyz_Morceaux::sous_zones ()
Renvoie la liste des sous_zones associees.
Returns:
LIST(REF(Sous_Zone))&
Signification: la liste des sous_zones associees
Contraintes:
Definition at line 230 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References les_sous_zones.
{
  return les_sous_zones;
}
const List_Ref_Sous_Zone & Champ_Fonc_Fonction_txyz_Morceaux::sous_zones () const
Renvoie la liste des sous_zones associees.
(version const)
Returns:
LIST(REF(Sous_Zone))&
Signification: la liste des sous_zones associees
Contraintes: reference constante
Definition at line 211 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References les_sous_zones.
{
  return les_sous_zones;
}
unsigned Champ_Fonc_Fonction_txyz_Morceaux::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 31 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
DoubleVect & Champ_Fonc_Fonction_txyz_Morceaux::valeur_a (const DoubleVect & positions, DoubleVect & tab_valeurs) const [virtual]
Renvoie la valeur du champ au point specifie
par ses coordonnees.
Returns:
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 278 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References Zone::chercher_elements(), mon_domaine, and valeur_a_elem().
{
  const Zone& la_zone = mon_domaine->zone(0);
  IntVect le_poly(1);
  la_zone.chercher_elements(positions,le_poly);
  return valeur_a_elem(positions,tab_valeurs,le_poly[0]);
}
DoubleVect & Champ_Fonc_Fonction_txyz_Morceaux::valeur_a_elem (const DoubleVect & position, DoubleVect & val, int le_poly) const [virtual]
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Returns:
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 314 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References Cerr, Process::exit(), finl, Field_base::nb_compo_, DoubleVect::size(), and Champ_Don_base::valeurs().
Referenced by valeur_a().
{
  if (val.size() != nb_compo_)
    {
      Cerr << "Error TRUST in Champ_Fonc_Fonction_txyz_Morceaux::valeur_a_elem()" << finl;
      Cerr << "The DoubleVect val doesn't have the correct size" << finl;
      exit();
    }
  const DoubleTab& ch = valeurs();
  if (nb_compo_ == 1)
    val(0) = ch(le_poly,0);
  else
    for (int k=0; k<nb_compo_; k++)
      val(k) = ch(le_poly,k);
  return val;
}
double Champ_Fonc_Fonction_txyz_Morceaux::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const [virtual]
Renvoie la valeur d'une composante du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Returns:
double
Signification: la valeur de la composante du champ specifiee au
point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 364 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References Cerr, Process::exit(), finl, Field_base::nb_compo_, and Champ_Don_base::valeurs().
{
  double val;
  if (ncomp > nb_compo_)
    {
      Cerr << "Error TRUST in Champ_Fonc_Fonction_txyz_Morceaux::valeur_a_elem_compo()" << finl;
      Cerr << "the integer ncomp is upper than the number of field components" << finl;
      exit();
    }
  const DoubleTab& ch = valeurs();
  if (nb_compo_ == 1)
    val = ch(le_poly,0);
  else
    val = ch(le_poly,ncomp);
  return val;
}
DoubleTab & Champ_Fonc_Fonction_txyz_Morceaux::valeur_aux (const DoubleTab & positions, DoubleTab & tab_valeurs) const [virtual]
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 407 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References Zone::chercher_elements(), mon_domaine, Zone::nb_elem(), and valeur_aux_elems().
{
  const Zone& la_zone = mon_domaine->zone(0);
  IntVect les_polys(la_zone.nb_elem());
  la_zone.chercher_elements(positions,les_polys);
  return valeur_aux_elems(positions,les_polys,tab_valeurs);
}
DoubleVect & Champ_Fonc_Fonction_txyz_Morceaux::valeur_aux_compo (const DoubleTab & positions, DoubleVect & tab_valeurs, int ncomp) const [virtual]
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees.
Returns:
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 444 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References Zone::chercher_elements(), mon_domaine, Zone::nb_elem(), and valeur_aux_elems_compo().
{
  const Zone& la_zone = mon_domaine->zone(0);
  IntVect les_polys(la_zone.nb_elem());
  la_zone.chercher_elements(positions,les_polys);
  return valeur_aux_elems_compo(positions,les_polys,tab_valeurs,ncomp);
}
DoubleTab & Champ_Fonc_Fonction_txyz_Morceaux::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & val) const [virtual]
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 481 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References Cerr, DoubleTab::dimension(), DoubleTab::dimension_tot(), Process::exit(), finl, Field_base::nb_compo_, DoubleTab::nb_dim(), IntVect::size(), and Champ_Don_base::valeurs().
Referenced by valeur_aux().
{
  if (val.nb_dim() == 2)
    {
      assert((val.dimension(0) == les_polys.size())||(val.dimension_tot(0) == les_polys.size()));
      assert(val.dimension(1) == nb_compo_);
    }
  else
    {
      Cerr << "Error TRUST in Champ_Fonc_Fonction_txyz_Morceaux::valeur_aux_elems()" << finl;
      Cerr << "The DoubleTab val don't have 2 entries" << finl;
      exit();
    }
  const DoubleTab& ch = valeurs();
  val = 0.;
  int p;
  for(int rang_poly=0; rang_poly<les_polys.size(); rang_poly++)
    if ((p = les_polys(rang_poly)) != -1)
      for(int n = 0; n < nb_compo_; n++)
        val(rang_poly, n) = ch(p, n);
  return val;
}
DoubleVect & Champ_Fonc_Fonction_txyz_Morceaux::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & val, int ncomp) const [virtual]
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 545 of file Champ_Fonc_Fonction_txyz_Morceaux.cpp.
References IntVect::size(), DoubleVect::size(), and Champ_Don_base::valeurs().
Referenced by valeur_aux_compo().
{
  assert(val.size() == les_polys.size());
  int le_poly;
  const DoubleTab& ch = valeurs();
  for(int rang_poly=0; rang_poly<les_polys.size(); rang_poly++)
    {
      le_poly=les_polys(rang_poly);
      if (le_poly == -1)
        val(rang_poly) = 0;
      else
        val(rang_poly) = ch(le_poly,ncomp);
    }
  return val;
}
Member Data Documentation
const Type_info Champ_Fonc_Fonction_txyz_Morceaux::info_obj [static]
Reimplemented from Champ_Don_base.
Definition at line 51 of file Champ_Fonc_Fonction_txyz_Morceaux.h.
List_Ref_Sous_Zone Champ_Fonc_Fonction_txyz_Morceaux::les_sous_zones [protected]
Definition at line 85 of file Champ_Fonc_Fonction_txyz_Morceaux.h.
Referenced by readOn(), and sous_zones().
Ref_Domaine Champ_Fonc_Fonction_txyz_Morceaux::mon_domaine [protected]
Definition at line 86 of file Champ_Fonc_Fonction_txyz_Morceaux.h.
Referenced by domaine(), mettre_a_jour(), readOn(), valeur_a(), valeur_aux(), and valeur_aux_compo().
Nom Champ_Fonc_Fonction_txyz_Morceaux::nom_champ_parametre_ [protected]
Definition at line 89 of file Champ_Fonc_Fonction_txyz_Morceaux.h.
Referenced by mettre_a_jour(), and readOn().
Vect_Parser_U Champ_Fonc_Fonction_txyz_Morceaux::parser [protected]
Definition at line 90 of file Champ_Fonc_Fonction_txyz_Morceaux.h.
Referenced by mettre_a_jour(), and readOn().
IntTab Champ_Fonc_Fonction_txyz_Morceaux::parser_idx [protected]
Definition at line 91 of file Champ_Fonc_Fonction_txyz_Morceaux.h.
Referenced by mettre_a_jour(), and readOn().
Ref_Probleme_base Champ_Fonc_Fonction_txyz_Morceaux::ref_pb [protected]
Definition at line 87 of file Champ_Fonc_Fonction_txyz_Morceaux.h.
Referenced by mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Fonc_Fonction_txyz_Morceaux.h
src/Kernel/Champs/Champ_Fonc_Fonction_txyz_Morceaux.cpp