TRUST: Convection_Diffusion_Concentration Class Reference
Convection_Diffusion_Concentration Class Reference
classe Convection_Diffusion_Concentration
Cas particulier de Convection_Diffusion_std
pour un ou plusieurs constituants.
Dans le cas de plusieurs constituants les champs
concentration et diffusivite sont vectoriels.
#include <Convection_Diffusion_Concentration.h>
Public Member Functions
~Convection_Diffusion_Concentration ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &titi) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Convection_Diffusion_Concentration ()
const Milieu_base & milieu () const override
Renvoie le milieu physique de l'equation.
(un Constituant upcaste en Milieu_base)
(version const)
Milieu_base & milieu () override
Renvoie le milieu physique de l'equation.
(un Constituant upcaste en Milieu_base)
const Constituant & constituant () const
Renvoie le constituant (si il a ete associe).
(version const)
Constituant & constituant ()
Renvoie le constituant (si il a ete associe).
void associer_milieu_base (const Milieu_base &) override
Associe un milieu physique a l'equation,
le milieu est en fait caste en Constituant et associe a l'equation.
void associer_constituant (const Constituant &)
Associe un constituant a l'equation.
void discretiser () override
Discretise l'equation.
const Champ_Inc & inconnue () const override
Renvoie le champ inconnue de l'equation: la concentration.
(version const)
Champ_Inc & inconnue () override
Renvoie le champ inconnue de l'equation: la concentration.
int nb_constituants () const
Renvoie le nombre de constituants du "Constituant" de l'equation.
int impr (Sortie &os) const override
Impression des flux sur les bords sur un flot de sortie.
Appelle Equation_base::impr(Sortie&)
int preparer_calcul () override
Tout ce qui ne depend pas des autres problemes eventuels.
void mettre_a_jour (double) override
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
const Champ_Don & diffusivite_pour_transport () const override
const Motcle & domaine_application () const override
Renvoie le nom du domaine d'application de l'equation.
Ici "Concentration".
const double & masse_molaire () const
Public Member Functions inherited from Convection_Diffusion_std
Convection_Diffusion_std ()
~Convection_Diffusion_std () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &titi) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
int nombre_d_operateurs () const override
Renvoie le nombre d'operateurs de l'equation:
2 pour une equation de diffusion.
const Operateur & operateur (int) const override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1
(version const)
Operateur & operateur (int) override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1.
void associer_vitesse (const Champ_base &)
Associe la vitesse transportante a l'equation.
const Champ_Inc_base & vitesse_transportante () const
Renvoie une reference sur le champ representant
la vitesse transportante.
const Champ_Inc & inconnue () const override=0
Champ_Inc & inconnue () override=0
virtual const Champ_Don & diffusivite_pour_transport () const
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
virtual const Champ_base & vitesse_pour_transport () const
int sauvegarder_base (Sortie &) const
int reprendre_base (Entree &)
Public Member Functions inherited from Equation_base
Equation_base ()
~Equation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Methode appelee lorsqu'on cree l'instance de l'objet dans
le jeu de donnees (Interprete::ajouter)
virtual void avancer (int i=1)
virtual void reculer (int i=1)
virtual int nombre_d_operateurs () const =0
virtual int nombre_d_operateurs_tot () const
virtual const Operateur & operateur (int) const =0
virtual Operateur & operateur (int)=0
virtual const Operateur & operateur_fonctionnel (int) const
virtual Operateur & operateur_fonctionnel (int)
virtual const Champ_Inc & inconnue () const =0
virtual Champ_Inc & inconnue ()=0
virtual void associer_milieu_base (const Milieu_base &)=0
virtual const Milieu_base & milieu () const =0
virtual Milieu_base & milieu ()=0
int sauvegarder (Sortie &) const override
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
int reprendre (Entree &) override
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
int limpr () const
Demande au schema en temps si il faut effectuer une impression.
Renvoie 1 si il faut effectuer une impression.
Appel simple a Schema_Temps_base::limpr()
virtual void imprimer (Sortie &os) const
Imprime les operateurs de l'equation si le schema en temps
indique que c'est necessaire.
[SI limpr() ALORS impr(os)].
virtual int impr (Sortie &os) const
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
virtual void associer_milieu_equation ()
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
virtual DoubleTab & derivee_en_temps_inco_transport (DoubleTab &derivee)
virtual DoubleTab & corriger_derivee_expl (DoubleTab &)
virtual DoubleTab & corriger_derivee_impl (DoubleTab &)
virtual void mettre_a_jour (double temps)
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
virtual void abortTimeStep ()
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
virtual void valider_iteration ()
virtual int preparer_calcul ()
Tout ce qui ne depend pas des autres problemes eventuels.
virtual bool initTimeStep (double dt)
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
virtual bool updateGivenFields ()
virtual void discretiser ()
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
virtual void associer_pb_base (const Probleme_base &)
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur
de masse a l'equation.
virtual void completer ()
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
virtual double calculer_pas_de_temps () const
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des
pas de temps calcules par les operateurs.
Ces pas de temps sont ceux pour le schema d'Euler explicite.
Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule.
void calculer_pas_de_temps_locaux (DoubleTab &) const
Sources & sources ()
Renvoie les termes sources asssocies a l'equation.
const Sources & sources () const
Renvoie les termes sources asssocies a l'equation<br>(version const)
Solveur_Masse & solv_masse ()
Renvoie le solveur de masse associe a l'equation.
const Solveur_Masse & solv_masse () const
Renvoie le solveur de masse associe a l'equation.
(version const)
Probleme_base & probleme ()
Renvoie le probleme associe a l'equation.
const Probleme_base & probleme () const
Renvoie le probleme associe a l'equation.
(version const)
Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe a l'equation.
const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe a l'equation.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
S'associe au schema_en_temps.
virtual void associer_zone_dis (const Zone_dis &)
Associe la zone discretisee a l'equation.
const Discretisation_base & discretisation () const
Renvoie la discretisation associee a l'equation.
virtual Zone_Cl_dis & zone_Cl_dis ()
Renvoie la zone des conditions aux limite discretisee
associee a l'equation.
virtual const Zone_Cl_dis & zone_Cl_dis () const
Renvoie la zone des conditions aux limite discretisee
associee a l'equation<br>(version const)
Zone_dis & zone_dis ()
Renvoie la zone discretisee associee a l'equation.
const Zone_dis & zone_dis () const
Renvoie la zone discretisee associee a l'equation.
(version const)
const Nom & le_nom () const override
Renvoie le nom de l'equation.
DoubleVect & get_residu ()
DoubleVect & residu_initial ()
void initialise_residu (int=0)
virtual void imprime_residu (SFichier &)
virtual Nom expression_residu ()
virtual void dimensionner_matrice (Matrice_Morse &mat_morse)
virtual void dimensionner_matrice_sans_mem (Matrice_Morse &mat_morse)
virtual void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void modifier_pour_Cl (Matrice_Morse &mat_morse, DoubleTab &secmem) const
virtual void assembler_avec_inertie (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void dimensionner_termes_croises (Matrice_Morse &matrice, const Probleme_base &autre_pb, int nl, int nc)
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void assembler_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={})
Champ_Inc_base & champ_conserve () const
int has_champ_conserve () const
void init_champ_conserve () const
virtual std::pair< std::string, fonc_calc_t > get_fonc_champ_conserve () const
virtual Champ_Inc_base & champ_convecte () const
virtual int has_champ_convecte () const
virtual void init_champ_convecte () const
virtual void mettre_a_jour_champs_conserves (double temps, int reset=0)
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Motcle & domaine_application () const
Renvoie "indetermine"
Navier_Stokes_standard par exemple surcharge cette methode
pour renvoyer "Hydraulique".
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Verification du nombre de composantes lues pour la specification d un champ.
Actuellement utilise pour la lecture d un condition initiale ou limite.
virtual void verifie_ch_init_nb_comp_cl (const Champ_Inc_base &ch_ref, const int nb_comp, const Cond_lim_base &cl) const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
Add convection term
In: solution is the unknown I
Out: secmem is increased by convection(I)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution, const DoubleTab &terme_mul)
Parametre_equation & parametre_equation ()
const Parametre_equation & parametre_equation () const
virtual const Ref_Objet_U & get_modele (Type_modele type) const
virtual int equation_non_resolue () const
int disable_equation_residual () const
virtual const Champ_Inc & derivee_en_temps () const
virtual Champ_Inc & derivee_en_temps ()
void set_calculate_time_derivative (int i)
int calculate_time_derivative () const
void set_residuals (DoubleTab r)
virtual int positive_unkown ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Convection_Diffusion_Concentration & self_cast (Objet_U &)
static const Convection_Diffusion_Concentration & self_cast (const Objet_U &)
Static Public Member Functions inherited from Convection_Diffusion_std
static const Type_info * info ()
static Convection_Diffusion_std & self_cast (Objet_U &)
static const Convection_Diffusion_std & self_cast (const Objet_U &)
Static Public Member Functions inherited from Equation_base
static const Type_info * info ()
static Equation_base & self_cast (Objet_U &)
static const Equation_base & self_cast (const Objet_U &)
static void calculer_champ_conserve (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Convection_Diffusion_std
static const Type_info info_obj
Static Public Attributes inherited from Equation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Convection_Diffusion_std::printOn(Sortie&)
Entree & readOn (Entree &) override
Verifie si l'equation a une concentration et un constituant associe
et appelle Convection_Diffusion_std::readOn(Entree&).
Protected Member Functions inherited from Convection_Diffusion_std
Sortie & printOn (Sortie &x) const override
Simple appel a Equation_base::printOn(Sortie&)
Entree & readOn (Entree &) override
cf Equation_base::readOn(Entree&)
Protected Member Functions inherited from Equation_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
virtual void set_param (Param &titi)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_sources (Entree &)
Lecture des termes sources dans un flot d'entree.
virtual Entree & lire_cond_init (Entree &)
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
virtual Entree & lire_cl (Entree &)
Lecture des conditions limites sur un flot d'entree.
voir Zone_Cl_dis_base::readOn.
virtual int verif_Cl () const
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
virtual void lire ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int nb_constituants_
Champ_Inc la_concentration
Ref_Constituant le_constituant
double masse_molaire_
Protected Attributes inherited from Convection_Diffusion_std
Ref_Champ_Inc_base la_vitesse_transportante
Operateur_Conv terme_convectif
Operateur_Diff terme_diffusif
Protected Attributes inherited from Equation_base
Nom nom_
Solveur_Masse solveur_masse
Sources les_sources
Ref_Schema_Temps_base le_schema_en_temps
Ref_Zone_dis la_zone_dis
Zone_Cl_dis la_zone_Cl_dis
Ref_Probleme_base mon_probleme
DoubleList dt_op_bak
int sys_invariant_
int implicite_
Parametre_equation parametre_equation_
Champ_Fonc volume_maille
List_RefObjU liste_modeles_
Champs_compris champs_compris_
Champs_Fonc list_champ_combi
Matrice_Morse matrice_stockee
int matrice_init
Champ_Inc champ_conserve_
Champ_Inc champ_convecte_
Detailed Description
classe Convection_Diffusion_Concentration
Cas particulier de Convection_Diffusion_std
pour un ou plusieurs constituants.
Dans le cas de plusieurs constituants les champs
concentration et diffusivite sont vectoriels.
Definition at line 33 of file Convection_Diffusion_Concentration.h.
Constructor & Destructor Documentation
~Convection_Diffusion_Concentration()
Convection_Diffusion_Concentration::~Convection_Diffusion_Concentration ()
Definition at line 25 of file Convection_Diffusion_Concentration.cpp.
Convection_Diffusion_Concentration()
Convection_Diffusion_Concentration::Convection_Diffusion_Concentration ()
Definition at line 27 of file Convection_Diffusion_Concentration.cpp.
                                                                      :masse_molaire_(-1.)
{
// On dimensionne liste_noms_compris et on remplit dans readOn()
}
Member Function Documentation
associer_constituant()
void Convection_Diffusion_Concentration::associer_constituant (const Constituant & un_constituant) inline
Associe un constituant a l'equation.
Definition at line 82 of file Convection_Diffusion_Concentration.h.
{
  le_constituant = un_constituant;
}
References le_constituant.
Referenced by associer_milieu_base().
associer_milieu_base()
void Convection_Diffusion_Concentration::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation,
le milieu est en fait caste en Constituant et associe a l'equation.
Implements Equation_base.
Definition at line 156 of file Convection_Diffusion_Concentration.cpp.
{
  const Constituant& un_constituant = ref_cast(Constituant,un_milieu);
  if (un_constituant.diffusivite_constituant().non_nul())
    associer_constituant(un_constituant);
  else
    {
      Cerr << "The dye (constituant) diffusivity has not been defined." << finl ;
      exit();
    }
}
References associer_constituant(), Cerr, Constituant::diffusivite_constituant(), Process::exit(), finl, O_U_Ptr::non_nul(), and ref_cast.
Referenced by Pb_Hydraulique_Concentration::associer_milieu_base(), and Pb_Thermohydraulique_Concentration::associer_milieu_base().
constituant() [1/2]
Constituant & Convection_Diffusion_Concentration::constituant ()
Renvoie le constituant (si il a ete associe).
Returns
Constituant&
Signification: le constituant associe a l'equation
Contraintes:
Definition at line 281 of file Convection_Diffusion_Concentration.cpp.
{
  if(!le_constituant.non_nul())
    {
      Cerr << "No constituant has been associated "
           << "with a Convection_Diffusion_Concentration equation." << finl;
      exit();
    }
  return le_constituant.valeur();
}
References Cerr, Process::exit(), finl, le_constituant, O_U_Ptr::non_nul(), and Ref_Constituant::valeur().
constituant() [2/2]
const Constituant & Convection_Diffusion_Concentration::constituant () const
Renvoie le constituant (si il a ete associe).
(version const)
Returns
Constituant&
Signification: le constituant associe a l'equation
Contraintes: reference constante
Definition at line 256 of file Convection_Diffusion_Concentration.cpp.
{
  if(!le_constituant.non_nul())
    {
      Cerr << "You forgot to associate the constituent to the problem named " << probleme().le_nom() << finl;
      Process::exit();
    }
  return le_constituant.valeur();
}
References Cerr, Process::exit(), finl, le_constituant, Probleme_base::le_nom(), O_U_Ptr::non_nul(), Equation_base::probleme(), and Ref_Constituant::valeur().
Referenced by diffusivite_pour_transport(), discretiser(), mettre_a_jour(), milieu(), and preparer_calcul().
cree_instance()
Objet_U * Convection_Diffusion_Concentration::cree_instance () static
Definition at line 25 of file Convection_Diffusion_Concentration.cpp.
diffusivite_pour_transport()
const Champ_Don & Convection_Diffusion_Concentration::diffusivite_pour_transport () const override virtual
Reimplemented from Convection_Diffusion_std.
Definition at line 168 of file Convection_Diffusion_Concentration.cpp.
{
  return constituant().diffusivite_constituant();
}
References constituant(), and Constituant::diffusivite_constituant().
discretiser()
void Convection_Diffusion_Concentration::discretiser () override virtual
Discretise l'equation.
Reimplemented from Equation_base.
Definition at line 187 of file Convection_Diffusion_Concentration.cpp.
{
  const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
  Cerr << "Transport concentration(s) equation discretization " << finl;
  nb_constituants_ = constituant().nb_constituants();
  dis.concentration(schema_temps(), zone_dis(), la_concentration, nb_constituants_);
  champs_compris_.ajoute_champ(la_concentration);
  Equation_base::discretiser();
}
References Champs_compris::ajoute_champ(), Cerr, Equation_base::champs_compris_, Discret_Thyd::concentration(), constituant(), Equation_base::discretisation(), Equation_base::discretiser(), finl, la_concentration, Constituant::nb_constituants(), nb_constituants_, ref_cast, Equation_base::schema_temps(), and Equation_base::zone_dis().
domaine_application()
const Motcle & Convection_Diffusion_Concentration::domaine_application () const override virtual
Renvoie le nom du domaine d'application de l'equation.
Ici "Concentration".
Returns
Motcle&
Signification: le nom du domaine d'application de l'equation
Contraintes: toujours egal a "Concentration"
Reimplemented from Equation_base.
Definition at line 387 of file Convection_Diffusion_Concentration.cpp.
{
  static Motcle domaine = "Concentration";
  return domaine;
}
duplique()
int Convection_Diffusion_Concentration::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file Convection_Diffusion_Concentration.cpp.
get_info()
const Type_info * Convection_Diffusion_Concentration::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Equation_base.
Definition at line 25 of file Convection_Diffusion_Concentration.cpp.
impr()
int Convection_Diffusion_Concentration::impr (Sortie & os) const override virtual
Impression des flux sur les bords sur un flot de sortie.
Appelle Equation_base::impr(Sortie&)
Returns
int
Signification: code de retour propage
Contraintes:
Reimplemented from Equation_base.
Definition at line 321 of file Convection_Diffusion_Concentration.cpp.
{
  return Equation_base::impr(os);
}
References Equation_base::impr().
inconnue() [1/2]
const Champ_Inc & Convection_Diffusion_Concentration::inconnue () const inline override virtual
Renvoie le champ inconnue de l'equation: la concentration.
(version const)
Returns
Champ_Inc&
Signification: le champ inconnue de l'equation, la concentration.
Contraintes: reference constante
Implements Convection_Diffusion_std.
Definition at line 103 of file Convection_Diffusion_Concentration.h.
{
  return la_concentration;
}
References la_concentration.
Referenced by Chimie::completer(), lire_motcle_non_standard(), and readOn().
inconnue() [2/2]
Champ_Inc & Convection_Diffusion_Concentration::inconnue () inline override virtual
Renvoie le champ inconnue de l'equation: la concentration.
Returns
Champ_Inc&
Signification: le champ inconnue de l'equation, la concentration.
Contraintes:
Implements Convection_Diffusion_std.
Definition at line 123 of file Convection_Diffusion_Concentration.h.
{
  return la_concentration;
}
References la_concentration.
info()
const Type_info * Convection_Diffusion_Concentration::info () static
Definition at line 25 of file Convection_Diffusion_Concentration.cpp.
lire_motcle_non_standard()
int Convection_Diffusion_Concentration::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
< Question: veut-on le mettre en majuscules ?
< Question: veut-on le mettre en majuscules ?
Reimplemented from Equation_base.
Definition at line 113 of file Convection_Diffusion_Concentration.cpp.
{
  if (mot=="nom_inconnue")
    {
      Motcle nom; //!< Question: veut-on le mettre en majuscules ?
      is >> nom;
      Cerr << "The unknow of a Convection_Diffusion_Concentration equation is renamed"
           << "\n Old name : " << inconnue().valeur().le_nom()
           << "\n New name : " << nom << finl;
      inconnue().valeur().nommer(nom);
      return 1;
    }
  else if (mot=="alias")
    {
      Motcle nom; //!< Question: veut-on le mettre en majuscules ?
      is >> nom;
      Cerr << "nom_inconnue: On renomme l'equation et son inconnue"
           << "\n Ancien nom : " << inconnue().valeur().le_nom()
           << "\n Nouveau nom : " << nom << finl;
      inconnue().valeur().nommer(nom);
      return 1;
    }
  else
    return Convection_Diffusion_std::lire_motcle_non_standard(mot,is);
  return 1;
}
References Cerr, finl, inconnue(), Field_base::le_nom(), Convection_Diffusion_std::lire_motcle_non_standard(), Field_base::nommer(), and Deriv_Champ_Inc_base::valeur().
masse_molaire()
const double & Convection_Diffusion_Concentration::masse_molaire () const
Definition at line 99 of file Convection_Diffusion_Concentration.cpp.
{
  assert(masse_molaire_>0);
  return masse_molaire_;
}
References masse_molaire_.
Referenced by Chimie::completer().
mettre_a_jour()
void Convection_Diffusion_Concentration::mettre_a_jour (double temps) override virtual
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
Reimplemented from Equation_base.
Definition at line 300 of file Convection_Diffusion_Concentration.cpp.
{
  Equation_base::mettre_a_jour(temps);
  constituant().mettre_a_jour(temps);
}
References constituant(), Equation_base::mettre_a_jour(), and Constituant::mettre_a_jour().
milieu() [1/2]
const Milieu_base & Convection_Diffusion_Concentration::milieu () const override virtual
Renvoie le milieu physique de l'equation.
(un Constituant upcaste en Milieu_base)
(version const)
Returns
Milieu_base&
Signification: le Constituant upcaste en Milieu_base
Contraintes: reference constante
Implements Equation_base.
Definition at line 214 of file Convection_Diffusion_Concentration.cpp.
{
  return constituant();
}
References constituant().
milieu() [2/2]
Milieu_base & Convection_Diffusion_Concentration::milieu () override virtual
Renvoie le milieu physique de l'equation.
(un Constituant upcaste en Milieu_base)
Returns
Milieu_base&
Signification: le Constituant upcaste en Milieu_base
Contraintes:
Implements Equation_base.
Definition at line 235 of file Convection_Diffusion_Concentration.cpp.
{
  return constituant();
}
References constituant().
nb_constituants()
int Convection_Diffusion_Concentration::nb_constituants () const inline
Renvoie le nombre de constituants du "Constituant" de l'equation.
Returns
int
Signification: le nombre de constituants de l'equation
Contraintes:
Definition at line 143 of file Convection_Diffusion_Concentration.h.
{
  return nb_constituants_;
}
References nb_constituants_.
preparer_calcul()
int Convection_Diffusion_Concentration::preparer_calcul (void) override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Equation_base.
Definition at line 292 of file Convection_Diffusion_Concentration.cpp.
{
  Equation_base::preparer_calcul();
  double temps=schema_temps().temps_courant();
  constituant().initialiser(temps);
  return 1;
}
References constituant(), Constituant::initialiser(), Equation_base::preparer_calcul(), Equation_base::schema_temps(), and Schema_Temps_base::temps_courant().
printOn()
Sortie & Convection_Diffusion_Concentration::printOn (Sortie & is) const override protected virtual
Simple appel a: Convection_Diffusion_std::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Equation_base.
Definition at line 45 of file Convection_Diffusion_Concentration.cpp.
{
  return Convection_Diffusion_std::printOn(is);
}
References Convection_Diffusion_std::printOn().
readOn()
Entree & Convection_Diffusion_Concentration::readOn (Entree & is) override protected virtual
Verifie si l'equation a une concentration et un constituant associe
et appelle Convection_Diffusion_std::readOn(Entree&).
Returns
Entree& is
Signification: le flot d'entree modifie
Contraintes:
< On ajoute le nom de l'inconnue pour prevoir une equation de scalaires passifs
Reimplemented from Equation_base.
Definition at line 66 of file Convection_Diffusion_Concentration.cpp.
{
  assert(la_concentration.non_nul());
  Convection_Diffusion_std::readOn(is);
  if (terme_convectif.op_non_nul())
    {
      Nom nom="Convection_";
      nom+=inconnue().le_nom(); //!< On ajoute le nom de l'inconnue pour prevoir une equation de scalaires passifs
      terme_convectif.set_fichier(nom);
      terme_convectif.set_description((Nom)"Convective mass transfer rate=Integral(-C*u*ndS)[m"+(Nom)(dimension+bidim_axi)+".Mol.s-1]");
    }
  else
    {
      EChaine ech("{ negligeable }");
      ech >> terme_convectif;
    }
  if (terme_diffusif.op_non_nul())
    {
      Nom nom="Diffusion_";
      nom+=inconnue().le_nom();
      terme_diffusif.set_fichier(nom);
      terme_diffusif.set_description((Nom)"Diffusion mass transfer rate=Integral(alpha*grad(C)*ndS) [m"+(Nom)(dimension+bidim_axi)+".Mol.s-1]");
    }
  else
    {
      EChaine ech("{ negligeable }");
      ech >> terme_diffusif;
    }
  return is;
}
References Objet_U::bidim_axi, Objet_U::dimension, inconnue(), la_concentration, O_U_Ptr::le_nom(), O_U_Ptr::non_nul(), Operateur_Conv::op_non_nul(), Operateur_Diff::op_non_nul(), Convection_Diffusion_std::readOn(), Operateur::set_description(), Operateur::set_fichier(), Convection_Diffusion_std::terme_convectif, and Convection_Diffusion_std::terme_diffusif.
self_cast() [1/2]
const Convection_Diffusion_Concentration & Convection_Diffusion_Concentration::self_cast (const Objet_U & r) static
Definition at line 25 of file Convection_Diffusion_Concentration.cpp.
self_cast() [2/2]
Convection_Diffusion_Concentration & Convection_Diffusion_Concentration::self_cast (Objet_U & r) static
Definition at line 25 of file Convection_Diffusion_Concentration.cpp.
set_param()
void Convection_Diffusion_Concentration::set_param (Param & titi) override virtual
Reimplemented from Equation_base.
Definition at line 105 of file Convection_Diffusion_Concentration.cpp.
{
  Convection_Diffusion_std::set_param(param);
  param.ajouter_non_std("nom_inconnue",(this));
  param.ajouter_non_std("alias",(this));
  param.ajouter("masse_molaire",&masse_molaire_);
}
References Param::ajouter(), Param::ajouter_non_std(), masse_molaire_, and Convection_Diffusion_std::set_param().
taille_memoire()
unsigned Convection_Diffusion_Concentration::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file Convection_Diffusion_Concentration.cpp.
Member Data Documentation
info_obj
const Type_info Convection_Diffusion_Concentration::info_obj static
Definition at line 35 of file Convection_Diffusion_Concentration.h.
la_concentration
Champ_Inc Convection_Diffusion_Concentration::la_concentration protected
Definition at line 62 of file Convection_Diffusion_Concentration.h.
Referenced by discretiser(), inconnue(), and readOn().
le_constituant
Ref_Constituant Convection_Diffusion_Concentration::le_constituant protected
Definition at line 63 of file Convection_Diffusion_Concentration.h.
Referenced by associer_constituant(), and constituant().
masse_molaire_
double Convection_Diffusion_Concentration::masse_molaire_ protected
Definition at line 64 of file Convection_Diffusion_Concentration.h.
Referenced by masse_molaire(), and set_param().
nb_constituants_
int Convection_Diffusion_Concentration::nb_constituants_ protected
Definition at line 61 of file Convection_Diffusion_Concentration.h.
Referenced by discretiser(), and nb_constituants().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Equations/Convection_Diffusion_Concentration.h
src/ThHyd/Incompressible/Equations/Convection_Diffusion_Concentration.cpp