TRUST: Eval_Puiss_Th_PolyMAC_Elem Class Reference
Eval_Puiss_Th_PolyMAC_Elem Class Reference
#include <Eval_Puiss_Th_PolyMAC_Elem.h>
Public Member Functions
void associer_champs (const Champ_Don &)
void mettre_a_jour () override
double calculer_terme_source (int) const override
void calculer_terme_source (int, DoubleVect &) const override
Public Member Functions inherited from Evaluateur_Source_PolyMAC_Elem
Evaluateur_Source_PolyMAC_Elem ()
Evaluateur_Source_PolyMAC_Elem (const Evaluateur_Source_PolyMAC_Elem &)
void completer () override
Public Member Functions inherited from Evaluateur_Source_PolyMAC
Evaluateur_Source_PolyMAC ()
virtual ~Evaluateur_Source_PolyMAC ()
Evaluateur_Source_PolyMAC (const Evaluateur_Source_PolyMAC &)
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
virtual double calculer_terme_source (int) const =0
virtual void calculer_terme_source (int, DoubleVect &) const =0
Protected Attributes
Ref_Champ_Don la_puissance
DoubleTab puissance
Protected Attributes inherited from Evaluateur_Source_PolyMAC_Elem
DoubleVect volumes
DoubleVect porosite_vol
porosites volumiques
Protected Attributes inherited from Evaluateur_Source_PolyMAC
Ref_Zone_PolyMAC la_zone
Ref_Zone_Cl_PolyMAC la_zcl
Detailed Description
Definition at line 32 of file Eval_Puiss_Th_PolyMAC_Elem.h.
Member Function Documentation
associer_champs()
void Eval_Puiss_Th_PolyMAC_Elem::associer_champs (const Champ_Don & Q)
Definition at line 18 of file Eval_Puiss_Th_PolyMAC_Elem.cpp.
{
  la_puissance = Q;
  puissance.ref(Q.valeurs());
}
References la_puissance, puissance, TRUSTTab< _TYPE_ >::ref(), and Champ_Don::valeurs().
Referenced by Terme_Puissance_Thermique_PolyMAC_Elem::associer_pb().
calculer_terme_source() [1/2]
double Eval_Puiss_Th_PolyMAC_Elem::calculer_terme_source (int num_elem) const inline override virtual
Implements Evaluateur_Source_PolyMAC.
Definition at line 54 of file Eval_Puiss_Th_PolyMAC_Elem.h.
{
  if (sub_type(Champ_Uniforme,la_puissance.valeur().valeur()))
    return puissance(0,0)*volumes(num_elem)*porosite_vol(num_elem);
  else
    {
      if (puissance.nb_dim()==1)
        return puissance(num_elem)*volumes(num_elem)*porosite_vol(num_elem);
      else
        return puissance(num_elem,0)*volumes(num_elem)*porosite_vol(num_elem);
    }
}
References la_puissance, TRUSTTab< _TYPE_ >::nb_dim(), Evaluateur_Source_PolyMAC_Elem::porosite_vol, puissance, sub_type, Deriv_Champ_Don_base::valeur(), Ref_Champ_Don::valeur(), and Evaluateur_Source_PolyMAC_Elem::volumes.
calculer_terme_source() [2/2]
void Eval_Puiss_Th_PolyMAC_Elem::calculer_terme_source (int e, DoubleVect & S) const inline override virtual
Implements Evaluateur_Source_PolyMAC.
Definition at line 67 of file Eval_Puiss_Th_PolyMAC_Elem.h.
{
  const int N = S.size(), pc = sub_type(Champ_Uniforme,la_puissance.valeur().valeur());
  for (int n = 0; n < N; n++) S[n] = puissance(!pc * e, n) * volumes(e) * porosite_vol(e);
}
References la_puissance, Evaluateur_Source_PolyMAC_Elem::porosite_vol, puissance, TRUSTVect< _TYPE_ >::size(), sub_type, Deriv_Champ_Don_base::valeur(), Ref_Champ_Don::valeur(), and Evaluateur_Source_PolyMAC_Elem::volumes.
mettre_a_jour()
void Eval_Puiss_Th_PolyMAC_Elem::mettre_a_jour () override virtual
Implements Evaluateur_Source_PolyMAC.
Definition at line 24 of file Eval_Puiss_Th_PolyMAC_Elem.cpp.
{
  /* int n = puissance.size();
     double pt=0.;
     for (int i =0;i<n;i++)
     {
     pt += puissance(i,0)*volumes(i);
     }
     Cout << "puissa tot "  << pt << finl;*/
}
Member Data Documentation
la_puissance
Ref_Champ_Don Eval_Puiss_Th_PolyMAC_Elem::la_puissance protected
Definition at line 44 of file Eval_Puiss_Th_PolyMAC_Elem.h.
Referenced by associer_champs(), and calculer_terme_source().
puissance
DoubleTab Eval_Puiss_Th_PolyMAC_Elem::puissance protected
Definition at line 45 of file Eval_Puiss_Th_PolyMAC_Elem.h.
Referenced by associer_champs(), and calculer_terme_source().
The documentation for this class was generated from the following files:
src/PolyMAC/Sources/Eval_Puiss_Th_PolyMAC_Elem.h
src/PolyMAC/Sources/Eval_Puiss_Th_PolyMAC_Elem.cpp