TRUST: Terme_Source_inc_th Class Reference
Terme_Source_inc_th Class Reference
#include <Terme_Source_inc_th.h>
Public Member Functions
void associer_eqn (const Navier_Stokes_std &)
void associer_eqn (const Convection_Diffusion_Temperature &)
const Navier_Stokes_std & eq_hydraulique () const
const Convection_Diffusion_Temperature & eq_thermique () const
void mettre_a_jour (double temps)
Protected Member Functions
Entree & lire_donnees (Entree &)
Protected Attributes
Ref_Navier_Stokes_std eq_hydraulique_
Ref_Convection_Diffusion_Temperature eq_thermique_
Ref_Champ_Don beta_t_
int impr
Detailed Description
Definition at line 27 of file Terme_Source_inc_th.h.
Member Function Documentation
associer_eqn() [1/2]
void Terme_Source_inc_th::associer_eqn (const Convection_Diffusion_Temperature & eq_thm)
Definition at line 25 of file Terme_Source_inc_th.cpp.
{
  eq_thermique_ = eq_thm;
}
References eq_thermique_.
associer_eqn() [2/2]
void Terme_Source_inc_th::associer_eqn (const Navier_Stokes_std & eq_hyd)
Definition at line 20 of file Terme_Source_inc_th.cpp.
{
  eq_hydraulique_ = eq_hyd;
}
References eq_hydraulique_.
Referenced by Terme_Source_inc_th_VDF_Face::associer_pb().
eq_hydraulique()
const Navier_Stokes_std & Terme_Source_inc_th::eq_hydraulique () const inline
Definition at line 51 of file Terme_Source_inc_th.h.
{
  return eq_hydraulique_.valeur();
}
References eq_hydraulique_, and Ref_Navier_Stokes_std::valeur().
Referenced by Terme_Source_inc_th_VDF_Face::ajouter_blocs().
eq_thermique()
const Convection_Diffusion_Temperature & Terme_Source_inc_th::eq_thermique () const inline
Definition at line 56 of file Terme_Source_inc_th.h.
{
  return eq_thermique_.valeur();
}
References eq_thermique_, and Ref_Convection_Diffusion_Temperature::valeur().
Referenced by Terme_Source_inc_th_VDF_Face::ajouter_blocs(), and Terme_Source_inc_th_VDF_Face::associer_pb().
lire_donnees()
Entree & Terme_Source_inc_th::lire_donnees (Entree & is) protected
Definition at line 31 of file Terme_Source_inc_th.cpp.
{
  Cerr << "Source_inc_th::lire_donnees" << finl;
// Initialisation
// u_etoile = 1.;
// h = 1.;
// coeff = 1;
// dir_source = 1;
  impr = 0;
// Fin Init
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{", mot="impr";
  is >> motlu;
  if(motlu != accolade_ouverte)
    {
      Cerr << "On attendait { a la place de " << motlu
           << " lors de la lecture de inc " << finl;
    }
  is >> motlu;
  while (motlu != accolade_fermee)
    {
      if (motlu==mot)
        {
          impr = 1;
          is >> motlu;
        }
      else
        {
          Cerr << "Le mot lu : " <<  motlu << " n'est pas compris dans Source_inc_th" << finl;
          Cerr << "Le mot compris est :  impr " << finl;
          Process::exit();
        }
    }
  return is;
}
References Cerr, Process::exit(), finl, and impr.
Referenced by Terme_Source_inc_th_VDF_Face::readOn().
mettre_a_jour()
void Terme_Source_inc_th::mettre_a_jour (double temps) inline
Definition at line 35 of file Terme_Source_inc_th.h.
  {
    ;
  }
Referenced by Terme_Source_inc_th_VDF_Face::mettre_a_jour().
Member Data Documentation
beta_t_
Ref_Champ_Don Terme_Source_inc_th::beta_t_ protected
Definition at line 43 of file Terme_Source_inc_th.h.
Referenced by Terme_Source_inc_th_VDF_Face::associer_pb(), and Terme_Source_inc_th_VDF_Face::beta().
eq_hydraulique_
Ref_Navier_Stokes_std Terme_Source_inc_th::eq_hydraulique_ protected
Definition at line 41 of file Terme_Source_inc_th.h.
Referenced by associer_eqn(), and eq_hydraulique().
eq_thermique_
Ref_Convection_Diffusion_Temperature Terme_Source_inc_th::eq_thermique_ protected
Definition at line 42 of file Terme_Source_inc_th.h.
Referenced by associer_eqn(), and eq_thermique().
impr
int Terme_Source_inc_th::impr protected
Definition at line 46 of file Terme_Source_inc_th.h.
Referenced by lire_donnees().
The documentation for this class was generated from the following files:
src/VDF/Sources/Terme_Source_inc_th.h
src/VDF/Sources/Terme_Source_inc_th.cpp