TRUST: QDM_Multiphase Class Reference
QDM_Multiphase Class Reference
classe QDM_Multiphase
Cette classe porte les termes de l'equation de la dynamique
pour un fluide sans modelisation de la turbulence.
On suppose l'hypothese de fluide quasi compressible.
Sous ces hypotheses, on utilise la forme suivante des equations de
Navier_Stokes:
DU/dt = div(terme visqueux) - gradP/rho + sources/rho
div U = W
avec DU/dt : derivee particulaire de la vitesse
rho : masse volumique
Rq : l'implementation de la classe permet bien sur de negliger
certains termes de l'equation (le terme visqueux, le terme
convectif, tel ou tel terme source).
L'inconnue est le champ de vitesse.
#include <QDM_Multiphase.h>
Public Member Functions
QDM_Multiphase ()
~QDM_Multiphase ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void completer () override
Complete l'equation base,
associe la pression a l'equation,
complete la divergence, le gradient et le solveur pression.
Ajout de 2 termes sources: l'un representant la force centrifuge
dans le cas axi-symetrique,l'autre intervenant dans la resolution
en 2D axisymetrique.
void discretiser_vitesse () override
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps de l'equation.
Appelle Equation_base::mettre_a_jour(double)
et met a jour la pression.
Integration des points suivis si le fluide est marque
Mise a jour du champ postraitable correspondant.
int impr (Sortie &os) const override
Effectue quelques impressions sur un flot de sortie:
- maximum de div U
- terme convectif
- terme diffusif
- divergence
- gradient.
bool initTimeStep (double dt) override
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
void abortTimeStep () override
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
void dimensionner_matrice_sans_mem (Matrice_Morse &matrice) override
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
const Champ_Don & diffusivite_pour_transport () const override
const Champ_base & diffusivite_pour_pas_de_temps () const override
const Champ_base & vitesse_pour_transport () const override
void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) override
void creer_champ (const Motcle &motlu) override
void update_y_plus (const DoubleTab &tab)
Public Member Functions inherited from Navier_Stokes_std
~Navier_Stokes_std ()
< For Immersed Boundary Method (IBM)
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Navier_Stokes_std ()
void set_param (Param &titi) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void associer_pb_base (const Probleme_base &) override
S'associe au probleme:
apelle Equation_base::associer_pb_base(const Probleme_base&)
s'associe avec les operateurs de divergence et de gradient.
void associer_fluide (const Fluide_base &)
Associe un fluide incompressible a l'equation.
const Milieu_base & milieu () const override
Renvoie le milieu physique de l'equation<br>(le Fluide_base upcaste en Milieu_base)
Milieu_base & milieu () override
Renvoie le milieu physique de l'equation<br>(le Fluide_base upcaste en Milieu_base)
(version const)
const Fluide_base & fluide () const
Renvoie le fluide incompressible (milieu physique de l'equation)
associe a l'equation.
(version const)
Fluide_base & fluide ()
Renvoie le fluide incompressible (milieu physique de l'equation)
associe a l'equation.
void associer_milieu_base (const Milieu_base &) override
Associe un mileu physique a l'equation en construisant
dynamiquement (cast) un objet de type Fluide_base
a partir de l'objet Milieu_base passe en parametre.
int nombre_d_operateurs () const override
Renvoie le nombre d'operateurs de l'equation:
Pour Navier Stokes Standard c'est 2.
int nombre_d_operateurs_tot () const override
const Operateur & operateur (int) const override
Renvoie le i-eme operateur de l'equation:
- le terme_diffusif si i = 0
- le terme_convectif si i = 1
exit si i>1
(version const)
Operateur & operateur (int) override
Renvoie le i-eme operateur de l'equation:
- le terme_diffusif si i = 0
- le terme_convectif si i = 1
exit si i>1.
const Operateur & operateur_fonctionnel (int) const override
Operateur & operateur_fonctionnel (int) override
Operateur_Div & operateur_divergence ()
Renvoie l'operateur de calcul de la divergence
associe a l'equation.
const Operateur_Div & operateur_divergence () const
Renvoie l'operateur de calcul de la divergence
associe a l'equation.
(version const)
Operateur_Grad & operateur_gradient ()
Renvoie l'operateur de calcul du gradient
associe a l'equation.
const Operateur_Grad & operateur_gradient () const
Renvoie l'operateur de calcul du gradient
associe a l'equation.
(version const)
const Champ_Inc & inconnue () const override
Renvoie la vitesse (champ inconnue de l'equation)
(version const)
Champ_Inc & inconnue () override
Renvoie la vitesse (champ inconnue de l'equation)
SolveurSys & solveur_pression ()
Renvoie le solveur en pression<br>(version const)
void discretiser () override
Dicretise l'equation.
virtual void discretiser_vitesse ()
void completer () override
Complete l'equation base,
associe la pression a l'equation,
complete la divergence, le gradient et le solveur pression.
Ajout de 2 termes sources: l'un representant la force centrifuge
dans le cas axi-symetrique,l'autre intervenant dans la resolution
en 2D axisymetrique
Association d une equation de transport d interface a l ensemble
de points suivis si le fluide est marque.
Entree & lire_cond_init (Entree &) override
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
bool initTimeStep (double dt) override
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps de l'equation.
Appelle Equation_base::mettre_a_jour(double)
et met a jour la pression.
Integration des points suivis si le fluide est marque
Mise a jour du champ postraitable correspondant.
void abortTimeStep () override
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
int impr (Sortie &os) const override
Effectue quelques impressions sur un flot de sortie:
- maximum de div U
- terme convectif
- terme diffusif
- divergence
- gradient.
void dimensionner_matrice_sans_mem (Matrice_Morse &matrice) override
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void assembler_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
int sauvegarder (Sortie &) const override
Appelle Equation_base::sauvegarder(Sortie&)
et sauvegarde la pression sur un flot de sortie.
int reprendre (Entree &) override
Effectue une reprise a partir d'un flot d'entree.
Appelle Equation_base::reprendre()
et reprend la pression.
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
DoubleTab & corriger_derivee_expl (DoubleTab &) override
Add a specific term for Navier Stokes (-gradP(n)) if necessary.
DoubleTab & corriger_derivee_impl (DoubleTab &) override
Resolution de la pression, inconnue implicitee de Navier Stokes.
int preparer_calcul () override
cf Equation_base::preparer_calcul()
Assemblage du solveur pression et
initialisation de la pression.
Matrice & matrice_pression ()
Assembleur & assembleur_pression ()
Champ_Inc & pression ()
Renvoie le champ de pression.
Champ_Inc & grad_P ()
Renvoie le gradient de pression<br>(version const)
const Champ_Inc & grad_P () const
Champ_Inc & pression_pa ()
Champ_Inc & div ()
const Champ_Inc & pression () const
Renvoie le champ de pression.
const Champ_Inc & pression_pa () const
const Champ_Inc & div () const
virtual const Champ_Don & diffusivite_pour_transport () const
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
virtual const Champ_base & vitesse_pour_transport () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
const Motcle & domaine_application () const override
Renvoie le nom du domaine d'application: "Hydraulique".
virtual const Champ_Inc & vitesse () const
virtual Champ_Inc & vitesse ()
virtual void projeter ()
Calcule la solution U des equations:
| M(U-V)/dt + BtP = 0
|-BU=0
On resoud le probleme en pression: -BM-1BtP = -BV/dt
sachant que -BV represente le calcul de la divergence de V
On resoud le probleme en vitesse en appliquant le solveur
de masse au gradient de P: U=V - dt*M-1BtP.
virtual int projection_a_faire ()
virtual void sauver () const
virtual void calculer_la_pression_en_pa ()
Calcul de "la_pression_en_pa" en fonction de "la_pression".
Si le champ milieu().masse_volumique() est uniforme, on suppose que
la_pression est P* = P/rho, et on multiplie par rho. Sinon,
la_pression est deja en Pa.
Cette methode est surchargee en front-tracking.
virtual void calculer_pression_hydrostatique (Champ_base &pression_hydro) const
int verif_Cl () const override
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
virtual const Champ_Inc & rho_la_vitesse () const
Operateur_Conv & get_terme_convectif ()
virtual void renewing_jacobians (DoubleTab &derivee)
virtual void div_ale_derivative (DoubleTrav &derivee_ale, double timestep, DoubleTab &derivee, DoubleTrav &secmemP)
virtual void update_pressure_matrix (void)
const int & get_matrice_pression_penalisee_H1 () const
const int & get_correction_matrice_pression () const
const int & get_correction_vitesse_modifie () const
const int & get_correction_pression_modifie () const
const int & get_gradient_pression_qdm_modifie () const
const int & get_i_source_pdf () const
const DoubleTab & get_champ_coeff_pdf_som () const
const int & get_correction_vitesse_projection_initiale () const
const int & get_correction_calcul_pression_initiale () const
const int & get_correction_matrice_projection_initiale () const
Public Member Functions inherited from Equation_base
Equation_base ()
~Equation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Methode appelee lorsqu'on cree l'instance de l'objet dans
le jeu de donnees (Interprete::ajouter)
virtual void avancer (int i=1)
virtual void reculer (int i=1)
virtual int nombre_d_operateurs () const =0
virtual int nombre_d_operateurs_tot () const
virtual const Operateur & operateur (int) const =0
virtual Operateur & operateur (int)=0
virtual const Operateur & operateur_fonctionnel (int) const
virtual Operateur & operateur_fonctionnel (int)
virtual const Champ_Inc & inconnue () const =0
virtual Champ_Inc & inconnue ()=0
virtual void associer_milieu_base (const Milieu_base &)=0
virtual const Milieu_base & milieu () const =0
virtual Milieu_base & milieu ()=0
int sauvegarder (Sortie &) const override
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
int reprendre (Entree &) override
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
int limpr () const
Demande au schema en temps si il faut effectuer une impression.
Renvoie 1 si il faut effectuer une impression.
Appel simple a Schema_Temps_base::limpr()
virtual void imprimer (Sortie &os) const
Imprime les operateurs de l'equation si le schema en temps
indique que c'est necessaire.
[SI limpr() ALORS impr(os)].
virtual int impr (Sortie &os) const
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
virtual void associer_milieu_equation ()
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
virtual DoubleTab & derivee_en_temps_inco_transport (DoubleTab &derivee)
virtual DoubleTab & corriger_derivee_expl (DoubleTab &)
virtual DoubleTab & corriger_derivee_impl (DoubleTab &)
virtual void mettre_a_jour (double temps)
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
virtual void abortTimeStep ()
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
virtual void valider_iteration ()
virtual int preparer_calcul ()
Tout ce qui ne depend pas des autres problemes eventuels.
virtual bool initTimeStep (double dt)
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
virtual bool updateGivenFields ()
virtual void discretiser ()
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
virtual void associer_pb_base (const Probleme_base &)
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur
de masse a l'equation.
virtual void completer ()
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
virtual double calculer_pas_de_temps () const
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des
pas de temps calcules par les operateurs.
Ces pas de temps sont ceux pour le schema d'Euler explicite.
Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule.
void calculer_pas_de_temps_locaux (DoubleTab &) const
Sources & sources ()
Renvoie les termes sources asssocies a l'equation.
const Sources & sources () const
Renvoie les termes sources asssocies a l'equation<br>(version const)
Solveur_Masse & solv_masse ()
Renvoie le solveur de masse associe a l'equation.
const Solveur_Masse & solv_masse () const
Renvoie le solveur de masse associe a l'equation.
(version const)
Probleme_base & probleme ()
Renvoie le probleme associe a l'equation.
const Probleme_base & probleme () const
Renvoie le probleme associe a l'equation.
(version const)
Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe a l'equation.
const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe a l'equation.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
S'associe au schema_en_temps.
virtual void associer_zone_dis (const Zone_dis &)
Associe la zone discretisee a l'equation.
const Discretisation_base & discretisation () const
Renvoie la discretisation associee a l'equation.
virtual Zone_Cl_dis & zone_Cl_dis ()
Renvoie la zone des conditions aux limite discretisee
associee a l'equation.
virtual const Zone_Cl_dis & zone_Cl_dis () const
Renvoie la zone des conditions aux limite discretisee
associee a l'equation<br>(version const)
Zone_dis & zone_dis ()
Renvoie la zone discretisee associee a l'equation.
const Zone_dis & zone_dis () const
Renvoie la zone discretisee associee a l'equation.
(version const)
const Nom & le_nom () const override
Renvoie le nom de l'equation.
DoubleVect & get_residu ()
DoubleVect & residu_initial ()
void initialise_residu (int=0)
virtual void imprime_residu (SFichier &)
virtual Nom expression_residu ()
virtual void dimensionner_matrice (Matrice_Morse &mat_morse)
virtual void dimensionner_matrice_sans_mem (Matrice_Morse &mat_morse)
virtual void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void modifier_pour_Cl (Matrice_Morse &mat_morse, DoubleTab &secmem) const
virtual void assembler_avec_inertie (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void dimensionner_termes_croises (Matrice_Morse &matrice, const Probleme_base &autre_pb, int nl, int nc)
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void assembler_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={})
Champ_Inc_base & champ_conserve () const
int has_champ_conserve () const
void init_champ_conserve () const
virtual std::pair< std::string, fonc_calc_t > get_fonc_champ_conserve () const
virtual Champ_Inc_base & champ_convecte () const
virtual int has_champ_convecte () const
virtual void init_champ_convecte () const
virtual void mettre_a_jour_champs_conserves (double temps, int reset=0)
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Motcle & domaine_application () const
Renvoie "indetermine"
Navier_Stokes_standard par exemple surcharge cette methode
pour renvoyer "Hydraulique".
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Verification du nombre de composantes lues pour la specification d un champ.
Actuellement utilise pour la lecture d un condition initiale ou limite.
virtual void verifie_ch_init_nb_comp_cl (const Champ_Inc_base &ch_ref, const int nb_comp, const Cond_lim_base &cl) const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
Add convection term
In: solution is the unknown I
Out: secmem is increased by convection(I)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution, const DoubleTab &terme_mul)
Parametre_equation & parametre_equation ()
const Parametre_equation & parametre_equation () const
virtual const Ref_Objet_U & get_modele (Type_modele type) const
virtual int equation_non_resolue () const
int disable_equation_residual () const
virtual const Champ_Inc & derivee_en_temps () const
virtual Champ_Inc & derivee_en_temps ()
void set_calculate_time_derivative (int i)
int calculate_time_derivative () const
void set_residuals (DoubleTab r)
virtual int positive_unkown ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static QDM_Multiphase & self_cast (Objet_U &)
static const QDM_Multiphase & self_cast (const Objet_U &)
Static Public Member Functions inherited from Navier_Stokes_std
static Objet_U * cree_instance ()
static const Type_info * info ()
static Navier_Stokes_std & self_cast (Objet_U &)
static const Navier_Stokes_std & self_cast (const Objet_U &)
Static Public Member Functions inherited from Equation_base
static const Type_info * info ()
static Equation_base & self_cast (Objet_U &)
static const Equation_base & self_cast (const Objet_U &)
static void calculer_champ_conserve (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Navier_Stokes_std
static const Type_info info_obj
Static Public Attributes inherited from Equation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Equation_base::printOn(Sortie&)
Ecrit l'equation sur un flot de sortie.
Entree & readOn (Entree &) override
Appel Equation_base::readOn(Entree& is)
En sortie verifie que l'on a bien lu:
- le terme diffusif,
- le terme convectif,
- le solveur en pression.
Entree & lire_cond_init (Entree &) override
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
int preparer_calcul () override
cf Equation_base::preparer_calcul()
Assemblage du solveur pression et
initialisation de la pression.
Protected Member Functions inherited from Navier_Stokes_std
Sortie & printOn (Sortie &x) const override
Simple appel a: Equation_base::printOn(Sortie&)
Ecrit l'equation sur un flot de sortie.
Entree & readOn (Entree &) override
Appel Equation_base::readOn(Entree& is)
En sortie verifie que l'on a bien lu:
- le terme diffusif,
- le terme convectif,
- le solveur en pression.
virtual void discretiser_assembleur_pression ()
Typage de l'assembleur pression. Le nom de l'assembleur
utilise est construit comme :
Assembleur_P_xxx" ou "xxx" est le nom de la discretisation.
Cette methode est virtuelle et surchargee dans le front-tracking.
Elle est appelee par Navier_Stokes_std::discretiser()
void uzawa (const DoubleTab &, const Matrice_Base &, SolveurSys &, DoubleTab &, DoubleTab &)
Protected Member Functions inherited from Equation_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
virtual void set_param (Param &titi)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_sources (Entree &)
Lecture des termes sources dans un flot d'entree.
virtual Entree & lire_cond_init (Entree &)
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
virtual Entree & lire_cl (Entree &)
Lecture des conditions limites sur un flot d'entree.
voir Zone_Cl_dis_base::readOn.
virtual int verif_Cl () const
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
virtual void lire ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
std::vector< Champ_Inc > vit_phases_
Motcles noms_vit_phases_
std::vector< Champ_Fonc > grad_vit_phases_
Motcles noms_grad_vit_phases_
Operateur_Evanescence evanescence
Protected Attributes inherited from Navier_Stokes_std
Ref_Fluide_base le_fluide
Champ_Inc la_vitesse
Champ_Inc la_pression
Champ_Inc divergence_U
Champ_Inc gradient_P
Champ_Inc la_pression_en_pa
Champ_Fonc la_vorticite
Champ_Fonc grad_u
Champ_Fonc critere_Q
Champ_Fonc pression_hydrostatique_
Champ_Fonc porosite_volumique
Champ_Fonc combinaison_champ
Champ_Fonc distance_paroi_globale
Champ_Fonc y_plus
Champ_Fonc Reynolds_maille
Champ_Fonc Courant_maille
Champ_Fonc Taux_cisaillement
Operateur_Conv terme_convectif
Operateur_Diff terme_diffusif
Operateur_Div divergence
Operateur_Grad gradient
Matrice matrice_pression_
Assembleur assembleur_pression_
SolveurSys solveur_pression_
int projection_initiale
double dt_projection
double seuil_projection
double seuil_uzawa
double max_div_U
double seuil_divU
double raison_seuil_divU
double LocalFlowRateRelativeError_
double cumulative_
Traitement_particulier_NS le_traitement_particulier
Nom chaine_champ_combi
int methode_calcul_pression_initiale_
int div_u_nul_et_non_dsurdt_divu_
int postraiter_gradient_pression_sans_masse_
int correction_matrice_projection_initiale_
int correction_calcul_pression_initiale_
int correction_vitesse_projection_initiale_
int correction_matrice_pression_
int matrice_pression_penalisee_H1_
int correction_vitesse_modifie_
int correction_pression_modifie_
int gradient_pression_qdm_modifie_
int i_source_pdf_
DoubleTab champ_coeff_pdf_som_
Protected Attributes inherited from Equation_base
Nom nom_
Solveur_Masse solveur_masse
Sources les_sources
Ref_Schema_Temps_base le_schema_en_temps
Ref_Zone_dis la_zone_dis
Zone_Cl_dis la_zone_Cl_dis
Ref_Probleme_base mon_probleme
DoubleList dt_op_bak
int sys_invariant_
int implicite_
Parametre_equation parametre_equation_
Champ_Fonc volume_maille
List_RefObjU liste_modeles_
Champs_compris champs_compris_
Champs_Fonc list_champ_combi
Matrice_Morse matrice_stockee
int matrice_init
Champ_Inc champ_conserve_
Champ_Inc champ_convecte_
Detailed Description
classe QDM_Multiphase
Cette classe porte les termes de l'equation de la dynamique
pour un fluide sans modelisation de la turbulence.
On suppose l'hypothese de fluide quasi compressible.
Sous ces hypotheses, on utilise la forme suivante des equations de
Navier_Stokes:
DU/dt = div(terme visqueux) - gradP/rho + sources/rho
div U = W
avec DU/dt : derivee particulaire de la vitesse
rho : masse volumique
Rq : l'implementation de la classe permet bien sur de negliger
certains termes de l'equation (le terme visqueux, le terme
convectif, tel ou tel terme source).
L'inconnue est le champ de vitesse.
Definition at line 44 of file QDM_Multiphase.h.
Constructor & Destructor Documentation
QDM_Multiphase()
QDM_Multiphase::QDM_Multiphase ()
Definition at line 29 of file QDM_Multiphase.cpp.
~QDM_Multiphase()
QDM_Multiphase::~QDM_Multiphase ()
Definition at line 29 of file QDM_Multiphase.cpp.
Member Function Documentation
abortTimeStep()
void QDM_Multiphase::abortTimeStep () override virtual
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
Reimplemented from Navier_Stokes_std.
Definition at line 235 of file QDM_Multiphase.cpp.
{
  Equation_base::abortTimeStep();
}
References Equation_base::abortTimeStep().
assembler_blocs_avec_inertie()
void QDM_Multiphase::assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) override virtual
Reimplemented from Equation_base.
Definition at line 161 of file QDM_Multiphase.cpp.
{
  Navier_Stokes_std::assembler_blocs_avec_inertie(matrices, secmem, semi_impl);
  if (evanescence.non_nul()) evanescence.valeur().ajouter_blocs(matrices, secmem, semi_impl);
}
References Operateur_base::ajouter_blocs(), Equation_base::assembler_blocs_avec_inertie(), evanescence, O_U_Ptr::non_nul(), and Deriv_Operateur_Evanescence_base::valeur().
Referenced by SETS::iterer_NS().
completer()
void QDM_Multiphase::completer (void) override virtual
Complete l'equation base,
associe la pression a l'equation,
complete la divergence, le gradient et le solveur pression.
Ajout de 2 termes sources: l'un representant la force centrifuge
dans le cas axi-symetrique,l'autre intervenant dans la resolution
en 2D axisymetrique.
Reimplemented from Navier_Stokes_std.
Definition at line 280 of file QDM_Multiphase.cpp.
{
  Cerr<<" Navier_Stokes_std::completer_deb"<<finl;
  Navier_Stokes_std::completer();
  Cerr<<" Navier_Stokes_std::completer_fin"<<finl;
  Cerr<<"unknow field type  "<<inconnue()->que_suis_je()<<finl;
  Cerr<<"unknow field name  "<<inconnue()->le_nom()<<finl;
  Cerr<<"equation type "<<inconnue()->equation().que_suis_je()<<finl;
  /* liste des choses qui doivent etre compatibles avec le multiphase */
  std::vector<const MorEqn*> morceaux = { &solveur_masse.valeur(), &les_sources, &terme_convectif.valeur(), &terme_diffusif.valeur(), &gradient.valeur() };
  for (auto mor : morceaux) mor->check_multiphase_compatibility();
}
References Cerr, MorEqn::check_multiphase_compatibility(), Navier_Stokes_std::completer(), finl, Navier_Stokes_std::gradient, Navier_Stokes_std::inconnue(), O_U_Ptr::le_nom(), Equation_base::les_sources, Objet_U::que_suis_je(), Equation_base::solveur_masse, Navier_Stokes_std::terme_convectif, Navier_Stokes_std::terme_diffusif, Deriv_Solveur_Masse_base::valeur(), Deriv_Operateur_Conv_base::valeur(), Deriv_Operateur_Diff_base::valeur(), and Deriv_Operateur_Grad_base::valeur().
cree_instance()
Objet_U * QDM_Multiphase::cree_instance () static
Definition at line 29 of file QDM_Multiphase.cpp.
creer_champ()
void QDM_Multiphase::creer_champ (const Motcle & motlu) override virtual
< Pour lui donner le bon nom dans discretiser_champ ; consequence : la premiere coordonnee en sortie n'a pas le bon nom
Reimplemented from Navier_Stokes_std.
Definition at line 294 of file QDM_Multiphase.cpp.
{
  Navier_Stokes_std::creer_champ(motlu);
  if (Taux_cisaillement.non_nul())
    if (!grad_u.non_nul()) creer_champ("gradient_vitesse");
  if (la_vorticite.non_nul())
    if (!grad_u.non_nul()) creer_champ("gradient_vitesse");
  int i = noms_vit_phases_.rang(motlu);
  if (i >= 0 && !(vit_phases_[i].non_nul()))
    {
      discretisation().discretiser_champ("vitesse",zone_dis(), noms_vit_phases_[i], "m/s",dimension, 1, 0, vit_phases_[i]);
      champs_compris_.ajoute_champ(vit_phases_[i]);
    }
  i = noms_grad_vit_phases_.rang(motlu);
  if (i >= 0 && !(grad_vit_phases_[i].non_nul()))
    {
      int D = dimension ;
      Noms noms(D * D), unites(D * D);
      std::vector<Nom> composantsVitesse({Nom("dU"), Nom("dV"), Nom("dW")});
      std::vector<Nom> composantsDerivee({Nom("dx"), Nom("dy"), Nom("dz")});
      for (int dU = 0 ; dU< D ; dU++)
        for (int dX = 0 ; dX < D ; dX++)
          {
            noms[ D * dU + dX]=Nom(composantsVitesse[dU] + "/" + composantsDerivee[dX]);
            unites[ D * dU + dX] = Nom("m2/s");
          }
      noms[0] = noms_grad_vit_phases_[i]; //!< Pour lui donner le bon nom dans discretiser_champ ; consequence : la premiere coordonnee en sortie n'a pas le bon nom
      Motcle typeChamp = "champ_elem" ;
      discretisation().discretiser_champ(typeChamp, zone_dis(), multi_scalaire, noms , unites, D*D, 0, grad_vit_phases_[0]);
      champs_compris_.ajoute_champ(grad_vit_phases_[i]);
    }
}
References Champs_compris::ajoute_champ(), Equation_base::champs_compris_, Navier_Stokes_std::creer_champ(), creer_champ(), Objet_U::dimension, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), Navier_Stokes_std::grad_u, grad_vit_phases_, Navier_Stokes_std::la_vorticite, multi_scalaire, noms_grad_vit_phases_, noms_vit_phases_, O_U_Ptr::non_nul(), Motcles::rang(), Navier_Stokes_std::Taux_cisaillement, vit_phases_, and Equation_base::zone_dis().
Referenced by creer_champ().
diffusivite_pour_pas_de_temps()
const Champ_base & QDM_Multiphase::diffusivite_pour_pas_de_temps () const override virtual
Reimplemented from Navier_Stokes_std.
Definition at line 251 of file QDM_Multiphase.cpp.
{
  return le_fluide->viscosite_cinematique();
}
References Navier_Stokes_std::le_fluide, and Fluide_base::viscosite_cinematique().
diffusivite_pour_transport()
const Champ_Don & QDM_Multiphase::diffusivite_pour_transport () const override virtual
Reimplemented from Navier_Stokes_std.
Definition at line 246 of file QDM_Multiphase.cpp.
{
  return le_fluide->viscosite_dynamique();
}
References Navier_Stokes_std::le_fluide, and Fluide_base::viscosite_dynamique().
dimensionner_blocs()
void QDM_Multiphase::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Navier_Stokes_std.
Definition at line 155 of file QDM_Multiphase.cpp.
{
  Navier_Stokes_std::dimensionner_blocs(matrices, semi_impl);
  if (evanescence.non_nul()) evanescence.valeur().dimensionner_blocs(matrices, semi_impl);
}
References Operateur_base::dimensionner_blocs(), Navier_Stokes_std::dimensionner_blocs(), evanescence, O_U_Ptr::non_nul(), and Deriv_Operateur_Evanescence_base::valeur().
Referenced by SETS::iterer_NS().
dimensionner_matrice_sans_mem()
void QDM_Multiphase::dimensionner_matrice_sans_mem (Matrice_Morse & matrice) override virtual
Reimplemented from Navier_Stokes_std.
Definition at line 141 of file QDM_Multiphase.cpp.
{
  Navier_Stokes_std::dimensionner_matrice_sans_mem(matrice);
  if (evanescence.non_nul()) evanescence.valeur().dimensionner(matrice);
}
References Operateur_base::dimensionner(), Navier_Stokes_std::dimensionner_matrice_sans_mem(), evanescence, O_U_Ptr::non_nul(), and Deriv_Operateur_Evanescence_base::valeur().
discretiser_vitesse()
void QDM_Multiphase::discretiser_vitesse () override virtual
Reimplemented from Navier_Stokes_std.
Definition at line 240 of file QDM_Multiphase.cpp.
{
  const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
  dis.vitesse(schema_temps(), zone_dis(), la_vitesse, ref_cast(Pb_Multiphase, probleme()).nb_phases());
}
References Equation_base::discretisation(), Navier_Stokes_std::la_vitesse, Equation_base::probleme(), ref_cast, Equation_base::schema_temps(), Discret_Thyd::vitesse(), and Equation_base::zone_dis().
duplique()
int QDM_Multiphase::duplique () const override virtual
Reimplemented from Navier_Stokes_std.
Definition at line 29 of file QDM_Multiphase.cpp.
get_info()
const Type_info * QDM_Multiphase::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Navier_Stokes_std.
Definition at line 29 of file QDM_Multiphase.cpp.
has_interface_blocs()
int QDM_Multiphase::has_interface_blocs () const override virtual
Reimplemented from Navier_Stokes_std.
Definition at line 147 of file QDM_Multiphase.cpp.
{
  int ok = Navier_Stokes_std::has_interface_blocs();
  if (evanescence.non_nul()) ok &= evanescence.valeur().has_interface_blocs();
  return ok;
}
References evanescence, Operateur_base::has_interface_blocs(), Navier_Stokes_std::has_interface_blocs(), O_U_Ptr::non_nul(), and Deriv_Operateur_Evanescence_base::valeur().
impr()
int QDM_Multiphase::impr (Sortie & os) const inline override virtual
Effectue quelques impressions sur un flot de sortie:
- maximum de div U
- terme convectif
- terme diffusif
- divergence
- gradient.
Returns
int
Signification: renvoie toujours 1
Contraintes:
< max|sum(u.ndS)i/(vol(i)/dt)|=max|div(U)i/dt| Calculation as OpenFOAM: http://foam.sourceforge.net/docs/cpp/a04190_source.html It is relative errors (normalized by the volume/dt)
Reimplemented from Navier_Stokes_std.
Definition at line 55 of file QDM_Multiphase.h.
  {
    return Equation_base::impr(os); //idem
  }
References Equation_base::impr().
info()
const Type_info * QDM_Multiphase::info () static
Definition at line 29 of file QDM_Multiphase.cpp.
initTimeStep()
bool QDM_Multiphase::initTimeStep (double dt) override virtual
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
Returns
0 en cas d'erreur, 1 sinon
Signification:
Contraintes:
Reimplemented from Navier_Stokes_std.
Definition at line 218 of file QDM_Multiphase.cpp.
{
  Schema_Temps_base& sch=schema_temps();
  ConstDoubleTab_parts ppart(pression()->valeurs());
  /* si pression_pa() est plus petit que pression() (ex. : variables auxiliaires PolyMAC), alors on ne copie que la 1ere partie */
  const DoubleTab& p_red = pression_pa()->valeurs().dimension_tot(0) < pression()->valeurs().dimension_tot(0) ? ppart[0] : pression()->valeurs();
  for (int i=1; i<=sch.nb_valeurs_futures(); i++)
    {
// Mise a jour du temps dans la pression
      pression()->changer_temps_futur(sch.temps_futur(i),i);
      pression()->futur(i)=pression()->valeurs();
      pression_pa()->changer_temps_futur(sch.temps_futur(i),i);
      pression_pa()->futur(i) = p_red;
    }
  return Equation_base::initTimeStep(dt);
}
References TRUSTTab< _TYPE_ >::dimension_tot(), Champ_Inc::futur(), Equation_base::initTimeStep(), Schema_Temps_base::nb_valeurs_futures(), Navier_Stokes_std::pression(), Navier_Stokes_std::pression_pa(), Equation_base::schema_temps(), Schema_Temps_base::temps_futur(), and Champ_Inc::valeurs().
lire_cond_init()
Entree & QDM_Multiphase::lire_cond_init (Entree & is) override protected virtual
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Navier_Stokes_std.
Definition at line 327 of file QDM_Multiphase.cpp.
{
  Cerr << "Reading of initial conditions\n";
  Nom nom;
  is >> nom;
  if (nom != "{") Cerr << que_suis_je() << ": expected { instead of " << nom << finl, Process::exit();
  int vit_lu = 0, press_lu = 0;
  for (is >> nom; nom != "}"; is >> nom)
    if (nom == "vitesse" || nom == "velocity")
      {
        Champ_Don src;
        is >> src;
        verifie_ch_init_nb_comp(la_vitesse, src.nb_comp());
        la_vitesse->affecter(src), vit_lu = 1;
        la_vitesse->passe() = la_vitesse->valeurs();
      }
    else if (nom == "pression" || nom == "pressure")
      {
        Champ_Don src;
        is >> src, verifie_ch_init_nb_comp(la_pression, src.nb_comp());
        la_pression->affecter(src);
        la_pression_en_pa->passe() = la_pression_en_pa->valeurs() = la_pression->passe() = la_pression->valeurs();
        press_lu = 1;
      }
    else Cerr << que_suis_je() << ": expected vitesse|velocity|pression|pressure instead of " << nom << finl, Process::exit();
  if (!vit_lu)   Cerr << que_suis_je() << ": velocity initial condition not found." << finl, Process::exit();
  if (!press_lu) Cerr << que_suis_je() << ": pressure initial condition not found." << finl, Process::exit();
  return is;
}
References Cerr, Process::exit(), finl, Navier_Stokes_std::la_pression, Navier_Stokes_std::la_pression_en_pa, Navier_Stokes_std::la_vitesse, Champ_Don::nb_comp(), Champ_Inc::passe(), Objet_U::que_suis_je(), Champ_Inc::valeurs(), and Equation_base::verifie_ch_init_nb_comp().
lire_motcle_non_standard()
int QDM_Multiphase::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Navier_Stokes_std.
Definition at line 134 of file QDM_Multiphase.cpp.
{
  if (mot=="evanescence") is >> evanescence;
  else return Navier_Stokes_std::lire_motcle_non_standard(mot, is);
  return 1;
}
References evanescence, and Navier_Stokes_std::lire_motcle_non_standard().
mettre_a_jour()
void QDM_Multiphase::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de l'equation.
Appelle Equation_base::mettre_a_jour(double)
et met a jour la pression.
Integration des points suivis si le fluide est marque
Mise a jour du champ postraitable correspondant.
< Les lignes et les colonnes sont inversees quand on passe dans DoubleTab_parts
< array(i)=sum(u.ndS)
< array(i)=sum(u.ndS)/vol(i)
< =max|sum(u.ndS)/(vol(i)/dt)|
Reimplemented from Navier_Stokes_std.
Definition at line 167 of file QDM_Multiphase.cpp.
{
  Equation_base::mettre_a_jour(temps);  //on saute celui de Navier_Stokes_std
  pression().mettre_a_jour(temps);
  pression_pa().mettre_a_jour(temps);
  int i, j, n, N = ref_cast(Pb_Multiphase, probleme()).nb_phases(), d, D = dimension;
  for (n = 0; n < N; n++)
    if (vit_phases_[n].non_nul())
      {
        vit_phases_[n].mettre_a_jour(temps);
        DoubleTab_parts psrc(inconnue().valeurs()), pdst(vit_phases_[n].valeurs());
        for (i = 0; i < std::min(psrc.size(), pdst.size()); i++)
          {
            DoubleTab& src = psrc[i], &dst = pdst[i];
            if (src.line_size() == N) /* une colonne par composante */
              for (j = 0; j < src.dimension_tot(0); j++) dst(j) = src(j, n);
            else if (src.line_size() == N * D) /* stockage N * d + n */
              for (j = 0; j < src.dimension_tot(0); j++)
                for (d = 0; d < D; d++)
                  dst(j, d, 0) = src(j, d, n);
            else abort(); //on ne connait pas
          }
      }
  if (grad_u.non_nul()) grad_u.mettre_a_jour(temps);
  if (la_vorticite.non_nul()) la_vorticite.mettre_a_jour(temps);
  if (Taux_cisaillement.non_nul()) Taux_cisaillement.mettre_a_jour(temps);
  for (n = 0; n < N; n++)
    if (grad_vit_phases_[n].non_nul())
      {
        grad_vit_phases_[n].mettre_a_jour(temps);
        DoubleTab_parts psrc(grad_u->valeurs()), pdst(grad_vit_phases_[n].valeurs());
        int copied = 0;
        for (i = 0; i < psrc.size(); i++)
          for (j = 0; j < pdst.size(); j++)
            {
              DoubleTab& src = psrc[i], &dst = pdst[j];
              if (src.line_size() == N * D * D && dst.line_size() == D * D) /* une colonne par composante */
                {
                  for (int k = 0; k < src.dimension_tot(0); k++)
                    for (int dU = 0; dU < D; dU++)
                      for (int dX = 0; dX < D; dX++)
                        dst(k, dX + D * dU) = src(k, dX, dU + n * D);//!< Les lignes et les colonnes sont inversees quand on passe dans DoubleTab_parts
                  copied += 1;
                }
            }
        if (copied != 1) { Cerr << "Problem in filling the gradients by phase" << finl ; abort();} //on ne connait pas
      }
}
References Process::abort(), Cerr, Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), finl, Navier_Stokes_std::grad_u, grad_vit_phases_, Navier_Stokes_std::inconnue(), Navier_Stokes_std::la_vorticite, TRUSTVect< _TYPE_ >::line_size(), Champ_Inc::mettre_a_jour(), Equation_base::mettre_a_jour(), Champ_Fonc::mettre_a_jour(), O_U_Ptr::non_nul(), Navier_Stokes_std::pression(), Navier_Stokes_std::pression_pa(), Equation_base::probleme(), ref_cast, TRUSTTab_parts< _TYPE_ >::size(), Navier_Stokes_std::Taux_cisaillement, Champ_Fonc::valeurs(), and vit_phases_.
preparer_calcul()
int QDM_Multiphase::preparer_calcul (void) override protected virtual
cf Equation_base::preparer_calcul()
Assemblage du solveur pression et
initialisation de la pression.
Returns
int
Signification: renvoie toujours 1
Contraintes:
< on remet les bons flux bords
< on remet les bons flux bords pour div
Reimplemented from Navier_Stokes_std.
Definition at line 359 of file QDM_Multiphase.cpp.
{
  return Equation_base::preparer_calcul(); //pour eviter Navier_Stokes_std::preparer_calcul() !
}
References Equation_base::preparer_calcul().
printOn()
Sortie & QDM_Multiphase::printOn (Sortie & is) const override protected virtual
Simple appel a: Equation_base::printOn(Sortie&)
Ecrit l'equation sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Navier_Stokes_std.
Definition at line 57 of file QDM_Multiphase.cpp.
{
  return Equation_base::printOn(is);
}
References Equation_base::printOn().
readOn()
Entree & QDM_Multiphase::readOn (Entree & is) override protected virtual
Appel Equation_base::readOn(Entree& is)
En sortie verifie que l'on a bien lu:
- le terme diffusif,
- le terme convectif,
- le solveur en pression.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Navier_Stokes_std.
Definition at line 86 of file QDM_Multiphase.cpp.
{
  evanescence.associer_eqn(*this);
  Navier_Stokes_std::readOn(is);
  assert(le_fluide.non_nul());
  if (!sub_type(Fluide_base,le_fluide.valeur()))
    {
      Cerr<<"ERROR : the QDM_Multiphase equation can be associated only to a fluid."<<finl;
      exit();
    }
  divergence.set_description((Nom)"Mass flow rate=Integral(rho*u*ndS) [kg.s-1]");
  terme_convectif.valeur().set_incompressible(0);
  const Pb_Multiphase& pb = ref_cast(Pb_Multiphase, probleme());
  if (!evanescence.non_nul() && pb.nb_phases() > 1)
    {
// Special treatment for Pb_HEM
// We enforce the evanescence to a specific value
      if (sub_type(Pb_HEM, probleme()))
        {
          EChaine eva("{ homogene { alpha_res 1 alpha_res_min 0.5 } }");
          eva >> evanescence;
        }
      else
        {
          EChaine eva("{ homogene { alpha_res 1e-6 } }");
          eva >> evanescence;
        }
    }
  /* champs de vitesse par phase pour le postpro */
  noms_vit_phases_.dimensionner(pb.nb_phases()), vit_phases_.resize(pb.nb_phases());
  for (int i = 0; i < pb.nb_phases(); i++)
    champs_compris_.ajoute_nom_compris(noms_vit_phases_[i] = Nom("vitesse_") + pb.nom_phase(i));
  noms_grad_vit_phases_.dimensionner(pb.nb_phases()), grad_vit_phases_.resize(pb.nb_phases());
  for (int i = 0; i < pb.nb_phases(); i++)
    champs_compris_.ajoute_nom_compris(noms_grad_vit_phases_[i] = Nom("gradient_vitesse_") + pb.nom_phase(i));
  return is;
}
References Champs_compris::ajoute_nom_compris(), MorEqn::associer_eqn(), Cerr, Equation_base::champs_compris_, vect_impl::dimensionner(), Navier_Stokes_std::divergence, evanescence, Process::exit(), finl, grad_vit_phases_, Navier_Stokes_std::le_fluide, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), noms_grad_vit_phases_, noms_vit_phases_, O_U_Ptr::non_nul(), Equation_base::probleme(), Navier_Stokes_std::readOn(), ref_cast, Operateur::set_description(), Operateur_Conv_base::set_incompressible(), sub_type, Navier_Stokes_std::terme_convectif, Deriv_Operateur_Conv_base::valeur(), Ref_Fluide_base::valeur(), and vit_phases_.
self_cast() [1/2]
const QDM_Multiphase & QDM_Multiphase::self_cast (const Objet_U & r) static
Definition at line 29 of file QDM_Multiphase.cpp.
self_cast() [2/2]
QDM_Multiphase & QDM_Multiphase::self_cast (Objet_U & r) static
Definition at line 29 of file QDM_Multiphase.cpp.
set_param()
void QDM_Multiphase::set_param (Param & param) override virtual
Reimplemented from Navier_Stokes_std.
Definition at line 128 of file QDM_Multiphase.cpp.
{
  Navier_Stokes_std::set_param(param);
  param.ajouter_non_std("evanescence|vanishing",(this));
}
References Param::ajouter_non_std(), and Navier_Stokes_std::set_param().
taille_memoire()
unsigned QDM_Multiphase::taille_memoire () const override virtual
Reimplemented from Navier_Stokes_std.
Definition at line 29 of file QDM_Multiphase.cpp.
update_y_plus()
void QDM_Multiphase::update_y_plus (const DoubleTab & tab)
Definition at line 364 of file QDM_Multiphase.cpp.
{
  if (!y_plus.non_nul()) Process::exit(que_suis_je() + " : y_plus must be initialised so it can be updated") ;
  DoubleTab& tab_y_p = y_plus->valeurs();
  if (tab.nb_dim()==2)
    for (int i = 0 ; i < tab_y_p.dimension_tot(0) ; i++)
      for (int n = 0 ; n < tab_y_p.dimension_tot(1) ; n++) tab_y_p(i,n) = tab(i,n);
  if (tab.nb_dim()==3)
    for (int i = 0 ; i < tab_y_p.dimension_tot(0) ; i++)
      for (int n = 0 ; n < tab_y_p.dimension_tot(1) ; n++) tab_y_p(i,n) = tab(i,0,n);
}
References TRUSTTab< _TYPE_ >::dimension_tot(), Process::exit(), TRUSTTab< _TYPE_ >::nb_dim(), O_U_Ptr::non_nul(), Objet_U::que_suis_je(), Champ_Fonc::valeurs(), and Navier_Stokes_std::y_plus.
vitesse_pour_transport()
const Champ_base & QDM_Multiphase::vitesse_pour_transport () const override virtual
Reimplemented from Navier_Stokes_std.
Definition at line 256 of file QDM_Multiphase.cpp.
{
  return la_vitesse;
}
References Navier_Stokes_std::la_vitesse.
Member Data Documentation
evanescence
Operateur_Evanescence QDM_Multiphase::evanescence protected
Definition at line 88 of file QDM_Multiphase.h.
Referenced by assembler_blocs_avec_inertie(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), has_interface_blocs(), lire_motcle_non_standard(), and readOn().
grad_vit_phases_
std::vector<Champ_Fonc> QDM_Multiphase::grad_vit_phases_ protected
Definition at line 85 of file QDM_Multiphase.h.
Referenced by creer_champ(), mettre_a_jour(), and readOn().
info_obj
const Type_info QDM_Multiphase::info_obj static
Definition at line 46 of file QDM_Multiphase.h.
noms_grad_vit_phases_
Motcles QDM_Multiphase::noms_grad_vit_phases_ protected
Definition at line 86 of file QDM_Multiphase.h.
Referenced by creer_champ(), and readOn().
noms_vit_phases_
Motcles QDM_Multiphase::noms_vit_phases_ protected
Definition at line 83 of file QDM_Multiphase.h.
Referenced by creer_champ(), and readOn().
vit_phases_
std::vector<Champ_Inc> QDM_Multiphase::vit_phases_ protected
Definition at line 82 of file QDM_Multiphase.h.
Referenced by creer_champ(), mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Equations/QDM_Multiphase.h
src/ThHyd/Multiphase/Equations/QDM_Multiphase.cpp