TRUST: Nom Class Reference
Nom Class Reference
class Nom
Une chaine de caractere pour nommer les objets de TRUST NOM_H
#include <Nom.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Nom ()
construit "??"
Nom (int i)
Nom(485)="485".
Nom (const char *nom)
Construction d'un nom a partir d'une chaine de caracteres
La chaine est copiee.
Nom (const std::string &nom)
Nom (const Nom &)
Constructeur par copie d'un nom.
Nom (char c)
Construction d'un nom a partir d'un caractere.
Nom (double)
Construction d'un nom a partir d'un flottant
La chaine cree est la representation du nombre reel (sprintf)
Nom (double le_reel, const char *format)
Construction d'un nom a partir d'un flottant
La chaine cree est la representation du nombre reel (sprintf)
Le format du nombre represente par la chaine est donne par format.
~Nom () override
Destructeur.
operator const char * () const
Retourne un pointeur sur la chaine de caractere du nom.
Nom & majuscule ()
Transforme le nom en majuscules
Seules les lettres 'a'-'z' sont modifiees.
int est_egal_a (const Objet_U &) const override
Comparaison avec un Objet_U
l'Objet_U est caste en Nom pour la comparaison.
int longueur () const
Renvoie le nombre de caracteres de la chaine du Nom
y compris le caractere zero de fin de chaine.
Exemple : Nom("hello").longueur() == 6.
const Nom & le_nom () const override
Renvoie *this;.
Nom & operator= (const char *const)
Copie la chaine nom.
Modif BM pour que nom puisse pointer sur une sous-partie de nom_.
Nom & operator= (const Nom &)
Copie le Nom nom.
Nom operator+ (const Nom &) const
Concatenation avec un Nom.
Nom & operator+= (const Nom &x)
Concatenation avec un Nom.
Nom & operator+= (const char *)
Nom & operator+= (char x)
concatenation de chaine
Nom & suffix (const char *const)
Extraction de suffixe :
Nom x("azerty");
x.suffix("aze")
x contient "rty".
const Nom getSuffix (const char *const) const
Nom & prefix (const char *const)
const Nom getPrefix (const char *const) const
Nom nom_me (int, const char *prefix=0, int without_padding=0) const
Insere _prefix000n (n=me() ou nproc()) dans un nom de fichier (par ex:toto.titi) pour donner toto_prefix000n.titi.
Nom substr_old (const int, const int) const
Retourne un nom selon la commande usuelle substr
ATTENTION : deb = 1 => premier caractere de la chaine !!!
Nom basename () const
Retourne fichier si le nom est sous la forme /toto/titi/fichier.
virtual int find (const char *const n) const
virtual int debute_par (const char *const n) const
virtual int finit_par (const char *const n) const
int find (const std::string &n) const
int debute_par (const std::string &) const
int finit_par (const std::string &) const
bool contient (const Nom &nom)
const char * getChar () const
const std::string & getString () const
std::string & getString ()
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Nom & self_cast (Objet_U &)
static const Nom & self_cast (const Objet_U &)
static void sed_check_case_non_sensitive (int i)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un Nom sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un nom.
En cas d'echec, le nom vaut "??" a la sortie.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
std::string nom_
Static Protected Attributes
static int nb_noms =0
static int check_case_non_sensitive_ =1
pour descativer dans ==
Friends
int operator== (const Nom &, const char *const)
Comparaison d'un nom avec une chaine de caractere
Utilise strcmp.
int operator!= (const Nom &, const char *)
Comparaison d'un nom avec une chaine de caractere.
int operator== (const Nom &, const Nom &)
int operator!= (const Nom &, const Nom &)
int operator== (const char *const, const Nom &)
int operator!= (const char *const, const Nom &)
Detailed Description
class Nom
Une chaine de caractere pour nommer les objets de TRUST NOM_H
Definition at line 34 of file Nom.h.
Constructor & Destructor Documentation
Nom() [1/8]
Nom::Nom ()
construit "??"
Constructeur par defaut.
Cree la chaine "??".
Definition at line 89 of file Nom.cpp.
{
  nb_noms++;
  nom_ = "??";
}
References nb_noms, and nom_.
Referenced by getPrefix(), and getSuffix().
Nom() [2/8]
Nom::Nom (int i)
Nom(485)="485".
Construction d'un nom a partir d'un entier
La chaine cree est la representation de l'entier
Exemple : Nom(128) cree la chaine "128".
Definition at line 132 of file Nom.cpp.
{
  nb_noms++;
  nom_ = "";
// 20 caracteres suffisent pour stocker n'importe quel entier
  char chaine[22];
#ifdef INT_is_64_
  sprintf(chaine, "%ld", i);
#else
  sprintf(chaine, "%d", i);
#endif
  operator=(chaine);
}
References nb_noms, nom_, and operator=().
Nom() [3/8]
Nom::Nom (const char * nom)
Construction d'un nom a partir d'une chaine de caracteres
La chaine est copiee.
Definition at line 161 of file Nom.cpp.
                        : nom_(nom)
{
  nb_noms++;
}
References nb_noms.
Nom() [4/8]
Nom::Nom (const std::string & nom)
Definition at line 166 of file Nom.cpp.
                             : nom_(nom)
{
  nb_noms++;
}
References nb_noms.
Nom() [5/8]
Nom::Nom (const Nom & nom)
Constructeur par copie d'un nom.
Definition at line 186 of file Nom.cpp.
                       : Objet_U(nom), nom_(nom.nom_)
{
  nb_noms++;
}
References nb_noms.
Nom() [6/8]
Nom::Nom (char c)
Construction d'un nom a partir d'un caractere.
Definition at line 109 of file Nom.cpp.
{
  nb_noms++;
  nom_=c;
}
References nb_noms, and nom_.
Nom() [7/8]
Nom::Nom (double le_reel)
Construction d'un nom a partir d'un flottant
La chaine cree est la representation du nombre reel (sprintf)
Definition at line 206 of file Nom.cpp.
{
  nb_noms++;
  nom_ = "";
  char la_chaine[80];
  sprintf(la_chaine,"%f",le_reel);
  operator=(la_chaine);
}
References nb_noms, nom_, and operator=().
Nom() [8/8]
Nom::Nom (double le_reel, const char * format)
Construction d'un nom a partir d'un flottant
La chaine cree est la representation du nombre reel (sprintf)
Le format du nombre represente par la chaine est donne par format.
Definition at line 231 of file Nom.cpp.
{
  char la_chaine[80];
  sprintf(la_chaine,format,le_reel);
#ifdef MICROSOFT
// sous windows les chiffres s'ecrivent 1.0000e+000 (avec 3 chiffres pour les puissances)
// on retire le premier zero
  unsigned int length=strlen(la_chaine);
  if (la_chaine[length-5]=='e')
    {
      if (la_chaine[length-3]!='0') exit();
      for (unsigned int i=length-3; i<=length; i++)
        la_chaine[i]=la_chaine[i+1];
    }
#endif
  nom_ =  la_chaine;
// delete[] la_chaine;
  nb_noms++;
}
References Process::exit(), nb_noms, and nom_.
~Nom()
Nom::~Nom () override
Destructeur.
Definition at line 266 of file Nom.cpp.
{
  nb_noms--;
}
References nb_noms.
Member Function Documentation
basename()
Nom Nom::basename () const
Retourne fichier si le nom est sous la forme /toto/titi/fichier.
< slash or backslash
Definition at line 633 of file Nom.cpp.
{
  Nom dirname("");
  Nom the_basename(nom_);
  int iLength = nom_.size();
  for (int i=0; i<iLength; i++)
    {
      dirname+=nom_[i];
      if (nom_[i]=='/' || nom_[i]=='\\')    //!< slash or backslash
        {
          the_basename.suffix(dirname);
          dirname="";
        }
    }
  return the_basename;
}
References nom_, and suffix().
Referenced by latatoother::interpreter().
contient()
bool Nom::contient (const Nom & nom) inline
Definition at line 83 of file Nom.h.
  {
    std::size_t found = nom_.find(nom.nom_);
    return found!=std::string::npos;
  }
References nom_.
Referenced by RegroupeBord::regroupe_bord().
cree_instance()
Objet_U * Nom::cree_instance () static
Definition at line 23 of file Nom.cpp.
debute_par() [1/2]
int Nom::debute_par (const char *const n) const virtual
Reimplemented in Motcle.
Definition at line 434 of file Nom.cpp.
{
  return debute_par(std::string(n));
}
References debute_par().
Referenced by Op_Correlation::associer(), Op_Ecart_type::associer(), Op_Moyenne::associer(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Echange_global_impose::champ_exterieur(), Scalaire_impose_paroi::compatible_avec_discr(), Equation_base::completer(), Flux_interfacial_Ranz_Marshall::completer(), Champ_Generique_Extraction::completer(), Champ_Generique_Transformation::completer(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), debute_par(), Motcle::debute_par(), Op_Conv_Amont_VDF_Elem::dimensionner_blocs(), PolyMAC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), Postraiter_domaine::ecrire(), Iterateur_Source_EF_base::equation_divisee_par_rho(), Iterateur_Source_PolyMAC_base::equation_divisee_par_rho(), Iterateur_Source_VDF_base::equation_divisee_par_rho(), Iterateur_Source_VEF_base::equation_divisee_par_rho(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_refChamp::get_directive_pour_discr(), Echange_couplage_thermique::get_dRho_dCp(), Champ_Generique_refChamp::get_localisation(), Operateur_base::get_localisation_pour_post(), PolyMAC_discretisation::get_name_of_type_for(), Discretisation_base::get_name_of_type_for(), getSuffix(), Debog_Pb::goto_msg(), Postraitement::init(), Porosites::interpreter(), Phases::interpreter(), latatoother::interpreter(), Simple::iterer_eqn(), Piso::iterer_NS(), Terme_Puissance_Thermique::lire_donnees(), Mod_turb_hyd_base::lire_motcle_non_standard(), Perte_Charge_Singuliere::lire_surfaces(), Chimie::mettre_a_jour(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Format_Post_Lata::modify_file_basename(), T_It_VDF_Face< _TYPE_ >::multiply_by_rho_if_hydraulique(), Champ_Generique_Transformation::preparer_macro(), Champ_Don_lu::readOn(), Diametre_bulles_constant::readOn(), Frottement_interfacial_Sonnenburg::readOn(), Frottement_interfacial_Tomiyama::readOn(), Frottement_interfacial_Wallis::readOn(), Frottement_interfacial_Weber::readOn(), Masse_ajoutee_Coef_Constant::readOn(), Multiplicateur_diphasique_Friedel::readOn(), Multiplicateur_diphasique_homogene::readOn(), Multiplicateur_diphasique_Lottes_Flinn::readOn(), Multiplicateur_diphasique_Muhler_Steinhagen::readOn(), Portance_interfaciale_Tomiyama::readOn(), Aire_interfaciale::readOn(), Force_Tchen_PolyMAC_P0::readOn(), Portance_interfaciale_PolyMAC_P0::readOn(), VDF_discretisation::residu(), PolyMAC_discretisation::residu(), Champ_Generique_refChamp::set_ref_champ(), suffix(), Champ_Inc_base::valeur_aux_bords(), Champ_Face_PolyMAC::valeur_aux_elems(), and Champ_Post_Operateur_Eqn::verification_cas_compo().
debute_par() [2/2]
int Nom::debute_par (const std::string & ch) const
Definition at line 409 of file Nom.cpp.
{
  return (nom_.rfind(ch, 0) == 0);
}
References nom_.
duplique()
int Nom::duplique () const override virtual
Implements Objet_U.
Definition at line 23 of file Nom.cpp.
est_egal_a()
int Nom::est_egal_a (const Objet_U & x) const override virtual
Comparaison avec un Objet_U
l'Objet_U est caste en Nom pour la comparaison.
Returns
int
Signification: 1 si egalite
Contraintes:
Reimplemented from Objet_U.
Definition at line 504 of file Nom.cpp.
{
  if (!(sub_type(Nom, x))) return 0;
  return (*this == ref_cast( Nom, x));
}
References ref_cast, and sub_type.
find() [1/2]
int Nom::find (const char *const n) const virtual
Reimplemented in Motcle.
Definition at line 429 of file Nom.cpp.
{
  return find(std::string(n));
}
References find().
Referenced by Schema_Explicite_Multi_TimeStep_base::authorized_equation(), Schema_Implicite_Multi_TimeStep_base::authorized_equation(), find(), Motcle::find(), LecFicDiffuse_JDD::ouvrir(), and Deriv_::typer().
find() [2/2]
int Nom::find (const std::string & n) const
Definition at line 423 of file Nom.cpp.
{
  std::size_t x = nom_.find(n);
  return (x != std::string::npos) ? x : -1;
}
References nom_.
finit_par() [1/2]
int Nom::finit_par (const char *const n) const virtual
Reimplemented in Motcle.
Definition at line 439 of file Nom.cpp.
{
  return finit_par(std::string(n));
}
References finit_par().
Referenced by Milieu_composite::check_fluid_name(), check_ICEM_ascii_file(), ecrit(), finit_par(), Motcle::finit_par(), getPrefix(), Debog_Pb::goto_msg(), Postraitement::init(), latatoother::interpreter(), main_TRUST(), prefix(), and Diametre_bulles_constant::readOn().
finit_par() [2/2]
int Nom::finit_par (const std::string & s) const
Definition at line 414 of file Nom.cpp.
{
  auto l = nom_.size(), e = s.size();
  if (l >= e)
    return (0 == nom_.compare(l - e, e, s));
  else
    return 0;
}
References nom_.
get_info()
const Type_info * Nom::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 23 of file Nom.cpp.
getChar()
const char * Nom::getChar () const inline
Definition at line 88 of file Nom.h.
{  return nom_.c_str();  }
References nom_.
Referenced by Probleme_base::addInputField(), Type_info::ajouter_type(), Domaine_dis::discretiser(), is_a_binary_file(), EcrFicPartageMPIIO::ouvrir(), Operateur_base::ouvrir_fichier(), printOn(), Champ_Fonc_t::readOn(), UserUnaryFunction::setFunction(), Probleme_U::setInputField(), Parser_U::setString(), Champ_input_P0::setValue(), Champ_Input_Proto::setValueOnTab(), Op_Diff_VEFP1NCP1B_Face::test(), Refine_Mesh::update_sub_zones(), va_a_la_parenthese_fermante(), va_a_la_parenthese_ouvrante(), and Domaine_dis::~Domaine_dis().
getPrefix()
const Nom Nom::getPrefix (const char * const s) const
Definition at line 455 of file Nom.cpp.
{
  if (finit_par(s))
    {
      const int n1 = nom_.size();
      const int n2 = strlen(s);
      const std::string str1 = nom_.substr(0,n1-n2);
      return Nom(str1);
    }
  return *this;
}
References finit_par(), Nom(), and nom_.
Referenced by Milieu_composite::check_fluid_name(), Format_Post_Med::ecrire_champ_med(), and Scatter::lire_domaine().
getString() [1/2]
std::string & Nom::getString () inline
Definition at line 90 of file Nom.h.
{  return nom_;   }
References nom_.
getString() [2/2]
const std::string & Nom::getString () const inline
Definition at line 89 of file Nom.h.
{    return nom_;   }
References nom_.
Referenced by Operateur_base::ajouter(), Perte_Charge_Singuliere_VDF_Face::ajouter_(), Acceleration_QC_VDF_Face::ajouter_blocs(), Source_qdm_QC_VDF_Face::ajouter_blocs(), Perte_Charge_Reguliere_QC_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_QC_VDF_Face::ajouter_blocs(), Darcy_QC_VDF_Face::ajouter_blocs(), Forchheimer_QC_VDF_Face::ajouter_blocs(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Perte_Charge_Reguliere_VDF_Face::ajouter_blocs(), Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Op_Conv_VDF_base::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Solveur_Masse_base::ajouter_masse(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Equation_base::assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Milieu_base::associer_equation(), Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), build_triofield(), Equation_base::calculer_champ_conserve(), Fluide_base::calculer_e_int(), Milieu_composite::check_fluid_name(), Operateur_base::contribuer_a_avec(), Source_base::contribuer_a_avec(), Operateur_base::contribuer_termes_croises(), Champ_Fonc_MED::creer(), Operateur_base::dimensionner(), Source_base::dimensionner(), Solveur_Masse_base::dimensionner(), Masse_PolyMAC_Face::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Diff_VDF_Face_base::dimensionner_blocs(), Op_Dift_VDF_Elem_base::dimensionner_blocs(), Op_Dift_VDF_Face_base::dimensionner_blocs(), Masse_VDF_base::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::dimensionner_blocs(), Force_Tchen_PolyMAC_P0::dimensionner_blocs(), Frottement_interfacial_PolyMAC_P0::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_Elem::dimensionner_blocs_ext(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Operateur_base::dimensionner_termes_croises(), Pb_Multiphase::get_correlation(), Equation_base::get_fonc_champ_conserve(), Probleme_U::getInputFieldTemplate(), ScalarRegister::getOutputDoubleValue(), Probleme_U::getOutputField(), ScalarRegister::getOutputIntValue(), Pb_Multiphase::has_correlation(), SETS::iterer_eqn(), Simple::iterer_eqs(), SETS::lire(), Champ_Fonc_MED::lire(), Pb_Multiphase::lire_correlations(), Scatter::lire_domaine(), Decouper_multi::lire_motcle_non_standard(), Milieu_composite::mettre_a_jour_tabs(), Source_base::ouvrir_fichier(), read(), Partitionneur_Union::readOn(), Viscosite_turbulente_multiple::readOn(), Noms::search(), Noms::search_without_checking_Motcle(), UserUnaryFunction::setFunction(), ScalarRegister::setInputDoubleValue(), Probleme_U::setInputDoubleValue(), Probleme_U::setInputField(), ScalarRegister::setInputIntValue(), and Op_Diff_PolyMAC_base::update_aux().
getSuffix()
const Nom Nom::getSuffix (const char * const s) const
Definition at line 396 of file Nom.cpp.
{
  if (debute_par(s))
    {
      const int n1 = strlen(s);
      const int n2 = nom_.size();
      const std::string str1 = nom_.substr(n1,n2);
      return Nom(str1);
    }
  return *this;
}
References debute_par(), Nom(), and nom_.
Referenced by Operateur_base::completer(), Format_Post_Med::ecrire_champ_med(), Milieu_composite::mettre_a_jour_tabs(), Operateur_base::ouvrir_fichier(), and Sonde::readOn().
info()
const Type_info * Nom::info () static
Definition at line 23 of file Nom.cpp.
le_nom()
const Nom & Nom::le_nom () const override virtual
Renvoie *this;.
Returns
const Nom&
Signification: reference sur le Nom
Contraintes:
Reimplemented from Objet_U.
Definition at line 766 of file Nom.cpp.
{
  return *this;
}
Referenced by check_frontiere(), Sonde::completer(), Postraitement::creer_champ_post(), Echange_contact_PolyMAC::init_op(), Echange_contact_PolyMAC_P0::init_op(), Remove_Invalid_Internal_Boundaries::interpreter_(), and Sonde::readOn().
longueur()
int Nom::longueur () const
Renvoie le nombre de caracteres de la chaine du Nom
y compris le caractere zero de fin de chaine.
Exemple : Nom("hello").longueur() == 6.
Definition at line 298 of file Nom.cpp.
{
  return nom_.size()+1;
}
References nom_.
Referenced by Operateur_base::completer(), Zones::comprimer(), extract_time_from_string(), and System::interpreter().
majuscule()
Nom & Nom::majuscule ()
Transforme le nom en majuscules
Seules les lettres 'a'-'z' sont modifiees.
Definition at line 286 of file Nom.cpp.
{
  int length = nom_.size();
  for(int p = 0; p < length; p++)
    nom_[p] = toupper(nom_[p]);
  return *this;
}
References nom_.
Referenced by Motcle::Motcle(), Motcle::operator+=(), Motcle::operator=(), Motcle::readOn(), Parser::searchFunc(), and Champ_Generique_refChamp::set_ref_champ().
nom_me()
Nom Nom::nom_me (int n, const char * prefix = 0, int without_padding = 0) const
Insere _prefix000n (n=me() ou nproc()) dans un nom de fichier (par ex:toto.titi) pour donner toto_prefix000n.titi.
< backward loop
Definition at line 524 of file Nom.cpp.
{
  int compteur=nom_.size();
  const char* ptr=nom_.c_str()+compteur;
  while((*ptr!='.') && (*ptr!='/')&&(compteur>0))  //!< backward loop
    {
      ptr--;
      compteur--;
      if (*ptr=='/')
        {
          compteur=0;
        }
    }
  int pas_de_point=0;
  if(compteur==0)
    {
      compteur=nom_.size();
      pas_de_point=1 ;
    }
  std::string newname=nom_.substr(0,compteur);
// searching for the number of digits we want to write
  int digits=0,diviseur=0;
  if(without_padding)
    {
      digits = (n==0) ? 1 : log10(n)+1;
      diviseur = pow(10, digits-1);
    }
  else
    {
      if (Process::nproc()<=10000)
        {
// the underscore will be taken into account later
// digits=5;
          digits=4;
          diviseur=1000;
        }
      else if (Process::nproc()<=100000)
        {
// the underscore will be taken into account later
// digits=6;
          digits=5;
          diviseur=10000;
        }
      else if (Process::nproc()<=1000000)
        {
// the underscore will be taken into account later
// digits=7;
          digits=6;
          diviseur=100000;
        }
      else
        {
          Cerr << "Error in Nom::nom_me. Contact TRUST support." << finl;
          exit();
        }
    }
  int prefix_len = 1; //for the underscore
  if(prefixe) prefix_len+=strlen(prefixe);
  char *c_numero=new char[prefix_len+digits+1];
  int resultat;
  c_numero[0]='_';
  if(prefixe) strcpy(c_numero+1, prefixe);
  for (int i=prefix_len; i<prefix_len+digits; i++)
    {
      resultat=n/diviseur;
      char c=('0'+resultat);
      c_numero[i]=c;
      n-=resultat*diviseur;
      diviseur/=10;
    }
  c_numero[prefix_len+digits]='\0';
  newname+=c_numero;
  if (pas_de_point==0)
    newname+=ptr;
  Nom new_name(newname);
  delete[] c_numero;
  return new_name;
}
References Cerr, compteur, Process::exit(), finl, nom_, and Process::nproc().
Referenced by Postraiter_domaine::ecrire(), Format_Post_Med::ecrire_champ_med(), Format_Post_Med::ecrire_domaine_dis(), DomaineCutter::ecrire_zones(), Format_Post_Med::finir(), Raffiner_isotrope_parallele::interpreter(), Scatter::lire_domaine(), ScatterMED::lire_domaine(), LecFicDistribue::ouvrir(), EcrFicCollecte::ouvrir(), Ch_front_Vortex::reprendre_vortex(), and Ch_front_Vortex::sauvegarder_vortex().
operator const char *()
Nom::operator const char * () const
Retourne un pointeur sur la chaine de caractere du nom.
Returns
char*
Signification: pointeur sur la chaine de caractere du nom
Contraintes:
Definition at line 664 of file Nom.cpp.
{
  return nom_.c_str();
}
operator+()
Nom Nom::operator+ (const Nom & x) const
Concatenation avec un Nom.
Returns
Nom
Signification: le nouveau Nom cree avec la concatenation de this et de x
Contraintes:
Definition at line 482 of file Nom.cpp.
{
  Nom nouveau(*this);
  nouveau += x;
  return nouveau;
}
operator+=() [1/3]
Nom & Nom::operator+= (char x)
concatenation de chaine
Definition at line 360 of file Nom.cpp.
{
  char n[2];
  n[0] = x;
  n[1] = 0;
  operator+=(n);
  return *this;
}
References operator+=().
operator+=() [2/3]
Nom & Nom::operator+= (const char * x)
Definition at line 352 of file Nom.cpp.
{
  nom_ += x;
  return *this;
}
References nom_.
operator+=() [3/3]
Nom & Nom::operator+= (const Nom & x)
Concatenation avec un Nom.
Returns
Nom&
Signification: reference sur this
Contraintes:
Definition at line 346 of file Nom.cpp.
{
  nom_ += x.nom_;
  return *this;
}
References nom_.
Referenced by operator+=(), and Motcle::operator+=().
operator=() [1/2]
Nom & Nom::operator= (const char * const nom)
Copie la chaine nom.
Modif BM pour que nom puisse pointer sur une sous-partie de nom_.
Definition at line 306 of file Nom.cpp.
{
  nom_=nom;
  return *this;
}
References nom_.
Referenced by Nom(), Motcle::operator=(), and readOn().
operator=() [2/2]
Nom & Nom::operator= (const Nom & nom)
Copie le Nom nom.
Returns
Nom&
Signification: reference sur this qui represente la chaine du Nom nom
Contraintes:
Definition at line 326 of file Nom.cpp.
{
  nom_ = nom.nom_;
  return *this;
}
References nom_.
prefix()
Nom & Nom::prefix (const char * const s)
Definition at line 444 of file Nom.cpp.
{
  if (finit_par(s))
    {
      int n = nom_.size();
      int n2 = strlen(s);
      nom_.erase(n-n2,n2);
    }
  return *this;
}
References finit_par(), and nom_.
Referenced by Probleme_Couple::ajouter(), Format_Post_Med::completer_post(), Solv_Petsc::config(), Champ_front_contact_VEF::connectivity_failed(), Format_Post_XYZ::construire_nom_xyz(), Pb_MED::creer_champ(), Postraitement::creer_champ_post_med(), decompression(), DecoupeBord::Decouper(), Postraiter_domaine::ecrire(), Format_Post_Lata::ecrire_champ(), Format_Post_Lata_V1::ecrire_champ_lata_V1(), Format_Post_Med::ecrire_champ_med(), Postraitement::finir(), Format_Post_Med::finir_med(), Debog_Pb::goto_msg(), Postraitement::init(), Ecrire_Champ_MED::interpreter(), System::interpreter(), latatoother::interpreter(), Lire_Tgrid::interpreter_(), ScatterMED::lire_domaine(), main_TRUST(), Navier_Stokes_std::preparer_calcul(), Format_Post_Med::preparer_post_med(), Postraitement::readOn(), Champ_Fonc_MED::readOn(), and split_mot().
printOn()
Sortie & Nom::printOn (Sortie & s) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un Nom sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 48 of file Nom.cpp.
{
  const char* nom=getChar();
  if(nom)
    return s << nom;
  else
    return s;
}
References getChar().
Referenced by Motcle::printOn().
readOn()
Entree & Nom::readOn (Entree & s) override protected virtual
Lecture d'un nom.
En cas d'echec, le nom vaut "??" a la sortie.
Reimplemented from Objet_U.
Definition at line 60 of file Nom.cpp.
{
  char buffer[BUFLEN];
  const int ok = s.get(buffer, BUFLEN);
  if (ok)
    operator=(buffer);
  else
    operator=("??");
  return s;
}
References BUFLEN, Entree::get(), and operator=().
Referenced by Motcle::readOn().
sed_check_case_non_sensitive()
void Nom::sed_check_case_non_sensitive (int i) static
Definition at line 28 of file Nom.cpp.
{
  check_case_non_sensitive_=i;
}
References check_case_non_sensitive_.
self_cast() [1/2]
const Nom & Nom::self_cast (const Objet_U & r) static
Definition at line 23 of file Nom.cpp.
self_cast() [2/2]
Nom & Nom::self_cast (Objet_U & r) static
Definition at line 23 of file Nom.cpp.
substr_old()
Nom Nom::substr_old (const int deb, const int la_longueur) const
Retourne un nom selon la commande usuelle substr
ATTENTION : deb = 1 => premier caractere de la chaine !!!
Definition at line 610 of file Nom.cpp.
{
  assert(deb > 0);
  assert(deb - 1 + la_longueur <= (int) nom_.size());
  Nom nouveau(nom_.substr(deb-1,la_longueur));
  return nouveau;
}
References nom_.
Referenced by Op_Correlation::completer(), extract_time_from_string(), and Mod_turb_hyd_base::sauvegarder().
suffix()
Nom & Nom::suffix (const char * const s)
Extraction de suffixe :
Nom x("azerty");
x.suffix("aze")
x contient "rty".
Returns
Nom&
Signification: reference sur this
Contraintes:
Definition at line 386 of file Nom.cpp.
{
  if (debute_par(s))
    {
      int n2 = strlen(s);
      nom_.erase(0,n2);
    }
  return *this;
}
References debute_par(), and nom_.
Referenced by Op_Correlation::associer(), Op_Ecart_type::associer(), Op_Moyenne::associer(), basename(), Sonde::completer(), Navier_Stokes_std::completer(), Convection_Diffusion_Temperature::creer_champ(), Postraitement::creer_champ_post_med(), Domaine_dis::discretiser(), Discretisation_base::get_name_of_type_for(), Debog_Pb::goto_msg(), System::interpreter(), Champ_Fonc_reprise::readOn(), Convection_Diffusion_Temperature::readOn(), and split_mot().
taille_memoire()
unsigned Nom::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 23 of file Nom.cpp.
Friends And Related Function Documentation
operator!= [1/3]
int operator!= (const char * const un_autre, const Nom & un_nom) friend
Definition at line 747 of file Nom.cpp.
{
  return ! (un_autre == un_nom);
}
operator!= [2/3]
int operator!= (const Nom & un_nom, const char * un_autre) friend
Comparaison d'un nom avec une chaine de caractere.
Returns
int
Signification: 1 si les noms sont differents, 0 sinon
Contraintes:
Definition at line 737 of file Nom.cpp.
{
  return ! (un_nom == un_autre);
}
operator!= [3/3]
int operator!= (const Nom & un_nom, const Nom & un_autre) friend
Definition at line 742 of file Nom.cpp.
{
  return ! (un_nom == un_autre);
}
operator== [1/3]
int operator== (const char * const un_autre, const Nom & un_nom) friend
Definition at line 713 of file Nom.cpp.
{
  return (un_nom == un_autre);
}
operator== [2/3]
int operator== (const Nom & un_nom, const char * const un_autre) friend
Comparaison d'un nom avec une chaine de caractere
Utilise strcmp.
Returns
int
Signification: 1 si les noms sont egaux, 0 sinon
Contraintes:
Definition at line 689 of file Nom.cpp.
{
  int res_actu=(un_nom.nom_.compare(un_autre)==0);
#ifndef NDEBUG
  if ((!res_actu) && (Nom::check_case_non_sensitive_==1))
    {
      Nom toto(un_autre);
      if (toto.majuscule().nom_.compare(un_nom.getChar()) == 0)
        {
          Cerr << "Warning: " << un_nom << " and " << un_autre << " are they really different ?" << finl;
          Cerr << "A test in the code on a string of characters does not seem to take account of the case." << finl;
          Cerr << "Contact TRUST support by sending your data file of this calculation." << finl;
          Cerr << finl;
        }
    }
#endif
  return res_actu;
}
operator== [3/3]
int operator== (const Nom & un_nom, const Nom & un_autre) friend
Definition at line 708 of file Nom.cpp.
{
  return (un_nom==un_autre.getChar());
}
Member Data Documentation
check_case_non_sensitive_
int Nom::check_case_non_sensitive_ =1 static protected
pour descativer dans ==
Definition at line 98 of file Nom.h.
Referenced by sed_check_case_non_sensitive().
info_obj
const Type_info Nom::info_obj static
Definition at line 36 of file Nom.h.
nb_noms
int Nom::nb_noms =0 static protected
Definition at line 95 of file Nom.h.
Referenced by Nom(), and ~Nom().
nom_
std::string Nom::nom_ protected
Definition at line 96 of file Nom.h.
Referenced by basename(), contient(), debute_par(), find(), finit_par(), getChar(), getPrefix(), getString(), getSuffix(), longueur(), majuscule(), Nom(), nom_me(), operator+=(), operator=(), prefix(), substr_old(), and suffix().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Nom.h
src/Kernel/Utilitaires/Nom.cpp