TRUST: Champ_front_lu Class Reference
Champ_front_lu Class Reference
classe Champ_front_lu
Classe derivee de Champ_front_var qui represente les
champs aux frontieres dont les valeurs sont lues dans un fichier de format :
nval
xi yi zi val_i
#include <Champ_front_lu.h>
Public Member Functions
Champ_front_lu ()
~Champ_front_lu ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
int is_bin (Nom name)
Renvoie le format du fichier lu.
Public Member Functions inherited from Ch_front_var_stationnaire
Ch_front_var_stationnaire ()
~Ch_front_var_stationnaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & valeurs_au_temps (double temps) override
Renvoie les valeurs sans s'occuper du temps puisque le champ
est stationnaire.
const DoubleTab & valeurs_au_temps (double temps) const override
Renvoie les valeurs sans s'occuper du temps puisque le champ
est stationnaire.
int avancer (double temps) override
Avance en temps : rien a faire pour un champ stationnaire !
int reculer (double temps) override
Recule en temps : rien a faire pour un champ stationnaire !
Champ_front_base & affecter_ (const Champ_front_base &ch) override
void changer_temps_futur (double temps, int i) override
Public Member Functions inherited from Champ_front_var
Champ_front_var ()
~Champ_front_var () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Public Member Functions inherited from Champ_front_base
~Champ_front_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base ()
virtual void completer ()
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe une frontiere discretisee au champ.
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
virtual DoubleTab & valeurs_au_temps (double temps)=0
virtual const DoubleTab & valeurs_au_temps (double temps) const =0
const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee associee au champ.
(version const)
Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee associee au champ.
const Zone_dis_base & zone_dis () const
virtual Champ_front_base & affecter_ (const Champ_front_base &ch)=0
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
virtual void calculer_coeffs_echange (double temps)
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
virtual void valeurs_face (int, DoubleVect &) const
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
virtual void verifier (const Cond_lim_base &la_cl) const
double get_temps_defaut () const
void set_temps_defaut (double temps)
virtual void changer_temps_futur (double temps, int i)
virtual int avancer (double temps)
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe
en parametre.
virtual int reculer (double temps)
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe
en parametre.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_front_lu & self_cast (Objet_U &)
static const Champ_front_lu & self_cast (const Objet_U &)
Static Public Member Functions inherited from Ch_front_var_stationnaire
static const Type_info * info ()
static Ch_front_var_stationnaire & self_cast (Objet_U &)
static const Ch_front_var_stationnaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var
static const Type_info * info ()
static Champ_front_var & self_cast (Objet_U &)
static const Champ_front_var & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_base
static const Type_info * info ()
static Champ_front_base & self_cast (Objet_U &)
static const Champ_front_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Ch_front_var_stationnaire
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime le champ sur flot de sortie.
Imprime la taille du champ et la valeur (constante) sur
la frontiere.
Entree & readOn (Entree &) override
Lit le champ a partir d'un flot d'entree.
Format:
Champ_front_lu nb_compo vrel_1 ... [vrel_i].
Protected Member Functions inherited from Ch_front_var_stationnaire
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Champ_front_var
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Domaine mon_domaine
Nom nom_fic
Protected Attributes inherited from Champ_front_base
double temps_defaut
Le temps pris par defaut quand le parametre n'est pas specifie. Ce sera en particulier celui utilise par les operateurs et les solveurs.
Ref_Frontiere_dis_base la_frontiere_dis
Roue_ptr les_valeurs
Les valeurs du champ.
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
classe Champ_front_lu
Classe derivee de Champ_front_var qui represente les
champs aux frontieres dont les valeurs sont lues dans un fichier de format :
nval
xi yi zi val_i
Definition at line 36 of file Champ_front_lu.h.
Constructor & Destructor Documentation
Champ_front_lu()
Champ_front_lu::Champ_front_lu ()
Definition at line 22 of file Champ_front_lu.cpp.
~Champ_front_lu()
Champ_front_lu::~Champ_front_lu ()
Definition at line 22 of file Champ_front_lu.cpp.
Member Function Documentation
cree_instance()
Objet_U * Champ_front_lu::cree_instance () static
Definition at line 22 of file Champ_front_lu.cpp.
duplique()
int Champ_front_lu::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file Champ_front_lu.cpp.
get_info()
const Type_info * Champ_front_lu::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 22 of file Champ_front_lu.cpp.
info()
const Type_info * Champ_front_lu::info () static
Definition at line 22 of file Champ_front_lu.cpp.
initialiser()
int Champ_front_lu::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Champ_front_base.
Definition at line 111 of file Champ_front_lu.cpp.
{
  if (!Ch_front_var_stationnaire::initialiser(temps,inco))
    return 0;
  int dim=nb_comp();
  Domaine& domaine=mon_domaine.valeur();
  const Frontiere_dis_base& fr_dis=frontiere_dis();
  const Frontiere& frontiere=fr_dis.frontiere();
  const int nb_faces=frontiere.nb_faces();
  const int ndeb=frontiere.num_premiere_face();
  DoubleTab& les_val=valeurs();
  LecFicDiffuse fic;
  int bin=is_bin(nom_fic);
  fic.set_bin(bin);
  fic.ouvrir(nom_fic);
  Nom format;
  if (bin)
    fic >> format;
  else
    format="ascii";
  Cerr << "Reading of the " << format << " file : " << nom_fic << finl;
  DoubleVect point(dimension);
  DoubleVect val_lu(dim);
  int nb_val_lues;
  fic >> nb_val_lues;
// Verification (il se peut que le fichier contienne PLUS de faces que la frontiere, exemple en periodique)
  int nb_faces_tot = mp_sum(nb_faces);
  if (nb_val_lues<nb_faces_tot)
    {
      Cerr << "This file contains " << nb_val_lues << " faces which is not enough compare to" << finl;
      Cerr << "the faces number (" << nb_faces_tot << ") of the boundary " << frontiere.le_nom() << finl;
      exit();
    }
// PQ 20/06/06 : pour permettre une recherche "rapide" des faces
// on s'appuie sur ma_zone.chercher_elements(x,y,z)
// (methode inspiree de EcritureLectureSpecial::lecture_special)
//
// Restriction --> champs aux faces
  const Zone& ma_zone = domaine.zone(0);
  int nb_elems = ma_zone.nb_elem();
  int nbfacelem=ma_zone.nb_faces_elem();
  const Zone_VF& zvf = ref_cast(Zone_VF, zone_dis());
  const IntTab& elem_faces=zvf.elem_faces();
  const DoubleTab& xv=zvf.xv();
  IntTab compteur(nb_faces);
  compteur=0;
  int k;
  double x,y,z=0;
  int pourcent=0,tmp;
  for (int p=0; p<nb_val_lues; p++)
    {
      tmp=(p*10)/nb_val_lues;
      if (tmp>pourcent)
        {
          pourcent=tmp;
          Cerr<<"\rProcess "<<Process::me()<<" has read "<<pourcent*10<<"% of values"<<flush;
        }
      for (k=0; k<dimension; k++)
        fic >> point[k];
      for (k=0; k<dim; k++)
        fic >>val_lu[k];
      x=point[0];
      y=point[1];
      if (Objet_U::dimension==3) z=point[2];
      int Case=-1;
// Premier algorithme (le plus rapide) cherchant l'element
// contenant le centre de gravite de la face
      int num_elem=ma_zone.chercher_elements(x,y,z);
      if ((num_elem!=-1) && (num_elem<nb_elems))
        {
// On cherche la face de l'element
          for (int fac=0; fac<nbfacelem; fac++)
            {
              int face=elem_faces(num_elem,fac);
              int ok=1;
              for (int dir=0; dir<dimension; dir++)
                {
                  ok=ok&&(est_egal(point[dir],xv(face,dir)));
                }
              if (ok)
                {
                  Case=face;
                  break;
                }
            }
        }
      else
        {
// Deuxieme algorithme (plus lent) utilise dans le cas ou le point se trouve a l'exterieur du domaine
// Dans ce cas la, on parcours les faces de la frontiere
          for (int face=0; face<nb_faces; face++)
            if (compteur[face] == 0)
              {
                int ok=1;
                for (int dir=0; dir<dimension; dir++)
                  ok=ok&&(est_egal(point[dir],xv(ndeb+face,dir)));
                if (ok)
                  {
                    Case=ndeb+face;
                    break;
                  }
              }
        }
// Face trouvee
      if (Case!=-1)
        {
          int face_loc=Case-ndeb;
          if ((face_loc<0) || (face_loc>=nb_faces))
            {
              Cerr << " The face " << ndeb << " found doesn't belong to the boundary sought " << finl;
              exit();
            }
          compteur[face_loc] += 1;
          for (k=0; k<dim; k++)
            les_val(face_loc,k) = val_lu[k];
        }
    }
  Cerr<<"\rProcess "<<Process::me()<<" has read 100% of values"<<finl;
// On verifie que toutes les faces de la frontiere ont ete affectees
  int err=0;
  for (int face=0; face<nb_faces; face++)
    if (compteur[face] != 1)
      {
        Cerr.precision(12);
        if (compteur[face] == 0)
          Cerr << "No value found for the face " << face << "/" << nb_faces-1 << " of the boundary " << frontiere.le_nom() << " on the processor " << Process::me() << ".";
        else
          Cerr << "Several values found for the face " << face << "/" << nb_faces-1 << " of the boundary " << frontiere.le_nom() << " on the processor " << Process::me() << ".";
        Cerr << " Coordinates: " << xv(ndeb+face,0) << " " << xv(ndeb+face,1);
        if (dimension==3) Cerr << " " << xv(ndeb+face,2);
        Cerr << finl;
        err=1;
      }
  if (Process::mp_sum(err))
    {
      erreur_chfront(nom_fic, dim, mon_domaine.le_nom());
    }
  les_val.echange_espace_virtuel();
  return 1;
}
References Cerr, Zone::chercher_elements(), compteur, Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), erreur_chfront(), est_egal(), Process::exit(), finl, Frontiere_dis_base::frontiere(), Champ_front_base::frontiere_dis(), Champ_front_var::initialiser(), is_bin(), Frontiere::le_nom(), O_U_Ptr::le_nom(), Process::me(), mon_domaine, Process::mp_sum(), Field_base::nb_comp(), Zone::nb_elem(), Frontiere::nb_faces(), Zone::nb_faces_elem(), nom_fic, Frontiere::num_premiere_face(), LecFicDiffuse::ouvrir(), ref_cast, Lec_Diffuse_base::set_bin(), Ref_Domaine::valeur(), Champ_front_base::valeurs(), Zone_VF::xv(), Domaine::zone(), and Champ_front_base::zone_dis().
is_bin()
int Champ_front_lu::is_bin (Nom name)
Renvoie le format du fichier lu.
Returns
int
Signification:
Contraintes:
Definition at line 278 of file Champ_front_lu.cpp.
{
  LecFicDiffuse fichier(name);
  Nom format;
  fichier >> format;
#ifdef INT_is_64_
// In case of INT_64, first Nom can be INT64 ...
  if(format=="INT64")
    format="binary";
#endif
  if(format=="binary")
    return 1;
  else
    return 0;
}
Referenced by initialiser().
printOn()
Sortie & Champ_front_lu::printOn (Sortie & os) const override protected virtual
Imprime le champ sur flot de sortie.
Imprime la taille du champ et la valeur (constante) sur
la frontiere.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 42 of file Champ_front_lu.cpp.
{
  const DoubleTab& tab=valeurs();
  os << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    os << tab(0,i);
  return os;
}
References TRUSTVect< _TYPE_ >::size(), and Champ_front_base::valeurs().
readOn()
Entree & Champ_front_lu::readOn (Entree & is) override protected virtual
Lit le champ a partir d'un flot d'entree.
Format:
Champ_front_lu nb_compo vrel_1 ... [vrel_i].
Returns
Entree& is
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 68 of file Champ_front_lu.cpp.
{
  int dim;
  Motcle motlu;
  Nom nom;
  is >> nom;
  mon_domaine = ref_cast(Domaine, Interprete::objet(nom));
  dim=lire_dimension(is,que_suis_je());
  fixer_nb_comp(dim);
  is >> nom_fic;
// Lecture des valeurs dans le fichier fic
  return is;
}
References Field_base::fixer_nb_comp(), Champ_Proto::lire_dimension(), mon_domaine, nom_fic, Interprete::objet(), Objet_U::que_suis_je(), and ref_cast.
self_cast() [1/2]
const Champ_front_lu & Champ_front_lu::self_cast (const Objet_U & r) static
Definition at line 22 of file Champ_front_lu.cpp.
self_cast() [2/2]
Champ_front_lu & Champ_front_lu::self_cast (Objet_U & r) static
Definition at line 22 of file Champ_front_lu.cpp.
taille_memoire()
unsigned Champ_front_lu::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file Champ_front_lu.cpp.
Member Data Documentation
info_obj
const Type_info Champ_front_lu::info_obj static
Definition at line 38 of file Champ_front_lu.h.
mon_domaine
Ref_Domaine Champ_front_lu::mon_domaine protected
Definition at line 46 of file Champ_front_lu.h.
Referenced by initialiser(), and readOn().
nom_fic
Nom Champ_front_lu::nom_fic protected
Definition at line 47 of file Champ_front_lu.h.
Referenced by initialiser(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_front_lu.h
src/Kernel/Champs/Champ_front_lu.cpp