TRUST: Op_Diff_VEF_Face_Stab Class Reference
Op_Diff_VEF_Face_Stab Class Reference
class Op_Diff_VEF_Face_Stab
Cette classe represente l'operateur de diffusion
La discretisation est VEF
Le champ diffuse est scalaire
Le champ de diffusivite est uniforme
#include <Op_Diff_VEF_Face_Stab.h>
Public Member Functions
Op_Diff_VEF_Face_Stab ()
~Op_Diff_VEF_Face_Stab ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_multi_scalaire (const DoubleTab &, Matrice_Morse &) const
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
on assemble la matrice.
Public Member Functions inherited from Op_Diff_VEF_Face
Op_Diff_VEF_Face ()
~Op_Diff_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_diffusivite (const Champ_base &) override
associe le champ de diffusivite
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
const Champ_base & diffusivite () const override
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
void verifier () const
void dimensionner (Matrice_Morse &) const override
on dimensionne notre matrice.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
on assemble la matrice.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_multi_scalaire (const DoubleTab &, Matrice_Morse &) const
void ajouter_cas_scalaire (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF) const
void ajouter_cas_vectoriel (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
void ajouter_cas_multi_scalaire (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
Public Member Functions inherited from Op_Diff_VEF_base
Op_Diff_VEF_base ()
~Op_Diff_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
double viscA (int face_i, int face_j, int num_elem, double diffu) const
double viscA (int face_i, int face_j, int num_elem, DoubleTab &diffu) const
double viscA (int face_i, int face_j, int num_elem, ArrOfDouble &diffu_ci_cj_elem) const
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_nu (DoubleTab &) const
int phi_psi_diffuse (const Equation_base &eq) const
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Diff_VEF_Face_Stab & self_cast (Objet_U &)
static const Op_Diff_VEF_Face_Stab & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_VEF_Face
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Diff_VEF_Face & self_cast (Objet_U &)
static const Op_Diff_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_VEF_base
static const Type_info * info ()
static Op_Diff_VEF_base & self_cast (Objet_U &)
static const Op_Diff_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_VEF_Face
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
void calculer_coefficients (const DoubleTab &, DoubleTab &) const
void calculer_min (const DoubleTab &, int &, DoubleTab &) const
void calculer_max (const DoubleTab &, int &, DoubleTab &) const
double calculer_gradients (int, const DoubleTab &) const
void modifie_pour_Cl (const DoubleTab &, DoubleTab &) const
void ajouter_operateur_centre (const DoubleTab &, const DoubleTab &, DoubleTab &) const
void ajouter_diffusion (const DoubleTab &, const DoubleTab &, DoubleTab &) const
void ajouter_antidiffusion (const DoubleTab &, const DoubleTab &, DoubleTab &) const
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Private Attributes
int standard_
int info_
int new_jacobian_
IntTab is_dirichlet_faces_
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Protected Attributes inherited from Op_Diff_VEF_Face
Ref_Champ_base diffusivite_
Protected Attributes inherited from Op_Diff_VEF_base
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base inconnue_
DoubleTab nu_
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Op_Diff_VEF_Face_Stab
Cette classe represente l'operateur de diffusion
La discretisation est VEF
Le champ diffuse est scalaire
Le champ de diffusivite est uniforme
Definition at line 32 of file Op_Diff_VEF_Face_Stab.h.
Constructor & Destructor Documentation
Op_Diff_VEF_Face_Stab()
Op_Diff_VEF_Face_Stab::Op_Diff_VEF_Face_Stab ()
Definition at line 41 of file Op_Diff_VEF_Face_Stab.cpp.
{
~Op_Diff_VEF_Face_Stab()
Op_Diff_VEF_Face_Stab::~Op_Diff_VEF_Face_Stab ()
Definition at line 41 of file Op_Diff_VEF_Face_Stab.cpp.
{
Member Function Documentation
ajouter()
DoubleTab & Op_Diff_VEF_Face_Stab::ajouter (const DoubleTab & inconnue_org, DoubleTab & resu) const override virtual
Reimplemented from Op_Diff_VEF_Face.
Definition at line 138 of file Op_Diff_VEF_Face_Stab.cpp.
{
  remplir_nu(nu_);
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
  DoubleTab nu;
  DoubleTab tab_inconnue;
  int marq=phi_psi_diffuse(equation());
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
  modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
  const DoubleTab& inconnue=modif_par_porosite_si_flag(inconnue_org,tab_inconnue,marq,porosite_face);
//
//
//
  DoubleTab resu2(resu);
  resu2=0.;
  DoubleTab Aij(nb_elem_tot,nb_faces_elem,nb_faces_elem);
  calculer_coefficients(nu,Aij);
  ajouter_operateur_centre(Aij,inconnue,resu2);
  if (!standard_)
    {
      ajouter_diffusion(Aij,inconnue,resu2);
      ajouter_antidiffusion(Aij,inconnue,resu2);
    }
  modifie_pour_Cl(inconnue,resu2);
  modifier_flux(*this);
  resu-=resu2;//-= car le laplacien est place en terme source dans l'equation
  return resu;
}
References ajouter_antidiffusion(), ajouter_diffusion(), ajouter_operateur_centre(), calculer_coefficients(), MorEqn::equation(), Op_Diff_VEF_base::la_zone_vef, modif_par_porosite_si_flag(), modifie_pour_Cl(), Op_VEF_Face::modifier_flux(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Op_Diff_VEF_base::remplir_nu(), standard_, Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
ajouter_antidiffusion()
void Op_Diff_VEF_Face_Stab::ajouter_antidiffusion (const DoubleTab & Aij, const DoubleTab & inconnueTab, DoubleTab & resuTab) const protected
Definition at line 387 of file Op_Diff_VEF_Face_Stab.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_tot=zone_VEF.nb_faces_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  int nb_comp=1;
  if(resuTab.nb_dim()==2) nb_comp=resuTab.dimension(1);
  const DoubleVect& inconnue = inconnueTab;
  DoubleVect& resu = resuTab;
  const DoubleTab& xv=zone_VEF.xv();
  DoubleTab rij(Objet_U::dimension);
  DoubleTab rji(rij);
  int elem=0;
  int facei_loc=0,facei=0;
  int facej_loc=0,facej=0;
  int dim=0;
  int dim2=0;
  double inc_i=0.;
  double inc_j=0.;
  double delta_ij=0.;
  double delta_imax=0.,delta_imin=0.;
  double delta_jmax=0.,delta_jmin=0.;
  double sij=0.;
  double sij_max=DMINFLOAT;
  double sij_min=DMAXFLOAT;
  double muij=0.,muji=0.;
  bool ok_facei=false;
  bool ok_facej=false;
  const IntTab& elem_faces=zone_VEF.elem_faces();
  DoubleTab Minima(nb_faces_tot);
  DoubleTab Maxima(nb_faces_tot);
  for (dim=0; dim<nb_comp; dim++)
    {
      calculer_min(inconnueTab,dim,Minima);
      calculer_max(inconnueTab,dim,Maxima);
      for (elem=0; elem<nb_elem_tot; elem++)
        for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
          {
            facei=elem_faces(elem,facei_loc);
            ok_facei=is_dirichlet_faces_(facei);
            inc_i=inconnue[facei*nb_comp+dim];
            delta_imin=Minima(facei)-inc_i;
            delta_imax=Maxima(facei)-inc_i;
            assert(delta_imax>=0.);
            assert(delta_imin<=0.);
            for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
              {
                const double aij=Aij(elem,facei_loc,facej_loc);
                if (aij>0.)
                  {
                    facej=elem_faces(elem,facej_loc);
                    ok_facej=is_dirichlet_faces_(facej);
                    inc_j=inconnue[facej*nb_comp+dim];
                    for (dim2=0; dim2<Objet_U::dimension; dim2++)
                      rij(dim2)=xv(facej,dim2)-xv(facei,dim2);
                    rji=rij;
                    rji*=-1.;
                    delta_ij=inc_i-inc_j;
                    delta_jmin=Minima(facej)-inc_j;
                    delta_jmax=Maxima(facej)-inc_j;
                    assert(delta_jmax>=0.);
                    assert(delta_jmin<=0.);
                    muij=calculer_gradients(facei,rij);
                    muji=calculer_gradients(facej,rji);
                    sij=0.; //reste a 0 si que des faces de Dirichlet
                    if (delta_ij>0.)
                      {
                        muij*=delta_imax;
                        muji*=-delta_jmin;
                        if (!ok_facei && !ok_facej) //pas de face de Dirichlet
                          sij=minimum(muij,delta_ij,muji);
                        if (!ok_facei && ok_facej) //facej Dirichlet et pas facei
                          sij=minimum(muij,delta_ij);
                        if (ok_facei && !ok_facej) //facei Dirichlet et pas facej
                          sij=minimum(delta_ij,muji);
                      }
                    else if (delta_ij<0.)
                      {
                        muij*=delta_imin;
                        muji*=-delta_jmax;
                        if (!ok_facei && !ok_facej) //pas de face de Dirichlet
                          sij=maximum(muij,delta_ij,muji);
                        if (!ok_facei && ok_facej) //facej Dirichlet et pas facei
                          sij=maximum(muij,delta_ij);
                        if (ok_facei && !ok_facej) //facei Dirichlet et pas facej
                          sij=maximum(delta_ij,muji);
                      }
                    if (info_)
                      if (delta_ij!=0.)
{
                          double tmp=sij/delta_ij;
                          if (tmp>sij_max) sij_max=tmp;
                          if (tmp<sij_min) sij_min=tmp;
                        }
                    resu[facei*nb_comp+dim]-=aij*sij;
                    resu[facej*nb_comp+dim]+=aij*sij;
                  }
              }
          }
    }
  {
    sij_max = Process::mp_max(sij_max);
    sij_min = Process::mp_min(sij_min);
    if (info_ && Process::je_suis_maitre())
      {
        SFichier mem_fichier("sij_memory.txt");
        mem_fichier<<sij_max<<" "<<sij_min<<finl;
      }
  }
}
References calculer_gradients(), calculer_max(), calculer_min(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, DMAXFLOAT, DMINFLOAT, Zone_VF::elem_faces(), finl, info_, is_dirichlet_faces_, Process::je_suis_maitre(), Op_Diff_VEF_base::la_zone_vef, maximum(), minimum(), Process::mp_max(), Process::mp_min(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Zone_VF::nb_faces_tot(), Ref_Zone_VEF::valeur(), Zone_VF::xv(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_contribution()
void Op_Diff_VEF_Face_Stab::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
Definition at line 860 of file Op_Diff_VEF_Face_Stab.cpp.
{
  if (!new_jacobian_)
    Op_Diff_VEF_Face::ajouter_contribution(transporte,matrice);
  else
    {
      modifier_matrice_pour_periodique_avant_contribuer(matrice,equation());
// On remplit le tableau nu car l'assemblage d'une
// matrice avec ajouter_contribution peut se faire
// avant le premier pas de temps
      remplir_nu(nu_);
      const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
      const Zone_VEF& zone_VEF = la_zone_vef.valeur();
      const IntTab& elem_faces = zone_VEF.elem_faces();
      const IntTab& face_voisins = zone_VEF.face_voisins();
      int n1 = zone_VEF.nb_faces();
      int nb_comp = 1;
      int nb_dim = transporte.nb_dim();
      DoubleTab nu;
      int marq=phi_psi_diffuse(equation());
      const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
      modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
      DoubleVect porosite_eventuelle(zone_VEF.porosite_face());
      if (!marq)
        porosite_eventuelle=1;
      if(nb_dim==2)
        nb_comp=transporte.dimension(1);
      int i,j,num_face;
      int elem1,elem2;
      int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
      double val;
      int nb_bords=zone_VEF.nb_front_Cl();
      for (int n_bord=0; n_bord<nb_bords; n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          if (sub_type(Periodique,la_cl.valeur()))
            {
              const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
              int fac_asso;
// on ne parcourt que la moitie des faces periodiques
// on copiera a la fin le resultat dans la face associe..
              int num2b=num1+le_bord.nb_faces()/2;
              for (num_face=num1; num_face<num2b; num_face++)
                {
                  elem1 = face_voisins(num_face,0);
                  elem2 = face_voisins(num_face,1);
                  fac_asso = la_cl_perio.face_associee(num_face-num1)+num1;
                  for (i=0; i<nb_faces_elem; i++)
                    {
                      if ( (j=elem_faces(elem1,i)) > num_face )
{
                          val = viscA(num_face,j,elem1,nu(elem1));
                          if (val<0.) val=0.;
                          for (int nc=0; nc<nb_comp; nc++)
{
                              int n0=num_face*nb_comp+nc;
                              int j0=j*nb_comp+nc;
                              matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                              matrice(n0,j0)-=val*porosite_eventuelle(j);
                              matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                              matrice(j0,j0)+=val*porosite_eventuelle(j);
                            }
                        }
                      if (elem2!=-1)
                        if ( (j=elem_faces(elem2,i)) > num_face )
{
                            val= viscA(num_face,j,elem2,nu(elem2));
                            if (val<0.) val=0.;
                            for (int nc=0; nc<nb_comp; nc++)
{
                                int n0=num_face*nb_comp+nc;
                                int j0=j*nb_comp+nc;
                                int  n0perio=fac_asso*nb_comp+nc;
                                matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                                matrice(n0,j0)-=val*porosite_eventuelle(j);
                                matrice(j0,n0perio)-=val*porosite_eventuelle(num_face);
                                matrice(j0,j0)+=val*porosite_eventuelle(j);
                              }
                          }
                    }
                }
            }
          else
            {
              for (num_face=num1; num_face<num2; num_face++)
                {
                  elem1 = face_voisins(num_face,0);
                  for (i=0; i<nb_faces_elem; i++)
                    {
                      if ( (j= elem_faces(elem1,i)) > num_face )
{
                          val = viscA(num_face,j,elem1,nu(elem1));
                          if (val<0.) val=0.;
                          for (int nc=0; nc<nb_comp; nc++)
{
                              int n0=num_face*nb_comp+nc;
                              int j0=j*nb_comp+nc;
                              matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                              matrice(n0,j0)-=val*porosite_eventuelle(j);
                              matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                              matrice(j0,j0)+=val*porosite_eventuelle(j);
                            }
                        }
                    }
                }
            }
        }
      int num_premiere_face = zone_VEF.premiere_face_int();
      for (num_face=num_premiere_face; num_face<n1; num_face++)
        {
          elem1 = face_voisins(num_face,0);
          elem2 = face_voisins(num_face,1);
          for (i=0; i<nb_faces_elem; i++)
            {
              if ( (j=elem_faces(elem1,i)) > num_face )
                {
                  val = viscA(num_face,j,elem1,nu(elem1));
                  if (val<0.) val=0.;
                  for (int nc=0; nc<nb_comp; nc++)
                    {
                      int n0=num_face*nb_comp+nc;
                      int j0=j*nb_comp+nc;
                      matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                      matrice(n0,j0)-=val*porosite_eventuelle(j);
                      matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                      matrice(j0,j0)+=val*porosite_eventuelle(j);
                    }
                }
              if (elem2!=-1)
                if ( (j=elem_faces(elem2,i)) > num_face )
                  {
                    val= viscA(num_face,j,elem2,nu(elem2));
                    if (val<0.) val=0.;
                    for (int nc=0; nc<nb_comp; nc++)
                      {
                        int n0=num_face*nb_comp+nc;
                        int j0=j*nb_comp+nc;
                        matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                        matrice(n0,j0)-=val*porosite_eventuelle(j);
                        matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                        matrice(j0,j0)+=val*porosite_eventuelle(j);
                      }
                  }
            }
        }
      modifier_matrice_pour_periodique_apres_contribuer(matrice,equation());
    }
}
References Op_Diff_VEF_Face::ajouter_contribution(), TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), modif_par_porosite_si_flag(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), TRUSTTab< _TYPE_ >::nb_dim(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Zone_dis_base::nb_front_Cl(), new_jacobian_, Op_Diff_VEF_base::nu_, Front_VF::num_premiere_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, Op_Diff_VEF_base::remplir_nu(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Op_Diff_VEF_base::viscA(), and Zone_dis_base::zone().
Referenced by contribuer_a_avec().
ajouter_contribution_multi_scalaire()
void Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire (const DoubleTab & transporte, Matrice_Morse & matrice) const
Definition at line 1033 of file Op_Diff_VEF_Face_Stab.cpp.
{
  if (!new_jacobian_)
    Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(transporte,matrice);
  else
    {
      modifier_matrice_pour_periodique_avant_contribuer(matrice,equation());
// On remplit le tableau nu car l'assemblage d'une
// matrice avec ajouter_contribution peut se faire
// avant le premier pas de temps
      remplir_nu(nu_);
      const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
      const Zone_VEF& zone_VEF = la_zone_vef.valeur();
      const IntTab& elem_faces = zone_VEF.elem_faces();
      const IntTab& face_voisins = zone_VEF.face_voisins();
      int n1 = zone_VEF.nb_faces();
      int nb_comp = 1;
      int nb_dim = transporte.nb_dim();
      DoubleTab nu;
      int marq=phi_psi_diffuse(equation());
      const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
      modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
      DoubleVect porosite_eventuelle(zone_VEF.porosite_face());
      if (!marq)
        porosite_eventuelle=1;
      if(nb_dim==2)
        nb_comp=transporte.dimension(1);
      int i,j,num_face;
      int elem1,elem2;
      int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
      double val;
      int nb_bords=zone_VEF.nb_front_Cl();
      for (int n_bord=0; n_bord<nb_bords; n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          if (sub_type(Periodique,la_cl.valeur()))
            {
              const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
              int fac_asso;
// on ne parcourt que la moitie des faces periodiques
// on copiera a la fin le resultat dans la face associe..
              int num2b=num1+le_bord.nb_faces()/2;
              for (num_face=num1; num_face<num2b; num_face++)
                {
                  elem1 = face_voisins(num_face,0);
                  elem2 = face_voisins(num_face,1);
                  fac_asso = la_cl_perio.face_associee(num_face-num1)+num1;
                  for (i=0; i<nb_faces_elem; i++)
                    {
                      if ( (j=elem_faces(elem1,i)) > num_face )
{
                          for (int nc=0; nc<nb_comp; nc++)
{
                              val = viscA(num_face,j,elem1,nu(elem1,nc));
                              if (val<0.) val=0.;
                              int n0=num_face*nb_comp+nc;
                              int j0=j*nb_comp+nc;
                              matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                              matrice(n0,j0)-=val*porosite_eventuelle(j);
                              matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                              matrice(j0,j0)+=val*porosite_eventuelle(j);
                            }
                        }
                      if (elem2!=-1)
                        if ( (j=elem_faces(elem2,i)) > num_face )
{
                            for (int nc=0; nc<nb_comp; nc++)
{
                                val = viscA(num_face,j,elem2,nu(elem1,nc));
                                if (val<0.) val=0.;
                                int n0=num_face*nb_comp+nc;
                                int j0=j*nb_comp+nc;
                                int  n0perio=fac_asso*nb_comp+nc;
                                matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                                matrice(n0,j0)-=val*porosite_eventuelle(j);
                                matrice(j0,n0perio)-=val*porosite_eventuelle(num_face);
                                matrice(j0,j0)+=val*porosite_eventuelle(j);
                              }
                          }
                    }
                }
            }
          else
            {
              for (num_face=num1; num_face<num2; num_face++)
                {
                  elem1 = face_voisins(num_face,0);
                  for (i=0; i<nb_faces_elem; i++)
                    {
                      if ( (j= elem_faces(elem1,i)) > num_face )
{
                          for (int nc=0; nc<nb_comp; nc++)
{
                              val = viscA(num_face,j,elem1,nu(elem1,nc));
                              if (val<0.) val=0.;
                              int n0=num_face*nb_comp+nc;
                              int j0=j*nb_comp+nc;
                              matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                              matrice(n0,j0)-=val*porosite_eventuelle(j);
                              matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                              matrice(j0,j0)+=val*porosite_eventuelle(j);
                            }
                        }
                    }
                }
            }
        }
      for (num_face=zone_VEF.premiere_face_int(); num_face<n1; num_face++)
        {
          elem1 = face_voisins(num_face,0);
          elem2 = face_voisins(num_face,1);
          for (i=0; i<nb_faces_elem; i++)
            {
              if ( (j=elem_faces(elem1,i)) > num_face )
                {
                  for (int nc=0; nc<nb_comp; nc++)
                    {
                      val = viscA(num_face,j,elem1,nu(elem1,nc));
                      if (val<0.) val=0.;
                      int n0=num_face*nb_comp+nc;
                      int j0=j*nb_comp+nc;
                      matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                      matrice(n0,j0)-=val*porosite_eventuelle(j);
                      matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                      matrice(j0,j0)+=val*porosite_eventuelle(j);
                    }
                }
              if (elem2!=-1)
                if ( (j=elem_faces(elem2,i)) > num_face )
                  {
                    for (int nc=0; nc<nb_comp; nc++)
                      {
                        val= viscA(num_face,j,elem2,nu(elem2,nc));
                        if (val<0.) val=0.;
                        int n0=num_face*nb_comp+nc;
                        int j0=j*nb_comp+nc;
                        matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                        matrice(n0,j0)-=val*porosite_eventuelle(j);
                        matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                        matrice(j0,j0)+=val*porosite_eventuelle(j);
                      }
                  }
            }
        }
      modifier_matrice_pour_periodique_apres_contribuer(matrice,equation());
    }
}
References Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), modif_par_porosite_si_flag(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), TRUSTTab< _TYPE_ >::nb_dim(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Zone_dis_base::nb_front_Cl(), new_jacobian_, Op_Diff_VEF_base::nu_, Front_VF::num_premiere_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, Op_Diff_VEF_base::remplir_nu(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Op_Diff_VEF_base::viscA(), and Zone_dis_base::zone().
Referenced by contribuer_a_avec().
ajouter_diffusion()
void Op_Diff_VEF_Face_Stab::ajouter_diffusion (const DoubleTab & Aij, const DoubleTab & inconnueTab, DoubleTab & resuTab) const protected
Definition at line 333 of file Op_Diff_VEF_Face_Stab.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  int nb_comp=1;
  if(resuTab.nb_dim()==2) nb_comp=resuTab.dimension(1);
  const DoubleVect& inconnue= inconnueTab;
  DoubleVect& resu= resuTab;
  int elem=0;
  int facei_loc=0,facei=0;
  int facej_loc=0,facej=0;
  int dim=0;
  double inc_i=0.;
  double inc_j=0.;
  double delta_ij=0.;
  double dij=0.;
  const IntTab& elem_faces=zone_VEF.elem_faces();
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
          {
            facej=elem_faces(elem,facej_loc);
            const double aij=Aij(elem,facei_loc,facej_loc);
            if (aij>0.)
              {
                dij=-aij;
                for (dim=0; dim<nb_comp; dim++)
                  {
                    inc_i=inconnue[facei*nb_comp+dim];
                    inc_j=inconnue[facej*nb_comp+dim];
                    delta_ij=dij*(inc_j-inc_i);
                    resu[facei*nb_comp+dim]+=delta_ij;
                    resu[facej*nb_comp+dim]-=delta_ij;
                  }
              }
          }
      }
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), Op_Diff_VEF_base::la_zone_vef, TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_operateur_centre()
void Op_Diff_VEF_Face_Stab::ajouter_operateur_centre (const DoubleTab & Aij, const DoubleTab & inconnueTab, DoubleTab & resuTab) const protected
Definition at line 285 of file Op_Diff_VEF_Face_Stab.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  int nb_comp=1;
  if(resuTab.nb_dim()==2) nb_comp=resuTab.dimension(1);
  const DoubleVect& inconnue = inconnueTab;
  DoubleVect& resu = resuTab;
  int elem=0;
  int facei_loc=0,facei=0;
  int facej_loc=0,facej=0;
  int dim=0;
  double inc_i=0.;
  double inc_j=0.;
  double delta_ij=0.;
  const IntTab& elem_faces=zone_VEF.elem_faces();
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
          {
            facej=elem_faces(elem,facej_loc);
            const double aij=Aij(elem,facei_loc,facej_loc);
            for (dim=0; dim<nb_comp; dim++)
              {
                inc_i=inconnue[facei*nb_comp+dim];
                inc_j=inconnue[facej*nb_comp+dim];
                delta_ij=aij*(inc_j-inc_i);
                resu[facei*nb_comp+dim]+=delta_ij;
                resu[facej*nb_comp+dim]-=delta_ij;
              }
          }
      }
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), Op_Diff_VEF_base::la_zone_vef, TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
calculer_coefficients()
void Op_Diff_VEF_Face_Stab::calculer_coefficients (const DoubleTab & nu, DoubleTab & Aij) const protected
Definition at line 527 of file Op_Diff_VEF_Face_Stab.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const DoubleVect& volumes=zone_VEF.volumes();
  double volume=0.;
  double signei=0.;
  double signej=0.;
  double psc=0.;
  double nu_elem=0.;
  int elem=0;
  int facei_loc=0,facei=0;
  int facej_loc=0,facej=0;
  int dim=0;
  assert(Aij.nb_dim()==3);
  assert(Aij.dimension(0)==nb_elem_tot);
  assert(Aij.dimension(1)==nb_faces_elem);
  assert(Aij.dimension(2)==nb_faces_elem);
  for (elem=0; elem<nb_elem_tot; elem++)
    {
      nu_elem=nu(elem);
      volume=1./volumes(elem);
      volume*=nu_elem;
      for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
        {
          facei=elem_faces(elem,facei_loc);
          signei=1.;
          if (face_voisins(facei,0)!=elem) signei=-1.;
          for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
            {
              facej=elem_faces(elem,facej_loc);
              signej=1.;
              if (face_voisins(facej,0)!=elem) signej=-1.;
              psc=0.;
              for (dim=0; dim<Objet_U::dimension; dim++)
                psc+=face_normales(facei,dim)*face_normales(facej,dim);
              psc*=signei*signej;
              psc*=volume;
              Aij(elem,facei_loc,facej_loc)=psc;
              Aij(elem,facej_loc,facei_loc)=psc;
            }
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Op_Diff_VEF_base::la_zone_vef, TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Ref_Zone_VEF::valeur(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by ajouter().
calculer_gradients()
double Op_Diff_VEF_Face_Stab::calculer_gradients (int facei, const DoubleTab & rij) const protected
Definition at line 589 of file Op_Diff_VEF_Face_Stab.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const IntTab& get_num_fac_loc=zone_VEF.get_num_fac_loc();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const DoubleVect& volumes=zone_VEF.volumes();
  double volume=0.;
  double signek=0.;
  double psc=0.;
  int elem=0;
  int elem_loc=0;
  int facei_loc=0;
  int facek_loc=0,facek=0;
  int dim=0;
  double mu_ij=0.;
  for (elem_loc=0; elem_loc<2; elem_loc++)
    {
      facei_loc=get_num_fac_loc(facei,elem_loc);
      elem=face_voisins(facei,elem_loc);
      if (elem!=-1)
        {
          volume+=volumes(elem);
          for (facek_loc=0; facek_loc<nb_faces_elem; facek_loc++)
            if (facek_loc!=facei_loc)
              {
                facek=elem_faces(elem,facek_loc);
                signek=1.;
                if (face_voisins(facek,0)!=elem) signek=-1.;
                psc=0.;
                for (dim=0; dim<Objet_U::dimension; dim++)
                  psc+=face_normales(facek,dim)*rij(dim);
                psc*=signek;
                if (psc<0.) psc*=-1.;
                mu_ij+=psc;
              }
        }
    }
  mu_ij/=volume;
  mu_ij*=2.;
  return mu_ij;
}
References Objet_U::dimension, Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Zone_VF::get_num_fac_loc(), Op_Diff_VEF_base::la_zone_vef, Zone::nb_faces_elem(), Ref_Zone_VEF::valeur(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by ajouter_antidiffusion().
calculer_max()
void Op_Diff_VEF_Face_Stab::calculer_max (const DoubleTab & inconnueTab, int & dim, DoubleTab & Maxima) const protected
Definition at line 734 of file Op_Diff_VEF_Face_Stab.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const int nb_faces_tot=zone_VEF.nb_faces_tot();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  int elem=0;
  int facei_loc=0,facei=0;
  int facej_loc=0,facej=0;
  int nb_comp = 1;
  if(inconnueTab.nb_dim()==2) nb_comp=inconnueTab.dimension(1);
  double inc_i=0.;
  double inc_j=0.;
  const DoubleVect& inconnue = inconnueTab;
  assert(Maxima.nb_dim()==1);
  assert(Maxima.dimension(0)==nb_faces_tot);
  assert(dim<nb_comp);
  for (facei=0; facei<nb_faces_tot; facei++)
    Maxima(facei)=inconnue[facei*nb_comp+dim];
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        inc_i=inconnue[facei*nb_comp+dim];
        double& maxi=Maxima(facei);
        for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
          {
            facej=elem_faces(elem,facej_loc);
            inc_j=inconnue[facej*nb_comp+dim];
            double& maxj=Maxima(facej);
            if (inc_j>maxi) maxi=inc_j;
            if (inc_i>maxj) maxj=inc_i;
          }
      }
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const int nb_bords=les_cl.size();
  int num1=0, num2=0;
  int n_bord=0;
  int ind_face=0;
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2 = le_bord.nb_faces_tot();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei=le_bord.num_face(ind_face);
              facej=le_bord.num_face(la_cl_perio.face_associee(ind_face));
              if (facei<facej)
                {
                  double& maxi=Maxima(facei);
                  double& maxj=Maxima(facej);
                  if (maxi>maxj) maxj=maxi;
                  if (maxj>maxi) maxi=maxj;
                }
            }
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), Periodique::face_associee(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter_antidiffusion().
calculer_min()
void Op_Diff_VEF_Face_Stab::calculer_min (const DoubleTab & inconnueTab, int & dim, DoubleTab & Minima) const protected
Definition at line 646 of file Op_Diff_VEF_Face_Stab.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const int nb_faces_tot=zone_VEF.nb_faces_tot();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  int elem=0;
  int facei_loc=0,facei=0;
  int facej_loc=0,facej=0;
  int nb_comp = 1;
  if(inconnueTab.nb_dim()==2) nb_comp=inconnueTab.dimension(1);
  double inc_i=0.;
  double inc_j=0.;
  const DoubleVect& inconnue= inconnueTab;
  assert(Minima.nb_dim()==1);
  assert(Minima.dimension(0)==nb_faces_tot);
  assert(dim<nb_comp);
  for (facei=0; facei<nb_faces_tot; facei++)
    Minima(facei)=inconnue[facei*nb_comp+dim];
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        inc_i=inconnue[facei*nb_comp+dim];
        double& mini=Minima(facei);
        for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
          {
            facej=elem_faces(elem,facej_loc);
            inc_j=inconnue[facej*nb_comp+dim];
            double& minj=Minima(facej);
            if (inc_j<mini) mini=inc_j;
            if (inc_i<minj) minj=inc_i;
          }
      }
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const int nb_bords=les_cl.size();
  int num1=0, num2=0;
  int n_bord=0;
  int ind_face=0;
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2 = le_bord.nb_faces_tot();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei=le_bord.num_face(ind_face);
              facej=le_bord.num_face(la_cl_perio.face_associee(ind_face));
              if (facei<facej)
                {
                  double& mini=Minima(facei);
                  double& minj=Minima(facej);
                  if (mini<minj) minj=mini;
                  if (minj<mini) mini=minj;
                }
            }
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), Periodique::face_associee(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter_antidiffusion().
completer()
void Op_Diff_VEF_Face_Stab::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Op_Diff_VEF_Face.
Definition at line 823 of file Op_Diff_VEF_Face_Stab.cpp.
{
  Op_Diff_VEF_Face::completer();
  {
    const Zone_VEF& zone_VEF=la_zone_vef.valeur();
    const Zone_Cl_VEF& zone_Cl_VEF=la_zcl_vef.valeur();
    const Conds_lim& les_cl=zone_Cl_VEF.les_conditions_limites();
    const int nb_bord=les_cl.size();
    const int nb_faces_tot=zone_VEF.nb_faces_tot();
    int ind_face=-1;
    is_dirichlet_faces_.resize(nb_faces_tot);
    is_dirichlet_faces_=0;
    for (int n_bord=0; n_bord<nb_bord; n_bord++)
      {
        const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
        const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
        int nb_faces_bord_tot=le_bord.nb_faces_tot();
        int face=-1;
        if ( (sub_type(Dirichlet,la_cl.valeur()))
             || (sub_type(Dirichlet_homogene,la_cl.valeur()))
           )
          for (ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
            {
              face = le_bord.num_face(ind_face);
              is_dirichlet_faces_(face)=1;
            }
      }
  }
}
References Op_Diff_VEF_Face::completer(), Cond_lim::frontiere_dis(), is_dirichlet_faces_, Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, TRUSTTab< _TYPE_ >::resize(), vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
contribuer_a_avec()
void Op_Diff_VEF_Face_Stab::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
on assemble la matrice.
Reimplemented from Op_Diff_VEF_Face.
Definition at line 65 of file Op_Diff_VEF_Face_Stab.h.
{
  if (!new_jacobian_)
    Op_Diff_VEF_Face::contribuer_a_avec(inco,matrice);
  else
    {
      const Champ_base& inconnue = equation().inconnue().valeur();
      const Nature_du_champ nature_champ = inconnue.nature_du_champ();
      if (nature_champ!=multi_scalaire)
        ajouter_contribution(inco, matrice);
      else
        ajouter_contribution_multi_scalaire(inco, matrice);
    }
}
References ajouter_contribution(), ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::contribuer_a_avec(), MorEqn::equation(), Equation_base::inconnue(), multi_scalaire, Field_base::nature_du_champ(), new_jacobian_, and Deriv_Champ_Inc_base::valeur().
cree_instance()
Objet_U * Op_Diff_VEF_Face_Stab::cree_instance () static
Definition at line 41 of file Op_Diff_VEF_Face_Stab.cpp.
{
duplique()
int Op_Diff_VEF_Face_Stab::duplique () const override virtual
Reimplemented from Op_Diff_VEF_Face.
Reimplemented in Op_Diff_VEF_Face_Stab_Var.
Definition at line 41 of file Op_Diff_VEF_Face_Stab.cpp.
{
get_info()
const Type_info * Op_Diff_VEF_Face_Stab::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_VEF_Face.
Reimplemented in Op_Diff_VEF_Face_Stab_Var.
Definition at line 41 of file Op_Diff_VEF_Face_Stab.cpp.
{
info()
const Type_info * Op_Diff_VEF_Face_Stab::info () static
Definition at line 41 of file Op_Diff_VEF_Face_Stab.cpp.
{
modifie_pour_Cl()
void Op_Diff_VEF_Face_Stab::modifie_pour_Cl (const DoubleTab & inconnue, DoubleTab & resu) const protected
Definition at line 182 of file Op_Diff_VEF_Face_Stab.cpp.
{
  const Zone_VEF& zone_VEF =  la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const DoubleVect& inconnueVect = inconnue;
  DoubleVect& resuVect = resu;
  const int nb_bords=les_cl.size();
  int nb_comp=1;
  if(resu.nb_dim()==2) nb_comp=resu.dimension(1);
  DoubleTab& tab_flux_bords = flux_bords_;
  tab_flux_bords.resize(zone_VEF.nb_faces_bord(),nb_comp);
  tab_flux_bords=0.;
  int num1=0, num2=0;
  int n_bord=0;
  int face=0;
  int face_associee=0;
  int ind_face=0;
  int dim=0;
  double surface=0.;
  double flux=0.;
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2 = le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              face_associee=le_bord.num_face(la_cl_perio.face_associee(ind_face));
              if (face<face_associee)
                for (dim=0; dim<nb_comp; dim++)
                  {
                    resuVect[face*nb_comp+dim]+=resuVect[face_associee*nb_comp+dim];
                    resuVect[face_associee*nb_comp+dim]=resuVect[face*nb_comp+dim];
                  }
            }
        }
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              surface=zone_VEF.surface(face);
              for (dim=0; dim<nb_comp; dim++)
                {
                  flux=la_cl_paroi.flux_impose(ind_face,dim)*surface;
                  resuVect[face*nb_comp+dim]-=flux;
                  tab_flux_bords(face,dim)=flux;
                }
            }
        }
      if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Echange_externe_impose& la_cl_paroi = ref_cast(Echange_externe_impose,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              surface=zone_VEF.surface(face);
              for (dim=0; dim<nb_comp; dim++)
                {
                  flux=la_cl_paroi.h_imp(ind_face,dim)*(la_cl_paroi.T_ext(ind_face,dim)-inconnueVect[face*nb_comp+dim])*surface;
                  resuVect[face*nb_comp+dim]-=flux;
                  tab_flux_bords(face,dim)=flux;
                }
            }
        }
      if (sub_type(Neumann_homogene,la_cl.valeur())
          || sub_type(Symetrie,la_cl.valeur())
          || sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              for (dim=0; dim<nb_comp; dim++)
                tab_flux_bords(face,dim)=0.;
            }
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Periodique::face_associee(), face_associee, Operateur_base::flux_bords_, Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Echange_impose_base::h_imp(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_ >::nb_dim(), Front_VF::nb_faces(), Zone_VF::nb_faces_bord(), Front_VF::num_face(), ref_cast, TRUSTTab< _TYPE_ >::resize(), vect_impl::size(), sub_type, Zone_VF::surface(), Echange_impose_base::T_ext(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
Referenced by ajouter().
printOn()
Sortie & Op_Diff_VEF_Face_Stab::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_VEF_Face.
Reimplemented in Op_Diff_VEF_Face_Stab_Var.
Definition at line 76 of file Op_Diff_VEF_Face_Stab.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Diff_VEF_Face_Stab::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_VEF_Face.
Reimplemented in Op_Diff_VEF_Face_Stab_Var.
Definition at line 84 of file Op_Diff_VEF_Face_Stab.cpp.
{
  Motcle motlu,accouverte="{",accfermee="}";
  Motcles les_mots(3);
  {
    les_mots[0]="standard";
    les_mots[1]="info";
    les_mots[2]="new_jacobian";
  }
  standard_=0;
  info_=0;
  new_jacobian_=0;
  s>>motlu;
  if (motlu!=accouverte)
    if (Process::je_suis_maitre())
      {
        Cerr<<"Error in Op_Diff_VEF_Face_Stab::readOn()"<<finl;
        Cerr<<"Option keywords must be preceded by an open brace"<<finl;
        Process::exit();
      }
  s>>motlu;
  while (motlu!=accfermee)
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          s>>standard_;
          break;
        case 1 :
          s>>info_;
          break;
        case 2 :
          s>>new_jacobian_;
          break;
        default :
          if (Process::je_suis_maitre())
            {
              Cerr<<"Error in Op_Diff_VEF_Face_Stab::readOn()"<<finl;
              Cerr<<"Word "<<motlu<<" is unknown"<<finl;
              Cerr<<"Known keywords are : "<<les_mots<<finl;
              Process::exit();
            }
          break;
        }
      s>>motlu;
    }
  return s;
}
References Cerr, Process::exit(), finl, info_, Process::je_suis_maitre(), new_jacobian_, Motcles::search(), and standard_.
self_cast() [1/2]
const Op_Diff_VEF_Face_Stab & Op_Diff_VEF_Face_Stab::self_cast (const Objet_U & r) static
Definition at line 41 of file Op_Diff_VEF_Face_Stab.cpp.
{
self_cast() [2/2]
Op_Diff_VEF_Face_Stab & Op_Diff_VEF_Face_Stab::self_cast (Objet_U & r) static
Definition at line 41 of file Op_Diff_VEF_Face_Stab.cpp.
{
taille_memoire()
unsigned Op_Diff_VEF_Face_Stab::taille_memoire () const override virtual
Reimplemented from Op_Diff_VEF_Face.
Reimplemented in Op_Diff_VEF_Face_Stab_Var.
Definition at line 41 of file Op_Diff_VEF_Face_Stab.cpp.
{
Member Data Documentation
info_
int Op_Diff_VEF_Face_Stab::info_ private
Definition at line 60 of file Op_Diff_VEF_Face_Stab.h.
Referenced by ajouter_antidiffusion(), and readOn().
info_obj
const Type_info Op_Diff_VEF_Face_Stab::info_obj static
Definition at line 34 of file Op_Diff_VEF_Face_Stab.h.
is_dirichlet_faces_
IntTab Op_Diff_VEF_Face_Stab::is_dirichlet_faces_ private
Definition at line 62 of file Op_Diff_VEF_Face_Stab.h.
Referenced by ajouter_antidiffusion(), and completer().
new_jacobian_
int Op_Diff_VEF_Face_Stab::new_jacobian_ private
Definition at line 61 of file Op_Diff_VEF_Face_Stab.h.
Referenced by ajouter_contribution(), ajouter_contribution_multi_scalaire(), contribuer_a_avec(), and readOn().
standard_
int Op_Diff_VEF_Face_Stab::standard_ private
Definition at line 59 of file Op_Diff_VEF_Face_Stab.h.
Referenced by ajouter(), and readOn().
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Diff_VEF_Face_Stab.h
src/VEF/Operateurs/Op_Diff_VEF_Face_Stab.cpp