TRUST: Eval_Grad_VDF_Face Class Reference
Eval_Grad_VDF_Face Class Reference
class Eval_Grad_VDF_Face
Evaluateur VDF pour le gradient
#include <Eval_Grad_VDF_Face.h>
Public Member Functions
Eval_Grad_VDF_Face ()
int calculer_arete_bord () const
int calculer_arete_fluide () const
int calculer_arete_paroi () const
int calculer_arete_paroi_fluide () const
int calculer_arete_symetrie () const
int calculer_arete_interne () const
int calculer_arete_mixte () const
int calculer_fa7_sortie_libre () const
int calculer_arete_periodicite () const
double flux_fa7_sortie_libre (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double flux_fa7_elem (const DoubleTab &, int, int, int) const
double flux_arete_interne (const DoubleTab &, int, int, int, int) const
double flux_arete_mixte (const DoubleTab &, int, int, int, int) const
double flux_arete_paroi (const DoubleTab &, int, int, int, int) const
double flux_arete_symetrie (const DoubleTab &, int, int, int, int) const
void flux_arete_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_paroi_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_periodicite (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_fa7_elem (const DoubleTab &, int, int, int, DoubleVect &flux) const
void flux_fa7_sortie_libre (const DoubleTab &, int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void flux_arete_interne (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_mixte (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_symetrie (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_paroi (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_paroi_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_periodicite (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
Detailed Description
class Eval_Grad_VDF_Face
Evaluateur VDF pour le gradient
See also:
Eval_Grad_VDF
Definition at line 40 of file Eval_Grad_VDF_Face.h.
Constructor & Destructor Documentation
Eval_Grad_VDF_Face::Eval_Grad_VDF_Face () [inline]
Definition at line 96 of file Eval_Grad_VDF_Face.h.
{}
Member Function Documentation
int Eval_Grad_VDF_Face::calculer_arete_bord () const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 101 of file Eval_Grad_VDF_Face.h.
{
  return 0;
}
int Eval_Grad_VDF_Face::calculer_arete_fluide () const [inline]
Definition at line 108 of file Eval_Grad_VDF_Face.h.
{
  return 0;
}
int Eval_Grad_VDF_Face::calculer_arete_interne () const [inline]
Definition at line 143 of file Eval_Grad_VDF_Face.h.
{
  return 0;
}
int Eval_Grad_VDF_Face::calculer_arete_mixte () const [inline]
Definition at line 151 of file Eval_Grad_VDF_Face.h.
{
  return 0;
}
int Eval_Grad_VDF_Face::calculer_arete_paroi () const [inline]
Definition at line 117 of file Eval_Grad_VDF_Face.h.
{
  return 0;
}
int Eval_Grad_VDF_Face::calculer_arete_paroi_fluide () const [inline]
Definition at line 126 of file Eval_Grad_VDF_Face.h.
{
  return 0;
}
int Eval_Grad_VDF_Face::calculer_arete_periodicite () const [inline]
Definition at line 167 of file Eval_Grad_VDF_Face.h.
{
  return 0;
}
int Eval_Grad_VDF_Face::calculer_arete_symetrie () const [inline]
Definition at line 135 of file Eval_Grad_VDF_Face.h.
{
  return 0;
}
int Eval_Grad_VDF_Face::calculer_fa7_sortie_libre () const [inline]
Definition at line 159 of file Eval_Grad_VDF_Face.h.
{
  return 1;
}
void Eval_Grad_VDF_Face::flux_arete_fluide (const DoubleTab & , int , int , int , int , double & , double &) const [inline]
Definition at line 177 of file Eval_Grad_VDF_Face.h.
{
  ;
}
void Eval_Grad_VDF_Face::flux_arete_fluide (const DoubleTab & , int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Definition at line 261 of file Eval_Grad_VDF_Face.h.
{
  ;
}
void Eval_Grad_VDF_Face::flux_arete_interne (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 271 of file Eval_Grad_VDF_Face.h.
{
  ;
}
double Eval_Grad_VDF_Face::flux_arete_interne (const DoubleTab & , int , int , int , int) const [inline]
Definition at line 187 of file Eval_Grad_VDF_Face.h.
{
  return 0;
}
void Eval_Grad_VDF_Face::flux_arete_mixte (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 281 of file Eval_Grad_VDF_Face.h.
{
  ;
}
double Eval_Grad_VDF_Face::flux_arete_mixte (const DoubleTab & , int , int , int , int) const [inline]
Definition at line 196 of file Eval_Grad_VDF_Face.h.
{
  return 0;
}
void Eval_Grad_VDF_Face::flux_arete_paroi (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 291 of file Eval_Grad_VDF_Face.h.
{
  ;
}
double Eval_Grad_VDF_Face::flux_arete_paroi (const DoubleTab & , int , int , int , int) const [inline]
Definition at line 205 of file Eval_Grad_VDF_Face.h.
{
  return 0;
}
void Eval_Grad_VDF_Face::flux_arete_paroi_fluide (const DoubleTab & , int , int , int , int , double & , double &) const [inline]
Definition at line 214 of file Eval_Grad_VDF_Face.h.
{
  ;
}
void Eval_Grad_VDF_Face::flux_arete_paroi_fluide (const DoubleTab & , int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Definition at line 301 of file Eval_Grad_VDF_Face.h.
{
  ;
}
void Eval_Grad_VDF_Face::flux_arete_periodicite (const DoubleTab & , int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Definition at line 310 of file Eval_Grad_VDF_Face.h.
{
  ;
}
void Eval_Grad_VDF_Face::flux_arete_periodicite (const DoubleTab & , int , int , int , int , double & , double &) const [inline]
Definition at line 223 of file Eval_Grad_VDF_Face.h.
{
  ;
}
double Eval_Grad_VDF_Face::flux_arete_symetrie (const DoubleTab & , int , int , int , int) const [inline]
Definition at line 232 of file Eval_Grad_VDF_Face.h.
{
  return 0;
}
void Eval_Grad_VDF_Face::flux_arete_symetrie (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 319 of file Eval_Grad_VDF_Face.h.
{
  ;
}
double Eval_Grad_VDF_Face::flux_fa7_elem (const DoubleTab & inco, int elem, int fac1, int) const [inline]
Definition at line 240 of file Eval_Grad_VDF_Face.h.
References Evaluateur_VDF::surface.
{
  return inco[elem]*surface(fac1);
}
void Eval_Grad_VDF_Face::flux_fa7_elem (const DoubleTab & inco, int elem, int fac1, int , DoubleVect & flux) const [inline]
Definition at line 328 of file Eval_Grad_VDF_Face.h.
References DoubleVect::size(), and Evaluateur_VDF::surface.
{
  for (int k=0; k<flux.size(); k++)
    flux(k) = inco(elem,k)*surface(fac1);
}
double Eval_Grad_VDF_Face::flux_fa7_sortie_libre (const DoubleTab & , int face, const Neumann_sortie_libre & la_cl, int num1) const [inline]
Definition at line 249 of file Eval_Grad_VDF_Face.h.
References Neumann::flux_impose(), and Evaluateur_VDF::surface.
{
  return (la_cl.flux_impose(face-num1)*surface(face));
}
void Eval_Grad_VDF_Face::flux_fa7_sortie_libre (const DoubleTab & , int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const [inline]
Definition at line 338 of file Eval_Grad_VDF_Face.h.
References Neumann::flux_impose(), DoubleVect::size(), and Evaluateur_VDF::surface.
{
  for (int k=0; k<flux.size(); k++)
    flux(k) = la_cl.flux_impose(face-num1,k)*surface(face);
}
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs/Eval_Grad_VDF_Face.h