TRUST: TRUSTLists< _TYPE_ > Class Template Reference
TRUSTLists< _TYPE_ > Class Template Reference
: Un tableau de listes de type IntList
#include <TRUSTLists.h>
Public Member Functions
virtual ~TRUSTLists ()
TRUSTLists ()
Construit un tableau vide de listes.
TRUSTLists (int i)
TRUSTLists (const TRUSTLists &vect)
Sortie & printOn (Sortie &s) const
Entree & readOn (Entree &is)
TRUSTLists & operator= (const TRUSTLists &)
Copie et affectation. Les anciennes donnees sont perdues.
const TRUSTList< _TYPE_ > & operator[] (int) const
Acces a la ieme liste du tableau.
TRUSTList< _TYPE_ > & operator[] (int)
void dimensionner (int)
Redimensionne un tableau de listes.
int size () const
retourne le nombre de listes dans le tableau
int search (const TRUSTList< _TYPE_ > &) const
Recherche d'une liste dans le tableau.
Protected Attributes
int sz
TRUSTList< _TYPE_ > * data
Detailed Description
template<typename _TYPE_>
class TRUSTLists< _TYPE_ >
: Un tableau de listes de type IntList
Definition at line 29 of file TRUSTLists.h.
Constructor & Destructor Documentation
~TRUSTLists()
template<typename _TYPE_ > virtual TRUSTLists< _TYPE_ >::~TRUSTLists () inline virtual
Definition at line 32 of file TRUSTLists.h.
  {
    if (sz)
      {
        assert(data);
        delete[] data;
      }
    else
      assert(data == 0);
  }
References TRUSTLists< _TYPE_ >::data, and TRUSTLists< _TYPE_ >::sz.
TRUSTLists() [1/3]
template<typename _TYPE_ > TRUSTLists< _TYPE_ >::TRUSTLists () inline
Construit un tableau vide de listes.
Definition at line 43 of file TRUSTLists.h.
TRUSTLists() [2/3]
template<typename _TYPE_ > TRUSTLists< _TYPE_ >::TRUSTLists (int i) inline
Definition at line 46 of file TRUSTLists.h.
                    : sz(i)
  {
    if (i == 0) data = 0;
    else
      {
        data = new TRUSTList<_TYPE_>[i];
        if (!data) throw_();
      }
  }
References TRUSTLists< _TYPE_ >::data, and throw_().
TRUSTLists() [3/3]
template<typename _TYPE_ > TRUSTLists< _TYPE_ >::TRUSTLists (const TRUSTLists< _TYPE_ > & vect) inline
Definition at line 57 of file TRUSTLists.h.
                                     : sz(vect.sz), data(new TRUSTList<_TYPE_>[vect.sz])
  {
    if (!data) throw_();
    int i = sz;
    if (i == 0) data = 0;
    else while (i--) data[i] = vect[i];
  }
References TRUSTLists< _TYPE_ >::data, TRUSTLists< _TYPE_ >::sz, and throw_().
Member Function Documentation
dimensionner()
template<typename _TYPE_ > void TRUSTLists< _TYPE_ >::dimensionner (int i) inline
Redimensionne un tableau de listes.
Definition at line 140 of file TRUSTLists.h.
{
  assert(sz == 0 && data == 0);
  sz = i;
  if (i == 0) data = 0;
  else
    {
      data = new TRUSTList<_TYPE_>[i];
      if (!data) throw_();
    }
}
References throw_().
Referenced by Op_Curl_VEFP1B::elements_pour_sommet().
operator=()
template<typename _TYPE_ > TRUSTLists< _TYPE_ > & TRUSTLists< _TYPE_ >::operator= (const TRUSTLists< _TYPE_ > & vect) inline
Copie et affectation. Les anciennes donnees sont perdues.
Definition at line 93 of file TRUSTLists.h.
{
  sz = vect.sz;
  if (data) delete[] data;
  if (sz)
    {
      data = new TRUSTList<_TYPE_>[sz];
      if (!data) throw_();
      int i = sz;
      while (i--) data[i] = vect[i];
    }
  else data = 0;
  return *this;
}
References TRUSTLists< _TYPE_ >::sz, and throw_().
operator[]() [1/2]
template<typename _TYPE_ > TRUSTList< _TYPE_ > & TRUSTLists< _TYPE_ >::operator[] (int i) inline
Definition at line 132 of file TRUSTLists.h.
{
  assert((i >= 0) && (i < sz));
  return data[i];
}
operator[]() [2/2]
template<typename _TYPE_ > const TRUSTList< _TYPE_ > & TRUSTLists< _TYPE_ >::operator[] (int i) const inline
Acces a la ieme liste du tableau.
Definition at line 125 of file TRUSTLists.h.
{
  assert((i >= 0) && (i < sz));
  return data[i];
}
printOn()
template<typename _TYPE_ > Sortie & TRUSTLists< _TYPE_ >::printOn (Sortie & s) const inline
Definition at line 65 of file TRUSTLists.h.
  {
    int i = sz;
    while (i--) data[i].printOn(s);
    return s << finl;
  }
References TRUSTLists< _TYPE_ >::data, finl, and TRUSTLists< _TYPE_ >::sz.
Referenced by IntListsListe::printOn().
readOn()
template<typename _TYPE_ > Entree & TRUSTLists< _TYPE_ >::readOn (Entree & is) inline
Definition at line 72 of file TRUSTLists.h.
{ return is; }
search()
template<typename _TYPE_ > int TRUSTLists< _TYPE_ >::search (const TRUSTList< _TYPE_ > & t) const inline
Recherche d'une liste dans le tableau.
Definition at line 111 of file TRUSTLists.h.
{
  int i = sz, retour = -1;
  while (i--)
    if (data[i] == t)
      {
        retour = i;
        i = 0;
      }
  return retour;
}
size()
template<typename _TYPE_ > int TRUSTLists< _TYPE_ >::size () const inline
retourne le nombre de listes dans le tableau
Definition at line 80 of file TRUSTLists.h.
References TRUSTLists< _TYPE_ >::sz.
Referenced by Partitionneur_base::corriger_multiperiodique(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Op_Curl_VEFP1B::elem_som_size(), VerifierCoin::interpreter_(), and Op_Diff_VEFP1NCP1B_Face::liste_face().
Member Data Documentation
data
template<typename _TYPE_ > TRUSTList<_TYPE_>* TRUSTLists< _TYPE_ >::data protected
Definition at line 85 of file TRUSTLists.h.
Referenced by TRUSTLists< _TYPE_ >::printOn(), TRUSTLists< _TYPE_ >::TRUSTLists(), and TRUSTLists< _TYPE_ >::~TRUSTLists().
sz
template<typename _TYPE_ > int TRUSTLists< _TYPE_ >::sz protected
Definition at line 84 of file TRUSTLists.h.
Referenced by TRUSTLists< _TYPE_ >::operator=(), TRUSTLists< _TYPE_ >::printOn(), TRUSTLists< _TYPE_ >::size(), TRUSTLists< _TYPE_ >::TRUSTLists(), and TRUSTLists< _TYPE_ >::~TRUSTLists().
The documentation for this class was generated from the following file:
src/Kernel/Math/TRUSTLists.h