TRUST: Postraitements Class Reference
Postraitements Class Reference
#include <Postraitements.h>
Public Member Functions
Postraitements ()
~Postraitements ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int lire_postraitements (Entree &is, const Motcle &motlu, const Probleme_base &mon_pb)
void postraiter ()
void traiter_postraitement ()
void mettre_a_jour (double temps)
void init ()
void finir ()
int sauvegarder (Sortie &os) const override
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
int reprendre (Entree &is) override
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
void completer ()
Public Member Functions inherited from List_Deriv_Postraitement_base
List_Deriv_Postraitement_base ()
~List_Deriv_Postraitement_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
List_Deriv_Postraitement_base (const Deriv_Postraitement_base &t)
List_Deriv_Postraitement_base (const List_Deriv_Postraitement_base &t)
Deriv_Postraitement_base & operator[] (int)
const Deriv_Postraitement_base & operator[] (int) const
Deriv_Postraitement_base & operator[] (const Nom &)
const Deriv_Postraitement_base & operator[] (const Nom &) const
Deriv_Postraitement_base & operator() (int i)
const Deriv_Postraitement_base & operator() (int i) const
Deriv_Postraitement_base & operator() (const Nom &n)
const Deriv_Postraitement_base & operator() (const Nom &n) const
Deriv_Postraitement_base & valeur ()
const Deriv_Postraitement_base & valeur () const
List_Deriv_Postraitement_base & operator= (const Deriv_Postraitement_base &t)
Deriv_Postraitement_base * operator-> ()
List_Deriv_Postraitement_base & operator= (const List_Deriv_Postraitement_base &)
List_Deriv_Postraitement_base & add (const List_Deriv_Postraitement_base &)
Deriv_Postraitement_base & add (const Deriv_Postraitement_base &)
List_Deriv_Postraitement_base & inserer (const List_Deriv_Postraitement_base &)
Deriv_Postraitement_base & inserer (const Deriv_Postraitement_base &)
void supprimer ()
List_Deriv_Postraitement_base & operator+= (const List_Deriv_Postraitement_base &)
List_Deriv_Postraitement_base & operator+= (const Deriv_Postraitement_base &)
Deriv_Postraitement_base & add_if_not (const Deriv_Postraitement_base &)
Deriv_Postraitement_base & add_if_not (const char *const)
List_Deriv_Postraitement_base & search (const Deriv_Postraitement_base &) const
List_Deriv_Postraitement_base & search (const char *const) const
List_Deriv_Postraitement_base & suivant ()
const List_Deriv_Postraitement_base & suivant () const
const List_Deriv_Postraitement_base & dernier () const
List_Deriv_Postraitement_base & dernier ()
List_Deriv_Postraitement_base & operator-= (const Deriv_Postraitement_base &)
int est_egal_a (const Objet_U &) const override
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
int contient (const Deriv_Postraitement_base &) const
int contient (const char *const) const
int rang (const Deriv_Postraitement_base &) const
void suppr (const Deriv_Postraitement_base &)
Public Member Functions inherited from liste
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
liste ()
Constructeur par defaut
Construit une liste vide.
liste (const liste &)
Constructeur
Ajoute les elements contenus dans la liste passe en parametre.
liste (const Objet_U &)
Constructeur
Construit une liste singleton.
~liste () override
Destructeur de liste.
int size () const
Renvoie la taille de la liste
Une liste vide est de taille nulle.
int rang (const char *const) const
Renvoie le rang d'une chaine de caracteres contenue dans la liste
Recherche un Objet_U de Nom ch.
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
void suppr (const char *const)
Supprime l'Objet de Nom ch contenu dans la liste.
int est_vide () const
Teste si la liste est vide.
int est_dernier () const
Teste si la liste comporte des elements suivants ou non.
Retourne 1 si la liste est vide.
void vide ()
Vide la liste.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Postraitements & self_cast (Objet_U &)
static const Postraitements & self_cast (const Objet_U &)
Static Public Member Functions inherited from List_Deriv_Postraitement_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static List_Deriv_Postraitement_base & self_cast (Objet_U &)
static const List_Deriv_Postraitement_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from liste
static Objet_U * cree_instance ()
static const Type_info * info ()
static liste & self_cast (Objet_U &)
static const liste & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from List_Deriv_Postraitement_base
static const Type_info info_obj
Static Public Attributes inherited from liste
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from List_Deriv_Postraitement_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
int est_egal_a (const List_Deriv_Postraitement_base &) const
Protected Member Functions inherited from liste
Sortie & printOn (Sortie &x) const override
Ecriture d'une liste sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une liste sur un flot d'entree.
Objet_U & operator() (int)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Objet_U & operator() (int) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Objet_U & operator() (const Nom &)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Objet_U & operator() (const Nom &) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Objet_U & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Objet_U & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
liste & operator+= (const Objet_U &)
Ajoute un Objet_U a la fin de la liste.
liste & operator+= (const liste &)
Ajoute une list d'Objet_U a la fin de la liste.
liste & operator-= (const Objet_U &)
Supprime un Objet_U de la liste
Affiche un message d'erreur si l'objet n'est pas trouve.
const liste & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
liste & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
Objet_U * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
const Objet_U * operator-> () const
Retourne un pointeur sur l'Objet_U premier element de la liste.
Objet_U & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Objet_U & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Objet_U & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Objet_U & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Objet_U & add (const Objet_U &)
Ajout d'un Objet_U a la liste.
Objet_U & add_deplace (DerObjU &)
Ajout d'un Objet_U a la liste
to_add est libere en sortie.
Objet_U & inserer (const Objet_U &)
Insertion d'un Objet_U dans la liste.
liste & add (const liste &)
Ajout d'une liste a la liste.
liste & inserer (const liste &)
Insertion d'une liste
NON CODE - SORT SYSTEMATIQUEMENT EN ERREUR.
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Objet_U & add_if_not (const Objet_U &)
Ajout d'un Objet_U a la liste ssi il n'existe pas deja.
liste & search (const Objet_U &) const
Recherche d'un Objet_U dans la liste.
liste & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
int contient (const Objet_U &) const
Verifie si un Objet_U appartient ou non a la liste.
int rang (const Objet_U &) const
Renvoie le rang d'un Objet_U dans la liste.
void suppr (const Objet_U &)
Supprime un Objet_U contenu dans la liste.
liste & operator= (const liste &)
Operateur d'affectation de liste.
const liste & dernier () const
Renvoie le dernier element de la liste.
liste & dernier ()
Renvoie le dernier element de la liste.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from liste
DerObjU data
liste * suivant_
Detailed Description
Definition at line 37 of file Postraitements.h.
Constructor & Destructor Documentation
Postraitements()
Postraitements::Postraitements ()
Definition at line 22 of file Postraitements.cpp.
~Postraitements()
Postraitements::~Postraitements ()
Definition at line 22 of file Postraitements.cpp.
Member Function Documentation
completer()
void Postraitements::completer ()
Definition at line 288 of file Postraitements.cpp.
{
  LIST_CURSEUR(DERIV(Postraitement_base)) curseur = *this;
  while(curseur)
    {
      Postraitement_base& post = curseur.valeur().valeur();
      post.completer();
      ++curseur;
    }
}
References Postraitement_base::completer(), DERIV, and LIST_CURSEUR.
Referenced by Probleme_base::completer().
cree_instance()
Objet_U * Postraitements::cree_instance () static
Definition at line 22 of file Postraitements.cpp.
duplique()
int Postraitements::duplique () const override virtual
Reimplemented from List_Deriv_Postraitement_base.
Definition at line 22 of file Postraitements.cpp.
finir()
void Postraitements::finir ()
Definition at line 252 of file Postraitements.cpp.
{
  LIST_CURSEUR(DERIV(Postraitement_base)) curseur = *this;
  while(curseur)
    {
      Postraitement_base& post = curseur.valeur().valeur();
      post.finir();
      ++curseur;
    }
}
References DERIV, Postraitement_base::finir(), and LIST_CURSEUR.
Referenced by Probleme_base::finir().
get_info()
const Type_info * Postraitements::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from List_Deriv_Postraitement_base.
Definition at line 22 of file Postraitements.cpp.
info()
const Type_info * Postraitements::info () static
Definition at line 22 of file Postraitements.cpp.
init()
void Postraitements::init ()
Definition at line 241 of file Postraitements.cpp.
{
  LIST_CURSEUR(DERIV(Postraitement_base)) curseur = *this;
  while(curseur)
    {
      Postraitement_base& post = curseur.valeur().valeur();
      post.init();
      ++curseur;
    }
}
References DERIV, Postraitement_base::init(), and LIST_CURSEUR.
Referenced by Probleme_base::init_postraitements().
lire_postraitements()
int Postraitements::lire_postraitements (Entree & is, const Motcle & motlu, const Probleme_base & mon_pb)
Definition at line 95 of file Postraitements.cpp.
{
  Motcles motcles(4);
  motcles[0] = "Postraitement|Post_processing";
  motcles[1] = "Postraitements|Post_processings";
  motcles[2] = "liste_postraitements";
  motcles[3] = "liste_de_postraitements";
  int lerang = motcles.search(motlu);
// a cause du cas Liste_Postraitements (rang=2)
// => obligation de creer la liste de nom de fichier associes au post
  LIST(Nom) list_nom_post;
  int compteur = 0 ;
  if (lerang == 0)
    {
// Creation et lecture d'un postraitement unique standard
      DERIV(Postraitement_base) & post = add( DERIV(Postraitement_base)() );
      post.typer("Postraitement");
      post.valeur().associer_nom_et_pb_base("neant", mon_pb);
      is >> post.valeur();
    }
  else if (lerang == 1 || lerang == 2 || lerang == 3 )
    {
// Lecture d'une liste
// Lire l'accolade
      Nom post_which_contains_statistic("");
      Motcle motlu2;
      is >> motlu2;
      if (motlu2 != "{")
        {
          Cerr << "Error while reading the list of Postraitements," << finl;
          Cerr << " we expected a {" << finl;
          exit();
        }
      is >> motlu2;
      while (motlu2 != "}")
        {
          Motcle type, nom_du_post;
          switch (lerang)
            {
            case 1:
              {
                type = "Postraitement";
                nom_du_post = motlu2;
                break;
              }
            case 2:
              {
                Cerr<<" Warning liste_postraitements obsolete option" <<finl;
// Le premier mot est le type, le deuxieme est le nom
                type = motlu2;
                is >> nom_du_post;
                break;
              }
            case 3:
              {
                nom_du_post = motlu2;
                is >> type ;
                break;
              }
            default:
              {
                Cerr<< "Error in Postraitements"<<finl;
                exit();
              }
            }
          list_nom_post.add_if_not(nom_du_post);
          DERIV(Postraitement_base) & post = add( DERIV(Postraitement_base)() );
          post.typer(type);
          post.valeur().associer_nom_et_pb_base(nom_du_post, mon_pb);
          is >> post.valeur();
          /*
          // Check if statistic block is defined several times
          // Not supported yet cause, backup files will contains several
          // statistic blocks with same name BUT different contents -> error
          // We should change the .sauv format and generalize the statistic block name
          if (ref_cast(Postraitement,post.valeur()).stat_demande() || ref_cast(Postraitement,post.valeur()).stat_demande_definition_champs())
          {
            if (post_which_contains_statistic!="")
            {
               Cerr << "Several statistic blocks in a same problem is not supported yet." << finl;
               Cerr << "It seems you defined statistics in the post processing block " << nom_du_post << finl;
               Cerr << "whereas some statistics has been defined already the in the block " << post_which_contains_statistic << finl;
               Cerr << "Check your data file by regrouping statistics in a same prostprocessing block." << finl;
               exit();
            }
                  post_which_contains_statistic=nom_du_post;
                }
          */
          is >> motlu2;
          compteur++;
        }
// test de verification pour eviter ecrasement de donnnes au fur et a mesure de leur enregistrement
// a cause du cas Liste_Postraitements => obligation de creer la liste de nom de fichier associes au post
      if (list_nom_post.size()!=compteur)
        {
          Cerr << "You can use the same name for the storing data file in two different blocks of post-processing" << finl;
          Cerr << "Check your datafile." << finl;
          exit();
        }
    }
  else
    {
      return 0;
    }
  return 1;
}
References List_Deriv_Postraitement_base::add(), Cerr, compteur, DERIV, Process::exit(), finl, LIST, and Motcles::search().
Referenced by Probleme_base::readOn().
mettre_a_jour()
void Postraitements::mettre_a_jour (double temps)
Definition at line 230 of file Postraitements.cpp.
{
  LIST_CURSEUR(DERIV(Postraitement_base)) curseur = *this;
  while(curseur)
    {
      Postraitement_base& post = curseur.valeur().valeur();
      post.mettre_a_jour(temps);
      ++curseur;
    }
}
References DERIV, LIST_CURSEUR, and Postraitement_base::mettre_a_jour().
Referenced by Probleme_base::mettre_a_jour(), Pb_Dilatable_base::mettre_a_jour(), and Probleme_base::postraiter().
postraiter()
void Postraitements::postraiter ()
< On force le postraitement
Definition at line 208 of file Postraitements.cpp.
{
  LIST_CURSEUR(DERIV(Postraitement_base)) curseur = *this;
  while(curseur)
    {
      Postraitement_base& post = curseur.valeur().valeur();
      post.postraiter(1); //!< On force le postraitement
      ++curseur;
    }
}
References DERIV, LIST_CURSEUR, and Postraitement_base::postraiter().
Referenced by Probleme_base::postraiter().
printOn()
Sortie & Postraitements::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from List_Deriv_Postraitement_base.
Definition at line 31 of file Postraitements.cpp.
{
  CONST_LIST_CURSEUR(DERIV(Postraitement_base)) curseur = *this;
  while(curseur)
    {
      const Postraitement_base& post = curseur.valeur().valeur();
      s << post;
      ++curseur;
    }
  return s;
}
References CONST_LIST_CURSEUR, and DERIV.
readOn()
Entree & Postraitements::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from List_Deriv_Postraitement_base.
Definition at line 24 of file Postraitements.cpp.
{
  Cerr << "Postraitements::readOn should not be used" << finl;
  exit();
  return s;
}
References Cerr, Process::exit(), and finl.
reprendre()
int Postraitements::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 276 of file Postraitements.cpp.
{
  LIST_CURSEUR(DERIV(Postraitement_base)) curseur = *this;
  while(curseur)
    {
      Postraitement_base& post = curseur.valeur().valeur();
      post.reprendre(is);
      ++curseur;
    }
  return 1;
}
References DERIV, LIST_CURSEUR, and Postraitement_base::reprendre().
Referenced by Probleme_base::reprendre().
sauvegarder()
int Postraitements::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 263 of file Postraitements.cpp.
{
  int bytes = 0;
  CONST_LIST_CURSEUR(DERIV(Postraitement_base)) curseur = *this;
  while(curseur)
    {
      const Postraitement_base& post = curseur.valeur().valeur();
      bytes += post.sauvegarder(os);
      ++curseur;
    }
  return bytes;
}
References CONST_LIST_CURSEUR, DERIV, and Postraitement_base::sauvegarder().
Referenced by Probleme_base::sauvegarder().
self_cast() [1/2]
const Postraitements & Postraitements::self_cast (const Objet_U & r) static
Definition at line 22 of file Postraitements.cpp.
self_cast() [2/2]
Postraitements & Postraitements::self_cast (Objet_U & r) static
Definition at line 22 of file Postraitements.cpp.
taille_memoire()
unsigned Postraitements::taille_memoire () const override virtual
Reimplemented from List_Deriv_Postraitement_base.
Definition at line 22 of file Postraitements.cpp.
traiter_postraitement()
void Postraitements::traiter_postraitement ()
< Postraitement si intervalle de temps ecoule
Definition at line 219 of file Postraitements.cpp.
{
  LIST_CURSEUR(DERIV(Postraitement_base)) curseur = *this;
  while(curseur)
    {
      Postraitement_base& post = curseur.valeur().valeur();
      post.postraiter(0); //!< Postraitement si intervalle de temps ecoule
      ++curseur;
    }
}
References DERIV, LIST_CURSEUR, and Postraitement_base::postraiter().
Referenced by Probleme_base::postraiter().
Member Data Documentation
info_obj
const Type_info Postraitements::info_obj static
Definition at line 39 of file Postraitements.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Postraitements.h
src/Kernel/Framework/Postraitements.cpp