TRUST: Discretiser_domaine Class Reference
Discretiser_domaine Class Reference
class Discretiser_domaine
discrtise le domaine
utile pour tester les geometries
#include <Discretiser_domaine.h>
Public Member Functions
Discretiser_domaine ()
~Discretiser_domaine ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Discretiser_domaine & self_cast (Objet_U &)
static const Discretiser_domaine & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
class Discretiser_domaine
discrtise le domaine
utile pour tester les geometries
Definition at line 36 of file Discretiser_domaine.h.
Constructor & Destructor Documentation
Discretiser_domaine::Discretiser_domaine ()
Definition at line 26 of file Discretiser_domaine.cpp.
Discretiser_domaine::~Discretiser_domaine ()
Definition at line 26 of file Discretiser_domaine.cpp.
Member Function Documentation
Objet_U * Discretiser_domaine::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 26 of file Discretiser_domaine.cpp.
int Discretiser_domaine::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 26 of file Discretiser_domaine.cpp.
const Type_info * Discretiser_domaine::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Discretiser_domaine.cpp.
const Type_info * Discretiser_domaine::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Discretiser_domaine.cpp.
Entree & Discretiser_domaine::interpreter_ (Entree & is) [virtual]
Implements Interprete_geometrique_base.
Definition at line 38 of file Discretiser_domaine.cpp.
References Interprete_geometrique_base::associer_domaine(), Zone_dis_base::associer_zone(), Zone_VF::discretiser(), Interprete_geometrique_base::domaine(), and Domaine::zone().
{
  associer_domaine(is);
  Domaine& dom=domaine();
  Zone_VF_inst zone_dis;
  zone_dis.associer_zone(dom.zone(0));
  zone_dis.discretiser();
  return is;
}
Sortie & Discretiser_domaine::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Discretiser_domaine.cpp.
{
  return Interprete::printOn(os);
}
Entree & Discretiser_domaine::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 33 of file Discretiser_domaine.cpp.
{
  return Interprete::readOn(is);
}
Discretiser_domaine & Discretiser_domaine::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Discretiser_domaine.cpp.
const Discretiser_domaine & Discretiser_domaine::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Discretiser_domaine.cpp.
unsigned Discretiser_domaine::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 26 of file Discretiser_domaine.cpp.
Member Data Documentation
const Type_info Discretiser_domaine::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 38 of file Discretiser_domaine.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Discretiser_domaine.h
src/Kernel/Geometrie/Discretiser_domaine.cpp