TRUST: DoubleList Class Reference
DoubleList Class Reference
Classe qui sert a representer une liste de reels double
precision. On ne peut pas utiliser la classe container
List avec des objets du type double car double est un type
predefini du C++ qui ne possede pas les fonctions exigees
par List< >.
#include <DoubleList.h>
Public Member Functions
DoubleList (const DoubleList &)
Constructeur par copie.
DoubleList ()
Construit une liste vide.
Sortie & printOn (Sortie &os) const
Ecriture d'une liste sur un flot de sortie
les elements separes par des virgules figurent entre des accolades.
Entree & readOn (Entree &is)
Lecture d'une liste sur un flot d'entree
les elements separes par des virgules figurent entre des accolades.
int size () const
Renvoie la taille de la liste
Une liste vide est de taille nulle.
int contient (double) const
Verifie si un element appartient ou non a la liste.
int rang (double) const
renvoie le rang d'un element dans la liste
si un element apparait plusieurs fois, renvoie le rang du premier.
DoubleListElem & dernier ()
Renvoie le dernier element de la liste.
const DoubleListElem & dernier () const
Renvoie le dernier element de la liste.
double & operator[] (int)
Operateur d'acces au ieme int de la liste.
const double & operator[] (int) const
Operateur d'acces au ieme int de la liste.
DoubleList & add (double)
insertion en queue
DoubleList & add_if_not (double)
Ajout d'un element a la liste ssi il n'existe pas deja.
DoubleList & operator= (const DoubleList &)
Affectation
Les elements sont copies.
void suppr (double)
Supprime un element contenu dans la liste.
void vide ()
Vide la liste.
void calcule_min_max ()
Private Attributes
DoubleListElem * dernier_
double min_data
double max_data
Friends
class DoubleList_Curseur
int operator== (const DoubleList &, const DoubleList &)
Operateur de comparaison de deux listes.
Detailed Description
Classe qui sert a representer une liste de reels double
precision. On ne peut pas utiliser la classe container
List avec des objets du type double car double est un type
predefini du C++ qui ne possede pas les fonctions exigees
par List< >.
Definition at line 45 of file DoubleList.h.
Constructor & Destructor Documentation
DoubleList::DoubleList (const DoubleList & a_list)
Constructeur par copie.
Definition at line 114 of file DoubleList.cpp.
References DoubleListElem::data, dernier_, DoubleListElem::DoubleListElem(), DoubleListElem::est_vide(), max_data, min_data, next(), and DoubleListElem::suivant_.
                                               : DoubleListElem()
{
  min_data=a_list.min_data;
  max_data=a_list.max_data;
  if(a_list.est_vide() )
    {
      suivant_=this;
    }
  else
    {
      data=a_list.data;
      dernier_=this;
      if(a_list.suivant_)
        {
          DoubleListElem* next = new DoubleListElem(*a_list.suivant_); //Recursif !!
          suivant_ = next;
        }
      else
        suivant_ =0;
    }
}
DoubleList::DoubleList () [inline]
Construit une liste vide.
Definition at line 116 of file DoubleList.h.
References dernier_.
                              :
  DoubleListElem(),min_data(DMAXFLOAT),max_data(-DMAXFLOAT)
{
  dernier_=this;
}
Member Function Documentation
DoubleList & DoubleList::add (double double_to_add)
insertion en queue
Returns:
DoubleList&
Signification: *this
Contraintes:
Reimplemented from DoubleListElem.
Definition at line 236 of file DoubleList.cpp.
References DoubleListElem::add(), DoubleListElem::data, dernier(), dernier_, DoubleListElem::DoubleListElem(), DoubleListElem::est_dernier(), DoubleListElem::est_vide(), max_data, min_data, next(), DoubleListElem::suivant(), and DoubleListElem::suivant_.
Referenced by add_if_not(), operator+(), operator=(), Equation_base::preparer_calcul(), and readOn().
{
  if (double_to_add<min_data)
    min_data=double_to_add;
  if (double_to_add>max_data)
    max_data=double_to_add;
  if( est_vide())
    {
      data=double_to_add;
      suivant_=0;
      return *this;
    }
  else
    {
      if(est_dernier())
        {
          DoubleListElem* next=new DoubleListElem(double_to_add);
          suivant_ = next;
          dernier_ = next;
        }
      else
        {
          dernier().add(double_to_add);
          dernier_ = &dernier_->suivant();
        }
      return *this;
    }
}
DoubleList & DoubleList::add_if_not (double x)
Ajout d'un element a la liste ssi il n'existe pas deja.
Returns:
DoubleList&
Signification: *this
Contraintes:
Definition at line 308 of file DoubleList.cpp.
References add(), and contient().
Referenced by operator+().
{
  if (!contient(x))
    return add(x);
  else
    return *this;
}
void DoubleList::calcule_min_max ()
Definition at line 522 of file DoubleList.cpp.
References DMAXFLOAT, max_data, min_data, and DoubleList_Curseur::valeur().
Referenced by suppr(), and vide().
{
  min_data=DMAXFLOAT;
  max_data=-DMAXFLOAT;
  DoubleList_Curseur curseur=*this;
  while(curseur)
    {
      double la_valeur=curseur.valeur();
      if (la_valeur<min_data)
        min_data=la_valeur;
      if (la_valeur>max_data)
        max_data=la_valeur;
      ++curseur;
    }
}
int DoubleList::contient (double x) const
Verifie si un element appartient ou non a la liste.
Returns:
int
Signification: 1 si la liste contient l'element, 0 sinon
Contraintes:
Definition at line 331 of file DoubleList.cpp.
References DoubleListElem::est_vide(), max_data, min_data, and DoubleList_Curseur::valeur().
Referenced by add_if_not().
{
  if(est_vide() || x>max_data || x<min_data)
    return 0;
  DoubleList_Curseur curseur(*this);
  while(curseur)
    {
      if (curseur.valeur()==x)
        return 1;
      ++curseur;
    }
  return 0;
}
const DoubleListElem & DoubleList::dernier () const
Renvoie le dernier element de la liste.
Returns:
const DoubleList&
Signification: le dernier element de la liste
Contraintes:
Definition at line 184 of file DoubleList.cpp.
References dernier_.
{
  return *dernier_;
  /*  if (est_dernier()) return *this;
      DoubleList_Curseur curseur(*this);
      while(curseur)
      if (curseur.list().est_dernier()) break;
      else ++curseur;
      return curseur.list(); */
}
DoubleListElem & DoubleList::dernier ()
Renvoie le dernier element de la liste.
Returns:
DoubleList&
Signification: le dernier element de la liste
Contraintes:
Definition at line 209 of file DoubleList.cpp.
References dernier_.
Referenced by add().
{
  return *dernier_;
  /*
    if (est_dernier()) return *this;
    DoubleList_Curseur curseur(*this);
    while(curseur)
    if (curseur.list().est_dernier()) break;
    else ++curseur;
    return curseur.list();
  */
}
DoubleList & DoubleList::operator= (const DoubleList & a_list)
Affectation
Les elements sont copies.
Returns:
DoubleList&
Signification: *this
Contraintes:
Definition at line 151 of file DoubleList.cpp.
References add(), DoubleListElem::est_vide(), DoubleListElem::suivant_, DoubleList_Curseur::valeur(), and vide().
{
  if(a_list.est_vide())
    {
      suivant_=this;
    }
  else
    {
      vide();
      DoubleList_Curseur curseur(a_list);
      while(curseur)
        {
          add(curseur.valeur());
          ++curseur;
        }
    }
  return *this;
}
const double & DoubleList::operator[] (int i) const
Operateur d'acces au ieme int de la liste.
Returns:
const double&
Signification: le ieme element de la liste
Contraintes:
Definition at line 419 of file DoubleList.cpp.
References Cerr, Process::exit(), finl, and DoubleList_Curseur::valeur().
{
  DoubleList_Curseur curseur(*this);
  while(curseur && i--)
    ++curseur;
  if(i!=-1)
    {
      Cerr << "Overflow list " << finl;
      Process::exit();
    }
  return curseur.valeur();
}
double & DoubleList::operator[] (int i)
Operateur d'acces au ieme int de la liste.
Returns:
double&
Signification: le ieme element de la liste
Contraintes:
Definition at line 392 of file DoubleList.cpp.
References Cerr, Process::exit(), finl, and DoubleList_Curseur::valeur().
{
  DoubleList_Curseur curseur(*this);
  while(curseur && i--)
    ++curseur;
  if(i!=-1)
    {
      Cerr << "Overflow list " << finl;
      Process::exit();
    }
  return curseur.valeur();
}
Sortie & DoubleList::printOn (Sortie & os) const
Ecriture d'une liste sur un flot de sortie
les elements separes par des virgules figurent entre des accolades.
Returns:
Sortie&
Signification: le flot d'entree modifie
Contraintes:
Definition at line 44 of file DoubleList.cpp.
References DoubleListElem::est_dernier(), DoubleList_Curseur::list(), and DoubleList_Curseur::valeur().
Referenced by DoubleLists::printOn().
{
  DoubleList_Curseur curseur(*this);
  Nom accouverte = "{";
  Nom accfermee = "}";
  Nom virgule = ",";
  os << accouverte << " " ;
  while(curseur)
    {
// if(est_dernier()) GF sinon on a une virgule de trop
      if(curseur.list().est_dernier())
        os << curseur.valeur() << " " ;
      else
        os << curseur.valeur() << " " << virgule << " " ;
      ++curseur;
    }
  os << accfermee;
  return os;
}
int DoubleList::rang (double x) const
renvoie le rang d'un element dans la liste
si un element apparait plusieurs fois, renvoie le rang du premier.
Returns:
int
Signification: le rang du premier element de la liste valant i,
-1 si la liste ne contient pas i.
Contraintes:
Definition at line 362 of file DoubleList.cpp.
References compteur, DoubleListElem::est_vide(), max_data, min_data, and DoubleList_Curseur::valeur().
{
  if(est_vide() || x>max_data || x<min_data)
    return -1;
  int compteur=0;
  DoubleList_Curseur curseur(*this);
  while(curseur)
    {
      if (curseur.valeur()==x)
        return compteur;
      ++compteur;
      ++curseur;
    }
  return -1;
}
Entree & DoubleList::readOn (Entree & is)
Lecture d'une liste sur un flot d'entree
les elements separes par des virgules figurent entre des accolades.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Definition at line 81 of file DoubleList.cpp.
References add().
{
  Nom accouverte = "{";
  Nom accfermee = "}";
  Nom virgule = ",";
  Nom nom;
  double t;
  is >> nom;
  assert(nom==accouverte);
  while(nom != accfermee)
    {
      is >> t;
      add(t);
      is >> nom;
      assert((nom==accfermee)||(nom==virgule));
    }
  return is ;
}
int DoubleList::size () const
Renvoie la taille de la liste
Une liste vide est de taille nulle.
Returns:
int
Signification: nombre d'elements de la liste
Contraintes:
Definition at line 280 of file DoubleList.cpp.
References DoubleListElem::est_vide().
{
  if(est_vide())
    return 0;
  int i=0;
  DoubleList_Curseur curseur(*this);
  while(curseur)
    {
      ++i;
      ++curseur;
    }
  return i;
}
void DoubleList::suppr (double obj)
Supprime un element contenu dans la liste.
Definition at line 479 of file DoubleList.cpp.
References calcule_min_max(), Cerr, DoubleListElem::data, dernier_, finl, DoubleList_Curseur::list(), next(), DoubleListElem::suivant(), DoubleListElem::suivant_, DoubleList_Curseur::valeur(), and DoubleListElem::valeur().
Referenced by operator+().
{
  if(valeur()==obj)
    {
      if(suivant_)
        {
          DoubleListElem* next=suivant_;
          suivant_=next->suivant_;
          data=next->valeur();
          next->suivant_=0;
          delete next;
        }
      else
        {
          suivant_=this;
          dernier_=this;
        }
      calcule_min_max();
      return;
    }
  DoubleList_Curseur curseur_pre=*this;
  DoubleList_Curseur curseur=*suivant_;
  while(curseur)
    {
      if(curseur.valeur()==obj)
        {
          DoubleListElem* next=&curseur_pre.list().suivant();
          curseur_pre.list().suivant_=curseur.list().suivant_;
          if (next->suivant_==0)
            dernier_=&curseur_pre.list();
          else
            next->suivant_=0;
          delete next;
          calcule_min_max();
          return ;
        }
      ++curseur;
      ++curseur_pre;
    }
  Cerr << "WARNING during deletion of an element in a list " << finl;
  Cerr << "One has not found object == : " << obj << finl;
}
void DoubleList::vide ()
Vide la liste.
Definition at line 552 of file DoubleList.cpp.
References calcule_min_max(), dernier_, DoubleListElem::est_vide(), and DoubleListElem::suivant_.
Referenced by operator+(), and operator=().
{
  if (!est_vide())
    if(suivant_)
      delete suivant_;
  suivant_=this;
  dernier_=this;
  calcule_min_max();
}
Friends And Related Function Documentation
friend class DoubleList_Curseur [friend]
Definition at line 49 of file DoubleList.h.
int operator== (const DoubleList & list1, const DoubleList & list2) [friend]
Operateur de comparaison de deux listes.
Returns:
int
Signification: 1 si les listes sont egales, 0 sinon
Contraintes:
Definition at line 451 of file DoubleList.cpp.
{
  int retour=1;
  if(list1.data != list2.data)
    retour= 0;
  if( (!list1.est_dernier()) && (list2.est_dernier()) )
    retour= 0;
  if( (list1.est_dernier()) && (!list2.est_dernier()) )
    retour= 0;
  if( (!list1.est_dernier()) && (!list2.est_dernier()) )
    retour= (*list1.suivant_ == *list2.suivant_);
  return retour;
}
Member Data Documentation
DoubleListElem* DoubleList::dernier_ [private]
Definition at line 73 of file DoubleList.h.
Referenced by add(), dernier(), DoubleList(), suppr(), and vide().
double DoubleList::max_data [private]
Definition at line 75 of file DoubleList.h.
Referenced by add(), calcule_min_max(), contient(), DoubleList(), and rang().
double DoubleList::min_data [private]
Definition at line 74 of file DoubleList.h.
Referenced by add(), calcule_min_max(), contient(), DoubleList(), and rang().
The documentation for this class was generated from the following files:
src/Kernel/Math/DoubleList.h
src/Kernel/Math/DoubleList.cpp