TRUST: Terme_Source_Qdm_lambdaup_VEF_Face Class Reference
Terme_Source_Qdm_lambdaup_VEF_Face Class Reference
class Terme_Source_Qdm_lambdaup_VEF_Face
#include <Terme_Source_Qdm_lambdaup_VEF_Face.h>
Public Member Functions
Terme_Source_Qdm_lambdaup_VEF_Face ()
~Terme_Source_Qdm_lambdaup_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &) override
DoubleTab & ajouter (DoubleTab &) const override
DoubleTab & calculer (DoubleTab &) const override
void mettre_a_jour (double) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
double norme_H1 (const DoubleTab &) const
double norme_L2 (const DoubleTab &) const
double norme_L2_H1 (const DoubleTab &) const
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don & source () const
Renvoie le champ donne representant le terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Terme_Source_Qdm_lambdaup_VEF_Face & self_cast (Objet_U &)
static const Terme_Source_Qdm_lambdaup_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double lambda
double lambda_max
double lambda_min
double cible
Ref_Champ_P1NC la_vitesse
Ref_Zone_VEF la_zone_VEF
Ref_Zone_Cl_VEF la_zone_Cl_VEF
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Protected Attributes inherited from Terme_Source_Qdm
Champ_Don la_source
Detailed Description
class Terme_Source_Qdm_lambdaup_VEF_Face
See also
Source_base
Definition at line 36 of file Terme_Source_Qdm_lambdaup_VEF_Face.h.
Constructor & Destructor Documentation
Terme_Source_Qdm_lambdaup_VEF_Face()
Terme_Source_Qdm_lambdaup_VEF_Face::Terme_Source_Qdm_lambdaup_VEF_Face ()
Definition at line 24 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
~Terme_Source_Qdm_lambdaup_VEF_Face()
Terme_Source_Qdm_lambdaup_VEF_Face::~Terme_Source_Qdm_lambdaup_VEF_Face ()
Definition at line 24 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
Member Function Documentation
ajouter()
DoubleTab & Terme_Source_Qdm_lambdaup_VEF_Face::ajouter (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 155 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
{
  static double rapport_old=1.;
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const DoubleVect& volumes_entrelaces=zone_VEF.volumes_entrelaces();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const DoubleTab& vitesse=la_vitesse.valeur().valeurs();
  DoubleTab ubar(vitesse);
  DoubleTab uprime(vitesse);
  const int nb_faces = zone_VEF.nb_faces();
  int face, k;
  int nb_comp = resu.line_size();
  la_vitesse.valeur().filtrer_L2(ubar);
  uprime-=ubar;
  double normbar=mp_norme_vect(ubar);
  double normprim=mp_norme_vect(uprime);
// double rapport=normbar/(normprim+DMINFLOAT) ;
  double rapport=(normprim!=0?normbar/normprim:0);
  double& l=lambda;
  if( (rapport < cible) && (rapport<rapport_old) ) l*=2.;
  if( (rapport < cible) && (rapport>rapport_old) ) l*=1.1;
  if( (rapport>cible) && (rapport>rapport_old)  )  l*=0.95;
  l=std::min(lambda, lambda_max);
  l=std::max(lambda_min, lambda);
  if (Process::je_suis_maitre())
    {
      Cerr << "|ubar| = " << normbar << finl;
      Cerr << "|ubar|/|uprim| = " << rapport << finl;
      Cerr << "lambda " << lambda << finl;
    }
  for(face=0; face<nb_faces; face++)
    for(k=0; k< dimension; k++)
      {
        double v=volumes_entrelaces(face)*porosite_face(face);
        if(nb_comp>1)
          {
            uprime(face,k)*=v;
          }
        else
          {
            uprime(face)*=v;
          }
      }
  double dt=la_vitesse.valeur().equation().schema_temps().pas_de_temps();
  resu.ajoute(-lambda/dt, uprime);
  rapport_old=rapport;
  return resu;
}
References TRUSTVect< _TYPE_ >::ajoute(), Cerr, cible, Objet_U::dimension, MorEqn::equation(), Champ_P1NC::filtrer_L2(), finl, Process::je_suis_maitre(), la_vitesse, la_zone_VEF, lambda, lambda_max, lambda_min, TRUSTVect< _TYPE_ >::line_size(), mp_norme_vect(), Zone_VF::nb_faces(), Schema_Temps_base::pas_de_temps(), Zone_VF::porosite_face(), Equation_base::schema_temps(), Ref_Champ_P1NC::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc_base::valeurs(), and Zone_VF::volumes_entrelaces().
Referenced by calculer().
associer_pb()
void Terme_Source_Qdm_lambdaup_VEF_Face::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Definition at line 121 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
{
  int nb_eqn = pb.nombre_d_equations();
  int ok=0;
  for (int i=0; i<nb_eqn; i++)
    {
      const Equation_base& eqn = pb.equation(i);
      if  (sub_type(Navier_Stokes_std,eqn))
        {
          la_vitesse = ref_cast(Champ_P1NC,eqn.inconnue().valeur());
          associer_zones(eqn.zone_dis(),eqn.zone_Cl_dis());
          i = nb_eqn;
          ok = 1;
        }
      else
        Cerr << "Lambdaup : " << eqn.que_suis_je() << finl;
    }
  if (!ok)
    {
      Cerr << "Erreur TRUST dans " << que_suis_je()  << finl;
      Cerr << "On ne trouve pas d'equation d'hydraulique dans le probleme" << finl;
      exit();
    }
}
References associer_zones(), Cerr, Probleme_base::equation(), Process::exit(), finl, Equation_base::inconnue(), la_vitesse, Probleme_base::nombre_d_equations(), Objet_U::que_suis_je(), ref_cast, sub_type, Deriv_Champ_Inc_base::valeur(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
associer_zones()
void Terme_Source_Qdm_lambdaup_VEF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
Implements Source_base.
Definition at line 147 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
{
  la_zone_VEF = ref_cast(Zone_VEF, zone_dis.valeur());
  la_zone_Cl_VEF = ref_cast(Zone_Cl_VEF, zone_Cl_dis.valeur());
}
References la_zone_Cl_VEF, la_zone_VEF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
Referenced by associer_pb().
calculer()
DoubleTab & Terme_Source_Qdm_lambdaup_VEF_Face::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 207 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
{
  resu = 0;
  return ajouter(resu);
}
References ajouter().
cree_instance()
Objet_U * Terme_Source_Qdm_lambdaup_VEF_Face::cree_instance () static
Definition at line 24 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
duplique()
int Terme_Source_Qdm_lambdaup_VEF_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
get_info()
const Type_info * Terme_Source_Qdm_lambdaup_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 24 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
info()
const Type_info * Terme_Source_Qdm_lambdaup_VEF_Face::info () static
Definition at line 24 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
mettre_a_jour()
void Terme_Source_Qdm_lambdaup_VEF_Face::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 213 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
{
  ;
}
norme_H1()
double Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1 (const DoubleTab & vitesse) const
Definition at line 218 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const Zone& zone = zone_VEF.zone();
  double dnorme_H1,norme_H1_comp,int_grad_elem,norme_grad_elem;
  int face_globale;
// On va calculer la norme H1 d'une inconnue P1NC.
// L'algorithme tient compte des contraintes suivantes:
// - l'inconnue peut avoir plusieurs composantes
// (i.e etre un scalaire ou etre un vecteur)
// - la dimension du probleme est arbitraire (1, 2 ou 3).
// ATTENTION: les prismes ne sont pas supportes.
  dnorme_H1=0.;
  for (int composante=0; composante<vitesse.line_size(); composante++)
    {
      norme_H1_comp=0.; //pour eviter les accumulations
      for (int K=0; K<zone.nb_elem(); K++) //boucle sur les elements
        {
          norme_grad_elem=0.; //pour eviter les accumulations
          for (int i=0; i<dimension; i++) //boucle sur la dimension du pb
            {
              int_grad_elem=0.; //pour eviter les accumulations
              for (int face=0; face<zone.nb_faces_elem(); face++) //boucle sur les faces d'un "K"
                {
                  face_globale = zone_VEF.elem_faces(K,face);
                  int_grad_elem += vitesse(face_globale,composante)*
                                   zone_VEF.face_normales(face_globale,i)*
                                   zone_VEF.oriente_normale(face_globale,K);
                } //fin du for sur "face"
              norme_grad_elem += int_grad_elem*int_grad_elem;
            } //fin du for sur "i"
          norme_H1_comp += norme_grad_elem/zone_VEF.volumes(K);
        } //fin du for sur "K"
      dnorme_H1 += norme_H1_comp;
    } //!< fin du for sur "composante"
  return sqrt(dnorme_H1);
}
References composante(), Objet_U::dimension, Zone_VF::elem_faces(), Zone_VEF::face_normales(), la_zone_VEF, TRUSTVect< _TYPE_ >::line_size(), Zone::nb_elem(), Zone::nb_faces_elem(), Zone_VEF::oriente_normale(), Ref_Zone_VEF::valeur(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by norme_L2_H1().
norme_L2()
double Terme_Source_Qdm_lambdaup_VEF_Face::norme_L2 (const DoubleTab & u) const
Definition at line 271 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const DoubleVect& volumes = zone_VEF.volumes_entrelaces();
  const int nb_faces = zone_VEF.nb_faces();
  int i=0;
  double norme =0;
  int nb_compo_=u.line_size();
  for(; i<nb_faces; i++)
    {
      double s=0;
      for(int j=0; j<nb_compo_; j++)
        s+=u(i,j)*u(i,j);
      norme+=volumes(i)*s;
    }
  return sqrt(norme);
}
References la_zone_VEF, TRUSTVect< _TYPE_ >::line_size(), Zone_VF::nb_faces(), norme(), Ref_Zone_VEF::valeur(), and Zone_VF::volumes_entrelaces().
Referenced by norme_L2_H1().
norme_L2_H1()
double Terme_Source_Qdm_lambdaup_VEF_Face::norme_L2_H1 (const DoubleTab & u) const
Definition at line 264 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
{
  double pas_de_temps = la_vitesse.valeur().equation().schema_temps().pas_de_temps();
  return ((1./pas_de_temps)*norme_L2(u))+norme_H1(u);
}
References MorEqn::equation(), la_vitesse, norme_H1(), norme_L2(), Schema_Temps_base::pas_de_temps(), Equation_base::schema_temps(), and Ref_Champ_P1NC::valeur().
printOn()
Sortie & Terme_Source_Qdm_lambdaup_VEF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 31 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_Qdm_lambdaup_VEF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 40 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
{
  lambda=-1.;
  lambda_min=1.e-24;
  lambda_max=2;
  cible=0.01;
  Motcle accouverte = "{" , accfermee = "}" ;
  Motcle motlu;
  is >> motlu;
  if(motlu!=accouverte)
    {
      Cerr << motlu << " --> " << finl;
      Cerr << "{ attendue a la lecture du terme source lambda uprime " << finl;
      Cerr << "La syntaxe du mot cle Source_Qdm_lambdaup a change, voir le" << finl;
      Cerr << "manuel utilisateur de la version 1.5.5 ou plus recent." << finl;
      Cerr << "La valeur de lambda, qui peut etre desormais variable" << finl;
      Cerr << "doit etre precedee d'un mot cle:" << finl;
      Cerr << "Ainsi, Source_Qdm_lambdaup valeur devient:" <<finl;
      Cerr << "Source_Qdm_lambdaup { lambda valeur }" <<finl;
      Process::exit();
    }
  Motcles les_mots(4);
  {
    les_mots[0] = "lambda";
    les_mots[1] = "lambda_min";
    les_mots[2] = "lambda_max";
    les_mots[3] = "ubar_umprim_cible";
  }
  lambda=-1;
  while(motlu!=accfermee)
    {
      is>>motlu;
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0:
          {
            is >> lambda;
            lambda_min=lambda;
            lambda_max=lambda;
            break;
          }
        case 1:
          {
            is >> lambda_min;
            break;
          }
        case 2:
          {
            is >> lambda_max;
            break;
          }
        case 3:
          {
            is >> cible;
            break;
          }
        default :
          {
            if(motlu!=accfermee)
              {
                Cerr << motlu
                     << " non compris dans terme source lambda uprime "
                     << finl;
                Process::exit();
              }
          }
        }
    }
  if(lambda < 0)
    lambda=lambda_min;
  if (lambda < 0.)
    {
      Cerr << "Erreur a la lecture de lambda dans " << que_suis_je() << finl;
      Cerr << " lambda doit etre defini et superieur a 0 " << finl;
      exit();
    }
  Cerr << "Sortie du readOn " << finl;
  return is ;
}
References Cerr, cible, Process::exit(), finl, lambda, lambda_max, lambda_min, Objet_U::que_suis_je(), and Motcles::search().
self_cast() [1/2]
const Terme_Source_Qdm_lambdaup_VEF_Face & Terme_Source_Qdm_lambdaup_VEF_Face::self_cast (const Objet_U & r) static
Definition at line 24 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
self_cast() [2/2]
Terme_Source_Qdm_lambdaup_VEF_Face & Terme_Source_Qdm_lambdaup_VEF_Face::self_cast (Objet_U & r) static
Definition at line 24 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
taille_memoire()
unsigned Terme_Source_Qdm_lambdaup_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Terme_Source_Qdm_lambdaup_VEF_Face.cpp.
Member Data Documentation
cible
double Terme_Source_Qdm_lambdaup_VEF_Face::cible protected
Definition at line 59 of file Terme_Source_Qdm_lambdaup_VEF_Face.h.
Referenced by ajouter(), and readOn().
info_obj
const Type_info Terme_Source_Qdm_lambdaup_VEF_Face::info_obj static
Definition at line 39 of file Terme_Source_Qdm_lambdaup_VEF_Face.h.
la_vitesse
Ref_Champ_P1NC Terme_Source_Qdm_lambdaup_VEF_Face::la_vitesse protected
Definition at line 60 of file Terme_Source_Qdm_lambdaup_VEF_Face.h.
Referenced by ajouter(), associer_pb(), and norme_L2_H1().
la_zone_Cl_VEF
Ref_Zone_Cl_VEF Terme_Source_Qdm_lambdaup_VEF_Face::la_zone_Cl_VEF protected
Definition at line 62 of file Terme_Source_Qdm_lambdaup_VEF_Face.h.
Referenced by associer_zones().
la_zone_VEF
Ref_Zone_VEF Terme_Source_Qdm_lambdaup_VEF_Face::la_zone_VEF protected
Definition at line 61 of file Terme_Source_Qdm_lambdaup_VEF_Face.h.
Referenced by ajouter(), associer_zones(), norme_H1(), and norme_L2().
lambda
double Terme_Source_Qdm_lambdaup_VEF_Face::lambda mutable protected
Definition at line 56 of file Terme_Source_Qdm_lambdaup_VEF_Face.h.
Referenced by ajouter(), and readOn().
lambda_max
double Terme_Source_Qdm_lambdaup_VEF_Face::lambda_max protected
Definition at line 57 of file Terme_Source_Qdm_lambdaup_VEF_Face.h.
Referenced by ajouter(), and readOn().
lambda_min
double Terme_Source_Qdm_lambdaup_VEF_Face::lambda_min protected
Definition at line 58 of file Terme_Source_Qdm_lambdaup_VEF_Face.h.
Referenced by ajouter(), and readOn().
The documentation for this class was generated from the following files:
src/VEF/Sources/Terme_Source_Qdm_lambdaup_VEF_Face.h
src/VEF/Sources/Terme_Source_Qdm_lambdaup_VEF_Face.cpp