TRUST: Partitionneur_Sous_Zones Class Reference
Partitionneur_Sous_Zones Class Reference
Partitionneur de domaine a partir de sous-zones du domaine
Voir construire_partition()
#include <Partitionneur_Sous_Zones.h>
Public Member Functions
Partitionneur_Sous_Zones ()
~Partitionneur_Sous_Zones ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param)
Format de lecture:
(la liste de sous_zones/domaines est optionnelle, N est le nombre d'entites lues)
{
[ Sous_zones N nom_sous_zone1 nom_sous_zone2 nom_sous_zone3 ... ]
[ Domaines N nom_domaine1 nom_domaine2 ... ]
}.
void associer_domaine (const Domaine &domaine)
Premiere etape d'initialisation du partitionneur: on associe un domaine.
void initialiser (const Noms &noms_sous_zones)
Deuxieme etape d'initialisation: on definit les sous_zones a utiliser.
(on peut utiliser readOn a la place).
void construire_partition (IntVect &elem_part, int &nb_parts_tot) const
Chaque sous-zone de noms_sous_zones_ definit les elements attribues
a un processeur.
Les processeurs sont attribues dans l'ordre d'apparition des
sous-zones/domaines dans le domaine (et non dans l'ordre d'apparition dans
la liste de sous-zones).
Premiere sous_zone/domaine qui figure dans la liste => proc 0
Element de la deuxieme sous_zone => proc 1
...
Elements restants qui ne figurent dans aucune sous_zone => sur un nouveau pe.
Si un element figure dans plusieurs sous-zones, c'est la premiere sous_zone
qui gagne.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Partitionneur_Sous_Zones & self_cast (Objet_U &)
static const
Partitionneur_Sous_Zones & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Private Attributes
Ref_Domaine ref_domaine_
Noms noms_sous_zones_
Noms noms_domaines_
Detailed Description
Partitionneur de domaine a partir de sous-zones du domaine
Voir construire_partition()
Definition at line 32 of file Partitionneur_Sous_Zones.h.
Constructor & Destructor Documentation
Partitionneur_Sous_Zones::Partitionneur_Sous_Zones ()
Definition at line 31 of file Partitionneur_Sous_Zones.cpp.
{
}
Partitionneur_Sous_Zones::~Partitionneur_Sous_Zones ()
Definition at line 28 of file Partitionneur_Sous_Zones.cpp.
Member Function Documentation
void Partitionneur_Sous_Zones::associer_domaine (const Domaine & domaine) [virtual]
Premiere etape d'initialisation du partitionneur: on associe un domaine.
Implements Partitionneur_base.
Definition at line 68 of file Partitionneur_Sous_Zones.cpp.
References ref_domaine_.
{
  ref_domaine_ = domaine;
}
void Partitionneur_Sous_Zones::construire_partition (IntVect & elem_part, int & nb_parts_tot) const [virtual]
Chaque sous-zone de noms_sous_zones_ definit les elements attribues
a un processeur.
Les processeurs sont attribues dans l'ordre d'apparition des
sous-zones/domaines dans le domaine (et non dans l'ordre d'apparition dans
la liste de sous-zones).
Premiere sous_zone/domaine qui figure dans la liste => proc 0
Element de la deuxieme sous_zone => proc 1
...
Elements restants qui ne figurent dans aucune sous_zone => sur un nouveau pe.
Si un element figure dans plusieurs sous-zones, c'est la premiere sous_zone
qui gagne.
Implements Partitionneur_base.
Definition at line 94 of file Partitionneur_Sous_Zones.cpp.
References Zone::calculer_centres_gravite(), Cerr, Noms::contient_(), Partitionneur_base::corriger_bords_avec_liste(), Process::exit(), finl, Objet_U::interprete(), Sous_Zone::le_nom(), Domaine::le_nom(), Partitionneur_base::liste_bords_periodiques_, Sous_Zone::nb_elem_tot(), Zone::nb_elem_tot(), noms_domaines_, noms_sous_zones_, O_U_Ptr::non_nul(), Interprete::objet_existant(), ref_cast, ref_domaine_, IntVect::resize(), IntVect::size(), vect_impl::size(), sub_type, Ref_Domaine::valeur(), and Domaine::zone().
{
  assert(ref_domaine_.non_nul());
  const Domaine& dom = ref_domaine_.valeur();
  const Zone& zone = dom.zone(0);
  const int nb_elem = zone.nb_elem_tot();
  elem_part.resize(nb_elem);
  elem_part = -1;
  if (noms_domaines_.size()!=0 && noms_sous_zones_.size())
    {
      Cerr << "Can't mix sous_zones and domaines yet in sous_zones partitionner." << finl;
      Process::exit();
    }
// Numero de processeur en cours d'attribution:
  int pe = 0;
  int count = 0;
  if (noms_domaines_.size()!=0)
    {
      for (int i=0; i<noms_domaines_.size(); i++)
        {
          const Nom& nom_domaine = noms_domaines_[i];
          if (!interprete().objet_existant(nom_domaine) || !sub_type(Domaine, interprete().objet(nom_domaine)))
            {
// Contrairement au sous zone, le domaine doit exister pour le moment
              Cerr << "Domain " << nom_domaine << " is not existing." << finl;
              Process::exit();
// ToDo eventuellement liste de zones dans des fichiers ex: DOM_0000.Zones, DOM_0001.Zones
            }
          const Domaine& domaine = ref_cast(Domaine, interprete().objet(nom_domaine));
          DoubleTab domaine_xp;
          domaine.zone(0).calculer_centres_gravite(domaine_xp);
          IntVect dom_cells_containing_domaine_cells;
          dom.zone(0).chercher_elements(domaine_xp, dom_cells_containing_domaine_cells);
          Cerr << " Allocation of elements of the domain " << domaine.le_nom() << " to the processor " << pe << finl;
          for (int cell = 0; cell < dom_cells_containing_domaine_cells.size(); cell++)
            {
              int elem = dom_cells_containing_domaine_cells[cell];
              if (elem_part[elem] < 0)
                {
                  count++;
                  elem_part[elem] = pe;
                }
            }
          Cerr << " Number of elements attributed to the processor " << pe << " : " << count << finl;
          pe++;
        }
    }
  else
    {
      const int nb_sous_zones = dom.nb_ss_zones();
      const int toutes_sous_zones = (noms_sous_zones_.size() == 0);
      if (toutes_sous_zones)
        Cerr << " No subarea specified, we use all existing subareas." << finl;
      for (int i_sous_zone = 0; i_sous_zone < nb_sous_zones; i_sous_zone++)
        {
          const Sous_Zone& sous_zone = dom.ss_zone(i_sous_zone);
          const Nom& nom = sous_zone.le_nom();
          bool sous_zone_trouvee = noms_sous_zones_.contient_(nom);
          if (!toutes_sous_zones && !sous_zone_trouvee)
            continue;
          Cerr << " Allocation of elements of the subarea " << nom << " to the processor " << pe << finl;
          count = 0;
          const int nb_elem_ssz = sous_zone.nb_elem_tot();
          for (int i = 0; i < nb_elem_ssz; i++)
            {
              const int elem = sous_zone[i];
              if (elem_part[elem] < 0)
                {
                  count++;
                  elem_part[elem] = pe;
                }
            }
          Cerr << " Number of elements attributed to the processor " << pe << " : " << count << finl;
          pe++;
        }
    }
  Cerr << " Allocation of the remaining elements to the processor " << pe << " : ";
  count = 0;
  for (int elem = 0; elem < nb_elem; elem++)
    {
      if (elem_part[elem] < 0)
        {
          count++;
          elem_part[elem] = pe;
        }
    }
  Cerr << count << " elements." << finl;
  /*
  if (count==0)
    {
      Cerr << "Error! The last zone will be empty with 0 elements. It is surely not what you want." << finl;
      Cerr << "Check, your partition strategy." << finl;
      Process::exit();
    } */
  if (liste_bords_periodiques_.size() > 0)
    corriger_bords_avec_liste(dom, liste_bords_periodiques_, 0, elem_part);
// On ne corrige pas elem0 sur proc0 (cas test CouplageFluide_Pb1Pb2_VEF_CN)
}
Objet_U * Partitionneur_Sous_Zones::cree_instance () [static]
Definition at line 28 of file Partitionneur_Sous_Zones.cpp.
int Partitionneur_Sous_Zones::duplique () const [virtual]
Implements Partitionneur_base.
Definition at line 28 of file Partitionneur_Sous_Zones.cpp.
const Type_info * Partitionneur_Sous_Zones::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 28 of file Partitionneur_Sous_Zones.cpp.
const Type_info * Partitionneur_Sous_Zones::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 28 of file Partitionneur_Sous_Zones.cpp.
void Partitionneur_Sous_Zones::initialiser (const Noms & noms_sous_zones)
Deuxieme etape d'initialisation: on definit les sous_zones a utiliser.
(on peut utiliser readOn a la place).
Definition at line 76 of file Partitionneur_Sous_Zones.cpp.
References noms_sous_zones_, O_U_Ptr::non_nul(), and ref_domaine_.
{
  assert(ref_domaine_.non_nul());
  noms_sous_zones_ = noms_sous_zones;
}
Sortie & Partitionneur_Sous_Zones::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 47 of file Partitionneur_Sous_Zones.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Partitionneur_Sous_Zones::printOn invalid\n" << finl;
  exit();
  return os;
}
Entree & Partitionneur_Sous_Zones::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 35 of file Partitionneur_Sous_Zones.cpp.
References Cerr, Process::exit(), finl, O_U_Ptr::non_nul(), and ref_domaine_.
{
  if (! ref_domaine_.non_nul())
    {
      Cerr << " Error: the domain has not been associated" << finl;
      exit();
    }
  Partitionneur_base::readOn(is);
  Cerr << " Subareas names : ";
  return is;
}
const Partitionneur_Sous_Zones & Partitionneur_Sous_Zones::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Partitionneur_base.
Definition at line 28 of file Partitionneur_Sous_Zones.cpp.
Partitionneur_Sous_Zones & Partitionneur_Sous_Zones::self_cast (Objet_U & r) [static]
Reimplemented from Partitionneur_base.
Definition at line 28 of file Partitionneur_Sous_Zones.cpp.
void Partitionneur_Sous_Zones::set_param (Param & param) [virtual]
Format de lecture:
(la liste de sous_zones/domaines est optionnelle, N est le nombre d'entites lues)
{
[ Sous_zones N nom_sous_zone1 nom_sous_zone2 nom_sous_zone3 ... ]
[ Domaines N nom_domaine1 nom_domaine2 ... ]
}.
< XD attr sous_zones listchaine sous_zones 1 N SUBZONE_NAME_1 SUBZONE_NAME_2 ...
< XD attr domaines listchaine domaines 1 N DOMAIN_NAME_1 DOMAIN_NAME_2 ...
Implements Partitionneur_base.
Definition at line 60 of file Partitionneur_Sous_Zones.cpp.
References Param::ajouter(), noms_domaines_, and noms_sous_zones_.
{
  param.ajouter("sous_zones",&noms_sous_zones_);     //!< XD attr sous_zones listchaine sous_zones 1 N SUBZONE_NAME_1 SUBZONE_NAME_2 ...
  param.ajouter("domaines",&noms_domaines_);         //!< XD attr domaines   listchaine domaines   1 N DOMAIN_NAME_1  DOMAIN_NAME_2  ...
}
unsigned Partitionneur_Sous_Zones::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 28 of file Partitionneur_Sous_Zones.cpp.
Member Data Documentation
const Type_info Partitionneur_Sous_Zones::info_obj [static]
Reimplemented from Partitionneur_base.
Definition at line 34 of file Partitionneur_Sous_Zones.h.
Noms Partitionneur_Sous_Zones::noms_domaines_ [private]
Definition at line 47 of file Partitionneur_Sous_Zones.h.
Referenced by construire_partition(), and set_param().
Noms Partitionneur_Sous_Zones::noms_sous_zones_ [private]
Definition at line 45 of file Partitionneur_Sous_Zones.h.
Referenced by construire_partition(), initialiser(), and set_param().
Ref_Domaine Partitionneur_Sous_Zones::ref_domaine_ [private]
Definition at line 43 of file Partitionneur_Sous_Zones.h.
Referenced by associer_domaine(), construire_partition(), initialiser(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Decoupeur/Partitionneur_Sous_Zones.h
src/Kernel/Geometrie/Decoupeur/Partitionneur_Sous_Zones.cpp