TRUST: Tayl_Green Class Reference
Tayl_Green Class Reference
class Tayl_Green
by: buchal@che41b0.der.edf.fr
modified version on Champs/Tourbillon
in *.datafile: Tourbillon kwave
u=sin(kwave*x)*cos(kwave*y)
v=cos(kwave*x)*sin(kwave*y)
#include <Tayl_Green.h>
Public Member Functions
~Tayl_Green ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Tayl_Green ()
Champ_base & affecter (const Champ_base &ch)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
double valeur_a_compo (const DoubleVect &position, int compo) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int elem) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Tayl_Green & self_cast (Objet_U &)
static const Tayl_Green & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a:
Champ_base::printOn(Sortie&)
virtual Entree & readOn (Entree &)
Simple appel a:
Champ_base::readOn(Entree&)
Protected Attributes
int kwave
Detailed Description
class Tayl_Green
by: buchal@che41b0.der.edf.fr
modified version on Champs/Tourbillon
in *.datafile: Tourbillon kwave
u=sin(kwave*x)*cos(kwave*y)
v=cos(kwave*x)*sin(kwave*y)
Definition at line 36 of file Tayl_Green.h.
Constructor & Destructor Documentation
Tayl_Green::~Tayl_Green ()
Definition at line 25 of file Tayl_Green.cpp.
Tayl_Green::Tayl_Green ()
Definition at line 39 of file Tayl_Green.cpp.
References Champ_Don_base::dimensionner().
{
  dimensionner(1,2);
}
Member Function Documentation
Champ_base & Tayl_Green::affecter (const Champ_base & ch)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
Returns:
Champ_base&
Signification: le resultat de l'affectation (*this)
Contraintes:
Reimplemented from Champ_base.
Definition at line 44 of file Tayl_Green.cpp.
{
  return *this;
}
Objet_U * Tayl_Green::cree_instance () [static]
Definition at line 25 of file Tayl_Green.cpp.
int Tayl_Green::duplique () const [virtual]
Implements Champ_Don_base.
Definition at line 25 of file Tayl_Green.cpp.
const Type_info * Tayl_Green::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 25 of file Tayl_Green.cpp.
const Type_info * Tayl_Green::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 25 of file Tayl_Green.cpp.
Sortie & Tayl_Green::printOn (Sortie & os) const [protected, virtual]
Simple appel a:
Champ_base::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 27 of file Tayl_Green.cpp.
{
  return os;
}
Entree & Tayl_Green::readOn (Entree & is) [protected, virtual]
Simple appel a:
Champ_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 32 of file Tayl_Green.cpp.
References Cerr, finl, and kwave.
{
  is >> kwave;
  Cerr << "kwave=" << kwave << finl;
  return is;
}
Tayl_Green & Tayl_Green::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Don_base.
Definition at line 25 of file Tayl_Green.cpp.
const Tayl_Green & Tayl_Green::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Don_base.
Definition at line 25 of file Tayl_Green.cpp.
unsigned Tayl_Green::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Tayl_Green.cpp.
DoubleVect & Tayl_Green::valeur_a (const DoubleVect & pos, DoubleVect & les_valeurs) const [virtual]
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
Returns:
reference a "valeurs"
Reimplemented from Champ_base.
Definition at line 49 of file Tayl_Green.cpp.
{
  assert(0);
  return tab_valeurs;
}
double Tayl_Green::valeur_a_compo (const DoubleVect & pos, int compo) const [virtual]
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
Returns:
double
Reimplemented from Champ_base.
Definition at line 64 of file Tayl_Green.cpp.
{
  assert(0);
  return 0;
}
DoubleVect & Tayl_Green::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Returns:
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 56 of file Tayl_Green.cpp.
{
  assert(0);
  return tab_valeurs;
}
double Tayl_Green::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
Definition at line 71 of file Tayl_Green.cpp.
{
  assert(0);
  return 0;
}
DoubleTab & Tayl_Green::valeur_aux (const DoubleTab & positions, DoubleTab & les_valeurs) const [virtual]
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 78 of file Tayl_Green.cpp.
References Objet_U::dimension, DoubleTab::dimension(), kwave, DoubleVect::size(), and DoubleVect::size_totale().
Referenced by valeur_aux_elems().
{
  assert(tab_valeurs.size_totale() == positions.size());
  for(int i=0; i<tab_valeurs.dimension(0); i++)
    {
      tab_valeurs(i,0)=-sin(kwave*positions(i,0))*cos(kwave*positions(i,1));
      tab_valeurs(i,1)= cos(kwave*positions(i,0))*sin(kwave*positions(i,1));
      if (dimension == 3)
        tab_valeurs(i,2)= 0.;
    }
  return tab_valeurs;
}
DoubleVect & Tayl_Green::valeur_aux_compo (const DoubleTab & pos, DoubleVect & les_valeurs, int compo) const [virtual]
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
Returns:
reference au tableau les_valeurs
Reimplemented from Champ_base.
Definition at line 92 of file Tayl_Green.cpp.
References DoubleTab::dimension(), kwave, DoubleVect::size(), and DoubleVect::size_totale().
Referenced by valeur_aux_elems_compo().
{
  assert(tab_valeurs.size_totale()==positions.dimension(0));
  if(ncomp==0)
    for(int i=0; i<tab_valeurs.size(); i++)
      {
        tab_valeurs(i)=-sin(kwave*positions(i,0))*cos(kwave*positions(i,1));
      }
  else if(ncomp==1)
    for(int i=0; i<tab_valeurs.size(); i++)
      {
        tab_valeurs(i)=cos(kwave*positions(i,0))*sin(kwave*positions(i,1));
      }
  else if(ncomp==2)
    for(int i=0; i<tab_valeurs.size(); i++)
      {
        tab_valeurs(i)=0;
      }
  return tab_valeurs;
}
DoubleTab & Tayl_Green::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 114 of file Tayl_Green.cpp.
References valeur_aux().
{
  return valeur_aux(positions, tab_valeurs);
}
DoubleVect & Tayl_Green::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 121 of file Tayl_Green.cpp.
References valeur_aux_compo().
{
  return valeur_aux_compo(positions, tab_valeurs, ncomp);
}
Member Data Documentation
const Type_info Tayl_Green::info_obj [static]
Reimplemented from Champ_Don_base.
Definition at line 38 of file Tayl_Green.h.
int Tayl_Green::kwave [protected]
Definition at line 65 of file Tayl_Green.h.
Referenced by readOn(), valeur_aux(), and valeur_aux_compo().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Tayl_Green.h
src/Kernel/Champs/Tayl_Green.cpp