TRUST: Iterateur_Source_VDF_base Class Reference
Iterateur_Source_VDF_base Class Reference
#include <Iterateur_Source_VDF_base.h>
Public Member Functions
Iterateur_Source_VDF_base ()
~Iterateur_Source_VDF_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_zones (const Zone_VDF &, const Zone_Cl_VDF &)
void associer (const Source_base &source)
virtual DoubleTab & ajouter (DoubleTab &) const =0
virtual DoubleTab & calculer (DoubleTab &) const =0
virtual Evaluateur_Source_VDF & evaluateur ()=0
virtual void completer_ ()=0
virtual int equation_divisee_par_rho () const
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Iterateur_Source_VDF_base & self_cast (Objet_U &)
static const
Iterateur_Source_VDF_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
Ref_Zone_VDF la_zone
Ref_Zone_Cl_VDF la_zcl
Ref_Source_base so_base
Detailed Description
Definition at line 42 of file Iterateur_Source_VDF_base.h.
Constructor & Destructor Documentation
Iterateur_Source_VDF_base::Iterateur_Source_VDF_base ()
Definition at line 25 of file Iterateur_Source_VDF_base.cpp.
Iterateur_Source_VDF_base::~Iterateur_Source_VDF_base ()
Definition at line 25 of file Iterateur_Source_VDF_base.cpp.
Member Function Documentation
virtual DoubleTab& Iterateur_Source_VDF_base::ajouter (DoubleTab &) const [pure virtual]
Implemented in Iterateur_Source_VDF_ElemEval_Puiss_Th_QC_VDF_Elem, T_It_Sou_VDF_Elem< _TYPE_ >, T_It_Sou_VDF_Face< _TYPE_ >, Iterateur_Source_VDF_FaceEval_Darcy_VDF_Face, Iterateur_Source_VDF_ElemEval_Dirac_VDF_Elem, Iterateur_Source_VDF_ElemEval_Echange_Himp_VDF_Elem, Iterateur_Source_VDF_FaceEval_Forchheimer_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Neutr_VDF_Elem, Iterateur_Source_VDF_FaceEval_Gravite_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Th_VDF_Elem, and Iterateur_Source_VDF_ElemEval_Source_C_VDF_Elem.
Referenced by Iterateur_Source_VDF::ajouter().
void Iterateur_Source_VDF_base::associer (const Source_base & source) [inline]
Definition at line 74 of file Iterateur_Source_VDF_base.h.
References so_base.
Referenced by Iterateur_Source_VDF::associer().
{
  so_base = source;
}
void Iterateur_Source_VDF_base::associer_zones (const Zone_VDF & zone_vdf, const Zone_Cl_VDF & zone_cl_vdf)
Definition at line 48 of file Iterateur_Source_VDF_base.cpp.
References la_zcl, and la_zone.
{
  la_zone = zone_vdf;
  la_zcl = zone_cl_vdf;
}
virtual DoubleTab& Iterateur_Source_VDF_base::calculer (DoubleTab &) const [pure virtual]
Implemented in Iterateur_Source_VDF_ElemEval_Puiss_Th_QC_VDF_Elem, T_It_Sou_VDF_Elem< _TYPE_ >, T_It_Sou_VDF_Face< _TYPE_ >, Iterateur_Source_VDF_FaceEval_Darcy_VDF_Face, Iterateur_Source_VDF_ElemEval_Dirac_VDF_Elem, Iterateur_Source_VDF_ElemEval_Echange_Himp_VDF_Elem, Iterateur_Source_VDF_FaceEval_Forchheimer_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Neutr_VDF_Elem, Iterateur_Source_VDF_FaceEval_Gravite_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Th_VDF_Elem, and Iterateur_Source_VDF_ElemEval_Source_C_VDF_Elem.
Referenced by Iterateur_Source_VDF::calculer().
virtual void Iterateur_Source_VDF_base::completer_ () [pure virtual]
Implemented in Iterateur_Source_VDF_ElemEval_Puiss_Th_QC_VDF_Elem, T_It_Sou_VDF_Elem< _TYPE_ >, T_It_Sou_VDF_Face< _TYPE_ >, Iterateur_Source_VDF_FaceEval_Darcy_VDF_Face, Iterateur_Source_VDF_ElemEval_Dirac_VDF_Elem, Iterateur_Source_VDF_ElemEval_Echange_Himp_VDF_Elem, Iterateur_Source_VDF_FaceEval_Forchheimer_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Neutr_VDF_Elem, Iterateur_Source_VDF_FaceEval_Gravite_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Th_VDF_Elem, and Iterateur_Source_VDF_ElemEval_Source_C_VDF_Elem.
Referenced by Iterateur_Source_VDF::completer_().
virtual int Iterateur_Source_VDF_base::duplique () const [pure virtual]
Implements Objet_U.
Implemented in Iterateur_Source_VDF_ElemEval_Puiss_Th_QC_VDF_Elem, T_It_Sou_VDF_Elem< _TYPE_ >, T_It_Sou_VDF_Face< _TYPE_ >, Iterateur_Source_VDF_FaceEval_Darcy_VDF_Face, Iterateur_Source_VDF_ElemEval_Dirac_VDF_Elem, Iterateur_Source_VDF_ElemEval_Echange_Himp_VDF_Elem, Iterateur_Source_VDF_FaceEval_Forchheimer_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Neutr_VDF_Elem, Iterateur_Source_VDF_FaceEval_Gravite_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Th_VDF_Elem, and Iterateur_Source_VDF_ElemEval_Source_C_VDF_Elem.
int Iterateur_Source_VDF_base::equation_divisee_par_rho () const [inline, virtual]
Definition at line 65 of file Iterateur_Source_VDF_base.h.
References Nom::debute_par(), and Objet_U::que_suis_je().
{
  Nom nom_eqn=la_zcl->equation().que_suis_je();
  if (nom_eqn.debute_par("Navier_Stokes"))
    return 1;
  else
    return 0;
}
virtual Evaluateur_Source_VDF& Iterateur_Source_VDF_base::evaluateur () [pure virtual]
Implemented in Iterateur_Source_VDF_ElemEval_Puiss_Th_QC_VDF_Elem, T_It_Sou_VDF_Elem< _TYPE_ >, T_It_Sou_VDF_Face< _TYPE_ >, Iterateur_Source_VDF_FaceEval_Darcy_VDF_Face, Iterateur_Source_VDF_ElemEval_Dirac_VDF_Elem, Iterateur_Source_VDF_ElemEval_Echange_Himp_VDF_Elem, Iterateur_Source_VDF_FaceEval_Forchheimer_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Neutr_VDF_Elem, Iterateur_Source_VDF_FaceEval_Gravite_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Th_VDF_Elem, and Iterateur_Source_VDF_ElemEval_Source_C_VDF_Elem.
Referenced by Iterateur_Source_VDF::evaluateur().
const Type_info * Iterateur_Source_VDF_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_VDF_ElemEval_Puiss_Th_QC_VDF_Elem, Iterateur_Source_VDF_FaceEval_Darcy_VDF_Face, Iterateur_Source_VDF_ElemEval_Dirac_VDF_Elem, Iterateur_Source_VDF_ElemEval_Echange_Himp_VDF_Elem, Iterateur_Source_VDF_FaceEval_Forchheimer_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Neutr_VDF_Elem, Iterateur_Source_VDF_FaceEval_Gravite_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Th_VDF_Elem, and Iterateur_Source_VDF_ElemEval_Source_C_VDF_Elem.
Definition at line 25 of file Iterateur_Source_VDF_base.cpp.
const Type_info * Iterateur_Source_VDF_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_VDF_ElemEval_Puiss_Th_QC_VDF_Elem, Iterateur_Source_VDF_FaceEval_Darcy_VDF_Face, Iterateur_Source_VDF_ElemEval_Dirac_VDF_Elem, Iterateur_Source_VDF_ElemEval_Echange_Himp_VDF_Elem, Iterateur_Source_VDF_FaceEval_Forchheimer_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Neutr_VDF_Elem, Iterateur_Source_VDF_FaceEval_Gravite_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Th_VDF_Elem, and Iterateur_Source_VDF_ElemEval_Source_C_VDF_Elem.
Definition at line 25 of file Iterateur_Source_VDF_base.cpp.
Sortie & Iterateur_Source_VDF_base::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_VDF_ElemEval_Puiss_Th_QC_VDF_Elem, Iterateur_Source_VDF_FaceEval_Darcy_VDF_Face, Iterateur_Source_VDF_ElemEval_Dirac_VDF_Elem, Iterateur_Source_VDF_ElemEval_Echange_Himp_VDF_Elem, Iterateur_Source_VDF_FaceEval_Forchheimer_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Neutr_VDF_Elem, Iterateur_Source_VDF_FaceEval_Gravite_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Th_VDF_Elem, and Iterateur_Source_VDF_ElemEval_Source_C_VDF_Elem.
Definition at line 30 of file Iterateur_Source_VDF_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Iterateur_Source_VDF_base::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_VDF_ElemEval_Puiss_Th_QC_VDF_Elem, Iterateur_Source_VDF_FaceEval_Darcy_VDF_Face, Iterateur_Source_VDF_ElemEval_Dirac_VDF_Elem, Iterateur_Source_VDF_ElemEval_Echange_Himp_VDF_Elem, Iterateur_Source_VDF_FaceEval_Forchheimer_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Neutr_VDF_Elem, Iterateur_Source_VDF_FaceEval_Gravite_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Th_VDF_Elem, and Iterateur_Source_VDF_ElemEval_Source_C_VDF_Elem.
Definition at line 38 of file Iterateur_Source_VDF_base.cpp.
{
  return s ;
}
const Iterateur_Source_VDF_base & Iterateur_Source_VDF_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_VDF_ElemEval_Puiss_Th_QC_VDF_Elem, Iterateur_Source_VDF_FaceEval_Darcy_VDF_Face, Iterateur_Source_VDF_ElemEval_Dirac_VDF_Elem, Iterateur_Source_VDF_ElemEval_Echange_Himp_VDF_Elem, Iterateur_Source_VDF_FaceEval_Forchheimer_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Neutr_VDF_Elem, Iterateur_Source_VDF_FaceEval_Gravite_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Th_VDF_Elem, and Iterateur_Source_VDF_ElemEval_Source_C_VDF_Elem.
Definition at line 25 of file Iterateur_Source_VDF_base.cpp.
Iterateur_Source_VDF_base & Iterateur_Source_VDF_base::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_VDF_ElemEval_Puiss_Th_QC_VDF_Elem, Iterateur_Source_VDF_FaceEval_Darcy_VDF_Face, Iterateur_Source_VDF_ElemEval_Dirac_VDF_Elem, Iterateur_Source_VDF_ElemEval_Echange_Himp_VDF_Elem, Iterateur_Source_VDF_FaceEval_Forchheimer_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Neutr_VDF_Elem, Iterateur_Source_VDF_FaceEval_Gravite_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Th_VDF_Elem, and Iterateur_Source_VDF_ElemEval_Source_C_VDF_Elem.
Definition at line 25 of file Iterateur_Source_VDF_base.cpp.
Member Data Documentation
const Type_info Iterateur_Source_VDF_base::info_obj [static]
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_VDF_ElemEval_Puiss_Th_QC_VDF_Elem, Iterateur_Source_VDF_FaceEval_Darcy_VDF_Face, Iterateur_Source_VDF_ElemEval_Dirac_VDF_Elem, Iterateur_Source_VDF_ElemEval_Echange_Himp_VDF_Elem, Iterateur_Source_VDF_FaceEval_Forchheimer_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Neutr_VDF_Elem, Iterateur_Source_VDF_FaceEval_Gravite_VDF_Face, Iterateur_Source_VDF_ElemEval_Puiss_Th_VDF_Elem, and Iterateur_Source_VDF_ElemEval_Source_C_VDF_Elem.
Definition at line 45 of file Iterateur_Source_VDF_base.h.
Ref_Zone_Cl_VDF Iterateur_Source_VDF_base::la_zcl [protected]
Definition at line 61 of file Iterateur_Source_VDF_base.h.
Referenced by associer_zones().
Ref_Zone_VDF Iterateur_Source_VDF_base::la_zone [protected]
Definition at line 60 of file Iterateur_Source_VDF_base.h.
Referenced by associer_zones(), and T_It_Sou_VDF_Face< _TYPE_ >::faces_doubles().
Ref_Source_base Iterateur_Source_VDF_base::so_base [protected]
Definition at line 62 of file Iterateur_Source_VDF_base.h.
Referenced by associer().
The documentation for this class was generated from the following files:
src/VDF/Sources/Iterateurs/Iterateur_Source_VDF_base.h
src/VDF/Sources/Iterateurs/Iterateur_Source_VDF_base.cpp