TRUST: Hexaedre_VEF Class Reference
Hexaedre_VEF Class Reference
Classe Hexaedre_VEF
Cette classe represente l'element geometrique Hexaedre_VEF.
Un Hexaedre_VEF est un polyedre qui a 4 faces, 4 sommets et
un seul type de face ayant 3 sommets par face.
#include <Hexaedre_VEF.h>
Public Member Functions
Hexaedre_VEF ()
~Hexaedre_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int face_sommet (int i, int j) const override
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
int face_sommet0 (int i) const
Renvoie le numero du i-ieme sommet de la face 0.
int face_sommet1 (int i) const
Renvoie le numero du i-ieme sommet de la face 1.
int face_sommet2 (int i) const
Renvoie le numero du i-ieme sommet de la face 2.
int face_sommet3 (int i) const
Renvoie le numero du i-ieme sommet de la face 3.
int face_sommet4 (int i) const
Renvoie le numero du i-ieme sommet de la face 4.
int face_sommet5 (int i) const
Renvoie le numero du i-ieme sommet de la face 5.
int nb_som () const override
Renvoie le nombre de sommets d'un Hexaedre_VEF: 8.
int nb_faces (int=0) const override
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
int nb_som_face (int=0) const override
Renvoie le nombre de sommets des faces
du type specifie.
int est_structure () const override
Renvoie toujours 0, car l'element geometrique
Hexaedre_VEF n'est pas de type structure.
const Nom & nom_lml () const override
Renvoie le nom LML d'un Hexaedre_VEF = "HEXA8".
int contient (const ArrOfDouble &, int) const override
Renvoie 1 si l'element ielem de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
int contient (const ArrOfInt &, int) const override
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Type_Face type_face (int=0) const override
Renvoie le i-ieme type de face.
Un Hexaedre_VEF n'a qu'un seul type de face.
void reordonner () override
NE FAIT RIEN:
A surcharger dans les classes derivees.
void calculer_volumes (DoubleVect &) const override
Calcule les volumes des elements de la zone associee.
int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const override
voir ElemGeomBase::get_tab_faces_sommets_locaux
Public Member Functions inherited from Elem_geom_base
Elem_geom_base ()
~Elem_geom_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void creer_faces_elem (Faces &, int, Type_Face) const
Cree les faces de l'element geometrique specifie de la zone
en precisant le type de face a creer.
void creer_faces_elem (Faces &, int) const
Cree les faces de l'element de la zone specifie.
virtual int face_sommet (int i, int j) const =0
void associer_zone (const Zone &)
Associe l'element geometrique a sa zone.
virtual int nb_som () const =0
virtual int nb_faces (int=0) const =0
virtual int nb_som_face (int=0) const =0
virtual int est_structure () const =0
virtual const Nom & nom_lml () const =0
virtual int contient (const ArrOfDouble &, int) const =0
virtual int contient (const ArrOfInt &, int) const =0
virtual int nb_type_face () const
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
virtual int num_face (int face, Type_Face &type) const
Renvoie le parametre face si le type
de face specifie est le meme que celui de l'element
geometrique.
virtual Type_Face type_face (int=0) const =0
virtual void calculer_centres_gravite (DoubleTab &) const
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
virtual void reordonner ()
NE FAIT RIEN:
A surcharger dans les classes derivees.
virtual void calculer_volumes (DoubleVect &) const =0
virtual void calculer_normales (const IntTab &faces_sommets, DoubleTab &face_normales) const
Sort en erreur. Cette methode n'est pas virtuelle pure
pour des raisons de commodite.
virtual int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
virtual void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const
idem que Elem_geom_base::get_tab_faces_sommets_locaux mais pour les aretes:
aretes_som_local.dimension(0) = nombre d'aretes sur l'element de reference
aretes_som_local.dimension(1) = 2 (nombre de sommets par arete)
aretes_som_local(i,j) = numero d'un sommet de l'element (0 <= n < nb_sommets_par_element)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Hexaedre_VEF & self_cast (Objet_U &)
static const Hexaedre_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Elem_geom_base
static const Type_info * info ()
static Elem_geom_base & self_cast (Objet_U &)
static const Elem_geom_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Elem_geom_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Elem_geom_base
Ref_Zone ma_zone
Detailed Description
Classe Hexaedre_VEF
Cette classe represente l'element geometrique Hexaedre_VEF.
Un Hexaedre_VEF est un polyedre qui a 4 faces, 4 sommets et
un seul type de face ayant 3 sommets par face.
Definition at line 36 of file Hexaedre_VEF.h.
Constructor & Destructor Documentation
Hexaedre_VEF()
Hexaedre_VEF::Hexaedre_VEF ()
Definition at line 19 of file Hexaedre_VEF.cpp.
~Hexaedre_VEF()
Hexaedre_VEF::~Hexaedre_VEF ()
Definition at line 19 of file Hexaedre_VEF.cpp.
Member Function Documentation
calculer_volumes()
void Hexaedre_VEF::calculer_volumes (DoubleVect & volumes) const override virtual
Calcule les volumes des elements de la zone associee.
Implements Elem_geom_base.
Definition at line 411 of file Hexaedre_VEF.cpp.
{
  const Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  IntTab face_sommet_global;
  face_sommet_global.resize(6,4);
  double x0,y0,z0;
  double x1,y1,z1;
  double x2,y2,z2;
  double x3,y3,z3;
  double volume;
// double volume_global;
  int s1,s2,s3,s4;
  int som0,som1,som2,som3,som4,som5,som6,som7;
// volume_global =0;
  int size_tot = zone.nb_elem_tot();
  assert(volumes.size_totale()==size_tot);
  for (int num_poly=0; num_poly<size_tot; num_poly++)
    {
// on initialise le volume
// volumes[num_poly] =0;
// pour chaque elem on le decoupe en tetra.
// On calcul le volume par somme des volumes des tetras.
// on definit les sommets de l'elem
// on recupere le centre de l'element.
      som0 = zone.sommet_elem(num_poly,0);
      som1 = zone.sommet_elem(num_poly,1);
      som2 = zone.sommet_elem(num_poly,2);
      som3 = zone.sommet_elem(num_poly,3);
      som4 = zone.sommet_elem(num_poly,4);
      som5 = zone.sommet_elem(num_poly,5);
      som6 = zone.sommet_elem(num_poly,6);
      som7 = zone.sommet_elem(num_poly,7);
// Cerr << " som0 " << som0 << " som1 " << som1 << " som2 " << som2 << " som3 " << som3 <<  finl;
// Cerr << " som4 " << som4 << " som5 " << som5 << " som6 " << som6 << " som7 " << som7 <<   finl;
// on construit le tableau de travail face_sommet_global
// les faces seront ordonnee suivant Xmin, Xmax, Ymin, Ymax, Zmin,Zmax
// toujours en gardant la numerotation de TRUST
      face_sommet_global(0,0) =som0;
      face_sommet_global(0,1) =som1;
      face_sommet_global(0,2) =som2;
      face_sommet_global(0,3) =som3;
      face_sommet_global(1,0) =som4;
      face_sommet_global(1,1) =som5;
      face_sommet_global(1,2) =som6;
      face_sommet_global(1,3) =som7;
      face_sommet_global(2,0) =som0;
      face_sommet_global(2,1) =som4;
      face_sommet_global(2,2) =som2;
      face_sommet_global(2,3) =som6;
      face_sommet_global(3,0) =som1;
      face_sommet_global(3,1) =som5;
      face_sommet_global(3,2) =som3;
      face_sommet_global(3,3) =som7;
      face_sommet_global(4,0) =som0;
      face_sommet_global(4,1) =som4;
      face_sommet_global(4,2) =som1;
      face_sommet_global(4,3) =som5;
      face_sommet_global(5,0) =som2;
      face_sommet_global(5,1) =som6;
      face_sommet_global(5,2) =som3;
      face_sommet_global(5,3) =som7;
// le sommet 0 sera toujours le centre de gravite
      x0 = ( dom.coord(som0,0) + dom.coord(som1,0) + dom.coord(som2,0) + dom.coord(som3,0) + dom.coord(som4,0) + dom.coord(som5,0) + dom.coord(som6,0) + dom.coord(som7,0) )*0.125;
      y0 = ( dom.coord(som0,1) + dom.coord(som1,1) + dom.coord(som2,1) + dom.coord(som3,1) + dom.coord(som4,1) + dom.coord(som5,1) + dom.coord(som6,1) + dom.coord(som7,1) )*0.125;
      z0 = ( dom.coord(som0,2) + dom.coord(som1,2) + dom.coord(som2,2) + dom.coord(som3,2) + dom.coord(som4,2) + dom.coord(som5,2) + dom.coord(som6,2) + dom.coord(som7,2) )*0.125;
// Cerr << "le num poly traite " << num_poly << finl;
// Cerr << "le centre de gravite " << x0 << " " << y0 << " " << z0 << finl;
      volume =0;
// On decoupe en tetra.
// pour chaque face de l'hexa (0 a 7)
      for ( int k=0 ; k<nb_faces(); k++)
        {
// on recupere les sommets de la face consideree
          s1 = face_sommet_global(k,0);
          s2 = face_sommet_global(k,1);
          s3 = face_sommet_global(k,2);
          s4 = face_sommet_global(k,3);
// Cerr << " les sommets de la face " << k << " = " << s1 << " " << s2 << " " << s3 << " " << s4 << finl;
// Cerr << "coord de s1 " << dom.coord(s1,0) << " " << dom.coord(s1,1) << " " << dom.coord(s1,2) << finl;
// Cerr << "coord de s2 " << dom.coord(s2,0) << " " << dom.coord(s2,1) << " " << dom.coord(s2,2) << finl;
// Cerr << "coord de s3 " << dom.coord(s3,0) << " " << dom.coord(s3,1) << " " << dom.coord(s3,2) << finl;
// Cerr << "coord de s4 " << dom.coord(s4,0) << " " << dom.coord(s4,1) << " " << dom.coord(s4,2) << finl;
          x1 = dom.coord(s1,0);
          y1 = dom.coord(s1,1);
          z1 = dom.coord(s1,2);
          x2 = dom.coord(s2,0);
          y2 = dom.coord(s2,1);
          z2 = dom.coord(s2,2);
          x3 = dom.coord(s4,0);
          y3 = dom.coord(s4,1);
          z3 = dom.coord(s4,2);
// volume_tetra1 =  std::fabs((x1-x0)*((y2-y0)*(z3-z0)-(y3-y0)*(z2-z0))-
// (x2-x0)*((y1-y0)*(z3-z0)-(y3-y0)*(z1-z0))+
// (x3-x0)*((y1-y0)*(z2-z0)-(y2-y0)*(z1-z0)))/6;
          volume += std::fabs((x1-x0)*((y2-y0)*(z3-z0)-(y3-y0)*(z2-z0))-
                              (x2-x0)*((y1-y0)*(z3-z0)-(y3-y0)*(z1-z0))+
                              (x3-x0)*((y1-y0)*(z2-z0)-(y2-y0)*(z1-z0)))/6;
          x1 = dom.coord(s1,0);
          y1 = dom.coord(s1,1);
          z1 = dom.coord(s1,2);
          x2 = dom.coord(s4,0);
          y2 = dom.coord(s4,1);
          z2 = dom.coord(s4,2);
          x3 = dom.coord(s3,0);
          y3 = dom.coord(s3,1);
          z3 = dom.coord(s3,2);
// volume_tetra2 = std::fabs((x1-x0)*((y2-y0)*(z3-z0)-(y3-y0)*(z2-z0))-
// (x2-x0)*((y1-y0)*(z3-z0)-(y3-y0)*(z1-z0))+
// (x3-x0)*((y1-y0)*(z2-z0)-(y2-y0)*(z1-z0)))/6;
          volume += std::fabs((x1-x0)*((y2-y0)*(z3-z0)-(y3-y0)*(z2-z0))-
                              (x2-x0)*((y1-y0)*(z3-z0)-(y3-y0)*(z1-z0))+
                              (x3-x0)*((y1-y0)*(z2-z0)-(y2-y0)*(z1-z0)))/6;
        }
      volumes[num_poly] = volume;
// volume_global += volumes[num_poly];
    }
// Cerr << "volumes " << volumes  << finl;
// Cerr << " le volume global est = " << volume_global << finl;
}
References Domaine::coord(), Zone::domaine(), Elem_geom_base::ma_zone, Zone::nb_elem_tot(), nb_faces(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size_totale(), Zone::sommet_elem(), and Ref_Zone::valeur().
contient() [1/2]
int Hexaedre_VEF::contient (const ArrOfDouble & pos, int element) const override virtual
Renvoie 1 si l'element ielem de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
Returns
int
Signification: 1 si le point de coordonnees specifiees
appartient a l'element ielem
0 sinon
Contraintes:
Implements Elem_geom_base.
Definition at line 314 of file Hexaedre_VEF.cpp.
{
  assert(pos.size_array()==3);
  const Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  int som0 = zone.sommet_elem(element,0);
  int som1 = zone.sommet_elem(element,1);
  int som2 = zone.sommet_elem(element,2);
  int som3 = zone.sommet_elem(element,3);
  int som4 = zone.sommet_elem(element,4);
  int som5 = zone.sommet_elem(element,5);
  int som6 = zone.sommet_elem(element,6);
  int som7 = zone.sommet_elem(element,7);
// GF on teste si le point est boen entre les 2 faces
  if (entre_faces(zone,dom,pos,som0,som1,som2,som4,som5,som6))
    if (entre_faces(zone,dom,pos,som0,som1,som4,som2,som3,som6))
      if (entre_faces(zone,dom,pos,som0,som2,som4,som1,som3,som5))
        return 1;
  return 0;
// PQ : 04/03 : optimisation
  int aff = 0;
  if (element==-701)
    {
      aff = 1;
    }
  if (contient_Tetra(zone, dom, pos, som0,som1,som2,som4,aff) ||
      contient_Tetra(zone, dom, pos, som1,som2,som3,som6,aff) ||
      contient_Tetra(zone, dom, pos, som1,som2,som4,som6,aff) ||
      contient_Tetra(zone, dom, pos, som3,som5,som6,som7,aff) ||
      contient_Tetra(zone, dom, pos, som1,som4,som5,som6,aff) ||
      contient_Tetra(zone, dom, pos, som1,som3,som5,som6,aff))
    {
      return 1;
    }
  return 0;
}
References contient_Tetra(), Zone::domaine(), entre_faces(), Elem_geom_base::ma_zone, TRUSTArray< _TYPE_ >::size_array(), Zone::sommet_elem(), and Ref_Zone::valeur().
contient() [2/2]
int Hexaedre_VEF::contient (const ArrOfInt & som, int element) const override virtual
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Returns
int
Signification: 1 si les sommets passes en parametre
sont ceux de l'element specifie, 0 sinon
Contraintes:
Implements Elem_geom_base.
Definition at line 380 of file Hexaedre_VEF.cpp.
{
  const Zone& zone=ma_zone.valeur();
  if((zone.sommet_elem(element,0)==som[0])&&
      (zone.sommet_elem(element,1)==som[1])&&
      (zone.sommet_elem(element,2)==som[2])&&
      (zone.sommet_elem(element,3)==som[3])&&
      (zone.sommet_elem(element,4)==som[4])&&
      (zone.sommet_elem(element,5)==som[5])&&
      (zone.sommet_elem(element,6)==som[6])&&
      (zone.sommet_elem(element,7)==som[7]))
    return 1;
  else
    return 0;
}
References Elem_geom_base::ma_zone, Zone::sommet_elem(), and Ref_Zone::valeur().
cree_instance()
Objet_U * Hexaedre_VEF::cree_instance () static
Definition at line 19 of file Hexaedre_VEF.cpp.
duplique()
int Hexaedre_VEF::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Hexaedre_VEF.cpp.
est_structure()
int Hexaedre_VEF::est_structure () const inline override virtual
Renvoie toujours 0, car l'element geometrique
Hexaedre_VEF n'est pas de type structure.
Returns
int
Signification: 1 si l'element est de type structure
0 sinon
Contraintes: toujours egal a 0
Implements Elem_geom_base.
Definition at line 401 of file Hexaedre_VEF.h.
{
  return 0;
}
face_sommet()
int Hexaedre_VEF::face_sommet (int i, int j) const inline override virtual
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
Returns
int
Signification: le numero du j-ieme sommet de la i-ieme face
Contraintes:
Implements Elem_geom_base.
Definition at line 85 of file Hexaedre_VEF.h.
{
  assert(i<6);
  switch(i)
    {
    case 0:
      return face_sommet0(j);
    case 1:
      return face_sommet1(j);
    case 2:
      return face_sommet2(j);
    case 3:
      return face_sommet3(j);
    case 4:
      return face_sommet4(j);
    case 5:
      return face_sommet5(j);
    default :
      return -1;
    }
}
References face_sommet0(), face_sommet1(), face_sommet2(), face_sommet3(), face_sommet4(), and face_sommet5().
face_sommet0()
int Hexaedre_VEF::face_sommet0 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 0.
Returns
int
Signification: le numero du i-ieme sommet de la face 0
Contraintes:
Definition at line 196 of file Hexaedre_VEF.h.
{
// face_sommet0(0)=0;
// face_sommet0(1)=2;
// face_sommet0(2)=4;
// face_sommet0(3)=6;
  assert(i>=0);
  assert(i<4);
  if(i>=4)
    {
      Cerr << "A VEF hexahedron (Hexaedre_VEF) has not " << i << " nodes per face" << finl;
      exit();
    }
  return 2*i;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet1()
int Hexaedre_VEF::face_sommet1 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 1.
Returns
int
Signification: le numero du i-ieme sommet de la face 1
Contraintes:
Definition at line 227 of file Hexaedre_VEF.h.
{
// face_sommet1(0)=0;
// face_sommet1(1)=1;
// face_sommet1(2)=4;
// face_sommet1(3)=5;
  assert(i>=0);
  assert(i<4);
  switch(i)
    {
    case 0:
      return 0;
    case 1:
      return 1;
    case 2:
      return 4;
    case 3:
      return 5;
    default :
      Cerr << "A VEF hexahedron (Hexaedre_VEF) has not " << i << " nodes per face" << finl;
      exit();
      return -1;
    }
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet2()
int Hexaedre_VEF::face_sommet2 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 2.
Returns
int
Signification: le numero du i-ieme sommet de la face 2
Contraintes:
Definition at line 267 of file Hexaedre_VEF.h.
{
// face_sommet2(0)=0;
// face_sommet2(1)=1;
// face_sommet2(2)=2;
// face_sommet2(3)=3;
  assert(i>=0);
  assert(i<4);
  if(i>=4)
    {
      Cerr << "A VEF hexahedron (Hexaedre_VEF) has not " << i << " nodes per face" << finl;
      exit();
    }
  return i;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet3()
int Hexaedre_VEF::face_sommet3 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 3.
Returns
int
Signification: le numero du i-ieme sommet de la face 3
Contraintes:
Definition at line 298 of file Hexaedre_VEF.h.
{
// face_sommet3(0)=1;
// face_sommet3(1)=3;
// face_sommet3(2)=5;
// face_sommet3(3)=7;
  assert(i>=0);
  assert(i<4);
  if(i>=4)
    {
      Cerr << "A VEF hexahedron (Hexaedre_VEF) has not " << i << " nodes per face" << finl;
      exit();
    }
  return 2*i+1;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet4()
int Hexaedre_VEF::face_sommet4 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 4.
Returns
int
Signification: le numero du i-ieme sommet de la face 4
Contraintes:
Definition at line 328 of file Hexaedre_VEF.h.
{
// face_sommet4(0)=2;
// face_sommet4(1)=3;
// face_sommet4(2)=6;
// face_sommet4(3)=7;
  assert(i>=0);
  assert(i<4);
  switch(i)
    {
    case 0:
      return 2;
    case 1:
      return 3;
    case 2:
      return 6;
    case 3:
      return 7;
    default :
      Cerr << "A VEF hexahedron (Hexaedre_VEF) has not " << i << " nodes per face" << finl;
      exit();
      return -1;
    }
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet5()
int Hexaedre_VEF::face_sommet5 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 5.
Returns
int
Signification: le numero du i-ieme sommet de la face 5
Contraintes:
Definition at line 367 of file Hexaedre_VEF.h.
{
// face_sommet4(0)=4;
// face_sommet4(1)=5;
// face_sommet4(2)=6;
// face_sommet4(3)=7;
  assert(i>=0);
  assert(i<4);
  if(i>=4)
    {
      Cerr << "A VEF hexahedron (Hexaedre_VEF) has not " << i << " nodes per face" << finl;
      exit();
    }
  return i+4;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
get_info()
const Type_info * Hexaedre_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 19 of file Hexaedre_VEF.cpp.
get_tab_faces_sommets_locaux()
int Hexaedre_VEF::get_tab_faces_sommets_locaux (IntTab & faces_som_local) const override virtual
voir ElemGeomBase::get_tab_faces_sommets_locaux
Reimplemented from Elem_geom_base.
Definition at line 845 of file Hexaedre_VEF.cpp.
{
  faces_som_local.resize(6,4);
  for (int i=0; i<6; i++)
    for (int j=0; j<4; j++)
      faces_som_local(i,j) = faces_sommets_hexa_vef[i][j];
  return 1;
}
References faces_sommets_hexa_vef, and TRUSTTab< _TYPE_ >::resize().
info()
const Type_info * Hexaedre_VEF::info () static
Definition at line 19 of file Hexaedre_VEF.cpp.
nb_faces()
int Hexaedre_VEF::nb_faces (int i = 0) const inline override virtual
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
Returns
int
Signification: le nombre de faces de type i
Contraintes: toujours egal a 6 (si i=0)
Implements Elem_geom_base.
Definition at line 143 of file Hexaedre_VEF.h.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A VEF hexahedron (Hexaedre_VEF) has not " << i << " types of face" << finl;
      exit();
    }
  return 6;
}
References Cerr, Process::exit(), and finl.
Referenced by calculer_volumes().
nb_som()
int Hexaedre_VEF::nb_som () const inline override virtual
Renvoie le nombre de sommets d'un Hexaedre_VEF: 8.
Returns
int
Signification: le nombre de sommets d'un Hexaedre_VEF
Contraintes: toujours egal a 8
Implements Elem_geom_base.
Definition at line 122 of file Hexaedre_VEF.h.
{
  return 8;
}
nb_som_face()
int Hexaedre_VEF::nb_som_face (int i = 0) const inline override virtual
Renvoie le nombre de sommets des faces
du type specifie.
Returns
int
Signification: le nombre de sommets des faces de type i
Contraintes: toujours egal a 4 (si i=0)
Implements Elem_geom_base.
Definition at line 170 of file Hexaedre_VEF.h.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A VEF hexahedron (Hexaedre_VEF) has not " << i << " types of face" << finl;
      exit();
    }
  return 4;
}
References Cerr, Process::exit(), and finl.
nom_lml()
const Nom & Hexaedre_VEF::nom_lml () const override virtual
Renvoie le nom LML d'un Hexaedre_VEF = "HEXA8".
Returns
Nom&
Signification: toujours egal a "HEXA8"
Contraintes: reference constante
Implements Elem_geom_base.
Definition at line 78 of file Hexaedre_VEF.cpp.
{
  static Nom nom="VOXEL8";
  return nom;
}
printOn()
Sortie & Hexaedre_VEF::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 36 of file Hexaedre_VEF.cpp.
{
  return s;
}
readOn()
Entree & Hexaedre_VEF::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 56 of file Hexaedre_VEF.cpp.
{
  return s;
}
reordonner()
void Hexaedre_VEF::reordonner () override virtual
NE FAIT RIEN:
A surcharger dans les classes derivees.
Reimplemented from Elem_geom_base.
Definition at line 700 of file Hexaedre_VEF.cpp.
{
  /*
    22/12/04 : Generalisation de la methode (mais c'est plus lent!)
    Numerotation d'un hexa VEF:
    6--------7
    | \       |\
    4   2-----3  5
    \ /       \ |
    0---------1
    On boucle sur chacune des faces et on fait le produit scalaire 03.12/|03||12|
    et on le compare a 02.13/|02||13|
    S'il est plus grand on intervertit les sommets 2 et 3.
    L'algorithme fonctionne si 0123 et 4567 sont deja sur une meme face
  */
  Zone& zone=ma_zone.valeur();
  IntTab& elem=zone.les_elems();
  int nb_elem=zone.nb_elem();
  DoubleTab& coord=zone.domaine().les_sommets();
// tableau contenant les permutations valides d'un quadrangle
  IntTab perm(8,4);
  perm( 0 , 0 )= 0 ;
  perm( 0 , 1 )= 1 ;
  perm( 0 , 2 )= 2 ;
  perm( 0 , 3 )= 3 ;
  perm( 1 , 0 )= 0 ;
  perm( 1 , 1 )= 2 ;
  perm( 1 , 2 )= 1 ;
  perm( 1 , 3 )= 3 ;
  perm( 2 , 0 )= 1 ;
  perm( 2 , 1 )= 0 ;
  perm( 2 , 2 )= 3 ;
  perm( 2 , 3 )= 2 ;
  perm( 3 , 0 )= 1 ;
  perm( 3 , 1 )= 3 ;
  perm( 3 , 2 )= 0 ;
  perm( 3 , 3 )= 2 ;
  perm( 4 , 0 )= 2 ;
  perm( 4 , 1 )= 0 ;
  perm( 4 , 2 )= 3 ;
  perm( 4 , 3 )= 1 ;
  perm( 5 , 0 )= 2 ;
  perm( 5 , 1 )= 3 ;
  perm( 5 , 2 )= 0 ;
  perm( 5 , 3 )= 1 ;
  perm( 6 , 0 )= 3 ;
  perm( 6 , 1 )= 1 ;
  perm( 6 , 2 )= 2 ;
  perm( 6 , 3 )= 0 ;
  perm( 7 , 0 )= 3 ;
  perm( 7 , 1 )= 2 ;
  perm( 7 , 2 )= 1 ;
  perm( 7 , 3 )= 0 ;
  DoubleTab v(3,3);
  ArrOfDouble prod_(3);
  ArrOfDouble prod_v(3);
  ArrOfDouble dist(8);
  DoubleTab prod_v2(3,3);
  ArrOfInt sa(8);
  for (int num_poly=0; num_poly<nb_elem; num_poly++)
    {
      int permutations=-1;
// int niter=0;
// on commence par remettre correctement les 2 plans opposes
      permutations+=reordonne(0,1,2,3,coord,elem,num_poly,0, v,prod_, prod_v, dist, prod_v2);
      permutations+=reordonne(4,5,6,7,coord,elem,num_poly,0, v,prod_, prod_v, dist, prod_v2);
      for (int i=0; i<8; i++)
        sa[i]=elem(num_poly,i);
// on teste les 8 possibilites
      int j;
      int n=0;
      int perm_valid=-1;
      for ( j=0; j<8; j++)
        {
// Cerr<<" debut test "<<j<<finl;
          int test=1;
          for (int i=4; i<8; i++)
            elem(num_poly,i)=sa[perm(j,i-4)+4];
// on regarde si les 6 plans sont valides
          permutations=0;
          permutations+=reordonne(2,0,3,1,coord,elem,num_poly,test, v,prod_, prod_v, dist, prod_v2);
          permutations+=reordonne(3,1,7,5,coord,elem,num_poly,test, v,prod_, prod_v, dist, prod_v2);
          permutations+=reordonne(7,5,6,4,coord,elem,num_poly,test, v,prod_, prod_v, dist, prod_v2);
          permutations+=reordonne(6,4,2,0,coord,elem,num_poly,test, v,prod_, prod_v, dist, prod_v2);
          permutations+=reordonne(2,3,6,7,coord,elem,num_poly,test, v,prod_, prod_v, dist, prod_v2);
          permutations+=reordonne(4,5,0,1,coord,elem,num_poly,test, v,prod_, prod_v, dist, prod_v2);
          if (permutations==0)
            {
              if (n>0)
                Cerr<<" former permutation "<< perm_valid<<" new permutation "<<j<<finl;
              perm_valid=j;
              n++;
            }
// Cerr << permutations << " permutations sur l'element " << num_poly << finl;
// Cerr << elem(num_poly,0) << " " << elem(num_poly,1) << " " << elem(num_poly,2) << " " << elem(num_poly,3);
// Cerr << " " << elem(num_poly,4) << " " << elem(num_poly,5) << " " << elem(num_poly,6) << " " << elem(num_poly,7) << finl;
// Cerr<<" fin test "<<j<<finl;
        }
      if (n==0)
        {
          Cerr << "Failure of the algorithm in Hexaedre_VEF::reordonner" << finl;
          Cerr << "Here is the connectivity element-node of the cell " << num_poly << " that raises problem:" << finl;
          for (int i=0; i<8; i++)
            Cerr << sa[i] << " ";
          Cerr << finl;
          exit();
        }
      else if (n>1)
        {
          Cerr<<"Failure of the algorithm in Hexaedre_VEF::reordonner"<<finl;
          Cerr<<"many permutations possibles"<<finl;
          Cerr << "Here is the connectivity element-node of the cell " << num_poly << " that raises problem:" << finl;
          for (int i=0; i<8; i++)
            Cerr << sa[i] << " ";
          Cerr << finl;
          Cerr << "Here is the new connectivity element-node of the cell " << num_poly << " that raises problem:" << finl;
          for (int i=0; i<8; i++)
            Cerr << elem(num_poly,i) << " ";
          Cerr << finl;
// exit();
        }
      {
        for (int i=4; i<8; i++)
          elem(num_poly,i)=sa[perm(perm_valid,i-4)+4];
        if(perm_valid!=0)
          Cerr<<" we carried out the permutation "<<perm_valid<<" on the element "<<num_poly<<finl;
      }
    }
}
References Cerr, Zone::domaine(), Process::exit(), finl, Zone::les_elems(), Domaine::les_sommets(), Elem_geom_base::ma_zone, Zone::nb_elem(), reordonne(), test(), and Ref_Zone::valeur().
self_cast() [1/2]
const Hexaedre_VEF & Hexaedre_VEF::self_cast (const Objet_U & r) static
Definition at line 19 of file Hexaedre_VEF.cpp.
self_cast() [2/2]
Hexaedre_VEF & Hexaedre_VEF::self_cast (Objet_U & r) static
Definition at line 19 of file Hexaedre_VEF.cpp.
taille_memoire()
unsigned Hexaedre_VEF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Hexaedre_VEF.cpp.
type_face()
Type_Face Hexaedre_VEF::type_face (int i = 0) const inline override virtual
Renvoie le i-ieme type de face.
Un Hexaedre_VEF n'a qu'un seul type de face.
Returns
Type_Face
Signification: un type de face
Contraintes: toujours egal a Faces::triangle_3D (si i=0)
Implements Elem_geom_base.
Definition at line 422 of file Hexaedre_VEF.h.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A VEF hexahedron (Hexaedre_VEF) has not " << i << " types of face" << finl;
      exit();
    }
  return Faces::quadrangle_3D;
}
References Cerr, Process::exit(), finl, and Faces::quadrangle_3D.
Member Data Documentation
info_obj
const Type_info Hexaedre_VEF::info_obj static
Definition at line 39 of file Hexaedre_VEF.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Hexaedre_VEF.h
src/Kernel/Geometrie/Hexaedre_VEF.cpp