TRUST: Champ_Don Class Reference
Champ_Don Class Reference
classe Champ_Don
Classe generique de la hierarchie des champs donnes, un objet
Champ_Don peut referencer n'importe quel objet derivant de
Champ_Don_base.
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
#include <Champ_Don.h>
Public Member Functions
Champ_Don ()
~Champ_Don ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & valeurs () override
Appel a l'objet sous-jacent.
Renvoie le tableau des valeurs.
const DoubleTab & valeurs () const override
Appel a l'objet sous-jacent.
Renvoie le tableau des valeurs.
(version const)
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
int fixer_nb_valeurs_nodales (int)
Appel a l'objet sous-jacent
Fixe le nombre de degres de liberte par composante.
int nb_valeurs_nodales () const
Appel a l'objet sous-jacent
Renvoie le nombre de degres de liberte par composante.
int nb_comp () const
Appel a l'objet sous-jacent
Renvoie le nombre de composantes du champ.
Champ_base & affecter_ (const Champ_base &ch)
Appel a l'objet sous-jacent
Affectation d'un Champ_Base dans un Champ_Don.
Champ_base & affecter_compo (const Champ_base &, int)
Appel a l'objet sous-jacent
Affectation d'une composante d'un Champ_Base dans la meme
composante d'un Champ_Don.
void mettre_a_jour (double temps)
Appel a l'objet sous-jacent
Provoque la mise a jour du champ si il est instationnaire.
int initialiser (const double temps)
Appel a l'objet sous-jacent
Provoque l'initialisation du champ si necessaire.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Deriv_Champ_Don_base
~Deriv_Champ_Don_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Champ_Don_base ()
Deriv_Champ_Don_base (const Deriv_Champ_Don_base &)
const Champ_Don_base & valeur () const
Champ_Don_base & valeur ()
const Champ_Don_base * operator-> () const
Champ_Don_base * operator-> ()
const Deriv_Champ_Don_base & operator= (const Champ_Don_base &)
const Deriv_Champ_Don_base & operator= (const Deriv_Champ_Don_base &)
operator const Champ_Don_base & () const
operator Champ_Don_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Don & self_cast (Objet_U &)
static const Champ_Don & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Champ_Don_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Champ_Don_base & self_cast (Objet_U &)
static const Deriv_Champ_Don_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Champ_Don_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le champ sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture du champ a partir d'un flot d'entree.
Protected Member Functions inherited from Deriv_Champ_Don_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
classe Champ_Don
Classe generique de la hierarchie des champs donnes, un objet
Champ_Don peut referencer n'importe quel objet derivant de
Champ_Don_base.
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
Definition at line 40 of file Champ_Don.h.
Constructor & Destructor Documentation
Champ_Don()
Champ_Don::Champ_Don ()
Definition at line 19 of file Champ_Don.cpp.
~Champ_Don()
Champ_Don::~Champ_Don ()
Definition at line 19 of file Champ_Don.cpp.
Member Function Documentation
affecter_()
Champ_base & Champ_Don::affecter_ (const Champ_base & ch) inline
Appel a l'objet sous-jacent
Affectation d'un Champ_Base dans un Champ_Don.
Returns
Champ_base&
Signification: le champ affecte (upcaste en Champ_base&)
Contraintes:
Definition at line 175 of file Champ_Don.h.
{
  return valeur().affecter(ch);
}
References Champ_base::affecter(), and Deriv_Champ_Don_base::valeur().
Referenced by Milieu_base::discretiser(), and Fluide_base::discretiser().
affecter_compo()
Champ_base & Champ_Don::affecter_compo (const Champ_base & ch, int compo) inline
Appel a l'objet sous-jacent
Affectation d'une composante d'un Champ_Base dans la meme
composante d'un Champ_Don.
Returns
Champ_base&
Signification: le champ affecte (upcaste en Champ_base&)
Contraintes:
Definition at line 202 of file Champ_Don.h.
{
  return valeur().affecter_compo(ch, compo);
}
References Champ_Don_base::affecter_compo(), and Deriv_Champ_Don_base::valeur().
cree_instance()
Objet_U * Champ_Don::cree_instance () static
Definition at line 19 of file Champ_Don.cpp.
duplique()
int Champ_Don::duplique () const override virtual
Reimplemented from Deriv_Champ_Don_base.
Definition at line 19 of file Champ_Don.cpp.
fixer_nb_valeurs_nodales()
int Champ_Don::fixer_nb_valeurs_nodales (int nb_noeuds) inline
Appel a l'objet sous-jacent
Fixe le nombre de degres de liberte par composante.
Returns
int
Signification: le nombre de degres de liberte par composante
Contraintes:
Definition at line 115 of file Champ_Don.h.
{
  return valeur().fixer_nb_valeurs_nodales(nb_noeuds);
}
References Champ_Don_base::fixer_nb_valeurs_nodales(), and Deriv_Champ_Don_base::valeur().
get_info()
const Type_info * Champ_Don::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Champ_Don_base.
Definition at line 19 of file Champ_Don.cpp.
info()
const Type_info * Champ_Don::info () static
Definition at line 19 of file Champ_Don.cpp.
initialiser()
int Champ_Don::initialiser (const double temps) inline
Appel a l'objet sous-jacent
Provoque l'initialisation du champ si necessaire.
Definition at line 220 of file Champ_Don.h.
{
  return valeur().initialiser(temps);
}
References Champ_Don_base::initialiser(), and Deriv_Champ_Don_base::valeur().
Referenced by Milieu_base::initialiser(), Fluide_Dilatable_base::initialiser(), Constituant::initialiser(), Fluide_base::initialiser(), Fluide_reel_base::initialiser(), and Fluide_Dilatable_base::initialiser_radiatives().
mettre_a_jour()
void Champ_Don::mettre_a_jour (double temps) inline
Appel a l'objet sous-jacent
Provoque la mise a jour du champ si il est instationnaire.
Definition at line 212 of file Champ_Don.h.
{
  valeur().mettre_a_jour(temps);
}
References Champ_Don_base::mettre_a_jour(), and Deriv_Champ_Don_base::valeur().
Referenced by Loi_Etat_base::calculer_mu(), Loi_Etat_Multi_GP_base::calculer_mu(), Milieu_base::mettre_a_jour(), DP_Impose::mettre_a_jour(), Terme_Source_Constituant::mettre_a_jour(), Terme_Puissance_Thermique::mettre_a_jour(), Champ_front_MED::mettre_a_jour(), Perte_Charge_Anisotrope_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Circulaire_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Directionnelle_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Isotrope_PolyMAC_Face::mettre_a_jour(), Terme_Source_Acceleration::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour(), Perte_Charge_Anisotrope_VEF_P1NC::mettre_a_jour(), Perte_Charge_Circulaire_VEF_P1NC::mettre_a_jour(), Perte_Charge_Directionnelle_VEF_P1NC::mettre_a_jour(), Perte_Charge_Isotrope_VEF_P1NC::mettre_a_jour(), Source_Qdm_EF::mettre_a_jour(), Source_Scalaire_EF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::mettre_a_jour(), Terme_Source_Qdm_Face_PolyMAC::mettre_a_jour(), Fluide_Dilatable_base::mettre_a_jour(), Constituant::mettre_a_jour(), Fluide_base::mettre_a_jour(), Fluide_Ostwald::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::mettre_a_jour(), Terme_Source_Qdm_VDF_Face::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Terme_Source_Qdm_VEF_Face::mettre_a_jour(), Fluide_Weakly_Compressible::mettre_a_jour_bis(), Fluide_Dilatable_base::update_pressure_fields(), Fluide_Weakly_Compressible::update_pressure_fields(), and Loi_Etat_Multi_GP_WC::update_Yn_values().
nb_comp()
int Champ_Don::nb_comp () const inline
Appel a l'objet sous-jacent
Renvoie le nombre de composantes du champ.
Returns
int
Signification: le nombre de composantes du champ
Contraintes:
Definition at line 135 of file Champ_Don.h.
{
  return valeur().nb_comp();
}
References Field_base::nb_comp(), and Deriv_Champ_Don_base::valeur().
Referenced by Echange_contact_VDF::calculer_h_autre_pb(), calculer_h_distant(), calculer_h_local(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_h_solide(), Echange_contact_Correlation_VEF::completer(), Milieu_base::discretiser(), Echange_contact_VDF::initialiser(), Equation_base::lire_cond_init(), Navier_Stokes_std::lire_cond_init(), QDM_Multiphase::lire_cond_init(), Echange_contact_VDF::mettre_a_jour(), T_It_VDF_Elem< _TYPE_ >::modifier_flux(), Op_VEF_Face::modifier_flux(), Constituant::nb_constituants(), Source_Qdm_EF::readOn(), Source_Scalaire_EF::readOn(), Perte_Charge_Anisotrope_PolyMAC_Face::readOn(), Perte_Charge_Circulaire_PolyMAC_Face::readOn(), Perte_Charge_Directionnelle_PolyMAC_Face::readOn(), Perte_Charge_Isotrope_PolyMAC_Face::readOn(), Terme_Source_Qdm_Face_PolyMAC::readOn(), Terme_Source_Qdm_VDF_Face::readOn(), Perte_Charge_Anisotrope_VEF_P1NC::readOn(), Perte_Charge_Circulaire_VEF_P1NC::readOn(), Perte_Charge_Directionnelle_VEF_P1NC::readOn(), Perte_Charge_Isotrope_VEF_P1NC::readOn(), and Terme_Source_Qdm_VEF_Face::readOn().
nb_valeurs_nodales()
int Champ_Don::nb_valeurs_nodales () const inline
Appel a l'objet sous-jacent
Renvoie le nombre de degres de liberte par composante.
Returns
int
Signification: le nombre de degres de liberte par composante
Contraintes:
Definition at line 155 of file Champ_Don.h.
{
  return valeur().nb_valeurs_nodales();
}
References Champ_Don_base::nb_valeurs_nodales(), and Deriv_Champ_Don_base::valeur().
Referenced by Fluide_base::initialiser(), Fluide_Dilatable_base::initialiser_radiatives(), and Fluide_base::mettre_a_jour().
operator const DoubleTab &()
Champ_Don::operator const DoubleTab & () const inline delete
operator DoubleTab &()
Champ_Don::operator DoubleTab & () inline delete
printOn()
Sortie & Champ_Don::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime le champ sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Champ_Don_base.
Definition at line 37 of file Champ_Don.cpp.
{
  return DERIV(Champ_Don_base)::printOn(os);
}
References DERIV, and printOn().
Referenced by printOn().
readOn()
Entree & Champ_Don::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Entree&)
Lecture du champ a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Champ_Don_base.
Definition at line 58 of file Champ_Don.cpp.
{
  return DERIV(Champ_Don_base)::readOn(is);
}
References DERIV, and readOn().
Referenced by readOn().
self_cast() [1/2]
const Champ_Don & Champ_Don::self_cast (const Objet_U & r) static
Definition at line 19 of file Champ_Don.cpp.
self_cast() [2/2]
Champ_Don & Champ_Don::self_cast (Objet_U & r) static
Definition at line 19 of file Champ_Don.cpp.
taille_memoire()
unsigned Champ_Don::taille_memoire () const override virtual
Reimplemented from Deriv_Champ_Don_base.
Definition at line 19 of file Champ_Don.cpp.
valeurs() [1/6]
const DoubleTab & Champ_Don::valeurs () const inline override virtual
Appel a l'objet sous-jacent.
Renvoie le tableau des valeurs.
(version const)
Returns
DoubleTab&
Signification: le tableau des valeurs du champ
Contraintes: reference constante
Implements Champ_Proto.
Definition at line 95 of file Champ_Don.h.
{
  return valeur().valeurs();
}
References Deriv_Champ_Don_base::valeur(), and Champ_Don_base::valeurs().
valeurs() [2/6]
virtual const DoubleTab & Champ_Proto::valeurs () const virtual
Implements Champ_Proto.
valeurs() [3/6]
DoubleTab & Champ_Don::valeurs () inline override virtual
Appel a l'objet sous-jacent.
Renvoie le tableau des valeurs.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ
Contraintes:
Implements Champ_Proto.
Definition at line 74 of file Champ_Don.h.
{
  return valeur().valeurs();
}
References Deriv_Champ_Don_base::valeur(), and Champ_Don_base::valeurs().
Referenced by Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Source_PDF_EF::ajouter_(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC::ajouter_blocs(), ajouter_bord(), Convection_Diffusion_Temperature::assembler(), Convection_Diffusion_Temperature::assembler_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Eval_Puiss_Th_EF::associer_champs(), Eval_Puiss_Th_PolyMAC_Elem::associer_champs(), Eval_Source_C_PolyMAC_Elem::associer_champs(), Eval_Puiss_Th_VDF_Elem::associer_champs(), Eval_Source_C_VDF_Elem::associer_champs(), Eval_Puiss_Th_VEF_Face::associer_champs(), Eval_Source_C_VEF_Face::associer_champs(), Source_PDF_EF::associer_pb(), Eval_Puiss_Th_QC_EF::associer_puissance(), Eval_Puiss_Th_QC_VEF_Face::associer_puissance(), Eval_Puiss_Th_QC_VDF_Elem::associer_puissance(), Champ_front_contact_VEF::calcul_coeff_amort(), Champ_front_contact_VEF::calcul_grads_locaux(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Milieu_base::calculer_alpha(), Loi_Etat_base::calculer_alpha(), Loi_Etat_GP_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_Cp(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Fluide_base::calculer_e_int(), Traitement_particulier_NS_EC::calculer_Ec(), calculer_h_distant(), calculer_h_local(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_h_solide(), Loi_Etat_base::calculer_lambda(), Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_GR_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_lambda(), Loi_Etat_Multi_GP_WC::calculer_masse_molaire(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Champ_Ostwald_VDF::calculer_mu(), Champ_Ostwald_VEF::calculer_mu(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Loi_Etat_Binaire_GP_base::calculer_mu_wilke(), Loi_Etat_Multi_GP_WC::calculer_mu_wilke(), Loi_Etat_base::calculer_nu(), Fluide_base::calculer_nu(), Loi_Etat_Binaire_GP_base::calculer_nu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_nu_sur_Sc(), Fluide_Weakly_Compressible::calculer_pression_hydro(), Fluide_Dilatable_base::calculer_pression_tot(), Loi_Etat_Multi_GP_WC::calculer_tab_Cp(), Loi_Etat_Multi_GP_base::calculer_tab_mu(), Fluide_Weakly_Compressible::completer(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Source_PDF_EF::contribuer_a_avec(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), Fluide_Dilatable_base::creer_champs_non_lus(), Fluide_base::creer_nu(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Source_PDF_EF::impr(), Champ_Ostwald_VEF::init_mu(), Loi_Etat_GP_base::initialiser(), Loi_Etat_GR_base::initialiser(), Fluide_base::initialiser(), Fluide_Weakly_Compressible::initialiser_pth_for_EOS(), Fluide_Weakly_Compressible::initialiser_pth_xyz(), Fluide_Dilatable_base::initialiser_radiatives(), Loi_Etat_rhoT_GP_QC::initialiser_rho(), Diametre_hyd_champ::interpreter(), Porosites_champ::interpreter(), Loi_Fermeture_Test::mettre_a_jour(), Op_Moyenne::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Fluide_base::mettre_a_jour(), Reynolds_maille_Champ_Face::mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson(), Terme_Puissance_Thermique::puissance_thermique(), Loi_Etat_Multi_GP_WC::readOn(), Fluide_Weakly_Compressible::remplir_champ_pression_for_EOS(), Loi_Etat_GP_base::remplir_T(), Loi_Etat_GR_base::remplir_T(), Source_PDF_EF::rotate_imposed_velocity(), Fluide_Dilatable_base::set_Cp(), Loi_Etat_base::temperature(), Fluide_Dilatable_base::temperature(), Convection_Diffusion_Temperature::transport_ibc(), Echange_interne_impose::update_inv_lambda(), Fluide_Weakly_Compressible::update_pressure_fields(), Milieu_base::update_rho_cp(), Fluide_Dilatable_base::update_rho_cp(), Loi_Etat_Multi_GP_WC::update_Yn_values(), and Source_PDF_EF::verif_ajouter_contrib().
valeurs() [4/6]
virtual DoubleTab & Champ_Proto::valeurs () virtual
Implements Champ_Proto.
valeurs() [5/6]
virtual DoubleTab & Champ_Proto::valeurs (double temps) inline virtual
Reimplemented from Champ_Proto.
Definition at line 50 of file Champ_Proto.h.
{ return valeurs(); }
valeurs() [6/6]
virtual const DoubleTab & Champ_Proto::valeurs (double temps) const inline virtual
Reimplemented from Champ_Proto.
Definition at line 51 of file Champ_Proto.h.
{ return valeurs(); }
Member Data Documentation
info_obj
const Type_info Champ_Don::info_obj static
Definition at line 42 of file Champ_Don.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_Don.h
src/Kernel/Framework/Champ_Don.cpp