TRUST: Op_Diff_VEF_Anisotrope_Face Class Reference
Op_Diff_VEF_Anisotrope_Face Class Reference
: class Op_Diff_VEF_Anisotrope_Face
<Description of class Op_Diff_VEF_Anisotrope_Face>
#include <Op_Diff_VEF_Anisotrope_Face.h>
Public Member Functions
Op_Diff_VEF_Anisotrope_Face ()
~Op_Diff_VEF_Anisotrope_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_diffusivite (const Champ_base &) override
associe le champ de diffusivite
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
const Champ_base & diffusivite () const override
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
void verifier () const
void dimensionner (Matrice_Morse &) const override
on dimensionne notre matrice.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
on assemble la matrice.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_multi_scalaire (const DoubleTab &, Matrice_Morse &) const
void ajouter_cas_scalaire (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF) const
void ajouter_cas_vectoriel (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
void ajouter_cas_multi_scalaire (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
Public Member Functions inherited from Op_Diff_VEF_base
Op_Diff_VEF_base ()
~Op_Diff_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
double viscA (int face_i, int face_j, int num_elem, double diffu) const
double viscA (int face_i, int face_j, int num_elem, DoubleTab &diffu) const
double viscA (int face_i, int face_j, int num_elem, ArrOfDouble &diffu_ci_cj_elem) const
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_nu (DoubleTab &) const
int phi_psi_diffuse (const Equation_base &eq) const
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Diff_VEF_Anisotrope_Face & self_cast (Objet_U &)
static const Op_Diff_VEF_Anisotrope_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_VEF_base
static const Type_info * info ()
static Op_Diff_VEF_base & self_cast (Objet_U &)
static const Op_Diff_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Diff_VEF_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
Ref_Champ_base diffusivite_
Protected Attributes inherited from Op_Diff_VEF_base
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base inconnue_
DoubleTab nu_
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
: class Op_Diff_VEF_Anisotrope_Face
<Description of class Op_Diff_VEF_Anisotrope_Face>
Definition at line 33 of file Op_Diff_VEF_Anisotrope_Face.h.
Constructor & Destructor Documentation
Op_Diff_VEF_Anisotrope_Face()
Op_Diff_VEF_Anisotrope_Face::Op_Diff_VEF_Anisotrope_Face ()
Definition at line 36 of file Op_Diff_VEF_Anisotrope_Face.cpp.
~Op_Diff_VEF_Anisotrope_Face()
Op_Diff_VEF_Anisotrope_Face::~Op_Diff_VEF_Anisotrope_Face ()
Definition at line 36 of file Op_Diff_VEF_Anisotrope_Face.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Diff_VEF_Anisotrope_Face::ajouter (const DoubleTab & inconnue_org, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 485 of file Op_Diff_VEF_Anisotrope_Face.cpp.
{
  remplir_nu(nu_);
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  int nb_comp = 1;
  int nb_dim = resu.nb_dim();
  if(nb_dim==2)
    nb_comp=resu.dimension(1);
  DoubleTab nu;
  DoubleTab tab_inconnue;
  int marq=phi_psi_diffuse(equation());
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
  modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
  const DoubleTab& inconnue=modif_par_porosite_si_flag(inconnue_org,tab_inconnue,marq,porosite_face);
  const Champ_base& inco = equation().inconnue().valeur();
  const Nature_du_champ nature_champ = inco.nature_du_champ();
  if(nature_champ==scalaire)
    ajouter_cas_scalaire(inconnue, resu, flux_bords_, nu, zone_Cl_VEF, zone_VEF);
  else if (nature_champ==vectoriel)
    ajouter_cas_vectoriel(inconnue, resu, flux_bords_, nu, zone_Cl_VEF, zone_VEF,nb_comp);
  else if (nature_champ==multi_scalaire)
    ajouter_cas_multi_scalaire(inconnue, resu, flux_bords_, nu, zone_Cl_VEF, zone_VEF,nb_comp);
  modifier_flux(*this);
  return resu;
}
References ajouter_cas_multi_scalaire(), ajouter_cas_scalaire(), ajouter_cas_vectoriel(), TRUSTTab< _TYPE_ >::dimension(), MorEqn::equation(), Operateur_base::flux_bords_, Equation_base::inconnue(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, modif_par_porosite_si_flag(), Op_VEF_Face::modifier_flux(), multi_scalaire, Field_base::nature_du_champ(), TRUSTTab< _TYPE_ >::nb_dim(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Op_Diff_VEF_base::remplir_nu(), scalaire, Deriv_Champ_Inc_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and vectoriel.
Referenced by calculer().
ajouter_cas_multi_scalaire()
void Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Zone_Cl_VEF & zone_Cl_VEF, const Zone_VEF & zone_VEF, int nb_comp) const
< real face
< real faces
< it is a virtual face
< dealing with real faces
Definition at line 264 of file Op_Diff_VEF_Anisotrope_Face.cpp.
{
  const int nb_cols_nu = nu.dimension(1);
  assert(nb_cols_nu == dimension*dimension*nb_comp*nb_comp);
  const IntTab& elemfaces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int i0,j,num_face;
  int nb_faces = zone_VEF.nb_faces();
  int n_bord;
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  double valA,flux0;
  DoubleVect n(Objet_U::dimension);
  DoubleTrav Tgrad(Objet_U::dimension,Objet_U::dimension);
// dimensionning and initializing flow balance tabulars
  tab_flux_bords.resize(zone_VEF.nb_faces_bord(),nb_comp);
  tab_flux_bords=0.;
  assert( nb_comp>1 );
  int nb_bords=zone_VEF.nb_front_Cl();
  int ind_face;
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = 0;
      int num2 = le_bord.nb_faces_tot();
      int nb_faces_bord_reel = le_bord.nb_faces();
// periodic case
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int fac_asso;
          for (ind_face=num1; ind_face<nb_faces_bord_reel; ind_face++)
            {
              fac_asso = la_cl_perio.face_associee(ind_face);
              fac_asso = le_bord.num_face(fac_asso);
              num_face = le_bord.num_face(ind_face);
              for (int kk=0; kk<2; kk++)
                {
                  int elem = face_voisins(num_face, kk);
                  for (i0=0; i0<nb_faces_elem; i0++)
                    {
                      if ( ( (j= elemfaces(elem,i0)) > num_face ) && (j != fac_asso ) )
{
                          for(int c1=0; c1<nb_comp; c1++)
{
                              for(int c2=0; c2<nb_comp; c2++)
{
                                  int diffusivity_index = c1*nb_comp + c2;
                                  int start_id = elem*nb_cols_nu+diffusivity_index*dimension*dimension;
                                  ArrOfDouble diffu_c1_c2_elem;
                                  diffu_c1_c2_elem.ref_array(nu, start_id ,dimension*dimension);
                                  valA = viscA(num_face,j,elem,diffu_c1_c2_elem);
                                  resu(num_face,c1)+=valA*inconnue(j,c2);
                                  resu(num_face,c1)-=valA*inconnue(num_face,c2);
                                  if(j<nb_faces) //!< real face
{
                                      resu(j,c1)+=0.5*valA*inconnue(num_face,c2);
                                      resu(j,c1)-=0.5*valA*inconnue(j,c2);
                                    }
                                }
                            }
                        }
                    }//loop over i0 (nb_faces) for elem1
                }//loop over kk
            } //!< ind face
        }//!< end periodic
      else
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              num_face = le_bord.num_face(ind_face);
              int elem=face_voisins(num_face,0);
// Loop over faces :
              for (int i=0; i<nb_faces_elem; i++)
                if (( (j= elemfaces(elem,i)) > num_face ) || (ind_face>=nb_faces_bord_reel))
                  {
                    for(int c1=0; c1<nb_comp; c1++)
                      {
                        for(int c2=0; c2<nb_comp; c2++)
{
                            int diffusivity_index = c1*nb_comp + c2;
                            int start_id = elem*nb_cols_nu+diffusivity_index*dimension*dimension;
                            ArrOfDouble diffu_c1_c2_elem;
                            diffu_c1_c2_elem.ref_array(nu, start_id ,dimension*dimension);
                            valA = viscA(num_face,j,elem,diffu_c1_c2_elem);
                            if (ind_face<nb_faces_bord_reel)
{
                                double flux=valA*(inconnue(j,c2)-inconnue(num_face,c2));
                                resu(num_face,c1)+=flux;
                                tab_flux_bords(num_face,c1)+=flux;
                              }
                            if(j<nb_faces) //!< real faces
{
                                resu(j,c1)+=valA*inconnue(num_face,c2);
                                resu(j,c1)-=valA*inconnue(j,c2);
                              }
                          }//!< loop c2
                      }//!< loop c1
                  } //!< j
            }//end of ind_face loop
        }//else
    }//end for the boundaries loop
// dealing now with internal faces
  for (num_face=zone_VEF.premiere_face_int(); num_face<nb_faces; num_face++)
    {
      for (int k=0; k<2; k++)
        {
          int elem = face_voisins(num_face,k);
          for (i0=0; i0<nb_faces_elem; i0++)
            {
              if ( (j= elemfaces(elem,i0)) > num_face )
                {
                  int el1,el2;
                  int contrib=1;
                  if(j>=nb_faces) //!< it is a virtual face
                    {
                      el1 = face_voisins(j,0);
                      el2 = face_voisins(j,1);
                      if((el1==-1)||(el2==-1))
                        contrib=0;
                    }
                  if(contrib)
                    {
                      for(int c1=0; c1<nb_comp; c1++)
                        for(int c2=0; c2<nb_comp; c2++)
{
                            int diffusivity_index = c1*nb_comp + c2;
                            int start_id = elem*nb_cols_nu+diffusivity_index*dimension*dimension;
                            ArrOfDouble diffu_c1_c2_elem;
                            diffu_c1_c2_elem.ref_array(nu, start_id ,dimension*dimension);
                            valA = viscA(num_face,j,elem,diffu_c1_c2_elem);
                            resu(num_face,c1)+=valA*inconnue(j,c2);
                            resu(num_face,c1)-=valA*inconnue(num_face,c2);
                            if(j<nb_faces) //!< dealing with real faces
{
                                resu(j,c1)+=valA*inconnue(num_face,c2);
                                resu(j,c1)-=valA*inconnue(j,c2);
                              }
                            else
{
// the face is virtual
                              }
                          }
                    }
                }
            }//loop i0 over elem faces
        }//loop over k
    }//loop over faces
// Neumann
// On se base sur ce qui est fait pour le cas scalaire
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              for (int nc=0; nc<nb_comp; nc++)
                {
                  flux0=la_cl_paroi.flux_impose(face-ndeb,nc)*zone_VEF.surface(face);
                  resu(face,nc) += flux0;
                  tab_flux_bords(face,nc) = flux0;
                }
            }
        }
      else if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Echange_externe_impose& la_cl_paroi = ref_cast(Echange_externe_impose, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              for (int nc=0; nc<nb_comp; nc++)
                {
                  flux0=la_cl_paroi.h_imp(face-ndeb,nc)*(la_cl_paroi.T_ext(face-ndeb,nc)-inconnue(face,nc))*zone_VEF.surface(face);
                  resu(face,nc) += flux0;
                  tab_flux_bords(face,nc) = flux0;
                }
            }
        }
      else if (sub_type(Neumann_homogene,la_cl.valeur())
               || sub_type(Symetrie,la_cl.valeur())
               || sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            for (int nc=0; nc<nb_comp; nc++)
              tab_flux_bords(face,nc) = 0.;
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VF::face_voisins(), Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Echange_impose_base::h_imp(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), TRUSTArray< _TYPE_ >::ref_array(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Zone_VF::surface(), Echange_impose_base::T_ext(), Deriv_Cond_lim_base::valeur(), Op_Diff_VEF_base::viscA(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_cas_scalaire()
void Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Zone_Cl_VEF & zone_Cl_VEF, const Zone_VEF & zone_VEF) const
< face reelle
< Il n'y a qu'une seule composante, donc on traite une equation scalaire (pas la vitesse) on a pas a utiliser le tau tangentiel (les lois de paroi thermiques ne calculent pas d'echange turbulent a la paroi pour l'instant
< face reelle
< C'est une face virtuelle
< On traite les faces reelles
Definition at line 68 of file Op_Diff_VEF_Anisotrope_Face.cpp.
{
// assurer on a un tableau bidimensionnel
  assert(nu.nb_dim()==2);
// assurer vrai nombre de composants pour l'anisotropie (9 pour 3d et 4 pour 2d)
  assert(nu.dimension(1)==dimension*dimension);
  const IntTab& elemfaces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int i,j,num_face;
  int nb_faces = zone_VEF.nb_faces();
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  double valA,flux;
  int n_bord, ind_face;
  int nb_bords=zone_VEF.nb_front_Cl();
// On dimensionne et initialise le tableau des bilans de flux:
  tab_flux_bords.resize(zone_VEF.nb_faces_bord(),1);
  tab_flux_bords=0.;
  const int premiere_face_int=zone_VEF.premiere_face_int();
// On traite les faces bord
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// const IntTab& elemfaces = zone_VEF.elem_faces();
      int num1=0;
      int num2=le_bord.nb_faces_tot();
      int nb_faces_bord_reel = le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int fac_asso;
          for (ind_face=num1; ind_face<nb_faces_bord_reel; ind_face++)
            {
              num_face = le_bord.num_face(ind_face);
              fac_asso = la_cl_perio.face_associee(ind_face);
              fac_asso = le_bord.num_face(fac_asso);
              for (int kk=0; kk<2; kk++)
                {
                  int elem = face_voisins(num_face,kk);
                  for (i=0; i<nb_faces_elem; i++)
                    {
                      if ( ( (j= elemfaces(elem,i)) > num_face ) && (j != fac_asso) )
{
                          valA = viscA(num_face,j,elem,nu);
                          resu(num_face)+=valA*inconnue(j);
                          resu(num_face)-=valA*inconnue(num_face);
                          if(j<nb_faces) //!< face reelle
{
                              resu(j)+=0.5*valA*inconnue(num_face);
                              resu(j)-=0.5*valA*inconnue(j);
                            }
                        }
                    }
                }
            }
        }
      else   //!< Il n'y a qu'une seule composante, donc on traite une equation scalaire (pas la vitesse) on a pas a utiliser le tau tangentiel (les lois de paroi thermiques ne calculent pas d'echange turbulent a la paroi pour l'instant
//
//
//
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              num_face = le_bord.num_face(ind_face);
              int elem = face_voisins(num_face,0);
              for (i=0; i<nb_faces_elem; i++)
                {
                  if (( (j= elemfaces(elem,i)) > num_face ) || (ind_face>=nb_faces_bord_reel))
                    {
                      valA = viscA(num_face,j,elem,nu);
                      if (ind_face<nb_faces_bord_reel)
{
                          flux=valA*(inconnue(j)-inconnue(num_face));
// PL : c'est bien un - ici pour flux_bords. Cette valeur est ensuite
// ecrasee pour les bords avec Neumann et ne sert donc que pour les bords
// avec Dirichlet ou le volume de controle est nul
                          tab_flux_bords(num_face,0)-=flux;
                          resu(num_face)+=flux;
                        }
                      if(j<nb_faces) //!< face reelle
{
                          flux=valA*(inconnue(num_face)-inconnue(j));
                          if (j<premiere_face_int)
                            tab_flux_bords(j,0)-=flux;
                          resu(j)+=flux;
                        }
                    }
                }
            }
        }
    }
// Faces internes :
  for (num_face=premiere_face_int; num_face<nb_faces; num_face++)
    {
      for (int k=0; k<2; k++)
        {
          int elem = face_voisins(num_face,k);
          {
            for (i=0; i<nb_faces_elem; i++)
              {
                j=elemfaces(elem,i);
                if ( j  > num_face )
                  {
                    int el1,el2;
                    int contrib=1;
                    if(j>=nb_faces) //!< C'est une face virtuelle
                      {
                        el1 = face_voisins(j,0);
                        el2 = face_voisins(j,1);
                        if((el1==-1)||(el2==-1))
                          contrib=0;
                      }
                    if(contrib)
                      {
                        valA = viscA(num_face,j,elem,nu);
                        resu(num_face)+=valA*inconnue(j);
                        resu(num_face)-=valA*inconnue(num_face);
                        if(j<nb_faces) //!< On traite les faces reelles
{
                            resu(j)+=valA*inconnue(num_face);
                            resu(j)-=valA*inconnue(j);
                          }
                      }
                  }
              }
          }
        }
    }
// Neumann :
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              flux=la_cl_paroi.flux_impose(face-ndeb)*zone_VEF.surface(face);
              resu[face] += flux;
              tab_flux_bords(face,0) = flux;
            }
        }
      else if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Echange_externe_impose& la_cl_paroi = ref_cast(Echange_externe_impose, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              flux=la_cl_paroi.h_imp(face-ndeb)*(la_cl_paroi.T_ext(face-ndeb)-inconnue(face))*zone_VEF.surface(face);
              resu[face] += flux;
              tab_flux_bords(face,0) = flux;
            }
        }
      else if (sub_type(Neumann_homogene,la_cl.valeur())
               || sub_type(Symetrie,la_cl.valeur())
               || sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            tab_flux_bords(face,0) = 0.;
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VF::face_voisins(), Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Echange_impose_base::h_imp(), Zone_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_ >::nb_dim(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Zone_VF::surface(), Echange_impose_base::T_ext(), Deriv_Cond_lim_base::valeur(), Op_Diff_VEF_base::viscA(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_cas_vectoriel()
void Op_Diff_VEF_Anisotrope_Face::ajouter_cas_vectoriel (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Zone_Cl_VEF & zone_Cl_VEF, const Zone_VEF & zone_VEF, int nb_comp) const
Definition at line 252 of file Op_Diff_VEF_Anisotrope_Face.cpp.
{
  Cerr << "Error in Op_Diff_VEF_Anisotrope_Face::ajouter_cas_vectoriel()" << finl;
  Cerr << "This case is not coded yet" << finl;
  Process::exit(-1);
}
References Cerr, Process::exit(), and finl.
Referenced by ajouter().
ajouter_contribution()
void Op_Diff_VEF_Anisotrope_Face::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
Definition at line 525 of file Op_Diff_VEF_Anisotrope_Face.cpp.
{
  modifier_matrice_pour_periodique_avant_contribuer(matrice,equation());
// On remplit le tableau nu car l'assemblage d'une
// matrice avec ajouter_contribution peut se faire
// avant le premier pas de temps
  remplir_nu(nu_);
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int n1 = zone_VEF.nb_faces();
  int nb_comp = 1;
  int nb_dim = transporte.nb_dim();
  DoubleTab nu;
  int marq=phi_psi_diffuse(equation());
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
  modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
  DoubleVect porosite_eventuelle(zone_VEF.porosite_face());
  if (!marq)
    porosite_eventuelle=1;
  if(nb_dim==2)
    nb_comp=transporte.dimension(1);
  int i,j,num_face;
  int elem1,elem2;
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  double val;
  int nb_bords=zone_VEF.nb_front_Cl();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = le_bord.num_premiere_face();
      int num2 = num1 + le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int fac_asso;
// on ne parcourt que la moitie des faces periodiques
// on copiera a la fin le resultat dans la face associe..
          int num2b=num1+le_bord.nb_faces()/2;
          for (num_face=num1; num_face<num2b; num_face++)
            {
              elem1 = face_voisins(num_face,0);
              elem2 = face_voisins(num_face,1);
              fac_asso = la_cl_perio.face_associee(num_face-num1)+num1;
              for (i=0; i<nb_faces_elem; i++)
                {
                  if ( (j=elem_faces(elem1,i)) > num_face )
                    {
                      val = viscA(num_face,j,elem1,nu);
                      for (int nc=0; nc<nb_comp; nc++)
{
                          int n0=num_face*nb_comp+nc;
                          int j0=j*nb_comp+nc;
                          matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                          matrice(n0,j0)-=val*porosite_eventuelle(j);
                          matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                          matrice(j0,j0)+=val*porosite_eventuelle(j);
                        }
                    }
                  if (elem2!=-1)
                    if ( (j=elem_faces(elem2,i)) > num_face )
                      {
                        val= viscA(num_face,j,elem2,nu);
                        for (int nc=0; nc<nb_comp; nc++)
{
                            int n0=num_face*nb_comp+nc;
                            int j0=j*nb_comp+nc;
                            int  n0perio=fac_asso*nb_comp+nc;
                            matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                            matrice(n0,j0)-=val*porosite_eventuelle(j);
                            matrice(j0,n0perio)-=val*porosite_eventuelle(num_face);
                            matrice(j0,j0)+=val*porosite_eventuelle(j);
                          }
                      }
                }
            }
        }
      else
        {
          for (num_face=num1; num_face<num2; num_face++)
            {
              elem1 = face_voisins(num_face,0);
              for (i=0; i<nb_faces_elem; i++)
                {
                  if ( (j= elem_faces(elem1,i)) > num_face )
                    {
                      val = viscA(num_face,j,elem1,nu);
                      for (int nc=0; nc<nb_comp; nc++)
{
                          int n0=num_face*nb_comp+nc;
                          int j0=j*nb_comp+nc;
                          matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                          matrice(n0,j0)-=val*porosite_eventuelle(j);
                          matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                          matrice(j0,j0)+=val*porosite_eventuelle(j);
                        }
                    }
                }
            }
        }
    }
  int n0 = zone_VEF.premiere_face_int();
  for (num_face=n0; num_face<n1; num_face++)
    {
      elem1 = face_voisins(num_face,0);
      elem2 = face_voisins(num_face,1);
      for (i=0; i<nb_faces_elem; i++)
        {
          if ( (j=elem_faces(elem1,i)) > num_face )
            {
              val = viscA(num_face,j,elem1,nu);
              for (int nc=0; nc<nb_comp; nc++)
                {
                  int nn0=num_face*nb_comp+nc;
                  int j0=j*nb_comp+nc;
                  matrice(nn0,nn0)+=val*porosite_eventuelle(num_face);
                  matrice(nn0,j0)-=val*porosite_eventuelle(j);
                  matrice(j0,nn0)-=val*porosite_eventuelle(num_face);
                  matrice(j0,j0)+=val*porosite_eventuelle(j);
                }
            }
          if (elem2!=-1)
            if ( (j=elem_faces(elem2,i)) > num_face )
              {
                val= viscA(num_face,j,elem2,nu);
                for (int nc=0; nc<nb_comp; nc++)
                  {
                    int nn0=num_face*nb_comp+nc;
                    int j0=j*nb_comp+nc;
                    matrice(nn0,nn0)+=val*porosite_eventuelle(num_face);
                    matrice(nn0,j0)-=val*porosite_eventuelle(j);
                    matrice(j0,nn0)-=val*porosite_eventuelle(num_face);
                    matrice(j0,j0)+=val*porosite_eventuelle(j);
                  }
              }
        }
    }
// Neumann :
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
        }
      else if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Echange_externe_impose& la_cl_paroi = ref_cast(Echange_externe_impose, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              matrice(face,face) += la_cl_paroi.h_imp(face-ndeb)*zone_VEF.face_surfaces(face);
            }
        }
      else if (sub_type(Neumann_homogene,la_cl.valeur())
               || sub_type(Symetrie,la_cl.valeur())
               || sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
        }
    }
  modifier_matrice_pour_periodique_apres_contribuer(matrice,equation());
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Echange_impose_base::h_imp(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), modif_par_porosite_si_flag(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), TRUSTTab< _TYPE_ >::nb_dim(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Zone_dis_base::nb_front_Cl(), Op_Diff_VEF_base::nu_, Front_VF::num_premiere_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, Op_Diff_VEF_base::remplir_nu(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Op_Diff_VEF_base::viscA(), and Zone_dis_base::zone().
Referenced by contribuer_a_avec().
ajouter_contribution_multi_scalaire()
void Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire (const DoubleTab & transporte, Matrice_Morse & matrice) const
Definition at line 715 of file Op_Diff_VEF_Anisotrope_Face.cpp.
{
  modifier_matrice_pour_periodique_avant_contribuer(matrice,equation());
// On remplit le tableau nu car l'assemblage d'une
// matrice avec ajouter_contribution peut se faire
// avant le premier pas de temps
  remplir_nu(nu_);
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int n1 = zone_VEF.nb_faces();
  int nb_comp = 1;
  int nb_dim = transporte.nb_dim();
  DoubleTab nu;
  int marq=phi_psi_diffuse(equation());
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
  modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
  DoubleVect porosite_eventuelle(zone_VEF.porosite_face());
  if (!marq)
    porosite_eventuelle=1;
  if(nb_dim==2)
    nb_comp=transporte.dimension(1);
  const int nb_cols_nu = nu.dimension(1);
  assert(nb_cols_nu == dimension*dimension*nb_comp*nb_comp);
  int i,j,num_face;
  int elem1,elem2;
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  double val;
  int nb_bords=zone_VEF.nb_front_Cl();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = le_bord.num_premiere_face();
      int num2 = num1 + le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int fac_asso;
// on ne parcourt que la moitie des faces periodiques
// on copiera a la fin le resultat dans la face associe..
          int num2b=num1+le_bord.nb_faces()/2;
          for (num_face=num1; num_face<num2b; num_face++)
            {
              elem1 = face_voisins(num_face,0);
              elem2 = face_voisins(num_face,1);
              fac_asso = la_cl_perio.face_associee(num_face-num1)+num1;
              for (i=0; i<nb_faces_elem; i++)
                {
                  if ( (j=elem_faces(elem1,i)) > num_face )
                    {
                      for(int c1=0; c1<nb_comp; c1++)
                        for(int c2=0; c2<nb_comp; c2++)
{
                            int diffusivity_index = c1*nb_comp + c2;
                            int start_id = elem1*nb_cols_nu+diffusivity_index*dimension*dimension;
                            ArrOfDouble diffu_c1_c2_elem;
                            diffu_c1_c2_elem.ref_array(nu, start_id ,dimension*dimension);
                            val = viscA(num_face,j,elem1,diffu_c1_c2_elem);
                            int n0=num_face*nb_comp+c1;
                            int j0=j*nb_comp+c1;
                            int n0b=num_face*nb_comp+c2;
                            int j0b=j*nb_comp+c2;
                            matrice(n0,n0b)+=val*porosite_eventuelle(num_face);
                            matrice(n0,j0b)-=val*porosite_eventuelle(j);
                            matrice(j0,n0b)-=val*porosite_eventuelle(num_face);
                            matrice(j0,j0b)+=val*porosite_eventuelle(j);
                          }
                    }
                  if (elem2!=-1)
                    if ( (j=elem_faces(elem2,i)) > num_face )
                      {
                        for (int nc=0; nc<nb_comp; nc++)
{
                            for(int c1=0; c1<nb_comp; c1++)
                              for(int c2=0; c2<nb_comp; c2++)
{
                                  int diffusivity_index = c1*nb_comp + c2;
                                  int start_id = elem1*nb_cols_nu+diffusivity_index*dimension*dimension;
                                  ArrOfDouble diffu_c1_c2_elem;
                                  diffu_c1_c2_elem.ref_array(nu, start_id ,dimension*dimension);
                                  val = viscA(num_face,j,elem1,diffu_c1_c2_elem);
                                  int n0=num_face*nb_comp+c1;
                                  int j0=j*nb_comp+c1;
                                  int n0b=num_face*nb_comp+c2;
                                  int j0b=j*nb_comp+c2;
                                  matrice(n0,n0b)+=val*porosite_eventuelle(num_face);
                                  matrice(n0,j0b)-=val*porosite_eventuelle(j);
                                  matrice(j0,n0b)-=val*porosite_eventuelle(num_face);
                                  matrice(j0,j0b)+=val*porosite_eventuelle(j);
                                  int  n0periob=fac_asso*nb_comp+c2;
                                  matrice(j0,n0periob)-=val*porosite_eventuelle(num_face);
                                }
                          }
                      }
                }
            }
        }
      else
        {
          for (num_face=num1; num_face<num2; num_face++)
            {
              elem1 = face_voisins(num_face,0);
              for (i=0; i<nb_faces_elem; i++)
                {
                  if ( (j= elem_faces(elem1,i)) > num_face )
                    {
                      for(int c1=0; c1<nb_comp; c1++)
                        for(int c2=0; c2<nb_comp; c2++)
{
                            int diffusivity_index = c1*nb_comp + c2;
                            int start_id = elem1*nb_cols_nu+diffusivity_index*dimension*dimension;
                            ArrOfDouble diffu_c1_c2_elem;
                            diffu_c1_c2_elem.ref_array(nu, start_id ,dimension*dimension);
                            val = viscA(num_face,j,elem1,diffu_c1_c2_elem);
                            int n0=num_face*nb_comp+c1;
                            int j0=j*nb_comp+c1;
                            int n0b=num_face*nb_comp+c2;
                            int j0b=j*nb_comp+c2;
                            matrice(n0,n0b)+=val*porosite_eventuelle(num_face);
                            matrice(n0,j0b)-=val*porosite_eventuelle(j);
                            matrice(j0,n0b)-=val*porosite_eventuelle(num_face);
                            matrice(j0,j0b)+=val*porosite_eventuelle(j);
                          }
                    }
                }
            }
        }
    }
  for (num_face=zone_VEF.premiere_face_int(); num_face<n1; num_face++)
    {
      elem1 = face_voisins(num_face,0);
      elem2 = face_voisins(num_face,1);
      for (i=0; i<nb_faces_elem; i++)
        {
          if ( (j=elem_faces(elem1,i)) > num_face )
            {
              for(int c1=0; c1<nb_comp; c1++)
                for(int c2=0; c2<nb_comp; c2++)
                  {
                    int diffusivity_index = c1*nb_comp + c2;
                    int start_id = elem1*nb_cols_nu+diffusivity_index*dimension*dimension;
                    ArrOfDouble diffu_c1_c2_elem;
                    diffu_c1_c2_elem.ref_array(nu, start_id ,dimension*dimension);
                    val = viscA(num_face,j,elem1,diffu_c1_c2_elem);
                    int n0=num_face*nb_comp+c1;
                    int j0=j*nb_comp+c1;
                    int n0b=num_face*nb_comp+c2;
                    int j0b=j*nb_comp+c2;
                    matrice(n0,n0b)+=val*porosite_eventuelle(num_face);
                    matrice(n0,j0b)-=val*porosite_eventuelle(j);
                    matrice(j0,n0b)-=val*porosite_eventuelle(num_face);
                    matrice(j0,j0b)+=val*porosite_eventuelle(j);
                  }
            }
          if (elem2!=-1)
            if ( (j=elem_faces(elem2,i)) > num_face )
              {
                for(int c1=0; c1<nb_comp; c1++)
                  for(int c2=0; c2<nb_comp; c2++)
                    {
                      int diffusivity_index = c1*nb_comp + c2;
                      int start_id = elem2*nb_cols_nu+diffusivity_index*dimension*dimension;
                      ArrOfDouble diffu_c1_c2_elem;
                      diffu_c1_c2_elem.ref_array(nu, start_id ,dimension*dimension);
                      val = viscA(num_face,j,elem2,diffu_c1_c2_elem);
                      int n0=num_face*nb_comp+c1;
                      int j0=j*nb_comp+c1;
                      int n0b=num_face*nb_comp+c2;
                      int j0b=j*nb_comp+c2;
                      matrice(n0,n0b)+=val*porosite_eventuelle(num_face);
                      matrice(n0,j0b)-=val*porosite_eventuelle(j);
                      matrice(j0,n0b)-=val*porosite_eventuelle(num_face);
                      matrice(j0,j0b)+=val*porosite_eventuelle(j);
                    }
              }
        }
    }
  modifier_matrice_pour_periodique_apres_contribuer(matrice,equation());
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), modif_par_porosite_si_flag(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), TRUSTTab< _TYPE_ >::nb_dim(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Zone_dis_base::nb_front_Cl(), Op_Diff_VEF_base::nu_, Front_VF::num_premiere_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), TRUSTArray< _TYPE_ >::ref_array(), ref_cast, Op_Diff_VEF_base::remplir_nu(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Op_Diff_VEF_base::viscA(), and Zone_dis_base::zone().
Referenced by contribuer_a_avec().
associer_diffusivite()
void Op_Diff_VEF_Anisotrope_Face::associer_diffusivite (const Champ_base & diffu) override virtual
associe le champ de diffusivite
Implements Operateur_Diff_base.
Definition at line 53 of file Op_Diff_VEF_Anisotrope_Face.cpp.
{
  diffusivite_ = diffu;
}
References diffusivite_.
calculer()
DoubleTab & Op_Diff_VEF_Anisotrope_Face::calculer (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 519 of file Op_Diff_VEF_Anisotrope_Face.cpp.
{
  resu = 0;
  return ajouter(inconnue,resu);
}
References ajouter().
Referenced by verifier().
completer()
void Op_Diff_VEF_Anisotrope_Face::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Definition at line 58 of file Op_Diff_VEF_Anisotrope_Face.cpp.
{
  Operateur_base::completer();
}
References Operateur_base::completer().
contribue_au_second_membre()
void Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre (DoubleTab & resu) const
Definition at line 930 of file Op_Diff_VEF_Anisotrope_Face.cpp.
{
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  int nb_comp = resu.line_size();
  int nb_bords=zone_VEF.nb_front_Cl();
// Partie imposee :
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            for (int comp=0; comp<nb_comp; comp++)
              resu(face,comp) += la_cl_paroi.flux_impose(face-ndeb,comp)*zone_VEF.surface(face);
        }
    }
}
References Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), ref_cast, sub_type, Zone_VF::surface(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
Referenced by contribuer_au_second_membre().
contribuer_a_avec()
void Op_Diff_VEF_Anisotrope_Face::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
on assemble la matrice.
Reimplemented from Operateur_base.
Definition at line 103 of file Op_Diff_VEF_Anisotrope_Face.h.
{
  const Champ_base& inconnue = equation().inconnue().valeur();
  const Nature_du_champ nature_champ = inconnue.nature_du_champ();
  if (nature_champ!=multi_scalaire)
    ajouter_contribution(inco, matrice);
  else
    ajouter_contribution_multi_scalaire(inco, matrice);
}
References ajouter_contribution(), ajouter_contribution_multi_scalaire(), MorEqn::equation(), Equation_base::inconnue(), multi_scalaire, Field_base::nature_du_champ(), and Deriv_Champ_Inc_base::valeur().
contribuer_au_second_membre()
void Op_Diff_VEF_Anisotrope_Face::contribuer_au_second_membre (DoubleTab & resu) const inline override virtual
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
Definition at line 117 of file Op_Diff_VEF_Anisotrope_Face.h.
{
  contribue_au_second_membre(resu);
}
References contribue_au_second_membre().
cree_instance()
Objet_U * Op_Diff_VEF_Anisotrope_Face::cree_instance () static
Definition at line 36 of file Op_Diff_VEF_Anisotrope_Face.cpp.
diffusivite()
const Champ_base & Op_Diff_VEF_Anisotrope_Face::diffusivite () const override virtual
Implements Operateur_Diff_base.
Definition at line 63 of file Op_Diff_VEF_Anisotrope_Face.cpp.
{
  return diffusivite_.valeur();
}
References diffusivite_, and Ref_Champ_base::valeur().
dimensionner()
void Op_Diff_VEF_Anisotrope_Face::dimensionner (Matrice_Morse & matrice) const inline override virtual
on dimensionne notre matrice.
Reimplemented from Operateur_base.
Definition at line 89 of file Op_Diff_VEF_Anisotrope_Face.h.
{
  Op_VEF_Face::dimensionner(la_zone_vef.valeur(), la_zcl_vef.valeur(), matrice);
}
References Op_VEF_Face::dimensionner(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
duplique()
int Op_Diff_VEF_Anisotrope_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 36 of file Op_Diff_VEF_Anisotrope_Face.cpp.
get_info()
const Type_info * Op_Diff_VEF_Anisotrope_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Definition at line 36 of file Op_Diff_VEF_Anisotrope_Face.cpp.
info()
const Type_info * Op_Diff_VEF_Anisotrope_Face::info () static
Definition at line 36 of file Op_Diff_VEF_Anisotrope_Face.cpp.
modifier_pour_Cl()
void Op_Diff_VEF_Anisotrope_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 94 of file Op_Diff_VEF_Anisotrope_Face.h.
{
  Op_VEF_Face::modifier_pour_Cl(la_zone_vef.valeur(),la_zcl_vef.valeur(), matrice, secmem);
}
References Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Op_VEF_Face::modifier_pour_Cl(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
printOn()
Sortie & Op_Diff_VEF_Anisotrope_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Diff_base.
Definition at line 40 of file Op_Diff_VEF_Anisotrope_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Diff_VEF_Anisotrope_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Diff_base.
Definition at line 46 of file Op_Diff_VEF_Anisotrope_Face.cpp.
{
  return s ;
}
self_cast() [1/2]
const Op_Diff_VEF_Anisotrope_Face & Op_Diff_VEF_Anisotrope_Face::self_cast (const Objet_U & r) static
Definition at line 36 of file Op_Diff_VEF_Anisotrope_Face.cpp.
self_cast() [2/2]
Op_Diff_VEF_Anisotrope_Face & Op_Diff_VEF_Anisotrope_Face::self_cast (Objet_U & r) static
Definition at line 36 of file Op_Diff_VEF_Anisotrope_Face.cpp.
taille_memoire()
unsigned Op_Diff_VEF_Anisotrope_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 36 of file Op_Diff_VEF_Anisotrope_Face.cpp.
verifier()
void Op_Diff_VEF_Anisotrope_Face::verifier () const
Definition at line 954 of file Op_Diff_VEF_Anisotrope_Face.cpp.
{
  static int testee=0;
  if(testee)
    return;
  testee=1;
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
// const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
// const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const DoubleVect& volumes_entrelaces = zone_VEF.volumes_entrelaces();
  const DoubleTab& xv=zone_VEF.xv();
  DoubleTab vit(equation().inconnue().valeurs());
  DoubleTab resu(vit);
  int i, comp;
  if(dimension==2)
    {
      const int nbf = vit.dimension(0);
      Cerr << " Verification de delta(x,0) " << finl;
      for(i=0; i<nbf; i++)
        {
          vit(i,0)=xv(i,0);
          vit(i,1)=0;
        }
      calculer(vit, resu);
      for(i=0; i<nbf; i++)
        for(comp=0; comp<dimension; comp++)
          resu(i,comp)/=(volumes_entrelaces(i));
      for(i=0; i<nbf; i++)
        {
          if(std::fabs(resu(i,0))>1.e-10)
            {
              Cerr << " delta(x,0) ("<<i<<") = "
                   << resu(i,0);
              Cerr << finl;
            }
        }
      Cerr << " Verification de delta(y(1-y),0) " << finl;
      for(i=0; i<nbf; i++)
        {
          vit(i,0)=xv(i,1)*(1-xv(i,1));
          vit(i,1)=0;
        }
      calculer(vit, resu);
      for(i=0; i<nbf; i++)
        for(comp=0; comp<dimension; comp++)
          resu(i,comp)/=(volumes_entrelaces(i));
      for(i=0; i<nbf; i++)
        {
          if(std::fabs(2-resu(i,0))>1.e-10)
            {
              Cerr << " delta(y(1-y),0) ("<<i<<") = "
                   << resu(i,0);
              Cerr << finl;
            }
        }
    }
}
References calculer(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), finl, Op_Diff_VEF_base::la_zone_vef, Ref_Zone_VEF::valeur(), Zone_VF::volumes_entrelaces(), and Zone_VF::xv().
Member Data Documentation
diffusivite_
Ref_Champ_base Op_Diff_VEF_Anisotrope_Face::diffusivite_ protected
Definition at line 81 of file Op_Diff_VEF_Anisotrope_Face.h.
Referenced by associer_diffusivite(), and diffusivite().
info_obj
const Type_info Op_Diff_VEF_Anisotrope_Face::info_obj static
Definition at line 35 of file Op_Diff_VEF_Anisotrope_Face.h.
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Diff_VEF_Anisotrope_Face.h
src/VEF/Operateurs/Op_Diff_VEF_Anisotrope_Face.cpp