TRUST: Schema_Adams_Moulton_order_3 Class Reference
Schema_Adams_Moulton_order_3 Class Reference
#include <Schema_Adams_Moulton_order_3.h>
Public Member Functions
Schema_Adams_Moulton_order_3 ()
class Schema_Adams_Moulton_order_3
~Schema_Adams_Moulton_order_3 ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int nb_valeurs_temporelles () const
Renvoie le nombre de valeurs temporelles a conserver.
3 valeurs temporelles : tn-1, tn, tn+1
1 valeur de plus pour le fonctionnement des algorithmes de l'implicite.
int nb_valeurs_passees () const
int nb_pas_dt_seuil () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Schema_Adams_Moulton_order_3 & self_cast (Objet_U &)
static const
Schema_Adams_Moulton_order_3 & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
virtual Entree & readOn (Entree &)
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
void compute_adams_moulton_coefficients (double time_step, const DoubleTab &times) const
Detailed Description
Definition at line 36 of file Schema_Adams_Moulton_order_3.h.
Constructor & Destructor Documentation
Schema_Adams_Moulton_order_3::Schema_Adams_Moulton_order_3 ()
class Schema_Adams_Moulton_order_3
Definition at line 40 of file Schema_Adams_Moulton_order_3.cpp.
Schema_Adams_Moulton_order_3::~Schema_Adams_Moulton_order_3 ()
Definition at line 40 of file Schema_Adams_Moulton_order_3.cpp.
Member Function Documentation
void Schema_Adams_Moulton_order_3::compute_adams_moulton_coefficients (double time_step, const DoubleTab & times) const [protected, virtual]
Implements Schema_Adams_Moulton_base.
Definition at line 100 of file Schema_Adams_Moulton_order_3.cpp.
References Schema_Adams_Moulton_base::adams_moulton_coefficients_, Cerr, Schema_Implicite_Multi_TimeStep_base::facsec_max_, Schema_Temps_base::facteur_securite_pas(), finl, integrate_lagrangian_basis(), Schema_Temps_base::limpr(), Schema_Temps_base::nb_pas_dt(), Array_base::NOCOPY_NOINIT, DoubleTab::resize(), and ArrOfDouble::size_array().
{
  if (nb_pas_dt()<100 && limpr() && (facteur_securite_pas()>1.0 || facsec_max_>1.0))
    {
      Cerr << finl;
      Cerr << "********************* Warning (printed only on the first 100 time steps) ************************"<< finl;
      Cerr << "The Adams Moulton order 3 scheme is recommended with a facsec and facsec_max set to 1.0 or lower."<< finl;
      Cerr << "*************************************************************************************************"<< finl;
// See $TRUST_ROOT/tests/Reference/Schema_Adams_Moulton_order_3 test case.
    }
  assert(times.size_array() == 3); //past, present and future times, stored in ascending order inside "times" table
  if ( adams_moulton_coefficients_.size_array() != 3)
    {
      adams_moulton_coefficients_.resize(3,Array_base::NOCOPY_NOINIT);
    }
  double past_time    = times[0];
  double present_time = times[1];
  double future_time  = times[2];
  adams_moulton_coefficients_[0] = integrate_lagrangian_basis(present_time,future_time,past_time,present_time,future_time);
  adams_moulton_coefficients_[1] = integrate_lagrangian_basis(past_time,future_time,present_time,present_time,future_time);
  adams_moulton_coefficients_[2] = 1 -  adams_moulton_coefficients_[1] -  adams_moulton_coefficients_[0];
}
Objet_U * Schema_Adams_Moulton_order_3::cree_instance () [static]
Definition at line 40 of file Schema_Adams_Moulton_order_3.cpp.
int Schema_Adams_Moulton_order_3::duplique () const [virtual]
Implements Schema_Adams_Moulton_base.
Definition at line 40 of file Schema_Adams_Moulton_order_3.cpp.
const Type_info * Schema_Adams_Moulton_order_3::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Adams_Moulton_base.
Definition at line 40 of file Schema_Adams_Moulton_order_3.cpp.
const Type_info * Schema_Adams_Moulton_order_3::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Adams_Moulton_base.
Definition at line 40 of file Schema_Adams_Moulton_order_3.cpp.
int Schema_Adams_Moulton_order_3::nb_pas_dt_seuil () const [virtual]
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 95 of file Schema_Adams_Moulton_order_3.cpp.
{
  return 1;
}
int Schema_Adams_Moulton_order_3::nb_valeurs_passees () const [virtual]
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 90 of file Schema_Adams_Moulton_order_3.cpp.
{
  return 1;
}
int Schema_Adams_Moulton_order_3::nb_valeurs_temporelles () const [virtual]
Renvoie le nombre de valeurs temporelles a conserver.
3 valeurs temporelles : tn-1, tn, tn+1
1 valeur de plus pour le fonctionnement des algorithmes de l'implicite.
Implements Schema_Temps_base.
Definition at line 85 of file Schema_Adams_Moulton_order_3.cpp.
{
  return 4 ;
}
Sortie & Schema_Adams_Moulton_order_3::printOn (Sortie & os) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Schema_Adams_Moulton_base.
Definition at line 46 of file Schema_Adams_Moulton_order_3.cpp.
{
  return  Schema_Adams_Moulton_base::printOn(s);
}
Entree & Schema_Adams_Moulton_order_3::readOn (Entree & is) [protected, virtual]
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Schema_Adams_Moulton_base.
Definition at line 54 of file Schema_Adams_Moulton_order_3.cpp.
{
  return Schema_Adams_Moulton_base::readOn(s);
}
const Schema_Adams_Moulton_order_3 & Schema_Adams_Moulton_order_3::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Schema_Adams_Moulton_base.
Definition at line 40 of file Schema_Adams_Moulton_order_3.cpp.
Schema_Adams_Moulton_order_3 & Schema_Adams_Moulton_order_3::self_cast (Objet_U & r) [static]
Reimplemented from Schema_Adams_Moulton_base.
Definition at line 40 of file Schema_Adams_Moulton_order_3.cpp.
unsigned Schema_Adams_Moulton_order_3::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 40 of file Schema_Adams_Moulton_order_3.cpp.
Member Data Documentation
const Type_info Schema_Adams_Moulton_order_3::info_obj [static]
Reimplemented from Schema_Adams_Moulton_base.
Definition at line 39 of file Schema_Adams_Moulton_order_3.h.
The documentation for this class was generated from the following files:
src/Kernel/Schemas_Temps/Schema_Adams_Moulton_order_3.h
src/Kernel/Schemas_Temps/Schema_Adams_Moulton_order_3.cpp