TRUST: Pred_Cor Class Reference
Pred_Cor Class Reference
class Pred_Cor
Le schema doit etre utilise avec un schema d'espace alternant
#include <Pred_Cor.h>
Public Member Functions
Pred_Cor ()
~Pred_Cor ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int nb_valeurs_temporelles () const
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n et n+1, donc 2.
virtual int nb_valeurs_futures () const
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1, donc 1.
virtual double temps_futur (int i) const
Renvoie le le temps a la i-eme valeur future.
Ici : t(n+1)
virtual double temps_defaut () const
Renvoie le le temps le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : t(n+1)
virtual int faire_un_pas_de_temps_eqn_base (Equation_base &)
void completer ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Pred_Cor & self_cast (Objet_U &)
static const Pred_Cor & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
virtual Entree & readOn (Entree &)
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
Detailed Description
class Pred_Cor
Le schema doit etre utilise avec un schema d'espace alternant
Definition at line 40 of file Pred_Cor.h.
Constructor & Destructor Documentation
Pred_Cor::Pred_Cor ()
Definition at line 26 of file Pred_Cor.cpp.
Pred_Cor::~Pred_Cor ()
Definition at line 26 of file Pred_Cor.cpp.
Member Function Documentation
void Pred_Cor::completer (void) [inline, virtual]
Implements Schema_Temps_base.
Definition at line 68 of file Pred_Cor.h.
{
}
Objet_U * Pred_Cor::cree_instance () [static]
Definition at line 26 of file Pred_Cor.cpp.
int Pred_Cor::duplique () const [virtual]
Implements Schema_Temps_base.
Definition at line 26 of file Pred_Cor.cpp.
int Pred_Cor::faire_un_pas_de_temps_eqn_base (Equation_base & eqn) [virtual]
Implements Schema_Temps_base.
Definition at line 94 of file Pred_Cor.cpp.
References Champ_Inc::avancer(), Equation_base::derivee_en_temps_inco(), Schema_Temps_base::dt_, DoubleVect::echange_espace_virtuel(), Champ_Inc::futur(), Zone_Cl_dis::imposer_cond_lim(), Equation_base::inconnue(), Schema_Temps_base::pas_de_temps(), Champ_Inc::reculer(), Schema_Temps_base::temps_courant(), Schema_Temps_base::update_critere_statio(), Champ_Inc::valeurs(), and Equation_base::zone_Cl_dis().
{
  DoubleTab& xi=eqn.inconnue().valeurs();
  DoubleTab& xipls1=eqn.inconnue().futur();
  DoubleTab dudt(xi);
// Etape PREDICTOR
  eqn.zone_Cl_dis()->imposer_cond_lim(eqn.inconnue(),temps_courant()+pas_de_temps());
// On tourne la roue pour que les operateurs utilisent les champs au temps futur
  eqn.inconnue().avancer();
  eqn.derivee_en_temps_inco(dudt);
// Xi+1=Xi+dt_*dX/dt(Xi)
  xipls1 = dudt;
  xipls1 *= dt_;
  xipls1 += xi;
  xipls1.echange_espace_virtuel();
// Etape CORRECTOR
  DoubleTab dudtpls1(xipls1);
  eqn.derivee_en_temps_inco(dudtpls1);
  eqn.inconnue().reculer();
  dudtpls1 += dudt;
  dudtpls1 *= 0.5;
// Xi+1=Xi+dt_*0.5*(dX/dt(Xi)+dX/dt(Xi+1))
  xipls1  = dudtpls1 ;
  xipls1  *= dt_;
  xipls1  += xi ;
  eqn.zone_Cl_dis()->imposer_cond_lim(eqn.inconnue(),temps_courant()+pas_de_temps());
  update_critere_statio(dudtpls1, eqn);
  return 1;
}
const Type_info * Pred_Cor::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 26 of file Pred_Cor.cpp.
const Type_info * Pred_Cor::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 26 of file Pred_Cor.cpp.
int Pred_Cor::nb_valeurs_futures () const [virtual]
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1, donc 1.
Implements Schema_Temps_base.
Definition at line 64 of file Pred_Cor.cpp.
{
  return 1 ;
}
int Pred_Cor::nb_valeurs_temporelles () const [virtual]
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n et n+1, donc 2.
Implements Schema_Temps_base.
Definition at line 56 of file Pred_Cor.cpp.
{
  return 2 ;
}
Sortie & Pred_Cor::printOn (Sortie & os) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 32 of file Pred_Cor.cpp.
{
  return  Schema_Temps_base::printOn(s);
}
Entree & Pred_Cor::readOn (Entree & is) [protected, virtual]
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 40 of file Pred_Cor.cpp.
{
  return Schema_Temps_base::readOn(s) ;
}
const Pred_Cor & Pred_Cor::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Schema_Temps_base.
Definition at line 26 of file Pred_Cor.cpp.
Pred_Cor & Pred_Cor::self_cast (Objet_U & r) [static]
Reimplemented from Schema_Temps_base.
Definition at line 26 of file Pred_Cor.cpp.
unsigned Pred_Cor::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Pred_Cor.cpp.
double Pred_Cor::temps_defaut () const [virtual]
Renvoie le le temps le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : t(n+1)
Implements Schema_Temps_base.
Definition at line 82 of file Pred_Cor.cpp.
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
{
  return temps_courant()+pas_de_temps();
}
double Pred_Cor::temps_futur (int i) const [virtual]
Renvoie le le temps a la i-eme valeur future.
Ici : t(n+1)
Implements Schema_Temps_base.
Definition at line 72 of file Pred_Cor.cpp.
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
{
  assert(i==1);
  return temps_courant()+pas_de_temps();
}
Member Data Documentation
const Type_info Pred_Cor::info_obj [static]
Reimplemented from Schema_Temps_base.
Definition at line 43 of file Pred_Cor.h.
The documentation for this class was generated from the following files:
src/Kernel/Schemas_Temps/Pred_Cor.h
src/Kernel/Schemas_Temps/Pred_Cor.cpp