TRUST: Extraire_plan Class Reference
Extraire_plan Class Reference
Classe Extraire_plan
Lecture d'un fichier.
#include <Extraire_plan.h>
Public Member Functions
Extraire_plan ()
~Extraire_plan ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
Fonction principale de l'interprete.
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Extraire_plan & self_cast (Objet_U &)
static const Extraire_plan & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Protected Member Functions inherited from Interprete_geometrique_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Classe Extraire_plan
Lecture d'un fichier.
Definition at line 37 of file Extraire_plan.h.
Constructor & Destructor Documentation
Extraire_plan()
Extraire_plan::Extraire_plan ()
Definition at line 27 of file Extraire_plan.cpp.
~Extraire_plan()
Extraire_plan::~Extraire_plan ()
Definition at line 27 of file Extraire_plan.cpp.
Member Function Documentation
cree_instance()
Objet_U * Extraire_plan::cree_instance () static
Definition at line 27 of file Extraire_plan.cpp.
duplique()
int Extraire_plan::duplique () const override virtual
Implements Objet_U.
Definition at line 27 of file Extraire_plan.cpp.
get_info()
const Type_info * Extraire_plan::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 27 of file Extraire_plan.cpp.
info()
const Type_info * Extraire_plan::info () static
Definition at line 27 of file Extraire_plan.cpp.
interpreter_()
Entree & Extraire_plan::interpreter_ (Entree & is) override virtual
Fonction principale de l'interprete.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Implements Interprete_geometrique_base.
Definition at line 98 of file Extraire_plan.cpp.
{
  Nom nom_pb;
  Nom nom_dom;
  ArrOfDouble origine,point1,point2,point3;
  int triangle;
  double epaisseur;
  Param param(que_suis_je());
  param.ajouter("domaine",&nom_dom,Param::REQUIRED);
  param.ajouter("probleme",&nom_pb,Param::REQUIRED);
  param.ajouter("origine",&origine,Param::REQUIRED);
  param.ajouter("point1",&point1,Param::REQUIRED);
  param.ajouter("point2",&point2,Param::REQUIRED);
  param.ajouter("point3",&point3);
  param.ajouter_flag("triangle",&triangle);
  param.ajouter("epaisseur",&epaisseur,Param::REQUIRED);
  int via_extraire_surface=0, inverse_condition_element;
  param.ajouter_flag("via_extraire_surface",&via_extraire_surface);
  param.ajouter_flag("inverse_condition_element",&inverse_condition_element);
  Noms bords;
  param.ajouter("avec_certains_bords_pour_extraire_surface",&bords);
  param.lire_avec_accolades_depuis(is);
  associer_domaine(nom_dom);
  if (point3.size_array()==0)
    {
      point3.resize_array(3);
      for (int dir=0; dir<3; dir++)
        if (triangle)
          point3[dir]=(point1[dir]+point2[dir])/2.;
        else
          point3[dir]=point1[dir]+point2[dir]-origine[dir];
    }
  if (via_extraire_surface)
    {
// determination de la normale
      ArrOfDouble normal(3);
      calcul_normal_norme(origine,point1,point2,normal);
      double dx=0;
      for (int dir=0; dir<3; dir++)
        dx+=normal[dir]*origine[dir];
      Noms axes(3);
      axes[0]="x";
      axes[1]="y";
      axes[2]="z";
      SChaine out;
      out << " { domaine "<<nom_dom <<" probleme "<<nom_pb <<finl;
      out<<" condition_elements (" <<-dx ;
      for (int dir=0; dir<3; dir++)
        if (normal[dir])
          out<<"+"<<axes[dir]<<"*("<<normal[dir]<<")";
      if (inverse_condition_element)
        out<<")_ge_0"<<finl;
      else
        out<<")_le_0"<<finl;
      out<<" condition_faces (";
      for (int ori=0; ori<2; ori++)
        {
          ArrOfDouble& A=(ori==0?origine:point3);
          ArrOfDouble& D=(ori!=0?origine:point3);
          ArrOfDouble normal2(3),prov(3),zero(3);
          for (int te=0; te<2; te++)
            {
              ArrOfDouble& B=(te==0?point1:point2);
// ArrOfDouble& C=(ori!=0?point1:point2);
              prov=normal;
              prov+=A;
              calcul_normal_norme(A,B,prov,normal2);
// prov=REF;
// prov-=A;
              double dxbis=0;
              double ref=0;
              out<<"((";
              for (int dir=0; dir<3; dir++)
                {
                  dxbis+=normal2[dir]*D[dir];
                  ref+=normal2[dir]*A[dir];
                  if (normal2[dir])
                    out << axes[dir]<<"*("<< normal2[dir]<<")+";
                }
              out<<"("<<-ref<<"))";
// Cout<<"INFO " << dx-ref<<finl;
              if ((dxbis-ref)>0)
                out <<"_ge_0)*";
              else
                out <<"_le_0)*";
            }
        }
      out<<"1)"<<finl;
// out<<" avec_les_bords "<<finl;
      if (bords.size())
        out<<"avec_certains_bords " <<bords<<finl;
      out<<"}" << finl;
      Cout<<" Creation of the plan through Extraire_surface "<< out.get_str()<<finl;;
      EChaine in(out.get_str());
      Extraire_surface extraction;
      extraction.interpreter(in);
// abort();
      return is;
    }
  Domaine& dom=domaine();
// on recupere le pb
  if(! sub_type(Probleme_base, objet(nom_pb)))
    {
      Cerr << nom_pb << " is of type " << objet(nom_pb).que_suis_je() << finl;
      Cerr << "and not of type Probleme_base" << finl;
      exit();
    }
  Probleme_base& pb=ref_cast(Probleme_base, objet(nom_pb));
  const Zone_VF& zone_vf=ref_cast(Zone_VF,pb.equation(0).zone_dis().valeur());
  dom.les_sommets()=zone_vf.zone().domaine().les_sommets();
  const DoubleTab& coord=dom.les_sommets();
  Zone zone__;
  dom.add(zone__);
  Zone& zone=dom.zone(0);
  zone.nommer(dom.le_nom());
  const Nom& type_elem=zone_vf.zone().type_elem().valeur().que_suis_je();
  if (type_elem==Motcle("Tetraedre"))
    zone.typer("Triangle");
  else
    {
      Cerr<<que_suis_je()<<"  not coded for this type of elements "<<finl;
      exit();
    }
  zone.associer_domaine(dom);
// IntTab& les_elems=zone.les_elems();
// creation d'une zone pipo pour pouvoir chercher les faces
  Domaine test;
  ArrOfDouble normal(3);
  {
    Zone prov;
    test.add(prov);
    Zone& zone_test=test.zone(0);
    zone.nommer("NO_FACE");
    if (triangle)
      zone_test.typer("Prisme");
    else
      zone_test.typer("Hexaedre_vef");
    zone_test.associer_domaine(test);
    DoubleTab& somm_hexa=test.les_sommets();
    int nb_som=4;
    if (triangle) nb_som=3;
    somm_hexa.resize(nb_som*2,3);
    for (int dir=0; dir<3; dir++)
      {
        somm_hexa(0,dir)=origine[dir];
        somm_hexa(1,dir)=point1[dir];
        somm_hexa(2,dir)=point2[dir];
        somm_hexa(3,dir)=point3[dir];
        for (int t=0; t<nb_som; t++)
          somm_hexa(t+nb_som,dir)=somm_hexa(t,dir);
      }
// il faut maintenant epaissir l'hexa dans la direction normale
    calcul_normal_norme(origine,point1,point2,normal);
    double d_epaisseur=epaisseur/2.;
    for (int t=0; t<nb_som; t++)
      for (int dir=0; dir<3; dir++)
        {
          somm_hexa(t,dir)=somm_hexa(t,dir)-d_epaisseur*normal[dir];
          somm_hexa(nb_som+t,dir)=somm_hexa(nb_som+t,dir)+d_epaisseur*normal[dir];
        }
    IntTab& elem_test=zone_test.les_elems();
    elem_test.resize(1,nb_som*2);
    for (int s=0; s<nb_som*2; s++) elem_test(0,s)=s;
    /*
      SFichier es("hex.geom");
      es<<test;
    */
  }
  Zone& zone_test=test.zone(0);
  const DoubleTab& xv =zone_vf.xv();
  int nbfaces=zone_vf.nb_faces();
  ArrOfInt marq(nbfaces);
// on marque les joints
// const Joints& joints=zone_vf.face_joints();
  int nbjoints=zone_vf.nb_joints();
  for(int njoint=0; njoint<nbjoints; njoint++)
    {
      const Joint& joint_temp = zone_vf.joint(njoint);
      int pe_voisin=joint_temp.PEvoisin();
      if (pe_voisin<me())
        {
          const IntTab& indices_faces_joint = joint_temp.joint_item(Joint::FACE).renum_items_communs();
          const int nb_faces_j = indices_faces_joint.dimension(0);
          for (int j = 0; j < nb_faces_j; j++)
            {
              int face_de_joint = indices_faces_joint(j, 1);
              marq[face_de_joint] = -1;
            }
        }
    }
  int nb_t=0;
  for (int fac=0; fac<nbfaces; fac++)
    {
      if (zone_test.chercher_elements(xv(fac,0),xv(fac,1),xv(fac,2))==0)
        if (marq[fac]!=-1)
          {
// tester si item_commun....
            marq[fac]=1;
            nb_t++;
          }
    }
  ArrOfDouble point0b(3),point1b(3),point2b(3);
  Cerr<<"Number of elements of the new domain "<<nb_t<<finl;
  IntTab& les_elems=zone.les_elems();
  les_elems.resize(nb_t,3);
  const IntTab& face_sommets=zone_vf.face_sommets();
  int nb=0;
  for (int fac=0; fac<nbfaces; fac++)
    if (marq[fac]==1)
      {
        Cerr<<fac <<" ";
        for (int s=0; s<3; s++)
          les_elems(nb,s)=face_sommets(fac,s);
// on calcule la normale
        ArrOfDouble normal_b(3);
        for (int i=0; i<3; i++)
          {
            point0b[i]=coord(les_elems(nb,0),i);
            point1b[i]=coord(les_elems(nb,1),i);
            point2b[i]=coord(les_elems(nb,2),i);
          }
        calcul_normal(point0b,point1b,point2b,normal_b);
        if (dotproduct_array(normal,normal_b)<0)
          {
// si normal a l'envers on inverse les deux sommets
            les_elems(nb,1)=face_sommets(fac,2);
            les_elems(nb,2)=face_sommets(fac,1);
          }
        nb++;
      }
  Cerr<<finl;;
  assert(nb==nb_t);
  NettoieNoeuds::nettoie(dom);
  return is;
}
References Domaine::add(), Param::ajouter(), Param::ajouter_flag(), Zone::associer_domaine(), Interprete_geometrique_base::associer_domaine(), calcul_normal(), calcul_normal_norme(), Cerr, Zone::chercher_elements(), Cout, TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), Interprete_geometrique_base::domaine(), dotproduct_array(), Probleme_base::equation(), Process::exit(), Joint::FACE, Zone_VF::face_sommets(), finl, SChaine::get_str(), Interprete_geometrique_base::interpreter(), Zone_VF::joint(), Joint::joint_item(), Domaine::le_nom(), Zone::les_elems(), Domaine::les_sommets(), Param::lire_avec_accolades_depuis(), Process::me(), Zone_VF::nb_faces(), Zone_VF::nb_joints(), NettoieNoeuds::nettoie(), Zone::nommer(), Interprete::objet(), Joint::PEvoisin(), Objet_U::que_suis_je(), ref_cast, Joint_Items::renum_items_communs(), Param::REQUIRED, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), sub_type, test(), Zone::type_elem(), type_elem(), Zone::typer(), Deriv_Zone_dis_base::valeur(), Deriv_Elem_geom_base::valeur(), Zone_VF::xv(), zero(), Zone_dis_base::zone(), Domaine::zone(), and Equation_base::zone_dis().
printOn()
Sortie & Extraire_plan::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 43 of file Extraire_plan.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Extraire_plan::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 62 of file Extraire_plan.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Extraire_plan & Extraire_plan::self_cast (const Objet_U & r) static
Definition at line 27 of file Extraire_plan.cpp.
self_cast() [2/2]
Extraire_plan & Extraire_plan::self_cast (Objet_U & r) static
Definition at line 27 of file Extraire_plan.cpp.
taille_memoire()
unsigned Extraire_plan::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 27 of file Extraire_plan.cpp.
Member Data Documentation
info_obj
const Type_info Extraire_plan::info_obj static
Definition at line 39 of file Extraire_plan.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Extraire_plan.h
src/Kernel/Geometrie/Extraire_plan.cpp