TRUST: List_Nom Class Reference
List_Nom Class Reference
#include <List_Nom.h>
Public Member Functions
List_Nom ()
~List_Nom ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
List_Nom (const Nom &t)
List_Nom (const List_Nom &t)
Nom & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Nom & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Nom & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Nom & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Nom & operator() (int i)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Nom & operator() (int i) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Nom & operator() (const Nom &n)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Nom & operator() (const Nom &n) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Nom & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Nom & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
List_Nom & operator= (const Nom &t)
Nom * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
List_Nom & operator= (const List_Nom &)
List_Nom & add (const List_Nom &)
Nom & add (const Nom &)
List_Nom & inserer (const List_Nom &)
Nom & inserer (const Nom &)
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
List_Nom & operator+= (const List_Nom &)
List_Nom & operator+= (const Nom &)
Nom & add_if_not (const Nom &)
Nom & add_if_not (const char *const)
List_Nom & search (const Nom &) const
List_Nom & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
List_Nom & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
const List_Nom & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
const List_Nom & dernier () const
Renvoie le dernier element de la liste.
List_Nom & dernier ()
Renvoie le dernier element de la liste.
List_Nom & operator-= (const Nom &)
int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
int contient (const Nom &) const
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
int rang (const Nom &) const
void suppr (const Nom &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static List_Nom & self_cast (Objet_U &)
static const List_Nom & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture d'une liste sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'une liste sur un flot d'entree.
int est_egal_a (const List_Nom &) const
Detailed Description
Definition at line 27 of file List_Nom.h.
Constructor & Destructor Documentation
List_Nom::List_Nom ()
Definition at line 29 of file Interprete.cpp.
List_Nom::~List_Nom ()
Definition at line 29 of file Interprete.cpp.
List_Nom::List_Nom (const Nom & t) [inline]
Definition at line 27 of file List_Nom.h.
List_Nom::List_Nom (const List_Nom & t) [inline]
Definition at line 27 of file List_Nom.h.
Member Function Documentation
List_Nom & List_Nom::add (const List_Nom & a_list) [inline]
Definition at line 27 of file List_Nom.h.
Referenced by Param::ajouter_condition(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_moreqn(), Postraitement::creer_champ_post_stat(), Probleme_base::init_postraitements(), Zone::Lire_Bords_a_imprimer(), Zone::Lire_Bords_a_imprimer_sum(), Postraitement::lire_champs_a_postraiter(), Mod_turb_hyd_base::lire_motcle_non_standard(), Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), Param::lire_sans_accolade(), Postraitement::lire_tableaux_a_postraiter(), Param::read(), and Objet_a_lire::set_name().
Nom & List_Nom::add (const Nom & t) [inline]
Definition at line 27 of file List_Nom.h.
Nom & List_Nom::add_if_not (const Nom & t) [inline]
Definition at line 27 of file List_Nom.h.
Referenced by Postraitement::creer_champ_post().
Nom & List_Nom::add_if_not (const char * const t) [inline]
Definition at line 27 of file List_Nom.h.
int List_Nom::contient (const Nom & t) const [inline]
Definition at line 27 of file List_Nom.h.
Referenced by Param::check(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_moreqn(), Postraitement::creer_champ_post_stat(), Op_VEF_Face::impr(), Op_Grad_VDF_Face::impr(), T_It_VDF_Face< _TYPE_ >::impr(), Op_Grad_PolyMAC_Face::impr(), Op_Diff_PolyMAC_base::impr(), T_It_PolyMAC_Elem< _TYPE_ >::impr(), Op_Grad_VEF_P1B_Face::impr(), Op_Grad_EF::impr(), Op_EF_base::impr(), Op_Diff_CoviMAC_base::impr(), Postraitement::lire_champs_a_postraiter(), and Operateur_base::ouvrir_fichier().
int List_Nom::contient (const char * const ch) const [inline]
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
Returns:
int
Signification: 1 si la liste contient un Objet_U de Nom ch, 0 sinon
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
Objet_U * List_Nom::cree_instance () [static]
Reimplemented from liste.
Definition at line 29 of file Interprete.cpp.
const List_Nom& List_Nom::dernier () const [inline]
Renvoie le dernier element de la liste.
Returns:
const liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented from liste.
List_Nom & List_Nom::dernier () [inline]
Renvoie le dernier element de la liste.
Returns:
liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
int List_Nom::duplique () const [virtual]
Reimplemented from liste.
Definition at line 29 of file Interprete.cpp.
int List_Nom::est_egal_a (const Objet_U & x) const [virtual]
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
Reimplemented from Objet_U.
Definition at line 29 of file Interprete.cpp.
int List_Nom::est_egal_a (const List_Nom &) const [inline, protected]
const Type_info * List_Nom::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from liste.
Definition at line 29 of file Interprete.cpp.
const Type_info * List_Nom::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from liste.
Definition at line 29 of file Interprete.cpp.
List_Nom & List_Nom::inserer (const List_Nom & a_list) [inline]
Definition at line 27 of file List_Nom.h.
Nom & List_Nom::inserer (const Nom & t) [inline]
Definition at line 27 of file List_Nom.h.
const Nom & List_Nom::operator() (const Nom & nom) const [inline]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
Nom & List_Nom::operator() (const Nom & nom) [inline]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
const Nom & List_Nom::operator() (int i) const [inline]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
Nom & List_Nom::operator() (int i) [inline]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
List_Nom & List_Nom::operator+= (const Nom & t) [inline]
Definition at line 27 of file List_Nom.h.
List_Nom & List_Nom::operator+= (const List_Nom & a_list) [inline]
Definition at line 27 of file List_Nom.h.
List_Nom & List_Nom::operator-= (const Nom & t) [inline]
Definition at line 27 of file List_Nom.h.
Nom * List_Nom::operator-> () [inline]
Retourne un pointeur sur l'Objet_U premier element de la liste.
Returns:
Objet_U*
Signification: pointeur sur l'Objet_U premier element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
List_Nom & List_Nom::operator= (const Nom & t) [inline]
Definition at line 27 of file List_Nom.h.
List_Nom & List_Nom::operator= (const List_Nom & a_list) [inline]
Definition at line 27 of file List_Nom.h.
Nom & List_Nom::operator[] (int i) [inline]
Operateur d'acces au ieme element de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
Nom & List_Nom::operator[] (const Nom & nom) [inline]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
const Nom & List_Nom::operator[] (const Nom & nom) const [inline]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
const Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
const Nom & List_Nom::operator[] (int i) const [inline]
Operateur d'acces au ieme element de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
Sortie & List_Nom::printOn (Sortie & os) const [protected, virtual]
Ecriture d'une liste sur un flot de sortie.
Returns:
Sortie&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from liste.
Definition at line 29 of file Interprete.cpp.
int List_Nom::rang (const Nom & t) const [inline]
Definition at line 27 of file List_Nom.h.
Referenced by Probleme_base::init_postraitements(), Parametre_implicite::readOn(), and Param::supprimer_condition().
Entree & List_Nom::readOn (Entree & is) [protected, virtual]
Lecture d'une liste sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from liste.
Definition at line 29 of file Interprete.cpp.
List_Nom & List_Nom::search (const Nom & t) const [inline]
Definition at line 27 of file List_Nom.h.
List_Nom & List_Nom::search (const char * const ch) const [inline]
Recherche d'un Objet_U de Nom ch dans la liste.
Returns:
liste&
Signification: L'element de la liste trouve
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
const List_Nom & List_Nom::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from liste.
Definition at line 29 of file Interprete.cpp.
List_Nom & List_Nom::self_cast (Objet_U & r) [static]
Reimplemented from liste.
Definition at line 29 of file Interprete.cpp.
const List_Nom & List_Nom::suivant () const [inline]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
const liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
List_Nom & List_Nom::suivant () [inline]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
void List_Nom::suppr (const Nom & t) [inline]
Definition at line 27 of file List_Nom.h.
Referenced by Param::supprimer_condition().
void List_Nom::supprimer () [inline]
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
unsigned List_Nom::taille_memoire () const [virtual]
Reimplemented from liste.
Definition at line 29 of file Interprete.cpp.
const Nom & List_Nom::valeur () const [inline]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
const Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
Nom & List_Nom::valeur () [inline]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
Member Data Documentation
const Type_info List_Nom::info_obj [static]
Reimplemented from liste.
Definition at line 27 of file List_Nom.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/List_Nom.h
src/Kernel/Utilitaires/Interprete.cpp