TRUST: interface_CALCULBIJ Class Reference
interface_CALCULBIJ Class Reference
#include <interface_CALCULBIJ.h>
Public Member Functions
void initialiser_les_commons ()
void init ()
void init_sans_initialiser_les_commons ()
void check_common ()
void compare_common ()
void set_param (Param &)
void dump (Sortie &)
void init_from_common ()
void init_from_file (const Nom &)
void Compute (const int nbnn, const int nbsomtot, const ArrOfDouble &xl, const ArrOfInt &num, ArrOfDouble &bij, const ArrOfDouble &poro, const int ip, const int npgau, const ArrOfDouble &xgau, const ArrOfDouble &frgau, const ArrOfDouble &dfrgau, const ArrOfDouble &poigau, ArrOfDouble &detj, ArrOfDouble &ajm1, ArrOfDouble &aj, ArrOfDouble &df, double &volume, ArrOfDouble &volume_sommet, ArrOfDouble &iphi) const
Detailed Description
Definition at line 24 of file interface_CALCULBIJ.h.
Member Function Documentation
check_common()
void interface_CALCULBIJ::check_common ()
Definition at line 47 of file interface_CALCULBIJ.cpp.
{
}
compare_common()
void interface_CALCULBIJ::compare_common ()
Definition at line 51 of file interface_CALCULBIJ.cpp.
{
}
Compute()
void interface_CALCULBIJ::Compute (const int nbnn, const int nbsomtot, const ArrOfDouble & xl, const ArrOfInt & num, ArrOfDouble & bij, const ArrOfDouble & poro, const int ip, const int npgau, const ArrOfDouble & xgau, const ArrOfDouble & frgau, const ArrOfDouble & dfrgau, const ArrOfDouble & poigau, ArrOfDouble & detj, ArrOfDouble & ajm1, ArrOfDouble & aj, ArrOfDouble & df, double & volume, ArrOfDouble & volume_sommet, ArrOfDouble & iphi) const
Definition at line 55 of file interface_CALCULBIJ.cpp.
{
  F77NAME(CALCULBIJ)(&nbnn, &nbsomtot,  xl.addr(),  num.addr(),  bij.addr(),  poro.addr(), &ip, &npgau,  xgau.addr(),  frgau.addr(),  dfrgau.addr(),  poigau.addr(),  detj.addr(),  ajm1.addr(),  aj.addr(),  df.addr(), &volume,  volume_sommet.addr(),  iphi.addr());
}
References TRUSTArray< _TYPE_ >::addr(), and F77NAME.
Referenced by Zone_EF::calculer_Bij().
dump()
void interface_CALCULBIJ::dump (Sortie & os)
Definition at line 67 of file interface_CALCULBIJ.cpp.
{
  Param param("interface_CALCULBIJ");
  set_param(param);
  param.print(os);
}
References Param::print(), and set_param().
init()
void interface_CALCULBIJ::init ()
Definition at line 36 of file interface_CALCULBIJ.cpp.
{
  initialiser_les_commons();
  init_sans_initialiser_les_commons();
}
References init_sans_initialiser_les_commons(), and initialiser_les_commons().
init_from_common()
void interface_CALCULBIJ::init_from_common ()
Definition at line 44 of file interface_CALCULBIJ.cpp.
{
}
init_from_file()
void interface_CALCULBIJ::init_from_file (const Nom & nom_fic)
Definition at line 59 of file interface_CALCULBIJ.cpp.
{
  LecFicDiffuse entree(nom_fic);
  Param param("interface_CALCULBIJ");
  set_param(param);
  param.read(entree);
}
References Param::read(), and set_param().
init_sans_initialiser_les_commons()
void interface_CALCULBIJ::init_sans_initialiser_les_commons ()
Definition at line 41 of file interface_CALCULBIJ.cpp.
{
}
Referenced by init().
initialiser_les_commons()
void interface_CALCULBIJ::initialiser_les_commons ()
Definition at line 33 of file interface_CALCULBIJ.cpp.
{
}
Referenced by init().
set_param()
void interface_CALCULBIJ::set_param (Param & param)
Definition at line 74 of file interface_CALCULBIJ.cpp.
{
}
Referenced by dump(), and init_from_file().
The documentation for this class was generated from the following files:
src/EF/fortran/interface_CALCULBIJ.h
src/EF/fortran/interface_CALCULBIJ.cpp