TRUST: OutputCommBuffer Class Reference
OutputCommBuffer Class Reference
:
Classe outil utilisee exclusivement par Schema_Comm. C'est une classe
derivee de Entree dont le stream est de type ostrstream (les donnees
sont ecrites par operator<< dans un buffer en memoire).
On utilise la classe comme suit:
(1) on ecrit des donnees avec operator<< dans le buffer
ouput_comm_buffer << x << y << chaine << ... ;
(2) on recupere l'ensemble des donnees ecrites sous la forme d'un
bloc de memoire contigu de taille "get_buffer_size()" situe
a l'adresse "get_buffer()".
(3) on reinitialise le buffer avec "clear()"
et on peut refaire (1)
#include <OutputCommBuffer.h>
Public Member Functions
OutputCommBuffer ()
~OutputCommBuffer () override
void clear ()
const char * get_buffer ()
int get_buffer_size ()
ostringstream & get_stream ()
Public Member Functions inherited from Sortie
Sortie ()
Sortie (ostream &os)
Sortie (const Sortie &os)
Sortie & operator= (ostream &os)
Sortie & operator= (Sortie &os)
ostream & get_ostream ()
const ostream & get_ostream () const
void set_ostream (ostream *os)
void set_col_width (const int)
Sortie & operator<< (ostream &(*f)(ostream &))
Sortie & operator<< (Sortie &(*f)(Sortie &))
Sortie & operator<< (ios &(*f)(ios &))
virtual Sortie & flush ()
virtual Sortie & lockfile ()
virtual Sortie & unlockfile ()
virtual Sortie & syncfile ()
virtual void setf (std::_Ios_Fmtflags)
virtual void precision (int)
virtual Sortie & operator<< (const Separateur &)
virtual Sortie & operator<< (const Objet_U &ob)
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
virtual Sortie & operator<< (const int ob)
virtual Sortie & operator<< (const unsigned ob)
virtual Sortie & operator<< (const long ob)
virtual Sortie & operator<< (const float ob)
virtual Sortie & operator<< (const double ob)
virtual Sortie & operator<< (const char *ob)
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
virtual Sortie & operator<< (const std::string &str)
virtual int add_col (const double ob)
virtual int add_col (const char *ob)
virtual int put (const unsigned *ob, int n, int nb_colonnes=1)
virtual int put (const int *ob, int n, int nb_colonnes=1)
virtual int put (const float *ob, int n, int nb_colonnes=1)
virtual int put (const double *ob, int n, int nb_colonnes=1)
virtual int put (const long *ob, int n, int nb_colonnes=1)
virtual ~Sortie ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
int is_bin ()
bool has_ostream () const
Private Attributes
ostringstream stream_
std::string string_
Additional Inherited Members
Protected Attributes inherited from Sortie
int bin_
int col_width_
Detailed Description
:
Classe outil utilisee exclusivement par Schema_Comm. C'est une classe
derivee de Entree dont le stream est de type ostrstream (les donnees
sont ecrites par operator<< dans un buffer en memoire).
On utilise la classe comme suit:
(1) on ecrit des donnees avec operator<< dans le buffer
ouput_comm_buffer << x << y << chaine << ... ;
(2) on recupere l'ensemble des donnees ecrites sous la forme d'un
bloc de memoire contigu de taille "get_buffer_size()" situe
a l'adresse "get_buffer()".
(3) on reinitialise le buffer avec "clear()"
et on peut refaire (1)
Definition at line 34 of file OutputCommBuffer.h.
Constructor & Destructor Documentation
OutputCommBuffer()
OutputCommBuffer::OutputCommBuffer ()
Definition at line 18 of file OutputCommBuffer.cpp.
{
  bin_ = 1;
  set_ostream(& stream_);
// Initialisation avec les 2 lignes suivantes car sinon plantage sur PAR_Cx 7 procs sur AIX:
// La STD est specifique sur cette machine
  *this << "";
  stream_.seekp(0);
}
References Sortie::bin_, Sortie::set_ostream(), and stream_.
~OutputCommBuffer()
OutputCommBuffer::~OutputCommBuffer () override
Definition at line 28 of file OutputCommBuffer.cpp.
{
  clear();
  set_ostream(0);
}
References clear(), and Sortie::set_ostream().
Member Function Documentation
clear()
void OutputCommBuffer::clear ()
Definition at line 46 of file OutputCommBuffer.cpp.
{
  stream_.seekp(0);
}
References stream_.
Referenced by Schema_Comm::end_comm(), and ~OutputCommBuffer().
get_buffer()
const char * OutputCommBuffer::get_buffer ()
Definition at line 34 of file OutputCommBuffer.cpp.
{
// Need a copy:
  string_ = stream_.str();
  return string_.c_str();
}
References stream_, and string_.
Referenced by InputCommBuffer::create_stream_from_output_stream(), envoyer_broadcast_buffered_(), and envoyer_buffered_().
get_buffer_size()
int OutputCommBuffer::get_buffer_size ()
Definition at line 41 of file OutputCommBuffer.cpp.
{
  return stream_.tellp();
}
References stream_.
Referenced by InputCommBuffer::create_stream_from_output_stream(), Schema_Comm::echange_messages(), Schema_Comm::echange_taille_et_messages(), envoyer_broadcast_buffered_(), and envoyer_buffered_().
get_stream()
ostringstream & OutputCommBuffer::get_stream () inline
Definition at line 42 of file OutputCommBuffer.h.
  {
    return stream_;
  };
References stream_.
Member Data Documentation
stream_
ostringstream OutputCommBuffer::stream_ private
Definition at line 47 of file OutputCommBuffer.h.
Referenced by clear(), get_buffer(), get_buffer_size(), get_stream(), and OutputCommBuffer().
string_
std::string OutputCommBuffer::string_ private
Definition at line 48 of file OutputCommBuffer.h.
Referenced by get_buffer().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/OutputCommBuffer.h
src/Kernel/Utilitaires/OutputCommBuffer.cpp