TRUST: Evaluateur_Source_VDF Class Reference
Evaluateur_Source_VDF Class Reference
#include <Evaluateur_Source_VDF.h>
Public Member Functions
Evaluateur_Source_VDF ()
virtual ~Evaluateur_Source_VDF ()
Evaluateur_Source_VDF (const Evaluateur_Source_VDF &)
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
virtual double calculer_terme_source (int) const =0
virtual void calculer_terme_source (int, DoubleVect &) const =0
Protected Attributes
Ref_Zone_VDF la_zone
Ref_Zone_Cl_VDF la_zcl
Detailed Description
Definition at line 40 of file Evaluateur_Source_VDF.h.
Constructor & Destructor Documentation
Evaluateur_Source_VDF::Evaluateur_Source_VDF () [inline]
Definition at line 65 of file Evaluateur_Source_VDF.h.
{}
virtual Evaluateur_Source_VDF::~Evaluateur_Source_VDF () [inline, virtual]
Definition at line 46 of file Evaluateur_Source_VDF.h.
{};
Evaluateur_Source_VDF::Evaluateur_Source_VDF (const Evaluateur_Source_VDF & eval) [inline]
Definition at line 67 of file Evaluateur_Source_VDF.h.
  : la_zone(eval.la_zone),la_zcl(eval.la_zcl) {}
Member Function Documentation
void Evaluateur_Source_VDF::associer_zones (const Zone_dis_base & zone_vdf, const Zone_Cl_dis_base & zone_cl_vdf) [inline]
Definition at line 71 of file Evaluateur_Source_VDF.h.
References completer(), la_zcl, la_zone, and ref_cast.
Referenced by Terme_Source_Constituant_VDF_Elem::associer_zones(), Terme_Puissance_Thermique_VDF_Elem::associer_zones(), Terme_Gravite_VDF_Face::associer_zones(), Source_Neutronique_VDF::associer_zones(), Source_Forchheimer_VDF_Face::associer_zones(), Source_Echange_Th_VDF::associer_zones(), Source_Dirac_VDF_Elem::associer_zones(), Source_Darcy_VDF_Face::associer_zones(), and Terme_Puissance_Thermique_QC_VDF_Elem::associer_zones().
{
  la_zone = ref_cast(Zone_VDF,zone_vdf);
  la_zcl = ref_cast(Zone_Cl_VDF,zone_cl_vdf);
  completer();
}
virtual void Evaluateur_Source_VDF::calculer_terme_source (int , DoubleVect &) const [pure virtual]
Implemented in Eval_Puiss_Th_QC_VDF_Elem, Eval_Darcy_VDF_Face, Eval_Dirac_VDF_Elem, Eval_Echange_Himp_VDF_Elem, Eval_Forchheimer_VDF_Face, Eval_Gravite_VDF_Face, Eval_Puiss_Neutr_VDF_Elem, Eval_Puiss_Th_VDF_Elem, and Eval_Source_C_VDF_Elem.
virtual double Evaluateur_Source_VDF::calculer_terme_source (int) const [pure virtual]
Implemented in Eval_Puiss_Th_QC_VDF_Elem, Eval_Darcy_VDF_Face, Eval_Dirac_VDF_Elem, Eval_Echange_Himp_VDF_Elem, Eval_Forchheimer_VDF_Face, Eval_Gravite_VDF_Face, Eval_Puiss_Neutr_VDF_Elem, Eval_Puiss_Th_VDF_Elem, and Eval_Source_C_VDF_Elem.
virtual void Evaluateur_Source_VDF::completer () [pure virtual]
Implemented in Eval_Puiss_Neutr_VDF_Elem, Evaluateur_Source_VDF_Elem, and Evaluateur_Source_VDF_Face.
Referenced by associer_zones().
virtual void Evaluateur_Source_VDF::mettre_a_jour () [pure virtual]
Implemented in Eval_Puiss_Th_QC_VDF_Elem, Eval_Darcy_VDF_Face, Eval_Dirac_VDF_Elem, Eval_Echange_Himp_VDF_Elem, Eval_Forchheimer_VDF_Face, Eval_Gravite_VDF_Face, Eval_Puiss_Neutr_VDF_Elem, Eval_Puiss_Th_VDF_Elem, and Eval_Source_C_VDF_Elem.
Member Data Documentation
Ref_Zone_Cl_VDF Evaluateur_Source_VDF::la_zcl [protected]
Definition at line 57 of file Evaluateur_Source_VDF.h.
Referenced by associer_zones().
Ref_Zone_VDF Evaluateur_Source_VDF::la_zone [protected]
Definition at line 56 of file Evaluateur_Source_VDF.h.
Referenced by Eval_Darcy_VDF_Face::associer(), Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), associer_zones(), Evaluateur_Source_VDF_Face::completer(), Evaluateur_Source_VDF_Elem::completer(), Eval_Dirac_VDF_Elem::mettre_a_jour(), and Eval_Darcy_VDF_Face::mettre_a_jour().
The documentation for this class was generated from the following file:
src/VDF/Sources/Evaluateurs/Evaluateur_Source_VDF.h